### ISSUE TITLE
You may need an appropriate loader to handle this file type. Angular 7

### ISSUE THREAD

**Issue by Adeeljavedvirk** [amcharts/amcharts4#1002]
ERROR in ./node_modules/@amcharts/amcharts4/.internal/core/responsive/Responsive.js 418:15
Module parse failed: Unexpected token (418:15)
You may need an appropriate loader to handle this file type.
|      */
|     Responsive.prototype.loadDefaultRules = function () {
>         return import(/* webpackChunkName: "responsivedefaults" */ "./ResponsiveDefaults");
|     };
|     return Responsive;
ERROR in ./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js 64:24
Module parse failed: Unexpected token (64:24)
You may need an appropriate loader to handle this file type.
|             switch (_a.label) {
|                 case 0: return [4 /*yield*/, Promise.all([
>                         import(/* webpackChunkName: "pdfmake" */ "pdfmake/build/pdfmake.js"),
|                         import(/* webpackChunkName: "pdfmake" */ "../../pdfmake/vfs_fonts")
|                     ])];

----------------------------------------------------------
Getting this error while building the code. 

Imported amcharts 4 lib like : 

import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";
import am4themes_animated from "@amcharts/amcharts4/themes/animated";

**Comment by jimmykane** [comment]
Same here

**Comment by Pauan** [comment]
This is a bug in Webpack, not amCharts.

You can downgrade to Webpack version `4.28.4` to fix it.

Or if that doesn't work, you can try some of the other solutions:

https://github.com/webpack/webpack/issues/8656#issuecomment-456010969

**Comment by BRoy98** [comment]
> This is a bug in Webpack, not amCharts.
> 
> You can downgrade to Webpack version `4.28.4` to fix it.
> 
> Or if that doesn't work, you can try some of the other solutions:
> 
> [webpack/webpack#8656 (comment)](https://github.com/webpack/webpack/issues/8656#issuecomment-456010969)

Having the same issue even after downgrading to Webpack version `4.28.4`. Is anyone getting the same issue?

**Comment by Sam123-7** [comment]
I swapped to yarn to fix the above. Seems npm has some issues with peer dependency resolution.

**Comment by jimmykane** [comment]
Same here! NPM took so long to fix this and I find no reason to use NPM to
be honest (except to install Yarn)

**Comment by BRoy98** [comment]
Oh, Thanks a lot @Sam123-7 @jimmykane ! It fixed the issue.
