### ISSUE TITLE
Poor performance with Gantt chart

### ISSUE THREAD

**Issue by dorsharon** [amcharts/amcharts4#1003]
I have a Gantt chart made of an XYChart with CategoryAxis and DateAxis.
I'm trying to show about 1k-1.5k columns in the column series, and I get a very laggy, almost unusable experience.

Are there any tips or things I should know about to enhance performance?
Is 1.5k columns too much for Amcharts 4?

**Comment by martynasma** [comment]
Can you post your chart as a codepen?

**Comment by dorsharon** [comment]
I can't really attach any actual data, since its been fetched and processed in a remote server, but my config is like in this codepen:
https://codepen.io/anon/pen/JzoPpL

As you can see, in before-data-validated event, I take the passed data and adjust it to the gantt I want to present.

There are some other stuff going on, which is why i asked for tips or tricks instead of giving my config right away, as I think it might be somewhat problematic to analyze...

**Comment by martynasma** [comment]
Any chance of producing a working codepen with data/setup as close as possible to yours?

Without being able to run and test your code/data, we have a huge overhead of figuring out how it works and inventing the data, so what we test might be entirely different then what you actually have.

Not to mention huge overhead of time required for it.

Hope you find it reasonable.
