### ISSUE TITLE
Any way to reduce number of rendered SVG elements in Gantt?

### ISSUE THREAD

**Issue by dorsharon** [amcharts/amcharts4#1008]
I have a gantt that produces ~1.5k columns in a gantt, and it takes a toll on FPS and performance (zooming and panning is laggy).

Any way to set which elements to render and which not to?
For example, at highest zoom out level, some elements are so small, they're barely noticeable, and I'd like to not render them until reaching a sufficient zoom level.
Any way to do that?

**Comment by martynasma** [comment]
No, I'm afraid.
