### ISSUE TITLE
Column tooltip flashing when using XYCursor

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#1009]
I am using an XYCursor to show a grey background and both axis tooltips, but I want the tooltip to be on the invidual columns, not the whole date.

I am not using `series.tooltipText`, but rather `series.columns.template.tooltipText`.

When hovering over a column, I see a flash of a tooltip, but it quickly disappears.

Here's the Codeden demo: https://codepen.io/team/amcharts/pen/86a5cb43b1455b59a6101ec612bd24d8.

How to enable column tooltips while at the same time using XYCursor?

![chrome_nrvt5lterp](https://user-images.githubusercontent.com/13300227/53425043-98c6c180-39e4-11e9-9872-8e0548b985b9.png)

**Comment by martynasma** [comment]
Sorry. Not possible. There's one Tooltip instance per Series, which is used both by cursor and series' elements like column.
