### ISSUE TITLE
Positioning buttons

### ISSUE THREAD

**Issue by promitanan** [amcharts/amcharts4#1011]
Is there a way to put the zoom control and globe buttons to the left side of the map so they don't cover some countries? I've tried changing dx and dy for the buttons but that didn't work.

![image](https://user-images.githubusercontent.com/18385581/53471623-27a20100-3a1a-11e9-8216-7556217a83ab.png)

**Comment by martynasma** [comment]
Yes. Use their [`align`](https://www.amcharts.com/docs/v4/reference/zoomcontrol/#align_property) property.

**Comment by promitanan** [comment]
Thanks, I really appreciate how quickly you respond!
