### ISSUE TITLE
The number text and legend are far between.

### ISSUE THREAD

**Issue by thanh121094** [amcharts/amcharts4#1012]
Hi all,
I'm trying to use amcharts4 for my react's project and I am following this page: https://www.amcharts.com/demos/angular-gauge/
It's easy to use with default value, but when I have to set height of chart with code:
`<div id={"myId"} style={{ width: "100%", height: "90px" }}></div>`
This is result:
![ask](https://user-images.githubusercontent.com/24429197/53473999-8610c300-3a9e-11e9-816b-cbf2d22249fd.png)

As you see the legends and text are too far which is showed by the red line. So, how can I reduce the distance?
Thanks.

**Comment by RobbiesCode** [comment]
Hi,

You can adjust the `radius` value for your axis labels:

```
axis.renderer.labels.template.radius = 5; // pixel value
```

Docs: https://www.amcharts.com/docs/v4/reference/axislabelcircular/#radius_property.

Hope this helps!
