### ISSUE TITLE
Dependency(static-eval) Vulnerability for amCharts

### ISSUE THREAD

**Issue by ashok3107** [amcharts/amcharts4#1016]

**Comment by martynasma** [comment]
More details please?

**Comment by ashok3107** [comment]
Was getting the following moderate severity vulnerability issue when trying to install amcharts4.

Moderate        Sandbox Breakout / Arbitrary Code Execution

 Package         static-eval

 Dependency of   @amcharts/amcharts4

 Path            @amcharts/amcharts4 > pdfmake > pdfkit > linebreak > brfs >
                 static-module > static-eval

**Comment by martynasma** [comment]
Thanks.

Unfortunately, this relates to a third party library - pdfmake, over which we don't have control.

I suggest you raise this issue with pdfmake:
https://github.com/bpampuch/pdfmake/issues

Please do search their current issues first, in case it was already reported.

**Comment by ashok3107** [comment]
Thanks. Just saw that the issue has been resolved.
