### ISSUE TITLE
Exception/Crash in Line Series

### ISSUE THREAD

**Issue by asifmehboob** [amcharts/amcharts4#1017]
4.1.4 to 4.1.8 gives the "Cannot set property 'segment' of undefined" error and then browser crash in higher versions. For now we downgraded to the 4.1.3 version.
We are not even trashing the chart.data in a loop. Just resetting the chart.data value to a different array.

**Comment by asifmehboob** [comment]
Relates to https://github.com/amcharts/amcharts4/issues/979

**Comment by martynasma** [comment]
Can you provide an example?
