### ISSUE TITLE
Resize chart when printing with validateNow

### ISSUE THREAD

**Issue by AcerLaurinum** [amcharts/amcharts4#1019]
I am using amCharts 4 and am trying to get charts to resize to fit their container when printing an entire page. This example for amCharts 3 works perfectly and is exactly what I'm looking to do: https://amcharts.zendesk.com/hc/en-us/articles/203002652-Resizing-the-chart-for-print. The validateNow() function does not appear to be available in amCharts 4 and other functions I tried from the documentation did not work. Is it possible to do this in amCharts4? Thank you

**Comment by darlesson** [comment]
You could try use [minWidth](https://www.amcharts.com/docs/v4/reference/xychart/#minWidth_property) or [maxWidth](https://www.amcharts.com/docs/v4/reference/xychart/#maxWidth_property) when printing to manipulate the size on print:

    chart.exporting.events.on("exportstarted", function(ev) {
       if (ev.format == "print") {
         chart.maxWidth = 1000;
       }
    });

    chart.exporting.events.on("exportfinished", function(ev) {
       if (ev.format == "print") {
         chart.maxWidth = null;
       }
    });

Check more about manipulating properties on printing here: https://www.amcharts.com/docs/v4/tutorials/removing-chart-background-on-print/

If that doesn't work, could you provide a [codepen](https://codepen.io/) reproducing the issue?

**Comment by AcerLaurinum** [comment]
Thanks so much for the reply. Here is a codepen of the issue: https://codepen.io/anon/pen/jJqNQd I am right clicking and choosing the "Print..." option in Google Chrome rather than using amCharts export option as I'm trying to print a whole page with multiple charts on it. When printing the right side of the chart gets cut off. I have also tried setting the maxWidth and doing invalidate(), and reinit() with no luck.

**Comment by martynasma** [comment]
For that you might need to utilize generic print events. They are a bit tricky and vary from browser to browser, but you can read the scoop of it here:

https://stackoverflow.com/a/15713060/634045

**Comment by AcerLaurinum** [comment]
Yes, I am using generic print events in the example I linked. The issue I'm running into is there doesn't seem to be a function like chart.validateNow() in amCharts 4 to make the chart resize to fit into it's container when printing.

**Comment by martynasma** [comment]
You don't need to validate the chart. Simply change the width/height of the chart's container, and the chart will update itself:

```
document.getElementById("chartdiv").style.witdh = "500px";
```

**Comment by AcerLaurinum** [comment]
Unfortunately the chart doesn't seem to update in time when you update the size of the container with print events: https://codepen.io/anon/pen/jJqNQd

**Comment by martynasma** [comment]
Indeed. Chart building is async, meaning that it does not start rebuilding itself immediately when you change container size.

Another idea: maybe use CSS trasnform to resize the whole chart for print media query?

**Comment by AcerLaurinum** [comment]
Thanks! Doing CSS transform did work. Calculating the percentage you need to scale can potentially make things complicated but it should work for what I'm trying to do.
