### ISSUE TITLE
Depth chart: overlapping x-axis labels

### ISSUE THREAD

**Issue by runeksvendsen** [amcharts/amcharts4#1021]
Using [this data](https://gist.githubusercontent.com/runeksvendsen/4ad7d260abc03d1cc2447cc61f6aa7d3/raw/24ac985886faf75fc3f6ab2ddb762e85eab0ed8b/btcusd.json) for the depth chart, the price labels on the x-axis overlap each other: 
<img width="920" alt="screenshot 2019-03-01 at 13 47 51" src="https://user-images.githubusercontent.com/1069247/53639132-a7051f80-3c28-11e9-835c-0054920d620c.png">

Here's the Codepen example: https://codepen.io/anon/pen/rRxKjE (taken from the [chart demo site](https://www.amcharts.com/demos/live-order-book-depth-chart/) and modified to use the data that causes the issue).

**Comment by martynasma** [comment]
There are few ways to fix that:

1) Controlling label density:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

2) Rotating labels:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Label_rotation

3) Wrapping or truncating labels:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#selenium-highlight

**Comment by runeksvendsen** [comment]
Thank you for the quick reply!

If I increase `minGridDistance` to 100 for the x-axis, the labels no longer overlap:
<img width="755" alt="screenshot 2019-03-02 at 09 24 01" src="https://user-images.githubusercontent.com/1069247/53679427-f43acd00-3ccc-11e9-8e4c-8ab0db5c7d38.png">

However, the reason the labels overlap in the first place is that the precision of the x-axis labels is way too high (e.g. `3,981.2083`). Is there a way to adjust the precision of the labels, so that e.g. `3,981.2083` is displayed as `3,981` (ie. with four significant digits?). 

A nice interface to this would being able to supply a function that's applied to each a label value before it's displayed. Like:

```
var xAxis = chart.xAxes.push(new am4charts.CategoryAxis());
xAxis.renderer.labelFormatFn = function (x) {
    return Number.parseFloat(x).toPrecision(4);
};
```

As far as I can see from reading the [formatting numbers](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/) article, I can't adjust the number of significant digits, so that the number formatter makes sense both for input like `0.23432447292743` and `6384.324234` (which would become `0.2343` and `6384`, respectively.

**Comment by martynasma** [comment]
Well, since this particular demo uses `CategoryAxis`, no formatting on labels is applied. Category axis treats all labels as strings, not numbers.

I suppose you could add an adapter to category axis' labels to round those numbers.

```
xAxis.renderer.labels.template.adapter.add("textOutput", function(text, target) {
  return Math.round(target.dataItem.category).toString();
});
```

**Comment by runeksvendsen** [comment]
Wonderful! Thanks a lot. This was exactly what I was looking for.
