### ISSUE TITLE
validateData alternative on amcharts 4

### ISSUE THREAD

**Issue by Aljessy** [amcharts/amcharts4#1022]
Hello, i have 3 amcharts graphs. One are visible and the two others are hidden. I have a selectlist to choose which datas i want to display on my graphs. Then i have 3 others buttons to show or hide one of the graph. When i load my page, all the graph is draw so i can navigate into the using my buttons. But when i choose another list of data in my selectfield, only the diplay graph is loader, Hidden graphs are not loaded. How can i solve it using amcharts 4

**Comment by martynasma** [comment]
I'm not entirely sure I understand what you're asking, but if it is about dynamic data updated in amCharts 4, the following should get you rolling:

https://www.amcharts.com/docs/v4/concepts/data/#Dynamic_updates

**Comment by Aljessy** [comment]
Hi, my issue is mostly about displaying the graphs after selecting a specific data (using a selectfield from my database) in runtime without loading my page.

As you can see on the captured images, when i'm opening the page for the first time, all the charts are display (first 3 images are loaded propely), but after using a select only the current tab display the graph and the two oders are completely empty (as you can see on the 2 last images)

![loading_1](https://user-images.githubusercontent.com/5612015/53826805-777c4d00-3f71-11e9-831f-959f09e98739.PNG)

![loading_2](https://user-images.githubusercontent.com/5612015/53826806-7814e380-3f71-11e9-90a7-5dd9a8bd3211.PNG)

![loading_3](https://user-images.githubusercontent.com/5612015/53826807-7814e380-3f71-11e9-937c-e7c9734d5b1b.PNG)

![rechage_1](https://user-images.githubusercontent.com/5612015/53826809-7814e380-3f71-11e9-8b83-7e6dae8d8297.PNG)

![rechage_2](https://user-images.githubusercontent.com/5612015/53826810-78ad7a00-3f71-11e9-9f24-cec7d062b3ba.PNG)

**Comment by Aljessy** [comment]
Hi, thanks for you help. I solve the problem.

**Comment by danielmatthew** [comment]
@Aljessy Can you share your solution, please?
