### ISSUE TITLE
Columns pop in/out while panning/zooming using XYChartScrollbar

### ISSUE THREAD

**Issue by addexm** [amcharts/amcharts4#1023]
I'm having an issue with columns popping in/out while panning/zooming using XYChartScrollbar.

Here's an example: https://codepen.io/anon/pen/MxKRWm

Any thoughts? Maybe related to https://github.com/amcharts/amcharts4/issues/722

**Comment by martynasma** [comment]
Not sure if it's related, but definitely not right :)

Thanks for the heads up!

Will let you know when the fix is available.

**Comment by martynasma** [comment]
Screenshot of issue:
![image](https://user-images.githubusercontent.com/1458520/53679089-606b0000-3cd0-11e9-8dc5-7a000e1f885f.png)

**Comment by addexm** [comment]
@martynasma I think this turns out be a data issue. I realized that my dates aren't sorted correctly in the above example. Sorting them correctly seems to fix the problem.

**Comment by martynasma** [comment]
OK. Thanks for the update. Closing this then.
