### ISSUE TITLE
Pie chart labels not responsive

### ISSUE THREAD

**Issue by promitanan** [amcharts/amcharts4#1024]
The pie chart labels are not responsive to the size of the window, even though the pie chart itself is.
The charts are in responsive divs.

Full width container:
![image](https://user-images.githubusercontent.com/18385581/53676262-aedab900-3c54-11e9-9b28-909976011345.png)

Smaller screen: 
![image](https://user-images.githubusercontent.com/18385581/53676275-cfa30e80-3c54-11e9-84c8-5474cc06780e.png)

**Comment by darlesson** [comment]
amCharts just released a tutorial how you could get your chart to be responsive: https://www.amcharts.com/docs/v4/concepts/responsive/

I recommend to check the information on the link above, then you could try to increase the padding and make the ticks and the labels disappear such as:

```
 chart.responsive.enabled = true;
 chart.responsive.useDefault = false;

 chart.responsive.rules.push({
   relevant: function(target) {
     if (target.pixelWidth <= 400) {
       return true;
     }
    
     return false;
   },
   state: function(target, stateId) {
    
     if (target instanceof am4charts.Chart) {
       var state = target.states.create(stateId);
       state.properties.paddingTop = 0;
       state.properties.paddingRight = 25;
       state.properties.paddingBottom = 0;
       state.properties.paddingLeft = 25;
       return state;
     } else if (target instanceof am4charts.AxisLabelCircular ||
       target instanceof am4charts.PieTick) {
       var state = target.states.create(stateId);
       state.properties.disabled = true;
       return state;
     }
     return null;
   }
 });
```

Please check the working example here: https://codepen.io/team/amcharts/pen/a0a51c451e6dc92863bc64f14212732f
