### ISSUE TITLE
Dynamically changing data granularity on a Serial chart

### ISSUE THREAD

**Issue by MartinCerny** [amcharts/amcharts4#1026]
Hello,
can i use something similar in version 4? In version 3 it is good functionality for 40 000+ records. The version 4 took 2GB memory and then shuts down... version 3 took 60MB memory and it's still very fast for exploring chart. 

Thank you for answer

**Comment by dorsharon** [comment]
Also interested, but for XY chart

**Comment by martynasma** [comment]
Dynamic data grouping is not yet implemented in amCharts 4, I'm afraid.

We will be implementing it, but at this point I can't provide an ETA, yet.

**Comment by MrCrunsh** [comment]
Same Problem at XY CHarts in V4. Update chart.data will explode Chrome-Memory and the Browser crashed, if you will use more then 2 Charts on one Page.

**Comment by martynasma** [comment]
Just posted this example which creates aggregated snapshots of the daily data, and uses proper granularity dynamically, ensuring that at any given time the chart does not have more than a few hundred data items, which makes it fast.

https://codepen.io/team/amcharts/pen/zbyveK?editors=0010

Hope you guys find it useful until we implement proper data point grouping.

**Comment by TippyTipster** [comment]
Is there by chance an ETA or plans for this? I'm also running into this issue. Though your example is helpful, it would be wonderful to be able to work with the proper functionality built in.

**Comment by havietduc91** [comment]
Same problem here, I'm building the XYChart in version 4 with 30 series and 180 columns, it took 3897MB and the browser crashed immediately after that.

**Comment by martynasma** [comment]
Dynamic data point grouping has been available since `4.7.0`.

More details:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping
