### ISSUE TITLE
Hovering over choropleth map removes shades

### ISSUE THREAD

**Issue by promitanan** [amcharts/amcharts4#1027]
I've been trying to make a drill-down choropleth map and so far I've added a choropleth of the USA, using your choropleth map demo data, but when you hover over the states the shades are reset and when you press the home button the shades are reset too. So clicking the US, then home, then clicking US again will remove the heat colors. The tooltips over the states retain their color though. I'm not sure why this is happening?

Only US has choropleth color but the Canada also has a state-level map (single color):
https://jsfiddle.net/promitanan/qh5axfnL/5/

Thank you!

**Comment by notacouch** [comment]
Between being hidden at the onset and the color being lost between hover/default states, it looks like that in this case you'll need a heatrule to target the `defaultState` of the `mapPolygon`s as well.

```javascript
        usaStatesSeries.heatRules.push({
            property: "fill",
            target: usaStatesSeries.mapPolygons.template.defaultState,
            min: chart.colors.getIndex(1).brighten(1),
            max: chart.colors.getIndex(1).brighten(-0.3)
        });
```

For some insight, at the end of the day the heatrule applies an adapter on the `target`, [source](https://github.com/amcharts/amcharts4/blob/ccdc7bfb9a99432ba0eda0acc8abd36eb4fc732d/src/.internal/charts/series/Series.ts#L1385):

```typescript
    target.adapter.add(<any>property, (value, ruleTarget, property) => {
        // ...
```

Fork:
https://jsfiddle.net/notacouch/uwrh2cLg/

**Comment by promitanan** [comment]
Thank you for the help and the explanation! That works. The state level maps also seem to flash when the map first renders, is there a way to remove that?
