### ISSUE TITLE
Rendering error when timestemps are too close (but not the same)

### ISSUE THREAD

**Issue by danielhoeltgen** [amcharts/amcharts4#1028]
Hi everyone,

I found a rendering error that occurs when you have timestamps which are very close to each other. The chart shows only the last points of the data set then.
![image](https://user-images.githubusercontent.com/23211023/53733266-c8604880-3e80-11e9-82b1-ab804b8a553e.png)
Use this Code to cause the error:

```javascript
// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("chartdiv", am4charts.XYChart);

// Add data
chart.data = [{
  "temp1": 102,
  "temp2": 90,
  "_time": new Date("2019-03-02T23:30:20.346Z")
}, {
  "temp1": 102,
  "temp2": 90,
  "_time": new Date("2019-03-02T23:30:25.346Z")
}, {
  "temp1": 125,
  "_time": new Date("2019-03-02T23:30:30.346Z")
}, {
  "temp2": 90,
  "_time": new Date("2019-03-02T23:30:30.347Z")
}, {
  "temp1": 55,
  "_time": new Date("2019-03-02T23:30:35.347Z")
}, {
  "temp1": 81,
  "temp2": 60,
  "_time": new Date("2019-03-02T23:30:40.348Z")
}];

// Create axes
var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

// Create series
var series = chart.series.push(new am4charts.LineSeries());
series.dataFields.valueY = "temp1";
series.dataFields.dateX = "_time";
```

when changing
```javascript
{"temp2": 90,
  "_time": new Date("2019-03-02T23:30:30.347Z")
}
```
to
```javascript
{"temp2": 90,
  "_time": new Date("2019-03-02T23:30:30.346Z")
}
```
(same milliseconds as previous) or to
```javascript
{"temp2": 90,
  "_time": new Date("2019-03-02T23:30:30.357Z")
}
```
(larger gap between milliseconds) everything works fine.

is there an easy way to fix the problem? I think I will try using an adapter and rounding the millisecond values.

**Comment by martynasma** [comment]
This looks like an issue with automatic data granularity detection.

When using data at irregular intervals it's best not to rely on chart to automatically detect your data granularity and specify it yourself, using `baseInterval`.

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Manually_specifying_data_granularity
