### ISSUE TITLE
Where is AmCharts.Guide()? 

### ISSUE THREAD

**Issue by hengfengli** [amcharts/amcharts4#1029]
I can see that there is `AmCharts.Guide()` in V3, but not in V4. Can you tell how can I create a horizontal guideline like that in V4? Thanks.

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides

**Comment by hengfengli** [comment]
Thanks a lot for replying. It's really difficult to look up things from V3 to V4.
