### ISSUE TITLE
`label.text` is ignored on a CategoryAxis axis range

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#103]
```
range.startCategory = "Marketing";
range.endCategory = "Marketing";
range.label.inside = true;
range.label.text = "Something";
range.label.fill = "#c22";
range.axisFill.fill = "#c22";
range.axisFill.fillOpacity = 0.4;
```

The label should say "Something", but is says "Marketing":

![image](https://user-images.githubusercontent.com/1458520/41838431-17e9f4b6-7869-11e8-8c3a-0ded72cb3df5.png)

Example: https://codepen.io/team/amcharts/pen/325d6e14ea9da257b1320ac4be323f0c?editors=0010

**Comment by zeroin** [comment]
correct way would be to use: 
`range.text = "Something"`
