### ISSUE TITLE
Autogridcount missing

### ISSUE THREAD

**Issue by ekosynth** [amcharts/amcharts4#1030]
I have a xychart with labels on the y axis. Every second label is being hidden. Google suggests that I can set:     
`valueAxis.autoGridCount = false;`
and: 
` valueAxis.gridCount `
to the number of grids required by the data. 

...but it doesn't have any effect, autoGridCount seems to be missing in the V4 documentation and there is no mention of it being removed.
![image](https://user-images.githubusercontent.com/10242235/53736266-22610e00-3e81-11e9-8005-c2cf64190ee2.png)

**Comment by martynasma** [comment]
amCharts 4 has nothing to do with v3 and its config.

Take a look here instead:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels
