### ISSUE TITLE
Issue #27 reintroduced? XYCursor displaying on wrong dates (which do not exist in the dataset)

### ISSUE THREAD

**Issue by sschrijver** [amcharts/amcharts4#1031]
Is it possible that issue #27 is reintroduced in Angular? (`"@amcharts/amcharts4": "^4.0.4",`  &  `"@amcharts/amcharts4": "^4.1.14",`)?
When I am hovering charts, the cursor shows dates that aren't in the dataset.
Also the steps are 5 days, while the datasets has gaps of 7 days.

In the below examples there are a few issues:
- 5 October is not a datapoint, its the data of 8 October that is shown on this point
- 16 October is shown after 15 October when hovered (last two images)

![screenshot 2019-03-04 at 15 13 43](https://user-images.githubusercontent.com/12063538/53738767-63acea00-3e90-11e9-9432-b4c447d34f3c.png)
![screenshot 2019-03-04 at 15 07 44](https://user-images.githubusercontent.com/12063538/53738548-c0f46b80-3e8f-11e9-9af0-0ab7028fea76.png)
![screenshot 2019-03-04 at 15 07 49](https://user-images.githubusercontent.com/12063538/53738549-c0f46b80-3e8f-11e9-9049-65992ad1479d.png)

_Originally posted by @sschrijver in https://github.com/amcharts/amcharts4/issues/27#issuecomment-469251977_

**Comment by martynasma** [comment]
From the looks of it your chart is in weekly mode, in which case the label represents start of the week.

BTW, can you post your chart/data so that we can try it?

**Comment by sschrijver** [comment]
Thanks for the response, was able to fix this issue by setting the axis to day-mode
```
 (<am4charts.DateAxis>correctAxis).baseInterval = {
          'timeUnit': 'day',
          'count': 1
        };
```
