### ISSUE TITLE
Inversed ColumnChart

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#1032]
Hello,

How to inverse (rotate ?) ColumnChart xAxis and yAxis ( in JSON config mode) ?

I didn't find something about that in documentation... 

![image](https://user-images.githubusercontent.com/6083644/53748212-2f8ff400-3ea5-11e9-9e52-0279e5c00dbf.png)

This is not working: 

```javascript
var config = {
	"xAxes": [
		{
			"type": "CategoryAxis",
			"dataFields": {
				"category": "country",
				"title": {
					"text": "Countries"
				}
			},
			"renderer": {
				"inversed": true,
				"grid": {
					"strokeWidth": 0
				}
			}
		}
	],
	"yAxes": [
		{
			"type": "ValueAxis",
			"renderer": {
				"opposite": true,
				"grid": {
					"strokeWidth": 0
				}
			}
		}
	]
}
```
This too :  

```javascript
var config = {
	"xAxes": [
		{
			"type": "ValueAxis",
			"renderer": {
				"grid": {
					"strokeWidth": 0
				}
			}
		}
	],
	"yAxes": [
		{
			"type": "CategoryAxis",
			"dataFields": {
				"category": "country",
				"title": {
					"text": "Countries"
				}
			},
			"renderer": {
				"grid": {
					"strokeWidth": 0
				}
			}
		}
	]
}
```

**Comment by martynasma** [comment]
The code snippet does not correspond with the screenshot.

You have CategoryAxis in yAxes and ValueAxis in xAxes in screenshot, but the other way around in your code, so I'm assuming there's either an issue with your code or your pasted something different.

In any case, setting `axis.renderer.inversed = true` should effectively flip the axis.

https://codepen.io/team/amcharts/pen/f1a25157e97d8df9bdeab4d850098817?editors=0010

**Comment by martynasma** [comment]
JSON version:
https://codepen.io/team/amcharts/pen/afea4c9a4e2722919ca367efa988a64c?editors=0010

**Comment by ptorrent** [comment]
Thanks, you're perfect !
