### ISSUE TITLE
amcharts doesn't load data for object jsob based 

### ISSUE THREAD

**Issue by siiamine** [amcharts/amcharts4#1033]
my amcharts doesn't load  object json data
{0: {…}, 2: {…}, 7: {…}}
0: {id: 1, name: "Fiche", created_at: "2018-10-03 10:02:56", updated_at: "2018-10-03 10:02:56", comingdocs_count: 1}
2: {id: 3, name: "Correspondance", created_at: "2018-10-03 10:05:21", updated_at: "2018-10-03 10:05:21", comingdocs_count: 1}
7: {id: 8, name: "Note de service", created_at: "2019-02-13 11:17:58", updated_at: "2019-02-13 11:17:58", comingdocs_count: 1}

**Comment by martynasma** [comment]
If you could elaborate what "doesn't load data" means, maybe someone would be able to help :)

Better yet, post a codepen of your chart, so we know what you're aiming to achieve here.
