### ISSUE TITLE
Adding subcategories to XYChart

### ISSUE THREAD

**Issue by sunnyboi21** [amcharts/amcharts4#1036]
Is it possible to add subcategories Amchart v4? It works in v3.

I want to be able to group the data by name then by date and display 3 types of columns for each subcategory.
http://jsfiddle.net/jozdfvw4/

Edit:  https://playfairdata.com/3-ways-use-dual-axis-combination-charts-tableau/ is another example of subcategories

**Comment by martynasma** [comment]
You can use Axis Ranges for that.

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/

Example:
https://codepen.io/team/amcharts/pen/OqWjMv?editors=0010
