### ISSUE TITLE
TypeError: "Cannot read property 'axisLength' of undefined" when trying to update charts

### ISSUE THREAD

**Issue by ashok3107** [amcharts/amcharts4#1037]
I am using "amcharts": "^4.1.14" and "react": "^16.6.3" and I am facing the above error when I try to update my graph by passing a new set of series/ new data and clearing the old series present.  

I am updating the graph via componentDidUpdate() method, 

componentDidUpdate(oldProps){
       if(oldProps.series != this.props.series){
           var length = this.chart.series.length;
           for(var i =0; i< length; i++){
               this.chart.series.removeIndex(0);
           }
           this.props.series && this.props.series.map((data) => {
               this.chart.series.push(data);
           });
           this.chart.data = this.props.chartData;
       }
   }

**Comment by martynasma** [comment]
Can you produce a full demo for us to try to understand what's going on?

I'm afraid this snipped is not enough :(
