### ISSUE TITLE
"Counties Morphing To Heart" demo error: cannot read property "hide" of undefined

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#1038]
Looking at [this demo](https://www.amcharts.com/demos/countries-morphing-to-heart/) I get an error `cannot read property "hide" of undefined`.

I believe the error comes from the arbitrary timeout of 500ms:

```
  countriesSeries.geodataSource.events.on("ended", function() {
    setTimeout(function() {
      handleNext(userCountryId);
    }, 500)
  });
```

The function `zoomToSelectedPolygon` is called after these 500ms, which might be sufficient for high-speed devices, but it is not enough for my good old Chromebook. Another user reported the same thing.

It means that `countriesSeries.getPolygonById(userCountryId);` returns `undefined` when it is called for the first time.

Instead of setting a timeout, it would be better to wait for some event like "all polygons loaded" if possible.

Here's the demo: https://codepen.io/team/amcharts/pen/bf69f142c4a9886cfb39494b5da2002f?editors=0010.

If I set the timeout of `500` to `1500` it works for me, so that tells me it has to do something with polygons being ready or not yet.

---

Update: user actually mentions that he's not seeing this error anymore (somehow). In the meantime, I still get it (if I don't update the timeout).

**Comment by martynasma** [comment]
How about if we use series' "ready" event instead?

```
  countriesSeries.events.on("datavalidated", function() {
      console.log("HANDLE NEXT");
      handleNext(userCountryId);
  });
```
