### ISSUE TITLE
Multiple grouped category axes for bar chart

### ISSUE THREAD

**Issue by muratcatal** [amcharts/amcharts4#1039]
Hi,
I'm trying to create a stacked bar chart with multiple clustered categories as shown in picture. I created a stacked bar chart with two categories however i could not find anywhere if amcharts supports multiple group/clustered bar chart as shown in picture.

The code which i wrote is in [https://codesandbox.io/embed/z2vy76x5w4?fontsize=14](url)

I donno if i missed something or not, however i could not find a solution in anywhere.

![amcharts_chart](https://user-images.githubusercontent.com/5106209/53889808-1bc8c700-4038-11e9-95be-4e2419808836.png)

Thanks from now for any helps.

**Comment by martynasma** [comment]
You can use Axis Ranges to group them:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/

Here's an example:
https://codepen.io/team/amcharts/pen/OqWjMv?editors=0010
