### ISSUE TITLE
Bar chart label bullet is cut off from highest bar

### ISSUE THREAD

**Issue by mcenkar** [amcharts/amcharts4#1040]
Hi,

when using LabelBullet it sometimes gets cut off from chart, see: 
https://codepen.io/anon/pen/wOgyJv

![image](https://user-images.githubusercontent.com/11230749/53899462-87139880-403a-11e9-94f0-3163aa9c2535.png)

However doesn't happen when you increase higher value:

```
{
  "category": "Distribution",
  "value": 2050
}
```
![image](https://user-images.githubusercontent.com/11230749/53899509-a6122a80-403a-11e9-96ee-0f8e6858f879.png)

**Comment by martynasma** [comment]
Axis scale is not influenced by bullets, so they might get cut off if close to the edge.

There are two ways to work around that:

1) Unmasking bullets:
https://www.amcharts.com/docs/v4/concepts/bullets/#Bullets_outside_plot_area

2) Increasing scale a bit:
https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Relatively_expanding_the_scale

**Comment by mcenkar** [comment]
This helped, thanks:

```
      valueAxis.extraMax = 0.05;
```

But I would still say it's a bug/feature. Unmasking bullets even in your example still cuts off, and with increasing scale I have to come up with some arbitrary number to increase it. It would be much nicer to be able to configure `justDontCutItOff: true` :+1:

**Comment by martynasma** [comment]
There is a setting like that, except it's called `chart.maskBullets = false` ;)

**Comment by mcenkar** [comment]
If in your chart example you change max value to 1950 even with maskBullets it cuts off:

https://www.amcharts.com/docs/v4/concepts/bullets/#Bullets_outside_plot_area

![image](https://user-images.githubusercontent.com/11230749/53966852-542ddb00-40f4-11e9-800c-91e5982fcb3c.png)

**Comment by martynasma** [comment]
Yeah, they don't fit physically into chart container. You might need to increase `paddingTop` for small charts.

That, or `extraMax`. It is relative BTW, so setting it to 0.05 would add 5% to whatever scale you currently have.

In any case, I can't classify it as "bug". Adjusting scale based on labels would be overkill, especially that label can be anything anywhere.

Hope you find it reasonable.

**Comment by mcenkar** [comment]
Fair enough, `extraMax` will do. Thanks for tip

**Comment by demostheneslld** [comment]
`paddingTop` worked for me without changing the chart scale. I didn't even need to modify `chart.maskBullets`

**Comment by SantySun** [comment]
## Amazing! Thanks for your help!
