### ISSUE TITLE
Wrong dates in line chart DateAxis

### ISSUE THREAD

**Issue by dFelinger** [amcharts/amcharts4#1041]
Something wrong with dates: it's all decreased by 1 day if skip one day in the start.
https://codepen.io/anon/pen/PLWBoZ#anon-login
If uncomment "2019-03-06" date - it all be fine.
With this demo all works fine even if I delete one date. https://www.amcharts.com/demos/date-based-data/

**Comment by dorsharon** [comment]
Same issue, only with 2 hours forward.

**Comment by dorsharon** [comment]
After some digging, my issue was caused by having a base interval of 1ms.
My dates were being offset by UTC timezone when rounding the date to the base interval, but were never offset back. since on 1ms it immediately returns the date

**Comment by martynasma** [comment]
@dFelinger Not seeing the decrease. Can you check if you are running the latest version (4.2.0)?

**Comment by martynasma** [comment]
This is what I'm seeing BTW:

![image](https://user-images.githubusercontent.com/1458520/53961297-ec29c580-40f0-11e9-8c13-e5d2e2ee2571.png)

**Comment by dFelinger** [comment]
This issue appears only if there is no "Mar 06" in data.
![image](https://user-images.githubusercontent.com/5339870/53975048-96780c00-4136-11e9-8d1f-063ff0737338.png)

**Comment by martynasma** [comment]
OK, so the issue is that labels are positioned at the beginning of the period, rather than in the middle.

You can fix that by repositioning them to the middle:

```
dateAxis.renderer.labels.template.location = 0.5;
```

**Comment by dFelinger** [comment]
No. The issue is date in chart.data: "mar 5", "mar 12", "mar 19" (if there is three dates in data - "mar 06" is commented) BUT dates in chart is "mar 04", "mar 11", "mar 18" - the dot is on "mar 04" - not in the "mar 05"
![image](https://user-images.githubusercontent.com/5339870/54044551-d0faab00-4201-11e9-9e7c-3ddee0f36a9a.png)
In data there is "2019-03-**12**" but in chart date is "mar **11**".

**Comment by dFelinger** [comment]
@martynasma , please try 3 dates like in my previous commentary

**Comment by dorsharon** [comment]
try giving a base interval other than 1ms, like i said here before...

**Comment by dFelinger** [comment]
baseInterval with one date period helps, but I can't understand logic of display values - why if I not use baseInterval data in the chart is wrong? For mar 04 there is value 10 when real data is: value 10 is for mar 05

**Comment by martynasma** [comment]
If baseInterval is not set, the chart tries to deduct it out of your data. If data is not at regular intervals, it might get it wrong.
