### ISSUE TITLE
Unexpected token export when use nextjs and amchart 4

### ISSUE THREAD

**Issue by flyingtango** [amcharts/amcharts4#1043]
I have a problem when ingredient the amchart4 with nextjs using react. I try 2 method to import the amchart but both failed.
1.
let am4core = null
let am4charts = null
let am4themesAnimated = null
if (process.browser) {
  am4core = require('@amcharts/amcharts4/core')
  am4charts = require('@amcharts/amcharts4/charts')
  am4themesAnimated = require('@amcharts/amcharts4/themes/animated')
  am4core.useTheme(am4themesAnimated.default)
}

2.
import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";
import am4themes_animated from "@amcharts/amcharts4/themes/animated";

The error is ~/node_modules/@amcharts/amcharts4/core.js:8
export { System, system } from "./.internal/core/System";
^^^^^^

SyntaxError: Unexpected token export

Have no idea why it would happened.

**Comment by darlesson** [comment]
This issue is related to https://github.com/zeit/next.js/issues/706.

**Comment by pritam3010** [comment]
Just install the next-transpile-modules package from NPM and add the following line in your next.config.js file.

const withTM = require("next-transpile-modules")([
  "@amcharts/amcharts4/core",
  "@amcharts/amcharts4/charts",
  "@amcharts/amcharts4/themes/animated"
]); // pass the modules you would like to see transpiled

module.exports = withTM();

**Comment by LindseyRenken** [comment]
That worked for me, thanks.

**Comment by hmthanh** [comment]
For me it's problem with amchart5.
Here is answer, I just miss the documentation.

We need set `ssr` to `False` :
```javascript
const AmChartComponent = dynamic(() => import("../components/Chart/AmChartComponent"), {
  ssr: false
});
```

**Comment by MahmoudKafrawy** [comment]
> For me it's problem with amchart5. Here is answer, I just miss the documentation.
> 
> We need set `ssr` to `False` :
> 
> ```js
> const AmChartComponent = dynamic(() => import("../components/Chart/AmChartComponent"), {
>   ssr: false
> });
> ```

@hmthanh  thanks that worked for me on next 13.1.6
