### ISSUE TITLE
Chart Rotation leaves container

### ISSUE THREAD

**Issue by mcenkar** [amcharts/amcharts4#1044]
Hi,

I want to flip simple bar chart by 90 deg, while still keeping it in container. Unfortunately it seems to be leaving it's container completely going to the side.

You can see it here: https://codepen.io/anon/pen/OqmwLK?&editable=true or change rotation to any other.

![image](https://user-images.githubusercontent.com/11230749/54031939-74bb6b00-41b0-11e9-8116-dc73f3cdc245.png)

Is there a way to keep it in container?

**Comment by martynasma** [comment]
You can use `horizontalCenter` and `verticalCenter` to set a pivot point. It's in the upper-left corner by default, hence it rotating like that.

However, I can't see how that chart can fit into horizontal container while rotated to be vertical.
