### ISSUE TITLE
Line chart with live data has very high CPU usage

### ISSUE THREAD

**Issue by rocos-david** [amcharts/amcharts4#1046]
## Repro Steps
Use Chrome Performance monitor on your own live data example, and turn the render interval from 1000ms to 200ms you will see very high CPU usage.

https://www.amcharts.com/demos/live-data/

![image](https://user-images.githubusercontent.com/43590410/54063449-5a959180-4271-11e9-8d7c-947e636d4f22.png)

I manipulated the different animation settings and one of the big culprits was dateAxis.rangeChangeDuration.  If you set that to 0 it goes from ~95% CPU consumption down to ~35% consumption, but obviously lose the lovely smoothing.

##  Actual Behavior
Consumes nearly all available processing for the web page and slows everything down.

## Expected Behavior
Need to be able to render updates at least every 200ms (if not faster) especially if we are only dealing with one series, and often we have up to 3.  Ideally with animation settings on.

We use many different controls and libraries from 3rd parties such as 3D rendering, mapping etc. and these when optimised correctly can all performance well under 10% with much more complex data at faster than 200ms refresh interval. 

Ideally this would be something like 3% consumption, not > 95% consumption as we would like to put 10 of these graphs all updating on screen at the same time, but any improvement on what the system currently has would be appreciated.

## Version Info 
Using your own example at https://www.amcharts.com/demos/live-data/

**Comment by martynasma** [comment]
I'm going to mark this as an enhancement issue. We might try to come up with the solutions on how to speed this up or reduce CPU usage in the future.

However, for right now, setup where you need to update the chart every 200ms but keep animations is a bit far fetched, and frankly a bit niche, so I can't give it a priority :(

**Comment by rocos-david** [comment]
Ok, thanks @martynasma, totally understand that the market you are after is really just for static reporting, this unfortunately rules your charting out for dashboarding live data scenarios.  I'll keep an eye on this ticket to see if there are any changes later on.

**Comment by martynasma** [comment]
We've come a long way since this thread has started i terms of performance.

I'm going to go ahead and close this.

We also have a central point for all significant performance tips:
https://www.amcharts.com/docs/v4/concepts/performance/
