### ISSUE TITLE
skipEmptyPeriods skipping more then just the weekend

### ISSUE THREAD

**Issue by thiagottjv** [amcharts/amcharts4#1047]
Hi, I`m using the CDN version of amCharts.
My problem is that I have a chat that show Stock values during a year. My problem was that on the weekends there isnt a value.
So I used **skipEmptyPeriods** on my **DateAxis**. The problem was that it didnt skipped data on the weekends, but **it erased from Nov 2 to Feb 17** (starting at a weekend and ending in another). Before Nov 1 it eresed the weekends fine (for example the Oct 20 and 21).
What should I do?

**Comment by RobbiesCode** [comment]
Hi,

That doesn't sound right, I agree. Do you have code + data online somewhere, preferably in a Codepen? That way we can have a closer look at what is going on.

**Comment by thiagottjv** [comment]
Hi Robbies, good Idea.
This is the pen I created:
https://codepen.io/thiagottjv/pen/vPZqoo

I used the example from the amCharts website and the same data that I`m using.
If you remove the line 12 (skipEmptyPeriods) you`ll see that there is a lot of data between November and 
February.

**Comment by RobbiesCode** [comment]
Thanks for creating the Codepen! I still see the data between Nov 2 and Feb 17, even if `skipEmptyPeriods` is **true**. This is what I see:

![image](https://user-images.githubusercontent.com/13300227/54085577-fa215580-433f-11e9-9c7f-1d1de68f7737.png)

**Comment by thiagottjv** [comment]
Thats strange, look what my graph looks like:
![image](https://user-images.githubusercontent.com/4126003/54085642-fb8e5600-431e-11e9-9afa-9508776998c6.png)
I`m from Brazil. maybe is there some problem on locale?

**Comment by martynasma** [comment]
@thiagottjv We've just released 4.2.2. Can you try how it is now for you?

**Comment by thiagottjv** [comment]
@martynasma Thanks, on the codepen is working. I`ll change my local code and try too (I changed for CategoryAxis)!
