### ISSUE TITLE
Malaysia geodata: Sabah state missing

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#1048]
<img width="271" alt="Screenshot 2019-03-09 at 11 24 41 PM" src="https://user-images.githubusercontent.com/13300227/54085073-b6c3e880-4339-11e9-9ad8-e66ffc474e50.png">

On Malaysia maps (like https://github.com/amcharts/amcharts4/blob/master/dist/geodata/es2015/malaysiaHigh.js) the state of Sabah is missing.

Technically, you can find a polygon in our geodata named Sabah, but it's too small, and should not be seperated from Malaysian Borneo.

**Comment by martynasma** [comment]
The map was updated in geodata 4.1.4.
