### ISSUE TITLE
DateAxis.zoomToDates() does not work in a multi-axis chart

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#105]
Example: https://codepen.io/team/amcharts/pen/5bdc8d13a02ada667e3d7c92a08d7daf/

The chart has two `DateAxis` with a `LineSeries` in each of them.

Calling `zoomToDates()` on an axis does not seem to have an effect.

If I disable second axis and its series, zooming works as expected.

**Comment by zeroin** [comment]
Don't have other solution except that both axes should be zoomed. We are syncing zoom levels of axes because otherwise value axis selection is jumpy while scrolling a chart with multiple value axes.

**Comment by martynasma** [comment]
Just to make it clear: to zoom chart with several DateAxis you need to call `zoomToDates()` on all axes for it to work.
