### ISSUE TITLE
Tooltip on date axis repeating second to last value

### ISSUE THREAD

**Issue by jakeleventhal** [amcharts/amcharts4#1050]
![Mar-10-2019 23-06-19](https://user-images.githubusercontent.com/15133828/54098033-28775300-4389-11e9-8c39-1d70a6f5fe89.gif)

The data should be Mar 9 and Mar 10 as the last two values. Instead the tooltip says Mar 9 for both.

**Comment by martynasma** [comment]
1) Can you verify that you are using the latest version of amCharts? We've fixed some issues related to axis tooltips recently.

2) If the above does not help, can you post a working example of your chart with the issue on codepen/jsfiddle, which we can test?

**Comment by jakeleventhal** [comment]
I cannot get the behavior to repeat, but I was on the most recent version. I guess I will just reopen if I see the bug again.
