### ISSUE TITLE
Drawing tool for trend lines

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#1055]
Hello,

I have observed that there is a provision for user to draw a trend line in stock chart.

https://www.amcharts.com/demos-v3/drawing-trend-lines-v3/

Is there any similar provision for line series? I tried achieving it using drag start and drag end events, but didn't  produce proper results.
It would be really helpful if there is a built-in functionality.

**Comment by martynasma** [comment]
There's currently no such functionality. We might introduce it in the future, but right now, we don't have any immediate plans.

Sorry.

**Comment by martynasma** [comment]
At this point we are not going to be implementing a built-in trend line functionality.

Two options:

1) Use Annotation plugin:
https://www.amcharts.com/docs/v4/tutorials/plugin-annotation/

2) Implement custom solution:
https://www.amcharts.com/demos/drawing-chart-series-with-mouse-or-touch/
