### ISSUE TITLE
Draw a line while dragging a bullet

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#1057]
Hello,

I have a requirement that when user selects any two points on the line series, the selected area must be highlighted and maximum point should be plotted as a bullet.

I am able to achieve this through axis ranges and trend lines successfully.

The only problem is that I want to join the selected points through a trend line while user drags from the first point, rather than selecting two points through two clicks.

Is there any provision to achieve that.

![Capture](https://user-images.githubusercontent.com/41825318/54175841-61f7ad80-44b2-11e9-9d69-85f18fa6e54a.PNG)

Below is the demo:
https://codepen.io/vaish1906/pen/OqjQoE?editors=0010

**Comment by martynasma** [comment]
It should be possible because technically any object in the chart can be made draggable and have drag events, so you can update the line dynamically as user is dragging the bullet.

Unfortunately, there's no such demo readily available. Good luck :)
