### ISSUE TITLE
Chart container sizes not updating

### ISSUE THREAD

**Issue by reikidd** [amcharts/amcharts4#1058]
I got a weird issue, if I change the data displayed on the chart using an external element(select, switch, etc.), the chart container width/height stops to dynamic update it when I resize the page.
Here is a pen: https://codepen.io/kiradead/pen/zbogQw

**Comment by notacouch** [comment]
Thanks for the pen, it helped a lot.

So, it's not that you're changing the chart's data, you're making a new chart every time.

If you `dispose` the previous chart(s) before making a new one on the same element, the new charts still resize just fine. E.g.

```javascript
am4core.registry.baseSprites.forEach(chart => chart.dispose());
```

Demo:
https://codepen.io/team/amcharts/pen/5608c86bd9a84a1a1b047f5ca9ceac21
