### ISSUE TITLE
Applying a fill-pattern to one chart segment only

### ISSUE THREAD

**Issue by microrache** [amcharts/amcharts4#1061]
Hi guys, I think I need some help: I want to apply a fill-pattern to only one particular segment in a pie-chart. I think I already am on the right track by writing a fill-adapter and identifying the correct filter, but somehow it still refuses to work as expected, although the pattern-fill-object is applied correctly to the slice I want: https://jsfiddle.net/zscnyxkv/

It does work though when I apply the same fill-pattern-object to the slices-object in general, so why does it not work when it comes from the adapter?

Could you please have a look at this and help me? Thanks a lot.

**Comment by martynasma** [comment]
An adapter is used when the chart is operational, not at the JSON parsing stage.

Which means it must return an object suitable for use in `fill`, not its JSON representation.

```
            var pattern = new am4core.LinePattern();
            pattern.width = 8;
            pattern.height = 8;
            pattern.strokeWidth = 1;
            pattern.stroke = am4core.color("#666");
            pattern.rotation = 45;
            return pattern;
```

Or this will work too:

```
            var pattern = new am4core.LinePattern();
            pattern.config = {
              width: 8,
              height: 8,
              strokeWidth: 1,
              stroke: "#666",
              rotation: 45
            };
            return pattern;
```

https://jsfiddle.net/h4e1gsf9/

**Comment by microrache** [comment]
Ah, that makes sense, of course. Thank you!
