### ISSUE TITLE
Angular + Webpack when unhidding a series it is not shown

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1062]
Hi after updating to latest when I set hidden to false for a series then that series is not shown but when again I disable it then it shown the animation of going down. 

Looks like some index issue. 

related to <base>

**Comment by jimmykane** [comment]
Here is a video of the behavior 

https://drive.google.com/file/d/1kDelbwgLTPJkV30q9Wcr9GKZr-pO-3Nb/view

**Comment by jimmykane** [comment]
I think this broke after the last 4.1.x version 

@martynasma

**Comment by jimmykane** [comment]
I found out what changed: 

```
chart.legend.itemContainers.template.events.on("toggled", (ev) => {
        const series = <am4charts.LineSeries>ev.target.dataItem.dataContext;
        // Getting visible...
        if (ev.target.readerChecked === true) {
          this.showSeries(series)
        } else {
          // debugger;
          this.hideSeries(series)
        }
      });
``` 
You changed the behaviour of `ev.target.readerChecked` when toggling a label. 

Is there another way to check if the label when it's click is enabled or not ?

**Comment by jimmykane** [comment]
hmmm and the above changed again with 4.2.2

**Comment by martynasma** [comment]
`readerChecked` was being set incorrectly before.

Use `isActive` instead to check whether legend item is turned off (`true`) or on (`false`).

**Comment by martynasma** [comment]
Hey, found this old thread. It should be OK now. Feel free to reopen if it's still an issue.
