### ISSUE TITLE
Disable animations dynamically

### ISSUE THREAD

**Issue by CalvinNunes** [amcharts/amcharts4#1063]
Hello, I have a Question:

I want to use animations when rendering my charts, but there's some moment where my users can interact with the charts and change some `data` properties (including fill color and fill opacity) , to this to take effect immediately i call `validateData()`,
but I don't want to have the chart making the animation again, I want it more smooth possible. So can I disable all animations, validate new data, and then enable the animations again?

Or there is some other option that I can use to avoid that?

Example of the animation that I want to avoid (the user is clicking a bullet to select it and then making all other bullets with opaque):
![example](https://user-images.githubusercontent.com/32517249/54231945-52935700-44e8-11e9-8bd8-d0276ca226dc.gif)

**Comment by martynasma** [comment]
Try calling `invalidateRawData()` instead. It will just animate values from current ones to new ones. No jumping :)

**Comment by CalvinNunes** [comment]
But `invalidateRawData` will not change points or area colors. Or it will?

**Comment by martynasma** [comment]
Are you using `propertyFields` to change opacity/color of individual data items?

If that is correct, then no, `invalidateRawData` will not take in those new settings.

**Comment by CalvinNunes** [comment]
Yes I'm using... So, there's no way to 'deactivate' the animation or to change colors at runtime without `invalidating` all data and redrawing everything?

**Comment by martynasma** [comment]
I'm trying to reproduce this behavior, but can't.

Can you post a codepen of your chart that shows this behavior?

BTW, you don't need to call `validateData()` if you replace whole `data`.

If you change only few properties, you need to call `invalidateData()`.

**Comment by CalvinNunes** [comment]
The idea of my code is something like this: User select some data to inspect (value of sellings, quantity of products by month, year, etc...) then this data is displayed in a chart (Amchart), this Data can be customized, user can choose line color, bullet color, almost everything. 
When the user clicks one of the bullets, I need to show him that that bullet is "selected", so I need to change the color of all other bullets and also get this bullet value to pass to a "drill-down" in another chart, user can inclusive select more than one bullet while holding ctrl.  

The bullet creation code have this (some parts are cutted off because it is a really big code)
```
template.events.on("hit", this.OnClickPoint.bind(this, chartSerie));
template.circle.radius = toDecimal(this.DotSize);
template.tooltipHTML = "{ToolTip}"; 
template.propertyFields.fillOpacity = "alpha";
template.defaultState.propertyFields.fillOpacity = "alpha";
template.propertyFields.isActive = "IsSelected";

```

This is the "OnClickPoint" function:
```
 var clicked = event.target;
 var dataItem = clicked.dataItem
 if (filled(dataItem)) {
     var point = dataItem.dataContext;
     point.IsSelected = true;
     this.SelectedItems.push(point).;
     this.AdjustSelectedVisual(chartSerie);
     if (filled(this.OnClickItem)) {
        this.OnClickItem.call(this, point);
     }
}
```

and this is the "AdjustSelectedVisual"function:

 ```
var data = this.amChart.data;

 for (var i = 0; i < data.length; i++) {
      var point = data[i]
      point.IsSelected = false;
      point.alpha = this.SelectedItems.length > 0 ? 0.2 : 1;
  }

  for (var i = 0; i < this.SelectedItems.length; i++) {
      var pointSel = this.SelectedItems[i]
      pointSel.alpha = 1;
      pointSel.IsSelected = true;
  }
        
 this.amChart.validateData(); //<--- HERE HAPPENS THE ANIMATION EFFECT THAT I DONT WANT
```


I'm also open for new ideas on how to build this, but for real, my code have many more functions and callbacks, so it's not easy to modify it or change its structure. Also, this function change just the opacity and the "Selected" property, but other functions change colors and values.

**Comment by tprochazka** [comment]
I also would like to skip the initially shown animation, but then I want to have all other animation and not found a way how to do it.

**Comment by AlexanderArvidsson** [comment]
I am having the same issue, as well as the issue described in #826 and would really appreciate some sort of fix or workaround for this.

Why are the points even animating in the first place, when their positions have not been changed?
This sounds like a bug in the package, does it not?

**Comment by martynasma** [comment]
To disable initial animation of series, you can use `showOnInit`:

```
series.showOnInit = false;
```

**Comment by tprochazka** [comment]
I just tried showOnInit and it looks that it has no effect, data are still animated.

**Comment by jungti1234** [comment]
@martynasma @tprochazka same situation. I didn't use theme and I used 'showOnInit' for all series but still animated. any solutions yet?

**Comment by CalvinNunes** [comment]
Still same problem on 4.9.9... any solutions?

**Comment by zarir94** [comment]
Did you guys find any solution for this? I'm on version 5
