### ISSUE TITLE
Put a JSON chart into a Container

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#1064]
Studying [this](https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/#Adding_charts_to_containers), and it seems to indicate that .createFromConfig() cannot be used with containers? I can't find a way to add JSON charts into a container.

Here's a [codepen](https://codepen.io/npc42/pen/rRYGxZ) where I tried several approaches:
1. Pass Container as 2nd argument into .createFromConfig (instead of id string) — error
2. Create chart in an outside div, and then try to add to container (via chart.parent, or container.children) — chart is moved to container, but truncated.
3. Try to add id attr to a Container manually, and pass to .createFromConfig() — as far as I can tell, id is being added, but it still results in error.

Most reasonable approach seems to process container instead of id in .createFromConfig(), as far as I remember you allowed such flexibility in V3.

PS The problem I try to solve is somehow unify chart and scrollable legend into a same unit (wrap them in a container) to make them easier to handle. I so wish you just added scrolling to the built-in legend :)

PPS Btw, Instance.createFromConfig shows up in docs search, but the page is not available: https://www.amcharts.com/docs/v4/reference/instance/#createFromConfig_method

**Comment by martynasma** [comment]
That scrollable legend part got me confused a bit. amCharts 4 containers cannot be scrollable, so I'm not entirely sure what you are trying to achieve.

Yes, I did read what you wrote, but still probably missing something.

Were you able to achieve what you need using object-based syntax perhaps?

**Comment by NPC** [comment]
Yeah, sorry, I was just trying to provide context. With the ability to include external legend in export I hoped that finally I'll be able to use it, but I still can't find a way to include it together with a chart — I hoped to create a container for layout, inside it one for the chart (JSON), and one for a div with legend, which would have scrolling in it.

From your reply I think that I may get disappointed once I try to get a div into a container :( I guess I should have started with that part, not with the chart.

Object-based is not available for me, we generate dynamic JSON charts server-side based on user settings. I hoped to add just minor processing on the client to split chart / legend into containers. Probably a bad plan.

**Comment by martynasma** [comment]
Sorry for the silence.

Correct, you won't get a `<div>` into a chart's `Container`. So this whole setup might not be a good idea after all.
