### ISSUE TITLE
Ability to zoom further in on map

### ISSUE THREAD

**Issue by grasmachien** [amcharts/amcharts4#1069]
Would it be possible to let user zoom further in on the map?

https://www.amcharts.com/demos/multi-series-map/
When zooming in on Belgium on the map in this example you will notice that the country stays pretty small.

I have not found an option or parameter to change this.

Thanks in advance!

**Comment by martynasma** [comment]
That parameter you did not find is `maxZoomLevel` ;)

https://www.amcharts.com/docs/v4/reference/mapchart/#maxZoomLevel_property

**Comment by grasmachien** [comment]
Nice.
Thanks!
