### ISSUE TITLE
Some mistakes in docs

### ISSUE THREAD

**Issue by Hamcker** [amcharts/amcharts4#1070]
I was just reading [docs for JSON-based configuration](https://www.amcharts.com/docs/v4/concepts/json-config/) which found this:
In [this](https://www.amcharts.com/docs/v4/concepts/json-config/#Type_of_the_object) section, the type of Series is written into wrong place I think.

`{"series": [{"dataFields": {"type": "LineSeries", "value": "revenue", "category": "department"}}]}`

should be something like: 

`{"series": [{
    "type": "LineSeries",
    "dataFields": {
      "value": "revenue",
      "category": "department"
    }
  }]}`

**Comment by martynasma** [comment]
You're absolutely right. Thanks for the heads up!

Docs fixed.
