### ISSUE TITLE
Issue in XY chart for date  showing dates one date previous

### ISSUE THREAD

**Issue by gomteshhatgine** [amcharts/amcharts4#1071]
I am using amchart 4 XY chart

But after bind data dates are showing in chart in wrong i.e. One date previous of actual date

for following example:
July 26 for value 13

July 27 for value 11 like wise i.e. date showing one date previous

       `chart.data = [{
            "date": "2012-07-27",
            "value": 13
        }, {
            "date": "2012-07-28",
            "value": 11
        }, {
            "date": "2012-07-29",
            "value": 15
        }, {
            "date": "2012-07-30",
            "value": 16
        }];

        // Set input format for the dates 
        chart.dateFormatter.inputDateFormat = "yyyy-MM-d";

        // Create axes
        let dateAxis = chart.xAxes.push(new am4charts.DateAxis());
        let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

        // Create series
        let series = chart.series.push(new am4charts.LineSeries());
        series.dataFields.valueY = "value";
        series.dataFields.dateX = "date";
        series.tooltipText = "{value}"
      
        //series.minBulletDistance = 15;

        // Drop-shaped tooltips
        series.tooltip.background.cornerRadius = 20;
        series.tooltip.background.strokeOpacity = 0;
        series.tooltip.pointerOrientation = "vertical";
        series.tooltip.label.minWidth = 40;
        series.tooltip.label.minHeight = 40;
        series.tooltip.label.textAlign = "middle";
        series.tooltip.label.textValign = "middle";

        // Make bullets grow on hover
        let bullet = series.bullets.push(new am4charts.CircleBullet());
        bullet.circle.strokeWidth = 2;
        bullet.circle.radius = 4;
        bullet.circle.fill = am4core.color("#fff");

        let bullethover = bullet.states.create("hover");
       // bullethover.properties.scale = 1.3;

        // Make a panning cursor
        chart.cursor = new am4charts.XYCursor();
        chart.cursor.behavior = "panXY";
        chart.cursor.xAxis = dateAxis;
        chart.cursor.snapToSeries = series;`

**Comment by martynasma** [comment]
Can you double check which amCharts version you are running? We have fixed this issue very recently.

**Comment by jungti1234** [comment]
Is that really fixed? It seems still has some problem.
I'm using latest version now.

![제목 없음](https://user-images.githubusercontent.com/17401597/54737571-1355bc00-4bf4-11e9-8869-cd27ef60bf12.png)

and you can check this.
It may same problem or may not be with attached picture.

**Comment by gomteshhatgine** [comment]
After using latest version issue is resolved in my case

**Comment by martynasma** [comment]
@jungti1234 I'm not seeing the issue on your codepen. Have you cleared your browser cache?

**Comment by gomteshhatgine** [comment]
Issue is still there

**Comment by guruprasadpatil** [comment]
@martynasma,
@gomteshhatgine and I tried it on amchart4 but issue is still there. Chart accepts date but shows as one day less than actual value.
