### ISSUE TITLE
"a" for numberFormat doesn't work correctly, see example below

### ISSUE THREAD

**Issue by dk8996** [amcharts/amcharts4#1072]
Take a look at the example below.  The problem happens when there is data in small range with large number, it seems like it's not doing the right thing.

[Example](https://codepen.io/anon/pen/LaeJZO)

**Comment by martynasma** [comment]
Again, what's wrong with it?

Your format does not specify number of decimals, so they are displayed as they are calculated: in increments of 0.00005.
