### ISSUE TITLE
""###.###a" for numberFormat is not working correctly for the case with 3 "#"

### ISSUE THREAD

**Issue by dk8996** [amcharts/amcharts4#1073]
""###.###a" for numberFormat is not working correctly for the case with 3 "#".  See Example below.

[Example](https://codepen.io/anon/pen/wOpEJb)

**Comment by martynasma** [comment]
What's not correct about it?

Your numbers all result to 1.060 when rounded to tree decimal points. Since # is not mandatory, the zeroes at the end get shortened to 1.06, which is correct behavior.

If you need to absolutely keep all three decimals, you should use 0 (zero) instead: "###.000a"
