### ISSUE TITLE
Question about missing DateAxis labels

### ISSUE THREAD

**Issue by puyt** [amcharts/amcharts4#1075]
Hi, 

I'm trying out your library because it looks really advanced and I want to replace highcharts.

I don't understand why the xAxis labels aren't shown and the current gridInterval returns count `2` while I set a baseInterval of `1`. 

In my example there's enough space for 2 columns but not for a label ? Is there any way I can force to always show an xAxis label in DateAxis?

Thanks in advance.

https://codepen.io/puyt/pen/MxQmqV

**Comment by martynasma** [comment]
Thanks! ;)

The number (and density) of labels is determined by minimum pixel distance, governed by `minGridDistance`.

So, if you need more labels, packed closer together, decrease it:

```
dateAxis.renderer.minGridDistance = 30;
```

More info about controlling label density here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by puyt** [comment]
That's exactly what I needed, thanks :) 

I've got one more off-topic question: is there some documentation or tutorial that could help me to animate a switch between stacked & grouped column bars using a button? Changing the stacked property of a serie will break the chart.

**Comment by martynasma** [comment]
You mean something like this?

https://codepen.io/team/amcharts/pen/ePrjKz?editors=0010

**Comment by puyt** [comment]
This is indeed a great start!

Actually I wanted to create a toggle that animates the series down then change the stacked type to either `none` , `percent` or just `stacked` and then animate the series back up as in first render of the chart.

But your pen has most of the stuff I need, so now I can check out the docs on animations and play around with your example. Thanks! :+1: :smile:
