### ISSUE TITLE
DateAxis: Highlight week changes

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#1078]
The requirement I have it to highlight week changes (and show ISO week #) on a DateAxis of a zoomable chart.

From #614 I see that chart determines time granularity based on zoom, so in my case it starts with months, then weeks, then days. As I understand, period change formats are used to show units larger than the current zoom level. 

So, when at week zoom level, period changes are marked at months.

This is fine so far, but when I zoom to days level, month is used for period change, and I can't find a way to show week change formats. Can you please point me in the right direction?

Also, it seems that custom month's periodChange format is not used when on daily level — it uses the default.

Here's a [codepen](https://codepen.io/npc42/pen/qvxyVd?editors=0010) I used for my tests. Week labels are bold and all disappear when zoomed in.

**Comment by martynasma** [comment]
Well, when you zoom in, and chart goes into "day" mode, the "period change" is "month".

There's no setting to use weeks as periods in daily mode. 

There are a couple of options, though.

### Option 1

Use and adapter:

```
  "xAxes": [
    {
      "id": "dates",
      "type": "DateAxis",
      "dataFields": { "category": "date" },
      "dateFormats": {
        "day": "dd/MM",
        "week": "[bold]dd/MM (ww)",
        "month": "MMM YY"
      },
      "periodChangeDateFormats": {
        "week": "[bold]dd/MM (ww)",
        "month": "[bold]dd/MM (ww)"
      },
      "renderer": {
        "labels": {
          "adapter": {
            "textOutput": function(text, target) {
              if (target.dataItem && target.dataItem.date.getDay() == 1) {
                return target.dateFormatter.format(target.dataItem.date, "[bold]dd/MM (ww)");
              }
              return text;
            }
          }
        }
      }
    }
  ],
```

### Option 2

Disable "day" period altogether:

```
  "xAxes": [
    {
      "id": "dates",
      "type": "DateAxis",
      "dataFields": { "category": "date" },
      "dateFormats": {
        "day": "dd/MM",
        "week": "[bold]dd/MM (ww)",
        "month": "MMM YY"
      },
      "periodChangeDateFormats": {
        "week": "[bold]dd/MM (ww)",
        "month": "[bold]dd/MM (ww)"
      },
      callback: function(target) {
        this.gridIntervals.setAll([
          { timeUnit: "week", count: 1 },
          { timeUnit: "month", count: 1 },
          { timeUnit: "month", count: 2 },
          { timeUnit: "month", count: 3 },
          { timeUnit: "month", count: 6 },
          { timeUnit: "year", count: 1 },
          { timeUnit: "year", count: 2 },
          { timeUnit: "year", count: 5 },
          { timeUnit: "year", count: 10 },
          { timeUnit: "year", count: 50 },
          { timeUnit: "year", count: 100 },
          { timeUnit: "year", count: 200 },
          { timeUnit: "year", count: 500 },
          { timeUnit: "year", count: 1000 },
          { timeUnit: "year", count: 2000 },
          { timeUnit: "year", count: 5000 },
          { timeUnit: "year", count: 10000 },
          { timeUnit: "year", count: 100000 }
        ]);
      },
    }
  ],
```

**Comment by NPC** [comment]
@martynasma 

This is great help, thank you!

Adapters looks like the best solution for now, though I wonder about option 2 — I expected it would remove zoom granularity level that would display day labels (say, as it only shows monthly labels at “month” zoom level, but still shows daily chart entries), instead it [sums up daily values into weekly items](https://codepen.io/npc42/pen/PLRygq?editors=0010).

Is there a description of gridIntervals prop? Only mention in search is the [DateAxis class doc](https://www.amcharts.com/docs/v4/reference/dateaxis/#gridIntervals_property), and it doesn't help (I know you've tried, and you always do an excellent job, but in this case I can't comprehend it). What does a single unit/count pair signify, exactly?

PS Did you notice from my earlier comment that custom period change format for month is not used in my [original codepen](https://codepen.io/npc42/pen/qvxyVd?editors=0010)?

**Comment by martynasma** [comment]
Well, no that I'm thinking about it maybe second option is not very good, since it also affects how DateAxis thinks of each cell - resulting in number of days put in the same day.

Basically `gridIntervals` define all options for what a single cell/increment on axis can represent. If we eliminate everything below week, than a single cell cannot be a day, it'll be a week.

When you have a lot of data in a visible span, it might start going up that list and each cell starting to represent a month, etc.

I agree, it's a bit overwhelming without knowing internals. It probably deserves a tutorial. Making a note to create one :)

I suppose monthly `periodChangeDateFormats` is not used because in month mode, a "period change" is start of the year, and you don't have that in your data.

**Comment by NPC** [comment]
@martynasma understood, thanks for looking into this. It'd be nice to have a bit more control over labels shown — as we zoom into the chart, it seems to intelligently decide that it shows only month labels, then week labels, then daily labels, as space allows — all this time showing daily values. If we could tell it — don't go to daily labels.

Anyway, your suggested option 1 with adapters and week's start still works for me, so you've been very helpful, as always.

**Comment by NPC** [comment]
@martynasma monthly label is gone after I added "day" format to periodChangeDateFormats — I guess the property name defines zoom granularity at which the label is shown, not which label it is, I am confused but glad I found a solution :)
