### ISSUE TITLE
Cannot scroll over a map 

### ISSUE THREAD

**Issue by jakeleventhal** [amcharts/amcharts4#1081]
When using a map chart, I have the following code

```
// Disable panning and zooming
this.map.seriesContainer.draggable = false;
this.map.seriesContainer.resizable = false;
this.map.maxZoomLevel = 1;
```

This gives some of the behavior that I want, disabling zooming/panning.

The other behavior that I want is that the user can still scroll on the map to move up and down the webpage. Currently, it just has no response and keeps the mouse stuck in place without moving the webpage up or down

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/tutorials/disabling-mouse-wheel-zoom-in-maps/
