### ISSUE TITLE
numberFormatter instance isn't unique for each yaxis instance!

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1086]
Hey I have an example here of multi-axis graph, where there is 2 yaxis: fakePrecent & kwhYaxis.
kwhYaxis should have a numberFormatter which assign kw units for each yaxis value,
fakePrecent should have a numberFormatter which assign % units for each yaxis value.
Apparently the last one instance of numberFormatter(with kw units) of the yaxis reflect on previous yaxis also.
This is a strange behavior and unwanted result,
I think that it is may be a bug.
Here is the reproduction of this scenario:
https://stackblitz.com/edit/angular-uqxg9h

**Comment by martynasma** [comment]
It's not a strange behavior. It's by design.

All objects inherit same NumberFormatter instance from the chart. It's so that you don't have to set formats in multiple places.

If however, you need something unique in some place, you can create a new `NumberFormatter` instance there.

```
axis.numberFormatter = new am4core.NumberFormatter();
axis.numberFormatter.numberFormat = "####"; // <-- this is unique to this particular axis
```

https://www.amcharts.com/docs/v4/concepts/formatters/#Individual_formatters

**Comment by BrkCoder** [comment]
hey @martynasma can I solve this issue from my json config only without typescript?

**Comment by martynasma** [comment]
Yes:

```
"yAxes": [{
  // ...
  "numberFormatter": {
    "type": "NumberFormatter",
    "numberFormat": "####"
  }
}]
````

**Comment by BrkCoder** [comment]
@martynasma if understand correctly for json base config, the type keyword is crucial for creating new instance of elements? correct me if I am wrong ?
In my original case I have missed the type keyword because I thought that numberformatter was a set of properties of valueaxis only.

**Comment by martynasma** [comment]
You are absolutely right. If there's `type` keyword, JSON parser takes it as an instruction to create a new object.

https://www.amcharts.com/docs/v4/concepts/json-config/#Creating_or_reusing_

**Comment by BrkCoder** [comment]
thanks!
