### ISSUE TITLE
How to differentiate two bubbles with the same 'x' and 'y' value. 

### ISSUE THREAD

**Issue by ashok3107** [amcharts/amcharts4#1087]
Have a need to show tooltips for all the bubbles with the same x and y values. However, I am not able to get it. Is there a way to achieve this? 

Code - https://codepen.io/anon/pen/aMKGbx

**Comment by martynasma** [comment]
No built-in functionality like that.

But doable with custom events.

Try hovering over right bullet:
https://codepen.io/team/amcharts/pen/MxXMOv?editors=0010
