### ISSUE TITLE
Venn Diagram support

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1088]
Do you think it's possible to integrate VennDiagram in amcharts ?

Like : https://github.com/benfred/venn.js

Thanks

**Comment by martynasma** [comment]
We do have Venn Diagram on our radar and will definitely implement it at some point.

However, I can't provide any ETA right now, I'm afraid.

**Comment by Identity-labs** [comment]
With commercial licence we can't have access protoype or beta or release candidate of the lib ?
We can help you for testing an feedback

**Comment by martynasma** [comment]
Dully noted. Appreciate your willingness in helping test it.

If there's some space for external testing, I'll ping you when we have something.

**Comment by Lenewtype** [comment]
If you need more external testers, my company has a commercial license for AmCharts 4 as well, and a need for a Venn Diagram module. I would be interested in helping test as well!

**Comment by martynasma** [comment]
With release of 4.9.0, Venn Diagram is now available.

More details:
https://www.amcharts.com/docs/v4/chart-types/venn/
