### ISSUE TITLE
Support for reactjs?

### ISSUE THREAD

**Issue by smartynov** [amcharts/amcharts4#109]
We have a commercial licence and use amCharts 3 with React, and we would like to switch to amCharts 4. We tried to do it ourselves, but it looks quite a bit tricky. Do you have plans to release an official plugin, such as amcharts3-react?

**Comment by martynasma** [comment]
We do, at some point. Just can't provide an ETA, yet.

Also, I'm sure you saw it, but let me link it here just in case, for anyone else viewing this thread:

https://www.amcharts.com/docs/v4/getting-started/integrations/using-react/
