### ISSUE TITLE
Enhancement: Support for bullet.copyToLegendMarker on ColumnSeries

### ISSUE THREAD

**Issue by bosiljkakostic** [amcharts/amcharts4#1090]
What is the easiest way that legend follows the bullets shape? I am trying to use 
 bullet.copyToLegendMarker, hoping that maker at legend will have the shape of bullets, but it not work on that way. The example is on 
https://jsfiddle.net/bosiljkakostic1/65echf0n/65/

**Comment by martynasma** [comment]
`ColumnSeries` does not copy bullets to its legend markers, because, well, it does not make a lot of sense.

I suggest you use `LineSeries` instead, since you don't show columns anyway. This type of series will automatically create bullets in legend, no additional configuration required.

**Comment by bosiljkakostic** [comment]
Thanks

**Comment by bosiljkakostic** [comment]
But I have a task to translate something like this from v3 to v3, and it has sense
![image](https://user-images.githubusercontent.com/48427836/54595935-f2466d00-4a33-11e9-88bd-1f1b15e24ddd.png)

**Comment by martynasma** [comment]
Hm, indeed.

We will consider adding support for bullet copying on `ColumnSeries`.

Meanwhile, I suggest you use `LineSeries` for bullets and have separate `ColumnSeries` for bars.

You can combine several series into a single legend item:
https://www.amcharts.com/docs/v4/tutorials/toggling-multiple-series-with-a-single-legend-item/

**Comment by bosiljkakostic** [comment]
Thanks, I will do it on that way

**Comment by bosiljkakostic** [comment]
When I use LineSeries I have to set valueX and valueY , but I have category and date, and it is not Intended for that

**Comment by bosiljkakostic** [comment]
Excuse me, it is ok,             series.dataFields.dateX  and series.dataFields.categoryY work well for line series

**Comment by bosiljkakostic** [comment]
I am trying to use LineSeries, but I have no shape of bullets copied in legend
https://jsfiddle.net/bosiljkakostic1/65echf0n/70/

**Comment by martynasma** [comment]
This is because of this line in your config:

```
chart.legend.useDefaultMarker = true;
```

**Comment by bosiljkakostic** [comment]
Thank you very much
