### ISSUE TITLE
Add zoom plus and zoom minus buttons

### ISSUE THREAD

**Issue by amit648** [amcharts/amcharts4#1092]
Hello,

I want to add custom zoom plus and zoom minus buttons in this below chart. Please help me on this pen.

[https://codepen.io/purvik7373/pen/KJyBgX](https://codepen.io/purvik7373/pen/KJyBgX)

Thanks

**Comment by martynasma** [comment]
With `CategoryAxis`:
https://codepen.io/team/amcharts/pen/VRBgjp?editors=0010

With `DateAxis`:
https://codepen.io/team/amcharts/pen/3db56ec332049201d6535f4a7ab355bc?editors=0010
