### ISSUE TITLE
maxHeight sets absolute height to bars

### ISSUE THREAD

**Issue by obsnomad** [amcharts/amcharts4#1094]
When I try to set maxHeight to absolute value (for example `series.columns.template.maxHeight = 100;`) it also affects the height property.
[What I see](https://i.ibb.co/gJS7cPT/2019-03-19-13-28-17.png)
[What I expect to see](https://i.ibb.co/StpMbL8/2019-03-19-13-42-13.png)

**Comment by martynasma** [comment]
Well, `maxHeight` is what determines actual height. The series itself uses `maxHeight` to instruct columns how big they can be. So if you set it to 100 that's what they "know" they can grow to.

I totally understand that it might be counterintuitive, and that you would expect `maxWidth` to act as a "cap".

At this point I can suggest using an adapter:

```
series.columns.template.adapter.add("maxHeight", function(height) {
  return height > 100 ? 100 : height;
});
```

**Comment by obsnomad** [comment]
@martynasma It's really confusing that such a simple thing is missing. I tried your solution but it doesn't work as expected - the bar sticks to the top (left in case of column chart) edge of its container. And I can't move it to the center by `series.columns.template.align`.
