### ISSUE TITLE
Question: why property-fields are ignored in tooltip scope for current series?

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1095]
Hey I have a basic linechart, where is value on the line should have a tooltip which shows its value,
the tooltip stroke background should be changed according to the color field in every dataitem.
This means that the propertyfields of background tooltip should be map stroke field into "color" field of dataitem.
I have reproduce this problem, I am apparently doing something wrong because the mapping should work out of the box:
https://stackblitz.com/edit/angular-dfhsz2

Any help is welcome!

**Comment by BrkCoder** [comment]
Hey amcharts team, I am really need a quick answer regarding this issue.
Thanks in advance!

**Comment by martynasma** [comment]
I am getting differently colored tooltips:
![2019-03-21_14-56-54](https://user-images.githubusercontent.com/1458520/54753393-9e7d8480-4be9-11e9-9095-466de293591c.gif)

What am I missing?

**Comment by BrkCoder** [comment]
ok you can closed this issue
