### ISSUE TITLE
Standalone version at amcharts.com is still 4.2.2

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts4#1097]
Here because of the "Exporting via API from a chart that did not have ExportMenu set, was resulting in error" introduced in 4.2.2.  I see this was fixed in 4.2.3, but standalone downloads are still showing 4.2.2 at www.amcharts.com/download/.  

I can get source here, but don't need the 'extra' and would need to change a lot of paths.  Is there any reason the latest release isn't always compiled/listed at www.amcharts.com?

**Comment by martynasma** [comment]
Oh boy, our bad :)

Fixed now.

**Comment by morrow95** [comment]
@martynasma Thank you!
