### ISSUE TITLE
Syntax Error when creating barchart3D

### ISSUE THREAD

**Issue by ryanmakiling26** [amcharts/amcharts4#1099]
I found syntax error in javascript while initializing 3D Barchart.

Please see the attached file.

I'm using IE 11 and it shows this error below

![3DBarChart](https://user-images.githubusercontent.com/45944073/54671788-9235f080-4b31-11e9-9d4e-2245b422d5db.JPG)

**Comment by martynasma** [comment]
IE does not support ES6 local function syntax.

Instead of this:

```
... (fill, target) => { ...
```

Use this:
```
... function(fill, target) { ...
```

**Comment by ryanmakiling26** [comment]
@martynasma, I have tried to remove '=>'. Now I got this error. " Expected ')' "
Awaiting for your reply. Thank you

**Comment by ryanmakiling26** [comment]
I get it haha thanks a lot! cheers to you!
