### ISSUE TITLE
Legend marker cornerRadius via createFromConfig

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1100]
How to set cornerRadius from Config to markers ?

I have try a lot of configuration but none work's
I want to have a rounded marker

`{legend: {
markers: {
width: 9,
height: 9,
strokeWidth: 0,
cornerRadiusTopLeft: 9,
cornerRadiusTopRight: 9,
cornerRadiusBottomRight: 9,
cornerRadiusBottomLeft: 9
},
labels: {
position: "right",
template: {
text: "{name}",
fill: "#FFFFFF"
}
},
valueLabels: {
template: [ ]
},
itemContainers: {
template: {
width: "100%"
}
},
position: "bottom",
fontSize: "10"
}}`

Thx

**Comment by martynasma** [comment]
Normally, legend tries to mimic look of the markers, hence ignoring own marker settings.

To have completely custom markers use `useDefaultMarker: true`:

https://www.amcharts.com/docs/v4/concepts/legend/#Default_markers

**Comment by Identity-labs** [comment]
I can't change cornerRadius with the factory createFromConfig

**Comment by martynasma** [comment]
If by "factory" you mean "default", then default setting for `useDefaultMarker` is `false`. You need to explicitly set to `true` for being able to configure markers.

**Comment by Identity-labs** [comment]
He does't work very well 

https://codepen.io/anon/pen/JzerBj
