### ISSUE TITLE
AxisLabel (DateAxis): Custom date adapter for range

### ISSUE THREAD

**Issue by dror-weiss** [amcharts/amcharts4#1102]
I think it would be very useful to see an adapter on the AxisLabel (for the DateAxis) that provides a range formatter between the current point and next one.

One obvious example is week range, e.g. "March 13 - 19".

In order to accomplish this I'm doing the following patch:
    
    import addDays from "date-fns/addDays";
    import startOfDay from "date-fns/startOfDay";
    import parseISO from "date-fns/parseISO";
    import format from "date-fns/format";
    ...
    ...
    const dateAxis = this.createDateAxis(chart);
    dateAxis.baseInterval = (() => {
        let timeInterval: am4core.ITimeInterval = {timeUnit: "day", count: 1};

        switch (viewPeriod) {
          case ViewPeriod.Daily:
            timeInterval = {timeUnit: "day", count: 1};
            break;
          case ViewPeriod.Weekly:
            timeInterval = {timeUnit: "day", count: 7};
            break;
          case ViewPeriod.Monthly:
            timeInterval = {timeUnit: "day", count: 28};
            break;
        }

        return defaultTimeInterval;
    })();

    // Format daily view.
    dateAxis.dateFormats.setKey("day", "YYYY-MM-dd:EEE\nMMM d");
    dateAxis.periodChangeDateFormats.setKey("day", "YYYY-MM-dd:EEE\nMMM d");

    // Format weekly view.
    dateAxis.dateFormats.setKey("week", "YYYY-MM-dd:YYYY-MM-dd");
    dateAxis.periodChangeDateFormats.setKey("week", "YYYY-MM-dd:YYYY-MM-dd");

    // Format monthly view.
    dateAxis.dateFormats.setKey("month", "YYYY-MM-dd:MMM YYYY");
    dateAxis.periodChangeDateFormats.setKey("month", "YYYY-MM-dd:MMM YYYY");

    // Change the label. Use ":" as separator to get original date and original format.
    dateAxis.renderer.labels.template.adapter.add("text", (text) => {
        if (text === undefined) {
          return undefined;
        }

        const splittedText = text.split(":");
        const originalDate = parseISO(splittedText[0]);
        const originaFormat= splittedText[1];

        switch (viewPeriod) {
          
          case ViewPeriod.Daily:
            return originaFormat;
          
          case ViewPeriod.Weekly: {
            const startDate = new Date(originalDate.getTime());
            const endDate = addDays(startDate, 7);
            const sameMonth = (startDate.getMonth() === endDate.getMonth());
            if (sameMonth) {
              return `${format(startDate, "MMM d")} - ${format(endDate, "d")}`;
            }
            const differentYear = (startDate.getFullYear() !== endDate.getFullYear());
            if (differentYear) {
              return `${format(startDate, "MMM d, yyyy")} - ${format(endDate, "MMM d, yyyy")}`;
            }
            return `${format(startDate, "MMM d")} - ${format(endDate, "MMM d")}`;
          }
          
          case ViewPeriod.Monthly: {
            return originaFormat;
          }
        }

        throw new Error("formatter for view period not supported");
      });

Any thoughts on the issue? Perhaps there's a better way?

**Comment by martynasma** [comment]
How about checking if this label is coming from a range or a simple label?

```
dateAxis.renderer.labels.template.adapter.add("text", (text, target) => {
  if (target.dataItem.isRange) {
    // range
    // ...
  }
  else {
    // regular label
    // ....
  }
});
```
