### ISSUE TITLE
HeatMap with Date Axis and Value Axis

### ISSUE THREAD

**Issue by rdibenedetto** [amcharts/amcharts4#1104]
The idea in the following Pen is to create an Heatmap with a dateAxis on X and a valueAxis on the Y.
If you see the Pen you can see there isn't points between 11:00:00 and 20:00:00. 
Is there one way to extend the column of the 11:00:00 until we found another point? 
in this case 20:00:00 in order to don't leave any blank space between the points.
I need to use valueAxis and dateAxis and not CategoryAxis because I could integrate some points after the render

The link of the Pen is: https://codepen.io/roger710/pen/WmaxGB

**Comment by martynasma** [comment]
How about using `skipEmptyPeriods`?

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Removing_empty_time_units

**Comment by rdibenedetto** [comment]
I saw it, but I don't want use it because I lost the timeline proportion

**Comment by martynasma** [comment]
Hm, in that case don't have any other suggestion :(
