### ISSUE TITLE
Hide elements on orthographic map rotation

### ISSUE THREAD

**Issue by EdoRguez** [amcharts/amcharts4#1107]
Hi, I'm using a map chart that uses orthographic projection. When you rotate the map, all countries and lines hide at the border, that works perfectly. 

My problem is, as lines and countries do, is there a way to hide elements when you rotate an orthographic map?

I have planes and cities made by svg circles, but I don't get the way to hide them when you rotate the map.

This works for me, but not perfectly.

```
    cities.events.on("validated",function(ev)
    { 
        var degreesLeft = chart.deltaLongitude + 90;
        var degreesRight= chart.deltaLongitude - 90;

        if(myCity.longitude < degreesLeft && myCity.longitude > degreesRight){
            myCity.hide();
            myPlane.hide();
        }
        else{
            myCity.show();
            myPlane.show();
        }
    })
```

**Comment by martynasma** [comment]
`MapLineSeries` with `shortestDistance = true` will be cut off over the horizon.

`MapImageSeries` also support Orthographic projection meaning that any images on the opposite side of the globe will be automatically hidden. This applies to the the places as well.

I'm afraid I'm not entirely sure why you might need this code.

https://codepen.io/team/amcharts/pen/6e382e25fe0b4fa7cd1ae24f255531cf?editors=0010
