### ISSUE TITLE
XYCandlestick Y Axis Not Loading Properly

### ISSUE THREAD

**Issue by rusty-banks** [amcharts/amcharts4#1112]
Hi,

I have tried everything but this chart does not load properly.

https://codepen.io/anon/pen/GezrVx

The y axis is way too zoomed in to see the data. When I zoom out, the chart appears fine.

Could you please suggest what is wrong here?

**Comment by martynasma** [comment]
The issue is related to your data coming in descending order. The chart needs it to be in ascending order, hence the anomaly.

Do this to fix:

```
chart.data = [
  // ....
].reverse();
```

**Comment by rusty-banks** [comment]
Perfect. Thanks a lot. :)
