### ISSUE TITLE
Seems like bubble based heat map hover over and cursor are broken

### ISSUE THREAD

**Issue by dk8996** [amcharts/amcharts4#1114]
It seems like in bubbled based heat map the hover over breaks when enabling cursor.  See example below.

[Example](https://codepen.io/anon/pen/jJJRwJ)

![image](https://user-images.githubusercontent.com/2559655/54944298-8ec3b000-4f09-11e9-8155-6b813bb8c2cf.png)

**Comment by zeroin** [comment]
You should set `series.cursorTooltipEnabled = false;` for this example to work properly.
