### ISSUE TITLE
EventDispatcher is disposed Error on the TreeMap chart

### ISSUE THREAD

**Issue by yvelianyk** [amcharts/amcharts4#1115]
"EventDispatcher is disposed" error appears randomly on the TreeMap chart. 
It happens after dynamically setting the new data to the chart.
I've tried to call `chart.invalidateData()` method after setting the new data, but it does not help.

Version: latest

**Comment by yvelianyk** [comment]
JFYI, we dynamically change the whole data set.

**Comment by yvelianyk** [comment]
I suppose it can be caused by a memory leak in the AmCharts library. I've created a [pen](https://codepen.io/yvelianyk/pen/OqGgrm?&editable=true) with dynamically setting data into the TreeMap chart, and I see that memory of the browser tab is constantly growing. In my case, this issue is reproducible after setting new data to the chart a lot of times. Please, let me know is it some workaround

**Comment by martynasma** [comment]
Does this happen in all browsers?
Approximately how long do you have to keep this pen open for the issue to kick in?

Just trying to reproduce this.

**Comment by yvelianyk** [comment]
I've tested it only in Chrome. Approximately it 5-10 mins. Also, I've additional testing info. "EventDispatcher is disposed" Error appears when the new data set is applied to the chart at the moment when TreeMap chart is zoomed (drilled down). I've tried to reproduce it in the pen, but without success.

**Comment by yvelianyk** [comment]
Also, I can't figure out how to zoom out TreeMap chart. There is `goHome` method in the map chart type. Is there something similar in the TreeMap chart?

**Comment by yvelianyk** [comment]
Please, take a look at this [pen](https://codepen.io/yvelianyk/pen/OqGgrm?&editable=true) and open memory monitor. Memory constantly growing on 20-25 Mb every 2 seconds(interval time).

**Comment by yvelianyk** [comment]
I close this issue as I've created 2 separate ones. 
About memory leak: [link](https://github.com/amcharts/amcharts4/issues/1127)
About chart crash: [link](https://github.com/amcharts/amcharts4/issues/1125)
