### ISSUE TITLE
bent does not work with wrap or truncate

### ISSUE THREAD

**Issue by jimitm10** [amcharts/amcharts4#1120]
I want to wrap the label also i want to bent the label along the circle.
Wrap works fine if i dont use bent but if i use bent wrap does not work

**Comment by notacouch** [comment]
### Quick test w/ `wrap`

Seems to clip the label vertically even though its `maxHeight` is `300` by default and `measuredHeight` is `288`.

#### Screenshot:
![image](https://user-images.githubusercontent.com/2334143/55374383-44789b00-54d6-11e9-8ba0-573d6ff5ba83.png)

#### Demo:
https://codepen.io/team/amcharts/pen/aa86514b97570435412980b4051970e0

### Quick test w/ `truncate`

Seems to work fine?

#### Screenshot:
![image](https://user-images.githubusercontent.com/2334143/55374499-ab964f80-54d6-11e9-8ea9-90834d2e8caf.png)

#### Demo:
https://codepen.io/team/amcharts/pen/b3de2faeae761c67ce45f975f4846bd9

**Comment by jimitm10** [comment]
I am trying to apply bent along with wrap or truncate in below demo example.

https://www.amcharts.com/demos/radar-timeline/

It is not working for categoryAxisLabel.
Can you please help me out here.

**Comment by martynasma** [comment]
There's no good way to measure "length" of a bent text.

When we have horizontal text it's easy to measure whether it fits into certain width.

Not so with text that follows a curve.

It would still try to use its `width` and try to truncate itself if resulting width does not fit, as per @notacouch example above. But that can work in any roughly reasonable way only for horizontal text.

There's no good built-in way to do truncate bent labels.

The only workaround I can think of is to use adapters to clip the text to certain character count, e.g.:

```
axisRange.label.adapter.add("textOutput", function(text) {
  return am4core.utils.truncateWithEllipsis(text, 20, "...");
});
```
