### ISSUE TITLE
Angular Gauge and Bullet Chart

### ISSUE THREAD

**Issue by debajyotidey** [amcharts/amcharts4#1124]
I am putting the end/max value to 126 with "strictMinMax = true;" . The range creates but the labels not showing. Its showing 120 last.

**Comment by martynasma** [comment]
Axis does not put labels at arbitrary values, I'm afraid.

I suggest you use an axis range to put labels where you need them to be.

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/
