### ISSUE TITLE
Enhancement: Multi-line legend not arranged into columns

### ISSUE THREAD

**Issue by bosiljkakostic** [amcharts/amcharts4#1126]
I have this:
![image](https://user-images.githubusercontent.com/48427836/55222618-a7cfa800-520c-11e9-8f15-ea928665e76b.png)
but I want this:
![image](https://user-images.githubusercontent.com/48427836/55223009-84592d00-520d-11e9-9d77-3203c170fffe.png)
in amcharts v3 it was "equalWidths": false, I tried 
chart.legend.fixedWidthGrid = false; but it do not work. Please help me to find solution

**Comment by bosiljkakostic** [comment]
example : https://jsfiddle.net/bosiljkakostic1/65echf0n/138/

**Comment by martynasma** [comment]
There's no direct equivalent of `equalWidths` in v4. The layout of the legend is always grid :(

**Comment by martynasma** [comment]
BTW, `fixedWidthGrid` does work, just not the same way as you probably expect.

If it's not set to `false` then all columns in the legend would be equal width.

**Comment by bosiljkakostic** [comment]
How I can change individual legend.itemContainers width to actual space occupied

**Comment by bosiljkakostic** [comment]
How can I change individual legend.itemContainers width to actual space occupied

**Comment by bosiljkakostic** [comment]
fixedWidthGrid do not work in any way, this is a picture of a real example, and legend is same either fixedWidthGrid is true or false
![image](https://user-images.githubusercontent.com/48427836/55305664-b1961d00-5451-11e9-9492-8b01901cc27b.png)

**Comment by bosiljkakostic** [comment]
I have blank space in the first column, and all columns are equal width

**Comment by martynasma** [comment]
> I have blank space in the first column, and all columns are equal width

This is how your example looks like:
![image](https://user-images.githubusercontent.com/1458520/55322950-52063480-5486-11e9-956f-c16ee608aa1f.png)

Columns are not same width.

If you can provide similar fiddle for that second chart, I could take a look at it as well.

> How can I change individual legend.itemContainers width to actual space occupied

As I mentioned earlier, no way :(
