### ISSUE TITLE
When I use configField to fill series or bullets, legend color is not correct

### ISSUE THREAD

**Issue by bosiljkakostic** [amcharts/amcharts4#1128]
When I use configField to fill series or bullets, legend color is not correct
example
https://jsfiddle.net/bosiljkakostic1/65echf0n/146/

**Comment by notacouch** [comment]
Legends get their `fill` from their series' `fill`.

The bullets' colors are irrelevant for the legend (how would the chart know which bullet to grab color data from?).

I am not sure what the expectation is for the `configField` to work for the series, its data applies to its plots/bullets in this case, there isn't a way for the chart to say, hey, for the series, pick this `config` field from this random point in the array

However, if you instead set `series[i].fill = colors[i]`, then the legend items will properly reflect said color.

Example:
https://jsfiddle.net/notacouch/q5t0kn3f/

**Comment by bosiljkakostic** [comment]
Thanks,
I have set bullets[i].copyToLegendMarker = true; I usually have colors in the database, and I read it from tables, but I can extract colors, so I can resolve this
