### ISSUE TITLE
Setting color from default list to Axis doesn't work

### ISSUE THREAD

**Issue by dk8996** [amcharts/amcharts4#1129]
Setting the color from the default chart list doesn't seem to work.  See example below.  Seems like the color is lazy loaded.

Works 
`distanceAxis.renderer.labels.template.fill = am4core.color("#ff0000");`

This doesn't work
`distanceAxis.renderer.labels.template.fill = chart.colors.list[0];`

[Example](https://codepen.io/anon/pen/EJYmej)

**Comment by martynasma** [comment]
Directly accessing `list` is not safe, since it will not trigger its population with values (if that's what the issue here).

Much safer way is to use `getIndex()` method:

```
distanceAxis.renderer.labels.template.fill = chart.colors.getIndex(0);
```
