### ISSUE TITLE
Efficient way to change color and data of countries in MapChart?

### ISSUE THREAD

**Issue by delaaxe** [amcharts/amcharts4#1131]
First of all thanks for this great library!

I have an application where I'm displaying a map of the world with amCharts 4 and high resolution geo data.

I'm using 2 `MapPolygonSeries`:
- one with all countries except antarctica in gray
- another one with a subset of countries displayed in blue

Whenever I need to update which countries are displayed in blue, I remove the second series with removeIndex() and add a new series with other countries. This works fine although there's a noticeable delay (~500ms) that's blocking UI. This is undesirable and I assume it happens because of the SVG is being re-rendered.

I tried mutating the `include` array on the second `MapPolygonSeries` but this didn't seem to have any effect. Am I doing something wrong or is there a better way to achieve this?

**Comment by martynasma** [comment]
That sounds very inefficient.

Why not have one `MapPolygonSeries` and set colors for each country individually?

https://www.amcharts.com/docs/v4/chart-types/map/#Binding_properties_to_data

Or if you need to change the color on the fly:

```
polygonSeries.getPolygonById("FR").fill = am4core.color("#f00");
```

**Comment by delaaxe** [comment]
Thanks martynasma. How would I apply a heat rule on the fly in the same manner?

**Comment by martynasma** [comment]
OK, so are you applying heat rules or custom colors to some countries individually?

**Comment by delaaxe** [comment]
I currently have 2 series:
- one with all countries as a gray "background"
- one with some countries using a heat rule

I'm looking for a way to optimize that since it seems to be slow because of the double rendering of some countries

**Comment by martynasma** [comment]
In that case probably the best way to update heat rule data is to update `data` for the series, then call its `invaldiateData()` method.

**Comment by delaaxe** [comment]
Thanks I'll try this out!
