### ISSUE TITLE
Multiple bullets is not showing when data is set to serie

### ISSUE THREAD

**Issue by bosiljkakostic** [amcharts/amcharts4#1132]
If I set data to shart, and I have multiple values for the same category, all bullets are showing; but when I separate data and set data for series it does not work correctly
The example is at
https://jsfiddle.net/bosiljkakostic1/jp5476t0/13/
In that example, Peter should be represented with two red arrows and one green circle, but he has only one arrow

**Comment by martynasma** [comment]
```
  {
    name: "Peter",
    fromDate: "2018-01-01 20",
    fromDate: "2018-01-01 22",
  },
```

This doesn't look right. Shouldn't it have `toDate` in place of the second `fromDate`?

**Comment by bosiljkakostic** [comment]
Yes, thanks, I changed that, and it is showing but so small so, that is almost invisible
link is 
https://jsfiddle.net/bosiljkakostic1/jp5476t0/15/

**Comment by martynasma** [comment]
Try removing this line:

```
dateAxis.strictMinMax = true;
```

**Comment by bosiljkakostic** [comment]
thanks
