### ISSUE TITLE
Circles outside of the plot area

### ISSUE THREAD

**Issue by prostoandrei** [amcharts/amcharts4#1134]
Hello!

I'm trying to make active bubbles on a hit and my circles appeared outside of the plot area.
Is there a way to handle it somehow? Or it's a bug?

Here are screenshot and example on jsFiddle from your demo charts:
http://jsfiddle.net/prostoandrei/zvgsLqkp/2/

![image](https://user-images.githubusercontent.com/7234499/55383207-4a9b6580-5530-11e9-95f6-78b3a580ac4e.png)

Thank you :)

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/concepts/bullets/#Bullets_outside_plot_area

**Comment by prostoandrei** [comment]
@martynasma yes, I saw this option. But I want to cut bullets and circles. With `chart.maskBullets = true;` it cuts only bullets, but not circles.

**Comment by martynasma** [comment]
Um, what's the difference between a "bubble" and "circle"? :)

Maybe you can add your circles to `chart.bulletsContainer` instead of `plotContainer`?
