### ISSUE TITLE
World map doesn't center in container

### ISSUE THREAD

**Issue by maurycyg** [amcharts/amcharts4#1135]
Last known version where this worked is 4.2.6 and map does centre in a container
![image](https://user-images.githubusercontent.com/701197/55389035-5edd6380-552c-11e9-9a57-80bb6033f98a.png)
while in the latest version it positions itself in the top left corner
![image](https://user-images.githubusercontent.com/701197/55389225-b8de2900-552c-11e9-8d93-f08603c2997c.png)

**Comment by martynasma** [comment]
Do you have a working example? I suspect there might be some error happening before centering takes place, but I can't seem to be able to reproduce it.
