### ISSUE TITLE
How to switch scrollbar from top to bottom? 

### ISSUE THREAD

**Issue by bloodchow** [amcharts/amcharts4#1136]
```
var scrollbarX = new am4charts.XYChartScrollbar();
scrollbarX.series.push(lineSeries);
chart.scrollbarX = scrollbarX;
```

How to make the scrollbar go to chart bottom?

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/tutorials/setting-position-of-the-chart-scrollbars/

**Comment by bloodchow** [comment]
> https://www.amcharts.com/docs/v4/tutorials/setting-position-of-the-chart-scrollbars/

That was quick reply, gotcha : 

```
var scrollbarX = new am4charts.XYChartScrollbar();
scrollbarX.series.push(lineSeries);
chart.scrollbarX = scrollbarX;
chart.scrollbarX.parent = chart.bottomAxesContainer;
```
Thanks martynasma!

**Comment by ravitejamajeti** [comment]
Quick question related to this chart.

How to get the zoomed in chart start and end dates. Suppose, in the above demo chart, if I am zoomed in between 15th Jan 2017 to 23rd Feb 2017. How to extract those start and end dates?

Thanks

**Comment by martynasma** [comment]
@ravitejamajeti Please open a new thread if you have questions. Do not hijack someone else's. It's not in any way related to to the position the scrollbar.
