### ISSUE TITLE
Special character on tooltipText

### ISSUE THREAD

**Issue by rodrigobastosv** [amcharts/amcharts4#1137]
I'm having trouble using special characters like á, ã on tooltipText

What's the recomended way to handle that?

Code:

```java
MapPolygon polygonTemplate = polygonSeries.mapPolygons.template;
polygonTemplate.tooltipText = "{name}: {value}";
```

See example bellow:

![w](https://user-images.githubusercontent.com/12686272/55410841-ec27b480-553a-11e9-80b2-b31b146375d0.png)

**Comment by martynasma** [comment]
There's nothing to handle - if your page is in Unicode, there should be no problems with special characters.

Make sure your HTML or other file is saved as UTF-8 encoded.

**Comment by rodrigobastosv** [comment]
My bad, i got a geojson file that's was not encoded as UTF-8.

Thanks very much
