### ISSUE TITLE
Property 'cornerRadius' does not exist on type 'Sprite'

### ISSUE THREAD

**Issue by venkat4541** [amcharts/amcharts4#1138]
**NOTE**: This is more of a question rather than a bug. 

I'm trying to update the legend marker to be circle in shape instead of a square on a pie chart. But when trying to update the property I'm getting an error that the cornerRadius properties are not part of the object. I have referred to article: https://www.amcharts.com/docs/v4/concepts/legend/#Default_markers

I have tried below ways to get what I need:

```
const marker = chart.legend.markers.template.children.getIndex(0);
```

1. marker.setPropertyValue('cornerRadiusTopLeft', 10);
2. marker.cornerRadius(12, 12, 12, 12);

**Comment by martynasma** [comment]
Can you post your whole chart on codepen/jsfiddle?

**Comment by venkat4541** [comment]
I'm having this problem only in my project which is in Angular. Typescript complains about the missing object. Nevermind, I'll see if I can figure out, just wanted to know if this was a known behavior in certain environments. Thanks for responding!

**Comment by venkat4541** [comment]
For anyone else having this issue, it seems to be a typescript problem and just requires the marker's type to be explicitly set to any.

`const marker**:any** = chart.legend.markers.template.children.getIndex(0);`

**Comment by notacouch** [comment]
Just make sure the marker is a [`RoundedRectangle`](https://www.amcharts.com/docs/v4/reference/roundedrectangle/#cornerRadiusBottomLeft_property), as only those have the `cornerRadius*` properties. The `RoundedRectangle` may also possibly be its `background` property if at all.

**Comment by farrukh-taqveem** [comment]
> For anyone else having this issue, it seems to be a typescript problem and just requires the marker's type to be explicitly set to any.
> 
> const marker **:any** = chart.legend.markers.template.children.getIndex(0);

Perefctly Worked for me in case of Bullets.isDynamic

**Comment by eduardmavliutov** [comment]
Thanks @notacouch ! I'd rather go with `RoundedRectangle` type than with `any`.
