### ISSUE TITLE
Better way to add custom items to Legend

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#114]
### To anyone reading this: the code below is a proposal, not something that works at the moment of this writing.

Right now the legend works fine with auto-generated items like from Series.

However, if I would create a Legend with custom items, I'd need to go through great lengths of manually adding squares and labels.

We need something like the below to work: (right now it doesn't because legend expects a full-fledged DataItem)

```
chart.legend = new am4charts.Legend();
chart.legend.data = [{
  "title": "One",
  "color": am4core.color("#72A6B2")
}, {
  "title": "Two",
  "color": am4core.color("#667E93")
}, {
  "title": "Three",
  "color": am4core.color("#488BB2")
}];

chart.legend.dataFields.name = "title";
chart.legend.labels.template.text = "{name}";
chart.legend.markers.template.propertyFields.fill = "color";
```

**Comment by Ekliptor** [comment]
Looking forward to this as well.
My primary use case for this are maps using MapPolygonSeries. If I color countries based on population (or other data) I want it to be able to show on a legend. Especially for printing since tooltips don't work anymore and the actual data is currently lost when printing.

**Comment by martynasma** [comment]
@Ekliptor 

For the record, if you are using heat rules for your heat map, you can use `HeatLegend` for that:

https://www.amcharts.com/docs/v4/concepts/legend/heat-legend/

However, if you apply custom colors to polygons, then yeah - you will need this functionality for the regular Legend.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.32](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.32).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
A bit of related docs:
https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items

**Comment by bijay-ps** [comment]
@martynasma with this approach am able to create custom legends but when I click on legend the stacked columns are not getting filtered accordingly. Checkout https://stackblitz.com/edit/angular-kmwdqm
How to achieve amchart's default legend behaviour in this scenario?
