### ISSUE TITLE
amcharts-number-formatter for small scales

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1142]
Hey I have tried to apply number formatter for small units between 0 - 1 for example 0.5, 0.2 and so on...
I have succeeded in applying number formatter for large scale units between 1 - 10(1e+1)
and more large scales as 1000(1e+3), 1000000(1e+6) and so on...
But I haven't succeed in applying unit formatter for small scales between 0 - 1.
I am attach an example of my current problem:
[https://stackblitz.com/edit/amcharts-number-formatter](https://stackblitz.com/edit/amcharts-number-formatter)

**Comment by BrkCoder** [comment]
answer or guidelines will be useful,
thanks in advance!

**Comment by martynasma** [comment]
How about specifying number of decimals in format?

```
this.chart.numberFormatter.numberFormat = "#.##a";
```

**Comment by BrkCoder** [comment]
thanks for the help :)
