### ISSUE TITLE
Line Chart with Scroll and Zoom - Extracting start and end dates of zoomed in chart

### ISSUE THREAD

**Issue by ravitejamajeti** [amcharts/amcharts4#1143]
https://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/

How to get the zoomed in chart start and end dates. Suppose, in the above demo chart, if I am zoomed in between 15th Jan 2017 to 23rd Feb 2017. How to extract those start and end dates?

Thanks

**Comment by martynasma** [comment]
```
dateAxis.events.on("datarangechanged", function(ev) {
  var start = new Date(dateAxis.minZoomed);
  var end = new Date(dateAxis.maxZoomed);
});
```
