### ISSUE TITLE
Making column bar shorter and hide at back 

### ISSUE THREAD

**Issue by bloodchow** [amcharts/amcharts4#1144]
1. How to make column bar shorter like 20% of the maximum height in amcharts? 
<img width="635" alt="vol" src="https://user-images.githubusercontent.com/48185838/55482684-a7de0680-5657-11e9-8be4-bc9b5e1e30a7.png">

I have tried series.max=20%; but no luck, max range cant accept value in percentage. 

I am creating candlestick chart with volume, the volume bar block out almost all the candlestick view : 

<img width="659" alt="3212" src="https://user-images.githubusercontent.com/48185838/55483099-80d40480-5658-11e9-9018-8445121f7665.png">
<img width="670" alt="3323" src="https://user-images.githubusercontent.com/48185838/55483114-86c9e580-5658-11e9-9ac2-dfc1bdbdf875.png">

Is there any z-index in amcharts like https://www.tutorialspoint.com/css/css_z-index.htm

Anyone answer is welcomed.

**Comment by venkat4541** [comment]
I'm not an expert but till someone knowledgeable responds here I'll share what I know.

1. Don't know if that would set the max height to 20% of chart but to pass a percentage value, use the below format: 
**series.max = am4core.percent(20);**

2. There is a z-index for every element inside the amcharts. It could be something like this based on your chart element's reference: 
**_candleStickChart_.zIndex = 10;** (replace _candleStickChart_ with your chart elements)

**Comment by bloodchow** [comment]
@venkat4541

adding z-index works! 
`series.zindex=10;`

<img width="652" alt="33222" src="https://user-images.githubusercontent.com/48185838/55555849-c1935280-5718-11e9-9a0a-75d260107d69.png">
