### ISSUE TITLE
Buttons not updating to dark theme

### ISSUE THREAD

**Issue by promitanan** [amcharts/amcharts4#1145]
When I change the theme from regular to dark in React's componentDidUpdate, the buttons stay with the original theme even though the rest of the chart changes. I'm specifically talking about changing the theme on the map, although this might happen in other charts too. If I rerender the whole map in componentDidUpdate, the buttons change themes correctly, but I don't want to force a rerender. 

![image](https://user-images.githubusercontent.com/18385581/55526961-f4234980-564b-11e9-8413-cb225db28bcb.png)

**Comment by martynasma** [comment]
When you say "change the theme" what do you mean?

There's currently no way to change the theme on a live chart. The only sure way to apply a different theme is to go ahead and recreate the whole chart/map.

**Comment by promitanan** [comment]
I was just trying to unuse(theme) and use a different theme. I see the other parts of the chart weren't changing themes either, just the buttons were more visible. Is there a plan to add this feature?

**Comment by martynasma** [comment]
Well, we would like to have it, but I doubt it will be implemented any time soon. Sorry.
