### ISSUE TITLE
Slowness on the treatment of data

### ISSUE THREAD

**Issue by tlebreton** [amcharts/amcharts4#1147]
Hi everyone

Thank you for you amazing work on this lib.
Actually we are on d3js which is very powerfull but not very simple to use.

We discover your library a few days ago and we were very enthusiastic by the simplicity of your library.

Bur we discover a blocking problem for us.

We need in some case to show a lot of data (like thousands of points) and your library is slow in particualr for zooming purpose.

Can we do something to speed up the process or it's impossible ?

Here is a little example for you.

https://jsfiddle.net/dm9eqsuf/

Dont hesitate to ask me any question

Thanks

**Comment by martynasma** [comment]
Your chart has ~150K of data points across three series. Even tho it works in my tests, there's one thing you can do.

Since user can't see 50K data points crammed into a single chart, I suggest simplifying the polylines:

```
am4core.options.minPolylineStep = 5;
```

This should speed the charts up.

**Comment by Servuc** [comment]
Hi,

@tlebreton is on holidays, lucky man ... ^^

I've tried your idea, but even with a minimal polyline step at 50, that doesn't really speed up the chart.
Comparing with our D3JS solution, this is not usable for our customers.
I will looking for another solution and keep in touch :)

Have a good coding day :)

**Comment by martynasma** [comment]
OK :)
