### ISSUE TITLE
Feature request: Change the line color between two points

### ISSUE THREAD

**Issue by peluprvi** [amcharts/amcharts4#115]
I know that is a way to change between two colors for values above and bellow zero, but I didn't find in the documentation (amCharts3 and/or amCharts4) if there is a way to create a chart like that:

![image](https://user-images.githubusercontent.com/1561360/42130214-567ef3f8-7cb4-11e8-92d2-dc9804e2c0cd.png)

In this example picture, the points represent the only data I have.
The line that connects the two points can be or not be smoothed.
The color changes by using the yAxis value, not the series value.

Textual example:
I want the color red from y = 0 until y = 10; and yellow until y = 20.
If I have the points (x, y): (1, 2) and (2, 5); the points and the lines will be all in red.
If I have the points (x, y): (1, 8) and (2, 12); the first point will be red, half of the line will be red and other half yellow, and the second point will be yellow.

**Comment by martynasma** [comment]
@peluprvi Yes, that is totally possible using Axis Ranges feature in amCharts 4.

More details here: https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/

P.S. this feature is not available in V3.

**Comment by peluprvi** [comment]
That's awesome @martynasma !

All examples of this page is using a single range.
Is there a way to use more than one rage in a single data.series?

If so, could you please edit this codepen to have a green color between 2018-03-24 and 2018-03-25:
https://codepen.io/anon/pen/pKGrGV

**Comment by martynasma** [comment]
You can add as many ranges as you need.

I updated your codepen as requested:

https://codepen.io/team/amcharts/pen/38d194084945c6691d8bc2bb0f22b646/

**Comment by peluprvi** [comment]
Thank you so much, @martynasma and all amCharts team!
Version 4 gonna be great!
