### ISSUE TITLE
Move XY-Chart x-axis labels to top of chart from bottom

### ISSUE THREAD

**Issue by LadyLynn32** [amcharts/amcharts4#1154]
Is it possible to move the x-axis labels of an XY- Chart to the top of the chart instead of the bottom? 
![XYChart](https://user-images.githubusercontent.com/22241914/55577577-e3bdae00-56e1-11e9-977e-b116ccc8eee0.png)

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/concepts/axes/#Orientation_and_position

**Comment by LadyLynn32** [comment]
Thank you!
