### ISSUE TITLE
Trigger hover "event" on map based on activity on a different part of the page

### ISSUE THREAD

**Issue by promitanan** [amcharts/amcharts4#1155]
For example, if I have a button on some part of the page that says United States and I hover over that button I'd like just the United States to be highlighted on the map. It can be a fill color change or a stroke width increase. I believe I can use "over" and "out" events with a custom hover state but I'm not sure how to isolate just one country at a time.

**Comment by martynasma** [comment]
You can do something like this:

```
polygonSeries.getPolygonById("US").isHover = true;
```

**Comment by promitanan** [comment]
Is there a way to show the tooltip associated with a country too?

**Comment by martynasma** [comment]
Yeah:

```
var us = polygonSeries.getPolygonById("US");
us.isHover = true;
us.showTooltip();
```

**Comment by promitanan** [comment]
I tried that but the tooltip doesn't show. The docs say I need to pass in an IPoint, but I'm not sure how to get the IPoint associated with a country?

**Comment by martynasma** [comment]
OK, you're right. Sorry, I totally forgot series needs to be prepped up for it:

```
polygonSeries.calculateVisualCenter = true;
polygonTemplate.tooltipPosition = "fixed";
```

No need for `showTooltip()` as well, setting `isHover` is enough.

Demo:
https://codepen.io/team/amcharts/pen/3e9f4326c51c0064ee652c7bcef7f7de

**Comment by enggomarpu** [comment]
@martynasma  if i want to do in react what will the scenario? because in react the map is rendered in componentdidmount so it is not available in DOM after rendering.
