### ISSUE TITLE
Sunburst Truncate labels in slices

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1156]
Hi, 

I have try to truncate labels in slices, because all labels overlap in otherside of the sunburst

Have have an exemple here : https://codepen.io/anon/pen/rbeQqK

Thx

**Comment by bosiljkakostic** [comment]
put in comment  "hideOversized": true, and set width, then label will truncate or wrap (if you don't truncate you will see wrapping :
			"labels": {
        "width":50,
				"truncate": true,
//				"hideOversized": true,
				"wrap": true
			}

**Comment by martynasma** [comment]
There's no good way to precisely auto-truncate such rotated labels.

What I'd do is to add an adapter that truncates labels by character count using a custom adapter.

Something like this:

```
"seriesTemplates": [{
  "labels": {
     "adapter": {
         "textOutput": function(text) {
            return am4core.utils.truncateWithEllipsis(text, 5, "...");
         }
      }
  }
}]
```

**Comment by Identity-labs** [comment]
It's not dynamique like treemap, 
I don't know how many pixel the slice have to show Label correctly.
In treemap the label is automatically truncated.

**Comment by martynasma** [comment]
Well, like I said, there's no easy way to determine if rotated label fits into some odd shape :(

**Comment by Identity-labs** [comment]
the height of the diameter is the same, because the symmetry axis is use to write the label in this direction

**Comment by martynasma** [comment]
Technically, it should be possible. I'm chalking this up as an enhancement to consider. Thanks.

**Comment by martynasma** [comment]
OK, here's a workaround for ya:

https://www.amcharts.com/demos/sunburst-chart/

It uses "rotation" adapter to apply maxWidth/maxHeight to the labels, causing them to truncate better.

We decided against hardcoding this functionality in, because someone might not want those labels truncated.

Hope you find this useful.

**Comment by martynasma** [comment]
Relevant code:

```
level0SeriesTemplate.labels.template.adapter.add("rotation", (rotation, target) => {
  target.maxWidth = target.dataItem.slice.radius - target.dataItem.slice.innerRadius - 10;
  target.maxHeight = Math.abs(target.dataItem.slice.arc * (target.dataItem.slice.innerRadius + target.dataItem.slice.radius) / 2 * am4core.math.RADIANS);

  return rotation;
})
```
