### ISSUE TITLE
The axisRange.label.text is not showing when is set text adapter on categoryAxis.renderer.labels.template

### ISSUE THREAD

**Issue by bosiljkakostic** [amcharts/amcharts4#1158]
The axisRange.label.text is not showing when is set text adapter on categoryAxis.renderer.labels.template

example https://jsfiddle.net/bosiljkakostic1/65echf0n/203/

without adapter work example

https://jsfiddle.net/bosiljkakostic1/65echf0n/202/

It seems that if I add adapter on categoryAxis.renderer.labels.template it work on AxisRange also, and as axisRange label expect string constant, not data field it does not work. I want to use nondefault text for the Category Axis label, and another fixed text for axis range. How I can do it.
Probably there is another way, but I could not find it in the documentation.

**Comment by martynasma** [comment]
You may check if it's a label for a range in adapter:

```
label1.adapter.add("text", (text, target) => {
  if (target.dataItem && target.dataItem.isRange) {
    return text;
  }
  else {
    return "[bold]{labelName}[/]";
  }
});  
```

**Comment by bosiljkakostic** [comment]
I resolve lables on another way, so this is not important more
