### ISSUE TITLE
Column width does not work in Gantt chart example

### ISSUE THREAD

**Issue by thunderbolt10** [amcharts/amcharts4#1159]
The [Gantt chart demo](https://www.amcharts.com/demos/gantt-chart-dates/) has a line to change the columns width 
`series1.columns.template.width = am4core.percent(80);`

Changing this percentage value does not seem to work.

**Comment by martynasma** [comment]
Thanks for the heads up!

There was an error in demo code. It's supposed to be `height` (not `width`).

Demo fixed.

**Comment by thunderbolt10** [comment]
Perfect! Seems obvious once you have pointed it out. 
Thanks
