### ISSUE TITLE
Can't update chart series

### ISSUE THREAD

**Issue by lucianholt97** [amcharts/amcharts4#116]
When I update my chart data, I have to update my series, too. Currently, there is only a getter for chart.series. When I try to use ListTemplate methods (like chart.series.clear() or chart.series.setAll()) instead, I get the error "Start index must be lower than end index".
In addition to this, the overall performance of my Vue.js dashboard (using two charts) is horrible at the moment. I hope this is due to a lot of debugging code?

Besides, the library looks very promising. Looking forward to the official launch.

**Comment by martynasma** [comment]
Thanks @lucianholt97 

Unfortunately (or fortunately?) I can seem to be able to reproduce it.

Take a look at this codepen:
https://codepen.io/team/amcharts/pen/f5c93464aec43bdfc1be736920eb4227?editors=0010

Upon button click it replaces both data, and all series using `series.setAll()`.

Is your setup fundamentally different? Can you share it?
