### ISSUE TITLE
Please help me, I can not change previosly set axis range

### ISSUE THREAD

**Issue by bosiljkakostic** [amcharts/amcharts4#1162]
Please help me,
I can change data that define axis range, but when I render the chart, after that changes on axis range is not showing on the chart even if I use        
 categoryAxis.deepInvalidate(); or
 chart.reinit();
an example is at https://jsfiddle.net/bosiljkakostic1/1zbqpogy/21/
problem is showing after clicking on button Change Range (below chart)
if you remove the comment and call the same function before the document is fully loaded everything is o.k. and a new state is shown. example of that is at https://jsfiddle.net/bosiljkakostic1/1zbqpogy/24/ (the new state is showed without clicking on Change Range button)

**Comment by martynasma** [comment]
The issue is how you are clearing your list of current ranges. Using `shit()` and manually setting `length` does not seem like a good way.

Simply use `clear()`:

```
categoryAxis.axisRanges.clear();
```

An there's no need to `deepInvalidate()` and `reinit()`. Those calls are redundant and should be removed.

**Comment by bosiljkakostic** [comment]
Thank you, very much, I was tried with categoryAxis .axisRanges.dispose(), but it produces an error that there is no such method. In the documentation there are no method clear for CategoryAxisDataItem (CategoryAxis, axisRanges properties class also there are no in class from which it inherits (Axis class)
