### ISSUE TITLE
chart.invalidateSize is not a function 

### ISSUE THREAD

**Issue by rstmsn** [amcharts/amcharts4#1163]
I have constructed a World Map Chart, using amCharts.
My chart object is defined as follows:

`chart = am4core.create("chartdiv", am4maps.MapChart);`

Later in my code, after I have added and removed some Line Series data, I need to call invalidateSize() on my chart, to force resizing. When I do so, I get the error: `chart.invalidateSize is not a function  `

My chart object is within scope. When I console.log() it, my output is:

`Object { _disposed: false, _disposers: (33) […], _className: "MapChart", events: {…}, properties: {…}, adapter: {…}, _bindings: {}, _isTemplate: false, _inited: false, _ready: false, … }`

I can even call chart.zoomOut(), which executes successfully. 
Any thoughts on what is going wrong? 
Regards

**Comment by martynasma** [comment]
There's no such function `invalidateSize()` in amCharts 4.

You don't need to call anything after adding or removing series, the MapChart will take care of it automatically.

Or am I missing something here?

**Comment by nmase88** [comment]
I would like to add to this as I was just about to attempt this to workaround a problem with creating charts on hidden divs. invalidateSize() did used to be a thing in v3 (https://www.amcharts.com/docs/v3/tutorials/displaying-charts-in-tabs-or-other-dynamic-page-elements/) has something been added to replace it?

**Comment by rmwever** [comment]
@nmase88 I was experiencing an issue where I also had to force a resize. I was able to do so by using 
`chart.svgContainer.measure();`

from #2327
