### ISSUE TITLE
Only hit event handler is getting fired even when both hit and doublehit event handlers are defined

### ISSUE THREAD

**Issue by PSEH-3** [amcharts/amcharts4#1164]

**Comment by PSEH-3** [comment]
Hi, I am trying to use doublehit and hit events together. But only hit gets invoked even on double click. However, if I remove hit event handler then doublehit gets invoked. Do I need to set the hitoptions adapter to make it work. Can you please share an example for setting hitoptions adpter?

**Comment by martynasma** [comment]
If both "hit" and "doublehit" events are set on an element then when you doubleclick it both "hit" and "doublehit" event should fire in rapid succession. First click generates "hit", the second "doublehit".

Are you saying it does not work that way, or you need the second click to generate "hit" as well?

**Comment by PSEH-3** [comment]
I want to differentiate single click from double click as I want to take different actions based on the type of click. If both the events are fired how would I distinguish between them.

**Comment by martynasma** [comment]
Are you sure? I did try and I'm pretty sure I do get both.

Can you provide the demo you are trying on?

**Comment by martynasma** [comment]
No worries :)
