### ISSUE TITLE
Bind column color to a data field with Column Series

### ISSUE THREAD

**Issue by munawarb** [amcharts/amcharts4#1168]
I'm trying to bind the color of each bar in a column series to a field in my data. This data field contains a color object, and I need to tell AmCharts to use this data field for every column and get its color information from there.

I've tried setting `series.propertyFields.fill` to "barColor" because the barColor field in my datapoints holds the AMCharts Color object, but the colors of the bars don't change.

I'm finding many examples for AmCharts3 but so far nothing on AmCharts4 and have been looking for a long time now. Is there a way to bind the color of each bar to a data field? I want each bar to get its color attribute from its specific datapoint and am not looking to make all the bars a single color. Also, these colors are not known ahead of time by the UI so I can't just add a color set and call it done. (Well, I guess I could do that but then I'd end up with over 2000 colors in the color set, one for each datapoint.)

**Comment by martynasma** [comment]
Of course there is. And the propertyFields is the way to go. Except you need to use those on column template, not directly on series:

```
series.columns.template.propertyFields.fill = "barColor";
```

**Comment by munawarb** [comment]
Hi @martynasma, thanks for the quick response; this worked.

**Comment by yuvi1422** [comment]
Hi @martynasma, I tried that solution but it is not working for me.
I have used similar logic over pie chart, it is working for that.

Can you please provide some code snippet with data format ?

**Comment by luceat-lux-vestra** [comment]
@night-fury-rider, @munawarb, @martynasma, @amcharts, @Pauan 

I tried this today, but not working for me.

my data looks like this.
```javascript
const color = ({
      0: am4core.color("#76C76C"),
      1: am4core.color("#DDB73B"),
      2: am4core.color("#CA444A")
      // 0: "#76C76C",
      // 1: "#DDB73B",
      // 2: "#CA444A"
    }) [((percentage >= 80) ? 2 : 0) ||
        (percentage >= 60 ? 1 : 0)];

    const chartData = [{
      "category": deline`\${category}`,
      "value": deline`\${percentage}`,
      "color": deline`\${color}`,
      "full": 100,
      "width": am4core.percent(0)
    }];
```

and  
```
series2.columns.template.propertyFields.fill = "color";
```

Please help.
