### ISSUE TITLE
Panoramix scrollbar label 

### ISSUE THREAD

**Issue by Ices-Eyes** [amcharts/amcharts4#1169]
Hi. I have a graph with a scrollbarx on top of it. The graph has the xaxis label defined as 
`
dateAxis.renderer.labels.template.horizontalCenter = "right";
dateAxis.renderer.labels.template.verticalCenter = "middle";
dateAxis.renderer.labels.template.rotation = 270;
`
but the orientation change is applied also to scrollbar labels. Is there a way to retain scrollbar labels horizontal?

**Comment by martynasma** [comment]
This is not super prominent, but you can access axis copies in the scrollbar and set their properties directly:

```
chart.scrollbarX.scrollbarChart.xAxes.getIndex(0).renderer.labels.template.rotation = 0;
```

https://codepen.io/team/amcharts/pen/8703fc217ca45e63a55fe471f6b7dc39?editors=0010

**Comment by Ices-Eyes** [comment]
Well... It was easy after all... 😶 Thanks a lot 😅
