### ISSUE TITLE
Customize grid style

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#117]
Hello,

How to customize grid style for yAxe et xAxe ?

I tried valueAxe.gridAlpha, valueAxe.renderer.gridAlpha

Thanks for your help !

**Comment by martynasma** [comment]
Since you closed this, I'm going to assume you have figured this out already.

For anyone else viewing this, grid customization happens via `axis.renderer.grid.template` object:

https://www.amcharts.com/docs/v4/concepts/axes/#Grid_labels_and_ticks

**Comment by ptorrent** [comment]
Yes thanks, I found the solution in the API.

Have a nice day
