### ISSUE TITLE
Memory leak on demo page 'One Country morphing to another'

### ISSUE THREAD

**Issue by damian2** [amcharts/amcharts4#1172]
If you left demo page 'One Country morphing to another', for 30min browser is crashing. I checked this on Chrome and Opera.
Not sure, maybe problem is with `animation.events.on("animationended"` calling n+1 times with every call.

**Comment by martynasma** [comment]
Thanks for the heads up. I've made some changes in the demo (replacing `on()` with `once()`).

This should keep the event handlers from piling up.
