### ISSUE TITLE
Print any chart is resized on second page

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1173]
Hi, 

When I try to print chart, the chart is resized on the second page, after the pagebreak
It's possible to keep chart on both page ? like amcharts 3

I have the bug on chrome / chromium / phantomjs, I think it's the resizeSensor ?

In chrome print preview mode :

![image](https://user-images.githubusercontent.com/600296/55724771-66a97600-5a0c-11e9-802b-b4356175e765.png)

Here the original in browser :

![image](https://user-images.githubusercontent.com/600296/55724856-95275100-5a0c-11e9-9a47-5ad6f65ca83c.png)

**Comment by Identity-labs** [comment]
If I had this css on SVG node it's correct
```css
    position: absolute;
    top: 0;
    bottom: 0;
```

**Comment by notacouch** [comment]
Would exporting the chart to an image/pdf and printing that work for you instead?

**Comment by Identity-labs** [comment]
How it’s possible in chrome or other browser to detect « file > print » to pre-render all charts ?

**Comment by martynasma** [comment]
How about just inserting an element with `break-after` CSS in it so that full second chart would go into second page?

https://developer.mozilla.org/en-US/docs/Web/CSS/break-after

**Comment by Identity-labs** [comment]
Yes I know this stuff, 
but I have a complex layout, all charts are on absolute position, so the html flow is broken and this property does't work.
Don't worry I have put the previous CSS to the first SVG node of all charts in my layout.
