### ISSUE TITLE
Performance Issue in Map

### ISSUE THREAD

**Issue by sheepsy90** [amcharts/amcharts4#1177]
I am using the Map chart with React, and trying to set the data on the polygon series to highlight some countries dynamically. However the graph takes noticeable time to update and the frame rate drops to almost zero during the time.

Anyone has experience with that?
![debug](https://user-images.githubusercontent.com/595087/55740230-e9d9c480-5a2a-11e9-90cb-77e2736aa62d.png)

**Comment by zeroin** [comment]
If you set data on series, everything is being redrawn, which is of course quite costly. You can access country polygon and set it's fill color, or, if your color depends on some value, then you can modify value of  a data item.

**Comment by sheepsy90** [comment]
@zeroin Thank you for the quick answer - currently i am doing: 

`      this.polygonSeries.data = [

      {
        "id": this.state.currentSelected,
        "name": "United States",
        "value": 100,
        "fill": am4core.color("#0000FF")
      }];`

Can you give me a tiny example how i would access the country's polygon - i didn't find it in the docs

**Comment by martynasma** [comment]
```
var polgon = this.polygonSeries.getPolygonById(this.state.currentSelcted);
polygon.fill = am4core.color("#0000FF");
```
