### ISSUE TITLE
How to center a guideline

### ISSUE THREAD

**Issue by rdibenedetto** [amcharts/amcharts4#1180]
Hi, in the following pen I have an bullet with timestamp 1515150955816, and i want to add in the same point a guideline. so I set range.date = 1515150955816, but there is no overlapping. 
How can I add a guideline in the same point of the bullet?

the pen is : https://codepen.io/roger710/pen/MRJgOZ

**Comment by martynasma** [comment]
This is because bullets/columns/data items are centered within period, whereas the axis range is placed at exact timestamp across DateAxis scale.

I suggest you adjust the timestmap of the axis range so it comes exactly in the middle of the minute you have your data points set for.
