### ISSUE TITLE
External legend height

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#1181]
Trying to toggle display of an external legend, please see the [codepen](https://codepen.io/npc42/pen/ZZLvaJ), based on “scrolling legend” demo. 

The legend.contentHeight property returns different results on different calls — initially it only shows half of the entries (up to UK). Then, as you click “toggle legend” again it gets updated to full height — all the way to Spain. This only happens if I also resize the main chart (the space is shared between chart and legend) — so I suspect some weird interaction between chart resize events and legend content height update.

In my production it is even wilder, legend content height changes drastically between each call (first it's tiny, then inserts a massive gap at the top, and only on third try it fits actual legend items), but this is the closest I could reproduce it in an isolated environment.

Again, none of this would happen if you had built-in legend scrolling ;)

PS Also, a heads up, this [demo](https://codepen.io/team/amcharts/pen/GBjGyb) (linked from Legend / Related demos article) has weird toggle behaviour.
PPS May be related to #1025, but I'm seeing this on Chrome on Windows.

**Comment by martynasma** [comment]
Thanks for heads up about Gauge demo. Fixed.

And thanks for the legend height note. Gah, it's complicated. Kicking it over to dev team. Will keep you posted.

**Comment by zeroin** [comment]
I added another listener:
<code>chart.legend.events.on("sizechanged", resizeLegend);</code>

and it works fine now:
https://codepen.io/team/amcharts/pen/vMxyYo

**Comment by NPC** [comment]
@martynasma @zeroin thanks for your help! 

The codepen is fixed indeed, but the issues in my dev.environment are still happening :( Not your fault, I'll keep looking, and if I manage to isolate it — I'll bug you again (sorry!).

**Comment by NPC** [comment]
So far my random issues are (seemingly) solved by also adding a 'sizechanged' handler to the external legend container. Maybe this'll help someone else.
