### ISSUE TITLE
Typo in documenation

### ISSUE THREAD

**Issue by onx2** [amcharts/amcharts4#1183]
It should say "JavaScript" as the 2nd tab option.

It is on this URL:
https://www.amcharts.com/docs/v4/tutorials/handling-axis-zoom-events-via-api/#Catching_zoom_event

![image](https://user-images.githubusercontent.com/23039725/55825580-43e29480-5ad4-11e9-9171-df41ecf69ea3.png)

**Comment by martynasma** [comment]
Thanks for the heads up! Fixed.
