### ISSUE TITLE
alignment of charts with different data diversity

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1186]
Hey I have 3 different graphs on 3 different containers with different data diversity.
As you can see all the graphs aren't align in terms of yaxis, is there any logic for alignment different containers with single yaxis with different data diversity.
Here is the example:
https://stackblitz.com/edit/angular-5haisz

Best Regards,
Barak Inbal

**Comment by martynasma** [comment]
I suggest using "stacked axis":

https://www.amcharts.com/docs/v4/tutorials/stacked-axes/
