### ISSUE TITLE
Step Line Series has unwanted vertical lines

### ISSUE THREAD

**Issue by thunderbolt10** [amcharts/amcharts4#1187]
[Codepen example](https://codepen.io/thunderbolt10/pen/VNpmEe)

When using the Step Line Series chart and using series.propertyFields.fill (line 65) we get vertical lines appear in the fill.
![Annotation 2019-04-10 115859](https://user-images.githubusercontent.com/30114322/55873629-0d665180-5b88-11e9-8234-48da597aa648.png)

The thickness of the lines can be reduced by setting the dateAxis.baseInterval to a small value (line 53), but they are still visible.
It seems that the lines are caused by overlapping fill sections between points. This can be seen if you zoom into the transition between blue to yellow, there is a blend of the two overlapping colors.
![Annotation 2019-04-10 115604](https://user-images.githubusercontent.com/30114322/55873570-ea3ba200-5b87-11e9-9d2e-7f4ccec80e12.png)

Is there a method to prevent these overlapping fill lines?

**Comment by notacouch** [comment]
After some testing, I haven't really been able to determine why exactly it's happening, but I'm thinking it has to do with the irregular intervals.

The quickest workaround I could think of (after trying some different things), is to just use a solid fill, i.e. `fillOpacity = 1`, optionally adjusting the color as if its transparent (I just used the eyedropper in Paint to get the RGB values from the screenshot), and lastly layer the grid on top, e.g.

```javascript
dateAxis.renderer.gridContainer.zIndex = 10;
dateAxis.renderer.grid.template.strokeOpacity = 0.07; // Default: 0.15

// ...

valueAxis.renderer.gridContainer.zIndex = 10;

// ...

// signalSeries.fillOpacity = 0.5;
signalSeries.fillOpacity = 1;
```

Screenshot (please ignore the tooltip that's fading out):
![Screenshot of update with no overlapping fills](https://user-images.githubusercontent.com/2334143/55919981-08c08e00-5bc6-11e9-8b54-2e82deb5ea6b.png)


Here's a fork that demos the above workaround:
https://codepen.io/team/amcharts/pen/2420d6d325f12ebda4b2e2b813b05ebf

**Comment by thunderbolt10** [comment]
Thanks for your suggestion. Whilst this fixes the demo sample it does not work if we zoom out. So I have forked your work around and changed the value of the first data point to a few hours earlier to stretch the chart.
[https://codepen.io/thunderbolt10/pen/VNbpmQ](https://codepen.io/thunderbolt10/pen/VNbpmQ)

The vertical lines have now reappeared to the right of the yellow fill.
![image](https://user-images.githubusercontent.com/30114322/55941737-c1c0b000-5c3a-11e9-95ee-cabdd2b22e5d.png)

**Comment by martynasma** [comment]
What jumps out at me is that you have "color" field specified for each and every data point. This creates a separate line segment element for each data point. When they are very small, the renderer is having issues painting them attached to each other nicely, hence visual glitches.

Aside from that, it's also inefficient from performance stand-point.

I suggest adding "color" field to those data points where the color actual changes.

```
data = [
  {event_time: new Date('Tue Apr 09 2019 8:50:47'), signal: 93, color: "rgb(129, 192, 233)"},
  {event_time: new Date('Tue Apr 09 2019 11:03:47'), signal: 93},
  {event_time: new Date('Tue Apr 09 2019 11:03:47'),  signal: 93},
  {event_time: new Date('Tue Apr 09 2019 11:04:16'), signal: 100, color: "rgb(255, 255, 128)"},
  {event_time: new Date('Tue Apr 09 2019 11:06:01'),  signal: 91, color: "rgb(129, 192, 233)"},
  {event_time: new Date('Tue Apr 09 2019 11:06:01'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:06:22'),  signal: 92},
  {event_time: new Date('Tue Apr 09 2019 11:06:22'),  signal: 92},
  {event_time: new Date('Tue Apr 09 2019 11:07:48'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:07:48'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:07:49'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:07:51'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:07:53'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:07:59'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:08:04'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:08:10'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:09:50'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:11:14'),  signal: 92},
  {event_time: new Date('Tue Apr 09 2019 11:11:14'), signal: 92},
  {event_time: new Date('Tue Apr 09 2019 11:11:30'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:11:30'), signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:14:04'),  signal: 92},
  {event_time: new Date('Tue Apr 09 2019 11:14:04'),  signal: 92},
  {event_time: new Date('Tue Apr 09 2019 11:15:01'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:15:01'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:15:17'),  signal: 92},
  {event_time: new Date('Tue Apr 09 2019 11:15:17'),  signal: 92},
  {event_time: new Date('Tue Apr 09 2019 11:15:43'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:15:43'),  signal: 91},
  {event_time: new Date('Tue Apr 09 2019 11:16:51'), signal: 92},
];
```

This will solve the lines problem, while speeding up the chart.

https://codepen.io/team/amcharts/pen/c7d579952c3eb10d301a63dadef77624
