### ISSUE TITLE
How to disable automatic locale/datetime format detection?

### ISSUE THREAD

**Issue by ciarancourtney** [amcharts/amcharts4#1188]
It seems like setting `this.chart.dateFormatter` props doesn't guarantee consistent usage in other areas like tooltip, export etc

    this.chart.dateFormatter.dateFormat = this.dateFormat;
    this.chart.dateFormatter.utc = true;  // We naively encode localtime as unix epoch

I find I still need to set the tooltip and export format manually, otherwise it interprets from the browser. How can you disable this feature and DIY locale configuration?

**Comment by ciarancourtney** [comment]
Note that setting `dateFormat` on exporting is ok for CSV output, but not for JSON

**Comment by martynasma** [comment]
Tooltips should use chart's `dateFormatter.dateFormat` unless you have separate dateFormatter instance set for series, or use inline formatting.

`DateAxis` has own set of formats and does not use `chart.dateFormatter.dateFormat`.

Were you referring to the axis tooltips?

**Comment by ciarancourtney** [comment]
> Tooltips should use chart's `dateFormatter.dateFormat` unless you have separate dateFormatter instance set for series, or use inline formatting.
>
> `DateAxis` has own set of formats and does not use `chart.dateFormatter.dateFormat`.
> 
> Were you referring to the axis tooltips?

Yes I'm referring to axis tooltips. I guess the problem is you set a global `dateFormat` but this may get truncated elsewhere based on context, meaning you have to explicitly override all props with the same value.

I'd like to enforce ISO where possible and disable locale detection. What would be the config required to ensure `yyyy-mm-dd hh:mm` is used everywhere?

**Comment by martynasma** [comment]
In that case you should take a look at the `dateFormats` description here:

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Formatting_date_and_time
