### ISSUE TITLE
Question: Chart Theme & toggle legend Text Items?

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1191]
Hey amcharts4, I have struggling with a theme issue with amcharts4,
How can I change the text color of legend items for different charts when I switching between 2 different custom themes.
Please provide a simple example, because this issue isn't clear or covered by amcharts4 docs.

Best Regards,
Barak Inbal

**Comment by martynasma** [comment]
There's no way to switch themes on a live chart. Sorry.

**Comment by BrkCoder** [comment]
If I am doing reinit() for each chart, no change to switch theme also?

**Comment by martynasma** [comment]
Nope. Themes are applied at the moment when object instantiated. This way we know that we won't overwrite any settings your code might have set afterwards.

`reinit()` only invalidates all objects, causing them to redraw, but it won't apply the theme.

**Comment by BrkCoder** [comment]
ok I got youur point, thanks for the help :)
