### ISSUE TITLE
Problem with openDateX and dateX Candlesticks

### ISSUE THREAD

**Issue by rdibenedetto** [amcharts/amcharts4#1193]
Hi, 
in the following pen I would draw more candlestick in sequence and I want to define their width with the field openDateX and dateX but as you can see the firsts 2 overlap but I set endDate of the first,  equals to the opendate of the second. 
The last 2 seems the result I want but I inverted the open date and the end date for the last one altering the data.
How can I achieve the result I want? There is something wrong I didn't understand?
The pen is: 
https://codepen.io/roger710/pen/WWjKGM

**Comment by martynasma** [comment]
I don't think that's going to be possible. The candlesticks are being centered, so it having worked when reversing open/close is a sideeffect rather than correct behavior.

Sorry.
