### ISSUE TITLE
Extra indent in docs

### ISSUE THREAD

**Issue by onx2** [amcharts/amcharts4#1196]
Please let me know if these kinds of issues aren't meant on this channel or if it's too nit-picky 😄 

On this URL: https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Setting_up_axes, under the `JSON` tab, `"title"` is forward two spaces too many.

![image](https://user-images.githubusercontent.com/23039725/56051993-5a7c2c00-5d1e-11e9-977a-33d18fb9985b.png)

**Comment by onx2** [comment]
I've noticed this in a few different spots, maybe I can just open a PR with all the fixes instead of posting them here 😄

**Comment by martynasma** [comment]
Nah, not too nit-picky. Much appreciated.

Maybe you could just point the URLs with issues and we'll fix those on our end?

This is a public repo, only for distribution of the lib. We can't really merge PRs into our codebase from here :(

**Comment by martynasma** [comment]
Fixed that article you linked to.
