### ISSUE TITLE
Fixed-width links for Sankey Diagram

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#120]
Might make sense to implement ability for fixed-width Sankey Links. Just like it's available for Chord.

**Comment by Taova** [comment]
@martynasma Thank you  for your answer

**Comment by NPC** [comment]
Just combed through many tickets and sankey demos looking for this possibility. It'd be nice if Sankey allowed drawing simple thin arrows (with actual arrows at the end) bentween nodes (then nodes could be fixed height/width), to produce something like block schemes or organisation charts.

Then you'll have us asking for custom node shapes ;)

**Comment by NPC** [comment]
Ooh, there's actually a [middle-line](https://www.amcharts.com/docs/v4/reference/sankeylink/#middleLine_property) property on links, it shows when I do this (in JSON):
```javascript
links: {
   template: {
      fillOpacity: 0,
      middleLine: {
         strokeOpacity: 1,
         stroke: 'grey'
      }
   }
},
```

Now if only we could have:
* Arrow (as on [MapLine](https://www.amcharts.com/docs/v4/reference/mapline/#arrow_property))
* Fixed-sized nodes (perhaps already possible?), basically to make link values irrelevant, a link becomes binary yes/no, and nodes' widths don't depend on it.

**Comment by martynasma** [comment]
Sorry, been a while. Just posted this `middleLine` workaround in official Sankey docs:
https://www.amcharts.com/docs/v4/chart-types/sankey-diagram/#Fixed_width_links

**Comment by Pierre-louis242** [comment]
Hey, see the solution with the middleLine, but what if you want to have them in different colors?
