### ISSUE TITLE
Legend Color And Default Value On Candlestick Chart

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1200]
See [CodePen here](https://codepen.io/anon/pen/bJobKG).  I want to make the legend color the same as the candlestick color (either green or red).  However, it is always green.  How can this be done?

Also, is it possible to set the legend values to the most recent candlestick (or if not, perhaps the last candlestick viewed/hovered) as a default?  Otherwise, when you mouse off of the chart, the legend collapses since there are no OHLC values.

**Comment by martynasma** [comment]
Try this:

```
chart.legend.labels.template.text = "[bold {column.fill}]Open:${openValueY.value} Low:${lowValueY.value} High:${highValueY.value} Close:${valueY.value}[/]";
```

**Comment by martynasma** [comment]
As for second question:

```
series.legendSettings.labelText = "[bold {column.fill}]Open:${openValueY.close} Low:${lowValueY.close} High:${highValueY.close} Close:${valueY.close}[/]"
```

**Comment by bfailing** [comment]
The first suggestion works perfectly for the coloring of the dynamic data (updated based on cursor position).  However, there are some issues with the second suggestion shown in [this pen](https://codepen.io/anon/pen/rbGvEa).

Initially, the second seems to override the first (it always shows the most recent value vs. showing the values of the current cursor position).  Is there a way to show the second by default but override the default with the first when the cursor is on the chart?

Also, how can I apply the colors to the default values (i.e. should be green in this case since the last candlestick is green)?  "column.fill" doesn't seem to be recognized.
