### ISSUE TITLE
Question: oneBalloonOnly field of amcharts 3 in amcharts 4

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1201]
Hey I have many tooltips which are shown by default for all series of chart,
any chance to show only the tooltip for hovered series, or in other words what is the equivalent to the field oneBalloonOnly of amcharts 3 in amcharts 4?

**Comment by martynasma** [comment]
There's no equivalent to `oneBalloonOnly` in v4, I'm afraid.

If you have `ColumnSeries`, I suggest adding `tooltipText` directly to column template, as well as setting `cursorTooltipEnabled = false`. This way only hovered column will show tooltip, even if you have cursor enabled.

I'm repurposing this thread to serve as an enhancement request for when we decide to implement this feature.

Thanks!

**Comment by martynasma** [comment]
This is now possible via `maxTooltipDistance`:
https://www.amcharts.com/docs/v4/reference/xycursor/#maxTooltipDistance_property

**Comment by sassomedia** [comment]
`maxTooltipDistance` seems like a good idea but that only seems to work if the series are actually apart from each other. In the event though that multiple LineSeries are overlaying each other at the exact same data points, max distance of `0` fails. The positions are the same, so it displays multiple tooltips. I would only need that one tooltip of the top-most series that's actually being rolled over. Is there a way to achieve that? This was really simple in v3 with `oneBalloonOnly`.

**Comment by sassomedia** [comment]
I see this works now in https://github.com/amcharts/amcharts4/releases/tag/4.9.6 with `maxTooltipDistance = -1`; Thanks!
