### ISSUE TITLE
Series bullet column overflow

### ISSUE THREAD

**Issue by anthnm** [amcharts/amcharts4#1203]
Hey,
I'm struggling with some thing for a while. I'm trying to add a background image for every column in the series and it works fine for wide ones, but for narrow ones, image renders outside the column.

See example here: [https://codepen.io/anthnm/pen/KYXoXq](https://codepen.io/anthnm/pen/KYXoXq)

I tried using bullets with image as a child and just image as a template child(but I guess this doesn't work cuz it's added as a sibling to path that renders the column).

Is there any way to configure this to be looking like that(or completely remove image in narrow columns)?
![Zrzut ekranu 2019-04-15 o 09 03 01](https://user-images.githubusercontent.com/49633492/56113260-a36df380-5f5d-11e9-858e-b27587fad5b7.png)
Or if not, is there any possibility to implement something like that in the future?

Thanks.

**Comment by martynasma** [comment]
Here's an example that uses adapter as a workaround:
https://codepen.io/team/amcharts/pen/pBWYQd?editors=0010

Hope you find it useful.

**Comment by anthnm** [comment]
This is awesome, works like a charm.

Thank you!
