### ISSUE TITLE
Locale / numberFormater from config ?

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1205]
Hi,

I think the locale configuration does't work
I have apply like in the documentation :
https://www.amcharts.com/docs/v4/concepts/locales/#Setting_a_locale

Here an exemple with locale FR
https://codepen.io/anon/pen/xeXNWr

We expect thousandSeparator was space and decimalSeparator was coma

Thx

**Comment by martynasma** [comment]
Congratulations, you've found a bug :)

Let you know when a fix is available.

**Comment by martynasma** [comment]
Just released 4.4.0 which fixes this issue, except you will need to use it like this:

```
  language: {
    locale: am4lang_fr_FR
  },
```

For some reason specifying it as string "fr_FR" does not work. It's a separate issue, though, which we'll need to resolve.

**Comment by martynasma** [comment]
Heads up, 4.4.1 fixes specifying locale as string as well.
