### ISSUE TITLE
How I can display only years on dateAxis with baseInterval {count: 1, timeUnit: "month",};

### ISSUE THREAD

**Issue by bosiljkakostic** [amcharts/amcharts4#1206]
I need to have a base interval set to 
dateAxis.baseInterval = {
            count: 1,
            timeUnit: "month",
        }
so the elements of that chart start relatively within the grid, but I want on DateAxis to show the only year. I tried it with dateAxis.dateFormats.setKey("year", "yyyy"); and 
dateAxis.dateFormatter.dateFormat = "yyyy";  but it does not help. The dateAxis shows months. I have a switch on a web page that defines did I have to show a month or not, but even if is chosen year, the position of elements with different months have to be different. The only way on which I can do it is to set base interval on month. I could not change minGridDistance (it seems that it not dynamically changeable), and I do not know the period so that I can calculate needed minGridDistance to hide months on that way (nevertheless, if there are space for more than minGridDistance it change nothing). I also tried 
dateAxis.gridInterval = {
            count: 1,
            timeUnit: "year",
        };        it means grid interval (it look like the best way for that), but it did not help me.

**Comment by martynasma** [comment]
You need to use `DateAxis` setting [`gridIntervals`](https://www.amcharts.com/docs/v4/reference/dateaxis/#gridIntervals_property) for that.

E.g.:

```
dateAxis.gridIntervals = [
 { timeUnit: "year", count: 1 },
 { timeUnit: "year", count: 2 },
 { timeUnit: "year", count: 5 },
 { timeUnit: "year", count: 10 },
 { timeUnit: "year", count: 50 },
 { timeUnit: "year", count: 100 }
];
```

**Comment by bosiljkakostic** [comment]
last do not work. I was made new issue https://github.com/amcharts/amcharts4/issues/1284
