### ISSUE TITLE
Charts in tabs becoming blank after refresh

### ISSUE THREAD

**Issue by Takhysis** [amcharts/amcharts4#1209]
Hi,

I'm facing a problem while drawing charts in tabs or collapsed panels (accordion).
On first page load all seems to work correctly: all charts are shown and tabs and collapsed panel do what they are supposed to do. But if I reload charts using a page control (a button for example) only the currently visible chart is redrawn correctly, the others become white (or 0x0 pixel).

Here you can find an example using tabs:
[https://jsfiddle.net/giulia_pinnisi/cqoz5vbg/18/](url)
On first run it's ok, pressing the Refresh buttons the hidden charts become white

Thank you very much for your help

Giulia

**Comment by martynasma** [comment]
Looking at your code it seems that hitting Refresh simply tries to create a new chart in the same container over existing one.

That is not right way to do it. The old SVG is overwritten, but all the variables, event handlers, helper elements remain, and quite possible causing all kinds of issues.

If you are overwriting a chart make sure you call `dispose()` on its object first.

Better yet, if you need to just update data of the charts, you can reuse same objects, and just set their `data` property.

https://www.amcharts.com/docs/v4/concepts/data/#Dynamic_updates

**Comment by Takhysis** [comment]
Thank you very much!

I tried to update [my fiddle](https://jsfiddle.net/giulia_pinnisi/cqoz5vbg/25/), and now charts are correctly redrawn.. but axis labels of hidden charts are not in their correct position:

![Capture](https://user-images.githubusercontent.com/7262214/56344381-8afc1400-61bd-11e9-880f-efbd46e4cd17.PNG)

What am I doing wrong now?

**Comment by martynasma** [comment]
Indeed. We'll need to figure this one out.

Will keep you posted.

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
