### ISSUE TITLE
Number formatter - rounding

### ISSUE THREAD

**Issue by piernik** [amcharts/amcharts4#1211]
Here You have chart with number formatter: https://codepen.io/piernik/pen/pBpyoq
Hover over `Austria`. Something wrong with rounding. How to fix it? Can I force formatter to round to one place after comma?

**Comment by martynasma** [comment]
Trying to understand, what is wrong with rounding on Austria?

![image](https://user-images.githubusercontent.com/1458520/56211652-ff6d7080-6060-11e9-9968-76592ef6fda2.png)

**Comment by martynasma** [comment]
Nevermind, sorry. I see it.

You can force the formatting to one digit after comma like this:

```
chart.numberFormatter.numberFormat = '#.#a';
```

**Comment by piernik** [comment]
Thanks
