### ISSUE TITLE
Scrollbar zoom y1 and y2 value line overflow on export feature

### ISSUE THREAD

**Issue by rohit1018** [amcharts/amcharts4#1213]
![export_scrollbar](https://user-images.githubusercontent.com/28265981/56254976-fe543780-6090-11e9-9e56-1d964304f322.png)

**Comment by martynasma** [comment]
Interesting. Would you be able to share a codepen/jsfiddle with this chart?

**Comment by rohit1018** [comment]
Now, unable to reproduce again because now working export normally. I didn't change anything in the code.

**Comment by martynasma** [comment]
Alright. Let's revisit this if the issue re-appears.
