### ISSUE TITLE
Reference line on a graph

### ISSUE THREAD

**Issue by Ices-Eyes** [amcharts/amcharts4#1216]
Hi all,
I'm drawind a column chart and would like to draw on it a red line as a treshold indicator, a reference line that is parallel to the x axis. Is there a way to do it without drawing a line series and having to know the first and last categories? I mean somenthing like xaxis.value='all' yaxis.value=0.95...

Thanks :)

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides

**Comment by Ices-Eyes** [comment]
Damn... I was sure it was possible!!! Thanks to pointing me to right page! :)
