### ISSUE TITLE
Why not formatting the numbers?

### ISSUE THREAD

**Issue by marcosfsj** [amcharts/amcharts4#1218]
var chart = am4core.create("distAverage", am4charts.PieChart);

chart.numberFormatter.numberFormat = '###.00';

chart.data = [
      {Company: "Swisher International Inc", Share: 10.0},
      {Company: "Dosal Tobacco Company", Share: 10.0},
      {Company: "Global Tobacco Lic", Share: 20},
      {Company: "dkdkdkdk d dkdkdk d", Share: 20},
      {Company: "test", Share: 20},
      {Company: "test", Share: 20}
];

var pieSeries = chart.series.push(new am4charts.PieSeries());
pieSeries.dataFields.value = "Share";
pieSeries.dataFields.category = "Company";

pieSeries.colors.list = [
   am4core.color("#800000"),
   am4core.color("#006600"),
   am4core.color("#2b546f"),
   am4core.color("#e6dd30"),
   am4core.color("#c96012"),
   am4core.color("#7f7f7f")
];

**Comment by martynasma** [comment]
Because `PieSeries` sets default label content that has in-line formatting set already, which overrides global one.

Use it like this:

```
pieSeries.labels.template.text = "{category}: {value.percent.formatNumber('###.00')}%";
pieSeries.slices.template.tooltipText = "{category}: {value.percent.formatNumber('###.00')}% ({value.value})";
```

**Comment by marcosfsj** [comment]
What about if I am using legend?

chart.legend = new am4charts.Legend();
chart.legend.position = "right";
chart.legend.labels.template.text = "{category}";

I could not find how to affect the numbers....

**Comment by marcosfsj** [comment]
I tried this with on success:

chart.legend.labels.template.numberFormatter.numberFormat = "###.00";

**Comment by martynasma** [comment]
For legend, global number formatter should work:

```
chart.numberFormatter.numberFormat = '###.00';
```

**Comment by marcosfsj** [comment]
It is not working.

Please take a look at the CodePen:
https://codepen.io/marcosfsj/pen/EJQOwW?editors=0110

**Comment by martynasma** [comment]
This is CodePen for some entirely different chart. Are you sure you sent the right link?

**Comment by marcosfsj** [comment]
Sorry! You can check again, please:

https://codepen.io/marcosfsj/pen/EJQOwW

**Comment by martynasma** [comment]
Ah OK, sorry. I misled you.

You'll need this as well:

```
chart.legend.valueLabels.template.text = "{value.percent.formatNumber('#.00')}%"
```

**Comment by marcosfsj** [comment]
Works! Thanks a lot!

**Comment by hossein13m** [comment]
How can we change the format of the number when we hover on the piechart itself?:

**Comment by lehieu099** [comment]
> The column with the value is calculated by amCharts and I could not find a way to affect that column:
> 
> ![image](https://user-images.githubusercontent.com/6600644/56389532-cf0c0a80-61f7-11e9-9600-89bfdb16c2f8.png)

how can i remove it? thank you. guys
