### ISSUE TITLE
Problem with firing events

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [amcharts/amcharts4#1221]
Hi,
we are evaluating purchase the library. First we used v4 but due to some performance problem over iexplorer we are now using v3.

With v4 we had no problems with "ready" events, but with v3 the event is fired when makeChart is called. This also happens with "init" event.

For example, this is not firing never:

AmChart chart = AmCharts.makeChart(div, conf);
chart.addListener("rendered", () -> {
                AmCharts.makeChart(div2, conf2);
            });

We are using amcharts over GWT.

Do you have any ideas?

Thanks in advance

**Comment by martynasma** [comment]
I'm sorry, this is a repo for v4. Let's not derail the topic.

Thank you for understanding.

**Comment by RaulPampliegaMayoral** [comment]
For sure, I did not realize this was for v4. I'm sorry
