### ISSUE TITLE
Changing Scrollbar Thumb Color Doesn't Stick If Previously Hovered

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1222]
See [this pen](https://codepen.io/anon/pen/zXaRJm).

Steps to reproduce:
1. Move mouse over thumb before without first pressing "Change Thumb Color" button
2. Click "Change Thumb Color" button (color of thumb is changed to red)
3. Move mouse back over thumb
4. Move mouse off of thumb (color should revert to red, but instead it reverts to the original color)

Note that this does not occur if you press the "Change Thumb Color" button before hovering on the thumb.

**Comment by martynasma** [comment]
Let me explain what happens.

When you set a property, like `fill` for the first time on an object, the previous value for fill is considered a "default" value.

When you hover a thumb, it is transitioning to "hover" state, and back to "default" state when you hover out.

So, if the first `fill` set comes from your code ("red"), the default is red, and that's what it returns to after hover.

If the first `fill` set comes from a hover, the previous default gray becomes the default fill and it is returned back to grey after hover out.

So, in order for this to work, you need to modify dafault state as well:

```
chart.scrollbarX.thumb.background.fill = am4core.color('#FF0000');
chart.scrollbarX.thumb.background.defaultState.properties.fill = am4core.color('#FF0000');
```

Hope that makes sense.

**Comment by bfailing** [comment]
This works. Thanks.
