### ISSUE TITLE
tooltip is not working(IE9)

### ISSUE THREAD

**Issue by waltersgit** [amcharts/amcharts4#1223]

**Comment by martynasma** [comment]
A bit vague. Would you be able to provide an example?

**Comment by waltersgit** [comment]
Tooltip can be displayed normally in chrome, firefox, edge when the mouse slides in, but ie9 cannot be displayed.

**Comment by martynasma** [comment]
Will you make me guess what you have for a config? :)

OK, here we go. Do you perhaps use `tooltipHTML` instead of `tooltipText`?

If that is the case, it will not work for IEs as those do not support `foreignObject`.

**Comment by khiami** [comment]
@martynasma That was truly helped. Reverting back to text format.
