### ISSUE TITLE
Any solution for rendering hundreds of SVG elements?

### ISSUE THREAD

**Issue by dorsharon** [amcharts/amcharts4#1225]
I have a Gantt that includes hundreds of SVG elements, which causes my browser to slow down to a crawl.
Any way of addressing this issue?
Like grouping together small chunks of SVGs into one element until they're zoomed in enough to see them apart?
Or perhaps prevent rendering very small elements until they can be seen (in zoom)?

**Comment by martynasma** [comment]
No, I'm afraid.

Do you have a demo of your chart, so that I can take a look?
