### ISSUE TITLE
Is there a way to go back to the old export icon?

### ISSUE THREAD

**Issue by marcosfsj** [amcharts/amcharts4#1227]
Is there a way for me to customize the export icon to be back to use this?

![image](https://user-images.githubusercontent.com/6600644/56586351-91b7cc00-65ad-11e9-9f76-014be343c425.png)

or I would have to override css classes to do so?

**Comment by martynasma** [comment]
You can disable built-in CSS altogether, and use your own:

https://www.amcharts.com/docs/v4/reference/exportmenu/#defaultStyles_property
https://www.amcharts.com/docs/v4/concepts/exporting/#Styling

**Comment by martynasma** [comment]
Heads up. This article just been posted:
https://www.amcharts.com/docs/v4/tutorials/replacing-default-export-icon/
