### ISSUE TITLE
what is the difference between categoryX dateX and valueX?

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1229]
I cannot understand why there are 3 properties to set the X value.   C
Can somebody explain when to use each one (or the 3 together?)
Thanks !

**Comment by martynasma** [comment]
If you have `DateAxis` as your X axis, you use `dateX`.
If you have `CategoryAxis` as your X axis, you ouse `categoryX`.

You get the drift ;)

https://www.amcharts.com/docs/v4/concepts/series/#Binding_to_data
