### ISSUE TITLE
How to replace data with "addData" (or "incremental" and "keepCount")?

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1230]
I'm adding new data to my chart, but the new data should replace the data if is added to some X coordinate where there is already some value (if not will add the data and remove the first as usual).    
Something like;     
if( hasValue in X ) replace data in X    
else add Data and remove First Data (this is normal behaviour)    
Is this possible somehow or I need to modify the code?

**Comment by martynasma** [comment]
There's no built-in way to detect whether data point "already exists".

So it would probably be up to your code that updates data to do that.

If data point exists, you would modify the actual entry in `chart.data`, then call `chart.invalidateRawData()`. This will cause the chart to animate to new values, without re-evaluating the whole data.

If data point does not exists, you do `addData()` regularly.

Makes sense?
