### ISSUE TITLE
Change graph type dynamically

### ISSUE THREAD

**Issue by Ices-Eyes** [amcharts/amcharts4#1234]
Hi,
I would like to ask you an advice. I have a page with a single div graph container. Depending on some click I need to sometimes just reload the data of the graph (and this is easy), but sometimes need to change the graph type and series.
What I would like to ask you is if the best way to achive this is by destroing the current graph and composing a new one, or if there is a better way to do this.

Thanks :)

**Comment by martynasma** [comment]
There's no way to change type of the Series dynamically.

Your best bet is to remove the series, then create a new one.

**Comment by Ices-Eyes** [comment]
Ok, so to change also the graph type, from xy to radar or pie, and the axis types the best is to destroy and then recreate the entire graph... Thanks :)
