### ISSUE TITLE
Tooltip on valueAxis For Horizontal Line?

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1235]
As shown in [this pen](https://codepen.io/anon/pen/yrQjjR), I'm creating a horizontal line using a range grid based on the tutorial [here](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/).  The line is placed at the close of the last candlestick.  I'd like to create a tooltip similar to the valueAxis tooltip that shows the current value of a horizontal line (i.e. the close of the last candlestick).  The cursor valueAxis tooltip and the horizontal line tooltip would overlap if close.  Is this possible?

Alternatively, is it possible to create a second valueAxis tooltip at a fixed value (the same as the horizontal line)?

**Comment by martynasma** [comment]
Maybe something like this?

https://codepen.io/team/amcharts/pen/PLKMRN?editors=0010

**Comment by bfailing** [comment]
This works, but it presents some issues and questions.  See [this pen](https://codepen.io/anon/pen/GLzQPy).

1. How do you move the label to the left so that it is inline with the tooltip?  MarginRight affected the valueAxis labels as well.  It also was limited by `chart.leftAxesContainer.width`
2. How do you apply the numberFormatter to the range label (i.e. so that it is the same as the valueAxis labels)?  I tried adding it to `range` and `range.label`, but neither affected it.
3. It doesn't show up in the pen, but in my code the range label is placed before the valueAxis label elements in the DOM so that the valueAxis labels appear in front of the range label.  In the above pen, it is placed after the valueAxis label elements, so the range label appears in front of the valueAxis labels.  How can I fix this?  I tried applying zIndex to the range label, but it didn't seem to affect the inline styles, so I'm guessing that it won't help.
