### ISSUE TITLE
amcharts4 formatter for Octets

### ISSUE THREAD

**Issue by vipera7** [amcharts/amcharts4#1236]
I'm wondering if it's possible to format numbers into Octets. I'm able to format them in bytes.

Here is my charts : https://codepen.io/anon/pen/Pgxapa

**Comment by martynasma** [comment]
You can modify `bigNumberPrefixes` for that:

https://www.amcharts.com/docs/v4/tutorials/modifying-big-number-prefixes/#Modifying_suffixes

**Comment by vipera7** [comment]
So I do something like 

```
chart.numberFormatter.numberFormat = "#a";
chart.numberFormatter.bigNumberPrefixes = [
  { "number": /8, "suffix": "Byte" },
  { "number": /8, "suffix": "MegaByte" },
  { "number": /8, "suffix": "GigaByte" }
];
```

I'm a bit lost sorry

**Comment by martynasma** [comment]
More like this :)

```
chart.numberFormatter.numberFormat = "#a";
chart.numberFormatter.bigNumberPrefixes = [
  { "number": 8, "suffix": "Oct" },
  { "number": 8000, "suffix": "MegaOct" }
];
```

**Comment by vipera7** [comment]
Yeah right, How I did not think about it... Thank you a lot !

**Comment by vipera7** [comment]
I made some testing and the result I'm getting from it is false. Here is the new code pen : https://codepen.io/anon/pen/Pgxapa

**Comment by martynasma** [comment]
False how?

**Comment by vipera7** [comment]
The data result in a higher bandwidth value which should be reverse compared to bit

**Comment by martynasma** [comment]
OK, so if we don't apply number prefixes we have numbers like this on value axis:
5,000,000
10,000,000
etc.

If we turn custom prefixes, we get:

625MegaOct
1250MegaOct
etc.

5000000 / 8000 = 625
10000000 / 8000 = 1250

Seems right to me.

**Comment by vipera7** [comment]
Well if I take the first value of this charts I get 3.7MB and 68.4KB (https://codepen.io/anon/pen/GLPPGq)
And If I take the vlaue in Byte the value 489.23 MegaOctet and 8.75 MegaOctet (https://codepen.io/anon/pen/PgXVLd), the values seems to high for me

**Comment by martynasma** [comment]
In that case you may need to modify `bigNumberPrefixes` as per your requirements.

This works by dividing the actual value from the number you specify in "number".
