### ISSUE TITLE
Is possible to draw Candlestick chart mixed with a HeatMap?

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1237]
When I try to combine both charts, as soon as the line for pushing the new serie is reach this error is thrown:    
"Data fields for series "id-124" are not properly defined."

**Comment by martynasma** [comment]
Yes you can mix any `XYSeries` together.

Based on error I'm assuming you are using incorrect `dataFields` for one of the series.

It needs to match the type of the axis. E.g. if you have `DateAxis` as X axis, series use `dateX`. For `CategoryAxis` that's `categoryX`, etc.

Keep in mind that you can use multiple different categories as well if you need to.

**Comment by enriquepiatti** [comment]
yes you are right, I need two CategoryAxis for my heatmap so defining a valueAxis and CategoryAxis did the trick, but now I cannot put them in sync.      
I was trying defining the  valueAxis.min and valueAxis.max to the min and max from my CategoryAxis, but for some reason is not following that.   
min = 3760 and max = 5800 is putting correctly the top at 5800 but starting at 3600 ! do you know what could cause that?

**Comment by enriquepiatti** [comment]
OK, I found the problem here: https://www.amcharts.com/docs/v4/concepts/axes/value-axis/   
we need to add: valueAxis.strictMinMax = true;

**Comment by martynasma** [comment]
All set then? Or need any further assistance? :)

**Comment by enriquepiatti** [comment]
Well actually now you mention it there is another problem, but maybe is better in a new thread, I will open it now so we can close this
