### ISSUE TITLE
formatting with square brackets in category fields [foo]

### ISSUE THREAD

**Issue by paxapy** [amcharts/amcharts4#1238]
hello!
I'm getting issue with column chart, when i'm trying use data like this:
```
...
{value: 20559, xfullname: "[<=448.0]"}
{value: 19363, xfullname: "[>448.0]"}
...
```
and trying to use `xfullname` as column label:
`categoryAxis.dataFields.category = 'xfullname';`
it seems like amchart trying to treat it as text formatting and I have an empty labels on a chart.
what can I do to avoid this?

**Comment by martynasma** [comment]
You can disable formatting using [`ignoreFormatting`](https://www.amcharts.com/docs/v4/reference/label/#ignoreFormatting_property) setting on respective label.

For example, if you are using it in a `LabelBullet`:

```
bullet.label.ignoreFormatting = true;
```

**Comment by paxapy** [comment]
@martynasma thanks a lot! it seems like it was the thing i looking for, but can't figure out how to apply it for toolTip. I have series like this:
```
const series = chart.series.push(new am4charts.ColumnSeries());
series.dataFields.valueY = 'value';
series.dataFields.categoryX = 'xfullname';
series.tooltipText = '{xfullname}: {valueY}';
```
where should i set this `ignoreFormatting` parameter?

**Comment by martynasma** [comment]
```
series.tooltip.label.ignoreFormatting = true;
```

**Comment by paxapy** [comment]
thank you man.
was really helpful :pray: 
just for reference, i'll post here examples how I apply it in different cases:
`categoryAxis.tooltip.label.ignoreFormatting = true;`
`categoryAxis.renderer.labels.template.ignoreFormatting = true;`
`series.tooltip.label.ignoreFormatting = true;`
also, i'll change the title to be more specific about this, and close an issue
:kissing_cat:
