### ISSUE TITLE
Angular and React support for AmCharts4

### ISSUE THREAD

**Issue by Krishna-Agrawal** [amcharts/amcharts4#124]
By when can we expect to get Angular support for AmCharts4 similar to amcharts3-angular2?

**Comment by martynasma** [comment]
amCharts 4 has native support for ES6 modules and therefore does not need additional wrappers to be used in Angular2+ as V3 did. Just follow the guidelines in this articles and you should be good to go:

https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/
