### ISSUE TITLE
Zooming out remove date but keep time

### ISSUE THREAD

**Issue by vipera7** [amcharts/amcharts4#1240]
When I'm zooming in my chart, I can see the date like `26 Apr, 9:05` but when I zoom out I only see time like `9:00`. How can I show the date all the time ? Here is my graph :
https://codepen.io/anon/pen/GLPPGq

**Comment by martynasma** [comment]
Try lowering `minGridDistance`:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by vipera7** [comment]
I found it, I needed to add the following :

```
dateAxis.dateFormats.setKey("hour", "d MMM,\nHH:mm");
dateAxis.periodChangeDateFormats.setKey("hour", "d MMM,\nHH:mm");
```
