### ISSUE TITLE
Maximum call stack exceed - Sankey Diagram

### ISSUE THREAD

**Issue by adtype-com** [amcharts/amcharts4#1243]
There seems to be a problem when loading a specific dataset into a Sankey chart. Seems to be a problem with circular paths. In our case we have some states that can appear repeatedly, but it's important that they're not added to the beginning of the chart, but as a continuation of the full path.

### Works
Because there aren't any circular paths: https://codepen.io/anon/pen/yrZaoP
```
{ from: "A", to: "B", total: 14 }
{ from: "B", to: "C", total: 60 }
```
### Does not work
Because there are circular paths: https://codepen.io/anon/pen/xeMEdQ
```
{ from: "A", to: "B", total: 14}
{ from: "B", to: "A", total: 60}
```
### Workaround
To circumvent the issue we've added a label with the "level" to differentiate A1 from A2 (even though all A's are the same for us): 

https://codepen.io/anon/pen/NmoRMj

But ideally we would prefer not to have those indexes as labels. Is there any way to specify a different `label name` (used as visual name) than `label id` (used to create nodes and links) or something to the effect? Thanks!

**Comment by martynasma** [comment]
You could use an adapter to strip down suffixes, e.g.:

```
chart.nodes.template.nameLabel.label.adapter.add("textOutput", function(text) {
  return text.replace(/[0-9]+$/, "");
});
```

Here's a working example:
https://codepen.io/team/amcharts/pen/441623c9a741519377493974d3611970?editors=0010

**Comment by adtype-com** [comment]
Yes, that should definitely work for us. Thanks for the suggestion!
