### ISSUE TITLE
 dateAxis points (ticks) vs series points 

### ISSUE THREAD

**Issue by AndrewSlv** [amcharts/amcharts4#1244]
Hi!
How can I influence the calculation of the X-axis (date).
I have dynamic data. And depending on the period, I get a series of data with different steps. Not necessarily "day", "week", "month" .. but rather a certain number of days. If I have a week (7 points) or a month (every day - ~ 30 points) then all is well.
But if I have a long period of several months, in increments of several days (for example, 7), then the problem is.
How can I display the labels and the grid so that the series points coincide with the grid and labels. That labels would be the same points of the series.
Ex: in first case i have 30 data points (month) with step 1 day. And grid, labels and series points on the same line.
![image](https://user-images.githubusercontent.com/1997620/56819835-41fa2e80-6853-11e9-901e-f16140b7ac23.png)
2nd case I have a data range from 02.02.2019 - 20.04.2019 with step 7 (days) .. 
![image](https://user-images.githubusercontent.com/1997620/56819666-dd3ed400-6852-11e9-8f66-8eeb2c32a432.png)
P.S.: I tried to set a property baseInterval with { timeUnit: 'day', count: 7 } but its not help

**Comment by martynasma** [comment]
You can use `location` for that:

```
dateAxis.renderer.grid.template.location = 0.5;
dateAxis.renderer.labels.template.location = 0.5;
dateAxis.renderer.ticks.template.location = 0.5;
```

**Comment by AndrewSlv** [comment]
Thanks for your advice, but it does not help.
amchart dateAxis calculates tiks itself. The above solution only shifts the grid but does not set it correctly (exactly) on series points.
If I take periods 05.03 - 23.04  i will have 12 points in series [05.02, 12.02, 19.02]
![image](https://user-images.githubusercontent.com/1997620/56895037-6ee75500-6a90-11e9-8c70-29797b044501.png)
but on axis its calculate (show) 04.02, 11.02
![image](https://user-images.githubusercontent.com/1997620/56895017-5840fe00-6a90-11e9-9a7f-a8a8fa64268a.png)
In this case calculated ticks has some shift 1 day .. 
In another case If I take periods even more from 20 May 2018 to 21 Apr 2019 
17 points with 21 day step ...
![image](https://user-images.githubusercontent.com/1997620/56895181-e917d980-6a90-11e9-8b5b-d4eb213d1f2d.png)
![image](https://user-images.githubusercontent.com/1997620/56895218-0f3d7980-6a91-11e9-9906-5e1d26a8feb0.png)
How can i manually set the step and points to be used on the axis?

**Comment by martynasma** [comment]
There are a number of ways to influence steps/density of the DateAxis labels.

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

Also modifying `gridIntervals`:
https://github.com/amcharts/amcharts4/issues/1078#issuecomment-473195664
