### ISSUE TITLE
addData is removing more data than expected

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1245]
Maybe the error is due my configuration, this is my chart:    
X: Category Axis    
Y: 2 axis: Value and Category    
With ValueAxis I have a candlestick series, and with Category I have a HeatMap    
My data is something like (pseudoCode):    
{ xValue, yValueForHeatMal, valueForHeatMap, open, high, low, close }     
There are 100 entries like that for every xValue, but only the first one of those have open, high, low and close properties.    
The chart is drawn correctly, but the problem is with "addData":    
// items is an array of 100 elements for the same xValue (this means adding a new X entry for every value in CategoryY axis).

> chart.addData(items, 0);    // this line works ok

But the problem is with remove:     
`chart.addData(items, 1);    `

this works almost OK, it adds the new values, but removes one extra point from the start, so every time I call addData the YAxis is cut by one value.    

Any ideas?

**Comment by martynasma** [comment]
Well, that argument means how many data points to remove from the start, so it's working as designed.

If you have several series that are fed by a single `chart.data`, you might want to consider setting `data` directly on series, then calling `addData()` on the series you want to update data for, leaving the other one intact.

Hope that makes sense.

**Comment by enriquepiatti** [comment]
Yes I have all data in the same chart.data. But I think I will need a special modification to the remove function, because I want to remove one categoryX value, not only one item, and is not even "fixed" the number of "Y" values for every "X"

**Comment by enriquepiatti** [comment]
do we need to call invalidateData(); after addData()?    
because after addData() if I remove the items the chart is almost destroyed (it removes much more items than expected) and calling invalidateData() fix the problem

**Comment by martynasma** [comment]
No, there's no need to call `invalidateData()` after `addData()`. In fact, it would cause excessive overhead since `invalidateData()` would cause **all** data to be revalidated, as opposed to just data points that were added.

As of it "destroying" the chart, would you be able to provide a working example? I'd like to take a look in case there's a bug or something.

**Comment by enriquepiatti** [comment]
You can find an example here:     
https://codepen.io/enriqu3/pen/PgvBpK    
just click the "add remove" button after the chart is loaded (you can see Add button works fine, is the same code but it has remove=0)     
Also I'm a bit worried about the performance, this code is explained here:   
https://github.com/amcharts/amcharts4/issues/1257
