### ISSUE TITLE
Request: Custom tooltip text callback function

### ISSUE THREAD

**Issue by Ekliptor** [amcharts/amcharts4#125]
It would be very nice to have a custom tooltip text function.
I am using the map chart with your default worldLow geo data. My tooltips look like this:
`polygonTemplate.tooltipText = "{name}\r\nStreams: {streams}\r\nDatacenters: {datacenters}";`
However, I only have custom data for `streams` and `datacenters` for a few countries. So the value is empty for most countries (showing ugly tooltips because it's obvious that something is missing there).

To set default/empty values as well as correct ones, a callback function like this would be great:
```
polygonTemplate.tooltipTextFunction = function (data) {
        // check if null/undefined and return alternative values
        return data.name + "\r\nStreams:"  + data.streams;
}
```

My chart code:
```
        let chart = am4core.create("streamCountryMap", am4maps.MapChart);

        // Set map definition
        chart.geodata = am4geodata_worldLow;
        // Set projection
        chart.projection = new am4maps.projections.Miller();

        // Create map polygon series
        let polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
        // Make map load polygon (like country names) data from GeoJSON
        polygonSeries.useGeodata = true;
```

This is not urgent, as my current workaround is to just modify `am4geodata_worldLow` myself and add some default/empty values.

**Comment by martynasma** [comment]
You can use adapters for that:

```
polygonTemplate.adapter.add("tooltipText", function(text, target) {
  return "something " + text;
});
```

https://www.amcharts.com/docs/v4/concepts/adapters/

**Comment by Ekliptor** [comment]
Sorry, but I have to open this again:
How do I access my data within the adapter?
Data:
```
        polygonSeries.data = [{
            "id": "US",
            "name": "United States",
            "streams": 100,
            "fill": am4core.color("#F05C5C")
        }, {
            "id": "FR",
            "name": "France",
            "streams": 50,
            "fill": am4core.color("#5C5CFF")
        }];
```

This causes the value for `streams` to be displayed correctly in the formatter:
`polygonTemplate.tooltipText = "{name}\r\nStreams: {streams}";`

But how do I access it via `target`?
```
polygonTemplate.adapter.add("tooltipText", function(text, target) {
  console.log(target.dataItem.value) // undefined
  console.log(target.dataItem.values) // empty object
  console.log(target.dataItem.streams) // undefined
  return "something " + text;
});
```

**Comment by Ekliptor** [comment]
Thx for the great help as always. You might want to add the `dataContext` to the tutorial about adapers😇
https://www.amcharts.com/docs/v4/concepts/adapters/

**Comment by martynasma** [comment]
Noted. However, target of the adapters can be virtually anything, not just `DataItem`, so this information might be too specific for generic concept article like the one you referred to.
