### ISSUE TITLE
am stock chart overlaps category label when chart scroll move

### ISSUE THREAD

**Issue by pankajd1990** [amcharts/amcharts4#1250]
I am working stock chart of record per millisecond format.when i move scroll left to right,all labels of stock chart are overlapping each other.this is my code 

`{
    type: "stock",
    theme: "none",   
    categoryAxis:{  
        showFirstLabel:true,
        showLastLabel:true,        
        gridPosition: "start",
        gridAlpha: 1,     
    tickPosition: "start",   
    tickLength: 20,
    autoGridCount :true,
    centerLabels:true,
    fontSize:15,
    glueToTheEnd:true,
    zoomOutOnDataSetChange:true,
    dateFormats:[{"period":"fff","format":"JJ:NN:SS.QQQ"},{"period":"ss","format":"JJ:NN:SS"},{"period":"mm","format":"JJ:NN"},{"period":"hh","format":"JJ:NN"}],           
    },
    valueAxesSettings :{
        gridThickness:1,    
        axisColor:"#FFFFFF",
        showLastLabel:true,
        axisThickness:1,
        inside:false,
        axisAlpha:1,
        unitPosition:"left",
        tickLength:1,        
        labelRotation:-90, 
    },
    categoryAxesSettings: {
      minPeriod:"fff",
      groupToPeriods:["fff"],
      color:"#FFFFFF",
      axisColor:"#FFFFFF",    
      axisAlpha:1,    
      dateFormats:[{"period":"fff","format":"JJ:NN:SS.QQQ"},{"period":"ss","format":"JJ:NN:SS"},{"period":"mm","format":"JJ:NN"},{"period":"hh","format":"JJ:NN"}],           
      equalSpacing:true,
      gridPosition: "start",
      gridAlpha: 1,
      tickPosition: "start",
      tickLength: 5,
      inside:false,
      fontSize:15,
     
    } ,
    dataSets: [ {
      color: "white",
      fieldMappings: [ {
        fromField: "MRFILLPRICE",
        toField: "MRFILLPRICE"
      }     
    ],
     dataProvider:[],
      categoryField: "MRJIFFYTMST",      
       stockEvents: []
    } ],
  
  
    panels: [ {
       
      title: "Price",
      marginTop:100,
      autoMargins:false,
      percentHeight:60,
      showCategoryAxis: true,
      valueAxes: [{
        position: "left",        
        id:"p1",              
        inside:false,     
        color: "#FFFFFF", 
        axisColor:"green", 
        axisAlpha:1,
        title:"Price",
        axisThickness:5,   
        minMarginTop:20,
        marginTop:20,             
        labelOffset:3,
        labelRotation:-90, 
        maximum:0,
        minimum:0,
        fontSize:15,
        "useDataSetColors": false,      
      },     
    ],
      stockGraphs: [ {
        id: "g1",
        valueField: "MRFILLPRICE",
        showAllValueLabels:true,
        valueAxis:"p1",
        type: "smoothedLine",
        lineThickness: 1,
        bullet: "round",   
        bulletAlpha:0,
        // forceGap:true,
        bulletSize:0,
        balloonColor:"white",
        lineColor: "red",
        showBalloon:true,
        
        balloonText:"Time:<b>[[tm]]</b><br> Price:-<b>[[MRFILLPRICE]]</b>",
        
        gapPeriod:5,
        "useDataSetColors": false,       
      } ],
      stockLegend: {
        valueTextRegular: " ",
        markerType: "square"
    }
    } ],
    stockLegend: {

    },
    chartScrollbarSettings: {
      graph: "g1",     
      offset:10,
      enable:false,
      autoGridCount:true,
      position:"top"
    },
    chartScrollbar:{
        offset:200,
        updateOnReleaseOnly: true,
        autoGridCount:true
    },
    chartCursorSettings: {
      valueBalloonsEnabled: true,
      graphBulletSize: 1,
      valueLineBalloonEnabled: true,
      valueLineEnabled: true,
      valueLineAlpha: 0.5,
      enabled:false,
      categoryBalloonDateFormats: [{
        period: "fff",
        format: "NN:SS:QQQ"
    }]
    },        
    panelsSettings: {
      usePrefixes: true,
      marginLeft:60,      
      marginTop:10, 
    },   
    export: {
        enabled: true,
        position: "bottom-right"
    },
    listeners: [ {
        event: "dataUpdated",
        method: function(event) {
          console.log("data updated");
        }
      } ]        
  } 
}
![Screenshot_3](https://user-images.githubusercontent.com/16352295/56878521-25880d00-6a72-11e9-833f-cc15bb40a20a.png)

`

**Comment by pankajd1990** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/16352295/56878475-f2457e00-6a71-11e9-9ea8-518e6c3b7cf3.png)

**Comment by martynasma** [comment]
This is repository for amCharts 4. Closing.
