### ISSUE TITLE
invalidateRawData doing nothing

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1252]
I'm trying to update my chart data in this way but the chart does not change:    
```
        for (var i = 0; i < items.length; i++) {
            chart.data.push(items[i]);
        }
        chart.invalidateRawData();
```     

Am I missing something?   
I need a really fast update, I have a CategoryX with two YAxis (one category and one value).    
Sometimes I need to add a new categoryX at the end (with the Y values) and in that case also remove another categoryX (with its Y values, which is not a constant number). And sometimes I need to replace the last categoryX Yvalues without removing anything.     
    
So I cannot use addData in any of the 2 operations (because is not replacing data, and because is not removing my data from arbitrary position).    
    
Any ideas?

**Comment by martynasma** [comment]
`invalidateRawData()` is fr situations where you change value of **existing** items in `data`.

It causes old values to animate to new ones.

It will not check or take in any new data items you add, or remove, or replace.

If you add something new, you can use `addData()`.

In other cases, you will need to call `invalidateData()` causing all of the data set to be revalidated.

**Comment by enriquepiatti** [comment]
The scenario is a bit confusing. Because on the same "X" I have multiple Y values, but is not a constant number of items. Maybe in X1 I have 3 Y values (Y1, Y2 and Y3) and then I want to update all the values for X1 to 2 or four Y. Is this adding data or replacing?

**Comment by martynasma** [comment]
If you are replacing numeric values on **existing** data points, `invalidateRawData()` should do.

If you add/remove/replace any of the data points in `data` array, `invalidateRawData()` won't work correctly.
