### ISSUE TITLE
Charts not showing visible lables - Html to PDF Covert 

### ISSUE THREAD

**Issue by jgathairu** [amcharts/amcharts4#1253]
Am using selectPDF on asp.net core application. I have created a html page that automatically converts to PDF ready for sending via a JOB scheduler. The exports works well only that the amcharts lables are not visible though you can see there is some text. Am attaching the results of exports together with expected behavior. The following code didnt work.   _pieSeries.labels.template.fill = am4core.color("black");_
![Capture-What I require](https://user-images.githubusercontent.com/29246216/56902378-dad2b900-6aa2-11e9-83ca-e0dd3f1d1c1f.JPG)
![Capture-Labels with no Visible Color](https://user-images.githubusercontent.com/29246216/56902379-db6b4f80-6aa2-11e9-884b-fbcb94a08e55.JPG)

**Comment by martynasma** [comment]
I'm afraid we're not familiar with selectPDF :(

I suppose there might be some issue. Probably would make sense to bring it up with selectPDF developers, so they can look into why labels are not being exported.

**Comment by jgathairu** [comment]
Thanks. Will raise the issue with SelectPDF
