### ISSUE TITLE
strokeOpacity cannot be set for column series

### ISSUE THREAD

**Issue by justinhelmer** [amcharts/amcharts4#1254]
From the XY chart example for stacked column series, try adding a stroke and opacity, i.e.

```js
series.stroke = am4core.color('red');
series.strokeWidth = '5px';
series.strokeOpacity = 0.1; // ignored
```

Tried with different colors. Forked example pen:

https://codepen.io/anon/pen/rbbwEL

**Comment by martynasma** [comment]
This is because each column has `strokeOpacity` explicitly set on it, so the setting set on series directly is not being inherited.

To fix it set directly on column template:

```
series.columns.template.strokeOpacity = 0.1;
```

**Comment by justinhelmer** [comment]
That does it thanks! Updated the title slightly so it doesn't seem to be reported as a bug, in case others search for this same problem.

**Comment by justinhelmer** [comment]
As a follow-up, is there a way to gather this information through the documentation? It sometimes can be tough to know about the full spectrum of capability and options for things like `*.renderer` or `*.template`. There is documentation for things like [AxisRenderer](https://www.amcharts.com/docs/v4/reference/axisrenderer/) and [ListTemplate](https://www.amcharts.com/docs/v4/reference/listtemplate/), but it doesn't seem to line up with the examples illustrated in your otherwise very comprehensive docs.

**Comment by martynasma** [comment]
Well, I have to admit it that no. There's no such list.

With so much hierarchy going on, as well as organic SVG property inheritance, it's not easy to always know if property is being overridden with a default somewhere down the line, or not :/

**Comment by justinhelmer** [comment]
No problem, I completely understand. It can be difficult to write and maintain this level of documentation.

Overall, the solution is very intuitive and the level of documentation is impressive. Thanks for the help.
