### ISSUE TITLE
Very slow performance combining candles with heat map (codepen example)

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1257]
Hi here is the example:    
https://codepen.io/enriqu3/pen/PgvBpK    
Try putting max hour to 18 for example and it will take a very long time (if not crash)    
     
Code Explanation:     
X: CategoryAxis    // time in data
Y1: CategoryAxis (for heat map)   // price and volume in data
Y2: ValueAxis (for candles)     // open, high, low, close in data
chart.data = [ { time, price, volume, open, high, low, close } ... ]     // OHLC only present in one item per "time"    
First "column" ("time" value) is a fake data, with volume=0 for every possible "price", so we can keep Y1 and Y2 in sync.     
    
Is this the max performance we can get with amcharts or we can do some improvement?

Thanks !!

**Comment by martynasma** [comment]
At this point we can't offer any immediate improvement for this kind of chart. It's a lot of objects.

We'll have our eyes open for opportunities to speed it up, just not sure if/when that happens :(

**Comment by enriquepiatti** [comment]
OK, could you tell me what is the main problem? maybe I can work a bit to improve it.     
Because the data is not so big, is less than 10K items, so maybe the problem is related with having two axis? or the heatmap filter? or too many "rectangles" (heat map)?

**Comment by martynasma** [comment]
Not sure what to suggest, I'm afraid. A column is not a single element, there are more accompanying elements, like groups, etc.

Save for reducing number of rectangles, there's not a lot you can do :/
