### ISSUE TITLE
ignoreFormatting and mixed (brackets]

### ISSUE THREAD

**Issue by paxapy** [amcharts/amcharts4#1260]
i know I have pretty uncommon scenario and brackets here in data used to point if number is in a range or not, but still..
in this pen https://codepen.io/paxapy/pen/oOrrbK I have very strange situation when `ignoreFormatting` seams to work like partially or something. so:
`"y":"(30.0 to 33.0]"` -> `(30.0 to 33.0`
`"y":"[33.0 to 37.0)"` -> `[33.0 to 37.0)]`
is there something i can do about this?

**Comment by martynasma** [comment]
How about just escaping square brackets?

`"y":"(30.0 to 33.0]]"`
