### ISSUE TITLE
Dynamic load region map - naming

### ISSUE THREAD

**Issue by kenzo23312** [amcharts/amcharts4#1261]
I have question how to get dynamically region map.

From world map I get data:

```
id: "SA"
madeFromGeoData: true
multiPolygon: [Array(1)]
name: "Saudi Arabia"
```

but region map need name pattern: saudiArabia.

This is easy use case, there are more like Saint -> st / sint 
United States -> usa 

Is there a way to import this name without hundreds of IF to check if it's not common name for region map ?

**Comment by martynasma** [comment]
I'm afraid there's no easy way to map country "id" to a country map, besides maintaining some sort of mapping list.

Unfortunately, we don't have one readily available.

We're going to give it some thought, tho. Maybe we can include it.

**Comment by kenzo23312** [comment]
Since there is no naming convention than dynamic use is useless.

**Comment by kenzo23312** [comment]
@martynasma One more question, do you have any converter / way to convert missing svg maps to geojson format ?

SVG maps source: https://www.amcharts.com/svg-maps/

**Comment by martynasma** [comment]
No, but we have a guide on creating maps from shape files:
https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/

**Comment by kenzo23312** [comment]
But why I need to create from scratch since you have already prepared svg files, is it possible to load those files in armcharts v4 ?

**Comment by martynasma** [comment]
There's no way to load V3's SVG files into V4, I'm afraid.

V3 used SVG.
V4 uses GeoJSON.

**Comment by Ices-Eyes** [comment]
Regarding the first matter, why not to create a reverse map from name to ID? You should create it once and use on name property, without having to use all the if in the code...

**Comment by martynasma** [comment]
@Ices-Eyes The issue is not mapping name of the country to its it. It's mapping id of the country to a map file / geodata. The map file may not be exactly like a name.

For example: United States (US) has a file usaLow/usaHigh. There's no way to translate "United States" into "usa" according to any universal rules.

So the only way is for us to maintain so sort of map list ID > map file, which we are already looking for ways to do.

Will keep you guys posted.

**Comment by Ices-Eyes** [comment]
Ok, completely misunderstood the problem, sorry :)

**Comment by martynasma** [comment]
OK, there you go:
https://github.com/amcharts/amcharts4-geodata/blob/master/dist/script/countries.json
