### ISSUE TITLE
How to disable zoom out button

### ISSUE THREAD

**Issue by lounikffm** [amcharts/amcharts4#1262]
Hi Guys,

im building an XY chart at the moment and since I am using custom controls to zoom in and out of the chart I don`t need the default zoom out button in the top right corner. Is there any way to disable that button from being shown?

**Comment by martynasma** [comment]
Sure:

```
chart.zoomOutButton.disabled = true;
```

:)

**Comment by lounikffm** [comment]
Oh well okay that was easy :D thanks a lot

**Comment by pushprajchaudhary** [comment]
@martynasma How can I disable mouse swipe zoom on line charts

**Comment by chengzh2008** [comment]
Save ask. Is there a way to disable the zoom out functionality via mouse range selection?

**Comment by puredazzle** [comment]
@pushprajchaudhary you can do it by disabling the behavior on the cursor:

```
chart.cursor = new am4charts.XYCursor();
chart.cursor.behavior = "none";
```
