### ISSUE TITLE
Tooltips breaks after angular router.navigate

### ISSUE THREAD

**Issue by FrankMerema** [amcharts/amcharts4#1264]
Hi,

I am experience an issue regarding to [Issue 802](https://github.com/amcharts/amcharts4/issues/802). You guys fixed the toolips perfectly on FF45, but after upgrading to that version my tooltips breaks on Chrome. It hadn't got a high prio until now, so after a couple of days trying to reproduce finally I got it (not) working :p

[Stackblitz example](https://stackblitz.com/edit/gantt-chart-active-item-bug?file=src%2Fapp%2Fdashboard%2Fdashboard.component.ts)

Try to click on some series and you see the tooltip breaks... I have added some comments in the code to play around with.

Hopefully this is enough info for addressing the issue. If not please ask and I am happy to investigate more!

**Comment by FrankMerema** [comment]
Any updates maybe already?

**Comment by martynasma** [comment]
Gah I think we forgot to notify you. Try 4.4.4. Let us know if that fixes it.

**Comment by FrankMerema** [comment]
You guys rock! Thanks for the fix!

Fixed in 4.4.4
