### ISSUE TITLE
How to pre zoom to the current day on timestamp

### ISSUE THREAD

**Issue by vipera7** [amcharts/amcharts4#1265]
I'm trying to pre-zoom my charts to show the current day. Here is my graph :

https://codepen.io/anon/pen/zXggRG

Here is the code I added :

```
    chart.events.on("ready", function () {
        dateAxis.zoomToDates(
            new Date(2019, 5, 02),
            new Date(2019, 5, 03)
        );
    });
```

**Comment by martynasma** [comment]
Since you are loading data externally, which is not yet available when "ready" event kicks in, you're better off with using "datavalidated" event instead.

```
    chart.events.on("datavalidated", function () {
        dateAxis.zoomToDates(
            new Date(2019, 5, 02),
            new Date(2019, 5, 03)
        );
    });
```

**Comment by vipera7** [comment]
I used  datavalidated but it doesn't take the range
https://codepen.io/anon/pen/BeBymx

**Comment by martynasma** [comment]
Note that months in `Date()` constructor are zero-based. January is 0, Feb - 1, etc. So you're instructing it to zoom to June 2-3.

**Comment by Ices-Eyes** [comment]
On the same topic, is there a way to prezoom to the last x days/month, without knowing what the last day in the data is?

**Comment by martynasma** [comment]
> On the same topic, is there a way to prezoom to the last x days/month, without knowing what the last day in the data is?

There's no dedicated method to "prezoom to last X days".

Probably the easiest way is to grab dates from last data point and X-th data point from the end of data, and use those dates in `zoomToDates()`.
