### ISSUE TITLE
[Question] - Dead code elimination?

### ISSUE THREAD

**Issue by justinhelmer** [amcharts/amcharts4#1267]
I found a significant performance limitation when comparing amCharts against some other libraries. As far I could tell, you do not provide a babel plugin (or some other transformation) to cherry-pick / tree-shake just the charts we will use in our application.

In other words, we are forced to import the entire `am4core` + `am4charts` libraries into our codebase (which is a whopping 187kB, including gzip + minification/obfuscation with [terser](https://github.com/terser-js/terser)), just to use a single chart.

Perhaps I missed something, and you actually do provide a transformation similar to [babel-plugin-recharts](https://github.com/recharts/babel-plugin-recharts)?

Thanks for the info. This will help us in making a decision.

**Comment by justinhelmer** [comment]
I posted this question through the website contact feature to the sales team, a week ago - but I have received zero traction there.

**Comment by martynasma** [comment]
Well, treeshaking should work to some extent, however I agree it's not a perfect solution. The core of V4 has a lot of interwoven dependencies. I'm afraid there's little you or us can do about reducing the size of the lib drastically at this time. Sorry.

**Comment by justinhelmer** [comment]
Thanks for the info.
