### ISSUE TITLE
Retrieving object from TreeMap

### ISSUE THREAD

**Issue by Rapster** [amcharts/amcharts4#1268]
I'm trying to retrieve the "clicked" object from TreeMap at level 0 with this sample https://codepen.io/team/amcharts/pen/erojQb, by doing so:

```js
chart.seriesTemplates.template.columns.events.on('hit', function(ev) {
  console.log(ev.target.dataItem);
});
```

But `dataItem` is always set as undefined. I suspect a bug here... I tried to get some help from here also: https://stackoverflow.com/questions/55969915/retrieving-object-from-treemap

**Comment by martynasma** [comment]
It's a bit more complicated than that. To attach events, you'll need to to actually create series for the specific level, then attach events on its column template:

```
var series = chart.seriesTemplates.create("0");
series.columns.template.events.on('hit', function(ev) {
  console.log(ev.target.dataItem);
});
```

**Comment by Rapster** [comment]
Great, thank you!

**Comment by Fasih1994** [comment]
How do you get the name of the entity shown in the leaf (box) of the treemap. I have some names which I am showing on tree map 
and also showing other stuff related to those entities. what I want is to get the name out of a click that on which box a user have clicked then pass that name to query so I can adjust other visualization related to user's click.
