### ISSUE TITLE
Way to avoid slider and export button overlap

### ISSUE THREAD

**Issue by Ices-Eyes** [amcharts/amcharts4#1269]
Hi there,
in a situation like the one on this pen
https://codepen.io/Ices_Eyes/pen/aroXbZ
is there a way to avoid bottom slider and export button to overlap? I tried play with dx/dy margins and pagging of the slider, but not able to obtain somethin working good.

Thanks :)

**Comment by martynasma** [comment]
Dunno, `chart.paddingRight = 60` should solve the issue :)

**Comment by Ices-Eyes** [comment]
Mmmh.... working but not really nice... :D
I was looking if it is possibile to use a container for better result...

**Comment by martynasma** [comment]
What would you consider a "better result"? :)

**Comment by Ices-Eyes** [comment]
Well, the Graph is a column chart, and making it padding results on seeing it not centered in the page. This is somehow not really good looking :)
