### ISSUE TITLE
Update chart with JSON config

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#127]
Hello !

Is there a way to update full chart with a specific JSON config or I need to destroy the chart and rebuild it each time ?

I tried to do: 

`amchart.config = {  new JSON CONFIG }` => Duplicate id (id-7715) used on multiple objects.

**Comment by martynasma** [comment]
If you want to replace a chart with a wholly new config, then destroying current one and creating a new one sounds like a better way.

```
// Destroy old instance
amchart.dispose();

// Create a new one
amchart = am4core.createFromConfig({ ... }, ...);
```

I'm going to go ahead and close this, but feel free to reply back if you're still having issues with it.
