### ISSUE TITLE
Region data js file errors.

### ISSUE THREAD

**Issue by dvodvo** [amcharts/amcharts4#1270]
Note.  These errors were derived from the downloaded package of all nations with regions and refer to the "...Low.js" version of the file.  Errors were teste on localhost and remote servers.

Country code PH returns "this.getFeature(...) is undefined"
Country code ZA & PK render a blank page, 
while ZM goes into a heavy calculation loop and returns  a [toungue-in-cheek here...] very nice picasso-esque rendering of that nation :
![Screen Shot 2019-05-05 at 14 34 48](https://user-images.githubusercontent.com/716130/57194105-08a47b80-6f43-11e9-8909-d92865dab6df.png)

**Comment by dvodvo** [comment]
Also, NZ renders really, really tiny...  I do not recall New Zealand having any tiny island near the arctic circle.  I check the JSON data and the starting geo coordinate always sits between 168...177 and -36...-52  so there appears not to be any geocoordinate error (the map is decent upon zooming in) so there must be some quirky setting in the midst.

**Comment by martynasma** [comment]
Um, which particular maps renders like that? I wasn't able to understand it from your description.

As for the map of NZ, they don't have an island that's far away, but they do have one (Chatham) that jumps over 180/-180 longitude causing it to be drawn across all of the map.

The solution is to use `deltaLongitude` to rotate the longitude a bit so the island "fits":

```
chart.deltaLongitude = -10;
```

https://codepen.io/team/amcharts/pen/VOYLap

**Comment by dvodvo** [comment]
PH, Philippines, returns the javascript error
ZA & PK, South Africa and Pakistan render blanks
ZM, Zambia, has the affinity to Picasso.
Will keep in mind that fix for other cases similar to NZ!

**Comment by martynasma** [comment]
Thanks!

> PH, Philippines, returns the javascript error
Confirmed. Low-detail version is broken. We're going to fix it.
High-detail version appears to be fine.

> ZA & PK, South Africa and Pakistan render blanks
Can't reproduce this one. Both maps appear fine in my tests.

> ZM, Zambia, has the affinity to Picasso.
Yup. Zambia map is broken. Fixing.

Let me know if you find any other issues or ways to reproduce issue with ZA/PK maps.

**Comment by dvodvo** [comment]
ZA & PK - my bad.  They render fine. Since the 2-character iso is being used, I am calling the maps with that code and thus need to modify the js file accordingly.  had thrown in a stupid space after 2-character code in these two instance.

Can you advise when the other two are fixed?

**Comment by martynasma** [comment]
Just released updated geodata package (4.1.5).

It also contains a JSON file which maps country IDs to their respective map files.

https://github.com/amcharts/amcharts4-geodata/blob/master/dist/script/countries.json
