### ISSUE TITLE
Export Not working Properly in IE 11

### ISSUE THREAD

**Issue by srajanish** [amcharts/amcharts4#1271]
image export is not working in IE properly,i'm trying to export the chart with transparent background but it's exporting as a black color background in IE,its working fine in chrome .Please give some solution for this issue.

see the below code im using

chart.exporting.backgroundColor="transparent";
chart.exporting.getImage("png",true,0.9).then(function(imgData) {

})

giving black background color in IE when export to png with base64 format

**Comment by martynasma** [comment]
IE does not understand color "transparent".

Try this instead:

```
chart.exporting.backgroundColor = am4core.color("white", 0);
```
