### ISSUE TITLE
Gantt Chart with clickable Category rows

### ISSUE THREAD

**Issue by dtsw** [amcharts/amcharts4#1272]
It is not an issue, but rather a question for the example at https://www.amcharts.com/demos/gantt-chart/ 
I would like to have the names on the left clickable, and if one clicks on a name, do something with the data on that row (display, open a website... )
I guess i can somehow use categoryAxis.getSeriesDataItem to get the item, but i was not able to attach the event to make it firing when clicking on name(s)

**Comment by martynasma** [comment]
I suppose you can add "hit" events on the category axis labels:

```
categoryAxis.renderer.labels.template.cursorOverStyle = am4core.MouseCursorStyle.pointer;
categoryAxis.renderer.labels.template.events.on("hit", function(ev) {
  console.log(ev.target.dataItem.category);
});
```

**Comment by dtsw** [comment]
works, thanks :)
