### ISSUE TITLE
Label color auto contrast - help

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#1273]
It is possible to set label color to detect contrast and work as tooltip text does?

See pen bellow:
https://codepen.io/aniov/pen/NVPQvj?editors=0010

Thank you.

**Comment by zeroin** [comment]
Yes, you can do it with a help of adapter:

```
series.nodes.template.label.adapter.add("fill", (fill, target)=>{
  return am4core.color(target.dataItem.color).alternative;
})```

**Comment by aniov** [comment]
Thanks, this works :)
(I was trying the same thing but attaching the adapter in the wrong spot)
