### ISSUE TITLE
Series tooltip only on mouse hover

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#1274]
Hello,

Is there a way to print series tooltips only when the mouse is hover the serie ?

Here what I actually have when I move the mouse over the period:

![image](https://user-images.githubusercontent.com/6083644/57299265-687e5c00-70d4-11e9-8e64-bed2ed56036f.png)

**Comment by martynasma** [comment]
Yeah. To disable Cursor tooltip, set https://www.amcharts.com/docs/v4/reference/xyseries/#cursorTooltipEnabled_property for all your series.
