### ISSUE TITLE
Sankey Chart nodes margin

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#1276]
Hello !

Is there a way to change node margin in sankey chart ? 

![image](https://user-images.githubusercontent.com/6083644/57300025-3cfc7100-70d6-11e9-81c9-c0e268379e7d.png)

I didn't see something about that in documentations

Thanks for your help !

**Comment by zeroin** [comment]
Yes, use chart.nodePadding property: 

`chart.nodePadding = 5;`
