### ISSUE TITLE
ValueAxis extraMin/extraMax analogue

### ISSUE THREAD

**Issue by sadman4eg** [amcharts/amcharts4#1279]
For CategoryAxis we can use extaMin and extraMax (to add padding between chart values and axis). But this property don't work for valueAxis. Cold you help me to find analogue? I spent more then day to solve this problem but failed.

**Comment by martynasma** [comment]
You mean something similar for `CategoyAxis`?

You can use `startLocation` and `endLocation`:

```
categoryAxis.startLocation = -0.5;
categoryAxis.endLocation = 1.5;
```

More info and demo:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends
