### ISSUE TITLE
locationY of RadarColumn bullets does not position as expected

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#1280]
[Expect a `locationY` of `1` would position the bullet on the bottom of columns](https://www.amcharts.com/docs/v4/concepts/bullets/#Positioning_within_column), e.g.

```javascript
var series = chart.series.push(new am4charts.RadarColumnSeries());
var labelBullet = series.bullets.push(new am4charts.LabelBullet());
labelBullet.locationY = 1;
labelBullet.label.text = "y: 1";
```

but instead... well, look at the screenshot below.

Screenshot:
![image](https://user-images.githubusercontent.com/2334143/57403296-66d19880-71a7-11e9-9dec-19aacdf2c0ed.png)

Pen:
https://codepen.io/team/amcharts/pen/40c454008eadbaff2e6f0fdb415de68e

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
