### ISSUE TITLE
dateAxis.gridIntervals do not work (produce error)

### ISSUE THREAD

**Issue by bosiljkakostic** [amcharts/amcharts4#1284]
dateAxis.gridIntervals do not work (produce error)

example https://jsfiddle.net/bosiljkakostic1/65echf0n/206/

(with default grid intervals from amcharts4 docs about dateAxis class).
Deafult amCharts behaivor is to show element at the center choosen interval (not relative) exapme if a choose             ss.dateAxis.baseInterval = {
                count: 1,
                timeUnit: "month",            
            };  
The bullets will be positioned at the center of month, and in axis month will be showed, but I want that bullets be at the beginning of the cell at 1 day at month and at end of cell for last day of minth, and still to not see days in Axis labels. It was so in amCharts v3 and it have to be corrected. Even .gridIntervals  will not resolve problem, but I wanted to tray with grid intervals  { timeUnit: "day", count: 31 }, so maby only month will be shown, but  dateAxis.gridIntervals produce error **a.getIndex is not a function**

**Comment by martynasma** [comment]
`gridIntervals` is an object of type `List`, it's not an `Array`, whereas you are replacing it with an array, hence the chart not working.

Instead of replacing the whole of the `gridIntervals` use it's `setAll()` method:

```
dateAxis.gridIntervals.setAll(
[
 { timeUnit: "millisecond", count: 1 },
 { timeUnit: "millisecond", count: 5 },
 { timeUnit: "millisecond", count: 10 },
  // ...
 { timeUnit: "year", count: 50 },
 { timeUnit: "year", count: 100 }
]);
```

**Comment by bosiljkakostic** [comment]
Thanks, now it works fine
