### ISSUE TITLE
Different tooltips for different levels in ForceDirectedTree.

### ISSUE THREAD

**Issue by gauravneema** [amcharts/amcharts4#1285]
I am using ForceDirectedTree. How can I customize the tooltip differently for top-level node and child nodes.

I tried  `networkSeries.nodes.template.tooltipText = "{name} ({value})";` but it sets same tooltips format for all the nodes.

**Comment by martynasma** [comment]
This can only be implemented using adapters:

```
networkSeries.nodes.template.tooltipText = "{name}: {value}";
networkSeries.nodes.template.adapter.add("tooltipText", function(text, target) {
  if (target.dataItem) {
    switch(target.dataItem.level) {
      case 0:
        return "LEVEL 1: {name}";
      case 1:
        return "LEVEL 2: {name} ({value})";
    }
  }
  return text;
});
```

Example:
https://codepen.io/team/amcharts/pen/EzpggE?editors=0010
