### ISSUE TITLE
Colored Vertical Bands on LineSeries Chart?

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1287]
Similar to [this demo](https://www.amcharts.com/docs/v3/tutorials/colored-vertical-bands-stock-chart/), is it possible to add colored vertical bands on a V4 LineSeries chart?

**Comment by martynasma** [comment]
Yes:

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides
