### ISSUE TITLE
Propagating series changes to legend items not consistent

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#1288]
It seems that changes to the series don't propagate to the legends in as straightforward of a manner like other changes do. [For example](https://codepen.io/anon/pen/Xwmpzj?editors=0010), changing the series' `name` property doesn't update the legend marker name at all unless you call both `invalidate` and `invalidateRawData` methods on the legend itself:

```
  series1.name = 'TEST';
  
  chart.legend.invalidate();
  chart.legend.invalidateRawData();
```

Other alternatives ways to do this that don't seem natural:

Hardcoding series' labelText and calling `invalidate` on the legend:

```
  series1.legendSettings.labelText = 'TEST';
  chart.legend.invalidate();
```

Hardcoding the series' legendDataItem  label text:

```
  series1.legendDataItem.label.text = 'TEST';
```

**Comment by martynasma** [comment]
Propagating `name` to legend should work since 4.4.7.
