### ISSUE TITLE
Wordcloud non-stop label animation after initial render

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#1289]
In this [fiddle](https://jsfiddle.net/bL0qx5wk/) where a data array is used, the wordcloud plugin generates a wordcloud where the words are constantly animating and moving around after the initial render. This doesn't occur when converting the same input as a text value, though the multi-word labels don't translate well as a single string.

**Comment by zeroin** [comment]
This chart has a lot of words. And the font-size settings causes these words not to fit into available space. When words do not fit, they reduce the size by 10% and try to arrange them again. So it looks like it's an infinite loop, but it isn't. The only solution now would be to either reduce number of words or reduce maxFontSize/minFontSize to some smaller numbers for the labels to fit initially.

**Comment by xorspark** [comment]
Got it. Thanks!

**Comment by 3zzy** [comment]
@zeroin Its not possible to know how many words a word cloud would have unless there's a number we know it supports and beyond which it causes this issue. There should really be a method to pause the "loop" after x internal or something.
