### ISSUE TITLE
Hide stacked column label with an adapter

### ISSUE THREAD

**Issue by mkutlu** [amcharts/amcharts4#1290]
![amcharts](https://user-images.githubusercontent.com/9056500/57531751-d3cd6580-7342-11e9-97c3-2a1d1d1eaf82.png)

How can I hide column label if value under certain amount? I resolved pie chart problem like this with an adapter. But I could not find proper series attribute to comparise and hide. 
I am using label bullet like this:
                      ```
var labelBullet = series.bullets.push(new am4charts.LabelBullet());
                      labelBullet.label.text = "{valueY}";
                      labelBullet.locationY = 0.5;
```

**Comment by martynasma** [comment]
You can do something like this:

```
  labelBullet.label.adapter.add("text", function(text, target) {
    if (target.dataItem && target.dataItem.valueY == 0) {
      return "";
    }
    return text;
  })
```

**Comment by mkutlu** [comment]
Thank you @martynasma !
