### ISSUE TITLE
Zoom Reset On Data Replacement

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1299]
If a chart is zoomed and the data is replaced, the zoom is reset.  

See [this pen](https://codepen.io/anon/pen/NVRQwO).  Zoom in part way, then click the "Replace Chart Data To Show Overlap Issue" button.  The zoom is reset.  Note that this occurs even with the datavalidated event listener callback removed/commented.

Can this be disabled so that the zoom is not affected when replacing data?

**Comment by martynasma** [comment]
Check `keepSelection` setting:

https://www.amcharts.com/docs/v4/reference/dateaxis/#keepSelection_property

**Comment by bfailing** [comment]
That worked for me. Thanks.
