### ISSUE TITLE
"Class [...] is not loaded" error following simple JSON setup 

### ISSUE THREAD

**Issue by RobbertBreij** [amcharts/amcharts4#13]
Following the simple JSON based Pie Chart from here: https://www.amcharts.com/docs/v4/getting-started/basics/.

This message shows at the place where the chart should be:

```
Class [function e(){var e=t.call(this)||this;return e.className="PieChart",e.innerRadius=0,e.radius=Object(a.c)(80),e.align="none",e.valign="none",e.startAngle=-90,e.endAngle=270,e.applyTheme(),e}] is not loaded.
```

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.15](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.15)
