### ISSUE TITLE
How to determine if cursor is currently showing?

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1300]
Once a cursor is shown and the shown event has fired, is there a property that can be checked to see if the cursor is currently showing?

**Comment by martynasma** [comment]
Try this:

```
if (cursor.hidden || cursor.isHiding) {
  // nope, cursor is not there
}
```

**Comment by bfailing** [comment]
Both properties are always false.  See [this pen](https://codepen.io/anon/pen/zQogxb).  

With the console open, click the "Get Cursor Info In 2 Seconds" button and do not move the mouse (i.e. keep the cursor off the chart so that the cursor is not displayed).  Both are false, but at least one should be true.

**Comment by martynasma** [comment]
Gah, sorry my bad, it's `isHidden` (not `hidden`).

**Comment by bfailing** [comment]
That worked.  Thanks.
