### ISSUE TITLE
[Feature Request] Add downsampling support to handle very large real time streams 

### ISSUE THREAD

**Issue by armujahid** [amcharts/amcharts4#1302]
Currently chart rendering becomes too slow if we increase data points (lets say 100k+) because chart uses all points by default.  I think amcharts should support downsampling to map very large dataset to small significant dataset (lets say 1000 points) like https://janjakubnanista.github.io/downsample/

Because currently it seems impossible to use amcharts to plot multi axis real time timeseries (with lets say 1 minute interval) with historical data of one+ week.

This should also support scroll-and-zoom functionality so that more points can be used if chart is zoomed.

**Comment by martynasma** [comment]
The automatic grouping of data points is planned, but not yet supported.

However, for LineSeries, you may employ other curve simplification techniques, as described here:

https://www.amcharts.com/docs/v4/concepts/performance/#Simplifying_paths

**Comment by armujahid** [comment]
@martynasma thanks. I noticed performance improvement after using path simplification solution `am4core.options.minPolylineStep = 5;` but I also noticed that now chart is showing loading indicator whenever new data points are added in it. Previously chart was refreshing with new data without showing any loading indicator. I am not sure whats the root cause. I will dig down further tomorrow.
