### ISSUE TITLE
[Question] Alignment clustered pie's

### ISSUE THREAD

**Issue by puyt** [amcharts/amcharts4#1303]
Hi,

I'm trying to figure out why the pie isn't centered in the container using a customized version from the codepen demo.

In the codepen I've duplicated the last chart to make more pie charts and decreased the size of legend items. I also added a wrapping div to make it scrollable.

I'm also wondering if it's possible to right align the legend values while left aligning the legend names? 

Customized codepen example: https://codepen.io/anon/pen/EzNejz

As seen in the screenshot below the pie isn't centered in the parent element:
![image](https://user-images.githubusercontent.com/3668615/57700499-6c712780-765a-11e9-81f4-3867374b06cc.png)

Thanks in advance.

**Comment by juanpablogd** [comment]
+1

**Comment by martynasma** [comment]
It is centered, and it 's clear if you add a border for the chart:

![image](https://user-images.githubusercontent.com/1458520/58367963-6e56a880-7eee-11e9-80a6-8eb880a3111f.png)

It's just your legend does not go all the way to the left making the impression that pie is offset.

Try this:

```
chart.legend.itemContainers.template.width = am4core.percent(100);
chart.legend.valueLabels.template.width = am4core.percent(100);
```

**Comment by juanpablogd** [comment]
it works perfect, thanks

**Comment by puyt** [comment]
Great thanks ! Btw how did you add the border? I was looking for it when making the codepen :sweat_smile: 

> It is centered, and it 's clear if you add a border for the chart:
> 
> ![image](https://user-images.githubusercontent.com/1458520/58367963-6e56a880-7eee-11e9-80a6-8eb880a3111f.png)
> 
> It's just your legend does not go all the way to the left making the impression that pie is offset.
> 
> Try this:
> 
> ```
> chart.legend.itemContainers.template.width = am4core.percent(100);
> chart.legend.valueLabels.template.width = am4core.percent(100);
> ```

**Comment by martynasma** [comment]
I added a border on the `<div>` elements via CSS.

But you could add that via chart's SVG just as well:

```
chart.background.strokeOpacity = 1;
chart.background.stroke = am4core.color("#f00");
```

**Comment by puyt** [comment]
Thanks!
> But you could add that via chart's SVG just as well:
> 
> ```
> chart.background.strokeOpacity = 1;
> chart.background.stroke = am4core.color("#f00");
> ```
