### ISSUE TITLE
Adapter 'height' for FunnelSeries' doesn't work

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#1305]
Example:
https://codepen.io/dmsmaxim/pen/ZNBgVg?editors=1010

`series.sliceLinks.template.adapter.add('height', () => Math.random() * 30);` does nothing.

All I want to do is to change sliceLink's height relative to some value in a data item

**Comment by martynasma** [comment]
Try `pixelHeight` instead.

Although, with random value each like in your demo it might get a bit funky :)
