### ISSUE TITLE
labelBullet.tooltipColourSource usage question

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#1307]
See the codepen: https://codepen.io/npc42/pen/ZNLYpm?editors=0010

I'd like to use a column tooltip with bullet labels, but can't find a way to inherit column colour for the label tooltip itself. labelBullet.tooltipColorSource = series.columns.template seems to have no effect (check by hovering column, and then the number label).

PS If I don't set labelBullet.tooltipText, then the tooltip hides when I hover the label itself. Maybe there's a way to set no hover events (or pointer pass through) for the bulletLabel instead? Or just specify tooltip fill colour directly.

**Comment by martynasma** [comment]
I suppose it's easier to just disable all interactivity for the label bullet:

```
labelBullet.interactionsEnabled = false;
```

**Comment by NPC** [comment]
@martynasma this is exactly what I needed, thanks! Of course, I am still curious about using tooltipColourSource, but my immediate problem is solved.

**Comment by martynasma** [comment]
`tooltipColorSource` is not set for bullets, and its not inherited. It's only set for series, hence it not working on bullet's label.

Not sure if this helps in any way tho :)
