### ISSUE TITLE
Long text wrapping from bullet tooltip only works the first time

### ISSUE THREAD

**Issue by davidliang2008** [amcharts/amcharts4#1308]
When the text on the bullet tooltip is too long, I want it to be wrapped. I thought I can get the `tooltip` off the `bullet` after setting its `tooltipText` but the `tooltip` has not been instantiated until you mouse over the bullets. Hence I had to use `adapter` on the bullet (as I couldn't find another way) to modify the `tooltip` there:

```javascript
var bullet = series.bullets.push(new am4charts.CircleBullet());
bullet.tooltipText = "[bold]Comments[/]: {comments}";
bullet.adapter.add("tooltipText", (text, target) => {
    target.tooltip.label.wrap = true;
    return text;
});
```

**demo:** https://jsfiddle.net/davidliang2008/5av8whb0/69/

The problem is: it only worked for the first time. The background seems to be way off from the text after the first time.

### 1st time hover

![image](https://user-images.githubusercontent.com/1124420/57741473-d77a2880-7671-11e9-85f6-a594722d1571.png)

### next time hover

![image](https://user-images.githubusercontent.com/1124420/57741551-2b850d00-7672-11e9-82d2-5371db6dcd8e.png)

**Comment by martynasma** [comment]
The issue is that you are setting label's properties in the adapter, which causes it to invalidate and redraw, which in turn throws off size calculation for the tooltip background.

Set it once:

```
series.tooltip.label.wrap = true;
bullet.adapter.add("tooltipText", (text, target) => {
  //target.tooltip.label.wrap = true;
  return text;
});
```

This will fix the issue.

**Comment by davidliang2008** [comment]
Wow amazing! It always confuses me though where I need to / can get the reference of the tooltip. Sometimes it's off the series, `series.tooltip`. In fact, the reason why I used adapter here is that I thought since I set the tooltipText on the bullet, I might have to configure the tooltip object there. And I couldn't do `bullet.tooltip.` because it's always `null`.

Anyways thanks a lot!
