### ISSUE TITLE
ForceDirectedSeries: update linkWith without redrawing entire chart

### ISSUE THREAD

**Issue by braco** [amcharts/amcharts4#1310]
Is there any way to update the linkWith property in a graph without redrawing the whole chart?

Changing the deep property isn't detected:
```
this.series.data[0].children[i].linkWith = newData
```

Which I believe only leaves invalidateData() as an option, which redraws the whole chart.

I'm trying to render a complex graph with lots of links between nodes, and that data is loaded asynchronously. The trouble is that the graph will spasm/re-render constantly, even with minor link additions.

**Comment by martynasma** [comment]
Currently there's no way to add additional links without revalidating whole data.

However, it would make a nice and useful feature. We're going to explore if we can implement that.

Will keep you posted.

**Comment by martynasma** [comment]
Implemented in [4.4.8](https://github.com/amcharts/amcharts4/releases/tag/4.4.8).

## [4.4.8] - 2019-05-23

### Added

- `linkWithStrength` added to `ForceDirectedSeries`.
- `linkWith(node, strength)` method added to `ForceDirectedNode`. Allows adding links without revalidating whole data.
- `unlinkWith(node)` method added to `ForceDirectedNode`.
- `expandAll` property added to `ForceDirectedNode` (default: `true`). If set to `false`, only a single level of children will be expanded on click/tap.

### Fixed
- Links created using `linkWith` data field were not using any strength setting, affecting the layout.
- Some problems with `maxLevels` on `ForceDirectedSeries` solved.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
