### ISSUE TITLE
tooltip is not working with pieSeries

### ISSUE THREAD

**Issue by juanpablogd** [amcharts/amcharts4#1311]
The Tooltip is black. See my code in following url

http://jsfiddle.net/u384yknz/

**Comment by martynasma** [comment]
This is because of the `toolipText` set directly on series. It tries to show a tooltip on whole of the series, and since it does not have any dataItem comes out as black.

If you want to chance the tooltip contents, you need to set it on slice template:

```
pieSeries.slices.template.tooltipText = "{category}";
```

**Comment by juanpablogd** [comment]
it works perfect, thanks
