### ISSUE TITLE
TreeMap: min size for under-weight nodes

### ISSUE THREAD

**Issue by Rapster** [amcharts/amcharts4#1313]
Using TreeMap, one of my node has a very small weight, I can barely see it and even worse, I can't click on it... Is there a way to set a minimal size for those nodes with a small weight compared to the others?

I tried minWidth/minHeight on series.columns.template but no success... Here an example https://codepen.io/rapster/pen/MdpPxw with 

```js
var data = {
    "Ford": { "C-Max": 18390, "Edge": 10 }
}
```

Original post: https://stackoverflow.com/questions/56113899/treemap-min-size-for-under-weight-nodes

**Comment by martynasma** [comment]
There's currently no way to set minimum dimensions for the nodes.

We'll need to implement that, tho.

I'm setting this up as an enhancement request. Thanks!

**Comment by martynasma** [comment]
OK, turns out this feature would require quite an overhaul of the layout algos, which we're not prepared to do now.

We might come back to this in the future, but for now we have to shelve it :(

**Comment by Rapster** [comment]
Thank you for letting me know

**Comment by hassankhan** [comment]
Hi @martynasma, is there any workaround for the meantime? Not entirely sure how to approach it...

**Comment by martynasma** [comment]
> Hi @martynasma, is there any workaround for the meantime? Not entirely sure how to approach it...

No, I'm afraid.

**Comment by qasimalbaqali** [comment]
I wish this would be reconsidered, as we have many use cases that require such feature :(

**Comment by aryan-dixit-26** [comment]
@martynasma , do we have a solution for this in amcharts5?
