### ISSUE TITLE
Hover keeps alive

### ISSUE THREAD

**Issue by lmarre** [amcharts/amcharts4#1316]
When clicked a polygon in a map (simple-map-chart) it change as active, changing color, then it changes to default if other is clicked, which is right,  but if hover on the first one it take the active color again, so we have two colored as active. It is not right. I mean, the default condition does not put back all features to a polygon which was active before, its hover as active remains.
![Captura de pantalla 2019-05-19 01 52 01](https://user-images.githubusercontent.com/49735516/57978310-c9f9d100-79d8-11e9-88f6-284f9acfa428.png)

**Comment by zeroin** [comment]
OK, so instead of setting defaultState to the currentActive polygon, you should set currentActive.isActive = false; This will return default state and also will solve the problem. We do not set isActive = false when setting defaultState for some internal reasons.

**Comment by lmarre** [comment]
Hi, I solved it, The Active condition should be changed to false manually, as shown here

// Set events to apply "active" state to clicked polygons
var currentActive;
polygonTemplate.events.on("hit", function (event) {
	// if we have some country selected, set default state to it
	if (currentActive) {
		currentActive.setState("default");
		currentActive.isActive =false;
	}

![Captura de pantalla 2019-05-20 11 26 23](https://user-images.githubusercontent.com/49735516/58033281-33b9ce00-7af2-11e9-84b2-3770711490a6.png)

**Comment by lmarre** [comment]
> OK, so instead of setting defaultState to the currentActive polygon, you should set `currentActive.isActive = false;` This will return default state and also will solve the problem. We do not set `isActive = false` when setting `defaultState` for some internal reasons.

Thanks Zeroin, this helped.

**Comment by lmarre** [comment]
Thanks Zeroin, It solved.
    On Monday, May 20, 2019, 9:31:47 AM GMT-4, zeroin <notifications@github.com> wrote:  
 
 
OK, so instead of setting defaultState to the currentActive polygon, you should set currentActive.isActive = false; This will return default state and also will solve the problem. We do not set isActive = false when setting defaultState for some internal reasons.
