### ISSUE TITLE
Loading Indicator is triggered twice on rendering data if Xscrollbar is used

### ISSUE THREAD

**Issue by kimlukas3** [amcharts/amcharts4#1317]
Example: https://codepen.io/kimlukas3/pen/wbPdjW

How to reproduce it:
Add a few series with around 2000-6000 points to get an loading indicator, and a Xscrollbar to a Line Chart.
If the chart loads it will trigger twice a Loading Indicator.

**Comment by zeroin** [comment]
This is by design. Scrollbar with series has just another XYSerialChart inside, so the preloader is also shown while it processes data. 
To disable this preloader, you can do this:

```
scrollbarX.scrollbarChart.preloader = new am4core.Preloader();
scrollbarX.scrollbarChart.preloader.disabled = true;
```

Although the chart will be quite unresponsive while the data is parsed.
