### ISSUE TITLE
Differentiate column labels : making each category.renderer.labels clickable

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#1318]
On a stacked columns chart i'd like to make the label of each columns a link that can redirect to the page dedicated to the mentioned category. I did something like this :
``` Javascript
var chart = am4core.create("chartdiv", am4charts.XYChart);

chart.data = [
	{
		'Category' : 'Column label 1',
		'Value 1' : 1,
		'Value 2' : 2,
		'Value 3' : 3,
	},{
		'Category' : 'Column label 2',
		'Value 1' : 1,
		'Value 2' : 2,
		'Value 3' : 3,
	}
];

var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "Category";

var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.renderer.labels.template.disabled = true;

function createSeries(field) {
    var series = chart.series.push(new am4charts.ColumnSeries());
    series.dataFields.valueY = field;
    series.dataFields.categoryX = "Category";
    series.stacked = true;

    return series;
}

// I looped on the values
series = createSeries('Value 1')
// etc...
```
To add an url to the columns labels i tried to execute the following code in a loop to iterate on the correct value :
``` Javascript
categoryAxis.renderer.labels.template.url = "{url.i.want}"
```
But of course, all it does is overwriting the url mutliple times and give the same for all labels. Is the a way to access the labels individually?

**Comment by Segolene-Albouy** [comment]
The solution I came up is to configure the label in my category field in html and then add : ` categoryAxis.renderer.labels.template.propertyFields.html = "Category";`

**Comment by martynasma** [comment]
Probably easier would be to configure `url` property field for labels, e.g.:

```
label.propertyFields.url = "url";
```

Now labels for that series will be hyperlinked to whatever you have in "url" property for that data point.

**Comment by Segolene-Albouy** [comment]
Thanks, that works great too!
