### ISSUE TITLE
Safari - Whole Map blinks during fill updates

### ISSUE THREAD

**Issue by git-ashish** [amcharts/amcharts4#1322]
In Safari, when making updates to "fill" of a MapPolygonSeries data, the whole map blinks.

Here is a [codepen](https://codepen.io/git-ashish/pen/OYzbLq?editors=0010) which can be run on Safari to see the same.

How can this be avoided?

Thanks!

**Comment by bfailing** [comment]
Your pen doesn't show the issue (based on the comments in your code):
````
  polygonSeries.data = JSON.parse(JSON.stringify(data));
  
  //polygonTemplate.propertyFields.fill = "fill";
    
  polygonSeries.invalidateRawData();
  
  // This works but the map flashes/blinks on Safari
  //polygonSeries.addData(polygonSeries.data, polygonSeries.data.length);
````
It would be helpful if you linked to pen showing the issue.

**Comment by git-ashish** [comment]
@bfailing Thanks for your comment. Have you tried running that codepen on Safari? Here is how it looks on Safari on 

![image](https://user-images.githubusercontent.com/2697421/58304039-53156b80-7e10-11e9-86ac-8f1d204439dc.png)

![amcharts4-maps-flash](https://user-images.githubusercontent.com/2697421/58304003-28c3ae00-7e10-11e9-9042-bbe77901aefb.gif)

The codepen shows two techniques to update the dataset - 

1. Using invalidateRawData()
2. Using addData()

Both are resulting in the map flashing on updates.

Please let me know if you need more information.

Thanks.

**Comment by git-ashish** [comment]
@martynasma Any thoughts please? Thanks.

**Comment by martynasma** [comment]
Found this old issue. Seems like it's not happening anymore, so closing :)
