### ISSUE TITLE
Clustered bar chart with gaps in data

### ISSUE THREAD

**Issue by Lokzor** [amcharts/amcharts4#1323]
Hello,

The main concept of what I'm trying to do is simple. I have a lot of data with similar categories and I'm trying to group them using a clustered bar chart.

However, not all of my data share the same categories, so we have a "gap", so to speak. For example, let's say we have these 4 entries:

`
{
        "account_id": "4994",
        "measure": "258444",
        "Year": "1996"
      },

      {
        "account_id": "2872",
        "measure": "268320",
        "Year": "1997"
      },

      {
        "account_id": "3664",
        "measure": "271584.0000",
        "Year": "1997"
      },

      {
        "account_id": "3293",
        "measure": "276084.0000",
        "Year": "1998"
      }
`

So as you can see, the same account_id does not exist for all of the Years
I've changed the form of the data so it follows the structure of this example https://www.amcharts.com/demos/clustered-bar-chart/

So now I have this structure:

`
[{
Year:1996,
4994:258444
},{
Year:1997,
2872:268320,
3664:271584
},{
Year:1998,
3293:276084
}]
`

The problem is that I get these big gaps between the grouped bars, which I understand are made because the "missing" common categories are "skipped" thus creating empty bars

![gaps](https://user-images.githubusercontent.com/37675740/58178091-2fd2ab00-7cae-11e9-98cf-cd6b6d535a0e.PNG)

Is there any workaround for this? How can I close the distance between the groups and make it more like this:

![gaps2](https://user-images.githubusercontent.com/37675740/58178376-c2734a00-7cae-11e9-9f4d-cda8089bd666.PNG)

One final note, I also tried this example https://www.amcharts.com/demos/partitioned-bar-chart/
but when there are duplicate entries per category for example:

`
{
        "account_id": "3000",
        "measure": "258444",
        "Year": "1996"
      },

      {
        "account_id": "3000",
        "measure": "268320",
        "Year": "1997"
      },

      {
        "account_id": "3664",
        "measure": "271584.0000",
        "Year": "1997"
      },

      {
        "account_id": "3000",
        "measure": "276084.0000",
        "Year": "1998"
      }
`

It behaves erratically. Does it work only when one of the categories' key, is unique?

Is there any way for either of these examples to work with the structure of my data?

If I did not explain something properly, please commend so I can explain in greater detail

Thank you in advance

**Comment by martynasma** [comment]
Yes, category keys need to be unique, because otherwise it's the same category.

I suggest having unique keys with some prefixes, then stripping them out using adapters.

https://www.amcharts.com/docs/v4/tutorials/handling-repeating-categories-on-category-axis/

**Comment by Lokzor** [comment]
Thank you, this indeed solves the problem
