### ISSUE TITLE
html container not found  <div id="chartdiv" ... />

### ISSUE THREAD

**Issue by GhassanGuessous** [amcharts/amcharts4#1324]
Hello,

I have attempted to use Amcharts  my Angular  projects. But I am unable to succeed. It does show error (html container not found), but i have a <div id="chartdiv" ... /> in my html, and in the .ts file a call am4core.create("chartdiv", am4charts.XYChart)

Thanks in advance!

**Comment by martynasma** [comment]
Perhaps your `<div>` element is created before your chart code runs?

Try wrapping chart code into:

```
am4core.ready(function() {

  // chart code

});
```

**Comment by GhassanGuessous** [comment]
it did work, thank you !

**Comment by GhassanGuessous** [comment]
thanks for your help, but apparently .ready does not solve the problem...right now i'm just setting timeout to 1000ms as trick.

**Comment by Aterops** [comment]
I'm not very familiar with Angular, but as it is working with a virtual DOM, the element may not be available when you are calling the create chart function. There are library specific ways to interact with the real DOM. Are you using the method described here? [https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/](url)

**Comment by GhassanGuessous** [comment]
thanks a lot.

**Comment by jediManJS** [comment]
Hello. I got the same issue and found more elegant, than _setTimeout_ function, way.
In the template, I added _templateVariable_ to div: 
`<div id="bar-lines-chart" style="width: 100%; height: 200px" #chartElement></div>`
In the component, I made next:
`@ViewChild('chartElement') chartElement: ElementRef<HTMLElement>;`
and in _am4core.create_ function:
`const chart = am4core.create(this.chartElement.nativeElement, am4charts.XYChart);`
Working well.

**Comment by GhassanGuessous** [comment]
thank you @jediManJs

**Comment by VictorChatterji** [comment]
@jediManJS thanks man ! it worked like charm

**Comment by nikilkumar9** [comment]
@jediManJS Finally worked, thanks!

**Comment by samheihey** [comment]
You may simply setup the chart after view init

**Comment by ChamithMendis** [comment]
@jediManJS thankyou!

**Comment by YuriLukashenko** [comment]
I got the same issue and noticed that you should implement your component from OnInit and paste your chart code into ngOnInit(). Then <div id="chartdiv"></div> will work.
