### ISSUE TITLE
HeatRules not being applied to a bubble chart through JSON config

### ISSUE THREAD

**Issue by XactaAndy** [amcharts/amcharts4#1327]
I can't get my heatRules to apply to a bubble chart I am trying to make.

https://codepen.io/XactaAndy/pen/RmMgNv

I believe I have everything set up correctly. Does anyone have any ideas?

**Comment by martynasma** [comment]
Two things:

1) Your target refers to all of the bullets list, we need to refer to specific bullet.
2) `min` and `max` need to be numbers, whereas you have them as strings.

The following will work:

```
        {
          "target": "bullets.0.circle",
          "property": "radius",
          "min": 2,
          "max": 40,
          "dataField": "value"
        }
```

**Comment by XactaAndy** [comment]
Brilliant, many thanks!
