### ISSUE TITLE
RadarChart Bullet click event

### ISSUE THREAD

**Issue by mkutlu** [amcharts/amcharts4#1328]
I did click event for RadarChart. But my hit event attempts was not succesful on bullets itself.  I dont want click event outside of bullet areas. How can I perform hit event for bullets?  For below example I want to get related data's id attribute.
```
top10graph.events.on("hit", function (ev) {
                        var url = '../customer/list.htm?id=' + e.item.dataContext.id;
                        url = addFilterToUrl(url);
                         window.open(url,'_blank');
                    });
```
![Screenshot_6](https://user-images.githubusercontent.com/9056500/58327416-3ab94700-7e38-11e9-9107-765043fc2a04.png)
![screen](https://user-images.githubusercontent.com/9056500/58327566-9aafed80-7e38-11e9-8131-4c0608fd6f3b.png)

**Comment by martynasma** [comment]
If you need to catch a click event on the bullet you need to set it on the bullet itself:

```
bullet.events.on("hit", function(ev) {
  // ...
});
```

Setting it on series only affects the line element.

**Comment by mkutlu** [comment]
Thank you @martynasma!
