### ISSUE TITLE
Problem with animated fillOpacity

### ISSUE THREAD

**Issue by stla** [amcharts/amcharts4#1329]
Hello, 

 Please take a look at this "pen": [draggable column chart](https://codepen.io/team/amcharts/pen/OQePOB).

The `fillOpacity` property of the columns should be animated on hover:
```
// column template
var columnTemplate = series.columns.template;
columnTemplate.fillOpacity = 0.8;
// hover state
var columnHoverState = columnTemplate.column.states.create("hover");
columnHoverState.properties.fillOpacity = 1;
```

That doesn't work. 

And if you set `columnHoverState.properties.fillOpacity` to a number less than `columnTemplate.fillOpacity`, for example `columnHoverState.properties.fillOpacity = 0.4`, then the opacity goes as expected to `0.4` when you hover the column, but then it remains at `0.4` when you unhover the column.

**Comment by martynasma** [comment]
There's an issue with that demo:

```
columnTemplate.fillOpacity = 0.8;
```

Should be:

```
columnTemplate.column.fillOpacity = 0.8;
```

Fixed the demo. Thanks for the heads up!

**Comment by stla** [comment]
Indeed, that works. Thank you!
