### ISSUE TITLE
Refresh map fills with new heat legend

### ISSUE THREAD

**Issue by jorseijo** [amcharts/amcharts4#1332]
Hello,
I have two displays in my map of California: temperature and rainfall. I use radio buttons to switch from one to the other.
When I switch the display, I update the heatlegend with new colors and new max and min values (see the code below). Although the heat legend gets properly updated, the color fills in the map are not. Looks like they need to be reset. I tried to reinitialize the map but that doesnt work either. Any ideas?
Thank you.
Jorge

```
polygonSeries.heatRules.clear();
polygonSeries.heatRules.push({
  property: "fill",
  target: polygonSeries.mapPolygons.template,
  min: am4core.color("#99ccff"),
  max: am4core.color("#ff9999")
});

heatLegend.minValue = 0;
heatLegend.maxValue = 105;
```

**Comment by martynasma** [comment]
You might also need to revalidate data on the series:

```
polygonSeries.invalidateData();
```

**Comment by jorseijo** [comment]
Thanks. I tried that but still no success. I dropped this for the moment.
