### ISSUE TITLE
xyChart Heatmap conditional formatting adapters

### ISSUE THREAD

**Issue by alexwindelberg** [amcharts/amcharts4#1334]
Hello as the title suggests I'm currently working on a xyChart heatmap but I'm having some difficulty. My chart is very similar to the chart below but I need to use 3 colors green, yellow, red for 0 - 100%. I found that using adapters I can get this done but I'm having difficulty with implementing one as I keep getting "template is not defined" I may be doing this incorrectly. I wanted to ask if I could get an example of how I could implement conditional formatting on a xy heatmap?

https://codepen.io/team/amcharts/pen/BrOeRz

**Comment by martynasma** [comment]
Heatmaps won't work with 3 colors. Like you said you have to use adapters for that.

E.g.:

```
columnTemplate.column.adapter.add("fill", function(fill, target) {
  if (target.dataItem) {
    if (target.dataItem.value >= 6000) {
      return am4core.color("green")
    }
    else if (target.dataItem.value >= 4000) {
      return am4core.color("yellow")
    }
    else {
      return am4core.color("red");
    }
  }
  return fill;
});
```

Here's an example:
https://codepen.io/team/amcharts/pen/JqBYEN

**Comment by martynasma** [comment]
And a bit of a commentary here:
https://www.amcharts.com/docs/v4/tutorials/multi-color-xy-heatmap/

**Comment by alexwindelberg** [comment]
Thank you this was exactly what I was attempting to do
