### ISSUE TITLE
Map wrap-around when panning

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#1335]
Hello,

Is there a way to enable map horizontal wrapping (countries that disappear from the right edge show up on the left, and vice versa) without panBehavior="rotateLong"?

My issue with "rotateLong" is that it doesn't allow vertical panning even when zoomed in, which is inconvenient and simply impractical, I can't offer this to our users. I tried "rotateLongLat", it makes the map go absolutely nuts (at least in Miller projection — looks like it's intended for spheric displays), so I haven't found a way to enable vertical panning with horizontal wrap-around. That could be a possible solution to my problem.

Any help with this would be much appreciated.

PS In the meantime, is it valid to use homeGeoPoint and deltaLatitude at the same time? As I understood, homeGeoPoint pans the map to specified coordinated, while deltaLatitude ensures country polygons are drawn “around” this position (which wouldn't be needed with wrap-around).

**Comment by martynasma** [comment]
Indeed. There should be a way to pan up/down when zoomed in.

We'll see what we can do.

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.

**Comment by GideonMax** [comment]
@martynasma the problem does not seem to have been fixed, "rotateLong" does not allow for moving up and there still is no good way of making the map wrap.
