### ISSUE TITLE
Sankey Graph: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by DylanAlloy** [amcharts/amcharts4#1336]
Hi!

I ran into the error while building a three-tier sankey visualization with 92 rows of data, three columns/datapoints for each row. Not a lot, all things considered?

Wondering if there should maybe be two JSON objects for throwing data into the graph instead of one? 

Not sure if my code would help. Here is my data object:

`[{"from":"CBIS","to":"BILLING","value":83205},{"from":"BILLING","to":"BILLING QUESTION & CONCERNS","value":83205},{"from":"CIM","to":"BILLING","value":58290},{"from":"BILLING","to":"BILLING QUESTION & CONCERNS","value":58290},{"from":"CMSE","to":"BILLING","value":142245},{"from":"BILLING","to":"BILLING QUESTION & CONCERNS","value":142245},{"from":"CMSW","to":"BILLING","value":36570},{"from":"BILLING","to":"BILLING QUESTION & CONCERNS","value":36570},{"from":"CSS","to":"BILLING","value":22875},{"from":"BILLING","to":"BILLING QUESTION & CONCERNS","value":22875},{"from":"CBIS","to":"DNP","value":516},{"from":"DNP","to":"DNP COMPLETE","value":516},{"from":"CIM","to":"DNP","value":56},{"from":"DNP","to":"DNP COMPLETE","value":56},{"from":"CMSE","to":"DNP","value":168},{"from":"DNP","to":"DNP COMPLETE","value":168},{"from":"CMSW","to":"DNP","value":56},{"from":"DNP","to":"DNP COMPLETE","value":56},{"from":"CSS","to":"DNP","value":4408},{"from":"DNP","to":"DNP COMPLETE","value":4408},{"from":"CBIS","to":"NO INTENT","value":106},{"from":"NO INTENT","to":"NO INTENT","value":106},{"from":"CBIS","to":"OUTAGE","value":5},{"from":"OUTAGE","to":"ACTIVE OUTAGE","value":5},{"from":"CBIS","to":"OUTAGE","value":15},{"from":"OUTAGE","to":"ASSUMED OUTAGE","value":15},{"from":"CBIS","to":"OUTAGE","value":45},{"from":"OUTAGE","to":"NO INTENT","value":45},{"from":"CBIS","to":"OUTAGE","value":6420},{"from":"OUTAGE","to":"RECENTLY RESTORED OUTAGE","value":6420},{"from":"CIM","to":"OUTAGE","value":645},{"from":"OUTAGE","to":"RECENTLY RESTORED OUTAGE","value":645},{"from":"CMSE","to":"OUTAGE","value":120},{"from":"OUTAGE","to":"ACTIVE OUTAGE","value":120},{"from":"CMSE","to":"OUTAGE","value":65},{"from":"OUTAGE","to":"ASSUMED OUTAGE","value":65},{"from":"CMSE","to":"OUTAGE","value":130},{"from":"OUTAGE","to":"FREQUENT CALLER OUTAGE","value":130},{"from":"CMSE","to":"OUTAGE","value":10},{"from":"OUTAGE","to":"NO INTENT","value":10},{"from":"CMSE","to":"OUTAGE","value":145},{"from":"OUTAGE","to":"RECENTLY RESTORED OUTAGE","value":145},{"from":"CMSW","to":"OUTAGE","value":50},{"from":"OUTAGE","to":"ACTIVE OUTAGE","value":50},{"from":"CMSW","to":"OUTAGE","value":90},{"from":"OUTAGE","to":"ASSUMED OUTAGE","value":90},{"from":"CMSW","to":"OUTAGE","value":20},{"from":"OUTAGE","to":"NO INTENT","value":20},{"from":"CMSW","to":"OUTAGE","value":65},{"from":"OUTAGE","to":"RECENTLY RESTORED OUTAGE","value":65},{"from":"CSS","to":"OUTAGE","value":10},{"from":"OUTAGE","to":"ASSUMED OUTAGE","value":10},{"from":"CSS","to":"OUTAGE","value":915},{"from":"OUTAGE","to":"RECENTLY RESTORED OUTAGE","value":915},{"from":"CBIS","to":"PAYMENT","value":11445},{"from":"PAYMENT","to":"DELINQUENT PAYMENT","value":11445},{"from":"CBIS","to":"PAYMENT","value":9275},{"from":"PAYMENT","to":"REGULAR PAYMENT","value":9275},{"from":"CIM","to":"PAYMENT","value":357},{"from":"PAYMENT","to":"DELINQUENT PAYMENT","value":357},{"from":"CIM","to":"PAYMENT","value":1946},{"from":"PAYMENT","to":"REGULAR PAYMENT","value":1946},{"from":"CMSE","to":"PAYMENT","value":7},{"from":"PAYMENT","to":"DELINQUENT PAYMENT","value":7},{"from":"CMSE","to":"PAYMENT","value":35},{"from":"PAYMENT","to":"REGULAR PAYMENT","value":35},{"from":"CMSW","to":"PAYMENT","value":21},{"from":"PAYMENT","to":"REGULAR PAYMENT","value":21},{"from":"CSS","to":"PAYMENT","value":6090},{"from":"PAYMENT","to":"DELINQUENT PAYMENT","value":6090},{"from":"CSS","to":"PAYMENT","value":10654},{"from":"PAYMENT","to":"REGULAR PAYMENT","value":10654},{"from":"CBIS","to":"SERVICE","value":5},{"from":"SERVICE","to":"STOP SERVICE","value":5},{"from":"CIM","to":"SERVICE","value":5},{"from":"SERVICE","to":"FREQUENT CALLER SERVICE","value":5},{"from":"CSS","to":"SERVICE","value":30},{"from":"SERVICE","to":"FREQUENT CALLER SERVICE","value":30},{"from":"CBIS","to":"PREDICTED ACCOUNT","value":130},{"from":"PREDICTED ACCOUNT","to":"CALL VOLUME","value":130},{"from":"CBIS","to":"PREDICTED ACCOUNT","value":250},{"from":"PREDICTED ACCOUNT","to":"PRI/ALT PHONE","value":250},{"from":"CIM","to":"PREDICTED ACCOUNT","value":10},{"from":"PREDICTED ACCOUNT","to":"CALL VOLUME","value":10},{"from":"CIM","to":"PREDICTED ACCOUNT","value":10},{"from":"PREDICTED ACCOUNT","to":"PRI/ALT PHONE","value":10},{"from":"CMSE","to":"PREDICTED ACCOUNT","value":147},{"from":"PREDICTED ACCOUNT","to":"CALL VOLUME","value":147},{"from":"CMSE","to":"PREDICTED ACCOUNT","value":30},{"from":"PREDICTED ACCOUNT","to":"PRI/ALT PHONE","value":30},{"from":"CSS","to":"PREDICTED ACCOUNT","value":60},{"from":"PREDICTED ACCOUNT","to":"CALL VOLUME","value":60}]`

**Comment by martynasma** [comment]
You have at least one link pointing to itself:

```
{ "from": "NO INTENT", "to": "NO INTENT", "value": 106 },
```

This gets the chart into whack :)

**Comment by DylanAlloy** [comment]
Oh! Yeah, that makes sense. I do a quick check for mutual to->from and delete them from the JSON I'm passing and it works. Thank you so much and very good eye considering this data probably means nothing to you!

**Comment by martynasma** [comment]
Ha, thanks. Not the first time this issue surfaces ;)

**Comment by bittu35** [comment]
Is there any limit with the JSON data provided? I have removed these kind of duplicate scenarios, but still I am getting this Maximum call stack size exceeded error.

**Comment by yarogon** [comment]
@martynasma I have the same situation:

`{ "from": "A", "to": "B", "value": 1 },`
`{ "from": "B", "to": "C", "value": 1 },`
`{ "from": "C", "to": "A", "value": 1 },`

This data execute looping and Amchart throws an error: Maximum call stack size exceeded error.
