### ISSUE TITLE
Exporting API It's taking too long

### ISSUE THREAD

**Issue by bjcCin** [amcharts/amcharts4#1339]
When I call exporting API to get image data like below,

```javascript
async export() {
    let options = this.chart.exporting.getFormatOptions("jpg");
    options.quality = 0;
    await this.chart.exporting.getImage('jpg', options);
  }
```

its took so so longer time and shows message "Export operation took longer than expected. Something might have gone wrong."

![Captura de Tela 2019-05-28 às 15 57 26](https://user-images.githubusercontent.com/15972641/58504744-b3cedc00-8161-11e9-95af-2336c071cba9.png)

I need to export dozens of graphs and these operations is crashing my browser. Only export SVG is working well. Export data by export menu is working well too.

I'm using amcharts version 4.1.6 with Angular 7.

**Comment by martynasma** [comment]
Are you sure you are using 6.4.1? We're currently at only 4.4.9 ;)

That said, does it export despite the message eventually, or it fails completely?

**Comment by bjcCin** [comment]
> Are you sure you are using 6.4.1? We're currently at only 4.4.9 ;)
> 
> That said, does it export despite the message eventually, or it fails completely?

Sorry, I'm using 4.1.6 amChart version. Yes, although it takes more than a minute per chart, I can export it.

**Comment by martynasma** [comment]
How about current version? 4.1.6 is months old.
