### ISSUE TITLE
Space instead of comma in Formatting Numbers

### ISSUE THREAD

**Issue by vitalytalyzin** [amcharts/amcharts4#1344]
Hello.
I have a tree chart and I want to format bullets with spaces (no commas).
For example 15,000 => 15 000
I tried to do this in different ways but nothing helped. 

```
"numberFormatter": {
    "precision": -1,
    "decimalSeparator": ",",
    "thousandsSeparator": " "
  },
```

`"text": "{value.formatNumber('# ###')}",`

I've tried locale 'ru-RU' as well and it didn't help.
Is there some option to do this?
Here is my chart https://codepen.io/vitalytalyzin/pen/gyRGJP?editors=1010

**Comment by martynasma** [comment]
Separators are not settings of numberFormatter but rather locale.

Take a look here:
https://www.amcharts.com/docs/v4/concepts/locales/#Numbers
