### ISSUE TITLE
AmCharts city map suport

### ISSUE THREAD

**Issue by lorduakiti** [amcharts/amcharts4#1346]
The AmCharts have any suport or development for citys map view?

I only find the [countrys ](https://www.amcharts.com/visited_countries/) and [states ](https://www.amcharts.com/visited_states/) map levels.

**Comment by martynasma** [comment]
We don't have any plans on implementing city-level maps. Sorry.

You can take a stab at creating your own, if you can find source data:

https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/

**Comment by lorduakiti** [comment]
@martynasma  thanks for help support, I finaly concluded the implamantation city-level references for states of Brazil.

Link code:
https://codepen.io/lorduakiti/pen/gVmarz
