### ISSUE TITLE
ValuesAxis doesn't disappear when all legend items are unselected

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1347]
Hey amcharts 4 team,
I would like to know why 2 charts from different versions(4 & 3) act differently.
I have the following example:
[amcharts3 demo](https://www.amcharts.com/demos-v3/stacked-clustered-column-chart-v3/)
You can see clearly that when I unselect all legend items, the value axis instance disappear as expected!
In the following example:
[amcharts4 demo](https://www.amcharts.com/demos/stacked-clustered-column-chart/)
You can see clearly that when I unselect all legend items, the value axis instance stayed not as expected!
Why the original behavior from version 3 didn't preserve and pass to version 4 as expected!
Is it a bug ? or desired behavior please clarify asap.

**Comment by BrkCoder** [comment]
@martynasma hey any help from official team is welcome, I still don't know if this is a bug or desired behavior

**Comment by martynasma** [comment]
@BrkCoder I put together a small example which mimics the behavior of V3:

https://codepen.io/team/amcharts/pen/KLYrww?editors=0010

@georgybu If you think it's a bug, please post it as a separate issue.

**Comment by BrkCoder** [comment]
> @BrkCoder I put together a small example which mimics the behavior of V3:
> 
> https://codepen.io/team/amcharts/pen/KLYrww?editors=0010
> 
> @georgybu If you think it's a bug, please post it as a separate issue.

thanks for the quick reply!

**Comment by martynasma** [comment]
Posted some commentary about it here:
https://www.amcharts.com/docs/v4/tutorials/auto-hide-value-axes/
