### ISSUE TITLE
labelBullet does not completely disappear after hiding a treemap item

### ISSUE THREAD

**Issue by agentfox** [amcharts/amcharts4#1349]
![bulletLabel](https://user-images.githubusercontent.com/23256873/58850270-00616c80-86b8-11e9-9d79-85f0bd085e3c.png)
[ttps://codepen.io/team/amcharts/pen/zLVKLm](url)

**Comment by zeroin** [comment]
You should set `level2_bullet.label.hideOversized = true;` for labels to disappear.

**Comment by agentfox** [comment]
Thanks, i'll try

Vào 15:24, Th 4, 12 thg 6, 2019 zeroin <notifications@github.com> đã viết:
