### ISSUE TITLE
Question: How to set initial Zoom on a DateAxis

### ISSUE THREAD

**Issue by cam-m** [amcharts/amcharts4#135]
I would like to be able to configure the initial zoom at chart creation (I'm using createFromConfig).

Is this possible? 

**Use case**
My client always requests the same preset date range of chart data from the server (lets say the last 90 days). Each chart is configured to show a smaller initial range of that 90 days of data (E.g. the last 7 days, last 14 days and so on).  Users can then toggle between zoom presets once the chart is displayed.

At the moment I'm using `DateAxis.zoomToDates` post chart creation. This works, however all 90 days of data are shown first before the preset zoom is applied. This is visually jarring. I tried the property `DateAxis.zoomFactor` but found it to be readOnly. I could not see any other property that suits.

Many thanks!

Cam

**Comment by martynasma** [comment]
I think zooming on a `"datavalidated"` event might be a solution for you:

```
chart.events.on("datavalidated", function () {
  dateAxis.zoomToDates(new Date(2018, 0, 21), new Date(2018, 1, 1), false, true);
});
``

Since this event happens before chart is drawn, the initial (zoomed out) stat will never make it to screen before `zoomToDates()` (or whatever else method you are using to zoom) kicks in.

Note the last argument to `zoomToDates()`. It makes instant zoom, so that there's no animation, even if you have "animated" theme enabled.

Hope you find this acceptable.

P.S. there are currently no special properties on axis for pre-zoom.

**Comment by cam-m** [comment]
That sounds great, i'll give it a shot shortly. Thanks heaps!

**Comment by cam-m** [comment]
This worked perfectly thanks!
