### ISSUE TITLE
Add toggle-all button to legend

### ISSUE THREAD

**Issue by chris-rs** [amcharts/amcharts4#1350]
My case uses a XYChart with 10 lineSeries. I added a legend below and the chart has great functionality to toggle individual lines.
Since my chart contains 10 lines it would tedious to toggle all individual lines if you want to view only one or two. How can I add a custom control in the legend that toggles all lines on/off next to the individual controls?

**Comment by martynasma** [comment]
You might find the following tutorial useful:
https://www.amcharts.com/docs/v4/tutorials/toggling-multiple-series-with-a-single-legend-item/

**Comment by chris-rs** [comment]
Hi Martynas,
Thanks for your reply. Yeah I already reviewed that tutorial. But this tutorial is about having a single toggle to control all. I like to have all individual line toggles but add an custom toggle which toggles them all. In fact I like to know how to extend the legend with an extra custom toggle to toggle all lines in the chart.
Regards

**Comment by martynasma** [comment]
You could add an additional series and use it toggle all other series.

https://codepen.io/team/amcharts/pen/JqVQJp

**Comment by chris-rs** [comment]
Thanks for your working example! Although it feels a bit like hacking it seems to do the job well.

**Comment by dvbuiilds** [comment]
It would be really helpful if you can share some resources on how to create a toggle for multiple series on amcharts 5. Everywhere it is amcharts 4 only.

**Comment by demetriad** [comment]
Second that.
