### ISSUE TITLE
Popup docs: Remove extra semicolon

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#1351]
On the [popup docs page](https://www.amcharts.com/docs/v4/concepts/popups-and-modals/#Appearance_via_CSS), there is an extra semicolon in the "default CSS" code block.

![image](https://user-images.githubusercontent.com/23387905/58964878-a3c88500-877d-11e9-9ee6-cd408699e91c.png)

**Comment by martynasma** [comment]
Thanks for the heads up! All done.
