### ISSUE TITLE
Is this possible?  (z-index related)

### ISSUE THREAD

**Issue by lgerndt** [amcharts/amcharts4#1352]
Here's the design spec:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/1790016/58981859-12aadb80-8788-11e9-9abd-3b1bb81522d3.png">

Here's what I *can* do, but notice the lines aren't on top of the bars (though, oddly, the bullets are).

![image](https://user-images.githubusercontent.com/1790016/58981981-59003a80-8788-11e9-8f26-c63bbdadd719.png)

And if I reverse the z-indexes, it looks like this (not what we want)

![image](https://user-images.githubusercontent.com/1790016/58982111-8fd65080-8788-11e9-98cf-b5740acf80a2.png)

Is there a way to selectively modify z-indexes such that the design spec can be achieved?

**Comment by Aterops** [comment]
I'm not sure about modifying the z-index as I would guess the stroke (line) of the area is part of the same object so the line and the area would always be in the same layer. The bullets are separate elements so they can be on top of the bars.

However a work around might be to remove the bullets and turn the stroke off the area series, and then add another series which is the same data as the area series, but just draw the new series as a line with bullets. That could then be set to be on top of the bars but leave the area behind the bars.

**Comment by lgerndt** [comment]
My designer just suggested the same thing, thanks for confirming the approach!
