### ISSUE TITLE
ZoomOut button visibility bug

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1354]
Open a bug which has been reported by @georgybu
> I also found unexpected behavior. When I unselect all and select one of them, I see ZoomOut Button.
> ZoomOut button visibility also is unpredictable.
> 
> https://codepen.io/georgyb/pen/MdLMXQ?&editable=true
> 
> ![image](https://user-images.githubusercontent.com/1044215/58817810-34477e00-8635-11e9-8fdd-05542a48d92c.png)

**Comment by zeroin** [comment]
This is by design. When some of the series are hidden, the chart does not change value axis, it zooms it in so that only the visible series are shown. If you click the zoomout button while some series are hidden, the chart will zoomout to the values as if all the series are visible.

**Comment by BrkCoder** [comment]
@zeroin thanks for the quick respond
