### ISSUE TITLE
Is there back to previous level button in TreeMap (without navigationBar)?

### ISSUE THREAD

**Issue by Kadirkhodjaev** [amcharts/amcharts4#1356]
Hi. I have a question. Can I back to previous page in TreeMap. In my case, navigationBar cannot be solution, because I have not so big place for my TreeMap. 

It will be great if there some solution like zoomOutButton, but only to previous level.

**Comment by martynasma** [comment]
Nope. Sorry :(

I'm going to leave this open to serve as a feature suggestion.

**Comment by martynasma** [comment]
I'm afraid we won't be adding built-in back button on TreeMap. Sorry.
