### ISSUE TITLE
Space between legend label and value in Pie Chart 3D

### ISSUE THREAD

**Issue by aline-matos** [amcharts/amcharts4#1360]
How can I descrease the space between legend label and value?

![space-between-3D-piechart](https://user-images.githubusercontent.com/5360477/59105843-3ea29a00-890b-11e9-915f-0fba8a6e4e81.png)

Thanks in advance

**Comment by martynasma** [comment]
For side-placed legends, the width is automatically set to `800` pixels.

Just set legend's `width` to something else:

```
chart.legend.width = 100;
```

**Comment by aline-matos** [comment]
Fantastic, thank you very much!
