### ISSUE TITLE
AM chart 4 Line with different negative color issue with positive numbers

### ISSUE THREAD

**Issue by gauravsarwal** [amcharts/amcharts4#1361]
Hi,
I am trying to replicate the functionality from this example chart from v4: https://www.amcharts.com/demos/date-based-line-chart/. It has different colors for negative and positive values for the line chart and the fill color. This chart has change in fill color on the base value of 0. I have dataset of all positive number and my base value is 10000 and it will never become negative and end value will be 100 . i.e

    var range = valueAxis.createSeriesRange(series);
    range.value = 10000 ;
    range.endValue = 100 ;

Is it possible to produce same kind of graph with positive numbers, if yes please suggest.

Cheers.

**Comment by martynasma** [comment]
Yes, the following tutorial describes how you can define ranges to color series:

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Value_axis_range

**Comment by gauravsarwal** [comment]
> Yes, the following tutorial describes how you can define ranges to color series:
> 
> https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Value_axis_range

I already gone through it but its coloring the fill in whole area, see this post: https://stackoverflow.com/questions/56465859/am-chart-4-line-with-different-negative-color-issue-with-positive-numbers?noredirect=1#comment99592356_56465859

**Comment by martynasma** [comment]
If you don't want a fill on the series outside of the range, don't set `fillOpacity` on your series:

```
series.fillOpacity = 0.1;
```

**Comment by gauravsarwal** [comment]
> If you don't want a fill on the series outside of the range, don't set `fillOpacity` on your series:
> 
> ```
> series.fillOpacity = 0.1;
> ```

its already 0.1, see below screenshot, range.value=140 and range.endvalue= 10.

![image](https://user-images.githubusercontent.com/2039902/59145580-7bea5300-8a03-11e9-92a8-9d8163cc7f0c.png)

**Comment by martynasma** [comment]
Oh ok. It's not possible. Sorry :(

**Comment by gauravsarwal** [comment]
Thanks for update, its bad  that its not possible, is there any way to make it possible with some other chart? Please suggest.
