### ISSUE TITLE
responsive issue

### ISSUE THREAD

**Issue by xbaha** [amcharts/amcharts4#1365]
on mobile device, when i display my chart, it's too small because i have over 30 bars, can the responsive mechanism cut the data and reduce the number of bars shown to be visually accepted?

**Comment by martynasma** [comment]
I don't think manipulating data is the right thing to do. The data should be the same regardless of the point of access. It's just the representation that needs to change, and that's where responsive features come in.

30 bars does not seem like somehting a phone screen could not handle.

I suggest taking a look at the responsive features here:
https://www.amcharts.com/docs/v4/concepts/responsive/

I'm sure that even enabling default rules, will solve the issue. And if not, you can tweak it with your own custom rules.
