### ISSUE TITLE
Category axis with extra visual info: help

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#1366]
Hy there, let's say we have an usual XYChart with CategoryAxis: https://codepen.io/aniov/pen/VOoRNy?editors=0010.
What is the best approach to add some extra info bars on top of every category with tooltip on mouse over? (like in the pic bellow)

![image](https://user-images.githubusercontent.com/21243081/59157985-6422d580-8abc-11e9-9afa-943a7130a3a5.png)

Thank you in advance.

**Comment by Aterops** [comment]
Possibly you could use a category range for each category? Something like:

let axisRange = categoryAxis.axisRanges.create();
axisRange.locations.category = 0;
axisRange.locations.endCategory = 1;
axisRange.category = "Marketing";

let axisFill = axisRange.axisFill;
axisFill.fill = am4core.color("green");
axisFill.interactionsEnabled = true;
axisFill.showSystemTooltip = true;
axisFill.readerTitle = "Some tooltip";

**Comment by martynasma** [comment]
Or use another series for that:

https://codepen.io/team/amcharts/pen/ec5890bab3c06b0c6cecb759c8f261cd

**Comment by aniov** [comment]
Thank you for your response.

@martynasma the solution seems ok but I also use zoom on chart, and zooming on 0y axis has effect on colored info bars also: https://codepen.io/aniov/pen/mZyEGW?editors=0010 which I don't want to be zoomed of course. If is a way to disable zoom for the extra columns then I can use it.

@Aterops I don't think I understand how to achieve my purpose. Can you give me a more complete example?

Thank you guys.

**Comment by martynasma** [comment]
Hey, sorry for the silence.

Here's a workaround involving additional series and axis:
https://codepen.io/team/amcharts/pen/WqqjYb?editors=0010
