### ISSUE TITLE
Tooltip map / keep focus on hover 

### ISSUE THREAD

**Issue by kalfeutre** [amcharts/amcharts4#1367]
Hi,
i'm wondering if it's possible to keep a custom html tooltip open when the focus is on the tooltip himself ( and not on the marker who opened it ) 

```
var imageSeries = map.series.push(new am4maps.MapImageSeries());
var imageSeriesTemplate = imageSeries.mapImages.template; 
var marker = imageSeriesTemplate.createChild(am4core.Image) ;
 marker.href = _URL + 'img/SITE/GENERAL/_marker_map.svg';
marker.width = 26;
marker.height = 35;
marker.nonScaling = true;
marker.tooltipHTML ="<div>{title}</div>";
marker.horizontalCenter = "middle";
marker.keepTargetHover = true;

```

I tried a lot of solutions but no one worked in this case ( the tooltip close when the marker is out of focus ) . What i do wrong ? 
Thanks a  lot

**Comment by martynasma** [comment]
Hm, `keepTargetHover` might not work on HTML tooltips :(

I'm marking this as a bug, so that we can look if there's a fix or a workaround.

At this point I can't promise anything, but we'll keep this open until we can take a stab at fixing it.

**Comment by Bleiber** [comment]
I think I have the same problem: Tooltip on ImageSeries (Yellow Dots) closes and as an result the button in the tooltip is not clickable. Example: [https://jsfiddle.net/e5ku3vr2/]( https://jsfiddle.net/e5ku3vr2/). Am I right?

**Comment by PratapAkshay** [comment]
I want to Copy text on tooltip by selecting it on Amchart barchart. please help

**Comment by martynasma** [comment]
I'm afraid we were not able to fix this. Focusing on HTML content removes focus/hover on the SVG elements. Closing.

**Comment by Oleksandr07** [comment]
The following code helped me solve this problem

//lets mouse hover over tooltip without it vanishing
imageSeries.tooltip.keepTargetHover = true;

//Enables interactivity of the tooltips label elements
imageSeries.tooltip.label.interactionsEnabled = true;
