### ISSUE TITLE
exporting chart in IE11 fails with error

### ISSUE THREAD

**Issue by jimitm10** [amcharts/amcharts4#1368]
Getting below error in IE11 when using this.chart.exporting.getImage('png').then((imgData) => { }

Unhandled Promise rejection: Object doesn't support property or method 'measureTextRecursive' ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Object doesn't support property or method 'measureTextRecursive' TypeError: Object doesn't support property or method 'measureTextRecursive'

I am using 4.4.3 version

**Comment by martynasma** [comment]
I don't think IE supports arrow functions `=>`.

Why don't you try defining it as a regular anonymous function?

```
  chart.exporting.getImage('png').then(function(imgData) {
    // do your thing
  });
```

**Comment by jimitm10** [comment]
The issue is not with arrow function. The error is coming when we call chart.exporting.getImage('png')
which uses canvg node module in which we are getting below error only in ie11.
Object doesn't support property or method 'measureTextRecursive' at at getAnchorDelta (http://localhost:4200/canvg.js:10:43785)

**Comment by martynasma** [comment]
Can you post your chart online, one that you are having issues with?

I tried with some chart setups, and the API export works just fine on IE11.

**Comment by jimitm10** [comment]
I found the issue. 
What I did is that i have updated canvg module version in your package.json file to latest and it is working fine in ie11. 
Can you please let me know which canvg version you are using in latest version of amcharts?

**Comment by jimitm10** [comment]
> Can you post your chart online, one that you are having issues with?
> 
> I tried with some chart setups, and the API export works just fine on IE11.

Do you have any angular 7 setup for testing this?
I am using Angular 7 and after updating the version of canvg from 1.5.3 to 2.0.0, it resolved the issue. 
So is it possible to update the version of canvg to latest version in amcharts?

**Comment by jimitm10** [comment]
Try this in IE11. It is giving the same error.
http://jsfiddle.net/c7oaw5m9/1/

Note: Its the same code which i have taken from your demo. I have added line for exporting the image. check the console. You will see the error.

**Comment by martynasma** [comment]
It looks like you are calling export before the chart is even built.

Try this instead:

```
chart.events.on("ready", function() {
  chart.exporting.getImage('png').then(function(res){
	console.log(res);
  })
});
```

**Comment by jimitm10** [comment]
It still gives the same error even after using your code
http://jsfiddle.net/8taezpx9/

**Comment by martynasma** [comment]
Hey, can you confirm this is still an issue for you?

Just tried your fiddle in IE11. Got export just fine.
