### ISSUE TITLE
Stacked XYChart Double Hit events work intermittently

### ISSUE THREAD

**Issue by cam-m** [amcharts/amcharts4#137]
On an XY chart with various features enabled (Scrollbar, Tooltips, Stacked columns) doublehit events don't fire consistently. It seems as I disable features one at a time the dblhit event becomes more reliable. With a very basic chart they fire consistently.

See [this codepen](https://codepen.io/cam-m/pen/RJzgxp?editors=0010) and refer to the console log.

**Comment by martynasma** [comment]
Hm, `doublehit` event seems to be firing for me every single time on both charts.

Could this be a browser thing? I'm testing on Chrome.

**Comment by cam-m** [comment]
How confusing! Yes Chrome here too. I found that i can work reliably at
first on one column, but then trying to click another column fails
repeatedly. Could you humour me and try that?

I'll try to narrow down the cause.

Cheers,

Cam

**Comment by cam-m** [comment]
Cleared Chrome's caches and retested... now can't replicate the issue. So sorry for wasting your time! Cam

**Comment by martynasma** [comment]
Ha, no worries!

I wish all of the issues would be resolvable via clearing cache ;)
