### ISSUE TITLE
Need v4 version of a v3 example - custom HTML legend

### ISSUE THREAD

**Issue by lgerndt** [amcharts/amcharts4#1370]
I was thrilled to see your example of how to write an HTML-based legend that interacts properly with the chart, but it turns out it's only for v3:

https://www.amcharts.com/docs/v3/tutorials/fully-functional-custom-legend-pie-chart/

Would you be willing to port that example to v4? It would really help, and I suspect quite a few people will want to use it.   I couldn't migrate it myself because I'm a newbie to amcharts.

P.S. I'm a Victory charts refugee, and absolutely loving this charting library. You guys rock!

**Comment by martynasma** [comment]
Sorry for late reply. Here's the same chart in V4:

https://codepen.io/team/amcharts/pen/aevJEw?editors=0010

Hope it's still relevant :)
