### ISSUE TITLE
Geodata missing: ukCountiesHigh.js / ukCountiesLow.js

### ISSUE THREAD

**Issue by Simon-01** [amcharts/amcharts4#1373]
Trying to learn how to work with maps and discovered Scotland only loads the small islands north of it and doesn't load the mainland.

Here's an example
https://codepen.io/anon/pen/PrwLVj

Example code taken from documentation here and edited
https://www.amcharts.com/docs/v4/chart-types/map/

**Comment by martynasma** [comment]
Hey just released a new geodata 4.1.7.

## [4.1.7] - 2019-07-31

### Added
- New maps: Gabon, Kenya.

### Fixed
- Fixed map: `ukCounties` map has Scotland wrong.
- Fixed map: `venezuela` map had a typo in name of "Carabobo".
- Fixed map: `worldRegions*` map had a wrong id for "Africa".
- Typo in `uzbekistan` map file names fixed.
