### ISSUE TITLE
How to animate new data when bound to the chart data

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1374]
Hi, 

When for the first time data is added to the chart they are not being animated and that is fine

eg `this.chart.data = [somevalues]`

I understand that if new data come in and you directly assign them like 

`this.chart.data = newData` 

then the chart does not animate. 

I understand that you need to find the old value on the current chart data and change it and also add add new categories via `this.chart.addData(nonExistingDataItem)`

So for all works fine. But what about removing data and animations? 

Eg if I splice the chart.data array and remove the ones that no longer exist in the new dataset then the chart does not upadate or animage with `invalidateRawData`. The removed data stay there. 

IF I call `invalidateData` the data get updated and the removed categories eg are removed but the chart won't animate. 

That is the way to animate the chart data upon removal?

**Comment by martynasma** [comment]
Hm, you can trigger initial animation of the series by calling its `appear()` method.

https://codepen.io/team/amcharts/pen/73d2e48db833e916509f3e2949cafe21?editors=0010

Maybe that could be a solution for you?

**Comment by jimmykane** [comment]
IT helps a bit but it wont show the data changing smooth animation.

The problem is mainly when data are removed from the chart data that you need to call the invalidate data that redraws the whole thingy , while the invalidaterawdata has a cool animation.

**Comment by jimmykane** [comment]
Perhaps this snippet explain the problem better: 

```
 // To create an animation here it has to update the values of the data items
    const generatedData = this.generateChartData(this.data);
    if (!this.chart.data.length) {
      this.chart.data = generatedData;
      return;
    }


    // Take out all data from the chart that do not exist on the new set
    let removedSomeData = false;
    for (let i = this.chart.data.length - 1; i >= 0; i--) {
      if (!generatedData.find(data => data.type === this.chart.data[i].type)) {
        this.chart.data.splice(i, 1)
        removedSomeData = true;
      }
    }
    // Go over all the new data
    for (const data of generatedData) {
      const existingDataItem = this.chart.data.find(dataItem => data.type === dataItem.type);
      if (!existingDataItem) {
        this.chart.addData(data);
      } else {
        existingDataItem.value = data.value;
      }

    }
    removedSomeData ? this.chart.invalidateData() : this.chart.invalidateRawData();
```

**Comment by martynasma** [comment]
Thanks. Well, I'm not sure how animation of data removal should look like, but we don't support it :(

The only variant is to update data, and call `appear()` to make the whole series animate again.

**Comment by jimmykane** [comment]
@martynasma  is the new `updateCurrentData ` related ?

**Comment by parthi2929** [comment]
Even I am facing the same issue. Using appear will actually refresh the chart making it vary from initial value instead of new value. My code

```
    chart.setTimeout(randomValue, 2000);
    // setInterval(randomValue, 2000);
    

    var newData = [];
    function randomValue()
    {
        console.log("Hello");         
        var val1 = Math.random() * 100;    
        // newData  = [{
        //     "category": "Raw Water Tank (RWT)",
        //     "value1": val1,
        //     "value2": 100-val1
        //   }];   
        // chart.data = newData;

        chart.data[0]['value1'] = val1;
        chart.data[0]['value2'] = 100-val1;      
        chart.validateData();  
        chart.appear();
        // console.log(chart);

        chart.setTimeout(randomValue, 2000);
    }

```

**Comment by msaqlain** [comment]
Why this is closed without any solution? I need the same behavior of animating chart when data is changed.
