### ISSUE TITLE
Problems compiling Angular 8 CLI project with amcharts4

### ISSUE THREAD

**Issue by Stychlok** [amcharts/amcharts4#1375]
I updated my application which used @amcharts/amcharts4@4.3.5 to Angular 8 and now have problems compiling it.

Already updated amcharts to version 4.4.10. But the problem remains.

> ERROR in ./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js 68:24
> Module parse failed: Unexpected token (68:24)
> You may need an appropriate loader to handle this file type.
> |             switch (_a.label) {
> |                 case 0: return [4 /*yield*/, Promise.all([
>                          import(/* webpackChunkName: "pdfmake" */ "pdfmake/build/pdfmake.js"),
> |                         import(/* webpackChunkName: "pdfmake" */ "../../pdfmake/vfs_fonts")
> |                     ])];

**Comment by martynasma** [comment]
Take a look at thread in #1002
