### ISSUE TITLE
Column image children outside of container

### ISSUE THREAD

**Issue by CarlosHdez** [amcharts/amcharts4#1376]
Hi,
I'm trying to add some Image bullets to the bottom of a ColumnSeries and as the docs specify I'm using just a children for each column, but I have some issues.
![image](https://user-images.githubusercontent.com/5401623/59457719-98f59c00-8dde-11e9-8500-78f9e2f9bf75.png)
As you can see if the column is too short, the image is not visible is there a way for it to always be rendered or for me to move it outside of the chart container so that it continues below ('maskBullets' won't work since this is not actually a bullet)

Thanks for your help

**Comment by martynasma** [comment]
Do you perhaps have a codpen/jsfiddle of your chart?

**Comment by CarlosHdez** [comment]
Sure, here it is https://codepen.io/carloshdez/pen/EBNwOM

**Comment by martynasma** [comment]
Well, those are not bullets but children of columns.

Would you consider adding them as regular bullets? If the scale of values always starts at zero, like in your example, that might work better than child-element approach.

https://codepen.io/team/amcharts/pen/5b9d010388ad4a33f1d3f24a89a43439

**Comment by CarlosHdez** [comment]
Ohh ok, I just got confused based on the docs saying it will require children from columns but I now see that it works just fine with bullets, thanks.
