### ISSUE TITLE
zoom/pan/scroll force-directed-diagram

### ISSUE THREAD

**Issue by hichd** [amcharts/amcharts4#1377]
Whenever I display a large amount of child nodes, some parent nodes start floating out of the browser's screen space and they become unreachable. I tried to find out how to implement zooming or panning capability but all I came across were ways to implement these features for XYcharts and maps. I couldn't figure out how to restrict the nodes into a closed container either. Any help would be immensely appreciated. 

here is what I mean : 
https://codepen.io/hichd/pen/ewpoVX

**Comment by martynasma** [comment]
There's no way to pan or zoom ForceDirectedChart, I'm afraid.

I noticed you had this in your code:

```
networkSeries.linkWithStrength = 0;
```

I suggest setting this value at some non-zero number, e.g. `0.2`. It will bring clusters of nodes closer together, making them more likely to fit into container.

![image](https://user-images.githubusercontent.com/1458520/59547402-045a7d80-8f47-11e9-8dbf-3e2415c16454.png)

Hope that helps.

**Comment by lancegliser** [comment]
For reference, there is a version of pan and zoom to investigate now. Might not be exactly what you need but start here: https://www.amcharts.com/docs/v4/chart-types/force-directed/#Zooming
