### ISSUE TITLE
How can I invert the selection behavior on click in the legend of the donut chart?

### ISSUE THREAD

**Issue by aline-matos** [amcharts/amcharts4#1378]
The current behavior of the donut chart is to remove of the chart the item when you click on a legend item. How do I reverse this behavior, by clicking on the legend item, select and highlight this item?

**Comment by martynasma** [comment]
Do you mean that the chart should start off empty with all slices disabled, then the user would click them all on selectively?

I suppose you can do that with `dataFields.hidden`.

Here's a demo:
https://codepen.io/team/amcharts/pen/PrZOLq?editors=0010

**Comment by aline-matos** [comment]
I've mean the chart start with all the data and slices enabled, but when I click in a item on the legend, instead of remove the clicked data, highlight this data.

**Comment by martynasma** [comment]
OK, this then:
https://www.amcharts.com/docs/v4/tutorials/activate-deactivate-a-pie-slice-on-legend-click-instead-of-toggling/

**Comment by aline-matos** [comment]
Thank you very much @martynasma !!!
It's also possible to allow only one item at time?

**Comment by martynasma** [comment]
Well, you would need to modify the code to cycle through all of the slices and unselect them:

```
chart.legend.itemContainers.template.events.on("hit", function(ev) {
  var slice = ev.target.dataItem.dataContext.slice;
  pieSeries.slices.each(function(item) {
    if (item != slice) {
      item.isActive = false;
    }
    else {
      slice.isActive = !slice.isActive;
    }
  })
});
```

https://codepen.io/team/amcharts/pen/vqWOVJ
