### ISSUE TITLE
Question How to hide the Amcharts logo 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1379]
I do well understand that on the free side we should not hide the logo. 

However, considering to purchase, I was trying to figure out how to hide the logo and it's impossible. 

this.chart.logo.hide() or hidden does not work.

**Comment by martynasma** [comment]
Can you ping us at contact@amcharts.com? We'll sort it out. I'm reluctant to post logo removal instructions here out in the open :)

**Comment by jimmykane** [comment]
Aha! Sure! Np. It's not my number one prio atm and good for you to hide it :-D 

I add a screen here of what is being built with your awesome charts 
<img width="944" alt="Screenshot 2019-06-14 at 16 46 22" src="https://user-images.githubusercontent.com/1268723/59517817-b3a24080-8ec4-11e9-8905-12eb1678d295.png">

**Comment by martynasma** [comment]
No seriously, ping me on contact@amcharts.com. Let's hide those logos. They look real ugly overlapped with export button in an otherwise sleek interface.

**Comment by jimmykane** [comment]
Done

**Comment by noiwid** [comment]
Hi, did you get what you need ? :)

**Comment by breshman** [comment]
If it's any use, this worked for me.
**chart.logo.height = -15;**

**Comment by daaddd** [comment]
If it's any use, this worked for me. (2)
chart.logo.height = -15000;
this will remove the logo, if you start earning revenue with your app make sure to purchase the license and support the developers for this amazing tool.

**Comment by arifhas** [comment]
i have used
chart.logo.disabled = true;
and worked for me

**Comment by arifhas** [comment]
May be this is the best way to hide it.
chart.logo.disabled = true;
and worked for me

**Comment by arifhas** [comment]
May be this is the best way to hide it.
**chart.logo.disabled = true;**
and worked for me

**Comment by noiwid** [comment]
@arifhas Thanks a lot, works like a charm!
I'm happy to see they provide an official solution.

**Comment by Floreskikeson** [comment]
chart.logo.disabled=true;
paste in any part of code for any chart :D

**Comment by Swaraj55** [comment]
> May be this is the best way to hide it.
> **chart.logo.disabled = true;**
> and worked for me

It worked for me.
Thanks @arifhas

**Comment by sekny** [comment]
Is there any problem if I using Free license and hide @Amcharts logo?
