### ISSUE TITLE
Question - Is there any event to know axes labels are rendered

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#138]
Hi,

Is there any event to know when all the axes labels are rendered or each label is rendered

**Comment by martynasma** [comment]
You may use axis' `"inited"` event for that:

```
axis.events.on("inited", function(ev) {
  // ...
});
```

Or you can trigger init event for each individual label:

```
axis.renderer.labels.template.events.on("inited", function(ev) {
  // ...
});
```

However, if you could explain your reasoning behind requiring to know if labels are rendered, I might suggest some better approach.

Normally, you should not care if label is rendered or not.

**Comment by Varshamathukumalli** [comment]
We wanted to remove from tspans after it is rendered. But anyway we are giving only the required text.
Is there any way to use category field as different and the labels we display are different?

**Comment by martynasma** [comment]
> Is there any way to use category field as different and the labels we display are different?

Not sure I follow. Do you want to display `CategoryAxis` titles other than the actual categories?

**Comment by Varshamathukumalli** [comment]
Yes

**Comment by martynasma** [comment]
In that case you might want to check out adapters:

https://www.amcharts.com/docs/v4/concepts/adapters/

```
categoryAxis.renderer.labels.template.adapter.add("text", function(text, target) {
  return ">>> " + text + " <<<";
});
```

https://codepen.io/team/amcharts/pen/bjNapq?editors=0010

**Comment by Varshamathukumalli** [comment]
Hi,

We are updating the object which we are assigning to chart.data, then bars are not rendered for the fields which are modified. In the below url, bars are not rendered for the labels which are wrapped into multiple lines programatically.

codepen url: https://codepen.io/varshamathukumalli/pen/qyBXjE

**Comment by martynasma** [comment]
This is happening because you are using different fields for category axis and series. You use your processed field (`labelField`) for axis and source field (`country`) for series.

Since some of the values due not match, hence no bars.

Those should be equal.

**Comment by Varshamathukumalli** [comment]
Oops, our mistake. 
Thanks

**Comment by martynasma** [comment]
No worries :)

Feel free to close this issue if this is resolved.

If you have other questions, feel free to open a new issue so this one does not get too long and complicated for anyone else to follow.
