### ISSUE TITLE
Clustering of points with number indicator

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1385]
Hey I have the following example of clustering points in amcharts4:
https://codepen.io/Barak/pen/xoVVjO?editors=0010
which based on the issue: https://github.com/amcharts/amcharts4/issues/1087
I would like to know how can I add a number which indicates on the number of points in current cluster.
Can you provide such an example?
Thanks in Advance
Barak Inbal

**Comment by martynasma** [comment]
We don't have such example. However, if you'd to implement one, it would probably go like this:

1) Create additional series for bullets.
2) Add handler for series `datavalidated` event.
2) Push labelbullet into the bullet series data to show the label at specific point.

I hope you'll be able to implement it.
