### ISSUE TITLE
Ho do i make column specific series 

### ISSUE THREAD

**Issue by GensysSonar** [amcharts/amcharts4#1386]
i wan to create column specific series like there is only two series for column A and three series for column B . I have done this through data but its make blank space for no value series. it create blank space for series 3 in column A. 
i have define my problem in screen shot please refer it. 
thank you in advance.i wan to create column specific series like there is only two series for column A and three series for column B . I have done this through data but its make blank space for no value series. it create blank space for series 3 in column A. 
i have define my problem in screen shot please refer it. 
thank you in advance.
<img width="941" alt="amchar issue" src="https://user-images.githubusercontent.com/42341930/59565829-952f7700-9075-11e9-81e2-cf753877d9d1.png">

**Comment by martynasma** [comment]
I'm sorry, but there's no way to "collapse" series with missing data.

The only workaround would be to have single series, then grouping columns using axis ranges.

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/

**Comment by GensysSonar** [comment]
Thanks Martynas Majeris I appreciate your quick response.
