### ISSUE TITLE
Display XYChart ValueAxis in percent?

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1388]
Is it possible to display the ValueAxis labels in percent instead of the actual values?  The zero could, e.g., be either the lowest displayed grid line or the grid line closest to the lowest displayed value.  The highest displayed values could be well below 100% or go well above (to say 200% or 300%).

**Comment by zeroin** [comment]
If you set:

`series.calculatePercent = true;
series.dataFields.valueYShow = "changePercent";`

Instead of real values, the series will display how much each value changed comparing to the first one and axis will also show these values. Is it what you want to achieve?

**Comment by bfailing** [comment]
You suggestion doesn't seem to apply to candlestick charts.  You can uncomment the lines you've suggested in [this pen](https://codepen.io/anon/pen/zVzPLJ).  At any rate, I don't think it's the best solution as discussed below.

My application uses up to ten charts on a page with combinations of candlestick, line, and column charts.  Some of the line charts have 5+ series.  The performance of this (actually with just the candlesticks alone) is very poor with >1,000 data points (e.g., vs. TradingView which works very well with many more data points) when loading, zooming, panning, adding data, etc.  So I'm hesitant to use `series.calculatePercent = true;` which would reduce performance (according to your documentation).  Also, I don't know if it would solve the problem re the valueAxis labels.

With reference to the pen above, the zero percent line could be either the lowest grid line (0.0099) or the grid line closest to the data (0.01) as examples.  In the first example, the 0.01 grid line would be 1.01%, the 0.0101 grid line would be 2.02%, and so on.  In the second example, the lowest grid line would be -1%, the 0.0101 grid line would be 1%, the 0.0102 grid line would be 2%, and so on.  This allows you to quickly visualize the data wrt percentages and is common on commercial financial software packages.

Calculating the percentages for ~10 grid lines is much more efficient than for 1,000+ data points.  This could be done by looping through the DOM elements for the labels and changing them, but I'd rather use something within your code.  Is it possible to overwrite the labels via the amcharts code without directly changing them in the DOM?  Perhaps as an alternative, is it possible to create a second set of valueAxis labels as percentages and hide the set with the actual values?

**Comment by zeroin** [comment]
Well, yes, you can easily change text in the value axis labels. We have adapters for that. Here is a basic example:

`valueAxis.renderer.labels.template.adapter.add("text", (text, label)=>{
  return label.dataItem.value + "%";
})
`

You can do any math with label.dataItem.value you want.

**Comment by bfailing** [comment]
How do you find the `label.dataItem.value` for the bottom-most grid line?

**Comment by zeroin** [comment]
I would check if the value of a data item is the same as min of the value axis: https://codepen.io/team/amcharts/pen/LKOwoo

**Comment by bfailing** [comment]
Instead of the minimum value for the valueAxis, is it possible to access the value of the bottom-most displayed grid line?  If the chart is zoomed in, the bottom grid line often changes.  I want the label of the bottom-most displayed grid line to be 0%.

As a separate question, is it possible to switch back and forth between the new labels (e.g., percentages) and the original labels (e.g., value) without refreshing or zooming the chart?  See [this pen](https://codepen.io/anon/pen/QXawXg).  By toggling the "Use Percentages" checkbox, you can switch between the two, but there are issues.  For example, if you start with the checkbox checked, uncheck the checkbox, then zoom in about halfway, the "9.09%" line changes to "0.0108" and does not change back.  For some reason, the "5.05%" does not change to "0.0104".  Previously hidden grid lines work as expected (e.g., the "0.0109" line changes to "10.10%" and back).  That said, the labels do not change without zooming.

**Comment by zeroin** [comment]
I could not think of a bullet-proof way to find which of the label is the first. From my point of view, showing percent values like in your case, especially when the chart is zoomed doesn't make a lot of sense and I would say might be misleading. valueAxis has properties start and end which are relative values (0-1) indicating the zoom level of axis, so theoretically you can calculate the possible value of first grid, but this won't be really accurate.

As for the switching - you can simply deepInvalidate all the axis when user clicks on the checkbox:

```document.getElementById("cb").addEventListener("click", function(){  valueAxis.deepInvalidate()})```

**Comment by bfailing** [comment]
It's the other way around.  Showing percentages based on the entire data range (even data not shown due to zoom) is misleading as the percentages are not representative of the displayed data.  Take the attached screenshot from TradingView showing percentages of the displayed data.  To put values to the data, say the 0% grid line corresponds to a value of 100 and the 24% grid line corresponds to a value of 124.  If the lowest value of in the chart is say 25 (off-screen to the left because say it's a value from yesterday's data), then the 0% grid line would be 300% and the 24% grid line would be 396%.  So you would indicate a difference of 96% instead of a more representative difference of 24%.

As an alternative, is it possible access the delta between grid lines (i.e. a grid line spacing in valueAxis values)?

![TV Percent](https://user-images.githubusercontent.com/17439289/60459616-8230b100-9bf6-11e9-8353-21e526964cbf.jpg)

**Comment by zeroin** [comment]
I see. Maybe I simply haven't faced case like this, as from my experience, in finance charts, when axis shows percent, the values are recalculated so that they would show the relative change comparing to the first item in the selection.

The delta between values can be accessed via `valueAxis.step`
