### ISSUE TITLE
Setting a label inside a pie chart does not render well on mobiles (ANDROID)

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1390]
Create a lable inside a chart like so: 

```
const label = pieSeries.createChild(am4core.Label);
      label.horizontalCenter = 'middle';
      label.verticalCenter = 'middle';
      // label.fontSize = 12;
      label.html = `{values.value.sum.formatNumber('#')}`;
      label.adapter.add('htmlOutput', (text, target, key) => {
        const data = DynamicDataLoader.getDataInstanceFromDataType(this.chartValueType, Number(text));
        return `<p style="text-align: center; font-size: 1.1em">${data.getDisplayType()}</p>
                <p style="text-align: center; font-size: 1.2em; font-weight: bold">${data.getDisplayValue()}${data.getDisplayUnit()}</p>`
      });
```

The only thing needed is a 2 line label. 

On all devices it renders fine except Android phones. 

![image](https://user-images.githubusercontent.com/1268723/59690889-739fce00-91e2-11e9-80e3-c3ac74d1fd9f.png)

vs the rest that look like: 

<img width="355" alt="Screenshot 2019-06-18 at 16 01 11" src="https://user-images.githubusercontent.com/1268723/59690929-85817100-91e2-11e9-9d1d-ce87d0c3557a.png">

**Comment by martynasma** [comment]
Sorry just noticing this now.

When you are using HTML output for labels, it produces foreignObject with HTML in it. We have little control over how Android browser renders HTML.

How about using SVG labels? `textOutput`.

The formatting options seem pretty straightforward and can totally be replicated using amCharts' in-line formatting:
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Visual_formatting

**Comment by jimmykane** [comment]
The problem is that I want to use the numerical value. 

I tried `textOutput` on a label adapter and it does not get called.

**Comment by jimmykane** [comment]
Actually it works if you dont use the html but text

**Comment by jimmykane** [comment]
Ok almost there but stuck 

```
label.adapter.add('textOutput', (text, target, key) => {
      const data = DynamicDataLoader.getDataInstanceFromDataType(this.chartDataType, Number(text));
      return `[font-size: 1.3em]${data.getDisplayType()}[/]\n
              [font-size: 1.4em]${data.getDisplayValue()}${data.getDisplayUnit()}[/]\n
              [font-size: 1.0em]${this.chartDataValueType}[/]`
    });
```

<img width="467" alt="Screenshot 2019-07-27 at 15 39 23" src="https://user-images.githubusercontent.com/1268723/61995160-bfb51c80-b084-11e9-89e9-6c3b5312a624.png">


The only thing I miss is the alignment of the context with line breaks to center. 

Any clue? @martynasma

**Comment by martynasma** [comment]
> The only thing I miss is the alignment of the context with line breaks to center.

How about using `textAlign`?

```
label.textAlign = "middle";
```
