### ISSUE TITLE
"Auto-hide value axes" example doesn't work for stacked axes.

### ISSUE THREAD

**Issue by kzh-dev** [amcharts/amcharts4#1392]
This example doesn't work if rightAxesContainer is "vertical". https://www.amcharts.com/docs/v4/tutorials/auto-hide-value-axes/

**Comment by zeroin** [comment]
If layout of rightAxesContainer == "vertical" then you will have to hide series of both right axes in order the chart to expand and take all the space, we can not change this behavior. Unless you had something else in your mind.

**Comment by kzh-dev** [comment]
@zeroin Thank you very much for your quick response!

When I added this line to the example on CodePen and reran:
```
chart.rightAxesContainer.layout = "vertical";
```

* After I hide both series, when I show one of the series, its Y axis takes place only half of the chart height.  Could you suggest me the best way to have remaining axes take place entire chart height?
* The chart behavior looks little bit weird when I do:
  1. Hide "Hits" by clicking chart legend. ("View" series look unchanged but its Axis shifts upward.)
  2. HIde "Views".
  3. Show "Views". (The series and its axis appears in the upper half of the chart)
  4. Show "Hits". (Both series are displayed in the upper half but their Axes look normally.)
