### ISSUE TITLE
Edge labels on map prevent click on area

### ISSUE THREAD

**Issue by jorseijo** [amcharts/amcharts4#1393]
When I test my map on Edge, the labels that I place on the map to display some data prevent the click on the map areas to work.  So basically the labels are placed on top of the areas and when you click on them nothing happens. What can I do to trigger the area click when clicking on the labels?

**Comment by martynasma** [comment]
You may need to disable interactions on your labels, e.g.:

```
labelTemplate.interactionsEnabled = false;
```

**Comment by martynasma** [comment]
More info and examples here:
https://www.amcharts.com/docs/v4/tutorials/automatic-labels-over-map-polygons/#Series_for_labels

**Comment by jorseijo** [comment]
Indeed I just found out that the key is interactionsEnabled. But it is ignored by MS Edge. Whatever I set it to, the labels are not clickable.

**Comment by jorseijo** [comment]
Apparently when using html for the label, not when I use text.

**Comment by martynasma** [comment]
Is there specific reason you want to use HTML labels over SVG ones?

**Comment by jorseijo** [comment]
I'm trying to make a weather map and I show temperatures like this: polygon.dataItem.dataContext.value + "&#176;" (that would be the degrees symbol)
It would be great to know how to put this in the map without compromising the clicking on the map areas regardless of the browser.

**Comment by martynasma** [comment]
I suggest you use `MapImageSeries` for those icons.

Like here:
https://www.amcharts.com/demos/weather-map/
