### ISSUE TITLE
Call to toString() in core.js throws security errors

### ISSUE THREAD

**Issue by animaldna** [amcharts/amcharts4#1394]
Attempting to load a map in an iframe cross-domain throws the following: 

```core.js:formatted:13853 Uncaught DOMException: Blocked a frame with origin "https://www.cbdcentral.com" from accessing a cross-origin frame.
    at Object.Mtpk.e.toText (https://SOURCE.COM/assets/core.js:1:266131)
    at e.set [as valign] (https://SOURCE.COM/assets/core.js:1:438596)
    at https://SOURCE.COM/assets/standalone-map.js?ver=5.2.2:9:24
```

Access Control has been set to wildcard, so no issue with CORS. Tested in Chrome 74.0.3729.169 and FF 67.0.3.

**Comment by martynasma** [comment]
When you say "cross-domain", do you mean that iframe's `src` is from another domain, or that some assets in it are loaded from another domain?

If you could provide an example, that would be great.

**Comment by shakee93** [comment]
here is a fiddle : https://jsfiddle.net/shakee93/vsjpbrzk/

**Comment by martynasma** [comment]
I'm getting a lot of errors in console. None of those seem to be related to amCharts.

It must be something related to how the web page is set up.

Here's a codepen with an iframe with a demo from amcharts.com:

https://codepen.io/team/amcharts/pen/6922c6d5fa9ddfc50b34c9745e540ee9

Working fine.
