### ISSUE TITLE
Tooltips inside AxisRanges

### ISSUE THREAD

**Issue by diego2094** [amcharts/amcharts4#1396]
I was using an XYChart with some AxisRanges determining different sections of the chart and implemented some tooltips with HTML to provide some information for each section.

Some days ago I realized that they stopped working and been trying to find what caused the problem. I weren't able to find anything so I checked your latest commits to see if there was any dated when I started having the issue.

Finally, by moving to a previous version of the library (4.4.10), they are working again.

Maybe in those last commits there's something that prevent them from showing.

**Comment by zeroin** [comment]
Could you please provide the code of the demo? What kind of series do you use?
