### ISSUE TITLE
Question: Limiting axis labels

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#140]
Hi,

How to display only specified number of labels on x-axis or y-axis(providing frequency or interval)

**Comment by martynasma** [comment]
We do have an excellent article that deals with this topic:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/

Let me know if you still have questions after reading it.

**Comment by Varshamathukumalli** [comment]
In the documentation, minGridDistance property is used to set the customized number of labels . 
But that property is in pixel, whereas what we are expecting is a number which specifies to display only 4 or 5 labels

**Comment by martynasma** [comment]
I'm afraid, there is no setting to force the axis to display specific number of labels.

Axis label/grid frequency is a product of complex mechanism, which determines optimal number of labels/grid lines, which is influenced by a lot of criteria.

That said there might be ways to influence labels other than `minGridDistance`. What kind of axis are you trying to control number of labels on? If you could provide a sample chart you are working on, that would b great.

**Comment by Varshamathukumalli** [comment]
Actually we want to display the number of labels on category axis depending on the user input.
Say if he/she provides interval as "3", then we'll display labels  which will be displayed with a gap of 3 bars/points.

**Comment by martynasma** [comment]
I'm afraid that is currently not possible. Sorry.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by NPC** [comment]
@martynasma is there a way to determine, how many labels are shown by an axis? I am digging through CategoryAxis object in the console. but so far can't even find where it holds labels it rendered.

(by checking that and dynamically adjusting minGridDistance / rotation I hope to achieve more/fewer labels automatically)

**Comment by martynasma** [comment]
@NPC You can find all label instances of an axis in `axis.renderer.labels`.

Same with `ticks` and `grid`.

**Comment by NPC** [comment]
@martynasma thank you, I'm progressing, but still need help in detecting which of those labels are visible.

I've tried these criteria:
* label.currentText — when checked on chart “inited“ event, it is mostly only populated for visible labels (plus an odd label with text “L”, which I assume is your internal helper), but on chart resizes all of the labels have their currentText populated.
* label.isHidden / label.hidden / label.isHiding — always false.
* label.element.node.getBoundingClientRect().width — on “inited” it is 0 for all labels, later it is set to non-zero for visible labels, but also for some (not all) invisible ones.

(also JQuery .is(':visible'), but that was a shot in the dark anyway, and it didn't work as I expected)

PS Is it OK to check this on “inited”, or should I wait till “ready”? (then label adjustments will make the chart jump around, but that's manageable).

**Comment by NPC** [comment]
@martynasma is there an update on above? Or where could I look?

**Comment by NPC** [comment]
@martynasma I'm checking the new CategoryAxis.frequency property, it seems to provide the information I needed, thank you for this improvement!

Now the chart flickers when I try to adjust label positions on the fly (seeking to achieve frequency === 1 if possible), but that's a different issue.
