### ISSUE TITLE
Tooltip.pointerOrientation = "up" does not work as expected

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#1401]
Looks like "up" is ignored.

![image](https://user-images.githubusercontent.com/1458520/60085644-5c149800-9742-11e9-9049-b9c2daab489d.png)

Example:
https://codepen.io/team/amcharts/pen/5876406429037162bd149569e99ba289?editors=0010

**Comment by zeroin** [comment]
This is caused because when we have little estate for the tooltips they are arranged in order not to overlap and the pointer orientation changes.
