### ISSUE TITLE
radarColumnSeries.columns.template.propertyFields.fill = "myCustomColor";

### ISSUE THREAD

**Issue by naveenhirebeel** [amcharts/amcharts4#1402]
propertyFileids.fill some custom color works for ColumnSeries but the does not work for RadarColumnSeries, Kindly let me know how to achieve the same.

**_Works_**
columnSeries.columns.template.propertyFields.fill = "myCustomColor";

Check Demo Example : http://jsfiddle.net/Lyrtfqvg/1/
Line Number  72

**_Does Not Work_**
radarColumnSeries.columns.template.propertyFields.fill = "myCustomColor";

Check Deom Example : http://jsfiddle.net/sybmevg2/
Code is at line number 86.

@martynasma Kindly verify.

**Comment by zeroin** [comment]
To set custom color on radar column, use:

`series1.columns.template.radarColumn.propertyFields.fill = "myCustomColor";`
