### ISSUE TITLE
Show tooltip item for non-zero data item only

### ISSUE THREAD

**Issue by mattlung** [amcharts/amcharts4#1403]
My stacked column chart has more than 50 series, the tooltip becomes laggy and difficult to view. So, I would like to show tooltip for non-zero data item only. Or is there has any other config that can improve the chart performance? Thanks.

**Comment by zeroin** [comment]
My suggestion would be to disable cursor tooltips at all by setting `series.cursorTooltipEnabled = false` And add tooltips to column templates only. Then the tooltip will be shown only on a hovered column and the performance should be much better.

**Comment by mattlung** [comment]
I have already set `series.cursorTooltipEnabled = false`, and it is still quite slow when the tooltip is shown on the hovered column. And the value of most data items are zero, so I want to hide those tooltips when hovering the column. Is it possible to do that?

**Comment by mattlung** [comment]
@zeroin Thanks. The performance is much better now.
