### ISSUE TITLE
Adding images to timeline

### ISSUE THREAD

**Issue by EdoRguez** [amcharts/amcharts4#1406]
Is it possible to add images to the timeline? This would be a great feature when you make a history timeline or something like that.

I'm using this example but I cannot find out how to add images.

https://www.amcharts.com/demos/timeline/

**Comment by zeroin** [comment]
A bullet is a container, so you can add anything to it. Here is a demo with bullets with images, you can do the same with timeline: https://www.amcharts.com/demos/bars-with-moving-bullets/

BTW, we are working on a much more advanced timeline plugin, it should be released until the end of the summer.

**Comment by EdoRguez** [comment]
Thanks!
