### ISSUE TITLE
Labels position on both sides of pictorial stacked chart

### ISSUE THREAD

**Issue by Andrewzzx** [amcharts/amcharts4#1407]
Is it possible to position labels on both sides of a chart? For example, I have 4 labels and I want to position two of them on the left, others on the right. I could only found this option:
`series.alignLabels = true;
 series.labelsOpposite = true;`
But it allows to change position of all labels.

**Comment by zeroin** [comment]
Unfortunately this is not supported out of the box. You could however try setting `series.alignLabels = false` and then set dx property field for labels and have positive/negative dx values in your data.
