### ISSUE TITLE
AmCharts Maps with custom maps bug

### ISSUE THREAD

**Issue by apuntovanini** [amcharts/amcharts4#1408]
Following https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/ I created Italy's provinces GeoJson.
When used:

```javascript 
// data/provinces.js

export default {
  type: 'FeatureCollection',
  features: [...]
} // see attached file (nope, can't send .js, let me know if you need it)
```

```javascript 
import provinces from 'data/provinces';

const chart = am4core.create('map-chart', am4maps.MapChart);
chart.geodata = am4geodata_italyLow;
chart.projection = new am4maps.projections.Miller();
const polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
polygonSeries.useGeodata = true;
```
it seems to produces wrong svg attributes and freezes with more than 5 items
![Schermata 2019-06-27 alle 19 15 17](https://user-images.githubusercontent.com/1159781/60286501-f37b1600-990f-11e9-84af-cbe50bb55686.png)

We use webpack 4

**Comment by zeroin** [comment]
Well, we need the map file in order to find where the problem is. Is there a way you could share it?

**Comment by apuntovanini** [comment]
https://www.dropbox.com/s/7rkqts2zb7mnncf/provinces.js?dl=0
https://www.dropbox.com/s/cpp1idcwz45ies9/provinces.json?dl=0

**Comment by zeroin** [comment]
Your maps do not use real longitudes/latitudes, (longitude mus be within -180 and 180 and latitude within -90 and 90. If you are using some software to generate these maps, check if it has an option to use real longitudes/latitudes. Unfortunately we only support real-life coordinates.

**Comment by apuntovanini** [comment]
Confirmed, Italian's official shapefiles needed a conversion I made with 

```ogr2ogr -f GeoJSON -s_srs prov2011_g.prj -t_srs EPSG:4326 sub.json prov2011_g.shp```

as of @riccardoscalco suggestion in https://gist.github.com/riccardoscalco/6029355
It works! Thank you very much

**Comment by rogobgobs** [comment]
@apuntovanini can you teach me the proses of making custom map in amchart

**Comment by apuntovanini** [comment]
These are notes I left to myself months ago, I hope they can serve your purpose

Download shapefiles from ISTAT https://www4.istat.it/it/archivio/209722

```
ogr2ogr -f GeoJSON -s_srs ***.prj -t_srs EPSG:4326 provinces.json ***.shp
```

Upload all the files to mapshaper (https://mapshaper.org/) and follow this guide
https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/

precision=0.0001 id-field=SIGLA

**Comment by rogobgobs** [comment]
why my geojson file is normal in github and raw data github, but when i called the raw data in Amchart especially on chart.geodataSourceurl , there is not showed like in github 
![image](https://user-images.githubusercontent.com/64123952/86097231-8d0a7400-bade-11ea-8f61-1a89e27bf129.png)
on github
![image](https://user-images.githubusercontent.com/64123952/86097337-b0cdba00-bade-11ea-98f8-3c368e755a67.png)
on amchart

please anyone help me
