### ISSUE TITLE
No way to override ChordLink's color

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#141]
It always takes on its originating `ChordNode` color.

It's impossible to set via `chart.links.template.fill` and even via `chart.links.template.propertyFields.fill`.

Example:
https://codepen.io/team/amcharts/pen/b1fb06f13edb1bf1d276fcc8199fb8ba/

**Comment by zeroin** [comment]
you must set:

link.colorMode = "solid"; on a link template in order custom colors to work.
