### ISSUE TITLE
tooltipHTML does not work as expected on DateAxis

### ISSUE THREAD

**Issue by mattlung** [amcharts/amcharts4#1410]
I have set the tooltipHTML for a DateAxis. When the mouse hovers on the label first, the html content can be displayed. But when the mouse is hovering from the top side, the tooltip content will be use default formatted date. 

Here is the demo: https://codepen.io/anon/pen/wLpaYy

**Comment by zeroin** [comment]
When you hover directly on axis, it shows tooltipHTML just like any sprite would show tooltip when hovered over it. The tooltip of a cursor does not use axis tooltipHTML. To format Date axis tooltip, differently than the axis labels you can use `axis.tooltipDateFormat`. Hoever at the moment there is no way to have HTML there, we will think if we'll add this in the future.

**Comment by martynasma** [comment]
Please refer a solution using an adapter:
https://github.com/amcharts/amcharts4/issues/619#issuecomment-667836990
