### ISSUE TITLE
Is it possible to just change the Pointer color background color, Just the arrow symbol

### ISSUE THREAD

**Issue by amorouscreations** [amcharts/amcharts4#1411]
I am looking to change the tip color of just the small tip arrow (Red in attached Screenshot attached). Is this possible to do 

Code pen for testing https://codepen.io/team/amcharts/pen/XqPbYd

![image](https://user-images.githubusercontent.com/40366852/60331692-dd726180-99b2-11e9-9b3e-7fce7e3a5578.png)

**Comment by zeroin** [comment]
No, it is not possible - the pointer and body is one shape.
