### ISSUE TITLE
minGridDistance gives weird chart

### ISSUE THREAD

**Issue by xbaha** [amcharts/amcharts4#1412]
I am using minGridDistance=1 on data range (1 to 5)
the scale should be normal, but the chart has many axis lines, not sure if this is the normal behavior???

demo: https://codepen.io/xbaha/pen/orpxLv

**Comment by zeroin** [comment]
`minGridDistance` suggest the axis how many grid lines should be drawn. So the smaller the number the more grid lines you'll have. So for me the result seems normal.
