### ISSUE TITLE
RTL support for CSV export is lacking

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1414]
Hey I have created an example of RTL chart(Hebrew version), and I want to export it to csv.
apparently when I export to csv, the hebrew labels shows as junk characters(gibberish).
The rtl feature is enable, so I have no explanation why the output is  junk characters(gibberish).

![image](https://user-images.githubusercontent.com/5408870/60394098-77f3b180-9b27-11e9-906c-4c68a9a7a572.png)

Here is the example of the rtl chart:
https://codepen.io/Barak/pen/YoeNdE

Please confirm the identity of this issue:
Is this a bug or as designed or other?

**Comment by martynasma** [comment]
This looks like an Excel issue.

If I open exported CSV text in some text editor, the RTL text appears fine.

However, if I open it in Excel, I get garbage.

Have you tried opening other CSV files with RTL data in Excel?

P.S. data exported to XSLX opens fine in Excel.
