### ISSUE TITLE
In the ForceDirectedNetwork, is it possible to explicitly increase the distance of links between specified nodes without using the radius of the node?

### ISSUE THREAD

**Issue by brecriffs** [amcharts/amcharts4#1416]
![Screenshot from 2019-06-30 10-31-33](https://user-images.githubusercontent.com/49916905/60398082-4af0d000-9b22-11e9-95c4-89b28099d911.png)

I would like to have more space between the main nodes 'You and Your Teams' and 'The course'. I tried playing different radii, but I don't really want the nodes to be drastically large.

**Comment by brecriffs** [comment]
A feature for each node, that repels a list of other nodes, would be cool, and might work here. With the ability to set the strength on how much the nodes repel each other.

**Comment by Aterops** [comment]
I think you could do this by setting the distance. You can set a distance on the template at least.

var linkTemplate = networkSeries.links.template;
linkTemplate.distance = 1.3;

I assume you could configure the distance as part of your data object by setting a configField.

linkTemplate.configField = "configLink";

**Comment by brecriffs** [comment]
@Aterops 
Awesome, thanks! I didn't know about `linkTemplate.configField = "configLink"`. Seems like it only works on child to parent relationships/links, and if you just link two nodes using the 'link' array, this config doesn't work. Still worked for me for setting the distance though. Thanks again!
