### ISSUE TITLE
Hiding treemap tooltip

### ISSUE THREAD

**Issue by mNadimMat** [amcharts/amcharts4#1417]
Hello community,
I need to remove the Treemap's default tooltip that gets displayed on hover.
Thank you in advance

![image](https://user-images.githubusercontent.com/34912814/60429869-ea31c800-9bf3-11e9-8f2a-42a0eb1bef91.png)

**Comment by zeroin** [comment]
There are two ways:

1) disable series template tooltip: `level0SeriesTemplate.tooltip.disabled = true;`
2) set `tooltipText` to "": level0SeriesTemplate.columns.template.tooltipText = ""; 

you might need to do this on all level templates.
