### ISSUE TITLE
Automatically order columns

### ISSUE THREAD

**Issue by thalescifal** [amcharts/amcharts4#1418]
Is there any way to organize the columns in order by passing the reference?

Example: chart.OrderBy = "reference"

This tutorial is from version 3, needed a simplified form of version 4
https://www.amcharts.com/docs/v3/tutorials/automatically-order-columns-value/

**Comment by zeroin** [comment]
You can simply sort your chart data with some compare method, like in this pen:
https://codepen.io/team/amcharts/pen/QXmRxp?&editable=true

```function compare( a, b ) {
  if ( a.country < b.country ){
    return -1;
  }
  if ( a.country > b.country ){
    return 1;
  }
  return 0;
}

chart.data.sort(compare)```

**Comment by Mahisandy** [comment]
it's not working when we parse the a,b then only it work

function ascendingSort(a, b) {
               // return a - b;
                if (parseInt(a.Values) < parseInt(b.Values)) {
                    return -1;
                }
                if (parseInt(a.Values) > parseInt(b.Values)) {
                    return 1;
                }
                return 0;
            }
