### ISSUE TITLE
Manipulating color of individual bullets of a series dynamically (like on Mouse hover)

### ISSUE THREAD

**Issue by Vivek-Nehra** [amcharts/amcharts4#1419]
How do we change the color of a single bullet of any series (specifically Bullet chart) on some event occurence not associated with respective bullet (like mouse hover) ... I can identify the index and the series of the particular bullet but can't seem to change any of it's values like color ... Please help

**Comment by zeroin** [comment]
Here is how you do it:

1) get the `dataItem` of series
2) `dataItem` has a dictionary `bullets` where key is your bullet template's uid. 

For example:

`series.events.on("validated", function(){
  series.dataItems.getIndex(5).bullets.getKey(bullet.uid).fill = am4core.color("#ff0000")
})`

**Comment by Vivek-Nehra** [comment]
Thanks for the reply .. I tried what you said and apparently it changes the bullet color value but the change is not reflected in the UI. I am not using the validated event on the series to change the color , rather 'selectended' event of the cursor .. So can you help me figure out why the change is not reflected back in UI and how to fix it

**Comment by Pauan** [comment]
@Vivek-Nehra Can you share your full code, so we can figure out what the problem is?

**Comment by Vivek-Nehra** [comment]
Sorry I cannot put the entire code as it's very long .. But the relevant part is :

chart.cursor.events.on('selectended', ev =>

 // SOME CALCULATION

chart.series.values.map(val => {
    val.dataItems.values.map( each => {
        console.log(each.bullets.getKey(bullet.uid));
      })
}));

the console log statement is giving undefined ... Can you help me with why ( if i console log bullet.uid that is getting the correct id though)

**Comment by Pauan** [comment]
@Vivek-Nehra You can't use `val.bullets.template.uid`.

You mentioned that you know the series index and the bullet index. If so, then you can just do this:

```js
chart.cursor.events.on('selectended', ev => {
    chart.series.getIndex(seriesIndex).dataItems.getIndex(bulletIndex).bullets.each((key, bullet) => {
        bullet.fill = "red";
    });
});
```

In this case `seriesIndex` is the index of the series, and `bulletIndex` is the index of the bullet.

**Comment by Vivek-Nehra** [comment]
It worked ... Thanks a lot I was trying to do this for the past 1 week .. Instead of using bulletIndex, I used uid of bullets only and not from the template (bullets.values[0].uid -- as I have only 1 type of bullet per series) .. Now I can easily change the color of individual bullets

**Comment by Pauan** [comment]
Great, glad I could help.
