### ISSUE TITLE
Line chart overflows chart area when strictMinMax is set to true

### ISSUE THREAD

**Issue by c-eliasson** [amcharts/amcharts4#1420]
If we create a line chart where the x-axis is a date axis with set `min` and `max` values, then if we set `strictMinMax` to `true` the line chart will overflow the chart area and the last datapoint won't be visible because it is drawn outside the visible chart area.

I've put together [a codepen](https://codepen.io/anon/pen/BgxaRZ) that demonstrates this behaviour. In the codepen `strictMinMax` is `true`, and the last data point is not visible - if `strictMinMax` is set to `false` then the chart renders as expected.

Adding the code to reproduce this behaviour in the issue as well, if codepen goes missing for some reason:

```javascript
const chart = am4core.create('chartdiv', am4charts.XYChart)

const dateAxis = chart.xAxes.push(new am4charts.DateAxis())
dateAxis.renderer.labels.template.fontSize = 12
dateAxis.dataFields.data = 'date'
dateAxis.min = new Date('2019-06-28')
dateAxis.max = new Date('2019-07-02')

// Setting this to false will generate correct output
dateAxis.strictMinMax = true

dateAxis.renderer.grid.template.disabled = true

const valueAxis = chart.yAxes.push(new am4charts.ValueAxis())
valueAxis.renderer.labels.template.fontSize = 12
valueAxis.renderer.grid.template.disabled = true
valueAxis.title.text = `per day`
valueAxis.cursorTooltipEnabled = false

chart.cursor = new am4charts.XYCursor()
chart.cursor.lineY.disabled = true
chart.cursor.behavior = 'zoomXY'

const series = chart.series.push(new am4charts.LineSeries())
series.tooltipText = `click: {click}`
series.name = `click per day`
series.dataFields.dateX = `day`
series.dataFields.valueY = `click`
series.yAxis = valueAxis
series.strokeWidth = 2

const bullet = series.bullets.push(new am4charts.CircleBullet())
bullet.strokeWidth = 2
bullet.fill = am4core.color('#fff')

chart.cursor = new am4charts.XYCursor()
chart.cursor.lineY.disabled = true
chart.cursor.xAxis = dateAxis

chart.data = [
  { day: '2019-06-28', click: 5 },
  { day: '2019-06-29', click: 0 },
  { day: '2019-06-30', click: 1 },
  { day: '2019-07-01', click: 2 },
  { day: '2019-07-02', click: 1 },
]
```

**Comment by zeroin** [comment]
It seems everything normal here, you should set max to the end of the day or the 2019-07-03 in order the last date to be fully visible, as new Date('2019-07-02') is the beginning of the July 2nd.

**Comment by c-eliasson** [comment]
@zeroin  That makes sense, I guess. I doesn't seem to do any difference though. I made a fork of the codepen where I change the max date to `new Date('2019-07-03')` but that doesn't make a difference. I've also tried to extend the max date even further, but as long as `strictMinMax` is set to `true`, the chart is cropped of.

Here is the updated codepen: https://codepen.io/anon/pen/qzYRaz

**Comment by zeroin** [comment]
Sorry, I haven't noticed - you must pass numbers for min and max values:

`dateAxis.min = new Date('2019-06-28').getTime();
dateAxis.max = new Date('2019-07-03').getTime();`

**Comment by c-eliasson** [comment]
@zeroin Ahh thanks! I totally missed that. I just assumed that since the Axis is a `DateAxis`, the min / max values would actually be `Date` objects. 

Looking closer at the [docs](https://www.amcharts.com/docs/v4/reference/dateaxis/#min_property) it explicitly says it should be a `Number`.
