### ISSUE TITLE
chart.exporting.getImage('svg') returns a png image

### ISSUE THREAD

**Issue by samuel-p** [amcharts/amcharts4#1422]
I want to use `chart.exporting.getImage()` to get a svg image. But `getImage('svg')`returns a png image instead of a svg, because the returned string starts with `data:image/png;base64,iVBORw0...`.

[Here](https://codepen.io/anon/pen/gNzwre) is a code pen, which shows the current behavior.

**Comment by martynasma** [comment]
`getImage()` method is for bitmap exports.

To export SVG use `getSVG()` instead.

https://www.amcharts.com/docs/v4/reference/export/#getSVG_method

**Comment by samuel-p** [comment]
Thanks for your answer. I wasn't aware of the `getSVG()` method.
