### ISSUE TITLE
How do you make funnel chart start at 100%?

### ISSUE THREAD

**Issue by Reddian** [amcharts/amcharts4#1423]
Hello! I looked through the issues here and found that no one answered piernik's question: https://github.com/amcharts/amcharts4/issues/703

How do you get the funnel chart to start at 100% then show the percentage of the previous step? This chart is intended to show drop off of web traffic.

Is the only option to create a pre-processor script or is there an option I'm missing?

Thanks.

**Comment by zeroin** [comment]
Here is a pen which solves this issue with with adapters: https://codepen.io/team/amcharts/pen/Gbdvqy
