### ISSUE TITLE
How to create Aggregate Traceable Sankey Diagram?

### ISSUE THREAD

**Issue by bigredbug47** [amcharts/amcharts4#1425]
Hi all,

I'm working with Sankey Diagram, I want to create the Sankey chart that can traceable when click or hover in flow. Does the Amcharts library could solve it? I have researched but only found multi-level drill-down Sankey. 

Here is some images about my expectation chart: 
<img width="410" alt="sankey1" src="https://user-images.githubusercontent.com/31086329/60574122-2c4d3c00-9da3-11e9-966a-4592370024f5.PNG">
<img width="424" alt="sankey2" src="https://user-images.githubusercontent.com/31086329/60574157-3f600c00-9da3-11e9-8b41-456363a256e5.PNG">

Thanks

**Comment by zeroin** [comment]
I created a demo: https://www.amcharts.com/demos/traceable-sankey-diagram/
The idea is that you assign id with the same beginning for each link and when hovered, loop through all links and set `isHover = true` for those who have the same beginning of an ID. It would be also possible to do the same trick by assigning unique color for each flow, in case it's ok for your links to have different colors.

**Comment by bigredbug47** [comment]
Nice, it worked perfectly as my expectation. Thanks a lot.

**Comment by MatPike** [comment]
Is there a link to the complete working .js file? The page seems to not display the complete js, only up to line 119 and i cannot get the example to work.
