### ISSUE TITLE
TreeMap TreeMapSeries strokeWidth issue

### ISSUE THREAD

**Issue by jordidiaz** [amcharts/amcharts4#1426]
Hi,

In cases that the value data difference is too big (say 1/500 ratio) and when using a 5px strokeWidth (for example) the small portion of TreeMap's column just disappear. 

Any solution?

See the example here: https://codepen.io/syspunch/pen/ydEYNz

You can play changing:

`
level0SeriesTemplate.strokeWidth = 5;
`

Thanks in advanced.

**Comment by zeroin** [comment]
I am afraid the only solution is to use a very small strokeWidth value.
