### ISSUE TITLE
Question: how to use 2 value axes with tooltips working? 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1427]
Date, duration, and categories work great. But how about when you have 2 value axes. 

I read https://github.com/amcharts/amcharts4/issues/898 

But I don't understand the limitation behind it

**Comment by zeroin** [comment]
Could you create a codepen with your chart and describe the problem?

**Comment by jimmykane** [comment]
@zeroin  Take a look at the codepen of #989 

here https://codepen.io/anon/pen/jdBvLm

When there are 2 value axes there are no tooltips for series. 

But having 2 value axes is a common case eg when you want to add distance vs speed and many physics line chart needs. 

I am kindly asking if there is a limitation why amCharts does not work when you have 2 value axes like it would work if you have 1 category axis + 1 value axis etc.

**Comment by zeroin** [comment]
Oh, I thought that you have some combination with two value axes of the same direction. With X and Y value axis series tooltips do not work, it's not implemented. The main reason is that it's indeed quite costly procedure, as you have to loop through all the data items of series, calculate distance from mouse to each data point and show tooltip of a nearest data item, not like with date or category axis (take a look at https://www.amcharts.com/demos/zoomable-bubble-chart/ and imagine a lot more bubbles). What you did in your example is quite the same as how we would do it. I promise to consider adding this as a build-in feature.

**Comment by jimmykane** [comment]
That would be great. I understand it's doable but it feels safer if it's native :-D

**Comment by jimmykane** [comment]
Hi, @zeroin and @martynasma  I don't understand why the tooltip needs nearby data. 

When having 2 value axis I am assuming that there is no extrapolation of values. 

So for example if a series has this set: 
```
distance: 5
heartRate: 160
```

And another series has 
```
distance: 10
speed: 20
```

where is the problem exactly ?

**Comment by martynasma** [comment]
@jimmykane We're still figuring out how to do it intelligently, without mindlessly sifting through all of the data.

Just wanted to reassure you that it's not forgotten. We'll get there.

**Comment by jimmykane** [comment]
Thank you @martynasma very much. No rush I was just wondering. 

I have played a LOT with the data structures and similar issues to power up my app's engine, I know it can be tricky.

**Comment by jimmykane** [comment]
Hey hi @martynasma and @zeroin , just checking, is this released (somehow I remember another issue closed related to this).

**Comment by zeroin** [comment]
If you set `chart.cursor.snapToSeries = series` the tooltip will be snapped to the nearest point with both x and y value axes. The limitation is that it will work with one series only.

**Comment by jimmykane** [comment]
hmmm this does not work very well :-/ 

The cursor lines jump all over the place

**Comment by martynasma** [comment]
@jimmykane There's something wonky with `snapToSeries` going on, probably bug. We're looking into this.

**Comment by martynasma** [comment]
Heads up, 4.7.7 (released just now) fixes tooltip jumping.

**Comment by mdorion1** [comment]
It is not fixed when both xAxis and yAxis are a ValueAxis. Tooltips are not showing

**Comment by martynasma** [comment]
@mdorion1 Can you post a CodePen of the chart you are still having issues with?

**Comment by mdorion1** [comment]
> @mdorion1 Can you post a CodePen of the chart you are still having issues with?

No problem, i'll try to do a simple codepen tomorrow.

**Comment by mdorion1** [comment]
Here is the codepen:

https://codepen.io/mdorion1/pen/bGdbbJW

thanks

**Comment by kozga** [comment]
Codepen from #898: https://codepen.io/kozga/pen/JjdEVEG

Using "chart.cursor.snapToSeries" allows to show a tooltip to a series near the mouse cursor, but I find its behavior a little strange. The tooltip should appear at the point of the series which has x coordinate closest to the x coordinate of the mouse cursor. Regardless of the mouse y coordinate.
Now it seems to scan y axis in a very limited range relative to mouse y, and if it doesn't find a point on the series in this range, the tooltip appears at the point that has the closest y, but completely different x (which can result in showing a tooltip at the other side of the screen than the mouse cursor).

**Comment by zeroin** [comment]
For a chart with two value axes, the cursor searches for the nearest data point to the cursor. This is by design and we will not change it, sorry. 

And since todays release you can provide array of series to the `snapToSeries` property, so @mdorion1  could try to use it.

**Comment by mdorion1** [comment]
Thanks, i'll check that today.

**Comment by kozga** [comment]
> For a chart with two value axes, the cursor searches for the nearest data point to the cursor.

What exactly means 'the nearest data point'? On the attached screenshot tooltip is not at data point nearest to the cursor.

![obraz](https://user-images.githubusercontent.com/22498983/75249403-8d180180-57d6-11ea-87d9-70bfc6c3259c.png)

**Comment by jimmykane** [comment]
@kozga  what do you mean? I see it's in the nearest

**Comment by jimmykane** [comment]
@zeroin  I am getting strange UI when enabling this 
<img width="956" alt="Screenshot 2020-02-25 at 14 44 14" src="https://user-images.githubusercontent.com/1268723/75252608-572a4b80-57dd-11ea-9e0f-874620b72b3f.png">

**Comment by zeroin** [comment]
We were modifying this feature in this release, I guess something went wrong. I am looking at it now.

**Comment by kozga** [comment]
@jimmykane One picture is worth a thousand words :)

![obraz](https://user-images.githubusercontent.com/22498983/75254179-3e6f6500-57e0-11ea-9b81-02b22f6e2aa5.png)

**Comment by zeroin** [comment]
@kozga Could you share the code of the chart where you reproduced this?

**Comment by kozga** [comment]
> @kozga Could you share the code of the chart where you reproduced this?

https://codepen.io/kozga/pen/JjdEVEG

**Comment by zeroin** [comment]
We released an update (4.9.3)where this should be fixed

**Comment by dhiren-eng** [comment]
> Date, duration, and categories work great. But how about when you have 2 value axes.
> 
> I read #898
> 
> But I don't understand the limitation behind it

@jimmykane Are you sure that the tooltip will show fine with Duration axis as X axis (and Value as Y axis) while it is inheriting from value axis ? Because after removing snapToSeries for duration axis the tooltip does not show ..
