### ISSUE TITLE
Partitioned bar chart overlapping values

### ISSUE THREAD

**Issue by ttran1904** [amcharts/amcharts4#1429]
Hi, I have a question regarding overlapping partitioned bar chart values.

I am trying to create a partitioned bar chart on topic-words distribution. The separated category is Topic (1, 2, 3, 4) and each bar represent a word's distribution. However, some words appear in multiple topics, for example word 1, word 4, and word 5.

My JSONObjects clearly indicate words that belong to each topic, even if they appear in multiple topics:

`{"Topic":"1","distribution":0.009,"word":word 1"}` 
and
`{"Topic":"2","distribution":0.0533,"word":"word 1"}`

How do I make repeating words not stack on each other or conflict?

This is my code:

![image](https://user-images.githubusercontent.com/49138332/60640773-f8315400-9e52-11e9-966d-c867013e2c03.png)
![image2](https://user-images.githubusercontent.com/49138332/60640774-f8315400-9e52-11e9-8910-45bca0d2ec6e.png)
![image3](https://user-images.githubusercontent.com/49138332/60640775-f8c9ea80-9e52-11e9-94ec-71a78ccbb952.png)
![image4](https://user-images.githubusercontent.com/49138332/60640777-f8c9ea80-9e52-11e9-8ddc-0385751c96fc.png)

My result is this:

![image5](https://user-images.githubusercontent.com/49138332/60640878-7130ab80-9e53-11e9-9744-8ee9469b2b25.png)

I want my result structured similar to the sample online:

![image6](https://user-images.githubusercontent.com/49138332/60640881-7130ab80-9e53-11e9-8921-8658ceea83c4.png)

**Comment by zeroin** [comment]
To solve this, you should add some id or something to your categories in data and then add another field like "name" which would not have this id, just the real category. And use this field for the labels, tooltips etc. Here is an example: https://codepen.io/team/amcharts/pen/jjpBxQ

**Comment by ttran1904** [comment]
@zeroin Thank you so much. That works great! :)
