### ISSUE TITLE
Question: v4 equivalent to v3 ShowNextAvailable cursor property 

### ISSUE THREAD

**Issue by thunderbolt10** [amcharts/amcharts4#1430]
I have multiple data series with different horizontal data point and want to show tooltips for all series to the nearest X value for that series.
 
Is there an equivalent cursor property to what we had with v3 ChartCursor?

> showNextAvailable | Boolean | false | If true, the graph will display balloon on next available data point if currently hovered item doesn't have value for this graph.

**Comment by zeroin** [comment]
Try setting `series.snapTooltip = true;`

**Comment by thunderbolt10** [comment]
This does not behave the same though if you have multiple series as it only shows a single tooltip in this [example pen](https://codepen.io/thunderbolt10/pen/VJBmyx)

snapTooltip gives us:
![image](https://user-images.githubusercontent.com/30114322/60667784-4732b580-9e62-11e9-95a6-53c99d5745b2.png)

We would like two tooltips shown as in:
![image](https://user-images.githubusercontent.com/30114322/60667931-a395d500-9e62-11e9-96e6-349bd1a8be4c.png)

thanks.

**Comment by zeroin** [comment]
I forgot to mention, that in order this to work, you need to set `dateAxis.snapTooltip = false;`

**Comment by thunderbolt10** [comment]
That works!
```
dateAxis.snapTooltip = false;
series.snapTooltip = true;
```
Thanks.
