### ISSUE TITLE
Chart Legend Content width does not get updated when using value axis and an external container for the legend. 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1431]
I have a legend set on an external container. 

I listen to the chart maxSizeChanged event and as per instructions I change the size of the container like so: 

```
      ev.target.chart.legend.svgContainer.htmlElement.style.height = this.chart.legend.contentHeight + 'px'; // @todo test

```

However, when I have only 2 value axis (x,y) for the chart the 
```

      console.log(this.chart.legend.contentHeight)
      console.log(this.chart.legend.contentWidth)
```

Remain the same and the values of height and width dont change. 

This works fine if the axis is category or date or duration

**Comment by zeroin** [comment]
Could you show chart setup? As the demo in our tutorial works fine, I need to see the exact case in order to help. A codepen would be best - thanks!
