### ISSUE TITLE
Question - how to not order y axis category alphabetically

### ISSUE THREAD

**Issue by yehudahkay** [amcharts/amcharts4#1433]
Hi I am using the category axis as the y axis on a column chart. The chart automatically orders the categories alphabetically. Is there a way to order by value or not change the order of the data? Thank you.

**Comment by zeroin** [comment]
No, it should't order category axis items. I could help, but I need to see the working example of a chart, a codepen would be best.

**Comment by yehudahkay** [comment]
Sorry this was my fault, perhaps a confusing factor is that the y axis flips the order of the data :-)
