### ISSUE TITLE
Property 'series' does not exist on type 'Scrollbar'. Angular 7

### ISSUE THREAD

**Issue by pushprajchaudhary** [amcharts/amcharts4#1443]
![Screenshot 2019-07-08 at 12 24 40 PM](https://user-images.githubusercontent.com/24788190/60788918-70618780-a17b-11e9-93a2-5dcf1a48877b.png)

**Comment by martynasma** [comment]
If you need to add series to a scrollbar you need to use `XYChartScrollbar` not `Scrollbar`.

**Comment by osman144** [comment]
I'm using `XYChartScrollbar` but still seeing this issue. 

<img width="733" alt="Screen Shot 2019-09-17 at 7 26 33 PM" src="https://user-images.githubusercontent.com/25594064/65089111-8bbdef80-d981-11e9-857f-6f912ed5f12b.png">

**Comment by nineforty5** [comment]
```
let scrollbarX = new am4charts.XYChartScrollbar();
     scrollbarX.series.push(series);
     chart.scrollbarX = scrollbarX;
```

**Comment by azflin** [comment]
Why is this issue closed? I have the same issue.
