### ISSUE TITLE
Can not set ID for MapLine objects in a MapLineSeries

### ISSUE THREAD

**Issue by vfauth** [amcharts/amcharts4#1444]
Hi,
I am using JSON-based config and amCharts 4.4.4 (I had this issue with previous versions already).

I have a MapChart on which I add three series: countries, images and lines.
For the images, I can use `mapImages.propertyFields.id` to set image IDs.
But for the lines, I try to use `mapLines.propertyFields.id` to set IDs and dummyData. It works fine for dummyData. But if I try to set IDs, amCharts fails with `Duplicate id (<first ID here>) used on multiple objects.`

I checked, my IDs are unique.
I tried with string IDs like `A<>B` and `A_B`, and then I tried with integers, same result.
Removing the images IDs do not improve the situation.

**Comment by martynasma** [comment]
Would you be able to post your map setup as a demo on codepen or jsfiddle?

I can't seem to be able to reproduce this issue:
https://codepen.io/team/amcharts/pen/92d5b8076c5a3aecf20f29a2094d7a97

**Comment by vfauth** [comment]
After rewriting our backend, that issue disappeared. We probably had something wrong with our data.

Sorry for the inconvenience.
