### ISSUE TITLE
Is it possible to disable a node as soon as the Sankey chart is loaded?

### ISSUE THREAD

**Issue by antonio-prigl** [amcharts/amcharts4#1445]
Hi all!

The amcharts sankey nodes can be toggled on and off by default. What I want to do is have some of the nodes turned off as soon as the sankey is initialized so that it looks like this when it loads:
<img width="1802" alt="Screenshot 2019-07-08 at 23 24 02" src="https://user-images.githubusercontent.com/39717838/60843635-86049a80-a1d7-11e9-8505-5d135893c446.png">

Is this possible? 
Thanks!

**Comment by martynasma** [comment]
Yes, it is possible using `propertyFields` of node template.

```
nodeTemplate.propertyFields.hidden = "disabled";
```

The above basically means: "look for a value in 'disabled' key on data and if it's `true` show node pre-hidden.

Example:
https://codepen.io/team/amcharts/pen/ydQrMb

**Comment by antonio-prigl** [comment]
Thank you so much!
I've been trying to figure this out for hours.

**Comment by JasonAskew** [comment]
This only works when a node only has one link
