### ISSUE TITLE
Large data issue with force directed tree

### ISSUE THREAD

**Issue by herinlakdawala** [amcharts/amcharts4#1446]
I have a requirement to show 1k nodes on scree and all together at same time with different scenarios as below:
1. 1k nodes within single parent node.
2. 1k nodes distribute(uniformly/non-uniformly) among different parent nodes.
(Note: none of the node should overlap)
For scenario 1, I have created demo on pen for same. It takes more than hour to load nodes. Is there any way to optimize the performance?
https://codepen.io/herin0506/pen/pXxXyo

For scenario 2, I am unable to show more than 3 clusters(each contain 1 parent and each parent contain 175 child nodes) on screen and cluster float away from one another. Hence unable to accommodate all clusters(6 clusters) on single screen within few seconds.
![02_3clusters525nodes](https://user-images.githubusercontent.com/19507887/60956970-742f0e80-a321-11e9-8ae4-ac262d4da8b5.png)

Feel free to get more details. The quick support is highly appreciated.

**Comment by martynasma** [comment]
I'm afraid ForceDirected chart is quite resource intensive and is not not compatible with large amounts of data. I don't think we can offer any insights into how to solve this :(

**Comment by herinlakdawala** [comment]
> I'm afraid ForceDirected chart is quite resource intensive and is not not compatible with large amounts of data. I don't think we can offer any insights into how to solve this :(

Thanks @martynasma . Can you suggest some other alternative to accommodate the usecase where a cluster with thousand data points can be efficiently be plotted(in single cluster of multiple cluster)?

**Comment by martynasma** [comment]
Ummmm... maybe a drill-down TreeMap?

https://www.amcharts.com/docs/v4/chart-types/treemap/
