### ISSUE TITLE
Bar graph issue for selecting a bar or corresponding label

### ISSUE THREAD

**Issue by herinlakdawala** [amcharts/amcharts4#1447]
When selecting particular bar or label corresponding to the bar graph the the selected bar should be highlighted and on selecting other bar graph the previous needs to set at its initial state and the newly selected should be highlighted in order o distinguish the active selection of bar graph.

 categoryAxis.renderer.labels.template.adapter.add("text", function (text, target) {
      target.events.on("hit", (ev) => {
        categoryAxis.renderer.labels.template.fontWeight = "100";
        ev.target.fontWeight = "bold";
        let text = `${target.currentText}`;
        getClickedGraph(text);
      })

The above code, on selection of a lable 1st time changes the font weight of all the lables of graph and holds the selected. And then on succeeding selections the previously highlighted(bold) label do not get unselected. Instead all the succeeding selections keep all the previously selected labels bold and hence no differentiation between active bar graph.

Is there any way to change the background color of selected bar graph and changing it to initial state when selecting other bar in same graph.

(Note: here selecting is referred to click event and not hover as on clicking the data description is to be display on screen based on selected bar or corresponding label of graph.)

**Comment by martynasma** [comment]
Something like this?
https://codepen.io/team/amcharts/pen/KjjPzP?editors=0110

**Comment by herinlakdawala** [comment]
> Something like this?
> https://codepen.io/team/amcharts/pen/KjjPzP?editors=0110

I tried the same code snippet from pen with latest version of amcharts4 (4.5.6). I get below error:
![Error](https://user-images.githubusercontent.com/19507887/61359335-bdd7a600-a899-11e9-83af-84f6a4336021.png)

**Comment by martynasma** [comment]
That's just your compiler trying to keep you safe since `XYChart.series` can contain any type of series, not just `ColumnSeries`.

Since you know you have only `ColumnSeries` in there, you can just typecast it:

```
(<am4charts.ColumnSeries>series).columns.each(function(column) {
```

Or better yet add a check:

```
function highlighColumn(ev) {
  chart.series.each(function(series) {
    if (series typeof am4charts.ColumnSeries) {
      series.columns.each(function(column) {
        if (column.dataItem.categoryX == ev.target.dataItem.category) {
          column.isActive = true;
        }
        else {
          column.isActive = false;
        }
      })
    }
  })
}
```

**Comment by herinlakdawala** [comment]
@martynasma still no luck. Some other error pops up. May be its integration with Angular7 is issue.

**Comment by martynasma** [comment]
What is that other error?

P.S. I doubt it's due to Angular.
