### ISSUE TITLE
large data issue with bargraph rendering

### ISSUE THREAD

**Issue by herinlakdawala** [amcharts/amcharts4#1449]
i tried plotting 1k bars in graph and the graph looks as the attached screenshot. Post scrolling a bit the data gets arranged and bars looks clear.

Suggest any workaround to load the bars properly on load.
![all-system1](https://user-images.githubusercontent.com/19507887/60956684-eb17d780-a320-11e9-92c5-80924829d4fb.png)

**Comment by martynasma** [comment]
Can you share your code in form of a codepen or jsfiddle so that we know what you are doing?

**Comment by herinlakdawala** [comment]
> Can you share your code in form of a codepen or jsfiddle so that we know what you are doing?

Attached is the code pen as requested.
https://codepen.io/herin0506/pen/agPeZL

**Comment by martynasma** [comment]
Thank you.

Having so many columns is not very resource efficient.

A few questions:

Is this a real data? If that is so, do you think it's useful for a user at all, having to scroll a long way to see specific category of interest?

Would you consider replacing `ColumnSeries` with a `StepLineSeries`? That would increase performance dramatically.

https://codepen.io/team/amcharts/pen/b1306377ab1e1a93fae4f9b7e61db5d5

Finally, with so many items, it would make sense disabling "animated" theme.
