### ISSUE TITLE
determine Time after zooming

### ISSUE THREAD

**Issue by nima-rnd** [amcharts/amcharts4#1451]
my date is in "YYYY-MM-DD HH:mm:ss" format as you can see 
![Screenshot (373)](https://user-images.githubusercontent.com/29012958/60956705-92444100-a318-11e9-91b0-38d349b4caf2.png)
but my chart couldn't understand the time of the day for  example in 24th April I have 6 value in 6 different times but after zooming all values are in 00:00
![Screenshot (372)](https://user-images.githubusercontent.com/29012958/60956892-e8b17f80-a318-11e9-8ea3-17389d28a654.png)
please help how I can fix it  (amcharts v4)
`  let dateAxis = chart.xAxes.push(new am4charts.DateAxis());
          dateAxis.renderer.grid.template.location = 0;
          chart.dateFormatter.dateFormat = 'YYYY-MM-DD  HH:mm:ss';
          dateAxis.dateFormats.setKey("day", "MMM dt");
          dateAxis.dateFormats.setKey("minute", "mm");
          dateAxis.dateFormats.setKey("hour", "HH:mm");
          dateAxis.periodChangeDateFormats.setKey("minute", "mm");
          dateAxis.baseInterval={ timeUnit: "minute",count:"30" };`

**Comment by martynasma** [comment]
Can you post your chart in codepen or jsfiddle so that we can take a look at its full setup?

**Comment by nima-rnd** [comment]
I changed my date to timestamp and everything is ok now.
