### ISSUE TITLE
amCharts cursor zoom not work in openlayers overlay

### ISSUE THREAD

**Issue by abmohajeri** [amcharts/amcharts4#1454]
I added amCharts chart to openlayers map overlay but chart cursor zoom not work like gif provided below:
[gif](https://i.stack.imgur.com/Ck81e.gif)

you can see exampe here:
https://jsfiddle.net/abmohajeri/xchqb5mj/18/

question on stackoverflow:
[https://stackoverflow.com/questions/56984380/amcharts-cursor-zoom-not-work-in-openlayers-overlay](url)

**Comment by abmohajeri** [comment]
any idea?

**Comment by martynasma** [comment]
Not seeing any chart in your fiddle. Can you make the modifications so that it shows?

**Comment by abmohajeri** [comment]
@martynasma tnx for your response, please click on every where on the map and overlay will be shown and chart is in the overlay.

**Comment by abmohajeri** [comment]
@martynasma @Pauan @amcharts Any Idea? i think this is a bug

**Comment by abmohajeri** [comment]
this issue answered in stackoverflow.
