### ISSUE TITLE
4.5.3: PieSeries.legendSettings.valueText cannot be disabled

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#1456]
In version 4.5.3, `PieSeries.legendSettings.valueText` seems to always require a value and if not specified, will use the default value `"{value}"`. If I use an empty string `""`, it gets ignored and uses the default value instead. The only way I seem to be able to get rid of it is by using an empty space `" "`. However, this still creates the element and occupies space. 

Hijacking an exist example here:
https://codepen.io/team/amcharts/pen/Vdweaq

Replace: `pieSeries.legendSettings.labelText = "{category} {value.percent}%";`
With: `pieSeries.legendSettings.valueText = "";`

The values remain. Add a space to make them "go away" but the spacing remains:
`pieSeries.legendSettings.valueText = " ";`

For my use-case, I don't need to display a value and the legend items should be lining up horizontally snug next to each other below the chart. With extra empty space, it creates too much distance between the items and there is no way to adjust margins.

So my expectation would be that if I pass an empty string `""`, the element would not be created at all, therefore freeing up the space. The obvious workaround would be to create a custom legend but is that the expected way to do it?

TIA!

**Comment by martynasma** [comment]
If I understand you corrently, the following should do the trick:
```
chart.legend = new am4charts.Legend();
chart.legend.position = "bottom";
chart.legend.valueLabels.template.disabled = true;
```

https://codepen.io/team/amcharts/pen/9c05ee5f7c8eebc07e7854d651968db6

**Comment by sassomedia** [comment]
@martynasma That is exactly what I was looking for but of course, was looking in the wrong place. Thanks a lot!
