### ISSUE TITLE
Display combined tooltip text near/on mouse cursor

### ISSUE THREAD

**Issue by b49015** [amcharts/amcharts4#1458]
I want to display a combined tooltip text of all series near mouse cursor. I tried chart level tooltipText, it starts showing the tooltip on mouse cursor but not the data values. How can I display the data values also?

chart.tooltipPosition = "pointer"
chart.tooltipText = "Chart Level: {categoryX}: [bold]{valueY} {value}[/]";
Please see an example at codepen: https://codepen.io/b49015/pen/orRLOj

**Comment by martynasma** [comment]
Do you mean you want to display values from **data items** in chart's tooltip?

I suppose you could use an adapter for that:

```
chart.tooltipText = " ";
chart.tooltip.label.adapter.add("textOutput", function(text, target) {
  var text = "";
  series.dataItems.each(function(item) {
    text += item.categoryX + ": [bold]" + item.valueY + "[/]\n";
  })
  return text;
});
```

https://codepen.io/team/amcharts/pen/96afd6e221531f84aa2199383a287689

**Comment by b49015** [comment]
ok, I am rephrasing my question. I want to display the data values in tooltip which should display near mouse cursor instead of on columns/bars 
I know with `chart.tooltipPosition = pointer` I can show tooltip on cursor position, but don't know how to show the data values of those columns/bars which are under current cursor position.

![demo_pic](https://user-images.githubusercontent.com/49409244/61231115-0764ab80-a749-11e9-9051-324f1685e314.PNG)

I hope you got my point.

**Comment by martynasma** [comment]
Have you tried the codepen I linked to?

**Comment by b49015** [comment]
Yes I saw your example. You are collecting all series data and then showing that same data in tooltip at every cursor position. 
But my case is different, I am looking for dynamic data in tooltip which depends upon cursor position.
e.g. in this demo there are 3 bars (research, marketing, distribution), 
* when I move cursor and "y-axis" line of cursor touches the "research" bar/cluster, a tooltip appears with text "Research: 450" on that bar. I want this exact text at crossing point of x-axis and y-axis lines of cursor.
* And when "y-axis" line of cursor touches the "Marketing" bar/cluster, a tooltip appears with text "Marketing: 1200" on that bar. I want this exact text at cursor position. similarly for 3rd bar.

I know my English is bad. Please tell me if you need more details.

**Comment by martynasma** [comment]
Gotcha. Updated the demo:

https://codepen.io/team/amcharts/pen/96afd6e221531f84aa2199383a287689?editors=0010

Is the behavior like you wanted it?

**Comment by b49015** [comment]
yes, this is exactly what I was looking for. Thanks a lot.
