### ISSUE TITLE
Ready event is too late, and hidding serie is not working inside it

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1460]
I want to hide/show my series depending on some checkbox, even after reloading it, so I'm using this event (Column Series):   
```
                                series.events.on('ready', () => {
                                    console.log('ready ' + name);
                                    const visible = $('#chart_container').find('input[value="'+valueKey+'"]').is(':checked');
                                    if(visible){
                                        series.show();
                                    }else {
                                        series.hide;
                                    }
                                });
```

The ready event is fired, but not only is fired after one second was shown but also the code to hide is serie is not working.

Using chart.events.on('ready' ... ) is working, but I see the glitch because al the series are shown at first, and the event is fired a few seconds later and then the series are hidden

**Comment by zeroin** [comment]
Try using series.hidden property for series to be initially hidden.
