### ISSUE TITLE
scrollbar with export  menu overlap on each other 

### ISSUE THREAD

**Issue by GRIM-AVENGER** [amcharts/amcharts4#1463]
I have created a multi-line chart with 'export' menu and 'scrollbarX'.
The export icon overlap on end of scrollbar.
In v3, I remember there was small gap between these two.
Can the similar functionality be provided in V4 as default behaviour?

![issue](https://user-images.githubusercontent.com/23376158/61198129-179f6b00-a6f6-11e9-9dc7-3a02f134aac9.PNG)

**Comment by martynasma** [comment]
Due to nature of how flexible amCharts 4 is, it's hard to select default padding settings that would work in all cases. We're trying to avoid using too much fuzzy logic.

I suppose your best bet is to set padding/margin of the chart manually, e.g.:

```
chart.paddingRight = 60;
```
