### ISSUE TITLE
slow performance about 100% Stacked Column Chart

### ISSUE THREAD

**Issue by mattlung** [amcharts/amcharts4#1465]
We are buiding a 100% stacked column chart which has many series(up to 100) and a dateAxis. User is able to switch between weekly and monthly view, the number of columns can be more than 200 on weekly view. The browser will become unresponsive when user selects weekly view.

Here is a demo with 87 series and 33 columns https://codepen.io/anon/pen/agebqj

**Comment by martynasma** [comment]
For this kind of usage, I strongly recommend using `StepLineSeries` instead.

It will be much faster.

https://codepen.io/team/amcharts/pen/0610925e2828395a9209261f0d56c41a

**Comment by mattlung** [comment]
Thanks. 🙏🙏🙏. It is still not smooth enough and we decided to use another canvas based chart library to render the chart with many elements.
