### ISSUE TITLE
Zoom on dateAxis with reversed date list breaks

### ISSUE THREAD

**Issue by nicolasthomas** [amcharts/amcharts4#1466]
I used the example code from: https://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/
and replaced the data with my own example data.
That data comes via ajax and it took me a while to notice why it didn't work: the oldest date is the first array element. This somehow breaks the zooming functionality. (Either drag-select a part of the chart or change the 'until'-date. Changing the 'from'-date works)
See this fiddle: http://jsfiddle.net/nicolas_thomas/mwyxovk8/9/
If your reorder the array, it works: http://jsfiddle.net/nicolas_thomas/mwyxovk8/10/

**Comment by zeroin** [comment]
I am afraid the data should be ordered ascending, the chart was not designed to work with descending data.

**Comment by nicolasthomas** [comment]
That's okay, but what about throwing an error if it's not correctly ordered? At first glance it seems to work and only breaks on zooming in. It's super tough to find the problem.

**Comment by martynasma** [comment]
Error checks is an additional processing overhead. For large data sets they might sum up in something noticeable.

I understand that it makes debugging harder, but once you know this fact, you may account for it by always pre-sorting your data.
