### ISSUE TITLE
Axis ranges in category axis

### ISSUE THREAD

**Issue by ModKub** [amcharts/amcharts4#1469]
Hi,
I created chart with axis ranges in category axis like nominal voltage, min and max alarm.
Here is an example https://codesandbox.io/s/amcharts-problem-mn8f6.
And that min and max alarm will be create by user. And I don't know it will be 253V or less like 250V.

How to create axis ranges not directly on predefined category axis ? It will be count dynamically and could be +9% of nominal volatge etc

And how to make +infinite to be visible ?

**Comment by matinfo** [comment]
Here example of what we try to achieve: 
<img width="895" alt="Screenshot 2019-07-17 at 13 46 58" src="https://user-images.githubusercontent.com/460827/61373428-16a73e80-a89a-11e9-9393-f50ce9017b2c.png">

**Comment by martynasma** [comment]
You can set Range's position within category using their locations setting:

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_locations

So if you have 9% you know you can set location to 0.5 and place it on 8% category.

That said, I'd say having `ValueAxis` as an X axis is probably a better solution.
