### ISSUE TITLE
Dependency not found: @amcharts/amcharts4-geodata/worldLow

### ISSUE THREAD

**Issue by sergiocastrovale** [amcharts/amcharts4#147]
I'm following the docs posted [here](https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/). This is my imports file (it's a Nuxt.js build):

```
import * as am4core from '@amcharts/amcharts4/core'
import * as am4maps from '@amcharts/amcharts4/maps'
import am4themesAnimated from '@amcharts/amcharts4/themes/animated'
import am4geodataWorldLow from "@amcharts/amcharts4-geodata/worldLow"
import Vue from 'vue'

am4core.useTheme(am4themesAnimated)

Vue.prototype.$am4core = () => {
  return {
    am4core,
    am4maps,
    am4themesAnimated,
    am4geodataWorldLow
  }
}
```

Everything works fine except the **worldLow** path doesn't exist. Should I be installing any external resources for that?

**Comment by martynasma** [comment]
Your code appears to be fine. It may be some pathing issue in your `package.json`, though. Like maybe you are linking directly to `.../worldLow` not the `amcharts4-geodata` package.

Can you check?

**Comment by sergiocastrovale** [comment]
@martynasma do I  need to get `amcharts4-geodata` separately? All I installed was amcharts4 via `npm install @amcharts/amcharts4`.

**Comment by martynasma** [comment]
Yes, it's a separate package.

We deliberately made it so because it will be relatively big (when we start adding more maps), so we did not want to include into main package and bloat up its size for those who don't need to use maps.

**Comment by sergiocastrovale** [comment]
@martynasma That makes sense but it's hard to tell that by reading the docs or the [README.md](https://github.com/amcharts/amcharts4), maybe that could be improved?

I still haven't had the chance to test it out with the 2nd package added on, will update and close if this is fixed as soon as possible.

**Comment by martynasma** [comment]
Agreed. Will update the docs accordingly.

**Comment by martynasma** [comment]
Added a section about geodata package here:
https://www.amcharts.com/docs/v4/getting-started/basics/#Map_files_Geo_data

Let me know if it makes sense to you.

**Comment by sergiocastrovale** [comment]
It does and everything is working as expected. Thanks!
