### ISSUE TITLE
Zoomin and zoom out makes the axis move to left.

### ISSUE THREAD

**Issue by GRIM-AVENGER** [amcharts/amcharts4#1471]
I have created a multiaxis chart.
I am also formatting numbers on value axis (valueAxis.numberFormatter.numberFormat = "# a").

I trie to zoom in and zoomout on the chart and encountred one abnormal behaviour-

1. Original chart
![BeforeZoom](https://user-images.githubusercontent.com/23376158/61371147-be7c3680-a8b1-11e9-9aa4-0e3f115c38c4.png)
-
Here you can see the standard gap between y axis and the legend name.

2. I tries to zoomed in the chart due to which the y axis changes (expected) and moved towards left to accommodate the big number(500m etc)-
![ZoomIn](https://user-images.githubusercontent.com/23376158/61371212-e075b900-a8b1-11e9-97c7-8febbfebc4c5.png)

3. After that I tries to zoomed out, and I expect the y axis to back to normal, but there is an extra gap between the y-axis and the axis name which was created in step 2.
![ZoomOut](https://user-images.githubusercontent.com/23376158/61371430-524e0280-a8b2-11e9-9540-24b2db4ea650.png)

I suppose zooming out should bring back the same chart as mentioned in Step 1.

**Comment by martynasma** [comment]
Would you be able to post your chart live on codepen or jsfiddle? It would be easier to figure out what's going on with the particular chart.

**Comment by GRIM-AVENGER** [comment]
I have updated the example mentioned in amchart4 documentation and I am able to reproduce it.

Here is the code pen-
https://codepen.io/Grim-Avenger/pen/bXbjWX

Just do a full zoom in and zoom out , and check the value axis, it will get displaced.

**Comment by martynasma** [comment]
Technically, it by design, so that axis does not jump when zooming.

Disabling axis' "ghost label" should fix that:

```
valueAxis.ghostLabel.disabled = true;
```

**Comment by GRIM-AVENGER** [comment]
Thank you. I tried it and its working for me.
