### ISSUE TITLE
How to reload chart with dataSource (event zoomended)

### ISSUE THREAD

**Issue by kevenjesus** [amcharts/amcharts4#1474]
Hey Guys,

I need every time the zoomended event is called, make a new request with the date range.

I was able to return the interval between dates and make the request, but I can not update the graph with this new period, I did not find anything about it in the documentation.

Can you help me? Thank you

**Comment by martynasma** [comment]
How about this?

https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/#Reloading_different_data

**Comment by kevenjesus** [comment]
Thanks for answering.

I did the implementation however the graph is not rendered with the new data, the requestion is working correctly.

```
chart.cursor.events.on("zoomended", function(event) {
            const chart = event.target.chart;
            const dateAxis = chart.xAxes.values[0]; 
            const series = chart.series.values[0];
            const range = chart.getUpdatedRange(dateAxis, event.target.xRange);
            const startItem = dateAxis.getSeriesDataItem(series, range.start).dataContext; 
            const endItem = dateAxis.getSeriesDataItem(series, range.end).dataContext;
            chart.dataSource.url = `http://localhost:3500/api/historyMeasurement/allVitalSigns/${self.state.ala}/${Number(self.state.leito)}?startDate=${startItem}&endDate=${endItem}&screen=graphic`
            chart.dataSource.load();
});
```

**Comment by martynasma** [comment]
Does the event kick in?

If it does, can you check the actual response of the URL? Maybe there's some error there which prevents data from being parsed.

**Comment by kevenjesus** [comment]
The request works the same url that initiates the graph, however there are 2 parameters of start date and end date that changes.

**Comment by martynasma** [comment]
Weird. Would you be able to post sample output of both the full and updated data?

If you can't post it publicly, you can email us at contact@amcharts.com

**Comment by kevenjesus** [comment]
Thanks @martynasma
