### ISSUE TITLE
phantomJS, exporting issue

### ISSUE THREAD

**Issue by awindHydro** [amcharts/amcharts4#1476]
I'm having this issue where I'm attempting to download a barChart image but it doesn't render all the data, all other charts do. I'm getting the data from a query through a php script. The other charts do seem to render appropriately but the bar chart doesn't. I've disabled animations and followed the phantomJS documents but still failed.
Any guidance would be greatly appreciated 

After more digging I came across this old post, I'm ultimately looking to do this as well and wanted to ask if it was still not possible to do server side rendering of the charts as I keep getting empty anytime I generate a report.

https://github.com/amcharts/amcharts3/issues/102

**Comment by darlesson** [comment]
[PhantomJS](https://phantomjs.org/) is an abandoned project so we moved away from it in V4. We recommend Selenium Webdriver instead. Please check the tutorial here: https://www.amcharts.com/docs/v4/tutorials/automating-report-generation-using-selenium-webdriver/

Let us know if you still encounter the same issue after updating your setup, and please provide a reproducible example.

:-)
