### ISSUE TITLE
Time-based series with a not a round interval are not rendered

### ISSUE THREAD

**Issue by zdm** [amcharts/amcharts4#1477]
Hi,
I have data series, where each point comes with interval of 23 minutes.
For example:
```
[
	{
        earned => 110,
        time   => 1563640336
    },
    {
        earned => 120,
        time   => 1563641716
    },
    {
        earned => 130,
        time   => 1563643096
    },
]
```
This data is not rendering at all, chart is empty.
But if I make interval multiple of 5 or 10 or 30 minutes - it will rendered correctly.

How I can make this data displayed?

My chart config
```
{
	type       => 'XYChart',
	xAxes      => [ { type => 'DateAxis', } ],
	yAxes      => [ { type => 'ValueAxis', id => 'axis-revenue' } ],
	series => [
		{   type            => 'LineSeries',
			id              => 'series-revenue',
			name            => 'Revenue',
			yAxis           => 'axis-revenue',
			dataFields      => { dateX => 'time', valueY => 'earned', },
			connect         => \0,                                          # gaps
		},
	],
}
```

**Comment by zdm** [comment]
Setting ```baseInterval``` was not helpful.

**Comment by zdm** [comment]
Also, if interval is 1 hour - data is displayed, if 2 hours - not, if 3- yes.
Why it is so, and what intervals are legal?

**Comment by martynasma** [comment]
All intervals are legal :)

The issue is with `connect = false`.

When it's set, the LineSeries measures distance between any two data points. If it's longer then `baseInterval` the line is cut.

So to be correct, you have two options:

1) Set `baseInterval` to 1 minute as well as set `autoGapCount` to 30 or so. So the lines do not break if the distance is less than 30 minutes.

2) Set `baseInterval` to 23/30 minutes.

I'd go with the first option first. It gives more granularity/precision on DateAxis.

**Comment by zdm** [comment]
Thank you, I will try

**Comment by zdm** [comment]
I if correctly understand, if I don't set base interval - amcharts trying to detect it automatically.
My data points are come in regular interval, so everything should work without additional setup.
What I am missing? I want to better understand, how it works.

**Comment by zdm** [comment]
How is basInterval calculated?How is basInterval calculated?

**Comment by martynasma** [comment]
There's quite a fuzzy logic at play, so it's hard to explain in a few sentences.

If you'd like you can take a look at the source code here:
https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/axes/DateAxis.ts

That said, it's always a good idea to set your data granularity manually, versus relying on fuzzy logic blindly. It might work most of the time, but in some odd cases it might produce a result that's not expected.

**Comment by zdm** [comment]
Ok, thank.
