### ISSUE TITLE
setting alwaysShowTooltip to false does not hide tooltips.

### ISSUE THREAD

**Issue by thinkingparticle** [amcharts/amcharts4#1478]
working with version 4.5.8 

**1st problem:**
I set alwaysShowTooltip to true and it works. shows the tooltips that i need.
but then i set it back to false to hide them, it does not work. the tooltips do not disappear.

https://www.amcharts.com/docs/v4/reference/tooltip/#alwaysShowTooltip_property

**2nd problem**
setting alwaysShowTooltip to true, shows a tooltip on legend items which is odd and unusual.

**Comment by thinkingparticle** [comment]
I just want to be able to hide and show tooltips manually. when i use serie.tooltip.show(), if the tooltip was not shown before, it just shows an empty baloon on corner of chart like this image: 

![image](https://user-images.githubusercontent.com/17741554/61589144-508a8480-abbb-11e9-865d-2e5d7e7de6c2.png)

**Comment by martynasma** [comment]
Would you be able to post a chart on codepen/jsfiddle so that we know exactly what you're doing?

**Comment by thinkingparticle** [comment]
check this fiddle: http://jsfiddle.net/tjezvwp5/

I want to show all tooltips and this works. it shows all tooltips (line 97 in jsfiddle): 
`series_array.map(ser=>ser.columns.template.alwaysShowTooltip = true)`

Then I wrote this code to hide all tooltips. but it does not hide the tooltips. 
```
setTimeout(function(){
	series_array.map(ser=>ser.columns.template.alwaysShowTooltip = false)
        series_array.map(ser=>ser.tooltip.hide())
},5000)
```

**Comment by martynasma** [comment]
OK, so what's going on is you set this setting on a template, which gets propagated to actual columns as they are created.

However, then you are resetting it on template, which does not affect actual columns.

The following will do the trick:

```
  chart.series.each(function(series) {
    series.columns.each(function(column) {
    	column.alwaysShowTooltip = false;
    	column.hideTooltip();
    })
  })
```

We'll consider implementing hiding of tooltips on actual columns when `alwaysShowTooltip` is set on template as well.

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.

**Comment by EvansPM** [comment]
For slider i use hide any tooltip related to my slider:
```slider.showSystemTooltip = false;```
