### ISSUE TITLE
gyp ERR! configure error 

### ISSUE THREAD

**Issue by karuppasamy20** [amcharts/amcharts4#1479]
I did in amchart 4 on my project but is showing this error,whats the problem ?

npm install --save @amcharts/amcharts4

> canvas@2.6.0 install /node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v48-linux-glibc-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.0 and node@6.10.3 (node-v48 ABI, glibc) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/karuppaswamy/edge/17_07_2019/edge/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.13.0-37-generic
gyp ERR! command "/.nvm/versions/node/v6.10.3/bin/node" "/home/17_07_2019/edge/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/17_07_2019/edge/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/17_07_2019/edge/node_modules/canvas/build/Release" "--node_abi_napi=node-v48" "--napi_build_version=0" "--node_napi_label=node-v48"
gyp ERR! cwd /17_07_2019/node_modules/canvas
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/.nvm/versions/node/v6.10.3/bin/node /17_07_2019/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/17_07_2019/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/17_07_2019/node_modules/canvas/build/Release --node_abi_napi=node-v48 --napi_build_version=0 --node_napi_label=node-v48' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/17_07_2019/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.13.0-37-generic
node-pre-gyp ERR! command "/.nvm/versions/node/v6.10.3/bin/node" "/17_07_2019/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /17_07_2019/node_modules/canvas
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/.nvm/versions/node/v6.10.3/bin/node /17_07_2019/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/17_07_2019/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/17_07_2019/edge/node_modules/canvas/build/Release --node_abi_napi=node-v48 --napi_build_version=0 --node_napi_label=node-v48' (1)
Project@1.0.1 /17_07_2019/
+-- @amcharts/amcharts4@4.5.8 
| +-- UNMET PEER DEPENDENCY canvas@^2.1.0
| +-- UNMET PEER DEPENDENCY jsdom@^13.0.0
| `-- UNMET PEER DEPENDENCY xmldom@^0.1.27
+-- UNMET PEER DEPENDENCY @angular/common@4.4.7
+-- UNMET PEER DEPENDENCY @angular/core@4.4.7
+-- UNMET PEER DEPENDENCY rxjs@6.2.2
`-- UNMET PEER DEPENDENCY typescript@3.5.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/compiler-cli@4.4.7 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN @angular/core@4.4.7 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/http@4.4.7 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/router@4.4.7 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/tsc-wrapped@4.4.7 requires a peer of typescript@^2.1.5 but none was installed.
npm WARN angular2-cookie@1.2.6 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN angular2-cookie@1.2.6 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN tsickle@0.21.6 requires a peer of typescript@^2.1.0 but none was installed.
npm WARN canvg@2.0.0 requires a peer of jsdom@^13.0.0 but none was installed.
npm WARN canvg@2.0.0 requires a peer of xmldom@^0.1.27 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@2.6.0 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@2.6.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Use this configuration :**

"dependencies": {
    "@amcharts/amcharts3-angular": "^1.2.0",
    "@amcharts/amcharts4": "^4.5.8",
    "@angular/animations": "^4.2.3",
    "@angular/common": "^4.2.3",
    "@angular/compiler": "^4.2.3",
    "@angular/core": "^4.2.3",
    "@angular/forms": "^4.2.3",
    "@angular/http": "^4.2.3",
    "@angular/platform-browser": "^4.2.3",
    "@angular/platform-browser-dynamic": "^4.2.3",
    "@angular/router": "^4.2.3",
    "@ng-idle/core": "^2.0.0-beta.13",
    "ag-grid-angular": "^19.1.2",
    "ag-grid-community": "^19.1.3",
    "angular2-cookie": "^1.2.6",
    "angular2-image-zoom": "^1.2.1",
    "axios": "^0.16.2",
    "blob-util": "^1.3.0",
    "bootstrap": "^3.3.7",
    "chart.js": "2.1.3",
    "concat-stream": "^1.6.0",
    "connect-timeout": "^1.9.0",
    "core-js": "^2.4.1",
    "cors": "^2.8.5",
    "d3": "^4.10.0",
    "d3-pre": "^1.3.0",
    "d3-tip": "^0.7.1",
    "express": "^4.16.1",
    "express-session": "^1.15.6",
    "file-saver": "^1.3.3",
    "font-awesome": "4.7.0",
    "form-data": "^2.3.1",
    "fs": "0.0.1-security",
    "fullcalendar": "^3.1.0",
    "jQuery-QueryBuilder": "^2.4.4",
    "jquery": "^3.2.1",
    "moment": "^2.17.1",
    "multer": "^1.3.0",
    "nanoscroller": "0.8.7",
    "ng-circle-progress": "^1.0.0",
    "ng-drag-drop": "^4.0.1",
    "primeng": "^4.2.1",
    "query": "^0.2.0",
    "quill": "^1.1.8",
    "rxjs": "~6.2.0",
    "typescript": "^3.5.3",
    "web-animations-js": "^2.2.2",
    "xmlhttprequest": "^1.8.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "^4.1.0",
    "@angular/language-service": "^7.0.4",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "^3.5.3"
  }

**Comment by Pauan** [comment]
@karuppasamy20 What's your operating system?

**Comment by karuppasamy20** [comment]
linux 16.04

**Comment by Pauan** [comment]
@karuppasamy20 That's odd, it should work okay with Ubuntu.

In any case, this is an [issue with fabric](https://github.com/fabricjs/fabric.js/pull/5786), so we're working with them to get it fixed.

**Comment by NemoDima** [comment]
@Pauan I have a similar situation.
OS: Windows server 2016 (64-bit)
`C:\projects\Test\GoodStreamWebSpaClient>npm install @amcharts/amcharts4

> > canvas@2.6.0 install C:\projects\Test\GoodStreamWebSpaClient\node_modules\canvas
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download
> node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v
> 57-win32-unknown-x64.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.0 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile
> with node-gyp)
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\developer\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\node-gyp\l
> ib\configure.js:484:19)
> gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\developer\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\node-gyp\li
> b\configure.js:509:16)
> gyp ERR! stack     at C:\Users\developer\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\developer\\AppData\\Roaming\\nvm\\v8.12.0\\node_modules\\npm\\node_mo
> dules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\projects\\Test\\GoodStreamWebSpaClient\\node_modules\
> \canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\projects\\Test\\GoodStreamWebSpaClient\\node_modules\\ca
> nvas\\build\\Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
> gyp ERR! cwd C:\projects\Test\GoodStreamWebSpaClient\node_modules\canvas
> gyp ERR! node -v v8.12.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\developer\AppData\Roaming\nvm\v8.12.0\node_m
> odules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\projects\Test\GoodStreamWebSpaClient\node_mod
> ules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\projects\Test\GoodStreamWebSpaClient\node_modules\canvas\bui
> ld\Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\projects\Test\GoodStreamWebSpaClient\node_modules\node-pre-gyp\lib\util\comp
> ile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> node-pre-gyp ERR! System Windows_NT 6.3.9600
> node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\projects\\Test\\GoodStreamWebSpaClient\\node_modules\\node-pre-gyp\
> \bin\\node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd C:\projects\Test\GoodStreamWebSpaClient\node_modules\canvas
> node-pre-gyp ERR! node -v v8.12.0
> node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> node-pre-gyp ERR! not ok
> Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\developer\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\node-gy
> p\bin\node-gyp.js configure --fallback-to-build --module=C:\projects\Test\GoodStreamWebSpaClient\node_modules\canvas\build\Release\canva
> s.node --module_name=canvas --module_path=C:\projects\Test\GoodStreamWebSpaClient\node_modules\canvas\build\Release --napi_version=3 --n
> ode_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
> npm WARN rollback Rolling back sax@1.2.4 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\projects\Test\G
> oodStreamWebSpaClient\node_modules\needle\node_modules'
> npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\proje
> cts\Test\GoodStreamWebSpaClient\node_modules\@angular\cli\node_modules\chokidar\node_modules'
> npm WARN @angular/compiler-cli@5.2.5 requires a peer of typescript@>=2.4.2 <2.7 but none is installed. You must install peer dependencie
> s yourself.
> npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN tsickle@0.26.0 requires a peer of typescript@>=2.4.2 <2.7 but none is installed. You must install peer dependencies yourself.
> npm WARN canvg@2.0.0 requires a peer of jsdom@^13.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"o
> s":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"o
> s":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@2.6.0 (node_modules\canvas):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@2.6.0 install: `node-pre-gyp install --fallback-to-build`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> + @amcharts/amcharts4@4.5.9
> updated 1 package and audited 13633 packages in 48.048s
> found 169 vulnerabilities (18 low, 53 moderate, 96 high, 2 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details  

**dependencies**
>   "dependencies": {
>     "@amcharts/amcharts4": "^4.5.9",
>     "@angular/animations": "^5.0.0",
>     "@angular/common": "^5.0.0",
>     "@angular/compiler": "^5.0.0",
>     "@angular/core": "^5.0.0",
>     "@angular/forms": "^5.0.0",
>     "@angular/http": "^5.0.0",
>     "@angular/platform-browser": "^5.0.0",
>     "@angular/platform-browser-dynamic": "^5.0.0",
>     "@angular/router": "^5.0.0",
>     "@ngx-translate/core": "^8.0.0",
>     "@ngx-translate/http-loader": "^2.0.0",
>     "@types/bootstrap": "^3.3.33",
>     "@types/google.visualization": "0.0.40",
>     "@types/numeral": "0.0.21",
>     "bootstrap": "^4.3.0",
>     "core-js": "^2.4.1",
>     "file-saver": "^2.0.2",
>     "font-awesome": "^4.7.0",
>     "jquery": "^3.4.1",
>     "jquery-ui": "^1.12.1",
>     "jquery-ui-dist": "^1.12.1",
>     "moment": "^2.18.1",
>     "numeral": "^2.0.6",
>     "postcss-custom-properties": "^8.0.10",
>     "rxjs": "^5.1.0",
>     "slickgrid": "2.4.9",
>     "underscore": "^1.8.3",
>     "zone.js": "^0.8.4"
>   },
>   "devDependencies": {
>     "@angular/cli": "^1.0.3",
>     "@angular/compiler-cli": "^5.0.0",
>     "@types/jasmine": "2.5.38",
>     "@types/node": "~6.0.60",
>     "autoprefixer": "^7.0.0",
>     "circular-dependency-plugin": "^3.0.0",
>     "codelyzer": "^4.0.0",
>     "copy-webpack-plugin": "^4.1.1",
>     "css-loader": "^0.28.1",
>     "cssnano": "^3.10.0",
>     "exports-loader": "^0.6.3",
>     "file-loader": "^1.1.5",
>     "html-webpack-plugin": "^2.29.0",
>     "istanbul-instrumenter-loader": "^2.0.0",
>     "jasmine-core": "~2.5.2",
>     "jasmine-spec-reporter": "~3.2.0",
>     "karma": "~1.4.1",
>     "karma-chrome-launcher": "~2.1.1",
>     "karma-cli": "~1.0.1",
>     "karma-coverage-istanbul-reporter": "^0.2.0",
>     "karma-jasmine": "~1.1.0",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "less-loader": "^4.0.5",
>     "popper.js": "^1.14.0",
>     "postcss-loader": "^1.3.3",
>     "postcss-url": "^5.1.2",
>     "protractor": "~5.1.0",
>     "raw-loader": "^0.5.1",
>     "sass-loader": "^6.0.3",
>     "source-map-loader": "^0.2.0",
>     "style-loader": "^0.13.1",
>     "stylus-loader": "^3.0.1",
>     "ts-node": "~2.0.0",
>     "tslint": "^5.5.0",
>     "typescript": ">=2.8.0 <2.9.0",
>     "uglifyjs-webpack-plugin": "1.0.0",
>     "url-loader": "^0.6.2",
>     "webpack": "~3.8.1",
>     "webpack-concat-plugin": "1.4.0",
>     "webpack-dev-server": "~2.9.3"
>   }

Can you suggest me any way to solve this problem, please?
I have read linked issue but didn't understand how to fix my errors.

Best wishes.

**Comment by karuppasamy20** [comment]
@NemoDima can u upgrade in angular 6 is working fine for me.

**Comment by NemoDima** [comment]
@ karuppasamy20 Thanks for the advice, but my colleagues told me that at the present time it is impossible for us, but they have a plan for refactoring this project.

About the problem that I asked to solve.
1. Necessary prebuild canvas isn't available https://github.com/node-gfx/node-canvas-prebuilt/issues/81
2. Decide to compile it using instruction https://github.com/Automattic/node-canvas/wiki/Installation%3A-Windows
After that, everything works fine.

**Comment by martynasma** [comment]
@karuppasamy20 @NemoDima We think we have found a workaround for this, which will be available in the next release. Probably early next week.

We'll ping you here once that happens.

**Comment by martynasma** [comment]
Fixed in [4.5.10](https://github.com/amcharts/amcharts4/releases/tag/4.5.10).

## [4.5.10] - 2019-07-29

### Fixed
- Sometimes setting `fill`/`stroke` to a non-opaque `Color`, alpha setting was being ignored.
- `PinBullet` (from Bullets plugin) was distorted if used with image since last release.
- Fabric dependency was causing errors on installation under some setups.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
