### ISSUE TITLE
Overlap in export menu issue

### ISSUE THREAD

**Issue by karuppasamy20** [amcharts/amcharts4#1480]
Export menu is overlapping that every chart .how to fix this issue.

![Screenshot from 2019-07-22 14-52-19](https://user-images.githubusercontent.com/26301377/61621310-556d3800-ac90-11e9-80b4-ed6088e6d69c.png)

**Comment by martynasma** [comment]
This is a repo for amCharts 4, whereas it looks like [amCharts 3](https://github.com/amcharts/amcharts3).
