### ISSUE TITLE
yAxis of heatmap does not show all labels 

### ISSUE THREAD

**Issue by thinkingparticle** [amcharts/amcharts4#1481]
in the default example of heatmap in https://www.amcharts.com/demos/heat-map-with-legend/

I want to see all yAxis labels so i use this line of code: 
`yAxis.renderer.minGridDistance = 0;`
it shows all labels **except the first one**

just take a look at fiddle in link below. it does not show the first yaxis label. 
http://jsfiddle.net/awbof36p/
![image](https://user-images.githubusercontent.com/17741554/61635042-f0bdd780-aca7-11e9-8281-eee3d6f2dd9c.png)

how should I fix that?

**Comment by martynasma** [comment]
Try this:

```
yAxis.renderer.minGridDistance = 1;
```

Should fix the issue.

I suppose having zero throws off the calculation algorithm.

**Comment by thinkingparticle** [comment]
Yes it worked. Thanks a lot!
