### ISSUE TITLE
How to have a fixed number of grid lines?

### ISSUE THREAD

**Issue by andii1997** [amcharts/amcharts4#1482]
Is it possible to have a fixed number of grid lines? Currently the number of lines is highly dependent on the data and varies between 2 and 7. And also for multiple axis it would be really good, to have them aligned.  
![image](https://user-images.githubusercontent.com/7026923/61689847-4639c900-ad28-11e9-8ad6-3c129cfd9794.png)

**Comment by martynasma** [comment]
The only way to have fine-grained control over grid line count/placement is to add them manually as Axis Ranges.

https://www.amcharts.com/docs/v4/tutorials/custom-valueaxis-grid-using-ranges/

**Comment by andii1997** [comment]
Alright, thank you for your quick response. I'll try that approach :)
