### ISSUE TITLE
Animation not working for XYcharts3d

### ISSUE THREAD

**Issue by parthi2929** [amcharts/amcharts4#1483]
Newbie here. I tried lot of methods but I could not make this work. My example is based on [amchart4 cylinder gauge](https://www.amcharts.com/demos/cylinder-gauge/)

I simply added extra code as below, but for new value, chart abruptly switches, does not animate smoothly like it does initially when loading.

```
    
    chart.setTimeout(randomValue, 2000);
    // setInterval(randomValue, 2000);
    

    var newData = [];
    function randomValue()
    {
        console.log("Hello");         
        var val1 = Math.random() * 100;    
        // newData  = [{
        //     "category": "Raw Water Tank (RWT)",
        //     "value1": val1,
        //     "value2": 100-val1
        //   }];   
        // chart.data = newData;

        chart.data[0]['value1'] = val1;
        chart.data[0]['value2'] = 100-val1;      
        chart.validateData();
        // chart.invalidateData();  
        // chart.appear();
        console.log(chart);

        // chart.setTimeout(randomValue, 2000);
    }

```

Kindly help. All I need is to make smooth animation of liquid levels raising or falling. Any direct example of that also would be highly appreciated.

**Comment by martynasma** [comment]
Try `invalidateRawData()` instead.

https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points
