### ISSUE TITLE
Question: Multiple Colors for TreeMap Children

### ISSUE THREAD

**Issue by vidganshorn** [amcharts/amcharts4#1484]
Hey there,

I came across your TreeMap and was wondering whether it's possible for parents and children to have different colors.
For example, I would need a TreeMap in which the children can have different colors from its parents and among themselves. My data looks like this:

`chart.data = [{
            name: "First",
            color: am4core.color("#0fF"),
            children: [
                {
                    name: "A1",
                    value: 100,
                    color: am4core.color("#0f0")
                },
                {
                    name: "A2",
                    value: 60,
                    color: am4core.color("#Ff0")
                },
                {
                    name: "A3",
                    value: 30,
                    color: am4core.color("#0f0")
                }
            ]
        },...`

I've used the Drill-Down Treemap from your website (https://www.amcharts.com/demos/drill-down-treemap/) to configure the chart. But only the tooltip color changes for the children.

Thank you very much in advance!

**Comment by vidganshorn** [comment]
I was able to solve the problem with:

`level1SeriesTemplate.columns.template.adapter.add("fill", function(fill, target) {

            return fill;
        });`

**Comment by chengzh2008** [comment]
@vidganshorn I have the same issue however it won't work with the above solutions. Could you share your configuration part of the treemap? Thanks

**Comment by prasad2312** [comment]
pls share complete configuration...

**Comment by prasad2312** [comment]
> @vidganshorn I have the same issue however it won't work with the above solutions. Could you share your configuration part of the treemap? Thanks

Remove line
level1SeriesTemplate.columns.template.fillOpacity = 0;

**Comment by prasad2312** [comment]
am4core.useTheme(am4themes_animated);

// create chart
var chart = am4core.create("chartdiv", am4charts.TreeMap);
chart.hiddenState.properties.opacity = 0; // this makes initial fade in effect

// only one level visible initially
chart.maxLevels = 1;
// define data fields
chart.dataFields.value = "count";
chart.dataFields.name = "name";
chart.dataFields.children = "children";
chart.dataFields.color = "color";
chart.homeText = "US Car Sales 2017";

// enable navigation
chart.navigationBar = new am4charts.NavigationBar();

// level 0 series template
var level0SeriesTemplate = chart.seriesTemplates.create("0");
level0SeriesTemplate.strokeWidth = 2;

// by default only current level series bullets are visible, but as we need brand bullets to be visible all the time, we modify it's hidden state
level0SeriesTemplate.bulletsContainer.hiddenState.properties.opacity = 1;
level0SeriesTemplate.bulletsContainer.hiddenState.properties.visible = true;

// create hover state
var columnTemplate = level0SeriesTemplate.columns.template;
var hoverState = columnTemplate.states.create("hover");

// level1 series template
var level1SeriesTemplate = chart.seriesTemplates.create("1");
level1SeriesTemplate.columns.template.adapter.add("fill", function(fill, target) {
  return fill; });

var bullet1 = level1SeriesTemplate.bullets.push(new am4charts.LabelBullet());
bullet1.locationX = 0.5;
bullet1.locationY = 0.5;
bullet1.type="LineSeries";
bullet1.label.text = "{name}";
bullet1.label.fill = am4core.color("#ffffff");

// level2 series template
var level2SeriesTemplate = chart.seriesTemplates.create("2");
level2SeriesTemplate.columns.template.adapter.add("fill", function(fill, target) {
  return fill; });

var bullet2 = level2SeriesTemplate.bullets.push(new am4charts.LabelBullet());
bullet2.locationX = 0.5;
bullet2.locationY = 0.5;
bullet2.label.text = "{name}";
bullet2.label.fill = am4core.color("#ffffff");

chart.data = [
 {"name":"Acura","children":[{"name":"ILX","count":11757,"color":"red"},{"name":"MDX","count":54886,"color":"green"},{"name":"NSX","count":581,"color":"green"},{"name":"RDX","count":51295,"color":"green"},{"name":"RLX","count":1237,"color":"green"},{"name":"TLX","count":34846,"color":"green"}],"color":"red"},
  
{"name":"Other","children":[{"name":"Alfa Romeo","children":[{"name":"4C","count":407,"color":"green"},{"name":"Giulia","count":8903,"color":"#66cc66"},{"name":"Stelvio","count":2721,"color":"green"}],"color":"yellow"}]}];
