### ISSUE TITLE
How to detect when the chart is ready after updating data?

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1485]
I can see the "ready" event for the chart is fired only when creating the chart, if we update the "data" is not fired again.   
How can we detect when the chart is ready again after updating the data?

**Comment by martynasma** [comment]
I'd use `datavalidated` or `validated`. Depending on what you need data items to be available or actual visual elements to be redrawn.

**Comment by enriquepiatti** [comment]
I will comment the real situation because maybe is another XY problem:     
I need to update the data but also remember the current scrollbars position.    
So I'm setting the data and then setting the scrollbars again.   
This has 2 problems:   
1) there is a visual glitch   
2) I need to process the data but after everything is ready (data and visual I guess, because I need to access to the "x and y" position in the chart for some position.

**Comment by martynasma** [comment]
In this case you should probably check `selectionextremeschanged` event for each axis, so that you can restore it.

I may be missing the point. If you could produce some sort of codepen demo, that would make it clearer.

**Comment by runfaj** [comment]
I essentially just did the following - seems to work well. In my case, I have a custom overlay loader that is added before the chart inits/updates and the onReady below will remove that overlay.

```
function showLoadingIndicator({
  chart,
  onReady,
}) {
  if (chart.preloader) {
    chart.preloader.disabled = true;
  }

  const eventTriggerType = chart._ready ? 'validated' : 'ready';

  function onChartReady(ev) {
    if (onReady) {
      onReady();
    }
    chart.events.off(eventTriggerType, onChartReady, this);
  }
  chart.events.on(eventTriggerType, onChartReady, this);
}
```
