### ISSUE TITLE
Setting axisObject.renderer.line.disabled to true doesn't remove the line when series.stacked = true

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#1486]
In [this codepen example](https://codepen.io/team/amcharts/pen/69145200d0c88e2ab53ea2d51f7d0499?editors=0010) I'm disabling the axis line and grids by setting the associated objects' `disabled` property to true, however the category axis line is still visible when the series' `stacked` property is enabled. If you comment out line 72, the line is hidden like it's supposed to.

**Comment by martynasma** [comment]
Missing one more axis item to disable :)

```
valueAxis.renderer.baseGrid.disabled = true
```

**Comment by xorspark** [comment]
Whoops! Thanks. :)
