### ISSUE TITLE
HowTo / Replacement for chart.plotAreaFill...?

### ISSUE THREAD

**Issue by Christian-Adler** [amcharts/amcharts4#1488]
Is there a replacement for the amcharts 3 chart properties **plotAreaFillColors** and **plotAreaFillAlpha**?

There is chartContainer.fill or chart.background but they are to large - containing the full chart with axes.

**Comment by martynasma** [comment]
There's also `chart.plotContainer.background`, which you can use to set various settings to.

Schema in in here might come in handy:
https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/#Pre_defined_chart_containers

**Comment by Christian-Adler** [comment]
Perfect - Thanks.

Not seen the property in the reference.
It is a bit difficult to find the correct property because i found no overview of all properties (per class),
You always have to scroll down the list...
