### ISSUE TITLE
ScrollbarX resets ScrollbarY position

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1489]
I'm trying to restore the previous scrollbar positions after updating the data, the problem is not only the visual glitch, but when I set the scrollbarX position for some reason it resets the scrollbarY position too.   
This happen if I move the scrollbarX manually (it seems the be happening after crossing 0.5):   

EXAMPLE: 
https://jsfiddle.net/732qb9Lp/   

How to Test: move the scrollbarY first, and then move the scrollbarX, at some point the scrollbarY is reset.

It does not work by code either, I'm actually doing something like:   

```
chartpools.events.once("ready", function () {
                        
  // this works, but if I set the scrollbarX too then the scrollbarY is reset!
  chartpools.scrollbarX.start = 0;
  chartpools.scrollbarX.end = 1;
  chartpools.scrollbarY.start = 0.3;
  chartpools.scrollbarY.end = 0.7;
                        
});
```

**Comment by zeroin** [comment]
If you set: 

`priceAxis.keepSelection = true;`

it should keep the selection:

https://jsfiddle.net/6qrtj10b/

**Comment by enriquepiatti** [comment]
Is that working only for ValueAxis?
