### ISSUE TITLE
Invalid tooltip color, when axisRanges.contents used

### ISSUE THREAD

**Issue by zdm** [amcharts/amcharts4#1490]
Here is the part of my config
```
yAxes      => [
    {   type            => 'ValueAxis',
        id              => 'axis-roi',
        axisRanges      => [
            {   series   => 'series-roi',
                endValue => 100,
                contents => { stroke => '#ff0000', fillOpacity => 0.5, fill => '#ff0000' },
            },
        ],
    },
],
```

![Annotation 2019-07-24 170621](https://user-images.githubusercontent.com/1025608/61800352-89ce2900-ae35-11e9-8756-1043630c8302.jpg)
![Annotation 2019-07-24 170707](https://user-images.githubusercontent.com/1025608/61800353-89ce2900-ae35-11e9-8d58-6dafc2684662.jpg)

You can see, that tooltip fill color changed to red for all values, regardless to the range.
I am expected, that tooltip color become red only for values in range.

**Comment by martynasma** [comment]
Indeed. Looks like bug.

Here's a simplified demo for dev team.
https://codepen.io/team/amcharts/pen/0917516d32ef608cc1c691f3430c019a

**Comment by zeroin** [comment]
Unfortunately we can not fix this on our side when range is added to ValueAxis. However I created a modified pen with a workaround which does what you expect: 

https://codepen.io/team/amcharts/pen/0917516d32ef608cc1c691f3430c019a
