### ISSUE TITLE
Ranges as guides displayed one month off

### ISSUE THREAD

**Issue by cruzel89** [amcharts/amcharts4#1493]
When including `axisRanges` on a `DateAxis()`, the range gets displayed one month off.

Issues in [Demo-Fiddle](http://jsfiddle.net/ts0odc8L/):
* range defined from `2019-01-01 12:00` to `2019-01-05 12:00` is displayed from `2019-02-01 12:00` to `2019-02-05 12:00`
* range2 (single line) defined at `2019-05-25 12:00` is displayed at `2019-06-25 12:00`

**Comment by martynasma** [comment]
Months in `Date` constructor are zero-based. Meaning that January is 0, February - 1, etc.

Update your code accordingly ;)

**Comment by cruzel89** [comment]
Aww, thanks for the hint. It's a real shame, that JS has this quirk.
