### ISSUE TITLE
How to show bars on column chart with only ValueAxis?

### ISSUE THREAD

**Issue by b49015** [amcharts/amcharts4#1495]
I have created 2 ValueAxis, one for xAxes and other for yAxes and added a column series to my XY chart but the chart is being created with no bars inside.
Please have a look to this codepen: https://codepen.io/b49015/pen/YmWbXr
How can I create a XY column chart with only ValueAxises?

**Comment by martynasma** [comment]
Well, this is because the columns don't know what width they should be.

When there's a `DateAxis` or `CategoryAxis`, each axis cell has a width.

On `ValueAxis` there are no cells, so default relative width of the columns fails.

Try hardcoding column width in pixels:

```
series.columns.template.width = 50;
```

**Comment by b49015** [comment]
Thanks @martynasma  for quick response. I have added the width as you suggested and now bars appear on the chart but they are overlapping with each other. Is there any way that chart adjust column/cells width and spacing between them automatically depending upon the width of chart same like the category Axis do? because it is very difficult to maintain the spacing between columns with static width where data ranges may vary.

**Comment by martynasma** [comment]
I don't think so.

Maybe with an adapter:

```
series.columns.template.adapter.add("pixelWidth", function(width, target) {
  if (target.dataItem) {
    var series = target.dataItem.component;
    return chart.plotContainer.pixelWidth / series.columns.length * 0.8;
  }
  return 10;
});
```

**Comment by T-Grave** [comment]
I'm trying to accomplish something similar. I tried using a CategoryAxis first, which works well for my columns. But I need to be able to draw a LineSeries on top of the columns with certain accuracy (not limited to the Column category values).

Using a fixed width actually draws the columns, but using an adapter as you stated, results in an empty chart again even when I simply return a fixed value for testing. (tried to set an adapter on pixelWidth as well as width)

**Comment by martynasma** [comment]
OK, I came up with an event-based solution where columns are being resized automatically, based on current zoom:

https://codepen.io/team/amcharts/pen/gOYxOyy?editors=0010
