### ISSUE TITLE
How to change scroll bar height

### ISSUE THREAD

**Issue by karuppasamy20** [amcharts/amcharts4#1497]
this image changed to below image .it is possible in amcharts 3 but 4 is it possible
![Firefox_Screenshot_2019-07-26T09-41-06 025Z](https://user-images.githubusercontent.com/26301377/61942837-cf1a6400-afb7-11e9-9b16-955b82171b1b.png)

changed to this one like this.
![Firefox_Screenshot_2019-07-26T09-41-27 295Z](https://user-images.githubusercontent.com/26301377/61942861-dccfe980-afb7-11e9-8f0f-5778dfd87c0e.png)

**Comment by martynasma** [comment]
You may change that using scrollbar's `minHeight`:

```
chart.scrollbarX.minHeight = 4;
```

**Comment by karuppasamy20** [comment]
@ martynasma  thank u

**Comment by bhupi1985** [comment]
Please tell me, how to resize the stargrip icon of scrollbar in amcharts.
