### ISSUE TITLE
ShowAlwaysTooltip for HeatMap

### ISSUE THREAD

**Issue by pankajd1990** [amcharts/amcharts4#1500]
How to do ShowAlwaysToolTip in HeatMap chart
I have written following code which also shows tooltip after mouse over.
So How to display Tooltip always in all values

  categoryAxis.renderer.labels.template.events.on("over", function(ev) {
    console.log(ev);
    heatLegend.valueAxis.showTooltipAt(ev.target.dataItem.dataContext['value']);
  
});

categoryAxis.renderer.labels.template.events.on("out", function(ev) {
  heatLegend.valueAxis.hideTooltip();
});

**Comment by martynasma** [comment]
Something like this would work:

```
series.columns.template..alwaysShowTooltip = true;
series.tooltip.pointerOrientation = "down";
series.tooltip.dy = -15;
```

https://codepen.io/team/amcharts/pen/qeRrgz?editors=0010
