### ISSUE TITLE
Label values are not updated when value is 0

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1501]
I'm using this:
```
let valueLabel = info.createChild(am4core.Label);
valueLabel.id = field;
valueLabel.text = "-";
```
And is working fine when field is > 0 but when field is 0 is keeping the previous value, not showing 0, is that normal?

**Comment by martynasma** [comment]
What type of object is `info`?

**Comment by enriquepiatti** [comment]
Sorry:  
`let info = chart.plotContainer.createChild(am4core.Container);`    
I have copied the code from one of the official examples/tutorials

**Comment by martynasma** [comment]
Um, would you be able to post your complete chart code? I tried replacing some of the values from demos in that tutorial. They are updating fine.

**Comment by enriquepiatti** [comment]
OK, here is a working example, you can see when mouse is over some empty value (actually 0 value) it does not show 0 but instead it keeps showing the previous value:
https://jsfiddle.net/mhgawsjk/

**Comment by martynasma** [comment]
Thanks. Look at this condition when updating:

```
if(dataItem && dataItem.valueX){
```

A number zero evaluates as `false` in conditional statements. This is why labels are not updated at all because the above condition evaluates to `false`.

Update your code accordingly, e.g.:

```
if(dataItem && !isNaN(dataItem.valueX)){
```
```

**Comment by enriquepiatti** [comment]
Perfect. Thanks !!
