### ISSUE TITLE
Gauge chart error

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#1505]
![Screen Shot 2019-07-29 at 5 33 43 pm](https://user-images.githubusercontent.com/33300743/62084334-19554c80-b227-11e9-9858-342e49498377.png)
![Screen Shot 2019-07-29 at 5 33 47 pm](https://user-images.githubusercontent.com/33300743/62084346-1fe3c400-b227-11e9-8d92-c1f2d796590e.png)

Hello,
 
I am stuck and I don’t understand the following error.

Many Thanks!
Alex

**Comment by martynasma** [comment]
Try this:

```
let axis = chart.xAxes.push(new am4charts.ValueAxis<am4charts.AxisRendererCircular>());
```

**Comment by AlexandreKang** [comment]
Hello,

Once I edit my file according to your suggestion, it says Cannot find namespace ‘am4charts’

**Comment by martynasma** [comment]
Seems like according to your code you need to replace "chart" with "clock".

**Comment by AlexandreKang** [comment]
Hello,

I changed to clock and this is what appear:
![Screen Shot 2019-07-31 at 6 39 23 pm](https://user-images.githubusercontent.com/33300743/62253067-b7314e80-b3c2-11e9-93e1-07ab5469d7b9.png)

**Comment by martynasma** [comment]
Can you post this online somewhere?

**Comment by AlexandreKang** [comment]
Yes, for sure here is the link: https://codepen.io/alexandrekang/pen/oKewVL?editors=0010#0

**Comment by martynasma** [comment]
OK, so I think TS pre-compiler does not know anything about modules that are bing imported at run-time.

In this case, I suppose you're down to using `<any>` keyword to avoid error.

```
let axis = chart.xAxes.push(new am4charts.ValueAxis<any>());
```

**Comment by AlexandreKang** [comment]
Many thanks! I forgot to close it.
