### ISSUE TITLE
Can I make the sankey animations less "stretchy"?

### ISSUE THREAD

**Issue by nealfinley** [amcharts/amcharts4#1506]
When I enable a node it stretches a lot and goes out of bounds like on this pen: https://codepen.io/team/amcharts/pen/vjeZXj

When I enabled "D":
![Screenshot_1](https://user-images.githubusercontent.com/53459395/62098814-42f48f00-b28c-11e9-872e-1aa9254a49f1.png)

Can I make the sankey animate but not go out of bounds or at least stretch out less?

Thank you.

**Comment by martynasma** [comment]
Do you mean when part of the chart goes out of bounds briefly during node toggle animation?

That said, even when not animating, seems like part of the lower nodes is cut off, which is probably a bug. We'll need to look into it.

![image](https://user-images.githubusercontent.com/1458520/62101198-3af11b00-b29d-11e9-8736-823676c23737.png)

**Comment by zeroin** [comment]
I actually tried doing that but all the attempts resulted to a very non-smooth animations. So I am afraid I don't have a better solution.
