### ISSUE TITLE
Candlestick chart add multiple bullet 

### ISSUE THREAD

**Issue by karuppasamy20** [amcharts/amcharts4#1507]
Candlestick chart adds multiple bullets like this image.
![Firefox_Screenshot_2019-07-30T09-06-56 983Z](https://user-images.githubusercontent.com/26301377/62116411-bd96cc00-b2d7-11e9-86c2-e71881186852.png)

**Comment by martynasma** [comment]
It looks like amCharts 3, whereas it's a repo for amCharts 4.

Correct me if I'm wrong.

**Comment by karuppasamy20** [comment]
yes is amchart3 i need same in mutiple bullet points in amchart 4 but i dont know how to do in mutiple bulltes in there.

**Comment by martynasma** [comment]
Just add a `LineSeries` with multiple data items with the same category in their data.

https://codepen.io/team/amcharts/pen/8f2beb9ca5b4a938ffde638345623c2f?editors=0010

**Comment by karuppasamy20** [comment]
@martynasma Thank u.
