### ISSUE TITLE
PieChart , colors seem not working

### ISSUE THREAD

**Issue by andrelec1** [amcharts/amcharts4#1508]
I define a array of colors and re-use it for all my charts ...
That work on all of my chart exept on pieChart 

https://codepen.io/anon/pen/XvMEyN?editors=1111

i can't find what i'm doing wrong :/
( i need a alternative  blue / orange slice ( apply my array .... ))

**Comment by martynasma** [comment]
`PieChart` is different in such regard that each series uses separate `ColorSet` for each slice. It does not use chart's colorset.

So the only modification you have to do is to assign your colors to series, not chart:

```
pieSeries.colors.list = colors;
```
