### ISSUE TITLE
ValueAxis labels not rendering when min is set to 0 and all values are negative

### ISSUE THREAD

**Issue by fundo-dev** [amcharts/amcharts4#1509]
On a ColumnSeries chart, I'd like to set the base line to 0 for showing the entire column.
But when all values are negative, ValueAxis labels are not rendered.

Example:
https://codepen.io/ivanmoretti/pen/ZgeaqW

**Comment by martynasma** [comment]
I'm struggling to understand how having `min = 0` with all-negative values could make any sense.

In such situation setting `max = 0` would make much more sense:

![image](https://user-images.githubusercontent.com/1458520/62132065-030dc600-b2e5-11e9-8da4-7dafc1b329d9.png)

**Comment by fundo-dev** [comment]
Of course! I feel bad to have wasting your time.
I was misled by amcharts 3 where

```
"valueAxes": [{
    "minimum": 0
  }]
```
does the same as `max = 0` in version 4.

**Comment by martynasma** [comment]
No worries :)

Feel free to close this issue, when you're ready.
