### ISSUE TITLE
BUG!. Dynamically created iframe element. Error: html container not found.

### ISSUE THREAD

**Issue by nikhilsmg** [amcharts/amcharts4#1511]
Hi,

I'm trying to create 2 charts. Created 1st div in plain HTML. 2nd one created dynamically in an iframe.
1st chart is displaying and 2nd chart throwing an error: "html container not found".
Please check in chrome & firefox. In firefox 2nd chart will display slightly.

Then I checked the armcharts4 code in Github. The error is in DOM.ts the element is checking that is it the instanceof HTMLElement. then it fails. (https://github.com/amcharts/amcharts4/blob/master/src/.internal/core/utils/DOM.ts#L77)

So I tried to fix the issue locally but getting error in building the armcharts4 code.

Please download the file and rename it to test.html and open in FF & firefox then see the difference.
[test.txt](https://github.com/amcharts/amcharts4/files/3446716/test.txt)

Regards,
Nikhil S

**Comment by martynasma** [comment]
I seriously doubt it will work that way. Does `graphElement2` even result in a reference to a valid element?

**Comment by nikhilsmg** [comment]
> graphElement2

Yes. Please check download the file and rename to .html and open in FF & chrome.
[test.txt](https://github.com/amcharts/amcharts4/files/3446700/test.txt)

**Comment by martynasma** [comment]
I mean does your `iframeDocument.querySelector('div#chartArea2');` return any valid reference to an element at all?

Try adding `console.log(graphElement2)`.

**Comment by nikhilsmg** [comment]
@martynasma  yes, it's a valid reference to an element.

**Comment by martynasma** [comment]
OK. I don't think it will work anyway, because amCharts code still runs in scope of the original document, not the one in the iframe.

I'm sorry, we won't be able to accommodate this request.

Please consider invoking amCharts code in the document of the iframe.

**Comment by nikhilsmg** [comment]
> OK. I don't think it will work anyway, because amCharts code still runs in scope of the original document, not the one in the iframe.
> 
> I'm sorry, we won't be able to accommodate this request.
> 
> Please consider invoking amCharts code in the document of the iframe.

Ok Thank you.
I cloned the amcharts4 code trying to build it locally but getting errors.
steps i followed: 
yarn install
yarn run build

How to build the code? Any docs? can you please help me with this?

**Comment by martynasma** [comment]
Yes, there are plenty of docs :)

https://www.amcharts.com/docs/v4/getting-started/

**Comment by nikhilsmg** [comment]
> Yes, there are plenty of docs :)
> 
> https://www.amcharts.com/docs/v4/getting-started/

I go through the code. but it's for enduser.
can you please share me the developers doc if possible. So that i can fix it myself.

**Comment by martynasma** [comment]
Not sure what you mean by "developer's doc". amCharts is not an end-user tool, it's only meant for developers.

**Comment by nikhilsmg** [comment]
I didn't find how to build this [](https://github.com/amcharts/amcharts4) code. There is no info in readme also.
