### ISSUE TITLE
How to set the image of the pattern responsive?

### ISSUE THREAD

**Issue by koja-e** [amcharts/amcharts4#1513]
Is there a way to set the image of the pattern responsive?
I want to set the following "setSize" according to the width.
https://codepen.io/koja-e/pen/MNmrpe

I don’t know how to return the state in the ”chart.responsive.rules.push”.
https://www.amcharts.com/docs/v4/concepts/responsive/

**Comment by martynasma** [comment]
I'm afraid I wasn't able to find a way to automatically resize element image of a pattern using responsive features. Sorry.

**Comment by koja-e** [comment]
Thank you for your answer.

**Comment by martynasma** [comment]
I'm afraid we won't be able to implement this. Sorry.
