### ISSUE TITLE
Unusual chart

### ISSUE THREAD

**Issue by ModKub** [amcharts/amcharts4#1514]
Hi,

How to make such chart? Is it even possible ?

<img width="538" alt="Screenshot 2019-07-29 at 16 36 35" src="https://user-images.githubusercontent.com/29551067/62205702-4f621000-b390-11e9-9222-6a232c054998.png">

**Comment by ModKub** [comment]
I made similar chart, but with bullets:
https://codepen.io/anon/pen/pMwGar?editors=0100

I want this values represent by lines

**Comment by martynasma** [comment]
This could be achieved by providing two data points per series.

https://codepen.io/team/amcharts/pen/fc919f4bf061bbcdb97aef57441f2da5?editors=0010

**Comment by ModKub** [comment]
Thank You!
