### ISSUE TITLE
Highlight specific bullet/point by vertical line

### ISSUE THREAD

**Issue by WojciechKlisiewicz** [amcharts/amcharts4#1517]
![image](https://user-images.githubusercontent.com/21077892/62219971-8bf13400-b3af-11e9-93c0-874c27522d8d.png)

I want to add vertical line where one point from serie has property 'hideBullet' = false. I added this property to data item and I can draw line basing on your tutorial:
https://www.amcharts.com/demos/step-count-chart/

by adding:
`const middleLine = this.chart.plotContainer.createChild(am4core.Line);`
`middleLine.paddingLeft = 140;`
`middleLine.adapter.add('y2', (y2, target) => target.parent.pixelHeight);`

But I don't know how to move line (by paddingLeft or something else) to specific bullet position. What is a proper solution?

**Comment by martynasma** [comment]
This demo might provide a better approach:

https://codepen.io/team/amcharts/pen/71c22713c1bde1427d2e765d0fc8d63b?editors=0010

It uses actual bullets with `Line` elements in them.

**Comment by WojciechKlisiewicz** [comment]
@martynasma Thanks for example. How to set y position to move line to the top grid?
![image](https://user-images.githubusercontent.com/21077892/62286930-10e45800-b459-11e9-9d51-7d9ae2bc5aae.png)
Code define constant line.y2 as 1000px but it's begin from bullet to bottom and I cannot calculated how grid height is and what is a bullet position to calculate negative y1 position (to move it to top)
`line.x1 = 0;`
`line.y1 = 0;`
`line.x2 = 0;`
`line.y2 = 1000;`

**Comment by martynasma** [comment]
Try setting `y1 = -1000`.

Also you probably have `maskBullets` set to false. It should not go outside plot area like that if you didn't.

You might need to remove that from your code.

**Comment by WojciechKlisiewicz** [comment]
Thanks - removing maskBullets helps me
