### ISSUE TITLE
synching a legend between 2 charts

### ISSUE THREAD

**Issue by rebmullin** [amcharts/amcharts4#1518]
I am trying to use 1 legend for these 2 charts and on hover I would like the tooltip to show up on both. Is that possible? I have a sample which I am hoping will help:

https://codepen.io/anon/pen/LwPexv?editors=0000

So again if I hover on "Ireland" in the legend, I would like the tooltip to show on both charts. I've tried various things but it's not working : / 

any suggestions? or can you please point me to any docs that might help.

thanks!

**Comment by martynasma** [comment]
The following approach might be better:

```
firstChart.legend.itemContainers.template.events.on('over', function(ev) {
  secondChart.series.getIndex(0).slices.getIndex(ev.target.dataItem.index).isHover = true;
});

firstChart.legend.itemContainers.template.events.on('out', function(ev) {
  secondChart.series.getIndex(0).slices.getIndex(ev.target.dataItem.index).isHover = false;
});
```
