### ISSUE TITLE
Tooltip position changes if text set using propertyFields for ColumnSeries

### ISSUE THREAD

**Issue by thunderbolt10** [amcharts/amcharts4#1519]
The vertical positioning of the tooltip is affected by how the tooltip text is assigned. I would like to use the propertyFields assignment method but with the tooltips positioned at the top of the column.

I have 2 column series where the only difference is how the tooltipText is set.
Series1 sets the text directly in the series:
```series1.tooltipText = "{categoryX}: [bold]{valueY}[/]";```
whilst series2 uses propertyFields to reference the text format in the data points
```series2.columns.template.propertyFields.tooltipText = 'ttip';```

![image](https://user-images.githubusercontent.com/30114322/62287610-36219800-b452-11e9-920f-78b1c9f59f30.png)

Codepen [example](https://codepen.io/thunderbolt10/pen/oKwJJd?editors=0010)

**Comment by martynasma** [comment]
Setting `tooltipText` directly on column template when using cursor is not a good combination.

It's best to set `tooltipText` directly on series.

You can reference to any key in data using curly brackets even within formatting blocks, so you don't need to use `propertyFields`, e.g.:

```
series1.tooltipText = "{categoryX}: [bold {color}]{valueY}[/]";
```
