### ISSUE TITLE
Range label tooltip overlapping with axis tooltip: question

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#1520]
Hy, having the pen bellow:

https://codepen.io/aniov/pen/aewRrM?editors=0010

How can I disable (hide) categoryAxis tooltip but see range label tooltip on mouse over ?
The range label must be inside chart.
(It seems that for some reason categoryAxis is inheriting range label tooltip color)

Thank you.

**Comment by martynasma** [comment]
To disable axis tooltip:

```
categoryAxis.tooltip.disabled = true;
```

However, axis tooltip inheriting color of the axis range label is a weird bug. We'll need to fix that.

For dev team:

Initially axis tooltip is correct:
![image](https://user-images.githubusercontent.com/1458520/62351588-9b3ac380-b50e-11e9-896a-ac0747b55700.png)

After hovering over range label the fill of the axis tooltip changes:
![image](https://user-images.githubusercontent.com/1458520/62351620-b4437480-b50e-11e9-8775-d68585252067.png)

**Comment by aniov** [comment]
Thank you for your response but disabling categoryAxis tooltip results in range label tooltip being disabled also (I suppose because is created on top of categoryAxis and inherits his properties).
Only if I move range labels outside chart I can see tooltips for them, otherwise they are overlapped by categoryAxis tooltip.

![RangeLabelTooltip](https://user-images.githubusercontent.com/21243081/62353312-0f776600-b513-11e9-8f93-dfc8fc055043.gif)


>How can I disable (hide) categoryAxis tooltip but see range label tooltip on mouse over ?

Thank you.

**Comment by martynasma** [comment]
I suppose you will need to create a "personal" tooltip for each range, so it does not try to reuse axis' tooltip:

```
range.label.tooltip = new am4core.Tooltip();
```

**Comment by aniov** [comment]
I suppose you are right.
Thank you :)

**Comment by zeroin** [comment]
Another solution would be setting:
`categoryAxis.tooltip.getFillFromObject = false;`
