### ISSUE TITLE
Adaptive axis scale not working

### ISSUE THREAD

**Issue by l1b3r** [amcharts/amcharts4#1527]
Hello, 

Could someone please help me figure out how to make the axes (specifically, the Y axis) respond to the zooming and panning of the chart and rescale respective of the visible part of the chart?

Please refer to the minimal repro I've prepared on stackblitz:
https://stackblitz.com/edit/angular-denrs2

**Repro steps:**
1. Wait for the demo to load;
2. Zoom into some certain part of the line using the scrollbar or by selecting a range using a mouse;
3. Pan the zoomed area to the left and to the right;

**Current behavior**
The Y axis remains fixed to [-15; 10] no matter the zoom level.

**Desired behavior**
The Y axis responds to the currently zoomed area and adjusts itself respectively.

According to [this documentation page](https://www.amcharts.com/docs/v4/tutorials/fixed-value-axis-scale/#Adaptive_scale) this feature should be enabled by default. However, I seem to be missing something. The very first series of screenshots on that page (under the `Adaptive Scale` section) is exactly the feature I'm after.

Thanks

**Comment by martynasma** [comment]
Your setup uses `ValueAxis` for both X and Y. This scenario is different from linear scenarios where one of the axes is either `CategoryAxis` or `DateAxis`. I'm afraid there's no built-in method to implement automatic zoom to the values within visible range.

Technically, it should be possible to watch for zoom events on the X axis (or scrollbar), then cycle through the values in series, determine min/max that fit within range and zoom Y axis manually.

Unfortunately, I don't have a ready-made example for that :(

**Comment by l1b3r** [comment]
Thanks for your answer, @martynasma.

It seems to me that using `ValueAxis` for both X and Y would be a common case if some scientific data is being plotted. (e.g. sensor information: a series of observations unevenly distributed in time on a millisecond scale starting from some point in time). I have also noticed that series tooltips are not working as expected in this "mode" as well:
```
const series = this.chart.series.push(new am4charts.LineSeries());
//fill in the data and other stuff
series.tooltipText = 'test';
```
The tooltip is not being displayed on a `ValueAxis`x`ValueAxis` chart. If I, however, switch X to be a `DateAxis`, then both the auto axis adjustment, as well as the tooltips, start working immediately.

Perhaps I'll be able to transform my data so that it can be properly displayed using a `DateAxis` (with correct axis ticks/labels etc.)

Thank you for your help!

**Comment by martynasma** [comment]
Yes, series tooltips do not work, either.

I'm not sure if we can resolve either items. Both `DateAxis` and `CategoryAxis` are linear. Meaning that data items are in some kind of order, going one way or another.

`ValueAxis` is non-linear. So when we have both X and Y as `ValueAxis`, we have a scatter chart scenario.

Too much questions arise. Like when do we display a series tooltip? When cursor is exactly over data item's value? Close to it? How close? What if there are 20 items with the same value?

I know there some niche cases where it's straightforward and would work. But, unfortunately we can't hardcode fuzzy logic for all contingencies.

You get the drift :)

**Comment by l1b3r** [comment]
I get your point with the complexity of general XY scattercharts. The type of a chart I was pursuing is a simple subclass of scatter with unevenly distrubuted yet monotone increasing X values of the observations, e.g.:
```
Time, ms | Voltage, V
1.1 | 3.4
1.4 | 2.7
2.3 | 2.9
2.4 | 2.8
3.7 | 2.9
```
Where `Time, ms` would be X, and `Voltage, V` would be Y. I tried expressing X as a `DateAxis`, but it's trying to interpret the floating X values as either Unix timestamps or as something else. If there was a `DateAxis` that would not try to perform any date guessing and just printed the actual provided values yet it had all the other featues  a `DateAxis` can provide (I mean tooltips, Y autoscaling etc), it would be perfect for the job.

But I guess this is getting a little out of scope of the original question, so I suppose this issue can be closed now.

Thanks again for your help!

**Comment by martynasma** [comment]
I understand your task at hand. Perhaps it's something to consider for us.

Technically, I bet `DateAxis` can be "hacked" to achieve what you need. E.g. use time units of millisecond:

```
dateAxis.baseUnit = {
  timeUnit: "millisecond"
  count: 1
}
```

Then it would be just up to configuring date formatters to display numbers instead of formatted date/time.

I think it's doable.
