### ISSUE TITLE
How to update config for amcharts4

### ISSUE THREAD

**Issue by Mignon-han** [amcharts/amcharts4#1529]
I find it difficult to update the properties of the chart instance arbitrarily because of the existence of List template

**Comment by martynasma** [comment]
Is that a question?

**Comment by Mignon-han** [comment]
@martynasma  Yes, and I want to kow `how can I import types, such as the type of chart instance, or the type of axis, and the type of parameters that legends can configure?`.

**Comment by Mignon-han** [comment]
@martynasma Yes, it's a question.

```
componentDidUpdate(oldProps) {
    if (oldProps.paddingRight !== this.props.paddingRight) {
      this.chart.paddingRight = this.props.paddingRight;
    }
  }
```

In the example you provided, you simply changed a `paddingRight` attribute.
But now I have a lot of attributes to configure, and they have complex nesting relationships.
In amcharts4, this seems difficult to do.

**Comment by martynasma** [comment]
Do you mean you would rather use JSON object to update a bunch of attributes all at once?

https://www.amcharts.com/docs/v4/concepts/json-config/#Mixed_configuration

You can set `config` property of any object with JSON config, and it will populate it with new properties.

**Comment by Mignon-han** [comment]
Thank you! I'll try.
