### ISSUE TITLE
Question: Can amcharts4 support for ‘Live order book / depth chart(of amcharts3)’?

### ISSUE THREAD

**Issue by yilin0710** [amcharts/amcharts4#153]
I want to use amcharts4 to implement a depth chart, I saw a demo in amcharts3(as the following image shows), but in amcharts4 there's no such examples about it. And I read the documentation(version 4) only find that it supports the 'XY chart series--StepLineSeries', not the 'Step Series' which I looked for. So are there any methods to solve this problem? Thank you!
![depthchart](https://user-images.githubusercontent.com/24372123/42919119-03308d9a-8b43-11e8-921d-a9cd6dee40a4.png)

**Comment by martynasma** [comment]
The short answer is most definitely.

We're going to start porting over all of our v3 demos to v4 soon.

Will let you know when this one is available.

**Comment by yilin0710** [comment]
OK, thank you!

**Comment by martynasma** [comment]
Took a while :)

https://codepen.io/team/amcharts/pen/05485bb10d1144aa8b163fd08dcae65b?editors=0010

If it doesn't work, it might be due to CORS. Try loading this URL directly first.

https://poloniex.com/public?command=returnOrderBook&currencyPair=BTC_ETH&depth=50
