### ISSUE TITLE
Modify individual categoryAxis labels

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1533]
I am trying to modify the labels that appear on the categoryAxis to show the categories in different formats. I have tried using the add adapter on the labels template but that changes all of the labels to be the same.

Is it possible to access each individual label and modify it's value?

Thanks

Iain

**Comment by martynasma** [comment]
How do you want it changed?

**Comment by towsie84** [comment]
I would like to split the label value and only display a section of it

**Comment by martynasma** [comment]
Adapter seems perfect for it. Except maybe you should use adapter for `textOutput` which is a populated final text, versus `text` which is a template.

```
categoryAxis.renderer.labels.template.adapter.add("textOutput", function(text) {
  // do something to text
  // ...
  return text;
});
```

**Comment by towsie84** [comment]
When I try that text comes through as {category} rather than the actual label text.

Thanks

**Comment by martynasma** [comment]
Can you post your whole chart code?

**Comment by towsie84** [comment]
Sorry my bad, I had changed "text" to "textOutput" then it got un-done when I reverted another part of the code. I have put it back in and looks to be working a treat.

Thank you very much for your help.

**Comment by martynasma** [comment]
Perfect. Feel free to close this topic when you're done with it ;)

**Comment by towsie84** [comment]
I have one finally question regarding this if possible? 

The code is designed to allow the user to select the format they want the labels. Is there an easy way to revert the labels back to the original value if requried?

Thanks

**Comment by martynasma** [comment]
You can modify your adapter's code to account for user's preferences.

To force the labels to redraw you can invalidate the axis:

```
categoryAxis.deepInvalidate();
```
