### ISSUE TITLE
Add children to chart.data dynamically without invalidating whole chart?

### ISSUE THREAD

**Issue by sophanox** [amcharts/amcharts4#1536]
Hi there,

I'm wondering if it's possible to dynamically add child data to chart.data keys and have the graph recalculate without having to invalidate it entirely?

E.g., for the sunburst graph, I would like to add a new 'ring' to it without having to completely redraw the entire graph. Is this possible at all?

I've made a fiddle so you can see:

https://jsfiddle.net/s09L6axg/1/

Clicking the 'click' button will trigger data being added resulting in the new 'ring'; however, it needs the invalidation. My question is thus - can that ring just be animated in, without having to completely redraw the entire graph?

Thanks - and thanks for an amazing library :)

**Comment by martynasma** [comment]
No, I'm afraid :( There's currently no way to incrementally add child data.

**Comment by sophanox** [comment]
No problem. Thanks for letting me know!
