### ISSUE TITLE
Poor performance with category and columns

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1537]
I think it's easier to explain with a working example:    
https://jsfiddle.net/2wfcyg3k/   
If you click reload button it will take more than 10 seconds to load the data.   
Is this normal? is a lot of data but not so much, probably 4K columns.  
Any idea about how to optimize this?

**Comment by martynasma** [comment]
4K columns is a lot. I suggest considering using `StepLineSeries` instead.

More details here:
https://www.amcharts.com/docs/v4/concepts/performance/#Column_series

**Comment by enriquepiatti** [comment]
Thanks! I wil try with stepseries, I think it works a bit faster but not sure if enough, maybe is not possible to manage so many elements with SVG?    
I will try to convert them to canvas, not sure if the best solution either, maybe a better solution is to change the "data" depending on the zoom level?

**Comment by martynasma** [comment]
> I will try to convert them to canvas, not sure if the best solution either, maybe a better solution is to change the "data" depending on the zoom level? if you have any recommendation please let me know :)

Well, we do have a feature in todo list for dynamica data granularity, but I'm not sure when it is gonna come out.

Meanwhile, I have this (a bit wonky) demo:
https://codepen.io/team/amcharts/pen/zbyveK?editors=0010

> Also, not related but maybe good to know: when is better to use columns instead of steplineseries if they look the same?

I suppose if you need to have some sort of interactivity, or borders, different colors, or clustered columns, then using actual `ColumnSeries` is the only way to go.

**Comment by enriquepiatti** [comment]
I understand. Thanks for your help!
One more thing, I'm also trying to load "historical" data ondemand, currently I'm trying to do that detecting the panended event and trying to figure out if it's maxPanOut or something like that, but I'm also worried about the performance of adding too much data (so I think I will try to unload some non visible parts too).    
I was wondering if there is an example with something similar, just to avoid reinventing the wheel

**Comment by martynasma** [comment]
Maybe it would be better to just use `start` and `end` properties of the `DateAxis`?

Those should not be affected by `maxPanOut`.

**Comment by enriquepiatti** [comment]
Actually maxPanOut is useful, I want to detect when the user tries to go beyond the current loaded data, and then loadMore (I've done this detecting chart._panEndXRange.start == -chart.cursor.maxPanOut and then in panended load the extra data).    
DateAxis works faster than Category? I'm updating the data every 5min, and adding historical data ondemand, I was worried about performance that's why I've chosen Category (but my axis is actually a timestamp)

**Comment by martynasma** [comment]
> DateAxis works faster than Category?
It depends. With many data items, `DateAxis` is definitely faster.
