### ISSUE TITLE
How can I import and use types in amchart4

### ISSUE THREAD

**Issue by Mignon-han** [amcharts/amcharts4#1539]
Now I just find some types here : https://www.amcharts.com/docs/v4/reference/tag/type/
But there seems to be only a few types here. And I don't know how to import them.

**Comment by martynasma** [comment]
Why would you need to import them? Are you building a TS application and want to use them to strong-type your custom functions?

**Comment by Mignon-han** [comment]
Yes, I use amchart with typescript.

**Comment by martynasma** [comment]
In that case importing a type is like importing any other entity in TS.

We suggest importing all of amCharts using core:

```
import * as am4core from "@amcharts/amcharts4/core";
```

Then you can use type like `am4core.Align`.

**Comment by Mignon-han** [comment]
@martynasma Thanks!

**Comment by roaldjap** [comment]
@martynasma what if I wanted to do it on ES6?

`Attempted import error: 'Align' is not exported from '@amcharts/amcharts4/core' (imported as 'am4core').`

I got this error using `am4core.Align`

**Comment by dreamyguy** [comment]
Also using ES6 and getting this error:

`Attempted import error: 'SVGAttribute' is not exported from '@amcharts/amcharts4/core' (imported as 'am4core').`

when using `am4core.SVGAttribute`
