### ISSUE TITLE
Removing series from chart valueAxis

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1540]
I have a vertically stacked axes chart which allows the user to add multiple axes and series. They can remove a series from the chart or move a series between axes.

The issue I have is that when there is a single series attached to an axis and that series is removed the axis scale remains and when I then move another series to that axis I get an "EventDispatcher is disposed" error.

It seems as if the axis thinks the original series is still attached to it.

**Comment by martynasma** [comment]
To make sure I understand: when series is removed from axis' `series` list or when the the last series in the axis is disposed?

**Comment by towsie84** [comment]
The issues happens when the series is disposed. 

How would I remove the series from the axis series list?

**Comment by towsie84** [comment]
I have checked and the issue is because the series is not being removed from the axis series list. I can clear the list so that all series get removed, but is it possible to remove a specific series from the list?

Thanks

**Comment by towsie84** [comment]
I have been able to figure out how to do this. Thanks for pointing me in the direction of the axis series list.
