### ISSUE TITLE
Color data gaps on charts.

### ISSUE THREAD

**Issue by ModKub** [amcharts/amcharts4#1541]
Hello,

I have a question about gaps in data. 
In this example https://www.amcharts.com/demos/chart-with-gaps-in-data/.
What is the best way to color this gaps between data ?
I know about axis ranges. This is very good solution. But I have to know about start and end of ranges.
In amcharts You count if it's neccesary to display gaps "baseInterval * autoGapCount". 
Is data about gaps (where to start and end gap) stored anywhere in amcharts ? 
Or I have to count it with equation above ?

**Comment by martynasma** [comment]
I'm afraid there are no information stored about the gaps :(

There's an undocumented method to `DateAxis`: `makeGap(currentDataItem, previousDataItem)`.

It will return `true` or `false` if there should be a gap between the two.

So maybe you can just cycle through series' `dataItems` and collect gaps that way?

**Comment by ModKub** [comment]
I see that series.dataItems is an array of objects. But I can't cycle trough that array.
I did for tests something like this: 
```
chart.series.values[0].dataItems.values.map(el => console.log(el))
```
And this returns empty array.

**Comment by martynasma** [comment]
That's because it's not an array. It's an amCharts-specific object `List`, you can cycle through them with an `each()` method.

It's also better to use `getIndex()`, not reference to `values` directly.

```
chart.series.getIndex(0).dataItems.each((el) => {
  console.log(el);
});
```

**Comment by ModKub** [comment]
Thanks for reply. 

You mean forEach() method ? I tested also this method, but didn't work for me.

**Comment by martynasma** [comment]
No, I mean `each()`. Again, this is not `Array` we're dealing with, it's a custom class [`List`](https://www.amcharts.com/docs/v4/reference/list/#each_method).

**Comment by ModKub** [comment]
I tried each method first as You described:
```
chart.series.getIndex(0).dataItems.each((el) => {
  console.log(el);
});
```
,but returns nothing.

**Comment by martynasma** [comment]
You must be calling it before the chart had parsed its data and created data items.

Try wrapping it into and event handler, e.g.:

```
chart.series.events.on("datavalidated", (ev) {
  // ...
});
```

**Comment by ModKub** [comment]
Am I doing something wrong ?
Part of json config:
```
  "series": [
      {
        "type": "LineSeries",
        "connect": false,
        "dataFields": {
          "valueY": "value1",
          "dateX": "date",
        },
        "name": "L1",
        "stroke": "#c90d23",
        "strokeWidth": 2,
        "tooltipText": "L1: {valueY.value}",
        "tooltip": {
          "getFillFromObject": false,
          "background": {
            "fill": "#c90d23",
          },
        },
        "events": {
          "validated": (ev) => countGaps(ev),
        },
      },
```
And function: 
```
countGaps = (ev) => {
    console.log(ev.dataItems);
    const dataItems = ev.dataItems.each((el) => {
      console.log(el);
      return el;
    });
    console.log(dataItems);
  }
```
each() in this case is undefined. Tried a lot of events, in some case each() is undefined in other there is nothing happen

**Comment by ModKub** [comment]
Thank You for your help and patience :)
