### ISSUE TITLE
Breadcrumb in treemap

### ISSUE THREAD

**Issue by renjiie** [amcharts/amcharts4#1542]
How can I change the breadcrumb color in the treemap .

**Comment by martynasma** [comment]
To color text of the NavigationBar use these two lines:

```
chart.navigationBar.links.template.fill = am4core.color('#000');
chart.navigationBar.activeLink.fill = am4core.color('#000');
```

**Comment by renjiie** [comment]
How can I provide a single color to all the treemap segments . random colors are given by default .

**Comment by martynasma** [comment]
Probably the easiest way to do that is to just disable color step:

```
chart.colors.step = 0;
```

If you want to use specific color, modify color list:

```
chart.colors.step = 0;
chart.colors.list = [am4core.color("#f00")];
```

P.S. moving forward, it'd be good if you could open a separate issue for questions not related to the topic of the original issue. Thanks!

**Comment by renjiie** [comment]
appreciate your quick response @martynasma

**Comment by avijsdev** [comment]
How can we customize the breadcrumb look and feel?
