### ISSUE TITLE
bar chart average line 

### ISSUE THREAD

**Issue by karuppasamy20** [amcharts/amcharts4#1543]
bar chart average line like am-chart 3..like below the image in am-chart 4.
![Firefox_Screenshot_2019-08-08T10-46-20 133Z](https://user-images.githubusercontent.com/26301377/62697320-106b3480-b9f8-11e9-9c7a-9fe19f12fb72.png)

**Comment by martynasma** [comment]
In V4 you can use axis ranges to place guides/labels:

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides

**Comment by karuppasamy20** [comment]
Thank u @martynasma

**Comment by ChristopherWesson** [comment]
@martynasma how do you create these using the actual mean or median of a series rather than a simple number as you have shown?
