### ISSUE TITLE
Range label in front of series tooltip [question]

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#1544]
I have a simple value series with bullets tooltip.
If I add a range with label on top of series bullet, series tooltip wont be triggered anymore on mouse hover.
How can I bring series + bullet tooltip in front ?
I've tried using ".toFront()", ".toBack()" but I can't make it work.

![RangeLabelTooltipOnTop](https://user-images.githubusercontent.com/21243081/62709512-30055b80-b9fe-11e9-928b-be332a95437d.gif)

here is pen: https://codepen.io/aniov/pen/wVmVOg?editors=0010

Thank you.

**Comment by martynasma** [comment]
If you don't need any interactivity on the range label, you can simply disable interactions on it to solve the issue:

```
range.label.interactionsEnabled = false;
```

**Comment by aniov** [comment]
Thank you, that should do the trick.

Question:
If the label is covering the bullet series, how can I display the series line and bullet on top ?
![LabelOverSeries](https://user-images.githubusercontent.com/21243081/62740949-e3dc0a80-ba41-11e9-8b69-14153de4c24e.gif)

pen: https://codepen.io/aniov/pen/gVzqLw?editors=0010

**Comment by martynasma** [comment]
Try this:

```
chart.bottomAxesContainer.zIndex = -1000;
```
