### ISSUE TITLE
I want hollow circle legends in line graph like below

### ISSUE THREAD

**Issue by pushprajchaudhary** [amcharts/amcharts4#1545]
![Screenshot 2019-08-08 at 8 04 20 PM](https://user-images.githubusercontent.com/24788190/62712291-2b4da100-ba18-11e9-8a1a-cf947d2411f4.png)

**Comment by martynasma** [comment]
Take a look at this tutorial:
https://www.amcharts.com/docs/v4/concepts/legend/#Customizing_markers

You can customize the actual marker using its `fillOpacity` and `strokeWidth` to achieve what you need.
