### ISSUE TITLE
Tooltip for all category lineSeries when hover single one [question]

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#1547]
I'm having a XY chart with with CategoryAxis and multiple 'LineSeries'.
I want to disable tooltips when hover over categories and show them ONLY when hover over series bullet.
I've made them independent but I want to show all series tooltips from that category when I hover over a single series bullet. For the moment it shows tooltip only for that series.

![HoverOverBulet](https://user-images.githubusercontent.com/21243081/62713177-f84de200-ba04-11e9-8835-a7706ea68a3b.gif)
![HoverOverBuletCategory](https://user-images.githubusercontent.com/21243081/62713182-fa17a580-ba04-11e9-827a-f181f3b0c449.gif)

here is a pen: https://codepen.io/aniov/pen/PMewor?editors=0010

How can I do that?
Thank you.

**Comment by martynasma** [comment]
Here's a version of the chart with the required modifications:

https://codepen.io/team/amcharts/pen/0845c85144133276bbf26b3e7c211aff

Hope the code changes are self-explanatory. Let me know if something does not make sense.

**Comment by aniov** [comment]
Thank you.
In **my project** your solution **is working** fine.

PS:
In your example tooltips sometimes seems to get wrong location.
![SingleTooltipsHover](https://user-images.githubusercontent.com/21243081/62743109-d6c31980-ba49-11e9-8096-f82556c24cf1.gif)

**Comment by martynasma** [comment]
I it's working fine on your end, let's call it a day, and revisit only if wrong tooltip positions show up in prod env :)
