### ISSUE TITLE
Terrible performance with multiple charts on the same page

### ISSUE THREAD

**Issue by calvinanderson** [amcharts/amcharts4#155]
I have recently moved to v4 for an app I am developing for my client.

V3 was able to handle multiple graphs on a page, with between 400-800 datapoints with ease.  It was not the fastest, but it worked.

Since moving to v4 our app has become almost unusable.

Is there anything that can be done to increase performance, disable animations, touch-events etc?

Here is an example codepen: https://codepen.io/calvinanderson/pen/wxzVqx

I am also getting a lot of warnings from Chrome: https://gfycat.com/EducatedGreenAntelope

Edit: Our company owns an AMCharts license, if there is a better place for technical discussion, please let me know.

**Comment by martynasma** [comment]
Before we jump to conclusions that v4 is slower than v3 let's take a breath and remind ourselves that this is a pre-release software :)

We are working furiously on enhancing performance. In several directions in fact:
1. Optimizing initial parsing of data and generation of chart;
2. Overall optimizations by reducing number of elements used;
3. Implementing a queuing mechanism that would make multiple charts load in daisy-chain so they don't hog CPU trying to initialize themselves all at once.

I can't classify this as bug, as there's no single identifiable point of failure to tackle, but rather ongoing effort.

Just wanted to assure you we are aware and are making constant efforts in improving the situation.

---

What can be done right now?

This does not apply for your particular demo, but for anyone else looking: disabling animated theme will surely give your chart a boost.

For this particular demo:
1. Using columns is not particularly useful here. Having 1000 columns crammed into tight space does not result in good UX. Line series would probably convey data better, and would be much much faster.
2. Using `XYChartScrollbar` adds extra 200 columns to the mix. Replacing it with a regular `Scorllbar` would give another boost in performance.

Those are two things that jump out at me.

Neither (or even both) will not make your particular charts superfast, but might improve the situation while we work on engine-level improvements.

---

Strangely, I don't get those warnings in console that you posted. If you want to pursue this, can you please open a new issue for it?

Let's keep this issue as a rally point regarding performance-related discussion if you don't mind. If you do - just go ahead and close it :)

**Comment by calvinanderson** [comment]
Thanks for the feedback.

The reason why we have so many data points on a column is that there is a user-specified option for what time to aggregate the data, and if they select "1 Minute" over a day of records it can result in a large dataset.

We are looking at making the default time interval larger to help offset this.

I have removed the `XYChartScrollbar` entirely and that has helped performance substantially.  

In terms of the console warnings: these are turned off by default in Chrome and you need to select Verbose.

Now another question, I saw issue #68 and I was wondering if this would help at all?  Putting it on the chart and not on a series?  And if so, is there a link or page in the documentation that would explain the syntax for this?

**Comment by martynasma** [comment]
@calvinanderson 

> Now another question, I saw issue #68 and I was wondering if this would help at all? Putting it on the chart and not on a series? And if so, is there a link or page in the documentation that would explain the syntax for this?

If you mean putting whole `chart.data` on the chart or divvying it up directly on `series.data`, the `chart.data` will always win. Especially on large data sets.

There is a brief mention on how to use it here:
https://www.amcharts.com/docs/v4/concepts/series/#Series_specific_data

Although it's not much more than you already know.

P.S. we'll investigate those console warnings. Thanks for the heads up!

**Comment by martynasma** [comment]
@calvinanderson 

We have made some huge performance improvements since you last posted it. While those charts do not perform nowhere near acceptable speed (c'mon admit those 1K-column charts are not particularly reasonable ;) ), you should notice a significant improve.

I'm also not getting performance-related console warnings (in verbose mode) anymore.

We'll continue working on the performance, just wanted to update you about the progress.

**Comment by calvinanderson** [comment]
@martynasma 

Thanks very much, I will do some testing and report back!

**Comment by calvinanderson** [comment]
@martynasma This is looking much better and I am no longer getting those warnings in `core.js`

Thanks very much for your assistance.

**Comment by zeroin** [comment]
Version 64 beta splits long processes into chunks so now even with multiple charts on the same page browser won't freeze. We also improved overall performance in this version.
