### ISSUE TITLE
Question: How to clear a cursors selection

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1550]
Hi I would like to clear the cursors selection via the api but cannot find out how todo this after about 2 hours of trying and reading the docs. 

Thanks

**Comment by zeroin** [comment]
You should simply hide the selection sprite, like:

`chart.cursor.selection.hide();`

https://codepen.io/team/amcharts/pen/WVgzXM?&editable=true

**Comment by jimmykane** [comment]
Yup that did the trick
