### ISSUE TITLE
[question] Start DateAxis from the first date

### ISSUE THREAD

**Issue by a-tarasyuk** [amcharts/amcharts4#1551]
Is it possible to make a chart scaling started from the _first date_ in data and end with the _last date_?

For instance, there is an array of dates started from _11 am_ and ended at _11 am_ the last day.
Is it possible to show _11:00_ as a first label and _11:00_ at last instead of 12:00?
> https://jsfiddle.net/0nhbum2p/2/

![1](https://user-images.githubusercontent.com/509265/62787977-978adc00-bace-11e9-9afd-07e773cdbc6c.jpg)

Also, is it possible to show "fixed" grid border without "breaks"? Like this
![2](https://user-images.githubusercontent.com/509265/62788265-38799700-bacf-11e9-9dd2-39c3574b30ef.png)

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

It's not a guarantee that 11:00 labels will appear, though.

You may need to increase density of labels for that to happen:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Controlling_spacing

Don't understand your second question, I'm afraid. The grid in both pictures looks identical.

**Comment by a-tarasyuk** [comment]
@martynasma Thanks for your answers. 

> Don't understand your second question, I'm afraid. The grid in both pictures looks identical.

 The differences in the left border, on the second image it starts from 0. On the first image, I market useless grid lines by violet lines.

**Comment by martynasma** [comment]
Gotcha. Didn't notice that.

Well, since the star/end grid lines not always coincide with the edge of plot area, it might result in "edgeless" chart.

Increasing density of grid lines like I mentioned above might help.

You can also enable a border all around the plot area as well:

```
chart.plotContainer.stroke = am4core.color("#000");
chart.plotContainer.strokeOpacity = 0.5;
```

**Comment by a-tarasyuk** [comment]
@martynasma thanks
