### ISSUE TITLE
How to control Zoom out button on a Pie chart? 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1554]
Hi, 

`chart.zoomOutButton` dies not exist on Pie chart. 

However the slice plugin adds the button. 

How can we control it?

**Comment by martynasma** [comment]
You can access the instance of the `ZoomOutButton` via plugin's property `zoomOutButton`.

https://www.amcharts.com/docs/v4/reference/slicegrouper/#zoomOutButton_property
