### ISSUE TITLE
Chart data not stretching across entire categoryAxis

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1556]
I have a chart that uses a categoryAxis and when I add a data source that has only two data points the lineSeries does not stretch across the entire x-axis as shown below,

![image](https://user-images.githubusercontent.com/48843852/62873796-e7a8af00-bd17-11e9-9f28-4b385a5f0cd8.png)

I need to ensure that any data starts on the left y-axis and end at the right y-axis.

Thanks

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

**Comment by towsie84** [comment]
Thanks, that worked perfectly
