### ISSUE TITLE
Cloudflare  failure

### ISSUE THREAD

**Issue by AbhiSNSoft** [amcharts/amcharts4#1557]
![Screenshot 2019-08-13 at 3 13 19 PM](https://user-images.githubusercontent.com/42136588/62922004-ed1bfd00-bddc-11e9-993b-9a8c712da5ed.png)

**Comment by martynasma** [comment]
https://status.mediatemple.net/incidents/q5j9y3th8xdc

¯\_(ツ)_/¯
