### ISSUE TITLE
custom data attributes

### ISSUE THREAD

**Issue by nmase88** [amcharts/amcharts4#1558]
How can I/Is it possible to have custom fields in the data object that are not used in the chart but can be used in the 'hit' event? I've been searching the documents for somewhere that I can set a field for it but I have been unable to find anything.

Thanks,
Nick

**Comment by martynasma** [comment]
You can put anything into your data, then just access `dataContext` of the target's dataItem:

```
columnSeries.columns.template.events.on("hit", function(ev) {
  console.log(ev.target.dataItem.dataContext);
});
```

It will contain the original object from data.

**Comment by nmase88** [comment]
I did try that but dataContext came back undefined. I'll try again

**Comment by nmase88** [comment]
when I try and do it with sunburst it doesn't work, i've created a fiddle for it: https://jsfiddle.net/4d7hgxsz/3/

**Comment by nmase88** [comment]
seems to work fine for a radial histogram, am I putting the event on the wrong thing for sunburst?

**Comment by nmase88** [comment]
i've figured it out, needed to do 

series.slices.template.events where as I was just doing series.events
