### ISSUE TITLE
Setting fill colour of SVG bullet

### ISSUE THREAD

**Issue by rcslaney** [amcharts/amcharts4#1559]
Is there a way to set the fill/stroke colour of a custom SVG used as a bullet as an am4core.image? I tried setting the stroke and fill colour but as the SVG is inserted as an image this does not have any effect on it. The same SVG will be used across multiple bullets but will be different colours on each so I can't just change the original SVG.

**Comment by martynasma** [comment]
You can't set a color to a standalone SVG image, sorry.

You would need to use regular `Sprite` as a bullet and set its `path` to an SVG path.

Here's an example:
https://codepen.io/team/amcharts/pen/oNvbENK

Hope this helps.

**Comment by rcslaney** [comment]
That's may just work, is there any reason you set bullet.width and height? They don't seem to change anything.

**Comment by rcslaney** [comment]
Also is it possible to use an adapter to set the path variable? I've tried changing the codepen you sent but it doesn't seem to be working - https://codepen.io/rcslaney/pen/NWKxmNP

**Comment by martynasma** [comment]
Indeed, width/height in this case is redundant because the size is controlled by the path itself.

Also, there is no adapter for `path`.

**Comment by rcslaney** [comment]
Ok, how can I do a series, with two different symbols possible for bullets dependent on the data, with an arbitrary colour also defined in the data?

**Comment by martynasma** [comment]
I suppose you can use propertyFields for the bullet's `path` property, then supply path in data.

https://www.amcharts.com/docs/v4/concepts/data/#Property_fields
