### ISSUE TITLE
"EventDispatcher is disposed" when trying to update imageSeries on a map

### ISSUE THREAD

**Issue by sergiocastrovale** [amcharts/amcharts4#156]
I'm trying to build a map which can be toggled by continent, showing the capital cities for each country of the selected continent like this:

![screenshot_1](https://user-images.githubusercontent.com/8822036/42941662-5e8d7718-8b55-11e8-9348-2bfbc4bb02b7.png)

However, I'm running into an issue when try to switch my mapSeries and getting an `EventDispatcher is disposed` error.

Here's the code (running in a Vue.js component): 

```
    updateContinent (continent) {
      this.selectedContinent = continent
      this.populateMap()
    },
    populateMap () {
      // Add countries which belong to selectedContinent
     // world is a list of countries and their coordinates on the map, 
     // grouped by continent (i.e. `{ EUROPE: { PT: 'Portugal' } })
      this.polygonSeries.include = Object.keys(world[this.selectedContinent])

      // Add data for territories
      // this.territories holds a fetched list of territory objects, grouped by continent too.
     // Each object has a name, latitude and longitude
      this.imageSeries.data = this.territories[this.selectedContinent]
    },
```

I couldn't find any example featuring this kind of toggling so I'm a bit lost - am I doing something wrong by directly changing `data`? And additionally, is overriding `include` in the polygonSeries the best way to switch continents?

**Comment by martynasma** [comment]
Reusing the same series sounds a bit complicated. I would create multiple `MapPolygonSeries` for "all occasions" and would just toggle them as needed.

Here's an example:
https://codepen.io/team/amcharts/pen/YjpveO?editors=0010

That said, changing series' data or includes should not trigger errors. We're going to look into it.

Will update this issue once I had a chance to test it.

**Comment by martynasma** [comment]
OK, so I'm looking into it, and can't seem to be able to reproduce this error.

https://codepen.io/team/amcharts/pen/081f2c0d2a7bc1fc11a8203575b09003/?editors=0010

One issue I noticed that when updating `include`, the polygons that are not included in the new updated list are still there.

However, if that happens together with `data` update, everything seems to work as expected.

I've opened a separate issue for that: #157

Even that might be solved with `series.invalidateData()` call after `include` update.

If you would like to help me with reproducing this error, that would be great. If you'd rather go with the multiple series approach I suggested, that's fine either. Just close the issue when you're done with it :)

**Comment by martynasma** [comment]
@sergiocastrovale 

For the record, I agree with you that disposing the whole map on each update is very inefficient. We should avoid that, especially when there's a API in place allowing dynamic updates.

I'd still go with the separate series approach I mentioned. It doesn't matter if you pre-create them, or create and add them on some click.

Whenever you need some different set of data shown, you crate a new `MapPolygonSeries`, then `hide()` current one and `show()` the new one.

You can also implement some kind of caching mechanism to store series you have already created.

That said, your approach of updating data should work as well, save for the bug noted in #157. I can't seem to be able to reproduce those errors you're having :(

**Comment by sergiocastrovale** [comment]
@martynasma I'm going to try your approach - I've managed to get things to work but they are pretty laggy due to the complete re-rendering and re-fetching of resources.

Won't I be running into #157 though?

What I mean to do is:

* Pre-fetch all continents' info
* Pre-create all `mapPolygonSeries` and only show the default (Europe)
* Toggle as needed

**Comment by Pauan** [comment]
@sergiocastrovale We've fixed a lot of disposer leaks, please try version `4.0.0-beta.36` and let me know if you're still getting the `EventDispatcher is disposed` error or not.

**Comment by sergiocastrovale** [comment]
Hi @Pauan thanks for looking into it - I'm afraid I'm going to be short on time to do that today but I'll update as soon as I can.

**Comment by martynasma** [comment]
@sergiocastrovale 
I'm closing this, but please feel free to post any follow up questions you may have, or if you're still having the issue with the latest version.
