### ISSUE TITLE
Do not want to show tooltip for 0 value bullet in multiline graph. Ref: Image attached.

### ISSUE THREAD

**Issue by pushprajchaudhary** [amcharts/amcharts4#1560]
![Screenshot 2019-08-13 at 6 54 36 PM](https://user-images.githubusercontent.com/24788190/62945238-01232700-bdfc-11e9-9a1e-0396ccadc01d.png)

**Comment by martynasma** [comment]
You can use an adapter for that.

Here's an example:
https://codepen.io/team/amcharts/pen/vMvwpJ

**Comment by pushprajchaudhary** [comment]
Thanks but it is saying "Property 'valueY' does not exist on type 'DataItem'. Did you mean 'values'?ts(2551)". Below is the code.

 function createAxisAndSeries(field, name) {
      const series = chart.series.push(new am4charts.LineSeries());
      series.dataFields.valueY = field;
      series.dataFields.dateX = 'Date';
      series.strokeWidth = 2;
      series.simplifiedProcessing = true;
      series.yAxis = valueAxis;
      series.name = name;
      series.tooltip = undefined;
      series.bullets.push(new am4charts.CircleBullet());
      series.bullets.getIndex(0).tooltipText = '{name}: [bold]{valueY}';
      series.tooltip.label.adapter.add('text', function(text, target) {
        if (target.dataItem && target.dataItem.valueY == 0) {
          return '';
        } else {
          return text;
        }
      });
    }

**Comment by martynasma** [comment]
If you are using it in TypeScript, you may need to provide type to re-assure the compiler that everything is OK:

```
if (target.dataItem && (<am4charts.ColumnSeriesDataItem>target.dataItem).valueY == 0) {
```
