### ISSUE TITLE
Range gridline extention and label overlap

### ISSUE THREAD

**Issue by sailMar** [amcharts/amcharts4#1561]
I would like to create a chart as per the example picture attached.
In the example, Series are: Harris, Brown, George, 
CategoryX are: Pro, Team, Reg, and 
Ranges are: Eastern US and Western US
I tried using ranges but 2 obstacles occurred:
a) I can't find anywhere in docs how to extend range's grid line, below x-axis, as I know it was possible in amcharts 3.
b) If I put range.label.valign set to 'bottom', labels are overlapping with category labels which in my case are selectively offsetted as per the relevant tutorial.![chartex2](https://user-images.githubusercontent.com/54068689/62944309-104aaa80-bde5-11e9-9456-1d931a359ee8.png)
The picture does not represent my real data, is just a good example of how I would like to visualize my data

**Comment by martynasma** [comment]
Something like this?

https://www.amcharts.com/demos/partitioned-bar-chart/

**Comment by sailMar** [comment]
Thank you for you reply, and sorry for the delayed answer, I was in vacation leave.

I have checked the linked demo, but I want vertical columns, guides and ranges. (As shown in the picture I attached)
A workaround I have found is posted here:
https://stackoverflow.com/questions/54112167/amchart-4-axis-range

but sometimes it fail ‘s to compile, because strokeOpasity does not exist in CategoryAxisDataItem.
When it compiles it gives me the desired outcome.

**Comment by martynasma** [comment]
Well, you can have any axis on any direction. So in order to flip the demo, just replace swap all X and Y related parameters places.

**Comment by sailMar** [comment]
So I 've tried your suggestion
for your info, I am using Angular.
Here is a pen of your demo with reversed axes:
https://codepen.io/sailMar/pen/YzKVMvy
if range labels can be manipulated separately (haven't looked into it yet), it will be a  nice outcome.

Here is a snapshot of the outcome I get with typescript and the exact same code as the pen above:

![demoChart](https://user-images.githubusercontent.com/54068689/63851984-ecb86000-c99f-11e9-8cdd-a2c99612d4d8.PNG)

as you can see ranges are missing... Should I be doing something different? I am confused

**Comment by martynasma** [comment]
OK, some other tweaking might also be needed, like reversing axis, positioning labels, etc:

https://codepen.io/team/amcharts/pen/VwZWZpP?editors=0010
