### ISSUE TITLE
When using trendline, main data set is 1 month off

### ISSUE THREAD

**Issue by kelso6969** [amcharts/amcharts4#1565]
I could very easily be doing something wrong here.

https://codepen.io/kels0/pen/eYOJrdR

Im trying to add a trend line, essentially, 2 data points, first and last of the main data set to create an "average" line. I can do this with a another series and having the data embedded into the chart data json, but it seems like a waste to have the same value in there xxx times.

Am I doing something wrong here, or is this not how it's supposed to work?

**Comment by martynasma** [comment]
Why do you have your `new Date(....)` enclosed in quotes?

```
trend.data = [
  { "date": "new Date(2019, 08, 13, 07, 00)", "oosmta": 5966 },
  { "date": "new Date(2019, 08, 13, 12, 55)", "oosmta": 5966 }
];
```

If I removed the quotes, everything works just fine.

**Comment by kelso6969** [comment]
Doh, knew it was something stupid. :) thanks for quick response!
