### ISSUE TITLE
Suggestion: add Conic/Polar gradient

### ISSUE THREAD

**Issue by kubk** [amcharts/amcharts4#1567]
Amcharts4 already allows to use [Linear gradient](https://www.amcharts.com/docs/v4/reference/lineargradient/) and [Radial gradient](https://www.amcharts.com/docs/v4/reference/radialgradient/) to specify a color of chart. It would be nice to also have Conic/Polar gradient built-in.
Example using plain Canvas API: http://jsfiddle.net/m1erickson/w46ps/
We can test conic gradient here: https://codepen.io/kubk/pen/XWrXQoq

**Comment by martynasma** [comment]
I'm afraid we won't be able to implement this. Sorry.

**Comment by kubk** [comment]
@martynasma It's ok. For anyone interested I created a tiny library for rendering conic/polar gradients: https://github.com/kubk/gauge-chart-js
