### ISSUE TITLE
Dynamically updating MapPolygonSeries.include leaves previous `include` elements

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#157]
Example:
https://codepen.io/team/amcharts/pen/081f2c0d2a7bc1fc11a8203575b09003/?editors=0010

**Comment by zeroin** [comment]
This one is tricky, I think at the moment I can suggest to reset data like polygonSeries.data = [] before changing the include. Doing it all the time on our side would result other problems.
