### ISSUE TITLE
Chart disappears with XY cursor zoom

### ISSUE THREAD

**Issue by vanjavidenovic** [amcharts/amcharts4#1571]
Having an issue with the XY chart with Amcharts4 and Angular7. When ever the chart is zoomed, the data disappears from view until it is zoomed out. Have tried older versions of the library too, could it be the amount of data being fed into the chart is too much?

The issue can be seen here: https://codepen.io/vanjavidenovic/pen/dybMEWx?editors=1111

**Comment by martynasma** [comment]
The chart expects data to be ordered in ascending order, whereas yours is in descending, hence the anomaly.

If you can't re-order your data on server-side, you can do so on client-side using JS's `reverse()` method:

```
chart.data = [........].reverse();
```

**Comment by jungti1234** [comment]
@martynasma Wow.. I was troubled with solving same problem. You saved me. Thanks.

**Comment by dulhaniAshish** [comment]
@martynasma Thanks. Took me 2 days to figure out.
