### ISSUE TITLE
Stacked Bar Chart with Scrolling has Poor Performance

### ISSUE THREAD

**Issue by ag1211kb** [amcharts/amcharts4#1573]
Hello,

I'm trying to build a stacked bar chart with scrolling and zoom. The original displayed chart hides and a new, more detailed chart is brought into view when the user reaches a certain level of zoom. 

The more detailed chart has 8 stacked bar charts each with 25 segments for a total of 200 segments.  The problem is zooming and scrolling in the more detailed chart is slow and laggy.
Here's a [demo](https://jsfiddle.net/o6h9s413/1/).

Is there any way to make the scrolling and zooming performance better for this chart, or are we just trying to scroll though too much data?

**Comment by martynasma** [comment]
200 segments does not sound like a lot. We'll investigate if this is something we can optimize and speed up.

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
