### ISSUE TITLE
Legend contentHeight issues (again)

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#1574]
I've encountered this again in my application, legend's contentHeight does not include all elements. 

The closest I get to reproducing it is when I use [codepen](https://codepen.io/npc42/pen/ZZLvaJ?editors=0110) from earlier issue (#1181), and set the chart height to e.g. 500px. When you first toggle the legend on, you'll see it shows countries up to UK only (and the contentHeight in console is 300px. On repeat toggles it goes up to 645, but in my app it stays at a smaller number no matter what — unfortunately, I can't reproduce it exactly.

(also, I can get correct height if I listen to sizechanged in the codepen, but not in my app)

For now it looks like contentHeight is unreliable, I'll probably have to resort to calculate an estimate (thinking # of series multiplied by legend item height, or something — perhaps you could give a better idea). 

It'd be nice if you could get to the bottom of it (another person also saw it in #1431, then fell off the face of the Earth…).

**Comment by zeroin** [comment]
SVG has difficulties to measure size of elements if rendered in a hidden div. So in this case my suggestion would be to listen to "sizechanged" event of a legend, it should help to handle the situation:

https://codepen.io/team/amcharts/pen/aboYEMZ?editors=0110
