### ISSUE TITLE
Q: Flights route map

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#1576]
Hello,

Do you know how can I remove the rectangles in the background of your demo?
https://www.amcharts.com/demos/flight-routes-map/?theme=dark
![Screen Shot 2019-08-19 at 10 31 11 PM](https://user-images.githubusercontent.com/33300743/63313088-574b0b00-c2d1-11e9-9076-5122e6b4d509.png)
 
Many thanks!

**Comment by martynasma** [comment]
This code is responsible in adding the graticules ("rectangles"):

```
var graticuleSeries = chart.series.push(new am4maps.GraticuleSeries());
graticuleSeries.mapLines.template.line.strokeOpacity = 0.05;
```
