### ISSUE TITLE
zoomToMapObject is bugged

### ISSUE THREAD

**Issue by wearemetabolism** [amcharts/amcharts4#1579]
Hi there, it seems that there is some issues with the zoomToMapObject method, sometimes, the view jump to a previously zoomed object or to an unknown area.

You can reproduce easily using the demo at https://www.amcharts.com/docs/v4/tutorials/zooming-to-map-area-on-click/

Here is an example : https://recordit.co/d11PE3PTXI

It seems to be related to the animations, I can't reproduce if wait untill the end of each animations to click on another coutry...

Thank you

**Comment by martynasma** [comment]
I was able to reproduce it after a lot of random clicking/zooming/panning. So there's no sure way, yet.

If you were able to work out an exact workflow to reproduce it, let us know. We're going to take a stab at figuring it out anyway, but it would surely help.

**Comment by wearemetabolism** [comment]
Hey, thank you for your answer, I reproduce each time with this workflow:
- click on a country
- unzoom with the mousewheel
- while the animation is running, pan
- while the animation is running, click on a country

BTW I'm on Win10, Chrome 76

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
