### ISSUE TITLE
Grouping Legends

### ISSUE THREAD

**Issue by Porthorian** [amcharts/amcharts4#1580]
This is not so much an issue but just curious.
I was wondering if this was at all possible.

![image](https://user-images.githubusercontent.com/34264214/63366145-18579c80-c347-11e9-8325-c787007cb19e.png)

This is as far as I got, but it doesn't seem possible to be able to add a container with a border radius like this
![image](https://user-images.githubusercontent.com/34264214/63366228-44731d80-c347-11e9-8e4c-bc3a245b3090.png)

**Comment by martynasma** [comment]
Hm, not really.

Unless you want to create a completely custom `Container`, add other containers to it, then move actual legend items into them by setting their `parent`.

I don't have a such example, tho.

**Comment by Porthorian** [comment]
Hmmm thanks for the quick reply. Will probably go the root of creating these custom containers. https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/#Nesting_containers

Something along those lines.
