### ISSUE TITLE
MapPolygonSeries and MapImageSeries

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#1581]
Hello, 

Is it possible to use both MapPolygonSeries and MapImageSeries together. I want the user to see the country when he/she hovers on the country as well as zoom in when he/she clicks on the country.

In the typescript file:
Line 1084: const worldPolygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
Line 1119 : const originImageSeries = chart.series.push(new am4maps.MapImageSeries());

Code : https://codepen.io/alexandrekang/pen/ZEzBQQd

Many thanks!

**Comment by martynasma** [comment]
Just to make sure I understand you correctly, when user clicks on a country you want to zoom in on it, then show relevant map markers for that country?

You might find the following demo useful:

https://www.amcharts.com/demos/map-image-drill-down/

**Comment by AlexandreKang** [comment]
For your question: it is exactly what I want :)
As for the code, I follow what is written in the documentation:  

      // Create a polygonSeries
      const worldPolygonSeries = chart.series.push(
        new am4maps.MapPolygonSeries()
      );
      worldPolygonSeries.useGeodata = true;
      worldPolygonSeries.fillOpacity = 0.5;
      worldPolygonSeries.exclude = ['AQ'];

      // Create a template for the polygonSeries
      const worldPolygonTemplate = worldPolygonSeries.mapPolygons.template;
      // Use tooltipText attribute to display the country's name when hover
      worldPolygonTemplate.tooltipText = '{name}';
      worldPolygonTemplate.fill = am4core.color('#61605f');

      // Create a function that when on click, it will zoom the click's target (the country)
      worldPolygonTemplate.events.on('hit', (ev) => {
        ev.target.series.chart.zoomToMapObject(ev.target);
        chart.closeAllPopups();
        chart.openPopup("We clicked on <strong> <a href = https://duckduckgo.com/?q=" + (<any>ev.target.dataItem.dataContext).name.replace(/\s/g, "") + "&t=h_&ia=news&iar=news target=_blank>" + (<any>ev.target.dataItem.dataContext).name + "</a> </strong>");
        });


      // Fill with purple color when hovers on the country
      const hs = worldPolygonTemplate.states.create('hover');
      hs.properties.fill = am4core.color('#6037f5');

**Comment by martynasma** [comment]
OK, so what I would do is create a separate `MapImageSeries` for each country.

Add `hit` event on `MapPolygonSeries` polygons. When user clicks on a country, I would `show()` related image series, and `hide()` whatever previous series was displayed before.

Hope that makes sense.

**Comment by AlexandreKang** [comment]
I tried your recommendation but I feel this https://www.amcharts.com/demos/zooming-to-countries-map/ would be more suitable with what I want. I tried to apply it and it still doesn't work. 

Code : https://codepen.io/alexandrekang/pen/ZEzBQQd?editors=0110

In the typescript file, it starts at line 36

**Comment by martynasma** [comment]
I'm sorry, but we don't have capacity to dig down into custom code like that. Sorry :(

It shouldn't be too complicated, though. Taking a line from the demo you mentioned:

```
var lastSelected, lastSelectedImages;
polygonTemplate.events.on("hit", function(ev) {
  if (lastSelected) {
    // This line serves multiple purposes:
    // 1. Clicking a country twice actually de-activates, the line below
    //    de-activates it in advance, so the toggle then re-activates, making it
    //    appear as if it was never de-activated to begin with.
    // 2. Previously activated countries should be de-activated.
    lastSelected.isActive = false;
  }

  ev.target.series.chart.zoomToMapObject(ev.target);
  if (lastSelected !== ev.target) {
    lastSelected = ev.target;

    // Enable related images
    if (lastSelectedImages) {
      lastSelectedImages.hide();
    }

    // Here we create or reuse proper MapImageSeries then show it
    // The id of clicked country is in ev.target.dataItem.dataContext.id
    // ...
    lastSelectedImages = ....;
    lastSelectedImages.show();
  }
});
```

**Comment by AlexandreKang** [comment]
So, I manage to d
