### ISSUE TITLE
Line between Montreal and Canberra

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#1582]
Hello,

Out of curiosity, is it possible to have a continuous line between Monteal and Canberra. See screenshot attached. It's the pink line.

![Screen Shot 2019-08-20 at 10 02 19 PM](https://user-images.githubusercontent.com/33300743/63396856-88414380-c396-11e9-9065-9199bacff7da.png)

Many thanks!

**Comment by martynasma** [comment]
Yes. You;ll have to set `shortestDistance = false` on your line tho.

https://www.amcharts.com/docs/v4/chart-types/map/map-lines/#Curved_vs_straight_line
