### ISSUE TITLE
Treemap Hierarchy

### ISSUE THREAD

**Issue by ClaytonAstrom** [amcharts/amcharts4#1583]
Two questions about the treemap hierarchy interactions - 

1. Is there anyway for children to not inherit parent's color?  When you zoom in on an object to populate each child with a new (or even the same default) set of colors?

2.  Is there anyway to repopulate a legend when you zoom into a node?  Given the data set:
```
[
  { name: "A",
    children: [
        { name: "A1", value: 10 },
        { name: "A2", value: 30 }
    ]},
   { name: "B",
      children: [
        { name: "B1", value: 10 },
        { name: "B2", value: 30 }
    ]}
]
```
Rather than have the legend just be `[ "A", "B" ]` at every depth, can it change to `[ "A1", "A2" ]` when I zoom in on the A node?

**Comment by martynasma** [comment]
> Is there anyway for children to not inherit parent's color? When you zoom in on an object to populate each child with a new (or even the same default) set of colors?

I suppose it's possible by creating a separate `ColorSet` then have adapter which overrides fill for each column:

```
var colors = new am4core.ColorSet();
level1ColumnTemplate.column.adapter.add("fill", function(fill, target) {
  return colors.next();
});
```

https://codepen.io/team/amcharts/pen/24042d4866b1acc16f022da0c77b0f04?editors=0010

> Is there anyway to repopulate a legend when you zoom into a node?

I suppose it should be possible by creating a custom legend, then updating its custom markers on each level change.

But I don't have a demo for that.

Here's more about custom legend:
https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items

Hope this helps.
