### ISSUE TITLE
Is possible get full date value from current position thumb in XYChartScrollbar?

### ISSUE THREAD

**Issue by irekrog** [amcharts/amcharts4#1584]
Is a possible get value from current position of thumb in XYChartScrollbar?

I tried 
`chart.scrollbarX.adapter.add('positionValue', (value) => console.log(value); return value));`

and it returns '2009' but I would like to get full date.

Full example: http://jsfiddle.net/qasbfz8p/1/

**Comment by martynasma** [comment]
When you say "get value" do you mean you want to know the position of the scrollbar when it's updated?

I'm a bit confused about your use of adapter, which is meant to manipulate actual value, not to retrieve it.

**Comment by irekrog** [comment]
@martynasma 
No, I need to get **full date value** from current position of thumbs (start thumb and end thumb). Please look at example on jsfiddle and check values from console.log. There is object with year in `value` for example "2009", but I would like to get full date (for example dd-mm-yyyy).

Yes I know, adapter is confuse here but it is the only way what I found to get value from this but of course it doesnt work as I would like

**Comment by martynasma** [comment]
Easier way would be to use scrollbar's `start` and `end` properties to find relative selection, then convert those to actual dates via `DateAxis` method:

```
var startDate = dateAxis.positionToDate(chart.scrollbarX.start);
var toDate = dateAxis.positionToDate(chart.scrollbarX.end);
```

**Comment by irekrog** [comment]
@martynasma Oh thank you! It works now!
