### ISSUE TITLE
Question: Is it possible via the API to select all zoomed or not area?

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1585]
Question: Is it possible via the API to select all zoomed or not area?

Could you hint me perhaps with an approach  ?

**Comment by martynasma** [comment]
Not sure I follow. Is this about map or chart? And what do you mean by "select"? :)

**Comment by martynasma** [comment]
Gotcha. Hm... I don't think there are any methods to trigger cursor selection via API.

That said, if you need to mark some range on the chart, maybe just create an Axis Range dynamically?

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/
