### ISSUE TITLE
Tooltip text and hover

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#1586]
I manage to make it work the hover, text and zoom in for Canada and USA. I don't understand why for others countries around the world doesn't work:

      // Create map polygon series
      const polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
      const usaSeries = chart.series.push(new am4maps.MapPolygonSeries());
      const canadaSeries = chart.series.push(new am4maps.MapPolygonSeries());

      // Make map load polygon (like country names) data from GeoJSON
      polygonSeries.useGeodata = true;
      polygonSeries.exclude = ['AQ'];
      usaSeries.geodata = am4geodata_usaHigh;
      usaSeries.useGeodata = true;
      canadaSeries.geodata = am4geodata_canadaHigh;
      canadaSeries.useGeodata = true;

      // Configure series
      const polygonTemplate = polygonSeries.mapPolygons.template;
      polygonTemplate.tooltipText = '{name}';
      polygonTemplate.fill = am4core.color('#61605f');
      polygonTemplate.events.on('hit', (ev) => {
      ev.target.series.chart.zoomToMapObject(ev.target);
      });

      const usaTemplate = usaSeries.mapPolygons.template;
      usaTemplate.tooltipText = '{name}';
      usaTemplate.fill = am4core.color('#61605f');
      usaTemplate.events.on('hit', (ev) => {
      ev.target.series.chart.zoomToMapObject(ev.target);
      });

      const canadaTemplate = canadaSeries.mapPolygons.template;
      canadaTemplate.tooltipText = '{name}';
      canadaTemplate.fill = am4core.color('#61605f');
      canadaTemplate.events.on('hit', (ev) => {
      ev.target.series.chart.zoomToMapObject(ev.target);
      });

      const hs = polygonTemplate.states.create('hover');
      hs.properties.fill = am4core.color('#6037f5');
      const hus = usaTemplate.states.create('hover');
      hus.properties.fill = am4core.color('#6037f5');
      const hcan = canadaTemplate.states.create('hover');
      hcan.properties.fill = am4core.color('#6037f5');

**Comment by martynasma** [comment]
Can you post your full map as a codepen?

**Comment by AlexandreKang** [comment]
Hello,
I'm sorry, here is the link: https://codepen.io/alexandrekang/pen/NWKdmzB

**Comment by martynasma** [comment]
I'm sorry but we don't have resources to dig into plain code like this. Sorry.

Can you post a demo that works either plain JS on codepen, or if you need to post it as Angular app, you can do so on codesandbox.io or stackblitz.com.

Thanks.

**Comment by AlexandreKang** [comment]
Hello, here is the stackblitz link: https://stackblitz.com/edit/angular-weqvmz

**Comment by martynasma** [comment]
OK, so the problem is here:

```
polygonSeries.toBack();
```

You send polygon series to back, well beyond all other stuff, so it does not receive any hover events anymore.

**Comment by AlexandreKang** [comment]
It works! Thank you so much! I can't imagine where my project will be without your help!
