### ISSUE TITLE
Line partially display

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#1588]
Is it normal that the line is partially display?

![Screen Shot 2019-08-23 at 7 36 01 AM](https://user-images.githubusercontent.com/33300743/63590066-cc8c3980-c578-11e9-9fa1-f127b0f4fb49.png)

Code: https://codepen.io/alexandrekang/pen/bGbgMNY

Line (1226-1232):       // Line series
      const lineSeries = chart.series.push(new am4maps.MapLineSeries());
      lineSeries.mapLines.template.line.strokeOpacity = 5;
      lineSeries.mapLines.template.shortestDistance = false;
      chart.events.on('ready', (event) => {
        showLines(originImageSeries.dataItems.getIndex(0));
      }, this);

Many thanks!

**Comment by martynasma** [comment]
It looks like MapPolygonSeries has bigger "zindex" than MapLineSeries.

Try creating line series last, or set its `zIndex` to some big number, e.g. 10000.

**Comment by AlexandreKang** [comment]
Unfortunately, adding
      lineSeries.mapLines.template.zIndex = 1000000;
still doesn't work

At line 1230: https://codepen.io/alexandrekang/pen/bGbgMNY

**Comment by martynasma** [comment]
I'd be happy to take a look if you could post it as a working demo either as plain JS or as Angular app on codesandbox.io or stackblitz.com.

**Comment by AlexandreKang** [comment]
Hello, I'm sorry,
Here is the stackblitz link: https://stackblitz.com/edit/angular-weqvmz
Hope it well help you understand the code

**Comment by martynasma** [comment]
OK, so same thing with your other issue.

You send line series `toBack()` which means it goes behind Canada series.

Do this instead:

```
lineSeries.toFront();
```

**Comment by AlexandreKang** [comment]
It works! Thank you so much! I can't imagine where my project will be without your help! :)
