### ISSUE TITLE
Cannot click on Force Directed Link

### ISSUE THREAD

**Issue by ShashankAnantharam** [amcharts/amcharts4#1590]
I have created a force directed graph with nodes and links. I wrote an on-click event for the nodes:

```
series.nodes.template.events.on("up", function (event) {
  var node = event.target;
  node.outerCircle.disabled = !node.outerCircle.disabled;
});
```

However, I also wrote the following code to register a click event on the force directed link but that doesn't work:

```
//NOT WORKING
series.links.template.clickable = true;
series.links.template.strokeWidth = 20;
series.links.template.events.on("hit", function (event) {
  console.log(event);
});
```

Event tooltip text does not show up for the links. I need these for my usecases.

`series.links.template.tooltipText = "123"`

How do I go about fixing this? Is this a new feature yet to be implemented in amcharts?

**Comment by martynasma** [comment]
All interactions are disabled on links by design.

In order for any event to work on those you need to re-enable interactions:

```
series.links.template.interactionsEnabled = true;
```

**Comment by ShashankAnantharam** [comment]
Thanks it is done... Working!!
