### ISSUE TITLE
Format image shape in amcharts force directed tree. 

### ISSUE THREAD

**Issue by ShashankAnantharam** [amcharts/amcharts4#1591]
I have made a force directed tree with one Node that is represented by an image.

series.data = [{
                "name":"Sandwraith",
                "image": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Nigel_Farage_%2845718080574%29_%28cropped%29.jpg"}]

// Configure icons
            var icon = series.nodes.template.createChild(am4core.Image);
            icon.propertyFields.href = "image";
            icon.horizontalCenter = "middle";
            icon.verticalCenter = "middle";
            icon.width = 60;
            icon.height = 60;

The node appears square. I want it to appear circular. 

I have an Image object that has processed the href and gotten a circular image. Is there any way to directly insert the Image object as the Node image? The documentation on this mentions giving image path but not the image object itself.
Or is there any other way within am-charts itself to format the image of the Node?

**Comment by martynasma** [comment]
You can apply a circle mask to the image:

```
var mask = new am4core.Circle();
mask.radius = 30;
icon.mask = mask;
```

**Comment by ShashankAnantharam** [comment]
Still not working! Image on the node is square despite the mask! Is there something else to enable/disable?

**Comment by martynasma** [comment]
Can you post your whole chart on codepen/jsfiddle?

**Comment by ShashankAnantharam** [comment]
chartCode(){
            // Create chart
            var chart = am4core.create("chartdiv", am4plugins_forceDirected.ForceDirectedTree);

            // Create series
            var series = chart.series.push(new am4plugins_forceDirected.ForceDirectedSeries());

            // Set data
            series.data = [{
                "name":"Sandwraith",
                "image": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Nigel_Farage_%2845718080574%29_%28cropped%29.jpg",
            "children": [{
                "name": "Chrome",
                "value": 1,
                "image": "https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-160/icon_chrome.svg"
            }, {
                "name": "Firefox",
                "value": 1,
                "image": "https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-160/icon_firefox.svg"
            }, {
                "name": "Internet Explorer",
                "value": 1,
                "image": "https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-160/icon_ie.svg"
            }, {
                "name": "Safari",
                "value": 1,
                "image": "https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-160/icon_safari.svg"
            }, {
                "name": "Opera",
                "value": 1,
                "image": "https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-160/icon_opera.svg"
            }]
            }];

            // Set up data fields
            series.dataFields.value = "value";
            series.dataFields.name = "name";
            series.dataFields.id = "id";
            series.dataFields.children = "children";
            series.dataFields.linkWith = "link";

            // Add labels
            series.nodes.template.label.text = "{name}";
            series.nodes.template.label.valign = "bottom";
            series.nodes.template.label.fill = am4core.color("#000");
            series.nodes.template.label.dy = 10;
            series.nodes.template.tooltipText = "{name}: [bold]{value}[/]";
            series.nodes.template.label.hidden = true;
            series.fontSize = 10;
            series.minRadius = 30;
            series.maxRadius = 30;

            // Configure circles
            series.nodes.template.circle.disabled = true;
            series.nodes.template.outerCircle.disabled = true;

            // Configure icons
            var icon = series.nodes.template.createChild(am4core.Image);
            icon.propertyFields.href = "image";
            icon.horizontalCenter = "middle";
            icon.verticalCenter = "middle";
            icon.width = 60;
            icon.height = 60;

            var mask = new am4core.Circle();
            mask.fill = am4core.color('#000');
            mask.radius = 30;
            series.nodes.template.mask = mask;
///            icon.mask = mask;
//            icon.mask.disabled = false;
           

            series.centerStrength = 0.2;

            series.nodes.template.events.on("up", function (event) {
                var node = event.target;
                node.outerCircle.disabled = !node.outerCircle.disabled;
              });
              
              //NOT WORKING
              series.links.template.interactionsEnabled = true;
              series.links.template.clickable = true;
              series.links.template.strokeWidth = 20;
              series.links.template.events.on("hit", function (event) {                
                var link = event.target;                
              });
              
    
            this.chart = chart;
      }

      componentDidMount() {
        this.chartCode();
      }
render(){
        return (
            <div>                
                <div id="chartdiv" style={{ width: "100%", height: "500px" }}></div>
            </div>
        );
    }

**Comment by ShashankAnantharam** [comment]
@martynasma I've shared my chart code here. Kindly take a look.

**Comment by ShashankAnantharam** [comment]
@martynasma Here is a link to codepen for same code https://codepen.io/sandwraith/pen/LYPyErV

**Comment by martynasma** [comment]
OK, here's another approach using [`Bullets` plugin](https://www.amcharts.com/docs/v4/tutorials/plugin-bullets/).

```
            var icon = series.nodes.template.createChild(am4plugins_bullets.PinBullet);
            icon.image = new am4core.Image();
            icon.image.propertyFields.href = "image";
            icon.circle.radius = am4core.percent(100);
            icon.circle.strokeWidth = 0;
            icon.background.pointerLength = 0;
            icon.background.disabled = true;
```

**Comment by martynasma** [comment]
https://codepen.io/team/amcharts/pen/84a44875f99ada4004aff1ee042856fd

**Comment by ShashankAnantharam** [comment]
Dear Martynas,
   This approach has worked well for me. However, I am not able to change
the size of the image. Even if I increase the icon.circle.radius and
increase image.width and image.height, the circle increases in size but the
image dimensions stay the same. Code:

var icon = series.nodes.template.createChild(am4plugins_bullets.PinBullet);
            icon.image = new am4core.Image();
            icon.image.propertyFields.href = "image";
            icon.circle.radius = 40;       icon.image.width = 80;
icon.image.height = 80;
            icon.circle.strokeWidth = 0;
            icon.background.pointerLength = 0;
            icon.background.disabled = true;

I have put it in this Codepen here:
https://codepen.io/sandwraith/pen/mdeExeQ
If you notice, the image dimensions for some reason do not change. It is
fixed. That is my problem.
How do I resolve this?
I have also raised an issue on GitHub regarding this. You can answer it
there itself: https://github.com/amcharts/amcharts4/issues/2375
Yours sincerely,
Shashank
