### ISSUE TITLE
LabelBullet doesn't redraw

### ISSUE THREAD

**Issue by lgerndt** [amcharts/amcharts4#1593]
Hi.  I need to force LabelBullet to redraw when our theme changes, so that it draws with the correct color.  However, I cannot seem to make it redraw.  None of the 'invalidate' methods work as advertised, I also tried changing the text to trigger the redraw, but no matter what I try, it never redraws.  Is there something that comes to mind? 

```
const labelBullet = series.bullets.push(new am4charts.LabelBullet());
this.labelBullet = labelBullet;
labelBullet.label.adapter.add('stroke', this.labelBulletStrokeAdapter);
labelBullet.label.adapter.add('fill', this.labelBulletFillAdapter);
labelBullet.label.adapter.add('visible', this.labelBulletVisibleAdapter);
labelBullet.label.textAlign = 'end';
labelBullet.label.fontSize = 12;
labelBullet.isMeasured = false;
labelBullet.dx = -30;
labelBullet.dy = 30;
```

**Comment by martynasma** [comment]
You may need to trigger redraw of each individual bullet clone, not just the template:

```
labelBullet.clones.each(function(clone) {
  clone.invalidate();
});
```

**Comment by lgerndt** [comment]
unfortunately, no, that doesn't do it either.
