### ISSUE TITLE
ColumnSeries Tooltips overlap and position issues

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#1594]
A couple related issues both with tooltips y positioning on ColumnSeries.

1) If having multiple series, the tooltips always overlap each other, as well as the columns, making all of it impossible to read.

  ![image](https://user-images.githubusercontent.com/3292053/63643853-c04ace00-c697-11e9-9f87-1201d793025d.png)

  Here's the amcharts 3 equivalent where the chart actively tries to not overlap the tooltips, thus extending the arrows:

  ![image](https://user-images.githubusercontent.com/3292053/63643855-d2c50780-c697-11e9-9e12-6715748f93d4.png)

2. The docs say to do `series.columns.template.tooltipY` to make the tooltip positioned at the top of the column. However, this isn't super intuitive on negative values, as it makes the tooltips all still sit at the top instead of reflecting the position.

![image](https://user-images.githubusercontent.com/3292053/63643894-b1b0e680-c698-11e9-8c5e-36bec0a27977.png)

And the v3 equivalent:

![image](https://user-images.githubusercontent.com/3292053/63643897-c4c3b680-c698-11e9-9bc4-9806789502c6.png)

I can override this behavior with an adapter, but there's not any documentation and it isn't very intuitive.

```
series.columns.template.adapter.add('tooltipY', tooltipPositionAdapter);

function tooltipPositionAdapter(value, target) {
  if (target.dataItem && (target.dataItem.valueY < 0)) {
    return target.bbox.height;
  } else {
    return 0;
  }
}
```

It would be nice to have negative values for things like this reversed so tooltipY = 0 works for both positive and negative. Having this adapter also causes the tooltips to flicker when the mouse moves between columns, so isn't ideal.

**Comment by martynasma** [comment]
Can you post your chart online for us to check? I can't seem to be able to reproduce this.

![image](https://user-images.githubusercontent.com/1458520/63645881-fd52a700-c70f-11e9-9c38-ebd69e9ece0c.png)

https://codepen.io/team/amcharts/pen/d2ed9b564e7fe385728492bc6f972f97?editors=0010

**Comment by runfaj** [comment]
@martynasma Here you go: https://jsfiddle.net/runfaj/kq6r5zys/13/

**Comment by martynasma** [comment]
Thanks! We'll look into it.

**Comment by zeroin** [comment]
In order column series to arrange tooltips, the tooltipText should be set on series itself, not on Column template, like:

`series.tooltipText = '{categoryX}: {valueY} {name}';`

**Comment by runfaj** [comment]
Seems unintuitive that tooltipText must be set this way, where the adapter for something like tooltipY needs to be on series.columns.template. I would expect tooltipText to be able to be set both ways without error (which does appear to work, except positioning). However, this fix works, so I'll close the issue. Thanks!
