### ISSUE TITLE
Custom number format function

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#1597]
Maybe I'm missing it in the docs, but I've searched pretty extensively and can't seem to find any way to provide a custom number format function for the value axis. We have a pretty complex set of rules that have been built out for amcharts3 via valueAxis.labelFunction, but I don't see something similar in v4. It looks like there is a more comprehensive number formatter, but it doesn't include any adapters to provide a custom function that can be evaluated on a per-value basis.

For context, we have about 20 chart types that we are trying to upgrade from v3 to v4 and this is the only major thing holding us back, as all of our chart types rely on this custom formatting function in some form or another. Rewriting the function isn't an option, as it contains a lot of rules that can't be converted easily to a number formatter.

Can you guys provide some guidance on accomplishing this? For comparison, I'm also using the necessary formatter for the label bullets like so: `labelBullet.label.adapter.add('text', formatValueAdapter.bind(this, chartInfo, i, vizData, true));`

**Comment by martynasma** [comment]
You can use adapter for those as well:

```
valueAxis.rederer.labels.template.adapter.add("textOutput", function(text, target) {
  // ...
  return text;
});
```
