### ISSUE TITLE
Animation line

### ISSUE THREAD

**Issue by bymagnum** [amcharts/amcharts4#1598]
The ranks chart. Tried everything how to make a line on the chart that will move at the same time, with the same speed along with the point?

![image](https://user-images.githubusercontent.com/33207527/63734132-bc7b9f00-c883-11e9-96a2-0236017286aa.png)

The fact that the series specified animation:
series.interpolationDuration 					= 500;

And here is line horizontal, as for it do 500 delay?

	var range = valueAxis.axisRanges.create();
	range.grid.stroke = am4core.color('#40E0D0');
	range.grid.strokeOpacity = 1;
	range.grid.strokeWidth = 2;
	range.grid.strokeDasharray = '4, 4';
	range.label.background.fill = am4core.color('#40E0D0');                    
	range.label.padding(5, 10, 5, 10);
	range.label.fill = am4core.color("#505050");
	range.interpolationDuration = 500;
	chart.events.on('datavalidated', function() {
		if (series.dataItems.last) {
			range.value = series.dataItems.last.valueY;
			range.label.text = range.value;
		}
	});

**Comment by martynasma** [comment]
This will do the trick:

```
chart.events.on('datavalidated', function() {
  if (series.dataItems.last) {
    range.animate({
      "property": "value",
      "to": series.dataItems.last.valueY
    }, series.interpolationDuration, series.interpolationEasing)
    range.label.text = range.value;
  }
});
```

**Comment by martynasma** [comment]
https://codepen.io/team/amcharts/pen/5fa5290428e6f49d3a68c8d65b043e5b?editors=0010

**Comment by bymagnum** [comment]
thank you very much! three days I could not understand how to do it! that's it in this piece of code-stopped and could not understand how to do it! 

thanks again dear friend!

**Comment by martynasma** [comment]
You're welcome. Feel free to close this issue when you're ready.
