### ISSUE TITLE
It would be great to be able to use the timeline chart in a vertical fashion. Is this possible?

### ISSUE THREAD

**Issue by iamtomhanks** [amcharts/amcharts4#1599]

**Comment by martynasma** [comment]
You mean this?
https://www.amcharts.com/demos/timeline/

**Comment by martynasma** [comment]
It's just a matter of specifying which axis is which, and juggling some other settings like alignment:

https://codepen.io/team/amcharts/pen/gOYWVQg

**Comment by brecriffs** [comment]
Oh yeah very cool! The highlighting to zoom in feature doesn't translate, but maybe I will disable that anyway. Thanks!

**Comment by martynasma** [comment]
OK, feel free to close this when ready.
