### ISSUE TITLE
I'd like to add node dynamically in force directed graph network, is it possible? :question:

### ISSUE THREAD

**Issue by Ganariya** [amcharts/amcharts4#1600]
Hello, I'd like to use this library because the documentation is great and the functions are excellent.

[In this page](https://www.amcharts.com/docs/v4/chart-types/force-directed/),
 I want to add these functions.

1. If I click the screen, we can add a new node into the network dynamically.
2. If I click the node, we can remove this node.
3. If I click the node(right click), we can trigger a javascript event, for example, console.log("hello, world").
4. We can change node property and edge's width in realtime , when we want to change properties.

Is it possible of these functions.

Thank you.

**Comment by martynasma** [comment]
There are no way to incrementally add nodes to a chart. You would need to updated whole of the chart's `data`, I'm afraid.

As for other things, it is possible. You just need to add right events to `series.node.template`, such as `hit` and `doublehit`.

To hide a node, simply call `hide()` method on it. No point in manipulating the data.

E.g.:

```
series.node.template.events.on("hit", function(ev) {
  ev.target.hide();
});
```

The above will hide the whole node when clicked.
