### ISSUE TITLE
Is there a way to show part of chart data at the beginning, then use the scrollbar to see all data?

### ISSUE THREAD

**Issue by yuxuejiao** [amcharts/amcharts4#1601]
If I have 365 days of chart data, then I set the gridIntervals as the following: 
`dateAxis.gridIntervals.setAll([{
    timeUnit: "day",
     count: 1
          }]);
`
There is a problem about chart rendering for the data is too much. 
So I want to ask is there a way to show part of chart data at the beginning, then use the scrollbar to see all data?

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/tutorials/pre-zooming-an-axis/

**Comment by yuxuejiao** [comment]
Thanks a lot!
