### ISSUE TITLE
when i'm trying to download image in map of amcharts4 in angular 7 

### ISSUE THREAD

**Issue by Sunil1997** [amcharts/amcharts4#1602]
when i'm trying to download image in map of amcharts4 in angular 7 it's giving so many error

i used to below syntax,
**this.chart.exporting.getImage("png").then((data) => {
                            img = data;
                            this.stroeImage(img);
                        });** 

i got following error
![1](https://user-images.githubusercontent.com/26225153/63831591-9130a700-c98c-11e9-8b60-4ee0223d1a01.png)

why this kind of errror is thrown when i try to download image using above method

**Comment by martynasma** [comment]
It's trying to download web fonts to depict exported image as closely to original as possible.

You can disable it by disabling `useWebFonts`:

```
chart.exporting.useWebFonts = false;
```

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/concepts/exporting/#Web_fonts

**Comment by Sunil1997** [comment]
Thanks @martynasma ,
      It's worked for me.
