### ISSUE TITLE
isuues related to legend of map in amcharts 4 in angular 7

### ISSUE THREAD

**Issue by Sunil1997** [amcharts/amcharts4#1603]
when i created map in angular 7 everything is working fine. but legend is not worked properly .

In legend, it's not hiding map line according to legend.

This what i write in code,

 var legend = new am4maps.Legend();
                    legend.parent = chart.chartAndLegendContainer;
                    legend.background.fill = am4core.color("#000");
                    legend.background.fillOpacity = 0.05;
                    legend.strokeOpacity = 0.5;
                    legend.width = 120;
                    legend.align = "right";
                    legend.data = [{
                        "name": "Vendor",
                        "fill": am4core.color("#F60F59"),
                        "groupId":"Vendor"
                    }, {
                        "name": "Employee",
                        "fill": am4core.color("#B22507"),
                        "groupId":"Employee"
                    }, {
                        "name": "Customer",
                        "fill": am4core.color("#07B240"),
                        "groupId":"Customer"
                    }
                    ];
                    

but when i click on customer , it's not showing only customer data.
it's not working properly

i'll aslo apply groupId in lineseries but it's not worked.
 var mapMarker1 = imageSeriesTemplate1.createChild(am4core.Sprite);
        mapMarker1.path = "M4 12 A12 12 0 0 1 28 12 C28 20, 16 32, 16 32 C16 32, 4 20 4 12 M11 12 A5 5 0 0 0 21 12 A5 5 0 0 0 11 12 Z";
        mapMarker1.width = 32;
        mapMarker1.height = 32;
        mapMarker1.scale = 0.7;
        mapMarker1.fillOpacity = 0.8;
        mapMarker1.horizontalCenter = "middle";
        mapMarker1.verticalCenter = "bottom";
        mapMarker1.tooltipText = "{title}";
        mapMarker1.propertyFields.fill = "color";
        mapMarker1.name = name;
        mapMarker1.groupId = name;

        imageSeriesTemplate1.propertyFields.latitude = "latitude";
        imageSeriesTemplate1.propertyFields.longitude = "longitude";

 list.push({
                    "latitude": Number(data[i].latitude),
                    "longitude": Number(data[i].longitude),
                    "title": data[i].answerReportValue,
                    "color": chart.colors.getIndex(2).brighten(-0.2),
                    "groupId":name
                });

 var line = lineSeries.mapLines.create();
        line.line.controlPointDistance = -0.3;
        line.line.groupId = name;

**Here name is my data pass id**

**Comment by martynasma** [comment]
You provide `data` directly to legend, so it treats it completely as custom items. No relation with any other map object, hence nothing happening.

If you need to toggle something on the map, you can add `hit` events to legend items, so that you create a function that toggles that particular item. E.g.:

```
legend.itemContainers.template.events.on("hit", function(ev) {
  // ... do something here
});
```

**Comment by Sunil1997** [comment]
okay @martynasma . then how can i add data in legend?
If want to add which map to object?
is there any reference ??

**Comment by martynasma** [comment]
Well, dunno. It's your custom functionality :)

For example, if your legend items correspond to items in some series, you could technically reference them by index:

```
legend.itemContainers.template.events.on("hit", function(ev) {
  series.images.getIndex(ev.target.dataItem.index).hide();
});
```

Or, probably better, refer to original data context of the clicked item to identify what to do with it:

```
legend.itemContainers.template.events.on("hit", function(ev) {
  // use `ev.target.dataItem.dataContext.someFieldInData`
});
```

**Comment by Sunil1997** [comment]
hello @martynasma ,

above solution is not worked for me..

what is series.In my case i used as lineseries of mapcharts

is there any example so i can figure out?

**Comment by martynasma** [comment]
In that case you can hide/show items in `lineSeries.lines`.

There's no example. Sorry.

**Comment by Sunil1997** [comment]
Hello @martynasma ,
I have written below code in my .ts file. It's throw an error in my case

 legend.itemContainers.template.events.on("hit", function(ev) {
            var groupId = ev.target.dataItem.dataContext.groupId;
            console.log(groupId);
            if ( undefined !== ev.target.dataItem.hidden && ev.target.dataItem.hidden ) {
                ev.target.dataItem.hidden = false;
                lineSeries.lines.getIndex(ev.target.dataItem.index).show();
                    } 
                    else {
                      ev.target.dataItem.hidden = true;
                      lineSeries.lines.getIndex(ev.target.dataItem.index).hide();
                    }
          });
**I got below error**
![2](https://user-images.githubusercontent.com/26225153/63992661-84d25880-cb0a-11e9-934d-9e6ec2feedad.png)

**Comment by martynasma** [comment]
I'm terribly sorry, it's `lineSeries.mapLines` (not `lines`).

**Comment by Sunil1997** [comment]
@martynasma 

it's worked first time but when second time i click on that it's throw an error.

  legend.itemContainers.template.events.on("hit", function(ev) {
                        
            var groupId = ev.target.dataItem.dataContext.groupId;
            console.log(groupId);
            if ( undefined !== ev.target.dataItem.hidden && ev.target.dataItem.hidden ) {
                // ev.target.dataItem.hidden = false;
                lineSeries.mapLines.getIndex(ev.target.dataItem.index).show();
                    } else {
                        // ev.target.dataItem.hidden = true;
                        lineSeries.mapLines.getIndex(ev.target.dataItem.index).hide();
                    }
                    // this.chart.legend.validateNow();
            // console.log("clicked on ",ev.target.dataItem.dataContext.);
          });

**can you tell me how to check mapline is hide or show condtion.??**

**Comment by martynasma** [comment]
You can check its `isHidden` and `isHiding` properties.

**Comment by Sunil1997** [comment]
i have try according to you, but it's not worked well what's wrong please tell me

legend.itemContainers.template.events.on("hit", function(ev) {
                        
            var groupId = ev.target.dataItem.dataContext.groupId;
            console.log(groupId);
            if ( ev.target.dataItem.hidden && ev.target.dataItem.isHiding   ) {
                // ev.target.dataItem.hidden = false;
                lineSeries.mapLines.getIndex(ev.target.dataItem.index).show();
                    } else {
                        // ev.target.dataItem.hidden = true;
                        lineSeries.mapLines.getIndex(ev.target.dataItem.index).hide();
                    }
                    // this.chart.legend.validateNow();
            // console.log("clicked on ",ev.target.dataItem.dataContext.);
          });


**giving below error**

![3](https://user-images.githubusercontent.com/26225153/63996179-8c98f980-cb18-11e9-974a-65f3d281eaba.png)

**Comment by martynasma** [comment]
Evidently the index approach does not work. I suppose number of lines in series does not correspond to the number of legend items.

At this point it's becoming a guessing game. If you'd like me to take a further look, please post your working map on codepen or jsfiddle.

**Comment by Sunil1997** [comment]
hello @martynasma ,

here is belove link:
https://codepen.io/sunil1997/pen/KKPvPVR

**Comment by martynasma** [comment]
Thanks, but that's just some code pasted in. It doesn't work.

If you don't want to convert it into a standalone JS demo, you can post your Angular app on codesandbox.io or stackblitz.com.
