### ISSUE TITLE
Disable the "doublehit" event of scrollbar is not work?

### ISSUE THREAD

**Issue by yuxuejiao** [amcharts/amcharts4#1604]
I want to disable the "doublehit" event of scrollbarX, the code is as following:
`chart.scrollbarX.events.disableType("doublehit");`

But it is not work. Is there any problem?

**Comment by martynasma** [comment]
This event is set on a dragger element, not the Scrollbar itself.

Try this:

```
chart.scrollbarX.thumb.events.disableType("doublehit");
```

**Comment by yuxuejiao** [comment]
It works! Thanks for your quick and effective reply!
