### ISSUE TITLE
Synchronized grid with multiple y axes

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#1606]
Hopefully this is a easy question, but is there some similar way to accomplish in v4 what used to be in v3 as chart.synchronizeGrid and valueAxis2.synchronizationMultiplier? Most the examples for 2 axis charts don't appear to have this issue, but my chart definitely has it:

![image](https://user-images.githubusercontent.com/3292053/63869701-d39ab980-c975-11e9-8f6a-c2c1e8009c57.png)

The example here: https://www.amcharts.com/demos/multiple-value-axes/ conveniently doesn't show the horizontal lines, but has the same issue when I re-enable them: http://jsfiddle.net/runfaj/4hbnx9wj/.

In my screenshot above, I have the minGridDistance the same value (24) and I don't have any type of max/min set.

```
  let valueAxis = new am4charts.ValueAxis();
  chartInstance.yAxes.push(valueAxis);
  valueAxis.cursorTooltipEnabled = false;
  valueAxis.fontSize = allLabelFontSize;
  valueAxis.renderer.labels.template.disabled = !axisEnabled;
  valueAxis.renderer.minGridDistance = isExpanded ? 40 : 24; //default 40, this may need to be dynamic based on chart height
  valueAxis.title.fontSize = allTitleFontSize;
  valueAxis.title.text = chartInfo.twoAxesChart ? valueAxisMaxTitle.title : '';

  if (axisNum === 2) {
    valueAxis.renderer.opposite = true;
  }
```

**Comment by martynasma** [comment]
There's currently no way to synchronize grid between multiple value axes, I'm afraid.

Possible workarounds:

1. Disabling grid for one of the axis.
2. Coloring axis and related grid differently.

**Comment by martynasma** [comment]
There's an open enhancement request here: #433

I suggest you follow it for any updates, in case we implement it at some point.

**Comment by runfaj** [comment]
@martynasma Thanks, I'll follow that! I know our stakeholders won't allow an upgrade with visibly so many grid lines, so maybe hiding until that enhancement is the way to go.
