### ISSUE TITLE
How to prevent nodes from coming-close when clicked.

### ISSUE THREAD

**Issue by ShashankAnantharam** [amcharts/amcharts4#1607]
I have created a graph with Firefox as one node connected to Internet Explorer and Chrome.

My problem is that when I click the firefox node, the links to the other two nodes (IE and Chrome) suddenly shorten their length. I need to click the firefox node again to get the links to those two nodes to the original size.

How do I disable this? Even after clicking the node, I need an event to be fired for me to take my own action (I will use the hit event for that) **BUT I do not want the link size to change**. How do I go about this?

Codepen: 
https://codepen.io/sandwraith/pen/GRKEoWJ

**Comment by martynasma** [comment]
Just do this:

```
series.nodes.template.togglable = false;
```

**Comment by martynasma** [comment]
More details here:
https://www.amcharts.com/docs/v4/chart-types/force-directed/#Controlling_toggling_of_nodes
