### ISSUE TITLE
how to handle the chart event if charts more than one, can we write one method for all graphs.

### ISSUE THREAD

**Issue by ssurwasegd** [amcharts/amcharts4#1608]

**Comment by martynasma** [comment]
Conceptual questions about implementation of your app are beyond the scope of amCharts, I'm afraid.

**Comment by ssurwasegd** [comment]
in amchart 3 we achive like this 
AmCharts.addInitHandler(function (ev) {
logic
},["serial"]));

**Comment by martynasma** [comment]
You can use events in amCharts 4 for that. There are plenty that kick in before chart is rendered.

E.g.:

```
chart.events.on("beforedatavalidated", function(ev) {
  // logic
});
```
