### ISSUE TITLE
Programatically zoom In/out

### ISSUE THREAD

**Issue by Bulletninja** [amcharts/amcharts4#1609]
I'm trying to implement this component in react with a slider, but i want that slider to be located outside of the chart itself. Like this:

![Screen Shot 2019-08-29 at 4 02 21 PM](https://user-images.githubusercontent.com/71659/63979635-9b2ed480-ca76-11e9-92ea-f6de5997a192.jpg)

Instead of right next to it. So i basically implemented this using a react reducer and context api. At some point i noticed that updating `chart.scrollbarX.start` and `chart.scrollbarX.end` did update the graph. 

![Screen Shot 2019-08-29 at 4 03 25 PM](https://user-images.githubusercontent.com/71659/63980327-73407080-ca78-11e9-98d4-1de85d1e0b5a.jpg)

The problem is that it only does that once. After that, the graph and the scroll are "unliked" if that makes sense. My guess is that i have to call some kind of dispatcher to propagate the event. Or maybe an adapter but i'm not sure.

Here are 2 gifs:
0.01 step
![](https://i.imgur.com/HZkznnx.gif)

0.1 step
![](https://i.imgur.com/4H4NnZ6.gif)

**Comment by martynasma** [comment]
Not sure I understand. Are you moving out amCharts scrollbar instance somewhere else, or you have some completely different slider you want to use to control the zoom of the chart?

I'd say it's the latter, but the screengrabs confuse me :)

**Comment by Bulletninja** [comment]
Sorry for the confusion, it's the latter!

**Comment by martynasma** [comment]
No worries. Thanks for the clarification.

In that case you should be setting `start` and `end` on the `DateAxis`, not on `Scrollbar`. You don't even need the scrollbar at all if you are going to be using something else.

Here's an example:
https://codepen.io/team/amcharts/pen/a1e77ade0f1604f48e7f10a10d6215b8?editors=1000

**Comment by martynasma** [comment]
An here's a version with jQuery UI Slider:
https://codepen.io/team/amcharts/pen/e14cf69cc89ccace2ba8fb22207632e7?editors=1000

**Comment by Bulletninja** [comment]
Thanks @martynasma, that solved my issue

**Comment by martynasma** [comment]
We've also posted this tutorial:
https://www.amcharts.com/docs/v4/tutorials/zooming-axis-via-api-or-external-scrollbar/
