### ISSUE TITLE
How to set cell and row styles for export excel file

### ISSUE THREAD

**Issue by sonnguyen610** [amcharts/amcharts4#1610]
![Capture](https://user-images.githubusercontent.com/40166074/64005166-042b5080-cb3a-11e9-9cdd-ca16cc5f0dbf.PNG)
I have this excel file style. How can i add border, backgroud ... like this for xlsx export file? Please help. THANKS!

**Comment by martynasma** [comment]
I'm afraid we don't support setting cell styling to XLSX export. Sorry.

**Comment by sonnguyen610** [comment]
> I'm afraid we don't support setting cell styling to XLSX export. Sorry.

Oh, rreally. So, is there any other way to setup excel file using js from amcharts? Please help me!

**Comment by martynasma** [comment]
We're using this library to generate XLSX documents:
https://github.com/sheetjs/js-xlsx

I suppose you can implement your own export.

Here's code responsible for Excel export. Might help in creating your own:

https://github.com/amcharts/amcharts4/blob/66a2202df7a084ff5a4f4d88c40a49e0214cd051/src/.internal/core/export/Export.ts#L2708-L2823

**Comment by sonnguyen610** [comment]
Thanks you so muck! I will try.
