### ISSUE TITLE
Horizontal and Vertical stacked ValueAxis

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1614]
Hi, I am developing a vertically stacked multiple valueAxis chart. Is it possible to also add a horizontally stacked valueAxis?

Thanks

Iain

**Comment by martynasma** [comment]
So like a grid of axes / plot containers? No, I'm afraid, that would be too much, even for amCharts 4 :)

You can create a container and add a grid of individual charts into it, though:
https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/#Adding_charts_to_containers

**Comment by towsie84** [comment]
I have a chart where I can add additional axes and they are stacked vertically as below,

https://www.amcharts.com/demos/vertically-stacked-axes-chart/

Is it possible to then add another axis horizontally like the example below?

https://www.amcharts.com/demos/multiple-value-axes/

Thanks

**Comment by martynasma** [comment]
Nope. The axes are either stacked vertically or horizontally. There's no way to mix them.

Multiple charts within single `Container` might be a better approach as I suggested above.
