### ISSUE TITLE
Solid gauge render glitch

### ISSUE THREAD

**Issue by LorenzoLeonardini** [amcharts/amcharts4#1615]
Hi, I have implemented a solid gauge chart following the [official demo](https://www.amcharts.com/demos/solid-gauge/). However, the rendering glitches out in different ways quite often. (Actually, the amount of glitchy renders is bigger than the correct ones).

![Example glitch n1](https://i.imgur.com/bApgVOG.png)
(ignoring the square edges, last value is not 100%)

![Example glitch n2](https://i.imgur.com/P8qXAZ1.png)

Maybe the problem is linked to decimal values, but it seems weird to me.

Does everyone have any idea on the possible cause? Thank you so much for your help.

This is an example JSON I load, nothing weird:

```json
[{"category":"IpInfo monthly limit","value":"0.20","full":100},{"category":"Daily mail limit","value":"0.00","full":100},{"category":"2 GB pics limit","value":"8.27","full":100}]
``` 

And this is the source code:

```javascript
    let chart = am4core.create("main_gauge_chart", am4charts.RadarChart)

    chart.startAngle = -90
    chart.endAngle = 180
    chart.innerRadius = am4core.percent(20)

    chart.numberFormatter.numberFormat = "#.#'%'"

    let categoryAxis = chart.yAxes.push(new am4charts.CategoryAxis())
    categoryAxis.dataFields.category = "category"
    categoryAxis.renderer.grid.template.location = 0
    categoryAxis.renderer.grid.template.strokeOpacity = 0
    categoryAxis.renderer.labels.template.horizontalCenter = "right"
    categoryAxis.renderer.labels.template.fontWeight = 500
    categoryAxis.renderer.labels.template.adapter.add("fill", (fill, target) => {
        return (target.dataItem.index >= 0) ? chart.colors.getIndex(target.dataItem.index) : fill
    })
    categoryAxis.renderer.minGridDistance = 10

    let valueAxis = chart.xAxes.push(new am4charts.ValueAxis())
    valueAxis.renderer.grid.template.strokeOpacity = 0
    valueAxis.min = 0
    valueAxis.max = 100
    valueAxis.strictMinMax = true

    let series1 = chart.series.push(new am4charts.RadarColumnSeries())
    series1.dataFields.valueX = "full"
    series1.dataFields.categoryY = "category"
    series1.clustered = false
    series1.columns.template.fill = new am4core.InterfaceColorSet().getFor("alternativeBackground")
    series1.columns.template.fillOpacity = 0.08
    series1.columns.template.cornerRadiusTopLeft = 20
    series1.columns.template.strokeWidth = 0
    series1.columns.template.radarColumn.cornerRadius = 20

    let series2 = chart.series.push(new am4charts.RadarColumnSeries())
    series2.dataFields.valueX = "value"
    series2.dataFields.categoryY = "category"
    series2.clustered = false
    series2.columns.template.strokeWidth = 0
    series2.columns.template.tooltipText = "{category}: [bold]{value}[/]"
    series2.columns.template.radarColumn.cornerRadius = 20

    series2.columns.template.adapter.add("fill", (fill, target) => {
        return chart.colors.getIndex(target.dataItem.index)
    })

    chart.cursor = new am4charts.RadarCursor()

    chart.dataSource.url = "general_gauge.php"
    chart.dataSource.reloadFrequency = 60000
```

**Comment by martynasma** [comment]
I'm trying to reproduce the glitch you described:
https://codepen.io/team/amcharts/pen/8e97d7370dfe065c9786a627e3138199?editors=0010

The only "glitch" that I can see is the straight line for the near-zero-value bar. And I even don't know if it's a glitch.

That's how a bar with rounded corners works. It rounds the corners of the bar. If there length of the bar is smaller than corner radius, the corners get smaller. When we have a hairline-thin bar, there are no corners.

I suppose the solution would be to use adapter to hide such small bars altogether:

```
series2.columns.template.adapter.add("fill", (fill, target) => {
  if (target.dataItem.valueX < 1) {
    target.hide();
  }
  return chart.colors.getIndex(target.dataItem.index)
});
```

**Comment by LorenzoLeonardini** [comment]
Your codepen example is giving me the same glitch. However, I've noticed there is no glitch on my mobile phone.

The glitch is present on Google Chrome Version 75.0.3770.90 (Official Build) (64-bit) on Arch Linux.
If someone with the same chrome version has no glitch than maybe there's some problem with my laptop (maybe some bad drivers?). In that case, the issue could be closed.

**Comment by martynasma** [comment]
Mine is Version 76.0.3809.132 (Official Build) (64-bit)

Not sure if Linux releases lag behind, but if they're not, could you please try upgrading Chrome and checking if the glitch persists?

**Comment by LorenzoLeonardini** [comment]
Just updated, no difference.

Probably there is some weird glitch with the opensource video driver

**Comment by martynasma** [comment]
Can't help you with that :(
