### ISSUE TITLE
Radial Chart series color change based on value

### ISSUE THREAD

**Issue by mooreaa** [amcharts/amcharts4#1616]
Hi, I have a radial chart per the example and I would like to change the colors and values of the chart dynamically.

I am able to update values and call invalidateRawData() which animates nicely, but I have not been able to get the color to update. 

I have set the color rules in this adapter:
series2.columns.template.adapter.add("fill", function(fill, target) {
	LOGIC
});

but the only way to get the colors to change is to call invalidateData() which kills the animation.

Appreciate any insight.

I would be fine with using straight up css/js to change the colors if that is an option.

**Comment by ssc-hrep3** [comment]
Could you just use a color which is defined in the data object and change that too if the data changes instead of using an adapter?

`series2.columns.template.propertyFields.fill = "color";`

And then in the data array, add a property `color` to each data item.

```
[{
  label: "First label",
  data: 1234,
  color: am4core.color("#f00")
}, {...}]

**Comment by martynasma** [comment]
@mooreaa Try the following hack before (or immediately after) calling `invalidateRawData()`:

```
series2.columns.each(function(column) {
  column.fill = column.fill;
});
```

This should re-trigger the adapter for fill.

**Comment by mooreaa** [comment]
@martynasma this worked, though there is a bit of delay. 

I am calling this each update. Curious if that will hurt performance. 

I'm plotting live data.
