### ISSUE TITLE
Tooltip text on ValueAxis

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1617]
Is it possible to change the text shown on a series tooltip depending on the value? i.e, if the value was 1 could the tooltip text be modified to "1. On".

Thanks

**Comment by martynasma** [comment]
Yes, you can use an adapter to create special functions that modify tooltip contents:

```
series.tooltip.text.adapter.add("textOutput", function(text, target) {
  // value is probably in target.dataItem.valueY
  // modify and return text accordingly
  return text;
});
```

More about adapters:
https://www.amcharts.com/docs/v4/concepts/adapters/
