### ISSUE TITLE
Fixed Grid Intervals on ValueAxis

### ISSUE THREAD

**Issue by hinterseerflorian93** [amcharts/amcharts4#1619]
Hi,

I'd like to have fixed grid Intervals on my ValueAxis (0, 90, 180, 270, 360).
I already have these properties set:
 ```
     valueAxisX.min = 0;
     valueAxisX.max = 360;
     valueAxisX.strictMinMax = true;
```
And i also experiemented with the `valueAxisX.renderer.minGridDistance` property.

But unfortunately i havent found a way to explicitly set specific grid intervals.
Note: I change the width and height of the chart constantly.

Thanks in advance.

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/tutorials/custom-valueaxis-grid-using-ranges/

**Comment by hinterseerflorian93** [comment]
Thanks a lot. Worked for me!
