### ISSUE TITLE
Unable to fetch the full object I clicked on

### ISSUE THREAD

**Issue by sergiocastrovale** [amcharts/amcharts4#162]
This is somewhat related to #156 (same project), and the full code of this particular part can be found [here](https://github.com/amcharts/amcharts4/issues/156#issuecomment-406583372).

I'm building a world map (split by continent) where I want to have a marker on the capital city of each country. Then, when I `hit` a marker, I need to be able to somehow know which capital I've clicked - either by passing an `id` parameter upon instantiation of the `imageSeries` or by any other way.

The closest example for amcharts v4 I've found relied on adding the `hit` event to the  `imageSeriesTemplate` like this:

```
      // Add countries which belong to selectedContinent
      this.polygonSeries.include = Object.keys(world[this.selectedContinent])

      // Add data for territories
      this.imageSeries.data = this.territories[this.selectedContinent]

      // ...

      let imageSeriesTemplate = imageSeries.mapImages.template
      let circle = imageSeriesTemplate.createChild(am4core.Circle)
      circle.radius = 5
      circle.fill = am4core.color('#deefe1')
      circle.stroke = am4core.color('#367B25')
      circle.nonScaling = true
      circle.tooltipText = '{name} ({continent.name})'

      imageSeriesTemplate.events.on('hit', (e) => { console.log(e.target.dataItem) })
```

However, I can't find any relevant information from the object I've just clicked on anywhere (`id` and `value` are `undefined`). 

![screenshot_2](https://user-images.githubusercontent.com/8822036/43008532-3d592766-8c33-11e8-8735-cb51b953531a.png)

Any idea of what might be missing?

**Comment by dswitzer** [comment]
Try:

imageSeriesTemplate.events.on('hit', (e) => { console.log(e.target.dataItem.dataContext) })

**Comment by sergiocastrovale** [comment]
That's exactly it @dswitzer. Thanks, still getting the hand on the whole docs and examples of v4.

**Comment by gaoshijun1993** [comment]
https://codepen.io/anon/pen/XPRyMB @dswitzer

**Comment by dswitzer** [comment]
@gaoshijun1993 

Unfortunately, I do not know the answer to your question. I've never used a polygon map, so have no experience with them.

It could be a bug and since this issue is closed, I'd suggest you open a new Github issue and let the amCharts team help you out.

**Comment by gaoshijun1993** [comment]
@dswitzer Thanks a lot anyway, I've found the reason😄

**Comment by aidaghazaryan** [comment]
@reuwi hello, I'm facing same issue. What was the reason please? Thanks
