### ISSUE TITLE
Add few methods

### ISSUE THREAD

**Issue by jMoulis** [amcharts/amcharts4#1620]
Hello,
I probably mistaken and those methods exists. I'm using the force tree and build a breadcrumb based on selectedTreeNode. And I needed to create a method to find if an element (dataItem) has parent and get his parent cloneId. Is it useful and then possible to add those methods?
Cheers,
And by the way your work is so impressive

**Comment by martynasma** [comment]
A `ForceDirectedSeriesDataItem` has a [`parentLink`](https://www.amcharts.com/docs/v4/reference/forcedirectedseriesdataitem/#parentLink_property) property.

It in turn has [`source`](https://www.amcharts.com/docs/v4/reference/forcedirectedlink/#source_property) property which is a parent.
