### ISSUE TITLE
Select checkbox and highlight areas map in amcharts04 with Vuejs, typescript

### ISSUE THREAD

**Issue by dacoten** [amcharts/amcharts4#1623]
I am using amCharts04 and Vuejs to follow to article: https://www.amcharts.com/visited_countries/#
But i have trouble when selecting the checkbox to highlight areas map. This is my code:

**Component parent App.vue:**
```
<template>
 <div>
    <div id="main-app"></div>
    <Countries v-bind:listOfCountries="listOfCountries" :changeStateOfCountry="changeStateOfCountry"/>
  </div>
</template>

import * as am4core from "@amcharts/amcharts4/core"
import * as am4maps from "@amcharts/amcharts4/maps"

export default {
  name: 'app',
  components: {
    Countries,
  },
  data() {
    return {
      listOfCountries : [],
    }
  },
  mounted: function() {
    let _this = this;
    let map = am4core.create("main-app", am4maps.MapChart)
    map.geodata = am4geodata_worldLow
    map.projection = new am4maps.projections.Miller()
    let polygonSeries = map.series.push(new am4maps.MapPolygonSeries())
    polygonSeries.useGeodata = true
    // map.zoomOutButton.enable = true;

    let polygonTemplate = polygonSeries.mapPolygons.template;
    polygonTemplate.tooltipText = "{name}";
    polygonTemplate.fill = am4core.color("#B4B4B7");

    // Create hover state and set alternative fill color
    let hs = polygonTemplate.states.create("hover");
    hs.properties.fill = am4core.color("#9EC2F7");

    // Create active state
    let activeState = polygonTemplate.states.create("active");
    activeState.properties.fill = am4core.color("#84ADE9");

    polygonSeries.exclude = ["AQ"];
    // let selectCountries = [];
    polygonTemplate.events.on("hit", function (ev) {
      var data = ev.target.dataItem.dataContext;
      // Create an event to toggle "active" state
      ev.target.isActive = !ev.target.isActive;
    })
  },

  methods: {
    changeStateOfCountry(countries){
      this.listOfCountries = countries;
    },
  beforeDestroy() {
    if (this.map) {
      this.map.dispose()
    }
  }
}
```

**Component parent Countries.vue:**
```
<template>
  <div>
    <b-form-group label="Using options array:">
      <b-form-checkbox-group
        id="checkbox-group"
        v-model="selected"
        :options="options"
        name="flavour"
        @change="changeStateOfCountry($event)"
        >
       </b-form-checkbox-group>
    </b-form-group>
    <ul>
    <li v-for="(country) in listOfCountries" v-bind:key="country">{{country}}</li>
  </ul>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        selected: this.listOfCountries, // Must be an array reference!
        options: [
          { text: 'English', value: 'EN' },
          { text: 'United State', value: 'US' },
          { text: 'Russia', value: 'RU' },
          { text: 'Japan', value: 'JP' }
        ]
      }
    },
    watch: {
        listOfCountries: {
        immediate: true,
        handler() {
            this.changeValueSelection()
        }
       },
    methods: {
        changeValueSelection(){
            this.selected = this.listOfCountries;
        }
    },
    props: {
        listOfCountries: Array,
        changeStateOfCountry: Function
    }
  }
</script>`
```
I can get name of countries when clicking checkbox using changeStateOfCountry() function, but i cannot know how can trigger to **areas map** in **mounted** function.
I hope everyone can help me, thank you so so much. 
Image detail:
![countries](https://user-images.githubusercontent.com/5999144/64222785-58547d00-cf0c-11e9-8546-f3d5ecb89d66.PNG)

**Comment by martynasma** [comment]
To trigger "active" state on a country, simply set its `isActive = true`.

You can retrieve an actual country object using PolygonSeries' `getPolygonById()` method.

Also check this demo:
https://www.amcharts.com/demos/selecting-multiple-areas-map/

**Comment by dacoten** [comment]
@martynasma  Sorry for a stupid question.
I have used: var country = this.polygonSeries.getPolygonById("US"); but country is an array, so i cannot set "active" area map US country. How can i set "active" a country?

**Comment by dacoten** [comment]
@martynasma I have a quick question. If i only use 2 libraries with **map** on my above project, is it free? Sorry to bother you. I have read Free license but i don't know what is "**amCharts attribution**"  in Use anywhere you want as long as you don't mind a small amCharts attribution on charts.
"@amcharts/amcharts4": "^4.5.15",
 "@amcharts/amcharts4-geodata": "^4.1.7",
Thank you so much.

**Comment by martynasma** [comment]
You can use it any way you like. The amCharts attribution comes in a form of a small amCharts logo in the corner of the chart. You don't have to do anything to turn in on, or provide any further attributions.

**Comment by dacoten** [comment]
@martynasma Thank you so so much.

**Comment by 5p1d32-m4n** [comment]
Has anyone ported this to Vue 3 ? I have a project that could use this and I would like to know if I could contact anyone that has done it.
