### ISSUE TITLE
How to dynamically change chart title in JSON-based implementation

### ISSUE THREAD

**Issue by abdfahim** [amcharts/amcharts4#1624]
I tried
`chart.titles.text = "New Title";
  chart.validateNow();`

but seems like validateNow() method is dropped in amcharts4.

Can anyone please suggest the alternative?

Below is my fork to demonstrate the issue
https://codepen.io/abdfahim/pen/zYOPvPx

**Comment by martynasma** [comment]
Try this:

```
chart.titles.getIndex(0).text = "New Title";
```

It should take automatically. No need for additional method calls.
