### ISSUE TITLE
DateAxis labels?

### ISSUE THREAD

**Issue by nikola1970** [amcharts/amcharts4#1625]
Hello, how do we format DateAxis labels? I would like to have it like this:

https://ibb.co/k5KRG1T

I set dateAxis.renderer.minGridDistance = 100 to make ticks and labels more distant one from another, but not sure how could I set labels now, i am getting hours currently for every tick.

Codepen:
https://codepen.io/nikola1970/pen/ExYbKBz

**Comment by martynasma** [comment]
I suggest you start here:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Formatting_date_and_time

**Comment by nikola1970** [comment]
Weird, when i set these two to my codepen:

**Comment by martynasma** [comment]
Well, if your axis in hourly mode, then the "day" format does not apply anymore.

Try "hour".

**Comment by nikola1970** [comment]
Thanks! @martynasma  :)
