### ISSUE TITLE
legend text not visible

### ISSUE THREAD

**Issue by karuppasamy20** [amcharts/amcharts4#1626]
this legend div is rendered but the text is not there. I don't know what problem. kindly check below mentioned screenshot and code.

![image](https://user-images.githubusercontent.com/26301377/64239714-5b586900-cf1e-11e9-878c-1e178dfb9b24.png)

![image](https://user-images.githubusercontent.com/26301377/64239962-c43fe100-cf1e-11e9-8c07-b4d8b7330807.png)

 var legend = new am4charts.Legend();
legend.parent = chart.chartContainer;
legend.itemContainers.template.togglable = false;
legend.marginTop = 20;

let legendContainer = am4core.create("legenddivtop", am4core.Container);
legendContainer.width = am4core.percent(100);
legendContainer.height = am4core.percent(50);
legend.parent = legendContainer;
let markerTemplate = legend.markers.template;
markerTemplate.width = 10;
markerTemplate.height = 10;

series.events.on("ready", function(ev) {

 let data1 = [{name:'greater then potential',fill:'#203864'},{name:'lesser then potential',fill:'#DAE3F3'},{name:'same as potential',fill:'#8EA9DC'}];
 var legenddata = [];
 data1.forEach(function(column) {
   legenddata.push({
     name: column.name,
     fill: column.fill
   });
 });

 legend.data = legenddata;
});

this is not working in production build only.

**Comment by martynasma** [comment]
Check out the note about optimizer here:
https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/

I'm pretty sure that's the issue.

**Comment by karuppasamy20** [comment]
Thank u @martynasma
