### ISSUE TITLE
TypeScript ForceDirectedSeriesDataItem

### ISSUE THREAD

**Issue by jMoulis** [amcharts/amcharts4#1629]
Hi,
I'm using react with typescript and I have a trouble with this error:
It seems that the property 'name' does not exists on type ForceDirectedSeriesDataItem.
Is this a pb with typing definition or it is on my side?

```javascript

interface Props {
  datas: ForceDirectedNode;
  setSelectedNode: Function;
}
const SelectedListItem = ({ datas, setSelectedNode }: Props) => {
  const handleSelectListItem = (response: ForceDirectedNode) => {
    setSelectedNode(response);
    response.setActive(!response.isActive);
  };
  return (
    <>
      <Root>
        {datas.dataItem.children.values.map((item, index) => (
          <ListItem
            key={item.cloneId}
            borderTop={index === 0}
            onClick={() => handleSelectListItem(item.node)}
          >
            <div>
              <Item>{item.cloneId}</Item>
              <Item>{item.name}</Item>
            </div>
            <ButtonWrapper>
              <Button width="3" bgColor="blue" radius={200} />
              <Button bgColor="red" color="#fff" width="3" radius={200} />
            </ButtonWrapper>
          </ListItem>
        ))}
      </Root>
    </>
  );
};
```

**Comment by martynasma** [comment]
How about using `{item.dataContext.name}`?

**Comment by jMoulis** [comment]
Yes. I works. But this raised another pb while typing as well. If I understand dataContext represents all the informations that we can pass to an item. For example I pass the id of my field in case of hit event. But typescript yield telling me that item.dataContext.id doesn't exists so I have to extends the item definition to add dataContext: any.

**Comment by martynasma** [comment]
Yes, you will need to use `<any>` on dataContext because it does not have any specific interface.
