### ISSUE TITLE
the problem of upgrading amcharts

### ISSUE THREAD

**Issue by yuxuejiao** [amcharts/amcharts4#1630]
when I upgrade @amcharts/amcharts4 version from 4.0.1 to 4.5.15, @amcharts/amcharts4-geodata from 4.0.21 to 4.1.7,  the performace of scrollbar sometimes disappear.

the perfomarce of amcharts 4.0.1 is as following:
![image](https://user-images.githubusercontent.com/18752571/64307570-150c1400-cfc9-11e9-857f-fa5e9a3e01f8.png)
the scrollbar of two charts is normally show

the performace of amcharts 4.5.15 is as following:
![image](https://user-images.githubusercontent.com/18752571/64307643-5270a180-cfc9-11e9-8e37-cdc813b58aaa.png)
the problem is the scrollbar of first chart disappear.

the code is all the same, only the version of amcharts is different.

**Comment by martynasma** [comment]
Can you post your chart live somewhere where we can see this behavior?

**Comment by yuxuejiao** [comment]
Sorry,  it is caused by other reason.
