### ISSUE TITLE
Invalid dates when plotContainer is disabled

### ISSUE THREAD

**Issue by paulheijman** [amcharts/amcharts4#1631]
I'm trying to create a date range selector based on https://www.amcharts.com/docs/v4/tutorials/scrollbar-only-xy-chart/

When hovering over the XYChartScrollbar I get "From Invalid date to Invalid date", but when I comment out the line `chart.plotContainer.disabled = true;` it shows the correct range.

Example:
https://codepen.io/team/amcharts/pen/qMOKyp?editors=0010

Thanks

**Comment by martynasma** [comment]
I suppose when you disable plot container, some of the objects do not get instantiated, that are required for calculation of the range.

I suggest using this instead:

```
chart.plotContainer.visible = false;
```

That seems to have the same effect as `disabled` and does not "ruin" the tooltip data.

**Comment by paulheijman** [comment]
Thank you Martynas!
I figured out something like that: `chart.plotContainer.hidden = true;`
Maybe the documentation could be updated...

**Comment by martynasma** [comment]
> Maybe the documentation could be updated...

Good idea. Done!
