### ISSUE TITLE
core.js modifies native `parseInt`

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#1633]
While stepping through some code, I ended up stepping into `parseInt`, which should not happen as it is supposed to be native. When using Chrome dev tools, the file I stepped into seems to come from here according to the sourcemap:
C:/Dropbox/www/amcharts4dev/node_modules/core-js/modules/_parse-int.js

When using Safari's dev tools, it get to:
C:/Dropbox/www/amcharts4dev/node_modules/core-js/modules/es7.string.match-all.js

Maybe `es7.string.match-all` is using `_parse-int` in some way, although I didn't see a direct dependency. In any case, a library that modifies native objects can have unforeseen consequences. Is there a way that this dependency can be removed from Amcharts?

Added a fiddle here:
https://jsfiddle.net/sassomedia/av75wcbt/

The example is using an older version but even the current version (4.5.16) shows the same issue. When `core.js` is removed, `parseInt` can't be stepped into anymore, which would be the expected behavior.

**Comment by Pauan** [comment]
Thanks for the report! This was an issue with the older versions of `core-js`, but it has been fixed in `core-js@3`. We've upgraded `core-js` in amCharts, so this will be fixed in the next version of amCharts.

**Comment by sassomedia** [comment]
Excellent, thanks! 👍

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
