### ISSUE TITLE
Resize Icon Sprite in Map Chart

### ISSUE THREAD

**Issue by carmoreira** [amcharts/amcharts4#1634]
Considering this example:

https://codepen.io/carmoreira/pen/OJLzpxr

The icon doesn't seem to react to any of these parameters:

```
marker.width = 58;
marker.height = 58;
marker.scale = 2;
```
Considering it's a path, I understand why the width/height wouldn't work, but the scale should work, right? Possible bug?

**Comment by martynasma** [comment]
The `nonScaling = true` is preventing its scale to be changed.

I understand however, how this might be inconvenient without being able to set initial scale.

We'll try to figure out if this can somehow resolved.

**Comment by zeroin** [comment]
My recommendation would be to set nonScaling on a image template (also set the tooltipText):
https://codepen.io/team/amcharts/pen/VwZXrXZ

**Comment by carmoreira** [comment]
Thank you @zeroin and @martynasma ! 
This works well for what I need to do.
