### ISSUE TITLE
Using a gauge chart in flask app

### ISSUE THREAD

**Issue by songs2kats** [amcharts/amcharts4#1639]
Hi,

I am trying to use the gauge chart with gradient fill in my flask app to display sentiment score. I need a set hand.value to the score. Can you suggest how I can do this?

**Comment by martynasma** [comment]
Just set `value` property of the hand object.

Or am I missing something here?

Here's an example:
https://www.amcharts.com/demos/animated-gauge/

**Comment by songs2kats** [comment]
As long as I was setting the hand.value to a fixed number say 50, it was working fine. I couldn't get it to take the value dynamically. I have managed to do that now. Thanks for the response.
