### ISSUE TITLE
Getting AMElement.js:297 Error: <rect> attribute width: Expected length, "NaN".

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1640]
Hi after latest version I am getting : `AMElement.js:297 Error: <rect> attribute width: Expected length, "NaN".`

at 

```
/**
     * Sets a set of attributes on a element.
     *
     * @param attributes  An object with attribute names (key) and values
     * @return The same element
     */
    AMElement.prototype.attr = function (attributes) {
        var _this = this;
        $object.each(attributes, function (attributeName, attributeValue) {
            if (!$type.hasValue(attributeValue)) {
                _this.node.removeAttribute(attributeName);
            }
            else {
                // this is for performance testing
                //if(attributeValue == this.node.getAttribute(attributeName)){
                //	console.log(attributeName, attributeValue)
                //}
                _this.node.setAttribute(attributeName, attributeValue);
            }
        });
        return this;
    };
```

**Comment by jimmykane** [comment]
And then a `Chart was not disposed id-22` 

This errors when I create a chart with Angular

**Comment by jimmykane** [comment]
![Screenshot 2019-09-08 at 22 31 08](https://user-images.githubusercontent.com/1268723/64494056-5ed65200-d288-11e9-808e-60f894b0cfe2.png)

**Comment by martynasma** [comment]
For the first error, we'll need some way to reproduce it. Can you post your chart for us to test?

As for the "disposed" warning, we did add console warnings for charts that are not in use but haven't been disposed properly.

Make sure you follow all instructions on destroying the chart objects here:
https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/

**Comment by armanozak** [comment]
Hi @martynasma,

I had exactly the same problem with the **XYChart** in the getting started (w/ Angular) tutorial, but am unable to reproduce it in an isolated environment like StackBlitz or brand new project.

I've put a breakpoint on line 297 of AMElement.js and found out that **amcharts is trying to set `NaN` as width and height for the main `<rect>`** (the one that gives the chart its size). Most probably, the library is trying to reach the DOM before Angular renders it.

I have a workaround which might help @jimmykane or anyone else having this issue. Taking advantage of a [zero-delay timeout](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop#Zero_delays), I could get rid of the error.

```typescript

  ngAfterViewInit() {
    this.zone.runOutsideAngular(() =>
      setTimeout(() => {

        // draw chart here

      }, 0),
    );
  }

```

As for the the "disposed" warning, either the `this.chart.dispose();` does not work or the documentation lacks something, because I have `ngOnDestroy` in place and am disposing the chart as described in the tutorial, but still getting the warning. Even more interesting is the fact that this warning was **thrown without any component being destroyed** and the workaround above fixed it too. 🤷‍♂️

**Comment by jimmykane** [comment]
@armanozak I ll try this asap after updating to latest AMcharts 

Indeed I have the same behaviour: 

> thrown without any component being destroyed

**Comment by yingwei1025** [comment]
Hi, I was using amcharts/amcharts4.6.4", 

And design using Angular Material <mat-tab > and each Tab have different chart on it.
I also had exactly this same problem, by using the solution of @armanozak able to solve it if the chart is on the first tab

Found out this zero delay timeout also unable to solve it when the chart is on 2nd tab. 
If I move that chart to first tab then will be no console error.
```
<mat-tab-group>
    <mat-tab label="1"> 
        <app-chart1></app-chart1>
    </mat-tab>
    <mat-tab label="2"> 
        <app-chart2></app-chart2>
    </mat-tab>
</mat-tab-group>
```

**Comment by jimmykane** [comment]
Unfortunately I cannot test the timeout thingy because my component is created and needs to return a value eg: 

```
protected createChart(chartType?: typeof am4charts.Chart): am4charts.Chart {
    return this.zone.runOutsideAngular(() => {
      this.applyChartStylesFromUserSettings(this.userChartSettings, this.chartTheme);

      // Create a chart
      am4core.options.commercialLicense = true;
      // am4core.options.queue = true // Use this for apearing after the other (eg big data)
      const chart = am4core.create(this.chartDiv.nativeElement, chartType || am4charts.XYChart);
      chart.pixelPerfect = false;
      // chart.dataSource.updateCurrentData = true
      return chart;
    });
  }
```

**Comment by jimmykane** [comment]
Hmmm this is an issue @martynasma  that leads to big memory consumption. 

My elements have a dynamic height and this issue still happens. 

Perhaps a codepen @yingwei1025 and @armanozak ?

**Comment by jimmykane** [comment]
just tested the timeout and same issue with @yingwei1025  on a hidden tab the same message pops up

**Comment by jimmykane** [comment]
@yingwei1025 @armanozak  I fanaly nailed this one 

You need to set a width (and perhaps height) in px to get this message out, avoid the memory leaks etc. 

So before:
```
 <div #chartDiv style="min-width: 100%; width: 100%; min-height: 100vh; height: 100vh"></div>
  <div #legendDiv style="min-width: 100%; width: 100%; height: 10vh; min-height: 10vh;"></div>
```
After

```
  <div #chartDiv style="min-width: 320px; width: 100%; min-height: 100vh; height: 100vh" width="100"></div>
  <div #legendDiv style="min-width: 320px; width: 100%; height: 10vh; min-height: 10vh;"></div>
```

**Comment by jimmykane** [comment]
I still have though the 

```
breadcrumbs.js:64 Chart was not disposed
```

**Comment by armanozak** [comment]
Thanks @jimmykane.

I don’t want to believe this really is the reason. It is 2019 and we all are doing responsive web apps. Setting a fixed width on the container should not be a requirement! 🤦‍♂️

@martynasma, could you please confirm or deny this? Thanks.

**Comment by yburke94** [comment]
The `setTimeout` solution @armanozak posted worked for me as well.
Worth noting we are using angular 9 and it seems others are having the same problem.
See: https://github.com/amcharts/amcharts4/issues/2306
