### ISSUE TITLE
Overlapping label in donut chart

### ISSUE THREAD

**Issue by famithanelofer06** [amcharts/amcharts4#1645]
![image](https://user-images.githubusercontent.com/55138095/64607569-63188180-d3e6-11e9-8548-6486b65e40ee.png)
  var series = this.piediv4.series.push(new am4charts.PieSeries());
      series.dataFields.value = "value";
      series.dataFields.category = "key";
      series.ticks.template.disabled = true;
      series.alignLabels = false;
      series.showOnInit = false;
      series.labels.template.text ="{value.percent.formatNumber('#.0')}%";
      series.labels.template.radius = -60;
      series.labels.template.fill = am4core.color("white");
      series.labels.template.relativeRotation = 90;

I need to change the label which is overlapped outside the chart.

**Comment by martynasma** [comment]
There's really no good way to deal with bunched up labels of very small slices.

I suggest grouping them together using grouper plugin:
https://www.amcharts.com/docs/v4/tutorials/plugin-slice-grouper/
