### ISSUE TITLE
Retrieving value axis when clicked on a series

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#1646]
Is there a way to retrieve the value from the value axis when clicked on a series?

I have a chart where the value axis represent time; I'd like to make this chart clickable. The information I need is the date (i.e. the value of the value axis) on which the user clicked. What can I do to get this information?

Here is the [codepen](https://codepen.io/segolene-albouy/pen/pozLLNw) of what I did.

Thanks!

**Comment by German-Corpaz** [comment]
Try adding this inside seriesConfig()

`  series.columns.template.events.on("hit", function(ev) {
  console.log(ev.target.dataItem.dataContext.year);
}, this);`

**Comment by Segolene-Albouy** [comment]
This works perfectly! Thank you very much :)
