### ISSUE TITLE
Force Directed Tree "Collapsed'ness"

### ISSUE THREAD

**Issue by ct5845** [amcharts/amcharts4#1647]
The forced directed tree doesn't seem to respect sub-collapsed nodes when their parent is opened.

https://codepen.io/ct5845/pen/NWKMxKv?editors=0010

The top level, and the 2nd level "First" node have their collapsed properties set to true. However "First" get's opened when it's parent does. Would be nice to have an option to disallow this, makes navigating the tree in some circumstances much nicer to only focus on the path you want.

**Comment by German-Corpaz** [comment]
You can set the collapsed state when you click a node.

```
networkSeries.nodes.template.events.on("hit", function(ev) {
  ev.target.dataItem.children.values.forEach(function(child){
    child.collapsed=true
  })
}, this);
```

**Comment by martynasma** [comment]
Better yet set `expandAll = false` on your nodes, so they expand only their immediate children, not the whole branch.

https://www.amcharts.com/docs/v4/reference/forcedirectednode/#expandAll_property
