### ISSUE TITLE
Wrong word's size calculation on WordCloud diagram

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#1649]
Example:
https://codepen.io/dmsmaxim/pen/YzKLGEG
For some reason, word sizes differ drastically here. But there is only 2x difference in their weights

**Comment by German-Corpaz** [comment]
Its because there are only 2 values and the chart is using the minFontSize and maxFontSize values (2px and 20px by default)

You can use this to change the values and it will work.
```
series.maxFontSize=100;
series.minFontSize=50;`
```

Another hack you can do is adding an empty value to the set, and setting the minFontSize to 0 like this
```
 {
  "tag": "dummy",
  "weight": 0,
  "color": am4core.color("#000000")
}
// code
series.maxFontSize=100;
series.minFontSize=0;`
```

**Comment by dmsmaxim** [comment]
Thanks. "Another hack you can do is adding an empty value to the set" worked nicely for me
