### ISSUE TITLE
Export Button black background on menu items

### ISSUE THREAD

**Issue by itomasevic** [amcharts/amcharts4#1650]
![exportbutton](https://user-images.githubusercontent.com/44024624/64698219-bfd97200-d4a2-11e9-9053-876458d3acea.jpg)
Hi,
can somebody take a look at this issue, what could be wrong with background on menu items inside export button (all items are black), please take a look at image.
kind regards,
Igor

**Comment by martynasma** [comment]
Most probably some CSS from your web page is interfering with the menu which is in HTML.

You can find out what using browser's dom explorer.

**Comment by itomasevic** [comment]
you were right, found it! 
Thank You martynasma!
