### ISSUE TITLE
How to show only the current name and count in the Tooltip in treemap chart

### ISSUE THREAD

**Issue by renjiie** [amcharts/amcharts4#1653]
In the treemap chart , the tooltip shows the name of the current segment and the previous one . How to hide the previous name and only show the current name with count . 
Find the implementation here in this [link](https://codesandbox.io/s/wispy-sky-lc3sq) . 
Is there any way to drilldown to a single segment onclick of the parent segment it shows all its child segments . Onclick of the child segment , how to drill down to only that particular child segment .

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/chart-types/treemap/#Tooltip_content

P.S. please do not put multiple unrelated questions in the same post. Post a separate issue. Thanks.
