### ISSUE TITLE
Question: Are geojson files also available via cdn?

### ISSUE THREAD

**Issue by carmoreira** [amcharts/amcharts4#1654]
The same way we can access https://www.amcharts.com/lib/4/geodata/worldLow.js
Are the geojson files available in the repo also available via cdn? I couldn't determine if they were, tried a few links. 
Thank you

**Comment by sassomedia** [comment]
@martynasma At some point, these files were all versioned as well but it seems this has changed at some point:
https://www.amcharts.com/lib/version/4.9.30/geodata/worldLow.js is not available anymore, while https://www.amcharts.com/lib/version/4.9.30/maps.js is available. I used the `worldLow.js` as recently as with v4.9.26 but by checking now, it's gone as well.

Is there a reason for having this only available under the latest version with https://www.amcharts.com/lib/4/geodata/worldLow.js? I'm concerned about this updating at some point without me having tested it first.

**Comment by sassomedia** [comment]
Ah, never mind, just saw https://github.com/amcharts/amcharts4/issues/2695.

**Comment by martynasma** [comment]
@sassomedia  geodata version history CDN is back.

We're also now recommending to use `cdn.amcharts.com` domain, though `www.amcharts.com` will work, too.

**Comment by sassomedia** [comment]
@martynasma ok thanks, noted. I'll make updates accordingly. 👍
