### ISSUE TITLE
Three bugs when reducing the height of the graph

### ISSUE THREAD

**Issue by NemoDima** [amcharts/amcharts4#1655]
Hi

Use version "4.5.16" with angular.

When reducing the height of the graph from 250px to 150px, we encountered three problems:
1. The tooltip for the X axis has ceased to be displayed.
2. Signatures of the X axis fit onto the graph.
3. Despite the hide property, the Y axis began to appear.
![150px](https://user-images.githubusercontent.com/43349820/64795924-8cbcde80-d587-11e9-826a-bbab96d1a8ce.png)
![250px](https://user-images.githubusercontent.com/43349820/64797755-8bd97c00-d58a-11e9-90cc-d552052b9023.png)
What additional data should I provide? 

Help me please with this problems.
Regards, Dmytro

**Comment by NemoDima** [comment]
Thanks for the reply.
I'll try to prepare our example at codepen.io service.

**Comment by NemoDima** [comment]
I have prepared our example on codepage.io
https://codepen.io/vovaltus/pen/aboQYVO?editors=0010
But I can't understand why it works %)
@martynasma maybe you can check example and suggest anything for us.
I'll be appreciated for any helps.
Regards, Dmytro

**Comment by martynasma** [comment]
I'm afraid I can't provide any further insight without being able to reproduce it.

Maybe some version we've released afterwards fixed it? :)

Wanna try upgrading to the latest version in your app?

**Comment by NemoDima** [comment]
Thanks.
I'll try and reply after.

**Comment by NemoDima** [comment]
Hi @martynasma 
We reproduce the same result at codepen.io
Step of reproducing:
1. please open https://codepen.io/vovaltus/pen/aboQYVO 
2. try to delete from html part:
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>`
3. wait for updating the view.

Also, I record the video. Please check it too.
[video.zip](https://github.com/amcharts/amcharts4/files/3690374/video.zip)

Regards.
