### ISSUE TITLE
Tooltip in position for a straight line, when added to a shortest distance line (curved) the tooltip shows up under the curve

### ISSUE THREAD

**Issue by mimattie** [amcharts/amcharts4#1657]
I have a map of the world. I use curved lines. When I use curved lines the tooltip is in the wrong position: under the line and offset from the pointer.

When I use straight lines the tooltip is perfectly positioned, but that's unusable because it looks like a cat's cradle.

**Comment by mimattie** [comment]
I tried that, it had no effect.

**Comment by martynasma** [comment]
Can you post your map code on codepen/jsfiddle?
