### ISSUE TITLE
Sankey node coloring

### ISSUE THREAD

**Issue by rchadwic** [amcharts/amcharts4#1658]
There seems to be an issue with the coloring of sankey nodes. In the below example, you'd expect D to be orange, because the documentation states that node colors come from links that originate at the node. It seems like the first layer of nodes takes color from outgoing links, but then next layers take color from the incoming links.

I cant seem to properly figure out how to set the color of every node by assigning to the links. 

chart.data = [
  { "from": "A", "to": "D", "value": 10, color:"red" },
  { "from": "B", "to": "D", "value": 8, color:"green" },
  { "from": "B", "to": "E", "value": 4, color:"green" },
  { "from": "C", "to": "E", "value": 3, color:"blue" },
  { "from": "D", "to": "G", "value": 5, color:"orange" },
  { "from": "D", "to": "I", "value": 2, color:"orange" },
  { "from": "D", "to": "H", "value": 3, color:"orange" },
  { "from": "E", "to": "H", "value": 6, color:"cyan" },
  { "from": "E", "value": 2, color:"red" },
  { "from": "G", "to": "J", "value": 5, color:"red" },
  { "from": "I", "to": "J", "value": 1, color:"red" },
  { "from": "H", "to": "J", "value": 9, color:"red" }
];

https://codepen.io/team/amcharts/pen/MGvRaE

![image](https://user-images.githubusercontent.com/1257870/64882064-4d939980-d62a-11e9-85bb-d698e3613c11.png)

**Comment by martynasma** [comment]
Indeed. Something's off. We're going to look into it.

Working pen:
https://codepen.io/team/amcharts/pen/62d95c31a917540555324fdffdb94897

**Comment by martynasma** [comment]
Turns out it's not a bug.

When `color` data field is set, like in your case the chart acts a bit different - it uses the color of data item where the node name occurred for the first time. So in your case you can solve this by adding data items with only "from" and "color" value specified to the beginning of data, like:

```
chart.data = [  
  { "from": "D", color:"orange" },
  { "from": "A", "to": "D", "value": 10, color:"red" },
  { "from": "B", "to": "D", "value": 8, color:"green" },  
  { "from": "B", "to": "E", "value": 4, color:"green" },
  { "from": "C", "to": "E", "value": 3, color:"blue" },
  { "from": "D", "to": "G", "value": 5, color:"orange" },
  { "from": "D", "to": "I", "value": 2, color:"orange" },
  { "from": "D", "to": "H", "value": 3, color:"orange" },
  { "from": "E", "to": "H", "value": 6, color:"cyan" },
  { "from": "E", "value": 2, color:"red" },
  { "from": "G", "to": "J", "value": 5, color:"red" },
  { "from": "I", "to": "J", "value": 1, color:"red" },
  { "from": "H", "to": "J", "value": 9, color:"red" }
];
```

Updated pen:
https://codepen.io/team/amcharts/pen/62d95c31a917540555324fdffdb94897

P.S. we're going to updated our docs about it to reflect this.

**Comment by rchadwic** [comment]
Excellent!! That means I can move forward without updating the library. Thanks.
