### ISSUE TITLE
Bug: State.properties.minWidth requires original object to have a minWidth value

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#166]
See full code examples and console logs here:
https://codepen.io/notacouch/pen/52542576f10ee6f4d9a4a25dfd861d26?editors=0010

default doesn't have a manually-set `minWidth`:
```javascript
var wideStateA = containerA.states.create('wide');
wideStateA.properties.minWidth = 100;
console.log('containerA minWidth by default? ', containerA.minWidth);
// ^undefined
containerA.setState('wide');
console.log('containerA minWidth in wide state? ', containerA.minWidth);
// ^NaN
```

vs manually-set `minWidth`

```javascript
containerB.minWidth = 0; // minWidth's value is initialized in a sense.
var wideStateB = containerB.states.create('wide');
wideStateB.properties.minWidth = 100;
console.log('containerB minWidth by default? ', containerB.minWidth);
// ^0
containerB.setState('wide');
console.log('containerB minWidth in wide state? ', containerB.minWidth);
// ^100
```

Also, I'm not sure whether to make this a separate issue, but when the animation theme is enabled, and  switching between states through responsive rules, they animate from the original `minWidth`, not the previous state's value.

Say the container's `minWidth` is set to 150, stateA has 300, stateB has 500. If we switch to stateA, the width will animate from 150 to 300. If we then switch to stateB it'll animate from 150 to 500, instead of 300 to 500. See: https://codepen.io/notacouch/pen/5f8299a5af6655f0534e71be6b3b3742?editors=0010 (the responsive width breakpoint is 600px)

**Comment by martynasma** [comment]
We'll need to discuss this. Keep you posted.
