### ISSUE TITLE
LineSeries not respecting categories as unique data rows

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#1660]
Back with another question or bug!

I have the following setup: http://jsfiddle.net/runfaj/zgd5pvL7/ where the categories can be arbitrary names. If I run this fiddle with 2 ColumnSeries, it behaves as expected where there are basically 300+ columns:

![image](https://user-images.githubusercontent.com/3292053/64893721-0a8af380-d635-11e9-85e3-1735842c4373.png)

However, when I do 2 LineSeries, it looks like my toddler got ahold of a crayon and went crazy:

![image](https://user-images.githubusercontent.com/3292053/64893771-2a221c00-d635-11e9-8281-14a83054cf48.png)

Is there a setting I'm missing that will make the line series respect the individual data elements? This also happens when I mix and match column/line where the line doesn't respect those individual elements.

**Comment by martynasma** [comment]
Wow, this is looks super cool. I love id :)

`CategoryAxis` looks at actual category name, not just iterating through data items, so all categories need to be unique.

Since you are display date-based information, I strongly suggest using `DateAxis` instead.

Or, add year to your dates, so that all "categories" are unique.

Well, you'd need to add year to produce proper dates as well :)

**Comment by runfaj** [comment]
@martynasma We don't have control over what the labels will be - they are dynamic based on user selections. Is there some alternative where we could pass a unique key for the charting, but be able to render out the labels for the axis via a different key? For example, if I had each element like so:

```
{
  category_unique: <unique id>,
  category: <name>,
  valueN: <valueN>
}
```

Is there some way to chart of category_unique, but use category as the labels?

**Comment by martynasma** [comment]
You can prefix all categories with some unique number, then strip it off hen showing label.

```
chart.events.on("beforedatavalidated", function(ev) {
  for(var i = 0; i < chart.data.length; i++) {
  	chart.data[i].category += "---" + i;
  }
  console.log(chart.data);
});

categoryAxis.renderer.labels.template.adapter.add("textOutput", function(label) {
  return label ? label.replace(/---.*$/, "") : label;
});

categoryAxis.tooltip.label.adapter.add("textOutput", function(label) {
  return label ? label.replace(/---.*$/, "") : label;
});
```

http://jsfiddle.net/ueb8Ln5y/

**Comment by runfaj** [comment]
That'll work - thanks!
