### ISSUE TITLE
Padding?

### ISSUE THREAD

**Issue by FunkMonkey33** [amcharts/amcharts4#1661]
How do I remove the padding of a chart?  I have tried setting padding to 0 in the chart container CSS, setting flex properties of same, setting the padding properties of the chart (chart.paddingTop = 0 etc), setting the chart's margin properties, setting it's valign to 'top', and setting it's contentValign to 'top'.  Nothing has any effect.

I'm not sure why this is so difficult.  I've spent about 2 hours on it so far.  

![image](https://user-images.githubusercontent.com/1623153/64907224-d3f0bf80-d6ac-11e9-9200-3e448779b13d.png)

**Comment by FunkMonkey33** [comment]
let chart = am4core.create("activeStrategiesChart", am4charts.PieChart);

    chart.data = [
      {
        'priorityId': 1000,
        'name': 'Category 1',
        'numberOfStrategies': 15
      },
      {
        'priorityId': 1001,
        'name': 'Category 2',
        'numberOfStrategies': 9
      },
      {
        'priorityId': 1002,
        'name': 'Category 3',
        'numberOfStrategies': 18
      },
      {
        'priorityId': 1003,
        'name': 'Category 4',
        'numberOfStrategies': 13
      }
    ];

    let pieSeries = chart.series.push(new am4charts.PieSeries());
    pieSeries.dataFields.value = "numberOfStrategies";
    pieSeries.dataFields.category = "name";

    chart.innerRadius = am4core.percent(40);
    chart.paddingTop = 0;
    chart.marginTop = 0;
    chart.valign = 'top';
    chart.contentValign = 'top';

    // add number of strategies
    let label = chart.seriesContainer.createChild(am4core.Label);
    label.text = "55";
    label.horizontalCenter = "middle";
    label.verticalCenter = "middle";
    label.fontSize = 16;
    label.fontWeight = "bold";

    pieSeries.slices.template.stroke = am4core.color("#fff");
    pieSeries.slices.template.strokeWidth = 1;
    pieSeries.slices.template.strokeOpacity = 1;

    pieSeries.labels.template.disabled = true;
    pieSeries.ticks.template.disabled = true;
    pieSeries.slices.template.tooltipText = "";
    pieSeries.slices.template.fillOpacity = 1;

    // tooltip
    pieSeries.slices.template.tooltipHTML = '<div>{category}: {value.value}</div>';

    // legend
    chart.legend = new am4charts.Legend();
    chart.legend.valueLabels.template.text = '{value.value}';
    chart.legend.valueLabels.template.marginLeft = 0;

**Comment by martynasma** [comment]
The pie radius by default is 80% of the available space (to accomodate for labels, pull outs, etc.)

You can set it to 100%:

```
chart.radius = am4core.percent(100);
```
