### ISSUE TITLE
Using pin as a map point

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#1662]
I'm making a map where several series can be located in the same place. I would like to create "pins" on the map, consisting of a circle and a line, like the image below. I don't want to use an svg image of a pin because I want to be able to vary the size of the circle without enlarging the whole pin. Ideally, the entire pin should be a single object.

![pinz](https://user-images.githubusercontent.com/44207487/64964908-5095c080-d89c-11e9-93b7-bc22a2879657.png)

I tried to create two elements (a circle and a triangle) by defining an offset for the circle, but when zooming, the two elements separate, because the offset is fixed to the background map ... and well, this is not very eye appealing anyway. I wanted to try with a line, but since the offset is not expressed in latitude/longitude, I don't know if it's a satisfying solution.

Here's a [codepen](https://codepen.io/segolene-albouy/pen/MWgBdMg) of what I did. I'd like to know the best way to do this.

Thank you very much!

**Comment by martynasma** [comment]
An idea: why don't you use `PinBullet`? They're visually appealing, and any part is configurable individually.

https://www.amcharts.com/docs/v4/tutorials/plugin-bullets/#As_map_markers

**Comment by Segolene-Albouy** [comment]
It's seems to fit my needs! Thank you very much!
