### ISSUE TITLE
breaks chart

### ISSUE THREAD

**Issue by bymagnum** [amcharts/amcharts4#1663]
Hello!

https://codepen.io/pavlok2008/pen/vYBzXdo

why does the chart break when you put more than 3 seconds difference between the lines? 

now there is a difference of 5 seconds...

what needs to be achieved? I want to hide the second line, put series2.strokeWidth = 0;
so the first line was always been in the middle horizontally and adding data addData method

but this does not work, the schedule "breaks". 

I tried to add and separately data, i.e. in each series separately data... the graph also breaks when data is added... 

tried to add just a normal line, horizontally, from the last date and forward, for example 15 minutes... as soon as I start to add data by the addData method-the chart immediately "breaks" in this way as given in the example.

how else can you affect the graph so that when you add live data, the series line is in the middle horizontally? 

the zoom start and end method will not work, I adjust the x axis with them

**Comment by martynasma** [comment]
Can you be more specific what "breaks" in the chart? Do you mean that line curves are a overly "wavy"?
