### ISSUE TITLE
Property 'series' does not exist on type 'Scrollbar' 

### ISSUE THREAD

**Issue by osman144** [amcharts/amcharts4#1666]
As you can see from screenshot. 

Similar issue to https://github.com/amcharts/amcharts4/issues/1443

<img width="733" alt="Screen Shot 2019-09-17 at 7 26 33 PM" src="https://user-images.githubusercontent.com/25594064/65094632-6a5e0300-d983-11e9-8445-906fb5160c99.png">

**Comment by martynasma** [comment]
Yeah, so the type of that accessor is `Scrollbar` hence it pushing out a warning.

Besides doing something radical, like requiring to use generics to specify what kind of scrollbars you will be using when creating chart, or going with an unsafe `any` for the type of that property, there's little how we can fix this transparently.

On your end there are a couple of ways to fix it.

Reassuring TS you are using correct type:

```
(<am4charts.XYChartScrollbar>chart.scrollbarX).series.push(series);
```

Or creating an instance of the object, configuring it, and then setting it back to the chart:

```
let scrollbarX = new XYChartScrollbar();
scrollbarX.series.push(series);
chart.scrollbarX = scrollbarX;
```
