### ISSUE TITLE
Chart Cursor offset for DateAxis

### ISSUE THREAD

**Issue by meijermarcel** [amcharts/amcharts4#1669]
I am trying to add a simple cursor as shown in https://www.amcharts.com/docs/v4/concepts/chart-cursor/

Instead of the vertical cross-hair being aligned with the tip of my cursor on screen, it is offset to the right of the cursor. I am not sure why this is happening when all I'm doing is creating an XYCursor object like they show in the first example and not adding any custom settings.

**Comment by martynasma** [comment]
Do you mean you see cursor line offset on the demo on that tutorial? Or in your own chart?

If it's the latter, can you post your chart as a codepen?
