### ISSUE TITLE
Question: Get new latitude/longitude after dragstop event

### ISSUE THREAD

**Issue by carmoreira** [amcharts/amcharts4#1670]
I'm thinking of building an interface to allow users to change the auto generated labels for regions in the Map Chart:

In this fork, the labels are already draggable.
https://codepen.io/carmoreira/pen/wvwYPwm

Is it possible to get the new coordinates after the label is dragged into a new position?

I have fiddled with svgPointToGeo without success. Is it possible in the current version?

**Comment by martynasma** [comment]
You've close, just need to convert particular label's coordinates to chart's coordinates before converting to lat/long:

```
  var geo = chart.svgPointToGeo(
    am4core.utils.spritePointToSvg({
      x: ev.target.x,
      y: ev.target.y
    }, ev.target)
  );
```

**Comment by carmoreira** [comment]
Amazing @martynasma ! Thank you. 
I have updated the codepen and it's working well. 
Cheers

**Comment by carmoreira** [comment]
Update: the resulting coordinates where wrong, but I found the way to do it thanks to your tip:

`  var geo = chart.svgPointToGeo({
					x: ev.target.parent.x + ev.target.x,
					y: ev.target.parent.y + ev.target.y
				});`
Thanks.
