### ISSUE TITLE
Treemap set current zoom level

### ISSUE THREAD

**Issue by nmase88** [amcharts/amcharts4#1673]
I am trying to refresh the data at a set interval and need to maintain the current zoom level of a drill-down treemap. I've scoured the documentation to try and figure out how to do this without any joy. Could you advise? I tried setting isActive on the new data like other charts but it doesn't work for a treemap it appears.

**Comment by martynasma** [comment]
Take a look at this demo here:
https://codepen.io/team/amcharts/pen/jONKZEe

It contains code that can be used to "restore" drill-down to specific level/node.

Hope you find it useful.

**Comment by nmase88** [comment]
thanks martyn that is exactly what I was after, had a search of the docs and zoomToChartDataItem doesn't come back as a result, not even if I search zoomTo.

**Comment by martynasma** [comment]
Hm, I'm not sure why we used that particular method. I think `zoomToSeriesDataItem` should work just as well.

**Comment by nmase88** [comment]
ah ok great, I've got it sorted now. Thanks for your help :)
