### ISSUE TITLE
Button bug in Mozilla

### ISSUE THREAD

**Issue by ak3895** [amcharts/amcharts4#1674]
![button_mozilla](https://user-images.githubusercontent.com/42930917/65244803-f64d6780-db08-11e9-93ee-73da7c73be53.png)
The graph seems to be fine but the button is not.
The same graph with button comes perfectly in Chrome. 

Followed this tutorial to add a button : [https://www.amcharts.com/docs/v4/tutorials/adding-home-button-to-map-chart/](url)

**Comment by martynasma** [comment]
Can you provide your chart code?

I tried it here:
https://codepen.io/team/amcharts/pen/3bd37edb3b0848996387939b0495c80e?editors=0010

Coming up fine in Firefox.

![image](https://user-images.githubusercontent.com/1458520/65249989-81c0fb80-dafd-11e9-9fa2-d4f52b10d5c6.png)

**Comment by ak3895** [comment]
```		
var home = chart.plotContainer.createChild(am4core.Button);
home.background.cornerRadius(5, 5, 5, 5);
home.paddingRight = 8;
home.paddingLeft = 8;
home.paddingBottom = 4;
home.paddingTop = 4; 
home.align = "right"
home.icon = new am4core.Sprite();
home.icon.path = "M16,8 L14,8 L14,16 L10,16 L10,10 L6,10 L6,16 L2,16 L2,8 L0,8 L8,0 L16,8 Z M16,8";`
```
This is the code I am using for the button.
I have two graphs one below the other .
**In Mozilla**
![screenshot_1](https://user-images.githubusercontent.com/42930917/65322457-87cddf80-dbc4-11e9-81b5-f44f03cdd253.png)


**In Chrome**
![screenshot_2](https://user-images.githubusercontent.com/42930917/65322724-3a9e3d80-dbc5-11e9-909d-4e30106c0669.png)

In Mozilla there is some issue. The pic I have uploaded has a problem on the top graph's button but sometimes it happens in bottom or even both.

**Comment by martynasma** [comment]
Can you post it as a live chart somewhere? I still can't reproduce it:

https://codepen.io/team/amcharts/pen/3bd37edb3b0848996387939b0495c80e?editors=0010

![image](https://user-images.githubusercontent.com/1458520/65368112-f3f02800-dc44-11e9-8905-dc16cd76bf5d.png)

**Comment by ak3895** [comment]
[https://codepen.io/ak3895/full/PoYXEZa](url)
It seems fine on Firefox (Windows) don't know about Firefox (Linux), will check that tomorrow and let you know.
Don't know what is causing that unusual behavior.

Are you testing on a Windows or Linux machine ?

Thanks

**Comment by martynasma** [comment]
Windows and MacOS. We don't test in Linux, I'm afraid.
