### ISSUE TITLE
Start / end properties of scrollbar are ignored in IE

### ISSUE THREAD

**Issue by Aleksandra-K** [amcharts/amcharts4#1675]
While rendering a chart with scrollbar in Interner Explorer 11, "start" / "end" properties of a chart config are ignored. It results in a full-length rect. And, therefore, the only way to get a scroll is to zoom in. However, it is not suitable for the project, pre-zoom is required.
In Google Chrome there is no such problem, everything works as expected.

Here is a part of config:
`scrollbarY: {
    type: "Scrollbar",
    start: 0.45,
    hideGrips: true
},
`

**Comment by martynasma** [comment]
Can you post your whole chart online somewhere? I can't seem to be able to reproduce it:

https://cdpn.io/team/amcharts/debug/bff51c562601b5cbdb9a975e3ee15702

This chart pre-zooms fine for me in IE11.

**Comment by martynasma** [comment]
Ah wait, it's Y axis. In that case there are other factors at play, like playing initial animations which knock off your pre-zoom.

For this case, you may need to set `keepSelection: true` on your Y axis:

```
  "yAxes": [{
    "type": "ValueAxis",
    "keepSelection": true,
    // ...
  }],
```

Updated above example:
https://cdpn.io/team/amcharts/debug/bff51c562601b5cbdb9a975e3ee15702

**Comment by Aleksandra-K** [comment]
Thank you for answers, but it still doesn't work in IE :(

I have vertical chart with scroll by category axis.

Here is the full config:
`CHART_CONFIG = {
    data: [],
    series: [{
        type: "ColumnSeries",
        dataFields: {
            valueX: "value",
            categoryY: "text"
        }
    }],
    xAxes: [{
        type: "ValueAxis"
    }],
    yAxes: [{
        type: "CategoryAxis",
        keepSelection: true,
        dataFields: {
            category: "text"
        }
    }],
    scrollbarY: {
        type: "Scrollbar",
        start: 0.45,
        hideGrips: true
    },
    zoomOutButton: {
        disabled: true
    }
};
`

**Comment by martynasma** [comment]
Thanks. Can you post it on https://codepen.io together with all the data?

**Comment by Aleksandra-K** [comment]
Yes, sure.
Here it is: https://codepen.io/Aleks-k/pen/aboPrdE

**Comment by martynasma** [comment]
Um, I made a copy of your pen (so that I can view it in debug mode in IE):
https://cdpn.io/team/amcharts/debug/62356f7c2bafa541707d37f868feefca

It still pre-zooms fine for me in IE11:

![image](https://user-images.githubusercontent.com/1458520/65417368-8d186d80-de02-11e9-9241-fd614f0667f6.png)

**Comment by Aleksandra-K** [comment]
Hm, also it works fine for me in codepen debug mode.

Thank you for your help! Hope I'll figure out what is the reason for the problem on a project.

**Comment by Aleksandra-K** [comment]
Ok, I dug deeper into the problem and figure out that the problem in dynamic chart data pushing.
If the data is initially in config, everything is fine. 
However, I set config and render chart first and then load data from backend and set them into chart.data. And here IE fails while Chrome doing great.

I updated codepen demo. In my project I'm using react+redux, but here I emulate them with setTimeout.
https://codepen.io/Aleks-k/pen/aboPrdE

It seems that I have to force rerender somehow, but chart.reinit doesn't work.

**Comment by martynasma** [comment]
Well, the chart will tend to zoom out after data update. It should probably not work correctly in Chrome every time as well.

The correct way to do that would be to set axis zoom after data is validated:

```
chart.events.on("datavalidated", function(ev) {
  chart.scrollbarY.start = 0.45;
});
```

**Comment by Aleksandra-K** [comment]
Thank you for the help!)
