### ISSUE TITLE
Remove white space in map using amchart plugin

### ISSUE THREAD

**Issue by JenishaDalin** [amcharts/amcharts4#1677]
`I need map without whitespace`

- Based on dom element size the map is prepared and according to aspect ratio width and height it was rendered with white space, I need map should take all the space of dom element without white space

- In the below pic, red was white space of an SVG and green was my map. I need the map would remove all the white space of an SVG

https://prnt.sc/p8z8z0

**Comment by martynasma** [comment]
How do you imagine that should happen without breaking aspect ratio and without zooming in so that top/bottom map are out of the viewport?
