### ISSUE TITLE
Lines in 100% width line chart with disabled labels do not fill 100% of the container

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1678]

**Comment by algebrathefish** [comment]
Please close this

**Comment by martynasma** [comment]
You might need to also disable chart padding:

```
chart.padding(0, 0, 0, 0);
```

**Comment by algebrathefish** [comment]
Hi @martynasma I did it, but there are still a few pixels between the line and the chart.

I happens if I set the width of the chart in pixels to be equal to the width of the container, too

Here is an image zoomed 

![zoomed image](https://user-images.githubusercontent.com/46368248/65521500-b8ad5d80-debf-11e9-895b-36e1464d8768.png)

And the wider the container, the more space it leaves

**Comment by martynasma** [comment]
In that case:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

**Comment by algebrathefish** [comment]
Hi @martynasma thank you for your help.

Setting categoryAxis.startLocation = 0.5;  and categoryAxis.endLocation = 0; worked.

I would have expected 0 and 0 to be the right values.

Either way, thank you
