### ISSUE TITLE
MapPolygonSeries (MapSeries?) unexpected behaviors with hide/show(), isHidden, hiddenState.isDisposed()

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#168]
I found some quirky behaviors while trying to make MapPolygonSeries hidden by default.

[pen](https://codepen.io/notacouch/pen/2eea3ad335eb794d57eec8ddf531504c?editors=0010) ([live view](https://codepen.io/notacouch/live/2eea3ad335eb794d57eec8ddf531504c)) (convenience menu is pretty tall, sorry about that)

Here are some quirky behaviors (Flash of content/mapPolygon is ~~easier~~ only seen in Chrome ~~than Firefox~~):
-  `mapPolygonSeries.hide()` does not hide by default, nor does it hide after rendering, it does not set `isHidden` to true (See Canada in sample above)
-  `mapPolygonSeries.setState('hidden')`, hides but after rendering causing a flash of polygon(s), does not set `isHidden` to true (See USA in sample above)
-  ~~`mapPolygonSeries.visible = false`, hides but after rendering causing a flash of polygon(s) (See Brazil)~~ _This has been fixed as of beta.38_, see https://github.com/amcharts/amcharts4/issues/93
- ~~`mapPolygonSeries.opacity = 0`,~~  ~~animates after rendering instead of starting off as 0~~ ~~polygons render fully opaque  (See Brazil) _(The animation thing no longer happens as of beta.38, that was in combination with `visible = false`, not sure if that's related.)_~~ _(Checked in, currently beta.47, this is good now.)_
-  At any given time, `mapPolygonSeries.show/hide()` do not animate/fade opacity like polygons would eg `mapPolygonSeries.mapPolygon.getIndex(n).show/hide()` (See all buttons/countries except for Argentina*/Antarctica)
- At any given time, `mapPolygonSeries.hide()` has a delay despite not animating, it is not clear if this is processing or some kind of transitionDuration between states, yet `mapPolygonSeries.show()` works instantaneously.
- I cannot tell when the `hiddenState` is on/off. `mapPolygonSeries.hiddenState.isDisposed()` seems to be  always true. See all series, at all times, even the `labelSeries.hiddenState.isDisposed()` is always true and it is a `mapImageSeries`! _(Checked in, currently beta.47, Brazil is an exception, but it's hidden via `.hide()` once it's validated.)_

*Martynas provided a solution while I was working on this: set the `default`/`hiddenState.properties.opacity` manually (1/0, respectively), which I tried with Argentina and Antarctica. 

I tried to hide Argentina at the onset via `.setState('hidden')`, but like the others, we get a flash of content. Clicking Argentina's `.show()` the first time shows it instantly, but afterwards its `.show()`/`.hide()` starts animating. _(Checked in, currently on beta.47, this no longer flashes, even in Chrome, but the `.show()`/`.hide()` do nothing now.)_

For Antarctica, I  ~~`.hide()` it on the `validated` event (perhaps `inited` event if using `useGeodata = true`)~~ (as of beta.38: ) set `visible = false` and `opacity = 0` at the onset and it works flawlessly - it is hidden at the onset without any flash of polygon(s), and it animates on `show`/`hide()`. _(Checked in, currently beta.47, Antarctica no longer `.show()`/`.hide()`s, so there's some kind of regression/change.)_

edit on July 26th 2018 509pm EST to reflect beta.38 updates.
edit on August 30th 2018 1213am EST to reflect status as of beta.47.

**Comment by notacouch** [comment]
I saw with [beta.37](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta37---2018-07-26) setting `series.visible = false` is a way of hiding a series preemptively. So I tested this with `MapPolygonSeries`. I've updated the pen so that Canada now uses `visible = false` instead of `.hide()`, Brazil no longer uses `visible = false`, Antarctica now uses `visible = false` and `opacity = 0` instead of `hide()` (which previously was done on `validated` event, not at the onset). 

Good news is `visible = false` hides `MapPolygonSeries` by default!

Another change is that it's hard to see the flash of polygons in Firefox now, the effect was just as pronounced before, but not as much now except w/ Brazil's example. Chrome is much better for seeing the flash of polygons. Both experience the `.hide()` delay pretty much the same.

**Comment by zeroin** [comment]
Could you check if you have these issues with current version?

**Comment by notacouch** [comment]
Yes, some of the issues are still present.

Cleaned up the code/tests a bit in a forked [pen](https://codepen.io/team/amcharts/pen/f43f387f703efd3d2138fdfb9b48bd39?editors=0010), [live version](https://codepen.io/team/amcharts/live/f43f387f703efd3d2138fdfb9b48bd39)

We're on beta.63 at the time of this writing/testing.

After creating a `MapPolygonSeries`:

```javascript
  polygonSeries.hide(); // returns undefined, so it's not an animation, i.e. we can't run events on it like events.on("animationended", ...)
  // Expected behavior: starts off hidden
  // Actual behavior: visible
  // See: Canada
```
```javascript
  polygonSeries.setState('hidden');
  // Expected behavior: starts off hidden
  // Actual behavior (Chrome): flash of render then hidden
  // Actual behavior (Firefox): starts off hidden
  // See: USA
```
```javascript
  polygonSeries.opacity = 0;
  // Expected behavior: starts off hidden 
  // Actual behavior: visible
  // See: Brazil
```

In this method, the first `.show()` shows instantly, afterwards both `show()` and `hide()` animate:
```javascript
  // Recommendation
  polygonSeries.defaultState.properties.opacity = 1;
  polygonSeries.hiddenState.properties.opacity = 0;
  // end recommendation
  
  polygonSeries.setState('hidden');
  // Expected behavior: start off as hidden
  // Actual behavior (Chrome): flash of content
  // Actual behavior (FF): start off as hidden
  // See: Argentina
```

This combination was what wound up working at some point and is still good now:
```javascript
  polygonSeries.visible = false; // added after beta.38
  polygonSeries.opacity = 0; // added after beta.38
  
  // Recommendation
  polygonSeries.defaultState.properties.opacity = 1;
  polygonSeries.hiddenState.properties.opacity = 0;

  // Expected behavior: start off as hidden
  // Actual behavior: start off as hidden
  // See: Antarctica
```


`polygonSeries.isHidden` is always `false` in  the above cases. (I am not sure if that's expected.)


Once a series is rendered, e.g. after `validated` or all the work is done:

```javascript
  polygonSeries.show() // does not animate, works instantaneously
  // See: Any MapPolygonSeries, except Argentina after first .show() and Antarctica
```
```javascript
  polygonSeries.hide() // does not animate, hides after a delay
  // See: Any MapPolygonSeries, except Argentina and Antarctica
```

When I last tested this I did so in conjunction with `polygonSeries.opacity = 0;` as soon as I push the series to the chart. That `opacity` now seems irrelevant:
```javascript
  polygonSeries.events.once("validated", function(ev) {
    polygonSeries.hide().events.on("animationended", () => {
      // polygonSeries.isHidden === true
      polygonSeries.show().events.on("animationended", () => {
        // polygonSeries.isHidden === false
      });
    });
  });
  // Expected behavior: Flash of render, animated fade out
  // Actual behavior: Flash of render in all browsers
  // See: Brazil
```

`polygonSeries.hiddenState.isDisposed()` is always `false`.
