### ISSUE TITLE
ValueAxis Typing Bug

### ISSUE THREAD

**Issue by Sam123-7** [amcharts/amcharts4#1680]
AmCharts version - 4.6.1

`Error:(636, 38) TS2345: Argument of type 'ValueAxis<AxisRenderer>' is not assignable to parameter of type 'Axis<AxisRendererCircular>'.`

Typing error when instantiating a new ValueAxis - example taken from the Gauge Chart Documentation. https://www.amcharts.com/docs/v4/chart-types/gauge-chart/

`let axis = chart.xAxes.push(new am4charts.ValueAxis());`

Type error goes away if you pass 

`let axis = chart.xAxes.push(new am4charts.ValueAxis<am4charts.AxisRendererCircular>());`

But i imagine this is not the intended implementation?

**Comment by martynasma** [comment]
> But i imagine this is not the intended implementation?

Technically, it is. For strong type support, an axis needs to know what type of renderer it is used with. For this purpose we use generics, and your last snippet is correct.

As for docs, well, we try to keep it simple(-ish). We do have users of varying levels of experience, and having generics there would confuse, break code for people using it in plain JS, hence our choice of not including in snippets.

Maybe we should rethink this strategy, tho.

Thanks for bringing it to our attention.

**Comment by ari62** [comment]
It doesn't contain generics in the Typscript tab of the doc source code, which causes an error in typscript
