### ISSUE TITLE
Line Chart with multiple lines: When switching from DateAxis to CategoryAxis all points get jammed at 0

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1687]
Hello, I started off from this example https://codepen.io/team/amcharts/pen/BPEpZy that comes from this page https://www.amcharts.com/docs/v4/concepts/series/

My code is something like this:
```

  let chart = am4core.create("chartdiv", am4charts.XYChart);
  var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
  dateAxis.renderer.minGridDistance = 50;
  dateAxis.renderer.grid.template.location = 0.5;
  dateAxis.startLocation = 0.5;
  dateAxis.endLocation = 0.5;

  var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

  var series2 = chart.series.push(new am4charts.LineSeries());
  series2.dataFields.valueY = "y";
  series2.dataFields.dateX = "x";
  series2.strokeWidth = 3;
  series2.tensionX = 0.8;
  series2.bullets.push(new am4charts.CircleBullet());
  series2.data = [{
      "x": 1,
      "y": 101
    }, {
      "x": 2,
      "y": 79
    }, {
      "x": 3,
      "y": 90
    }, {
      "x": 4,
      "y": 60
    }, {
      "x": 5,
      "y": 115
  }];

```
Until then it shows fine.
Since the data is x, y pairs of integers, I don't need the date, so I changed

`var dateAxis = chart.xAxes.push(new am4charts.DateAxis());`

for

`var dateAxis = chart.xAxes.push(new am4charts.CategoryAxis()); `

and

`series2.dataFields.dateX = "x";`

for

`series2.dataFields.categoryX = "x";`

and then all the points get jammed at the 0, like shown below

![jammed points](https://user-images.githubusercontent.com/46368248/65549697-6d617200-def4-11e9-8933-8b27a955bc4e.png)

What am I doing wrong? thank you

Edit: Here is the same problem in a codepen example https://codepen.io/nombreyapellido/pen/vYBPOEj

**Comment by martynasma** [comment]
`CategoryAxis` needs to know what categories are. It can't extract that data from individual series.

Since you are setting data directly to series, and not on chart (which category axis could use), you will also need to set data as well as dataFields on axis itself:

```
dateAxis.dataFields.category = "date";
dateAxis.data = [{
  "date": 1
}, {
  "date": 2
}, {
  "date": 3
}, {
  "date": 4
}];
```

**Comment by algebrathefish** [comment]
Thank you @martynasma.

I added the code to the codepen and the problems is fixed.

However some points seem to be off

![off bullets](https://user-images.githubusercontent.com/46368248/65713566-d3263900-e06f-11e9-99de-39b858241452.png)

**Comment by algebrathefish** [comment]
@martynasma can you point me in the direction of a line chart with the other json data format (like this one https://www.amcharts.com/demos/multiple-value-axes/) that can show me how to do gradients under the lines?

I have been able to do it with each like being a different series, but with the DateAxis instead of category axis, formatting the json as in the code pen

let gradient = new am4core.LinearGradient();
gradient.addColor(am4core.color(parsedData[index].colorInitGradient));
gradient.addColor(am4core.color(parsedData[index].colorEndGradient));
newSeries.fill = gradient;

(it's too complicated to find responses in the docs for a being a paid chart)

**Comment by martynasma** [comment]
Looks some kind of a bug with that out of place bullet.

Updated codepen for the dev team:
https://codepen.io/team/amcharts/pen/46b00ffe4dcdb29032585f721a4f102e?editors=0010

We'll need to fix it. I'll let you know when it happens.

P.S. please open a separate issue or email our support for separate unrelated questions.

**Comment by zeroin** [comment]
This issue is fixed in the latest release.

**Comment by algebrathefish** [comment]
Ok thank you for letting me know.
