### ISSUE TITLE
Load of LineSeries poor performance  

### ISSUE THREAD

**Issue by matinfo** [amcharts/amcharts4#1689]
I plan to use your chart library that is awesome! But based on different test with LineSeries charts, I see poor performance to load a chart.

To demonstrate that, find here a codepen where you be able to test with custom number of points: https://codepen.io/matinfo/pen/MWgGRxx

Example with 10'000 points chart show nice loader but take time for rendering. And imagine if in the page 5-10 charts like this that need displayed. User experience become unsupportable. And UI hang with Chrome during loading phase, result user have a bad experience.
And not test with 20'000-30'000 points some time browser crash.

I plan to use amcharts4 for a IoT project with lot of charts and plan to buy the license for this project. But the only blocking point is this poor loading capability. 

For example HightCharts offer a boost solution to display 500'000 points very fast :   https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-boost/

When do you plan to provide capability to load more the 10'000 by chart type LineSeries or other?

Related: #632, #395, #85, #1302

**Comment by martynasma** [comment]
I suppose path simplification might be a good way to speed up such chart:
https://www.amcharts.com/docs/v4/concepts/performance/#Simplifying_paths

**Comment by matinfo** [comment]
Thank you for your quick answer @martynasma 
In the codepen test https://codepen.io/matinfo/pen/MWgGRxx, I already use path simplification `am4core.options.minPolylineStep = 5;`, this help a bit, but not fixe completely loading time issue, and can't be able to increase it to more without losing to much chart line detail.

My project will display voltage/tension points, made every 10 min. Result if I want to display 5 LineSeries charts with 12 series each (for compare purpose) of a period of 7 days. Each chart will take min 9 sec to display x 5 charts, user will wait 45 secs!
 
Do you plan to provide other speed / load improvement ?

**Comment by martynasma** [comment]
> Do you plan to provide other speed / load improvement ?

As a matter of fact, we do.

Next version will contain dramatic improvements for large dataset charts.

Will ping you here as well when it's released in the coming days.

**Comment by martynasma** [comment]
Just released 4.6.4.

Can you try how the performance is now for your chart?

**Comment by matinfo** [comment]
Awesome, I see a huge speed improvement! Now I'm confident to use amcharts4 library for our project.  Thank a lot.
