### ISSUE TITLE
labels with square brackets in their databound text do strange things

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#169]
See pen: https://codepen.io/notacouch/pen/2eea3ad335eb794d57eec8ddf531504c

see any square brackets "[]" in "text" properties below:

```
labelSeries.data = [
...
    text: "Canada - useGeodata, series.hide()",
...,
...
    text: "USA - useGeodata, series.setState('hidden')",
...,
  // the label reads up to data=, the rest gets cut off
...
    text: "Mexico - series.setState('hidden'), data=[], Hello world",
...,
  // the below label texts include tests for the square bracket-related bugs
...
    text: "Brazil - opacity=0, visible=false, series.hide() on validated, data=a[b[]c, Hello Brazil, a[b[B]c",
...,
...
    text: "Argentina - series.[default|hidden]State.properties.opacity=1/0, series.setState('hidden'), data=a[]b]c, Hello Argentina, a[b]B]c",
...,
...
    text: "Antarctica - series.[default|hidden]State.properties.opacity=1/0, series.hide() on validated, data=a]b[]c, Hello Antarctica, a]b[B]c"
];
```

Results:

![image](https://user-images.githubusercontent.com/2334143/43120643-f50b0566-8ee8-11e8-838e-d612cd00c4b3.png)

- If it's just `[]`, then everything afterwards gets cut off (See Mexico's label)
- If there's an opening or closing bracket before an empty pair e.g. `[cut off[]` or `]cut off[]`, then everything in between gets cut off (See all labels below Mexico's)
- If there's an opening or closing bracket before or after and the pair also has something in between, then what's within the pair stays, but things outside it get cut off, e.g. `stays]cut[stays]off`. (See all labels below Mexico's)
- If the pair is not empty, what's inside gets cut out, but things after (See Argentina and Antarctica, `series.State` should read `series.[default|hidden]State`!)

Those are just some things I found, probably more quirky behaviors might be there, but I imagine those would probably also get settled once the underlying issue is fixed, too.

**Comment by martynasma** [comment]
Technically, square brackets are used for formatting of the text, so they need to be escaped.

```
label.text = "Something [[cool]] here";
```

Should result into `"Something [cool] here"`.

However, escaping (repeating twice) does not work properly right now so this will need to be fixed.

**Comment by notacouch** [comment]
Despite the [beta.36 fix](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta36---2018-07-25), I still think something is off. 

I've updated the pen so Argentina and Antarctica's texts are updated for some additional testing.

I would expect the single quote strings to actually disappear, wasn't sure if they would escape the brackets for me, fwiw they do neither.

```javascript
"Argentina - series.'[[default|hidden]]'State.properties.opacity=1/0, series.setState('hidden'), data=a[]b]c, Hello Argentina, a[b]B]c",
```

`'[[default|hidden]]'` renders as `'[default|hidden]'`, was hoping for `default|hidden`. The double brackets seems good, though! If this is intentional, perhaps [add to the docs](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Square_brackets) that square brackets can _only_ be escaped via repeating twice, the single quote won't escape it.

```javascript
"Antarctica - series.'[default|hidden]'State.properties.opacity=1/0, series.hide() on validated, data=a]b[]c, Hello Antarctica, a]b[B]c"
```

`a[]b]c` and `a]b[]c` both come out as `ac`, even if I escape or remove the earlier brackets in the string. The latter just doesn't make sense to me. Or in general, why would empty or non-matching formatting brackets cut out remainder text, e.g.:

```javascript
"Mexico - series.setState('hidden'), data=[], Hello world"
"Mexico - series.setState('hidden'), data=[, Hello world"
"Mexico - series.setState('hidden'), data=], Hello world"
```

All of them cut out `, Hello world`.

These examples are also curious:

```javascript
"Mexico - series.setState('hidden'), data=[], Hello []world"
"Mexico - series.setState('hidden'), data=[], Hello [world"
"Mexico - series.setState('hidden'), data=[], Hello ]world"
"Mexico - series.setState('hidden'), data=[, Hello [world"
"Mexico - series.setState('hidden'), data=], Hello [world"
"Mexico - series.setState('hidden'), data=], Hello ]world"
```

All of them cut out `, Hello `.

Or the following, I would expect putting an empty pair with a "closing tag" to "format" the string in between, but since the format is empty then just return the string as is (`, Hello `):
```javascript
"Mexico - series.setState('hidden'), data=[], Hello [/]world",
```

But it renders as:
```javascript
"Mexico - series.setState('hidden'), data=/",
```

**Comment by martynasma** [comment]
Yup, that needs to be fixed.

I'm not entirely sure if enclosing to quotes should "turn off" formatting within, tho. That would mean that users have to escape quotes. Quotes are used far far more often than square brackets in text, so I see it as an inconvenience that does not bring a lot of benefits.

We'll need to revamp the docs to make it superclear about how escaping and formatting works in labels.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.37](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.37).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
OK, so empty `[]` should not break stuff anymore.

Square and curly brackets are now displayed properly when escaped by duplicating them.

I'm not sure whether we should handle incorrectly formatted/unescaped brackets, though.

Refreshing text formatter documentation article as we speak, to make bracket escaping more prominent.

**Comment by martynasma** [comment]
FYI, Formatting Strings tutorial was revamped to make escaping (and meaning) of curly and square brackets clearer:

https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/

**Comment by notacouch** [comment]
> OK, so empty `[]` should not break stuff anymore.

Did some quick tests, looks good.

> I'm not sure whether we should handle incorrectly formatted/unescaped brackets, though.

That's totally fair. In that case should it be mentioned somehow? E.g. invalid formatting is not managed? I went through the documentation updates and it's great, the individual formatters even link back to the parent doc on escaping brackets. Maybe right after the double bracket example give a pitfall example of how invalid formatting is not supported/managed? 

Maybe something like, "Formatters aren't concerned with validating the actual brackets, whether individually, in pairs, or so on. Invalid, unescaped brackets will have unpredictable results, e.g. my IDE/editor does code completion, so as I type `[`, it closes it with `]`, but I forget that, continue typing, ending up with: `[]bold]NOT YELLING, JUST SAYING.`. That just prints `bold`, instead of the intended sentence. So be sure the use of brackets are valid.

**Comment by martynasma** [comment]
You got it!

https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Bracket_syntax_errors
