### ISSUE TITLE
Clustered Column Chart memory leak with large data

### ISSUE THREAD

**Issue by havietduc91** [amcharts/amcharts4#1690]
Hi Amchart team,

Firstly, thank a lot for the effort you're putting in the library, well-done team.

Secondly, now I'm facing the memory leak issue when I build the **2** XYChart in version 4 with 30 series and 180 columns, it took 3897MB and the browser crashed immediately after that, like the bellow image: 
![Screenshot from 2019-09-24 14-01-15](https://user-images.githubusercontent.com/4966192/65589166-d5768d80-dfb2-11e9-9e81-b041a6827348.png)

And I have created the demo on Codepen **1** XYChart with 30 accounts (30 series) and 365 days (365 columns) it took around 750MB. Please take a look this link https://codepen.io/havietduc91/pen/vYBbdjP
![Screenshot from 2019-09-25 16-26-25](https://user-images.githubusercontent.com/4966192/65589441-40c05f80-dfb3-11e9-9c5b-3c92127c294a.png)

And finanlly, let me know the solutions to resolve it (decrease memory) or inform me if I'm wrong.

Many thanks!

**Comment by martynasma** [comment]
Well, having a chart with a lot of columns (~10K in your case) is slow and memory consuming.

Would you rather consider using `StepLineSeries` instead?

https://codepen.io/team/amcharts/pen/0ca31658345e87e4de9647443047ae28?editors=0010

It's much much faster.

**Comment by havietduc91** [comment]
Hi @martynasma, 

Thank you for the quick response, it looks better for performance and memory issue but with a real app, we want to show the tooltip when the user hovers the columns, something like the below image:
![Screenshot (27)](https://user-images.githubusercontent.com/4966192/65740402-d6263580-e112-11e9-8716-e3177c2a2c0f.png)

Because I see that there is a difference between the chart has tooltip or not 
*In case 1, comment the code to show tooltip*
![Screenshot (29)](https://user-images.githubusercontent.com/4966192/65740703-d83cc400-e113-11e9-8068-d65e7a0416d0.png)

*In case 2, remove comment to show a tooltip, but the tooltip is not showing and the chart is broken*
![Screenshot (28)](https://user-images.githubusercontent.com/4966192/65740709-dd9a0e80-e113-11e9-984e-5a4b1e3cde12.png)

So is it possible to show a tooltip with StepLineSeries?

Many thanks.

**Comment by martynasma** [comment]
Sure. Just add `tooltipText` directly to series and also add `chart.cursor = new am4charts.XYCursor()`.

**Comment by havietduc91** [comment]
yeah, look good to me, it works like the below image:

![Screenshot (30)](https://user-images.githubusercontent.com/4966192/65742346-f0afdd00-e119-11e9-80ff-c1488957f984.png)

I will try to implement it for real app (to make rich tooltip text) and inform you later if have any update

Big thank for your help.

**Comment by havietduc91** [comment]
Hi @martynasma , 

The tooltip looks fine like the below image for the real app
![export](https://user-images.githubusercontent.com/4966192/66103381-c1004980-e5df-11e9-98c1-e47deea36cc0.png)

It looks good to me, but please let me know if you have any update for the status of this issue with the clustered column chart in the long term.

so for now, I will close this issue right away. 

Many thanks.
