### ISSUE TITLE
Line chart - updating data seems to break chart.

### ISSUE THREAD

**Issue by nmase88** [amcharts/amcharts4#1691]
Hi, 

When using a line chart, if i update chart.data even with the exact same data as currently being used by the chart, the chart seem to break. It's possible i'm not setting something I need to but then why does it work in the first instance? See code pen below, there is a refresh button below the chart which just resets the data to the same thing

https://codepen.io/nmase88/pen/aboMJMm

Thanks,
Nick

**Comment by martynasma** [comment]
`DateAxis` expects data items to be ordered in ascending order.

Yours seems to be the other way around.

This may (and does) create all kinds of anomalies, such as one you are seeing.

Passing in data arranged in ascending order would not break a chart.

**Comment by nmase88** [comment]
Thank you, I missed that. I thought it must have been something I was doing it just threw me off that it worked before the update.
