### ISSUE TITLE
calculateTotals summing method

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#1692]
Hi - I'm looking at the stacked column totals example here: https://www.amcharts.com/docs/v4/tutorials/totals-on-column-stacks/

I plugged in the same example here: http://jsfiddle.net/runfaj/k4en76fd/2/ but added a couple negative values.

In comparing amcharts3 totals to this method of totals, it looks like in amcharts3 would just do a straight sum, meaning the last column in the fiddle above would have a total of "0.1". In amcharts4, this total displays as "5.7".

I can see both contexts being correct depending on the situation of the chart. If you wanted to see the overall height of the stack, then the 5.7 would be correct. However, if you were doing something like cashflow where you have both positive and negative, I would expect the total to be the net value total, or "0.1".

Is there a configuration that allows choosing which totaling method is applied, or does this need to be added as a feature? I imagine this would be an incredibly easy flag to add where one keeps the Math.abs and one doesn't.

It looks like I could potentially add a text adapter on the labels and sum up the values how I want via dataItem._dataContext, but that seems incredibly hacky.

**Comment by martynasma** [comment]
I think having absolute values as total makes more sense then sum of source values.

For the latter, it would display a zero on a stack of two columns with values 10 and -10.

That said for only negative values, it would make sense to have a total with a minus sign as well.

I don't think we'll go the road of adding a setting for that, tho.

I suppose you could just have an adapter for the label and either do own calculations if current method does not suit the requirements, or simply add minus sign where applicable.

**Comment by runfaj** [comment]
@martynasma That's what I was thinking as well. It might be worth putting some of the gotchas and adapter options in the tutorial linked above for anybody in the future that might run across this.

**Comment by martynasma** [comment]
Noted. Thanks!

**Comment by wegnertm** [comment]
@runfaj - not sure if this is the correct spot for this but I've got a stacked barchart (using amcharts4) and I want a negative totals label to appear at the bottom of the stack instead of at the top. Is this possible and how should I do it? 

https://codepen.io/teweg/pen/jOxqmGj
