### ISSUE TITLE
How to set the color of the label of the ValueAxis on a react chart?

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1694]
I have gone all over the documentation and can't find the answer

I have looked here: https://docs.amcharts.com/javascriptcharts/ValueAxis and tried

```
var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.color = "#ff0000";
```

and it doesn't work

I also tried 

`am4core.color("#ff0000");`

just in case, which doesn't seem to do anything at all.

Thank you

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/concepts/axes/#Labels

The first code snippet shows how to change color of axis labels 😛 

P.S. that link you shared is for amCharts 3, old version of amCharts.

**Comment by martynasma** [comment]
> How to do that in v5?
> 
> Can'f find. Help pls!

Please post your question in [amCharts 5 repo](https://github.com/amcharts/amcharts5/issues/).
