### ISSUE TITLE
background-color problem

### ISSUE THREAD

**Issue by palvors** [amcharts/amcharts4#1695]
I tried to put a background color on labels , buts that doesn't work.

anyone know how make that ? 

 let xAxis = _chart.xAxes.push(
            new am4charts.ValueAxis<am4charts.AxisRendererCircular>()
        );
        xAxis.renderer.maxLabelPosition = 0.99;
        xAxis.renderer.fontWeight = 'bold';
xAxis.renderer.labels.template.background.fill = am4core.color('red');

but all labels are red  :(, I just want to put color backgournd on text-labels

**Comment by martynasma** [comment]
The code looks good. It should work.

https://codepen.io/team/amcharts/pen/b79f688d88dd2022cc93a053b311687d?editors=0010
