### ISSUE TITLE
HeatRules - applying min/maxValue

### ISSUE THREAD

**Issue by piernik** [amcharts/amcharts4#1699]
I want to use heat map. Above certain value (3000 in example) I want bubles to be red, below let's say blue.
I think I can use `heatRules` with `minValue` and `maxValue` but it does not seems to work.

Here is example: https://codepen.io/piernik/pen/WNeWYQQ?editors=0010

**Comment by martynasma** [comment]
Well, you have both min and max set to the same color:

```
  min: am4core.color('#ff0000'),
  max: am4core.color('#ff0000'),
```

**Comment by piernik** [comment]
I solved my issue differently - thanks for help!
