### ISSUE TITLE
Wrong demo (documentation) on Layered Column Chart

### ISSUE THREAD

**Issue by theCuriousOne** [amcharts/amcharts4#1700]
On the **["Layered Column Chart"](https://www.amcharts.com/demos/layered-column-chart/)** page the y axis and the tooltips are wrong. I believe the error lies in the **numberFormat "#.3'%'"** (where someone forgot to press **Shift** :) ) and should be:

**chart.numberFormatter.numberFormat = "#.#'%'";**

**Comment by martynasma** [comment]
Nice catch. Thanks! :)

Fixed.
