### ISSUE TITLE
HeatMap - min and max value

### ISSUE THREAD

**Issue by piernik** [amcharts/amcharts4#1701]
In this example: https://codepen.io/piernik/pen/yLBrJGv?editors=0010#0
I have data that min value is 50, so heat map's min value is 50 and that's why it's transparent. 
But I what to give amcharts min value (set to 0) so that opacity of "50" value would be .5 not 0.

I tired 
```
series.min = 0;
series.max = 100;
series.strictMinMax = true;
```

but no luck

**Comment by martynasma** [comment]
I'm afraid you're code is completely off. Series object does not have `min`, `max`, or `strictMinMax` properties.

**Comment by piernik** [comment]
It turned out that I needed to use `minValue`, `maxValue` in HeatRules.
