### ISSUE TITLE
Dynamic slice color in RadarColumnSeries

### ISSUE THREAD

**Issue by piernik** [amcharts/amcharts4#1702]
Here is example:
https://codepen.io/piernik/pen/pozBqwZ?editors=0010#0

I want that data would give me color of slice. So as in docs (https://www.amcharts.com/docs/v4/reference/radarcolumnseries/#propertyFields_property):

`series2.propertyFields.fill = 'kolor';`
Also tried: `series2.columns.template.propertyFields.fill = 'kolor';`

Still default color.

**Comment by martynasma** [comment]
Try this:

```
series2.columns.template.radarColumn.propertyFields.fill = 'kolor';  
```

**Comment by piernik** [comment]
I must say doc is not precise :/ Thanks.

**Comment by martynasma** [comment]
> I must say doc is not precise :/ Thanks.

We'd like to fix it. Which part threw you off?

**Comment by piernik** [comment]
Doc says that `propertyFields` is property of `RadarColumnSeries`.
In that example: https://codepen.io/piernik/pen/pozBqwZ?editors=0010#0
I have:
` const series2 = chart.series.push(new am4charts.RadarColumnSeries());`
I think that `series2` is `RadarColumnSeries` so I think that it has `propertyFields`, but I have to use `series2.columns.template.radarColumn.propertyFields` :/

**Comment by martynasma** [comment]
OK, I know how this might be confusing, but `propertyFields` is available on any element, not just series.

That's the beauty and flexibility of amCharts 4. You can bind any property of any element to a value in data.

I'm making a note of making it more prominent in classref. Thanks!
