### ISSUE TITLE
Is it possible to change the position of the scrollbarX? and can i set it's position to absolute?

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1704]
I was looking at this tutorial but couldn't find it https://www.amcharts.com/docs/v4/tutorials/customizing-chart-scrollbar/

thank you

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/tutorials/setting-position-of-the-chart-scrollbars/

**Comment by algebrathefish** [comment]
Hi again @martynasma and thank you

The link was useful, however I cannot set the y property of the scrollbarX inside the container.

It works fine with x property, but the y property is ignored completely

Here is a codesandbox example, that I forked

https://codesandbox.io/s/amchart-nwysc

As you can see on lines 94 and 95 of Sales.jsx, setting 

`chart.scrollbarX.x = -100; `

works, while 

`chart.scrollbarX.y = -100;`

is ignored.

Is this a bug or am I doing something wrong?

I also tried making the container higher, but the y property still gets ignored.

Thank you
