### ISSUE TITLE
Hover event listener?

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1705]
I was wondering if there is a hover event listener that returns the points of the lines I am hovering on.

I found this link on event listeners https://www.amcharts.com/docs/v4/concepts/event-listeners/
and there is no hover or MouseOver event on the list.

There is a list below with the headline "The table will show the event identificator (type), e.g. "hit" as well as the precise structure of the event object that will be passed into your custom function whenever event occurs." but in the list the "hit" event mentioned on the headline is missing, so I was wondering if the list is incomplete, or if there is no hover event at all.

In addition, my series is a line series.

In case such event exists, how would I make the call?

The example states

`series.columns.template.events.on(...)`

I don't know which arbitrary name you chose for the line series.

Should it be

`series.lines.template.events.on(...)`

?

Edit: I tired series.lines.template.events.on and series.line.template.events.on and none work, so why is it not specified on the docs for other than column series? Thank you

**Comment by algebrathefish** [comment]
I found it here https://www.amcharts.com/docs/v4/reference/categoryaxis/#Events

**Comment by martynasma** [comment]
That would be `series.segments.template`.

https://www.amcharts.com/docs/v4/reference/lineseries/#segments_property

**Comment by algebrathefish** [comment]
Thank you @martynasma 

And is there a way to get the category or the coordinates I am rolling over into? (i.e. the x and y axis coordinates?)

IS there any event that returns that ?

When I do 

```
newSeries.segments.template.events.on("over", function(ev) {
        console.log(ev);
      }, this);
```

nothing happens

for `popertychanged` instead of `over `it works

**Comment by zeroin** [comment]
Try also setting:
`newSeries.segments.template.interactionsEnabled = true` As they are disabled by default.

**Comment by algebrathefish** [comment]
@zeroin thank you, that seems to trigger the mouse over event.

It returns an object with many properties, could you please tell me where to find the x coordinate that I am rolling over to in that moment?

I tried ev.target.dataItem.dateX, I figured it could be, but it is undefined

Thank you

**Comment by zeroin** [comment]
I would say you are over-complicating things. You could simply add cursor to the chart and then use `tooltipshownat` event of a series to get data item, and if you need, a data context (raw data item). Here is a demo: https://codepen.io/team/amcharts/pen/14a94b0ad87b3fc83d7a49ebd3e4d886?&editable=true

(check console)

**Comment by algebrathefish** [comment]
thank you, @zeroin that is what i need

**Comment by algebrathefish** [comment]
unfortunately it doesn't work in my case, I am creating an individual series for each line. Maybe that is the cause, I will research and get back

**Comment by algebrathefish** [comment]
Got it working :), i had not added the XYCursor

Thank you very much for help

**Comment by algebrathefish** [comment]
@zeroin one more question please.

I see that event.dataItem.point.x returns the x mouse coordinate with respect to the chart.

I there a way to get the y coordinate of mouse over respect to the chart? event.dataItem.point.y doesn't seem to .

Thank you very much

**Comment by martynasma** [comment]
You may use [`am4core.utils.spritePointToSvg()`](https://www.amcharts.com/docs/v4/reference/utils_module/#spritePointToSvg_method) function to convert local point x/y to chart x/y.

```
var chartpoint = am4core.utils.spritePointToSvg(event.dataItem.point, chart)
```

**Comment by algebrathefish** [comment]
Thank you @martynasma 

I will try

**Comment by algebrathefish** [comment]
@martynasma this doesn't work. Since the y value is always the same for event.dataItem.point, the returned **y** value for var chartpoint = am4core.utils.spritePointToSvg(event.dataItem.point, chart) is always the same to
