### ISSUE TITLE
How to center axis label after wrap text?

### ISSUE THREAD

**Issue by irekrog** [amcharts/amcharts4#1707]
Hi,

how to center text after wrap? 

This text on the label is align to the left:
`valueAxis.title.text = 'Lorem ipsum tests123 label hello world';`

and after this
`valueAxis.title.maxWidth = 160;
valueAxis.title.wrap = true;`

in svg there are two lines: 
`<text>Lorem ipsum tests123</text>`
`<text>"label hello world</text>`

I would like to center second line relative to the first line (now whole text is to the left)

Here is example: http://jsfiddle.net/xb9gn1cf/9/

**Comment by zeroin** [comment]
`valueAxis.title.textAlign = "middle"; should do the job.
