### ISSUE TITLE
Series tooltip text

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1708]
The screenshot below shows a graph I am working on. As you can see the tooltip text for the red series is not showing. I know that this is because there is not a data value for the red series at that specific time. Is it possible so that the tooltip text for each series is shown regardless of where the cursor is along the Y-Axis?

![Capture](https://user-images.githubusercontent.com/48843852/65953804-9de96480-e43c-11e9-81ef-3f596ace9cb9.PNG)

Thanks

**Comment by zeroin** [comment]
It is possible, although a bit complicated. You have to:

1) set data for the series instead of the chart
2) set `series.snapTooltip = true`
3) set `xAxis.snapTooltip = false`

Here is a demo: https://codepen.io/team/amcharts/pen/b9f682419029ecd2fa274858ffde2363?&editable=true

**Comment by towsie84** [comment]
I I have made these changes but I still have an issue. The data I am using refreshes every 5 seconds and when an update occurs the trend disappears from the chart. The series still appears to the in place as the axis scale and legend details are still present.

Thanks

**Comment by zeroin** [comment]
I am afraid I need a codepen of the situation in order I could help.

**Comment by towsie84** [comment]
It is possible to use the snapTooltip when data is set to the chart rather than the series?

Thanks

**Comment by martynasma** [comment]
> It is possible to use the snapTooltip when data is set to the chart rather than the series?
Yes.

**Comment by towsie84** [comment]
Would this work when the x-axis is a CategoryAxis?

**Comment by martynasma** [comment]
I'm sorry, I jumped the gun there. No it won't work with data set directly to chart.

It will also not work on `CategoryAxis`.

**Comment by towsie84** [comment]
I have got it working using a dateAxis rather than a categoryAxis. Thanks for your help.
