### ISSUE TITLE
Can't resolve pdfmake.js

### ISSUE THREAD

**Issue by HDaghash** [amcharts/amcharts4#1709]
Hey ,
Using amChart with Angular falls into errors such can't resolve pdfmake.js

- Angular Version 7.
- Typescript > 3.

before that error the error was : can't find module *css-element-queries* 

and after installing the missing module it's showing *can't resolve pdfmake.js*

also please note : i'm not using type script strict mode any one can help in that.

Thanks.

**Comment by Pauan** [comment]
@HDaghash Are you using npm or yarn?

After adding `@amcharts/amcharts4` to your `package.json`, did you run `npm install` (or `yarn install`)?

**Comment by HDaghash** [comment]
> @HDaghash Are you using npm or yarn?
> 
> After adding `@amcharts/amcharts4` to your `package.json`, did you run `npm install` (or `yarn install`)?

npm and yes i did :)
