### ISSUE TITLE
Annotation feature

### ISSUE THREAD

**Issue by manoj016** [amcharts/amcharts4#171]
I could not find annotation menu item in the documentation. Is it there or removed?

**Comment by martynasma** [comment]
There's no annotation functionality in amCharts 4, yet.

It may come in a form of plugin at some later stage. Unfortunately, I can't provide any timeline for it. Sorry.

**Comment by manoj016** [comment]
No issues, Thank you anyway.

**Comment by martynasma** [comment]
Found this old thread. Annotation functionality has been available for a while now.

https://www.amcharts.com/docs/v4/tutorials/plugin-annotation/
