### ISSUE TITLE
Y-Axis labels

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1710]
I am using a value axis as my y-axis and was looking for a way to ensure that the maximum y-axis value is always shown as a label.

Thanks

**Comment by zeroin** [comment]
Could you give more details? Do you need some line at exact value of the maximum of your data? As by default, the adjusted maximum label is always shown. A codepen example or an image would help.

**Comment by towsie84** [comment]
I played about with the axis minGridDistance an was able to resolve my issue.

Thanks
