### ISSUE TITLE
Line on baseValue overlaps columns

### ISSUE THREAD

**Issue by geertplaisier** [amcharts/amcharts4#1711]
If a floating bar chart has bars ranging from negative to positive values, there is a line which overlaps the bar. After looking in the source I see that its the baseGrid on the AxisRenderer. Its hidden from the docs, on purpose I guess? Is the overlapping behavior a bug or intentional? Changing the strokeOpacity of the baseGrid hides the line, so that could be a fix, but since its not in the docs I don't know if there are any side effects. Tried setting a zIndex on the line but I cannot get it behind the bars.

See here for an example: https://codepen.io/geertp/pen/MWgMzVj

**Comment by zeroin** [comment]
You can indeed use `baseGrid`. It's our mistake it's not in the docs, should be there after next update - thanks!

**Comment by martynasma** [comment]
`baseGrid` is now in classref:
https://www.amcharts.com/docs/v4/reference/axisrenderer/#baseGrid_property

**Comment by geertplaisier** [comment]
Thanks for adding this to the docs, now we know its safe to use. Part of my question still stands though. Is it possible to put this baseGrid line behind the bars/columns? Tried setting zIndex on baseGrid (1) and on the ColumnSeries (2), but this does not work. Should this be working or it this intended behavior?

**Comment by martynasma** [comment]
Try this:

```
chart.bottomAxesContainer.zIndex = -1;
```
