### ISSUE TITLE
Retrieving array of selected data by scrollbar

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#1712]
Is there a way to get the part of the data property that is selected with a scrollbar?

For example, if I have an line chart with a scrollbar associated to the axis of time, when the time range selected changes, is there a sidebar or chart property that holds the part of the dataset that is visible to the user?

Thank you very much!

**Comment by zeroin** [comment]
There is no such property but you can easily do that yourself:

`dateAxis.events.on("startendchanged", function(){
	let start = Math.floor(dateAxis.start * chart.data.length);
	let end = Math.ceil(dateAxis.end * chart.data.length);
	
	console.log(chart.data.slice(start, end));
})`

**Comment by Segolene-Albouy** [comment]
Thanks a lot, that's what I did!
