### ISSUE TITLE
usaTerritories2High not compatible with AlbersUsa projection

### ISSUE THREAD

**Issue by yimej** [amcharts/amcharts4#1714]
Can the usaTerritories2High map layer be made compatible with the Albers projection? It seems to be glitching currently--the map is cut off right below Texas (approximately where the Albers projection would cut off the usaHigh map layer).

Can coordinates also be scaled to the Albers projection for all U.S. territories and associated states in usaTerritories2High?

**Comment by zeroin** [comment]
I am afraid no. AlbersUSA projection only takes care about Hawaii and Alaska.
