### ISSUE TITLE
Could not find root error

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1716]
I receive the error below when exiting a display that contains an amCharts serial line chart.

![Capture](https://user-images.githubusercontent.com/48843852/66034625-7f00d600-e501-11e9-9ab5-69fbdcbf6996.PNG)

Thanks

**Comment by zeroin** [comment]
Is there a possibility to see this chart? It is quite complicated to debug having only a picture.

**Comment by towsie84** [comment]
Attached is the code for the chart.

Thanks

[amCharts Stacked Trend.txt](https://github.com/amcharts/amcharts4/files/3681688/amCharts.Stacked.Trend.txt)

**Comment by Pauan** [comment]
@towsie84 It sounds like you're removing the DOM element.

If you're going to do that, you have to call `chart.dispose()` before you remove the DOM node, so that way amCharts can clean up all of its internal state.

**Comment by towsie84** [comment]
@Pauan that's for your help. I have added chart.dispose() to my code and it works a treat.

Thanks
