### ISSUE TITLE
How to disable dragging (panning)

### ISSUE THREAD

**Issue by lgerndt** [amcharts/amcharts4#1719]
Hi, I can't seem to find the API that would prevent the ability to drag an XY chart horizontally.  I think you call this panning.  Some of our charts don't have this problem, but others do, and I can't seem to find any api to disable it.  I saw the tutorial about disabling it for a Map chart, which is a special case, but nothing for other chart types.

**Comment by martynasma** [comment]
Panning is not enabled by default on any XY chart. If it does work like that it means you have explicitly enabled it by setting cursor's `behavior` property.

Look for it in you code ;)

**Comment by zeroin** [comment]
Usually panning is set like this: `chart.cursor.behavior = "panX"`. If you remove this line, it should start zooming instead of panning, as default behavior is `zoomX`.

**Comment by lgerndt** [comment]
Thank you, thank you!  that was the solution!
