### ISSUE TITLE
Disable legend toggling

### ISSUE THREAD

**Issue by dyzajash** [amcharts/amcharts4#172]
Hello,
I have simple PieChart with Legend created with JSON Configuration. How can I disable legend series toggling? 

My current config:

```
"legend": { "clickable": false }
```

or

```
"legend": {"togglable": false }
```

is not working.

**Comment by martynasma** [comment]
Try this instead:

```
chart.legend.itemContainers.template.clickable = false
chart.legend.itemContainers.template.focusable = false
```

Or in JSON:

```
"legend": {
  "itemContainers": {
    "clickable": false,
    "focusable": false
  }
}
```
https://codepen.io/team/amcharts/pen/oMeaGN?editors=0010

**Comment by martynasma** [comment]
I closing this, but please feel free to post any follow up questions you may have.
