### ISSUE TITLE
Last number formatter is used for all chart values when we applied individual number formatter in Y Axes

### ISSUE THREAD

**Issue by erhspatel** [amcharts/amcharts4#1720]
Individual Number Formatter is not working after release 4.5.12 for JSON Base Config. It's working fine for 4.5.11.
[#221](https://github.com/amcharts/amcharts4/issues/221)

**Comment by martynasma** [comment]
We've changed how JSON handles creation of new objects. Now if `type` is set and it matches an already existing object type, it won't create a new object but rather use a new one.

You can fix it with a `forceCreate` setting:

```
numberFormatter: {
  type: "NumberFormatter",
  forceCreate: true,
  // ...
}
```

More info here:
https://www.amcharts.com/docs/v4/concepts/json-config/#Creating_or_reusing_

**Comment by erhspatel** [comment]
Thank you Martynas Majeris :)
