### ISSUE TITLE
 synchronize zero value in graph with multiple axes in AMCHART4

### ISSUE THREAD

**Issue by Eguerrero86** [amcharts/amcharts4#1723]
Hi,
I'm trying synchronize the value zero in a column graph whit multiple yaxis, I tried with minimum and maximum values ​​in the yaxis but it didn't work.

![image](https://user-images.githubusercontent.com/32604694/66165603-b7d0a600-e5fa-11e9-8ddd-8df3a7b72b4d.png)

Thanks :-)

**Comment by xorspark** [comment]
Are you setting the right properties in your axis? You need to modify `min` and `max` in the axis objects. I'm able to sync the zero line across multiple series just fine after determining the min/max values across all of the series values.

[Here's an example](https://codepen.io/team/amcharts/pen/ae292d4820b1efa900e8a424be909dfd?editors=0010)
