### ISSUE TITLE
Chord Diagram

### ISSUE THREAD

**Issue by genryd** [amcharts/amcharts4#1724]
Example: https://codepen.io/team/amcharts/pen/MBGJZO

Could you explain what these lines are responsible for:

```
var colors = {
    Rachel:chart.colors.next(),
    Monica:chart.colors.next(),
    Phoebe:chart.colors.next(),
}
```

```
chart.data = [
// node property fields take data from data items where they are first mentioned, that's 
// why we add empty data items at the beginning and set colors here
{"from":"Monica", "color":colors.Monica},
{"from":"Rachel", "color":colors.Rachel},
```
Initially, I thought that in the first part of the code we specify the next color of the palette. In the second part we indicate the color source. 
But in practice, the code is completely counterintuitive. I did not find examples and descriptions in the documentation.

**Comment by zeroin** [comment]
`colors` property of a chart holds a ColorSet: https://www.amcharts.com/docs/v4/reference/colorset/
So we just create a simple object with names and assign a color to each of them from ColorSet.
Later we use it in the data. You can actually have the `{"from":"Monica", "color":chart.colors.next()}`, and not create that object.

**Comment by genryd** [comment]
It's not working that way with second part of code.

**Comment by martynasma** [comment]
You will need to provide more details about your setup and what does not work if you expect any insights ;)
