### ISSUE TITLE
Bulletts on line chart are displaced

### ISSUE THREAD

**Issue by prodenx** [amcharts/amcharts4#1725]
Hi,

I have issue with bullet on line chart on Chrome 77.0. The bullets are displaced to the right side.
![image](https://user-images.githubusercontent.com/10025771/66197461-a784fd80-e6c4-11e9-8d87-b6995b58b70f.png)

I used baseInterval
        dateAxis.baseInterval = {
            "timeUnit": "day",
            "count": 1
        }

That does not help.

I am using amcharts 4.6.0 with Angular 8.0.

**Comment by zeroin** [comment]
Try to upgrade to the latest version, there were indeed problems with bullets in v 4.6.0 but they should be fixed in 4.6.5

**Comment by prodenx** [comment]
Thanks, works for me
