### ISSUE TITLE
series.connect issue

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1726]
I have a chart with a dateAxis for the x-axis and a valueAxis for the y-axis. The data is set against the series and when I set series.connect = false I get strange results.

The codepen below shows an example of my issue.

[https://codepen.io/towsie84/pen/wvvwQmY](url)

**Comment by zeroin** [comment]
In case you only want gaps where the value is "null", you should set `series.autoGapCount = Infinity`
Otherwise the gaps are placed at each missing date.

**Comment by towsie84** [comment]
Would autoGapCount work with either a categoryAxis, when the data is set against the chart or both together?

**Comment by zeroin** [comment]
`autoGapCount` works with DateAxis only.

**Comment by towsie84** [comment]
Thanks, will it work when the data is set against the chart?

**Comment by martynasma** [comment]
`autoGapCount` should work either way.

**Comment by towsie84** [comment]
When I set the data against the chart I get the same issue

**Comment by martynasma** [comment]
Did you add the `autoGapCount` like @zeroin suggested?

I get continuous line if I add that to your codepen.

**Comment by towsie84** [comment]
I had done that but the way I am handling the data was causing the issue. Now that I have changed that the series are displaying correctly. This has however stopped one of my other features from working.

I had the data setup so that when the user hovers over the chart the series tool tip was displayed for all series. This no longer works.

**Comment by martynasma** [comment]
Wanna post the chart like you have it now again?

**Comment by towsie84** [comment]
I have updated my codepen and when you hover over the bullets where both series have a point on the same date it only shows the tooltip for one of them.

[https://codepen.io/towsie84/pen/wvvwQmY](url)

**Comment by martynasma** [comment]
Well, it's not a bullet, tooltip, or cursor issue. Date-based data needs to be ordered in ascending order.

Yours is not, hence the issue.

Also, you may need to consolidate values from the same date into one object:

```
chart.data = [{
  "date": new Date(2018, 3, 20),
  "value0": 90
}, {
  "date": new Date(2018, 3, 22),
  "value1": 101
}, {
  "date": new Date(2018, 3, 23),
  "value0": 125,
  "value1": 79
}, {
  "date": new Date(2018, 3, 24),
  "value1": null
}, {
  "date": new Date(2018, 3, 25),
  "value1": 60
}, {
  "date": new Date(2018, 3, 26),
  "value0": 77,
  "value1": 115
}, {
  "date": new Date(2018, 3, 28),
  "value0": 113
}];
```

**Comment by towsie84** [comment]
I was consolidating the data and sorting it in ascending order previously but that is what was causing my issue to start with.

The link below has been updated to have the data consolidated and in order.

[https://codepen.io/towsie84/pen/wvvwQmY](url)

**Comment by martynasma** [comment]
Ah, gotcha.

In that case the only way is to have separate data for each series:
https://codepen.io/team/amcharts/pen/cdb345c358cac1ad7462573665acf666?editors=0010

**Comment by towsie84** [comment]
If I set the data against the series how do I updated the series data once it has been created?

The actual data I am using is live data that updates regularly.

**Comment by martynasma** [comment]
The same way you would update chart's data: either by replacing `data` altogether or using `addData()`.

**Comment by towsie84** [comment]
Thanks for your help, I now have it working.
