### ISSUE TITLE
how to change the exported file name need to change customize name not default one 

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#1727]

**Comment by xorspark** [comment]
Set [`filePrefix`](https://www.amcharts.com/docs/v4/reference/export/#filePrefix_property) to the desired name. The export function will append the correct extension to it.

```
chart.exporting.filePrefix = "myExport"; //file names will be myExport.png, myExport.pdf, etc
```

[Further documentation](https://www.amcharts.com/docs/v4/concepts/exporting/#Export_options)
