### ISSUE TITLE
In Firefox, when revealing overlaying MapPolygons during zoom, may see dual tooltips

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#173]
[pen](https://codepen.io/notacouch/pen/7b7bbee45ad000190f3bac54eb14dbc0?editors=0010), [live version](https://codepen.io/notacouch/live/7b7bbee45ad000190f3bac54eb14dbc0)

Steps to reproduce:

1. Hovering over France should reveal its tooltip in red.
2. Clicking it should zoom in, 
3. while zooming, its regions (in a separate MapPolygonSeries) start showing (whether animated or not)
4. as they come into view, so does a tooltip, sometimes both show simultaneously:

![image](https://user-images.githubusercontent.com/2334143/43293560-efa76476-9108-11e8-9c42-1bcb5725229a.png)

Sometimes (the first time) it shows up all the way in the top left corner:
![image](https://user-images.githubusercontent.com/2334143/43293452-54f84cc4-9108-11e8-8041-ce7fe2a06b52.png)

The line is just some random line to demo some other quirk I've found, will post that separately.

**Comment by martynasma** [comment]
Looks like linked codepen was used for another issue and no longer displays above screenshots. Would you be able to bring it back?

**Comment by notacouch** [comment]
Ah, I didn't post a screen of how it starts.

It starts off zoomed out (and again the bug only seems to happen in Firefox):

![image](https://user-images.githubusercontent.com/2334143/43412068-0e072f5c-93fa-11e8-8ca7-ea1779b87789.png)

Then hover:

![image](https://user-images.githubusercontent.com/2334143/43412103-2db8a0e2-93fa-11e8-8222-369c5c50ed7e.png)

Then click:

![image](https://user-images.githubusercontent.com/2334143/43412156-4f80b372-93fa-11e8-9868-a8de93e6adae.png)

Above screens were taken whilst in private browsing.

**Comment by zeroin** [comment]
Could you check if you can still reproduce this issue?

**Comment by notacouch** [comment]
Yes.

Firefox version 62.0.3 (64-bit) on Windows 7.

Steps:
1. Opened live link in Private window, it starts off by zooming in
2. Used zoom control to zoom all the way out
3. Clicked on France (red polygon)
4. Leave mouse [incredibly still](https://www.quirkybyte.com/wp-content/uploads/2018/08/Drax-Quotes-1.jpg)

Screenshot:
![image](https://user-images.githubusercontent.com/2334143/47318025-ef785500-d618-11e8-8b34-eb17b540b229.png)

**Comment by notacouch** [comment]
Not sure when this changed, but dual tooltips no longer show. Also not sure what the expected behavior should be, but the original tooltip of the object that is no longer hovered over (France) is what remains:

![image](https://user-images.githubusercontent.com/2334143/54409457-35fc4800-46bd-11e9-9551-38cbdc5fdc56.png)
