### ISSUE TITLE
Setting 0 to dateAxis.startLocation and dateAxis.endLocation the line is off place

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1730]
I need the line to start and end at the chart limits

Originally it said dateAxis.startLocation = 0.5;
dateAxis.endLocation = 0.5;

Changing it to 
dateAxis.startLocation = 0;
dateAxis.endLocation = 0;

makes the line display off place. Please help

Example: https://codepen.io/nombreyapellido/pen/dyyyQNX

**Comment by martynasma** [comment]
Well, if you set `endLocation` to zero, you effectively telling `DateAxis` to cut off at the beginning of the last date, which it does.

So if you want the line to start and end at the edges of plot area, you need to set both options to `0.5`.

**Comment by algebrathefish** [comment]
@martynasma could you explain the logic to me?

What do you mean cut off?

Why does the zoom out button go to a start point of 0.5?

I have an extra layer I have to add, that needs to match the zoom position, and I am having a really hard time

What does 0.5 mean?

is it a percentage, is it pixels?

Why does dateAxis.startLocation = 0; and dateAxis.endLocation = 0; have a different starting point when adding more or less points to the series?

Here is a 4 point example for comparison https://codepen.io/nombreyapellido/pen/BaaNLar
and the previous 2 point example https://codepen.io/nombreyapellido/pen/dyyyQNX

in one it starts at the middle and on the other more to the left.

I really don't understand,

**Comment by martynasma** [comment]
The following tutorial should get you sorted out:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

**Comment by algebrathefish** [comment]
ok, thank you
