### ISSUE TITLE
Forced directed Tree fixed children

### ISSUE THREAD

**Issue by simonstumpf** [amcharts/amcharts4#1731]
Hi,

Is there a option to set fixed positions for the children of a node?
I know that i can set fixed positions for the nodes with the following code:
[Doc](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Fixed_nodes)

**Comment by martynasma** [comment]
Technically, it should work on all nodes. It does not, though.

We'll need to look into it. Thanks for the heads up!

**Comment by etaphie** [comment]
Hello!
Is there any news about this bug? 
Thanks in advance.

**Comment by zeroin** [comment]
Sorry for delay, it will be fixed in next release.

**Comment by zeroin** [comment]
It should work fine since v 4.8.5
