### ISSUE TITLE
Modify chart axisLength

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1735]
Is it possible to modify the xAxis axisLength to change the size of a chart?

**Comment by towsie84** [comment]
Is it possible to drag the axis to the length you want it to be?

Thanks

**Comment by martynasma** [comment]
Why would you want to make the axis be of different width than the plot area? Or maybe I'm misunderstanding your question.

**Comment by towsie84** [comment]
I would want the plot area to change along with the axis. The idea is that the user will be able to resize the chart to their preferred size or to fit on their screen.

**Comment by martynasma** [comment]
The chart will automatically adapt to the size of its container. It sounds like you need some kind of div resizer in place. A bit out of scope of the charts.

**Comment by towsie84** [comment]
Thanks, I will look into that.
