### ISSUE TITLE
Force Directed Tree custom nodes

### ISSUE THREAD

**Issue by altieres** [amcharts/amcharts4#1737]
Is it possible to set a Pie Chart as the node of a Force Directed Tree?

If not, I am trying to use an image, but it doesn't auto scale. I tried to set 100% (am4core.percent(100)) on sample (https://codepen.io/team/amcharts/pen/YMGNrR) but the image disappears. Using paths the size doesn't change.

Thanks, Altieres.

**Comment by martynasma** [comment]
Something like this?
https://codepen.io/team/amcharts/pen/eb0e234d9af0d74f1d64b41f47388c2b?editors=0010

**Comment by altieres** [comment]
Awesome!
I got how to put the Pie, but the negative offset saved me.
Thanks!
