### ISSUE TITLE
Error in core.js: Cannot read property '1' of null

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1738]
I'm getting this error when core.js is loaded:    

```
core.js:formatted:20368 Uncaught TypeError: Cannot read property '1' of null
    at core.js:formatted:20368
    at Object.Nv8/ (core.js:formatted:20369)
    at r (core.js:formatted:30)
    at Object.0 (core.js:formatted:682)
    at r (core.js:formatted:30)
    at core.js:formatted:105
    at core.js:formatted:106
```
I think the reason is because I'm loading it inside a Chrome Extension (a content script defined in manifest.json)    

Any idea how to solve it?
    
The problem seems to be here:   

```
        i.p = function(t) {
            return /(.*\/)[^\/]*$/.exec(t)[1]
        }(function() {
            if (document.currentScript)
                return document.currentScript;
            var t = document.getElementsByTagName("script");
            return t[t.length - 1]
        }().src)
```   

In Chrome Extensions content scripts the document.currentScripts is not defined and document.getElementsByTagName is returning the <script> tags from the original page.    
The URL used to load core.js is something like this:    
chrome-extension://kbilmlsdasdddkiknipbpmljgmnjdefpnd/content/js/amcharts/core.js

**Comment by Pauan** [comment]
@enriquepiatti Chrome Extensions don't give access to the URL, so our `<script>` version is broken, and unfortunately there isn't anything we can do about that.

Instead, you should use [Webpack](https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/) to bundle the ES6 version of amCharts with your code. That way it only needs to load 1 file, and it doesn't care about the current URL, so it will work with Chrome Extensions.

**Comment by kostazol** [comment]
Hello. I don't  understand why i have this error in 4.9.19 when i use
<script src="~/Scripts/chart/core.js"></script>
<script src="~/Scripts/chart/charts.js"></script>
<script src="~/Scripts/chart/animated.js"></script>

Can you help me? What i need to to? I tried pack 3 scripts at one and it doesn't help.
