### ISSUE TITLE
Update cursor tooltip when mouse over chart with live data updates

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1741]
I leave this codepen to show the actual behavior of the dateAxis cursor tooltip https://codepen.io/nombreyapellido/pen/MWWwGEg

When the mouse over the chart is still, with no movement, the data updates in the chart behind it, but the cursorTooltip label does not update

I know this is a cursor function, but it is useless to keep the old data in the label, instead of updating it together with the series.

Is there a work around ? Can this behaviour be changed? thank you

For context, I am using series.events.on("tooltipshownat", function (event) { this.something = event.dataItem.dataContext.x }) to get that value. Maybe there is another event that I could use?

**Comment by algebrathefish** [comment]
Hi, any answer on this?

**Comment by zeroin** [comment]
Sorry for delay. To solve this, you should hide and show the tooltip when data changes:

```
dateAxis.hideTooltip(0);
dateAxis.showTooltipAtPosition(chart.cursor.xPosition);
```

If you don't want' the fade-in animation, set:

`dateAxis.tooltip.defaultState.transitionDuration = 0;`

**Comment by algebrathefish** [comment]
Thank you @zeroin
