### ISSUE TITLE
display consistent-width columns across several charts

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#1742]
need place consistent width for coulmn chart but dependes on data is vary.is there any Property to set the width.
i tryed this one 
series1.columns.template.width = am4core.percent(50);

example:
https://www.amcharts.com/demos/simple-column-chart/

here if i remove last 3-4 column then width will increse

**Comment by martynasma** [comment]
Try `maxWidth` instead.

**Comment by Mahisandy** [comment]
i tried that but not working 

below code i tried for that
var columnTemplate = series.columns.template;
columnTemplate.strokeWidth = 2;
columnTemplate.strokeOpacity = 1;
**columnTemplate.width= am4core.percent(50);
columnTemplate.maxWidth= am4core.percent(20);**

> **can u drop demo example for that**

**Comment by martynasma** [comment]
`maxWidth` can only be set in pixels, not percents.

**Comment by martynasma** [comment]
`"20px"` is not a number, try:

```
columnTemplate.maxWidth = 20;
```
