### ISSUE TITLE
Hiding a series if valueY = 0 in amcharts4

### ISSUE THREAD

**Issue by shripradashivakumar** [amcharts/amcharts4#1743]
I am working on a clustered bar graph in amcharts4 
<img width="1555" alt="Screenshot 2019-10-10 at 11 53 11 AM" src="https://user-images.githubusercontent.com/50405790/66543998-8dc83800-eb54-11e9-88fc-de07e2464fb4.png">

I do not need those empty spaces to show up - the data for those columns are zero. Hence i want to hide them. 

How can i achieve that?

I am using columnSeries.

**Comment by martynasma** [comment]
I'm afraid it's not possible to "collapse" individual columns withing categories.

Or do you mean to hide the whole series if its **all** values are zero?

**Comment by shripradashivakumar** [comment]
I want to collapse an individual column only.

As seen in the screenshot I have attached, say for VP, 'Below Expectations' = 0 in my data. So i do not want to display that one particular columnSeries. I just need the 2 bars that has data to show up in the chart.

Code:
`function createSeries (field, name) {
      var series = chart.series.push(new am4charts.ColumnSeries())
      series.dataFields.valueY = field
      series.dataFields.categoryX = 'calibrated_level'
      series.dataFields.valueYShow = 'totalPercent'
      series.name = name
      // series.columns.template.width = am4core.percent(95)
      series.columns.template.tooltipText = "{valueY.totalPercent.formatNumber('#.0')}%"
      series.tooltip.pointerOrientation = 'vertical'
}

    createSeries('Below Expectations', 'Below Expectations')
    createSeries('Development Needed', 'Development Needed')
    createSeries('Solid Performer', 'Solid Performer')
    createSeries('Exceeds Expectations', 'Exceeds Expectations')
    createSeries('Role Model', 'Role Model')
`

**Comment by martynasma** [comment]
I'm afraid that's not possible. Sorry :(

**Comment by shripradashivakumar** [comment]
oh damn. thanks for the response.

**Comment by shripradashivakumar** [comment]
I have another question. 
Only alternate values are being displayed on the x-axis. (screenshot attached)
<img width="1556" alt="Screenshot 2019-10-11 at 10 29 48 AM" src="https://user-images.githubusercontent.com/50405790/66625535-31c3e900-ec12-11e9-8d39-cb4491640059.png">

This happens when the list of countries i am trying to display is big. Say with 4 values, i can see all countries. 

Please let me know how i can solve this issue.

**Comment by martynasma** [comment]
Please post a separate issue for different topic. It's not a chat :)

**Comment by shripradashivakumar** [comment]
so sorry about that. posted a new one :)
