### ISSUE TITLE
Get series trend value between two data points

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1744]
The screen shot below shows a chart I have and the two blue crosses are data. Is it possible for me to get the value of the series at any point between the data? 

For example, if I set up an event to record the data value on double click and I click anywhere on the black line, I would want to be able to record the value of the trend at that point on the x-axis.

![Capture](https://user-images.githubusercontent.com/48843852/66558815-24dcc200-eb4c-11e9-8d16-c88217e8a25f.PNG)

**Comment by martynasma** [comment]
I'm afraid we don't have such built-in functions. Sorry.

**Comment by towsie84** [comment]
Thanks for your response.

Is it possible to get the value from the series tooltips?

I have the chart setup to show a tooltip for each series, as shown below. Could I setup a double click event to capture the values from the displayed tooltip for each series?

![Capture](https://user-images.githubusercontent.com/48843852/66561062-a1719f80-eb50-11e9-91e7-e4dce162bd6d.PNG)

Thanks

**Comment by martynasma** [comment]
Yes, you can access series' [`tooltipDataItem`](https://www.amcharts.com/docs/v4/reference/lineseries/#tooltipDataItem_property) property to get data item currently feeding its toolitp.

**Comment by towsie84** [comment]
@martynasma that does the job perfectly, thanks for your help.
