### ISSUE TITLE
Using an SVG heatmap instead of re-rending GeoJSON everytime

### ISSUE THREAD

**Issue by andreibondarev** [amcharts/amcharts4#1745]
I have the following heatmap:
![image](https://user-images.githubusercontent.com/541665/66578819-cadafd00-eb49-11e9-9a4b-763824de7315.png)

Followed the code example here: https://www.amcharts.com/demos/us-heat-map/

Is it possible to use the pre-built SVG version of the map from here (https://www.amcharts.com/svg-maps/?map=usa), set the heatmap geodata, wire up the tooltip, and any other JS afterwards instead of re-rending the GeoJSON everytime?

The issue is that I also have a US Counties heatmap and it takes roughly 10 seconds to fully render.

**Comment by martynasma** [comment]
You could export the chart to SVG via Export:
https://www.amcharts.com/docs/v4/concepts/exporting/

Wiring a tooltip to a static SVG is trickier, though. You'll need some other tool/library for that, I'm afraid.

**Comment by andreibondarev** [comment]
@martynasma Thank you for your prompt reply! Any way to prerend the amcharts output? Server-side rendering perhaps?

**Comment by martynasma** [comment]
If you want to automate that, maybe use something like Selenium:
https://www.amcharts.com/docs/v4/tutorials/automating-report-generation-using-selenium-webdriver/

**Comment by andreibondarev** [comment]
@martynasma Got it. Is there a US County map available for AmCharts v3.x? I couldn't find it anywhere, is it in the paid tier?

**Comment by martynasma** [comment]
Yes, County maps are available for commercial license holders of V3. But please, this is repo for V4, so let's keep us in the scope :)
