### ISSUE TITLE
Only alternate values are displayed on the x-axis (amcharts4)

### ISSUE THREAD

**Issue by shripradashivakumar** [amcharts/amcharts4#1746]
Only alternate values are being displayed on the x-axis. (screenshot attached)
<img width="1556" alt="Screenshot 2019-10-11 at 10 29 48 AM" src="https://user-images.githubusercontent.com/50405790/66626937-a9e0dd80-ec17-11e9-8ffa-a9a3d9ac1121.png">

This happens when the list of countries i am trying to display is big. Say with 4 values, i can see all countries.

Please let me know how i can solve this issue.

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by shripradashivakumar** [comment]
thanks. problem solved :)
