### ISSUE TITLE
Set zIndex for bullet doesn't work

### ISSUE THREAD

**Issue by irekrog** [amcharts/amcharts4#1747]
Hi, I have a problem

I would like to set "visits" series on the top and `series.zIndex = 1;` works well but `bullet.circle.zIndex = 1;` doesn't work and there are still bullets from last series

Here is an example: http://jsfiddle.net/uftkne8p/1/

**Comment by martynasma** [comment]
That's because bullets go into separate container that is placed above series container.

The solution would be to move bullets into `seriesContainer`.

Here's a demo:
https://codepen.io/team/amcharts/pen/ea95a7ce0e2faaf29fba4ba12410a1ae?editors=0010

**Comment by irekrog** [comment]
@martynasma 

I've tried add `series.bulletsContainer.parent =  chart.seriesContainer;` and now a line overlaps bullets, but still there is bullet from other series
http://jsfiddle.net/6bfh1kxa/

**Comment by martynasma** [comment]
Yes, you need to put all bullets from all series into `seriesContainer`, then you can arrange everything via their respective `zIndex` properties.

**Comment by irekrog** [comment]
@martynasma 
Thanks for your help :) it works

**Comment by martynasma** [comment]
Just posted this:
https://www.amcharts.com/docs/v4/tutorials/ordering-zindex-of-series-lines-and-bullets/
