### ISSUE TITLE
Pie Chart- Hide value on legend

### ISSUE THREAD

**Issue by alsohi24** [amcharts/amcharts4#1748]
Hi, I want to remove the values ​​of the legend. Is this the best way to do it?.
Works, but only in the development environment
`pieSeries.legendSettings.valueText = "{ }";
`
Description:
https://stackoverflow.com/questions/58348433/amcharts-v4-pie-chart-hide-value-on-legend
Production env:
![on_production](https://user-images.githubusercontent.com/29634496/66685588-99922800-ec42-11e9-8b11-0c280de73000.gif)

Develoment env:
![on_develoment](https://user-images.githubusercontent.com/29634496/66685663-cb0af380-ec42-11e9-8a33-439ea0d63964.gif)

**Comment by martynasma** [comment]
This should probably do it as well:

```
legend.valueLabels.template.disabled = true;
```

**Comment by alsohi24** [comment]
> This should probably do it as well:
> 
> ```
> legend.valueLabels.template.disabled = true;
> ```

It's works, thanks.
