### ISSUE TITLE
where to plcae License for website where we have multiple page with amchart?

### ISSUE THREAD

**Issue by ssurwasegd** [amcharts/amcharts4#1749]
currenlty we are plcae in very chart end of line this statment is there any generic place so no need to write in multiple .

**Comment by martynasma** [comment]
You need to place license code before you instantiate the first chart. Once is enough.

**Comment by ssurwasegd** [comment]
can we write like this
$(function() {
    am4core.options.commercialLicense = true;
});

**Comment by martynasma** [comment]
Please contact us at contact@amcharts.com to discuss this further.
