### ISSUE TITLE
Series and ranges are displaced on date axis chart

### ISSUE THREAD

**Issue by prodenx** [amcharts/amcharts4#1752]
Hi,

I have issue with date chart. Data points on line and ranges on date axis does not fit values on the date axis.
![image](https://user-images.githubusercontent.com/10025771/66732871-ce42f100-ee87-11e9-9ed3-4a17379d8c15.png)

You can see that grid lines on x axis are not same places with data points on series and ranges.
Time part is set to zero for both (begin of day)

The initialization part:

       let chart = am4core.create(chartId, am4charts.XYChart);

        chart.colors.list = [
            am4core.color("#845EC2"),
            am4core.color("#00fb9c"),
            am4core.color("#FF6F91"),
            am4core.color("#FFC75F"),
            am4core.color("#F9F871")
        ];

        // Create axes
        let dateAxis = chart.xAxes.push(new am4charts.DateAxis());
        // dateAxis.baseInterval = {
        //     "timeUnit": "day",
        //     "count": 1
        // }
        let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

        chart.cursor = new am4charts.XYCursor();
        chart.cursor.xAxis = dateAxis;

        chart.legend = new am4charts.Legend();
        chart.legend.position = "top";

        this.chart = chart;

Tryed to base interval property - did not help

Same thing on another chart

Angular 8.0 and amcharts 4.6.5 are used

**Comment by martynasma** [comment]
It's hard to tell without seeing your code, but you might need to specify range locations:

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_locations

**Comment by prodenx** [comment]
@martynasma You can see that even on demo page of amcharts (tooltip on x axsis and grid line do not have the same place as label when you move mouse over the chart)
![image](https://user-images.githubusercontent.com/10025771/66811008-880a9200-ef5a-11e9-9d6f-afc095fe6aca.png)
https://www.amcharts.com/demos/stacked-area/

What about ranges - works differently on different machines: on dev machine ranges are shifted to the right side (on 20% aprox), on production (app compiled with prod conf) - ok.

Also the same bug you have on demo page:
![image](https://user-images.githubusercontent.com/10025771/66811915-1fbcb000-ef5c-11e9-9312-1f96d2704a94.png)

So no need to past code here. You can see all bugs on demo page.

My browser: Chrome 77

**Comment by prodenx** [comment]
@martynasma sorry, have the same bugs on production

**Comment by martynasma** [comment]
That demo is not right. It places start/end of the range at month 1 which means February, hence the shift.

Fixed to use January.

Thanks for the heads up!

**Comment by prodenx** [comment]
@martynasma Thanks. Now I understand how it works. What about the first issue? (tooltip on x axsis and grid line do not have the same place as label when you move mouse over the chart)

**Comment by martynasma** [comment]
Cursor is placed in the middle of the category/period. While the axis range follows exact start and end dates.

**Comment by prodenx** [comment]
@martynasma I am talking about ranges now, but about label and grid on x axis
![image](https://user-images.githubusercontent.com/10025771/66902205-742e6100-f02a-11e9-8fa9-040ebb6749e6.png)
You can see that label, grid and point on series do not have same postion for same date. But if you zoom chart then they fit
![image](https://user-images.githubusercontent.com/10025771/66902423-d2f3da80-f02a-11e9-9f59-4e0b9fa2a455.png)

Please check this on the demo
