### ISSUE TITLE
Page load stuck for zoomed, low resolution Chrome page

### ISSUE THREAD

**Issue by mkutlu** [amcharts/amcharts4#1753]
Hi, I confront a issue about resolution and zoom performance. When I use 1366*768 screen and Chrome zoom rate %70, page is not loading.  There is no problem with 100% but when I decrease rate, page stuck on resfresh load. I disabled amcharts graphs and page loaded without any problem. I stopped script execution from developer console few times to understand where code actually. Normally after page load that script execution pointer shows "this.update();" line but at this situation script not points this lines. Seems like graphs load very slowly.

At this point, what can be the problem?

**Comment by martynasma** [comment]
Do you get this on some particular charts/setups, or any chart?

I did try it on some of the demos on amcharts.com and they do not seem to hang the browser on load. E.g. this:
https://www.amcharts.com/demos/line-graph/

If you could post a demo or a link to the page which exhibits this behavior, we'd take a look.

Otherwise, I can only hazard a guess that some CSS/JS or other layouting mechanisms on your page make the chart container resize constantly, causing it to resize itself as well, resulting in dead loop.

To test this theory, try disabling auto-resize of the charts:

```
chart.svgContainer.autoResize = false;
```

**Comment by mkutlu** [comment]
I tried "chart.svgContainer.autoResize = false;" for each chart but it is not solved. It is only problem for our main dashboard, which contains 20-30 graph. Other pages do not have any problem. But we roll back our previous version, which we upgraded 4.4.2 to 4.4.7. At version 4.4.2 problem not occur.  

Maybe not related but one of our console error came back with that downgrade:

![image](https://user-images.githubusercontent.com/9056500/66814630-9a2b0700-ef3f-11e9-880e-b4fbeb5757cd.png)

**Comment by martynasma** [comment]
How about `4.7.0`?

**Comment by mkutlu** [comment]
No version 4.7.0 not worked. I tried version from 4.4.2 one by one. Problem started with 4.4.5. IE and firefox does not have any problem.

**Comment by martynasma** [comment]
Gotcha. Though we'll need some way to reproduce this issue before being able to fix it.

**Comment by mkutlu** [comment]
I will try to prepare similar test page for you.

**Comment by mkutlu** [comment]
Hi @martynasma ! I minimized page. It just contains basic libs. Problem still continue. I am using 1080p resolution. Chrome version 77.0.3865.120. You can set page zoom into 75%.
Page first load seems like completed. But it causes high memory usage. You can check task manager. If you reload page second time, then page will not load even partially and stuck chrome page. 
Here is the code:
https://drive.google.com/file/d/1sH2BlpJmoKwWCOqwEqyaviGeYYx3yzz0/view?usp=sharing

**Comment by mkutlu** [comment]
@martynasma Is there any progress on this issue?

**Comment by martynasma** [comment]
What should I be seeing when I run your standalone demo?

This is what I get, regardless of zoom setting:
![image](https://user-images.githubusercontent.com/1458520/68183708-d8976d00-ffa5-11e9-8400-7c0255b0dd3c.png)

**Comment by mkutlu** [comment]
![image](https://user-images.githubusercontent.com/9056500/68191154-eeb22700-ffbf-11e9-94be-ae764ce90f39.png)

In our case page is not loading. It stucks and page load keeps going. Also chrome memory usage hit 99s for this page. Sometimes page loads as your screen. But when reload it happens again.

We test it with different machines. The problem continues.
Please try few options on chrome zoom rate. We confront that problem with fifferent rates for each machines.
