### ISSUE TITLE
Unability to set the bullet color depending on value

### ISSUE THREAD

**Issue by maf1a** [amcharts/amcharts4#1754]
Made a StackOverflow question for you, please review to improve the functionality of the framework (or in case i am stupid just tell me the way to solve it). Thank you :)
https://stackoverflow.com/questions/58378896/how-can-i-set-color-of-the-bullet-depending-on-the-data-passed-from-the-external

**Comment by martynasma** [comment]
Looks like you answered that SO question yourself ;)
