### ISSUE TITLE
Html with AmChart jQuery to PDF Conversion taking time in HiQ or other PDF Converter. 

### ISSUE THREAD

**Issue by erhspatel** [amcharts/amcharts4#1755]
We have upgrade Amchart version 3 to 4. In Amchart Version 3, PDF Conversion with HIQ PDF, It's Working fine but After implement Amchart version 4, It's taking wait time 5 sec to 50 sec in PDF Conversion in AMchart 4. I have attached my html file.(Test.txt) and For normal html load, Document Content load time is 3 sec. It's very high rather than previous verison of amchart.

Reference URL.
http://www.hiqpdf.com/demo/ConvertHtmlToPdf.aspx

[test.txt](https://github.com/amcharts/amcharts4/files/3727754/test.txt)
![amchartdebuggermode](https://user-images.githubusercontent.com/28670185/66808481-f3e3ff00-ef48-11e9-8a55-447162a5abb8.png)

**Comment by erhspatel** [comment]
Have you got any solution for this issue?

**Comment by erhspatel** [comment]
@martynasma Please give any solution for this issue. This issue hold my production deployment.

**Comment by martynasma** [comment]
I'm sorry, I've never used HIQ PDF, so can't provide any insights into it.

**Comment by erhspatel** [comment]
It's not specific HIQ PDF. AM Chart 4 html to PDF conversion is not working on other PDF conversion tools like winnovative, selectPDF. I have verified in these tools.

**Comment by martynasma** [comment]
I'm not sure what "HTML to PDF" means in context of amCharts 4. We don't use HTML in charts.

**Comment by erhspatel** [comment]
We have used your Amchart 4 in our page. In PDF conversion, we are generated html of all amcharts and out content and converting to PDF. In Amchart V3, We are using same process to generated PDF. It's working fine.

I will give you simple example of your team created amchart.
1) For now, I have using [this amchart](https://codepen.io/team/amcharts/pen/mdbXvXo).
2) I have generated this amchart code to html string. I have added html file as text file into AmchartTestForGitHubExample ZIP. (In my code more than one amcharts)
3)Copy html string and Paste to [HIQPDF](http://www.hiqpdf.com/demo/ConvertHtmlToPdf.aspx) html content box.
4) please add Waittime(It's for jquery load time) 5 second into box. It's generated perfectly. For One AMchart, It's taking time more 4 second. It's too much.



[AmchartTestForGitHubExample.zip](https://github.com/amcharts/amcharts4/files/3761538/AmchartTestForGitHubExample.zip)

**Comment by martynasma** [comment]
I'm sorry, but this looks like a support request for particular PDF conversion tool, which we're not familiar with. This question is out of scope of amCharts support.
