### ISSUE TITLE
Container not visible in amcharts4

### ISSUE THREAD

**Issue by shripradashivakumar** [amcharts/amcharts4#1757]
Here is what i am doing in amcharts4 to add a chart inside a container. But charts are being displayed and not the container (the nice box). What am i doing wrong? Any inputs will be useful.   

    var container = am4core.create('chartdiv5', am4core.Container)
    container.width = am4core.percent(100)
    container.height = am4core.percent(100)
    container.layout = 'vertical'

      //Create chart instance
      var chart = container.createChild(am4charts.XYChart)

**Comment by shripradashivakumar** [comment]
The chartdiv5 is the html div container ID.

**Comment by martynasma** [comment]
`Container` is a virtual thing. There is no "nice box". Much like `<div>` in HTML - you just put stuff in it, there are no decorations that come with it unless you add them.

**Comment by shripradashivakumar** [comment]
oh thanks. realised what i was doing wrong!
