### ISSUE TITLE
The tooltips with rich HTML content is not showing in case the data not full enough on the line chart

### ISSUE THREAD

**Issue by havietduc91** [amcharts/amcharts4#1759]
Hi Amchart team,

Firstly, thank you a lot for the effort you've put into this library.
Secondly, I'm facing the issue is that the tooltips with rich HTML content is not showing in case the data not full enough on the line chart, like the bellow image, the tooltip does not show when we hover date is 1995
![Screenshot (72)](https://user-images.githubusercontent.com/4966192/66897518-5ad4e700-f021-11e9-9ac8-9d10aaf5fb8f.png)

For example: 
We have a statistic about the number of `car`, `motorcycles`, `bicycles` from 1994 to 2012. But we lost data for `bicycles` in 1994, 1995 and  `car` in 1996 and `motorcycles` in 1997 also, something like the below image:
![Screenshot (73)](https://user-images.githubusercontent.com/4966192/66897796-f2d2d080-f021-11e9-910f-2d7609e7989c.png)
So how can we show the tooltip when we hover the date is 1994, 1995, 1996 and 1997?

Please refer to this example to know more: https://codepen.io/havietduc91/pen/rNNLWJN
Example build from https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/
 
Many thanks,

**Comment by martynasma** [comment]
If you expect your data for the series you display consolidated tooltip for to have gaps like that, then I suggest adding a fourth series - no bullets, `strokeOpacity = 0` so it's hidden - with data for each year and value set to zero, then adding `tooltipHTML` to that series.

**Comment by havietduc91** [comment]
Thank @martynasma for a quick response.

In this situation, I think that's a good idea, I try to implement and it's work as expected, like the below image

![Screenshot (74)](https://user-images.githubusercontent.com/4966192/66973295-bfe01980-f0c1-11e9-8b41-54af3a49e397.png)

I will close this issue right away, many thanks.
