### ISSUE TITLE
localization: Does file extensions need to be translated?

### ISSUE THREAD

**Issue by bsvensson** [amcharts/amcharts4#176]
Not sure if I'm looking in the right place for version 4 localization, but ... in [en.js](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/.internal/lang/en.js):
```
    "PNG": "",
    "JPG": "",
    "GIF": "",
    "SVG": "",
    "PDF": "",
    "JSON": "",
    "CSV": "",
    "XLSX": "",
```
https://github.com/amcharts/amcharts4/blob/master/dist/es2015/.internal/lang/en.js#L242-L249
Are these file extensions?  If so, wouldn't they be the same for all locales, and thus not need to be localized? If so, it would maybe be better to remove them from the localization files and hardcode in the library.

**Comment by martynasma** [comment]
Good catch.

Those are not extensions, but actually format names, used in Export menu. Even though we don't translate them in English, we can't predict how they might be used in other languages, hence them being in there.

If you are working on a translation, you can leave those as they are.

Hope that makes sense and sounds reasonable.
