### ISSUE TITLE
Legend's position in map chart.

### ISSUE THREAD

**Issue by BesoKakulia** [amcharts/amcharts4#1763]
Hi, I want to adjust the map's size depending on the legend's position, but when I align legend it overlaps the map [(example)](https://codepen.io/beso-kakulia/pen/QWWEaZO?=true). In charts when I use position property it works correctly [(example)](https://codepen.io/beso-kakulia/pen/Exxyoer?=true), it reduces chart's size for fitting the legend. But for maps alternatives for the `position` are `align` and `valign` properties. How can I fix it?
Thanks!

**Comment by zeroin** [comment]
The behavior is different for regular charts and maps, it's by design. To solve this, you should create initial Container and put both chart and legend to this container, like in this demo:
https://codepen.io/team/amcharts/pen/3b51054565ab4dbda7b9e0eb302b8f4e

**Comment by BesoKakulia** [comment]
> The behavior is different for regular charts and maps, it's by design. To solve this, you should create initial Container and put both chart and legend to this container, like in this demo:
> https://codepen.io/team/amcharts/pen/3b51054565ab4dbda7b9e0eb302b8f4e

Thanks!
