### ISSUE TITLE
LineChart with grouping enabled displays bullets incorrectly

### ISSUE THREAD

**Issue by tmalaher** [amcharts/amcharts4#1764]
With `dateAxis.groupData = true`, `series.minBulletDistance = 7.5` and `series.groupFields.valueY = "average"` when I zoom in far enough that the bullets are displayed but the data is still grouped, the bullets are displayed *off* the line, and the tooltip is not displaying consistently (some points display, some don't, depending on zoom level and position on the graph... hard to describe).

![image](https://user-images.githubusercontent.com/41802/66936946-cd32d080-effb-11e9-9d4a-d255ecb1c736.png)

Zooming in slightly causes the grouping to stop and the bullets appear in the expected locations and the tooltips start working again:

![image](https://user-images.githubusercontent.com/41802/66937697-2d764200-effd-11e9-9ba9-eeb283f62afb.png)

Using version 4.7.1, apparently, directly from `www.amcharts.com/lib/4/core.js`

**Comment by zeroin** [comment]
Could you provide a codepen of the situation? I tried to reproduce but with no luck :(

**Comment by whakaoo** [comment]
I have the same problem on rAmCharts4 (vers. 1.3.1). After zooming and dragging the bullet is wrongly positioned and in some cases disappear.
