### ISSUE TITLE
How can I get a different color for each column in amcharts4

### ISSUE THREAD

**Issue by shripradashivakumar** [amcharts/amcharts4#1767]
I have a column series bar chart with 5 columns and i need to put a different color for each of it. Is there a way to do that?
<img width="762" alt="Screenshot 2019-10-17 at 4 14 51 PM" src="https://user-images.githubusercontent.com/50405790/67002313-46fcb400-f0f9-11e9-9a59-6d215526fbcc.png">

**Comment by zeroin** [comment]
You can use adapters for that, this demo does the thing:
