### ISSUE TITLE
Need examples or feature request.

### ISSUE THREAD

**Issue by NemoDima** [amcharts/amcharts4#1771]
There are two examples of amcharts, when clicking or hovering over a legend, it changes the state of the lines on the chart.
https://www.amcharts.com/docs/v4/tutorials/highlighting-column-series-on-legend-click/
https://codepen.io/vovaltus/pen/LYYRGjq
But we cannot adapt them to our needs.
1. 
a) When we hover over the legend, to highlight the line on the chart.
b) If the line thickness is 0 as here: https://codepen.io/vovaltus/pen/jOONJOv highlight the bullets.
2. Also, when hovering over a line, it should be highlighted, an example here:
https://codepen.io/vovaltus/pen/QWWKydG
Thanks in advance for your help.

**Comment by NemoDima** [comment]
Please, any suggestions.

**Comment by NemoDima** [comment]
@martynasma am I right that example https://www.amcharts.com/docs/v4/tutorials/highlighting-column-series-on-legend-click/ close to my request(1a, 1b), but its a ColumnSeries, not LineSeries.
https://github.com/amcharts/amcharts4/issues/1512

Tell me please, how I can adapt it for the LineSeries?

And still can't find any examples for highlighting LineSeries when move mouse on it.
Same as: https://codepen.io/vovaltus/pen/QWWKydG

Appreciate for help.

**Comment by martynasma** [comment]
Maybe this will help:
https://codepen.io/team/amcharts/pen/mZoXVY
