### ISSUE TITLE
Label text color alternate changing in accordance to column series color in amcharts4 

### ISSUE THREAD

**Issue by shripradashivakumar** [amcharts/amcharts4#1772]
Hi, 

I have a stacked column series graph with 5 colours and i am using series[i].columns.template.fill = am4core.color(COL_COLORS[i]) to fill the colors in a loop for all the series.
(i is coming from the looping logic in my code)

And I am using valueLabel[i] = series[i].columns.template.createChild(am4core.Label)
and filling the corresponding labels with - valueLabel[i].fill = series[i].fill.alternative

The result is in the attachment - 
<img width="1356" alt="Screenshot 2019-10-18 at 7 55 40 AM" src="https://user-images.githubusercontent.com/50405790/67061094-ced7d200-f17c-11e9-9487-fae247b343e9.png">

the 2nd series from the end (dark green) has still has its text color as black, while the dark blue (seen in the stacked first bar) has a white color text. 

Pointers on what i am doing wrong would be great. Or is there any alternate way to achieve this?
I basically want white text on dark colors and black on light ones. (similar to how tooltop behaves by default)

**Comment by martynasma** [comment]
What is the dark green color hex?

I grabbed #325022 from the image, then tried to output it via amCharts alternative color mechanism. It gives white, so it should be gtg.

Maybe you can post your whole chart on codepen/jsfiddle?

**Comment by shripradashivakumar** [comment]
`
const COL_COLORS = ['#E5813A', '#DDDB48', '#2B4360', '#479B30', '#28521B']
// Create chart instance
    let chart = am4core.create('chartdiv1', am4charts.XYChart)

    // Add data
    // chart.data = this.state.data
    
    // Create axes
    let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis())
    categoryAxis.dataFields.category = 'calibrated_level'
    categoryAxis.renderer.grid.template.location = 0
    categoryAxis.renderer.minGridDistance = 20
    // categoryAxis.renderer.inside = true
    // categoryAxis.renderer.labels.template.valign = 'top'
    categoryAxis.renderer.labels.template.fontSize = 20
    categoryAxis.renderer.cellStartLocation = 0.1
    categoryAxis.renderer.cellEndLocation = 0.9

    let valueAxis = chart.yAxes.push(new am4charts.ValueAxis())
    valueAxis.renderer.grid.template.disabled = true
    valueAxis.min = 0
    valueAxis.max = 100
    valueAxis.renderer.minWidth = 20
    valueAxis.strictMinMax = true
    valueAxis.calculateTotals = true
    valueAxis.renderer.minWidth = 50

    // Create series
    function createSeries (field, name, color) {
      let series = chart.series.push(new am4charts.ColumnSeries())
      series.dataFields.valueY = field
      series.dataFields.categoryX = 'calibrated_level'
      series.dataFields.valueYShow = 'totalPercent'
      series.name = name
      // series.columns.template.width = am4core.percent(95)
      series.columns.template.maxWidth = 30
      series.columns.template.tooltipText = "{valueY.totalPercent.formatNumber('#.0')}%"
      series.tooltip.pointerOrientation = 'vertical'
      series.columns.template.fill = am4core.color(color)
      series.columns.template.stroke = am4core.color('#ffffff')

      let valueLabel = series.columns.template.createChild(am4core.Label)
      valueLabel.adapter.add('text', (text, target) => {
        let value = target.dataItem.values.valueY.totalPercent
        return value < 15 ? '' : "{valueY.totalPercent.formatNumber('#.0')}%"
      })
      valueLabel.valign = 'middle'
      valueLabel.align = 'center'
      valueLabel.strokeWidth = 0
      valueLabel.rotation = 270
      valueLabel.fill = series.fill.alternative
    }

    chart.maskBullets = false

    createSeries('Below Expectations', 'Below Expectations', COL_COLORS[0])
    createSeries('Development Needed', 'Development Needed', COL_COLORS[1])
    createSeries('Solid Performer', 'Solid Performer', COL_COLORS[2])
    createSeries('Exceeds Expectations', 'Exceeds Expectations', COL_COLORS[3])
    createSeries('Role Model', 'Role Model', COL_COLORS[4])

    // chart.cursor = new am4charts.XYCursor()
    chart.legend = new am4charts.Legend()
    chart.legend.itemContainers.template.clickable = false
    chart.legend.itemContainers.template.focusable = false
    chart.legend.itemContainers.template.cursorOverStyle = am4core.MouseCursorStyle.default`

Hex code - #28521B. sorry cannot paste the full working code. but this is the chart part of it. even with the hex code you have mentioned, i still end up with a black text color.

**Comment by martynasma** [comment]
Ok, so I think I know what's going on.

You set the color to the `series.columns.template.fill`.

However, you check the alternative color of `series.fill`.

To fix simple update your label color check to draw from column fill:

```
valueLabel.fill = series.columns.template.fill.alternative;
```

**Comment by shripradashivakumar** [comment]
Thank you. This worked for me :)
