### ISSUE TITLE
When axis is inversed, the scrollbar system tooltip is not inversed

### ISSUE THREAD

**Issue by yingyinghu** [amcharts/amcharts4#1773]
When axis is inversed, the scrollbar system tooltip is not inversed. It's still on normal order.

https://codepen.io/nanamissier/pen/WNNGKYe

**Comment by martynasma** [comment]
Do you mean this:

![image](https://user-images.githubusercontent.com/1458520/67081167-533b4c80-f19f-11e9-9783-73beed000e01.png)

It should say From Jan 08 to Jan 01 instead?

**Comment by yingyinghu** [comment]
> should say From Jan 08 to Jan 01 instead?

Yes.

**Comment by martynasma** [comment]
Gotcha. We'll fix this.

**Comment by martynasma** [comment]
## [4.7.4] - 2019-10-22

## Added
- New global option: `am4core.options.viewportTarget`. If you are placing charts into a scrollable container and using `onlyShowOnViewport`, set this option to a reference to the container. The system will monitor both window and individual scroll of the container to know where to reveal the lazy-loaded chart.
- New `MapChart` property: `geodataNames`. It can now be used to automatically translate country names into multiple languages. Check out [usage instructions](https://www.amcharts.com/docs/v4/tutorials/using-map-country-name-translations/).
- `hideParentColumns` property added to `TreeMap`. If set to `true` columns of the parent series will be hidden when user drills-down into deeper levels.

### Fixed
- `ColorSet` was starting to generate grayscale colors at some point.
- Accessibility: Series that has items with roles "menuitem" will now have its role set to "menu" automatically.
- Series bullets were dislocated on `XYChart` with `DateAxis` and `dateFormatter.utc = true`.
- In some specific cases 3D columns used incorrect `zIndex`.
- Index of dataItem of `PercentSeries` could be `-`1 after first render.
- `yRange` of `XYCursor` was inversed.
