### ISSUE TITLE
[CategoryAxis].tooltip changes it's position when toolitpText is changed

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#1774]
Example:
https://codepen.io/dmsmaxim/pen/RwwGqve
![image](https://user-images.githubusercontent.com/15041200/67091693-044ce180-f1b6-11e9-969f-191be1801778.png)
For example, if you hover on the year 1994 and wait for 3s and then change `tooltipText`, the tooltip shifts to the center for some reason:
![image](https://user-images.githubusercontent.com/15041200/67091889-8210ed00-f1b6-11e9-96f7-d494bff778a6.png)

**Comment by martynasma** [comment]
Why would you do something like that? If you explain what you are trying to achieve, I'm sure we can find some way to do it in a safe way.

**Comment by dmsmaxim** [comment]
I'm trying to create a common tooltip (category tooltip) where all series' tooltips are merged together with some other text. In this common tooltip, I want to highlight (with `[bold]`) some pieces of the text accordingly to what series is hovered at a given time (this information is tracked via over/out event listeners on a series and then is being saved in a variable).
I use a category tooltip adapter, where I can compose this common tooltip. But since recent times it's not possible anymore, because tooltip adapters now called only when XCursor changes its position horizontally. So when you just move the mouse cursor to another line on the linear chart (on the same vertical), that adapter is not being called.
So, my new solution is to change tooltip's text from the series' event listeners. But when I do this, tooltip for some reason shifts to the center as I've shown you in the example.

**Comment by martynasma** [comment]
Gotcha.

In this case, you should be probably better off updating tooltip's label directly:

```
axis.tooltip.label.text = ".....";
```

Or, you can try invalidating the label so it is drawn anew and adapter kicks in again:

```
axis.tooltip.label.invalidate();
```

**Comment by dmsmaxim** [comment]
Thanks.
The first option works for me.
The second one looks more appealing to me but unfortunately doesn't work. The adapter simply is not being called
