### ISSUE TITLE
Is there any resource for geodata available in other languages?

### ISSUE THREAD

**Issue by eestein** [amcharts/amcharts4#1776]
I'm using worldLow from amcharts4-geodata (@amcharts/amcharts4-geodata/worldLow). But I can't find translated resources. The lib provides the ability to change locales, but not for geodata. Is that possible? That's the only part of my app that will remain in English after changing the language. It's not great.

I dug into the code a little bit and noticed the countries' names are hard coded inside the files, so, I'm assuming, a different resource would be required. Is it possible?

**Comment by martynasma** [comment]
Good point. It's easy to provide own translations via series `data`, but we'll think if maybe we could provide some automated solution.

Will keep you posted.

**Comment by eestein** [comment]
Thanks. When you say "provide own translations via series data", you mean translating every entry, right? Do you have an example on how to do that? If it's not overkill, I might implement that until you provide the automated version.

**Comment by martynasma** [comment]
Sure:

```
polygonSeries.data = [{
  id: "US",
  name: "Estados Unidos"
}, {
  id: "DE",
  name: "Alemania"
}];
```

**Comment by martynasma** [comment]
And voila:
https://www.amcharts.com/docs/v4/tutorials/using-map-country-name-translations/

**Comment by eestein** [comment]
Amazing! Thank you for the fast response and fix!
