### ISSUE TITLE
Default ColorSet Generating Grey Colors

### ISSUE THREAD

**Issue by puddings** [amcharts/amcharts4#1777]
Hi,

I have a stacked bar chart with the default ColorSet and a color step of 3 (for better readability). Before I updated my Amcharts version (4.5.4), the new lighter colors will be generated once the ColorSet runs out of color while populating the chart.

After updating to the latest version (4.7.3), I noticed grey colors are being generated instead of lighter versions of the default colors. May I know why this is happening, and if possible, how do I get around this issue?

Thank you.

![image](https://user-images.githubusercontent.com/3920132/67175118-62b4d280-f3f7-11e9-9d8e-3455c7a2d74b.png)

**Comment by martynasma** [comment]
## [4.7.4] - 2019-10-22

## Added
- New global option: `am4core.options.viewportTarget`. If you are placing charts into a scrollable container and using `onlyShowOnViewport`, set this option to a reference to the container. The system will monitor both window and individual scroll of the container to know where to reveal the lazy-loaded chart.
- New `MapChart` property: `geodataNames`. It can now be used to automatically translate country names into multiple languages. Check out [usage instructions](https://www.amcharts.com/docs/v4/tutorials/using-map-country-name-translations/).
- `hideParentColumns` property added to `TreeMap`. If set to `true` columns of the parent series will be hidden when user drills-down into deeper levels.

### Fixed
- `ColorSet` was starting to generate grayscale colors at some point.
- Accessibility: Series that has items with roles "menuitem" will now have its role set to "menu" automatically.
- Series bullets were dislocated on `XYChart` with `DateAxis` and `dateFormatter.utc = true`.
- In some specific cases 3D columns used incorrect `zIndex`.
- Index of dataItem of `PercentSeries` could be `-`1 after first render.
- `yRange` of `XYCursor` was inversed.
