### ISSUE TITLE
timeline chart - update interval on zoom

### ISSUE THREAD

**Issue by nmase88** [amcharts/amcharts4#1779]
I'm currently trying to use the new timeline charts to display changes to a version controlled folder across time. Could you tell me if it's possible to, when zooming, alter the interval i.e. if I have changes spanning days then the interval gets set to days (unless otherwise specified). I would like it so that if I zoom to a specific day the interval can update to hours.

**Comment by martynasma** [comment]
Check data point item grouping:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping

**Comment by nmase88** [comment]
That's great thanks, that seems to have done what I need. A few minor things but I'm sure they will just be settings/config I need to adjust.

Thank you!
