### ISSUE TITLE
Show single tooltip instead of many- JSONconfig

### ISSUE THREAD

**Issue by amodis** [amcharts/amcharts4#1780]
Im trying to show only one tooltip on the column and line chart. Now when I create stacked column chart and I hover on column, it's  show me all tooltips from this column. Similary on the line chart.
I would only want to see tolltip with category and value of one that i hover on. Like on the picture. 
[https://imgur.com/a/1Vwjont](https://imgur.com/a/1Vwjont)
Is it possible to do this in jsonconfig?
I tried to do this with bullets, but still not working.
demo:
[https://codepen.io/lukasss/pen/QWWdjgJ](https://codepen.io/lukasss/pen/QWWdjgJ)
[https://jsfiddle.net/97xys8ae/1/](https://jsfiddle.net/97xys8ae/1/)
[https://jsfiddle.net/97xys8ae/2/](https://jsfiddle.net/97xys8ae/2/)
Thank You.

**Comment by martynasma** [comment]
Take a look at this tutorial:
https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/

**Comment by amodis** [comment]
That's not what im looking. This one show all series in one tooltip. My problem is that i want to hover mouse on one series in column (one color in column) and see one tooltip with value. Now i see all tooltips from column when i hover on it. Same with line chart.
Like on the photos for example. When I hover on blue i want to see c: 37 and when i hover on violet i want to see only e: 4.
[https://imgur.com/a/6JXela6](https://imgur.com/a/6JXela6)
And now when I hover on any color in column i always see all tooltips.
[https://imgur.com/a/Z81sLYv](https://imgur.com/a/Z81sLYv)
Same with line series.
I wan to do this in jsonconfig.
Thank You.

**Comment by amodis** [comment]
Yes, that's the solution of my problem.
Thank You

**Comment by megharajdeepak** [comment]
Hi @amodis 
I am looking for same implementation for line chart. ie., I want to show tooltip only on hovering a particular line. Based on @martynasma 's suggestion, I set cursorTooltipEnabled of each of the series to false. With that, the default behaviour of showing all the tooltips of all the series for a given month is disabled. However, I dont get to see the actual tooltip on hovering a line.
Kindly let me know if there any any other additional change I need to make to get it work.

**Comment by megharajdeepak** [comment]
<img width="272" alt="Untitled" src="https://user-images.githubusercontent.com/5477084/102860032-1168fe80-4453-11eb-92d4-a1309d5faf52.png">

This is how it shows up currently.
