### ISSUE TITLE
How to change scrollbar with series background style

### ISSUE THREAD

**Issue by yingyinghu** [amcharts/amcharts4#1781]
Hello, I need help to change visibility for scrollbar unselect area.
With default value, it´s a bit difficult to see the interval text in gray. How can I change this value opacity or color?

![image](https://user-images.githubusercontent.com/11941866/67219777-e0450680-f428-11e9-9e89-6e2d6ad72f1d.png)

Thankss.

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/tutorials/customizing-chart-scrollbar/#Customizing_fills

**Comment by yingyinghu** [comment]
Thanks, It helps a lot.
