### ISSUE TITLE
When limit scrollbar, horizontal scrollbar init on right and vertical on bottom

### ISSUE THREAD

**Issue by yingyinghu** [amcharts/amcharts4#1782]
When limit scrollbar with maxZoomCount, horizontal scrollbar init on right and vertical on bottom.
Can I change this behavior without inversed the value?

After validateDate, the zoom area of horizontal dataAxis is restored to initial right position. Can I save the last zoom position for DateAxis? I try this but I dont find how.

(Press on series column to refresh data and see the behavior)
https://codepen.io/nanamissier/pen/eYYdjxB

**Comment by zeroin** [comment]
To keep the selection after data validate, add this to your source:

`dateAxis.keepSelection = true;`

To change the initial zoom position you must either specify dateAxis.start and dateAxis.end values or  zoom the date axis after the chart is inited.
