### ISSUE TITLE
Question: How to access from category axis text adapter action the category value

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1784]
When I use something like: 
```
    categoryAxisLabelTemplate.adapter.add('text', (text, target, key) => {
      debugger;
      return `[bold font-size: 1.0em]${text}[/]`;
    });
```

On a TimeLine Plugin Spiral Chart the target is an AxisLabel and has an Axis etc but I cannot find and relation to the original data eg 

```
{timestamp, value}
```

Since for example in that case the text holds only `Nov 2019` for example, and the 
```
    categoryAxis.renderer.labels.template.text = '{category}, {value}'
```

Does not seem to change the adapter text input argument `text`

here: 

`  categoryAxisLabelTemplate.adapter.add('text', (text, target, key) => {`

I did try to traverse the target and could find the original value of the item and the data of the chart, but that feels hacky.

**Comment by martynasma** [comment]
How about `target.dataItem.category`?

**Comment by jimmykane** [comment]
Yea getting there. The callback returns many times unidentified for this property but for some works. 

I think this will do. Closing this

**Comment by martynasma** [comment]
> The callback returns many times unidentified for this property but for some works.

Yeah, because axis generates "extra" label elements just in case it needs to show more labels after some zoom/updates, also there's a "phantom" label used for maintaining height/width of the axis etc.

All those labels do not have dataItem attached to them (they are not visible), so you should probably implement check if dataItem exists.

**Comment by jimmykane** [comment]
hmmm 

When the category axis is a date axis I suppose I should look at the date instead of category. 

However, when I have a category axis I can already find the datacontext that has the data vlaues for that category. 

Using a date axis , it deent have any other info than dates.

**Comment by martynasma** [comment]
Correct. `DateAxis` does not have any relation to particular data context items - it's just a time scale.
