### ISSUE TITLE
JSON ValueAxis numberFormatter overriden by global?

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#1785]
Looking at recommendations in #1503, I attempt to create chart from JSON using a ValueAxis numberFormatter that is different (0 decimal digit) from the global numberFormatter (1 decimal digit).

Please see the [codepen](https://codepen.io/npc42/pen/KKKWKEY) — ValueAxis numberFormatter and maxPrecision properties seem to have no impact. If I remove the global numberFormatter, then all values have 0 decimal digits (including the y axis, not what I need).

PS If I put the global numberFormatter above the ValueAxis definition (which I can't easily do in my actual code, these properties are generated dynamically) — then seems to be ignored, although that's not much issue.

**Comment by martynasma** [comment]
If you need a separate instance of `NumberFormatter` to be created for your axis, you need to also add `forceCreate: true` directive:

```
"numberFormatter": { 
  "type": "NumberFormatter", 
  "numberFormat": "#.",
  "forceCreate": true
}
```

Otherwise it just inherits global instance of the formatter, then sets `numberFormat` on it, affecting the whole of the chart.

**Comment by NPC** [comment]
@martynasma this makes sense (and works!), thank you.

Out of curiosity, what does maxPrecision do? Or is it to be used only when there's no formatter (global or local)?

**Comment by NPC** [comment]
@martynasma Nevermind, I discovered that it affects grid lines and labels. When will I ever learn to read documentation attentively? /s
