### ISSUE TITLE
Close no-parents nodes by click

### ISSUE THREAD

**Issue by nasodan** [amcharts/amcharts4#1786]
I've three nodes on the same level. Each one has some children.
If I click on a child i'd like close (if are opened) the nodes that are not parent of my clicked child.
It's possible?

**Comment by nasodan** [comment]
sorry, i'm working with ForceDirected

**Comment by martynasma** [comment]
Something like this:
https://codepen.io/team/amcharts/pen/ExxmJoK

**Comment by nasodan** [comment]
Yes this is very useful in general, but ther is a way to get a specific node by id.
I would like to be able to decide which node to close through the node id. Something like getElementById
Thanks a lot

**Comment by martynasma** [comment]
There's no such method, I'm afraid.

You can iterate through nodes and check:

```
series.nodes.each(function(node) {
  if (.....) {
    .....
  }
});
```

**Comment by nasodan** [comment]
Ok Thanks you.
