### ISSUE TITLE
Chart disappears when scrolling

### ISSUE THREAD

**Issue by ilxanlar** [amcharts/amcharts4#1787]
![amcharts](https://user-images.githubusercontent.com/5252133/67382849-07234a00-f59b-11e9-9bf0-3b9a39a70dce.gif)

I'm using scrollbars with preview but the same happens with simple scrollbars too.
Version: `@amcharts/amcharts4@4.6.4`

**Comment by zeroin** [comment]
Any chance you could create a codepen with this happening? It's not much we can tell without having code and data.

**Comment by martynasma** [comment]
Also, have you tried it with the latest version (4.7.4)?

**Comment by ryanli-me** [comment]
I got the same issue with 4.7.4. However, I looked at my data and found that the order of objects inside the data array is reversed. Namely, the array has descending date (2019-10-23, 2019-10-22). I reversed the array and everything works fine. @ilxanlar Hopefully this helps you.

**Comment by martynasma** [comment]
@ryanli-me Thanks for sharing that. Yes, order of data is important, and can produce visual anomalies when data is not ordered properly.
