### ISSUE TITLE
Support for long axis titles

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#1788]
Example:
https://codepen.io/dmsmaxim/pen/KKKWymB
![image](https://user-images.githubusercontent.com/15041200/67385739-5322be80-f59c-11e9-9bd6-c94f66a8ad83.png)
For some reason, the title is not fully shown.
I think it would be better if a multiline title was supported here

**Comment by zeroin** [comment]
We will think if we can add it as a default behavior, meanwhile you can solve it by setting width of a title and wrap to true:

```
valueAxis.title.width = 300;
valueAxis.title.wrap = true;
```

**Comment by dmsmaxim** [comment]
What if my diagram can be changed sometime (by user) in width? I need adaptive width...

**Comment by martynasma** [comment]
You can do something like this:

```
valueAxis.title.wrap = true;
valueAxis.events.on("sizechanged", function(ev) {
  ev.target.title.maxWidth = ev.target.measuredHeight;
});
```

**Comment by dmsmaxim** [comment]
Thanks.
But of course, it would be awesome if it was by default

**Comment by martynasma** [comment]
Agreed. We'll definitely consider this.

**Comment by martynasma** [comment]
As we're trying to avoid too much fuzzy logic, we won't be implementing this. Sorry.

Please refer to the suggested solutions.
