### ISSUE TITLE
Change color node onClick in Force Directed Tree

### ISSUE THREAD

**Issue by nasodan** [amcharts/amcharts4#1790]
When I click on a node, I display some information loaded via jason in a div. Is it possible to change the color of the clicked node, so as to highlight to the user which node the information displayed in the div refers to?

**Comment by martynasma** [comment]
Whipped up something :)

https://codepen.io/team/amcharts/pen/KKKmYJP?editors=0010

Hope it helps.

**Comment by nasodan** [comment]
Lovely. Thanks a lot!

**Comment by nasodan** [comment]
There is al little bug. 
When a child is selected and i click on the father, the child focused doesn't close.

**Comment by martynasma** [comment]
Updated demo to fix that.

https://codepen.io/team/amcharts/pen/KKKmYJP?editors=0010

**Comment by nasodan** [comment]
Thanks a lot. Great!
