### ISSUE TITLE
Bug on openValueY

### ISSUE THREAD

**Issue by PedroPMV1** [amcharts/amcharts4#1791]
When i create a new line series to fill te gap of two values the chart doesn't appear, if i comment the line of the  openValueY the chart shows again.

here's a code pen example: https://codepen.io/PMV/pen/yLLMZGP
![1](https://user-images.githubusercontent.com/5107330/67430337-68a5e180-f5b8-11e9-90bc-dff08573a302.png)
![2](https://user-images.githubusercontent.com/5107330/67430338-693e7800-f5b8-11e9-8f4f-5c929893cb03.png)

**Comment by martynasma** [comment]
There are certain requirements for data order when used with `DateAxis`.

The data points must come in ascending order.

Furthermore, when you separate min value and max value in separate data points, the chart can't make a sense of the connection between the two. So you need to consolidate both values for the same date into the same data item:

```
var data = [{
  "year": new Date(2018, 0, 1),
  "minLow" : 123456,
  "maxLow" : 123456,
}, {
  "year": new Date(2018, 0, 10),
  "minLow" : 156,
  "maxLow" : 123459
}];
```

Hope that makes sense.
