### ISSUE TITLE
How can I change scale of Value Axis on waterfall chart

### ISSUE THREAD

**Issue by AGrazka** [amcharts/amcharts4#1792]
Hi,

I got problem with scaling value axis. Last column is hiding because of large numbers before it. 
Can't using logarithmic, three bars must open at 0. 

Can you help me? Thanks. 

![image](https://user-images.githubusercontent.com/41653062/67436718-63b05480-f5ef-11e9-8a1d-474a83e48471.png)

**Comment by zeroin** [comment]
I am afraid there is nothing you can do here. Well, maybe you could set a some bigger value but display smaller one, but that would be totally wrong from the data side.
