### ISSUE TITLE
how to customize tooltip in the piechart ?

### ISSUE THREAD

**Issue by RohitChangediya** [amcharts/amcharts4#1793]
![InkedScreenshot_4_LI](https://user-images.githubusercontent.com/7242037/67448321-4487e600-f634-11e9-9918-6c2e77e109cc.jpg)
Need to remove the text in image uploaded

**Comment by martynasma** [comment]
Try the docs ;)

https://www.amcharts.com/docs/v4/chart-types/pie-chart/#Changing_tooltip_content
