### ISSUE TITLE
Tooltip zindex and other page DOM

### ISSUE THREAD

**Issue by Ices-Eyes** [amcharts/amcharts4#1794]
Hi,
In a page I have lots of mini graph shown in a "card" content. What happen is that sometimes the tooltip on the graph gos under the near card div. Is there a way to solve the issue? I have tried to set a zindex for the tooltip, but without luck it seems. Thanks
![Tooltip_ZIndex](https://user-images.githubusercontent.com/13162428/67469286-42318600-f64c-11e9-8330-27356793bb9d.png)

**Comment by martynasma** [comment]
Setting `zIndex` on tooltip won't work because it still is a child of a chart's container, so it might have lower zIndex of the adjacent chart.

The good solution is to temporarily rise the `zIndex` of hovered container, e.g.:

```
.chart:hover {
  z-index: 100000;
}
```

(update CSS selector accordingly.

**Comment by Ices-Eyes** [comment]
It works perfectly, thank you very much! 👍
