### ISSUE TITLE
how to fix  height of value axis 

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#1797]
![image](https://user-images.githubusercontent.com/54665162/67479796-7755cc80-f67c-11e9-8af9-cf0b80a3ddb0.png)

here the max value header is overlap can u check how to fix this issue

and one more thing can i set value axis height

**Comment by martynasma** [comment]
What you probably looking for is not setting value axis height, but its scale.

You can use `min` to set the value starts on, e.g. set it to 0 (zero) to start from zero and show full height columns.

Please refer to this article for more information and tricks:

https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Adjusting_scale

**Comment by martynasma** [comment]
If you mean that bullets are cut off, the following will fix it:

```
chart.maskBullets = false;
```

**Comment by Mahisandy** [comment]
still some of part is cut off here you can check here by chnaging the json data
[{
    "name": "John",
    "points": 35654,
    "color": chart.colors.next(),
    "bullet": "https://www.amcharts.com/lib/images/faces/A04.png"
}, {
"name": "Damon",
"points": 195456,
"color": chart.colors.next(),
"bullet": "https://www.amcharts.com/lib/images/faces/C02.png"
}, {
"name": "Patrick",
"points": 145724,
"color": chart.colors.next(),
"bullet": "https://www.amcharts.com/lib/images/faces/D02.png"
}, {
    "name": "Mark",
    "points": 13654,
    "color": chart.colors.next(),
    "bullet": "https://www.amcharts.com/lib/images/faces/E01.png"
}];
link: https://www.amcharts.com/demos/column-chart-images-top/
[](https://www.amcharts.com/demos/column-chart-images-top/)

**Comment by martynasma** [comment]
Might need to give extra scale to the value axis using `extraMax`:

https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Relatively_expanding_the_scale
