### ISSUE TITLE
HeatRules and stroke

### ISSUE THREAD

**Issue by tlebreton** [amcharts/amcharts4#1798]
Hi everybody

I got a small problem with heatRules.
It seems that there is a little stroke between each column and i can't get ride of it.
I try the `column.template.strokeWidth = 0;` but still present.

![image](https://user-images.githubusercontent.com/24650214/67500015-542e1b80-f682-11e9-988d-948da00b3fa0.png)

i try to avoid this by settings `columnTemplate.propertyFields.stroke = "color";` but allways this small whiter dash.

Do you any idea? 

Is it possible to get more documentation on the heatRules property for now we got a `@todo description` :D

Thanks for your future response

Have a good day

Ps if you want example : https://codepen.io/team/amcharts/pen/pLOXgO

**Comment by martynasma** [comment]
Edges of the column will never be ideally "to the pixel", hence it will have some aliasing to offset for non-exact coordinates, resulting in slightly visible gaps between border-less columns.

The only sure way to work around it is to have column stroke colored same way as the columns. In a heatmap scenario it means repeating same rule for `stroke` as you have for `fill`:

```
series.heatRules.push({
  target: columnTemplate,
  property: "fill",
  min: am4core.color("#ffffff"),
  max: am4core.color("#692155")
});

series.heatRules.push({
  target: columnTemplate,
  property: "stroke",
  min: am4core.color("#ffffff"),
  max: am4core.color("#692155")
});
```

**Comment by tlebreton** [comment]
Hi 

Thanks a lot.
I don't know that we can chain the heatrules like this.

Will it be more convenient to put an array of property instead of two heatRules? (just an idea)

**Comment by martynasma** [comment]
Ummm... what's wrong with having two heat rules? :)

**Comment by tlebreton** [comment]
Nothink is wrong :D but in my opinion it's best to have 

```
series.heatRules.push({
  target: columnTemplate,
  property: ["fill","stroke"],
  min: am4core.color("#ffffff"),
  max: am4core.color("#692155")
});

```
instead of

```
series.heatRules.push({
  target: columnTemplate,
  property: "fill",
  min: am4core.color("#ffffff"),
  max: am4core.color("#692155")
});

series.heatRules.push({
  target: columnTemplate,
  property: "stroke",
  min: am4core.color("#ffffff"),
  max: am4core.color("#692155")
});
```

But it's just my opinion for better readibility and less to write :D

**Comment by martynasma** [comment]
I hear you, but multi-property heat rules are not supported :)

In order to avoid code duplication, maybe you can create a function:

```
function addHeatRule(property) {
  series.heatRules.push({
    target: columnTemplate,
    property: property,
    min: am4core.color("#ffffff"),
    max: am4core.color("#692155")
  });
}

addHeatRule("fill");
addHeatRule("stroke");
```
