### ISSUE TITLE
ngOnDestroy dispose call does not remove all listeners

### ISSUE THREAD

**Issue by xire28** [amcharts/amcharts4#18]
```
  ngOnDestroy() {
      this.chartContainer.disposeChildren();
      this.chartContainer.dispose();
  }
```
Produces the following error after having destroyed the component:
```
core.js:1601 ERROR TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at documentPointToSvg (Utils.js:811)
    at Object.documentPointToSprite (Utils.js:840)
    at XYCursor.Cursor.handleCursorMove (Cursor.js:88)
    at XYCursor.handleCursorMove (XYCursor.js:193)
    at Object.eval [as dispatch] (EventDispatcher.js:357)
    at eval (EventDispatcher.js:248)
    at Object.each [as b] (Array.js:54)
    at InteractionObjectEventDispatcher.EventDispatcher._eachListener (EventDispatcher.js:221)
    at InteractionObjectEventDispatcher.EventDispatcher.dispatchImmediately (EventDispatcher.js:246)
    at Interaction.handleTrack (Interaction.js:1204)
```

am4charts.XYCursor dispose method does not unregister the events

**Comment by arm1n** [comment]
I'm experiencing the same issue!

**Comment by martynasma** [comment]
Hey guys, can you try if [4.0.0-beta.21](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.22) fixes the issue for you?

**Comment by arm1n** [comment]
I'm already using latest beta.21, but the problem still persists. Also calling `chart.dispose()` outside of `ngOnDestroy()` leads to this error.

**Comment by martynasma** [comment]
That's weird. 21 should have fixed the dispose issue.

Will recheck and get back to you.

**Comment by martynasma** [comment]
OK, so it seems we did not bump up version number for the latest release so it did not publish to npm.

Can you try 4.0.0-beta.22 now?

**Comment by arm1n** [comment]
Thanks for the update, just tested `4.0.0.-beta.22`, but the issue persists :(

**Comment by martynasma** [comment]
Gotcha. Back to testing.

**Comment by Pauan** [comment]
Please try version `4.0.0-beta.23`

Also, you shouldn't need to use `this.chartContainer.disposeChildren()`, `dispose()` should be good enough.

**Comment by leandrodlm** [comment]
For me it seems to have something with the label bullets... commented this stuff and it stopped the problem, btw i am using 4.0.0-beta.24

**Comment by Pauan** [comment]
@leandrodlm Thanks, that helped out a lot.

I think I fixed it, please try version `4.0.0-beta.26`

**Comment by bhaskerchari** [comment]
Does calling this.chartContainer.dispose(); really remove all the events attached on the chart using different child objects, without we having to manually remove them individually?

**Comment by martynasma** [comment]
@bhaskerchari If you are trying to get rid of the chart altogether, you should call `dispose()` on the chart object. No need for `disposeChildrend()` call.

**Comment by martynasma** [comment]
Yes, it is supposed to remove everything including all DOM objects as well as listeners.

**Comment by bhaskerchari** [comment]
Thanks for confirming on the same ☺👍

**Comment by Pauan** [comment]
@bhaskerchari If you find something which *isn't* removed by `chart.dispose()`, then that's a bug and you should let us know about it, so we can fix it!

We try hard to clean up everything when `dispose()` is called, but sometimes we miss things.
