### ISSUE TITLE
How to change color of other slices on hover

### ISSUE THREAD

**Issue by cipsicko** [amcharts/amcharts4#1800]
Hi,
i need to achive the slice color changing on hover from other slice of pie / donut chart.
The hovered slice keep the same color and the other slice will be change

Adapter can be useful? i don't find nothing about it.

thanks

**Comment by martynasma** [comment]
I don't think an adapter will help. More like adding an `over` event to slices, then finding the target related slice ant setting its `isHover = true` to simulate hover on it, too.

**Comment by cipsicko** [comment]
Could you provide an example?

**Comment by martynasma** [comment]
Sure:

```
pieSeries.slices.template.events.on("over", function(ev) {
  pieSeries.slices.getIndex(3).isHover = true;
});
```

This will trigger hover on 4-th slice when hovered on any slice.

Please update accordingly to your logic.

**Comment by cipsicko** [comment]
Thanks is working for me, but default state is not trigger on over out

**Comment by martynasma** [comment]
Well, for that you would need to use `out` event to set `isHover = false`. Thought maybe it was self-evident ;)

**Comment by cipsicko** [comment]
thanks!
sorry but the doc was not so helpfull
