### ISSUE TITLE
how tooltip mouse follow

### ISSUE THREAD

**Issue by cipsicko** [amcharts/amcharts4#1801]
Hi,

is possible to change tooltip position from static to relative to mouse position?

thanks

**Comment by martynasma** [comment]
Depends on what tooltip you are talking about. Could you provide more context?

**Comment by cipsicko** [comment]
The tooltip showing on pie slice hover.
Here's a piece of my code

`var pieSeries = chartArray['donut'].series.push(new am4charts.PieSeries());
pieSeries.tooltip.pointerOrientation = "down";
pieSeries.tooltip.getFillFromObject = false;
pieSeries.tooltip.background.fill = am4core.color("#FFFFFF");
pieSeries.tooltip.autoTextColor = false;
pieSeries.tooltip.label.fill = am4core.color("#444444");
pieSeries.tooltip.background.cornerRadius = 0;` 

i need the tooltip is showing on hover (as is) and follow the mouse pointer

**Comment by martynasma** [comment]
That would be:

```
pieSeries.slices.template.tooltipPosition = "pointer";
```
