### ISSUE TITLE
Guide labels cover watermark despite the index being set lower

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1806]
I set some guides and their labels 

zIndex is set to 1

Watermark zIndex is set to 100

Labels of the Guides do overlap the Watermark creating a very ugly thingy 

<img width="311" alt="Screenshot 2019-10-27 at 11 34 01" src="https://user-images.githubusercontent.com/1268723/67633245-d6e6ee80-f8ad-11e9-94d2-701e7ab1eb02.png">

**Comment by martynasma** [comment]
What container are you adding watermark to?

**Comment by jimmykane** [comment]
```    chart.plotContainer.children.push(watermark);
    watermark.align = 'right';
    watermark.valign = 'bottom';
    watermark.fontSize = '2.1em';
    watermark.opacity = 0.8;
    watermark.marginRight = 25;
    watermark.marginBottom = 10;
    watermark.zIndex = 100;
    watermark.filters.push(this.getShadowFilter());
```

@martynasma the chart.plotcontainer. Not a big issue but just wondering
