### ISSUE TITLE
How to use the new patterns theme? 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1807]
I have updated to the latest version with the new patterns theme but when I use the theme the columns become white.

**Comment by martynasma** [comment]
Do you mean that they do not get filled with a pattern, or that they disregard fill colors?

**Comment by jimmykane** [comment]
They disregard all fill colors becoming white.

**Comment by martynasma** [comment]
Well, it has its problems. We are redoing it as we speak. Should be better in the next release.

If you could post your chart, I'd test it before release if all is good with the updated version.

**Comment by martynasma** [comment]
Hey, just released 4.7.6 which fixes up patterns theme.

And here's more info about it:
https://www.amcharts.com/docs/v4/tutorials/using-patterns-theme/
