### ISSUE TITLE
How to create category axis tooltips via property fields

### ISSUE THREAD

**Issue by andykno** [amcharts/amcharts4#1808]
I have a XYChart witch a CategoryAxis and a XYCursor.

The Axis Tooltip documentation (https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/) containes an example to set the content of the tooltip with an adapter.

How can I do it with a property field?

**Comment by martynasma** [comment]
There's no way to do that, I'm afraid.

**Comment by andykno** [comment]
We are working with serializable JSON configurations. So an adapter is not an option for us.

Is there any other way to customize the cursor tooltip of the category axis?

**Comment by martynasma** [comment]
Gotcha. It depends what you mean by "customize". Can you elaborate on that?

**Comment by andykno** [comment]
The use case is very simple. Each category has a (static) description.
e.g.
 Category => "France"
 Tooltip => "France is a country in europe"

**Comment by martynasma** [comment]
Understood. I can see how this could be useful to have. We'll need to discuss how this may be implemented.

**Comment by martynasma** [comment]
I'm afraid we won't be implementing modifying axis tooltip content via propertyFields.

Instead, please consider using an adapter:

```
categoryAxis.tooltip.label.adapter.add("text", function(text, target) {
  if (target.dataItem) {
    return target.dataItem.dataContext.axisLabel;
  }
  return text;
});
```

Example:
https://codepen.io/team/amcharts/pen/jOqNreJ
