### ISSUE TITLE
Axis range fills are circular on radial axis with gridType="polygons"

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#181]
![image](https://user-images.githubusercontent.com/1458520/43363770-d630fb70-9314-11e8-8793-9fc41809670f.png)

Example:
https://codepen.io/team/amcharts/pen/3606c9a81ec6a15a473d8bb6c1da7204/

**Comment by runfaj** [comment]
@martynasma @zeroin Ran into this as well, but that same example above appears to not affect grid lines anymore either:

![image](https://user-images.githubusercontent.com/3292053/65998884-7a80e280-e459-11e9-9492-680e977d6db5.png)

Another example based on the demos: http://jsfiddle.net/runfaj/78pqtgch/
