### ISSUE TITLE
tooltipHTML in pie charts not positioned correctly

### ISSUE THREAD

**Issue by jhadenfeldt** [amcharts/amcharts4#1811]
I am expecting the pie chart tooltip to be positioned on top of the active segment, just like the default tooltip is. Unfortunately, the custom tooltip is always centered in the middle of the chart:

https://codepen.io/jhadenfeldt/pen/wvvqpBe

The same goes for tooltipText: https://codepen.io/jhadenfeldt/pen/wvvqpKe

**Comment by martynasma** [comment]
Tooltip is centered on the object you are adding it on. In your charts you add it to series, hence it is displayed in the middle of the chart - the whole series.

If you need it centered on the slice, add it to slice template:

```
pieSeries.slices.template.tooltipHTML = "....";
```

**Comment by jhadenfeldt** [comment]
That's it, thank's so much!
