### ISSUE TITLE
How to combine tooltipText for grouping data?

### ISSUE THREAD

**Issue by AnastasiiaTsvetkova** [amcharts/amcharts4#1813]
Hi! When I grouped my data with dateAxis.groupData = true and added series .groupFields.valueY = 'average' I need show combine tooltip with new average value. How can I do this?

**Comment by martynasma** [comment]
You can use `{valueY}` in your tooltip. It will show the aggregate value.

**Comment by dharam0034** [comment]
If the grouping was based on for example 'max' then is there any way to get index/that complete element ?

**Comment by martynasma** [comment]
I'm not sure I follow.

If your group field is "max" then the value of "valueY" for grouped data item will be max value out of the values that grouped data item consists of.

**Comment by dharam0034** [comment]
OK. Thanks.

**Comment by dharam0034** [comment]
I wanted to get the dateAxis value after grouping. 

"tooltipshownat" event solves my problem to get the both Value and Date axes values (even after the grouping). I wonder that there is no detailed document about this event.

**Comment by martynasma** [comment]
I would do that via cursor's position. More details here:
https://www.amcharts.com/docs/v4/tutorials/tracking-cursors-position-via-api/#Getting_position
