### ISSUE TITLE
Export chart in png, jpg and pdf took longer and didn't work

### ISSUE THREAD

**Issue by romina-code** [amcharts/amcharts4#1815]
![Capture](https://user-images.githubusercontent.com/55830376/67783272-4e617d00-fa6a-11e9-965a-61dab62f0ea8.PNG)

**Comment by martynasma** [comment]
Does this happen on all charts? For example here:

https://www.amcharts.com/demos/exporting-chart-to-image/

Also, do you get any error in browser console?
