### ISSUE TITLE
Lines are doubled when zoomout -- amCharts4

### ISSUE THREAD

**Issue by Eguerrero86** [amcharts/amcharts4#1817]
I have problems with my graphics when I try to zoomout

Normal Graph:
![image](https://user-images.githubusercontent.com/32604694/67903126-d6ae5380-fb38-11e9-8f55-d72cd453dcd0.png)

Graph with zoom:
![image](https://user-images.githubusercontent.com/32604694/67903176-eaf25080-fb38-11e9-8cbe-0fe2d9c09444.png)

Graph when with zoomout:
![image](https://user-images.githubusercontent.com/32604694/67903228-08271f00-fb39-11e9-8d2c-16edc2659542.png)

This started to happen when I started using the propertyFields.Stroke and propertyFields.Fill in my series.
Is there any way to use the property but that this error does not happen?

Thank you.

**Comment by martynasma** [comment]
That's weird. Can you post your chart in codepen/jsfiddle so that we can test?

Also, before you invest too much time, can you check whether you are using the latest version? (4.7.6)

**Comment by Eguerrero86** [comment]
Hi, I managed to find the error.


When a point with a null value is given a colorField property, it has the effect of multiplying the lines.
See the following example and look at the data. Then zoom in on the graph and then quickly zoom out.

https://codepen.io/eguerrero86/pen/vYYWJwK

The solution was to give null color when the point value is null. As in the following example.

https://codepen.io/eguerrero86/pen/zYYPdQX?editors=0010

Thank you for your cooperation :D
