### ISSUE TITLE
Question: Set overflow on tooltip

### ISSUE THREAD

**Issue by jpirzent** [amcharts/amcharts4#1819]
Hi, I'm having an issue with the tooltips being too long in a mobile view, is there a way to set the overflow on the tooltip?

**Comment by martynasma** [comment]
You can set `maxWidth` on tooltip label, and make them wrap. E.g.:

```
series.tooltip.label.maxWidth = 150;
series.tooltip.label.wrap = true;
```

**Comment by martynasma** [comment]
Or you can omit the `maxWidth` part so it will wrap if it does not fit into chart container width.

**Comment by martynasma** [comment]
Do you mean that if tooltip would get bigger than maxHeight its contents would become scrollable?

**Comment by jpirzent** [comment]
Yea, that's exactly what I need. Is that possible?

**Comment by jpirzent** [comment]
Okay, thanks very much :+1:
