### ISSUE TITLE
Funnel Chart

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#182]
Hello,

Is funnel chart not supported in v4?

I can't find any references.

**Comment by martynasma** [comment]
Funnel is not yet supported in amCharts 4.

We plan on implementing it in coming 1-2 months.

In any case it most definitely will be implemented.

**Comment by VaishnaviAppannagari** [comment]
Thank you.
When can we expect official v4 release?

**Comment by martynasma** [comment]
Tentative release date is somewhere in September.

**Comment by zeroin** [comment]
Just wanted to let you know that funnels are now supported:
Regullar funnel chart:
https://codepen.io/team/amcharts/pen/YOMXbP

Horizontal Funnel Chat:
https://codepen.io/team/amcharts/pen/mzMRbP

Pictorial stacked chart:
https://codepen.io/team/amcharts/pen/NOvbZg

Pyramid charts are also supported.

**Comment by martynasma** [comment]
Related docs:
https://www.amcharts.com/docs/v4/chart-types/sliced-chart/
