### ISSUE TITLE
question about moving nodes in sankey chart 

### ISSUE THREAD

**Issue by shinji7800** [amcharts/amcharts4#1820]
Hello, 

it is possible to move a node in both directions (x and y), organize a node layout or change the horizontal distribution (number of columns)

because automatically layout is not optimal

like this picture below

![AMCharts_SanKey_diagram_Microsoft Edge](https://user-images.githubusercontent.com/9131657/67952491-ad9bca80-fbed-11e9-8866-c8cd79cd8101.png)

best regards

**Comment by martynasma** [comment]
I'm afraid there's currently no way to specify specific positions of the nodes. Those are determined by the order of the data and links between them.
