### ISSUE TITLE
some issues with firefox 

### ISSUE THREAD

**Issue by shinji7800** [amcharts/amcharts4#1821]
Hello, 

I don't understand I have no issues with Edge but with chrome(sometimes) and Firefox (every time) I have errors

 and have this result on my page : 
![AMCharts_SanKey_diagram_Firefox](https://user-images.githubusercontent.com/9131657/67953101-c658b000-fbee-11e9-9c16-3c3fb027c4e2.png)

RangeError: Maximum call stack size exceeded (Chrome) 
InternalError: too much recursion (Firefox)

in console log there is the message : 

`columnNumber: 55885
​
fileName: "https://www.amcharts.com/lib/4/charts.js"
​
lineNumber: 1
​
message: "too much recursion"
​
stack: "XFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55885\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\nr/<@https://www.amcharts.com/lib/4/core.js:1:623728\nWglt/e.each@https://www.amcharts.com/lib/4/core.js:1:622447\nXFs4/De</t.prototype.getNodeLevel@https://www.amcharts.com/lib/4/charts.js:1:55724\nXFs4/De</t.prototype.getNodeLevel/<@https://www.amcharts.com/lib/4/charts.js:1:55850\nWglt/e.each/<@https://www.amcharts.com/lib/4/core.js:1:622468\n"`

in edge the same page display this : 

![AMCharts_SanKey_diagram_Microsoft Edge](https://user-images.githubusercontent.com/9131657/67953073-b80a9400-fbee-11e9-8c6b-8a19aac02c9c.png)

best regards

**Comment by martynasma** [comment]
Can you post your chart on codepen/jsfiddle?

**Comment by shinji7800** [comment]
Hello, 

[CodePen](https://codepen.io/shinji7800/pen/PooOKLp)

results : 

![codepen-AMCHART](https://user-images.githubusercontent.com/9131657/67957907-96ada600-fbf6-11e9-8c87-036d88d9f37d.png)

**Comment by martynasma** [comment]
This is due to circular references. SankeyDiagram can't handle those.

I suggest naming your nodes form different levels differently, and using separate keys for labels.

Here's a simple example:
https://codepen.io/team/amcharts/pen/RwwgoQv

**Comment by shinji7800** [comment]
hello, 

thanks for your time

I follow this example on amCharts website : [Here](https://www.amcharts.com/demos/traceable-sankey-diagram/)

[CodePenFromamChart](https://codepen.io/shinji7800/pen/VwwrMRM?&editable=true
)

and this why I chose to arrange data like that. 

it is a bad example given on amChartWeb site ? or I miss something ?

thanks

**Comment by martynasma** [comment]
Both of the charts you've linked to in your last comment work fine in Firefox and other browsers because they do not have circular references, whereas the one you sent initially does, which is not supported in Sankey.

**Comment by shinji7800** [comment]
thanks I understand the reason

can you explain to me  what is a circular reference in this context ? is in data array ? I not sure what I am looking for 

best regards

**Comment by martynasma** [comment]
Circular reference is when the change of from/to links results in a loop.

E.g. A > B > C > A

**Comment by shinji7800** [comment]
Ok I believe I do understand.

I will check if there is loops 


Thanks
