### ISSUE TITLE
Dateformats with setInterval does not play well 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1824]
On an XYChart I create a date axis and load it with some data for eg 1 month per day

I set the axis intervals 

```
 axis.baseInterval = {
              'timeUnit': 'day',
              'count': 1
            };
            axis.dateFormats.setKey('day', 'dd/MM');
```

So it will display days 

Then I set as seen the day format. 

However the first value on the date axis is not formated as seen 

<img width="899" alt="Screenshot 2019-10-31 at 18 52 13" src="https://user-images.githubusercontent.com/1268723/67972904-d765e900-fc0f-11e9-8cde-cbefa42e1279.png">

**Comment by martynasma** [comment]
Time to learn about `periodChangeDateFormats` ;)

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Period_change_format
