### ISSUE TITLE
Axis Label Allignment

### ISSUE THREAD

**Issue by ctlewis** [amcharts/amcharts4#1825]
Looking at the demo site and the out of the box Date Based Chart, the X-Axis labels are halfway between two data points. Is there a way to ensure the axis labels are directly below the actual datapoint? https://www.amcharts.com/demos/date-based-data/
![image](https://user-images.githubusercontent.com/17432639/67979688-ca82ce80-fbea-11e9-9952-cdc4356d1d51.png)

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis

**Comment by ctlewis** [comment]
That is what I was trying to find, thank you!
