### ISSUE TITLE
AmCharts 4 how to make category axis display all values

### ISSUE THREAD

**Issue by ZakThompsonEchelon** [amcharts/amcharts4#1826]
What is the proper way to make amcharts 4 be forced to display all values on a category axis? 
![image](https://user-images.githubusercontent.com/20604292/67985919-e50f7480-fbf7-11e9-899c-0063f6989644.png)

In my dataset, I have some values grouped by the string representation of each month of the year.  However, on the category axis, it only displays the string value for every other month.  My end goal is to be able to get rid of the legend and have the labels solely be on the X axis, but I have not been able to figure out a way to do that.  It looks like there is ample space between each column to put each other month, so I am unsure why they are not even being included in the first place. 

I found this old case for amcharts 3, but when looking at the typescript definitions for amcharts 4, I am not seeing any options for gridCount or autoGridCount.
https://github.com/amcharts/amstock3/issues/5

Any guidance is appreciated.

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by ZakThompsonEchelon** [comment]
This solved it, thanks!
