### ISSUE TITLE
Amcharts V4 Pie Chart: Get the current clicked slice

### ISSUE THREAD

**Issue by jessemoon0** [amcharts/amcharts4#1828]
Hi, I have been stuck for 2 days now, so I would be thankful for any help:

I am trying to **get the current clicked slice in a pie chart**, in order to **get its dataSet**, in `V3` there was a `sliceClicked` event but now is only `'hit'` and I can't seem to find any property that allows me to get the just clicked slice (isActive returns as false for all slices in case u were wondering).

Here is some code I have tried so far with no success (I use it to only show 1 active slice at a time, as per documentation):

```
pieSeries.events.on('hit', (event) => {
      const series: PieSeries = event.target.dataItem.component;
      console.log('Event');
      console.log(event.target);
      console.log('Slices');
      console.log(series.slices);
      series.slices.each((slice: amCharts4Core.Slice) => {
        // console.log(slice);
        if (slice.isActive) {
          console.log('Selected');
          console.log(slice.dataItem.values.radiusValue.value);
          console.log('Slice Data Item Category');
          console.log(slice.dataItem.properties.category);
          slice.isActive = false;
        }
      });
    });
```

**BONUS HELP**: With the TS approach, do you guys know how to dynamically change the data of a chart? 

Ill deeply appreciate, thanks!

**Comment by martynasma** [comment]
Just add hit event on a slice instead:

```
pieSeries.slices.template.events.on("hit", (event) => {
  // event.target is the clicked Slice
});
```

P.S. please do not mash up several unrelated questions in a single issue. Post one separately.

**Comment by Swaraj55** [comment]
Hey, @martynasma  how disable the first "hit" click in amcharts
pieSeries.slices.template.events.on("hit", (event) => {
  event.target.url = "https://time.is/UTC";
});

when I  do first click  on slice it neither navigate but on second click it navigate. how we resolve?

**Comment by Fasih1994** [comment]
how can we do the same for Treemap?
