### ISSUE TITLE
Bullet Chart

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#183]
Hello,

I am trying to implement Bullet Chart with provided properties and classes, but I am unable to achieve proper result.

Can you provide a sample or any suggestions?

**Comment by martynasma** [comment]
Just so we're on the same page, are we talking about something like this?

https://www.amcharts.com/demos/bullet-chart/

(the above link is for a demo in previous version of amCharts - v3)

**Comment by VaishnaviAppannagari** [comment]
Yes. Just like this.

**Comment by martynasma** [comment]
OK, I put together an example here:

https://codepen.io/team/amcharts/pen/oMqvOP/

I will probably will whip up a tutorial with short explanation of what's going on in there.

Meanwhile, if  you have any questions, just ask.

**Comment by VaishnaviAppannagari** [comment]
Sure. Thank you.

**Comment by martynasma** [comment]
There ya go:
https://www.amcharts.com/docs/v4/tutorials/creating-a-bullet-chart/

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
