### ISSUE TITLE
Cannot disable the bullets disable bullets in scrollbarX scrollbarChart

### ISSUE THREAD

**Issue by dharam0034** [amcharts/amcharts4#1830]
Hi, 
I am using v4 stockchart, live data update with grouping enabled. 

Seems to be working fine, except the newly pushed bullet in scrollbarX (going out side of scrollbarX, the gray bullet above the blue one). 
How can I disable this one bullet from scrollbarX.chart (but keeping in main chart), or can I disable the all the bullets in scrollbarX.scrollbarChart. Cant figure out by myself. 
![issue](https://user-images.githubusercontent.com/11994706/68079258-db506180-fdef-11e9-95c7-f21d0583015e.PNG)

chart.scrollbarX.scrollbarChart.series.getIndex(0).bullets ...........??

Thanks in advance.

**Comment by martynasma** [comment]
I'm not sure I follow. Would you be able to post your chart online somewhere where we can test and understand your setup better?

**Comment by dharam0034** [comment]
Hi, Thanks a lot for the quick reply. 
I have modified the amchart's live data example by adding a  scrollbarX (see link). 
I am trying to keep scrollbarX's bullet inside scrollbarX or disable it. 
Below is the modified example-- (JS, last 4 lines added).

[https://codepen.io/dharam0034/pen/NWWXJdo](url)

**Comment by martynasma** [comment]
I suppose the easiest way around it is to create scrollbar and add series to it **before** creating a bullet:

```
chart.scrollbarX = new am4charts.XYChartScrollbar();
chart.scrollbarX.series.push(series);
chart.scrollbarX.unselectedOverlay.fill = am4core.color("#fff");
chart.scrollbarX.unselectedOverlay.fillOpacity = 0.9;

// bullet at the front of the line
var bullet = series.createChild(am4charts.CircleBullet);
bullet.circle.radius = 5;
bullet.fillOpacity = 1;
bullet.fill = chart.colors.getIndex(0);
bullet.isMeasured = false;
```

**Comment by dharam0034** [comment]
Hi, Thanks a bunch. It works very well :))! 

I have one more question, is there any way to fix scrollbarX's  x-axis's label's position or scrollbarX's series' y-range after creating it. For example (in attached image) -> to avoid the series and axis label overlapping with each other.

Best wishes for this great tool. 
![Capture](https://user-images.githubusercontent.com/11994706/68110084-daedbe80-fef4-11e9-8404-3eee9769eb06.PNG)

**Comment by martynasma** [comment]
Please post a separate issue for unrelated questions.
