### ISSUE TITLE
Question: how to scale enabled yAxes/Series in height when using stacked axes?

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1832]
For example 

<img width="956" alt="Screenshot 2019-11-03 at 19 18 01" src="https://user-images.githubusercontent.com/1268723/68089974-ca930080-fe6e-11e9-9cae-89f84f714e03.png">

As you can see when a series is hidden / disabled and their corresponding yAxes there is a gap in the chart. Is there any easy way or at what direction should I look at?

**Comment by zeroin** [comment]
Here is a quick demo: 
https://codepen.io/team/amcharts/pen/KKKQNKy

You need to set height of the axis with no series to 0, and disable it so that no labels would remain visible. 

We are working on a plugin which should do this automatically, it should be released during next month.

**Comment by jimmykane** [comment]
Thank you so much @zeroin . That is great news
