### ISSUE TITLE
Microsecond data differentiation issue

### ISSUE THREAD

**Issue by dharunkumar** [amcharts/amcharts4#1835]
Hi,
I'm trying to plot dates with microsecond difference against value axis data, but when there are two points lying on same line because of microsecond time difference, only one data point tooltip is being shown, here's a example https://codepen.io/dharunkumar/pen/vYYdxpM , in that the blue lines near the end has the issue I mentioned.
How to differentiate data which are differing by microseconds and not milliseconds.

**Comment by martynasma** [comment]
I'm afraid there's no way around it. The cursor will only display one tooltip per series, regardless whether there are more data points that fall into the same millisecond. Even if timestamps were ideally same down to microsecond, the cursor would still not be able to display two tooltips for the same series. Sorry.
