### ISSUE TITLE
How to manipulate the chart sprites from outside without recreating again

### ISSUE THREAD

**Issue by jamfilho** [amcharts/amcharts4#1837]
I have Map Chart with some Circles, and a Side List (a different component outside the Chart Container )  how to change the stroke of some circle (like a selection which i already have on the "hit" event) according to some object selected on that "Side List"?

Basically interaction betweens Amcharts and External Elements

**Comment by martynasma** [comment]
I suppose you could use states for that:

```
var is = imageSeries.mapImages.template.states.create("selected");
is.properties.stroke = am4core.color("red");
```

Then when you need to set state on sepcific image:

```
image.setState("selected");
```

More about states:
https://www.amcharts.com/docs/v4/concepts/states/

Hope this helps.
