### ISSUE TITLE
Showing axis line by minute, not intervals

### ISSUE THREAD

**Issue by yendai-vo** [amcharts/amcharts4#1838]
Hello there, 

I'm creating a XYSeries chart with time for the x-axis and I wanted to display a vertical line to represent the current time on my chart. I couldn't quite figure out how to draw a line on the axis, so I've resorted to having the cursor line be "sticky" for the current time, and whenever I hover over the chart, the cursor line will follow. I currently have it hard-coded to a specific area on my chart.
`chart.cursor.triggerMove({ x: 310, y: 0 }, "soft");`

Right now, the main problem I'm facing is my data values are based off of 5 minute intervals, so the cursor line will only display every 5 minute intervals. I would like it capable of displaying every minute. I tried using chart.cursor.snapToSeries, but it was to no avail. 
![image](https://user-images.githubusercontent.com/37639491/68166674-aeec3080-ff28-11e9-9770-423449c6bb54.png)

**Comment by martynasma** [comment]
You will need to manually specify data granularity for your DateAxis:

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Manually_specifying_data_granularity

**Comment by yendai-vo** [comment]
I tried `dateAxis.baseInterval = {"timeUnit": "minute", "count": 1}` and `dateAxis.baseInterval = {"timeUnit": "second", "count": 1}` to display for every minute, but that did not fix the 5 minute interval for the sticky cursor line. 

![image](https://user-images.githubusercontent.com/37639491/68223618-bc4dfd00-ffb2-11e9-90be-f554c70b0c0c.png)

It just influenced the data points rather than the line

**Comment by martynasma** [comment]
Um, I've re-read your original post and must admit I'm not entirely sure I understand the issue.

Do yo want the cursor line to snap to each individual data point, or don't? :)

If you could also post your chart as codepen/jsfiddle that would be great.

**Comment by yendai-vo** [comment]
Sorry if I'm making it sound confusing. I created a codePen if you would like to take a look at my code. 

https://codepen.io/yendai10607/pen/xxxjKBN?editors=0010

I just want to have that sticky cursor line for every minute instead of every 5 minutes.

**Comment by martynasma** [comment]
Thanks.

In that case you might disable snapping of tooltip to grid:

```
dateAxis.snapTooltip = false;
```

**Comment by yendai-vo** [comment]
That works, thank you!
