### ISSUE TITLE
How to show all labels in Category Axis?

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1839]
I was searching a way to solve this and I can find only solutions for amcharts v3 like this one:   
https://stackoverflow.com/questions/28331577/how-to-disable-auto-hiding-of-labels-on-category-axis/28338768

**Comment by martynasma** [comment]
How about this? :)

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by enriquepiatti** [comment]
Perfect, that works !
