### ISSUE TITLE
Dynamic data update Issue

### ISSUE THREAD

**Issue by dharunkumar** [amcharts/amcharts4#1840]
Hi,
I'm trying to update data dynamically based on user input and display the result, Example as in https://codepen.io/dharunkumar/pen/vYYdxpM, based on inputs from dropdown, those values will be displayed, but I'm getting error attached in this screenshot, any way to resolve this?
![error](https://user-images.githubusercontent.com/15508535/68194600-55910980-ffdb-11e9-8590-d727c98b728c.PNG)

**Comment by martynasma** [comment]
What do I need to do to trigger this error? I played around with the selector up top, but could not get the chart to error out.
