### ISSUE TITLE
auto gap in multiple date axis

### ISSUE THREAD

**Issue by nima-rnd** [amcharts/amcharts4#1841]
I'm using a chart with multiple date axis, and I want to make a gap into series, but I faced the error "Cannot read property 'getTime' of undefined." 
https://codepen.io/nimosh/pen/mddXNOa?&editable=true#anon-signup

**Comment by martynasma** [comment]
Well you do have two data sets that do not overlap, yet using those in a single chart-wide data. I don't event want to think what's going on calculating gaps in such scenario :)

Why don't you create to completely separate data arrays and assign them directly to each series?

Here's your chart redone:
https://codepen.io/team/amcharts/pen/48261c2e4e29cdf5cdc5ab4baf18c5f3?editors=0010
