### ISSUE TITLE
Tooltip position

### ISSUE THREAD

**Issue by AnastasiiaTsvetkova** [amcharts/amcharts4#1843]
Hi! Could you help me? Can we add a position for tooltip on the corner point?
For example like this. Combine horizontal and up or down position.
![image](https://user-images.githubusercontent.com/55182060/68209733-b836d500-ffdc-11e9-8467-81b9842180e7.png)

**Comment by martynasma** [comment]
Currently there's no way to force corner position for tooltip, I'm afraid.

**Comment by moghthalkushal** [comment]
https://codepen.io/moghthalkushal/pen/BaaMBap

![image](https://user-images.githubusercontent.com/5137212/69104099-fa6b1680-0ab2-11ea-9062-c872e183aac6.png)

Can we change the XY cursor and the tool tip , when the chart is rotated?

**Comment by martynasma** [comment]
@moghthalkushal Please post questions that are not directly related to original topic in a separate issue.

**Comment by martynasma** [comment]
I'm afraid we have decided not to implement this at this time. Sorry. Closing.
