### ISSUE TITLE
How to show Date Axis label in UTC?

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1845]
If I have in my data:    
data = [ { x: new Date('2019-02-01'), y: 1 } ]    
And in my axis:   
dateAxis.tooltipDateFormat = "MMM";    
Then instead of showing Feb it shows Jan because of my timezone. Is there any way to format always the date using UTC?

**Comment by martynasma** [comment]
Try this:

```
chart.dateFormatter.utc = true;
```
