### ISSUE TITLE
Large and Small values plotting on the same bargraph amcharts4

### ISSUE THREAD

**Issue by shripradashivakumar** [amcharts/amcharts4#1847]
Hi, 
I am plotting a bar chart in amcharts4 and the data set has some large values and really small values. Attaching the graph. Is there a way i can make the bars for small values visible?
<img width="550" alt="Screenshot 2019-11-06 at 11 01 56 AM" src="https://user-images.githubusercontent.com/50405790/68271015-58483900-0085-11ea-87d1-4c4ab8b35a7c.png">

**Comment by martynasma** [comment]
I suppose you can make use of "axis breaks":
https://www.amcharts.com/docs/v4/concepts/axes/#Breaks

**Comment by shripradashivakumar** [comment]
Hello, 
Sorry breaking the range isn't an option for me as i am not sure in my case what range i can remove from the axis. my data is like that. 

Is there an alternative way to solve my issue?

**Comment by martynasma** [comment]
Yes. Logarithmic scale on ValueAxis. But it won't work if there are zero values.

```
valueAxis.logarithmic = true;
```
