### ISSUE TITLE
How to position the start and end of date chart exactly at the beginning and end of chart, respectively

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1848]
I thought I was achieving this with 

dateAxis.startLocation = 0.5;
    and
dateAxis.endLocation = 0.5;

But when I zoom in really close (from right to left, leaving the scrollbarX.startGrip untouched), the space between time 0 and time 1 is waaay less than the space between time 1 and time 2, so I am assuming part of the lines are off view.

Is this a bug? Do you need an example?

**Comment by martynasma** [comment]
Yes, an example would help. Thanks.

**Comment by algebrathefish** [comment]
@martynasma in fact I don't even have to zoom, you can see here, https://codepen.io/nombreyapellido/pen/pooLKwd that the space between 0 and 1 is half the space between 1 and 2. Don't look at the points in the line but at the tooltip data

**Comment by martynasma** [comment]
Well, that's what `startLocation = 0.5` means: "start first cell at the middle", hence the smaller.

If you would rather have bullets be placed at the beginning of the cell rather than in middle, you can do this:

```
series.dataItems.template.locations.dateX = 0;
```

For that you'll probably also need to set `endLocation = 0` so there's no last empty cell.

**Comment by algebrathefish** [comment]
@martynasma I don't understand, 

There I have the lines going from end to end, but the tooltip data does not match the lines. How is that not a bug?

**Comment by algebrathefish** [comment]
Ok, @martynasma I think I got it with what you said
https://codepen.io/nombreyapellido/pen/ExxEROM

I'll let you know if I need further help, thank you
