### ISSUE TITLE
ForceDirectedTree Chart's 'collapsed' property not working

### ISSUE THREAD

**Issue by mandgenikhil** [amcharts/amcharts4#1849]
Hi Team 

I was trying to use the default collapsed dataField property of forceDirected chart, but the collapsed property does not reflect as expected. I want to have children nodes hidden by default.

I have tried using the official documentation here : -https://www.amcharts.com/docs/v4/chart-types/force-directed

Code which I have used :- 

networkSeries.dataFields.collapsed = 'true';		

Note:- I have tried with Boolean value also, but it does not work out for me.

**Comment by martynasma** [comment]
The code you posted means that the series will look for a field in data, named "true" to see if it holds boolean value `true` which would mean this node should start collapsed.

It should point to an actual field, e.g.:

```
networkSeries.dataFields.collapsed = 'collapsed';
```

Then the data could have `collapsed: true` in data for the node which needs to start collapsed.
