### ISSUE TITLE
Disable tooltip on Sankey diagram

### ISSUE THREAD

**Issue by marjukas** [amcharts/amcharts4#1851]
Hello!

We are using Sankey diagram. We would like to disable default tooltip and set static info box as described in article "Custom static multi-value tooltip".

However, we are not able to disable the Sankey diagram tooltips as described in the article. In the  article there is mentioned that tooltips won't appear if you don't add tooltipText to series, but on Sankey there seems to be no series property. If no info is given about tooltips, it displays default tooltips.

How can we disable tooltips in Sankey diagram or access them to modify them? 

Thank you!

**Comment by martynasma** [comment]
This will disable tooltips for Sankey links:

```
chart.links.template.tooltipText = "";
```

**Comment by marjukas** [comment]
Thank you! It worked well!
