### ISSUE TITLE
Synchronize y = 0 axis with multiple y axis

### ISSUE THREAD

**Issue by alessandrovir** [amcharts/amcharts4#1854]
I am trying to build an XY chart in amcharts4 that has two y axes, one on the left, the other one on the right. The two axes refer to two different variables that have different range of values. I am not able to configure the graph so that both the y axes "share" the y = 0 axis. It is useful when i want to see a part of the x axis and i am interested more on the trend of the two separate variables. I am more interested in viewing when the variables are positive or negative and the relation they have with each other (the exact value will be displayed in a tootlip). One solution could be to use a fixed scale with the bigger range between the two y axis values. But, in this case, if i have a variable that changes just a little around the 0 and the other one has bigger range, the line of the first one will be pretty flat compared to huge changes in the second.

Example: 
[Here](https://imgur.com/a/HFqsIy6)
The ligth blue refers to the y axis on the left, purple on is on the right.

What i want is a graph that has on the left the values [-2, 2], and on the right [-400, 400] so that the 0 is in the center of both y axis. What i have now is a graph in which the purple variable seems to have negative values since i read it from left to right.

One idea is to calculate manually the range of the axis in order to have as result the new interval [-400, 400] but there are two problems: - I have a great amount of data to check for the max and min values on both axis. In my case, in the graph, will be displayed about 10 variables. - I cannot generalize the calculus because the values can be of any type: only negative, only positive or both positive and negative. I think that a function that produce the desired output interval is to expensive for me.

Is there an amcharts4 method / property / etc. that allows me to do this easily?

`const data = [{"var1": 0, "var2": 400, "MyDate": 'today'}, {"var1": 0, "var2": 0, "MyDate": 'tomorrow'};`

`const chart = am4core.create(chartTitle, am4charts.XYChart);`

`chart.data = data;`

`const dateAxis = this.chart.xAxes.push(new am4charts.DateAxis());`

`const valueAxis1 = this.chart.yAxes.push(new am4charts.ValueAxis());`

`const valueAxis2 = this.chart.yAxes.push(new am4charts.ValueAxis());`

`valueAxis2.renderer.opposite = true;`

`const series = this.chart.series.push(new am4charts.LineSeries());`

`series.dataFields.valueY = "var1";`
`series.dataFields.dateX = "MyDate";`

`const series2 = this.chart.series.push(new am4charts.LineSeries());`

`series2.dataFields.valueY = "var2";`
`series2.dataFields.dateX = "MyDate";`

I opened this issue also on stackoverflow
[Here](https://stackoverflow.com/questions/58012708/amcharts4-synchronize-y-0-axis-with-multiple-y-axis)

**Comment by wmatex** [comment]
Did you figure this out @martynasma? I am facing the same issue.
