### ISSUE TITLE
Tooltip color don't inherit when setting negative color

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#1855]
Hy,
Having the pen bellow, how can I set tooltip background color to be inherited from series?

![Tooltip-color-inherit](https://user-images.githubusercontent.com/21243081/68474812-1ce96e00-022f-11ea-9b7e-771b82de4182.gif)

https://codepen.io/aniov/pen/oNNyLwg?editors=0010

Thank you.

**Comment by zeroin** [comment]
This can be done with some hack:
https://codepen.io/team/amcharts/pen/51e4eaf6756e57430c7cbe9a9d861884?&editable=true

These lines does it:
`series.tooltip.getFillFromObject = false;
series.tooltip.adapter.add("x", (x, target)=>{
    if(series.tooltip.tooltipDataItem.valueY < 0){
        series.tooltip.background.fill = chart.colors.getIndex(4);
    }
    else{
        series.tooltip.background.fill = chart.colors.getIndex(0);
    }
    return x;
})`

Unfortunately we can not do that automatically as ranges can overlap and some other reasons.

**Comment by zeroin** [comment]
Another alternative would be to add invisible bullets with color adapter and set tooltipText to the bullet. But it's not very good for performance, if you have a lot of data: https://www.amcharts.com/demos/smoothed-line-chart/

**Comment by aniov** [comment]
Thanks for the answer.
I used first solution (I have to much data to add bullets).

Thank you,
