### ISSUE TITLE
Hidden state of a series is not correct on events like hidden or shown. 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1856]
When a series is shown or hidden I listen on those events for example : 

```
    series.events.on('hidden', async () => {
      console.log(series.name + ' hidden state: ' + series.hidden)
```

When I programmatically hide a series like this: 

`series.hidden = true` that event fires and the state of serries hidden is read correct. 

However, when a label item is pressed the same event fires up but with a different state for `hidden` of the series. 

So when I click the legend label and hide a series the hidden event fires and this is the output of the above: 

```
Battery Current hidden state: false
```

**Comment by jimmykane** [comment]
To report the .visible property has the correct state. 

So I am confused. 

Programmatically setting the visibility (`.visible`) of a series has no effect. 
Setting the `.hidden` has effect but the event from a label no ....

**Comment by martynasma** [comment]
I would probably use `visibilitychanged` event and `visible` property:

```
series.events.on('visibilitychanged', async (ev) => {
  console.log(ev.target.name + ' hidden state: ' + ev.target.visible)
});
```

I would also use `hide()` method of the series to hide it, instead of setting `hidden` property.

This should produce constant behavior when toggling via legend and API.

**Comment by jimmykane** [comment]
Using the hide() produces unexpected results unfortunately and very much
flickering in the flow. I kinda solve this by changing the hidden property
on the events shown or hidden hook.

**Comment by martynasma** [comment]
You seem to be doing something super clever :)

Not sure why `hide()` would produce flickering, though. It's what Legend does to a series when you click on its marker.

**Comment by jimmykane** [comment]
I think what hide is doing is:

I create a chart.

I want to attach series with a state of hidden not shown

If I attach them and then hide them , then it flickers.

I will experiment a bit with this and come back to you.

**Comment by martynasma** [comment]
Chart updates/build is completely asynchronous. If your create series and call `hide()` on it immediately then it should start as hidden and not flicker at all.

But let's see what your experiments come up with :)
