### ISSUE TITLE
Series don't respect hidden attribute when add new serie to chart

### ISSUE THREAD

**Issue by joseooortega** [amcharts/amcharts4#1857]
Hello there,

### Explanation:

I’m managing a LineSeries chart and I need to print multiple series and have control on them.

I have separate filters where I control the click event over them and I’m showing or hiding series depending on the case. (serie.show(), serie.hide())

When I click in one filter to add a “new” serie (the chart doesn’t have the data of this serial yet) I update the chart data including this serial data.

And here’s the problem: when I do it, all the serials that were hidden appears again.

### Code:

I think that the way I use to save the serials may influence that behavior.. When I create new serial I save it to an object with all the serials of chart.

```javascript
this.createAxisAndSeries = function (fieldY, fieldX, name, opposite, bullet) {
    this.series[fieldY] = this.chart.series.push(new am4charts.LineSeries())
    this.series[fieldY].sequencedInterpolation = true
    this.series[fieldY].interpolationDuration = 1000
    this.series[fieldY].dataFields.valueY = fieldY
    this.series[fieldY].dataFields.dateX = fieldX
    this.series[fieldY].strokeWidth = 2
    this.series[fieldY].yAxis = this.valueAxis
    this.series[fieldY].name = name
    this.series[fieldY].tooltipText = '{name}: [bold]{valueY}[/]'

    var interfaceColors = new am4core.InterfaceColorSet()

    switch (bullet) {
      case 'triangle':
        var bullet = this.series[fieldY].bullets.push(new am4charts.Bullet())
        bullet.width = 12
        bullet.height = 12
        bullet.horizontalCenter = 'middle'
        bullet.verticalCenter = 'middle'

        var triangle = bullet.createChild(am4core.Triangle)
        triangle.stroke = interfaceColors.getFor('background')
        triangle.strokeWidth = 2
        triangle.direction = 'top'
        triangle.width = 12
        triangle.height = 12
        break
      case 'rectangle':
        var bullet = this.series[fieldY].bullets.push(new am4charts.Bullet())
        bullet.width = 10
        bullet.height = 10
        bullet.isDynamic = true
        bullet.horizontalCenter = 'middle'
        bullet.verticalCenter = 'middle'

        var rectangle = bullet.createChild(am4core.Rectangle)
        rectangle.stroke = interfaceColors.getFor('background')
        rectangle.strokeWidth = 2
        rectangle.width = 10
        rectangle.height = 10
        break
      default:
        var bullet = this.series[fieldY].bullets.push(new am4charts.CircleBullet())
        bullet.circle.stroke = interfaceColors.getFor('background')
        bullet.isDynamic = true
        // bullet.align = 'left'
        bullet.circle.strokeWidth = 2
        break
    }

    this.valueAxis.renderer.line.strokeOpacity = 1
    this.valueAxis.renderer.line.strokeWidth = 2
    this.valueAxis.renderer.line.stroke = am4core.color('#333333')
    this.valueAxis.renderer.labels.template.fill = am4core.color('#333333')
    this.valueAxis.renderer.opposite = opposite
    this.valueAxis.renderer.grid.template.disabled = true

    if (this.scrollBar == 1)
      this.chart.scrollbarX.series.push(this.series[fieldY])
  }
```

I tried to apply the function .show() and .hide() in a saved serial in individual variable and the problem disappear. But I need to save them as I do because maybe I’ll have dynamic serials from now on.

```javascript

/*----------------------------
	Activamos o creamos los series pertinentes
----------------------------*/
for (var idPais in that.valuesByDefault) {
	if (that.series.hasOwnProperty(idPais)) {
		if (that.series[idPais].isHiding || that.series[idPais].isHidden) {
			that.series[idPais].show()
			// That will show all hidden series
	} else {
		that.createAxisAndSeries(idPais, that.fieldX, that.valuesByDefault[idPais], false, "circle")
	}
}

/*----------------------------
	Ocultamos los series que tocan
----------------------------*/
for (var idPais in that.series) {
	if (!that.valuesByDefault.hasOwnProperty(idPais)) {
		that.series[idPais].hide()
	}
}
```

### Codepen

https://codepen.io/jortega_db/pen/ExxpmJE?editors=0010

### Thanks in advance

------------------------------------------------------------

Possible issue related: #1856

**Comment by martynasma** [comment]
Toggling series via `hide()` and `show()` is the correct way to do it via API.

It should also retain its status across data updates.

Can you post your whole chart on codepen/jsfiddle?

**Comment by joseooortega** [comment]
Thank you for you quick response!

Here you have a codepen: https://codepen.io/jortega_db/pen/ExxpmJE?editors=0010

To see the bug:

1. Click on this filter: Turkey
2. Click on it again to hide the serie
3. Click on the last filter: GDP Developed

You will see that the series Turkey has shown without circles.

Thanks!

**Comment by jimmykane** [comment]
@martynasma  I am having the same issue. 

Basicaly I prehide a series with `hide()` as we talked in the referenced issue. 
The moment I add a new series that series as also show. 

IF all the series are added and then the state is changed via `hide()` then all works fine.

**Comment by jimmykane** [comment]
I solved this via `    series.showOnInit = false;
`

**Comment by joseooortega** [comment]
Do you put `series.showOnInit = false;` when creating the series or when `series.hide()` ?

If you could put an easy example it would help me a lot. I tried this two ways, putting it when creating series and when I hide them but it still doesn't work :(

**Comment by jimmykane** [comment]
When creating. But not sure, can be a side effect based on my logic

**Comment by joseooortega** [comment]
At the moment of create series, if I save one series in one single variable instead of an object the `.show()` and `.hide()` work fine on it but as I coded don't.
