### ISSUE TITLE
Series.minBulletDistance seems to be all-or-nothing, rather than based in individual bullet distance.

### ISSUE THREAD

**Issue by lpuccio** [amcharts/amcharts4#1859]
https://codepen.io/larry-puccio/pen/PooaJwg

minBulletDistance seems to show or hide all the bullets in a series at once, rather than having them pop in individually as they zoom. 

To illustrate, in the code pen I've provided, minBulletDistance is set to 15 and the bullets are hidden even though the data on the left side of the date axis is monthly data rather than daily data and they are well over 15 pixels away from each other. If you set the minBulletDistance to 10, all of the bullets appear.  

I need to show monthly data when zoomed out and daily data when zoomed in, and I thought minBulletDistnce was the way to do that. Is this a bug? Or am I missing something?

**Comment by martynasma** [comment]
This is by design. This feature is meant to disable bullets if data items are closer than X pixels. Regardless of data granularity itself.

**Comment by lpuccio** [comment]
You may wish to make that clearer in the documentation. From the page on the series class: 

"Minimal distance between two adjacent bullets in pixels.
If bullet is closer, it will be **skipped** and not shown.
This allows to avoid crammed up graphs wil a lot of bullets"

"Skipped" here seems to indicate that it's handled on an individual basis, no for the whole series.

**Comment by martynasma** [comment]
Duly noted. Totally agree that description is a bit misleading. Thanks!
