### ISSUE TITLE
Is there any way to render Axis inside Axis Ranges?

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#186]
https://www.amcharts.com/demos/animated-gauge/

I am trying to achieve something similar to the above referred gauge chart where I need to render the axis inside.

I am now using axis ranges as a substitute for bands.
But there is no property mentioned which enables to render ranges outside or axis inside.

**Comment by martynasma** [comment]
You're right. There's currently no way to make axis ranges to be drawn outside of the axis itself.

I'm going to set this issue up as feature request.

Meanwhile, here's a workaround involving two axes:

https://codepen.io/team/amcharts/pen/vadJpJ?editors=0010

**Comment by VaishnaviAppannagari** [comment]
Thank you. Its working!
