### ISSUE TITLE
Can you remove the last point in a date series?

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1860]
I am going through the docs https://www.amcharts.com/docs/v4/concepts/data/, it says how to remove points at the beginning of the series, or how to replace points, I can't see reference on how to remove the last point. 
Thank you

**Comment by martynasma** [comment]
There's currently no way to remove data points from the end of the data set, save for removing them from the `data` array itself, then ivalidating the whole data by calling `invalidateData()`.

We currently do not have plans on implementing "incremental" data removal from the end of the data set.

There's one to remove data items from the beginning only: [`removeData(count)`](https://www.amcharts.com/docs/v4/reference/xychart/#removeData_method).

**Comment by algebrathefish** [comment]
Ok, thank you

Invalidate raw data does not seem to be working thought, this is a sample fiddle when i pop from the current data, i do other stuff too, not only pop, but it is just an example http://jsfiddle.net/02yaszhk/1/

**Comment by martynasma** [comment]
You sure it does not work? Your fiddle is removing data points from the end of the dataset for me.

**Comment by algebrathefish** [comment]
@martynasma it does , but the chart gets redrawn

**Comment by martynasma** [comment]
Yes. Because "incremental removal of last data points" is not supported, as I noted one of my previous comments ;)
