### ISSUE TITLE
ForcedirectedNode - add a child

### ISSUE THREAD

**Issue by jMoulis** [amcharts/amcharts4#1861]
Hello, I’m using amcharts with React.  The data that I pass to the charts are initially sent from the backend. Then the user is able to add nodes, some with simple link and others as direct child. The pb is on the second case, to do so I have to modify the data object and then the node as to fully refresh to add the node. Would it be possible to add a node to the children array and just use createNode with oit refreshing the whole graph ? Or a way to keep Track of the nodes who Were Expanded and reExpanded them after refreshing?
Best regards

**Comment by martynasma** [comment]
Currently there's no way to add data incrementally on ForceDirectedTree. Sorry.
