### ISSUE TITLE
Preloader not displaying

### ISSUE THREAD

**Issue by rbruhn** [amcharts/amcharts4#1863]
Been trying to figure out why the preloader doesn't show on my charts. I'm loading the charts dynamically using a url for the DataSource (loads series and data json) and a json config file.

The charts load when I click buttons for certain years. Each button creating the url to load. They charts work fine, just never show any preloader.

config:
```
{
  "xAxes": [{
    "type": "DateAxis",
    "renderer": {
      "minGridDistance": 50
    },
    "startLocation": 0.5,
    "endLocation": 0.5,
    "baseInterval": {
      "timeUnit": "day",
      "count": 1
    },
    "tooltip": {
      "exportable": false,
      "background": {
        "fill": "#07BEB8",
        "strokeWidth": 0
      },
      "dy": 5
    }
  }],
  "yAxes": [{
    "type": "ValueAxis",
    "tooltip": {
      "disabled": true
    },
    "calculateTotals": true
  }],
  "cursor": {
    "type": "XYCursor",
    "lineX": {
      "stroke": "#8F3985",
      "strokeWidth": 4,
      "strokeOpacity": 1,
      "strokeDasharray": ""
    },
    "lineY": {
      "disabled": true
    }
  },
  "scrollbarX": {
    "type": "Scrollbar",
    "exportable": false
  },
  "legend": {
    "labels": {
      "maxWidth": 450,
      "truncate": true
    },
    "itemContainers": {
      "tooltipText": "{name}"
    }
  },
  "dateFormatter": {
    "inputDateFormat": "yyyy-MM-dd"
  },
  "series": "",
  "data": ""
}
```

script:
```
         function loadChart(url) {
            let ds = new am4core.DataSource();
            ds.url = url;
            ds.events.on("done", function (ev) {
                buildChart(ev.data.config);
            });
            ds.load();
        }

        function buildChart(config) {
            transcripts = am4core.createFromConfig(config, "transcriptTest", am4charts.XYChart);
            let cellSize = 1.5;
            transcripts.events.on("datavalidated", function(ev) {
                // Get objects of interest
                let chart = ev.target;
                let categoryAxis = chart.yAxes.getIndex(0);

                // Calculate how we need to adjust chart height
                let adjustHeight = chart.data.length * cellSize - categoryAxis.pixelHeight;

                // get current chart height
                let targetHeight = chart.pixelHeight + adjustHeight;

                // Set it on chart's container
                chart.svgContainer.htmlElement.style.height = targetHeight + "px";
            });
        }
```

**Comment by martynasma** [comment]
If your data loads very fast you might not see the preloader appear. Especially if you are using animated theme which adds two-second fade in for preloader. This is to avoid preloader flashing quickly.

If you are indeed using animated theme you can disable this:

```
chart.preloader.hiddenState.transitionDuration = 0;
```

**Comment by rbruhn** [comment]
The data loading does happen fairly quickly during the call to the url. But when actually building the chart, and it's blank for a bit, I would think something would show. I built a test example at the following URL, along with some console output for when events are being fired.

https://dev.biospex.org/projects/13/test

**Comment by martynasma** [comment]
Not sure if it's just me or there's only a fraction of second between the "loading started" notice in console and the chart actually appearing on screen.

There's a fair amount of chart container being empty, but most of it happens before loading of the data has started.

**Comment by rbruhn** [comment]
I guess that's the question then. Is the preloader only for when it's loading data via the url? Or should it also show while the data is being parsed and the chart created?
If only the former, then I will have to create modal to show it's processing.

**Comment by martynasma** [comment]
Technically, it's for any operation that is taking longer than 50-100ms.

**Comment by rbruhn** [comment]
Alright. Then I guess it's broken as it's not showing. I even tried your suggestion above. I will just have to build my own.

**Comment by Legends** [comment]
Same in my case, when I trigger create chart (small amount of data) it takes about 1s on my local machine.
So what's the way to go here? Custom loading indicator?

I've also tried `chart.preloader.hiddenState.transitionDuration = 0;` with no success (BubbleChart)

**Comment by martynasma** [comment]
From chart's perspective, loading external data and validating loaded data are two distinctive operations. So if any of those take less than preloader timeout, it does not appear.

I suppose you could force preloader to show by setting `chart.preloader.progress = 0.5`.

Or, use custom preloader:
https://www.amcharts.com/docs/v4/tutorials/custom-loading-indicator/

**Comment by allgrowsm** [comment]
@martynasma 
Hello there,
When I reload the data via API, the preloader is not showing.

Here is how I realod the data via API.
```
  chart.dataSource.url = 'myapi';            
  chart.dataSource.load();
```

When I first load the data, preloader is showing.

Regards,
