### ISSUE TITLE
zoomOutButton icon disable cause the browser to freeze

### ISSUE THREAD

**Issue by yudarik** [amcharts/amcharts4#1864]
Hi,
I'm trying to disable the zoomOutButton icon on a gantt chart (XYChart), and set a text label instead.
I've noticed that once I'm trying to set: `chart.zoomOutButton.icon.disabled = false;`, my app became unresponsive. Examining the resources of Chrome browser with task manager, I can that the CPU of the app where my webapp is running raise to 100%.
Once I remove the property `icon.disabled` from the chart config, the app loads as usual.
While the app is compiled normally, it looks like the chart fails to render on the DOM, making the browser to enter in to some infinite-loop while trying to render the chart.

Here's my stack:
Angular 8.2.0
Node 10.0.0
NPM: 6.9.0
Chrome browser: Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by martynasma** [comment]
Can you perhaps post your chart as Codepen/jsfiddle?

I can't seem to be reproduce this. And not sure how setting `disabled = false` would cause any issues. It's not disabled by default, so it effectively does nothing.

**Comment by yudarik** [comment]
I'm trying to prepare an angular8 jsFiddle example with amcharts, but so far without a success.
I guess this can be reproduced only with Angular, since I'm not able to reproduce it with Typescript/ES6 only, as well.
