### ISSUE TITLE
About the links on a force-directed tree

### ISSUE THREAD

**Issue by JFLopez7** [amcharts/amcharts4#1865]
Hi,

I'm doing some test with the force-directed tree from amcharts4 and so far is doing what I expected, however I can't change the width of the links between 2 nodes of the same heriarchy, 

Lets say that I need to change the width of the link between 3 father notes: A, B and C, and I need to set the width of the link between A and B different from the width of the link betweent A and C or B and C.

I've read the docs but there is no description or explanation for this specific issue.

Is there a way to do this with some kind of utility from the library? and if there is a way I hope that you guys can help me with some type of explanation.

**Comment by martynasma** [comment]
We've just posted a relevant tutorial here:
https://www.amcharts.com/docs/v4/tutorials/variable-link-widths-in-forcedirectedtree/

Hope you find it useful.

**Comment by JFLopez7** [comment]
Thank you very much!!! I think that with the last example on the tutorial, I'll be able to do what I asked.

I have a quick question... can I create unique popups for every single link of the force-directed tree?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by JFLopez7** [comment]
Will do! and again, thank you very much for the help
