### ISSUE TITLE
Invalidate raw data not working?

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1866]
Hi again, I updated one of your fiddles to show the problem-

http://jsfiddle.net/bos9j8rc/1/

Instead of adding a new point as your live example did, I am cloning the data array and assigning it again to the chart, using chart.invalidateRawData()

and here using pop

http://jsfiddle.net/02yaszhk/1/

I looks like the initial animation is playing again.

Can you please tell me what I am doing wrong? Thank you

**Comment by martynasma** [comment]
`invalidateRawData()` is about updating numeric values for existing data. If you are cloning data and setting it as a new data, those are considered completely new data points, resulting in them animating again.

**Comment by algebrathefish** [comment]
@martynasma here I am only replacing the last value, without cloning http://jsfiddle.net/nsjdq39v/1/

and here, only popping from chart.data http://jsfiddle.net/28ezbw3s/1/

In both cases the data gets redrawn (i.e., there is a jump)

**Comment by martynasma** [comment]
In both fiddles you're doing `invalidateData()` (not `invalidateRawData()`)

**Comment by algebrathefish** [comment]
Ohhhh you are right.
Closing now, thanks sorry for the trouble
