### ISSUE TITLE
cursor.interactions.hitOptions.hitTolerance seems to be broken

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1867]
`cursor.interactions.hitOptions.hitTolerance ` and not matter what I set it to, when the cursor behaviour is **selecting** it will always trigger `selectended` that I think it shouldn't or wasn't like so in the past I think.

**Comment by martynasma** [comment]
`hitTolerance` is not considered when behavior is `"select*"`. It's by design.

We use `hitTolerance` only when behavior is zoom to prevent accidental overzooms when user just clicks on the chart.

Since selecting is not as potentially destructive as overzoom, I think it makes sense to leave this as it is. You may implement some fuzzy logic on your app's end to decide whether to "react" to small selections or not.

Does that make sense?

**Comment by jimmykane** [comment]
Yes it does a lot

**Comment by jimmykane** [comment]
I checked the event `selectended ` but the range does not change. 

So eg: `selectended ` on an area of 100px give some ranges over x,y

Just clicking on the map (with no area selected) the `selectended ` for the ranges has the previous ranges. 

So its a bit difficult to termine if the user selected or no. 

the most problematic is that `selectended ` triggers on top of other events eg button 'hits'

**Comment by martynasma** [comment]
Do you mean that cursor's `xRange` shows previous selection values when you click on a chart?

**Comment by jimmykane** [comment]
yes I can show with a video what I mean

**Comment by jimmykane** [comment]
That happens only when clicking not selecting. Still triggers the
selectended.

Get my point here?

So selected with drag and select reports correct range, clicking on the
chart , selectended shows the previous range

**Comment by martynasma** [comment]
Gotcha. We might need to look into it if maybe it would make sense to not invoke this event if the selection did not move during mousedown.

**Comment by martynasma** [comment]
Hey, just released 4.7.9.

It will now correctly reset `xRange` and `yRange` for the cursor if last select did not exceed `hitTolerance` setting.

Will still invoke `selectended` event, though. But now you can easily distinguish non-select events because ranges are `undefined` on click.

**Comment by jimmykane** [comment]
Yes that is correct ! 

Thank you very much !
