### ISSUE TITLE
PieSeries Label Background Round Corners

### ISSUE THREAD

**Issue by Infineon12** [amcharts/amcharts4#1868]
Hello all,

i tried all things i could find but i seem to not be able to create a rounded border on pie labels background.

Example:
https://codepen.io/Infineon12/pen/ExxRZyr

Is there any option i am missing out?
As far as i see the background is a "Rectangle" instead of a "RoundedRectanble".

Greetings

**Comment by martynasma** [comment]
Yup, your observation is correct. `Label` has a `Rectangle` for its background.

You can just replace it with a new instance of `RoundedRectangle`:

```
series.labels.template.background = new am4core.RoundedRectangle();
series.labels.template.background.fill = "#333";
series.labels.template.background.fillOpacity = 1;
series.labels.template.background.strokeWidth = 0;
```

**Comment by Infineon12** [comment]
Many thanks for the help!
