### ISSUE TITLE
Multiple bullets for Line Series

### ISSUE THREAD

**Issue by dharunkumar** [amcharts/amcharts4#1871]
Is it possible to have multiple bullet types for a single LineSeries item, for Ex: I would like to have triangle, circle and rectangle based on field in data and set it using series.propertyFields, I have seen options to change radius, color, but how to create bullets dynamically and set it using propertyFields?

**Comment by zeroin** [comment]
There are several options:

1) add ImageBullet to your series, define `bullet.propertyFields.href = "hrefField"` and then have paths to svg files in your data.
2) add simple Bullet to your series, define `bullet.propertyFields.path="pathField"` and then add svg path strings to your data.
3) add a separate bullet to your series with the shapes you need, then set bullet.disabled = true and then  add `bullet.propertyFields.disabled="disabledField1"` etc and only set value of the field to `false` for the data items which must be visible.

**Comment by dharunkumar** [comment]
Is it possible to have different bullet types in same LineSeries as in this demo https://codepen.io/team/amcharts/pen/ajPdwB , only difference is this demo has triangles, but I would like to have inbuilt shapes like triangles, circles, rectangles in a single series. So how to initialize bullet class using propertyFields from data similar to bullet.propertyFields.disabled="disabledField1"

**Comment by martynasma** [comment]
You could do something like this:
https://www.amcharts.com/docs/v4/concepts/bullets/#Individual_images_for_data_items

**Comment by dharunkumar** [comment]
Thanks for the quick response.
