### ISSUE TITLE
Set Bullet Position Based on Series and Not Axis

### ISSUE THREAD

**Issue by rc6886** [amcharts/amcharts4#1872]
![Screen Shot 2019-11-11 at 11 12 38 AM](https://user-images.githubusercontent.com/6307249/68606530-434c1b00-0474-11ea-8ab4-658736e73876.png)

https://stackblitz.com/edit/angular-j1euc9?file=src%2Fapp%2Fapp.component.ts

I'm trying making a chart that represents sale information for a particular store. The chart will display information based on the date sold, number of contracts sold, number of contracts cancelled, and the net difference between the two.

I've gotten everything working except the net difference. I'm trying to place a bullet on each series that will plot the net contracts sold for a particular store in that date range. Only instead of placing the bullet on the column series it's associated with, it's positioning it based on the axis. Those yellow bullets should be place in the middle of the light blue bars, and not the middle of the x-axis.

Is there anywhere to position the bullet so that it's in the middle of the column series it's tied to and not the x-axis itself?

**Comment by zeroin** [comment]
Hi,

I don't see bullets in your demo, but if I try the described scenario, the bullets are placed above the columns. If you could make modifications to this demo so that it would show your case, it would help to find a problem:

https://codepen.io/team/amcharts/pen/8e3fd36f9579a367b1bca4b38ca82688

**Comment by rc6886** [comment]
I'm so sorry! Looks like I edited it by mistake.

I setup a separate link with the original work I was doing that you can view here:

https://stackblitz.com/edit/amcharts-bullets

**Comment by zeroin** [comment]
So you are adding bullets to a serpate LineSeries, not column series. In this case the bullet will be positioned at the center as it does not know anything about the columns. To modify bullet position you must modify the location of your series data item, like:

`series.dataItems.template.locations.categoryX = 0.25;`

Where 0.25 is the relative position (0-1) in the cell.

**Comment by rc6886** [comment]
That did it!

Thanks for the help, I really appreciate it!

**Comment by martynasma** [comment]
For anyone looking, here's more info about data item `locations`:
https://www.amcharts.com/docs/v4/concepts/series/#Data_item_locations
