### ISSUE TITLE
TriggerMove: using longtime instead of x-coordinates for XY charts

### ISSUE THREAD

**Issue by yendai-vo** [amcharts/amcharts4#1873]
Hi, I wanted add a line in my chart that represents a specific time on the chart. I decided to use the the triggermove method from cursor to set it. I know I can set an x-coordinate in and get the line to stay at that point in time. But I have a currentTime function written and it will be returning a longtime. I there a way for triggerMove to accept a longtime instead of x-coordinate? Attached is my codePen. I made a comment for the longtime in my getCurrentTime function. 

https://codepen.io/yendai10607/pen/xxxjKBN

**Comment by yendai-vo** [comment]
So far, I've tried using dateAxis.dateToPosition(), dateAxis.valuetoPosition(), and dateAxis.anyToPoint(). No matter what position I pass into dateToPosition, it always returns 0.

**Comment by martynasma** [comment]
Three things:

1) You should use `DateAxis` method `dateToPoint()` as it converts date to a specific point you can use with cursor's `tiggerMove()`.

2) The value you pass into `dateToPoint()` needs to be a `Date` object, so you need to convert your timestamp.

3) This needs to happen when chart has already parsed data, and therefore knows the range of the DateAxis. You can use chart's "ready" event to be on the safe side.

```
function getCurrentTime() {
  /*returning a longtime*/
  return 1569918000000;
}

chart.events.on("ready", function(ev) {
  var point = dateAxis.dateToPoint(new Date(getCurrentTime()))
  chart.cursor.triggerMove({ x: point.x, y: 0 }, "soft");
});
```

**Comment by martynasma** [comment]
BTW, if you want to indicate specific time on your chart with a line, wouldn't it be better to use an axis range to place one, and not use chart cursor for it?

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides

**Comment by yendai-vo** [comment]
Thank you, I took your advice and used the axis range instead. It looks and works better that way!
