### ISSUE TITLE
Unable to align bullets to the right on a gantt (XYChart) with version 4.7.5

### ISSUE THREAD

**Issue by yudarik** [amcharts/amcharts4#1875]
I've upgraded Amcharts4 to the latest version (4.7.8) and noticed the the bullets on my Gantt chart became centered instead of aligned to the right as they should and like it was with version 4.5.15

Version 4.5.15:
![Screen Shot 2019-11-12 at 9 53 28](https://user-images.githubusercontent.com/4311544/68653489-8b327700-0534-11ea-8b0c-c14eb53737d3.png)

version 4.7.8:
![Screen Shot 2019-11-12 at 10 11 28](https://user-images.githubusercontent.com/4311544/68653702-f1b79500-0534-11ea-9180-6e270eadd5fa.png)

Here's the code used to add the bullets to the series:

> const bullets: am4core.Image = series.bullets.push(new am4charts.Bullet()).createChild(am4core.Image);
bullets.propertyFields.href = 'bullet';
bullets.propertyFields.width = 'bulletSize';
bullets.propertyFields.height = 'bulletSize';
bullets.horizontalCenter = 'right';
bullets.verticalCenter = 'middle';
bullets.dx = -15;
bullets.opacity = 0.9;
bullets.validatePosition();

I've even tried to add bullets.align = 'right' but it does not help.  The bullets are stay on their centered place. 

Here's a link to a [working example](https://codepen.io/yudarikode/pen/pooOzQb)

**Comment by zeroin** [comment]
There were indeed some changes with bullets in recent versions. To set a bullet position in this case, use:
```
bullets.locationX = 0; //right
bullets.locationX = 1; // left
```

**Comment by yudarik** [comment]
Thanks, that works for me.
