### ISSUE TITLE
Unable to set minimum pixel height for vertical ColumnSeries

### ISSUE THREAD

**Issue by rafehi** [amcharts/amcharts4#1877]
**Problem**
I'm unable to set a minimum pixel height for column series. 

I've tried the following:
* setting `series.column.template.minHeight`. This has no effect
* creating adapter for `minHeight`. This never seems to be called
* creating adapter for `pixelHeight`. This allows me to change the height of the bar, but it changes it wrt to the top, not the bottom. See image below.

![image](https://user-images.githubusercontent.com/3108685/68729941-6cf57580-061f-11ea-859f-c8aa936cd783.png)

**Expected Behaviour**
Identical to [chartjs's `minBarLength` functionality](https://www.chartjs.org/docs/latest/charts/bar.html#dataset-configuration). We are using `ColumnSeries` with a `DateAxis`, and would like 0 and near 0 values to be displayed with a min pixel height.

**Comment by martynasma** [comment]
Showing stuff that's bigger than its value accounts for is not a very good dataviz practice.

If you're worries about items not appearing for zero values at all, you may work around it by putting a `stroke` around your columns.

**Comment by rafehi** [comment]
I agree that it's not good practice in general. The problem that we're trying to solve is that the data is intermittent, and we need a distinction b/w no datapoint and a datapoint with 0 value. For clarity, we're plotting vehicle velocity, and care about when the vehicle is stationary with 0 velocity, as opposed to having no data at all (which indicates a connectivity issue).

Looks I can achieve the desired effect using a 100% width `RectangularBullet` that's top aligned (as only want to increase the height, not the width, which doesn't seem doable with stroke).

**Comment by martynasma** [comment]
Gotcha. Let me know if you manage to get it to work with the bullets.

**Comment by rafehi** [comment]
Yes indeed. Here's how I did it:

```javascript
let columnTemplate = series.columns.template;
columnTemplate.strokeWidth = 0;

// bullet / cap over data
let bullet = columnTemplate.createChild(am4core.Rectangle); 

bullet.locationY = 0.5;
bullet.align = "center";
bullet.valign = "top";
bullet.fill = am4core.color("#26C6DA");
bullet.fillOpacity = 1;
bullet.width = am4core.percent(100); 
bullet.height = 3;
bullet.strokeWidth = 0;
bullet.dy = -2;
```
I'm currently evaluating amcharts, here's a jsfiddle I've got going showing bullets (+ some other functionality we require). There is a learning curve and it does things differently to other js charting libraries I've used, but on the whole I think it's brilliant. 

https://jsfiddle.net/awraf/6ust9f5w/41/
