### ISSUE TITLE
ScrollBar with custom data

### ISSUE THREAD

**Issue by dharunkumar** [amcharts/amcharts4#1878]
Hello,
Is it possible to have scrollbar with larger data than series data, Ex: My use case is to show only 1000 frames in chart, but actual data will have thousands of data, so dumping them into chart will make it clumsy and slow, so the idea is to show only 1000 frames in chart and show a preview of entire data in ScrollBar. Is this possible?

**Comment by martynasma** [comment]
I don't think it's a good idea of desyncinc scrollbar and chart like that, even if it were possible.

How about data item grouping instead? You can have charts with hundreds of thousands of data items with it.

More details here:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping

**Comment by dharunkumar** [comment]
This grouping is possible only for dateAxis types right?I guess I will not be able to use it because of this limitation https://github.com/amcharts/amcharts4/issues/1835

**Comment by martynasma** [comment]
That is correct.

What is your setup?

**Comment by dharunkumar** [comment]
Hi,
I have to display thousands of data points to user, but I will load only around 1000 data points into chart. This data may contain some specific fields which I need to highlight to the user by changing bullet color to red. These fields may be present in any of the frames, so I need to show a preview to the user where this kind of data has occurred without actually loading the entire data. This is the scenario, any ideas or suggestions on how to achieve the same?

**Comment by martynasma** [comment]
OK, but what is the data for? I mention you want to highlight specific places in data, which indicates you have some linear data. If it's not a time scale, maybe it can be emulated with time scale, e.g. pretending that each "frame" is a "millisecond" for example.

I'm just trying to pitch this idea of using `DateAxis` because it supports dynamic data grouping out of the box.

Any other solution would involve custom setups to some extent.

**Comment by dharunkumar** [comment]
I cannot use dateAxis as my Yaxis is Category Axis and this data represents some logs which are varying by microseconds.

**Comment by martynasma** [comment]
Gotcha.

Maybe then this could work best:

1) Create separate series and separate X axis for it.
2) Set aggregated full width data for it directly on series.
3) Use that series for the scrollbar.

Does that make sense?

**Comment by dharunkumar** [comment]
So, you mean to say use a separate series for ScrollBar alone and update the chart data based on scroll events? Also in this case, should I hide the series and X axis which was created for the purpose of scrollbar?

**Comment by martynasma** [comment]
Yup. That's exactly what I meant.

I wish I had an example of something like this :/

**Comment by dharunkumar** [comment]
Hi,
I tried based on this approach, should I create a separate chart for this purpose(ScrollBar) and handle the events on this chart to zoom and pan the original chart?

**Comment by dharunkumar** [comment]
And also how to know the current values zoomed in scrollbar? Which fields should I look into and should I listen to rangechanged event?

**Comment by martynasma** [comment]
Technically, you can create series directly in scrollbar:

```
chart.scrollbarX.scrollbarChart.series.push(....);
```

> And also how to know the current values zoomed in scrollbar? Which fields should I look into and should I listen to rangechanged event?

You can use scrollbar's `start` and `end` to get selection positions, then convert those to actual dates using DateAxis' `positionToDate()` method:

https://www.amcharts.com/docs/v4/reference/dateaxis/#positionToDate_method

And yes, `rangechanged` event seems to be good candidate to track any changes.

**Comment by devendrabohre83incs** [comment]
Hello, same problem is going with my case, i am creating separating series and xases and yaxes for scrollbar, but when I scroll my scrollbar,then data filtered and chart updated with required data. after updating chart again zoom its data.

here is my code

```
componentChart.scrollbarX = new am4charts.XYChartScrollbar();
		if (_self.state.planProfilerReboot)
			componentChart.scrollbarX.scrollbarChart.xAxes.push(new am4charts.ValueAxis());
		else
			componentChart.scrollbarX.scrollbarChart.xAxes.push(new am4charts.CategoryAxis());
		componentChart.scrollbarX.scrollbarChart.yAxes.push(new am4charts.ValueAxis());
		var series = componentChart.scrollbarX.scrollbarChart.series.push(new am4charts.LineSeries());
		series.dataFields.valueY = _self.state.planProfilerReboot ? "y" : "z";
		series.dataFields[_self.state.planProfilerReboot ? "valueX" : "categoryX"] = _self.state.planProfilerReboot ? "x" : "distance";
		series.strokeOpacity = 0;
		series.hidden = true;
		series.data = cloneDeep(this.state.chartData);
		componentChart.scrollbarX.marginBottom = 20;
		componentChart.scrollbarX.scrollbarChart.plotContainer.visible = false;
		componentChart.scrollbarX.scrollbarChart.leftAxesContainer.visible = false;
		componentChart.scrollbarX.events.on("rangechanged", function (event) {
			var rangeMin = event.target.range.start;
			var rangeMax = event.target.range.end;
			clearTimeout(timer)
			timer = setTimeout(() => {
				rangeMin = Math.floor(_self.state.chartData.length * rangeMin)
				rangeMax = Math.floor(_self.state.chartData.length * rangeMax)
				_self.setState({
					start: rangeMin,
					end : rangeMax
				}, () => {
					componentChart.data = _self.getComponentChartData(cloneDeep(_self.state.chartData));
				})
			}, 1000)
		})
```
