### ISSUE TITLE
Question: Can we show guides (ranges) without a chart grid

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1879]
Hi I have followed the guide for ranges and added successfully some lines to my chart. 

But if I disable the grid renderer of the chart those ranges disappear. 

The same happens if I alter the stroke of the grid.

**Comment by zeroin** [comment]
So if you set: `range.grid.disabled = true;` it should be disabled. Range is basically an axis data item, it has a reference to gird, label etc.

You can also do it on a template:
`valueAxis.axisRanges.template.grid.strokeWidth = 10;`

This should not affect other grid items.

**Comment by jimmykane** [comment]
First I disable the chart Grid 

then I do 

`    xAxis.axisRanges.template.grid.disabled = false;
`

to bring back only the ranges
