### ISSUE TITLE
Accessing tooltip on Sankey

### ISSUE THREAD

**Issue by marjukas** [amcharts/amcharts4#1880]
Hello,

We would need to access the tooltip on Sankey diagram for features like changing the background color or setting interactionsEnable = true. 

For other chart types in tutorials it is advised to use series.tooltip to access for example getFillFromObject. On Sankey there is no series. 

How can we still change the tooltip properties?

**Comment by martynasma** [comment]
You're right - there are no series on SankeyDiagram, so chart's own `tooltip` is used:

```
chart.tooltip.getFillFromObject = false;
```

**Comment by marjukas** [comment]
Yes, this worked well! Thank you so much!
