### ISSUE TITLE
Add bullets to Pie Chart?

### ISSUE THREAD

**Issue by kencrim** [amcharts/amcharts4#1881]
Hi! I'm wondering if it's currently possible to add bullets to the slices of a pie chart. When we try adding them via the same method as other charts, they haven't shown up.

**Comment by zeroin** [comment]
It was definitely possible, I remember testing this thing when Pie chart was the only chart in V4. But it seems the feature was lost at some moment and as it's rare scenario, nobody reported the bug. I will bring it back to life in next release. 

Actually it is possible to have bullets with current version, you need to set `showOnInit = true` 
But it is still a bit buggy, as if used with legend the position of bullets is not correct.

```
let bullet = pieSeries.bullets.push(new am4charts.CircleBullet())
bullet.circle.radius = 10;
bullet.showOnInit = true;
```

**Comment by kencrim** [comment]
That worked! Thanks, I really appreciate it.
