### ISSUE TITLE
Battlefront arrows

### ISSUE THREAD

**Issue by 5pix** [amcharts/amcharts4#1882]
Hi, is there some possibilities to create from standard tools of framework' battlefront arrows? something like this
![imageArrows](https://user-images.githubusercontent.com/44845672/68894201-df597900-0737-11ea-975b-09561c64c8f6.png)
P.S.,  
Are there any plans to create offline documentation for all methods and classes of the framework (like, php documentation with a description of the methods and simple examples for them)?
Thank you!

**Comment by martynasma** [comment]
No, we don't plan on implementing something like that.
