### ISSUE TITLE
Series.connect for stepLine charts

### ISSUE THREAD

**Issue by yendai-vo** [amcharts/amcharts4#1883]
Hi there,

I have a lineSeries with a bullet point for every 5 minutes, and a stepLineSeries with bullet points every hour. I would like the series to disconnect when ever the data value is null. I used `series.connect = false` and that works well for the lineSeries. However, for the StepLine, it disconnects every single bullet point. I'm assuming it's because the gap in between each bullet point is too large. Is there a way I can fix this? Thank you.

**Comment by martynasma** [comment]
Yes, you can use `autoGapCount` for that.

Check out following description for more details:

https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Gaps_over_missing_data_points

**Comment by yendai-vo** [comment]
I've been trying to figure out the math for this because if I set `series.connect = false;` to have the gap for missing data, then the distance between the two points have to be greater than baseInterval * autoGapCount. I have `dateAxis.baseInterval = { timeUnit: "minute", count: 1 };` So for my line series I have `series.autoGapCount = 5;` and that works to provide the gap when there's missing data. Since my Step Line series is every hour, I figured `series.autoGapCount = 60;` would work, but it doesn't. The line is still drawn and connected, only the bullet point is missing.

**Comment by martynasma** [comment]
Can you post your chart and data online (codepen or jsfiddle)? I suppose it would be easier to understand your setup that way.

**Comment by yendai-vo** [comment]
https://codepen.io/yendai10607/pen/xxxjKBN

I tried doing it on my codePen, but unfortunately whenever I add in the `series.connect=false` I get an error about undefined getTime. I don't get that error from my code though. Also, in the codePen, it doesn't work for either series, however in my code it works only for line but not step line.

**Comment by martynasma** [comment]
Hm, indeed. It must be some weird bug.

Thanks for the codepen!

We'll be looking into this and will keep you posted.

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
