### ISSUE TITLE
Display stack total percent?

### ISSUE THREAD

**Issue by JorgeBlasco** [amcharts/amcharts4#1885]
Is there a way to show a stack total percent?
Let's take this example: 
https://codepen.io/team/amcharts/pen/QzRBmr?editors=0010
Subtotals are 7.7 , 8.2 , 8.8
Total is 7.7 + 8.2 + 8.8 = 24.7

The percents I am looking for are:
7.7 / 24.7 * 100 = 31.17%
8.2 / 24.7 * 100 = 33.2%
8.8 / 24.7 * 100 = 35.63%
So that:
31.17 + 33.2 + 35.63 = 100%

**Comment by martynasma** [comment]
I'm afraid there's no built-in way to do that.

All solutions would include implementing calculations. E.g.:

1) Pre-calculating percentage when data is generated, then just using it to feed the totals bullet.

2) Using an adapter for totals bullet to iterate through all data items for all series and calculating the percentage.

Hope that makes sense, as we do no't have a ready-made example, I'm afraid.

**Comment by JorgeBlasco** [comment]
Thank you for your answer! I will solve this pre-calculating percentage. Please, think about including this feature as It is very related to the _{valueX.total}_ feature shown in [Placeholders for numeric values](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Placeholders_for_numeric_values ).
I think It would be useful for other users.

**Comment by martynasma** [comment]
Duly noted. Thanks!
