### ISSUE TITLE
Changing node shape in Sankey Diagram

### ISSUE THREAD

**Issue by marjukas** [amcharts/amcharts4#1886]
Hello!

Is it possible to change the node shape in Sankey Diagram?
Right now it is rectangle but could it be triangle instead?

Like in this image:

![Shape](https://user-images.githubusercontent.com/35274613/68946934-d494f780-07bc-11ea-8fa9-85c3feeb581c.jpeg)

And can this be applied to some nodes only?

**Comment by martynasma** [comment]
Something like this?

https://codepen.io/team/amcharts/pen/BaaGWjK

**Comment by marjukas** [comment]
Hello! 
It works. Thank you!
