### ISSUE TITLE
Error generating pdf on Microsoft Edge 42.17134

### ISSUE THREAD

**Issue by arranzizquierdo** [amcharts/amcharts4#1887]
Version: 4.5.7 error when is genarating graphic pdf. The pdf don´t show colors of categories

**Comment by martynasma** [comment]
What about current version? (4.7.10)

**Comment by martynasma** [comment]
Would you be able to post the code/data for your chart so that we can test?

**Comment by arranzizquierdo** [comment]
**1) Executes the following snips in "Edge"**

  savePDF() {
    const filterDataTable = this.graphicService.dataTable;
    const legend = this.graphicService.legend;
    const translateService = this.translate;
    Promise.all([
      this.chart.exporting.pdfmake,
      this.chart.exporting.getImage('png')
    ]).then(function(res) {
      const pdfmake = res[0];
      const doc = {
        pageSize: 'A4',
        pageOrientation: 'portrait',
        pageMargins: [30, 30, 30, 30],
        content: []
      };
      doc.content.push({
        image: base64.logo,
        width: 60
      });
      doc.content.push({
        text: translateService.instant('COMMON.TEXT.GRAPHIC-REPORT'),
        alignment: 'center',
        fontSize: 20,
        bold: true,
        margin: [0, 20, 0, 15]
      });
      doc.content.push({
        image: res[1],
        width: 530
      });
      doc.content.push({
        text: translateService.instant('COMMON.TEXT.LEGEND'),
        fontSize: 16,
        bold: true,
        margin: [0, 15, 0, 10]
      });
      legend.forEach(item => {
        doc.content.push({
          color: 'black',
          markerColor: item.color,
          markerSize: 25,
          ul: [item.value]
        });
      });
      doc.content.push({
        text: translateService.instant('COMMON.TEXT.SCORE'),
        fontSize: 16,
        bold: true,
        margin: [0, 15, 0, 10]
      });
      doc.content.push({
        ol: [
          translateService.instant('COMMON.TEXT.DEFICIENT'),
          translateService.instant('COMMON.TEXT.IMPROVE'),
          translateService.instant('COMMON.TEXT.ACCEPATEBLE'),
          translateService.instant('COMMON.TEXT.EFFICIENT'),
          translateService.instant('COMMON.TEXT.EXCELLENT'),
        ]
      });
      doc.content.push({
        text: translateService.instant('COMMON.TEXT.FILTERS'),
        fontSize: 16,
        bold: true,
        margin: [0, 15, 0, 10]
      });
      filterDataTable.forEach(filter => {
        doc.content.push({
          margin: [5, 5, 5, 5],
          fontSize: 10,
          table: {
            headerRows: 1,
            body: filter
          }
        });
      });
      pdfmake.createPdf(doc).download('Report Radar Graphic.pdf');
    });
  }

 **2) It reponds (pdf attached )**
[Report Radar Graphic.pdf](https://github.com/amcharts/amcharts4/files/3858442/Report.Radar.Graphic.pdf)

**3) Repeats previous steps in "Chrome" and result (pdf attached)**
[Report Radar Graphic (1).pdf](https://github.com/amcharts/amcharts4/files/3858455/Report.Radar.Graphic.1.pdf)

**Comment by martynasma** [comment]
Thanks. Would you be able to post code for the chart itself as well?

**Comment by arranzizquierdo** [comment]
This codepen if it opens in edge the same thing happens( https://codepen.io/ArranzIzquierdo/pen/ZEEVqwd ). Maybe the problem are the ranges

**Comment by martynasma** [comment]
Thanks!

Looks like for some reason EDGE is ignoring axis range masks. I'm upgrading this to a bug. We'll be looking into it.

**Comment by martynasma** [comment]
OK, so upon further examination it's starting to look like an EDGE bug. It seems that browser is ignoring masks when using `createObjectURL()`.

Since current EDGE rendering engine is being deprecated, it's very unlikely MS will fix this, especially since in new EDGE Beta does not have this issue.

At this point I can offer to disable built-in canvas creation mechanism in favor of canvg:

```
chart.exporting.useSimplifiedExport = false;
```
