### ISSUE TITLE
External chart legend container is not disposed when disposing the chart

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1889]
Related to https://github.com/amcharts/amcharts4/issues/752 I finally manged to nail this one. 

I create a chart legend in an external container like in the tutorial 

```
    // Create a Legend
    chart.legend = new am4charts.Legend();
    chart.legend.fontSize = '1em';
    chart.legend.parent = am4core.create(this.legendDiv.nativeElement, am4core.Container);
    this.logger.info(`created laged ${chart.legend.parent.uid}`)
    chart.legend.parent.width = am4core.percent(100);
    chart.legend.parent.height = am4core.percent(100);
```

When I dispose the chart I can see a message that that elements UID is not disposed. 

I would expect disposing the chart to dispose the legend + legend right?

**Comment by martynasma** [comment]
Hm, the answer to this question is not as straightforward as it may seem.

I would tend to agree, however you would still need to dispose the `Container` you put the legend in manually. And disposing `Container` automatically disposes its children, so it kinda beats the purpose?

**Comment by jimmykane** [comment]
A little confused here. 

I tried to: 

```
return this.zone.runOutsideAngular(() => {
      if (this.chart && this.chart.legend) {
        this.chart.legend.parent.dispose();
      }
    });
```

Or 

```
```
return this.zone.runOutsideAngular(() => {
      if (this.chart && this.chart.legend) {
        this.chart.legend.dispose();
      }
    });
```

But still getting the message that the legend Container is not disposed.

**Comment by martynasma** [comment]
Have you tried disposing both the chart and the legend container?

**Comment by jimmykane** [comment]
Yes. First the container (because the chart ref is needed) and then the
chart.

Inner to outer disposal.

**Comment by jimmykane** [comment]
Also since this is open:  IF I create a legend with it's container etc and then I attach it to the cart eg: 
- Create legend set the container + setup the styles 

Then do `chart.legend = this.getLegend()` then the container element is not removed and adds there hidden am4charts stuff about licensing

**Comment by martynasma** [comment]
OK, I think this is something deeper than that.

I'm trying to reproduce this but can't. Here's what I have:
https://codepen.io/team/amcharts/pen/8dece92be7ff071542b573cee21534a1?editors=0010

Both chart and legend container get disposed, effectively clearing both <div> completely.

If you could produce some kind of working prototype for this that would make it easier.

**Comment by jimmykane** [comment]
Strange. Now `        this.chart.legend.parent.dispose();
` works !

**Comment by martynasma** [comment]
Cool. All set then? :)

**Comment by thunsaker** [comment]
@martynasma is there a chance we can get this little tidbit added to [About "Chart Not Disposed"](https://www.amcharts.com/docs/v4/tutorials/chart-was-not-disposed/). I spent a good hour trying to figure out which chart wasn't being disposed, when I KNOW my chart WAS being disposed. Turns out it was the legend in an external container that needed to be disposed.

**Comment by martynasma** [comment]
@thunsaker Yes. That would absolutely make sense. Will do. Thanks for the suggestion!
