### ISSUE TITLE
ForceDirection - Reset Force Attraction closing nodes 

### ISSUE THREAD

**Issue by nasodan** [amcharts/amcharts4#1891]
Hi, i have this situation 
https://codepen.io/daniele-messa/pen/vYYQVxx
At the beginning, the links between the father (AREAS OF ACTIVITIES) and the 3 children, have the same distance.
After opened some child the distance changes, and it's ok.
But when I close a child node  (SCIENTIFIC RESEARCH in particular, because has a lot of children) the distance does not return like that of the beginning, the node remains far away.
Is it possible to restore the "weight" or "gravity" of a node, to return to the starting situation?
Thanks a lot

**Comment by martynasma** [comment]
It looks like this happens on links between a fixed-position parent node and its child nodes.

I'm marking this as a bug. We'll see if it's fixable, or can maybe worked around.

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
