### ISSUE TITLE
"Uncaught ReferenceError: am4internal_webpackJsonp is not defined" raise in [4.7.10] standalone javascript version

### ISSUE THREAD

**Issue by SungKyung-Kim** [amcharts/amcharts4#1893]
Hi. I'm trying to test amcharts4 for my company's web site.

I download amcharts4 from https://www.amcharts.com/download/
a standalone JavaScript version. [4.7.10]

and add <script> tag 
"amcharts4/core.js" and "amcharts4/charts.js"

but some error occured.

Uncaught ReferenceError: am4core is not defined    /   dashboard.js:60 
    at dashboard.js:60
    at dashboard.js:89
(anonymous) @ dashboard.js:60
(anonymous) @ dashboard.js:89

Uncaught ReferenceError: am4internal_webpackJsonp is not defined / charts.js:20 
    at charts.js:20
(anonymous) @ charts.js:20

What should I do now?

**Comment by martynasma** [comment]
Try downloading the latest version, updating the files, and clearing your browser cache.

Let me know if this still persists.

**Comment by SungKyung-Kim** [comment]
Dear @martynasma 


The version I've tested is the latest version. [4.7.10]

Is there any other download page besides this page?

https://www.amcharts.com/download/

**Comment by martynasma** [comment]
Sorry, for some reason I've read 4.7.0. Yes 4.7.10 is the latest.

And I've just downloaded it to doublecheck. It works fine.

Make sure you update all files from the package if you had any previous versions. Also clear your browser cache.

If you are using any cloudfront services like CloudFlare or proxy servers, some files might be cached there as well. Make sure you clear that cache as well.

Finally, make sure you include `core.js` first, before `charts.js`.

**Comment by SungKyung-Kim** [comment]
Dear @martynasma 

Thanks.
I found the problem.

> Finally, make sure you include core.js first, before charts.js.

Yes. you're right.
It was because of the loading order.

The framework I use,
automatically add the async defer attribute to the script tag.

Anyway thanks to you.
