### ISSUE TITLE
Visualization of data that changes the time interval atleast once in the same period and How to?

### ISSUE THREAD

**Issue by shlomo7492** [amcharts/amcharts4#1894]
Hi,
I have the following problem: 
Our data is populated in the Database by sensor device once per time. The customer, can set this time interval(in minutes), so the data may be taken each one minute, or two,four... etc. The problem is that when I want to visualize a period that have change of the interval in it the line gets weird. In the time of first record with the new interval, it has a gap, then while not zoomed the rest looks ok, but when I zoom it to see the details, the lines disapear...
Is there any solution for such cases?
Thank you
Dimitar D.

P.S. I use line chart with data grouping, and series.connect = false,

**Comment by martynasma** [comment]
I suppose it's about setting proper `baseInterval` and `autoGapCount`.

Take a look at these two sections:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Manually_specifying_data_granularity
https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Gaps_over_missing_data_points

**Comment by shlomo7492** [comment]
Thank you! autoGapCount did the job! All fixed!
Sorry for delaying the response.
