### ISSUE TITLE
Can we remove the gaps horizontal bar charts (like simple gantt chart) ?

### ISSUE THREAD

**Issue by kaukota** [amcharts/amcharts4#1895]
<img width="693" alt="Screenshot 2019-11-18 at 3 42 33 PM" src="https://user-images.githubusercontent.com/33623676/69043958-1078c880-0a1a-11ea-940c-71e164748fcf.png">
Wanted to achieve similar functionality in amcharts4, series.columns.template.width = am4core.percent(100) is failing for horizontal charts

**Comment by martynasma** [comment]
You almost got it ;) Since this those columns are horizontal you should use `height` instead :)
