### ISSUE TITLE
How to get calculated max and min values

### ISSUE THREAD

**Issue by cipsicko** [amcharts/amcharts4#1896]
I'm trying to get the max value to set the axisRenges value. So it can be positioned in the perfect top of the chart.
As you can see in the [pen](https://codepen.io/cipsicko/pen/rNNooXZ), there is an extra space on the top of the chart.
I understand that the extra space is based on data that you set to the chart.

I find the `getMinMax` function that get the min end max values and set to those vars.
`this._minAdjusted = min;
  this._maxAdjusted = max;
  this._finalMin = min;
  this._finalMax = max;`
But no ones help me to find a solution.

thanks

**Comment by xorspark** [comment]
You can set [`strictMinMax`](https://www.amcharts.com/docs/v4/reference/valueaxis/#strictMinMax_property) to true to prevent the chart from automatically adjusting your max/min values.

[Codepen](https://codepen.io/team/amcharts/pen/bb6c9e212c264d94a415a6e719a4d801?editors=0010)

Note that when `strictMinMax` is not enabled, the value set in [`max`](https://www.amcharts.com/docs/v4/reference/valueaxis/#max_property) and [`min`](https://www.amcharts.com/docs/v4/reference/valueaxis/#min_property) may be overridden by the chart to make it fit into the grid, so those properties will contain the calculated values. If you ever need to get the initial values you specified, you can get them through the [`maxDefined`](https://www.amcharts.com/docs/v4/reference/valueaxis/#maxDefined_property) and [`minDefined`](https://www.amcharts.com/docs/v4/reference/valueaxis/#minDefined_property) properties.

**Comment by cipsicko** [comment]
Thanks, now is clear!
