### ISSUE TITLE
Chart was not disposed - React & Material 

### ISSUE THREAD

**Issue by shweta2345** [amcharts/amcharts4#1897]
Hi,
In version 4.5.16 print a warning "Chart was not disposed id-22" Am I missing something here? I do not intend to recreate or dispose of the chart at all.

**Comment by shweta2345** [comment]
Hi,
In version 4.5.16 print a warning "Chart was not disposed id-22" Am I missing something here? I do not intend to recreate or dispose of the chart at all.

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/tutorials/chart-was-not-disposed/
