### ISSUE TITLE
Gradient Support

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#190]
Hello,

I am trying to color my bar i.e. column with gradient colors.

It is mentioned in the docs that we can use fillModifier to achieve that. But I am unable to find anything about fillModifier. 

Can you suggest anything?

**Comment by martynasma** [comment]
Yes, this article :D

https://www.amcharts.com/docs/v4/concepts/colors/#Gradients

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by VaishnaviAppannagari** [comment]
I don't know how did I miss this article. Thank you for the reply.
