### ISSUE TITLE
Data export ".contains" error with Vue

### ISSUE THREAD

**Issue by Venlious** [amcharts/amcharts4#1900]
I am using amCharts 4 with Vue.

I have an XYChart in which I have a date field going by the name `time` containing timestamps. In order to allow the client to export the data, I make use of the [chart exporting functionality](https://www.amcharts.com/docs/v4/reference/export/). As the client has no use for the timestamps, I was asked if I could process these prior to export.

Upon reading the documentation, I understand that setting the following should in theory export the graph data in the ISO-8601 date format.

```
...
chart.exporting.dateFormat = 'i'
chart.exporting.dateFields = ['time']
...
```

However, an error appears in the console claiming that `contains` is not a function when I then try to export something.

```
Uncaught (in promise) TypeError: this.dateFields.contains is not a function
    at Export.isDateField (Export.js?7e9c:2819)
    at Export.convertToDateOrDuration (Export.js?7e9c:2140)
    at eval (Export.js?7e9c:2052)
    at eval (Object.js?a0dd:107)
    at eachContinue (Object.js?a0dd:93)
    at Module.each (Object.js?a0dd:106)
    at Export.getCSVRow (Export.js?7e9c:2043)
    at Export.eval (Export.js?7e9c:1995)
    at step (tslib.es6.js?9ab4:99)
    at Object.eval [as next] (tslib.es6.js?9ab4:80)
```

Going to the `Export.js` file under `@amcharts/amcharts4/.internal/core/export/Export.js` and changing `isDateField: this.dateFields.contains(field)` with `isDateField: this.dateFields.indexOf(field) > -1` resolves this issue for me and allows the data export to work as it should, including in the correct format. (But is of course not a real fix I can use in production)

**Comment by martynasma** [comment]
`dataFields` is not an array. It's an object of type `List`. The error occurs because you are replacing it with an array.

Instead replace just the values:

```
chart.exporting.dateFields.setAll(['time']);
```

**Comment by dnewkerk** [comment]
@martynasma I ran into the same issue as the original poster after following the instructions at https://www.amcharts.com/docs/v4/concepts/exporting/#Export_options

Here it says that `dateFields` has a type of `string[]` ... so it appears the documentation needs a quick update to match the solution you mentioned here. I tried your solution with setAll and it worked for me as well.

Thanks!

**Comment by martynasma** [comment]
@dnewkerk Good point. Updated. Thanks!
