### ISSUE TITLE
''zoomToDates'' does not work well with non-periodic data

### ISSUE THREAD

**Issue by dharam0034** [amcharts/amcharts4#1902]
dateXAxis.zoomToDates(
    date1,
    date2
  );

where date1 and date2 are two random date objects within the limits of the timestamps of X axis date points but not necessarily equal to the any points on date axis. After the zoomToDates command the both ends of the scrollbar is going in the beginning of the chart. Please help.

**Comment by martynasma** [comment]
Could you please post a working example?
