### ISSUE TITLE
Heat Legend reverseOrder not working

### ISSUE THREAD

**Issue by prathyushapatel** [amcharts/amcharts4#1903]
heatLegend.reverseOrder = true;
Above line has to change the heatlegend to reverse direction which is not working.

**Comment by martynasma** [comment]
`reverseOrder` is an inherited setting from `Container` which means that its children element need to be arranged in different order.

It does not related in any way to special stuff in HeatLegend like direction of gradient or scale numbers.

That said, I can see how this might be useful. I'm marking this as a possible enhancement we will consider.

While I can't provide any ETA, we'll keep you posted here about any possible developments.

Thanks!

**Comment by martynasma** [comment]
This seems to have been implemented a while ago. Closing.
