### ISSUE TITLE
How to know if hovering over the graph, not the chart

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1906]
Hi, is there a listener to know if the mouse is over the graph part?

I am using `chart.events.on("over", this.handleHoverChart, this)` but this also triggers when hovering the zoom bar or the numbers of the scale that are _outside_ the chart graph

To be clear, I would like to know if there is hover function for when hovering the RECTANGLE that holds the lines, not the lines only, and not anything outside the bounding of where the chart is drawn

Thank you

**Comment by martynasma** [comment]
You may need to set events on `chart.plotContainer` then.

**Comment by algebrathefish** [comment]
That seems to work, thank you!
