### ISSUE TITLE
"ZoomToData - scrollbar" does not work well in cordova iso app ( I am using amcharts 4 ionic 3 )

### ISSUE THREAD

**Issue by wsmr** [amcharts/amcharts4#1907]
![chart_error](https://user-images.githubusercontent.com/26834950/69399243-63e96000-0d13-11ea-8217-74931500ebe5.PNG)

**Comment by wsmr** [comment]
hi, @martynasma 
Is this a bug or my issue?
any solution.

thank you.

**Comment by martynasma** [comment]
Not sure. We don't have any experience with Cordova. if you could provide some way to reproduce this, we could take a look.
