### ISSUE TITLE
How to properly set dummyData of LineSeries?

### ISSUE THREAD

**Issue by dFelinger** [amcharts/amcharts4#1909]
I am trying to set dummyData to series of LineSeries chart by this article https://www.amcharts.com/docs/v4/concepts/data/#Dummy_data_in_data_points
But propertyFields (series.propertyFields.dummyData = 'extraData';) do not affect to use dummyData in tooltip text for example.
When I'm trying to set dummyData to dataFields (series.dataFields.dummyData = 'extraData';) it's ok, but for small data, on some big data chart shows error: "Cannot read property 'value' of undefined":
```
TypeError: Cannot read property 'value' of undefined
    at DateAxis.ts:959
    at Object.e.each (Array.ts:95)
    at DateAxis.ts:957
    at Object.e.each (Array.ts:95)
    at e.t.each (SortedList.ts:343)
    at DateAxis.ts:941
    at Object.e.each (Array.ts:95)
    at e.groupSeriesData (DateAxis.ts:915)
    at DateAxis.ts:884
    at Object.e.each (Array.ts:95)
```
Pen for test: https://codepen.io/dfelinger/pen/ZEEZpeQ
So, how to set dummyData to series of LineSeries.

**Comment by Mahisandy** [comment]
use this 
series.propertyFields.dummyData = "extraData";

**Comment by dFelinger** [comment]
> use this
> series.propertyFields.dummyData = "extraData";

In this way there is no data in:
```
series.tooltipText = "[bold]{category}[/]\nPersonnel: {dummyData.personnel}\nEquipment: {dummyData.equipment}\nOther: {dummyData.other}";
```

**Comment by Mahisandy** [comment]
ohh you u need add preperty to bullets not series try this code it working

//series.propertyFields.dummyData = "extraData";

//series.tooltipText = "[bold]{valueY}[/]\nPersonnel: {dummyData.personnel}\nEquipment: {dummyData.equipment}\nOther: {dummyData.other}";

var bullet = series.bullets.push(new am4core.Circle());
bullet.propertyFields.dummyData = "extraData";
bullet.tooltipText = "[bold]{valueY}[/]\nPersonnel: {dummyData.personnel}\nEquipment: {dummyData.equipment}\nOther: {dummyData.other}";

**Comment by dFelinger** [comment]
That doesn't help if I want to show tooltips on min scale, when bullets is automatically hidden :(
Like this with series.minBulletDistance = 200; for test

https://codepen.io/dfelinger/pen/ZEEZpeQ

**Comment by Mahisandy** [comment]
minBulletDistance setting means if there is less pixels between two adjacent data points, hide the bullets.so if want to see hiden bullet need to add scrollbar.

please read the document

https://www.amcharts.com/docs/v4/concepts/bullets/
