### ISSUE TITLE
Amchart 4 Legend Object initialization on Angular 6 

### ISSUE THREAD

**Issue by NIHAR1** [amcharts/amcharts4#1910]
i have issue with legend object initialization while implementing pie chart. i will share the screenshot, please let me how to resolve this issue.

![legend](https://user-images.githubusercontent.com/16055334/69412704-6eb4ec80-0d35-11ea-83e4-6d1eb92e5cc3.PNG)

**Comment by xorspark** [comment]
What TypeScript version are you using? AmCharts requires at [version 2.8](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/) or later. If you have strict mode enabled, you need to disable [strictNullChecks](https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/#TypeScript_strict_mode)

**Comment by NIHAR1** [comment]
> What TypeScript version are you using? AmCharts requires at [version 2.8](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/) or later. If you have strict mode enabled, you need to disable [strictNullChecks](https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/#TypeScript_strict_mode)

i have used typescript version 2.7.2 and also i have make strictNullChecks as false.

![typescript](https://user-images.githubusercontent.com/16055334/69428790-1511e980-0d58-11ea-96ba-e0964a000be0.PNG)
![strict](https://user-images.githubusercontent.com/16055334/69428803-1c38f780-0d58-11ea-980d-7717068aa41f.PNG)

**Comment by xorspark** [comment]
Did updating typescript fix the problem? 2.7.2 is below the minimum required version.
