### ISSUE TITLE
Associate several series with same legend

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#1913]
I have two charts that are depicting the same dataset. I added a legend to the first chart and i'd like to toggle the visibility of corresponding series in both charts when clicking on the legend.
Is there a way to bind several series to a legend like this?

Thank you very much!

**Comment by martynasma** [comment]
Something like this?
https://codepen.io/team/amcharts/pen/VwwNMWN

**Comment by Segolene-Albouy** [comment]
That's perfect! Thank you very much!
