### ISSUE TITLE
Gauge end value missing

### ISSUE THREAD

**Issue by saintpaulie123** [amcharts/amcharts4#1914]
Hi

I want to add a gauge that only shows the start end and values on the axis. I saw on the site that you could just change the value of minGridDistance and this seems to work. But if you change the value of axis.max then the end value disappears. For example in the pen below I've change the end value to 101 (from 100) and the value disappears. Change it back to 100 and it comes back. 
I wanted to have the gauge to show where someone is in regards to their targets which will change each month and won't be a very rounded number.

Is this a bug or is there another way around this?

Thanks

<p class="codepen" data-height="265" data-theme-id="default" data-default-tab="js,result" data-user="saintpaulie" data-slug-hash="mddgRop" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="amCharts 4: Gauge chart showing only first and last label">
  <span>See the Pen <a href="https://codepen.io/saintpaulie/pen/mddgRop">
  amCharts 4: Gauge chart showing only first and last label</a> by Paul (<a href="https://codepen.io/saintpaulie">@saintpaulie</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>

**Comment by xorspark** [comment]
Looks like `strictMinMax` with the odd end value isn't playing nicely with this.

An alternative solution is to use [axis ranges](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/) as guides and insert them at the minimum and maximum values of your gauge chart while disabling the axis' labels entirely:

```
axis.renderer.labels.template.disabled = true;
// ...
var minLabelGuide = axis.axisRanges.create();
minLabelGuide.value = axis.min;
minLabelGuide.endValue = axis.min;
minLabelGuide.label.text = axis.min;

var maxLabelGuide = axis.axisRanges.create();
maxLabelGuide.value = axis.max;
maxLabelGuide.endValue = axis.max;
maxLabelGuide.label.text = axis.max;
```

[Updated codepen](https://codepen.io/team/amcharts/pen/3624ab53398bceacbea92f05c3626078?editors=0010)

**Comment by saintpaulie123** [comment]
That's great! Thank you!
