### ISSUE TITLE
Detect column series isHover work is not well

### ISSUE THREAD

**Issue by havietduc91** [amcharts/amcharts4#1915]
Hi Amchart team,

Firstly, a big thank for your effort and nice support you've put in the library 
Secondly, we'd like to implement the feature that when the user hovers one column we'd like to set the opacity for the others one. But we're facing the issue that sometimes we cannot detect the column is hover

The error like the below image:
![Screenshot (1)](https://user-images.githubusercontent.com/4966192/69528161-4bda4080-0fa0-11ea-81a4-5cd6494f8005.png)
The video record the error: https://drive.google.com/file/d/1QG72USgepgbI80vZ8Mwj3oNL7bDdPgmv/view

And please refer the link to know more code example: https://codepen.io/havietduc91/pen/xxxNYvm

We use the below code to detect the hovered column:
```
let hoveredColumn = null;
columns.each(function(column) {
  const col = column
  if (col.isHover) {
    hoveredColumn = column;
    return;
  }
});

return hoveredColumn;
```
Finally, please show the solution to resolve it and let me know if I'm wrong

Many thanks,

**Comment by martynasma** [comment]
Relying on `isHover` in this case is super unreliable, since it is set by chart cursor, which works asynchronously. So it may be able to set each column's `isHover` in time before "over" event kicks in, or it may not.

Safer way would be to track cursor's movement, translate it's position into a category, and highlight columns in that category.

The following tutorial might be a good place to start:
https://www.amcharts.com/docs/v4/tutorials/tracking-cursors-position-via-api/

**Comment by havietduc91** [comment]
Thank you for the quick response, 
I have used ` track cursor` before for line chart, it works really good for a line chart, but with stacked column chart, we'd like to hide the tooltip when the user mouse out from column (column.isHover = false)

So should can I do in this case?
Many thanks,

**Comment by martynasma** [comment]
What I meant you can still rely on "over" event on columns, but when determining what other columns to highlight in the stack, you would not check their `isHover` status, but rather use cursor's position to highlight columns under that category.

Does that make sense?

**Comment by havietduc91** [comment]
Good idea, let me try and I will inform you later

Thank you for an awesome answer

**Comment by havietduc91** [comment]
I'm really glad to inform you that it works as expected.
so I will close this issue right away.

Many thanks,
