### ISSUE TITLE
Word cloud export right after creating the chart returns a blank image

### ISSUE THREAD

**Issue by dsjkaa** [amcharts/amcharts4#1917]
Hi, in my program I'm exporting charts right when I create them. This approach works for all other charts except word cloud.

**Note**: each chart is wrapped in a separate functions that returns the `chart `object.

For example, this code will result in either a blank PDF document or a document with a few words.

```
create_word_cloud().exporting.getImage("jpg").then(function(res){
      doc.content.push({
        image: res,
        fit: [600,300]
      });

pdfMake.createPdf(doc).download("report.pdf"); 
```

Is it possible to make exporting word clouds more "synchronous-like"? I thought about using
series.events.on("arrangeended", function(ev) {}), but that would require an async function and/or working with promises which is not ideal in my case.

**Comment by martynasma** [comment]
WordCloud final view is not available immediately. It needs some time to perform word arrangement, so doing export on "arrangeended" event is the only option, I'm afraid.

Not sure why async nature of event handlers would create any issues, though.

**Comment by waynep16** [comment]
Hi I am looking for an Amchart developer on a project ,  we are planning on using Wird Cloud charts. @dsjkaa are you available?
