### ISSUE TITLE
Typescript types or definitelytyped

### ISSUE THREAD

**Issue by oliverlj** [amcharts/amcharts4#1918]
I use this library in an ember app with typescript. Is is possible to have the types definition .d.ts ? or make a package inside http://definitelytyped.org/ ?

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/getting-started/integrations/using-ember/

**Comment by oliverlj** [comment]
I've completed this.
This will add the javascript libraby in node_modules.

Vscode tells me 
``Cannot find module '@amcharts/amcharts4/charts'.ts(2307)`` on 
``import * as am4charts from '@amcharts/amcharts4/charts';``

because there is no types defided

**Comment by oliverlj** [comment]
there is a type definition for amcharts v3 here https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/amcharts

**Comment by martynasma** [comment]
Did you install `@amcharts/amcharts4` package in your app?

**Comment by oliverlj** [comment]
Thanks, this made the job
``npm install --save-dev @amcharts/amcharts4``

Maybe the docs could be updated ?

**Comment by oliverlj** [comment]
I think now i have the dependency size issue
https://github.com/amcharts/amcharts4/issues/569

```
⠴ building... [Bundler][BABEL] Note: The code generator has deoptimised the styling of /home/oliver/git/fritzy/fritzy-front/node_modules/pdfmake/build/pdfmake.js as it exceeds the max of 500KB.
⠦ building... [Bundler][BABEL] Note: The code generator has deoptimised the styling of /home/oliver/git/fritzy/fritzy-front/node_modules/@amcharts/amcharts4/.internal/pdfmake/vfs_fonts.js as it exceeds the max of 500KB.
⠴ building... [Bundler][BABEL] Note: The code generator has deoptimised the styling of /home/oliver/git/fritzy/fritzy-front/node_modules/xlsx/xlsx.js as it exceeds the max of 500KB.
```

**Comment by oliverlj** [comment]
All is fine, just a babel info log
