### ISSUE TITLE
Rotated XY chart Axis grid and tooltip issue

### ISSUE THREAD

**Issue by shichenglu** [amcharts/amcharts4#192]
if create CategoryAxis to yAxes, the grid location cannot be changed by setting: categoryAxis.renderer.grid.template.location = 0.5;
Also, I use openValueX and valueX to create segments, there might be some issue with the tooltip of segments, if the container width is large enough, the tooltip will show up, otherwise the tooltip won't show up as below.
![image](https://user-images.githubusercontent.com/33080381/43547764-37c5554c-95aa-11e8-857e-c5979ac5789e.png)
the code is here
http://jsfiddle.net/shichenglu/gso90u6L/

**Comment by martynasma** [comment]
Indeed, `renderer.grid.template.location` does not seem to have any impact when used on a vertical axis.

We'll need to investigate this.

**Comment by martynasma** [comment]
Regarding tooltips. Do you mean tooltips that appear when hovering over bars? They show up for me at any size of the chart. Or is it something else?

**Comment by shichenglu** [comment]
yes, have you tried like this:
![image](https://user-images.githubusercontent.com/33080381/43566634-1f1ffa58-95fd-11e8-8b07-ab1e01dfada8.png)
if the width of the result column goes too narrow, the tooltips won't show up when hovering over bars. I have tried 2 different computers and got the same results.

**Comment by martynasma** [comment]
I got it as narrow as this:

![image](https://user-images.githubusercontent.com/1458520/43573198-d95a0584-9649-11e8-9a6e-43d775fb3f44.png)

Still tooltips show up.

This is weird that yours don't.

Does this happen in all browsers for you, or just Chrome?

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.41](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.41).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
