### ISSUE TITLE
 Space at the end of the graph

### ISSUE THREAD

**Issue by Alanovski** [amcharts/amcharts4#1920]
How could I add an extra space at the end of the graph so that it would not be stuck at the end of the frame?
Is there any property that solves that?

Regards

**Comment by martynasma** [comment]
Please provide mode details about your chart. Bets of all if you could post your whole chart on CodePen or jsFiddle.

**Comment by Alanovski** [comment]
Thanks for the reply 👍 
We currently have this graph:
[https://ibb.co/5RNghSW](url)
And we want that in the end it has a space or margin as in this image:
[https://ibb.co/7494tH8](url)


If possible without sending data or empty candles.

Regards

**Comment by martynasma** [comment]
You can use `extraMax` on `DateAxis` to add additional scale to the axis. For example:

```
dateAxis.extraMax = 0.1;
```

This will make the scale of the axis 10% longer.

**Comment by Alanovski** [comment]
Solved!
Many thanks to the team for the efficiency.

Regards
