### ISSUE TITLE
Serie disappear when mouse wheeel on drag

### ISSUE THREAD

**Issue by yingyinghu** [amcharts/amcharts4#1921]
Hi.
I want to drag a serie box but I have a limit of height so I want to use the mouse wheel to move up and down at same time. 
But when I do this. The series disappear sometimes and appear again when I return back. 
This action apper more when I go fast.

You can try on the link,
https://codepen.io/nanamissier/pen/dyyBLvp

**Comment by martynasma** [comment]
You are doing something funky with the chart. You made individual columns draggable. Is that your intention?

**Comment by yingyinghu** [comment]
Yes，it's Amchart alowed to do somethng like this? 

I use it to change items category value.  To organize my items to get better combination.

Please need help to see why it disappear!!

**Comment by martynasma** [comment]
I don't know man. Dragging a column is just changing position of visual element, not underlying data, so it gets reset to reflect real data whenever is needed.

I suppose you could watch events, change data accordingly, but it's quite complicated. We don't have a demo for that, or an easy way to do that. Sorry.

**Comment by yingyinghu** [comment]
Change the data is simply, I apply the new category data to the target when event dragStop occurs, and refresh de chart to have all centered.

The only things is the weird behavior of disappearing when scroll down or up.

Anyway, thank you for responding quickly.

**Comment by martynasma** [comment]
OK, so I might not be grasping the issue. I tried scrolling your chart in a lot of ways, but was not able to make columns to disappear. Can you post exact steps to reproduce the issue?

**Comment by yingyinghu** [comment]
Keep drag when scroll

**Comment by martynasma** [comment]
Gotcha. I don't think this can be implemented with reasonable complexity. Sorry.
