### ISSUE TITLE
Some charts not displaying after css-element-queries dependency update

### ISSUE THREAD

**Issue by BobNudd** [amcharts/amcharts4#1922]
This is due to save some potential headaches for users of the library.

Essentially, I have several charts wrapped in `tab` component from the `ngx-boostrap` lib.

After upgrading to `4.7.11`, I noticed that whilst the initial charts (default tab) loads, the remainder don't render (all the syntax is there when inspected via Chrome). Note nothing else was changed.

After downgrading the `css-element-queries` dependency to `1.2.1` this has fixed the issue.

I appreciate it's likely an issue relating to `ngx-boostrap` but naturally this isn't obvious.

**Comment by martynasma** [comment]
`css-element-queries` dependency haven't been updated a while. Which previous version of amCharts did you use?

**Comment by BobNudd** [comment]
Sorry for late late reply,

So, `"css-element-queries": "^1.0.5"` installs the 1.2.2 package, which causes the issue.

I can immediately fix this by explicitly specifying the 1.2.1 below (since `npm install` reverts the `package-lock.json` file)

    "@amcharts/amcharts4": {
      "version": "4.7.13",
      "resolved": "https://registry.npmjs.org/@amcharts/amcharts4/-/amcharts4-4.7.13.tgz",
      "integrity": "sha512-QM3oNVgnNPhbHwRoBiuQz+/rkeRv6d4U1Ds0YCKuPm5h6gN9ZxFYNCEl0l4T4p8f2t+MMZYca3uG7BM0ZPbCPg==",
      "requires": {
        "@types/regression": "^2.0.0",
        "canvg": "^2.0.0",
        "css-element-queries": "^1.0.5",
        "d3-force": "^2.0.1",
        "d3-geo": "^1.11.3",
        "d3-geo-projection": "^2.6.0",
        "pdfmake": "^0.1.36",
        "polylabel": "^1.0.2",
        "regression": "^2.0.1",
        "tslib": "^1.9.3",
        "xlsx": "^0.12.8"
      },
      "dependencies": {
        "css-element-queries": {
          "version": "1.2.1",
          "resolved": "https://registry.npmjs.org/css-element-queries/-/css-element-queries-1.2.1.tgz",
          "integrity": "sha512-hiI1tSzf+U/gE13qhfwnCvN90Ay0THnE+mT3pjN/c/mvFmEUHZVNrvMJrrkw2ppOzkl69FdgH2ZGZENYQUaN2A=="
        }
      }

**Comment by zeroin** [comment]
Hi,

We temporarily downgraded css-element-queries in v 4.7.14, which should fix the problem.
in the meantime we will investigate a proper fix

**Comment by BobNudd** [comment]
Thanks, installed and working as expected.
