### ISSUE TITLE
Multiple scales in 1 yAxis (valueAxis)

### ISSUE THREAD

**Issue by dordana** [amcharts/amcharts4#1923]
Hey,

I'm trying to implement multiple scales in 1 yAxis (valueAxis) like this:
![image](https://user-images.githubusercontent.com/30469137/69788983-81a54200-11b7-11ea-9e13-fb1de8dd9eb5.png)

Help?

**Comment by martynasma** [comment]
Check this:
https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Multiple_axes

**Comment by dordana** [comment]
Sorry but I can’t find it.
I need one line with multiple yAxes like the attached pic

**Comment by martynasma** [comment]
Attached pic has four lines with four separate scales / value axes. I must be missing something.

**Comment by dordana** [comment]
As you can see in the red circle, there is only one yAxis (valueAxis) for 4 different lines (series) with different color.

**Comment by martynasma** [comment]
Nope, I see four different value axes, superimposed on each other :)

You can make all left axes superimposed like this:

```
chart.leftAxesContainer.layout = "absolute";
```

**Comment by dordana** [comment]
![image](https://user-images.githubusercontent.com/30469137/69788610-caa8c680-11b6-11ea-9ee6-09d1d0ff9580.png)
Yes, I've thought about this but I'm facing a new issue as you can see

**Comment by martynasma** [comment]
Um, not sure what to suggest. There's no way to make labels from difference axes to "stack" onto each other. Sorry.
