### ISSUE TITLE
Stock chart  hour-based problem

### ISSUE THREAD

**Issue by ehsanpro2** [amcharts/amcharts4#1924]
Hello there
I've been involving  to solve a crazy problem for Stock chart.
My question is how can I set a candlestick chart based on hour.
I've already set it by this code: 
```
chart.dateFormatter.inputDateFormat = "yyyy-MM-dd HH:mm";
dateAxis.baseInterval = {
  "timeUnit": "hour",
   "count": 1
} ;
```
But when I have 3 data in a specific hour of the day, it shows all data not only one of them.
How can I fix it.
see the attached image in below link :
[https://pasteboard.co/IIG4kJX.png](url)

**Comment by martynasma** [comment]
I suppose it can be resolved using data point grouping.

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping

Can you post your whole chart on CodePen?

**Comment by ehsanpro2** [comment]
It works properly 
thanks .
