### ISSUE TITLE
export excel data as well image

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#1926]
can i add data as well image for excel export chart option

**Comment by martynasma** [comment]
No, I'm afraid. Sorry.

**Comment by Mahisandy** [comment]
ohhh bad luck amchart 4 every thing is customise that one not possible.
and one more i am trying to add export option for excel for map chart but in export menu not showing there any restriction can u explain and

**Comment by martynasma** [comment]
Um, not sure what data from map would you like to export to Excel?

**Comment by Mahisandy** [comment]
same data which i provided to chart but insted of id i need to show country name

**Comment by martynasma** [comment]
This might be useful:
https://www.amcharts.com/docs/v4/tutorials/exporting-mapchart-data/
