### ISSUE TITLE
How can I add new arrow (like bidirectinal) on MapLineSeries

### ISSUE THREAD

**Issue by mreorhan** [amcharts/amcharts4#1927]
**Im trying add 2 arrows on a line, but thats not working;**

 let lineSeries = map.series.push(new am4maps.MapLineSeries());

    // LINE OPTIONS
    lineSeries.mapLines.template.line.stroke = am4core.color("#5C5CFF");
    lineSeries.mapLines.template.line.strokeOpacity = 0.8;
    lineSeries.mapLines.template.line.strokeWidth = 2;
    lineSeries.mapLines.template.line.strokeDasharray = "6";
    lineSeries.mapLines.template.line.nonScalingStroke = true;

    let arrow2 = lineSeries.mapLines.template.arrow;
    let arrow = lineSeries.mapLines.template.arrow;

    arrow2.nonScaling = true;
    arrow2.position = 0.1;
    arrow2.height = 16;
    arrow2.width = 16;
    arrow2.fill = am4core.color("blue"); // 1. arrow

    arrow.nonScaling = true;
    arrow.position = 0.9; //0-1 arasında
    arrow.height = 16;
    arrow.width = 16;
    arrow.fill = am4core.color("black"); // 2. arrow

**Comment by martynasma** [comment]
`MapLine` supports only one built-in arrow.

To add several, we would need to create multiple elements ourselves and add them to the line.

Here's an example:
https://codepen.io/team/amcharts/pen/1d3e4de618ef3085c3d3f59bf6e26c8d?editors=0010
