### ISSUE TITLE
Question: Titles on top of vertical (value) axis but for Stacked Axes 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1929]
This is a great tutorial for moving the axis labels on top. 

However when I try to achieve the same with stacked axes its very difficult or I dont know how to do it 

Some guidance would be great .

So far I tried 

```
 // yAxis.layout = 'absolute';
      // yAxis.title.rotation = 0;
      // yAxis.title.align = 'center';
      // yAxis.title.valign = 'top';
      // yAxis.title.padding(10,10,10,10)
      // yAxis.title.dy = -40;
```

On a stacked axis but with no luck . The grid lines would not display etc. 

https://www.amcharts.com/docs/v4/tutorials/titles-on-top-of-vertical-value-axis/

**Comment by martynasma** [comment]
What issues are you experiencing?

I tried using it on a stacked chart example. Seems OK:
https://codepen.io/team/amcharts/pen/fb9136c2709397b87f3c8b1dc190ecb6?editors=0010

**Comment by jimmykane** [comment]
you can see the issue already in the example you provided @martynasma  

For more exposure try adding to the 1st value axis 

```
valueAxis.renderer.minLabelPosition = 0.05;
    valueAxis.renderer.maxLabelPosition = 0.95;
    valueAxis.title.fontSize = '1.0em';
    valueAxis.title.fontWeight = '600';

    valueAxis.renderer.ticks.template.disabled = false;
    valueAxis.renderer.ticks.template.strokeOpacity = 1;
    valueAxis.renderer.ticks.template.strokeWidth = 1;
    valueAxis.renderer.ticks.template.length = 5;
    valueAxis.renderer.minGridDistance = 20;
      valueAxis.renderer.line.strokeOpacity = 1;
```

In your example it shows here 

<img width="400" alt="Screenshot 2019-11-28 at 17 56 03" src="https://user-images.githubusercontent.com/1268723/69823142-63b3fd80-1208-11ea-99a6-98659774006c.png">

Notice that the axis renderer lables are offset for the top axis

**Comment by zeroin** [comment]
Moving the title to renderer and setting `isMeasured = false` will do most of the job. But you might need to adjust margins of scrollbar/axes in order to have enough space for them.

**Comment by jimmykane** [comment]
Almost there: 
```
      yAxis.layout = 'absolute';
      yAxis.renderer.line.align = 'right';
      yAxis.align = 'right';
      yAxis.marginTop = 20;
      yAxis.title.valign = 'top';
      yAxis.title.align = 'left';
      yAxis.title.dx = 100;
      yAxis.title.isMeasured = false;
      yAxis.title.parent = yAxis.renderer;

```

However I cannot get the title to align correctly 

Notice how depending on the screen size moves to the right / left. 

Any tips (take your time)
<img width="1072" alt="Screenshot 2019-12-09 at 18 49 28" src="https://user-images.githubusercontent.com/1268723/70459589-c9c83c80-1ab4-11ea-8f4c-b06aa934e7d1.png">

`
