### ISSUE TITLE
Container children do not position relatively as expected

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#193]
I was trying to place an `am4core.Image` to the bottom right of a Container (whose `isMeasured = false`) via its `x`/`y` coords being set to `am4core.Percent`s. 

What I noticed is that though a container's `.background` might auto expand to its contents, the container itself does not necessarily do so. Without a set `width`/`height`, or `minWidth`/`minHeight`, the `pixelWidth`/`Height` of the container itself is 0, so percentage-based positioning are 0, too. But its `measuredWidth`/`Height`s are accurate.

See the following example:
[pen](https://codepen.io/notacouch/pen/fc3a0ae5237012bd8dafaa6d4b268e0f?editors=0011), [live](https://codepen.io/notacouch/live/fc3a0ae5237012bd8dafaa6d4b268e0f)

There are 3 containers (A-C), each has 1 label saying what it is (eg "containerA") and each container has 3 positioned labels, one at top right, bottom right, and one at the bottom left (their `text` is their position).

`containerA` has no `minWidth`/`Height`, its background auto expands to its label's text, but all other labels are at the beginning.

`containerB` has `minWidth`/`Height` set to 50, the positioned labels we can see begin to position properly.

`containerC` has larger values and we can see the positioned labels in their respective positions, clearly.

**Comment by notacouch** [comment]
it's interesting to note the container's `measuredWidth`/`Height`s are accurate, they match the `pixel`/`measuredWidth`/`Height`s of its `.background`.

**Comment by notacouch** [comment]
Hrm so I'm trying to rely on `width`/`minWidth`, but it gets weird if the container has padding. note in the demo all containers have full padding of 15px. Everything is indented by 15px. But when positioning against the right side.... it's 30px away from the edge. So in the meantime it's better to use both a set width/minWidth (minus padding), and position what you can manually or carefully.

**Comment by martynasma** [comment]
Gotcha. Looks like padding is not taken into account, either.
