### ISSUE TITLE
Resizing or scaling the chart when exporting as image

### ISSUE THREAD

**Issue by dragosdydy** [amcharts/amcharts4#1930]
The chart that we're displaying the website is quite small, but we'd like that when it's exported as an image (or pdf) to increase it's size. Example: Chart in the website is 850px x 250px, but we'd like to export it at 1500px x 500px (just as an idea).

I have tried to play with the following code:
```
chart.exporting.events.on("exportstarted", function(ev) {
        chart.width = 1000;
        chart.height = 500;
});
```

But this is modifying the chart in the website too, and that's not desired as it has it's own space in the layout, and increasing the size in the website is breaking the layout.

Is there anyway to clone it in the background at the desired size and export that one? Or any other alternatives?

Thanks.

**Comment by martynasma** [comment]
You can use [`scale`](https://www.amcharts.com/docs/v4/reference/iexportimageoptions/#scale_property) option on image formats.

Here's how to set format-specific options:
https://www.amcharts.com/docs/v4/concepts/exporting/#Format_specific_options

**Comment by dragosdydy** [comment]
Great. I managed to make it work, thanks a lot for your answer. If someone's wondering, you can find my code below:

Function:
`exportChart = type => {
        let options = this.chart.exporting.getFormatOptions(type);
        options.scale = 2;
        this.chart.exporting.setFormatOptions(type, options);
        this.chart.exporting.filePrefix = "Prefix";
        this.chart.exporting.export(type);
    };`

Trigger:
`<button  onClick={() => this.exportChart("png")} className="button is-new-default is-small">
 PNG
</button>`

I'm using React 👍

Thanks again.
