### ISSUE TITLE
Question: zoom to latitude/longitude coordinate

### ISSUE THREAD

**Issue by AnastasiiaTsvetkova** [amcharts/amcharts4#1931]
Hi!

I need to zoom to the country after clicking outside the map. In amcharts 3 you have method zoomToLatLong. Is there a similar method? Or some other solutions? I have only latitude/longitude for point on the map.

Thanks

**Comment by martynasma** [comment]
Yes: [`zoomToGeoPoint()`](https://www.amcharts.com/docs/v4/reference/mapchart/#zoomToGeoPoint_method)
