### ISSUE TITLE
Solid Gauge with different Column Widths

### ISSUE THREAD

**Issue by Infineon12** [amcharts/amcharts4#1932]
Within Solid Gauge Charts in AM3 i could define the radius of the series.

Means e.g. 3 Small options, 1 Enlarged
Example:
https://codepen.io/Infineon12/pen/OJPLVEd

Any suggestion how this can be achieved with the AM4 Implementation?
Based on demo: https://www.amcharts.com/demos/solid-gauge/

In addition in my AM3 example included a second question i would have.
With the usage of radius i could customize the paddings between the options.

---

Following two images show the usage with AM3 which i want to achieve with AM4.

![2019-11-29 13_37_36- TEST  Statistik Gauge Demo](https://user-images.githubusercontent.com/2978137/69869634-a7147780-12ad-11ea-9075-1542bfa331a9.png)

![2019-11-29 13_37_58- TEST  Statistik Gauge Demo](https://user-images.githubusercontent.com/2978137/69869644-b1cf0c80-12ad-11ea-8a77-e3470633591e.png)

Thanks for your support in advance.

**Comment by zeroin** [comment]
You could set width of the columns in data using width property field:
https://codepen.io/team/amcharts/pen/JjoPerv

**Comment by Infineon12** [comment]
Thanks. For sure this idea i also tried.
Problem is that it only changes the width usage of the bar within the column.
The column itself does not change which results in unequal spaces.

**Comment by zeroin** [comment]
You can try this: https://codepen.io/team/amcharts/pen/1d4e40649415c989fad7f350d1e1b17f
The chart uses two value axes, series base axis is set to y axis. Axis ranges are created for the labels, in case you need them.

**Comment by Infineon12** [comment]
Just for your information, the second question i could resolve by using 100% usage and just adding two additional series with a value of 0 which now do act like a spacer.


![2019-12-02 08_35_59- TEST  Statistik Gauge Demo](https://user-images.githubusercontent.com/2978137/69938922-d2ca7400-14de-11ea-92ff-e72c4fcae18e.png)

**Comment by Infineon12** [comment]
> You can try this: https://codepen.io/team/amcharts/pen/1d4e40649415c989fad7f350d1e1b17f
> The chart uses two value axes, series base axis is set to y axis. Axis ranges are created for the labels, in case you need them.

Thank you very much.
I could use this to handle both issues without a problem.

Great support!
