### ISSUE TITLE
PieChart label radius and color

### ISSUE THREAD

**Issue by tomasts248** [amcharts/amcharts4#1934]
Several questions for Donut type Chart

I have been playing several hours into this, and it's been great, unfortunately there are stil some things I haven't managed to achieve.

1. How can the category labels be separateda bit in the outer direction of the circle?
Found this` https://codepen.io/team/amcharts/pen/0bdc44dd35e4484ed0c7e672849e7654`
but unfortunately the sintax is differnt for latest v4 version of AmCharts

2. How can I change the color of all the labels? For example to white. Tried with this css:
```
tspan {
  color:white;  
}
```

3. How to set a bottom border for every label. Tried with this css:
```
tspan { 
  border-bottom:1px solid black;
}
```

4. How to display the tooltip that is shown on hover also on active state?
That is if a slide has been clicked.

5. How to add the "active state" separation of slides by default, without clicking? and separate even more after click?

Last here is my current code in codepen:
`https://codepen.io/Snippet/pen/XWJrNQM`

**Comment by martynasma** [comment]
You can set the `radius` of the label template to control its distance from slices:

```
series.labels.template.radius = 50;
```

You can control other label appearance settings that way as well, including color.

Refer to [`AxisLabelCircular`](https://www.amcharts.com/docs/v4/reference/axislabelcircular/) class ref for available properties.

P.S. there's no way to add single border on label, I'm afraid.

Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic or multiple questions, please post a separate issue.

**Comment by tomasts248** [comment]
Thank you!!! For future reference I'm listing the solutions
# 1 worked perfectly.
# 2 used : series.labels.template.fill = "#6F6F6F";
# 3 can be set an underline perhaps?
# 5 in part solved by https://www.amcharts.com/docs/v4/tutorials/pie-chart-with-pre-pulled-slices/

"please post a separate issue."
Alright, I apologize will do in the future.
