### ISSUE TITLE
Dynamic heat rules in heatmap

### ISSUE THREAD

**Issue by felox2** [amcharts/amcharts4#1936]
Is there a way to update heat rules dynamically in the heatmap chart?

When you do it like this only a part of the chart updates:
```js
series.heatRules.clear()
series.heatRules.push({    
    target: columnTemplate,
    property: "fill",
    min: am4core.color('#fff'),
    max: am4core.color(getRandomColor())
});
```

Example: [https://codepen.io/felox2/pen/jOENYqa](https://codepen.io/felox2/pen/jOENYqa)

**Comment by zeroin** [comment]
Hi,

calling `chart.invalidateData()` should fix the thing. I will think if we can do it automatically bet don't want to promise anything.

**Comment by felox2** [comment]
Ah thanks that was easier than I thought it would be and I don't think it's necessary to automatically call the method just mention it in the docs somewhere.
