### ISSUE TITLE
Stacked LineSeries only one series tooltip shown on hover

### ISSUE THREAD

**Issue by crocusoft** [amcharts/amcharts4#1941]
Hi. I want to create chart like on the following image link: 
https://ibb.co/pRpw09N
I create this chart by Lineseries, setting stacked property true, when I want to display tooltip on only one element, after my research I can only set the tooltip in bullets, and setting cursorTooltipEnabled property to false. But I have to show tooltip on segments of series(not on bullets), when I do like that, datafields value don't display.
My code is on below link:
https://codepen.io/teller-guluzadeh/pen/rNaNWEL
How can I solve this issue? I would be grateful, if you help me about this.

**Comment by crocusoft** [comment]
Hi. I want to create chart like on the following image link: 
https://ibb.co/pRpw09N
I create this chart by Lineseries, setting stacked property true, when I want to display tooltip on only one element, after my research I can only set the tooltip in bullets, and setting cursorTooltipEnabled property to false. But I have to show tooltip on segments of series(not on bullets), when I do like that, datafields value don't display.
My code is on below link:
https://codepen.io/teller-guluzadeh/pen/rNaNWEL
How can I solve this issue? I would be grateful, if you help me about this.

**Comment by zeroin** [comment]
When you set a tooltip on a segment, it treats it as a simple sprite and simply shows what you've set there and does not take into account over which data item your cursor is. 
I created a demo where tooltip is set on series, but when you hover the segment it disables tooltips of all the series except the one you are hovering. However I could not find a way to have the tooltip in the middle:
https://codepen.io/team/amcharts/pen/8155753075c79af96237965e4cc3a748

**Comment by crocusoft** [comment]
Thanks for your reply, it was the solution to my problem.
