### ISSUE TITLE
Stacked Column doesn't respect the order data is returned in.

### ISSUE THREAD

**Issue by IKKaybe** [amcharts/amcharts4#1942]
I'm having an issue where when creating a stacked column, the series are not displaying in the order that they are returning in my data. 

Example 

![image](https://user-images.githubusercontent.com/8282135/70041845-c6651a80-15b5-11ea-8aa1-d68125c4ea46.png)

In the screenshot above, "Lowest Achievable Spend" is placed in the middle (This happens for the other months also) 

In my data it's being returned like so - 

![image](https://user-images.githubusercontent.com/8282135/70041951-f3b1c880-15b5-11ea-9d28-f61da33b5cee.png)

As you can see, "Lowest Achievable Spend" is the first entry, not the second entry.

We are building these charts using the am4core.createFromConfig

Our config being used is as follows

`{
  "data": [
    {
      "Month": "July 2019",
      "Lowest Achievable Spend": "£3,562.42",
      "Missed Saving": "£364.00",
      "Actual Saving": "£4,383.50",
      "Lowest Achievable SpendBreakDown": "<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201907'})\">£3,562.42</a>",
      "Actual SavingBreakDown": "<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201907'})\">£4,383.50</a>",
      "Missed SavingBreakDown": "<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201907'})\">£364.00</a>"
    },
    {
      "Month": "August 2019",
      "Lowest Achievable Spend": "£7,261.16",
      "Missed Saving": "£2,950.06",
      "Actual Saving": "£1,982.96",
      "Lowest Achievable SpendBreakDown": "<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201908'})\">£7,261.16</a>",
      "Actual SavingBreakDown": "<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201908'})\">£1,982.96</a>",
      "Missed SavingBreakDown": "<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201908'})\">£2,950.06</a>"
    },
    {
      "Month": "September 2019",
      "Lowest Achievable Spend": "£8,274.84",
      "Missed Saving": "£78.10",
      "Actual Saving": "£3,745.50",
      "Lowest Achievable SpendBreakDown": "<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201909'})\">£8,274.84</a>",
      "Actual SavingBreakDown": "<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201909'})\">£3,745.50</a>",
      "Missed SavingBreakDown": "<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201909'})\">£78.10</a>"
    },
    {
      "Month": "October 2019",
      "Lowest Achievable Spend": "£4,736.96",
      "Missed Saving": "£6,491.08",
      "Actual Saving": "£3,260.28",
      "Lowest Achievable SpendBreakDown": "<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201910'})\">£4,736.96</a>",
      "Actual SavingBreakDown": "<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201910'})\">£3,260.28</a>",
      "Missed SavingBreakDown": "<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201910'})\">£6,491.08</a>"
    },
    {
      "Month": "November 2019",
      "Lowest Achievable Spend": "£10,167.97",
      "Missed Saving": "£4,391.53",
      "Actual Saving": "£6,046.24",
      "Lowest Achievable SpendBreakDown": "<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201911'})\">£10,167.97</a>",
      "Actual SavingBreakDown": "<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201911'})\">£6,046.24</a>",
      "Missed SavingBreakDown": "<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201911'})\">£4,391.53</a>"
    }
  ],
  "legend": {
    "disabled": true,
    "type": "Legend"
  },
  "xAxes": [
    {
      "type": "CategoryAxis",
      "title": {
        "text": "Month"
      },
      "dataFields": {
        "category": "Month",
        "title": {
          "text": "Month"
        }
      },
      "renderer": {
        "labels": {
          "rotation": 90,
          "verticalCenter": "middle",
          "horizontalCenter": "left"
        }
      }
    }
  ],
  "yAxes": [
    {
      "type": "ValueAxis",
      "title": {
        "text": "Transactions"
      },
      "numberFormatter": {
        "numberFormat": "'£' #,###.00"
      }
    }
  ],
  "series": [
    {
      "name": "Actual Saving",
      "type": "ColumnSeries",
      "dataFields": {
        "valueY": "Actual Saving",
        "categoryX": "Month"
      },
      "stacked": true,
      "columns": {
        "tooltipText": "[bold]{categoryX} - Actual Saving[/]\n{valueY}",
        "cursorOverStyle": [
          {
            "property": "cursor",
            "value": "pointer"
          }
        ]
      },
      "events": {},
      "colors": {
        "list": [
          "#51a7fa",
          "#72bf4a",
          "#f5d428"
        ]
      }
    },
    {
      "name": "Lowest Achievable Spend",
      "type": "ColumnSeries",
      "dataFields": {
        "valueY": "Lowest Achievable Spend",
        "categoryX": "Month"
      },
      "stacked": true,
      "columns": {
        "tooltipText": "[bold]{categoryX} - Lowest Achievable Spend[/]\n{valueY}",
        "cursorOverStyle": [
          {
            "property": "cursor",
            "value": "pointer"
          }
        ]
      },
      "events": {},
      "colors": {
        "list": [
          "#51a7fa",
          "#72bf4a",
          "#f5d428"
        ]
      }
    },
    {
      "name": "Missed Saving",
      "type": "ColumnSeries",
      "dataFields": {
        "valueY": "Missed Saving",
        "categoryX": "Month"
      },
      "stacked": true,
      "columns": {
        "tooltipText": "[bold]{categoryX} - Missed Saving[/]\n{valueY}",
        "cursorOverStyle": [
          {
            "property": "cursor",
            "value": "pointer"
          }
        ]
      },
      "events": {},
      "colors": {
        "list": [
          "#51a7fa",
          "#72bf4a",
          "#f5d428"
        ]
      }
    }
  ]
}`

Hopefully this issue can be fixed or sorted on my side as this is stopping us from purchasing an amCharts4 license for when we launch with our product.

**Comment by zeroin** [comment]
The stack order does not depend on the order of properties in your data, it depends only on the order of the series in your config. So you must move the 'Lowest Achievable Spend' series to before the `Actual Saving` series in config.

**Comment by IKKaybe** [comment]
@zeroin It is before Actual Saving as shown in my config above, or am I missing something?

**Comment by zeroin** [comment]
Your code is:

```
{ 
   "data":[ 
      { 
         "Month":"July 2019",
         "Lowest Achievable Spend":"£3,562.42",
         "Missed Saving":"£364.00",
         "Actual Saving":"£4,383.50",
         "Lowest Achievable SpendBreakDown":"<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201907'})\">£3,562.42</a>",
         "Actual SavingBreakDown":"<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201907'})\">£4,383.50</a>",
         "Missed SavingBreakDown":"<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201907'})\">£364.00</a>"
      },
      { 
         "Month":"August 2019",
         "Lowest Achievable Spend":"£7,261.16",
         "Missed Saving":"£2,950.06",
         "Actual Saving":"£1,982.96",
         "Lowest Achievable SpendBreakDown":"<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201908'})\">£7,261.16</a>",
         "Actual SavingBreakDown":"<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201908'})\">£1,982.96</a>",
         "Missed SavingBreakDown":"<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201908'})\">£2,950.06</a>"
      },
      { 
         "Month":"September 2019",
         "Lowest Achievable Spend":"£8,274.84",
         "Missed Saving":"£78.10",
         "Actual Saving":"£3,745.50",
         "Lowest Achievable SpendBreakDown":"<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201909'})\">£8,274.84</a>",
         "Actual SavingBreakDown":"<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201909'})\">£3,745.50</a>",
         "Missed SavingBreakDown":"<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201909'})\">£78.10</a>"
      },
      { 
         "Month":"October 2019",
         "Lowest Achievable Spend":"£4,736.96",
         "Missed Saving":"£6,491.08",
         "Actual Saving":"£3,260.28",
         "Lowest Achievable SpendBreakDown":"<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201910'})\">£4,736.96</a>",
         "Actual SavingBreakDown":"<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201910'})\">£3,260.28</a>",
         "Missed SavingBreakDown":"<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201910'})\">£6,491.08</a>"
      },
      { 
         "Month":"November 2019",
         "Lowest Achievable Spend":"£10,167.97",
         "Missed Saving":"£4,391.53",
         "Actual Saving":"£6,046.24",
         "Lowest Achievable SpendBreakDown":"<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201911'})\">£10,167.97</a>",
         "Actual SavingBreakDown":"<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201911'})\">£6,046.24</a>",
         "Missed SavingBreakDown":"<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201911'})\">£4,391.53</a>"
      }
   ],
   "legend":{ 
      "disabled":true,
      "type":"Legend"
   },
   "xAxes":[ 
      { 
         "type":"CategoryAxis",
         "title":{ 
            "text":"Month"
         },
         "dataFields":{ 
            "category":"Month",
            "title":{ 
               "text":"Month"
            }
         },
         "renderer":{ 
            "labels":{ 
               "rotation":90,
               "verticalCenter":"middle",
               "horizontalCenter":"left"
            }
         }
      }
   ],
   "yAxes":[ 
      { 
         "type":"ValueAxis",
         "title":{ 
            "text":"Transactions"
         },
         "numberFormatter":{ 
            "numberFormat":"'£' #,###.00"
         }
      }
   ],
   "series":[ 
      { 
         "name":"Actual Saving",
         "type":"ColumnSeries",
         "dataFields":{ 
            "valueY":"Actual Saving",
            "categoryX":"Month"
         },
         "stacked":true,
         "columns":{ 
            "tooltipText":"[bold]{categoryX} - Actual Saving[/]\n{valueY}",
            "cursorOverStyle":[ 
               { 
                  "property":"cursor",
                  "value":"pointer"
               }
            ]
         },
         "events":{ 

         },
         "colors":{ 
            "list":[ 
               "#51a7fa",
               "#72bf4a",
               "#f5d428"
            ]
         }
      },
      { 
         "name":"Lowest Achievable Spend",
         "type":"ColumnSeries",
         "dataFields":{ 
            "valueY":"Lowest Achievable Spend",
            "categoryX":"Month"
         },
         "stacked":true,
         "columns":{ 
            "tooltipText":"[bold]{categoryX} - Lowest Achievable Spend[/]\n{valueY}",
            "cursorOverStyle":[ 
               { 
                  "property":"cursor",
                  "value":"pointer"
               }
            ]
         },
         "events":{ 

         },
         "colors":{ 
            "list":[ 
               "#51a7fa",
               "#72bf4a",
               "#f5d428"
            ]
         }
      },
      { 
         "name":"Missed Saving",
         "type":"ColumnSeries",
         "dataFields":{ 
            "valueY":"Missed Saving",
            "categoryX":"Month"
         },
         "stacked":true,
         "columns":{ 
            "tooltipText":"[bold]{categoryX} - Missed Saving[/]\n{valueY}",
            "cursorOverStyle":[ 
               { 
                  "property":"cursor",
                  "value":"pointer"
               }
            ]
         },
         "events":{ 

         },
         "colors":{ 
            "list":[ 
               "#51a7fa",
               "#72bf4a",
               "#f5d428"
            ]
         }
      }
   ]
}```

Instead, ir should be (check series order):

```
import * as am4core from "../src/core";
import * as am4charts from "../src/charts";
import * as am4maps from "../src/maps";
import am4geodata_worldLow from "../src/geodata/worldLow";
//import am4geodata_worldIndiaHigh from "../src/geodata/worldIndiaHigh";
import am4geodata_worldHigh from "../src/geodata/worldHigh";
import am4geodata_continentsHigh from "../src/geodata/continentsHigh";
import am4geodata_continentsLow from "../src/geodata/continentsLow";
import am4geodata_usaHigh from "../src/geodata/usaHigh";
import am4geodata_germanyHigh from "../src/geodata/germanyHigh";
import am4geodata_usaLow from "../src/geodata/usaLow";
import am4geodata_arubaLow from "../src/geodata/arubaLow";
import am4geodata_arubaHigh from "../src/geodata/arubaHigh";
import am4themes_dark from "../src/themes/dark";
import am4themes_amchartsdark from "../src/themes/amchartsdark";
import am4themes_animated from "../src/themes/animated";
import * as am4plugins_sunburst from "../src/plugins/sunburst";
import am4geodata_test from "../src/geodata/usaTerritoriesLow"
import * as am4plugins_wordCloud from "../src/plugins/wordCloud";
import * as am4plugins_forceDirected from "../src/plugins/forceDirected";
import * as am4plugins_sliceGrouper from "../src/plugins/sliceGrouper";
import * as am4plugins_bullets from "../src/plugins/bullets";
import * as am4plugins_timeline from "../src/plugins/timeline";
import * as am4plugins_regression from "../src/plugins/regression";

/**
 * ---------------------------------------
 * This demo was created using amCharts 4.
 * 
 * For more information visit:
 * https://www.amcharts.com/
 * 
 * Documentation is available at:
 * https://www.amcharts.com/docs/v4/
 * ---------------------------------------
 */



{ 
   "data":[ 
      { 
         "Month":"July 2019",
         "Lowest Achievable Spend":"£3,562.42",
         "Missed Saving":"£364.00",
         "Actual Saving":"£4,383.50",
         "Lowest Achievable SpendBreakDown":"<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201907'})\">£3,562.42</a>",
         "Actual SavingBreakDown":"<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201907'})\">£4,383.50</a>",
         "Missed SavingBreakDown":"<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201907'})\">£364.00</a>"
      },
      { 
         "Month":"August 2019",
         "Lowest Achievable Spend":"£7,261.16",
         "Missed Saving":"£2,950.06",
         "Actual Saving":"£1,982.96",
         "Lowest Achievable SpendBreakDown":"<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201908'})\">£7,261.16</a>",
         "Actual SavingBreakDown":"<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201908'})\">£1,982.96</a>",
         "Missed SavingBreakDown":"<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201908'})\">£2,950.06</a>"
      },
      { 
         "Month":"September 2019",
         "Lowest Achievable Spend":"£8,274.84",
         "Missed Saving":"£78.10",
         "Actual Saving":"£3,745.50",
         "Lowest Achievable SpendBreakDown":"<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201909'})\">£8,274.84</a>",
         "Actual SavingBreakDown":"<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201909'})\">£3,745.50</a>",
         "Missed SavingBreakDown":"<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201909'})\">£78.10</a>"
      },
      { 
         "Month":"October 2019",
         "Lowest Achievable Spend":"£4,736.96",
         "Missed Saving":"£6,491.08",
         "Actual Saving":"£3,260.28",
         "Lowest Achievable SpendBreakDown":"<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201910'})\">£4,736.96</a>",
         "Actual SavingBreakDown":"<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201910'})\">£3,260.28</a>",
         "Missed SavingBreakDown":"<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201910'})\">£6,491.08</a>"
      },
      { 
         "Month":"November 2019",
         "Lowest Achievable Spend":"£10,167.97",
         "Missed Saving":"£4,391.53",
         "Actual Saving":"£6,046.24",
         "Lowest Achievable SpendBreakDown":"<a onclick=\"clicked({'Category': 'Lowest Achievable Spend', 'Date': '201911'})\">£10,167.97</a>",
         "Actual SavingBreakDown":"<a onclick=\"clicked({'Category': 'Actual Saving', 'Date': '201911'})\">£6,046.24</a>",
         "Missed SavingBreakDown":"<a onclick=\"clicked({'Category': 'Missed Saving', 'Date': '201911'})\">£4,391.53</a>"
      }
   ],
   "legend":{ 
      "disabled":true,
      "type":"Legend"
   },
   "xAxes":[ 
      { 
         "type":"CategoryAxis",
         "title":{ 
            "text":"Month"
         },
         "dataFields":{ 
            "category":"Month",
            "title":{ 
               "text":"Month"
            }
         },
         "renderer":{ 
            "labels":{ 
               "rotation":90,
               "verticalCenter":"middle",
               "horizontalCenter":"left"
            }
         }
      }
   ],
   "yAxes":[ 
      { 
         "type":"ValueAxis",
         "title":{ 
            "text":"Transactions"
         },
         "numberFormatter":{ 
            "numberFormat":"'£' #,###.00"
         }
      }
   ],
   "series":[      
      { 
         "name":"Lowest Achievable Spend",
         "type":"ColumnSeries",
         "dataFields":{ 
            "valueY":"Lowest Achievable Spend",
            "categoryX":"Month"
         },
         "stacked":true,
         "columns":{ 
            "tooltipText":"[bold]{categoryX} - Lowest Achievable Spend[/]\n{valueY}",
            "cursorOverStyle":[ 
               { 
                  "property":"cursor",
                  "value":"pointer"
               }
            ]
         },
         "events":{ 

         },
         "colors":{ 
            "list":[ 
               "#51a7fa",
               "#72bf4a",
               "#f5d428"
            ]
         }
      },
      { 
         "name":"Missed Saving",
         "type":"ColumnSeries",
         "dataFields":{ 
            "valueY":"Missed Saving",
            "categoryX":"Month"
         },
         "stacked":true,
         "columns":{ 
            "tooltipText":"[bold]{categoryX} - Missed Saving[/]\n{valueY}",
            "cursorOverStyle":[ 
               { 
                  "property":"cursor",
                  "value":"pointer"
               }
            ]
         },
         "events":{ 

         },
         "colors":{ 
            "list":[ 
               "#51a7fa",
               "#72bf4a",
               "#f5d428"
            ]
         }
      },
      { 
         "name":"Actual Saving",
         "type":"ColumnSeries",
         "dataFields":{ 
            "valueY":"Actual Saving",
            "categoryX":"Month"
         },
         "stacked":true,
         "columns":{ 
            "tooltipText":"[bold]{categoryX} - Actual Saving[/]\n{valueY}",
            "cursorOverStyle":[ 
               { 
                  "property":"cursor",
                  "value":"pointer"
               }
            ]
         },
         "events":{ 

         },
         "colors":{ 
            "list":[ 
               "#51a7fa",
               "#72bf4a",
               "#f5d428"
            ]
         }
      }      
   ]
}```
