### ISSUE TITLE
Legend label color changes to default and Some legend Question

### ISSUE THREAD

**Issue by Muzzamil1** [amcharts/amcharts4#1943]
Hi there!
1. To change the default color of the line series I did it using
`series.stroke = am4core.color(color);`
and the legend label color also changes to that color. If I click the legend it hides the series and then clicks again the legend color changes to default.
Here is the codepen 
[https://codepen.io/muzzamil/pen/wvBByaq](https://codepen.io/muzzamil/pen/wvBByaq)

2. How can I add an HTML element right next to each Legend which is independent of the legend click event? let's say I want to add a radio button with each legend or add the legend in an HTML table row that has some other data in its columns. 
i.e. legend/series label, value, and some other information in the HTML table row for each series

3. Is it possible to move the Legend position like this instead of middle or left or right? One at the start and second in the middle. Of course, the 3rd will be below to the first one 
![Legend](https://user-images.githubusercontent.com/53085438/70117210-a8b3b600-1686-11ea-8671-6edb14e01546.PNG)

**Comment by zeroin** [comment]
Hi,

1) Instead of setting colors like you do, add this:
chart.legend.labels.template.propertyFields.fill = "stroke";
It should solve the issue.

2) I made this pen to show how you can add html to the legend items:
https://codepen.io/team/amcharts/pen/ce506ff0c316afae5946c5c5b8f91312
In general I add a Label to `itemContainer` and set html property to some HTML.

3) `chart.legend.contentAlign = "left";` will do that.

**Comment by Muzzamil1** [comment]
Thanks, man.
Really appreciate it.
3. with `chart.legend.contentAlign = "left"; `all the legend align to left. Is it possible to move the 2nd series in the center? 
![Legend](https://user-images.githubusercontent.com/53085438/70235469-d5e68e00-1784-11ea-8b73-9452c87f583e.PNG)

**Comment by zeroin** [comment]
Well, you could try setting `chart.legend.itemContainers.template.paddingRight = 500`; so that the gap would be really big.

**Comment by Muzzamil1** [comment]
Thanks again 
Worked.

**Comment by Muzzamil1** [comment]
Hi @zeroin 
I was trying to use the radio button functionality with a Live chart.
Here is the pen.
[https://codepen.io/muzzamil/pen/BayoaGv](https://codepen.io/muzzamil/pen/BayoaGv)
1. If I select the radio option it will automatically uncheck when graph updates.
2. As graph updates, there is floating value in the legend
![Legend](https://user-images.githubusercontent.com/53085438/70316253-1a356500-183d-11ea-9a13-1f61604864a2.PNG)
How to stop this behavior?

**Comment by zeroin** [comment]
You can apply number formatting like:
`series.legendSettings.valueText = " {valueY.close.formatNumber('#.#')}";`

This will result maximum one number after the comma.
The label is recreated each time series data changes, that's why the button loses the checked attribute. I solved this by using series dummyData:
https://codepen.io/team/amcharts/pen/6fd20ff4a30acc592b0bb1e6dff974d0

**Comment by Muzzamil1** [comment]
Thanks.

**Comment by dhiren-eng** [comment]
Hi @zeroin @martynasma ,

chart.legend.labels.template.propertyFields.fill = "fill"; does not seem to solve the legend label color problem for **candlestick series or column series**. Default legend colors still show in this situation.

Here is the codepen : https://codepen.io/dhiren530/pen/zYKYvXe

**Comment by zhaoyi-zhuang** [comment]
> 1. chart.legend.labels.template.propertyFields.fill = "stroke";

Hi there. How do I achieve this line in amchart5? Thanks!

--------------------

Update:

nvm, found it here: https://www.amcharts.com/docs/v5/tutorials/using-series-color-for-legend-labels/

**Comment by zhaoyi-zhuang** [comment]
> > 1. chart.legend.labels.template.propertyFields.fill = "stroke";
> 
> Hi there. How do I achieve this line in amchart5? Thanks!
> 
> Update:
> 
> nvm, found it here: https://www.amcharts.com/docs/v5/tutorials/using-series-color-for-legend-labels/

Update again.

Seems like this solution does not work with cursor: https://codepen.io/zhaoyi-zhuang/pen/QwwyWre

When a legend is disabled, its color will be changed when user hover on the chart.

Opened an issue in amchart5: https://github.com/amcharts/amcharts5/issues/1896
