### ISSUE TITLE
Animate again pie or bars after load() of new datas.

### ISSUE THREAD

**Issue by noiwid** [amcharts/amcharts4#1944]
Hi,
I'm using amCharts 4 on a page that combinate 3 graphs :
- Pie with age range of my users
- Pie with genre repartiton
- Histogram with number of orders

I've set up a system that allow to make all charts react to filters done on other charts on this page.

If I click on a age range (20-25 for example), it'll highlight the slice I clicked, get its id, and go load the content filtered with my selection for my 2 other graphs (genre/orders). Everything is working as expected on this side. I can combinate, remove my filters it works like a charm.

**My problem :**
I don't find any way to animate the load of new datas on my graphs (as it's done when graphs are first built).

**How I initiate my graphs:**

    var chart = am4core.create("myGraph", am4charts.PieChart);
    chart.dataSource.url = url_json_dataset; 
    chart.dataSource.parser = new am4core.JSONParser();

**How I update my graphs:**

    chart.dataSource.url = url_json_dataset_with_filters;
    chart.dataSource.load();

I've also try to load my json outside amcharts, and force update of the dataset, and don't get better results, data load is done without any transition:

    chart.data = my_json_array;
    chart.invalidateData();

The animateAgain() method is documented for amCharts 3, but is not working anymore on the new version, see here : https://www.amcharts.com/docs/v3/tutorials/showcase-various-chart-animation-effects/

Any idea on how to achieve it ?

Thanks a lot for your support.

**Comment by zeroin** [comment]
To repeat series animation, simply call:
```series.appear()```

**Comment by noiwid** [comment]
Thanks a lot for this feedback!!! 
I've just try, it's doing the job

Meanwhile I also dig with invalidateRawData() that allow to animate values changes in a smoothy maner (not all graph is updated, but just interpolation to new values), but it's painfull to update the dataset, it seems values has to be changed indivualy in the array, if you overwrite the array itself, no animation..

**Update with animation:**
```
chart.data[0]["nb"] = 800; // newvalue
chart.data[1]["nb"] = 1000; // newvalue2

```....
chart.invalidateRawData()

**Update without animation:**
```
chart.data = newdataset;
chart.invalidateRawData(); // I also try invalidateData() method...

```
The first method downsides are:
- Need to grab array key to allow to remplace each data that require update
- In some case, the series change, so we need to add/remove new items in the dataset

If new items are added, the array order change, and for an unknow reason I loose animation on the way... Any idea why replace the whole chart.data with a new array (even if the series is equal with new values) the transition animation stops?
