### ISSUE TITLE
Question: ShowOnlyOnViewport creates a strange chart 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1945]
What can I be doing wrong when I enable showOnlyOnViewPort? 

Here is the produce 
<img width="1430" alt="Screenshot 2019-12-04 at 18 06 17" src="https://user-images.githubusercontent.com/1268723/70164124-ed5c4300-16c0-11ea-8713-c0a6a4f3a319.png">

**Comment by jimmykane** [comment]
It kinda looks the x DateAxis has only a few points parsed?

**Comment by zeroin** [comment]
There is not much you can do wrong with it, well, it should go above the charts. Unfortunately I can't reproduce this :(
