### ISSUE TITLE
Treemap

### ISSUE THREAD

**Issue by ombi** [amcharts/amcharts4#1946]
Hi folks,
I need to create a drillable treemap where values of level 0 are not computed from the sum of its children but directly set. I tried using "value : xxx" before children array but apparently it was rewritten with the sum of the childeren values....
Any hint?

**Comment by zeroin** [comment]
Sorry, but this is not possible.

**Comment by davidzmx** [comment]
> Hi folks,
> I need to create a drillable treemap where values of level 0 are not computed from the sum of its children but directly set. I tried using "value : xxx" before children array but apparently it was rewritten with the sum of the childeren values....
> Any hint?

did you resolve this? I need to do that as well.
