### ISSUE TITLE
Show Tooltip in area chart & get data after clicking on tooltip

### ISSUE THREAD

**Issue by guruprasadpatil** [amcharts/amcharts4#1948]
Hi Team,
I want to show tooltip in area chart created by using XYChart & Line series. Now, my chart is not showing neither tooltip in Text nor in HTML. I want to create area chart which will do following activity in Angular 6 application-

1. Show four values in tooltip i.e **myXVal, myYVal, other1, count**
2. Allow Click on tooltip & get **myXVal** shown in that tooltip
3. Print **myXVal** in console / assign respective **count** to **selectedCount**

![image](https://user-images.githubusercontent.com/24885074/70234576-f6174c80-1786-11ea-8df4-fb3057d5f03d.png)

**Comment by zeroin** [comment]
I will take a look. But it would be so much faster if you could provide a working codepen example instead of pasting code here - thanks!

**Comment by zeroin** [comment]
With both axes to be ValueAxis, you don;t get tooltips to be shown automatically, unless you tell the cursor to which series it should snap:

`chart.cursor.snapToSeries = series;`

ANother way would be adding bullets to the series, but of course they will be shown only when hovered. This might be a solution when you have more than one series, as snapToSeries only accepts one series.

**Comment by guruprasadpatil** [comment]
Hi @zeroin ,
Please have a look on following sample application. I need to do 3 actions which are mentioned in issue description.
https://stackblitz.com/edit/amcharts4-zwpxno

**Comment by zeroin** [comment]
Hi,

Here is all the requirements implemented:
https://codepen.io/team/amcharts/pen/c3dd93a334cdb5d289aea76f9d4892ff

the tooltip is not showing in your stackblitz demo because you use a very old version, I recommend using the latest version.
