### ISSUE TITLE
Documentation Typo (Anatomy of a Force Directed Tree) 

### ISSUE THREAD

**Issue by VJordi** [amcharts/amcharts4#1949]
I was checking the Force-directed tree documentation to integrate it and I found a small type that can case headache to someone:

Under the Length section (https://www.amcharts.com/docs/v4/chart-types/force-directed/#Length) the code snippet of the tab _Javascript_ presents this code:

```
series.links.template.disatnce = 2;
```

Where it should be
```
series.links.template.distance = 2;
```

Just that :D

**Comment by martynasma** [comment]
Docs are fixed. Thanks for the heads up!
