### ISSUE TITLE
Maps: projection AlbersUSA: Cannot read property '0' of null

### ISSUE THREAD

**Issue by a-dub-l** [amcharts/amcharts4#1950]
When creating an amcharts map using the AlbersUSA projection with a MapImageSeries, a severe failure occurs with the message (in the middle of where the map should be): Cannot read property '0' of null.

To better explain and in order to help, I've included a failing example in JsFiddle: http://jsfiddle.net/bLfp1c23/

Thanks

**Comment by zeroin** [comment]
AlbersUSA projection only handles latitudes/longitudes properly which are withing US latitudes/longitudes. If you change your longitude to

`longitude: -89.5073`

the chart will work properly.

**Comment by a-dub-l** [comment]
Hah! Thanks. It was a typo, but it showed that the large amount of actual data actually contained a few of these typos as well...

As a suggestion, though, perhaps a better error message for this time of issue would be appropriate here?
