### ISSUE TITLE
Force Directed Tree Collapse issue.

### ISSUE THREAD

**Issue by XGuGu** [amcharts/amcharts4#1951]
Hi.

In the chart, we have several mainNodes, and each mainNode has several childNodes. And childNodes are connected to several other mainNodes(not only include parent node). I used linkWith for the connection.

I am trying to add a button to collapse all the mainNodes or undo it. When I collapse all and reopen all of the mainNodes by manually click, the connection between mainNodes and childNodes are lost.

I tried to use collapsed attribute and maxLevels. Both ways did not work.

code:
https://codesandbox.io/s/fragrant-morning-5b1he?fontsize=14&hidenavigation=1&theme=dark

There is a bottom on the top for the feature I want.

**Comment by zeroin** [comment]
I checked your demo, clicked on button twice and I always get the same result, I event made a printscreen to compare it - all the links were the same.

**Comment by XGuGu** [comment]
Hi @zeroin ,
Thanks for your response. In the demo, can you try to click once(collapse all the nodes). Then, reopen the nodes manually. You will find the obvious difference.

**Comment by zeroin** [comment]
Oh, I see now. 
I need to think how to fix this issue, meanwhile I can recommend this workaround - do not set nodes as collapsed initially, instead make them inactive, like this:

```
    networkSeries.events.on("ready", ()=>{
      networkSeries.nodes.each((node)=>{
        node.isActive = false;
      })
    })
```

I will let you know when I'll find a better solution.

**Comment by XGuGu** [comment]
Thanks you @zeroin . This solution really help a lot!
