### ISSUE TITLE
Question: Is it possible to set pattern on chart through config?

### ISSUE THREAD

**Issue by prostoandrei** [amcharts/amcharts4#1952]
Hello!

I found articles about patterns at docs https://www.amcharts.com/docs/v4/concepts/colors/#Patterns.
I want to set a pattern for axisRanges.
Is it possible to set a pattern as a part of the config? Something like this:

```js
const axisRanges = [{
    date: new Date(2019, 10, 10),
    endDate: new Date(2019, 10, 25),
    // here
    axisFill: {
        pattern: {
            width: 10,
            height: 10,
            stroke: 'red',
            strokeWidth: 2,
            rotation: 45,
        },
    },
}];
```

Thank you!

**Comment by prostoandrei** [comment]
I want to make something like that:
![image](https://user-images.githubusercontent.com/7234499/70329083-98006d00-184b-11ea-9094-c13425190a6b.png)

But I'm not sure about the right way to do that.

**Comment by martynasma** [comment]
I'm assuming you are using JSON config.

Patterns are objects of type `Pattern`, you can't simply use a basic JS object, so you need to specify object type. There's also no such property as "pattern", you need to set patterns to `fill` property.

Something like this:

```
const axisRanges = [{
    date: new Date(2019, 10, 10),
    endDate: new Date(2019, 10, 25),
    // here
    axisFill: {
        fill: {
            type: "LinePattern",
            width: 10,
            height: 10,
            stroke: 'red',
            strokeWidth: 2,
            rotation: 45,
        },
    },
}];
```

**Comment by prostoandrei** [comment]
Yes, It helped me :) Thank you!
