### ISSUE TITLE
peer deps are missing

### ISSUE THREAD

**Issue by dad-of-ma-gr** [amcharts/amcharts4#1954]
The current amcharts package uses canvg 2.0.0 but it is not mentioned as peer Dep but is included in the amcharts directly.

But canvg requires 3 peerDeps:
 "peerDependencies": {
    "canvas": "^2.1.0",
    "jsdom": "^13.0.0",
    "xmldom": "^0.1.27"
  },

My npm now say I'm missing canvas and jsdom package, because canvg needs it.
But for me it is a bit strange, i don't have to add canvg to my deps but the peers of it?

Wouldn't it be better to include this packages also directly into amcharts or to "force" the user to also add the canvg ref to his code-base?

**Comment by Pauan** [comment]
The `canvas` and `jsdom` packages are only needed if you are using Node.js, they are not needed for the browser. The reason they are `peerDependencies` is so that way they won't be installed if you are targeting the browser. So you can safely ignore the npm warnings.
