### ISSUE TITLE
PieChart3D Export API Error with Custom Colors - canvg.js IndexSizeError

### ISSUE THREAD

**Issue by marcusr21** [amcharts/amcharts4#1957]
### Issue Summary
When using custom colours defined in a JSON payload for PieChart3D / PieSeries3D we are unable to export the chart due to a canvg.js error - IndexSizeError: Index or size is negative or greater than the allowed amount.

Our custom colours are passed dynamically through JSON (PHP) as we repeat the same chart twice to show a Before and After.

### Pie Chart 3D Creation
```
sectorPieBefore = am4core.create('sectorPieBefore', am4charts.PieChart3D); 
      sectorPieBefore.dataSource.url = URL;
      sectorPieBefore.innerRadius = am4core.percent(30);
      sectorPieBefore.depth = 150;
      sectorPieBefore.legend = new am4charts.Legend();
      sectorPieBefore.exporting.menu = new am4core.ExportMenu();
      
var series = sectorPieBefore.series.push(new am4charts.PieSeries3D());
      series.dataFields.value = 'value';
      series.dataFields.depthValue = 'value';
      series.dataFields.category = 'sector';
      series.slices.template.propertyFields.fill = 'colour';
```
### Export Through API
```
  var chartPromise1 = sectorPieBefore.exporting.getImage("png", options).then( (data) => {
      chart1 = data;
      var split = chart1.split(",");
      var newChart1 = decodeURIComponent(split[1]);
      form.append($("<input>").attr("type", "hidden").attr("name", "chart-1-svg").attr("value", newChart1));
      console.log("chart 1 svg = " + newChart1);
    } );
```
### Chart CSS
```
#sectorPieBefore{
  width: 100%;
  min-height: 600px;
  /* display: none; */
}
```

When changing the pie chart from 3D to 2D this works as expected immediately. Is there something wrong with my CSS or there is a deeper bug in the rendering of the canvas?
Many thanks for all your help in advance.

**Comment by martynasma** [comment]
I can see you are specifying the `propertyFields.color` to a field in data. Do you by any chance specify values there as hex strings or as proper `Color` objects?

If you could post your whole chart code/data, that would be easier for us to figure this out.

**Comment by marcusr21** [comment]
We use hex strings (e.g. `$color = "#FFA500"`) as the data is created on the PHP server before pushing a `json_encode` array back to the client side.

**Comment by marcusr21** [comment]
https://codepen.io/marcusr21/pen/MWYyGZa 
An example of what we're running

**Comment by martynasma** [comment]
The export works fine on your CodePen in all browsers.

Could you please set it up so that we can reproduce the error?

**Comment by marcusr21** [comment]
Hi,

I've updated the codepen to include the exporting link. I'm not expecting an image to come out but as you can see there is no data being logged in the console. This is similar to the behaviour on our website.

**Comment by martynasma** [comment]
This is what I'm getting after click in FireFox:
![image](https://user-images.githubusercontent.com/1458520/70980460-0b13aa00-20bc-11ea-86b2-a6b44035bb49.png)

And this is Chrome:
![image](https://user-images.githubusercontent.com/1458520/70980500-1961c600-20bc-11ea-8e6d-51c7606779c3.png)

Seems pretty consistent in that in both browsers I get "Work" prompt, and then some JS error, which originates in code of the click handler, not amCharts. Are you seeing some different error?

**Comment by marcusr21** [comment]
Yes, when we export your 3D chart we receive the following error: 

![image](https://user-images.githubusercontent.com/7628312/71073177-c4838580-2177-11ea-9714-3c939c36157f.png)

**Comment by martynasma** [comment]
What version of FF are you using?

**Comment by marcusr21** [comment]
71.0 (64 bit)

**Comment by martynasma** [comment]
Same here. Different error. Weird :)

Have you tried clearing your browser cache?

**Comment by marcusr21** [comment]
Yes we have, weirdly enough it always works on a 2D Pie Chart with custom colours as hex strings. But when trying to use a 3D Pie Chart and append it to a form to submit to the backend, that's when we get the IndexSizeError. Almost as if the canvas is too big?

**Comment by martynasma** [comment]
Still can't reproduce this. Let me know if you figure out a way to repro this.
