### ISSUE TITLE
Resizing breaks country center.

### ISSUE THREAD

**Issue by BesoKakulia** [amcharts/amcharts4#1958]
Map charts, centered using  `deltaLongitude`, lose center after resizing, [example](https://www.loom.com/share/457cdcfcc6064e9ab8b09bfd80a6dfe3). Do you have any idea how can I fix it? deltaLongitude stays -90 beside the wrong position.
```
      // Center wide countries
      if (['russia', 'newZealand', 'asia'].includes(mapSettings.identifierName)) {
        mapChart.deltaLongitude = -90
      }
```

**Comment by martynasma** [comment]
Can you provide a working example of this? I'm having issue reproducing the issue you have described.
