### ISSUE TITLE
Angular 8.1.2 build error

### ISSUE THREAD

**Issue by SegoviaDiego** [amcharts/amcharts4#1960]
Hi!

I'm trying to use `Amcharts 4.7.0` in my `Angular 8.1.2` project but when I try to build it in production mode the compiler throws this error:

```
ERROR in /Users/dsegovia/Desktop/projects/SKYFRAME/packages/angular/node_modules/@amcharts/amcharts4/.internal/core/export/Export.js 69:24
Module parse failed: Unexpected token (69:24)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js
You may need an additional loader to handle the result of these loaders.
|             switch (_a.label) {
|                 case 0: return [4 /*yield*/, Promise.all([
>                         import(/* webpackChunkName: "pdfmake" */ "pdfmake/build/pdfmake.js"),
|                         import(/* webpackChunkName: "pdfmake" */ "../../pdfmake/vfs_fonts")
|                     ])];

```

I already tried to use `----build-optimizer=false` but it does not work.

Versions:
- `Angular 8.1.2`
- `Amcharts 4.7.0`

**Comment by xorspark** [comment]
This appears to be the same issue as mentioned in #868, which is a result of a bug in Webpack v4.29.x. We touch on this in our [using webpack guide](https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/) and recommend to either try an older webpack version or updating the acorn package. Give those solutions a try and see if that helps.

**Comment by kavishsoam** [comment]
try build optimser false

use ng build --prod --build-optimizer=false
