### ISSUE TITLE
Toggle series Tooltip when click on chart instead of appearing on hover

### ISSUE THREAD

**Issue by Muzzamil1** [amcharts/amcharts4#1962]
Hi there,
I tried to find an example in docs to hide and show multiple series tooltip when clicking on the chart instead of showing tooltips when hovering but was not able to find one.
Is it possible to toggle the series tooltip with click event?

**Comment by martynasma** [comment]
Sorry for the late reply. Here's a demo that does that:
https://codepen.io/team/amcharts/pen/QWwmPVO?editors=0010
