### ISSUE TITLE
Toggle legend not working properly after set legend data

### ISSUE THREAD

**Issue by quangdnptit** [amcharts/amcharts4#1963]
Hi Amchart4 team, I have 1 issue about toggle legend not working after set custom legend data, please take a look: https://codepen.io/quangdnptit/pen/mdyPpEp

For example: When I turn off "Europe" in legends, Europe series not hidden as well
if I remove custom legend data, toggle action work fine
please help. thanks

**Comment by zeroin** [comment]
When you set custom data on your legend, it looses all the events and links with the series. So you either need to create all the hit listeners yourself or use default one.

**Comment by quangdnptit** [comment]
ya, thank you, I got it
