### ISSUE TITLE
Best practise handle font size scaling when chart is resized

### ISSUE THREAD

**Issue by Masus** [amcharts/amcharts4#1964]
I've created a "donut" graph that displays the summary in the middle based on the tutorial provided here: [sum-label-inside-a-donut-chart](https://www.amcharts.com/docs/v4/tutorials/sum-label-inside-a-donut-chart/).

I have set the font size to a fixed value (60) but I want the text in the middle to scale based on the width and height of the div container the graph is placed in.

I've tried playing around with the "vw" css attribute but it only works for the viewport (not the actually div container).

One possible way is to use the sizechanged event on the chart and do the calculation manually but this will gets very tedious, complex and time consuming fast.

I haven't found any way for amchart to handle the scaling for me automatically.

What is the recommend practises to handle scaling relative the container of the chart (or the size of the chart itself)?

**Comment by zeroin** [comment]
I am afraid your suggested method is the only way to do it.

**Comment by Masus** [comment]
@zeroin Ok! Thanks for the fast reply!

**Comment by Paradox7208** [comment]
I know this has been closed, but I thought I would provide some code that I wrote to achieve the scaling functionality.

https://github.com/Paradox7208/AMCharts4Helpers/blob/master/ChartBuilderService.js

Example trigger:
chart.events.on('maxsizechanged', scaleGaugeChartLabels);
