### ISSUE TITLE
Issue when individual chart themes are applied

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#1966]
Question/Issue 1
---
A previous issue explained that individual chart themes isn't in the works (unfortunately): https://github.com/amcharts/amcharts4/issues/865.

My issue is the time at when a chart theme is applied. Initially I tried something like the following:
```
function initChart(<params>) {
  if (isAnimated) {
    am4core.useTheme(am4themesAnimated); // enable animation for this chart
  }
  const chartInstance = am4core.create(element, instanceType);
  if (isAnimated) {
    am4core.unuseTheme(am4themesAnimated);
  }
  return chartInstance;
}

function updateChart(chartInstance) {
  // then do all the chart configs, like setting data and such
}
```

In this example, the animations never ran. I'm assuming this is because the theme isn't actually attached until the update cycle (from what I can tell in the amcharts source code).

So, my next thought was to do something like:
```
function initChart(<params>) {
  if (isAnimated) {
    am4core.useTheme(am4themesAnimated); // enable animation for this chart
  }
  const chartInstance = am4core.create(element, instanceType);
  chartInstance._isAnimated = isAnimated;
  return chartInstance;
}

function updateChart(chartInstance) {
  // then do all the chart configs, like setting data and such
  if (chartInstance._isAnimated) {
    am4core.unuseTheme(am4themesAnimated);
  }
}
```

This works great for one chart, or if I add charts sequentially where each chart has to update data and such before the next one is initialized. This appears to be the intended example as described in the docs.

However, if there is any asynchronous process between the charts (which is absolutely necessary in our application), then this logic breaks down. This is because the unuseTheme could be called by one chart before another chart has all of its configs set, thus potentially none of the charts would get the animation theme. In this example: https://recordit.co/NXqVmvX4ny, the first two charts have the animation theme and the second two don't. You can see something is maybe trying to happen, but is intermittent at best, sometimes never animating (due to async timing).

While there may be no priority on doing theming at an individual chart level, would it be possible to at least update the theme application to happen within the chart creation (first example), instead of the update cycle?

It seems in both the first example, or in individual chart themes, it would be easy enough to make a copy of the theme per chart at chart creation and have the chart reference those copied variables instead of the ones in registry.themes.

Question/Issue 2
---
Is there a way to cause the chart to re-animate when data is replaced? The example here: https://www.amcharts.com/docs/v4/concepts/data/#Replacing_whole_data_set animates upon render, but not when switching the data set.

**Comment by zeroin** [comment]
I am afraid we do not have plans for this. The reason is simple - the theme is applied at the moment some object is created. When object is created it might not have any reference to a chart or parent or anything, it might be create by the user like: new SomeObject(). The theme can not be applied later as it would mess up user defined properties. 

As for the second question - you can initiate animation of series or some other object by calling `series.appear()`

**Comment by runfaj** [comment]
@zeroin That seems like a bigger use case for allowing the user to manually call a setTheme/unsetTheme on an individual object. Keeping a global theme is essential, but the ability for a user to manually override that as needed per chart seems just as essential. We'll make do with what's available right now, but really hoping that this can be added as a future feature.
