### ISSUE TITLE
`renderer.labels.template.location` is ignored on DateAxis

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#197]
It's currently impossible to set location of the axis labels on a `DateAxis`, because it is being overwritten by axis [fuzzy logic](https://www.amcharts.com/docs/v4/concepts/axes/#Labels_on_Date_axis).

The following has no effect:

```
dateAxis.renderer.labels.template.location = 0;
```

Example:
https://codepen.io/team/amcharts/pen/9c5d4bee8779aaae80b53566b97b42a0/

**Comment by zeroin** [comment]
In next update labels will pay attention to location when label will represent full period between grid lines, otherwise it will be shown on the grid.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.41](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.41).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
@jochenjonc 

It doesn't look like you are setting any location for labels on your data axis.

Try this:

```
dateAxis.renderer.labels.template.location = 0;
```

**Comment by jochenjonc** [comment]
@martynasma that fixes it. Thx.
