### ISSUE TITLE
Custom field in a tooltip bug

### ISSUE THREAD

**Issue by pivasikkost** [amcharts/amcharts4#1970]
I use multiple series with groupping and custom variable in a tooltip on 4.7.7-4.7.14, and find a bug.
```
series.dataFields.valueY = 'someFieldName1';
series.dataFields.openValueY = 'someFieldName2';
series.name = 'someTitle';
series.tooltipText = "{name}: [bold]{valueY}[/]" + "{openValueY}";
```
For some reason, an attempt to use any other name of a non-standard variable excerpt "openValueY" gives an error in the core.js file "TypeError: Cannot read property 'value' of undefined". Although earlier this functionality worked, at least on version 4.6.5, and it is described in the documentation https://www.amcharts.com/docs/v4/tutorials/custom-static-multi-value-tooltip/ (first code pen) .
Please, fix it.

**Comment by zeroin** [comment]
Could you provide a codepen with this can be reproduces?
Here is the one where I tried to reproduce the described:
https://codepen.io/team/amcharts/pen/cbc090532a78d5014cdae6b437fbd719

It worked fine, no error. So I need your help here, thanks!

**Comment by zeroin** [comment]
I also tried it with the candlestick codepen: https://codepen.io/team/amcharts/pen/MxaywM

**Comment by pivasikkost** [comment]
Here is https://codepen.io/pivasikkost/pen/BayQbma .
Also, as you can see, it’s strange that dates are substituted every 15 minutes, and draws them every 10/20 minutes.

**Comment by zeroin** [comment]
OK, so one problem is that you try to set custom field on your series. This can not be done, as it tries to set some value on data item which is not there. Custom values can be used, but without setting them as fields. When you use them in tooltip, they are extracted directly from your raw data object. 
So this will work:
`series.tooltipText = "{name}: [bold]{valueY}[/]  {" + field + "_sum}";`

But only if you do not use data grouping. Data grouping and custom fields will not work, as one grouped data item can have multiple data contexts inside and it's quite unclear from which one we should extract data and what we should do with it. Custom fields work well with non-grouped data only. 

Here is a modified pen:
https://codepen.io/team/amcharts/pen/407b5052e3af66f41a653dfac57491dd

**Comment by pivasikkost** [comment]
But in 4.6.5 I can use custom values with setting them as fields. And custom value 'openValueY' works in my pen. And custom values 'lowValueY' or 'highValueY' works in pen from documentation and your second pen. And in my pen, they do not work, even with grouping turned off. So the reason is something else.
And due to the fact that time intervals get confused when using grouping (although the values do not have time intervals of 10 and 20 minutes at all), I want to say that this is not normal, and the grouping behaves incorrectly too. In version 3, the grouping worked correctly.
Also, you did not comment on the overestimated upper limit on the chart when using the 'openValueY' custom field (the maximum value is 7000, and the last digit is 12000 on the axis).

**Comment by zeroin** [comment]
openValueY is not custom, it is one of possible valueFiels of XYSeries:
https://www.amcharts.com/docs/v4/reference/ixyseriesdatafields/

The candlestick codepen also uses only allowed value fields:
https://www.amcharts.com/docs/v4/reference/icandlestickseriesdatafields/

It was indeed working, but more by a coincidence. I checked why it is no longer working and found the problem, so it will work again since next release, but it is unsupported thing (you would even get error if you'd work in typescript). And it will not work with `dataGrouping = true`.

The grouping to 10 and 20 minutes happens because default grouping intervals are:
```
			{ timeUnit: "millisecond", count: 1 },
			{ timeUnit: "millisecond", count: 10 },
			{ timeUnit: "millisecond", count: 100 },
			{ timeUnit: "second", count: 1 },
			{ timeUnit: "second", count: 10 },
			{ timeUnit: "minute", count: 1 },
			{ timeUnit: "minute", count: 10 },
			{ timeUnit: "hour", count: 1 },
			{ timeUnit: "day", count: 1 },
			{ timeUnit: "week", count: 1 },
			{ timeUnit: "month", count: 1 },
			{ timeUnit: "year", count: 1 }
```

So you should modify them and leave only the ones you need, for example:

```
	dateAxis.groupIntervals.clear()	
  dateAxis.groupIntervals.pushAll([
			{ timeUnit: "hour", count: 1 },
			{ timeUnit: "day", count: 1 },
			{ timeUnit: "week", count: 1 },
			{ timeUnit: "month", count: 1 },
			{ timeUnit: "year", count: 1 }
		]);  
```

I actually see 8000 as a max value of the axis, can you confirm you get 12000?

**Comment by zeroin** [comment]
We are also thinking how to solve custom fields problem with dataGrouping, maybe we will add some additional legal data fields for that purpose, I will let you know.

**Comment by zeroin** [comment]
We released an update today (v 4.7.16). And we made changes which should solve the issues:

1) we added one `customValue` dataField to XYSeries. So you can use it even with data grouped and you can even tell which calculated value should be used when data is grouped, for example:

```
    series.dataFields.customValue = field + "_sum";
    series.groupFields.customValue = "sum";
```
means that when data is grouped, all the customValues in the period will be summed.
A demo: https://codepen.io/team/amcharts/pen/3cac6475b1e4ac2845aa92dc2750b6d1

Besides, we copy all the properties/values from raw data item to the dataContext of the grouped data item, which means that you will be able to access last occurrence of all the fields in the grouped data item. So for example, if you set your tooltipText to:

`series.tooltipText = "{name}: [bold]{valueY}[/]  {field9_sum}";`

when data is not grouped, it will show the actual `field9_sum` value of each data item.
when data is grouped, it will show the last `field9_sum` value in the grouped period.

I hope these changes will solve your issues.

**Comment by pivasikkost** [comment]
Well thank you. Could you then explain in more detail what the 'openValueY' field is for? This is when setting the series values to about 12000 into it, the border was shifted, I edited my pen  https://codepen.io/pivasikkost/pen/BayQbma.

**Comment by zeroin** [comment]
`openValueY` is used by LineSeries in case you want to have a fill not to the base axis but to some other values, like in this chart: https://www.amcharts.com/demos/range-area-chart/

So if you set this field, it is included when calculating min/max values.

**Comment by pivasikkost** [comment]
Thanks. At the moment, this functional is enough for me.
