### ISSUE TITLE
How to set a data gap default value ?

### ISSUE THREAD

**Issue by blackjak231** [amcharts/amcharts4#1972]
Hello,

I would like to know how to apply a default value to a data gap in line graphs. Right now if i do not apply data gaps I have continuous lines displayed which can cause problems when reading the chart.

This has been done in [amchart 3 as a plugin ](https://codepen.io/team/amcharts/pen/cf086d66eee0381fcd45aaa099eced33)and i would like to do it in amchart 4.

Thank you !

**Comment by martynasma** [comment]
There's no way to automatically treat gaps in data as zero values, but to implement custom data processor, which augments the source data with data items with zero values.

You can do so on `beforedatavalidated` event. E.g.:

```
chart.events.on("beforedatavalidated", function(data) {
  // iterate through data and add zero data points in gaps
  // ...
});
```

I'm afraid I don't have a ready-made example for it, though.

**Comment by blackjak231** [comment]
Hey @martynasma, 

Thank you for your response, it answers my question and its enough for me to work with :)  I'll simply see if I do the processing on server side or client side now (not many data so both are good).

Thanks again.
