### ISSUE TITLE
Cropped legend items

### ISSUE THREAD

**Issue by irekrog** [amcharts/amcharts4#1973]
Hi, I have a problem with cropped legend .

When I set `maxWidth` to 300px then last characters of first item on the legend are cropped. I think "cropped" word should be move to the next line

Here is an example:

https://codepen.io/irekrog/pen/BayzXeq

**Comment by martynasma** [comment]
It seems that "cropped" still does fit into the 300px you have hardocded, hence it not being wrapped.
