### ISSUE TITLE
Parent chart is listening for events of chlidren / embedded chart

### ISSUE THREAD

**Issue by ThibaultFoureur** [amcharts/amcharts4#1974]
Hello,

I'm working on a chart that consist of a force directed tree but with a donut chart around the main node that disappear when it's expanded.

const series = chart.series.push(new ForceDirectedSeries());
const pieChart = series.nodes.template.createChild(am4charts.PieChart);

But the problem is that a hit on one of the slices is also considered as a hit on the main node...

pieSeries.slices.template.events.on('hit', function (ev) {}) 
is triggered at the same time as
series.nodes.template.events.on('hit',function (ev) {})

Is there a way to disable the parent from listening to children events ?

**Comment by martynasma** [comment]
Yes, try this:

```
series.nodes.template.events.of('hit');
```
