### ISSUE TITLE
How to set gray out (inactive) for series on the line chart

### ISSUE THREAD

**Issue by havietduc91** [amcharts/amcharts4#1976]
Hi Amcharts team,

How we can set gray out (inactive) for series on the line chart?

Like the below image:
![how to set gray out for series](https://user-images.githubusercontent.com/4966192/70902957-6dbf6400-2030-11ea-8985-58949d59dc5f.png)

Please correct me in this [link](https://codepen.io/havietduc91/pen/ExaNVXE?&editable=true)

Many thanks,

**Comment by zeroin** [comment]
Here is a demo:
https://codepen.io/team/amcharts/pen/70104ecd24a447be88fd1fd9bd950a44?&editable=true

You can of course use any other event, not hover to highlight series.

**Comment by havietduc91** [comment]
Yep, that's sound great, thank you a lot!

**Comment by havietduc91** [comment]
Hi @zeroin 
I'm used this code to set inactive series, it's work
```
makeHoverable(series2);

function makeHoverable(series) {
  series.strokeOpacity = 0.3;
}
```
But when we set inactive for all series after that with the below code, it's not working
```
function setInactiveForAllSeries() {
  chart.series.values.forEach(function(series) {
    series.strokeOpacity = 0.3;
  });
}
```
Please take a look the below image and correct me in this [LINK](https://codepen.io/havietduc91/pen/qBEqJom)

![why inactive all series is not working](https://user-images.githubusercontent.com/4966192/71144274-0f70cc00-2250-11ea-93f6-b4a4ef086105.png)

Many thanks

**Comment by zeroin** [comment]
This is a bit complicated, but this should work:

`series.segments.template.strokeOpacity = 0.3;`

**Comment by havietduc91** [comment]
yeah, it works as my expected, thank you a lot
