### ISSUE TITLE
Cannot zoom into minutes/seconds when using mouseWheel zoom on large data sets

### ISSUE THREAD

**Issue by wotway84** [amcharts/amcharts4#1978]
When using a data set of for example 3 months with the values at intervals of 5 minutes, it does not zoom in further than an hourly range when using mouse scroll zoom. Using the cursor to zoom however does zoom in further to seconds intervals. The problem only seems to be with the mouse scroll.

https://codepen.io/wotway84-snow/pen/gObLwRm

I have tried different baseInterval and gridInterval settings with no success.

**Comment by zeroin** [comment]
I confirm it's a bug, will try to fix it. By the way, you should avoid adding two data items with exactly the same dates to the chart.data. If you'd remove the `baseInterval`, having multiple items with the same dates would result an error. You either combine data item into one or set it on series instead of a chart.

**Comment by wotway84** [comment]
thanks for the fast response and the advice. I will change my script to add data to each series instead.

**Comment by wotway84** [comment]
another question related to this.
When zooming using mouse wheel scroll  it jumps from 1 week to 1 day.
The grindIntervals default list includes the following and so i thought it should jump from 1 week to 5 days first ,then 4 days etc:
 { timeUnit: "day", count: 1 },
  { timeUnit: "day", count: 2 },
  { timeUnit: "day", count: 3 },
  { timeUnit: "day", count: 4 },
  { timeUnit: "day", count: 5 },
  { timeUnit: "week", count: 1 },

Is this also a bug?

**Comment by martynasma** [comment]
This should have been fixed in the latest version 4.7.17.

I'm closing this, but feel free to reopen if you still having issues after upgrading.

**Comment by wotway84** [comment]
really appreciate the fast response on this. Thanks, it works great now!
