### ISSUE TITLE
Binding properties to data generated in application backend

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#1981]
I have a recurring problem related to the generation of my data sets in the application backend. I want to set some properties with `dataFields` and `propertyFields`, however it is thus not possible to use functions like `am4core.percent()`, `am4core.color()`, etc.

For example, if a "width" field is defined in a dataset like so:
```javascript
[{name: "foo", value: "bar", width: 20},{...},{...}]
```
Is there a way to set the width of series in a way allowing to retrieve and modify the value associated with the field "width" like so (i.e. without having to loop through the data set to access individual values):
```javascript
series.propertyFields.width = am4core.percent("width")
```
I hope my explanations are not too confusing. Thank you for your help!

**Comment by martynasma** [comment]
You may use strings with a percent sign in you data:

```
[{name: "foo", value: "bar", width: "20%"},{...},{...}]
```

There's casting in place that should detect such strings and convert them into `Percent` properly.

**Comment by Segolene-Albouy** [comment]
Thanks! That's great :)
