### ISSUE TITLE
Stacked chart displayed many tooltips when using chart cursor

### ISSUE THREAD

**Issue by quangdnptit** [amcharts/amcharts4#1983]
Hi amcharts4 team, I try to add **cursor** for stacked chart but facing the big problems "tooltips display many times"
I added cursor by:
**chart.cursor = new am4charts.XYCursor();
chart.cursor.lineY.disabled= true;
chart.cursor.lineX.disabled= true;** 

the results: 
![image](https://user-images.githubusercontent.com/31880059/71065767-76d14200-21a4-11ea-89bd-39a3cafcc9e2.png)

Note: this code above work fine on the line chart
Please help, thank you

More details, please see the link below
 https://codepen.io/quangdnptit/pen/ZEYLLOp

**Comment by martynasma** [comment]
To solve tooltip overlapping, set `tooltipText` directly on series, not on column template.

```
series.tooltipText = "[bold]{name}[/]\n[font-size:14px]{categoryX}: {valueY}";
```

https://www.amcharts.com/docs/v4/concepts/chart-cursor/#Series_tooltips
