### ISSUE TITLE
How to sort the legends with a different order than series in stacked columns chart.

### ISSUE THREAD

**Issue by quangdnptit** [amcharts/amcharts4#1984]
Hi amcharts4 team, how can I sort the legend with a different order than series? any idea for that? please help, thank you

**Comment by martynasma** [comment]
Do you mean reverting the order or using completely custom order?

**Comment by quangdnptit** [comment]
yeah, I want to build the legend with a different order of series
For example: 
order of series: s1 s2 s3 s4 s5

order of legend: lg1 lg3 lg2 lg4 lg5
is it possible?

**Comment by martynasma** [comment]
Challenge accepted :)

https://codepen.io/team/amcharts/pen/bGNgXYg

**Comment by quangdnptit** [comment]
Ops, I mean the series of the stacked chart, sorry for miss information

**Comment by martynasma** [comment]
OK, so it's not about legend at all?

**Comment by quangdnptit** [comment]
yeah, I want to build the stacked chart with the order of series different than the order of legend

**Comment by martynasma** [comment]
OK, so the proposed solution still works.

You add series in the order you want them to appear in plot area, and you apply the solution I proposed to order Legend items differently.

**Comment by quangdnptit** [comment]
yeah, thank for yours support
