### ISSUE TITLE
How to differentiate between "hit" and "doublehit" events

### ISSUE THREAD

**Issue by dharunkumar** [amcharts/amcharts4#1987]
Is there any way to differentiate between hit and doublehit events, as I need to trigger different functions for each of these events, but if I intend to double click, it also triggers hit as well, any way to handle this issue?

**Comment by martynasma** [comment]
No, I'm afraid. There's no way to disable first "hit" event. If that was the case we would have to delay "hit" event and wait if there will be a second click afterwards. That results in unresponsive bad UX :/

You can easily solve this by delaying whatever your hit action is supposed to do for 300ms or so, and cancel it if "doublehit" occurs.

**Comment by kolle1986** [comment]
still not possible?

**Comment by DevMazen** [comment]
Sure we can .

Try this :
For doublehit on series :
  series.slices.template.events.on("doublehit", function (ev) {
           console.log( ev.target.dataItem.category); 
   });

for one hit on series 
  series.slices.template.events.on("hit", function (ev) {
         console.log( ev.target.dataItem.category); 
   });
