### ISSUE TITLE
mysterious empty space on main chart container

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#1988]
I'm trying to figure out what might be causing this space that appears on a chart.

![](http://g.recordit.co/twTjyrOb0Q.gif)

You can see in this gif that the root element for an xychart has a height of 473, but the direct chartContainer element underneath is 458 tall.

Here's what I have in the config:
- The chart is auto calculating all heights/widths to the parent (just default 100% fill).
- All of my margins are default configurations (meaning I haven't defined any in my config)
- The only padding I have defined aside from defaults is the chart.paddingBottom as 0. 
- I have no custom widths defined that might affect this (e.g. on the rotated labels).
- I have no custom heights defined.
- The only dy config I have defined is -12 on the category labels if they are rotated the 45deg. Experiments on removing this appear to not affect the container at all.

So I'm stumped on why the chart might be calculating this extra spacing of 15. What I do know is that the spacing is always 15 different, regardless of how tall my chart containing div is. However, I can't figure out where this 15 is actually coming from.

Another thing I noticed. If I set chart.paddingBottom to -15 while a chart has labels, it looks good:

![image](https://user-images.githubusercontent.com/3292053/71187644-b0ee2280-223c-11ea-83c1-23fecd357323.png)

However, on my mini version of the chart where the labels are hidden, that config just makes the bottom axis disappear and look bad:

![image](https://user-images.githubusercontent.com/3292053/71187610-9fa51600-223c-11ea-83f3-e11026a2db96.png)

So, the best solution appears to be with the following logic:
```
if (axisEnabled) {
    chart.paddingBottom = -1 * chart.paddingTop; // this doesn't make any sense in the css world, but apparently does in amcharts world
  } else {
    chart.paddingBottom = 0;
  }
```

I'm fine using this, but it seems pretty hacky. So I'm wondering if there is a better thing I should be adjusting that I don't know about, or is it just a result of how amcharts calculates things?

**Comment by martynasma** [comment]
The chart itself has a default `paddingBottom`, so you should remove that.

Also, axis labels can have padding of their own, so when whole height of the axis is measured, that goes into account. So you might want to disable padding of labels as well.

If you could post your chart as a CodePen, I could take a look if there's maybe something else.

**Comment by runfaj** [comment]
@martynasma I'd love to post a codepen, but our chart configs are generated on the fly, so unless there's a way to export the config from the chart, I'm a bit stuck on that one. I'll take a look at the label padding to see if that might be affecting things.

**Comment by martynasma** [comment]
There is no such thin, I'm afraid :(

Even though your charts are generated on fly, I'm sure some code is there, that can be ported to a static chart.
