### ISSUE TITLE
variable radius pie chart issue

### ISSUE THREAD

**Issue by XGuGu** [amcharts/amcharts4#1989]
Hi team,

Is it possible to set minimum radius for the variable radius pie chart ? It is not looking good when the data has huge difference. 
<img width="614" alt="Screen Shot 2019-12-19 at 2 13 09 PM" src="https://user-images.githubusercontent.com/39609237/71206420-1f95a500-226a-11ea-8cd5-01439776cfb9.png">

**Comment by martynasma** [comment]
Yes, you can use an adapter for that:

```
series.slices.template.adapter.add("radius", function(radius) {
  return radius < 50 ? 50 : radius;
});
```

**Comment by XGuGu** [comment]
Thanks for the help! It works.
