### ISSUE TITLE
In Firefox, clicking mapImage/Circles to open popups causes weird zoom/pan

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#199]
![20180803-amcharts-v4-popup-pan](https://user-images.githubusercontent.com/2334143/43668353-76196774-974a-11e8-9d8a-11d6f1c234db.gif)

[pen](https://codepen.io/notacouch/pen/fd55e791810b7d2b0721b0515418f0a7?editors=0010), [live](https://codepen.io/notacouch/live/fd55e791810b7d2b0721b0515418f0a7)

Steps to reproduce:

In Firefox:

1. Zoom into France a bit,
2. Click different or even the same cities until bug occurs

**Comment by martynasma** [comment]
Indeed a bug. Funky.

And it seems that it IS indeed related to Popup, which is weird since Popups don't do anything with zoom.

**Comment by notacouch** [comment]
Yeah I was wondering if it was related to click events and/or overlaying of series, but none of the click events were triggered. In this pen there are no overlaying series, even, let alone click events! Bizarre. 

It seems related to the issue of the flash of scrollbars on popup creation, though. Could be while adding the popup, it is in the undocument and unstyled for a split microsecond (lol), and this somehow causes some kind of redraw on the chart??? I don't know.

**Comment by martynasma** [comment]
This does not seem to be happening locally with the dev version, though. So it might be something that we inadvertently fixed already. OK yeah that happens :)

Let's revisit this when we release the next version.

**Comment by martynasma** [comment]
4.0.0-beta.42 is out now.

I can't reproduce the centering issue in FF anymore. Let me know if you can.

P.S. on a totally unrelated note, that three markers in the North of France look like head of a Mickey the Mouse with oversized ears:

![image](https://user-images.githubusercontent.com/1458520/43683560-27c3849e-9897-11e8-8379-bff5de5cbd74.png)

**Comment by notacouch** [comment]
Yep, seems fixed on my end, too. Good stuff.

LOL @ Mickey Mouse

 :laughing: :rofl: :rofl: :skull: :coffin:
