### ISSUE TITLE
custom texts for NavigationBar on TreeMap

### ISSUE THREAD

**Issue by mauriciolauffer** [amcharts/amcharts4#1990]
I'm trying to change the default text for NavigationBar on TreeMap. I'm using the following code for it:

```
const chart = am4core.create("some_dom_id", am4charts.TreeMap);
chart.homeText = "Countries";
chart.navigationBar = new am4charts.NavigationBar();
chart.navigationBar.dataFields.name = "my_own_property";
```

![image](https://user-images.githubusercontent.com/443888/71215095-eeb97c80-230a-11ea-9df6-9d2e99aeb722.png)

It seems to work fine. However, homeText is ignored. How can I fix it? There is only basic examples of NavigationBar on amcharts website.

**Comment by xorspark** [comment]
Reposting from zendesk for greater visibility:

You can set a `text` adapter on the navigationBar's [activeLink](https://www.amcharts.com/docs/v4/reference/navigationbar/#activeLink_property) object when you drill down to customize the text using a different property from your data. For example:

```
// assumes babel/transpiling for ? chaning syntax
chart.navigationBar.activeLink.adapter.add("text", function(text, target) {
  // get the data item associated with the text link
  var dataItem = target.dataItem?.dataContext?.dataContext;
  if (dataItem) {
    return dataItem.my_own_property;
  }

  // otherwise return the default text (e.g. homeText)
  return text;
});
```

[Demo](https://codepen.io/team/amcharts/pen/f7c222d490f37f0c73c7ddc49630a46a?editors=0010)
