### ISSUE TITLE
[Question] Display DummyData on Exploded PieChart Tooltip 

### ISSUE THREAD

**Issue by jerryngm** [amcharts/amcharts4#1991]
Hi,
How can I access and display Cat_Total_Quantity and Product_Quantity on the Tooltip for the following JSON array? 
I have tried this:
```
pieSeries.slices.template.dummyData = "Product_List";
pieSeries.slices.template.tooltipText = "{category}\n[bold]{value} [/]\nQuanlity: {dummyData.Quantity}";
```
without success

Please assist. Thanks

```
[ 
   { 
      "Product_Cat":"Book",
      "Cat_Profit":10000,
      "Cat_Total_Quantity":58,
      "Product_List":[ 
         { 
            "Product_Name":"Book 1",
            "Product_Profit":100,
            "Product_Quantity":24
         },
         { 
            "Product_Name":"Book2",
            "Product_Profit":34000,
            "Product_Quantity":34
         }
      ]
   },
   { 
      "Product_Cat":"CD",
      "Cat_Profit":262000,
      "Cat_Total":116,
      "Product_List":[ 
         { 
            "Product_Name":"CD 1",
            "Product_Profit":18000,
            "Product_Quantity":9
         },
         { 
            "Product_Name":"CD 2",
            "Product_Profit":60000,
            "Product_Quantity":15
         }
 
      ]
   }]
```

**Comment by martynasma** [comment]
Define "Exploded PieChart" :)

Maybe you can just post full chart on CodePen/jsFiddle so that we can see what you're talking about?

**Comment by jerryngm** [comment]
I mean this one: https://www.amcharts.com/demos/pie-chart-broken-slices/
When you click on a slice the data from "Product_List" array will appear
This is my chart: https://codepen.io/jerryngm/pen/JjoWzyJ?&editable=true
Please have a look :)

**Comment by martynasma** [comment]
Thanks.

I suppose you don't need to refer `dummyData` (not sure what that would mean in this case anyway). The chart uses a custom function to generate data, so you're free to modify it the way you see fit. In this case you use either `Cat_Total_Quantity` or `Product_Quantity` to assign to universal field `Quantity` and use that in `tooltipText`.

Hope that makes sense.

Here's a modified chart:

https://codepen.io/team/amcharts/pen/7e0a0ef40af28ffc70c977b004db0e1b?editors=0010

**Comment by jerryngm** [comment]
Thanks for your support. That’s very useful. I thought I need to use DummyData as describe here https://www.amcharts.com/docs/v4/concepts/data/

Anyways, it works, I learn something new. Thank you very much, you’re legend!!
