### ISSUE TITLE
error TS2339: Property 'router' does not exist on type 'unknown'.

### ISSUE THREAD

**Issue by ER-GAIBI** [amcharts/amcharts4#1994]
Hi,

I use the map in amchart, and I want to call the angular Router to change the html pgae.

```
export class MarketComponent implements OnInit {

    constructor(
        private router: Router
    ) { }
    
    ngOnInit() {
    ........
    polygonSeries.mapPolygons.template.events.on('hit', function(event) {
            const country = (event.target.dataItem.dataContext as any).id;
            handleHover(event.target);
            this.router.navigateByUrl('/uk');
        });
     }
```

**I want to use router to change the html page when I clic on a country in the map.**

I got this error when I clic on a country in the map :
**ERROR TypeError: Cannot read property 'router' of undefined**

**Comment by martynasma** [comment]
Try adding a context for event handler:

```
polygonSeries.mapPolygons.template.events.on('hit', function(event) {
  const country = (event.target.dataItem.dataContext as any).id;
  handleHover(event.target);
  this.router.navigateByUrl('/uk');
}, this);
```

(notice the last parameter to `on()` method)

Hope this helps.

**Comment by ER-GAIBI** [comment]
Thank you @martynasma , you made my day better.
I had worked on this issue for more than one day, your proposition solved my issue.
