### ISSUE TITLE
can we do in amchart 4 version ?

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#1996]
![image](https://user-images.githubusercontent.com/54665162/71396431-1dec2880-2640-11ea-815b-c9ab0a31f1bb.png)

when i slide scrollbar with year, chart data updating to relevent year.
can we do in amchart 4 version ?
for refernce check the attachement image

**Comment by martynasma** [comment]
Such built-in time lines are not part of amCharts packaged. However, you can certainly implement your own and update chart's data dynamically.

Here's a tutorial about updated chart's data dynamically:
https://www.amcharts.com/docs/v4/concepts/data/#Dynamic_updates

Here's a TreeMap example that updates data:
https://www.amcharts.com/demos/dynamic-data-updates-on-treemap/

There's also a timeline slider example albeit with different chart type:
https://www.amcharts.com/demos/animated-xy-bubble-timeline-chart/

Hope this helps.
