### ISSUE TITLE
how to rotation title of value axis

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#1997]

**Comment by martynasma** [comment]
```
axis.title.rotation = 45;
```

**Comment by Mahisandy** [comment]
not working for this graph please check attachement
![image](https://user-images.githubusercontent.com/54665162/71415419-a0490c80-2681-11ea-95de-61d02d5d3c96.png)

**Comment by martynasma** [comment]
Make sure `rotation` is set **after** `opposite`:

```
valueAxis.title.text = "Value";
valueAxis.renderer.opposite = true;
valueAxis.title.rotation = 45;
```
