### ISSUE TITLE
Question: How to invert a duration series

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1998]
I am trying to achieve to show pace (duration) eg min/km but inverse the logic. 

here is an example 

<img width="811" alt="Screenshot 2019-12-24 at 15 52 15" src="https://user-images.githubusercontent.com/1268723/71417396-666a0d00-2665-11ea-81b3-eb823003cf06.png">

As you can see the longer the duration the higher the point in the yAxis as it's logical. 

How could one achieve a kinda inversed logic? 

I tried to set the renderer of the yAxis to inversed but that created not exactly what I wanted. 

It created this: 

<img width="817" alt="Screenshot 2019-12-24 at 15 54 26" src="https://user-images.githubusercontent.com/1268723/71417456-b77a0100-2665-11ea-9e44-5cfc9cf3c0c1.png">

Which is not exactly what I wanted. 

Here is for example what "other services do" 

<img width="741" alt="Screenshot 2019-12-24 at 15 55 25" src="https://user-images.githubusercontent.com/1268723/71417494-d4aecf80-2665-11ea-8bc0-ed25412071bb.png">

This is not a huge problem and I bet with time I ll think this through, but I just wanted to ask , if there was a simple out of the box solution. 

And hey thanks for the great work and happy holidays

**Comment by jimmykane** [comment]
Could one inverse the fill perhaps ?

**Comment by jimmykane** [comment]
:-O 

I think I did it. 

```
   yAxis.renderer.inversed = true;
      yAxis.baseValue = 6000;
```

**Comment by martynasma** [comment]
All set then? :)

**Comment by jimmykane** [comment]
YEs sir
