### ISSUE TITLE
Responsive Rules: Custom rules relevancy not working correctly

### ISSUE THREAD

**Issue by charlietoleary** [amcharts/amcharts4#1999]
I believe i have found a bug with the responsive rules feature.

I'm finding that when setting a more than 1 custom rule, if ALL of their "relevant" checks do not explicitly resolve to FALSE: then all the rules "state" methods are fired, even if the "relevant" check for that specific rule resolved to FALSE.

CodePen Example Here:
https://codepen.io/charlietoleary/pen/povrzoe

- This pen is forked from https://codepen.io/team/amcharts/pen/RBodeW which is on this page: https://www.amcharts.com/docs/v4/concepts/responsive/

- 2 custom responsive rules have been added, one that has a relevancy check that will always resolve to TRUE. The other will always resolve to FALSE.

- Both rules 'state' methods will fire, even though only one rule's "relevant" check passes.

Let me know if more info is required.

**Comment by martynasma** [comment]
Well, the state for the rule does get created, but are you sure it actually gets applied?

I wasn't able to get the state that relevant results `false` to ever get applied.

**Comment by charlietoleary** [comment]
Hi @martynasma,

If you check me codepen and open the JS console, you will be able to see the console logs for both 'state's even though one of their 'relevant' checks just plainly returns FALSE.

Check line 178 of the JS on the codepen to see the misbehaving rule.
`console.log('never fire');`

**Comment by martynasma** [comment]
Yes, but the `console.log()` is run when state for the rule is created, not when it is actually applied.

So even if you are getting "never fire" in console, it does not mean responsive rule is being actually applied to the chart.

Or do you think it is?
