### ISSUE TITLE
amcharts4 Waterfall chart question

### ISSUE THREAD

**Issue by quangdnptit** [amcharts/amcharts4#2003]
Hi amcharts4 team, how can I create this line for a waterfall chart? is it possible to create it by the library? 
![image](https://user-images.githubusercontent.com/31880059/71567925-79f9f580-2af5-11ea-8f3b-6da5e75633ea.png)
please help, thank you

**Comment by martynasma** [comment]
Well, not the arrow things, but at least labels you can do using axis ranges.

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_labels

Axis ranges are much more, but among other things they allow adding guide/label at certain position (category/value/date) on an axis.

**Comment by quangdnptit** [comment]
got it, thank you
