### ISSUE TITLE
Replacing the data messes up the chart

### ISSUE THREAD

**Issue by voger** [amcharts/amcharts4#2007]
Please take a look at the following fiddle.
https://jsfiddle.net/jcdu4z82/1/

Upon setting the initial data on a XYChart the chart appears as it should. Once the data is replaced the chart gets messed up.

**Comment by martynasma** [comment]
Your data is in descending order, hence the anomaly.

Chart expects date-based data in ascending order. Try reversing your data array.

**Comment by voger** [comment]
Thanks. It works
https://jsfiddle.net/jcdu4z82/2/
