### ISSUE TITLE
Resizing is slow

### ISSUE THREAD

**Issue by snowl** [amcharts/amcharts4#2008]
Hi,

I'm currently evaluating AMCharts for use in my application. I've got it integrated but one of the issues that I've found is that resizing is slow (even though the chart performance is fast).

I've created a codesanbox here: https://codesandbox.io/s/thirsty-ishizaka-mhcnp?fontsize=14&hidenavigation=1&theme=dark

When dragging the handle the chart is very choppy and performance in the browser overall is degraded. Is there anything I am doing wrong or is this able to be improved?

Thanks

**Comment by martynasma** [comment]
Works pretty much smoothly for me in Chrome.

Which browser are you testing with?

**Comment by snowl** [comment]
Chrome as well. It must be a CPU thing - my development machine is not very strong.

Thanks
