### ISSUE TITLE
Adapter for path on Image does not work

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#2010]
From  https://www.amcharts.com/docs/v4/concepts/legend/#Customizing_markers

Works
```
flag.adapter.add("href", function(href, target) {
  console.log(1)
  if (target.dataItem && target.dataItem.dataContext && target.dataItem.dataContext.dummyData) {
    return target.dataItem.dataContext.dummyData.flag;
  }
  else {
    return href;
  }
});
```
Doesnt: 
```
flag.adapter.add("path", function(href, target) {
  console.log(2)
  if (target.dataItem && target.dataItem.dataContext && target.dataItem.dataContext.dummyData) {
    return target.dataItem.dataContext.dummyData.flag;
  }
  else {
    return href;
  }
});
```

Not sure if it should but at least I can use the event right?

**Comment by martynasma** [comment]
Can you post your whole chart on CodePen?

`href` and `path` are not equivalent values.

The former holds the whole data uri (along with data type, base64 encoding, etc.) of the image, be it SVG, PNG, or something else.

The latter is just an SVG path sring.

**Comment by jimmykane** [comment]
@martynasma  I understand the different. What I want to achieve is feed a different path (SVG path) to the adapter for each marker icon/image 

Here is an example 

https://codepen.io/dimitrios-kanellopoulos/pen/qBExEVd 

You can see that the url adapter correctly triggers and console.logs 1 while the path adapter does not run (there is no console.log of 2)

**Comment by martynasma** [comment]
Gotcha. `path` adapter will probably will not work, because we can't just check if it is set on all Sprite element. That would be unnecessary overhead.

There's a workaround, though. Use some generic adapter (say "dx") to set `path` of the target element. E.g.:

```
flag.adapter.add("dx", function(dx, target) {
  target.path = target.dataItem.dataContext.dummyData.path;
  return dx;
});
```

Example:
https://codepen.io/team/amcharts/pen/45f0801247bded3601a4cbf32fa20820?editors=0010
