### ISSUE TITLE
Map Chart Tooltip styling possible?

### ISSUE THREAD

**Issue by Infineon12** [amcharts/amcharts4#2013]
Hello all,

thanks in advance for any help regarding my question.

In various type of charts i am able to find a way to define the look and feel of tooltips.
E.g.

```
			valueAxisTooltip.fill = am4core.color("#ffffff");
			valueAxisTooltip.fontSize = '10px';
			valueAxisTooltip.background.fill = am4core.color("#ff0000");
			valueAxisTooltip.background.strokeWidth = 0;
			valueAxisTooltip.background.cornerRadius = 3;
			valueAxisTooltip.exportable=false;
```

For Map Charts though i tried and tried but did not found a solution
E.g. 
```
			// Configure series
			var polygonTemplate = polygonSeries.mapPolygons.template;
			polygonTemplate.nonScalingStroke = true;
			polygonTemplate.strokeWidth = 0.5;
					
			//Tooltip
			polygonTemplate.propertyFields.tooltipHTML="tooltip";
			polygonTemplate.tooltipPosition = "fixed";
```

I would like to style the marked tooltip.

![image](https://user-images.githubusercontent.com/2978137/71891530-261b8c00-3147-11ea-928a-1340df9569dc.png)

Any suggestions how this is possible?

**Comment by martynasma** [comment]
You can access map series tooltip via its `tooltip` property:

```
polyhonSeries.tooltip.background....
```

Make sure you use `getFillFromObject = false` so that it does not inherit fill color from hovered object.

**Comment by Infineon12** [comment]
Thank you very much.
It works

**Comment by sureshhallyali** [comment]
thank you for this response and its working but error is occurring in angular 8

Error:
Property 'cursorOverStyle' does not exist on type '{ multiGeoPolygon?: string; multiPolygon?: string; visualLatitude?: string; visualLongitude?: string; precision?: string; zoomLevel?: string; zoomGeoPoint?: string; layout?: string; fontWeight?: string; ... 97 more ...; userClassName?: string; }'.
    
    191               polygonTemplate.propertyFields.cursorOverStyle = "cursor";
                                                     ~~~~~~~~~~~~~~~
