### ISSUE TITLE
Question: How to remove a label text on adapter: text

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#2015]
Example: 

```
  categoryLabel.label.adapter.add('text', (text, target) => {
        return `${Math.round(target.dataItem.values.valueX.percent)}%`;
      });
```

I would like to remove the text if I put an empty or undefined one. 

Now the label still shows (empty) if you have a background fill. 

I tried again with adapters to reduce the height and width to 0 but still the label would ocupy and show on the chart.

**Comment by martynasma** [comment]
I suggest adding another adapter for `visible` which would return `false` for labels that should be hidden altogether.

**Comment by jimmykane** [comment]
Thanks
