### ISSUE TITLE
Candlesticks with custom colors

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#2017]
Hi, is possible to create some adapter to change the colors of some specific candlestick?   
Currently we can change the colores with riseFromOpenState, etc. But what if I want some candlesticks with different color? (suppose big candles, or any specific rule)

**Comment by enriquepiatti** [comment]
OK, this is what I have now:   

```
        series.columns.template.adapter.add("fill", (fill, target) => {
            return target.dataItem && (chart.data[target.dataItem.index].isBlack) ? am4core.color("#000000") : fill;
        });
```

And it's working, but when I update the last candle and call invalidateRawData then the black candles are restored to the original color

**Comment by martynasma** [comment]
I suppose it would be safer to modify respective states as well for specific columns. Something like this:

```
series.columns.template.adapter.add("fill", (fill, target) => {
  if (target.dataItem && (chart.data[target.dataItem.index].isBlack) {
    target.riseFromOpenState.properties.fill = am4core.color("#000000");
    target.dropFromOpenState.properties.fill = am4core.color("#000000");
    return am4core.color("#000000");
  }
  return target.dataItem && (chart.data[target.dataItem.index].isBlack) ? am4core.color("#000000") : fill;
});
```

P.S. haven't actually tried it. Let me know how it goes :)

**Comment by enriquepiatti** [comment]
it shows me this error: Cannot read property 'properties' of undefined

**Comment by martynasma** [comment]
Can you post your whole chart?

**Comment by enriquepiatti** [comment]
You can see an example here (based on https://www.amcharts.com/demos/candlestick-chart/ )
https://codepen.io/enriqu3/pen/MWYVEzW

**Comment by martynasma** [comment]
Ah, OK I see the issue with my code. Those states are set on series, whereas we're trying to look for them in column. This approach won't work I'm afraid.

Probably the easiest way would be to just reset both of those default states altogether and handle fills in your adapter.

```
delete series.riseFromOpenState.properties.fill;
delete series.dropFromOpenState.properties.fill;
```

This means that fill adapter needs to take rise/drop and produce proper color as well.

Hope that makes sense.

**Comment by enriquepiatti** [comment]
Perfect, I have saved the codepen with the solution too. Thanks !

**Comment by enjoywithouthey** [comment]
Anyone know how to do this in amCharts 5?
