### ISSUE TITLE
How to get pie slice data values from over event?

### ISSUE THREAD

**Issue by clayton-crawford** [amcharts/amcharts4#2018]
I am trying to retrieve the category and value for a hovered pie slice. I initially attempted to use the `tooltipshownat` event however I discovered that this doesn't exist for a `PieSeries`. Currently, I have an `over` listener on my `PieSeries`. I understand that the `event.target` is the hovered slice but I can't work out how to get the corresponding category value and data value. 

Side question: Is there a reason why `tooltipshownat` is not implemented for `PieSeries`?

**Comment by martynasma** [comment]
You can use `event.target.dataItem` to access its structured data item and its data fields, e.g. `event.target.dataItem.category`.

Or access raw data: `event.target.dataItem.dataContext`.

I don't have an answer for your bonus question. Sorry :)

**Comment by clayton-crawford** [comment]
Thanks for the reply @martynasma! I tried that but for some reason all of those return undefined for me. `event.target.dataItem` returns an object but `.category`, `.value`, and `.dataContext` is undefined. Below is a small snippet of my implementation. Is there any common issues that I should check for in my code that could be causing the problem?

```
var pieSeries = pieChart.series.push(new am4charts.PieSeries());
pieSeries.dataFields.value = dataProperty; // intended to be set to a string variable
pieSeries.dataFields.category = "groupName";
pieSeries.events.on("over", function(event){
     // all undefined
     console.log(event.target.dataItem.dataContext);
     console.log(event.target.dataItem.category);
     console.log(event.target.dataItem.value);
});
```

**Comment by martynasma** [comment]
Because you're setting it on series directly, not on slice. Here's how to set it:

```
pieSeries.slices.template.events.on("over", function(event){
....
```

**Comment by clayton-crawford** [comment]
Ah, that did it! I guess I was a bit confused on how to accomplish this as I'm doing the same for a bar chart but doing `barSeries.events.on("tooltipshownat", function(event){...})` instead and thought that putting the event listener on the `pieSeries` would give me what I want as well. Thanks again!

**Comment by martynasma** [comment]
Well, for `ColumnSeries` it's the same. If you want individual data item when clicked you would set event handle on a column template:

```
barSeries.columns.template.events.on("hit", ....);
```
