### ISSUE TITLE
Using adapter function to return custom jsx in React?

### ISSUE THREAD

**Issue by maddieijams** [amcharts/amcharts4#2019]
I am using AMCharts4 to create this chart in React.

![](https://i.stack.imgur.com/s53jq.png)

I want to completely customize the legend to display the flag images of the countries instead of the default color bullets. I think I can achieve this by using an adapter to return html. I am using the flag-icon-css to generate the flag images so I want to do something like this:
` flag.adapter.add('href', function(href: any, target: any) {
          return <span className={target.dataItem.dataContext.dummyData.flag}></span>;
        });
      });`

I have been relying heavily on this example from the docs: https://codepen.io/team/amcharts/pen/VqQvxX I can't figure out what to add as the first argument to the adapter function. They use 'href' but I really want to use something like 'html' which i don't think exists and it's currently giving me the error: 'Type 'Element' is not assignable to type 'string'' when I try to return that from the adapter function.

I am currently trying to dynamically assign some dummyData to the series when they are created that takes the country iso code and puts it into a class name that the flag-icon package accepts. Like this:
`newSeries.dummyData = {
          flag: 'flag-icon flag-icon-${ownershipItem.isoCode.toLowerCase()}'
        };`

Is it possible to return html/jsx from an adapter function with amcharts4? and if not is there another way to achieve this custom legend? Any help is appreciated. I will post some more detailed code below.
` useEffect(
    function() {
      if (topOwnershipMounted && CompanyTopOwnership) {
        topOwnershipChart.current = (() => {
          am4core.useTheme(am4themes_kelly);
          const newChart = am4core.create('topOwnershipChart', am4charts.XYChart);
          newChart.data = CompanyTopOwnership;
          newChart.dateFormatter.dateFormat = 'yyyy';
          newChart.minHeight = 300;

          // Declare Axes
          let countryAxis = newChart.yAxes.push(new am4charts.ValueAxis());
          let yearAxis = newChart.xAxes.push(new am4charts.DateAxis());
          yearAxis.renderer.axisFills.template.disabled = false;
          yearAxis.renderer.axisFills.template.fillOpacity = 0.8;
          yearAxis.renderer.axisFills.template.fill = am4core.color('#F0F4FC');

          newChart.legend = new am4charts.Legend();
          let marker = newChart.legend.markers.template;
          marker.disposeChildren();

          //create line series
          CompanyTopOwnership.companyTopOwnerShips.map((ownershipItem: any) => {
            let newSeries = newChart.series.push(new am4charts.LineSeries());
            newSeries.name = ownershipItem.countryName;
            const newSeriesData = ownershipItem.ownerShipPercentageDates.map((percentItem: any) => {
              return percentItem;
            });

            // assign data for flags
            newSeries.dummyData = {
              flag: `flag-icon flag-icon-${ownershipItem.isoCode.toLowerCase()}`
            };

            // Add custom image instead
            let flag = marker.createChild(am4core.Image);

            // use adapter to try and return custom html instead of marker
            flag.adapter.add('path', function(path: any, target: any) {
              
              return <span className={target.dataItem.dataContext.dummyData.flag}></span>;
            });

            newSeries.data = orderBy(
              newSeriesData,
              ({ year }) => {
                return moment(year).format('YYYY');
              },
              ['asc']
            );

            newSeries.dataFields.dateX = 'year';
            newSeries.dataFields.valueY = 'percentage';
            newSeries.strokeWidth = 3;
            newSeries.tensionX = 0.7;
            newSeries.bullets.push(new am4charts.CircleBullet());
          });

          return newChart;
        })();
      }
    },
  
    [CompanyTopOwnership, getCompanyData, topOwnershipMounted]
  );`

**Comment by maddieijams** [comment]
The example from this issue https://github.com/amcharts/amcharts4/issues/2010 has helped me greatly and is very close to what i'm trying to do, but I do not want to return just an svg path, i need to return jsx in my adapter instead. Is it possible to do this? Link to codepen example: https://codepen.io/team/amcharts/pen/45f0801247bded3601a4cbf32fa20820?editors=0010

**Comment by martynasma** [comment]
If I understand you correctly, you wan to use HTML as a legend marker?

The only way I can see it working if you:

1) Add a `Label` object (instead of `Image` or `Sprite`) as a child of marker.
2) Use its `html` property or adapter to set to your HTML content.

Not sure how this would work with JSX, and haven't actually tried the above, but it's worth giving a shot.

Alternatively, you may consider building a completely custom legend:
https://codepen.io/team/amcharts/pen/aevJEw?editors=0010

**Comment by maddieijams** [comment]
The label property worked! Thanks! Code for my legend:

`          newChart.legend = new am4charts.Legend();
          newChart.legend.useDefaultMarker = true;
          const marker = newChart.legend.markers.template;
          marker.disposeChildren();
          const flag = marker.createChild(am4core.Label);
          flag.adapter.add('html', function(label: any, target: any) {
            let iso = target.dataItem.dataContext.dummyData;
            if (target.dataItem.dataContext) {
              console.log(iso);
              return `<span class='flag-icon flag-icon-${iso.toLowerCase()}'></span> `;
            } else {
              return label;
            }
          });`
