### ISSUE TITLE
Column Series Fill and Stroke values are not being used by Tooltip where valueY equals 0

### ISSUE THREAD

**Issue by cam-m** [amcharts/amcharts4#202]
Using an XY Chart with Stacked Columns, an XYCursor, and tooltips per Column - this creates a tooltip that displays Name and Value for all columns for a stacked date on the xaxis.

When a column has a zero value the tooltip colors (fill and stroke) are not getting their values from the series. 

[Codepen illustrating issue](https://codepen.io/cam-m/pen/rrKWBb)

Moving the cursor over the first value illustrates the issue - the 'Open' tooltip fill is being taken from the default, but it should be set to the color I've defined for the series.

I guess the tooltip is trying to get its fill/stroke values from the the Column rather than the Series, and since there is no Column for a zero value it cannot find a color.

**Comment by cam-m** [comment]
ok... so I just realised I was not setting the fill on the series at all .. it was on the column... it works now. 

New question: How do I delete an issue entirely :)

**Comment by martynasma** [comment]
Glad you worked it out.

> New question: How do I delete an issue entirely :)

Closing is enough. Maybe somebody else is going through the same pain, and your follow will help them ;)
