### ISSUE TITLE
On Force-directed tree  Can you use an direction Arrow?

### ISSUE THREAD

**Issue by isnopitag** [amcharts/amcharts4#2020]
I'm looking for to add an arrow to the link on Force-directed tree from parent node to child node.

It's possible?

**Comment by martynasma** [comment]
No, I'm afraid.

**Comment by rubenstolk** [comment]
Looking for this too.

**Comment by aklauza** [comment]
Interested in this feature as well. Thanks

**Comment by senzzzi** [comment]
Also interested in the feature.

**Comment by hfgbarrigas** [comment]
+1 for the feature. Ty

**Comment by skkart** [comment]
Looking for this feature. Pls fix it.

**Comment by martynasma** [comment]
I'm sorry everyone, but we are not planning on implementing this feature for amCharts 4.
