### ISSUE TITLE
X Axis value alignment

### ISSUE THREAD

**Issue by rbruhn** [amcharts/amcharts4#2021]
I've poured over the documents trying to find this answer but can't find it. When the legend labels and values are shown, how can I align the values so they are not so far away? Example:

Test 1:               98
Test 2:               100
Test 3:               50

I'd rather the number show after the colons.

**Comment by rbruhn** [comment]
Ok, apparently github removed my spaces, so here is an image
![c7ac39c610bfa89f6279108c4db1769d](https://user-images.githubusercontent.com/1283141/72018739-33637400-3236-11ea-8e86-e047cc8c4490.png)

**Comment by martynasma** [comment]
I suppose the easiest way is to just add value placeholder into legend label text:

```
chart.legend.labels.template.text = "{name}: {valueY.close}";
```

**Comment by rbruhn** [comment]
Thank you. That did the trick.
