### ISSUE TITLE
Drawing tool for maps || Question

### ISSUE THREAD

**Issue by moghthalkushal** [amcharts/amcharts4#2022]
G'day !!

I am looking for a drawing tool over a map , something like a lasso on a map , I can select all the geo points , by drawing something , something similar to below example :
http://bl.ocks.org/skokenes/498a150f94cd21e2270f

![image](https://user-images.githubusercontent.com/5137212/72029158-c224cf00-32d0-11ea-954c-47fbd64b9122.png)

Any leads or ideas will be really appreciated.

Cheers!!!

**Comment by martynasma** [comment]
I'm afraid we don't have such tools planned for implementation. Sorry.

**Comment by moghthalkushal** [comment]
@martynasma , thank you , I have used leaflets to achieve the same.
https://moghthalkushal.github.io/leaflet-maps-with-lasso/#

Lasso Plugin Provider : "https://github.com/zakjan/leaflet-lasso"
