### ISSUE TITLE
How to use axis range on XYChart3D ?

### ISSUE THREAD

**Issue by XxSven** [amcharts/amcharts4#2023]
Hello,
I wasn't able to find any demo showing how to make an axis range work on XYChart3D.
When I add an axis range to an existing XYChart3D demo, the range isn't correctly placed, as if the chart wasn't 3D :

![image](https://user-images.githubusercontent.com/22731605/72047901-dd391400-32bb-11ea-96b3-4828ff619ce2.png)

The demo I used :
https://www.amcharts.com/demos/3d-column-chart/
The code I added at the end :
```
// Create value axis range
var range = valueAxis.axisRanges.create();
range.value = 300;
range.endValue = 1100;
range.axisFill.fill = am4core.color("#396478");
range.axisFill.fillOpacity = 0.2;
range.grid.strokeOpacity = 0;
```

Is there an option I missed to make the axis range acknowledge the 3D ?
Thanks for the support 👍

**Comment by martynasma** [comment]
Axis ranges were not implemented to support 3D charts.

I'm marking this as a possible enhancement. We'll let you know if there's a progress.

In the interim you can adjust the position of the range fill manually:

```
range.axisFill.dx = 26;
range.axisFill.dy = -8;
```

**Comment by martynasma** [comment]
Hi again. Sorry for the wait. We have decided not to implement this feature at this point. Sorry.

Please consider using the proposed workaround.
