### ISSUE TITLE
wrong rendering on multiple date axis

### ISSUE THREAD

**Issue by ahmedali5530** [amcharts/amcharts4#2024]
Hi there,
I am using multiple date axis with dynamic values and series, i have random data on dates, when i tries to render the chart, it renders successfully, but shows the wrong date stacking. It should start all the rendering from left to right, not from center.

Here is the demo [https://codepen.io/ahmedali5530/pen/LYEdybR?editors=0010](https://codepen.io/ahmedali5530/pen/LYEdybR?editors=0010)

**Comment by martynasma** [comment]
The second series has one data point, hence its `DateAxis` having no scale whatsoever, just one day in the middle.

If you need your second axis to render a range of time bigger than actual range of data (one data point), you can use `min` and `max` properties of the axis to set the range manually. E.g.:

```
  if (item == "Set 0") {
    dateAxis.min = new Date("2020-01-03").getTime();
    dateAxis.max = new Date("2020-01-09").getTime();
  }
```

**Comment by martynasma** [comment]
https://codepen.io/team/amcharts/pen/6f452201c93a738747b771bec36c2d0b?editors=0010
