### ISSUE TITLE
v4 Create documentation is missing

### ISSUE THREAD

**Issue by mlippert** [amcharts/amcharts4#2025]
There is a link to the [create documentation](https://www.amcharts.com/docs/v4/reference/utils_module/#create_method) on the [getting started page](https://www.amcharts.com/docs/v4/getting-started/basics/) on the  but the documentation itself is missing.

I was looking for the documentation because I wondered if the containing element had to be referenced by id, of if I could just pass in the DOM element somehow.

On a side note, are the utility functions really intended to be sorted in descending alphabetic order?

**Comment by martynasma** [comment]
Thanks for bringing it to our attention. Link is fixed now.

And no, they are not supposed to be sorted in descending order. We'll need to fix that as well.

Thanks again!

**Comment by mlippert** [comment]
Looks all fixed, thanks. I'd say this is closed now, but wasn't sure I should be the one to close it.

**Comment by martynasma** [comment]
No worries, I'll close it for you.
