### ISSUE TITLE
automatic hides the label ,when we have more series labels are comming randomly 

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#2026]
![image](https://user-images.githubusercontent.com/54665162/72136382-af80c780-33ae-11ea-815b-1e386b3b13e7.png)

**Comment by martynasma** [comment]
Not randomly at all. Take a look here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by Mahisandy** [comment]
yaxis inside series lable are comming  randomly

**Comment by martynasma** [comment]
What do you mean randomly? Your screenshots show every second label appearing, which is exactly product of `minGridDistance` setting.

Did you read the information in the link I mentioned? :)
