### ISSUE TITLE
Angular Universal Express Engine Build Error

### ISSUE THREAD

**Issue by azizcetin-medyanet** [amcharts/amcharts4#2027]
For SEO I wanna use '**@nguniversal/express-engine**' package in my app, but when I run  below command, I get 
below exception.

**CLI Command**
`npm run build:ssr && npm run serve:ssr`

**Exception**
ERROR in ./node_modules/canvg/dist/node/canvg.js
Module not found: Error: Can't resolve 'canvas' in 'C:\Users\xxx\Desktop\projectname\node_modules\canvg\dist\node'

ERROR in ./node_modules/canvg/dist/node/canvg.js
Module not found: Error: Can't resolve 'jsdom' in 'C:\Users\xxx\Desktop\projectname\node_modules\canvg\dist\node'

ERROR in ./node_modules/canvg/dist/node/canvg.js
Module not found: Error: Can't resolve 'xmldom' in 'C:\Users\xxx\Desktop\projectname\node_modules\canvg\dist\node'

**OS Platform :** Windows
**amcharts4 Package Version :** 4.7.20

**Comment by Pauan** [comment]
@azizcetin-medyanet Could you please share your code (ideally as a GitHub repository)?

**Comment by azizcetin-medyanet** [comment]
> @azizcetin-medyanet Could you please share your code (ideally as a GitHub repository)?

 I am using https://www.creative-tim.com/product/blk-design-system-angular# this template for my project. When I try to use  '@nguniversal/express-engine' package  before  using amcharts4, it works very well. But when I wanna use one of the maps in the amcharts4  with  '@nguniversal/express-engine' package it gives me errors which are I mentioned before. 
In this link "https://github.com/cetinaziz2894/amcharts4-angular-universal/tree/master/src/app/pages/world"  you can see the source code and my world component. This component includes a world map by using amchart4. 

Than you for your concern and kind. I am looking forward to your reply.

**Comment by vasiliy-maslov** [comment]
I got the same error and a few more when using amcharts 4. The server folder is not generated when the build part of the distribution kit for server rendering is build.
The commands that I ran:
`ng add @ nguniversal / express-engine`
`npm run build: ssr && npm run serve: ssr`

Exceptions and warnings:

> WARNING in ./node_modules/jsdom/node_modules/ws/lib/buffer-util.js
> Module not found: Error: Can't resolve 'bufferutil' in '/home/maslov/WebstormProjects/angular-universal/node_modules/jsdom/node_modules/ws/lib'
> 
> WARNING in ./node_modules/jsdom/node_modules/ws/lib/validation.js
> Module not found: Error: Can't resolve 'utf-8-validate' in '/home/maslov/WebstormProjects/angular-universal/node_modules/jsdom/node_modules/ws/lib'
> 
> ERROR in ./node_modules/canvg/dist/node/canvg.js
> Module not found: Error: Can't resolve 'canvas' in '/home/maslov/WebstormProjects/angular-universal/node_modules/canvg/dist/node'
> 
> ERROR in ./node_modules/jsdom/lib/jsdom/utils.js
> Module not found: Error: Can't resolve 'canvas' in '/home/maslov/WebstormProjects/angular-universal/node_modules/jsdom/lib/jsdom'
> 
> ERROR in ./node_modules/canvg/dist/node/canvg.js
> Module not found: Error: Can't resolve 'xmldom' in '/home/maslov/WebstormProjects/angular-universal/node_modules/canvg/dist/node'
