### ISSUE TITLE
Amchart4 tooltip issue in javascript for multiple(more than 15) LineSeries XY Charts

### ISSUE THREAD

**Issue by srisharan403** [amcharts/amcharts4#2028]
I am using amchart4 free version. I have a requirement to show more than 15 line series for XYChart.
so using the mentioned code , i can find tooltip for only some of the line series(may be 4 or 5 out of 15 series). so can anyone provide solution for my requirement and can anyone let me know where i am going wrong
[amchart.data.txt](https://github.com/amcharts/amcharts4/files/4045372/amchart.data.txt)
[Amchart.script.txt](https://github.com/amcharts/amcharts4/files/4045373/Amchart.script.txt)

**Comment by martynasma** [comment]
Do you mean that you get too many tooltips?

The solution would be to set up cursor to show only closest ones:

```
chart.cursor.maxTooltipDistance = 10;
```

https://www.amcharts.com/docs/v4/reference/xycursor/#maxTooltipDistance_property

**Comment by srisharan403** [comment]
hi martynasma,
the solution which u have provided is not working out, could you please suggest me some more relavant solution.As you can see in my attached picture, when i place cursor tooltip on series  we can see only tooltip for two of the series,but not to the remaining series..so i need tooltipText for all the line series(where by i have 20 line series for a chart). please find the attachement for clear picture
![amchart issue](https://user-images.githubusercontent.com/59687588/72258336-cb48cf80-3633-11ea-85ca-22035116284c.JPG)

**Comment by martynasma** [comment]
Maybe then combine stuff into a single tooltip or display hover information in a custom element:

https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/
https://www.amcharts.com/docs/v4/tutorials/custom-static-multi-value-tooltip/
