### ISSUE TITLE
columnseries tooltip change view position

### ISSUE THREAD

**Issue by malajyoti9** [amcharts/amcharts4#2029]
![tooltipissue](https://user-images.githubusercontent.com/27776245/72150212-0399a500-33cb-11ea-9927-ce9d25679809.png)

I am using amcharts column series.My tooltip is getting over the blue column.I want to add some padding or margin to tooltip or change the starting position of tooltip instead of pointer being in middle.

**Comment by XxSven** [comment]
Here is what you need :
https://www.amcharts.com/docs/v4/tutorials/using-sticky-tooltips/#Positioning_within_target_element
you can move the tooltip on the right using this:
**JS**
`series.tooltip.dx = 20;`
**JSON**
```
"series": [{
    "type": "ColumnSeries",
    // ...
    "tooltip": {
      // ...
      "dx": 20
    }
  }]
```

**Comment by martynasma** [comment]
Tooltip has properties `tooltipX` and `tooltipY` which can be absolute pixel values or percents. E.g.:

```
series.tooltip.tooltipX = am4core.percent(100);
```

The above will place tooltip at the right of the column.

**Comment by malajyoti9** [comment]
> Here is what you need :
> https://www.amcharts.com/docs/v4/tutorials/using-sticky-tooltips/#Positioning_within_target_element
> you can move the tooltip on the right using this:
> **JS**
> `series.tooltip.dx = 20;`
> **JSON**
> 
> ```
> "series": [{
>     "type": "ColumnSeries",
>     // ...
>     "tooltip": {
>       // ...
>       "dx": 20
>     }
>   }]
> ```

dx is making a gap between my mouse cursor and tooltip point

**Comment by malajyoti9** [comment]
> Tooltip has properties `tooltipX` and `tooltipY` which can be absolute pixel values or percents. E.g.:
> 
> ```
> series.tooltip.tooltipX = am4core.percent(100);
> ```
> 
> The above will place tooltip at the right of the column.

it's causing no effect .

**Comment by zeroin** [comment]
Do you use the lateste version or some older one? A possibility to set tooltipX and tooltipY in percent values was added not so long ago.

**Comment by malajyoti9** [comment]
Mine version is 4.4.1

**Comment by martynasma** [comment]
> Mine version is 4.4.1

We're currently at `4.8.0`. Let us know if you still can't make it work after upgrading.

**Comment by malajyoti9** [comment]
> > Mine version is 4.4.1
> 
> We're currently at `4.8.0`. Let us know if you still can't make it work after upgrading.

No effect then also,Isn't there anything that it don't go over blue boxes.

**Comment by martynasma** [comment]
@malajyoti9 Can you post your chart somewhere we can check?

**Comment by hauhuynh1208** [comment]
@martynasma I am facing the same issue. Here is my codepen:
https://codepen.io/hauhuynh1208/pen/PobKqLv?editors=0110

Please see line 113. I set tooltipY = am4core.percent(50) but it has no effect
