### ISSUE TITLE
Rendering Lengthy Labels without Truncation

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#203]
Hello,

When I am trying to render label bullets with lengthy label texts with disabled truncate property, the labels are not displayed.

In the pen attached below, I want the label texts to override the adjacent columns. Is that not possible?

https://codepen.io/anon/pen/YjjJGw?editors=0010

**Comment by martynasma** [comment]
Hi,

Do you mean labels on the category axis? ("USA", "China", etc.)

If yes, then check out this doc:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

It will explain everything :)

**Comment by VaishnaviAppannagari** [comment]
No, I am talking about labels for series i.e label bullets.

**Comment by martynasma** [comment]
Ah ok gotcha. Now I can see the "vvv" labels :)

On chart labels that do not fit into their place are automatically hidden.

To disable this, use label's [`hideOversized`](https://www.amcharts.com/docs/v4/reference/label/#hideOversized_property) property.

```
labelBullet.label.hideOversized = false;
```

**Comment by VaishnaviAppannagari** [comment]
Thank you. Its working.

**Comment by martynasma** [comment]
Great!

I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by shashisingh111** [comment]
Hello, 
I am still facing the issue when label is large, the last label is truncating.
I have attached the pen link below.
[https://codepen.io/shashi_111/pen/JjKeGOY?editors=1010](url)
