### ISSUE TITLE
How to get the date object used to display DateAxis tooltip ?

### ISSUE THREAD

**Issue by XxSven** [amcharts/amcharts4#2030]
I am trying to change the tooltip of the dateAxis using the adapter "getTooltipText".
I want to retrieve the date object to do some manipulations on it, but I can't find which property to use (the property used to create the text parameter).

Here is a codepen indicating where I am having trouble (the commented line "target. ???") :
https://codepen.io/XxSven/pen/bGNMNWB

Thanks for the support.

**Comment by zeroin** [comment]
There is no such thing as current data item on the date axis. So my suggestion would be to set some date format for the tooltipDateFormat and then parse the date from the string date, like:

`
dateAxis.tooltipDateFormat = "yyyy-MM-dd";
dateAxis.adapter.add("getTooltipText", function(text, target) {	
  console.log(chart.dateFormatter.parse(text, "yyyy-MM-dd"));
  return text;
})`
