### ISSUE TITLE
how to improve the performace

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#2032]
in single page i am loading more than 50 graphs,data received from api once dependes on length excutes the for loop amchart code writen inside the loop body.

**Comment by martynasma** [comment]
The following page has some performance-enhancing tips:
https://www.amcharts.com/docs/v4/concepts/performance/

**Comment by Mahisandy** [comment]
artical's in complete ,sample code/example not there 
how to disable the amination can u provide me demo example

**Comment by martynasma** [comment]
You disable animations by not enabling them :) That is by not applying animated theme.

```
am4core.useTheme(am4themes_animated);
```

The following line must be remove to disable animations.
