### ISSUE TITLE
Tooltip percent value not updated with adapter when a legend slice is hidden

### ISSUE THREAD

**Issue by oliverlj** [amcharts/amcharts4#2033]
Hello,

I write this codepen https://codepen.io/oliverlj/pen/yLyjYdM of a sunburst diagram.

When a slice is hidden, the tooltip percent of other slice are not updated. I don't know if this is bug ?

Regards, Oliver

**Comment by martynasma** [comment]
The thing is that you are accessing aggregated Sunburst data item value.

This should do the trick:

```
level1.slices.template.adapter.add('tooltipText', (text, target) => {
  const data = target.tooltipDataItem;
  if (data) {
    return data.values.value.percent;
  } else {
    return text;
  }
});
```
