### ISSUE TITLE
Chart visualization

### ISSUE THREAD

**Issue by bbogdanov** [amcharts/amcharts4#2034]
Hello,

Recently I started using amcharts4 with Angular Elements and AngularJS. For over a month and a half everything was working fine but for some reason, the chart stopped showing up. What is strange is that sometimes the renderer is working and I can see the chart but most of the time it just doesn't render on the page.

First I thought that maybe the `am4core.create` doesn't find the HTML element but I can see that the HTML element has the SVG that `am4core.create` creates.

I followed the tutorial here -> https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/ so the code is not different than the one in the tutorial.

Do you have any suggestions about what could be the problem?

The is the SVG that the `am4core.create` created and it exists in the HTML but doesn't render on the page.

`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" role="group" style="width: 100%; height: 100%; overflow: visible;"><desc>JavaScript chart by amCharts</desc><defs><clipPath id="id-1509"><rect width="0" height="0"></rect></clipPath><linearGradient id="gradient-id-1532" x1="1%" x2="99%" y1="59%" y2="41%"><stop stop-color="#474758" offset="0"></stop><stop stop-color="#474758" stop-opacity="1" offset="0.75"></stop><stop stop-color="#3cabff" stop-opacity="1" offset="0.755"></stop></linearGradient><filter id="filter-id-1456" width="200%" height="200%" x="-50%" y="-50%"></filter><filter id="filter-id-1464" width="200%" height="200%" x="-50%" y="-50%"></filter><clipPath id="id-1473"><path d="M0,0 L0.0001,0 L0.0001,0.0001 L0,0.0001 L0,0M0,0 L0,0 L0,0 L0,0 L0,0"></path></clipPath><clipPath id="id-1577"><path d="M0,0 L0,0 L0,0 L0,0 L0,0"></path></clipPath><clipPath id="id-1585"><rect width="0" height="0"></rect></clipPath><clipPath id="id-1934"><rect width="0" height="0"></rect></clipPath><filter id="filter-id-1513" width="200%" height="200%" x="-50%" y="-50%"><feGaussianBlur result="blurOut" in="SourceGraphic" stdDeviation="1.5"></feGaussianBlur><feOffset result="offsetBlur" dx="1" dy="1"></feOffset><feFlood flood-color="#000000" flood-opacity="0.5"></feFlood><feComposite in2="offsetBlur" operator="in"></feComposite><feMerge><feMergeNode></feMergeNode><feMergeNode in="SourceGraphic"></feMergeNode></feMerge></filter><filter id="filter-id-1530" width="120%" height="120%" x="-10%" y="-10%"><feColorMatrix type="saturate" values="0"></feColorMatrix></filter><filter id="filter-id-1477" width="200%" height="200%" x="-50%" y="-50%"><feGaussianBlur result="blurOut" in="SourceGraphic" stdDeviation="1.5"></feGaussianBlur><feOffset result="offsetBlur" dx="1" dy="1"></feOffset><feFlood flood-color="#000000" flood-opacity="0.5"></feFlood><feComposite in2="offsetBlur" operator="in"></feComposite><feMerge><feMergeNode></feMergeNode><feMergeNode in="SourceGraphic"></feMergeNode></feMerge></filter></defs><g><g fill="#ffffff" fill-opacity="0"><rect width="0" height="0"></rect></g><g><g role="widget" clip-path="url(&quot;#id-1509&quot;)" opacity="1" aria-describedby="id-1490-description"><g transform="translate(15,15)"><g><g><g><g><g><g><g transform="translate(0,0)" style="touch-action: none; user-select: none; -webkit-user-drag: none;"><g fill="#ffffff" fill-opacity="0" transform="translate(0,0)"><rect width="0" height="0"></rect></g><g><g><g><g stroke="#000000" stroke-opacity="0.15" fill="none" display="none"><path d=" M0,0  L0,0 " transform="translate(-0.5,-0.5)"></path></g><g stroke="#000000" stroke-opacity="0.15" fill="none" display="none"><path d=" M0,0  L0,0 " transform="translate(-0.5,-0.5)"></path></g><g stroke="#000000" stroke-opacity="0.15" fill="none" display="none"><path d=" M0,0  L0,0 " transform="translate(-0.5,-0.5)"></path></g><g stroke="#000000" stroke-opacity="0.15" fill="none"><path d=" M0,0  L0,0 " transform="translate(-0.5,-0.5)"></path></g><g stroke="#000000" stroke-opacity="0.15" fill="none" display="none"><path d=" M0,0  L0,0 " transform="translate(-0.5,-0.5)"></path></g><g stroke="#000000" stroke-opacity="0.15" fill="none" display="none"><path d=" M0,0  L0,0 " transform="translate(-0.5,-0.5)"></path></g><g fill="#000000" fill-opacity="0" style="pointer-events: none;"><path d="M0,0 L0,0 L0,0 L0,0 L0,0"></path></g></g></g><g><g><g stroke="#000000" stroke-opacity="0.15" fill="none"><path d=" M0,0  L0,0 " transform="translate(-0.5,-0.5)"></path></g><g stroke="#000000" stroke-opacity="0.15" fill="none" transform="translate(0.000050624133148404996,0)"><path d=" M0,0  L0,0 " transform="translate(-0.5,-0.5)"></path></g><g stroke="#000000" stroke-opacity="0.15" fill="none" transform="translate(0.00010124826629680999,0)" display="none"><path d=" M0,0  L0,0 " transform="translate(-0.5,-0.5)"></path></g></g></g><g><g><g role="group" stroke-opacity="1" fill-opacity="0" fill="#67b7dc" stroke="#67b7dc" stroke-width="2" aria-describedby="id-1480-description"><g><g clip-path="url(&quot;#id-1473&quot;)"><g><g><g><g fill="#67b7dc" fill-opacity="0" stroke="#67b7dc" stroke-opacity="1" stroke-width="2" style="pointer-events: none;"><g><g stroke-opacity="0"><path></path></g><g fill="none" fill-opacity="0"><path d=" M-0.2,-0.2  M0,0  C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0"></path></g></g></g></g></g></g></g><g></g><g><g><g clip-path="url(&quot;#id-1577&quot;)" stroke="#ff0000" fill="#ff0000"><g><g fill="#ff0000" stroke="#ff0000" style="pointer-events: none;"><g><g stroke-opacity="0"><path></path></g><g fill="none" fill-opacity="0"><path d=" M-0.2,-0.2  M0,0  C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0,0 C0,0 0,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0 C0.0001,0 0.0001,0 0.0001,0"></path></g></g></g></g></g></g></g></g><desc id="id-1480-description">Series</desc></g></g></g><g clip-path="url(&quot;#id-1934&quot;)"><g><g fill="#67b7dc" stroke="#67b7dc"><g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g><g opacity="1"><g></g></g></g></g></g></g><g><g><g><g></g></g><g><g></g></g></g></g><g><g></g></g><g><g></g></g><g opacity="0" visibility="hidden" aria-hidden="true" clip-path="url(&quot;#id-1585&quot;)" style="touch-action: none; user-select: none; -webkit-user-drag: none;"><g><g fill-opacity="0.2" fill="#000000" visibility="hidden" style="pointer-events: none;"><path></path></g><g stroke="#000000" fill="none" stroke-dasharray="3,3" stroke-opacity="0.4" style="pointer-events: none;"><path></path></g><g stroke="#000000" fill="none" stroke-dasharray="3,3" stroke-opacity="0.4" style="pointer-events: none;"><path></path></g></g></g><g role="button" focusable="true" opacity="0" transform="translate(0,-3)" aria-labelledby="id-1504-title" aria-hidden="true" visibility="hidden"><g fill="#6794dc" stroke="#ffffff" fill-opacity="1" stroke-opacity="0" transform="translate(0,8)"><path d="M9,0 L9,0 a9,9 0 0 1 9,9 L18,9 a9,9 0 0 1 -9,9 L9,18 a9,9 0 0 1 -9,-9 L0,9 a9,9 0 0 1 9,-9 Z"></path></g><g transform="translate(9,9)"><g stroke="#ffffff" transform="translate(0,8)" style="pointer-events: none;"><path d=" M0,0  L11,0 " transform="translate(2.5,7.5)"></path></g><g fill="#000000" transform="translate(6,8)" style="pointer-events: none;"><g></g></g></g><title id="id-1504-title">Zoom Out</title></g></g></g><g><g><g aria-hidden="true"><g><g fill="#000000" transform="translate(0,0.00005) rotate(-90)"><g></g></g><g stroke="#000000" stroke-opacity="0.15" fill="none" transform="translate(0,0)"><path transform="translate(-0.5,-0.5)" d=" M0,0  L0,0 "></path></g><g transform="translate(20,0)"><g><g fill="#000000" fill-opacity="0" opacity="0" stroke-opacity="0" style="pointer-events: none;"><g transform="translate(-10,0)" style="user-select: none;"><text x="0" y="0" dy="0"><tspan>L</tspan></text></g></g><g fill="#000000" display="none"><g transform="translate(-10,0)"></g></g><g fill="#000000" display="none"><g transform="translate(-10,0)"></g></g><g fill="#000000" display="none"><g transform="translate(-10,0)"></g></g><g fill="#000000"><g transform="translate(-10,0)"></g></g><g fill="#000000" display="none"><g transform="translate(-10,0)"></g></g><g fill="#000000" display="none"><g transform="translate(-10,0)"></g></g></g></g><g stroke="#000000" stroke-opacity="0" fill="none" style="pointer-events: none;"><path d=" M0,0  L0,0.0001 " transform="translate(-0.5,-0.5)"></path></g></g></g></g></g><g><g></g></g></g></g><g><g></g></g><g><g><g aria-hidden="true"><g><g stroke="#000000" stroke-opacity="0" fill="none" style="pointer-events: none;"><path d=" M0,0  L0.0001,0 " transform="translate(-0.5,-0.5)"></path></g><g><g><g fill="#000000" fill-opacity="0" opacity="0" stroke-opacity="0" style="pointer-events: none;"><g transform="translate(0,10)" style="user-select: none;"><text x="0" y="0" dy="0"><tspan>L</tspan></text></g></g><g fill="#000000" transform="translate(0.000025312066574202498,0)"><g transform="translate(0,10)"></g></g><g fill="#000000" transform="translate(0.0000759361997226075,0)"><g transform="translate(0,10)"></g></g><g fill="#000000" transform="translate(0.00012662968099861303,0)" display="none"><g transform="translate(0,10)"></g></g></g></g><g stroke="#000000" stroke-opacity="0.15" fill="none" display="none"><path transform="translate(-0.5,-0.5)" d=" M0,0  L0,0 "></path></g><g fill="#000000" transform="translate(0.00005,0)"><g></g></g></g></g></g></g></g></g></g></g></g><desc id="id-1490-description">Chart</desc></g><g><g><g role="tooltip" visibility="hidden" opacity="0"><g fill="#ffffff" fill-opacity="0.9" stroke-width="1" stroke-opacity="1" stroke="#ffffff" filter="url(&quot;#filter-id-1513&quot;)" style="pointer-events: none;"><path d="M3,0 L21,0 a3,3 0 0 1 3,3 L24,8 a3,3 0 0 1 -3,3 L3,11 a3,3 0 0 1 -3,-3 L0,3 a3,3 0 0 1 3,-3"></path></g><g><g fill="#ffffff" transform="translate(12,0)" style="pointer-events: none;"><g transform="translate(0,7)"></g></g></g></g><g visibility="hidden" display="none" style="pointer-events: none;"><g fill="#ffffff" opacity="1"><rect width="0" height="0"></rect></g><g><g><g><g stroke-opacity="1" fill="#f3f3f3" fill-opacity="0.8"><g><g><path d=" M53,0  a53,53,0,0,1,-106,0 a53,53,0,0,1,106,0 M42,0  a42,42,0,0,0,-84,0 a42,42,0,0,0,84,0 L42,0 "></path></g></g></g><g stroke-opacity="1" fill="#000000" fill-opacity="0.2"><g><g><path d=" M50,0  a50,50,0,0,1,-100,0 a50,50,0,0,1,100,0 M45,0  a45,45,0,0,0,-90,0 a45,45,0,0,0,90,0 L45,0 "></path></g></g></g><g fill="#000000" fill-opacity="0.4"><g></g></g></g></g></g></g><g opacity="0" aria-labelledby="id-1530-title" filter="url(&quot;#filter-id-1530&quot;)" transform="translate(0,0)" aria-hidden="true" style="cursor: pointer;" visibility="hidden"><g fill="#ffffff" opacity="0"><rect width="66" height="21"></rect></g><g><g shape-rendering="auto" fill="none" stroke-opacity="1" stroke-width="1.7999999999999998" stroke="#3cabff"><path d=" M15,15  C17.4001,15 22.7998,15.0001 27,15 C31.2002,14.9999 33.2999,6 36,6 C38.7001,6 38.6999,10.5 40.5,10.5 C42.3001,10.5 42.2999,6 45,6 C47.7001,6 50.9999,14.9999 54,15 C57.0002,15.0001 58.7999,15 60,15"></path></g><g shape-rendering="auto" fill="none" stroke-opacity="1" stroke-width="1.7999999999999998" stroke="url(&quot;#gradient-id-1532&quot;)"><path d=" M6,15  C8.2501,15 9.7498,15.0001 15,15 C20.2502,14.9999 20.7748,3.6 27,3.6 C33.2252,3.6 33.8998,14.9999 39.9,15 C45.9002,15.0001 45.9748,15 51,15 C56.0252,15 57.7499,15 60,15"></path></g></g><title id="id-1530-title">Chart created using amCharts library</title></g><g role="tooltip" visibility="hidden" opacity="0"><g fill="#000000" fill-opacity="1" stroke-width="1" stroke-opacity="1" stroke="#000000" transform="translate(15,15)" style="pointer-events: none;"><path d="M0,0 L20,0 a0,0 0 0 1 0,0 L20,10 a0,0 0 0 1 -0,0 L0,10 a0,0 0 0 1 -0,-0 L0,0 a0,0 0 0 1 0,-0"></path></g><g><g fill="#ffffff" transform="translate(25,15)" style="pointer-events: none;"><g transform="translate(0,5)"></g></g></g></g><g role="tooltip" visibility="hidden" opacity="0"><g fill="#000000" fill-opacity="1" stroke-width="1" stroke-opacity="1" stroke="#000000" transform="translate(-25,5)" style="pointer-events: none;"><path d="M0,0 L20,0 a0,0 0 0 1 0,0 L20,0 L20,0 L25,10 L20,10 L20,10 a0,0 0 0 1 -0,0 L0,10 a0,0 0 0 1 -0,-0 L0,0 a0,0 0 0 1 0,-0"></path></g><g><g fill="#ffffff" transform="translate(-15,5.0001)" style="pointer-events: none;"><g transform="translate(0,5)"></g></g></g></g><g role="tooltip" visibility="hidden" opacity="0"><g fill="#ffffff" fill-opacity="0.9" stroke-width="1" stroke-opacity="1" stroke="#ffffff" filter="url(&quot;#filter-id-1477&quot;)" transform="translate(6,-5.5)" style="pointer-events: none;"><path d="M3,0 L21,0 a3,3 0 0 1 3,3 L24,8 a3,3 0 0 1 -3,3 L3,11 a3,3 0 0 1 -3,-3 L0,8 L0,10.5 L-6,5.5 L0,0.5 L0,3 a3,3 0 0 1 3,-3"></path></g><g><g fill="#ffffff" transform="translate(18,-5.5)" style="pointer-events: none;"><g transform="translate(0,7)"></g></g></g></g></g></g></g></g></svg>`

**Comment by martynasma** [comment]
I don't think we can figure this out unless you post it online. Must be something setup-related. Sorry.
