### ISSUE TITLE
Conditional import for browser-only dependencies

### ISSUE THREAD

**Issue by grdnrt** [amcharts/amcharts4#2035]
Hello,

I'm having an issue when trying to build a Gatsby app using amCharts. Minimal repro [here](https://github.com/grdnrt/gatsby-charts-repro).

The issue appears to be caused by the dynamic import on [this line](https://github.com/amcharts/amcharts4/blob/master/src/.internal/core/export/Export.ts#L4779), as canvg does not have proper support for SSR ([#627](https://github.com/canvg/canvg/issues?q=is%3Aissue+server+side+is%3Aclosed)). Maybe a more safe import could be something as described in the cited issue, checking for the existence of browser objects and conditionally making the import.

I've tried to fork the package and make a fix but didn't succeed at building it on macOS Catalina v. 10.15 with Node v. 13.2.0.

Thanks!

**Comment by Pauan** [comment]
amCharts is a browser-only library, it needs access to the DOM in order to create the chart elements and attach event listeners.

So conditionally importing canvg won't help, because browser APIs are needed all throughout amCharts.

Your repro doesn't contain amCharts at all, and building it succeeds without any errors. I also tried adding amCharts by [following our tutorial](https://www.amcharts.com/docs/v4/getting-started/integrations/using-react/), and it works fine. Could you please update your repro so it shows the problem?

**Comment by grdnrt** [comment]
Omg sorry, didn't commit the changes to the repo. Can you please check it again?

**Comment by grdnrt** [comment]
FWIK tracing the issue: Gatsby is trying to build everything to serve it in the first load, but as `canvg` is in the declared as a browser dependency, Gatsby is unable to find the module. But that's just what I'm thinking, please correct me if I'm wrong. 

The log errors are the same as the ones in [this issue](https://github.com/amcharts/amcharts4/issues/2027).

**Comment by grdnrt** [comment]
Hey guys! Any updates on this? I would really appreciate it :)

**Comment by Pauan** [comment]
@grdnrt Thanks, I see the error now. I'm working on figuring out why it breaks, but my code doesn't break.

**Comment by grdnrt** [comment]
I got a successful build when commenting the import of `canvg` in the file `Export.ts`. But that was directly in the build inside my project. I didn’t succeed at making the change in the source and building it. I'm looking now at why is the build failing.

**Comment by Pauan** [comment]
@grdnrt I was able to fix the immediate error by doing `yarn add canvas jsdom xmldom`, could you check and see if that fixes it for you?

**Comment by grdnrt** [comment]
@Pauan That makes sense.

But after installing the dependencies, I got a different error:

```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected character '�' (1:0)

File: node_modules/canvas/build/Release/canvas.node:1:0
```

Both in the actual project and the repro. I've also tried with Node v. 10.15.1 but no luck whatsoever.

**Comment by Pauan** [comment]
@grdnrt That's very strange, I wasn't getting that error when I tested it before, but I'm getting it now.

I found [this issue](https://github.com/gatsbyjs/gatsby/issues/17661#issuecomment-532424504) which says that you should add this to your `gatsby-node.js` file:

```js
exports.onCreateWebpackConfig = ({
  stage,
  rules,
  loaders,
  plugins,
  actions,
}) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /canvas/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
};
```

Now everything builds and works correctly.

**Comment by grdnrt** [comment]
Beautiful, thank you so much! @Pauan 

It makes real sense that Gatsby provides a general solution, it works perfectly. 

Thank you again for the time, really appreciated.

**Comment by Pauan** [comment]
Great, I'm glad you got it working!
