### ISSUE TITLE
Gantt chart on 2 category axes

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#2036]
As I can see from documentation ColumnSeries has `dataFields.openCategoryX` field. So it makes me think it's possible to plot a Gantt chart not on Category & Date axes, but on two Category axes (what I need actually). Am I right?
So basically I want something like this:
https://codepen.io/dmsmaxim/pen/XWJYMwP?editors=1010
```
xAxis.dataFields.openCategory = "fromDate";
```
But `ICategoryAxisDataFields` doesn't have `openCategory` field...

**Comment by martynasma** [comment]
`CategoryAxis` does not have to have an open data field because it just provides a scale.

You should be putting it on series, if you want some column to span multiple categories.

E.g.:

```
series1.dataFields.openCategoryX = "fromX";
series1.dataFields.categoryX = "toX";

series1.dataFields.openCategoryY = "fromY";
series1.dataFields.categoryY = "toY";
```
