### ISSUE TITLE
Sankey node positioning issue

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#2037]
Hi,

Here's the [example codepen](https://codepen.io/npc42/pen/OJPEByR?editors=0010). Note that links are defined from Printer, to Glue2, to Die Coater — I'd expect them to show each on their own line, but for some reason last two are shown together.

If I remove the node definition sections from .data, then they draw correctly. But I use these to define additional node-related property .fromDesc, which is used by node's tooltipHTML. Perhaps you'll advise a better way to define this.

PS Using middleLine as mentioned [here](https://github.com/amcharts/amcharts4/issues/120#issuecomment-573252094).

**Comment by sunco007** [comment]
The fisrt data needs: "toCode": "Glue2\nKraft 2020-08-92", 

The third data needs: "toCode": "Die Coater\nShrink 2020-07-82", 

I mean, you are not specifying where to connect

**Comment by NPC** [comment]
Thanks for trying to help, @sunco007, but this is correct. I'm using non-linking data entries to populate fromDesc for corresponding nodes (used node tooltips) — otherwise I can't specify different data values for two nodes on the same link.

It works as expected in most cases, too, but this one gets the Sankey stumped, for some reason.

**Comment by zeroin** [comment]
It's a bit complicated, but you can solve this by sorting the initial list of nodes in the same order as they need to be: https://codepen.io/team/amcharts/pen/dfc1371e27730bcdb737c3b000ed4f27?editors=0010

**Comment by NPC** [comment]
@zeroin OK, so I'll try to supply them in the order of “levels”, works for me, thank you!
