### ISSUE TITLE
How to prevent pull out effect when clicking on pie chart slice using JSON config ? 

### ISSUE THREAD

**Issue by XxSven** [amcharts/amcharts4#2038]
Hello,

I can't find how to prevent the active pull out effect from happening, nor the hovering scale effect when using the JSON config of the PieChart. What am I missing ?
Here is a codepen of my try :
https://codepen.io/XxSven/pen/WNbyVqR

Thanks for the support !

**Comment by dmsmaxim** [comment]
`series` and `slices` are objects, not arrays as in your example.

You can see it in the documentation:
![image](https://user-images.githubusercontent.com/15041200/72342646-9ab97200-36d5-11ea-91f7-bd816b8db317.png)

**Comment by XxSven** [comment]
Thank you ! 
I was using this doc which uses an array for slices : 
https://www.amcharts.com/docs/v4/tutorials/disabling-default-hover-and-click-effects-on-pie-chart/#Disabling
Using object notation worked. But series should still be used as an array otherwise it won't work.
It would be nice to update the doc :)
