### ISSUE TITLE
How to prevent TreeMap showing 0 value's labelBullet

### ISSUE THREAD

**Issue by shichenglu** [amcharts/amcharts4#2039]
Hi,

I am trying to updating treemap's data by directly change value field and invalidateRawdata, for example, the data is like this:
[{
  "name": "A",
  "children": [
    { "name": "A1", "value": 100, "value2":200 },
    { "name": "A2", "value": 0, "value2":100},
    { "name": "A3", "value": 30, "value2":200 }
  ]
}, {
  "name": "B",
  "children": [
    { "name": "B1", "value": 135, "value2":200 },
    { "name": "B2", "value": 98, "value2":100},
    { "name": "B3", "value": 56, "value2":200 }
  ]
}]
I can set chart.dataFields.value = "value2" to update the chart data, this methods works fine for the treeMap itself, however, I experiencing an issue with the labelBullet, since some data has zero value,  so the treeMap block won't show up, but the labelBullet will still show for that zero data, it makes the chart looks wired, is there a way to prevent labelBullet show up for those zero data?
Thanks!

**Comment by martynasma** [comment]
You may try using `hideOversized` on the label. If set to `true` it will automatically hide labels that do not fit into their respective columns, which means none of the zero-value labels will show up.

```
labelBullet.label.hideOversized = true;
```

**Comment by shichenglu** [comment]
Yes, it works! Thanks!
