### ISSUE TITLE
Scrollbar for every axis

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#2041]
Is possible to have a different scrollbar for every axis?   
I have a chart very similar to this:   
https://www.amcharts.com/demos/stock-chart/   
But I want to be able to zoom and move the main chart without modifying the zoom level of the bottom chart/axis.
I have tried with this: 
```
chart.events.on("ready", function(ev) {
  valueAxis.min = valueAxis.minZoomed;
  valueAxis.max = valueAxis.maxZoomed;
});
```
from: https://www.amcharts.com/docs/v4/tutorials/fixed-value-axis-scale/
But moving the scroll bar is affecting the extra series/axis too. I want to keep them in sync with the time (horizontal) axis, but I want to zoom/pan the vertical (values) axis individually

Maybe it's easier to create different charts instead of different axis and sync them, like in this example:
https://www.amcharts.com/docs/v3/tutorials/using-syncwithcursor-sync-cursor-across-several-serial-charts/
Is there any example to do the same with v4?

**Comment by martynasma** [comment]
There's no built-in way to have separate scrolling for multiple axes, I'm afraid.

So yeah, probably better to have two charts with synced zooms.

**Comment by enriquepiatti** [comment]
I'm using these tutorials to sync both charts:
https://www.amcharts.com/docs/v4/tutorials/handling-axis-zoom-events-via-api/
https://www.amcharts.com/docs/v4/tutorials/tracking-cursors-position-via-api/
https://www.amcharts.com/docs/v4/tutorials/positioning-xy-cursor-via-api/ (with sticky cursor)

And seems to be working but I have a problem:
The horizontal axis (common in both charts) is not perfectly aligned, because the scrollbar from the first chart is taking some space (and is not present in the extra chart) and because both values scales have very different values, hence they have different width. The final result is both chart have different widths.

**Comment by martynasma** [comment]
I suggest you hold off for now. We're working on built-in axis syncing functions as we speak.

If all is good (and it's looking that way), they should be rolled into the next version.

It will be immensely easier than implementing syncing on your own.

Stay tuned :)

https://github.com/amcharts/amcharts4/releases

**Comment by enriquepiatti** [comment]
Perfect, thanks !!

**Comment by martynasma** [comment]
OK, so I jumped the gun. We're not going to be adding those functions after all.

Can you post what you have so far, and I'll take a look if maybe there's some clever way to compensate for those different widths?

**Comment by enriquepiatti** [comment]
ok :(
This is https://www.amcharts.com/demos/stock-chart/ example but with a scrollbarY   
https://codepen.io/enriqu3/pen/jOEorRb   
The problem is the zoom will affect the columns bar too.   

This is the solution with two charts in sync: https://codepen.io/enriqu3/pen/gObJMyE
well now is not working at all, I was trying to simplify the code because my code is too complex to separate in a working example, but now if I uncomment the line:
// var series2 = chart2.series.push(new am4charts.ColumnSeries());
to enable the second chart everything crashes, if you can tell me what's the problem there I can continue adding the code to sync both charts
