### ISSUE TITLE
Chart jumping when scrolling

### ISSUE THREAD

**Issue by AnastasiiaTsvetkova** [amcharts/amcharts4#2042]
Hi!
When I am scrolling date, chart is jumping. It happens when dates were grouped by date from hours to days.  How can I prevent this behavior?
![4](https://user-images.githubusercontent.com/55182060/72516024-a6ce3c80-3859-11ea-887e-90f419eeb250.gif)

Thanks

**Comment by martynasma** [comment]
Can you please post your full chart code and data so that we can check?

Usually, this happens when Date-based data comes in any other order than ascending.

Please doublecheck.

**Comment by AnastasiiaTsvetkova** [comment]
Thanks. It happened because of other order than ascending
