### ISSUE TITLE
Stock Graph balloon text not wrapping

### ISSUE THREAD

**Issue by amirh19** [amcharts/amcharts4#2043]
I'm using an Strock Graph with ChandlerStick graph, but the balloon text is not being wrapped. This issue is resolved after resizing screen. No css or media queries are applied.
![image](https://user-images.githubusercontent.com/59974280/72551013-94ec9980-3859-11ea-9bec-639bacd9470b.png)
After resizing to mobile
![image](https://user-images.githubusercontent.com/59974280/72551140-dda45280-3859-11ea-8f37-47bf7fc2615f.png)
![image](https://user-images.githubusercontent.com/59974280/72551223-0cbac400-385a-11ea-9c2b-c43669d6495b.png)
Setup:

@amcharts/amcharts4 : ^4.0.0-beta.28"
@angular/cdk: "^5.0.0",
@angular/cli: "^1.7.4",
Windows 10 x64

This proyect create the stock chart and switches between types 
`changeTypeGraph(type, id) {

    $(".icon-chart").removeClass("active");
    $("#" + id).addClass("active");

    this.type_chart = type;
    if (this.chart.panels[0].stockGraphs[0] !== undefined) {
      switch (this.type_chart) {
        case "line":
          this.chart.panels[0].stockGraphs[0].type = "line";
          this.chart.chartScrollbarSettings.graph.type = 'line';
          this.chart.chartScrollbarSettings.graph.lineAlpha = 0.5;
          this.chart.chartScrollbarSettings.graph.fillAlphas = 0;
          this.chart.chartScrollbarSettings.graph.lineThickness = 2;
          this.chart.panels[0].stockGraphs[0].balloonText = this.IndicatorTranslate.cfClose + ": [[value]]";
          break;
        case "area":
          this.chart.panels[0].stockGraphs[0].type = "serial";
          this.chart.chartScrollbarSettings.graph.type = 'line';
          this.chart.chartScrollbarSettings.graph.lineAlpha = 0.5;
          this.chart.chartScrollbarSettings.graph.fillAlphas = 0.3;
          this.chart.chartScrollbarSettings.graph.lineThickness = 2;
          this.chart.panels[0].stockGraphs[0].balloonText = this.IndicatorTranslate.cfClose + ": [[value]]";
          break;
        case "candlestick":
        case "candlestickhollow":
          this.chart.panels[0].stockGraphs[0].type = "candlestick";
          this.chart.panels[0].stockGraphs[0].lowField = "low";
          this.chart.panels[0].stockGraphs[0].highField = "high";
          this.chart.panels[0].stockGraphs[0].openField = "open";
          this.chart.panels[0].stockGraphs[0].closeField = "close";
          this.chart.chartScrollbarSettings.graph.type = 'candlestick';
          this.chart.chartScrollbarSettings.graph.lineAlpha = 0.5;
          this.chart.chartScrollbarSettings.graph.fillAlphas = 0.5;
          this.chart.chartScrollbarSettings.graph.lineThickness = 1;
          this.chart.panels[0].stockGraphs[0].balloonText = this.IndicatorTranslate.cfClose + ": [[value]]<br/>" + this.IndicatorTranslate.cfOpen + ": [[open]]<br/>" + this.IndicatorTranslate.cfHigh + ": [[high]]<br/>" + this.IndicatorTranslate.cfLow + ": [[low]]";
          this.chart.panels[0].stockGraphs[0].negativeFillColors = "#F33940";
          this.chart.panels[0].stockGraphs[0].negativeLineColor = "#F33940";
          this.chart.chartScrollbarSettings.graphType = "line";
          console.log(this.chart);
          break;
      }

      if (this.type_chart === "candlestickhollow") {
        this.chart.panels[0].stockGraphs[0].proCandlesticks = true;
      } else {
        this.chart.panels[0].stockGraphs[0].proCandlesticks = false;
      }

      this.chart.validateNow();
    }
  }`

Some classes declared:
`this.chart = AmStockChart;

this.chart.panels[] = AmStockPanel;

this.chart.panels[].stockGraphs[] =  StockGraph;

`
Please note above is not code, just class references.
 

This is the initial view, then switches between chart's types.
![image](https://user-images.githubusercontent.com/59974280/72552000-9ae37a00-385b-11ea-84a1-0d6467375423.png)

**Comment by martynasma** [comment]
This is a repository for amCharts 4, whereas your code is for a different product: amCharts 3: Stock Chart.

If you have a support subscription I suggest you contact amCharts directly for support.
