### ISSUE TITLE
Incorrect year for january  

### ISSUE THREAD

**Issue by AnastasiiaTsvetkova** [amcharts/amcharts4#2044]
Hi! 
I have dates value from 1 October to 17 January.
When dates are grouped by month January showed with the year 2019. How can I fix it?

Example of my data: [{
value: 0,
date: "Fri Jan 17 2020 20:00:00 GMT+0200 (Eastern European Standard Time)"
},
{
value: 0,
date: "Fri Jan 17 2020 21:00:00 GMT+0200 (Eastern European Standard Time)"
},
{
value: 0,
date: "Fri Jan 17 2020 22:00:00 GMT+0200 (Eastern European Standard Time)"
},
{
value: 0,
date: "Fri Jan 17 2020 23:00:00 GMT+0200 (Eastern European Standard Time)"
}]

chart.dateFormatter.inputDateFormat = 'DD-MMM-YY HH:mm'

![image](https://user-images.githubusercontent.com/55182060/72600145-c168ea00-391b-11ea-9823-10a559cbc455.png)

**Comment by martynasma** [comment]
You're using wrong code for a year. "Y" (uppercase) means week year, meaning what was the year the week representing this label started on. January 1st 2020, belongs to a week that started in December 2019.

For a proper year use lowercase "y".

More on codes here:
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-date-time/#Format_codes
