### ISSUE TITLE
How to resize width of chart?

### ISSUE THREAD

**Issue by ariefsn** [amcharts/amcharts4#2045]
Hi, I use amCharts v4 on my Vue app.
The app has a sidebar when it's expanded or collapse the chart not resized.

![PA-AmChart-Case](https://user-images.githubusercontent.com/33569737/72600864-fe96a180-3946-11ea-9792-aadcbdb6bcac.gif)

Charts in the right column, it's not resized.

How to resize the chart? Without rebuild/recreate it.

**Comment by martynasma** [comment]
The chart is designed to automatically resized when its parent container resizes.

It means that the size of the container does not change when you toggle the menu.

Make sure it does and the chart will resize together with it.

**Comment by ariefsn** [comment]
> The chart is designed to automatically resized when its parent container resizes.
> 
> It means that the size of the container does not change when you toggle the menu.
> 
> Make sure it does and the chart will resize together with it.

But why the other component (like the map) can be resized?

**Comment by martynasma** [comment]
> But why the other component (like the map) can be resized?

I don't know. Could be a million of reasons. Without seeing this app live it'd be just guesswork.

**Comment by ariefsn** [comment]
> > But why the other component (like the map) can be resized?
> 
> I don't know. Could be a million of reasons. Without seeing this app live it'd be just guesswork.

Thanks for your response :)
The chart needs to be disposed of first, before rebuilding it again.
It solves the resized's case.
🙏🏻
