### ISSUE TITLE
Calculate the breakSize in AxisBreak

### ISSUE THREAD

**Issue by sunco007** [amcharts/amcharts4#2046]
I'm struggling on how to calculate the breakSize. The [docs](https://www.amcharts.com/docs/v4/reference/axisbreak/) says:

**A size of the break relative to the actual size of the scope break spans.

For example, if breakSize = 0.1 and unbroken scope of _b_alues it spans would be 100 pixels, the break would be 10 pixels wide.**

I already modified the example https://www.amcharts.com/demos/column-chart-with-axis-break/ to make all numbers dynamic

Only thing can't convert is the formula for that breakSize

**Comment by martynasma** [comment]
Thanks for the heads up about the typo, we'll fix that.

Back to original question: I'm trying to wrap my head around what kind of calculation you need for the break size. The value of the `breakSize` is a relative number to the actual width/height of the axis, so it is calculated automatically.

It's designed specifically for the purpose of taking up a fixed width/height regardless of actual scope of values on the axis.

Can you explain how what you are trying to achieve?

**Comment by sunco007** [comment]
Oks, thans for your reply

On the example of column-chart-with-axis-break, let's say we will change the max value, the USA = 23725

Value = 23725 - breakSize = 0.005 - Looks great

Value = 13725 - breakSize = 0.005 - Looks small

Value = 13725 - breakSize = Not set - Looks great

Value = 3725 - breakSize = 0.005 - Looks no space between lines

Value = 3725 - breakSize = Not set - Looks no space between lines

So, I want to calculate that 0.005 so the result can fit with any values

**Comment by martynasma** [comment]
Can you post a full example of a chart in which axis break does not look great?

That demo contains a lot of settings that affect axis scale and position/size of the axis break, not just the max value. (break start end values, axis min/max, etc.)

**Comment by sunco007** [comment]
Yes, sure - https://codepen.io/sunco/pen/VwYGgmR?editors=0010

**Comment by zeroin** [comment]
I updated our demo: https://www.amcharts.com/demos/column-chart-with-axis-break/
So that the break is of the fixed size, no matter the span of the break.

The formula which calculates the needed size is:
`var d = (axisBreak.endValue - axisBreak.startValue) / (valueAxis.max - valueAxis.min);
axisBreak.breakSize = 0.05 * (1 - d) / d;`

where 0.05 means that the break should occupy about 5% of the value axis.

**Comment by sunco007** [comment]
Yay, that's the answer I was looking for. Thanks a lot. Works great :smiley:
