### ISSUE TITLE
How to display the column tooltip on hover of category axis label

### ISSUE THREAD

**Issue by lgerndt** [amcharts/amcharts4#2047]
Hi, is it possible to hook things up such that upon hover of a category axis label, the corresponding column's tooltip is displayed?

**Comment by martynasma** [comment]
I suppose it is doable with `XYCursor` and triggering its move via API:

```
categoryAxis.renderer.labels.template.events.on("over", function(ev) {
  var point = categoryAxis.categoryToPoint(ev.target.dataItem.category);
  chart.cursor.triggerMove(point, "soft");
});
```

https://codepen.io/team/amcharts/pen/gObBeXm

**Comment by lgerndt** [comment]
That works (thank you!) but would it be possible to hide the tooltip when the mouse is not hovering over a label or a column?  Our current implementation does that for the columns, because critics were saying that having the tooltip always on no matter where you hover is a bit distracting.

**Comment by martynasma** [comment]
This'll do it:

```
categoryAxis.renderer.labels.template.events.on("out", function(ev) {
  var point = categoryAxis.categoryToPoint(ev.target.dataItem.category);
  chart.cursor.triggerMove(point, "none");
});
```

**Comment by lgerndt** [comment]
Perfect!!  Thank you so much for quickly responding, Marty!

**Comment by lgerndt** [comment]
One more ask, if you please:  can we also do this: on hover over a bar, bold the label?

**Comment by lgerndt** [comment]
bump

**Comment by lgerndt** [comment]
bump
