### ISSUE TITLE
Lines crossing into the void given certain latitude / longitude

### ISSUE THREAD

**Issue by lamoni** [amcharts/amcharts4#2049]
I'm getting an issue (I'm sure it's expected, but I can't find an option to turn it off) with lines taking a "shortcut" through the edge of the map. Is there a proper way I can make the lines cross the map instead of "shortcutting"?:

<img width="635" alt="Screen Shot 2020-01-18 at 6 15 26 PM" src="https://user-images.githubusercontent.com/5675626/72673398-c367a180-3a1e-11ea-80a7-a3bf69ce2a71.png">

**Comment by martynasma** [comment]
To avoid that, you'll need to disable line series' `shortestDistance`.

https://www.amcharts.com/docs/v4/chart-types/map/#Curved_vs_straight_lines

**Comment by lamoni** [comment]
Thank you, that worked! Closing issue

**Comment by eapatel** [comment]
Hi @martynasma, I'm not able to see shortestDistance in v5 version. What should be alternative to fix it?
