### ISSUE TITLE
Poor performance while using chart.animate

### ISSUE THREAD

**Issue by dordana** [amcharts/amcharts4#2050]
Hey,

I have a poor performance while using chart.animate to center the globe.
It seems to be very heavy and slow and compromises performance, plus there are bugs and blasts in the animation (high latency).

Code: 
`am4core.useTheme(am4themes_animated);
var chart = am4core.create("chartdiv", am4maps.MapChart);
chart.geodata = am4geodata_worldLow;
chart.maxZoomLevel = 1;
chart.responsive.enabled = true;
chart.maxZoomLevel = 1;
chart.seriesContainer.draggable = false;
chart.seriesContainer.resizable = false;
var interfaceColors = new am4core.InterfaceColorSet();
chart.geodata = am4geodata_worldLow;
chart.projection = new am4maps.projections.Orthographic();
chart.panBehavior = "rotateLongLat";
chart.deltaLatitude = 0;
chart.deltaLongitude = 0;
chart.padding(20, 20, 20, 20);
var polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
polygonSeries.useGeodata = true;
polygonSeries.calculateVisualCenter = true;
polygonSeries.tooltip.background.fillOpacity = 0.2;
polygonSeries.tooltip.background.cornerRadius = 20;
var template = polygonSeries.mapPolygons.template;
template.nonScalingStroke = true;
template.fill = am4core.color(VARIABLES.continentsColor);
template.stroke = am4core.color(VARIABLES.continentsColor);
let graticuleSeries = chart.series.push(new am4maps.GraticuleSeries());
graticuleSeries.mapLines.template.line.stroke = am4core.color("#ffffff");
graticuleSeries.mapLines.template.line.strokeOpacity = 0.1;
graticuleSeries.fitExtent = false;
chart.backgroundSeries.mapPolygons.template.polygon.fillOpacity = 1;
chart.backgroundSeries.mapPolygons.template.polygon.fill = am4core.color(VARIABLES.seasColor);
polygonSeries.calculateVisualCenter = true;
template.propertyFields.id = "id";
template.tooltipPosition = "fixed";
template.fillOpacity = 1;
try {
    chart.geodata = am4geodata_worldLow;
} catch (e) {
    chart.raiseCriticalError(new Error('Map geodata could not be loaded. Please download the latest <a href="https://www.amcharts.com/download/download-v4/">amcharts geodata</a> and extract its contents into the same directory as your amCharts files.'));
}
chart.projection = new am4maps.projections.Orthographic();
chart.zoomDuration = 0
chart.panBehavior = "rotateLong";
let animation;
let freeRotateGlobe = null;
/******* On mouse over *******/
let circleSeries = chart.series.push(new am4maps.MapPolygonSeries());
console.log('document.getElementsByClassName("cube1")[0] :', document.getElementsByClassName("cube1"));
document.getElementsByClassName("cube1")[0].onmouseover = function() {
    let circleTemplate = circleSeries.mapPolygons.template;
    circleTemplate.fill = am4core.color(VARIABLES.coordinateForCube1.color);
    circleTemplate.strokeWidth = 2;
    circleTemplate.stroke = am4core.color("#fff");
    circleTemplate.fillOpacity = 0.75;
    let polygon = circleSeries.mapPolygons.create();
    polygon.multiPolygon = am4maps.getCircle(VARIABLES.coordinateForCube1.latitude + 3, VARIABLES.coordinateForCube1.longitude - 3, 1.2);
    rotateTo({
        latitude: VARIABLES.coordinateForCube1.latitude,
        longitude: VARIABLES.coordinateForCube1.longitude
    }, VARIABLES.coordinateForCube1.offSetX, VARIABLES.coordinateForCube1.offsetY);
};
document.getElementsByClassName("cube2")[0].onmouseover = function() {
    let circleTemplate = circleSeries.mapPolygons.template;
    circleTemplate.fill = am4core.color(VARIABLES.coordinateForCube2.color);
    circleTemplate.strokeWidth = 2;
    circleTemplate.stroke = am4core.color("#fff");
    circleTemplate.fillOpacity = 0.75;
    let polygon = circleSeries.mapPolygons.create();
    polygon.multiPolygon = am4maps.getCircle(VARIABLES.coordinateForCube2.latitude + 20, VARIABLES.coordinateForCube2.longitude + 20, 1.2);
    VARIABLES.coordinatesChildrensForCube2.forEach(c => {
        let polygon = circleSeries.mapPolygons.create();
        polygon.multiPolygon = am4maps.getCircle(c.latitude, c.longitude, 1.2);
    });
    rotateTo({
        latitude: VARIABLES.coordinateForCube2.latitude,
        longitude: VARIABLES.coordinateForCube2.longitude
    }, VARIABLES.coordinateForCube2.offSetX, VARIABLES.coordinateForCube2.offsetY);
};
document.getElementsByClassName("cube3")[0].onmouseover = function() {
    let circleTemplate = circleSeries.mapPolygons.template;
    circleTemplate.fill = am4core.color(VARIABLES.colorOfCoordinatesForCube3);
    circleTemplate.strokeWidth = 2;
    circleTemplate.stroke = am4core.color("#fff");
    circleTemplate.fillOpacity = 0.75;
    VARIABLES.capitalCitiesCube3.forEach(c => {
        let polygon = circleSeries.mapPolygons.create();
        polygon.multiPolygon = am4maps.getCircle(c.latitude, c.longitude, 1.2);
    });
    setFreeRotateGlobe();
};
/******* On mouse leave *******/
document.getElementsByClassName("cube1")[0].onmouseleave = function() {
    removeCities();
};
document.getElementsByClassName("cube2")[0].onmouseleave = function() {
    removeCities();
};
document.getElementsByClassName("cube3")[0].onmouseleave = function() {
    removeCities();
    if (animation) {
        animation.stop();
    }
};
/******* Functions *******/
function rotateTo({
    longitude,
    latitude
}, longitudeOffset = 0, latitudeOffset = 0) {
    if (animation) {
        animation.stop();
    }
    animation = chart.animate(
        [{
            property: "deltaLongitude",
            to: longitude + longitudeOffset
        }, {
            property: "deltaLatitude",
            to: latitude + latitudeOffset
        }], 400, am4core.ease.cubicInOut);
}

function removeCities() {
    circleSeries.removeChildren();
}

function setFreeRotateGlobe() {
    animation = chart.animate(
        [{
            property: "deltaLongitude",
            to: 100000
        }, {
            property: "deltaLatitude",
            to: 100000
        }], 20000000);
}
})`

help?

**Comment by martynasma** [comment]
Can you post it as a CodePen or jsFiddle?
