### ISSUE TITLE
How to stop data hiding when I zoom in on multi axes line chart

### ISSUE THREAD

**Issue by JamesDolphin** [amcharts/amcharts4#2051]
When I use the zoom control (highlight an area to zoom into it) or a scroll bar ( when moving right side control to the left) my data becomes invisible.

REf: https://www.amcharts.com/demos/multiple-value-axes/

If I mouse over the chart I still see popups of values but the visual representation of the line is not visible. 

[Hidden data](https://i.stack.imgur.com/RBT6O.png)

[Working data](https://i.stack.imgur.com/9ja2t.png)

**Comment by martynasma** [comment]
It looks like the chart in your screenshot is a modified version of that demo.

Can you post it in full on CodePen/jsFiddle, as I can't seem to be able to reproduce the issue on the demo you linked to.

**Comment by JamesDolphin** [comment]
Below has what I am using. Data format is { "date" : date, "option1" : option1Value, "option2": option2Value }
https://jsfiddle.net/8x70zwgv/

Data is displaying perfectly unless I zoom in. Essentially it breaks of the righthand side of the chart is not displaying the final values of the dataset

**Comment by martynasma** [comment]
Is your data in ascending order? (hint: it must be)

**Comment by JamesDolphin** [comment]
Will have to check tomorrow, its displaying in the correct order but I assume if its reversed it may stuff up the zoom

**Comment by JamesDolphin** [comment]
Thanks @martynasma that was the solution, nice to see amCharts could handle displaying data in a reversed order, even better than when I do my part all the rest works as well : )
