### ISSUE TITLE
How do I get the Y Axis Value from a ValueAxis? 

### ISSUE THREAD

**Issue by franny2491** [amcharts/amcharts4#2053]
I have used the example Step count chart, however I would like to represent the data of the y axis (normally represented via the tooltip) in a separate area so I can run a computation on it. 

How would I add an adapter to get this value? I have tried 'tooltipText' from the series and 'getTooltipText' on the ValueAxis. Neither seem to get the result that is shown on that tooltip. 

I feel like I might be missing something simple?

Thanks,

**Comment by martynasma** [comment]
Can you provide more details, like what from do you want to get the value for? Like cursor position, hovered bullet, something else?

If you can post your chart as a CodePen that would be great.

**Comment by franny2491** [comment]
Hi @martynasma 

The chart is pretty much the Step count chart as on your website. I was aiming to get the value for my own hovered bullet instead of your own tooltip. I'm not interested in the cursor position, just the y value that is currently in the middle (the tooltip on the series) 

Thanks,

**Comment by martynasma** [comment]
OK, in this case you can use bullet's "over" event:

```
bullet.events.on("over", function(ev) {
  console.log(ev.target.dataItem);
});
```

**Comment by franny2491** [comment]
Ahhh ok, how would that work with the Step count chart - I don't see bullets anywhere in the code?

https://www.amcharts.com/demos/step-count-chart/ is the demo I am using. The tooltip calls out the value, that's the value I want. Is it the column 'over' event?

Thanks,

**Comment by martynasma** [comment]
In that case you would put an event handler on a column template:

```
series.columns.template.events.on("over", function(ev) {
  console.log(ev.target.dataItem);
});
```
