### ISSUE TITLE
Keep value outside of subscribe

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#2055]
Hello,

Using this function: 
```
 this.service.getCity(originCityForm.value.origin).subscribe(city => {
      this.originCity.push(city);
      this.originImageSeries.data = this.originCity;
```
and
getCity: 
```
  getCity(title: string): Observable<City> {
    return this.http.get<City>(this.baseUrl + "/api/" + title);
  }
```
I have notice that when I am in the subscribe function, I have all the data (this.originCity and this.originImageSeries.data) that I need but once the subsciption is done, all the data (this.originCity and this.originImageSeries.data) disappears.

![Screen Shot 2020-01-20 at 8 12 52 PM](https://user-images.githubusercontent.com/33300743/72767203-432d7180-3bc1-11ea-86a3-94b8d3d77b60.png)

**Comment by martynasma** [comment]
I don't think this is related to amCharts 4. It's rather how references to objects are kept in your application. Sorry can't help.
