### ISSUE TITLE
Handle "Mouse out" event on lineSeries? 

### ISSUE THREAD

**Issue by quangdnptit** [amcharts/amcharts4#2056]
Hi Amchart4 team, the first thing I would like to say Amchart4 is one of the best libraries for draw chart :>

as the title, How can I handle the "mouse out" event line series? I try to use 
**series.segments.template.events.on(
      "out", () => {
}}**
and 
**series.events.on("over", getOverCallback($vm.chart, $vm))**
but I seem not work, please help, thanks

**Comment by martynasma** [comment]
Series segments has interactions disabled by default, hence all over/out events not working.

Try enabling them:

```
series.segments.template.interactionsEnabled = true;
```

**Comment by quangdnptit** [comment]
![image](https://user-images.githubusercontent.com/31880059/72799642-46376900-3c78-11ea-82d3-103578b92913.png)
I'm trying to disable tooltip when mouse out this line, is it possible ?

**Comment by quangdnptit** [comment]
as you can see, tooltip still display after **mouse out** series area

**Comment by quangdnptit** [comment]
I turned on the Series segments interactions but It seems not work

**Comment by martynasma** [comment]
Can you post your whole chart on CodePen?

**Comment by quangdnptit** [comment]
Sorry, I need more time to remove redundant parts and push it to CodePen, I will come back soon, thank for your support
