### ISSUE TITLE
ForceDirectedSeries: Last(MInimum Size Circle)Child Circle how to overwrite the Inline Style of Default Cursor None

### ISSUE THREAD

**Issue by sarankumar87** [amcharts/amcharts4#2057]
In am4plugins_forceDirected.ForceDirectedSeries():Last(MInimum Size Circle)Child Circle how to overwrite the Inline Style of Default Cursor None.

nodeTemplate.events.on("over", function (event) {
            var dataItem = event.target.dataItem;
            dataItem.childLinks.each(function (link) {
                link.isHover = true;
            })
        })

After doing like this also , inline styles are  not overwriting . and for the child circle cursor pointer is not changing.

**Comment by zeroin** [comment]
Could you explain, do you need to show some different cursor on all nodes or only on some of them?
In case on all, this should work fine:

`networkSeries.nodes.template.cursorOverStyle = am4core.MouseCursorStyle.pointer;`

**Comment by sarankumar87** [comment]
I tried same.. is was not working for Last child(minimum size circle) circle.

**Comment by zeroin** [comment]
Sorry, I forgot that we set this dynamically based on the fact if the node has children or not. So if you need pointer on all nodes, you need to add adapter for cursorOptions:

https://codepen.io/team/amcharts/pen/0b09cef8202ea9497f3b70d9493b8b7e

```
networkSeries.nodes.template.adapter.add("cursorOptions", function(options) {
  options.overStyle = am4core.MouseCursorStyle.pointer;
  return options;
});
```

**Comment by sarankumar87** [comment]
Sounds Good , yes its Working fine.  tq so much
