### ISSUE TITLE
How can I point my external nested json to my heat map?

### ISSUE THREAD

**Issue by mx316** [amcharts/amcharts4#2058]
Hello all,

I have read that nested json is not supported so what are my possibilities?

My current json structure looks like:
`{
  "id": “1”
  	“map”: [{
		“value”: [{
			"id": "EG",
			"name": "Egypt",
			"value": 1
		}, {
			"id": "GH",
			"name": "Ghana",
			"value": 1
		}, {
			"id": "HN",
			"name": "Honduras",
			"value": 2
		}]
	}]
}`

My question is, how could I drill down to value and point to the id,name and value. Can we manipulate with polygonSeries.data? Sidenote: Map will be a part of VueJS app.

Thanks a lot for your help!

**Comment by martynasma** [comment]
If you can't manipulate your source data, your next best thing is to reformat the data using `beforedatavalidated` event:

```
series.events.on("beforedatavalidated", function(ev) {
  var data = ev.target.data;
  // manipulate data
  ev.target.data = data;
});
```

**Comment by mx316** [comment]
But how could I manipulate it in my case if it is not too much to ask?

Thanks!

**Comment by martynasma** [comment]
You manipulate by writing a code that takes data in your input format, and produces in a format that amCharts accepts.

I've pointed in the direction, but writing actual conversion code is a bit out of scope of our support. Sorry.

**Comment by mx316** [comment]
I have managed to solve the issue quite easily though. Thanks for the help.
