### ISSUE TITLE
Risk Heatmap with Date Axis

### ISSUE THREAD

**Issue by clayton-crawford** [amcharts/amcharts4#2059]
Hello! I am trying to implement the Risk Heatmap demo but with a DateAxis for the x-axis. I can't seem to figure out how to make the appearance look the same as in the Risk Heatmap Demo. The series data point columns are only taking up half of the horizontal space and the value labels are at the end of the series data point column (or middle of the entire vertical column section). I assume this has to do with how the DateAxis works for a single date. Any ideas or tips for replicating the Risk Heatmap demo but with a DateAxis? 

The following pen should show an example of the issue I'm facing.  https://codepen.io/AggieCridmus/pen/KKwbMqv

Edit: Updated the pen to better match the original Risk Heatmap demo.

**Comment by zeroin** [comment]
Here is modified pen:
https://codepen.io/team/amcharts/pen/mdyaNrO

For columns to occupy 100% of the day, you need to set:
`series.dataItems.template.locations.dateX = 1;`

And instead of adding bullets as bullets, I added them as children of a column.

**Comment by clayton-crawford** [comment]
@zeroin This is exactly what I was looking for; thank you!
