### ISSUE TITLE
Rendering problem (zoom) with empty category

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#206]
Hello,

I am trying to dynamically add data to serie. There seems to be a rendering problem because of some category that have no value.

Before zooming

![image](https://user-images.githubusercontent.com/6083644/43773850-63670f28-9a47-11e8-9a96-27c1f360e70f.png)

After zooming : 

![image](https://user-images.githubusercontent.com/6083644/43773884-7bfd5ca4-9a47-11e8-9f68-a383551fc1b0.png)

https://codepen.io/ptorrent/pen/mjGYEe

Cursor don't work and XYChartScrollbar too.

I've to add data directly on the serie because of this : 
https://github.com/amcharts/amcharts4/issues/130 

Thanks

**Comment by zeroin** [comment]
My suggestion in this case would be not to use addData() here, instead, you could have all values of columns in your initial data set to 0, then you could modify them and call chart.invalidateRawData() method for columns to update.

**Comment by martynasma** [comment]
@ptorrent 

Let me know if the solution @zeroin suggested works for your requirements.

**Comment by martynasma** [comment]
> I will try but in my case, no data does not mean that the value is 0

Try omitting the value altogether. Not the data point, but the key/value pair where you don't have a value for.

**Comment by ptorrent** [comment]
Ok it's work. Thanks !
