### ISSUE TITLE
show multiple LineSeries separately

### ISSUE THREAD

**Issue by aikodeio** [amcharts/amcharts4#2061]
Hi! I have a graph that shows two lines, but one looks on top of another. Is it possible to display them separately, just like the columns (ColumnSeries)? I need to show both without them hiding over another.

![Captura de pantalla 2020-01-21 19 12 50](https://user-images.githubusercontent.com/47112604/72848319-193c8380-3c83-11ea-9bec-b4321fa352b3.png)

**Comment by martynasma** [comment]
Excellent question!

Yes it is possible to shift LineSeries horizontally using this series setting:

```
series.dataItems.template.locations.categoryX = 0.5;
```

The default is 0.5 which means that it's in the middle.

If you set it to a lower number, the whole series will move to the left, for bigger number, it will move to the right.

You can use it to shift each series individually.

**Comment by aikodeio** [comment]
Excellent! This helped me a lot, but the line connecting both points is misaligned. I searched for information but couldn't find something that specified how to correct that:
https://www.amcharts.com/docs/v4/concepts/series/#Data_item_locations

Thanks!

![gra](https://user-images.githubusercontent.com/47112604/72893450-c7821080-3cf7-11ea-90f8-87914db4594d.jpg)

**Comment by martynasma** [comment]
Can you post your chart online?

**Comment by aikodeio** [comment]
It is already corrected! Thanks again. Can I bother you with two more questions? I have 2 conflicts that I couldn't resolve days ago

**Comment by zeroin** [comment]
Sure, but please, post them as separate issues if they are not related to this one.
