### ISSUE TITLE
Bind zoom in multiple treemaps

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#2064]
I have multiple treemaps on the same page displaying related datasets. I'd like to bind the zoom on a data item of a treemap with the zoom on the corresponding data item in the other treemap : in other words, when the user click on an item, i'd like both treemaps to zoom simultaneously.

I've tried multiple ways (looping on charts `dataItems` property, adding event listeners) but I can't access the data items individually. As treemap series don't seem to be based on the same logic than other types of chart series, I can't find a solution that works..

Thank you for your help!

(In addition, the indexes of the corresponding data items in the two treemaps are not necessarily the same, which implies that they cannot be mapped via the index number.)

Here is a codepen : https://codepen.io/segolene-albouy/pen/vYEQZMX?editors=0010

**Comment by zeroin** [comment]
By the way, it's a nice demo, do you mind if we make a copy of it to our demos page?

**Comment by Segolene-Albouy** [comment]
Thanks a lot for your responsiveness!
Please go ahead :) actually, i'm quite proud if it can make it to the demo page!

**Comment by zeroin** [comment]
Here it is: https://www.amcharts.com/demos/binded-tree-maps/
Should we add some credits of yours?
Thank you for a nice demo!

**Comment by Segolene-Albouy** [comment]
Actually, you did pretty much all the coding work!
But you could mention that the visualization depicts ancient astronomical concepts. It is going to appear on the website of a research project on history of astronomy (https://dishas.obspm.fr/) in the next few months along with other dataviz made with amcharts :).
