### ISSUE TITLE
How to highlight and label a specific column by value?

### ISSUE THREAD

**Issue by slead** [amcharts/amcharts4#2066]
Is it possible to highlight a specific column by its value? Taking the [simple column chart](https://www.amcharts.com/demos/simple-column-chart/) example, how could you highlight the UK column based on its country name?

Based on the sample code in https://github.com/amcharts/amcharts4/issues/1517 I tried adding the `color` to the `chart.data` but this doesn't work (see [JSFiddle](http://jsfiddle.net/slead/w8mzv1tx/13/))

```
{
  "country": "UK",
  "visits": 1122,
  "color": am4core.color("#050"),
}
```

 Is there another way to achieve this? Thanks

**Comment by xorspark** [comment]
I replied to your SO post, but here it is again:

There are two approaches you can take.

1) Use an [adapter](https://www.amcharts.com/docs/v4/concepts/adapters/) on the column's `fill` and `stroke` and check the column value before modifying the color, e.g.

```
series.columns.template.adapter.add('fill', function(fill, target) {  
  if (target.dataItem && target.dataItem.categoryX == "UK") {
    return "#ff0000";
  }
  return fill;
});

series.columns.template.adapter.add('stroke', function(stroke, target) {  
  if (target.dataItem && target.dataItem.categoryX == "UK") {
    return "#ff0000";
  }
  return stroke;
})
```

[Demo](https://codepen.io/team/amcharts/pen/b0933b23b5a6c261ab039b87da6105aa?editors=0010)

2) Use a [property field](https://www.amcharts.com/docs/v4/concepts/data/#Property_fields) and set the stroke and fill from your data:

```
chart.data = [
  // ...
  {
    "country": "UK",
    "value": 1122,
    "color": "#ff0000"
  },
  // ...
];
// ...
series.columns.template.propertyFields.fill = "color";
series.columns.template.propertyFields.stroke = "color";
```

[Demo](https://codepen.io/team/amcharts/pen/bfcd4d79305ca79f239405529fa9792d?editors=0010)

**Comment by slead** [comment]
Many thanks for the fast replies

**Comment by slead** [comment]
A related question if I may. I have disabled the labels on the category axis using `categoryAxis.renderer.labels.template.disabled = true;` and wish to label only the highlighted column.

Is this possible? It should look like this:

![Screen Shot 2020-01-24 at 9 22 25 am](https://user-images.githubusercontent.com/133596/73029154-24fa9680-3e8b-11ea-8a5e-9455ced7f1ba.png)

**Comment by xorspark** [comment]
Labels are possible by adding a LabelBullet to the series.

```
let columnLabel = series.bullets.push(new am4charts.LabelBullet());
columnLabel.label.text = "{categoryX}";
columnLabel.label.verticalCenter = "bottom";
columnLabel.label.truncate = false;
columnLabel.label.hideOversized = false;
```

An adapter on the label text can be used to show whether or not to display the label

If you're using the adapter approach from the previous response::

```
columnLabel.label.fill = "#ff0000";
columnLabel.label.adapter.add('text', function(text, target) {
  if (target.dataItem.categoryX == "UK") {
    return text;
  }
  return "";
});
```

[Demo](https://codepen.io/team/amcharts/pen/5fe4554027998080b45a2629db6b1226?editors=0010)

If you're using propertyFields, this is another approach that uses the color property in your data to determine whether to show the label or not:

```
columnLabel.label.propertyFields.fill = "color";
columnLabel.label.adapter.add('text', function(text, target) {
  if (target.dataItem.dataContext.color) {
    return text;
  }
  return "";
});
```

[Demo](https://codepen.io/team/amcharts/pen/fdbd311c0da67ef8f9444dab08f28aaa?editors=0010)
