### ISSUE TITLE
Question : Set first data point to left (DateAxis)

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#207]
Hello !

Is there a way to set the first data point to the left of the xAxe (and the first label too) ?

![image](https://user-images.githubusercontent.com/6083644/43789360-0f4dd498-9a70-11e8-8b4a-b4fe220b4806.png)

https://codepen.io/ptorrent/pen/yqROOP

Thanks for your reply !

**Comment by martynasma** [comment]
We can use adapters for that:

```
  "xAxes": [
    {
      "id": "76c8f561-2ce2-53c2-18f4-81f085f262ea",
      "type": "DateAxis",
      "stroke": "#000000",
      "strokeOpacity": 0,
      "dateFormat": {
        "day": "MMMM d, yyyy",
        "hour": "MMMM d, yyyy",
        "week": "MMMM d, yyyy",
        "month": "MMMM d, yyyy",
        "year": "MMMM d, yyyy"
      },
      "renderer": {
        "labels": {
          "adapter": {
            "location": function(location, target) {
              if ((target.x >= 0) && target.x <= 100) {
                return 0;
              }
              return location;
            }
          }
        }
      }
    }
  ],
```

This will override X axis label's `location` to 0 (start) if the label falls within the first 100 pixels of the axis.

Here's a working example:

https://codepen.io/team/amcharts/pen/9868bc94e884e9eebdd1b6642918dd17/

Do you think something like that could work for you?

**Comment by ptorrent** [comment]
Yes thanks a lot !

**Comment by martynasma** [comment]
Perfect!

I'm closing this, but please feel free to post any follow up questions you may have.
