### ISSUE TITLE
zoomToMapObject issue

### ISSUE THREAD

**Issue by Sacha-Bombard** [amcharts/amcharts4#2070]
Hello,

(I'm french sorry for my English ...). I'm coding a website which uses world map. I have followed a demo to do this thing (https://www.amcharts.com/demos/drill-down-to-countries/). I copied exactly the same code, import files etc... but when I click on a country, the zoom go to the country but there isn't country shape ...
I have tried my code with a basic html page and it's work. Therefore, maybe css rules could be the problem but which one ?

Thanks !

**Comment by martynasma** [comment]
Maybe you could post what you have so far on CodePen?

**Comment by Sacha-Bombard** [comment]
It's was a simply bug about waitforImage by Jquery ... Thank you for your answer.
