### ISSUE TITLE
How to display more than 2 polygons on the same MapPolygonSeries

### ISSUE THREAD

**Issue by graille** [amcharts/amcharts4#2071]
Hi,

I just took the example from [here](https://www.amcharts.com/docs/v4/tutorials/custom-polygons-on-map-chart/) and tried to add 2 more polygons. But it seems amCharts cannot display more than 2 polygons at a time in the same _MapPolygonSeries_:

https://codepen.io/Graille/pen/qBEvwmv

(In this example, you have 3 declared polygons, but only the two firsts are displayed, if you want to display the thrid one, you have to comment one of the two firsts).

I don't know if it's a bug or not, I noticed it when I tried the same thing in my project.

Regards

**Comment by martynasma** [comment]
The data for each polygon needs to be in a separate object:

```
shapeSeries.data = [{
  "title": "Bermuda triangle",
  "geoPolygon": [
    [
      {latitude: 25.774, longitude: -80.190},
      {latitude: 32.321, longitude: -64.757},
      {latitude: 18.466, longitude: -66.118},
      {latitude: 25.774, longitude: -80.190}
    ],
  ]
}, {
  "geoPolygon": [
    [
      {latitude: -25.774, longitude: 80.190},
      {latitude: -32.321, longitude: 64.757},
      {latitude: -18.466, longitude: 66.118},
      {latitude: -25.774, longitude: 80.190}
    ],
  ]
}, {
  "geoPolygon": [
    [
      {latitude: 25.774, longitude: 80.190},
      {latitude: 24.321, longitude: 64.757},
      {latitude: 42.466, longitude: 66.118},
      {latitude: 32.774, longitude: 80.190}
    ]
  ]
}];
```
