### ISSUE TITLE
Unable to access data from JSON data variable for amchart Map tooltiptext

### ISSUE THREAD

**Issue by dev-debug** [amcharts/amcharts4#2072]
I've JSON data (which is similar to the data of amchart drill down map) as

```
   var countries = {
        "FR": {
            "country": "France",
            "id": "FR",
            "continent_code": "EU",
            "continent": "Europe",
            "customData": "52140706.156",
            "maps": ["franceLow", "franceHigh", "franceDepartmentsLow", "franceDepartmentsHigh"]
        },
        "CA": {
            "country": "Canada",
            "id": "CA",
            "continent_code": "NA",
            "continent": "North America",
            "customData": "60584269.516",
            "maps": ["canadaLow", "canadaHigh"]
        },
        "US": {
            "country": "United States",
            "id": "US",

            "continent_code": "NA",
            "continent": "North America",
            "customData": "427901562.033",
            "maps": ["usaLow", "usaHigh", "usaTerritoriesLow", "usaTerritoriesHigh", "usaTerritories2Low", "usaTerritories2High"]
        },
        "DE": {
            "country": "Germany",
            "id": "DE",

            "continent_code": "EU",
            "continent": "Europe",
            "customData": "77179099.655",
            "maps": ["germanyLow", "germanyHigh"]
        },
        "GB": {
            "country": "United Kingdom",
            "id": "GB",

            "continent_code": "EU",
            "continent": "Europe",
            "customData": "73696011.225",
            "maps": ["ukLow", "ukHigh", "ukCountiesLow", "ukCountiesHigh"]
        },
        "AU": {
            "country": "Australia",
            "id": "AU",

            "continent_code": "OC",
            "continent": "Oceania",
            "customData": "147434203.043",
            "maps": ["australiaLow", "australiaHigh"]
        }

    };
```

I'm unable to access the data customData to show in tooltiptext of the countries in the map using the code

`    worldPolygon.tooltipText = "Total Margin for {name} :{countries.name.customData.formatNumber('#.00')}";
`

My amchart drill down map in your website is the same as this and data are almost same - I just added customData. The chart is the last chart in your website's page

[**_building-drill-down-maps: Loading maps dynamically_**](https://www.amcharts.com/docs/v4/tutorials/building-drill-down-maps/)

[**_Codepen of drill-down-maps: Loading maps dynamically_**](https://codepen.io/pen/?=true)

**Comment by martynasma** [comment]
You don't seem to be using `value` data field. You can do that.

```
worldSeries.dataFields.value = "customData";
...
worldPolygon.tooltipText = "Total Margin for {name} :{value.formatNumber('#.00')}";
```

Hope that helps.

**Comment by dev-debug** [comment]
> value
@martynasma Your answer doesn't work. My JSON data has multiple values 

`            "country": "France",
            "id": "FR",
            "continent_code": "EU",
            "continent": "Europe",
            "customData": "52140706.156",
            "maps": ["franceLow", "franceHigh", "franceDepartmentsLow", "franceDepartmentsHigh"]
`

- so which value in your code is referencing?

`worldPolygon.tooltipText = "Total Margin for {name} :{value.formatNumber('#.00')}";`

And what if I want to show multiple values in my tooltiptext of my map chart on hover like this?

[Custom tooltip in amcharts' chart where data taken from axes](https://codepen.io/team/amcharts/pen/MxaywM)

I can't use this format cuz I'm using a map which has no axes unlike chart. But I want a custom tooltip like this. The issue here is the JSON format - how do I access data for each key and represent in an format like this as below. I've keys like FR:, AU:. So how do I access data from such heirarchical JSON format(This format is required for drill down map chart) and represent it as something like this

`worldPolygon.tooltipText = "Total Margin for {name} :{countries.name.customData.formatNumber('#.00')}";

`

**Comment by dev-debug** [comment]
> You don't seem to be using `value` data field. You can do that.
> 
> ```
> worldSeries.dataFields.value = "customData";
> ...
> worldPolygon.tooltipText = "Total Margin for {name} :{value.formatNumber('#.00')}";
> ```
> 
> Hope that helps.

**Comment by dev-debug** [comment]
> You don't seem to be using `value` data field. You can do that.
> 
> ```
> worldSeries.dataFields.value = "customData";
> ...
> worldPolygon.tooltipText = "Total Margin for {name} :{value.formatNumber('#.00')}";
> ```
> 
> Hope that helps.


Hi i think I know what the problem is - I need to add

`worldSeries.mapPolygons.template.adapter.add('tooltipText', (text, target) => {`
to my map series template

But even if I used this, how do i get customData to be returned as text?
