### ISSUE TITLE
treemap level0 image  download multiple times when calling invalidateRawData as well as drill down to next level

### ISSUE THREAD

**Issue by shichenglu** [amcharts/amcharts4#2073]
Hi,

I am setting up a treemap with image background on level0 like this:
[
{"name":"A","image":"imageA","children":[{"name":"A1","count0":10,"count1":11,"count2":12}]}
{"name":"B","image":"imageB","children":[{"name":"B1","count0":10,"count1":11,"count2":12}]}
]
the reason why there are count0, count1, count2 is I need to animate the treemap by set chart.dataFields.value="count1" and call chart.invalidateRawData()
however, when I call invalidateRawData every image for level0 will be downloaded multiple times depending on how many dataset I have.
Also when I click the level0 to drill down to level1, the image will be downloaded multiple times.
I think it's a bug related to treemap datavlidation.

PS: I also check the demo https://www.amcharts.com/demos/drill-down-treemap/
same issue here, drill down to next level will download every image multiple times.

Thanks

**Comment by shichenglu** [comment]
any update on this issue?

**Comment by martynasma** [comment]
I'm afraid that's how it is. Elements, including images, may get regenerated, and not reused in some cases, including yours.

That should not be an issue, because browsers employ caching mechanism. They do not download the same image multiple times.

Hope that sounds reasonable.

**Comment by shichenglu** [comment]
my bad, checked the 'disable cache' option on Chrome inspection which causes this issue.
