### ISSUE TITLE
Reduce Distance between legend items in legend container , in order to avoid scroll bar for container in amchart4

### ISSUE THREAD

**Issue by srisharan403** [amcharts/amcharts4#2075]
hi ,

I have a requirement where a legend container contains legend items in amchart4 , i need to reduce the gap or distance between legend items , so that there will be no scroll side needed if the items can fit into the container .please look at my screen shot attached and script as well..please provide me the solution as soon as possible
![legend space](https://user-images.githubusercontent.com/59687588/73259901-c4eb5380-41ee-11ea-848d-06e5f51a05bd.JPG)
![script legend container](https://user-images.githubusercontent.com/59687588/73259999-01b74a80-41ef-11ea-8384-3a16118d4fac.JPG)

**Comment by zeroin** [comment]
The gaps between legend items can be adjusted using 
```
chart.legend.itemContainers.template.padding(3, 0, 3, 0);
chart.legend.itemContainers.template.margin(0, 5, 0, 5);
```
But I can not guarantee that this will solve your isseu. If it won't, I could try to help, but I need a codepen of your chart in order to do that.

**Comment by Polfo** [comment]
This worked for me:
```
itemContainers: {
    template: {
        paddingTop: 0,
    }
},
```

**Comment by Polfo** [comment]
This worked for me:
```
legend: {
    itemContainers: {
        template: {
            // console.log(chart.legend.itemContainers._template.properties)
            paddingTop: 0, // default 8
            paddingBottom: 0, // default 8
            marginLeft: 4, // default 10
            marginRight: 4, // default 10
        }
    },
```

**Comment by Polfo** [comment]
This worked for me:
`console.log(chart.legend.itemContainers._template.properties)`
```
legend: {
    itemContainers: {
        template: {
            paddingTop: 0, // default 8
            paddingBottom: 0, // default 8
            marginLeft: 4, // default 10
            marginRight: 4, // default 10
        }
    },
```
