### ISSUE TITLE
PieChart with a custom html tooltip does not display any data from curly brackets. 

### ISSUE THREAD

**Issue by IlliaFilatov** [amcharts/amcharts4#2077]
Trying to connect this chart to react.js app. Everything is ok, except one thing: any expression in curly brackets from html template `...` does not work. Any help would be good. 

// Here is an html code of a tooltip: 
pieSeries.tooltipHTML = `
      <div style="width: 140px; margin: 5px;">
        <div style="">
          // <img src={icon} alt="">
        </div>
        <div style="">Title: {field}</div>
        <div>{radius}</div>
        <div style="">Result: {result + "%"}</div>
      <div> 
    `;

// Here is a data: 
    chart.data = [
      {
        field: "Server & IT",
        result: 47,
        radius: 8,
        color: am4core.color("rgba(41, 133, 191, 1)"),
        icon: iconServer
      },
      {
        field: "Reisen",
        result: 28,
        radius: 7,
        color: am4core.color("rgba(55, 148, 207, 1)"),
        icon: iconServer
      }
    ];

**Comment by martynasma** [comment]
This is because you are setting `tooltipHTML` directly on series. Series itself does not have any data items and therefore cannot refer to dataContext.

You need to set it on slices:

```
pieSeries.slices.template.tooltipHTML = "......";
```

**Comment by IlliaFilatov** [comment]
Great. Thanks, now it works properly!
