### ISSUE TITLE
getting error: 'am4themes_animated' is not defined

### ISSUE THREAD

**Issue by SheharyarSMAdil** [amcharts/amcharts4#2078]
I just pasted the demo code and installed `npm install @amcharts/amcharts4`
`npm install @amcharts/amcharts4-geodata` in react.js
 I am getting error : ###`'am4themes_animated' is not defined` <br/> 
if i comment the line `am4core.useTheme(am4themes_animated);`  then i am getting error: `Module not found: Can't resolve '@amcharts/amcharts4/charts' `.
please help

**Comment by martynasma** [comment]
Please follow this guide:
https://www.amcharts.com/docs/v4/getting-started/integrations/using-react/

All modules, including animated theme needs to be imported before you can use it.

**Comment by SheharyarSMAdil** [comment]
thanks, @martynasma.
