### ISSUE TITLE
"Rangechanged" event for scrollbar isn't triggered on zoom out

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#2080]
I use the `"rangechanged"` event of a scrollbar in a visualization and I noticed that the event isn't triggered when clicking on the "zoom out" button of the chart. I don't know if it is supposed to stay this way but it could be nice to bind the two events together :)

https://codepen.io/segolene-albouy/pen/xxbNpay?editors=1010 : here is a codepen

![scrollbar-event](https://user-images.githubusercontent.com/44207487/73370985-5b824800-42b5-11ea-9284-4dcbb12afb15.png)

Thanks a lot for all your work!

**Comment by zeroin** [comment]
Thank you for noticing. Although it might seem an easy fix, but I am not yet sure I will do it, as it might cause some extra redraws of the chart which is not good for CPU. Meanwhile I recommend using `startendchanged` event of your x axis - it will be fired whenever range changes, no matter what caused it.

**Comment by Segolene-Albouy** [comment]
Thank you, I'll use that then!

**Comment by prasanna-sasne** [comment]
I think, 'rangechanged' only gets triggered if you are handling scrollbarX. but if you want some functionality on the zoom out button then you must use `chart.zoomOutButton.events.on('hit', ()=> {}, this)`. 
Also, 'startendchanged' will be triggered multiple times, the issue stems from the fact that when loading a substantial amount of data into the line series chart, it requires time to adjust the ranges properly. During this adjustment process, the chart undergoes multiple changes in scale, leading to the occurrence of numerous zoom events. As a result, this situation leads to multiple calls being made. And if you want to do some API calls after zooming in then performance will be reduced. 
I will suggest using the event on the cursor rather on 'timeaxis'. 

`chart.cursor.events.on('zoomended', () => { ... do your work  })`  this will trigger for only once.
