### ISSUE TITLE
Popups and Modals header elements visible when defaultStyles is set to false

### ISSUE THREAD

**Issue by eTingleff** [amcharts/amcharts4#2083]
Popups configured like so:

`popup.defaultStyles = false;`
`popup.draggable = false;`
`popup.closable = false;`

 still display the popup's empty header element. Not sure if it's a bug but this did not used to be the case.
I am able to achieve a plain/transparent popup like I was able to with an earlier release with the following:

`popup.elements['header'].style.display = 'none';`

[codepen example](https://codepen.io/eTingz/pen/WNbBaRX)

**Comment by zeroin** [comment]
We added this recently in order to have some area which is draggable (having all the popup draggable caused problems). So to hide it, add this to your css: 

```
.ampopup-header{
  background-color: transparent;
}
```

**Comment by zeroin** [comment]
Or, if you want to hide it completely, add:

```
.ampopup-header{
  display: none;
}
```

**Comment by eTingleff** [comment]
Okay cool, I didn't know if it was intentional or not. Thank you for the CSS class style that achieves what I'm looking for.
