### ISSUE TITLE
how to remove the spacing between legend

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#2084]
![image](https://user-images.githubusercontent.com/54665162/73427967-f6366180-435d-11ea-9309-16a7a1237c2d.png)

**Comment by zeroin** [comment]
Which spacing - horizontal or vertical?
valueLabels of legend occupie 50px, even if you don't use them. So you can disable them by setting:

`legend.valueLabels.template.disabled = true`

this should save horizontal space.
