### ISSUE TITLE
Treemap chart throwing error with 0 valued data.

### ISSUE THREAD

**Issue by phillipmiles** [amcharts/amcharts4#2085]
I've come across a bug with the Treemap chart when some of that data has a value of zero. Instead of rendering the chart the message `Cannot set property '__disabled' of undefined`  appears. You should be able to see the issue in this codepen which is just a copy of a pen used in amcharts docs but with some values set to 0.

https://codepen.io/phillipmiles/pen/mdyZMEQ

Weirdly it's a little inconsistent. If you edit the above codepen so that only two data items have a value of 0 it will render fine. But if you make it so that three or one data items have the value of 0 it will break again.

The expected behaviour should be whats described in the docs regarding zero values... https://www.amcharts.com/docs/v4/chart-types/treemap/#Zero_negative_values ... in that any square with zero values should just be hidden.

**Comment by zeroin** [comment]
This issue was fixed in v 4.8.6 - thank you for helping to find it!
