### ISSUE TITLE
Is there a way to set a column to active on dateRangeChanged event?

### ISSUE THREAD

**Issue by franny2491** [amcharts/amcharts4#2087]
Hi, 

I am looking to change the active state on a column on the dateRangeChanged event. 
There is a little spot of code below, where I have put '// This is the line I need help with ' is where I am missing the magical line to check to see if the dataItem has been scrolled to a position in the chart. 
I am interested in this so that I can change a colour of a column to an active state if it scrolls over a certain part of the chart, and then back to the default colour if it's outside that range. 

I have tried the hit event, but that actually requires the column to be clicked on, I am looking for a scroll event. 

Thanks

dateAxis.events.on("datarangechanged", function(event) {
                console.log("something happened ", event);
                series.columns.each(function(column) {
                  if (column.dataItem.?   !== event.target) { // This is the line I need help with 
                    column.setState("default");
                    column.isActive = false;
                  }
                else {
                    column.isActive = true;
                }
        })
});

**Comment by zeroin** [comment]
Here is a demo of a concept:
https://codepen.io/team/amcharts/pen/gObNjOR

Basically you need to access `dateX` of the data item and compare it to the `minZoomed` / `maxZoomed` values of the Date axis

**Comment by franny2491** [comment]
Hi @zeroin 

I have put this in, but it doesn't change the colour of the bars when I scroll left and right?

Thanks,

Francis

**Comment by zeroin** [comment]
I am afraid I need to see the working chart in order to tell something.
