### ISSUE TITLE
Labels not positioned properly for floating bars

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#209]
Hello,

I am trying to render a floating bar chart where I want to position labels for each bar according to the bar final or close value.
Though I am able to achieve that, I cannot position labels so that they don't overlap on bars.
If I set verticalCenter as bottom or top, it will be efficient only to decreasing(valueY > openValueY)  bars and increasing(valueY < openValueY) bars respectively.

But I am looking for a solution which will satisfy both the cases. Is it possible?

Example:
https://codepen.io/anon/pen/ajRgyz?editors=0010

**Comment by martynasma** [comment]
Yes, this sounds like a job for an Adapter:

```
function(center, target) {
  var values = target.dataItem.values;
  return values.valueY.value > values.openValueY.value ? "bottom" : "top";
});
```

Example:
https://codepen.io/team/amcharts/pen/a6b4f7f893113b4c2a1cec9b01d4e408/

About adapters:
https://www.amcharts.com/docs/v4/concepts/adapters/

**Comment by martynasma** [comment]
Posted a related article:
https://www.amcharts.com/docs/v4/tutorials/using-adapters-for-value-sensitive-bullet-adjustments/

You might find it useful.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
