### ISSUE TITLE
Is there any way to put conditional statement in tooltipHTML?

### ISSUE THREAD

**Issue by dharam0034** [amcharts/amcharts4#2091]
Hi, 

I want to display different text for series-tooltip depending on the valueY. 
I tried but couldn't make it working. 

Thanks.

**Comment by dharam0034** [comment]
To be more clear, is there any way to make condition in html of  toolTipHTML?

**Comment by martynasma** [comment]
You should use "adapters" for that:
https://www.amcharts.com/docs/v4/concepts/adapters/

**Comment by dharam0034** [comment]
Thanks

**Comment by setiawans** [comment]
@martynasma i have quick question about it.
what can i do when i need to filter the value. for example we should showing "A+" if `valueY > 90` and so on..
i know from the example only using like this `{valueY}`
thanks

**Comment by setiawans** [comment]
Sorry, i found this solution here https://github.com/amcharts/amcharts4/issues/67
thanks
