### ISSUE TITLE
'legendSettings' - 'itemValueText' to check for empty or undefined value

### ISSUE THREAD

**Issue by rai-gaurav** [amcharts/amcharts4#2092]
I asked this question on stackoverflow -https://stackoverflow.com/questions/59895938/amcharts4-legendsettings-itemvaluetext-to-check-for-empty-or-undefined-valu
Since I haven't got any response hence asking here.

Q -Is there some way where we can check 'itemValueText' or {valueY} to check whether it is 'undefined' and modify display value based on that?

**Comment by xorspark** [comment]
I replied to your quesiton on SO, but here it is again for your convenience.

You can create a [`textOutput`](https://www.amcharts.com/docs/v4/reference/label/#textOutput_adapter) adapter on the legend's [`valueLabels`](https://www.amcharts.com/docs/v4/reference/legend/#valueLabels_property) template to check the final text output based on your template string and adjust accordingly.

```
chart.legend.valueLabels.template.adapter.add("textOutput", function(text, target) {
  if (text === '(Avg: [bold]%[/])') {
    return 'N/A';
  }
  else if (text === '[bold]%[/]') {
    return '';
  }
  return text;
});

```

[Demo](https://codepen.io/team/amcharts/pen/3d4d35c659b91733c90fa82805fc5433?editors=0010)

**Comment by sudo-batman** [comment]
Thanks you. This is exactly what I was looking for.
