### ISSUE TITLE
cannot read property 'slice' of undefined error after clearing series and adding a new one.

### ISSUE THREAD

**Issue by o0JoeCool0o** [amcharts/amcharts4#2093]
So on my pie chart I keep the same chart but just clear the series and map a new one multiple times.
This used to work fine but all of a sudden getting the error cannot read property 'slice' of undefined.

I believe a bug was maybe introduced somewhere. I found out if I delete the entire chart now instead of just the series, then exact same data is mapped fine.

as per docs I am using currentChart.series.removeIndex(0).dispose(); to remove I tried without .dispose() as well same error

I then use 
currentChart.data = chartData;
    var series = new am4charts.PieSeries();
set the related values and add the series
currentChart.series.push(series);

This always works now on first series added but if I remove the series and try the exact same again I get the slice error. Was working fine a few weeks ago.

**Comment by zeroin** [comment]
Tried to reproduce this with no luck, Here is the chart with all the elements you mentioned (series is removed after 3 seconds):

https://codepen.io/team/amcharts/pen/MWwgjJY

If you could edit the pen to reproduce the exact situation when this happens, it would help a lot.

**Comment by ivasanpag** [comment]
Same issue here. I have the problem when the data retrieved from the server contains 0 values.
