### ISSUE TITLE
No Events in ColumnSeries

### ISSUE THREAD

**Issue by rasca** [amcharts/amcharts4#2094]
In [Events Listeners](https://www.amcharts.com/docs/v4/concepts/event-listeners/#Available_events) it links to the [Column Series Event section](https://www.amcharts.com/docs/v4/reference/columnseries/#Events) which states it doesn't have any events when I gather it should at least contain `hit`.

When trying:
```js
series.columns.template.events.onAll(function(ev) {
  console.log("something happened ", ev);
}, this);
```
I don't get any click events either.

**Comment by martynasma** [comment]
Looks like something broke in our classref. Will let you know when it's fixed.

Thanks for the heads up!

**Comment by martynasma** [comment]
Class reference is now showing events. Thanks again for bringing it to our attention!
