### ISSUE TITLE
dateAxis and scrollbar

### ISSUE THREAD

**Issue by PepiBobanov** [amcharts/amcharts4#2095]
Hello, i want to customize scrollbar to display every year only.
Is there a way to do something like this:

dateAxis.gridIntervals.setAll([{timeUnit: "year", count: 1}]);

But to be applied only to scrollbar, not to whole chart

**Comment by xorspark** [comment]
You can access the scrollbar's chart direclty through its [`scrollbarChart`](https://www.amcharts.com/docs/v4/reference/xychartscrollbar/#scrollbarChart_property) property and make the desired changes on that chart instance.

Assuming this is on the X axis:

```
chart.scrollbarX.scrollbarChart.xAxes.getIndex(0).gridIntervals.setAll([{timeUnit: "year", count: 1}]);
```

More customization info [here](https://www.amcharts.com/docs/v4/tutorials/customizing-chart-scrollbar/).

**Comment by PepiBobanov** [comment]
works, thanks. ^_^
