### ISSUE TITLE
Set date format for exported date in Excel files 

### ISSUE THREAD

**Issue by ZeLourenco** [amcharts/amcharts4#2097]
This is my code, where i start the export functionality and define which format i want for the exported dates.

chart.exporting.menu = new am4core.ExportMenu();
chart.exporting.dateFormat = "yyyy-MM-dd HH:mm:ss.SSS Z";

When exported date to xlsx files, the exported date aren't correctly represented in the excel files.

I saw this issue (Set date/time format for export in Excel #742), but i don't know how to solve.

**Comment by martynasma** [comment]
Try disabling formatting of dates according to user's locale for XLSX format:

```
chart.exporting.getFormatOptions("xlsx").useLocale = false;
```
