### ISSUE TITLE
Tooltips not work correctly

### ISSUE THREAD

**Issue by aikodeio** [amcharts/amcharts4#2098]
Hi! Thank you for reading.

I have a problem. I need to create the following graphic:

https://codepen.io/aikodeio/pen/PoqYMQd?editors=0010

I am using LineSeries but I cannot disconnect them according to their category. I read the documentation, I used:

`serie.connect = false`

but still the connections are mixed.

In addition, the "Tooltip" also does not work correctly since it does not show me the information based on the data where I position the cursor.

I need to achieve this:
![chart](https://user-images.githubusercontent.com/47112604/73857934-676e8c80-4816-11ea-97f7-aa7e8cd5f57a.jpg)

**Comment by aikodeio** [comment]
**UPGRADE**

I managed to keep the points from connecting, with `serie.connect = false`

 but the "Tooltip" still fails.

https://codepen.io/aikodeio/pen/PoqYMQd?editors=0010

**Comment by martynasma** [comment]
I suggest putting `tooltipText` directly on bullet, this way you'll get the tooltip on a bullet that is being hovered.

```
bullet.tooltipText = '{valueY} people in {choice}';
```

**Comment by aikodeio** [comment]
wow, ok, this worked, thanks!

but it has a strange interaction, especially when I navigate, the tooltip usually returns to the highest value:

**Comment by martynasma** [comment]
You might want to add `cursorTooltipEnabled = false` on series as well:

```
serie.cursorTooltipEnabled = false;
```

**Comment by aikodeio** [comment]
This is great, I'm getting the desired graphic. Thanks for the help

I just need to solve another configuration with tooltips:

When I place the mouse cursor over the number, the tooltip is displayed, but if I place it over the bullet but not in the number, the tooltip disappears.

I tried to use:
```
bullet.circle.paddingLeft = 14
bullet.circle.paddingRight = 14
```
and
```
bullet.label.paddingLeft = 14
bullet.label.paddingRight = 14
```
but it does not work



**updated code**:
https://codepen.io/aikodeio/pen/PoqYMQd?editors=0010

**Comment by aikodeio** [comment]
@martynasma any solution for this? sorry

**Comment by zeroin** [comment]
You should move this line:

`bullet.tooltipText = '{valueY} people in {choice}';`

above the line where you create label bullet, or (this would be more correct) use a different var name for the label bullet. As now you've simple set the tooltipText for the label, not the bullet.

**Comment by aikodeio** [comment]
@zeroin I can't believe the solution was as simple as that. I thank you very much! I got the graphic I needed :)
