### ISSUE TITLE
enhancement - Plot negative values in ValueAxis when logarithmic = true

### ISSUE THREAD

**Issue by lucasgdutra** [amcharts/amcharts4#2100]
### enhancement - Plot negative values in ValueAxis when logarithmic = true

Is not possible to compute `log10(x)` when `x <= 0`, but negatives values can be calculated with `Math.log10(Math.abs(x))` and then inverted multipling by` -1`

To maintaining continuity when closer to 0` log10(x)` can be approximated by `log10(1 + Math.abs(x/1))` 

resulting in function below presented by J. Beau W. Webber
`y = Math.sign(x) * Math.log10(1 + Math.abs((x/1)))`

The Aproximation is great to values > |10|

reference: 
https://www.mathworks.com/matlabcentral/fileexchange/57902-symlog
https://pdfs.semanticscholar.org/70d5/3d9f448e6f2c10bd87a4a058be64f5af7dbc.pdf

**Comment by zeroin** [comment]
Thank you for suggestion, we will consider it.

**Comment by martynasma** [comment]
Hi again. Sorry for the wait. We have decided not to implement this feature at this point. Sorry.
