### ISSUE TITLE
html in legend similar to tooTop HTML? 

### ISSUE THREAD

**Issue by dharam0034** [amcharts/amcharts4#2101]
Hi, 

Is there any way to display the html in legend similar to toopTip html. 
I mean it can be like having HTML tooltip in the legend outside the chart container. 

Thanks !

**Comment by martynasma** [comment]
Something like this?

https://www.amcharts.com/docs/v4/tutorials/custom-external-legend/

**Comment by dharam0034** [comment]
Thanks, that is a good link but it doesn't solve my problem. 
I am working with multiple line series. 
I have created a sub-container in topAxesContainer (containing labels for each series) and the position of sub-container changes with the cursor. So, it is like a multi-series tooltip outside the chart's main container. 
something like this example but outside chart: https://www.amcharts.com/docs/v4/tutorials/custom-static-multi-value-tooltip/

The plan is to display the calculated values for each series but I want to use the html instead of text in each label. I am assigning the the current dataItem from series to label.dataItem and then try to update the calculated values in labels at 'tooltipshownat' or cursorpositionchanged by using { } in label.html. But, it's not picking the real values though the text version is working fine.

**Comment by martynasma** [comment]
Do you have your chart online?

**Comment by dharam0034** [comment]
I will try to make a quick demo in some time.
