### ISSUE TITLE
Wrong zoom applied for Value axis after updating data when using groupFields: {valueY: "sum" } for Date axis

### ISSUE THREAD

**Issue by Avecom** [amcharts/amcharts4#2102]
Code Pen: https://codepen.io/paulsans/pen/VwLwmWE

Issue: after pressing the "Update chart data" button, the chart columns become clipped due to wrong zoom for Value axis.

Probably issue's cause: the zooming logic doesn't take in account a summation which is required by the following command:
series.groupFields.valueY = "sum"

Removing that line makes the chart working correctly (but not summarizing values).

![image](https://user-images.githubusercontent.com/39749088/73946388-6fb6ec80-4928-11ea-8be0-fe147e4e14d7.png)

**Comment by zeroin** [comment]
Should work fine in v 4.8.9

**Comment by Avecom** [comment]
Great, thanks!
