### ISSUE TITLE
Is it possible to put as fileprefix in exporting charts a value from database?

### ISSUE THREAD

**Issue by romina-code** [amcharts/amcharts4#2103]
Hi,
I want to use a value from my database as fileprefix in exporting and I tried 

```
chart.exporting.filePrefix = <?php echo $value['addresses'].','.$value['accountno'];?>;
```

but its not working. Can you please tell me if its possible and how can I do it?
Thank you in advance!

**Comment by martynasma** [comment]
You probably need to enclose your prefix into quotes, as well as escape the JS string. Using PHP function `json_encode()` is probably a good way to do both:

```
chart.exporting.filePrefix = <?php echo json_encode( $value['addresses'].','.$value['accountno'] );?>;
```

**Comment by romina-code** [comment]
You are so right, thank you for your help :) !
