### ISSUE TITLE
Hide Rows in Gantt Chart

### ISSUE THREAD

**Issue by ChopperDave** [amcharts/amcharts4#2105]
Hi,

Is it possible to use a legend to hide rows in a gantt chart based on a value in the series?

Here's the code I'm working with:
https://codepen.io/ChopperDave/pen/gOpOeLP

I want to be able to click on one of the groups in the legend and hide all the people associated with that group. If there is a better way to do this I'm down for that too.

Thanks

**Comment by martynasma** [comment]
Probably easiest way is to iterate through series' columns when item in legend is toggled, then hide()/show() ones that match clicked item:

```
chart.legend.itemContainers.template.events.on("toggled", function(ev) {
  series1.columns.each(function(column) {
    if (column.fill.hex == ev.target.dataItem.dataContext.fill.hex) {
      if (ev.target.isActive) {
        column.hide(0);
      }
      else {
        column.show(0);
      }
    }
  })
});
```

Here's a working version of your chart:
https://codepen.io/team/amcharts/pen/oNXgZyB
