### ISSUE TITLE
Change Label Text to Input

### ISSUE THREAD

**Issue by PiyuGandhi** [amcharts/amcharts4#2106]
Hi, I wanted to know how can I make labels editable directly on the website.
I have a local state for default label, but I also want it to be editable.
I understand that it only takes the "text" property as a string so I cannot make it an Input property.

I'm using React.js

**Comment by martynasma** [comment]
Technically, you could use `html` (instead of `text`) property and supply any HTML, including form fields into it. How to handle input to it would be up to you though :)

**Comment by PiyuGandhi** [comment]
Hey @martynasma , Thank you :)
