### ISSUE TITLE
Incorrect date display by week

### ISSUE THREAD

**Issue by jungti1234** [amcharts/amcharts4#2107]
![1](https://user-images.githubusercontent.com/17401597/74000975-49876000-49ad-11ea-9af3-c5b72da47d17.png)

![2](https://user-images.githubusercontent.com/17401597/74000986-4ee4aa80-49ad-11ea-8a0a-a46ba9418432.png)

I specified all date formats as 'M W' (exclude Korean).

In the first image, when the year changes, the value for 'W (Week of Month)' changes to 'w (Week of the Year)'.

In the second image, the tooltip values ​​are different between date axis and candle stick series.
(first image also. Dec 6W ^^;)

Is there any solutions?

and could you check P.R. for languages update please?

**Comment by zeroin** [comment]
Did you set formats on both `dateAxis.dateFormats` & `dateAxis.periodChangeDateFormats`

**Comment by jungti1234** [comment]
@zeroin yes. I also set 'dateAxis.tooltipDateFormat'.

**Comment by zeroin** [comment]
In that case I need to see your chart live in order to help. Could you produce a codepen?
