### ISSUE TITLE
Ticks in OHLC series are not visible when there are many series

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts4#2108]
Code sample:
https://codepen.io/dez1729/pen/ExjxrOQ?editors=0010

It seems that the open/close ticks are getting smaller with each additional series added until they are not visible anymore.

In addition, is there a way to style the ticks to make them longer/thicker?

**Comment by dez1729** [comment]
This might be a scaling issue. With more series being added each series scales lower, but it is also scaling the horizontal open/close ticks as well.

**Comment by zeroin** [comment]
It's quite simple - when you add a lot of series, the cell space is divided for each of them. Try setting:

`series[i].columns.template.width = am4core.percent(200)` and you will start seeing them, but the ticks might start overlap.

**Comment by dez1729** [comment]
Thanks. This will work but probably should be documented somewhere.
