### ISSUE TITLE
Bullet position

### ISSUE THREAD

**Issue by AnastasiiaTsvetkova** [amcharts/amcharts4#2111]
Hi!

Can you help me?
My bullets go beyond the graph. 
I tried to use chart.maskBullets = true. This expression trims the bottom points on the chart. 
How can I fix this problem?
Thanks
![image](https://user-images.githubusercontent.com/55182060/74097154-73599780-4b11-11ea-88a9-13d6a68cd99e.png)

**Comment by martynasma** [comment]
Maybe you can set `min = -5` on your value axis, so there's extra space in plot area, and you don't have to disable masking of bullets.

Does that make sense?

**Comment by AnastasiiaTsvetkova** [comment]
I need that graph should start at 0. That why I can't use min = -5.

**Comment by zeroin** [comment]
It is possible to add adapter for dx which would check x position and show/hide bullets if they are out of plot area. The downside is that the bullet will appear/disappear at once, but it should be ok if they are small. Here is a demo: https://codepen.io/team/amcharts/pen/jOPPbJG

**Comment by AnastasiiaTsvetkova** [comment]
Thanks! I will try it!
