### ISSUE TITLE
Force Directed Tree without physics

### ISSUE THREAD

**Issue by simonstumpf** [amcharts/amcharts4#2114]
I really love your force directed tree, however I find that the bubbles are bouncing to much. Will there be a option to disable this?

**Comment by zeroin** [comment]
You can solve the bounciness by adjusting strengths. There are 3 strengths you can adjust:
```
networkSeries.centerStrength = 0;
networkSeries.manyBodyStrength = 0;
networkSeries.linkWithStrength = 0;
```
(try both positive and negative values)

Hovewer, this means that the nodes won't be arranged nicely, as it's the force which does that. SO you might need to make them fixed and set x and y positions manually.

Another approach would be to make only the dragged nodes fixed:
https://codepen.io/team/amcharts/pen/VwLYqPa

**Comment by simonstumpf** [comment]
So I played a little bit with all the values that are given at your docs. 
Here is my example on codeopen:
https://codepen.io/simonstumpf/pen/oNXNNXr

But if you expand one zone the bubbles are jumping on the side of the monitor. This effect can sometimes be really annoying. Is there a way to solve this?

**Comment by zeroin** [comment]
Well, `centerStrength` is the one what tries to keep the items within the chart area. So I guess having it 0 is not a good idea then.

**Comment by zeroin** [comment]
We added `velocityDecay` property to ForceDirectedSeries, which works similar to friction. So you can animate this property to 1 after the chart is inited for the nodes to slow down and then become fixed. Here is a demo: https://codepen.io/team/amcharts/pen/eYNvRjj

**Comment by simonstumpf** [comment]
> We added `velocityDecay` property to ForceDirectedSeries, which works similar to friction. So you can animate this property to 1 after the chart is inited for the nodes to slow down and then become fixed. Here is a demo: https://codepen.io/team/amcharts/pen/eYNvRjj

This feature is really awesome! Thank you
