### ISSUE TITLE
Bad performance when using multiple series

### ISSUE THREAD

**Issue by XxSven** [amcharts/amcharts4#2115]
I have performance issues when trying to display ~30 3D column series on a single chart.
I made two codepens for the comparison with v3 and v4: 
amCharts v3
https://codepen.io/XxSven/pen/oNXXjpV

amCharts v4
https://codepen.io/XxSven/pen/zYGGvem

Am I missing something ?
Thanks for the support

**Comment by lticadler** [comment]
Performance - interesting topic.

Funny addition i found out:
if you add the following line in the for loop
series.showOnInit = true;
the chart building seams faster than before (also not as fast as v3).

**Comment by DevilDipan** [comment]
Yeah it is much faster

**Comment by DevilDipan** [comment]
You can also scroll to the future. Like if you scroll right it goes 2032 which is not it the data also it can go much further.

**Comment by XxSven** [comment]
showOnInit = true doesn't show the drawing progress, so you are waiting with a blank canvas, it's not quite faster I think

**Comment by zeroin** [comment]
I am afraid with this setup v3 is indeed a lot faster. V4 has a lot extra elements and things to handle and is not good for setups where a lot of elements are involved.
