### ISSUE TITLE
Cursor formatting for date and time

### ISSUE THREAD

**Issue by yendai-vo** [amcharts/amcharts4#2116]
Hi there,
I am trying to format the x-axis cursor. I just want the time to show up in HH:mm

![image](https://user-images.githubusercontent.com/37639491/74172736-5a76e200-4bf6-11ea-9a34-c6da7e8568d4.png)

There's an adapter method that can be used for custom functions, but it can't be used with dateFormatter. Do you have any other suggestions?

**Comment by martynasma** [comment]
You can use `axis.tooltipDateFormat` for it:

https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/#Tooltip_value_format

**Comment by yendai-vo** [comment]
Thank you! I was able to use the adapter method with tooltip to get back the right formatting with time zone.
