### ISSUE TITLE
amcharts logo could be easily removed by doing minor editions

### ISSUE THREAD

**Issue by DevilDipan** [amcharts/amcharts4#2118]
I am not giving instructions how to do so because I don't want people doing it and getting a license for free without recognizing the developer. But I have a preview image to prove so...
![Capture](https://user-images.githubusercontent.com/43346471/74211842-aa69ad80-4cb7-11ea-9ad0-701436db6cfd.PNG)

**Comment by martynasma** [comment]
Well, users who value their credibility, would never knowingly circumvent the only requirement for free use. Would they? :)

I'm gonna go and close this, since this is not an "issue" or a question. Cheers!

**Comment by DevilDipan** [comment]
I don't think people would not try to circumvent it

**Comment by DevilDipan** [comment]
I have seen many quora and other posts where they have clearly asked how they could circumvent this
