### ISSUE TITLE
Chart with gaps at special possitions...?

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#2119]
I'm about to update our products from amcharts 3 to 4.

I have to display multiple series of measurements in one chart. The data points are arbitrarily and not equidistant and also for the different series not at the same date/timestamp.

With version 3 there was a **gapField** for line charts. How to get the same functionality again with version 4?

I read issue #636 and of course the tutorial https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Gaps_over_missing_data_points with autoGapCount - it is powerful - but in my opinion not enough.

From #636
> We might implement gaps without empty data points in the future. Just not sure when that is going to happen.

Is there a plan when to implement such a feature?

Simple Pen for the problem:
https://codepen.io/chrisadler/pen/WNvvyvY

Comments from the pen for documentation in this issue:

> /* dataprovider has gap field for each series (like it worked in amchart v3).
> How to create a gap ONLY at that positions...?
> */
> 
> /* If series connect=true no gaps possible so far. */
> 
> /* If connect=false autoGapCount isn't successful, because
> 1) not the greatest distance between two datapoints is the gap
> 2) other series also destroying the "connection" - it would be necessary to invent new data in a series of measurements (which is not correct) */

**Comment by martynasma** [comment]
There's currently no `gapField` equivalent in V4. At this point we do not plan on implementing one.

How about just inserting an empty data point in the place where you want the gap to occur?

**Comment by lticadler** [comment]
If it is possible to add an empty data point even though series connect = true it would be a solution.

But how to?
If the value is null or undefined it is ignored.
"NaN" is mapped to 0.

 {
  "date": 1581399790000,
  "value": 90
}, {
  "date": 1581399791000,
  "value":  "What value should be set here in order to get a gap",
}, {
  "date": 1581399795000,
  "value": 125
}

**Comment by martynasma** [comment]
No, you would still need to use `connect = false`. You might need to set `autoGapCount` to some really big number so that it does not do autogaps, just the ones for empty data items.

You don't need to add any value at all to get a gap:

```
{
"date": 1581399790000,
"value": 90
}, {
"date": 1581399791000
}, {
"date": 1581399795000,
"value": 125
}
```

**Comment by lticadler** [comment]
Yes, thought of this too. But this is only a possibility for a single series.
I have a unknown number of series with every data point at an other date/timestamp.
(As could be seen in my pen https://codepen.io/chrisadler/pen/WNvvyvY)
So with connect = false every data point of series 1 is de facto a gap for series 2 (and series 3 and ...)
This would mean i have to invent data points for all other series where i don't want a gap. This would be impossible ( - even more if the series have tension).

**Comment by martynasma** [comment]
No need to invent datapoints, just set `autoGapCount` to a real big number :)

Also, did you know that you can set `data` directly on each series (as opposed to central `data` set on chart)? That might make it way easier to create isolated "gapped" data sets for each series individually.

**Comment by lticadler** [comment]
> Also, did you know that you can set `data` directly on each series (as opposed to central `data` set on chart)? That might make it way easier to create isolated "gapped" data sets for each series individually.

Didn't know that. Sounds like a solution :) Updated the pen and it works.

**Comment by lticadler** [comment]
Thanks again - now the chart works in my productive environment as expected.

While working with series.data I have noticed that scrollbarX is not working as expected. For this i created issue #2136.
