### ISSUE TITLE
Display sum on top of task : missing labels

### ISSUE THREAD

**Issue by brAvernet** [amcharts/amcharts4#212]
Hello,

Thanks for v4, great work !
I tried to display the "BulletLabels" on top of each category of the stacked chart below (sum of both series), and some of these labels vanish when the gap between values is too important.

https://codepen.io/anon/pen/WKYqNE

Is there some option that is missing here ?
Thanks

**Comment by martynasma** [comment]
Thanks!

The reason why they vanish is that the chart looks at the column section they are added to, sees that it is smaller than the label and hides the label automatically.

To disable this feature (which clearly misfires in this situation) add this line:

```
bullet.label.hideOversized = false;
```

**Comment by brAvernet** [comment]
Ok thanks a lot ! this works perfectly. It also solved the case when the sum === 0 ->the "0€" label is shown with this option

![example](https://user-images.githubusercontent.com/10059350/43900994-9c636290-9be6-11e8-9824-b2715e2beae3.PNG)

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
