### ISSUE TITLE
Custom tooltip text Safari

### ISSUE THREAD

**Issue by spotjobs** [amcharts/amcharts4#2120]
![Screen Shot 2020-02-11 at 3 06 22 PM](https://user-images.githubusercontent.com/57628942/74239878-70ad9c80-4ce1-11ea-8d44-13c314b577ef.png)
In a custom tooltip text stays outside of a tooltip box. It works this way on IOS every browser and desktop Safari. 
![Screen Shot 2020-02-11 at 3 26 00 PM](https://user-images.githubusercontent.com/57628942/74240524-d6e6ef00-4ce2-11ea-9caa-3542eb797f3f.png)
Sometimes there is only half of an icon.
Please, help me to understand, what should I do with it.

**Comment by martynasma** [comment]
Can you share your chart as a CodePen?

**Comment by spotjobs** [comment]
> Can you share your chart as a CodePen?

https://codepen.io/illiafilatov/pen/WNvramL

Yeah, sure. Code is a bit different, but the bug is also here.

**Comment by martynasma** [comment]
It looks like Safari gets thrown off by `translateY(-35%);` in a `foreignObject`.

I suggest centering your tooltip content using some other CSS style. Perhaps with `marginTop`?
