### ISSUE TITLE
Setting an image for zoomOutButton via JSON config.

### ISSUE THREAD

**Issue by c-goetz** [amcharts/amcharts4#2121]
Hi,

currently I'm trying to set an image with an inlined svg for the zoomOutButton using JSON config.
After reading https://www.amcharts.com/docs/v4/tutorials/configuring-the-zoom-out-button/ I created this codepen to try it out: https://codepen.io/c-goetz/pen/ZEGGNBz

Sadly there's no image in the zoomOutButton. Removing the comments in line 88 and thus using the JS api works like a charm.

Are there any things I'm missing from the config?

Thanks for the help,
Carlo

**Comment by martynasma** [comment]
The thing with JSON config is that when you are using arrays to as a property, it will check if there is already an element with the same index. So in this case `Image` with an index `0` in your config matches existing index `0` of the element that already exists in zoomout button.

In this case you can use `forceCreate: true` keyword, to, well, force the creation of a new child.

```
chart.zoomOutButton = {
  icon: {disabled: true},
  children: [
    {type: "Image",
     forceCreate: true,
    href: "data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIwIDAgMjQgMjQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS1taXRlcmxpbWl0PSIyIj48cGF0aCBmaWxsPSJub25lIiBkPSJNMCAwaDI0djI0SDB6Ij48L3BhdGg+PHBhdGggZD0iTTE0LjU1MiAxNS45NjJBNy40NjcgNy40NjcgMCAwMTEwIDE3LjUwMiA3LjUwNiA3LjUwNiAwIDAxMi40OTggMTAgNy41MDYgNy41MDYgMCAwMTEwIDIuNDk4IDcuNTA2IDcuNTA2IDAgMDExNy41MDIgMTBhNy40NjcgNy40NjcgMCAwMS0xLjU0IDQuNTUybDQuNTcgNC41N2MuMzg4LjM4NS4zOTMgMS4wMi4wMSAxLjQxYTEuMDAxIDEuMDAxIDAgMDEtMS40MiAwbC00LjU3LTQuNTd6TTEwIDQuNWMzLjAzNiAwIDUuNSAyLjQ2NCA1LjUgNS41cy0yLjQ2NCA1LjUtNS41IDUuNUE1LjUwMiA1LjUwMiAwIDAxNC41IDEwYzAtMy4wMzYgMi40NjQtNS41IDUuNS01LjV6Ij48L3BhdGg+PHBhdGggZD0iTTcgOC45OWg2LjAyMXYySDd6Ij48L3BhdGg+PC9zdmc+"},
    {type:"Label", text: "hi"}
  ]
}
```

I can see that our tutorial has missed that as well, which is now fixed. Sorry for the confusion.

**Comment by c-goetz** [comment]
That worked flawlessly. Thanks you for your help. Much appreciated.
