### ISSUE TITLE
Bug Report: Not all adapter functions are running when data changes

### ISSUE THREAD

**Issue by tehpsalmist** [amcharts/amcharts4#2122]
I have a pie chart with these two custom adapters for the labels:

```
pieSeries.labels.template.adapter.add('radius', function(radius, target) {
  if (target.dataItem && (target.dataItem.values.value.percent < 5)) {
    return 0;
  }
  return radius;
});

pieSeries.labels.template.adapter.add('fill', function(color, target) {
  if (target.dataItem && (target.dataItem.values.value.percent < 5)) {
    return am4core.color('#000');
  }
  return color;
});
```

The behavior I'm seeing is related to clicking on the legend and making a slice disappear: as the remaining slices are recalculated, some of the values initially below 5%  (and therefore with a radius of 0 and fill of black), go above 5%. When this happens, the radius adapter function is used to recalculate the radius and they end up at the default radius of -40 (according to my setup). However, the fill color function _never_ gets run again after it is initialized, so the text remains black. I did a bunch of testing, and confirmed that the function is not running. I also had an adapter that was adjusting the relativeRotation, but this too was not being re-run with the other calculations, with the exception that when a slice was _added back in_ to the pie, the rotation was recalculated once (at 0% because of animations), and as slices were added back, the direction of the labels was all "randomly" askew.

It seems that this bug might be related to some algorithm that is ignoring certain properties while running the adapters, but I wasn't able to cut through the code enough to say for sure, otherwise I would gladly submit a PR. I did my best to search other issues and documentation, but didn't see anything related to this issue. Sorry if this is somehow a duplicate. I'd be very interested to see the solution/workaround/docs if they exist for this problem.

Here is a gif:

![adapterbehavior](https://user-images.githubusercontent.com/26337310/74255415-d721c300-4cbf-11ea-9693-59dade060a09.gif)

**Comment by zeroin** [comment]
The sprite uses adapter when a getter of a property is called. So for example for a label, fill is set once and the adapter is used, but later the sprite does not do anything with fill unless you force it to do. If we'd make the sprite to check for each property adapter every time the other property is changed, it would make things really slow. So the hack in this case is this - if you know that some property is changed or accessed, use this adapter to set fill for the sprite by simply adding a line: `target.fill = target.fill`

**Comment by tehpsalmist** [comment]
Thanks for the response, @zeroin .

I understand the performance implications, that makes sense. Thanks for the tip on how to trigger it. What would be the best practices around "where" to put such a line of code? (speaking about `target.fill = target.fill`)

**Comment by tehpsalmist** [comment]
It seems I need to insert that line at the point in time when all of the animations have finished running, or at least uniformly throughout the time the animations are running, because so far I have only been able to inject it at the start of the animations and that isn't accurate by the time the animation ends.

**Comment by zeroin** [comment]
For purposes like this I often use dx adapter, as it is called a lot:

```
pieSeries.labels.template.adapter.add('dx', function(dx, target) {
  target.fill = target.fill
  return dx;
});
```
Or you could even add the whole logic of the fill there and not use fill adapter at all.

**Comment by tehpsalmist** [comment]
Bummer, I still can't get it to work even with this dx idea (I think this also creates an infinite loop, as I can see my console.logs never stop and it is crashing my devtools, so this is probably a bad idea anyway). Is there anything specific I can show you that would help you help me? I'm trying to set `fill` and `relativeRotation` this way, and neither are taking effect, even though radius is.

**Comment by zeroin** [comment]
Could you create a codepen of the situation, it would speed things up and I could work with the exact case - thanks!

**Comment by tehpsalmist** [comment]
https://codepen.io/tehpsalmist/pen/jOPbBvx

If you open up "other" and then remove/add some of the larger slices, you'll see the behavior I'm referring to pretty explicitly.

**Comment by zeroin** [comment]
I tried this with dx adapter and it seems to work fine:
https://codepen.io/team/amcharts/pen/xxGwdVw

**Comment by tehpsalmist** [comment]
Ok, it looks like the `else` condition and use of `undefined` was what I was missing. Thanks for looking into this. However, this seems like not the greatest resolution, as that dx function is now running continuously. My issue is resolved (I suppose), but I'm a little uncomfortable with an infinite loop running on my main thread, even though it appears to be asynchronously doing so. How can I request a feature where the fill and relativeRotation are evaluated on their own within the render cycle of the chart?

**Comment by zeroin** [comment]
Indeed, dx adapter does the infinite loop in this particular case. So my suggestion would be to put it all to the radius adapter: https://codepen.io/team/amcharts/pen/xxGwdVw

**Comment by tehpsalmist** [comment]
I'm still seeing the loop, unfortunately, and to the same degree of severity. Thank you so much for your time with this. It seems that as long as these infinite loops are possible (a non-trivial problem to solve, I'm sure), then maybe a feature request can be considered that these individual adapters be respected for any key during the render cycle.
