### ISSUE TITLE
Docs Error: Responsive !== Responsible

### ISSUE THREAD

**Issue by tehpsalmist** [amcharts/amcharts4#2124]
https://www.amcharts.com/docs/v4/concepts/responsive/#Using_pre_defined_named_breakpoints

The api is `am4core.ResponsiveBreakpoints`, but the list of possible properties (very helpful, by the way) has the typo `.ResponsibleBreakpoints`.

I hope this is a helpful place to report this. Thanks so much for making this project so robust!

**Comment by martynasma** [comment]
Wow, what an irresponsiBLe typo :)

Thanks for the heads up! Fixed.
