### ISSUE TITLE
Hover state prevents custom state from being displayed

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#2126]
I'm trying to apply to separated states on chart columns template : an `hover` state and a custom `clicked` state. The thing is, the hover state prevents the custom state to last: the custom state stays visible only on click then disappear. When the hover state is removed, all works perfectly.

https://codepen.io/segolene-albouy/pen/WNvQVmd

I tried to use the `active` state but then the custom properties don't properly disappear when clicking on an other column.

![active-state](https://user-images.githubusercontent.com/44207487/74428579-95c51b00-4e59-11ea-90a0-2ca0bb238bd3.png)

I could set the properties in the `changeClickedColumn` function but it won't fit my needs outside this simplified example.

How can I proceed to keep those two states concurrently?

Thank a lot for all your help!

**Comment by zeroin** [comment]
Here is how I would do it:
https://codepen.io/team/amcharts/pen/XWbXrxm

added:

`series.columns.template.togglable = true` so that active state is applied when clicked.
Also added `hit` listener ans simply tell all the columns that they are not active.

**Comment by Segolene-Albouy** [comment]
Thank you very much!
