### ISSUE TITLE
Heatmap within a heatmap, or help in figuring out some other way to display this info

### ISSUE THREAD

**Issue by sscots** [amcharts/amcharts4#2127]
I have a challenging heatmap I need to try and build and need some guidance on how it can be, or if it can be, achieved with amcharts 4.

My current heatmap is just an X & Y axis with blocks where the color is based on a scale from 1 to 30, very similar to this one: 
https://www.amcharts.com/docs/v4/wp-content/uploads/sites/2/2019/05/chrome_2019-05-28_11-05-38.png

In my scenario each individual block is a list of items where each item in the list has a status, and the count that you see in my current version is ONLY the total count of items with the status of "completed", where as the possible statuses could be "failed", "waiting", "done", "completed".
**What I want to do is get even more granular and show different colors for each status within each heatmap block**.

It doesn't have to be within this chart, and in fact it doesn't have to be a heatmap, but some way visually pleasing to display this info.

**Comment by martynasma** [comment]
Before we think if it's technologically possible, try imagining, better yet make a mockup, how such "tripple" heat map would look like, and whether such end-result would be useful to user of readable at all.

Maybe it would make more sense to have three adjacent distinctive charts for three metrics?
