### ISSUE TITLE
How to add gradient to the chart with scaling support?

### ISSUE THREAD

**Issue by VitalyV** [amcharts/amcharts4#2128]
Hi there,
I want to make a chart like this:
![Chart_with_gradient](https://user-images.githubusercontent.com/6535549/74551621-58ee4680-4f75-11ea-89f4-9db5dcdf9c5a.png)

I can add a gradient to the chart uses `renderer.gridContainer.background.fill`, but I need to have scaling support for gradient.

If I select a place where background is green, I need to set green background for the whole chart and vice versa.

What correct ways do we have to implement this functionality?
Thanks.

**Comment by martynasma** [comment]
> If I select a place where background is green, I need to set green background for the whole chart and vice versa.

In other words you need your gradient background to zoom together with the map.

Probably the easiest way to do it would be to create a one large column (via separate ColumnSeries) that would cover the whole area, then have it filled with gradient.

That said, the zooming of gradient will work only horizontally.

https://codepen.io/team/amcharts/pen/3b252d1d7f5844dd13a23736b5703c09?editable=true

Looking at your screenshot it seems you have a rotated gradient. I'm not sure how to implement rotated gradient zooming :(

**Comment by VitalyV** [comment]
@martynasma 
Thank you for your answer.

To be honest, I did it, but I use a very complex solution that has many limitations.

That is why I decided to find out, maybe there was an easier way.

Are there plans to add similar support for the gradient?

Thanks

**Comment by martynasma** [comment]
> Are there plans to add similar support for the gradient?

No, I'm afraid. Gradient is not something we paint ourselves. It's an SVG filter. In order for it to be zoomable we would somehow need to zoom actual element so that gradient zooms with it, and this would be super complicated. Sorry.

**Comment by VitalyV** [comment]
@martynasma 
I understood.
Thank you
