### ISSUE TITLE
DateAxis not setting the min value properly when stacked=true

### ISSUE THREAD

**Issue by xiandew** [amcharts/amcharts4#2129]
The dateaxis starts from 1970 when I have two series stacked together
https://codepen.io/xiandew/pen/jOPqrXP

**Comment by martynasma** [comment]
I'm not entirely sure if using stacking on a DateAxis makes sense. How do you add two days?

You already have both `dateX` and `openDateX` fields and values set, so you do not need stacking.

I imagine what you are looking for is disabling clustering:

```
series1.clustered = series2.clustered = false;
```

**Comment by xiandew** [comment]
Thanks so much! That's right. I just want to disable clustering 👍
