### ISSUE TITLE
need to rotate chart @90 degree

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#2130]
90 degrees (the columns will become bars)
amchart 3 there is proprty chart.rotate=true;,but amchart v4 how to achive this functionality

**Comment by martynasma** [comment]
In that case just push your `CategoryAxis` (or `DateAxis`) into `chart.yAxes`, and `ValueAxis` into `chart.xAxes`.

As well as update your series data fields accordingly.

Here's a demo:
https://www.amcharts.com/demos/bar-and-line-chart-mix/

**Comment by Mahisandy** [comment]
but in amchart v3 there is proprty for rotate why its not present in v4 its very difficlt to change for yAxes and xAxes as well as for tooltipText .

**Comment by martynasma** [comment]
¯\_(ツ)_/¯

**Comment by Mahisandy** [comment]
> `¯\_(ツ)_/¯`

@martynasma  ,what's the meaning of that.

**Comment by martynasma** [comment]
It means "oh well" ;)
