### ISSUE TITLE
[Question] How can we use legends as filters in AmCharts4?

### ISSUE THREAD

**Issue by bluefangs** [amcharts/amcharts4#2131]
Currently, in amchart4, the legends can be used to show / hide the target series on click. I would like the behaviour wherein on clicking on the legend:

1. Do not hide the clicked series.
2. Hide all other series except the one that was clicked so as to show only the seires whose legend that was clicked.

This question is on the back of an [older question](https://stackoverflow.com/q/44504923/1745073) targetting amcharts3. However, since v4 is significantly different from v3, the answer does not work.

Based on the documentation [here](https://www.amcharts.com/docs/v4/tutorials/toggling-multiple-series-with-a-single-legend-item/), it appears that the below should work:

```
series1.events.on("hidden", function() {
  series2.hide();
  series3.hide();
// but when I run series1.show() in order to mimic series1 to not hide, I get a max call size exceeded msg
});
```
Further to that, according to [this](https://www.amcharts.com/docs/v4/tutorials/disabling-toggling-of-items-in-legend/), one can outright disable the toggle on the legends - but it works at the cart level and not at the series level.

Note: Cross posted on SO : https://stackoverflow.com/questions/60221701/how-can-we-use-legends-as-filters-in-amcharts4

Thanks.

**Comment by zeroin** [comment]
Here is how you do it:
https://codepen.io/team/amcharts/pen/285b315ff30a2740fdbf72f27230711c

To avoid SO you need to make itemContainers not togglable:

```
chart.legend.itemContainers.template.togglable = false;

chart.legend.itemContainers.template.events.on("hit", function(event){
    var target = event.target;

    chart.legend.itemContainers.each(function(item){
        if(item != target){
            item.isActive = true;
            item.dataItem.dataContext.hide();
        }
    })
    target.isActive = false;
    target.dataItem.dataContext.show();
})
```

**Comment by bluefangs** [comment]
Thanks @zeroin This works perfectly. There is a small second part to this that also has to work. How do I re-enable all the series again?  In the graph I'm building, I have a series called 'allTraffic' and multiple other series. 

1. AllTraffic should never get hidden.
2. When I click on any of the other series apart from AllTraffic, hide the other series apart from AllTraffic and the series whose legend has been clicked.
3. Reset everything (bring back all the series) when AllTraffic's legend is clicked.

How do I go about this?

**Comment by zeroin** [comment]
I would say it's the right way.

**Comment by bluefangs** [comment]
Thanks @zeroin ! Good to close.

**Comment by snasir3** [comment]
Hi, I know this issue had been closed but my issue is very similar to this:
- same as above but when you click on a legend 2nd time it enables all the legends/series data on thee chart
for example, when you first click on a legend it only shows the data for that legend on the chart and hides all other series but clicking it again shows all the series/legend.

**Comment by snasir3** [comment]
Hi [zeroin], 
I am working towards achieving the same goal as above except the 'All' option. My task is to implement the following:
- when you first click on the legend it only shows data for that legnd and hide other legends
- clicking the same legend reset everything

**I have come up with the below but it has same issues. For instance, when one legend is clicked and you click legend 2 this leaves the previously selected legend in grey and activates all the other legends and when you click again on legend 2 it shows previously selected legend as well as legend 2.**

chart.legend.itemContainers.template.togglable = false
    chart.legend.itemContainers.template.events.on('hit', (event) => {
      const { target } = event
      chart.legend.itemContainers.each((item) => {
        const state = item
        // if (state !== target) {
        //   state.isActive = true
        //   state.dataItem.dataContext.hide()
        // }
        if (state.dataItem.dataContext.isHidden) {
          state.isActive = false
          state.dataItem.dataContext.show()
        } else {
          state.isActive = true
          state.dataItem.dataContext.hide()
        }
      })
      target.isActive = false
      target.dataItem.dataContext.show()
    })

**Any help is much appreciated!!**
