### ISSUE TITLE
XY Chart labels are exceeding the chart boundry

### ISSUE THREAD

**Issue by tarikziyad9** [amcharts/amcharts4#2132]
When I have some values in the XY chart, some column label locations' are exceeding the boundary of the chart, like in the image, how can I suppress that?

![image](https://user-images.githubusercontent.com/41581421/74648464-ce812f00-518e-11ea-8d99-f4e37fad3f3f.png)

**Comment by martynasma** [comment]
ValueAxis does not take labels into account when calculating scale.

You can add additional scale padding using `extraMax`:

https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Relatively_expanding_the_scale

**Comment by tarikziyad9** [comment]
> ValueAxis does not take labels into account when calculating scale.
> 
> You can add additional scale padding using `extraMax`:
> 
> https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Relatively_expanding_the_scale

This worked fine for the data, but for the x-axis labels I still have the same problem 

![2020-02-18](https://user-images.githubusercontent.com/41581421/74710834-9ed83280-5233-11ea-8908-3b636091abff.png)

**Comment by zeroin** [comment]
You can solve this by either increasing `paddingRight` of the whole chart or by setting `axis.maxLabelPosition = 0.98` which would result last label to be hidden.

**Comment by tarikziyad9** [comment]
Thank you, paddingRight is working fine
