### ISSUE TITLE
[Question] How can I create animated line on map chart in AmCharts4?

### ISSUE THREAD

**Issue by slavakamrad** [amcharts/amcharts4#2134]
I want to use amCharts for create connection map. I took this demo: https://www.amcharts.com/demos/animations-along-lines

But, I want to draw a curved line between two locations and animate the creation of this line between the two points instead of an airplane. Can this be implemented?

**Comment by martynasma** [comment]
There you go:
https://www.amcharts.com/docs/v4/tutorials/animating-map-lines-with-css/

**Comment by slavakamrad** [comment]
Oh... Thank you! It's work!

**Comment by slavakamrad** [comment]
> There you go:
> https://www.amcharts.com/docs/v4/tutorials/animating-map-lines-with-css/

And another question from the same theme. I create a unique ID using `+ (new Date()).getTime();` but I lose css property for draw... How I fix it? 

`var line = lineSeries.mapLines.create();
line.multiGeoLine = connect;
line.line.controlPointDistance = -0.2;
// добавляем анимацию линии через css
line.id = "myline"  + (new Date()).getTime(); 
line.setClassName();

setInterval(function(){
  line.hide();  
},3000)`
