### ISSUE TITLE
Bug concerning the hours in the GanttChart

### ISSUE THREAD

**Issue by TristanLavalou** [amcharts/amcharts4#2138]
Hello,

I want to report an issue concerning the GanttChart you gave in your documentation (https://www.amcharts.com/demos/gantt-chart/). If you want to put a precise hour (like 11:49), it will be rounded up to 12:00. In fact, only plain hours and half hours are displayed.

Below, an example using your CodePen with 10:45, displayed as 10:30 :
![AMCHARTS](https://user-images.githubusercontent.com/43167576/74741587-62213100-525d-11ea-879c-7ff690e8d6a5.png)

Is it possible to fix this bug?

Thanks :)

**Comment by zeroin** [comment]
Yes, you just need to set the baseInterval manually, like: 
`dateAxis.baseInterval = {timeUnit:"minute", count:1}`

**Comment by TristanLavalou** [comment]
Thanks a lot @zeroin!

We found another issue concerning the labels on the GanttChart. We just want to write in boxes as the example below :
![Capture](https://user-images.githubusercontent.com/43167576/74843107-beeb1d00-532b-11ea-9b9b-dfb7ed1ef8f4.PNG)

If we want to use a LabelBullet and to limit the time window, labels could disappear or be cut. Please, could you provide us a solution?

Here is the CodePen if you want to have a greater overview : https://codepen.io/amcharts4/pen/VwLKweK

**Comment by zeroin** [comment]
To solve this, you should add bullets as children of columns, not as a bullet of series. Then you can align it in a middle of a column:
https://codepen.io/team/amcharts/pen/f3429c11a8a0c4cf89d123629b801ce8

**Comment by TristanLavalou** [comment]
Nice, it works very well! Thanks! 😄
