### ISSUE TITLE
Custom Line chart

### ISSUE THREAD

**Issue by silviucuruciuc** [amcharts/amcharts4#2139]
Hello.

I have to create a chart that looks like this 

![percentile](https://user-images.githubusercontent.com/13822464/74756474-42016a00-527d-11ea-8ba4-59f820b34273.png)

Could you please advise on which chart is best to use and what adjustments do I need to make in order to achieve this?
Please note that is important to have those lines that go downwards to the x axis.

Thanks!

**Comment by zeroin** [comment]
It's a simple XY chart, with two series - LineSeries and ColumnSeries. They should use the same dataFields and Column Series should have a fixed column width set:

`columnSeries.columns.template.width = 2;`

**Comment by silviucuruciuc** [comment]
Thank you!
