### ISSUE TITLE
Disable rerendering when content page moves

### ISSUE THREAD

**Issue by Legends** [amcharts/amcharts4#2140]
I have a sidebar which when it gets closed makes the content page shift to left (padding-left) to fill the whole space.
Is there a way to disable rerendering (readjustment) of the chart during the shift?
Currently it makes the whole animation look jumpy.

I could make it `display:none` and at the end make it visible again, but is there another way to just tell it not to readjust and after the animation is complete to tell it to adjust itself again?

**Comment by martynasma** [comment]
Try pausing the whole system:

```
am4core.system.isPaused = true;
```

To unpause:

```
am4core.system.isPaused = false;
```

**Comment by Legends** [comment]
Yup, that helps. Thanks!

**Comment by Legends** [comment]
@martynasma **fyi**

On desktop this works nice, but when testing the page on chrome android the right edge of the page starts to flicker extremely.

I narrowed it down to my custom css style for the scrollbars (works only on chrome and FF).
Disabling the css eliminates the flicker.

I guess custom scrollbar styles are still experimental...

Actually I should disable the style for mobile devices anyway...



```
html {
  scrollbar-color: rgb(194, 194, 197) #efefef;
  scrollbar-width: thin;
}

::-webkit-scrollbar {
  width: 11px;
}
 
::-webkit-scrollbar-thumb {
  background-color: rgb(194, 194, 197);
  &:hover {
    background-color: #d8d8dc;
  }
}
....
..
```

**Comment by martynasma** [comment]
Thanks for sharing this!
