### ISSUE TITLE
Fetch data from googlesheet json into a map chart

### ISSUE THREAD

**Issue by wewlad-dev** [amcharts/amcharts4#2141]
I tried to fetch data from a googlesheet json file with variables `gsx$countryid` and `gsx$value` to the 3D rotating map of amcharts, but for some reason it's not working unless it is hardcoded

**Comment by martynasma** [comment]
First of all, your fiddle does not load jQuery, which you are trying to use to load the data.

Second, jQuery `getJSON` function is asynchronous, which means that map is created before data is loaded. You should start creating map in a handler for `getJSON` call.

You will also need to parse the data loaded from Google, as it comes in a JSON structure that is not compatible with `MapChart`.

**Comment by wewlad-dev** [comment]
While trying it I loaded jQuery and having it run within `getJSON`, like the fiddle now. but still having the same issue. I think it is what you said last is not being compatible with MapChart, how to map it to be compatible? Thank you

**Comment by martynasma** [comment]
> ... how to map it to be compatible?

I'm afraid that's a bit out of scope of this GitHub repository. You get the data in JSON structured by Google Docs. It's up to you as a coder to create a code that would transform it into a structure suitable for Map Chart.

I wish we had an example like that readily available, to make it easier. But we don't :(

**Comment by wewlad-dev** [comment]
Oh bummer! Thanks for guiding me anyway, and if there are any examples for using mapchart -regardless what kind of chart- and json it would be great.
