### ISSUE TITLE
Multiple charts on one page

### ISSUE THREAD

**Issue by lec23** [amcharts/amcharts4#2142]
Hi, I am pretty new to data visualization and coding and I am trying to put two charts (and preferably more) on one web page. I copied the demo code for the type of chart I wanted from amCharts, put it into codepen into the html section and edited the data to represent the data I have for my project. It looks great and works when I put the code into my index.html file to host on github but I can't figure out how to put another chart on the same web page (using the same process). I apologize for my very limited knowledge of coding but is there a simple thing I am missing or is it more complicated than I think it is? My goal is to create multiple different types of charts for the same data set so I can show my advisor and they can choose which ones they prefer. I don't have an issue with just getting the image of the chart (and putting it into a pdf) but I like that the amCharts are interactive so my plan was to put them all on one webpage then send the webpage to my advisor so they could see them all and interact with them all in one place. Is this the best way to go about this? Or should I try a different approach? Is there a way to export the html to pdf while still keeping the chart interactive?

If any of my code or further explanation is needed just let me know. Thank you!

**Comment by zeroin** [comment]
You should simply create more div's in your HTML section, give unique id for each of them and then, when creating a chart this line:

`am4core.create("chartdiv1", am4charts.XYChart)`

should use a different id for each chart.

**Comment by lec23** [comment]
That worked! Thank you so much! I'm glad it was something simple.

**Comment by guthriegobar** [comment]
> You should simply create more div's in your HTML section, give unique id for each of them and then, when creating a chart this line:
> 
> `am4core.create("chartdiv1", am4charts.XYChart)`
> 
> should use a different id for each chart.

I am new to data visualization as well. I used am5 to create a chart and i cant seem to find how to create more than one. Could you please help.
