### ISSUE TITLE
Axis labels html adapter not working?

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#2143]
In the docs there is a html adapter for axis labels:
https://www.amcharts.com/docs/v4/reference/axislabel/#html_adapter

But it seems the html adapter is not working... instead of the label value the callback function gets undefined.
(text adapter works as expected)

Simple pen:
https://codepen.io/chrisadler/pen/JjdKwVa

![image](https://user-images.githubusercontent.com/58069494/74806305-eb7c4600-52e5-11ea-9905-33fdfa5ee831.png)

**Comment by martynasma** [comment]
Axis labels draw their data from `AxisDataItem` which does not have `html` property, hence value that arrives to `html` is `undefined`.

So you won't be able to reference it by variable.

There are a few ways to go about it:

1) Adapter-less. Just set `html` for label template referencing to `text` in dataitem:

```
yAxis.renderer.labels.template.html = "{text} B";
```

2) If you need an adapter:

```
yAxis.renderer.labels.template.adapter.add('html', text => '{text} B');
```

Hope this makes sense.

**Comment by lticadler** [comment]
Thanks :) 
Updated the pen with both ways.
