### ISSUE TITLE
Geochart with custom geojson renders incorrect

### ISSUE THREAD

**Issue by achilovbakhrom** [amcharts/amcharts4#2144]
Hello!
We are using amchart in our local project and we want to show our region. We have geo json data of our region. We tried to render geojson on http://geojson.io/ and everything works perfect. 
![Screenshot_1](https://user-images.githubusercontent.com/18023993/74813642-788bc300-5317-11ea-9c81-f8df2b16d31d.png)
But with amchart the result is:
![Screenshot_2](https://user-images.githubusercontent.com/18023993/74813705-90fbdd80-5317-11ea-956e-14e069f8d489.png)
We have tried to set special ids for every region, to change scale but didnt help.

**Comment by martynasma** [comment]
Can you post your map on CodePen?

**Comment by Sam116** [comment]
Have the same problem, any solutions?
