### ISSUE TITLE
Incorrect pie series when using JSON config

### ISSUE THREAD

**Issue by rchadwic** [amcharts/amcharts4#2147]
When using a JSON config with series level data, the render seems to show the same data in each series. Oddly, when setting this up in JS (not the JSON), the render appears correct. 

See https://jsfiddle.net/pt8xn7sf/

**Comment by martynasma** [comment]
The issue with your char is that you do not specify what type of series you have (`type: "PieSeries"`). If you add those into your config, everything will just work just fine.

https://jsfiddle.net/amcharts/xjpeLqfd/

**Comment by rchadwic** [comment]
Fantastic! Thank you!
