### ISSUE TITLE
Data item grouping not working with Gantt chart

### ISSUE THREAD

**Issue by yudarik** [amcharts/amcharts4#2148]
I have a gantt chart that need to display a lot of data items for the whole year, as data items grows, the performance of the chart becomes very poor, so I've tried to group data items as suggested [here](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping). 
My chart looks similar to the one used in the [demo](https://www.amcharts.com/demos/gantt-chart/), except that it has more than 2K nodes.
Unfortunately what works great for an XYChart, does not works for Gantt.
Is there any other setting I need to add except for `dateAxis.groupData = true;` to make it work?

**Comment by martynasma** [comment]
No, I'm afraid.

I can't even imagine how that would work. When grouping single points, it's easy.

In Gantt you have floating columns that start and end anywhere. How would you group them? :)

**Comment by yudarik** [comment]
Well I thought maybe you already managed to do that.
But if I would need to guess, then almost the same as on regular ColumnSeries, where the date is the "fromDate" and the "value" is the duration (toDate-fromDate). And since the value is not really relevant in that case, we can omit the toDate from the calculation.
The rest is the same, just as it's was described in the [docs](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping).
Am I missing something?

**Comment by yudarik** [comment]
I've managed to achieve some sort of grouping, after I've add the `baseAxis` property to my series as dateAxis. But the grouping is done weird, across all axis X and Y.
Meaning that instead of groping only by date, the items are grouped both by date and category.
And once I zoom-in, instead of showing more items, the chart shows less.

**Comment by martynasma** [comment]
I think it might theoretically be useful if somehow we'd group all open and end values and data items that fall within them into a single one.

However, that adds a whole new dimension to an already super complicated mechanism, with frankly very little application.

I'm sorry, but this feature is simply not meant for what you are trying to do :(
