### ISSUE TITLE
Bent Label: Truncante and hideOversized don't work.

### ISSUE THREAD

**Issue by pauloalexandre3d** [amcharts/amcharts4#2149]
Hi,
I'm trying to fix the label in the Radar Timeline, and the truncate doesn't look work properly.

For example:
![image](https://user-images.githubusercontent.com/3245563/74933424-cf5ad080-53db-11ea-9e54-cac3d71748f2.png)
![image](https://user-images.githubusercontent.com/3245563/74933631-4abc8200-53dc-11ea-9551-e4419f23a987.png)

This is my setup:
`
var axisLabel = axisRange.label;
 axisLabel.interactionsEnabled = false;
 axisLabel.bent = true;
 axisLabel.location = 0.5;
 axisLabel.fill = am4core.color("#ffffff");
 axisLabel.radius = 3;
 axisLabel.relativeRotation = 0;
 axisLabel.textAlign = "start";
 
 axisLabel.truncate = true;
 axisLabel.hideOversized = true;
 axisLabel.fullWords = false;
`

Best regards,
Paulo

**Comment by zeroin** [comment]
Unfortunately `bent` labels do not yet support truncating or wrapping. We will let you know when/if this will be implemented.

**Comment by pauloalexandre3d** [comment]
@zeroin Could we do left justify this label text?

Thanks,

**Comment by martynasma** [comment]
Sorry for the wait. I'm afraid we won't be able to implement truncation or wrapping on bent labels.
