### ISSUE TITLE
Question : Column Series, togglable legend for Individual legend item for each column

### ISSUE THREAD

**Issue by mahesh-chotrani** [amcharts/amcharts4#2150]
I would like to know how to have legends `togglable` for a column chart with custom legends (_as shown in the example - https://www.amcharts.com/docs/v4/tutorials/individual-legend-item-for-each-column/_)
Here `legend.itemContainers.template.togglable` has specifically turned as false.

I saw one of the similar questions - #348. But the approach is to have multi series, which is not what I am looking for as I have dynamic series.

**Comment by zeroin** [comment]
Here is a demo: https://codepen.io/team/amcharts/pen/bGNyXod

**Comment by mahesh-chotrani** [comment]
Thank you very much for quick response, @zeroin  !

This is exactly what I needed. Hope this can be included in the example / demo section as many people have asked this at various sites, but no answer (_especially with v4_).
