### ISSUE TITLE
How to change the scrollbar width?

### ISSUE THREAD

**Issue by VitalyV** [amcharts/amcharts4#2151]
Hi,
By default when initializing a chart we see the following behavior
![image](https://user-images.githubusercontent.com/6535549/74937788-9ab43c80-540e-11ea-8a1c-f50b3f999f3d.png)

How to change the scrollbar width like this?
![image](https://user-images.githubusercontent.com/6535549/74937819-a869c200-540e-11ea-9cbb-4b1093b65467.png)

This is not scaling.

Thanks

**Comment by zeroin** [comment]
This will do the thing:

```
chart.scrollbarY.marginLeft = 20;
chart.scrollbarX.marginBottom = 20;
```

**Comment by VitalyV** [comment]
@zeroin Thank you for your answer but this is not what is required!
For: 
```javascript
chart.scrollbarX.marginBottom = 50;
chart.scrollbarY.marginLeft = 50;
```
![image](https://user-images.githubusercontent.com/6535549/74941615-26c96280-5415-11ea-86b3-9b97086e79cb.png)

**Comment by zeroin** [comment]
Try this:

```
chart.scrollbarY.paddingTop = 12;
chart.scrollbarY.paddingBottom = 12;

chart.scrollbarX.paddingLeft = 12;
chart.scrollbarX.paddingRight = 12;
```
