### ISSUE TITLE
addData to force directed series

### ISSUE THREAD

**Issue by mcverticchio** [amcharts/amcharts4#2152]
I am attempting to dynamically update a force directed tree (with a fairly nested data structure).  Its possible that new children could be added somewhere within the tree structure, not likely to be added to the end (unlike a line graph for instance).

My question is, is this possible with addData without having to rerender the whole chart?  I'd like to just smoothly show a new branch being added (or removed) and not reanimate the entire chart.

If this is not possible, do you have any plans for this in the future?

**Comment by martynasma** [comment]
No, I'm afraid it's currently not possible to incrementally add data for chart types that are using hierarchical data structure.

We might add it in the future, but there are no exact plans for it in place, I'm afraid.

**Comment by martynasma** [comment]
I'm afraid we won't be able to implement incremental updates on ForceDirectedTree chart. There's just too many moving parts there for it. Sorry.
