### ISSUE TITLE
Errors on add and visualizing new series over a x DateAxis

### ISSUE THREAD

**Issue by nathanredblur** [amcharts/amcharts4#2155]
I have this simple example where I add and remove series from data.

I don't know why look bad on add. check this example:
https://codepen.io/nathanredblur/pen/NWqRoab?editors=0011

also notice how the colors of the line not return to the initial state(blue) and zoom doesn't work well

**Comment by martynasma** [comment]
Your data seems to be in descending order. DateAxis expects data in ascending order.

As for colors, chart uses ColorSet and iterates between color list, generating new colors if it runs out.

Removing series, does not "free up" the color used for it. If you need to reset the color list to the start, you can call `chart.colors.reset()`.

Or you can set color for the series manually:

```
series.stroke = chart.colors.getIndex(seriesIndex - 1);
series.fill = series.stroke;
```

**Comment by martynasma** [comment]
CodePen with the above fixes:
https://codepen.io/team/amcharts/pen/eb516ed90abdf96c4ed222d12db4ee02?editors=0011

**Comment by nathanredblur** [comment]
Awesome !, thanks!
