### ISSUE TITLE
How to bold a column's category label when a column is hovered?

### ISSUE THREAD

**Issue by lgerndt** [amcharts/amcharts4#2156]
[CodePen that demos the problem](https://codepen.io/lgerndt/pen/rNVxMVp)

Here's the problem:

I'm using the **over** (and **out**) events on Column in order to try to change the style of the corresponding category axis label (like make it bold, or, as in the CodePen example, color it red).

Here I register for the `over` event:
`series.columns.template.events.on('over', this.onBarOver);`

Here's my `over` event handler:
```
  onBarOver = (e) => {
    const { index } = e.target.dataItem;
    const label = this.categoryAxis.renderer.labels.values[index];
    label.fill = this.labelColorSelected;
    label.fontWeight = 500;
  };
```
The problems is that it affects the previous column's label instead of the hovered column's label.  Ah, so just increase the index by 1, you say.  Alas, that works at first, but we have some other interactions for the chart like clicking a bar to select it.  I'm using column fill adapters to dim all but the selected bar.  After selecting a column, and then un-selecting it, now the index is not off by one, everything works as expected.

In trying to debug this I noticed that even though my data contains only 6 columns, there are eight category axis labels in `categoryAxis.renderer.labels.values`, which is very confusing to me.  Can you help me with the correct implementation?  Thanks in advance!

**Comment by xorspark** [comment]
Use the `dataItems` list in the category axis instead of the renderer's labels.

```
series.columns.template.events.on('over', (e) => {
  const { index } = e.target.dataItem;
  categoryAxis.dataItems.getIndex(index).label.fill = 'red';
});
series.columns.template.events.on('out', (e) => {
  categoryAxis.dataItems.each((axisDataItem) =>  {
    axisDataItem.label.fill = 'black';
  });
});
```

[Updated codepen](https://codepen.io/team/amcharts/pen/cade3c90dbde127c3a8e83153eab9207?editors=0010)

**Comment by lgerndt** [comment]
Works like a charm, thank you SO MUCH marty for responding so quickly, made my day!
