### ISSUE TITLE
Dynamically import the country geodata with ES6 - Maps

### ISSUE THREAD

**Issue by vdraceil** [amcharts/amcharts4#2157]
https://www.amcharts.com/docs/v4/tutorials/building-drill-down-maps/#Loading_maps_dynamically

In this tutorial the geodata for the country clicked is being loaded from an external source (from data hosted on amcharts.com).
Is it not possible to dynamically import the geodata based on the current country and use that?

I'm using Vue.js (+Quasar) and I tried
```
let country = 'indonesia'
let { default: geodata } = await import(`@amcharts/amcharts4-geodata/${country}Low`)
// then use the geodata to construct the map
```
This failed with error _Critical dependency: the request of a dependency is an expression_

However when using a plain string, it works alright.
```
let { default: geodata } = await import('@amcharts/amcharts4-geodata/indonesiaLow')
```
This works.
... but my page/component is country dependent and I dont want to load all maps at once.

I have **amcharts4** and **amcharts4-geodata** installed via npm as dependency modules.
Is dynamic importing (with ES6) possible or loading the geodata from an external source is the only way out?
.. or am I doing something wrong?

This most likely is not an issue with amcharts, but just a question.

**Comment by vdraceil** [comment]
I'm trying to set the `geodata` property of the map series directly, after loading.
It works if the map data is imported already anyway.
Is there anything wrong with that approach? The note in the tutorial says thats not how its done (rather using `geodataSource`) but doesn't say the why part.

**Comment by martynasma** [comment]
The following Mozilla tutorial deals with dynamic imports of modules:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports

Hope you find it useful.

**Comment by vdraceil** [comment]
The way the dynamic import was done is actually correct.
I digged deep enough and understood that webpack requires a relative path of some sort if I'm going to use dynamic imports in my code.. and even so, its going to take up every module in the directory and bundle it (just in case).
So, the vendor.js bloats up with the whole **am4charts-geodata** JSONs.

The best way is to of course self-host the geo-data JSONs in the static dir or something and load it up via an XHR call - I suppose.

**Comment by vdraceil** [comment]
I'm thinking of using the CopyWebpackPlugin to copy the JSONs from _@amcharts/am4charts-geodata/json/*.json_ to the **dist/** dir at build time and host from there.
Do you think thats the best way to go about this for a website?

**Comment by martynasma** [comment]
Well, it depends. If you only need just a few maps, and do not want to take up a lot of space for developers/users of your app by inlcuding the whole `@amcharts/amcharts4-geoada` as a dependency, then yes it would make sense just to copy the maps that you need selectively.

I'm not familiar with the Webpack plugin you mentioned, but it sounds like it does exactly that.

**Comment by vdraceil** [comment]
Got it! Thanks @martynasma
