### ISSUE TITLE
StockChart not rendering properly in AmCharts4 typescript

### ISSUE THREAD

**Issue by Meenal-Sharma** [amcharts/amcharts4#2158]
@martynasma -  StockChart not rendering properly in AmCharts4 in typescript. In my dataset, I'm not having the open, high, low, close points, due to which chart is not rendering properly. Also, zoom in and out is also having the issue.

**Comment by martynasma** [comment]
There's no StockChart in amCharts 4. Are you sure you are using V4?

**Comment by Meenal-Sharma** [comment]
https://www.amcharts.com/demos/stock-chart/
I'm using this demo.

**Comment by Meenal-Sharma** [comment]
@martynasma 
The data used here have following columns - Date,Open,High,Low,Close,Volume,Adj Close.
But I've only Date, Volume and Value. And, then the chart is not working properly.

**Comment by martynasma** [comment]
I just tried that demo in TypeScript. Works perfectly fine.

The issue is probably in your modifications. If you get any errors (runtime or during compile) they might give some clues.

**Comment by Meenal-Sharma** [comment]
@martynasma 
That particular demo is working fine at my end too. But, when I'm providing my own data with these columns Date, Volume and Value, it's not working properly.

**Comment by martynasma** [comment]
Well, then you probably can't use CandlestickSeries, you need to use either `ColumnSeries` or `LineSeries`, and do not define `openValueY`, `highValueY`, and `lowValueY` data fields.

More info here:
https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Binding_series_to_data

**Comment by Meenal-Sharma** [comment]
@martynasma
But the demo is not making use of CandlestickSeries.
