### ISSUE TITLE
Getting Json config from a Chart

### ISSUE THREAD

**Issue by tymwin11** [amcharts/amcharts4#2159]
Is there a way to get the json config of a created chart? I am creating a chart dynamically by having a base layout, and then I am adding various properties to it through the application (like adding more more series or changing the colors). I want to get the json config of the finished chart and save the config.  I just want to get something like the code below. 

{
    "xAxes": [{
        "type": "CategoryAxis"
    }],

    // Value axis
    "yAxes": [{
        "type": "ValueAxis"
    }],

    // Series
    "series": [
        {
            "type": "LineSeries",
            "dataFields": {
                "categoryX": "category",
                "valueY": "column-1"
            },
            "name": "graph 1",
            "tensionX": 0.8,
            "tensionY": 1,
            "bullets": [{
                "children": [{
                    "type": "Rectangle",
                    "width": 10,
                    "height": 10,
                    "horizontalCenter": "middle",
                    "verticalCenter": "middle"
                }]
            }]
        },
        {
            "type": "LineSeries",
            "dataFields": {
                "categoryX": "category",
                "valueY": "column-2"
            },
            "name": "graph 2",
            "tensionX": 0.8,
            "tensionY": 1,
            "bullets": [{
                "type": "CircleBullet"
            }]
        }
    ],

    // Cursor
    "cursor": {},
  
    "legend": {},

    // Data
    "data": [{
            "category": "category 1",
            "column-1": 1,
            "column-2": 2
	},
	{
            "category": "category 2",
            "column-1": 3,
            "column-2": 4
	},
	{
            "category": "category 3",
            "column-1": 5,
            "column-2": 6
        },
	{
            "category": "category 4",
            "column-1": 7,
            "column-2": 8
	},
	{
            "category": "category 5",
            "column-1": 9,
            "column-2": 10
	},
	{
            "category": "category 6",
            "column-1": 13,
            "column-2": 12
	},
	{
            "category": "category 7",
            "column-1": 16,
            "column-2": 18
	}]

    }

**Comment by martynasma** [comment]
No, I'm afraid there's currently no way to searialize the chart object into JSON config. Sorry.

**Comment by 3zzy** [comment]
+1 This would be so helpful!
