### ISSUE TITLE
Can we load multiple data source URLs for multiple series in Amcharts 4 using typescript

### ISSUE THREAD

**Issue by Meenal-Sharma** [amcharts/amcharts4#2160]
@martynasma 
Can we load multiple data source URLs for multiple series in XY Chart in Amcharts 4 using typescript?

**Comment by martynasma** [comment]
Yes. Each series can have own `dataSource` instance.

```
series1.dataSource.url = "data1.json";
series2.dataSource.url = "data2.json";
```
