### ISSUE TITLE
Question: When to dispose what

### ISSUE THREAD

**Issue by Legends** [amcharts/amcharts4#2162]
I have a global variable `let chart`. On page load a chart is created.
The user has the option to change the chart type afterwards using a settings panel.

The variable above will contain different chart types depending on users choice.

**Question: Is it enough to call dispose on the chart variable and create a new chart type?**

```
 chart.dispose();

        if (this.checked) {
            chart = CreateTreeMapChart(chart);
            chart.data = getData();
        } else {
            ({ chart, series } = CreateBubbleChart(chart, series));
            series.data = getData();
        }
```

**Comment by martynasma** [comment]
Yes, it is enough to call `dispose()` on an existing chart object to completely remove all traces of it, including DOM elements, event handlers, etc.
