### ISSUE TITLE
Unable to get rid of the xlsx dependency - Webpack

### ISSUE THREAD

**Issue by vdraceil** [amcharts/amcharts4#2163]
I'm using Vue (+Quasar) + amcharts4 (v4.9.0)
From the advice in https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/#Large_file_sizes I tried to eliminate the unwanted (for me) dependency packages from being bundled into **vendor.js**

If I just use `/canvg|pdfmake/` in the externals regex (or as a part of the function as shown in the above web page), it works and eliminates dependencies **canvg** and **pdfmake**

![Screenshot_23-Feb-2020_T20-07-39_+07](https://user-images.githubusercontent.com/10086849/75112774-93449b80-5679-11ea-825a-6990fbd52c47.png)

.. but if I make the regex `/xlsx|canvg|pdfmake/` as suggested, the build (webpack) throws an error which is absolutely unclear. So, the **xlsx** package remains.

![Screenshot_23-Feb-2020_T20-15-05_+07](https://user-images.githubusercontent.com/10086849/75112768-8627ac80-5679-11ea-926e-9eb365333a6c.jpg)

Is this a know issue or is it just happening for me (& my set up)?
My build succeeds without the externals function (adds in xlsx, canvg, pdfmake dependencies).. and also after removing canvg, pdfmake with the externals function.. fails only when I include **xlsx** in the regex part

Any pointers on how to go about this?

**Comment by vdraceil** [comment]
`Cannot convert undefined or null to object`
This error is so vague that I'm unsure on even where to start the debug/fix from

**Comment by vdraceil** [comment]
Ah ah, even when I use webpack externals to remove **canvg** & **pdfmake** dependencies, the build succeeds but the deployment fails with another strange error

```
Server listening at port 3000

500 on /
TypeError: Cannot read property 'install' of undefined
    at Function.Ai.t.use (server-bundle.js:16:215110)
    at Module.4edf (server-bundle.js:16:747158)
    at i (server-bundle.js:1:194)
    at Object.0 (server-bundle.js:1:1330)
    at i (server-bundle.js:1:194)
    at module.exports.0 (server-bundle.js:1:1291)
    at Object.<anonymous> (server-bundle.js:1:1300)
    at evaluateModule (/home/vdraceil/Workplace/Personal/test/node_modules/vue-server-renderer/build.dev.js:9318:21)
    at /home/vdraceil/Workplace/Personal/test/node_modules/vue-server-renderer/build.dev.js:9376:18
    at new Promise (<anonymous>)
```

**Comment by martynasma** [comment]
Please see the discussion in issue #82.

**Comment by vdraceil** [comment]
To clarify further - I'm trying SSR mode with Quasar (Vue.js)
webpack externals dont work for me at all. Even if I get the build to succeed, on serving the files I'm getting that weird cannot-install error.

So for now, I've excluded nothing. Just going on with am4charts as dependency.
The webpack build is being done with `production` mode. Now I see **vendor.js** and **xlsx.js** made but pdfmake and canvg seems to come inside vendor.js

![Screenshot_26-Feb-2020_T16-24-42_+07](https://user-images.githubusercontent.com/10086849/75331953-223df780-58b6-11ea-963d-bb7b115d25bb.jpg)

If I go ahead and start serving the generated files (server + client), I see xlsx.js fetched always.
In my code I have the following imports -

```
import {
  create as AM4Create,
  useTheme as AM4UseTheme,
  color as AM4Color
} from '@amcharts/amcharts4/core'

import {
  MapChart as AM4MapChart,
  MapPolygonSeries as AM4MapPolygonSeries,
  GraticuleSeries as AM4GraticuleSeries,
  projections as AM4Projections
} from '@amcharts/amcharts4/maps'

import AM4ThemeAnimated from '@amcharts/amcharts4/themes/animated'
```

So, finally, my vendor.js is about 2MB gzipped and XLSX is about 450+kB gzipped.
All dependencies are just being loaded - I'm not using any export functions - so xlsx, pdfmake, etc. shouldnt be loaded, correct?

Is this because I'm trying in SSR mode?
I'm not even sure whats going on.

**Comment by vdraceil** [comment]
@martynasma I read that discussion even before creating this issue.

What is said there is -
1. amcharts core, xlsx, pdfmake will be in separate js bundles when build in production mode with webpack. 
2. xlsx & pdfmake bundles will be loaded only when required (that is when it is imported somewhere in the code)

First I tried getting rid of the dependencies with webpack externals and that didnt end up well. Then I thought the above behavior isnt that bad at all, but now I'm facing this issue where everything is getting bundled together (besides xlsx - I'm not sure why pdfmake doesnt get bundled separately) and loaded in the browser.

amcharts v4.9.0

**Comment by vdraceil** [comment]
Okay so, this is what is working for me now
```
build: {
  vendor: {
    remove: [ 'pdfmake', 'canvg', 'xlsx' ]
  }
}
```
This entry in `quasar.conf.js` pulls out these into seperate bundles.
If anyone is attempting to use Quasar/Vue+amcharts4 this would help, I guess.

However, these bundles are now being forcefully prefetched even when I dont import any export related functionality. I'm investigating on that now - however, that falls on Quasar and not on amcharts.
