### ISSUE TITLE
Value Axis label position - question

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#2165]
Hy, 
given the pen bellow: https://codepen.io/aniov/pen/oNXBwqg?editors=0010
How can I set xAxis labels to display only series values, and also the grid moved as well?
Like this:
![image](https://user-images.githubusercontent.com/21243081/75169463-48865a80-5731-11ea-997a-a0525008fe11.png)

Thank you in advance.

**Comment by xorspark** [comment]
Your best bet is to disable the axis' generated labels/grids and [create guides using axis ranges](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Creating_a_guide) from your data:

```
xAxis.renderer.labels.template.disabled = true;
xAxis.renderer.grid.template.disabled = true;
// ...
chart.data.forEach(function(dataItem) {
  var range = xAxis.axisRanges.create();
  range.value = dataItem.x;
  range.label.text = dataItem.x;
})
```

[Updated codepen](https://codepen.io/team/amcharts/pen/45775ea839d699140bb9978b026f8cdf?editors=0010)

**Comment by aniov** [comment]
Thank you for you answer. I was going to do that but I thought there is some easier way already implemented.
Thank you.
