### ISSUE TITLE
Venn diagram JSON config error

### ISSUE THREAD

**Issue by Ardillen66** [amcharts/amcharts4#2166]
It seems that the new Venn diagram support #1088 feature does not work with JSON config.

[This codepen](https://codepen.io/Ardillen/pen/yLNgoEB) illustrates the issue. It implements the [complete example](https://www.amcharts.com/docs/v4/chart-types/venn/#Complete_example) from the documentation.

When I try to initialize the chart, I get "u is undefined".

On a sidenote, the JSON config version of the example uses "am4plugins_vennd.VennDiagram" for the chart type. It should be "am4plugins_venn.VennDiagram".

Thanks in advance

**Comment by martynasma** [comment]
Thanks for the heads up.

Seems like there's a mistake in JSON config in that doc ("category" data field is replaced with "name").

Should be like this:

```
    "dataFields": {
      "value": "value",
      "category": "name",
      "intersections": "sets"
    }
```

The doc is now corrected.

Sorry for the inconvenience.

**Comment by Ardillen66** [comment]
This was indeed the issue. Thanks for the quick response.
