### ISSUE TITLE
Getting chart data using this.http.get(url)

### ISSUE THREAD

**Issue by Meenal-Sharma** [amcharts/amcharts4#2167]
@martynasma 
How to get the chart data using this.http.get(url) and parsing it via CSV Parser?

**Comment by martynasma** [comment]
If you need to parse CSV data loaded by some other tool using amCharts parser, you can just instantiate a `CSVParser` object and use it for parsing:

```
var parser = new am4core.CSVParser();
parser.options.delimiter = ",";
parser.options.useColumnNames = true;
var data = parser.parse(csv);
```
