### ISSUE TITLE
Angular RouteReuseStrategy Issue

### ISSUE THREAD

**Issue by temp69** [amcharts/amcharts4#2168]
### Implementing a custom RouteReuseStrategy destroys the responsivness of AmChart!

Since component's are destroyed once you leave a route and due to some heavy lifting of data queries inside of those components I implemented a custom RouteReuseStrategy. 
With doing so the visited components on those routes are stored and retrieved. This will speed up the application when changing routes in general and makes downloading data from services inside of components redundant.

[StackBlitz Example](https://stackblitz.com/edit/angular-router-basic-example-rtp2ol)

**How to reproduce:**

1. Open the stackblitz example
2. Resize the HTML view to see the responsivness from the chart, getting bigger & smaller.
3. Change the route to "User" -> The "Home" route will get stored.
4. Change back to the "Home" route
5. Try to resize the HTML view again.

Comment below code in **app.routing.module.ts** to disable the RouteReuseStrategy and everything works again.

```
        ///// UN- & COMMENT HERE TO SEE PROBLEM /////
        {
            provide: RouteReuseStrategy,
            useClass: CustomReuseStrategyForUserDashboard
        }
        /////////////////////////////////////////////
```

No idea if anything can be done on AmChart side, since the whole RouteReuseStrategy is more then user un-friendly and lacks quite some functions still. Also if anyone has suggestions or a better approach on how I could store components when revisiting (routing) is appreciated.

**Comment by martynasma** [comment]
Just to make sure "change route" means clicking on the Home > User links on top?

If that is so, the chart remains resizable no matter how many times I go back and forth those links.

**Comment by temp69** [comment]
Thank you for your reply @martynasma .

Like in the GIF animation you can see right after the innitial loading of the page the chart shrinks and expanse. Once i change the route from Home -> User, i store the component and restore it once i go back from User -> Home.
Once you try to resize the HTML you can notice that the chart does not change its size anymore, aka it lost it's responsivness.

![amChartResponsive](https://user-images.githubusercontent.com/36497576/76139167-27d1d500-604e-11ea-9d5c-be35a0c613b0.gif)

**Comment by martynasma** [comment]
@temp69 Sorry for the long radio silence.

Since Angular messes with DOM structure, our resize sensor gets knocked off the track when routing occurs.

Resetting should fix it:

```
chart.svgContainer.resizeSensor.reset();
```

Hope this helps.

**Comment by martynasma** [comment]
Please disregard my last post. We're getting rid of the `resizeSensor` in new version altogether in favor of other solution.

I'll notify you here when new version is available.

**Comment by martynasma** [comment]
Fixed in [4.9.19](https://github.com/amcharts/amcharts4/releases/tag/4.9.19).

## [4.9.19] - 2020-04-30

### Added
- Export: Two new PDF export options added: `font` and `extraFonts` which enable specifying non-default font to use when exporting PDF. [More info](https://www.amcharts.com/docs/v4/concepts/exporting/#PDF_and_non_Latin_languages).

### Changed
- Third party resize sensor replaced with a home-brewed, which is faster and more reliable.
- `svgContainer.resizeSensor` replaced with a dummy object. Make sure you remove all references to it in your code. Calling it's `reset()` method will now generate a warning in console.

### Fixed
- Inline text formatting blocks now accept quote-enclosed values, e.g. `[font-family: 'Segoe UI']`.
- Fills for columns in `RadarColumnSeries` were black (since last release).
- With Chrome 81 disposing the chart in with DevTools open was very slow.
- Performance optimizations when showing/hiding series with a lot of data.
- Tooltip was flickering at 0,0 position if animated theme was not enabled.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by temp69** [comment]
Hi  @martynasma 

Thank you for your responds.
I can let you know that this responsive issue is now solved but a new one appeared with switching to your own implementation.

I am overriding the default responsive settings with this custom one.

```
      ////// RESPONSIVE SETTINGS ////////////////////////
      chart.responsive.useDefault = false;
      chart.responsive.enabled = true;
      chart.responsive.rules.push({
        relevant: function (target) {
          if (target.pixelWidth <= 450) {
            return true;
          }
          return false;
        },
        state: function (target, stateId) {
          if (target instanceof am4charts.AxisRendererY) {
            const state = target.states.create(stateId);
            state.properties.disabled = true;
            return state;
          }
          if (target instanceof am4charts.Legend) {
            const state = target.states.create(stateId);
            state.properties.layout = 'vertical';
            state.properties.contentAlign = 'center';
            return state;
          }
          return null;
        }
      });
      //////////////////////////////////////////////////
```

Validating the responsivness in chrome browser on my windows machine works flawless. Even after changing the size or actually toggeling the device to a phone it accuratly loads them.

But loading the site on my phone (Pixel 3, unrooted, latest patch), it starts rendering the chart layout correct with the Y-axis labels disabled and the legend items aligned vertically like stated in the responsive settings.
Yet right after the chart data has finished loading, the chart itself (XYChart) is drawn and it ignores the responsive settings altogether, the Y-axis labels are back and the legend aligned wrong.

I can get the responsive settings re-enabled when changing the orientation on the phone first to horizontal and then back to vertical, but the innitial load of the chart is not working as stated.
Also when i call `this.chart.invalidateRawData();` on the chart the correct responsive settings kick back in.

**Comment by temp69** [comment]
@martynasma 
If you want, you can close this one and I will create a new with the new flaw.
