### ISSUE TITLE
Smoothed line with automatic tension?

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#2169]
Is there anything like automatic tension considering the distances between data points?
(was the same "problem" in amcharts 3)

In a date based chart where the data points are not equidistant a line chart with tension has some funny but unwanted curves (going backwards in time).

https://codepen.io/chrisadler/pen/eYNgPYz

![image](https://user-images.githubusercontent.com/58069494/75216904-db58e080-5795-11ea-8cab-4c904cb59750.png)

**Comment by martynasma** [comment]
I'm afraid smoothing algorithm does not work well with data items spaced erratically.

I can suggest using higher `tensionX` values.
