### ISSUE TITLE
ColumnSeries always in center

### ISSUE THREAD

**Issue by aikodeio** [amcharts/amcharts4#2171]
hello, I have a graphic which I would like the columns to always show in the center, independent if there are others that are hidden.

**Code**: **https://codepen.io/aikodeio/pen/XWbpwpM**

**Example #1:**
![Sin título-1](https://user-images.githubusercontent.com/47112604/75250091-53370300-57b6-11ea-8f04-46e84e102cdc.jpg)

**Expected result #1:** 
![Sin título-2](https://user-images.githubusercontent.com/47112604/75250988-6e0a7700-57b8-11ea-8df8-dff4eb9deab8.jpg)

**Example #2:**
![Sin título-4](https://user-images.githubusercontent.com/47112604/75251009-795da280-57b8-11ea-9acc-9314ae3008a4.jpg)

**Expected result #2:** 
![Sin título-3](https://user-images.githubusercontent.com/47112604/75251026-84b0ce00-57b8-11ea-996b-5d1984cb15d6.jpg)

**Comment by zeroin** [comment]
I made a demo, based on yours:
https://codepen.io/team/amcharts/pen/rNVywzK

I stripped it so that we could use it in our demos, as it's indeed a nice feature.

**Comment by aikodeio** [comment]
@zeroin  Excellent! It is what I needed. Thank you very much: D
