### ISSUE TITLE
World map using AmCharts 4 very long to load only on Android Phones + Chrome browser

### ISSUE THREAD

**Issue by jmd-sinartis** [amcharts/amcharts4#2173]
We experience performance problems with loading a world map using AmCharts 4 (see attached code) on Android with some browsers (Chrome). 

Step to reproduce:
1. You need to be using a real Android smartphone
2. Open Chrome browser
3. Go to this page http://www.opendoors.ch/index
4. The map takes up to 20 - 30 seconds until it loads

This issue only appears on Android smartphone and if you use iphone + chrome, we don't have the issue.

Has anyone experienced similar issues have a suggestion for resolving it?

**Comment by xorspark** [comment]
Your map is using AmCharts 3, not AmCharts 4. Also worldMapHigh has more details at the cost of performance, so it will load slower as a result. Consider switching to worldMapLow if you don't need the extra detail.
