### ISSUE TITLE
SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by ivy-man** [amcharts/amcharts4#2174]
I've installed the package with npm.
After adding scripts to my HTML page, I get this error in the browser :

SyntaxError: export declarations may only appear at top level of a module

This is how I use the package‌:
<script src="node_modules/@amcharts/amcharts4/core.js"></script>
<script src="node_modules/@amcharts/amcharts4/charts.js"></script>
<script src="node_modules/@amcharts/amcharts4/themes/animated.js"></script>

**Comment by martynasma** [comment]
Those are ES2015 modules that need to be imported into your app, not plain JavaScript. So if you are planning on including them via `<script>` tag, you should use JavaScript version.

It is available via download of a ZIP file, or online as CDN:
https://www.amcharts.com/download/

**Comment by ivy-man** [comment]
Thank you very much.
it's done.
