### ISSUE TITLE
can u help me out for radar chart 

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#2175]
for every country series need to show score value unable to map properties

[{CountryName: "China",
Price: "3.0",
provide_FOB_Score: "4.0",
Tariff_Advantage_Score: "2",
Sustainability_Score: "2.5",
Production_Quality_Score: "4.5",
efficiency_Score: "3.0"
},
{CountryName: "India",
Price: "3.0",
provide_FOB_Score: "4.0",
Tariff_Advantage_Score: "2",
Sustainability_Score: "2.5",
Production_Quality_Score: "4.5",
efficiency_Score: "3.0"
},{CountryName: "Bangaladesh",
Price: "3.0",
provide_FOB_Score: "4.0",
Tariff_Advantage_Score: "2",
Sustainability_Score: "2.5",
Production_Quality_Score: "4.5",
efficiency_Score: "3.0"
},{CountryName: "Aus",
Price: "3.0",
provide_FOB_Score: "4.0",
Tariff_Advantage_Score: "2",
Sustainability_Score: "2.5",
Production_Quality_Score: "4.5",
efficiency_Score: "3.0"
}]

**Comment by martynasma** [comment]
Data like that won't work. You'll need to convert the data to a format suitable for `RadarChart` series.

You can do so with a custom function. Or use `beforedatavalidated` event to reformat data before it is parsed by chart.

```
chart.events.on("beforedatavalidated", function(ev) {
  // custom code that modifies chart.data
  // ...
});
```
