### ISSUE TITLE
Chart Event not rendering properly

### ISSUE THREAD

**Issue by Meenal-Sharma** [amcharts/amcharts4#2176]
@martynasma 
   I want my chart to pre-zoom like this by giving an event, but sometimes it is pre-zooming to given date values and sometimes not.
     chart.events.onAll(function () {
        let max = dateAxis.groupMax["day1"];
        let date = new Date(max);
        am4core.time.add(date, "month", -1);
        zoomToDates(date);
      });

**Comment by martynasma** [comment]
I'm not sure what your custom function `zoomToDates` does, but I'm presuming it zooms actual chart in some way. Which means that it generates a bunch of events, that are in turn caught back by `onAll()`, resulting in dead loop.

I strongly suggest not using generic `onAll()` but rather specific event, like "ready":

```
chart.events.on("ready", function () {
  ....
});
```

P.S. I'm flattered you single me out of all amCharts tea by adding my username at the top of all your issues. Just want to let you know that this in no way results in personal notifications, or faster response times ;)

**Comment by Meenal-Sharma** [comment]
I tried it on ready event also. But It didn't worked out. 
zoomToDates function can be seen here - https://www.amcharts.com/demos/stock-chart/

**Comment by martynasma** [comment]
Can you post your full chart on CodePen?
