### ISSUE TITLE
Change whole data with animation

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2177]
How change whole data with animation?
in v4 not animated:
https://codepen.io/team/amcharts/pen/XOPoMN
but in v3 with ```animateData```:
https://codepen.io/team/amcharts/pen/e5b7e755ec85b282612c7d60d25b97fa

**Comment by zeroin** [comment]
To animate from one data to another, you should change values in the original data array (but not hte array itself) and then call `chart.invalidateRawData();`
