### ISSUE TITLE
[Question] Is there a way to freeze display while updating the chart ?

### ISSUE THREAD

**Issue by IkamThorek** [amcharts/amcharts4#2178]
Sometimes I need to modify several items (some series and ranges) at the same time. However, for better user experience, I would like to have the chart render only once all changes have been finished. 

Is there a way to freeze the chart while updating and display the changes only once everything is done ?

**Comment by martynasma** [comment]
Well, since charts are completely asynchronous, you can make multiple changes and it will update only once.

However, if your updates are also asynchronous, there's a way to freeze everything:

```
am4core.system.isPaused = true;
```

To unfreeze:

```
am4core.system.isPaused = false;
```

**Comment by IkamThorek** [comment]
It seems like what I am looking for, however it doesn't work as I would have expected. Here is a link  that shows what happens : https://s27.aconvert.com/convert/p3r68-cdx67/r1v2f-yahru.gif

**Comment by martynasma** [comment]
The link seems to be broken.

**Comment by IkamThorek** [comment]
![amcharts_paused_bug](https://user-images.githubusercontent.com/60658002/75430685-fa996e80-594b-11ea-93fe-94c2f8299fba.gif)

**Comment by martynasma** [comment]
Thanks. It's still hard to understand what's going on there.

Any chance you could post it as a live chart somehwere?

**Comment by IkamThorek** [comment]
Alright I got it, it works as expected, I just forgot that I had 2 independent charts in independent components that ran the exact same code, but with different data. What created the above gif is that the other chart rendered sooner, thus setting am4core.system.Paused to false, enabling changes for the slower chart. Now I know what I have to do. Thanks a lot !

For your information, what I was doing is similar to this : https://stackblitz.com/edit/typescript-y75kht

**Comment by IkamThorek** [comment]
Is there a way to pause only for a single chart ?

**Comment by martynasma** [comment]
> Is there a way to pause only for a single chart ?

Nope :(

**Comment by IkamThorek** [comment]
Ok, I'll manage with some component synchronization. Thanks for the help.

(I edited the stackblitz so that you can see what happened.)
