### ISSUE TITLE
Updating chart with invalidateRawData (angular)

### ISSUE THREAD

**Issue by mcverticchio** [amcharts/amcharts4#2179]
Hi there, 

I followed your tutorial on how to integrate amcharts with Angular.  My question is about updating pieces of data.  I have a simple example below, where after setTimeout i am changing an existing name and calling invalidateRawData.  I see the underlying data changing (chart.data), but do not see it reflected in the UI until I click within the chart.  Is there a different way I should be doing this so that changes are reflected on screen? 

`
export class MyComponent {
    private chart: am4charts.Chart;

    constructor( private zone: NgZone ) {};

    ngAfterViewInit() {
        this.zone.runOutsideAngular(() => {
            let chart = am4core.create("chartdiv", am4plugins_forceDirected.ForceDirectedTree);
            chart.Data = [{
                name: "Main Bubble",
                value: 8,
                children: [{
                    name: "Child Bubble 1",
                    value: 4
                }, {
                    name: "Child Bubble 2",
                    value: 4
                }]
            }];

            let series = chart.series.push(new am4plugins_forceDirected.ForceDirectedSeries());

            series.dataFields.value = "value";
            series.dataFields.name = "name";
            series.dataFields.children = "children";
            series.nodes.label.text = "{name}";

            this.chart = chart;

            this.update();
            
        })

    }

    update() {
        const self = this;
        setTimeout(function() {
              self.chart.data[0].name = "Main Bubble New Title";
              self.chart.invalidateRawData();
        }, 3000);
    }
}
`

Thank you!

**Comment by martynasma** [comment]
`invalidateRawData()` is meant to animate numeric values from current to new ones. It won't affect any other values, like strings.

In this case you should use `invalidateData()`. There's no way to morph one string into another anyway ;)

**Comment by mcverticchio** [comment]
Ah I missed that in the docs.  Thanks.
