### ISSUE TITLE
Map not rendering with Webpack production mode bundle

### ISSUE THREAD

**Issue by deemaxx** [amcharts/amcharts4#2181]
We recently updated amCharts4 from version `4.5.16` to `4.9.0` and amcharts4-geodata from `4.1.7` to `4.1.11`.

Prior the update, all charts and maps rendered as expected. Performance was not the best. So, we figured updating to the latest version may improve performance a bit. 

However, while all the charts and maps render just fine locally, using webpack's `development` mode, when creating a dist build for prod, the maps are not rendering. 

After hours of debugging, I found out that one of webpack's default settings in the `optimization `options, `usedExports: true`, prevents the map module from being bundled properly. The interesting part is there is no warning or error message during the build even when `noEmitOnErrors` is set false.

Once I change `usedExports` to false, the map renders again. 

Webpack's documentation for `usedExports` describes this feature as following:

> optimization.usedExports
boolean

> Tells webpack to determine used exports for each module. This depends on optimization.providedExports. Information collected by optimization.usedExports is used by other optimizations or code generation i.e. exports are not generated for unused exports, export names are mangled to single char identifiers when all usages are compatible. Dead code elimination in minimizers will benefit from this and can remove unused exports. 

It does say it is enabled in all modes, however that is incorrect based on their documentation on `mode` [https://webpack.js.org/configuration/mode/](url). It is, however, on by default when creating a prod build.

I have been trying to figure out what exactly changed in the `maps.js` file between version `4.5.16` and `4.9.0` of amCharts4 that would fail to bundle using the default configuration that webpack applies for `production` mode. 

I'd rather not have to set `usedExports` to false just for the maps module. 

We're using Vue as our front end framework. At the top of the script part in the Vue single file component we use the Map module is as follows:

```
<script>
  /** AmCharts */
  import * as am4core from '@amcharts/amcharts4/core'
  import * as am4charts from '@amcharts/amcharts4/charts'
  import * as am4maps from '@amcharts/amcharts4/maps'
  // eslint-disable-next-line camelcase
  import am4geodata_worldHigh from '@amcharts/amcharts4-geodata/worldHigh'
  
  // eslint-disable-next-line camelcase
  import am4themes_kochava from '@/modules/amcharts4/themes/kochava-amcharts4-theme'

  am4core.useTheme(am4themes_kochava)
  am4core.options.commercialLicense = true
```

We have not changed this between version updates of amCharts4. 

Any help is greatly appreciated.

**Comment by Pauan** [comment]
@deemaxx Sorry for the delay, and I really appreciate the very detailed report.

However, I haven't been able to reproduce this. I created a map chart with webpack 4.42.0 and the latest version of amcharts4, but it renders fine.

Could you try and get a reduced test case, which shows the smallest amount of code needed to cause the problem?
