### ISSUE TITLE
How to pre-zoom to 1 month instead of MAX in amcharts 4?

### ISSUE THREAD

**Issue by Meenal-Sharma** [amcharts/amcharts4#2182]
@martynasma 

https://www.amcharts.com/demos/stock-chart/
How to pre-zoom to 1 month instead of MAX in amcharts 4  above example?

**Comment by martynasma** [comment]
The following code would do it:

```
chart.events.on("ready", function() {
  var max = dateAxis.groupMax["day1"];
  var date = new Date(max);
  am4core.time.add(date, "month", -1);
  zoomToDates(date);
});
```

**Comment by samakhani** [comment]
where should I put this code? its doesn't working:(

**Comment by samakhani** [comment]
chart.events.on("datavalidated", function(ev) {
  selector.setPeriodInterval("ytd");
});
I test this and working it was on the document
