### ISSUE TITLE
group containing one data item issue  

### ISSUE THREAD

**Issue by dharam0034** [amcharts/amcharts4#2183]
Hi, 

When gouping is enabled on dateAxis and we zoom the chart enough till group size is 1 then there is an issue. 

For example: to get the last grouped data in series 

var lastdataItem = series.dataItems.getIndex(series.dataItems.length - 1);
var pointCount = lastdataItem.values.valueY.count //where pointCount  is group data count. 

Now, if we want to get the time of that last data point (when pointCount  is 1)
it should be as following: 
lastdataItemTime = Math.floor(lastdataItem.values.dateX.value)

But, it doesn't works: 

The return value (lastdataItemTime) is something else between range 
lastdataItem.values.dateX.open     and   lastdataItem.values.dateX.close

instead of actual value of date at that point. 

I hope that I explained enough. 

Thanks.

**Comment by martynasma** [comment]
Can you perhaps post an example of a chart like that?
