### ISSUE TITLE
LabelBullet click doesnt drill down in Tree Map

### ISSUE THREAD

**Issue by Zimmerr** [amcharts/amcharts4#2186]
When using LabelBullets in a drill down Tree Map, clicking in them doesnt activate the drill down event, only if you click outside of the label.

I tried to mess with the events in the LabelBullet and on the columns from the seriesTemplate, but couldn't find any success. I wanted to add a "hit" event on the LabelBullet that could trigger the "down" event on the column, but i didnt knew how to do it properly with the dispatch method

I dont know if this is intended, but i believe that it would be way better if we could trigger the drill down by clicking the labelBullet by default, but having a workaround available could already solve my problem

**Comment by xorspark** [comment]
You can set `interactionsEnabled` to false on the LabelBullet so that the underlying cell receives the click when the bullet is clicked, triggering the drilldown:

```
bullet.interactionsEnabled = false;
```

[Demo](https://codepen.io/team/amcharts/pen/e81b3eb610a9097ca6b4fe730824120e?editors=0010)
