### ISSUE TITLE
Last column series added to stacked column chart always renders a value

### ISSUE THREAD

**Issue by LeeWarner** [amcharts/amcharts4#2187]
[Link to codepen of modified example:](https://codepen.io/LeeWarner/pen/dyoWWvV?editable=true)

In my link above, for each of the years of data, I set the value to 0.  Depending on the last series added, it will still render in the chart (in this case Africa).

**Comment by martynasma** [comment]
Do you mean that there's a think line for Africa eve though its value is zero?

This is because of the outline on columns. Even though the column itself is zero-height, it still draws a border around it, hence it becoming visible.

You can disable column border like this:

```
series.columns.template.strokeWidth = 0;
```

**Comment by LeeWarner** [comment]
Thanks, that solved my issue.
