### ISSUE TITLE
No highlighting on legend hover if serie not active

### ISSUE THREAD

**Issue by DavidAuger** [amcharts/amcharts4#2190]
Hello guys,

I just saw your new demo "Highlighting line chart series on legend hover".
I developed myself quite a similar functionality few months ago and have exactly the same result as yours (using events and visual style effect).

I have a question though, is it possible to detect active state to avoid "hover effect style" when series is not active (not shown on chart). I mean, i think it's quite "strange" to hover a hidden / inactive series (resulting to dimming every series).

Is it possible to add a condition on a specific property to avoid dimming in that specific case ?
And if so, what property could i or we use ?

Thanks
Best regards

**Comment by martynasma** [comment]
I suppose you can check series' [`isHidden`](https://www.amcharts.com/docs/v4/reference/series/#isHidden_property) property.

**Comment by DavidAuger** [comment]
Thank you, it's works very well 👍

**Comment by DavidAuger** [comment]
So for the record and to help any one who would like to personalize the hovering effect, here is my code (completed after that by the good demo: https://www.amcharts.com/demos/highlighting-line-chart-series-on-legend-hover/)

`
/**
     * HOVER EFFECT TO DISPLAY SERIE ON CHART WITH A SMALL COLOR EFFECT
     */
    let timer;
    chart.legend.itemContainers.template.events.on("over", (ev) => {
      const serieSelected = chart.series.values.find(serie => serie.dataFields.valueY === ev.target.dataItem.dataContext['name']);

      // Check if serie in not hidden, avoiding applying dimming effect and not showing anything
      if (!serieSelected.isHidden) {
        timer = setTimeout(() => {
          chart.series.values.forEach(serie => {
            if (serie === serieSelected) {
              serie.strokeWidth = 2;
              serie.fill = serie.stroke;
              serie.fillOpacity = 0.1;
            } else {
              serie.strokeWidth = 0.2;
            }
          });
        }, 500);
      }
    }, this);

    chart.legend.itemContainers.template.events.on("out", (ev) => {
      clearTimeout(timer);

      chart.series.values.forEach(serie => {
        serie.strokeWidth = 1;
        serie.fillOpacity = 0;
        serie.strokeOpacity = 1;
      });
    }, this);
`
