### ISSUE TITLE
Update geodata!

### ISSUE THREAD

**Issue by Aissaoui-Ahmed** [amcharts/amcharts4#2191]
Hi amcharts!
fix a typo in filename for turkmenistant(Low|High) to turkmenistan
See : [script](https://github.com/amcharts/amcharts4-geodata/tree/master/dist/script) and  [es2015](https://github.com/amcharts/amcharts4-geodata/tree/master/dist/es2015)
Update KeyName into countries files `NAME` to `name`

**Comment by martynasma** [comment]
Thanks for the heads up! Will be fixed in the next version of geodata package.

**Comment by martynasma** [comment]
Just released geodata package. It fixes the issues you mentioned.
