### ISSUE TITLE
Epoch (Unix Timestamp or Timestamp ms) not working with CSVParser

### ISSUE THREAD

**Issue by rhaenni** [amcharts/amcharts4#2192]
Whenever I have a Unix Timestamp (or Timestamp in Milliseconds) in a .csv file that is parsed using ```chart.dataSource.parser = new am4core.CSVParser();``` amcharts fails to parse the timestamp into a proper date, no matter I specify ```chart.dataSource.parser.options.dateFormat = 'x'``` or not.

Result is that a unix timestamp like 1582939984 loaded from .csv is always interpreted as "Year 1582" and other wrong things.

**Comment by xorspark** [comment]
Adding the field containing your timestamp to the parser's `numberFields` array in addition to using the `'x'` format seems to make the timestamp get parsed correctly:

```
chart.dateFormatter.inputDateFormat = 'x'; //or chart.dataSource.parser.options.dateFormat = 'x';
// ...
chart.dataSource.parser.options.numberFields = ['timestamp'];
```

[Demo](https://codepen.io/team/amcharts/pen/dbe3a02b5c06053cfb2e72c302f8dccd?editors=0010)
