### ISSUE TITLE
[Question] GroupData: series change from LineSeries to StepLineSeries if data is not grouped

### ISSUE THREAD

**Issue by borodiliz** [amcharts/amcharts4#2193]
I'm using `GroupData` in conjunction with `LineSeries` and `StepLineSeries`. My goal is to dynamically represent:

* `LineSeries` when `amcharts` is grouping my data:

<img width="772" alt="Captura de pantalla 2020-03-01 a las 13 05 15" src="https://user-images.githubusercontent.com/2467193/75625322-65051580-5bbd-11ea-866d-33cd05983ead.png">

* `StepLineSeries` when `amcharts` is NOT grouping my data:

<img width="779" alt="Captura de pantalla 2020-03-01 a las 13 05 39" src="https://user-images.githubusercontent.com/2467193/75625323-67676f80-5bbd-11ea-9afd-738a3e5d169e.png">

Is there any way to achieve this automatically? 

Thanks in advance!

**Comment by martynasma** [comment]
No, I'm afraid, there's no way to switch series type on the fly. Sorry.

**Comment by borodiliz** [comment]
Thanks anyways and thanks for your quick reply
