### ISSUE TITLE
Tooltip not updated in live data chart

### ISSUE THREAD

**Issue by DavidAuger** [amcharts/amcharts4#2194]
Hello guys,

I am using XYChart with live data. I configured series tooltip (using tooltipText, colors fills, ...).
For this i used your documentation like 'Anatomy of an XY Chart' (https://www.amcharts.com/docs/v4/chart-types/xy-chart/).

Unfortunately, it appears that information are only updated on cursor movement. So, while my live data flow is running, if my cursor stayed in the exact same position, information are not running as well.
![image](https://user-images.githubusercontent.com/48203813/75660522-31cd8f80-5c6c-11ea-9606-874742218420.png)

Is it possible to solve this issue, either by adding an update in 'beforedatavalidated' event either by any other means possible ?

Thank you a lot for your help

**Comment by martynasma** [comment]
A method for such update will be implemented in the next version.

I'll let you know when it happens (probably within few days) as well as provide more details.

**Comment by DavidAuger** [comment]
Nice, it would be great !

**Comment by DavidAuger** [comment]
On m screenshot, we can see that some series seems not having a tooltip 'card'. Do you know why it is not shown ? (i can guarantee that there is some data for each series right where my cursor is)

If i could add something linked to those points, i also observed that property 'arrangeTooltips' seems to work fine in most cases but sometimes small tooltip 'cards' are overlapping (especially on my live data charts).
Is it due to small delay to let tooltip's view been initialized and rendered ?

**Comment by martynasma** [comment]
Let's keep one thing per issue. If you have a separate question/bug, please open a new issue.

**Comment by DavidAuger** [comment]
Your right, sorry i will open an other issue

**Comment by martynasma** [comment]
OK, so new version is out: 4.9.5.

You can now do this, to make cursor update its tooltips:

```
chart.cursor.triggerMove(chart.cursor.point, "none", true);
```

**Comment by DavidAuger** [comment]
Hello @martynasma ,

Thank you for your work and for your update.
Unfortunately, it doesn't change any thing on our application, the problem stays unresolved.
![image](https://user-images.githubusercontent.com/48203813/75900944-07cbc700-5e3e-11ea-8895-a4d736365fba.png)

Note that is our randomized dev data but still, we can see that tooltip is not well updated.

**Comment by martynasma** [comment]
Can you post your chart/data somewhere where we can test?

**Comment by DavidAuger** [comment]
I will try to share you an exemple you could test as soon as possible (i need to transform a bit my code due to it's integration in our application)

In the mean time, is there a function we could call to force update in event 'afterdatavalidated' or something like ? I know it would durty but...

**Comment by martynasma** [comment]
There's no special function, I'm afraid :(

This stuff should work:

```
chart.cursor.triggerMove(chart.cursor.point, "none", true);
```

Example:
https://codepen.io/team/amcharts/pen/05d7c3f001d3f95c5460b5bec0dbcb4d?editors=0010

**Comment by DavidAuger** [comment]
> This stuff should work:
> 
> ```
> chart.cursor.triggerMove(chart.cursor.point, "none", true);
> ```
> 
> Example:
> https://codepen.io/team/amcharts/pen/05d7c3f001d3f95c5460b5bec0dbcb4d?editors=0010

Yes indeed, it works !! When you firstly give me this trick few days ago, i was not using it well (i didn't understood that it has to be in the validated event).

Last point, the xAxis tooltipDate is not updated. Is there a similar way to do it ?

**Comment by martynasma** [comment]
Um... what is "xAxis tooltipDate"? :)

**Comment by DavidAuger** [comment]
Umm... indeed that wasn't clear :)
We are using this:
```
var xAxis = chart.xAxes.push(new am4charts.DateAxis());
xAxis.baseInterval = {
    "timeUnit": "millisecond",
    "count": 1
};
xAxis.tooltipDateFormat = "HH:mm:ss";
```
Using this property to format tootltip axis (in black on my screenshot):
https://www.amcharts.com/docs/v4/reference/dateaxis/#tooltipDateFormat_property

**Comment by martynasma** [comment]
Still not following. Do you mean that `tooltipDateFormat` is being ignored?

**Comment by DavidAuger** [comment]
No it's working fine, ```tooltipDateFormat``` is working as i configured it (```"HH:mm:ss"``` format).

I will try to sum it up:
At the beginning, we had a global problem of refresh on live data chart. If the mouse cursor was not moving, chart's tooltip was not updating, meaning that small colored series cards stayed in position with old values and xAxis' tooltip (the one in black displaying time in format ```"HH:mm:ss"```) was not updated neither.

Now, with code changes and all your explanations, small series cards are working perfectly well. But still, xAxis' tooltip seems to "freeze" on the time where mouse cursor stopped. On my 2nd screenshot, you can see that xAxis tooltip is displaying "17:06:56" but it should display "17:07:37" as we could see that cursor is now after 17:07.
On my first screenshot, you can see that it's displaying "09:53:01" but it should be "09:54:01" according to position on chart.

Is there a way to update it as ```chart.cursor.triggerMove(chart.cursor.point, "none", true);``` but to update this xAxis' tooltip ?

**Comment by martynasma** [comment]
Gotcha. Sorry I should have caught that. We'll probably need to fix that in the code.

Will keep you posted.

**Comment by martynasma** [comment]
OK, so I can's seem to be able to reproduce this. Here's what I have:
https://codepen.io/team/amcharts/pen/8502c667e1072430a275060dbbc5fcce?editors=0010

Is the tooltip stuck or is it being updated for you on that demo?

**Comment by DavidAuger** [comment]
Sorry for the long update !
On the demo, i can see the tooltip is updated.
I will see if i can fix my code or update your demo with mine to get the same state.
