### ISSUE TITLE
How do I update a single column without re-rendering the chart?

### ISSUE THREAD

**Issue by sopsick** [amcharts/amcharts4#2197]
I have an XYChart with a column series and a template adapter for 'fill' that colors the bars based upon information in the data context. When I change the values in the data context I want to update just the column affected by the change (i.e., redraw the column with the new color). If I do a `chart.invalidateData` it works, but any vertical zooming that the user has done gets reset due to the update. Is there a way to get a single column to re-render without updating the entire chart?

Thanks

**Comment by martynasma** [comment]
How about changing `fill` of the affected column directly?

```
chart.data[1].color = am4core.color("blue");
series.columns.getIndex(1).fill = am4core.color("blue");
```

**Comment by sopsick** [comment]
That works. I guess I misunderstood. I thought the template adaptor was doing that calculation when the data context changed. 

Thanks

**Comment by martynasma** [comment]
Well, adapters do not kick in out of the blue. You need to trigger them by invalidating data, or particular object. I did the latter.

There's one other option for you to consider: `keepSelection` setting on `ValueAxis`. If set to `true`, it should preserve the current zoom across data updates, even if you call `invalidateData()`.
