### ISSUE TITLE
DateAxis label positions get distorted on resize

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#220]
Labels are usually OK, on first load.

Then when the chart is resized so that some labels are omitted, and resized back, some labels are out of place:

![chrome_2018-08-10_18-01-59](https://user-images.githubusercontent.com/1458520/43965311-974a43be-9cc7-11e8-8f85-490ede43f487.png)
![chrome_2018-08-10_18-02-35](https://user-images.githubusercontent.com/1458520/43965318-9ac32664-9cc7-11e8-8b7a-8714bf17fbac.png)
![chrome_2018-08-10_18-02-23](https://user-images.githubusercontent.com/1458520/43965320-9cd2fd26-9cc7-11e8-8a59-e6d901f1c3c2.png)

Example:
https://codepen.io/team/amcharts/pen/d8bba223c157c311950940e9b8b8b9f1/

**Comment by zeroin** [comment]
reproduced in codepen only, looks like the problem with legend labels, does not happen with default fonts or outside codepen.

**Comment by martynasma** [comment]
Shelving this until we find a way to reproduce outside CodePen.
