### ISSUE TITLE
[Question] Setting language.locale doesn't seem to work from @amcharts/amcharts4/lang/

### ISSUE THREAD

**Issue by IkamThorek** [amcharts/amcharts4#2201]
Here is a [stackblitz](https://stackblitz.com/edit/typescript-t2jztl)

Right after I create a chart, I set its language.locale to the imported language. However, the chart doesn't seem to use it, even though the elements have inherited the language.

**Comment by martynasma** [comment]
You're not importing the locale right. The following should work:

```
import am4lang_fr_FR from "@amcharts/amcharts4/lang/fr_FR";
```

**Comment by IkamThorek** [comment]
Thanks, it works partially.

![image](https://user-images.githubusercontent.com/60658002/75859016-8eaa8080-5df9-11ea-9dbe-8e0d96677ee6.png)

**Comment by IkamThorek** [comment]
Nevermind. 

What happened is that I set **chart.scrollbarX.parent** so that I could have more control over its position. When I set it, the scrollbarX lost the inherited locale. 

To fix it, I just had to set **chart.scrollbarX.language.locale** AFTER changing the parent component.
