### ISSUE TITLE
Question: Difference series vs chart regarding data property

### ISSUE THREAD

**Issue by Legends** [amcharts/amcharts4#2202]
I can do the following:

```
 let { series, chart } = await CreateBubbleChart();
chart.data = getData();
```
**or** 

`series.data = getData();`

Both show/display the bubble chart. Any difference here?

**Comment by martynasma** [comment]
It depends on your chart and data setup.

If you have multiple series and different data sets to plot on them, then it makes sense to use series' `data`, as consolidating them into a single array would be quite an overhead.

That said, having data for each series is slower, so if there's a lot of data items, it would be wise to use just a single data set.

Also, if you have CategoryAxis, setting data directly on series would mean that axis does not have any categories, so you would need to set category data on axis.data as well. So again, having one data set is more convenient.
