### ISSUE TITLE
amCharts Export is not working  (all chart)

### ISSUE THREAD

**Issue by hshahul** [amcharts/amcharts4#2205]
I am facing export network failure issue in all my charts. sometimes it download image is working fine, most of the time i am getting ""Export operation took longer than expected. Something might have gone wrong" error or network failure error only..

I tried to add milliseconds also but no luck..

Can you provide any good solution for this

**Comment by martynasma** [comment]
Do you have any errors displaying in browser console?

**Comment by hshahul** [comment]
No error logs... "Network failure" in that downloaded image

**Comment by martynasma** [comment]
We'll need some way to reproduce this. If you can provide a link to online chart, or post it on CodePen that would be great.

**Comment by hshahul** [comment]
I am using same example code only, nothing specific. only different is data, am getting from Qlik sense.

**Comment by martynasma** [comment]
I'm sorry but we can't troubleshoot issues with theoretical setups.
