### ISSUE TITLE
How do I stick a tooltip to the top of the chart?

### ISSUE THREAD

**Issue by floklein** [amcharts/amcharts4#2206]
Hi!

I have been following [this tutorial](https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/) to join all my series tooltips into a single tooltip.
But instead of having the tooltip on only one of the series, or on each one and hiding the others with `chart.cursor.maxTooltipDistance = 0`, I'd like to stick it to the top of the chart (like "y = 0"), with it still following the cursor ("x = cursorX").

I tried to use the chart tooltip and a `cursorpositionchanged` event, without success. While the event is fired on every cursor move, the tooltip position doesn't follow.
```
chart.plotContainer.tooltipPosition = 'fixed';
chart.plotContainer.tooltipText = 'test';
chart.plotContainer.tooltipY = 0;
chart.cursor.events.on('cursorpositionchanged', e => {
    chart.plotContainer.tooltipX = Math.floor(e.target.point.x);
});
```

**Comment by martynasma** [comment]
Probably easiest way to do is to override tooltip `y` with an adapter:

```
series.tooltip.adapter.add("y", function(y, target) {
  return chart.paddingTop;
});
```

**Comment by floklein** [comment]
Works great! Thanks a lot!

**Comment by floklein** [comment]
I have one more question:
When a series gets close to an axis, the tooltip still keeps moving a bit up or down not to overlap the axis. So I tried `tooltip.dy = 0` or even `tooltip.adapter.add('dy', () => 0)`, but failed.

**Comment by martynasma** [comment]
Perhaps you can use tooltips [`pointerOrientation`](https://www.amcharts.com/docs/v4/reference/tooltip/#pointerOrientation_property)?

**Comment by floklein** [comment]
Not working with `pointerOrientation` set to `'horizontal'`, `'left'` or `'right'`.
![tooltip bug](https://user-images.githubusercontent.com/4128942/76226981-e5abbd80-621e-11ea-9d3a-1a153cc98225.gif)

**Comment by martynasma** [comment]
Can you post your chart online somewhere, e.g. CodePen?

**Comment by floklein** [comment]
https://stackblitz.com/edit/react-7dfu3f

**Comment by zeroin** [comment]
Sorry for the long wait. It's quite impossible to work on this stackblitz, the things keep crashing. So I made a similar case in codepen:
https://codepen.io/team/amcharts/pen/5dd61245198db6ae7f329d2a75b4f7c1?editable=true

The trick is to set bounds for the tooltip which would be bigger than the chart area. As by default, the chart tries to fit the tooltip to the plot area, shift's it's y and so the jumping happens.

**Comment by floklein** [comment]
Thanks for answering! Exactly what I needed, perfect!
