### ISSUE TITLE
CategoryAxis tooltipHTML Problems

### ISSUE THREAD

**Issue by jeadly** [amcharts/amcharts4#2209]
I'm debugging a project that uses CategoryAxis ToolTips to display a block of info to the left when the user hovers over the chart category. It works well except for two issues:

1. the very first hover after page load shows the tooltipText value, not the tooltipHTML block.
![badTip](https://user-images.githubusercontent.com/6715857/75999452-398d6e00-5ed0-11ea-897f-f52f2d11786a.png)If you mouse over another record and back it realizes it should be showing the HTML.
![goodTip](https://user-images.githubusercontent.com/6715857/75999478-44480300-5ed0-11ea-9e4f-5f98d2927cf3.png)

2. the tooltip content shows info for the last axis dataitem, not the hovered label. I'm not super clear on why the labels show axis tooltips when the tooltipHTML value is defined, but they need to have the right info if they do.
![wrongTip](https://user-images.githubusercontent.com/6715857/75999569-680b4900-5ed0-11ea-9c2f-2b6339331aac.png)
(hovering over the "Kent" label after the "Sussex" axis row)

I've set up a simplified example here with some audience participation Q&A property setting on JS line 179:
https://codepen.io/jeadly/pen/vYOejWw

I appreciate any input you can provide!

**Comment by jeadly** [comment]
There seems to be a substantive difference between:

[categoryAxis.tooltipHTML](https://www.amcharts.com/docs/v4/reference/categoryaxis/#tooltipHTML_property)
VS
[categoryAxis.tooltip.html](https://www.amcharts.com/docs/v4/reference/tooltip/#html_property)

Which I hadn't expected.  Seems like everything works as expected when the latter is set instead. Shows html content immediately and no tooltip over axis labels.

**Comment by martynasma** [comment]
Are you all set then, or is there something else you need help with? :)

**Comment by jeadly** [comment]
I guess I'm all set, thanks. All it takes is asking for help to stumble on a fix. Do you know if that's the expected behavior of categoryAxis.tooltipHTML? Or should we expect it to behave differently in future versions?

**Comment by martynasma** [comment]
We're not planning on changing anything there.
