### ISSUE TITLE
Date Axis Incorrect Grid Offset

### ISSUE THREAD

**Issue by jawaff** [amcharts/amcharts4#2210]
To sum it up, the DateAxis grid lines seem to be incorrectly offset. In other words, the actual points in the graph aren't lining up with the grid lines as I'd expect them to.

[Here is an example showing the problem.](https://codepen.io/jawaff/pen/abzxwbB) I reused a chart and just added some values. All of the values in the graph with the value, 3, have a date that should place the point on one of the DateAxis' grid lines. The first point with the value of 3 has a date of 2:20/10:20 (depending on the timezone). However, the problem is that the grid line for 2:20/10:20 isn't lining up with that point. The second point with the value of 3 has a date of 2:30/10:30, but also isn't lining up with the DateAxis' grid line.

**Comment by martynasma** [comment]
The grid lines are placed on the exact timestamp, on the minute. Whereas the data item is centered withing the cell. This is default behavior.

You can move grid lines to the middle as well:

```
dateAxisA.renderer.grid.template.location = 0.5;
dateAxisA.renderer.labels.template.location = 0.5;
```

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_location_

Or you can move actual data items to the start of the minute:

```
seriesA.dataItems.template.locations.dateX = 0;
```

https://www.amcharts.com/docs/v4/concepts/series/#Data_item_locations

Your call.

**Comment by JacobDeuchert** [comment]
Works like a charm!

The only problem i now have is the tooltip of the DateAxis not having the same location as the data.
There is probably an easy solution but i am not able to find it.

![image](https://user-images.githubusercontent.com/43518397/76293597-a37f8c00-62b1-11ea-9ec0-05544be19948.png)

You can reproduce this by addind a standard XYCursor to one of your tutorial [Codepen](https://codepen.io/team/amcharts/pen/RwwMJYr)

**Comment by martynasma** [comment]
Yup:

```
dateAxis.renderer.tooltipLocation = 0;
```

**Comment by jawaff** [comment]
@martynasma Thanks, that clears things up for me.
