### ISSUE TITLE
Setting dateFormat in axis doesn't apply to every label

### ISSUE THREAD

**Issue by IkamThorek** [amcharts/amcharts4#2211]
I used the following to display my labels as "S 1", "S 2", ...

**Comment by IkamThorek** [comment]
`abscissaAxis.dateFormats.setKey("week", "'S' w");`

However, it is displayed as 
![image](https://user-images.githubusercontent.com/60658002/76091301-99ae0e00-5fbd-11ea-89b8-0e2e81b3eb63.png)


As you can see, one of the labels didn't get the format I set before. It is not necessarily the one in the middle, it happens quite randomly (I only did a few attemps). 

My data is the following : 
```
{
    "date": 1558656000000, 
    "series1": 6833.2064566667, 
    "series2": 6653.1487443357,
     "series3": 180.057712331
},
{
    "date": 1559260800000, 
    "series1": 6753.6188766667,
     "series2": 6613.520333083, 
    "series3": 140.0985435837
},
{
    "date": 1559865600000,
     "series1": 6024.9066361111, 
    "series2": 5847.1576695704, 
    "series3": 177.7489665408
},
{
    "date": 1560470400000, 
    "series1": 6339.667208889, 
    "series2": 6169.0016951406,
     "series3": 170.6655137484
},
{
    "date": 1561075200000, 
    "series1": 5153.2269799996,
     "series2": 4858.5778982019, 
    "series3": 294.6490817977
}
```


Do you have any idea why it happens ?

PS : I sent this in 2 posts because I didn't know about the Ctrl + Enter shortcut, my apologies

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Period_change_format

**Comment by IkamThorek** [comment]
I should have found that. Thanks and sorry for wasting your time.
