### ISSUE TITLE
How to define minimum zoom on XYChart init?

### ISSUE THREAD

**Issue by Sebastp** [amcharts/amcharts4#2212]

**Comment by martynasma** [comment]
If you need an answer you'll need to provide a more thorough description of what you want to achieve, rather than having us guess ;)

**Comment by Sebastp** [comment]
Sorry.
I want to see 2.5 on value axis and 10 on dateAxis(I'm working with seconds and milliseconds) even when there is no data, and when I add any data I want zoom to be in the same place until the data is withing visible labels on axises

**Comment by Sebastp** [comment]
Eg. here https://bit.ly/3cLDwx8
I don't know if they used this package but I want to see a few levels on two axes even when chart.data is empty.

**Comment by martynasma** [comment]
You can use `min` and `max` properties on axis to fix the scale.

It works on `DateAxis` as well, you just need to use timestamps for `min` and `max`.

**Comment by Sebastp** [comment]
> You can use `min` and `max` properties on axis to fix the scale.
> 
> It works on `DateAxis` as well, you just need to use timestamps for `min` and `max`.

Yeah but if I do that the chart won't scale out when y value is more then 2 like on the example I've sent you.
Also how to set min/max on DateAxis when I use milliseconds? I don't set data values with new Data(...), just ints

**Comment by martynasma** [comment]
Just use milliseconds on DateAxis' `min` and `max`.

**Comment by Sebastp** [comment]
For anyone with the same problem;
Instead of adding min/max to axes, I added another series(S2) with initial data of 2 points of the chart;
``` 
[
  {value: {minimum value you want to have on chart}, data: {max data you want to have on chart}}, 
  {value: {max value you want to have on chart}, data: {minimum data you want to have on chart}}
] 
```
Unlike setting .min/.max on axes you can still scale out your chart when you add data to your series(S1)
that has values bigger than min and max values in S2.

_Still doesn't work as it should, but I'm working on it_
