### ISSUE TITLE
Change format of first label

### ISSUE THREAD

**Issue by Sebastp** [amcharts/amcharts4#2213]
I've added this;
```
  dateAxis.baseInterval = {
    timeUnit: 'millisecond',
    count: 1,
  }

  dateAxis.dateFormats.setKey('millisecond', 's')
  dateAxis.dateFormats.setKey('second', 's')
  dateAxis.dateFormats.setKey('minute', 's')
```
to my value axis config but first label alwasy has different formating. How can I make it to show "0"?
![Untitled-1](https://user-images.githubusercontent.com/17354422/76096546-91a69c00-5fc6-11ea-830a-248b8ff22d8a.jpg)

**Comment by martynasma** [comment]
See #2211.

**Comment by Sebastp** [comment]
Thank you so much, I've been looking for hours
