### ISSUE TITLE
Minimum value on ValueAxis

### ISSUE THREAD

**Issue by Sebastp** [amcharts/amcharts4#2214]
How Can I prevent XYChart from zooming out too far when I can see negative values on my Value axis? I got _valueAxis.min = 1_ but it still shows negative values. Can I somehow align my chart line to the bottom?

**Comment by martynasma** [comment]
Try also setting `valueAxis.strictMinMax = true`.

**Comment by Sebastp** [comment]
I did
```
  valueAxis.min = 1
  valueAxis.strictMinMax = true
```
most of the time it works but sometimes when I add new data it still shows negative values :(

**Comment by martynasma** [comment]
Do you have an example of such chart and data?

**Comment by Sebastp** [comment]
![Untitled-1](https://user-images.githubusercontent.com/17354422/76213190-71ffb580-620a-11ea-8b2e-79a4f951ea63.jpg)
I want value "1" to be where 0.9 is.
Above state occurs when I reset data array with 
```
        chart.data = [
          {
            tick: 1,
            value: 1,
          },
        ]
```

**Comment by martynasma** [comment]
You might need to set `max` as well:

```
yAxis.min = 1;
yAxis.max = 2;
yAxis.strictMinMax = true;
```

**Comment by Sebastp** [comment]
Yeah but if I do that the chart won't scale out when y value is more then 2 like on the example I've send you

**Comment by martynasma** [comment]
Yes, but there's no other way to fix just one end of the axis scale, I'm afraid :(
