### ISSUE TITLE
How to control the Legend filter in background code ( with external NavBar ) ? 

### ISSUE THREAD

**Issue by liorkatzdev** [amcharts/amcharts4#2216]
I have chart with 4 groups of series, (s1,s2,s3,s4).
how can i control the filter that each "link" in my Nav will show 
the group i want?

**Comment by martynasma** [comment]
Not sure I understand the question. Please consider rewording your question and also posting your chart online.

**Comment by liorkatzdev** [comment]
i have this chart for example with 4 series:
![chart](https://user-images.githubusercontent.com/56354154/76194641-402d2580-61ef-11ea-8eaa-e0a820f28bbb.png)

and i have this template with nav that has 4 "links":
![chart2](https://user-images.githubusercontent.com/56354154/76194829-a6b24380-61ef-11ea-8672-c806a5f5bb9a.png)

How can i control on the filter of the series that:
UDP In controls series 1,
UDP Out controls series 2,
TCP In controls series 3,
TCP Out controls series 4

**Comment by martynasma** [comment]
OK, so if I understand you correctly, you need to toggle series by external link.

You will find this tutorial useful:
https://www.amcharts.com/docs/v4/tutorials/toggling-series-via-api/

**Comment by liorkatzdev** [comment]
that's great, but can i do the same functionality on group of series?

**Comment by martynasma** [comment]
Sure. You can call `hide()` a `show()` on multiple series instances.

```
series1.hide();
series2.hide();
```

**Comment by liorkatzdev** [comment]
thank you for the help!
