### ISSUE TITLE
dateAxis.periodChangeDateFormats null value

### ISSUE THREAD

**Issue by Sebastp** [amcharts/amcharts4#2217]
How can I prevent periodChangeDateFormats show any label?
I just want it to be blank

**Comment by martynasma** [comment]
Set it to an empty string then, e.g.:

```
dateAxis.periodChangeDateFormats.setKey("day", "");
```

Although, it would look weird with a gap in place of a label.

**Comment by Sebastp** [comment]
> Set it to an empty string then, e.g.:
> 
> ```
> dateAxis.periodChangeDateFormats.setKey("day", "");
> ```
> 
> Although, it would look weird with a gap in place of a label.

The empty string doesn't work, it shows 1970-01-01 when I set it to ""

**Comment by martynasma** [comment]
Indeed, sorry.

Make it an empty string with a space:

```
dateAxis.periodChangeDateFormats.setKey("day", " ");
```

**Comment by Sebastp** [comment]
It worked. Thanks
