### ISSUE TITLE
Angular Error: JavaScript heap out of memory

### ISSUE THREAD

**Issue by jlmonteagudo** [amcharts/amcharts4#2218]
Hello,

I've developed a new app with Angular 7 (I can't use version 8 neither 9), TypeScript 3.1 and amCharts 4. I've followed this guide to integrate with Angular: https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/

If I run **ng start**, the application is working fine. If I update the app source code while the app is running, then Angular recompiles and I get the error "JavaScript heap out of memory". I attach the full error that I get.

![angular-amchartv4-error](https://user-images.githubusercontent.com/2536720/76195476-aa8e9780-61e8-11ea-800e-48a9c34725f5.png)

I would be grateful if you could help me to solve this problem.

**Comment by martynasma** [comment]
Can you post a runable app for us to try? I'm afraid we can't reproduce this behavior.
