### ISSUE TITLE
Lineseries chart is not drawn in ie

### ISSUE THREAD

**Issue by Anusha-grandhim** [amcharts/amcharts4#2220]
Lineseries chart is not drawn in ie. All the points are clustered and line is not disappeared.
I am using amcharts 4

**Comment by martynasma** [comment]
Please post your chart full code and data somewhere where we can take a look. E.g. CodePen or jsFiddle.

**Comment by Anusha-grandhim** [comment]
I can see error SVG path data has incorrect format and could not be completely parsed.
I passing the date in the format 03/01/19 19:32:55.137

**Comment by martynasma** [comment]
Most probably you are not specifying date input format, so IE does not how to parse it.

Please read here:
https://www.amcharts.com/docs/v4/concepts/data/#Parsing_dates_in_data

**Comment by Anusha-grandhim** [comment]
I have to show the both date and time.How can I show using dateAxis

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
