### ISSUE TITLE
Inconsistent output from DateAxis textOutput adapter

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#2221]
For some reason I'm getting an inconsistent output from the DateAxis `textOutput` adapter and I can't seem to figure out where this is coming from. I created a pen [here](https://codepen.io/sassomedia/pen/xxGXXoZ?editors=0010) that gets as close to my project as possible but I don't see anything weird there. The console output in the pen is as expected:
```
undefined
Jan 08
Jan 07
Jan 06
Jan 05
Jan 04
Jan 03
Jan 02
[bold]January[/]
```

In my project however, I see the following:
```
undefined
Mar 10
Mar 09
Mar 08
Mar 07
Mar 06
Mar 03
Mar 04
(2) Mar 05
Mar 04
Mar 03
Mar 05
Mar 04
Mar 03
Mar 05
Mar 04
Mar 03
Mar 05
Mar 04
Mar 03
Mar 05
Mar 04
Mar 03
Mar 05
Mar 04
Mar 03
Mar 05
Mar 04
Mar 03
Mar 05
Mar 04
Mar 03
```
First, the dates are not in order and then some of the dates are repeated, randomly it seems. Each time I load the page, the repetitions can be more or less but there are always repetitions. The chart data provided seems to be fine, no duplicate or out of order records either. Not sure where the issue is there, the function is only called once, hence the `undefined` value at the beginning only showing once. What could be causing this behavior?

Another issue I was running into is the reverse order of the dates in this adapter. This can be seen in both the pen and in my project. I basically wanted to sort this first with the `beforedatavalidated` event listener but that does not seem to work as the `evt.target.dataItems.values` are empty at the time this event fires. Is there better way to get this data sorted or why is the data in reverse when the source data is in the right order?

Any insight would be appreciated!

**Comment by martynasma** [comment]
Due to performance optimization, label elements are reused for various purposes, and some un-displayed labels are pre-created. You can't rely on those adapters kicking in in perfect order, I'm afraid.

If your adapter needs to make decision on the order, you may use `target.dataItem.itemIndex` for that:

```
dateAxis.renderer.labels.template.adapter.add("textOutput", function(text, target) {
  if (target.dataItem) {
    console.log(target.dataItem.itemIndex);
  }
  return text;
});
```

**Comment by sassomedia** [comment]
Hmm, in that case I cannot use that adapter. `target.dataItem` would result in the same thing, just now outputting the index in odd order:
```
undefined
7
6
5
4
3
0
1
(2) 2
1
0
2
1
0
2
1
0
2
1
0
2
1
0
2
1
0
2
1
0
2
1
0
2
1
0
2
1
0
2
1
0
2
1
0
```
What I initially hoped to do was create a date axis with just the date numbers and the initial month, stacked. Then only display the month name again once the month changes:
```
Mar                                                          Apr
04          05          06          07          ...          01          02
```
`periodChangeDateFormats` sort of works for that but only when the month actually changes, i.e. on the 1st of the month. It wouldn't work where the date range displays anytime during the month, let's say from March 4th to March 11th. There would be no month visible. Hence, I thought the adapter could work for this customization but that would require 1) the data to be in sequential order and 2) only output the actual numbers of the date range.

Unless you have any other suggestion, I can go with `periodChangeDateFormats` then. I just have to display the abbreviated month with every date and then on every changing month, I'll format it to the full month to create a bit more of a visual change:
<img width="1096" alt="Screen Shot 2020-03-11 at 1 41 12 PM" src="https://user-images.githubusercontent.com/5614099/76382959-aeafe600-639d-11ea-9867-2a2266c7f1d6.png">

**Comment by martynasma** [comment]
I think using `itemIndex` is reliable. You can use `periodChangeDateFormats` like you said, and just detect the first item to override the format via `itemIndex`.

Does that make sense?

**Comment by sassomedia** [comment]
Ah, now I get it, didn't think of combining the two. Yes, so I was able to make something work with this:
```javascript
dateAxis.periodChangeDateFormats.setKey("day", "[bold]MMM[/]\ndd");
dateAxis.renderer.labels.template.adapter.add("textOutput", (txt, target) => {
  if (txt) {
    // supplied by "periodChangeDateFormats", already formatted
    if (txt.includes("[bold]")) {
      return txt;
    } else {
      let formattedDate;
      const [month, date] = txt.split(" ");

      // first item of the axis always needs to show the month
      if (target.dataItem && target.dataItem.itemIndex === 0) {
        formattedDate = `[bold]${month}[/]\n${date}`;
      } else {
        formattedDate = `\n${date}`;
      }

      return formattedDate;
    }
  }

  return txt;
});
```
Updated the pen [here](https://codepen.io/sassomedia/pen/WNvMGpB?editors=0010). I might have to add a case for the month display in case of a yearly view but otherwise, this basically does what I need it to do.

Thanks for the help @martynasma ! 👍
