### ISSUE TITLE
Two series with unsorted data

### ISSUE THREAD

**Issue by Sebastp** [amcharts/amcharts4#2222]
Hi,
I'd like to add one default series in XYChart(for default zoom out - see [issue-576998319 ](https://github.com/amcharts/amcharts4/issues/2212#issue-576998319)
```
chart.data =   [
    {
      tick: 0,
      value2: 1,
    },
    {
      tick: 0,
      value2: 2,
    },
    {
      tick: 5000, //+500 initial start
      value2: 1,
    },
  ]
```

after that I'm trying to add live data to another series with valueY = 'value' and dateX = 'tick'.
I'm doing it with chart.addData but the second line(live data) only appears on the chart after tick 5000. How can I make it visible from the start?

**Comment by martynasma** [comment]
I'm going to have to ask you to post your whole live chart somewhere where we can see it. Otherwise it's just guessing what you are doing and what seems to be the issue.

**Comment by Sebastp** [comment]
The first default data for the second series(S2) is related to this issue, I also explained how I did the default zoom;
[issuecomment](https://github.com/amcharts/amcharts4/issues/2212#issuecomment-597529557)
but when I try to update the chart with addData(object from live data), the first series(S1) doesn't show up on chart till it passes tick 5000(last point of S2).

![Nagranie-z-ekranu-2020-03-11-o-1](https://user-images.githubusercontent.com/17354422/76406045-6ab2e600-6389-11ea-86ae-ee3e530fc5a8.gif)
_note; S1 is updated with live data from tick 0_

I tried to use **chart.data =** to update the chart instead of .addData

```
//tickDataObj is a new data from sockets
        let newData = [...chart.data, tickDataObj]
        newData.sort(
          (chartItem1, chartItem2) => chartItem1.tick - chartItem2.tick
        )
        chart.data = newData //causing lags

        chart.invalidateData()
```
and it workes as expected, S1 is visible from tick 0 and zoom out stays the same until tick value on S1 is larger than the largest tick value on S2 **BUT** the whole thing is so laggy when I do it this way.
Hence I opened [this](https://github.com/xDevs-pl/GamblingFront-react/issues/35), but I assume "chart.data =" is just rerendering the whole chart, not just data inside.
You can see how I initialize amchart [here](https://codesandbox.io/s/amchart-example-jumdb) in chartService.js.
Hope it makes sense

**Comment by martynasma** [comment]
Looks like codesandbox.io link takes to an empty app, no chart. Can you post your actual chart there?

**Comment by Sebastp** [comment]
> Looks like codesandbox.io link takes to an empty app, no chart. Can you post your actual chart there?

No, not really. My app is extensive and chart uses socket data and when I try to setup it on codesandbox it throws _"Cannot read property 'requestFrame' of undefined"_. Try to intialize chart with code I wrote [there](https://codesandbox.io/s/amchart-example-jumdb) and then add any data with "chart.addData()" eg. ```
chart.addData({
        tick: 5000
        value: 1.3
      }) 
```

**Comment by Sebastp** [comment]
any ideas @martynasma ? The chart works when I add it with 
```
chart.data = newData //causing lags
chart.invalidateData()
```
but the whole website is very laggy when I do it this way.

**Comment by zeroin** [comment]
Could you try to add data to the series instead of the whole chart?

**Comment by Sebastp** [comment]
Sorry, I don't work on this project anymore. Thanks a lot for all your help
