### ISSUE TITLE
[Question] how to implement date & time (ie: 2020-03-09 07:17:00 ) together on chart axis

### ISSUE THREAD

**Issue by SheharyarSMAdil** [amcharts/amcharts4#2223]
![image](https://user-images.githubusercontent.com/41816068/76318657-0e59b300-6304-11ea-9a6c-a4ba3d61cca2.png)

my chart is showing like this (referring above image), just because it is not taking date format as "yyyy-MM-dd HH:mm:ss", I also tried `chart.dateFormatter.dateFormat = "yyyy.MM.dd HH:mm:ss";`

I am using Typescript/ES. 

please if possible try to upload some of its tutorials on Youtube.

Thanks

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Formatting_date_and_time
