### ISSUE TITLE
dateAxis tooltipHTML loading issue.

### ISSUE THREAD

**Issue by masc2279** [amcharts/amcharts4#2224]
Latest Amcharts Version

So there is a bug when loading dateAxis tooltipHTML ....

When mousing from any direction other than from the bottom where the date axis loads the standard tooltip is displayed which should not happen when a tooltipHTML has been set. 

<img width="525" alt="Screen Shot 2020-03-10 at 8 04 05 AM" src="https://user-images.githubusercontent.com/1273722/76321147-36ff8f80-62a7-11ea-9b61-3aa7ad33efff.png">

Once you mouse from the bottom and cross the dateAxis, Amcharts loads the tooltipHTML.

<img width="513" alt="Screen Shot 2020-03-10 at 8 06 02 AM" src="https://user-images.githubusercontent.com/1273722/76321424-9f4e7100-62a7-11ea-8624-665be87da8ea.png">

and from that point it knows of the tooltipHTML 

<img width="534" alt="Screen Shot 2020-03-10 at 8 06 39 AM" src="https://user-images.githubusercontent.com/1273722/76321542-cc9b1f00-62a7-11ea-9530-a0d48b397f5f.png">

and no matter what direction you come from it will display it correctly from that point on.

The tooltipHTML is set this should be known at load and not have a mixed experience.

**Comment by martynasma** [comment]
I'm not entirely sure this should work at all.

When you say "loading tooltipHTML" do you mean you are setting it directly on axis like this?

```
axis.tooltipHTML = ".....";
```

I suppose the correct way would be to override axis tooltip's label `html` property with an adapter:

```
axis.tooltip.label.html = " ";
axis.tooltip.label.adapter.add("html", function(html, target) {
  // construct tooltip HTML contents
  // ...
  return html;
});
```

**Comment by masc2279** [comment]
Yes setting it directly just like the docs state todo for series but it does not work. I have dug some more and I have found another post and its marked as a known bug. So this is still an issue out that has not been resolved.

**Comment by martynasma** [comment]
Have you tried the adapter approach I suggested in my last post?

**Comment by jeadly** [comment]
This sounds a lot like the issue I had with the categoryAxis toolTipHTML property.
https://github.com/amcharts/amcharts4/issues/2209
It doesn't display the HTML content until you mouse over the axis labels. Instead, try setting the axis.tooltip.html property.
