### ISSUE TITLE
Can't set stroke color for ColumnSeries3D

### ISSUE THREAD

**Issue by mrAndyss** [amcharts/amcharts4#2226]
I am try to set columns stroke color in this demo:
https://codepen.io/mrAndyss/pen/RwPQbLb
But it does not work.
For ColumnSeries it works perfectly.
What am I doing wrong?

**Comment by xorspark** [comment]
You have to set the stroke, fill, etc on the `column3D` property in the column template, e.g.

```
series.columns.template.column3D.fillOpacity = .8; 
series.columns.template.column3D.strokeWidth = 2;
series.columns.template.column3D.strokeOpacity = 1;
series.columns.template.column3D.stroke = am4core.color("red");
```

[Updated codepen](https://codepen.io/team/amcharts/pen/c73dcac8357d6ef1dfa0a82e64876400?editors=0010)

**Comment by mrAndyss** [comment]
Perfect! Thanks you!
