### ISSUE TITLE
Horizontal gauge chart with non linear axis and gradient

### ISSUE THREAD

**Issue by squareloop1** [amcharts/amcharts4#2227]
I am trying to create a horizontal gauge chart with a gradient [similar to this one](https://i.stack.imgur.com/hrbAH.png)

Sadly I can't find anything in demos or docs to create a chart like this. It seems like the gauge charts can't be set to a straight horizontal bar?

I would also like to have a non linear axis on that bar.
If you look at the bar in the attached image what I want to do is the red range to occupy a bigger value part but still rendering as the same or smaller size then other ranges to be able to display more values and keep the color gradient smooth without too large or too small colored ranges.

Is this somehow possible with this library? I can't seem to find any information on that in the docs / demos.

**Comment by martynasma** [comment]
Perhaps you can use this demo as a base:
https://www.amcharts.com/demos/bullet-chart/

Use axis ranges to place brackets labels, and event bullets:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_labels
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_bullets
