### ISSUE TITLE
dynamic values in column chart

### ISSUE THREAD

**Issue by liorkatzdev** [amcharts/amcharts4#2229]
i have this design : 

![cpu2](https://user-images.githubusercontent.com/56354154/76396149-5539be00-6381-11ea-85fd-ffe8aad74ab9.png)

1) how I make the data in the column change dynamicly?
2) how and were I initialize the data (in chart.data or series.data?) and were to make it look like that? (that Pe in the Category)

**Comment by martynasma** [comment]
Read here:
https://www.amcharts.com/docs/v4/concepts/data/#Dynamic_updates

And here:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_labels

**Comment by liorkatzdev** [comment]
how I will update specific column data without to remove it?

**Comment by martynasma** [comment]
Have you read the documentation links? It contains the information you're asking.

**Comment by liorkatzdev** [comment]
To add new data point, or several data points, to already existing data set, you use chart's addData(datapoint(s), remove) method.

As the first parameter, you pass in a data point (or an array of data points) to add to your existing data set.

Optional second parameter tells how many data points to remove **from the begining of the data set.**

if i have : 
this.chart.data = [
      {
        category: 'Pe1' ,
       c1: 10
      },
      {
        category: 'Pe1' ,
        c2: 20
      },
 {
        category: 'Pe1' ,
       c3: 30
      }
    ]

how i remove the 2nd object?

**Comment by sassomedia** [comment]
As far as I understand it, `addData` is only meant for a continually updating chart, like a live chart. For anything else, just reassign new data.
