### ISSUE TITLE
Working with Codesandbox

### ISSUE THREAD

**Issue by RaedsLab** [amcharts/amcharts4#223]
I have tried to use amcharts with [Codesandbox ](https://codesandbox.io/s/xrp42n3nxw) and Babel kept throwing errors as soon as I imported it.

I have [opened an issue there](https://github.com/CompuIves/codesandbox-client/issues/1029) and @CompuIves seems to think its because of async `import()`, not sure if this is intentional and whether it can fixed ?

**Comment by amcharts** [comment]
> New comment from Zendesk by **Abed Islam** on ticket **38680**.
> (replying here will automatically notify amCharts support agent)

Would it be possible to use StackBlitz for your purposes?

E.g.
https://stackblitz.com/edit/38680-codesandbox-error

The live editor works there, though the file structure is a little different in the editor, it uses the same create-react-app under the hood. When you export/download the project archive, you'll get a similar file structure, as well as a package.json with the same scripts for building.

Yours sincerely,

Abed Islam
amCharts

**Comment by RaedsLab** [comment]
Thank you, I kind of forgot about stackblitz but it work great!

**Comment by amcharts** [comment]
> New comment from Zendesk by **Abed Islam** on ticket **38680**.
> (replying here will automatically notify amCharts support agent)

Awesome! You're welcome.

Glad that's working for you.

If you have any other issues please don't hesitate to reach out to us.

Yours sincerely,

Abed Islam
amCharts
