### ISSUE TITLE
Setting tooltiptext in an adapter fixes the tooltip to the cursor

### ISSUE THREAD

**Issue by IkamThorek** [amcharts/amcharts4#2231]
Hi, I'm trying to show a tooltip on some labels, and I would like to position it right under the axis. However, even though I set the tooltipPosition to "fixed", the tooltip follows the cursor.

Here is the [stackblitz](https://stackblitz.com/edit/typescript-jkukyp).

**Comment by martynasma** [comment]
I suppose it's because you are setting `tooltipText` directly on axis. Try setting it on the label itself.

```
ev.target.tooltipText = "Tooltip";
```

**Comment by IkamThorek** [comment]
When I set ev.target.tooltipText, the tooltip is fixed and points to the center of the label, as would be expected which is close to what I'm trying to achieve. 

The reason why I initially set axis.tooltipText is that I want the tooltip to be fixed to the axis (so a few pixels higher than the label's tooltip). 

I posted this issue because it made no sense to me that when I set axis.tooltipText, the tooltip behaves as if it weren't fixed, even though the tooltipPosition is still "fixed".

**Comment by martynasma** [comment]
I suppose you can also use `tooltipY` to modify the place tooltip is pointing to:

```
ev.target.tooltipY = -5;
ev.target.tooltipText = "Tooltip";
```

**Comment by IkamThorek** [comment]
That does the trick for me thanks. But is what I described above the expected behaviour ?

**Comment by martynasma** [comment]
Well, the axis is a big thing spanning whole width of the chart, whereas it has one tooltip. So using its tooltip to position over specific label, seems a bit weird to me :)

If you need to display tooltip on label, maybe you should use label's own `tooltipText` and `tooltipY` directly (no need for hover events):

```
xAxis.renderer.labels.template.tooltipText = "Something";
xAxis.renderer.labels.template.tooltipY = -5;
```
