### ISSUE TITLE
style error while adding data to chart RadarChart

### ISSUE THREAD

**Issue by liorkatzdev** [amcharts/amcharts4#2236]
that's the chart before i added my data: 

![mem before](https://user-images.githubusercontent.com/56354154/76440775-09116c80-63c7-11ea-9572-8924d23db40f.png)

but after i added my data object to chart.data with: chart.AddData({data obj}) style went wrong:   

![mem after](https://user-images.githubusercontent.com/56354154/76440975-5ab9f700-63c7-11ea-81f5-c4db63328c27.png)

**Comment by martynasma** [comment]
Can you post your chart on CodePen?
