### ISSUE TITLE
Setting disabled property on LabelBullet has no effect when series was hidden during the last change of disabled property

### ISSUE THREAD

**Issue by c-goetz** [amcharts/amcharts4#2237]
Hi,

we use amcharts4 and implemented a button to toggle the visibility of LabelBullets. This does work most of the time but not for the following case:

Codepen: https://codepen.io/carlo_g/pen/QWbQmLq

*Steps to reproduce:*

- hide series 'Asia-Pacific' through legend
- click 'toggle labels' twice
- show series 'Asia-Pacific' through legend
- click 'toggle labels' once

*Expected result:*

Label for series 'Asia-Pacific' is visible.

*Actual result:*

The series 'Asia-Pacific' has no visible label.

I tried to fix this the last hours but could not find a solution. For me it looks like the properties are set correctly on the template and on the clones.

What am I doing wrong?

Already tried the solution from:
https://github.com/amcharts/amcharts4/issues/1593

Thanks for your help and have a nice day.
Carlo

**Comment by martynasma** [comment]
You can toggle both `disabled` and `visible`:

```
b.disabled = !toggle;
b.visible = !toggle;
```

That should do the trick.

**Comment by c-goetz** [comment]
Hi,

thanks for your quick reply.
I updated the CodePen. Using the recommended approach. I still get a not-visible label:

- hide series 'Asia-Pacific'
- toggle labels twice
- show series 'Asia-Pacific'
- toggle labels once

--> label is shown

- toggle labels once
- hide series 'Asia-Pacific'
- toggle labels twice
- show series 'Asia-Pacific'
- toggle labels once

--> label is not shown

Also I'm not sure why the label is visible after the first cycle. Setting `visible` to the same value as `disabled` and seeing the label is a little bit counterintuitive.

Thanks for your help and have a nice weekend.
Carlo

**Comment by zeroin** [comment]
This happens because when a series is hidden, the labels animate their opacity to 0. So after some clicks the label remains invisible. To solve this, you should also set opacity of a label to 1:

https://codepen.io/team/amcharts/pen/36606a097eb1cf1f13c001a80bedc9fb

**Comment by c-goetz** [comment]
Works like a charm.
Thanks again for your fast help. You have some really good support here.
Have a nice day!
