### ISSUE TITLE
[Question] How to clear chart data Completely.

### ISSUE THREAD

**Issue by SheharyarSMAdil** [amcharts/amcharts4#2238]
I am using `chart.data= []` to clear the chart data but it is not doing so.
am I doing something wrong? @martynasma 

![image](https://user-images.githubusercontent.com/41816068/76507697-3ca9d080-6473-11ea-8b12-0b6838ae128e.png)

**Comment by martynasma** [comment]
Setting `data` to empty array should do it. I just checked and it works.

Can you post your actual chart on CodePen?

**Comment by SheharyarSMAdil** [comment]
@martynasma yeah, it works, but another problem occurs, every time I update the chart it reduces its size and shift upwards, 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/41816068/76675556-895eea00-65e0-11ea-983e-3658b8b63891.gif)

btw thanks for helping me out.

**Comment by SheharyarSMAdil** [comment]
![image](https://user-images.githubusercontent.com/41816068/76675878-2bcc9c80-65e4-11ea-83e3-640052ed0bfe.png)

**Comment by SheharyarSMAdil** [comment]
![image](https://user-images.githubusercontent.com/41816068/76675945-d8a71980-65e4-11ea-8150-6421f934d86e.png)

![image](https://user-images.githubusercontent.com/41816068/76675941-d2b13880-65e4-11ea-8316-8257ef346283.png)

**Comment by martynasma** [comment]
I'm sorry mate, I can't debug screenshots.

Can you post your chart online?

**Comment by SheharyarSMAdil** [comment]
Bro, I thought this might be some type of common issue. I send you an invite for a collaborator in the git repository. I hope this will help you in debugging my code.

**Comment by martynasma** [comment]
Do you have support subscription with amCharts? If you do, please contact@amcharts.com

If you don't, you can purchase one:
https://www.amcharts.com/support/support-info/purchase-support/

I took a look at your repo, and it's a large application. The issue is not self-evident, and would require more research, which goes beyond the scope of basic support we do here in GitHub.
