### ISSUE TITLE
Export as pdf setting addURL to false is ignored

### ISSUE THREAD

**Issue by IkamThorek** [amcharts/amcharts4#2239]
In order to export my data correctly, I use an adapter with **chart.exporting.adatper.add("data", ...)**. 

However, even though **chart.exporting.getFormatOptions("pdf").addURL** is false, I get the url in my pdf files.

As a matter of fact, the [tutorial](https://www.amcharts.com/docs/v4/tutorials/adding-extra-info-in-exported-pdf/#Example) that explains how to get rid of the link still has the link to me.

![image](https://user-images.githubusercontent.com/60658002/76511105-f2185c00-6452-11ea-9d5d-85669b64a7f2.png)

**Comment by martynasma** [comment]
It looks like you are exporting pdf data. It has different option set: "pdfdata".

```
chart.exporting.getFormatOptions("pdfdata").addURL = false;
```

**Comment by IkamThorek** [comment]
Thanks
