### ISSUE TITLE
Wrong legend colors after hide and show

### ISSUE THREAD

**Issue by dennis-kramp** [amcharts/amcharts4#2240]
I encountered probably a bug...
When you disable a series with the use of the legend and then enable it again the setted colors on the text are wrong. In order to colorize the text i used the following:      
`chart.legend.labels.template.text = "[{color}]{name}[/]";`

See the following image
![wrong colors legend amcharts](https://user-images.githubusercontent.com/43716136/76519084-98b72980-6460-11ea-9456-cce7f43288a8.gif)
Initial the colors are yellow and purple which are correct. After changing they are becoming blue (default text color for the whole page via css).

**Comment by martynasma** [comment]
What is `{color}` supposed to refer to?

If you could post your actual chart on CodePen that would make it easier for us.

**Comment by dennis-kramp** [comment]
Thanks for your reply.
Here you have a [CodePen](https://codepen.io/dennis-kramp/pen/ZEGxGMa).

So `{color}` should in my opinion refer to the series.stroke property (if set). [https://www.amcharts.com/docs/v4/concepts/series/#Simple_properties](https://www.amcharts.com/docs/v4/concepts/series/#Simple_properties)

I've setted the `chart.legend.labels.template.text` according to the [Name Label Section](https://www.amcharts.com/docs/v4/concepts/legend/#Name_labels)

After some investigation I found out that if the `chart.colors.list` array contains the respective colors then everything is fine. In my example it is
```javascript
chart.colors.list = [am4core.color('#6610f2'), am4core.color('#f8ae00')];
```
In [this example](https://codepen.io/team/amcharts/pen/aKbOgd) from you the chart uses the default colors so the "bug" will never appear.

I have no idea why initially the label color is correct, without setting up the color list. Maybe the docs should have a annotation to what the `{color}`-Formatting String actually refers.

**Comment by martynasma** [comment]
So if you are referring to `stroke` property, you should probably use that code in label formatting as well:

```
chart.legend.labels.template.text = "[{stroke}]{name}[/]";
```

**Comment by dennis-kramp** [comment]
Oh wow. thats much easier then... Thank you! :relaxed:
