### ISSUE TITLE
Switch between date format

### ISSUE THREAD

**Issue by Julienh** [amcharts/amcharts4#2241]
I'm updating my code from amcharts3 to amcharts4. Users can switch between 4 different format date: day (yyyy-mm-dd), week (yyyy-ww), month (yyyy-mm) and year (yyyy).

With amcharts3 I used AmCharts.stringToDate to format the date but with amcharts4 I don't find the equivalent. When the dates are 2019 and 2020 I have this:

![](https://i.stack.imgur.com/TXaJS.png)

I'm usinf DateAxis and I tried to add this as the documentation said but no help :
```
chart.dateFormatter.inputDateFormat = "yyyy";
chart.dateFormatter.dateFormat = "yyyy";
```

Here is an example of data used for the screenshot:
```
[{"year":2019,"value1":21956,"value2":71639.96,"value3":699187},{"year":2020,"value1":4248,"value2":12672.74,"value3":122456}]
```

Thank you for your help.

**Comment by Julienh** [comment]
Here is an example: https://codepen.io/julienh/pen/ExjQzeR?editors=0010

**Comment by martynasma** [comment]
`DateAxis` does not use `dateFormatter.dateFormat` but rather collection of multiple formates.

Please read here:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Formatting_date_and_time

**Comment by Julienh** [comment]
Thank you :)
