### ISSUE TITLE
Map of India is wrong

### ISSUE THREAD

**Issue by wilzad** [amcharts/amcharts4#2242]
Hi, 
I tried to use the inbuilt map for India in am4map package and the map for India is wrong on the Kashmir side so it is not legal to use in India'. Please take a look

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v4/tutorials/country-specific-world-maps/
https://www.amcharts.com/docs/v4/tutorials/using-india-version-of-world-map/

**Comment by martynasma** [comment]
Sorry, you mentioned India map, not the world map.

You may need to use `india2019*` map which is an updated map.
