### ISSUE TITLE
Sunburst dynamic updates not working as expected

### ISSUE THREAD

**Issue by RichardCosta10** [amcharts/amcharts4#2244]
I'm trying to get the Sunburst chart to update as per [documentation](https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points) however modifying the values and calling `invalidateRawData` doesn't cause the chart to update.

The chart updates when using `invalidateData` but I want to be able to see the chart animations/transition.

The issue can be seen here: https://codepen.io/richardcosta10/pen/dyomOmw?editors=1011

Any help appreciated, thank you.

**Comment by martynasma** [comment]
`invalidateRawData` does not support charts with hierarchical data like Sunburst. There's no workaround at this time. Sorry.

We will discuss of maybe adding this support and will let you know.

**Comment by RichardCosta10** [comment]
Thanks for your very prompt response.

Do you think this is something simple enough that can fixed by the user and possibly a pull request submitted?

**Comment by martynasma** [comment]
> Do you think this is something simple enough that can fixed by the user and possibly a pull request submitted?

I doubt that :/ We do have a tentative TODO to implement dynamic data updates for hierarchical data, but it's quite complicated frankly. So no ETA.

**Comment by martynasma** [comment]
I'm afraid we won't be able to implement incremental updates on Sunburst chart. There's just too many moving parts there for it. Sorry.
