### ISSUE TITLE
Zooming out does not resize yAxes

### ISSUE THREAD

**Issue by floklein** [amcharts/amcharts4#2245]
Hi!

When zooming in, yAxes widths correctly expand to display labels with their increasing number of decimals. But when zooming out, they don't revert, keeping their extended width, and a lot of blank space.

![yaxes](https://user-images.githubusercontent.com/4128942/76632388-72b68580-6543-11ea-9c8c-077f707a401b.png)

https://codepen.io/floklein/pen/bGdvabv
Steps to reproduce:
- Zoom in a lot until labels reach multiple decimals
- Zoom out

**Comment by martynasma** [comment]
This is by design, so that axis widths do not jump around when zooming and panning.

I suppose you can fix the width of the labels, so they never change:

```
axis.renderer.labels.template.width = 40;
```

**Comment by floklein** [comment]
Isn't there a way to force axes to redraw, like with an `.invalidate()`?

**Comment by zeroin** [comment]
Try to add this line:
`dateAxis.ghostLabel.disabled = true`

This ghostLabel is made for the axes not to jump when zooming, but you need the opposite :)

**Comment by zeroin** [comment]
Hm, I see that this does not actually help, I'll try to find another solution.

**Comment by zeroin** [comment]
OK, I am not very smart today - you should disable `valueAxis.ghostLabel`, not date axis':
https://codepen.io/team/amcharts/pen/113f0e64069f6cdc95fd3f6955d19142

**Comment by floklein** [comment]
Thanks! Works great!
