### ISSUE TITLE
Different circle property for different data in data object [map]

### ISSUE THREAD

**Issue by sanjayojha** [amcharts/amcharts4#2246]
I want to show circle on different states. I want to set circle radius, fill color and stroke different for different data in data objects.

I am following this example(https://www.amcharts.com/docs/v4/chart-types/map/#Image_series) to create circle. 

Consider this data object:
```
imageSeries.data = [{
  "latitude": 48.856614,
  "longitude": 2.352222,
  "title": "Paris"
}, {
  "latitude": 40.712775,
  "longitude": -74.005973,
  "title": "New York"
}, {
  "latitude": 49.282729,
  "longitude": -123.120738,
  "title": "Vancouver"
}];
```
Now I want to show circle for these 3 locations but with different color, radius and stroke. 
How can I do this?

**Comment by martynasma** [comment]
You can use `propertyFields` to bind different properties of series objects to data. E.g.:

```
var circle = imageSeries.mapImages.template.createChild(am4core.Circle);
// ... configure circle
circle.propertyFields.fill = "color";
circle.propertyFields.radius = "radius";
```

More info here:
https://www.amcharts.com/docs/v4/chart-types/map/#Binding_properties_to_data

**Comment by sanjayojha** [comment]
Its working. Thank you very much for quick reply and making this awesome library.

**Comment by sanjayojha** [comment]
Just made this - https://coronavirus-india-map.com/
Is their any way, I can show pulsating effect

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by sanjayojha** [comment]
Sorry, I will create new post.
