### ISSUE TITLE
Bullets position on ColumnSeries3D

### ISSUE THREAD

**Issue by mrAndyss** [amcharts/amcharts4#2248]
I need to place a bullet under the series columns. How can I do it?
https://codepen.io/mrAndyss/pen/YzXabpj?editable=true
![image](https://user-images.githubusercontent.com/62033545/76687325-e46dfc80-6633-11ea-885d-8e934747c139.png)

**Comment by martynasma** [comment]
You can use bullet's `x` and `y` properties:

```
bullet.x = am4core.percent(50);
bullet.y = am4core.percent(100);
```

**Comment by mrAndyss** [comment]
Thank you.
