### ISSUE TITLE
Question: How to expand only one sub-level in force directed graph?

### ISSUE THREAD

**Issue by jbrepogmailcom** [amcharts/amcharts4#2249]
I have graph with many levels and hundreds of nodes. On start, I can display only two top levels. But when I collapse top level by click and then click again to expand it, ALL sub-levels get expanded and desktop is cluttered by nodes.

Is it possible to expand only one level down by one click? Thank you very much, Jan

**Comment by martynasma** [comment]
Set node template [`expandAll`](https://www.amcharts.com/docs/v4/reference/forcedirectednode/#expandAll_property) to `false`:

```
series.nodes.template.expandAll = false;
```
