### ISSUE TITLE
Another data field for column series label

### ISSUE THREAD

**Issue by mrAndyss** [amcharts/amcharts4#2250]
I know this very easily, but i cant find how do it ((.
In this demo https://codepen.io/mrAndyss/pen/YzXabpj, I need do that the labels for the column are assigned from the field "name" , and not from the filed "fullname". If i change series.dataFields.categoryX = "name" ill get one column instead two.

**Comment by martynasma** [comment]
You can use an adapter for that:

```
categoryAxis.renderer.labels.template.adapter.add("textOutput", function(text, target) {
  if (target.dataItem.index >= 0) {
    return chart.data[target.dataItem.index].name;
  }
  return text;
});
```

**Comment by mrAndyss** [comment]
Thank you again! And sorry for my newbee question.
