### ISSUE TITLE
Question: Scrollbar to force directed graphp

### ISSUE THREAD

**Issue by smooth97** [amcharts/amcharts4#2253]
I would like to apply a scroll bar that displays data filtering on the force directed graph, but I would appreciate it if you could answer if this was possible.
thank you so much :)

**Comment by martynasma** [comment]
There's no such built-in function. However, you can implement your own.

Depending on how you want your chart to function you might either need to dynamically replace `chart.data`, or hide/show available nodes.

In case you want to do the latter, here's a demo on how you can toggle nodes by id:

https://codepen.io/team/amcharts/pen/WqbPQe
