### ISSUE TITLE
Can't display Map image series with JSON

### ISSUE THREAD

**Issue by fredmef** [amcharts/amcharts4#2254]
Hi,

I can't display the following map image series using JSON configuration.
However Map polygon and line series are well displayed.`
I'm using Amcharts 4.9.8.

```

'series' => [
        [
          'type' => 'MapPolygonSeries',
          'id' => 's1',
          //'exclude' => ['AQ'],
          'useGeodata' => TRUE,
          'mapPolygons' => [
            'tooltipText' => '{name}',
            //'fill' => '#74B266',
            'fill' => '#67b7dc',
            'states' => [
              'hover' => [
                'properties' => [
                  'fill' => '#367B25'
                ]
              ]
            ]
          ]
        ],
        [
          'type' => 'MapImageSeries',
          'useGeodata' => TRUE,
          'mapImages' => [
            'propertyFields' => [
              'latitude' => 'latitude',
              'longitude' => 'longitude',
              'title' => 'title',
            ],
            'children' => [
              [
                'type' => 'Circle',
                'radius' => 4,
                'stroke' => '#B27799',
                'strokeWidth' => 2,
                'nonScaling' => TRUE,
                'tooltipText' => '{title}',
              ]
            ],
            'data' => [
              [ 'latitude' => 55.7504461, 'longitude' => 37.6174943, 'title' => 'Moscou' ],
            ]
          ]
        ],
        [
          'type' => 'MapLineSeries',
          'mapLines' => [
            'nonScalingStroke' => TRUE,
            'arrow' => [
              'nonScaling' => TRUE,
              'position' => 0.5
            ],
          ],
          'data' => [
            [
              'multiGeoLine' => [
                [
                  [ 'latitude' => 48.8566969, 'longitude' => 2.3514616 ],
                  [ 'latitude' => 38.7077507, 'longitude' => -9.1365919 ],
                  [ 'latitude' => -33.928992, 'longitude' => 18.417396 ],
                  [ 'latitude' => 40.7127281, 'longitude' => -74.0060152 ]
                ]
              ]
            ]
          ]
        ]
      ],
```

Thanks for your comments.
Regards,
Frederic.

**Comment by xorspark** [comment]
Your map image data needs to be set at the series level, not at the `mapImages` level


        [
          'type' => 'MapImageSeries',
          'useGeodata' => TRUE,
          'data' => [
              [ 'latitude' => 55.7504461, 'longitude' => 37.6174943, 'title' => 'Moscou' ],
           ],
          'mapImages' => [
            'propertyFields' => [
              'latitude' => 'latitude',
              'longitude' => 'longitude',
              'title' => 'title',
            ],
            'children' => [
              [
                'type' => 'Circle',
                'radius' => 4,
                'stroke' => '#B27799',
                'strokeWidth' => 2,
                'nonScaling' => TRUE,
                'tooltipText' => '{title}',
              ]
            ],
          ]


[Demo](https://codepen.io/team/amcharts/pen/42f3f289e12e958dc27a81e2fa72b480?editors=0010)

**Comment by fredmef** [comment]
@xorspark I didn't check that in the documentation. Thanks a lot, it works perfectly.
