### ISSUE TITLE
Question: how do I remove empty legend items in nested pie?

### ISSUE THREAD

**Issue by puyt** [amcharts/amcharts4#2255]
Hi,

Is it possible to remove the empty legend item in a nested pie?

I modified this [pen](https://codepen.io/team/amcharts/pen/PQrvJr) by simply adding a legend and changing the data to something similar to my use case.

Modified pin:
https://codepen.io/puyt/pen/oNXdqWO

Thanks in advance.

**Comment by zeroin** [comment]
The most simple solution would be to set data for each of the series independently:
https://codepen.io/team/amcharts/pen/oNXdqVN

**Comment by puyt** [comment]
That's what I feared :sweat_smile:
Currently I had all data set to a serie regardless of the chart I used but I found that the data set on the chart was more flexible since my data is always the same but displayed differently (column, stacked, clustered, waterfall, ...). 

There's no workaround to solve this with the data on the chart? If not, no big problem i'll just make an exception for pie charts

**Comment by zeroin** [comment]
Well, dataItem has a `hiddenInLegend` property and dataField, and you can use it to hide the items, but I would say it's a lot more complicated than having separate data for each series.

**Comment by puyt** [comment]
Alright thanks  :+1:
