### ISSUE TITLE
IE11 different width of Pie Chart than on Chrome

### ISSUE THREAD

**Issue by WojciechKlisiewicz** [amcharts/amcharts4#2257]
Hello, I rendered 4 charts in one row as flexbox so all of them should have 25% of the width. On Chrome all charts resized properly so empty space between pie chart in SVG are reduced (I using min-height of parent div). In chrome when I checked width property in chart model - its 135px and height 156px (the same like min-height). For the same view on IE 11 width is 300px so the whole view is destroyed (too wide charts). The size of pie chart is the same but empty space is bigger than on Chrome. Is any solution to fix it in IE?

**Comment by martynasma** [comment]
Can you post your chart setup online, e.g. on CodePen or jsFiddle?

**Comment by WojciechKlisiewicz** [comment]
`
this.element = this.elRef.nativeElement.querySelector('.chart');
this.chartType = am4charts.PieChart;
this.chart = am4core.create(element, this.chartType);
this.series = this.chart.series.push(new am4charts.PieSeries());
this.chart.innerRadius = am4core.percent(60);
this.series.dataFields.value = 'count';
this.series.dataFields.category = 'category';
this.chart.fontFamily = 'Arial';
this.chart.fontSize = '12px';
this.series.ticks.template.disabled = true;
this.series.labels.template.disabled = true;
this.series.focusable = false;
this.series.hoverable = false;
this.series.slices.template.states.getKey('hover').properties.scale = 1;
this.series.slices.template.states.getKey('active').properties.shiftRadius = 0;
`

And all charts is rendered as:

`
<div styles="display: flex">
    <div class="box-with-chart" styles="flex-basis: 100%; flex-grow: 1"><div class="chart"></div></div>
    <div class="box-with-chart" styles="flex-basis: 100%; flex-grow: 1"><div class="chart"></div></div>
    <div class="box-with-chart" styles="flex-basis: 100%; flex-grow: 1"><div class="chart"></div></div>
    <div class="box-with-chart" styles="flex-basis: 100%; flex-grow: 1"><div class="chart"></div></div>
</div>
`

Of course is only a mocking for you. I cannot share the original code. I see that IE set a different width for SVG.

**Comment by martynasma** [comment]
This doesn't look like a flex box that would be displayed in four columns, charts or not.

Are you sure it's an amCharts problem?

**Comment by WojciechKlisiewicz** [comment]
Content of SVG has 300px width, I expect to  display square (only pie chart) without no bigger space - should be 130px x 130px instead of 300px x 150px. Can I set displaying SVG with proportion 1:1?

**Comment by martynasma** [comment]
I'm sorry but I don't understand. I don't see any pixel widths in your code.

Can you post your chart online somewhere where I can see it in action? Performing good in Chrome, but failing in IE.

Please also note that IE11's implementation of flexbox is quite buggy.

**Comment by WojciechKlisiewicz** [comment]
It looks like SVG issue in flexbox on IE. Changing it to the table helped me.
