### ISSUE TITLE
Is an automatic zoom can be applied between Map series ?

### ISSUE THREAD

**Issue by fredmef** [amcharts/amcharts4#2258]
Hi,

is it possible to have an automatic zoom set on data for a map image series applied directly on a map polygon series to see only the part of the map with data ?

Regards,
Frederic.

**Comment by xorspark** [comment]
We have a couple of tutorials that go into this.

Setting initial zoom and position: https://www.amcharts.com/docs/v4/tutorials/setting-initial-zoom-and-position-of-a-map-chart/

Pre-zooming to a country: https://www.amcharts.com/docs/v4/tutorials/pre-zooming-map-to-a-country/

**Comment by fredmef** [comment]
@xorspark Thanks but these tutorials don't help me because they use an hardcoded zoom (not based on data series)

I want to create something like the automatic zoom on markers in Google Maps.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/41957018/76940349-5aa38500-68fa-11ea-97e3-6ff04804db59.png">

**Comment by martynasma** [comment]
`MapImageSeries` has properties like `south`, `east`, `west`, `north`. Those will hold the the latitudes, and longitues of the series boundaries. You can use those to zoom.

**Comment by fredmef** [comment]
Thanks @martynasma I'll use these options.
