### ISSUE TITLE
XY lines/dots charts with interpolationDuration have appearance bug on executing chart.validateData()

### ISSUE THREAD

**Issue by wj42ftns** [amcharts/amcharts4#2260]
Demo: https://youtu.be/8u63-fPUcBc
The example with the bug: https://codepen.io/wj42ftns/pen/rNNZapX?editors=1010
How to reproduce to duplicate: click to "validate data" button and you will see that the chart is jogging.
I duplicated it in the latest Chrome, fireFox (in rest browsers I didn't try to check it)

**Comment by wj42ftns** [comment]
also, the same for chart.invalidateData() - example above was updated.

**Comment by wj42ftns** [comment]
The same for the am4charts.RadarChart type - example above was updated

**Comment by zeroin** [comment]
Well, you ar enot using animated theme but only set interpolationDuration for the series. So this is expected result - series animates and value axis jumps instead of animating. If you add: 

`am4core.useTheme(am4themes_animated)` line to your code, the animation would be smooth.

**Comment by wj42ftns** [comment]
Thank you, it looks a little better, but not like the expectable result.
Can I somehow keep from the start animation axis size from the end of the animation without this jogging?

I mean without adding fixated axis.min/max values - because I using dynamic filling data from the input and I need to show all values on the chart with extra min/max and axis values steps exactly the same as the default.

**Comment by zeroin** [comment]
This can be done if you set min and max values for your ValueAxis. Or, set `valueAxis.strictMinMax = true`, but this will result the min and max to be at exactly your min/max values, unless you set `valueAxis.extraMin` and `valueAxis.extraMax` to some 0.1 or so, but the axis will not necessary start at the round value. 

And if you do nothing but use animated theme and not set series interpolationDuration to 3000, but keep default value, the interpolation will be much smoother. Or, if you need a long interpolation, then you should adjust `rangeChangeDuration` of your value axis to some similar value: https://codepen.io/team/amcharts/pen/a31d94fe8d6c53d307b7fcb384e49988?editors=1010
