### ISSUE TITLE
Multi-series shared tooltip value does not render when it has special characters

### ISSUE THREAD

**Issue by pragatheeswarans** [amcharts/amcharts4#2261]
Hello,

I am trying to build a line chart with Multi-series shared tooltip. In the tooltip, the value is not rendered when the key has some special characters like `()` or `html` tags. 

Sample Data format:
> {
  'date': new Date(2018, 0, 1),
  'value': 450,
  'value2': 362,
  'value3()': 699
}

Output:
![amcharts](https://user-images.githubusercontent.com/19588386/76947103-21cfd400-692b-11ea-8ab5-f909200717f3.png)

Can someone help me on how to overcome this issue as the user input in our application might have any characters in it. 

Here is the [codepen for demo](https://codepen.io/Pragatheeswaran/pen/poJKWYg)
This demo is changed from the [actual demo from the official page](https://www.amcharts.com/docs/v4/tutorials/multi-series-shared-tooltip-with-colored-bullets/)

**Comment by martynasma** [comment]
Brackets are special characters used for in-line formatting of values, so they can't be used as a reference in curly brackets.

If you do not control the naming of data fields, you may just escape them by replacing to some other character like an underscore. The following will work:

```JavaScript
{
  'date': new Date(2018, 0, 1),
  'value': 450,
  'value2': 362,
  'value3__': 699
}
```

**Comment by pragatheeswarans** [comment]
Thanks for responding. I can see from [the docs for Formatting Strings](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/) that square brackets `[]` are used for formatting. Can you point me to the docs where paranthesis `()` is used for inline formatting?

Also the angle brackets `<>` also don't work in this example.

**Comment by martynasma** [comment]
Sure:
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/#Overriding_format
