### ISSUE TITLE
date grid line issues

### ISSUE THREAD

**Issue by a30000329** [amcharts/amcharts4#2262]
Please use [this link](https://codepen.io/alexfan/pen/BayvVgB?editors=0011) for issue recreation. Issues found:

- vertical grid line misalignment
when hover to one data point say 6am, the hover line in red does not align with 06AM label line in blue
![image](https://user-images.githubusercontent.com/46702190/77119613-ee0bc000-6a8a-11ea-9ca2-31b84adffd48.png)

**Comment by martynasma** [comment]
Please see this: #2210

**Comment by a30000329** [comment]
Hi, thanks for your solution. could you have a look at my other questions as well? Thanks

**Comment by martynasma** [comment]
> Hi, thanks for your solution. could you have a look at my other questions as well? Thanks

Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
