### ISSUE TITLE
XYChart categoryAxis tooltip has wrong background alignment

### ISSUE THREAD

**Issue by brjaenu** [amcharts/amcharts4#2263]
Hello

Yesterday I've created this [stackoverflow-issue](https://stackoverflow.com/questions/60725203/amcharts-categoryaxis-tooltip-has-wrong-background-alignment) . 
I would like to have a AmCharts4 ganttchart with category-tooltips. Those tooltips should display the category-title and a description, which i receive from the chartDataSet.
Unfortunately the background of the tooltip swaps to the left:
![gantt-nok](https://user-images.githubusercontent.com/62385581/77071625-aa627900-69ec-11ea-80be-86a5f2f18752.png)

The category-axis-configs looks like this:
```
var categoryAxis = chart.yAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "category";
categoryAxis.renderer.labels.template.tooltipText = '[bold]{category}[/]\n{categoryDesc}';
categoryAxis.tooltip.align = 'right';
categoryAxis.tooltip.contentAlign = 'right';
categoryAxis.tooltip.background.opacity = 0.7;
categoryAxis.tooltip.maxWidth = 200;
categoryAxis.tooltip.label.wrap = true;
categoryAxis.cursorTooltipEnabled = false;
```
Code-Pen-Link: [Demo](https://jsfiddle.net/L7cp1bw2/4/)

**Comment by martynasma** [comment]
Well, axis has own logic and set up for tooltips. To avoid that, it's simpler to create a separate Tooltip instance for labels:

```
categoryAxis.renderer.labels.template.tooltip = new am4core.Tooltip();
```

**Comment by brjaenu** [comment]
If i create a tooltip-instance for labels, the problem is still there: [Demo](https://jsfiddle.net/1jsy36ea/)
After I hovered the 2nd time over the label it aligns to the center and the text is partially covered and not readable.

**Comment by martynasma** [comment]
Indeed. We'll need to look into this. Will keep you posted.

**Comment by martynasma** [comment]
OK, seems that setting bounds and `cloneTooltip = false` fixes the issue:

https://jsfiddle.net/qat6ynjp/
