### ISSUE TITLE
Map Marker with different colors

### ISSUE THREAD

**Issue by phane24** [amcharts/amcharts4#2265]
i am mapmarkers as images , but wen i tried to add diiferent colors for different data it is not working....is there any way to add different colors to the map markers ??? please help

i already tried using the svg path but in that i am unable to find the svg path of the image .

**Comment by martynasma** [comment]
The only way to apply color to markers via data is to create them as `Sprite` elements and set their `path` property. This way they will be able to inherit color set via `propertyFields`.

There's a tutorial and live demo here:
https://www.amcharts.com/docs/v4/tutorials/using-actual-images-in-mapimageseries/#Using_SVG_paths

It means you will need to extract path from your SVG images. You can't use whole standalone SVG image file.

**Comment by phane24** [comment]
yeah that is okay....is there any way to write text on those markers ????

**Comment by martynasma** [comment]
Nope. To write text add `Label` elements to the `MapImageSeries`.

**Comment by phane24** [comment]
is there any way to override the svg attribute of transform in amcharts

**Comment by martynasma** [comment]
> is there any way to override the svg attribute of transform in amcharts

Not sure what you mean there. Is this still about markers?

**Comment by phane24** [comment]
Not sure what you mean there. Is this still about markers?

yes

**Comment by martynasma** [comment]
Can you explain what you're trying to achieve?

**Comment by vividtahir** [comment]
how can give **multiple colors** in different **countries**
