### ISSUE TITLE
question : How can I draw weekly type charts like other charts?

### ISSUE THREAD

**Issue by uckhj** [amcharts/amcharts4#2266]
I use graphs in months, weeks, days, and minutes as needed using DateAxis.
And I want to be labeled where the data is, and I want it to be placed between the grids like any other chart.
If it is not possible, I would like to draw a graph of the date every 7 days, but if you know how, please reply.

![chart1](https://user-images.githubusercontent.com/42442833/77152774-ef190d80-6adb-11ea-986c-7311c4152f6b.png)
![chart2](https://user-images.githubusercontent.com/42442833/77152777-f04a3a80-6adb-11ea-8b07-082ccf4671cf.png)
![chart3](https://user-images.githubusercontent.com/42442833/77153542-45d31700-6add-11ea-97bd-4eaa4878bce7.png)

**Comment by martynasma** [comment]
If it's about position of the labels, please take a look here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis

**Comment by uckhj** [comment]
> If it's about position of the labels, please take a look here:
> https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis

Thank you for your reply.
I tried to move the label. However, if you look at the screenshot, the date of the data is 2020-01-01 but the date of the label is different, so the method was not available.

**Comment by martynasma** [comment]
Can you post your chart online? E.g. on CodePen?

**Comment by uckhj** [comment]
> Can you post your chart online? E.g. on CodePen?
Thank you for your reply
here is example code

https://codepen.io/uckhj/pen/OJVBymr

**Comment by martynasma** [comment]
Thanks.

Since you have a weekly data you probably want to set `baseInterval` to that, so that grid/label is placed every week. You also may use label's `location` to position label in the middle:

```
dateAxis.renderer.labels.template.location = 0.5;
dateAxis.baseInterval = {
  timeUnit: "week",
  count: 1
};
```

**Comment by uckhj** [comment]
> Thanks.
> 
> Since you have a weekly data you probably want to set `baseInterval` to that, so that grid/label is placed every week. You also may use label's `location` to position label in the middle:
> 
> ```
> dateAxis.renderer.labels.template.location = 0.5;
> dateAxis.baseInterval = {
>   timeUnit: "week",
>   count: 1
> };
> ```

thanx.

If I want, can I not use the Week type even if the data comes in every 7 days?
or can I remove(or block?) the Week type?

**Comment by martynasma** [comment]
I'm not sure I follow. Why would you want to provide incorrect data granularity to the chart?

**Comment by uckhj** [comment]
> I'm not sure I follow. Why would you want to provide incorrect data granularity to the chart?

If only the label is moved, the date of the actual data and the date of the label are different, which is likely to cause visual confusion.
However, I solved the problem by processing only the week type chart as category Axis and outputting the string as it is.

thanx for your help :)
