### ISSUE TITLE
How to add different class name on each categoryaxis？

### ISSUE THREAD

**Issue by msaus** [amcharts/amcharts4#2267]
Hi,

I want to add different class name for each categoryaxi and make it text link or normal text by css.

I know that I can add class name like following.

`am4core.options.autoSetClassName = true;`

But, this one dose not allow me to specify  class name.

Do you have any suggestions?

I have very similar graph like following.

https://www.amcharts.com/demos/divergent-stacked-bars/

Regards,

**Comment by martynasma** [comment]
You can set an `id` of your axis, e.g:

```
categoryAxis.id = "myAxis";
```

Together with enabling `autoSetClassName` it will set class names with custom ids on axis, e.g.: `amcharts-Sprite-group amcharts-Container-group amcharts-Component-group amcharts-Axis-group amcharts-CategoryAxis-group amcharts-myAxis`
