### ISSUE TITLE
WordCloud invalid regexp error

### ISSUE THREAD

**Issue by tjk911** [amcharts/amcharts4#2268]
Hey folks - I'm getting an invalid regexp error with the wordcloud library. 

When I double check the plugin cdn link (https://www.amcharts.com/lib/4/plugins/wordCloud.js), I see this

``this.dataFields.value="value";var t="A-Za-zÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-ËË†-Ë‘Ë -Ë¤Ë¬Ë®Í°-Í´Í¶-Í·Íº-Í½Î†Îˆ-ÎŠÎŒÎŽ-Î¡Î£-ÏµÏ·-ÒÒŠ-Ô£Ô±-Õ–Õ™Õ¡-Ö‡×-×ª×°-×²Ø¡-ÙŠÙ®-Ù¯Ù±-Û“Û•Û¥-Û¦Û®-Û¯Ûº-Û¼Û¿ÜÜ’-Ü¯Ý-Þ¥Þ±ßŠ-ßªß´-ßµßºà¤„-à¤¹à¤½à¥à¥˜-à¥¡à¥±-à¥²à¥»-à¥¿à¦…-à¦Œà¦-à¦à¦“-à¦¨à¦ª-à¦°à¦²à¦¶-à¦¹à¦½à§Žà§œ-à§à§Ÿ-à§¡à§°-à§±à¨…-à¨Šà¨-à¨à¨“-à¨¨à¨ª-à¨°à¨²-à¨³à¨µ-à¨¶à¨¸-à¨¹à©™-à©œà©žà©²-à©´àª…-àªàª-àª‘àª“-àª¨àªª-àª°àª²-àª³àªµ-àª¹àª½à«à« -à«¡à¬…-à¬Œà¬-à¬à¬“-à¬¨à¬ª-à¬°à¬²-à¬³à¬µ-à¬¹à¬½à­œ-à­à­Ÿ-à­¡à­±à®ƒà®…-à®Šà®Ž-à®à®’-à®•à®™-à®šà®œà®ž-à®Ÿà®£-à®¤à®¨-à®ªà®®-à®¹à¯à°…-à°Œà°Ž-à°à°’-à°¨à°ª-à°³à°µ-à°¹à°½à±˜-à±™à± -à±¡à²…-à²Œà²Ž-à²à²’-à²¨à²ª-à²³à²µ-à²¹à²½à³žà³ -à³¡à´…-à´Œà´Ž-à´à´’-à´¨à´ª-à´¹à´½àµ -àµ¡àµº-àµ¿à¶…-à¶–à¶š-à¶±à¶³-à¶»à¶½à·€-à·†à¸-à¸°à¸²-à¸³à¹€-à¹†àº-àº‚àº„àº‡-àºˆàºŠàºàº”-àº—àº™-àºŸàº¡-àº£àº¥àº§àºª-àº«àº­-àº°àº²-àº³àº½à»€-à»„à»†à»œ-à»à¼€à½€-à½‡à½‰-à½¬à¾ˆ-à¾‹á€€-á€ªá€¿á-á•áš-áá¡á¥-á¦á®-á°áµ-á‚á‚Žá‚ -áƒ…áƒ-áƒºáƒ¼á„€-á…™á…Ÿ-á†¢á†¨-á‡¹áˆ€-á‰ˆá‰Š-á‰á‰-á‰–á‰˜á‰š-á‰á‰ -áŠˆáŠŠ-áŠáŠ-áŠ°áŠ²-áŠµáŠ¸-áŠ¾á‹€á‹‚-á‹…á‹ˆ-á‹–á‹˜-áŒáŒ’-áŒ•áŒ˜-ášáŽ€-áŽáŽ -á´á-á™¬á™¯-á™¶áš-áššáš -á›ªá›®-á›°áœ€-áœŒáœŽ-áœ‘áœ -áœ±á€-á‘á -á¬á®-á°áž€-áž³áŸ—áŸœá  -á¡·á¢€-á¢¨á¢ªá¤€-á¤œá¥-á¥­á¥°-á¥´á¦€-á¦©á§-á§‡á¨€-á¨–á¬…-á¬³á­…-á­‹á®ƒ-á® á®®-á®¯á°€-á°£á±-á±á±š-á±½á´€-á¶¿á¸€-á¼•á¼˜-á¼á¼ -á½…á½ˆ-á½á½-á½—á½™á½›á½á½Ÿ-á½½á¾€-á¾´á¾¶-á¾¼á¾¾á¿‚-á¿„á¿†-á¿Œá¿-á¿“á¿–-á¿›á¿ -á¿¬á¿²-á¿´á¿¶-á¿¼â±â¿â‚-â‚”â„‚â„‡â„Š-â„“â„•â„™-â„â„¤â„¦â„¨â„ª-â„­â„¯-â„¹â„¼-â„¿â……-â…‰â…Žâ… -â†ˆâ°€-â°®â°°-â±žâ± -â±¯â±±-â±½â²€-â³¤â´€-â´¥â´°-âµ¥âµ¯â¶€-â¶–â¶ -â¶¦â¶¨-â¶®â¶°-â¶¶â¶¸-â¶¾â·€-â·†â·ˆ-â·Žâ·-â·–â·˜-â·žâ¸¯ã€…-ã€‡ã€¡-ã€©ã€±-ã€µã€¸-ã€¼ã-ã‚–ã‚-ã‚Ÿã‚¡-ãƒºãƒ¼-ãƒ¿ã„…-ã„­ã„±-ã†Žã† -ã†·ã‡°-ã‡¿ã€ä¶µä¸€é¿ƒê€€-ê’Œê”€-ê˜Œê˜-ê˜Ÿê˜ª-ê˜«ê™€-ê™Ÿê™¢-ê™®ê™¿-êš—êœ—-êœŸêœ¢-êžˆêž‹-êžŒêŸ»-ê ê ƒ-ê …ê ‡-ê Šê Œ-ê ¢ê¡€-ê¡³ê¢‚-ê¢³ê¤Š-ê¤¥ê¤°-ê¥†ê¨€-ê¨¨ê©€-ê©‚ê©„-ê©‹ê°€-íž£ï¤€-ï¨­ï¨°-ï©ªï©°-ï«™ï¬€-ï¬†ï¬“-ï¬—ï¬ï¬Ÿ-ï¬¨ï¬ª-ï¬¶ï¬¸-ï¬¼ï¬¾ï­€-ï­ï­ƒ-ï­„ï­†-ï®±ï¯“-ï´½ïµ-ï¶ï¶’-ï·‡ï·°-ï·»ï¹°-ï¹´ï¹¶-ï»¼ï¼¡-ï¼ºï½-ï½šï½¦-ï¾¾ï¿‚-ï¿‡ï¿Š-ï¿ï¿’-ï¿—ï¿š-ï¿œ0-9@+"``

**Comment by tjk911** [comment]
Hmm, I'm not sure this is the issue at all. I'm cloning the demos and they're all throwing me an invalid regexp error. 

``Uncaught SyntaxError: Invalid regular expression: /([A-Za-zÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-ËË†-Ë‘Ë -Ë¤Ë¬Ë®Í°-Í´Í¶-Í·Íº-Í½Î†Îˆ-ÎŠÎŒÎŽ-Î¡Î£-ÏµÏ·-ÒÒŠ-Ô£Ô±-Õ–Õ™Õ¡-Ö‡×-×ª×°-×²Ø¡-ÙŠÙ®-Ù¯Ù±-Û“Û•Û¥-Û¦Û®-Û¯Ûº-Û¼Û¿ÜÜ’-Ü¯Ý-Þ¥Þ±ßŠ-ßªß´-ßµßºà¤„-à¤¹à¤½à¥à¥˜-à¥¡à¥±-à¥²à¥»-à¥¿à¦…-à¦Œà¦-à¦à¦“-à¦¨à¦ª-à¦°à¦²à¦¶-à¦¹à¦½à§Žà§œ-à§à§Ÿ-à§¡à§°-à§±à¨…-à¨Šà¨-à¨à¨“-à¨¨à¨ª-à¨°à¨²-à¨³à¨µ-à¨¶à¨¸-à¨¹à©™-à©œà©žà©²-à©´àª…-àªàª-àª‘àª“-àª¨àªª-àª°àª²-àª³àªµ-àª¹àª½à«à« -à«¡à¬…-à¬Œà¬-à¬à¬“-à¬¨à¬ª-à¬°à¬²-à¬³à¬µ-à¬¹à¬½à­œ-à­à­Ÿ-à­¡à­±à®ƒà®…-à®Šà®Ž-à®à®’-à®•à®™-à®šà®œà®ž-à®Ÿà®£-à®¤à®¨-à®ªà®®-à®¹à¯à°…-à°Œà°Ž-à°à°’-à°¨à°ª-à°³à°µ-à°¹à°½à±˜-à±™à± -à±¡à²…-à²Œà²Ž-à²à²’-à²¨à²ª-à²³à²µ-à²¹à²½à³žà³ -à³¡à´…-à´Œà´Ž-à´à´’-à´¨à´ª-à´¹à´½àµ -àµ¡àµº-àµ¿à¶…-à¶–à¶š-à¶±à¶³-à¶»à¶½à·€-à·†à¸-à¸°à¸²-à¸³à¹€-à¹†àº-àº‚àº„àº‡-àºˆàºŠàºàº”-àº—àº™-àºŸàº¡-àº£àº¥àº§àºª-àº«àº­-àº°àº²-àº³àº½à»€-à»„à»†à»œ-à»à¼€à½€-à½‡à½‰-à½¬à¾ˆ-à¾‹á€€-á€ªá€¿á-á•áš-áá¡á¥-á¦á®-á°áµ-á‚á‚Žá‚ -áƒ…áƒ-áƒºáƒ¼á„€-á…™á…Ÿ-á†¢á†¨-á‡¹áˆ€-á‰ˆá‰Š-á‰á‰-á‰–á‰˜á‰š-á‰á‰ -áŠˆáŠŠ-áŠáŠ-áŠ°áŠ²-áŠµáŠ¸-áŠ¾á‹€á‹‚-á‹…á‹ˆ-á‹–á‹˜-áŒáŒ’-áŒ•áŒ˜-ášáŽ€-áŽáŽ -á´á-á™¬á™¯-á™¶áš-áššáš -á›ªá›®-á›°áœ€-áœŒáœŽ-áœ‘áœ -áœ±á€-á‘á -á¬á®-á°áž€-áž³áŸ—áŸœá  -á¡·á¢€-á¢¨á¢ªá¤€-á¤œá¥-á¥­á¥°-á¥´á¦€-á¦©á§-á§‡á¨€-á¨–á¬…-á¬³á­…-á­‹á®ƒ-á® á®®-á®¯á°€-á°£á±-á±á±š-á±½á´€-á¶¿á¸€-á¼•á¼˜-á¼á¼ -á½…á½ˆ-á½á½-á½—á½™á½›á½á½Ÿ-á½½á¾€-á¾´á¾¶-á¾¼á¾¾á¿‚-á¿„á¿†-á¿Œá¿-á¿“á¿–-á¿›á¿ -á¿¬á¿²-á¿´á¿¶-á¿¼â±â¿â‚-â‚”â„‚â„‡â„Š-â„“â„•â„™-â„â„¤â„¦â„¨â„ª-â„­â„¯-â„¹â„¼-â„¿â……-â…‰â…Žâ… -â†ˆâ°€-â°®â°°-â±žâ± -â±¯â±±-â±½â²€-â³¤â´€-â´¥â´°-âµ¥âµ¯â¶€-â¶–â¶ -â¶¦â¶¨-â¶®â¶°-â¶¶â¶¸-â¶¾â·€-â·†â·ˆ-â·Žâ·-â·–â·˜-â·žâ¸¯ã€…-ã€‡ã€¡-ã€©ã€±-ã€µã€¸-ã€¼ã-ã‚–ã‚-ã‚Ÿã‚¡-ãƒºãƒ¼-ãƒ¿ã„…-ã„­ã„±-ã†Žã† -ã†·ã‡°-ã‡¿ã€ä¶µä¸€é¿ƒê€€-ê’Œê”€-ê˜Œê˜-ê˜Ÿê˜ª-ê˜«ê™€-ê™Ÿê™¢-ê™®ê™¿-êš—êœ—-êœŸêœ¢-êžˆêž‹-êžŒêŸ»-ê ê ƒ-ê …ê ‡-ê Šê Œ-ê ¢ê¡€-ê¡³ê¢‚-ê¢³ê¤Š-ê¤¥ê¤°-ê¥†ê¨€-ê¨¨ê©€-ê©‚ê©„-ê©‹ê°€-íž£ï¤€-ï¨­ï¨°-ï©ªï©°-ï«™ï¬€-ï¬†ï¬“-ï¬—ï¬ï¬Ÿ-ï¬¨ï¬ª-ï¬¶ï¬¸-ï¬¼ï¬¾ï­€-ï­ï­ƒ-ï­„ï­†-ï®±ï¯“-ï´½ïµ-ï¶ï¶’-ï·‡ï·°-ï·»ï¹°-ï¹´ï¹¶-ï»¼ï¼¡-ï¼ºï½-ï½šï½¦-ï¾¾ï¿‚-ï¿‡ï¿Š-ï¿ï¿’-ï¿—ï¿š-ï¿œ0-9@+]+[-A-Za-zÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-ËË†-Ë‘Ë -Ë¤Ë¬Ë®Í°-Í´Í¶-Í·Íº-Í½Î†Îˆ-ÎŠÎŒÎŽ-Î¡Î£-ÏµÏ·-ÒÒŠ-Ô£Ô±-Õ–Õ™Õ¡-Ö‡×-×ª×°-×²Ø¡-ÙŠÙ®-Ù¯Ù±-Û“Û•Û¥-Û¦Û®-Û¯Ûº-Û¼Û¿ÜÜ’-Ü¯Ý-Þ¥Þ±ßŠ-ßªß´-ßµßºà¤„-à¤¹à¤½à¥à¥˜-à¥¡à¥±-à¥²à¥»-à¥¿à¦…-à¦Œà¦-à¦à¦“-à¦¨à¦ª-à¦°à¦²à¦¶-à¦¹à¦½à§Žà§œ-à§à§Ÿ-à§¡à§°-à§±à¨…-à¨Šà¨-à¨à¨“-à¨¨à¨ª-à¨°à¨²-à¨³à¨µ-à¨¶à¨¸-à¨¹à©™-à©œà©žà©²-à©´àª…-àªàª-àª‘àª“-àª¨àªª-àª°àª²-àª³àªµ-àª¹àª½à«à« -à«¡à¬…-à¬Œà¬-à¬à¬“-à¬¨à¬ª-à¬°à¬²-à¬³à¬µ-à¬¹à¬½à­œ-à­à­Ÿ-à­¡à­±à®ƒà®…-à®Šà®Ž-à®à®’-à®•à®™-à®šà®œà®ž-à®Ÿà®£-à®¤à®¨-à®ªà®®-à®¹à¯à°…-à°Œà°Ž-à°à°’-à°¨à°ª-à°³à°µ-à°¹à°½à±˜-à±™à± -à±¡à²…-à²Œà²Ž-à²à²’-à²¨à²ª-à²³à²µ-à²¹à²½à³žà³ -à³¡à´…-à´Œà´Ž-à´à´’-à´¨à´ª-à´¹à´½àµ -àµ¡àµº-àµ¿à¶…-à¶–à¶š-à¶±à¶³-à¶»à¶½à·€-à·†à¸-à¸°à¸²-à¸³à¹€-à¹†àº-àº‚àº„àº‡-àºˆàºŠàºàº”-àº—àº™-àºŸàº¡-àº£àº¥àº§àºª-àº«àº­-àº°àº²-àº³àº½à»€-à»„à»†à»œ-à»à¼€à½€-à½‡à½‰-à½¬à¾ˆ-à¾‹á€€-á€ªá€¿á-á•áš-áá¡á¥-á¦á®-á°áµ-á‚á‚Žá‚ -áƒ…áƒ-áƒºáƒ¼á„€-á…™á…Ÿ-á†¢á†¨-á‡¹áˆ€-á‰ˆá‰Š-á‰á‰-á‰–á‰˜á‰š-á‰á‰ -áŠˆáŠŠ-áŠáŠ-áŠ°áŠ²-áŠµáŠ¸-áŠ¾á‹€á‹‚-á‹…á‹ˆ-á‹–á‹˜-áŒáŒ’-áŒ•áŒ˜-ášáŽ€-áŽáŽ -á´á-á™¬á™¯-á™¶áš-áššáš -á›ªá›®-á›°áœ€-áœŒáœŽ-áœ‘áœ -áœ±á€-á‘á -á¬á®-á°áž€-áž³áŸ—áŸœá  -á¡·á¢€-á¢¨á¢ªá¤€-á¤œá¥-á¥­á¥°-á¥´á¦€-á¦©á§-á§‡á¨€-á¨–á¬…-á¬³á­…-á­‹á®ƒ-á® á®®-á®¯á°€-á°£á±-á±á±š-á±½á´€-á¶¿á¸€-á¼•á¼˜-á¼á¼ -á½…á½ˆ-á½á½-á½—á½™á½›á½á½Ÿ-á½½á¾€-á¾´á¾¶-á¾¼á¾¾á¿‚-á¿„á¿†-á¿Œá¿-á¿“á¿–-á¿›á¿ -á¿¬á¿²-á¿´á¿¶-á¿¼â±â¿â‚-â‚”â„‚â„‡â„Š-â„“â„•â„™-â„â„¤â„¦â„¨â„ª-â„­â„¯-â„¹â„¼-â„¿â……-â…‰â…Žâ… -â†ˆâ°€-â°®â°°-â±žâ± -â±¯â±±-â±½â²€-â³¤â´€-â´¥â´°-âµ¥âµ¯â¶€-â¶–â¶ -â¶¦â¶¨-â¶®â¶°-â¶¶â¶¸-â¶¾â·€-â·†â·ˆ-â·Žâ·-â·–â·˜-â·žâ¸¯ã€…-ã€‡ã€¡-ã€©ã€±-ã€µã€¸-ã€¼ã-ã‚–ã‚-ã‚Ÿã‚¡-ãƒºãƒ¼-ãƒ¿ã„…-ã„­ã„±-ã†Žã† -ã†·ã‡°-ã‡¿ã€ä¶µä¸€é¿ƒê€€-ê’Œê”€-ê˜Œê˜-ê˜Ÿê˜ª-ê˜«ê™€-ê™Ÿê™¢-ê™®ê™¿-êš—êœ—-êœŸêœ¢-êžˆêž‹-êžŒêŸ»-ê ê ƒ-ê …ê ‡-ê Šê Œ-ê ¢ê¡€-ê¡³ê¢‚-ê¢³ê¤Š-ê¤¥ê¤°-ê¥†ê¨€-ê¨¨ê©€-ê©‚ê©„-ê©‹ê°€-íž£ï¤€-ï¨­ï¨°-ï©ªï©°-ï«™ï¬€-ï¬†ï¬“-ï¬—ï¬ï¬Ÿ-ï¬¨ï¬ª-ï¬¶ï¬¸-ï¬¼ï¬¾ï­€-ï­ï­ƒ-ï­„ï­†-ï®±ï¯“-ï´½ïµ-ï¶ï¶’-ï·‡ï·°-ï·»ï¹°-ï¹´ï¹¶-ï»¼ï¼¡-ï¼ºï½-ï½šï½¦-ï¾¾ï¿‚-ï¿‡ï¿Š-ï¿ï¿’-ï¿—ï¿š-ï¿œ0-9@+]*[A-Za-zÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-ËË†-Ë‘Ë -Ë¤Ë¬Ë®Í°-Í´Í¶-Í·Íº-Í½Î†Îˆ-ÎŠÎŒÎŽ-Î¡Î£-ÏµÏ·-ÒÒŠ-Ô£Ô±-Õ–Õ™Õ¡-Ö‡×-×ª×°-×²Ø¡-ÙŠÙ®-Ù¯Ù±-Û“Û•Û¥-Û¦Û®-Û¯Ûº-Û¼Û¿ÜÜ’-Ü¯Ý-Þ¥Þ±ßŠ-ßªß´-ßµßºà¤„-à¤¹à¤½à¥à¥˜-à¥¡à¥±-à¥²à¥»-à¥¿à¦…-à¦Œà¦-à¦à¦“-à¦¨à¦ª-à¦°à¦²à¦¶-à¦¹à¦½à§Žà§œ-à§à§Ÿ-à§¡à§°-à§±à¨…-à¨Šà¨-à¨à¨“-à¨¨à¨ª-à¨°à¨²-à¨³à¨µ-à¨¶à¨¸-à¨¹à©™-à©œà©žà©²-à©´àª…-àªàª-àª‘àª“-àª¨àªª-àª°àª²-àª³àªµ-àª¹àª½à«à« -à«¡à¬…-à¬Œà¬-à¬à¬“-à¬¨à¬ª-à¬°à¬²-à¬³à¬µ-à¬¹à¬½à­œ-à­à­Ÿ-à­¡à­±à®ƒà®…-à®Šà®Ž-à®à®’-à®•à®™-à®šà®œà®ž-à®Ÿà®£-à®¤à®¨-à®ªà®®-à®¹à¯à°…-à°Œà°Ž-à°à°’-à°¨à°ª-à°³à°µ-à°¹à°½à±˜-à±™à± -à±¡à²…-à²Œà²Ž-à²à²’-à²¨à²ª-à²³à²µ-à²¹à²½à³žà³ -à³¡à´…-à´Œà´Ž-à´à´’-à´¨à´ª-à´¹à´½àµ -àµ¡àµº-àµ¿à¶…-à¶–à¶š-à¶±à¶³-à¶»à¶½à·€-à·†à¸-à¸°à¸²-à¸³à¹€-à¹†àº-àº‚àº„àº‡-àºˆàºŠàºàº”-àº—àº™-àºŸàº¡-àº£àº¥àº§àºª-àº«àº­-àº°àº²-àº³àº½à»€-à»„à»†à»œ-à»à¼€à½€-à½‡à½‰-à½¬à¾ˆ-à¾‹á€€-á€ªá€¿á-á•áš-áá¡á¥-á¦á®-á°áµ-á‚á‚Žá‚ -áƒ…áƒ-áƒºáƒ¼á„€-á…™á…Ÿ-á†¢á†¨-á‡¹áˆ€-á‰ˆá‰Š-á‰á‰-á‰–á‰˜á‰š-á‰á‰ -áŠˆáŠŠ-áŠáŠ-áŠ°áŠ²-áŠµáŠ¸-áŠ¾á‹€á‹‚-á‹…á‹ˆ-á‹–á‹˜-áŒáŒ’-áŒ•áŒ˜-ášáŽ€-áŽáŽ -á´á-á™¬á™¯-á™¶áš-áššáš -á›ªá›®-á›°áœ€-áœŒáœŽ-áœ‘áœ -áœ±á€-á‘á -á¬á®-á°áž€-áž³áŸ—áŸœá  -á¡·á¢€-á¢¨á¢ªá¤€-á¤œá¥-á¥­á¥°-á¥´á¦€-á¦©á§-á§‡á¨€-á¨–á¬…-á¬³á­…-á­‹á®ƒ-á® á®®-á®¯á°€-á°£á±-á±á±š-á±½á´€-á¶¿á¸€-á¼•á¼˜-á¼á¼ -á½…á½ˆ-á½á½-á½—á½™á½›á½á½Ÿ-á½½á¾€-á¾´á¾¶-á¾¼á¾¾á¿‚-á¿„á¿†-á¿Œá¿-á¿“á¿–-á¿›á¿ -á¿¬á¿²-á¿´á¿¶-á¿¼â±â¿â‚-â‚”â„‚â„‡â„Š-â„“â„•â„™-â„â„¤â„¦â„¨â„ª-â„­â„¯-â„¹â„¼-â„¿â……-â…‰â…Žâ… -â†ˆâ°€-â°®â°°-â±žâ± -â±¯â±±-â±½â²€-â³¤â´€-â´¥â´°-âµ¥âµ¯â¶€-â¶–â¶ -â¶¦â¶¨-â¶®â¶°-â¶¶â¶¸-â¶¾â·€-â·†â·ˆ-â·Žâ·-â·–â·˜-â·žâ¸¯ã€…-ã€‡ã€¡-ã€©ã€±-ã€µã€¸-ã€¼ã-ã‚–ã‚-ã‚Ÿã‚¡-ãƒºãƒ¼-ãƒ¿ã„…-ã„­ã„±-ã†Žã† -ã†·ã‡°-ã‡¿ã€ä¶µä¸€é¿ƒê€€-ê’Œê”€-ê˜Œê˜-ê˜Ÿê˜ª-ê˜«ê™€-ê™Ÿê™¢-ê™®ê™¿-êš—êœ—-êœŸêœ¢-êžˆêž‹-êžŒêŸ»-ê ê ƒ-ê …ê ‡-ê Šê Œ-ê ¢ê¡€-ê¡³ê¢‚-ê¢³ê¤Š-ê¤¥ê¤°-ê¥†ê¨€-ê¨¨ê©€-ê©‚ê©„-ê©‹ê°€-íž£ï¤€-ï¨­ï¨°-ï©ªï©°-ï«™ï¬€-ï¬†ï¬“-ï¬—ï¬ï¬Ÿ-ï¬¨ï¬ª-ï¬¶ï¬¸-ï¬¼ï¬¾ï­€-ï­ï­ƒ-ï­„ï­†-ï®±ï¯“-ï´½ïµ-ï¶ï¶’-ï·‡ï·°-ï·»ï¹°-ï¹´ï¹¶-ï»¼ï¼¡-ï¼ºï½-ï½šï½¦-ï¾¾ï¿‚-ï¿‡ï¿Š-ï¿ï¿’-ï¿—ï¿š-ï¿œ0-9@+]+)|([A-Za-zÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-ËË†-Ë‘Ë -Ë¤Ë¬Ë®Í°-Í´Í¶-Í·Íº-Í½Î†Îˆ-ÎŠÎŒÎŽ-Î¡Î£-ÏµÏ·-ÒÒŠ-Ô£Ô±-Õ–Õ™Õ¡-Ö‡×-×ª×°-×²Ø¡-ÙŠÙ®-Ù¯Ù±-Û“Û•Û¥-Û¦Û®-Û¯Ûº-Û¼Û¿ÜÜ’-Ü¯Ý-Þ¥Þ±ßŠ-ßªß´-ßµßºà¤„-à¤¹à¤½à¥à¥˜-à¥¡à¥±-à¥²à¥»-à¥¿à¦…-à¦Œà¦-à¦à¦“-à¦¨à¦ª-à¦°à¦²à¦¶-à¦¹à¦½à§Žà§œ-à§à§Ÿ-à§¡à§°-à§±à¨…-à¨Šà¨-à¨à¨“-à¨¨à¨ª-à¨°à¨²-à¨³à¨µ-à¨¶à¨¸-à¨¹à©™-à©œà©žà©²-à©´àª…-àªàª-àª‘àª“-àª¨àªª-àª°àª²-àª³àªµ-àª¹àª½à«à« -à«¡à¬…-à¬Œà¬-à¬à¬“-à¬¨à¬ª-à¬°à¬²-à¬³à¬µ-à¬¹à¬½à­œ-à­à­Ÿ-à­¡à­±à®ƒà®…-à®Šà®Ž-à®à®’-à®•à®™-à®šà®œà®ž-à®Ÿà®£-à®¤à®¨-à®ªà®®-à®¹à¯à°…-à°Œà°Ž-à°à°’-à°¨à°ª-à°³à°µ-à°¹à°½à±˜-à±™à± -à±¡à²…-à²Œà²Ž-à²à²’-à²¨à²ª-à²³à²µ-à²¹à²½à³žà³ -à³¡à´…-à´Œà´Ž-à´à´’-à´¨à´ª-à´¹à´½àµ -àµ¡àµº-àµ¿à¶…-à¶–à¶š-à¶±à¶³-à¶»à¶½à·€-à·†à¸-à¸°à¸²-à¸³à¹€-à¹†àº-àº‚àº„àº‡-àºˆàºŠàºàº”-àº—àº™-àºŸàº¡-àº£àº¥àº§àºª-àº«àº­-àº°àº²-àº³àº½à»€-à»„à»†à»œ-à»à¼€à½€-à½‡à½‰-à½¬à¾ˆ-à¾‹á€€-á€ªá€¿á-á•áš-áá¡á¥-á¦á®-á°áµ-á‚á‚Žá‚ -áƒ…áƒ-áƒºáƒ¼á„€-á…™á…Ÿ-á†¢á†¨-á‡¹áˆ€-á‰ˆá‰Š-á‰á‰-á‰–á‰˜á‰š-á‰á‰ -áŠˆáŠŠ-áŠáŠ-áŠ°áŠ²-áŠµáŠ¸-áŠ¾á‹€á‹‚-á‹…á‹ˆ-á‹–á‹˜-áŒáŒ’-áŒ•áŒ˜-ášáŽ€-áŽáŽ -á´á-á™¬á™¯-á™¶áš-áššáš -á›ªá›®-á›°áœ€-áœŒáœŽ-áœ‘áœ -áœ±á€-á‘á -á¬á®-á°áž€-áž³áŸ—áŸœá  -á¡·á¢€-á¢¨á¢ªá¤€-á¤œá¥-á¥­á¥°-á¥´á¦€-á¦©á§-á§‡á¨€-á¨–á¬…-á¬³á­…-á­‹á®ƒ-á® á®®-á®¯á°€-á°£á±-á±á±š-á±½á´€-á¶¿á¸€-á¼•á¼˜-á¼á¼ -á½…á½ˆ-á½á½-á½—á½™á½›á½á½Ÿ-á½½á¾€-á¾´á¾¶-á¾¼á¾¾á¿‚-á¿„á¿†-á¿Œá¿-á¿“á¿–-á¿›á¿ -á¿¬á¿²-á¿´á¿¶-á¿¼â±â¿â‚-â‚”â„‚â„‡â„Š-â„“â„•â„™-â„â„¤â„¦â„¨â„ª-â„­â„¯-â„¹â„¼-â„¿â……-â…‰â…Žâ… -â†ˆâ°€-â°®â°°-â±žâ± -â±¯â±±-â±½â²€-â³¤â´€-â´¥â´°-âµ¥âµ¯â¶€-â¶–â¶ -â¶¦â¶¨-â¶®â¶°-â¶¶â¶¸-â¶¾â·€-â·†â·ˆ-â·Žâ·-â·–â·˜-â·žâ¸¯ã€…-ã€‡ã€¡-ã€©ã€±-ã€µã€¸-ã€¼ã-ã‚–ã‚-ã‚Ÿã‚¡-ãƒºãƒ¼-ãƒ¿ã„…-ã„­ã„±-ã†Žã† -ã†·ã‡°-ã‡¿ã€ä¶µä¸€é¿ƒê€€-ê’Œê”€-ê˜Œê˜-ê˜Ÿê˜ª-ê˜«ê™€-ê™Ÿê™¢-ê™®ê™¿-êš—êœ—-êœŸêœ¢-êžˆêž‹-êžŒêŸ»-ê ê ƒ-ê …ê ‡-ê Šê Œ-ê ¢ê¡€-ê¡³ê¢‚-ê¢³ê¤Š-ê¤¥ê¤°-ê¥†ê¨€-ê¨¨ê©€-ê©‚ê©„-ê©‹ê°€-íž£ï¤€-ï¨­ï¨°-ï©ªï©°-ï«™ï¬€-ï¬†ï¬“-ï¬—ï¬ï¬Ÿ-ï¬¨ï¬ª-ï¬¶ï¬¸-ï¬¼ï¬¾ï­€-ï­ï­ƒ-ï­„ï­†-ï®±ï¯“-ï´½ïµ-ï¶ï¶’-ï·‡ï·°-ï·»ï¹°-ï¹´ï¹¶-ï»¼ï¼¡-ï¼ºï½-ï½šï½¦-ï¾¾ï¿‚-ï¿‡ï¿Š-ï¿ï¿’-ï¿—ï¿š-ï¿œ0-9@+]+)/: Range out of order in character class``

**Comment by martynasma** [comment]
Which demos are you getting errors on?

Does this happen in all browsers, or just particular one?

**Comment by tjk911** [comment]
I've tested this demo (https://www.amcharts.com/demos/word-cloud/) and a few others from here (https://www.amcharts.com/docs/v4/chart-types/wordcloud/). The error is happening in both Chrome and Safari (in incognito, plugins/addons turned off).

It could very well be an issue on my end - still troubleshooting.

**Comment by tjk911** [comment]
Y'know what - it's working now. I have no idea what happened/changed but I'm not seeing the error anymore. I'm sorry I wasted your time.
