### ISSUE TITLE
How to achieve multi-level grouping

### ISSUE THREAD

**Issue by DJLongZai** [amcharts/amcharts4#2270]
![p1](https://user-images.githubusercontent.com/24751427/77185679-c1988800-6b0c-11ea-8324-8e26591199c9.jpg)
![22](https://user-images.githubusercontent.com/24751427/77187188-0b826d80-6b0f-11ea-881a-c4f4f8376995.jpg)

**Comment by martynasma** [comment]
On that demo axis ranges are used to "group" categories. You can add as many of those as needed, including overlapping them. You can also us `dy` on labels to shift them downwards.

Demo:
https://www.amcharts.com/demos/grouped-and-sorted-columns/

More about axis ranges:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides

**Comment by DJLongZai** [comment]
Sorry, it still didn't happen. Can you write an example for me?
`let chart = am4core.create("amchart", am4charts.XYChart);
            var data1 = [
                {country:'china',production :'bicycle',color:'green',picre:1564},
                {country:'china',production :'bicycle',color:'yellow',picre:1564},
                {country:'china',production :'car',color:'yellow',picre:5463},
                {country:'china',production :'car',color:'green',picre:154324},
                {country:'USA',production :'bicycle',color:'green',picre:4158},
                {country:'USA',production :'bicycle',color:'yellow',picre:543543},
                {country:'USA',production :'car',color:'yellow',picre:4158},
            ];
            var datas =[]
            data1.forEach(e=>{
                datas.push(
                    { 
                        category: e.country + "_" + e.production,
                        realName: e.production,
                        category2:e.country + "_" + e.production+'_'+e.color,
                        realName2: e.color,
                        value: e.picre,
                        provider: e.country
                    }
                );
            })
            
            console.log(datas)
            // some extra padding for range labels
            chart.paddingBottom = 50;

            chart.cursor = new am4charts.XYCursor();
            chart.scrollbarX = new am4core.Scrollbar();

            // will use this to store colors of the same items
            var colors = {};

            var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
            categoryAxis.dataFields.category = "category";
            categoryAxis.renderer.minGridDistance = 60;
            categoryAxis.renderer.grid.template.location = 0;
            categoryAxis.dataItems.template.text = "{realName}";
            categoryAxis.adapter.add("tooltipText", function(tooltipText, target){
                return categoryAxis.tooltipDataItem.dataContext.realName;
            })

            var categoryAxis2 = chart.xAxes.push(new am4charts.CategoryAxis());
            categoryAxis2.dataFields.category = "category2";
            categoryAxis2.renderer.minGridDistance = 60;
            categoryAxis2.renderer.grid.template.location = 0;
            categoryAxis2.dataItems.template.text = "{realName2}";
            categoryAxis2.adapter.add("tooltipText", function(tooltipText, target){
                return categoryAxis2.tooltipDataItem.dataContext.realName2;
            })



            var rangeTemplate = categoryAxis.axisRanges.template;
            rangeTemplate.tick.disabled = false;
            rangeTemplate.tick.location = 0;
            rangeTemplate.tick.strokeOpacity = 0.6;
            rangeTemplate.tick.length = 60;
            rangeTemplate.grid.strokeOpacity = 0.5;
            rangeTemplate.label.tooltip = new am4core.Tooltip();
            rangeTemplate.label.tooltip.dy = -10;
            rangeTemplate.label.cloneTooltip = false;
            // create range (the additional label at the bottom)

            var range = categoryAxis.axisRanges.create();
            range.category = 'china_bicycle';
            range.endCategory = 'china_car';
            range.label.text = 'china';
            range.label.dy = 30;
            range.label.truncate = true;
            range.label.fontWeight = "bold";
            range.label.tooltipText = 'china';

            var range1 = categoryAxis.axisRanges.create();
            range1.category = 'USA_bicycle';
            range1.endCategory = 'USA_car';
            range1.label.text = 'USA';
            range1.label.dy = 30;
            range1.label.truncate = true;
            range1.label.fontWeight = "bold";
            range1.label.tooltipText = 'USA';

            var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis.tooltip.disabled = true;
            valueAxis.min = 0;

            // single column series for all data
            var columnSeries = chart.series.push(new am4charts.ColumnSeries());
            columnSeries.columns.template.width = am4core.percent(80);
            columnSeries.tooltipText = "{category2}: {realName2}, {valueY}";
            columnSeries.dataFields.categoryX = "category2";
            columnSeries.dataFields.valueY = "value";


            // fill adapter, here we save color value to colors object so that each time the item has the same name, the same color is used
            columnSeries.columns.template.adapter.add("fill", function(fill, target) {
                var name = target.dataItem.dataContext.realName;
                if (!colors[name]) {
                colors[name] = chart.colors.next();
                }
                target.stroke = colors[name];
                return colors[name];
            })

            ///// DATA
            var chartData = [];
            var lineSeriesData = [];

            chart.data = datas;`
Now:
![22](https://user-images.githubusercontent.com/24751427/77220920-ce09f880-6b7f-11ea-9d16-a6ffc47dcf0e.jpg)

Desired outcome：
![222](https://user-images.githubusercontent.com/24751427/77220930-fdb90080-6b7f-11ea-8312-0beacd194cc8.jpg)

**Comment by martynasma** [comment]
The tutorial I referred you to contains information about set start and end location of the axis range:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_locations

**Comment by DJLongZai** [comment]
> The tutorial I referred you to contains information about set start and end location of the axis range:
> https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_locations

The most step forward, thank you for your support。
``
` var range3 = categoryAxis.axisRanges.create();
            range3.category = 'china_bicycle_green';
            range3.endCategory = 'china_bicycle_yellow';
            range3.label.text = 'bicycle';
            range3.label.dy = 20;
            range3.label.truncate = true;
            range3.label.fontWeight = "bold";
            range3.label.tooltipText = 'bicycle';

            var range5 = categoryAxis.axisRanges.create();
            range5.category = 'china_car_yellow';
            range5.endCategory = 'china_car_green';
            range5.label.text = 'car';
            range5.label.dy = 30;
            range5.label.truncate = true;
            range5.label.fontWeight = "bold";
            range5.label.tooltipText = 'car';

            var range4 = categoryAxis.axisRanges.create();
            range4.category = 'USA_bicycle_green';
            range4.endCategory = 'USA_bicycle_yellow';
            range4.label.text = 'bicycle';
            range4.label.dy = 30;
            range4.label.truncate = true;
            range4.label.fontWeight = "bold";
            range4.label.tooltipText = 'bicycle';

            var range6 = categoryAxis.axisRanges.create();
            range6.category = 'USA_car_yellow';
            range6.endCategory = 'USA_car_green';
            range6.label.text = 'car';
            range6.label.dy = 30;
            range6.label.truncate = true;
            range6.label.fontWeight = "bold";
            range6.label.tooltipText = 'car';
            var range = categoryAxis.axisRanges.create();
            range.category = 'china_bicycle';
            range.endCategory = 'china_car';
            range.label.text = 'china';
            range.label.dy = 30;
            range.label.truncate = true;
            range.label.fontWeight = "bold";
            range.label.tooltipText = 'china';

            var range1 = categoryAxis.axisRanges.create();
            range1.category = 'USA_bicycle';
            range1.endCategory = 'USA_car';
            range1.label.text = 'USA';
            range1.label.dy = 30;
            range1.label.truncate = true;
            range1.label.fontWeight = "bold";
            range1.label.tooltipText = 'USA';`

![223](https://user-images.githubusercontent.com/24751427/77231790-1f45d680-6bd8-11ea-99df-be406a7195fc.jpg)
![224](https://user-images.githubusercontent.com/24751427/77231814-3f759580-6bd8-11ea-9a23-889ab3821dc5.jpg)

**Comment by DJLongZai** [comment]
Problem solved, thank you very much
