### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by trav-xeno** [amcharts/amcharts4#2273]
I have a map app that uses vuejs and allows the user to change the map projection. I get this error when the user changes the projection with data displayed on it. It seems related to being zoomed in and the amount of data being shown, but I am not a hundred percent sure though. 
console log 
TypeError: Cannot read property '0' of null
    at e.validatePosition (maps.js:1)
    at e._systemValidatePositions (core.js:1)
    at e._systemValidatePositions (core.js:1)
    at t.validatePositions (core.js:1)
    at core.js:1
    at core.js:1
    at l (core.js:1)
    at Object.Qkdp.e.each (core.js:1)
    at t.update (core.js:1)
    at core.js:1
core.js:1 TypeError: Cannot read property '0' of null
    at e.validatePosition (maps.js:1)
    at maps.js:1
    at core.js:1
    at core.js:1
    at Object.Wglt.e.each (core.js:1)
    at e.validate (maps.js:1)
    at e._systemUpdate (core.js:1)
    at e._systemUpdate (core.js:1)
    at core.js:1
    at core.js:1

//takes in string of select value  checks and redraws map 
          changeMap: function(str){
        
            if( str == "u"){
              this.chart.geodata = am4geodata_usaHigh;
            // Set projection
              this.chart.projection = new am4maps.projections.AlbersUsa();
            }else if(str == 'w'){
              this.chart.geodata = am4geodata_worldHigh;
              // Set projection
             this.chart.projection = new am4maps.projections.Miller();
            }

          },

    an example of my data 
    { svg":star,"name":"demo","address":"somewhere","city":"some where ","color": primarycolor,"country":"USA","latitude":"1.1 ","longitude":"-11.332 "},

Any suggestions? Is this my code or a bug in amcharts?

**Comment by martynasma** [comment]
I tried reproducing it here:
https://codepen.io/team/amcharts/pen/99d3a4f83bacb8e41c660653408e5196?editors=1000

Changing both geodata and projection works fine. So I assume it might have something to do with the data.

Feel free to fork and modify demo above to better reflect your setup and code so that issue can be reproduced.
