### ISSUE TITLE
How to load a particular legend in the !toggle state when loading a chart

### ISSUE THREAD

**Issue by smooth97** [amcharts/amcharts4#2274]
I want the last legend loaded without being selected. I'd appreciate it if you could tell me how
thank you :)

**Comment by martynasma** [comment]
If it's for series, check out here:
https://www.amcharts.com/docs/v4/concepts/series/#Pre_hiding_series

If it's for slice:
https://www.amcharts.com/docs/v4/tutorials/pre-hiding-pie-chart-slices/
