### ISSUE TITLE
Timeline chart is cropped

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#2275]
When dynamically adding a chart of timeline this happens with the latest version. This was ok 

I am not sure if this is known, I will try to track down the version that breaks this 

<img width="357" alt="Screenshot 2020-03-23 at 21 37 50" src="https://user-images.githubusercontent.com/1268723/77361039-cd738c80-6d4e-11ea-92bc-4f03c4c8a913.png">

**Comment by jimmykane** [comment]
All other charts work well.

**Comment by jimmykane** [comment]
Ok queue is. the issue here

**Comment by martynasma** [comment]
Are you fine with working with the `queue` disabled, or still would like to pursue this?

(gonna ask you for a CodePen for the latter ;)

**Comment by jimmykane** [comment]
I think I am fine :-p
