### ISSUE TITLE
grid line start and finish

### ISSUE THREAD

**Issue by a30000329** [amcharts/amcharts4#2278]
Please use [this link](https://codepen.io/alexfan/pen/BayvVgB?editors=0011) for issue recreation.

is there any way to achieve:
- vertical lines to start from the beginning like horizontal lines? 
basically I want to achieve this:
![image](https://user-images.githubusercontent.com/46702190/77039862-e86e9580-6a0a-11ea-9857-a517084b4d49.png)

**Comment by a30000329** [comment]
@martynasma separate issue created. thanks

**Comment by martynasma** [comment]
> vertical lines to start from the beginning like horizontal lines?

What do you mean? What is beginning? :)

P.S. please post unrelated questions separately. This is not a support forum.

**Comment by a30000329** [comment]
this is the version I got from my end:
![image](https://user-images.githubusercontent.com/46702190/77481211-4a018a80-6e77-11ea-994a-0d1a8cf04773.png)

and the version I want to achieve is already posted in this issue. If you compare, you will find the vertical grid lines and the time labels are starting from beginning til the end. That is what I mean. Can you please have a look?

**Comment by a30000329** [comment]
can I know where is the support forum? I am paid customer so hopefully I can raise a support ticket for these issues.

**Comment by martynasma** [comment]
If you have a support subscription, you're welcome to contact amCharts support at contact@amcharts.com.

As per your question, your CodePen does display find start and end, this is why it was confusing.

The grid/labels are displayed at set intervals. If the data starts at not such interval, the start label/grid won't be shown. The same goes end.

What you can do is to increase number of grid lines using `minGridDistance`:

```
dateAxis.renderer.minGridDistance = 30;
```

You also have other settings in your config like allowing grid only every 6 hours. So if you need more grid lines and labels, you'll need to revise that.

Finally, if you need to force a display of a start and end label, you can do so with axis ranges:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_labels

**Comment by a30000329** [comment]
Our intention was to still keep interval as 6 hours, but the label should start from first data point (left edge of graph) and finish at the last data point (right edge of graph). The reason is we are displaying last 24 hours data, so we want to always show the current time, for example 5:15pm on the right edge and yesterday 5pm as left edge label. It will give full 24 hr starting from right now backwards

**Comment by martynasma** [comment]
The only way to place grid/label at arbitrary times is to use axis range.
