### ISSUE TITLE
minPolylineStep option allowed for Map series ?

### ISSUE THREAD

**Issue by fredmef** [amcharts/amcharts4#2279]
Hi everybody,

is the option `am4core.options.minPolylineStep` impacts the Map series performances ?

Thanks,
Fred.

**Comment by zeroin** [comment]
No, it doesn't.

**Comment by fredmef** [comment]
Too bad...

So how can we improve map performance for MapLineSeries with a huge amount of data points ?

**Comment by martynasma** [comment]
Does using `precision` setting help?

https://www.amcharts.com/docs/v4/reference/mapline/#precision_property

**Comment by fredmef** [comment]
No, because I'd like to have the following behavior as for `minPolylineStep`.

> The beauty of this approach is that when user zooms in, more detail will start to emerge. This means you are losing the detail only on zoom levels that would make seeing the detail impossible, anyway.

**Comment by martynasma** [comment]
I'm sorry, bur there are no other settings that can be used to speed up performance of the lines.
