### ISSUE TITLE
Non gregorian calendar dateaxis

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2280]
How use non gregorian calendar (Hijri, Persian) in dateaxis.
I use moment for convert date.

**Comment by martynasma** [comment]
I'm afraid we do not have support for non-Gregorian calendars. There is also no plans on adding this support. Sorry.

**Comment by HASSANDL** [comment]
Please explain how add this option.

**Comment by martynasma** [comment]
I'm afraid I can't suggest anything, since as per my previous reply we do not support other calendars.

**Comment by matinwd** [comment]
Still has no plans for Jalali/Shamsi Calendars?
