### ISSUE TITLE
color of axis line

### ISSUE THREAD

**Issue by a30000329** [amcharts/amcharts4#2281]
Please use [this link](https://codepen.io/alexfan/pen/BayvVgB?editors=0011) for issue recreation.

is there any way to achieve:
- change the color of the axis line?
basically I want to achieve this:
![image](https://user-images.githubusercontent.com/46702190/77039862-e86e9580-6a0a-11ea-9857-a517084b4d49.png)

**Comment by martynasma** [comment]
Check this tutorial:
https://www.amcharts.com/docs/v4/concepts/axes/#The_axis_line

**Comment by a30000329** [comment]
Thank you, this works.
