### ISSUE TITLE
lower case am pm

### ISSUE THREAD

**Issue by a30000329** [amcharts/amcharts4#2282]
Please use [this link](https://codepen.io/alexfan/pen/BayvVgB?editors=0011) for issue recreation.

is there any way to achieve:
- use lower case am/pm
basically I want to achieve this:
![image](https://user-images.githubusercontent.com/46702190/77039862-e86e9580-6a0a-11ea-9857-a517084b4d49.png)

**Comment by martynasma** [comment]
Yes. You will have to modify language prompts for that, though:

```
chart.language.locale["AM"] = "am";
chart.language.locale["PM"] = "pm";
```

**Comment by martynasma** [comment]
For your convenience:
https://www.amcharts.com/docs/v4/tutorials/make-am-pm-prompts-lowercase-or-change-them/

**Comment by a30000329** [comment]
thanks, that works perfectly.
