### ISSUE TITLE
How to set z-index on permanent tooltips

### ISSUE THREAD

**Issue by lgerndt** [amcharts/amcharts4#2286]
Hi, trying to solve this overlap problem with zIndex.  The first tooltip is a "permanent" one via "alwaysShowTooltip".  The second one appears on hover and should be OVER the permanent one but is always behind.  I've tried various API's that look like they should work but to no avail.  How would you solve this?

![image](https://user-images.githubusercontent.com/1790016/77560482-ca75ba80-6e7a-11ea-96b3-d0505682fe14.png)

**Comment by zeroin** [comment]
Try setting `series.tooltip.zIndex = Infinity`. If this won't work, I will need a codepen of this situation in order to help.

**Comment by lgerndt** [comment]
Thanks but that didn't work.  Here's a [codepen](https://codepen.io/lgerndt/pen/ympXBJ).

**Comment by martynasma** [comment]
You might need to change the `zIndex` after series is initialized to ensure that series tooltip is above any individual tooltips that were created during initialization:

```
series.events.on("ready", function(ev) {
  ev.target.tooltip.zIndex = Infinity
});
```

**Comment by lgerndt** [comment]
didn't work.  Could you please modify the codepen if you have a solution?  Thanks!

**Comment by martynasma** [comment]
There ya go:
https://codepen.io/team/amcharts/pen/9b2427bdb8bb1a621722d8515370047c?editors=0010

**Comment by lgerndt** [comment]
ah!  That works, thank you!  That proves it can work, and I now have it working correctly in my application.  But now my problem is after chart is initialized and user clicks some other bar, then THAT bar should have the permanent tooltip.  When I try to respond to the event, I end up with the same problem as before.  What is the best way to get the chart to re-initialize and set zindexes correctly to fix the problem in that case?
