### ISSUE TITLE
Live data chart setInterval() problem in browser's window/tab focused out

### ISSUE THREAD

**Issue by Mehran91z** [amcharts/amcharts4#2287]
There is a problem with live data chart in this link: [amChart Live Data Demo](https://www.amcharts.com/demos/live-data/)

If we switch browser's (Chrome/Firefox) tab or window the chart will be stopped because of these codes: 
```
document.addEventListener("visibilitychange", function() {
    if (document.hidden) {
        if (interval) {
            clearInterval(interval);
        }
    }
    else {
        startInterval();
    }
}, false);
```
Removed those line version: https://codepen.io/Mehran91z/pen/zYGMBRB (you can check this out by focus out and return to this tab again after few seconds)

If we remove these codes, chart will be kind of unavailable! and data are not shown well in those seconds that window/tab was not focused, kind of we lost that data!

Can anyone help with this situation of live data chart?
It should works fine with setInterval() and unfocused tab and return to it again.

Thanks in advance.

**Comment by martynasma** [comment]
Updating chart is a CPU-intensive operation. That's why it's a sensible thing to do to ensure CPU is not wasted on a chart that is not visible, hence the code being there in the demo.

You're welcome to remove the code and modify it as you see fit in your setup, though.

**Comment by Mehran91z** [comment]
@martynasma Thank you for answer, but what about the core of amchart that does not know chart data (undefined values of series.dataItems)?

This should be known for develop other stuff!

**Comment by zeroin** [comment]
I solved this by adding:
```
if(document.hidden){
    am4core.system.update();
}
```
to the setInterval method.

Here is a pen:

https://codepen.io/team/amcharts/pen/807081d64cdfb84d1f3098946dbc29ef

**Comment by zeroin** [comment]
Update: I think a better approach would be to call `chart.validateData()` as system.update() results some jagged animation when window is focused again.
