### ISSUE TITLE
Legend Interaction with maps

### ISSUE THREAD

**Issue by phane24** [amcharts/amcharts4#2288]
How to achieve the Custom Legend Interaction with Maps with Lat and Long?? Like if we click on the legend then appropriate maps lat and long show hidden and wen we click again the same legend then appropriate maps lat and lat should display .....please help Thanks in advance

**Comment by zeroin** [comment]
You should add "toggled" event listener to the legend's itemContainer template and then do the things you need when event happens. I can't tell anything more specific, as it's not very clear what you want to achieve.

```
chart.legend.itemContainers.template.events.on("toggled", function(event){
  if(event.target.isActive){
    //do smth
  }
  else{
    //do smth
  }
})
```
