### ISSUE TITLE
Stacked Bar Chart with inconsistent data

### ISSUE THREAD

**Issue by EwattchGuillaumeCaruso** [amcharts/amcharts4#2289]
We (as in my company) are currently testing this library, in order to replace highcharts. So far it seems like it but we found multiple issue that are key to our development.

When trying to create a stacked bar chart with inconsistent data, we get this result :

![image](https://user-images.githubusercontent.com/62694436/77631043-54da1f00-6f4c-11ea-8d61-b5049131ed17.png)

The code is the following 
`
var chart = am4core.create("chartdiv", am4charts.XYChart);

        chart.legend = new am4charts.Legend();
        chart.legend.position = "right";

        var dateAxis = chart.xAxes.push(new am4charts.DateAxis());

        var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
        valueAxis.min = 0;

        var serie1 = chart.series.push(new am4charts.ColumnSeries());
        serie1.dataFields.valueY = 'y';
        serie1.dataFields.dateX = "x";
        serie1.stacked = true;
        serie1.name = "Canalis";
        serie1.tooltipText = "{name}: [bold]{valueY}[/]";
        serie1.data = [
            {x: 1451606400000, y: 272547327},
            {x: 1483228800000, y: 132483522},
            {x: 1514764800000, y: 113897230},
            {x: 1546300800000, y: 101435390},
            {x: 1577836800000, y: 7407186}
        ];
        
        var serie2 = chart.series.push(new am4charts.ColumnSeries());
        serie2.dataFields.valueY = 'y';
        serie2.dataFields.dateX = "x";
        serie2.stacked = true;
        serie2.name = "Compre";
        serie2.tooltipText = "{name}: [bold]{valueY}[/]";
        serie2.data = [
            {x: 1420070400000, y: 1717404000},
            {x: 1451606400000, y: 2445746544},
            {x: 1483228800000, y: 2261726916},
            {x: 1514764800000, y: 1916525236},
            {x: 1546300800000, y: 1076590557},
            {x: 1577836800000, y: 0},
        ];

        chart.cursor = new am4charts.XYCursor();`

As you can see, the first column does not start at 0. But when we hide the "Canalis" it does come back at 0.

Is this an issue on my part, or is this the intended behavior ?

**Comment by zeroin** [comment]
Hi,

We have this note in the `stacked` description in the docs:

	 * Note: proper stacking is only possible if series have the same number
	 * of data items. To ensure this, don't set data directly on series
	 * but do this on chart instead.

Or you can set the data to the series like you do, but both data arrays should have the same number of data items (and dates should match).

**Comment by EwattchGuillaumeCaruso** [comment]
Thanks for the info !
