### ISSUE TITLE
Cannot add data to ColumnSeries directly

### ISSUE THREAD

**Issue by VictorJuliani** [amcharts/amcharts4#229]
Hello, me again!

Currently, it seems that adding data restricted to a single series is not available for (at least) PieSeries and ColumnSeries. For LineSeries & RadarSeries the data is being plotted normally.

Here's a very simple repro: https://codepen.io/victorjuliani/pen/vaPwPV?editors=0010
When you change "series.data" to "chart.data" (line 13), the columns are plotted.

**Comment by martynasma** [comment]
No bug here.

When we move your data to the series, it sets data for that series only.

What we forget is that `CategoryAxis` needs data to draw its categories from as well. It can't take it data from series' data.

So, if you absolutely need to move data to series, you also need to ensure that your category axis has category data. Either through chart's `data`, or through axis` own `data`. It does not need to have values, just categories. E.g.:

```
categoryAxis.data = [{
  "category": 10
}, {
  "category": 20
}, {
  "category": 30
}];
```

Here's your pen updated:
https://codepen.io/team/amcharts/pen/06f59bfb9dc971a5930bbce204a803e1/

**Comment by martynasma** [comment]
Updated [this tutorial section](https://www.amcharts.com/docs/v4/concepts/series/#Series_specific_data) accordingly.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
