### ISSUE TITLE
Updating chart data on zoom events

### ISSUE THREAD

**Issue by DerekDuchesne** [amcharts/amcharts4#2290]
I'm trying to find a way to update a chart's data in response to a zoom. The use case is that the data needs to be recalculated with respect to the new start and end dates after the zoom.

I'm using the `selectionextremeschanged` event on a `Date Axis`, and inside the event handler, am reassigning `chart.data`. I found that updating the chart data also causes a `selectionextremeschanged` event, so to avoid a recursive loop, I'm storing a `startDate` and `endDate` before the zoom so that when it's called recursively, if neither of the dates have changed, the chart data does not get updated again.

This works when zooming on some date ranges, but not others. With some date ranges, I get the following error:
`Cannot read property 'dateX' of undefined`

Here's a codepen that demonstrates the issue: https://codepen.io/derek35/pen/rNVQRwN?editors=1111

Some more info on that codepen:
- `startDate` and `endDate` are the aforementioned variables that prevent a loop. They're meant to represent the current zoom range.
- `chartData` is the initial data the chart is loaded with. When the zoom button is clicked, it gets updated with `updatedChartData`.
- `chartData` goes from `2017-03-01` to `2017-09-30`. If I remove March and have it just go from `2017-04-01` to `2017-09-30`, I don't run into the `Cannot read property 'dateX' of undefined` error.

Thank you!

**Comment by zeroin** [comment]
Let me ask first - when you update data, does the number of data items in the selection remains the same? In case it does, then instead of setting new data for the chart I would strongly recommend modifying the old data array and calling `chart.invalidateRawData()` this will be way more faster and you will not get into loops of events.

**Comment by DerekDuchesne** [comment]
For my use case, I can keep the number of data items the same. When I try that, edit the data in-place, and use `chart.invalidateRawData()`, I didn't get into an event loop and didn't run into the same issue.

Thank you!
