### ISSUE TITLE
Is it posible to not use decimals?

### ISSUE THREAD

**Issue by Carlos123211** [amcharts/amcharts4#2291]
Hello, I'm using amcharts bar race,but I do not not to use the decimals, eventhough the decimals seems to be obligatory, is there any way to prevent that, I want to performance something like this ->
https://observablehq.com/@d3/bar-chart-race-explained

**Comment by zeroin** [comment]
You can format numbers in anyway you want: https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/

**Comment by Carlos123211** [comment]
But When I format the number it still displaying decimals in the iterations, 
https://codepen.io/Carlos1232/pen/xxGmEmj?editable=true
I want to achieve it without showing the decimals and the numberformatter do not let me do it.

**Comment by martynasma** [comment]
You can specify your global number format like this:

```
chart.numberFormatter.numberFormat = "#";
```

Please note that in your example, there's also inline format for the label bullet:

```
labelBullet.label.text = "{values.valueX.workingValue.formatNumber('#,###')}";
```

You will need to update it as well:

```
labelBullet.label.text = "{values.valueX.workingValue.formatNumber('#')}";
```

**Comment by Carlos123211** [comment]
Even though I had done that when I use the values.valuex.workingValue , still showing decimals->
https://codepen.io/Carlos1232/pen/xxGmEmj?editable=true

**Comment by martynasma** [comment]
Right. To eliminate the decimals, you can just add a dot at the end of the number format:

```
chart.numberFormatter.numberFormat = "#.";
```

That link my colleague sent has all of that ;)

https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/

**Comment by Carlos123211** [comment]
Thanks, It worked.
