### ISSUE TITLE
Duplicate theme in React environment

### ISSUE THREAD

**Issue by smooth97** [amcharts/amcharts4#2292]
I set different charts for each chart, and the same theme applies.

**Comment by martynasma** [comment]
What do you mean "different charts for each chart"? Did you mean you set different themes?

The themes in amCharts 4 are global. Meaning that if a theme is active at the moment of chart's creation, it will be applied to it.

If multiple themes are active, multiple themes will be appllied.

Check here for a solution:
https://www.amcharts.com/docs/v4/concepts/themes/#Different_themes_to_different_charts
