### ISSUE TITLE
Modifying ScrollbarX view

### ISSUE THREAD

**Issue by WojciechKlisiewicz** [amcharts/amcharts4#2293]
Hi, I tried to adopt scrollbar to dark theme.
![image](https://user-images.githubusercontent.com/21077892/77743302-27f33e00-7018-11ea-878f-91ebeb5add58.png)
Can you tell me how to change:
1. Selected area border (white color to dark)
2. Grip start end border (white color to dark)
3. Grip hover background (grey color to darken)
4. Disabling X labels

I will be grateful for help.

**Comment by zeroin** [comment]
We have tutorial which should cover 1-3:
https://www.amcharts.com/docs/v4/tutorials/customizing-chart-scrollbar/

To modify colors on various states, check states: 
https://www.amcharts.com/docs/v4/concepts/states/

To disable labels, try:
`chart.scrollbarX.scrollbarChart.xAxes.getIndex(0).renderer.labels.template.disabled = true;`
