### ISSUE TITLE
chart element show out of div

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2296]
chart element show out of div.
https://codepen.io/hassandl/pen/KKpbpeQ

![Untitled](https://user-images.githubusercontent.com/22093903/77750481-7d901080-7041-11ea-9237-1c5de838a54d.png)

**Comment by krystian-wolarek** [comment]
I've got similar problem. [Example](https://codepen.io/codeapi/pen/poJqEgv). 
I've added bullets to charts to make point more visible but with series with zeros they were cut. So i decided to add some padding and it was fine with bullets.
Then i saw another problem. When series uses tensionY and data got few at least one value above 0 the line disappears.

<img width="977" alt="Zrzut ekranu 2020-03-27 o 16 59 23" src="https://user-images.githubusercontent.com/39270768/77775134-6dc9f980-704c-11ea-8028-8c3529e8c4d1.png">

I know i can use extraMin but it will create another value on axis and will take extra space.
I think so i would be awesome to have tensionY = 1 for for repetitive data.

**Comment by martynasma** [comment]
@HASSANDL You can try reducing radius of the labels:

```
axis.renderer.labels.template.radius = 10;
```

@krystian-wolarek Yours is altogether different issue. Please consider posting as a separate issue.

**Comment by krystian-wolarek** [comment]
OK, i'll make separate one. Thanks

**Comment by HASSANDL** [comment]
Very thanks.
