### ISSUE TITLE
Charts cuts off lines bellow minimal value and if tension is used the line can disappear 

### ISSUE THREAD

**Issue by krystian-wolarek** [amcharts/amcharts4#2297]
[Example](https://codepen.io/codeapi/pen/poJqEgv). 
I've added bullets to charts to make point more visible but with series with zeros they were cut.

<img width="858" alt="Zrzut ekranu 2020-03-30 o 14 47 59" src="https://user-images.githubusercontent.com/39270768/77913990-7f521200-7295-11ea-92ec-283ededb5c89.png">

So i decided to add some `paddingBottom` and it was fine with bullets ( but if line stroke was for example 2px, on the 0 line it was displayed like 1px thick).
Then i saw another problem. When series uses `tensionY` and data got at least one value above 0, the line disappears.

<img width="996" alt="Zrzut ekranu 2020-03-30 o 14 46 35" src="https://user-images.githubusercontent.com/39270768/77913870-50d43700-7295-11ea-8d32-1b49e6805af4.png">

I know i can use `extraMin` but it will create another value on axis ( for only positive data negative value is not desirable ) and will take extra space.

I think so i would be awesome to have `tensionY = 1` for repetitive data or the line should be rendered in additional padding, not cut off.

**Comment by zeroin** [comment]
I am afraid there is no other solution except extraMin/extraMax here. It's how smoothed lines work.

**Comment by sassomedia** [comment]
@zeroin Is there a way to bring back bezier curves from amchartsV3? The example above wasn't an issue there, bezier curves would only apply to actual value changes and they wouldn't overshoot. I feel like the smoothed lines are visually a big step backwards. There may be instances where an overshooting curve is preferred but I'd say for most use cases, it does not visually represent accurate data. Is there a reason why this was changed?

**Comment by martynasma** [comment]
@sassomedia Check this out:
https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Alternate_smoothing_algorithm

**Comment by sassomedia** [comment]
@martynasma Ah right, I remember seeing this at some point and that does indeed take care of the overshooting part. Although, I ended up not using it as there was no setting to adjust the strength of the curve like `tension` does. With `monotoneX` it's either all or nothing and for my use-case, it was way too much. Is customization something that could be added in the future, maybe based off the tension factor?

Also, on lines that go diagonally from a low to a high point or vice versa but have points in between, there is always a small "bump" on those points. The screenshot shows only a tiny "bump" but I've had other instances where it was more pronounced:
<img width="690" alt="Screen Shot 2020-11-10 at 5 32 42 PM" src="https://user-images.githubusercontent.com/5614099/98649402-e92db080-237a-11eb-8f5d-1c5b4660cbbb.png">

As far as I recall, the v3 implementation handled that more gracefully and just run straight through the point. With `monotoneX` I guess it can only curve horizontally, hence the "bump" on every point. Maybe a threshold could help as to when to apply it? If it's below a certain point, don't curve at all?

**Comment by martynasma** [comment]
I'm sorry, but those are the only two options :(

**Comment by sassomedia** [comment]
Right but could there be room for an enhancement?

**Comment by martynasma** [comment]
> Right but could there be room for an enhancement?

At this time we are not planning any new smoothing algos. V3 smoothing was not universally good, either.

**Comment by sassomedia** [comment]
Alright, I'm sure v3 had its own issues.
