### ISSUE TITLE
Is it posible to set max Columns to be showed?

### ISSUE THREAD

**Issue by Carlos123211** [amcharts/amcharts4#2299]
Hello,for example In Chart Bar Race I want to show top 5, is it posible to set it like that? I?m trying to implement maxColumns, but I'm not able to do it.
Am I doing something wrong? 

series.columns.maxColumns = 5;
https://codepen.io/Carlos1232/pen/xxGmEmj

**Comment by xorspark** [comment]
If you want to lock the view to the top five, use `zoomToIndexes` to lock to zoom to the first five values in the category axis, e.g. `categoryAxis.zoomToIndexes(0, 5);`

[Demo](https://codepen.io/team/amcharts/pen/a063d1c85de6fc778d9f28ffe6f19f1c?editors=0010)

**Comment by Carlos123211** [comment]
Thanks It worked for me.
