### ISSUE TITLE
Offer possibility to change chart type on existing graph

### ISSUE THREAD

**Issue by noiwid** [amcharts/amcharts4#2302]
Hi there,
I'm looking for a way to change graph type on the fly, and don't find info on this question on the doc. 

I'm trying to offer a way to users to switch view from pie to bars or bars to pie... (with same graph object if possible). Do you know if it's possible ?

Thanks a lot for your support 🙏

**Comment by martynasma** [comment]
> Do you know if it's possible ?

Nope.

You can have two charts `PieChart` and `XYChart` ready, with one hidden. Then when user toggles chart type, you just hide one and reveal the other.
