### ISSUE TITLE
How to show Map tooltip for the circles dynamically via API

### ISSUE THREAD

**Issue by vihano** [amcharts/amcharts4#2304]
`let imageSeries = this.AMCHART_OBJ.series.push(new am4maps.MapImageSeries());
            imageSeries.data = this.REGION_CARDS;
            // imageSeries.dataFields.category = "country";
            imageSeries.dataFields.value = "confirmed";

            let imageTemplate = imageSeries.mapImages.template;
            imageTemplate.nonScaling = true
            imageTemplate.propertyFields.latitude = "latitude";
            imageTemplate.propertyFields.longitude = "longitude";

            let circle = imageTemplate.createChild(am4core.Circle);
            circle.fillOpacity = 0.7;
            circle.fill = "red";
            circle.tooltipText = "{region_name}";
            // circle.alwaysShowTooltip = true;
            imageSeries.heatRules.push({
                "target": circle,
                "property": "radius",
                "min": 4,
                "max": 30,
                "dataField": "value"
            });`

**Comment by zeroin** [comment]
If you set `imageSeries.mapImages.getIndex(index).isHover = true` it should show the tooltip.
