### ISSUE TITLE
"Chart was not disposed id" even when using chart.dispose();

### ISSUE THREAD

**Issue by liorkatzdev** [amcharts/amcharts4#2306]
still getting errors (in angular) about Chart was not disposed id-X :

`ngOnDestroy() {
  this.zone.runOutsideAngular(() => {
    if (this.chart) {
      this.chart.dispose();
    }
  });
}`

**Comment by BdDragos** [comment]
Do you happen to use Angular 9? I also had the same issue after updating to Angular 9 and what worked was putting a setTimeout(() => {}); in the code that contains the create chart functionality. Dispose triggered for me but it wasn't finished doing it's thing when a new chart was created.

**Comment by liorkatzdev** [comment]
i have more then one chart components, ill need setTimeout(() => {}); 
in each one of them?
using angular 8

**Comment by martynasma** [comment]
Do you happen to use an external legend? It needs to be disposed as well.
