### ISSUE TITLE
Disable weighted option for the VennDiagram

### ISSUE THREAD

**Issue by djpirra** [amcharts/amcharts4#2311]
Hi, is there any option to not make the diagram weighted? No use value to define the circles size.

Thank you

**Comment by martynasma** [comment]
If it's only about making all bubbles equally-sized then you can just use the same value for all of them.

And for intersections, we absolutely need values to know how much are they overlapping.

Isn't it the whole point of Venn diagram?

**Comment by djpirra** [comment]
Hi martynasma,

There are several ways to use a venn diagram, it can be weighted or not.
For example in my particular case I have a big different between the values for some intersections and this makes it impossible to analyze or even represent. I was trying to find a way to at least just be able to see the intersections with a value in it.

Like this example: [Venn Diagram](https://www.gliffy.com/hubfs/images/Diagram%20Pages/venn-hero.jpg)

But instead of the labels I might wanna see the values with the usage of a legend by color.

**Comment by martynasma** [comment]
I'm afraid there's no way to replicate the diagram from your example in amCharts 4 :(

Seems quite hand-tailored.

Sorry mate, at this point we won't be able to implement value-less Venn data support. Sorry.

**Comment by djpirra** [comment]
Hi martynasma,

Thanks for the reply, I think this would be awesome to consider in adding to the exist venn diagram or create a new one as static venn diagram just to represent the values on the intersections.

This is required in many business scenarios I am involved at.

Thank you

Regards,
LS

**Comment by martynasma** [comment]
Well, you can still do that with values. Just use some value for all bubbles, say 10, and one value for all intersections, say 2.

If you want to show something else than actual value or name for a label on intersections, you can configure that via label template:

https://www.amcharts.com/docs/v4/chart-types/venn/#Contents_of_the_label

**Comment by djpirra** [comment]
I have tried that approach but it seemed to have rendered incorrectly.

**Comment by martynasma** [comment]
Can you post what you tried?

**Comment by djpirra** [comment]
Basically I have 4 circles with intersections between them.
Have used 50 as size for the base items (no sets) and 50 divided by the number of items in correspondent set.

**Comment by martynasma** [comment]
So, something like this?
https://codepen.io/team/amcharts/pen/12bbd1f42d094ac5a6147aff0c745f98?editors=0010

**Comment by djpirra** [comment]
Hi Martynasma,

Not exactly because in that one we don't have all the possible intersections...
Using 4 combinations you will need to have something similar to this:

![image](https://user-images.githubusercontent.com/15980662/78715284-3e5d9b80-792e-11ea-93e6-4228650422b2.png)

**Comment by martynasma** [comment]
Like this then:
https://codepen.io/team/amcharts/pen/12bbd1f42d094ac5a6147aff0c745f98?editors=0010

**Comment by djpirra** [comment]
Hi Martynasma,

This is exactly what I needed! How did you calculated the different values for each set dimension? Experimenting? I will need to do something similar for also for 3 circles etc...

Anyway, thanks! Amazing.

**Comment by martynasma** [comment]
Actually for this chart only the first round of intersection values matter, because they lock positions of the four circles. Inside values do not influence anything because overlaps are already locked in.

Hope that makes sense.

**Comment by djpirra** [comment]
It seems that the order of the data is important too...
Try to see this dataset since it does not appear to work properly:

`series.data = [
   {
      "name":"Is Retail",
      "value":50
   },
   {
      "name":"Is Malls",
      "value":50
   },
   {
      "name":"Is Auto",
      "value":50
   },
   {
      "name":"Is Real Estate",
      "value":50
   },
   {
      "name":"Is Malls & Is Retail",
      "value":30,
      "sets":[
         "Is Malls",
         "Is Retail"
      ]
   },
   {
      "name":"Is Auto & Is Retail",
      "value":30,
      "sets":[
         "Is Auto",
         "Is Retail"
      ]
   },
   {
      "name":"Is Auto & Is Malls",
      "value":30,
      "sets":[
         "Is Auto",
         "Is Malls"
      ]
   },
   {
      "name":"Is Real Estate & Is Retail",
      "value":30,
      "sets":[
         "Is Real Estate",
         "Is Retail"
      ]
   },
   {
      "name":"Is Auto & Is Real Estate",
      "value":30,
      "sets":[
         "Is Auto",
         "Is Real Estate"
      ]
   },
   {
      "name":"Is Malls & Is Real Estate",
      "value":30,
      "sets":[
         "Is Malls",
         "Is Real Estate"
      ]
   },
   {
      "name":"Is Auto & Is Malls & Is Retail",
      "value":30,
      "sets":[
         "Is Auto",
         "Is Malls",
         "Is Retail"
      ]
   },
   {
      "name":"Is Auto & Is Real Estate & Is Retail",
      "value":30,
      "sets":[
         "Is Auto",
         "Is Real Estate",
         "Is Retail"
      ]
   },
   {
      "name":"Is Malls & Is Real Estate & Is Retail",
      "value":30,
      "sets":[
         "Is Malls",
         "Is Real Estate",
         "Is Retail"
      ]
   },
   {
      "name":"Is Auto & Is Malls & Is Real Estate",
      "value":30,
      "sets":[
         "Is Auto",
         "Is Malls",
         "Is Real Estate"
      ]
   },
   {
      "name":"Is Auto & Is Malls & Is Real Estate & Is Retail",
      "value":30,
      "sets":[
         "Is Auto",
         "Is Malls",
         "Is Real Estate",
         "Is Retail"
      ]
   }
];`

**Comment by martynasma** [comment]
Yes, order is important, because intersections are calculated one by one. If some intersections lock in circles in some particular pattern, then any subsequent intersection can't change that.

**Comment by djpirra** [comment]
What is the most correct way to sort data in the object then?

**Comment by martynasma** [comment]
I don't think there's a "correct" way.

I suppose you put intersections that you need correctly sized by value or least complex (less circles intersecting) first.

**Comment by djpirra** [comment]
Let me give an example of something I thing its not getting correctly represented:

The circle marked in yellow seem to have the dimensions wrong accordingly to the volume shown in the values.
What can be wrong here?

![Annotation 2020-04-08 202430](https://user-images.githubusercontent.com/15980662/78808869-19713300-79d7-11ea-9722-810552aa0cda.png)

**Comment by martynasma** [comment]
This has got way outside of the scope of original question. If you want to pursue this, please consider opening a separate issue. However, I don't think that will lead to anything. We're using an established Venn algorithm, so options in modifying it are quite limited.

**Comment by djpirra** [comment]
Hi Martynasma,
Will create a new issue then.

Continuing this thread, would it be achievable to have the chart to highlight/select on the part for example for ACD combination?

**Comment by martynasma** [comment]
Please, let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by djpirra** [comment]
Hi @martynasma.
Would it be achievable to have the chart to highlight/select on the part for example for ACD combination?

My goal was to be able to select/highlight all possible combinations between 4 dimensions and currently this diagram does not allow me to see for example dimension A as not having any intersection, it highlights the whole A.

Thank you

**Comment by djpirra** [comment]
Any updates please? This is the only thing missing to finish my component.

Thank you
