### ISSUE TITLE
Venn Diagram slices event always propagating

### ISSUE THREAD

**Issue by djpirra** [amcharts/amcharts4#2312]
Hi currently I built a code to show a context menu but the event is always propagating and showing the menu from chrome together with the context menu.
What is wrong or is it a bug?

`this.vennSeries.slices.template.events.on("rightclick", 
            function(ev){
                    ev.event.preventDefault();
                    ev.event.stopPropagation();             
                    const mouseEvent: MouseEvent = ev.event as MouseEvent;
                    var _dataItem:VennSeriesDataItem = <VennSeriesDataItem>ev.target.dataItem; 
                    this.selectionManager.showContextMenu(_dataItem, {
                        x: mouseEvent.clientX,
                        y: mouseEvent.clientY
                    });                    
            }
            ,this);
`

Thank you

**Comment by martynasma** [comment]
"rightclick" event does not disable context menu. There's not easy, standard way to do that. If you need to replace it with something else, you will need to implement yourself, I'm afraid.

**Comment by djpirra** [comment]
It was fixed by adding a contextmenu event and stopping propagation there.
