### ISSUE TITLE
Disable initial loading animation for force-directed charts

### ISSUE THREAD

**Issue by sophanox** [amcharts/amcharts4#2315]
Hi there,

I was just wondering if anyone could let me know what exact setting I need to disable to stop the initial loading animation for force directed charts? The animation where it seems to originate from the top left of the chart area. I've tried a variety of combinations but nothing seems to be working.

Thanks very much

**Comment by zeroin** [comment]
There is no way to disable it completely, as the layout of the bubbles is not created instantly but is a result of forces being applied for multiple frames. There is no way to have the initial layout without instantly, unless you specify all the positions manually:
https://www.amcharts.com/docs/v4/chart-types/force-directed/#Fixed_nodes

You could also check the velocityDecay setting:
https://www.amcharts.com/docs/v4/chart-types/force-directed/#Friction_and_mobility

**Comment by sophanox** [comment]
I see. Thanks very much for your answer & the info.
