### ISSUE TITLE
Can we load multiple data source URLs for multiple series in Amcharts 4 using Javascript

### ISSUE THREAD

**Issue by komaldudakiya** [amcharts/amcharts4#2320]
With reference to [https://github.com/amcharts/dataloader/issues/20](https://github.com/amcharts/dataloader/issues/20) is there any example present on how to use DataLoader in Version 4? Or an alternate option to that?

I want to load data from multiple csv files into single line series chart using Javascript.

I tried using dataSource for series. But it doesn't plot the X-axis. Below is the snippet

      series.dataSource.url = "file.csv";
      series.dataSource.parser = new am4core.CSVParser();
      series.dataSource.parser.options.useColumnNames = true;
      series.dataSource.parser.options.skipEmpty = false;
      series.dataSource.parser.options.numberFields = ["totalConfirmed", "totalDeaths", "totalRecovered"];
      
      series.dataFields.valueY = field;
      series.dataFields.categoryX = "date";

**Comment by martynasma** [comment]
Well, it looks like you are using `CategoryAxis`.

If you are not loading data for the chart itself, the axis does not know which categories to use.

So either you need to use `chart.dataSource` so that axis knows list of categories, or you can load the data in axis itself `axis.dataSource = ...`.

**Comment by komaldudakiya** [comment]
Thanks for your help. I am now using DateAxis instead of CategoryAxis.

And using series.dataSource.url = "*.csv" worked for me to load data from multiple csv files.
