### ISSUE TITLE
When VennDiagram legend is turn invisible the diagram do not occupy that space

### ISSUE THREAD

**Issue by djpirra** [amcharts/amcharts4#2321]
My goal when disabling/turning invisible the legend for the venn diagram was so that the diagram could expand and occupy the space previously taken by the legend.

How to achieve this?

Thank you

**Comment by martynasma** [comment]
Try setting `chart.legend.disabled = true`.

**Comment by djpirra** [comment]
Thank you that worked flawlessly. Was searching for enabled option instead of disabled :)
