### ISSUE TITLE
Both Sprite and Image doesnt work properly in MapImageSeries

### ISSUE THREAD

**Issue by mr660** [amcharts/amcharts4#2322]
Im trying to make markers on map, nothing really works.

     // define images / markers
      markerSeries = chart.series.push(new am4maps.MapImageSeries())
      markerSeries.data = markersData

      // define images template
      markerSeriesTemplate = markerSeries.mapImages.template
      markerSeriesTemplate.propertyFields.latitude = 'coordinatex'
      markerSeriesTemplate.propertyFields.longitude = 'coordinatey'
      // markerSeriesTemplate.nonScaling = true
      // markerSeriesTemplate.tooltipText = '{name}'

     /* when using both Sprite and Image width and height doesnt work, when using Image vertical/horizontalCenter also doesnt work  */
      let marker = markerSeriesTemplate.createChild(am4core.Sprite)  
      marker.path = pinPath
      marker.width = 20
      marker.height = 20
      marker.scale = 1
      marker.horizontalCenter = 'middle'
      marker.verticalCenter = 'bottom'
      marker.fill = '#ff0000'
      // marker.tooltipText = '{name}'

Im starting to pull my hair out, since im using Sprite and not Image i tried to find some special series for sprites so i found `new am4maps.MapSeries()` but couldnt find any template, tried to use bullets.template but doesnt work. Why this simple thing just cant get to work??? Whats the problem here?

**Comment by mr660** [comment]
update: percentage values also doesn't work..

**Comment by martynasma** [comment]
What is in `pinPath`?

**Comment by mr660** [comment]
It's just a path, to be exact:
`const pinPath = 'M256,0C153.755,0,70.573,83.182,70.573,185.426c0,126.888,165.939,313.167,173.004,321.035 c6.636,7.391,18.222,7.378,24.846,0c7.065-7.868,173.004-194.147,173.004-321.035C441.425,83.182,358.244,0,256,0z M256,278.719 c-51.442,0-93.292-41.851-93.292-93.293S204.559,92.134,256,92.134s93.291,41.851,93.291,93.293S307.441,278.719,256,278.719z`

I'm using lazyloading with webpack(`lazyload` function need to be attached to scroll event in future) and call to api for markers data.
Here is full code:
```
(() => {
  const $this = $('.m-partners-map')
  const pinPath = 'M256,0C153.755,0,70.573,83.182,70.573,185.426c0,126.888,165.939,313.167,173.004,321.035 c6.636,7.391,18.222,7.378,24.846,0c7.065-7.868,173.004-194.147,173.004-321.035C441.425,83.182,358.244,0,256,0z M256,278.719 c-51.442,0-93.292-41.851-93.292-93.293S204.559,92.134,256,92.134s93.291,41.851,93.291,93.293S307.441,278.719,256,278.719z'
  const pinUrl = $this.data('map-pin')
  const pinColor = $this.data('map-pin-color')
  const $map = $this.find('.m-partners-map__map-inner')
  let chart, polygonSeries, polygonTemplate, markerSeries, markerSeriesTemplate

  let am4core, am4maps, am4geodata

  function lazyload () {
    const offsetTop = $this.offset().top
    const offsetBottom = offsetTop + $this.outerHeight()
    const vpTop = $(window).scrollTop()
    const vpBottom = vpTop + $(window).innerHeight()

    if ((vpBottom > offsetTop) && (vpTop < offsetBottom)) {
      initModules()
    }
  }

  function initModules () {
    Promise.all([
      import(/* webpackChunkName: "amcharts_core" */ '@amcharts/amcharts4/core'),
      import(/* webpackChunkName: "amcharts_map" */ '@amcharts/amcharts4/maps'),
      import(/* webpackChunkName: "amcharts_geodata" */ '@amcharts/amcharts4-geodata/switzerlandLow')
    ]).then((modules) => {
      am4core = modules[0]
      am4maps = modules[1]
      am4geodata = modules[2].default

      initMap()
      $.ajax('/_api/partners', {
        success: (data) => {
          initMapMarkers(data)
        },
        error: (xhr) => {
          console.log('Something went wrong with ajax call to t3api', xhr)
        }
      })
      // Chart code goes here
    }).catch((e) => {
      console.error('Error when loading amcharts modules', e)
    })
  }

  function initMap () {
    am4core.ready(() => {
      // define map chart and use geodata
      chart = am4core.create($map[0], am4maps.MapChart)
      chart.geodata = am4geodata
      chart.chartContainer.wheelable = false

      // define polygons based on geodata
      polygonSeries = chart.series.push(new am4maps.MapPolygonSeries())
      polygonSeries.useGeodata = true

      // define polygon template
      polygonTemplate = polygonSeries.mapPolygons.template
      polygonTemplate.fill = am4core.color('#999999')
      polygonTemplate.stroke = am4core.color('#F7F7F7')
    })
  }

  function initMapMarkers (markersData) {
    markersData = markersData['hydra:member']
    for (const item of markersData) {
      item.coordinatex = parseFloat(item.coordinatex)
      item.coordinatey = parseFloat(item.coordinatey)
    }

    am4core.ready(() => {
      // define images / markers
      markerSeries = chart.series.push(new am4maps.MapImageSeries())
      markerSeries.data = markersData

      // define images template
      markerSeriesTemplate = markerSeries.mapImages.template
      markerSeriesTemplate.propertyFields.latitude = 'coordinatex'
      markerSeriesTemplate.propertyFields.longitude = 'coordinatey'
      // markerSeriesTemplate.nonScaling = true
      // markerSeriesTemplate.tooltipText = '{name}'

      let marker = markerSeriesTemplate.createChild(am4core.Sprite)
      marker.path = pinPath
      marker.width = 20
      // marker.height = 20
      marker.horizontalCenter = 'middle'
      marker.verticalCenter = 'bottom'
      marker.fill = '#ff0000'
      // marker.tooltipText = '{name}'
    })
  }

  lazyload()
})()

```

**Comment by martynasma** [comment]
Your SVG path is huge. Setting it to `path` on a Sprite does not automatically resize it to fit the 20x20px you have set for your Sprite. So Sprite displays just a corner of the big path, which does not contain anything, hence empty markers.

Try using `scale` property to size-down the markers so your path does fit into 20x20.
