### ISSUE TITLE
Series tooltips only showing last series added with 'dateAxis' x-axis

### ISSUE THREAD

**Issue by stinney1103** [amcharts/amcharts4#2323]
With DateAxis, I am losing all tooltips for all but the last series added to the chart when I use the DateAxis. I have tried adding the data to the series or the chart level. Am I missing something or is there a bug in the DateAxis tooltips?

https://codepen.io/stinney1103/pen/zYvOXwp

**Comment by xorspark** [comment]
Your code is setting [`snapToSeries`](https://www.amcharts.com/docs/v4/reference/xycursor/#snapToSeries_property) for each series that gets created (line 240: `chart.cursor.snapToSeries = series;`), so the last one assigned in your loop will be what the cursor snaps to. This setting forces the cursor to only trigger tooltips for the series it is assigned to. Removing it will fix the problem.

**Comment by stinney1103** [comment]
Thank you very much @xorspark that did the trick!
