### ISSUE TITLE
Prevent end label in CategoryAxis from being cut off

### ISSUE THREAD

**Issue by DerekDuchesne** [amcharts/amcharts4#2324]
The `CategoryAxis` graph that I'm working on has an end label that is being cut off. I tried lessening `categoryAxis.renderer.minGridDistance` to 1, but there's enough data points that the last label still gets cut off. I can fix that by rotating the labels 90 degrees, but I was wondering if there is a way to keep the label horizontal while still making it fit within the graph.

Here's a codepen showing the graph: https://codepen.io/derek35/pen/rNVQRwN?editors=1011

Thank you,

**Comment by xorspark** [comment]
You can add some padding on the right of the chart, e.g.

```
chart.paddingRight = 30;
```

**Comment by DerekDuchesne** [comment]
Using `chart.paddingRight = 30;` worked.

Thank you!
