### ISSUE TITLE
Resizing makes rendering too slow on Venn Chart

### ISSUE THREAD

**Issue by djpirra** [amcharts/amcharts4#2327]
Hi,
My venn chart lives inside a container that can be resized by the user.
When the event of resizing is happening the chart redraws itself for every position during the resizing/dragging.
Is there a way to avoid this?

Thank you

**Comment by martynasma** [comment]
You may disable chart auto-resizing like this:

```
chart.svgContainer.autoResize = false;
```

Then force resizing manually:

```
chart.svgContainer.measure();
```
