### ISSUE TITLE
Moving trend line by dragging

### ISSUE THREAD

**Issue by mrmime95** [amcharts/amcharts4#2329]
Having the pen bellow, how is it possible to move, or delete the line on click/on dragging.

https://codepen.io/mrmime95/pen/VwvwmXe?editors=0010

**Comment by zeroin** [comment]
We have a similar concept here: https://www.amcharts.com/demos/drawing-chart-series-with-mouse-or-touch/

**Comment by mrmime95** [comment]
Thanks, but in this example I have to click to the bullet and then I can change it's position.
If I click on a line, is it possible to define, which line was clicked?
