### ISSUE TITLE
Show/hide custom image bullet by hover

### ISSUE THREAD

**Issue by fisherspoons** [amcharts/amcharts4#2330]
I have a line graph with two indicators for sale and purchase, I want two custom points (images) to be shown only when you point at a vertical line intersecting these points and disappear after leaving their borders.
I found a method that works when hovering it is over, but I can’t figure out which property to set for images exhaustively and which to show them on hovering.
I know what two events with what i can track this, it's '**over**' and '**out**'. I can’t understand how to turn to the image itself to show or hide it. I could not find anything similar in the examples, everything similar was done there on the svg elements (stroke, fill) which hide through opacity

![Image example](https://user-images.githubusercontent.com/54633510/78897361-b6d17300-7a7a-11ea-89ea-2e57180e802f.png)

[Codepen example](https://codepen.io/fisherspoons/pen/xxwxdXo)

And there’s one more thing, maybe someone knows if it’s possible to make the top and bottom of the graph so that the images can be on top of the graph 
![the image is cropped by the borders of the graph](https://user-images.githubusercontent.com/54633510/78898027-c7ceb400-7a7b-11ea-9ff0-c3d74f9ab9b6.png)

I will be very grateful for the help

**Comment by fisherspoons** [comment]
Omg, no one to help?

**Comment by fisherspoons** [comment]
Someone tell me why the Over / Out event is triggered single-core on each bullet,

`       bullet.events.on("over", function (e) {
            console.log('over')
            e.target.show();
        }, this);


        bullet.events.on("out", function (e) {
            console.log('out')
            e.target.hide();
        }, this);`

**Comment by martynasma** [comment]
No need for those events. You can just make bullets invisible in "default" state, and visible in "hover" state:

```
bullet.hide();
bullet.defaultState.properties.visible = false;
bullet.states.create("hover").properties.visible = true;
```

Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by fisherspoons** [comment]
Thank you, I did as you said, but jelly appeared at hover.

[Example](https://codepen.io/fisherspoons/pen/xxwxdXo?editors=0010)

**Comment by martynasma** [comment]
Jelly?
