### ISSUE TITLE
How do I get the object clicked in a ColumnSeries?

### ISSUE THREAD

**Issue by raz3r** [amcharts/amcharts4#2331]
I've been searching through the ev.target object but I can't find the actual clicked object anywhere. Usually for PieSeries I use ev.target.dataItem._dataContext.

**Comment by martynasma** [comment]
You are probably putting the event directly on series. Do that on column template instead:

```
series.columns.template.events.on("hit", function(ev) {
  console.log(ev.target.dataItem.dataContext);
});
```
