### ISSUE TITLE
The equivalent of colorField for PieChart

### ISSUE THREAD

**Issue by Julienh** [amcharts/amcharts4#2332]
Hello,

I'm looking for the equivalent of colorField for PieChart to set colors from data.
I tried: series.propertyFields.fill = "color";

With this in my data : color: "#00b7d9"

But it's not working.
Thank you.

**Comment by martynasma** [comment]
`propertyFields` is used on actual object you want to apply property values to. In this case it would mean a slice in series, not the series itself:

```
series.slices.template.propertyFields.fill = "color";
```

Please refer to the property fields docs:
https://www.amcharts.com/docs/v4/concepts/data/#Property_fields

**Comment by Julienh** [comment]
Thank you !

**Comment by fisherspoons** [comment]
And no one can help on my question :(
