### ISSUE TITLE
Shadow in points on line graphic

### ISSUE THREAD

**Issue by CapInSpase** [amcharts/amcharts4#2335]
Good afternoon to everyone, I don’t understand what needs to be done to **give more room for the shadow,** it is cropped. At the same time, the proportions of the point completely suit me, except for the shadow. And how to change **animation duration opacity** when point show by hover? Points appears and disappears very slowly
The shadow should shift down 12px with blur 10px. The size of the point itself is now what we need.
Perhaps one of the good people will help)

[Codepen graphic](https://codepen.io/fisherspoon/pen/RwWNPoN)

**Comment by CapInSpase** [comment]
Ok, with animate I did, please help me with shadow!

**Comment by martynasma** [comment]
You might need to increase width/height of the shadow filter:

```
shadow.width = 400;
shadow.height = 400;
```

Those are not pixels but rather percent from the actual object width/height. So with your blur settings, you need it at 400% bigger than actual bullet to fit properly.

**Comment by CapInSpase** [comment]
Thank you!
