### ISSUE TITLE
Bad performance: Axis and series tooltips are calculated even when not shown

### ISSUE THREAD

**Issue by jyrimatti** [amcharts/amcharts4#2339]
Hi,

First of all, thank you for amcharts! I have only been using it for a couple of hours and it already seems extremely versatile and powerful! Also I'm really happy with the extensive documentation!

I'm using amcharts 4.9.13 to draw an XYChart with a DateAxis having about a thousand LineSeries (maybe around a hundred points in each). Performance was initially so bad that the chart was totally unusable. Even initialization takes about 2 minutes (around 100ms per series).

I used Chrome profiler to find that tooltips use a lot of CPU even when I'm simple moving the cursor on an empty space without causing any interactions with the series.

`chart.arrangeTooltips = false;` helped a bit.
`xAxis.snapTooltip = false;` also helped a bit.
These we both quite clearly visible in the profiler. The code base seems to iterate over all the series in several places, and if the amount of work for each series becomes nontrivial, having a thousand series is quickly going to cause problems.

I tried disabling cursor tooltips completely with the following:
```
xAxis.cursorTooltipEnabled = false;
yAxis.cursorTooltipEnabled = false;
seriesX.cursorTooltipEnabled = false; //for all the series
```
and the tooltips disappeared from the UI, as expected, but the profiler still showed a lot of CPU being burned calculating tooltips. (`e.showAxisTooltip` and `e.showSeriesTooltip` under `e.handleCursorPositionChange`). Only when completely removing the cursor (`am4charts.XYCursor`) was I able to make tooltip calculations disappear.

Still, making repeated hovering over the series (to show their actual tooltips) seemed slow.
Setting `tooltipPosition = "pointer";` for all the series helped a bit, since without it every cursor move seemed to cause a repainting of a series due to it being "invalid". This seems strange, could there be something in the code base causing too much invalidations?

Also, a function called getBBox seemed to show up a lot in the profiler. I would guess that bounding boxes aren't cached anywhere even if they are fairly static and used a lot? I didn't dig deeper yet, though.

So:
1. Maybe you might want to add some conditionals to the code base to skip tooltip calculations during cursor events, when the tooltips are actually disabled?
2. Could you perhaps investigate why an actual tooltip seems to always cause a repaint of the series? Or if this is working-as-expected, maybe investigate why tooltips seem to be such a resource hog?
3. Maybe investigate if bbox-calculations can/should be cached somehow?
4. If there's nothing to improve in the code base, maybe at least mention tooltips (and the properties listed here) in the Performance page, so that others could get better performance without going through a profiler?

Thank you!

Meanwhile, I'd be happy to learn more tips about improving performance.

**Comment by zeroin** [comment]
Thank you for your insights, they were really helpful. I already made some improvements based on them (I will let you know when a new release is ready).

I have a question - you say:

> Still, making repeated hovering over the series (to show their actual tooltips) seemed slow. Setting tooltipPosition = "pointer";

Do you talk about the situation where the cursor is not added? As I don't see a lot of sense to show tooltip on a series (if it's line series) when hovered the line it will show some generic text without any specific information based on the pointer position.

**Comment by zeroin** [comment]
Is there a chance you could create a sample codepen of the similar situation where the series is repainted when a tooltip is shown? As I can't reproduce this. 

getBBox is mostly called to measure label size, do you observe it called a lot when no tooltips are shown?

**Comment by jyrimatti** [comment]
Do you talk about the situation where the cursor is not added?
Yes. In my use case each series has a useful identity, so that generic text is actually useful.



[Here's](https://cdpn.io/jyri-matti/fullpage/yLYJXWz) a simple CodePen to demonstrate the additional tooltip calculations.
Start Chrome profiler and move the cursor back and forth over the empty chart for a couple of seconds to get something like this:
<img width="584" alt="Screenshot 2020-04-18 at 23 23 55" src="https://user-images.githubusercontent.com/1271944/79671680-e9930e00-81d4-11ea-81c9-5a2445a52301.png">

There's even seriestooltips and sorting them taking time even though there are no series added to the chart.
Setting `cursorTooltipEnabled=false;` doesn't help, but removing the whole XYCursor does. For my use case, I would like to keep the XYCursor for panning, but I don't need the axis tooltips.



Regarding invalidation and bbox, I might have made a mistake. It might have been my column series after all, and not the line series, but I'm not sure.
I wasn't able to reproduce a CodePen for it. However, the problem is visible in my actual project (not published yet, sorry). I have a few hundred overlapping 2D columns (filled rectangles) and if I move my cursor over them randomly for 15 seconds I get a profile like this:
<img width="752" alt="Screenshot 2020-04-18 at 23 54 57" src="https://user-images.githubusercontent.com/1271944/79671689-f9aaed80-81d4-11ea-8601-da48476ff393.png">

The large amount of time spent calculating bounding boxes seems strange since at this point I'm only displaying boxes and their tooltips (the default shape). Calculating bounding box of a box shouldn't be a big deal, unless the whole thing has to be redrawn for it. Of course, if this getBBox happens to contain all the time needed to actually draw the tooltip then this might be just fine (I don't know how much time drawing a tooltip _should_ take...).

This was with `tooltipPosition = "pointer";` with the default tooltipPosition the chart seems a lot laggier and I get this (after 15 seconds):
<img width="645" alt="Screenshot 2020-04-19 at 0 04 44" src="https://user-images.githubusercontent.com/1271944/79671691-ffa0ce80-81d4-11ea-9866-c85adb583255.png">

In this case the tooltips aren't even shown on the screen since they happen to be completely outside the current view.

Obviously removing the tooltips fixes this problem, but I have a feeling that there's some room for improvement regarding the performance of tooltips.

**Comment by zeroin** [comment]
Thanks a lo for more details.

I added some conditions to the latest release which should make things better when `seriesX.cursorTooltipEnabled = false`. However we can not completely disable all the calculations when cursor is moved, as we can't always know if user needs them or not. User might use `series.tooltipDataItem` (which is defined while cursor is moving)  for some external legend or some other stuff.
