### ISSUE TITLE
sort data with animation in runtime

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2340]
How sort data with animation in runtime for example by click button. I change ```sortBySeries``` but no thing change.
https://codepen.io/hassandl/pen/ExVjmbp

**Comment by martynasma** [comment]
If you need to sort the columns after chart is already initialized, you will also need to invalidate data, besides setting `sortBySeries`:

```
setTimeout(function () {
  categoryAxis.sortBySeries = series;
  chart.invalidateData();
}, 8000);
```

**Comment by HASSANDL** [comment]
Thanks, it correctly worked. 2 question:
1. How decrease sort animation speed
2. I use checkbox for sort, when user uncheck, set ```sortBySeries = undefined``` but animation not fire.
https://codepen.io/hassandl/pen/ExVjmbp

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by HASSANDL** [comment]
If chart type is LineSeries, sortBySeries not work. how sort in status with animation?
