### ISSUE TITLE
Logarithmic value axis can not have values <= 0.

### ISSUE THREAD

**Issue by niawjunior** [amcharts/amcharts4#2341]

**Comment by martynasma** [comment]
Is that a question?

**Comment by niawjunior** [comment]
> Is that a question?

Yeah, I try to use Logarithmic for scale my chart, but some data less than zero and I got an error

I saw some solution for fix this problem  https://stackoverflow.com/questions/54823997/amcharts4-proper-way-to-handle-zero-values-on-logarithmic-value-axis
but I think this is not the best practice. And I want to know you have the right way to fix this?

**Comment by martynasma** [comment]
There's no way to "fix" this. Math does not work that way. Sorry :(
