### ISSUE TITLE
decrease sort animation speed

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2342]
How decrease sort animation speed when change ```sortBySeries```?
https://codepen.io/hassandl/pen/ExVjmbp

**Comment by martynasma** [comment]
You can use `interpolationDuration` setting on your category axis:

```
categoryAxis.interpolationDuration = 2000;
```

the setting is in milliseconds. The bigger the number, the longer sorting animation will play out.

**Comment by HASSANDL** [comment]
Very thanks.
