### ISSUE TITLE
XYChart flickering on data change

### ISSUE THREAD

**Issue by danieldimitrov91** [amcharts/amcharts4#2344]
Hi,
I have created a XYChart with amcharts4 in angular 8 project. I have a socket connection and when I change the data the chart flickers instead of transition smoothly. I have tried different approaches from similar issues that I found, but it seems that they do not work for my case. I can provide my config if necessary.

![amcharts4-xychart-flickering](https://user-images.githubusercontent.com/5704839/79118349-5e5de680-7d96-11ea-9871-56a65f4fd593.gif)

Thank you!

**Comment by martynasma** [comment]
Does the number of data items change with each update? If not, you may use `invalidateRawData()` method:
https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points

**Comment by danieldimitrov91** [comment]
@martynasma the data may change couple of times in a second and may have more or less entries. That is why i need to change the whole data.

**Comment by martynasma** [comment]
In that case, I suggest disabling animations, so it does not animate, just updates to new data set.

**Comment by danieldimitrov91** [comment]
@martynasma the animation for this chart was disabled, but I found out that the animation of the other chart that I have was interfering with this one and that causes the issue. Now everything is ok. 

I have another question regarding this type of chart:
Is there a way to keep 50 / 50 ratio for the asks and bids even if I have data with different length?
![uneven_asks_and_bids](https://user-images.githubusercontent.com/5704839/79211174-8f99ed80-7e4e-11ea-90c5-4be8f793aa55.png)
![even_asks_and_bids](https://user-images.githubusercontent.com/5704839/79211186-945ea180-7e4e-11ea-9b24-7a98816c206f.png)


Thank you!

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by TheBodger** [comment]
hi , i have flickering issues that only occur when i have a second chart. How did you fix the issue you had with the 2nd chart causeing the issue ?
