### ISSUE TITLE
How to control the quantity of days displayed in the chart

### ISSUE THREAD

**Issue by CapInSpase** [amcharts/amcharts4#2345]
Hi, i have a chart with fake date with max period by 1 year. And I can’t find a parameter that is responsible for the number of days that I can view in the chart. That is, when a period of up to 6 months is selected, data is displayed for each day, but if 1 year is selected, data is displayed in increments of 7 days. How to make sure that when choosing a period of 1 year or 6.3.1 months, data is always displayed for each day?

[Example](https://codepen.io/fisherspoon/pen/pojJZza?editors=0010)

**Comment by martynasma** [comment]
You have data grouping enabled. If you don't need that, just disable it by removing this line in your code:

```
dateAxis.groupData = true;
```

More about data item grouping:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping

**Comment by CapInSpase** [comment]
Yes, I did.
But after that, the chart does not rebuild at the click of a button.


`  document.getElementById("seven_days").addEventListener("click", function() {
            var max = dateAxis.groupMax["day1"];
            var date = new Date(max);
            am4core.time.add(date, "day", -7);
            zoomToDates(date);
        });`

**Comment by martynasma** [comment]
You should probably use `DateAxis` method [`zoomToDates()`](https://www.amcharts.com/docs/v4/reference/dateaxis/#zoomToDates_method) instead of `zoom()`.

**Comment by CapInSpase** [comment]
In that code example and in the graph example, the **zoomToDates()** method is also used.

**Comment by martynasma** [comment]
I don't see any use of `zoomToDates()` in your CodePen example, you linked to in original post.

If you have another example, can you post it?

**Comment by CapInSpase** [comment]
Sorry, I looked in the wrong way, everything is correct, if you pass two dates, the schedule is rebuilt.
You can also tell what **dateAxis.groupMax ["day1"];**
And why does not work when turned off
**dateAxis.groupData = true**

**Comment by martynasma** [comment]
> Is there any method for simple work with dates? Get 1, 3, 6 months for example from today's date?

No, I'm afraid. You'll need to calculate start and end dates.

**Comment by CapInSpase** [comment]
You can also tell what dateAxis.groupMax ["day1"];
And why does not work when turned off
dateAxis.groupData = true

**Comment by martynasma** [comment]
If grouping is turned off, then no group-related properties are being calculated.
