### ISSUE TITLE
4.9.15 is having compilation error for angular

### ISSUE THREAD

**Issue by phxphx303** [amcharts/amcharts4#2348]
Today I saw an compilation error with the latest version 4.9.15

ERROR in node_modules/@amcharts/amcharts4/.internal/charts/axes/AxisRendererX3D.d.ts(68,15): error TS2416: Property '_chart' in type 'AxisRendererX3D' is not assignable to the same property in base type 'AxisRendererX'.
  Type 'MutableValueDisposer<XYChart3D>' is not assignable to type 'MutableValueDisposer<this["_chartType"]>'.
    Type 'XYChart3D' is not assignable to type 'this["_chartType"]'.
      Type 'XYChart3D' is not assignable to type 'Chart'.
        Types of property 'copyFrom' are incompatible.
          Type '(source: XYChart3D) => void' is not assignable to type '(source: this["_chartType"]) => void'.
            Types of parameters 'source' and 'source' are incompatible.
              Type 'this["_chartType"]' is not assignable to type 'XYChart3D'.
                Type 'Chart' is missing the following properties from type 'XYChart3D': _axisRendererX, _axisRendererY, columnsContainer, updateSeriesMasks, and 93 more.
node_modules/@amcharts/amcharts4/.internal/charts/axes/AxisRendererX3D.d.ts(100,5): error TS2416: Property 'chart' in type 'AxisRendererX3D' is not assignable to the same property in base type 'AxisRendererX'.
  Type 'XYChart3D' is not assignable to type 'this["_chartType"]'.
node_modules/@amcharts/amcharts4/.internal/charts/axes/AxisRendererY3D.d.ts(68,15): error TS2416: Property '_chart' in type 'AxisRendererY3D' is not assignable to the same property in base type 'AxisRendererY'.
  Type 'MutableValueDisposer<XYChart3D>' is not assignable to type 'MutableValueDisposer<this["_chartType"]>'.
    Type 'XYChart3D' is not assignable to type 'this["_chartType"]'.
      Type 'XYChart3D' is not assignable to type 'Chart'.
        Types of property 'copyFrom' are incompatible.
          Type '(source: XYChart3D) => void' is not assignable to type '(source: this["_chartType"]) => void'.
            Types of parameters 'source' and 'source' are incompatible.
              Type 'this["_chartType"]' is not assignable to type 'XYChart3D'.
                Type 'Chart' is missing the following properties from type 'XYChart3D': _axisRendererX, _axisRendererY, columnsContainer, updateSeriesMasks, and 93 more.
node_modules/@amcharts/amcharts4/.internal/charts/axes/AxisRendererY3D.d.ts(100,5): error TS2416: Property 'chart' in type 'AxisRendererY3D' is not assignable to the same property in base type 'AxisRendererY'.
  Type 'XYChart3D' is not assignable to type 'this["_chartType"]'.

**Comment by phxphx303** [comment]
Actually, 4.9.14 is having the same issue but 4.9.13 doesn't

**Comment by martynasma** [comment]
Thanks for the heads up. We're looking into it.

Will keep you posted.

**Comment by martynasma** [comment]
Just released 4.9.16 which should fix the issue. Let us know if you are still seeing the error after upgrading.
