### ISSUE TITLE
Add button next to a category name

### ISSUE THREAD

**Issue by aikodeio** [amcharts/amcharts4#2349]
Hello! I need to add a button next to the text of each category as it should redirect to different pages.

Can you help me add this?

Thank you very much :)

Example
![chart](https://user-images.githubusercontent.com/47112604/79186319-45c9ec80-7de7-11ea-9fd8-fff4ff74709a.jpg)

**Comment by zeroin** [comment]
You could use bullets of the axis, like these flags in this demo:
https://www.amcharts.com/demos/images-as-categories/

Positioning next the the end of label is a bit more trickier - I would add dx and dy adapter which would mesure label width and set half of the width for the dx value.

**Comment by aikodeio** [comment]
@zeroin Thank you! i'm going to try that solution
