### ISSUE TITLE
MapChart.zoomToRectangle

### ISSUE THREAD

**Issue by ilueckel** [amcharts/amcharts4#2350]
Hi,
I'm trying to zoom to rectangle on a map chart. The bounds are calculated by outer GeoPoints. But zooming with chart.zoomToRectangle(), with multiple or without zoomlevels, always zooms out the map as much as possible.

Here is an example fiddle: https://jsfiddle.net/3tex2amz/

I create 4 datapoints, which are the bounds for the zoomRectangle as well. I expect the map to zoom as high as possible while still displaying all 4 datapoints.

**Comment by zeroin** [comment]
I would recommend using series "inited" event instead of "datavalidated", as the chart is not yet build when data is validated:
```
polygonSeries.events.on("inited", function(ev) {
  chart.zoomToRectangle(55, 12, 50, 0);
});
```
