### ISSUE TITLE
Order book chart data visualization

### ISSUE THREAD

**Issue by danieldimitrov91** [amcharts/amcharts4#2352]
Hi,
Is there a way to keep 50 / 50 ratio for the asks and bids even if I have data with different length? For example 5 asks and 10 bids.

![uneven_asks_and_bids](https://user-images.githubusercontent.com/5704839/79211686-39797a00-7e4f-11ea-94ec-a9a394b2f453.png)

This is the desired effect.
![even_asks_and_bids](https://user-images.githubusercontent.com/5704839/79211695-3c746a80-7e4f-11ea-895c-a5ddc855bc3d.png)

Thank you!

**Comment by martynasma** [comment]
Yes. You will just need to use `ValueAxis` as your Y axis, not `CategoryAxis`.

**Comment by martynasma** [comment]
Also set its `min` and `max` or adjust data accordingly so it is ditributed like you ant it to.
