### ISSUE TITLE
The property textValign has no effect for chart with multiple axes

### ISSUE THREAD

**Issue by lk-geimfari** [amcharts/amcharts4#2354]
I'm trying to move titles of axes to the top of the chart, but I cannot figure out how to do it, because `textValign` does not work in my case, probably I'm doing something in a wrong way, idk.

Titles must be on the top, like this:

<img width="981" alt="Screenshot 2020-04-14 at 15 03 20" src="https://user-images.githubusercontent.com/15812620/79223044-4a32eb80-7e61-11ea-82ba-00101b308f2f.png">

There is a code:

```js
for (let axisConfig of axesConfigs) {
  let valueAxis = chartDetailed.xAxes.push(new am4charts.ValueAxis());
  valueAxis.tooltip.disabled = true;
  valueAxis.renderer.baseGrid.disabled = true;
  valueAxis.marginRight = 4;
  valueAxis.renderer.labels.template.adapter.add("text", (text, target) => null);
  valueAxis.renderer.gridContainer.background.fill = 'rgba(0, 0, 0, 0)';
  valueAxis.renderer.gridContainer.background.fillOpacity = 0.05;
  valueAxis.renderer.grid.template.stroke = interfaceColors.getFor("background");
  valueAxis.renderer.grid.template.strokeOpacity = 1;
  valueAxis.title.text = axisConfig.axis.titleName;
  valueAxis.title.textValign = 'top'; // <--------------
  valueAxis.renderer.grid.template.disabled = true;
  valueAxis.min = 0;
  valueAxis.max = 100;
  valueAxis.strictMinMax = true;

  let series = chartDetailed.series.push(new am4charts.ColumnSeries());
  series.dataFields.categoryY = "name";
  series.dataFields.valueX = axisConfig.series.valueX;
  series.xAxis = valueAxis;
  series.name = axisConfig.series.name;
  series.clustered = false;
  series.tooltipHTML = null;

  let label = series.columns.template.createChild(am4core.Label);
  label.text = "{valueX}%";
  label.fontSize = 13;
  label.valign = "middle";
  label.dx = 10;
  label.strokeWidth = 0;
}
```

**Comment by martynasma** [comment]
Axis title is positioned next to the axis itself. So if it is at the bottom (default) the title will be placed in axis container, so using any vertical alignment setting does not make sense.

Just place your value axis at the opposite side:

```
valueAxis.renderer.opposite = true;
```

**Comment by lk-geimfari** [comment]
@martynasma  Yeah, I tried it but this is the result:
<img width="1109" alt="Screenshot 2020-04-14 at 16 11 14" src="https://user-images.githubusercontent.com/15812620/79228727-9cc4d580-7e6a-11ea-9fa4-8034dff6d576.png">

But I need to move only titles, without changing the chart.

**Comment by martynasma** [comment]
Well, if you set `opposite` the axes are moved to other container, so you need to set layout on top container, instead of bottom:

```
chart.topAxesContainer.layout = "horizontal";
```
