### ISSUE TITLE
Adapter for the width property does not work

### ISSUE THREAD

**Issue by cmillottb** [amcharts/amcharts4#2355]
Adding an adapter for the width property of a rectangle like in the following snippet does not work, the callback is never executed. (Changing the adapter argument to an other property like opacity will work correctly)
```
let rect = series.columns.template.createChild(am4core.Rectangle);
rect.width = am4core.percent(100);
rect.height = am4core.percent(100);
rect.fill = am4core.color('red');
rect.adapter.add('width', (width, target) => {
  console.log(width, target.dataItem?.getValue('valueX'));
  return am4core.percent((target.dataItem?.getValue('valueX') || 100));
});
```
The expected behavior is that the callback will be called, the width and valueX will be logged, and the rectangle width will be set.

The actual behavior is that the callback is never executed.

The width property is listed in the Adapters of the Rectangle Class. https://www.amcharts.com/docs/v4/reference/rectangle/#width_adapter

**Comment by martynasma** [comment]
`width` is kinda consolidated setter. It's used to set width in various formats, but it's not actually used by the chart.

If you need to modify actual pixel width use `pixelWidth` adapter instead.

**Comment by cmillottb** [comment]
Thanks for your feedback.

The issue with pixelWidth is that it expects a number, and I need to set it as a percentage of the parent. Is there another way to do it?
I tried using a child chart, but in my specific usage, it was using too much resources, and was not usable because of the low framerate.

**Comment by martynasma** [comment]
In that case try using `percentWidth` adapter.

**Comment by cmillottb** [comment]
I think you meant `relativeWidth`. Thanks, using this property, I was able to set it as a percentage of the parent, it solved my issue.

**Comment by martynasma** [comment]
Yes, sorry. Good catch :)
