### ISSUE TITLE
Something broke in last two days.  Demo code is broke too. 

### ISSUE THREAD

**Issue by redliontrader** [amcharts/amcharts4#2359]

**Comment by redliontrader** [comment]
https://www.amcharts.com/demos/animated-gauge/

Since I used this as my template my gauge is also broken.  I just happened in the last day or so.

**Comment by martynasma** [comment]
Sorry for this.

In recent version we fixed the issue where `innerRadius` was being ignored.

This line:

```
axis2.renderer.innerRadius = 10;
```

We've fixed our demo (thanks for the heads up), and you should fix your chart configs accordingly.
