### ISSUE TITLE
Question: Listen to events globally

### ISSUE THREAD

**Issue by VictorJuliani** [amcharts/amcharts4#236]
Is it possible to listen to events globally instead of each series?
I want to listen to zoom (datarangechanged, for rangechangeended never seems to be triggered) events on the chart, but with multiple series these events are triggered once for each of them, flooding the callback.

By setting "chart.events.on('datarangechanged', handler, this)", the event fires only upon chart initialization and never after that.

**Comment by VictorJuliani** [comment]
In case someone has the same question, I have found the correct way to achieve this: add the event on the axis instead and it will be triggered only once, independently of the series count.

**Comment by martynasma** [comment]
Thanks for sharing your solution @VictorJuliani 

Yes, that what I would have suggested, had I gotten in time to read this ;)
