### ISSUE TITLE
How to fix a problem with tooltip indentation depending on the position of its appearance near the point

### ISSUE THREAD

**Issue by fisherspoon** [amcharts/amcharts4#2360]
Hi, I have to questions:
1.How to fix a problem with tooltip indentation depending on the position of its appearance near the point. I want to give a little indent from the point so that the tooltip appears abroad point.
If the tooltip is indented, for example, dx = 5. There will be a problem if the tooltip is adjusted on which side it is shown.
[Codepen](https://codepen.io/fisherspoons/pen/eYpJNRg)

If appears to the right of the point, everything is fine 
![Good!](https://user-images.githubusercontent.com/17007495/79318985-693c8680-7f10-11ea-93e4-697e02813b8e.png)

If appears to the left of the point, it's bad 
![Bad(](https://user-images.githubusercontent.com/17007495/79319134-98eb8e80-7f10-11ea-9944-396b49648293.png)

2.Is it possible to remove the first and last vertical lines in the chart?

![Screenshot_4](https://user-images.githubusercontent.com/17007495/79319423-f7b10800-7f10-11ea-966d-fc0fd5e78ded.png)

**Comment by martynasma** [comment]
Maybe with an adapter?

```
series.tooltip.adapter.add("dx", function(dx, target) {
  return target.background.pointerX < 0 ? 5 : -5;
});
```

Please post your other question separately. Let's keep this place clutter-free, both for our own sake and the other's.

**Comment by fisherspoon** [comment]
Yes, of course, thank you very much for 1 answer, it really helped!
