### ISSUE TITLE
external ledgend disposal documentation

### ISSUE THREAD

**Issue by nmase88** [amcharts/amcharts4#2362]
Hi,

Please could the documentation on [chart legend in an external container](https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/) please be updated to include the fact that they need to be disposed separately to the chart as stated [here](https://www.amcharts.com/docs/v4/tutorials/chart-was-not-disposed/). It's kind of important information and I wouldn't have noticed it if I hadn't stumbled across that page.

Thanks,
Nick

**Comment by martynasma** [comment]
Good point!

Added:
https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/#Disposing_external_legend
