### ISSUE TITLE
Bullet hover mode in legend

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2363]
I set hover mode for bullet and set event over & out for legend. after click legend and series disable and enable, show hover mode in legend.
https://codepen.io/hassandl/pen/NWGxpjB
![image](https://user-images.githubusercontent.com/22093903/79357439-44b6cd80-7f55-11ea-923f-69a05960aeb1.png)
![image](https://user-images.githubusercontent.com/22093903/79357479-54cead00-7f55-11ea-912d-ebe5526bd416.png)

**Comment by zeroin** [comment]
Bullet states ar copied to the bullet of the legend. So you need to remove the hover state. This should do the thing:

```
chart.legend.markers.template.events.on("inited", (event)=>{
  event.target.children.each((child)=>{
    child.states.removeKey("hover");
  })
})
```

**Comment by HASSANDL** [comment]
Very thanks.
