### ISSUE TITLE
Is it possible to remove the first and last vertical lines in the chart?

### ISSUE THREAD

**Issue by fisherspoon** [amcharts/amcharts4#2365]
Hi, how to remove the first and last vertical lines in the chart? Maybe there is some kind of setting?
![Screenshot_1](https://user-images.githubusercontent.com/17007495/79428557-fe05b980-7fce-11ea-9c01-a3e132218b3b.png)

[Codepen](https://codepen.io/fisherspoons/pen/eYpJNRg)

**Comment by zeroin** [comment]
This adapter should do the thing:

```
dateAxis.renderer.grid.template.adapter.add("opacity", function(opacity, target){
  if(target.pixelX < 1 || target.pixelX > chart.plotContainer.measuredWidth - 1){
    return 0
  }
  return opacity;
})
```

**Comment by fisherspoon** [comment]
Yes it works, but if the chart is updated, for example, by clicking on the button, sometimes a bug appears

[Codepen](https://codepen.io/fisherspoons/pen/pojgmPJ)

![Screenshot_1](https://user-images.githubusercontent.com/17007495/79451865-eab71600-7fef-11ea-8ac6-d9d6c2d3bac5.png)

**Comment by zeroin** [comment]
I see, this happens because opacity is set only initially and grid lines are reused. So I suggest workaround - add adapter for dx, return the same value but set opacity in the adapter:

https://codepen.io/team/amcharts/pen/69a91a5b7826a87ab92ebcd989452e95
