### ISSUE TITLE
ValueAxis hidden after update data

### ISSUE THREAD

**Issue by setiawans** [amcharts/amcharts4#2366]
Value axis is working properly for the first load, but after i updated data (we used select option to updating chart data) value axis hidden.
here is the screenshot 

@martynasma please give me suggestion to fix this issue.
thanks

Before
![Before](https://user-images.githubusercontent.com/5799999/79456152-32ea2e80-8018-11ea-9104-5f4003b5605c.png)

After
![After](https://user-images.githubusercontent.com/5799999/79456159-35e51f00-8018-11ea-850c-40eaa7c67c3f.png)

**Comment by martynasma** [comment]
Can you post a demo of your chart and what you are doing with "select option"?

**Comment by setiawans** [comment]
we just using boostrap select option and calling ajax when it changed.
btw, i found solution for this issue a few minutes ago.
try to add this code before update data.

`chart.parsingStepDuration = 500;`
