### ISSUE TITLE
Chart flashing on data refresh

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#2367]
I am using amCharts 4 and have my data set against each series. On each data refresh my chart flashes. Is there any way to stop this from happening?

Thanks

**Comment by martynasma** [comment]
We'll need a CodePen/jsFiddle demo to see what you're doing before we can provide any suggestions.

**Comment by towsie84** [comment]
I will work on getting a codepen created to show you. I amCharts 3 I previously used chart.validateData as the data was set against the chart. Is there anything similar in amCharts 4 for when the data is set against a series in a XYChart lineseries.

**Comment by martynasma** [comment]
Thanks.

Please refer to this doc about dynamic data updates in V4:
https://www.amcharts.com/docs/v4/concepts/data/#Dynamic_updates

**Comment by towsie84** [comment]
Regarding the section on "Manipulating existing data points" all the example for using invalidateData() and invalidateRawData() is for when data is set against the chart. How would I implement either of these when the data is set against a series?

**Comment by martynasma** [comment]
It works exactly the same for series. If you have your data set on series, then you call those methods on series as well, e.g.

```
series.invalidateRawData();
```

**Comment by towsie84** [comment]
Would that have to be done for each series created on the chart?

**Comment by martynasma** [comment]
Yes. Refreshing data on one series does not affect other series.

**Comment by geervani** [comment]
Hi,
we have somewhat same issue.. we have an amcharts 4 - XYChart. The data is is refreshed frequently. Also we have a slider, which loads charts with diferent data(XYChart).

Issue is, when we slide, the previous panel data flickers for a second and then load the current chart data.

Tried removing the animation and also tried series.invalidateRawData();.. but not working..

Thanks

**Comment by kh1msh0** [comment]
> https://www.amcharts.com/docs/v4/concepts/data/#Dynamic_updates

did you manage to fix that?
