### ISSUE TITLE
No organization Chart available

### ISSUE THREAD

**Issue by Bunny1991** [amcharts/amcharts4#2368]
I'm using amcharts from past 2 years and it has humongous  number of charts and customization if we compare with others but today when i was checking all the demos i didn't find **Org**. chart or **Hierarchy** chart in the list of charts.
Could you please through some light on this chart availability in the library as i found it a major miss. When amchart is adding or any plan of adding it in the library.

**Comment by martynasma** [comment]
At this time we're not planning on implementing Org Chart.

**Comment by bsplosion** [comment]
Sadly, missing this functionality also removed amCharts as a contender for us.
