### ISSUE TITLE
XYChartScrollbar Desaturate filter removal from clone isn't working as intended

### ISSUE THREAD

**Issue by rodizipa** [amcharts/amcharts4#2370]
**Browser:** Google Chrome 80
**Amcharts4 version:** 4.9.16

Reading https://www.amcharts.com/docs/v4/tutorials/customizing-chart-scrollbar/ and trying to remove the desaturation filter from the scrollbar series isn't work as intended. 

`let scrollSeries1 = chart.scrollbarX.scrollbarChart.series.getIndex(0);
scrollSeries1.filters.clear();`

Even the example that used to have the scrollbar series colored is gray. Possible bug or working as intended? The preview of the pen example showcases the old behavior coloring the series, running it shows gray series.

![image](https://user-images.githubusercontent.com/17985067/79501961-522b9080-8005-11ea-8b25-5d9b8f2b24da.png)

Pen: https://codepen.io/team/amcharts/pen/OJLwMGg

**Comment by martynasma** [comment]
Thanks for bringing this to our attention!

We no longer apply `Desature` each series individually, but rather the whole plot area of the scrollbar chart. So this should be now use to remove desaturation of the series in scrollbar:

```
chart.scrollbarX.scrollbarChart.plotContainer.filters.clear();
```

Updating the docs as we speak.
