### ISSUE TITLE
How to fix tooltip by click?

### ISSUE THREAD

**Issue by fisherspoon** [amcharts/amcharts4#2372]
Hi! How to lock tooltip on click? But continue to show the rest when you hover, and after the next press, rearrange the fixed tooltip to a new location. 

[Codepen](https://codepen.io/fisherspoon/pen/pojJZza?editors=0010)

**Comment by martynasma** [comment]
This could work using this workflow:

1) Add bullets on your line series
2) Add `tooltipText` to bullets
3) Once you click on the plot area set `alwaysShowTooltip` on bullets under the date/category of the click (see for a tutorial link below on how to track it)
4) Remove `alwaysShowTooltip` from previously "activated" bullets

Here's a link which explains how to determine cursor's position on click:
https://www.amcharts.com/docs/v4/tutorials/tracking-cursors-position-via-api/

Unfortunately, I don't have a ready-made example.

Hope this helps if you'd like to take a stab at implementing it.
