### ISSUE TITLE
Can't access "active" state of columns in stacked bar charts

### ISSUE THREAD

**Issue by jhadenfeldt** [amcharts/amcharts4#2373]
I have created a demo here: https://codepen.io/jhadenfeldt/pen/ExVyaKr

When I am trying to access the `active` state of a column like so:
```
  series.columns.template.states.getKey(
    "active"
  ).properties.opacity = 1;
```

I am getting a JS error:
```
Uncaught TypeError: Cannot read property 'properties' of undefined
```

Doing the same, but for the `default` state works without any issues. I've also been successfully doing the same with a pie chart.

**Comment by martynasma** [comment]
Columns do not have "active" state created by default, hence the error.

If you need to use it for something, you need to create that state first:

```
series.columns.template.states.create("active");
```

**Comment by iamtomhanks** [comment]
@martynasma Can I create an active state on a column segment? Would this require a different input data format?

**Comment by martynasma** [comment]
What is a "column segment"?

**Comment by iamtomhanks** [comment]
> What is a "column segment"?

Instead of an entire column or series being active, just one of the stacked portions of the columns. One stack column.

**Comment by martynasma** [comment]
You can apply active state to particular column of particular series, e.g.:

```
series.columns.getIndex(5).isActive = true;
```

**Comment by iamtomhanks** [comment]
> You can apply active state to particular column of particular series, e.g.:
> 
> ```
> series.columns.getIndex(5).isActive = true;
> ```

Oh awesome, do you know how I would combine that with a 'hit' handler?

**Comment by martynasma** [comment]
Do you mean click on the column itself?

```
series.columns.events.on("hit", function(ev) {
  ev.target.isActive = true;
});
```

**Comment by iamtomhanks** [comment]
I tried that before. I'm using TypeScript and am getting:

```
Argument of type '"hit"' is not assignable to parameter of type '"inserted" | "removed" | "setAll" | "insertIndex" | "setIndex" | "removeIndex"'. 
```

**Comment by iamtomhanks** [comment]
Oh, you might have meant to add ```.template```. But following the data structure implemented by many graphs in amcharts, my data is like: ```{categoryX: 'Gender', male: 45, female: 65}```, and adding isActive as a property, makes the whole column active.

**Comment by iamtomhanks** [comment]
Do you understand my problem, or do you need more information?

**Comment by martynasma** [comment]
Yes, sorry my bad. The `.template` part is missing:

```
series.columns.template.events.on("hit", function(ev) {
  ev.target.isActive = true;
});
```

Though, I don't understand the issue. This will apply hover on the specific section/column of the series.

**Comment by iamtomhanks** [comment]
> Yes, sorry my bad. The `.template` part is missing:
> 
> ```
> series.columns.template.events.on("hit", function(ev) {
>   ev.target.isActive = true;
> });
> ```
> 
> Though, I don't understand the issue. This will apply hover on the specific section/column of the series.

Ah no worries. I want to have the data provide the active state, via a data-field. But the data context in the ev.target above, will be the data context for that categories' column, the entire column.

Basically, I want to have a stacked column chart, and I want to bind the active state for individual category-series pairings (stacks), in the data, and not set 'active' explicitly.
