### ISSUE TITLE
DateAxis change value of first label

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2374]
How change value of first label in dateAxis?

**Comment by martynasma** [comment]
It depends on what you want to change it to.

Is it just format or something completely custom?

Does it depend on actual date/time? Data values?

Please consider providing more details of what you are trying to achieve, and what you have tried so far, so that we can help you better.

**Comment by HASSANDL** [comment]
my data is for 2 years and start from Nov but chart show labels for Jan & Jul.
I show labels for Feb and Jun.

**Comment by martynasma** [comment]
You may need to increase granularity of your grid/labels:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by HASSANDL** [comment]
I don't want number of labels, I want change first label start in Feb and same period 6 months.
```"Jan" next label "Jul" -> "Feb" next label "Aug"```

**Comment by martynasma** [comment]
In that case you may need to use "axis ranges" to set labels at arbitrary places.

https://www.amcharts.com/docs/v4/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/
