### ISSUE TITLE
Pinbullet image in force directed tree stays the same.

### ISSUE THREAD

**Issue by ShashankAnantharam** [amcharts/amcharts4#2375]
Earlier, I raised an issue regarding image shapes in a force directed graph for which I got a satisfactory answer using Pin bullets. That answer can be viewed here: https://codepen.io/team/amcharts/pen/84a44875f99ada4004aff1ee042856fd

Now, I face a different problem with that same code. When I want to increase the image dimensions, but I cannot do so.

The change in my code is following:
```
            var icon = series.nodes.template.createChild(am4plugins_bullets.PinBullet);
            icon.image = new am4core.Image();
            icon.image.propertyFields.href = "image";
            icon.circle.radius = 40;      icon.image.width = 80;       icon.image.height = 80;
            icon.circle.strokeWidth = 0;
            icon.background.pointerLength = 0;
```

I have put my code with these changes in Codepen here:
https://codepen.io/sandwraith/pen/mdeExeQ

**Expected output**: Radius and image dimensions both increase.
**Observed output**: Radius increases but image dimensions remain the same.

I kindly request you to help me resolve this.

**Comment by martynasma** [comment]
To set size of the image in a `PinBullet` you need to increase background radius:

```
icon.background.radius = 60;
```

**Comment by ShashankAnantharam** [comment]
Hi,
   I have another issue regarding dynamically created links in a Force
Directed Tree. I have posted it here:
https://github.com/amcharts/amcharts4/issues/2422
Yours sincerely,
Shashank
