### ISSUE TITLE
DateAxis GroupData breaks on LineChart with smaller incremental dates

### ISSUE THREAD

**Issue by migee** [amcharts/amcharts4#2376]
I've was not able to have GroupData work for me when trying it against my particular data. After reviewing [the demo](https://codepen.io/team/amcharts/pen/wvvKQBK) and what I was [attempting to do](https://codepen.io/migee/pen/bGVeaQa), the only difference came down to the data. 

Once I fiddled with the demo to see if I could get it to break, the breaking change was having dates on the dateaxis having 30 minutes inbetween as opposed to the demo's one day increments, the rendering appears to break down.

Setting baseinterval seems to break it further if I try to resolve the issue

```
dateAxis.baseInterval = {
   "timeUnit": "minute",
   "count": 30
};
```

@1000 Dates 30 min increments
![image](https://user-images.githubusercontent.com/10858619/79672223-0829e280-819e-11ea-9b94-eee5ec51c346.png)

@5000 Dates 30 min increments (constantly refreshes, then breaks)
![image](https://user-images.githubusercontent.com/10858619/79672239-268fde00-819e-11ea-9a2a-3fd9bd5495a7.png)

Mid-post update:

I was also having _many, many issues_ with other parts of the functionality until I came across #1466 causing me to have lost several hours of trying to figure out why this was. The dates were ordered, however descending rather than ascending. If I had known this it would have helped a lot, or at least have some kind of error output (as you can see the graph when raising to 5000 items completely breaks with no error or console output). 

Should there not be some kind of exception being thrown? Or perhaps the documentation should be updated? I could not find this requirement called out somewhere that dates need to be pre-sorted in a particular manner. Posting this to have more visibility on this issue for others who might be struggling with something similar.

**Comment by zeroin** [comment]
Thank you for the notice, we will check the places where we could mention about sorted data.
So to be clear - can we call this resolved, as if I reverse your data array in your pen, the chart works as expected for me.

**Comment by martynasma** [comment]
@migee We already have the[ whole section](https://www.amcharts.com/docs/v4/concepts/data/#Order_of_data_items) devoted to order of data items.

We also just added a [note](https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Order_of_date_based_data) in `XYChart` article.

**Comment by migee** [comment]
@martynasma  @zeroin you guys are awesome! Thanks!
Just want to avoid others going through a similar ordeal
