### ISSUE TITLE
Adding ranges to multiple series with the same axis causes a strange unexpected behaviour

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#2377]
Code: 
```

  private addStartPauseGuides(chart: am4charts.XYChart, xAxisType: XAxisTypes, series: am4charts.XYSeries[]) {
    // const xAxis = <am4charts.ValueAxis>chart.yAxes.getIndex(0);
    // xAxis.axisRanges.template.grid.disabled = false;

    series
      .forEach((serie, seriesIndex) => {
        if (seriesIndex !== 0) {
          return;
        }
        const activity = serie.dummyData.activity;
        const stopEvents = activity.getStopEvents();
        const stopAllEvents = activity.getStopAllEvents();
        activity.getStartEvents().forEach((startEvent, startEventIndex) => {
          if (startEventIndex === 0) {
            return;
          }
          let range;
          let stopEvent;
          console.log(serie.name);
          range = serie.xAxis.createSeriesRange(serie);
          stopEvent = stopEvents[startEventIndex - 1] ? stopEvents[startEventIndex - 1] : stopAllEvents[startEventIndex - 1];
          range.date = new Date(activity.startDate.getTime() + stopEvent.getValue() * 1000);
          range.endDate = new Date(activity.startDate.getTime() + startEvent.getValue() * 1000)
          range.contents.stroke = am4core.color("#f00");
          range.contents.fill = am4core.color("#f00");
          range.contents.fillOpacity = 0.5;
        })
      });
  }
```

Result ok: 

<img width="828" alt="Screenshot 2020-04-19 at 20 31 52" src="https://user-images.githubusercontent.com/1268723/79696422-f53a0f80-827c-11ea-80df-2011631cecf9.png">

Code: 

```

  private addStartPauseGuides(chart: am4charts.XYChart, xAxisType: XAxisTypes, series: am4charts.XYSeries[]) {
    // const xAxis = <am4charts.ValueAxis>chart.yAxes.getIndex(0);
    // xAxis.axisRanges.template.grid.disabled = false;

    series
      .forEach((serie, seriesIndex) => {
        if (seriesIndex !== 0) {
        
        }
        const activity = serie.dummyData.activity;
        const stopEvents = activity.getStopEvents();
        const stopAllEvents = activity.getStopAllEvents();
        activity.getStartEvents().forEach((startEvent, startEventIndex) => {
          if (startEventIndex === 0) {
             return
          }
          let range;
          let stopEvent;
          console.log(serie.name);
          range = serie.xAxis.createSeriesRange(serie);
          stopEvent = stopEvents[startEventIndex - 1] ? stopEvents[startEventIndex - 1] : stopAllEvents[startEventIndex - 1];
          range.date = new Date(activity.startDate.getTime() + stopEvent.getValue() * 1000);
          range.endDate = new Date(activity.startDate.getTime() + startEvent.getValue() * 1000)
          range.contents.stroke = am4core.color("#f00");
          range.contents.fill = am4core.color("#f00");
          range.contents.fillOpacity = 0.5;
        })
      });
  }
```

result NOK
<img width="825" alt="Screenshot 2020-04-19 at 20 35 33" src="https://user-images.githubusercontent.com/1268723/79696507-64176880-827d-11ea-8264-fc2fb6049273.png"> 

What is going on ?  The only thing that changes is to apply the ranges to many series  (see `  if (seriesIndex !== 0) {` ) which only stops from adding the ranges to more than one series 

^^^ please check updated issue as of now

**Comment by jimmykane** [comment]
it kinda looks like its leaking 

<img width="829" alt="Screenshot 2020-04-19 at 20 50 57" src="https://user-images.githubusercontent.com/1268723/79696863-81e5cd00-827f-11ea-9c83-5037434bd980.png">

**Comment by jimmykane** [comment]
This doesn't happen when one is not using the stacked axis 
<img width="1440" alt="Screenshot 2020-04-20 at 09 30 34" src="https://user-images.githubusercontent.com/1268723/79725510-9c549080-82e9-11ea-9c37-3f472bc09249.png">

**Comment by jimmykane** [comment]
Any clue on how to proceed ?

**Comment by jimmykane** [comment]
<img width="967" alt="Screenshot 2020-04-20 at 19 10 22" src="https://user-images.githubusercontent.com/1268723/79779396-a488ec00-833a-11ea-987e-416cb72a85af.png">

It looks like it kinda drops a little out of the y axis

**Comment by jimmykane** [comment]
Oe more thing I notice here is the cursor 

<img width="928" alt="Screenshot 2020-04-20 at 19 59 05" src="https://user-images.githubusercontent.com/1268723/79783770-72c75380-8341-11ea-8779-661c0cb01436.png">


Any insights or help here where to start @martynasma @zeroin  ? Would be much appriciated

**Comment by martynasma** [comment]
@jimmykane We always try to help and get to the bottom of it, especially when it's probably a bug. But having us reproduce issues from screenshots and code scraps makes it much more difficult and thus takes significantly longer.

If you could share a bit of workload with us by producing a standalone reduced-case demo we can run to reproduce the issue, we'd be able to move dramatically faster.

Hope that sounds reasonable :)

**Comment by martynasma** [comment]
P.S. check this out :)
https://shmetrix.com/visualizing-my-yearly-bike-rides-or-other-activities/

**Comment by jimmykane** [comment]
Omg. I'll try to implement it 🤣

That said sometimes I open bugs in case someone has this, or if you guys
already suspect an issue or is something know.
