### ISSUE TITLE
Using a series template to create a new series is slow

### ISSUE THREAD

**Issue by jyrimatti** [amcharts/amcharts4#2378]
Using a series template to create a new series takes a lot of time comparing to not using a template.

If you load [this CodePen](https://cdpn.io/jyri-matti/fullpage/VwvjBoO) with Chrome profiling you get something like the following:
<img width="479" alt="Screenshot 2020-04-19 at 21 22 14" src="https://user-images.githubusercontent.com/1271944/79696615-734ee400-8286-11ea-8b87-b43198048caf.png">

Most of the time is spent in cloning the series template (or whetever is happening). Replacing `var series = chart.series.create();` with `var series = chart.series.push(new am4charts.LineSeries());` fixes the issue.

In this example the template is completely empty. If I add stuff to it the situation seems to get even worse, although I didn't perform any more measurements. I also didn't measure whether this is only about series templates or every kind of template.

I would think templates should _improve_ performance instead of hurting it, since I guess they allow the framework to perform some operations in advance and possibly reuse structures.

Could you have a look why templates are so slow? Please let me know if I can be of any help.

**Comment by martynasma** [comment]
No, I'm afraid, templates are there for convenience not as a mean to improve performance.

What happens when you create a template clone is that **all** its properties are being copied, hence it being slower than what you would normally get by creating a blank template.

This is a fundamental part of how amCharts 4 works, so I'm afraid there's nothing to be done to improve template performance.

I suggest instead of using `template.create()`, use a custom function `myCustomSeries()` which instantiates new series and sets properties as required.

**Comment by jyrimatti** [comment]
Thank you for a quick answer!

Since the performance impact seems quite considerable (the example loads about twice as slow with templates), maybe this should be mentioned in the "Improving chart performance" page?

What about "deeper" cases where amcharts is creating something itself based on a template, for example columns or bullets? How can I replace bullet templates with a function?

Would it be possible to extend the template mechanism to understand a template function in addition to a template object? If a function is provided, its return value would be used instead of cloning anything? Or would this not work for some fundamental reason?

**Comment by martynasma** [comment]
> Since the performance impact seems quite considerable (the example loads about twice as slow with templates), maybe this should be mentioned in the "Improving chart performance" page?

Well, using templates to create series is not a technique we encourage everywhere, and I don't think it's widely used, so adding it to performance tutorial might be somewhat confusing. Also having large numbers of series is not what people usually do anyways, while cloning just a few series would not have any significant performance impact.

> What about "deeper" cases where amcharts is creating something itself based on a template, for example columns or bullets? How can I replace bullet templates with a function?

Series is created by user. What is created by an engine is another matter. You would not want to be responsible for creating every line segment, bullet, column, fill, label, axis grid line, tick, etc. It's just simply not feasible.

> Would it be possible to extend the template mechanism to understand a template function in addition to a template object? If a function is provided, its return value would be used instead of cloning anything? Or would this not work for some fundamental reason?

I'm intrigued by your template/function suggestion. Right now the only way to automatically populate a `TemplateList` is to create deep clones of its `template`.

If in addition you could set a custom function that returns proper object, that could work as well, and might save some CPU cycles in the process.

I'll make sure we discuss this, and will keep you posted.

Thanks!

**Comment by martynasma** [comment]
Hey, just had a wild thought: why don't you just override list's `create()` method with your own?

```
chart.series.create = function() {
  var series = var series = chart.series.push(new am4charts.LineSeries());
  // set defaults
  return series;
};
```
