### ISSUE TITLE
ColumnSeries columns sometimes disappear when scrolling

### ISSUE THREAD

**Issue by jyrimatti** [amcharts/amcharts4#2379]
Here's a column series with some real data: https://codepen.io/jyri-matti/pen/VwvjJNR

If you scroll left the columns will suddenly appear. If you keep scrolling, at some point some of the columns may disappear and after yet more scrolling reappear, even though the columns in question should be visible all the time. What I mean is, that sometimes (all the time) when scrolling a column disappears even though it is still on view.

Why is this happening? I haven't been able to find a workaround, and I wasn't able to reproduce this with minimal fake data. Is there some way to turn on any debug messages to see if something is failing somewhere?

**Comment by martynasma** [comment]
This is most probably is happening because `DateAxis` expects data items ordered in ascending order, whereas date values for `dateX` data field are all over place.

Try ordering your data by "loppuX" field in data.

**Comment by jyrimatti** [comment]
The "Data" guide says on its [Order of data items](https://www.amcharts.com/docs/v4/concepts/data/#Order_of_data_items) section:
> If you have a series, that is not connected by lines, you should be good to go.

Maybe it needs an update?

Anyway, I updated the pen with sorting, but I'm afraid it doesn't fix the problem. Changing the sorting - either sort first by start time (alkuX) and then by end time (loppuX), or the opposite - indeed seems to change what columns show up, but they keep disappearing ~randomly when scrolling.

Would you happen to have another suggestion I could try out, or maybe give me some hints on how to replicate the behavior with dummy data?

**Comment by martynasma** [comment]
OK, so it's not it. We'll need to dig a bit deeper. Will let you know if we need any assistance in reproducing this or distilling into a less cluttered example.

**Comment by zeroin** [comment]
Setting base axis of a series to yAxis should solve the problem:

`seriesEI.baseAxis = yAxis;`

**Comment by jyrimatti** [comment]
This indeed seems to fix it, thank you!
Would there be a simple explanation why this is needed? Should this possibly be mentioned in some guide?

**Comment by martynasma** [comment]
`DateAxis` has it's own logic on arranging a scale and manipulating granularity of data. When combined with `dateX` and `openDateX` fields it may lead to unpredictable results, like you experienced.

By setting `baseAxis` to the Y axis, we're taking out the series out of `DateAxis` "jurisdiction", which solves the issue.

I know it's vague, but I hope it makes sense :)
