### ISSUE TITLE
Flat line series stroke width not working

### ISSUE THREAD

**Issue by a30000329** [amcharts/amcharts4#2380]
Please compare [this](https://codepen.io/alexfan/pen/BayvVgB?editors=0011) 
![image](https://user-images.githubusercontent.com/46702190/79706427-94521c00-82fc-11ea-9e40-d1cf7931d243.png)

with [this](https://codepen.io/alexfan/pen/BayvVgB?editors=1111)
![image](https://user-images.githubusercontent.com/46702190/79706397-784e7a80-82fc-11ea-81c3-310e632200b9.png)

this issue only happens when there is a flat line

**Comment by zeroin** [comment]
This happens because SVG has issues with straight lines and filters. This line should fix the issue:

`series.filterElement.attr({filterUnits:"userSpaceOnUse"});`

For some internal reasons we can not make this as default.

**Comment by a30000329** [comment]
Please note that with this change (https://codepen.io/alexfan/pen/BayvVgB?editors=0011):
- it breaks the tooltip snap-on data point
- it makes a console error

![image](https://user-images.githubusercontent.com/46702190/79720261-8d8acf80-8323-11ea-8f5b-cc7d5407c63b.png)

**Comment by zeroin** [comment]
Sorry, it should be after the sprite is validated:

```
        series.events.on("validated", function(){
          series.filterElement.attr({filterUnits:"userSpaceOnUse"});
        })
```

I will think if we can add this as a property of a filter for an easier use.

**Comment by zeroin** [comment]
In v 4.9.17 you can set:

```
var seriesShadow = series.filters.push(new am4core.DropShadowFilter());
seriesShadow.filterUnits = "userSpaceOnUse";
```

**Comment by martynasma** [comment]
FYI, just posted this:
https://www.amcharts.com/docs/v4/tutorials/fixing-gradients-and-filters-on-straight-lines/

**Comment by a30000329** [comment]
thanks a lot guys
