### ISSUE TITLE
IE 11 not drawing the line for XYChart

### ISSUE THREAD

**Issue by a30000329** [amcharts/amcharts4#2382]
When you tried this (https://codepen.io/alexfan/pen/mderPOM?editors=0011),  you will get this in IE11:
![image](https://user-images.githubusercontent.com/46702190/79726374-05f68e00-832e-11ea-9eca-535f416901dd.png)

In our real angular application, I have tried adding
`import 'core-js';`
into polyfill.ts file, but it does not make a difference

**Comment by zeroin** [comment]
It's again filters which cause the issue. I am looking into it, but the filters and IE11 doesn't work well, as it's an old browser and quite a buggy one. Meanwhile I could suggest not to add a dropshadow filter for the line series (at least when browser is IE11). I will let you know when I'll  have some more details.

**Comment by zeroin** [comment]
So I must say I can't find a reason why IE11 does not display line when a filter is added. So for now our solution will be to clear filters from line series if it's IE. We will add a checkup in next release, meanwhile you can easily check if it's IE and not to add a filter to the series in the following way:

```
if (!am4core.utils.isIE()) {
  var seriesShadow = series.filters.push(new am4core.DropShadowFilter());
  seriesShadow.dx = 0;
  seriesShadow.dy = 10;
  seriesShadow.opacity = 0.5;
  seriesShadow.height = 200;
  seriesShadow.blur = 2;
  series.stroke = am4core.color('#00DFED');
}```

**Comment by a30000329** [comment]
thanks for the clarification :)

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
