### ISSUE TITLE
Chart will not rendered when not in visible view

### ISSUE THREAD

**Issue by mdevDE** [amcharts/amcharts4#2385]
Hi there, I am using amcharts (4.9.16) in vue js. I experience a problem when trying to create a XYchart when the Div for this chart is not in the visible viewport. The chart will not be rendered, only after resizing the page but still when the chart div in the visible viewport. I have checked this in google chrome, safari, Firefox and opera (macoxs 10.5.3) safari (iOS 13). Is there something I am doing wrong? Could you please advise.

Kinder regards,

Michael

**Comment by martynasma** [comment]
Can you post and example we can test?

**Comment by ankytkedia** [comment]
@mdevDE @martynasma was this issue solved ? please see the attached image - when the chart (at the time page loads) is not in view port - it does not appear properly - notice the lines from left chart to right one


![image](https://user-images.githubusercontent.com/42583811/88275392-f60a9380-ccfa-11ea-8f67-bf5c4f84955d.png)
