### ISSUE TITLE
AxisRange on DateAxis line not drawing on correct date

### ISSUE THREAD

**Issue by madnivek** [amcharts/amcharts4#2386]
Hello,

I am attempting to use `AxisRange` on a `DateAxis` to draw a reference line on a line series chart, but the reference line does not appear to align with the specific date that I have set.

Here is a simple example forked from one of your documentation examples: [https://codepen.io/madnivek/pen/yLYaPge](url)

Note where I create the reference line:

```
var line = dateAxis.axisRanges.create();
line.date = chart.data[2].date;
line.grid.stroke = am4core.color('red');
line.grid.strokeWidth = 2;
line.grid.strokeOpacity = 1;
```

Notice that the red line is not being drawn exactly on the third datapoint, but instead is offset to the left. 

I have also attempted to offset the `location` of the grid by using `line.grid.location = 0.5`, but that does not seem to do anything.

Is there something I'm missing here?

Any help would be appreciated, thank you!

**Comment by xorspark** [comment]
The axis range is drawn in the correct location as the dates are placed in the center of the range and your value is set to midnight. The data points, however, are centered by default. You can change this behavior by setting `series.dataItems.template.locations.dateX = 0;`

[Updated pen](https://codepen.io/team/amcharts/pen/c75033524d7343e4e1dfe826b0f9e03e?editors=0010)

**Comment by madnivek** [comment]
For anyone who may be following this ticket, the amcharts official response from amcharts to align series and date axis labels with reference lines drawn by `AxisRanges` is to manually set all of their `locations` to 0 as `AxisRanges` are by default drawn at `location` 0

```
dateAxis.renderer.labels.template.location = 0;
dateAxis.renderer.tooltipLocation = 0;
series.dataItems.template.locations.dateX = 0;
```

[Updated codepen
](https://codepen.io/madnivek/pen/yLYaPge)

Hope this helps anyone who has been trying to do the same!

**Comment by goodmorninggoaway** [comment]
Does this work for date-times other than midnight?

**Comment by goodmorninggoaway** [comment]
I thought I was doing something wrong in my complex chart, but I forked @madnivek example and set all the times to 1030. It seems the axis range has some affinity to midnight regardless of time zone. Example: https://codepen.io/goodmorninggoaway/pen/GRNmBOq
