### ISSUE TITLE
external ledgend and onlyShowOnViewport/queue

### ISSUE THREAD

**Issue by nmase88** [amcharts/amcharts4#2387]
When using an external ledgend and trying to use onlyShowOnViewport and/or queue the external ledgend doesn't seem to render. I've tried moving the code for the external ledgend into a chart event but it still doesn't seem to work. 
Could you advise if there is something additional that needs to be done for this? or does external ledgend just not work with onlyShowOnViewport or queue? 

version 4
chrome
typescript

**Additional context**

**Comment by martynasma** [comment]
I can't seem to be able to reproduce this.

Here's what I'm working with:
https://codepen.io/team/amcharts/pen/bcb5ff2cd99ddf9cda37874919ff83ca

When I scroll down to the chart and legend both appear fine.

Can you post your chart in CodePen, or if not possible CodeSandbox?

**Comment by nmase88** [comment]
that's odd, i'll try and put something together later today and post. thank you.

**Comment by martynasma** [comment]
Could be a version issue. Are you on latest amCharts 4 version? (4.9.17)

**Comment by nmase88** [comment]
Yes I am, we updated recently. Oddly enough, now i'm testing today queue is working fine and that was also giving me an issue yesterday. I've made a few adjustments in the last 24 hours so it must have been something on my end. 

Before I/you close it down could you just advice me. The onlyShowOnViewport isn't working still because the charts are in a scrollable container. Now I can see that there is a viewportTarget for this, but the page for that is empty. What exactly is this option expecting? HTMLElement or a string for the id or something else?

**Comment by martynasma** [comment]
Thanks for the heads up about docs page being broken. We'll need to fix that.

Yes, it expects either a reference to HTMLElement, or an array with references if you have few containers to watch for.

**Comment by nmase88** [comment]
great thanks martynasma! thanks for looking into my issue for me too.
