### ISSUE TITLE
Color does not get available after removing and disposing the series that was using it

### ISSUE THREAD

**Issue by thefat32** [amcharts/amcharts4#2389]
**Bug description**
I have a simple code that switches the chart between columns and lines. When the switch is triggered 
I remove and dispose the series and then I proceed to recreate them again whether the new ones are columns or lines. The problem is the colors provided to the chart through `chart.colors.list` property are not released to use again, and the new series got gray colored.

The code to remove and dispose series:

```typescript
const seriesCount = chart.series.length;
for (let i = 0; i < seriesCount; i++) {
    chart.series.removeIndex(0).dispose();
}
```

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Chart's ColorSet has internal counter which does not get reset when you remove series.

You can do do so like this:

```
chart.colors.reset();
```

**Comment by thefat32** [comment]
Thank you!
