### ISSUE TITLE
Is v4 somewhat ready to use in real project?

### ISSUE THREAD

**Issue by bcronje** [amcharts/amcharts4#239]
Not sure where else to ask this. I'm starting a new project and want to use amCharts. Is the recommendation to still use v3, or is v4 in a state to start using it in a new project?

**Comment by martynasma** [comment]
v4 definitely.

If you're just starting it means you're probably months away from the release. v4 is pretty stable as it is, and there are no breaking changes planned anymore. It's suitable for testing and development, and most probably will lose beta tag before you release.

**Comment by bcronje** [comment]
Perfect, thank you @martynasma
