### ISSUE TITLE
How to add 2 proportionally related xAxis?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#2390]
(hi, and sorry for my bad english)
I have multiple-axes.
I need two x axis for one line series. 
* simple example for understanding - what i need:
* example: line is a duration, axis x1 is days, axis x2 is weeks, f.e. 

I draw line-graphic, xAxes show same values in another metric system. How can i realize that?

My situation:
x1 - is barrel per day.
x2 - litres per day.
x1 and x2 show same info, but in different metric system.

thats what i'm done
[JSFiddle](http://jsfiddle.net/y1Lnqa0p/)

 I add data according only to barrel. And upper x axis not related and show empty, without nothing.

How can a drow upper axis's labels(ticks) proportionally related to bottom xAxis?

**Comment by martynasma** [comment]
Since there are no series attached to your secondary X axis, it does not have a scale, hence not axis at all.

I suppose you can set your scale manually:

```
xAxisUpper.min = 0;
xAxisUpper.max = 5000;
```
