### ISSUE TITLE
showTooltipOn how change this property?

### ISSUE THREAD

**Issue by fisherspoons** [amcharts/amcharts4#2393]
Hi, please help how to access a property showTooltipOn for line graph.

series.columns.template.showTooltipOn = "hit";

[Codepen](https://codepen.io/fisherspoons/pen/MWaygyY?editors=1010)

**Comment by fisherspoons** [comment]
I use
seriesSale.dataItems.template.showTooltipOn = "hit";
seriesBuy.dataItems.template.showTooltipOn = "hit";

How it work? 
[showTooltipOn definition](https://www.amcharts.com/docs/v4/reference/lineseries/#showTooltipOn_property)


No one came across when you need to make the mobile so that the tooltip is shown by clicking and not by hover? Or maybe someone knows another option, so that the tooltip doesn’t get cleaned, do you start scrolling the page on the phone?

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
