### ISSUE TITLE
Legend for Maps

### ISSUE THREAD

**Issue by phane24** [amcharts/amcharts4#2394]
Is there any way to place a legend just beside to a country(UK)?? 

Thanks in advance .

**Comment by martynasma** [comment]
Yes:
https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items

**Comment by phane24** [comment]
I already seen this link and it is possible to place the legend in maps just precise to COUNTRY (UK)??

**Comment by martynasma** [comment]
Do you mean so that it would move together with the map?

**Comment by phane24** [comment]
No. The legend position should be FIXED .It  just below/above  the country(UK)

**Comment by martynasma** [comment]
In that case you should refer to the example above and position your custom legend with `x` and `y` properties.

**Comment by phane24** [comment]
is there any way to place our custom html tags beside/ just below to the particular country? please see the above  attachement for reference . If possible please suggest a way to do it. Thanks In Advance
