### ISSUE TITLE
XYCursor places tooltipText incorrectly

### ISSUE THREAD

**Issue by MGMehdi** [amcharts/amcharts4#2397]
When I use XYCursor, amCharts display only the first column tooltip if I move in another column

![image](https://user-images.githubusercontent.com/48625769/79984458-8097e880-84a9-11ea-98b1-420508cd4841.png)

If I zoom or if I remove XYCursor, tooltip work correctly
If I zoom with the first column the same bug occur

**Comment by martynasma** [comment]
We can't seem to be able to replicate the issue you have described.

Please provide a demo, code, or description of the steps needed to reproduce it.

**Comment by MGMehdi** [comment]
Thanks for your response

Here a demo

https://codepen.io/MGMehdi/pen/qBORYZx?editors=0010

**Comment by MGMehdi** [comment]
It's not working 

I find this [code](https://codepen.io/anon/pen/vvOPgO?editors=0010) but I don't know what's different from mine

**Comment by MGMehdi** [comment]
Thanks it work !
Can you tell me what is this line ?

**Comment by martynasma** [comment]
It instructs cursor not to try to show a tooltip for particular series. Once cursor is not interfering the regular hovers set up directly on columns work as expected.

**Comment by MGMehdi** [comment]
Thanks again for your help
