### ISSUE TITLE
Auto handle radius labels in piechart

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2398]
How handle radius labels in pieChart for labels not show outside chart.
https://codepen.io/hassandl/pen/Yzypodv
![image](https://user-images.githubusercontent.com/22093903/79990751-ab446a00-84c6-11ea-9d13-7a5c22a18915.png)

**Comment by martynasma** [comment]
I suggest you take a look at this tutorial:
https://www.amcharts.com/docs/v4/tutorials/dealing-with-piechart-labels-that-dont-fit/

**Comment by HASSANDL** [comment]
Very thanks.
