### ISSUE TITLE
How to make a XYChart size dynamic in width and height based on the parent Element/Div

### ISSUE THREAD

**Issue by djpirra** [amcharts/amcharts4#2399]
Hi,

I am trying to create a XYChart that will adjust to the resizing of a parent element in width and height.
It seems to be working only on the width and not the height even though I am setting both as percent 100.

How can this be achieved?

Example Pen [Here](https://codepen.io/djpirra/pen/MWajvdP)

Thank you

**Comment by martynasma** [comment]
The chart will watch for size of its parent container and will resize itself if it changes. It works both for width and height.

In CodePen you provided, the "chartdiv" element, which is the container for chart, does not have any height set to it. You should probably size your chart container using CSS, which is tricky with relative heights, but doable.

**Comment by djpirra** [comment]
My goal is the chartdiv to also be set to occupy the remaining vertical area... this is what seems not to be working.
Tried couple of things but nothing worked so far.

**Comment by martynasma** [comment]
The chart does not modify the size of its container in any way. So sizing chart container is up to you using whatever means you have at your disposal: CSS, JavaScript, in-line styles, etc.

**Comment by djpirra** [comment]
My container is resizing correctly, but the chart seems to only adjust up to a certain minimum height.

On the start of the chart I am using:

this.xYChart.width = am4core.percent(100);
this.xYChart.height = am4core.percent(100);

**Comment by cwooldridge1** [comment]
I have the same issue I cannot position chart to occupy the remaining vertical space.
