### ISSUE TITLE
ES2015 import without .js is broken.

### ISSUE THREAD

**Issue by SowingSadness** [amcharts/amcharts4#24]
Vanila es2015 require a location of url with extension (.js) in a path.
Today dist/es2015 implementation of amcharts4 doesn't work.

![image](https://user-images.githubusercontent.com/576443/40014353-0e371bea-57b9-11e8-89d7-c49795a6165c.png)

**Comment by Pauan** [comment]
@SowingSadness We do not support native ES6 modules at this time, you will need to use a bundler like Webpack or Rollup.

There are two reasons for this:

1. TypeScript does not support outputting the `.js` extension:

   https://github.com/Microsoft/TypeScript/issues/16577
   https://github.com/Microsoft/TypeScript/issues/13422

2. We use npm modules, such as `pdfmake` and `xlsx`, and npm modules do not work in the browser.

   [There is a proposal to make npm modules work in the browser, but it has not been standardized or implemented yet.](https://github.com/domenic/package-name-maps)
