### ISSUE TITLE
Safari/IE Edge not update chart by buttons

### ISSUE THREAD

**Issue by fisherspoons** [amcharts/amcharts4#2400]
Ok, I have a graph redone from an example in which it changes depending on the selected period by buttons. Everything works fine in all browsers except IE edge and Safari.
I think this is connected if the property is turned off **dateAxis.groupData = true;**
But I need to display all dates, without groupings.

[Example Codepen](https://codepen.io/fisherspoons/pen/BaopyoX?editors=1010)

By default should be seven days and switch the schedule by buttons

**Comment by fisherspoons** [comment]
Sorry, I just did not pass the date object, although it is strange that for half of the browsers this works)

**Comment by xorspark** [comment]
`'2020, 12, 24'` isn't a valid date format for `Date` constructors; the fact that it works in other browsers at all shows that they're being way too lenient. [The standard dictates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#Timestamp_string) that you need to use ISO8601 (with _dashes_, not commas) or RFC 2822 formats if you're using a string in the `Date` constructor if you want consistent results. Anything else is simply leaving it up the browser vendor's discretion.
