### ISSUE TITLE
Showing only one country maps in amcharts?

### ISSUE THREAD

**Issue by phane24** [amcharts/amcharts4#2401]
is there anyway to show only one country in maps of amcharts???

**Comment by martynasma** [comment]
Yes, please refer to the `MapChart` docs on using different country specific maps:
https://www.amcharts.com/docs/v4/chart-types/map/#Using_map_definition

Or if you need to show just a single country using World map, use `include`:
https://www.amcharts.com/docs/v4/chart-types/map/#Including_and_excluding_objects

**Comment by phane24** [comment]
Thanks
