### ISSUE TITLE
Series.dataItems.last is undefined

### ISSUE THREAD

**Issue by woodly0** [amcharts/amcharts4#2402]
Hey,
this has been asked already: #355 However, I cannot find an answer so I ask again:
I have a XYchart with two line series. One of these is shorter then the other one and I would like to access the last entry via: `series.dataItems.last.point` which throws an error 
_Cannot read property 'point' of undefined_  - in the browser. Am I missing something?
I have to mention that I'm loading the data from an external CSV file which works perfectly.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).

**Comment by woodly0** [comment]
Alright, thanks.

**Comment by DJ2022** [comment]
Great help.. thanks
