### ISSUE TITLE
Initial animation works only for the last added chart

### ISSUE THREAD

**Issue by woodly0** [amcharts/amcharts4#2403]
Hi again,
I like v4 so much that I've created a page with two chart instances on it. The data is loaded through a CSV file for both of them. Everything works fine except that the inital animation where the series go from zero to their absolute value works only for the second chart. I cannot find much documentation on what to consider when using multiple charts per page but I guess it should be straight forward.
I have tried to force the animation with `series1.showOnInit = true; `  but no success. 
Don't know if this is a bug or I am missing something.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).

**Comment by woodly0** [comment]
Got it. If you added a documentation for multiple charts on the same page, that would probably help some of your users.
Cheers!
