### ISSUE TITLE
Show labels over columns

### ISSUE THREAD

**Issue by juanramonmartinez** [amcharts/amcharts4#2405]
Hi.

First of all, Sorry for my English.

amCharts version: 4.9.16

I created a chart based on: https://www.amcharts.com/demos/grouped-and-sorted-columns/

The chart shows information between dates and, in this example, if you look the two images:

1) Dates: 23/04/2019 to 23/04/2020. The graph does not show some labels

![1](https://user-images.githubusercontent.com/37975911/80153307-8b43a200-85bd-11ea-9bec-938b9b3f2860.png)

2) Dates: 01/04/2019 to 23/04/2020. The graph shows the labels

![2](https://user-images.githubusercontent.com/37975911/80153482-e70e2b00-85bd-11ea-8582-7b55d9c49ae2.png)

Depending on the date range, the labels are visible or not. What can I do?

Thanks

**Comment by martynasma** [comment]
You might need to extend the scale of the axis:
https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Relatively_expanding_the_scale

**Comment by juanramonmartinez** [comment]
Perfect... Solved :)

Thanks !!
