### ISSUE TITLE
XYChart valueAxis labels cached when values change to similar scale

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#2406]
This seems to be a bug as I've been able to recreate this with two different approaches.

Issue:
When changing data in the chart that causes the valueAxis to update, it seems to cache labels when the scale is similar.

Steps to reproduce:
https://codepen.io/sassomedia/pen/eYpvByj?editors=0010
1. Example starts out with "Data 1" selected. Labels display numbers in the millions. ✅ 
1. Select "Data 2": display in the thousands. ✅ 
1. Select "Data 3": display in the thousands _without_ the currency. ❌ 
1. Select "Data 4": display in single digits with percentage. ✅ 
1. Select "Data 3": display in the thousands with the currency. ✅ 
1. Select "Data 2": display in the thousands _with_ the currency. ❌
1. Select "Data 1": display in the millions. ✅ 

If the change in scale is large enough, there is no issue:
1. Example starts out with "Data 1" selected. Labels display numbers in the millions. ✅ 
1. Select "Data 3": display in the thousands with the currency. ✅ 
1. Select "Data 4": display in single digits with percentage. ✅ 
1. Select "Data 2": display in the thousands. ✅ 

While the example uses the `numberFormatter`, the issue is not related to it. The same behavior can be seen when instead using an adapter to format the labels `valueAxis.renderer.labels.template.adapter.add('text', formatValueFn);`. The returned strings of the `formatValueFn` are all correct but the valueAxis still reuses values from a previous display if the scale was similar enough. - In my actual project, I would sometimes see only partial reuse of labels. So I would have currency values and non-currency values on the same valueAxis. Really strange.

Note: the valueAxis tooltip however does display the correct values

**Comment by martynasma** [comment]
You're right about labels being cached for the same value. It's a performance-oriented feature, put there on purpose. It means that labels are reused as much as possible.

Setting different format to a chart-wide NumebrFormatter does not invalidate those labels. And frankly, it shouldn't because invalidating and redrawing stuff is a costly operation.

So, in your case you just need to invalidate those labels on axis manually after changing the data:

```
valueAxis.invalidateLabels();
```

That should fix the issue.

**Comment by sassomedia** [comment]
Ah I see, I must have overlooked that method. That works now as intended. Thanks! 🎉
