### ISSUE TITLE
Can I create an amchart Map with gradient ?

### ISSUE THREAD

**Issue by kisscodes1909** [amcharts/amcharts4#2408]
Hello everyone, I have a problem with amchart Map. Can I create an amchart Map with the gradient color?  

This is map image https://prnt.sc/s5rcn8

I tried to fill colors to polygon but It's don't like the mockup
https://codepen.io/dac-huu-nguyen/pen/QWjdOwZ

I think we need group the polygon and fill gradients on them

**Comment by martynasma** [comment]
I don't think it's possible to make fill gradient go across multiple elements.

Maybe a workaround would be this:
1) Create a custom GeoJSON map that contains all of the world in a single polygon.
2) Create series for it and apply gradient to it.
3) Create normal MapPolygonSeries for normal map.
4) Make polygons for that series fully transparent.

I don't have a ready-made example for that.

I'll see if we can create a GeoJSON like that easily.

**Comment by kisscodes1909** [comment]
For #1 Create a custom GeoJSON map that contains all of the world in a single polygon.

Can you give example about create a single polygon ?

**Comment by martynasma** [comment]
OK, found a much easier way:

```
var gradient = new am4core.LinearGradient();
gradient.addColor(am4core.color("#d9217a"));
gradient.addColor(am4core.color("#858cac"));
gradient.gradientUnits = "userSpaceOnUse";

polygonTemplate.fill = gradient;
```

Example:
https://codepen.io/team/amcharts/pen/gOaWQOM

**Comment by kisscodes1909** [comment]
That is awesome! Thanks to marty

**Comment by Sundus05** [comment]
Is this still possible with amcharts5?
