### ISSUE TITLE
Enhancement: Add reserved state "non-active" and "non-hovered"

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#241]
One of our use cases looks as follows: Each slice of a pie chart (or series in a line chart, etc.) should have a different look when no element is selected ("default" state for all elements) than when any element is active. 

You can see the visualization in the following image. The slices have a different color when any other slice is active or hovered in contrast to the "default" state where no interaction is happening.

![image](https://user-images.githubusercontent.com/247564/44206478-34d06000-a15a-11e8-97cc-bbec93de4645.png)

Is it possible to add these states (names could be different, wasn't too sure what to call them), or is it better to create custom states and manually toggle the respective "non-active" or "non-hover" states on all the other slices?

**Comment by martynasma** [comment]
I believe it would be too "niche" to introduce the "non-active" state that is applied to all elements that are not active when one element becomes active. There probably are a lot of other credible usage scenarios that could use their own hardcoded states. But if we go down that road, there's no telling where it would end. We might wake up one day with a complex tangle of a lot of states noone can make sense of :)

I'd say it's better to implement an event on slices to watch when it becomes active (probably ["toggled"](https://www.amcharts.com/docs/v4/reference/slice/#toggled_event) event is perfect for it). Then just apply your own customly-created state to the rest of the slices in the series.

Does that make sense?

**Comment by Chnoch** [comment]
I can see the point that there would probably a lot of use cases to add hardcoded states. 
In that case I'll see what I can do with implementing custom states to the slices and legends. Thanks for pointing me to the `toggled` event, seems to be what I'll need.

**Comment by martynasma** [comment]
@sassomedia How about using "over" and "out" events on legend items then re-apply appropriate custom states on related slices?

**Comment by sassomedia** [comment]
@martynasma Ok, yes that seemed to work. However, the "hit" event seems a bit more tricky, I'll give it a try. Thanks!

**Comment by sassomedia** [comment]
Alright, got it to work! In case someone needs something similar, updated example [here](https://jsfiddle.net/sassomedia/fdkuqexa/181/).
