### ISSUE TITLE
Treemap after zoom show label previous level

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2410]
After zoom in treeMap, show label previous level.
https://codepen.io/hassandl/pen/dyYWppZ
![image](https://user-images.githubusercontent.com/22093903/80299869-15059200-87ad-11ea-8f13-3828bb0f105f.png)
![image](https://user-images.githubusercontent.com/22093903/80299877-264e9e80-87ad-11ea-9c79-63d1215d3d8d.png)

**Comment by zeroin** [comment]
This is by design. To hide, them, simply set the opacity of your 1st level columns to 1. This way they will overlay the bullets:

`level1SeriesTemplate.columns.template.fillOpacity = 1;`

**Comment by HASSANDL** [comment]
Very thanks.
