### ISSUE TITLE
Support for Vue Component is missing

### ISSUE THREAD

**Issue by bluemonk3y** [amcharts/amcharts4#2412]
The Vue integration guide is not a proper Vue component example. ApexCharts have a decent model that I tried to follow, however, when actually using it as a component to get the data bindings working I ran into the dreaded error; `Chart was not disposed id=22` error. The chart was not actually created, however, something to do with Vue DOM template integration confuses amcharts. I just spent 2 days trying to build a component model but have now given up.

Links:
- Commit log:  https://github.com/liquidlabsio/fluidity/tree/amcharts-trial
- Vue component:  https://github.com/liquidlabsio/fluidity/blob/amcharts-trial/web/src/main/webapp/js/amcharts-vue.js
- ApexCharts links are referenced at the top of the vue amcharts-vue.js

To test:
- check out the branch
- navigate to the web module
https://github.com/liquidlabsio/fluidity/tree/amcharts-trial/web/src/main/webapp
- open the index.html file in chrome and check the console log

**Comment by martynasma** [comment]
Sorry you are having issues with amCharts and Vue.js.

The steps in our Vue.js guide were verified to work.

Unfortunately, we do not plan on any deeper integration, like building dedicated Vue.js component, or documenting niche/complex setups, at this moment. We're a small team, and simply can't do it all.

It pains me to say this, but if this seems like a deal-breaker, and you have a better alternative, you might just as well take it.

**Comment by simvol** [comment]
@martynasma Just a headsup, I believe assigning chart to vue component leads to potential performance issues. Vue wraps the object in setters/getters to analyze if something was changed and that process is a giant recursive method. If there is no need for vue know what happens to "chart" object I guess there is no need for "this.chart = chart;".

https://www.amcharts.com/docs/v4/getting-started/integrations/using-vue-js/

**Comment by martynasma** [comment]
@simvol Makes sense. However, if we don't store the chart reference, how do we know how to dispose it?

**Comment by simvol** [comment]
@martynasma everything stays the same, I just use normal variable.
`
<template> <div ref="chartdiv" /> </template
<script>
  let chart = null;
  export default {
    ...
    mounted() {
      chart = am4core.create(this.$refs.chartdiv, am4charts.XYChart);
    }
    beforeDestroy() {
      if (chart) {
        chart.dispose();
      }
    }
</script>
`

**Comment by martynasma** [comment]
Global vars eh? I guess that could work.

In any case, could try 4.9.19 (just released) if it makes it any better?
