### ISSUE TITLE
Choropleth Map define ranges for specific colors

### ISSUE THREAD

**Issue by Lms24** [amcharts/amcharts4#2415]
**Question**

Hi there,
I am trying to create a choropleth heat map with amcharts4. I have values for almost each country of the earth that range in the area of 0.0 to 0.35. The problem is that there are three outliers with values in the range of (0.8; 1.2). As a consequence almost all countries have the same colour because of the outliers. What I would like to achieve is to assign specific colours to self defined (non-equi distant) ranges. Say e.g.

* white      [0; 0.05)
* light red  [0.05; 0.2)
* red         [0.2; 0.3)
* dark red [0.3; 2)

I cannot simply cap the outliers to a smaller value as this would compromise the data I need to display. I couldn't find any hints on how to achieve what I am looking for. Thus I'm writing this question here.

**Environment**

* Angular 9 / typescript
* ngx Admin Dashboard
* latest amcharts4 version
* all browsers

Thanks!

**Comment by martynasma** [comment]
We're not planning on introducing multi-range heat rules, I'm afraid.

That said, we're currently working on a logarithmic option for heat rules. That should solve your issue.

Please make sure you subscribe to issue #2388 for updates.

Alternative solution:
1) Set your heat rule's `min` and `max` manually.
2) Add a `fill` [adapter](https://www.amcharts.com/docs/v4/concepts/adapters/) on the polygon which would check if actual value is outside the range and use custom color for it.

Hope that makes sense.

**Comment by Lms24** [comment]
Hi, yes, a logarithmic scale would help but I think it's far from ideal. The multi-range heat rules would however make most sense and allow for the biggest possibility of customization. That being said, thank you for your support though and thanks for offering this library for free. 

I will try the alternative solution and report back.

**Comment by Lms24** [comment]
the alternative solution works out for the time being. thanks
