### ISSUE TITLE
Force Directed Tree edge value

### ISSUE THREAD

**Issue by amiraziz** [amcharts/amcharts4#2416]
i need a graph  like 'Force Directed Tree' that when i mouse over on links, tooltip preview weight of that.

is this possible in latest version?

thank you.

**Comment by martynasma** [comment]
Yes. Take a look here:
https://www.amcharts.com/docs/v4/chart-types/force-directed/#Tooltips_on_links

**Comment by amiraziz** [comment]
thanks for quick answer.

can you explain how can i set `{value}` on links, this value is for smaller node and in my requirement i need preview transaction amount between to cards? node value in my case is card number.

**Comment by martynasma** [comment]
You can add custom fields in data and just refer to your custom fields in `tooltipText`: `{myCustomValue}`.

**Comment by amiraziz** [comment]
@martynasma `myCustomValue` is ok but i can't define that in links!

assume this sample [https://codepen.io/amiraziz/pen/gOaRWOq?editors=0010](url):

i need `linkWith` with object values not string array of ids.

(1):   `"link":[{"id":"Second","value":10}],`
(2):   `series.links.template.tooltipText = "[bold]{link.value}[/]";`
 is this possible in amCahrts?

**Comment by martynasma** [comment]
OK, yeah `linkWidth` links do not have associated data item.

The only way to do that is via adapter:

```
series.links.template.adapter.add("tooltipText", function(text, target) {
  // determine text to be shown from `target`
  console.log(target);
  return tooltiptext;
});
```

Hope this makes sense.
