### ISSUE TITLE
Creating Multiple value axies using category Axis in X axis is not working

### ISSUE THREAD

**Issue by sunith-kumar** [amcharts/amcharts4#2417]
Steps to reproduce

1 edit the mutiple axis example from official cite. 
[click](https://codepen.io/pen/?&editable=true=https%3A%2F%2Fwww.amcharts.com%2Fdemos%2Fmultiple-value-axes%2F)
2. To change the Date axis to Category Axis
  a) change line 23 as below 
     var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
  b) line 41 to   
    series.dataFields.categoryX = "category";
  c) line 126 to 
       category: i.toString(),

Below is codepen link with above changes made
[bug link](https://codepen.io/Sunith_kumar/pen/GRpmzQR)

**Comment by martynasma** [comment]
You didn't set up your `CategoryAxis` properly. `dataFields.category` is not set.

https://www.amcharts.com/docs/v4/concepts/axes/category-axis/#Binding_categories_to_data

**Comment by sunith-kumar** [comment]
@martynasma That was very quick and great. Thanks a lot
