### ISSUE TITLE
AmCharts 4.9.17 with canvg 3.0.6 failing when exporting on IE11

### ISSUE THREAD

**Issue by c-goetz** [amcharts/amcharts4#2418]
**Question**
Hi,

we recently migrated our codebase from AmCharts 3 to 4. During QA it was noticed that the chart export does not work on IE11.
The error occurs when `Export.js/getCanvasAdvanced()` calls `canvg()`: `Cannot call a class as a function`.

Our current solution is to downgrade AmCharts from 4.9.17 to 4.8.9. The export works in IE11 for this version.

I can't deliver a minimum example for this behaviour. I tried to reproduce it using the files from https://www.amcharts.com/lib/4/ (seems to be 4.9.17). But with these files it also works in IE11.

Pinning the AmCharts version is not a viable long term solution for us. Therefore I'd like to fix this.

Do you have any pointers for me how to debug/fix this? We tried it for a whole day and the only solution we could find was the downgrade.

Any help would be much appreciated.

Thanks and have a nice day,
Carlo

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Can you prep a runnable example we can test? We can't seem to be able to reproduce this error.

**Comment by c-goetz** [comment]
Thanks for your fast response. My first attempt on a runnable example worked in IE. I suspect that our webpack setup plays a role here.
We currently do not have the time to investigate this further/extract an example from our application. We'll disable chart export for IE11 instead.

If this comes up again I'll create a new issue with an example.

Thanks for your help and have a nice day.
