### ISSUE TITLE
Slider on category axis creates extra vertical space

### ISSUE THREAD

**Issue by laurens-dg** [amcharts/amcharts4#2420]
**Bug description**

There is a blank space at the end of the chart, created by the slider when it's added, in our usecase this is a lot bigger than the one in the following example.

Easiest steps to reproduce is: 
Edit the example on: https://www.amcharts.com/docs/v4/tutorials/handling-axis-zoom-events-via-api/ => on line 82 switch the Scrollbar to a Slider.

**Environment (if applicable)**

 - amcharts 4.9.17
 - Chrome 81

**Comment by martynasma** [comment]
Sorry, `Slider` was never meant to be used as Chart's scrollbar and is not readily supported. 

Chart expects a range not a position from scrollbar.

**Comment by laurens-dg** [comment]
Ok, pity, the way I read the documentation this was exactly the control we needed.

Slider
Type class
Creates a slider – a version of scrollbar with just one grip.

What steps could I take to have the slider return a range instead of a position? We have a specific use-case (which isn't too weird I think, fixed number of bars in a category axis) so I get that it wouldn't be supported out of the box. I saw the example that used jquery uislider, but I'd prefer to have a 'amcharts native' solution.

PS: I believe our 12-month of legendary customer support has expired some time ago, so thanks for the quick response anyway.
So far our upgrade from 3 to 4 has been going great as this is the first real issue we encounter where we're adding new functionality so, so far so good :)
