### ISSUE TITLE
Using watermark for chorddiagram not works

### ISSUE THREAD

**Issue by sinramyeon** [amcharts/amcharts4#2421]
In amcharts4, when use watermark for chorddiagram like

```
const chart = am4core.create('chartdiv', am4charts.ChordDiagram);

// Add watermark
const watermark = new am4core.Label();
watermark.text = "Test Test";
chart.plotContainer.children.push(watermark);
````

causing trouble with `TypeError: Cannot read property 'children' of undefined`

**Comment by martynasma** [comment]
`ChordDiagram` does not have `plotContainer`. You can push watermark to `chartContainer`:

```
chart.chartContainer.children.push(watermark);
```

**Comment by sinramyeon** [comment]
@martynasma is there a way to put a colour or paint full in watermarks? i couldn't find docs related.

**Comment by martynasma** [comment]
You can set watermark's color using `fill` option:

```
watermark.fill = am4core.color("#f00");
```

Not sure if I understand what you mean by "paint full in watermarks". Like a pattern?
https://www.amcharts.com/docs/v4/tutorials/adding-watermarks-to-charts/#Setting_container_s_fill

**Comment by sinramyeon** [comment]
@martynasma can i fill full square div with watermark also? like background color

**Comment by martynasma** [comment]
CSS fills of `<div>` elements are possible but a bit out of scope of amCharts repository. I'm sure you'll find your answers.
