### ISSUE TITLE
Creating edges dynamically in Force Directed Tree (only update relevant nodes)

### ISSUE THREAD

**Issue by ShashankAnantharam** [amcharts/amcharts4#2422]
**Question**
When I create links between two nodes dynamically in a Force directed tree, then ALL the nodes are being rerendered in the chart. I ONLY want the two nodes between which the link has been created to be rerendered. How do I achieve this?

Code: 
https://codepen.io/sandwraith/pen/mdeExeQ

In this code, I am adding a link between Node 1 and Node 2 whenever any node is clicked but the entire chart is being rerendered just to add 1 extra link.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
