### ISSUE TITLE
Radar chart not show tooltip if cursor disabled

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2424]
Radar chart not show tooltip if cursor disabled.
https://codepen.io/hassandl/pen/yLYoZMY

**Comment by martynasma** [comment]
This is by design. If there's no cursor, you have to hover on an object directly to show the tooltip.

Since there's nothing to hover on (e.g. bullet) you don't have the tooltips anymore.

**Comment by HASSANDL** [comment]
I update example and add bullet but not show tooltip.
https://codepen.io/hassandl/pen/yLYoZMY

**Comment by martynasma** [comment]
You need to put tooltip information on a bullet itself then:

```
var bullet = series.bullets.push(new am4charts.CircleBullet());
bullet.tooltipHTML = "Series: {name}\nCategory: {categoryX}\nValue: {valueY}";
```

**Comment by HASSANDL** [comment]
Very thanks.
