### ISSUE TITLE
Map Lines Colour from JSON

### ISSUE THREAD

**Issue by jf19742016** [amcharts/amcharts4#2425]
Is it possible to have different colour lines using multiGeoLine.  So line 1 has one colour and line 2 is a different colour and populate this using JSON?

**Comment by martynasma** [comment]
No, I'm afraid. It's still a single line from SVG standpoint.

You would need to create separate lines for each colored segment.

**Comment by jf19742016** [comment]
Hi, sorry - what does that mean.  They are not lines as per the other chart types?

**Comment by martynasma** [comment]
What I meant to say is that there's no way to specify colored segments on a single MapLine.

If you meant to ask whether it's possible to apply different colors to **separate** lines within `MapLineSeris`, then yes, it is possible.

**Comment by jf19742016** [comment]
I've created separate line series for each one I need with a different color.  Just thought would be good for this to be set per line with JSON e.g. Lat, Lon, Color.....  thanks

**Comment by martynasma** [comment]
Can you post your map on CodePen? I'll take a look, maybe there's an easy way.

It's hard to give advice without seeing your actual setup.
