### ISSUE TITLE
Make the axis labels width a percentage of the charts container?

### ISSUE THREAD

**Issue by brecriffs** [amcharts/amcharts4#2427]
**Question**
In a chart like the population pyramid found here:
https://www.amcharts.com/demos/population-pyramid/

My category labels are long and I only want labels on one of the axes. However,
in this container, there are two charts. I have set each to width 50% (`am4core.percent(50)`).
Unfortunately, the width of the labels on the one chart's axis makes that chart smaller compared to the other one. 

Desired scenario: 

Both charts are the same width. Set by percent, not a hard-coded pixel value. Labels are on only one of the charts. 

I tried this:

`categoryAxis.renderer.labels.template.width = am4core.percent(10)`

But the labels were then very small, and it doesn't seem like any percentage works here. I tried using maxWidth, but that only accepts a number, and not a percent.

Using typescript/react.

**Comment by brecriffs** [comment]
Another solution would be to render the labels in a separate container. If they would follow the same grid rules as the chart they are connected to.

**Comment by brecriffs** [comment]
![Screenshot from 2020-05-02 13-26-37](https://user-images.githubusercontent.com/49916905/80871073-94490900-8c78-11ea-8346-2ce974a4495c.png)

This is what is rendering when I try to set a percentage width for the labels. The docs says that the label extends container, and that ```Relative width will be calculated using closest measured ancestor Container.``` Maybe I need to set the relative width it's parent? 

I am trying to have the container of everything as 100% width. The left and right chart's to be the same width, as a percentage of the parent container, and the labels just on one of the sides.

**Comment by martynasma** [comment]
Depending on how you are creating those labels (as bullets or as Label elements as column children) they may already be in a separate container (`chart.bulletsContainer`).

I could take a look if you could post your whole chart on CodePen.
