### ISSUE TITLE
How to have animation when data changes on column series

### ISSUE THREAD

**Issue by simvol** [amcharts/amcharts4#2428]
**Question**
How to make chart animate when data changed? I would like to achieve something like this.

I tried to use this [example](https://www.amcharts.com/demos/dynamic-data-updates-on-treemap/), but I almost crashed my laptop trying to access series.dataItem - everything started lagging and my cooller went like crazy..

My attempt to change data doesn't have any animation:
https://codepen.io/simvol/pen/GRpMBxg

Is there something to get this result, but without this "hacky" get by id stuff?
https://codepen.io/team/amcharts/pen/e5b7e755ec85b282612c7d60d25b97fa?editors=0010

**Comment by martynasma** [comment]
If you want to transition from one value to another, you need to modify existing dataset, then call `invalidateRawData()` method.

More details here:
https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points

**Comment by simvol** [comment]
Thank you!
