### ISSUE TITLE
chart.dispose() is causing major rendering delays in chrome

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#2429]
**Bug description**

This is a major blocker for our devs right now. I haven't been able to replicate this in a fiddle/pen, but I can show recordings of exactly what is happening. This is happening for all chart types that we have configured, regardless of how many data points or chart configurations.

We have tiles that load dynamically. When a tile mounts, it renders the chart. When it unmounts, it disposes the chart with:
```
componentWillUnmount() {
    if (this.chart) {
      if (this.chart.dispose) {
        console.log('chart dispose. Tile id: ', this.metric.title);
        this.chart.dispose();
      }
    }
  }
```

With this setup, you can see in the following recording how long it takes to switch between tiles. Note the log appearing nearly immediately after a click, but then the actual rendering takes seconds until switching.

https://recordit.co/XG3NX4Uf6U

Now, let me comment out the chart.dispose() line. You'll notice I get the log warnings, but things go _significantly_ faster.

https://recordit.co/h0k2XEMHdF

Now, here's a weird twist. If I put the chart.dispose() back in, but turn on the chrome profiler, it also goes super quick.

https://recordit.co/RWGotvTEJB

I'm not sure what could be causing such strange behavior, but there is definitely something in the dispose method that is causing our pages to halt. We've already ruled out every other factor that could be causing this and the recording above show this is definitely something in the dispose that is having issues.

Here's the environment info we're using:

React 16.9
mobx 4.2.1
mobx-state-tree 2.0.5
amcharts (happens on all versions from 4.8.3 to 4.9.19)

Now, upon further testing and writing up this bug, it appears to be chrome specific:

started happening around chrome version 79 and persists on 81
does not happen in firefox 75
does not appear to be happening in safari 13.1

So, it looks like this is tied to something chrome updated, which is bad news being the most used browser.

**Comment by martynasma** [comment]
That's weird. There's a bug in Chrome 81 that makes dispose of amCharts very slow when DevTools are open.

That said, we've introduced a workaround for it in 4.9.19 so it must be fast.

Can you double check if you still get slow dispose on 4.9.19, and whether it is affected by DevTools being open?

**Comment by runfaj** [comment]
@martynasma yes, this is happening on the latest version as well unfortunately.

**Comment by zeroin** [comment]
Is there a way for us to see the chart?
Could you add `console.log(am4core.System.VERSION)` to be sure it's 4.9.19 and not cached older version?

**Comment by runfaj** [comment]
@zeroin Yup! Here you go:
![image](https://user-images.githubusercontent.com/3292053/80922655-ce2f1380-8d3b-11ea-93d3-de762d2329a1.png)

**Comment by zeroin** [comment]
Is there a chance you are using ResizeSensor: https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.d.ts

Which we used before 4.9.19 for your own purposes? Or maybe some other lib which does this:

```
var observer = new MutationObserver(function (mutations) {});
document.addEventListener("DOMContentLoaded", function (event) {
    observer.observe(document.body, {
        childList: true,
        subtree: true,
    });
});
```

We found out that this was what caused the disposing delays (probably because of some Chrome bug).

If it's not the case, I am afraid we will need some isolated case from you so we could reproduce the issue and try to find what causes the problem.

And we will try to report this problem to Chrome.

**Comment by zeroin** [comment]
We reported the issue, you are welcome to star it:
https://bugs.chromium.org/p/chromium/issues/detail?id=1077657

**Comment by runfaj** [comment]
@zeroin We do use a mutation observer, but only on the root html element. However, I disabled to test this case anyway and it didn't seem to have any affect. I'll work on attempting to reproduce this outside our private environment so I can get you more information. In the meantime, thanks for reporting that bug.
