### ISSUE TITLE
Accessing variables in tooltipText - percent calculation from another series?

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts4#2431]
Chart with three series.  I am showing tooltip text on only one of those and including values from all three in a single tooltip.  The raw values work by referencing them by their name, but does not work for percent calculations.  I have `calculatePercent` set to true for all three series.

`series3.tooltipText = "[bold]Active : [/]{Active.formatDuration()} ({Active.percent.formatNumber('#.0')}%)\n[bold]Idle : [/]{Idle.formatDuration()} ({Idle.percent.formatNumber('#.0')}%)\n[bold]Total : [/]{Total.formatDuration()} ({Total.percent.formatNumber('#.0')}%)";`

The `???.formatDuration()` entries show fine, but the `???.percent.formatNumber('#.0')}` entries do not.  I realize I can use `valueY` as the name, which works, but only for the series it is called in (series 3).  I would like to show the percent values from the other series (1 and 2) as well IN the series 3 tooltipText.  Is there any way to get around this?

Link to fiddle : [https://jsfiddle.net/5v3L2nho/](https://jsfiddle.net/5v3L2nho/)

**Comment by martynasma** [comment]
The chart calculates derivative values for series' dataFields only. Referring to raw data will not work for calculated values, I'm afraid.

The only workaround would be to use an adapter for `tooltipText`, which would access `target.dataItem.dataContext` (which is raw data), then calculate those values and format tooltip contents.

Another option is to cycle through series in `tooltipText` adapter, find their data item for specific date, then get pre-calculated percent value.

I wish I had an example, but I don't.

Hope this makes sense.

**Comment by morrow95** [comment]
Thanks, but that doesn't really help me.  I've always had trouble with amcharts because I never know where to start, look, etc when I want to accomplish something - there is just sooo much and without examples it makes it pretty tough to see how everything comes together, what it does, etc - for me at least.

series3.adapter.add("tooltipText", function (text, target, key) {
        console.log(text);
	console.log(target);
        console.log(key);
	console.log(target.dataItem.dataContext);
	return "test";
 });

You mentioned `target.dataItem.dataContext` but that is undefined as far as the usage above goes.  `target` has contents, but as far as me finding anywhere in it there shows the data set I sent to the chart... I can't find it.  `text` is also undefined and `key` just = 'tooltipText'.

**Comment by martynasma** [comment]
Sorry, you're right. Data item is underfined directly on series, and since your adapter is on series, `target` is series itself.

Try `target.tooltipDataItem.dataContext` instead.

**Comment by morrow95** [comment]
That gives me access to my data for the point I am hovered over.  I can make that work since I send the chart totals with every point.  Wouldn't have a need for `calculatePercent` since I would return the percent calculations on my own then.  This will do fine.  Thanks.
