### ISSUE TITLE
Show bullet on initial level on TreeMap

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [amcharts/amcharts4#2432]
**Question**

I want to use the TreeMap chart as you are doing in drill down example (https://codepen.io/team/amcharts/pen/paXGJj)

Problem is that i have no images for the initial level and i want to show bullets for it so I've tried to put the following:
````
var level0SeriesTemplate = chart.seriesTemplates.create("0");
var bullet0 = level0SeriesTemplate.bullets.push(
  new am4charts.LabelBullet()
);
bullet0.locationX = 0.5;
bullet0.locationY = 0.5;
bullet0.label.text = "AA : {name}";
bullet0.label.fill = am4core.color("#ffffff");
level0SeriesTemplate.columns.template.fillOpacity = 0;
````
but without success (https://codepen.io/RaulPampliegaMayoral/pen/mdeqGoW?editors=1010) so i supose it's not the way to go.

I've tried too adding custom label and setting the text with an adapter.
````
var containerLabel  = level0SeriesTemplate.columns.template.createChild(am4core.Label));
containerLabel.align    = "center";
containerLabel.valign   = "middle";
containerLabel.truncate = true;
containerLabel.fontSize = 12;
containerLabel.fillOpacity = 0.5;
containerLabel.adapter.add("text", (label, target) -> {
  var dataItem = target.parent.dataItem;
  if (dataItem) {
    return dataItem.treeMapDataItem.name;
  }

  return "":
});
````
This way i can see the label but dont like so much this solution.

Is possible make what i want via configuration or i need to put it manually via custom labels and adapters?

----
- AmChart 4.9.16
- Chrome

**Comment by martynasma** [comment]
You don't get bullets because you're making them invisible:

```
level0SeriesTemplate.columns.template.fillOpacity = 0;
```

**Comment by RaulPampliegaMayoral** [comment]
Oh my god! i dont realized about this property... Thanks @martynasma 

Is there anyway to hide this serie0 bullet when click over one serie?

**Comment by RaulPampliegaMayoral** [comment]
@martynasma forget about last question, it's hidding correctly when go to level 1.

Thanks for your time!
