### ISSUE TITLE
Cannot set the color of RadarColumnSeries

### ISSUE THREAD

**Issue by lesfrank** [amcharts/amcharts4#2433]
I tried to fill a RadarColumnSeries different for each X category. Setting the configField does not force to use the config elements of the data set. Is this a bug of the RadarColumnSeries of what do I wrong? Many thanks!

See: https://jsfiddle.net/lefrank/1kft0sd3/4/

Or:  

am4core.ready(function() {

elementChartData= [
{"element":"One", "value": 68, "config":{"fill": "red"}},
{"element":"Two", "value": 58, "config": {"fill": "#fff000" }},
{"element":"Three", "value": 88, "config": {"fill": "#fff000" }}
];

am4core.useTheme(am4themes_animated);

var radarChart = am4core.create("statusElements", am4charts.RadarChart);

radarChart.data = elementChartData;

var radarCategoryAxis = radarChart.xAxes.push(new am4charts.CategoryAxis());
radarCategoryAxis.dataFields.category = "element";

var radarValueAxis = radarChart.yAxes.push(new am4charts.ValueAxis());
radarValueAxis.min = 0;
radarValueAxis.max = 100;

var radarSeries1 = radarChart.series.push(new am4charts.RadarColumnSeries());
radarSeries1.columns.template.tooltipText = "{categoryX}: {valueY.value}";
radarSeries1.name = "Value";
radarSeries1.dataFields.categoryX = "element";
radarSeries1.dataFields.valueY = "value";
radarSeries1.configField = 'config';
});

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).

**Comment by lesfrank** [comment]
Hi there,
I tried everything and followed all documentation but the color of the items of the RadarColumnSeries doesn't change. It must be a bug. I cannot change the color with this simple code. This is my last issue before buying a license. I would be very, very happy if you could confirm a bug or tell me that my code is wrong. Thanks!

Frank

The code:

  thedata = [
    {"element":"One",  "value": 80,  "config": {"fill": "#F00"}}, 
    {"element":"Two",  "value": 60,  "config": {"fill": "#0F0"}} ];

  var radarChart = am4core.create("statusElements", am4charts.RadarChart);  
  radarChart.data = thedata;
  
  var radarCategoryAxis = radarChart.xAxes.push(new am4charts.CategoryAxis());
  radarCategoryAxis.dataFields.category = "element";
  
  var radarValueAxis = radarChart.yAxes.push(new am4charts.ValueAxis());

  var radarSeries1 = radarChart.series.push(new am4charts.RadarColumnSeries());
  radarSeries1.name = "Value";
  radarSeries1.dataFields.categoryX = "element";
  radarSeries1.dataFields.valueY = "value";

This
  radarSeries1.configField = 'config';
or this:
  radarSeries1.columns.template.configField = "config";

**Comment by zeroin** [comment]
Config field is not working with columns because series override the values.
However you could set this for the last element, radarColumn:

`radarSeries1.columns.template.radarColumn.configField = 'config';`

and it should work.

**Comment by lesfrank** [comment]
That works. I will also put this information on stackoverflow. Many, many thanks!
