### ISSUE TITLE
Build failing on all platforms

### ISSUE THREAD

**Issue by alexbdv** [amcharts/amcharts4#2434]
I'm trying to build amcharts4(v4.9.19) from source on Windows, Mac & Linux and getting the same errors on all 3 platforms

I've updated yarn & node and i'm running `yarn install && yarn run build`.
Install succeeds but build fails with several errors. If I try to bypass the errors, more errors are encountered, mainly around dependencies.
Since there are so many errors and since it's failing on all platforms I'm assuming that there would be some additional steps that are missing. Are there any detailed build instructions that I'm missing ? 

```
src/fonts/sarabun-thai.ts:1:23 - error TS2307: Cannot find module '@amcharts/amcharts4/core'.

1 import { IFont } from "@amcharts/amcharts4/core";
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/plugins/overlapBuster.ts:1:15 - error TS2307: Cannot find module '../.internal/plugins/overLapBuster/OverlapBuster'.

1 export * from "../.internal/plugins/overLapBuster/OverlapBuster";

src/plugins/overlapBuster.ts:1:15 - error TS2307: Cannot find module 
  '../.internal/plugins/overLapBuster/OverlapBuster'.
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/.internal/charts/map/projections.ts:7:27 - error TS2307: Cannot find module './projections/AlbersUsa'.
7 export { AlbersUsa } from "./projections/AlbersUsa";
                            ~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by Pauan** [comment]
@alexbdv Why are you building from source? It is far easier and faster to just install amCharts by using `yarn add --dev @amcharts/amcharts4`

**Comment by alexbdv** [comment]
@Pauan - I want to have the unminified source code for debugging my charts. It works better for me than the typescript + source map. Is that available anywhere ?

**Comment by Pauan** [comment]
@alexbdv The files in the `@amcharts/amcharts4` npm package are already unminified.

If your code is minified, that's because of your Webpack setup: you need to use `mode: "development"` in order to disable minification in Webpack.

**Comment by alexbdv** [comment]
@Pauan, Thanks!

**Comment by skratchdot** [comment]
@Pauan - can you offer a solution on how to build this project from source? we are looking into fixing some code and potentially submitting a pr.
