### ISSUE TITLE
Add html adapter to XYChart legend with StepLineSeries

### ISSUE THREAD

**Issue by Husein-Kasem** [amcharts/amcharts4#2435]
I'm searching the documentation on how to add an HTML adapter to the legend labels of XYChart with StepLineSeries.

I have tried adding the adapter via the following code:
```
chart.legend.labels.template.adapter.add('html', (label, target, key) => {
                const dataContext = target.dataItem.dataContext;
                if (dataContext) {
                   return '<div>custom label</div>'
                }
                return label;
            });
```
but this is adapting the legend only when I hover over the lines in the chart. if I don't hover it wont adapt the legend.

In summary:
I'm trying to render an HTML foreign object as a label for the series in XYChart with StepLineSeries.
I'm using: amcharts4 version 4.7.14, typescript, react, and chrome as the browser.
here is an example of the code on stackblitz: https://stackblitz.com/edit/react-ts-8wr5w7

**Comment by martynasma** [comment]
Well, your code which returns HTML in adapter relies on dataItem being there.

However, when you're not hovering on plot area, there's no single dataItem, hence the code not executing at all.

You will need to modify your adapter function to accommodate or dataItem-less situation.

**Comment by Husein-Kasem** [comment]
Thanks for the feedback!

I have adapted my code to not use the dataItem.
Now it uses the currentText of the label object which is the series name and made sure that the label is adapted only for one time when the currentText of the label is set.

I'll post my solution here for anyone who comes across such a problem.
full code: https://stackblitz.com/edit/react-ts-8wr5w7

Here is the new adapter code:
```
chartLegend.labels.template.adapter.add(
      "html",
      (label, target, key) => {
        const text = target.currentText;
        if(text && text.length === 17){
            return `<div class="grid-device-tile" id="bla">
                    <img src="bla" title="bla" alt="bla" class="tile-image unknown"/>
                    <div class="first-line">${text}</div>
                    <div class="second-line">unknown</div>
                    <div class="third-line">unknown</div>
                  </div>`;
        }
        return text;
      }
    );
```
