### ISSUE TITLE
Positioning and data placeholder issues with series' tooltips

### ISSUE THREAD

**Issue by alejandroiglesias** [amcharts/amcharts4#2436]
**Bug description**
I see a bunch of issues with the tooltips on a Gantt chart:

![image](https://user-images.githubusercontent.com/480640/80984489-4bbe5680-8e04-11ea-99b4-be4a9843c179.png)

1. Tooltip is always positioned at the center of the chart. (trying to mimic [this](https://www.amcharts.com/demos/gantt-chart/) and [this](https://www.amcharts.com/demos/gantt-chart-dates/) tutorials' tooltips)
2. Tooltip data placeholders don't work. (docs [1](https://www.amcharts.com/docs/v4/concepts/data/#Text_placeholders) and [2](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Data_placeholders))
3. Tooltip color is not picked from column color or data `color` property. ([docs](https://www.amcharts.com/docs/v4/concepts/series/#Tooltip_colors))

Reduced test case: https://codepen.io/alejandrogarciaiglesias/pen/jObagwa

Also, unrelated to the main issue topic, but I would like you to please see the misalignment of the column bullet labels pointed by the blue arrows as well.

Do you have any hints into what is happening to know if there's an issue on the settings I'm using or is it a bug in the library itself?
Thanks in advance.

**Comment by alejandroiglesias** [comment]
Regarding items 1 and 2, I figured out that the problem was that the `tooltipText` property had to go inside series' `columns.template` object path:
```js
series: [
    {
        type: "ColumnSeries",
        dataFields: {
            openDateX: "start",
            dateX: "end",
            categoryY: "category",
        },
        columns: {
            template: {
                tooltipText: "[bold]{name}:[/]\n{start} to {end}",
            },
        },
    },
],
```
Still, I'm not sure why this has to be different while in a LineSeries I can put it directly as a property of the series.

Finally, the third item still remains (bullet label misalignment).

**Comment by martynasma** [comment]
OK, so about bullets. Your columns start and end on milliseconds, however distances between data points are seconds apart. This makes `DateAxis` switc itself in `seconds` mode. So bullets are placed right on second, whereas column might end mid-second, hence different distance.

You can help `DateAxis` by putting it in millisecond mode:

```
    xAxes: [
      {
        title: { text: "Time Range" },
        type: "DateAxis",
        baseInterval: { timeUnit: "millisecond" }
      },
    ],
```

**Comment by alejandroiglesias** [comment]
@martynasma thank you very much, the label misalignment is fixed now. Regarding the tooltips, can you explain why in the `LineSeries` I can put the `tooltipText` property directly on it, and in the `ColumnSeries` I have to put it under `columns.template`?

**Comment by martynasma** [comment]
It's all about which axis is used as a base for the series. Basically you put tooltipText on column template if you want only that element to display tooltip on hover. Otherwise cursor tries to display tooltips for all data items for all series within same category/date in the same base axis. In a Gantt scenario it becomes quite complicated, with columns starting and ending wherever they can, even overlapping each other. There's quite a fuzzy logic in place.
