### ISSUE TITLE
Is it possible to remove fill when line series is disabled by legend?

### ISSUE THREAD

**Issue by NudeFox** [amcharts/amcharts4#2437]
Not sure if it could be a bug.
I'm trying to remove negative range fill color on interpolated line series chart by disabling line with legend.
Here is example from your demo with few changes: https://jsfiddle.net/qdwh3o8s/6/.
By so far positive range is easily removed with the help of events (line 94):
```
series2.events.on('hidden', event => {
    series.fillOpacity = 0;
});
```
This negative range is created on chart 'datavalidated' event and if i try to use the same code that generates these negativeRanges (line 117) just add more layers over existing fill. 
Is it possible to hide negative ranges also?

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
