### ISSUE TITLE
Is it possible to add custom bullets to scrollbar or chart for multiple line charts?

### ISSUE THREAD

**Issue by NudeFox** [amcharts/amcharts4#2438]
Is it possible with latest version to add custom bullets on scrollbar if for ex some value on line series is lower than some hardcoded count or we have the special property in chart data.
```
{
    date: 'Sat Jan 25 2020',
    hits: 2895,
    views: 8708,
    visits: 1599
    issue: true <--- like this
} 
```
What i want to achieve is something like this:
![image](https://user-images.githubusercontent.com/17131070/81007330-b352c100-8e59-11ea-8e9a-00a925fb1a5d.png)

The same would be on the line itself, only the bullet with issue should be visible.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
