### ISSUE TITLE
How can i put bullet on line series in any position on line?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#2440]
How can i put one or more bullet on line depending on X-coordinate? Y-coordinate automatically get from line. Is it possible?
i've just read at docs that bullets appear depending on line's data-points.
but i haven't found any examples how put bullet in any/random position.

**Comment by martynasma** [comment]
I'm, afraid there's no way to put bullets on a line between actual data points. Sorry.

**Comment by russeljo** [comment]
> I'm, afraid there's no way to put bullets on a line between actual data points. Sorry.

Maybe i can read position Y by X on my line? Can I?(how?)
And then a can add another one line serie with one coordinate in data = [X,Y] and put bullet on it ?

**Comment by martynasma** [comment]
Well, you can set bullet's `dx` and `dy` setting if you know how to calculate it.

Unfortunately, I don't have any docs or example to show :(
