### ISSUE TITLE
Label auto truncate not working properly

### ISSUE THREAD

**Issue by prk87** [amcharts/amcharts4#2442]
I observed that while using packed circle chart the labels are auto truncated nicely which use core library as prerequisite, then when i used wordcloud chart with same core library the word cloud chart not loading, then i specifically refereed the core library that is used in wrodcloud demo in amchart website then i can see wordcloud chart loading but the auto truncate feature for packed circle not working properly showing some special characters instead of dots.

please refer to the below screenshot.

![Label_AutoTruncate_Issue](https://user-images.githubusercontent.com/64831085/81045796-8e4f6400-8ed4-11ea-986d-a315e245992f.PNG)

**Comment by martynasma** [comment]
Can you post your chart on CodePen or jsFiddle?

**Comment by prk87** [comment]
if i refer the core library directly "https://www.amcharts.com/lib/4/core.js" it is working but when i try copy to my machine it is not working.

**Comment by martynasma** [comment]
I'm not entirely sure what you mean.

Can you post live chart online so that we can see what you're doing there?
