### ISSUE TITLE
updateRawData not updating DateAxis min and max

### ISSUE THREAD

**Issue by orosens** [amcharts/amcharts4#2443]
Hello, 

I have a XY chart (dates on X, values on Y) that I update using chart.invalidateRawData(). 
It contains 100 data points, in a rolling window (last 100 minutes) with 1 data point per minute. It is updated every 2 seconds.
I clearly see the updates on the last point every 2 seconds (the last data point value is correctly updated). However, when a new minute begins, I don't see the new point appear on the chart, I only see the first one disappearing from it. 
The DateAxis min and max values are not updated, and I see the whole chart "drifting" to the right as time passes.
It is exactly the same issue as the one in this post : https://github.com/amcharts/amcharts4/issues/622
But with DateAxis instead of ValueAxis.
Can you help me with this ? Thanks in advance !

**Comment by martynasma** [comment]
Please consider providing a working example.

**Comment by orosens** [comment]
It was an error on my side, found out while creating the codepen with an example... Really sorry for the disturbance, thank you for everything !
