### ISSUE TITLE
chart.dispose() is slow when multiple axis & series

### ISSUE THREAD

**Issue by markmonty** [amcharts/amcharts4#2445]
When using amcharts with multiple axis and series the chart dispose slows significantly.
Testing on our site for our stock chart shows that the chart without a volume series desposes in around 200-300 milliseconds, but when the volume series is added the time blows out to around 3000-5000 milliseconds to dispose.

An example 
https://codepen.io/mamontgo/pen/zYvpXQb

**Comment by martynasma** [comment]
Well, you have 10K data points, which means your ColumnSeries has at least 10K elements to dispose.

Taking into account that user can't possibly see all those thousands of columns crammed into ~1K pixels, I suggest considering two options:

1) Using filled `StepLineSeries` instead.
https://www.amcharts.com/docs/v4/concepts/performance/#Column_series

2) Using data point grouping:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping

Both will benefit you greatly not just in dispose but in overall chat performance and UX.

**Comment by markmonty** [comment]
Thanks martynasma I will play around with those suggestions.
I updated the code pen example with data point grouping and that fixed the slow dispose time as you suggested.
Strangely on our site we are already using date grouping settings the same as the updated codepen but still seem to have very slow dispose with less than the 10K points.

I'll play around some more it seems the slow dispose must be some other factor I need to find.

**Comment by martynasma** [comment]
We have introduced some dramatic improvements in dispose performance in 4.9.19. You might still be on some earlier version in your local setup.

Also, if you are using Chrome 81, it has a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1077657) that significantly slows down DOM element removal if DevTools are open. You might keep that in mind.

**Comment by markmonty** [comment]
Ohh thanks martynasma looks like it the chrome bug I am encountering.  It loads quickly in FF and worked fine when I restarted chrome.
I guess this is resolved thanks for your help!
