### ISSUE TITLE
get MapPolygon State Name when i am on MapImage

### ISSUE THREAD

**Issue by mjanbazi** [amcharts/amcharts4#2446]
hi
i have a map with all states in all of world, i have multi  point (mapimage) on it(My Location History)
i want to have a tooltip on each point that shows PointName with stateName
like "Location1-Paris"  that Paris comes from back Polygon and authomatically fill

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
