### ISSUE TITLE
switch tooltip from always to hover not work

### ISSUE THREAD

**Issue by mjanbazi** [amcharts/amcharts4#2447]
i have a map and a checkbox on top of it,when i checked the checkbox show tooltip on lineSeries always and when i unchecked show tooltip on hover
when i checked that work correctly show tooltip always and all thing is OK
but when i uncheck the tooltip is always yet and not hide
when i hide it with code : hideTooltip() after zoom in or out all tooltip appear(like always mode)

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
