### ISSUE TITLE
How decrease paddings in container and spacing between axis on small screens?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#2449]
On small window width graphic area become too much small, and other elements take too much space(axis, legend, padding between container)

on screenshot black border is container:
[Screenshot](https://monosnap.com/file/JnYmjBGqDwUH996tmGNtRzacrBnL9T)

Is there some solutions, recipes?

**Comment by martynasma** [comment]
Yes, you can use [`padding()`](https://www.amcharts.com/docs/v4/reference/sprite/#padding_method) and [`margin()`](https://www.amcharts.com/docs/v4/reference/sprite/#margin_method) methods on chart and other elements to control the spacing.

Some elements (including chart itself) have some default padding or margin set.

**Comment by russeljo** [comment]
this may help too
https://www.amcharts.com/docs/v4/concepts/responsive/
