### ISSUE TITLE
v4 documentation contribution

### ISSUE THREAD

**Issue by bcronje** [amcharts/amcharts4#245]
Is the v4 [documentation](https://www.amcharts.com/docs/v4/) available on github somewhere? Would like to make some pull requests on minor errors in the documentation I've picked up?

**Comment by bcronje** [comment]
E.g. https://www.amcharts.com/docs/v4/chart-types/map/#Setting_projection the documentation states the projection class definitions are accessible via `am4core.projections` but  should be `am4maps.projections`

**Comment by martynasma** [comment]
Good catch! Thanks @bcronje 

Unfortunately docs are not available as a GitHub repo you can easily make mods to.

You can email corrections to contact@amcharts.com or post them here.

Your help is very much appreciated!

**Comment by bcronje** [comment]
Some other minor suggested edits:

Under section [Creating image series](https://www.amcharts.com/docs/v4/chart-types/map/#Creating_image_series) section delete the following line as it seems to have been copied from a previous example:

> Say we want to enhance our previous demo to apply different fill colors to the U.S. and France.

Similarly under section [Creating line series](https://www.amcharts.com/docs/v4/chart-types/map/#Creating_line_series) delete the following line:

> Say we want to enhance our previous demo to apply different fill colors to the U.S. and France.

**Comment by martynasma** [comment]
Awesome. Fixed. Thanks!
