### ISSUE TITLE
Custom BigNumberFormat for Tooltips

### ISSUE THREAD

**Issue by DTwigs** [amcharts/amcharts4#2451]
I want to customize the bigNumberFormat on tooltips on my line chart.
`series.tooltipText = "{valueY.formatNumber('#,###.##a')}";`
Right now, values with billions are represented as "2.85G" for example, I want to change it to a "B".
I can do this with a numberFormatter on the axis, but not on the tooltips it seems.
  
How do i customize the bigNumberFormat for a tooltip?

Thanks

**Comment by martynasma** [comment]
Do you want to customize big number prefixes only for tooltips or for all numbers across the chart?

If it's for all the numbers, you can modify `chart.numberFormatter.bigNumberPrefixes`:

https://www.amcharts.com/docs/v4/tutorials/modifying-big-number-prefixes/

If it's only for the tooltip of the particular series, you might need to create a separate instance of number formatter for series, or even its tooltip, then modify its `bigNumberPrefixes`:

```
series.numberFormatter = new am4core.NumberFormatter();
series.numberFormatter.bigNumberPrefixes = .....;
```

**Comment by DTwigs** [comment]
@martynasma adding the numberFormatter to the chart level was the solution.  Thank you very much!
