### ISSUE TITLE
How to access vertical grid lines in scrollbarX?

### ISSUE THREAD

**Issue by NudeFox** [amcharts/amcharts4#2453]
Hi, i've added a scrollbar and going on by the guide to customize scrollbar appearance. The series line could be hidden via `.hide()` but the grid lines still there. Is there a way to remove them?
![image](https://user-images.githubusercontent.com/17131070/81343293-696a1500-90bd-11ea-9c49-d2132a960653.png)

**Comment by martynasma** [comment]
I suppose this will do:

```
chart.scrollbarX.scrollbarChart.xAxes.getIndex(0).renderer.grid.template.disabled = true;
```

**Comment by NudeFox** [comment]
I suppose this `chart.scrollbarX.scrollbarChart.xAxes.getIndex(0)` is the same object as dateAxis on XYChart. And we could have access to the same properties? Maybe add this as a note to scrollbar customize documentation?
