### ISSUE TITLE
Error in core.js: Cannot read property '1' of null

### ISSUE THREAD

**Issue by kostazol** [amcharts/amcharts4#2454]
Hello. I found issue https://github.com/amcharts/amcharts4/issues/1738 , but it doesn't help.

I don't understand why i have this error in 4.9.19 when i use
```
<script src="~/Scripts/chart/core.js"></script>
<script src="~/Scripts/chart/charts.js"></script>
<script src="~/Scripts/chart/animated.js"></script>
```
Can you help me? What i need to to? I tried pack 3 scripts at one and it doesn't help.

I also see this code
```
        window.am4core = r,
        i.p = function (t) {
            return /(.*\/)[^\/]*$/.exec(t)[1]
        }
        (function () {
            if (document.currentScript)
                return document.currentScript;
            var t = document.getElementsByTagName("script");
            return t[t.length - 1]
        }
            ().src)
```
if i add check it will work without errors:
```
        window.am4core = r,
        i.p = function (t) {
            var x = /(.*\/)[^\/]*$/.exec(t);
            return x == null ? x : x[1]
        }
        (function () {
            if (document.currentScript)
                return document.currentScript;
            var t = document.getElementsByTagName("script");
            return t[t.length - 1]
        }
            ().src)
```
But may be i don't understand something and it isn't correct checking.

**Comment by kostazol** [comment]
I also see this code
```
        window.am4core = r,
        i.p = function (t) {
            return /(.*\/)[^\/]*$/.exec(t)[1]
        }
        (function () {
            if (document.currentScript)
                return document.currentScript;
            var t = document.getElementsByTagName("script");
            return t[t.length - 1]
        }
            ().src)
```
if i add check it will work without errors:
```
        window.am4core = r,
        i.p = function (t) {
            var x = /(.*\/)[^\/]*$/.exec(t);
            return x == null ? x : x[1]
        }
        (function () {
            if (document.currentScript)
                return document.currentScript;
            var t = document.getElementsByTagName("script");
            return t[t.length - 1]
        }
            ().src)
```
But may be i don't understand something and it isn't correct checking.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).

**Comment by kostazol** [comment]
I check examples and understand that i don't have error in examples. And i understand thar i have error when i load library using ng-include to my Single Page App.
