### ISSUE TITLE
Create your own custom number format (e.g. '#####foo')

### ISSUE THREAD

**Issue by DTwigs** [amcharts/amcharts4#2457]
I want to create a custom number format like the ones found here:
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/

I want to multiply the value by 10000 and add a string at the end, so the number "4" would become "40000foo" and would perhaps be represented by something like "#####foo".  Is this possible with the number formatter?

**Comment by martynasma** [comment]
I suppose you can trick NmberFormatter to do that:

```
chart.numberFormatter.numberFormat = "#a";
chart.numberFormatter.smallNumberThreshold = 10;
chart.numberFormatter.smallNumberPrefixes = [
  { "number": 0.0001, "suffix": "foo" }
];
```

**Comment by DTwigs** [comment]
Thanks for the response @martynasma.  This solutions isn't working for me, but it also looks like its designed to work on numbers below 10?  I need this to work on all numbers.  Is it possible?

**Comment by DTwigs** [comment]
Ok solved, my solutions is using what @martynasma suggested, but instead of using the small number formatting I hijacked the byte formatting since I am not using it in my app.

numberFormatter.bytePrefixes = [{number: 0.0001, prefix: 'foo'}]

This works on all numbers when applying the format = "#,###.##b"

Thanks for your help Martynasma

**Comment by martynasma** [comment]
Cool, clever. I wish I'd thought of that :)
