### ISSUE TITLE
Ohio Congressional missing from regional US maps

### ISSUE THREAD

**Issue by SamsGitAccount** [amcharts/amcharts4#2458]
![image](https://user-images.githubusercontent.com/19219431/81463148-47d46080-9185-11ea-8568-b84472b6ebd0.png)

 - amCharts version 4.1.15

**Comment by martynasma** [comment]
Thank you for bringing this to our attention. Working on resolving it.

**Comment by martynasma** [comment]
Just released new geodata package. It should have those maps back.
