### ISSUE TITLE
amcharts cluster graph creating column series with white space column of missing key in json

### ISSUE THREAD

**Issue by satyaprakashmehta** [amcharts/amcharts4#2459]
[https://stackoverflow.com/questions/61691433/amcharts-cluster-graph-creating-column-series-with-white-space-column-of-missing](https://stackoverflow.com/questions/61691433/amcharts-cluster-graph-creating-column-series-with-white-space-column-of-missing)

    function init() {

                const data = [
                    {
                        'A': 138,
                        'B': 132,
                        'C': 104,
                        'date': 'APR 20'
                    },
                    {
                        'A': 47,
                        'B': 46,
                        'C': 42,
                        'date': 'MAR 20'
                    },
                    {
                        'D': 44,
                        'A': 37,
                        'B': 32,
                        'date': 'FEB 20'
                    }
                ];
                generateClusterColumnChart('chartdiv', data, 20);
                function generateClusterColumnChart(id, data, cw) {
                    am4core.useTheme(am4themes_animated);
                    am4core.options.commercialLicense = true; // hide amchart linkwire
                    const chart = am4core.create(id, am4charts.XYChart);
                    chart.colors.step = 2;

                    chart.legend = new am4charts.Legend();
                    // chart.legend.markers.template.disabled = true; // disabled legend
                    chart.legend.position = 'bottom';
                    chart.legend.paddingBottom = 0;
                    let markerTemplate = chart.legend.markers.template;
                    markerTemplate.width = 12;
                    markerTemplate.height = 12;

                    chart.legend.labels.template.fontSize = '11px';
                    chart.legend.maxHeight = 60;
                    chart.legend.scrollable = true;

                    const xAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                    xAxis.dataFields.category = 'date';
                    xAxis.renderer.cellStartLocation = 0.2;
                    xAxis.renderer.cellEndLocation = 0.8;
                    xAxis.renderer.grid.template.disabled = true; // remove axis grid lines
                    xAxis.renderer.grid.template.location = 100;
                    const label = xAxis.renderer.labels.template;
                    // label.wrap = true;
                    // label.truncate = true;
                    // label.maxWidth = 60;
                    label.fontSize = 14;

                    const yAxis = chart.yAxes.push(new am4charts.ValueAxis());
                    yAxis.renderer.grid.template.disabled = true;
                    yAxis.renderer.labels.template.disabled = true;
                    yAxis.min = 0;
                    yAxis.max = 300;
                    yAxis.strictMinMax = true;
                    function createSeries(value, name) {
                        const series = chart.series.push(new am4charts.ColumnSeries());
                        series.columns.template.width = cw;
                        series.dataFields.valueY = value;
                        series.dataFields.categoryX = 'date';
                        series.name = name;
                        series.columns.template.tooltipText = '{name}: [bold]{valueY}[/]';
                        series.tooltip.fontSize = '11px';
                        // series.clustered = false;

                        return series;
                    }
                    let clusterKeys1 = [];
                    if (data && data.length) {
                        chart.data = data;
                        clusterKeys1 = data.reduce((keys, obj) => keys.concat(Object.keys(obj).filter((key) => keys.indexOf(key) === -1)), []).filter((date) => date !== 'date');
                    } else {
                        chart.data = [];
                        clusterKeys1 = [];
                    }
                    for (let ck of clusterKeys1) {
                        const tf = ck.replace(ck.charAt(0), ck.charAt(0).toUpperCase());
                        // createSeries(ck, tf);
                        const cSeries = createSeries(ck, tf);
                    }
                }
            }
            init();

    #chartdiv{
      width: 500px;
      height: 200px;
    }

    <!DOCTYPE html>
    <html class="no-js" lang="en" dir="ltr">

    <head>
    <script src="https://www.amcharts.com/lib/4/core.js"></script>
    <script src="https://www.amcharts.com/lib/4/charts.js"></script>
    <script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
    </head>

    <body>
        <div id="chartdiv"></div>
    </body>

**Comment by satyaprakashmehta** [comment]
![PqpGB](https://user-images.githubusercontent.com/19344801/81467590-49d70780-91f7-11ea-913f-1549056d6b5a.png)

**Comment by mdtahsinasif** [comment]
please answer the above question. it is really big prob,em in amcharts.

**Comment by zeroin** [comment]
I am afraid this is not possible.

**Comment by satyaprakashmehta** [comment]
AmChart having similar graph for same purpose? To show group wise data with different set in each group?

**Comment by martynasma** [comment]
You an work around it by placing each individual column in a separate category.

The labels can be achieved using axis ranges.

Here's a similar example demonstrating the concept:
https://www.amcharts.com/docs/v4/tutorials/simulating-individual-order-of-columns-within-categories/

Hope it helps.

**Comment by omprakash-sit** [comment]
@martynasma it's look like it is stacked column series not cluster one. Since "series.clustered = false".

**Comment by martynasma** [comment]
`stacked = true` will achieve the same effect in your case.
