### ISSUE TITLE
Use a function as chart label formatter

### ISSUE THREAD

**Issue by RaedsLab** [amcharts/amcharts4#246]
I would like to have some custom formatting for my labels with a complex logic. 

Is there a way to have a function to act as a formatter ?

Something like this: https://stackblitz.com/edit/38680-codesandbox-error-umv4vr

**Comment by martynasma** [comment]
Yes:
https://www.amcharts.com/docs/v4/concepts/adapters/

**Comment by RaedsLab** [comment]
Thank you works perfectly!
