### ISSUE TITLE
TypeScript Error for missing valueY on event.target.dataItem.valueY;

### ISSUE THREAD

**Issue by abowen** [amcharts/amcharts4#2460]
**Bug description**

TypeScript warning due to missing `valueY`

**Reproduce**

Copied and pasted the reference TypeScript code from here into our app
https://www.amcharts.com/demos/variable-width-curved-column-chart/

However for the following code

```
event.target.zIndex = valueAxis.max - event.target.dataItem.valueY;
```

There is a warning

```
Property 'valueY' does not exist on type 'DataItem'. Did you mean 'values'?
```

Using the reference links from amCharts to CodePen and jsFiddle, the chart renders, so it seems to be just a missing TypeScript definition.

**Environment**

 - amCharts: 4.9.19
- TypeScript: 3.8.3

**Comment by martynasma** [comment]
You may need to typecast in order to avoid the warning:

```TypeScript
event.target.zIndex =  valueAxis.max - (<am4charts.CurvedColumnSeriesDataItem>(event.target.dataItem)).valueY;
```

**Comment by abowen** [comment]
Much appreciated. I'm new to library, so that makes sense

I went with a slight tweak

`event.target.zIndex = valueAxis.max - (event.target.dataItem as am4charts.CurvedColumnSeriesDataItem).valueY;`
