### ISSUE TITLE
Variable-width curved all columns disappear when using legend filtering

### ISSUE THREAD

**Issue by abowen** [amcharts/amcharts4#2461]
**Bug description**

Adding a legend to a variable-width curved column, and then filtering the columns makes all the columns disappear when one should remain.

Using reference code here:

https://www.amcharts.com/demos/variable-width-curved-column-chart/

Add 

```
chart.legend = new am4charts.Legend();
```

Once running, click on the legend colors:
- All three rows activated = works
- Disabling first legend item = everything disappears when I expect to see 2 data sets
- Disabling second legend item = works
- Disabling third legend item = works

https://codepen.io/ajbowen/pen/qBOYLQY

**Environment**

- amCharts: 4.9.19
- TypeScript: 3.8.3

**Comment by zeroin** [comment]
This happens because all the columns added to the first series container using adapter. So when it is hidden, all the columns are also hidden. To solve this, you should add:

`series.hiddenState.properties.visible = true;`

this way the series will remain visible even then hidden state is applied.
