### ISSUE TITLE
build issue after adding amcharts4 package.json

### ISSUE THREAD

**Issue by ajaykamal** [amcharts/amcharts4#2462]
**Question**

After adding amcharts4 in my package.json file and installing it. I tried compiling the application. but its giving below error due some dependent 'canvg' module

ERROR in node_modules/canvg/lib/BoundingBox.d.ts(7,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/BoundingBox.d.ts(8,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/BoundingBox.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/BoundingBox.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/Document/Document.d.ts(12,91): error TS2304: Cannot find name 'OffscreenCanvas'.
node_modules/canvg/lib/Document/Document.d.ts(16,92): error TS2304: Cannot find name 'CanvasImageSource'.
node_modules/canvg/lib/Document/Document.d.ts(39,38): error TS2304: Cannot find name 'Omit'.
node_modules/canvg/lib/Document/Document.d.ts(104,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/Document/Document.d.ts(105,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/Document/Document.d.ts(106,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/Document/Document.d.ts(107,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/Document/Document.d.ts(108,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/Document/ImageElement.d.ts(9,22): error TS2304: Cannot find name 'CanvasImageSource'.
node_modules/canvg/lib/Document/MissingGlyphElement.d.ts(4,26): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/canvg/lib/Document/UseElement.d.ts(13,19): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/Font.d.ts(2,30): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/canvg/lib/Font.d.ts(3,32): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/canvg/lib/Font.d.ts(4,31): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/canvg/lib/Screen.d.ts(76,52): error TS2304: Cannot find name 'globalThis'.
node_modules/canvg/lib/ViewPort.d.ts(12,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/ViewPort.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/canvg/lib/presets/offscreen.d.ts(18,50): error TS2304: Cannot find name 'OffscreenCanvas'.
node_modules/canvg/lib/types.d.ts(1,69): error TS2304: Cannot find name 'OffscreenCanvasRenderingContext2D'.

**I am using below vesions:**

Angular CLI: 6.2.9
Node: 10.15.3
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.10
@angular-devkit/build-angular     0.13.10
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/build-webpack     0.13.10
@angular-devkit/core              7.3.10
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  7.3.10
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.1
typescript                        2.9.2
webpack                           4.29.0

Any help with this is appreciated. Thanks in advance

**Comment by berbare** [comment]
I have the same issue with 4.9.20
Will temporarily downgrade to a version my colleague has working fine on his machine.

**Comment by ajaykamal** [comment]
Yeah @berbare ...version downgrade worked for me. Thanks

**Comment by vitorquezada** [comment]
I have the same problem with version 4.9.20. Waiting a solution. Thanks

**Comment by martynasma** [comment]
Fixed in [4.9.21](https://github.com/amcharts/amcharts4/releases/tag/4.9.21).

## [4.9.21] - 2020-05-13

### Fixed
- Latest version of `canvg` was causing issues in some Angular setups. Downgraded to `3.0.0`.
- The legend marker for `LineSeries` with circle bullet was not properly centered.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
