### ISSUE TITLE
amcharts4/Demos functionality query

### ISSUE THREAD

**Issue by rajasekharponakala** [amcharts/amcharts4#2463]
**Question**
Is there any demo available for scenario like below:
Assume a multi-line chart with a log-scale. Can we compare the lines by the selection from menu on a page etc.

**Environment (if applicable)**
- amCharts 4
- Firefox 67
- JavaScript

**Additional context**

**Comment by martynasma** [comment]
While it's totally doable, we don't have a ready-made example for that, I'm afraid.
