### ISSUE TITLE
Issue in 4.9.20 Version.

### ISSUE THREAD

**Issue by sameerrswt** [amcharts/amcharts4#2469]
Error is getting while building application in version 4.9.20 but in 4.9.19 is working fine.

Please check or suggest.

![4_9_20_amcharts](https://user-images.githubusercontent.com/17155131/81781482-cd556900-9515-11ea-97b6-422fed57d013.PNG)

**Comment by martynasma** [comment]
Duplicate of #2462. Please follow that issue.
