### ISSUE TITLE
am4core.options.queue and am4core.options.onlyShowOnViewport does not work with Containers

### ISSUE THREAD

**Issue by MuratGT** [amcharts/amcharts4#2470]
**Bug description**

Following Options are set:

        am4core.options.queue = true;
        am4core.options.onlyShowOnViewport = true;

and the render

        let container = am4core.create(this.id, am4core.Container);
        container.width = am4core.percent(100);
        container.height = am4core.percent(100);
        let indicator = container.tooltipContainer.createChild(am4core.Container);
        indicator.background.fill = am4core.color("#fff");
        indicator.background.fillOpacity = 0.8;
        indicator.width = am4core.percent(100);
        indicator.height = am4core.percent(100);
        let indicatorLabel = indicator.createChild(am4core.Label);
        indicatorLabel.text = "Loading stuff...";
        indicatorLabel.align = "center";
        indicatorLabel.valign = "middle";
        indicatorLabel.fontSize = 20;

Then only one Container is displayed with the text "Loading stuff". However I have 9 Containers like that all with an unique id. If I turn off `queue`, then suddenly three Containers are rendered. If I also turn off `onlyShowOnViewport ` then all Containers are rendered.

The curious thing here is, if I use a `Chart` instead of a `Container`, then everything works perfectly fine with both options turned on.

` let container = am4core.create(this.id, am4charts.XYChart);`

Tech:

 "@amcharts/amcharts4": "4.9.21"
 "react": "16.10.2"
Chrome Browser

**Comment by martynasma** [comment]
Working example:
https://codepen.io/team/amcharts/pen/e8a220cb161efaaa1e2ca5a0987dff04?editors=0010

**Comment by MuratGT** [comment]
It does not work?

![image](https://user-images.githubusercontent.com/59017068/81831765-0c97b000-953e-11ea-9aef-512e63736e4f.png)

**Comment by martynasma** [comment]
Sorry I wasn't clear. This is a live example for dev team to experiment with ;)

**Comment by martynasma** [comment]
Fixed in [4.9.22](https://github.com/amcharts/amcharts4/releases/tag/4.9.22).

## [4.9.22] - 2020-05-14

### Changed
- Export: Now using forked version of `canvg` until underlying issues are fixed in source library.

### Fixed
- `queue` and `onlyShowOnViewport` were not working properly on regular `Container` instances.
- Export: Garbled IE image exports fixed.
- Some tooltips were reappearing on `MapChart` after their `showToolipOn` was reset back to `"hover"` from `"always"`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by MuratGT** [comment]
Looks like the queue is fixed while the option `onlyShowOnViewport` seems broken.

https://codepen.io/MuratGT/pen/vYNzGLa

You can see in the console logs that `datavalidated` and `beforedatavalidated` happens for all charts simultaneously while not in the viewport.

**Comment by MuratGT** [comment]
Ideally the Containers would load immediately with the loading icon while the charts will be loaded on scrolling into the viewport.

**Comment by martynasma** [comment]
OK, so we released a new version which adds new event: `removedfromqueue`.

I suggest using it to trigger the creation of the next container:

```
container1.events.on("removedfromqueue",function() {
  // create the next one
});
```

**Comment by MuratGT** [comment]
Could you give me an example how I would use that in the above codepen example?

**Comment by martynasma** [comment]
There ya go:
https://codepen.io/team/amcharts/pen/a218f79638359a160ee6105e022c3212?editors=1111

**Comment by MuratGT** [comment]
Thanks. It works
