### ISSUE TITLE
SyntaxError: Unexpected token 'export' with jest in Angular 9 project

### ISSUE THREAD

**Issue by davidefontana** [amcharts/amcharts4#2471]
Hi i have problems to run a test with an amcharts import on angular 9 project with jest. 

I use the guide described here to [install jest](https://www.xfive.co/blog/testing-angular-faster-jest/) on an angular project.

But when i use anything imported from amcharts and start a jest test i have this error.

`● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.  

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".       

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\workspace\repos\mfw-ng\node_modules\@amcharts\amcharts4\charts.js:7
    export { GaugeChartDataItem, GaugeChart } from "./.internal/charts/types/GaugeChart";
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import * as am4charts from '@amcharts/amcharts4/charts';
        | ^
      2 | 
      3 | describe('test', () => {
      4 |     it('should be true', () => {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)  
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/app/order-monitor/components/chart-rendering/test.spec.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        11.301s`

I create an example angular project with this error. 

[https://stackblitz.com/edit/angular-ivy-ud1rtv](https://stackblitz.com/edit/angular-ivy-ud1rtv)
I also have tried to add 
`"transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\](?!(@amcharts)\\/).+\\.js$"
],`

on package.json jest config but seems don't work. 

Any ideas ? 
Thanks in advance :D

**Comment by martynasma** [comment]
Please refer to this note:
https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/#Using_amCharts_with_Jest

**Comment by davidefontana** [comment]
But as you can see with jest the import refers to js file instead of typescript module is C:\workspace\repos\mfw-ng\node_modules\@amcharts\amcharts4\charts.js:7

**Comment by Pauan** [comment]
@davidefontana Our npm package does not contain TypeScript code, it contains regular `.js` code + `.d.ts` type signatures. This is normal for libraries, since it allows the code to work in both ES6 and TypeScript.

In any case, Jest won't work with amCharts, because Jest does not support SVG.

**Comment by davidefontana** [comment]
I solve the issue moving the amcharts rendering in an angular library with karma  & jasmine.

**Comment by giang21199z** [comment]
Hi @davidefontana.
I've just met your issue.
But As I know karma & jasmine didn't cover all files in project.
