### ISSUE TITLE
Chart intro animation plays differently if the same JSON is loaded via data or dataSource

### ISSUE THREAD

**Issue by virtualdj** [amcharts/amcharts4#2473]
**Bug description**

I tried with the **same JSON data** (12 categories with 12 values, 406 bytes) to create an XYChart first using the _data_ property and then with the _datasource_ (by loading the json file externally) as described on the [am4chart docs](https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/#JSON).
- When using the _data_ property the initial chart animation is smooth and the bars appear from right to left (see example below) perfectly.
- When using _datasource_ the chart "fades in" and there is basically no animation.

If the data is the same it shouldn't behave differently, right?

**Environment (if applicable)**

- Latest amCharts v4 (JS linked from the original website)
- Tried both Firefox 76 and Chrome 81 on Windows 10

**Additional context**

Please see the attached [examples.zip](https://github.com/amcharts/amcharts4/files/4629515/examples.zip).
When loaded in a web server (such as [MiniWeb HTTP Server](https://sourceforge.net/projects/miniweb/) **htdocs** folder) there are two versions of the same HTML and you can clearly see that there is no bar animation when using the _datasource_ version.

**Comment by virtualdj** [comment]
I've tried adding the snipped like this in **bar_datasource.htm** example file:

```
// Themes
am4core.useTheme(am4themes_dark);
am4core.useTheme(am4themes_animated);

// Chart
var chart = am4core.create("chartdiv", am4charts.XYChart);

// Chart data (from JSON file)
chart.dataSource.url = "data.json"
chart.dataSource.parser = new am4core.JSONParser();

// Add animation
chart.dataSource.events.on("loadended", function() {
  chart.series.each(function(series) {
    series.appeared = false;
  });
});

// Background
chart.background.fill = am4core.color("#00008c");
```

But it doesn't change: the chart with dataSource fades in, while with the other example the bars are animating smoothly and progressively.

**Comment by martynasma** [comment]
Can you post your chart on CodePen?

**Comment by virtualdj** [comment]
I tried initially, but with a Codepen free account I cannot upload the JSON file (and without that you can't spot the issue). However if you download the ZIP file on the first post you can find the two versions that differ only for the direct JSON or external JSON.

**Comment by martynasma** [comment]
Sorry, but this would go beyond the free support scope. I could take a look at online editable demo, but downloading and setting up custom test env goes beyond our capacity, unless you have a paid support subscription, in which case you should email contact@amcharts.com.

**Comment by virtualdj** [comment]
OK, I can understand this, but please try with any sample on your own with an animated chart and the same data "inline" (just as all the AmCharts  samples) and then with the data moved on an external JSON file. Does the animation work the same, or the chart is only fading in?
I just followed the documentation, like you can see on the code snippet on the last post.

**Comment by virtualdj** [comment]
I've just tried again, to be 100% sure. Steps to reproduce:

1. I've copied and pasted the [Simple Column Chart demo](https://www.amcharts.com/demos/simple-column-chart/) source code to a file named **1.htm** inside my web server.
2. I've copied **1.htm** to **2.htm** and cut the JSON data to a new file named **2.json**
3. I've edited **2.htm** by changing:
```
// Add data
chart.data = [{ ... }];

// Create axes
```
with:
```
// Add animation
chart.dataSource.events.on("loadended", function() {
  chart.series.each(function(series) {
    series.appeared = false;
  });
});

// Chart data (from JSON file)
chart.dataSource.url = "2.json"
chart.dataSource.parser = new am4core.JSONParser();

// Create axes
```
4. If I navigate to my **localhost/1.htm** the column series animation is played correctly, while if I navigate to **localhost/2.htm** the chart fades in. No other edits!

**Comment by virtualdj** [comment]
The bot is right as this issue is currently stale, but the problem is still there.
So this shouldn't be closed, IMHO.

**Comment by martynasma** [comment]
Please refer to this ticket for solution:
https://github.com/amcharts/amcharts4/issues/1621

**Comment by virtualdj** [comment]
Thanks, this finally worked correctly (i.e. **2.htm** behaves exactly like **1.htm**).
```
// Add animation
chart.events.on("datavalidated", function() {
  chart.series.each(function(series) {
    series.appear();
  });
});

// Chart data (from JSON file)
chart.dataSource.url = "2.json"
chart.dataSource.parser = new am4core.JSONParser();

// Create axes
```
