### ISSUE TITLE
Would like to create chart without parent html element

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts4#2477]
(Enhancement)
Just wanted to let you know that in some cases the instantiation order is a problem. Would be nice if you can create a chart object without placing it in the DOM model, set all properties and after that place the chart into a parent html element for it to render.

In other words, split the call

    var chart = am4core.create(this.getDomRef(), am4charts.RadarChart);

into two calls

    var chart = am4core.create(am4charts.RadarChart);
    chart.xAxis.push(new am4charts.CategoryAxis());
    chart.radius = 200;
    chart.placeAt(this.getDomRef());

I am currently wrapping am4charts into SAP OpenUI5 custom controls and because of the instantiation order, need to jump through a few hoops.

Recursion 1
In the Open UI5 framework you set the child controls first and at a later time they get rendered. Which is a problem with am4charts, as in order to set the chart properties, it needs to be created, in order to create it, it needs a DOM element. As this recursion cannot be prevented, I had to store all properties elsewhere and at render time create the chart and copy the values.

Recursion 2
Luckily the axis can be created without a relationship to the chart. Except that the renderer is not available at the time. It is obvious why there is no renderer without a chart it belongs to but again, I have to store the values somewhere else and copy at render time.

No idea how difficult it would be and the potential side effects.
As said, I can workaround it but wanted to let you know.

**Comment by martynasma** [comment]
I'm marking this as an `enhancement` for the future. However, it might be difficult to implement, given underlying structure.

**Comment by wernerdaehn** [comment]
Works like a charm and helped simplify my UI5 wrapper significantly.
Thanks!
