### ISSUE TITLE
Clustered bar chart with collapsed empty series columns

### ISSUE THREAD

**Issue by virtualdj** [amcharts/amcharts4#2478]
**Question**

I would like to create a "packed" **Clustered bar** chart (see image below) with these features:
1. without **any space** between the displayed columns and the missing ones (those with empty or zero values)
2. **centered** on the category axis
3. (possibly, with a property) **hiding from the legend** the series without any value in every category

**Sample data**

https://codepen.io/virtualdj/pen/MWaPMYJ

```
chart.data = [{
  "year": 2018,
  "A": 23.5,
  "B": 18.1
},{
  "year": 2019,
  "A": 26.2,
  "C": 22.8
},{
  "year": 2020,
  "A": 24.6,
  "B": 25,
  "D": 33
}];
```

**Expected result**

![Expected_Result](https://user-images.githubusercontent.com/3251704/82154896-4126a700-9871-11ea-955c-eb2f97763d2c.png)

**Environment (if applicable)**

- amCharts 4
- Firefox 76

**Comment by martynasma** [comment]
I'm afraid there's no way to "collapse" places of columns with empty values. Sorry.

**Comment by virtualdj** [comment]
Is it something suitable for a feature request / future version?
I'm not able to think about another better chart type to display my data (few series, more categories) than columns.

**Comment by martynasma** [comment]
Well, we don't have any plans on implementing it right now, I'm afraid.

However, you can work around it by using bogus categories (one category per column) and axis ranges for grid/labels.

Like on this example:
https://www.amcharts.com/demos/grouped-and-sorted-columns/

**Comment by virtualdj** [comment]
I made some tests, it's not bad after all, but unfortunately I'll loose the ability to show the legend of the series because every column will be charted as one in this way.

**Comment by martynasma** [comment]
Not at all. You can use multiple series. Just ensure there's only one value per category. Also set `clustered = false` for all series.

**Comment by virtualdj** [comment]
I used the example above and modified the script to push the correct values:

https://codepen.io/virtualdj/pen/OJyrRBm

> Not at all. You can use multiple series. Just ensure there's only one value per category. 

I'm still out of ideas on how to **create different series** (actually for each _realName_ on the array) to allow the legend to be displayed correctly and interactively (hiding/showing only those values) like on the example above.
Also the legend colour is not correct now, probably due to the adapter firing the first time with an undefined _realName_.

> Also set `clustered = false` for all series.

Doesn't seems to make any difference with `clustered` true or false, probably I'm missing something else?

**Comment by martynasma** [comment]
Here's an example of a simple chart with three series, one per category.

https://codepen.io/team/amcharts/pen/0fa20bce3ff5fb59e2d7f003356585de?editors=0010

Hope you can use it to modify your chart as needed.

**Comment by martynasma** [comment]
That's what I was trying to pitch: there's only one value per data point.

And if you need names in legend, you add `name` attribute of the series.

**Comment by virtualdj** [comment]
> That's what I was trying to pitch: there's only one value per data point.

OK, but how do I "group" the multiple activities (A, B, C, D or value1, value2, value3) of the same year (2018, 2019, 2020 or Research, Marketing, Distribution) then? The columns overlap even if I duplicate the JSON objects...

Should I name the categories differently, such as Research1, Research2, Research3?

**Comment by martynasma** [comment]
Yes. Categories need to be unique. You can disable actual category labels and use "axis ranges" to group columns, like in the demo I posted earlier.

**Comment by virtualdj** [comment]
Thanks, I must say this library is definitely **fabulous**, once you understand how to tame it!
This is my final result:

https://codepen.io/virtualdj/pen/rNOPGxP
