### ISSUE TITLE
expandAll adapter for ForceDirectedNode is never called

### ISSUE THREAD

**Issue by adititipnis** [amcharts/amcharts4#2479]
Adding an adapter for the expandAll property of a ForceDirectedNode like in the following snippet does not work, the callback is never executed. (Changing the adapter argument to an other property like strokeWidth will work correctly)

```
series.nodes.template.adapter.add('expandAll', (expandAll, target) => {
      const context = target.dataItem._dataContext;
      if (//some condition) return true;
      else return context.expandAll;
    });
```
The expected behavior is that the callback will be called.

The actual behavior is that the callback is never executed.

The expandAll property is listed in the Adapters of the ForceDirectedNode Class. https://www.amcharts.com/docs/v4/reference/forcedirectednode/#expandAll_adapter

**Comment by martynasma** [comment]
The `expandAll` property is checked only when you click on the collapsed node, at which point adapter for it kicks in.

I just verified it to be case.

If you are getting different result, maybe you can post your live chart on CodePen/jsFiddle so that we can check?

**Comment by adititipnis** [comment]
Yes, that's right. But I want the condition to be applied starting from the first time when the nodes are rendered. (So some nodes will be expanded to all the children and some will not when rendering for the first time). Is there something else for that?

**Comment by martynasma** [comment]
Gotcha.

`expandAll` does not do that. It's a setting that affects click on the node.

The only way to have pre-expanded nodes is to use `collapsed` data field:

https://codepen.io/team/amcharts/pen/c7e1388a0fc431d0986aed0adf359c38?editors=0010
