### ISSUE TITLE
Move the line on the X by dragging

### ISSUE THREAD

**Issue by mrmime95** [amcharts/amcharts4#2485]
**Question**

The line doesn't follows the bullet on X. How could I resolve it?

![May-19-2020 17-03-36](https://user-images.githubusercontent.com/18379137/82336027-bc639680-99f2-11ea-8f71-fa138d8f45f9.gif)

I tried it on the following CodePen project (lines 100-110):
https://codepen.io/mrmime95/pen/MWwNGpO?editors=0010

Moving exemple is form: 
https://www.amcharts.com/demos/drawing-chart-series-with-mouse-or-touch/

Thanks!

**Comment by zeroin** [comment]
It's a bit complicated, as you need to add this line in dragged event:

`dateAxis.postProcessSeriesDataItem(bullet.dataItem);`

Modified pen:
https://codepen.io/team/amcharts/pen/bGVOrzo

**Comment by mrmime95** [comment]
Thank You verry much! :)
