### ISSUE TITLE
First tooltip does not show

### ISSUE THREAD

**Issue by tapiamcclung** [amcharts/amcharts4#2486]
Found #2076 and was redirected to #1464.
Bringing this back up, I added a cursor to highlight stuff while displaying the tooltip on hover.
Forked the basic heatmap and added the appropriate cursor stuff and added this from the above:
```
series.cursorTooltipEnabled = false;
```
It works, except the first tooltip does not show up... Its element's visibility remains "hidden" and its opacity is 0. Hovering on subsequent cells shows normal functionality.
Here's a pen:
https://codepen.io/tapiamcclung/pen/GRpvvpm
Thanks!

**Comment by martynasma** [comment]
Which tooltip do you mean? And which is "first"? :) Afraid, I can't reproduce it.

![2020-05-20_08-32-04](https://user-images.githubusercontent.com/1458520/82408579-8830ba00-9a74-11ea-9eab-e578eac94353.gif)

**Comment by tapiamcclung** [comment]
Hi!
Something like this. I am referring to the tooltip on the grid cells, not on axes or HeatLegend.
By "first" I mean the first one I hover on. In the following example I hover on the top right cell and there is no tooltip at first. Then I move out and return, and it shows up. 
![C2DDC26A-C181-4A14-A400-4C9B9DDBFAE0](https://user-images.githubusercontent.com/7925327/82449022-2e2df580-9a70-11ea-9f78-cc4bfb927e90.GIF)

Something similar occurs if I hover to another cell, but in this case, the "first" tooltip does not show up. The one for the next cell does, and if I return to the previous one, it now shows.
![4A537111-CAFC-453C-A8CC-DCFD9501AC3D](https://user-images.githubusercontent.com/7925327/82449554-04c19980-9a71-11ea-856b-00d4769adfed.GIF)

Hope these examples help better understand the issue.
Thanks!

**Comment by martynasma** [comment]
Gotcha. Indeed.

**Comment by martynasma** [comment]
OK, so I probably know what's going on. If you hover while chart still is animating, the tooltips are hidden.

Does this happen if you let the chart to fully fade in before hovering?

**Comment by tapiamcclung** [comment]
I think so... Visually, I see the chart is done animating, but am not sure if the ready or done event would fire or if something is still being executed. If I wait a little longer, it does show up.

**Comment by zeroin** [comment]
Tooltip is not shown during initial animation. If you set:

`series.showOnInit = false;` it should work fine.

**Comment by tapiamcclung** [comment]
Great, thanks!
