### ISSUE TITLE
Access ImageSeries variables for conditional checks

### ISSUE THREAD

**Issue by ricardo-afonso** [amcharts/amcharts4#2487]
I'm using amCharts4 to display a map that has some bubbles ( circles ) appearing over some countries and some data associated with it. After building my data object I pass it to the series:

```
let imageSeries = chart.series.push(new am4maps.MapImageSeries());
imageSeries.data = dataObjectArray;
```
The dataObjectArray is an array of objects, each of which has a few properties that enable it to be rendered in the correct place, such as province, and some values associated with it. ( Also, I'm using the calculate visual center option ). So for an example object inside that array, we'd have

```
{
  province: 'CA',
  name: 'Canada',
  value: 12.3,
  size: 5,
}
```
Now, for this ImageSeries, I add a circle and a label as children, to display the info I want. I also add some colors to the label using amchart's own way of formatting text, such as:

`imageSeries.template.tooltipText = '{name}: [#ff0000]{value}[/]';`

However, I'd like that color to be conditional. If the value is positive, the color would be green, and if negative, red. I could easily check the sign of the value using Math.sign(), however, I have no idea how to access the value itself and have each individual tooltip act accordingly. I've looked at the documentation regarding data binding, but it doesn't seem to help me access the variables I need.

**Comment by xorspark** [comment]
You can add an [adapter](https://www.amcharts.com/docs/v4/reference/adapter/) on the image's tooltipText property and check the value through the target's dataItem property. For example, assuming the tooltip is set on the image itself:

```
image.adapter.add('tooltipText', function(text, target) {
  text = "{name}: [";
  if (target.dataItem && Math.sign(target.dataItem.value) === -1) {
    text += "red]";
  }
  else {
    text += "green]";
  }
  text += "{value}[/]";
  return text;
});
```

Here's [demo](https://codepen.io/team/amcharts/pen/4ea17773696695f8d52fe14aff791bea?editors=0010) of this in action using our Map with bubbles demo as a base that sets the tooltip value text color based on whether it is smaller than 25 mil or not.

**Comment by ricardo-afonso** [comment]
Thanks, that solved it!
