### ISSUE TITLE
Updating a map with React useState hook. Does amcharts4 support React hooks?

### ISSUE THREAD

**Issue by fbuireu** [amcharts/amcharts4#2488]
I am trying to set a map using amcharts 4 in a Gatsby project. I've followed some tutorials and some demo code and I've adapted it to make them work using React hooks (not a big deal changing `componentDidMount  `for `useEffect`).

My map is trying to create a line between destinations depending on the user's choice, from origin to the selected destination. 

When I set and create the map, I trigger a function that store the cities in a custom object:

```
  const setInitialCities = mapCities => {
    cities.forEach(city => {
      let mapCity = mapCities.mapImages.create();

      mapCity.latitude = city.coordinates.coordinates[1];
      mapCity.longitude = city.coordinates.coordinates[0];
      mapCity.tooltipText = city.name;
      mapCity.name = city.name;

      mapConfiguration.mapCities.push(mapCity);
    });
  };
```
Everything works fine here; the cities are shown in the map. Once the map is set, I add to the previous cities a listener to them:
```
    mapConfiguration.mapCities.forEach(city => {
      city.events.on(`hit`, element => {
        addLine(initialCity, element.target);
        flyPlane();
      });
    });

```
The previous code works too, but just for the first use click because the plane moves from `initialCity `to `element.target` city and the state are not updated.

My wish is to store the `element.target ` in a `useState `hook in order to update it on every user click, replacing  `addLine(initialCity, element.target);` by` addLine(STATE_ORIGIN, STATE_DESTINATION)`. My issue is:

- If I use `useEffect `with empty `deps`: I can't set a `useState`, it always gets the initial value.
- If I use a `useEffect `without `deps`: I can set a custom origin/destination but the map reloads.

How can I achieve it? Is there another workaround to do this?

 
Environment (if applicable):
- amcharts: 4.9.22
- Gatsby: ^2.19.7
- React: ^16.12.0

**Comment by CristianoYL** [comment]
There's a lot of implementation details here that I might not be aware of. But my 2 cents are:
- manage the city data as state (`useState`), and have the state in your `useEffect` reps, this will allow the effect only triggered by city update.
- If you don't want the map to be reloaded each time, you can have multiple `useEffect`, each triggered by different conditions (deps). So one effect would be loading the map, doesn't triggered by city update. The other effect handles that.
