### ISSUE TITLE
Bad example in documentation

### ISSUE THREAD

**Issue by samuelpucat** [amcharts/amcharts4#2489]
Hi, i think i found a mistake here https://www.amcharts.com/docs/v4/concepts/axes/date-axis/ 
![image](https://user-images.githubusercontent.com/18383653/82442338-becffa00-9a9f-11ea-8a96-d31b26b91d0a.png)
the groupFields object should be directly on series not inside dataFields

**Comment by martynasma** [comment]
Good catch. Thanks!

Docs fixed.
