### ISSUE TITLE
Multiple y-values for same x-value

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#2491]
Is possible to show multiple bullets at different y-values but for the same x-value and using the same serie?
Suppose I have a serie with temperature measurements, I want to show them every hour, bot in some hours could be 0 measurement and at another hour could have 5 measurements, in that case I want to show the 5 values (it's ok to show them as bullets).

**Comment by zeroin** [comment]
Hi,

You can have any number of bullets per series however series does not have so many data fields. So I would suggest using multiple series for your purposes.

**Comment by enriquepiatti** [comment]
But I don't know how many measurements I will have for every time value, do I need to create 100 series just in case I have 100 values in some time?

**Comment by zeroin** [comment]
You could create series on demand - before passing the data to the chart, make some data processing method which would also add series if it stumbles upon dates which have more series than you already have. 

Another possible approach would be add a lot of data items with the same dates to one series. This however might result some undesired results if you use cursor, like only one tooltip will be displayed when hovering a certain date.
