### ISSUE TITLE
Exporting for all child elements of a container

### ISSUE THREAD

**Issue by ahajric2** [amcharts/amcharts4#2493]
** Question **

I'm looking to stack multiple am charts as elements inside a container and have the ability to export each charts data. 

Currently, if I use the containers code provided by the documentation, I can alter this to allow exporting. However, it only works for the bottom chart. Is this a limitation of am charts, or should I be able to allow exporting for all charts inside a container? 

Here is the documentation I'm referencing: https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/
Here is the code pen I'm using to test:https://codepen.io/Azzmir/pen/GRpzWdp

I'm using this concept for another project, where I'm running into issues with this, but need to allow exporting for all chart children. I'm using Angular 7, latest version of am charts 4 and debugging in Google Chrome.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
