### ISSUE TITLE
Problem with max value in Y Axis. Max become bigger than setted max.

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#2494]
Problem with multi-lines.
My Yaxis is percent(efficient), so i set settings
valueAxis.min = 0;
valueAxis.max = 100;
valueAxis.strictMinMax = true;

But it draw max value 140. If set max=50, it draw 70 and so on. Always bigger than i need.
PROOF http://jsfiddle.net/7svjbq32/
but if line is only one - everything is OK...
example http://jsfiddle.net/7svjbq32/

**Comment by martynasma** [comment]
The issue is with the use of `syncWithAxis`. That feature invokes a pretty complex fuzzy logic, which might override `max`. I'm sorry but we won't be able to fix this. My suggestion would be to not use axis syncing if you need explicit precise scale.

**Comment by russeljo** [comment]
> The issue is with the use of `syncWithAxis`. That feature invokes a pretty complex fuzzy logic, which might override `max`. I'm sorry but we won't be able to fix this. My suggestion would be to not use axis syncing if you need explicit precise scale.

After resize it draw right way. So, maybe trigger some resize event? How?

**Comment by martynasma** [comment]
OK, that changes it. If the scale is restored properly after zoom, then it must be some timing bug. We'll look into it and let you know.

Thanks for additional details!

**Comment by russeljo** [comment]
I've try to not use **syncWithAxis** for my line and it's work! Thank you!

**Comment by martynasma** [comment]
We've looked into this. Unfortunately, like I wrote before, with such immense logic at play, we won't be able to resolve this when both `max` and `syncWithAxis` is used. Sorry.
