### ISSUE TITLE
innerRadius doesn't appear to work on the radarChart when used in a column chart.

### ISSUE THREAD

**Issue by alan-1066** [amcharts/amcharts4#2496]
Hi,

`innerRadius` doesn't appear to work on the radarChart when used in a column chart.

https://codepen.io/alan1066/pen/bGVxwox

Thanks!

**Comment by martynasma** [comment]
Seems like duplicate of this: #2484

**Comment by alan-1066** [comment]
Thanks for the latest version, however this doesn't fix an issue when applying innerRadius to a RadarChart that is added as a child of a column chart.

`var radarChart = series1.columns.template.createChild(am4charts.RadarChart);
  radarChart.innerRadius = 20 // innerRadius is ignored;`

**Comment by martynasma** [comment]
Try setting `innerRadius` on a renderer:

```
radarChartValueAxis.renderer.innerRadius = 20;
```

**Comment by alan-1066** [comment]
Awesome, Thank you @martynasma it now works perfectly.
