### ISSUE TITLE
Unable to get the name of the Tree dataItem in Treemap chart

### ISSUE THREAD

**Issue by sunith-kumar** [amcharts/amcharts4#2497]
**Bug description**
Unbale to get the name on click/hit  ev.target.dataItem.name returning undefined
 
from the below image if the click event has occured on A5 , how can i get the name A5.

![image](https://user-images.githubusercontent.com/44740648/82681862-02775f00-9c6c-11ea-8b71-72ab4abdac19.png)

level2SeriesTemplate.events.on(
      "hit",
      function (ev) {
        console.log("clicked on ",  ev.target.dataItem.name);      },
      this
    );

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
You set your event target to the whole series. You should set on a column template:

```
level2SeriesTemplate.columns.template.events.on("hit", .....);
```

**Comment by sunith-kumar** [comment]
Thank you
