### ISSUE TITLE
Custom number format in columnSeries.tooltipText

### ISSUE THREAD

**Issue by HidemitsuHashimoto** [amcharts/amcharts4#2498]
**Question**

Hello, i need a custom number format because i use currency values in my chart.

How can i change a value for Brazil currency format?

I use this line to make tooltip with sales value:
columnSeries.tooltipText = `${shopName}: R$ {valueY}`;

**Environment**

 - amCharts 4
 - Chrome
 - React 16.8.6

**Comment by xorspark** [comment]
AmCharts supports formatting numbers using the [Intl object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) as documented [here](https://www.amcharts.com/docs/v4/tutorials/formatting-date-time-and-numbers-using-intl-object/). You can set the object directly in the chart and it will format your values accordingly:

```
chart.numberFormatter.numberFormat = {
  "style": "currency",
  "currency": "BRL"
}
chart.numberFormatter.intlLocales = "pt-BR";
// ...
columnSeries.tooltipText = "{shopName}: {valueY}"; //{valueY} will include the Brazilian real symbol as well
```

Demo: https://codepen.io/team/amcharts/pen/826f32d2b806ea1333f621455185d9c6?editors=0010

**Comment by HidemitsuHashimoto** [comment]
It worked. Thanks a lot for the help.
