### ISSUE TITLE
tooltip show outside chart container

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2500]
tooltip show outside chart container
![image](https://user-images.githubusercontent.com/22093903/82728663-2176ff00-9d07-11ea-9997-7f10f659064c.png)

**Comment by martynasma** [comment]
Well there are a lot of tooltips so they don't fit.

There are a few options for you to consider:
1) Consolidate all data in a single tooltip.
2) Show tooltips to closest series only.
3) Increase `z-index` of the chart div on hover so that it's tooltips are over the rest of the page elements.
