### ISSUE TITLE
Animate a dashed line

### ISSUE THREAD

**Issue by fbuireu** [amcharts/amcharts4#2501]
I am trying to build a dashed line between two points in an amCharts 4 map based on this [CodePen][1].
I've tried something like this without succeed:

    let lineSeries = chart.series.push(new am4maps.MapLineSeries());
    lineSeries.mapLines.template.strokeWidth = 4;
    lineSeries.mapLines.template.stroke = am4core.color("#e03e96");
    lineSeries.mapLines.template.nonScalingStroke = true;
    lineSeries.mapLines.template.line.strokeDasharray = `.25rem`;

Of course, I can dash the line with CSS by:

    .amcharts-myline path {
      stroke-linejoin: round;
      stroke-linecap: round;
      stroke-dasharray: 8px;
      -webkit-animation: am-draw 40s forwards;
      animation: am-draw 40s;
    }

However, it makes a weird effect. I just want to make it as the initial animation, from A to B point forwarding the effect with a dashed line.

As far as I know SVG and dashed lines, I need to create another SVG and animate it but I can't figure out how to do it by keeping the structure.

  [1]: https://codepen.io/team/amcharts/pen/QWbEwEj?editors=1010

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
