### ISSUE TITLE
[Question] Using amCharts map, is there a way to limit the number of images displayed at one time?

### ISSUE THREAD

**Issue by ricardo-afonso** [amcharts/amcharts4#2502]
I'm using amCharts map module to display a lot of 'bubbles' with some information on a map, that are always visible ( not only on hover ). However, as there is a considerable number of countries that have data associated, this can lead to a cluttered map. I've followed the amcharts example to hide images until zoomed ( https://www.amcharts.com/docs/v4/tutorials/hide-map-images-until-zoomed-in/ ) but this leads to another problem:  On less cluttered areas of the map, some 'bubbles' don't show up until very zoomed in. This has led me to pursue another solution: Try to limit the number of bubbles that are displayed at once. I found an example about data grouping that could be useful but it's unavailable on maps (https://www.amcharts.com/demos/data-grouping-50k-points/). I've tried another solution, after looking at the properties of MapImages and Chart containers: By using a mix of fitsToBounds and getSvgPoint, I could try to figure out if a bubble is within the bounds of the 'visible' map ( for example when I'm zoomed in on certain continents ), and unhide bubbles until a certain number is reached ( 10, for example). This would be called on the 'zoomLevelChanged' and 'drag' events. For that I tried to repurpose the Hide images until zoomed example and do something like
` function updateImageVisibility(ev) {
  let chart = ev.target.baseSprite;
  let series = chart.map.getKey("markers");
  series.mapImages.each(function(image) {
    if (chart.fitsToBounds(chart.getSvgPoint(image)) {
      // show image if less than 10 are displayed
    }
  });
}`

However this is not working and I'm not sure why, so any help or other methods to achieve this would be appreciated.

**Comment by martynasma** [comment]
Can you post a full working example you have so far?

**Comment by ricardo-afonso** [comment]
Sure, using the example for 'Hide images until zoomed', I changed the `updateImageVisibility` function. It does not work, but I think the intention is somewhat clear:

https://codepen.io/Gryxs/pen/GRpLvmz

**Comment by ricardo-afonso** [comment]
I think I can adapt this code to my needs, thank you!
