### ISSUE TITLE
How to dynamically update the Label text using dummyData?

### ISSUE THREAD

**Issue by digrich** [amcharts/amcharts4#2503]
We are trying to use amchart containers for our UI layout and in one of container we need to display some text and for that we have started using amChart Label component. Some content of Label text is coming from the container dummyData and it reads that value correctly. When we get the updated data, Label text doesn't reflect the updated value.

[CodePin example](https://codepen.io/dig_rich/pen/GRpearZ?editors=1111)

Now sure if we have taken the right approach, but this doesn't reflect the change on Label text.  We are using simple amchart container and label without any chart component and trying to dynamically bind the label data.

**Comment by digrich** [comment]
Noticed that after updating the data, calling invalidateLabels() reflect the latest changes on Labels. Is it fare to call invalidateLabels on every new data update?

**Comment by martynasma** [comment]
Yes, it's the correct approach. `Component` does not automatically invalidate all of its labels on data update. That would be a resource waste. So manually forcing label invalidation seems easonable.

**Comment by digrich** [comment]
Thanks @martynasma

**Comment by digrich** [comment]
Hi @martynasma - One small question if you can quickly help me. Using amchart, how can I draw a simple straight line within a container? I want to draw a line with Container.

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by digrich** [comment]
Agree, I will post a separate issue if I am not able to figure out. Thanks @martynasma
