### ISSUE TITLE
Series tooltip inherit pattern & background - Question

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#2504]
**Question**

Hy there,

When using patterns to fill series, how can I set tooltip to inherit series background fill also
(or create a pattern / background fill separately).

![amcharts-tooltip-inherit-initial](https://user-images.githubusercontent.com/21243081/82753334-6cf3e080-9dcd-11ea-8824-38496cde6119.png)

I would like something like this.

![amcharts-tooltip-inherit](https://user-images.githubusercontent.com/21243081/82753299-3f0e9c00-9dcd-11ea-8f9b-ad001f88732e.png)

Please see pen attach bellow.
https://codepen.io/aniov/pen/PoPLXNg?editors=0010

Thank you in advance.

**Comment by amcharts** [comment]
A solution would be to have fill in the pattern, this way all the pattern will be copied to the tooltip background. I've tried it and it works with one issue:

https://codepen.io/team/amcharts/pen/ExVJVNj

I will fix this issue (a pattern is now in a rectangle) in next release. Alternatively you can solve this even now by setting fillOpacity of a pattern background to 1 and choosing the lighter color for the background:

https://codepen.io/team/amcharts/pen/pojBjRY?editors=0010

**Comment by aniov** [comment]
Thank you.
I will be using second solution. 
I've tried to fill the pattern color background but I didn't think that "backgroundFill" will work :)
Maybe if you could show this in your pattern examples would help. :)

Thank's.
