### ISSUE TITLE
Change background opacity tooltip without change background color

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2505]
How change background opacity tooltip without change background color?

**Comment by martynasma** [comment]
This might help:
https://www.amcharts.com/docs/v4/tutorials/overriding-series-tooltip-fill-color/

**Comment by HASSANDL** [comment]
I see this doc, I want only change opacity without change colorful tooltips.

**Comment by martynasma** [comment]
Not sure what you mean then. Please consider providing a better description.

**Comment by HASSANDL** [comment]
I want inherit color tooltip from related slice and only change opacity of inherited color.

**Comment by martynasma** [comment]
```
pieSeries.tooltip.background.fillOpacity = 0.2;
```

**Comment by HASSANDL** [comment]
Very thanks.
