### ISSUE TITLE
Draw line above the land

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#2506]
**Question**
What I would like to have is that the line on a map between two cities will be on the land. The line should cross the UK and Canada. See screenshot.
![Screen Shot 2020-05-25 at 11 21 54 PM](https://user-images.githubusercontent.com/33300743/82857587-6f465f80-9edf-11ea-9d1d-27cbfe4e66a1.png)

What I did?
I create the map chart using ngAfterViewInit in order to generate a map chart and then make it interactive with the user input. I tried to generate the map in ngOnInit but it will defeat the purpose of making it interactive.

Link: https://codesandbox.io/s/priceless-einstein-6swd4?file=/src/app/components/map/map.component.ts

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
If I understand your question correctly, you want to make the line stand out against the background.

For that you need to make line series go over the polygon series. You can do that by adding it after polygon series, or by calling `toFront()` on image series.

You also probably need to color it differently using `stroke`.

**Comment by AlexandreKang** [comment]
I don't know how to make line series go over the polygon series as the line series is created in a function called ```getDestinationCity```.

This function is called when someone submit a destination city (in this example, it's berlin). The polygonseries is created in ```ngAfterViewInit() ```.

Also, I tried to add ```toFront()``` on line series and it does not work.
