### ISSUE TITLE
Line series in Map chart for JSON configuration

### ISSUE THREAD

**Issue by fredmef** [amcharts/amcharts4#2507]
**Question**

Hi,
Can you give me a JSON configuration's example for integrating line series in a map chart ?
Regards,
Frederic.

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Yes, all code snippets in [this tutorial](https://www.amcharts.com/docs/v4/chart-types/map/map-lines/) have JSON version.

**Comment by fredmef** [comment]
Sorry I wasn't clear...
I want to display a XY chart and a MAP chart in the same chart with JSON like in the following [demo](https://www.amcharts.com/demos/map-line-chart-gauge/).

**Comment by martynasma** [comment]
Gotcha.

Sorry, don't have a ready-made example for that.

**Comment by fredmef** [comment]
Do you know when an example will be ready for that ?
I really need it...
Thanks

**Comment by martynasma** [comment]
There are no plans to create one. Sorry.
