### ISSUE TITLE
addData with removeCount parameter greater than 0.

### ISSUE THREAD

**Issue by ffamar** [amcharts/amcharts4#2508]
Hi,
I have a problem with the type gantt chart  when I use addData and I set the removeCount parameter greater than 0.
Many errors appear in the console like this:
**Error: <g> attribute transform: Trailing garbage, "... anslate (771.087, Infinity)".**
and the chart breaks.

I have prepared an example showing the problem
[CodePen Example](https://codepen.io/ffamar/pen/ZEbNvJQ?editors=1111)

Version of amCharts used: Latest (4.9.23).

Thanks in advance.
Fabio.

**Comment by amcharts** [comment]
I am afraid removing data with Gantt chart will not work properly, because series has a different number of data items comparing to categoryAxis. I will see if I can solve this, but don't ant to promise anything. Meanwhile I recommend changing whole data.

**Comment by ffamar** [comment]
> I am afraid removing data with Gantt chart will not work properly, because series has a different number of data items comparing to categoryAxis. I will see if I can solve this, but don't ant to promise anything. Meanwhile I recommend changing whole data.

My problem is to limit the number of information present in the chart in the time for safeguard chart performance.  Any advice for me?

**Comment by martynasma** [comment]
Quick follow up. I'm afraid we won't be making any changes on how `addData()` works on a Gantt chart. Sorry.

Please consider replacing the whole `chart.data` on each request, as suggested before.
