### ISSUE TITLE
Animation.setProgress when you use setProgress only on series, somehow works transition of opacity in other places

### ISSUE THREAD

**Issue by wj42ftns** [amcharts/amcharts4#2510]
Hello!

I have a problem with Animation.setProgress
interactive demo: https://codepen.io/wj42ftns/pen/KKdLerX?editors=0010

https://youtu.be/UBhz2VHbLkQ when you use setProgress only on series, somehow works transition of opacity in other places - I am not sure that it should works like this, how to escape this behavior and show them immediately with opacity 1 if progress > 0?

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
