### ISSUE TITLE
Animation.setProgress when you hide chart with or without animation setProgress never works

### ISSUE THREAD

**Issue by wj42ftns** [amcharts/amcharts4#2512]
Hello!

I have a problem with Animation.setProgress
interactive demo: https://codepen.io/wj42ftns/pen/KKdLerX?editors=0010

https://youtu.be/K4pjsaxF93s when you hide chart with or without animation setProgress never works.
https://github.com/amcharts/amcharts4/issues/2509 - here in demo you can see that with show animation it works.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
