### ISSUE TITLE
USA county level map (usaCountiesLow.js) performance

### ISSUE THREAD

**Issue by N-Jaro** [amcharts/amcharts4#2514]
**Question**
I am implementing a web app for COVID-19 data using drill down fashion. So, start at the world map and then when user click on countries it zoom in and show finer scale such as stated level data. 

The problem is that when I click on the USA, It takes very long time to load and appear on screen. I want to use county level data of the entire US with Albert projection.

Do you have any suggestion of how to improve the loading time and performance of the county level map?

I am using AmCharts the libraries as follows:

    <script src="https://www.amcharts.com/lib/4/core.js"></script>
    <script src="https://www.amcharts.com/lib/4/maps.js"></script>
    <script src="https://www.amcharts.com/lib/4/geodata/worldLow.js"></script>
    <script src="https://www.amcharts.com/lib/4/geodata/data/countries2.js"></script>
    <script src="https://www.amcharts.com/lib/4/geodata/region/usa/usaCountiesLow.js"></script>
    <script src="https://www.amcharts.com/lib/4/geodata/usaLow.js"></script>

    <script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
    <script src="https://www.amcharts.com/lib/4/themes/dark.js"></script>

**Environment (if applicable)**
This is the example:

Even with the initial loading, it is very slow. 
https://codepen.io/9bombs/pen/OJyejPv

**Comment by martynasma** [comment]
There's a lot of data there. I suggest using individual state maps for drill-down to counties. It will be much much faster.
