### ISSUE TITLE
How to create progress bar kind of in charts as show in attachment

### ISSUE THREAD

**Issue by nagabhushant** [amcharts/amcharts4#2518]
**Question**
How to create a chart that shows list of price gainers and price losers as shown in the attached image.

I want to create similar way but not getting proper examples.

**Environment (if applicable)**

- amCharts version : 4
 - Browser and its version : Chrome
![chart](https://user-images.githubusercontent.com/65383847/83248851-5087e780-a1c3-11ea-87f0-daefdedab2de.JPG)

**Comment by zeroin** [comment]
This is a regular bar chart with bullets as labels:
https://www.amcharts.com/demos/sorted-bar-chart/

More info how to hide everything you don't need: https://www.amcharts.com/docs/v4/tutorials/creating-sparkline-charts/

**Comment by nagabhushant** [comment]
Thanks for the info. I tried and its come the way i expected.

I am trying to add click event on the column series and i am not getting the value for category axis value when i clicked column.

series.columns.template.events.on("hit", function (ev) {
        alert("clicked on ", ev.target);
    }, this);

Is there is way to get the text which is displayed on column series as show  below 

![image](https://user-images.githubusercontent.com/65383847/83356877-90e39300-a386-11ea-826c-a5ab4c475da0.png)

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by nagabhushant** [comment]
This is related to this question only. Earlier i asked how to create the chart which was shown in the snapshot. And that i can able to create now but i faced issue in using click event and i couldn't able to get the text. So if you can guide me how to get that text it will be useful.
