### ISSUE TITLE
Bullet not on line with XYChart and vertical CategoryAxis

### ISSUE THREAD

**Issue by bmampaey** [amcharts/amcharts4#2519]
Since I updated the library (I believe the last time I updated was in June last year), charts with vertical CategoryAxis have bullet that are not on the line

![CategoryAxis](https://user-images.githubusercontent.com/3693702/83281847-fd209400-a1d8-11ea-88a3-6f41dc61c83f.png)

The problem does not appear with vertical ValueAxis
![ValueAxis](https://user-images.githubusercontent.com/3693702/83281931-23deca80-a1d9-11ea-87c6-3975da5a3caf.png)

See code pen for both examples
https://codepen.io/Benjamin-Mampaey/pen/xxwvxgB

I have tried with firefox and chromium under linux and both give the same problem

**Comment by martynasma** [comment]
You'll need to set bullet's `locationY` for that.

However, since `Circle` does not have `locationY` since it does not extend `Bullet`, you'll need to use `CircleBullet` instead:

```
bullets: [
  {
    type: "CircleBullet",
    locationY: 1,
    circle: {
      radius: 3
    }
  }
],
```

**Comment by bmampaey** [comment]
Indeed, this works perfectly for CategoryAxis. Note that specifying locationY for ValueAxis didn't seem to work.
https://codepen.io/Benjamin-Mampaey/pen/rNxaado
