### ISSUE TITLE
Zoomcontrol controls moving as I drag the map

### ISSUE THREAD

**Issue by ricardo-afonso** [amcharts/amcharts4#2520]
I do believe this is a bug as I have search through the documentation and didn't find anything related to this. Please let me know if it's not the case:

On a map chart, if the Zoom Control is enabled, thus showing the +/- buttons, having an event `chart.events.on('drag')` causes the zoom control buttons to float around.

Here's an example - Zoom in the map and then pan it around
https://codepen.io/Gryxs/pen/VwvoLed?editors=1010
I would expect the buttons to always be on the bottom right, but instead, they change position.

**Comment by zeroin** [comment]
When you add drag listener to a chart, you make it draggable, and the zoom controls are in the same container. If you want to register end of drag of the map, add event to chart.chartContainer:

`chart.chartContainer.events.on("drag", ondragfunction);`

**Comment by ricardo-afonso** [comment]
I've tried that line on codepen but the zoom controls still move around.

**Comment by zeroin** [comment]
Sorry, It should be `seriesContainer`, not `chartContainer`

**Comment by ricardo-afonso** [comment]
Thanks, I missed that part of the docs, and the zoom control behaviour was unexpected, although I can see how it makes sense.

Issue can be closed
