### ISSUE TITLE
Map not loading on IE 11

### ISSUE THREAD

**Issue by jparasha** [amcharts/amcharts4#2521]
**Map is not loading on IE 11**

I am using version **4.9.13**.
All builds around May 10-15 were working fine.
Post that, all new installs have following error being generated in IE 11

`Syntax error : class TinyQueue {..`

Which I suppose, is due to limited ES6 support in IE.
I believe **polylabel** is one of the dependency which uses **TinyQueue** class.

Since Codepen, is not supported on IE, I am afraid, need to run the [Map-Demo](https://www.amcharts.com/demos/flight-routes-map/ ) Code in local and then test it on IE 11

**Comment by martynasma** [comment]
That particular demo works fine in IE11.

Also 4.9.13 is quite old. Does this happen with current version? 4.9.24.

P.S. CodePen full-window view works in IE, so if you can provide a repro, that would be helpful.

**Comment by jparasha** [comment]
This did happen with latest release.

For now, I have added polylabel as our project dependency and trans-piling it through CRA.
So far, it's working fine and I do not see 'TInyQueue' class in the source-map. 

I will add proper repro for this issue soon.

**Comment by grohart** [comment]
I encountered the same problem with the last version of amcharts4 (4.10.13), the loading of a map failed with a SCRIPT1002 syntax error on IE (including IE11). I use Webpack Encore to compile my sources.

I solved it by adding the import "regenerator-runtime/runtime" on top of my client app and by including the packages 'd3-array', 'd3-geo', 'd3-geo-projection' and 'tinyqueue' in the options of Babel in my webpack.config.js file:

```
Encore
//...
  .configureBabel( function( babelConfig )
  {
    //...
  },
  {
    includeNodeModules: [ 'd3-array', 'd3-geo', 'd3-geo-projection', 'tinyqueue' ]
  }
  )
//...
;
```
