### ISSUE TITLE
The method label.template.radius resets the range.label.radius

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts4#2522]
The cycling Radar Chart has a dateAxis with month ranges. At -57% the week number labels are printed and at 100% the month-range-labels.

The order of the calls are

    dateAxis.renderer.labels.template.radius = am4core.percent(-57);
    for each range: range.label.radius= 10;

If you reverse the order by putting the first line below the range setting loop, the range.label.radius gets reset to -57% also.

see here:
https://codepen.io/wernerdaehn/pen/MWaNPya

I have read the documentation and did not find that this is the desired result.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
