### ISSUE TITLE
Warnings when there are logical inconsistencies

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts4#2523]
When I design charts, it occasionally happens that no data is shown at all. Once the chart is rendered nicely, just has no data at all, the other time not even the axes are properly drawn and my RadarChart has some black specks in the center (multiple text values written over each other) and nothing else.
And sometimes the data is simply wrong, the tooltips show numbers that do no correlate with the database query.

All of these issues are the result of wrong configurations of some sort.
For example I created a DateAxis with min/max for the year 1970 and the data is for year 2020. Of course no data is shown, it is obvious why. But is it obvious without knowing the fact? In this example I did not notice that the dateaxis.min value is a time-in-millis and hence did set it to the wrong value.

Hence I am asking myself if it wouldn't be better to get warnings, or errors even, instead of drawing a chart showing wrong/no data.

- If a series value is outside the axis range, it is not shown. Hence the overall revenue number shown in the chart is not the same as the database reports and you would draw wrong conclusions from the visualization.
- If a series has multiple data points for the same axis, only the first is shown and all others are silently ignored. So when rendering the yearly revenue but the data assigned at chart level has year and month for another series, only the first value is shown, thus the user draws the wrong conclusions from the visualization.
- A category axis with zero categories breaks a chart rendering for sure. Which axis is that?

I am not sure at what level I would add that, maybe just as warning messages in the console, maybe a message array at the chart level also, to have the option to provide feedback to the end user?
But at least some help for the developer to point him at potential issues and unintended side effects.

I know this is a big topic with little return but.....

**Comment by martynasma** [comment]
I hear you.

However, each of these checks would mean adding fuzzy logic. This means excess CPU load, memory, and bloated up code. And it's not just one situation we'd need to check. There are countless of contingencies that might or might not be considered an "error", based on logic of particular implementation.

That's why I think we should not try to think for the implementators of the charts, and let them decide how they want to handle each contingency.

Hope that sounds reasonable.

**Comment by wernerdaehn** [comment]
Pros and Cons.
Either way, just adding the code as such would be a large undertaking.

Just wanted to make you aware  - done - hence you can close the issue, if you like.
