### ISSUE TITLE
Adapter for a fill pattern lost when returning to the default state

### ISSUE THREAD

**Issue by Tamas-Fuci** [amcharts/amcharts4#2524]
Hello,

I have a chart with several column series, and we want to highlight the ones whose legend is hovered, and gray out the rest. This worked with changing to a new dimmed state based on the demos.
![image](https://user-images.githubusercontent.com/48349211/83353703-1c482e80-a35d-11ea-94fc-5ba80929ac7a.png)
The problem is we have an adapter to apply a fill pattern only on some specific columns based on an external value, and this is lost when reapplying the default state.
![image](https://user-images.githubusercontent.com/48349211/83353825-b9a36280-a35d-11ea-85a1-a74dd082de27.png)

I tried adding it to the default state explicitly but couldn't figure it out.
Here's a pen with this setup:
https://codepen.io/tfuci/pen/BaoXMrX?editors=0010

Any help is appreciated

**Comment by zeroin** [comment]
Things get complicated with states and patterns, and it's quite difficult to explain. I tried and this is the best solution I could find: 
https://codepen.io/team/amcharts/pen/699f1dc3a349c0f7f3f5b0d2221ba98e?editors=0010

**Comment by Tamas-Fuci** [comment]
Thanks for the help!
That works, however our datasets are large and this comes with quite a performance hit. Might need to drop the pattern then in favor of something else.
