### ISSUE TITLE
Tooltip Re-draw

### ISSUE THREAD

**Issue by PartyZan4Life** [amcharts/amcharts4#2525]
Hi dear community!

Can you please help me to understand how and why?

The issue is that when I try to display tooltip with the help of "serie.showTooltipAtDataItem(closest);" for many series tooltips often overlap on each other.

Here is code for example (attached):  [clean.zip](https://github.com/amcharts/amcharts4/files/4708101/clean.zip)

I had tried to make same zIndex for all Tooltips and all Series. And many other tries, but still nothing.

How to synchronize all Tooltips and make them shown separate from each other? It will be great if the tail of Tooltip container will still point to the origin place.

As for example here:
https://www.amcharts.com/demos/multiple-value-axes/
https://www.amcharts.com/demos/multiple-date-axes/

Best regards, Oleh!

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
