### ISSUE TITLE
propertyFields and tensionX/Y problem in LineSeries

### ISSUE THREAD

**Issue by sisao** [amcharts/amcharts4#2526]
Hi,
when using propertyFields and tensionX/Y together in a chart with LineSeries there is a problem (tension value seems to be 1) that occurs if propertyFields value changes in at least two consecutive data points.

[https://codepen.io/sisao/pen/xxZKZjZ](https://codepen.io/sisao/pen/xxZKZjZ)

Is this a know behavior or a bug?

**Comment by martynasma** [comment]
Well, it's not a bug but rather byproduct of using the two together.

The smoothed curve algorithm works by bending the path around multiple points.

Now, when you are using `propertyFields` to color specific section of the line, it creates a separate path for each separately-colored segment. If that segment encompasses only two points, the smoothing algorithm does not have anything to work with, hence the straight line.

Hope that makes sense.

If you still need smoothed lines and colored segments, I suggest you check out axis ranges instead:

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Using_with_series

**Comment by sisao** [comment]
Thx for clarification 😊
