### ISSUE TITLE
Cannot get zoom buttons to work

### ISSUE THREAD

**Issue by varenyagrawal** [amcharts/amcharts4#2527]
Hi,

I have written the below function to render a chart on my website. Everything works fine and the chart renders normally. However, the code to zoom into the chart using the zoomToDates function isn't working.

The part where I am binding a listener to the click even on button seems to be having some issue according to me as 

var max = dateAxis.groupMax["day1"];

doesn't get a proper value and the console shows that it's undefined. 

Can someone please help with this?

Thanks!

function buildAmPriceChart(dataArray, chart, symbol) {

  // the following line makes value axes to be arranged vertically.
    chart.leftAxesContainer.layout = "vertical";

    chart.paddingRight = 20;

    chart.dateFormatter.inputDateFormat = "yyyy-MM-dd";

    var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
    dateAxis.renderer.grid.template.location = 0;
    dateAxis.renderer.minGridDistance = 60;

    dateAxis.renderer.grid.template.location = 0;
    dateAxis.renderer.ticks.template.length = 8;
    dateAxis.renderer.ticks.template.strokeOpacity = 0.1;
    dateAxis.renderer.grid.template.disabled = true;
    dateAxis.renderer.ticks.template.disabled = false;
    dateAxis.renderer.ticks.template.strokeOpacity = 0.2;
    dateAxis.renderer.minLabelPosition = 0.01;
    dateAxis.renderer.maxLabelPosition = 0.99;
    dateAxis.keepSelection = true;
    dateAxis.minHeight = 30;
    //dateAxis.groupData = true;
    dateAxis.minZoomCount = 5;

    // For the Price Y Axis
    var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
    valueAxis.title.text = "Price";
    //valueAxis.logarithmic = true;
    valueAxis.tooltip.disabled = true;
    valueAxis.zIndex = 1;
    valueAxis.renderer.baseGrid.disabled = true;
    // height of axis
    valueAxis.height = am4core.percent(65);

    valueAxis.renderer.gridContainer.background.fill = am4core.color("#000000");
    valueAxis.renderer.gridContainer.background.fillOpacity = 0.03;
    valueAxis.renderer.inside = true;
    valueAxis.renderer.labels.template.verticalCenter = "bottom";
    valueAxis.renderer.labels.template.padding(2, 2, 2, 2);

    //valueAxis.renderer.maxLabelPosition = 0.95;
    valueAxis.renderer.fontSize = "0.8em"

    // The Price Series

    var series1 = chart.series.push(new am4charts.LineSeries());

    series1.name = symbol;
    series1.dataFields.dateX = "date";
    series1.dataFields.valueY = "close";
    series1.tooltipText = "Price: [bold]{valueY.value}[/]";
    series1.yAxis = valueAxis;

    series1.data = dataArray;

    // The volume axis

    var valueAxis2 = chart.yAxes.push(new am4charts.ValueAxis());
    valueAxis2.tooltip.disabled = true;
    // height of axis
    valueAxis2.height = am4core.percent(30);
    valueAxis2.zIndex = 3
    // this makes gap between panels
    valueAxis2.marginTop = 30;
    valueAxis2.renderer.baseGrid.disabled = true;
    valueAxis2.renderer.inside = true;
    valueAxis2.renderer.labels.template.verticalCenter = "bottom";
    valueAxis2.renderer.labels.template.padding(2, 2, 2, 2);
    valueAxis2.renderer.maxLabelPosition = 0.95;
    valueAxis2.renderer.fontSize = "0.8em"
    valueAxis2.renderer.gridContainer.background.fill = am4core.color("#000000");
    valueAxis2.renderer.gridContainer.background.fillOpacity = 0.05;

    var series2 = chart.series.push(new am4charts.ColumnSeries());
    series2.dataFields.dateX = "date";
    series2.clustered = false;
    series2.dataFields.valueY = "volume";
    series2.yAxis = valueAxis2;
    series2.tooltipText = "Volume: {valueY.value}";
    series2.name = "Volume - " + symbol;
    // volume should be summed
    //series2.defaultState.transitionDuration = 0;

    series2.data = dataArray;

    chart.cursor = new am4charts.XYCursor();

    //var scrollbarX = new am4charts.XYChartScrollbar();

    var scrollbarX = new am4core.Scrollbar();

    // chart.scrollbarX = new am4core.Scrollbar();
     scrollbarX.marginBottom = 25;
     chart.scrollbarX = scrollbarX;
    // scrollbarX.scrollbarChart.xAxes.getIndex(0).minHeight = undefined;

    // Legend
    chart.legend = new am4charts.Legend();
    //chart.legend.position = "top";

    /* Create a separate container to put legend in */
    // var legendContainer = am4core.create("priceChartLegend", am4core.Container);
    // legendContainer.width = am4core.percent(100);
    // legendContainer.height = am4core.percent(100);
    // chart.legend.parent = legendContainer;

    // document.getElementById("b1m").addEventListener("click", function() {
    //
    //     window.alert("Clicked");
    //
    //     var max = dateAxis.groupMax["day1"];
    //     var date = new Date(max);
    //     am4core.time.add(date, "month", -1);
    //     zoomToDates(date);
    //   });

      document.getElementById("b1m").addEventListener("click", function() {

        window.alert("Clicked");

            var max = dateAxis.groupMax["day1"];

            console.log(max);

            var date = new Date(max);

            console.log(date);

            am4core.time.add(date, "year", -1);
            zoomToDates(date);
          });

      function zoomToDates(date) {
        var min = dateAxis.groupMin["day1"];
        var max = dateAxis.groupMax["day1"];
        dateAxis.keepSelection = true;
        //dateAxis.start = (date.getTime() - min)/(max - min);
        //dateAxis.end = 1;

        dateAxis.zoom({start:(date.getTime() - min)/(max - min), end:1});
      }

}

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).

**Comment by varenyagrawal** [comment]
Can you please at least tell me how to understand the groupMax value so that at least that part works. Is there a prerequisite in the dates data that it requires to work?

**Comment by PartyZan4Life** [comment]
Hi dear user.

https://www.amcharts.com/docs/v4/reference/chart/#Methods

zoom() and zoomToIndexes() method may be will help you.

Also try to watch this link:
https://www.amcharts.com/docs/v4/tutorials/configuring-the-zoom-out-button/

Also you can try to search:
https://www.amcharts.com/docs/v4/?s=zoom+button

**Comment by PartyZan4Life** [comment]
Ohhh, I forget.

valueAxis.start = valueAxis.valueToPosition(start);
	valueAxis.end = 1;

This is how I make zoom. The other didn't work.
