### ISSUE TITLE
createSeriesRange creates to many StepLineSeriesSegment

### ISSUE THREAD

**Issue by PartyZan4Life** [amcharts/amcharts4#2528]
[multiple-axes-date-based-chart.zip](https://github.com/amcharts/amcharts4/files/4712032/multiple-axes-date-based-chart.zip)

Hi dear community!

I guess this is a bug, but, may be I do something wrong.

I try to make many AxisRanges like this "dateAxis.createSeriesRange(BBoxSeries);"

And then I try to see what "BBoxSeries" is after all operations on it. When I do not make any AxisRange my "BBoxSeries.segments.values.length" is 86. But when I add 63 AxisRanges then "BBoxSeries.segments.values.length" is 86 * 63 = 5418.

I thought adding a AxisRange will retype "BBoxSeries.segments" but not add a copy each time.

As I guess after my manipulations am4core tries to draw 5418 segments, that's why chart loads for ~5.4sec. But if I do not add AxisRanges it loads for ~1.3sec.

My example is working but is very dirty, sorry for it. If you will have some questions please ask them, I will come back from time to time.

Best regards, Oleh.

UPD. My browser is Chrome 83.

**Comment by martynasma** [comment]
I'm sorry, but we can't debug your application located in ZIP.

If you could make a reduced case setup on a CodePen, with only code required to demonstrate the issue, we'd be happy to take a look.

**Comment by PartyZan4Life** [comment]
https://codepen.io/PartyZan/pen/vYLYRYz

If we choose "serie.connect = false" option then we have a lot of segments in our "serie" as you can see from "console.log(testSeries.segments.values.length);" on line 31.

If we then will make a range for this "serie" (line 34) we will catch a twice more segments (line 32 -> testSeries.segments.values.length). And all of this segments will draw again (and this will take a time).

In my case there is 86 segments on line 31 and I need to draw about 60-70 ranges. That's why it takes much time, because creates 60-70 "chart.plotContainer" clones and 60-70 * 86 = 5160+ segments.

Also you can see that "chart.plotContainer" (line 11) after Range add make it's clone and we can see it extra "stroke".

http://skrinshoter.ru/s/030620/kpNCzPXy?a

On the screenshot you can see example of what result I need and why I need to make so much Ranges. My StepLine colored different from time to time. I try to achieve the same result with the help of LinearGradient (and positions) but it don't want to work correctly at all (also if you try to zoom). May be you know some quick solution...

P.S. CodePen crushes because of "console.log()" that's why this lines are commented.

**Comment by martynasma** [comment]
Gotcha. In your case I would suggest not using ranges, as you correctly pointed out that each series range creates a separate copy of the series. When you have a lot of segments you end up with a multitude of elements.

Instead, I suggest you use data to indicate where color should change. You can tie `stroke` to data using `propertyFields`.

More details here:
https://www.amcharts.com/docs/v4/concepts/data/#Property_fields

**Comment by PartyZan4Life** [comment]
Yeah, I also think that I need just to cut my StepLine correctly and just then change stroke color for each segment.

You help me a lot, thanks!
