### ISSUE TITLE
toGlobalPosition  didn't work fine?

### ISSUE THREAD

**Issue by PartyZan4Life** [amcharts/amcharts4#2529]
Hi dear community!

I try to zoom my chart and then make this:

`let cursor = chart.cursor;
let cursorPosition = cursor.xPosition;
let realPosition = dateAxis.toGlobalPosition(cursorPosition);`

"realPosition"  becomes 6 and higher. I don't think this is fine or I miss something?

This works for me correctly:
`let axisStart = cursor.xAxis.start;
 let realPosition = axisStart + cursorPosition * (cursor.xAxis.end - axisStart);`

"realPosition" always point to correct position and I can use it for "dateAxis.positionToValue(realPosition);" for example.

**Comment by zeroin** [comment]
If you want to know the real position on the axis, you should do:

`realPosition = categoryAxis.toAxisPosition(cursorPosition)`

**Comment by PartyZan4Life** [comment]
This is exatcly what I need. Thanks a lot!
