### ISSUE TITLE
Add third yAxes to the chart, which has a height, equal to the first yAxes

### ISSUE THREAD

**Issue by mrmime95** [amcharts/amcharts4#2532]
How could I add third yAxes to the chart, which has a height equal to the first yAxes?
I want something like this:
![Screenshot 2020-06-02 at 16 02 42](https://user-images.githubusercontent.com/18379137/83525315-7aa41700-a4ed-11ea-8c4d-00f26630b2ef.png)
(screenshot form: https://www.amcharts.com/demos/vertically-stacked-axes-chart/)

My problem is on the following link: https://codepen.io/mrmime95/pen/NWqVdMd
![Screenshot 2020-06-02 at 16 01 37](https://user-images.githubusercontent.com/18379137/83525691-00c05d80-a4ee-11ea-928b-20a51193c969.png)

**Comment by martynasma** [comment]
The simplest workaround would be to add a fourth dummy axis on the right (no series attached to it), so that the space is divided equally between them.

**Comment by martynasma** [comment]
Come to think of it, you can add any empty container there for the same effect:

```
var valueAxis4 = chart.rightAxesContainer.createChild(am4core.Container)
valueAxis4.height = am4core.percent(100);
```

**Comment by mrmime95** [comment]
Cool, it works, thank you :)
