### ISSUE TITLE
Amchart : Tooltip doesn't appear when cursor is hovering serie

### ISSUE THREAD

**Issue by AMINEAALI** [amcharts/amcharts4#2533]

**Comment by martynasma** [comment]
Try disabling all interactivity on the label:

```
serieLabel.interactionsEnabled = false;
```

**Comment by AMINEAALI** [comment]
> Try disabling all interactivity on the label:
> 
> ```
> serieLabel.interactionsEnabled = false;
> ```

Thank you a lot that solved my problem.
