### ISSUE TITLE
Get Text on the column series on mouse click

### ISSUE THREAD

**Issue by nagabhushant** [amcharts/amcharts4#2535]
**Question**

I am trying to add click event on the column series and i am not getting the value for category axis value when i clicked column.

series.columns.template.events.on("hit", function (ev) {
alert("clicked on ", ev.target);
}, this);

Is there is way to get the text which is displayed on column series as show below

![](https://user-images.githubusercontent.com/65383847/83356877-90e39300-a386-11ea-826c-a5ab4c475da0.png)

**Environment (if applicable)**
Environment (if applicable)

amCharts version : 4
Browser and its version : Chrome

**Comment by martynasma** [comment]
The clicked column data item should contain all the information you need.

Try exploring the `ev.target.dataItem` object:

```
series.columns.template.events.on("hit", function (ev) {
  console.log(ev.target.dataItem);
}, this);
```

**Comment by nagabhushant** [comment]
Thanks for your reply. It works. 

I don't see help document explains what all object contains in ev.target.

**Comment by martynasma** [comment]
The `ev.target` holds the object that clock occurred on. In this case it is a column object.

**Comment by nagabhushant** [comment]
ok thank you

**Comment by pratikgirikonvergedotai** [comment]
is mouseHover event supported ? . I only saw hit event in docs
