### ISSUE TITLE
Changing color of MapChart bug

### ISSUE THREAD

**Issue by AMINEAALI** [amcharts/amcharts4#2538]
I have a MapChart of the world with no color (grey by default for countries and white for the oceans):

![grey](https://user-images.githubusercontent.com/44714633/83656418-ce7f3080-a5bf-11ea-9e17-d0eab9af257c.png)

This is my code:

```
var container = am4core.create("concatChart", am4core.Container);
container.width = am4core.percent(100);
container.height = am4core.percent(100);

this.mapChart = container.createChild(am4maps.MapChart);
this.mapChart.geodata = am4geodata_continentsHigh;
this.mapChart.projection = new am4maps.projections.Miller();

var polygonSeries = this.mapChart.series.push(new am4maps.MapPolygonSeries());
polygonSeries.useGeodata = true;
```

I added some colors by adding these lines to my code :

```
this.mapChart.backgroundSeries.mapPolygons.template.polygon.fill = am4core.color("#91c2dc");
this.mapChart.backgroundSeries.mapPolygons.template.polygon.fillOpacity = 1;

polygonSeries.mapPolygons.template.fill = am4core.color("#FFFFFF");
polygonSeries.mapPolygons.template.strokeOpacity = 0;
```

but it is actually bugged, it seems like the world map is cut:

![cutted](https://user-images.githubusercontent.com/44714633/83656567-01c1bf80-a5c0-11ea-8712-8388a1661131.png)

**Comment by martynasma** [comment]
Could you post a reproducible live copy of your map/chart on CodePen/jsFiddle where we can test?

**Comment by AMINEAALI** [comment]
> Could you post a reproducible live copy of your map/chart on CodePen/jsFiddle where we can test?

https://stackblitz.com/edit/am-charts-emkfjj?file=src/app/app.component.ts

I added more informations

**Comment by martynasma** [comment]
Thank you.

Though, I'm trying to understand why are you using background series? If you just want to add blue background to the map you can do so by:

```
this.mapChart.background.fill = am4core.color("#91c2dc");
this.mapChart.background.fillOpacity = 1;
```

**Comment by AMINEAALI** [comment]
> Thank you.
> 
> Though, I'm trying to understand why are you using background series? If you just want to add blue background to the map you can do so by:
> 
> ```
> this.mapChart.background.fill = am4core.color("#91c2dc");
> this.mapChart.background.fillOpacity = 1;
> ```

Thank you a lot, it was a mistake. Tho I don't understand why it worked when the background were white and countries blue. Now if you can see there is a visible border at the very left of the map, do you know how can I fix this ?

**Comment by martynasma** [comment]
This is happening because of the retina screens.

Try this setting:

```
this.mapChart.background.pixelPerfect = true;
```

Stroke is not enabled by default on a background.

**Comment by AMINEAALI** [comment]
> This is happening because of the retina screens.
> 
> Try this setting:
> 
> ```
> this.mapChart.background.pixelPerfect = true;
> ```
> 
> Stroke is not enabled by default on a background.

Well I don't see any enable configuration in this code : https://codepen.io/team/amcharts/pen/KoGbaO

I tried this `this.mapChart.background.pixelPerfect = true;` but no difference.

**Comment by martynasma** [comment]
Did you try it on your StackBlitz setup? It did help me when I added that line there.

**Comment by martynasma** [comment]
I'm not seeing the blue outline on the right anymore. Or was it about something else?

![image](https://user-images.githubusercontent.com/1458520/83777662-5a618d00-a692-11ea-948e-ac7398ad9a8d.png)

**Comment by martynasma** [comment]
I'm not sure if I follow. Can you post a screenshot of the issue?

**Comment by martynasma** [comment]
Those white lines are outlines of the countries. And they are in both versions, except white outline around a white polygons makes it effectively seem like it's not there.

If you want to get rid of country borders on the gray map, you should set set polygon `stroke` to the same color as `fill`:

```
polygonSeries.mapPolygons.template.fill = am4core.color("#91c2dc");
polygonSeries.mapPolygons.template.stroke = am4core.color("#91c2dc");
```

**Comment by AMINEAALI** [comment]
> Those white lines are outlines of the countries. And they are in both versions, except white outline around a white polygons makes it effectively seem like it's not there.
> 
> If you want to get rid of country borders on the gray map, you should set set polygon `stroke` to the same color as `fill`:
> 
> ```
> polygonSeries.mapPolygons.template.fill = am4core.color("#91c2dc");
> polygonSeries.mapPolygons.template.stroke = am4core.color("#91c2dc");
> ```

I changed the color of countries with red, and I still don't see any outlines of the countries, do you know why ?

**Comment by martynasma** [comment]
I added this to your stackblitz chart:

```
polygonSeries.mapPolygons.template.stroke = am4core.color("#ff0000");
```

And got this:

![image](https://user-images.githubusercontent.com/1458520/83875752-5724da80-a740-11ea-83b4-41d2f470ad87.png)

You're probably doing something wrong :)

**Comment by AMINEAALI** [comment]
> I added this to your stackblitz chart:
> 
> ```
> polygonSeries.mapPolygons.template.stroke = am4core.color("#ff0000");
> ```
> 
> And got this:
> 
> ![image](https://user-images.githubusercontent.com/1458520/83875752-5724da80-a740-11ea-83b4-41d2f470ad87.png)
> 
> You're probably doing something wrong :)

I have the exact same result, and you can see that this is not like the gray map. Where are the outlines of countries ?

**Comment by martynasma** [comment]
There are no countries on continents map. If you need individual countries, use `world*` map, not `continents*`.
