### ISSUE TITLE
PieChart: Min size for slices 

### ISSUE THREAD

**Issue by JacobDeuchert** [amcharts/amcharts4#2541]
Hi, 
I created a Pie chart with 3 Slices and need to display them. The problem is, that when one of the slices has a very small percentage value like 0.5%, it is very small or doesn't even show up. Is there any possible solution to assign a min size to slices or change the displayed size with an adapter without changing the data? 
![image](https://user-images.githubusercontent.com/43518397/83721857-3b381080-a63c-11ea-8d86-e99e10fc615e.png)

Thanks in advance!

**Comment by zeroin** [comment]
No, it doesn't. It would not make sense from dataviz side. You can change values in data and have some "displayValue" field in your data and show the {displayData} in label/tooltip, but that again, would be wrong.

**Comment by JacobDeuchert** [comment]
Yes i thought of something like that and will do it since there isn't a direct solution. In my case it doesn't really matter if the relation between the slices is a bit off. The only thing matters is that you see every slice and every value with a label.

**Thanks for the respons** 
and sorry for asking since it doesn't make sense in a normal pie chart.
