### ISSUE TITLE
Export multiple amcharts images to server

### ISSUE THREAD

**Issue by prk87** [amcharts/amcharts4#2542]
may i know how i can do export of multiple amcharts images in a page to the server.

**Comment by martynasma** [comment]
You may find this tutorial handy:
https://www.amcharts.com/docs/v4/tutorials/automating-report-generation-using-selenium-webdriver/

**Comment by prk87** [comment]
Our Requirement is to export amcharts as images in multiple tabs in to PPT(Using Custom Code) on user button click.

While doing below export on click of a button some images are generating as a blank image, may be rendering issue as images are in different tabs.

Kindly suggest any other option to perform above export functionality.

Note:

We have a workaround as of now, if we manually visit all the tabs with amcharts rendered we are getting more images but if we directly click export button without visiting all the tabs then we are getting more blank images while using below code. 

Code Snippet:

Summarychart.exporting.getImage("jpg").then(function (imgData) {
            ChartImagesJson["InvestmentStatus"] = imgData;
        });

**Comment by martynasma** [comment]
I'm sorry, but we don't have any tutorials or examples for PPT.
