### ISSUE TITLE
Add outer circle to non-link nodes in force directed tree

### ISSUE THREAD

**Issue by StevenVerbiest** [amcharts/amcharts4#2543]
I'm trying to apply link styling to regular nodes, but I can't seem to find a solution. The use case is quite specific, so I'm not going to elaborate on it.

The problem is that nodes without children have `display="none"` and the `circle` node has no `r` attribute.

The html of an outer the circle of a link node is:
```
<g stroke-width="2" fill="#ffffff" transform="translate(0,0) scale(1.1)"><circle r="43"></circle></g>
```
That of a regular node is:
```
<g stroke-width="2" fill="#ffffff" display="none" transform="translate(0,0) scale(1.1)"><circle></circle></g>
```

What I would want to do is to apply styling to (some) nodes so that they appear to have children. 
I tried `series.nodes.template.outerCircle.disabled = false`, but this only works in reverse (setting disabled to true, removes the outer circle for links).

I also tried `series.nodes.template.outerCircle.config` but I can't seem to find the right settings.

Is what I am trying to do even possible or am I overlooking some options?

**Comment by martynasma** [comment]
ForceDirectedTree logic overrides your `outerCircle.disabled` setting based on whether node has children or not.

Try adapter instead:

```
series.nodes.template.outerCircle.adapter.add("disabled", function(disabled, target) {
  return false;
});
```

**Comment by StevenVerbiest** [comment]
I'm integrating the graph in a React project and the graph component keeps re-rendering when I add that code. 
I tried setting up a codesandbox with an example, but I keep getting `Object prototype may only be an Object or null: undefined` when I import amCharts via ```import * as am4core from "@amcharts/amcharts4/core"```

My component looks something like this
```
import React, { Component } from "react";
import * as am4core from "@amcharts/amcharts4/core";
import * as am4plugins_forceDirected from "@amcharts/amcharts4/plugins/forceDirected";
import data from "./data";

export class Graph extends Component {
  componentDidMount() {
    const chart = am4core.create(
      "chartdiv",
      am4plugins_forceDirected.ForceDirectedTree
    );
    chart.data = data;

    const series = chart.series.push(
      new am4plugins_forceDirected.ForceDirectedSeries()
    );

    // Data
    series.dataFields.value = "value";
    series.dataFields.name = "name";
    series.dataFields.children = "children";
    series.dataFields.fixed = "fixed";
    series.dataFields.color = "color";
    series.dataFields.id = "id";
    series.dataFields.party_type = "party_type";

    // Label style
    series.nodes.template.label.fill = am4core.color("#212121");
    series.nodes.template.label.fontSize = "14px";
    series.nodes.template.label.text = "[bold]{name}[/]";
    series.nodes.template.label.draggable = false;
    
    // INFINITE RERENDER WHEN THIS IS ADDED
    series.nodes.template.outerCircle.adapter.add(
      "disabled",
      (disabled, target) => {
        return false;
      }
    );

    this.chart = chart;
  }

  componentWillUnmount() {
    if (this.chart) {
      this.chart.dispose();
    }
  }

  render() {
    return <div id="chartdiv" style={{ width: "100%", height: "500px" }} />;
  }
}
```
