### ISSUE TITLE
DateTime bullets alignment

### ISSUE THREAD

**Issue by iBuggedNL** [amcharts/amcharts4#2544]
Hi there!

I want to make a chart with datetime values and "value" values and have the following code:

```
// Create chart
var chart = am4core.create("chartdiv", am4charts.XYChart);

// Load JSON data
chart.dataSource.url = "testJoep.json";

// Create X axis
var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
dateAxis.dataFields.category = "time";
dateAxis.dateFormatter.inputDateFormat = "yyyy-MM-dd HH:mm";
dateAxis.baseInterval = { timeUnit: "minute", count: 15};

// Create Y axis
var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

// Create series
var series1 = chart.series.push(new am4charts.LineSeries());
series1.dataFields.valueY = "ingepakt";
series1.dataFields.dateX = "time";
series1.name = "Ingepakt";
series1.bullets.push(new am4charts.CircleBullet());

// Add legend
chart.legend = new am4charts.Legend();
```

The JSON I load is the following:

```
[
    {
        "time": "2020-06-04 10:00",
        "ingepakt": 50
    },
    {
        "time": "2020-06-04 10:15",
        "ingepakt": 55
    },
    {
        "time": "2020-06-04 10:30",
        "ingepakt": 68
    },
    {
        "time": "2020-06-04 10:45",
        "ingepakt": 77
    },
    {
        "time": "2020-06-04 11:00",
        "ingepakt": 83
    },
    {
        "time": "2020-06-04 11:15",
        "ingepakt": 99
    },
    {
        "time": "2020-06-04 11:30",
        "ingepakt": 110
    },
    {
        "time": "2020-06-04 11:45",
        "ingepakt": 119
    },
    {
        "time": "2020-06-04 12:00",
        "ingepakt": 140
    }
]
```

The chart is made and the line is drawn, but the bullets are not directly above the time its value represents, as seen in this screenshot: https://prnt.sc/stl1tl.

The bullets / line is "half a cell" to the right of where it should be. I have used some options like `dateAxis.startLocation` and `dateAxis.renderer.grid.template.location`, but not with the result I wanted.

Which (seemingly easy) option or setting am I missing?

**Comment by martynasma** [comment]
You have two options for aligning bullets with the date/grid:

1) Move grid and labels to the middle:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_location_

2) Move bullets to the start of the cell.

https://www.amcharts.com/docs/v4/concepts/series/#Data_item_locations

**Comment by iBuggedNL** [comment]
Thanks for the help! Option 2 works like a charm for me!
