### ISSUE TITLE
After pointing to the legend of any line, the line almost always remains bold.

### ISSUE THREAD

**Issue by NemoDima** [amcharts/amcharts4#2546]
**Bug description**
After pointing any line to the legend, the line almost always remains bold and does not return to normal thickness after moving the cursor from its legend.

CodePen https://codepen.io/vovaltus/pen/bGENNMo?editors=0010

**Environment (if applicable)**
Amcharts 4.9.24
Angular 5
TypeScript 2.9

**Comment by zeroin** [comment]
I modified this demo to show how it should be done:
https://www.amcharts.com/demos/reversed-value-axis/

It is not working in your case because the structure of the line series is not straightforward, it contains more sprites.

**Comment by NemoDima** [comment]
@zeroin thank you for the answer.
We prepared one more example that very close to our problem: https://codepen.io/vovaltus/pen/bGENNMo
Hope it helps localize and fix the problem.
Please check it, too.
Thanks!

**Comment by NemoDima** [comment]
@zeroin If it's possible, please check our last example.
Best wishes.

**Comment by zeroin** [comment]
The key thing is to set strokeWidth on a segment:

```
let hs2 = series2.segments.template.states.create("hover")
hs2.properties.strokeWidth = 5;
series2.segments.template.strokeWidth = 1; // the default value

```

as by default, it does not have any value.

**Comment by NemoDima** [comment]
@zeroin Thanks a lot for the suggestion, it helped.
And also sorry for the long delay in answering, there was a high load.
Best wishes!
