### ISSUE TITLE
Animate both raw data and color?

### ISSUE THREAD

**Issue by bryceremick** [amcharts/amcharts4#2549]
**Environment**
AmchartsV4, Vue, Typescript

**Context**
Hello, I'm trying to manipulate _existing_ pieseries chart data, and then animate/transition on the size **and** color changes of said data. Currently I can animate the size by calling `chart.invalidateRawData()`, however doing that causes the chart to not update the color.

**Example**

Chart data:
```
chart.data = [
     {
        currentZone: '1',
        size: foo,
        color: '#FFFFFF'
      },
      {
        currentZone: '2',
        size: bar,
        color: '#121212'
      }
]
```

Updating Data: 
```
chart.data[0]['size'] = bar
chart.data[1]['size'] = foo
chart.data[0]['color'] = '#00FF00'

chart.invalidateRawData()
```

Calling `chart.invalidateData()` updates both data and color, but does not animate the changes.

What is the correct way to update the data and then animate both the size **and** color?

**Comment by martynasma** [comment]
I'm afraid there's no built-in way to animate values of the `propertyFields`.

`invalidateRawData()` animates values of the `dataFields`.

You can try the following, though:

```
chart.invalidateRawData();
pieSeries.slices.each(function(slice) {
  slice.fill = slice.fill;
});
```

It might trigger an invalidation of a slice and thus transition to a new color.
