### ISSUE TITLE
Issue with scaling polygon

### ISSUE THREAD

**Issue by avgorobec** [amcharts/amcharts4#2551]
Hi. I am created am4maps.MapChart object and added some polygons to MapImageSeries. For geodata use custom data that exported from https://www.openstreetmap.org. And some objects are disappearing with scaling polygon. The parametrs like seriesHeight, seriesWidth and other are changing a lot.

<img width="208" alt="SeriesParam" src="https://user-images.githubusercontent.com/47418945/83868132-0b1f6900-a733-11ea-92e4-146f8c12fca7.PNG">

Here is an example of one of these polyons.
https://codepen.io/gorobec/pen/mdVyGWy?editors=0010

At the same time that polygon correctly scaling on this site https://mapshaper.org
Thanks in advance!

My Environment
 - amCharts - 4.9.24, Typescript
 - Browser - Chrome 83
 - Framework - React 16.13

**Comment by zeroin** [comment]
Chart expects coordinates to go clockwise, if they are arranged ccw, it treats your coordinates as a hole. So you should `reverse()` your coordinates array in order this to work.

**Comment by avgorobec** [comment]
Еhank you very much, problem solved!
