### ISSUE TITLE
How to detect time of re-draw?

### ISSUE THREAD

**Issue by PartyZan4Life** [amcharts/amcharts4#2552]
Hi dear community!

I try to re-draw my chart using simple replacement of "series.data".

But there is no any event on Chart that hits after re-draw end.

Chart.events.on("ready") hits only on the first time, but not when Chart re-draw. Also I try to use many other events - nothing is what I need.

Did I miss something?

Best regards, Oleh!

**Comment by martynasma** [comment]
If you are replacing `data` on series, you might use series events, e.g. `validated` or `datavalidated`.
