### ISSUE TITLE
Force Directed Tree with inline SVG paths, icon.width/height has no effect

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts4#2554]
When you use SVG paths inline as icons, the width/height information is ignored. With external images it does work. https://codepen.io/team/amcharts/pen/YMGNrR

Example from the docs:
https://codepen.io/team/amcharts/pen/EJgNey

Now modify the width/height to something else. No matter if you specify a number or a percent, no visual change. Doing the same with external svg files, it does work.

    icon.width  = 10;
    icon.height = 10;

If that is a known limitation (and I can see technically why it might) the documentation and example should be updated.

**Comment by martynasma** [comment]
The difference between the two demos is that one uses `Image` and full SVG images which does scale using `width` and `height`.

The other uses `Sprite` with just its `path` set, which is not scaled by Sprite's `width`/`height`.

Knowing dimensions of the source inline SVG paths, you can scale the whole `Sprite` using it's `scale` property, though:

```
icon.scale = 2;
```

**Comment by wernerdaehn** [comment]
Thanks. Mind to update the docs and the sample on your web page? It is kind of weird to set a property that has no effect in a coding sample.

**Comment by martynasma** [comment]
Duly noted and fixed. Thanks!
