### ISSUE TITLE
Force Directed Tree with arrow lines for linkWith

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts4#2555]
I assume this is an enhancement request? I have the requirement for directional links between nodes, so would need to have the option for arrow heads on the lines.
The information as such exists as a linkWith has a start and end point, I just have not found a way to specify the line cap to be an arrow.

Assuming that there is no way I would see multiple options and I can live with all of them

1. Specify the line start/end for a single linkWith entry
1. A series property telling that arrows should be used

For bidirectional relationships:

1. One linkWith entry that has arrows at start and end, thus rendering a single line
1. Item A being linked with Item B via an arrow and item B being linked with Item A with an arrow, rendering two lines effectively. (like in the example below)
1. Two linkWith entries as above but rendered as one line with two arrows.

![image](https://user-images.githubusercontent.com/13607767/83963362-cff17700-a8a5-11ea-9c49-5ea6e02a1159.png)

**Comment by martynasma** [comment]
I'm afraid, we're currently not planning an enhancement like that. Sorry.

**Comment by wernerdaehn** [comment]
Understood. Still wanted to let you know.
