### ISSUE TITLE
No difference in word's size, if appends the next words set.

### ISSUE THREAD

**Issue by GopiAureus** [amcharts/amcharts4#2556]
In my application, I need to show multiple set of words. So I do have next and previous buttons. 
Initial set of words are displaying fine in word cloud. No issues with sizing as well. 
When I am rendering the next set of words by clicking on the next button, I do not see the size difference. And also If I come back to the first set by selecting the previous , again words size is not same. 

series.interpolationDuration  = 100; 
        series.dataFields.word = "tag";
        series.dataFields.value = "weight";
        series.sequencedInterpolation = false;
        series.responsive.enabled = true;
        series.randomness = 0;
        series.minFontSize = am4core.percent(2);
        series.maxFontSize = am4core.percent(20);
        series.nonScalingStroke = true;

Thanks in advance.

-Gopi

**Comment by martynasma** [comment]
What exactly are you doing on "next" button press?

If you could post your chart online somewhere, like CodePen, that would be much easier for us.

**Comment by GopiAureus** [comment]
In the next button press, I am fetching the next set of words from the database and showing in the wordcloud. 
I could not create the chart online for now.

**Comment by martynasma** [comment]
The reason I asked is that we don't have to guess what you are doing. If you want to help us help you, please do provide relevant code, or better yet a working chart that we can use.

I hope that sounds reasonable.
