### ISSUE TITLE
Small slice label shown when pie chart updated by a legend click

### ISSUE THREAD

**Issue by oliverlj** [amcharts/amcharts4#2557]
Hi,

Hi did the tutorial https://www.amcharts.com/docs/v4/tutorials/hiding-small-pie-slices/ for hiding labels.

But when I hide/show a slide with a legend click, the label appeared.

How can I do to keep this label hidden ?

**Comment by martynasma** [comment]
Thanks for the heads up.

We've just rewritten the whole section in that tutorial.

https://www.amcharts.com/docs/v4/tutorials/hiding-small-pie-slices/#Hiding_labels

**Comment by oliverlj** [comment]
Hi, thanks to have updated the tutorial.

I have an animated chart and this do not work.
DataItem could be undefined for visibilityChanged event and percent value is based on value when the animation started.

I have use this code :
```
pieSeries.labels.template.events.on('ready', this.hideSmall);
no visibility changed event.

  hideSmall(ev) {
    if (ev.target.dataItem.values.value.percent < 10) {
      ev.target.disabled = true;
    }
  }
```

**Comment by martynasma** [comment]
In that case you should probably check if dataItem exists, before making any checks.

```
function hideSmall(ev) {
  if (ev.target.dataItem && (ev.target.dataItem.values.value.percent < 5)) {
    ev.target.hide();
  }
  else {
    ev.target.show();
  }
}
```
