### ISSUE TITLE
Setting min and max value of an axis affect grid on change

### ISSUE THREAD

**Issue by IkamThorek** [amcharts/amcharts4#2559]
I have 2 charts built with the same component in parralel. The only difference between the 2 is the fact that I set the min and max values of the Y axis of one of them using the following lines :

```
if (this.minValueOrdonnateAxis !== undefined) {
   this.ordonateAxis.min = this.minValueOrdonnateAxis;
}
if (this.maxValueOrdonnateAxis !== undefined) {
  this.ordonateAxis.max = this.maxValueOrdonnateAxis;
}
```

At first, the graphs are created exactly identical. However, when I update them, even using the same data and the same button, the chart with the min and max fixed loses its Y grid rendering. 

Here are the before and after images :

First chart, I set min to 0, and max to 1, Second chart, I didn't set either min of max..

![image](https://user-images.githubusercontent.com/60658002/84035168-a74ba900-a99b-11ea-86f9-32ab7265c9cc.png)

This is after I changed data then went back to the original data (I did this to show evidence that data isn't the issue here).

![image](https://user-images.githubusercontent.com/60658002/84035228-bc283c80-a99b-11ea-9fad-f0fc7bbaf034.png)

**Comment by IkamThorek** [comment]
Do you have any idea on how to fix that ? Do I need to refresh some rendering when I update my data ?

**Comment by martynasma** [comment]
It shouldn't be that way.

Would you be able to post your chart on CodePen where we could test it and possibly figure out?
