### ISSUE TITLE
When is it safe to use MapChart.zoomToRectangle ?

### ISSUE THREAD

**Issue by bcronje** [amcharts/amcharts4#256]
I'm trying to use `zoomToRectangle` on my MapChart, but found that it causes a range of errors if I call it too soon. It works fine if I call it for example inside a button hit event after the map has been drawn. However, I want to set the zoom dynamically as soon as  my image series has been drawn and the map is ready.  Is there a "rendered" or "drawn" or "ready" event on the map that I can use to safely call `zoomToRectangle` ?

Is seems to work ok if I wrap it inside the imageSeries "transitionended" event, something like this:

```
imageSeries.events.on("transitionended", function(ev){
     this.map.zoomToRectangle(north, east, south, west, 1, true);
}, this);
```

But I couldn't get the above to work on codepen, only on my local machine, so I'm not sure if that is the right approach.

What or when would be the recommended way to dynamically call `zoomToRectangle`?

**Comment by martynasma** [comment]
It should be safe to call when chart's `inited` event kicks in:

```
chart.events.on("inited", function(ev) {
  // do your pre-zooming thing here
});
```

**Comment by bcronje** [comment]
I tried `inited` as you suggested but the zoom ends up in completely the wrong rectangle. If I change to `valueschanged` event then the rectable is correct. I created a codepen [example](https://codepen.io/anon/pen/NLWQeK) for you https://codepen.io/anon/pen/NLWQeK

You'll see that zoom rectangle ends up in the wrong place. If you uncomment line 22 then you see the zoom ends up in the correct place, even though the values to `zoomToRectangle` is exactly the same.

Is this a bug, or am I doing something wrong?

**Comment by martynasma** [comment]
OK, sorry about that. Seems like when `"inited"` kicks in the data is not yet ready from GeoJSON, hence it not working.

Based on this, [`"datavalidated"`](https://www.amcharts.com/docs/v4/reference/mapchart/#datavalidated_event) event seems like perfect candidate for your pre-zoom. I tried it on your pen, and it seems to be working fine.

**Comment by bcronje** [comment]
Ok great, thank you!
