### ISSUE TITLE
Scale values are cutting off on values axis in 3d column chart.

### ISSUE THREAD

**Issue by MuzaffarMahmood** [amcharts/amcharts4#2560]
Scale values are cutting off on values axis in 3D column chart as shown in below image.

![image](https://user-images.githubusercontent.com/18557321/84059311-d54cdf80-a9d3-11ea-96dc-b7babc40e19f.png)

**Comment by martynasma** [comment]
Could you please post your chart on CodePen?

**Comment by MuzaffarMahmood** [comment]
The issue is resolved. I handled it by valueaxis labels dx settings. Thanks you very much @martynasma
