### ISSUE TITLE
Animation using json

### ISSUE THREAD

**Issue by imtrobin** [amcharts/amcharts4#2561]
Hi, I'm trying to do the slice in animation via json, but I notice it only has javascript code.

https://www.amcharts.com/docs/v4/tutorials/creating-pie-series-animations/

From this page. How do I specify the template in JSON, I don't see it in reference?

```
pieSeries.slices.template.showOnInit = true;
pieSeries.slices.template.hiddenState.properties.shiftRadius = 1;
```

**Comment by martynasma** [comment]
The following doc shows how you can modify templates in JSON config:

https://www.amcharts.com/docs/v4/concepts/json-config/#List_templates

Hope this helps.

**Comment by imtrobin** [comment]
ok got it working, thanks.
