### ISSUE TITLE
Is it possible to disable a specific adapter ?

### ISSUE THREAD

**Issue by Scylanth** [amcharts/amcharts4#2562]
Hello,

If several adapters are applied to the same object, is it possible to specifically disable one of them ?

For instance, if I have the two following adapters applied to the text of a label :

valueAxis.renderer.labels.template.adapter.add('text', function(text) {
    return text + labelunit;
});

valueAxis.renderer.labels.template.adapter.add('text', function(text) {
    return text + ' per product';
});

Is it possible to disable specifically the second one ? I found out it was possible to remove them by priority but not disable them.

Best regards,

Scylanth

**Comment by martynasma** [comment]
No, I'm afraid. You can only disable by key, which would disable both "text" adapters :(
