### ISSUE TITLE
interpolationDuration doesn't animate when data changes

### ISSUE THREAD

**Issue by fasidOnGit** [amcharts/amcharts4#2564]
I cannot get the value changes in the XY chart to be animated... We are not using the themed animation but we did follow the [Manual animation](https://www.amcharts.com/docs/v4/concepts/animations/#Manual_animation_settings) guide. But, still we are having a hard time getting it to work...

 Here is the [codepen](https://codepen.io/fasid/pen/yLeebRq?editable=true%3Dhttps%3A%2F%2Fcodepen.io%2Fanon%2Fembed%2FWyNVpQ%3Fheight%3D400%26theme-id%3Ddark%26slug-hash%3DWyNVpQ%26default-tab%3Dresult%26animations%3Drun%26editable%3D%26embed-version%3D2%26preview%3Dtrue%26user%3Danon%26name%3Dcp_embed_4&__cf_chl_jschl_tk__=24077f2d0e78b645b02771bf0ad8be15a7c60cc9-1591776938-0-AXrKbAJt_ROmVGdWYhk6xKzLdntAW6PdI4sAzjsAgG09OanQPbLsfNUxw77uoTBVOwM5-ueQ8zPPRK-ufyrV-N7tq202E9gkI9iY5vWtI8eTFkVlgk1g40-oy5tk_4fMSWL2PxgO1AYd2zcLQ_jsLGe9_-IVboNCZu1okDbDFN-EXEqVcSsl86wg-4u2yNyK41tCe4NgqEnud7NHc5xTbPAFJci0_ed6pnuSRgOApDSUxQ1bz6Emyy0MbT6ojKi8gKBZ-YP2Iy0ZT6bokCZHFhppxweGME48lFJwoa2mR_mX_lHE8UinvMOa6jSj5tmcslTGzG2RJ0elNSbjU9NyvF20pvNEzn4A6aiqIiFt-SQ-6hGYLBxPprHWPa05sYLXwQ6y9Co4DSW9ubUP7p0M-1IcnVqWyrbRuz2xs3uXJg0yMHYZKK8SLoMsr33IUQlGM2ajj3NDC2I9nZCWcQXSK5x0Jg6k-hNp0pfusAFHy5mYp0AWAlYL-vqkKCst6rFv224irc9ufqhwZPj1I5uWzm3ikwkyRH-uMRvWANNghgIxFV7B87LwjL3PxutbPOh8Vy1eRM_SojNkfQhdsrTHYQ2a_coC1cz7HdOP2LjiKnxs88WStUt8tSShbX3_pYUvDG74vQ4nHacknm_MGFcoB4lI-E_j4BSNAxlcjMxmAjPreT2gm8hTiKcuXLiRCh8_gg) example that changes a specific data every 2seconds, calling `invalidateData()` or `invalidateRawData()` didn't work either for us.

_I can tell that there is something fundamental about amcharts animation that I am missing._

**Comment by zeroin** [comment]
Instead of calling invalidateData you should call `chart.invalidateRawData();`
Invalidate data simply creates everything from scratch, using your original data array.

**Comment by fasidOnGit** [comment]
@zeroin looks like working :), let me apply that to my scenario (which is not shared)

**Comment by fasidOnGit** [comment]
@zeroin Sorry to extend it from what we have originally reported...

`invalidateRawData` doesn't update the graph for us...

here is a snippet....

```
this.chart = am4core.create(this.id, am4charts.XYChart);
        this.chart.fontFamily = 'inherit';
        this.chart.data = [this.data];
        this.chart.height = this.height;
        this.chart.margin(0, 0, 0, 0);
        this.chart.padding(0, 0, 0, 0);
        this.chart.background.fill = am4core.color('#f8a8b8');
        // tslint:disable-next-line:no-magic-numbers
        this.chart.background.fillOpacity = 0.6;

        const categoryAxis = this.chart.yAxes.push(new am4charts.CategoryAxis());
        categoryAxis.renderer.grid.template.strokeWidth = 0;
        categoryAxis.strokeWidth = 0;
        categoryAxis.renderer.inside = true;
        categoryAxis.dataFields.category = 'key';
        categoryAxis.renderer.labels.template.disabled = true;

        const valueAxis = this.chart.xAxes.push(new am4charts.ValueAxis());
        valueAxis.renderer.grid.template.strokeWidth = 0;
        valueAxis.renderer.labels.template.disabled = true;
        valueAxis.strokeWidth = 0;
        valueAxis.calculateTotals = true;
        valueAxis.min = 0;
        valueAxis.max = this.data.total;
        valueAxis.strictMinMax = true;

        const actualSeries = this.chart.series.push(new am4charts.ColumnSeries());
        actualSeries.columns.template.height = this.height;
        actualSeries.stacked = true;
        actualSeries.dataFields.valueX = 'value';
        actualSeries.dataFields.categoryY = 'key';
        actualSeries.columns.template.fill = am4core.color(this.data.color);
        actualSeries.columns.template.fillOpacity = 1;
        actualSeries.columns.template.stroke = am4core.color('#FFFFFF');
        actualSeries.interpolationDuration = 900;
        actualSeries.defaultState.transitionDuration = 900;
        actualSeries.hiddenState.transitionDuration = 900;
```

and when I later update the `this.data` like
```
this.chart.data[0] = {...this.data};
this.chart.invalidateRawData();
```

the graph seems not to be updating...


(_I understand this is a bit complicated... I 'll shoot out a codepen in a while_)

**Comment by zeroin** [comment]
A codepen would help indeed.

**Comment by fasidOnGit** [comment]
@zeroin Seems to be working when I isolate it toa codepen...
I think I can fix it.. 

Thanks for the spontaneous help here... I appreciate it... Sorry for the noise :)

[Codepen](https://codepen.io/fasid/pen/yLeebRq?editors=0011)
