### ISSUE TITLE
Can't hide tooltip after using series.alwaysShowTooltip = true

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2565]
I'm struggling to hide my tooltips after using `series.alwaysShowTooltip = true`

I'm using an XY chart, I would like to show the series tooltips when hovering on the series in the legend and hide them on the hover off state.

I've tried a few methods, including using `showTooltipOn = "always"` and then setting it to false. This the code I'm currently trying

```
        chart.legend.itemContainers.template.events.on("over", function (ev) {
            var series = ev.target.dataItem.dataContext;
            series.alwaysShowTooltip = true;
        });

        chart.legend.itemContainers.template.events.on("out", function (ev) {
            var series = ev.target.dataItem.dataContext;
            series.alwaysShowTooltip = false;
            'series.bullets.values[1].hideTooltip();'
            series.hideTooltip();
        });
```

**Comment by zeroin** [comment]
A codepen of the situation would make it a lot easier for me to help you.

**Comment by Josh10101010** [comment]
Here is an example https://codepen.io/Josh519/pen/jOWqrNz

**Comment by zeroin** [comment]
Hi,

I would do it by setting isHover = true/false on the clones of the bullet, not on the template:

https://codepen.io/team/amcharts/pen/928e3782ae8dca6683cea1032181ef4a

**Comment by Josh10101010** [comment]
That works perfectly, thank you for the help!
