### ISSUE TITLE
Change series label color

### ISSUE THREAD

**Issue by imtrobin** [amcharts/amcharts4#2566]
Hi, how do I change the series label color, without the original series variable

eg. for piemenu

after setting up piemenu, somewherre else

```
chart.series.labels.template.fill = color; // not working
chart.series.values [0].labels.template.fill = color; // this crashes
```

**Comment by xorspark** [comment]
The [`series`](https://www.amcharts.com/docs/v4/reference/piechart/#series_property) property in a chart object is a [list](https://www.amcharts.com/docs/v4/reference/listtemplate/), which is similar to an array, so you need to get an item from the list to modify it using methods like `getIndex` or `each`. `template` is only used when you first define the objects that are created in its associated list as it will copy the values set in the template to each individual object upon creation. 

If you need to change values iniitally defined through a template, you need to access them directly from the list and modify them:

```
chart.series.getIndex(0).labels.each(function(label) {
  label.fill = color;
});
```

**Comment by imtrobin** [comment]
That's is the most logical explanation of  the template, thank you. That's why I get very confused because

1. This works for legends

```
chart.legend.labels .template.fill = fontColor;
chart.legend.valueLabels.template.fill = fontColor;
```

2. Your example runs but didn't work, label colors still unchanged. Yes, I did call validateData at the end

**Comment by xorspark** [comment]
It works for me. Note that the chart needs to be fully initialized (i.e. after the `ready` event has fired).

**Comment by imtrobin** [comment]
The chart is fully initialized, I'm changing the color via a button click

**Comment by xorspark** [comment]
Something must be wrong with your setup then. My original code [works just fine](https://codepen.io/team/amcharts/pen/4aecf9f76c28b4334e5587d7eab2a407), button click and all.

**Comment by imtrobin** [comment]
I made the call in a function and it doesn't change color 

[here](https://codepen.io/imtrobin/pen/bGEEXmN)

**Comment by xorspark** [comment]
Remove the `validateData` call. Chart objects can detect most changes to properties and data on its own, unless you're [mainpulating data in place](https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points), or other special cases where you need to call `invalidateData` or `invalidateRawData` for data and `invalidate` for other objects.

Besides, `validateData` isn't even valid in v4 anyway.

**Comment by imtrobin** [comment]
Ah I see. I found validateData method while searching online somewhere. Didn't know it would mess up.

I still have some issues.

1. For legends, I'm using this code, and it seems to work, is this correct for should it be a each loop too?

```
        if (chart.legend.labels)        chart.legend.labels     .template.fill = fontColor;
        if (chart.legend.valueLabels)   chart.legend.valueLabels.template.fill = fontColor;

```
2. When I removed validateData, it works from a button press. However it didn't work if I call it directly after create. I suppose it's not yet initialized?

[Updated](https://codepen.io/imtrobin/pen/bGEEXmN)

**Comment by xorspark** [comment]
For consistency, I'd err toward using the loop since there are cases where updating the template/similar template-like objects (bullets for instance) post initialization doesn't quite work vs looping through them.

>  When I removed validateData, it works from a button press. However it didn't work if I call it directly after create. I suppose it's not yet initialized?

Correct. If it's not yet initialized, template will still work (or just put it in a `ready` callback)

**Comment by imtrobin** [comment]
Ok, I got it working, thanks.  but I want to high light this part, which is very confusing. In your sample simple pie chart , you do this

```
// Add and configure Series
var pieSeries = chart.series.push(new am4charts.PieSeries());
pieSeries.dataFields.value = "litres";
pieSeries.dataFields.category = "country";
pieSeries.slices.template.stroke = am4core.color("#fff");
pieSeries.slices.template.strokeWidth = 2;
pieSeries.slices.template.strokeOpacity = 1;
```

In theory, we cannot configure slices.template until we got an instance, which potentially won't work because the chart can be initialized  immediately after the push. Is that correct?

**Comment by imtrobin** [comment]
Argh, I got another issue. I'm not sure if this is by design. When I change the data, the label color reverts back to the original color which I have first set.  I used a json , that should be the template.

**Comment by xorspark** [comment]
Template settings are tied to the object they're associated with. You can set those properties while you're creating the object.

Regarding the legend, using the template is fine to update - I misspoke. The color will stick after updates as they have `applyOnClones` enabled by default.

We have more in-depth documentation on templates [here](https://www.amcharts.com/docs/v4/concepts/list-templates). I may have simplified things so I recommend treating that as gospel on the subject.

**Comment by imtrobin** [comment]
Ok. I'm actually using json to create, and this is where the inconsistency comes in

```
 var chart = am4core.createFromConfig (json, chartID);

chart.legend.labels     .template.fill = fontColor;  // works fine
chart.legend.valueLabels.template.fill = fontColor;  // works fine

chart.titles.template.fill = fontColor; // does not work
chart.titles.values[0].fill = fontColor; // but this works

//chart.series.labels.template.fill = fontColor; // error does not exist
 // chart.series.labels.values[0].fill = fontColor; // cannot read values, due to chart not ready?
```

Only legends work fine, how do I set the title and labels template properly?

**Comment by xorspark** [comment]
> chart.series.labels.template.fill 

Did you forget about `getIndex`? `series` is a [list/"array"](https://www.amcharts.com/docs/v4/reference/listtemplate/), as I mentioned [previously](https://github.com/amcharts/amcharts4/issues/2566#issuecomment-642374194). 

```
chart.series.getIndex(0).labels.template.fill = color;
```

As mentioned in the [list template documentation I posted previously](https://www.amcharts.com/docs/v4/concepts/list-templates), you can assign values through the template if you enable `applyOnClones` as that is the default for legend labels and valueLabels.

```
chart.series.getIndex(0).labels.template.applyOnClones = true;
chart.series.getIndex(0).labels.template.fill = color; //this will now work
chart.titles.template.applyOnClones = true;
chart.titles.template.fill = color;  // this will also now work
```

Any confusion you have on templates will be cleared up in the template doc I linked to.

Note that if you're modifying a single title, you should use getIndex, similar to how you'd modify a single series' properties.

```
chart.titles.getIndex(0).fill = color;
```

**Comment by imtrobin** [comment]
No, I got it working with getIndex. It is confusing bcos

chart.titles.template.fill = fontColor; // does not work

applyOnClones is not default for titles and labels but default for legends. If I modify the template, I would expect it to change the current values as well. Why is default for legend but not titles/labels?

So now I can get it working without ready event or modifying individual values. applyOnClones is really I want needed  which is causing all these confusion.

**Comment by xorspark** [comment]
There isn't a rule of thumb as to what gets it enabled by default other than what the developers thought would make the most sense so that users wouldn't have to iterate through every object in the list to change them (bullets, columns/slices, legends make sense as there are always multiple objects, but not titles, for instance). Having it enabled by default on everything would have major performance implications as the chart would need to check/apply settings on every single clone from every object template. It's a trade-off.
