### ISSUE TITLE
Get chart instance by Div ID

### ISSUE THREAD

**Issue by imtrobin** [amcharts/amcharts4#2568]
Hi, how do I get a chart instance by ID? This solution does not seem to be working anymore

https://stackoverflow.com/questions/28384411/get-an-instance-of-amchart-using-id

**Comment by xorspark** [comment]
The v4 equivalent of doing this is to use search the chart instances inside the `amrcore.registry.baseSprites` array and find the matching div ID through its `htmlContainer` property:

    am4core.registry.baseSprites.find(function(chartObj) {
      return chartObj.htmlContainer.id === "your-div-id";
    });

**Comment by imtrobin** [comment]
got it working. thanks, it's a little different from the docs that uses svgcontainer

https://www.amcharts.com/docs/v4/tutorials/chart-was-not-disposed/

**Comment by xorspark** [comment]
I suspect that's a typo in the docs since that property is undefined when I tried to use it. Checking with the team. Thanks for the heads-up.

**Comment by imtrobin** [comment]
Hmm, I think I spoke a little too soon. I'm creating one piechart, but I see that console.table (am4core.registry.baseSprites); shows two entries in the array.

![image](https://user-images.githubusercontent.com/531606/84340917-68ecfe80-abd4-11ea-8dcf-ff11f9fa5060.png)

One of it doesn't have the html property.

Is there a place I can see the javascript? cos I don't have intellisense, and these are simple things which I can resolve myself easily if I can see the javascript code.

**Comment by xorspark** [comment]
Are you sure you're not creating the same chart twice somehow in your setup? That's the only way I can see you getting two objects. Not sure what to say about the undefined htmlContainer though.

**Comment by imtrobin** [comment]
I know why now. My page refreshes by code once upon, it does create two charts, but the first one is disposed. But I'm using console.table,  it behaves like a watch instead of logging at the current time it is called so it was showing the 2nd one which is not disposed properly.

So the question is, how should I dispose properly.

**Comment by xorspark** [comment]
Calling dispose() on the chart instance is how you dispose the chart, as mentioned in the documentation you linked previously. It also removes the instance from from the baseSprites array, as you can see [here](https://codepen.io/team/amcharts/pen/0b8ed816c94f722bcfd47c582323011f?editors=1011).

**Comment by imtrobin** [comment]
Ok, I did some changes but I couldn't fork your codepen. I put it through a function call and I can't dispose [here](https://codepen.io/imtrobin/pen/MWKKMNY)

**Comment by xorspark** [comment]
It's `dispose()` with a lowercase d. You're calling `Dispose()` with a capital D, which is not a valid method.

**Comment by imtrobin** [comment]
ah I see. thanks, seems working now.
