### ISSUE TITLE
Customise labels in cateogry/date axis 

### ISSUE THREAD

**Issue by yenniSuresh** [amcharts/amcharts4#2569]
How can I have each category/date label customised in category/date axis?

**Comment by zeroin** [comment]
There are a lot of ways to do it - using adapters, using property fields, getting label from data context etc.

**Comment by yenniSuresh** [comment]
@zeroin 

> There are a lot of ways to do it - using adapters, using property fields, getting label from data context etc.

Can you help me with doc link of how using adapter or an example because I have tried but couldn't figure it out

**Comment by zeroin** [comment]
Could you prepare a codepen of your chart and tell what exactly you want to customize?

**Comment by yenniSuresh** [comment]
Hi @zeroin , really sorry getting back so late,

here is the codepen link:  https://codepen.io/yennisuresh/pen/abdYKjJ
I want to achieve the output in code pen using DateAxis.

**Comment by martynasma** [comment]
If you would like to compare data from multiple periods, I suggest you consider using two separate DateAxes and set data directly to series.

Here's an example:
https://codepen.io/team/amcharts/pen/wmLZYM

**Comment by yenniSuresh** [comment]
Hi @martynasma, thanks for trying to help me out here.

I understand your suggestion but as per my requirement, I have to achieve the expected output using single DateAxes. I did went through documentation multiple time but couldn't find a way yet.

**Comment by martynasma** [comment]
In that case, your only option is to use adapters on DateAxis labels.

```
dateAxis.renderer.labels.template.adapter("text", function(text, target) {
  // extract date from target.dataItem and format your own label
  // then return it
  return text;
});
```

**Comment by yenniSuresh** [comment]
@martynasma , I tried what you have suggested

https://codepen.io/yennisuresh/pen/wvMXWJZ but seems prior_date is not available in target.dataItem

**Comment by martynasma** [comment]
Well, the data item for DateAxis does not contain actual data.

You will need to find closest one. Something like this:

```
dateAxis.renderer.labels.template.adapter.add("text", function(text, target) {
  if (!target.dataItem.date) {
    return text;
  }
  var pos = dateAxis.dateToPosition(target.dataItem.date);
  var dataItem = chart.getClosest(series1.dataItems.values, pos, 0);
  if (dataItem) {
    var dataContext = dataItem.dataContext;
    return `${dataContext.current_date.toString()} vs\n ${dataContext.prior_date.toString()}`;
  }
  return text;
});
```

**Comment by yenniSuresh** [comment]
@martynasma it works.

Can you tell me if its worth this way because it looked more simple and efficient to do using categoryAxis? If there is a way to use template structure for BOTH current_date and prior_date as dates while building concatenated label (i.e `return `${dataContext.current_date.toString()} vs\n ${dataContext.prior_date.toString()}`;`) then I think its worth to do using adapter solution because that way I will be able to make use of charts inbuilt date processing techniques else I think I might be introducing more overhead.

**Comment by martynasma** [comment]
It's up to you.

If you don't need natural time scale as well as other features (e.g. data item grouping, formatting of dates, etc.) that `DateAxis` brings, you can use `CategoryAxis`.

**Comment by yenniSuresh** [comment]
Okay, thanks a lot @martynasma for all your help
