### ISSUE TITLE
Alignging multiple charts

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#257]
Hi, we are rendering multiple charts in a single page.
And all of them needs to be aligned as in v3
V3: https://codepen.io/varshamathukumalli/pen/xzZQzN?editors=1010
V4: https://codepen.io/varshamathukumalli/pen/pOoqbM?editors=0010
How to achieve that in v4

**Comment by martynasma** [comment]
You can explicitly set width to all vertical axes' renderer to the same fixed value. (similarly like on v3 version)

```
categoryAxis.renderer.width = 150;
```

It will work on any kind of axis.

Here's your example:
https://codepen.io/team/amcharts/pen/aff7da2c43cbb488e0b0b384e6ab9a89/
