### ISSUE TITLE
Axis Range Label Unable to Overlap Value Axis Label 

### ISSUE THREAD

**Issue by sqsim** [amcharts/amcharts4#2570]
**Question**

How to ensure that the axis range label is always overlapping the value axis label?

Amcharts : "@amcharts/amcharts4": "^4.9.26",
Chrome : Version 83.0.4103.61 (Official Build) (64-bit)
Framework : "react": "^16.13.1",

Axis Range Label unable to overlap.
![image](https://user-images.githubusercontent.com/43167866/84296846-34028c80-ab7f-11ea-9a3d-75e559a05d58.png)

![image](https://user-images.githubusercontent.com/43167866/84296859-3a910400-ab7f-11ea-88a2-c70c26a526a2.png)

**Additional context**

My candlestick chart is getting new data and the axis range value and text is changing according to the last value of the data item.

I tried changing the Axis Range zIndex.

This is how my valueAxis and range looks like:

```
    let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
    valueAxis.renderer.opposite = true;


    var range = valueAxis.axisRanges.create();
    range.grid.strokeOpacity = 1;
    range.grid.strokeDasharray = "8,4";
    range.grid.above = true;
    range.label.background.fill = am4core.color("black");
    range.label.fill = am4core.color("#fff");
    range.label.text = range.value;

   valueAxis.events.on("dataitemsvalidated", (ev)=> {
      this.updateYaxis(series.dataItems.last);
    });
```
I have a function that updates the range value
```
  updateYaxis =(dataItem)=>{
    if (dataItem !== undefined){
      let series = this.chart.series.getIndex(0);
      let yAxes = this.chart.yAxes.getIndex(0);
      let range  =yAxes.axisRanges.values[0]

      range.value = dataItem['closeValueY']

      if (dataItem.droppedFromOpen) {
        range.label.background.fill = series.dropFromOpenState.properties.fill;
        range.grid.stroke = series.dropFromOpenState.properties.fill;
      }
      else {
        range.label.background.fill = series.riseFromOpenState.properties.fill;
        range.grid.stroke = series.riseFromOpenState.properties.fill;
      }
    }
  }

```

**Comment by zeroin** [comment]
Do you set `zIndex` on a range or on `range.label`? A codepen of your situation would make it a lot easier for me to help you.

**Comment by sqsim** [comment]
I tried setting zIndex on the ``` range.label```.
This is an example
https://codepen.io/sqsim/pen/OJMNLXy

**Comment by zeroin** [comment]
Working fine for me:
https://codepen.io/team/amcharts/pen/07b9b62550d6714dd3efc35c280b3562

**Comment by sqsim** [comment]
Oh i need to add zIndex inside the function whenever the axis range label changes.
Thank You for your help.
