### ISSUE TITLE
Random xAxes labels are hidden if yAxes contains a title and values

### ISSUE THREAD

**Issue by JeffDess** [amcharts/amcharts4#2572]
**Bug description**

On a XY Chart on narrow screens such as iPhones, random xAxes labels are not showing up if a yAxes title has been defined and yValues contain many characters, even if there is plenty of space for the label. It's not necessarily the last label that gets masked. 

Looking at the SVG, these labels only contains the character "L" :

```html
<g fill="#000000" fill-opacity="0" opacity="0" stroke-opacity="0" style="pointer-events: none;" transform="translate(117.5,0)">
  <g transform="translate(-4.5,10)" style="user-select: none;">
    <text x="0" y="17.015625" dy="-4.594"><tspan>L</tspan></text>
  </g>
</g>
``` 

Here's a JSON config to reproduce, "Cat 2" label is not displayed. However, removing yAxes title or using two digits values or lower for _a_ and _b_ makes it to appear as expected.  

```json
{
  "series": [
    {
      "type": "ColumnSeries",
      "name": "A",
      "dataFields": {
        "valueY": "a",
        "categoryX": "category"
      },
      "stacked": true
    },
    {
      "type": "ColumnSeries",
      "name": "B",
      "dataFields": {
        "valueY": "b",
        "categoryX": "category"
      },
      "stacked": true
    }
  ],
  "data": [
    {
      "category": "Cat 1",
      "a": 1200,
      "b": 1500
    },
    {},
    {
      "category": "Cat 2",
      "a": 500,
      "b": 700
    }
  ],
  "xAxes": [
    {
      "type": "CategoryAxis",
      "dataFields": {
        "category": "category"
      }
    }
  ],
  "yAxes": [
    {
      "type": "ValueAxis",
      "title": {
        "text": "Amount"
      }
    }
  ]
}
````

And here's some screenshot of these two scenarios : 

![2020-06-10 17_06_27-AmCharts](https://user-images.githubusercontent.com/6100619/84318763-f0872e80-ab3c-11ea-907a-029d339cf317.png)
![2020-06-10 17_07_06-AmCharts](https://user-images.githubusercontent.com/6100619/84318764-f11fc500-ab3c-11ea-988a-344e29854f2c.png)

**Environment (if applicable)**

* amCharts4
* Tested in Chrome 83 desktop using iPhone 6/7/8 device emulator preset (375px wide)

**Comment by xorspark** [comment]
You need to set a small `minGridDistance` in your category axis if you want to ensure that more labels are visible in smaller widths.

```
  "xAxes": [
    {
      "type": "CategoryAxis",
      "renderer": {
        "minGridDistance": 15
      },
      "dataFields": {
        "category": "category"
      }
    }
  ],
```

Documentation: https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by JeffDess** [comment]
Oh right, that's working. I can't believe I've missed that in the docs. 
May I suggest adding a note to [the reference](https://www.amcharts.com/docs/v4/reference/axisrenderer/#minGridDistance_property) ? Something like : "Could be useful to force the display of all labels when the chart is displayed on a tight space". 
Thanks a lot!
