### ISSUE TITLE
Change flights from not working. 

### ISSUE THREAD

**Issue by asunyer** [amcharts/amcharts4#2573]
Hi there,

I don't know how to add more "hubs" on the map. Currently, there are 4 "hubs", but if I click the button to change, it only shows two. It seems it doesn't iterate through the list. 

http://www.vueling-va.com/VAM/vam/nueva/index.php# 

You have to click on the "Cambiar HUB" link in the map.

Any suggestions?

**Comment by zeroin** [comment]
If you could create a codepen of your chart, I could try to help.

**Comment by asunyer** [comment]
@zeroin https://codepen.io/asunyer90/pen/gOPPVEN?editable=true

**Comment by zeroin** [comment]
It does not iterate through origin cities because the original demo was done to handle two and you didn't change anything for it to handle more. Here is modified pen:
https://codepen.io/team/amcharts/pen/LYGNEvB

check hit handler to see how it was done.

**Comment by asunyer** [comment]
@zeroin that's amazing. Thank you so much!!!
