### ISSUE TITLE
Stacked axis with AXIS ranges drop the fill 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#2574]
Hi, 

Latest version of am4Charts

Codepen https://codepen.io/dimitrios-kanellopoulos/pen/YzwqKaz 

Result 

<img width="1440" alt="Screenshot 2020-06-11 at 11 07 57" src="https://user-images.githubusercontent.com/1268723/84366959-dc424080-abd3-11ea-819e-2731b8c59c47.png">

Notice that the fist series doesn't drop the fill of the range but the second one does and so on.

**Comment by jimmykane** [comment]
<img width="1438" alt="Screenshot 2020-06-11 at 11 13 28" src="https://user-images.githubusercontent.com/1268723/84367564-b49fa800-abd4-11ea-8639-f74c18f8a101.png">


Also as seen above adding a series fill it really works bad pushing the fill lower than it should

**Comment by zeroin** [comment]
This should solve it:

```
  valueAxis.adapter.add("baseValue", function(baseValue, target){
    return target.minZoomed;
  })
```

I am afraid I can't change it in code, as it would result a lot of potential changes on a regular setup, like gradients starting from a different place etc.

**Comment by jimmykane** [comment]
Roger that. Indeed it works. 

Question. In a multiseries environment were some yAxis (value axis) are shared, should this be added per series or per axis?

**Comment by zeroin** [comment]
Per axis, it doesn't do anything with series.

**Comment by jimmykane** [comment]
If for some reason the event is added multiple times (eg 2 times on same
axis ) does it fire more than once? Or are those flattened ?

**Comment by zeroin** [comment]
No, it should be fired once (well, indeed a lot of times, but adding several will not do the harm)

**Comment by jimmykane** [comment]
Hi @zeroin  could you help a little bit more? 

The baseValue adapter works but when I have an axis of:

```
   yAxis.baseValue = Infinity;
        yAxis.extraMin = 0.0;
      
        // @todo this creates the issue
        yAxis.extraMax = this.extraMaxForPace;
```

This creates and issue like before. 

I fixed it a bit with 

```
if (baseValue === Infinity) {
                return target.maxZoomed;
              }
              return target.minZoomed;
```

But how can I account for that extraMax?

**Comment by jimmykane** [comment]
Actually this is working :-)
