### ISSUE TITLE
Gradient colors in heatLegend on resize

### ISSUE THREAD

**Issue by tapiamcclung** [amcharts/amcharts4#2575]
In this [pen](https://codepen.io/team/amcharts/pen/7fd84c880922a6fc50f80330d778654a) we are shown how to create a HeatLegend gradient with several colors. 
However, line 108 of the pen says "this needs to be repeated e.g. on window resize, orientation change, etc."

What would be the correct listener for this to happen? I tried to rebuild the gradient on "sizechanged" with

```
chart.events.on("sizechanged", function(ev) {
    heatLegendTop.markers.each(function(marker, markerIndex) {
    ... same gradient stuff ... 
})
```
but it still returns the 2-colored gradient on resize.

**Comment by zeroin** [comment]
I modified the pen to make it work more simply and also change on resize:
https://codepen.io/team/amcharts/pen/eYJZVEV

**Comment by tapiamcclung** [comment]
Awesome, thank you!
