### ISSUE TITLE
Custom tooltip positioning

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#2576]
The docs specifically say you can't adjust the tooltip's positioning (e.g 'above' or 'below') relative to the parent element. https://www.amcharts.com/docs/v4/tutorials/using-sticky-tooltips/#Position_and_orientation

This is incredibly annoying for certain situations where not being able to specific just doesn't make any sense. Take this example:

![image](https://user-images.githubusercontent.com/3292053/84449351-5ab9d500-ac0a-11ea-9fe4-7c9027aa2d72.png)

Not only does it not make sense where it is at, it renders right in the middle. However, if I adjust the dy to get it out of the way (`tooltip.dy = -14;`), it then gets cut off completely by the container element.

![image](https://user-images.githubusercontent.com/3292053/84449425-a0769d80-ac0a-11ea-93d2-c1d96bd2340e.png)

Is there any possibility of adding an option to allow us to manually specify which direction it opens? I would think, judging by the article, that `tooltip.pointOrientation = "up";` should do that, but it definitely isn't working.

(config for above second screenshot)
```
  legend.itemContainers.template.tooltipText = '{fullName}';
  const { tooltip } = legend;
  tooltip.dy = -14;
  tooltip.pointOrientation = "up";
```

**Comment by xorspark** [comment]
You have a typo in your property - it's `pointerOrientation`, not `pointOrientation`. `"up"` works correctly and positions the tooltip below the legend label once you correct the property name.

[Demo](https://codepen.io/team/amcharts/pen/5b0264aac66837dafd729dfdec2f0238?editors=0010)

**Comment by runfaj** [comment]
Well, I feel sheepish! Thanks for spotting such an amateur mistake!
