### ISSUE TITLE
Bad date displayed using break line and baseInterval

### ISSUE THREAD

**Issue by fredmef** [amcharts/amcharts4#2577]
**Question**

Hi,

I want to use "**break line**" functionality on line series.

My data have a periodicity of about **1 hour** and the timestamp is given in **second**.

I have done the following xAxes's configuration:
`
          'baseInterval' => [
            'timeUnit' => 'minute',
            'count' => 60,
          ],
`

and the following series's configuration:
`
            'connect' => FALSE,
            'autoGapCount' => 1.1,
            'type' => 'LineSeries',
`

It works fine but dates on tooltips are displayed without minute (plain hour) although minutes are set in timestamp. As you can see:

<img width="1260" alt="tooltips_without_minute" src="https://user-images.githubusercontent.com/41957018/84504938-1f2c1300-acbd-11ea-8b7e-22bc7106e20d.png">

Can you explain me how to display the real dates on tooltips ?

Regards,
Frederic.

**Environment (if applicable)**

amCharts 4.9.23
Configuration done in JSON

**Additional context**

None.

**Comment by martynasma** [comment]
To force particular format on the axis tooltip, use `tooltipDateFormat` setting:

https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/#Tooltip_value_format

**Comment by fredmef** [comment]
I already use the following configuration:

`
'tooltipDateFormat' => 'MMM d, HH:mm'
`

**Comment by martynasma** [comment]
Then, according to your screenshot, it displays the date/time in correct format.

**Comment by fredmef** [comment]
Yes, but minutes are reset in tooltip. On the screenshot minutes are set to 15 in the timestamp but displayed 00.

**Comment by martynasma** [comment]
Can you post your chart on CodePen or jsFiddle so that I could take a look and maybe find a solution?

**Comment by fredmef** [comment]
Yes of course, here is an example [CodePen](https://codepen.io/fredmef/pen/pogEvaX).

**Comment by fredmef** [comment]
Have you the chance to look at the CodePen example ?

**Comment by zeroin** [comment]
In your codepen the gaps between dates is >1 hour, so the chart autoselects baseInterval as one hour. This leads to the minutes to be rounded to hours. If you do not want this and need minutes to be displayed, you should set base interval to minute (or 15 minutes if that's what you need):

`dateAxis.baseInterval = {timeUnit:"minute", count:1}`

Then the tooltip will display minutes.

**Comment by fredmef** [comment]
@zeroin thanks for your answer but it's not exactly what I want to do.
I've updated the [CodePen](https://codepen.io/fredmef/pen/pogEvaX) to better explain.
I've 2 series with a periodicity around 1 hour. But sometimes there are missing dates (no sample received).

And I want the following:
- display series1 with connected line
- display series2 with "break line" functionality to see the missing dates
- display tooltip with minutes

Is it something possible ?
Thanks

**Comment by zeroin** [comment]
Is this demo does the thing you need or something is not right?
https://codepen.io/team/amcharts/pen/577d1553617d6501e9d9613be78ab56e

I set baseInterval to minute and also set autoGapCount to 70.

**Comment by fredmef** [comment]
Yes this configuration does the thing I need !!!
Thanks a lot @zeroin
