### ISSUE TITLE
data export in XSLX format add seconds in date at minute level

### ISSUE THREAD

**Issue by Scylanth** [amcharts/amcharts4#2578]
Hello,

I have noticed that when exporting time data at minute level in xslx format, the exported date is has the every correct value, except for the seconds. In my case, when I read the exported data in the CSV, the date is set to YYYY/MM/DD HH:MM:00, however in XSLX format, it is set to : YYYY/MM/DD HH:MM:21.

Here is an example in code pen :

https://codepen.io/Scylanth/pen/RwravrO

To reproduce, select the export menu button, export as CSV and XSLX and compare both files.

Please note that I have also been able to reproduce it on the codepen of one of the tutorial examples :
https://www.amcharts.com/docs/v4/tutorials/export-menu-in-external-container/#Example

amcharts version used : 4.9.25

Is this bug a configuration issue ? Or is it an issue in the amcharts library ?

Best regards,

Scylanth

**Comment by xorspark** [comment]
I just checked in Excel 2019 and I'm not seeing the issue. The seconds are exporting correctly in both formats (00 from your codepen):

![xlsx-csv-amcharts](https://user-images.githubusercontent.com/2679427/84554728-4566a880-ace7-11ea-888f-65cd142a2248.PNG)

**Comment by Scylanth** [comment]
Hello,

Would you mind sharing your timezone ? I have the feeling the issue I have is related to a bug in the xlsx library linked to timezone conversion as explained in [this thread](https://github.com/SheetJS/sheetjs/issues/1212).

I face exactly the same issue as one of the comment below (constantly +21 secs in French Timezone).

![image](https://user-images.githubusercontent.com/66303836/85003921-305e9f00-b157-11ea-9dd4-ed30e5834333.png)

**Comment by xorspark** [comment]
My timezone is EDT. I suppose it's related to the SheetJS issue you linked to. Unfortunately there isn't anything we can do about it until they address it.
