### ISSUE TITLE
Documentation: Gauge labels and Legend Markers

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#2579]
Just wanted to add a couple requests on documentation updates to help others.

**Gauge Labels**, this article: https://www.amcharts.com/docs/v4/tutorials/show-only-first-and-last-labels-on-gauge-chart/ is a work-around that doesn't allow keeping tick marks and such. A better way to do it is like this article: https://www.amcharts.com/docs/v4/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/. Here's some example code for how I implemented on a gauge:
```
    let rangeMin = valueAxis.axisRanges.create();
    rangeMin.value = startValue;
    rangeMin.label.text = startValue;

    let rangeMax = valueAxis.axisRanges.create();
    rangeMax.value = endValue;
    rangeMax.label.text = endValue;
```

**Legend Marker**, setting size. Hidden deep in this issue, the following comment regarding pixel/percent height/width setting should be added to the docs. https://github.com/amcharts/amcharts4/issues/762#issuecomment-642976936. Here's an example code:
```
// set custom marker height just for line series
markers.adapter.add('pixelHeight', function(_defaultValue, _target) {
  const referenceSeries = _.get(_target, 'dataItem.dataContext');
  if (referenceSeries instanceof am4charts.LineSeries) {
    return 8;
  }
  return 16;
});
```

**Comment by martynasma** [comment]
Good points. Thanks!

Just added this to the Gauge label tutorial:
https://www.amcharts.com/docs/v4/tutorials/show-only-first-and-last-labels-on-gauge-chart/#Solution_2

The note about width/height adapters will go into next update of the class ref.
