### ISSUE TITLE
Dynamic chart drawing based on labels

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#2580]
In amcharts v3, when we added long labels, it would make the chart smaller to accommodate the labels.

![image](https://user-images.githubusercontent.com/3292053/84551273-55bc5a80-acca-11ea-967c-11c56b13aabc.png)

However, in v4, the same type of configuration cuts them off:

![image](https://user-images.githubusercontent.com/3292053/84551294-679dfd80-acca-11ea-94bd-409c63365866.png)

Here's an example fiddle as well: https://jsfiddle.net/0fx13tLs/

Similarly, we run into the same issue with the last label when rotating a different way. Here's another fiddle:
https://jsfiddle.net/v4hzfoe2/

Given that all of my labels are going to be dynamic so I can't easily know the width of the strings, and I can't predict which labels amcharts will decide to hide/show, based on the parent container size, what would be the recommended way to make the chart adjust to fit the labels so they aren't truncated?

**Comment by zeroin** [comment]
In v4 this is not handled automatically. One of the possible approaches would be to measure width of all labels and adjust value axis margin:

https://jsfiddle.net/mg1fp4a7/

**Comment by runfaj** [comment]
Thanks - though not ideal, I think that will work! For future people reading this issue, here's the relevant code (would need some adjustment to handle margins on both sides of the graph):
```
categoryAxis.events.on("dataitemsvalidated", function(event){
  var minLeft = Infinity;
  categoryAxis.renderer.labels.each(function(label){
    var left = label.pixelX - label.measuredWidth * am4core.math.cos(label.rotation);
    if(left < minLeft){
      minLeft = left
    }    
  })

  valueAxis.minWidth = Math.abs(minLeft)
})
```
