### ISSUE TITLE
how to remove the data from end of series ? 

### ISSUE THREAD

**Issue by dharam0034** [amcharts/amcharts4#2581]
**Question**
Hi, 

Is there any way to remove the data items from the end of series instead of beginning?
I found "removeData" which removes the data from beginning! Can it also be used to remove the last data items ? Also, what is use of "skipRaw"?

"removeData(
count: $type.Optional < number > ,
skipRaw?: boolean
)"

**Environment (if applicable)**
amcharts v4, Google Chrome 

**Additional context**

**Comment by martynasma** [comment]
No, I'm afraid there's currently no way to incrementally remove data from the end. You would need to update `data` array, then revalidate whole dataset.

**Comment by dharam0034** [comment]
Thanks

**Comment by dharam0034** [comment]
Hi, 

Do you think this feature could be added in future? This is important for the following reason 

Imagine that you have display a plot for 'average of several data streams' from different sources (each data point contains a timestamp but these data-sources are not sending data at the same time and number of source are also varying over large time). 
Therefore, we have to display (update) the average at that timestamp until we keep receiving the data for that timestamp from different sources. So, easiest way is to remove the last data point and add a same updated data point.

**Comment by lticadler** [comment]
Take a look:
https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points
