### ISSUE TITLE
Duplicate id (id object) used on multiple objects message

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#2582]
**Question**
When I try to enter a third destination city, the following message appears : Duplicate id (kiev) used on multiple objects. Sometimes, when I use the debugger, the application accepts the third input and so on up until it crashes with the same message error. If I do not use the debugger, every third input, it crashes.

Note: to only put capital city in the fields (e.g. ottawa, paris, berlin, warsaw, kiev, moscow, peking, london, etc.)

Step order to reproduce the problem:
1) Enter the origin city (I type ottawa)
2) Enter a destination city (I type berlin)
3) Press enter
4) Click on "Click to show lines" on the map
5) Enter a destination city (I type kiev)
6) Press enter
7) Click on "Click to show lines" on the map
8) Enter a destination city (I type moscow)
9) Press enter
-> The message appears

Link: https://codesandbox.io/s/wizardly-fog-05s3r?file=/src/app/components/map/map.component.ts

In case you need the data file, see data.json under services/

**Environment (if applicable)**
amCharts 4
Firefox Browser Developer 78.0b6 (64-bit)
Angular 9.1.7
Typescript 3.9.3
MongoDB 4.2

**Additional context**
Before entering the third destination city
![Before entering the third destination city](https://user-images.githubusercontent.com/33300743/84596208-5f5cd400-ae2a-11ea-8e9d-2025780b24bb.png)

The message
![The message](https://user-images.githubusercontent.com/33300743/84596107-c5952700-ae29-11ea-8ae6-d17b24f046ce.png)

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
