### ISSUE TITLE
Show lines as soon as the user enters a destination city

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#2584]
**Question**
Instead of clicking to a link to show line between two cities, I would like that the line appears as soon as the user enter a destination city. I looked at the documentation but don't know how to implement: https://www.amcharts.com/docs/v4/reference/iinteractionobjectevents/#input_property

Note: to only put capital city in the fields (e.g. ottawa, paris, berlin, warsaw, kiev, moscow, peking, london, etc.)

Step order to reproduce the problem:
1) Enter the origin city (I type ottawa)
2) Enter a destination city (I type berlin)
3) Press enter
Should show the line instead of clicking the link on "Click to show lines" on the map

Link: https://codesandbox.io/s/wizardly-fog-05s3r?file=/src/app/components/map/map.component.ts

In case you need the data file, see data.json under services/

**Environment (if applicable)**
amCharts 4
Firefox Browser Developer 78.0b6 (64-bit)
Angular 9.1.7
Typescript 3.9.3
MongoDB 4.2

**Additional context**
Interface 
![Interface](https://user-images.githubusercontent.com/33300743/84596208-5f5cd400-ae2a-11ea-8e9d-2025780b24bb.png)

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
