### ISSUE TITLE
Strange AmCharts4 Map rendering/bug

### ISSUE THREAD

**Issue by lmarenco** [amcharts/amcharts4#2585]
**Bug description**

We created a geojson [map](https://senselab.med.yale.edu/__test/_luis/visnd.json) using the Maps tutorial.
That file renders well using Amcharts maps 3. Like in [this](https://codepen.io/team/amcharts/pen/1dc66e00033ea0c5bc1d0271ed0c7f33?editors=1000) solution

But it has problems while rendering on version 4.
Here is a live link https://senselab.med.yale.edu/__test/_luis/G1.html

And here is the code we are using.
```html
<html>
<head>
  <style>
    #chartdiv {
      width: 100%;
      height: 98vh;
    }
  </style>

  <script src="https://www.amcharts.com/lib/4/core.js"></script>
  <script src="https://www.amcharts.com/lib/4/maps.js"></script>

  <script>
    am4core.ready(function () {
      var chart = am4core.create("chartdiv", am4maps.MapChart);
      chart.geodataSource.url = "./visnd.json";
      chart.projection = new am4maps.projections.AlbersUsa();

      var polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
      polygonSeries.useGeodata = true;

      var polygonTemplate = polygonSeries.mapPolygons.template;
      polygonTemplate.tooltipText = "{id}";
      polygonTemplate.polygon.fillOpacity = 0.2;
      polygonTemplate.fill = am4core.color("#244226");

    });
  </script>
</head>
<body>
  <div id="chartdiv"></div>
</body>
</html>
```
We're really puzzled what could be wrong?

**Comment by zeroin** [comment]
Could you check if the same works with a different projection, like Mercator? AlbersUsa can not be used for maps with coordinates which goes out of the US area.

**Comment by lmarenco** [comment]
Changed to Miller. And the problem is still there. Thanks

**Comment by zeroin** [comment]
Could you explain the problem - I see the map is rendered and no errors are displayed.

**Comment by lmarenco** [comment]
If you zoom In will see that the map has features that do not show well (faded), And their Ids are not properly shown. It is like there are no feature limits, or just for one.
What had to create a new map from scratch. And it is fin.
But using the new geojson file I did a test. I moved some features from the original order, and the problem appeared again. It seems to me the AmCharts map rendering module perhap expects the features to appear in certain order.

**Comment by lmarenco** [comment]
![image](https://user-images.githubusercontent.com/12093412/84967265-8e509f80-b0e1-11ea-964b-c3daf6dc0fae.png)

**Comment by zeroin** [comment]
I see. It's indeed something in the geojson file. I think the problem might be with some areas. Check if the coordinates go clockwise and not counter clockwise, as ccw coordinates means that this is a hole in the area and not the area itself.

**Comment by Renziera** [comment]
Why counter-clockwise means there's a hole? I'm very confused. 
In the [docs](https://www.amcharts.com/docs/v4/tutorials/custom-polygons-on-map-chart/) it says 

> The order of points is important. According to GeoJSON specification, they must come in clockwise order. The first and last point should be present.

but according to the [geojson spec](https://tools.ietf.org/html/rfc7946) (section 3.1.6) 

> A linear ring MUST follow the right-hand rule with respect to the area it bounds, i.e., exterior rings are counterclockwise, and holes are clockwise.

They're contradicting each other :/

**Comment by zeroin** [comment]
We follow ESRI shape file standard:
https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf

Same as d3, which we use for processing coordinates.
And they need outer rings to be arranged clockwise.
