### ISSUE TITLE
Manual bending of a line

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2586]
Hi.
Let's say I want to draw a line from Athens to Palermo but representing a cruise ship. Using a simple straight line will overlap ground terrain, which would be wrong.
Is it possible to draw a MapLine with an irregular shape (red line)? 
Thank you!
![image](https://user-images.githubusercontent.com/37619567/84755375-468b2480-afca-11ea-8df3-691e1ef8af46.png)

**Comment by zeroin** [comment]
You can have this by adding intermediate points to your line. Meaning you cant use imagesToConnect but provide multiGeoLine coordinates: https://www.amcharts.com/docs/v4/reference/mapline/#multiGeoLine_property
