### ISSUE TITLE
Creating a title for the legend container - strange behaviour

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2588]
Hi,

I'm trying to create a title for the legend container, I've done so my appending labels to the container. The issue is that I would like to a label (or rectangle) to be the full width of the container with a background fill so act as a divider line.

However when I set this label to fill the entire width, the legend collapses into a single column, rather than wrapping as it usually would.

I believe it could be setting the width of a single column so there isn't room for any others?

What would be the best way of creating a title for the legend? Essentially I want it to behave like a separate container within the legend with properties the same as "display: block"

I've created a codepen demonstrating this

https://codepen.io/Josh519/pen/jOWqrNz

**Comment by zeroin** [comment]
Legend has a "grid" layout set so your label and each other element you add to it is treated in the same way as other legend items and it also influences all the layout. My suggestion would be to create a separate container, then add all the items you need to it and arrange in the way you want and then add it to `chart.legend.parent`.

**Comment by Josh10101010** [comment]
Thanks for the help, I've updated the codepen with the changes for anyone else who might need this.

I found that I had to change the parent depending on the legend position to get it to format nicely.

For position right I set the parent as chart.legend (width 100px)
For position bottom I set the parent as chart.legend.parent (width 100%)
