### ISSUE TITLE
What is KeyboardEvent?

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#2589]
**Question**
What should I put as KeyboardEvent? Should I use an object called KeyboardEvent? Do you have an example on how to apply the input property of InteractionObjectEvents?
Link of the article: https://www.amcharts.com/docs/v4/reference/iinteractionobjectevents/#input_property

**Comment by martynasma** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent
