### ISSUE TITLE
ChartScrollbar customization limit.

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/amcharts4#259]
Is there any v4 property to customize the following: 
  - selectedBackgroundColor (from v3)
  - selectedGraphFillColor (from v3)

I tried to use ``` fill ``` but it doesnt work.

Sample screenshot for my requirement
![image](https://user-images.githubusercontent.com/3138071/44398482-87ed4d00-a576-11e8-9764-0dc44a47856e.png)

**Comment by martynasma** [comment]
Unfortunately, it's currently not possible.

I'm going to chalk it up as an enhancement request.

If at some point we implement it, we'll ping you.

**Comment by kevzlou7979** [comment]
Any update on this feature request?

**Comment by fasidOnGit** [comment]
+1

**Comment by fasidOnGit** [comment]
Here is a workaround,
```
svg {
    g[role="scrollbar"] {
      g[role="slider"] {
        > :first-child {
          fill: red;
        }
      }
    }
  }
```

**Comment by kevzlou7979** [comment]
@fasidOnGit Nice

**Comment by martynasma** [comment]
We reached a decision not to implement this feature. Sorry.
