### ISSUE TITLE
how to apply same color for packed circle chart

### ISSUE THREAD

**Issue by prk87** [amcharts/amcharts4#2590]
how to apply same color for packed circle chart.

i have tried below code but not working.

code:
networkSeries.colors.list = [
                am4core.color("#F42B03")
];
![PackedCircle_Chart](https://user-images.githubusercontent.com/64831085/84775131-6e937b80-affc-11ea-85f9-74311bbd614a.PNG)

**Comment by martynasma** [comment]
You got it right, just need to instruct ColorSet to reuse the color list, not invent new colors:

```
networkSeries.colors.list = [
  am4core.color("#F42B03")
];
networkSeries.colors.reuse = true;
```

**Comment by prk87** [comment]
Fix is Working now, Thanks
