### ISSUE TITLE
How to update countries data and colors

### ISSUE THREAD

**Issue by YannickVeron** [amcharts/amcharts4#2591]
**Question**

How can I update the map data and countries colors ?

In Vue.JS, I've created a map with the country color depending of some data :

```
for(const code of Object.keys(this.countries)){
	let val = this.getValueForYear(this.countries[code],this.selectedYear)
	let color = this.getColor(val)
	polygonSeries.data.push({"id":this.countries[code].alpha2,"name":this.countries[code].name,"value":val,"fill":color,"alpha3":code})
}
var polygonTemplate = polygonSeries.mapPolygons.template;
polygonTemplate.tooltipText = "{name}";
polygonTemplate.polygon.fillOpacity = 0.6;
polygonTemplate.propertyFields.fill = "fill";
```
It's working nicely but I cannot manage to update the colors. I've added a slider that works well: 
```
var slider = chart.createChild(am4core.Slider);
slider.start = 0;
slider.padding(0, 30, 0, 80);
slider.background.padding(0, 30, 0, 80);
slider.marginBottom = 15;
slider.events.on("rangechanged", ()=>{
	let year = Math.round(1990+(slider.start*26))
	if(year!=this.selectedYear){
		this.selectedYear=year
		this.updateMap();
	}
})
```
But the map doesn't change : 
```
updateMap:function(){
	let chart = am4core.registry.baseSprites.find(c => c.htmlContainer.id === "chartdiv")
	for(const dataIndex in chart.series.values[0].data){
		if(chart.series.values[0].data[dataIndex].hasOwnProperty("alpha3")){
			let value = this.getValueForYear(this.countries[chart.series.values[0].data[dataIndex].alpha3],this.selectedYear)
			let color = this.getColor(value)
			chart.series.values[0].data[dataIndex].value=value
			chart.series.values[0].data[dataIndex].fill=color
		}
	}
	chart.invalidateData()
}
```
I managed to make it work by adding 
`chart.series.values[0].getPolygonById(chart.series.values[0].data[dataIndex].id).fill = color;`
after the data set but isn't there a better solution ?

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
