### ISSUE TITLE
How dynamically make some bullets visible/hidden when click on some div-element?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#2592]
I got line serie. One bullet is visible. I've got 2 div-elements: arrow-left, arrow-right.
I need on click on div - hide current bullet and show prev/next bullet on line.

 please, help, i don't understand how to do it.

**Comment by martynasma** [comment]
You can iterate through bullets in your series and check their `dataItem` then use `hide()` or `show()` accordingly, e.g.:

```
series.bullets.each(function(bullet) {
  bullet.clones.each(function(clone) {
    // Check clone.dataItem and determine whether to clone.show() or clone.hide() this bullet
    // ...
  });
});
```
