### ISSUE TITLE
How to don't show serie-Line animation from bottom to it coordinates position when update chart data or on first draw?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#2593]
1) I dinamically change line coordinates and on every change it jump from bottom.
It's a bad behavior for me, because i need line to move itself from current position to new position without jumping every time. Can i off this animation effect?

2) or maybe, How can i make line invisible, then reload data, and after line come in it end position, make it vivsible?

*sorry for my bad english

**Comment by zeroin** [comment]
Could you show a codepen of your case so I could see how do you change coordinates?

**Comment by russeljo** [comment]
Codepen https://codepen.io/russeljo/pen/NWGbLmj?editors=1111
it's a lil big. And there's another one problem - bullet's tooltip is blinked very fast and hide.

**Comment by zeroin** [comment]
As you are updating raw data but not changing the array, instead of assigning new data each time, you could call:
```
          //chartMain.data = getMainChartData();
        chartMain.invalidateRawData();
```

**Comment by russeljo** [comment]
I found more esiest solution:
//just don't use animated theme, work now perfect 
    //am4core.useTheme(am4themes_animated);

**Comment by zeroin** [comment]
Of course, but I thought you need other animations :)
