### ISSUE TITLE
How to disable zoom in XY and bar chart

### ISSUE THREAD

**Issue by LalitAgrawala004** [amcharts/amcharts4#2594]
**Question**
I want to disable zoom in my XY and bar charts. Could not find the required property to disable it. I tried to maxZoomLevel: 1 but it is not working.  Please help.

**Environment (if applicable)**

**Additional context**

**Comment by zeroin** [comment]
If you need chart cursor, you could set `chart.cursor.behavior = "none"` and do not add the scrollbar at all.
