### ISSUE TITLE
How add text near the line serie?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#2595]
I create line series depend on some third parameter, there are too much lines to write third parameter f.e. in legend. Need add some text description near the line. Please, how can i do that?
I foun only https://www.amcharts.com/docs/v4/tutorials/placing-labels-anywhere-on-the-chart/
but it's too complicated, need recalculate coordinates of labels. Is there simple way?

**Comment by martynasma** [comment]
Something like this maybe?

https://www.amcharts.com/docs/v4/tutorials/show-last-value-at-the-end-of-lineseries/

**Comment by russeljo** [comment]
yes, it's good thing, thank you!
