### ISSUE TITLE
How do I reference a valueY column name containing brackets in tooltipText?

### ISSUE THREAD

**Issue by timbostop** [amcharts/amcharts4#2596]
**Question**

I am following the example tooltip with rich content. https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/

I want to refer to specific column valueYs in the tooltip like the example:

```
series3.tooltipText = `[bold]YEAR {categoryX}[/]
----
Cars: {cars}
Motorcycles: {motorcycles}
Bicycles: {bicycles}`;
series3.tooltip.pointerOrientation = "vertical";
```

But my column names (may) have brackets in them:

```
series3.tooltipText = `[bold]YEAR {categoryX}[/]
----
Cars: {cars}
Motorcycles: {motorcycles}
Bicycles: {bicycles (bikes)}`;
series3.tooltip.pointerOrientation = "vertical";
```

See the example:
https://codepen.io/timbostop/pen/rNxWWBO

The tooltipText cannot resolve {bicycles (bikes)} even though that is a valid column name in the data set.

Is there a knack to escaping these brackets so that I can refer to them?
I've tried escaping the brackets, stripping the brackets. Unfortunately not having the brackets in the names is not an option for the data set I am using.

How do I reference such an item as a placeholder?

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
No, I'm afraid. Brackets in placeholders are used for in-line functions so there's no way to use them in a name of a field. There's also no way to escape them. Sorry.
