### ISSUE TITLE
Map zoom without scaling text?

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2597]
I am trying to focus a specific section of the map like in this example: [https://www.amcharts.com/docs/v4/tutorials/pre-zooming-map-to-a-list-of-countries/](url)

The problem is that the text (and line stroke) are affected by the zoom, but they shouldn't. I want the same font-size and line appearance as it is on normal scale.
Thank you for your help!

**Initial preview**
![image](https://user-images.githubusercontent.com/37619567/84888566-2168e580-b0a0-11ea-8699-ba2c2d77100e.png)

**Zoomed preview** (I want to zoom the map, not the text, line is also affected)
![image](https://user-images.githubusercontent.com/37619567/84888657-45c4c200-b0a0-11ea-829d-99a200a83425.png)

**Comment by zeroin** [comment]
setting `label.nonScaling = true`  or `line.nonScalingStroke = true` should do the thing.

**Comment by directcuteo** [comment]
Yes, now it looks perfect. I appreciate!
