### ISSUE TITLE
amCharts V4 exporting to image generating Canvas popup

### ISSUE THREAD

**Issue by SrinivasKothapalli** [amcharts/amcharts4#2599]
while Exporting chart to image , getting Canvas popup before downloading image. 

let img;
img = await chart.exporting.getImage( "png" );
chart.exporting.getImage( "png" ).then( ( data ) => {
  img = data;
} );

**Comment by martynasma** [comment]
Is there a question in there? :)

**Comment by SrinivasKothapalli** [comment]
we were using Canvas in our application for screen Capture. 
But when we added V4 to our Application, it was conflection with its z-index:-9999 and a canvas was shown for a second while download.
