### ISSUE TITLE
ChartScrollbar - can't hide only the main chart

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/amcharts4#260]
I have a chartscrollbar and I just wanna display only the scrollbar and hide the main chart , to do this I tried the following code:

```
xyChart.scrollbarX.chart.hide();
```

But it seems that also the scrollbar get affected to be not displayed.

**Comment by martynasma** [comment]
The `XYScrollbar` does not display any series by default.

If yours is, it means you are explicitly adding a series to scrollbar's `series` list. Something like this:

```
scrollbarX.series.push(series);
```

Remove those lines from your code and you'll be good to go :)

**Comment by kevzlou7979** [comment]
This is what happened when i remove the code
![image](https://user-images.githubusercontent.com/3138071/44494385-19a3aa00-a69e-11e8-97a7-33ead90ea96d.png)

I think what I need to hide is just the graph below but retain the scrollbar

![image](https://user-images.githubusercontent.com/3138071/44494442-52438380-a69e-11e8-992a-b53d22efd57e.png)

**Comment by martynasma** [comment]
OK, let me get this straight: you don't need the chart, just scrollbar with chart in it?

```
chart.plotContainer.disabled = true;
```

https://www.amcharts.com/docs/v4/tutorials/scrollbar-only-xy-chart/

**Comment by kevzlou7979** [comment]
Cool that works :)
