### ISSUE TITLE
more than 1 chart on page

### ISSUE THREAD

**Issue by serhiolo** [amcharts/amcharts4#2601]
Hi, i have simple question. Im tested free demo amcharts4. When Im trying to add 2 charts to my html, i have errors and i see always  only second chart. I trying to rename 'chartdiv', but it give me another error, chartdiv not found.
Can i create more than 1 chart on page? And mayby you have some specification, how i can do it. Thanks a lot, and have a nice day. Regards

**Comment by martynasma** [comment]
Yes, you can. Just make sure that you use different ids both in HTML when defining a `<div>` and in `am4core.create()` function call.
