### ISSUE TITLE
https://www.amcharts.com/demos/custom-html-elements-map-markers/

### ISSUE THREAD

**Issue by kdambekalns** [amcharts/amcharts4#2606]
**Bug description**

The markers [in the demo](https://www.amcharts.com/demos/custom-html-elements-map-markers/) are positioned wrong:

<img width="637" alt="wrong-position" src="https://user-images.githubusercontent.com/95873/85016504-21cdb300-b16a-11ea-8ddb-917145231903.png">

And they become visible outside the map container if you zoom in:

<img width="915" alt="markers-outside-map" src="https://user-images.githubusercontent.com/95873/85016529-2f833880-b16a-11ea-81ab-171c0ec82cd2.png">

Since there is really not much code to it, it seems `geoPointToSVG()` is not working as expected?

**Environment (if applicable)**

- https://www.amcharts.com/demos/custom-html-elements-map-markers/
- macOS 10.15.5
- Firefox 77.0.1
- Chrome 83.0.4103.106
- Safari 13.1.1

**Additional context**

The v3 demo at https://www.amcharts.com/docs/v3/tutorials/custom-html-elements-map-markers/ works fine…

**Comment by martynasma** [comment]
Thanks for the heads up! Fixed.

It was an issue with CSS.

**Comment by TheLalaMan** [comment]
Can you elaborate on what it was? Because we have a map based on this tutorial and there the custom markers display the same behavior... thx!

**Comment by martynasma** [comment]
Sure.

The markers are placed in the "chartdiv" and positioned using `position: absolute`. However, "chartdiv" itself did not have any positioning, which means that marker positions were relative to the closest positioned parent.

I just added `position: relative` to the "chartdiv" style.

P.S. I'm not sure why it did work before, though. Maybe some overall CSS from website was making chartdiv positioned, and something changed.
