### ISSUE TITLE
 Amchart 4 radar chart axis tooltip bug

### ISSUE THREAD

**Issue by oweichpold** [amcharts/amcharts4#2609]
Hello!

In the current version of the Amchart 4 radar chart, the axis tooltip sometimes displays the wrong designation.

See graph on CodePen:

https://codepen.io/Dionisys/pen/OJMWmdq

Furthermore I can't deactivate the axis tooltip.

Thanks in advance for your help

Best regards!

**Comment by zeroin** [comment]
This can be solved by adding:

`categoryAxis.renderer.tooltipLocation = 0.01`

I will see if I can fix the issue on our side.

**Comment by oweichpold** [comment]
Thanks zeroin, ist works! 

The other question, can I disable/hide the black axis-toolstips?

**Comment by zeroin** [comment]
Sure, you either set `axis.tooltip.disabled = true` or `axis.cursorTooltipEnabled = false;`

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
