### ISSUE TITLE
Legend colors

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#261]
Hi,

I want to render only legends with a given color.
Legends are rendering but colors are not applied.
Codepen link: https://codepen.io/varshamathukumalli/pen/WgbBzw?editors=0010
How to apply colors to legends

**Comment by martynasma** [comment]
You almost got it, except property fields should be setting on legend marker's tmeplate, not directly on legend:

```
chart.legend.markers.template.propertyFields.fill = 'color';
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
