### ISSUE TITLE
PDF export from amcharts is not Korean

### ISSUE THREAD

**Issue by wkdaudwn11** [amcharts/amcharts4#2610]
Before asking a question, the sentence may be weird because it is a Google translator. Please understand.

I am using version 16.13.1 of React. I need to download a PDF using amchart's export function. This function works fine. However, if Korean is included in the content, Text is broken.

https://www.amcharts.com/docs/v4/tutorials/using-pdf-export-fonts/

I tried referring to the link above, but the symptoms are the same.

Below is the PDF download related part of my code.
(If I upload all the code, it will be too long, so I will only upload the PDF-related code.)

Please help me...T_T

```
import am4fonts_notosans_kr from '@amcharts/amcharts4-fonts/notosans-kr';

...code...

chart.exporting.menu = new am4core.ExportMenu();
// const pdfOption = chart.exporting.formatOptions.getKey("pdf"); // Error! getKey() is undefined.
const pdfOption = chart.exporting.getFormatOptions('pdf');

pdfOption.addData = true;
pdfOption.addURL = false;
pdfOption.font = am4fonts_notosans_kr; // Code for Korean patch.

chart.exporting.adapter.add('pdfmakeDocument', function (pdf, target) {
    // Add title
    pdf.doc.content.unshift({
        text: '캠페인 주요 지표 트렌드 - CPC, Clicks',
        margin: [0, 30],
        style: {
            fontSize: 25,
            bold: true,
        },
    });

    // Add logo
    pdf.doc.content.unshift({
        image: logo_base64,
    });

    return pdf;
});
```

**Comment by wkdaudwn11** [comment]
`
import am4fonts_notosans_kr from '@amcharts/amcharts4-fonts/notosans-kr';

...code...

chart.exporting.menu = new am4core.ExportMenu();
// const pdfOption = chart.exporting.formatOptions.getKey("pdf"); // Error! getKey() is undefined.
const pdfOption = chart.exporting.getFormatOptions('pdf');

pdfOption.addData = true;
pdfOption.addURL = false;
pdfOption.font = am4fonts_notosans_kr; // Code for Korean patch.

chart.exporting.adapter.add('pdfmakeDocument', function (pdf, target) {
    // Add title
    pdf.doc.content.unshift({
        text: '캠페인 주요 지표 트렌드 - CPC, Clicks',
        margin: [0, 30],
        style: {
            fontSize: 25,
            bold: true,
        },
    });

    // Add logo
    pdf.doc.content.unshift({
        image: logo_base64,
    });

    return pdf;
});
`

**Comment by martynasma** [comment]
Hm, it works fine for me:
https://codepen.io/team/amcharts/pen/d3848848ed3e520d4bf054321ed1bb1e

Is it possible that you might be using not the most recent version of amCharts or font package?

**Comment by wkdaudwn11** [comment]
The amchart version is:
```
"@amcharts/amcharts4": "^4.9.4",
"@amcharts/amcharts4-fonts": "^4.0.1",
"@amcharts/amcharts4-geodata": "^4.1.14",
```
Currently, after installing using "yarn add @amcharts/amcharts4-fonts", 
"import am4fonts_notosans_kr from'@amcharts/amcharts4-fonts/notosans-kr';" It is written as.

Looking at the Codepen you wrote, it looks like vanilla JavaScript, and my environment is react. Maybe this difference...T_T

How can I get and write notosans-kr.js from React using CDN method?

**Comment by martynasma** [comment]
Why would you want to use CDN for React?

Just make sure you are using latest version of fonts and main charts package and you should be good to go.

**Comment by wkdaudwn11** [comment]
Um... once confirmed, it doesn't work on Mac, but on Windows 10, Korean works well. We will try to update the version later. Thanks for the reply.
