### ISSUE TITLE
LineSeries is not updating/refreshing data giving push of null error

### ISSUE THREAD

**Issue by SanjibMajhi1998** [amcharts/amcharts4#2611]
**Bug description**
when I'm going to use LineSeries and trying to update data by using setInterval(), it is not updating/refreshing the data and its giving "Cannot read the property of push of null" error. Whereas .....when I'm going to use ColumnSeries and trying to update the data Its working properly.

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Can you post an example on CodePen/jsFiddle?
