### ISSUE TITLE
How to fit labels in chord diagram

### ISSUE THREAD

**Issue by otmezger** [amcharts/amcharts4#2612]
**Question**
How can we adjust the chord diagram to fit the labels?

See example: https://codepen.io/team/amcharts/pen/MBGJZO

<img width="802" alt="amCharts_V4__Who_kissed_who_in_FRIENDS" src="https://user-images.githubusercontent.com/2758346/85120808-0c1cc400-b224-11ea-86d4-0b0d13aee049.png">

Maybe by allowing the axis to be in 2 rows, or by giving the labels of the axis more space?  --> Is there an option to manage the "radial" width of the axis labels?

**Comment by martynasma** [comment]
I suppose you can reduce the default radius of the diagram:

```
chart.radius = am4core.percent(60);
```

Making labels wrap is another option as well:

```
chart.nodes.template.label.maxWidth = 70;
chart.nodes.template.label.wrap = true;
```

**Comment by sinramyeon** [comment]
@martynasma is there any way to set a names label to left or right? I guess it is more convenient...
