### ISSUE TITLE
Zoom to a MapLineObject

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2613]
I am trying to zoomIn a MapLineObject created on a line between certain points expressed at multiGeoLine.

These are my lineObject and my image attached to it:
```
        const bullet = this.line.lineObjects.create();
        bullet.nonScaling = true;
        bullet.width = 1;
        bullet.height = 1;
        bullet.horizontalCenter = 'middle';
        bullet.verticalCenter = 'middle';

        const img = bullet.createChild(am4core.Image);
        img.width = 50;
        img.height = 40;
        img.horizontalCenter = 'middle';
        img.verticalCenter = 'middle';
        img.scale = 1.2;
        img.href = 'assets/img2.svg';
```

I tried to use the function: 
```
this.map.events.on('ready', () => {
    this.map.zoomToMapObject(bullet, 1, true);
});

```

But it doesn't compile because MapLineObject does not extend MapObject. 
Would be fine to zoom to the image attached to the bullet aswell.

How can I achieve this? There is no zoomToMapLineObject() method. Thank you!

**Comment by martynasma** [comment]
I'm afraid `zoomToMapObject()` does not support `MapLine`'s.

The workaround would be to automatically calculate East, West, North, and South coordinates, then use `MapChart`'s `zoomToRectangle()` method:
https://www.amcharts.com/docs/v4/reference/mapchart/#zoomToRectangle_method

I don't think we have a ready-made example, though.
