### ISSUE TITLE
Changing the color of each category names

### ISSUE THREAD

**Issue by oweichpold** [amcharts/amcharts4#2614]
Hello!

I would like to ask how to change the color of each category names, I have not found anything how to solve it:

For example:

T1 = Color Green
T2 = Color Blue
T3 = Color Red
...

Here is the CodePen to my question:

https://codepen.io/Dionisys/pen/OJMWmdq

Many, many thanks in advance!

Best regards,

Oliver

**Comment by xorspark** [comment]
You can define a `propertyFields` on the category axis label to reassign the `fill` property to your font_color field.

```
categoryAxis.renderer.labels.template.propertyFields.fill = "font_color";
```

Documentation: https://www.amcharts.com/docs/v4/concepts/data/#Property_fields
