### ISSUE TITLE
Legend with multiple columns

### ISSUE THREAD

**Issue by janbols** [amcharts/amcharts4#2615]
I think the following feature is not yet supported. 

I would like to create a legend having multiple columns: one with the min value, one with the max value, one with the average value, one with the sum. The legend would look something like the following:

               min   max   avg   sum
series1    5      90       45   1420    
series2    8      57       38   1200
series3    8      35       15   500

The values one be calculated based on the current data of the series.

Best regards
Jan

**Comment by martynasma** [comment]
Technically, you can include multiple value placeholders in the legend:

```
chart.legend.valueLabels.template.text = "{valueY.open} {valueY.close} {valueY.sum} {valueY.average}"
```

That said, arranging them in precise columns might be problematic. If that is a requirement, you might need to consider building a custom legend:

https://www.amcharts.com/docs/v4/tutorials/custom-external-legend/
