### ISSUE TITLE
How to tile/wrap Map

### ISSUE THREAD

**Issue by GideonMax** [amcharts/amcharts4#2617]
I have a map using the Miller projection and I want it to tile, meaning, I don't want the map to be "re-projected" when a user pans, I just want simple tiling.
as the miller projection of a map is a rectangle, I don't see any reason why it should not be tileable.

I have tried changing the map's panBehaviour, "rotateLong" solves the sideways tiling but it doesn't allow the user to pan up or down, even when zoomed in, "rotateLongLat" makes the map "re-project" when the user pans up.

there was another issue about this problem that was closed in January as someone claimed that it had already been fixed, yet it has not.
this is my code:
```
        MapsCore.useTheme(theme);
        this.map = MapsCore.create(this.div, Maps.MapChart);
        this.map.geodata = GeoData;
        this.map.projection = new Maps.projections.Miller();
        this.series = this.map.series.push(new Maps.MapPolygonSeries());
        this.series.useGeodata = true;
```
MapsCore and Maps are aliases for am4core and am4maps.
GeoData is an alias for the default export of worldHigh.js.
theme is the default export of the theme I'm using.

additional info:
I'm using the newest version of amcharts, more specifically, the es2015 modules version which I forked from this very github on 2020.6.20.
I'm not using any framework, I'm using plain js and web components.

**Comment by martynasma** [comment]
How about not setting `panBehavior` at all? It then should just drag the map regularly, regardless of projection.

**Comment by GideonMax** [comment]
I tried that, the map didn't tile, moving the map would reveal the map boundaries

**Comment by martynasma** [comment]
Oh, you want the wraparound functionality.

I'm afraid that's not possible with regular `panBehavior`. And it's also not possible to pan without projection not recalculating itself using `rotateLongLat`.

Sorry.

**Comment by GideonMax** [comment]
I am aware that this is not possible, that is also why I'm making this issue, because I think that this should be implemented.

**Comment by martynasma** [comment]
Sorry, I wasn't clear. What I meant we are not planning on implement this functionality, I'm afraid.
