### ISSUE TITLE
How to display Label text on multiple lines?

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2618]
Hi. I am having a long text wrapped inside a container and I would like to display the text on multiple lines.

Usually, when you have in HTML something like this: 
```
<div style="width: 200px; background: #44f400">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
</div>
```
It would look like this: 
![image](https://user-images.githubusercontent.com/37619567/85273883-dc212b00-b486-11ea-8d5c-ccf5eb297fff.png)

Using the am4core.Label Object, how can get something like above?

I've created a CodePen with the example:

https://codepen.io/directcuteo/pen/wvMJEwM

Here it would be nice to have this case explained aswell:
https://www.amcharts.com/docs/v4/tutorials/wrapping-and-truncating-axis-labels/

Thank you!

**Comment by martynasma** [comment]
You seem to have wrapping disabled:

```
description.wrap = false;
```

Just change it to `true` to get text wrapped to your set width.

**Comment by directcuteo** [comment]
Indeed it is working fine on CodePen. Still, on my app it is working only if I use `label.text`, instead of `label.description`. Somehow, that `<foreignObject>` tag is not taking the width I am providing with `label.width` field, but on CodePen that's working fine. The code is the same, the container child is added to the `map.chartContainer` element.

In my app, on Chrome, foreignObject is having that `74` width always:
![image](https://user-images.githubusercontent.com/37619567/85278736-ff030d80-b48d-11ea-895b-2c3b32030a1f.png)

and of course the view is affected:
![image](https://user-images.githubusercontent.com/37619567/85278832-25c14400-b48e-11ea-90b0-a908560eb225.png)


If you have any hint why am I getting this behaviour would be great... Thank you!

**Comment by martynasma** [comment]
Do you by any chance have older version of amCharts in your app?

Also, if it's only text that you are going to display, you might want to consider using `text` instead of `html` label.

**Comment by directcuteo** [comment]
I think I am using pretty new versions:

    "@amcharts/amcharts4": "4.2.6",
    "@amcharts/amcharts4-geodata": "^4.1.4",

The final thing I would like to accomplish is writing 3 lines of text and then display the ellipsis "...". I am not sure if this can be achieved using the properties we have on amCharts Sprite in order to just use simple text.

![image](https://user-images.githubusercontent.com/37619567/85282724-e2b69f00-b494-11ea-8510-bafc45973b69.png)

I think I can just cut the text to a certain index, but having it automated by css would be better.

**Comment by martynasma** [comment]
4.2.6 is 15 months old.

Wanna try current version (4.9.27)? :)

**Comment by directcuteo** [comment]
I've installed it via npm a week ago, weird that it didn't installed the lastest one.
What's important is that after the update, it is indeed working as I want it. Thanks a lot!
