### ISSUE TITLE
Line chart's line renders in a weird way

### ISSUE THREAD

**Issue by kavinda1995** [amcharts/amcharts4#2619]
**Bug description**

I'm using amcharts to create some line chars with vertical stacked line series, and the output is something like this

![image](https://user-images.githubusercontent.com/19621533/85300210-e44b8b80-b4c3-11ea-8099-e0c4a763703f.png)

as you can see the lines are rendered in a weird way, Sometimes - when there is big amount of points it draws correctly, like this

![image](https://user-images.githubusercontent.com/19621533/85300416-25dc3680-b4c4-11ea-94f1-ae36061252c8.png)

But whenever i zoom it, it get's weird again.

**Environment (if applicable)**

 - amCharts version - 4.9.19
 - Browser and its version - chrome
 - Related frameworks and their versions  - Angular 9

**Additional context**

I'm using data grouping (in DateAxis)

**Comment by xorspark** [comment]
Is your data sorted in ascending order? This is required for date-based data, as mentioned [here](https://www.amcharts.com/docs/v4/concepts/data/#Date_based_data). Out of order data can sometimes cause weird rendering issues like this.

Does this occur in the latest release? We're currently on 4.9.27.

If the issue still persists after verifying the above, then please provide a minimal repro case on codepen/stackblitz/codesandbox.
