### ISSUE TITLE
Stop bar race chart animation

### ISSUE THREAD

**Issue by avalosrodriguez** [amcharts/amcharts4#2620]
Hi , I really like the bar chart race, but how do I change it so when it ends, doesnt restart again the animation.
I would like to once it reached the end it will stop, and only starts again if you push the play button.

**Comment by xorspark** [comment]
If you're using the same structure as the race demo, just set `playButton.isActive` to false and do an early return in the nextYear function, or your equivalent method:

```
function nextYear() {
  year++

  if (year > 2018) {
    year = 2003;
    playButton.isActive = false; //triggers the toggled event, which calls stop when isActive is false
    return;
  }
  // ...
}
```
