### ISSUE TITLE
Remove series by reference

### ISSUE THREAD

**Issue by vladipooh** [amcharts/amcharts4#2621]
I found the way to remove series by reference but I can't make it work.

var series1 = chart.series.push(new am4charts.LineSeries());
series1.dataFields.valueY = "value";
series1.dataFields.dateX = "date";
series1.name = "value1"
series1.strokeWidth = 3;
series1.tensionX = 0.8;
series1.data = [{...}]

chart.series.removeIndex(
  chart.series.indexOf(series_to_remove)
);

I replaced "value1" to "series_to_remove" but it doesn't work. What I should replace in series_to_remove?

**Comment by xorspark** [comment]
Did you mean to replace `series_to_remove` with `series1`? There is no `value1` in your snippet.

`chart.series.removeIndex(chart.series.indexOf(series1))` works just fine for me.

[Demo](https://codepen.io/team/amcharts/pen/7f7ab5d22a9d7799f894c0a3fb1ca31c?editors=1010)

**Comment by vladipooh** [comment]
Thank you very much. That´s very clear with your demo.
