### ISSUE TITLE
Can't the Info box come out when downloading as a PDF?

### ISSUE THREAD

**Issue by wkdaudwn11** [amcharts/amcharts4#2622]
Hello. I am writing amchart well. Thank you.

```
chart.exporting.menu = new am4core.ExportMenu();
```
I am downloading a PDF using the exporte button.

https://www.amcharts.com/docs/v4/tutorials/custom-static-multi-value-tooltip/

Also, by referring to the link at the top, an Info box is created to display data in the Info box when the mouse is over.

However, if you download the PDF in this state, the Info box will appear.
Can you make the Info box invisible in PDF?

**Comment by xorspark** [comment]
You can set `exportable` to false on the info box to exclude it from the export output.

```
info.exportable = false;
```

Documentation: https://www.amcharts.com/docs/v4/concepts/exporting/#Excluding_elements_from_export

**Comment by wkdaudwn11** [comment]
It works very well. Thank you!!
