### ISSUE TITLE
How to change XYChartScrollbar chart (type)

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#2623]
**Question**
Is it possible to display the scrollbar chart different to the main chart?

My chart is a 3D column chart with multiple series.
In the scrollbar only one series is displayed. So there is no sense in displaying it also 3D.

I tried to set angle and depth to 0 but nothing changed.
```
    const scrollbarChart = chart.scrollbarX.scrollbarChart;
    scrollbarChart.angle = 0;
    scrollbarChart.depth = 0;
```

![image](https://user-images.githubusercontent.com/58069494/85394973-bb70d800-b54f-11ea-8433-6aa2a25490d2.png)

Additionally on the right side the scrollbar chart is cut off:
![image](https://user-images.githubusercontent.com/58069494/85402641-4eb00a80-b55c-11ea-9f61-edc271bf63ed.png)

**Environment (if applicable)**
 - amCharts version 4.9.27

**Comment by zeroin** [comment]
You should reset depth and angle on series:
```
var sbSeries = scrollbarX.scrollbarChart.series.getIndex(0)
sbSeries.depth = 0;
sbSeries.angle = 0;
```

**Comment by lticadler** [comment]
50% solved ;) The angle value is used by the scrollbar.
Unfortunately, setting the depth has no impact. Doesn't matter if the value is 0 or 1000.

https://codepen.io/chrisadler/pen/PoZjREd

Screenshot from the pen
![image](https://user-images.githubusercontent.com/58069494/85717187-87cbb480-b6ed-11ea-811c-5dd88f4f6e76.png)

**Comment by lticadler** [comment]
Hi,
any new ideas? Or should it be treated as a bug?

**Comment by martynasma** [comment]
I would rather create a completely separate series to use for scrollbar:

```
var series3 = chart.series.push(new am4charts.ColumnSeries());
series3.dataFields.valueY = "year2017";
series3.dataFields.categoryX = "country";
series3.clustered = false;
series3.hidden = true;

....

var sbSeries = scrollbarX.scrollbarChart.series.getIndex(0)
sbSeries.hidden = false;
```

You hide it from the main chart, but unhide when it creates a clone in scrollbar.

https://codepen.io/team/amcharts/pen/7c374ceba84190b39e918ac610f8f0c5?editors=0010

**Comment by lticadler** [comment]
### Background info:
On legend label click I exchange the scrollbar series to the chosen series.
Therefore I remove the old one and push the selected and afterwards configure the scrollbar series layout. That works well so far.
```
chart.scrollbarX.series.removeIndex(0);
chart.scrollbarX.series.push(seriesX);
```

### Additional info I found out for:
> You should reset depth and angle on series:
> 
> ```
> var sbSeries = scrollbarX.scrollbarChart.series.getIndex(0)
> sbSeries.depth = 0;
> sbSeries.angle = 0;
> ```

After exchanging the the scrollbar series the depth and angle settings work (for series)
Start
![image](https://user-images.githubusercontent.com/58069494/86556492-c9612880-bf53-11ea-85a2-fbdabc73c38c.png)
After exchange
![image](https://user-images.githubusercontent.com/58069494/86556236-0678eb00-bf53-11ea-9f4f-ea2de39be31b.png)
So this would be a workaround - but the scrollbarchart has still the depth. This why if changing to a series other than the first one the scrollbar series "flies"
![image](https://user-images.githubusercontent.com/58069494/86556662-3c6a9f00-bf54-11ea-99ae-3699df59801c.png)

### Using a separate series for the scrollbar
**Yes, thank you.**
In case others stumble upon this issue:
No more removing / pushing different series to the scrollbar. Just reuse the single separate one.
If you want to change the scrollbar series to an other series values bind it and invalidate scrollbar chart afterwards.
```
const sbSeries = chart.scrollbarX.scrollbarChart.series.getIndex(0);
sbSeries.bindDataField('valueY', valueY);
chart.scrollbarX.scrollbarChart.invalidateData();
```
https://codepen.io/chrisadler/pen/xxZYyKE?editors=0010

**Other things to mention:**
- Not only hide the separate series from chart - also from legend
```
series3.hidden = true;
series.hiddenInLegend = true;
```

- With the separate scrollbar series I have the problem, that the scrollbar is empty in some of my chart configurations.
I assume it has to do with charts which use min/max for the date category axis. I will create an other issue with detailed info...
