### ISSUE TITLE
How can i replace copyrights or customize it, or show it once?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#2625]
I use few charts on page. Can i show amCharts logo only on one chart? Can i change position of logo to rigtht top or another?
Maybe it's possibel to show not gray, but colored copyright and change colors of lines?
Can i show text logo instead the lines-logo?
What can i change?

**Comment by ailon** [comment]
Hi,

You have to show the logo on all charts as is - that's the condition of the free license. Sorry.
