### ISSUE TITLE
tooltip doesn't appear on exact hovered position on a column of bar chart

### ISSUE THREAD

**Issue by ashmichheda** [amcharts/amcharts4#2626]
Hi Amcharts Team,

I am trying to show tooltip exactly at the position I hover on a column of the bar chart. But, it seems that the tooltip by default shows at the center of the hovered column.

Something like this:

![image](https://user-images.githubusercontent.com/31774401/85505294-da4c8a00-b5a2-11ea-8548-9a7b918757ae.png)

Here is my: [Codepen link](https://codepen.io/ashmichheda/pen/gOPWEoQ?editors=0010)

Is there any property/event I can apply on this? 

Thanks,
Ashmi

**Comment by martynasma** [comment]
```
series.columns.template.tooltipPosition = "pointer";
```

**Comment by ashmichheda** [comment]
Thanks, it works. But it also shows the tooltip when I hover outside of the columns. 

Is there any way in which the tooltip appears only when hovering on the columns and disappears if the cursor is anywhere other than the columns.?

**Comment by ashmichheda** [comment]
> Thanks, it works. But it also shows the tooltip when I hover outside of the columns.
> 
> Is there any way in which the tooltip appears only when hovering on the columns and disappears if the cursor is anywhere other than the columns.?

By disabling cursorTooltipEnabled property it works as I want.
```
series.cursorTooltipEnabled = false;
```

**Comment by martynasma** [comment]
Seems like you already solved it. I'm going to just add it here for anyone else interested:

```
series.cursorTooltipEnabled = false;
```
