### ISSUE TITLE
Map line's dimension changes on zoom even when NonScalingStroke is enabled

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2629]
Hello. I have built a line between different geo-points using `multiGeoLine`.
I have set the property `nonScalingStroke` to `true` like this:`        lineSeries.mapLines.template.line.nonScalingStroke = true;
`

CodePen sample: https://codepen.io/directcuteo/pen/vYLZNKW

**Expected behaviour:**
When I zoom in, I expect to see the same width and height of the dashed lines no matter how much I zoom in.

**Current behaviour:**
When I zoom in, the width of the lines and the spacing between them seems to increse. I don't know why it happens and I ask for help.

**For example this line:**
![image](https://user-images.githubusercontent.com/37619567/85581461-45e73380-b645-11ea-9d06-ea245ba6f73f.png)

**If I look at the red section it looks like this:**
![image](https://user-images.githubusercontent.com/37619567/85581529-55ff1300-b645-11ea-96da-d506b935578d.png)

**But if I zoom, it looks like this:**
![image](https://user-images.githubusercontent.com/37619567/85581681-775fff00-b645-11ea-8b39-cd5bd3172828.png)

The last 2 pictures of the same section are clearly different in terms of width and spacing (for each little line).

**Comment by zeroin** [comment]
Although I don't see a proper automatic way to solve this on our side, I can suggest the following solution:

As nonScalingStroke is not actually supported properly by all browsers, what we do is simply change `strokeWidth` of a line when map is zoomed. This means that line.strokeWidth is called each time and this means that if we add and adapter for strokeWidth and return the same value but also add some additional code in this adapter, it will also be called. So here is the adapter:
```
        lineSeries.mapLines.template.line.strokeDasharray = '5 3';        
        lineSeries.mapLines.template.line.adapter.add("strokeWidth", function(strokeWidth, target){
            target.strokeDasharray = (5 / map.zoomLevel) + " " + (3 / map.zoomLevel)
            return strokeWidth;
        })
```

And here is the same codepen with it: 
https://codepen.io/team/amcharts/pen/6d9fec877eff4d525f47711c235da25f

**Comment by directcuteo** [comment]
Thank you for the solution. Do you think there is some way I can throttle the calculation function? The lines are moving too much (or maybe when the zoomLevel is complete).

**Comment by zeroin** [comment]
If you do this only when zooming is complete, you will experience ugly jump, I promise, you will not like it.

**Comment by directcuteo** [comment]
Alright then, thank you!
