### ISSUE TITLE
View a Single Selected Legend Item in Chart 

### ISSUE THREAD

**Issue by ahajric2** [amcharts/amcharts4#2630]
**Question**
Hello, 

I understand that the default behavior of legend toggle is to inactivate or activate the legend/series on the chart. Does there exist functionality to do the inverse of this? i.e. If I select a legend item/series, I want to only see that series data and remove other previously available series on the chart. 

I've looked  through every tutorial I could find, closest I can find is the single legend item to toggle all series off and on https://codepen.io/team/amcharts/pen/JqVQJp . I can some what replicate the behavior I want if I toggle everything off, then select a single series and have that show up. But this is two steps. 

Can this be done with existing functionality? More specifically, can it be done with custom hit events?

**Comment by zeroin** [comment]
Here is an example:
https://codepen.io/team/amcharts/pen/bGERoWo

**Comment by ahajric2** [comment]
Thank you zeroin. This is close to the functionality I was looking for. If I set the initial series variables to hidden = false, then it's exactly what I expected. Now working on figuring out how to toggle all of them to show after I've clicked on one at first. I think I need to  create a toggle all series for that functionality.
