### ISSUE TITLE
 How to fill 100% of chart image with A4 paper in landscape mode when downloading as PDF?

### ISSUE THREAD

**Issue by wkdaudwn11** [amcharts/amcharts4#2631]
![스크린샷 2020-06-25 오전 10 10 34](https://user-images.githubusercontent.com/26559413/85642421-758d4e80-b6cc-11ea-83e4-dedf187dfb30.png)

When you download it as PDF, A4 is basically in the new mode, and the width of the chart image is 100% accordingly.

But when I change this to landscape mode, I want the chart image to be 100%, what should I do?

**Comment by martynasma** [comment]
You may need to use one of the export's image scaling options:
https://www.amcharts.com/docs/v4/concepts/exporting/#Scaling_images

**Comment by wkdaudwn11** [comment]
Below is my code.
```
const pdfOption = chart.exporting.getFormatOptions('pdf');

pdfOption.addData = false; 
pdfOption.addURL = false; 
pdfOption.font = am4fonts_notosans_kr;

pdfOption.pageOrientation = 'landscape';
pdfOption.useRetina = false; // Not working
pdfOption.minWidth = 2000; // Not working
pdfOption.minHeight = 2000; // Not working
pdfOption.maxWidth = 3000; // Not working
pdfOption.maxHeight = 3000; // Not working
pdfOption.scale = 2; // Not working
```

I tried applying Scale, min, and max options, but nothing changed. Why not? Help me..!

**Comment by martynasma** [comment]
Which version of amCharts 4 are you using? the min/max settings were introduced fairly recently.

**Comment by wkdaudwn11** [comment]
Here is the version I use:
```
"@amcharts/amcharts4": "^4.9.4",
"@amcharts/amcharts4-fonts": "^4.0.1",
"@amcharts/amcharts4-geodata": "^4.1.14",
```

**Comment by martynasma** [comment]
OK, those settings were definitely introduced after 4.9.4. Wanna try upgrading to the latest version?

**Comment by wkdaudwn11** [comment]
Yes, I want to upgrade.
Existing amcharts were deleted by 'yarn remove', and then 'yarn add' was installed.

So now the version is like this.
```
"@amcharts/amcharts4": "^4.9.27",
"@amcharts/amcharts4-fonts": "^4.0.1",
"@amcharts/amcharts4-geodata": "^4.1.15",
```

Even if I upgraded the version, it doesn't seem to work. Is there another way?

**Comment by martynasma** [comment]
Can you post your whole chart on CodePen or Stackblitz?
