### ISSUE TITLE
Dynamic height with new yAxis

### ISSUE THREAD

**Issue by mrmime95** [amcharts/amcharts4#2634]
I am trying to add new charts with new series below of a main chart.
The main chart should have a constant height, so I added some dynamic height as I saw [here](https://codepen.io/team/amcharts/pen/RqQYgj?editors=1010)
As on the gif is visible, my probleme is: firstly it draws the new chart, then grows the main charts height.
![dynamic height issue](https://user-images.githubusercontent.com/18379137/85756605-a47ce200-b717-11ea-9d2c-52b316dfc9e2.gif)

I tried it on the following CodePen project (lines 73-106):
https://codepen.io/mrmime95/pen/xxZrJQd

Also, if I comment line 106, it works correctly

Thank you! :)

**Comment by martynasma** [comment]
Looks like setting height for the axis is the culprit:

```
indicatorValueAxis.height = INDICATOR_SIZE;
```

I suspect it might have something to do that you're changing height of the chart container and the axis at the same time.

Though, if I change the height to a relative, the issue goes away:

```
indicatorValueAxis.height = am4core.percent(50);
```

**Comment by mrmime95** [comment]
Thank you for the response.
It works with percent, so i refactor my code around of this :)
