### ISSUE TITLE
Animated theme for two charts on page

### ISSUE THREAD

**Issue by serhiolomakin** [amcharts/amcharts4#2635]
Hi! I have a question about animated theme for two charts on page. I have two charts- first - bar chart race and second - radar chart with axis. I execute scripts "core.js", "chart.js", "animated.js" before the body on page, then I execute scripts in divs. Animated theme accepted only in second chart? What i'm doing wrong? Thanks...

**Comment by martynasma** [comment]
It should work for both charts, unless you call `am4core.useTheme()` after the first chart.

**Comment by serhiolomakin** [comment]
I'm calling am4core.useTheme() before the chart script like in amcharts examples. Also i tried to call am4core.unuseTheme() after the second chart and call am4core.useTheme() before the second chart but nothing happens. In first chart theme working not correctly.

**Comment by martynasma** [comment]
That's weird. Can you post your charts online where we can check?

**Comment by serhiolomakin** [comment]
http://карта-спбмтсб.рф/index.php/hydrogen/petroleum-products

**Comment by martynasma** [comment]
Thanks. I got both charts animating, though. Am I missing something?
![2020-06-26_10-34-03](https://user-images.githubusercontent.com/1458520/85832370-9f13ac00-b798-11ea-8c52-518f16f602f8.gif)

**Comment by serhiolomakin** [comment]
The first chart working not correctly. Look on my page again, i will turn off the second chart and you will see how it must working.

**Comment by martynasma** [comment]
OK, so it's not a theme issue. The code for second chart obviously is interfering with the first one. Like you maybe reusing some of the variables, or somthing.

Try isolating code for both charts, e.g. putting it in separate functions:

```
function createChart1() {
  // code for chart 1
}

function createChart2() {
  // code for chart 2
}

createChart1();
createChart2();
```

**Comment by serhiolomakin** [comment]
Thanks, i will try

**Comment by serhiolomakin** [comment]
Great, It's working. Thank you very much!!!!
