### ISSUE TITLE
Keep getting Invalid type: "XYCursor" in Bar Chart ..

### ISSUE THREAD

**Issue by LalitAgrawala004** [amcharts/amcharts4#2636]
**Question**
I keep getting "Invalid Type: XYCursor" in my bar chart...
Here is my cursor config -

`cursor: {
				disabled: true,
				lineY: {
					disabled: true
				},
				lineX: {
					disabled: true
				},
				type: 'XYCursor'
			},`

and I am setting disabled to false  in chart ready based on a condition.

**Environment (if applicable)**

**Additional context**

![image](https://user-images.githubusercontent.com/17126892/85799885-fde01380-b70d-11ea-8afa-8858a08bb2ec.png)

**Comment by xorspark** [comment]
I'm unable to reproduce your error, as you can see [here](https://codepen.io/team/amcharts/pen/7e72894c0cf25c5fd6bb1c3aa9333ecd?editors=1010).

Can you please provide a minimal codepen or jsfiddle that triggers your error?

**Comment by LalitAgrawala004** [comment]
Hi @xorspark ... Thank you for looking into it.. Sorry, I could not get back to you earlier as I was not available .. 
I tried to create a js fiddle but could not able to reproduce the issue .. It's happening in my deployed environment.. it also showing stack trace in browser console ..

`Error: Invalid type: "XYCursor".
    at XYChart.BaseObject.createClassInstance (Base.js:995)
    at Base.js:463
    at Object.js:121
    at Module.each (Array.js:74)
    at Module.eachOrdered (Object.js:120)
    at XYChart.BaseObject.processConfig (Base.js:444)
    at XYChart.Sprite.processConfig (Sprite.js:8382)
    at XYChart.Chart.processConfig (Chart.js:281)
    at XYChart.processConfig (XYChart.js:1799)
    at XYChart.set [as config] (Base.js:418)`

when it is trying to create XYCursor class, there is no registered class available.. and this is happening only for bar chart. not the line chart.. It's getting critical for us. any help would be highly appreciated.. Thank you ..

**Comment by xorspark** [comment]
It's hard to say without a means to reproduce this. If this is occurring in react or angular, try setting this up in stackblitz or codesandbox. I converted the above setup into an angular app on [stackblitz](https://stackblitz.com/edit/angular-ivy-nzspn9) and still could not reproduce the issue.
