### ISSUE TITLE
combining numberFormatters

### ISSUE THREAD

**Issue by mrmime95** [amcharts/amcharts4#2637]
**Question**
Is that possible with numberFormatter to format to % and if the number is too big usethe bigNumberPrefixes?

Something like in the red block: 
![Screenshot 2020-06-26 at 14 34 43](https://user-images.githubusercontent.com/18379137/85853082-903df100-b7ba-11ea-89d7-69bbca62a5d0.png)

or with exponential view (##.##%e)

**Comment by martynasma** [comment]
No, I'm afraid there's currently no way to combine percent and prefix modifiers :(

**Comment by mrmime95** [comment]
Okey then, Thanks for the fast answer :)

**Comment by mrmime95** [comment]
And do you have some siggestion to resolve this thing manually?
![Screenshot 2020-06-26 at 17 22 50](https://user-images.githubusercontent.com/18379137/85867639-db173300-b7d1-11ea-987e-ba986e4bab66.png)

**Comment by martynasma** [comment]
Un, one option would be to recalculate your values to 100-base percent. I.e. `0.5` becomes `50`. Then you can just use `a` modifier.

There are other (more complicated) options, but let's see how you like this one first :)

**Comment by mrmime95** [comment]
I am working now with 100-base percent, so my data comes like 0.5, on which I am using ##.##% modifier and then it becomes 50%.
But I have a data like this, and 2000000000000000000..0000000 and with modifier gots 2 more 0s, and a percentage symbol.
So I think, I have to use some axis label modification method, where I can modify manually that big number :/

**Comment by mrmime95** [comment]
Cool, thank you, exactly this is the solution to my probem :)
