### ISSUE TITLE
Radar Chart style problem

### ISSUE THREAD

**Issue by liorkatzdev** [amcharts/amcharts4#2639]
can i remove the 0% in the config? (or to do "hide" in some way)
![memory chart](https://user-images.githubusercontent.com/56354154/85947192-cf527a80-b951-11ea-87f4-7378f158fb10.png)

**Comment by martynasma** [comment]
Yeah:

```
xAxis.renderer.minLabelPosition = 0.1;
```

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Start_and_end_labels
