### ISSUE TITLE
iOS : Colored range display bug and export

### ISSUE THREAD

**Issue by Darcelsan** [amcharts/amcharts4#2640]
**Bug description**

I have two bugs on the typescript version of amCharts. 

First, when I try to export a chart displayed like that : 
![IMG_5EE1874ED6C5-1](https://user-images.githubusercontent.com/10349529/85990221-fc566a00-b9f1-11ea-8a91-3116a31b8841.jpeg)

My export looks like that : 
<img width="433" alt="Capture d’écran 2020-06-29 à 10 20 18" src="https://user-images.githubusercontent.com/10349529/85990335-2445cd80-b9f2-11ea-824f-8133078e6f4a.png">
The problem here is that the blue range is for 2 to -99 999 values and should not appears in my case, like in the first screenshot

With this problem I tried to update my amCharts npm package version (4.7.18 to last : 4.9.27) and I'm getting a new bug in the display with still the same problem on my export : 
![IMG_BBFAAAFCDDCD-1](https://user-images.githubusercontent.com/10349529/85990649-a0d8ac00-b9f2-11ea-8e4b-86899aff93aa.jpeg)

Export result : 
![image](https://user-images.githubusercontent.com/10349529/85991240-776c5000-b9f3-11ea-8f41-d39983388adb.png)

**Environment (if applicable)**

Ionic App in 4.7.1 version of Ionic, 8.1.2 version Angular, tested on iOS. On Android everything seems to be good

**Additional context**

If you need more info, feel free to ask me

**Comment by martynasma** [comment]
I'm gonna have to ask you for a reproducible case which we can run and test. You can post it on CodePen, StackBlitz, or similar service.

**Comment by Darcelsan** [comment]
> I'm gonna have to ask you for a reproducible case which we can run and test. You can post it on CodePen, StackBlitz, or similar service.

I don't know how I could do that as this bug is in an Ionic App, on iOS with very specific graph (XYChart with negative and positive colored ranges) and export function in png. How could I make you a working case ? 

Here is my graph generation function :
` generateGraph() {

    if (this.datalogging.measuresList && this.datalogging.measuresList.length > 1) {
      this.zone.runOutsideAngular(() => {
        am4core.options.minPolylineStep = 5;
        const chart = am4core.create('chartdiv', am4charts.XYChart);
        const lang = this.getLocalLanguage();
        chart.language.locale = lang.locale;
        chart.numberFormatter.language = lang;
        chart.dateFormatter.language = lang;

        // Add data
        chart.data = this.generateChartData();
        chart.dateFormatter.dateFormat = 'HH:mm:ss';
        chart.dateFormatter.inputDateFormat = 'yyyy-MM-DDTHH:mm:ss';
        chart.dateFormatter.dateFormat = 'i';
        chart.dateFormatter.utc = false;
        chart.background.fill = am4core.color('#1E1F20');

        // Create axes
        let dateAxis = chart.xAxes.push(new am4charts.DateAxis());
        dateAxis.renderer.minGridDistance = 70;
        const ampm = moment.locale() === 'en' ? 'a' : '';
        dateAxis.periodChangeDateFormats.setKey('hour', `${this.shortDateFormat} [bold]hh:mm`);
        dateAxis.renderer.grid.template.stroke = am4core.color('white');
        dateAxis.renderer.labels.template.fill = am4core.color('white');
        dateAxis.renderer.grid.template.hidden = false;
        dateAxis.renderer.grid.template.strokeOpacity = 0.2;
        dateAxis.baseInterval = {
          count: interval / 60,
          timeUnit: 'minute'
        };


        const valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
        valueAxis.renderer.grid.template.stroke = am4core.color('white');
        valueAxis.renderer.grid.template.strokeOpacity = 0.2;
        valueAxis.renderer.labels.template.fill = am4core.color('white');

        // Create series
        const series = chart.series.push(new am4charts.LineSeries());
        series.dataFields.valueY = 'values';
        series.dataFields.dateX = 'date';
        series.strokeWidth = 1;
        series.stroke = am4core.color('#00A78D');
        series.minBulletDistance = 10;
        series.connect = false;

        if (this.datalogging.alarms) {
          valueAxis.max = this.maxValue;
          valueAxis.min = this.minValue;
          const alarms = this.orderAlarms();
          for (let index = 0; index < alarms.length; index++) {

            if (alarms[index].alarmMode.alarmLowEnable) {
              const lowValue = alarms[index].lowLimitValue.measureFloat
              valueAxis.baseValue = lowValue;
              const range = valueAxis.createSeriesRange(series);
              range.value = lowValue;
              range.endValue = (index === 0) ? -99999 : alarms[index - 1].lowLimitValue.measureFloat;
              range.contents.stroke = am4core.color('#0035ff');
              range.contents.fill = am4core.color('#0035ff');
              range.contents.fillOpacity = (1 / (index + 1));
              // range.maxPosition = 2;
              // range.grid.above = true;

              const range2 = valueAxis.axisRanges.create();
              range2.value = lowValue;
              range2.grid.stroke = am4core.color('#0035ff');
              range2.grid.strokeWidth = 2;
              range2.grid.strokeOpacity = (1 / (index + 1));
              range2.grid.strokeDasharray = '3,3';
              // range2.grid.above = true;
              if (!this.zoomOnData && (isNullOrUndefined(valueAxis.min) || valueAxis.min > lowValue)) {
                valueAxis.min = lowValue;
              }
            }
            if (alarms[index].alarmMode.alarmHighEnable) {
              const highValue = alarms[index].hightLimitValue.measureFloat;
              const range = valueAxis.createSeriesRange(series);
              range.value = highValue;
              range.endValue = (index === 0) ? 99999 : alarms[index - 1].hightLimitValue.measureFloat;
              range.contents.stroke = am4core.color('#FF0000');
              range.contents.fill = am4core.color('#FF0000');
              range.contents.fillOpacity = (1 / (index + 1));
              // range.grid.above = true;
              this.alarmChart.push(range);

              const range2 = valueAxis.axisRanges.create();
              range2.value = highValue;
              range2.grid.stroke = am4core.color('#FF0000');
              range2.grid.strokeWidth = 2;
              range2.grid.strokeOpacity = (1 / (index + 1));
              range2.grid.strokeDasharray = '3,3';
              // range2.grid.above = true;
              if (!this.zoomOnData && (isNullOrUndefined(valueAxis.max) || valueAxis.max < highValue)) {
                valueAxis.max = highValue;
              }
            }

          }
        }




        // Add scrollbar
        const scrollbarX = new am4charts.XYChartScrollbar();
        scrollbarX.series.push(series);
        scrollbarX.background.fill = am4core.color('#000000');
        scrollbarX.thumb.background.fill = am4core.color('#FFFFFF');
        scrollbarX.startGrip.background.fill = am4core.color('#00A78D');
        scrollbarX.endGrip.background.fill = am4core.color('#00A78D');
        scrollbarX.stroke = am4core.color('#00A78D');
        chart.scrollbarX = scrollbarX;

        // Add cursor
        chart.cursor = new am4charts.XYCursor();
        chart.cursor.xAxis = dateAxis;
        chart.cursor.snapToSeries = series;
        this.chart = chart;
        this.dataloggingService.graph = this.chart;
        this.displayChart = true;
      });
    }

  }

  generateChartData() {
    const chartData = [];

    this.datalogging.measuresList.forEach(measure => {
      let value = measure.measureFloat;
      value = Math.round(value * 100) / 100;
      chartData.push({
        date: new Date(measure.date.timeStamp * 1000),
        values: value
      });
      if (isNullOrUndefined(this.minValue) || this.minValue > value) {
        this.minValue = value;
      }
      if (isNullOrUndefined(this.maxValue) || this.maxValue < value) {
        this.maxValue = value;
      }
    });

    return chartData;
  }

  orderAlarms(): AlarmInformation[] {
    let highAlarms: AlarmInformation[] = [];
    let lowAlarms: AlarmInformation[] = [];
    const alarms: AlarmInformation[] = [];

    this.datalogging.alarms.forEach(alarm => {
      if (alarm.alarmMode.alarmHighEnable) {
        highAlarms.push(alarm);
      }
      if (alarm.alarmMode.alarmLowEnable) {
        lowAlarms.push(alarm);
      }
    });
    highAlarms = highAlarms.sort((a, b) => b.hightLimitValue.measureFloat - a.hightLimitValue.measureFloat);
    lowAlarms = lowAlarms.sort((a, b) => a.lowLimitValue.measureFloat - b.lowLimitValue.measureFloat);
    for (let index = 0; index < this.datalogging.alarms.length; index++) {
      let alarm = new AlarmInformation();
      alarm.alarmMode = new AlarmMode();
      if (highAlarms[index] && highAlarms[index].alarmMode.alarmHighEnable) {
        alarm.alarmMode.alarmHighEnable = true;
        alarm.hightLimitDuration = highAlarms[index].hightLimitDuration;
        alarm.hightLimitValue = (JSON.parse(JSON.stringify(highAlarms[index].hightLimitValue)));
      }
      if (lowAlarms[index] && lowAlarms[index].alarmMode.alarmLowEnable) {
        alarm.alarmMode.alarmLowEnable = true;
        alarm.lowLimitDuration = lowAlarms[index].lowLimitDuration;
        alarm.lowLimitValue = (JSON.parse(JSON.stringify(lowAlarms[index].lowLimitValue)));
      }
      alarms.push(alarm);
    }

    return alarms;
  }`


For your information, this graph displays temperature with threshold for value below 2°C and value above 13°C

**Comment by martynasma** [comment]
I'm sorry but we'll need a clear way to reproduce it. It's hard to do that without being able to run, see actual data, etc.

Out of my experience, first thing to check would be the order of your data. Are all of the data items in ascending order?

**Comment by Darcelsan** [comment]
> I'm sorry but we'll need a clear way to reproduce it. It's hard to do that without being able to run, see actual data, etc.
> 
> Out of my experience, first thing to check would be the order of your data. Are all of the data items in ascending order?

The easiest way to reproduce it is to start a Ionic App with my previous code to generate a graph on iOS and export it. I can't do it on a CodePen or equivalent I think... I can give you data in json file if you want but yes, it's in ascending order on date.

**Comment by martynasma** [comment]
I'm terribly sorry, but debugging apps is way outside of scope of our support.

I strongly believe the issue is not with the framework, though. If you could somehow produce a reduced case demo with the issue, I'm sure we'd be able to figure out whether it's a problem of setup or a bug.

Hope you find it reasonable.

**Comment by Darcelsan** [comment]
I really can't make a full example on a CodePen, it's way too big and asks to be run on an iOS device.

But I found the problem and it comes from the simplifiedImageExport() function at the case 1. By deleting the line _ctx = canvas.getContext("2d");_ my export is now good.
Is this line really useful or it can be removed to fix this bug ?

<img width="431" alt="Capture d’écran 2020-06-30 à 11 47 57" src="https://user-images.githubusercontent.com/10349529/86111864-8cb2ae80-bac7-11ea-9023-7632a3955755.png">

**Comment by martynasma** [comment]
Well, you simply create an error which is caught by exception, and export then goes on to a canvg fallback.

You can do that less dramatically :)

```
chart.exporting.useSimplifiedExport = false;
```

**Comment by Darcelsan** [comment]
> Well, you simply create an error which is caught by exception, and export then goes on to a canvg fallback.
> 
> You can do that less dramatically :)
> 
> ```
> chart.exporting.useSimplifiedExport = false;
> ```

Thank you ! It's ok with this now !
