### ISSUE TITLE
Is it possible to have multiple links in the same label?

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2641]
I would like to be able to click on "Data One" or "Data Two" and be directed to different urls. Is there a way to do this with the text formatting or using textLink?

This is what I currently have:
```
var sourceLabel = chart.createChild(am4core.Label);
sourceLabel.text = "Source: Date one & Data Two";
sourceLabel.align = "right";
sourceLabel.interactionsEnabled = true;
sourceLabel.url = "https://data-one.html";
```

**Comment by martynasma** [comment]
You would need to use HTML label for that:

sourceLabel.html = '<a href="....">First link</a> .... <a href="....">Second link</a>';
```

**Comment by Josh10101010** [comment]
That's great, thanks.
