### ISSUE TITLE
Accessing evaluated data for series

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2642]
How would one access evaluated data? 

Such as ```series.dataItems.length```, ```series.dataItems.first.openValueY``` etc.

I was hoping to use open and close values with the length to calculate an annualised return which I would then display in the legend value label.

**Comment by martynasma** [comment]
`series.dataItems` will contain data items with evaluated data.

You can iterate through them if you need to make your own calculations, e.g.:

```
series.dataItems.each(function(item) {
  console.log(item.values);
});
```

**Comment by Josh10101010** [comment]
Thanks.

I can get to work when I run it inside the charts "ready" event. Is there an event that's triggered after the series data has been validated?
```
chart.events.on('ready', () => {
  series.dataItems.each(function(item) {
    console.log(item.values);
  });
};
```

For example if I wanted to do something like the below, but have set the text before the chart renders?
```
var range = series.dataItem.values.valueY.close - series.dataItem.values.valueY.open;
label1.text = range;
```

**Comment by martynasma** [comment]
Yes. You can use `datavalidated` event.

If you set data on chart, add listener on chart object. If you add it directly to series, add it to series.

**Comment by Josh10101010** [comment]
I have managed to calculate what I required, but setting the value to the series.legendSetting.valueText seems to have no effect, however if I set the value outside of the code block below it works.

This code is run within a function that creates the series.
```
series.events.on("datavalidated", function (ev) {
    var openValue = Math.floor(series.dataItem.values.valueY.open);
    var closeValue = series.dataItem.values.valueY.close;
    var periods = series.dataItem.values.valueY.count;
    var annualisedReturn = Math.pow((closeValue / openValue), (1 / (periods / 12))) - 1;

    series.legendSettings.valueText = (annualisedReturn * 100).toFixed(2) + "%";
});
```

**Comment by martynasma** [comment]
Yeah, just modifying `legendSettings` will not trigger any visual updates.

Try calling this after `legendSettings` is updated:

```
series.updateLegendValue();
```

**Comment by Josh10101010** [comment]
That doesn't seem to force an update, only resizing the chart causes the values to display.

**Comment by martynasma** [comment]
Hm, it does in my test:
https://codepen.io/team/amcharts/pen/937737c74462bd9dc8aaad6f8d589094?editors=0010

**Comment by Josh10101010** [comment]
https://codepen.io/Josh519/pen/NWxXRye

Could it be an issue with my legend container?

**Comment by martynasma** [comment]
Indeed, weird.

This seems to do the trick, though:

```
chart.legend.invalidate();
```
