### ISSUE TITLE
Grabbing zoomed data

### ISSUE THREAD

**Issue by alienbuild** [amcharts/amcharts4#2643]
I've searched the documentation and issues but haven't found a clear answer to this question so would be helpful to be pointed in the right direction.

I'm just about to get started with amcharts4 for a new project and I need the ability to create an XY chart and have the user click/drag a range to be zoomed in, which is fine and supported. However I need to be able to then capture that data and have the user submit it to an API. I haven't seen anywhere that it is possible to get the current data in the view that the user has selected. Is there a call back function that exists for this?

**Comment by martynasma** [comment]
You can watch cursor's `selectended` event, then iterate through series' data items and see what fits into the range. E.g. for the category axis:

```
chart.cursor.events.on("selectended", function(ev) {
  var range = ev.target.xRange;
  series.dataItems.each(function(dataItem) {
    var pos = categoryAxis.categoryToPosition(dataItem.categoryX);
    if (pos >= range.start && pos <= range.end) {
      // This data item is within selected range
      // ...
    }
  });
});
```

P.S. If you have a `DateAxis` you would need to use `dateToPosition()` and `dataitem.dateX` instead.
