### ISSUE TITLE
Cannot use toggable property to remove property applied on selected column using custom state

### ISSUE THREAD

**Issue by ashmichheda** [amcharts/amcharts4#2644]
Hello Amcharts team,

I am using a custom state ```selected``` to highlight a column of a chart on click. If I click on the same highlighted column again, I want the state of the highlighted column to be back to ```default``` state.
Since, the ```toggable``` property is disabled when we use custom state, how can I achieve this functionality?
Is there any column property I can use to achieve the same? 

Here is the [Reference Codepen Link](https://codepen.io/ashmichheda/pen/JjGOdqz?editors=0010)

Thanks,
Ashmi

**Comment by martynasma** [comment]
`togglable` is in no way disabled when using custom states. You can use `active` state to set how element looks like when it is toggled on:

```
columnSeries.columns.template.togglable = true;
var activeSate = columnSeries.columns.template.states.create("active");
activeSate.properties.fill = am4core.color("#E94F37");
activeSate.properties.fillOpacity = 0.8;
```

**Comment by ashmichheda** [comment]
Can I have custom as well as active state applied to columnSeries?

**Comment by martynasma** [comment]
Yes. But if both states set the same properties, the last one set will override the other.

**Comment by ashmichheda** [comment]
@martynasma - The problem here is: I am using a custom state, when I select on a column for the first time - it gets highlighted with the properties I have set on the ```customState```. 
Next time when I select on the highlighted column again it doesn't set the ```customState``` to default as written in the logic.

[Reference Codepen Link](https://codepen.io/ashmichheda/pen/JjGOdqz?editors=0010)

Can you please check the codepen link?

**Comment by martynasma** [comment]
Well, you'll need to modify your code to accommodate that. Right now it's set up so that state is being reset to default only when some other column is clicked, not when already selected column is clicked again.

You might want to log which column is currently selected in a global variable.

Or use toggling option like we discussed before.
