### ISSUE TITLE
Extract value from tooltip text

### ISSUE THREAD

**Issue by AlexandreKang** [amcharts/amcharts4#2645]
**Question**

I would like to get the text value from the tooltip. How can I get the text Canada in the tooltip if I hover on Canada?

For TypeScript/Angular/React use:
https://codesandbox.io/s/bold-cache-iknwo?file=/src/app/components/map/map.component.ts

**Environment (if applicable)**
 - amCharts version : 4
 - Browser and its version : Firefox dev edition 78.0b9
 - Related frameworks and their versions [Angular (10.0.0), TypeScript(3.9.5)]

![Screen Shot 2020-06-29 at 10 46 23 PM](https://user-images.githubusercontent.com/33300743/86077941-f0eb5900-ba5a-11ea-923a-12843152accf.png)

**Comment by martynasma** [comment]
Do you mean in an adapter?

```
polygonSeries.tooltip.adapter.add("textOutput", function(text, target) {
  // text == "Canada"
  return text;
});
```

**Comment by AlexandreKang** [comment]
I added what you suggest, but there is an error message:

`Argument of type '"textOutput"' is not assignable to parameter of type '"hidden" | "disabled" | "layout" | "fontWeight" | "fontSize" | "fontFamily" | "textDecoration" | "contentAlign" | "contentValign" | "fixedWidthGrid" | "maxColumns" | "reverseOrder" | ... 128 more ... | "showInViewport"'.ts(2345)`

Essentially, I want to have the value from the tooltip when I hove on a country.

**Comment by martynasma** [comment]
I'm terribly sorry, I made a typo. This is how it should be:

```
polygonSeries.tooltip.label.adapter.add("textOutput", function(text, target) {
  // text == "Canada"
  return text;
});
```
