### ISSUE TITLE
Low performance  when drawing a scatter plot with large data

### ISSUE THREAD

**Issue by saleemshenlin** [amcharts/amcharts4#2647]
**Bug description**

I need to draw a scatter plot with bullet.
the performance is low, sometimes the browser freezes. when rendering lots of bullets.
In particular, an x value corresponds to multiple y values.

this is the example : [https://stackblitz.com/edit/react-ts-amcharts](https://stackblitz.com/edit/react-ts-amcharts)
you can select the X and Y to change data

![Snipaste_2020-06-30_15-48-33](https://user-images.githubusercontent.com/3690320/86098779-2b9bd280-bae9-11ea-8727-b394342de1da.jpg)

**Environment (if applicable)**

 - amCharts version 4.9.28
 - Browser and its version Microsoft Edge Version 85.0.552.1 (Official build) dev (64-bit)
 - TypeScript, React, antd

**Comment by martynasma** [comment]
I'm afraid, plotting 9K points like that might put too much pressure on the chart. I'm not sure if there's anything that can be done to improve the performance of this chart considerably in current version. Sorry.

**Comment by saleemshenlin** [comment]
I did two optimizations. it become a little quicker.

1. use different series for each y value.

2.  use strictMinMax

I think you can do something more about that
