### ISSUE TITLE
Removing and adding heat rules dynamically

### ISSUE THREAD

**Issue by TheJhonny007** [amcharts/amcharts4#2648]
**Question**
Hi, I am triying to dynamically add and remove heatRules from a MapPolygonSeries. It works with things like bar charts, but if I remove the heatRule from a map it doesn't reset.

https://stackblitz.com/edit/js-tfyv5z

If you click on the map it should remove the heatRule and display a purple color.
Do I have to do something different?

**Environment**
amCharts: 4.9.28
Browser: Chrome  83.0.4103.116

**Comment by xorspark** [comment]
By default, property changes on the column template aren't propagated to the columns, as documented [here](https://www.amcharts.com/docs/v4/concepts/list-templates/#Propagating_template_changes). You can change this behavior by setting `applyOnClones` to true on the series column template, e.g. `series.columns.template.applyOnClones = true;`.

**Comment by TheJhonny007** [comment]
Thank you very much. Although I only needed to do that for the `mapPolygons.template`. The `columns.template` seems to work without enabeling that feature.
