### ISSUE TITLE
Sparkline Charts in version 4?

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/amcharts4#265]
Is there a sparkline chart tutorial on v4?

**Comment by manoj016** [comment]
See [this](https://codepen.io/immanoj16/pen/aaoMJz) if it is helpful for you.

**Comment by martynasma** [comment]
@manoj016 example is nice.

I also was meaning to do a sparklines/minicharts article, but haven't gotten around to it.

Basically creating a sparkline boils down to these tasks:

### Disabling axis grid and its labels

```
dateAxis.renderer.grid.template.disabled = true;
dateAxis.renderer.labels.template.disabled = true;

// ...

valueAxis.renderer.grid.template.disabled = true;
valueAxis.renderer.baseGrid.disabled = true;
valueAxis.renderer.labels.template.disabled = true;
```

### Removing all padding from the chart

```
chart.padding(0, 0, 0, 0);
```

### Tweaking other stuff

Like where axis starts and ends using `startLocation` and `endLocation`. Controlling bullets using `propertyFields`, etc.

Here's an example:
https://codepen.io/team/amcharts/pen/WgroVb/

Hope you find it useful.

**Comment by kevzlou7979** [comment]
Thanks @manoj016 and @martynasma - appreciate your help

**Comment by martynasma** [comment]
You're welcome!

I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by martynasma** [comment]
One more thing I forgot to mention.

### Disabling axis tooltips

```
dateAxis.cursorTooltipEnabled = false;
valueAxis.cursorTooltipEnabled = false;
```

**Comment by martynasma** [comment]
FYI:
https://www.amcharts.com/docs/v4/tutorials/creating-sparkline-charts/

**Comment by kevzlou7979** [comment]
Thanks
