### ISSUE TITLE
loading big data in chart very slow

### ISSUE THREAD

**Issue by JunjaK** [amcharts/amcharts4#2650]
**Question**

I am drawing a chart using line series and date axis, but it takes too much time to load for data over 80k. (24hour per second  data * n)
Since it is a project aimed at showing data completely, only the chart zoom and export are needed. 
There is no need for additional functions except mentioned above. 
Is there any way to improve performance?

I already read this doc, and I Apply to my project. Performance is a bit better, but it's still too slow to use.
(https://www.amcharts.com/docs/v4/concepts/performance/)

and I want to remove this screen when loading big data (when small data loading, this screen is not showing)
![image](https://user-images.githubusercontent.com/30404630/86231887-28c6dd80-bbce-11ea-9f74-678f58ec65ac.png)

**Environment (if applicable)**
amchart 4.9.13
vue 2.6.11
browser : chrome and edge

**Additional context**
license is applied in project

**Comment by martynasma** [comment]
Are you concerned about how long it takes the initial load? If that is the case, I'm afraid there's little that can be done besides what is listed in the tutorial you referred to.

You can disable the preloader like this:

```
chart.preloader.disabled = true;
```

**Comment by JunjaK** [comment]
Thank you for the reply!
Then,
Is there any way to improve performance by turning off other add-ons such as animations?

**Comment by martynasma** [comment]
Turning off animations might help with the chart speed, but not with the stage where data is parsed.

**Comment by JunjaK** [comment]
Thank you for your support... 
I'll find other ways

**Comment by JunjaK** [comment]
@ritesh2403  Nope. but I found another super fast chart.  

https://github.com/leeoniya/uPlot

If you want fancy chart like amchart using this uplot chart, needs complicate customize...
