### ISSUE TITLE
There is problem of download over 80k data through amchart export 

### ISSUE THREAD

**Issue by JunjaK** [amcharts/amcharts4#2651]
**Question**
I want to download a large amount of data through amchart export.   
For small data, I can download all formats such as pdf, xlsx, and json without any problems,  
but for data over 80k, an error occurs even when the time out of export is set for more than 50 seconds.   
(for data format of pdf, xlsx, json, csv / Image download has no problem)  
Is there a solution?

error is here
![image](https://user-images.githubusercontent.com/30404630/86306553-894a2f00-bc4f-11ea-892b-04b911bca50d.png)

and I applied this option 
```
chart.exporting.timeoutDelay = 50000
````

**Environment (if applicable)**
amchart 4.9.13
vue 2.6.11
browser : chrome and edge

**Additional context**
license is applied in project

**Comment by martynasma** [comment]
Do you mean even CSV export does not work?

**Comment by JunjaK** [comment]
Yes. even CSV export dose not work.

**Comment by martynasma** [comment]
I'm going to have to ask for a demo.

I just tried a simple chart with 100K data points:
https://codepen.io/team/amcharts/pen/1c1f645711788a587069660bc422b52f?editors=0010

The data exports just fine. XLSX might take a while (5-7 seconds in my case) to export 100K data points, but it still nothing close to failing out.

**Comment by JunjaK** [comment]
Thank you. 
I'll check demo and apply my project.

**Comment by JunjaK** [comment]
this might be our project problem. 
Thank you for your comment.,..
