### ISSUE TITLE
Putting marker tooltip on button click on the map in React

### ISSUE THREAD

**Issue by enggomarpu** [amcharts/amcharts4#2653]
Hello guys, 
Hope you are doing great, and in best of your health. 
I am trying to put marker tool-tip on map by button click. I am using **amCharts** So for I have able to get tool-tip on button click but the tool-tip shows near button not on the map marker or map polygon. I am doing all this in **REACT** so guide accordingly. 

```
triggerTooltip(code) {
    // let imagesLe = this.chart._series._values[1]._mapImages._values.length;
    let imageFind, polygonFind;
    this.chart._series._values[0]._mapPolygons._values.forEach((image) => {
      if (image._dataItem._dataContext.id === code) {
        polygonFind = image;
      }
    });
    this.chart._series._values[1]._mapImages._values.forEach((image) => {
      if (image._dataItem._dataContext.id === code) {
        imageFind = image;
      }
    });
    console.log(polygonFind);
    polygonFind.isHover = true;
    imageFind.isHover = true;
  }
```

**Comment by enggomarpu** [comment]
@martynasma any hint for this.? really struggling to get it right. In jquery it is so easy but in react i am scratching my head.

**Comment by martynasma** [comment]
Is the problem that the code does not find the polygon and/or image, or that setting `isHover` does not trigger the tooltip?

**Comment by enggomarpu** [comment]
tooltip appears but it does not appear on marker in the map, it appears on the cursor position .. and moves as cursor moves.
What i want on click, tooltip should appear on polygon or marker in the map  [
![image](https://user-images.githubusercontent.com/66190713/86370925-bc191500-bc99-11ea-8739-81cee0d78f77.png)
](url)

**Comment by martynasma** [comment]
Have you tried setting tooltipPosition?

```
polygonSeries.mapPolygons.template.tooltipPosition = "fixed";
```

**Comment by enggomarpu** [comment]
polygonSeries.mapPolygons.template.tooltipPosition = "fixed";  this is only available in componenetDidMount. I cannot access chart like this outside the componentDidMount. If this is possible, it would be quite easy to do the task. just 2 lines of code.

**Comment by martynasma** [comment]
That code needs to code next to your polygonSeries initialization code. Not on interaction.

**Comment by enggomarpu** [comment]
I understand your point. How will I listen button click in componentDidMount, with passing a value of "code" after rendering the component?

**Comment by martynasma** [comment]
I'm sorry, I don't follow. You create the whole map in `componentDidMount` I presume. I'm just saying you should add additional line of code there.

**Comment by enggomarpu** [comment]
You are genious man, I got your point now. Thanks for your help. I was thinking, it will be a silly mistake on my side. Thanks.

**Comment by martynasma** [comment]
No worries. Feel free to close the issue if/when ready.
