### ISSUE TITLE
MapLineSeries is not binding data to MapLineObject

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2654]
Hi. I am creating a line based on a multiGeoLine array and on the line I am showing a specific point. I am providing a very simple array of data for the `MapLineSeries` like this: ` lineSeries.data = [{name: 'Paris'}];`

On the point created on this line I expect to be able to read the data like it's working on an `MapImageSeries` case but for some reason the data is not available for this case...
![image](https://user-images.githubusercontent.com/37619567/86329954-9ff08600-bc4f-11ea-8f4d-8a426ad82d27.png)

The tooltip text is added like this: `rectangle.tooltipText = 'The name is: {name}';` but the `name` property is not available on runtime.

I've set up a codePen for a better understanding.
https://codepen.io/directcuteo/pen/WNrdNmJ

**Comment by martynasma** [comment]
An object attached to a line (via `lineObjects`) does not inherit line's data items, and thus placeholders do not resolve from line data.

Frankly, I'm not sure how to go about it, besides just adding the name directly to the `tooltipText` of the Rectangle.

**Comment by directcuteo** [comment]
I wil try then some workarounds... What's interesting is that MapLineSeries has a `data` array field to it and still you're saying that the lineObjects don't inherit this data..
