### ISSUE TITLE
Updating to Angular 10 and get warning "CommonJS or AMD dependencies can cause optimization bailouts"

### ISSUE THREAD

**Issue by haileymesserfs** [amcharts/amcharts4#2656]
Hi everyone, so I am updating the project to Angular 10, then I got these warnings and more. 

> WARNING in C:\Users\xxx\Documents\dashboard\node_modules\@amcharts\amcharts4\.internal\canvg\index.js depends on core-js/modules/es.array.map. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

>WARNING in C:\Users\xxx\Documents\dashboard\node_modules\@amcharts\amcharts4\.internal\canvg\index.js depends on core-js/modules/es.reflect.get-prototype-of. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

>WARNING in C:\Users\xxx\Documents\dashboard\node_modules\@amcharts\amcharts4\.internal\canvg\index.js depends on core-js/modules/es.reflect.apply. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

>WARNING in C:\Users\xxx\Documents\dashboard\node_modules\@amcharts\amcharts4\.internal\canvg\index.js depends on core-js/modules/es.map. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

I know I can add `"allowedCommonJsDependencies": [ ]` in angular.json to hide the warnings, but there are a lot and according to Angular, depending on CommonJS modules  results in larger bundle sizes. Any idea how to solve this?

Below is my dependencies:
```
"dependencies": {
    "@amcharts/amcharts4": "^4.9.28",
    "@angular/animations": "~10.0.1",
    "@angular/cdk": "^10.0.0",
    "@angular/common": "~10.0.1",
    "@angular/compiler": "~10.0.1",
    "@angular/core": "~10.0.1",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~10.0.1",
    "@angular/material": "^10.0.0",
    "@angular/platform-browser": "~10.0.1",
    "@angular/platform-browser-dynamic": "~10.0.1",
    "@angular/router": "~10.0.1",
    "@aspnet/signalr": "^1.1.4",
    "@okta/okta-angular": "2.0.0",
    "@servicestack/client": "^1.0.31",
    "ag-grid-angular": "^23.2.1",
    "ag-grid-community": "^23.0.1",
    "ag-grid-enterprise": "^23.0.1",
    "core-js": "^3.6.5",
    "moment": "^2.24.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular/cli": "~10.0.0",
    "@angular/compiler-cli": "~10.0.1",
    "@angular/language-service": "~10.0.1",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
```

**Additional context**

**Comment by Pauan** [comment]
@haileymesserfs This is because the `core-js` npm package [does not use ES6 modules](https://github.com/zloirock/core-js/issues/385).

But `core-js` is only used by `canvg`, and `canvg` is *not* included in the bundle, it is loaded separately on-demand only when it is used. So you can safely ignore the warnings, because it will not affect your bundle size.

**Comment by haileymesserfs** [comment]
I see. Thank you for your reply :)

> @haileymesserfs This is because the `core-js` npm package [does not use ES6 modules](https://github.com/zloirock/core-js/issues/385).
> 
> But `core-js` is only used by `canvg`, and `canvg` is _not_ included in the bundle, it is loaded separately on-demand only when it is used. So you can safely ignore the warnings, because it will not affect your bundle size.
