### ISSUE TITLE
How to zoom to default period only when request is done

### ISSUE THREAD

**Issue by fisherspoon** [amcharts/amcharts4#2657]
Good afternoon, I have a schedule with periods (1 day, 7 days, 1 month, 1 year).
There is data that is downloaded from the server, I want to make the request be made with the maximum period at the beginning of the page loading, and by clicking on the desired period the schedule was rebuilt with the help of the ZOOM.

But I ran into a problem, how to make the chart not drawn right after the request, and at the end I would do the ZOOM to the default value I needed, for example, 7 days?

A request is made with a maximum period, the chart is not drawn
`chart.dataSource.url = "/rates/get-archive?period=year"`

Only after the data has been downloaded, execute the ZOOM
`      chart.dataSource.events.on("done", function(ev) {
                var one_week = moment(_tomorrow).subtract(7,'d').format('YYYY-MM-DD');
                zoomMove(_tomorrow, one_week);
            });`

**Comment by martynasma** [comment]
I suggest to use chart's `datavalidated` event instead:

```
chart.events.on("datavalidated", function(ev) {
  if (chart.data.length > 0) {
    var one_week = moment(_tomorrow).subtract(7,'d').format('YYYY-MM-DD');
    zoomMove(_tomorrow, one_week);
  }
});
```

`done` event in `dataSource` indicates that data has been loaded and passed on to chart, but it doesn't mean that the chart has finished parsing it, so it's safer to use chart's events.
