### ISSUE TITLE
How to make an image fill all it's parent container dimensions

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2658]
Hi. I am trying to simulate a 'background-image' behaviour for a Container.
I have created inside my container an `Image` element and I would like it to cover the entire width and height of it's parent `Container`.
Unfortunately this is not working well and I can't find a way to fit the dimensions.

My code:
```
   const cont = this.map.chartContainer.createChild(Container);
        cont.height = 300;
        cont.width = 250;
        cont.layout = 'absolute';

  const backImg = cont.createChild(Image);
        backImg.height = percent(100);
        backImg.width = percent(100);
        backImg.href = 'myimage.jpg';
        backImg.align = 'center';
```

**Result:**
![image](https://user-images.githubusercontent.com/37619567/86348232-0bdee880-bc68-11ea-9516-6753c6f8312c.png)

It would be great to make the image zoomed so that the entire area is covered. (like a CSS `object-fit: cover`)

**Comment by directcuteo** [comment]
Any suggestions on this? :/
Unfortunately setting an `overflow: hidden` on the parent container is not working because the container will grow to fit the image.
If container has 200px width and the image has 300px, then the container will have also 300px which seems wrong.

**Comment by zeroin** [comment]
I've managed to do it by setting preserveAspectRatio:

`backImg.element.attr({preserveAspectRatio: "xMidYMid slice"})`

and updating width/height to the same number:

https://codepen.io/team/amcharts/pen/4c2961af49436344d43757fb029aac61?editors=0010
