### ISSUE TITLE
Tooltip doesn't stick with it's element when zooming the map

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2660]
Hello!
I am showing a tooltip on a plane and when I click on the plane I want the tooltip to stay open, for this I am using (on `hit` event) `plane.showTooltipOn = 'always';`. When I click on the plane, I also zoom in the map to focus the plane's route area.
Somehow, the tooltip does not stick with the plane and it's position seems to be absolute to the chart and not plane's position in the chart... 
Any suggestions on my problem?

**Before I click, all good**
![image](https://user-images.githubusercontent.com/37619567/86446804-1d35fc80-bd1d-11ea-8501-7f61a3ead691.png)

**After I click, the tooltip stays on as I expect, but it doesn't react well to the zoom**
![image](https://user-images.githubusercontent.com/37619567/86447122-8ae22880-bd1d-11ea-81eb-d5d9cb4d4c9e.png)

The zoom is activated through the code, not by the user.
`this.map.zoomToRectangle(north + 3, east + 3, south - 3, west - 3, 1, true, 1500);`

The tooltip follows the plane well if the user zooms in, but that's not this case.

**Comment by martynasma** [comment]
The following should fix this:

```
this.map.events.on("mappositionchanged", function() {
  plane.showTooltip();
})
```

**Comment by directcuteo** [comment]
I see that this is not working for the case when the map is moved/draged.
The 'mappositionchanged' event is called, but the tooltip does not follow it's parent.

**Comment by martynasma** [comment]
It does for me. Can you post your actual map on CodePen so that I can take a look?

**Comment by directcuteo** [comment]
CodePen demo: https://codepen.io/directcuteo/pen/NWNqOvZ

**Comment by martynasma** [comment]
I'm not getting any tooltips or animations in your CodePen. Am I missing something?

![image](https://user-images.githubusercontent.com/1458520/89787547-50428b80-db26-11ea-80a6-ad7c36f30c5e.png)

**Comment by directcuteo** [comment]
I think there's something wrong with CodePen. Try add a space somewhere in the code so CodePen recompiles the code.

**Comment by martynasma** [comment]
I don't think that changes anything. Does it work for you?

**Comment by directcuteo** [comment]
Try to refresh it until it appears. I can't explain why it's doing this.

**Comment by martynasma** [comment]
I did. Nothing's happening.

If you suspect it's CP's fault, maybe try jsFiddle or some other tool out there?

**Comment by directcuteo** [comment]
JSFiddle: https://jsfiddle.net/hwkybgv3/
Try hit RUN until it works. For me it works on first attempt. Sorry for the trouble..

**Comment by zeroin** [comment]
Try setting the tooltip on the imageSeriesTemplate instead of a Rectangle, it should work fine.
