### ISSUE TITLE
How to hide custom preloader

### ISSUE THREAD

**Issue by fisherspoons** [amcharts/amcharts4#2661]
Good afternoon, I looked at your examples with a custom preloader, the only thing I can’t understand is how to show it during a request and then hide it at the end.
https://codepen.io/team/amcharts/pen/JeXLrb/

` var indicator;`

function showIndicator() {
                    indicator = chart.tooltipContainer.createChild(am4core.Container);
                    indicator.background.fill = am4core.color("#fff");
                    indicator.background.fillOpacity = 0.8;
                    indicator.width = am4core.percent(100);
                    indicator.height = am4core.percent(100);
                    var indicatorLabel = indicator.createChild(am4core.Label);
                    indicatorLabel.align = "center";
                    indicatorLabel.valign = "middle";
                    indicatorLabel.fontSize = 20;
                    indicatorLabel.dy = 50;
                    var hourglass = indicator.createChild(am4core.Image);
                    hourglass.href = "https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-160/hourglass.svg";
                    hourglass.align = "center";
                    hourglass.valign = "middle";
                    hourglass.horizontalCenter = "middle";
                    hourglass.verticalCenter = "middle";
                    hourglass.scale = 0.7;
                }

`chart.dataSource.url = "https://some_data`
`chart.events.on("datavalidated", function(ev) {
    showIndicator();
});`

**Comment by martynasma** [comment]
Probably best to use data loader's event for that:

```
chart.dataSource.events.on("started", showIndicator);
chart.events.on("datavalidated", hideIndicator);
```

**Comment by fisherspoons** [comment]
Hi, but how to remove or hide the preloader element?
indicator.remove?

**Comment by martynasma** [comment]
To completely destroy and remove an element you call its `dispose()` method.

If you just want to hide element, you call its `hide()` method. You can show such hidden element later on using `show()` method.

Hope that makes sense.

**Comment by fisherspoons** [comment]
Thanks a lot!
