### ISSUE TITLE
DateAxis on line chart is incorrect

### ISSUE THREAD

**Issue by rolandasj** [amcharts/amcharts4#2664]
If there is 2 points in line chart and the date is ordered in ascending order and the date is difference is more than 1 day, the data displayed is incorrect.

This does not work (**ascending** order)
2018-01-**01**
2018-01-**03** 

This works
2018-01-**01**
2018-01-**02**

This works (ordering in **descending** solves the issue)
2018-01-**03**
2018-01-**01**

https://codepen.io/rolandas-janulis/pen/qBbxQLw?editors=1010

**Comment by zeroin** [comment]
You should not use descending order. You need set `baseInterval` manually in order to solve the issue:

`dateAxis.baseInterval = {timeUnit:"day", count:1}`

**Comment by rolandasj** [comment]
> You should not use descending order. You need set `baseInterval` manually in order to solve the issue:
> 
> `dateAxis.baseInterval = {timeUnit:"day", count:1}`

Yes, that would solve the issue, however that would force the interval to be 1 day for all data. Since the data differs, it could be months and years, and sometimes only 2 points - scenario as such.
The default baseInterval works great, so i would avoid overriding it.

Is overriding baseInterval the only option to fix this? Why descending order is a no go? Everything seems to work as usual including fixing this part as well.

**Comment by zeroin** [comment]
Descending order works with two points by pure luck, it's a strict no, the chart will not work properly.
In your case, when you have two data points with a gap being equal to two days, the chart choses baseInterval to be:

`dateAxis.baseInterval = {timeUnit:"day", count:2}` 

and then it rounds the dates to 2, 4...

So yes, overriding base Interval is the only 100% way to fix this.
