### ISSUE TITLE
Labels for node links for force-directed trees

### ISSUE THREAD

**Issue by hau-zy** [amcharts/amcharts4#2665]
Hi,

I would like to add labels (not tooltip) to node links, couldn't find any documentation on this. If there is a sample solution would someone be able to point me to it. Otherwise, is there anyway this can be achieved?

Thanks! :) @martynasma

**Comment by martynasma** [comment]
No simple solution, I'm afraid.

**Comment by hau-zy** [comment]
Alright thanks!
