### ISSUE TITLE
Export icon in amcharts not showing properly.

### ISSUE THREAD

**Issue by Sanky-Shelar** [amcharts/amcharts4#2666]
I have used 
chart.exporting.menu = new am4core.ExportMenu();
to export menu option but hovering on my export icon showing bullet like field.
Kindly help.
![ExportIsuue](https://user-images.githubusercontent.com/67903291/86586186-21744b00-bfa5-11ea-8901-85f17f430b81.PNG)

**Comment by martynasma** [comment]
I suppose there's some interference from the CSS on your web page.

You can investigate it using browser's developer tools to determine which CSS rules do that, and make necessary modifications to your CSS. It's always best to limit CSS queries to the narrowest scope possible to limit such conflicts.
