### ISSUE TITLE
How to change number format to indian numbering system.

### ISSUE THREAD

**Issue by Sanky-Shelar** [amcharts/amcharts4#2667]
Hi,

i want to change my comma format to this format.
eg -1,22,22,234  
how can it be done.

**Comment by martynasma** [comment]
I'm afraid formatting numbers like that is not supported. Sorry.

**Comment by Sanky-Shelar** [comment]
hi

cant we use this
chart.numberFormatter.intlLocales = "de-AT";
to change number formats.

**Comment by martynasma** [comment]
Changing locale just applies pre-set number/date formats and translations. It does not any new formatting capabilities.

So, no :(

**Comment by ShekharSahu** [comment]
Is the support available now?
