### ISSUE TITLE
XY chart´s series slow with Label Bullets

### ISSUE THREAD

**Issue by marcustavora** [amcharts/amcharts4#2668]
I have a XY chart with 24 bars (Hour category) and in each bar has 8 stacked series.
When I use label bullet in all series, the chart turns slow to renderize.

I´m creating the label bullet as the following:
let labelBullet = series.bullets.push(new am4charts.LabelBullet());

I faced the same problem when I tried to put Label Bullet in a Amcharts codepen

**Comment by martynasma** [comment]
Have you tried using `am4core.Label` instead of `am4charts.LabelBullet`?

Plain label is much less complicated element than bullet and should be faster.

If it's still a no go, maybe you can post your chart on CodePen, so that we can take a look?

**Comment by marcustavora** [comment]
@martynasma I tried using am4core.label but it still slow.
If possible, take a look in my CodePen [https://codepen.io/marcustavora/pen/ExPEQNK]
When I remove all series label, works smoothly

**Comment by martynasma** [comment]
I'm afraid there's little that can be done, besides disabling animations.
