### ISSUE TITLE
Is there a way to remove the gridlines in a chart?

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/amcharts4#267]
Hi There can we hide or remove the grid line backgrounds of a chart. 
Indicated the red arrows in the image below.
![image](https://user-images.githubusercontent.com/3138071/44516332-649ddb80-a6f7-11e8-8d60-612482b354e2.png)

**Comment by RaedsLab** [comment]
In your axes config try this : 

```js
renderer: {
              grid: {
                disabled: true
              }
            }
```

**Comment by kevzlou7979** [comment]
I tried it, and it works only on valueAxis not on category axis
![image](https://user-images.githubusercontent.com/3138071/44518710-8c903d80-a6fd-11e8-8506-2116ebbfe2ff.png)

**Comment by kevzlou7979** [comment]
Tried this
```
valueAxis.renderer.grid.push(new am4charts.Grid()).disabled = true;
```

**Comment by martynasma** [comment]
Yes:

```
categoryAxis.renderer.grid.template.disabled = true;
valueAxis.renderer.grid.template.disabled = true;
```

BTW, I noticed you are asking a lot of questions that are addressed in the docs ;)

The above, for example, is here:
https://www.amcharts.com/docs/v4/concepts/axes/#Disabling_certain_elements

Not that we're not glad to point you in the right direction, but you would probably get it done faster.

Just sayin' ;)
