### ISSUE TITLE
 When exporting to PDF, I don't want to see what happens when I mouse over.

### ISSUE THREAD

**Issue by wkdaudwn11** [amcharts/amcharts4#2670]
```
chart.exporting.menu = new am4core.ExportMenu();
```
I am using the function to export to PDF using the above code.

When exporting, it takes a little loading time. If you hover over the chart at this time, the exported PDF will show the mouse over. Can't you make this invisible?

Below is a captured photo of the pdf I exported.
![스크린샷 2020-07-07 오후 3 47 01](https://user-images.githubusercontent.com/26559413/86730151-30243600-c069-11ea-805b-6d401240bada.png)

**Comment by martynasma** [comment]
Technically, cursor should not be exported. However, you might still try disabling cursor before export starts:

```
chart.exporting.events.on("exportstarted", function() {
  chart.cursor.disabled = true;
});

chart.exporting.events.on("exportfinished", function() {
  chart.cursor.disabled = false;
});
```

**Comment by wkdaudwn11** [comment]
thanks!!!
