### ISSUE TITLE
Gauge Chart can't Show in Firefox

### ISSUE THREAD

**Issue by hastiningrat** [amcharts/amcharts4#2671]
i have problem with gauge chart, it can show well in chrome but not in firefox. like below :

in Google Chrome
[
![chrome](https://user-images.githubusercontent.com/8059756/86743734-4e873300-c063-11ea-9d0e-661edac643e5.JPG)
](url)

in Firefox
![Firefox](https://user-images.githubusercontent.com/8059756/86743930-71194c00-c063-11ea-9879-332f3ae4fb08.JPG)

What i should do to solve it?
thank you.

**Comment by martynasma** [comment]
Looks like chart container is too small. Try verifying it in browser's developer console by inspecting the chart element.

If it's indeed to small, you will need to work on your CSS to fix it.

**Comment by hastiningrat** [comment]
i was solving the issue with removing row class and col class in html which
is container for the chart,

thank you
