### ISSUE TITLE
LineSeries shrank 

### ISSUE THREAD

**Issue by liorkatzdev** [amcharts/amcharts4#2672]
on the ran my chart shrinks, 
checked and there is no dot behind that can make that behavior,
do i need to config one of the chart properties?

regular:
![regular](https://user-images.githubusercontent.com/56354154/86749831-3654eb00-c046-11ea-9500-80f415c6899f.png)

when shrink:
![shranked](https://user-images.githubusercontent.com/56354154/86749884-3fde5300-c046-11ea-926f-b1aa87762748.png)

**Comment by martynasma** [comment]
Check if your data items are in ascending order.

If they are and still seeing the issue, please post your chart on CodePen or jsFiddle for us to check.

**Comment by liorkatzdev** [comment]
I also notice that I get an error, maybe its related:
![error](https://user-images.githubusercontent.com/56354154/86786541-cdcd3480-c06c-11ea-8044-222ef08b42d9.png)

**Comment by martynasma** [comment]
We'll need a way to reproduce this somehow. Please consider posting your chart online where we can check it.

**Comment by liorkatzdev** [comment]
This chart gets real-time data, have 1 dateAxie and 2 valueAxies , and each Series are one line at the chart,
what is your recommendation for configuration chart and axies?

**Comment by martynasma** [comment]
I'm not sure how to answer that :)

If you need two ValueAxis and one DateAxis, then that is how chart needs to be set up.

If you could find a way for us to reproduce this behavior, we'd be happy to take a look.

**Comment by liorkatzdev** [comment]
Tried to put the data and the series but could not remake the problem,
that behavior happens probably only with live data ,
I tried to give a solution  by changing the min date each run

**Comment by martynasma** [comment]
Let us know if you find a way to reproduce this.
