### ISSUE TITLE
 Will the amchart logo at the bottom left disappear after payment?

### ISSUE THREAD

**Issue by wkdaudwn11** [amcharts/amcharts4#2673]
I am using amchart well. Thank you for your quick response and thank you very much.

I don't want to see the logo on the bottom left. Does it disappear when I pay? How do I pay?

And how do I apply it to the code after I pay?

And what is the pricing policy?

**Comment by martynasma** [comment]
Hi there. Purchasing a commercial license gives you right to disable amCharts logo.

You can purchase it via our online store:
https://www.amcharts.com/online-store/

Once order is through, you will receive further instructions on how to do so.

The above page also reviews various types of licenses.

If you have any further license-related questions, you are welcome to contact us at contact@amcharts.com
