### ISSUE TITLE
Zooming behaviour on XY chart

### ISSUE THREAD

**Issue by r-s-sandbox** [amcharts/amcharts4#2674]
I have noticed some erratic behaviour when zooming on XY chart. Here is a video that shows the problem

![47imdh](https://user-images.githubusercontent.com/43778016/86800133-9bbad300-c06a-11ea-873f-e35f2cd2977d.gif)

1) At times the lineseries dissapears upon zooming in
2) Selecting the zoom bounds does a best approximation when rendering the zoomed in view

Is it possible to restrict the zoom bounds to the selection via a config?

**Comment by martynasma** [comment]
That behavior might be due to data items not being ordered in ascending order.

Please verify if this is not the case.
