### ISSUE TITLE
ValueAxis, last label doesn't reflect valueAxis.max

### ISSUE THREAD

**Issue by iamtomhanks** [amcharts/amcharts4#2676]
I have `valueAxis.strictMinMax = true;`

When dynamically setting the max on the valueAxis, here is what it looks like:
![Screenshot from 2020-07-07 13-25-14](https://user-images.githubusercontent.com/18446243/86820205-b6834c80-c056-11ea-840c-69000a3024c0.png)

Below I statically set it to '200,000' and '199,999'. The graph doesn't respect the 199,999 and shows the label as '200,000'.

![Screenshot from 2020-07-07 13-26-29](https://user-images.githubusercontent.com/18446243/86820201-b5eab600-c056-11ea-97dc-f180c138323d.png)
![Screenshot from 2020-07-07 13-26-06](https://user-images.githubusercontent.com/18446243/86820203-b5eab600-c056-11ea-9d85-937ad062c95e.png)

Is there a way to get the valueAxis label to respect the max value set, for the last label on the axis?

**Comment by iamtomhanks** [comment]
I also want the columns/charts to be 100% height of the container, no matter how many series there are in the column or the sequencing of the valueAxis.

**Comment by martynasma** [comment]
`min` and `max` settings regulate axis scale, but not grid or labels.

Those are still are placed at regular increments.

If you need labels placed at some arbitrary values like 199999, you can use axis ranges:

https://www.amcharts.com/docs/v4/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/

**Comment by iamtomhanks** [comment]
@martynasma Exactly what I was looking for, thanks very much!

**Comment by iamtomhanks** [comment]
Now unfortunately I can't get the stacked column charts to be 100% height. Is there a way to set this?

![Screenshot from 2020-07-08 15-25-37](https://user-images.githubusercontent.com/18446243/86961698-a4291180-c12f-11ea-9424-5770520e7555.png)
![Screenshot from 2020-07-08 15-27-04](https://user-images.githubusercontent.com/18446243/86961700-a4c1a800-c12f-11ea-917e-075bdfc7a136.png)

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by iamtomhanks** [comment]
@martynasma Ok, will do.
