### ISSUE TITLE
ForceDirectedTree - links of children nodes disappears when hidden

### ISSUE THREAD

**Issue by hau-zy** [amcharts/amcharts4#2678]
Hi,

Would like to ask if it is possible to display links of children nodes when they are hidden? 

Something like this:
Initial (A--A1--B) , and after child node is hidden( A--B).

Or, if it is possible to hide only non-linked children nodes?

Thanks!

**Comment by martynasma** [comment]
No, I'm afraid that is not possible. Sorry.
