### ISSUE TITLE
data sort not working

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#2679]
it's not working when we parse the a,b then only it work

function ascendingSort(a, b) {
               // return a - b;
                if (parseInt(a.Values) < parseInt(b.Values)) {
                    return -1;
                }
                if (parseInt(a.Values) > parseInt(b.Values)) {
                    return 1;
                }
                return 0;
            }

_Originally posted by @Mahisandy in https://github.com/amcharts/amcharts4/issues/1418#issuecomment-655403653_

**Comment by martynasma** [comment]
Sounds like issue with your code/data, which is a bit out of scope.

The following article will help you understand how array sorting works in JavaScript:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
