### ISSUE TITLE
Change ValueAxis position from left to right?

### ISSUE THREAD

**Issue by RaedsLab** [amcharts/amcharts4#268]
The value axes is by default on the left of the chart. 

Is there a way to place it on the right ?

https://codepen.io/anon/pen/BONvKJ

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **38916**.
> (replying here will automatically notify amCharts support agent)

Hi there,

Yes there is. You have to set the value axis' `opposite` property to true in its `renderer`:

```
valueAxis.renderer.opposite = true;
```

Demo: https://codepen.io/team/amcharts/pen/1f2e8a07c2230855b58c2cb3d50b3eef/?editors=0010

I hope this helps.

Best,

Anthony Piris
amCharts

**Comment by RaedsLab** [comment]
Thank you, works perfectly !

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **38916**.
> (replying here will automatically notify amCharts support agent)

You're welcome! Glad to help.

Best,

Anthony Piris
amCHarts
