### ISSUE TITLE
data sort not working

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#2681]
Need to show acceding or descending 
https://codepen.io/team/amcharts/pen/QXmRxp?&editable=true

**Comment by martynasma** [comment]
You're comparing country names. Shouldn't you be comparing values?

```
function compare( a, b ) {
  if ( a.visits < b.visits ){
    return -1;
  }
  if ( a.visits > b.visits ){
    return 1;
  }
  return 0;
}
```
