### ISSUE TITLE
Documentation on ticks is misleading if not just wrong

### ISSUE THREAD

**Issue by coltonw** [amcharts/amcharts4#2683]
**Bug description**

Under AxisRenderer, the documentation for ticks is as follows:
> A list of Axis' Tick elements.
> 
> Please note that these are disabled by default. To enable them, set template to true.
> Typescript / ES6
> `categoryAxis.renderer.ticks.template.disabled = false;`

After hours of frustration, a coworker figured out that the ACTUAL way to turn on ticks is to set strokeOpacity to 1:
https://codepen.io/coltonw/pen/PoZejOr

As a bonus, the text of "set template to true" doesn't really make any sense and is also wrong.

**Environment (if applicable)**

amCharts 4
Chrome 83.0.4103.116

**Comment by martynasma** [comment]
Thanks for the heads up! And sorry for the confusion.

At some point we have changed default `strokeOpacity` of the ticks, and the docs did not catch up.

We're updating the docs as we speak.
