### ISSUE TITLE
 I want to adjust the value that goes into the Tooltip.

### ISSUE THREAD

**Issue by wkdaudwn11** [amcharts/amcharts4#2685]
Basically, the tooltip seems to be able to control only the values ​​entered in the chart as shown in the code below.
```
series.tooltipText = '{name}:{value}'
```

But I want to display the tooltip with data that is not in the chart.
For example, I drew the values ​​with percentage data in the chart, but I want to display the absolute values ​​in the Tooltip.

Absolute value example: 92832 <- I want to mark this on the Tooltip.
Percent example: 0.78    <- This enters the chart

The mapping value of each other is a date.

I did a lot of searches, but I didn't think it could be done with the Tooltip provided by default, so I solved it with the Info box.
https://www.amcharts.com/docs/v4/tutorials/custom-static-multi-value-tooltip/

Like the Info box, can I enter the values ​​into the Tooltip regardless of the chart?

Also, if there are multiple series of tooltip boxes, can you fix the order of showing tooltips according to the sequence of the series?

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
