### ISSUE TITLE
 Two Export menus open at the same time. Is it possible to open them separately?

### ISSUE THREAD

**Issue by wkdaudwn11** [amcharts/amcharts4#2686]
![스크린샷 2020-07-09 오후 7 07 24](https://user-images.githubusercontent.com/26559413/87027077-964ebb80-c217-11ea-8e62-efb0d34ccf78.png)

In the screenshot above, there are two line charts on one screen. 
The dom id of the above line chart is test1, and the bottom line chart is test2, so the IDs are different.

However, if you mouse over the Export menu button on the line chart above, the menu button on the line chart below will also open.

Can't it be opened separately?

**Comment by martynasma** [comment]
That shouldn't be like this this. Here's a basic two-chart setup with menus opening separately:

https://codepen.io/team/amcharts/pen/8d281fb82dfa67c8aa74ee873991814a?editors=0010

Can you post your setup?
