### ISSUE TITLE
Can you set the bars in a stacked column chart to be 100%?

### ISSUE THREAD

**Issue by iamtomhanks** [amcharts/amcharts4#2687]
Is there a way to get the stacked column charts to be consistently 100% height of the chart, and container. Is there a way to set this? This might not make sense if you had more than one column. But I want to show just one stacked column, so from a UI point of view, it would be nice if it could be 100% height, regardless of the data passed to the chart.

![Screenshot from 2020-07-08 15-25-37](https://user-images.githubusercontent.com/18446243/86961698-a4291180-c12f-11ea-9424-5770520e7555.png)
![Screenshot from 2020-07-08 15-27-04](https://user-images.githubusercontent.com/18446243/86961700-a4c1a800-c12f-11ea-917e-075bdfc7a136.png)

The second image above is me using the Chrome Inspector to illustrate that there is available space in either the chart or container elements. The graph on the right is 100% height. Maybe since there were more series, it decided to stretch?

**Comment by martynasma** [comment]
You might need to do this:
https://www.amcharts.com/docs/v4/chart-types/xy-chart/#100_stacks

Alternative solution would be to set `max` on your `ValueAxis` to the total sum of your stacked values, as well as `strictMinMax = true`.

**Comment by iamtomhanks** [comment]
Great, I will try it, thanks. 

I feel like I tried the alternative, but since I'm using ranges, which I didn't bring that info from the other thread, the max on the valueAxis gets overwritten. Or that's how it seemed anyway.

**Comment by martynasma** [comment]
Ranges should not affect axis scale.

**Comment by iamtomhanks** [comment]
Not sure I have the correct terminology. But when I added ranges, the axis labels were a separate set of labels underneath. I guess the axis scale doesn't change. 

But in my experimentation before, without ranges, the stacked column chart will not be 100% height reliably

**Comment by martynasma** [comment]
The last axis label is added by a range?

**Comment by iamtomhanks** [comment]
If not using ranges (If I don't want an explicitly set max value on the axis) , the last axis label, is not reliable to be there. The axis rounds the max value even with strictMinMax set. 

But, let's say I want my max value axis label to be, the total of the stacked column chart, you advised ranges. But then the chart being 100% height isn't reliable.

**Comment by iamtomhanks** [comment]
If you are suggesting that only the last label is produced by a range, that seems like it may work.

But sometimes the chart, without ranges, produces a last label, sometimes not. Would that be addressable?

**Comment by martynasma** [comment]
I'm going to need some point of reference in order to be able to answer that.

Can you post a CodePen of your chart. One that does not show a label where it should?

**Comment by iamtomhanks** [comment]
Yeah sorry about that, definitely easier to start there, with a CodePen. I forked one of your CodePens and I think it should illustrate the idea. The y-axis stops labelling before the bars stops. 

https://codepen.io/ToysInTheAttic/pen/yLeqjjX

**Comment by martynasma** [comment]
The axis chooses its grid based on scale and available pixel space, so that it comes in "pretty" increments.

Normally it would end at 800 in your case.

However, since you have `strictMinMax` set, it ends 751.9 which is short of the next step, hence no last label.

Hope that makes sense.

**Comment by iamtomhanks** [comment]
Ah I see. Okay thank you for looking into it. Looks like I will have to round up. Seems like strictMinMax works as expected (potentially), only restricting the length of the axis, and not affecting the labels. Would be nice to have the ability to show that last label though. Even through some other means.

Thanks again

**Comment by iamtomhanks** [comment]
Rounding doesn't seem to work consistently. If I round from 751 to 800 it works, or from 25, 393 to 30, 000. But one of my graphs rounds from 8425 to 9000 and the last label doesn't show. I'm fine with libraries making decisions for me, to make it easier, but the reason I use amcharts is because of the insane amount of customizablility that is available. This seems like something I should be able to do.

**Comment by martynasma** [comment]
You might need to reduce the `minGridDistance` if you want better granularity.

The way it works is that if the available step is 200, then setting max to 900 will not produce a last label because it would be in the middle of the step.

**Comment by iamtomhanks** [comment]
Unfortunately rounding up, makes the stacked-column not 100% height. I would really like to see this addressed. I've recommended your software to several companies and the membership is not cheap.

**Comment by iamtomhanks** [comment]
I want one stacked column, 100% height, with a last label.

**Comment by martynasma** [comment]
In that case you will need to add that label using axis range.

There's no option in amCharts to force last label at an inconsistent value.

**Comment by iamtomhanks** [comment]
That would be an option, but as I explained earlier. The last label is inconsistent, meaning sometimes it is there and sometimes not. The axis range would be definitely adding the label, and potentially putting 2 labels at the end.

**Comment by martynasma** [comment]
Well, you can prevent an automatic label using `maxLabelPosition`, e.g.:

```
var range = valueAxis.axisRanges.create();
range.value = 700;
range.grid.disabled = true;
range.label.dataItem.maxPosition = 1;
valueAxis.renderer.maxLabelPosition = 0.8;
```

**Comment by iamtomhanks** [comment]
Can you show me a working example?

**Comment by martynasma** [comment]
You can use this. It even updates end labels as you zoom in.

https://codepen.io/team/amcharts/pen/JjGmWOO

**Comment by iamtomhanks** [comment]
I don't really want to look through the code of this random chart. This question seems to be above your skill, but more likely initiative level. I will be suggesting another charting library to my future clients.

**Comment by martynasma** [comment]
If you have a support subscription, feel free to contact our support crew at contact@amcharts.com. If you don't you can acquire one.

Without it, I'm afraid we don't have the capacity to provide any more assistance than what I already provided here.
