### ISSUE TITLE
After deletion, an error is thrown when resizing

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2689]
Hi. I am having a situation where I am deleting and adding elements based on some logic to improve performance.
The problem is that after I delete something, if I then resize the `div` where the map chart is created, an error will occur.

I have created a CodePen example with the pulsating bullets demo that is on the amCharts website.
I added a timeout (line 65), so after 3 seconds the `imageSeries` will be disposed.
If I now try to resize the window, an error will be shown on the screen and the map will be not available anymore.

CodePen Example: https://codepen.io/directcuteo/pen/eYJKBZX

Thank you!

**Comment by zeroin** [comment]
Hi,

Instead of disposing, you should remove the series form the chart:

`chart.series.removeValue(imageSeries)`

**Comment by directcuteo** [comment]
This is working great, thank you!
