### ISSUE TITLE
Line Chart - ability to convert to an area chart

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/amcharts4#269]
Is there any way we can turn the line chart into an area chart?
![test](https://user-images.githubusercontent.com/3138071/44519419-94e97800-a6ff-11e8-80d8-1f553db1317d.png)

**Comment by martynasma** [comment]
Yes, simply set series' `fillOpacity` to a non-zero value.

```
series.fillOpacity = 0.5;
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by kevzlou7979** [comment]
Cool thank you very much
