### ISSUE TITLE
Data points not reaching y-axis

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#2692]
I have noticed something strange when using a very small amount of data (2 points) that the points don't reach the y-axis lines (shown below). In this scenario the line should stretch from the left axis to the right axis

![two-points issues](https://user-images.githubusercontent.com/48843852/87295059-8cb9a200-c4fc-11ea-8441-9110490c93c6.PNG)

Thanks

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

**Comment by towsie84** [comment]
Great, thank you very much for your help
