### ISSUE TITLE
Your GeoData CDN is empy. You broke probably thousands of websites.

### ISSUE THREAD

**Issue by hirishh** [amcharts/amcharts4#2695]
**Bug description**

https://www.amcharts.com/lib/version/geodata/

![image](https://user-images.githubusercontent.com/7662810/87308195-26904780-c51b-11ea-8b33-ae6f892401db.png)

Is there a reason for this?

**Comment by martynasma** [comment]
Yes, we're having server issues. For now please current version of the geodata cdn at `/lib/geodata/`.

**Comment by hirishh** [comment]
https://www.amcharts.com/lib/geodata gives me 404

**Comment by martynasma** [comment]
Sorry my bad. It's https://www.amcharts.com/lib/4/geodata

**Comment by martynasma** [comment]
Heads up, geodata version CDN is back.

We're also now recommending to use `cdn.amcharts.com` domain, though `www.amcharts.com` will work, too.

**Comment by SoftcaseDelmer** [comment]
I don't think so ... I tried to access, but now can't even open the https://www.amcharts.com/lib/version/ 
![image](https://user-images.githubusercontent.com/67698369/87788225-6012cc80-c813-11ea-9c9f-d20c44dd6385.png)
![image](https://user-images.githubusercontent.com/67698369/87788067-15915000-c813-11ea-81bd-561588874d2e.png)

**Comment by SoftcaseDelmer** [comment]
Do you have any estimate of when the `www.amcharts.com` will get back?

**Comment by martynasma** [comment]
> Do you have any estimate of when the `www.amcharts.com` will get back?

Back? Is it down for you?

**Comment by SoftcaseDelmer** [comment]
Yes, as you can see ...

![image](https://user-images.githubusercontent.com/67698369/87791822-4eccbe80-c819-11ea-9057-66e084ce3942.png)

And if I try to access the link I get this ...
![image](https://user-images.githubusercontent.com/67698369/87791868-69069c80-c819-11ea-8c8f-6c08cfa56e57.png)

**Comment by martynasma** [comment]
Ah OK, so it's a CORS issue. We just fixed this in the new CDN. Can you try it if it's OK on your end, too?

**Comment by SoftcaseDelmer** [comment]
No, not yet ...

![image](https://user-images.githubusercontent.com/67698369/87795698-d49f3880-c81e-11ea-925c-c9844f55cbd5.png)

**Comment by martynasma** [comment]
OK, try clearing your browser cache :)

**Comment by SoftcaseDelmer** [comment]
Even clearing my browser cache ... 

I replicated on JSFiddle, if you wanna see ... https://jsfiddle.net/3zu2a7mf

**Comment by martynasma** [comment]
Looks good to me:
![image](https://user-images.githubusercontent.com/1458520/87812815-7186c380-c869-11ea-8de1-53d7eed22168.png)

**Comment by SoftcaseDelmer** [comment]
Like you can see there, I still have errors occurring ...
It seems like something about CORS policy ...

![image](https://user-images.githubusercontent.com/67698369/87826122-b0f3e680-c84e-11ea-8c12-a1d95af11612.png)

**Comment by martynasma** [comment]
Must be caching issue. There are definitely CORS headers now. Try a bit later if this still persist.

**Comment by SoftcaseDelmer** [comment]
It's working now, thank you for your help 

![image](https://user-images.githubusercontent.com/67698369/87936830-efb1b880-ca69-11ea-8bf6-225e3276c72c.png)
