### ISSUE TITLE
Sankey Link Color (fill)

### ISSUE THREAD

**Issue by ct5845** [amcharts/amcharts4#2696]
The sankey link color doesn't seem to be 'settable' this is apparent in the demo page example on how to set a links color;

https://codepen.io/team/amcharts/pen/NMvZGV

Unless i'm mistaken the "links" should have the color set by linkTemplate.fill, but they all just seem to take the color of their 'from' node.

**Comment by xorspark** [comment]
It appears that the current default behavior is to inherit the color from the fromNode, which wasn't the case when the documentation was first written, if I recall correctly. In order to change the color, you have to set the link's `colorMode` to `"solid"` first:

```
chart.links.template.colorMode = "solid";
chart.links.template.fill = am4core.color("#A8C686");
```

I've updated the demo. I'll ping the team to tweak the tutorial.

**Comment by martynasma** [comment]
FYI, we've just updated the docs:
https://www.amcharts.com/docs/v4/chart-types/sankey-diagram/#Link_color_mode

Thanks for bringing this to our attention @ct5845

**Comment by ct5845** [comment]
Thanks,

For reference, obviously setting colorMode to 'solid' loses gradients. In my case i simply wanted to always color my 'drop-offs' (toNode = null) red. You can however achieve this by creating the gradient in the data 

e.g.;

```
const gradient = new LinearGradient();
gradient.addColor(color('red'));
gradient.addColor(color('blue')); // for purposes of showing it works!

const data = [
...,
{ from: 'A', to: null, value: 100, linkColor: gradient }
...
]

const linkTemplate = chart.links.template;
linkTemplate.colorMode = 'solid';
linkTemplate.propertyFields.fill = 'linkColor';
```
