### ISSUE TITLE
Clustered Layered Columns

### ISSUE THREAD

**Issue by thefat32** [amcharts/amcharts4#2697]
**Question**
Is there any way to get multiple "layered" columns for the same date/category? In this [example](https://www.amcharts.com/demos/layered-column-chart/) there is one layered column for each date (each column contains two series, outer and inner), I would like to achive some more layered columns (each of them with it's respective two series) in a clustered way for each date.

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
I'm afraid there's no way to mix clustered of overlaid columns within a single category/date. Sorry.

**Comment by thefat32** [comment]
Thank you for the answer!
