### ISSUE TITLE
Axis displays wrong cursor tooltips if `skipEmptyPeriods` is used

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#27]
<img width="461" alt="chrome_2018-05-15_11-32-44" src="https://user-images.githubusercontent.com/1458520/40045756-d303054a-5833-11e8-903c-09e2d35f51e0.png">

(Apr 26 data point does not exist, but it shows up as tooltip while hovering on Apr 30, which does exist)

Example: https://codepen.io/team/amcharts/pen/erjazO

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.26](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.26)

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta26---2018-05-30).

**Comment by sschrijver** [comment]
Is it possible that this bug is reintroduced in `"@amcharts/amcharts4": "^4.0.4",` ?
