### ISSUE TITLE
Bug in Venn diagram sets showcase (Overlap Issue).

### ISSUE THREAD

**Issue by PratapAkshay** [amcharts/amcharts4#2702]
There is 3 object A, B, and C. A having value 15, B has value 119, and C is set of A and B with value 15 (same as A), the chart should showcase C with its color but instead of that it hide both A and C, which get overlap by full circle of B. 

ShowCase correct graph data : [
  { "name": "A", "value": 119, "color": am4core.color("#8F3985") },
  { "name": "B", "value": 15, "color": am4core.color("#07BEB8") },
  { "name": "C", "value": 15 , "color": am4core.color("#82E0AA"), "sets": ["A", "B"] }
];

ShowCase wrong graph data : [
  { "name": "A", "value": 15, "color": am4core.color("#8F3985") },
  { "name": "B", "value": 119, "color": am4core.color("#07BEB8") },
  { "name": "C", "value": 15 , "color": am4core.color("#82E0AA"), "sets": ["A", "B"] }
]; 

**NOTE**: chart showcases different charts with the same data but just by manipulating data index.

For bug Showcase use:
CodePen ->  https://codepen.io/pratapakshay/pen/qBbMYJy?editors=0010

development environment :

 - amCharts version : "4.9.28",
 - Chrome Browser version : 83.0.4103.116,
 - React.js

**Comment by zeroin** [comment]
We do not solve label overlapping in Venn diagrams. The only way to solve this would be to add some adapter and move one of the labels by some pixels. Here is a demo: 
https://codepen.io/team/amcharts/pen/7159810e94a42d25a0df02e88273b5ba?editors=0010

**Comment by PratapAkshay** [comment]
> We do not solve label overlapping in Venn diagrams. The only way to solve this would be to add some adapter and move one of the labels by some pixels. Here is a demo:
> https://codepen.io/team/amcharts/pen/7159810e94a42d25a0df02e88273b5ba?editors=0010

okay. but try to put value of A as 45 and B as 118 than the expected output on the graph should be B and within B's circle C with its color, but getting B circle overlapping C, why it's not highlighting sets color.

**Comment by zeroin** [comment]
You should sort data in ascending order before passing it to the chart:

https://codepen.io/team/amcharts/pen/bGExOvG

**Comment by PratapAkshay** [comment]
> You should sort data in ascending order before passing it to the chart:
> 
> https://codepen.io/team/amcharts/pen/bGExOvG

YES, I know this is the makeshift we can do. but this should not happen. Venn diagram should showcase data as it mentioned.

**Comment by zeroin** [comment]
Sorry, but we do not have plans in changing this behavior.

**Comment by PratapAkshay** [comment]
> Sorry, but we do not have plans in changing this behavior.

okay thnx for support
