### ISSUE TITLE
Removed logo amcharts

### ISSUE THREAD

**Issue by fisherspoons** [amcharts/amcharts4#2703]
Good afternoon, I noticed an error, I made a preloader during each request and my function removes the logo Amcharts at the bottom of the graph

` var indicator;
                function showIndicator() {
                    indicator = chart.tooltipContainer.createChild(am4core.Container);
                    indicator.background.fill = am4core.color("#fff");
                    indicator.background.fillOpacity = 0.8;
                    indicator.width = am4core.percent(100);
                    indicator.height = am4core.percent(100);
                    var indicatorLabel = indicator.createChild(am4core.Label);
                    indicatorLabel.dy = 90;
                    var hourglass = indicator.createChild(am4core.Image);
                    hourglass.href = "https://i.pinimg.com/originals/04/bd/f8/04bdf8f9d33a4464118c0804e2c4cea2.gif;
                    hourglass.align = "center";
                    hourglass.valign = "middle";
                    hourglass.horizontalCenter = "middle";
                    hourglass.verticalCenter = "middle";
                    hourglass.scale = 2;
                }

                function hideIndicator(){
                    chart.tooltipContainer.removeChildren(am4core.Container);
                }

                chart.dataSource.url = "/rates/get-archive?period=week&from_currency=" + exchangeRatesByChart.exchangeRates + "&to_currency=" + exchangeRatesByChart.toCurrency;
                chart.dataSource.events.on("started", showIndicator);

                chart.events.on("datavalidated", hideIndicator);`

[https://prnt.sc/ti9eeo](https://prnt.sc/ti9eeo)

**Comment by martynasma** [comment]
Your `removeChildren()` line might wreck havoc and remove much more than the logo, causing the chart to misbehave.

It's much better to dispose the exact element you want to remove:

```
indicator.dispose();
```

**Comment by fisherspoons** [comment]
Yes, it's work but for other people who will use their preloaders it is better to do so
`var indicator;
                function showIndicator() {
                    indicator = chart.tooltipContainer.createChild(am4core.Container);
                    indicator.background.fill = am4core.color("#fff");
                    indicator.background.fillOpacity = 0.8;
                    indicator.width = am4core.percent(100);
                    indicator.height = am4core.percent(100);
                    var indicatorLabel = indicator.createChild(am4core.Label);
                    indicatorLabel.dy = 90;
                    var hourglass = indicator.createChild(am4core.Image);
                    hourglass.href = "https://privatbank.ua/uploads/media/default/0001/13/8e797b5d9f24dede323fa20bad80ba5021059cae.gif";
                    hourglass.align = "center";
                    hourglass.valign = "middle";
                    hourglass.horizontalCenter = "middle";
                    hourglass.verticalCenter = "middle";
                    hourglass.scale = 2;
                }

                function hideIndicator(){
                    indicator.dispose();
                }

                chart.dataSource.url = "/rates/get-archive?period=week&from_currency=" + exchangeRatesByChart.exchangeRates + "&to_currency=" + exchangeRatesByChart.toCurrency;
                chart.dataSource.events.on("started", showIndicator);
                chart.dataSource.events.on("ended", hideIndicator);`


if use "datavalidated" there will be a method call not yet declared object, respectively, get an error
`chart.events.on("datavalidated", hideIndicator);`

**Comment by MohitUpa** [comment]
this.root._logo.dispose();
