### ISSUE TITLE
tooltips overlap

### ISSUE THREAD

**Issue by syfgkjasdkn** [amcharts/amcharts4#2704]
👋

**Bug description**

Tooltips overlap when the chart is created via `createFromConfig` and `tooltipText` is set inside a `columns` map.

```js
// ...
columns: {
  tooltipText: "{name}: [bold]{valueY}[/]"
}
// ...
```

Example: https://codepen.io/syfgkjasdkn/pen/zYrJyww

<img width="1181" alt="Screenshot 2020-07-15 at 16 16 33" src="https://user-images.githubusercontent.com/43219386/87549524-9a1a8c00-c6b6-11ea-8ac7-338e6b3679de.png">

---

If the `tooltipText` is set one level higher, everything works as expected.

```js
// ...
{
  type: "ColumnSeries",
  dataFields: { categoryX: "bucket", valueY: "in" },
  name: "avg # of pedestrians (in)",
  tooltipText: "{name}: [bold]{valueY}[/]",
 },
// ...
```

But all examples in the docs set the tooltip text inside the `columns` map, so I'm not sure if that would lead to any other problems.

**Comment by zeroin** [comment]
This is a known behavior. We only solve overlapping if tooltipText is set on series.

**Comment by syfgkjasdkn** [comment]
Thank you for the quick response!
