### ISSUE TITLE
Enable series on legend label click

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#2705]
The Problem: 

Many series and their data added at once (data per series) dynamically (async) to the chart can cause a performance issue. 

I tested adding a series and it's data async, but disabled and it improved the performance. Probably because no computation was done. 

However I could not find a way to "enable" this series. Could one point me to the right direction ?

**Comment by martynasma** [comment]
Hey Jimmy,

Do you perhaps have this chart online somewhere?

**Comment by jimmykane** [comment]
Hey @martynasma no need for me to add a chart somewhere. I think this is simple. 

I am asking if we can "reduce" the calculations if a series is added (with their data) with a state of disabled. 

I tested this and yes it reduces the CPU needed and makes it smoother but re-enabling the series doesn't allow it to be drawn at the chart. 

Is there any way I can achieve this? There are tons of your demos that could be used. 

Thanks a lot and have a great weekend
