### ISSUE TITLE
question: combine heatmap, column, and bar charts?

### ISSUE THREAD

**Issue by mg1075** [amcharts/amcharts4#2706]
Is it possible, if nothing else at least in theory, to combine a heatmap, a column chart, and a bar chart in amcharts 4?

An example of what I mean is in the screenshot below, from a Tableau-based solution.

Note how the column headings of the heatmap also serve as the column labels for the column chart above the heatmap.
Likewise, the barchart at the end of the heatmap has its bars fit inside the same "table" of the heatmap.

Now, it would be possible to build something like this using html and css,
but I'm wondering if it is feasible in amcharts 4?

![image](https://user-images.githubusercontent.com/2031435/87580268-dc36d400-c69c-11ea-945b-9d8178367c63.png)

**Comment by zeroin** [comment]
Yes, this is totally doable, with some light hacking. These are 3 different charts added to Container, with some layout/margins tricks applied. I recommend to start with creating three independent charts and then I could help to layout them like in the picture.

**Comment by mg1075** [comment]
First experiment result here:

https://jsfiddle.net/bz60uvj5/

Overall appearance is ok; not as polished as I'd like yet because I'm only now trying to become familiar with amcharts v4.
The way I've approached it might not be best approach and too hacky; e.g., how to make left side of heatmap align with left side of column chart.
And if I removed the value axis labels on the bar chart, it would be necessary to add a margin or padding hack to that chart to keep it even with the heatmap "rows".

FWIW...
Trying to get familiar with amchart v4, 
It might be helpful if there was a single page view one can interact with - expand/collapse - similar to highcharts documentation?
Kind of feels like I'm jumping around and getting disoriented.
Might try starting to use the new editor to get more familiar with api options. 
At risk of bloating the editor view, wonder if it would be useful to integrate "help/info/about" related info by clicking on a particular api property and providing full explanation, external links to examples, etc.?

**Comment by mg1075** [comment]
v1: https://jsfiddle.net/bz60uvj5/

(Also, was not able to figure out how to get the heatmap scale working for the color scale I was using, so not showing a heatmap legend.)

![image](https://user-images.githubusercontent.com/2031435/87998327-32e94700-cabd-11ea-9ba8-1e0a3b3484a6.png)

**Comment by martynasma** [comment]
> I might try starting to use the new editor to get more familiar with api options.
At risk of bloating the editor view, I wonder if it would be useful to integrate "help/info/about" related info by clicking on a particular api property and providing full explanation, external links to examples, etc.?

It's a good idea, though for non-coder users that might be even more confusing reading developer-oriented reference.

**Comment by mg1075** [comment]
> ...for non-coder users that might be even more confusing...
Yeah, could become unnecessarily complicated; maybe there could be two versions or modes for the editor - one with integrated documentation, the other without - that a person could toggle on/off (?).

**Comment by martynasma** [comment]
Yeah, thanks. We'll keep that idea open.
