### ISSUE TITLE
How to set an offset when zooming 

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2707]
Hi! I am using the amCharts map to display multiple routes.

### **The behaviour**
When I click on a route, I will focus that area of the map using the zoomToRectangle function like this:
```
    private zoomToRectangle(latitudes: number[], longitudes: number[]): void {
        const north = Math.max.apply(null, latitudes);
        const south = Math.min.apply(null, latitudes);
        const west = Math.min.apply(null, longitudes);
        const east = Math.max.apply(null, longitudes);

        this.map.zoomToRectangle(north, east, south, west, 1, true, 1500);
    }
```
`longitudes` and `latitudes` are all the points that build the line between cities.

**Preview:**
![image](https://user-images.githubusercontent.com/37619567/87636557-9e43b980-c749-11ea-992c-fc927cfafb17.png)

What I also do on focusing a route is showing a side panel on the right.
![image](https://user-images.githubusercontent.com/37619567/87636896-1a3e0180-c74a-11ea-9d06-1e7d07286138.png)

### **What I need**

As you can already see, I need to specify an offset on the right so that the entire route is visible.

### **The problem**

It would be easy to add an east longitude offset (for example `30`) to the zoom function, but having different routes on the map this would not always work. Look at the example below.

*For example we have 2 routes: Moscow-Shanghai and Paris - Barcelona:*

![image](https://user-images.githubusercontent.com/37619567/87639790-7014a880-c74e-11ea-9a20-912c63d5b1f3.png)

Now if I add `30` to the east longitude the actual offset in pixels would be different for the 2 previews because of the zoom level that the map requires to display the entire route.

![image](https://user-images.githubusercontent.com/37619567/87640620-a7378980-c74f-11ea-8958-cf629ef71edd.png)

### **What I am trying to do**

The side panel will always have the same width (300px). Would be great to actually give a 300px offset to the zoom function.
Or maybe based on the east, west, north and south points to create a formula which outputs the needed east longitude number to add so that in the view will result in a 300px right offset.
How can I achieve this? Thank you!

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
