### ISSUE TITLE
Update chart language

### ISSUE THREAD

**Issue by VictorJuliani** [amcharts/amcharts4#271]
Hello!

Is it possible to update the chart's locale after it's been initialized?
Currently, I can set the locale only in a near time after the chart has been created.

However, in a case where user wants to change the language manually, the chart won't update.
Here's a simple repro: https://codepen.io/victorjuliani/pen/aavBZp?editors=0010

The visible difference between EN and PT languages used on the CodePen is that PT uses DOT formatting for numbers and EN uses COMMA formatting. You can see that the chart won't be updated after 5s.
If you switch the properties (start with PT and than change to EN), it's possible to see that locale is actually working and the issue is updating it.

Portuguese & english formatters are very similar and it makes barely a difference, but for a language such as Chinese it might be very helpful for the user.

**Comment by martynasma** [comment]
Dynamically changing chart locale is currently not supported.

I'm going to mark this as a possible enhancement.

Will let you know if/when it is implemented.

Thank you for the suggestion!

**Comment by anirudhsamudrala** [comment]
@VictorJuliani I ran into similar use case and I landed on this issue. I played around the pen you mentioned here and I see the values changing from comma to dot for pt-BR. Does this mean amcharts now supports dynamic locale?

**Comment by martynasma** [comment]
We've decided not to implement dynamic locale switching on chart.

The recommended action is to re-create the chart with a new locale.

**Comment by abelardolg** [comment]
Hi there, 

Have you changed of thoughts about this issue?

Best regards.
