### ISSUE TITLE
Tooltip overlaps when showTooltipOn = "always"

### ISSUE THREAD

**Issue by PratapAkshay** [amcharts/amcharts4#2717]
I am using this to show all slice tooltip but my tooltip gets overlap is there any way I can fix this?
 pieSeries.slices.template.showTooltipOn = "always"

**Comment by martynasma** [comment]
No, I'm afraid. There's no built-in overlap checking for tooltips.

**Comment by PratapAkshay** [comment]
> No, I'm afraid. There's no built-in overlap checking for tooltips.

Okay thankyou.
