### ISSUE TITLE
syncWithAxis / scrollbarY causing looped visual "jump"

### ISSUE THREAD

**Issue by 128keaton** [amcharts/amcharts4#2718]
**Bug description**

I have a single XYChart with two ValueAxis objects. Left has a huge scale of 0 - 12k. Right has 0 - 100. 

On some scrolls/zooms with the ScrollBar (or API) the right ValueAxis line values jump up and down on the chart repeatedly. 
Sometimes it will correct itself and recover, other times I have to zoom or scale it again to get it to stop
[Codepen Example](https://codepen.io/128keaton/pen/XWXozVy)

**Environment (if applicable)**

* @amcharts/amcharts4 - 4.9.30
* @angular/core - 9.1.11
* macOS 10.15.5 
* Chrome  83.0.4103.116

**Attached GIF**

![output](https://user-images.githubusercontent.com/1402918/87981215-7e3e2e00-ca9a-11ea-8ff0-47e78efa6f29.gif)

**Comment by zeroin** [comment]
syncWithAxis can not work properly with scrollbar of the same direction as your axes are. We do not have plans to fix this.
