### ISSUE TITLE
Tooltip hover region and isMeasured = false

### ISSUE THREAD

**Issue by churchianity** [amcharts/amcharts4#2719]
**Question**
Is there a way to change the hover region of a labelTemplate, or move the region without moving the corresponding label? How is the hover region of a tooltip determined?

The hover region for tooltips on some labels on a category axis are appearing vertically offset from where they should be for me, but the labels themselves are arranged correctly.

![image](https://user-images.githubusercontent.com/43279719/88096817-405a0c00-cb65-11ea-9761-baaa36b2b773.png)

If my mouse is on the red dot, the tooltip that gets shown is for the bar below it. 

Edit: i'm going to upload a codesandbox.io.

**Comment by martynasma** [comment]
I suggest disabling interactions on labels at all:

```
labelTemplate.interactionsEnabled = false;
```

This way yo'll ensure that only hovers on columns trigger a tooltip.
