### ISSUE TITLE
cannot use amchart 4 with next.js

### ISSUE THREAD

**Issue by supasonk** [amcharts/amcharts4#272]
when i try to import the use the amchart4. in next.js i got the following error.

Unexpected token export
/Users/almagest/Development/Project/dw/node_modules/@amcharts/amcharts4/core.js:8
export { System, system } from "./.internal/core/System";

any idea to fix this.

**Comment by notacouch** [comment]
Is it possible for you to provide a demo so we can take a look?

**Comment by supasonk** [comment]
thank @notacouch. I already find the solution to this. I'm gonna post it for anyone run in this problem like me.


```
let am4core = null
let am4charts = null
let am4themesAnimated = null
if (process.browser) {
  am4core = require('@amcharts/amcharts4/core')
  am4charts = require('@amcharts/amcharts4/charts')
  am4themesAnimated = require('@amcharts/amcharts4/themes/animated')
  am4core.useTheme(am4themesAnimated.default)
}
```
use this instead of normal import.

**Comment by notacouch** [comment]
Good to know you were able to get it working, and thanks for sharing your solution.

**Comment by dwehrmann** [comment]
It's 2019 now and next.js has dynamic imports now, I ran into the same situation and was able to solve it like here: https://nextjs.org/docs/#3-with-no-ssr

Hope that helps someone else.

**Comment by marcelobaez** [comment]
> It's 2019 now and next.js has dynamic imports now, I ran into the same situation and was able to solve it like here: https://nextjs.org/docs/#3-with-no-ssr
> 
> Hope that helps someone else.

Can you provide an example of your solution using next dynamic imports? The examples only show how to import react components, but amcharts aren´t that case, amcharts is a charting library. Thanks in advance

**Comment by miladd3** [comment]
> It's 2019 now and next.js has dynamic imports now, I ran into the same situation and was able to solve it like here: https://nextjs.org/docs/#3-with-no-ssr
> 
> Hope that helps someone else.

I tried using dynamic imports but it has limitation importing node modules.

can you provide example with amcharts

**Comment by pritam3010** [comment]
> > It's 2019 now and next.js has dynamic imports now, I ran into the same situation and was able to solve it like here: https://nextjs.org/docs/#3-with-no-ssr
> > Hope that helps someone else.
> 
> I tried using dynamic imports but it has limitation importing node modules.
> 
> can you provide example with amcharts.

I know I'm little late for this reply but i got solution while googling about this problem.

Just install the next-transpile-modules package from NPM and add the following code in your next.confing.js file.

const withTM = require("next-transpile-modules")([
  "@amcharts/amcharts4/core",
  "@amcharts/amcharts4/charts",
  "@amcharts/amcharts4/themes/animated"
]); // pass the modules you would like to see transpiled

module.exports = withTM();

**Comment by rikinshah23** [comment]
any idea why its giving me addEventListener is not defined error when I try to build production build? 
`next js production build error : ReferenceError: addEventListener is not defined`

[https://github.com/amcharts/amcharts4/issues/2608](https://github.com/amcharts/amcharts4/issues/2608)

**Comment by rikinshah23** [comment]
@supasonk - thanks for your solution. 
@notacouch 
I fixed the build error by removing amcharts from webpack file. and import it like below when page loads.

```
let am4core = null;
let am4charts = null;
let am4themesAnimated = null;
if (process.browser) {
  console.log("process.browser", process.browser);
  am4core = require("@amcharts/amcharts4/core");
  am4charts = require("@amcharts/amcharts4/charts");
  am4themesAnimated = require("@amcharts/amcharts4/themes/animated");
  am4core.useTheme(am4themesAnimated.default);
}
```
Now my prod build works fine and chart is loading fine on first load.
When I refresh the page it shows me below error:

```
charts.js:1 Uncaught ReferenceError: am4internal_webpackJsonp is not defined
    at charts.js:1
(anonymous) @ charts.js:1
maps.js:1 Uncaught ReferenceError: am4internal_webpackJsonp is not defined
    at maps.js:1
```
how do I fix this? Your help is appreciated. Thanks

**Comment by Pauan** [comment]
@rikinshah23 NextJS does server side rendering, so you have to make sure that the amCharts code is NOT run on the server.

You can do that by creating a component which is just for amCharts, like this:

```ts
// components/Chart.ts
import { useLayoutEffect } from "react";
import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";
import am4themes_animated from "@amcharts/amcharts4/themes/animated";

am4core.useTheme(am4themes_animated);

function Chart() {
    useLayoutEffect(() => {
        let chart = am4core.create("chartdiv", am4charts.XYChart);

        // ... chart code goes here ...

        return () => {
            chart.dispose();
        };
    }, []);    
}

export default Chart;
```

Now you can make sure that the `Chart` component is [only loaded in the browser](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr):

```ts
// pages/Foo.ts
import dynamic from "next/dynamic";

const Chart = dynamic(
    () => import("../components/Chart"),
    { ssr: false }
);

function Foo() {
    return <Chart />;
}

export default Foo;
```

Also, you must use the [npm version of amCharts](https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/), NOT the [script version of amCharts](https://www.amcharts.com/docs/v4/getting-started/using-javascript/).

**Comment by rikinshah23** [comment]
@Pauan Thank you so much for your answer. I followed your sample.

I created below 2 components. and dynamically importing them in my main chart page 
```
const MVIChart = dynamic(() => import("../components/MVIChart"), {
  ssr: false,
});
const MultilineChart = dynamic(() => import("../components/MultilineChart"), {
  ssr: false,
});
```

Before when I refresh the page it was giving that error and also stop loading the chart. 

Now I am able to refresh the page and charts looks fine, but debugger shows the same error . 
Let me know if you would like to see more code. 
You can also comment on the question I created. [https://github.com/amcharts/amcharts4/issues/2608](url)

Thanks for your time and helping me.

**Comment by Eronheit** [comment]
> @ rikinshah23 NextJS faz renderização do lado do servidor, então você deve ter certeza de que o código amCharts NÃO é executado no servidor.
> 
> Você pode fazer isso criando um componente que é apenas para amCharts, como este:
> 
> ```ts
> // components / Chart.ts 
> import  {  useLayoutEffect  }  de  " react " ; 
> importar  *  como  am4core  de  "@ amcharts / amcharts4 / core" ; 
> importar  *  como  am4charts  de  "@ amcharts / amcharts4 / charts" ; 
> importar  am4themes_animated  de  "@ amcharts / amcharts4 / themes / animated" ;
> 
> am4core . useTheme ( am4themes_animated ) ;
> 
> function  Chart ( )  { 
>     useLayoutEffect ( ( )  =>  { 
>         let  chart  =  am4core . create ( "chartdiv" ,  am4charts . XYChart ) ;
> 
>         // ... o código do gráfico vai aqui ...
> 
>         return  ( )  =>  { 
>             gráfico . dispose ( ) ; 
>         } ; 
>     } ,  [ ] ) ;     
> }
> 
> exportar  gráfico padrão  ;
> ```
> 
> Agora você pode ter certeza de que o `Chart`componente está [carregado apenas no navegador](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) :
> 
> ```ts
> // pages / Foo.ts 
> import  dynamic  from  "next / dynamic" ;
> 
> const  Chart  =  dynamic ( 
>     ( )  =>  import ( "../components/Chart" ) , 
>     {  ssr : false  } 
> ) ;
> 
> function  Foo ( )  { 
>     return  < Chart / >;
> }
> 
> exportação  padrão  Foo ;
> ```
> 
> Além disso, você deve usar a [versão npm de amCharts](https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/) , NÃO a [versão de script de amCharts](https://www.amcharts.com/docs/v4/getting-started/using-javascript/) .

It worked for me, thanks!

**Comment by Eronheit** [comment]
> @ rikinshah23 NextJS faz renderização do lado do servidor, então você deve ter certeza de que o código amCharts NÃO é provado no servidor.
> 
> Você pode fazer isso criando um componente que é apenas para gráficos, como este:
> 
> ```ts
> // components / Chart.ts 
> importação  {  useLayoutEffect  }  de  " reagir " ; 
> importar  *  como  am4core  de  "@ amcharts / amcharts4 / core" ; 
> importar  *  como  am4charts  de  "@ amcharts / amcharts4 / charts" ; 
> importar  am4themes_animated  de  "@ amcharts / amcharts4 / themes / animated" ;
> 
> am4core . useTheme ( am4themes_animated ) ;
> 
> function  Chart ( )  { 
>     useLayoutEffect ( ( )  =>  { 
>         let  chart  =  am4core . create ( "chartdiv" ,  am4charts . XYChart ) ;
> 
>         // ... o código do gráfico vai aqui ...
> 
>         return  ( )  =>  { 
>             gráfico . dispose ( ) ; 
>         } ; 
>     } ,  [ ] ) ;     
> }
> 
> Exportar  Gráfico Padrão  ;
> ```
> 
> Agora você pode ter certeza de que o `Chart`componente está [carregado apenas no navegador](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) :
> 
> ```ts
> // pages / Foo.ts 
> import  dynamic  from  "next / dynamic" ;
> 
> const  Chart  =  dynamic ( 
>     ( )  =>  import ( "../components/Chart" ) , 
>     {  ssr : false  } 
> ) ;
> 
> function  Foo ( )  { 
>     return  < Chart / >;
> }
> 
> exportação  padrão  Foo ;
> ```
> 
> Além disso, você deve usar uma [versão npm de amCharts](https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/) , NÃO uma [versão de script de amCharts](https://www.amcharts.com/docs/v4/getting-started/using-javascript/) .

it worked for me.

**Comment by thom801** [comment]
[My solution for this on StackOverflow](https://stackoverflow.com/questions/69499613/amcharts-in-nextjs-syntaxerror-unexpected-token-export) seems to have gotten a lot of attention and is working for some so I figured I'll link it here.

I think it's pretty similar to the solutions shared above with dynamic imports.
