### ISSUE TITLE
Positioning Axis Elements not working for radial/circular axis

### ISSUE THREAD

**Issue by nasreddineskandrani** [amcharts/amcharts4#2721]
Hi,
This is a Bug report
version amcharts 4 
Note: reproducible in any official example of RadarChart as:
https://www.amcharts.com/demos/radar-chart/

### Bug description
following the doc here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Fine_tuning_label_positions

In a RadarChart with a circular or radial axis, the part `renderer.inside = true` is working fine (the labels move inside) but the code to move in `dy` || `dx` is not working.

```
valueAxis.renderer.inside = true;
valueAxis.renderer.maxLabelPosition = 0.99;
**valueAxis.renderer.labels.template.dy = -20;**
```

### Workaround
in the demo of this example: https://www.amcharts.com/demos/radar-chart/
I used `categoryAxis.renderer.labels.template.radius` to move the axis.
This is working
```
var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";
categoryAxis.renderer.inside = true;
categoryAxis.renderer.maxLabelPosition = 0.99;
categoryAxis.renderer.labels.template.radius = 100;
```
![image](https://user-images.githubusercontent.com/1953635/88122153-d148db80-cb95-11ea-974d-722659c95432.png)

Thank you

**Comment by martynasma** [comment]
This is happening because circular axis renderer already is using `dx` and `dy` to position those labels, so yours is getting overwritten.

You are correct to assume that label's `radius` property is the correct way to control this.

**Comment by nasreddineskandrani** [comment]
ok perfect so i close it :) thanks. Maybe you can update the doc at the link i posted to mention this.

**Comment by martynasma** [comment]
> Maybe you can update the doc at the link i posted to mention this.

Good idea! Added.
