### ISSUE TITLE
LineSeries' line parts missing when using connect:false on default zoom but looks good zoomed in

### ISSUE THREAD

**Issue by alejandroiglesias** [amcharts/amcharts4#2722]
**Bug description**

I see a difference in the rendering of the line for a `LineSeries` with `connect: false`. On the default zoom / zoomed out it misses some parts of the line that were displayed when using `connect: true`. Upon zoom in, the correct line can be seen. I attach two pictures to demonstrate the issue:

**Small crop from the default zoom:**
<img width="137" alt="Screen Shot 2020-07-21 at 11 02 57 PM" src="https://user-images.githubusercontent.com/480640/88127004-1f1b0f00-cba9-11ea-8368-2cf4da23a6fe.png">

**Zoomed in that slice:**
<img width="1079" alt="Screen Shot 2020-07-21 at 11 03 19 PM" src="https://user-images.githubusercontent.com/480640/88127011-23472c80-cba9-11ea-8253-4a12960502c9.png">

As can be seen in the first picture (default zoom), both lines miss a good part. When zooming in, everything appears correctly (with a correct missing data point).

I can try to isolate an example, but the data and the chart setup is a bit complicated, so I'm trying to see if there's anything obvious that I might be missing. The data is sorted by date.

**Chart options:**
```js
var chartOptions = {
    data: scope.dashboard.data,
    yAxes: [
        { type: "ValueAxis" },
    ],
    titles: [
        { text: scope.title },
    ],
    series: [],
    cursor: {},
    xAxes: [
        {
            type: "DateAxis",
            dataFields: { dateX: "category" },
        },
    ],
};
```

**Series options:**
```js
{
    tooltipText: '{name}: [bold]{value}[/]',
    dataFields: {
        valueY: 'value',
        dateX: 'category',
    },
    name: scope.dashboard.legends[i],
    strokeWidth: 1.3,
    type: 'LineSeries',
    fillOpacity: fillOpacity,
    connect: false,
}
```

**Environment (if applicable)**

- amCharts version: 4.9.31
- Browser: Chrome 83
- Related frameworks: Angular.js 1.4.14

**Additional context**

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by alejandroiglesias** [comment]
@martynasma here is a reproduction of the issue in CodePen: https://codepen.io/alejandrogarciaiglesias/pen/XWXGdbb

While making it I realized the problem appears when limiting the width of the chart. I added 2 charts in the example with the exact same config and data, but the first is limited in width and displays the issue, and the second doesn't have any limit and displays correctly.

**Comment by martynasma** [comment]
Thanks. Though, I don't see any difference between the two. What am I missing?

![image](https://user-images.githubusercontent.com/1458520/88315476-046aa680-cd1f-11ea-8cde-4aa73f0b41e0.png)

We've released a new version earlier today. Maybe we fixed this inadvertently? :)

**Comment by alejandroiglesias** [comment]
@martynasma what a coincidence! I was just loading from `https://www.amcharts.com/lib/4/core.js` 1 hour ago, so I assume I was on the latest. I cannot reproduce anymore after a few reloads, so I guess it took some time for the release to propagate to the CDN. Thanks!
