### ISSUE TITLE
How to lazy load map details on zoom in

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2723]
Hello!
I would like to use amCharts map to load details in a progressive way. Is there a solution to load details of a specific area after zoomed in? 
Something like Google Maps, Leaflet, or pretty much any map.
How would this actually work without loading the entire map at the beginning? Also, do you have a track who can provide these detailed GeoJson (paid aswell)?
Thank you!

**Comment by martynasma** [comment]
You could use JSON version of our maps. Depending on your implementation, you could use `geodataSource` on a `MapPolygonSeries` to trigger a load, on some zoom event, e.g.:

```
polygonSeries.geodataSource.url = "https://cdn.amcharts.com/lib/4/geodata/json/brazilLow.json";
polygonSeries.geodataSource.load();
```

The following tutorial might help with zooming events:
https://www.amcharts.com/docs/v4/tutorials/hide-map-images-until-zoomed-in/
