### ISSUE TITLE
compressing graph when more series

### ISSUE THREAD

**Issue by sureshhallyali** [amcharts/amcharts4#2726]
**Bug description**

When more  series in line chart the graph is compressing as you can see in attached file(image)

**Environment (if applicable)**

**Additional context**

![Screenshot from 2020-07-22 16-53-18](https://user-images.githubusercontent.com/57383836/88170944-22aba600-cc3c-11ea-93f1-3d53ebf372e7.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by sureshhallyali** [comment]
Thank you for the response and issue has been solved,
problem was that i am using  in each loop as shown below code

_.each( this.selected_area , function( arr ) {
        // Create axes 
        let dateAxis = chart.xAxes.push(new am4charts.DateAxis()); 
        dateAxis.renderer.minGridDistance = 50;
        chart.paddingRight = 20;
        chart.scrollbarX = new am4charts.XYChartScrollbar();

let series = chart.series.push(new am4charts.LineSeries());
series.dataFields.valueY = "visits"+j;
series.dataFields.dateX = "date"+j;
} 
 
Then i made changes  code out side each loop
        // Create axes 
        let dateAxis = chart.xAxes.push(new am4charts.DateAxis()); 
        dateAxis.renderer.minGridDistance = 50;
        chart.paddingRight = 20;
        chart.scrollbarX = new am4charts.XYChartScrollbar();

_.each( this.selected_area , function( arr ) {

let series = chart.series.push(new am4charts.LineSeries());
series.dataFields.valueY = "visits"+j;
series.dataFields.dateX = "date"+j;
} 

alo we need use   this.chart.dispose();
thats why its compressing graph now its has been solved
