### ISSUE TITLE
Possible to choose which direction to find the closest data item in a date axis?

### ISSUE THREAD

**Issue by Bluecoaster455** [amcharts/amcharts4#2727]
I've been looking for a long time for a possibility to find the closest "left" or "right" data item into an xychart using date axis and step line series. So far, I found this code in DateAxis.ts:2199:

```js
dataItem = series.dataItems.getIndex(series.dataItems.findClosestIndex(date.getTime(), (x) => {
    if (x[key]) {
        return <number>x[key].getTime();
    }
    else {
        return -Infinity;
    }
}, "any"));
```

The direction parameter seem to be only set to "any" which will find the closest data item in any direction on the xAxis. In my chart, I need to get the closest left data item. I did a test by changing "any" to "left" in core.js temporarily and seem to work fine.

Any way to allow devs to change this in any line series using date axis (and possibly other xAxis types perhaps)? If there is already a way, how?

Thanks!

**Comment by martynasma** [comment]
There's currently no way to pass in a direction to `getSeriesDataItem()`, I'm afraid.

The workaround would be to create your own custom function based on `getSeriesDataItem()` code:

https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/axes/DateAxis.ts#L2199-L2232
