### ISSUE TITLE
How to disable color shift on legend tooltips

### ISSUE THREAD

**Issue by ZakThompsonEchelon** [amcharts/amcharts4#2728]
I am currently trying to change the background color of legend tooltips.  I was able to get the background color to successfully change.  However, when mousing over a legend item when it was previously on a different legend item, the background color of the tooltip does not immediately shift.  Instead, it sets the old tooltip background color as the start of a gradient, the new background color as the end of a gradient, and animates the background color transition through the gradient over about one second.  I am trying to make it so that the background colors for the tooltips shift immediately and no color animation takes place. I've tried looking for animation and transition properties on the legend's itemContainer template to set to disable the animation, but have not been able to make any progress

Here is what I have so far codewise:

```
//in each series, I set the background color on the series dummy data inside the series creation loop
series.dummyData = {   
    color: 'a_color_hex_code_here'
};
```

```
//legend configuration
chart.legend = new am4charts.Legend();
chart.legend.itemContainers.template.tooltipText = "{name}";
chart.legend.itemContainers.template.clickable = false;
chart.legend.itemContainers.template.focusable = false;
chart.legend.itemContainers.template.cursorOverStyle = am4core.MouseCursorStyle.default;
chart.legend.itemContainers.template.adapter.add("fill", (value, target, key) => {
    if (!target.dataItem) {
        return value;
    }
    const dummyData = (target.dataItem.dataContext as any).dummyData;
    return dummyData && dummyData.color && am4core.color(dummyData.color) || am4core.color("black");
});
```

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
