### ISSUE TITLE
ForceDirected - Data imported using getDataItemById is different from the original

### ISSUE THREAD

**Issue by smooth97** [amcharts/amcharts4#2729]
Hi there,

Environment - React / chrome / amcharts4 / forceDirected

`networkSeries.getDataItemById`  is used to create the ability to show and hide nodes.

`var node = networkSeries.getDataItemById (networkSeries.dataItems, id)`

I want to hide this node's children.
The chart shows the children's nodes well,
The problem is that children are randomly placed in an empty array.

Here's an example.
https://codepen.io/smooth97/pen/jOOWKxO?editors=1010

**Comment by martynasma** [comment]
Can you explain what you mean by "randomly placed in an empty array"?

If it's about random placement of nodes on the chart, it's part of how ForceDirectedTree works. There's a level of randomness to it. No way around it.

**Comment by smooth97** [comment]
I'm sorry for my poor English.
What I was trying to explain was that there were times when children were in an empty array within the value of the node.

**Comment by martynasma** [comment]
I'm still at loss of what you're trying to say. Maybe post a screenshot? :)
