### ISSUE TITLE
Remove the category axis values from the XYChartScrollbar

### ISSUE THREAD

**Issue by manoj016** [amcharts/amcharts4#273]
I want to remove the category axis values of a or all line series from the XYChartScrollbar. Is it possible?

**Comment by martynasma** [comment]
This will do the trick:

```
chart.scrollbarX.scrollbarChart.xAxes.getIndex(0).renderer.labels.template.disabled = true;
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by manoj016** [comment]
Hi,

How to place the XYChartScrollbar to the bottom of the chart?

Thank you,

**Comment by martynasma** [comment]
To move the `scrollbarX` to bottom, do this:

```
chart.scrollbarX.parent = chart.bottomAxesContainer;
```

If you would like to move X axis to top:

```
categoryAxis.renderer.opposite = true;
```

Demo: https://codepen.io/team/amcharts/pen/wEGoMm
