### ISSUE TITLE
propertyFields.fill for sankey diagrams might be broke

### ISSUE THREAD

**Issue by nate-h** [amcharts/amcharts4#2730]
**Bug description**

I cant seem to configure individual link color for sankey diagrams.
From the doc, this should work:
```
var linkTemplate = chart.links.template;
linkTemplate.propertyFields.fill = "linkColor";
linkTemplate.propertyFields.fillOpacity = "linkOpacity";
```
You can test it with this link:
[codepen example for custom sankey link colors](https://codepen.io/team/amcharts/pen/KRXzdB)

Set the link color from a -> d to #ff0000 and it wont stick.
I think the same color node color and links inheriting those colors might have spoofed the visual inspection.

**Environment (if applicable)**

amchars v4

**Comment by zeroin** [comment]
Try to set:

`linkTemplate.colorMode = "solid"`

**Comment by nate-h** [comment]
That was it! Thank you for the quick reply. I see you guys corrected the example as well.
