### ISSUE TITLE
Making rounded corners for the cursor fullWidthLine 

### ISSUE THREAD

**Issue by Parallaps** [amcharts/amcharts4#2731]
Hi!

I use a sticky cursor with fullWidthLineX filling and I need to make a selection rounded but I haven't found any simple decision for it.
![image](https://user-images.githubusercontent.com/12274253/88284913-e5f0b500-ccf6-11ea-864e-66d72e1ce8d9.png)

Original pen is - https://codepen.io/team/amcharts/pen/ZNzzxL

Is it possible?

**Comment by martynasma** [comment]
I'm afraid there's no way to do that. Sorry.

**Comment by Parallaps** [comment]
It's bad :-( Thank you
