### ISSUE TITLE
Customize the appearance of a legend scrollBar

### ISSUE THREAD

**Issue by Muntaner** [amcharts/amcharts4#2732]
TItle says it all.

I successfully enabled the legend for a Pie Chart (via `chart.legend.scrollable = true`), but I can't figure out how I can edit the style of the scrollBar itself (width/colors/etc.)

Minimal codePen: https://codepen.io/team/amcharts/pen/eYmLvoR

**Comment by martynasma** [comment]
Legend does have a property `scrollbar` which holds an instance of [`Scrollbar`](https://www.amcharts.com/docs/v4/reference/scrollbar/).

You can customize any aspect of it. Follow the link above to the classref.

E.g.:

```
chart.legend.scrollbar.thumb.background.fill = am4core.color("red")
```
