### ISSUE TITLE
Can you mix a clustered bar chart with a line series and have the line series not reference the cluster labels?

### ISSUE THREAD

**Issue by ahajric2** [amcharts/amcharts4#2733]
**Question**

If the title was confusing, I'm sorry. I'm trying to implement a dual axis clustered bar chart with the dual axis labels matching the initial series for the bar chart. When overlaying a second series for the dual axis as a line chart, the reference is to the  clustered data point in the initial series and axis. Here's an ex of what I mean  :https://codepen.io/Azzmir/pen/ZEQPbPo

Question, is it possible to implement a second series to follow and ref the first series columns? Similar to how https://www.amcharts.com/demos/layered-column-chart/ this example allows the overlaid columns but with a second axis for the larger values and clustering. 

Thank you very much :)

**Comment by martynasma** [comment]
Yes, it's possible using series' data item locations:

https://www.amcharts.com/docs/v4/concepts/series/#Data_item_locations

You would need to set relative location for each `LineSeries`.

**Comment by ahajric2** [comment]
Thank you! I wasn't able to coordinate the line series with the bar chart, but I did end up placing two ColumnSeries and then used the relative location on ColumnSeries 2 to overlap ColumnSeries 1. I then did the same thing with the ColumnSeries  Bullet labels to match up. It's not ideal, but it works.
