### ISSUE TITLE
SankeyNode fill won't change when trying to set to different fill in hit event

### ISSUE THREAD

**Issue by RichardCosta10** [amcharts/amcharts4#2734]
Please see example: https://codepen.io/richardcosta10/pen/rNxPoWR

The node won't change fill when clicked on. I also tried doing it using an active state but again it won't change. Any help appreciated, thanks.

**Comment by martynasma** [comment]
Try setting fill to a `background` of the node:

```
node.background.fill = am4core.color("#0075bc");
```
