### ISSUE TITLE
How to do Multiple exports with amcharts and non amcharts visualization in single pdf

### ISSUE THREAD

**Issue by hardikforall** [amcharts/amcharts4#2735]
We have a dashboard that includes multiple visualizations most of them are amcharts and few of them are non-amcharts.

in dashboard pdf export we want to combine these in single pdf 

is there any way we can combine these nonamcharts visualization in pdf as images

below is dashboard placement

![image](https://user-images.githubusercontent.com/12095664/88372344-53621b80-cdb3-11ea-8fbf-ee760e25221d.png)

expected pdf 

![image](https://user-images.githubusercontent.com/12095664/88372488-9b813e00-cdb3-11ea-9e68-e8540b78db10.png)

**Comment by martynasma** [comment]
Take a look at this tutorial:
https://www.amcharts.com/docs/v4/tutorials/generating-multi-content-pdf-export/
