### ISSUE TITLE
Tooltip with xAxes using ValueAxis instead of CategoryAxis

### ISSUE THREAD

**Issue by lnicastro** [amcharts/amcharts4#2738]
Why when `xAxes` is created via `ValueAxis` instead of `CategoryAxis` both `tooltipText` and `legendSettings.valueText` are ignored?
BTW: `cursor.snapToSeries` seems to work fine.

- amCharts 4.9.33
- apparently any browser

See: https://qsfit.inaf.it/xy_vText.html

**Comment by zeroin** [comment]
This is by design. tooltipText can be shown if you set `cursor.snapToSeries = series` but the legend will not be adjusted.

**Comment by lnicastro** [comment]
As said, actually with `snapToSeries` the legend, *for that series only*, gets updated.
