### ISSUE TITLE
 Is there any function to check if the mouse cursor is off the chart?

### ISSUE THREAD

**Issue by wkdaudwn11** [amcharts/amcharts4#2739]
![스크린샷 2020-07-27 오후 3 39 17](https://user-images.githubusercontent.com/26559413/88511277-7ee93e00-d01f-11ea-816e-8b8339ec31a7.png)

In the screenshot above, the Info box appears at the top when the mouse cursor hovers over the chart.
At this time, I want to hide the Info box when the cursor is off the chart.
I tried to solve it with the mouse coordinates, but I can't detect that the cursor is out of the 12 o'clock position.

When the mouse enters the chart, I am using the function below.
```
chart.cursor.events.on('cursorpositionchanged', function (ev) {
    ...code
})
```
Contrary to the above function, I want to detect when it is out of the chart.

Below is my cursor related function code.
```
chart.cursor.events.on('cursorpositionchanged', function (ev) {
    const { contentWidth, contentHeight, point, xPosition, yPosition } = ev.target;
    const { x, y } = point;

    if (y > 0 && x > 0 && y < contentHeight && x < contentWidth) {
         info.disabled = false;

        let point = dateAxis.dateToPoint(
            dateAxis.positionToDate(dateAxis.toAxisPosition(xPosition)),
        );

        info.x = point.x;

        chart.cursor.triggerMove(point, 'none');

        let dataItem = dateAxis.getSeriesDataItem(
            series,
            dateAxis.toAxisPosition(chart.cursor.xPosition),
            true,
        );

        const { date } = dataItem._dataContext;
            updateValues(date);
    } else if (y > 0) {
        info.disabled = true;
    }
});

chart.cursor.events.on('mouseout', function (ev) {
    console.log('mouseout'); // Not working.. T_T
});
```

**Comment by martynasma** [comment]
You may check against cursor's [`visible`](https://www.amcharts.com/docs/v4/reference/xycursor/#visible_property) property.
