### ISSUE TITLE
Hiding origin line

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#274]
Hi, 

When a scale is having both positive and negative values, a line is displaying at zero.
How to remove/hide that?

**Comment by martynasma** [comment]
That line is contained in axis renderer's `baseGrid` property. To disable it simply set `disabled = true` on it:

```
valueAxis.renderer.baseGrid.disabled = true;
```

**Comment by martynasma** [comment]
FYI, just added this:
https://www.amcharts.com/docs/v4/concepts/axes/#Zero_line

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
