### ISSUE TITLE
Amcharts 4.9.16 - Build fails with dependency to pdfmake

### ISSUE THREAD

**Issue by mahesh-chotrani** [amcharts/amcharts4#2741]
**Bug description**

We have been using version **4.9.16**, and it has been working pretty well. 
But since today, our build fails with following error

```
    ERROR in ./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js
    Module not found: Error: Can't resolve 'pdfmake/build/pdfmake.js' in '/home/jenkins/workspace/my_app/web/node_modules/@amcharts/amcharts4/.internal/core/export'
     @ ./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js 69:24-92
     @ ./node_modules/@amcharts/amcharts4/.internal/core/Sprite.js
     @ ./node_modules/@amcharts/amcharts4/.internal/charts/cursors/XYCursor.js
     @ ./node_modules/@amcharts/amcharts4/charts.js
     @ ./node_modules/kernel-charts-module/lib/PieChart.js
     @ ./node_modules/kernel-charts-module/lib/ChartModule.js
     @ ./app/app.js
     @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.js[39m[22m
    Child [1mhtml-webpack-plugin for "index.html"[39m[22m:
```

Has there been any changes in dependencies ? Any pointers appreciated.

**Comment by martynasma** [comment]
What about current version (4.9.33)?

**Comment by mahesh-chotrani** [comment]
We have a pretty big application, and version upgrade may take testing around all the corners, before we release it. 

Though that can be taken up, but looking for an immediate fix

**Comment by mahesh-chotrani** [comment]
Tried with latest version of AmCharts (**4.9.33**), but still the same issue. 

The point is, if I include pdfmake individually to my package.json, I can see `build`, `src` and `node_modules` folders. 
But, with amcharts (`@amcharts\amcharts4\.internal\pdfmake`), only `vfs_fonts.js` and related `td` files are seen. 

There were new check ins for `pdfmake` in last 2 days and amcharts is referring that version (0.1.67). Below is excerpt from yarn.lock

```
pdfmake@^0.1.36:
  version "0.1.67"
  resolved "https://registry.yarnpkg.com/pdfmake/-/pdfmake-0.1.67.tgz#834a2a72dd76485ab7a28f6024565895b1705f52"
  integrity sha512-lc9A+Ztuz9Yvw9Tqd1cnvBImVXchWc4CdHtG2pBT7qhxs2Jn79+OSO04pbLyUcMWo7tv07NVb17bJiji3Epsuw==
  dependencies:
    iconv-lite "^0.6.0"
    linebreak "^1.0.2"
    pdfkit "^0.11.0"
    svg-to-pdfkit "^0.1.8"
    xmldoc "^1.1.2"
```

`xmldoc` is new dependency which was not there 3 days ago. 

Hope, this helps to get more information for the failure above.

**Comment by rnowm** [comment]
@martynasma just in case that helps, we are using it with React, all references I found. with 'pdfmake/build/pdfmake.js' looks like it can be solved in webpack, but that's not how we use it :(

**Comment by Pauan** [comment]
@rnowm If you're not using Webpack, what build system are you using?

**Comment by Pauan** [comment]
@mahesh-chotrani If you downgrade to `pdfmake` version `0.1.66` does it work?

You can do that by specifying this in your `package.json` (and then running `yarn install` or `npm install`):

```json
"dependencies": {
    "pdfmake": "0.1.66"
}
```

**Comment by mahesh-chotrani** [comment]
@Pauan , I have tried this to downgrade the version of pdfmake with `0.1.66` and `0.1.65`, and it didn't work with both.

**Comment by Pauan** [comment]
@mahesh-chotrani Hmmm, we haven't made any changes to pdfmake since 4.9.16, so it sounds like an issue with your build system. What build system are you using?

**Comment by rnowm** [comment]
@Pauan we are using webpack, but we first import amcharts via another repo, that's why I'm a bit confused.
Also pdfmake is imported like so: ^0.1.36. Even if you are not directly changing that component you are exposed to their updates. That's why we first thought the issue could come from them, as they have done changes over the weekend, exact time when our builds started to crash

**Comment by rnowm** [comment]
Also, it's hard to reproduce the issue on our side, as in our local builds are working but we have this error when deploying on the server.

**Comment by rnowm** [comment]
Sorry for the confusion, we finally found the issue as is unrelated to Amcharts.
We had a different version of yarn in both local and the server (1.22.4). That's why we could not reproduce the issue in local.
After cleaning `yarn.lock` file we were able to install again.

**Comment by Pauan** [comment]
@rnowm Yes, that's why I suggested above to downgrade to the older version of pdfmake to see if it would help.

I'm glad you were able to figure it out.
