### ISSUE TITLE
PieChart Legend Markers can't set stroke

### ISSUE THREAD

**Issue by NikolayVitkovMM** [amcharts/amcharts4#2744]
I want all markers to have a small darker border (technically the stroke)  so light colors can be seen easier. To do this I would use an adapter and then AmCharts' color manipulation.
The problem is that it works for XYCharts but It does not for PieChart.

Here are fiddles for example of the behavior:
https://jsfiddle.net/NikolayVitkovMM/m8g9rt5f/3/ - Stacked XYChart - as you can see there is a border on the markers.
https://jsfiddle.net/NikolayVitkovMM/6yLw8xzc/3/ - No border.

Even if I set them to a color manually the same issue persists:
https://jsfiddle.net/NikolayVitkovMM/m8g9rt5f/7/ - Stacked XYChart.
https://jsfiddle.net/NikolayVitkovMM/6yLw8xzc/11/ - PieChart.

The expected behavior is that the PieCharts Legend should act as the XYChart one.

**Comment by martynasma** [comment]
Well, PieSeries works a bit differently in that it decorates markers of the legend itself, mirroring border settings as well.

The solution is to set stroke on slices but hide actual stroke with `strokeOpacity`.

https://jsfiddle.net/amcharts/6r1cbmh9/1/

**Comment by NikolayVitkovMM** [comment]
It a little bit weird and counterintuitive. But this fixes my issue so closing.
