### ISSUE TITLE
Can I use LinePattern for having vertical and horizontal line patterns on each column of bar-chart?

### ISSUE THREAD

**Issue by ashmichheda** [amcharts/amcharts4#2745]
I know ```amCharts``` has ```PatternSet``` with pre-defined patterns. But if I want to define a ```Line Pattern``` with ```horizontal and vertical lines```. 
Is that possible?
Can I define 2 ```pattern instances``` and assign it to the ```fill``` property? 
Or is there any other way round?

Thanks,
Ashmi

**Comment by martynasma** [comment]
There's no way to apply two patterns to a `fill` of a single element, I'm afraid.

The only way would be to create your own custom pattern.

You can do that by extending a `LinePattern` and overriding its `draw` method to draw two sets of lines.

https://github.com/amcharts/amcharts4/blob/master/src/.internal/core/rendering/fills/LinePattern.ts#L52

I'm afraid we don't have a live demo for that.

**Comment by ashmichheda** [comment]
> There's no way to apply two patterns to a `fill` of a single element, I'm afraid.
> 
> The only way would be to create your own custom pattern.
> 
> You can do that by extending a `LinePattern` and overriding its `draw` method to draw two sets of lines.
> 
> https://github.com/amcharts/amcharts4/blob/master/src/.internal/core/rendering/fills/LinePattern.ts#L52
> 
> I'm afraid we don't have a live demo for that.

Okay. If amCharts can give an example demo of custom patterns in future, that would be very helpful.
Thanks!
