### ISSUE TITLE
How to add an offset to a tooltip?

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2746]
Hi. In my map chart, I am using tooltips to display some information.
This is how my tooltip is looking now:

![image](https://user-images.githubusercontent.com/37619567/88634804-89f3ab00-d0bf-11ea-9fa6-817e2131e2a1.png)

I would like to add an offset to the tooltip, so it won't touch and cover the plane.
I was able to add the offset using: `plane.tooltipY = 20` and the output looks good:

![image](https://user-images.githubusercontent.com/37619567/88635053-dc34cc00-d0bf-11ea-9331-349b6195f18d.png)

However, some of the planes are rotated because they are following certain routes, thus the Y Axis of the tooltip gets rotated and the position is wrong:

![image](https://user-images.githubusercontent.com/37619567/88635222-17cf9600-d0c0-11ea-8238-3609ca67f3d0.png)

How can I have the tooltip always on the middle top having a little offset? Thank you!

**Comment by martynasma** [comment]
I suppose the solution would be to center the plane itself:

```
plane.verticalCenter = "middle";
plane.horizontalCenter = "middle";
```

**Comment by directcuteo** [comment]
The plane is already centered using the setup you mentioned. The plane is actually an am4core.Image object, don't know if this matters.
I've created a little CodePen to illustrate the problem: https://codepen.io/directcuteo/pen/YzwbQYj

You can get different rotating positions to test by changing between the line points (first 3 lines of the CodePen):
```
// var geoPoints = getOceaniaPoints();
var geoPoints = getAtlanticPoints();
// var geoPoints = getIndianPoints();
```

**Comment by martynasma** [comment]
I'm a bit stumped why you are using `over` event to enable tooltip.

If I set `tooltipHTML` directly on image, it's being centered properly:

```
planeImage.tooltipHTML = "<div>Lorem ipsum dolor sim amnet</div>";
```

**Comment by directcuteo** [comment]
Well...If I apply `planeImage.tooltipY = 100;` the tooltip still appears in a wrong position.

![image](https://user-images.githubusercontent.com/37619567/88662365-86bde680-d0e2-11ea-826b-ea9982507901.png)

**Comment by martynasma** [comment]
Using `tooltipY` on a rotated and scaled element sounds like trouble :)

Try `dy` instead:

```
planeImage.tooltip.dy = -10
```

**Comment by directcuteo** [comment]
yes, you're right 😆 

Works great with `dy`, I appreciate!
