### ISSUE TITLE
Error - typescript - node_modules/@amcharts/amcharts4/.internal/core/export/Export.d.ts(2034,35): error TS1003: Identifier expected.

### ISSUE THREAD

**Issue by pejano** [amcharts/amcharts4#2747]
Hi all,

I'm trying to build an interactive map for SharePoint 2019 using the [SharePoint Framework (SPFx)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview) and after trying (and failing) with a number of libraries, I am agonisingly close with amCharts. There are version constraints that I am working within and I would like to know whether I can overcome this error.

SPFx for SharePoint 2019 has the following version constraints:

- Node.js v8x or v10x
- npm v4x (although I'm using v6 with no issues)
- TypeScript v2.4 ([hard requirement apparently](https://blog.mastykarz.nl/typescript-version-sharepoint-framework-projects/))
- React v15x (optional)

I have created a vanilla create-react-app with React 15.6.2 using this [guide](https://www.amcharts.com/docs/v4/getting-started/integrations/using-react/) to produce this [map](https://www.amcharts.com/docs/v4/chart-types/map/). Now I am trying to incorporate this into the SPFx boilerplate TypeScript (TSX) code. I have resolved a number of warnings and errors with the final two being:

`Error - typescript - node_modules\@amcharts\amcharts4\.internal\core\export\Export.d.ts(2034,35): error TS1003: Identifier expected.`
`Error - typescript - node_modules\@amcharts\amcharts4\.internal\core\export\Export.d.ts(2034,77): error TS1109: Expression expected.`

The line of code referenced above is:
`readonly canvg: Promise<typeof import("../../canvg/index.js")["default"]>;`

I don't know enough about TypeScript to determine whether or not I can workaround this. I have tried the following:

- Adding `// @ts-ignore` on a line above the imports for `'@amcharts/amcharts4/core'`, `'@amcharts/amcharts4/maps'`, and `'@amcharts/amcharts4-geodata/worldLow'`.
- Also `"skipLibCheck": true` is set in tsconfig.js.

Now, I have used the same code in SharePoint Online SPFx boilerplate code which uses TypeScript 3.5 and this works perfectly fine! So I am satisfied that the amCharts code is valid. I know that [amCharts 4 supports TypeScript 2.9+](https://github.com/amcharts/amcharts4/issues/2531) but I am hoping that someone can help me get around the above.

Failing that, what are my options? Are there amCharts 3 examples written in TypeScript 2.4 and below? I could possibly write the code in plain JavaScript, but I don't know how tightly coupled Microsoft have made their SPFx framework with TypeScript.

If you require the package.json, tsconfig.json or the .ts and .tsx code, please let me know.

Thanks!

**Comment by martynasma** [comment]
I'm sorry, but we require TypeScript 2.9 at minimum. No way around it, I'm afraid.

**Comment by pejano** [comment]
Thanks @martynasma for the quick response. That's a shame because amCharts is a really good product! I will see if I can find a workaround to my problem.
