### ISSUE TITLE
Hover events ignored during animation of columns

### ISSUE THREAD

**Issue by lgerndt** [amcharts/amcharts4#2750]
Hi, hope this is a simple question for you:  I'm finding that hover events are ignored by the library while initially animating the bars of the chart (as evidenced by the fact that it doesn't display the tooltip, which it normally does when there's no animation in progress).

Is this known behavior?  Is there an easy way to insure that the hover events are responded to even during the animation?

**Comment by martynasma** [comment]
This is by design. You can revert this functionality by setting series' [`hideTooltipWhileZooming = false`](https://www.amcharts.com/docs/v4/reference/xyseries/#hideTooltipWhileZooming_property).

**Comment by lgerndt** [comment]
Belated thank you!
