### ISSUE TITLE
How to change color of slider play button?

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2752]
Hi. I am using slider with a play button like in this example: https://www.amcharts.com/demos/map-line-chart-gauge/

I would like to apply my custom theme color to the play button.
The main color I've managed to change like this: `playButton.background.fill = color('#396cf4');`
and also the hover state color:
```
const hs = playButton.background.states.create('hover');
hs.properties.fill = color('#1b4dd6');
```
Now the problem is: 

 How to change the color when the button is clicked (when the click is hold)? There is a default green (`#68dc75`) color on all examples within amCharts demos.

If you hold click this is the color:
![image](https://user-images.githubusercontent.com/37619567/88769163-bfae9780-d184-11ea-8511-8c2417b7dca0.png)

I've even tried `playButton.events.onAll(() => playButton.background.fill = color('red'))` but without any success.
Thank you!

**Comment by xorspark** [comment]
You can use the `"down"` state for this. 

```
const ds =   playButton.background.states.create('down');
ds.properties.fill = '#ff0000';
```

The list of reserved states are mentioned [here](https://www.amcharts.com/docs/v4/concepts/states/#Reserved_named_states).
