### ISSUE TITLE
Series bullet tooltip - programmatically show / hide

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#2753]
**Question**

Hello there. Need some help on this one.

Having some internal logic I determine what series bullets tooltips I have to show when I hover any of them (or legend using other internal logic).
I'm setting id's for series and also for those bullets and let's say I determine that bullets having:
```
 id === ['series_1'] and index [1, 2],
 id === ['series_2'] and index [5,],
 id === ['series_3'] and index [6]
```
I have to show.

How can I do that ?
How can I access my bullets list so I can set  ".isHover" = true / false on each one from my list?

![image](https://user-images.githubusercontent.com/21243081/88782644-7cf5bb00-d196-11ea-81e0-68fdef660255.png)

I attached a pen to help possible response.

https://codepen.io/aniov/pen/NWxogVa

Thank you in advance.

**Comment by martynasma** [comment]
I would use `showTooltipOn` property on series bullet, e.g.:

```
// Show tooltips on second and third bullet in series
series.bullets.getIndex(0).clones.getIndex(1).showTooltipOn == "always";
series.bullets.getIndex(0).clones.getIndex(2).showTooltipOn == "always";
```

**Comment by aniov** [comment]
I want to show them only on mouse hover on bullets. If I do that how can I set them to hidden on mouse out ?

**Comment by martynasma** [comment]
I understand. So to sum up: when your logic needs to display tooltip on bullet number 3:

```
var bullet = series.bullets.getIndex(0).clones.getIndex(1);
bullet.showTooltipOn == "always";
bullet.showTooltip();
```

When it needs to hide it:

```
var bullet = series.bullets.getIndex(0).clones.getIndex(1);
bullet.showTooltipOn == "hover";
bullet.hideTooltip();
```

**Comment by aniov** [comment]
Thank you for your solution.

I have implemented it for 2 ".yAxes" types: ValueAxis & CategoryAxis with hover over **legend** and series **bullets**: https://codepen.io/aniov/pen/NWxogVa?editors=0010
and is working ok with one "small" issue.

As you can see I have a problem on series with close oY values, the tooltips are overlapping. Is there a way to make them auto arrange like in a category ox chart ?

![image](https://user-images.githubusercontent.com/21243081/89048084-fe487b80-d357-11ea-96ca-7a8754ce604b.png)

If you think this second question doesn't belong here I can open another "issue".

Thank you.

**Comment by martynasma** [comment]
I'm afraid tooltips do not check each other for overlapping. I don't think there's a lot you can do about it :(

**Comment by aniov** [comment]
That's not good news :)

So let's set then the tooltips on series to take advantage of that auto-arange.
For my example setting the tooltips on series with **Catgegory** axes works ok with small modifications , but how can I do the same for **ValueAxes** ?

https://codepen.io/aniov/pen/gOrYmRZ?editors=0010

Thnak you.

**Comment by martynasma** [comment]
For `ValueAxis` you can use `snapToSeries` to specify a list of series cursor should snap to. It will show a tooltip for it.

Unfortunately, in such setup only a single tooltip will be shown, not multiple ones for the same X value.
