### ISSUE TITLE
Space between  Yaxis values and graph in left side

### ISSUE THREAD

**Issue by sureshhallyali** [amcharts/amcharts4#2754]
Its taking gap between   Yaxis values and graph in left side

 - amCharts version: 4
 - Browser and its version: Google Chrome,
![bugAmchart](https://user-images.githubusercontent.com/57383836/88822548-a12ab980-d1e1-11ea-8478-4b00c3bc6253.png)

 - Related frameworks and their versions:Angular

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by sureshhallyali** [comment]
ok

**Comment by sureshhallyali** [comment]
solved thank you
