### ISSUE TITLE
Interacting with a chart disrupts the layout of the page (with multiple charts)

### ISSUE THREAD

**Issue by stla** [amcharts/amcharts4#2755]
Hello,

 Here is my [jsfiddle](https://jsfiddle.net/stla/gz4y0532/). When I click on a legend item of the second chart, the layout is disrupted: the first chart slightly goes down. I'm wondering how one can avoid that. With CSS or with an amcharts option? I encountered a similar issue with a fluid Bootstrap layout.

![amcharts4issue](https://user-images.githubusercontent.com/4466543/88836585-31173600-d1d7-11ea-9ff6-ddff712b19f3.gif)

**Comment by stla** [comment]
I've just found that this issue is fixed by setting `display: inline-flex` instead of `display: inline-block`. Is it the way to go?

**Comment by martynasma** [comment]
Frankly, I'm not entirely sure what;s going on there with the inline block. I would use `float: left` thought, not `inline-block`.
