### ISSUE TITLE
Is there any way to get the Hex color code of a radar chart column on clicking of a radar label instead of clicking on radar column?

### ISSUE THREAD

**Issue by AbhishekKadavergu** [amcharts/amcharts4#2756]
I have been trying to get the Hex color code of the radar column on clicking radar labels but I'm failed. I know how to get Hex color code on clicking the radar column but my requirement is to get the Hex color on clicking the label. Please suggest any ideas. Following is the code to get Hex color on clicking the Column `          series.columns.template.events.on(
            "hit",
            function (ev) {
              //this.onLabelClick(ev.target.dataItem.dataContext["category"]);
              console.log(ev.target.fill["hex"]);
              //this.impactService.setColorCode(ev.target.fill["hex"]);
              console.log(ev.target);
            },
            this
          );`
please find the code in given link https://codepen.io/abhishekkadavergu/pen/qBbzLyQ

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
