### ISSUE TITLE
How to stop interactions with a tooltip?

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2757]
Hello! I am pretty much implementing something like this: https://www.amcharts.com/demos/map-line-chart-gauge/

I am facing a silly problem: if you pause the slider, most likely a tooltip will be shown within the map (for example above Hawaii).
Now if you hover Hawaii, the tooltip will hide itself.

I expect if the user pauses the animation, all interactions with the tooltip will be stopped. For the user the message is not an actual tooltip, it's just 'something' and it should not interact with the hover state but have a "videolike" behaviour (no interactions).

Is there any way to stop interactions for a tooltip or tooltip's parent ?

**Comment by martynasma** [comment]
If tooltip is for some series element, you can disable it like this:

```
series.tooltip.disabled = true;
```

For a chart-wide tooltip:

```
chart.tooltip.disabled = true;
```

**Comment by directcuteo** [comment]
`chart.tooltip.disabled = true` hides the tooltip. I don't want to disable the tooltip, but the interaction that hides/shows the tooltip.
I expect if I show the tooltip programatically (like here when the slider reaches specific value) , then I also can hide the tooltip only programatically and not when hovering in/out.

**Comment by martynasma** [comment]
Not sure what to suggest. Maybe if you need to temporarily disable tooltip on hover on some element you can set its `hoverable = false`?

**Comment by directcuteo** [comment]
I think if I need such isolated behavior, I should use a custom `Container` for which I have better control.
