### ISSUE TITLE
input csv data via <input type="file" id="input">

### ISSUE THREAD

**Issue by julrie** [amcharts/amcharts4#2758]
Is it somehow possible to input (csv) data via the `<input type="file" id="input">` methode?
My problem:
html:
```
....
<input type="file" id="input">
<input type="submit" value="Submit"id="submit">
....
```

javascript:
```
document.getElementById("submit").addEventListener("click",myFunction);

function myFunction() {

var chart = am4core.create("chartdiv", am4charts.XYChart);

chart.dataSource.url = document.getElementById("myFile").files[0];
chart.dataSource.parser = new am4core.CSVParser();
chart.dataSource.parser.options.useColumnNames = true;
chart.dataSource.parser.options.delimiter = ";";
```
Result in console: `GET http://.../[object%20File] 404 (Not Found)`

Do you have solution for my problem?

**Comment by martynasma** [comment]
I don't think you can use a file from the input field as a URL.

I'm not sure if this can be done completely in browser as browser's JS does not have access to local file system.

In any case, it's a little bit out of scope of amCharts.
