### ISSUE TITLE
How to remove space on the left and right side of a chart

### ISSUE THREAD

**Issue by nagabhushant** [amcharts/amcharts4#2759]
I am displaying data on column chart and i hiding Axis label on the left but still little space is taken on the left and right side of the chart as shown in the attached snap shot.
I am using amcharts4 version and running in google chrome.
![ColumnChart](https://user-images.githubusercontent.com/65383847/89146909-c36e5f80-d572-11ea-851d-bf3dcea8eb55.JPG)

Here is my code :

var chartData = [{"TimeFrame" : "31/07", "COI" : "-21", "ToolTipTxt" : ""},{"TimeFrame" : "30/07", "COI" : "1", "ToolTipTxt" : ""},{"TimeFrame" : "29/07", "COI" : "5", "ToolTipTxt" : ""},{"TimeFrame" : "28/07", "COI" : "-7", "ToolTipTxt" : ""},{"TimeFrame" : "27/07", "COI" : "0", "ToolTipTxt" : ""}]};

var chart = am4core.create("div_Chart", am4charts.XYChart);

    chart.data = chartData;
    var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
    categoryAxis.renderer.grid.template.location = 0;
    categoryAxis.dataFields.category = "TimeFrame";
    //categoryAxis.renderer.minGridDistance = 30;
    categoryAxis.renderer.inversed = true;
    categoryAxis.renderer.grid.template.disabled = true;
    categoryAxis.renderer.baseGrid.disabled = true;
    categoryAxis.renderer.inside = true;
    categoryAxis.renderer.labels.template.valign = "center";
    categoryAxis.renderer.labels.template.fontSize = 9;

    
    var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
    valueAxis.renderer.minWidth = 10;
    //valueAxis.min = -1000;
    valueAxis.cursorTooltipEnabled = true;
    valueAxis.renderer.labels.template.fontSize = 9;
    valueAxis.renderer.grid.template.disabled = true;
    valueAxis.paddingLeft = -30;
    valueAxis.paddingRight = -30;
   // valueAxis.layout = "absolute";
    valueAxis.renderer.labels.template.disabled = true;

    // Create series
    var series = chart.series.push(new am4charts.ColumnSeries());
    series.sequencedInterpolation = true;
    series.dataFields.valueY = "COI";
    series.dataFields.categoryX = "TimeFrame";
    series.columns.template.strokeWidth = 0;
    series.columns.template.column.fillOpacity = 0.8;
    series.tooltip.label.textAlign = "middle";
    series.tooltip.pointerOrientation = "down";
    series.tooltip.dy = -5;
    series.stroke = "#FF2E00";
    series.fill = "#FF2E00";
    series.fillOpacity = 0.4;

    series.columns.template.tooltipText = "{categoryX}\n[bold]COI : {valueY}%[/]\n{ToolTipTxt}";
    series.columns.template.showTooltipOn = "hover";
    series.columns.template.tooltipY = 0;

**Comment by martynasma** [comment]
You may remove chart's padding:

```
chart.paddingLeft = 0;
chart.paddingRight = 0;
```

Also not sure that adding negative padding to the value axis has any effect.

**Comment by nagabhushant** [comment]
I update as you suggested but still there is some space as shown below

![image](https://user-images.githubusercontent.com/65383847/89259115-3f39dc00-d647-11ea-8c97-e9ef9caa3e86.png)

here is the html code for that box. I haven't given any extra space here.

<div class='col-md-3'>
--
  | <div class='panel panel-default'>
  | <div class='panel-title'><a href='FuturesOIPage.aspx?s=BANKNIFTY' target='_blank'>BANKNIFTY</a></div>
  | <div id='div_BANKNIFTY' style='height:200px; width:100%;'> </div>
  | </div>
  | <div style='display:none' id='div_BANKNIFTY_Json'>{"Data" : [{"TimeFrame" : "03/08", "COI" : "14", "ToolTipTxt" : ""},{"TimeFrame" : "31/07", "COI" : "-21", "ToolTipTxt" : ""},{"TimeFrame" : "30/07", "COI" : "1", "ToolTipTxt" : ""},{"TimeFrame" : "29/07", "COI" : "5", "ToolTipTxt" : ""},{"TimeFrame" : "28/07", "COI" : "-7", "ToolTipTxt" : ""}]}</div>
  | </div>

**Comment by nagabhushant** [comment]
Looks like i can't paste html code here properly.

![image](https://user-images.githubusercontent.com/65383847/89259239-80ca8700-d647-11ea-9129-afd01eb2a972.png)

**Comment by nagabhushant** [comment]
Sorry no worries looks like there was some padding on left and right in css style sheet.

Thanks for the solution.

**Comment by martynasma** [comment]
Thanks for the update! Feel free to close this if you have figured this out.
