### ISSUE TITLE
How to display tooltips in axis break expanded area?

### ISSUE THREAD

**Issue by vidyashreen1991** [amcharts/amcharts4#2760]
I am trying to add an axis break to the value axis. It is working fine, but the tooltip is not getting displayed in the expanded area.

// Adding Axisbreaks to value axis
    let valueAxis = chart.yAxes.getIndex(0);
    var axisBreak = valueAxis.axisBreaks.create();
    axisBreak.startValue = 50000;
    axisBreak.endValue = 490000;
    var d = (axisBreak.endValue - axisBreak.startValue) / (valueAxis.max - valueAxis.min);
    axisBreak.breakSize = 0.05 * (1 - d) / d; // 0.05 means that the break will take 5% of the total value axis height
    axisBreak.events.on('over', function() {
      axisBreak.animate(
        [{ property: 'breakSize', to: 1 }, { property: 'opacity', to: 0.1 }],
        1500,
        am4core.ease.sinOut
      );
    });
    axisBreak.events.on('out', function() {
      axisBreak.animate(
        [{ property: 'breakSize', to: 0.005 }, { property: 'opacity', to: 1 }],
        1000,
        am4core.ease.quadOut
      );
    });

**Comment by martynasma** [comment]
Can you please clarify what tooltip do you mean? Is it axis tooltip, or series tooltip, or maybe something else?

If you could also post your chart on CodePen that would be great.
