### ISSUE TITLE
Axis break events are not firing if it is added by adding corresponding JSON config

### ISSUE THREAD

**Issue by vidyashreen1991** [amcharts/amcharts4#2761]
Below is the config which is added for axis break. Events are not getting fired. I have temporarily resolved it by attaching the events in the callback of 'chartReady' event. Please let me know what is wrong with the config.

axisBreaks: [{
        startValue : 50000,
        endValue   : 490000,
        breakSize  : 0.05,
        events     : {
          'over'(ev) {
            var axisBreak = ev.target;
            axisBreak.animate(
              [{ property: 'breakSize', to: 1 }, { property: 'opacity', to: 0.1 }],
              1500,
              am4core.ease.sinOut
            );
          },
          'out'(ev) {
            var axisBreak = ev.target;
            axisBreak.animate(
              [{ property: 'breakSize', to: 0.05 }, { property: 'opacity', to: 1 }],
              1000,
              am4core.ease.quadOut
            );
          }
        }
      }]

**Comment by martynasma** [comment]
This doesn't look like a valid code. Can you please post your code in a CodePen or jsFiddle?
