### ISSUE TITLE
Min height on stacked column chart

### ISSUE THREAD

**Issue by r-s-sandbox** [amcharts/amcharts4#2762]
I'm trying to add labels inside the bars of a stacked column chart and struggling to fit the text in. Is it possible to set a min height on the bar?

https://jsfiddle.net/gvnrw4p7/

Alternatively when I try positioning the label text beneath the x-axis, it gets cut off.

**Comment by martynasma** [comment]
No, I'm afraid there's no way to set min-height of the stacked column. Sorry.
