### ISSUE TITLE
 mouse hover on country show different  cursor

### ISSUE THREAD

**Issue by sureshhallyali** [amcharts/amcharts4#2764]
**  Map Chart, if we mouse  hover on country by default show pointer cursor for all country so  what i needed if country don't have value that time  cursor  not-allowed icon has to show**

for example:
united state and India has value then need this property   {cursor: default;} other all country  don't have  value then this disables  { cursor: not-allowed;} 

codePen:
https://codepen.io/sutya/pen/zYqxOvz

**Comment by sureshhallyali** [comment]
Thank you in advance

**Comment by sureshhallyali** [comment]
@martynasma  please can you response

**Comment by martynasma** [comment]
Something like this will work:

```
// Add some data
polygonSeries.data = [{
  "id": "US",
  "name": "United States",
  "value": 100,
  "fill": am4core.color("blue"),
  "cursor": am4core.MouseCursorStyle.pointer
}, {
  "id": "IN",
  "name": "India",
  "value": 50,
  "fill": am4core.color("blue"),
  "cursor": am4core.MouseCursorStyle.pointer
}];

// Bind "fill" property to "fill" key in data
polygonTemplate.propertyFields.fill = "fill";
polygonTemplate.propertyFields.cursorOverStyle = "cursor";
```

**Comment by sureshhallyali** [comment]
it's working fine but in angular 9  its giving error:
**Error:**

Property 'cursorOverStyle' does not exist on type '{ multiGeoPolygon?: string; multiPolygon?: string; visualLatitude?: string; visualLongitude?: string; precision?: string; zoomLevel?: string; zoomGeoPoint?: string; layout?: string; fontWeight?: string; ... 97 more ...; userClassName?: string; }'.
    
    191               polygonTemplate.propertyFields.cursorOverStyle = "cursor";
                                                     ~~~~~~~~~~~~~~~

**Comment by martynasma** [comment]
Just use generics:

```
(<any>polygonTemplate).propertyFields.cursorOverStyle = "cursor";
```

**Comment by sureshhallyali** [comment]
Thank you so much its working fine now.
