### ISSUE TITLE
How to enable horizontal full width cursor line? (May be bug)

### ISSUE THREAD

**Issue by yenniSuresh** [amcharts/amcharts4#2765]
The example shown in documentation is for vertical [full width cursor line](https://www.amcharts.com/docs/v4/concepts/chart-cursor/#Enabling_full_width_cursor_lines). 

[Here](https://codepen.io/yennisuresh/pen/xxVbXNa) is the codepen where am trying to achieve horizontal full width cursor line.

Am not getting expected output for horizontal case as it is in vertical case in documentation.

**Comment by martynasma** [comment]
It's not about vertical or horizontal. It's about supported axis types.

`DateAxis` and `CategoryAxis` support full-width cursors because they have exact units of increment.

`ValueAxis` does not because it's just a numeric scale.

**Comment by yenniSuresh** [comment]
Correct, it worked with CategoryAxis. thanks
