### ISSUE TITLE
Axis Break Start value dynamic calculation

### ISSUE THREAD

**Issue by Lathaviswa** [amcharts/amcharts4#2766]
Hi,
  
var axisBreak = valueAxis.axisBreaks.create();
axisBreak.startValue = 2100;
axisBreak.endValue = 22900

 How to calculate Startvalue and endvalue based on the data  dynamically

**Comment by martynasma** [comment]
Could you please explain what exactly you want to calculate? Can you also post your chart (what you have so far) on CodePen?

**Comment by pcartwright81** [comment]
I created a demo by copying https://codepen.io/team/amcharts/pen/aGNvgY and then changing the value to 10000.  What I was trying to do is make a dynamic line break from around 200-9000.  On sets of data that are constantly changing a dynamic line break could be calculated to fill data gaps.  The data I am looking at has a 70000 gap which looks good with a static line break, but I am worried about putting a line break and the data being cut off.  Also I realize that log scale was created just for this purpose, but we were told not to use it.
