### ISSUE TITLE
Check if legend item has been hidden or shown

### ISSUE THREAD

**Issue by magijoylarin** [amcharts/amcharts4#2767]
Hi, 

I used the "hit" event to listen when a legend item is clicked. In the event function, I want to check if item has been hidden or shown. But when I checked the hidden property of the element, it always returns false.

Here is my code.

`
            var chart = am4core.createFromConfig({
                "series": [{
                    "type": "PieSeries",
                    "dataFields": {
                        "value": "value",
                        "category": "category"
                    }
                }],
                "type": am4charts.PieChart,
                "container": "pie-chart",
                "data": data,
                "legend": {
                    "position": 'right',
                    "contentAlign": "left",
                    "labels": {
                        "marginRight": 120,
                        "truncate": false
                    },
                    "width": 400,
                    "fontSize": 16,
                    "itemContainers": {
                        "template": {
                            "events": {
                                "hit": checkIfItemIsHidden
                            }
                        }
                    },
                    "valueLabels": {
                        "align": "right",
                        "textAlign": "end"
                    }
                }
            });

            function checkIfItemIsHidden(e) {
                    console.log(e.target.hidden); // returns false
                    console.log(e.target.disabled); // returns false
                    console.log(e.target.dataItem.hidden); // returns false
                    console.log(e.target.dataItem.dataContext.hidden); // returns false
            }
`
 In amcharts 3, using "e.dataItem.hidden" works. Please let me know how I am supposed to check it in amcharts 4.

**Comment by Rohitbels** [comment]
I had used this:
`seriesObj.dataFields.hiddenInLegend = hiddenInLegendDataField;`

Try 'dataItem.hiddenInLegend'

**Comment by martynasma** [comment]
I would use this:

```
chart.legend.itemContainers.template.events.on("toggled", function(ev) {
  console.log(ev.target.isActive ? "off" : "on")
});
```

**Comment by magijoylarin** [comment]
> .

Thanks! ev.target.isActive works for me.
