### ISSUE TITLE
Toggling specific non-adjacent radar chart data items?

### ISSUE THREAD

**Issue by elenapan** [amcharts/amcharts4#2768]
**Question**

Greetings,

I am using a Radar chart much like the [demo chart shown here](https://www.amcharts.com/demos/radar-chart/):

<img src="https://user-images.githubusercontent.com/31134749/89649089-dfeafe80-d8c8-11ea-9a0d-ee7f5d19a4df.png" data-canonical-src="https://user-images.githubusercontent.com/31134749/89649089-dfeafe80-d8c8-11ea-9a0d-ee7f5d19a4df.png"  height="300" />

I would like to toggle specific data items by clicking on them so that, for instance, the `Ireland` and `Austria` items are temporarily hidden from the chart.
I am aware that I can enable a slider and use partial axis ranges in order to only show a range of data items, but I was wondering if it is possible to toggle specific, non-adjacent data items by clicking on them or their label.

I did not manage to find information about this in the documentation or past github issues.
Thank you in advance.

**Environment**

- amCharts version: 4
- Using pure Javascript

**Comment by martynasma** [comment]
There's no way to toggle specific data items, save for modifying chart's data.

Something like this:

```
categoryAxis.renderer.labels.template.events.on("hit", function(ev) {
  chart.data.splice(ev.target.dataItem.index, 1);
  chart.invalidateData();
});
```

https://codepen.io/team/amcharts/pen/a84d3164c22e3e298ca8358ad7de957f?editable=true
