### ISSUE TITLE
first month format in DateAxis without year

### ISSUE THREAD

**Issue by Gheeroppa** [amcharts/amcharts4#2770]
[amChart V4 - ReactJs]

In a XYChart I am trying to set on the x-Axes, the twelve months as lables, from Jan to Dec, but the first month has also the Year (yyyy), in my case, Jan 2020.

`let dateAxis = chart.xAxes.push(new am4charts.DateAxis());`

How can I show just the name of the month as first x label?

**Comment by martynasma** [comment]
Please refer to this documentation:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Period_change_format
