### ISSUE TITLE
zIndex adapter on Bullet or Bullet.circle does not trigger

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#2771]
https://codepen.io/dimitrios-kanellopoulos/pen/XWdbJKL?editors=1111

In this case the zIndex adapter doesn't trigger.

**Comment by martynasma** [comment]
It's by design. The `zIndex` is a bit different from other properties. The layout mechanism maintains an index of elements and their positions, and does not refer to actual properties of the element in most cases, as it would be a serious bottleneck in performance.

If you need to selectively set `zIndex` of a bullet, I suggest using some other property as an adapter, then setting zIndex explicitly:

```
bullet.adapter.add('dx', (value, target, key) => {
  target.zIndex = 10;
  return dx;
});
```

Please not that manipulating `zIndex` invalidates layout of the parent container, so do that only if absolutely necessary.

**Comment by jimmykane** [comment]
@martynasma that doesn't seem to work. 

See example: https://codepen.io/dimitrios-kanellopoulos/pen/XWdbJKL?editors=1111 

2 bullets from 2 different series set in the same container overlap each other. One is bigger and covers the smaller. 
I cannot bring the smaller in front.

**Comment by jimmykane** [comment]
I tried in many ways to set and index of a bullet and could not manage that. :-/

**Comment by martynasma** [comment]
OK, so the issue is not with the `zIndex` of individual bullets, because all bullets from all series are not children of a single container - each series has own `bulletsContainer`.

So if your task is to prioritize one series' bullets over the other, you can use `zIndex` of series' `bulletsContainer`:

```
series.bulletsContainer.zIndex = field === 'value2'?  10 : 20;
```

If you need to set `zIndex` of each individual bullet based on its actual value, the task becomes much more complicated :)

**Comment by jimmykane** [comment]
I need the more complicated task.

Each bullet needs it's zindex from the dataitem which holds info from all
the series.

So yeah somehow to order the bullets independently of the series order.

**Comment by martynasma** [comment]
OK, so here's how to make it work.

1) Override series' `bulletsContainer` with the same container for all series:

```
series.bulletsContainer = chart.bulletsContainer;
```

2) Apply zIndex to individual bullets either via adapter like I suggested before or via events, e.g.:

```
chart.events.on("ready", function() {
  chart.series.each(function(series) {
    series.bullets.each(function(bullet) {
      bullet.clones.each(function(item) {
        if (item.dataItem && item.dataItem.valueY) {
          //item.zIndex = 10000 - item.dataItem.valueY;
          //item.zIndex = 10000 - item.circle.radius;
          item.zIndex = Math.round(Math.random() * 1000);
        }
      })
    })
  })
});
```

**Comment by jimmykane** [comment]
@martynasma that worked thanks a lot. 

However, when I set `series.bulletsContainer = chart.bulletsContainer;` then the performance is dramatically crippled.

**Comment by martynasma** [comment]
Well, cramming all bullets into single container is the only way to control their zIndex individually.

I'm not sure why it affects performance dramatically for you. I suppose you have a lot of bullets (much more than in our test pen). In that case, setting a bunch of zIndex values would trigger a lot of excessive reordering of container elements.

**Comment by jimmykane** [comment]
~2K bullets :-O

**Comment by jimmykane** [comment]
Specifically its about this chart: 

<img width="626" alt="Screenshot 2020-08-12 at 18 54 49" src="https://user-images.githubusercontent.com/1268723/90044035-558e0a80-dccd-11ea-9c6f-841f4d20af55.png">


I have added according to your @martynasma logic multiple series with their data. Each series has its own set of bullets for each day. 

Each bullet has a color based on a sport type eg red = weights and green = walking. 

So on a year set of days it can be about 10-12 different bullets for each day for example max.

**Comment by zeroin** [comment]
Could you make a codepen of this specific chart+data? It would help a lot.

**Comment by jimmykane** [comment]
@martynasma @zeroin  here you go

https://codepen.io/dimitrios-kanellopoulos/pen/wvGBXXB?editors=0011

Look for 

```
 // Look here 
    bubbleSeries.bulletsContainer = chart.bulletsContainer;
```

Notice that commenting that line has a huuuuuge impact on performance.  

At the example I posted there is no zindex logic there (I just didn't add it) but still, the performance imo is very very bad

**Comment by jimmykane** [comment]
To note: The bullets are not many. 460.

**Comment by martynasma** [comment]
Hi Jimmy,

I'm afraid there's nothing else we can suggest as to how to speed up custom zIndex application across bullets of multiple series. Sorry :(

**Comment by jimmykane** [comment]
One comment here: 

Removing the setter of a new cursor dramatically improves performance but still not up to quite smooth 

Commenting out the line of : 


```
      // chart.cursor = new am4charts.XYCursor(); // Or any other cursor 
```
