### ISSUE TITLE
How can I get the assigned background color for tooltip?

### ISSUE THREAD

**Issue by magijoylarin** [amcharts/amcharts4#2772]
**Question**

Hi, I'm trying to create a custom theme for my pie chart. I want to get the assigned color of the tooltip for the legend. By default, the color can be seen in the background fill of the tooltip. When I print the target and inspect the background fill in the console, I can see the assigned color. But when I try to access the target.background.fill.hex, the output is always white (#ffffff).

`
if (target instanceof am4core.Tooltip && target.label) {
        console.log(target);
        console.log(target.background.fill.hex);
}
`

Any ideas?

**Comment by martynasma** [comment]
Can you post your whole chart code on CodePen? I'm not entirely sure where your code snippet goes to.

**Comment by magijoylarin** [comment]
Here is the [code](https://codepen.io/magijoylarin/pen/eYZNPed).

**Comment by martynasma** [comment]
A theme is applied to an object before it has any data or other settings set to it, hence the backround coming up as white every time.

If you need to modify background color on a fully initialized object, you're better off using an adpater:

```
pieSeries.tooltip.background.adapter.add("fill", function(fill, target) {
  console.log(fill);
  return fill;
});
```

**Comment by magijoylarin** [comment]
> A theme is applied to an object before it has any data or other settings set to it, hence the backround coming up as white every time.
> 
> If you need to modify background color on a fully initialized object, you're better off using an adpater:
> 
> ```
> pieSeries.tooltip.background.adapter.add("fill", function(fill, target) {
>   console.log(fill);
>   return fill;
> });
> ```

Using this, I only got the fill of the previously hovered tooltip and not the current one. 

In pie series, the tooltip inherits its color from the slice right? Is it possible to get the color of the slice from the tooltip object?

**Comment by martynasma** [comment]
Try `target.fill`.

**Comment by magijoylarin** [comment]
I tried and got maximum call stack exceeded. I think it infinitely loops in the fill function.

**Comment by martynasma** [comment]
Ah yes, my bad. Request for `fill` triggers the adapter.

What are you trying to do exactly? Do you need to modify something in the tooltip itself when it's shown, or you need color for something else?

**Comment by magijoylarin** [comment]
I want the tooltip to look like the balloontext in amcharts 3. To do that, I would need the inherited color in the stroke and the background fill to be white.

**Comment by martynasma** [comment]
That's what you should have started with :)

```
pieSeries.tooltip.getFillFromObject = false;
pieSeries.tooltip.getStrokeFromObject = true;
```

https://www.amcharts.com/docs/v4/concepts/tooltips/#Color_inheritance

**Comment by magijoylarin** [comment]
@martynasma Thank you so much! Sorry for making things complicated. lol

**Comment by sajidAzeem** [comment]
> That's what you should have started with :)
> 
> ```
> pieSeries.tooltip.getFillFromObject = false;
> pieSeries.tooltip.getStrokeFromObject = true;
> ```
> 
> https://www.amcharts.com/docs/v4/concepts/tooltips/#Color_inheritance

Even If I do the same, It's not working for me. I  need the inherited color in the stroke and the background fill to be white.
