### ISSUE TITLE
Tooltip is not removed when removing parent element

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2773]
Hi. 
I am creating a tooltip element on my `Container` object.
I am triggering the tooltip manually using `container.showTooltip();`

At some point I destroy the `Container` by destroying the series in which the `Container` was created like this: `chart.series.removeValue(mySeriesWhereTheContainerIs)`.

When I destroy the series, the tooltip may be visible.
In the case it is visible, it is not destroyed, and remains active, even if the container below it is not visible anymore.

Before: 
![image](https://user-images.githubusercontent.com/37619567/89770125-f8485c80-db06-11ea-89c4-e2779b9a7e10.png)

And after:
![image](https://user-images.githubusercontent.com/37619567/89770180-11510d80-db07-11ea-8bb0-07e3e2bc9fe8.png)

**Comment by martynasma** [comment]
I suggest simply hiding tooltip before destroying the container:

```
container.hideTooltip();
```
