### ISSUE TITLE
How to use specific property of amcharts in Multiple Same charts without repetition?

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#2777]
I created three stacked bar charts using amchart libraries on the same page but some property is repeated how we minimized it?
I share my code 

 createStackBarChart1(){

        var chart = am4core.create("chartdiv3", am4charts.XYChart);
        chart.padding(20,30,0,0);  
            // Add data
            chart.data = [];
            
            if(chart.data.length > 0){
              **// Create axes**
              var categoryAxis = chart.yAxes.push(new am4charts.CategoryAxis());
              categoryAxis.dataFields.category = "host";
              categoryAxis.renderer.grid.template.location = 0;
              categoryAxis.renderer.minGridDistance = 20;
              categoryAxis.renderer.cellStartLocation = 0.1;
              categoryAxis.renderer.cellEndLocation = 0.9;
              categoryAxis.renderer.labels.template.fill = am4core.color("#fff");
              categoryAxis.renderer.grid.template.stroke = am4core.color("#fff");
            
             **//Value Axis**
              let label = categoryAxis.renderer.labels.template;
                label.wrap = true;
                label.maxWidth = 120;
              var  valueAxis = chart.xAxes.push(new am4charts.ValueAxis());
              valueAxis.min = 0;
              
              valueAxis.renderer.labels.template.fill = am4core.color("#fff");
              valueAxis.renderer.grid.template.stroke = am4core.color("#fff");

        
        
              // Create series
              function createSeries(field, name, stacked) {
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.dataFields.valueX = field;
                series.dataFields.categoryY = "host";

                
                series.name = name;
                series.tooltip.label.wrap = true;
                series.tooltip.label.width = 200;
                //series.columns.template.tooltipText = "{host}\n[bold]Uploads: {Upload}\n[bold]Downloads:{Download}";
                series.columns.template.tooltipText = "{host}\n[bold]{name}: [bold]{valueX}[/]";
                series.stacked = stacked;
                series.columns.template.width = am4core.percent(95);
              }
              createSeries("Upload", "Uploads", false);
              createSeries("Download", "Downloads", true);
              
              
              // Add legend
              chart.legend = new am4charts.Legend();
              chart.legend.labels.template.fill = am4core.color("#fff");
              
            }
            **else**{
              let indicator = chart.tooltipContainer.createChild(am4core.Container);
                  indicator.background.fill = am4core.color("#fff");
                  indicator.background.fillOpacity = 0.5;
                  indicator.width = am4core.percent(100);
                  indicator.height = am4core.percent(100);
              
              let label = chart.createChild(am4core.Label);
                  label.text = "No Data Found!";
                  label.fill = am4core.color("#F9F871");
                  label.fontSize = 20;
                  label.align = "center";
                  label.isMeasured = false;
                  label.x = am4core.percent(50);
                  label.horizontalCenter = "middle";
                  label.y = 180;
            }
        });  
    }

This is the **first stacked bar chart and another two charts is just similar to this one** here you see some sections like /**/Create Axes** and **//Value Axes** and **else section** same code I used in two others charts **so how I minimize it?**

**Comment by martynasma** [comment]
This seems like a generic coding question, not related specifically to amCharts.

**Comment by Swaraj55** [comment]
Thanks @martynasma 
I have one more question How we do common tooltip in the stacked and Column chart?
This means no individual tooltip show it can be shown in the single tooltip if hover over the stacked.

But as you see in this example they are different tooltip for different stacked.
[https://codepen.io/pen/](url)

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
