### ISSUE TITLE
ToolTip doesn't work with ClockHand

### ISSUE THREAD

**Issue by netcommerce** [amcharts/amcharts4#2778]
I'm follow this example to build a Gauge Graph with AmCharts: 
https://www.amcharts.com/demos/gauge-with-bands/

After some modifications, I added a new ClockHand element as can be seen in the image below 
![Gauge](https://user-images.githubusercontent.com/64865739/89908942-eb8a3e00-dbc4-11ea-9f31-f054e35ca1f4.png)
[https://i.stack.imgur.com/ElYyc.png].

In the gauge graph, I adde a second ClockHand (blue color) and try to add a ToolTip..

But when I tryed to use this ToolTip, It' not showing in the correct position. I'm using this code:

var hand2 = chartdivGauge.hands.push(new am4charts.ClockHand());
hand2.innerRadius = am4core.percent(95);
hand2.radius = am4core.percent(100);
hand2.startWidth = 20;
hand2.pin.disabled = true;
hand2.value = 50; 
hand2.fill = am4core.color('blue');
hand2.stroke = am4core.color('blue');
hand2.tooltipText = "My Tool Tip";

So, how can I fix that? How can I put this Tooltip in the right position, close to clockhand.

Thanks!

**Comment by martynasma** [comment]
A `ClockHand` is a big element, consisting of many sub-elements.

I suggest you put tooltip on its `hand` sub-element:

```
hand2.hand.tooltipText = "My Tool Tip";
```

**Comment by netcommerce** [comment]
It works as @martynasma said.
