### ISSUE TITLE
Bullets JSON config

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#278]
Hello,

I try to add bullets on my LineSeries but it doesn't work.

https://codepen.io/ptorrent/pen/eLJEeb

What am I doing wrong?

**Comment by ptorrent** [comment]
Solved (doc example not working) 

![image](https://user-images.githubusercontent.com/6083644/44618580-16b0e100-a879-11e8-9c7d-91fa28834cb2.png)

This works : 

![image](https://user-images.githubusercontent.com/6083644/44618585-216b7600-a879-11e8-8143-f54e14e39da2.png)

**Comment by martynasma** [comment]
Are you sure the syntax from docs does not work?

I just tried it and it worked perfectly.

Here's an example:
https://codepen.io/team/amcharts/pen/5c517f1ba3126fe7710e9e856e7d08ea

If it wasn't working for you, it must have been something wrong with the config.

If you'd like to resolve it, just post your chart code here (or as a CodePen). I'll be glad to take a look.

**Comment by ptorrent** [comment]
Her my working example : 

https://codepen.io/ptorrent/pen/eLJEeb

I don't know what I did yesterday. What's de difference between : 

```javascript 
[ { children : [ { type : Rectangle } ]  }  ] 
```
and bullets : 
```javascript 
[ { type : Rectangle } ] 
```

**Comment by martynasma** [comment]
The first code is good.

The second is bad.

Bullets can only be of type `Bullet` or some type that extend `Bullet`, like `CircleBullet`, `LabelBullet`, etc.

`Rectangle` does not extend `Bullet` and therefore cannot be directly showed into series' `bullets`.

The solution is to add a `Rectangle` as a child of a `Bullet`. (if no type is specified for a bullet the chart just assumes `Bullet`), hence the first snipped being correct.

Does that make sense?

**Comment by ptorrent** [comment]
Yes totaly ! Thanks
