### ISSUE TITLE
Dynamic filter saturation does not work

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2780]
Hi.
I am creating a simple `Image` element inside a `Container` and I apply to the Image a filter like this: 
```
const filter = new DesaturateFilter();
filter.saturation = 0.005;
image.filters.push(filter);
```

At some point I change the saturation back to `1` but there is no visual effect, the image is still gray (saturation = `0.005`)

The weird part is that if I resize the window, the new saturation is applied. I don't know how to demo this cuz the app is pretty big and other examples I tried on simple demos are actually working fine.

**Comment by martynasma** [comment]
I'm afraid we'll need a repro case for this. Let us know if you can create some test case for us to use for testing.

**Comment by directcuteo** [comment]
apparently it was my fault. It's working fine now.
