### ISSUE TITLE
Can we do Generic coding using amcharts or not?

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#2782]
This means, that we write generic coding using amcharts because I reading most of the documentation of amcharts 4 but I, not get my answer related to this topic.

**Comment by martynasma** [comment]
Could you clarify: what is "generic coding"?

**Comment by Swaraj55** [comment]
The example:: I have used 5 stacked & column charts and it takes more number of lines can we do it small for creating a single function where all properties are written related to stacked & column chart and call that in this five charts because the repetition of code occurring so we can do with amcharts or not?

**Comment by martynasma** [comment]
Yes, you can wrap your amCharts code into a function :)

Not that this requires any specific support from amCharts, or any other JS library for that matter.

Just to be perfectly clear, this is a repository for amCharts-related bugs/issues/questions and might not be the best place to ask generic programming questions you're asking.

**Comment by Swaraj55** [comment]
Thanks, @martynasma  for helping me
