### ISSUE TITLE
How to create a common tooltip in stacked and Column chart?

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#2783]
I have a question How we create common tooltip in the stacked and Column chart?
This means no individual tooltip shows. For one Column it shows common tooltip. I share a link here you see the tooltip for Europe and North America are separately show but I need that both of them come in the single tooltip and when I hover a single column of the chart single tooltip comes not two. Can we do this chart?

https://codepen.io/swarajv5/pen/xxVwXpq?editors=0010

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/tutorials/multi-series-shared-tooltip-with-colored-bullets/

**Comment by Swaraj55** [comment]
These docs help me little bit but I need a single tooltip but I get two. I share my file here you see 
https://codepen.io/swarajv5/pen/xxVwXpq?editors=0010

**Comment by Swaraj55** [comment]
Okay, Thanks @martynasma

**Comment by robjean9** [comment]
Hello @Swaraj55 , I imagine that you've already solved your problem to leave only a tooltip showing.

I followed the tutoria and ran into the same scenario, but realized it was just an attribute I forgot to set in the end. (which is mentioned in the documentation).

`chart.cursor.maxTooltipDistance = 0;`

**Comment by robjean9** [comment]
Hello @Swaraj55, I found another solution on  AmCharts4 documentation https://www.amcharts.com/docs/v4/concepts/chart-cursor/#Series_tooltips

Use: `chart.cursor.maxTooltipDistance = -1;`

<img width="804" alt="image" src="https://github.com/user-attachments/assets/5b39abab-09b6-44d8-8302-b71093c4b720">
