### ISSUE TITLE
How to disable mouse hover  if country don't have value ?

### ISSUE THREAD

**Issue by sureshhallyali** [amcharts/amcharts4#2784]
In Map Chart, By default for all country mouse hover work whether don't have value or have value it will mouse hove so what needed is "if country don't  have value should not mouse hover  on country" ?

example:
India and united state have value other don't have value so mouse hove will  effect "Greey" colour  other country need to don't effect.

https://codepen.io/sutya/pen/zYqxOvz

**Comment by martynasma** [comment]
You can do so using `propertyFields` to connect to polygon's `interactionsEnabled` setting:

```
// Add some data
polygonSeries.data = [{
  "id": "US",
  "name": "United States",
  "value": 100,
  "fill": am4core.color("blue"),
  "cursor": am4core.MouseCursorStyle.pointer,
  "hoverable": true
}, {
  "id": "IN",
  "name": "India",
  "value": 50,
  "fill": am4core.color("blue"),
   "cursor": am4core.MouseCursorStyle.notAllowed ,
  "hoverable": true
}];

// Bind "fill" property to "fill" key in data
polygonTemplate.propertyFields.fill = "fill";
polygonTemplate.propertyFields.cursorOverStyle = "cursor";

polygonTemplate.interactionsEnabled = false;
polygonTemplate.propertyFields.interactionsEnabled = "hoverable";
```

I suppose this is related to your other ticket as well: #2785

Enabling the above will solve that ticket as well, without adding the adapter.
