### ISSUE TITLE
In map tooltipText  showing common  for all need different if they don't have value??

### ISSUE THREAD

**Issue by sureshhallyali** [amcharts/amcharts4#2785]
In map tooltipText  showing common  for all  but some country don't have value so there label showing country name and colon ":"
so its problem?

Based on value exist or not tooltipText has to show 

example:
on mouse hover tooltipText:

Unites sate:200        Right  showing`
India :100:                Right  showing
China:                    Wrong showing

Colon symbol " : " should not display if don't have value 

Codepen:

https://codepen.io/sutya/pen/zYqxOvz?editors=0010

**Comment by martynasma** [comment]
I suppose you can use an adapter to dynamically determine what is displayed in tooltip, based on target dataItem:

```
polygonTemplate.tooltipText = "{name}:{value}";
polygonTemplate.adapter.add("tooltipText", function(text, target) {
  return target.dataItem.value !== undefined ? text : "";
});
```

Empty text means no tooltip is shown.
