### ISSUE TITLE
showTooltip() is not working

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2786]
Hi. I am having a tooltip on a Container and I would like to show the tooltip on some event.

I am facing some trouble with the `showTooltip()` function. It seems to be broken. The tooltip has text but the `showTooltip()` is still returning false and the tooltip is not visible. Hovering works fine.

CodePen example: https://codepen.io/directcuteo/pen/gOraJYX (hover a city - see line 45)

Thank you!

**Comment by martynasma** [comment]
You are calling `showTooltip()` on a MapImage template, which is used to create actual map markers but is not shown on a map itself.

You also set `tooltipText` on a circle - a child element of actual MapImage.

I would set it on a template, and also would call on actual marker you want tooltip shown for:

This will work:

```
cities.mapImages.template.tooltipText = 'Hello there';
...
cities.mapImages.getIndex(0).showTooltip();
```

**Comment by directcuteo** [comment]
Because my real example is a bit more complicated I would ask further for my specific case:

I have a series in which I create a container:
```
const series = this.map.series.push(new MapImageSeries());
const imageSeriesTemplate = series.mapImages.template;
const wrapper = imageSeriesTemplate.createChild(Container);
```

Further I create another container inside previous one
```
const cont = wrapper.createChild(Container);
```
Then, I create n containers inside this last container, each having attached an `Image` with a `Tooltip` :
```
someArray.forEach(segment => {
  const markerContainer = cont.createChild(Container);
  const marker = markerContainer.createChild(Image);
  marker.tooltipText = segment.title;
});
```
If I now run for example `cont.children.values[0].children.values[0].showTooltip()` it won't work.
Thank you

**Comment by martynasma** [comment]
Then you will need to call `showTooltip()` on whatever element/child `tooltipText` is set on, an actual MapImage object, not template.

**Comment by directcuteo** [comment]
I got it. I had to use the series itself as a beginning to select the corect child object.  
`series.mapImages.values[0].children. --blabla-- .showTooltip()`

Now it's working fine. Thank you!
