### ISSUE TITLE
updateFromConfig

### ISSUE THREAD

**Issue by SeregPie** [amcharts/amcharts4#2787]
Hi.
There is a possibility to create a chart from a JSON config. But I found no possibility to also update the chart from config. This would be a great feature. This would also make it possible, to create components for React, Vue, etc.

```js
let chart = am4core.createFromConfig(config, el, am4charts.PieChart);
onUpdate(config => {
  chart.updateFromConfig(config);
});
```

**Comment by martynasma** [comment]
Technically, it should be possible, depending on how complex your updates are:

```
let chart = am4core.createFromConfig(config, el, am4charts.PieChart);
onUpdate(config => {
  chart.config = config;
});
```

**Comment by SeregPie** [comment]
Ah. Ok. Thank you. I will try that out.

**Comment by SeregPie** [comment]
That works. But the data is not updated. It needs to be applied separately.

```js
let chart = am4core.createFromConfig(config, el, 'PieChart');
onUpdate(config => {
  chart.config = config;
  chart.data = config.data;
});
```

https://codepen.io/SeregPie/pen/zYqrXPM

**Comment by martynasma** [comment]
> That works. But the data is not updated. It needs to be applied separately.

Or you can invalidate data:

```
chart.invalidateData();
```

**Comment by SeregPie** [comment]
Hi again.
There is just the last issue, that prevents me from going on.
https://codepen.io/SeregPie/pen/WNwxQbP
Would be nice, if it could automatically update th children by comparing the ids from the new config.

**Comment by SeregPie** [comment]
Hmmm. I see. There are even more problems. Like updating data inside nested charts. So updating from config is not really an option for now. For a smooth data update from a JSON, there should be a support for an ID in a data item. So a long way to go.
