### ISSUE TITLE
Question: How to force value axis to display 0?

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2788]
I have a chart will sometimes display very large numbers (see below), I would like the axis to display 0, -20,000 +20,000 intervals. It is possible to force it to count from 0?

![image](https://user-images.githubusercontent.com/66729900/90134618-596f6a80-dd69-11ea-809e-59c068f872b2.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Josh10101010** [comment]
I've created a codepen here https://codepen.io/Josh519/pen/RwarzaB , thanks

**Comment by zeroin** [comment]
If I removed the text adapter from your code, the axis starts at 0 value. I am afraid we can not control the gaps in this case at all. You could try to adjust `axis.renderer.minGridDistance` or disable default labels at all and add axisRanges at some custom values.

**Comment by Josh10101010** [comment]
Would you recommend a different way to achieve the percentage returns on the axis? Instead of the adapter?

**Comment by zeroin** [comment]
Usually in stock charts it's done by providing real values of a stock and then telling series that it should use `changePercent` instead of value:

`series.dataFields.valueYShow = "changePercent";`

or, if you want the change not to be adjusted from the beginning of the selection but from the first data point:

`series2.dataFields.valueYShow = "startChangePercent";`

Like in this demo:

https://www.amcharts.com/demos/stock-chart-comparing-prices/

**Comment by Josh10101010** [comment]
Thanks, I've tried that and it's working as we wanted, however the animation is buggy when you toggle a series on the legend, any ideas why? I've updated the codepen

**Comment by zeroin** [comment]
To solve this problem you should set:

`valueAxis.maxZoomFactor = Infinity`

The series will display fine then, although the animation will still be strange, but there is nothing we can do here, as when animating values, percent's get really big and the series fly out of the visible range. So you should either live with it or do not use animation at all. 

By the way, I think your values in data are still not real prices but changes, most likely you were just testing the feature, but I thought I will tell.
