### ISSUE TITLE
How to define global properties of particular amchart?

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#2789]
There is any way where we define all the global properties of a Simple bar chart in function and we access those properties where we need. The reason is that they have lots of properties which I need to call in my four charts so my code is going long. If some properties I defined in that function and call in those four charts. There is any way how we define global properties?

**Comment by martynasma** [comment]
You could create a custom theme:

https://www.amcharts.com/docs/v4/tutorials/creating-themes/
