### ISSUE TITLE
Animation overshoots on load

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#2790]
I'm seeing odd animation on some charts when they load. The animation/scale overshoots and then comes back down. Sometimes, it doesn't come back down at all and I have to zoom out for it to get to display normally. It seems like the chart doesn't know its max value on the valueAxis.

I currently have this running in:
- Storybook 5.3.18
- React 16.13.1
- AmCharts 4.9.33
- happens in all major browsers

I could set this up in a Codepen if needed although maybe someone has already seen this before and has any advice. Following screen recordings show the behavior. While this shows especially stacked charts, I've also observed this on some regular line charts where this would occasionally happen.

![StackedArea](https://user-images.githubusercontent.com/5614099/90144680-15f11c80-ddba-11ea-99dd-252c34120ca1.gif)

![StackedColumn](https://user-images.githubusercontent.com/5614099/90143844-0d4c1680-ddb9-11ea-819a-3f4992cf307f.gif)

**Comment by zeroin** [comment]
A codepen would help a lot - thanks!

**Comment by sassomedia** [comment]
@zeroin Codepen unfortunately wasn't much help, it's working fine on it's own [there](https://codepen.io/sassomedia/pen/zYqrygV?editors=1000). Troubleshooting Storybook could be more difficult. Any suggestions on what could cause such a high-ranging animation? Like any heights to be set or max limits that could potentially help?

**Comment by zeroin** [comment]
Are the charts in the pen exactly the same (data count, values etc)? And when you change the type, is is exactly the same thing you do on your setup?

**Comment by sassomedia** [comment]
I initially had a simplified version with both using CategoryAxis but I updated it now to closer match my setup. One is using CategoryAxis, the other DateAxis. Also updated the number of data points that now match exactly what I have but it does not seem to make a difference. Standalone, it works but I have a feeling this could be Storybook related. Not sure though how it could cause such a spike, it's getting almost the same setup information as in the pen.

**Comment by zeroin** [comment]
Did you consider instead of disposing whole chart changing series settings to get the same result?
Also, could you try to store previous chart in some variable and dispose it only after the new one is inited?

**Comment by sassomedia** [comment]
Unfortunately, with Storybook, that's out of my control. Not sure if you're familiar with [Storybook](https://storybook.js.org) but what it mainly does is load and unload components when you switch between different stories/pages. The charts are basically abstracted inside a React component, so I can't keep the chart around. Once the component unloads, so does the chart. 

I'm still suspecting this is somehow Storybook related, I just can't imagine how it could affect the chart animation. And it works fine for most charts but I've seen issues really only with Line and Bar charts so far. I'll have to dig some more...

There's also a new major version of Storybook that has just been released, which might alleviate the issue. Although, because of breaking changes in the new version, it may take a while for us to upgrade.

**Comment by zeroin** [comment]
Well, at least you could try to dispose the old chart with some timeout.

**Comment by sassomedia** [comment]
Ah, that wouldn't make a difference. The issue already happens the first time I load the chart when none other existed before.

**Comment by sassomedia** [comment]
Closing this issue for now, doesn't look like we have bandwidth for upgrading Storybook anytime soon. Will open again once I have more info on that.
