### ISSUE TITLE
Align bullet and CategoryAxis in a LineSeries

### ISSUE THREAD

**Issue by magijoylarin** [amcharts/amcharts4#2793]
**Question**

Hi, how can I align the bullet and CategoryAxis in a LineSeries? I have 2 x-axis in my chart. (DateAxis and CategoryAxis)

I'm trying to align the category labels to the bullet in the graph. Can you help me on how I can do that?

Here's what I got so far.
https://codepen.io/magijoylarin/pen/mdPPdwQ

**Comment by martynasma** [comment]
Read this solution: https://github.com/amcharts/amcharts4/issues/2544#issuecomment-638871202

**Comment by magijoylarin** [comment]
@martynasma 

The solution works on consistent data but with inconsistent dates it still doesn't align. 
I've updated the codepen.

**Comment by martynasma** [comment]
If you need grid/labels on axis placed at arbitrary intervals, you will need to use axis ranges.

More info:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/
https://www.amcharts.com/docs/v4/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/

**Comment by magijoylarin** [comment]
> If you need grid/labels on axis placed at arbitrary intervals, you will need to use axis ranges.
> 
> More info:
> https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/
> https://www.amcharts.com/docs/v4/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/

Thank you! The axis ranges works for me.

**Comment by fu1996** [comment]
Hello, can you put the solved code in codepen? I also encountered the same problem. After reading the tutorial, I still can't think of how to solve it. Thank you
