### ISSUE TITLE
Error: EventDispatcher is disposed

### ISSUE THREAD

**Issue by crossx4real** [amcharts/amcharts4#2794]
**Bug description**

am4Charts is crapping-out approximately every hour when i try to print the next candle  on a 1hr timeframe.

the application has been working flawlessly until recently, not sure what happened but something changed

Browser: brave browser

Error: EventDispatcher is disposed
    at e.t.isEnabled (core.js:1)
    at t.e.dispatchImmediately (core.js:1)
    at t.set [as parent] (core.js:1)
    at core.js:1
    at Object.e.each (core.js:1)
    at e.t.each (core.js:1)
    at e.validateDataElement (core.js:1)
    at e.validateDataElements (core.js:1)
    at e.validate (core.js:1)
    at e.validate (core.js:1)

**Comment by martynasma** [comment]
We'll need a repro case which we can test. Do you think you can whip one up?

**Comment by crossx4real** [comment]
martynasma - i have two charts that i am feeding the same data, not sure if this is a browser issue, haven't test on chrome yet but i know this just started happening out of the blue and i haven't updated my code.

![image](https://user-images.githubusercontent.com/1406703/90397203-7fe11e80-e065-11ea-8096-267e5618e748.png)


`<html>
<body>
<div id="chartDiv_1"></div>
<div id="chartDiv_2"></div>

<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>

<script>

var candleARR = [];
var chart_1 = drawChart("chartDiv_1");
var chart_2 = drawChart("chartDiv_2");

setInterval(function() {
	var ts = new Date().getTime();
	var candleOBJ = { timestamp: ts, open: 20, close: 80, high: 100, low: 10 };
	candleARR.push(candleOBJ );
	plotChartData(candleARR);
}, 3600000) ;   //using 1hr timeframe

function drawChart(chartID) {
	var tempOBJ = {};
	am4core.useTheme(am4themes_animated);
	tempOBJ = am4core.create(chartID, am4charts.XYChart);
	tempOBJ.dateFormatter.inputDateFormat = 'd-H:m:ss';
	tempOBJ.leftAxesContainer.layout = "vertical";

	var dateAxis = tempOBJ.xAxes.push(new am4charts.DateAxis());
	dateAxis.groupData = true;
	dateAxis.renderer.fontSize = '0.75em';
	dateAxis.tooltip.fontSize = '0.75em';
	dateAxis.disable = true;

	var valueAxis = tempOBJ.yAxes.push(new am4charts.ValueAxis());
	valueAxis.renderer.fontSize = '0.75em';
	valueAxis.tooltip.fontSize = '0.75em';
	valueAxis.zIndex = 1;
	valueAxis.renderer.baseGrid.disabled = true;
	valueAxis.height = am4core.percent(100);

	var candleTip = 'Open: ${openValueY} \n Low: ${lowValueY} \n High: ${highValueY} \n Close: ${valueY}';
	var candleSeries = tempOBJ.series.push(new am4charts.CandlestickSeries());
	candleSeries.dataFields.dateX = 'timestamp';
	candleSeries.dataFields.valueY = 'close';
	candleSeries.dataFields.openValueY = 'open';
	candleSeries.dataFields.lowValueY = 'low';
	candleSeries.dataFields.highValueY = 'high';
	candleSeries.tooltipText = candleTip;
	candleSeries.tooltip.pointerOrientation = 'horizontal';
	candleSeries.propertyFields.alwaysShowTooltip = true;
	candleSeries.tooltip.fontSize = '10px';
	candleSeries.riseFromOpenState.properties.fill = am4core.color('#00ff00');
	candleSeries.dropFromOpenState.properties.fill = am4core.color('#FF0000');
	candleSeries.riseFromOpenState.properties.stroke = am4core.color('#00ff00');
	candleSeries.dropFromOpenState.properties.stroke = am4core.color('#FF0000');
	candleSeries.riseFromPreviousState.properties.fillOpacity = 1;
	candleSeries.dropFromPreviousState.properties.fillOpacity = 0;

	var scrollSeries = tempOBJ.series.push(new am4charts.LineSeries());
	scrollSeries.dataFields.dateX = 'timestamp';
	scrollSeries.dataFields.valueY = 'close';
	scrollSeries.defaultState.properties.visible = false;
	scrollSeries.hiddenInLegend = true;
	scrollSeries.fillOpacity = 0.5;
	scrollSeries.strokeOpacity = 0.5;

	var scrollbarX = new am4charts.XYChartScrollbar();
	scrollbarX.series.push(scrollSeries);
	tempOBJ.scrollbarX = scrollbarX;
	tempOBJ.scrollbarX.minHeight = 30;

	return tempOBJ
}

function plotChartData(newCandle) {
		chart_1.addData(newCandle, 0);
		chart_2.addData(newCandle, 0);
		chart_1.validateData();
		chart_2.validateData();
}

</script>
</body>
</html>`

**Comment by crossx4real** [comment]
Ditching this am4Chart.
