### ISSUE TITLE
Scroll in plotContainer

### ISSUE THREAD

**Issue by DmitryTevtonsky** [amcharts/amcharts4#2795]
**Question**

Is there any way to add scroll to plotContainer (with vertical layout of leftAxisContainer) like a legendContainer?
This may allow virtualization and dynamic loading for series.
Idk, but maybe it can work with adapters or something else?

amcharts 4 with React.

Thank you very much.

**Comment by zeroin** [comment]
Do you mean it like in this demo: https://www.amcharts.com/demos/zoomable-value-axis/ ?

**Comment by DmitryTevtonsky** [comment]
> Do you mean it like in this demo: https://www.amcharts.com/demos/zoomable-value-axis/ ?
Sorry, i disappeared for a while.

No, i mean scrolling in plotContainer not single series (like zooming).
I mean scrolling when the following conditions are met together:
1) axes stacked vertically;
2) axes have a fixed height;
2) they don't fit in the viewport (viewport with fixed height);

Situation 1 (It's Ok)
![5 axes fit in viewport](https://user-images.githubusercontent.com/46815138/93187182-30673e80-f748-11ea-903e-62e699ffcb56.png)

Situation 2 (Not good for me, with hacks)
![6 axes don't fit in viewport, but I enlarged the chartContainer and added a outer scroll](https://user-images.githubusercontent.com/46815138/93187305-58ef3880-f748-11ea-8bac-f7512d93946b.png)
In this case i have 6 or more axis, enlarged chartContainer, but outer(not amcharts) scroll.
Its bad for me, because when i scroll down, its scrolled the chart container and Amcharts.Scrollbar goes out of viewport.
When I'm at the top of the scroll date axis out of viewport (look at images).

Last word: i need to scroll not a chartContainer, but the container which contains the axis and series (
![orange area](https://user-images.githubusercontent.com/46815138/93189118-76250680-f74a-11ea-858b-81407b5df346.png)
)

**Comment by martynasma** [comment]
Maybe something like this:
https://www.amcharts.com/docs/v4/tutorials/freeze-horizontal-axis/

**Comment by DmitryTevtonsky** [comment]
Thank you very much guys!
