### ISSUE TITLE
Wrong text positions on the card system of Bootstrap

### ISSUE THREAD

**Issue by Cuperido** [amcharts/amcharts4#2796]
Hello,
First, thank you for making a great library.

It's a topic similar to "https://github.com/amcharts/amcharts4/issues/1209"
The chart does not display properly when moving tabs on the card system of Bootstrap.

When I draw a chart on an active tab, the chart appears correctly, but when drawing on a disabled tab and then clicks the tab, the position of texts appears incorrectly.

By the way, I tried to make a sample code on JsFiddle, but it doesn't even load the chart properly on each card page on JsFiddle, and it seems that only the first chart was loaded on each card system
I am not sure it is also a bug or just a JsFiddle problem.

For your information, I attached a recorded video and code snippets.

Could you please give me some advice?
Although I couldn't find it in the document. is there a way to refresh the text position?

Thank you in advance.

**JsFiddle:** 
https://jsfiddle.net/cuperido/93zwvhm8/75/

**Video:**
https://www.youtube.com/watch?v=cEQ4TlPxU7Q

**Original code snippets:** 
https://codecollab.io/@cuperido/AmChart

**Environment:**
Version: AmChart 4
Browser: Chrome latest version
Framework: Vanilla

**Comment by zeroin** [comment]
Try calling `chart.invalidateLabels()` after the card with a chart rendered in a hidden tab was shown.

**Comment by Cuperido** [comment]
It works! Thank you so much, Zeroin!
