### ISSUE TITLE
zoomToDates not working with datasource

### ISSUE THREAD

**Issue by gotzsys** [amcharts/amcharts4#2797]
Hello
I'm trying start my candlestick graphic with a pre zoom.
I followed this docs: https://www.amcharts.com/docs/v4/tutorials/pre-zooming-an-axis/
But not working.

`// Themes begin
        am4core.useTheme(am4themes_animated);
        // Themes end

        var chart = am4core.create("chartdiv", am4charts.XYChart);
        chart.language.locale = am4lang_pt_BR;
        chart.paddingRight = 20;

        chart.dateFormatter.inputDateFormat = "yyyy-MM-dd";

        var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
        dateAxis.renderer.grid.template.location = 0;
        dateAxis.skipEmptyPeriods = true;
        dateAxis.showOnInit = false;

        var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
        valueAxis.tooltip.disabled = true;

        var series = chart.series.push(new am4charts.CandlestickSeries());
        series.dataFields.dateX = "date";
        series.dataFields.valueY = "close";
        series.dataFields.openValueY = "open";
        series.dataFields.lowValueY = "low";
        series.dataFields.highValueY = "high";
        series.simplifiedProcessing = true;
        series.tooltipText = "Open:R${openValueY.value}\nLow:R${lowValueY.value}\nHigh:R${highValueY.value}\nClose:R${valueY.value}";
        series.showOnInit = false;

        chart.cursor = new am4charts.XYCursor();

        // a separate series for scrollbar
        var lineSeries = chart.series.push(new am4charts.LineSeries());
        lineSeries.dataFields.dateX = "date";
        lineSeries.dataFields.valueY = "close";
        // need to set on default state, as initially series is "show"
        lineSeries.defaultState.properties.visible = false;

        // hide from legend too (in case there is one)
        lineSeries.hiddenInLegend = true;
        lineSeries.fillOpacity = 0.5;
        lineSeries.strokeOpacity = 0.5;

        var scrollbarX = new am4charts.XYChartScrollbar();
        scrollbarX.series.push(lineSeries);
        chart.scrollbarX = scrollbarX;

        chart.dataSource.url = HOST_URL + '/tickers/' + $('#tickers-show').data('ticker') + '/getJsonData';

        chart.events.on("ready", function () {
            dateAxis.zoomToDates(
                new Date(2019, 1),
                new Date(2020, 1)
            );
        });`

**Comment by zeroin** [comment]
A pen with data would help a lot. 
Try to use "datavalidated" event instead. 

And even better solution would be to calculate relative start/end of the axis and set dateAxis.start / dateAxis.end  + dateAxis.keepSelection = true: https://www.amcharts.com/docs/v4/tutorials/pre-zooming-an-axis/#Relative_pre_zooming

This is much better for performance.
