### ISSUE TITLE
property for rounded corner in gaugeChart's valueAxis

### ISSUE THREAD

**Issue by devendrabohre83incs** [amcharts/amcharts4#2798]
Hello Amchart, I am not able to find something to do rounded corner property in gauge chart valueaxis. if we have some property to do this, then help me.

**Comment by martynasma** [comment]
I'm afraid there's no way to enable corner rounding for axis line or its bands. Sorry.

**Comment by devendrabohre83incs** [comment]
thanks Martynas
________________________________
