### ISSUE TITLE
Is there any way to disable or stop the minimizaton after clicking the slice in chord chart?

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#2799]
Whenever I clicked on slice they minimize is there any way we disabled for minimization because I don't need.
I also use this property they do not help me according to my needs
1. chart.nodes.template.slice.disabled = true;
2. chart.nodes.template.label.disabled = true;

Take the example of PieChart when we clicked on its slice it not minimize there is a way for ChordChart?

I share my code:
https://codepen.io/swarajv5/pen/ZEWOVbL?editors=0010

**Comment by martynasma** [comment]
Check this out:
https://www.amcharts.com/docs/v4/chart-types/chord-diagram/#Disabling_toggling_or_dragging_of_Nodes

**Comment by Swaraj55** [comment]
I share my code you can see whenever I am clicking on different slices they always give me "uncategorized"?

there is problem with my data or something else? 
check-in console
https://codepen.io/swarajv5/pen/ZEWOVbL?editors=0011

**Comment by martynasma** [comment]
I'm sorry but we don't have the capacity to debug your code.

**Comment by Swaraj55** [comment]
okay thanks
