### ISSUE TITLE
Tooltip positionning

### ISSUE THREAD

**Issue by kothve** [amcharts/amcharts4#2800]
**Question**

Hi,

Instead of having the tooltip near the ValueAxis of the GaugeChart, I am trying to make the tooltip float at the top of the chart. ( Only move horizontally)

I have the following properties:
chart.cursor = new RadarCursor();
  chart.cursor.lineY.disabled = true;
  chart.cursor.lineX.disabled = true;
  axis.cursorTooltipEnabled = properties.cursorTooltipEnabled;
  axis.renderer.labels.template.disabled = !properties.showLabels;
  axis.adapter.add(ChartAdapters.TOOLTIP_TEXT, () => {
        return ${properties.tooltipText};
      });

I have tried to change the positioning using axis.tooltip.dy or axis.tooltipY without success, the tooltip always floats near the axis.

![Screen Shot 2020-08-18 at 10 56 17 AM](https://user-images.githubusercontent.com/7607272/90529229-7c22ca00-e141-11ea-85f6-dfbb4fd7504c.png)

**Comment by martynasma** [comment]
I would use an adapter on `pixelY` on the tooltip. Something like this:

```
chart.tooltip.adpater.add("pixelY", function(y, target) {
  return 0;
});
```
