### ISSUE TITLE
Category Axis with Fixed Items

### ISSUE THREAD

**Issue by mcgodan** [amcharts/amcharts4#2803]
Is it possible to use a category axis with a fixed list of data points/labels so that they are present when there is no data in the series?

Apologies if this is obvious, i could not find any reference or example.

**Comment by xorspark** [comment]
Yes, it's possible. All you need to do is set the category axis' data array with the list of categories you want visible. 

```
categoryAxis.dataFields.category = "category";
categoryAxis.data = [{ "category": "Research" }, { "category": "Marketing" }, { "category": "Distribution" }];
```

[Demo](https://codepen.io/team/amcharts/pen/0e4b329694576be4aa2712ff2653e7cf?editors=0010)
