### ISSUE TITLE
Force Directed Tree node size question

### ISSUE THREAD

**Issue by wkdaudwn11** [amcharts/amcharts4#2804]
The options to adjust the size of the node in the Force Directed Tree seem to be 'networkSeries.minRadius' and 'networkSeries.maxRadius'.

But can't you control it separately in a function other than this?

For example, like this.
```
networkSeries.nodes.template.events.on('ready', function (event) {
    let fontColor = '#0067b9', // 뎁스2 노드의 폰트색상
        strokeColor = '#cee0f5'; // 보더 색상
    const { level } = event.target.dataItem;

    if(level === 0){
        fontColor = '#ffffff';
        strokeColor = '#0067b9'; // 뎁스0 기준 (자사 브랜드)
    }else if(level === 1){
        fontColor = '#ffffff';
        strokeColor = blue_2; // 뎁스1 기준 (카테고리)
    }
					
    event.target.label.fill = am4core.color(fontColor); // 텍스트 색상
    event.target.stroke = am4core.color(strokeColor); // 노드의 보더 색상
    event.target.outerCircle.fill = am4core.color(strokeColor); // 0,1뎁스의 흰색?으로 감싸져있는 거 색상
});
```

The above code is a function that designates the text color, border color, and outerCircle color by node level.

I want to adjust the size(radius) for each node level in this way, but it doesn't work. It seems that the size is continuously adjusted by the value of the node. I want to adjust the size according to the level regardless of the value. How do I do it?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
