### ISSUE TITLE
getImage with and without a parent DOM element

### ISSUE THREAD

**Issue by SeregPie** [amcharts/amcharts4#2807]
Hi.
What is the proper way to get an image from a chart?
`exporting.getImage()` is not waiting until all animations are finished.
If I create a chart without a parent, how do I set its size?
https://codepen.io/SeregPie/pen/wvGzZvO

**Comment by martynasma** [comment]
Please read all of this:
https://www.amcharts.com/docs/v4/concepts/exporting/#Getting_raw_data

**Comment by SeregPie** [comment]
I have already read all the docs. Still could not figure that out. =(

**Comment by martynasma** [comment]
Are you sure you read it all? ;)

![image](https://user-images.githubusercontent.com/1458520/90760372-71576900-e2ea-11ea-9875-cfbf00c37269.png)

**Comment by SeregPie** [comment]
Yes.
:P
Look in the code pen I linked in the first post.

**Comment by martynasma** [comment]
OK, so you should probably set up your export to delay by number of milliseconds it takes animations to finish. Export can't check if some animations are still playing, I'm afraid.

**Comment by SeregPie** [comment]
And what about the second image in the example? How do I set width and height, when the parent DOM element is missing?

**Comment by martynasma** [comment]
I don't think you can export chart that was initialized outside of DOM. Maybe try Shadow DOM, if you don't want the chart to appear on screen?

**Comment by SeregPie** [comment]
It looks like it is already working outside the DOM. Only the size is messed up.

See code pen.

![](https://puu.sh/GkcBU/0947e59bd5.png)

**Comment by martynasma** [comment]
Not sure what else to suggest. Sorry.
