### ISSUE TITLE
osm tiles in background

### ISSUE THREAD

**Issue by rahimramezanian** [amcharts/amcharts4#2808]
There is an example here,

https://www.amcharts.com/docs/v4/tutorials/using-mapchart-with-google-maps-api/

which the background tiles come from google map, 
could you please have an example with open street map tiles?
Thanks.

**Comment by martynasma** [comment]
I'm afraid we do not have plans to implement something like that. Especially that OSM does not seem to have official client-side JS API, like Google Maps. Sorry.
