### ISSUE TITLE
Different colors for negative values on the line chart

### ISSUE THREAD

**Issue by jaischeema** [amcharts/amcharts4#281]
Hi,

I am trying to replicate the functionality from this example chart from v3: https://www.amcharts.com/demos/smoothed-line-chart/. It has different colors for negative and positive values for the line chart but I was unable to find an option to do this in version 4. Is it possible and if yes, how would you go about doing that?

Cheers

**Comment by zeroin** [comment]
Hi, 

You can easily do this with axis ranges: https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/

**Comment by jaischeema** [comment]
Thank you @zeroin, that is 👌🏻, great work!
