### ISSUE TITLE
Map geoJson wrong render

### ISSUE THREAD

**Issue by Sam116** [amcharts/amcharts4#2810]
**Bug description**

If using custom geocoordinates on amcharts map, it renders inversed. 
Coordinates taking from http://geojson.io/
What must be:
![image](https://user-images.githubusercontent.com/5461966/90769927-b3d47200-e2f9-11ea-917c-b3291a8bdcb6.png)

What i have:
![image](https://user-images.githubusercontent.com/5461966/90770003-d1094080-e2f9-11ea-8b52-fa18ad0950f1.png)

I tryed to reverse coordinates, but it does no effect.
Codepen example:
https://codepen.io/Sam116/pen/abNmgEd

**Comment by martynasma** [comment]
Reversing the coordinates fixes the issue:

https://codepen.io/team/amcharts/pen/374b28fa0c114c073239fe24584c6547?editors=0010

**Comment by Sam116** [comment]
Thanks, for help!
