### ISSUE TITLE
TreeMap with custom Legend (sort order)

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#2811]
I can't seem to make a TreeMap with custom Legend work. The TreeMap sorts legend items based on the values of the map. Most of the time that's desired but in some cases it may not be. As an example [here](https://codepen.io/sassomedia/pen/NWNRZRz?editors=0010), I would like to keep the order of the items in the order that the data is structured so that it makes chronological sense when reading:
`•Morning •Mid-Morning •Afternoon •Early Evening •Evening`

I've first tried to add custom items into `chart.legend.data = []` but that does not seem to work. I then tried to sort the markers and itemContainers but that doesn't seem to have any effect either. I tried with a number of events to make that happen but nothing worked. Is there anything I'm missing?

**Comment by zeroin** [comment]
Hi,

I used `beforedatavalidated` event and sort data:

https://codepen.io/team/amcharts/pen/Rwaprwg?editors=0010

**Comment by sassomedia** [comment]
@zeroin Thanks for looking into this! Right, it seems like using `chart.legend.data` vs `chart.legend.markers` and the `beforedatavalidated` event does the trick. That does make sense. 👍
