### ISSUE TITLE
Links become invisible when values have a too hight difference

### ISSUE THREAD

**Issue by julie-bernal-cko** [amcharts/amcharts4#2812]
Hi,

I noticed that links become invisible when there is too high of a difference between values from the dataset. I re-produced the issue I was having on the Codepen below.

https://codepen.io/julie-bernal-cko/pen/JjXbPBQ

<img width="1270" alt="Screenshot 2020-08-20 at 16 51 05" src="https://user-images.githubusercontent.com/61151627/90788079-b210ab80-e305-11ea-9d6f-5a812c0b6b64.png">

I tried changing the size of the nodes as recommended in the documentation but with no success. I did not find a way to set a min-height for the link that would not break the chart. 

Is there a way to target the graph scaling and set a min-height for links to avoid them to disappear?

**Comment by martynasma** [comment]
This can be resolved by enabling link stroke:

```
chart.links.template.strokeOpacity = 0.1;
```

![image](https://user-images.githubusercontent.com/1458520/90855482-66531600-e388-11ea-9d1a-2ac85812d859.png)
