### ISSUE TITLE
XYchart scrollbarY wheel sensitivity modification does not change any thing.

### ISSUE THREAD

**Issue by AMINEAALI** [amcharts/amcharts4#2813]
**Bug description**

Hi, I have a `XYChart` and I made a horizontal scrollbar (Y axis) for it like this : 

```TYPESCRIPT
this.chart.scrollbarY = new am4core.Scrollbar();
this.chart.scrollbarY.startGrip.disabled = true;
this.chart.scrollbarY.endGrip.disabled = true;
this.chart.scrollbarY.parent = this.chart.leftAxesContainer;
this.chart.scrollbarY.mouseOptions.sensitivity = 50; // <---------- this does not work at all
this.chart.scrollbarY.wheelable = true;
this.chart.mouseWheelBehavior = "panY";
```

Changing the sensitivity in `mouseOptions` does not change anything.

**Environment (if applicable)**

Here's the github : https://github.com/AMINEAALI/amcharts

 - I am using amcharts 4.9.35
 - Latest version of Firefox
 - Using Angular 10 framework

Thank you for your help.

**Comment by martynasma** [comment]
I know it's not super intuitive, but it's [mentioned](https://www.amcharts.com/docs/v4/reference/sprite/#mouseOptions_property) in the class ref: you have to set sensitivity on the `chart.plotContainer`:

```
chart.plotContainer.mouseOptions.sensitivity = 50;
```

**Comment by AMINEAALI** [comment]
> 
> 
> I know it's not super intuitive, but it's [mentioned](https://www.amcharts.com/docs/v4/reference/sprite/#mouseOptions_property) in the class ref: you have to set sensitivity on the `chart.plotContainer`:
> 
> ```
> chart.plotContainer.mouseOptions.sensitivity = 50;
> ```

Thanj you very much
