### ISSUE TITLE
TreeMap - Display bullets for level 1 and 2

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2814]
I have a TreeMap with 3 levels and I've defined a bullet for each level. If I initially set maxLevels=1, then I can see the first bullet. But if I set maxLevels=2 I can see the bullet for the second level but not for the first one. Is there any way to display the bullet for the first level along with the bullet for the second level when I initially set maxLevels=2?

Thank you.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by martynasma** [comment]
You might want to modify top-level bullet's hidden state:

```
bullet0.hiddenState.properties.visible = true;
bullet0.hiddenState.properties.opacity = 1;
```

**Comment by javier-fjfs** [comment]
This works perfect.

Thank you!!
