### ISSUE TITLE
Force directed series value size calculation method

### ISSUE THREAD

**Issue by lancegliser** [amcharts/amcharts4#2819]
**Question**

In reviewing the documentation for [force directed series node sizing](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Sizing), it uses this language:

> "If node has any children, its value is a sum of values of its children."

I expected then that if all nodes are assigned a value of 1, the tree would calculate and grow parent nodes based on the total number of children.
A > B > C, D ~ 3
R > S > T, U, V > W ~ 5

However, the actual code for calculated size at: src/.internal/plugins/forceDirected/ForceDirectedSeries.ts:172 uses this logic:

```typescript
/**
 * @return Value
 */
public get value(): number {

	let value = this.values.value.value;

	if (!$type.isNumber(value)) { // Line 176
		if (this.children) {
			value = 0;
			this.children.each((child) => {
				value += child.value;
			})
		}
	}

	return value;
}
```

That logic is at odds with the quoted document. It would only calculate from children if no value was already present.

Does the documentation need to be updated or the code change?

**Comment by zeroin** [comment]
Yes, indeed, it's our mistake in the docs. We will update the documentation, thanks a lot for the heads up.

**Comment by martynasma** [comment]
The docs have been updated:

Node's own value is determined this way:

1. If data for the node contains numeric value (as determined via `dataFields`, that value is used for the node. It is not affected by any other values in the hierarchy.
2. If there's no value set specifically for the node, the value is calculated by summing up values of all its child nodes. It works like that all the way through hierarchy: second level node's value is a sum of its children that reside in third level, and so on.
