### ISSUE TITLE
Different labels for negative and positive portions of the axis

### ISSUE THREAD

**Issue by jaischeema** [amcharts/amcharts4#282]
Hi,

I am trying to add two labels to the value axis, one for `> 0` portion and the other for `< 0` portion.

![chart](https://user-images.githubusercontent.com/306437/44633962-02cec180-a9d6-11e8-86da-576bea87f1d4.jpg)

I know this might not be possible without some custom code, just wanted some direction on where would I start implementing something like this? I was ready to do this outside the chart but zero axis is not consistent because the values vary over different time periods.

Any help in this is much appreciated.

**Comment by zeroin** [comment]
Hi, 

You can easily achieve this using axisRanges: https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/

**Comment by martynasma** [comment]
Just to add, specifically, you're looking to add an axis range with a label:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Adding_guide_labels

I put together an example for you:
https://codepen.io/team/amcharts/pen/NLNpRp

**Comment by jaischeema** [comment]
Thank you @zeroin and @martynasma, that worked perfectly and thanks heaps for providing examples along with the documentation!
