### ISSUE TITLE
amcharts map: activated/deactivate a country dinamically

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2821]
I have a map (worldlow) where I'm loading new data each time a users selects a country on a combo box. That's working fine. In addition what I want is to select that country on the map, so each country selection will select that country on the map. Only one county can be selected at a time.

I'm using this code with the event 'datavalidated' but I guess that's not the correct event because each time the code deactivates a country (isActive=false), this event is triggered again and the code fails.
```
var activeState = this.polygonTemplate.states.create("active");
activeState.properties.fill = this.chart.colors.getIndex(4);
var activeCountry;

    this.polygonSeries.events.on("datavalidated", (ev) => {
        if (activeCountry){
          activeCountry.isActive = false;
        }
        activeCountry = this.polygonSeries.getPolygonById(isoReporter);
        activeCountry.isActive = true;
    }, this);
```
What I need is to select one country each time new data is loaded and deselect the previous one. Is there any event that I can use to do that once the data is loaded on the map?

Thank you.

**Comment by zeroin** [comment]
You could try using "datavalidated" or "dataitemsvalidated" event of series.
