### ISSUE TITLE
How to add horizontal line at front of the bullet in live data amcharts

### ISSUE THREAD

**Issue by mianSaif** [amcharts/amcharts4#2822]
i'm working on amchart live data you can check here https://www.amcharts.com/demos/live-data/. So I want to add a horizontal line at front of the line bullet like you can check here https://iqoption.com/en/ in this site when you signup and click on trade there will be a chart show. at front of the line bullet, there is a horizontal line I want to like this. So let me know is it possible ??

**Comment by zeroin** [comment]
Sure, you can add axisRange to the Date axis:  https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/
