### ISSUE TITLE
How we display both date and time at same time in dateAxis?

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#2823]
Is there any way to display both Date and Time in dateAxis?
I am using ISO 8601 Date and Time and trying to show in dateAxis but I do not get any achievement. I always get Date but not time. So, how we get time also.

Here, is my code:
// Create chart instance
var chart = am4core.create("chartdiv", am4charts.XYChart);

// Add data
chart.data = [{
  "date": "2020-08-23T10:40:00.000Z",
  "value": 9000
}, {
  "date": "2020-08-23T10:45:00.000Z",
  "value": 1020
}, {
  "date": "2020-08-24T10:45:00.000Z",
  "value": 6500
}];

var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
// // Set date label formatting
dateAxis.dateFormats.setKey("day", "MM-dd");

// Create value axis
var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.numberFormatter.numberFormat = "#b";
valueAxis.numberFormatter.bytePrefixes = [
     {"number": 1e+3, "suffix": "K"},
     {"number": 1e+6, "suffix": "M"},
     {"number": 1e+9, "suffix": "G"},
     {"number": 1e+12, "suffix": "T"}
]

// Create series
var series = chart.series.push(new am4charts.ColumnSeries());
series.dataFields.valueY = "value";
series.dataFields.dateX = "date";
series.name = "Sales";

var title = chart.titles.create();
title.text = "Sent Traffic in MB";
title.fontSize = 25;
title.marginBottom = 30;

**Comment by zeroin** [comment]
You should set baseInterval for your date axis manually:

`dateAxis.baseInterval = {timeUnit:"minute", count:1}`

and specify date format format to show hours and minutes

`dateAxis.dateFormats.setKey("day", "MM-dd HH:mm");`

**Comment by Swaraj55** [comment]
I get the result a little bit closer but not get the full results.

**_My code:_**

var chart = am4core.create("chartdiv", am4charts.XYChart);


// Add data
chart.data = [{
  "date": "2020-08-22T10:40:00.000Z",
  "value": 900000
}, {
  "date": "2020-08-23T10:45:00.000Z",
  "value": 102000
}, {
  "date": "2020-08-24T10:50:00.000Z",
  "value": 650000
}];

// Create axes
var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
// Set date label formatting
dateAxis.dateFormats.setKey("day", "MM/dd HH:mm");
dateAxis.baseInterval = {timeUnit:"day", count:1};

// Create value axis
var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.numberFormatter.numberFormat = "#b";
valueAxis.numberFormatter.bytePrefixes = [
     {"number": 1e+3, "suffix": "K"},
     {"number": 1e+6, "suffix": "M"}
]

// Create series
var series = chart.series.push(new am4charts.ColumnSeries());
series.dataFields.valueY = "value";
series.dataFields.dateX = "date";
series.name = "Sales";

**Output**
![Capture](https://user-images.githubusercontent.com/48621208/90990576-38f0ad00-e5c0-11ea-82f0-0de658970fa7.PNG)

You see the dateAxis that type of dateAxis I need but time does not show correctly?

**Comment by zeroin** [comment]
When baseInterval is set to day, the axis rounds the dates to days. There is no way to overcome this, the only solution would be to use CategoryAxis instead of DateAxis and pass categories in a way you want them to be displayed.

**Comment by Swaraj55** [comment]
As the above example, I will take a different date but If data coming of a single date and but time is the difference so how we plot the chart. So, we take time for making the charts but time is not rendered properly always show 12:00 what its means.

chart.data = [{
  "date": "2020-08-22T**10:40:00**.000Z",
  "value": 900000
}, {
  "date": "2020-08-22T**10:45:00**.000Z",
  "value": 102000
}, {
  "date": "2020-08-22T**10:50:00**.000Z",
  "value": 650000
}]; 

![data](https://user-images.githubusercontent.com/48621208/91024317-69166b00-e615-11ea-83f9-2eedb5675dec.PNG)

**Comment by zeroin** [comment]
As I mentioned, when interval is day, the dates are rounded to 00:00. There is no way to solve this, except to use CategoryAxis.

**Comment by Swaraj55** [comment]
Ok thanks

**Comment by Swaraj55** [comment]
How we done with category axis if you give some demo?

**Comment by martynasma** [comment]
> How had we done with category axis if you give some demo or link where I see those things?

You just supply pre-formatted dates in your data as categories.

https://www.amcharts.com/docs/v4/concepts/axes/category-axis/

**Comment by Swaraj55** [comment]
I don't take more time of you guys last things I need to clear from you through this property we can set the tooltip as we want
**series.tooltipText = "{dateX.formatDate('MM/dd HH:mm')}";**
can any similar things for axis labels?

_**Code:::**_
// Create chart instance
var chart = am4core.create("chartdiv", am4charts.XYChart);
// Add data
chart.data = [{
  "date": "2018-07-14T12:10:00.000Z",
  "value": 450
}, {
  "date": "2018-07-15T13:10:00.000Z",
  "value": 320
}, {
  "date": "2018-07-16T13:10:00.000Z",
  "value": 411
}, {
  "date": "2018-07-17T14:30:00.000Z",
  "value": 451
}, {
  "date": "2018-07-18T22:00:00.000Z",
  "value": 390
}];


// Create axes
var categoryAxis = chart.xAxes.push(new am4charts.DateAxis);
categoryAxis.renderer.grid.template.location = 0;
**categoryAxis.dateFormatter.inputDateFormat="yyyy-MM-ddTHH:mm:ss";**
var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
// Create series
var series = chart.series.push(new am4charts.LineSeries());
series.dataFields.valueY = "value";
series.dataFields.dateX = "date";
**series.tooltipText = "{dateX.formatDate('MM/dd HH:mm')}";**
series.strokeWidth = 2;

var bullet = series.bullets.push(new am4charts.CircleBullet());
bullet.circle.stroke = am4core.color("#fff");
bullet.circle.strokeWidth = 2;

**Output**
![Screenshot (7)](https://user-images.githubusercontent.com/48621208/91142695-d63a0700-e6ce-11ea-91bc-b06ae1c0f488.png)

**Comment by martynasma** [comment]
Yes: https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/#Tooltip_value_format

**Comment by Swaraj55** [comment]
**I not talking about tooltip I take tooltip to show that can we do the same thing for the x-axis.** My question is that through formaDate() we format our date and time of tooltip as you see the above picture **can we do something for x-axis labels also?** **because that what I want to show in my x-axis label.**

**Comment by martynasma** [comment]
You can format axis labels via dateFormats:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Formatting_date_and_time

Or via adapters:
https://www.amcharts.com/docs/v4/concepts/adapters/

**Comment by Swaraj55** [comment]
please help me with more problems. why they not show 07/18 15:00 in x-axis?
![tiqme](https://user-images.githubusercontent.com/48621208/91155304-48671780-e6e0-11ea-8bf5-2ede1b425938.png)

chart.data = [{
  "date": '2018-07-18T10:00:00.000Z',
  "value": 450
}, {
  "date": "2018-07-18T11:00:00.000Z",
  "value": 320
}, {
  "date": "2018-07-18T12:00:00.000Z",
  "value": 411
}, {
  "date": "2018-07-18T13:00:00.000Z",
  "value": 451
}, {
  "date": "2018-07-18T14:00:00.000Z",
  "value": 390
},**{
  "date": "2018-07-18T15:00:00.000Z",
  "value": 390
}**];



// Create axes
var categoryAxis = chart.xAxes.push(new am4charts.DateAxis());
categoryAxis.renderer.grid.template.location = 0;
categoryAxis.dateFormats.setKey("hour", "MM/dd HH:mm");
categoryAxis.baseInterval = {
  "timeUnit": "minute",
  "count": 1
}
chart.dateFormatter.inputDateFormat = "yyyy-MM-ddTHH:mm:ss";

![tiqme](https://user-images.githubusercontent.com/48621208/91155331-5321ac80-e6e0-11ea-8fc1-6d8667580cee.png)

**Comment by Swaraj55** [comment]
How to create space here?

![Screenshot (10)](https://user-images.githubusercontent.com/48621208/91168371-27f48880-e6f3-11ea-9b57-724e3d4b9610.png)

**Comment by Swaraj55** [comment]
when we pointing on bullet tooltip show correct time but cursor tooltip show wrong time why is the difference in the value?

![Screenshot (11)](https://user-images.githubusercontent.com/48621208/91168557-74d85f00-e6f3-11ea-9613-8f673c377e1b.png)
