### ISSUE TITLE
Label is not shown for some strange reason

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#2824]
Hi, At some cases where there are not a lot of data for a month for example this happens: 

More data https://codepen.io/dimitrios-kanellopoulos/pen/yLOgLOq?editors=0011

<img width="352" alt="Screenshot 2020-08-22 at 19 44 11" src="https://user-images.githubusercontent.com/1268723/90962392-e1631c00-e4af-11ea-98ac-146962176557.png">

Less data https://codepen.io/dimitrios-kanellopoulos/pen/XWdpWMQ?editors=0011

<img width="229" alt="Screenshot 2020-08-22 at 19 45 20" src="https://user-images.githubusercontent.com/1268723/90962420-0e173380-e4b0-11ea-8c27-736584eafeaf.png">

**Comment by zeroin** [comment]
You add range from the beginning to the end of the month, so the label is somehere at July 15. But your axis actually starts at July 20, naturally, it's invisible. You should check the min/max of the date axis and modify start/end dates of the ranges.

**Comment by jimmykane** [comment]
That did the trick thanks !
