### ISSUE TITLE
How to add click event for each column in XYChart

### ISSUE THREAD

**Issue by tanming363** [amcharts/amcharts4#2825]
### **How to add click event for each column in XY Chart**
I want to add a click event for each column so that I can show particular information of the column.

`pieSeries.slices.template.events.on("hit", function (ev) { 
               var data = ev.target.dataItem.dataContext;
 });`
above code is working for PieChart, so the same thing  I am trying in below code for XYChart but it's not working.

` series.columns.template.events.on("hit", function (ev) {
                var data = ev.target.dataItem.dataContext;
 })`  

[Demo: CodePen](https://codepen.io/tanming363/pen/vYGgxWj)

**Comment by zeroin** [comment]
You should add this code within createSeries method, otherwise your series variable is not defined.

**Comment by tanming363** [comment]
thanks a lot, it's working :)
