### ISSUE TITLE
responsive bug

### ISSUE THREAD

**Issue by nguyenhong1611209** [amcharts/amcharts4#2826]
**I'm really stuck! Can anyone help me
I'm having a responsive error when I reload the page responsive doesn't work when I resize the site it works but only 1 time and then I reload the page and it doesn't work.
I only added 2 charts to the map, responsive works, from 4 charts loaded up responsive doesn't work.**

**here is my code file `
[index - Copy.txt](https://github.com/amcharts/amcharts4/files/5114370/index.-.Copy.txt)
`
**

**Below is a responsive error image. Each 2009 issue is a chart that I add to the map. but because of the responsive bug, it doesn't work.
![image](https://user-images.githubusercontent.com/70104348/90983862-84dd2b00-e59b-11ea-8514-0828ab12ce78.png)
**

**Comment by martynasma** [comment]
I'm afraid we can't run the file you referred to to test. If you think you stumbled on the bug, please consider posting a working live example on CodePen or jsFiddle.

**Comment by nguyenhong1611209** [comment]
> I'm afraid we can't run the file you referred to test. If you think you stumbled on the bug, please consider posting a working live example on CodePen or jsFiddle.

![image](https://user-images.githubusercontent.com/70104348/91017251-2bffa800-e618-11ea-9442-f630f4ee5815.png)
This is my first time opening the website. everything's fine. but when I reload the page, things go awry.
![image](https://user-images.githubusercontent.com/70104348/91017440-72ed9d80-e618-11ea-89a7-b43add7cc783.png)
As you can see, when I reload the page, responsive doesn't work.

**Comment by martynasma** [comment]
We can't test your screenshots, though. Can we? ;)

**Comment by nguyenhong1611209** [comment]
> We can't test your screenshots, though. Can we? ;)

Hi sir, I found the answer in version 4.9.6.
I have a common problem with this man.  https://github.com/amcharts/amcharts4/issues/2204
when I tune everything back to version 4.9.6 everything works flawlessly. No responsive bugs. I don't understand why the latest versions are faulty and only version 496 does not

**Comment by martynasma** [comment]
We'd be happy to test your map, and fix the issue if it's a bug. But we can't do that unless you provide us with the code.

**Comment by nguyenhong1611209** [comment]
> We'd be happy to test your map and fix the issue if it's a bug. But we can't do that unless you provide us with the code.

really sorry about that, I'm using a virtual server(GeoServer and Xampp), so I don't know how to share your code with you

**Comment by martynasma** [comment]
You can create a reduce-case scenario on CodePen.
