### ISSUE TITLE
How to do full stack for mix column and line series 

### ISSUE THREAD

**Issue by yenniSuresh** [amcharts/amcharts4#2827]
Codepen: https://codepen.io/yennisuresh/pen/eYZgrxd

Above codepen contains stacked bar and line series but seems like line series is also being considered in same stack by value axis which make bar stack limited to 80% and 20% used by line.

Expected out: Bar and line series both to have their own individual 100% stacking.

**Comment by martynasma** [comment]
Series of different types are note being stacked on each other.

If you take a look at the LineSeries in your demo, you'll see that it is plotted at exactly the values you have in your data.

**Comment by yenniSuresh** [comment]
@martynasma  Yes, line and bar series are not stack together but their 100% representation against value axis is shared, I was assuming bar stack will have its own 100% representation against value axis and line stack will have its own i.e one on top of other

**Comment by martynasma** [comment]
Well, you don't have `valueYShow` data field, so it is using absolute values.

```
series2.dataFields.valueYShow = "totalPercent";
```

**Comment by yenniSuresh** [comment]
@martynasma sorry, I didn't update that in codepen (now updated) but I have tried that, bar series still doesn't utilise 100% of value axis.

**Comment by martynasma** [comment]
Indeed. Let us take a another look.

**Comment by yenniSuresh** [comment]
Sure, thanks for your time @martynasma

**Comment by martynasma** [comment]
OK, so here's the deal.

`totalPercent` is being calculate for all series and used in other places, not just for stacking. So we can't change it's calculation mechanism.

The solution in this case would be to add `LineSeries` into separate `ValueAxis`, e.g.:

```JavaScript
var  valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.title.text = "Expenditure (%)";
valueAxis.calculateTotals = true;
valueAxis.min = 0;
valueAxis.max = 100;
valueAxis.strictMinMax = true;
valueAxis.renderer.labels.template.adapter.add("text", function(text) {
  return text + "%";
});

var valueAxis2 = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis2.calculateTotals = true;
valueAxis2.min = 0;
valueAxis2.max = 100;
valueAxis2.strictMinMax = true;
valueAxis2.renderer.labels.template.disabled = true;
valueAxis2.renderer.grid.template.disabled = true;

// Create series
var series = chart.series.push(new am4charts.ColumnSeries());
series.dataFields.valueY = "research";
series.dataFields.valueYShow = "totalPercent";
series.dataFields.categoryX = "country";
series.name = "Research";
series.tooltipText = "{name}: [bold]{valueY}[/]";
series.stacked = true;
series.dataFields.valueYShow = "totalPercent";

var series2 = chart.series.push(new am4charts.LineSeries());
series2.dataFields.valueY = "marketing";
series2.dataFields.categoryX = "country";
series2.name = "Marketing";
series2.tooltipText = "{name}: [bold]{valueY}[/]";
series2.stacked = true;
series2.dataFields.valueYShow = "totalPercent";
series2.yAxis = valueAxis2;
series2.strokeWidth = 3;

var series3 = chart.series.push(new am4charts.ColumnSeries());
series3.dataFields.valueY = "sales";
series3.dataFields.valueYShow = "totalPercent";
series3.dataFields.categoryX = "country";
series3.name = "Sales";
series3.tooltipText = "{name}: [bold]{valueY}[/]";
series3.stacked = true;
series3.dataFields.valueYShow = "totalPercent";
```

**Comment by yenniSuresh** [comment]
thanks for the clarity @martynasma, will try to go forward with above suggestion.
