### ISSUE TITLE
2 object data of images series having same location (latitude and longitude)

### ISSUE THREAD

**Issue by AMINEAALI** [amcharts/amcharts4#2828]
Hello, is there a way to ensure that 2 images series of `MapChart` have the same location and make sure that they are side by side, not one over another ? For example if I have this : 

```JSON
imageSeries.data = [{
  "latitude": 48.856614,
  "longitude": 2.352222,
  "title": "Paris",
  "icon": "../icon.png"
},
{
  "latitude": 48.856614,
  "longitude": 2.352222,
  "title": "Paris",
  "icon": "../anothericon.png"
}]
```

I want these 2 data to be side by side on the map, not one over another ( both located in Paris )

**Comment by martynasma** [comment]
There's no built-in way to do that.

You might implement some custom code which sifts through data and applies `dx` to markers if it finds some overlapping.

Sorry, I don't have a demo for it.

Another option is try our experimental [overlap buster plugin](https://www.amcharts.com/docs/v4/tutorials/plugin-overlap-buster/).

**Comment by AMINEAALI** [comment]
> 
> 
> There's no built-in way to do that.
> 
> You might implement some custom code which sifts through data and applies `dx` to markers if it finds some overlapping.
> 
> Sorry, I don't have a demo for it.
> 
> Another option is try our experimental [overlap buster plugin](https://www.amcharts.com/docs/v4/tutorials/plugin-overlap-buster/).

Ok thank you :)
