### ISSUE TITLE
Maps and logarithmic rules

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2829]
I want to use a logarithmic rule on [this map](https://jsfiddle.net/zdL56cbv/3) but when I set the logarithmic property, all countries are displayed with the same color. If I deactivate that property, it works fine but in this case all countries have the same color except one. Am I missing something?

Another issue is that when I set the logarithmic property to true, the values are not displayed on the heat legend. If I set the  logarithmic property to false then everything is working fine. Is there something that I have to take into account when logarithmic property is true?

Thank you.

**Comment by martynasma** [comment]
The thing is that you have countries with negative values, which do not work with logarithmic scale.

No way around it but recalculate your values so they are all > 0.

**Comment by javier-fjfs** [comment]
Now on [this map](https://jsfiddle.net/y25rkjh1/) all values are > 0 but the behavior is the same. Only one color and the heat legend is not working. Do I need to do something else?

Thank you.

**Comment by martynasma** [comment]
It's because you have one area with zero value. You can't calculate logarithm of a zero.

**Comment by javier-fjfs** [comment]
Yes!, sorry, I didn't notice that. Thank you for your help!
