### ISSUE TITLE
Why cursor tooltip show incorrect time?

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#2833]
when we pointing on bullet tooltip show correct time but cursor tooltip show wrong time why is the difference in the value?

![Screenshot (11)](https://user-images.githubusercontent.com/48621208/91168557-74d85f00-e6f3-11ea-9613-8f673c377e1b.png)

_Originally posted by @Swaraj55 in https://github.com/amcharts/amcharts4/issues/2823#issuecomment-679965995_

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Swaraj55** [comment]
Sure, 
https://codepen.io/swarajv5/pen/zYqZepE

**Comment by martynasma** [comment]
Your baseInterval is set to a wrong type:

```
categoryAxis.baseInterval = [{
  "timeUnit": "hour",
  "count" : 1
}]
```

It can't be an array.
