### ISSUE TITLE
Why isn't the label over my map being produced from my geojson using amcharts?

### ISSUE THREAD

**Issue by anshver92** [amcharts/amcharts4#2834]
**Bug description**

I can't seem to produce automatic labels over map polygon like the example used in the [documentation](https://www.amcharts.com/docs/v4/tutorials/automatic-labels-over-map-polygons/). [codepen for this example](https://codepen.io/team/amcharts/pen/QoeVyd).

I adapted the example to use with a different geojson file given in this [link](https://raw.githubusercontent.com/anshver92/walruswondersitaly/master/italian-regions.geojson). However, it doesn't produce the labels anymore. The map still appears. The codepen for the adapted example is given [here](https://codepen.io/anshver92/pen/abNpwoX) . Does anyone have any idea of what the problem could be? Is it in the geojson?

What I am using 

 - amCharts4
 - Chrome 84.0.4147.135
-->

**Additional context**
I also tried the following things:

1) I tried changing the `polygonTemplate.propertyFields.id` to `"id"` and then changing `var ids` accordingly too but that didn't work. The labels on the parts of the map stored in `ids` still did not appear.

**Comment by martynasma** [comment]
Well, since your GeoJSON has ids of the polygons set in numbers, it's a bit different.

I found this to work:

```
// Set up label series to populate
polygonSeries.events.on("datavalidated", function () {
  for(var i = 0; i < ids.length; i++){
  	var polygon = polygonSeries.map.getKey(ids[i]);
  	if(polygon){
	    var label = labelSeries.mapImages.create();
	    var state = polygon.dataItem.dataContext.name;
	    label.latitude = polygon.visualLatitude;
	    label.longitude = polygon.visualLongitude;
	    label.children.getIndex(0).text = state;
	}
  }
});
```

`getPolygonById` does not work because it is referencing directly to GeoJSON data, hence it not finding "lombardia", because it is identified by number 3.

Also, "datavalidated" event is better, because it kicks in later and thus has the chance to set custom ids via `propertyFields` like you have it set up.

Hope this makes sense.

**Comment by anshver92** [comment]
@martynasma Thanks. I had actually modified the geojson to change the `id` to the `name`, but that solution works with the original geojson.
