### ISSUE TITLE
amcharts maps and series

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2835]
I have a requirement to group countries on a map the same way as in this [example](https://www.amcharts.com/demos/grouped-countries-map/). If I set the property 'chart.legend.itemContainers.template.interactionsEnabled' to true, when I select a group the corresponding countries dissapier from the map. Is it possible to use a different background color for these countries so that they are highlighted when the legend is selected?

Thank you.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).

**Comment by javier-fjfs** [comment]
Thank you for your answer. I understand this is not a expected behavior so I appreciate you took the time to review the question.
