### ISSUE TITLE
How to change number formatter from giga(G) to Billions(B) .

### ISSUE THREAD

**Issue by hardikforall** [amcharts/amcharts4#2836]
We have a case where we do not want number format to format values to Giga we just want to show till billions. e.g 5.0G to 5.0B.

what can be done? is there any special format?

**Comment by xorspark** [comment]
You can just modify the bigNumberPrefixes array and set the format you want for billions:

```
chart.numberFormatter.bigNumberPrefixes = [
  { "number": 1e+3, "suffix": "K" },
  { "number": 1e+6, "suffix": "M" },
  { "number": 1e+9, "suffix": "B" },
  // etc ...
];
```

[Tutorial](https://www.amcharts.com/docs/v4/tutorials/modifying-big-number-prefixes/)
