### ISSUE TITLE
Stacked chart full filled

### ISSUE THREAD

**Issue by Sam116** [amcharts/amcharts4#2837]
It is posiible to fill 100% of column in stacked chart? Cant find any same example 

![image](https://user-images.githubusercontent.com/5461966/91577799-ed3c5b80-e951-11ea-99e4-447be7b782a2.png)

**Comment by martynasma** [comment]
I would do it by adding a second series with bigger values, and unclustering all series, so that they overlap:

https://codepen.io/team/amcharts/pen/96aff3067b94c51a40efd5b53130cb28?editors=0010
