### ISSUE TITLE
How to add pulsating animation for specific circles

### ISSUE THREAD

**Issue by AMINEAALI** [amcharts/amcharts4#2839]
Here's the link of a demo : https://jsfiddle.net/esc6dLf7/1/
Let's say for example how to make sure that the only pulsating bullets or those which have a value >= 400.
How to do that ?

 - amCharts version 4.9
 - Latest version of Firefox
 - Angular 10, TypeSript 3.9

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
