### ISSUE TITLE
Watermark Image missing on Chart Export

### ISSUE THREAD

**Issue by octopusabhiraj** [amcharts/amcharts4#2840]
**Bug description**

I am trying to export the watermark image along with the chart. I am also adding a title just during export (which works fine). 

This is how the chart looks in a browser.
![image](https://user-images.githubusercontent.com/47333991/91589013-0aa80000-e927-11ea-81c5-ff1e1d41b7c1.png)

But when I export the chart as PNG, the watermark disappears.
![image](https://user-images.githubusercontent.com/47333991/91589055-1bf10c80-e927-11ea-8256-8c9f16c1e9f3.png)

AmChart version is 4.
Using files:

1. https://cdn.amcharts.com/lib/4/core.js
2. https://cdn.amcharts.com/lib/4/charts.js

Here's the code snippet of the watermark.

```
var options = chart.exporting.getFormatOptions("png");
options.keepTainted = true;
chart.exporting.setFormatOptions("png", options);

var watermark = new am4core.Image();
watermark.href = "http://localhost:3001/assets/images/car.png";
chart.plotContainer.children.push(watermark);
watermark.align = "right";
watermark.valign = "top";
watermark.marginRight = 10;
watermark.marginBottom = 5;
watermark.exportable = true;

chart.exporting.validateSprites.push(watermark);
```

How can I fix this? My aim is to have the watermark/logo on the exported image.

Thanks in advance.

**Comment by martynasma** [comment]
Is the web page loaded from http://localhost:3001/ as well? If not, then image is considered "tainted" and is removed on export.

The only way to to make images export is to load them from exactly same host as the web page.

**Comment by octopusabhiraj** [comment]
I am testing it on CodePen.io. In order to keep the "tainted" images, I used the following block of code as well.

```
var options = chart.exporting.getFormatOptions("png");
options.keepTainted = true;
chart.exporting.setFormatOptions("png", options);
```

Shouldn't this help?

**Comment by martynasma** [comment]
No it won't help. The browser security restrictions will kick in and prevent canvas created with tainted images.

**Comment by octopusabhiraj** [comment]
Alright. I thought the documentation says otherwise - https://www.amcharts.com/docs/v4/concepts/exporting/#Tainted_images

Anyway, thanks, @martynasma.

**Comment by Logicobal** [comment]
```
    var watermark = new am4core.Image();


    watermark.href = "YOUR IMAGE URL";

    chart.plotContainer.children.push(watermark);

    watermark.align = "right";

    watermark.valign = "bottom";

    watermark.opacity = 0.4;

    watermark.width = 120;

    watermark.marginRight = 10;

    watermark.marginBottom = 5;
```
