### ISSUE TITLE
amcharts tooltip background

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2841]
I want to set the background of a tootilp to white color but when a I set the property background.fill to 'white', what I see is like a bone color with some transparency as you can see in [this code](https://jsfiddle.net/0fhw1q98/2/). These are the lines I'm using:

```
series.tooltip.getFillFromObject = false;
series.tooltip.background.fill = am4core.color("white");
```
If I change the color to something different to white, then it works but if I set the property to 'white' or '#ffffff', then the background is not exactly white. How can I set the background of the tooltip to full white without any transparency?

Thank you.

**Comment by martynasma** [comment]
That's because tooltip's fill is semi-transparent by default. To make it fully opaque set its `fillOpacity` to 1.

```
series.tooltip.background.fillOpacity = 1;
```

**Comment by javier-fjfs** [comment]
That works perfect. Thank you!!
