### ISSUE TITLE
chart not Responsive 

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#2842]
https://codepen.io/mahisandy/pen/xxVLZrN

label are overlaping 

https://codepen.io/mahisandy/pen/Yzqxwry

pie chart label are cutting

**Comment by martynasma** [comment]
I suggest you take a look at this pieces of documentation:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Controlling_spacing
https://www.amcharts.com/docs/v4/tutorials/dealing-with-piechart-labels-that-dont-fit/
https://www.amcharts.com/docs/v4/concepts/responsive/
