### ISSUE TITLE
Wrong custom geodata?

### ISSUE THREAD

**Issue by adamalexandru4** [amcharts/amcharts4#2843]
I'm trying to render the following GeoJSON [https://raw.githubusercontent.com/akaleeroy/romania-uat/master/geojson/AB.geojson](url) but the map is empty, without any polygons (white screen). 

With geodata from your repository the amchart map works fine.
I checked my geojson file but it looks fine. 
Any solution?

**Comment by xorspark** [comment]
Your polygons are missing their respective unique `id` properties, which amCharts requires. The `natcode` looks like a good candidate, but pick whichever unique value you want.

```
	"type": "FeatureCollection",
	"features": [{
			"type": "Feature",
			"geometry": {
				"type": "Polygon",
                               // ...
			},
			"properties": {
				"natcode": "4482",
                                "id": "4482", 
                                // ...
			}
		},
               // ...
```

If you rather not regenerate your JSON, you can modify it prior to assigning it to the chart's `geodata` property. [Demo](https://codepen.io/team/amcharts/pen/bbf987910e8095267fdcc7e6303ebf67?editors=0010)

**Comment by adamalexandru4** [comment]
Thank you a lot @xorspark !!
