### ISSUE TITLE
Graph taking too long making UI unresponsive 

### ISSUE THREAD

**Issue by maximinogomez** [amcharts/amcharts4#2844]
Hi, 

I using a Gantt graph which works very well small datasets. However when I give it more than 20K data points the graph takes a very long time(minutes) to render making the UI unresponsive and bringing my browser to a crawl. I have followed all the steps to improve performance as mentioned on https://www.amcharts.com/docs/v4/concepts/performance/ but nothing helps. Is it too much data for this type of graph? 

**Question**

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
There's currently no way to speed up a Gantt chart with 20k data points. There's simply too many elements. Sorry.
