### ISSUE TITLE
The graphs do not start drawing until you return to the report page

### ISSUE THREAD

**Issue by Anna11235813** [amcharts/amcharts4#2845]
Hey, I'm using simple html+php+JS page for the report with 20+ charts (using amcharts4). I've used suggested tips to improve performance (lazy loading, smoothed lines and queue for rendering), but the graphs start to draw only when I return to the page. 

Use case is:
- open the report page
- go to other pages while DOM is loading
- return to the report page, but the graphs are just starting to be rendered

In the third point, no matter how long I wait to return to the report, the graphs will not be pre-displayed.I tried with different options (am4core.options.queue, am4core.options.onlyShowOnViewport), but nothing helps.

Is there a way to start rendering without user interaction?

Sorry I'm not so good at frontend terminology, so let me know if you need other details or example.
Thank you in advance!

**Comment by martynasma** [comment]
This is by design. Charts/browsers are optimized not to use CPU for windows/tabs that are not in focus.

**Comment by Anna11235813** [comment]
So there is no way to avoid this, is there? amcharts3 didn't have this functionality

**Comment by martynasma** [comment]
No, I'm afraid. amCharts 4 uses animation frames that are usually paused when tab is not in focus, so that background tabs do not interfere with the browsing experience.
