### ISSUE TITLE
Map - Deselect last selected country

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2846]
I'm trying to create a chart where if you select the same country twice, the chart zooms out and deselects the country. So far it zooms out, but I can't get it to "reset" the active state.

Any suggestions?

Pen https://codepen.io/Josh519/pen/PoNKyYK

**Comment by martynasma** [comment]
You don't need this line:

```
lastSelected.isActive = false;
```

You already have "active" state which is automatically toggled on and off when clicking on an element repeatedly.

What happens is that your code resets `isActive` setting, then built in toggling mechanism kicks in checks `isActive` finds it to be `false` and decides it needs to turn active state on.

Remove the above line should fix it.

**Comment by Josh10101010** [comment]
I removed the line, however, if I zoom in a country and then click one next to it, the other country removes highlighted.

**Comment by martynasma** [comment]
In that case you might consider not using `isActive` and "active" state at all.

Instead create your own custom state, e.g. "myActiveState". Then just apply that state or "default" state on "hit" event, as per your code.
