### ISSUE TITLE
Legend Labels are cut - Chart Responsive problems

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#2847]
Hey I have a chart with 6 series on top , I break my head in figure out how to make each item act as flex item in the legend , which means when no enough space the item should move to the next line.
What instead I got are labels which are cut off by their text.
Here is a reproduce of this problem:
https://codesandbox.io/s/immutable-monad-wdeu6?file=/src/app/app.component.ts

**Comment by martynasma** [comment]
You might find this useful:

https://www.amcharts.com/docs/v4/tutorials/truncating-legend-labels/

**Comment by BrkCoder** [comment]
hey @martynasma thanks for the quick answers,  but I have already read this guide and it didn't  help me.
I have define:
      chart.legend.labels.template.maxWidth = 1500;
      chart.legend.labels.template.truncate = true;
and still I can't see all the text of labels, maybe I missing something here?

**Comment by martynasma** [comment]
If you mean you want legend items to wrap to multiple lines if they don't fit, you should get rid of this line:

```
legend.layout = "horizontal";
```

**Comment by BrkCoder** [comment]
thx this solved the problem!
