### ISSUE TITLE
Unable to set Map projection as { type: "projection_name" } in createFromConfig

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#285]
The [JSON documentation for Maps](https://www.amcharts.com/docs/v4/chart-types/map/#Setting_projection) states that a projection can be set through the projection property like so:

```
projection: {
  type: "Miller"
}
```

However doing this results in a `this.series.chart.projection.projectGeoArea is not a function` error. This can be worked around by setting the projection property to an `am4maps.projection` object but this makes it less JSON-like.

[Codepen](https://codepen.io/team/amcharts/pen/8db9c49525beeaa62dde388425cb034a?editors=0010)

**Comment by martynasma** [comment]
Error in docs. Should be:

```
"projection": "Miller"
```

P.S. docs updated accordingly.
