### ISSUE TITLE
Regional USA Maps not centered when using MapPolygonSeries include property 

### ISSUE THREAD

**Issue by rdalfonso** [amcharts/amcharts4#2850]
I've noticed that Regional USA Maps when using MapPolygonSeries include to show partial state maps, aren't centered correctly and part of the map (bottom, top, left, right) disappears or is cut off. I've included same code that loads ISO county codes for Southern NJ (photo showing the map cut off on left is attached). This issue happens sporadically on various groupings of state counties, however. I've pasted the most basic implementation of the React/Type script map code below. Is this a bug with Amcharts?

```
import React, { Component } from 'react';
import { withRouter } from 'react-router-dom';
import * as am4core from '@amcharts/amcharts4/core';
import * as am4maps from '@amcharts/amcharts4/maps';
import am4themesAnimated from '@amcharts/amcharts4/themes/animated';
import am4geodataRegionUsaNjLow from '@amcharts/amcharts4-geodata/region/usa/njLow';
am4core.useTheme(am4themesAnimated);

class MapTemp extends Component<any, any> {
  map: any;
  polygonSeries: any;

  componentDidMount() {
    am4core.options.commercialLicense = true;
    const map = am4core.create('mapSearch', am4maps.MapChart);
    map.geodata = am4geodataRegionUsaNjLow;
    map.projection = new am4maps.projections.Mercator();

    let includedCounties = [];
    includedCounties.push('34001');
    includedCounties.push('34011');
    includedCounties.push('34009');

    const polygonSeries = new am4maps.MapPolygonSeries();
    polygonSeries.useGeodata = true;
    polygonSeries.include = includedCounties;
    polygonSeries.fill = am4core.color('#fff');
    map.series.push(polygonSeries);

    // Configure series
    const polygonTemplate = polygonSeries.mapPolygons.template;
    const hs = polygonTemplate.states.create('hover');
    hs.properties.fill = am4core.color('#FA6401');

    //Set color of active state to same color as hover
    const acs = polygonTemplate.states.create('active');
    acs.properties.fill = am4core.color('#FA6401');

    polygonTemplate.tooltipText = '{name}';
    polygonTemplate.fill = am4core.color('#dddddd');

    this.polygonSeries = polygonSeries;
    this.map = map;
  }

 componentWillUnmount() {
    if (this.map) {
      this.map.dispose();
    }
  }

  render() {
    return (
      <div>
        <div id="mapSearch" style={{ height: '400px', textAlign: 'center', background: '#eeeeee', zIndex: 2 }} />
      </div>
    );
  }
}

export default withRouter(MapTemp);
```

![image](https://user-images.githubusercontent.com/4713950/91894335-2a0e9800-ec5b-11ea-92c9-e9256be0d436.png)

**Comment by xorspark** [comment]
Your map looks centered to me in this [codepen](https://codepen.io/team/amcharts/pen/97bfd9a7c0d5c9df9a2fc44e0c2ececf). Are you on the latest release? We're currently on 4.10.0.

**Comment by rdalfonso** [comment]
I'm on 4.3.5. I'll see if an upgrade solves it

**Comment by rdalfonso** [comment]
@xorspark - Upgrading did not solve the issue.

**Comment by xorspark** [comment]
We need a repro then. Can you provide a codepen or stackblitz that reproduces the problem? I can't reproduce it using your code either in the above codepen or [in this stackblitz](https://stackblitz.com/edit/react-ts-d1i2hm)

**Comment by rdalfonso** [comment]
@xorspark - when I switch the version paths in your CodePen example to 4.3.5 (below) I was able to reproduce the issue! I'm going to upgrade my development environment to 4.10.0 and try again.

<script src="https://cdn.amcharts.com/lib/version/4.3.5/core.js"></script>
<script src="https://cdn.amcharts.com/lib/version/4.3.5/maps.js"></script>
<script src="https://cdn.amcharts.com/lib/version/4.3.5/themes/animated.js"></script>

**Comment by rdalfonso** [comment]
This issue has been fixed after upgrading the package. Thank.

**Comment by rdalfonso** [comment]
@xorspark  - Version 4.10 caused a build issue (js from Terser Unexpected token: expand (...)) so I upgraded from 4.3.5 to the most recent version that fixes the issue 4.5.0. However, this caused an issue when loading the map with SSR. Do you know of a stable version that's closest to 4.5.0 that fixes the original issue and doesn't causes an issue with SSR?

**Comment by martynasma** [comment]
@rdalfonso Make sure you follow the following tutorial closely for SSR to work:

https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/

Please note that this tutorial has been updated specifically for SSR support purposes very recently.

**Comment by rdalfonso** [comment]
The issue has been solved. Thanks
