### ISSUE TITLE
Property 'category' does not exist on type 'IAxisDataFields'.

### ISSUE THREAD

**Issue by steve3d** [amcharts/amcharts4#2851]
**Bug description**
I'm upgrading a project to angular 10, which use typescript 3.9, and after upgrades, some of old code won't compile any more:

```
        const chart = ChartUtils.createChild(container, RadarChart);
        const categoryAxis = chart.xAxes.push(new CategoryAxis());
        categoryAxis.dataFields.category = 'user_id';
        categoryAxis.renderer.labels.template.radius = 10;
        categoryAxis.renderer.minGridDistance = 5;
        categoryAxis.gridType = 'polygon';
```

this generates following error
```
ERROR in resources/src/module-safety/hidden-danger-stats/hidden-danger-stats.component.ts:331:33 - error TS2339: Property 'category' does not exist on type 'IAxisDataFields'.

331         categoryAxis.dataFields.category = 'user_id';
                                    ~~~~~~~~
resources/src/module-safety/hidden-danger-stats/hidden-danger-stats.component.ts:335:22 - error TS2339: Property 'gridType' does not exist on type 'Axis<AxisRendererCircular>'.

335         categoryAxis.gridType = 'polygon';
```

**Additional context**

if i change the category axis to `const categoryAxis: CategoryAxis<AxisRendererCircular> = chart.xAxes.push(new CategoryAxis());`

then the first error gone, but sill told me that `gridType` does not exists. 

and also, with angular 10 there are many warnings created as #2848

**Comment by martynasma** [comment]
Your solution to the first problem is proper.

As for the second, X axis on RadarChart uses `AxisRendererCircular` which does not support `gridType`, hence the error.

BTW, you're setting `gridType` directly on axis, whereas it's a renderer setting.

You need to set it on renderer of the Y axis which uses `AxisRendererRadial`:

```
const valueAxis: ValueAxis<AxisRendererRadial> = chart.yAxes.push(new ValueAxis());
valueAxis.renderer.gridType = "polygons";
```

I suggest you subscribe to updates on #2848 to keep track of any developments regarding 3rd party canvg and Angular 10.
