### ISSUE TITLE
How do I automatically resize the Y-axis based on the displayed graphs?

### ISSUE THREAD

**Issue by NemoDima** [amcharts/amcharts4#2852]
**Question**
Suggest me please, how do I automatically resize the Y-axis based only on the **displayed** graphs?
Currently, I have the graph on which Y-axis sized to the max graph which I have but doesn't showed.

https://codepen.io/vovaltus/pen/jOONJOv?editors=0010
"Макс. выкладка"- disabled, but still affects the Y-axis

**Environment (if applicable)**

amcharts - 4.10.0
Chrome Version 85.0.4183.83
Angular 5, typescript 2.8

**Comment by martynasma** [comment]
Seems like a bug, caused by vertical scrollbar.

We're going to take a look if we can fix it. Meanwhile, you can disable scrollbar for immediate effect.

Thanks for bringing it to our attention.

**Comment by martynasma** [comment]
OK, so the issue is that there's no way to remedy that when using two Y axes and a vertical scrollbar.

The two (not perfect) workarounds would be:

1) Disable vertical scrollbar.
2) Disable zooming of the second axis:

```
chartYAxix2.zoomable = false;
```

**Comment by NemoDima** [comment]
@martynasma thank you for the suggestion, I'll check it.
Could you tell me please, is any chance to fix this problem?

**Comment by martynasma** [comment]
> Could you tell me please, is any chance to fix this problem?

No, sorry. There's too many moving parts and no correct way to handle all situations when zoom can come from two different sources: scrollbar and value range.

**Comment by NemoDima** [comment]
@martynasma , thank you for the explanation.

**Comment by NemoDima** [comment]
@martynasma we try to use the second workaround but it didn't help.
Could you check it please https://codepen.io/vovaltus/pen/MWyXQYY line 2528?
Maybe I misunderstood smth?
Thanks

**Comment by NemoDima** [comment]
@martynasma  , we have updated the codepen: https://codepen.io/vovaltus/pen/jOONJOv?editors=1000
Could you please check it and maybe update the resolution for this bug report?
I'll be appreciated.
Best wishes.
