### ISSUE TITLE
Do we have "disappeared" event on column series?

### ISSUE THREAD

**Issue by andreymishagin** [amcharts/amcharts4#2853]
I've found in column series's docs event appear, that described as "Invoked when Sprite appears. Sprite appears when sprite.appear() method is called and show animation is finished."

But i can't found event, when Sprite disappears and show animation is finished?

**Comment by martynasma** [comment]
No, I'm afraid there's no such event.

There is `hidden` event. You might use it then delay the action which is supposed to kick in after series is hidden by animation duration:

```
series.events.on("hidden", function(event) {
  setTimeout(function() {
    // do whatever needs to be done when series is finished hiding
    // ...
  }, event.target.defaultState.transitionDuration);
});
```

**Comment by andreymishagin** [comment]
It works. Thank you!
