### ISSUE TITLE
amcharts treemap small items text

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2854]
I'm working with a treemap that has many child items. I have defined a bullet to show a text on each element but the treemap always displays the text (or at least part of the text) on all items even the smaller ones. This means that If I have many small items, the texts overlap and the effect is that there are many letters all together. Is there any way to avoid displaying the text when the items are very small or when the bullet's text is much longer than the item?

Thank you.

**Comment by martynasma** [comment]
You may use label's setting `hideOversized` to force hiding of labels that do not fit, e.g.:

```
bullet1.label.hideOversized = true;
```

**Comment by javier-fjfs** [comment]
Thank you. That works but there are still many items that are showing a bullet with only one character. I don't know if there is any additional option to control the visibility of bullets depending on the item size.

Another question related to bullet's appearance. Is there any way to change the size of bullet's font size depending on the item's size? What I'd like to get is the something similar to [this example](https://oec.world/en/visualize/tree_map/hs92/export/prk/all/show/2018/).

Thank you again.

**Comment by javier-fjfs** [comment]
Just wanted to share the [code of the treemap](https://jsfiddle.net/fu3rzvd9/1/) I have. As you can see, even with the `hideOversized` property set to true, there are many small items displaying only one or two charecters. In addition, on these small items the bullet's text is not respecting the `locationX `and `locationY `properties so there's some overlapping between treemap's items.

**Comment by martynasma** [comment]
You can also set `truncate = false` on labels:

```
bullet1.label.truncate = false;
```

And yes, it's possible to dynamically size labels use heat rules, but it's a whole new topic. If you wish to discuss it, please open another issue. I'll just link tutorial here:
https://www.amcharts.com/docs/v4/concepts/series/#Heat_maps

**Comment by javier-fjfs** [comment]
Thank you for your response but with `truncate = false` almost all texts are hidden because they are quite long. What I need is to truncate the text but when only one or two characters are displayed, then in those cases hide the bullet. Is that possible?

Thank you.

**Comment by martynasma** [comment]
Maybe an adapter:

```
bullet1.label.adapter.add('textOutput', function(text, target) {
  return target.maxWidth < 50 ? "" : text;
})
```

**Comment by javier-fjfs** [comment]
That works perfect. Thank you!!

**Comment by dileeptp** [comment]
Thank you @martynasma . You are a life saver.
