### ISSUE TITLE
Vue Js with am4charts: building package takes very long

### ISSUE THREAD

**Issue by JackShepard98** [amcharts/amcharts4#2855]
Hi,

I am using am4charts inside my vue js app. When running npm run serve (translates to vue-cli-service serve) everything goes fine but when trying to build: npm run build (vue-cli-service build) it gets stuck at: "Building for production...". After about half an hour the build is done but it's  almost 30 mb (build without am4chart is around 10 mb). Is there any way to make the build take less time?

Thanks

**Comment by JackShepard98** [comment]
I noticed this happens when using minify libraries (Terser or Babel-minify) in my webpack config. Is there any way to fix this without removing the minifier?

**Comment by martynasma** [comment]
You may find this tutorial useful:
https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/

Let me know if you aren't able to resolve this with suggestions in the tutorial.
