### ISSUE TITLE
Multi tooltip with dynamic series

### ISSUE THREAD

**Issue by emortri** [amcharts/amcharts4#2857]
Hi!, i'm trying to make a custom dynamic tooltip that have all series data inside.
Ill try to explain, i have a minimum of 1 serie and a maximum of 4. I want to display a single tooltip with all the information of those 1-4 series. Like this:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/12174790/92114917-ea2de900-edf1-11ea-96cc-7ad81e1d18c9.png">

I have this code, i'm trying to make a tooltip but only takes the last iteration value obviously. I don't know if its a good practice generate series like that. I retrieve data from a service that gives me dates and prices for a stock. I'm trying to compare this stocks.

https://jsfiddle.net/emortri/qa1g5w0k/2/

I don't know if its possible to access to a "global tooltip" or something like that.

Thanks and sorry my english.

**Comment by martynasma** [comment]
You might find the following tutorials useful:
https://www.amcharts.com/docs/v4/tutorials/multi-series-shared-tooltip-with-colored-bullets/
https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/
