### ISSUE TITLE
treemap tooltip behavior

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2859]
I have a treemap with a tooltipHTML that is working fine. I have created a bullet that has the same tooltip as the template:

```
let level2_column_left = this.level2SeriesTemplateLeft.columns.template;
level2_column_left.tooltipHTML = <my html>
level2_bullet_left.tooltipHTML = level2_column_left.tooltipHTML;
```
The problem is that the same tooltip behaves in a diiferent way. For the template it is displayed according to the limits of the charts but that is not happening with the bullet tooltip, as you can see on these images:

Template tooltip (woks fine):
![good](https://user-images.githubusercontent.com/12800152/92180894-152a3400-ee16-11ea-88c5-8cc963ab4097.PNG)

Bullet tooltip (the same tooltip is displayed outside the container):
![bad](https://user-images.githubusercontent.com/12800152/92180984-3ee35b00-ee16-11ea-9cec-6bb7137a302e.PNG)

Is there any way to display the bullet tootip the same way as the template tooltip? What I need is that the bullet tooltip is displayed inside the container the same way as the template tooltip.

Thank you.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by javier-fjfs** [comment]
I've just realized that setting the bullet's property interactionsEnabled to false is the solution I needed in order to enable the bullet's tooltip on any part each treemap item.
