### ISSUE TITLE
Coloring world countries according to certain conditions

### ISSUE THREAD

**Issue by sergiocastrovale** [amcharts/amcharts4#286]
I'm trying to set the `fill` property of my polygonSeries according to these conditions:

- `dataItem.dataContext.owner` is null? Fill with color 1
- `dataItem.dataContext.owner` is not null and matches the current user? Fill with color 2
- `dataItem.dataContext.owner` is not null and doesn't match the current user? Fill with color 3

I can't find this anywhere on the docs nor the few amcharts 4 map examples on codepen. I've been able to set up a heat map:

```
      polygonSeries.heatRules.push({
        property: "fill",
        target: polygonTemplate,
        min: am4core.color("#74B266"),
        max: am4core.color("#ec5113")
      })
```

... but that doesn't work for what I need. Thanks in advance.

**Comment by martynasma** [comment]
Looks like you need an adapter for that:
https://www.amcharts.com/docs/v4/concepts/adapters/

E.g.:

```
polygonSeries.mapPolygons.template.adapter.add("fill", function(fill, target) {
  if (target.dataItem.dataContext.owner == null) {
    return am4core.color("#f00");
  }
  else {
    return am4core.color("#0f0");
  }
});
```

**Comment by sergiocastrovale** [comment]
That did the trick, thanks! Suggestion: I know it must be terribly boring but we could use a bunch more codepen map examples for v4 :)

**Comment by martynasma** [comment]
I agree. Whenever we solve a ticket like that, we try to turn it into a tutorial, or a section in related documentation article. Those are always accompanied with a live demo.

There's quite a bunch already:
https://www.amcharts.com/docs/v4/tutorials/

I'm sure this issue will reincarnate into a small tutorial as well :)

**Comment by sergiocastrovale** [comment]
@martynasma thanks, that's pretty useful. However, it's still a pain to navigate through all that; only a few are map examples and we can't really see the outcome like in codepen.
