### ISSUE TITLE
Add today marker

### ISSUE THREAD

**Issue by frank-fajardo-a142179** [amcharts/amcharts4#2861]
**Question**

How can I add a today marker like this:
![image](https://user-images.githubusercontent.com/35437382/92212775-d196ff00-eed5-11ea-91fe-fb00dc138916.png)

I tried adding an axis range with a tooltip but I could only manage this... I could not get the tooltip to display outside of the chart. See CodePen here: https://codepen.io/frankfajardo/pen/dyMZVxv?editors=0010

![image](https://user-images.githubusercontent.com/35437382/92212002-acee5780-eed4-11ea-97e8-fa12d598e219.png)

I also tried using a `FlagBullet` which gave me the same result: https://codepen.io/frankfajardo/pen/dyMZVxv?editors=0010

**Environment (if applicable)**
 - amCharts version 4

**Comment by martynasma** [comment]
This will do the trick:

```
flag.tooltipText = 'Today';
flag.showTooltipOn = 'always';
flag.tooltipY = -160;
flag.tooltip = new am4core.Tooltip();
flag.tooltip.pointerOrientation = "down";
```

As for your other question, `target.dataItem.dateX` will contain label's `Date` object. You can check against current date and return specific color accordingly.

**Comment by frank-fajardo-a142179** [comment]
I did what you suggested to the flag but the tooltip is getting clipped. How do I prevent that?

Also, `target.dateItem.dateX` does not exist. I tried `target.dataItem.dates.date` but the fill is not getting applied somehow:

```
dateAxis.renderer.labels.template.adapter.add('fill', (fill, target) => { 
      if (target.dataItem.dates.date === new Date(2018, 0, 3)) {
        return am4core.color('blue');  
      }
      return am4core.color('red');
});

![image](https://user-images.githubusercontent.com/35437382/92217638-4a4c8a00-eedb-11ea-999d-48cd5eaaf4a6.png)

**Comment by martynasma** [comment]
Well, adding some `chart.paddingTop` should help :)

Let's keep this place clutter-free, both for our own sake and the other's. Since your other question is not related to original topic, can you please post a separate issue?

**Comment by frank-fajardo-a142179** [comment]
@martynasma sorry I should have said I actually tried adding `chart.paddingTop` earlier before even raising this question. But that didn't work. All it did was squish the chart down and push the tooltip higher over the chart. This is the chart with `chart.paddingTop = 100;` to make the effect obvious

![image](https://user-images.githubusercontent.com/35437382/92336820-18f4d980-f0e8-11ea-937c-ca7a298d884c.png)

I also tried  `chart.plotContainer.paddingTop` but that had a worse effect.

(I'll move the question about XHChartScrollbar to another issue.)

Thanks in advance for your help.

**Comment by frank-fajardo-a142179** [comment]
Actually I have fixed the problem with the tooltip getting clipped. So all I need assistance with now is the changing of the color of the date-axis label.

For the tooltip, I wrapped the chart with another `<div>` and prevented margin collapsing (by adding `display: flex` to the shell). I then added top padding to the `chartdiv` via CSS. Adding the padding programmatically via `chart.paddingTop` does not appear to work in this scenario. Not sure why.

**Comment by frank-fajardo-a142179** [comment]
I was doing the date comparison wrong. It should be:

```
dateAxis.renderer.labels.template.adapter.add('fill', (fill, target) => { 
      if (target.dataItem.dates.date && target.dataItem.dates.date.getTime() === new Date(2018, 0, 3).getTime()) {
        return am4core.color('blue');  
      }
      return am4core.color('red');
});
```

**Comment by frank-fajardo-a142179** [comment]
@martynasma sorry mate. I have to reopen this.
The tooltip for the flag bullet does not go away when flag gets outside the zoom-in zone:

![image](https://user-images.githubusercontent.com/35437382/92420589-a8b58900-f1b7-11ea-95ed-3351c661b418.png)

**Comment by martynasma** [comment]
I suppose the solution is then to watch for axis zoom events, and hide tooltip if your "today" marker does not fall within the range.

https://www.amcharts.com/docs/v4/tutorials/handling-axis-zoom-events-via-api/

**Comment by frank-fajardo-a142179** [comment]
We ended up using the flag bullet, with the flag showing the text instead of the tooltip, and disabled the tooltip.
