### ISSUE TITLE
Axial arrows

### ISSUE THREAD

**Issue by AGrazka** [amcharts/amcharts4#2862]
Is it possible to add arrows to the ends of the axis? I need it for my column chart.
I mean the arrow as in the picture below (the red one).

![image](https://user-images.githubusercontent.com/41653062/92227732-fb84fd00-eea6-11ea-8617-0c58033c8f3b.png)

Thanks.

**Comment by martynasma** [comment]
Challenge accepted :)

https://codepen.io/team/amcharts/pen/bGpYxLp?editors=0010

The idea is that we put various elements like `Container`, `Line`, and `Triangle` into predefined chart containers like `topAxesContainer` and `leftAxesContainer`.

More information about chart containers here:
https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/

**Comment by AGrazka** [comment]
I already gave up, thinking it was impossible - huuuge thank you !
