### ISSUE TITLE
How to display Day of the week  [ Mon, Tues] instead of date like[ Jan 01,Jan 02  or  01 02 ] on Date axis

### ISSUE THREAD

**Issue by gaurav30-hkr** [amcharts/amcharts4#2863]
**Question**
How to display Day [ like Mon, Tues ] on my dateaxis using amcharts.
Data : Data for 1 week from Monday to Sunday by Date and instead of showing date on dateaxis my requirement is to show day

**Environment (if applicable)**
Angular 9 , HTML
TypeScript 3.8

**Additional context**
Support is provided on : https://www.amcharts.com/docs/v4/concepts/formatters/formatting-date-time/
but have no idea about how to use it

**Comment by martynasma** [comment]
Perhaps this tutorial is better:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Formatting_date_and_time
