### ISSUE TITLE
Amchart4 XY chart Series tooltip background html div

### ISSUE THREAD

**Issue by anilkumar763** [amcharts/amcharts4#2864]
I'm using XY chart, to draw bar-chart.
I want to render HTML content for toolTip  , by return a div, with the background-border-color as the bar.

series.tooltip.label.adapter.add("textOutput", (text, target, key) => {
  console.log(target.backgroound)
  if (target.dataItem) {
//  return HTMLDiv, with background color as target bar color
  }
  return '';
});

I tried looking for the background & color properties on "target" in the callback, but couldn't get any / they are null values.
How to get that background-color and use it, in my return HTML.

**Comment by martynasma** [comment]
Try `target.targetSprite.fill` or `target.dataItem.component.fill`.

**Comment by sajidAzeem** [comment]
I an using following code to display tooltip in a barchart. 
`     series.adapter.add('tooltipText', (text, target) => {
        const data = target.tooltipDataItem.dataContext;
        if (target.tooltipDataItem.dataContext) {
          return '{categoryY}: [bold]{valueX.formatNumber(\'$' + '#,###.##\')}[/]';
        }
        else {
          return text;
        }
      });`
 I wanted to apply styles like border color, background color.. etc. I have used below line to inherit respective bar color to tooltip border. It's showing only blue color as tooltip border color at all bars. I want to change the tooltip border to respective bar color we are pointing to. 
`series.tooltip.getStrokeFromObject = true;`

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v4/concepts/tooltips/#Configuring_appearance
