### ISSUE TITLE
Can not import @amcharts/amcharts4/core.js. SyntaxError: Unexpected token 'export'.

### ISSUE THREAD

**Issue by exoriri** [amcharts/amcharts4#2865]
I am trying to Amcharts 4 with React and Typescript. I have installed all dependencies as it is written in documentation. Then I try to import amcharts like this: 

 `import * as am4core from "@amcharts/amcharts4/core.js";`
 `import * as am4charts from "@amcharts/amcharts4/charts.js"; `
 `import am4themes_animated from "@amcharts/amcharts4/themes/animated.js";`
 `am4core.useTheme(am4themes_animated);`

However, I when I do that, I get error:
  
![image](https://user-images.githubusercontent.com/29581006/92286676-5c94eb00-ef10-11ea-915e-a43a1d8502ec.png)

I tried to downgrade webpack to `4.28.4`, install `acorn`, but it didn't help. The question is: is it possible to fix this error?

Would be glad to hear from you. Thanks.

**Comment by martynasma** [comment]
What version of TypeScript are you using?

**Comment by exoriri** [comment]
Typescript version is 3.7.3

**Comment by martynasma** [comment]
Thanks. I'm afraid amCharts 4 requires at least 2.9.

**Comment by Pauan** [comment]
@exoriri Are you using `yarn build` or `yarn test`?

**Comment by exoriri** [comment]
@Pauan I use `npm run dev`, it starts my development server

**Comment by Pauan** [comment]
@exoriri Can you share your configuration? By default React apps have no problems at all with ES6 modules (Webpack has built-in support for ES6 modules).
