### ISSUE TITLE
[Question] Is there any way to disable grid lines ONLY in the inside of the chart?

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#2866]
Hello,

Thank you for providing this library, it works great so far but I couldn't find an answer to my question on the docs. I understand it's possible to disable grid lines entirely, but it is possible to disable only those inside the chart and allow X and Y axis to show?

Like in this example [codepen](https://codepen.io/team/amcharts/pen/RYxdgx) all grid lines are shown but I'd like to only have a box grid or just for X/Y axis.

I tried the following

`valueAxis.renderer.grid.template.strokeWidth = 0;`

`valueAxis.renderer.grid.template.disabled = true;`

But then I get all grid lines disabled.

**Comment by martynasma** [comment]
If you're OK of having full outline on the plot area, you may disable grid like you have above, then enable stroke on `plotContainer`:

```
valueAxis.renderer.grid.template.disabled = true;

chart.plotContainer.strokeOpacity = 0.2;
chart.plotContainer.stroke = am4core.color("#000");
```

If you want only the top ant bottom lines there are more steps:

1) Disable grid.
2) Add another X axis on top.

```
var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "category";
categoryAxis.renderer.grid.template.location = 0;

var categoryAxis2 = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis2.dataFields.category = "category";
categoryAxis2.renderer.grid.template.disabled = true;
categoryAxis2.renderer.labels.template.disabled = true;
categoryAxis2.renderer.opposite = true;
categoryAxis2.renderer.line.strokeOpacity = 0.2;
```

**Comment by teodosii** [comment]
Thank you!
