### ISSUE TITLE
CategoryAxis image tooltips

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2868]
I've create a chart using images in the categories, as show in this example

https://www.amcharts.com/demos/images-as-categories/

I would like each image to have its own custom tooltip text, passed in with the chart data object.

I've achieved this with the following code, but it feels "hacky", is there a more appropriate/efficient way to do this using property fields etc? I've also tried with an adapter, but was unsuccessful.

```
Chart.data = [{
    "cat": "a",
    "value": -57,
    "fill": "#3cb4e5",
    "definition": "One"
}, {
    "cat": "b",
    "value": 52,
    "fill": "#00c18b",
    "definition": "Two"
}]

series.events.on("ready", function (ev) {
    for (x in categoryAxis.dataItems.values) {
    	categoryAxis.dataItems.values[x].sprites[0].tooltipText = categoryAxis.dataItems.values[x].dataContext.definition;
    };
});
```

**Comment by martynasma** [comment]
Yeah, there's an easier way - data placeholders ;)

```JavaScript
image.tooltipText = "{definition}";
```

**Comment by Josh10101010** [comment]
Thanks! I've read through the placeholders/property fields reference and it's really useful!

Now that's working properly, how would I style the image tooltip? I've tried settings the properties on the "image", but it's not applying.

**Comment by martynasma** [comment]
You can configure chart's global tooltip:

```
chart.tooltip.getFillFromObject = false;
chart.tooltip.background.fill = am4core.color("red");
```

Or, create localized tooltip for each image and configure it:

```
image.tooltip = new am4core.Tooltip();
image.tooltip.getFillFromObject = false;
image.tooltip.background.fill = am4core.color("red");
```

More about tooltips:
https://www.amcharts.com/docs/v4/concepts/tooltips/

**Comment by Josh10101010** [comment]
Perfect, thanks!
