### ISSUE TITLE
Treemap: change dynamically bullet's font size

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2869]
I'm trying to get a treemap similar to [this example](https://oec.world/en/visualize/tree_map/hs92/export/prk/all/show/2018/) where the bullet's font size changes dynamically based on the item size. Is there a way to get a similar behavior?

Thank you.

**Comment by martynasma** [comment]
You can create a heat rule to size bullet/labels based on the value. However, the size will be relative to the value, not to actual size of the block it's for.

https://www.amcharts.com/docs/v4/concepts/series/#Heat_maps

**Comment by javier-fjfs** [comment]
Thank you for the info. I've tried to create a rule to change the font size of a bullet but something is wrong because it doesn't work. This is the code I'm using:

```
level1SeriesTemplate.heatRules.push({
  "target": bullet1.label,
  "property": "fontSize",
  "min": 5,
  "max": 40
 });

```
And the complete example [is here](https://jsfiddle.net/1oyj7snw/).

Thank you.

**Comment by martynasma** [comment]
Indeed. Heat rules don't seem to affect Treemap labels :/

We've concocted some other solution using events:
https://jsfiddle.net/ec65mvj2/1/

**Comment by javier-fjfs** [comment]
You guys are awesome!! That's perfect. The only change I made is to change the event to "ready". With the "positionchanged" event some times not all bullets were resized.

**Comment by javier-fjfs** [comment]
Just one additional question. This solution works for one level on the treemap but if I drill down then the bullets of the new level keeps the same size as the parent's bullets. Here you can see [an example](https://jsfiddle.net/wLvrpgfa/1/). If you dill down to level 1, it works perfect. If on that level you select the item with value **4.55554** you can go to level 3. On that level I'd like to have the same behavior, i.e, adjust the size according to the values and items of this new level. I've create a new bullet's event for this level but it doesn't work.

```
bullet2.events.on("ready", function(event){
  let target = event.target;
  if (target.parent) {
    var pw = target.maxWidth;
    var ph = target.maxHeight;

    let label = target.children.getIndex(0)
    var tw = label.measuredWidth;
    var th = label.measuredHeight;

    let k = Math.min(pw / tw, ph / th);

    if (!isNaN(k) && k != Infinity) {
      target.scale = k;
    }
  }
}) 
```

Thank you again for your help.

**Comment by javier-fjfs** [comment]
I answer myself. Changing the event of the new bullet to `positionchanged` is the solution.

Thanks again.
