### ISSUE TITLE
amchart 4 data remove issue in multiple XY axis.

### ISSUE THREAD

**Issue by farzdmhb** [amcharts/amcharts4#2870]
I have a problem with amcharts library.
first of all, I add data to my chart due to examples in amcharts website. for each data set, I add a new y-axis and a new graph, but for every new data, it adds 2, 4, 6, and so on y-axis and legend.
the second one when I use ' series.removeindex()' to remove all data in the chart to re-render the chart all y-axes and other components are still there and it does not reset the chart and just graphs get removed.
the code that i use to remove data is :
   for (;amChart.series.length > 0;) {
       amChart.series.removeIndex(0).dispose();

I would really appreciate if anyone helps me with this.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by farzdmhb** [comment]
actually it is a confidential project so that unfortunately I can not share the code.

**Comment by farzdmhb** [comment]
this is the part I try to implement for the amchart:
var amChart;
$(document).ready(function () {
    am4core.useTheme(am4themes_animated);
    amChart = am4core.create("chartdiv", am4charts.XYChart);
    let dateAxis = amChart.xAxes.push(new am4charts.DateAxis());
    dateAxis.renderer.minGridDistance = 50;
    amChart.colors.step = 2;
    amChart.legend = new am4charts.Legend();
    amChart.cursor = new am4charts.XYCursor();
});

/****************************************/
function chart_dell() {
    for (; amChart.series.length > 0;) {
        amChart.series.removeIndex(0).dispose();
    }
}

/************************************/
function amchart_setChart(data, hello, chartElem) {
    let chartData = [];
    $.each(data, function (key, data_value) {
        let obj = {
            date: new Date(data_value.ts * 1000)
        };
        for (let v in hello) {
            let vu = data_value[hello[v]];
            obj["dataset" + v] = vu;
        }
        chartData.push(obj);
    });
    chartElem.data = chartData;
    let dateAxis = chartElem.xAxes.push(new am4charts.DateAxis());
    dateAxis.renderer.minGridDistance = 50;
    for (let v in hello) {
        createAxisAndSeries(chartElem, "dataset" + v, "dataset" + v, false);
    }
    chartElem.legend = new am4charts.Legend();
    chartElem.cursor = new am4charts.XYCursor();
}

function createAxisAndSeries(chart, field, name, opposite) {
    var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

    var series = chart.series.push(new am4charts.LineSeries());
    series.dataFields.valueY = field;
    series.dataFields.dateX = "date";
    series.strokeWidth = 2;
    series.yAxis = valueAxis;
    series.name = name;
    series.tooltipText = "{name}: [bold]{valueY}[/]";
    series.tensionX = 0.8;

    valueAxis.renderer.line.strokeOpacity = 1;
    valueAxis.renderer.line.strokeWidth = 2;
    valueAxis.renderer.line.stroke = series.stroke;
    valueAxis.renderer.labels.template.fill = series.stroke;
    valueAxis.renderer.opposite = opposite;
    //valueAxis.renderer.grid.template.disabled = true;
}

**Comment by martynasma** [comment]
I'm terribly sorry but I'm going to have to ask you to post this as a live chart on CodePen or jsFiddle or any other service to your liking.

**Comment by farzdmhb** [comment]
https://codepen.io/mokhtasatxyz/pen/WNwMRKL

Also i think it is good to mention that chart.js library is also in use in the project.
Does that make a interference?

**Comment by martynasma** [comment]
Thanks for posting that link. Is it supposed to do anything? I don't get any charts in it, even if I check checboxes.

I don't have any experience in using chart.js, but I doubt that there should be any conflicts. amCharts works in its own scope, and does not rely on globals that can be influenced by other libraries.

**Comment by martynasma** [comment]
Thanks for additional info.

Removing series from the chart, does not automatically remove related axes. If you want to remove Y axis attached to the series you're about to remove, you need to remove it as well:

```
chart.series.getIndex(0).yAxis.dispose();
chart.series.removeIndex(0).dispose();
```

That being said, if your aim is to remove all axes and series, there's a better way:

```
chart.series.clear();
chart.yAxes.clear();
```
