### ISSUE TITLE
how to change wordcloud words ColorSet ? No actual available example for wordcloud

### ISSUE THREAD

**Issue by Leslie23971** [amcharts/amcharts4#2871]
Hi, 

I've been desperately trying to change the ColorSet : I found a lot of different examples for colunms but so far none applied to wordclouds, or at least none of my attemps worked. The chart code is valid, it does build and display the chart, but once I try to incorporate the ColorSet related changes it no longer build the chart, which I understand it to be due to a misuse or bug of dedicated API...Plus in some of the examples online : 
- it was also stated that the chart.list was to be re-assigned before the following invokation _var series = chart.series.push(new am4plugins_wordCloud.WordCloudSeries());_ , but still nothing.
- some were using _series.color.list_, while others used _chart.color.list_

Here is the generic code I used before trying to change the colors used : 
_series.colors = new am4core.ColorSet();
series.colors.passOptions = {};_

Based on the examples I found online and my understanding of the documentation, here is what I tried so far : 

- **Attemp 1** : _does not even build the chart (also tried to replace chart.colors by series.colors)_
_chart.colors.list = ["#522c0f", "#5f3312", "#6d3a15", "#7b4217", "#88491a", "#96501d",
    "#a4581f", "#b15f22", "#bf6625", "#cd6e27", "#d6762e", "#d97f3c",
    "#db8849", "#de9157", "#e19a65"].map(function(color) {
      return new am4core.color(color);});
    series.colors = colorSet;_

- **Attemp 2** :  _builds the chart but does not display nothing except the title
var colors = ['#2776BD', '#00A1D0','#00C195','#7ED321','#A8C600','#C9B600','#E3A600', '#F7941E', '#FC7149'];
     var am4colors = [];
     colors.forEach(function(hex) { am4colors.push(am4core.color(hex)); });
    chart.colors.list = am4colors;_

- **Attemp 3** : _does not even build the chart (also tried to replace chart.colors by series.colors)_
_chart.colors.list = [
      am4core.color("#522c0f"),
      am4core.color("#5f3312"),
      am4core.color("#6d3a15"),
      am4core.color("#7b4217"),
      am4core.color("#88491a"),
      am4core.color("#96501d"),
      am4core.color("#a4581f"),
      am4core.color("#b15f22"),
      am4core.color("#bf6625"),
      am4core.color("#cd6e27"),
      am4core.color("#d6762e"),
      am4core.color("#d97f3c"),
      am4core.color("#db8849"),
      am4core.color("#de9157"),
      am4core.color("#e19a65")
    ];
    series.template.events.once("inited", function(event){
      event.target.fill = chart.colors.getIndex(event.target.dataItem.index);_

**Here is my complete code (and its works) :** 

_function myFunction()
{
  am4core.ready(function() {
    am4core.useTheme(am4themes_animated);

    var chart = am4core.create("chartdiv", am4plugins_wordCloud.WordCloud);
    chart.fontFamily = "Courier New";

    var series = chart.series.push(new am4plugins_wordCloud.WordCloudSeries());

    series.randomness = 0.1;
    series.rotationThreshold = 0.5;

    series.data = [  _explicit content removed for the sake of this post_ ];

    //Configure data
    series.dataFields.word = "tag";
    series.dataFields.value = "weight";

    //Modify ColorSet
    series.colors = new am4core.ColorSet();
    series.colors.passOptions = {};
    
    series.labels.template.tooltipText = "{word}: {value}";
    series.tooltip.fill = am4core.color("#e6ab80");
    series.tooltip.getFillFromObject = false;
    series.tooltip.background.fill = am4core.color("#111111");

    //Hover state
    var hoverState = series.labels.template.states.create("hover");
    hoverState.properties.fill = am4core.color("#f3d8c4");

    //Chart title
    var title = chart.titles.create();
    title.text = "Skills chart";
    title.fontSize = 50;
    title.fontWeight = "800";
    title.fill = am4core.color("#c66a26");
    title.stroke = am4core.color("#a4581f");

    series.events.on("arrangestarted", function(ev) {
      ev.target.baseSprite.preloader.show(0);
    });

    series.events.on("arrangeprogress", function(ev) {
      ev.target.baseSprite.preloader.progress = ev.progress;
    });
  });
}_

I really hope someone will please guide me, as the documentation is lacking precisions+actual example for this specific type of chart, and none of the few online example/forums provides a clear+working answer.

Thanks for your help .

**Comment by martynasma** [comment]
You almost got it. Just need to change colorset list on a series, rather than a chart:

```
series.colors.list = [
  am4core.color("#522c0f"),
  am4core.color("#5f3312"),
  am4core.color("#6d3a15"),
  am4core.color("#7b4217"),
  am4core.color("#88491a"),
  am4core.color("#96501d"),
  am4core.color("#a4581f"),
  am4core.color("#b15f22"),
  am4core.color("#bf6625"),
  am4core.color("#cd6e27"),
  am4core.color("#d6762e"),
  am4core.color("#d97f3c"),
  am4core.color("#db8849"),
  am4core.color("#de9157"),
  am4core.color("#e19a65")
];
```

**Comment by martynasma** [comment]
The following doc section explains more about colors on series:
https://www.amcharts.com/docs/v4/chart-types/wordcloud/#Colors

**Comment by Leslie23971** [comment]
Hi, thank you for your answer.

As stated in my initial post, I had already tried that, but your answer got me looking into it again and try to get rid of this specific folowing line that I had for some reason right after the _series.color.list_ instantiation :
_series.template.events.once("inited", function(event){event.target.fill = chart.colors.getIndex(event.target.dataItem.index);_

So now the following code is working :
_series.colors = new am4core.ColorSet();
series.colors.passOptions = {};_

_series.colors.list = [
    am4core.color("#522c0f"),
    am4core.color("#5f3312"),
    am4core.color("#6d3a15"),
    am4core.color("#7b4217"),
    am4core.color("#88491a"),
    am4core.color("#96501d"),
    am4core.color("#a4581f"),
    am4core.color("#b15f22"),
    am4core.color("#bf6625"),
    am4core.color("#cd6e27"),
    am4core.color("#d6762e"),
    am4core.color("#d97f3c"),
    am4core.color("#db8849"),
    am4core.color("#de9157"),
    am4core.color("#e19a65")
  ];_

But I have another questions : 
I have 51 words in my chart, and when I set the chart with 15 customs colors, it seems that once it runs out of colors it start picking colors from the predefined themes instead of looping up on my customized Colorset. To force it to remain in my theme I had to add in my customized ColorSet as much color as I have words (repeating the set of customized color as many times as needed to reach the 51 count).

Isn't supposed to loop on the ColorSet/Theme ? Isn't _series.colors = new am4core.ColorSet();_ line of code supposed to re-init the list and erase any previous color declaration ? Am I missing any other line of code that would fix that ?

**Comment by Leslie23971** [comment]
Hey thank you for your answer!

As stated in my previous comment, I had actually already tried your solution but at the time it still wouldn't work. Yet your answer got me looking again into my code and realize I had one 2 line of code from the original template I found online for this customization and that wasn't necessary...I guess it was somehow contradicting something in my code cause the chart wouldn't even "build" (if that makes any sense), but anyway thanks for confirming that my code was correct at least for the ColorSet customization :) .

Now it's fixed and I can see the chart, I have another question : 
I have 51 words in my data chart, and 15 colors in my customized Colorset. For some reason, instead of looping back on the colors declared in the series.colors.list, it picks colors from one of the predefined theme. To fix fix this problem, I had to add to my list as much colors as I have words in my data chart.

I thought _series.colors = new am4core.ColorSet();_ was a way to reset the list and remove any default color ? And that the color selector is supposed to loop on the list customized or not ? So what am I missing ?

**Comment by martynasma** [comment]
You might also set `reuse` setting of the `ColorSet` if you want same colors reused when set runs out of colors:

```
series.colors.reuse = true;
```

**Comment by martynasma** [comment]
P.S. the docs were updated accordingly.

**Comment by Leslie23971** [comment]
ok, I will try that, but why would I need to do that, if the behavior with the default ColorSet/themes is to loop on the given set of colors (which btw makes complete sense, the whole purpose behind defining a theme is to "stay" within the define set of colors/police..etc, so I wouldn't expect anything else as behavior) ? Cause basically the only thing I'm doing is customizing in this situation is changing the content of list of colors in which the program pics up a "random" color to be set for each new element of the chart : in other words I don't change (per se) the behavior around this list, so why would I need to add any other property/configuration on it when I'm only touching its content ?

**Comment by Leslie23971** [comment]
Your solution fixed my second issue, so thank you for your answers. I'll keep this thread opened just until I receive your answers to my previous comment for improvement purposes (if relevant), then I'll close it. Thanks.

**Comment by martynasma** [comment]
I'm sorry, I'm not entirely sure what is the "first" issue? Can you re-iterate it again briefly?

I thought the aim was to make words repeat same few colors, which, as I understand, is now achieved.

**Comment by Leslie23971** [comment]
My bad :

issue 1 : change wordcloud ColorSet/theme (which wasn't a real issue per se but due to an additional line of code in my code that was probably contradictory to the rest of the code _so you mainly confirmed I was on the right path_)

issue 2 : looping on the same ColorSet -> fixed with your solution _series.colors.reuse = true;_

So basically all my issues are fixed now, my last "comment/remark/concern" was mainly about the API logic regarding the necessity to add _series.colors.reuse = true;_ to have the code looping on my custom ColorSet while the default behavior (when there is no list customization) is to loop on the default _ColorSet.list_ anyway ??!?

**Comment by martynasma** [comment]
Thanks for the confirmation.

Default behavior is not to loop the colors. Default behavior is to generate unique colors with every iteration. Hence the need for `reuse` setting.

**Comment by Leslie23971** [comment]
ok now I get it - Thanks !

**Comment by milkeddy1** [comment]
@martynasma  Hi I have a similar question, I have 80 words but I would only like to custom the top of six words color, and rest of the words stays the custom same color. Is there any way to do it?

**Comment by tisi1550** [comment]
I have three categories: A, B, and C. I want to use colors c1 for A, c2 for B, and c3 for C. The categories receive new data that gets appended after every few seconds, and I want to maintain the specified colors for each category. How can I implement it ?
