### ISSUE TITLE
Is it possible to have tooltip on chart.cursor.line<Y/X>?

### ISSUE THREAD

**Issue by yenniSuresh** [amcharts/amcharts4#2873]
Hi, I am trying to achieve HTML tooltips on XYCursor line such that I can show all series values for current hovered cursor category. https://codepen.io/yennisuresh/pen/KKzQMXJ 

The final idea is to be able to use adapter so that I can customise content inside tooltip as per series style.

**Comment by martynasma** [comment]
Yes:

```
chart.cursor.lineX.tooltipHTML = '<div><span>i am tooltip</span>';
chart.cursor.lineX.interactionsEnabled = true;
```

**Comment by yenniSuresh** [comment]
@martynasma that work but when am trying to use adapter 
`chart.cursor.lineX.adapter.add('tooltipHTML', function() {
  return '<div><span>i am tooltip</span>';
});`
it is not working.

**Comment by martynasma** [comment]
It doesn't work if you don't set `tooltipHTML` in first place - because it never gets executed.

Just set it to something non-empty:

```
chart.cursor.lineX.tooltipHTML = ' ';
chart.cursor.lineX.interactionsEnabled = true;
chart.cursor.lineX.adapter.add('tooltipHTML', function() { return '<div><span>i am tooltip</span>'; });
```

**Comment by yenniSuresh** [comment]
@martynasma 
`chart.cursor.lineX.adapter.add('tooltipHTML', function(text, sprite) { return '<div><span>i am tooltip</span>'; });` here `sprite` contains no `dataItems`. I mean for example I have bar and line series, how may I get all data points in current hovered cursor category (i.e for my example one from bar and one from line series)? I cant find anything about these in docs. If you think they are documented then please point me to that.

**Comment by yenniSuresh** [comment]
![tooltip_in_v3](https://user-images.githubusercontent.com/61043119/92459269-19729a80-f1e4-11ea-95f8-b26c427a9778.gif)
above is my required output which in done in amcharts 3

**Comment by martynasma** [comment]
In such case I wouldn't put tooltip on cursor line, but rather on series.

https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/
https://www.amcharts.com/docs/v4/tutorials/custom-static-multi-value-tooltip/
https://www.amcharts.com/docs/v4/tutorials/multi-series-shared-tooltip-with-colored-bullets/

**Comment by yenniSuresh** [comment]
I have gone through all above links and got a output but that is not same as what I have attached above.

My current output looks like this:
![current_output](https://user-images.githubusercontent.com/61043119/92463720-d1567680-f1e9-11ea-849b-3a773cd574b6.gif)

In all above links, the tooltip is achieved by enabling tooltip on only last series but that not how it is in expected gif.

**Comment by martynasma** [comment]
Is it about position of the tooltip, which you always want top-aligned?

**Comment by yenniSuresh** [comment]
yes, I have tried solution suggested here https://github.com/amcharts/amcharts4/issues/2800

**Comment by martynasma** [comment]
Something like this should work:

```
series.tooltip.pointerOrientation = "up";
series.tooltip.adapter.add("pixelY", function(y, target) {
  return 20;
});
```

For the tooltip color, please see here:
https://www.amcharts.com/docs/v4/concepts/tooltips/#Color_inheritance

**Comment by yenniSuresh** [comment]
Just tried that but sadly didn't work, attached the output gif below
![pixelYadapter](https://user-images.githubusercontent.com/61043119/92467508-5e4ffe80-f1ef-11ea-9285-b8a0a7851869.gif)

The way it looks in expected output gif, I believe it is achieved through Axis tooltips in amchart3 but I couldn't achieve same in amchart4 using axis tooltips, I have tried, I might have missed something or may be it is not yet supported, only you can confirm that.

Regarding tooltip color, yes, `fill` property is the way to go but I don't have access to column's fill. The solution we are discussing or mentioned in links above involves adding tooltips to series but not columns so I don't have access to `column.fill` which can be different from `series.fill` in case of bar series.

**Comment by martynasma** [comment]
It did work for me. Can you post your current chart on CodePen?

**Comment by yenniSuresh** [comment]
sure, will build and post

**Comment by yenniSuresh** [comment]
@martynasma here it https://codepen.io/yennisuresh/pen/QWNQpoN

**Comment by martynasma** [comment]
Indeed.

In this case, I suppose you could leave your tooltip on cursor line, then use its events to update tooltip contents.

This tutorial is very close to it:
https://www.amcharts.com/docs/v4/tutorials/custom-static-multi-value-tooltip/

**Comment by yenniSuresh** [comment]
Is there any possibility to achieve expected result using axis tooltips?

**Comment by martynasma** [comment]
Yes, I suppose. You can add an adapter on `axis.tooltip.label` to modify its contents.

**Comment by yenniSuresh** [comment]
how can I make category x-axis tooltip balloon float on top?

**Comment by yenniSuresh** [comment]
@martynasma I have got the expected output using cursor tooltip.

How I did: I got current hovered axis index using current cursor position inside tooltipHTML adapter on cursor. Using the axis index on chart series and data, I could populated tooltip content as required. 
Thanks for your help and discussions.
