### ISSUE TITLE
Is there a way to get the pixel height of the grid area of an XYChart?

### ISSUE THREAD

**Issue by frank-fajardo-a142179** [amcharts/amcharts4#2874]
**Question**

Is there a way to programmatically get the height (in pixels) of the grid area of an XYChart? 

![image](https://user-images.githubusercontent.com/35437382/92446851-ca376480-f1f9-11ea-8c64-e1e08fdc9f65.png)

**Environment (if applicable)**

 - amCharts version 4

**Comment by martynasma** [comment]
Yes: `chart.plotContainer.pixelHeight`.

You might need for chart to be fully rendered for it to return proper value, e.g. after chart's `ready` event kicks in.
