### ISSUE TITLE
Changing the scrollbar look

### ISSUE THREAD

**Issue by frank-fajardo-a142179** [amcharts/amcharts4#2875]
**Question**

Is there a way to change the scrollbar's look to be something like this:
- Reduce thickness of the slider bar (gray background)
- Add drop shadows to the start/end grips

![image](https://user-images.githubusercontent.com/35437382/92453234-59487a80-f202-11ea-9aa2-7d37b23f284a.png)

**Environment (if applicable)**

 - amCharts version 4

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v4/tutorials/customizing-chart-scrollbar/

**Comment by frank-fajardo-a142179** [comment]
@martynasma I looked at that but I could not figure out how to change the background (gray bar) to be thinner, and to add the drop shadow on the grip buttons.

**Comment by martynasma** [comment]
You can make the line thinner by decreasing padding:

```
chart.scrollbarX.background.padding(2,2,2,2);
```

Grip button objects are accessible by scrollbar's `startGrip` and `endGrip` properties. Refer to this guide on how to add filters:

https://www.amcharts.com/docs/v4/tutorials/using-filters/
