### ISSUE TITLE
bar chart tooltip colors

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2877]
I have a bar chart that displays values sorted that is working fine. Now I want to change the tooltip colors so I'm adding these lines:

```
series.columns.template.tooltip.getFillFromObject = false;
series.columns.template.tooltip.background.fill = am4core.color("#fff");
series.columns.template.tooltip.label.fill = am4core.color("#000");
```

Now, the tooltip is not working (it is not displayed) and the values displays on the chart are not sorted. Could you please check what I'm not doing correctly? The complete [code is here](https://jsfiddle.net/posg0ak3/).

Thank you.

**Comment by xorspark** [comment]
The error in the browser console hints at what is going on:

```
TypeError: Cannot set property 'getFillFromObject' of undefined
```

`tooltip` is not defined at the column level. It needs to be configured at the series level:

```
series.tooltip.getFillFromObject = false;
series.tooltip.background.fill = am4core.color("#fff");
series.tooltip.label.fill = am4core.color("#000");
```

[Updated fiddle](https://jsfiddle.net/4Lkw5e7r/)

**Comment by javier-fjfs** [comment]
Thank you so much for your response.
