### ISSUE TITLE
Responsive Bug On Multiple Resizes

### ISSUE THREAD

**Issue by ACVis** [amcharts/amcharts4#2878]
**Bug description**
With responsive features enabled, chart loads correctly, then responds correctly to window resizing. Then if we put the window back to a larger size and then again sizing it smaller, it renders differently compared to the first time the window was resized. 

This video illustrates the problem: https://streamable.com/7s0w3a
Here's the codepen: https://codepen.io/ACvis/pen/dyMdjaW?editors=0010
In codepen I seem to be able to reproduce the effect in full page mode, but not debug mode.

**Comment by martynasma** [comment]
It looks like some mix of layout-related settings in legend is not being reset properly. There's quite a fuzzy logic going on, when you want to organize your legend horizontally or vertically.

Best way would be to toggle `position` value in your responsive rules, and not mess with individual item container settings, or layout types.

Just for the reference here's what's going on on change of `position`:

https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/Legend.ts#L844-L866

Maybe you can refactor your code using position instead.

If you can't, let me know, we'll see if I can figure some setting combination out.

**Comment by ACVis** [comment]
I removed all the other responsive rules and tried using position instead,  I cut the Legend on down to this:

```javascript
          if (target instanceof am4charts.Legend) {
            var state = target.states.create(stateId);
            console.log('target LEGEND', target);
            // state.properties.paddingTop = 0;
            // state.properties.paddingRight = 0;
            //state.properties.paddingBottom = 0;
            // state.properties.paddingLeft = 0;
            // state.properties.marginLeft = 0;
            state.properties.fontSize = 8;

            // state.properties.maxHeight = 60;
            // state.properties.maxWidth = undefined;
            state.properties.position = 'bottom';
            // state.properties.align = 'left';
            // state.properties.align = 'left';
            //state.properties.valign = 'bottom';
            // state.properties.contentValign = 'bottom';
            // state.properties.layout = 'horizontal';
            return state;
          }
```
And the problem still persists. I can get the legend to initially position correctly at cell phone size, but then when expanded (like changing phone to horizontal) and then bringing it back to the original cell phone size, the legend does not position the same. I've tried positioning it a couple different ways and making it really minimal. I looked at the source you linked and I'm still not sure how to resolve this. As far as I can tell, I'm using the responsive rules in the intended way. I hope I'm not missing something obvious.

**Comment by martynasma** [comment]
I found this to work properly:

```
      if (target instanceof am4charts.Legend) {
        var state = target.states.create(stateId);
        state.properties.width = am4core.percent(100);
        state.properties.maxColumns = undefined;
        return state;
      }
```

**Comment by ACVis** [comment]
Thank you, I will test this out.
