### ISSUE TITLE
Forcing start and end points on date axis?

### ISSUE THREAD

**Issue by syfgkjasdkn** [amcharts/amcharts4#2879]
**Question**

👋 

I have a chart where I'd like to show the full axis (e.g. 01/01/2020 -- 01/02/2020) even if data only includes a subset of the date range (e.g. 05/01/2020 -- 17/01/2020). Is this possible with amcharts without changing the dataset?

If not, what are possible approaches to showing the full date axis with amcharts?

So far I see two, are there any downsides to any of them that I'm possibly missing:

- fill the intervals with missing data with empty values (e.g. `{x: '01/01/2020'}`, `{x: '02/01/2020'}`, etc)
- only fill the first and last missing interval with an empty value (is there any downside to this compared to the first option?)

Also both options seem to be showing a tooltip on the missing intervals, is there a way to disable that and only make it show on intervals with data?

**Comment by martynasma** [comment]
Yes, it's possible. You can set `min` and `max` on your `DateAxis` to starting and ending timestamp.

```
dateAxis.min = new Date(2020, 0, 5).getTime();
dateAxis.max = new Date(2020, 0, 17).getTime();
```

**Comment by syfgkjasdkn** [comment]
@martynasma Thank you!

**Comment by syfgkjasdkn** [comment]
@martynasma seems like it doesn't work, date axis is not changing.
