### ISSUE TITLE
Misplaced tooltip

### ISSUE THREAD

**Issue by syfgkjasdkn** [amcharts/amcharts4#2880]
**Bug description**

👋

Sometimes the tooltips get shown in a wrong place:

<img width="527" alt="Screenshot 2020-09-09 at 14 21 27" src="https://user-images.githubusercontent.com/43219386/92592141-ce21c000-f2a7-11ea-81df-6a663d3c46e4.png">

My cursor was where I drew the dot.

**Additional context**

The chart is rendered in a https://github.com/haltu/muuri grid item.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by syfgkjasdkn** [comment]
@martynasma hi! It might be not that easy to reproduce. I wonder if you could point me to the amcharts module that renders the tootips? I think the area of the chart that amcharts thinks is visible is not in sync with the actual size of the chart.

**Comment by syfgkjasdkn** [comment]
@martynasma if I turn off the initial scale animation in muuri, the problem seems to go away. I'll prepare a repro.

**Comment by syfgkjasdkn** [comment]
@martynasma sorry to bother you, but I haven't been able to find the way to invalidate size in the docs myself. Could you please point me in the right direction?
