### ISSUE TITLE
Missing linechart

### ISSUE THREAD

**Issue by syfgkjasdkn** [amcharts/amcharts4#2881]
**Bug description**

A linechart is rendered without the line:

<img width="508" alt="Screenshot 2020-09-09 at 14 24 48" src="https://user-images.githubusercontent.com/43219386/92592496-53a57000-f2a8-11ea-8e88-1ad3a132c2e1.png">

The tooltips are in place, though.

**Environment (if applicable)**

**Additional context**

The chart is rendered in a [muuri](https://github.com/haltu/muuri) grid item.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by syfgkjasdkn** [comment]
@martynasma sure! Here's a codepen: https://codepen.io/syfgkjasdkn/pen/bGpLXVO

**Comment by syfgkjasdkn** [comment]
Ping

**Comment by syfgkjasdkn** [comment]
Sorry, but the issue hasn't been addressed and it still happens.
