### ISSUE TITLE
Using series grouping, background is not synced with series

### ISSUE THREAD

**Issue by sdapkus** [amcharts/amcharts4#2882]
**Bug description**

When using series grouping, and passing only one parameter: `[{timeUnit: "week", count: 1}]` it looks like that background is not synced with series. First date on x-axes is not at a same place where series starts

https://codepen.io/sdapkus/pen/YzqeoNW

**Environment (if applicable)**

- Browser: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

![image](https://user-images.githubusercontent.com/58326108/92592331-14771f00-f2a8-11ea-824b-73c00a362d59.png)

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis

**Comment by sdapkus** [comment]
I've tried adding `dateAxis.renderer.labels.template.location = 0.0001;` from a link, but it does not change anything.

And this issue is not really like in a docs. In a docs it says it will not draw some labels because they do not fit - that is okay. But in my case, data labels fits in a screen, but they a drawn in a wrong places.
![amchart1](https://user-images.githubusercontent.com/58326108/92596528-a1bd7200-f2ae-11ea-84c1-d6a5bb77285d.png)
![amchart2](https://user-images.githubusercontent.com/58326108/92596530-a1bd7200-f2ae-11ea-9251-b1ac4a24ada5.png)
