### ISSUE TITLE
Data Grouping has to be done based on switching to weekly,monthly and daily

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#2884]
Hi 

I have been working on amcharts4, in our Angular 6+ project in that single chart has three options to switch among daily, weekly and monthly. For example when we set monthly that chart has to group data into monthly and present chart and same accordingly for others.  

Working fine if we give normal string:
dateAxis.groupData = true;
dateAxis.groupInterval = { timeUnit: 'week' , count: 1};

and not working when we give it as a variable:
dateAxis.groupData = true;
dateAxis.groupInterval = { timeUnit: this.periodInterval, count: 1};

and i have defined this.periodInterval = 'week'/ 'month'/ 'day' wherever it needed  then the corresponding method is implemented when we switch

I'm getting this error:
error TS2322: Type '{ timeUnit: string; count: number; }' is not assignable to type '{ count: number; timeUnit: ""; }'.
  Types of property 'timeUnit' are incompatible.
    Type 'string' is not assignable to type '""'.

How can we implement groupInterval with passing a variable?

Thank you...

**Comment by martynasma** [comment]
I suppose you need to set the type of your `periodInterval`, e.g.:

```
public periodInterval: am4core.TimeUnit;
```
