### ISSUE TITLE
China GeoJson data file has incorrect State/Province information

### ISSUE THREAD

**Issue by g-roblin** [amcharts/amcharts4#2886]
I noted that at least two of the GeoJSON polygons in the chinaLow.json (and chinaHigh.json) have incorrect properties with relation to the mapping to the ISO-3166-2 province/state subdivision codes.

[1] Snippet from the GeoJSON:  `"properties":{"name":"Jiangsu","id":"CN-JX","TYPE":"Province","CNTRY":"China"}`

The ISO-3166-2 Code for **Jiangsu** is **CN-JS** not CN-JX as documented in the GeoJSON.

[2] Snippet from the GeoJSON: `"properties":{"name":"Jiangxi","id":"CN-36","TYPE":"Province","CNTRY":"China"}`

The ISO-3166-2 Code for **Jiangxi** is **CN-JX** not CN-36 as documented in the GeoJSON.

Also, please note that CN-36 is the previous code for Jiangxi that was changed in 2017 to CN-JX.  CN-36 is the only legacy numeric state/province code in the China GeoJSON file.  All the other records are represented as the new (post 2017) alpha codes.  for example CN-JX, CN-JS, CN-JL

Information or confirmation of the above ISO-3166-2 mapping errors can be found at the standards source:  https://www.iso.org/obp/ui/#iso:code:3166:CN

or via https://en.wikipedia.org/wiki/ISO_3166-2:CN

Can you please confirm the above and help rectify the GeoJSON, please?

**Comment by martynasma** [comment]
Thank you for bringing this to our attention. The maps will be fixed in the next release of the `amcharts4-geodata` package.

CDNs might get updated sooner.

Make sure you subscribe to the notifications for [amcharts4-geodata](https://github.com/amcharts/amcharts4-geodata) to get notified when new update is available.
