### ISSUE TITLE
'fill' adapter for dateAxis labels does not get applied on wide date axis

### ISSUE THREAD

**Issue by frank-fajardo-a142179** [amcharts/amcharts4#2887]
**Bug description**

When a chart has a strict min/max date axis, and there is a 'fill' adapter for the labels, the fill adapter seems to stop working.

Here is an example where it fails: https://codepen.io/frankfajardo/pen/dyMZVxv 
The date axis has a strict range from Jan 1 to Feb 28.
I expected Jan 3 to be shown in red when the date axis shows a label for it. But it doesn't.

However, if I change the date axis range to only Jan 1 to Jan 14, the fill adapter starts working.
Or if I leave the date axis range as is but set `dateAxis.renderer.minGridDistance` to 20, it starts working also.

**Environment (if applicable)**

 - amCharts version 4

**Comment by xorspark** [comment]
You're better off adding an adapter to the `text` property instead and adding a shortcode color formatter to the text, since that adapter will consistently fire on each label. There is a value axis example of this in [the adapter documentation](https://www.amcharts.com/docs/v4/concepts/adapters/#Chaining_multiple_adapters), but a date axis implementation is similar enough:

```dateAxis.renderer.labels.template.adapter.add('text', (text, target) => { 
  if (target.dataItem && target.dataItem.date) {
    if (target.dataItem.date.getTime() === today) {
      return '[red]' + text;
    }
  }
  return '[gray]' + text;
});
```

[Updated codepen](https://codepen.io/team/amcharts/pen/c2e2ce2e70448e7db454fcff57ed5452?editors=0010)

**Comment by frank-fajardo-a142179** [comment]
Hi @xorspark , I understand that the codepen works with your changes. However, I'm getting this warning on VSCode:
```
Property 'date' does not exist on type 'AxisDataItem'. Did you mean 'dates'?ts(2551)
DataItem.d.ts(198, 14): 'dates' is declared here.
```
![image](https://user-images.githubusercontent.com/35437382/92861187-854f4000-f43c-11ea-8e53-af8faba21904.png)

Does this mean I'm using incorrect typings for amCharts? We are currently on v4.9.37. Or has it changed between v4.9 and v4.10?

**Comment by martynasma** [comment]
You're using correct typings, just specify type for TS, e.g.

```TypeScript
var dataItem = <am4charts.DateAxisDataItem>(target.dataItem);
if (dataItem && dataItem.date) {
....
```

**Comment by frank-fajardo-a142179** [comment]
Thanks @martynasma and @xorspark
