### ISSUE TITLE
How to fix partial visibility of bullets on edge in xy chart

### ISSUE THREAD

**Issue by yenniSuresh** [amcharts/amcharts4#2888]
![Peek 2020-09-10 20-10](https://user-images.githubusercontent.com/61043119/92747709-1d4c1b80-f3a2-11ea-88b3-5263e5ce7fcf.gif)

In above gif bullets are half cut/hidden on left side, same thing happens when bullet is at right side

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v4/concepts/bullets/#Disabling_bullet_clipping
