### ISSUE TITLE
How can I align tooltip on cursor in rotated xy chart from left to right

### ISSUE THREAD

**Issue by yenniSuresh** [amcharts/amcharts4#2889]
![cursor-to-right](https://user-images.githubusercontent.com/61043119/92748981-4d47ee80-f3a3-11ea-8994-1a5c4302f4c5.gif)

I tried using tooltipY, align, horizontal/vertialCentera and adpater with pixelY but none worked.

**Comment by yenniSuresh** [comment]
@martynasma can you help? I am kinda out of idea to fix this issue

**Comment by yenniSuresh** [comment]
@martynasma I think `cursor.line.tooltipX = '100%'` should work (but not working) as `cursor.line.tooltipX = 1300` works for me but I cant keep static number as width will be different depending upon window size.

**Comment by martynasma** [comment]
I have a better solution for you: putting tooltip on series and overriding `tooltipX` with an adapter:

```JavaScript
series.tooltipText = "{categoryY}: {valueX}";
series.adapter.add("tooltipX", function(x, target) {
  return chart.plotContainer.pixelWidth;
})
```

Here's a working example:
https://codepen.io/team/amcharts/pen/321133a7aad6204653ba405e5a7d2a43?editors=0010

**Comment by yenniSuresh** [comment]
Hi @martynasma 

I have went with this approach 

> chart.cursor.lineY.tooltip.adapter.add('pixel_x', () =>
>             chart.rightAxesContainer.getPixelX(percent(101))
>  );

The out of this is pretty close to what I want but its not perfect. I think it will be perfect if [this](https://github.com/amcharts/amcharts4/issues/2889#issuecomment-690991508) works

And I still think its not right way to have a single series alone take responsibility to show data for all possible series in a chart like in your example in above comment. I have already tried the approach you have mentioned and I faced few design and output issues.

An issue was: Imagine its a bar chart, if I make a single series to show data for all series in its tooltip then I could not come up with solution to give column fill specific color to each data inside the tooltip. when I say column fill specific, I mean color inside a column/bar but not color of the series it belongs to.

I am actually trying to create a generic vue component wrapper which would take care of all cases.

**Comment by martynasma** [comment]
> An issue was: Imagine its a bar chart, if I make a single series to show data for all series in its tooltip then I could not come up with solution to give column fill specific color to each data inside the tooltip. when I say column fill specific, I mean color inside a column/bar but not color of the series it belongs to.

I'm not sure I understand this. Why can't you give a color in your tooltip?

**Comment by yenniSuresh** [comment]
@martynasma 

You can take giphy in here https://github.com/amcharts/amcharts4/issues/2889#issue-698080460 as reference how tooltip will look.

Tooltip itself will not have color (by default background will be white), it will have colourful tags representing multiple data points belonging to different series for a hovered category.

**Comment by martynasma** [comment]
Again, I'm not sure I understand what seems to be the problem? This thread is about position of the tooltip. If that's resolved, I suggest to close the issue, and open a new one to discuss other topics.

**Comment by yenniSuresh** [comment]
Sure @martynasma , in that case can you confirm if there are any plan to fix [this](https://github.com/amcharts/amcharts4/issues/2889#issuecomment-690991508) in future because this will sync well with my current implementation and also as per docs `tooltipX` is suppose to support percentage value.

**Comment by martynasma** [comment]
I'm afraid we won't be changing positioning of the tooltip using absolute values. Sorry.
