### ISSUE TITLE
Bug when zooming on a XY Series: All the series disappears

### ISSUE THREAD

**Issue by EmaGht** [amcharts/amcharts4#2890]
**Bug description**
When zooming on a XYSeries with high data precision, apparently all series disappers

CodePen:
https://codepen.io/EmaGht/pen/RwaMBGa?editors=0010

Just try to zoom on any part of the series

i *THINK* it might depend on the fact the highest number is like *1.000.000.000.000 the smallest number but i'm not sure

Edit:
What's more, it's like the chart actually understands what is going on and where the series should be because if i try to zoom here: 
![image](https://user-images.githubusercontent.com/12494403/92754744-6fce0d80-f38b-11ea-8060-9798d9404b9a.png)

the chart correctly places the tooltip where the invisible series are:
![image](https://user-images.githubusercontent.com/12494403/92754840-870cfb00-f38b-11ea-96cb-7ffc3d53ac67.png)

**Comment by martynasma** [comment]
The issue is not with data precision but rather order. Date-based data needs to be in ascending order, whereas yours is in descending, hence the zooming anomaly.

**Comment by EmaGht** [comment]
Oh. Okay. Neat.
I updated the Codepen, now works without a problem.
Love the quick answer! Thanks!
