### ISSUE TITLE
Date axis is not formatting first label

### ISSUE THREAD

**Issue by sagarkale94** [amcharts/amcharts4#2891]
I have created simple column with date axis. Applied date formatter for the same but for first column label the format has been displayed different compare to rest column labels which are perfectly formatted. Sharing codepen for the same https://codepen.io/sagarkale94/pen/xxVqgwm?editors=0010

**Comment by martynasma** [comment]
Please refer to solution in #2713

**Comment by sagarkale94** [comment]
Thanks, got working now..!!
