### ISSUE TITLE
Setting `min` and `strictMinMax` clips computed chart line. Any way to fix that?

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#2893]
Hey,

This is a great library and thanks for all prompt response on github issues. I have a question, I've noticed when setting `min` to `0` and `strictMinMax` to `true`, without setting a max value, sometimes the chart line/series is clipped at the top.

Is there any way to prevent that? Preferably by not manually `valueAxis.extraMax = 0.2; `

[CodePen example](https://codepen.io/raresmardare/pen/abNYXvV)

This CodePen was sent in another ticket reported on website but for the bullet being clipped. Now that is being solved by explicitly marking the bullet as not clipped, but for the line?

Thank you!

**Comment by martynasma** [comment]
Well, setting `strictMinMax = true` works that way. If either `min` or `max` is not set explicitly, they will be set using whatever actual min or max value there is in data.

This should work around it:

```
series.mainContainer.mask = undefined;
series.maskBullets = false;
```

Though, if you have srolling/zooming on your chart, some series elements might protrude.

**Comment by teodosii** [comment]
Thank you very much, that solved the issue!
