### ISSUE TITLE
how to change the valueAxis.opposite after the chart has been loaded

### ISSUE THREAD

**Issue by mokhtasatxyz** [amcharts/amcharts4#2894]
Hello
I have made a multiple value axes chart with flexible number of axes like the one in demos:
[ https://www.amcharts.com/demos/multiple-value-axes/](url)
I need to change the OPPOSITE option on preferred value axes by pressing a button or check box to change the position of axis from right to left or vice versa after the chart has been loaded.
Thanks

**Comment by martynasma** [comment]
It's as easy as setting `renderer.opposite` on that axis object:

```
chart.yAxes.getIndex(1).renderer.opposite = false;
```

This will move the second axis to left.
