### ISSUE TITLE
how to mix value yaxes in multiple value axes after the chart has been loaded

### ISSUE THREAD

**Issue by mokhtasatxyz** [amcharts/amcharts4#2895]
Hello
I have made a multiple value axes chart with flexible number of axes like the one in demos:
[ https://www.amcharts.com/demos/multiple-value-axes/](url)

I need to mix value axes with the same types of data together which means assigning two or more graphs (series) to one values axes.
Is there any feature for this in amcharts?
Thanks

**Comment by martynasma** [comment]
Yes, you can assign multiple series to the same axis. Please refer this documentation:
https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Multiple_axes
