### ISSUE TITLE
Dynamic custom label data on map polygon 

### ISSUE THREAD

**Issue by adamalexandru4** [amcharts/amcharts4#2896]
Hello everyone,
I'm trying to set custom label data for each 5 seconds over Romanian counties. I would like to show inside county polygon the following data text, which will be updated at 5 seconds as I mentioned:
"{name} 
   TEXT_UPDATED"

It will be great if the render can be optimized without any drawback.

Could everyone help me with a piece of code?

**Comment by martynasma** [comment]
What are you struggling with: putting the labels on states, or updating them?

**Comment by adamalexandru4** [comment]
Updating them

**Comment by martynasma** [comment]
If the value of the label is coming from data, then it should be as easy as setting new data, or updating existing data and calling `invalidateData()` on your label series.
