### ISSUE TITLE
Problem with the column width changing

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#290]
https://codepen.io/dmsmaxim/pen/vzGjPK

In this example after 3s I'm trying to change the column width by adding 1% to it.
The result is not what you expect:
![image](https://user-images.githubusercontent.com/15041200/44662788-75ac5c80-aa17-11e8-9810-3238e35c3100.png)

**Comment by zeroin** [comment]
The solution I would suggest here would be to invalidate series after you change width:
series.invalidate();
https://codepen.io/team/amcharts/pen/QVMOzp

**Comment by martynasma** [comment]
Looks like @zeroin solution works. Closing this, but feel free to post any follow up if you have questions.
