### ISSUE TITLE
Line chart doesn't break on missing data point

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#2900]
I have created a line chart and want it to break on a missing data point (as well as an empty data point). The latter is working, but when a data point is missing, the line still connects.

I have a created a CodePen demonstrating the issue: [https://codepen.io/jbate/pen/RwayoGE](https://codepen.io/jbate/pen/RwayoGE)

This could certainly be user error on my part ;) but I have tried following the [documentation](https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Line_series_with_gaps) to no avail.

In this case I have added `series.connect = false` and the gap appears to be at least 10% greater than the granularity of data.

Am I doing something wrong?

**Comment by martynasma** [comment]
The automatic gaps work only on `DateAxis`. We should explicitly mention that in the docs. Making a note to do so.

As for your setup (2 x `ValueAxis), the only way to insert a gap is to insert a missing data point.

It can even be a an empty object `{}`.

**Comment by jbate** [comment]
Thanks for getting back so quickly @martynasma! I think an additional note to the documentation would be great.

In this case, I'll pad out my data with empty objects where I need to enforce a break.
