### ISSUE TITLE
Resize chart

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2902]
I have added a navigation bar to a bar chart that is working fine. The problem is that if I go to a second level and then go back to the initial level, the width of the chart is now smaller than the original size. Is it possible to keep always the 100% width?

Here you have the code I'm using: https://jsfiddle.net/hL0gjk6a/

Thank you.

**Comment by martynasma** [comment]
The following should do the trick:

```
categoryAxis.ghostLabel.disabled = true;
```

**Comment by javier-fjfs** [comment]
Yes! Thank you!!
