### ISSUE TITLE
Heatmap performance issues

### ISSUE THREAD

**Issue by ne140** [amcharts/amcharts4#2904]
We are trying to render a heatmap with around 100 values on the x axis (Days) and 48 values on the y axis (Time of Day)- i.e. 4,800 coloured blocks on the chart.

We have achieved this - however the memory and processor usage on the client browser is very high, too high for us to reasonably expect our users to wait for.

We know that it is not an issue with data delivery from server to client, because we can render a simple line chart with the same data fast.

Is there a way to optimise the rendering performance on heatmaps with this number of objects, or should we give up and use a different package?

**Comment by martynasma** [comment]
I'm afraid there's little that can be done to speed up 4.8k columns. Sorry.

**Comment by ne140** [comment]
Ok thanks, we will use a D3 implementation instead.

**Comment by martynasma** [comment]
OK, then. I'm gonna go ahead in close this.
