### ISSUE TITLE
Loading External Data Protected By OAuth 2.0 Bearer Authorization

### ISSUE THREAD

**Issue by Staggen** [amcharts/amcharts4#2905]
**Question**

Hello,

I am trying to load "external" data from my **.NET Core 3.1 backend** to a **React 16.13.1 frontend**, which is implementing a **AmCharts v4 (4.10.2) XY chart**. My backend is using an **OAuth 2.0 authentication scheme with Bearer authorization** for API requests. **I know for a fact that my backend is working properly** as I can send a GET request via a JavaScript Fetch and I hit my endpoint, and get the expected response. When I however try to hit the same endpoint via the integrated DataSource from AmCharts, I can't get my request authorized. Even when I **include my Bearer authorization header** and **enabling withCredentials**, I keep getting a **401 Unauthorized** response.

Below you will find an example of something that works as intended. This example also works without the `"Content-Type": "text/csv"` header, the only required header is the `"Authorization": "Bearer . . ."`

```js
async function getStockData(){
    let accessToken = await authService.getAccessToken()
    let response = await fetch("api/stocks/getstockintraday1min/tsla", {
        headers: {
            "Content-Type": "text/csv",
            "Authorization": `Bearer ${accessToken}`
        }
    })
    if(response.ok){
        return await response.text() // Works great, fetches my data and returns it as expected
    }
}
```
Now for my attempts to get this same data from the same endpoint with AmCharts DataSource object:
```js
// Get access token
let accessToken = await authService.getAccessToken()
console.log("Access token: " + accessToken) // Verify that the token is set correctly

// Create chart
let chart = am4core.create("chartdiv", am4charts.XYChart)
chart.padding(2, 2, 2, 2)
chart.dataSource.url = "api/stocks/getstockintraday1min/tsla"
chart.dataSource.requestOptions.requestHeaders = [{
    "Accept" : "*/*",
    "Content-Type": "text/csv",
    "Authorization": `Bearer ${accessToken}`
}]
chart.dataSource.requestOptions.responseType = "text"
chart.dataSource.requestOptions.withCredentials = true
chart.dataSource.parser = new am4core.CSVParser()
chart.dataSource.parser.options.dateFields = ["col0"]
chart.dataSource.parser.options.numberFields = ["col1", "col2", "col3", "col4", "col5"]
chart.dataSource.parser.options.reverse = true
chart.dataSource.showPreloader = true
```
I have tried doing `.withCredentials = false` as well as true. I have tried just the `"Authorization": "Bearer . . ."` header. I have tried adding the `"Content-Type": "text/csv"` and `"Accept": "*/*"` headers. I tried to set the `.responseType = "text"`. So far, nothing has worked as I just keep getting the same 401 Unauthorized response.

Other things I have tried for good measure (but that failed as one would expect) include:
- Launching the project in Chrome and Edge instead of FireFox
- Making sure I was on the latest AmCharts version (I already was).
- Making sure I was on the latest React version (I already was).

Just to make sure the other parts of this worked fine I set up an unauthorized endpoint and tried to get the data from that, and everything loaded perfectly into my chart. I can however not deploy my project with unauthorized API endpoints, so I really need to figure out how to do this properly.

Thanks in advance for any help or suggestions helping me figure out what I am doing wrong here.

**Comment by martynasma** [comment]
I think the next step would be to set up a working JS prototype as well as one with amCharts dataSource. Then compare actual HTTP request headers in browser's network console. Maybe some header item is missing from the amCharts-based setup.

**Comment by Staggen** [comment]
You're right, when I send the request via the JavaScript Fetch method, I have the Authorization header present, but when I let the DataSource do the data-fetching, the Authorization header is missing completely?!

Fetch request: https://i.imgur.com/JrLtxPX.png
AmCharts DataSource request: https://i.imgur.com/XEoUlS9.png

Err... any idea what I can try to do to fix that?

**Comment by martynasma** [comment]
OK, my bad for not noticing it right away. `requestHeaders` is not an object, but rather an array of objects:

```TypeScript
chart.dataSource.requestOptions.requestHeaders = [
  { key: "Accept", value: "*/*" },
  { key: "Content-Type", value: "text/csv" },
  { key: "Authorization", value: `Bearer ${accessToken}` }
];
```

Seems we don't have anything about `requestOptions` in our [external data doc](https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/) which might be a contributing factor to the confusion.

Making a note to add it to docs.

**Comment by Staggen** [comment]
Not sure how I missed it, but when one looks at the DataSource object in the docs it does actually specify the requestOptions parameter with an example of key + value. I know I had looked at the DataSource object docs earlier, but it didn't click in my head then for some reason.

It might be a good idea to add an example to the external data docs as well like you said, but I should have picked up on it elsewhere -.-

Thanks for helping out :)
