### ISSUE TITLE
Single tooltip for line series chart

### ISSUE THREAD

**Issue by gaurav30-hkr** [amcharts/amcharts4#2906]
**Question**
Single tooltip for line series chart

**Environment (if applicable)**
Angular 9

**Additional context**

chart.Data = [
{id: "B31083EB0ED34", Date_1: "01/08/2020", Data_1: "12", temp_1: 10, tempHigh_1: 20},
{id: "B31083EB0ED34", Date_1: "02/08/2020", Data_1: "14", temp_1: 8, tempHigh_1: 15},
{id: "B31083EB0ED34", Date_1: "03/08/2020", Data_1: "16", temp_1: 15, tempHigh_1: 30},
{id: "B31083EB0ED34", Date_1: "04/08/2020", Data_1: "18", temp_1: 25, tempHigh_1: 35},
{id: "B31083EB0ED34", Date_1: "05/08/2020", Data_1: "18", temp_1: 30, tempHigh_1: 35},
{id: "B31083EB0ED34", Date_1: "06/08/2020", Data_1: "21", temp_1: 40, tempHigh_1: 50},
{id: "B31083EB0ED34", Date_1: "07/08/2020", Data_1: "2", temp_1: 5, tempHigh_1: 8},
{id: "90471F78C4774", Date_2: "01/08/2020", Data_2: "0", temp_2: 5, tempHigh_2: 8},
{id: "90471F78C4774", Date_2: "02/08/2020", Data_2: "24", temp_2: 5, tempHigh_2: 8},
{id: "90471F78C4774", Date_2: "03/08/2020", Data_2: "6", temp_2: 5, tempHigh_2: 8},
 {id: "90471F78C4774", Date_2: "04/08/2020", Data_2: "8", temp_2: 5, tempHigh_2: 8},
 {id: "90471F78C4774", Date_2: "05/08/2020", Data_2: "4", temp_2: 5, tempHigh_2: 8},
 {id: "90471F78C4774", Date_2: "06/08/2020", Data_2: "8", temp_2: 5, tempHigh_2: 8},
 {id: "90471F78C4774", Date_2: "07/08/2020", Data_2: "6", temp_2: 5, tempHigh_2: 8},
 {id: "22DFB11D37C64", Date_3: "01/08/2020", Data_3: "12", temp_3: 5, tempHigh_3: 8},
 {id: "22DFB11D37C64", Date_3: "02/08/2020", Data_3: "4", temp_3: 5, tempHigh_3: 8},
 {id: "22DFB11D37C64", Date_3: "03/08/2020", Data_3: "6", temp_3: 5, tempHigh_3: 8},
 {id: "22DFB11D37C64", Date_3: "04/08/2020", Data_3: "8", temp_3: 5, tempHigh_3: 8},
 {id: "22DFB11D37C64", Date_3: "05/08/2020", Data_3: "4", temp_3: 5, tempHigh_3: 8},
 {id: "22DFB11D37C64", Date_3: "06/08/2020", Data_3: "8", temp_3: 5, tempHigh_3: 8},
 {id: "22DFB11D37C64", Date_3: "07/08/2020", Data_3: "10", temp_3: 5, tempHigh_3: 8},
 {id: "C1D599ACD3D84", Date_4: "01/08/2020", Data_4: "12", temp_4: 5, tempHigh_4: 8},
 {id: "C1D599ACD3D84", Date_4: "02/08/2020", Data_4: "4", temp_4: 5, tempHigh_4: 8},
 {id: "C1D599ACD3D84", Date_4: "03/08/2020", Data_4: "6", temp_4: 5, tempHigh_4: 8},
 {id: "C1D599ACD3D84", Date_4: "04/08/2020", Data_4: "8", temp_4: 5, tempHigh_4: 8},
 {id: "C1D599ACD3D84", Date_4: "05/08/2020", Data_4: "4", temp_4: 5, tempHigh_4: 8},
 {id: "C1D599ACD3D84", Date_4: "06/08/2020", Data_4: "8", temp_4: 5, tempHigh_4: 8},
 {id: "C1D599ACD3D84", Date_4: "07/08/2020", Data_4: "16", temp_4: 5, tempHigh_4: 8}
 ].
One week data for specified dates
passing data individually for specific data in createAxisAndSeries  function

createAxisAndSeries(field, time, name ) { 
series.dataFields.dateX = time; //time : Date_1/2/3/4
series.dataFields.valueY = field; // field : Data_1/2/3/4
}

I have to create a single tooltip to display multiple data in it. 
using series.tooltipHTML .
Whenever I am passing data in 
** <p>`+name+`: <strong>{valueY.value}</strong></p>"  **
previou value does not persists.

Tooltip display format : 

Data_1 : Value       temp_1    tempHigh_1
Data_2 : Value       temp_2     tempHigh_2
Data_3 : Value       temp_3     tempHigh_3
Data_4 : Value       temp_4     tempHigh_4

**Comment by martynasma** [comment]
You'll need to consolidate your data items into single ones. It won't work like that.

E.g. there's a single data object for date "01/08/2020" with all four values: tempHigh_1, tempHigh_2, tempHigh_3, tempHigh_4.
