### ISSUE TITLE
Horizontal Column Labels - Render labels outside of column

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2908]
Is there a straight forward to render the column label outside of the column (yellow highlight on the image)?

It's easy on a vertical chart, but I'm struggling on the horizontal with positive/negative values.

![image](https://user-images.githubusercontent.com/66729900/93235029-f19bad80-f774-11ea-8246-3dc470829931.png)

https://codepen.io/Josh519/pen/WNwKwKe

**Comment by xorspark** [comment]
You can create an adapter on the label's `horizontalCenter` property and shift it based on the column value.

```
valueLabel.adapter.add("horizontalCenter", function(horizontalCenter, target) {
  if (target.dataItem.valueX < 0) {
    return "right";
  }
  return "left";
});
```

[Demo](https://codepen.io/team/amcharts/pen/92b1ebd649a9eef5975fdc1a34bbe9ee?editors=0010)

**Comment by Josh10101010** [comment]
```
valueLabel.adapter.add("horizontalCenter", function(horizontalCenter, target) {
  if (target.dataItem.valueX < 0) {
    return "left";
  }
  return "right";
})
```
This is working for the positive values, but not the negative

![image](https://user-images.githubusercontent.com/66729900/93235239-2a3b8700-f775-11ea-8818-18a0420851b9.png)

**Comment by xorspark** [comment]
My bad, I didn't notice you wanted them at the bottom of their respective columns.

Use a `LabelBullet` instead and set the `locationX` to 1. You'll also need an adapter to space out the label from the bottom, if desired.

```
var valueLabel = series.bullets.push(new am4charts.LabelBullet());
valueLabel.label.text = "{value}";
// ...
valueLabel.locationX = 1;
valueLabel.label.adapter.add("horizontalCenter", function(align, target) {
  if (target.dataItem.valueX < 0) {
    return "left";
  }
  return "right";
}); 
valueLabel.label.adapter.add("dx", function(dx, target) {
  if (target.dataItem.valueX < 0) {
    return 10;
  }
  return -10;
});
```

[Updated codepen](https://codepen.io/team/amcharts/pen/92b1ebd649a9eef5975fdc1a34bbe9ee?editors=0010)

**Comment by Josh10101010** [comment]
That's perfect, thanks for the help!

Out of interest does the below not have a locationX or locationY property?
```series.columns.template.createChild(am4core.Label)```

**Comment by martynasma** [comment]
`locationX` and `locationY` are properties of a `Bullet`. Label does not have them.
