### ISSUE TITLE
Horizontally stacked axes - render axes title opposite

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2909]
Based on the codepen example, how would you render the axis titles at the top of the chart since there are multiple value axes?

https://codepen.io/Josh519/pen/yLOqVoy

**Comment by Josh10101010** [comment]
I've just managed to do it using 
```
chart.bottomAxesContainer.toBack();
```

Is that the best way?

**Comment by martynasma** [comment]
I wouldn't mess with the chart built-in container layout. The following will achieve the same result:

```JavaScript
chart.topAxesContainer.layout = "horizontal";
chart.topAxesContainer.reverseOrder = true;
valueAxis1.renderer.opposite = true;
valueAxis2.renderer.opposite = true;
valueAxis3.renderer.opposite = true;
```
