### ISSUE TITLE
Is there anyway to resize length, or positioning point of LineSeries?

### ISSUE THREAD

**Issue by darkhader** [amcharts/amcharts4#2910]
Im trying find the way to to resize length of my lineChart between 2 point, 
I have try series.segments.each and series.children.each but it get the whole of segment not individual point

**Comment by martynasma** [comment]
I'm not entirely sure what you mean by "increase length of line chart". Can you explain n greater detail what you're trying to achieve?

**Comment by darkhader** [comment]
i mean the line, LineSeries actually

**Comment by martynasma** [comment]
Do you mean the thickness of the line itself?

```
series.strokeWidth = 5;
```

**Comment by darkhader** [comment]
no it's the length, seem like the length equal the distance between 2 axis

**Comment by martynasma** [comment]
I must admit I'm not sure what you mean. Do you want to zoom in the chart? Or you want to make series start right on the vertical axis, without any padding?

**Comment by darkhader** [comment]
oh, yeah I mean serries without any padding, with a gaps, I want to make its size(or length) smaller between start and endpoint

**Comment by martynasma** [comment]
Thanks for the confirmation.

You may find these useful:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends
