### ISSUE TITLE
【help】The problem of overlapping of picture and text and truncation by chart

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#2911]
Hi, I'm trying to add some pictures to the series, but sometimes the images overlap and the graph is truncated. Excuse me, is there any good way to solve this problem? English is not easy to use Google translation.

![1a35c512-009c-44f7-9072-e8e45af857b3](https://user-images.githubusercontent.com/42232973/93302235-3afb0400-f82c-11ea-8678-7d01acd4a149.jpg)
![ad6783b3-5f34-40d8-bc98-d9cb4cc80315](https://user-images.githubusercontent.com/42232973/93302247-40f0e500-f82c-11ea-9409-b9504a83cd06.jpg)
![5b590223-015d-4427-918a-92cab91f6486](https://user-images.githubusercontent.com/42232973/93302305-57973c00-f82c-11ea-970f-6b40609639fd.jpg)

**Comment by martynasma** [comment]
Please read the solution in #2888

**Comment by fu1996** [comment]
@martynasma Thank you, there is a problem of overlapping icons and text. I know that there are icon overlap nemesis, but the effect is not the same as what I want. I want the effect of high and low display. Not stacking. Thank you

**Comment by martynasma** [comment]
> Thank you, the problem is that in the first picture, the text inside is overlapped and occluded, and some of the occlusions of the picture are displayed high and low.

I'm not sure what you mean. I don't see any text in icons. Or icons overlapping with text.

**Comment by fu1996** [comment]
> > 谢谢您，问题是在第一张图片中，内部的文本被重叠和遮挡，并且该图片的某些遮挡显示为高和低。
> 
> 我不确定你是什么意思。我在图标中看不到任何文字。或与文本重叠的图标。
In the first picture, where the coordinate axis is 24-25, one has 3 icons, two are stacked and displayed, and one is blocked. And the words "老大18岁" and "老大21岁" are overlapped because of the distance
![image](https://user-images.githubusercontent.com/42232973/93424683-1580ff80-f8eb-11ea-85e1-07b4de672d98.png)

**Comment by martynasma** [comment]
OK, thanks. Not sure what to suggest, though.

Maybe apply `rotation` to those labels, so that they are positioned diagonally?
