### ISSUE TITLE
every time fillOpacity changes Legend gets shrunk

### ISSUE THREAD

**Issue by EmaGht** [amcharts/amcharts4#2912]
**Bug description**

I've taken this example:
https://www.amcharts.com/demos/highlighting-line-chart-series-on-legend-hover/

and I've added very few things: 
-a fillOpacity on the selected series 
-a longer name for the series

This is the result:
https://codepen.io/EmaGht/pen/MWyBLNe?editors=0110

if you hover on the series (both in the legend and on the chart) the legend gets shrunk more and more every over event. Is there something I'm missing? :(

**Comment by EmaGht** [comment]
Hi, do you have an ETA available on this?
I'm good with anything... it's just to know, more or less, when i can expect it to be fixed

Thanks

**Comment by martynasma** [comment]
Sorry for the delay.

Unfortunately, we won't be able to fix this at this time. Not without risking of breaking a lot of other stuff.

There's a workaround for you, though. It's in the modified CodePen:

https://codepen.io/team/amcharts/pen/XWKKYdm

Hope the code makes sense.

**Comment by EmaGht** [comment]
It does.

Basically the fillSprite of each line segment is not created when the fillOpacity is 0, causing a bad resize.

Workaround is gucci, i'm cool with that 👍 

Thanks!
