### ISSUE TITLE
Images in valueAxis title with a horizontally stacked axes chart

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2913]
Would it be possible to add images below each value axis title using this chart [demo](https://codepen.io/pen/?&editable=true=https%3A%2F%2Fwww.amcharts.com%2Fdemos%2Fhorizontally-stacked-axes%2F)?

I achieved it with the following code, drawing on the this [demo](https://www.amcharts.com/demos/images-as-categories/), but it's adding an image for each bullet.

I'd like to be able to add the image to the axis title container and set the layout to vertical.
```
chart.xAxes.each(function (axis) {
  axis.fontSize = 12;
  axis.title.fontSize = 14;
  axis.title.fontWeight = 700;
  axis.title.dy = -30;

  var image = new am4core.Image();
  image.horizontalCenter = "middle";
  image.verticalCenter = "middle";
  image.contentAlign = "center";
  image.width = 45;
  image.height = 46;
  image.dy = 50;
  image.href = "https://www.amcharts.com/wp-content/uploads/flags/united-states.svg";

  axis.dataItems.template.bullet = image;
  axis.marginBottom = 55;

});
```

**Comment by martynasma** [comment]
Maybe using axis range bullets is the solution?

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_bullets

**Comment by Josh10101010** [comment]
Thanks that's working for me, however the image and label are on top of each other. Is it possible to change them from "absolute" positioning to a "block" layout? 

```
chart.xAxes.each(function (axis) {
	axis.min = -100;
	axis.max = 100;
	axis.strictMinMax = true;

	var range = axis.axisRanges.create();
	range.value = 0;
	range.label.text = "test";;

	var image = new am4core.Image();
	image.horizontalCenter = "middle";
	image.verticalCenter = "bottom";
	image.width = 45;
	image.height = 46;
	image.href = "myimage.png";

	range.bullet = image;
});
```

**Comment by martynasma** [comment]
No, I'm afraid.

We do have this experimental plugin, though:
https://www.amcharts.com/docs/v4/tutorials/plugin-overlap-buster/

Might be a solution.
