### ISSUE TITLE
how to update data in a series map

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2914]
I'm trying to update data on a MapPolygonSeries but each time I have new data, the map is not updated even though the series has the updated data. I'm using these lines:

```
polygonSeries.include = includedCountries;
polygonSeries.data = JSON.parse(JSON.stringify(extractedData));
```

where includedCountries and extractedData are the objects where data is updated. I have tried to use `chart.validateData()`, `polygonSeries.invalidate()`, `polygonSeries.validateData()`, ... but the map us not updated. How can I tell the map and/or series that new data has to be updated on the map?

Thank you.

**Comment by martynasma** [comment]
Updating `polygonSeries.data` should be enough. Here's an example:
https://codepen.io/team/amcharts/pen/29e39bd6ccd82b1076ac7cb6bb73db46

If you could provide a CodePen of your map not updating properly, I'd be able to take a look.

**Comment by javier-fjfs** [comment]
I think the problem is with include and exclude properties of series. It seems that if I assign a new array of countries for example to exclude, the map keeps the previous excluded countries. Is there a way to reset these properties? One option is to create again the series object but the question is whether it is possible to reset the excluded/included countries of an existing series object on the map. I have checked that the property (e.g. excluded) has the right array of countries but the map is not reflecting that.

This is the code I have:

```
this.polygonSeries_world.name = "world";
this.polygonSeries_world.useGeodata = true;
this.polygonSeries_world.exclude = excludedCountries;
this.polygonSeries_world.mapPolygons.template.nonScalingStroke = true;
this.polygonSeries_world.hiddenInLegend = true;
```

Each time I assign a new array of excluded countries, the map keeps what I had previously.

Thank you.

**Comment by martynasma** [comment]
So you are not updating series data but rather just changing `exclude`?

In this case you should probably call `series.invalidateData()` afterwards.

**Comment by javier-fjfs** [comment]
Yes, it's for the series 'rest of the world' that has no data. I'm using this code but it is still not working.

```
this.polygonSeries_world.name = "world";
this.polygonSeries_world.useGeodata = true;
this.polygonSeries_world.exclude = excludedCountries;
this.polygonSeries_world.invalidateData();
this.polygonSeries_world.mapPolygons.template.nonScalingStroke = true;
this.polygonSeries_world.hiddenInLegend = true;
```

**Comment by martynasma** [comment]
I think we'll need a full working example so that we see your actual setup. Can you post that on CodePen?

**Comment by tongwl** [comment]
@javier-fjfs 
I also met this issue, did you find how to update exclude or include in a map series?
