### ISSUE TITLE
Show tooltip on 0 value series

### ISSUE THREAD

**Issue by cumthyb** [amcharts/amcharts4#2915]
I am working on Column and Bar chart , and I have to show tooltip on series ,but when the value of a serie is 0 ,the tooltip does not appears when the mouse hovers on the xAxies.

I also try it with Wijmo chart, it works as expected, so the question is **how to show tooltip on 0 value series** , is there any api can help ?

Live code : [https://codepen.io/cumthyb/pen/gOrdLLv?editable=true%3Dhttps%3A%2F%2Fwww.amcharts.com%2Fdemos%2Fsimple-column-chart%2F](https://codepen.io/cumthyb/pen/gOrdLLv?editable=true%3Dhttps%3A%2F%2Fwww.amcharts.com%2Fdemos%2Fsimple-column-chart%2F)

Thank you!

**Comment by martynasma** [comment]
You can just add a chart cursor and set `tooltipText` directly on series:

```
series.tooltipText = "{categoryX}: [bold]{valueY}[/]";
chart.cursor = new am4charts.XYCursor();
```

**Comment by cumthyb** [comment]
Many thanks , it works!

**Comment by RajasekharReddy82** [comment]
Facing same issue in amchart5, How can set this on amchart5
