### ISSUE TITLE
1. The text added via axisRange cannot be exported when the icon is exported. Is there any way to solve it. 2. Is there any good way to get the complete PNG image of the chart after all elements of the chart are rendered?

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#2916]
1. The text added via axisRange cannot be exported when the icon is exported. Is there any way to solve it. 
2. Is there any good way to get the complete PNG image of the chart after all elements of the chart are rendered?
![cd81afde-dbc3-4a37-b36b-41b7e2a453f3](https://user-images.githubusercontent.com/42232973/93432730-82e75d00-f8f8-11ea-9b17-d2bba13d0b18.jpg)
first is the chart
![511ccfc7-39a2-426f-8152-d7585ce2d978](https://user-images.githubusercontent.com/42232973/93432791-95fa2d00-f8f8-11ea-892c-78c1d403cd28.jpg)
second is the picture

**Comment by martynasma** [comment]
For the first question: are we talking about export to PNG or PDF?

Second question: you can use chart's `ready` event for that.

**Comment by fu1996** [comment]
> For the first question: are we talking about export to PNG or PDF?
> 
> Second question: you can use chart's `ready` event for that.

Haha, I used the second one correctly, the first one is in PNG format, thank you

**Comment by fu1996** [comment]
There is another question. There is a Bullet PNG picture button on the X axis. Can I use this picture to block the X axis?

**Comment by martynasma** [comment]
If you are exporting into PNG, then all of the text elements in chart should export as well.

If you could post your chart on CodePen, I could take a look at it.

I suggest posting any other non-related follow up questions as separate issues.
