### ISSUE TITLE
Legend - use default for some items and custom images for others

### ISSUE THREAD

**Issue by A143447** [amcharts/amcharts4#2917]
**Question**

I have a graph with 6 categories. I would like the first four categories to use the in-built default amCharts legend values, for the other two categories, I would like to use my own icons. Is this possible? 

From my understanding to add icons, I need to dispose of the children of the legend container and then I need to add them back in. From the example in the docs (https://www.amcharts.com/docs/v4/concepts/legend/#Individual_custom_markers), it appears that all the children need to be of the same type. Is this correct?

Currently I'm trying to get this solution working with the codePen that is supplied with the above docs link. 

Any assistance would be greatly appreciated

**Comment by martynasma** [comment]
> it appears that all the children need to be of the same type. Is this correct?

Well, not necessarily.

In this case, you would probably need to watch `ready` (or similar) event on legend/chart and then manipulate each actual entry in `legend.itemContainers` as you see fit.

I don't have a working example like this, though.
