### ISSUE TITLE
Manually hide ChordDiagram items with custom legend

### ISSUE THREAD

**Issue by rinatio** [amcharts/amcharts4#2918]
Hello,

We're trying to make a custom legend for ChordDiagram similar to one provided in this example: https://codepen.io/team/amcharts/pen/GRgadvV. That example however doesn't toggle items visibility, is there any other example on how to do that?

We were able to attach a `hit` event listener:
```
    const legend = new am4charts.Legend();
    legend.itemContainers.template.events.on('hit', function(ev) {
      const name = ev.target.dataItem.dataContext.name;
      
        chart.dataItems.each(row => {
          row.hidden = true;
        });
    });
```

It only hides a link though, not the full item.

**Environment (if applicable)**

"@amcharts/amcharts4": "4.9.28"

**Comment by martynasma** [comment]
You can hide particular node like this:

```
chart.nodes.getKey("B").hide();
```
