### ISSUE TITLE
Offsets in gradients are not working 

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#292]
Hi,

 i have created a gradient and trying to change the offsets dynamically, it's not working.
below is the snippet:

const gradient = new am4core.LinearGradient();
    gradient.addColor(am4core.color('#FF0000'));
    gradient.addColor(am4core.color('#f0f035'));
    gradient.addColor(am4core.color('#5cd85c'));
    const gradientElement = gradient.element.node;
    _.forEach(gradientElement.children, (element, idx) => {
        element.setAttribute('offset', idx === 0 ? '0.1' : idx === 1 ? '0.4' : '0.9');
      });

The offsets are changing from 0.1, 0.4, 0.9 to 0, 0.5, 1 always
How to fix that

**Comment by Varshamathukumalli** [comment]
Yeah, that helped. Thanks for the solution.
One more issue is how to change x1,x2,y1,y2 other than the default values

**Comment by martynasma** [comment]
@Varshamathukumalli Can you please clarify what does x1, x2, etc. mean in the context of gradients?

Or is it about something else? In which case you could probably create a separate issue/ticket in order to avoid long intermixing issues.

Thanks!

**Comment by Varshamathukumalli** [comment]
@martynasma ,

Below is how the horizontal linear gradient looks,
<linearGradient id="gradient" x1="0%" x2="100%" y1="50%" y2="50%">
   <stop stop-color="#ff0000" stop-opacity="1" offset="0.1"></stop>
   <stop stop-color="#f0f035" stop-opacity="1" offset="0.5"></stop>
   <stop stop-color="#5cd85c" stop-opacity="1" offset="0.8"></stop>
</linearGradient>

In the above linear gradient, i want to provide my custom start and end points from x1=0 to 20  and x2=100 to 90. and changing y1 and y2 in case of vertical linear gradient
I tried updating using setAttribute. But that didn't work
How to acheive the above

**Comment by Varshamathukumalli** [comment]
@martynasma ,

Is there any update for the above issue

**Comment by martynasma** [comment]
Not yet, sorry.

Will get back to you as soon as possible.

Thanks for hanging in.

**Comment by martynasma** [comment]
@Varshamathukumalli I'm afraid it's currently not possible to set custom x/y coordinates for the linear gradient in amCharts 4. Sorry.

**Comment by Varshamathukumalli** [comment]
@martynasma ,

As its an important requirement for us can you tell us, is there any ETA for the same.

**Comment by martynasma** [comment]
At this point I can't provide an ETA, I'm afraid.

I'm assigning this to the dev team, but since it's not a critical feature, I can't promise it will be picked up soon.

**Comment by martynasma** [comment]
This is feature is not going to be implemented. Sorry. Closing.
