### ISSUE TITLE
Setting the background of a column (container)

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#2921]
Might be an easy one, but it's eluding me, based on this [demo](https://codepen.io/pen/?&editable=true=https%3A%2F%2Fwww.amcharts.com%2Fdemos%2Fhorizontally-stacked-axes%2F) How would I achieve the (orange) stroke below, for all columns?

![image](https://user-images.githubusercontent.com/66729900/93616970-505b6400-f9cd-11ea-847b-0accbf1670d8.png)

**Comment by zeroin** [comment]
I would add axisRange for each category:

**Comment by Josh10101010** [comment]
Related to this, is there an event for hovering over the axisRange? [Demo](https://codepen.io/Josh519/pen/xxVQpQm) I'd like to show the darkened background on hover, so I could highlight all 3 charts for an individual.

**Comment by martynasma** [comment]
Yes, but you need to set your events on a grid element:

```JavaScript
range.grid.events.on("over", function (ev) {
  console.log("test")
})
```

**Comment by Josh10101010** [comment]
That allows me to trigger it, but the event only covers the top 1px edge of the "range"

![RangeGrid1](https://user-images.githubusercontent.com/66729900/93987114-10a2cc80-fd7f-11ea-8fc3-013dbf344e59.gif)

[codePen](https://codepen.io/Josh519/pen/xxVQpQm)

**Comment by martynasma** [comment]
OK, my bad. You should set your events on `axisFill` not the `grid`.

Furthermore, interactivity on axisFill needs to be explicitly enabled:

```JavaScript
range.axisFill.interactionsEnabled = true;
range.axisFill.events.on("over", function (ev) {
  range.axisFill.fillOpacity = 0.3;
})
```

**Comment by Josh10101010** [comment]
Thanks! That's precisely what I was looking for.
 
![RangeGrid2](https://user-images.githubusercontent.com/66729900/93989410-ca9b3800-fd81-11ea-8943-6205317119bd.gif)

**Comment by Josh10101010** [comment]
Is there an easy way to loop through the names to create a range for each one?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
