### ISSUE TITLE
Heat leyend height

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2922]
I'm trying the adjust the height of a heat legend using this line:

`heatLegend.markerContainer.height = 15;`

The problem is that I cannot reduce the height below 20 px. Is it possible to set a height below that number?

Thank you.

**Comment by martynasma** [comment]
It might be restricted by `minHeight` setting, so you should probably set both:

```
heatLegend.markerContainer.height = 15;
heatLegend.markerContainer.MinHeight = 15;
```

**Comment by javier-fjfs** [comment]
That did not work. I've just realized that I have to add a third line with the font size. Without that line, it does not matter what value I set on the height and minheight.

`heatLegend.valueAxis.renderer.labels.template.fontSize = 5;`

**Comment by martynasma** [comment]
Hm, OK. All set now?

**Comment by andreafonso** [comment]
Hello, I'm having this problem as well. 

Wanted to make the `am4maps.HeatLegend` a thiner line but just can't figure out how to do it.

Used [this](https://codepen.io/team/amcharts/pen/eYJZVEV) codepen as example, and tried with: 

```
heatLegend.markerContainer.height = 10;
heatLegend.markerContainer.minHeight = 10;
```

And even playing with `heatLegend.valueAxis.renderer.labels.template.fontSize` did not work. It keeps locked at 20px.

Is there a work around?

**Comment by samcarton** [comment]
I'm a bit late to the party, but in the interest of posting an actual solution for this:
The defaults for **both** `heatLegend.markers` and `heatLegend.markerContainer` sets `minWidth` and `minHeight` to 20 when constructing the heat legend.

So if you want to force it to be smaller, you need to set both:
```
heatLegend.markers.template.minHeight= 5;
heatLegend.markerContainer.minHeight = 5;
```

or for vertical orientation:
```
heatLegend.markers.template.minWidth = 5;
heatLegend.markerContainer.minWidth = 5;
```

**Comment by lireboy** [comment]
> I'm a bit late to the party, but in the interest of posting an actual solution for this: The defaults for **both** `heatLegend.markers` and `heatLegend.markerContainer` sets `minWidth` and `minHeight` to 20 when constructing the heat legend.
> 
> So if you want to force it to be smaller, you need to set both:
> 
> ```
> heatLegend.markers.template.minHeight= 5;
> heatLegend.markerContainer.minHeight = 5;
> ```
> 
> or for vertical orientation:
> 
> ```
> heatLegend.markers.template.minWidth = 5;
> heatLegend.markerContainer.minWidth = 5;
> ```

Ur completely right.
I had to do both 
heatLegend.markers.template.minHeight= 5;
heatLegend.markerContainer.minHeight = 5;

Its absolutely not intuituve
since u just want to do heatLegend.markerContainer.height = 5;
