### ISSUE TITLE
Step Line Series render issues on small screen or after resizing window

### ISSUE THREAD

**Issue by rafaeldefazio** [amcharts/amcharts4#2923]
I need to plot covid-19 data on a time series chart. I started using Column Chart, but there was overhead in rendering because each column was a .svg. Then, in the documentation, I saw a tip that we could use filled Step Line Series graphics to create the illusion of columns. On large screens, such as laptop computers, everything works fine. However, on mobile, the graph completely loses its format (started to present a peak shape). Is there any way around this? Thank you

**Environment**

```js
@amcharts/amcharts4": "^4.10.2"
@amcharts/amcharts4-geodata": "^4.1.17"

@angular/common": "^9.1.12"
@angular/compiler": "~9.0.7"
@angular/core": "~9.0.7"

@angular/platform-browser": "~9.0.7"
@angular/platform-browser-dynamic": "~9.0.7"
@angular/pwa": "^0.6.8"
@angular/router": "~9.0.7"
@angular/service-worker": "~9.0.7"
@angular-devkit/build-angular": "~0.900.7"
@angular/cli": "^9.1.12"
@angular/compiler-cli": "~9.0.7"
@types/node": "^12.12.61"
```

**Screenshots**

Desktop:
![Desktop](https://i.imgur.com/bu4snZO.png)

Smartphone:
![Smartphone](https://i.imgur.com/0c1CBhm.png)

This also happens when I resize the window under around 1840px (in a 1080p laptop):

![Resize](https://i.imgur.com/cBk6R24.png)

**In-production example**: https://picovid.com.br/painel/SP/Catanduva, in section "Histórico de casos por dia"

**Comment by martynasma** [comment]
I can see the issue in your website, but I can't seem to be able to reproduce it independently.

E.g.:
https://jsfiddle.net/amcharts/suwbot9m/

Would you be able to post your standalone chart somewhere so that we can see uncompiled code?

**Comment by rafaeldefazio** [comment]
I tried to post a standalone chart, but Stackblitz couldn't compile (infinite loading).

But here's the source code: https://github.com/rafaeldefazio/dashboard-covid/blob/master/src/app/pages/city/city.component.ts#L370-L477 and https://github.com/rafaeldefazio/dashboard-covid/blob/master/src/app/pages/city/city.component.ts#L640-L702

With following options:

```
am4core.options.onlyShowOnViewport = true;
am4core.options.deferredDelay = 500;
am4core.options.queue = true;
am4core.options.minPolylineStep = 5;
```

**Comment by martynasma** [comment]
I'm sorry, debugging custom apps is a bit out of scope. I'm going to ask you to provide a simple repro case we can use for testing.

I hope you find this request reasonable. Thanks!
