### ISSUE TITLE
Display the corresponding tooltip according to the visible series

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#2924]
codepen
[https://codepen.io/team/amcharts/pen/KKwrmyM](url)

When I click to hide series2, the corresponding tooltip should only be the tooltip of series1 and series3.

**Comment by martynasma** [comment]
You may modify the adapter code to check against series `visible` property:

```
  series.adapter.add("tooltipText", function(ev) {
    var text = "[bold]{dateX}[/]\n"
    chart.series.each(function(item) {
      if(item.visible) {
        text += "[" + item.stroke.hex + "]●[/] " + item.name + ": {" + item.dataFields.valueY + "}\n";
      }
    });
    return text;
  });
```

**Comment by fu1996** [comment]
> You may modify the adapter code to check against series `visible` property:
> 
> ```
>   series.adapter.add("tooltipText", function(ev) {
>     var text = "[bold]{dateX}[/]\n"
>     chart.series.each(function(item) {
>       if(item.visible) {
>         text += "[" + item.stroke.hex + "]●[/] " + item.name + ": {" + item.dataFields.valueY + "}\n";
>       }
>     });
>     return text;
>   });
> ```

Thank you for your hard work, this method is very useful for me.
