### ISSUE TITLE
Why does the value of the “parent” get the sum of the values of the “children” and not the value of itself in the TreeMap?

### ISSUE THREAD

**Issue by yuvalr55** [amcharts/amcharts4#2925]
**I could not understand why when a "parent" has value, he still does not receive his own value and still receives as the value the sum of the values of "his children".**

**Although it is recorded in the doc that when a "parent" has a value he does not inherit the values of his children**

`let chart = am4core.create("chartdiv",am4charts.TreeMap)
`
**InputJson:**
`const jsonData =[{
  "name": "First",
  "value": 2390, //Parent value
  "children": [
    { "name": "A1", "value": 0.4 }, //children value
    { "name": "A2", "value": 0.4 }, //children value
    { "name": "A3", "value": 0.1917355900000002 } //children value
  ]
}, {
  "name": "Second",
  "value": 5933, //Parent value
  "children": [
    { "name": "B1", "value": 0.2332 }, //children value
    { "name": "B2", "value": 0.323 }, //children value
    { "name": "B3", "value": 0.122332 } //children value
  ]
}]`

**I need the parent's value column to be a red value object and not a yellow object.(As in InputJson):**
![Screenshot_2](https://user-images.githubusercontent.com/59453585/93774854-5ef28700-fc2a-11ea-9b97-68748b924f7e.png)

**Comment by martynasma** [comment]
This is how TreeMap works. There's no way to override sum of child values by setting parent's value to some arbitrary number.

Sorry.

**Comment by yuvalr55** [comment]
Thank you very much!
