### ISSUE TITLE
Experiencing differing date tool tips based on the number of data points.

### ISSUE THREAD

**Issue by JamesDolphin** [amcharts/amcharts4#2926]
I am using an multi series line chart and experiencing some odd date formatting on the y axis tool tip.

The image below is showing the date formatting when the data set contains roughly 1000 elements.

![image](https://user-images.githubusercontent.com/29121533/93840260-2b1f6c00-fcd3-11ea-83ab-18124e0dd8fd.png)

The image below is showing the date formatting when the data set contains roughly 5000 elements

![image](https://user-images.githubusercontent.com/29121533/93840310-52763900-fcd3-11ea-938d-52c870f25c45.png)

When using a large data set the time formatting in the x axis tool tip is changing from hh:mm to mm:ss ms

I am currently forcing the formatting like this.

    dateAxis.dateFormats.setKey("hour", "HH:mm");
    dateAxis.periodChangeDateFormats.setKey("hour", "MMMM dt");

How can I ensure that the date formatting remains as HH:mm ?

**Comment by martynasma** [comment]
The axis tooltip uses format suitable for your data granularity. So if your granularity is milliseconds you get `MM:ss AAA`.

There are two ways to work with this:

1) Explicitly setting granularity of your data:

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Manually_specifying_data_granularity

2) Forcing specific format for `DateAxis` tooltip:

https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/#Tooltip_value_format
