### ISSUE TITLE
How can I append a dollar to the particular value in multiple line single tooltip box

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#2928]
Hi

I have been working on amcharts4, in our Angular 6+ project in that we are using single tooltip box for displaying multiple values which consists of 3 values and 3 volumes. For 3 values we need to append a dollar sign. I used a adapter over here to display in single tooltip.

Current code i'm dealing with
series.adapter.add("tooltipText", function(ev) {
                    var text = "[bold]{dateX.formatDate(\"MMM d, yyyy\")}[/]\n"
                    chart.series.each(function(item) {
                        text += "[" + item.stroke + "]●[/] "+ item.name + ": {" + item.dataFields.valueY+ "}\n";
                    });
                    return text;
                });

if I use the below logic i'm able to get the dollar sign but 
![Screenshot from 2020-09-22 11-44-25](https://user-images.githubusercontent.com/71019344/93849173-1d64e900-fcc9-11ea-9756-aa6040f4520e.png)
 for all the 3 values it is showing same number
series.adapter.add("tooltipText", function(ev) {
                    var text = "[bold]{dateX.formatDate(\"MMM d, yyyy\")}[/]\n"
                    chart.series.each(function(item) {
                        if(item.name.indexOf('Volume')>-1)
                        {
                            text += "[" + item.stroke + "]●[/] " + item.name + ": {" + item.dataFields.valueY + "}\n";
                        }else {
                            text += "[" + item.stroke + "]●[/] " + item.name + ": {" + 'valueY.formatNumber("$.")' + "}\n";
                        }
                    });
                    return text;
                });

How can we append Dollar sign to particular in tooltip?

Thanks in advance...

**Comment by martynasma** [comment]
Why not add dollar sign to the text itself, not to the `formatNumber` inline function?

```
if(item.name.indexOf('Volume')>-1)
{
  text += "[" + item.stroke + "]●[/] " + item.name + ": {" + item.dataFields.valueY + "}\n";
}else {
  text += "[" + item.stroke + "]●[/] " + item.name + ": ${" + item.dataFields.valueY + "}\n";
}
```

**Comment by meghanaNanuvala** [comment]
Thank you Martynasma
