### ISSUE TITLE
Legend Label reverse appearance in Prod build mode.

### ISSUE THREAD

**Issue by sajidAzeem** [amcharts/amcharts4#2929]
Hello all,
when I run my pie chart in production mode(prod build mode), then my chart's legend labels, value label and text label are appearing in reverse order(value label first and then text(category) label). anybody have solution to make it work fine in production mode?

Developer Mode.
![developer mode](https://user-images.githubusercontent.com/70995105/93850666-2a370c00-fccc-11ea-9c0f-d320739396d2.png)

Production Mode.
![production mode](https://user-images.githubusercontent.com/70995105/93850714-4cc92500-fccc-11ea-8e77-9ad177eddabe.png)

**Comment by xorspark** [comment]
Make sure you disable the build optimizer for your production build as mentioned [here](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/). If that doesn't help, please post a minimal stackblitz/codesandbox of your setup.

**Comment by sajidAzeem** [comment]
> Make sure you disable the build optimizer for your production build as mentioned [here](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/). If that doesn't help, please post a minimal stackblitz/codesandbox of your setup.

Thank You for Your reply. It didn't get worked for me.here's my [code](https://stackblitz.com/edit/angular-ivy-ihiunk?file=src/app/app.component.ts)

**Comment by sajidAzeem** [comment]
> Make sure you disable the build optimizer for your production build as mentioned [here](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/). If that doesn't help, please post a minimal stackblitz/codesandbox of your setup.

Thank you for response. I did use of it but my problem still remains. here is my [code]( https://codesandbox.io/s/pie-chart-8dj7k?file=/src/app/app.component.ts)

**Comment by sajidAzeem** [comment]
> Make sure you disable the build optimizer for your production build as mentioned [here](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/). If that doesn't help, please post a minimal stackblitz/codesandbox of your setup.

when I write my code in codesandbox It's showing error like below.
```
TypeError
Object prototype may only be an Object or null: undefined
```
here is my setup [code](https://codesandbox.io/s/prod-cookies-mc6jb?file=/src/app/app.component.ts)

**Comment by xorspark** [comment]
Not sure what's wrong with codesandbox so I ran your code locally using angular-cli.

`ng build --prod --build-optimizer=false` generates output with the legend label and values in the correct order.

If you're using `ng serve --prod`, you also need to set `buildOptimizer: false` in angular.json under the production configuration:

```
          "configurations": {
            "production": {
              // ...
              "optimization": true,
              // ...
              "buildOptimizer": false,
```

**Comment by sajidAzeem** [comment]
Thank You It's working fine now.

**Comment by sajidAzeem** [comment]
> Not sure what's wrong with codesandbox so I ran your code locally using angular-cli.
> 
> `ng build --prod --build-optimizer=false` generates output with the legend label and values in the correct order.
> 
> If you're using `ng serve --prod`, you also need to set `buildOptimizer: false` in angular.json under the production configuration:
> 
> ```
>           "configurations": {
>             "production": {
>               // ...
>               "optimization": true,
>               // ...
>               "buildOptimizer": false,
> ```

Thank you It's working fine now. But may I know why was that happening  when we had `buildOptimizer:true`

**Comment by xorspark** [comment]
The build optimizer is buggy. This has been discussed here: https://github.com/amcharts/amcharts4/issues/1146#issuecomment-526386236
