### ISSUE TITLE
ColumnSeries based on DateAxis

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#293]
Hello !

Is there an example of Columnseries based on DateAxis ?

**Comment by martynasma** [comment]
Yes.

https://codepen.io/team/amcharts/pen/eLZXKW

**Comment by ptorrent** [comment]
Thanks,

How to change the size of the column relative to a desired interval?

 For example, I would like my column to have a size of 6 hours.

https://codepen.io/ptorrent/pen/GXqjwZ

Is it possible ?

**Comment by ptorrent** [comment]
Ok I did it but there is something strange with the render : 

https://codepen.io/ptorrent/pen/GXqjwZ

Am I doing something wrong ?

**Comment by martynasma** [comment]
Alright. Glad you worked it out ;)
