### ISSUE TITLE
Add a picture on the x axis, how to block the position of the corresponding x axis.

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#2930]
Because the code is not easy to obtain, only the corresponding photos can be provided. Please help me see how to achieve it.
Current effect:
A button image is placed on the X axis, but not above the X axis.
Realization effect:
Like the button in this case, block the corresponding X-axis area
[https://www.amcharts.com/demos/line-chart-with-range-slider/](https://www.amcharts.com/demos/line-chart-with-range-slider/)

![01340ae4-93be-4954-972a-d87d27252ade](https://user-images.githubusercontent.com/42232973/93855845-c3751b00-fcea-11ea-9227-0428b5c31a7b.jpg)
![f770db7f-368a-4739-a4b9-54d0dfd0f7fb](https://user-images.githubusercontent.com/42232973/93855847-c40db180-fcea-11ea-863c-193d6e4a1d62.jpg)

**Comment by martynasma** [comment]
Try this:

```
chart.bottomAxesContainer.zIndex = -1;
```

**Comment by fu1996** [comment]
> Try this:
> 
> ```
> chart.bottomAxesContainer.zIndex = -1;
> ```

Thank you very much, the problem is solved, thank you
