### ISSUE TITLE
The chart shows the computer and tablet compatibility or Google version issues

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#2931]
The chart shows the computer and tablet compatibility or Google version issues

System: Both computers and tablets have windows,
Google Chrome version: PC: 84.0; Tablet PC: 80.0
The effect is as follows:
Expectation: It should be a green and a blue histogram
Now the result: all white in Google Chrome on the tablet, blue and green in Google Chrome on the computer
 
Use pattern to fill

**code:picture**
![a5f23116-c850-4dd4-ae83-6956cb0b6be2](https://user-images.githubusercontent.com/42232973/93857389-14860e80-fced-11ea-9f9a-bbf325798879.jpg)
![970468d1-23ac-4eb3-a3f9-150fc2d1f4bb](https://user-images.githubusercontent.com/42232973/93857398-1780ff00-fced-11ea-9484-18ba6fd1620b.jpg)

**Online debugging**
![778f5344-c837-441f-9a32-5f17d4598a2c](https://user-images.githubusercontent.com/42232973/93857478-31224680-fced-11ea-9040-b34589996f87.jpg)

**BUG picture**
![fbdeb742-411a-48ed-bb8a-c9c71372e827](https://user-images.githubusercontent.com/42232973/93857558-56af5000-fced-11ea-93a6-2705093fbf15.jpg)

**Normal picture**
![2c10fd50-31ef-46df-bf64-a010fa2d9323](https://user-images.githubusercontent.com/42232973/93857611-70509780-fced-11ea-8c91-361502978af8.jpg)

**Google Chrome version**
PC：
![c91ad62a-60f2-4800-8aa9-b59b53016cd3](https://user-images.githubusercontent.com/42232973/93857695-92e2b080-fced-11ea-86b8-cbcad0dfb152.jpg)

tablet：
![861a36de-4d09-4505-961b-5af859cec4a1](https://user-images.githubusercontent.com/42232973/93857732-a2fa9000-fced-11ea-9cd4-8fc5220b73f7.jpg)

**Comment by martynasma** [comment]
I'm sorry I'm not quite sure what you're asking here.

Can you post your chart online on CodePen and explain in detail what is not working like you expect to?

**Comment by fu1996** [comment]
> I'm sorry I'm not quite sure what you're asking here.
> 
> Can you post your chart online on CodePen and explain in detail what is not working like you expect to?

Sorry, I found the problem. Thank you for your answer
