### ISSUE TITLE
How to set a minimum shrinkage TreeMap cube?

### ISSUE THREAD

**Issue by yuvalr55** [amcharts/amcharts4#2935]
**I'm trying to set a minimal contraction and it does not work for me.**
`
let level2_column = level2.columns.template;
`

`
level2_column.minHeight = 10;
`
`
level2_column.minWidth = 10;
`

![Screenshot_3](https://user-images.githubusercontent.com/59453585/93889123-7fd1df80-fcf1-11ea-922e-608b18cd2f5a.png)

**Comment by martynasma** [comment]
I'm afraid there's currently no possibility to set minimum size of the columns.

**Comment by amolthakurr** [comment]
Is there a solution available for this now?
