### ISSUE TITLE
Right aligned axis tooltips don't render properly after first hover

### ISSUE THREAD

**Issue by mismael-r7** [amcharts/amcharts4#2936]
**Bug description**
Adding an axis tooltip to the y-axis that is aligned to the right side of the y-axis does not render properly on the second hover. On first hover the tooltip renders fine, but on the second it breaks.

Chrome Version 85.0
AmCharts v4
Mac OSX
Angular / Vanilla JS

Sandbox
https://codesandbox.io/s/misty-wood-oqrx5

On first hover the tooltip shows correctly (although missing the left pointer)
![Screen Shot 2020-09-22 at 1 32 06 PM](https://user-images.githubusercontent.com/71023380/93917007-5fe1f200-fcd8-11ea-9043-0badb2fd45b1.png)

On second hover the tooltip container is on the left and the tooltip text is on the right (in white so hard to see).
![Screen Shot 2020-09-22 at 1 32 11 PM](https://user-images.githubusercontent.com/71023380/93917009-5fe1f200-fcd8-11ea-9288-06c2c6704704.png)

**Comment by martynasma** [comment]
A bit hacky, but here's an easier solution:

```
valueAxis.updateTooltip = ()=>{};
axisTooltip.pointerOrientation = "left";
```

**Comment by mismael-r7** [comment]
So that actually gets us partially there! The tooltip still flashes incorrectly on the first hover but at least now it's pointing in the right direction every subsequent hover. curious why that worked. 🤔 

![Screen Shot 2020-09-23 at 12 39 53 PM](https://user-images.githubusercontent.com/71023380/94042773-fa563a00-fd99-11ea-968c-7029f7bd11bc.png)

![Screen Shot 2020-09-23 at 12 39 58 PM](https://user-images.githubusercontent.com/71023380/94042774-fa563a00-fd99-11ea-9e12-ddbd54567d13.png)

**Comment by martynasma** [comment]
That flashing is due to this line: `valueAxis.tooltipText = "TOOLTIPX";`.

Basically, axes have their own logic regarding tooltips, and setting `tooltipText` won't work as expected.

If you need to modify contents of the tooltip on axis, you'll need to apply an adapter:

https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/#Controlling_tooltip_content

**Comment by mismael-r7** [comment]
Sorry for any confusion but this is in regards to tooltips on hover of the y-axis itself and not the inner portion of the chart. So for example hovering over the label `2,000`

**Comment by martynasma** [comment]
Gotcha. No worries.

In that case you should probably set your tooltip stuff on labels directly:

```
valueAxis.renderer.labels.template.tooltip = new am4core.Tooltip();
valueAxis.renderer.labels.template.tooltipText = "TOOLTIPX";
```

Since we're creating a separate tooltip for labels, it's impervious to axis' tooltip fuzzy logic, and you can apply all kinds of settings to it.

**Comment by mismael-r7** [comment]
yup that seems to have done it! Good to know when to use the label itself vs simply the axis tooltip. Thanks!

**Comment by mismael-r7** [comment]
I have one last question before closing this issue. I couldn't find any documentation on position _axis label_ tooltips. Using the axis rendered properties `tooltipX` and `dx / dy` doesn't seem to allow me to position the tooltip relative to the axis label. (properties on the renderer)

```valueAxis.renderer.labels.template```



for instance positioning the tooltip to the left or right of the label

**Comment by mismael-r7** [comment]
question answered closing
