### ISSUE TITLE
amCharts Maps AlbersUsa projection doesn't support Puerto Rico or VirginIslands

### ISSUE THREAD

**Issue by shichenglu** [amcharts/amcharts4#2937]
AlbersUsa projection supports Alaska and Hawaii very well, however, even when I use usaTerritoriesLow map, it won't show Puerto Rico or US Virgin islands, the Miller projection will show those territories but it doesn't support real latitude/longitude. Is there a way to show those territories and support real latitude/longitude?
Thanks,

Lucsa

**Comment by xorspark** [comment]
The AlbersUsa projection only supports Hawaii and Alaska, per https://github.com/amcharts/amcharts4/issues/1714#issuecomment-537459785. usaTerritories maps are distorted visually, so real coordinates won't work on the territories.
