### ISSUE TITLE
How to compare 2 consecutive weeks by imposing the 2 graphs together

### ISSUE THREAD

**Issue by gaurav30-hkr** [amcharts/amcharts4#2938]
**Question**
How to compare 2 consecutive weeks by imposing the 2 graphs together.
Description : series 1 [september 13 to september 19]
                      series 2 [september 06 to september 12]
on Date Axis instead of date I am showing day [Sun, Mon ]

Now how to impose graph of 2 consecutive weeks on same date axis

**Environment (if applicable)**
Typescript
Angular 9

**Additional context**
sample data :
**Week 1 Data :** 
{Time: "2020-09-13", Data1: 8, Data2: 18,…}
.
.
.
{Time: "2020-09-19", Data1: 3, Data2: 3.3 …}

**Week 2 Data :** 
{Time: "2020-09-06", DataPreviousWeek1: 16, DataPreviousWeek: 3.3, …}
.
.
.
{Time: "2020-09-12", DataPreviousWeek1: 21, DataPreviousWeek: 8, …}

I have to compare  September 13[sunday] data with September 06 [Sunday] data and so on September 19 [Saturday] data with September 12 [Saturday] using series chart

**Comment by martynasma** [comment]
You will need to add two DateAxis and assign to their respective Series.

You will also need to add data directly to each series, as opposed to adding it to chart.

Here's an example:
https://www.amcharts.com/demos/multiple-date-axes/
