### ISSUE TITLE
Axis fills prevent column tooltips on RadarChart

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#294]
Example:
https://codepen.io/team/amcharts/pen/b4a1c7bed4e76d354384dfc7f2c9a5b3?editors=0010

**Comment by zeroin** [comment]
as zIndex of seriesContainer is set to -1, fills are above the columns. this means you have to set:

valueAxis.renderer.axisFills.template.interactionsEnabled = false;
categoryAxis.renderer.axisFills.template.interactionsEnabled = false;

in order for columns to receive mouse events.
