### ISSUE TITLE
While grouping how could i get sum value

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#2942]
Hi
I have been working on amcharts4, in our Angular 6+ project in that i have done grouping data based on switching elements like daily, weekly, monthly but not able to get the sum value while using adapter.

Working when i'm using without adapter
 dateAxis.groupData = true;
 dateAxis.groupInterval = {timeUnit: 'week', count: 1};
     const series = chart.series.push(new am4charts.LineSeries());
      series.dataFields.dateX = 'x';
      series.dataFields.valueY = 'y';
      series.name = 'Value1';
      series.stroke = am4core.color(colors[index]);
      series.strokeWidth = 3;
      series.tooltipText = name + ': {valueY}';
      series.tooltip.background.stroke = am4core.color(colors[index]);
      series.tooltip.background.strokeWidth = 2;
      series.tooltip.getFillFromObject = false;
      series.tooltip.background.fill = am4core.color('#ffffff');
      series.tooltip.label.fill = am4core.color('#030303');
      series.groupFields.valueY = 'sum';
      index++;

Not working when i'm using adapter
 dateAxis.groupData = true;
 dateAxis.groupInterval = {timeUnit: 'week', count: 1};
 const series = chart.series.push(new am4charts.LineSeries());
      series.dataFields.dateX = 'x';
      series.dataFields.valueY = 'y';
      series.name = 'Value1';
      series.stroke = am4core.color(colors[index]);
      series.strokeWidth = 3;
      series.tooltipText = name + ': {valueY}';
      series.tooltip.background.stroke = am4core.color(colors[index]);
      series.tooltip.background.strokeWidth = 2;
      series.tooltip.getFillFromObject = false;
      series.tooltip.background.fill = am4core.color('#ffffff');
      series.tooltip.label.fill = am4core.color('#030303');
      series.groupFields.valueY = 'sum';
      index++;

 series.adapter.add("tooltipText", function(ev) {
                var text = "[bold]{dateX.formatDate(\"MMM d, yyyy\")}[/]\n"
                chart.series.each(function(item) {
                        text += "[" + item.stroke + "]●[/] " + item.name + ": {" + item.dataFields.valueY + "}\n";
                });
                return text;
            });

Could you help me out on how to get sum value using adapter or any better solution for this issue.

Thanks in advance...

**Comment by martynasma** [comment]
Something like this should work:

```JavaScript
series.adapter.add("tooltipText", function(text, target) {
  var index = target.tooltipDataItem.index;
  var text = "[bold]{dateX.formatDate(\"MMM d, yyyy\")}[/]\n";
  chart.series.each(function(item) {
    text += "[" + item.stroke + "]●[/] " + item.name + ": " + item.dataItems.getIndex(index).valueY + "\n";
  });
  return text;
});
```

**Comment by meghanaNanuvala** [comment]
Working
series
![Screenshot from 2020-09-25 17-18-35](https://user-images.githubusercontent.com/71019344/94264812-0afedf80-ff55-11ea-8ef9-4d3c9d61adaa.png)
.adapter.add("tooltipText", function(ev) {
                    var text = "[bold]{dateX.formatDate(\"MMM d, yyyy\")}[/]\n"
                    chart.series.each(function(item) {
                        if(item.name.indexOf('Volume')>-1)
                        {
                            text += "[" + item.stroke + "]●[/] " + item.name + ": {" + item.dataFields.valueY + "}\n";
                        }else {
                            text += "[" + item.stroke + "]●[/] " + item.name + ":$ {" + item.dataFields.valueY + "}\n";
                        }
                    });
                    return text;
                });
![Screenshot from 2020-09-25 17-26-18](https://user-images.githubusercontent.com/71019344/94264700-c7a47100-ff54-11ea-9440-6d5b3a9b9aeb.png)

Still not working with the logic you have mentioned
series.adapter.add("tooltipText", function( text, target) {
               var index = target.tooltipDataItem.index;
                var text = "[bold]{dateX.formatDate(\"MMM d, yyyy\")}[/]\n"
                chart.series.each(function(item) {
                    if(item.name.indexOf('Volume')>-1)
                    {
                        text += "[" + item.stroke + "]●[/] " + item.name + ": {" + item.dataItems.getIndex(index).valueY + "}\n";
                    }else {
                         text += "[" + item.stroke + "]●[/] " + item.name + ": ${" + item.dataItems.getIndex(index).valueY + "}\n";
                    }
                });
                return text;
            });

**Comment by meghanaNanuvala** [comment]
Working
series3.adapter.add("tooltipText", function(ev) {
                    var text = "[bold]{dateX.formatDate(\"MMM d, yyyy\")}[/]\n"
                    chart.series.each(function(item) {
                        if(item.name.indexOf('Volume')>-1)
                        {
                            text += "[" + item.stroke + "]●[/] " + item.name + ": {" + item.dataFields.valueY + "}\n";
                        }else {
                            text += "[" + item.stroke + "]●[/] " + item.name + ":$ {" + item.dataFields.valueY + "}\n";
                        }
                    });
                    return text;
                });

![Screenshot from 2020-09-25 17-26-18](https://user-images.githubusercontent.com/71019344/94265205-bf006a80-ff55-11ea-8030-065272711834.png)


Still not working with the logic you have mentioned
series.adapter.add("tooltipText", function(text, target) {
  var index = target.tooltipDataItem.index;
  var text = "[bold]{dateX.formatDate(\"MMM d, yyyy\")}[/]\n";
  chart.series.each(function(item) {
    if(item.name.indexOf('Volume')>-1)
                    {
                        text += "[" + item.stroke + "]●[/] " + item.name + ": {" + item.dataItems.getIndex(index).valueY + "}\n";
                    }else {
                         text += "[" + item.stroke + "]●[/] " + item.name + ": ${" + item.dataItems.getIndex(index).valueY + "}\n";
                    }
  });
  return text;
});
![Screenshot from 2020-09-25 17-18-35](https://user-images.githubusercontent.com/71019344/94265271-d50e2b00-ff55-11ea-96b4-e73431a165a4.png)

**Comment by martynasma** [comment]
You shouldn't enclose values in curly brackets as they would be treated as data placeholders. Please refer to my code snippet.

**Comment by meghanaNanuvala** [comment]
Thank you so much........It worked

**Comment by meghanaNanuvala** [comment]
But formatting for tooltip is lost, How can i format number with comma to the tooltip adapter

**Comment by martynasma** [comment]
I suppose you can apply formatting directly using:

```
chart.numberFormatter.format(item.dataItems.getIndex(index).valueY)
```

**Comment by meghanaNanuvala** [comment]
Thank you
