### ISSUE TITLE
How to change the order of bars manually on a bar chart?

### ISSUE THREAD

**Issue by applecool** [amcharts/amcharts4#2943]
**Question**

Hi all,

I have a bar chart and want to change the order of the bars represented, but manually i.e., preferably by dragging and dropping to sort the bars. Does amCharts support this functionality?  I did see a draggable on pie slices demo but I couldn't find anything with the bar charts. The only other demo I found was to drag on the bars to increase and decrease the value with respect to its size. 

**Environment (if applicable)**
amCharts version 4 - 4.9.24

**Comment by martynasma** [comment]
Technically, it should be possible, but would require some custom coding, like with the Pie Chart demo you mentioned. And we don't happen to have such demo ready made :(

**Comment by applecool** [comment]
Cool. Thank you :)

**Comment by applecool** [comment]
@martynasma As you already know, I got this working with your [pen](https://codepen.io/team/amcharts/pen/jOqoKKb). I have a followup question though. Can we drag two bars at the same time to do a manual sort? With the draggable property set, only one bar/element can be moved around. Is there any way to multi-select and drag them together?

**Comment by applecool** [comment]
Found that multi-drag support is very minimal at this point. The manual drag and drop of bars has been updated on the am-charts demo [page](https://www.amcharts.com/demos/drag-ordering-of-bars/) Thank you again. Closing this.
