### ISSUE TITLE
How to get the pixel height of a value on the Y axis of the value axis

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#2944]
How to get the pixel height of a value on the Y axis of the value axis

**Comment by martynasma** [comment]
Um, what is a "pixel height of a value"? :)

If you mean pixel difference between two values, you can use `ValueAxis` method [`valueToPoint()`](https://www.amcharts.com/docs/v4/reference/valueaxis/#valueToPoint_method) on both values, then check the difference between `y` of the returned points.

**Comment by fu1996** [comment]
> 嗯，“值的像素高度”是什么？:)
> 
> 如果您是指两个值之间的像素差异，则可以对两个值都使用`ValueAxis`method [`valueToPoint()`](https://www.amcharts.com/docs/v4/reference/valueaxis/#valueToPoint_method)，然后检查`y`返回点之间的差异。

Get a Rectangle column with a value of 750 [Because the X axis uses ValueAxis, the column chart cannot be created]

[https://codepen.io/fu1996/pen/KKzJMJj?editors=0010](https://codepen.io/fu1996/pen/KKzJMJj?editors=0010)

**Current effect**
![image](https://user-images.githubusercontent.com/42232973/94109577-c6e7de00-fe73-11ea-97f8-81da7d9c2b0c.png)
**Actual desired effect**
![image](https://user-images.githubusercontent.com/42232973/94109991-71f89780-fe74-11ea-96a8-53472c806965.png)

**Comment by martynasma** [comment]
Do you need a fixed with column? If that is the case, you can just use `ColumnSeries` and set `width` on your column template:

```
columnSeries.columns.template.width = 50;
```

It would be easier than calculating widths, drawing axis ranges, and whatnot, for a simple square on a chart.

**Comment by fu1996** [comment]
> 您需要固定的立柱吗？如果是这种情况，您可以在列模板上使用`ColumnSeries`和设置`width`：
> 
> ```
> columnSeries.columns.template.width = 50;
> ```
> 
> 对于图表上的一个简单正方形，这比计算宽度，绘制轴范围等要容易得多。


Because the X axis uses ValueAxis, I cannot create a column chart through ColumnSeries

**Comment by martynasma** [comment]
Yes, you can:
https://codepen.io/team/amcharts/pen/1a03cf728bd3d98b965b64ae71b0b2be

**Comment by fu1996** [comment]
> Yes, you can:
> https://codepen.io/team/amcharts/pen/1a03cf728bd3d98b965b64ae71b0b2be

Thank you, this attribute is very useful to me.
Wow, awesome, can you tell me why you want to add this attribute? At first, I thought it was not possible to display both a line graph and a column graph on the value axis.
columnSeries.columns.template.width = 50;

**Comment by martynasma** [comment]
> can you tell me why you want to add this attribute?

Because value axis does not have exact categories so no exact cells, and columns do not know how to size themselves. Setting `width` explicitly solves it.
