### ISSUE TITLE
How to solve the problem of the icon icon being truncated

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#2945]
As mentioned in the title, the maskBullets = false attribute of the chart is used, but the problem still exists
[https://codepen.io/fu1996/pen/KKzJMJj](https://codepen.io/fu1996/pen/KKzJMJj)
for example:
![image](https://user-images.githubusercontent.com/42232973/94099280-2b4b7300-fe5d-11ea-9700-1003f12ce1f3.png)
![image](https://user-images.githubusercontent.com/42232973/94099478-9bf28f80-fe5d-11ea-8418-131707c9c0cc.png)
![image](https://user-images.githubusercontent.com/42232973/94099489-a3199d80-fe5d-11ea-87bf-dd5c75a8fc80.png)

**Comment by martynasma** [comment]
You can Increase `chart.paddingTop`.

**Comment by fu1996** [comment]
> You can Increase `chart.paddingTop`.

Thank you, this attribute is very useful to me.
