### ISSUE TITLE
How to update the system tooltips on the scrollbar chart?

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#2946]
I was following the [tutorial](https://www.amcharts.com/docs/v4/tutorials/handling-repeating-categories-on-category-axis/) to handle repeating categories in the CategoryAxis but it doesn't give any advice on how to fix the scrollbar chart system tooltips.

![image](https://user-images.githubusercontent.com/2857604/94135553-8714fc80-fe5b-11ea-9930-f88a9edc1950.png)

In the screenshot above, the tooltip should display 'To 3rd' not 'To 3rd (6)'.
Here is a CodePen illustrating the problem: https://codepen.io/jbate/pen/PoNVjKE

I can only find documentation on how to disable them. Any help would be greatly appreciated.

**Comment by martynasma** [comment]
I suppose you need to use adapters on everything then:

```
categoryAxis.renderer.labels.template.adapter.add("textOutput", normalizeCategory);
chart.scrollbarX.startGrip.adapter.add("readerTitle", normalizeCategory);
chart.scrollbarX.endGrip.adapter.add("readerTitle", normalizeCategory);

function normalizeCategory(text) {
  return text ? text.replace(/ \(.*/, "") : text;
}
```

That being said, just noticed there's an issue with system tooltips not being shown at all, since last update.

We'll fix it in the next version.

**Comment by jbate** [comment]
Excellent. Thanks for much for the quick response!
