### ISSUE TITLE
Avoid changing color in het map

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#2948]
I have a vertical bar chart where I have created a heat rule like this:

```
series.heatRules.push({
            "target": series.columns.template,
            "property": "fill",
            "min": am4core.color("#D58EAA"),
            "max": am4core.color("#0F8E8E"),
            "dataField": "valueX"
 });
```
It woks fine but the problem is that I'm displaying the values with a default level of zoom and what the charts does is to adjust the color of the items based on the number of items displayed. Is it possible to avoid this behavior? I don't want the colors to change, just apply the heat rule to all values and display always the same colors regarding of the level of zoom.

Thank you.

**Comment by martynasma** [comment]
I suppose you will need to add heat rule after data is validated and top values are calculated so you can explicitly set `minValue` and `maxValue` of the heat rule:

```JavaScript
chart.events.on('datavalidated', function() {
  series.heatRules.push({
    "target": series.columns.template,
    "property": "fill",
    "min": am4core.color("#D58EAA"),
    "minValue": series.min(valueAxis),
    "max": am4core.color("#0F8E8E"),
    "maxValue": series.max(valueAxis),
    "dataField": "valueX"
  });
})
```

**Comment by javier-fjfs** [comment]
That works perfect. Thank you!!

**Comment by javier-fjfs** [comment]
Sorry, I reopen this question because if I change the chart data, the colors displayed are not correct. I've seen that the heat rule has the correct values for max and min color but the chart is not reflecting that. Is there anything else to do to 'refresh' the chart? I've tried with validateRawData but it doesn't work.

Thank you.

**Comment by martynasma** [comment]
When you say "change chart data" do you mean you replace the whole `data` or you change individual values in data arrays?

**Comment by javier-fjfs** [comment]
hole data

**Comment by javier-fjfs** [comment]
Any update on this question?

Thank you.

**Comment by martynasma** [comment]
Do you have a CodePen for that? I can't seem to be able to reproduce this.
