### ISSUE TITLE
amcharts4 line chart fails to render in Firefox 81

### ISSUE THREAD

**Issue by poweradminllc** [amcharts/amcharts4#2949]
This page with 1 chart renders fine in Chrome, but fails to render in Firefox and also IE (not that IE matters to us).

https://paoffice.dyndns.org:81/STATUS_EXEC_SUMMARY_(0)/index.html?CMD=REFRESH_REPORT&RTYPE=14&ROBJ=0

There are no errors in the browser console so we're not sure what is going wrong.

**Comment by martynasma** [comment]
Chrome works because it's very forgiving to obscure date/time formats like one you have in your data: `12:25 AM\n16 Sep`

Firefox is not as easy going.

More information about date formats in source data here:
https://www.amcharts.com/docs/v4/concepts/data/#Parsing_dates_in_data

**Comment by poweradminllc** [comment]
Thank you Martynas - date formats lead us to the solution.
