### ISSUE TITLE
Showing less than symbol at percentage in legend value label , when percentage is 0 or less.

### ISSUE THREAD

**Issue by sajidAzeem** [amcharts/amcharts4#2952]
Hi,
I want to show less than(<) symbol at percentage in my piechart legend value label when It shows  percentage as 0. I wanted to show like below.
![Screenshot from 2020-09-25 16-14-45](https://user-images.githubusercontent.com/70995105/94258670-d0904500-ff4a-11ea-980b-14d5e111776e.png)

**Comment by martynasma** [comment]
You can do so using an adapter:

```JavaScript
chart.legend.valueLabels.template.adapter.add("textOutput", function(text, target) {
  return target.dataItem.values.value.percent < 0.01 ? "<0.01%" : text;
})
```

**Comment by sajidAzeem** [comment]
> You can do so using an adapter:
> 
> ```js
> chart.legend.valueLabels.template.adapter.add("textOutput", function(text, target) {
>   return target.dataItem.values.value.percent < 0.01 ? "<0.01%" : text;
> })
> ```

Thank you for response. when I use above trick it's just showing percentage, it's not showing value.
![Screenshot from 2020-09-25 17-22-51](https://user-images.githubusercontent.com/70995105/94264198-e48c7480-ff53-11ea-8293-67f26d41a64e.png)

It should show percentage(<0.01)  in braces beside value.

**Comment by martynasma** [comment]
Oh, c'mon, it's not that hard to figure it out ;)

```JavaScript
chart.legend.valueLabels.template.adapter.add("textOutput", function(text, target) {
  if(target.dataItem.values.value.percent < 0.01) {
    text = text.replace(/\(.*$/, "(<%0.01)");
  }
  return text;
})
```

**Comment by sajidAzeem** [comment]
> Oh, c'mon, it's not that hard to figure it out ;)
> 
> ```js
> chart.legend.valueLabels.template.adapter.add("textOutput", function(text, target) {
>   if(target.dataItem.values.value.percent < 0.01) {
>     text = text.replace(/\(.*$/, "(<%0.01)");
>   }
>   return text;
> })
> ```

Thank you very much. It's working perfectly.
