### ISSUE TITLE
Pie Chart and Bar chart are not loading when I change date ranges.

### ISSUE THREAD

**Issue by sajidAzeem** [amcharts/amcharts4#2953]
Hello,
when I switch to Different date ranges  like year , month..etc  then my pie and bar charts are not getting loaded.
![Screenshot from 2020-09-25 18-11-12](https://user-images.githubusercontent.com/70995105/94268553-f9203b00-ff5a-11ea-884c-59480337df35.png)

when I check my Browser console am getting a warning like `chart was not disposed`, and chart is not getting visibled. Below is my browser console.
![Screenshot from 2020-09-25 21-33-17](https://user-images.githubusercontent.com/70995105/94289746-d13ed080-ff76-11ea-867a-d3c79c994b28.png)

**Comment by martynasma** [comment]
You're basically asking us debug a screenshot of your custom app. This is beyond scope of this repo, sorry.
