### ISSUE TITLE
Force directed tree link dataFields

### ISSUE THREAD

**Issue by lancegliser** [amcharts/amcharts4#2954]
**Question**

I checked #2416, it isn't quite the same question.
I'm wondering how I associate a set of data with a linkWith generated link. I have some meta data such as a description of the relationship that needs to be accessible from the link. It's data that's independent of either connected node. 

I was hoping to find dataFields in some method that would work, but there doesn't appear to be. I checked, and `link._dataItem` refers to one of the related nodes.

If I could do anything like keeping at least an id on the link I could query the rest if I have to. I'd prefer to store an arbitrary dataItem for the link. 

Is that at all possible?

**Environment (if applicable)**

amCharts4@4.9.37
Chrome (but doesn't apply)
Vue, typescript (but doesn't apply)

**Comment by martynasma** [comment]
I'm afraid there's no way to attach separate data context to a ForceDirectedLink (regardless if it's a parent-child or peer-to-peer link) as links do not have own data items.

I suppose the solution is to attach your meta data to either source or target node (accessible via data item of the link via `source` and `target` properties), then extract it via custom code.

I hope that makes sense.

Here's an example:
https://codepen.io/team/amcharts/pen/6075f21ca2adeebc406ce4c8d94a37a0
