### ISSUE TITLE
There is space on left side of line series 

### ISSUE THREAD

**Issue by setiawans** [amcharts/amcharts4#2955]
**Question**
Guys, can you help me, why there is space on line series?
[https://monosnap.com/file/ra35uaYKD5cmq2VJGjuCp6hjn3bXJ0](url)

**Comment by setiawans** [comment]
@martynasma i think this one is related with #968

**Comment by martynasma** [comment]
Please read here for the solution:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

**Comment by setiawans** [comment]
@martynasma please take a look to this video https://monosnap.com/file/HnZe8GXruOdDOp3BBK4OvuyMhAE9xs
when i try to resize the screen the space gone. so how to solve this problem? or maybe you have suggestion what element was making a problem.

**Comment by martynasma** [comment]
Could you post your chart online where we can test it? E.g. on CodePen or jsFiddle.
