### ISSUE TITLE
Regarding groupinterval

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#2957]
Hi 
I am working on amcharts4 in our angular 6+ project, that I am struggling with this issue regarding groupinterval.

code : dateAxis.groupInterval = { timeUnit: this.periodInterval, count: 1};
error            : error TS2551: Property 'groupInterval' does not exist on type 'DateAxis<AxisRenderer>'. Did you mean 'groupIntervals'?

Here I have defined this.periodInterval as day/week/month

Could you give a solution to sort out immediately

Thanks in advance

**Comment by martynasma** [comment]
I suppose it depends on how you instantiate your DateAxis object whether TS compiler is able to derive the type.

To fix this I suggest instantiating `DateAxis` in a standalone variable, then pushing it to `xAxes` of the chart:

```TypeScript
const dateAxis = new am4charts.DateAxis();
chart.xAxes.push(dateAxis);
```

This should take care of the warning.
