### ISSUE TITLE
Column Series Labels

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#2958]
**Question**

I have created a chart with a column series and have used the code below to create a label with the value.

var label = hourlyVarianceSeries.columns.template.createChild(am4core.Label);
label.text = "{value}";
label.fill = scope.config.textColour;
label.rotation = 270;
label.align = "bottom";
label.valign = "middle";
label.zIndex = 1;

The label creates fine but I want to add a couple of user options to allow them to change the label fill and and to disable the labels if required.

I have tried modifying the following attributes but it had no affect,

chart.series.values[2].columns.template.children[1].fill = scope.config.textColour;
chart.series.values[2].columns.template.children[1].disabled = true;

**Environment (if applicable)**

**Additional context**

**Comment by xorspark** [comment]
Since the label is part of a template, you need to set [`applyOnClones`](https://www.amcharts.com/docs/v4/concepts/list-templates/#Propagating_template_changes) to true on the initial label object in order for the changes to propagate:

```
label.applyOnClones = true;

// ...
chart.series.getIndex(2).columns.template.children.getIndex(1).fill = scope.config.textColour;
chart.series.getIndex(2).columns.template.children.getIndex(1).disabled = true;
```

**Comment by towsie84** [comment]
Great, thanks that worked a treat.

Is it possible to add an adapter for locationY? I would like to modify the locationY value based on the value of the label.

Thanks

**Comment by martynasma** [comment]
> Is it possible to add an adapter for locationY? I would like to modify the locationY value based on the value of the label.

Labels do not have locationY property and in extension adapter for it.

If you need to position a Label as a child to a column, you will need to use `align` and `valign` properties instead. Adapters for those should work.

If you want `locationY` you will need to add your labels to series' `bullets` as `LabelBullet` objects.
