### ISSUE TITLE
Adding a alignment within tooltip box

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#2959]
Hi
I have been working on amcharts4 in our angular6+ project. In a multi-line single tool tip how can I add a alignment within it. 

Thanks in advance

**Comment by martynasma** [comment]
If you are referring to text alignment within the tooltip, then you can do so using tooltip's label object:

```JavaScript
series.tooltip.label.textAlign = "middle";
```

**Comment by meghanaNanuvala** [comment]
To adapter How can i add?
series.adapter.add("tooltipText", function(text, target) {
                var index = target.tooltipDataItem.index;
                var text = "[bold]{dateX.formatDate(\"MMM d, yyyy\")}[/]\n";
                chart.series.each(function(item) {
                    if(item.name.indexOf('Volume')>-1) {
                        text += "[" + item.stroke + "]●[/] " + item.name + ": " + chart.numberFormatter.format(item.dataItems.getIndex(index).valueY) + "\n";
                    }else{
                        text += "[" + item.stroke + "]●[/] " + item.name + ": $" + chart.numberFormatter.format(item.dataItems.getIndex(index).valueY)+ "\n";
                    }
                });
                return text;
            });

Only the values in tooltip need to be aligned right. How can I implement?
![Screenshot from 2020-09-29 12-26-36](https://user-images.githubusercontent.com/71019344/94523644-1ef55a80-024f-11eb-916d-4d51357530f2.png)

**Comment by martynasma** [comment]
There's no way to set in-line alignment in SVG text tooltips.

You would need to use `tooltipHTML` instead and use HTML/CSS in tooltip content to arrange your tooltip content.

**Comment by meghanaNanuvala** [comment]
How can I set for multiline single tooltip box?

Can you elaborate a little bit

**Comment by martynasma** [comment]
It's the same as you have right now, except instead of `tooltipText` you use `tooltipHTML`, and instead inline formatting like `[#f00]` you use actual HTML code and CSS.

Hope that makes sense.
