### ISSUE TITLE
Change category and legend `font-family` 

### ISSUE THREAD

**Issue by fakhamatia** [amcharts/amcharts4#2963]
How can I change `font-family` only for category of data and legend?
or
How can I set a class for the only category and legend to fix the RTL thing

![ksnip_20200929-171951](https://user-images.githubusercontent.com/20030910/94567189-0c434b80-0278-11eb-98ff-9a42d3874e08.png)

**Comment by martynasma** [comment]
You can set `fontFamily` on axis' label template:

```
axis.renderer.labels.template.fontFamily = ".....";
```

Similarly, for legend:

```
chart.legend.labels.template.fontFamily = "....";
```

**Comment by fakhamatia** [comment]
> ```
> axis.renderer.labels.template.fontFamily = ".....";
> ```
I want to change the green box, not the red box, and label text disappears!
![ksnip_20200929-192408](https://user-images.githubusercontent.com/20030910/94582952-be374380-0289-11eb-9506-cdab914a9a86.png)
 
> ```
> chart.legend.labels.template.fontFamily = "....";
> ```
This Work.

**Comment by martynasma** [comment]
Maybe you did not replace "axis" with the actual variable that holds Y axis object?

**Comment by fakhamatia** [comment]
Yes, I've replaced the wrong variable, its work now
But I want to fix braces it's `()` but in the chart show `))`

**Comment by martynasma** [comment]
Do you have your chart online somewhere?

**Comment by fakhamatia** [comment]
Must be on CodePen/jsFiddle? On a host, if I put it, it's okay?

**Comment by martynasma** [comment]
Ideally, yes. If it's not possible, you can put it on your own host and the code would be accessible then it's OK I suppose.

**Comment by fakhamatia** [comment]
I did my best
[Project Link](https://codepen.io/fakhamatia/project/editor/AgGpyz)

**Comment by martynasma** [comment]
I'm not seeing any double `))` in your chart. What am I missing?

![image](https://user-images.githubusercontent.com/1458520/95052405-90258980-06f7-11eb-83c4-b12fbf1d319a.png)

**Comment by fakhamatia** [comment]
No not double `))`
This text is correct 
![ksnip_20201005-143555](https://user-images.githubusercontent.com/20030910/95072502-24074d80-0718-11eb-90cb-d2f4bdecb97c.png)
Not this
![ksnip_20201005-143726](https://user-images.githubusercontent.com/20030910/95072592-4dc07480-0718-11eb-8ad0-635f9e472522.png)

**Comment by martynasma** [comment]
Adding `chart.rtl = true` seems to fix those labels. I don't see this anywhere in your code.

**Comment by fakhamatia** [comment]
Yes its work, but its effect on legends and align them to right

**Comment by martynasma** [comment]
This, should fix the legend:

```JavaScript
chart.legend.labels.template.textAlign = "end";
```
