### ISSUE TITLE
TreeMap: is {sum} not a valid data placeholder?

### ISSUE THREAD

**Issue by clintharris** [amcharts/amcharts4#2964]
**Question**

The `{sum}` data placeholder does not appear to work with TreeMapSeries. Is this expected?

Demo: https://codepen.io/clintharris/pen/LYNopXY

**Comment by martynasma** [comment]
There's no "sum" being calculated in each of the individual data items. However, each "virtual" series, has sum of its nodes calculated in its own data item. You can access it like this: `{dataItem.value}`.

I know - not super intuitive, but it works ;)
