### ISSUE TITLE
xAxis interval background-color

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#2965]
Hello there !

Is there a way to reproduce something like that with amchart (for date axis)? I mean change background color for an internval ? (maybe change the color on hover to ?)

![image](https://user-images.githubusercontent.com/6083644/94572069-e49cb500-0270-11eb-93b6-43c78d7c0a1b.png)

Thanks for your help!

**Comment by martynasma** [comment]
I'm afraid there's no straightforward way to do that with just settings. Sorry.

**Comment by ptorrent** [comment]
ok thanks !

**Comment by ashwanikumar415** [comment]
i want to do exact same thing . How did you manage to customize x-axis ?
if you have done it in with svg . Could you please share your code ?
