### ISSUE TITLE
Problem with RTL template and bootstrap-rtl

### ISSUE THREAD

**Issue by fakhamatia** [amcharts/amcharts4#2966]
I use [CoreUI](https://github.com/coreui/coreui-free-bootstrap-admin-template) template and CoreUI support RTL by adding `dir="rtl` to HTML tag

When I use `<html dir="rtl">` and `bootstrap-rtl`:

![ksnip_20200929-180059](https://user-images.githubusercontent.com/20030910/94573168-b02ff580-027e-11eb-9435-763923785bb3.png)

When I don't use `<html dir="rtl">` and `bootstrap-rtl` in English version:

![ksnip_20200929-180904](https://user-images.githubusercontent.com/20030910/94573441-f4bb9100-027e-11eb-83d6-c3fd8eb801dc.png)

Using `chart.rtl = true; chart.legend.itemContainers.template.reverseOrder = true;` not work

[bootstrap-rtl.css.zip](https://github.com/amcharts/amcharts4/files/5299865/bootstrap-rtl.css.zip)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by fakhamatia** [comment]
Sorry, I do not know much about working with these sites, I'm trying to get charts online
But in the new update, the chart got much better when using `chart.rtl = true;`
One question and one problem
How to move categories to right?
And labels not showing

![ksnip_20201002-170628](https://user-images.githubusercontent.com/20030910/94930077-c33b0380-04d2-11eb-8ae4-2bf2ed56a20e.png)

**Comment by martynasma** [comment]
> How to move categories to right?

```JavaScript
categoryAxis.renderer.opposite = true;
```

> And labels not showing

Not sure. Would it be possible to see your chart code and data so that we can reproduce it?

**Comment by fakhamatia** [comment]
> > How to move categories to right?
> 
> ```js
> categoryAxis.renderer.opposite = true;
> ```

And How change direction to right? like  `chart.legend.itemContainers.template.reverseOrder = true;` but for categories

> > And labels not showing
> 
> Not sure. Would it be possible to see your chart code and data so that we can reproduce it?

I was testing the project on codepen for reproducing and realized that there is a problem with this particular font and other fonts do not have this problem and it has nothing to do with the site being RTL
Why? its font problem?
Use this CDN:
```html
<link href="https://cdn.jsdelivr.net/gh/rastikerdar/samim-font@v[X.Y.Z]/dist/font-face.css" rel="stylesheet" type="text/css" />
```
[Samim Font](https://github.com/rastikerdar/samim-font)

![Screenshot from 2020-10-02 18-17-50](https://user-images.githubusercontent.com/20030910/94937720-d4890d80-04dc-11eb-9c4f-d4317c8e2f7f.png)

**Comment by martynasma** [comment]
Try this:

```
categoryAxis.renderer.labels.template.align = "right";
```

**Comment by fakhamatia** [comment]
Thanks for the great support
Sorry if I asked too many questions, thank you for your patience

**Comment by fakhamatia** [comment]
Thanks for the great support
Sorry if I asked too many questions, thank you for your patience
