### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#2968]
Hi

![Screenshot from 2020-10-01 17-08-59](https://user-images.githubusercontent.com/71019344/94804629-c2d63600-0408-11eb-8695-838027157eb7.png)

Can you tell me how to remove that 0.00 at right side axis. 

`volumeAxis.numberFormatter.numberFormat = '#,###'; //tried this`
`chart.numberFormatter.numberFormat = "#,###.00"; //but it is overriding this logic`

Thanks in advance

**Comment by martynasma** [comment]
I don't see why zero label should be formatted like this. It means you have something in your setup that causes it.

If you could post your whole chart on CodePen.jsFiddle I'd be able to take a look.

**Comment by meghanaNanuvala** [comment]
> I don't see why zero label should be formatted like this. It means you have something in your setup that causes it.
> 
> If you could post your whole chart on CodePen.jsFiddle I'd be able to take a look.

Here is my  [chart code](https://jsfiddle.net/meghanan/2pvswu4L/40/)

**Comment by martynasma** [comment]
Thanks. Indeed.

There are a few things you can do:

1) Disabling adjustment of label precision:

```JavaScript
volumeAxis.adjustLabelPrecision = false;
```

This way, the ValueAxis will not try to automatically select label precision based on step size, so all the labels will follow global label format you have set on global formatter.

2) If you need to follow axis different number format, you can create a separate instance of NumberFormatter, like you have for another axis:

```JavaScript
volumeAxis.numberFormatter = new am4core.NumberFormatter();
volumeAxis.numberFormatter.numberFormat = '#.';
```
