### ISSUE TITLE
Tooltip not displaying properly if data contains a 'name' property

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#2969]
I have a chart that has a 'name' property in the data. Trying to display the series name in the tooltip displays the name from the data field instead.

Is this a bug or am I missing something? How can I be explicit and tell it to use the series name?

Here is a CodePen with an example: https://codepen.io/jbate/pen/JjXQWVK

This is a screenshot of the expected result:
![image](https://user-images.githubusercontent.com/2857604/94819133-cf519300-03f6-11eb-910e-c56bd30956de.png)

And here is a screenshot of the actual result:
![image](https://user-images.githubusercontent.com/2857604/94819170-da0c2800-03f6-11eb-9354-c1c319b1f62e.png)

**Comment by martynasma** [comment]
It's by design. The data placeholders will first look in data item and data context and then in the data item's parent object.

The solution would be to use `{component.name}`, because `component` in series data item refers to the related series object.
