### ISSUE TITLE
Live data amcharts getting slow like it's hang after sometime the page refresh.

### ISSUE THREAD

**Issue by mianSaif** [amcharts/amcharts4#2971]
Hi there I'm making a trading website and I'm using a amcahrts for this. But during the development, I have faced some issues in live data charts. amcharts getting so slow.  when the page reloads its speed performance get fast but after sometimes chart performance gets so slow even all the js functionality also gets so slow due to the chart. which is I'm using for the front end http://binvestic.com/. You can check here chart.

2). The second problem is that you I'll notices when you look up the graph I'm using the range axis with the bullet which is showing at from of the line the range axis line and front bullet not moved at the same time. Let me know what's the problem is.

3). Zoom in and zoom out not working.

**Comment by martynasma** [comment]
I'm sorry, but debugging custom set ups is beyond the scope of this place. If you have a specific bug to report, or have a question, please post a standalone example of the chart in question. One question per issue please.
