### ISSUE TITLE
Line marker across multiple axis.

### ISSUE THREAD

**Issue by Chriztiaan** [amcharts/amcharts4#2972]
Hey guys,
I have a single chart which has 2 vertically stacked value axis as in the picture.

![image](https://user-images.githubusercontent.com/13052031/94962018-0fe40600-04f6-11eb-8833-fbe6a07a62ad.png)
 
I am trying to display/render the red line as marker which I can move programmatically. I've fiddled with bullets but I don't think that's I what I should be using. Perhaps something like a static XYCursor, but I don't think I can have two cursors on a single chart. Any thoughts?

**Comment by martynasma** [comment]
How about axis range?

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides

**Comment by Chriztiaan** [comment]
I've tried that.

If I do use the following code I get this:

let range = valueAxis.axisRanges.create();
range.value = 5;
range.endValue = 10;

![image](https://user-images.githubusercontent.com/13052031/94994093-be8b5380-0595-11eb-9a0e-393ffb93590b.png)

How can I constrain the red area to some range of x?

**Comment by martynasma** [comment]
So basically you need to create a square somewhere within plot area?

Axis range won't work for that.

You would need to create a separate `LineSeries` with a fill and set its own `data`.

How that data looks depends on your actual X axis type. Here's an example using `DateAxis`:

https://codepen.io/team/amcharts/pen/gOrVJqj
