### ISSUE TITLE
Change chart type from line to candlestick on click

### ISSUE THREAD

**Issue by mianSaif** [amcharts/amcharts4#2973]
Hi there, I'm working on a live data amcharts. I want functionality like I want to show a popup in which 2 chart layout will show one is a candlestick chart second is a bar chart. When I'll click on the candlestick chart my live data amchart will convert into a candlestick chart and when bar it will be in a bar chart. Let me know is there any plugin which amcharts provide to convert chart type from one chart to another in the same chart as i want discussed above. 
Thanks.

**Comment by martynasma** [comment]
There's no way to dynamically switch the type of the series.

In your case the obvious solution is to have two series - column and candlestick - pre-created, with one hidden initially.

Once user switches the type, you hide one and show another.

You may also need to toggle `hiddenInLegend` setting so the hidden series is not represented in legend if you have one.

To show/hide series, simply call its `show()` or `hide()` method.

**Comment by mianSaif** [comment]
Is there any documentation available to pre_create two series. Knidly share the link thanks.

**Comment by martynasma** [comment]
It would be just like creating a regular series, except you hide it initially:

```
series2.hide();
series2.hiddenInLegend = true;
```

Once you want to show it you:

```
series2.show();
series2.hiddenInLegend = false;
```
