### ISSUE TITLE
How to add specific interval line in chart

### ISSUE THREAD

**Issue by mianSaif** [amcharts/amcharts4#2974]
![expiration-time-line](https://user-images.githubusercontent.com/68012827/94979886-f9ae6800-053e-11eb-8016-3a76d84dedac.PNG)
Hi there, I'm using a live data amcharts. I want to add a specific interval line as shown in the image. This interval line will show after a specific time that I will set. Let me know is there any feature or plugin which support that as I want.
Thanks

**Comment by martynasma** [comment]
How about axis range?

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides

**Comment by mianSaif** [comment]
I have noticed I can fill color in a specific area. But can I create also a verticle line like as shown in image start and finish?

**Comment by Chriztiaan** [comment]
It is my understanding that an axis range for a ValueAxis will create horizontal lines and that an axis range for a CategoryAxis wil create vertical lines.

**Comment by martynasma** [comment]
Adding an axis range to a horizontal axis will add vertical lines/bands, whereas adding a range to vertical axis will create horizontal lines/bands.

The actual type of axis is not important, you can add ranges to any axis.
