### ISSUE TITLE
amcharts animation behave wired with Wordpress Twenty Twenty theme

### ISSUE THREAD

**Issue by shichenglu** [amcharts/amcharts4#2975]
Hi,

I am designing a new site with wordpress+amcharts and found a wired issue regarding the animation, with Twenty Twenty theme, the animation looks like quite different as normal, you can check this live demo here https://petbyus.com/36538/
Switch to another theme will solve the problem, wondering what causes this problem.
Thanks,

Lucas

**Comment by martynasma** [comment]
There are no errors, and no obvious indications of what might be causing this.

The theme might be overriding something, but I'm afraid debugging WP themes is a bit out of scope.
