### ISSUE TITLE
DateAxis rotation

### ISSUE THREAD

**Issue by habib3962** [amcharts/amcharts4#2976]
in line graph time interval is showing horizontally.
but ending minute showing in vertical view.

i want every time to show in horizontal view.

see attachment
![Screenshot (50)_LI](https://user-images.githubusercontent.com/60214489/94987239-3f3e5580-057e-11eb-8992-e56ba1a7923f.jpg)

thanks.

**Comment by martynasma** [comment]
I'm not sure how one label out of many would show as vertical. It's not a built-in behavior.

Do you have your chart online somewhere?
