### ISSUE TITLE
Series tooltip issue with zoomToIndexes/zoomToCategories

### ISSUE THREAD

**Issue by ramix1235** [amcharts/amcharts4#2978]
Once a second, the data in the chart is updated, and sometimes the tooltip disappears when the chart is zoomed. How to avoid this and display tooltip always?

without zoomToIndexes/zoomToCategories:
![chrome-capture-1](https://user-images.githubusercontent.com/19249303/95094638-c92f1f80-0732-11eb-8fc4-56153804e4a7.gif)

with zoomToIndexes/zoomToCategories:
![chrome-capture-2](https://user-images.githubusercontent.com/19249303/95094655-ce8c6a00-0732-11eb-965d-1d9e6872eed0.gif)

playground: https://codepen.io/Ramix1235/pen/JjKPYQa

**Comment by martynasma** [comment]
try adding this:

```JavaScript
series.hideTooltipWhileZooming = false;
```

**Comment by ramix1235** [comment]
> try adding this:
> 
> ```js
> series.hideTooltipWhileZooming = false;
> ```

looks like it works, thanks
