### ISSUE TITLE
axis tooltips not showing on correct bullet when using ValueAxis together with CategoryAxis in Series

### ISSUE THREAD

**Issue by CristianoYL** [amcharts/amcharts4#2983]
I'm trying to create an XYChart where my X-axis is an ValueAxis and my Y-axis is a CategoryAxis. And what I want to achieve is that when the user hovers over each bullet, a tooltip will show up on that bullet, together with tooltips on x,y axes too. 

The bullet tooltip always shows up at correct places, but the x-axis tooltip usually shows up at wrong places.
![image](https://user-images.githubusercontent.com/17320996/95266119-6d729e00-07e7-11eb-8b69-89e8ad157f15.png)

Everything works as expected when I'm using ValueAxis for both Axes.

Here's a code pen for a repro: [CodePen](https://codepen.io/CristianoYL/pen/qBNBBbm)

FYI:
- I refactored the ZoomableBubbleChart from the Amcharts demo page by changing y-axis to CategoryAxis and used some simple mock data.
- I noticed that if I click the bullet when the x tooltip shows up at the wrong place, the x tooltip will briefly move to the correct place and goes back to the wrong place.
- I need to use `snapToSeries` since real data has precision requirement and the non-snapped tooltip can be misleading.
- I'm not sure if it's a bug or I misconfigured somewhere so I posted it as a question.

Thank you.

**Comment by CristianoYL** [comment]
@martynasma Thanks for your response. But it doesn't seem to work. The `cursorTooltipEnabled` seems to take effect on axes instead of series, and that's not what I intended anyway.

I'm hoping to show the tooltips on axes and when hovering on a particular bullet, the tooltip should be fixed to that bullet's x and y instead of showing a dynamic value corresponding to the cursor's (it's what `chart.cursor.snapToSeries = series` is supposed to do). I added `extraTooltipPrecision` to the x-axis in the CodePen so that it's more obvious.

**Comment by martynasma** [comment]
Well, snapping of cursor to bullet won't work because you have multiple data items with the same category, so it will always snap to the first data item within category, not the closest one.

Few solutions:

1) Have multiple series, so that each series has only data item per series.
2) Switch to some other axis setup, e.g. where both axes are `ValueAxis`.

**Comment by CristianoYL** [comment]
> snapping of cursor to bullet won't work because you have multiple data items with the same category, so it will always snap to the first data item within category, not the closest one

This does not like the desired behavior. When snapping to series, shouldn't it check both axes? Although there are multiple matching categories (y-axis), there should be only one matching value on x-axis.

**Comment by martynasma** [comment]
It's a niche case, and supporting it would require implementing complex fuzzy logic. It's something we are desperately trying to avoid.

I'm afraid we won't be able to provide a transparent solution for this. Sorry.
