### ISSUE TITLE
Label on specific value in with custom text

### ISSUE THREAD

**Issue by mianSaif** [amcharts/amcharts4#2984]
![label](https://user-images.githubusercontent.com/68012827/95292993-065af500-088c-11eb-9ad1-b3ed0cda63a9.PNG)

Hi, there I'm using live data amchart.i want to create a label with a customs value on a specific value in a chart and want to remove that label after a specific time. How can I do this? I want achieve this on a click when I will on a button then this label will place on that latest value which is come in chart. To better understand I have attached an image. hope you understand my question.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
