### ISSUE TITLE
Replacing the default behavior on chord diagram node click

### ISSUE THREAD

**Issue by YannCami** [amcharts/amcharts4#2985]
Hello,

I am using amCharts to create a simple chord diagram. I would like to define a custom behavior when the user clicks on a node.

To this end, I would also like to disable the default behavior of collapsing a node when it is clicked.

How should I proceed? The documentation mentions setting `nodeTemplate.clickable = false;` This does not fit my use-case as I wish to still be able to use the `hit` event.

**Comment by martynasma** [comment]
Try this instead:

```
nodeTemplate.events.off("hit");
```

This must go before adding your own custom hit event handlers.

**Comment by YannCami** [comment]
Thank you! This is indeed what I was looking for.

**Comment by oneill479** [comment]
This helped me thank you @martynasma
