### ISSUE TITLE
remove repeated axis, hide value axis and show only value, merge multiple cursor tooltip

### ISSUE THREAD

**Issue by gaurav30-hkr** [amcharts/amcharts4#2986]
**Question**

I am plotting 2 types of graph together due to which value axis is getting repeated twice or thrice.

Is there any property if 
1. one can merge value axis together
I tried with setting dy, is ther any property of graph that it could be set to achieve the required result.

2. Hide the black color vertical line and show only values.
tried with  
valueAxis2.disabled = true;
but it is removing the corresponding graph

3. merge the 2 cursor tooltip into single

**Environment (if applicable)**
Angular and typescript

**Additional context**

![image](https://user-images.githubusercontent.com/44194164/95315121-b8f07f00-08af-11eb-8ca6-85ce8888fa39.png)

**Comment by martynasma** [comment]
If you want to hide tooltip from an axis, you can set its `cursorTooltipEnabled = false`.

"merging" axes inadvisable, as it would look like a mess.

Merging tooltips is possible using `getTooltipText` adapter:

```
axis.adapter.add("getTooltipText", function(text, target) {
  var cursorPosition = chart.cursor.yPosition;
  return text + " : " + series2.yAxis.getTooltipText(cursorPosition);
});
```

Here's an example:
https://codepen.io/team/amcharts/pen/MWeWvKp

**Comment by gaurav30-hkr** [comment]
Thanks @martynasma for your quick response.
 Do you have any suggestion on how to approach

Data format : 
[
{
AreaA1: 33.2
AreaA2: 31
AreaB1: 57
AreaB2: 5
Line_1: 6.2
Line_2: 5.2
LineA_1: 14.7
LineA_2: 4.7
Time: "2020-08-29"
},
{
AreaA1: 34.2
AreaA2: 32
AreaB1: 58
AreaB2: 54
Line_1: 18.2
Line_2: 3.2
LineA_1: 11.7
LineA_2: 1.7
Time: "2020-08-30"
},
{
AreaA1: 35.2
AreaA2: 33
AreaB1: 59
AreaB2: 50
Line_1: 8.2
Line_2: 12.2
LineA_1: 4.7
LineA_2: 14
Time: "2020-08-31"
}
]

using one chart series for :
Line_1 and Line_2
LineA_1 and LineA_2 

using another chart series for : 
AreaA1, AreaA2 
and AreaB1, AreaB2

they are being called through function : 
createAxisAndSeries(Line detail , time, Area 1, Area 2 );

Do you have any suggestion on its approach on how to proceed ahead.
in case you need further related information. Please let me know

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
