### ISSUE TITLE
Export in CSV with column names as "name" not "valueY"

### ISSUE THREAD

**Issue by Julienh** [amcharts/amcharts4#2989]
Hello, 

I have a chart with some series like : 
```
let series = chart.series.push(new am4charts.ColumnSeries());
series.name = "PlayStation 5";
series.dataFields.valueY ="ps5";
```

When I export the chart in CSV, the column names are the value of "series.dataFields.valueY", how can I change to the name please (series.name) ? 

I didn't find the information in the documentation.

Thank you

**Comment by martynasma** [comment]
Did you perhaps check here? ;)

https://www.amcharts.com/docs/v4/concepts/exporting/#Changing_order_and_names_of_columns

**Comment by Julienh** [comment]
I was thinking of an option that use the name that I already set to the series.
I will use dataFields, thanks :)
