### ISSUE TITLE
PinBullet hover zIndex doesn't work

### ISSUE THREAD

**Issue by MitchelGuy** [amcharts/amcharts4#2990]
Hi,

I have tried to get the hover on a PinBullet to change the zIndex on hover so that when they overlap you can see the overlapped PinBullet by hovering over it.

This is my code below. It works to set the scale as per your demo but not zIndex.

var pin = imageTemplate.createChild(am4plugins_bullets.PinBullet);

var hoverState = pin.states.create("hover");
hoverState.properties.zIndex = 10;

**Comment by martynasma** [comment]
Could you provide more info about your set up? What kind of series are those? Are there multiple series, or just one?

If you could also post your full working chart on CodePen/jsFiddle that would go a mile towards us coming up with a solution.
