### ISSUE TITLE
MapPolygonSeries and `calculatePercent`: `{percent}` data placeholder doesn't work

### ISSUE THREAD

**Issue by clintharris** [amcharts/amcharts4#2991]
Setting `calculatePercent = true` on a `MapPolygonSeries` doesn't seem to add a `percent` property that can be referenced as a data placeholder. Is this expected? Perhaps there is a different placeholder that should be used?

**Comment by martynasma** [comment]
You need to refer to the percent of the specific value in your placeholder. This will work `{value.percent}`.
