### ISSUE TITLE
Issue 2268 is back

### ISSUE THREAD

**Issue by luke1961** [amcharts/amcharts4#2994]
**Bug description**

I have noticed that there is some sort of a problem with your javascript file located here:

http://cdn.amcharts.com/lib/4/plugins/wordCloud.js

If you open this file you are going to see a large block of ‘garbage’ characters causing an exception looking like this under Chrome debugger:

Uncaught SyntaxError: Invalid regular expression: /([A-Za-zÂªÂµÂºÃ€-Ã– ...(more garbage characters follow)

Of course, the word cloud fails to display. The above is exactly as someone reported before:

https://github.com/amcharts/amcharts4/issues/2268

Any ideas?

**Comment by martynasma** [comment]
Do you have any specific demo that is failing with errors?

I checked a few of those and don't see any error.

https://www.amcharts.com/demos/word-cloud/
https://www.amcharts.com/demos/changing-data-word-cloud/
https://codepen.io/team/amcharts/pen/qvWBRd

**Comment by ddietzel** [comment]
I'm also having this issue
<img width="358" alt="Screen Shot 2020-10-13 at 7 59 14 AM" src="https://user-images.githubusercontent.com/2907730/95878425-0cd4eb00-0d2a-11eb-9ade-c8ac9903fab7.png">

**Comment by luke1961** [comment]
I apologize for the late answer to the request to produce an example demonstrating the problem. The issue disappeared after I converted my html and css files to UTF-8 and added BOMs to those files

**Comment by luke1961** [comment]
Also, use your browser (I used Chrome) and enter https://cdn.amcharts.com/lib/4/plugins/wordCloud.js in the address bar. The JS file will be displayed. Are all of those special characters supposed to be there? Some sort of encrypted or encoded section to be unpacked at runtime? I am not sure and had to time to study this code.
![wordcloud js](https://user-images.githubusercontent.com/6032592/95884226-d9a25400-0d49-11eb-9d89-8f7d8f0155d3.jpg)

**Comment by martynasma** [comment]
Well, the JS files do not carry any encoding information, like HTML files do. However, they are not actually meant to be viewed in browser window directly, but rather used by interpreter.

I'm not sure what to suggest for using on non-UTF8 pages, though :(

**Comment by luke1961** [comment]
Well, javascript files are just text files and Chrome displays them as text files when opened the way I did. So, if you see garbage characters there is an issue unless the file has encoded or encrypted sections that are to be unpacked at runtime. Usually this is done to protect intellectual property of for nefarious reasons to hide malicious code.

**Comment by ddietzel** [comment]
@martynasma solved it for me accidentally, in the header you have to add <meta charset="UTF-8"> - we did this on our website to support chinese characters but forgot to add it to our app because it's coded by hand.

**Comment by ddietzel** [comment]
It's part of a regex string - Regular expressions are not javascript specific - they're a layer deeper than that. It works in codepen because it's set to UTF 8

<img width="297" alt="Screen Shot 2020-10-13 at 11 04 44 AM" src="https://user-images.githubusercontent.com/2907730/95898462-ee7be900-0d43-11eb-8acc-1ad134e2f8d0.png">


![Screenshot_of_MediaWiki_Blacklist](https://user-images.githubusercontent.com/2907730/95898358-c5f3ef00-0d43-11eb-9f34-e06854dcc88c.png)

**Comment by luke1961** [comment]
@ddietzel Do you think this string has something to do with matching all kinds of international characters for the purpose of parsing out words as needed by the word cloud widget? I think so now. I also think the code would be able to avoid dependency on UTF-8 encoded html files if the chars were hex encoded using \xcccc instead of UTF-8 encoded.

**Comment by ddietzel** [comment]
Yes, I would ask @martynasma but most likely they are removing crazy characters that would make the rendering malfunction. I also don't know enough about regex to comment - just know that's what it's doing.

**Comment by luke1961** [comment]
@martynasma I think that adding UTF-8 BOM to wordclud.js could solve the problem for non-UTF8 customers

**Comment by martynasma** [comment]
We're going to look into it. Thanks.

Will keep you posted.
