### ISSUE TITLE
Using adapter to modify tooltip fill based on value

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#2996]
**Question**

I currently have an adapter that modifies the column fill based on the target.dataItem.ValueY and it works as required.

I now want to add a second adapter that modifies the fill of tooltips based on the same value.

I am using the code for both adapters is below,

hourlyVarianceSeries.columns.template.column.adapter.add("fill", function(fill, target) {
				var value = target.dataItem.valueY;
				if (isNaN(value)) {
					return am4core.color("#421C52");
				} else if (value < 0) {
					return scope.config.hourlyVarianceNegativeColour;
				} else {
					return scope.config.hourlyVariancePositiveColour;
				}
			});

hourlyVarianceSeries.tooltip.background.adapter.add("fill", function(fill, target) {
				var value = target.dataItem.valueY;
				if (isNaN(value)) {
					return am4core.color("#421C52");
				} else if (value < 0) {
					return scope.config.hourlyVarianceNegativeColour;
				} else {
					return scope.config.hourlyVariancePositiveColour;
				}
			});

The issue is that the adapter for the tooltips always return the the colour #421C52. The tooltip labels correctly show the value and the column fill adapter gets the value as a number.

Is there any reason why the 2nd adapter can't get the correct value for modifying the fill?

Thanks

Iain

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
The problem is that series reuses same tooltip object for all columns. Once it's drawn, it's drawn. The `fill` adapter for its background never kicks in again.

You can work around it by tapping into tooltip's property that DOES change, like `x`, then setting background color explicitly:

```JavaScript
series.tooltip.getFillFromObject = false;
series.tooltip.adapter.add("x", function(x, target) {
  var value = target.dataItem.valueY;
  if (isNaN(value)) {
    target.background.fill = am4core.color("#421C52");
  } else if (value < 0) {
    target.background.fill =  scope.config.hourlyVarianceNegativeColour;
  } else {
    target.background.fill =  scope.config.hourlyVariancePositiveColour;
  }
  return x;
});
```

Or use a column event:

```JavaScript
series.tooltip.getFillFromObject = false;
series.columns.template.events.on("over", function(ev) {
  var value = target.dataItem.valueY;
  if (isNaN(value)) {
    series.tooltip.background.fill = am4core.color("#421C52");
  } else if (value < 0) {
    series.tooltip.background.fill =  scope.config.hourlyVarianceNegativeColour;
  } else {
    series.tooltip.background.fill =  scope.config.hourlyVariancePositiveColour;
  }
})
```

**Comment by mfones** [comment]
Test message to see where this goes.

Please reply back, very interested in amCharts.

 

-=Mike=-
