### ISSUE TITLE
Date Axis and Category Axis reverse order for RTL

### ISSUE THREAD

**Issue by AhmedSayed77** [amcharts/amcharts4#2999]
**Question**

I'm making an arabic web application. I followed everything on the RTL support documentation page, and it worked fine, until I want to make an XY chart. I wanted the y-axis to be on the right - which is also documented, and working as intended - and the x-axis to be drawn from right to left - which I couldn't do. For category axes there's a work around, which is to reverse the data source, but for the date axis, I didn't find anything on how to do it. Can it be done?

**Comment by xorspark** [comment]
You can set [`inversed`](https://www.amcharts.com/docs/v4/reference/axisrenderer/#inversed_property) to true in the axis' renderer to flip the scale to descending order.

```
dateAxis.renderer.inversed = true;
```

**Comment by AhmedSayed77** [comment]
That worked, thanks a lot
