### ISSUE TITLE
Axis tooltip shows wrong date information

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#30]
This might be related to #27.

When I enable the XYCursor on a line chart with a DataAxis, the xAxis is showing the wrong values on the tooltip. All of the tooltips are off by 30 minutes. Instead of showing 8:00 - 16:00, when mousing over the chart it's showing values from 8:30 - 16:30:

https://codepen.io/anon/pen/KRrqGw

You can see the behavior here:

![ezgif-4-5e6305be0b](https://user-images.githubusercontent.com/900497/40196098-771a601a-59dd-11e8-8ca6-60a348cec001.gif)

**Comment by martynasma** [comment]
It's probably not related to #27 because yours does not use `skipEmptyPeriods`.

Thanks for the heads up. Going to investigate.

**Comment by dswitzer** [comment]
@martynasma 

The only reason I said they might be related, is I noticed I changed the ```dateAxis.skipEmptyPeriods``` to ```false``` the xAxis tooltip doesn't align with the correct label text. If you change the value to ```false``` and mouse over where the "Aug 30" is, the tooltip doesn't change to "Apr 30" until you're to the right of the label. Actually, when I hover over "Apr 30" the tooltip says "Apr 29".

They certainly could be completely unrelated.

**Comment by martynasma** [comment]
Still trying to figure this out.

Technically, the tooltip is right. It is drawn in the middle of the hour, hence `xx:30`.

While labels show time for the hour start, but they are aligned to the middle as well.

This is confusing to the user, but technically logical from the chart standpoint.

Working around all of those contingencies would require some fuzzy logic, which we are trying to avoid.

Just wanted you to know it's a process, not a simple fixable bug.

Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.26](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.26)

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta26---2018-05-30).
