### ISSUE TITLE
Dataset for morphing countries chart

### ISSUE THREAD

**Issue by zaombr** [amcharts/amcharts4#3001]
Hello, could you help me please with dataset for morphing countries chart (https://codepen.io/team/amcharts/pen/LQKExW).
I want dataset for this chart in json format like {id: "somecountry-ID", value: [  { value: 100, category: "First" },  { value: 20, category: "Second" },  { value: 10, category: "Third" } ], info: "someinfo"} or similar.
So I want to set specific numbers for the list of regions of the country. Is it possible?

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).

**Comment by jswelsh** [comment]
@zaombr are you requesting specifically the geojson/json for this dataset or are you asking how to modify the json into that structure?

**Comment by zaombr** [comment]
> @zaombr are you requesting specifically the geojson/json for this dataset or are you asking how to modify the json into that structure?

Json for this dataset.

**Comment by jswelsh** [comment]
If I'm not mistaken, it would be this [`country JSON`](https://www.amcharts.com/lib/4/geodata/worldLow.js#). It includes the polygon coordinates.

**Comment by zaombr** [comment]
I mean DATASET like this 
{id: "somecountry-ID", value: [ { value: 100, category: "First" }, { value: 20, category: "Second" }, { value: 10, category: "Third" } ], info: "someinfo"} .......
