### ISSUE TITLE
How to make serpentine timeline to be a straight horizontal line

### ISSUE THREAD

**Issue by wesleychew** [amcharts/amcharts4#3004]
How to make serpentine timeline to be a straight horizontal line?

https://www.amcharts.com/demos/serpentine-timeline/

I've tried `chart.levelCount = 1;` but its not working

**Comment by martynasma** [comment]
If you need a straight line, why not just use `XYChart` instead? :)

**Comment by wesleychew** [comment]
I see ok. Thanks! 👍
