### ISSUE TITLE
Chart padding where removed logo was is not reduced after adding license key

### ISSUE THREAD

**Issue by manwithtwowatches** [amcharts/amcharts4#3005]
After adding my license key to remove the logo from the charts, I was hoping that the vertical space taken up by the logo would be utilised for the chart. Instead the chart is exactly the same, and the vertical space where the logo was is just blank wasted pixels in the form of padding. Is there some way I can make the chart expand vertically to more efficiently use all the space available?

**Comment by martynasma** [comment]
The logo is placed over the chart and does not affect chart's layout in any way.

What you probably seeing is a default bottom padding of the chart. You can disable it like this:

```
chart.paddingBottom = 0;
```
