### ISSUE TITLE
Cannot read property globalScale of undefined

### ISSUE THREAD

**Issue by applecool** [amcharts/amcharts4#3006]
**Question**

Hi all,

I have a bar chart which can be manually reordered by dragging around. Whenever I drop the bar in a different position, I do `categoryAxis.invalidateData()` in order for the am charts to take care of the labelling on the category axis especially when there is a `minGridDistance` attribute set. 

I get the following error: 
`Cannot read property globalScale of undefined`
<img width="561" alt="Screen Shot 2020-10-14 at 7 57 07 PM" src="https://user-images.githubusercontent.com/1661749/96072008-22483300-0e58-11eb-84cf-9eb792446460.png">

This error occurs intermittently and sometimes on the very first attempt of dragging the bar around. And sometimes after 3 or 4 attempts of drag. 

**Note**: This error is happening only when there are hidden labels on the category axis. If we have `minGridDistance` set to `0` i.e., we show all the `x` no of `labels` for `x` no of `bars`, this error doesn't occur. 

The other question I have is: 
Even though the `interpolationDuration` is set to `0`, I am getting a bit of lag when I drag the bar around too fast i.e., the `invalidateData()` is not happening too fast. 

Here is the [Codepen](https://codepen.io/applecool/pen/MWeKoJX?editors=0010)

Any help is hugely appreciated. 

**Environment (if applicable)**
amCharts version 4 - 4.9.24
Chrome 86

**Comment by applecool** [comment]
@martynasma

**Comment by zeroin** [comment]
Hi,

Invalidating data causes the Sprites to be disposed, so I am not surprised errors happen, as you are interacting with some of the sprites. Here is a pen where dragging is made without invalidating data:

https://codepen.io/team/amcharts/pen/yLJezZo

**Comment by applecool** [comment]
@zeroin Okie. Thank you for that but how do you suggest in getting the hidden label of the bar on the category axis to appear if I am not using the invalidateData() ? For example in my code pen, If I move the bar with label 1 to the second position (i.e., the bar which doesn't have the label), I want to get the label 2 which was previous hidden to be shown. 

Here's the codepen without the invalidateData() : https://codepen.io/applecool/pen/MWeKoJX?editors=0010

**Initial state**: Label 2 is hidden because of the minGridDistance

<img width="1659" alt="Screen Shot 2020-10-14 at 11 03 33 PM" src="https://user-images.githubusercontent.com/1661749/96083351-defabe00-0e71-11eb-9b14-202af68e1532.png">

**Final state**: I dragged and moved the bar 1 to the bar 2 position. So bar 1 and 2 have been swapped. Now, it looks as follows. How can I get the Label 2 to reappear? 

<img width="1752" alt="Screen Shot 2020-10-14 at 11 03 51 PM" src="https://user-images.githubusercontent.com/1661749/96083357-e0c48180-0e71-11eb-8519-2a8b921193ac.png">

**Comment by zeroin** [comment]
In this case I would make sure all the labels are create by setting minGridDistance to some small number and then manually showing/hiding every X label after the sorting is done.

**Comment by applecool** [comment]
@zeroin thank you for the suggestion :)
