### ISSUE TITLE
Set (Suggested) Min & Max unless value exceeds it.

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#3007]
Is it possible to set a suggested minimum and maximum for the valueAxis which also allows adjusting the axis is a value is larger? e.g. a min max of -3 & 3, but if a dataset has a value of 9 then the max changes to 10?

**Comment by martynasma** [comment]
Not, with a single setting.

It's possible to emulate with events:

```JavaScript
valueAxis.events.on("datavalidated", function(ev) {
  var axis = ev.target;
  if (axis.min > 0) {
    axis.min = 0;
  }
  if (axis.max < 1000) {
    axis.max = 1000;
  }
});
```

**Comment by Josh10101010** [comment]
Thanks, really straightforward solution!
