### ISSUE TITLE
Adding LabelBullet/AxisLabelCircular to pie charts won't appear when embedded in a map chart

### ISSUE THREAD

**Issue by RichardCosta10** [amcharts/amcharts4#3008]
Please see examples taken from amcharts demos where I've added an extra label to the pie charts.

[Works on a single pie chart](https://jsfiddle.net/Lzqvtmdw/9/)

[Doesn't work on charts embedded within the map](https://jsfiddle.net/mzwp61cd/3/)

Only additional code I've added to the examples is

```javascript
var label = pieSeries.bullets.push(new am4charts.AxisLabelCircular());
label.text = "TESTING";
label.stroke = am4core.color("black");
```

**Comment by martynasma** [comment]
Adding this seems to fix it:

```
label.showOnInit = true;
```

**Comment by RichardCosta10** [comment]
Thanks marty
