### ISSUE TITLE
Group data bug on small dataset

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#3009]
I have a chart with a DateAxis and 10 data points. If my users enable 'groupData' it looks strange. Please see the screenshots below.

**Group data disabled**
![image](https://user-images.githubusercontent.com/2857604/96245271-0bf8bf00-0f9f-11eb-8a25-eb26b2e025cd.png)

**Group data enabled**
![image](https://user-images.githubusercontent.com/2857604/96245191-f5eafe80-0f9e-11eb-9875-c4553c873150.png)

My understanding was that, by default, this only kicked in when there were over 200 values? 

1. It seems to have grouped values together from the same _day_. Is that expected?
2. Notice how the tooltip displays a different date/time altogether.

Here is a CodePen with my example: https://codepen.io/jbate/pen/RwRaRyr?editors=0010

**Comment by martynasma** [comment]
When talking about when grouping kicks in is important to understand that `groupCount` is not "number of actual data points" but rather "number of time units within selected range".

Now, time units depend on granularity of your data. If you have data points on the same day you can't rely on chart to reliably determine granularity of your data. You will need to specify it yourself using `baseInterval`.

With your data configuration, the chart detects it as "day". There are more days from 25-Aug-2018 to 11-Apr-2019 than 200 hence grouping kicks in.

There is no way to enable grouping by number of data points.

You can set `baseInterval` to something else, e.g. a month. In such case grouping would not be kicking in.

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Manually_specifying_data_granularity

I hope that makes sense.

**Comment by jbate** [comment]
Ah yes! That does make sense now, thank you. Until now, I've always interpretted the date grouping to mean number of data items rather than the time units. Knowing this definitely helps to explain what was happening.

What about the tooltip though? When grouping is enabled why does it display a tooltip for the first point as 20-Aug-2018 instead of 25-Aug-2018?

**Comment by martynasma** [comment]
> What about the tooltip though? When grouping is enabled why does it display a tooltip for the first point as 20-Aug-2018 instead of 25-Aug-2018?

Most probably your chart in that moment is grouping items into weeks. A week is represented by the first date in that week. For week of 25-Aug-2018, Monday is 20-Aug-2018, hence it being displayed in tooltip.

**Comment by jbate** [comment]
You're right. That was it. 

I think I'm clear on this now. It's the 200 threshold being the number of time units _not_ data items that threw me.

Thank you for getting back to me so quickly. Much appreciated!
