### ISSUE TITLE
Chart freezes if XYCursor hovers over DateAxis' cell with no data item

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#301]
Example:
https://codepen.io/team/amcharts/pen/9d9ad5201ef8625b918bab945c8dc0cb?editors=0010

Hover over Apr 25 to reproduce.

**Comment by martynasma** [comment]
We've been able to fix this and will release an update soon. (within couple of days)

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.48](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.48).

## [4.0.0-beta.48] - 2018-08-31

### Added
- `useWebFonts` setting in `Export`. Allows disabling of download of web fonts when exporting.
- `useRetina` setting in `Export`. Images are now exported scaled up on retina displays by default. Set `useRetina = false` to disable.

### Changed
- Export fallback mechanism for older browsers changed from FabricJS to canvg, which is much lighter and has better text formatting support.
- On retina displays images will now export supersized in order not to lose quality. Set `useRetina = false` to disable.
- amCharts logo will now auto-hide on supersmall chart sizes.

### Fixed
- Cursor was zooming the chart even if drag motion was performed on an external element positioned over the chart.
- Cursor was not hidden when it was no longer hovering the chart area if chart had no padding.
- `urlTarget` was not carried over from `ListTemplate` template to new items.
- Cursor could cause chart to freeze up on a DateAxis with empty cells in the axis' beginning or end.
- Export will now correctly handle web fonts, such as Google Fonts. Please note that FontAwesome is not supported, since they forbid any kind of usage, except inclusion via CSS.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by ptorrent** [comment]
Not working with last release :

https://codepen.io/ptorrent/pen/LJWQEd

**Comment by martynasma** [comment]
Working fine for me. Have you cleared your browser cache?

**Comment by ptorrent** [comment]
Yes it was the cache ! sorry
