### ISSUE TITLE
line-chart is not rendering and cause fxLayout malfunction

### ISSUE THREAD

**Issue by mjsaijem09** [amcharts/amcharts4#3013]
Hi I really want to implement your line-chart in my project but the browser wont render it and also cause my fxLayout to malfunction when I add it in my html. Need your help.

comment div
`<!-- <div class="line-chart" [id]="lineData.chartId"></div> -->`

![image](https://user-images.githubusercontent.com/50950599/96361067-2d031080-1155-11eb-8712-2f77e8842978.png)

uncomment div
`<div class="line-chart" [id]="lineData.chartId"></div>`

![image](https://user-images.githubusercontent.com/50950599/96361083-59b72800-1155-11eb-8fb1-9566fbff065a.png)

**Comment by mjsaijem09** [comment]
@martynasma need your guide

**Comment by martynasma** [comment]
I'm sorry, but we don't have the capacity to debug user apps. If you do have support subscription, please contact our support at contact@amcharts.com. Otherwise, I'm just going to leave this here, in case someone have had similar issue with your setup and know precise solution.
