### ISSUE TITLE
select onChange event not fired when over a chart

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [amcharts/amcharts4#3014]
**Bug description**

It seems that when you have a select which drop down goes over a chart, then clicking on the option fails to trigger the "onChange" event (in Internet Explorer 11).

Instead it goes with the pointerDown event handled by amcharts that starts the UI to select a time frame to zoom on (see gif below)

![example](https://user-images.githubusercontent.com/11965035/96477591-fd2c3980-1236-11eb-9038-31b81f3d219c.gif)

**Expected**

In that case, the event should not be grabbed, and let the browser continue with the trigger of the onChange.

**Environment**

internet explorer 11.0.9600

On Chrome or other chromium browser (including Edge), it works as expected

**Comment by AdrienNguyenWorldline** [comment]
I am going to fiddle with the issue on my side. I will check if that still happen if I chance the cursor behaviours of the chart.
And try to disable amcharts when some start clicking on the select, then re-enable it (trough the "system" object of amcharts that can be paused/disabled)

**Comment by martynasma** [comment]
Good idea. It should be enough to disable interactivity of the chart's cursor:

```JavaScript
chart.cursor.interactionsEnabled = false;
```

Then re-enabled them when selection is complete:

```JavaScript
chart.cursor.interactionsEnabled = true;
```

**Comment by drallieiv** [comment]
When I put chart.cursor.interactionsEnabled = false; on IE, the cursor interaction disappear (no more value displayed on hover and such) but when I put it back to true, it does not come back
