### ISSUE TITLE
It's possible to remove year from x axis ?

### ISSUE THREAD

**Issue by rullymartanto** [amcharts/amcharts4#3016]
It's possible to remove year from x axis ?
I am using DateAxis for x axis...

Thanks
![image](https://user-images.githubusercontent.com/5577057/96536915-458f3a00-12bf-11eb-8bf5-73f6d04248b1.png)

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Period_change_format

**Comment by rullymartanto** [comment]
yes,.. I am using that
 xAxis.dateFormats.setKey("day", "MMM dd");
 xAxis.periodChangeDateFormats.setKey("day", "MMM dd");

But Only Works when I zoom it.

![amchart-zoom](https://user-images.githubusercontent.com/5577057/96541804-fcdd7e00-12ca-11eb-9d86-22d32b7b2b7c.PNG)

**Comment by martynasma** [comment]
You probably need to set formats for `"month"`, too.

**Comment by rullymartanto** [comment]
Awesome !  Thanks..
