### ISSUE TITLE
CurveColumnSeries corner radius 

### ISSUE THREAD

**Issue by gary258796** [amcharts/amcharts4#3018]
I'm trying to set my CurveColumnSeries to have rounded corner .
But after searching google , only find ways to set columnseries but curvercolumnseries.

here below is my code about carvercolumnseries

`

                
                var series = chart.series.push(new am4plugins_timeline.CurveColumnSeries());
                series.columns.template.height = am4core.percent(50);
                series.columns.template.width = am4core.percent(100);
                series.dataFields.openDateX = "start";
                series.dataFields.dateX = "end";
                series.dataFields.categoryY = "category";
                series.baseAxis = categoryAxis;
                series.columns.template.propertyFields.fill = "color"; // get color from data
                series.columns.template.propertyFields.stroke = am4core.color("#C34738");
                series.columns.template.stroke = am4core.color("#C34738");
                series.columns.template.strokeOpacity = 0.6;
                series.columns.template.strokeWidth = 2;
                series.columns.template.fillOpacity = 0.6;
                series.tooltip.pointerOrientation = "up";

`

If you do have some articles for me to read , please tell me !
I can't find any articles that I need for this .

**Comment by martynasma** [comment]
CurveColumnSeries does not have any corners by nature. They are smooth curves.

Example:
https://www.amcharts.com/demos/curved-columns/

Or do you need regular columns but with rounded columns?

In such case you can use corner radius settings on column template:

```
series.columns.template.column.cornerRadiusTopLeft = 10;
series.columns.template.column.cornerRadiusTopRight = 10;
```

Example:
https://www.amcharts.com/demos/column-with-rotated-series/

**Comment by gary258796** [comment]
@martynasma Thanks for your apply. 
Sorry that I didn't ask a good and clear question . 

https://www.amcharts.com/demos/linear-process-diagram/

Can you check the graph oh this amchart's website ?
What I want is to set the part's, where I circle inside attached image, corner radius.

<img width="569" alt="截圖 2020-10-21 下午2 57 46" src="https://user-images.githubusercontent.com/53204534/96684307-f96ef300-13ad-11eb-99c2-f746ef1c52a0.png">


And here is my charts result

<img width="1231" alt="截圖 2020-10-21 下午3 02 45" src="https://user-images.githubusercontent.com/53204534/96684671-8914a180-13ae-11eb-9db9-930d6ff3747e.png">

here below is the code about the amCharts 

`




             am4core.ready(function() {

             // Themes begin
             am4core.useTheme(am4themes_animated);
            // Themes end

            var water = someImagesrc...for bullet;
            var breakfast = someImagesrc....for bullet;
            var exercise = someImagesrc....for bullet;
            var car = someImagesrc....for bullet;

            am4core.ready(function() {
                var chart = am4core.create("chartdiv", am4plugins_timeline.CurveChart);
                chart.curveContainer.padding(0, 50, 0, 50);
                chart.maskBullets = false;


                var colorSet = new am4core.ColorSet();

                chart.dateFormatter.inputDateFormat = "yyyy-MM-dd HH:mm";
                chart.dateFormatter.dateFormat = "HH";

                chart.data = [{
                    "category": "",
                    "start": '2019-01-01',
                    "end": '2020-07-01',
                    "color": am4core.color("#ffffff00"),
                    "colorCircle": am4core.color("#C34738"),
                    'hidden': true,
                    disabledCircle: false
                },{
                    "category": "",
                    "start": '2019-01-01',
                    "end": '2019-05-01',
                    "color": am4core.color("#ff5a60"),
                    "colorCircle": am4core.color("#ffffff00"),
                    'hidden': true,
                    disabledCircle: true
                }, {
                    "category": "",
                    "start": '2019-03-01',
                    "end": '2019-03-01',
                    "color": colorSet.getIndex(14),
                    "colorCircle": am4core.color("#ffffff00"),
                    "icon": water,
                    "text": "Drink water",
                    'hidden': false,
                    disabledCircle: true
                },
                    {
                        "category": "",
                        "start": '2020-01-01',
                        "end": '2020-01-01',
                        "color": colorSet.getIndex(13),
                        "colorCircle": am4core.color("#ffffff00"),
                        "icon": exercise,
                        "text": "Exercise",
                        'hidden': false,
                        disabledCircle: true
                    },
                    {
                        "category": "",
                        "start": '2020-05-01',
                        "end": '2020-05-01',
                        "color": colorSet.getIndex(12),
                        "colorCircle": am4core.color("#ffffff00"),
                        "icon": breakfast,
                        "text": "Have breakfast",
                        'hidden': false,
                        disabledCircle: true
                    },
                    {
                        "category": "",
                        "start": '2020-07-01',
                        "end": '2020-07-01',
                        "color": colorSet.getIndex(11),
                        "colorCircle": am4core.color("#ffffff00"),
                        "icon": car,
                        "text": "Drive to work",
                        'hidden': false,
                        disabledCircle: true
                    }];

                chart.fontSize = 10;
                chart.tooltipContainer.fontSize = 10;

                var categoryAxis = chart.yAxes.push(new am4charts.CategoryAxis());
                categoryAxis.dataFields.category = "category";
                categoryAxis.renderer.grid.template.disabled = true;
                categoryAxis.renderer.labels.template.paddingRight = 25;
                categoryAxis.renderer.minGridDistance = 10;
                categoryAxis.renderer.innerRadius = 10;
                categoryAxis.renderer.radius = 30;

                var dateAxis = chart.xAxes.push(new am4charts.DateAxis());


                dateAxis.renderer.autoScale = true;
                dateAxis.renderer.autoCenter = false;
                dateAxis.renderer.minGridDistance = 70;
                //dateAxis.baseInterval = { count: 1, timeUnit: "month" };
                dateAxis.renderer.tooltipLocation = 0;
                //dateAxis.renderer.line.strokeDasharray = "1,4";
                dateAxis.renderer.line.disabled = true;
                //dateAxis.renderer.line.stroke = am4core.color("#ff5a60");
                dateAxis.renderer.line.strokeOpacity = 1;
                dateAxis.renderer.line.strokeDasharray = "1,4";
                dateAxis.tooltip.background.fillOpacity = 0.2;
                dateAxis.tooltip.background.cornerRadius = 5;
                dateAxis.tooltip.label.fill = new am4core.InterfaceColorSet().getFor("alternativeBackground");
                dateAxis.tooltip.label.paddingTop = 7;
                dateAxis.endLocation = 0;
                dateAxis.startLocation = -0.5;
                dateAxis.min = moment('2019-01-01');
                dateAxis.max = moment('2020-07-01');
                dateAxis.renderer.grid.template.disabled = true;

                var labelTemplate = dateAxis.renderer.labels.template;
                labelTemplate.verticalCenter = "middle";
                labelTemplate.fillOpacity = 0.6;
                labelTemplate.background.fill = new am4core.InterfaceColorSet().getFor("background");
                labelTemplate.background.fillOpacity = 0;
                labelTemplate.fill = new am4core.InterfaceColorSet().getFor("text");
                labelTemplate.padding(7, 7, 7, 7);
                labelTemplate.adapter.add("text", function(label, target, key) {
                    if (target.dataItem && target.dataItem.date) {
                        var targetDate = moment(target.dataItem.date).format('YYYY-MM');
                        var checkItem = _.find(chart.data, function(item) {
                            var startDate = moment(item.start).format('YYYY-MM');
                            if (startDate === targetDate) {
                                return true;
                            }
                            return false;
                        });
                        if (checkItem) {
                            return targetDate;
                        }
                        return '';
                    } else {
                        return '';
                    }
                });

                var series = chart.series.push(new am4plugins_timeline.CurveColumnSeries());
                series.columns.template.height = am4core.percent(50);
                series.columns.template.width = am4core.percent(100);

                series.dataFields.openDateX = "start";
                series.dataFields.dateX = "end";
                series.dataFields.categoryY = "category";
                series.baseAxis = categoryAxis;
                series.columns.template.propertyFields.fill = "color"; // get color from data
                series.columns.template.propertyFields.stroke = am4core.color("#C34738");
                series.columns.template.stroke = am4core.color("#C34738");
                series.columns.template.strokeOpacity = 0.6;
                series.columns.template.strokeWidth = 2;
                series.columns.template.fillOpacity = 0.6;
                series.tooltip.pointerOrientation = "up";

                /*var bullet = series.bullets.push(new am4charts.CircleBullet());
                bullet.circle.radius = 6;
                bullet.circle.strokeOpacity = 0;
                bullet.propertyFields.fill = "colorCircle";
                bullet.propertyFields.disabled = 'disabledCircle';
                bullet.locationX = 0;


                var bullet2 = series.bullets.push(new am4charts.CircleBullet());
                bullet2.circle.radius = 10;
                bullet2.circle.strokeOpacity = 0;
                bullet2.propertyFields.fill = "colorCircle";
                bullet2.propertyFields.disabled = 'disabledCircle';
                bullet2.locationX = 1;*/

                var imageBullet1 = series.bullets.push(new am4plugins_bullets.PinBullet());
                imageBullet1.background.radius = 18;
                imageBullet1.locationX = 1;
                imageBullet1.propertyFields.stroke = "color";
                imageBullet1.propertyFields.disabled = 'hidden';
                imageBullet1.background.propertyFields.fill = "color";
                imageBullet1.image = new am4core.Image();
                imageBullet1.image.propertyFields.href = "icon";
                imageBullet1.image.scale = 0.7;
                imageBullet1.circle.radius = am4core.percent(100);
                imageBullet1.background.fillOpacity = 0.8;
                imageBullet1.background.strokeOpacity = 0;
                imageBullet1.dy = -2;
                imageBullet1.background.pointerBaseWidth = 10;
                imageBullet1.background.pointerLength = 10;
                imageBullet1.tooltipText = "{text}";

                var textBullet = series.bullets.push(new am4charts.LabelBullet());
                textBullet.label.propertyFields.text = "text";
                textBullet.disabled = true;
                textBullet.propertyFields.disabled = "textDisabled";
                textBullet.label.strokeOpacity = 0;
                textBullet.locationX = 1;
                textBullet.dy = - 100;
                textBullet.label.textAlign = "middle";

                dateAxis.renderer.tooltipLocation2 = 0;
                categoryAxis.cursorTooltipEnabled = false;

                chart.zoomOutButton.disabled = true;
            });
        }); // end am4core.ready()


`

**Comment by martynasma** [comment]
Gotcha. Sorry, I assumed you were talking about `CurvedColumnSeries`.

No, I'm afraid there's no way to add rounded corners for `CurveColumn`. Sorry.
