### ISSUE TITLE
How to add CategoryAxis labels after you change location - Question

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#302]
Creating a simple Column chart with CategoryAxis and ValueAxis, after translate oX axis (categoryAxis.renderer.grid.template.location = 0) location like in this pen:
https://codepen.io/aniov/pen/vzyBRG?editors=0010
how can I set new labels like in pic bellow.
I've tried with "dateAxis.createSeriesRange" but I don't think is the write way...

![image](https://user-images.githubusercontent.com/21243081/44813401-5c0b4080-abe2-11e8-9cee-054922c2b1d9.png)

Thank you in advance.

**Comment by martynasma** [comment]
You can do that with axis ranges, just not created on series:

https://codepen.io/team/amcharts/pen/aaBRjx

**Comment by aniov** [comment]
I was close doing this but I didn't know how to set last label "max" :). Thank's a lot.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
