### ISSUE TITLE
How to reduce space between solid gauge chart values and actual chart ??

### ISSUE THREAD

**Issue by sagarkale94** [amcharts/amcharts4#3021]
![image](https://user-images.githubusercontent.com/46244365/96830034-57581500-1458-11eb-899d-5261843cbd48.png)

Sharing the codepen for the same : https://codepen.io/hardikforall/pen/MWKooNj?editors=0010

**Comment by martynasma** [comment]
You can use `valueAxis.renderer.labels.template.radius` to set that distance.

Please note that it can even be a negative value.

**Comment by sagarkale94** [comment]
@martynasma thank you works perfectly..!! i appreciate your quick response
