### ISSUE TITLE
Display year as first label on date axis

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#3022]
Is it possible to edit the first label on the date axis to display the year? I tried this using an adapter but I as it is only relevant on certain time units (months?) I wondered whether there might be a setting for it? Kinda like "period change" but "period start"?

**Rationale**
Some of our users mention that it's not always immediately obvious when looking at a historical chart what year the data is for.
They have to scan ahead to find a "period change" label (if it exists) and deduct one year to get the start year.

**Example chart**
![image](https://user-images.githubusercontent.com/2857604/96859350-4eb40e80-1459-11eb-9345-13ecc4d4305e.png)

**CodePen example**
https://codepen.io/jbate/pen/NWrbXxR?editors=0010

**Comment by martynasma** [comment]
Maybe something like this would do?

https://www.amcharts.com/docs/v4/tutorials/force-first-and-last-labels-on-axis/

**Comment by jbate** [comment]
Thanks for getting back to me. It's good to know something like that is possible, however it might not always be applicable. e.g. if the user's data means the chart is already displaying years then it isn't needed... perhaps it's close enough though. Maybe there's something else I can do to determine the current axis label format?

**Comment by martynasma** [comment]
> Maybe there's something else I can do to determine the current axis label format?

No I'm afraid, label does not carry any information about the format used for it :(

**Comment by jbate** [comment]
Don't worry. This probably gives me enough to go on... I'll work something out.
