### ISSUE TITLE
Can i Create chart in C sharp console application and save base64 value in database

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#3023]
Requirement is create a chart into console application and save that image into database.I am not using web application is it possible.

**Comment by martynasma** [comment]
Not really. Sounds like an overkill.

**Comment by EmaGht** [comment]
Well, server side rendering now works on am-charts if I'm not mistaken so you can technically run a node application that prints out a chart from a console... i guess... maybe...

Or you could use RRDTools

**Comment by Mahisandy** [comment]
from server side is there any alternate way to get chart image

**Comment by EmaGht** [comment]
Have you tried RRDTools?
