### ISSUE TITLE
Spelling error in docs

### ISSUE THREAD

**Issue by jswelsh** [amcharts/amcharts4#3024]
A couple of suspected spelling errors in docs. I've kept a list of a couple over time. Not sure if I should bothering reporting these / if it helps. 

**located in**
sidebar Tutorials and Demos
![Direced](https://user-images.githubusercontent.com/51499117/96943263-69ec4180-148c-11eb-8dbf-7f9971b1338f.png)
"Force **Direced** Tree" should be  "Force Directed Tree"

**located in**
[Force the first and last labels on axis](https://www.amcharts.com/docs/v4/tutorials/force-first-and-last-labels-on-axis/)
![ant](https://user-images.githubusercontent.com/51499117/96944137-dc5e2100-148e-11eb-9778-76c0f893a9ce.png)
" **ant**" should be "and"

**located in**
[Custom order of legend items](https://www.amcharts.com/docs/v4/tutorials/custom-order-of-legend-items/)
![evens](https://user-images.githubusercontent.com/51499117/96944096-c6506080-148e-11eb-9758-69b23e6a46f1.png)
"**evens**" should be "events"

**located in**
[Controlling automatic granularity of axis grid](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Controlling_automatic_granularity_of_axis_grid)
![settin](https://user-images.githubusercontent.com/51499117/96944494-c9981c00-148f-11eb-8fe5-0eff4f7f242a.png)
"**settin**" should be "setting"

**Comment by martynasma** [comment]
Thanks mate! All fixed.
