### ISSUE TITLE
Stacked Column Chart Accessibility dis

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [amcharts/amcharts4#3025]
**Bug description**

When using accessible navigation, trough browser tab, or alternate controls (voice commands, mouth-stick, ...)
Setting the focus a a series title of a Stacked Column Chart is rendered by a very ugly highlight over the svg text object

![image](https://user-images.githubusercontent.com/11965035/96975878-6653cb80-151b-11eb-85a4-bca263f26f86.png)

**Expected Behaviour**

It would be nice to have the focus highlight on a bounding box instead of the text element itself. so it is rendered as a readable text in a blue box and not this.

**Comment by martynasma** [comment]
Try the following workaround:

```JavaScript
var rect = new am4core.Rectangle();
chart.legend.itemContainers.template.background = rect
chart.legend.itemContainers.template.paddingLeft = 4;
chart.legend.itemContainers.template.paddingBottom = 4;
chart.legend.itemContainers.template.paddingTop = 4;
```
