### ISSUE TITLE
Multiple Charts, Minimum Size in Grid

### ISSUE THREAD

**Issue by mikeladurner** [amcharts/amcharts4#3026]
Desired result: 

I'd like to create a responsive webpage with VueJs and AmCharts. I create 4 charts, rendered into a <div> via ref, like in all the samples (components, vue). When i shrink the window, the charts get smaller. At some point, the labels of my piechart uses 90% of the hight, the pie is very small. I'd like to have a minimum height for the graphical part of my piechart.  

Including rules, i want the labels to be placed below the graphic. This happens fine, but as soon as there are many labels, the chart shrinks and shrinks. 

I tried to count the labels and set the hight of the chart to 200+40*numberOfLabels. This renders the charts correctly. 

When i now put them into a grid with 2x2 layout, the chart.pixelHeight acts strange. The first chart gets the 200+40*numberOfLabels, but the second one in the first row already contains the newly calculated size and gets the additional height a second time. This also happens to the second chart in the second row of the grid. The first ones of each row stay correct, the second one somehow already has the pixel height from the grid.

Is there a way to counteract that?

Best regards - Mike

**Comment by jswelsh** [comment]
from the question template "...Best of all, post your current chart online."

It's probably a good idea to toss your code in an online code sandbox so others can see what exactly you are seeing. Trying to diagnose the issue just through written layman's terms usually isn't efficient or effective. You are more likely to get help if you remove as much friction for others to troubleshoot. 

[codepen](https://codepen.io/)
[codesandbox](https://codesandbox.io)
[jsfiddle](https://jsfiddle.net/)
[stackblitz](https://stackblitz.com/)
