### ISSUE TITLE
manipulate path-finding between nodes / data points on a Line Series

### ISSUE THREAD

**Issue by jswelsh** [amcharts/amcharts4#3028]
Just working through demo's and I was wondering about the line series in [Transport (metro) map schema](https://www.amcharts.com/demos/transport-metro-map/) I understand the pathfinding from each node/station is partially dependent on the order they are in the array, but was wondering if it's possible to manipulate at what _X_ and  _Y_ value, maybe creating a 45°angle, change the number of direction changes (more than just one 90° at either the same _X_ and _Y_ of either of the joining nodes. Similar to either the red or blue line in this picture
![image12](https://user-images.githubusercontent.com/51499117/97104490-81d0ea80-1671-11eb-95f8-ba7d6eabdcb4.png)

[linked](https://jsfiddle.net/jswelsh/Lh8f2v9m/1/) is the demo, stripped of all routes except for one; it has two points, 
`  
{ station: "Airport", x: 12, y: 43 },
{ station: "Tsing Yi", x: 25.5, y: 56.5},`
with the path changing direction at x: 25.5, y: 43

looking through the [Line Series](https://www.amcharts.com/docs/v4/reference/lineseries/) API docs, I see a [PATH](https://www.amcharts.com/docs/v4/reference/lineseries/#path_property) Property, but I suspect that it may have nothing to do with what I want, even if it did, I don't really know how I can interact with this property to achieve any changes.

**Comment by martynasma** [comment]
There's no way to update "path finding". However, you can switch `StepLineSeries` to just `LineSeries`, so there are straight lines between points, then update the code and data to add anchor points at precise locations you want them to be.

I hope that makes sense.

**Comment by jswelsh** [comment]
yes, that's the solution. 
Thanks
