### ISSUE TITLE
Change font family Legend

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#3029]
I want to set a specific font family for a chart's legend. How can I load the correct font family so that the legend is displayed correctly? This is the font I want to use:

`chart.legend.fontFamily = "Source Sans Pro"`

Thank you.

**Comment by jswelsh** [comment]
[Web Font Loader](https://github.com/typekit/webfontloader) is the suggested solution for amCharts as per [amCharts docs](https://www.amcharts.com/docs/v4/tutorials/using-web-font-loader/)

**Comment by javier-fjfs** [comment]
Thank you for the info. I was able to load the font with Web Font Loader.
