### ISSUE TITLE
DateAxis labels print on unexpected marks when timezone specified is not same as browser timezone.

### ISSUE THREAD

**Issue by frank-fajardo-a142179** [amcharts/amcharts4#3030]
**Bug description**

### Scenario when problem occurs
When creating a chart that is for a different timezone to the browser's timezone and the time difference is not exact hours. For example, `chart.dateFormatter.timezone = 'Australia/Adelaide'` and the browser's timezone is `'Australia/Sydney'`, which is ahead in time by 30 minutes. 

### Problem description
The date axis label seems to be printed based on the browser's timezone. For example, the hour labels are printed on the 12:30, 1:30, and 2:30 marks instead of 12:00, 1:00 and 2:00 marks. The 12:30 label is correct because it is placed at the 12:30 mark. But I did not expect it to print a label at 12:30. Rather, I expected it to print a label at 12:00.

### Samples:
When data is on 'Australia/Adelaide' timezone, which is on different timezone as the browser: 
Link to sample chart: https://codepen.io/frankfajardo/full/yLJMVpx
How the sample looks on a browser with timezone 'Australia/Melbourne' (which is same time as 'Australia/Sydney'):
![image](https://user-images.githubusercontent.com/35437382/97135091-71b92800-17a3-11eb-8313-42f2d5eac9a2.png)

When data is on 'Australia/Sydney' timezone, which is on same timezone as the browser: 
Link to sample chart: https://codepen.io/frankfajardo/full/RwRpoOV
How the sample looks on a browser with timezone 'Australia/Melbourne' (which is same time as 'Australia/Sydney'):
![image](https://user-images.githubusercontent.com/35437382/97135082-6cf47400-17a3-11eb-8e2e-39e2fa51c861.png)

**Note:**
The sample chart is plotted on a day where both timezones switch from normal hours to daylight savings. We are testing the timezone patch on v4.10.1.

**Environment (if applicable)**

 - amCharts version 4.0

**Comment by jswelsh** [comment]
I've seen this issue before (specifically with an Australian time zone) I don't think it was with amCharts but I think it has something to do with the timezones and daylight savings. Let me look back on a few different forums but could you try and see if using West Africa Standard Time causes the same issue or similar issue.

**Comment by frank-fajardo-a142179** [comment]
A quick look at the amCharts source code, the `DateAxis` appears to use [`checkChange()`](https://github.com/amcharts/amcharts4/blob/57587d05b19e14ab65ad8d350fc66393aef1e2c8/src/.internal/core/utils/Time.ts#L120) [which looks at the UTC value of the dates to see if there is a change in the hour](https://github.com/amcharts/amcharts4/blob/57587d05b19e14ab65ad8d350fc66393aef1e2c8/src/.internal/core/utils/Time.ts#L162). So if the timezone offset is not exactly in whole hour/s, that becomes a problem. In case of `Australia/Adelaide`, the UTC hour change kicks in when the time is on the 30th minute of the hour.

There are definitely places where the timezone is not exactly whole hours difference from UTC.
In Australia, there are 2 major cities that this is the case: Adelaide and Darwin

**Comment by martynasma** [comment]
Thanks for reporting this. We're looking into it.

Here's a very simple repro case (for the dev team):
https://codepen.io/team/amcharts/pen/efddf0ef2322fc146c1e30df8bbbc5e4?editors=0010

**Comment by martynasma** [comment]
OK, so here's how to work around it.

You currently have set `timezone` on chart's DateFormatter only. It does mean that it is being applied to all timestamps, but does not actually influence calculation of grid for the DateAxis.

To fix it, you need to create a separate DateFormatter (without timezone) for DateAxis, as well as set `timezone` for axis itself:

```
dateAxis.dateFormatter = new am4core.DateFormatter();
dateAxis.timezone = 'Australia/Adelaide';
```

You will also need to adjust your `min`/`max` settings accordingly, e.g.:

```
dateAxis.min = am4core.time.setTimezone(Date.parse("2020-10-04T00:00:00+09:30"), 'Australia/Adelaide');
dateAxis.max = am4core.time.setTimezone(Date.parse("2020-10-05T00:00:00+10:30"), 'Australia/Adelaide');
```

**Comment by frank-fajardo-a142179** [comment]
@martynasma 

Unfortunately, that workaround causes other problems. It fixes the labels but it causes the chart to be wrong when the timezone comes off Daylight Savings. 

[Here is the chart where data is on 4 April 2020 when Adelaide moves from Daylight Savings to normal hours.](https://codepen.io/frankfajardo/full/dyXzjqY) And it looks like this

![image](https://user-images.githubusercontent.com/35437382/97388367-06e72880-192c-11eb-95d3-c2e8849c133b.png)

Without the workaround, it looks like this:

![image](https://user-images.githubusercontent.com/35437382/97388557-7230fa80-192c-11eb-80ec-38f6b6791b70.png)

**Comment by martynasma** [comment]
Not sure what to suggest :(

If you have an amCharts license, can you contact us at contact@amcharts.com to discuss this further?

**Comment by frank-fajardo-a142179** [comment]
Yes we have a license. Will do.

**Comment by martynasma** [comment]
OK, so the quickest workaround I could find was to use [`timezoneOffset`](https://www.amcharts.com/docs/v4/reference/dateaxis/#timezoneOffset_property) instead of `timezone`.

```JavaScript
dateAxis.timezoneOffset = -570;
```

Simplified demo:
https://codepen.io/team/amcharts/pen/0c1196b67af05f081b434ca48a0ac6dc

This setting sets difference in minutes between intended time zone and the UTC.

**Comment by frank-fajardo-a142179** [comment]
@martynasma that workaround messes the drill-down functionality we have in the chart. Are you able to tell us the when the bug fix for this will be released?

**Comment by martynasma** [comment]
@frank-fajardo-a142179 OK, so here's the deal:

Next version we'll release (prob at some point next week) will support have changes in `DateFormatter` needed to fully support `timezone` in `DateAxis`.

You will no longer need to set `timezone` on axis, just on chart's `dateFormatter`.

The difference from now, is that `DateAxis` will correctly place grid/labels at whole hour, not at half hours,like 6:30 - 7:30 - 8:30.

I will let you know here when the new version is out.

**Comment by martynasma** [comment]
OK, so the new version is out.

Please note that you need to only set `timezone` on `chart.dateFormatter`. Not need to create formatter or set timezone for the axis.
