### ISSUE TITLE
Handle button click in custom tooltip

### ISSUE THREAD

**Issue by TomRed97** [amcharts/amcharts4#3032]
Hello.
I have an Angular application.
I implemented custom tooltip with custom html content and I have button in it.
I should execute some method in my class when clicking button. As I see there is no way for that, because it searches methods in global state. But the problem is that I can't move my functions to global state.
Is there any way to implement this?
Can you help me?

**Comment by TomRed97** [comment]
As I hurried I find some way. I handle the hit event of tooltip and filter target to find my button click and processed accordingly.
So closing this question and thank you for library.

**Comment by ali0707** [comment]
hello 

> As I hurried I find some way. I handle the hit event of tooltip and filter target to find my button click and processed accordingly. So closing this question and thank you for library.

Hello TomRed did you find the solution for that ? i have the same same issue

**Comment by TomRed97** [comment]
> hello
> 
> > As I hurried I find some way. I handle the hit event of tooltip and filter target to find my button click and processed accordingly. So closing this question and thank you for library.
> 
> Hello TomRed did you find the solution for that ? i have the same same issue

Hello.
` this.chartSeries.tooltip.events.on('hit', (event) => {
            const target: any = event.event.target;
            if (target.className === 'rc-pie-tooltip__link') {
                this.goToPage(target.id);
            }
        });`
I just listen to hit events of tooltip and filter html by className and do some action
