### ISSUE TITLE
Difficult to setState in React based on startchanged and endchanged events listeners

### ISSUE THREAD

**Issue by RSchneider94** [amcharts/amcharts4#3034]
**Question**
Unfortunately I could not find anything in docs and here in the issues that could help me to do what I want here. Sorry also that I can't provide a working live sandbox of my example, because my chart data comes from API and I can't reproduce it 100% in sandbox. I'll try to do my best explaining and providing some code parts.

I've followed the [tutorial about handling axis zoom events](https://www.amcharts.com/docs/v4/tutorials/handling-axis-zoom-events-via-api/) in the docs and I've done the following code:

```javascript
dateAxis.events.on('rangechangestarted', onChangeRange);
dateAxis.events.on('rangechangeended', onChangeRange);
```

basically, my chart is a React component which receives ```onChangeRange``` as prop and here is what ```onChangeRange``` is trying to do:

```javascript
const handleChangeRange = (ev) => {
    let start = ev.target.minZoomed;
    let end = ev.target.maxZoomed;
    console.log('New range: ' + start + ' -- ' + end);
    setRangeDate([start, end]);
  };
```

when I try to ```setRangeDate``` and it ofc triggers a re-render, AmCharts is not working really well.

Sometimes I got the error: ```Base.ts:1323 Uncaught TypeError: Cannot read property 'push' of null``` but even thought there's no error, the chart simply stops from displaying data well for all series (just after I filter the range or smth), look:

First render (everything is fine):
<img width="461" alt="Screen Shot 2020-10-26 at 16 14 36" src="https://user-images.githubusercontent.com/11929659/97217636-5996d800-17a6-11eb-9dd2-52ed5f940224.png">

After clicking on some period of range selector or zooming in:
<img width="306" alt="Screen Shot 2020-10-26 at 16 15 10" src="https://user-images.githubusercontent.com/11929659/97217704-6fa49880-17a6-11eb-896b-f0e79e9ecdd7.png">

as you can see, the red axis is not showing any value anymore.

I can't understand because this state I'm setting is not even used by the chart, it's used just for another API call.

Things I've noticed:
- sometimes the event logs null for the start, for example: ```New range: null -- 1603675322687.6929```
- the event is called **a lot of times**, for just a period click or a zoom in (is that normal? Saw in the docs example and the console is also triggering a lot of times)
- after clicking in the same period for the second time or zooming in again, the data has come again, like the first screenshot

**Environment (if applicable)**
- amcharts 4.9.25
- using React w/ create-react-app (16.13.1)

**Comment by martynasma** [comment]
And what the `setRangeDate()` function do?

**Comment by RSchneider94** [comment]
> And what the `setRangeDate()` function do?

hi! appreciate your response! it sets a React useState and this will later call a API with the range dates as a param. But, from yesterday to today I have fixed it as it seems. Done some changes and it seems to be working now.

What I've done:

- Changed the event to ```rangechangeended```
- Created an array of objects used to store start and end ranges from charts (because when you select a range with the mouse - zoom in - it will call the event a lot of times and after that, I have set a timeout function to get just the last one, which I ```setRangeDate()``` and it calls another API

Now seems to work fine, no problems in the charts anymore. Don't know if it's the best solution or I'll have some trouble doing like this for the lib, but right now it seems to be working.

**Comment by martynasma** [comment]
Phew, OK then :)

Feel free to close this when ready ;)

**Comment by RSchneider94** [comment]
> Phew, OK then :)
> 
> Feel free to close this when ready ;)

hi, yes! sure! I'm just wondering, in case you could eventually help, if there's really no bugs with ```rangechangeended```? Even though it's working, it's still calling a lot of times, according to the docs, it should be only called when the animation event ends, right? Because of this, my app is calling the API multiple times 😞 

thanks!

**Comment by martynasma** [comment]
Are you zooming using `XYCursor`? If that is so, `rangechangeended` should be called only once.

**Comment by RSchneider94** [comment]
> Are you zooming using `XYCursor`? If that is so, `rangechangeended` should be called only once.

hi! yes, with `XYCursor`! it's called two times minimum

**Comment by jswelsh** [comment]
I would say it's more likely a state issue, what's the hierarchy for your react app and where is the state for all these components located

**Comment by martynasma** [comment]
> hi! yes, with XYCursor! it's called two times minimum

Hm, it shouldn't be that way. Could it be that your event is being added twice?

In any case, deferring handler code in case there are any further triggers is a sensible thing to do, so I would just go with it.

**Comment by RSchneider94** [comment]
hey, thanks @jswelsh and @martynasma for all the help!! solved it as @martynasma said, deferring the handler. Thanks for all support! wish you all the best!
