### ISSUE TITLE
Growing axis label gap

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#3035]
Axis labels adjust the chartable area based on their width, although it seems like they are only doing this inward. When labels get smaller in width the chart area does not expand outward. This leaves a growing gap between axis title and chart area as can be seen in this demo:
![axisLabelGap](https://user-images.githubusercontent.com/5614099/97305414-6566c500-18a0-11eb-91d0-a0b63be27e90.gif)

I'm already calling `invalidateLabels` on the axis each time I update the series, to make sure that the labels aren't cached. Is this a bug or is there a way to reset this? TIA!

 - amCharts version: 4.10.7
 - Browser and its version: Chrome 86.0.4240.111
 - Related frameworks and their versions: React 16.13.1, Storybook 5.3.18

**Comment by martynasma** [comment]
It's because of what we call "ghost label". It's an invisible label, that is sized to a maximum available label, to avoid legend width changing when zooming/scrolling/updating data.

You can disable it like this:

```JavaScript
yAxis.ghostLabel.disabled = true;
```

**Comment by sassomedia** [comment]
Ah I see, I did come across that at some point but didn't think it was enabled by default. Turning it off does solve the issue. Thanks @martynasma !
