### ISSUE TITLE
Cannot turn off axes animations even though chart and series durations are set to 0

### ISSUE THREAD

**Issue by Andy1605** [amcharts/amcharts4#3036]
Hi There,

I want to **useTheme( animated )** for tooltips, cursor etc. and even for some other charts (like a pie chart).
I also want to disable animations of a specific chart and its series. I control that by setting the interpolationDurations and defaultState/hiddenState.transitionDuration.
This works fine so far, **but i cannot manage to disable animations of the axes** on updates via chart.invalidateRawData(). Maybe i am just not aware of any other options than those i've tried: Setting the transition and interpolation durations of the axes.

I prepared a code pen example by forking the AMCharts4: Animation (1) example:
https://codepen.io/Andy-1605/pen/MWemvdo

It also contains my desperate tries to disable the axes animations.

I am also greatful to get any workaround for that matter ;)

Greetings

**Comment by martynasma** [comment]
What you're looking for is axis' `rangeChangeDuration`:

```JavaScript
valueAxis.rangeChangeDuration = 0;
```

**Comment by Andy1605** [comment]
Oh my.... That does the trick!
Thanks alot. I updated the codepen example accordingly! https://codepen.io/Andy-1605/pen/MWemvdo

**Comment by Andy1605** [comment]
But what i cannot do now is to distinct whether an update occured or whether it was initially. For example, if the chart series initially animate with 3000ms but interpolated values are animated with 500ms. The only good result i get for the axis for now is to completely turn the rangeChange animation off.
