### ISSUE TITLE
openValueY question

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#3037]
Hello !

This is my case: 

![image](https://user-images.githubusercontent.com/6083644/97442849-97246e00-192a-11eb-91d4-5492638dd373.png)

I would like to fill only the blue zone. Is it possible ? I'm using open value like that

```javascript
		var	series3  = chart.series.push(new am4charts.LineSeries());			
			series3.name = 'auto'
			series3.dataFields.valueY = "auto";
			series3.dataFields.dateX	= "date";
			series3.yAxis = valueAxis;
			series3.dataFields.openValueY = "import";
			series3.stroke = am4core.color("#ffff00");
			series3.fill = series.stroke;
			series3.fillOpacity = 0.8;
```

Only when auto > import.

Thanks for your help!

**Comment by martynasma** [comment]
There's no built-in way to apply different fill based on whether fill area is above or below other series.

Maybe you can consider this axis range-based solution:
https://www.amcharts.com/demos/range-chart-with-different-fill-colors/
