### ISSUE TITLE
"Failed to execute 'toDataURL' on 'HTMLCanvasElement'"

### ISSUE THREAD

**Issue by TomRed97** [amcharts/amcharts4#3038]
The issue is like #8 .
I have an Angular application and I use    
 "@amcharts/amcharts4": "4.9.31",
The problem is that this error appears not always and I don't understand the case to fix it some way.
It is my code.
`chart.exporting.getImage("png").then((image) => {
            this.exportedReportImageEmitter.emit(image);
        });`
So any ideas about that?

**Comment by martynasma** [comment]
Two questions:

1) When do you call the export code? Are you sure the chart is fully initialized when you do?
2) Does this happen with current version (4.10.9)?

**Comment by TomRed97** [comment]
Thank you for your response.
1. I noticed that it executes export code after chart initialization under the hood, but I also tried to do it in 'appeared' event, but in some cases the same error is present, maybe it is a bug of canvas and toDataUrl function, I tried to set keepTaint option also, but error is present.
2. Yes I set the current version and tried again.

I do some search and I think it is a problem of canvas because of CORS and other origins, but I have no images from other sources. 
I have no idea what to do. I can catch error and try to do export again 😊 if there is no solution.

**Comment by martynasma** [comment]
Well, if you could whip up some live repro case, I could take a look.

**Comment by TomRed97** [comment]
Oh, I can't reproduce the case maybe it's a problem of CORS I don't know 😭. I will do research and will close the issue if I can't reproduce it.
Maybe it's a problem with custom tooltip HTML. 
I disable tooltip exporting and it doesn't work. It works in bar charts but in the pie chart doesn't work.
Here is code [https://codepen.io/tamara-aprikyan/pen/JjKpmaR?editors=0010](url)
Maybe I set the wrong exportable property.
I am migrating to amCharts and everything is cool, thank you. But export is playing with my nerves. 😂

**Comment by martynasma** [comment]
The export in CodePen you linked does work. Am I missing something?

**Comment by TomRed97** [comment]
Oh sorry I didn't write the case. When chart draws and immediately I hover on it to show tooltip, tooltip also will be present in exported image. But I set tooltip.exportable to false.

**Comment by TomRed97** [comment]
Closing issue because I found another solution for export

**Comment by TomRed97** [comment]
Closing issue because I found another solution for export
