### ISSUE TITLE
Is it possible to disable a node containing multiple links as soon as the Sankey chart is loaded?

### ISSUE THREAD

**Issue by JasonAskew** [amcharts/amcharts4#3039]
Given https://www.amcharts.com/docs/v4/tutorials/pre-hidden-sankey-nodes/
Which references codepen https://codepen.io/team/amcharts/pen/ydQrMb
simply setting { from: "B", to: "E", value: 4, disabled: true } breaks the sankey. 
Clicking on B's node, there is no longer a link to E. 
C's link to E is broken. 
The missing links B->E and C->E display again if you click on E

Please refer to https://codepen.io/jason-askew/pen/KKMQQrL

**Comment by martynasma** [comment]
If you don't need the C > E link to be hidden, then remove the `disabled: true` from the B > E data.

As all nodes of any level draw information from the first time it is mentioned in data, if you including `disabled: true` in `B > E` data affects both B and E.

So, probably easiest way is to just include "empty" entries for all disabled nodes at the beginning of data.

For example, if I want do disable only B and D, I can do this:

```JavaScript
chart.data = [
  { from: "B", disabled: true },
  { from: "D", disabled: true },
  { from: "A", to: "D", value: 10 },
  { from: "B", to: "D", value: 8 },
  { from: "B", to: "E", value: 4 },
  { from: "C", to: "E", value: 3 },
  { from: "D", to: "G", value: 5 },
  { from: "D", to: "I", value: 2 },
  { from: "D", to: "H", value: 3 },
  { from: "E", to: "H", value: 6 },
  { from: "G", to: "J", value: 5 },
  { from: "I", to: "J", value: 1 },
  { from: "H", to: "J", value: 9 }
];
```

**Comment by JasonAskew** [comment]
My aim is to only allow one node to be visible at any given time, so that clickin on one node ensures all others are disabled. I've written a hit handler:
chart.nodes.template.events.on("hit", function(ev) {
	  var from = ev.target.dataItem.dataContext.from;
	  var arrayLength = chart.data.length;
	  for (var i = 0; i < arrayLength; i++) {
		    if(chart.data[i].from != from) {
		    	chart.data[i].disabled = true;
		    } else {
		    	chart.data[i].disabled = false;
		    }
	  }
	  ev.target.data = data;
	  chart.validateData();
	}, this);

which still fails with the json data in the format you've described ...please see https://codepen.io/jason-askew/pen/YzWaypa

**Comment by JasonAskew** [comment]
Just figured it out ...hit function needed to be:
chart.nodes.template.events.on("hit", function(ev) {
	  var from = ev.target.dataItem.dataContext.from;
	  var arrayLength = chart.data.length;
	  for (var i = 0; i < arrayLength; i++) {
		  	if(typeof(chart.data[i].to) == "undefined") {
			    if(chart.data[i].from != from) {
			    	chart.data[i].disabled = true;
			    } else {
			    	chart.data[i].disabled = false;
			    }
		  	}
	  }
	  chart.validateData();
	}, this);

Thanks for your help.
