### ISSUE TITLE
AmCharts multiCSV dataloader with Worldmap

### ISSUE THREAD

**Issue by JonhSilver** [amcharts/amcharts4#304]
[It is possible to get somting like that?](https://stackoverflow.com/questions/52090629/amcharts-multicsv-dataloader-with-worldmap)

![image](https://user-images.githubusercontent.com/24619483/44837093-4c6f1480-ac41-11e8-8b6d-d84510a3ca0e.png)

**Comment by martynasma** [comment]
Yes, of course.

Let us know if you hit any snags implementing it, or have any questions.

**Comment by JonhSilver** [comment]
Yes, thanks for [xorspark ](https://stackoverflow.com/questions/52090629/amcharts-multicsv-dataloader-with-worldmap/52105948#52105948)

now I wondered how to fix bubble positions 
![image](https://user-images.githubusercontent.com/24619483/45090305-a24b2d00-b117-11e8-9d98-6bc11a354b78.png)

**Comment by xorspark** [comment]
@JonhSilver  - FYI, this repo is for v4 questions. The solution I provided on SO is for v3. In my answer, I pointed out you can modify the variables that define `latitude` and `longitude` exceptions to position specific labels. You pulled the label generation code from [this example](https://www.amcharts.com/kbase/automatically-create-state-labels-callouts-values/) - study that and figure out your values for those specific countries using ISO-3166-2 codes (RU for Russia, NO for norway, etc)

**Comment by JonhSilver** [comment]
I need to change colors with `AmCharts.addInitHandler`, but it runs only once on page load, how to runt init hadler each time values changes?

**Comment by martynasma** [comment]
@JonhSilver This is a repo for amCharts 4. You are using amCharts 3 (previous version). Please email us at contact@amcharts.com for further support.

I'm going to go ahead and close this.
