### ISSUE TITLE
Export multiple charts (more than 15 Charts)

### ISSUE THREAD

**Issue by derd1011** [amcharts/amcharts4#3040]
hi, dear,
     

1. If I export 15 to 25 Charts at the same time it will take more than 5 to 10 min based on the server.

1.  and in  codepen it is crash the browser please help me with reducing the time of exporting multiple charts.

**Thanks in Advance.**

working code is [here](https://codepen.io/derd1011/pen/eYzVQdz).

i look this page before [coding](https://www.amcharts.com/docs/v4/tutorials/generating-multi-content-pdf-export/)

**Comment by martynasma** [comment]
Doing so on client-side in browser seems like an overkill.

Automated, server-based solution sounds better. E.g.:
https://www.amcharts.com/docs/v4/tutorials/automating-report-generation-using-selenium-webdriver/

**Comment by derd1011** [comment]
@martynasma thanks for quick response,
I see this link earlier and I not to much familiar with Node.JS. I need help on the PHP or on the client-side.

any other idea or solution are acceptable.

**Comment by derd1011** [comment]
no response from anyone.
