### ISSUE TITLE
how to change swtichbutton background color  and  circle  active or hover  fill

### ISSUE THREAD

**Issue by jianly** [amcharts/amcharts4#3041]

**Comment by jswelsh** [comment]
With the background for the circle, I assume you mean like when it is toggled, the button's circle changes on which direction/state it is toggled. Pretty sure the background is changed using the **background** property, ref in doc [here](https://www.amcharts.com/docs/v4/reference/switchbutton/#background_property)

I haven't used the switch button yet, but looking for stuff I think this might point in the right direction for both hover and active states

[Issue #263](https://github.com/amcharts/amcharts4/issues/263) seems similar in nature, it's an old post, but assuming the properties for hasn't changed for `container` and `SpriteState` then modifying the  `background` for these should be the solution. I'll try this out in a bit and see if I can make a sandbox of what I think you are trying to accomplish
