### ISSUE TITLE
column label is not visible

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#3042]
some time values are less than 1 that lable are not visible see in first and last column the value are half label's are visible can we restrict /any provision to display full label

![image](https://user-images.githubusercontent.com/54665162/97577598-a6ccb100-1a15-11eb-9f74-27a1196c0c30.png)

**Comment by jswelsh** [comment]
when you say restrict, do you mean you are ok with any label that is < 1 be hidden, or do you want the scaling to **always** accommodate the label.

**Comment by martynasma** [comment]
Provided you're not just trying to hide the labels (in which case @jswelsh suggestions would be perfect), you would need to [unmask the bullets](https://www.amcharts.com/docs/v4/concepts/bullets/#Disabling_bullet_clipping) as well as figure out what to do with colors: I don't think there are suitable color that would work on both very dark and white backgrounds.

Maybe add a background to those bullet labels?

```JavaScript
let foo = series.bullets.push(new am4charts.LabelBullet());
foo.label.background.fillOpacity = 0.5;
foo.label.background.fill = series.fill;
foo.label.background.disabled = false;
```

**Comment by jswelsh** [comment]
Looking at this again, the numbers at the top are being cut off, wouldn't that mean there isn't enough room for the chart within the given space? Could this be an issue with CSS or other styling effects? This is me speculating, from my understanding, the default behaviour of amcharts is scaling the axis for the data provided. you are doing a percentage so I assume you set a fixed size of the y-axis.
