### ISSUE TITLE
Potential Spelling errors

### ISSUE THREAD

**Issue by jswelsh** [amcharts/amcharts4#3043]
**located in:**
[Loading maps dynamically](https://www.amcharts.com/docs/v4/tutorials/building-drill-down-maps/#Loading_maps_dynamically)

in the code example under loading maps dynamically

`  if (map)
    countrySeries.geodataSource.url = "https://cdn.amcharts.com/lib/4/geodata/json/" + map + ".json";
    countrySeries.geodataSource.load();
  }
});`

`if (map) ` is missing `{`

**located in:**
[create grouped outlines](https://www.amcharts.com/docs/v4/tutorials/combining-map-polygon-series-to-create-grouped-outlines/#The_solution)

'Still not quite what we wanted, because state polygons are obstructing counties, and **there** state outlines are not prominent enough.'
**"there"** should be "their"

**located in:**
[What are Containers](https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/#What_are_Containers_)

This one I suspect is an intentional reference to slang for 'Really F***ing simple' but maybe not?
"Containers can be complex or **freally** simple. A Button"
**freally** possibly be "really", possibly stay the same

[Legend Label](https://www.amcharts.com/docs/v4/concepts/legend/#Legend_labels)

"Or, by setting legend's label template just **ones**:"
**"ones"** should be "once"

**Comment by martynasma** [comment]
Thanks for those! Fixed.
