### ISSUE TITLE
minPolylineStep per chart or only global?

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3045]
In the general concepts improving chart performance there is the simplify path section https://www.amcharts.com/docs/v4/concepts/performance/#Simplifying_paths
My question is, if this global setting is evaluated on new chart creation or also is used by already existing charts (e.g. on data updates).
(Because sometimes multiple charts are displayed at the same time - for some it would be good - others must not use the simplification.)

For themes I learned that themes could be set for each single chart by setting them before creating the chart.
https://www.amcharts.com/docs/v4/concepts/themes/#Different_themes_to_different_charts
E.g.
```
 am4core.unuseAllThemes();
 am4core.useTheme(am4themes_animated);
 createChart();
```

**Comment by martynasma** [comment]
The global setting will affect rendering process. So if you enable it after chart is created, it won't affect the current chart, until it is re-rendered, i.e. after data update.
