### ISSUE TITLE
any plans for a Dark mode for documents?

### ISSUE THREAD

**Issue by jswelsh** [amcharts/amcharts4#3047]
I know this tends to be a luxury item and is reasonably simple for users to do hacky solutions for making dark mode for docs. (web browser extension and community designed style sheets). That being said It would be sweet to know if there is one in the pipeline or if I should just make a quick and dirty one.

**Comment by martynasma** [comment]
How about just using `dark` [theme](https://www.amcharts.com/docs/v4/concepts/themes/)?

https://www.amcharts.com/demos/simple-pie-chart/?theme=dark

**Comment by jswelsh** [comment]
haha, sorry the question wasn't clear enough, I meant like a toggle button on the nav-bar of amCharts docs, that toggles a dark theme for the website's documentation. I currently use just a generic one while checking documentation for the site, but I find it leaves a lot to be desired. 

this is what it looks like
![Screenshot from 2020-11-01 23-55-40](https://user-images.githubusercontent.com/51499117/97843319-f3c2b880-1c9d-11eb-80f1-3fadfc3e6950.png)

ideally, it would be something cleaner like this...

![Screenshot from 2020-11-01 23-59-33](https://user-images.githubusercontent.com/51499117/97843557-5a47d680-1c9e-11eb-88db-892cabb864b3.png)

this is a custom dark mode using css styling and an extension applied to Github's domain, I'll end up making one for amcharts if nothing is planned, but if a native option does exist or will exist for the site, It'll likely be is far superior to anything I can build or find, in which case I'd just wait till then.

I realize that for the demo's this may not be ideal, or a realistic feature. I was just curious.

**Comment by martynasma** [comment]
Oh OK. No plans for it right now :)

**Comment by jswelsh** [comment]
all good, thanks for letting me know.
