### ISSUE TITLE
Amcharts 4 Performance Issue with Angular 9, Very slow rendering on browsers

### ISSUE THREAD

**Issue by Amit6882** [amcharts/amcharts4#3048]
**Question**
Amcharts 4 Performance Issue with Angular 9, Very slow rendering on browsers

**Environment (if applicable)**
   amCharts version: "^4.9.30",
   Browser and its version - Google Chrome - Version 86.0.4240.111 (Official Build) (64-bit)
   Angular: "~9.1.11",
  TypeScript: "~3.8.3"

**Additional context**
Reference Link: https://stackoverflow.com/questions/64644835/amcharts-4-performance-issue-with-angular-9
We have placed multiple charts on one of the pages in our Angular 9 app.

However, it takes a lot of time to load the page. On parent component's ngOnInit() we are initializing the components and making API calls to get the chart data to render on chart and it is not able to detect the view initialization as it seems stuck waiting for charts to complete initialization. The APIs are stuck in pending state till then and the load time is quite high for the page. Tried daisychain instantiation but that did not help as it makes it a jerky load experience. Also, can't use lazyloading as there are more than one charts which show above the fold itself.

If we comment out the charts then page loads very quickly. Help would be highly appreciated.

**Comment by martynasma** [comment]
Maybe try deferred loading?

https://www.amcharts.com/docs/v4/concepts/performance/#Deferred_daisy_chained_instantiation
