### ISSUE TITLE
Problem with custom geodata in map chart

### ISSUE THREAD

**Issue by delpin** [amcharts/amcharts4#3052]
Hello, could you help me to find a bug:
I try to use an example from your site (https://www.amcharts.com/demos/coronavirus-animated-dashboard-u-s/) with my own geodata. And some coordinates broked the chart (example: https://codepen.io/delpi5/pen/mdELQwp?editable=true%3Dhttps%3A%2F%2Fwww.amcharts.com%2F - the only difference from site example is in mapChart.geodata)
`
{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
                  37.51618268854978,
                  55.59955617694572
                ],
            [
              37.74895551569822,
              55.59605708144622
            ],
            [
              37.63934481104261,
              55.64133713707681
            ],
            [
                  37.51618268854978,
                  55.59955617694572
                ]
          ]
        ]
      },
      "id": "16376",
      "properties": {
        "name": "город Когалым",
        "id": "16376",
        "CNTRY": "Russia",
        "TYPE": "MUNICIPALITY"
      },
      "type": "Feature"
    }]}
`
Geojson is correct, checked by https://geojson.io/ . When i change start and finish coords, it starts to look normal. Example:
`{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
                  37.59229110289914,
              55.755816859174445
                ],
            [
              37.74895551569822,
              55.59605708144622
            ],
            [
              37.63934481104261,
              55.64133713707681
            ],
            [
                   37.59229110289914,
              55.755816859174445
                ]
          ]
        ]
      },
      "id": "16376",
      "properties": {
        "name": "город Когалым",
        "id": "16376",
        "CNTRY": "Russia",
        "TYPE": "MUNICIPALITY"
      },
      "type": "Feature"
    }]}`

**Comment by delpin** [comment]
Please check work of map plugin (use the latest version, download from site). I have 4 random correct polygons (screen 1), add it to the chart (mapChart.geodata) and then one of them fills the chart and the coordinates of the polygon are the hole (screen 2 and 3). Without the polygon, chart work correctly (screen 4)

![correct3](https://user-images.githubusercontent.com/3188330/98207096-327d9a80-1f4c-11eb-971f-6e41b7967c18.PNG)
![wrong](https://user-images.githubusercontent.com/3188330/98207335-93a56e00-1f4c-11eb-8843-9ce646ec9131.PNG)
![wrong2](https://user-images.githubusercontent.com/3188330/98207339-956f3180-1f4c-11eb-90d1-c21af0693ef1.PNG)
![correct](https://user-images.githubusercontent.com/3188330/98207459-c3ed0c80-1f4c-11eb-82ef-7d8f2f5a85aa.PNG)


full feature collections (1st wrong):
{"type":"FeatureCollection","features":[{"geometry":{"type":"Polygon","coordinates":[[[37.51618268854978,55.59955617694572],[37.74895551569822,55.59605708144622],[37.63934481104261,55.64133713707681],[37.51618268854978,55.59955617694572]]]},"id":"16376","properties":{"name":"город Когалым","id":"16376","CNTRY":"Russia","TYPE":"MUNICIPALITY"},"type":"Feature"},{"geometry":{"type":"Polygon","coordinates":[[[37.59229110289914,55.755816859174445],[37.590917811883514,55.79606628728175],[37.636236415399146,55.7976135086467],[37.64104293395383,55.748459087879276],[37.64310287047726,55.72250213829501],[37.59435103942258,55.72288968290279],[37.59709762145382,55.73606390136603],[37.59229110289914,55.755816859174445]]]},"id":"11656","properties":{"name":"Белоярский район","id":"11656","CNTRY":"Russia","TYPE":"MUNICIPALITY"},"type":"Feature"},{"geometry":{"type":"Polygon","coordinates":[[[37.69399431808777,55.76699452281603],[37.854669366915886,55.7863448479833],[37.842996393283066,55.70423317222987],[37.69399431808777,55.76699452281603]]]},"id":"13099","properties":{"name":"Березовский район","id":"13099","CNTRY":"Russia","TYPE":"MUNICIPALITY"},"type":"Feature"},{"geometry":{"type":"Polygon","coordinates":[[[37.33890081243488,55.755792619028064],[37.32166757549526,55.76691094824724],[37.35187997783901,55.78239201357875],[37.359433078424935,55.7808441849252],[37.39170541729212,55.76536250205853],[37.41999208160106,55.75977386664133],[37.40282594390572,55.74505842959907],[37.37124025054634,55.74195973243626],[37.336907975155725,55.74467110596806],[37.372613541561996,55.75938668972003],[37.33890081243488,55.755792619028064]]]},"id":"24958","properties":{"name":"город Лангепас","id":"24958","CNTRY":"Russia","TYPE":"MUNICIPALITY"},"type":"Feature"}]}

**Comment by martynasma** [comment]
Hey, just found this older thread.

Try adding `chart.reverseGeodata = true` to check if it fixes the issue for you.
