### ISSUE TITLE
ToolTip Issue

### ISSUE THREAD

**Issue by Jac0310** [amcharts/amcharts4#3053]
**Bug description**

Amcharts tool tip not rendering correctly for multi Y axis graph... I have created a multi axis graph with grouped categories following your tutorial here:

https://www.amcharts.com/docs/v4/tutorials/grouping-axis-labels-using-ranges/

My code is pretty much the same as yours bar abstracting/generalisation and domain specific stuff...

The tooltips do not render correctly:

![image](https://user-images.githubusercontent.com/32792148/97894671-10f59680-1d33-11eb-8436-2303aea7a1cf.png)

i.e. positioned centre of page, and valueY not found...

It looks like your example has the same issue:

![image](https://user-images.githubusercontent.com/32792148/97894832-4601e900-1d33-11eb-8230-9e6864aa484d.png)

**Environment (if applicable)**
Firefox and chrome

Amcharts 4...

**Additional context**

**Comment by xorspark** [comment]
The tooltip needs to be set on the column template since there is no XYCursor defined:

```
  series.columns.template.tooltipText = "{dateX}: [b]{valueY}[/]";
```

The example has been updated accordingly.

**Comment by Jac0310** [comment]
Thanks for the response I'll try that out :)

**Comment by Jac0310** [comment]
Works perfectly, thanks!
