### ISSUE TITLE
Is there a way to show picture in popup?

### ISSUE THREAD

**Issue by neung2542** [amcharts/amcharts4#3054]
Am working on pinbullet event hit and I want to show picture in popup
Some code example:
imageSeries.data = [
      {
        latitude: 20.6828175,
        longitude: -88.5728543,
        title: "Chichen Itza",
        // value: 2,
        length: 50,
        flag: "./images/new/n1.JPEG"
      }
]

pin.events.on("hit", function (ev) {
      
      
        setTimeout(function() {    
          var popup = chart.openPopup(ev.target.dataItem.dataContext.flag);
          }
}
the result is Its showing the "./images/new/n1.JPEG" text

**Comment by xorspark** [comment]
You can pass in HTML, per the [docs](https://www.amcharts.com/docs/v4/concepts/popups-and-modals/#Popup_Modal_content)

> Popup or Modal itself is an HTML element, which means that content can also be full-fledged HTML. You can use images, tables, iframes, and anything else HTML standard offers.

Just wrap your flag variable in an `<img>` tag and you're all set.

**Comment by neung2542** [comment]
Finally I can do it.THXBRO!!!
