### ISSUE TITLE
selectionextremeschanged event catching incorrect ev.target.minZoomed

### ISSUE THREAD

**Issue by azflin** [amcharts/amcharts4#3056]
I have the below chart event listener to pre zoom the chart once my chart's data changes:

```javascript
this.chart.events.on("datavalidated", () => this.selector.setPeriodInterval({timeUnit: "year", count: 1}));
```

I also have a DateAxis event listener to handle zoom events:

```javascript
let dateAxisChanged = (ev) => {
    let start = ev.target.minZoomed;
    let end = ev.target.maxZoomed;
    ...
}
dateAxis.events.on("selectionextremeschanged", dateAxisChanged);
```

I've noticed my final chart will correctly display the 1 yr pre zoomed range, however sometimes the ev.target.minZoomed will incorrectly be the start date of my data range (I presume because by default charts are fully zoomed out). Also, because of animations, the "selectionextremeschanged" event fires multiple times instead of once. Is there something I can do to reliably ensure my ev.target.minZoomed will correctly be the start date of my pre zoom period?

**Comment by martynasma** [comment]
How about `minmaxchanged` event?

`selectionextremeschanged` might be kicking in before related axis properties are updated.

**Comment by azflin** [comment]
@martynasma The minmaxchanged event does not exist for DateAxis.

**Comment by martynasma** [comment]
Oops sorry, my bad. I meant `startendchanged`.

**Comment by azflin** [comment]
Many thanks! It works now.

**Comment by PabloMizzle** [comment]
Hi @azflin,

May I ask how you handled this?

> "selectionextremeschanged" event fires multiple times instead of once

When I select a date range, this event fires like 50 times.
Maybe it has to do with my using the "animated" theme...

Best
Pablo
