### ISSUE TITLE
change precision of cursor's value, tooltip's value on Yaxis on small intervals

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3057]
When Y axis draw labels as integers, but values is float numbers.
![image](https://user-images.githubusercontent.com/11944160/98053077-3678c200-1e51-11eb-8ae6-842154c460df.png)

How can i change precision for cursor and tooltip

Same issue is for small decimal values:
![image](https://user-images.githubusercontent.com/11944160/98053380-e2221200-1e51-11eb-863f-05e9c1a06cc7.png)

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/#Number_precision_on_ValueAxis

**Comment by russeljo** [comment]
Thanks.
This helped me for axis
https://www.amcharts.com/docs/v4/reference/valueaxis/#extraTooltipPrecision_property
