### ISSUE TITLE
Multiple Value Axes. Opposite Yaxis and cursor with tooltip - dashed line direction bug

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3058]
I use Multiple Value Axes.
snapToSeries for opposite Y axis
`chart.cursor = new am4charts.XYCursor();
chart.cursor.snapToSeries = [eff];
`
Dashed line go to not opposite Yaxis.
Bug screen
![image](https://user-images.githubusercontent.com/11944160/98053781-d256fd80-1e52-11eb-99d3-b231fd1720d8.png)

**Comment by martynasma** [comment]
You just need to specify cursor's `yAxis`, e.g.:

```
chart.cursor.yAxis = series2.yAxis;
```

**Comment by russeljo** [comment]
Yes, thanks. But it's work only if one tooltip enabled for one line.
If I enable tooltips for many lines - cursor breaks
`
chart.cursor.snapToSeries = [
        series1,
       series2,
       series3
    ];
`
![image](https://user-images.githubusercontent.com/11944160/98128174-040ea980-1ed1-11eb-8e40-d30d74a62c2a.png)

**Comment by martynasma** [comment]
Unfortunately, there's no such possibility. Sorry :(
