### ISSUE TITLE
how save cursor's dashed lines for all axes in Multiple Value Axes with tooltip

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3059]
When i use tooltip for cursor, dashed lines draw only for tooltip, but hide for other axes.
But i stil need the cross lines for all axes.
how to fix it?

![image](https://user-images.githubusercontent.com/11944160/98054813-6de96d80-1e55-11eb-9a41-db3a77280693.png)

**Comment by martynasma** [comment]
I'm not sure what you mean. An `XYCursor` will show vertical and horizontal lines, as well as tooltips for ALL available axes by default.

If your chart acts differently, maybe you can post it on CodePen?

**Comment by russeljo** [comment]
Codepen above.
All axes is valueAxis.
Cursor labels is show, cursor lines show only for tooltip.
https://codepen.io/team/amcharts/pen/daLpro?editors=0010

**Comment by martynasma** [comment]
Thanks. This behavior is by design. Chart cursor has only two lines, and when you make it snap to series, it will show two lines leading upt to the data item it is currently snapped to - the one that is closest to the actual mouse cursor.
