### ISSUE TITLE
How to show line's dot value under cursor in XYchart relate to x-position?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3060]
Purpose: show in XYchart dot's y-value on series under cursor corespondin to x-value near cursor. I've got 3 series based on ValueAxes. And need to show for all lines.
The problem is:
`On an all-ValueAxis chart, the cursor's tooltip will snap to the nearest data point, calculated by both X and Y coordinates`
And multipleXY on valueAxes show only one tooltip.

so, i can not use cursor's tooltip for my purpose.

How can i realise purpose?
Maybe, i can:
1. get x-value of current cursor position
2. get nearest bullet to x-value under cursor
3. highlight nearest bullet and show label with coordinates

![image](https://user-images.githubusercontent.com/11944160/98056026-519b0000-1e58-11eb-8b82-525bda7b94c5.png)

**Comment by martynasma** [comment]
Technically, that could work. However we don't have a ready-made example for it.

You may find this tutorial useful:
https://www.amcharts.com/docs/v4/tutorials/tracking-cursors-position-via-api/

It shows how you can track cursor position and convert to actual values on various axis types.

Then it would be up to finding a nearest data item for specific series. There are no built-in functions to do that for ValueAxis, though, so you would probably need to iterate through all datatiems.

For found data items' bullets you could then set `isHover = true` to trigger tooltip.

Those are generic pointers, though. I don't have working demo. Hope it helps.

**Comment by russeljo** [comment]
Thank you!
