### ISSUE TITLE
Is there any way to save / remember position of the nodes of amchart force directed tree?

### ISSUE THREAD

**Issue by biletskiy6** [amcharts/amcharts4#3061]
Here is an example of amchart force directed tree https://www.amcharts.com/demos/force-directed-tree/

Is there any way to remember positions of all nodes and then after page refreshing show it correctly?

**Comment by martynasma** [comment]
This can be achieved using "fixed" nodes:

https://www.amcharts.com/docs/v4/chart-types/force-directed/#Fixed_nodes

You can access current `x` and `y` property of the node for saving, then supply it via data.

I don't have a demo, tho.

**Comment by biletskiy6** [comment]
> This can be achieved using "fixed" nodes:
> 
> https://www.amcharts.com/docs/v4/chart-types/force-directed/#Fixed_nodes
> 
> You can access current `x` and `y` property of the node for saving, then supply it via data.
> 
> I don't have a demo, tho.

Yes, i know it. But how can i save / remember this position, like saving to storage(localstorage or smth like this) and then after page refreshing show with this saved positions?

**Comment by biletskiy6** [comment]
I mean that I want to arrange everything once, then save it and then when I refresh the page show the graph with this saved positions

**Comment by martynasma** [comment]
Maybe something like this:

```JavaScript
networkSeries.nodes.template.events.on("dragstop", function(event) {
  console.log(event.target.x, event.target.y);
  event.target.dataItem.fixed = true;
});
```

Then you can collect the x, and y which you can then supply via data next time chart loads.

**Comment by biletskiy6** [comment]
> Maybe something like this:
> 
> ```js
> networkSeries.nodes.template.events.on("dragstop", function(event) {
>   console.log(event.target.x, event.target.y);
>   event.target.dataItem.fixed = true;
> });
> ```
> 
> Then you can collect the x, and y which you can then supply via data next time chart loads.

Ohh, yes, thanks, im really close.. the only problem is:

on gragstop i set dataitem fixed in true - thats ok
but then i want on dragstart event set dataitem fixed in false to move in again. Because after I changed the position once, I can't do it twice(second time)

I tried this one but its not working :(

networkSeries.nodes.template.events.on('dragstart', function(event) {
      console.log(event.target.dataItem)
      event.target.dataItem.fixed = false
    })

Maybe i should listen another event to set fixed in false?

**Comment by martynasma** [comment]
This should do:

```JavaScript
networkSeries.nodes.template.events.on("over", function(event) {
  event.target.dataItem.fixed = false;
});
```

**Comment by biletskiy6** [comment]
Yes, it works.
Thank you very much, I am very thankful for your help!

**Comment by biletskiy6** [comment]
Can you help, please, again?

Everything that we've discussed above is working perfectly, thank you.

But then when i want to save my all networkSeries.data array here is a problem. 


When i type console.log(networkSeries.data) there is an array of all my nodes, yes, but there are no positions for x and y stored there.

Maybe on drag event i need do any additional code ?


I mean that if this is my initial networkSeries data array(example below) then after dragstop there is no x and y for the node which i dragged:

networkSeries.data = [
      {
        name: 'Project Alpha',
        fixed: true,
        color: '#F7CB53',
        x: am4core.percent(60),
        y: am4core.percent(50),
        children: [
          {
            name: '#1',
            value: 1,
            color: '#425CD1',
            // fixed: true,
            // x: am4core.percent(20),
            // y: am4core.percent(20),
            children: [
              {
                name: 'Task 1',
                image:
                  'https://live.staticflickr.com/446/32478802896_79554c84e8_b.jpg'
                // disabledCircle: true,
              },
              { name: 'Task 2' },
              { name: 'Task 3' },
              {
                name: 'Task 4',
                children: [
                  {
                    name: 'Subtask 1'
                  },
                  {
                    name: 'Subtask 2'
                  }
                ]
              }
            ]
          },
          {
            name: '#2',
            value: 1,
            children: [
              { name: 'Task 1' },
              {
                name: 'Task 2',
                children: [
                  {
                    name: 'Subtask 1'
                  },
                  {
                    name: 'Subtask 2'
                  }
                ]
              }
            ]
          },
          {
            name: '#3',
            value: 1,
            // fixed: true,
            // x: 352.203,
            // y: 220.819,
            children: [
              { name: 'Task 1' },
              {
                name: 'Task 2',
                children: [
                  {
                    name: 'Subtask 1'
                  },
                  {
                    name: 'Subtask 2'
                  }
                ]
              }
            ]
          },
          {
            name: 'Problem',
            color: '#FF0000',
            value: 1,
            children: [{ name: '#1' }, { name: '#2' }]
          }
        ]
      }
    ]

**Comment by martynasma** [comment]
```JavaScript
networkSeries.nodes.template.events.on("dragstop", function(event) {
  console.log(event.target.x, event.target.x);
  event.target.dataItem.fixed = true;
  event.target.dataItem.dataContext.x = event.target.x;
  event.target.dataItem.dataContext.y = event.target.y;
});
```

**Comment by biletskiy6** [comment]
You are the best and made my day. Appreciate, thank you!

**Comment by biletskiy6** [comment]
Bro, you are my last chance, I've wasted a lot of time and cant find right solution...
All that we've described with you above works perfeclty, but there is a small bug...


Right know it works as it should, but with small issue.

If you move any node, on dragstop event i save the positions of x and y in the localstorage and then after page refreshing it shows me the tree with correct positions - this is fine. But on init, once you refresh the page and then you hover on the children node it lags, glitches. After these lags, it works fine, but on init it has a problems. What am I doing wrong? :( 


Here is and structure of my index.html file where i inline all code that we discussed with you, in action...

`<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}

	#chartdiv {
	  width: 100%;
	height:550px;
	max-width:100%;
	}
	</style>
</head>
<body>
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/plugins/forceDirected.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>

<div id="chartdiv"></div>

<script>
		
	 /**
 * ---------------------------------------
 * This demo was created using amCharts 4.
 * 
 * For more information visit:
 * https://www.amcharts.com/
 * 
 * Documentation is available at:
 * https://www.amcharts.com/docs/v4/
 * ---------------------------------------
 */

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end



var chart = am4core.create("chartdiv", am4plugins_forceDirected.ForceDirectedTree);
chart.legend = new am4charts.Legend();

var networkSeries = chart.series.push(new am4plugins_forceDirected.ForceDirectedSeries())

networkSeries.data = JSON.parse(localStorage.getItem('chart')) || [{
  name: 'Flora',
  children: [{
    name: 'Black Tea', value: 1
  }, {
    name: 'Floral',
    children: [{
      name: 'Chamomile', value: 1
    }, {
      name: 'Rose', value: 1
    }, {
      name: 'Jasmine', value: 1
    }]
  }]
}, {
  name: 'Fruity',
  children: [{
    name: 'Berry',
    children: [{
      name: 'Blackberry', value: 1
    }, {
      name: 'Raspberry', value: 1
    }, {
      name: 'Blueberry', value: 1
    }, {
      name: 'Strawberry', value: 1
    }]
  }, {
    name: 'Dried Fruit',
    children: [{
      name: 'Raisin', value: 1
    }, {
      name: 'Prune', value: 1
    }]
  }, {
    name: 'Other Fruit',
    children: [{
      name: 'Coconut', value: 1
    }, {
      name: 'Cherry', value: 1
    }, {
      name: 'Pomegranate', value: 1
    }, {
      name: 'Pineapple', value: 1
    }, {
      name: 'Grape', value: 1
    }, {
      name: 'Apple', value: 1
    }, {
      name: 'Peach', value: 1
    }, {
      name: 'Pear', value: 1
    }]
  }, {
    name: 'Citrus Fruit',
    children: [{
      name: 'Grapefruit', value: 1
    }, {
      name: 'Orange', value: 1
    }, {
      name: 'Lemon', value: 1
    }, {
      name: 'Lime', value: 1
    }]
  }]
}];


networkSeries.dataFields.linkWith = "linkWith";
networkSeries.dataFields.name = "name";
networkSeries.dataFields.id = "name";
networkSeries.dataFields.value = "value";
networkSeries.dataFields.children = "children";

networkSeries.nodes.template.tooltipText = "{name}";
networkSeries.nodes.template.fillOpacity = 1;


networkSeries.dataFields.fixed = 'fixed';
networkSeries.nodes.template.propertyFields.x = 'x';
networkSeries.nodes.template.propertyFields.y = 'y';

networkSeries.nodes.template.label.text = "{name}"
networkSeries.fontSize = 8;
networkSeries.maxLevels = 2;
networkSeries.maxRadius = am4core.percent(6);
networkSeries.manyBodyStrength = -16;
networkSeries.nodes.template.label.hideOversized = true;
networkSeries.nodes.template.label.truncate = true;

networkSeries.events.on("inited", function(){
    networkSeries.animate({property:"velocityDecay", to:1}, 3000);
})

networkSeries.nodes.template.events.on('over', function(event) {
      // event.target.dataItem.dataContext.fixed = false
      console.log(event.target);
      event.target.dataItem.fixed = false;
    })
    networkSeries.nodes.template.events.on('dragstop', function(event) {
    	console.log('ok');
      event.target.dataItem.dataContext.x = event.target.x;
      event.target.dataItem.dataContext.y = event.target.y;
      event.target.dataItem.dataContext.fixed = true;
      event.target.dataItem.fixed = true;
      localStorage.setItem('chart', JSON.stringify(networkSeries.data));
    })

</script>
</body>
</html>`

**Comment by biletskiy6** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}

	#chartdiv {
	  width: 100%;
	height:550px;
	max-width:100%;
	}
	</style>
</head>
<body>
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/plugins/forceDirected.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>

<div id="chartdiv"></div>

<script>
		
	 /**
 * ---------------------------------------
 * This demo was created using amCharts 4.
 * 
 * For more information visit:
 * https://www.amcharts.com/
 * 
 * Documentation is available at:
 * https://www.amcharts.com/docs/v4/
 * ---------------------------------------
 */

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end



var chart = am4core.create("chartdiv", am4plugins_forceDirected.ForceDirectedTree);
chart.legend = new am4charts.Legend();

var networkSeries = chart.series.push(new am4plugins_forceDirected.ForceDirectedSeries())

networkSeries.data = JSON.parse(localStorage.getItem('chart')) || [{
  name: 'Flora',
  children: [{
    name: 'Black Tea', value: 1
  }, {
    name: 'Floral',
    children: [{
      name: 'Chamomile', value: 1
    }, {
      name: 'Rose', value: 1
    }, {
      name: 'Jasmine', value: 1
    }]
  }]
}, {
  name: 'Fruity',
  children: [{
    name: 'Berry',
    children: [{
      name: 'Blackberry', value: 1
    }, {
      name: 'Raspberry', value: 1
    }, {
      name: 'Blueberry', value: 1
    }, {
      name: 'Strawberry', value: 1
    }]
  }, {
    name: 'Dried Fruit',
    children: [{
      name: 'Raisin', value: 1
    }, {
      name: 'Prune', value: 1
    }]
  }, {
    name: 'Other Fruit',
    children: [{
      name: 'Coconut', value: 1
    }, {
      name: 'Cherry', value: 1
    }, {
      name: 'Pomegranate', value: 1
    }, {
      name: 'Pineapple', value: 1
    }, {
      name: 'Grape', value: 1
    }, {
      name: 'Apple', value: 1
    }, {
      name: 'Peach', value: 1
    }, {
      name: 'Pear', value: 1
    }]
  }, {
    name: 'Citrus Fruit',
    children: [{
      name: 'Grapefruit', value: 1
    }, {
      name: 'Orange', value: 1
    }, {
      name: 'Lemon', value: 1
    }, {
      name: 'Lime', value: 1
    }]
  }]
}];


networkSeries.dataFields.linkWith = "linkWith";
networkSeries.dataFields.name = "name";
networkSeries.dataFields.id = "name";
networkSeries.dataFields.value = "value";
networkSeries.dataFields.children = "children";

networkSeries.nodes.template.tooltipText = "{name}";
networkSeries.nodes.template.fillOpacity = 1;


networkSeries.dataFields.fixed = 'fixed';
networkSeries.nodes.template.propertyFields.x = 'x';
networkSeries.nodes.template.propertyFields.y = 'y';

networkSeries.nodes.template.label.text = "{name}"
networkSeries.fontSize = 8;
networkSeries.maxLevels = 2;
networkSeries.maxRadius = am4core.percent(6);
networkSeries.manyBodyStrength = -16;
networkSeries.nodes.template.label.hideOversized = true;
networkSeries.nodes.template.label.truncate = true;

networkSeries.events.on("inited", function(){
    networkSeries.animate({property:"velocityDecay", to:1}, 3000);
})

networkSeries.nodes.template.events.on('over', function(event) {
      // event.target.dataItem.dataContext.fixed = false
      console.log(event.target);
      event.target.dataItem.fixed = false;
    })
    networkSeries.nodes.template.events.on('dragstop', function(event) {
    	console.log('ok');
      event.target.dataItem.dataContext.x = event.target.x;
      event.target.dataItem.dataContext.y = event.target.y;
      event.target.dataItem.dataContext.fixed = true;
      event.target.dataItem.fixed = true;
      localStorage.setItem('chart', JSON.stringify(networkSeries.data));
    })

</script>
</body>
</html>
```

**Comment by martynasma** [comment]
Perhaps you should delay adding of "over" and "dragstop" events by 3000ms so that all nodes have a chance to settle before invoking those handlers?
