### ISSUE TITLE
Cant find it in google or in docs, so do you have a mousedown event? Like you have 'over', 'dragstop', 'hit' etc

### ISSUE THREAD

**Issue by biletskiy6** [amcharts/amcharts4#3062]
**Question**

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
You found `over` and `dragstop` but missed `down`? :)

https://www.amcharts.com/docs/v4/reference/sprite/#down_event

**Comment by biletskiy6** [comment]
best support ever, thank you
