### ISSUE TITLE
Add our external click event to download xlsx file in click on menu

### ISSUE THREAD

**Issue by sedhalsoni** [amcharts/amcharts4#3063]
Can I add external libraries to download the xlsx file because I am unable to modify the header text as bold and external info in your chart options?

I am using this code for a fire event for download xlsx file but no success. I am using amcthrt4: '^4.9.33'

```
chart.exporting.export("xlsx", function(data) {
      console.log(data);
});
```

Please see the attached image I need to do like this in xlsx `format.`
https://prnt.sc/vdszgz

Thanks

**Comment by martynasma** [comment]
The export functionality uses [SheetJS](https://github.com/sheetjs/sheetjs) library to generate XLSX output.

If you want to make any changes to the xlsx document before it is outputed to user you can use the `xlsxWorkbook` adapter:

```JavaScript
chart.exporting.adapter.add("xlsxWorkbook", function(wb) {
  // make any changes you need to the workbook
  // ...
  return wb;
});
```

**Comment by hshahul** [comment]
I have tried the following way to add the footer text at the 20th row of the excel column but no luck.

chart.exporting.adapter.add("xlsxWorkbook", function(workbook) {
          workbook.workbook.Sheets.Data["A20"] = {
          v: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs",
          t:"s"
          }
return workbook;
});
