### ISSUE TITLE
Uncaught TypeError when creating/destroying charts often/fast

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3064]
**Bug description**
I have a scenario where charts could be created and destroyed quickly.
Sometimes there happens a nullpointer.
Probably there is a `if(!this._disposed)` missing in Base.ts#addDisposer like it is in removeDispose.
![image](https://user-images.githubusercontent.com/58069494/98236478-b1ca9880-1f63-11eb-886c-f1610d2f6abc.png)

![image](https://user-images.githubusercontent.com/58069494/98236765-2dc4e080-1f64-11eb-9474-d9462cff3b0d.png)
![image](https://user-images.githubusercontent.com/58069494/98236847-46cd9180-1f64-11eb-87ef-cc452d4ce502.png)

**Environment (if applicable)**

 - amCharts version: 4.10.10
 - Browser and its version: found in Chrome

**Comment by martynasma** [comment]
Would you be able to provide a working example which we can use to test and reproduce the issue?

**Comment by lticadler** [comment]
I'll give it a try.
But this is not 100% reproduceable. Don't know, if I'm able to turn it into a pen...

**Comment by lticadler** [comment]
Seems to me that all the errors I discovered lately have something to do with unchecked disposers.
So far I wasn't able to reproduce exactly this error (of this issue).
But possibly this issue will be fixed as well if #3051 is fixed.
In https://github.com/amcharts/amcharts4/issues/3051#issuecomment-724564383 I was able to create a pen.

**Comment by martynasma** [comment]
#3051 will be fixed in the next release. I doubt it will fix this, though.

Let's wait and see if it does.
