### ISSUE TITLE
How can i change font size for separate node?

### ISSUE THREAD

**Issue by biletskiy6** [amcharts/amcharts4#3065]
How can i change font size for SEPARATE node? Not for all,  like this networkSeries.fontSize = 8

**Comment by martynasma** [comment]
You can use `propertyFields` for that:
https://www.amcharts.com/docs/v4/concepts/data/#Property_fields

**Comment by biletskiy6** [comment]
Yes, but there is no property fontSize

**Comment by martynasma** [comment]
There is on `networkSeries.nodes.template.label`.

**Comment by biletskiy6** [comment]
Yes, but there is not property for fontSize networkSeries.nodes.template.label. ? I see textAlign, text, wrap, selectable, html, truncate, fullwords, ellipsis, hideOversized, ignoreFormatting, path, locationOnPath, baseLineRatio etc.

**Comment by martynasma** [comment]
There's `fontSize` property on `Label`:
https://www.amcharts.com/docs/v4/reference/label/#fontSize_property

**Comment by biletskiy6** [comment]
Yes, got it. But this is not propertyField and if i write networkSeries.nodes.template.label.fontSize = 20 it changes fontSize for ALL nodes, but i wanted to change for some specific node. For example if it's my networkSeries.data:

```
`[
        { 
 name: 'Project Alpha', 
 color: '#F7CB53',
 label: {
    fontSize: 20 // ????
  }
         }
  ]`
```

**Comment by martynasma** [comment]
`propertyFields` is exactly for that. It allows trying specific properties of an element to a key in data. You might need to "flatten" your data, though:

```JSON
[
 { 
   name: 'Project Alpha', 
   color: '#F7CB53',
   labelFontSize: 20
 }
]
```

And:

```JavaScript
networkSeries.nodes.template.label.propertyFields.fontSize = "labelFontSize";
```

**Comment by biletskiy6** [comment]
Yes, it works! Thank you very much
