### ISSUE TITLE
Annotation menu visible/hide based on button click

### ISSUE THREAD

**Issue by sagarkale94** [amcharts/amcharts4#3066]
I have to implement annotation menu hide or show based on button click. 

I have tried something here i am sharing codepen for the same: https://codepen.io/sagarkale94/pen/MWeqYwN?editors=0010

I am able to hide the menu but not able to make it visible again on button click, While hide annotation menu, annotation data should remain as it is.

**Comment by martynasma** [comment]
How about just hiding actual menu element?

```JavaScript
// Hide menu
chart.exporting.menu.element.style.display = "none";

// Show menu
chart.exporting.menu.element.style.display = "block"
```

**Comment by sagarkale94** [comment]
Wow..!! got it working as required. @martynasma thank you for the amazing chart library.
