### ISSUE TITLE
Sorting unequal length series after addData() update hides new data

### ISSUE THREAD

**Issue by clintie** [amcharts/amcharts4#3069]
I'm having an issue updating a Line Graph containing unequal length series.

`addData(...)` will of course add data to the `chart.data` object.  My two datasets are of unequal length, and representing data similar to 

- a day's **predicted** price movements (24h of data available, dataset does not change) and
- a _shorter_ set, the **actual** price as it is published (so <24h of data, updated regularly)

The correct lines appear initially, but an update (via `setTimeout` for example in CodePen) mimicking a new 'actual' published value _does not show if a simple `beforedatavalidated` event is set to sort them._  

```
chart.events.on("beforedatavalidated", function (ev) {
  chart.data.sort(function (a, b) {
    return (a.date - b.date);
  });
});
```

If the data is left **unsorted**, the new item does appear, but this causes random UI glitches.

I've added a codepen using a modified example from amChart's site which executes an addData() after 10 seconds with an auto-beforedatavalidated sort :

https://codepen.io/clintw/pen/ZEOMRqX

**Unsorted data.  New data point appears after 10s:**
<a href="https://imgbb.com/"><img src="https://i.ibb.co/x1J2sjv/sorted.png" alt="sorted" border="0" /></a>

**Sorted data (via beforedatavalidated), new datapoint never shows:**
<a href="https://imgbb.com/"><img src="https://i.ibb.co/PC2VxpT/unsorted.png" alt="unsorted" border="0" /></a>

**Comment by martynasma** [comment]
`addData()` does not invalidate whole data set (that's the whole point behind it), so sorting of the whole data set will not work as expected. It's supposed to be used to add new data points at the end.

If you need to change the whole order of the data set after adding new data point, you need to either modify existing `chart.data` and call `chart.invalidateDat()`, or set `chart.data` to a new array.

**Comment by clintie** [comment]
Thanks for the reply.  

This solution will cause the redraw flicker.  I guess there isn't a way to achieve this result as the full set of forecast data will be present up to the **end** of the data (from 00:00 to 23:59) as Series1, and as the day progresses a realtime Series2 will be continually added to  the to show against Series1.  As the check for new data happens several times a minute this probably isn't workable.

Thanks anyway.
