### ISSUE TITLE
am4Map renders a custom map geojson in an incorrect way

### ISSUE THREAD

**Issue by Ziyad-web** [amcharts/amcharts4#3071]
Hello,

**Question**
I get a weird results when I use external geojson for the am4Map as you see in this link[ live example](http://test.pixcept.com/), normally it's a smoother version of Switzerland cantons, and it renders well on mapShaper.org and QGIS too, but when specified as a data source for the map on am4Map I get squarebox with a dot inside

here is the [link to the geoson file](http://test.pixcept.com/geo_source/switzerland.json)

**Edit:** I have changed the geojson file to the one that I've got following the tutorial that you published here: [https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/](https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/), and the one that I get when I follow the same steps doesn't seem to work, but yours that you have provided at the end of the tutorial, despite the forgotten ";" comma at the end of the file (waSchools.json), works and mine doesn't, and still gives me the same weird result, even that when comparing the two files, everything is the same except for some after comma numbers that change. What I find really mysterious!

**Environment (if applicable)**

- amCharts version: 4.10.10
 - Browser and its version: latest Chrome
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.]: None

**Comment by xorspark** [comment]
The coordinates in your file appear to be in the wrong order. AmCharts only supports clockwise coordinates. Running the code below in the console fixed the map:

```
for(var i = 0; i < polygonSeries.geodata.features.length; i++) {
  var feature = polygonSeries.geodata.features[i];
  for(var x = 0; x < feature.geometry.coordinates.length; x++) {
    if (feature.geometry.type == "MultiPolygon") {
      for(var y = 0; y < feature.geometry.coordinates[x].length; y++) {
        feature.geometry.coordinates[x][y].reverse();
      }
    }
    else {
      feature.geometry.coordinates[x].reverse();
    }
  }
}
```

Result:

<img src="https://user-images.githubusercontent.com/2679427/98615530-d8bcfd80-22c8-11eb-9c31-1c7e5e01ae7c.png" width="400">

**Comment by Ziyad-web** [comment]
Thank you very much @xorspark that's a good mention, I have fixed my geojson files to be compatible with am4map
