### ISSUE TITLE
Legend label truncation not working after hovering over chart (only Chrome)

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3072]
**Bug description**

In Chrome browser the truncation of the legend labels is not working as expected.
Not at the beginning (static) and absolutely not on dynamic updates through hovering.

Pen: https://codepen.io/chrisadler/pen/pobxLOL?editors=0010

On start (no mouse move over the chart yet)
Firefox 
![image](https://user-images.githubusercontent.com/58069494/98629503-4c86f680-2319-11eb-8723-618ae936fc39.png)
Chrome (already not as expected by the label width value)
![image](https://user-images.githubusercontent.com/58069494/98629528-5d376c80-2319-11eb-873e-183b590c0664.png)

After moving the mouse over the chart multiple times and showing the values in the legend
Firefox
![image](https://user-images.githubusercontent.com/58069494/98629637-95d74600-2319-11eb-887d-5f520f03b33b.png)
Chrome (value in the legend no longer available [outside the painting area])
![image](https://user-images.githubusercontent.com/58069494/98629753-d8991e00-2319-11eb-83f0-c9083693ce56.png)

**Additional**
valueLabel settings seem not to work as expected as well...?
```
legend.valueLabels.template.width = 40;
legend.valueLabels.template.textAlign = 'end';
legend.valueLabels.template.align = 'right';
```
Label width grows and has with small values not the expected width.
Value is not aligned right although my legend and legend.itemContainers got a fix width.
And hovering over the same value has two different results at the end.
Pictures from Firefox (while hovering over the chart)
Growing label
![image](https://user-images.githubusercontent.com/58069494/98630489-92dd5500-231b-11eb-8e6c-83734b3adb47.png)
![image](https://user-images.githubusercontent.com/58069494/98630669-eea7de00-231b-11eb-97d0-951f4c759ac0.png)
![image](https://user-images.githubusercontent.com/58069494/98630676-f5ceec00-231b-11eb-941a-fb8ef7d477f5.png)
Back to first value
![image](https://user-images.githubusercontent.com/58069494/98630701-08492580-231c-11eb-8794-da9ea9db59fb.png)

**Environment (if applicable)**

 - amCharts version: all versions
 - Browser and its version: Chrome

**Comment by zeroin** [comment]
The only way to solve this which I see is to add an adapter:

```
legend.labels.template.adapter.add("maxWidth", ()=>{
  return 80
})
```

Because of some alignment issues we do reset maxWidth inside the legend so this is why your setup is not working. Unfortunately I can not change this behavior.

**Comment by lticadler** [comment]
Thanks a lot for the solution :)
