### ISSUE TITLE
Can't access am4core.SVGAttribute import when using ES6

### ISSUE THREAD

**Issue by dreamyguy** [amcharts/amcharts4#3073]
**Bug description**

I'm using ES6 and following the instructions from https://www.amcharts.com/docs/v4/reference/svgattribute/.

`import * as am4core from '@amcharts/amcharts4/core';`

When attempting to use `SVGAttribute`, like so:

`am4core.SVGAttribute`

I get this error:

```
Attempted import error: 'SVGAttribute' is not exported from '@amcharts/amcharts4/core' (imported as 'am4core').
```

**Environment (if applicable)**

Node + Create React App (**React 16.12.0**)

**amCharts version**

`@amcharts/amcharts4@4.10.4`

_A similar problem was reported by @roaldjap in https://github.com/amcharts/amcharts4/issues/1539#issuecomment-627837647_

> @martynasma what if I wanted to do it on ES6?
>
> `Attempted import error: 'Align' is not exported from '@amcharts/amcharts4/core' (imported as 'am4core').`
>
> I got this error using `am4core.Align`

**Comment by martynasma** [comment]
`SVGAttribute` is a `type`, not regular entity which you can use.

So if you are using TypeScript, you can use it to define a type of a variable, e.g.:

```
let test: am4core.SVGAttribute;
```

Types are not exported as modules, so you can use them in a non-TS app.
