### ISSUE TITLE
When zoom out button appears, what methods should I use to implement the click function of zoom out button? The purpose is to manually call the click method of the zoooutbutton without the appearance of the zoooutbutton

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#3074]
When zoom out button appears, what methods should I use to implement the click function of zoom out button? The purpose is to manually call the click method of the zoooutbutton without the appearance of the zoooutbutton

[https://codepen.io/fu1996/pen/oNLQqxa](https://codepen.io/fu1996/pen/oNLQqxa)

When I click the button in the lower left corner, the maximum height of the Y axis changes

**Comment by martynasma** [comment]
I'm not sure what you're asking. Your custom zoom out button seems to be working, no?
