### ISSUE TITLE
Candlestick has visual bug when panned/zoomed and candlestick size is small

### ISSUE THREAD

**Issue by lauris** [amcharts/amcharts4#3075]
**Bug description**

If you zoom so that the candlesticks become small (approx less than 10px in width) and then pan horizontally the high/low stick will move 1px to the left. Easier to notice when candlesticks are especially small. Happens on Chrome, Safari and mobile browsers. 

This bug happens in any candlestick chart, even the main demos, e.g., https://www.amcharts.com/demos/professional-candlesticks/ (easier to replicate if on mobile or browser window is made smaller in size)

Screenshot (check "stick" part of candlestick)
<img width="464" alt="Screenshot 2020-11-11 at 13 20 22" src="https://user-images.githubusercontent.com/625264/98806138-657acf00-2421-11eb-9347-1d3d799f4280.png">

**Environment (if applicable)**

Latest version 4.10.

**Additional context**

**Comment by lauris** [comment]
If chart data is reloaded then the candlesticks are redrawn and the bug temporary disappears. Calling invalidate/deepInvalidate doesn't help though.

**Comment by martynasma** [comment]
We'll introduce a global setting to fix that in the next version to be released.

I'll let you know when it's out as well as provide more details then.

Thanks!

**Comment by lauris** [comment]
Thanks @martynasma for a quick response. Is there a temporary workaround for this or can you suggest where to look to fix this at least locally for testing?

**Comment by martynasma** [comment]
No, I'm afraid. We should release a new version within few days.

**Comment by martynasma** [comment]
4.10.11 is out. It adds the following global option:

```JavaScript
am4core.options.pixelPerfectPrecision = 3;
```
