### ISSUE TITLE
Multiple Charts Components in React, how would be the best way to structure?

### ISSUE THREAD

**Issue by RSchneider94** [amcharts/amcharts4#3079]
Hello,

it's not a difficulty itself or issue, but I'm wondering how people are structuring their projects with AmCharts here? If someone have some tip or wanna share. In the examples [Using React](https://www.amcharts.com/docs/v4/getting-started/integrations/using-react/) there's just a App.js file with a single chart. But what would be the best / correct way to work with AmCharts using multiple components / charts? Currently I have more than 10 chars in my application and one component for each one and they look like this: https://gist.github.com/RSchneider94/adce2b26e9036fa8ac5d0fd19d2c1af4

As you can see, for each component, I'm importing almost all this repeatedly:

```javascript
import * as am4core from '@amcharts/amcharts4/core';
import * as am4charts from '@amcharts/amcharts4/charts';
import am4themes_animated from '@amcharts/amcharts4/themes/animated';
import am4lang_pt_BR from '@amcharts/amcharts4/lang/pt_BR';
import * as am4plugins_rangeSelector from '@amcharts/amcharts4/plugins/rangeSelector';
```

Is that ok? I mean, if I want to use a different theme in one specific chart, I just change in this specific chart the import. Are you guys doing the same?

I've seen a two strange 'bugs' while doing like this, that's why I'm asking here too.

- First of all: when I changed one theme from one chart in a page, the other chart has changed too (even though it has another theme set)
- Second: while using rangeSelector things gone a bit wrong too, when clicking in periods from the second chart didn't do anything at all, maybe cuz the first one had one too?

I'd be glad if you guys could share this and also if you guys have seen these 'bugs' before or know how to solve this would be also awesome! Thanks!

**Comment by martynasma** [comment]
By nature, all active themes are applied to all the charts, so there's no way to specify a theme per chart, I'm afraid.

As for the range selector issue you mention, if you can make a reproducible case, can you post it as a separate issue? I did whip up a small example with two charts with range selectors and they appear to work fine:
https://codepen.io/team/amcharts/pen/xxOmEEN?editors=0010

**Comment by RSchneider94** [comment]
> By nature, all active themes are applied to all the charts, so there's no way to specify a theme per chart, I'm afraid.
> 
> As for the range selector issue you mention, if you can make a reproducible case, can you post it as a separate issue? I did whip up a small example with two charts with range selectors and they appear to work fine:
> https://codepen.io/team/amcharts/pen/xxOmEEN?editors=0010

hi @martynasma !! about the themes, thanks! about the range selector, yes, your example seems to work really well! Unfortunately, in React, while importing two different chart components that have each one a selector inside of it, it's not working well, but yes, I can try to make a reproducible case and post as a separate issue. Thanks!

**Comment by RSchneider94** [comment]
@martynasma https://github.com/amcharts/amcharts4/issues/3088 opened the issue with a example and better explanation, thanks!
