### ISSUE TITLE
Annotation menu not pop up over the tile

### ISSUE THREAD

**Issue by sagarkale94** [amcharts/amcharts4#3080]
![annotation](https://user-images.githubusercontent.com/46244365/98901776-56a42300-24da-11eb-8ce2-1a4be4d283b6.png)

Annotation menu getting hide inside chart tile(div). Please share u r suggestion.

**Comment by martynasma** [comment]
Perhaps you have `overflow: hidden` CSS set on your chart div? In that case you could remove it.

If it's still needed, you can consider placing your ExportMenu outside chartdiv:
https://www.amcharts.com/docs/v4/tutorials/export-menu-in-external-container/

**Comment by sagarkale94** [comment]
Yes, i removed `overflow:hidden` now, but the new problem raised. 
![annotation1](https://user-images.githubusercontent.com/46244365/98904744-337c7200-24e0-11eb-81bc-9d7bec8a2e2f.png)
No addition z-index is provided anywhere.

**Comment by martynasma** [comment]
Well, you will need to manage z-indexes of the different chart containers yourself.

Probably the easiest way would be to add hover z-index on chart divs:

```CSS
.chart:hover {
  z-index: 100000;
}
```
