### ISSUE TITLE
How to fixed position of grid in live amcharts 

### ISSUE THREAD

**Issue by mianSaif** [amcharts/amcharts4#3081]
Hi there i'm using live  amcharts  i have a question when live data comes in charts the grid lines in amcharts move with axis. But i want to fixed of this position. How can i do this??

**Comment by martynasma** [comment]
No, I'm afraid there's no way to force grid to stay in the same place regardless of the scope data range.

Unless you want to fix the scale using `min` and `max`, e.g.:

```JavaScript
dateAxis.min = new Date(2020, 0, 1).getTime();
dateAxis.max = new Date(2020, 11, 31).getTime();
```

**Comment by mianSaif** [comment]
Okay Thanks
