### ISSUE TITLE
How to remove axis range line which i have already create  after 30 seconds

### ISSUE THREAD

**Issue by mianSaif** [amcharts/amcharts4#3082]
Hi, there I'm creating an axis range line when I click on the button . I have attached an image to explain clearly you can check. I want to remove this created axis horizontal line which I have created after some time like 30 secconds. Below is my code to create axis range line
![axis-range](https://user-images.githubusercontent.com/68012827/98914397-704d6680-24ea-11eb-8d16-644bf444aed9.PNG)
                `let range = valueAxis.axisRanges.create();
                range.value = range_val;
                range.grid.stroke = am4core.color("#" + color);
                range.grid.strokeWidth = 2;
                range.grid.strokeOpacity = 2;
                range.label.inside = false;
                range.grid.above = false;
                range.label.fill = range.grid.stroke;
                range.label.align = "center";
                range.label.verticalCenter = "center";`

**Comment by martynasma** [comment]
Did you try calling `range.dispose()` on it?

**Comment by mianSaif** [comment]
it's not working it's throwing an error you can check in the link i have attached. And by the way I don't want to dispose all the ranges line in the chart, I want to remove a specific line in the chart.[https://www.loom.com/share/2356c9e1a403409bba838face4b683e4](url)

**Comment by martynasma** [comment]
Here's an example:
https://codepen.io/team/amcharts/pen/d66b68a9f5317e8da75799e915848d3c

Disposing a range removes it from the chart.

Are you doing it differently?

**Comment by mianSaif** [comment]
It's not possible to remove just a specific line ??

**Comment by mianSaif** [comment]
I'm creating multiples lines from range variable on different positions. But if I will dispose  the range variable. It will remove all the lines. but I need to remove a specific line.

**Comment by martynasma** [comment]
I'm afraid I don't understand what you mean. One axis range - one line. You remove that axis range, you remove one line.

What am I missing?

**Comment by mianSaif** [comment]
Here is my chart [http://binvestic.com/trade](url).
You can check when you click on Higher and Lower button you will see the lines. I just want to remove one specific line not all. My question is so simple. I dont want to remove all line. Just visit my chart from the above link. You will understand what i want.

**Comment by mianSaif** [comment]
you can check in this video i'm creating two line when i place bet i have also show you code from I'm creating these lines. Just want to remove one specific line not all.

**Comment by mianSaif** [comment]
Let me know is there any solution from which I can remove the already created line. Not all specific lines.

**Comment by mianSaif** [comment]
You can check in this video[https://www.loom.com/share/ddc03e79541740c597282e9d945eb081](url)
In this video i'm creating two lines i just want to remove one specific line. How can i do this..?

**Comment by martynasma** [comment]
```JavaScript
valueAxis.axisRanges.getIndex(0).dispose();
```

**Comment by mianSaif** [comment]
getIndex(0) will i pass the range value like (getIndex(range_val)) from where i want to remove line ??

**Comment by martynasma** [comment]
It's the index of the range.

If you want to find a range by value, you will need to iterate through `axisRanges` and compare their `value` to the value you want to remove.

**Comment by mianSaif** [comment]
I have tried this solution but still no improvement
