### ISSUE TITLE
Live Trading Chart

### ISSUE THREAD

**Issue by habib3962** [amcharts/amcharts4#3083]
**Question**
How to stop moving chart by default.

**Environment (if applicable)**
PHP, Laravel, JS

**Additional context**
https://www.amcharts.com/demos/live-data/
chart should be still but dot should continue to move on.
like dateAxis should be still by default.

**Comment by martynasma** [comment]
DateAxis range depends on the available data range.

If you want to fix axis to specific range, you can do so via `min` and `max`:

```JavaScript
dateAxis.min = new Date(2020, 0, 1).getTime();
dateAxis.max = new Date(2020, 11, 31).getTime();
```

**Comment by habib3962** [comment]
actually i am working on a trading website.
i want dateAxis to stop moving but want the series dot to continue, on dragging towards right. 
Is Am Chart is suitable for Trading platform. like expertoption or iqoption?

![Screenshot (125)](https://user-images.githubusercontent.com/60214489/98928500-ab0bca80-24fb-11eb-8674-901da7ac145c.png)

**Comment by martynasma** [comment]
Well, please read my reply above, about fixing the axis scale to a certain time stan.

**Comment by habib3962** [comment]
ok. if you can see a dot in picture with horizontal line in it.
they move both together but not smoothly.
if i add a interpolationDuration in series then line proceeds fast but dot proceeds slow.
is there any way that bot proceed smoothly together?

**Comment by martynasma** [comment]
I could take a look if you could post your working chart on CodePen/jsFiddle.

**Comment by John-Matthew9** [comment]
@habib3962  did u manage to get a solution i also need help with the same thing
