### ISSUE TITLE
Unable to update Legend settings in theme function

### ISSUE THREAD

**Issue by IraErshova** [amcharts/amcharts4#3086]
**Question**

Hi! I'm trying to create my custom theme to apply certain settings to all my charts in the project. And I came across an issue when I couldn't add some settings to the theme function because of an error
`TypeError: Cannot read property '****' of undefined`

For example, I want to define a default position and label color for Legend in the theme:
```
if (target instanceof am4charts.Legend) {
        target.paddingTop = 20;
        target.labels.template.fill = am4core.color('#637178');
        target.position = 'bottom';
}

```
**paddingTop** - works
**labels.template.fill and position** - doesn't

I get the error
` TypeError: Cannot read property 'template' of undefined`

I have this issue not only with Legend but with Axes and other classes
Could you tell me what's wrong? Maybe I can't change some settings in the theme.

**Environment**

- "@amcharts/amcharts4": "4.9.6"
- "@angular/core": "^9.1.0"
- Goggle Chrome Version 86.0.4240.183 (Official Build) (64-bit)

Sometimes there is a second error after the first one
![image](https://user-images.githubusercontent.com/14790520/98947074-6c770f80-24fd-11eb-9722-f81b8d8ab2f7.png)

**Comment by martynasma** [comment]
Try this:

```JavaScript
if (target instanceof am4charts.Legend) {
  target.paddingTop = 20;
  if (target.labels) {
    target.labels.template.fill = am4core.color('#637178');
  }
  target.position = 'bottom';
}
```

**Comment by IraErshova** [comment]
@martynasma yeah, it helps! So probably I have to check if this property is available before using it. Thanks for help!
