### ISSUE TITLE
On xAxis ticks appears under range, not only axis's labels.

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3089]
Ticks appear under range
![image](https://user-images.githubusercontent.com/11944160/99011578-d75c3100-2565-11eb-8dc7-10f3fe358ba3.png)

https://codepen.io/ruslan-muhamedqrow/pen/NWrBPxm?editors=0011

**Comment by xorspark** [comment]
AxisRanges have their own [`tick`](https://www.amcharts.com/docs/v4/reference/axisdataitem/#tick_property) objects that are configured separately. You can disable it if desired by setting `disabled` to true.
