### ISSUE TITLE
History in chart

### ISSUE THREAD

**Issue by habib3962** [amcharts/amcharts4#3092]
**Question**
How to get history on dragging/panning backward.
It shows up to limited history about some minutes. What if I want 1 day history?

![Screenshot (125)](https://user-images.githubusercontent.com/60214489/99067516-acf18e80-25cc-11eb-9819-4af311ae7906.png)

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
There's no such built-in feature. Sorry.

**Comment by habib3962** [comment]
ok thanks
