### ISSUE TITLE
Multiple Layouts

### ISSUE THREAD

**Issue by habib3962** [amcharts/amcharts4#3095]
**Question**
is there any option of multiple layouts, like 2 live charts can be shown and every chart has separate functionalities of bidding etc showing in following pic.

**Environment (if applicable)**

**Additional context**
![screenshot-app expertoption com-2020 11 14-20_49_47](https://user-images.githubusercontent.com/60214489/99151200-3da69800-26bb-11eb-8294-3e5be30a74c9.jpg)

**Comment by martynasma** [comment]
Why not create two separate charts?
