### ISSUE TITLE
Custom vertical lines of specific time interval

### ISSUE THREAD

**Issue by mianSaif** [amcharts/amcharts4#3097]
Hi There, I want two verticle lines these line intervals will be of 30 seconds. You can see in the image to understand more clearly. Let me know if it is possible in amchart.
![Expiration-line](https://user-images.githubusercontent.com/68012827/99221482-7735eb00-2802-11eb-8399-b0f261b36157.PNG)

**Comment by martynasma** [comment]
You can use axis ranges:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/

**Comment by mianSaif** [comment]
I was expecting you will give me this answer. But it's not only about the drawn line. I want two line area interval as in image it's should be an exact 30-second interval

**Comment by mianSaif** [comment]
**Check This out:**

![line](https://user-images.githubusercontent.com/68012827/99232223-76598500-2813-11eb-8621-3f4c651d602b.PNG)

**Comment by martynasma** [comment]
Axis range can have open and end value/date, you can have it filled. Please do read the docs before asking for solutions ;)

**Comment by mianSaif** [comment]
I have read the docs let I try this solution if it will work then sound good I'll close this topic. If it will not work I'll get back to you.
By the way, I have seen the red shaded area and horizontal line. It's also possible I can draw a verticle line on the start and end point of the shaded area ??

**Comment by martynasma** [comment]
What is a "red shaded area"?

**Comment by mianSaif** [comment]
![area](https://user-images.githubusercontent.com/68012827/99235615-e407b000-2817-11eb-8e0e-bab27af6ef89.PNG)

**Comment by martynasma** [comment]
Series-based axis ranges do not have vertical lines. Sorry.

**Comment by mianSaif** [comment]
Okay Thanks
