### ISSUE TITLE
Question - about tooltips and plot area

### ISSUE THREAD

**Issue by TomRed97** [amcharts/amcharts4#3098]
<img width="1142" alt="Screen Shot 2020-11-16 at 13 00 59" src="https://user-images.githubusercontent.com/20994693/99233537-cbde6380-280c-11eb-93f1-6b66a285d6dd.png">
Hello. One more time thank you for this library.
I have a question.
I have a problem. I implement a custom tooltip in which there can be links. And the problem is that when tooltip content is big and high, it gets out of the plot area and when you want to move the pointer on the tooltip it disappears.
In the attached screenshot, there is a red area that is out of the plot area and my tooltip is in that area.
And the question is there a solution for that, for example, to set some offset for plot active area or I don't know.

**Comment by xorspark** [comment]
Have you tried setting `keepTargetHover` on the series' tooltip object as mentioned [here](https://www.amcharts.com/docs/v4/tutorials/clickable-links-in-tooltips/)?

```
series.tooltip.keepTargetHover = true;
```

**Comment by martynasma** [comment]
@xorspark This won't help because `Cursor` will monitor whether pointer is over chart area and will hide tooltips when it's out.

The only solution I can think of is to disable cursor when tooltip is displayed:

```JavaScript
series.tooltip.keepTargetHover = true;
series.tooltip.ignoreBounds = true;
series.tooltip.pointerOrientation = "down";
series.tooltip.events.on("shown", function() {
  chart.cursor.interactionsEnabled = false;
});

series.tooltip.events.on("hidden", function() {
  chart.cursor.interactionsEnabled = true;
});
```

**Comment by TomRed97** [comment]
Thank you @martynasma and @xorspark for your attention and help. The last solution with cursors works great.
