### ISSUE TITLE
How to share zoom between independents charts

### ISSUE THREAD

**Issue by fredmef** [amcharts/amcharts4#3099]
**Question**

Hello,
here is what I'm trying to do but without any success.
When I zoom into chart1 (div1), I want the exactly the same zoom apply to chart2 (div2).

Here is my codepen:
https://codepen.io/fredmef/pen/mdEowBG 

If you can help me I would appreciate a lot.

Regards,

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Here's an example that might help:
https://codepen.io/team/amcharts/pen/JjXdBVq?editors=0010

**Comment by fredmef** [comment]
Thanks a lot @martynasma !!!!
I've successfully deployed your codepen example in my environment.
