### ISSUE TITLE
Manipulating existing data points in order to remove them isn't possible?

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3101]
Don't know if question or bug...

**Question**
At https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points is described how existing data points could be manipulated.
But "removing" a data point is not possible. The chart still shows the "removed" value (and also legend shows value if set to NaN).
CodePen https://codepen.io/chrisadler/pen/mdEoveE?editors=0010

Commens from the pen
```javascript
  // Update existing value to other value - OK
  // chart.data[2].value = 5;
  
  // Update so far not existing - OK
  // chart.data[3].value = 5; // working
  
  // Update existing value to NaN - NOT OK
  // chart.data[2].value = NaN;
  // Update existing value to undefined - better (legend shows no value) - NOT OK
  // chart.data[2].value = undefined;
  // Delete existing value - like undefined - NOT OK
  delete chart.data[2].value;
  chart.data[3].value = 5; 
  chart.invalidateRawData(); // invalidateData would of course work but that is not wanted 
```

How to remove a data point (without calling invalidateData)?

**Environment (if applicable)**

 - amCharts version: 4.10.11
 - Browser and its version: all

**Comment by martynasma** [comment]
> How to remove a data point (without calling invalidateData)?

There's no way. Sorry.

**Comment by lticadler** [comment]
Ok, thanks for the quick reply.
