### ISSUE TITLE
Axis distortion while switching between the tabs

### ISSUE THREAD

**Issue by matlapuditej** [amcharts/amcharts4#3102]
Hi,
I am rendering XY Charts as tab contents as follows: 
![image](https://user-images.githubusercontent.com/57768603/99412720-a871f200-28ba-11eb-89c5-b5b74f054456.png)

It renders properly at the first render when switching between the tabs after some time, I have noticed that the x-axis(value-axis) has distorted as follows:
![image](https://user-images.githubusercontent.com/57768603/99412767-b4f64a80-28ba-11eb-81fa-581dd61936ca.png)
This distortion will be corrected once the chart is re-rendered upon the data update.

**Comment by martynasma** [comment]
Duplicate. Please refer to [this solution](https://github.com/amcharts/amcharts4/issues/2796#issuecomment-674828053).

**Comment by matlapuditej** [comment]
That solution worked. Thanks
