### ISSUE TITLE
Zoom out button unnecessarily appears when hiding chart

### ISSUE THREAD

**Issue by lab900-marcel-samyn** [amcharts/amcharts4#3103]
**Bug description**

Code example: the stacked bar chart demo: https://www.amcharts.com/demos/stacked-clustered-column-chart/

When you hide one of the series (by clicking on the legend), Amcharts does this:

1. Hides the series
2. Zooms to fit the currently visible series
3. Makes the "Zoom Out" button visible, which zooms out to fit *all* series (including what's hidden, so it just adds some whitespace)

Zooming out is kind of useless there, so I'd like it to not appear (or that there's an option for me to hide it in those cases).

**Environment (if applicable)**

Latest Amcharts, Firefox.

**Comment by martynasma** [comment]
I'm afraid, we won't be able to fix that. It's the underlying logic of how zooming works non vertical axis.

I simply suggest disabling the zoom out button:

```JavaScript
chart.zoomOutButton.disabled = true;
```
