### ISSUE TITLE
Bullet tooltip not showing because series tooltip (activated by snapped chart cursor) overrides it

### ISSUE THREAD

**Issue by azflin** [amcharts/amcharts4#3104]
My XYChart's bullets' tooltips are not showing when I hover over them because I have a series tooltip being activated by a chart cursor snapped to that series. The series tooltip prevents my bullet tooltip from showing - when I disable the series tooltip, the bullet tooltips appear. The gist of my code is below:

```javascript
series.tooltipText = "foo";
this.chart.cursor = new am4charts.XYCursor();
this.chart.cursor.xAxis = dateAxis;
this.chart.cursor.snapToSeries = series;
let bullet = series.bullets.push(new am4plugins_bullets.PinBullet());
bullet.tooltipText = "foo";
```

**Comment by martynasma** [comment]
So you want series tooltip displayed over bullet when cursor is near the bullet, but replace that with a bullet's own tooltip when hovered directly over it?

**Comment by azflin** [comment]
> So you want series tooltip displayed over bullet when cursor is near the bullet, but replace that with a bullet's own tooltip when hovered directly over it?

Correct

**Comment by martynasma** [comment]
Hm, maybe maybe you can use events on a circle element of `PinBullet` to dynamically change `tooltipText` for series:

```JavaScript
bullet.circle.hoverable = true;
bullet.circle.events.on("over", function(ev) {
  series.tooltipText = "bar"
})

bullet.circle.events.on("out", function(ev) {
  series.tooltipText = "foo"
})
```

**Comment by azflin** [comment]
This works. Thank you.
