### ISSUE TITLE
Default formatter isn't displaying correctly if using milliseconds in DurationAxis

### ISSUE THREAD

**Issue by louisnow** [amcharts/amcharts4#3106]
The time axis incorrectly says  x days y minutes, etc instead of x days y hours z minutes, etc when using milliseconds as the value. It skips the hours part.

https://codepen.io/louis9171/pen/ExyJLGR

The time axis works correctly if seconds are used instead.
https://codepen.io/louis9171/pen/bGeJKNg

**Environment (if applicable)**
 - amCharts version 4.10.11
 - Browser and its version Chrome latest
 - Related frameworks and their versions React 16

**Comment by martynasma** [comment]
You can modify your own formats, e.g.:

```JavaScript
chart.durationFormatter.durationFormats.millisecond.day = "d'd' hh:mm:ss"
```

More info:
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-duration/
