### ISSUE TITLE
Hiding 0-value LineSeries data points using 'datavalidated' event

### ISSUE THREAD

**Issue by clintie** [amcharts/amcharts4#3107]
Hi,

There's an example of hiding small value pie chart slices at:

https://www.amcharts.com/docs/v4/tutorials/hiding-small-pie-slices/

But I can't find a way to translate this to LineSeries.  There is a `hide()` method, but it doesn't seem to hide the 0-value items

https://codepen.io/clintw/pen/VwjNELo

```
var series = chart.series.push(new am4charts.LineSeries());
series.dataFields.valueY = "value";
series.dataFields.dateX = "year";
   ...
series.events.on("datavalidated", function(ev) {
  ev.target.dataItems.each((di) => {
      if (di.values.valueY.value === 0 ) {
        di.hide()
        console.log('* hide fired')
      }
  })
})
```
Is there something I'm missing?

Thanks :)

**Comment by martynasma** [comment]
Why not remove specific data points from the data itself before it's passed into chart?

Or if that's not possible, modify source data array **before** it is parsed by chart using `beforedatavalidated` event which kicks before all data items are created.

**Comment by clintie** [comment]
Yes, I've been down those roads.  I'm working with a **live** and **predicted** dataset.  The live part gets updated every minute and am looking to avoid the flicking on `invalidateData()`.  

<pre>
+-------+------------+--------------+------------+
| Time  | Y1: Actual | Y2:Predicted |            |
+-------+------------+--------------+------------+
| 00:01 | 2          | 2            |            |
| 00:02 | 5          | 3            |            |
| 00:03 | 4          | 5            |            |
| 00:03 | 9          | 4            | <-Time now |
| 00:04 | 0          | 7            |            |
| 00:05 | 0          | 9            |            |
| 00:06 | 0          | 10           |            |
| etc.. | etc...     | etc...       |            |
+-------+------------+--------------+------------+
</pre>


I can't go from `null `to a value, as that doesn't update correctly with just `invalidateRawData()` and as I need to continually update data, the data needs to be in the same 'shape' from its instantiation.  `addData()` will need `invalidateData()`.  My hope was to hide data the future/unknown 0 points until they contain the current-time valid data.  

**Actual** value will never hit 0, so if I can hide those the graph would be correct.

**Comment by martynasma** [comment]
There's no way to "hide" a specific data point in a LineSeries. Sorry.
