### ISSUE TITLE
Responsive Label to stay the same percentage width & position on Container?

### ISSUE THREAD

**Issue by ChazUK** [amcharts/amcharts4#3108]
I'm trying to create a gauge that has a single label which can be selected by the user when clicking on a range. The label itself should stay at a consistent size with the rest of the chart.

I can't find a way to do this in AmCharts4 natively, but wondering if it could be combined with the solution here https://css-tricks.com/fitting-text-to-a-container/#just-use-svg

Code Demo: https://codepen.io/ChazUK/pen/ExyJdzY

And this is how I would like it to work, staying the same ratio even when scaled.

![Screenshot 2020-11-18 at 15 25 41](https://user-images.githubusercontent.com/768108/99553823-7b0a6e80-29b6-11eb-95ff-a9bc30ff80e9.png)

**Comment by martynasma** [comment]
I suppose you can adapt this to Gauge chart:
https://www.amcharts.com/docs/v4/tutorials/automatically-resize-label-to-fit-donut-inner-radius/

**Comment by ChazUK** [comment]
Thanks for putting me on the right track @martynasma. AmCharts is so vast it's sometimes quite hard to get a good starting foot.

After fiddling with trying to get the container to display correctly I came up with this. using the height to calculate the scale.

```
const chart = am4core.create(this.chartId, GaugeChart);

const container = chart.createChild(am4core.Container);
container.horizontalCenter = 'middle';
container.verticalCenter = 'bottom';
container.height = am4core.percent(20);
container.x = am4core.percent(50);
container.y = am4core.percent(100);
container.isMeasured = false;

const label = container.createChild(am4core.Label);
label.horizontalCenter = 'middle';
label.verticalCenter = 'bottom';
label.x = am4core.percent(50);
label.y = am4core.percent(100);
label.fontSize = 30; // irrelevant, can be omitted
label.text = 'Auto sizing text';

chart.events.on('sizechanged', () => {
  label.scale = container.bbox.height / this.label.bbox.height;
});
```
