### ISSUE TITLE
AmCharts4 CSS Offsetting Mouse Cursor

### ISSUE THREAD

**Issue by leungk712** [amcharts/amcharts4#3109]
Hello, 

I've created a Vue component where my graph is inside. I originally had padding: 1rem which resulted in the mouse cursor being offset quite a bit as seen below. 

<img width="944" alt="Screen Shot 2020-11-18 at 8 57 14 AM" src="https://user-images.githubusercontent.com/42705941/99554651-ab351b80-297c-11eb-977a-3738d72ce88c.png">

So I removed padding: 1rem resulting in the mouse cursor being aligned but now the graph does not have enough space from the borders. 

<img width="943" alt="Screen Shot 2020-11-18 at 8 56 19 AM" src="https://user-images.githubusercontent.com/42705941/99554752-c99b1700-297c-11eb-8341-6ef1544f1699.png">

I was wondering if there was anyway I can add a "fake" legend to the top but remove the values in it which will naturally provide the white space and proper mouse alignment? Below I added the legend prop but it still has the blue line marker.

![Screen Shot 2020-11-18 at 8 58 24 AM](https://user-images.githubusercontent.com/42705941/99554863-e9cad600-297c-11eb-81dd-e25d623de9b9.png)

Thank you.

**Comment by martynasma** [comment]
Why not use `chart.paddingTop` instead?

**Comment by leungk712** [comment]
Thank you @martynasma for the quick response. Greatly appreciate it.
