### ISSUE TITLE
Combined tooltip ghosting/flickering

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#3110]
I'm experiencing the same issue as in the following example when moving the cursor over the chart back and forth:
https://www.amcharts.com/docs/v4/tutorials/multi-series-shared-tooltip-with-colored-bullets/

How can this ghosting and flickering be prevented? I've tried tinkering with the `tooltip` properties; `rollOutDelay` (which does not seem to affect anything) and `animationDuration` (visible change but does not alleviate the issue). Is there any other setting that could be used?

TIA!

**Comment by martynasma** [comment]
I believe it's coming from tooltip fade animations (one tooltip is fading out while other is fading in).

The solution would be to disable all animations on tooltip:

```JavaScript
series.tooltip.defaultState.transitionDuration = 0;
series.tooltip.hiddenState.transitionDuration = 0;
```

**Comment by sassomedia** [comment]
@martynasma Excellent, that works well! Thanks for updating the example as well. 👍
