### ISSUE TITLE
dataField other than value is not working in heatrules

### ISSUE THREAD

**Issue by MohitKandpal** [amcharts/amcharts4#3114]
I am creating a heat rule and I want to generate the color pattern on a custom property (There is a property **colorValue** in my data that I want to use) instead of using the **value** property of the data. 

But while setting this custom property in the **dataField** of heat rule, I am getting the below error - 

					"**_Cannot read property 'low' of undefined_**"

And as an alternative solution if I am trying to use the **minValue** and **maxValue** properties of heat rules instead of setting any property in dataField then heat rules are not getting applied.

Codepen - https://codepen.io/mohit_k/pen/rNLgmBJ?editable=true%3Dhttps%3A%2F%2Fcodepen.io%2Fteam%2Famcharts%2Fembed%2FLmmpJE%3Fdefault-tab%3Dresult%26editable%3Dtrue%26theme-id%3Ddark

**Comment by martynasma** [comment]
There is no such data field as "colorValue", hence the error.

Use `customValue` instead:

```JavaScript
var series = chart.series.push(new am4charts.ColumnSeries());
series.dataFields.valueY = "value";
series.dataFields.customValue = "colorValue";
series.dataFields.categoryX = "category";
series.columns.template.strokeWidth = 0;

/* Create a heat rule */
series.heatRules.push({
  "target": series.columns.template,
  property: "fill",
  //minValue : 400,
  //maxValue : 1000,
  dataField: "customValue",
  min: am4core.color("#F5DBCB"),
  max: am4core.color("#ED7B84")
 });
```

**Comment by MohitKandpal** [comment]
The provided fix worked well. Thanks for your help.

**Comment by andreipradan** [comment]
If anyone uses MapPolygonSeries, I made it work like this:
```
series.dataFields.value = "myCustomField";
```
Nothing else
