### ISSUE TITLE
i am trying to load more than 30 column and date difference is one day but its shows me month wise column can you help me

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#3116]
/**
 * ---------------------------------------
 * This demo was created using amCharts 4.
 *
 * For more information visit:
 * https://www.amcharts.com/
 *
 * Documentation is available at:
 * https://www.amcharts.com/docs/v4/
 * ---------------------------------------
 */

// Create chart instance
var chart = am4core.create("chartdiv", am4charts.XYChart);

// Add data
chart.data = jQuery.parseJSON("[{\"TotalCount\":\"555\",\"Positive\":\"116\",\"Negative\":\"0\",\"Neutral\":\"398\",\"ContributorsCount\":\"402\",\"Date\":\"21/08/2020\"},{\"TotalCount\":\"356\",\"Positive\":\"87\",\"Negative\":\"0\",\"Neutral\":\"242\",\"ContributorsCount\":\"270\",\"Date\":\"22/08/2020\"},{\"TotalCount\":\"301\",\"Positive\":\"86\",\"Negative\":\"0\",\"Neutral\":\"193\",\"ContributorsCount\":\"220\",\"Date\":\"23/08/2020\"},{\"TotalCount\":\"380\",\"Positive\":\"94\",\"Negative\":\"0\",\"Neutral\":\"248\",\"ContributorsCount\":\"281\",\"Date\":\"24/08/2020\"},{\"TotalCount\":\"529\",\"Positive\":\"117\",\"Negative\":\"0\",\"Neutral\":\"370\",\"ContributorsCount\":\"384\",\"Date\":\"25/08/2020\"},{\"TotalCount\":\"604\",\"Positive\":\"160\",\"Negative\":\"0\",\"Neutral\":\"396\",\"ContributorsCount\":\"428\",\"Date\":\"26/08/2020\"},{\"TotalCount\":\"546\",\"Positive\":\"137\",\"Negative\":\"0\",\"Neutral\":\"366\",\"ContributorsCount\":\"395\",\"Date\":\"27/08/2020\"},{\"TotalCount\":\"552\",\"Positive\":\"136\",\"Negative\":\"0\",\"Neutral\":\"375\",\"ContributorsCount\":\"379\",\"Date\":\"28/08/2020\"},{\"TotalCount\":\"424\",\"Positive\":\"118\",\"Negative\":\"0\",\"Neutral\":\"279\",\"ContributorsCount\":\"312\",\"Date\":\"29/08/2020\"},{\"TotalCount\":\"340\",\"Positive\":\"119\",\"Negative\":\"0\",\"Neutral\":\"205\",\"ContributorsCount\":\"230\",\"Date\":\"30/08/2020\"},{\"TotalCount\":\"429\",\"Positive\":\"104\",\"Negative\":\"0\",\"Neutral\":\"291\",\"ContributorsCount\":\"308\",\"Date\":\"31/08/2020\"},{\"TotalCount\":\"551\",\"Positive\":\"124\",\"Negative\":\"0\",\"Neutral\":\"393\",\"ContributorsCount\":\"388\",\"Date\":\"01/09/2020\"},{\"TotalCount\":\"564\",\"Positive\":\"126\",\"Negative\":\"0\",\"Neutral\":\"397\",\"ContributorsCount\":\"398\",\"Date\":\"02/09/2020\"},{\"TotalCount\":\"646\",\"Positive\":\"160\",\"Negative\":\"0\",\"Neutral\":\"438\",\"ContributorsCount\":\"452\",\"Date\":\"03/09/2020\"},{\"TotalCount\":\"519\",\"Positive\":\"107\",\"Negative\":\"0\",\"Neutral\":\"365\",\"ContributorsCount\":\"388\",\"Date\":\"04/09/2020\"},{\"TotalCount\":\"345\",\"Positive\":\"104\",\"Negative\":\"0\",\"Neutral\":\"214\",\"ContributorsCount\":\"262\",\"Date\":\"05/09/2020\"},{\"TotalCount\":\"304\",\"Positive\":\"77\",\"Negative\":\"0\",\"Neutral\":\"190\",\"ContributorsCount\":\"244\",\"Date\":\"06/09/2020\"},{\"TotalCount\":\"382\",\"Positive\":\"97\",\"Negative\":\"0\",\"Neutral\":\"248\",\"ContributorsCount\":\"286\",\"Date\":\"07/09/2020\"},{\"TotalCount\":\"450\",\"Positive\":\"108\",\"Negative\":\"0\",\"Neutral\":\"313\",\"ContributorsCount\":\"341\",\"Date\":\"08/09/2020\"},{\"TotalCount\":\"576\",\"Positive\":\"130\",\"Negative\":\"0\",\"Neutral\":\"393\",\"ContributorsCount\":\"436\",\"Date\":\"09/09/2020\"},{\"TotalCount\":\"560\",\"Positive\":\"128\",\"Negative\":\"0\",\"Neutral\":\"378\",\"ContributorsCount\":\"403\",\"Date\":\"10/09/2020\"},{\"TotalCount\":\"530\",\"Positive\":\"126\",\"Negative\":\"0\",\"Neutral\":\"370\",\"ContributorsCount\":\"370\",\"Date\":\"11/09/2020\"},{\"TotalCount\":\"249\",\"Positive\":\"59\",\"Negative\":\"0\",\"Neutral\":\"170\",\"ContributorsCount\":\"203\",\"Date\":\"12/09/2020\"},{\"TotalCount\":\"222\",\"Positive\":\"62\",\"Negative\":\"0\",\"Neutral\":\"143\",\"ContributorsCount\":\"161\",\"Date\":\"13/09/2020\"},{\"TotalCount\":\"322\",\"Positive\":\"91\",\"Negative\":\"0\",\"Neutral\":\"207\",\"ContributorsCount\":\"243\",\"Date\":\"14/09/2020\"},{\"TotalCount\":\"382\",\"Positive\":\"98\",\"Negative\":\"0\",\"Neutral\":\"255\",\"ContributorsCount\":\"293\",\"Date\":\"15/09/2020\"},{\"TotalCount\":\"332\",\"Positive\":\"111\",\"Negative\":\"0\",\"Neutral\":\"193\",\"ContributorsCount\":\"254\",\"Date\":\"16/09/2020\"},{\"TotalCount\":\"310\",\"Positive\":\"70\",\"Negative\":\"0\",\"Neutral\":\"210\",\"ContributorsCount\":\"238\",\"Date\":\"17/09/2020\"},{\"TotalCount\":\"137\",\"Positive\":\"36\",\"Negative\":\"0\",\"Neutral\":\"90\",\"ContributorsCount\":\"112\",\"Date\":\"18/09/2020\"}]");

// Create axes
var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
dateAxis.baseInterval = {
  "timeUnit": "day",
  "count": 1
};
dateAxis.renderer.minGridDistance=40;
var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

// Create series
var series = chart.series.push(new am4charts.ColumnSeries());
series.dataFields.valueY = "ContributorsCount";
series.dataFields.dateX = "Date";
series.name = "Sales";

// Create scrollbars
chart.scrollbarX = new am4core.Scrollbar();
chart.scrollbarY = new am4core.Scrollbar();

**Comment by martynasma** [comment]
The first thing to do here would be to set the date format for your data:

https://www.amcharts.com/docs/v4/concepts/data/#Parsing_dates_in_data

**Comment by Mahisandy** [comment]
Thanks
