### ISSUE TITLE
Maps with custom GeoJson data renders incorrect polygon

### ISSUE THREAD

**Issue by komaldudakiya** [amcharts/amcharts4#3117]
I'm following the Amcharts Map tutorial to create a visualisation using other open sourced geodata.

I'm trying to display a map of Virginia counties and I followed the tutorial step by step and this is what I get:
![image](https://user-images.githubusercontent.com/49227447/99800451-62d35480-2b5a-11eb-9f14-104b6a51ec05.png)

Whereas it should look like this:
![image](https://user-images.githubusercontent.com/49227447/99800563-92825c80-2b5a-11eb-870d-8bb7ac62bf5b.png)

I have tried reversing the co-ordinates but it lands to same polygon.

Here is a snippet:
 
    var chart = am4core.create("mapDiv", am4maps.MapChart);
    chart.geodata = mapJson;

    // Set projection
    chart.projection = new am4maps.projections.AlbersUsa();

    // Create map polygon series
    var polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
    polygonSeries.useGeodata = true;

    // Configure series
    var polygonTemplate = polygonSeries.mapPolygons.template;
    polygonTemplate.tooltipText = "{geocoding.name}";
    polygonTemplate.fill = am4core.color("#74B266");

_And the mapJson looks like:_
var mapJson = {
    "type": "FeatureCollection",
    "features": [{
            "type": "Feature",
            "id": 12,
            "properties": {
                "place_id": 235602888,
                "display_name": "Балтасинский район, Татарстан, Приволжский федеральный округ, Россия"
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [-77.655169, 38.942656],
                        [-77.657581, 38.943231],
                        [-77.658739, 38.943508],
                        ...
                   ]
                ]
            }
        }
    ]
}

Is there anything wrong with this code or json?

**Comment by martynasma** [comment]
Try this:
https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/#Map_appears_garbled

**Comment by komaldudakiya** [comment]
Tried this but still getting the same issue.

![county_map](https://user-images.githubusercontent.com/49227447/99819079-e8e5a000-2b46-11eb-9675-4c3a37328905.png)

I am using this GeoJson file

[modifiedVaCounties.zip](https://github.com/amcharts/amcharts4/files/5574539/modifiedVaCounties.zip)

**Comment by mtmibjas** [comment]
You have to rewind your JSON. you can do here https://observablehq.com/

**Comment by martynasma** [comment]
Can you check you are running the latest version? The setting was added in the version 4.10.11.

**Comment by komaldudakiya** [comment]
I was running on 4.9 version.
But rewinding the json from the link you shared worked and map rendered properly.

Thanks for your help.
