### ISSUE TITLE
Can I adjust the height of a flag bullet after the chart has been rendered?

### ISSUE THREAD

**Issue by A143447** [amcharts/amcharts4#3119]
**Question**

Is there a way to adjust the height of a flag bullet after the chart has been rendered?
Problem: We have a chart that has a flag bullet with the height of `chart.plotContainer.pixelHeight`. This means that the pole actually goes above the chart that is displayed. We have a label for that flag bullet that has a label.dy value set to allow for it to be displayed on the screen. Unfortunately when the customer zooms in on the graph, when they get to a particular zoom, the labels on the x-axis are displayed over 2 lines (instead of just one), this pushes the label of the flag bullet out of the viewing area and it cannot be seen. 

What I've tried: Using this documentation: https://www.amcharts.com/docs/v4/tutorials/handling-axis-zoom-events-via-api/, I have been able to work out when something needs to be done to the chart to allow for the flag bullet to be resized but I cannot find how to do this. Making the value that is set in the creation of the flag bullet does nothing. 

Any assistance is greatly appreciated

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can check and maybe figure out a solution?

**Comment by A143447** [comment]
Thanks for your prompt response @martynasma, here is a working CodePen eg for you: https://codepen.io/justineverheijden/pen/abZeXyq

(Drag the zoom from the right hand side to see the label disappear - if you drag from the left, the bullet flag will disappear too!)

**Comment by martynasma** [comment]
Thanks.

Zooming changes date formats on a DateAxis. They vary between one- and two-line formats, which changes height of the axis, and subsequently height of the `plotContainer`.

I've come up with a solution that resizes flag pole on zoom:

```JavaScript
dateAxis.events.on("startendchanged", function() {
  console.log(dateAxis.measuredHeight)
  flag.poleHeight = chart.measuredHeight - dateAxis.measuredHeight + 42;
});
```

Hope you find it useful.

**Comment by A143447** [comment]
Thank you so much for your assistance, I had been trying to adjust the offset (flag.label.dy). The poleHeight adjustment is EXACTLY what I needed.
