### ISSUE TITLE
chart.dataFields.color = 'color' results in "Cannot read property 'toString' of undefined" error

### ISSUE THREAD

**Issue by datasushi** [amcharts/amcharts4#3121]
**Bug description**

I was trying out the Sunburst Demo. Everything works fine up to the point where on tries to override auto color assignment.

In other words, remove line 60 from the following pen to see it work. 

https://codepen.io/datasushi/pen/QWEemjM

**Comment by xorspark** [comment]
You have an invalid color definition in your data:

```
		{ name: "BB", value: 33, color: 1 },
```

Color needs to be a hex/rgb(a) string or an am4core.color instance. Once you fix this line, the chart will work.

**Comment by datasushi** [comment]
🤦🏻‍♂️
Thanks!!
