### ISSUE TITLE
How to set menu alignment when only Annotation is enabled?

### ISSUE THREAD

**Issue by jziggas** [amcharts/amcharts4#3122]
The [Exporting](https://www.amcharts.com/docs/v4/concepts/exporting/) docs give an example for changing the position of the menu via something like:

```
chart.exporting.menu = new am4core.ExportMenu();
chart.exporting.menu.align = 'right';
chart.exporting.menu.verticalAlign = 'bottom';
```

When you add [Annotation](https://www.amcharts.com/docs/v4/tutorials/plugin-annotation/) to a chart it becomes available from the same/similar "..." button menu but there is no clear way to change its position if the `new am4core.ExportMenu();` hasn't also been added. Is this possible?

**Comment by xorspark** [comment]
The docs mention that the annotation creates an export menu if one does not exist. From https://www.amcharts.com/docs/v4/tutorials/plugin-annotation/#Using_with_or_without_export_menu:

> If you don't have Export Menu added to your chart, the plugin will create one for you - without any export options.

You can just add your align settings after enabling the annotation plugin.

```
chart.plugins.push(new am4plugins_annotation.Annotation());
chart.exporting.menu.align = 'right';
chart.exporting.menu.verticalAlign = 'bottom';
```

**Comment by jziggas** [comment]
Dang, somehow I missed that. Thank you.
