### ISSUE TITLE
first, i added bullet to last last point of line chart , but why when i panX on the chart ,the last point has passed Yaxis but it still show bullet , how can i hide this bullet with last point of chart ?

### ISSUE THREAD

**Issue by maophal** [amcharts/amcharts4#3124]
**Question**

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
You probably have `chart.maskBullets = false` set somewhere in your code. Remove it.

**Comment by maophal** [comment]
no , i'm set it like that ,but this how i set the bullets , 

       `let bullet = series.createChild(am4charts.CircleBullet);

        bullet.strokeOpacity = 0;
        bullet.circle.radius = 2;
        bullet.fillOpacity = 1;
        bullet.stroke = "#2cac40";
        bullet.fill = am4core.color("#2cac40");
        bullet.isMeasured = false;

       let secondCircle = bullet.createChild(am4core.Circle);
       secondCircle.radius = bullet.circle.radius + 2;`


       this code i follow this live chart  (https://www.amcharts.com/demos/live-data/),
       because i also want to  make live chart and need to bullet like this,

      thank you so much for quickly reply!.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
