### ISSUE TITLE
Uncaught TypeError: Cannot read property 'touch' of undefined

### ISSUE THREAD

**Issue by ljones-i-nexus** [amcharts/amcharts4#3125]
Using a touch interface anywhere on a page with a chart can result in the console error "Uncaught TypeError: Cannot read property 'touch' of undefined". I've managed to reproduce this on your own pages so have provided links to them rather than a sandbox.

**To reproduce:**
1)  Go to one of the following pages on a touch device or put Chrome into touch device emulation in the dev tools.
2) Touch/click and hold anywhere on the page 

That should be enough to reproduce the issue.

**Reproducible on:**
https://www.amcharts.com/demos/drawing-chart-series-with-mouse-or-touch/
https://www.amcharts.com/demos/line-graph/
https://www.amcharts.com/demos/bar-and-line-chart-mix/
https://www.amcharts.com/demos/trend-lines/

In production it displays a console error. In development it kills the page. This is problematic in development when using elements such as touch and hold tooltips (standard material-ui) or menus opened in the same manner on a page with a chart.

**Environment**

In production we are currently using version 4.10.10 of the library. We are able to reproduce it in Chrome on desktop and mobile. We are using React 17.0.1 in Typescript. We are also using Material-UI 4.9.7, but we do not use the problematic charts in Material components.

**Comment by martynasma** [comment]
Weird. I can't seem to be able to reproduce this.

I tried Chrome in mobile mode on Windows (touch enabled device) and MacOS (not touch enabled, obviously), iPhone emulator on iOS, and some other setups. Can't reproduce the issue on any of the demos.

I'm thinking it might be related to specific hardware or Chrome version, plugin or other setup details.

Any ideas?

**Comment by jeremypanelli1** [comment]
Hi - looks like the first link is able to be reproduced. I am also curious about this because we are also getting this error reported. Let me know if there are any updates to this

https://user-images.githubusercontent.com/72107501/108932091-a3c98200-75fd-11eb-99ac-b0b4b5df79eb.mov
