### ISSUE TITLE
LabelBullet cannot be relatively positioned on StepLine series

### ISSUE THREAD

**Issue by dhiren-eng** [amcharts/amcharts4#3126]
In this codepen sample [https://codepen.io/dhiren530/pen/dypbdWe?editors=0010](https://codepen.io/dhiren530/pen/dypbdWe?editors=0010)  , I've added a LabelBullet for StepLine series and I have placed it on the left of the series using valueLabel.label.x = -50; . Setting the relative position here using am4core.percent is not changing the label position at all and as a result, on zooming the chart it is overlapping with the horizontal line of stepline series. Could anyone please help to keep the position of the label after zoom same as it's position before zoom ? The labels also overlap with the horizontal lines with even a slight increase of screen width.

I've tried other options also. horizontalCenter = right is shifting the label only a little and not in the expected position. Also tried valueLabel.locationX as mentioned in the documentation which is not working. Tried creating a label as child element of the series which is also not happening.

@martynasma

**Comment by martynasma** [comment]
The only workaround I can think of which does not involve dynamically repositioning bullets is to create another series just for label bullets and use [data item location](https://www.amcharts.com/docs/v4/concepts/series/#Data_item_locations).

Here's an example:
https://codepen.io/team/amcharts/pen/949525de90f0801cf19a40c8c5ecb9df

Hope the code there makes sense.

**Comment by dhiren-eng** [comment]
Thanks for your time :) It works
