### ISSUE TITLE
cloudword font-size problem

### ISSUE THREAD

**Issue by XiaohanZhong** [amcharts/amcharts4#3130]
I used tag cloud demo and found a font-size problem, it won't show as font-size in g element property font-size. 
![image](https://user-images.githubusercontent.com/37728326/100326011-593b6800-3004-11eb-96e5-33841167674b.png)

global style.css set font-size to 100% which leads to this result, but this comes from bootstrap and other css files which can't be removed, would like to know if there's any solutions for this. Thanks!

**Comment by martynasma** [comment]
Just adding Bootstrap CSS to the page does not seems to be enough to reproduce this.

Do you have a demo?

**Comment by XiaohanZhong** [comment]
> Just adding Bootstrap CSS to the page does not seems to be enough to reproduce this.
> 
> Do you have a demo?
I found it's from a company internal component css file. I can't demo it. When  I delete that style it's working but it can't be removed. so I wonder is there a way to get font-size attribute value in g element and set it separately to font-size style.

**Comment by martynasma** [comment]
https://codepen.io/team/amcharts/pen/c9cdd991ae9d4d09d23a99ed69c808db
