### ISSUE TITLE
Bug: amcharts can't compile in Jest mode

### ISSUE THREAD

**Issue by dipsaus9** [amcharts/amcharts4#3131]
**Bug description**
amChart is not compatatible with Jest mode. The following error keeps happening:

```
^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import { useLayoutEffect, useRef } from 'react';
      2 |
    > 3 | import * as am4charts from '@amcharts/amcharts4/charts';
```
Tried the transformIgnorePatterns option in the Jest config but without any results.

Running `jest` in any React project with the `@amcharts/amcharts4/core` import will break. transformIgnorePatterns did not solve the problem. Even if the component is being mocked it still breaks. 

amChart version: `4.10.11`
jest version: `26.0,0`

**Environment (if applicable)**

This happens in development environment.

**Comment by martynasma** [comment]
amCharts is not compatible with Jest because it does not support SVG.

More details [here](https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/#Using_amCharts_with_Jest).

**Comment by dipsaus9** [comment]
The components are now being mocked so the tests won't break as Jest does not support SVG. But the error contains a different message regarding the transpile options of amCharts.

A little more details on the problem. I'm using a next setup with babel with the `next/babel` preset. The problem is that next and Jest does not work with a `.babel.rc` file and needs a `babel.config` file instead. This issue is `Next` related so this issue is closed for now. 

I did see more people with this issue so I want to address this problem again. It state in #336  that using the transformIgnorePatterns should solve this problem. This is true. But it should be configured with a correct babel config as well.
