### ISSUE TITLE
chart.dispose() doesn't dispose legends and charts in containers

### ISSUE THREAD

**Issue by sperghetti** [amcharts/amcharts4#3133]
Just putting this here after banging my head against the wall for 3 hours.

If your legend is in a container and/or if a chart is in a container when you use chart.dispose() or chart.disposeChildren() and re-render it you'll get "Chart was not disposed". 

To get around this I did:

```
  clearChart() {
    if(this.chart && this.chart.legend) {
      this.chart.legend.parent.dispose();
    }
    if(this.chart && this.chart.parent) {
      this.chart.parent.dispose();
    }
    if(this.chart) {
      this.chart.dispose();
    }
  }
```

**Comment by martynasma** [comment]
Do you mean that Legend is in a different `Container` than the chart itself?

Yes, in that case it needs to be disposed separately.

In fact we [mention it](https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/#Disposing_external_legend) in the docs.

**Comment by sperghetti** [comment]
Yes, that works if you assign a legend to a container, but if you assign the chart to a container as well it will not dispose when you do chart.dispose() or chart.disposeChildren(). I had to just guess 100 times what could possibly fix it until chart.parent.dispose() worked.

**Comment by martynasma** [comment]
You mean there's one parent `Container` and both chart and legend are direct children to it?

**Comment by sperghetti** [comment]
No, here's how to reproduce:

```
    // Create Chart
    const chartContainer = am4core.create("AMChartLineBarComboChart", am4core.Container);  
    const chart = am4core.create("AMChartLineBarCombo", am4charts.XYChart);
    chart.parent = chartContainer;
 
   // Create Legend
      var legendContainer = am4core.create("AMChartLineBarComboLegend", am4core.Container);
      legendContainer.width = am4core.percent(100);
      legendContainer.height = am4core.percent(100);
      chart.legend.parent = legendContainer;

-> update the chart with new data, run chart.dispose() and chart.legend.dispose() beforehand
-> will still get "chart was not disposed"
-> solution is you also have to run chart.parent.dispose()
```

The reason I have both the chart and the legend in containers is so I can style them differently in CSS without using options.autoSetClassName = true, which is incredibly resource intensive

**Comment by martynasma** [comment]
Makes sense.

I suppose you should just dispose `chartContainer` and `legendContainer`.

No need to dispose the `chart` because it will be disposed as a child of `chartContainer`.

But your way makes sense, too.

**Comment by sperghetti** [comment]
So is the correct syntax chart.[nameofcontainer].dispose()?

I just brute forced a way to do it, it wasn't in the documentation on containers

**Comment by martynasma** [comment]
No.

You should dispose the topmost container. Everything in it will go automatically.

Come to think of it, you should not create your chart in a separate container if you are moving it into another container immediately.

So instead of this:

```JavaScript
const chartContainer = am4core.create("AMChartLineBarComboChart", am4core.Container);  
const chart = am4core.create("AMChartLineBarCombo", am4charts.XYChart);
chart.parent = chartContainer;
```

You should do this:

```JavaScript
const chartContainer = am4core.create("AMChartLineBarComboChart", am4core.Container);  
const chart = chartContainer.createChild(am4charts.XYChart);
```

**Comment by sperghetti** [comment]
This makes a lot more sense, have changed the code to

```
Instantiate:

    const chartContainer = am4core.create("AMChartLineBarComboChart", am4core.Container);  
    const chart = chartContainer.createChild(am4charts.XYChart);
    let legendContainer = am4core.create("AMChartLineBarComboLegend", am4core.Container);

Bind:

    this.chartContainer = chartContainer;
    this.legendContainer = legendContainer;
    

Dispose on componentDidUpdate :
  clearChart() {
    if(this.chartContainer) {
      this.chartContainer.dispose();
    }
    if(this.legendContainer) {
      this.legendContainer.dispose();
    }
  }
```

Works and seems faster - thank you! This would really help in the "working with containers" documentation
