### ISSUE TITLE
Cannot change the Width of a ColumnSeries when yAxis is the CategoryAxis

### ISSUE THREAD

**Issue by MashRoofa** [amcharts/amcharts4#3134]
So i have been trying to resize the column or "bar" size of my chart using the tutorial on am4Charts website. 

The tutorial code works as expected: [Tutorial](https://www.amcharts.com/docs/v4/tutorials/managing-width-and-spacing-of-column-series/)

Now all the tutorial examples are using a yAxis of type ValueAxis and an xAxis of type CategoryAxis. With this configuration the width behaves normally. When i try reverse my axes i.e. make the yAxis a CategoryAxis and the xAxis a ValueAxis the width of the ColumnSeries totally dies out and does not produce the expected outcome. Another issue i noticed is that even with a 100% width and a cellWidth configuration of:

`categoryAxis.renderer.cellStartLocation = 0
categoryAxis.renderer.cellEndLocation = 1
`
The columns or "bars" wont touch each other. For the columns to full all the available space i need to set the cellEndLocation to 1.2

For more details please see the CodePen project i added, trying to replicate the issue.

[CodePen](https://codepen.io/ChrisMash/pen/YzGzvgJ)

**Environment**
am4Charts
Google Chrome - Version 87.0.4280.67 (Official Build) (x86_64)

**Comment by martynasma** [comment]
For bar scenario, you should use `height` instead of `width`.

And if you set `height` to 100%, the bars will touch themselves with `cellStartLocation = 0` and `cellEndLocation = 1`.

**Comment by MashRoofa** [comment]
Well this makes perfect sense thank you 👍
