### ISSUE TITLE
The hide pie series appears blank after calling invalidateRawData.

### ISSUE THREAD

**Issue by foorin** [amcharts/amcharts4#3136]
**Bug description**

When I hiding PieSeries and then call chart.invalidateRawData() it appears blank.
I expect keep the hidden series (not blank).

See jsfiddle https://jsfiddle.net/ygoje5bw/ for more details.

**Environment (if applicable)**

- amCharts version  
  4.10.12
- Browser and its version
  - Google Chrome
    87.0.4280.66
  - Mozilla Firefox
    83.0
  - Microsoft Edge
    87.0.664.47

**Comment by zeroin** [comment]
I can suggest this workaround to fix the problem:
https://jsfiddle.net/20na6ef9/

**Comment by foorin** [comment]
mistake

**Comment by foorin** [comment]
@zeroin 
Thanks for suggest workaround.
I was able to workaround the problem.

**Comment by foorin** [comment]
@martynasma 
Is not this a bug?
If not, I can closing this issue.

**Comment by martynasma** [comment]
> Is not this a bug?
> If not, I can closing this issue.

Well, we are not intending on applying fuzzy logic check. So yeah, please go ahead an close when ready.
