### ISSUE TITLE
Significant performance drop when using chart.addData

### ISSUE THREAD

**Issue by Zookdotcom** [amcharts/amcharts4#3138]
Hi there!

I'm using amCharts in a WebAssembly project that calls a JS function, that initiates the chart, to visualize data I receive from an API using a line chart. The amount of datapoints can get very large at some points in time. More often than not there are 10k+ points in the chart. I have no performance issues doing that, because of data grouping etc. My problem occurs when trying to make the chart automatically update and add datapoints in a given interval. When adding a point using chart.addData, the chart freezes for a more or less significant time making it very unpleasant to use while automatically receiving new data every 2-10 seconds. Is there a way to make this less of an issue?
Heres a code example to demonstrate and give you something to work with:
https://jsfiddle.net/0fLsm9pe/10/

Thank you in advance.

**Comment by GhostKilllaX** [comment]
Having the same issue with performance..

**Comment by martynasma** [comment]
Unfortunately, there's nothing we can do here. When grouping is on, adding new data points needs to re-evaluate groups, hence the delay. Sorry.
