### ISSUE TITLE
I installed @amcharts/amcharts4-geodata module, but i can't find this module in 'node_modules' folder.

### ISSUE THREAD

**Issue by yongzhe-han** [amcharts/amcharts4#3139]
I installed @amcharts/amcharts4-geodata module, but i can't find this module in 'node_modules' folder.

// package.json

![image](https://user-images.githubusercontent.com/52684304/100717291-d1cf6980-33f4-11eb-84b5-e45d9ddf0417.png)

**Comment by martynasma** [comment]
I don't see how this can be possible. Maybe try running `npm install` (or `yarn install`) again?

**Comment by yongzhe-han** [comment]
Try again npm install, it's installed. Thanks for your reply.
