### ISSUE TITLE
Stacked clustered with negative values

### ISSUE THREAD

**Issue by Parallaps** [amcharts/amcharts4#3140]
I'm trying to build a clustered stacked chart. Every column has positive and negative values but amcharts creates gaps for the 2nd and after columns:
https://codepen.io/arseniy-kushnir/pen/GRjJwYa
![image](https://user-images.githubusercontent.com/12274253/100751646-a484ba80-33f8-11eb-9947-9f2963c75a7d.png)

It is working fine if create fake columns with empty results but it adds horizontal gaps between columns

**Comment by martynasma** [comment]
Just disable [`stackToNegative`](https://www.amcharts.com/docs/v4/reference/xyseries/#stackToNegative_property):

```
series.stackToNegative = false;
```

**Comment by Parallaps** [comment]
It makes chart much more worse than previous issue:
Negative values became look like positive. 
![Screenshot_20201203_112217](https://user-images.githubusercontent.com/12274253/100983150-fbee6c00-3559-11eb-881f-d62364201e88.jpg)

**Comment by martynasma** [comment]
Indeed. Will need to get back to you.

**Comment by martynasma** [comment]
I'm sorry but we won't be able to provide a fix for this chart setup. Sorry.

**Comment by puyt** [comment]
I'm having the same problem, why is this a `won't fix` and why doesn't the `stackToNegative` work?

**Comment by martynasma** [comment]
Because it would create a too complex fuzzy logic, which we are trying to avoid. Our charts do not support clustered stacks with both positive and negative values. Sorry.
