### ISSUE TITLE
Char wont load on Angular 10 until scrolled

### ISSUE THREAD

**Issue by ecampoBilbomatica** [amcharts/amcharts4#3142]
We are working with:

- amCharts v4.10.10
- Angular v10

We have reached a problem where an timeline chart won't load until the window is resized or the page is scrolled. Until then the chart is drawn completely blank and no information is shown. We have identified that the chart gets stuck at an event of "beforedatavalidated", and inmediatelly when scrolling it continues throwing events. It is worth mentioning that it throws a second "beforedatavalidated" for as long time as you keep waiting until scrolling or resizing (see gif bellow). 

![2020-12-02_13h57_00](https://user-images.githubusercontent.com/59646904/100875911-f421bf80-34a6-11eb-8643-774a348bbb82.gif)

This only happens when navigating from other component to the component with the chart, not when reloading the page.

**Comment by martynasma** [comment]
Would you be able to post your whole working chart on codesandbox.io so that we can test?

**Comment by ecampoBilbomatica** [comment]
I will try to ilustrate the problem in a codesandbox example. I have been able to address the issue by adding a timeout in the initial load of the chart.

`
  ngAfterViewInit(): void{
    this.browserOnly(() => { 
      setTimeout(() => {             
        this.prepareChart();  
        this.showIndicator();
        this.prepareData();
      },20)
    })
  }
` 

This solution is not ideal and I would like if we could correct the issue in some other way. When I have the codesandbox example ready I will post back.

Thank you for the prompt response.

**Comment by ecampoBilbomatica** [comment]
It seems that the problem is generated by the following configuration line:

`am4core.options.onlyShowOnViewport = true`

Removing it makes the charts work perfectly without the need of the viewport changing.
