### ISSUE TITLE
Titles on top of vertical (value) axis (with reversed axis)

### ISSUE THREAD

**Issue by Mattes83** [amcharts/amcharts4#3143]
**Bug description**

I followed the official demo to put the title of a valueaxis on top like described here: https://www.amcharts.com/docs/v4/tutorials/titles-on-top-of-vertical-value-axis/

This does not work when I inverse the axis with axis.renderer.inversed = true, like shown in this codepen: 
https://codepen.io/mattes83/pen/vYXLYKW

I guess this is a bug, right?
Is there a workaround?

Best regards

**Comment by xorspark** [comment]
You need to set `inversed` before you set up the axis title. Setting it afterwards will reset the positioning values you set on it.

```
  axis.renderer.inversed = true;
  
  // Set up axis title
  axis.title.text = title;
  axis.title.rotation = 0;
  axis.title.align = "center";
  axis.title.valign = "top";
  axis.title.dy = -40;
  axis.title.fontWeight = 600;
```

**Comment by Mattes83** [comment]
Oh, okay. That was quite unexpected.
Thanks for your help!
