### ISSUE TITLE
Can't load custom geojson into map

### ISSUE THREAD

**Issue by andreafonso** [amcharts/amcharts4#3144]
Hello,

I am trying to render a custom geojson into a map without success.

Data loads correctly in geojson.io, and I made sure that I had a unique value for the `id` property inside each feature.

However, when loading the data to the chart it just shows a rectangle. No console errors.

Data can be found [-> here](https://gist.githubusercontent.com/andreafonso/5952d54ec59311839a2432b41991dd29/raw/0761ee3dfedd681435c69e07521e84c80969b1ed/map.geojson)

What may be causing this issue?

**Comment by martynasma** [comment]
This should do the trick:

```
chart.reverseGeodata = true;
```

**Comment by andreafonso** [comment]
Thank you, it does. I think I tried that, but most certainly it was before adding the unique `id` property.
