### ISSUE TITLE
Adding fixed space between columns or grid cells on my bar chart.

### ISSUE THREAD

**Issue by MashRoofa** [amcharts/amcharts4#3145]
I successfully managed to control the space of my column series and also the cell widths by following this guide on am4Charts website. [Managing width and spacing of Column Series](https://www.amcharts.com/docs/v4/tutorials/managing-width-and-spacing-of-column-series/)

However, what Im searching is how to add space between columns without resizing them, for example add 200 pixels between columns, while maintaining the columns sizes and a 200 pixel gap between them. This will require the chart to be wider but this is no issue.

If you can please direct me to the appropriate configuration i will be very grateful.

**Comment by martynasma** [comment]
For this you would need to implement the code that:

1) Checks data and counts number of data items, multiplies it by your target column width + target gap width.
2) Adds expected vertical axis width and chart padding.
3) Resizes chart `<div>` via style to that specific width.

If you do not wish to hardcode vertical axis width you can do this calculation after the chart load.

We do actually have something similar here:
https://www.amcharts.com/docs/v4/tutorials/auto-adjusting-chart-height-based-on-a-number-of-data-items/

It adjust chart height based on a number of items, but it should be easy to adapt to your horizontal scenario.

**Comment by MashRoofa** [comment]
Thank you, your answer was very helpful as always! I was able to replicate the example to resize the width on the xAxis. What is not exactly clear to me though is how to add space between the cells i.e. the target gap. Im thinking to keep my columns at 100% width so i can control their width from the cell width, but then how do i tell each cell to space it self from the other using the desired gap.

Here is my code [Code](https://codepen.io/ChrisMash/pen/BaLjxjX)

Please let me know if Im missing something here.

**Comment by martynasma** [comment]
I suppose you can control those gaps with `cellStartLocation` and `cellEndLocation`:

https://www.amcharts.com/docs/v4/tutorials/managing-width-and-spacing-of-column-series/#Setting_cell_width

**Comment by MashRoofa** [comment]
Ok yes thank you, by using a fixed value for the column width inside the cell this can work with a cellStartLocation = 0 and cellEndLocation = 1. Then i just need to increment the cell width as i want and the gap will increase.

**Comment by MashRoofa** [comment]
@swathishetty hey this can be of help to you [https://www.amcharts.com/docs/v4/tutorials/managing-width-and-spacing-of-column-series/](url)
