### ISSUE TITLE
XY chart individual legend item for each column behaviour

### ISSUE THREAD

**Issue by GergelyBajusz** [amcharts/amcharts4#3146]
https://www.amcharts.com/docs/v4/tutorials/individual-legend-item-for-each-column/

I tried to recreate the above example but I can't seem to find a solution to get the legend default behavior, such as:

- show() hide() column (not the whole series)
- hover over legend markers to show tooltip (show it on the column and not on the marker)

Tried to play with the code beneath which could hide the whole series but can't find a way to hide individual columns.

    chart.legend.itemContainers.template.events.on("hit", () => {
      console.log("Clicked on ");
      let series = chart.series.getIndex(0);
      if (series.isHiding || series.isHidden) {
        series.show();
      } else {
        series.hide();
      }
    });

**Comment by martynasma** [comment]
Check this demo that has both added:
https://codepen.io/team/amcharts/pen/xxEZWPR

I'll add it to the tutorial as well.

**Comment by GergelyBajusz** [comment]
> Check this demo that has both added:
> https://codepen.io/team/amcharts/pen/xxEZWPR
> 
> I'll add it to the tutorial as well.

That is exactly what I was looking for. Thank you!
