### ISSUE TITLE
numberformatter ignored in axis tooltip

### ISSUE THREAD

**Issue by Mattes83** [amcharts/amcharts4#3147]
Hi there!

I have set the numberformatter on the whole chart  with `chart.numberFormatter.numberFormat = "#.0";`
However the marks on the axis which are shown when I move around with the cursor still show more than one decimal place.

This behavior can be seen here: https://codepen.io/mattes83/pen/WNGrzxY

![image](https://user-images.githubusercontent.com/22005222/101132277-0450b080-3607-11eb-8789-870875cb9e06.png)

**Comment by martynasma** [comment]
Number formats are applied only on values from `dataFields`.

`{count}` refers to the data context directly and thus the chart does not know that this is necessarily a number to be formatted.

You can force number formatting with inline function like this: `{count.formatNumber()}`

**Comment by Mattes83** [comment]
Thanks for your reply.
I guess I did not name it correctly, sorry. 
I am not speaking about the number part. When I use the cursor on the chart, amcharts shows marks on both axis indicating the current cursor position. On the yaxis the numberformatter is used correctly, but on the xaxis there are still many decimal places shown.

I marked the element I am speaking about with a red border in the attached screenshot below
![xyplot](https://user-images.githubusercontent.com/22005222/101134046-12540080-360a-11eb-91f5-06ff902aa071.png)

**Comment by martynasma** [comment]
Hm, OK, this is weird floating point idiocy in JavaScript.

We'll need to figure out how to fix this.

Will let you know how it goes.

**Comment by martynasma** [comment]
Ha, OK. So the issue is not in formatter, but rather chart setup.

The X axis is a `CategoryAxis`, which means that they display categories as strings, not numbers, and thus no formatting is applied to them at all.

So in this case, we just need to modify the code that generates the data to apply formatting:

```
data.map(function(item) {
  item.from = chart.numberFormatter.format(item.from);
})
```

**Comment by Mattes83** [comment]
Phew, okay. 
Now it makes sense. 
Thanks for your support!
