### ISSUE TITLE
Prevent map drag outside bounds

### ISSUE THREAD

**Issue by bryanbuchs** [amcharts/amcharts4#3149]
On a Map with drag/pan enabled, is there a method to prevent the user from dragging the contents ("the continents") outside the bounds of the visible area? I'm switching from a Leaflet/MapBox background, and there we used a "maxbounds" setting to lock the user inside 4 corners of the map (https://docs.mapbox.com/mapbox.js/example/v1.0.0/maxbounds/). Doesn't appear that anything exists along those lines in amcharts. (Yes, I realize they're completely different approaches to mapping)

Demo codepen is a clone of the simple, step one map:
https://codepen.io/bryanbuchs/pen/abmdrLx

**Comment by xorspark** [comment]
You can use the [`maxPanOut`](https://www.amcharts.com/docs/v4/reference/mapchart/#maxPanOut_property) to restrict the level of panning outside of the container. A value of zero prevents any part of the map from being dragged outside the container:

```
map.maxPanOut = 0;
```

**Comment by bryanbuchs** [comment]
Thank you - I missed that property. (RTFM, @bryanbuchs). Thank you!
