### ISSUE TITLE
Question - export image including other html elements

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#315]
Is there a way I can use export option (chart to image .png, .svg....) but also include some other DOM html elements when capture is executed, like a table for example?
So the final image should include the chart and other html element.

**Comment by martynasma** [comment]
No, I'm afraid that's currently not possible. Converting HTML to canvas is a whole different (and much more complicated) process than converting SVG to canvas.

There might be some libs out there that do that, but we don't have any experience with those. Maybe some day, but not now. Sorry :(

**Comment by ptorrent** [comment]
Maybe you can use PhantomJS to take a printscreen of your page (server side).

**Comment by martynasma** [comment]
Yes, server-side rendering/capturing might be a solution:
https://www.amcharts.com/docs/v4/tutorials/automating-report-generation-using-puppeteer/

**Comment by aniov** [comment]
Currently I use this https://github.com/tsayen/dom-to-image to capture charts and also other HTML data I need to be on same export image. I'll try also your solution. Ty.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
