### ISSUE TITLE
The way to generate rectangle markers for heat map. 

### ISSUE THREAD

**Issue by mtmibjas** [amcharts/amcharts4#3151]
I have generated a heat map with district value. Is there any way to generate a legend with fillable rectangle markers, Its name, and value?. like a normal legend.  If I put normal legend created code to map it is not working. below one.

` chart.legend = new am4maps.Legend();`

**Comment by martynasma** [comment]
You will need to generate a legend with custom items:

https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items
