### ISSUE TITLE
Docs bug: absent page in docs

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3152]
in export ref 
https://www.amcharts.com/docs/v4/reference/iexportpdfoptions/
look prop pageSize, here link to Export_module
https://www.amcharts.com/docs/v4/?post_type=reference&p=24206
and it's not work

**Comment by martynasma** [comment]
Thanks for the heads up!

We've removed the note with the link altogether, since link to proper type is in the property itself.

![image](https://user-images.githubusercontent.com/1458520/101321410-fa7cb680-386d-11eb-9f39-ccc2947f2560.png)
