### ISSUE TITLE
Export properties minWidth and minHeight don't work

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3154]
Sorry, maybe it's not bug, and i don't understand the mechanism of export. 
I need to export chart allways in fullHD format 1920*1080px or portrait 1080*1920px. 
And in mobile(small) width of browser chart is very narrow
![image](https://user-images.githubusercontent.com/11944160/101362401-810ab580-38b9-11eb-8d82-3be1f64e38e3.png)
But i need to export picture like this (ALWAYS!), independent of browser width
![image](https://user-images.githubusercontent.com/11944160/101362531-aac3dc80-38b9-11eb-9332-5b752c4245e7.png)

Export just scale up current chart image, bot not redraw it for setted width/height in export settings

I use this properties:
```
Chart.main.chart.exporting.formatOptions.getKey("jpg").minWidth = 1920;
Chart.main.chart.exporting.formatOptions.getKey("jpg").minHeight = 1080;
    Chart.main.chart.exporting.formatOptions.getKey("jpg").maxWidth = 1920;
    Chart.main.chart.exporting.formatOptions.getKey("jpg").maxHeight = 1080;
Chart.main.chart.exporting.formatOptions.getKey("jpg").pageMargins = [15,15];
```
And i trigger export, 
```
<a class="js-chart-main-export" href="#" data-type="jpg">JPG</a>
<a class="js-chart-main-export" href="#" data-type="pdf" data-orientation="portrait">Pdf portrait</a>
```
jQuery event handler:
```
$('.js-chart-main-export').on('click', function(e){
        e.preventDefault();
        let action = $(this).attr('data-type');
        if($(this).attr('data-orientation')=='landscape') {
            Chart.main.chart.exporting.formatOptions.getKey(action).pageOrientation = 'landscape';
            Chart.main.chart.exporting.formatOptions.getKey(action).minWidth = 1920;
            Chart.main.chart.exporting.formatOptions.getKey(action).minHeight = 1080;
            Chart.main.chart.exporting.formatOptions.getKey(action).maxWidth = 1920;
            Chart.main.chart.exporting.formatOptions.getKey(action).maxHeight = 1080;
        }else{
            Chart.main.chart.exporting.formatOptions.getKey(action).pageOrientation = 'portrait';
            Chart.main.chart.exporting.formatOptions.getKey(action).minWidth = 1080;
            Chart.main.chart.exporting.formatOptions.getKey(action).minHeight = 1920;
            Chart.main.chart.exporting.formatOptions.getKey(action).maxWidth = 1080;
            Chart.main.chart.exporting.formatOptions.getKey(action).maxHeight = 1920;
        }
        Chart.main.chart.exporting.export(action);
    });

```
When i change browser width, chart container become smaller and for export i need picture in fullHD format, but export picture is a same as in browser - tiny.

**Comment by martynasma** [comment]
These settings scale the chart image, as you correctly pointed out.

If you need to re-render the chart using different dimensions for export, you may find this tutorial useful:
https://www.amcharts.com/docs/v4/tutorials/modifying-chart-for-export/
