### ISSUE TITLE
Custom Sankeynodes Position

### ISSUE THREAD

**Issue by marcabrus** [amcharts/amcharts4#3155]
Hello, 
I got stuck while forcing a layout for a sankey plot I created.
I want that al the terminal nodes are placed at the rightmost part of the plot.

Is it possible?

Here is the code (I modified it starting from https://codepen.io/team/amcharts/pen/LYGZBJV)
```JS
/**
 * ---------------------------------------
 * This demo was created using amCharts 4.
 * 
 * For more information visit:
 * https://www.amcharts.com/
 * 
 * Documentation is available at:
 * https://www.amcharts.com/docs/v4/
 * ---------------------------------------
 */

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

var chart = am4core.create("chartdiv", am4charts.SankeyDiagram);
chart.hiddenState.properties.opacity = 0; // this creates initial fade-in

chart.data = [

  { from: "A", to: "D", value: 10 },
  { from: "B", to: "D", value: 8 },
  { from: "G", to: "J", value: 5 },
  { from: "D", to: "G", value: 5 },
  { from: "D", to: "I", value: 2 },
  { from: "D", to: "H", value: 3 },
  { from: "B", to: "E", value: 4 },
  {from:"E", align:"right"}

];

let hoverState = chart.links.template.states.create("hover");
hoverState.properties.fillOpacity = 0.6;

chart.dataFields.fromName = "from";
chart.dataFields.toName = "to";
chart.dataFields.value = "value";

// for right-most label to fit
chart.paddingRight = 30;
chart.nodeAlign= "top";


// make nodes draggable
var nodeTemplate = chart.nodes.template;
```

**Comment by marcabrus** [comment]
I found this solution:
```JS
chart.events.on('datavalidated', function() {
 chart.nodes.getKey('I').level = 3;
  chart.nodes.getKey('H').level = 3;
})
```
Is it something that can be achieved straight when building the plot?

**Comment by martynasma** [comment]
I'm not sure manipulating hierarchy of the nodes like that is a good way to go about it.

It skews the data, and beats the purpose of the Sankey Diagram, which is used to depict process flow.

**Comment by marcabrus** [comment]
I agree, but I was asked to have a final milestone in the same column for each member. Each member of the plot will have a starting status and a final status. what happens in the middle is left to the plot. I would like o pass the attribute final node via Json, and find a way to set this order not during an event but in a static way

**Comment by martynasma** [comment]
I'm afraid, there's no such built-in functionality. Sorry.

I suppose you can use your approach.

**Comment by marcabrus** [comment]
> I'm afraid, there's no such built-in functionality. Sorry.
> 
> I suppose you can use your approach.

Is there any alternative event, or something that i can use instead of 'datavalidated'? sometimes I modify the filtering of the data and the new data doesn't follow the same layout

**Comment by martynasma** [comment]
Not sure. This is a bit outside of scope of intended usage, so I'm reluctant to suggest "right" approach, because there is no (in my books).

**Comment by marcabrus** [comment]
> Not sure. This is a bit outside of scope of intended usage, so I'm reluctant to suggest "right" approach, because there is no (in my books).

Thank you anyway. Last Question: how to get the maximum level of the sankey?

**Comment by martynasma** [comment]
Well, it's not very clean but you can access chart's hidden property `_levelCount`. (notice the underscore)

**Comment by marcabrus** [comment]
Thank you!
