### ISSUE TITLE
Default legend colors appear on first time chart load and change back to expected colors on legend hover

### ISSUE THREAD

**Issue by dhiren-eng** [amcharts/amcharts4#3157]
In this codepen https://codepen.io/dhiren530/pen/zYKYvXe , when the chart loads for the first time, the legend color for both the boxplots shows the default colors (and not the boxplot colors) as shown in the screenshot below. But after we hover on the legend the colors change to the expected colors i.e. the colors of respective boxplots.
![image](https://user-images.githubusercontent.com/59474883/101605532-48d5b500-3a28-11eb-8f14-b003e1670a00.png)

How to make the legends show the expected colors i.e. colors of the respective boxplots , on first load ?

chart.legend.labels.template.propertyFields.fill = "stroke"; as mentioned in #1943 does not seem to solve the problem for **candlestick or column series** .

@martynasma  @zeroin

**Comment by martynasma** [comment]
Why not set the series `fill` and `stroke` right from the start when its initiated?

```
series.fill = color;
series.stroke = color;
```

**Comment by dhiren-eng** [comment]
It's working now.. Thanks a lot :) Okay that does the job of setting the legend color.. Was not aware of it.. Just wondering if it is mentioned in the documentation
