### ISSUE TITLE
Tooltip in amchart4 is behind the filled series range 

### ISSUE THREAD

**Issue by RiaBasil** [amcharts/amcharts4#3158]
Is there a way I could position tooltip over the filled series of XY chart(Currently  while hovering  tooltip is partially behind the series fill range). Tried setting the tooltip zindex,but didnt work..
      ` this.series.tooltip.zIndex=99;`

![Amchart_Tooltip_Issue](https://user-images.githubusercontent.com/75736804/101636279-1be9c800-3a51-11eb-8841-7e699635ba51.png)

**Comment by martynasma** [comment]
Um, tooltips should go over everything else. Do you have a working example of this chart?

**Comment by RiaBasil** [comment]
Actually it was my mistake.
I had set this.chart.zIndex = 9; which was causing the issue
