### ISSUE TITLE
Slider in Sankeyplot

### ISSUE THREAD

**Issue by marcabrus** [amcharts/amcharts4#3159]
I Have a Sankey with more than 20 levels. Is it possible use a slider in order to limit the levels to show?
Thank you!

**Comment by martynasma** [comment]
There's no such built-in feature. Sorry.

**Comment by marcabrus** [comment]
Sad to know. Thank you for the quick answer. 
@martynasma can I leave it open for few days? , maybe somebody from the community can come with a workaround.

**Comment by martynasma** [comment]
> can I leave it open for few days?

Sure. Issues auto-close in 35 days (I think).
