### ISSUE TITLE
Scripts are blocked by the browser?

### ISSUE THREAD

**Issue by aplogman** [amcharts/amcharts4#3161]
So my chart has been working for almost a year now and then all of a sudden the browser decides to block the scripts and says they are invoked via document.write. Here is my setup for the scripts and one of the warnings: I am not using document.write anywhere in my code and my internet speed is 1gb download lol? I also tried updating the links to the CDN and they did the same thing.

```
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
```

```A parser-blocking, cross site (i.e. different eTLD+1) script, https://cdn.amcharts.com/lib/4/core.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message```

**Comment by martynasma** [comment]
Do you get the same error on amcharts.com, or only in your setup?

Does this happen in all browsers?

Can you try accessing the those CDN urls directly in the browser. Maybe CloudFlare is finding you suspicious, and is displaying a challenge screen? :)

**Comment by aplogman** [comment]
Hmm well I think it fixed now, I auto formatted the code which was set to php originally and it stopped working lol. Really weird as nothing changed besides the spacing which JavaScript is not a stickler about since it can be minified without any issues. I also had to set the scripts to bypass the Cloudflare rocketloader but that was only part of the issue

**Comment by martynasma** [comment]
Thanks. Feel free to close this if you're all set.
