### ISSUE TITLE
TypeScript thinks chart.yAxes.getIndex(<index>) returns Axis instead of ValueAxis

### ISSUE THREAD

**Issue by azflin** [amcharts/amcharts4#3162]
I have the code
```javascript
valueAxis.syncWithAxis = chart.yAxes.getIndex(0);
```
taken from the example in https://www.amcharts.com/demos/multiple-value-axes/. My IDE throws a TS type error "TS2740: Type 'Axis ' is missing the following properties from type 'ValueAxis ': _min, _max, _minDefined, _maxDefined, and 59 more." because it thinks chart.yAxes.getIndex(0) returns Axis and the syncWithAxis property is typed ValueAxis. This errors my compiler during ng serve.

**Comment by martynasma** [comment]
Try casting it:

```TypeScript
valueAxis.syncWithAxis = <am4charts.ValueAxis>(chart.yAxes.getIndex(0));
```

**Comment by azflin** [comment]
Thank you marty.
