### ISSUE TITLE
Water mark Overlapping map

### ISSUE THREAD

**Issue by mtmibjas** [amcharts/amcharts4#3164]
I have done the map view but The watermark is overlapping the image like this. How can I fix this. Any idea?
![SDG_Srilanka_Data (8)](https://user-images.githubusercontent.com/19263982/101984784-a6c4ff80-3ca9-11eb-913e-55fc3f66f2db.png)

**Comment by martynasma** [comment]
Perhaps you can start your map zoomed out a bit:

```
chart.homeZoomLevel = 0.9;
```

**Comment by mtmibjas** [comment]
Thanks, I found and did it.
