### ISSUE TITLE
Get Raw and Column count in legend

### ISSUE THREAD

**Issue by mtmibjas** [amcharts/amcharts4#3165]
**Is there a way to get the table row and column count of the legend?**
According to windows screen size, It is changing dynamically. For example, One Legend is showing in pc screen size 5 col x 4 raw but It is I phone x mobile view 2 col x 10 raw and Galaxy S5 It is 1 col x 20 row.  So How can I get this column and row count in these different scenarios?

**Comment by martynasma** [comment]
Is there specific reason why you need that information? Do you maybe want to change something based on available space? In such case [responsive rules](https://www.amcharts.com/docs/v4/concepts/responsive/) might come in handy.
