### ISSUE TITLE
How to draw payoff charts 

### ISSUE THREAD

**Issue by nagabhushant** [amcharts/amcharts4#3166]
I am trying to draw similar to the snap shot below. I know this was done using amcharts but couldn't find example. Could you please help me to draw similar chart type?

![image](https://user-images.githubusercontent.com/65383847/102047583-81e49f80-3e03-11eb-8527-a1dcbe212c3d.png)

**Comment by nagabhushant** [comment]
Anybody can help on this?

**Comment by nagabhushant** [comment]
No, i couldn't find solution for this.

**Comment by dishantkhatri09** [comment]
@nagabhushant Were you able to find the solution for this? I need to prepare a payoff chart like this one.

**Comment by Stredsto** [comment]
@dishantkhatri09, You might want to check out this repo: https://github.com/Options-Visualizer/Options-Visualizer.github.io?tab=readme-ov-file
I used it a couple of years ago. It’ll need some customization, but it should help you generate the kind of graph you're looking for.
