### ISSUE TITLE
Is it possible to set border color of plot container in XY chart

### ISSUE THREAD

**Issue by RiaBasil** [amcharts/amcharts4#3167]
Is there a way I could have  a different border color for plot container like in the example. I need to have a different color for border top and bottom and also for right and left. But grids should have the default color.
![image](https://user-images.githubusercontent.com/75736804/102078749-74460e80-3e31-11eb-8878-aed6ff3636f9.png)

**Comment by martynasma** [comment]
SVG does not allow setting different border colors.

The only option is to add two vertical [axis ranges](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides), and two horizontal ant precise start/end values.
