### ISSUE TITLE
How to change a solid color to a gradient color, I tried, but failed

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#3168]
https://www.amcharts.com/demos/line-with-changing-color/

The colors in the chart are filled with three solid colors. I want to realize the filling of three gradient colors, but two gradient effects are added, but only one is shown

codepen: [https://codepen.io/fu1996/pen/abmJJbX](https://codepen.io/fu1996/pen/abmJJbX)

**Comment by martynasma** [comment]
Do you want continues gradient across all chart but with changing color in the middle? I'm afraid it's not possible.

You can only do full gradient for each segment using "fillModifier":

https://codepen.io/team/amcharts/pen/b2d4f5dfe9702cfa6890849ff48987ea?editors=0010

**Comment by fu1996** [comment]
> Do you want continues gradient across all chart but with changing color in the middle? I'm afraid it's not possible.
> 
> You can only do full gradient for each segment using "fillModifier":
> 
> https://codepen.io/team/amcharts/pen/b2d4f5dfe9702cfa6890849ff48987ea?editors=0010

哇，太酷了，这个可以增加‘rotation’属性吗？
Wow, that's cool. Can I add the 'rotation' attribute?

**Comment by fu1996** [comment]
> Do you want continues gradient across all chart but with changing color in the middle? I'm afraid it's not possible.
> 
> You can only do full gradient for each segment using "fillModifier":
> 
> https://codepen.io/team/amcharts/pen/b2d4f5dfe9702cfa6890849ff48987ea?editors=0010


我想系统的学习一下amcharts的相关api，请问有详细的文档吗？官方的太多太杂乱了，我的理解能力有限，有没有带着api的相关图例。
I would like to study the related API of amcharts systematically. Do you have detailed documents? There are too many official and messy ones. My understanding ability is limited. Do you have any related illustrations with API.

**Comment by fu1996** [comment]
> Do you want continues gradient across all chart but with changing color in the middle? I'm afraid it's not possible.
> 
> You can only do full gradient for each segment using "fillModifier":
> 
> https://codepen.io/team/amcharts/pen/b2d4f5dfe9702cfa6890849ff48987ea?editors=0010

https://www.amcharts.com/docs/v4/concepts/colors/#Rotating_modifier_generated_gradients
Wow, that's cool. Thank you for your help. This method is very useful for me

**Comment by martynasma** [comment]
Yes, you can apply rotation to fill modifier like this:

```
fillModifier.gradient.rotation = 90;
```

I updated the CodePen.

As for the docs, everything we have is here:
https://www.amcharts.com/docs/v4/

**Comment by fu1996** [comment]
> Yes, you can apply rotation to fill modifier like this:
> 
> ```
> fillModifier.gradient.rotation = 90;
> ```
> 
> I updated the CodePen.
> 
> As for the docs, everything we have is here:
> https://www.amcharts.com/docs/v4/

Ha ha ha, I also found it from the official website. Is there a Chinese version of the official website?

**Comment by martynasma** [comment]
> Is there a Chinese version of the official website?

No, I'm afraid.

**Comment by fu1996** [comment]
> No, I'm afraid.

Ha ha, then I can only communicate with you through Baidu translation. Thank you for your reply. I can close this question.
