### ISSUE TITLE
zoomOutButton appears unwantedly in XY charts that use Animated theme

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#317]
In an XY-chart that has no scrollbars & that has its XYCursor behavior set to "none", I don't expect the zoomOutButton to show anytime.

However, when the chart is created for the first time, animating the line series, the zoomOutButton sometimes appears and immediately disappears (flashes). It looks like this happens when the scale of the Y-axis changes (adapts to the newly animated data).

This effect is visible in Safari at least. I think this zoomOutButton should not show when animating on init.

Codepen demo: https://codepen.io/team/amcharts/pen/dqWBeb

**Comment by zeroin** [comment]
This was solved in one of the previous releases.
