### ISSUE TITLE
 UI issue when resizing

### ISSUE THREAD

**Issue by wawahuy** [amcharts/amcharts4#3170]
I use angular 9 and amcharts4:  ^4.10.5,

Default:
![image](https://user-images.githubusercontent.com/16779694/102187665-db71ca80-3ee6-11eb-9d40-2007634dfe28.png)

Resize:
![image](https://user-images.githubusercontent.com/16779694/102187806-1116b380-3ee7-11eb-97e7-9d89ebfebe07.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by wawahuy** [comment]
Sorry my code can't run due to it having too many linked modules, but I've included the core parts
https://jsfiddle.net/rbwvpx3s/
