### ISSUE TITLE
wrong links, spelling errors and syntax

### ISSUE THREAD

**Issue by jswelsh** [amcharts/amcharts4#3172]
A list of things from docs and such, some of these may not be proper corrections, but I'm pretty sure they need to be fixed. 

Located:
https://www.amcharts.com/download/download-editor/

the links to amcharts 4 editor isnt correct, take you to amcharts 4 not the editor
"Our **amCharts Editor 4 repository** is up-to-date and contains both ES2015 and JavaScript version."
the link is
https://github.com/amcharts/amcharts4
should be->
https://github.com/amcharts/editor4

"Not sure where to start? How about checking out **“Getting started”** article in amCharts Editor 4 documentation website."
the link is 
https://www.amcharts.com/docs/v4/getting-started/basics/
should be->
https://www.amcharts.com/docs/editor4/

Located:
https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/

Actual geographical data for the maps **is** contained in a separate package @amcharts/amcharts4-geodata. 

is -> are

For **example** pie contains all of the functionality required for creating Pie charts.
example -> example,

 use **it's** npm name @amcharts/amcharts4/....
 it's -> its
 
 For **consistence**, we suggest you do the same.
 consistence -> consistency
 
 The element **mus** exist before calling create().
 mus -> must
 
 It won't be created if it doesn't, resulting **in error**.
 in error -> in an error
 
 are created using chart's respective series property, and **it's** create() method.
 it's -> its
 
 
"Please refer to **an articles** on specific chart types, for more in-depth information about those. We are not going to get into particular details here."
I think "an articles" is referring to "amCharts documentation"? 

Basically this means that TS will go to great lengths to ensure you don't do anything stupid, like assigning wrong value, or using wrong class type.
->
This means that TS will go to great lengths to ensure you don't do anything stupid, like assigning the wrong value or using the wrong class type.

 Sublime Edit (shown in screenshot above), or Atom will outline error as well as provide description for the property, so that you know how to use it.
 ->
Sublime Edit (shown in the screenshot above), or Atom will outline errors as well as provide a description for the property so that you know how to use it.

Check out this tutorial for information on how you can lazy-load amCharts modules on-deman
deman -> demand

Located:
https://www.amcharts.com/docs/v4/concepts/tooltips/#Additional_dunctionality
dunctionality -> functionality
(the route works, just a spelling error in the route, I can remeber what link led me to that)

It's possible to make the tooltip show **on particular** element without
on particular -> on a particular

Located:
https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/#Base_chart
This will place **out** tooltip directly above the data point, 
out -> our

Located:
https://www.amcharts.com/docs/v4/concepts/tooltips/#Text_versus_HTML
Setting tooltipText will produce tooltips using SVG.

Setting **tooltipText** will use HTML to display tooltip contents.
tooltipText -> tooltipHTML.

Located:
https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/#Limitations
so you might also want to set tooltipText as a mean for alternative content.
mean -> means

Normally, cursor is hidden (along its tooltips)
along its -> along with its tooltips (I don't acctually know what exactly it should say, I think its this)

code that displays tooltip and rely on it to be exported to image,
rely -> relies

https://www.amcharts.com/docs/v4/tutorials/building-drill-down-maps/#Loading_maps_dynamically
in specifically **JavaScript** not **typescript** code example under loading maps dynamically
```

  if (map)
    countrySeries.geodataSource.url = "https://cdn.amcharts.com/lib/4/geodata/json/" + map + ".json";
    countrySeries.geodataSource.load();
  }
});
```
`if (map)`  is still missing `{`

**Comment by martynasma** [comment]
Thanks! Most of those were corrected.
