### ISSUE TITLE
How to add a mask with specified width and height?

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#3173]
codepen:[https://codepen.io/fu1996/pen/jOMmxRx](https://codepen.io/fu1996/pen/jOMmxRx)

demo:
![image](https://user-images.githubusercontent.com/42232973/102455123-04769480-407a-11eb-8336-4c47a3d65895.png)

target：
1. The highest point of data can be obtained as mask height

2. Any data point can be specified as the starting position of width

3. The last data in the chart is used as the end position of width
![image](https://user-images.githubusercontent.com/42232973/102455339-69ca8580-407a-11eb-972c-1ba62b810e73.png)

**Comment by martynasma** [comment]
A bit hacky but will do the trick:

```JavaScript
var fillSeries = chart.series.push(new am4charts.LineSeries());
fillSeries.dataFields.valueY = "value";
fillSeries.dataFields.dateX = "date";
fillSeries.ignoreMinMax = true;
fillSeries.fill = am4core.color("rgba(128,128,128)");
fillSeries.fillOpacity = 0.3;
fillSeries.strokeWidth = 0;
fillSeries.data = [];

chart.events.on("datavalidated", function() {
  var val = valueAxis._maxReal;
  var startDate = new Date(2018, 3, 22);
  var endDate = new Date(dateAxis.max);
  fillSeries.data = [{
    date: startDate,
    value: val
  }, {
    date: endDate,
    value: val
  }]
})
```

https://codepen.io/team/amcharts/pen/f83871e4d08ea484eaa2c448e1133f58

**Comment by fu1996** [comment]
> A bit hacky but will do the trick:
> 
> ```js
> var fillSeries = chart.series.push(new am4charts.LineSeries());
> fillSeries.dataFields.valueY = "value";
> fillSeries.dataFields.dateX = "date";
> fillSeries.ignoreMinMax = true;
> fillSeries.fill = am4core.color("rgba(128,128,128)");
> fillSeries.fillOpacity = 0.3;
> fillSeries.strokeWidth = 0;
> fillSeries.data = [];
> 
> chart.events.on("datavalidated", function() {
>   var val = valueAxis._maxReal;
>   var startDate = new Date(2018, 3, 22);
>   var endDate = new Date(dateAxis.max);
>   fillSeries.data = [{
>     date: startDate,
>     value: val
>   }, {
>     date: endDate,
>     value: val
>   }]
> })
> ```
> 
> https://codepen.io/team/amcharts/pen/f83871e4d08ea484eaa2c448e1133f58

Wow, you are too good. I've been thinking about it for a long time. Thank you very much
