### ISSUE TITLE
 In amcharts sunburst-diagram how to set a particular slice as selected or pre-pulled onload? 

### ISSUE THREAD

**Issue by gitrajeshr** [amcharts/amcharts4#3175]
I am able to do this in case of amcharts pie-chart using 

  VarPiechart.events.on("ready",function(ev){
         VarPieseries.slices.getIndex(0).isActive=true 
    }

 But similar code is not working with sunburst-diagram. The slices array is empty.

**Comment by martynasma** [comment]
That's because Sunburst creates multiple series automatically.

So, in your case, if you want to pull out the first slice of the inner-most ring:

```JavaScript
VarPiechart.events.on("ready",function(ev){
  target.series.getIndex(0).slices.getIndex(0).isActive = true;
}
```
