### ISSUE TITLE
GeoJSON format

### ISSUE THREAD

**Issue by jswelsh** [amcharts/amcharts4#3177]
not sure if This is the best place for this but I feel there is a gap in the docs, Located: [@ creating custom maps](https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/)
I think it would be very helpful for devs inexperienced with working with GeoJSON if there was a section that explicitly shows the necessary structure of the GeoJSON.

sort of like how [examining exported file](https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/#Examining_exported_file)  

I see there is a [Troubleshooting](https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/#Troubleshooting) section
but stating how certain properties are necessary for the map to render properly, ie 
- Each feature of a GeoJSON must have an unique id, id should go as feature property
- when using custom software to generate GeoJSON, real longitudes/latitudes lines are required
- order of Co-ordinates matter and `chart.reverseGeodata = true;` may be able to fix

I think it's important info, the docs make it seem like having a GeoJSON is all you need ["Congratulations! You're all set. amCharts 4 maps supports GeoJSON format out of the box."](https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/#GeoJSON).
***
[GeoJSON template only shows](https://geojson.org/)
 ``` {
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
```
yet amCharts needs some additions beyond that basic form.
Having a more prominent disclaimer especially within this [section](https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/#GeoJSON) even something as simple as "Make sure your custom GeoJson has this structure/includes these key:values and this order" could save on searches/posts on SO or here. 
Just a thought.

**Comment by martynasma** [comment]
Thanks for the suggestion!

That said, we don 't have any special requirements or deviations from GeoJSON standard. So, I'm not entirely sure how this would need to be worded out.

In most cases, user does not even have to look into the the resulting GeoJSON file, much less make any edits there.

Besides that tutorial's topic is about converting formats, not about GeoJSON format in general, which there is plenty of documentation around the web of.
