### ISSUE TITLE
legend: how can I set the fill color of the marker in the "active" state?

### ISSUE THREAD

**Issue by mk-startialab** [amcharts/amcharts4#3180]
**Question**
I'm  trying to customize legend color in the "active" state.
"label" and "valueLabel" were easy to change.

But fill color of marker is not.
To me, it seems to be fixed as "#999999".

I wrote codes like this jsFiddle:
https://jsfiddle.net/ynghkvfq/2/

Please help me.

**Environment (if applicable)**

amCharts version: latest CDN (https://www.amcharts.com/lib/4/core.js)

**Comment by martynasma** [comment]
The only workaround I can think of is this:

```JavaScript
markerTemplate.events.on("childadded", function(event) {
  var child = event.newValue;
  var activeState = child.states.create("active");
  activeState.properties.stroke = am4core.color(legendDisabledColor);
  activeState.properties.fill = am4core.color(legendDisabledColor);
});
```

**Comment by mk-startialab** [comment]
@martynasma Oh, the state can be add...
Thanks a lot!
