### ISSUE TITLE
Delete Spaces Between Page And Chart 

### ISSUE THREAD

**Issue by fightlikeagirl** [amcharts/amcharts4#3181]
Hello, I am really new about this chart. I want to use tag cloud (demo is here :https://www.amcharts.com/demos/tag-cloud/#code)  without title or subtitle. I saw big spaces all around  the cart . I try to delete them with 
```
chart.innerRadius = am4core.percent(40);
chart.paddingTop = 0;
chart.marginTop = 0;
chart.valign = 'top';
chart.contentValign = 'top';
```
 but that doesn't work.  Any help I really apprepiate it . Thank you

**Comment by martynasma** [comment]
If the chart container is big and there are too few words to fill it up (font size is capped to 20% of the container by default), the cloud won't fill up the whole area.

You can set series `maxFontSize` to a bigger size if you want allow words growing very big, e.g.:

```
series.maxFontSize = am4core.percent(50);
```

**Comment by fightlikeagirl** [comment]
Thanks it worked :)
