### ISSUE TITLE
Individual NumberFormatter is not working in Dual Value Axis charts

### ISSUE THREAD

**Issue by karthikeyanTEME** [amcharts/amcharts4#3182]
Before All..Thanks for this wonderful library.
The problem I am facing is,
I an dual axis chart, I couldn't apply separate number formatter for  individual axis. This happens only when both the axes are of type ValueAxis.
Sample Config:
```JSON
 "yAxes": [
                {
                  "type": "ValueAxis",
                  "id": "v1",
                  "title": {
                    "text": "Requests"
                  },
                  "numberFormatter": {
                    "type": "NumberFormatter",
                    "numberFormat": "#.0a"
                  }
                },
                {
                  "type": "ValueAxis",
                  "id": "v2",
                  "renderer": {
                    "opposite": true
                  },
                  "title": {
                    "text": "Bytes Delivered"
                  },
                  "numberFormatter": {
                    "type": "NumberFormatter",
                    "numberFormat": "#.0b"
                  }
                }
              ],
              "series": [
                {
                  "yAxis": "v1",
                  "type": "LineSeries",
                  "dataFields": {
                    "valueY": "Requests",
                    "dateX": "time"
                  },
                  "strokeWidth": 2,
                  "tooltipText": "Requests: {valueY.formatNumber('#.0a')}"
                },
                {
                  "yAxis": "v2",
                  "type": "ColumnSeries",
                  "dataFields": {
                    "valueY": "Bytes",
                    "dateX": "time"
                  },
                  "strokeWidth": 2,
                  "tooltipText": "Bytes: {valueY.formatNumber('#.0b')}"
                }
              ]
```

On my initial analysis, it seems only one number formatter instance is created in container level and the same is inherited by all its Child components. So the value (#.0a) set by ValueAxis-1 got overwritten to (#.0b) when processConfig of ValueAxix-2 

At the same time different formatter for tooltip is working fine.
Attaching a screen shot,
![image](https://user-images.githubusercontent.com/5602971/103334362-00457080-4a97-11eb-9d29-f9c7ca5b3236.png)

**Comment by martynasma** [comment]
Try forcing the creation of a new NumberFormatter object:

```
"numberFormatter": {
  "type": "NumberFormatter",
  "forceCreate": true,
  "numberFormat": "#.0b"
}
```

**Comment by karthikeyanTEME** [comment]
> Try forcing the creation of a new NumberFormatter object:
> 
> ```
> "numberFormatter": {
>   "type": "NumberFormatter",
>   "forceCreate": true,
>   "numberFormat": "#.0b"
> }
> ```
@martynasma 
Updating my configuration with "forceCreate": true as below worked for me
`"yAxes": [
                {
                  "type": "ValueAxis",
                  "id": "v1",
                  "title": {
                    "text": "Requests"
                  },
                  "numberFormatter": {
                    "type": "NumberFormatter",
                    "forceCreate": true,
                    "numberFormat": "#.0a"
                  }
                },
                {
                  "type": "ValueAxis",
                  "id": "v2",
                  "renderer": {
                    "opposite": true
                  },
                  "title": {
                    "text": "Bytes Delivered"
                  },
                  "numberFormatter": {
                    "type": "NumberFormatter",
                    "forceCreate": true,
                    "numberFormat": "#.0b"
                  }
                }
              ],`
              
              **THANK YOU**
