### ISSUE TITLE
The example of using PDF export in Korean is not working 

### ISSUE THREAD

**Issue by hyerin3854** [amcharts/amcharts4#3183]
I am writing regarding some error in exporting pdf file in Korean. As seen on your homepage, it should be printed in Korean, which is impossible. I want to export pdf in Korean through my Project, and I try to export Pdf in Korean. But I think there is some bug in your homepage guide. I'm looking forward to receiving your reply soon. Thank you.

link:https://www.amcharts.com/docs/v4/tutorials/using-pdf-export-fonts/

![image](https://user-images.githubusercontent.com/61176382/103363862-8bf2e780-4aff-11eb-92c1-9f2db94407c8.png)

**Comment by martynasma** [comment]
Indeed. Fonts work OK when exporting PDF as image, but not as data. Thanks for the heads up!

We'll need to fix it.

Will keep you posted.

**Comment by martynasma** [comment]
OK, so it's not a bug, but rather incomplete configuration. Exporting PDF as data has different option set so it needs to be set separately:

```JavaScript
var pdfOption = chart.exporting.getFormatOptions("pdf");
pdfOption.addData = true;
pdfOption.addURL = false;
pdfOption.font = am4fonts_notosans_kr; // Code for Korean patch.

var pdfDataOption = chart.exporting.getFormatOptions("pdfdata");
pdfDataOption.addURL = false;
pdfDataOption.font = am4fonts_notosans_kr; // Code for Korean patch.
```

I updated the related CodePen demo, and will update the documentation article accordingly.

Thank you for bringing this to out attention!

**Comment by hyerin3854** [comment]
Thank you for your fast reply!!
