### ISSUE TITLE
Can't draw properly multiple values for same day

### ISSUE THREAD

**Issue by gbarrionuevo** [amcharts/amcharts4#3185]
**Question**

I'm not able to draw properly two or more values for same day.

![image](https://user-images.githubusercontent.com/17553670/103411311-15310b00-4b4e-11eb-9d4b-851ebe1c5af3.png)

**Environment (if applicable)**

amCharts version 4

**Additional context**

I've tried using dateAxis min / max but not success

**Comment by martynasma** [comment]
What would you consider "proper" plot of such data?

**Comment by gbarrionuevo** [comment]
@martynasma  i didn't explain myself correctly, in the image there are two values for the same day but with diferent hours, if the graph scale adjust like that i would at least expect to be able to display a tooltip for both data points instead just one when hovering it

**Comment by martynasma** [comment]
In that case you might need to set granularity of your data manually. More about it here:

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Manually_specifying_data_granularity
