### ISSUE TITLE
Issues with examples compilation on Angular

### ISSUE THREAD

**Issue by grzegorz-ogrodowski** [amcharts/amcharts4#3186]
Hello,

I used examples from documentation https://www.amcharts.com/docs/v4/chart-types/.

I have few issues with compilation:

`//add adapter for href to load correct image
        image.adapter.add("href", function (href, target) {
            var dataItem = target.parent.dataItem;
            if (dataItem) {
                //treeMapDataItem not compiled but works --_--
                return "https://www.amcharts.com/lib/images/logos/" + dataItem.treeMapDataItem.name.toLowerCase() + ".png";
            }
        });`
        
Here I have issue:

> Property 'treeMapDataItem' does not exist on type 'DataItem'

Next one:

` var axis = chart.xAxes.push(new am4charts.ValueAxis());
        axis.min = 0;
        axis.max = 1000000;
        axis.strictMinMax = true;
        axis.numberFormatter.numberFormat = "#a";`
        
 Error:
 
> Argument of type 'ValueAxis<AxisRenderer>' is not assignable to parameter of type 'Axis<AxisRendererCircular>'.
  Types of property '_renderer' are incompatible.
    Type 'AxisRenderer' is missing the following properties from type 'AxisRendererCircular': pixelRadiusReal, axisRendererY, radius, pixelRadius, and 6 more.
    
I have few similar issues with compilation.

I am using amcharts4 in 4.10.13 version, angular 9 version and typescript in 3.7.5 version/

**Comment by martynasma** [comment]
You may need to cast the type:

```
(<TreeMapSeriesDataItem>dataItem).treeMapDataItem
```
