### ISSUE TITLE
XY Chart vertical axis zoom causes element disappearance

### ISSUE THREAD

**Issue by ncircleamit** [amcharts/amcharts4#3187]
We have created a gantt chart using this demo: https://www.amcharts.com/demos/gantt-chart-dates/

While zooming in the vertical axis some of the bars disappear unexpectedly (attached a gif for reference).
What could be the probable reason behind it?

![ganttChartIssue](https://user-images.githubusercontent.com/10433606/103554008-45710480-4ed4-11eb-93c9-0a04cf66ee8f.gif)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by ncircleamit** [comment]
Sure @martynasma,
Here's the link to jsFiddle: https://jsfiddle.net/amit_mandal/0ewLr2q9/6/

**Comment by martynasma** [comment]
This is solvable if you set data directly on chart, rather then on series.

I modified the fiddle: https://jsfiddle.net/amcharts/xj63nLu1/1/

**Comment by ncircleamit** [comment]
Thanks, it worked.
