### ISSUE TITLE
Legend CSS

### ISSUE THREAD

**Issue by simonziegler** [amcharts/amcharts4#3188]
Hi,

I'm working out how to style a chart with CSS (colours, fonts etc), because I need to be able to hot swap CSS for day/night themes. I have worked out how to do this for a line chart stroke color by adding a series id and then referencing the resultant new CSS class name! I need to be able to control the stroke color on the series legend too however but cannot find out how or if I can add a CSS class to a series legend. Is there a way to do this?

Many thanks, Simon

**Comment by martynasma** [comment]
I suggest you explore legend items with Chrome development tools and figure how you can target those with CSS.

I'm afraid we do not have any specific documentation for it.

**Comment by simonziegler** [comment]
Thanks - I think I'm getting there. I suspect I need to use an adapter to mark a class somewhere but am struggling with adapters and understanding their docs generally ATM.
