### ISSUE TITLE
[Question] Legend for Pie charts added dynamically in a map

### ISSUE THREAD

**Issue by mahesh-chotrani** [amcharts/amcharts4#3189]
**Question**
By following the example as provided in [this link](https://www.amcharts.com/demos/map-dynamic-pie-charts/), I could have pie charts rendered for various dynamic positions (_latitudes / longitudes_). This is not only for continents, but also for country and state geo data. 

![image](https://user-images.githubusercontent.com/50296623/103767859-60b05100-5047-11eb-98c7-46823d2956cc.png)

But would also like to include legend for the dynamic pie charts in the chart bottom. 

Because there are 2 series (_i.e., map polygon and pie_), when following line is included, 2 black dots are included. 
> `chart.legend = new am4charts.Legend();`

Is there a way to include legend only for slices of the pie charts ?

**Comment by martynasma** [comment]
Do you want one single legend for all pie charts, or multiple legends for each individual pie chart?

**Comment by mahesh-chotrani** [comment]
One single legend (_towards the bottom of the chart_) for all the pie charts because the series remains the same.

**Comment by martynasma** [comment]
In that case, you will need to create a custom legend, and add the items manually:
https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items

**Comment by mahesh-chotrani** [comment]
Thanks for the suggestion @martynasma . I could include legends using the sample above. 
The only issue, is that could not configure the legend position. It simply ignores `bottom` and `right` values. 

Here is the code - 

>  `chart.legend = new am4charts.Legend();`
>  `chart.legend.parent = chart.chartContainer;`
>  `chart.legend.position = "bottom"; // "right" also does not works. only "left" and "top" works`
>  `chart.legend.data = legendData; // sample data`
> 

![image](https://user-images.githubusercontent.com/50296623/103974619-38843780-5198-11eb-8f47-7545597c0a04.png)

Appreciate if you can let me know what is possibly wrong here.

**Comment by martynasma** [comment]
Try `chart.legend.valign = "bottom"`.

**Comment by mahesh-chotrani** [comment]
Thanks for quick reply and it worked ! 
Though I am not sure why `legend.position` did not, as that is what I see in most of the examples. 

There is one more query around this - the legends are painted above the map image, though in any of the other chart (_column or bar_) legends are painted below the axis and hence do not overlap the image. (_Below is a screen capture of two charts with same data_). I am not using an external container to render legends. 

Any idea, why that should be ? I'll appreciate in case of any pointers around this

![image](https://user-images.githubusercontent.com/50296623/104011270-d47f6480-51d3-11eb-95e3-436029fb87f5.png)

**Comment by martynasma** [comment]
This is because `MapChart` is constructed differently than other charts.

To give legend some space, you may add some padding to chart:

```JavaScript
chart.paddingBottom = 100;
```

**Comment by mahesh-chotrani** [comment]
Thanks for confirming that this issue is the way `MapChart` are being rendered and not a code issue. 

Unfortunately, `chart.paddingBottom` did not help. It did include `padding`, but space is after legend being rendered. 

![image](https://user-images.githubusercontent.com/50296623/104179396-cb8bce80-5431-11eb-82de-8b3439bfe6df.png)

Any other property you can suggest ?

**Comment by martynasma** [comment]
Can you post your chart setup online somewhere, e.g. on CodePen?

**Comment by mahesh-chotrani** [comment]
I have copied all code from this example - https://www.amcharts.com/demos/map-dynamic-pie-charts/

And after populating the `pieSeries.data`, you can just copy these lines as is. 

```
  // play with padding values
  chart.paddingTop = 0;
  chart.paddingBottom = 100;
  chart.paddingRight = 0;
  chart.paddingLeft = 0;

  // set inner radius
  pieChartTemplate.innerRadius = am4core.percent(40);
  
  // custom colors and legend options
  const options = {"colors":{"0":"#974FFF","1":"#0EC878","2":"#FE17F5","3":"#FEAF17","4":"#FF6657","5":"#17B4FE","6":"#1EF4A7","7":"#FFDB29","8":"#F0441C","9":"#1665FF"},"chart":{"values":["1","2","3","4","5"]}};

  // prepare legend data
  const legendData = [];
  if (options.chart.values && options.colors) {
      options.chart.values.forEach((val, index) => {
         legendData.push({name: val, fill: options.colors[index]});
      });
  }

  // including legend
  chart.legend = new am4charts.Legend();
  chart.legend.data = legendData;
  chart.legend.valign = 'bottom';
  chart.legend.itemContainers.template.clickable = false;
  chart.legend.itemContainers.template.focusable = false;
  chart.legend.itemContainers.template.cursorOverStyle = am4core.MouseCursorStyle.default;

```
Let me know, in case you need any other information. 

(attached screen shot)

![image](https://user-images.githubusercontent.com/50296623/104200135-4a8f0000-544e-11eb-8eb7-b5e1d46da423.png)

**Comment by martynasma** [comment]
This should do the trick:

```JavaScript
chart.legend.parent = chart.tooltipContainer;
```

**Comment by mahesh-chotrani** [comment]
Thanks for providing the solution. Observed that the legends are shifted more towards the container bottom with this.

Though it worked for legends which are of few character, but legends with large number of characters, it again becomes the same.  Also, in case of zoom in (and all legends with small number of characters), the chart comes under the legends.

![image](https://user-images.githubusercontent.com/50296623/104304427-5da6dc00-54f1-11eb-96c0-9a9bc2b920b3.png)

Truncating of legends can be one of options, but unacceptable to our customers.

One of the other options I thought was to have the legend scrollable by using below properties
```
 chart.legend.scrollable = true; // enable scrolling
 chart.legend.maxHeight = 200; // set some height
```
But this, along with setting **legend.parent** to `chart.tooltipContainer` gives an error as below and legends are not rendered - 
```
Cannot read property 'uidAttr' of undefined
```
![image](https://user-images.githubusercontent.com/50296623/104304946-12d99400-54f2-11eb-8296-30e5994d401b.png)

Let me know, in case more information required on any of these cases. Thanks

**Comment by martynasma** [comment]
I suggest you just move the legend to an completely external div, so it's not affected by any way by the map itself.

https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/

**Comment by mahesh-chotrani** [comment]
Thanks @martynasma !

Following the tutorial to have external container for legends, here are the steps I did to create one - 

```
chart.legend = new am4charts.Legend();
chart.legend.data = legendData; // sample data
let amLegendContainer = am4core.create(legendContainer, am4core.Container);
// let the size be 100%
amLegendContainer.width = am4core.percent(100);
amLegendContainer.height = am4core.percent(100);
// set parent
chart.legend.parent = amLegendContainer;
// legends not clickable
chart.legend.itemContainers.template.clickable = false;
chart.legend.itemContainers.template.focusable = false;
chart.legend.itemContainers.template.cursorOverStyle = am4core.MouseCursorStyle.default;
```

As per the tutorial -
> External legend is a separate instance that needs to be disposed as separately, as it won't get disposed together with the chart.

(https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/#Disposing_external_legend)

So, have included below code
```
// dispose legend
if (chart.legend && chart.legend.dispose) {
    chart.legend.dispose();
}
```
And below line to dispose charts (_which we already have_).
```
// finally dispose chart
chart.dispose();
```
But even though the chart gets disposed, I see warning for legend container in dev tools. 

Anything I am missing here ?

**Comment by martynasma** [comment]
You need to dispose the `amLegendContainer`, too.

**Comment by mahesh-chotrani** [comment]
Appreciate your swift responses, @martynasma ! 

It was a miss from my side. Instead of `chart.legend.dispose()` it should have been `chart.legend.parent.dispose()`.
