### ISSUE TITLE
Stacked columns chart disappear after page change

### ISSUE THREAD

**Issue by Calandal95** [amcharts/amcharts4#319]
Hello!
i've noticed that my stacked columns chart often disappears after leaving and re-accessing the page.
Only an empty container is rendered (with Amcharts logo at the bottom) but no other elements are rendered.
I've no errors or warnings. Just a blank container.
Any idea how to debug this problem in order to find a solution?
Thanks in advance
Alessio

**Comment by martynasma** [comment]
Hi Alessio,

Can you clarify what you mean by "re-accessing the page". Do you mean simply reloading the page results in an empty chart? Going back in history? Something else?

Thank you!

**Comment by Calandal95** [comment]
My web site is composed by multiple pages (i'm using react and react-router for navigation). When i enter the page X (the one with the stacked columns chart) at the beginning, the chart is successfully loaded. If i navigate to another page Y and then i come back to X page, sometimes the stacked columns charts it's not rendered. It's missing the whole svg container.
The chart is contained in a bootstrap (reactstrap) card.

![1](https://user-images.githubusercontent.com/39583628/45077080-7a929f80-b0ec-11e8-94f0-ae25a50b0142.JPG)

![3](https://user-images.githubusercontent.com/39583628/45077084-81211700-b0ec-11e8-8115-7af26d1b3a3b.JPG)

**Comment by martynasma** [comment]
OK, so it looks like your app or framework is destroying the chart.

Any chance you could produce a working demo which we can use to test?

**Comment by Calandal95** [comment]
I found the problem. There was a mistake by my side.
Thanks for your time!
Alessio

**Comment by martynasma** [comment]
OK cool. Glad you worked it out. Thanks for the update!

**Comment by tjones0808** [comment]
hi @Calandal95 what was the mistake? I am getting the same issue. I am using react whenever i change state my charts disappear. requires me to reload the page to bring them back.

**Comment by tjones0808** [comment]
figured it out. i needed to add a method to create charts in the componentDidUpdate as well.
