### ISSUE TITLE
Can we translate label text to different languages in amchart4 column series

### ISSUE THREAD

**Issue by srisharankanukanti** [amcharts/amcharts4#3190]
Hi ,
i have an issue where the column series label text needed to be translated to specific language, is there any way to change it? If so can you please help me .
<img width="769" alt="column series translation" src="https://user-images.githubusercontent.com/17096890/103774571-ceae4580-5052-11eb-89e7-6e51896e2c7e.PNG">

**Comment by martynasma** [comment]
Those are categories you provide in data. You can have any text, in any language there.

Or am I missing something?
