### ISSUE TITLE
How to change fillOpacity for scrollbar's background? Layer covers background

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3191]
Hey,

I'm facing the following problem - I want to fully customize the scrollbar and have the thumb a light gray color while the outside (that'd be the main scrollbar background) to be somewhat more darker

I have this pen https://codepen.io/raresm2020/pen/dypKvwY

As you can see it's setting `black` correctly for the thumb and `red` for the scrollbar's background but I see there's another SVG group `g` which acts as a layer?, set to `#fff` and with `fillOpacity` set to `0.8`. How do I change that?

![Image](https://i.ibb.co/7n935k3/amcharts.png "Debug Image")

Or is there any other way to set the scrollbar's background without being affected by that group? Setting `chart.scrollbarX.background.fillOpacity = 1` doesn't help.

Thanks!

**Comment by martynasma** [comment]
This will disable the overlay that is supposed to fade the non-selected parts:

```JavaScript
chart.scrollbarX.unselectedOverlay.fillOpacity = 0;
```

**Comment by teodosii** [comment]
@martynasma 
Thanks, that worked.

One more thing - is it possible to have the line position in front? Right now each color I use for the thumb background I need to decrease the opacity in order to see the line. Is it possible to change so that columns pop?

Line for the other part of the scrollbar shows correct as it's on top of the background.

Here's an updated pen describing the issue

[Codepen](https://codepen.io/raresm2020/pen/dypKvwY)

**Comment by teodosii** [comment]
Something like this

![Image](https://i.ibb.co/6g7ZNdw/white-bg.png "White background")

The colors differ but that's not the point. The main thumb is below the computed series. Is this possible? This was done in inspector tools not by configuration.

**Comment by teodosii** [comment]
Nevermind, negative zIndex seems to do the job.

**Comment by CHANDRAMOHANnegi** [comment]
How to do this in amchart5
