### ISSUE TITLE
Is there any way to move axis range to another container?

### ISSUE THREAD

**Issue by JayesNS** [amcharts/amcharts4#3192]
**Question**
I've received a task to create axis range which begins at specific value and ends at the top of chart (Infinity). I tried several possibilities, but using combination of [Range area chart](https://www.amcharts.com/demos/range-area-chart/) (dynamic limit) and [Axis ranges](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/) (to show that range goes beyond top of the chart) was best yet not perfect. The problem is that my range area chart is drawn above grid so I tried to use workaround described [here](https://www.amcharts.com/docs/v4/tutorials/grid-over-series/), but then Axis Range is moved too. Can I manually change origin of axis ranges? Changing parent didn't work

![obraz](https://user-images.githubusercontent.com/7165170/103827410-34adc380-5079-11eb-924e-278a6c7a5376.png)

**Environment (if applicable)**
AmCharts4

**Additional context**
Demo is available [here](https://codepen.io/jayesns/pen/xxEjYML)

**Comment by martynasma** [comment]
This should do the trick of bringing the grid back above everything:

```JavaScript
valueAxis.renderer.grid.template.above = true;
dateAxis.renderer.grid.template.above = true;
```

**Comment by JayesNS** [comment]
Thank you, it solves my problem, but now I must get rid of weird lines between values. It seems each Axis Range (red one on the top and green below) add one grid line. Do you know what may cause it?
![image](https://user-images.githubusercontent.com/7165170/103875983-5e93d400-50d3-11eb-8bf6-2a2d85bf4ddb.png)

**Comment by martynasma** [comment]
Yeah, just disable range's grid:

```JavaScript
fillRange.grid.disabled = true;
```

**Comment by JayesNS** [comment]
You don't know how glad I'm right now. You saved me a lot of time. Thank you once again. ;)
