### ISSUE TITLE
Any way to 'redraw' the svg on command?  (svg not showing properly when adding data to a chart while hidden)

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts4#3193]
Here is the scenario.  I have a chart which adds new data every 15 seconds similar to the 'live' example at [https://www.amcharts.com/demos/live-data/](https://www.amcharts.com/demos/live-data/) on the site.

For this particular chart I can collapse the div it is in so the div is hidden on the page (and the chart too of course).  If data is added to the chart while hidden and the div is then expanded afterwards (visible again) the chart does not display correctly.  I am assuming there is some internal code in amcharts that uses the width/height of its container to draw when it adds the new data.

So, what I would like to know is if there is a way to force a 'redraw' of the svg without adding new data?  If there is, I can add a listener to force a 'redraw' whenever the div the chart is located goes from a hidden to visible state.  Then the chart would always show properly.

I know I can add a listener to stop adding data when the chart is not visible, but in this case I would like to continue updating/adding data to it whether it is visible to the user or not.

**Comment by martynasma** [comment]
Try `chart.reinit()`.

**Comment by morrow95** [comment]
@martynasma - just what I was looking for - thank you!
