### ISSUE TITLE
addData tick causes cursor to lag spike

### ISSUE THREAD

**Issue by g-wm** [amcharts/amcharts4#3194]
addData causes the cursor to lag spike. For example, I have a chart that is constantly live updating by the second, if I move the cursor around there is a very noticeable lag spike.

```
  const chart = container.createChild(am4charts.XYChart);
  const dateAxis = chart.xAxes.push(new am4charts.DateAxis());
  const valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
  const series = chart.series.push(new am4charts.LineSeries());

  chart.data = data;

  dateAxis.keepSelection = true;
  valueAxis.keepSelection = true;  
  valueAxis.baseValue = valueAxis.min;
  dateAxis.start = 0.05;
  dateAxis.end = 1;

  series.fillOpacity = 1;
  series.fill = cfGradient();
  series.stroke = am4core.color('blue');
  series.dataFields.dateX = xLabel;
  series.dataFields.valueY = yLabel;
  series.tooltipText = `{value.formatNumber('${TOOLTIP_FORMAT}')}`;
  series.tooltip.pointerOrientation = 'horizontal';
  series.tooltip.getFillFromObject = false;
  series.tooltip.getStrokeFromObject = false;
  series.tooltip.background.fill = am4core.color('white');
  series.tooltip.background.stroke = am4core.color('white');
  series.tooltip.label.fill = am4core.color('blue');

  chart.cursor = new am4charts.XYCursor();
  chart.cursor.snapToSeries = series;
  chart.cursor.xAxis = dateAxis;
  chart.cursor.lineX.stroke = am4core.color('blue');
  chart.cursor.lineX.strokeWidth = 1;
  chart.cursor.lineX.strokeDasharray = '';
  chart.cursor.lineX.opacity = 1;
  chart.cursor.lineY.stroke = am4core.color('blue');
  chart.cursor.lineY.strokeWidth = 1;
  chart.cursor.lineY.strokeDasharray = '';
  chart.cursor.lineY.opacity = 1;
  chart.cursor.behavior = 'panX';
  chart.mouseWheelBehavior = 'zoomX';
  dateAxis.minZoomCount = 5;
```

Happens with/without any animations. Lag spike is only when call addData. There is 500 datapoints.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by g-wm** [comment]
> Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

I know not ideal but I can't share all the code or the data. But above is all the createChart code. I've tried removing everything else on the page, removing datapoints so there is only 500 (originally 5000), removing animations, removing the gradient. Also batching parent components updates so it's only rendering once per second. Still a lag spike, only on addData.

**Comment by martynasma** [comment]
I'm sorry, but I can't provide any insight into theoretical setups. I'll be happy to take a look if you can provide a working example of your chart, though.
