### ISSUE TITLE
how fix amcharts4 not working in internet explorer 11.

### ISSUE THREAD

**Issue by fairyland0926** [amcharts/amcharts4#3195]
![image](https://user-images.githubusercontent.com/72979420/103986369-aa11b500-519b-11eb-9eea-90ba88702cd3.png)

**Comment by martynasma** [comment]
The error originates in `vendor.js` which is not part of amCharts package. Are you sure it's amCharts-related?

If you are using some sort of packager that packs up a bunch of libraries into a single js file, can you try excluding amCharts files from it to see if it helps?

**Comment by fairyland0926** [comment]
![image](https://user-images.githubusercontent.com/72979420/103986948-b5b1ab80-519c-11eb-9d6e-9a8aa783d88f.png)

**Comment by martynasma** [comment]
TinyQuye is not part of amCharts.

**Comment by fairyland0926** [comment]
I'm using "@amcharts/amcharts4": "4.9.24".

**Comment by martynasma** [comment]
Like I said, TinyQueue is (and never was) part of any version of amCharts.
