### ISSUE TITLE
Removing empty axis space from a stacked clustered bar chart?

### ISSUE THREAD

**Issue by ggggabri** [amcharts/amcharts4#3196]
**Question**

To preface, I'm making a stacked clustered bar chart similar to this one from the docs: https://codepen.io/team/amcharts/pen/WKqZeX (stacked clustered columns over a category axis)

I see that when there are multiple "stacked columns", the axis correctly makes space for both. When a certain series is missing data for one of these categories though the white space remains. For example, after removing value3 and value4 from the first data node in the previous codepen: [screenshot](https://ibb.co/vhP5sTX)

Is it possible to remove this extra space? So that if category "One" only has data for 1 series, it'll take up the space of 1 column

**Comment by martynasma** [comment]
No, I'm afraid there's no way to make the remaining stack to take up the empty space when other stack is hidden. Sorry.
