### ISSUE TITLE
Single left click with panBehavior causes the map to zoom & pan real hard

### ISSUE THREAD

**Issue by T-Grave** [amcharts/amcharts4#3197]
**Bug description**

Ever since version 4.9.31 our Map zooms in super hard (and pans away), almost unrecoverable when just doing a single left click on the map anywhere.

I've narrowed it down to the following change:
https://github.com/amcharts/amcharts4/compare/4.9.30...4.9.31#diff-d60c175998d9472727b9dad0aa815d5ff7debbcc7fcf67b604e3476bb6d1d98aR1908

When I comment out that line of code, the map doesn't do anything on single left click (as expected)

This is how we setup the map:

```
this.map = am4core.create(this.mapRef.current, am4maps.MapChart);

this.map.geodata = am4geodata_worldLow;
this.map.panBehavior = 'rotateLong';
```

Except for a polgyon series and an image series being created, I don't think we're doing anything special.

We put back the panBahavior to `move` for now, as it's the rotation updating extremes causing the issue.
**Environment (if applicable)**

Version: 4.9.30+

We're using React as well, but I don't think that necesarilly makes a difference here.

**Comment by martynasma** [comment]
I can't seem to be able to reproduce the behavior you are describing.

Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
