### ISSUE TITLE
queueHandler: TypeError: Cannot set property '__disabled' of undefined

### ISSUE THREAD

**Issue by matinfo** [amcharts/amcharts4#3198]
**Bug description**

During chart data render initialisation (data loading) of a **XYChart**, fail with this error:

```
Instance.ts:310 Uncaught TypeError: Cannot set property '__disabled' of undefined
    at queueHandler (Instance.ts:310)
    at Instance.ts:265
    at Object.dispatch (EventDispatcher.ts:489)
    at EventDispatcher.ts:324
    at Module.each (Array.ts:95)
    at EventDispatcher._eachListener (EventDispatcher.ts:294)
    at EventDispatcher.dispatchImmediately (EventDispatcher.ts:322)
    at Registry.dispatchImmediately (Registry.ts:313)
    at System.update (System.ts:362)
    at System.ts:405
```

**Environment**

 - amCharts: 4.10.13
 - Browser: Chrome 88.0.4324.50
 - React: 16.14.0
 - Valid amcharts license

**Additional context**

- Json config
- This not occur on initial page load, and not always, very random but only after chart is re-initialised, to show new data set from useEffect. Difficult to reproduce always, but occur regularly.
- This bug, not occur with previous version 4.10.9

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by oliverlj** [comment]
I reproduced this issue with options :
options.onlyShowOnViewport = true;
