### ISSUE TITLE
HeatLegend not showing when passed via JSON config to MapChart

### ISSUE THREAD

**Issue by jaywalker21** [amcharts/amcharts4#3199]
`HeatLegend` is not showing up when passed using config in the same manner as done in the demo examples or the reference documentation

The use case is to show the HeatLegend based on `JSON` configuration. As per the documentation, passed the `HeatLegend` as a child to the chart and referenced the `series` via `id` to associate the `HeatLegend` with the same, but it is not working.

Please refer the below code pen in order to reproduce the same
https://codepen.io/jaybhatt21/pen/JjRazeJ

 - amCharts version - 4
 - Browser - Chrome

**Comment by jaywalker21** [comment]
@martynasma Can you please check the code pen once and advice? Thanks!

**Comment by xorspark** [comment]
You need to add `forceCreate: true` to your `children` array to ensure it is created. This is explained more in detail here: https://www.amcharts.com/docs/v4/concepts/json-config/#Creating_or_reusing_

[This example](https://www.amcharts.com/docs/v4/tutorials/map-heat-legend-with-real-start-end-value-labels/) also has this line in the JSON snippets, but we probably should also call this out in the main heat legend docs too.

**Comment by jaywalker21** [comment]
@xorspark Thanks for a quick revert. If we could add a little `note` to `HeatLegend` documentation, it will really help.

**Comment by jaywalker21** [comment]
@xorspark @martynasma Closing the issue as the answer is available and solved the problem.
