### ISSUE TITLE
Is there a possibility to make the dateAxis skipEmptyPeriods to skip periods not based on baseInterval but on some custom provided interval ?

### ISSUE THREAD

**Issue by dhiren-eng** [amcharts/amcharts4#3204]
I've made a scatter plot with lineSeries and bullets as shown below. The chart is showing fine as expected i.e. the X axis labels should display years unless on zooming a year.

The setting of baseInterval and gridInterval of my date axis is :        
        dateXAxis.baseInterval = {
          "timeUnit": "day",
          "count": 1
        }
        dateXAxis.gridIntervals.setAll([
          { timeUnit: "day", count: 1},
          { timeUnit: "month", count: 1},
          { timeUnit: "year", count: 1 }
        ]);
![image](https://user-images.githubusercontent.com/59474883/104315373-dcefdc00-5500-11eb-8f66-c8a788f6d79b.png)

Now I want to skip empty periods i.e. empty years in the above chart. So on setting axis' skipEmptyPeriods to true, I get an unexpected chart as shown below.
![image](https://user-images.githubusercontent.com/59474883/104315134-7ec2f900-5500-11eb-8926-259780a9d1eb.png)

I guess this is happening because of the baseInterval set to day but this setting i.e. baseInterval : day is required because the bullets are also required to be positioned day-wise i.e. according to the dates and not month/year wise. Is there any way of skipping only years in the 1st chart from top shown above when the baseInterval is set to 'day' ?

@martynasma @zeroin

**Comment by martynasma** [comment]
No, I'm afraid there's no way to force skipping custom intervals. Sorry.
