### ISSUE TITLE
Polygon stroke is not updated after invalidateData is called

### ISSUE THREAD

**Issue by komaldudakiya** [amcharts/amcharts4#3206]
I have a MapChart and a MapPolygonSeries with custom data. On click of map I am assigning the stroke color to the clicked region on map as follows:
globals.polygonSeries.mapPolygons.template.events.on("hit", event => {
        event.target.stroke = am4core.color("cyan");
        event.target.strokeWidth = 4;
}

But after I update the data and try to apply the stroke, nothing happens. Below is the update code:
   globals.polygonSeries.data = globals.proposedMapData;
   globals.polygonSeries.invalidateRawData();

   globals.polygonSeries.getPolygonById("2").stroke = am4core.color("cyan");
   globals.polygonSeries.getPolygonById("2").strokeWidth = 4;

getPolygonById returns undefined.

Can you please help with this.

**Comment by martynasma** [comment]
Are you sure there is a polygon with id "2"?

**Comment by komaldudakiya** [comment]
Yes.

**Comment by martynasma** [comment]
Can you post a demo of your whole map?

**Comment by komaldudakiya** [comment]
There is lot of custom data involved. I can add the code snippet with the workflow. Would that work?

**Comment by martynasma** [comment]
> There is lot of custom data involved. I can add the code snippet with the workflow. Would that work?

No, sorry.

**Comment by komaldudakiya** [comment]
Here is the demo I am trying to do.
https://codepen.io/komaldudakiya/pen/WNGaYWW

On click of the button - update, getPolygonById returns undefined.

**Comment by martynasma** [comment]
I did check your code, thanks.

The only place that uses `getPolygonById()` is not invoked. If I modify it to get invoked and use "2" as a parameter, it correctly returns the `MapPolygon` object.

Not entirely sure, what's the problem here? :)

**Comment by komaldudakiya** [comment]
The problem comes when you click on the update button, updateMap() function is called, where getPolygonById() function is invoked and that throws an error. Following are the steps to reproduce the issue:

1. Click on the colored region on the map. Region zooms and a cyan color stroke is applied.
![image](https://user-images.githubusercontent.com/49227447/104622231-0488a500-56b7-11eb-8427-9ab61da06253.png)

2. Click on the update button, you will see the error and also the stroke color of the clicked region is vanished.
![image](https://user-images.githubusercontent.com/49227447/104622338-21bd7380-56b7-11eb-895f-225fb60af0cc.png)

I have attached the screenshots of the error.

**Comment by martynasma** [comment]
When you set `data` on your series, all current data items are destroyed. Data updating is an asynchronous operation, so your code then proceeds to the `getPolygonById()` line, but since the data was not yet processed it results in error.

To be safe, wrap your code into `datavalidated` event:

```JavaScript
globals.polygonSeries.events.once("datavalidated", function() {
  globals.polygonSeries.getPolygonById(globals.regionId).stroke = am4core.color("cyan");
  globals.polygonSeries.getPolygonById(globals.regionId).strokeWidth = 4;
});
```

P.S. `invalidateRawData()` call is redundant since you are updating the whole data, so there will be no transition,and the data will be fully reevaluated anyway.

**Comment by komaldudakiya** [comment]
Thank you for the direction. That worked!! 👍 

On the same lines, do we also need to override the adapters again after data update? Because in the same demo if you see, for the first time after data update, popup/tooltip does not appear. But, if you move your cursor out and again hover over the region, tooltip is displayed.

**Comment by martynasma** [comment]
No, you don't have to re-add adapters, because those are added on templates and they are retained across data updates.

Though, I don't see any adapters used in your CodePen.

**Comment by komaldudakiya** [comment]
Sorry.. Not the adapter, on the "over" event trigger.

**Comment by martynasma** [comment]
Same goes for event handlers.
