### ISSUE TITLE
How to show all category labels in a condensed Gantt Chart

### ISSUE THREAD

**Issue by thunderbolt10** [amcharts/amcharts4#3207]
Taking the Amcharts demo for Gantt chart (https://www.amcharts.com/demos/gantt-chart-dates/) and adding a line to condense the rows  `chart.height = 300;` causes every other category label to disappear.
https://codepen.io/thunderbolt10/pen/eYdPBqo

So I tried reducing the font size of the labels `categoryAxis.renderer.labels.template.fontSize = 11;` but this did not allow all labels to be displayed.
![image](https://user-images.githubusercontent.com/30114322/104332599-40214480-54e8-11eb-8b41-ec27e1f50ee3.png)

What setting will show all category labels at the reduced row height?

**Comment by martynasma** [comment]
Please refer to [this tutorial](https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Controlling_spacing).
