### ISSUE TITLE
Chart was not disposed - conflict with Angular/Material's BrowserAnimationsModule

### ISSUE THREAD

**Issue by david-a** [amcharts/amcharts4#3208]
Hi,
I've noticed that when I add Angular/Material's `BrowserAnimationsModule` to the app's module imports, my chart (Force directed tree) is not disposed properly anymore (getting the `Chart was not disposed` warning) and is not rebuilt when changing to another component with the same chart in my single page app.

I'm using `this.chart.dispose();` inside `ngOnDestroy`, which was working without the `BrowserAnimationsModule`. Also tried `am4core.disposeAllCharts();` with no luck.

Any thoughts?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on Stackblitz or Codesandbox?

**Comment by david-a** [comment]
Hi,
I've tried using BrowserAnimationsModule again now (was using NoopAnimationsModule until now because of this issue) and it's working. The only major thing that was changed is the way I load the amCharts library - instead of importing it statically - I've dynamically imported all amcharts related libraries, with `/* webpackChunkName: "chart" */` comment. This was done in order to overcome this issue -  https://github.com/amcharts/amcharts4/issues/1146#issuecomment-693607250
