### ISSUE TITLE
Set Timezone For Calculating Date Axis Period Changes?

### ISSUE THREAD

**Issue by Halvi3** [amcharts/amcharts4#3209]
**Question**
I am trying to configure the labels of a Date Axis, and cannot determine how to specify the timezone to use when determining whether to use a _period change_ format or the regular period format. Specifically, I need all the labels on the date axis to be displayed as UTC regardless of the timezone of the user's browser. 

Setting 
```
dateAxis.dateFormatter.timezone = "UTC";
```

worked just as expected to have the hours displayed properly in UTC, but my browser is in Pacific Time (UTC-8) and as you can see in this screenshot:

![Screen Shot 2021-01-12 at 10 10 24 AM](https://user-images.githubusercontent.com/6120342/104354882-bdd05a80-54be-11eb-8f6e-4c743f23a476.png)

When the chart is zoomed such that it is using hours as the base time unit, the label suggests that the date changes at 08:00 instead of 00:00.

I have tried numerous different values for 
```
dateAxis.periodChangeDateFormats.setKey('hour', '[bold]yyyy-MM-dd');
```

Including using an `Intl.DateFormatOptions` object instead of a string and setting `timeZone: "UTC"` within that object, but all of them just modify the formatted value displayed on the label. I've also tried setting `.timezone = "UTC"` on other places on the chart, like on `dateAxis`  directly instead of the dateFormatter, and on `series.dateFormatter`, but none of these changes seem to do anything to get the chart to "think" internally in UTC instead of local time when calculating period changes.

**Comment by martynasma** [comment]
How about using formatter's `utc` setting?

```
chart.dateFormatter.utc = true;
```

**Comment by Halvi3** [comment]
Thank you! I figured as soon as I gave in and posted an issue about this my solution would just be some simple flag I had overlooked in the docs but I had been poring over them for days and had a complete blind spot for that property. 

This can be closed, thanks much for the quick response.
