### ISSUE TITLE
Ability to set minimum period for DateAxis labels

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#321]
Hello !

Is there a way to make work the Live data demo with date not rounded to second ?

https://codepen.io/ptorrent/pen/bxRYrw

I would like to keep ticks intervals of dateAxis insecond (exactly like your original example)

**Comment by martynasma** [comment]
Yes:

```
dateAxis.baseInterval = {
  "timeUnit": "second",
  "count": 1
}
```

https://www.amcharts.com/docs/v4/concepts/axes/#Data_granularity

**Comment by ptorrent** [comment]
Yes I already try but it's not realy what I want.

baseInterval = { ... } round the date to the specific unit.

I want to keep ms in chart and keep the 1s interval on dateAxis.

**Comment by martynasma** [comment]
Gotcha.

Unfortunately, I can't think of any way how to do so.

I suppose we'll need to implement some kind of setting for `DateAxis` for that. Just like `ValueAxis` has `maxPrecision`, we'll need `minPeriod` or something.

When that happens, we'll let you know.

**Comment by ptorrent** [comment]
Thanks it's exacly what I want !

**Comment by ciarancourtney** [comment]
Me too!

**Comment by martynasma** [comment]
Found this old thread. This has already been implemented:
https://www.amcharts.com/docs/v4/reference/dateaxis/#minZoomCount_property
