### ISSUE TITLE
Axis range line is not visible on the chart value axis when XY chart data values are low

### ISSUE THREAD

**Issue by Kosmarjus** [amcharts/amcharts4#3210]
Hello,

Question/Idea here I stumbled upon - is it possible to maintain a visible axis range line (like a goal/threshold [thing](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/)) at all times on a simple XY chart when numeric values are much lower than the threshold? I ran through the options given [here](https://www.amcharts.com/docs/v4/concepts/axes/value-axis/), setting the valueAxis.max doesn't quite cover it, as it works when data values are predictable, but if data is dynamic and it exceeds the pre-set max value - it goes off the charts. One could iterate through the chart values, and then decide if valueAxis.max is needed, but once it is set there is no way back to automatic scale without redrawing the chart.
So I'm thinking there could be a setting to include valueAxis range value in calculating the automatic scale of valueAxis. What do you think?

**Comment by xorspark** [comment]
You're in luck - this setting already exists :smiley: 

https://www.amcharts.com/docs/v4/reference/valueaxis/#includeRangesInMinMax_property

**Comment by Kosmarjus** [comment]
Well that's a turn of events! Works like a charm, albeit there are issues with chart being zoomed in after data set renewal, but setting valueAxis.keepSelection = true; and valueAxis.start = 0.0; valueAxis.end = 1.0; solves that.
Thanks!
