### ISSUE TITLE
Issue with divergent bar chart

### ISSUE THREAD

**Issue by 3zzy** [amcharts/amcharts4#3211]
I tried to recreate [this](https://www.amcharts.com/demos/stacked-bar-chart-with-negative-values/#code) example using JSON config and it almost works but the bars are not aligned for some reason:

https://jsfiddle.net/2b5Lypkw/

I tried a simpler reproduction and it still has an issue: https://jsfiddle.net/ryhLmcz7/

Am I missing something or or is it a bug?

Thanks

**Comment by xorspark** [comment]
`clustered` is a top-level series property. Your code has it set under `dataFields`, which is not correct.

```
    series: [{
        type: "ColumnSeries",
        dataFields: {
            valueX: "male",
            categoryY: "age",
        },
        clustered: false,
    },
    {
        type: "ColumnSeries",
        dataFields: {
            valueX: "female",
            categoryY: "age",
        },
        clustered: false,
    }]
```

[Updated fiddle](https://jsfiddle.net/jnvce9xp/)

**Comment by 3zzy** [comment]
Ah, thanks!

It would be awesome though if there was a way to export JSON config from a chart. Pretty sure its not that difficult but would help in so many ways. 

Ref https://github.com/amcharts/amcharts4/issues/2159
