### ISSUE TITLE
Dynamically change axis formatter

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#3212]
Hello,
Having this pen bellow, 

https://codepen.io/aniov/pen/gOwBQov?editors=1010

On oY axes formatter I want to switch between value and percent (also chart data is changing).
When selecting "percent"/ "value" it seems it doesn't change to the new format for all the values.
But if you scroll on Y Axes the correct format is displayed.

![AxesFormatter](https://user-images.githubusercontent.com/21243081/104440910-9f8c5c80-559b-11eb-8064-f7336d9fd1fc.gif)

How can I resolve this ? (maybe an event listener)
(Also this should work for multiple axes - the commented lines in example)

Thank you.

**Comment by martynasma** [comment]
This is because labels are cached and reused. You need to explicitly invalidate them after changing the formatter:

```JavaScript
valueAxis1.invalidateLabels();
```

**Comment by aniov** [comment]
Thank you :)

PS: I've invalidated all the other things but not the labels.
