### ISSUE TITLE
StepLine series disappear if I want to pass a relatively big array of data.

### ISSUE THREAD

**Issue by ngerasimoff** [amcharts/amcharts4#3213]
Hello Everyone!

I came across this problem while processing an array of data which contains a few thousand points.
I want to switch between the two types of charts (**StepLineSeries** and **ColumnSeries**).
Using the same set of points  a **ColumnSeries** chart renders everything perfectly fine, but after changing the chart type to **StepLine** all my series become invisible (even though I can still detect them with the help of cursor). 

Also, I need to show breaks so I use this **`connect`** property assigned to **`false`**
This is how I see my StepLine chart with 3700 points [**Basic example**](https://codepen.io/defoox/pen/oNzamLO)
![image](https://user-images.githubusercontent.com/53784088/104457727-74196a00-55bb-11eb-900e-e3c6bda2ef23.png)

and now same 3700 points with  **ColumnSeries**.
![image](https://user-images.githubusercontent.com/53784088/104458072-ebe79480-55bb-11eb-91fe-3210c3e0c34b.png)

so the question is **what should I do to make invisible series show up again** (except for zooming..because If I zoom in a little..I can see the chart lines well)??

Many thanks in advance!

**Comment by aniov** [comment]
I think because u have so many data you should group them (that will make the chart render faster also):

`dateAxis.groupData = true;`
`dateAxis.groupCount = 1000;`

change the 'groupCount' value to see more or less columns.

**Comment by martynasma** [comment]
Setting `autoGapCount` to zero like you do does not make a lot of sense, hence the issue.

The [following tutorial](https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Gaps_over_missing_data_points) has an explanation how it works.

**Comment by martynasma** [comment]
@ngerasimoff Hm, it seems an issue, which is rooted deeply into how StepLineSeries segments are created. I don't think we'll be able to fix that, as it would require a lot of refactoring.

How about a workaround: using separate `ColumnSeries` for fills. Here's an updated CodePen:

https://codepen.io/team/amcharts/pen/d42cedaa4074cd4e380a9cc648f189cb?editors=0010
