### ISSUE TITLE
Axis label tooltip pointerOrientation seems to be ignored

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#3217]
I'm following this article: https://www.amcharts.com/docs/v4/tutorials/wrapping-and-truncating-axis-labels/#Displaying_tooltips
but I'm trying to get the tooltips to appear above the axis label (thus overlapping the chart) instead of going below the chart in all scenarios, still leading to it getting cut off. Is there something I'm missing on the setting of the pointerOrientation, or is this just not supported?

Here's an example showing the issue: https://codepen.io/runfaj/pen/gOwQQNe (line 59)

**Comment by xorspark** [comment]
You'll need to configure this on the category axis label, rather than on the axis directly:

```
var label = categoryAxis.renderer.labels.template;
// ...
label.tooltip = new am4core.Tooltip();
label.tooltip.pointerOrientation = 'down';
label.tooltip.label.maxWidth = 200;
label.tooltip.label.wrap = true;
```

[Updated codepen](https://codepen.io/team/amcharts/pen/24c72901345e5a376fe591a9743f9a6b?editors=0010)

**Comment by runfaj** [comment]
@xorspark Thanks! I would have expected the built-in one to be this same code essentially (since it is listed in the docs as an instance of tooltip), but I guess that isn't t he case.
