### ISSUE TITLE
Adding Scrollbar or Overflow to Tooltip

### ISSUE THREAD

**Issue by ava8tor** [amcharts/amcharts4#3218]
Hello, I'm currently trying to add a scrollbar to a tooltip based on a suggestion given in #1819.

In this thread it suggests wrapping the contents of the tooltip in CSS contrained HTML with the following:

//series.tooltipHTML = '<\div style="max-height: 200px; overflow: auto;">{something}<\/div>';

However upon adding using adding the overflow: auto or scroll to stylize the html, although the scrollbar was added, I could not interact with the contents of the tooltip container until I also wrote out the following:

//lets mouse hover over tooltip without it vanishing
series.tooltip.keepTargetHover = true;

//Enables interactivity of the tooltips label elements
series.tooltip.label.interactionsEnabled = true;

My current issue is that when the _interactionsEnabled_ function (the 2nd line above) is used while the scrollbar is added to a container in the toolpicker and the contents is larger than the container , _the entire container will vanish and won't be visible._

If I happen to be overlooking anything, any assistance resolving the issue would be appreciated. 

Example code displaying the issue can also be found here (hover over one of the bars in the chart to display the tooltip): https://jsfiddle.net/ava8tor/a7wbpmkh/4/

**Comment by martynasma** [comment]
Hm, that's not how it acts for me:

https://user-images.githubusercontent.com/1458520/104690226-bacaa980-570c-11eb-9142-088dd2d965b7.mp4

It's in Chrome.

**Comment by ava8tor** [comment]
![image](https://user-images.githubusercontent.com/14093525/104738280-52cb9180-5713-11eb-8da0-e577165924e2.png)

There must be an issue with my current Chrome browser then as this is what it currently shows me. Upon testing this out on the Edge browser however, it does seem to be work. so the issue does seem to only be specific to just Chrome on my computer though as to why I haven't a clue, even after clearing the cookie and image cache.

**Comment by martynasma** [comment]
Anything in browser console?

**Comment by ava8tor** [comment]
![image](https://user-images.githubusercontent.com/14093525/104744493-f2405280-571a-11eb-8782-009986586336.png)

Nothing that sticks out to me.

**Comment by martynasma** [comment]
Not sure what to suggest then :(

**Comment by ava8tor** [comment]
Not a problem. I decided to try reinstalling chrome. I have no idea what originally caused the issue unfortunately but reinstalling seems to have fixed it and can see the container now. Thanks for the help, I wouldn't have known to check the browser otherwise!

![image](https://user-images.githubusercontent.com/14093525/104749566-f5d6d800-5720-11eb-85a6-e50a88a5f827.png)
