### ISSUE TITLE
How to draw correctly smoothed line with data gaps

### ISSUE THREAD

**Issue by fballardin** [amcharts/amcharts4#3219]
Hello,
I'm trying to draw a smoothed line with data gaps. I see this incorrect (at least for me) behaviour of the renderer when trying to do so. This only happens when setting a `tensionX` lower than `1`, if I set it to `1` the line is drawn correctly.

Fiddle: [https://jsfiddle.net/ph0akuv8/](https://jsfiddle.net/ph0akuv8/)
Screen smoothed: [https://i.stack.imgur.com/xeb7p.png](https://i.stack.imgur.com/xeb7p.png)
Screen normal: [https://i.stack.imgur.com/uN60h.png](https://i.stack.imgur.com/uN60h.png)

Is there any way to draw it without incurring in this line overlapping?
I've tested and verified this behaviour in Chrome 87, Firefox 84, Opera 73.
Thanks!

**Comment by martynasma** [comment]
You might try different smoothing algo:

https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Alternate_smoothing_algorithm

**Comment by fballardin** [comment]
Thanks @martynasma,
your proposed solution is just what I wanted.
Sorry for not seeing it in the docs before.
Wish you all the best!
