### ISSUE TITLE
Overlapping column bars

### ISSUE THREAD

**Issue by ncircleamit** [amcharts/amcharts4#3221]
We have created a gantt chart referring this demo: https://www.amcharts.com/demos/gantt-chart-dates/

But we have some overlapping bars due to which some of the bars are not visible properly. We are using single ColumnSeries.

Is there a way to handle it in AmCharts for single series?

<img width="1613" alt="BarOverlap" src="https://user-images.githubusercontent.com/10433606/104742015-efbc1800-576f-11eb-9ca9-f1eea9fb4e21.png">

**Comment by martynasma** [comment]
Do you have an idea how would you like it to be handled?

**Comment by martynasma** [comment]
I mean how the chart would look like?

**Comment by shijoshaji** [comment]
Hi am also looking for same solution. Do we have any for not to overlap the data?
