### ISSUE TITLE
dateAxis.skipEmptyPeriods ignores gridIntervals

### ISSUE THREAD

**Issue by andrewfmbs** [amcharts/amcharts4#3222]
**Bug description**

Not sure if this extends outside of CandleSeries, but in my specific case I cannot show periods with empty data (weekends) but when setting `dataAxis.skipEmptyPeriods = true;` then my grid intervals are ignored. 

Am I doing something wrong? Here is a jsFiddle replicating the issue (codepen was giving me issues)

[Fiddle](https://jsfiddle.net/eb4acyfL/)

I console logged the gridInterval so you can see it's setting it correctly, just being ignored.

**Comment by martynasma** [comment]
`skipEmptyPeriods` is not compatible `groupData`, as [per docs](https://www.amcharts.com/docs/v4/reference/dateaxis/#skipEmptyPeriods_property).

**Comment by andrewfmbs** [comment]
I'm not using groupData. It's commented out in the fiddle because I was testing different scenarios

**Comment by andrewfmbs** [comment]
> `skipEmptyPeriods` is not compatible `groupData`, as [per docs](https://www.amcharts.com/docs/v4/reference/dateaxis/#skipEmptyPeriods_property).

I'm not using groupData. It's commented out in the fiddle because I was testing different scenarios

**Comment by andrewfmbs** [comment]
@martynasma Any ideas here?

**Comment by martynasma** [comment]
The `gridIntervals` are not ignored. It's just that when `skipEmptyPeriods` is applied it removes periods with no data, even those that might have had grid and labels.

I would say that `skipEmptyPeriods` is not good for charts with highly irregular data.

You might try the trick with using two separate DateAxes, like in this demo:
https://codepen.io/team/amcharts/pen/e4eb89792003d371592a400b325f6242

**Comment by andrewfmbs** [comment]
I tried that but then my dates were not aligning with the candlesticks. Shame skipEmptyPeriods isn't working with this data set. It is pretty regular actually, just doesn't include weekends dates.

Might try building the grid lines myself with axis ranges.
