### ISSUE TITLE
Background on x axis disables tooltip. 

### ISSUE THREAD

**Issue by njfix6** [amcharts/amcharts4#3223]
**Bug description**
When I add a background color to the x axis, the tool tip hover over does not work anymore. 

Here is an example of the code: 
```
chart.cursor.xAxis = dateAxis;
const dateAxis = chart.xAxes.push(new am4charts.DateAxis());

// when adding this background
dateAxis.background.fill = am4core.color('grey', 0.1);

const range = dateAxis.axisRanges.push(new am4charts.DateAxisDataItem());
range.bullet = new am4core.ResizeButton();
range.bullet.draggable = false;
range.date = element.fromDate;

const marker = chart.createChild(am4core.Rectangle);
marker.width = 10;
marker.height = 40;
marker.nonScaling = true;
marker.tooltipText = element.title;
marker.horizontalCenter = 'middle';
marker.verticalCenter = 'top';
marker.fill = color;
range.bullet = marker;
```

When I do this, the marker's tooltip doesn't work. Im guessing all hover over options will not work. 

With background on mouse hover:
<img width="148" alt="Screen Shot 2021-01-17 at 9 10 13 AM" src="https://user-images.githubusercontent.com/6845581/104847213-517d9e80-58a4-11eb-9a35-05fafb5f51ed.png">
Without background on mouse hover:
<img width="199" alt="Screen Shot 2021-01-17 at 9 10 38 AM" src="https://user-images.githubusercontent.com/6845581/104847214-52163500-58a4-11eb-9fdb-617059dee105.png">

I would expect the tooltip to work on both cases. 

**Environment (if applicable)**
 - amCharts version - 4.10.13
 - Browser and its version - Chrome Version 87.0.4280.141
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.] - Typescript.

**Additional context**

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
