### ISSUE TITLE
Got error EventDispatcher is disposed when data is stream

### ISSUE THREAD

**Issue by denirahmanto** [amcharts/amcharts4#3224]
Hello all, I have a question why I got error `EventDispatcher is disposed at SpriteEventDispatcher.EventDispatcher.isEnabled` when data provider is stream (using firestore). 

I implemented using next js typescript and already do as documentation, also FYI in my website using 3 chart type and let user to choose their favorite charts.

Can anyone help me? or collaborator please give me example how to implement using stream data?? 

Note: I'm a licensed buyer

**Comment by martynasma** [comment]
Since I'm not familiar with the setup you have described, can you explain how the update is done?

If you create a new chart every time you update data or chart type, you will need to either dispose the previous chart instance, or enable auto-disposing.

More info:
https://www.amcharts.com/docs/v4/tutorials/chart-was-not-disposed/

**Comment by denirahmanto** [comment]
`const BAR = (props: IProps) => {
  const { data, formatDate } = props
  const chart: any = useRef(null)

  useLayoutEffect(() => {
    am4core.useTheme(am4themes_animated)
    am4core.options.autoDispose = true
    am4core.options.onlyShowOnViewport = true
    am4core.addLicense('XXXXXXXX')

    let element: any = am4core.create('bardiv', am4charts.XYChart)

    element.paddingRight = 20
    element.dateFormatter.inputDateFormat = formatDate || `YYYY-MM-dd HH:mm:ss`

    let dateAxis: any = element.xAxes.push(new am4charts.DateAxis())
    dateAxis.renderer.grid.template.location = 0
    dateAxis.renderer.grid.template.disabled = true

    let valueAxis: any = element.yAxes.push(new am4charts.ValueAxis())
    valueAxis.tooltip.disabled = true
    valueAxis.renderer.opposite = true

    let categoryAxis: any = element.yAxes.push(new am4charts.CategoryAxis())
    categoryAxis.renderer.grid.template.disabled = true

    let barSeries: any = element.series.push(new am4charts.ColumnSeries())
    barSeries.dataFields.dateX = 'date'
    barSeries.dataFields.valueY = 'volume'
    barSeries.name = 'Bar'
    barSeries.tooltipText = '{date}\n{codeEmiten}\nVolume: {valueY.value}'
    barSeries.dropFromOpenState.properties.fill = am4core.color('#BF2D30')
    barSeries.dropFromOpenState.properties.stroke = am4core.color('#BF2D30')
    barSeries.riseFromOpenState.properties.fill = am4core.color('#63B7EC')
    barSeries.riseFromOpenState.properties.stroke = am4core.color('#63B7EC')

    element.cursor = new am4charts.XYCursor()

    let lineSeries: any = element.series.push(new am4charts.LineSeries())
    lineSeries.dataFields.dateX = 'date'
    lineSeries.dataFields.valueY = 'close'
    lineSeries.defaultState.properties.visible = false
    lineSeries.hiddenInLegend = true
    lineSeries.fillOpacity = 0.5
    lineSeries.strokeOpacity = 0.5

    let scrollbarX: any = new am4charts.XYChartScrollbar()
    scrollbarX.series.push(lineSeries)

    element.data = data

    chart.current = element

    return () => element.dispose()
  }, [data])

  return (
    <Container>
      <div id='bardiv' style={{ width: '100%', height: '180px' }} />
    </Container>
  )
}`

the code is above, I'm using react hooks, also already put config `am4core.options.autoDispose = true` but still got same error @martynasma

**Comment by martynasma** [comment]
Which version of amCharts 4 are you using?

**Comment by martynasma** [comment]
Any chance you could produce a runnable example on StackBlitz/CodeSandbox?

**Comment by denirahmanto** [comment]
I couldn't provide in StackBlitz/CodeSandbox

**Comment by martynasma** [comment]
Have you tried setting up `componentWillUnmount` callbacks to dispose the chart as per our [React doc](https://www.amcharts.com/docs/v4/getting-started/integrations/using-react/)?
