### ISSUE TITLE
Firefox - Geojson Map not loading

### ISSUE THREAD

**Issue by Abhi-ak** [amcharts/amcharts4#3225]
Hi,
I am getting an unique issue. I am using amcharts to load world map with geojson, It works well and good in safari and chrome, but throws an error in firefox and takes forever to load.

Check the screenshot
![2021-01-18](https://user-images.githubusercontent.com/38856345/104927433-6acb3b80-59c7-11eb-9db4-b61036c5ec69.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
