### ISSUE TITLE
[Question] How to get coordinates for dynamically loaded geodata maps (e.g., in case of drill down) ?

### ISSUE THREAD

**Issue by mahesh-chotrani** [amcharts/amcharts4#3226]
**Question**

From some of the examples, found that for a given map polygon (country / state), there is a convenient method `getPolygonById` in `MapPolygonSeries` from which actual coordinates of the polygon can be retrieved. But realized that only after a chart is ready this method can be used. 

(_Assuming that **amcharts/amcharts4-geodata/worldLow** has been imported statically_)

```
// this code will fail to get coordinates
const country = polygonSeries.getPolygonById('US');
if (country) {
    console.log(country.visualLongitude, country.visualLatitude)
} else {
  console.log('polygon not found')
}
```

With below code will be able to get coordinates, though not sure, it should be `ready` event which should be subscribed for this to work.

```
// with this code, the coordinates will be printed
chart.events.on("ready", function(ev) {
  const _country = polygonSeries.getPolygonById('US');
  if (_country) {
    console.log(_country.visualLongitude, _country.visualLatitude)
  }
});
```

But what if the maps are loaded dynamically, as in the case of [drill down example](https://www.amcharts.com/docs/v4/tutorials/building-drill-down-maps/#Alternative_example) ?

Following the example, the event which is subscribed is `done` on the instance `countrySeries.geodataSource`. 
If I try to run the below code in the event, it fails to get coordinates - 

```
  const _state = countrySeries.getPolygonById('US-MA');
  if (_state) {
    console.log(_state.visualLongitude, _state.visualLatitude)
  }
```

My goal is to get these coordinates for selected states and render dynamic pie charts at those coordinates. Something as shown in this image -

![image](https://user-images.githubusercontent.com/50296623/104922506-d4941700-59c0-11eb-8def-eea9bcd111d6.png)

I would like to know - 
1. How do I get coordinates of map polygons which are included as a result of dynamically loading a series ?
2. Which is the correct event should be subscribed so to get polygon coordinates populated ?

Appreciate any suggestions / misses round this.

**Comment by martynasma** [comment]
How about not watching data source "done" event (it indicates that data was loaded from external source, but it does not mean that it was processed by the series) you watch for series' "datavalidated" event?

**Comment by mahesh-chotrani** [comment]
I have tried with `datavalidated` as well, but polygon coordinates do not get populated even after subscribing this event.

**Comment by martynasma** [comment]
I does work for me.

Take this example:
https://codepen.io/team/amcharts/pen/61681494ba78add966f9ac8cce0e8d45

I just added a simple `datavalidated` event on "country series", then grab random polygon from it and check `visualLongitude` which is shown.

```JavaScript
countrySeries.calculateVisualCenter = true;
countrySeries.events.on("datavalidated", function() {
  var polygon = countrySeries.mapPolygons.getIndex(3);
  console.log(polygon.visualLongitude)
});
```

**Comment by mahesh-chotrani** [comment]
Thanks for quick reply and sample @martynasma !

Though `countrySeries.mapPolygons.getIndex(3);` does work, for some reason `countrySeries.getPolygonById(countryCode)` doesn't works (_where `countryCode` is the code of the country user has clicked, for example, US, ID, IN, ES, etc._). 

The code in the if block never executes

```
let countryCode = '';
countrySeries.events.on("datavalidated", function() {
  var polygon = countrySeries.getPolygonById(countryCode);

  // polygon is always undefined !!
  if (polygon) {
    console.log(polygon.visualLongitude)
  }
});

worldPolygon.events.on("hit", function(ev) {
  // get map name
  let map = ev.target.dataItem.dataContext.map;
  // set country code
  countryCode = ev.target.dataItem.dataContext.id;
  // load JSON
  countrySeries.geodataSource.url = "https://cdn.amcharts.com/lib/4/geodata/json/" + map + ".json";
  countrySeries.geodataSource.load();
});
```

Am I missing something ?

**Comment by martynasma** [comment]
Well, if you clicked on Australia in got "AU" code, and then try to extract a polygon from map of Australia with an id of "AU", it's no there, naturally.

**Comment by mahesh-chotrani** [comment]
Yes, I missed. Didin't realise that need to pass state / province code (_e.g., `US-AL`, etc._), after drill down. 

So, it is `datavalidated` which should be subscribed in place of `ready` or `done` events

Thanks !
