### ISSUE TITLE
XYCursor: zoom/pan with middle/right mouse button

### ISSUE THREAD

**Issue by Mattes83** [amcharts/amcharts4#3227]
Hi,

i am trying to implement zoom and pan functionality side by side.
My current solution is to listen for certain keydown events, so I can switch the cursour behaviour from zoom to pan when a certain key is pushed.

It would be more convenient to use the mouse buttons for different behaviors. Eg zoom with left mouse button and pan with middle mouse button.
Can this be accomplished?

Best Regards

**Comment by martynasma** [comment]
No, I'm afraid. There's no such option right now.
