### ISSUE TITLE
dateAxis on lineChart is not rendering properly 

### ISSUE THREAD

**Issue by PratapAkshay** [amcharts/amcharts4#3228]
I am creating chart gauge and Line chart but my line chart date axis is creating issue some time and sometimes not when I comment my gauge line chart renders perfectly but in case of gauge render before and line renders afterward line chart create a problem.

 - amCharts version : 4.10.7
 - Browser: crome
 - ReactJS

![image](https://user-images.githubusercontent.com/45003568/105050328-acc1b380-5a93-11eb-943a-a5668bcd4884.png)

**Comment by PratapAkshay** [comment]
import React from "react";
// import PropTypes from 'prop-types';
// import styled from 'styled-components';
import * as am4charts from "@amcharts/amcharts4/charts";
import * as am4core from "@amcharts/amcharts4/core";
import am4themes_animated from "@amcharts/amcharts4/themes/animated";

let chart = {}

import { FormattedMessage } from "react-intl";
import messages from "./messages";

/* eslint-disable react/prefer-stateless-function */
class CreateChart extends React.Component {
    state = {
        color: ["#00da00", "#11A8E7"],
        alarm: {
            critical: "#e2030f",
            major: "#fb7f37",
            minor: "#fbbd50",
            warning: "#ffe680"
        }
    }
    hand = undefined;
    label = undefined;

    componentDidMount() {
        this.createChart();
    }

    componentWillReceiveProps(props) {
        if (props.data.category === "lineChart") {
            if (this.props.data && JSON.stringify(props.data.data.chartData) != JSON.stringify(this.props.data.data.chartData)) {
                if (props.operationAttribute && props.operationAttribute !== "NONE") {
                    let oldTime = chart[this.props.divId].series.getIndex(0).data.length ? chart[this.props.divId].series.getIndex(0).data[chart[this.props.divId].series.getIndex(0).data.length - 1].category : 0;
                    let operationOldTime = chart[this.props.divId].series.getIndex(1).data.length ? chart[this.props.divId].series.getIndex(1).data[chart[this.props.divId].series.getIndex(1).data.length - 1].category : 0;
                    let dataPoints = props.data.data.chartData.filter(val => val.category > oldTime)
                    let operationDataPoints = props.data.operationData.chartData.filter(val => val.category > operationOldTime)
                    if (dataPoints.length)
                        chart[this.props.divId].series.getIndex(0).addData(dataPoints, dataPoints.length);
                    if (operationDataPoints.length)
                        chart[this.props.divId].series.getIndex(1).addData(operationDataPoints, operationDataPoints.length);
                } else {
                    let oldTime = chart[this.props.divId].series.getIndex(0).data[chart[this.props.divId].series.getIndex(0).data.length - 1].category;
                    let dataPoints = props.data.data.chartData.filter(val => val.category > oldTime)
                    chart[this.props.divId].series.getIndex(0).addData(dataPoints, dataPoints.length);
                }
            }
            if (props.timeZone !== this.props.timeZone) {
                chart[this.props.divId].dispose();
                this.createChart()
            }
        }
        if (props.data.category === "gaugeChart") {
            if (this.props.data && JSON.stringify(props.data.data.value) != JSON.stringify(this.props.data.data.value)) {
                this.hand.value = props.data.data.value;
                this.label.text = `${props.data.data.value ? `${props.data.data.value.toFixed(2)} ${props.data.data.unit}` : ''}`;
            }
        }
    }

    createChart() {
        am4core.options.queue = true;
        if (this.props.type === "lineChart") {
            let _this = this;
            let config = {}
            let alarms = _this.props.attributes.find(val => val.attribute === _this.props.data.attributes[0] && val.isConfigured)
            function findColor(value) {
                if (alarms) {
                    for (var i = 0; i < alarms.alarmCriteria.length; i++) {
                        if (value < (alarms.alarmCriteria[i].type === "critical" && alarms.alarmCriteria[i].operator === "GREATER_THAN" ? 10000000 : alarms.alarmCriteria[i].high) && value >= (alarms.alarmCriteria[i].type === "critical" && alarms.alarmCriteria[i].operator === "LESS_THAN" ? -1000 : alarms.alarmCriteria[i].low)) {
                            return _this.state.alarm[alarms.alarmCriteria[i].type];
                        }
                    }
                }
            }

            // config.data = _this.props.data.data.chartData
            _this.props.data.data.availableAttributes[0].data = _this.props.data.data.chartData
            let attributesList = JSON.parse(JSON.stringify(_this.props.data.data.availableAttributes))
            if (_this.props.operationAttribute && _this.props.operationAttribute != "NONE") {
                attributesList.push({
                    attr: _this.props.operationAttribute,
                    attrDisplayName: _this.props.operationAttribute,
                    unit: "",
                    data: _this.props.data.operationData.chartData
                })
            }
            config.cursor = {}
            config.series = attributesList.map((val, seriesindex) => {
                return {
                    id: `Series${seriesindex}`,
                    name: val.attrDisplayName ? val.attrDisplayName : val.attr,
                    stroke: seriesindex ? _this.state.color[1] : _this.state.color[0],
                    strokeWidth: seriesindex ? 2 : 1,
                    tensionX: seriesindex ? 0.7 : 1,
                    type: "LineSeries",
                    xAxis: `xAxis${val.attr}`,
                    yAxis: `yAxis${val.attr}`,
                    minBulletDistance: 50,
                    data: val.data,
                    bullets: [{
                        "isDynamic": true,
                        children: [{
                            "type": "Circle",
                            "fill": am4core.color("#fff"),
                            "cursorOverStyle": am4core.MouseCursorStyle.pointer,
                            "resizable": true,
                            "width": 8,
                            "height": 8,
                            "states": {
                                "hover": {
                                    "properties": {
                                        "scale": 1.7
                                    }
                                }
                            },
                            "strokeWidth": 3,
                            "adapter": {
                                "stroke": function (stroke, target) {
                                    if (target.dataItem) {
                                        return findColor(target.dataItem.valueY);
                                    }
                                }
                            },
                            "filters": [{
                                "type": "DropShadowFilter",
                                "color": "#B8B8B8",
                                "dx": 3,
                                "dy": 3
                            }]
                        }],
                    }],
                    fill: seriesindex ? _this.state.color[1] : _this.state.color[0],
                    filters: [{
                        "type": "DropShadowFilter",
                        "color": "#e6e6e6",
                        "dx": 6,
                        "dy": 6
                    }],
                    fillOpacity: seriesindex ? 0 : 0.2,
                    dataFields: {
                        valueY: attributesList[0].attr,
                        dateX: "category",
                    },
                    adapter: {
                        tooltipText: function (text, target) {
                            if (target.tooltipDataItem._dataContext) {
                                return `${val.attrDisplayName ? val.attrDisplayName : val.attr} : [bold]${target.tooltipDataItem._dataContext[attributesList[0].attr].toString().length > 9 ? target.tooltipDataItem._dataContext[attributesList[0].attr].toFixed(2) : target.tooltipDataItem._dataContext[attributesList[0].attr]} ${" " + val.unit}`;
                            }
                        }
                    },
                    tooltip: {
                        getFillFromObject: false,
                        background: {
                            fill: "#211D21",
                            fillOpacity: 1,
                        },
                        label: {
                            fill: "#fff",
                        }
                    },
                    "segments": {
                        "fillModifier": {
                            "type": "LinearGradientModifier",
                            "opacities": [1, 0],
                            "gradient": {
                                "rotation": 90
                            }
                        }
                    },
                }
            })
            config.xAxes = attributesList.map((val, index) => {
                let obj = {
                    "startLocation": 0.5,
                    "endLocation": 0.7,
                    "type": "DateAxis",
                    id: `xAxis${val.attr}`,
                    "cursorTooltipEnabled": true,
                    "tooltipDateFormat": "dd MMM yyyy HH:mm",
                    "dateFormats": {
                        "day": "dd MMM",
                        "hour": "dd MMM HH:mm",
                        "minute": "dd MMM HH:mm",
                        "second": "HH:mm:ss",
                        "millisecond": "HH:mm:ss"
                    },
                    dateFormatter: { timezone: localStorage.timeZone },
                    "renderer": {
                        line: {
                            strokeOpacity: 0.1,
                            strokeWidth: 1,
                        },
                        "labels": {
                            "disabled": false,
                            "fill": "#808080"
                        },
                        opposite: index ? true : false,
                    },
                    "fontSize": "10px",
                }
                // if(attributesList.length > 1 && attributesList.length-1 == index){
                //     obj.syncWithAxis = `xAxis${attributesList[0].attr}`
                // }
                return obj;
            })
            config.yAxes = attributesList.map((val, index) => {
                return {
                    type: "ValueAxis",
                    id: `yAxis${val.attr}`,
                    cursorTooltipEnabled: false,
                    renderer: {
                        line: {
                            strokeOpacity: 0.2,
                            strokeWidth: 1,
                        },
                        labels: {
                            fill: "#808080",
                            adapter: {
                                "text": function (text, target, key) {
                                    if (target._dataItem.value) {
                                        if (target._dataItem.value.toString().length > 9) {
                                            return target._dataItem.value.toExponential(3);
                                        }
                                        return target._dataItem.value.toString();
                                    }
                                },
                            }
                        },
                        opposite: index ? true : false,
                    },
                    baseValue: -1000,
                    title: {
                        text: val.attrDisplayName ? `${val.attrDisplayName} ${val.unit ? `(${val.unit})` : ""}` : `${val.attr} ${val.unit ? `(${val.unit})` : ""}`,
                        fill: "#4a4a4a",
                        strokeWidth: 1,
                        fontWeight: "bold",
                        fontSize: 12
                    },
                    maxPrecision: 0,
                    fontSize: 10,
                }
            })

            _this.props.attributes.map(val => {
                if (val.attribute === _this.props.data.attributes[0] && val.isConfigured) {
                    config.yAxes[0].axisRanges = [];
                    const uniqueOperators = [...new Set(val.alarmCriteria.map(item => item.operator))];
                    if (uniqueOperators.length === 1) {
                        val.alarmCriteria.map(criteria => {
                            config.yAxes[0].axisRanges.push({
                                "series": "Series0",
                                "value": criteria.type === "critical" && criteria.operator === "LESS_THAN" ? -1000 : criteria.low,
                                "endValue": criteria.type === "critical" && criteria.operator === "GREATER_THAN" ? 10000000 : criteria.high,
                                "contents": {
                                    "stroke": _this.state.alarm[criteria.type],
                                    "fill": _this.state.alarm[criteria.type],
                                    "fillOpacity": 0.4
                                }
                            })
                        })
                    } else {
                        val.alarmCriteria.map(criteria => {
                            config.yAxes[0].axisRanges.push({
                                "series": "Series0",
                                "value": criteria.type === "critical" && criteria.operator === "LESS_THAN" ? -1000 : criteria.low,
                                "endValue": criteria.type === "critical" && criteria.operator === "GREATER_THAN" ? 10000000 : criteria.high,
                                "contents": {
                                    "stroke": _this.state.alarm[criteria.type],
                                    "fill": _this.state.alarm[criteria.type],
                                    "fillOpacity": 0.4
                                }
                            })
                        })
                    }

                }
            })
            if (_this.props.operationAttribute && _this.props.operationAttribute != "NONE") {
                config.legend = {
                    useDefaultMarker: true,
                    markers: {
                        width: 15,
                        height: 15
                    }
                }
            }
            config.scrollbarX = {
                "type": "XYChartScrollbar",
                series:["Series0"],
                minHeight : 20,
                dy: 0
            }
            config.marginTop = 20
            config.paddingRight = 10
            config.paddingLeft = 0
            config.paddingBottom = 0
            chart[_this.props.divId] = am4core.createFromConfig(config, _this.props.divId, am4charts.XYChart);
            console.log("chart[_this.props.divId]",chart[_this.props.divId].series.getIndex(0))
        } else {
            let _this = this;
            am4core.useTheme(am4themes_animated);
            // Themes end

            // create chart
            chart[_this.props.divId] = am4core.create(_this.props.divId, am4charts.GaugeChart);
            // chart[_this.props.divId].paddingBottom = 10;
            // chart[_this.props.divId].marginBottom = 0;
            chart[_this.props.divId].innerRadius = am4core.percent(90);
            chart[_this.props.divId].radius = am4core.percent(100);
            chart[_this.props.divId].startAngle = -200;
            chart[_this.props.divId].endAngle = 20;

            /**
             * Normal axis
             */

            let axis = chart[_this.props.divId].xAxes.push(new am4charts.ValueAxis());
            axis.min = _this.props.data.data.min;
            axis.max = _this.props.data.data.max;
            // axis.strictMinMax = true;
            axis.renderer.radius = am4core.percent(85);
            axis.renderer.inside = true;
            axis.renderer.line.strokeOpacity = 0;
            axis.renderer.ticks.template.disabled = false
            axis.renderer.ticks.template.strokeOpacity = 1;
            axis.renderer.ticks.template.length = 5;
            axis.renderer.grid.template.disabled = true;
            axis.renderer.labels.template.radius = 30;
            axis.renderer.labels.template.fontSize = 10;
            axis.renderer.minGridDistance = 75;
            // axis.startLocation = 1;
            // axis.endLocation = 0;

            /**
             * Axis for ranges
             */

            let colorSet = "new am4core.ColorSet();"

            let axis2 = chart[_this.props.divId].xAxes.push(new am4charts.ValueAxis());
            axis2.min = _this.props.data.data.min;
            axis2.max = _this.props.data.data.max;
            // axis2.strictMinMax = true;
            axis2.renderer.labels.template.disabled = true;
            axis2.renderer.ticks.template.disabled = true;
            axis2.renderer.grid.template.disabled = true;
            axis2.renderer.axisFills.template.disabled = false;
            axis2.renderer.axisFills.template.fillOpacity = 0.1;
            axis2.renderer.axisFills.template.fill = am4core.color("red");
            axis2.renderer.minGridDistance = 75;

            let checkAlarm = _this.props.attributes.length > 0 ? _this.props.attributes.find(val => val.attribute === _this.props.data.attributes[0] && val.isConfigured) : undefined
            if (checkAlarm) {
                const uniqueOperators = [...new Set(checkAlarm.alarmCriteria.map(item => item.operator))];
                if (uniqueOperators.length === 1) {
                    if (uniqueOperators[0] === 'GREATER_THAN') {
                        let range = axis2.axisRanges.create();
                        range.value = getFirstRangeMin();
                        range.endValue = checkAlarm.alarmCriteria[0].low;
                        range.axisFill.fillOpacity = 1;
                        range.axisFill.fill = "#00da00";

                        checkAlarm.alarmCriteria.map((category, i) => {
                            let range = axis2.axisRanges.create();
                            range.value = category.low;
                            range.endValue = category.type === 'critical' ? getLastRangeMax() : category.high;
                            range.axisFill.fillOpacity = 1;
                            range.axisFill.fill = _this.state.alarm[category.type];
                        })
                    } else {
                        checkAlarm.alarmCriteria.map((category, i) => {
                            let range = axis2.axisRanges.create();
                            range.value = category.type === 'critical' ? getFirstRangeMin() : category.low;
                            range.endValue = category.high;
                            range.axisFill.fillOpacity = 1;
                            range.axisFill.fill = _this.state.alarm[category.type];
                        })

                        let range = axis2.axisRanges.create();
                        range.value = checkAlarm.alarmCriteria[checkAlarm.alarmCriteria.length - 1].high;
                        range.endValue = getLastRangeMax();
                        range.axisFill.fillOpacity = 1;
                        range.axisFill.fill = "#00da00";
                    }
                } else {
                    checkAlarm.alarmCriteria.map((category, i) => {
                        let range = axis2.axisRanges.create();
                        range.value = category.type === 'critical' && category.operator === 'LESS_THAN' ? getFirstRangeMin() : category.low;
                        range.endValue = category.type === 'critical' && category.operator === 'GREATER_THAN' ? getLastRangeMax() : category.high;
                        range.axisFill.fillOpacity = 1;
                        range.axisFill.fill = _this.state.alarm[category.type];
                    })
                    let range = axis2.axisRanges.create();
                    range.value = checkAlarm.alarmCriteria.filter(criteria => criteria.type === 'warning' && criteria.operator === 'LESS_THAN')[0].high;
                    range.endValue = checkAlarm.alarmCriteria.filter(criteria => criteria.type === 'warning' && criteria.operator === 'GREATER_THAN')[0].low;
                    range.axisFill.fillOpacity = 1;
                    range.axisFill.fill = "#00da00";
                }
            } else {
                let range0 = axis2.axisRanges.create();
                range0.value = getFirstRangeMin();
                range0.endValue = getLastRangeMax();
                range0.axisFill.fillOpacity = 1;
                range0.axisFill.fill = "#00da00";
            }

            /**
             * Label
             */

            _this.label = chart[_this.props.divId].radarContainer.createChild(am4core.Label);
            _this.label.isMeasured = false;
            _this.label.fontSize = 16;
            _this.label.fontWeight = 600;
            _this.label.fill = "#4a4a4a";
            _this.label.x = am4core.percent(50);
            _this.label.y = am4core.percent(100);
            _this.label.horizontalCenter = "middle";
            _this.label.verticalCenter = "bottom";
            _this.label.dy = 40;
            _this.label.text = `${_this.props.data.data.value ? `${_this.props.data.data.value.toFixed(2)} ${_this.props.data.data.unit}` : ''}`;

            let label = chart[_this.props.divId].radarContainer.createChild(am4core.Label);
            label.isMeasured = false;
            label.fontSize = 13;
            label.fontWeight = 400;
            label.fill = "#4a4a4a";
            label.x = am4core.percent(50);
            label.y = am4core.percent(100);
            label.horizontalCenter = "middle";
            label.verticalCenter = "bottom";
            label.dy = 60;
            label.text = `${_this.props.data.data.attrDisplayName ? _this.props.data.data.attrDisplayName : _this.props.data.data.name}`;

            /**
             * Hand
             */

            _this.hand = chart[_this.props.divId].hands.push(new am4charts.ClockHand());
            _this.hand.axis = axis;
            _this.hand.radius = am4core.percent(80);
            _this.hand.startWidth = 5;
            _this.hand.endWidth = 1;
            _this.hand.fill = am4core.color("#4a4a4a");
            _this.hand.stroke = am4core.color("#4a4a4a");
            _this.hand.pin.disabled = false;
            _this.hand.value = _this.props.data.data.value;

            let shadowHand = _this.hand.filters.push(new am4core.DropShadowFilter());
            shadowHand.dy = 2;
            shadowHand.color = "#b8b8b8";

            let shadowPin = _this.hand.pin.filters.push(new am4core.DropShadowFilter());
            shadowPin.dy = -2;
            shadowPin.dx = -2;
            shadowPin.color = "#b8b8b8";

            _this.hand.pin.radius = 6;
            _this.hand.pin.strokeWidth = 4;
            _this.hand.pin.stroke = "#fff";
            _this.hand.pin.fill = "#4a4a4a";
            _this.hand.pin.zIndex = 1;

            function getFirstRangeMin() {
                return _this.props.data.data.min - (_this.props.data.data.max - _this.props.data.data.min)
            }

            function getLastRangeMax() {
                return _this.props.data.data.max + (_this.props.data.data.max - _this.props.data.data.min)
            }
        }

    }

    render() {
        return (
            <React.Fragment>
                <div id={this.props.divId} className="h-100"></div>
            </React.Fragment>
        )
    }

    componentWillUnmount() {
        chart[this.props.divId].dispose()
    }
}

CreateChart.propTypes = {};

export default CreateChart;

**Comment by martynasma** [comment]
Please consider posting a runnable example on CodePen/jsFiddle/StackBlitz/CodeSandbox. I'm afraid we can't point out an issue from a bunch of code like that.
