### ISSUE TITLE
Toggling bullet mask shows outer bullets

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3229]
Hey!

Is there any way to disaable masking only for the inner bullets? I know for disabling masking I'd use

`chart.maskBullets = false`

which indeed I'm using but messes up for bullets outside the viewing chart when using a scrollbar like in the screen below

![image](https://user-images.githubusercontent.com/40542072/105076908-60c33e80-5a94-11eb-8aa5-b48ac9394295.png)

Ideally I'd want inner bullets not to be clipped, so for any bullet's position that is inside the chart to have it not clipped. Is this possible? Or at least on hover to disable the mask?

![image](https://user-images.githubusercontent.com/40542072/105077245-e515c180-5a94-11eb-90ba-b80848f32cce.png)

Here for example I'd prefer if there's no other solution for the above to disable mask on hover.

Thank you!

**Comment by martynasma** [comment]
Hm, maybe set a non-transparent background on the Y axis?

```JavaScript
yAxis.background.fill = am4core.color("#fff");
yAxis.background.fillOpacity = 1;
chart.paddingLeft = 0;
```

**Comment by teodosii** [comment]
Thank you very much, that worked! I used it for both axes since I've removed clipping for series too.
