### ISSUE TITLE
How to increase granularity for days on DateAxis? BaseInterval seems to be ignored

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3230]
Hey again!

I know about the `baseLabel` on `DateAxis` but it seems to b e totally ignored for some reason

This is the DateAxis part

```jsx
const dateAxis = chart.xAxes.push(new am4charts.DateAxis())
dateAxis.padding(6, 0, 2, 0)
dateAxis.renderer.grid.template.disabled = true
dateAxis.renderer.minLabelPosition = 0.1
dateAxis.renderer.baseGrid.disabled = true
dateAxis.dateFormatter.dateFormat = 'yyyy-MM-dd'
dateAxis.baseInterval = { timeUnit: 'day', count: 1 }
dateAxis.renderer.cellStartLocation = 0.5
dateAxis.renderer.cellEndLocation = 0.5
dateAxis.keepSelection = true
dateAxis.groupData = false
dateAxis.renderer.grid.template.opacity = .4
dateAxis.renderer.inside = true
dateAxis.renderer.labels.template.fillOpacity = 1
dateAxis.tooltip.label.paddingTop = 7
dateAxis.endLocation = 0
dateAxis.startLocation = -0.5
dateAxis.min = chartData[0].date.getTime()
dateAxis.max = new Date().getTime()
dateAxis.dateFormats.setKey('day', 'MMMM dd')
dateAxis.tooltip.opacity = 0
dateAxis.cursorTooltipEnabled = false
```

What I'd like to achieve is to have as much granularity as possible for the date axis, as you can see below this doesn't happen, it shows only 1 month

![image](https://user-images.githubusercontent.com/40542072/105077604-6a00db00-5a95-11eb-8f3e-e4e4ab1ce0b8.png)

The wider the scrollbar the more months it shows but I'd like to have it more based on days when it's narrower rather than months...

![image](https://user-images.githubusercontent.com/40542072/105077868-cf54cc00-5a95-11eb-8d64-753b109d5e2f.png)

I also have this for setting width but I don't thing this is changing the granularity much

```jsx
dateAxis.events.on('sizechanged', e => {
  const axis = e.target
  axis.renderer.labels.template.maxWidth = axis.pixelWidth / (axis.endIndex - axis.startIndex)
})
```

**Comment by martynasma** [comment]
Do you mean granularity of data or the density of grid/labels on axis?

If it's the latter, you need to use `minGridDistance` setting:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Controlling_spacing
