### ISSUE TITLE
animating stepped line chart data changes

### ISSUE THREAD

**Issue by simonziegler** [amcharts/amcharts4#3231]
Hi, I I have a line chart on which I change data. To do this I set each series' data with new values one by one as in the code below. I'm using the animation theme and find that the transition is dramatic, with the y axis collapsing and re-opening as shown in the video attached.

I tried stepping through my code in Chrome developer tools and saw that each time I set series data, the old series disappears, but the new series doesn't yet display. This continues until no series are visible. Once my script finishes, amCharts repaints all the new lines, with the y axis visual jump associated.

Is there a way to take the drama out of affairs here? Ideally I'd like each line to smoothly animate to its new values (which probably do not share x values with their predecessor).

Thanks, Simon

```typescript
    if (lineSeriesDataArray) {
        for (let i = 0; i < lineSeriesDataArray.length; i++) {
            if (lineSeriesDataArray[i].showDataset) {
                let seriesData: object[] = [];

                for (let j = 0; j < lineSeriesDataArray[i].points.length; j++) {
                    seriesData.push({
                        date: new Date(lineSeriesDataArray[i].points[j].year, lineSeriesDataArray[i].points[j].month - 1, lineSeriesDataArray[i].points[j].day),
                        value: lineSeriesDataArray[i].points[j].amount,
                    });
                }

                let series = elem._chart.series.values[index++];
                series.data = seriesData;
            }
        }
    }
```

https://user-images.githubusercontent.com/11708435/105092688-78e98c80-5a99-11eb-8223-ba4682aee5c8.mp4

**Comment by martynasma** [comment]
If you have the same amount of data points in new data, you can use `invalidateRawData()`:

https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points

**Comment by simonziegler** [comment]
I saw that but unfortunately don't have the same amount of data, so I wonder if there's an alternative for me?

For instance, should I consider comparing the number of data items and then dynamically adding or removing from the old dataset before using `invalidateRawData()`?

**Comment by martynasma** [comment]
I don't see any alternative around it, sorry :(

**Comment by simonziegler** [comment]
Thank you for looking at this - I think I probably need to disable animation. As a last attempt, I discovered that series have `invalidateRawData()` methods too. Is there any documentation on these please?

**Comment by martynasma** [comment]
Yup:
https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points

**Comment by simonziegler** [comment]
Aha - I read that page but it relates only to `chart.invalidateRawData()` not `chart.series.invalidateRawData()` - I was wondering about the latter.

Tx, Simon

**Comment by martynasma** [comment]
In amCharts 4 you can set data either directly on chart or series.

If you set data on chart, you call chart's `invalidateRawData()` method.

If you set data on series, you call that method on series.

Does that make sense? :)

**Comment by simonziegler** [comment]
It does and thanks! For now I'll disable animations having spent enough time on them - animation is nice to have rather than critical. I can review in due course. Thanks for the help!
