### ISSUE TITLE
[Question] How can different polygons in a map can have different tooltip structures with selected being sticky ?

### ISSUE THREAD

**Issue by mahesh-chotrani** [amcharts/amcharts4#3232]
**Question**
I have a map where in default tooltip structure has been defined as - 

```
      let countryPolygon = countrySeries.mapPolygons.template;
      countryPolygon.tooltipText = "{name} [bold]{value}[/]";
```

What I am looking for is 
- on hover, few polygons (_i.e., areas with non-zero data_) have a different tooltip than others
- to include **sticky toggle behaviour** to this tooltip, so on click of polygon it should show or hide
- at any given time, multiple clicked tooltips can appear on map

A mock up would show as 
![image](https://user-images.githubusercontent.com/50296623/105124509-4c1c9000-5b00-11eb-8862-900065a99ebb.png)

Subscribed to polygon hit event as below - 

```
    countryPolygon.events.on("hit", function(ev) {
      // check if the state / province has data
      // if no data, do nothing and return

       if (!ev.target.dataItem.dataContext.tooltip) {
          // prepare tooltip data
          let _tt = "{name} - {value}";
          // assign 
          ev.target.tooltipText = _tt;
          // flag to make it sticky
          // ev.target.showTooltipOn = "always"
          // show tooltip
          ev.target.showTooltip(); 
          // set flag
          ev.target.dataItem.dataContext.tooltip = true;
       } else {
          // reset flag
          ev.target.dataItem.dataContext.tooltip = false;
       }
    });

```
But not have been able to get desired behaviour - 
1. **On hover**, the new tooltip is not visible; it is the same as shown for polygons with no data.
2. **On click**, new tooltip is visible, but as soon as mouse leaves the polygon, it also disappears. 
3. If `ev.target.showTooltipOn` is set as `always`, the tooltip follows the mouse pointer, even to the empty area of the map. 

Appreciate any pointers around these. Thanks !

**Comment by martynasma** [comment]
You might need to set `tooltipPosition` to fixed for it to not follow mouse:

```JavaScript
countryPolygon.tooltipPosition = "fixed";
```

**Comment by mahesh-chotrani** [comment]
Thanks for the quick solution @martynasma ! It solved the second and the third points mentioned above. 

But on `hover` no tooltip is rendered. It would be ideal to have the new tooltip, but even the old one should be fine while hovering a polygon, when the newer one is hidden. 

One more problem faced is the click of the dynamic `MapImageSeries` to render heat bubbles and labels (_as shown in the image above_) by referring to the example here - https://www.amcharts.com/demos/map-image-drill-down/ : 

The circle and labels do not respond to the `hit` event subscribed above for `countryPolygon` series. 
This seems to be as expected, because these elements seem to have a `z-index` greater than map polygon. 

Is there a way to bind the `hit` event of the circle and label (_created as `MapImageSeries`_) to the polygon these are being rendered for ? Or somehow, bubble the event from `MapImageSeries` element to the underlying polygon ?

Reason being, for an end users, the behaviour becomes - 
- if they click circle or label, nothing happens, 
- if any other uncovered polygon area, tooltip is shown

If there can be any other solution to have a consistent click behaviour, appreciate if you can point that.

**Comment by mahesh-chotrani** [comment]
Unable to have two different type of tooltips for polygons of the same map series. Going through [this section](https://www.amcharts.com/docs/v4/concepts/tooltips/#Configuring_appearance), realized that I have to set `getFillFromObject` property of a `tooltip` to false (`tooltip.getFillFromObject = false;`); 

But as I do this, the appearance of all the tooltips in the chart changes. Even if this is done on the clicked object (`ev.target.tooltip.getFillFromObject = false;` in the `hit` event handler above); 

Appreciate if you can let me know, if this is possible, and how to achieve this.

**Comment by martynasma** [comment]
> But on hover no tooltip is rendered. It would be ideal to have the new tooltip, but even the old one should be fine while hovering a polygon, when the newer one is hidden.

In that case you should probably set up "hover" and "out" events to show tooltip.

As for other questions, please consider posting separate issue, so that we don't keep monster threads with multiple topics.

**Comment by mahesh-chotrani** [comment]
> In that case you should probably set up "hover" and "out" events to show tooltip.

Thanks @martynasma . Individually subscribing above events worked. 

> As for other questions, please consider posting separate issue

Sure, I'll do that.
