### ISSUE TITLE
Changing default text color

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3233]
Hi,
every time i change text color instead default black color. I change it for every elements (labels, digits) in every chart - everything that have black color, and there are additional repeated lines of code.
Maybe, i can change this default black text color to another(i prefer gray color).
My search stoped at InterfaceColorSet, but i don't know how to apply for current theme.

**Comment by martynasma** [comment]
You can do something like that:

```JavaScript
function am4themes_myTheme(target) {
  if (target instanceof am4core.InterfaceColorSet) {
    target.setFor("text", am4core.color("#f00"));
  }
}

am4core.useTheme(am4themes_myTheme);
```

**Comment by russeljo** [comment]
thank you!
