### ISSUE TITLE
Multiple colors in toolitp? React for tooltip?

### ISSUE THREAD

**Issue by njfix6** [amcharts/amcharts4#3235]
**Question**
Will there be support for using react style code in the tooltip? Or will the tooltip support multiple text colors in the future?

**Comment by martynasma** [comment]
Tooltip already supports multiple colors with [in-line formatting](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Visual_formatting).

E.g.:

```JavaScript
series.tooltipText = "Look at me, I' [#f00]red[/]";
```

**Comment by njfix6** [comment]
This doesn't work for tooltipHTML though right? In my experience it doesn't work.

**Comment by martynasma** [comment]
Well, `toltipHTML` implies HTML :)

```JavaScript
series.tooltipHTML = "Look at me, I'm <span style="color: #f00;">red</span>";
```

**Comment by njfix6** [comment]
Oh my mistake. When trying  style="color: #f00;" in the past it didn't work but just tried it agin. Working fine 👍
