### ISSUE TITLE
Not working on Edge 

### ISSUE THREAD

**Issue by Rogeman** [amcharts/amcharts4#3236]
Hi

I'm using amcharts and have noticed it does not work well with Microsoft Edge Version 81.0.416.77 (Official build) (64-bit)

When the text is too big, instead of showing ... it shows weird characters like a€! (for example, for text Hello World it shows Hello... in Firefox which is expected, but shows Helloa€! in Edge which is not very nice looking.
When embedding the code in a Sharepoint web part in firefox it shows nicely but in edge it doesn't show at all.

Thanks
Rogelio

**Comment by martynasma** [comment]
Hi Rogelio,

It probably relates to the actual font, which does not seem to have a Unicode ellipsis symbol: `…`.

I'm not sure why your EDGE would use different font than other browsers, but it's the case.

Solution would be to either evaluate using a different font for your web page, or changing ellipsis to an actual three dot string where needed, e.g.:

```JavaScript
bullet.label.ellipsis = "...";
```
