### ISSUE TITLE
Heatmap marker color match

### ISSUE THREAD

**Issue by pcartwright81** [amcharts/amcharts4#3237]
When creating a map chart with AMCharts 4 we are taking the data into the legend and creating a legend from that.  Heatlegend has a series property that sets based on the shaded color, but I can't seem to be able to use the polygon series as the legend.series  and get any thing from it.  I tried to set the legend color with a foreach, and that did not work also.

I am trying to match the country color in the legend with the shade.  Attached is a sample of the code, which is a clone of amCharts V4: Geo Heat map.  

https://codepen.io/pcartwright81/pen/eYdoYRe

**Comment by xorspark** [comment]
Your code is creating a legend with custom items, so they have no link to the series or underlying polygons unless you specify one in the legend data array. A workaround you can use is to set an ID on your mapPolygons and perform a lookup using that ID value using [getKey](https://www.amcharts.com/docs/v4/tutorials/toggling-series-via-api/#By_id) to access the associated polygon through the marker. A propertyField that pulls the data/geoJSON id into the polygon's ID makes this easy to implement:

```
polygonSeries.mapPolygons.template.propertyFields.id = "id"; //pull ID from GeoJSON data
chart.events.on('ready', function(ev) {
  chart.legend.markers.each(function(marker) {
    marker.fill = polygonSeries.map.getKey(marker.dataItem.dataContext.id).fill;
  });
});
```

[Updated codepen](https://codepen.io/team/amcharts/pen/5de8d3eab8892956526b84b7b4ad4168?editors=0010)

**Comment by pcartwright81** [comment]
Works great! Thank you.
