### ISSUE TITLE
Is it possible to remove a bullet from the DOM entirely?

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3238]
Hey again!

I have around 400 data points which are continous points (dates to be more precise). My chart is a Line chart and I need to show bullets for points in order to interact with that specific date.

I've noticed it feels a bit laggy, mostly when hovering from a point to another, maybe it's the tooltip or there's too many bullets rendered into the DOM. Is there any possible way to actually remove a bullet from the DOM?

I have several data points with 0 value for which I hide the bullet, but it's still there.

```jsx
const bullet = series.bullets.push(new am4charts.CircleBullet())
bullet.hiddenState.properties.opacity = 0
bullet.circle.radius = 2.25
bullet.stroke = am4core.color('#fff')
bullet.strokeWidth = 0
bullet.fill = am4core.color(PRIMARY_COLOUR)
bullet.cursorOverStyle = am4core.MouseCursorStyle.pointer
bullet.events.on("hit", this.onColumnClick)
bullet.zIndex = 200
bullet.propertyFields.disabled = "disabled" /* this line turns off the opacity */

const bulletHover = bullet.states.create("hover")
bulletHover.properties.scale = 1.6
bulletHover.properties.stroke = am4core.color(PRIMARY_COLOUR)
bulletHover.properties.strokeOpacity = 0.3
bulletHover.properties.strokeWidth = 6
bulletHover.properties.fillOpacity = 1
bulletHover.properties.zIndex = 10
```

I've also added

`dateAxis.tooltipPosition = 'fixed'`

which seems to be a bit more faster but I guess turning those off would result in an even faster render

**Or is there any other way to boost it a bit? Dates are expressed in numbers as described in the performance tips article and tooltip uses fixed positioning but other than that I couldn't find anything else.**

**Comment by martynasma** [comment]
The solution would be to create just one bullet and placed where needed when cursor moves.

Maybe this demo will help:
https://codepen.io/team/amcharts/pen/yLavOOO
