### ISSUE TITLE
[Question] In a map chart, can polygons of same map series have different tooltips w.r.t. UI and data ?

### ISSUE THREAD

**Issue by mahesh-chotrani** [amcharts/amcharts4#3239]
**Question**

In a map, have few polygons for which there is some data to be displayed to end users. And for rest of the polygons, just want to have polygon name as tooltip. A screen mock for the same is as below - 

![image](https://user-images.githubusercontent.com/50296623/105320360-12c14e80-5bec-11eb-8557-f69057a9c2d5.png)

Going through [this section](https://www.amcharts.com/docs/v4/concepts/tooltips/#Configuring_appearance), realized that have to set `getFillFromObject` property of a `tooltip` to false (`tooltip.getFillFromObject = false;`); 

But with this, the appearance of **all the tooltips** in the **map series** changes. Even if this is done on the clicked object (`ev.target.tooltip.getFillFromObject = false;` in the `hit` event handler above); 

Appreciate if you can let me know, if this is possible, and how to achieve this.

**Comment by martynasma** [comment]
There are a few ways to go about it.

If you want to add fill color in data, you can use `propertyFields`:

```
series.tooltip.background.propertyFields.fill = "color";
```

https://www.amcharts.com/docs/v4/concepts/data/#Property_fields

If you need to apply custom logic for each tooltip, you can use adapter:

```
series.tooltip.background.adapter.add("fill", function(fill, target) {
  console.log(target.dataItem);
  // Based on dataItem, determine the color and return it
  return fill;
});
```

https://www.amcharts.com/docs/v4/concepts/adapters/

**Comment by mahesh-chotrani** [comment]
Thanks for pointers @martynasma . I was able to change the color by having the adapter as above. 

To change the content altogether of a tooltip (_as in image above, some will have only name of the US state, and others have a different breakdown of data_), please do let me know which adapter would be required.

**Comment by martynasma** [comment]
> To change the content altogether of a tooltip (as in image above, some will have only name of the US state, and others have a different breakdown of data), please do let me know which adapter would be required.

```JavaScript
series.tooltip.label.adapter("text", function(text, target) {
  return text;
});
```

**Comment by mahesh-chotrani** [comment]
Thanks @martynasma . 
That solves how to have different content and look of tooltips from the same series.
