### ISSUE TITLE
Superscript and subscript in labels

### ISSUE THREAD

**Issue by lnicastro** [amcharts/amcharts4#3240]
Because `baseline-shift` is no longer a valid CSS attribute and apparently using the `vertical-align` alternative seems to have no effect in the created `<tspan>` element, what would be an easy way to obtain the expected behavior?

See e.g. the [reference page](https://www.amcharts.com/docs/v4/tutorials/using-superscript-and-subscript-in-labels/) in the documentation.

**Comment by martynasma** [comment]
I suppose you could add both `baseline-shift` and `vertical-align`.

The former still seems to be supported (and probably will be for a while) by browsers. And once `vertical-align` starts to gain some support in SVG, it will take over.

And if you are using 2 and 3 as a superscript, you could just use Unicode symbols for it.

**Comment by lnicastro** [comment]
Well, the point is that both are ignored by Mozilla/Firefox and (apparently) also by IE. This is what I see in the reference page
![amc_sup_sub_labels](https://user-images.githubusercontent.com/6077048/105465473-3db2ad80-5c93-11eb-9eb6-45f3595dfd13.png)
A very simple [check code from CodePen](https://codepen.io/thebabydino/pen/GJQKQL).
Probably a warning should be added in the doc page.
I assume it cannot be replaced by the SVG `dy`attribute because in square brackets only style elements can be given.

**Comment by martynasma** [comment]
Good point. We'll add a warning in that doc. Thanks!
