### ISSUE TITLE
Scrollbar still zooms chart despite reaching the minimum width set

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3242]
[Codepen Example](https://codepen.io/raresm2020/pen/PoGgOKo)

If you narrow the thumb to the left until it reaches the minimum width, you're still able to zoom into that. 

In the screenshot below we see it's displaying only Jan 01 (you don't see Jan 03 for ex) since it was zoomed to its limit but the thumb says the interval should be wider

![image](https://user-images.githubusercontent.com/40542072/105355539-f973ce80-5bfa-11eb-98f1-fe441d206437.png)

Is there any way to disable zooming once we reach the minimum width?

**Comment by martynasma** [comment]
Setting `minWidth` on a scrollbar's thumb just caps the width of the visual element and does not affect the chart in any other way.

To properly restrict zoom, use axis' `minZoomCount`.

E.g. The following will not allow zooming in beyond less than 5 days:

```JavaScript
categoryAxis.minZoomCount = 5;
```
