### ISSUE TITLE
changePercent : tooltip attribute different colors for positive and negative value

### ISSUE THREAD

**Issue by ranell** [amcharts/amcharts4#3244]
Hi,
I'm trying to change color of label tooltext. While i'm using valueYShow =changePercent, i have some value below zero.
By default if the changePercent is positive then text color is green, else text color is red.

```
var seriesValue = chart.series.push(new am4charts.LineSeries());
	seriesValue.dataFields.dateX = "date";
	seriesValue.dataFields.valueY = "value";	
	seriesValue.dataFields.valueYShow = "changePercent";
	seriesValue.tooltipText = "{valueY.changePercent.formatNumber('[#0c0]+#.00|[#c00]#.##|0')}%";
	seriesValue.tooltip.pointerOrientation = "vertical";
	seriesValue.tooltip.getFillFromObject = false;
	seriesValue.tooltip.background.fill = am4core.color("#FFF");
	seriesValue.tooltip.background.fillOpacity = 0.5;
	seriesValue.strokeWidth = 2;
	seriesValue.smoothing= "monotoneX";
	seriesValue.fill = "#83A197";
	seriesValue.stroke = "#83A197";
```

I want to customize these colors. I tried adapter but it take value (always positive) and not changePercent instead

```
seriesValue.adapter.add("tooltipText", function(tooltipText) {
  if (seriesValue.tooltipDataItem.dataContext.value < 0) {
    seriesValue.tooltip.background.fill = "red";
  } else {
    seriesValue.tooltip.background.fill = "blue";
  }
  return tooltipText;
});

```
how to do this ? thanks
![tootip](https://user-images.githubusercontent.com/776863/105494468-212a6b80-5cbb-11eb-81a2-f3f39f546e95.png)

**Comment by xorspark** [comment]
You can access the `changePercent` by looking at the `values` object inside the `tooltipDataItem` object:

```
seriesValue.adapter.add("tooltipText", function(tooltipText, target) {
  if (target.tooltipDataItem.values.valueY.changePercent < 0) {
    target.tooltip.background.fill = "red";
  } else {
    target.tooltip.background.fill = "blue";
  }
  return tooltipText;
});
```

[Demo](https://codepen.io/team/amcharts/pen/47a109371fa39770c69da593749c5ef3?editors=0010)

**Comment by ranell** [comment]
Thanks a lot, this work actually for background. When i try `target.tooltip.label.fill` instead of background this do not work.

**Comment by xorspark** [comment]
You're assigning a color in your tooltipText (`"{valueY.changePercent.formatNumber('[#0c0]+#.00|[#c00]#.##|0')}%"`), so any fill you set will be overridden by the values in the string. In order for your `target.tooltip.label.fill` value to stick, you need to remove the inline color tags in the string (`[#0c0]`, `[#c00]`).

**Comment by ranell** [comment]
Ah really thanks ! it works 👍
