### ISSUE TITLE
Gaps in radar series

### ISSUE THREAD

**Issue by tapiamcclung** [amcharts/amcharts4#3246]
**Question**
Is it possible to hide part of the series in a radar chart?
This example shows a radar chart. In the general case, users will be able to choose dates and the chart will update accordingly with data from several years. Users can select initial and final month and year. For visualization purposes, it is better to show all the months even though it might be possible the user only selects some of the months.
Here's a [pen](https://codepen.io/tapiamcclung/pen/bGwypBx) with a radar chart that show all months but only has data for a few of them.
In this case, there is data from January to May. I would like to hide the line that joins May to January and I can do that by setting `series.connectEnds = false;` in line 21, but that doesn't work well if there is data for December (line 64).

amCharts v4 provides a way to deal with gaps in data for line charts with `connect = false`. I don't see an effect with `series.connect = false;` in this case. RadarSeries has a fillOpacity [adapter](https://www.amcharts.com/docs/v4/reference/radarseries/#fillOpacity_adapter) so I thought about using it to change the fillOpacity depending on whether there is data or not , but can't seem to find the appropriate way to set it.
```
series.adapter.add('fillOpacity', function(data) {
  am4core.array.each(data, function(item) {
    fillOpacity = item['2016'] ? 1 : 0;
  });
  return fillOpacity;
});
```

Do you have any pointers? Thanks a lot.

**Comment by martynasma** [comment]
While it would be difficult to handle such situation in chart, let me propose a workaround: put December data point first, then adjust `startAngle`/`endAngle` of the chart so that Jan is up top.

Here's a working example:
https://codepen.io/team/amcharts/pen/9dacffa255b8ee9c2f0696e48cf05df4

**Comment by tapiamcclung** [comment]
Thanks for the example. Using `series.connectEnds = false;` and adjusting the order of the data works fine for the particular case with data from Jan to May + Dec, but if there is data for every month, the series is not connected. So probably setting the property to `true` or `false` depending on whether ever data item has a value or not would work?

**Comment by martynasma** [comment]
Maybe. It's down to what possible scenarios the could be in your data configurations.

In any case, we might not be able to fix the situation where both `connect = false` and `connectEnds = true` would work properly.

Sorry.

**Comment by tapiamcclung** [comment]
Thanks!
