### ISSUE TITLE
Need to remove inner gridlines yAxes

### ISSUE THREAD

**Issue by UMSF-K13-3-Sahan** [amcharts/amcharts4#3247]
![image](https://user-images.githubusercontent.com/19708817/105515383-49c35d00-5cdd-11eb-9bfe-bb8c433038d2.png)
Hi there. Is it possible to remove only inner gridlines but save outer ones?

**Comment by martynasma** [comment]
Two options here:

1) Disable all grid lines and set a stroke on `chart.plotContainer`.
2) Disable all grid lines, and add an [axis range](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides) at the beginning ant end category/value.

**Comment by UMSF-K13-3-Sahan** [comment]
> Two options here:
> 
> 1. Disable all grid lines and set a stroke on `chart.plotContainer`.
> 2. Disable all grid lines, and add an [axis range](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides) at the beginning ant end category/value.

thx
