### ISSUE TITLE
If I want to read the source code of amcharts4, do you have any tutorial or API for source code analysis?

### ISSUE THREAD

**Issue by fu1996** [amcharts/amcharts4#3251]
If I want to read the source code of amcharts4, do you have any tutorial or API for source code analysis? Or where should we start reading? Is it possible to debug locally?

**Comment by martynasma** [comment]
Source code is available in this repo, in [/src](https://github.com/amcharts/amcharts4/tree/master/src) dir.

We don't have any documentation related directly to working with source code, though.

**Comment by fu1996** [comment]
> Source code is available in this repo, in [/src](https://github.com/amcharts/amcharts4/tree/master/src) dir.
> 
> We don't have any documentation related directly to working with source code, though.

Thank you. I'll try to read it.

**Comment by fu1996** [comment]
@martynasma I'm not very smart. I don't understand some methods. Do you have any useful debugging and development skills? Can you help me understand the code under src? Or do you use some useful methods or techniques to develop and maintain the code? thank you.
