### ISSUE TITLE
[Question] Can i explicitly said how the label should be formatted

### ISSUE THREAD

**Issue by NudeFox** [amcharts/amcharts4#3253]
There is only one data point that represents one month and it looks like this:
`{date: "2021/01/01 00:00:00", actual: 0, estimated: 0}`

And i need to set the dateAxis data label to show the same as on the bar chart, just `Jan` but it shows `1st`.
When there is a couple of data points it shows it as expected but not with only one.
How can i explicitly set format based on condition?

![image](https://user-images.githubusercontent.com/17131070/105847580-7087d900-5fe6-11eb-85fa-5c90c04d4026.png)

**Comment by martynasma** [comment]
If there's only one data item, the chart might have trouble determining granularity of your data, and you might need to specify it explicitly, e.g.:

```
dateAxis.baseInterval = {
  timeUnit: "month",
  count: 1
};
```

If that's not it, maybe you can post your chart on CodePen?
