### ISSUE TITLE
[Question] How can one subscribe hit event to toggle the dynamic pie charts rendered as 'MapImageSeries' ?

### ISSUE THREAD

**Issue by mahesh-chotrani** [amcharts/amcharts4#3254]
**Question**
Following the example of [map with dynamic pie charts](https://www.amcharts.com/demos/map-dynamic-pie-charts/), (_which is on the basis of continents_) have been able to do the same for country and state map. 

But would need to subscribe `hit` event so if a user clicks in the blank area of the polygon (_continent, country or state_), the visibility of the corresponding pie chart should toggle (_i.e., show / hide on clicks_). 

Can this be achieved ?

**Comment by martynasma** [comment]
Yes. You can ad an `id` to the data series that holds pie chart.

Then implement `hit` event on polygon series, find related pie and toggle it, e.g.:

```JavaScript
polygonSeries.mapPolygons.template.events.on("hit", function(ev) {
  var polygonId = ev.target.dataItem.dataContext.id;
  var pie = pieSeries.getImageById("chart_" + polygonId);
  if (pie) {
    if (pie.visible) {
      pie.hide();
    }
    else {
      pie.show();
    }
  }
})
```

Here's a working example:
https://codepen.io/team/amcharts/pen/71d273fdcad552485cad5c77cf957817?editors=0010

**Comment by mahesh-chotrani** [comment]
Thanks @martynasma ! I was unaware of the method `getImageById`. 

Appreciate swift response with working piece of code. :)

**Comment by mahesh-chotrani** [comment]
@martynasma , In addition to this , which property to use to have all the pie charts hidden when the map is first loaded?

So that, it is only after individual region (_here continent_) click, they are visible.

**Comment by martynasma** [comment]
```JavaScript
pieTemplate.hidden = true;
```

**Comment by mahesh-chotrani** [comment]
Thanks @martynasma  ! The suggestions above worked for me.
