### ISSUE TITLE
The question about license of XYchart and mapchart

### ISSUE THREAD

**Issue by hyerin3854** [amcharts/amcharts4#3256]
Hello,I am writing regarding xychart and mapchart.
As I heard, if I put license code before the code creating a chart or map, the license will be applied, with the related brand logo disappearing.It is true about xychart, but it isn't to mapchart. I am wondering if you could let me know the solution to the problem.
Sincerely,

**Comment by martynasma** [comment]
Please reach out to our support staff at contact@amcharts.com regarding all license-related questions and issues. Thank you.
