### ISSUE TITLE
Individual Bar colors not showing up for points/bars around 10000 (Column Series v4)

### ISSUE THREAD

**Issue by Anudeep-Kadavergu** [amcharts/amcharts4#3257]
am4core.ready(function() {
           am4core.useTheme(am4themes_animated);

           var chart = am4core.create("chartdiv_bar", am4charts.XYChart);

           chart.data = data;

           var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
           dateAxis.fontSize = 8;
           dateAxis.renderer.grid.template.disabled = true;
       
           dateAxis.keepSelection = true;
        
           var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
           valueAxis.fontSize = 5;
     
           var series = chart.series.push(new am4charts.ColumnSeries());
           series.dataFields.valueY = "Value";
           series.dataFields.dateX ="TimeStamp"; 
           series.name = "Bar chart";
           series.columns.template.tooltipText = "{dateX}: [bold]{valueY}[/]";

           // series.columns.template.fill = "color";
           series.columns.template.propertyFields.fill = 'color';
      
           var columnTemplate = series.columns.template;
           columnTemplate.strokeWidth = 2;
           columnTemplate.strokeOpacity = 1;
           columnTemplate.fillAlphas = 1;
     
           chart.scrollbarX = new am4charts.XYChartScrollbar();
           chart.scrollbarX.parent = chart.bottomAxesContainer;
           chart.scrollbarX.minHeight = 10;
           chart.scrollbarX.thumb.maxHeight = 5;
           chart.scrollbarX.thumb.maxWidth = 5;
        })

        Sample data : [{
          "TimeStamp": "Mon Sep 23 2019 20:03:46 GMT+0530 (India Standard Time)",
          "Value": 10
          "color":"rgb(99, 110, 250)"
      }]

All bar colors are showing same colors. I have drawn bars for 10000 points.

**Comment by Anudeep-Kadavergu** [comment]
<img width="771" alt="Screenshot 2021-01-28 192014" src="https://user-images.githubusercontent.com/40947280/106147460-e2eee980-619d-11eb-8d86-7c8f21814494.png">

Attached a image for reference

**Comment by xorspark** [comment]
The individual colors are there, they're just hidden by the default stroke color since there are so many columns in a tiny space. You can either map your color property to the `stroke` in addition to `fill` (`series.columns.template.propertyFields.stroke = "color"`) or set the `strokeOpacity` to zero instead of one.

[Codepen](https://codepen.io/team/amcharts/pen/b90ca73f496b2754dbb5bc3428dac4f7?editors=0010)

**Comment by Anudeep-Kadavergu** [comment]
Thanks, It's working
