### ISSUE TITLE
how can i get the params of the clicked collection in venn diagram

### ISSUE THREAD

**Issue by Huai-Dc** [amcharts/amcharts4#3258]
how can i get the params of the clicked collection in venn diagram

// code 
chart.seriesContainer.events.on('hit', function(ev){
    //  i want to get the raw data for the collection i clicked on
})

**Comment by martynasma** [comment]
Try `console.log(ev.target.dataItem)`.

**Comment by Huai-Dc** [comment]
> Try `console.log(ev.target.dataItem)`.

i tried to output undefined

**Comment by martynasma** [comment]
Do you have a full example online?

**Comment by Huai-Dc** [comment]
> Do you have a full example online?

https://codepen.io/huai-dc/pen/xxRxEwq

**Comment by martynasma** [comment]
Indeed. Sorry, I wasn't able to find a suitable way to do this.
