### ISSUE TITLE
Chart export to SVG is not a .svg file - Question

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#326]
Using download to SVG it's creating a correct .svg content file 
(<?xml version="1.0" encoding="utf-8"?><svg width....),
but when using chart.exporting.getSVG("svg") it produces a svg around the html : (data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" width=......).

https://codepen.io/aniov/pen/GXMYjv?editors=0010

I want to be able to get the real .svg so I can send it to back-end server where it will be included into a PowerPoint presentation. How can I get that ?
Thank you.

**Comment by xorspark** [comment]
The data you're getting is simply your SVG in a [Data URI format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs). It's up to your back-end to parse and decode the contents when you post it to your server if you're posting the results of `getSVG` to your server. Depending on what you're using on the server side, you can just remove the `data:<mediatype>,` part and URI decode the rest if it isn't already done for you when retrieving it from POST/whatever and get your file that way.

**Comment by aniov** [comment]
I don't think I understand how to do that. Let me rephrase what I want to achieve: 
Using "chart.exporting.getSVG("svg")" I need a svg file that I can insert in a PowerPoint document.
Using your download chart as SVG it creates a file with normal svg tags witch I can insert in a pptx file, and PowerPoint can read it. All other formats like Data URI /  base64 won't work.
So how can I get the same content of a file when using exporting function and download as SVG ?
Or how to parse this 
"%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csvg%20width%3D%22837px%22%20height...." into this 

"<?xml version="1.0" encoding="utf-8"?><svg width="837px" height..." ?
Thank you.

**Comment by xorspark** [comment]
I'm assuming you're posting this to your server, correct? You're not explaining your workflow very well

Typically when you post data to your server, the data is URI/base64 encoded, depending on what you're posting. It's up to your backend to parse that out. For data that is just URI encoded, the backend typically auto decodes this for you, so where the SVG data is concerned in this case, it already looks like this in in your server's POST/whatever variable:

```
data:image/svg+xml;charset=utf-8,<?xml version="1.0" encoding="utf-8"?><svg width="1729px" ...
```

So all your backend needs to do is grab the stuff after the first comma and write the rest to a file if you're just saving the result for someone to put into their powerpoint.

If you're doing this all in the front-end, just call split on the string and `decodeURIComponent` on the stuff after the comma:

```
decodedSVG = decodeURIComponent(imgData.split(',')[1]); //returns just <?xml ....><svg ...></svg>
```

Here's a [codepen](https://codepen.io/team/amcharts/pen/9fc0c42c0a67eb0aa6d986bcebd2002b/) demonstrating that.

Does this make sense?

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
