### ISSUE TITLE
chart line disappears at zero / close to zero values

### ISSUE THREAD

**Issue by sellsteam13** [amcharts/amcharts4#3261]
**Bug description**
Hello! If you reduce the size of the scrollbar and then start moving it from right to left, then the graph will disappear at zero values. Probably the graph line goes under the zero value of the X axis. Is this a bug or do you have any restrictions in the library on what data the graph can work with? Thanks!

For vanilla JavaScript examples use:
https://codepen.io/sellsteam13/pen/QWGwpqX

Provide details about your development environment where you think it might be useful. E.g.:

 - 4
 - Any
 - without framework

**Comment by martynasma** [comment]
It's not about zero values, it's about order of the data.

Data should come in ascending order, whereas yours is in descending, hence the anomaly.
