### ISSUE TITLE
How to conditional format (heatmap) a TreeMap with a different value from the TreeMap's value?

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts4#3263]
Suppose I have a data set that is something like this:

[
  {
    "industry": "Manufacturing",
    "weight0": 25,
    "children": [
      {
        "name": "abc",
        "weight": 20,
        "return": 1.3,
        "weightTotal": 0.5
      },
      {
        "name": "def",
        "weight": 15,
        "return": 2.1,
        "weightTotal": 0.375
      },...

I have a TreeMap that I split by "industry" based on "weight0", and then within each industry I split further by "weight". Finally with each name I want to conditional format based on "return", so green if +ve and red if -ve.

I think I can get around the issue of multiple splitting weights by using "weightTotal" which is the product of weight0 and weight, but I'm not sure how to feed in the field "return" to do the conditional highlighting.

**Comment by martynasma** [comment]
Heat rules won't work on TreeMap because of the fuzzy logic behind color inheritance.

Here's a demo which uses adapters to apply weight-based color instead:
https://codepen.io/team/amcharts/pen/KKMrPPj

Hope you find it useful.

**Comment by dez1729** [comment]
Thanks, but the example doesn't exactly use an external "value" to set the color, which in my example would be the "return" field. How would I go about that in this example?

**Comment by martynasma** [comment]
How about this one?
https://codepen.io/team/amcharts/pen/104d908b272d82cc118035ce4864a784?editors=0010

**Comment by dez1729** [comment]
Thanks that might get me closer to what I need.

I have another TreeMap related question...Is there a way for amcharts to produce sub headings in TreeMap? In other words I hope to replicate something like what finviz does:

![zk2ot2w9u2e11](https://user-images.githubusercontent.com/20635596/106713767-c264cc00-65af-11eb-9561-cc5af25a59bf.png)

**Comment by martynasma** [comment]
No, I'm afraid.
