### ISSUE TITLE
How to Add A row to Treemap 

### ISSUE THREAD

**Issue by fightlikeagirl** [amcharts/amcharts4#3264]
Hello, I have so basic knowledge. I want to add an second row to this tree map :  
[https://codepen.io/team/amcharts/pen/erojQb](url) 
Can someone show me a way please? Thanks

**Comment by martynasma** [comment]
There is no way to control specific rows or columns in a TreeMap chart. The layout is handled by itself, using chosen algorithm.

More info about available layout algos is here:
https://www.amcharts.com/docs/v4/chart-types/treemap/#Area_division_methods

**Comment by fightlikeagirl** [comment]
@martynasma  thanks for answer. Can I ask more? 
[https://codepen.io/aysuaysu/pen/YzpPBXO](url) in this code, I want to display more text, so I want to there is no space padding margin etc, ı want to name(text) cover the whole box. How can I do that ?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
