### ISSUE TITLE
Display name  in whole box

### ISSUE THREAD

**Issue by fightlikeagirl** [amcharts/amcharts4#3265]
[in this code](https://codepen.io/aysuaysu/pen/YzpPBXO), I want to display more text, so I want to there is no space padding margin etc, I want to name(text) cover the whole box. How can I do that ?

**Comment by martynasma** [comment]
You may need to disable `truncate` and enable `wrap` on those bullet labels:

```JavaScript
bullet1.label.truncate = false;
bullet1.label.wrap = true;
```

**Comment by fightlikeagirl** [comment]
It worked. Thank you so much.
