### ISSUE TITLE
Chart scrollbarX bug with parsing dates

### ISSUE THREAD

**Issue by NudeFox** [amcharts/amcharts4#3266]
Scrollbar baseInterval was explicitly set to days. And when the data comes with only dates for one day it starts to show the years instead of having one day.

Init of the scrollbar:
```
const scrollbarChart = chart.scrollbarX.scrollbarChart;
const scrollbarRenderer = scrollbarChart.xAxes.getIndex(0).renderer;
scrollbarRenderer.grid.template.disabled = true;
scrollbarRenderer.labels.template.location = 0.0000001;
scrollbarRenderer.labels.template.fill = am4core.color('#838FB6');
scrollbarRenderer.labels.template.fillOpacity = 1;
scrollbarChart.xAxes.getIndex(0).baseInterval = {
    timeUnit: 'day',
    count: 1,
};

const scrollSeries1 = scrollbarChart.series.getIndex(0);
scrollSeries1.filters.clear();
scrollSeries1.hide();
```

The data for chart:
![Screenshot at Feb 01 15-22-54](https://user-images.githubusercontent.com/17131070/106471656-872ca500-64aa-11eb-85e2-777d4a09725f.png)

How the chart parse it:
![Screenshot at Feb 01 15-22-29](https://user-images.githubusercontent.com/17131070/106471706-957ac100-64aa-11eb-9175-a80883f77a04.png)

If there is need to any other details i'm glad to provide them.

Codepen with representation: https://codepen.io/NudeFox/pen/qBqEzxB

**Comment by martynasma** [comment]
Are you actually using different data than the chart, or you just want to force higher granularity of labels for the scrollbar?

If it's the latter, you should probably modify `gridIntervals` for scrollbar's DateAxis, instead.

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Controlling_automatic_granularity_of_axis_grid

**Comment by NudeFox** [comment]
Well? In most cases i receive data that has a couple of days. But granularity could differ from 1+ minute. In case when we have a couple of days there everything is working fine. But as long as you receive data for only one day the scrollbar start to show those strange years.

Working data looks like this: 
![image](https://user-images.githubusercontent.com/17131070/106478704-24d7a280-64b2-11eb-8273-92700b9834b0.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by NudeFox** [comment]
I would mock the data for that and post it.

**Comment by NudeFox** [comment]
Well? i've tried with dateAxis also, and the same stuff there. https://codepen.io/NudeFox/pen/qBqEzxB

**Comment by martynasma** [comment]
I'm trying to wrap my ahead around what you are trying to do here.

Currently you have data with granularity of minutes, yet you are telling the chart that you have data is in day increments. `baseInterval` is essentially a hint to DateAxis about what your data is.

So what is it that you want to show on chart and the scrollbar? A single data point per day, and a single grid/label for that day in data, even though you have a number of actual data points spaced out each few minutes?

**Comment by NudeFox** [comment]
The point was to have data in the chart as is, with granularity in minutes. Also the chart could be zoomed in and out. And the scrollbar here is somewhat like a range selector with a day granularity. And that works perfect while there are a couple of days in data. 
![image](https://user-images.githubusercontent.com/17131070/106667424-934f5a00-65b1-11eb-8a60-7202feb6fbc4.png)

**Comment by martynasma** [comment]
How about using `groupData` for scrollbar's DateAxis only?

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping

**Comment by NudeFox** [comment]
Thanks for mentioning it, I'll try that. But the main point here is that this date parsing is a bug or not? Maybe there should be some restrictions to how the baseInterval works? or at least it shouldn't parse the same days as different years.

**Comment by martynasma** [comment]
I don't think so. `baseInterval` is a setting which tells axis about characteristics of data, not how it should display it.

So, "lying" in `baseInterval` produces anomalies, I would not consider it a bug :)
