### ISSUE TITLE
is it possible to export external table in external button click Using amchart4 ?

### ISSUE THREAD

**Issue by hshahul** [amcharts/amcharts4#3267]
I want to download table export using amchart export functionality. Is it possible to call export exporting adaptor event from external button click?
In amchart 3:

	<button onclick="exportXLSX()" class="dropdown-item" data-click="XLSX">XLSX</button>

function exportXLSX(){
chart.export.toCSV({}, function(data) {
    this.download(data, this.defaults.formats.CSV.mimeType, "amCharts.csv");
  });
}

there is any code like above example...in amchart4 version

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v4/concepts/exporting/#Using_export_API

**Comment by hshahul** [comment]
thanks for your response. I can get excel with created charts  using  chart.exporting.export("xlsx");.
My doubt is how can I get excel for external table using amchart export.? 
I am not able to get chart object using the following 
am4core.chart.exporting.export
am4chart.exporting.export

can you tell me is it possible to download external table using amchart export?

**Comment by martynasma** [comment]
> can you tell me is it possible to download external table using amchart export?

That is a bit out of scope of chart functionality.

We are using SheetJS library to generate XLSX documents.

https://docs.sheetjs.com/

You can use it to export your own information to Excel format, too, I guess.
