### ISSUE TITLE
Exporting events not fired when using getImage

### ISSUE THREAD

**Issue by 3zzy** [amcharts/amcharts4#3268]
Exporting events (`exportstarted` and `exportfinished`) are not fired when using `getImage` method.

Here's a quick fiddle: https://jsfiddle.net/iaezzy/gtkqea8u/9/

**Comment by martynasma** [comment]
This is by design.

An export operation is considered one that is invoked by `export()` method, or by selecting it from ExportMenu.

Individual `get***` functions would not trigger any events.

Use `Promise` functionality instead. You seem to already have `then()` handler in your code.
