### ISSUE TITLE
RangeSelector end date are automatically setting to end + some days

### ISSUE THREAD

**Issue by RSchneider94** [amcharts/amcharts4#3269]
**Bug description**

I don't know if it's really a bug or a config, but until now it seems to be working normally and today I saw this problem at my application. Here are some screenshots to explain it better:

![image](https://user-images.githubusercontent.com/11929659/106532736-80fcef80-64cf-11eb-9cf7-7f4d19cd3084.png)
(the position `246` of the array is my last object, as you can see, `2021-02-01` is the last date that should be the end date)

But here:
![image](https://user-images.githubusercontent.com/11929659/106532813-ac7fda00-64cf-11eb-9352-1c9279ff0195.png)
my `selector.container` "Até (until)" are going until `2021-02-08`.

And here are the periods that I use:

```javascript
selector.periods = [
  { name: '1 Sem.', interval: { timeUnit: 'week', count: 1 } },
  { name: '1 Mês', interval: { timeUnit: 'month', count: 1 } },
  { name: '3 Meses', interval: { timeUnit: 'month', count: 3 } },
  { name: '1 Ano', interval: { timeUnit: 'year', count: 1 } },
];
```

Have some of you guys already experienced this before? How to fix this?

Thanks.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by RSchneider94** [comment]
> Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

Hi @martynasma ! Thanks for the reply.

I have made a code snippet of my code here: https://codesandbox.io/s/friendly-moser-9tnzs?file=/src/App.js

Unfortunately (strangely) at code sandbox it's actually working normally. But I can't see why on my project don't. And my last date object it's really like the one on codesandbox `2021-02-01T00:00:00.000Z`. And the `apiRangeDate` is also correctly set: `apiRangeDate: ["2020-02-03", "2021-02-02"]`.

**Comment by martynasma** [comment]
OK, so we actually released a new version today, that fixes some issues with the RangeSelector.

Your internal project might still b using older version.

Can you try upgrading and see if it fixes the issue?

**Comment by RSchneider94** [comment]
> OK, so we actually released a new version today, that fixes some issues with the RangeSelector.
> 
> Your internal project might still b using older version.
> 
> Can you try upgrading and see if it fixes the issue?

just did this, unfortunately it's still not working 😢

**Comment by martynasma** [comment]
Darn.

Well, we'll still need some way to reproduce it.

**Comment by RSchneider94** [comment]
> Darn.
> 
> Well, we'll still need some way to reproduce it.

Thanks for all the help @martynasma .. unfortunately I couldn't reproduce it in a different env of mine :( I'll close the issue.
