### ISSUE TITLE
bullet tooltip is undefined

### ISSUE THREAD

**Issue by incadoi** [amcharts/amcharts4#327]
Hello,

I want to customize the appearance of the tooltip for a bullet but it's value is undefined. Here is a [codepen](https://codepen.io/anon/pen/VGrwGE?editors=1111) and if you uncomment line 54 it will throw an error because tooltip is undefined. How can I customize the appearance of the tooltip in this case?

**Comment by zeroin** [comment]
Bullets do not have their own tooltip and they use chart's main tooltip, or, if a cursor is enabled they use series tooltip. So you should modify chart's tooltip instead:

`chart.tooltip.background.fill = am4core.color('#fff');
chart.tooltip.getFillFromObject = false; // this needed for the color to be applied` 

Although in next release we are changing this behavior a bit and bullets will always use series tooltip, even without cursor. so after next release  you'll have to do the same on lineSeries tooltip.

**Comment by incadoi** [comment]
@zeroin thank you for insights!

**Comment by zeroin** [comment]
You are welcome :)
