### ISSUE TITLE
Missing Tooltips when the y-axis values are more than the max limit of the ValueAxis

### ISSUE THREAD

**Issue by venigallapraveen** [amcharts/amcharts4#3270]
**Bug description**

Unable to view tooltips when the value axis values are more than the max limit of the value axis. 
The following screenshots verify this bug:
A. Tooltips are clearly visible when the value is less than the max limit of the value axis.
![Screen Shot 2021-02-02 at 9 08 13 AM](https://user-images.githubusercontent.com/39606861/106612505-27c8a680-6537-11eb-8849-b024b2c9856e.png)
B.Tooltips are missing/ hidden when the y-axis value is more than the max limit of the value axis. Eg: The max limit of the value axis in this example is 80. 
![Screen Shot 2021-02-02 at 9 08 25 AM](https://user-images.githubusercontent.com/39606861/106612513-2ac39700-6537-11eb-95f4-1606fc134e30.png)

**For React use:**
CodePen (https://codepen.io/venigallapraveen/pen/oNYXqzR)

**Environment** 
 - AmCharts version: 4.10.13
 - React Version: 17.0.1

**Comment by martynasma** [comment]
The cursor snapping algo is constructed to snap to visible data points only. I'm afraid we do not have any plans on changing it. Sorry.
