### ISSUE TITLE
Which event I can use?

### ISSUE THREAD

**Issue by mazurp** [amcharts/amcharts4#3271]
**Question**
Hi,

I try implement logic to keep zoom after new data comes.

```
const minZoomed = chart.xAxes.values[0].minZoomed;
const maxZoomed = chart.xAxes.values[0].maxZoomed;

chart.addData(newPoints, chart.data.length >= 143 ? newPoints.length : 0); //144 = 24 hours

chart.xAxes.values[0].zoomToDates(minZoomed, maxZoomed); 
```
When I try execute list line directly after addData() the xAxes is not updated/ready yet and it's not working.

When I did workaround with setTimeout is sometime work but sometime one second is not enough.

```
 setTimeout(() => {
    chart.xAxes.values[0].zoomToDates(minZoomed, maxZoomed); 
}, 1000);
```
I need to find better solution. I  tried to use "datavalidated" but it's also trigger too soon so you have idea which event should I use in my case.

Best regards and thank you in advance,
Patryk Mazur

**Environment (if applicable)**

 - amCharts version **4.10.9**
 - Browser and its version **All**
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.] **React 16.14.0"**

**Comment by martynasma** [comment]
Why not just use [`keepSelection`](https://www.amcharts.com/docs/v4/reference/valueaxis/#keepSelection_property)?

**Comment by mazurp** [comment]
Because sometime I want keep zoom and sometime not.

**Comment by martynasma** [comment]
In that case you can set it to `true` or `false` just before setting new data.

**Comment by mazurp** [comment]
I changed it to use `keepSelection` and it's working like expected so thank for your help.
