### ISSUE TITLE
Lag when rotating globe / orthographic projection

### ISSUE THREAD

**Issue by Bartvelp** [amcharts/amcharts4#3275]
**Question**
Hi amcharts4 mainteners,
I would like to use the orthographic projection, but I am experiencing lag when rotating the globe on any hardware / browser combination I use.
Is there any way to reduce the time per frame? It should be possible.

**Environment (if applicable)**
See https://codepen.io/team/amcharts/pen/vQzvEv for your own example

**Comment by martynasma** [comment]
Consider disabling background and graticule series. It will make globe faster.

Other than that, there's little that can be done.

**Comment by Bartvelp** [comment]
Thanks for the tips, I already tried that but found the performance still to be lacking.
Do you might know why it is so laggy? I would guess that a 4 ghz processor should be able to rotate a sphere smoothly.
I noticed performance in Safari is significantly better than chrome and firefox, maybe that gives a hint.

**Comment by martynasma** [comment]
Well, re-rendering SVG on each turn is slow.

I'm not sure what to suggest :(

**Comment by Bartvelp** [comment]
That's fine, maybe just a limitation of browser performance then.
I would guess that maybe using a canvas could be faster, but that would be a drastically different approach and this is not the right library.
Maybe someone clever can come up with an improvement, but I'll close the issue.
