### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "@amcharts/amcharts4/maps"

### ISSUE THREAD

**Issue by voitje** [amcharts/amcharts4#3276]
Hello! I use native import without sort of bundler that is generating a broken import.
`import * as am4maps from "@amcharts/amcharts4/maps"`
and this error comes out
`Uncaught TypeError: Failed to resolve module specifier "@amcharts/amcharts4/maps". Relative references must start with either "/", "./", or "../".`

The error appeared after updating the package: d3-array (2.9.0 -> 2.11.0).
And I already described this error (https://github.com/mbostock/internmap/issues/1) (This error pops up if I add a slash before @amcharts, like this `import * as am4maps from "/@amcharts/amcharts4/maps"`)

**Comment by martynasma** [comment]
If you are not using any packager that might resolve NPM package names, you need to do `npm install` and do import using your own local path.

```TypeScript
import * as am4maps from "./node_modules/@amcharts/amcharts4/maps"
```
