### ISSUE TITLE
How to add series at a specific position in sorted XYchart without taking into account its value

### ISSUE THREAD

**Issue by Mohamed-Amine-AALI** [amcharts/amcharts4#3277]
![az](https://user-images.githubusercontent.com/72966861/106764623-3ea2f200-6638-11eb-8f42-dd9646c5852a.PNG)

This chart represents prices of different services that cloud providers offers.

In this XYchart, you can see 3 series at the very top that have a value of 0, those are bandwidth of OVHCloud, the thing is that in some places in the world, OVHCloud bandwidths are free, and because of that their width is equal to 0, and I can't click on them and use my on("hit") amcharts function.

The chart is sorted from the cheapest to the most expensive
What can I do to make sure that these 3 series stay at the very top of the sorted chart, and make them have an actual width, so I can click on them to do stuff ? With a label "FREE"

Thank you

**Comment by martynasma** [comment]
I'd probably do two things:

1) Unmask bullets so they are not cut off (`chart.maskBullets = false`)
2) Add hit event to the logo bullet, so it's clickable.

**Comment by Mohamed-Amine-AALI** [comment]
> 
> 
> I'd probably do two things:
> 
>     1. Unmask bullets so they are not cut off (`chart.maskBullets = false`)
> 
>     2. Add hit event to the logo bullet, so it's clickable.

Thank you for your answer.
I added an on("hi") function to the images, it works fine.
I added chart.maskBullets = false into my code, here's the result which is kinda weird : 
![azz](https://user-images.githubusercontent.com/72966861/106877767-6b5b1600-66d9-11eb-80cf-891ab717408d.PNG)

**Comment by martynasma** [comment]
Maybe you need to add some `paddingRight` to your scrollbar.

Also. maybe disable labels or right-align them for zero values, using adapter.

E.g.:

```
labelBullet.label.adapter.add("horizontalCenter", function(center, target) {
  return target.dataItem.valueY == 0 ? "left": center;
});
```
