### ISSUE TITLE
Radar chart category axis cursor tooltip wrong value revisited

### ISSUE THREAD

**Issue by tapiamcclung** [amcharts/amcharts4#3278]
**Bug description**
This was reported in #1637. Change log for v. 4.6.2 reads that `RadarCursor` could show incorrect label if the chart had CategoryAxis with only 3 categories was fixed.
This is still showing on my radar chart and also found it on the docs. For instance, in the [
Stacked radar columns](https://www.amcharts.com/docs/v4/chart-types/radar-chart/#Stacked_radar_columns) example ([pen here](https://codepen.io/team/amcharts/pen/KRQgKO)) if we hover between Czech Republic and Australia, series tooltips are correct, but axis tooltips are not.
I tried changing axis' `startLocation` and `endLocation` but cannot quite get it right.

**Comment by martynasma** [comment]
You can use the following workaround to fix the issue:

```JavaScript
categoryAxis.renderer.tooltipLocation = 0.001;
```

**Comment by tapiamcclung** [comment]
Thanks!
