### ISSUE TITLE
Dynamically change chart timezone offset

### ISSUE THREAD

**Issue by venigallapraveen** [amcharts/amcharts4#3279]
**Question**

I'm trying to figure out how to change a chart's timezone dynamically using a selector/button. 
E.g., A user can select a timezone using the timezone selector, and the chart renders timestamps in the user-selected timezone setting. 

 Until now, I'm changing the timezone of the incoming data manually and then sending this parsed data to the chart.

 I'm wondering if I can achieve the same(able to set/change timezone offset of the chart) using amcharts builtin API. I went through the docs, and it isn't clear how to add a timezone offset to the date axis when the incoming data is in UTC. 

My incoming data array: 
```
let data = [{
   value: 100,
   timestamp: "2021-02-03T15:45:27.074Z", //time in utc date format
  },
 {
  value: 200,
  timestamp: "2021-02-03T15:45:27.074Z",
 }]

```

I would appreciate it if you could point me to an example of setting the timezone offset of the date axis when the incoming data is in UTC. 

Thanks,

**Environment** 
 - AmCharts version : 4.10.13
 - React version: 17.0.1

**Comment by martynasma** [comment]
There is no example, but setting `timezone` or `utc` on `chart.dateFormatter` should be sufficient.
