### ISSUE TITLE
applyOnClones doesn't work with column width

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#328]
Example:
https://codepen.io/dmsmaxim/pen/QVOWoN

If you click on "Change width button", columns don't become 10% width:
![image](https://user-images.githubusercontent.com/15041200/45208717-ee22e100-b293-11e8-9bf0-240088310b25.png)

**Comment by zeroin** [comment]
Hi,

It's the same issue like in https://github.com/amcharts/amcharts4/issues/290
You must call series.invalidate() after width is changed.

**Comment by dmsmaxim** [comment]
But why? As I understand **applyOnClones** setting must do all the work.
By the way, what does this method `series.invalidate()` do? I can't even find it in the documentation.

**Comment by martynasma** [comment]
@dmsmaxim In some rare scenarios, such as this one, it would be too expensive performance-wise to monitor all changes that are very unlikely to be changed.

In such cases, you might need to manually invalidate series to cause a redraw.

We'll expose `invalidate()` method in docs. Thanks for the heads up!

**Comment by martynasma** [comment]
FYI, updated classref to expose `invalidate()`.

https://www.amcharts.com/docs/v4/reference/series/#invalidate_method

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
