### ISSUE TITLE
Hoverable tooltips not appearing in exported image

### ISSUE THREAD

**Issue by dhiren-eng** [amcharts/amcharts4#3280]
Hi,

I'm using exporting menu functionality and the tooltipText appears on hovering on respective columns.. The requirement is to show tooltips also in the downloaded jpg file since the tooltip holds a lot of useful information in our actual project. But this is not happening as seen in this sample codepen : [https://codepen.io/dhiren530/pen/vYyNbxj?editors=0010](https://codepen.io/dhiren530/pen/vYyNbxj?editors=0010) . 

So we have to separately take screenshots and give names to screenshots and then save them while preparing presentations which becomes time consuming. The same issue persists while using export api also.

Displaying hoverable tooltips in exported images will be very useful in a lot of cases 

@martynasma

**Comment by martynasma** [comment]
Perhaps you will find this demo useful:
https://codepen.io/team/amcharts/pen/8375a7fcc74f90a7afe52a6a4b8ea1e4?editors=0010

**Comment by dhiren-eng** [comment]
In the above demo 2 column series were being used but I'm using a single column series in my actual project and in that case the tooltip of each column is not shown . The issue is replicated in this codepen : [https://codepen.io/dhiren530/pen/wvoMGoR?editors=0010](https://codepen.io/dhiren530/pen/wvoMGoR?editors=0010)

**Comment by martynasma** [comment]
If you need multiple tooltips shown for a single series, you will need to create Tooltip instances for each column:

```JavaScript
series.columns.template.tooltip = new am4core.Tooltip();
```

**Comment by dhiren-eng** [comment]
Thanks a lot for the solution.. Now the only issue is that the opacity of the tooltips in exported image is less in actual project as shown below.. 
![image](https://user-images.githubusercontent.com/59474883/107028143-26b3a580-67d3-11eb-8179-0ed6ea662168.png)

I had tried validateSprites in the loop as shown below but it does not seem to work : 
        chart.series.values[0].columns.each(function (column){
          chart.exporting.validateSprites.push(column.tooltip);//also tried .....validateSprites.push(column)
        });

Is there any other way to delay export operation until the tooltips are ready ? Any solution for this problem will be very much appreciated..

**Comment by dhiren-eng** [comment]
Solved the problem by changing tooltips animation settings during export start and resetting the settings after export finishes.   

 function hideToolTipp() {
        boxplot.series.values[0].columns.each(function (column){
          column.tooltip.animationDuration = 500;
          column.tooltip.defaultState.transitionDuration = 500;
          column.tooltip.hiddenState.transitionDuration = 500;
          column.hideTooltip(0);
        });
      }      
function showToolTipp() {
        boxplot.series.values[0].columns.each(function (column){
          column.tooltip.animationDuration = 0;
          column.tooltip.defaultState.transitionDuration = 0;
          column.tooltip.hiddenState.transitionDuration = 1000;
          column.showTooltip(0);
        });
      }

**Comment by dhiren-eng** [comment]
Hi,

One observation in the demo shared by you in your previous comment [https://codepen.io/team/amcharts/pen/8375a7fcc74f90a7afe52a6a4b8ea1e4?editors=0010](https://codepen.io/team/amcharts/pen/8375a7fcc74f90a7afe52a6a4b8ea1e4?editors=0010) is that the tooltips are not shown in the exported SVG.. Could you please mention the reason for the same and also how to resolve it ?

**Comment by martynasma** [comment]
Those export for me fine, but there might be some timing issues with specific setups/browsers.

Try adding tooltips to tooltip to export's `validateSprites`:

```
chart.exporting.validateSprites.push(series1.tooltip);
chart.exporting.validateSprites.push(series2.tooltip);
etc.
```

**Comment by dhiren-eng** [comment]
Added the above code but still getting the same result i.e. tooltips not showing only in SVG export .. Tooltips are appearing in JPG, PNG and PDF exports.. Is it really happening because of browser issue because in that case the problem should be for all types exports and not just SVG ?

**Comment by martynasma** [comment]
Hm, indeed. Tooltips do not appear in SVG export. Not sure why is that. Don't have a solution. If I think of something, I'll let you know.
