### ISSUE TITLE
Tooltips missing after selecting a period with DateAxisRangeSelector

### ISSUE THREAD

**Issue by RSchneider94** [amcharts/amcharts4#3281]
**Bug description**
I have a XYChart where I have three different series and their values, plus a `DateAxisRangeSelector` in order to filter it. And I have a similar chart in my app that works the same way, with more than one series also and it works, but this one is missing tooltips after selecting a period or zooming in/out the chart. I can't figure out why. I have made a codesandbox and the problem has also appeared there:

https://codesandbox.io/s/friendly-moser-9tnzs
(I have no ideia why the period selection is not working on codesandbox, but in my project it is, but you can reproduce the bug using the slider though).

**Environment**
 - amCharts version: 4.10.14
 - Related frameworks and their versions: React 16.13.1

**Comment by martynasma** [comment]
I suppose this is due to that you have multiple data points for the same timestamp.

When chart is fully zoomed out, `groupData` kicks in and produces aggregate data items, so that all tooltips show up.

When you zoom in, grouping is disabled and no aggregating data points are produced. When cursor is looking for a data point that is closest to it sposition, it finds one data point, and shows tooltip for it.

I don't know if that makes sense or not, but bottom point you should probably aggregate your data points.

E.g. instead of this:

```
  {
    date: "2020-02-04T00:00:00.000Z",
    volume: 18750100,
    mainTickerClose: 30.4393
  },
  { date: "2020-02-04T00:00:00.000Z", marketClose: 32.2227766738921 },
  { date: "2020-02-04T00:00:00.000Z", sectorClose: 24.6309814453125 },
```

Have this:

```
  {
    date: "2020-02-04T00:00:00.000Z",
    volume: 18750100,
    mainTickerClose: 30.4393,
    marketClose: 32.2227766738921,
    sectorClose: 24.6309814453125
},
```

**Comment by RSchneider94** [comment]
> I suppose this is due to that you have multiple data points for the same timestamp.
> 
> When chart is fully zoomed out, `groupData` kicks in and produces aggregate data items, so that all tooltips show up.
> 
> When you zoom in, grouping is disabled and no aggregating data points are produced. When cursor is looking for a data point that is closest to it sposition, it finds one data point, and shows tooltip for it.
> 
> I don't know if that makes sense or not, but bottom point you should probably aggregate your data points.
> 
> E.g. instead of this:
> 
> ```
>   {
>     date: "2020-02-04T00:00:00.000Z",
>     volume: 18750100,
>     mainTickerClose: 30.4393
>   },
>   { date: "2020-02-04T00:00:00.000Z", marketClose: 32.2227766738921 },
>   { date: "2020-02-04T00:00:00.000Z", sectorClose: 24.6309814453125 },
> ```
> 
> Have this:
> 
> ```
>   {
>     date: "2020-02-04T00:00:00.000Z",
>     volume: 18750100,
>     mainTickerClose: 30.4393,
>     marketClose: 32.2227766738921,
>     sectorClose: 24.6309814453125
> },
> ```

Yes!! Perfect!! Thanks!!
