### ISSUE TITLE
Inoperable browser when using value axis labels html template and no series data

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3282]
**Bug description**

_This is maybe a following bug of #3252 and happens since amcharts 4.10.14_

Simple chart with line series which uses a **html template for the value axis labels**.
Updating the chart data with a series having no data (e.g. user chooses date where there are no measurements) results in an inoperable browser.

https://codepen.io/chrisadler/pen/ExNVdGw?editors=1010

**Environment (if applicable)**

 - amCharts version: 4.10.14/4.10.15
 - Browser and its version: all browsers

**Comment by martynasma** [comment]
It jumps out at me that you are using `{text}` in the label's html. It tries to grab `text` property from itself, which might lead to circular references in some cases, especially with ghost labels that have no value.

Better use `{value}` which is safer.

**Comment by lticadler** [comment]
Thank you very much.
Updated the pen with the solution :)
