### ISSUE TITLE
TreeMap logic to define sizes of each series

### ISSUE THREAD

**Issue by RSchneider94** [amcharts/amcharts4#3283]
**Question**
So I'm using the TreeMap to display some data. It's working pretty fine but I'm asking me how the `TreeMap` logic works to define the sizes of series. Because I have an example here, where I have 2 `children` objects and they have very similar values, but one is much bigger than the other. As the screenshots show:

<img width="1424" alt="Screen Shot 2021-02-04 at 17 13 46" src="https://user-images.githubusercontent.com/11929659/106950538-5009fe00-670d-11eb-9e63-3d18c96b396a.png">

<img width="518" alt="Screen Shot 2021-02-04 at 17 13 52" src="https://user-images.githubusercontent.com/11929659/106950548-55674880-670d-11eb-9122-6388dec9181e.png">

why are the red one (on the right) so small? And no, it's negative just in the tooltip / bullet. For the value I use `Math.abs` function to make it positive and just display the `realValue` from the object.

It's really bothering me, that as they are just 2 children and with similar value, they should be almost the same size, right?

Thanks!

**Environment (if applicable)**
- amCharts version: 4.10.14
- Related frameworks and their versions: React 16.13.1

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by RSchneider94** [comment]
> Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

hi @martynasma 

yes, please check: https://codesandbox.io/s/friendly-moser-9tnzs

thanks!

**Comment by martynasma** [comment]
Thanks.

OK, so in TreeMap node's value is sum of values of it's children. Based on your demo, "Tecnologia da Informação" has two children that sum up with the following values:

"PROGRAMAS E SERVIÇOS": 18.56
"COMPUTADORES E EQUIPAMENTOS": 1.3

Which makes actual nodes distribute size accordingly. The value for the first one is more than 10 times bigger.

**Comment by RSchneider94** [comment]
> Thanks.
> 
> OK, so in TreeMap node's value is sum of values of it's children. Based on your demo, "Tecnologia da Informação" has two children that sum up with the following values:
> 
> "PROGRAMAS E SERVIÇOS": 18.56
> "COMPUTADORES E EQUIPAMENTOS": 1.3
> 
> Which makes actual nodes distribute size accordingly. The value for the first one is more than 10 times bigger.

Thanks @martynasma, now I see. Just another question: is there someway to make it use the value of the 'root' element itself instead of its children? Like, I'm using here the `sectorVariation` which are respectively:

"PROGRAMAS E SERVIÇOS": 0.99 (with Math.abs to make it work)
"COMPUTADORES E EQUIPAMENTOS": 0.65

Then it will not be that big difference. Right?

Or another way: if I could make a average from the children, it would also display a better result, right? Is it possible with Am?

Thanks!

**Comment by martynasma** [comment]
No, sorry. Sum of values of the children is the only way to size the nodes.

That said, you could use any field in data as a `dataField.value` so you can spoof those values, and use different fields for labels/bullets/tooltips.

**Comment by RSchneider94** [comment]
> No, sorry. Sum of values of the children is the only way to size the nodes.
> 
> That said, you could use any field in data as a `dataField.value` so you can spoof those values, and use different fields for labels/bullets/tooltips.

Thanks for the answer. Yeah, actually I thought about this idea today. 😅
