### ISSUE TITLE
Creating Hover Effect on Bars is not working

### ISSUE THREAD

**Issue by xbaha** [amcharts/amcharts4#3284]
I am trying the latest amcharts to create a hover effect, I have a demo here:

https://jsfiddle.net/byk54qa8/2/

try hovering few times over the bars, it works a few times then the hover effect stop working.

regards

**Comment by martynasma** [comment]
The reason for it working funky is that you set most of the appearance setting on column template (`columns.template`), whereas state is created on its column child (`columns.template.column`).

Try creating the state directly on column template:

```JavaScript
var columnHoverState = columnTemplate.states.create("hover");
columnHoverState.properties.fillOpacity = 0.5;
columnHoverState.properties.cornerRadiusTopLeft = 35;
columnHoverState.properties.cornerRadiusTopRight = 35;
columnHoverState.properties.cursorOverStyle = am4core.MouseCursorStyle.pointer;
```
