### ISSUE TITLE
Static x/yAxis titles when resizing the chart

### ISSUE THREAD

**Issue by Val0590** [amcharts/amcharts4#3285]
I am not able to solve the following problem:.

I have produced a barchart but as I resize it (shrinking it down), the x/y axes are not resizing with it and as a consequence disappear when the chart becomes very small. This behaviour is not observed on the chart title for example (that rescale as we shrink the chart). 

Would you be able to point me to the right solution ?

At start: (axis title visible)
![image](https://user-images.githubusercontent.com/78660914/107127716-ea09ac00-68af-11eb-94c4-e56cbdc061f6.png)

Resized (axis title has disappeared) 
![image](https://user-images.githubusercontent.com/78660914/107127739-0dccf200-68b0-11eb-8bfd-f81d73fc78a4.png)

Thanks

**Comment by martynasma** [comment]
I can't seem to be able to reproduce this. Do you have a live demo perhaps?

**Comment by Val0590** [comment]
Thanks, will put together a codepen in the next week.
