### ISSUE TITLE
Candlestick Chart with numeric/double x-Axis

### ISSUE THREAD

**Issue by Val0590** [amcharts/amcharts4#3287]
I am trying to construct a candlestick chart, but the x-axis represents time in years (double/numeric based), eg. 0.15, 2.5, etc...
Depending on what I display the number of years can be between [0,1000].
As a candlestick chart  does not seem to support ValueAxis as x-axis, I have converted my double-based values in milliseconds,  like so:

```
 candleStickSeries.name = data.seriesName +  '__FuncSpecSnapToSeries';
      data.series.forEach(element => {
        element.x = new Date(element.x * 10);
      });
      candleStickSeries.data = data.series;
      const xAxis = chart.xAxes.values[0] as am4charts.DateAxis; 
      xAxis.dateFormats.setKey('millisecond','SS.S')

```
And I get the following:

      
![image](https://user-images.githubusercontent.com/78660914/107161209-19451980-6993-11eb-83a3-f273fdc40684.png)

Three questions:
1) Is it the right way to go about implementing this type of chart?
2) I would like more vertical gridlines on the x axis (with labels) not just 5.1 and 10,1 - what do I need to do? 
3) Sometimes it prints the label at y=0, and it appears in the format 00:00:00. How can I remediate that?

Important: I use `snapToSeries` to be able to display the tooltip, so its important that this functionality stays.
I have looked at possible solutions here:
https://github.com/amcharts/amcharts4/issues/877
https://github.com/amcharts/amcharts4/issues/898

but it does not work for me.

Thanks

**Comment by martynasma** [comment]
I don't think that using DateAxis is the right way to do it.

How about using ValueAxis and setting fixed width for your series' columns?
