### ISSUE TITLE
ForceDirectedTree: make API call onclick of a node to load children

### ISSUE THREAD

**Issue by gauravmaurya** [amcharts/amcharts4#3289]
Using **ForceDirectedTree** : I am finding difficulty in onclick of a node load the children node by making a api call. i.e. 

I need to make a api call on click of node to load the children nodes. On initial load of the page i cannot load diagram seeing the huge data load. 

data : how i need as per my project requirement
[{
       "name": "abc",
       "value": 50,
       "linkWith": [
         "a",
         "b"
       ]
     },
{
"name": "a",
  "value": 10,
"children": [i wish to load these children via making a api new call]
},
{
"name": "b",
  "value": 10,
"children": [i wish to load this children data via making a api new call]
}
]

Hope i am able to convey what my issue is. I have checked all the tutorials, documentations of amcharts, have googled to find any implemetations as such but no luck so far. Please suggest your inputs on this.

**Comment by martynasma** [comment]
I'm afraid there's no support for incremental data loading for hierarchical chart types like ForceDirectedTree.

You would need to grab the node clicked, load the missing data, push it into original data, and revalidate the whole chart data via `chart.invalidateData()`.

Hope that makes sense.
