### ISSUE TITLE
Chart cursor snaps to line where there is no data

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#329]
In this [pen](https://codepen.io/notacouch/pen/324413e43b9b228c33ab93af893d0b6d/), there is no data for April 27th, yet the chart cursor snaps to it anyway.

![chart cursor snap](https://user-images.githubusercontent.com/2334143/45246801-58a64200-b2d1-11e8-944c-c5062253f2e2.PNG)

Is there any way to prevent it from snapping or have it skip over a date?

**Comment by zeroin** [comment]
In v 4.0.6 we added `snapTooltip` property to DateAxis which is true by default, so it should work like you expect now.
