### ISSUE TITLE
Can @babel/runtime be moved to devDependencies?

### ISSUE THREAD

**Issue by eternalmatt** [amcharts/amcharts4#3290]
**Bug description**
I see this in my browser console:
```
index.js:135 C:\Project\node_modules\@amcharts\amcharts4\.internal\canvg\index.js depends on '@babel/runtime/regenerator'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
Can amcharts avoid using @babel/runtime in its source code?  This is typically not a prod dependency.

**Environment (if applicable)**
@amcharts/amcharts4@4.10.13
Angular 11
Typescript 4

**Comment by Pauan** [comment]
@eternalmatt As its name suggests, `@babel/runtime` contains runtime code, and so it cannot be in `devDependencies`:

https://babeljs.io/docs/en/babel-runtime

The warning is simply telling you that `@babel/runtime` is not using ES6 modules. It is harmless, and so you can ignore it.

You can add `"@babel/runtime"` to your `allowedCommonJsDependencies` which will silence the warning:

https://angular.io/guide/build#configuring-commonjs-dependencies
