### ISSUE TITLE
Export operation took longer than expected. Something might have gone wrong.

### ISSUE THREAD

**Issue by Amit6882** [amcharts/amcharts4#3291]
**Bug description** 
@amcharts @martynasma Please look into this issue

1. **Clicked and Print or export**
![image](https://user-images.githubusercontent.com/12683584/107341258-c11e2c80-6ae4-11eb-9acf-a20724001e31.png)

2. Already added property **timeoutDelay** = 20000;
![image](https://user-images.githubusercontent.com/12683584/107340615-fb3afe80-6ae3-11eb-8aac-394b3ea8d45a.png)

Getting this message while trying to print or export chart from UI:
**Export operation took longer than expected. Something might have gone wrong.**

**Version**
"@amcharts/amcharts4": "^4.10.10",
"@amcharts/amcharts4-geodata": "^4.1.18",
"@angular/animations": "~11.0.9",
"@angular/common": "~11.0.9",
"@angular/compiler": "~11.0.9",
"@angular/core": "~11.0.9",

**Error in console**
Export.js:951 Loading image "blob:http://localhost:4200/815f92df-5915-41e4-946f-f0079fc04426" failed
Error: Loading image "blob:http://localhost:4200/815f92df-5915-41e4-946f-f0079fc04426" failed
    at Image.image.onerror [as __zone_symbol__ON_PROPERTYerror] (http://localhost:4200/vendor.js:177738:31)
    at Image.wrapFn (http://localhost:4200/polyfills.js:10483:43)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:9664:35)
    at Zone.runTask (http://localhost:4200/polyfills.js:9432:51)
    at ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:9745:38)
    at invokeTask (http://localhost:4200/polyfills.js:10886:18)
    at Image.globalZoneAwareCallback (http://localhost:4200/polyfills.js:10912:21)
(anonymous) @ Export.js:951
Log.js:27 Simple export failed, falling back to advanced export
warn @ Log.js:27
zone-evergreen.js:659 Unhandled Promise rejection: This page contains the following errors:error on line 1 at column 24621: invalid character in attribute value
Below is a rendering of the page up to the first error. ; Zone: <root> ; Task: Promise.then ; Value: Error: This page contains the following errors:error on line 1 at column 24621: invalid character in attribute value
Below is a rendering of the page up to the first error.
    at Parser.checkDocument (index.js:2107)
    at Parser.parseFromString (index.js:2098)
    at Function.fromString (index.js:8298)
    at Export.<anonymous> (Export.js:1232)
    at step (tslib.es6.js:102)
    at Object.next (tslib.es6.js:83)
    at fulfilled (tslib.es6.js:73)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857 Error: This page contains the following errors:error on line 1 at column 24621: invalid character in attribute value
Below is a rendering of the page up to the first error.
    at Parser.checkDocument (http://localhost:4200/canvg.js:8169:15)
    at Parser.parseFromString (http://localhost:4200/canvg.js:8160:21)
    at Function.fromString (http://localhost:4200/canvg.js:14360:32)
    at Export.<anonymous> (http://localhost:4200/vendor.js:177259:52)
    at step (http://localhost:4200/vendor.js:209545:23)
    at Object.next (http://localhost:4200/vendor.js:209526:53)
    at fulfilled (http://localhost:4200/vendor.js:209516:58)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:9629:30)
    at Zone.run (http://localhost:4200/polyfills.js:9388:47)
    at http://localhost:4200/polyfills.js:10122:40
api.onUnhandledError @ zone-evergreen.js:659

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Amit6882** [comment]
Hi @martynasma @amcharts 
Working Fiddle: https://jsfiddle.net/AmitDubey/bn56sz9y
I got the root case in code but didn't found the solution, Actually when commenting below code then chart exporting working fine.
**// below code (line: 175 in fiddle) creating issue in chart exporting:**
series.slices.template.tooltipText = "[bold font-size: 20]{category}[\b]\nIndex: {radiusValue.formatNumber('#,###')}\nAudience Overlap: {audience_composition.formatNumber('#.#')}%";

I want working code along with above code.
Please take a look and provide the solution. Thanks

**Comment by martynasma** [comment]
I'm not entirely sure what's going on, but removing a space between `font-size` and `20` helps:

```
[bold font-size:20]
```

**Comment by Amit6882** [comment]
> I'm not entirely sure what's going on, but removing a space between `font-size` and `20` helps:
> 
> ```
> [bold font-size:20]
> ```

Tried your solution but It is not working. Please debug at your end once properly because noting wrong in tooltip code syntax.

**Comment by martynasma** [comment]
As weird as it may seem, it works properly for me without the space.

Can you try this fiddle?
https://jsfiddle.net/L7rqsywa/

**Comment by Amit6882** [comment]
![image](https://user-images.githubusercontent.com/12683584/107753916-c4b0ee00-6d46-11eb-8484-44d3a6763cb6.png)

See in fiddle screenshot when I clicked on print its giving the same error in console

**Comment by martynasma** [comment]
This workaround seems to take care of the weird issue:

```JavaScript
chart.exporting.events.on("exportstarted", function(ev) {
  series.tooltip.disabled = true;
})

chart.exporting.events.on("exportfinished", function(ev) {
  setTimeout(function() {
    series.tooltip.disabled = false;
  }, 100)
})

chart.exporting.validateSprites = series.tooltip;
```

**Comment by Amit6882** [comment]
Okay I'll give it a try

**Comment by Amit6882** [comment]
It is working only for the first click, but on second click onwards behavior is same

**Comment by martynasma** [comment]
OK, so this is actual because of this in your `tooltipText`: `[\b]`.

Replace it with proper style terminator: `[/]`.

**Comment by Amit6882** [comment]
Great, works like a charm!!!
Thanks @martynasma, Really appreciated your effort to find the root causes.
You may close this thread.
