### ISSUE TITLE
Handling data of nearly 2GB (1 Million points).

### ISSUE THREAD

**Issue by Anudeep-Kadavergu** [amcharts/amcharts4#3293]
Amchart version 4.
I have created a Line Chart and trying to load 1 Millions data points by adding different Line series on to that same chart.
When I am creating the line series, the CPU exceeds 95% and memory exceeds 2 GB then the website is not loading. (Memory crash error).
Can you suggest me the efficient way to handle data.

**My use case:**
I have 10 series e.g., A,B,C,D,E,F,G,H,I,J
On page loads I am creating series by giving id to them.
function loadSeries(series_val, color){
            // Create series
            var series = new am4charts.LineSeries(); 
            series.stroke = am4core.color(color);
            series.dataFields.valueY = series_val;
            series.dataFields.dateX = "TimeStamp";
            series.tooltipText = series_val+": "+"{valueY.value}";
            series.tooltip.label.fontSize = 10;
            series.name = series_val;
            series.strokeWidth=2;
            series.tooltip.getFillFromObject = false;
            series.tooltip.background.fill = am4core.color(color);
            series = chart.series.push(series);
            series.id = series_val;
            series.hide();
        }
I have check boxes for 10 series A-J, When checking the boxes I am toggling the particular series on the chart.

Issue:
At the first step itself while loading the series it gives me memory crash error (memory exceeds 2GB )

**Comment by martynasma** [comment]
I don't think amCharts 4 is capable of handling 1M data points on a simple LineSeries :(

Not if it's on a DateAxis with [data grouping](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping) enabled.

**Comment by Anudeep-Kadavergu** [comment]
Yes, The X-Axis is DateAxis and I have enabled the data grouping option with necessary options.
If not simple LineSeries, what will be feasible solution for this?

This is my data grouping code:
      dateAxis.groupData = true;
      dateAxis.groupIntervals.setAll([
                    { timeUnit: "millisecond", count: 100 },
                    { timeUnit: "second", count: 10 },
                    { timeUnit: "minute", count: 10 },
                    { timeUnit: "hour", count: 1 },
                    { timeUnit: "day", count: 1 },
                    { timeUnit: "week", count: 1 },
                    { timeUnit: "month", count: 1 },
                    { timeUnit: "year", count: 1 }
                    ]);

**Comment by martynasma** [comment]
> If not simple LineSeries, what will be feasible solution for this?

At this moment, none, I'm afraid.

We might have some options later this year, but I don't have any particular details.
