### ISSUE TITLE
How to set the position of legend in chart as per wish?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3294]
Hi 
I am using amchart4. While working with charts there are so many series in single chart where i have to display too many legends.
While the legends were occupying the space by default.

here, i have 12 legends over here
`chart.legend.maxHeight = 150;
 chart.legend.scrollable = true;`

![Screenshot from 2021-02-11 11-16-01](https://user-images.githubusercontent.com/71019344/107605925-90600380-6c5a-11eb-9e52-96c1a9ebf032.png)

For above one i just applied scrollable

Can you suggest something where all legends occupy minimum place without scrollable, for a reference i'm attaching the below picture
![Screenshot from 2021-02-11 11-18-57](https://user-images.githubusercontent.com/71019344/107606087-0c5a4b80-6c5b-11eb-8cb7-785d672e5274.png)

Thanks in advance

**Comment by martynasma** [comment]
Looking at the above screenshot it doesn't look like the width would fit any more columns.

You can try lowering `fontSize` on the legend, so the items are smaller.

**Comment by meghanaNanuvala** [comment]
Thank you
