### ISSUE TITLE
Chord diagram tooltip appears for deactivated groups

### ISSUE THREAD

**Issue by inakiapaolaza** [amcharts/amcharts4#3295]
**Bug description**
When moving the cursor over the connections between groups the tooltip appears for all of the possible combinations instead of just showing the connections between the still activated groups. It is difficult to find the desired tooltip between two groups when there are multiple combinations. 

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
I don't think that's the case. Tooltip appears only for the link you are hovering on.

However, if you have a chart that acts otherwise, maybe you can post it on CodePen or jsFiddle?

**Comment by inakiapaolaza** [comment]
> I don't think that's the case. Tooltip appears only for the link you are hovering on.
> 
> However, if you have a chart that acts otherwise, maybe you can post it on CodePen or jsFiddle?

The thing is that the tooltip appears when hovering on non-existing links (for links that you previously deselect).

**Comment by martynasma** [comment]
I don't follow. Do you mean you can hover on a link that goes to a hidden node?

**Comment by inakiapaolaza** [comment]
> I don't follow. Do you mean you can hover on a link that goes to a hidden node?

Yes, and you can also hover on a link between two hidden nodes.

**Comment by martynasma** [comment]
Can you point to a demo that does that? I can't seem to be able to reproduce this behavior.

**Comment by inakiapaolaza** [comment]
This would be an example of what I am trying to explain. Notice that "orange" node is hidden and the tooltip for "apple-orange" appears (example 1). The second image (example 2) shows the same but for two hidden nodes.

Example 1:
![bug](https://user-images.githubusercontent.com/78533382/107660359-74735680-6c88-11eb-9e90-6e75d8ed6d45.jpg)
Example 2:
![bug2](https://user-images.githubusercontent.com/78533382/107660912-0713f580-6c89-11eb-98af-d14f1b997013.png)

**Comment by martynasma** [comment]
Can you post that chart online?

**Comment by inakiapaolaza** [comment]
> Can you post that chart online?

https://app.deepint.net/shared/00000177018125a2-820cc876-3b6bed27-78375ed6/views/0000017791c1b105-0859e755-3f6eee27-61d79964

**Comment by martynasma** [comment]
Um, does this happen in all browsers for you? I can't reproduce it with Chrome on your chart.

**Comment by inakiapaolaza** [comment]
Yes, I have tested with chrome and firefox and happens in both of them. It is more noticeable if you create a demo with much more links.

**Comment by martynasma** [comment]
Not sure what to say. I can't for the life of me reproduce it :/
