### ISSUE TITLE
Is there a way to change Legend's Marker fill color?

### ISSUE THREAD

**Issue by roiassa94** [amcharts/amcharts4#3296]
I am trying to customize the Legend Marker's inside color but I just can't seem to find how.

marker.stroke = am4core.color('#ccc') works great, but when I try marker.fill = am4core.color('#bbb) nothing happens.
It just ignores it and keeps taking the color from the chart's fill color.

I couldn't find any example using marker.fill either so I guess it doesn't exist?

Any solution?

**Comment by martynasma** [comment]
You will need to override the color using adapter:

```JavaScript
marker.adapter.add("fill", function() {
  return am4core.color("#ccc");
});
```

**Comment by roiassa94** [comment]
@martynasma Thank you so much!

**Comment by KayvT** [comment]
@martynasma I am trying to do this dynamically for each marker with a bar Series.. but it keeps telling me that it doesn't exist
![image](https://user-images.githubusercontent.com/40730865/141306637-b7757dec-41be-461a-8b34-907b5dbbb3a3.png)
 
What am I doing wrong?
