### ISSUE TITLE
[Question] Can we have a different theme for a multiseries horizontal bar chart ?

### ISSUE THREAD

**Issue by mahesh-chotrani** [amcharts/amcharts4#3299]
**Question**

We have been using `animated` theme for most of our horizontal bar charts. While going through [this example](https://www.amcharts.com/docs/v4/tutorials/using-patterns-theme/), found that the library has a theme where we can have various `patterns`. For a given chart, I could have the sample working.

Can we have a bar chart with two series, and one of them can have patterns ? For example, in the chart below, the light colored bars (_i.e., arrowed_), need to a apply patterns to only those.

![image](https://user-images.githubusercontent.com/50296623/107738373-8c9cb180-6d2c-11eb-9002-8ff871809303.png)

**Comment by martynasma** [comment]
Probably the easiest way would be to use [color modifiers](https://www.amcharts.com/docs/v4/concepts/colors/#Color_modifiers).

**Comment by mahesh-chotrani** [comment]
Thanks @martynasma . 

Referring example [here](https://www.amcharts.com/docs/v4/concepts/colors/#Patterns_in_a_chart), here is how I could implement patterns for two series in a same chart. 

```
// series 1 rendered in solid colors
series1.columns.template.adapter.add("fill", (fill, target) => {
    return target.dataItem.dataContext.color;
});

// series 2 rendered in line patterns
series2.columns.template.adapter.add("fill", (fill, target) => {
    var pattern = new am4core.LinePattern();
    pattern.width = 10;
    pattern.height = 10;
    pattern.strokeWidth = 1;
    pattern.stroke = target.dataItem.dataContext.color;
    pattern.rotation = 45;
    return pattern;
});
```
