### ISSUE TITLE
Weird zoom behavior on Line Series with gaps

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#330]
In some cases, when there are `LineSeries` with `connect = false` and gaps in data (with `value = null`) and the chart is zoomed, some visual glitches appear on the series line.

Example:
https://codepen.io/team/amcharts/pen/c12d22bf2bbf4f480e6ef9837c2560c0?editors=0010

To reproduce, move left scrollbar grip half way to the right, then back out.

Initial chart look:
![image](https://user-images.githubusercontent.com/1458520/45250462-575e2f00-b33c-11e8-92e9-1195e307ae44.png)

After zoom in and zoom out:
![image](https://user-images.githubusercontent.com/1458520/45250478-870d3700-b33c-11e8-9c69-804c14cd99ff.png)

**Comment by notacouch** [comment]
Another way to reproduce:
- Drag left scrollbar grip so the scrollbar is no longer 100% width
- Drag scrollbar itself all the way to the left, the series will now have an artifact
- Drag right scrollbar grip back and forth, artifact will still be there, fixed in position

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.51](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.51).

## [4.0.0-beta.51] - 2018-09-13

### Changed
- Changed `Label.renderingFrequency` to `2`, for better performance.

### Fixed
- Performance tweaking.
- `DateAxis.baseInterval` was ignored in JSON-based configs.
- `"hoverActive"` state was not always being correctly applied.
- Better handling of cursor zoom and pan when outside chart area.
- Fixed occasional error when formatting dates or numbers.
- Line chart starts new segement only if properties (like `stroke`, `fill`, `strokeDashArray`, etc.) in data have changed. It used to start new segment if properties in data were defined resulting in reduced performance and disabled smoothed lines.
- Labels were not updating their position if their `fontSize` changed.
- `Sprite.nonScalingStroke = true` was ignored if set after `Sprite.strokeWidth`.
- `LineSeries` could leave some garbage lines while zooming.
- `ColumnSeries` could leave some garbage columns while zooming.
- `DateAxis` with one date only in chart data was not rendered properly.
- The chart was not zooming out after data validation.
- Added `ghostLabel` to `Axis` which is an invisible label and it helps to avoid unwanted changes of axis widht/height when the scale changes, e.g. on zoom.
- `zoomToMapObject`, if used with `MapPolygon` and custom `zoomLevel` was not working properly.
- `"hidden"` event of Series was called on initial chart initialization.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
