### ISSUE TITLE
How to list visible Axis labels ?

### ISSUE THREAD

**Issue by fasidOnGit** [amcharts/amcharts4#3300]
Currently I do not know, what values are visible in the axis. If I do `categoryAxis.renderer.labels.values` it has too many labels than what is displayed, and things like `isShowing`, `showOnInit` `hidden` `isHidding` are all kinda `false` So, they are not helpful to me either.

Is there a way that I can get the list of values that are visible in the screen?

**Comment by martynasma** [comment]
You may cycle through the labels and check their position. If it's within 0 and 1 range, it's probably on screen:

```
categoryAxis.renderer.labels.each(function(label) {
  if ((label.dataItem.position >= 0) || (label.dataItem.position <= 0)) {
    // this label is visible
  }
});
```

**Comment by fasidOnGit** [comment]
Thank you are the quick response :heart:  Let me check

**Comment by fasidOnGit** [comment]
btw, update your comment to `label.dataItem.position <= 1`

**Comment by fasidOnGit** [comment]
@martynasma  Well, I still get values that are not visible but in the dom.

**Comment by martynasma** [comment]
You may need to check their `visible` setting, and maybe `label.text` if has any text in it, too.

**Comment by fasidOnGit** [comment]
This is what I see in my screen,
![image](https://user-images.githubusercontent.com/27940795/107763254-53783780-6d54-11eb-8782-e24f8203b7e9.png)




But, the log is 
```
[
  "05:30",
  "23:30",
  "22:30",
  "21:30",
  "20:30",
  "19:30",
  "18:30",
  "17:30",
  "16:30",
  "",
  "14:30",
  "11:30",
  "08:30",
  "05:30",
  "02:30"
]
```

**Comment by martynasma** [comment]
I bet those extra ones will have `position` outside the 0-1 scope.

**Comment by fasidOnGit** [comment]
@martynasma Here you go,
```
[
  {
    "currentText": "05:30",
    "visible": true
  },
  {
    "currentText": "23:30",
    "position": 0,
    "visible": true
  },
  {
    "currentText": "22:30",
    "position": 0.125,
    "visible": true
  },
  {
    "currentText": "21:30",
    "position": 0.25,
    "visible": true
  },
  {
    "currentText": "20:30",
    "position": 0.125,
    "visible": true
  },
  {
    "currentText": "19:30",
    "position": 0.5,
    "visible": true
  },
  {
    "currentText": "18:30",
    "position": 0.625,
    "visible": true
  },
  {
    "currentText": "17:30",
    "position": 0.25,
    "visible": true
  },
  {
    "currentText": "16:30",
    "position": 0.875,
    "visible": true
  },
  {
    "currentText": "",
    "position": 1,
    "visible": true
  },
  {
    "currentText": "14:30",
    "position": 0.375,
    "visible": true
  },
  {
    "currentText": "11:30",
    "position": 0.5,
    "visible": true
  },
  {
    "currentText": "08:30",
    "position": 0.625,
    "visible": true
  },
  {
    "currentText": "05:30",
    "position": 0.75,
    "visible": true
  },
  {
    "currentText": "02:30",
    "position": 0.875,
    "visible": true
  }
]
```

**Comment by martynasma** [comment]
I'm sorry then. I don't have any further suggestions, I'm afraid :(
