### ISSUE TITLE
How to set a dynamic tooltip text while hovering?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3302]
Hi 

I am working with amcharts4, where the tooltip text has to be dynamic which displays the weekly dates by calculating from function.

In amcharts3, i used ballontext function and passed the function which calculates the weekly dates 
`'balloonFunction': funcArray[serialLineIndex]
let funcArray = [this.adjustBalloonTextCurrentDate, this.adjustBalloonTextLastDate] //in function array i'm just passing the functions that required for date calculation`

![Screenshot from 2021-02-12 19-30-14](https://user-images.githubusercontent.com/71019344/107778347-fc7d5d00-6d69-11eb-9ffd-5c1f15ffe0ad.png)
Above picture is for reference

So, that configuartion has to be implemented in amcharts4, Can you help me out  how to pass the date function to tooltiptext.

Thanks in advance.

**Comment by martynasma** [comment]
You'll need to use an adapter:

```
series.adapter.add("tooltipText", function(text, target) {
  console.log(target.dataItem);
  return text;
});
```

**Comment by meghanaNanuvala** [comment]
Can you tell me how to define required function in adapter

**Comment by martynasma** [comment]
> Can you tell me how to define required function in adapter

What do you mean? The adapter IS a function. You can add any code in it and have it return tooltip content. Exactly like with `balloonFunction` in V3.

**Comment by meghanaNanuvala** [comment]
I mean i'm pushing this entire function into balloon function

`adjustBalloonTextHubCurrentDate(graphDataItem, graph) {
        try {
            if (graphDataItem.values && graphDataItem.values.value && graph.title) {
                const chartId = graph.chart.stockChart.div.id;
                // let reportId = alacritiReports.activityChartConfig.reportId;
                let dollar = '';
                let graphvalue = '';
                let dataCategory = '';

                if (graphDataItem.graph.title.indexOf('Value') > -1) {
                    dollar = '$';
                    dataCategory = '[Value]';
                    graphvalue = alacritiReports.formatValue(parseFloat(graphDataItem.values.value).toFixed(2), '');
                } else if (graphDataItem.graph.title.indexOf('Volume') > -1) {
                    dataCategory = '[Volume]';
                    graphvalue = alacritiReports.formatValue(parseInt(graphDataItem.values.value, 10), false);
                } else {
                    graphvalue = alacritiReports.formatValue(parseInt(graphDataItem.values.value, 10), false);
                }
                const title = graphDataItem.graph.title.substr(0, graphDataItem.graph.title.indexOf('['));
                const balloonHTML = '<div style=\'margin:5px; font-size:14px;\'><span style=\'font-size:14px;\'>' +
                    title + '[' +
                    alacritiReports.formatDateForMultiXesActivityChartBalloonTextCurrentDate(graphDataItem.category,
                        graph.valueField, graph.categoryAxis.minPeriod) + ']' +
                    ': <span style="font-weight: bold">' + dollar + graphvalue + '</span></span></div>';
                return balloonHTML;

            }
        } catch (e) {
            console.log('error in multiaxes-activity chart:adjustBalloonTextHubCurrentDate: ', e);
            return '';
        }
    }
`

the above logic is for getting dates by calculating on what point we are hovering and how could i reuse this logic in adapter

**Comment by martynasma** [comment]
Naturally, you will need to adjust this code for V4.
