### ISSUE TITLE
[Question] Is there a way to bubble an event (e.g., `hit`) from elements of 'MapImageSeries' to the polygon series they are rendered with ?

### ISSUE THREAD

**Issue by mahesh-chotrani** [amcharts/amcharts4#3303]
**Question**

By referring to the example here - https://www.amcharts.com/demos/map-image-drill-down/ , have been successfully able to render dynamic `MapImageSeries` with circles and labels. 

We do have polygon series subscribing `hit` event as below -
```
countryPolygon.events.on("hit", function(ev) {
   . . . 
   // get polygon id
   // . . . ev.target.dataItem.dataContext.id
   // custom logic per polygon
});
```

But, the circle and labels do not respond to the hit event subscribed above for `countryPolygon` series. This seems to be as expected, because these elements have a `z-index` greater than map polygon.

Is there a way - 
- to bubble the event from `MapImageSeries` element to the underlying polygon ?
- to bind the hit event of the circle and label (_created as `MapImageSeries`_) to the underlying polygon ?

Reason being, for an end users, the behaviour becomes -
- if they click circle or label, nothing happens
- if they click on any other uncovered polygon area, click works.

**Comment by martynasma** [comment]
There's no way to make "hit" event bubble like that, I'm afraid.

If there's logical connection in data, e.g. like which circle corresponds to which country, you can take care of the country click event in image's handler, e.g.:

```JavaScript
imageTemplate.events.on("hit", function(ev) {
  // do whatever you need to do with image click
  // ...

  // get corresponding polygon id from data context
  var polygonId = ev.target.dataItem.dataContext.polygonId;
  var polygon = polygonSeries.getPolygonById(polygonId);
  if (polygon) {
    // do something with polygon
    // ...
    // or invoke polygons hit event
    polygon.dispatchImmediately("hit");
  }
});
```

Another option is to make those images completely unresponsive, so hit and other events comes through from the underlying polygon:

```JavaScript
imageTemplate.interactionsEnabled = false;
```

**Comment by mahesh-chotrani** [comment]
Thanks @martynasma ! For now, disabling interactions did the work. 

I will also be working on with the more generic solution as you have shown above, as we do have each circle corresponding to a polygon area.
