### ISSUE TITLE
Second Date Axis on the top of the chart

### ISSUE THREAD

**Issue by Nachtgesicht** [amcharts/amcharts4#3304]
How can I add a **second** Date Axis on the top of the chart?

Or how can I add a range.label.text above or on the top of the chart?

**Comment by martynasma** [comment]
This may help:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Alignment_within_plot_area

**Comment by Nachtgesicht** [comment]
Thank's thats a solution for my second question. 👍
Is there a solution for my first question?

**Comment by martynasma** [comment]
I didn't think there needs to be :)

You just add additional DateAxis, assign a series to it, and use `renderer.opposite = true`.

Assigning series is necessary, if you want the DateAxis to have scale.

**Comment by Nachtgesicht** [comment]
Doesn't work. No additional DateAxis is build:
![image](https://user-images.githubusercontent.com/21988873/108046270-b6174f00-7044-11eb-92e1-432931396020.png)

**Comment by martynasma** [comment]
Because there's no series attached to it, so it does not have scale.

Or you can sync them via events and `min`/`max`:

```JavaScript
var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
dateAxis.renderer.grid.template.location = 0;
dateAxis.renderer.minGridDistance = 30;

var dateAxis2 = chart.xAxes.push(new am4charts.DateAxis());
dateAxis2.renderer.grid.template.location = 0;
dateAxis2.renderer.minGridDistance = 30;
dateAxis2.renderer.opposite = true;
dateAxis2.strictMinMax = true;

dateAxis2.events.on("datavalidated", function() {
  dateAxis2.min = dateAxis.min;
  dateAxis2.max = dateAxis.max;
})
```

https://codepen.io/team/amcharts/pen/10fd0424337a135ce3ae06cb94c29e08?editors=0010

**Comment by Nachtgesicht** [comment]
Thanks a lot, that helps! 👍
