### ISSUE TITLE
how to style the chart's container borders

### ISSUE THREAD

**Issue by franjorub** [amcharts/amcharts4#3305]
**Question**

Hi, I'm trying to style the borders of the charts themselves, (not only the axis lines but I also want to style the top and right border too) I tried using the chart.className, applying color to the grid.template but without results

Amchart version: latest
framework: React

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
If you want to style the border of the plot container you can do so:

```JavaScript
chart.plotContainer.background.strokeWidth = 1;
chart.plotContainer.background.strokeOpacity = 1;
chart.plotContainer.background.stroke = am4core.color("#f00");
```

**Comment by franjorub** [comment]
@martynasma  thank you that worked, but I have an issue, how can I hide overflowed values in the Y axis ? 
![image](https://user-images.githubusercontent.com/24401350/108587130-35986d00-7328-11eb-9449-598e56797dbf.png)

**Comment by martynasma** [comment]
You might want to [hide end labels](https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Start_and_end_labels).

**Comment by franjorub** [comment]
thanks a lot @martynasma !
