### ISSUE TITLE
adjustLabelPrecision=false not working for heat legend

### ISSUE THREAD

**Issue by fasidOnGit** [amcharts/amcharts4#3306]
Hello, I am currently experimenting with Heatmap Legend, As per the docs, we should be able to disable auto-formating of value axis labels by setting `adjustLabelPrecision=false` [Adjusting label precision](https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Adjusting_label_precision)

But it does not seem to take effect, I still see the fractions being rounded with zeros like `#.00`. 
https://codepen.io/fasid/pen/XWjGqdQ

Thanks in advance :)

**Comment by martynasma** [comment]
This line is overriding number format:

```
        chart.numberFormatter.numberFormat = {
          style: 'decimal',
          minimumFractionDigits: 2,
          maximumFractionDigits: 2
        };
```

When you use Intl number format, all other formatting options are ignored, hence it ignoring `adjustLabelPrecision`.

I suggest using string base number format:

```
chart.numberFormatter.numberFormat = "#.##";
```

You also don't need the `adjustLabelPrecision` line at all.

**Comment by fasidOnGit** [comment]
@martynasma When I change it to `chart.numberFormatter.numberFormat = '#.##'`, I see the value axis in the heat legend is rounding to a while number. I also tried setting it at the `heatLegend.valueAxis.numberFormatter.numberFormat = '#.##'.  and `adjustLabelPrecision` is not helping either.

Please check the Codepen again to see it.

**Comment by martynasma** [comment]
OK, so what would you like those numbers to look like in heat legend?

**Comment by fasidOnGit** [comment]
> This line is overriding number format:
        chart.numberFormatter.numberFormat = {
          style: 'decimal',
          minimumFractionDigits: 2,
          maximumFractionDigits: 2
        };
> When you use Intl number format, all other formatting options are ignored, hence it ignoring adjustLabelPrecision.

Sorry if I am missing something obvious here, IIUC, the numberFormat specified in `Intl` is not working as expected for value axis in heat legend while it is formatted as expected in series tooltips.
Also, I find `Intl` way specifying the formatting options is making it easy to switch locale so I kinda a need it.

**Comment by fasidOnGit** [comment]
> OK, so what would you like those numbers to look like in heat legend?

The same way how it is formatted in the column tooltip. always 2 fractions.

**Comment by martynasma** [comment]
Um, so that's how it was in the first place in your own CodePen?

In that case you can go back to using Intl number format, or use the following:

```
chart.numberFormatter.numberFormat = '#.00';
heatLegend.valueAxis.adjustLabelPrecision = false;
```

**Comment by fasidOnGit** [comment]
@martynasma Maybe I explained it poorly. My end goal here is that, If I hover over a grid (column) in the series and the column's tooltip show a fraction value let's say `20.32` as value I want the same value to be shown in heatlegend's value axis tooltip. but what I see is `20.00` (always rounded with `.00`). I have clearly specified the formatting options in `Intl` way at the `chart.numberFormatter.numberFormat` level which is actually been inherited to both column and heatLegend's value axis numberFormatters but still, Surprisingly, heatLegend's value axis don't format as expected.

**Comment by fasidOnGit** [comment]
@martynasma Do you think this should labeled as a bug?

**Comment by martynasma** [comment]
OK, so I didn't realize it was about tooltips, not the labels.

For that you should use `extraTooltipPrecision`:

https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/#Number_precision_on_ValueAxis

**Comment by fasidOnGit** [comment]
@martynasma Yep, `extraTooltipPrecision` worked for the tooltip and this is pretty much what I wanted. Thanks alot.

But on a side note, I still didn't get the Heatmap valueAxis labels get rounded with `.00` no matter how I set the number formatting options. even after setting `adjustLabelPrecision = false`.

**Comment by martynasma** [comment]
Well, you still have this in your code:

```
heatLegend.valueAxis.numberFormatter.numberFormat = {
  style: 'decimal',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
}
```

As I explained earlier, when you use Intl number format, all other number format-related settings are ignored.

**Comment by fasidOnGit** [comment]
@martynasma Exactly, why not this (`Intl`) format take effect? the formatting option is quite obvious that I need two fraction digits. So, if the `Intl` is overriding the other format then Amcharts shouldn't try to adjust label precision like it is saying below in the docs.

> This is why ValueAxis will try to automatically format all numbers using the same number of decimals as the most granular label currently displayed, e.g.: 1.0, 1.5, 2.0.

> It is the default behavior since version 4.9.14.

> If you'd like to disable such auto-formatting, you can do so by setting axis' adjustLabelPrecision to false:

So, from a user point of view I am struck, the given `Intl` format won't take effect plus if I try to disable the auto-formatting with `adjustLabelPrecision` that wouldn't work either because I am using `Intl` I see there could be two ways out of it if Amchart's is willing,

1. apply the given `Intl` formatting setting on the heat legend labels and add the point to the docs that Intl will override `adjustLabelPreceision`
2. allow `adjustLabelPreceision` to take effect.

**Comment by martynasma** [comment]
I don't understand what you are suggesting.

It's really simple:

1) You either format numbers using Intl format...

2) ... or you format numbers using other options, like string-based `numberFormat`, `adjustlabelPrecision`, etc.

Please also note that `numberFormatter` is inheritable. So if you access `chart.numberFormatter` and `axis.numberFormatter`, it'll be the same object, so setting `numberFormat` on either will set it for the whole chart.

If you need separate format settings for separate objects, you need to create separate `NumberFormatter` object:

```JavaScript
axis.numberFormatter = new am4core.NumberFormatter();
axis.numberFormatter.numberFormat = "....."; <-- this will be used for this particular axis only
```

Hope it makes sense.

**Comment by fasidOnGit** [comment]
@martynasma Alright I understand. I tried the following
```
chart.numberFormatter.numberFormat = '#.###';
heatLegend.valueAxis.adjustLabelPrecision = false;
```

but I see that heatLegend axis labels are rounded to whole numbers, I did remove `Intl` formating here. Do you think it works as expected here?

**Comment by martynasma** [comment]
Axis labels are not rounded to whole numbers, they are **placed at precisely whole numbers** :)

**Comment by fasidOnGit** [comment]
Thaanks for all the support :)
