### ISSUE TITLE
Changing the bar height value for the XY Chart

### ISSUE THREAD

**Issue by bbg** [amcharts/amcharts4#3308]
**Question**

I have a XY chart that you will see in the Codepen example.

The thickness of the horizontal bars in this graphic is too much. I want to reduce the thickness and center it vertically.

Is it possible to do this?. In the documentation, I could not find the information I wanted.

Codepen: https://codepen.io/batuhangoksu/pen/dyOvaQL
amCharts version: am4
Browsers: All browsers

Thank you

**Comment by martynasma** [comment]
This tutorial explains how to do so:
https://www.amcharts.com/docs/v4/tutorials/managing-width-and-spacing-of-column-series/

**Comment by bbg** [comment]
Thank You @martynasma 

Code for vertical;

```javascript
series.columns.template.width = am4core.percent(15);
```

Code for horizontal

```javascript
series.columns.template.height = am4core.percent(15);
```
