### ISSUE TITLE
ScrollbarX Issue: Graph data is getting disappear in case of right to left slide 

### ISSUE THREAD

**Issue by Amit6882** [amcharts/amcharts4#3309]
**Bug description**
@amcharts @martynasma 
**Working Fiddle:** https://jsfiddle.net/AmitDubey/4ur1790a/
Graph data is getting disappear in case of right to left slide while left to right slide is working fine
**ScrollbarX Right to Left not working while Left to Right is working**

![image](https://user-images.githubusercontent.com/12683584/108062953-87b76500-7080-11eb-86ea-5862a6c019f2.png)
![image](https://user-images.githubusercontent.com/12683584/108063195-dc5ae000-7080-11eb-9913-78592e6c9592.png)

Please look into this issue.

**Environment (if applicable)**
"dependencies": {
    "@amcharts/amcharts4": "^4.10.10",
    "@amcharts/amcharts4-geodata": "^4.1.18",
    "@angular/animations": "~11.0.9",
    "@angular/common": "~11.0.9",
    "@angular/compiler": "~11.0.9",
    "@angular/core": "~11.0.9",
    }

Browser: **Google Chrome**
Version 88.0.4324.150 (Official Build) (64-bit)

**Additional context**

**Comment by martynasma** [comment]
Solution here: https://github.com/amcharts/amcharts4/issues/3261#issuecomment-770656160

**Comment by Amit6882** [comment]
Great it works, Thanks @martynasma
