### ISSUE TITLE
How to fix the "piece of floating Russia" in custom maps?

### ISSUE THREAD

**Issue by ggggabri** [amcharts/amcharts4#3310]
**Question**

I am trying to make a custom EMEA map (Europe, Middle East, Africa). Using QGIS I took your worldHigh json and kept only the countries I needed. The problem that I'm having is that amCharts cuts off a small piece of Russia and puts it off to the left.

Result on mapshaper: [link](https://i.ibb.co/n0KQwTZ/Cattura.png)
amCharts map: [link](https://i.ibb.co/m6qk0cq/Cattura2.png)

Is there a way to fix it? I tried all the available projections

**Environment (if applicable)**

amCharts version 4.10.13, latest Firefox/Chrome

**Comment by xorspark** [comment]
You can use [`deltaLatitude`](https://www.amcharts.com/docs/v4/reference/mapchart/#deltaLatitude_property) to shift the map's default center. We have a Pacific-centered map on our [demos page](https://www.amcharts.com/demos/pacific-centered-map/) that illustrates this as well as [this continent demo](https://codepen.io/team/amcharts/pen/78510503a1f14ee0ef1f8579c1770247?editors=1010) with some continents hidden similar to your setup.
