### ISSUE TITLE
Render two times amCharts

### ISSUE THREAD

**Issue by SagarDesai111** [amcharts/amcharts4#3311]
I'm using React with typescript.
 "react": "^17.0.1",
 "typescript": "^4.1.2",
 "@amcharts/amcharts4": "^4.10.15",
 
 I'm used one Pie Chart demo from amCharts but the issue was is chart is rendered two times. I don't know what the issue. I created a new react-app and just add the demo from amCharts.

Here my code:
`import "./App.css";
import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";

function App() {
  let chart = am4core.create("chartdiv", am4charts.PieChart);

  let series = chart.series.push(new am4charts.PieSeries());
  series.dataFields.value = "litres";
  series.dataFields.category = "country";

  chart.data = [
    {
      country: "Lithuania",
      litres: 501.9,
    },
    {
      country: "Czech Republic",
      litres: 301.9,
    },
    {
      country: "Ireland",
      litres: 201.1,
    },
    {
      country: "Germany",
      litres: 165.8,
    },
    {
      country: "Australia",
      litres: 139.9,
    },
    {
      country: "Austria",
      litres: 128.3,
    },
    {
      country: "UK",
      litres: 99,
    },
    {
      country: "Belgium",
      litres: 60,
    },
    {
      country: "The Netherlands",
      litres: 50,
    },
  ];

  chart.legend = new am4charts.Legend();

  return <div id="chartdiv"></div>;
}

export default App;
`
App Preview: https://prnt.sc/ztmogd

What the wrong with this code?

**Comment by martynasma** [comment]
Please refer to our [React guide](https://www.amcharts.com/docs/v4/getting-started/integrations/using-react/) for correct usage.

**Comment by SagarDesai111** [comment]
Okay, @martynasma I will check.
