### ISSUE TITLE
Relative pre-zooming with external data doesn't work

### ISSUE THREAD

**Issue by Vaidot** [amcharts/amcharts4#3312]
**Bug description**
Relative pre-zooming described in https://www.amcharts.com/docs/v4/tutorials/pre-zooming-an-axis/#Relative_pre_zooming will not work, if you try set data from external source: `chart.dataSource.url = "/data/url";`

**Additional context**
As a workaround you can put code
```
dateAxis.start = 0.8;
dateAxis.end = 1;
```
to event, like "datavalidated" or "parseended", but this worked before, without needing to do that.

From what I seen, it seems, that happened because of change https://github.com/amcharts/amcharts4/commit/c269869b59a0242e6d22cea86cd688a940187a34#diff-938a4b8d430b115a3e602cc356d7dc85dfabfe050356a906eb6558cef68c849a.
Chart calls ValueAxis.getMinMax() at some point before getting data, and that function resets "start" and "end" to default values, if there is no data.

**Comment by martynasma** [comment]
Have you tried setting `dateAxis.keepSelection = true`?

**Comment by Vaidot** [comment]
Of course I did. That's why I reported the problem.

**Comment by martynasma** [comment]
Using datavalidated event works fine for me:

https://codepen.io/team/amcharts/pen/9c36a87ff269d45b5833463591cfe1d8

**Comment by Vaidot** [comment]
That is why i wrote:
> As a workaround you can put code ... to event, like "datavalidated" or "parseended", but this worked before, without needing to do that.

Because in the past it worked without needing to add any code to an event, I assumed that it may be a bug. But if that is how it should be done, then that is fine, you can close the issue.

**Comment by martynasma** [comment]
Ah, ok. I thought you meant it wasn't working even with the event.

It's not a bug but byproduct of changes we made. It makes sense that it would not work without event because initially axis does not have any scale at all.
