### ISSUE TITLE
Multi yAxes with column series leads to columns in each chart being alternate

### ISSUE THREAD

**Issue by hauhuynh1208** [amcharts/amcharts4#3314]
**Question**

I am trying with multiple yAxes. I also set up 2 column series, but the columns in each chart is alternate

here is CodePen: https://codepen.io/hauhuynh1208/pen/ExNXPjq?editors=0010

I would like to those columns in top and bottom chart will be in straight as image below

![image](https://user-images.githubusercontent.com/31885286/108323343-24047780-71f9-11eb-89ed-614d83f3531d.png)

**Comment by martynasma** [comment]
Well, the series are being clustered by default. Just disable clustering to fix:

```
series.clustered = false;
...
series2.clustered = false;
```

**Comment by hauhuynh1208** [comment]
It works.
Thank you so much @martynasma
