### ISSUE TITLE
How to add in label.text double spaces(&nbsp) at end?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3315]
How to add in label.text &amp;nbsp; at the end?
label.text = someText + '&amp;nbsp;';

--- explanation why i need that:
So, i add to chart container some dynamic text:
let label  = Chart.main.container.**topContainer**.createChild(am4core.Label)
And for some purposes make them selectable=true:
label.**selectable = true**;
And there one very inconvenient thing, when i select text - it's very-very hard to select last char, because  you need end selecting text exactly on end of the char, because after that on next pixel - label is end and selection is fully reset, and you need select text again and very accurately.
So, i decide to add at the end some space chatacters... label.text = someText+'    '; 
But, i think text is trim and there no additional spaces. Ok, let add some &amp;nbsp; ... label.text = someText+'&amp;nbsp;&amp;nbsp;';
And what we see: &amp;nbsp; is print exactly like it write.

**Comment by martynasma** [comment]
`&nbsp;` is an HTML entity and will not work in SVG text.

You can use a non-breaking space Unicode character though:
https://en.wikipedia.org/wiki/Non-breaking_space

**Comment by russeljo** [comment]
I try this
Label.adapter.add("text", function(text, target, key) {
        return ".     " + text + "     .";
});
Double spaces is trimmed, as result ". text ."
