### ISSUE TITLE
amCharts Branding does not goes away!

### ISSUE THREAD

**Issue by Abhi-ak** [amcharts/amcharts4#3316]
Hi,
I have purchased amCharts for my single web page application and I have added the license key in the code base as well, But the amCharts branding is still visible. Can someone point out a fix for this. Is my money wasted?

**Comment by martynasma** [comment]
Sorry for the inconvenience.

Please email us at contact@amcharts.com to discuss all license-related topics. GitHub is for tracking technical issues.
