### ISSUE TITLE
Link externo através do data

### ISSUE THREAD

**Issue by Relison** [amcharts/amcharts4#3317]
Estou procurando, mas não achei nada relevante a essa questão, como posso passar uma url para ser chamada no clique.
https://www.amcharts.com/demos/force-directed-tree/
{
    "name": "Título",
    "value": 1,
	"url": "https://github.com/",
    "path": workstation
  }

Obrigado 

**Question**

**Environment (if applicable)**

**Additional context**

**Comment by xorspark** [comment]
You can set a `propertyField` on the node's `url` property to match up with your data.

```
series.nodes.template.propertyFields.url = "url";
series.nodes.template.urlTarget = "_blank"; // open in new window
// optional: prevent node from collapsing on click
series.nodes.template.togglable = false;
```

[Codepen](https://codepen.io/team/amcharts/pen/128dc74524985d03e98b6df7d6e0e802?editors=0010)

Documentation:
https://www.amcharts.com/docs/v4/concepts/data/#Property_fields
https://www.amcharts.com/docs/v4/reference/forcedirectednode/#url_property
https://www.amcharts.com/docs/v4/reference/forcedirectednode/#urlTarget_property
```

**Comment by Relison** [comment]
Thank you very much :)

________________________________
De: Anthony P <notifications@github.com>
Enviado: sexta-feira, 19 de fevereiro de 2021 23:38
Para: amcharts/amcharts4 <amcharts4@noreply.github.com>
Cc: Relison <relison007@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [amcharts/amcharts4] Link externo através do data (#3317)


You can set a propertyField on the node's url property to match up with your data.

series.nodes.template.propertyFields.url = "url";
series.nodes.template.urlTarget = "_blank"; // open in new window
// optional: prevent node from collapsing on click
series.nodes.template.togglable = false;


Codepen<https://codepen.io/team/amcharts/pen/128dc74524985d03e98b6df7d6e0e802?editors=0010>

Documentation:
https://www.amcharts.com/docs/v4/concepts/data/#Property_fields
https://www.amcharts.com/docs/v4/reference/forcedirectednode/#url_property
https://www.amcharts.com/docs/v4/reference/forcedirectednode/#urlTarget_property
