### ISSUE TITLE
Pie Chart clipping labels

### ISSUE THREAD

**Issue by christopherjbaker** [amcharts/amcharts4#332]
I have a fairly simple pie chart (in fact, my backend is having issues, so there is only 1 point of data at the moment), and the label is half off the screen. I have this same problem with others that are not 2 layers, and those with more slices, it is not relegated to this specific chart.

![image](https://user-images.githubusercontent.com/980338/45257619-7f37ac00-b3a9-11e8-87b4-3f7dc3f15594.png)

version: `@amcharts/amcharts4@4.0.0-beta.49`

**Comment by martynasma** [comment]
While this can be fixed by adding some `paddingTop` and `paddingBottom` to your chart, I agree that all labels should fit using default settings.

We'll see what we can do!

**Comment by martynasma** [comment]
We can't seem to be able to reproduce this anymore.

If you can, can you please share your chart code so that we can test?

**Comment by martynasma** [comment]
Here's one that I'm testing on:
https://codepen.io/team/amcharts/pen/cca8646c6d86ec70180c14f423661caa?editors=0010
