### ISSUE TITLE
Image Series Template hover can't get back to normal for maps

### ISSUE THREAD

**Issue by litiangui555** [amcharts/amcharts4#3320]
**Bug description**
Image Series Template hover can't get back to normal for maps

![image](https://user-images.githubusercontent.com/50727361/108654620-06d6ee00-7504-11eb-9eff-784247f72751.png)

For vanilla JavaScript examples use:
https://codepen.io/litiangui/pen/GRNMrOa

**Environment (if applicable)**
Chromium70

**Additional context**

**Comment by martynasma** [comment]
You may need to set default values on settings you are overriding with hover state, so that element knows what values to get back to once hover is over. E.g.:

```JavaScript
imageSeriesTemplate.stroke = am4core.color("#fff");
imageSeriesTemplate.strokeWidth = 0;
```

**Comment by litiangui555** [comment]
> You may need to set default values on settings you are overriding with hover state, so that element knows what values to get back to once hover is over. E.g.:
> 
> ```js
> imageSeriesTemplate.stroke = am4core.color("#fff");
> imageSeriesTemplate.strokeWidth = 0;
> ```

thanks

**Comment by litiangui555** [comment]
> You may need to set default values on settings you are overriding with hover state, so that element knows what values to get back to once hover is over. E.g.:
> 
> ```js
> imageSeriesTemplate.stroke = am4core.color("#fff");
> imageSeriesTemplate.strokeWidth = 0;
> ```

by the way,How do I control the marker hover manually.
for example,
I click one button, the marker shows hover, click another one, disable hover, thanks.

**Comment by martynasma** [comment]
You can set its `isHover` property:

```JavaScript
imageSeries.mapImages.getIndex(5).isHover = true;
```

**Comment by litiangui555** [comment]
> You can set its `isHover` property:
> 
> ```js
> imageSeries.mapImages.getIndex(5).isHover = true;
> ```

It's ok, thanks.
![image](https://user-images.githubusercontent.com/50727361/108956000-00827680-76aa-11eb-8250-6d2402303b50.png)
How to keep the font color unchanged.

**Comment by martynasma** [comment]
Set `strokeWidth = 0` on the label directly.

```JavaScript
label.strokeWidth = 0;
```

**Comment by litiangui555** [comment]
> Set `strokeWidth = 0` on the label directly.
> 
> ```js
> label.strokeWidth = 0;
> ```

thanks very much!

**Comment by litiangui555** [comment]
the hover size can zoom?
like css "transform:scale()"

**Comment by martynasma** [comment]
Yes. You can use `scale` property for that.
