### ISSUE TITLE
Is there any way to increase the number of different values generating by the animate function of a Slider element?

### ISSUE THREAD

**Issue by JacquesChiracSC2** [amcharts/amcharts4#3327]
Hi,

I'm currently struggling with the animate() function of a Slider element.
Basically I use the slider to generate a key with this format '0.02'. Then, I use this key to select a data set in my object.

This is the parameters I use to animate the slider : 

`.animate({ property: "start", from: 0, to: 1 }, 270000, am4core.ease.linear)`

The behaviours of this animation seems to only generate value between 0 and 1 for "start" even with different value in "from" and "to" keys (?).

If i change the duration to something a bit extreme, like 270000000, and log the value of start property I can observe that the animate() function only generate value from 0 to 1 with a maximal step of  **0.0001** and set a delay intervall between 2 iterations when the silmulation duration is too long.
Whereas the Slider itself seems to produce a way bigger number of different value (precission of 10^-8 or more)

So only 10.000 differents values can be generate by the animation(?), and I need near 30.000 differents value to display all my frame correctly.

**Is there any way to increase the number of different values generating by the animate function of a Slider component ?**

Feel free to ask for more informations if I'm not clear,
BR,
NH.

**Comment by martynasma** [comment]
I don't think animation caps precision in any way. It's limited by the speed of the computer and how many frames it can produce. So the incremental value is calculated based on frame-to-frame progress based on time difference.

I don't think there's a way to change that.

**Comment by JacquesChiracSC2** [comment]
> 
> 
> I don't think animation caps precision in any way. It's limited by the speed of the computer and how many frames it can produce. So the incremental value is calculated based on frame-to-frame progress based on time difference.
> 
> I don't think there's a way to change that.

Thanks for your answer, maybe you are talking about the SYSTEM "beat of heart" kind function but it way above my understanding to modify. I will content myself with 10.000 frame.
