### ISSUE TITLE
Support Pad escaping

### ISSUE THREAD

**Issue by cam-m** [amcharts/amcharts4#3328]
I want to be able to format multiple numbers in a tooltip's value part to give the appearance of them being in fixed width columns.

E.g. 

```   
Draft:     9   1.0%
Active:   10  11.0%
Closed:  999  99.0%
```

Are there any ways to support this?

I realise pad escaping is not supported but can I vote for adding it if there's no workaround?

Thanks!

Cam

**Comment by martynasma** [comment]
There's no way to arrange text into columns, I'm afraid.

I suppose the only workaround is to use HTML with tables or CSS for arranging text into columns.

**Comment by cam-m** [comment]
Thanks for quick response @martynasma, I figured as much. 

Is it a definite no to add support for pad escaping?

Cheers!

C

**Comment by martynasma** [comment]
I don't think so. Does SVG text even support tabs?

**Comment by cam-m** [comment]
Hmm I retract my question - I wouldn't want to implement that either :)

Thanks anyway!

**Comment by cam-m** [comment]
Question answered
