### ISSUE TITLE
Legend Items Grouping

### ISSUE THREAD

**Issue by x1mrdonut1x** [amcharts/amcharts4#3329]
**Question**
I'm trying to display legend items as compact as possible. By default, legend items are aligned in a grid:
![image](https://user-images.githubusercontent.com/15061380/109166075-59770b00-778d-11eb-8634-7875731a62dd.png).  
</br>
What I would like to see is something like this:
![image](https://user-images.githubusercontent.com/15061380/109166507-d4d8bc80-778d-11eb-9027-f536ca8c1301.png)
where all items are next to each other (like float)

**Environment (if applicable)**

AmCharts 4

**Comment by martynasma** [comment]
Try setting this:

```JavaScript
chart.legend.layout = "horizontal";
```

**Comment by x1mrdonut1x** [comment]
That unfortunately doesn't work :( 

It crops the Legend wherever the container stops.

Only option I see is to create a Legend container for each item separately, but maybe there's an easier way?

**Comment by martynasma** [comment]
> Only option I see is to create a Legend container for each item separately, but maybe there's an easier way?

No, I'm afraid :(

**Comment by x1mrdonut1x** [comment]
@martynasma Do you know how I can do that? Assign an element to each legend item separately?

**Comment by martynasma** [comment]
There's no way to arrange elements in a container like that. Sorry.
