### ISSUE TITLE
Series labels overlapping sometimes

### ISSUE THREAD

**Issue by christopherjbaker** [amcharts/amcharts4#333]
This problem was alleviated some by updating to `@amcharts/amcharts4@4.0.0-beta.49` but still exists. I can deal with the category label overlapping the series labels, but the jumble of series labels just wont do. The logic to separate them clearly exists.

If the actual source were on here, I would attempt a fix.

![image](https://user-images.githubusercontent.com/980338/45257636-de95bc00-b3a9-11e8-8335-1156efa87d72.png)
![image](https://user-images.githubusercontent.com/980338/45257639-e35a7000-b3a9-11e8-91de-2d049e9dabd7.png)

**Comment by martynasma** [comment]
@christopherjbaker Do you have a codepen which we can test for the overlapping issue?

**Comment by martynasma** [comment]
Looks like a duplicate of #266.

**Comment by christopherjbaker** [comment]
Yes it does.
