### ISSUE TITLE
Problem with synchronisation of two Gantt chart with different date axis data.

### ISSUE THREAD

**Issue by amitstar12** [amcharts/amcharts4#3331]
**Question**

We have created two date axis Gantt chart and tried to synchronously scroll both the chart.
But both Gantt chart doesn’t have same data.
Example: One Gantt chart has some data which starts with 5-Mar-2021 and the second Gantt chart has some data which starts with 22-Feb-2021. 
Now I want to show the Gantt chart with the same date axis dates. 

But currently, It is showing chart different date axis dates.

Can we add some dates to the date axis even if the data doesn't have those dates?

<img width="1771" alt="Screenshot 2021-02-26 at 2 47 41 PM" src="https://user-images.githubusercontent.com/20845866/109290144-3b70df80-784d-11eb-8a49-60c076b74ed7.png">

**Comment by martynasma** [comment]
You can set DateAxis' `min` and `max` to the same value, e.g.:

```JavaScript
dateAxis1.min = new Date(2020, 0, 1).getTime();
dateAxis1.max = new Date(2020, 5, 1).getTime();

dateAxis2.min = new Date(2020, 0, 1).getTime();
dateAxis2.max = new Date(2020, 5, 1).getTime();
```

**Comment by amitstar12** [comment]
Thanks for the quick reply.

I will check this solution and let you know.

**Comment by amitstar12** [comment]
Thank you!

Now It is working fine after Implementing your suggestion.
