### ISSUE TITLE
Column Series Legend Label not Truncate

### ISSUE THREAD

**Issue by XGuGu** [amcharts/amcharts4#3333]
I am trying to set maxWidth for the legend in a Stacked Column Chart.

I am doing 
chart.legend.labels.template.maxWidth = 50;
chart.legend.labels.template.truncate = true;

But it was not working. Am I missing something ?

**Example**
Please check this example:
https://codepen.io/xiaojingjing/pen/xxRWJeE

**Comment by martynasma** [comment]
This is because legend automatically overwrites `maxWidth` of its labels. The only workaround is to use an adapter:

```JavaScript
chart.legend.labels.template.adapter.add("maxWidth", function() {
  return 50;
})
```

**Comment by XGuGu** [comment]
Thanks so much! That fixed my problem.
