### ISSUE TITLE
How can I remove value of the series when it is disabled in single tooltip box

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3334]
Hi 
I'm working with amchart4 where i have multiple series which displays single tooltip box, but i disabled few of the series using hidden value is true, even the series is disabled in the tooltip box i'm getting the value of the disabled series.

For the reference, i have added a logic in codepen
[In this series4 is disabled but can you tell me how to disable in tooltip too](https://codepen.io/meghanananuvala/pen/LYZPBpj)

Thank you

**Comment by martynasma** [comment]
You can check if series `isHidden`:

```
if (!item.isHidden) {
  ....
}
```

**Comment by meghanaNanuvala** [comment]
I have tried for it with the logic you gave, but it didn't workout 
Can you check once
[Updated with hidden logic](https://codepen.io/meghanananuvala/pen/LYZPBpj)

**Comment by martynasma** [comment]
Well, you did add the check on one series, but not the others.

**Comment by meghanaNanuvala** [comment]
Thank you
