### ISSUE TITLE
Is there any way to have single tooltip box if first series is disabled

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3335]
Hi 
In the below example, if i disable the first label then it's not able to show tooltip box for remaining values.
Is there a way to solve this
[Disbale the label1 and need of single tooltip box for remaining labels](https://codepen.io/meghanananuvala/pen/LYZPBpj)

Thank you

**Comment by martynasma** [comment]
The solution is to put `tooltipText` on all series, and use `maxTooltipDistance` to ensure that only one tooltip is shown at a time:

https://www.amcharts.com/docs/v4/tutorials/multi-series-shared-tooltip-with-colored-bullets/

**Comment by meghanaNanuvala** [comment]
even i applied maxTooltipDistance, if i disable first label then the tooltip box is not showing for other series
[]with maxTooltipDistance (https://codepen.io/meghanananuvala/pen/LYZPBpj)

**Comment by martynasma** [comment]
You need to add `tooltipText` to all series. Adding adapter only will not work.

**Comment by meghanaNanuvala** [comment]
Even all series were added that still not working
[With tooltiptext for all series](https://codepen.io/meghanananuvala/pen/LYZPBpj)

Can you check once

**Comment by martynasma** [comment]
Well, you do have tooltips explicitly disabled for all but one series :)

```
series2.tooltip.disabled = true;
```

**Comment by meghanaNanuvala** [comment]
I don't need all tooltips at a time i need only one tooltip but irrespective of labels disabled

[More than 1 tooltip](https://codepen.io/meghanananuvala/pen/LYZPBpj)

Can you tell me how to set that

**Comment by meghanaNanuvala** [comment]
" If series1 is disable, then I want to get combined lables at series2"
If series2 disabled, then combined label should be shown at series3.

**Comment by martynasma** [comment]
Normally, `maxTooltipDistance` would take care of this. But since you have code in adapters that result in error, it does not work.

Try fixing those errors (check browser console).

**Comment by meghanaNanuvala** [comment]
Thank you, It's working

**Comment by meghanaNanuvala** [comment]
It's working, but at some point I can see all the three tooltip boxes.
Added screenshot for reference

![Screenshot from 2021-03-02 19-51-24](https://user-images.githubusercontent.com/71019344/109662298-e99fc080-7b90-11eb-8d55-c3d59c6fee15.png)

Can you tell me how to get rid of that

**Comment by martynasma** [comment]
Set `maxTooltipDistance = -1`
