### ISSUE TITLE
ColumnSeries, problem by zoomToValues and startendchanged event with animation

### ISSUE THREAD

**Issue by SymbioticKilla** [amcharts/amcharts4#3337]
Hello,

thanks for a great product. 
We have a problem with ColumnSeries "startendchanged" event with activated animation.
`
dateAxis.events.on("startendchanged", this.zoomChanged, this);
`

`
 this.dateAxis?.zoomToValues(
        this._range.from.getTime(),
        this._range.to.getTime());
`

zoomToValues produces 2-3 "startendchanged" events because of animation and minZoomed/maxZoomed values are not the same that we provided.
With animation off(instantly) we get one event with correct values.
1. Is there any possibility to turn off events on zoomToValues and turn it on again?
2. Is it perhaps a bug in animation behavior?

Thank you!

**Comment by martynasma** [comment]
Try `rangechangeended` event instead.

**Comment by SymbioticKilla** [comment]
Thank you for reply!
Same problem: first event with ev.target.minZoomed has wrong value => old one.

**Comment by martynasma** [comment]
If you could post it as a CodePen demo, I'd be happy to take a look.
