### ISSUE TITLE
Grouping specific signals

### ISSUE THREAD

**Issue by JBtje** [amcharts/amcharts4#3338]
**Is it possible to group only specific signals?**

Given 3 signals:
- Signal 1: 10 hour of data with 50k datapoints
- Signal 2: Same timespan, but 400 points
- Signal 3: Same timespan, but 600 points

Signal 1 is a percentage between 0 and 100% and shows as a single line.
Signal 2 and 3 are either 0 or 100 and show as a standing bar (see example below) whereas the "o" and "+" are the datapoints. This signal has a background with transparency and highlights parts of Signal 1

Signal 2/3:
```
     +-------+        +-------+
     |       |        |       |
     |       |        |       |
     |       |        |       |
_____o       o________o       o___
```

Because the datapoints "o" and "+" are close to another (on the x-axis), the grouping causes the signal to remain "0" and the highlight is not shown.

Is it possible to do grouping for Signal 1, but no grouping for signal 2 and 3 while they are all shown in the same plot?

**Environment (if applicable)**
 - amCharts 4

**Comment by martynasma** [comment]
No, I'm afraid it's possible to group by single interval only.
