### ISSUE TITLE
Is there any support of labels in ForceDirectedLink?

### ISSUE THREAD

**Issue by HimanshuGupta25** [amcharts/amcharts4#3339]
I want to show labels on each link connected to one source, just look at the screenshot below :-
<img width="411" alt="Screenshot (11)" src="https://user-images.githubusercontent.com/10741362/109636563-bd287c00-7b71-11eb-8f52-f59ecfecdc97.png">

Please let me know if it's possible.

Thanks

Himanshu Gupta

**Comment by martynasma** [comment]
No, I'm afraid.

**Comment by HimanshuGupta25** [comment]
Yep because I found everywhere but no clue of label.

I have used this reference 
https://www.amcharts.com/docs/v4/reference/forcedirectedlink/
