### ISSUE TITLE
How to render different shapes in bubble chart for a given data set with same x,y values

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#334]
Hi

How to plot multiple shapes for a bubble with same data, x and y values

**Comment by martynasma** [comment]
Not sure what you mean. Can you provide an example of such chart and how would you like it to look like?

**Comment by Varshamathukumalli** [comment]
https://www.amcharts.com/demos/bubble-chart/

Like the above chart, plotting bubble chart with different shapes

**Comment by martynasma** [comment]
Well, you can basically have anything as bullet in amCharts 4:
https://www.amcharts.com/docs/v4/concepts/bullets/#Configuring_bullets

To get a diamond shape, you add a `Bullet` instance as a bullet to series, then `Rectangle` to it, and set its `rotation: 45`.

The size of the bullet might be achieved via "heat rules, which is basically a way to tie some property of an element to a value in data:
https://www.amcharts.com/docs/v4/concepts/series/#Heat_maps

I put together a quick example so it makes more sense:
https://codepen.io/team/amcharts/pen/YOeRPG/

Hope it helps.

**Comment by Varshamathukumalli** [comment]
That helped, Thanks.
What are all the values that property in heat rule can accept?
It would be helpful if it is documented somewhere.
Triangle is not rendering in the below code pen:
https://codepen.io/varshamathukumalli/pen/ZMxQVK?editors=0010
what to provide in heat rule property?

**Comment by martynasma** [comment]
Heat rules can accept any property that has numeric value or value of type `Color`.

I believe it is documented here:
https://www.amcharts.com/docs/v4/concepts/series/#Heat_maps

As for your codepen, you have "Triangle" misspelled. Correcting it shows the chart ;)

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
