### ISSUE TITLE
Ability to hide axis ranges when they are too small?

### ISSUE THREAD

**Issue by cowwoc** [amcharts/amcharts4#3340]
Is there a feature similar to "data grouping" for axis ranges?

**Background**: https://www.amcharts.com/demos/data-grouping-50k-points/ shows how to improve performance when rendering a large amount of data points by rendering an aggregate value when the chart is zoomed out.

My graph has 20645 data points and 504 axis ranges.

When the chart is zoomed out enough that an axis range is too small (say 5 pixels in width or less) I'd like to avoid rendering it. Such ranges are too small to see, clutter the axis with too many labels, and seriously impacts performance. When the user zooms in on a particular region, increasing the width of an axis range to something more reasonable I'd for it to be rendered again.

Is there an existing feature for this or should I open a feature request?

**Comment by martynasma** [comment]
There's no such feature built-in or planned for current version.

Possible workaround would involve observing zoom-related events, then selectively hiding small ranges.

I'm afraid I don't have a ready-made demo for that, but it sounds doable.

**Comment by cowwoc** [comment]
@martynasma Thanks for the response. Can you please convert this question into a feature request?

In terms of implementing this thing, if I listen to zoom events, how do access the list of axis ranges from the event listener? And how do I determine their width at the current zoom level?

**Comment by martynasma** [comment]
> @martynasma Thanks for the response. Can you please convert this question into a feature request?

I'm pretty sure, we're not going to implement this, though. :(

Axis has a property [`axisRanges`](https://www.amcharts.com/docs/v4/reference/axis/#axisRanges_property) which is a [`ListTemplate`](https://www.amcharts.com/docs/v4/concepts/list-templates/) that you can iterate on using `each()`.

Now, each range will contain `date` and `endDate`, which you can convert into actual pixels via axis' method [`dateToPoint()`](https://www.amcharts.com/docs/v4/reference/dateaxis/#dateToPoint_method).

Hope that makes sense :)

**Comment by cowwoc** [comment]
@martynasma Okay. I'll try implementing this myself and let you know if I run into any problems. Thank you!

**Comment by cowwoc** [comment]
I got this working with two minor gotchas:

1. https://github.com/amcharts/amcharts4/issues/1397#issuecomment-789955416
2. https://github.com/amcharts/amcharts4/issues/3344

I'll clean up the code once the above questions are answered but here is what it currently looks like:

```
timeAxis.events.on("startchanged", timeAxisChanged as any);
timeAxis.events.on("endchanged", timeAxisChanged as any);

function timeAxisChanged(
	event: TargetedEventDispatcher<am4charts.DateAxis<am4charts.AxisRenderer>, IAxisRendererEvents>): void
{
	const timeAxis = event.target;
	for (const range of timeAxis.axisRanges)
	{
		const startPoint = timeAxis.dateToPoint(range.date);
		const endPoint = timeAxis.dateToPoint(range.endDate);
		const size = (endPoint.x - startPoint.x + 1) + (endPoint.y - startPoint.y + 1);
		if (size < RANGE_MIN_SIZE)
		{
			if (range.visible)
				range.hide();
		}
		else if (size >= RANGE_MIN_SIZE)
		{
			if (!range.visible)
				range.show();
		}
	}
}
```
