### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by cowwoc** [amcharts/amcharts4#3341]
If you click on "Run Pen" on the last chart at https://www.amcharts.com/docs/v4/tutorials/hiding-non-integer-labels-on-value-axis/ you will get an error: `Cannot read property 'match' of undefined`

**Comment by xorspark** [comment]
Thanks for the heads-up. The demo has been fixed.

Note that a simpler way to go about this is to set [`maxPrecision`](https://www.amcharts.com/docs/v4/reference/valueaxis/#maxPrecision_property) to zero on the axis:

```
valueAxis.maxPrecision = 0;
```
