### ISSUE TITLE
Multiple Cursor Tooltips For Series Data with Unsynchronized X Values

### ISSUE THREAD

**Issue by Halvi3** [amcharts/amcharts4#3342]
I have a pretty standard XY chart with multiple series along a DateAxis xAxis, each with their own ValueAxis yAxis, and I'm trying to find a sweet spot of cursor tooltip behavior, where multiple tooltips (one for each series) can be displayed while still benefitting from some amount of snapping/leeway.

If I leave `cursor.snapToSeries` turned off, then I get part of my desired behavior, where the chart will display labels for each value axis at the y position of the cursor, and if there are multiple series that have a data item exactly at the date cell underneath the cursor's position, then they each display a tooltip.

If I set 'cusror.snapToSeries' to an array of my visible series (I will have something like 40 series created from the data, but max 5 of them visible at any one time) then I get the other behavior I want, where the user doesn't have to hover exactly over the right date cell (second-interval data over multiple minutes, don't want them to have to find the exact right second to get a tooltip for a series), but it only displays a tooltip for the closest series to the mouse position, instead of the closest point for all series.

the examples from https://www.amcharts.com/docs/v4/tutorials/multiple-cursor-tooltips-on-scatter-chart/ do almost exactly what I'm looking for, e.g. if I modify the data in those examples so that the x values of each data point are not all the same value for both series, the tooltip just snaps to the closest point for each series independently:

![Screen Shot 2021-03-02 at 9 35 15 AM](https://user-images.githubusercontent.com/6120342/109689943-afa3cf80-7b3a-11eb-99ae-5526c4297415.png)

I was thinking maybe I need to modify `getSeriesDataItem` for my date axis in a similar way to how that tutorial modifies ValueAxis, but not sure if that's the right approach or exactly what modification should be.

Code sandbox link to my code (with snapToSeries enabled currently), apologies that there's a lot of extraneous bits to sort through there
https://codesandbox.io/s/multi-series-question-urt2s?file=/src/App.js 

![Screen Shot 2021-03-02 at 9 30 33 AM](https://user-images.githubusercontent.com/6120342/109690750-86377380-7b3b-11eb-8984-270f33b1f4f6.png)

As an example of what I mean with my chart, with the cursor in that position I would ideally want to display the tooltip for the cyan and orange lines closest dot. Also displaying the tooltip for the light blue dot on the far right would be better than only displaying one tooltip ever, but it would also be great if I could exclude showing tooltips for series where their closest point is too far away from the x position (like `cursor.maximumTooltipDistance`, but only along the x-axis instead of raw distance)

**Comment by martynasma** [comment]
I don't think what you need is currently doable with amCharts 4 built-in functionality.

It might be possible by overriding `getSeriesDataItem`, but I can't provide any guidance on that, I'm afraid.
