### ISSUE TITLE
Zoom button shape with "am4core.options.queue = true" - on Firefox

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#3343]
**Bug description**

In Firefox browser using `am4core.options.queue = true` will change zoom button shape
CodePen (https://codepen.io/aniov/pen/qBqKrmq?editors=0010)

![zoomButtonShape1](https://user-images.githubusercontent.com/21243081/109799016-28cb2180-7c24-11eb-883b-44670d66135d.gif)

**Environment (if applicable)**
 - amCharts version 4.10.16
 - Firefox 86.0 (64 bytes)
 - ReactJs

**Comment by martynasma** [comment]
A quick way to fix it is to invalidate the zoomout button:

```JavaScript
chart.events.on("inited", function() {
  chart.zoomOutButton.deepInvalidate();
})
```

At this moment we are not able to provide built-in fix.

**Comment by aniov** [comment]
Thank you.
This seems to do the trick for now.
