### ISSUE TITLE
Typescript example missing parameter type

### ISSUE THREAD

**Issue by cowwoc** [amcharts/amcharts4#3344]
The Typescript version of the first code panel in https://www.amcharts.com/docs/v4/tutorials/handling-axis-zoom-events-via-api/ reads:

```
dateAxis.events.on("startchanged", dateAxisChanged);
dateAxis.events.on("endchanged", dateAxisChanged);
function dateAxisChanged(ev) {
  console.log("DateAxis zoomed!");
}
```

Please update the code to include the type of the function parameter (`ev`) and return type. I tried and failed to figure what the parameter should be :)

**Comment by martynasma** [comment]
We do not include parameter type in TypeScript snippets for a reason. I understand that it does not look pretty, but a lot of users do not make distinction between TS and JS, and having types in JS would break the code, whereas not having it in TS would only produce a warning, and TS users are generally more knowledgeable :)

I know it's a half-a$$ed reason, but it is what it is.

**Comment by cowwoc** [comment]
@martynasma That's sad... I think this is going to cause real problems because in the above case there is no easy way for me to figure out what type to pass to Typescript. This needs to be documented somewhere.

If you're afraid of JS users flooding you with requests, you could default the code panel to showing JS code. Users would have to explicitly click on the TS tab to get Typescript code. You could also prefix each code snippet with a disclaimer:

`// NOTE: You cannot paste this Typescript code into Javascript files!` :)

**Comment by cowwoc** [comment]
In the meantime, are you able to provide the appropriate type for the above specific case? :) I need to please the eslint gods.

**Comment by martynasma** [comment]
`ev: any` should shut them up - they're not particularly needy ;)

**Comment by cowwoc** [comment]
This works on the `timeAxis.events.on()` end but if I try the same on the function parameter I get:

`ESLint: Unsafe member access .target on an any value.(@typescript-eslint/no-unsafe-member-access)`

Is there a more specific type I can use? I am currently using `TargetedEventDispatcher<am4charts.DateAxis<am4charts.AxisRenderer>, IAxisRendererEvents>` but it's a complete guess on my part.

**Comment by martynasma** [comment]
How about `unknown`? It's less permissive, so lint might let you get away with it :)

**Comment by cowwoc** [comment]
You cannot do this: `dateAxis.events.on("startchanged", myFunction as unknown)` because you'll get:

`TS2345: Argument of type 'unknown' is not assignable to parameter of type '(this: unknown, event: { type: "startchanged"; target: DateAxis ; }) => void'.`

But more importantly, this isn't the parameter I am asking for help with. I am asking what type I should declare for `myFunction`'s parameter... You know, the incoming `event`. What type should that have?

You can't declare that as `unknown` because the function method needs to access `event.target`, among other things, and you cannot access properties from `unknown`.

**Comment by Pauan** [comment]
@cowwoc This should work:

```ts
import { AMEvent } from "@amcharts/amcharts4/core";
import { IDateAxisEvents } from "@amcharts/amcharts4/charts";

dateAxis.events.on("startchanged", dateAxisChanged);
dateAxis.events.on("endchanged", dateAxisChanged);
function dateAxisChanged(ev: AMEvent<typeof dateAxis, IDateAxisEvents>["startchanged" | "endchanged"]) {
    console.log("DateAxis zoomed!", ev.target);
}
```

**Comment by cowwoc** [comment]
@Pauan First of all, thank you!

The first type-parameter looks wrong to me. I ended up using `DateAxis` instead of `typeof dateAxis`. The latter prevents you from referencing `event.target.axisRanges`.

So to recap, I used:

`function dateAxisChanged(ev: AMEvent<DateAxis, IDateAxisEvents>["startchanged" | "endchanged"])`
