### ISSUE TITLE
[question] How can I set a different field for tooltips in a PieChart?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3345]
I am looking for a way to handle negative values in a pie chart. My chart data looks like this bellow: 

```
data = [{
   name: 'Category A',
   value: 10,
   realValue: -10,
}];
```

I need to use the `value` field as chart value but `realValue` field to show tooltips

**Comment by xorspark** [comment]
You can refer to the field directly, just like in your v3 question.

```
pieSeries.slices.template.tooltipText = "{category}: {realValue}"
```
