### ISSUE TITLE
Different Heights for Bar Chart

### ISSUE THREAD

**Issue by bogiraju** [amcharts/amcharts4#3346]
Not able to add different heights to bars.
below code not working.

series.dataItems.template.adapter.add("height", (label, target) => {
    return am4core.percent(target.valueX / valueAxisD.max * 100);
});

**Comment by martynasma** [comment]
`height` and its adapter is not used in any layout. It's a shortcut property to set height. Try `pixelHeight` adapter instead.

**Comment by bogiraju** [comment]
pixelHeight also not working

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by bogiraju** [comment]
The height adapter is working fine with the build version, not in the development mode.
