### ISSUE TITLE
Cursor selectX - selection should only be made on drag

### ISSUE THREAD

**Issue by x1mrdonut1x** [amcharts/amcharts4#3347]
**Bug description**

When setting `XYCursor` behaviour to 'selectX', it only works when click&drag is complete. 

When clicking on the chart once, the selection will persist until a drag + mouse up event. There is no way to remove that selection when clicking somewhere else or outside the chart.

There should be a way to programatically remove the selection.

https://codepen.io/team/amcharts/pen/gKYmEL

I believe the selection should only be made when click&drag, or there should be an option for this.

**Comment by martynasma** [comment]
To programatically remove the selection you can just do this:

```
chart.cursor.selection.hide();
```
