### ISSUE TITLE
AMCharts - labels not showing in forced directed graph with tree map

### ISSUE THREAD

**Issue by akilasithum** [amcharts/amcharts4#3349]
I have created a AMCharts forced directed graph with treeMaps as the nodes. My problem is labels of the treeMap is not showing. My example can be seen in the following pen.  can anyone suggest about my error. 

[https://codepen.io/akilasithum/pen/VwmBYBz](https://codepen.io/akilasithum/pen/VwmBYBz)

**Comment by martynasma** [comment]
Frankly, I'm even surprised it works at all :)

Unfortunately, this is well beyond what we have imagined it can be used for, so we won't be able to provide any help wit that. Sorry.

**Comment by akilasithum** [comment]
Seems to be a series is not created with the child elements. Does any one have any suggestion on this?
var template = treeMap.seriesTemplates.create("0");
