### ISSUE TITLE
How to access all bullets in a chart

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#335]
Hello,

Is there any way to access all bullets present in all series of a chart to modify properties, rather than changing the same property for each series bullet?

**Comment by martynasma** [comment]
You can use series' `bullets` list for that. It holds the list of bullet templates used for that series. Changing properties on template, will change appearance of the actual bullets created from the template.

So, if you have only `CircleBullet` as bullets in all of the series, and want to change `radius` for all of them, you might do something like this:

```
var bullet = series.bullets.push(new am4charts.CircleBullet());
bullet.circle.applyOnClones = true; // this is needed to make changing template's "circle" properties apply to clones
// ...
function changeBullets() {
  chart.series.each(function(series) {
    series.bullets.each(function(bullet) {
      bullet.circle.radius = 20;
    })
  });
}
```

Here's a working example:
https://codepen.io/team/amcharts/pen/12a2631b22e9d676f9b11b10947eb76d?editors=0010

**Comment by VaishnaviAppannagari** [comment]
Ok. Thanks.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
