### ISSUE TITLE
Programmaticaly hide SeriesRange

### ISSUE THREAD

**Issue by x1mrdonut1x** [amcharts/amcharts4#3351]
I would like to hide a DateAxis SeriesRange programmaticaly.

There are two series on the chart: one that displays data and that has a range which fills the content in blue.

The other series is "invisible", it is only used to display a legend item that would toggle the Series Range on the first series.
Is it possible to change the opacity of only the SeriesRange when toggling the Legend Item? I would not want to change the opacity of the whole first series, as I could have more ranges.

**Comment by martynasma** [comment]
There's no way to temporarily hide a series axis range.

You can just remove it by disposing it and invalidating series (so it redraws its masks):

```
range.dispose();
series.deepInvalidate();
```

https://codepen.io/team/amcharts/pen/8d4002d08d83fcdacc860bda2c9a0c86

**Comment by x1mrdonut1x** [comment]
Thanks.

When trying to add a new range after disposing the old one, I'm getting an "EventDispatcher is disposed" error.

How can I re-draw the deleted range (or create an identical one) without errors?

https://codepen.io/aniznik/pen/abBRZNV

**Comment by martynasma** [comment]
I seems you also need to remove deleted axis range from the axis:

So instead of this:

```JavaScript
range.dispose();
```

We should do this:

```JavaScript
dateAxis.axisRanges.removeValue(range);
```
