### ISSUE TITLE
Value axis is not exported to image if labels use html template

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3352]
**Bug description**
Value axis is not exported to image if labels use html template.

I just added 
`valueAxis.renderer.labels.template.html = '{value}g';` to the export example
https://www.amcharts.com/demos/exporting-chart-to-image/

The chart itself is rendered correctly - but in the exported image the value axis is missing:
![image](https://user-images.githubusercontent.com/58069494/110096786-98fdb280-7d9e-11eb-9c10-0fd3070a23ba.png)

https://codepen.io/chrisadler/pen/PobBdaQ?editors=0010

**Environment (if applicable)**

 - amCharts version: 4.10.16 (and earlier - don't know since when exactly)
 - Browser and its version: all browsers

**Comment by martynasma** [comment]
HTML content cannot be exported. There's no way around it, I'm afraid.
