### ISSUE TITLE
Why are AMCharts with large amounts of data faster when you close the development console on your browser?

### ISSUE THREAD

**Issue by jeremypanelli1** [amcharts/amcharts4#3354]
I noticed this behavior when dealing with charts with large (> 1k) of data points and multiple series. I don't think that this is a bug or anything, just curious on why the dev menu in chrome makes amcharts less performant.

**Comment by martynasma** [comment]
I suppose it's because of [this Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1077657).
