### ISSUE TITLE
Normally chart should update it's gravity center when container resizes. Take this for example:

### ISSUE THREAD

**Issue by SwetaPMizzou** [amcharts/amcharts4#3355]
Normally chart should update it's gravity center when container resizes. Take this for example:
https://www.amcharts.com/demos/collapsible-force-directed-tree/

If you resize the window you'll see chart updating.

Can you post your chart setup on CodePen so that we can investigate?

_Originally posted by @martynasma in https://github.com/amcharts/amcharts4/issues/2709#issuecomment-659961861_

**Comment by martynasma** [comment]
The chart and gravity centers update fine to me when chart container size changes.
