### ISSUE TITLE
Change linkWith array of string into array of object

### ISSUE THREAD

**Issue by loicbrigardis** [amcharts/amcharts4#3357]
The default behaviour of linkWith is to connect nodes with array of strings

examples : 

`"children":[  
         {  
            "name":"David",
            "value": 30,
            "linkWith": ["Carol", "John"] 
         },
         {  
            "name":"Mike",
            "value":18
         }
      ]
   }`
   
   I would like to use objects instead of strings and add some informations
   
   `
   "children":[  
         {  
            "name":"David",
            "value": 30,
            "linkWith": [{
                "name": "Carol",
                "image": "...",
                "url":"..."
            },
            {
                "name": "John",
                "image": "...",
                "url":"..."
            },
            ] 
         },
         {  
            "name":"Mike",
            "value":18
         }
      ]
   }
   `
   
   Thank for your advices.

**Comment by martynasma** [comment]
Well, in that case you should set those objects up as `children` of the node.

**Comment by loicbrigardis** [comment]
Yeah but I would like links between nodes and not between parent and children. If I use children of the node, it's create a new node.

**Comment by martynasma** [comment]
Then it's just linkage by name.

**Comment by loicbrigardis** [comment]
Ok, and is it possible to have hit event on the links between nodes ?
