### ISSUE TITLE
Chart zooms on start when setting extraMax and strictMinMax

### ISSUE THREAD

**Issue by JacobDeuchert** [amcharts/amcharts4#3358]
**Bug description**

When setting extraMax and strictMinMax = true on the ValueAxis the charts begings to zoom when created and shows the zoom button even though the user never touched the chart.

`  valueAxis.extraMax = 0.1; 
  valueAxis.strictMinMax = true;
  valueAxis.max = 3000;
  valueAxis.min = 0;
`

I created a [codepen](https://codepen.io/jacobdeuchert/pen/XWdKqBq) showing it.
If you comment out the extraMax or the strictMinMax on the axis the chart works as expected.

I don't know if it's a bug or if it's an intended feature and i am doing something wrong.

**Comment by martynasma** [comment]
`extraMin`/`extraMax` are not compatible with `strictMinMax`.

We'll update the docs accordingly. Sorry, for missing this.

**Comment by JacobDeuchert** [comment]
Thanks for the fast response. I will probably just increase the max of the chart by 10% and continue using strictMinMax.
