### ISSUE TITLE
Show single tooltip for Barchart with XYCursor

### ISSUE THREAD

**Issue by joepwijnhoven** [amcharts/amcharts4#3359]
**Question**

I have a barchart which uses XYCursor to select a period. Adding the XYCursor creates more tooltips which I do not want.

Example barchart:
https://www.amcharts.com/demos/stacked-clustered-column-chart/

JSFiddle of barchart but with added XYCursor:
https://jsfiddle.net/xLmbgr06/2/

Is there a way to prevent te added tooltips? I tried `snapToSeries` but this does not work properly on a barchart (
If you hover over a bar it shows a different tooltip because the datapoint of that other bar is closer) .

**Environment**

- Amcharts v4

**Comment by martynasma** [comment]
If you need to use `XYCursor` then you will need to do two things here:

1) Move `tooltipText` to series (from column template).
2) Set `maxTooltipDistance` on cursor.

https://jsfiddle.net/9f2t6duv/

**Comment by joepwijnhoven** [comment]
Thanks for your response!

I also tried that, but that doesn't work as beautiful as without the XYCursor (see image).  I would expect a tooltip for the bar that I am hovering over.

![image](https://user-images.githubusercontent.com/11572235/110433317-93f77680-80b0-11eb-868a-0f286b65703e.png)

**Comment by martynasma** [comment]
In that case, there's another option:

1) Leave everything as is.
2) Disable cursor's tooltips: `series.cursorTooltipEnabled = false`.

**Comment by joepwijnhoven** [comment]
Yes, that is what I want! thank you very much!
