### ISSUE TITLE
Tooltips overlap after Chart Data updated

### ISSUE THREAD

**Issue by JacobDeuchert** [amcharts/amcharts4#3360]
**Question**
If the chart data gets updated the currently shown tooltips start overlapping:

Before the data gets added: 
![image](https://user-images.githubusercontent.com/43518397/110310956-702a2700-8003-11eb-8695-afce74071155.png)

After the data is updated:
![image](https://user-images.githubusercontent.com/43518397/110310999-7ae4bc00-8003-11eb-81e5-c2f0ec60e16d.png)

I created an example in [codepen](https://codepen.io/jacobdeuchert/pen/qBbEZYR).

It seems as if after the charts gets updated the tooltips just go inline with their respective bullet and stop calculate the space requirements of the other tooltips. This works just fine when having two series not as close together.

Is there an option i am missing in the tooltips or the cursor?

**Comment by martynasma** [comment]
You can fix this by calling `chart.handleCursorPositionChange()`, e.g. by delaying it after update:

```JavaScript
chart.events.once("datavalidated", function(){
          setTimeout(function(){
            chart.handleCursorPositionChange()
          }, 1000)
})
```

Here's a working example:
https://codepen.io/team/amcharts/pen/94752cbf49e38c2ab5ef099c2fc5fc35?editors=0010
