### ISSUE TITLE
local files from disk

### ISSUE THREAD

**Issue by ldijkman** [amcharts/amcharts4#3364]
Hello 

if i understand right, amcharts does not work with local files from disk

i do not understand
if i try
https://www.html5rocks.com/en/tutorials/file/dndfiles//
it reads/displays files from disk 

i would like to read files from disk
for a simple arduino project csv files maybe csv log from serial port data save to file (or sdcard)

test chart log from serial port to file
but saved to github bcause the file had to be online

http://arduino.tk/csv_chart.php?file=https://raw.githubusercontent.com/ldijkman/Arduino_Plant_Watering_System/main/reduce_received.csv 

but would be nice if i could use a disk file https://www.html5rocks.com/en/tutorials/file/dndfiles//

PS the amcharts are perfect, so easy to understand and perfect labels
much better as the offline csv graphic viewers i have treid

only  have not figured out yet how the minute log tooltips circles labels are easier popup displayed between the second log
have to be exactly on the 00 minute fo tooltip display 

greet luberth
luberth

**Comment by martynasma** [comment]
I'm afraid we do not plan on implementing `FileReader` interface for our data loading capabilities. It's quite limited, as there is no way to specify which file to load by URL - it has to be File object selected via "file" input by user. Sorry.
