### ISSUE TITLE
Way to Change Font Size with Zoom

### ISSUE THREAD

**Issue by jpnoe** [amcharts/amcharts4#3367]
Is there any way to change font size with zoom on force directed chart? I see a startendchanged event through which the zoom level might be accessible, but it doesn't seem to fire with zoom. Using the wheel event, I cannot find anywhere in the chart or series that contains a changing zoom level value? Any ideas?

**Comment by martynasma** [comment]
There's an easy way to make labels scale together with nodes:

```JavaScript
networkSeries.nodes.template.label.nonScaling = false;
```

**Comment by jpnoe** [comment]
Thanks so much!
