### ISSUE TITLE
Error in dataItem with label adapter

### ISSUE THREAD

**Issue by franjorub** [amcharts/amcharts4#3368]
**Bug description**

Hi, I'm using TypeScript and following the example to add an adapter for labels, I have an error that the "value" property is wrong, did you mean values?

![image](https://user-images.githubusercontent.com/24401350/110514313-8e645580-80dd-11eb-8528-6ea0088bc522.png)

doing a console log the value property exists in the data item so, I think this is an error with the d.ts file

**Comment by martynasma** [comment]
It's not a bug, it's just adapter defines generic `AxisDataItem` return value type, which fools the compiler, causing it report a warning.

To fix this just typecast to `: any` passed in `target` variable.

**Comment by franjorub** [comment]
Could this be included as a comment in the code for the TS example ? https://www.amcharts.com/docs/v4/concepts/adapters/#Chaining_multiple_adapters

**Comment by martynasma** [comment]
I just updated the code to use `dataItem.values` instead, so you do not need to type-cast anything.

Hope you find it acceptable, too.
