### ISSUE TITLE
Is it possible to set different border left, right, top, bottom for a column in XY-Chart (Bar Chart)? I need to have just 2 vertical lines and not the top and bottom for a particular column.

### ISSUE THREAD

**Issue by amanjangra3pg** [amcharts/amcharts4#3369]
**Question**

**Environment (if applicable)**

**Additional context**

**Comment by amanjangra3pg** [comment]
Is there any other work around maybe to achieve this? if you could just point me in the right direction, I may reach somewhere close. I just want 2 dashed lines on left and right side of a column and not on top and bottom if the value is 0.

**Comment by martynasma** [comment]
I think it might be doable using two thin column series.

https://codepen.io/team/amcharts/pen/732afde9af40a496d32ece0b26c17d88?editors=0010
