### ISSUE TITLE
Changing Outer Circle Behavior on ForceDirectedTree

### ISSUE THREAD

**Issue by jpnoe** [amcharts/amcharts4#3371]
When a node has children, it is formatted with an outer circle border, which expands upon being selected. Is it possible to get all nodes to render in this way, including ones without children? I tried experimenting with the outerCircle property, but it appears to be reset upon interacting with the node rendering the method ineffective.

**Comment by martynasma** [comment]
Hm, maybe with an event:

```JavaScript
networkSeries.nodes.template.events.on("validated", function(ev) {
  ev.target.outerCircle.disabled = false;
})
```

**Comment by jpnoe** [comment]
Great, thanks!
