### ISSUE TITLE
reload or load new data when some series is hidden will result in blank area

### ISSUE THREAD

**Issue by Zigngit** [amcharts/amcharts4#3372]
**Bug description**

Chart will be weired if you
1. hide a serie via legend
2. reload or load new data for the serie

Although serie is hidden (isHidden return true), the amcharts will still draw it with a blank area.

- amCharts: CDN version

**Additional context**

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
