### ISSUE TITLE
How can I limit the number of columns displayed at a column chart using scrollbar?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3373]
I have a chart similar to pareto diagram example: https://www.amcharts.com/demos/pareto-diagram/, and I'am trying to use zoomToIndexes() method this way: categoryAxis.zoomToIndexes(0, 11);

I think this should enlarge and display only 12 columns but it doesn't work

Thanks for the attention

**Comment by martynasma** [comment]
Check this response: https://github.com/amcharts/amcharts4/issues/3353#issuecomment-791987529

**Comment by gagigante** [comment]
It works for me, how can I do to force the zoom bar to be at the beginning?

**Comment by martynasma** [comment]
```JavaScript
chart.events.on("ready", function () {
  categoryAxis.zoomToIndexes(0, 11);
});
```

More info:
https://www.amcharts.com/docs/v4/tutorials/pre-zooming-an-axis/

**Comment by gagigante** [comment]
Thanks!
