### ISSUE TITLE
How do I assign multiple heat rules to a map image series

### ISSUE THREAD

**Issue by YujunXieODA** [amcharts/amcharts4#3375]
I have searched the closed issues and found this one where I have exact error
https://github.com/amcharts/amcharts4/issues/3114
But the issue above is for a columnseries, mine is a map image series.
I tried to assign a customValue to the series but it doesn't seem to have that property.

What I am trying to do is to have a circle for the map series, its radius is decided by dataitem's Count property but its fill color will be decided by data's Percent property.

I can only make the first part to work. Could you advise how to make the second rule work for a different property, which is not bind to the datafields.value property?

Thanks

Below is part of the codes related:

this._imageSeries = this._map.series.push(new am4maps.MapImageSeries());
this._imageSeries.dataFields.value = "Count";
let template = this._imageSeries.mapImages.template;
let circle = template.createChild(am4core.Circle);
		
this._imageSeries.heatRules.push({
	target: circle,
	property: "radius",
	min: 10, 
	max: 20,
	logarithmic: true
});

this._imageSeries.heatRules.push({
	target: circle,
	property: "fill",
	min: am4core.color("red"),
	max: am4core.color("green"),
	dataField: "Percent" // Can't make this work, getting "TypeError: Cannot read property 'low' of undefined"
});

**Comment by martynasma** [comment]
You can create multiple heat rules, but they need to be bound to actually available and defined data field, like `value`. You can't bind them to an explicit name of a field in data, I'm afraid.

You already using `value` for "Count", so you can't reuse it for "Percent". And there is no other numeric data field that you could use:

https://www.amcharts.com/docs/v4/reference/imapimageseriesdatafields/

Dunno, maybe you could try repurposing `zoomLevel` :)

**Comment by YujunXieODA** [comment]
> You can create multiple heat rules, but they need to be bound to actually available and defined data field, like `value`. You can't bind them to an explicit name of a field in data, I'm afraid.
> 
> You already using `value` for "Count", so you can't reuse it for "Percent". And there is no other numeric data field that you could use:
> 
> https://www.amcharts.com/docs/v4/reference/imapimageseriesdatafields/
> 
> Dunno, maybe you could try repurposing `zoomLevel` :)

@martynasma
Thanks for the advise. I will prefer not to hack a field which might be used for something else I don't know.
I ended up just map the circle's color field to a property from my view model object
`circle.propertyFields.fill = "Color"`
So I can implement my heat rule there directly like this:
`get Color(): string { 
	if (this.Percent < 0.5) {
		return "#B64343";
	}
	else {
		return "#1F8B51";
	}
}`
The only thing I don't know is how to get a correct color. For example, I can define the min color when Percent is 0 as red and max color when Percent is 1 as green. How should I figure a proper color for a Percent is 0.5? Any example that can help me figure it out will be appreciated.

Also, I am wondering why can't we just make multiple field mapping available to IMapImageSeriesDataFields? For example, something called customValues(or even just heatruleValues), which is basically a map. So when a heat rule tries to look for a proper value to read from, it can look up the map to see which property from the datacontext it should read from?

**Comment by martynasma** [comment]
> How should I figure a proper color for a Percent is 0.5? Any example that can help me figure it out will be appreciated.

You can use built-in color interpolation function:

```JavaScript
am4color(
  am4core.colors.interpolate(
    am4core.color("#B64343").rgb,
    am4core.color("#1F8B51").rgb,
    0.5
  )
)
```

(it's an undocumented function)

> Also, I am wondering why can't we just make multiple field mapping available to IMapImageSeriesDataFields? For example, something called customValues(or even just heatruleValues), which is basically a map. So when a heat rule tries to look for a proper value to read from, it can look up the map to see which property from the datacontext it should read from?

It could help, but I'm afraid this was never consider for feature set. Each "calculated" value is a huge load on performance. And even having a check if there are any custom ones would introduce additional burden on all charts, even though 99.9999% of chart setups would not make use of that feature. Sorry.
