### ISSUE TITLE
ForceDirectedTree - certain nodes' fixed property does not reflect their state

### ISSUE THREAD

**Issue by jpnoe** [amcharts/amcharts4#3376]
I'm having trouble fixing and unfixing nodes. Certain nodes remain fixed even when their fixed property is changed within the node's dataItem. I have this set up to occur on every node upon click, and it works for most, but certain ones remain fixed even when their properties contain "fixed: false"

**Comment by jpnoe** [comment]
I resolved it by setting the fixed property in a different location in the code, not that it makes any sense that this worked any differently.

**Comment by jpnoe** [comment]
I believe i've narrowed down the issue. It seems to happen if multiple "hit" events occur two close together in terms of timing, probably before the method is finished. What happens to interrupted event threads?

**Comment by jpnoe** [comment]
Update: removed all instances of fixing nodes, certain nodes randomly become fixed as I am using the chart. This makes no sense.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
