### ISSUE TITLE
categoryaxis end label are not display correctly 

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#3377]
**Question**
categoryaxis end label are not display correctly can you help me out

**Environment (if applicable)**

**Additional context**
![image](https://user-images.githubusercontent.com/54665162/110908118-5e62bf80-8334-11eb-96fb-58ed1a44227f.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Mahisandy** [comment]
here in this Demo Example i need to show end point label in chart
https://www.amcharts.com/demos/data-grouping-50k-points/

**Comment by martynasma** [comment]
Thanks. It's by design.

DateAxis displays grid/labels at some even intervals, like every ten years in the amCharts demo you linked to.

If the data ends before the next label/grid, it's not displayed.

**Comment by Mahisandy** [comment]
if we want to forcefully is there any way.

**Comment by martynasma** [comment]
Maybe add axis ranges:
https://www.amcharts.com/docs/v4/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/

**Comment by Mahisandy** [comment]
ok thanks
