### ISSUE TITLE
ColumnSerie grouping dates seconds interval causes low performance

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [amcharts/amcharts4#3378]
**Bug description**

The amchart4 [documentation on grouping intervals](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Group_intervals) includes the following example: [codepen](https://codepen.io/team/amcharts/pen/wvvKQBK)

In this exemple, a lot of data points are grouped by date.
If the dateAxis baseInterval is change to 15 minutes, nothing changes, the chart is rendered without any problem: [codepen](https://codepen.io/Sadiinso/pen/NWboGNO)

But if we changes the data generation code to generate dates minutes or seconds appart from one another, the chart rendering become extremely slow: [codepen](https://codepen.io/Sadiinso/pen/NWboGNO)

Upon further inspection of the generated chart, it seems like each column is made of multiple overlapped svg paths in this case (instead of one svg path per column like in the first two examples) which slows down the chart rendering significantly.

Is there a combination of options which can prevent this slowdown from occuring on tight date intervals ?

**Environment (if applicable)**

Latest amchart4 version on chrome 88 and edge 88.
Vanilla JS environment.

**Additional context**

**Comment by martynasma** [comment]
The issue with your CodePen is that you're essentially misleading the chart about granularity of your data.

The data is in seconds, whereas you set `baseInterval` to minutes, hence the issue.

You should either let chart decide about the granularity, or specify correct granularity in `baseInterval`.

If you need to control how grouping of the data happens, there's a number of settings for that:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Group_intervals

**Comment by SadiinsoSnowfall** [comment]
Oh, my bad, I have mistaken `baseInterval` with `groupInterval`.

I have changed 
```js
dateAxis.baseInterval = {
  timeUnit: "minute",
  count: 15
};
```
with
```js
dateAxis.groupIntervals.setAll([
  { timeUnit: "minute", count: 15 }
]);
```
And it is working flawlessly now.

Thank you for your time.
