### ISSUE TITLE
nonScalingStroke = true is ignored on bullets if set after strokeWidth

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#338]
![image](https://user-images.githubusercontent.com/1458520/45357106-f5b4f380-b5cd-11e8-880b-cec060fa631e.png)

Both series in the above chart have `Rectangle` used as bullet with `scale = 5`.

Both have `nonScalingStroke = true` set. The first one before `strokeWidth` displays correctly thin outline. The other which has `nonScalingStroke` set after `strokeWidth` displays scaled outline.

Example:
https://codepen.io/team/amcharts/pen/08b2eb2eb63cb605251397a7375d9fdb/

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.51](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.51).

## [4.0.0-beta.51] - 2018-09-13

### Changed
- Changed `Label.renderingFrequency` to `2`, for better performance.

### Fixed
- Performance tweaking.
- `DateAxis.baseInterval` was ignored in JSON-based configs.
- `"hoverActive"` state was not always being correctly applied.
- Better handling of cursor zoom and pan when outside chart area.
- Fixed occasional error when formatting dates or numbers.
- Line chart starts new segement only if properties (like `stroke`, `fill`, `strokeDashArray`, etc.) in data have changed. It used to start new segment if properties in data were defined resulting in reduced performance and disabled smoothed lines.
- Labels were not updating their position if their `fontSize` changed.
- `Sprite.nonScalingStroke = true` was ignored if set after `Sprite.strokeWidth`.
- `LineSeries` could leave some garbage lines while zooming.
- `ColumnSeries` could leave some garbage columns while zooming.
- `DateAxis` with one date only in chart data was not rendered properly.
- The chart was not zooming out after data validation.
- Added `ghostLabel` to `Axis` which is an invisible label and it helps to avoid unwanted changes of axis widht/height when the scale changes, e.g. on zoom.
- `zoomToMapObject`, if used with `MapPolygon` and custom `zoomLevel` was not working properly.
- `"hidden"` event of Series was called on initial chart initialization.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
Still doesn't work with heat maps. Reopening.

Sample:
https://codepen.io/team/amcharts/pen/YOeRPG

**Comment by zeroin** [comment]
Issue is fixed.
