### ISSUE TITLE
The pointer skips the vertical date line

### ISSUE THREAD

**Issue by MarkoB19** [amcharts/amcharts4#3380]
The pointer skips the vertical date line and shows a value with a offset from it. When I zoom in, the problem is solved.
The problem is that I show a weekly graph where this offset is constantly visible
Maybe this video will best show the problem.

<a href="https://www.loom.com/share/9c6f27b86f5843f0b3556a0df1d9230e"> <p>Data grouping 50K points - amCharts - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/9c6f27b86f5843f0b3556a0df1d9230e-with-play.gif"> </a>

Thank You

**Comment by martynasma** [comment]
It does not skip, it's just how grid/label is positioned when grouping data items and not.

You can force grid to always be in the middle like this:

```JavaScript
dateAxis.renderer.grid.template.location = 0.5;
dateAxis.renderer.labels.template.location = 0.5;
```

**Comment by martynasma** [comment]
More info here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis

**Comment by MarkoB19** [comment]
Thank You very much.
