### ISSUE TITLE
Improve design requiring user to set location to 0.0001 instead of 0

### ISSUE THREAD

**Issue by cowwoc** [amcharts/amcharts4#3382]
At https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/ you write:

> There is a catch, though. Since location default is 0 (zero), and we set it to zero as well, the DateAxis will not be able to distinguish 
> from user-set zero from default zero, and will assume that it's OK to go through with the fuzzy logic described above.
>
> The workaround is to set it to a value that is very close to zero, say, 0.0001.

Instead of causing confusion (there is no guarantee that users will run across this documentation or remember this detail a while later) consider the following two alternatives:

1. Expose a setter for this property. If a user invokes it, set an internal boolean flag to indicate that the value was overwritten by the user.
2. Make the value nullable, where a null value indicates the default value (not set by the user).

**Comment by martynasma** [comment]
Thanks for the suggestions. We have considered those a while ago. Unfortunately, they do not help, as location is being set internally by DateAxis, too. So based with current design of amCharts 4, it's impossible to distinguish between user-set and internal settings. Sorry.
