### ISSUE TITLE
SankeyNode styling

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3384]
Hello,

I'm trying to change the positioning of node/labels in a sankey diagram but some of the settings don't have any affect. Below is my attempt

![image](https://user-images.githubusercontent.com/40542072/111172211-4c8c5100-85ae-11eb-9e85-eed7b9449ffc.png)

Things I want to achieve:
- move the label above node and have it in a rectangle box (this is working)
- allow necessary space below each node for the new rectangle -  is this possible without using hacks (margin/offset)? I tried setting margin on the nodeTemplate but no results

`nodeTemplate.margin(0, 0, 20, 0)`

- rectangle border should use the node's fill but this doesn't seem to work with adapter
- adjust rectangles height dynamically (somehow)?

Currently for labels that are shorter this happens
![image](https://user-images.githubusercontent.com/40542072/111175765-68452680-85b1-11eb-819a-f2d52871e077.png)

```jsx
nodeTemplate.nameLabel.label.background.adapter.add('fill', (fill, target) => {
  // seems to fail, target.dataItem is undefined
  const id = (target.dataItem.dataContext as Edge).edge.to.id
  const node = chart.nodes.getKey(id.toString())
  return am4core.color(node.fill.hex)
})
```

I could take the fill from each node but have no idea how to set it to each rectangle separately...

My solution for the above but not working 100%

```jsx
nodeTemplate.nameLabel.label.background = new am4core.Rectangle()
nodeTemplate.nameLabel.label.background.width = 100
nodeTemplate.nameLabel.label.background.height = 40
nodeTemplate.nameLabel.label.background.strokeWidth = 1
nodeTemplate.nameLabel.label.background.strokeOpacity = 1
nodeTemplate.nameLabel.label.background.fillOpacity = 1
nodeTemplate.nameLabel.label.background.fill = am4core.color('#fff')
nodeTemplate.nameLabel.label.background.stroke = am4core.color('red')
nodeTemplate.nameLabel.label.dx = -20
nodeTemplate.nameLabel.label.dy = -15
```

![image](https://user-images.githubusercontent.com/40542072/111176816-544df480-85b2-11eb-9db9-6b6cd2e6d335.png)

This would be a reference for what I want to achieve

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test and maybe find a solution?

**Comment by teodosii** [comment]
[CodePen](https://codepen.io/raresm2020/pen/qBqwXJp)

I've solved setting the color based on node's fill but I still need to
- position correctly the rectangle above the node (some rectangles are put in the middle)
- space out nodes to allow space for rectangles

Also it seems rectangle's width/height aren't really taken into consideration. This is nice for height since I want it dynamically adjusted but I'd prefer to set a fixed width.

Do I need to open a ticket on amcharts' website for this?
Thank you!

**Comment by teodosii** [comment]
@martynasma 
I think I've sort of managed to shift the nodes in a way using an adapter on `dy`

```jsx
_shiftNodesDY(dy: number, target: SankeyNode): number {
  const edge = target.dataItem.dataContext as Edge
  const { nodeIndex } = edge.edge.to
  if (!nodeIndex) return dy
  return dy + nodeIndex * 15
}
```

but the last node gets clipped.

![image](https://user-images.githubusercontent.com/40542072/111293254-bc9fe300-8651-11eb-842b-ec2fd9ecfa5a.png)

**Comment by martynasma** [comment]
> but the last node gets clipped.

I suppose the easiest way to solve it is to add some padding to the chart, e.g.:

```
chart.paddingRight = 80;
```
