### ISSUE TITLE
How to hide "empty" gaps between column series

### ISSUE THREAD

**Issue by RSchneider94** [amcharts/amcharts4#3385]
**Question**

Print example:
![image](https://user-images.githubusercontent.com/11929659/111201769-e0a3eb80-85a1-11eb-99a7-9db421e32910.png)

I have this chart with doesn't have data coming from the API for the date "07 March" for example. Why does it creates this empty space there if there's no data for this date at all? I thought it has to do with the `minGridDistance`, but no, I tried to set different values and also setting no value hasn't changed. I would like to display the bars only for the dates which I actually have some `date` coming from API.

**Comment by martynasma** [comment]
Try this:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Removing_empty_time_units

**Comment by RSchneider94** [comment]
> Try this:
> https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Removing_empty_time_units

Perfect! Thanks! My bad, I didn't paid attention to the doc.
