### ISSUE TITLE
baseInterval not calculating correctly for simple use case

### ISSUE THREAD

**Issue by andrija29** [amcharts/amcharts4#3386]
I'm using AMCharts 4 and I am passing hour - values data pairs. So for example at 15h there is value of 10, at 16h value of 15, etc.

```
[...{
    "date": new Date(2020, 1, 1, 15, 0, 0, 0),
    "value": 10,
}, {
    "date": new Date(2020, 1, 1, 16, 0, 0, 0),
    "value": 15,
}...]
```
Chart is not plotting lines between points correctly (it is displaying correct data, but line is not printed as it should).

Example:

[https://i.imgur.com/IOZeqcM.png](https://i.imgur.com/IOZeqcM.png)

As you can see in the example above, it is displaying correct data but it does not have correct interpolation between lines. From example from picture it is obvious that from 14h to 15h it is a uptrend and that line should go up gradually and be there for 15h. Instead, it gradually goes down and when it realizes the value for 15h it moves up instantly to correct it.

After a lot of wasted time I figured out that I can manually set baseInterval and that solved the issue.
I didn't look into your source code but I am afraid that this is clearly a bug because this is simple case that your algorithm should recognize.

Edit: After some thinking I am not even sure why you need to know value of the interval when you just only need to plot the line between 2 values. I guess I want to check the source code now.

**Comment by andrija29** [comment]
Okay so without custom gridIntervals it is working as intended, but if I change grid interval it bugs out. Why are those 2 related?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by andrija29** [comment]
> Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

Here: https://codepen.io/andrija29/pen/abBxELp

**Comment by martynasma** [comment]
Thanks.

OK, so what is happening is you are telling DateAxes that there can only be 2-hour increments and nothing else, so it reverts to that granularity of data, hence the view.

As you correctly figured out, overriding data granularity with `baseInterval` fixes it:

```JavaScript
xAxes1.baseInterval = [{ timeUnit: "hour", count: 1 }];
```
