### ISSUE TITLE
ValueAxis auto adjust (min/max) doesn't seem to work with large value spread

### ISSUE THREAD

**Issue by squabtracker** [amcharts/amcharts4#3388]
I have multiple different data points on one graph that are grouped logically, but the ranges are very far apart. One is in the 34K range, and another is in the 1 to 2 range. When hiding the different Series it will not adjust below a max of about 30-40 for the series that is between 1 and 2. In the example below, hide all, then show Series 1 and the range fits perfectly. Hide Series 3 and then show Series 2 and the range fits. Hide Series 2, then show Series 3 and the range is 0-40 instead of being 1-2 or so. This seems like it is related to having multiple series with ranges being far apart. Multiple small ranges on one graph works, and multiple large ranges works, but when I combine the two the small range is too large and the line does not fill the vertical space on the graph.

I tried adding code to adjust the min/max, but the minZoomed and maxZoomed seem to always return the same values.

dateAxis.events.on("startendchanged", function(ev){
  valueAxis.min = valueAxis.minZoomed;
  valueAxis.max = valueAxis.maxZoomed;
});

Here is a link to an example that I created.
https://codepen.io/squabtracker/pen/MWbRqmW

Any help is appreciated!

**Comment by squabtracker** [comment]
Also, I should add that even if series 3 is in a range of 5-10 the max will still be 40 so it does not just happen because of the decimal places.

**Comment by martynasma** [comment]
Try adding this:

```JavaScript
valueAxis.maxZoomFactor = 1000000;
```

**Comment by squabtracker** [comment]
Perfect! That works like a charm. Thanks for the help!
