### ISSUE TITLE
Chart cursor tooltip not visible with stacked category axes

### ISSUE THREAD

**Issue by ceekaay** [amcharts/amcharts4#3389]
I'm using a date axis as x-axis and multiple vertical stacked category axes as y-axes. Category values are realized through bullets points. When I hover over these points with lineX cursor, I want so see the tooltips for every bullet point on this line. This is not working.
But when I additionally add a ValueAxis to yAxes it is working. Am I missing a configuration property?

Check this CodePen: https://codepen.io/ceekaay/pen/GRNLdox

Thank you

**Comment by martynasma** [comment]
Try setting `series1.baseAxis = dateAxis`

**Comment by ceekaay** [comment]
@martynasma Now the tooltips are visible, but the bullet circles from the other series are shifted from their horizontal y grid line

**Comment by martynasma** [comment]
Right.

Try setting `openCategoryY` data field to the same as `categoryY`, e.g.:

```JavaScript
series1.dataFields.categoryY = "network";
series1.dataFields.openCategoryY = "network";
```
