### ISSUE TITLE
Is there a way to avoid line series dots  from reaching the top of the grid?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3391]
https://www.amcharts.com/demos/pareto-diagram/ 

Is there a way to avoid line series dots  from reaching the top of the grid?

**Comment by martynasma** [comment]
Yes, for example this:
https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Relatively_expanding_the_scale

Or you can just unmask the bullets:
https://www.amcharts.com/docs/v4/concepts/bullets/#Disabling_bullet_clipping

**Comment by gagigante** [comment]
Thank you so much!
