### ISSUE TITLE
[Queston] - Multi-content PDF export with dynamic number of charts and non-charts sections

### ISSUE THREAD

**Issue by mahesh-chotrani** [amcharts/amcharts4#3392]
**Question**
Following [this example](https://www.amcharts.com/docs/v4/tutorials/generating-multi-content-pdf-export/), was able to include multiple charts in a pdf export, along with non-chart sections and columns. This worked successfully for ~20+ charts

We have a requirement, where in a configuration page a user can select few charts and non chart sections, another page for preview and download PDF. This works with user selecting at least one chart because `chart.exporting.pdfmake` loads the `pdfmake` library and populates instance. 
But there can be a case where user may not select any chart, but only non-chart sections. 

In your opinion, what would be the best way to get an instance of `pdfmake` for export ?

```
Promise.all([
  chart1.exporting.pdfmake,

  // other charts, if selected
  . . . 
]).then(res => {
  const pdfMake = res[0];

  // content
  . . . 

  // export
  pdfmake..createPdf(doc).download(`a.pdf`);
});
```

**Comment by martynasma** [comment]
Well, you can use a chart not included in the actual export to load pdfmake. Loading `pdfmake` does not mean it will be included in the actual export.

**Comment by mahesh-chotrani** [comment]
> Loading `pdfmake` does not mean it will be included in the actual export.

Yes, that I understand. 

In my preview page there are only those elements (_charts or non-charts_) which a user has selected and which are to be exported to PDF. So, just to get instance of `pdfmake`, if there are no charts on the page, the only option I can think of is to add a default chart **which is hidden** in preview page.

I just wanted to know, if there is a direct method in library which can be called without adding a default hidden chart in preview page.

**Comment by martynasma** [comment]
Hm, good point.

How about instantiating a standalone `Export` instance, and grabbing pdfmake from there?

```TypeSript
const exp = new am4core.Export();
Promise.all([
  exp.pdfmake,
  .....
])
```

**Comment by mahesh-chotrani** [comment]
Thank you @martynasma ! That worked. :)
