### ISSUE TITLE
Can't reproduce the Animated XY Bubble Timeline chart using my data

### ISSUE THREAD

**Issue by RSchneider94** [amcharts/amcharts4#3393]
**Question**
I'm trying to reproduce the [following chart from demo](https://www.amcharts.com/demos/animated-xy-bubble-timeline-chart/). I've just copied the chart code and readapted to my use case. Unfortunately, I can't achieve the same result. For example, I have the following problems:

- there's no colors inside each color series
- the bubbles are overlapping
- thus even that I have 2 years in the data (for the `first` and `last`) the animation doesn't seems to be changing

I've created a Sandbox in order to show what exactly my code looks like: https://codesandbox.io/s/friendly-moser-9tnzs

Appreciate the help! 😄

**Comment by RSchneider94** [comment]
Any updates on this? Thanks!!

**Comment by RSchneider94** [comment]
Still waiting for some help, in case someone had this problem also.

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
