### ISSUE TITLE
Is it possible to add an animation when the chart data is updated?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3395]
I have an event that update a piechart data. I want to add an animation when it occurs. Is it possible?

**Comment by martynasma** [comment]
Please refer to [this tutorial](https://www.amcharts.com/docs/v4/concepts/data/#Dynamic_updates) especially the "Manipulating existing data points" chapter.

**Comment by gagigante** [comment]
I tried `chart.invalidateRawData();` but it didn't work for piechart

```
updateChartData(data) {
   this.drillDownChart.data = data;

   this.drillDownChart.invalidateRawData();
}
```

**Comment by martynasma** [comment]
If you set `data` it invalidates all of the data, so the `invalidateRawData()` call is completely useless in this case.

If you need to use it (and animate to new values), you will need to modify existing data points, not replace them, e.g.:

```JavaScript
chart.data[1]["research"] = 123;
chart.invalidateData();
```

**Comment by gagigante** [comment]
Can I triger an animation after replace all data set?

**Comment by martynasma** [comment]
You may call series' `appear()` method:

```
series.appear();
```

**Comment by gagigante** [comment]
it works for me. Thank you so much!
