### ISSUE TITLE
Make Tooltips not overlap in Scatterplot

### ISSUE THREAD

**Issue by thespacedeck** [amcharts/amcharts4#3397]
Good day,

I trust you're well.

I'm in need of some help to arrange tooltips to NOT overlap AND always be visible on a scatterplot chart.

The documentation reference: https://www.amcharts.com/docs/v4/concepts/tooltips/#Making_cursor_arrange_tooltips

A sample implementation showing that the tooltipText is placed on the series is not providing the needed effect: https://codepen.io/whoweez/pen/NWqoMvm

Attached is the needed result.

I appreciate your guidance and time.

<img width="1038" alt="needed result" src="https://user-images.githubusercontent.com/67354103/112102593-2b7cbf00-8bb1-11eb-883f-2f2fd6972de1.png">

**Comment by martynasma** [comment]
Try [this tutorial](https://www.amcharts.com/docs/v4/tutorials/multiple-cursor-tooltips-on-scatter-chart/).

**Comment by thespacedeck** [comment]
Hi @martynasma,

Thanks for the tip. I'm definitely closer and have tried the example with some others as well. 

Please see https://codepen.io/whoweez/pen/ExZyzKN

Now the documentation says that:
"everything changes when we enable an XYCursor on our chart.......
A lot of tooltips might spell trouble if you have a lot of series with similar values: they would overlap." <- this is exactly my problem...

The solution according to the documentation is: (see https://www.amcharts.com/docs/v4/concepts/tooltips/#Charts_with_XYCursor)
"The solution is to set tooltipText not directly on series elements (in this case columns) but directly on series:"

Now if you look at the pen, the first series has the tooltip placed on the 'bullet' element (i.e. bullet.tooltipText - ln 114). The second series has the tooltip placed on the series itself (i.e. series2.tooltipText - ln 130). The problem is that there is no tooltip shown? Either I don't understand what the docs are trying to explain or there might be a bug setting a tooltipText directly on a series?

Let me know your thoughts.

Thanks again for replying!

**Comment by martynasma** [comment]
Oh, so you want all tooltips to be shown all the time, but also no overlap with each other?

That is not possible, I'm afraid :(

**Comment by thespacedeck** [comment]
Hi there community and @martynasma,

Thanks for the feedback so far. Since it seems this is not possible. I'll try my best to contribute by adding such functionality for anyone out there that may be looking for something similar :)

@martynasma, has pointed me in the direction of XYChart class which handles the vertical aspect of the tooltip:  sortSeriesTooltips (https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/types/XYChart.ts#L1376)

I'm a bit new to amcharts, but looking at my pen below, ln 115/116 is the same thing. series.bullets is an array that holds the instance of a bullet type. 
```
chart.series.values[0].bullets.values[0].tooltipX = 20
bullet.tooltipX = 10
```
=> https://codepen.io/whoweez/pen/ExZyzKN

My question is that sortSeriesTooltips receives an array called seriesPoints. Chart.seriesPoints = [] at any given time. In the end, I'm not too sure how to get to a place where I can iterate through each tooltip (via seriesPoints) to adjust the placement.
Is there a method/property in some other base class that I've missed that holds the seriesPoints?

Much appreciated :)
