### ISSUE TITLE
The live data chart with multiple series stop moving to the left

### ISSUE THREAD

**Issue by OGudkov-TechHub** [amcharts/amcharts4#3398]
Hi,

I'm trying to use the live data chart in the following scenario:
There might be one or more series of live data, which comes in a predefined interval. However, it may happen that values for a series stops to come, while they still comes for other series. In this case, the series, without new values won't continue it's line, of course. The whole chart renders properly until this series left the chart area. After the next tick of incoming values the chart does stop moving to the left, and it's date axis starting to "add" date points. With every next tick the remaining series starts rendering further and further from the values axis, because they still have strict number of points while date axis covers bigger and bigger time period.

Here is a link to the codepen where I've tried to simulated that situation: [https://codepen.io/oleggood/pen/QWGRQzG](https://codepen.io/oleggood/pen/QWGRQzG). After initial values assignment, the series 'value1' gets 5 new values and then only 'value' will receive new values.

I've also noticed, that as soon as new values comes for that stopped series - chart will be instantly refreshed and will be rendered in the normal way.

So now the question: how to avoid/resolve that behaviour? I've seen an advice somewhere here to addData function directly on the series. I've tried it before I've met the described problem, and, unfortunately, I wasn't really satisfied with the result: the chart's movement wasn't smooth and series sometimes "jumped out" of the available chart area. But maybe be I didn't implement it properly, of course.

Thanks in advance!

**Comment by martynasma** [comment]
This should work nicely if you would add data directly to each series.

Here's a version of your CodePen that does that. Hope it helps you refactor your own setups that way.

https://codepen.io/team/amcharts/pen/a8c5e6cf853f996263d73014a73ac51e?editors=1010

**Comment by OGudkov-TechHub** [comment]
Hi! First of all - thank you very much for the response. Yes, this approach does work, but I already mentioned in my original post, that I wasn't satisfied with the result. I think it's better to see once, so I've captured my browser window with it:

https://user-images.githubusercontent.com/28897173/112842032-d0afff80-90a9-11eb-97ab-7d42407817e9.mp4

I hope you can see there, how chart is "jumping" back and forth. This is exactly your version of my chart, but I just set 'visits1Limit' to 5000000 and has changed data interval back to 1 sec. If you know how to resolve that rendering behavior - I would be really glad to hear that!

Here are more details about my use case(s). Let's assume there 4 values incoming every N seconds. These values can be shown as is, or can be grouped in the various ways, depending on some settings, so instead of 4 series, there might 3, 2 or even 1. And, potentially, there might be a small gap between incoming values, while all four will have the same timestamp. All values comes in a live manner and separately from each other (I mean each value sent via its own payload). All that means I have to check if there is a single point for the received timestamp, get it and add received value or create a new point and add it to series/chart, and then - invalidate series/chart data to see changes. But doing that directly on the chart's data is more performant than on a single series data. Or am I wrong with this assumption?

**Comment by martynasma** [comment]
Unfortunately, there is no way to disable this "jumping" with animations on, besides disabling axis animations altogether.

```JavaScript
valueAxis.rangeChangeDuration = 0;
```

**Comment by OGudkov-TechHub** [comment]
Ok, it's not perfect, but it looks better with this option.

However, can I return back to my original question, please? The behaviour I described there is a bug or done by design? Could it changed/fixed in the foreseen future?

**Comment by OGudkov-TechHub** [comment]
Well, too bad... I still consider that this is a bug.

But in any case: thank you very much for the help! I appreciate that.
