### ISSUE TITLE
How do I keep the legend markers from graying out upon toggling or clicking an icon to hide a series

### ISSUE THREAD

**Issue by ava8tor** [amcharts/amcharts4#3399]
https://jsfiddle.net/ava8tor/8bvp7sLu/3/

When hiding or toggling off a series in a chart upon clicking on a legend marker, the icon will normally gray out as a result. Currently I'm trying to customize how the legend icon and label looks when it is disabled. The example above in AMchart's documentation shows how to place a strike through on the labeling and I know how to change the coloring or fill of the icons when disabled via the active state adapter with the following:

```
let as = legend.markers.template.children.getIndex(0).states.getKey("active");
as.adapter.add("fill", function (fill, target) {
     return am4core.color("color hex code");
}
```

In this case when toggled or disabled, I want to strikethrough the label text of the legend without the color of the icon changing or graying out. However, while I've tried the above function, I am unable to determine via code which icon for the respective series is being toggled as the target variable in the parameter only gives a general info on the active state but not on the series itself. 

I've also tried using the fill adapter function for the legend marker itself `via:`

```
let marker: any = legend.markers.template.children.getIndex(0);
marker.adapter.add("fill", function (fill, target) {
if(target.dataItem && target.dataItem.dataContext && target.dataItem.dataContext.dummyData) {
                return am4core.color(target.dataItem.dataContext.dummyData.colorFill);
            }
} return fill;
```

However, the code ignores this adapter function despite it being called when a legend icon is toggled.

**Comment by martynasma** [comment]
When you toggle a legend item, it sets `active` state on the marker, which subsequently sets that state on its children.

By default this state has gray fill.

I suppose the easiest way would be to just prevent marker from setting state on its children:

```JavaScript
chart.legend.markers.template.setStateOnChildren = false;
```

**Comment by ava8tor** [comment]
Thank you, this appears to have solve the issue.
