### ISSUE TITLE
Is it possible to set active state for Treemap item on load?

### ISSUE THREAD

**Issue by ElvisCaballero** [amcharts/amcharts4#3401]
**Problem**
I'm trying to set active state on Treemap item on chart load but with no success.

**Additional context**
Here's my Treemap attempt:
https://codepen.io/elviscaballero/pen/abpOEra

Thanks in advance.

**Comment by martynasma** [comment]
Try this insetad:

```JavaScript
const setActive = (name) => {
  level1_series.clones.each((series) => {
    series.dataItems.each((dataItem) => {
      if (dataItem.dataContext.name == name) {
        dataItem.column.isActive = true;
      }
    });
  })
};
```

TreeMap creates a lot of series, so we need to search in all of them.

**Comment by ElvisCaballero** [comment]
I see, for certain I wouldn't figured it out!
Thank you @martynasma for solution!
