### ISSUE TITLE
How can I do a horizontal scrollable legend?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3402]
I have a PieChart with lots of slices and I want to use the scrollable legend feature, but it doesn't seem to work horizontally

Is it possible? Can I use it with responsive features to change between vertical/horizontal orientation?

**Comment by martynasma** [comment]
No, I'm afraid horizontal scroll for Legend is not supported.

The only way would be to have an [external legend](https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/), and have it scroll using CSS means.
