### ISSUE TITLE
Renaming the amcharts.csv (or other) file downloads

### ISSUE THREAD

**Issue by nzpiquet** [amcharts/amcharts4#3405]
I have searched for similar questions on GitHub and amCharts documentation website but can't find a way to configure the name of the filename download for all formats.   Rather than amcharts.csv, amcharts(1).csv or amcharts.png etc, it would help users if the filename carried some context.  e.g: WorldPopnByCountry.csv.

I would hope that there is a simple configuration attribute that can be added in javascript.

**Comment by xorspark** [comment]
You can use [`filePrefix`](https://www.amcharts.com/docs/v4/reference/export/#filePrefix_property) for this purpose.

```
chart.exporting.filePrefix = 'WorldPopnByCountry';
```

**Comment by nzpiquet** [comment]
Found elsewhere:
`var chart = AmCharts.makeChart("chartdiv", {
  // ...
  "export": {
    "enabled": true,
    "fileName": "your new file name without extension", 
    // ...
  }
});`
