### ISSUE TITLE
Chart does not reclaim space after disabling stacked yAxis

### ISSUE THREAD

**Issue by M-Wildgruber** [amcharts/amcharts4#3407]
In order to hide an axis, the [documentation]( https://www.amcharts.com/docs/v4/tutorials/auto-hide-value-axes/#Turning_off_an_axis) says to set it to disabled and also that this will reclaim the space for the chart. 

For stacked y-axes however, the space is not reclaimed (red marks show the space that was occupied by the axis before): 

1st sample: lower axis disabled (upper axis stays, but a gap remains between the x-axis and the upper axis)
![image](https://user-images.githubusercontent.com/26223821/112721775-1d5ad580-8f06-11eb-8d1a-a0957f2865a0.png)

2nd sample: upper axis disabled (lower axis is moved up, but does not occupy full height):
![image](https://user-images.githubusercontent.com/26223821/112799720-084d8600-906f-11eb-872d-fd17e87b4e47.png)

This [pen](https://codepen.io/m-wildgruber/pen/jOyqbyZ) is based on a [demo](https://www.amcharts.com/demos/vertically-stacked-axes-chart/) by amCharts and demonstrates the issue. In the last line, the axis is disabled, but there remains a gap between the upper part of the chart and the x-axis. 

Are there any additional steps we need to take to remove the gap and reclaim the space?
Thanks for checking the behavior.

**Comment by M-Wildgruber** [comment]
I was able to remove the gap and reclaim the space for the remaining axes by setting the height of the disabled axis to 0. If I enable the axis again, how can I reset the height so that it is measured automatically again?

**Comment by martynasma** [comment]
How about setting its `height` to non-zero?

```JavaScript
valueAxis2.height = am4core.percent(50);
```

**Comment by M-Wildgruber** [comment]
@martynasma Thank you, that did the trick. I tried setting it to absolute values and also used the percentHeight property, but this did not show the expected result.
