### ISSUE TITLE
Axis label values are convert into percentage can you help me out

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#3408]
y Axis values all need to convert into percentage 
for example below chart i want to show in percentage how can show with same data.
https://www.amcharts.com/demos/3d-column-chart/

**Comment by Mahisandy** [comment]
![image](https://user-images.githubusercontent.com/54665162/112828506-69944a00-90ad-11eb-819d-e5a6c7172154.png)
when i tried this only percentage sign is come in front of the text its not converting into percentage 
4025   ÷   100 =40.25 1st value should be this

**Comment by martynasma** [comment]
You can format your number labels using [NumberFormatter](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/), e.g.:

```
chart.numberFormatter.numberFormat = "#%";
```

That being said, I don't see how 4025 can become 40.25%. It's the other way around.

So you will need to update your data value accordingly.
