### ISSUE TITLE
Color Set Step Option Saturation doesn't have any effect

### ISSUE THREAD

**Issue by cam-m** [amcharts/amcharts4#3409]
**Bug description**
Setting `ColorSet.stepOption.saturation` has no visible effect on the color value. By contrast setting others, lighten for example, works fine.

[Pen](https://codepen.io/cam-m/pen/poRbmev)

Angular, Typescript

**Comment by martynasma** [comment]
It's by design. Steps do not support saturation option, which was included in the docs by mistake.

We're going to remove it. Sorry for the inconvenience.

**Comment by cam-m** [comment]
All good, thanks @martynasma!

Since its a doc update could I also suggest adding explanation of each of the valid options in the Interface doco?  Something to distinguish the lightness, lighten and brightness options would be great :)

Cheers!

Cam

**Comment by cam-m** [comment]
I see the doco is already updated - nice!

**Comment by martynasma** [comment]
> Since its a doc update could I also suggest adding explanation of each of the valid options in the Interface doco? Something to distinguish the lightness, lighten and brightness options would be great :)

Adding to the TODO list ;) Thanks.
