### ISSUE TITLE
tensionX/tensionY is ignored whenever dasharray property is applied via propertyFields

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#341]
![image](https://user-images.githubusercontent.com/1458520/45367894-edb77c80-b5ea-11e8-9604-59dc89e57f9c.png)

Example:
https://codepen.io/team/amcharts/pen/a787870f4117a5e0ff51b8b19cd336e9/?editors=0010

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.51](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.51).

## [4.0.0-beta.51] - 2018-09-13

### Changed
- Changed `Label.renderingFrequency` to `2`, for better performance.

### Fixed
- Performance tweaking.
- `DateAxis.baseInterval` was ignored in JSON-based configs.
- `"hoverActive"` state was not always being correctly applied.
- Better handling of cursor zoom and pan when outside chart area.
- Fixed occasional error when formatting dates or numbers.
- Line chart starts new segement only if properties (like `stroke`, `fill`, `strokeDashArray`, etc.) in data have changed. It used to start new segment if properties in data were defined resulting in reduced performance and disabled smoothed lines.
- Labels were not updating their position if their `fontSize` changed.
- `Sprite.nonScalingStroke = true` was ignored if set after `Sprite.strokeWidth`.
- `LineSeries` could leave some garbage lines while zooming.
- `ColumnSeries` could leave some garbage columns while zooming.
- `DateAxis` with one date only in chart data was not rendered properly.
- The chart was not zooming out after data validation.
- Added `ghostLabel` to `Axis` which is an invisible label and it helps to avoid unwanted changes of axis widht/height when the scale changes, e.g. on zoom.
- `zoomToMapObject`, if used with `MapPolygon` and custom `zoomLevel` was not working properly.
- `"hidden"` event of Series was called on initial chart initialization.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by ZakTreister** [comment]
Hi,

I'm having this issue

![image](https://user-images.githubusercontent.com/43063428/71640402-04775c00-2c92-11ea-8f01-2dca7dafb072.png)

As you can see once the propertyFields kick in, I lose my tensionX.

I'm loading amcharts 4 with the CDN. Is this why I'm not getting the fix?
