### ISSUE TITLE
NavigationBar Links styling

### ISSUE THREAD

**Issue by QadiymStewart** [amcharts/amcharts4#3411]
Trying to style the Treemap navigationbar links 
![image](https://user-images.githubusercontent.com/28968495/112888052-e3bed180-90a1-11eb-8f4d-c48dec31e543.png)

But the background isn't being sized correctly 
![image](https://user-images.githubusercontent.com/28968495/112888251-208ac880-90a2-11eb-98cc-34e9aa938222.png)

Json Configs
{
  "id": "4cea7199-041d-4710-9e64-af867c6f9659",
  "titles": {
    "values": [
      {
        "type": "Label",
        "visible": false,
        "text": "My Single Series Chart",
        "html": "My Single Series Chart"
      }
    ]
  },
  "legend": {
    "position": "bottom",
    "visible": true,
    "contentAlign": "right",
    "truncate": false,
    "wrap": false
  },
  "type": "TreeMap",
  "maxLevels": 1,
  "data": [
    {
      "Name": "Pay_4",
      "Value": 10.793313738689498,
      "Children": [
        {
          "Name": "Vendor_10",
          "Value": 2.165965345839336
        },
        {
          "Name": "Vendor_7",
          "Value": 1.9437652086312227
        },
        {
          "Name": "Vendor_9",
          "Value": 1.9369966950485937
        },
        {
          "Name": "Vendor_5",
          "Value": 1.2753056521467163
        },
        {
          "Name": "Vendor_6",
          "Value": 1.0742160491433907
        },
        {
          "Name": "Vendor_4",
          "Value": 1.033203153379533
        },
        {
          "Name": "Vendor_8",
          "Value": 0.686452538306792
        },
        {
          "Name": "Vendor_3",
          "Value": 0.6774090961939147
        }
      ]
    },
    {
      "Name": "Pay_5",
      "Value": 9.590769107710464,
      "Children": [
        {
          "Name": "Vendor_8",
          "Value": 2.47596215047605
        },
        {
          "Name": "Vendor_10",
          "Value": 1.5864945071211638
        },
        {
          "Name": "Vendor_5",
          "Value": 1.3068584832919279
        },
        {
          "Name": "Vendor_9",
          "Value": 1.2824910645728667
        },
        {
          "Name": "Vendor_4",
          "Value": 0.984666816697887
        },
        {
          "Name": "Vendor_3",
          "Value": 0.7794241068314646
        },
        {
          "Name": "Vendor_7",
          "Value": 0.6638750428265642
        },
        {
          "Name": "Vendor_6",
          "Value": 0.5109969358925398
        }
      ]
    },
    {
      "Name": "Pay_3",
      "Value": 3.536659267061919,
      "Children": [
        {
          "Name": "Vendor_9",
          "Value": 1.4158632183554212
        },
        {
          "Name": "Vendor_7",
          "Value": 0.6827113080121261
        },
        {
          "Name": "Vendor_5",
          "Value": 0.6794388019837772
        },
        {
          "Name": "Vendor_8",
          "Value": 0.3484617899514045
        },
        {
          "Name": "Vendor_6",
          "Value": 0.19657671964960777
        },
        {
          "Name": "Vendor_3",
          "Value": 0.12539225864038525
        },
        {
          "Name": "Vendor_10",
          "Value": 0.04729987077696902
        },
        {
          "Name": "Vendor_4",
          "Value": 0.04091529969222817
        }
      ]
    }
  ],
  "dataFields": {
    "hidden": false,
    "value": "Value",
    "children": "Children",
    "name": "Name"
  },
  "colors": {
    "list": [
      "#8676FF",
      "#B6ADFF",
      "#CFC8FF",
      "#E7E4FF",
      "#DBDFF1",
      "#383874",
      "#8181A3",
      "#A1A8C2",
      "#20203F"
    ]
  },
  "navigationBar": {
    "links": {
      "fill": "#383874",
      "fontFamily": "Poppins",
      "fontSize": 20,
      "fontWeight": "600",
      "background": {
        "fill": "#EFF0F6",
        "paddingTop": 12,
        "paddingBottom": 12,
        "paddingLeft": 12,
        "paddingRight": 12,
        "cornerRadiusTopLeft": 10,
        "cornerRadiusTopRight": 10,
        "cornerRadiusBottomLeft": 10,
        "cornerRadiusBottomRight": 10,
        "type": "RoundedRectangle",
      }
    },
    "activeLink": {
      "fill": "#5F2EEA",
      "fontFamily": "Poppins",
      "fontSize": 20,
      "fontWeight": "600",
      "background": {
        "fill": "#FFFFFF",
        "stroke": "#5F2EEA",
        "strokeWidth": 2,
        "strokeOpacity": 1,
        "paddingTop": 12,
        "paddingBottom": 12,
        "paddingLeft": 12,
        "paddingRight": 12,
        "cornerRadiusTopLeft": 10,
        "cornerRadiusTopRight": 10,
        "cornerRadiusBottomLeft": 10,
        "cornerRadiusBottomRight": 10,
        "type": "RoundedRectangle"
      }
    }
  },
  "fontSize": 11,
  "homeText": "HomeTextExample"
}

**Comment by martynasma** [comment]
Try something like this:

```JavaScript
styleLink(chart.navigationBar.links.template);
styleLink(chart.navigationBar.activeLink);

function styleLink(target) {
  target.background = new am4core.RoundedRectangle();
  target.background.cornerRadius(5, 5, 5, 5);
  target.background.fillOpacity = 1;
  target.background.fill = am4core.color("#fff");
  target.background.stroke = am4core.color("#399");
  target.background.strokeWidth = 3;
  target.background.strokeOpacity = 0.2;
  target.padding(5, 5, 5, 5);
}
```

https://codepen.io/team/amcharts/pen/540a5ca7478ea5843c944498e74ad307?editors=0010

This translates into JSON config, well too. Just make sure you're applying those settings to `background` rather than directly to link.

**Comment by QadiymStewart** [comment]
Thanks
