### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by stefanwilliam96** [amcharts/amcharts4#3413]
![231231231](https://user-images.githubusercontent.com/32946809/113089352-af6a2300-9211-11eb-98b5-360ebfd4baf4.PNG)

How to give an enter after every chart ? So it looks like this...

Chart 1
| <enter>
| <enter>
Chart 2
| <enter>
| <enter>
Chart 3

**Comment by martynasma** [comment]
Try setting `layout` for your container:

```
container.layout = "vertical";
```

Of course, you will have to set proper height of your container so that all the charts fit.
