### ISSUE TITLE
How to produce layered column chart with multiple category axis

### ISSUE THREAD

**Issue by faizal-a** [amcharts/amcharts4#3414]
**Question**

I manage to plot the Layered Column chart using [Amcharts](https://www.amcharts.com/demos/layered-column-chart/) without any issue and work perfectly. In order to make it a more meaningful chart, I would need to develop this type of chart contains:

Category axis : Year Quarter value --> Site --> Actual vs Goal
Value axis : Actual & Goal value

![image](https://user-images.githubusercontent.com/42432122/113115521-18b45b00-923f-11eb-8cfd-d1285287a8ca.png)

And this is the JSON data to feed the chart;

![image](https://user-images.githubusercontent.com/42432122/113117794-6205aa00-9241-11eb-8c47-855f2d84e515.png)

Would it be possible to achieve this using Amcharts 4? Appreciate if anyone could advise how to get it done. Thanks!

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data what you have so far on CodePen/jsFiddle?

**Comment by faizal-a** [comment]
This will be the desired output that I'm looking for. The secondary axis should appear with a proper label and in a real case, the secondary axis item may have up to 5 different categories to be populated in the chart. Is it possible to achieve it?

And this is the link for the workaround chart I have done so far in [jsFiddle](https://jsfiddle.net/Faizal_a/Lvgsc64q/29/).

![image](https://user-images.githubusercontent.com/42432122/113321994-be062680-9346-11eb-879c-6c5c13867eb2.png)

**Comment by martynasma** [comment]
I don't think you need a secondary axis for that. You can use ranges to group labels:

https://www.amcharts.com/docs/v4/tutorials/grouping-axis-labels-using-ranges/
