### ISSUE TITLE
Drag a city on Map and save a new location

### ISSUE THREAD

**Issue by barwalker** [amcharts/amcharts4#3415]
**Question**
I'm following the Animations along lines example, and try to add a dragging feature like below:
```...
var city = cities.mapImages.template.createChild(am4core.Circle);
...
function addCity(coords, title) {
      let city = cities.mapImages.create();
      city.events.on("dragstop", (e)=>{
                console.log(e);
                console.log(e.target.dataItem);
            });
      return city;
}
...
``` 
Please help me get a new geo location (latitude, longitude) when stopping.
Thanks.

**Comment by martynasma** [comment]
You can find out new coordinates on `dragstop` event like this:

```JavaScript
var newLatitude = chart.seriesPointToGeo(e.target).latitude;
var newLongitude = chart.seriesPointToGeo(e.target).longitude;
```

**Comment by barwalker** [comment]
And can limit the drag&drop zone within a map area, not the whole space of SVG section?

**Comment by martynasma** [comment]
> And can limit the drag&drop zone within a map area, not the whole space of SVG section?

Nope, there's no setting for that :/
