### ISSUE TITLE
[HELP] - How to set the highlighted axis-area as a legend or a toggle button?

### ISSUE THREAD

**Issue by jet-c-21** [amcharts/amcharts4#3416]
### [my code pen](https://codepen.io/puff-vayne/pen/GRrrzRr)
![image](https://user-images.githubusercontent.com/67193495/113263000-d4d75980-9303-11eb-8070-84472d779ad5.png)

### my purpose
![image](https://user-images.githubusercontent.com/67193495/113263068-ec164700-9303-11eb-8dfc-f033d63a90dc.png)

**Comment by martynasma** [comment]
I would just add "empty" series, to the chart called "Weekend" without any actual data, so it does not show on chart, but will have a legend item.

**Comment by jet-c-21** [comment]
but how can the empty series link to the highlighted dateAxis.range()?

**Comment by martynasma** [comment]
Do you mean you want the legend to toggle weekend highlights?

**Comment by jet-c-21** [comment]
Yes!

**Comment by martynasma** [comment]
Something like this:

```JavaScript
  let rangeSeries = ha1.series.push(new am4charts.LineSeries());
  rangeSeries.dataFields.dateX = 'date';
  rangeSeries.dataFields.valueY = 'dummy';
  rangeSeries.name = "Weekend";
  rangeSeries.stroke = am4core.color('#396478');
  rangeSeries.strokeWidth = 2;
  
  rangeSeries.events.on("hidden", function() {
    ha1DateAxis.axisRanges.each(function(range) {
      range.hide();
    })
  })
  
  rangeSeries.events.on("shown", function() {
    ha1DateAxis.axisRanges.each(function(range) {
      range.show();
    })
  })
```

https://codepen.io/team/amcharts/pen/2d706df7a7981fde792dd58fcb2202a3?editors=0010

**Comment by jet-c-21** [comment]
Thanks! it is actually what I want!

**Comment by iSkYrIsE** [comment]
Hello guys, I wanna ask something about this you solved almost 2 years ago. 
My question is if it's possible to do this not with a date axis, but if this date axis was actually a Value axis.

Thank you!
