### ISSUE TITLE
Help to draw a computer network

### ISSUE THREAD

**Issue by ithoc** [amcharts/amcharts4#3417]
I try to create a computer networking map with ability to:
- show 2-ways link between each node.
- a node can be dragged freely and its current location can be saved.
Sample data:
```
link: [{"source":"node1", "target":"node2"},{"source":"node2", "target":"node1}]
node: [{"id":"node1","x":..., "y":...}, {"id":"node2","x":..., "y":...}]
```
I tried a Force-directed network chart, however it cannot show 2 links between nodes. Only a Map chart can be used to draw a 2-ways link but it cannot save new location after dragged.

Please suggest me to draw this kind of topology. Thanks.

**Comment by martynasma** [comment]
I'm afraid we do not have a chart suitable for that kind of diagram. Sorry.

**Comment by ithoc** [comment]
So it's no way to show 2 links between nodes in Force-directed network chart?
Eg: A=B and A-B

**Comment by martynasma** [comment]
> So it's no way to show 2 links between nodes in Force-directed network chart?
Eg: A=B and A-B

No, I'm afraid.
