### ISSUE TITLE
XYChart: autoscaling behaviour associated with x-axis zooming

### ISSUE THREAD

**Issue by zoony** [amcharts/amcharts4#3418]
Expect autoscaling of XYChart y-min/max values after zoom in event (depending on the data within the new x-range).

### Behaviour

- X ValueAxis
    - y-range UNCHANGED
    - the series bullets do NOT appear when display x-range < bullet display threshold
- X DateAxis & X CategoryAxis
    - y-range changes BUT with some non-zero extraMax/extraMin even if explicitly set to zero
    - series bullets DO appear when display x-range < bullet display threshold

### Setup

- A single series in an XYChart tested using each of the following axes combinations:
    - one Y ValueAxis & one X ValueAxis
    - one Y ValueAxis & one X DateAxis
    - one Y ValueAxis & one X CategoryAxis

### Notes

- I've set up a demo page comparing the 3 types of x-axes with the same dataset.
- There is a zoom in button to set up the conditions to demonstrate the above behaviour.

### Demo page only

[https://typescript-amchart-autoscale-on-zoom-27gvrz.stackblitz.io/](https://typescript-amchart-autoscale-on-zoom-27gvrz.stackblitz.io/)

### Demo source + output page

[https://stackblitz.com/edit/typescript-amchart-autoscale-on-zoom-27gvrz](https://stackblitz.com/edit/typescript-amchart-autoscale-on-zoom-27gvrz)

### Feature request (assuming I haven't just missed it in the docs)

- A flag to toggle autoscaling on/off for a chart

**Comment by martynasma** [comment]
I'm sorry, is there a question/bug, or it's a feature request to disable auto-scaling of the Y axis?

You can do that by disabling `selectionextremeschanged` event for all series on the chart:

```JavaScript
series.events.disableType("selectionextremeschanged");
```
