### ISSUE TITLE
Opacity setting is ignored after slice was hovered in PieChart(3D)

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#342]
Example:
https://codepen.io/dmsmaxim/pen/GXxWOP

When you hover a slice it's **opacity** becomes "1" and don't restore it's original value which was set in the `series.slices.template.opacity` even when the cursor leaves a slice.

This also applies to the PieChart.

**Comment by notacouch** [comment]
Yep. That's `SpriteState` for you. Please check out our guide on States:
https://www.amcharts.com/docs/v4/concepts/states/

Let me try and walk through what's going on here.

With only `series.slices.template.opacity = 0.3;`, the `opacity` is only being set on the newly-created slices, not on any of their states. When you hover over a slice, the slice is switched to its hover state (if one exists), once you're done hovering, it will switch the state of the slice to its default state (side note: this has a shortcut, `slice.defaultState`).

If we set the `opacity` of the default state to `0.3`, too,...
```javascript
series.slices.template.defaultState.properties.opacity = 0.3;
```
...you'll find when you hover over a slice it remains at `0.3` as well.

If you want that to change, you'll need to create a hover state and adjust its opacity. (The `'hover'` key for states is reserved for hover behavior, but needs to be created):
```javascript
series.slices.template.states.create('hover').properties.opacity = 1;
```

Now when you hover over a slice you'll find a slice going from 30% transparent, to fully opaque, and back.

You may also want to adjust the active state for when a slice is clicked (in this case, the state already exists):
```javascript
series.slices.template.states.getKey('active').properties.opacity = 1;
```

Now activating a slice will also render it fully opaque.

Here's a demo with all that thrown together:
https://codepen.io/team/amcharts/pen/2e851d068d0ef1eb038fa1ad3413b10b/

Let us know if this was helpful.

**Comment by dmsmaxim** [comment]
Thanks, this works.
But what if want to change opacity in the future.

Example:
https://codepen.io/dmsmaxim/pen/MqGgYp

After 5s I do this:
```
series.slices.template.opacity = 1;
series.slices.template.defaultState.properties.opacity = 1; 
```
Also I set `series.slices.template.applyOnClones = true` so changes in the template would apply to slices.
Opacity applies to clones, but `defaultState.properties.opacity` don't. So when you hover some slice again it's opacity becomes 0.3, as it was initially.

**Comment by martynasma** [comment]
Propagating state properties to clones is not yet currently implemented or possible, save iterating through all the clones and copying changes over. E.g.:

```
series.slices.template.opacity = 1;
series.slices.template.defaultState.properties.opacity = 1; 
serles.slices.template.clones.each(function(clone) {
  clone.defaultState.properties.opacity = series.slices.template.defaultState.properties.opacity;
});
```

We might introduce a method to do that automatically in the future, though.

Here's an open enhancement issue for that: #349

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
