### ISSUE TITLE
XYChart: negative y data values & extraMin behaviour 

### ISSUE THREAD

**Issue by zoony** [amcharts/amcharts4#3420]
Displaying a dataset containing some negative values in an XYChart with a ValueAxis,  DateAxis or a CategoryAxis as the x-axis.

### Behaviour

- Same for each of the 3 x-axis types.
- Non-zero difference between data y-min and axis y-min using
    - default y-axis extraMin/extraMax values
    - y-axis extraMin/extraMax explicitly set to zero.
- Difference between data y-max and axis y-max is as expected (zero)

### Setup

- A single series in an XYChart tested using each of the following axes combinations:
    - one Y ValueAxis & one X ValueAxis
    - one Y ValueAxis & one X DateAxis
    - one Y ValueAxis & one X CategoryAxis

### Notes

- I've set up a demo page comparing the 3 types of x-axes with the same dataset.
- There is a drop down list of options to change all negative y values to zero or larger negative values.

### Demo page only

[https://typescript-amchart-autoscale-on-zoom-27gvrz.stackblitz.io/](https://typescript-amchart-autoscale-on-zoom-27gvrz.stackblitz.io/)

### Demo source + output page

[https://stackblitz.com/edit/typescript-amchart-autoscale-on-zoom-27gvrz](https://stackblitz.com/edit/typescript-amchart-autoscale-on-zoom-27gvrz)

**Comment by martynasma** [comment]
I'm sorry, is there a question or an issue you'd like to report?

**Comment by zoony** [comment]
Bug

When the dataset contains some negative values, there can be a significant difference between data y-min and axis y-min using a ValueAxis,  DateAxis or a CategoryAxis as the x-axis. This is unaffected by explicitly setting extraMin to zero
