### ISSUE TITLE
XYChart: Trying to display pairs of opposing axes

### ISSUE THREAD

**Issue by zoony** [amcharts/amcharts4#3421]
Displaying pairs of opposite axes (bottom & top and left & right) with an XYChart.

### Setup

- A single series in an XYChart tested using each of following axes combinations:
    - a Y ValueAxis pair (left & right) & an X ValueAxis pair (bottom & top)
    - a Y ValueAxis pair (left & right) & an X DateAxis pair (bottom & top)
    - a Y ValueAxis pair (left & right) & an X CategoryAxis pair (bottom & top)

### Behaviour

- The opposite axis of:
    - an X ValueAxis pair,
    - an X DateAxis pair and
    - a Y ValueAxis pair
        - no ticks or labels displayed
        - empty space where labels expected
- The opposite axis of:
    - an X CategoryAxis pair
        - axis ticks & labels displayed as expected
- Zoom in for
    - an  X ValueAxis pair &
    - an X DateAxis pair
        - an immediate reset to full x-range occurs after zooming in.
        - introduced in v4.10.14
- Zoom in for
    - an X CategoryAxis pair
        - works as expected

### Notes

- I've set up a demo page comparing the 3 types of x-axes with the same dataset.
- The page includes
    - a checkbox to toggle display of 2nd opposite x & y-axes.
    - a zoom in button which demonstrates the reset behaviour when the opposite axes are used

### Demo page only

[https://typescript-amchart-autoscale-on-zoom-27gvrz.stackblitz.io/](https://typescript-amchart-autoscale-on-zoom-27gvrz.stackblitz.io/)

### Demo source + output page

[https://stackblitz.com/edit/typescript-amchart-autoscale-on-zoom-27gvrz](https://stackblitz.com/edit/typescript-amchart-autoscale-on-zoom-27gvrz)

**Comment by martynasma** [comment]
I'm sorry, is there a question or an issue you're reporting?

**Comment by zoony** [comment]
Bugs

When attempting to display pairs of opposing axes (bottom & top and left & right) the second axis (top & right) does not appear for any of the following: X & Y ValueAxis and X DateAxis.

Additionally, after amCharts v4.10.15, when an XYChart is set up to display the pairs of opposite axes for ValueAxis & DateAxis x-axes cases, zooming in results in immediate resetting of the x-range to the full range.
