### ISSUE TITLE
Is it safe for upgrading d3-selection to version 2.0.0?

### ISSUE THREAD

**Issue by barwalker** [amcharts/amcharts4#3422]
I found the latest version 4.10.7 is using "venn.js": "^0.2.20" which combines with d3-selection:
```
│ ├─┬ venn.js@0.2.20
│ │ ├── d3-selection@1.4.2

```
This d3-selection version is old and conflicting with some other chart packages.
Can I install d3-selection@2.0.0 instead? And are you planning to upgrade it?
Thanks

**Comment by martynasma** [comment]
Well, this is a sub-dependency. We are not using `d3-selection`, so I'm afraid we won't be able to upgrade it, until our direct dependency `venn.js` upgrade. And we can't force major version upgrade. Sorry.

**Comment by martynasma** [comment]
Bottom line, we can't upgrade to new `d3-selection@2.0.0` until `venn.js` make this upgrade on their end.

If you thing that older version of d3-selection is buggy, you should probably make a case with the makes of `venn.js`.
