### ISSUE TITLE
SyntaxError: Unexpected token 'export' when using amcharts with next.js

### ISSUE THREAD

**Issue by amala-james-cko** [amcharts/amcharts4#3427]
**Bug description**

When trying to load the page which uses the package amcharts, it's throwing the error
```
/node_modules/@amcharts/amcharts4/core.js:8
export { System, system } from "./.internal/core/System";
^^^^^^

SyntaxError: Unexpected token 'export'.
```

I tried transpiling the node modules of amcharts4 but it doesn't seem to work. It was working perfectly after transpiling with next.js version 10.0.0 and custom node server.

Examples use:
Code sand box: https://codesandbox.io/s/amcharts-with-nextjs-xbf3g 

 - amCharts version: Version 4.10.16
 - Browser and its version: Chrome Version 89.0.4389.114 (Official Build) (x86_64)
 - Related frameworks and their versions : Next.js version 10.1.2

**Comment by Pauan** [comment]
@amala-james-cko Thanks for letting us know about this, but it seems to be a bug in NextJS (or next-transpile-modules), so there's not much we can do about it. You can downgrade to an older version of NextJS, or you can use [our script version](https://www.amcharts.com/docs/v4/getting-started/using-javascript/).
