### ISSUE TITLE
DateAxis Grouping - Quarter as TimeUnit in groupInterval 

### ISSUE THREAD

**Issue by rejochandran** [amcharts/amcharts4#3428]
Hi,
I am able to force group the date axis into groups such as year, month, week, day, etc. 
However, there is no option to group the DateAxis as quarters (Q1, Q2, Q3 2021, and so on)

will we be able to do something like:
`dateAxis.groupInterval = { timeUnit: 'quarter', count: 1 };`

Found that we are able to reference quarter in the `dateFormat` according to #2920 but grouping by quarter is not available.

Is this possible or do we have to turn to any sort of custom grouping?

**Comment by martynasma** [comment]
We do not support quarters in built-in grouping.

You may try `{ timeUnit: 'month', count: 3 }` though.

Or [custom aggregation](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Custom_aggregate_functions).

**Comment by rejochandran** [comment]
Hi @martynasma 

Thank you very much for your response. Will quickly try that and get back!

**Comment by rejochandran** [comment]
Hi @martynasma,

`{ timeUnit: 'month', count: 3 }` works well!
However, we also have a need to change when a quarter starts (for example, fiscal year Q1 is April, May, June from the default as JFM)

looking into the documentation, I guess this is only possible through custom group aggregation. Is there any other approach to this?

Again, thank you very much for your help! 😄 🎉

**Comment by martynasma** [comment]
> looking into the documentation, I guess this is only possible through custom group aggregation. Is there any other approach to this?

No, other approach. Sorry :(

**Comment by rejochandran** [comment]
Got that! Thank you for the help ☺️
