### ISSUE TITLE
AmCharts 4: Can you draw a Gantt Chart with a line chart?

### ISSUE THREAD

**Issue by aabdelfa** [amcharts/amcharts4#3429]
Hi, I'm trying to create a Gantt chart above a line chart with the same date axis. I'm having trouble figuring out why I'm receiving This error - **Data fields for series "id-262" are not properly defined.**

Keep in mind that they both have a different dataset, which is another problem because You can't define the Gantt chart's series data, you have to identify the whole chart's dataset. 

Any help would be appreciated. Thanks.

**Comment by xorspark** [comment]
> You can't define the Gantt chart's series data, you have to identify the whole chart's dataset.

You can totally define the series data. The caveat with this approach when a category axis is involved is that you have to ensure that the category axis' data array has all possible category values that exist in your series' data array, as mentioned [here](https://www.amcharts.com/docs/v4/concepts/series/#Note_about_Series_data_and_Category_axis).

As for the error, it sounds like you didn't associate the correct type of dataField for the X and/or Y fields in one of your series; if your chart has a date axis and a category axis, then the appropriate category* and date* fields need to be accounted for in each series, depending on the axes' location.

**Comment by aabdelfa** [comment]
I got the Gantt chart to have its own series data, which is great. Thanks for that. 
The problem I'm having currently is that the dateAxis is not from the same data source for each chart and the Gantt chart has a startDate and an endDate while the line chart has just 1 timestamp for each datapoint. I feel that's why I'm receiving data not properly defined error or do you think there might be a different reason?

**Comment by aabdelfa** [comment]
Keep in mind that if I draw each chart individually with identifying data in its series, it charts fine but not when trying to chart both on the same dateAxis

**Comment by xorspark** [comment]
Can't say for sure without seeing your code. Can you throw it up on codepen or something?

**Comment by aabdelfa** [comment]
I found out what the problem was. The dates for the charts weren't aligned and that's what was causing the issue. I first created two different timelines for the dates and that worked and when I compared them together I found out that was the issue. Thank you for your help and quick reply. You can close this question out.
