### ISSUE TITLE
How to setting hover on MapArcSeries?

### ISSUE THREAD

**Issue by barwalker** [amcharts/amcharts4#3431]
In MapChart, is it possible to setting "hover" state or "over" event on the line series?
`var lineSeries = chart.series.push(new am4maps.MapArcSeries());`
And I want to change the line's appearance, e.g strokeWidth or strokeOpacity
Thanks.

**Comment by martynasma** [comment]
What have you tried so far?

Have you tried creating "hover" state on `lineSeries.mapLines.tempalte`?

https://www.amcharts.com/docs/v4/concepts/states/

**Comment by barwalker** [comment]
I'm editing this demo: https://www.amcharts.com/demos/animations-along-lines/
I tried 2 ways:
- Create a hover state:
```
var hover = lineSeries.mapLines.template.states.create("highlight");
hover.properties.fill = am4core.color("#69975F");
hover.properties.strokeWidth = 4;
```
- Create a over event:
```
lineSeries.events.on('over', ev => {
	console.log('ever')
	ev.target.properties.strokeWidth = 4;
});
```
Nothing is changed.
What's the difference if I create a state or event inside the addLine function?
```
function addLine(from, to) {
    var line = lineSeries.mapLines.create();
    var hover = line.states.create("highlight");
    hover.properties.fill = am4core.color("#69975F");
    hover.properties.strokeWidth = 4;
```

**Comment by martynasma** [comment]
Creating a "highlight" state does nothing. If you want it to be applied when hovered you need to use "hover" keyword for the state.

**Comment by barwalker** [comment]
Yes, I tried "hover" state at the first time and it doesn't work.

**Comment by martynasma** [comment]
OK, so a couple of things:

1) To change color of the line you need to use `stroke` property (not `fill`).
2) State needs to be created on the `template.line`, not directly on the template.

```JavaScript
var hover = lineSeries.mapLines.template.line.states.create("hover");
hover.properties.stroke = am4core.color("#69975F");
hover.properties.strokeWidth = 4;
```
