### ISSUE TITLE
How Sunburst Dynamic Loading on each series

### ISSUE THREAD

**Issue by arieldll** [amcharts/amcharts4#3432]
Hi all,

I am trying a Drill-Down Sunburst Chart (this example: https://www.amcharts.com/demos/drill-down-sunburst-chart/) with a dataset of 15k in 5 grouped combinations, i.e., something like:

```
{ field: '', child: [
  { field: '', child: [
    {field: child:[
      {field: '', child:[
        {field: '', child:[
        }]
      }]
    }]
  }]
}]
```

It represents an amount of 4k combinations, and it is too slow... 
I am thinking in load each level dynamically. 
I tried to change chart.data in each level navigation, but it is returning to the first level in each update. Can someone help how make it? 
There is how to make it by correct approach dynamically? 

Best regards,

**Comment by martynasma** [comment]
I'm afraid incremental data updates are not supported in amCharts 4.

**Comment by arieldll** [comment]
Thank you @martynasma. I am thinking to change "series" data direclty with a queue instead of change chart.data
Is there a example containing data series change data for sunburst chart?

**Comment by martynasma** [comment]
I don't think we have such demo. Sorry.

**Comment by arieldll** [comment]
Thank you @martynasma. 
I am following this example: https://www.amcharts.com/docs/v4/chart-types/sunburst/
So, can you help me how I can change this short part of code:

```
level0SeriesTemplate.slices.template.events.on("hit", function(event){
 ... 
    var hitSlice = event.target;
     if (hitSlice.dataItem.sunburstDataItem.children){
         var series = event.target.dataItem.component;
...
```

How I can to modify this code to set a new serie's data? 
I tried something as

`series.data = [ new data ];`

but it is not working. Can someone help me?

Best regards,

**Comment by martynasma** [comment]
I don't think you can do that in Sunburst chart. The series and their data are created dynamically. You can only change data of the whole chart.
