### ISSUE TITLE
Gantt chart : Expanding/collapsing categories to display subseries on click of button in external div

### ISSUE THREAD

**Issue by dhiren-eng** [amcharts/amcharts4#3433]
In the Gantt chart bordered by blue in the below image, have the following doubts : 

1. Is there a way to add and remove the categories in the chart i.e. Sub-phase1 & Sub-phase2 (on expand and collapse of external div by click of button in this case), apart from removing the categories from the data ? 
2. Is it possible to highlight the grid lines of expanded category as shown in the picture ? (the border of expanded phase 1 can be seen highlighted in the pic)

@martynasma

**Comment by martynasma** [comment]
There is no such functionality in amCharts. Sorry.
