### ISSUE TITLE
Export Menu Icon doesn't show options when using custom icon with JSON config setup

### ISSUE THREAD

**Issue by jaywalker21** [amcharts/amcharts4#3435]
**Question**

- I have a use case where we want to show our custom icon rather than the three dots `...` provided by AmCharts for Menu export. The approach we are going forward with is having `JSON` config for different `AmCharts`. Going by that approach, the custom icon is visible but doesn't have options on it's own for export. It doesn't do anything when hovered upon. Is this a bug from `JSON` config point of view?

**Environment (if applicable)** 
- Browser

**Additional context**

Referred link to get custom icon - https://www.amcharts.com/docs/v4/tutorials/replacing-default-export-icon

Code used to show custom image is at - https://codepen.io/jaybhatt21/pen/wvgrEMj

It does something like below which is suggested from the example link shared above.

```javascript
exporting: {
  menu: {
    items: [
      {
        icon: DownloadIcon // path to the icon (loads the icon well)
      }
    ]
  }
}
```

For reference, it is loading the icon like below image
![image](https://user-images.githubusercontent.com/56739130/113938880-d5e31c00-9818-11eb-889b-de1a6136b258.png)

Now the problem is that no options show up by default when having that custom image.
By options I mean - `Image`, `Data`, `Print` and the `subOptions` within them.

I know the long way is to configure all of them explicitly, but for the `Javascript` and `Typescript` example, it works out of the box. Then why not the JSON one?

**Comment by jaywalker21** [comment]
@martynasma @peluprvi If you could revert to it :D

**Comment by xorspark** [comment]
The reason why the options are hidden is because you're replacing the items array to be a singular item; the docs should be updated to call this out more clearly. Re-defining the array is one option, but a shorter way is to use  the chart's `ready` event to replace the icon without defining any items inside the JSON config.

```
chart.events.on('ready', function() {
  chart.exporting.menu.items[0].icon = icon
  chart.exporting.menu.invalidate();
})
```

[Demo](https://codepen.io/team/amcharts/pen/88f196d5446c0a52d8588d7b08197ff4?editors=0010)
