### ISSUE TITLE
Possible to add legend for range bullets?

### ISSUE THREAD

**Issue by gel-prog** [amcharts/amcharts4#3436]
Let's say I have something simular to [this](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Creating_range_with_bullet). Picture below for reference:

![image](https://user-images.githubusercontent.com/69680343/113999151-0eefb080-985a-11eb-9664-0220bc6f261f.png)

Is there some way with legends or some other tool, to get information on what the icon is? I'm thinking something like this:
![image](https://user-images.githubusercontent.com/69680343/113999377-48282080-985a-11eb-9862-6a4e8a6156ce.png)

But instead of the flags, it would be the red triangle (the range bullet). I know that you can create legends with custom icons, but it seems too complicated for what I am trying to do. Hence why I am asking here.

Any feedback would be appreciated.

**Comment by martynasma** [comment]
Well, you'll need to create element with custom icons. There's no easy way to make chart automatically include bullets into legend.
