### ISSUE TITLE
libraries cannot be loaded when jquery is used

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts4#3437]
I don't have an easy to reproduce test case, only access to a private server.

But when I add the core.js and chart.js via the html script tag, all is fine.
If I load it via sap.ui.define, that is a OpenUI5 library to include external JS scripts, the core.js fails with the error

```
Uncaught (in promise) TypeError: Cannot read property '1' of null
    at eval (core.js:20)
    at Object.Nv8/ (core.js:23)
    at r (bootstrap e6b9a60de46b1aa46f93:54)
    at eval (bootstrap e6b9a60de46b1aa46f93:149)
```

The reason is quite obvious. It happens in below code segment because the getCurrentScript() returns undefined in such case. When using the html script tag it returns something useful.

Any suggestions???

```
import fixPolyfills from "./polyfill";
import "core-js/stable";
import "regenerator-runtime/runtime";
import * as m from "../es2015/core";
window.am4core = m;

// TODO move all of this code into a different module and then import it
function getCurrentScript() {
	if (document.currentScript) {
		return document.currentScript;

	// Internet Explorer only
	} else {
		var scripts = document.getElementsByTagName("script");
		return scripts[scripts.length - 1];
	}
}

function dirpath(x) {
	return /(.*\/)[^\/]*$/.exec(x)[1];
}

__webpack_public_path__ = dirpath(getCurrentScript().src);

fixPolyfills();



//////////////////
// WEBPACK FOOTER
// ./core.js
// module id = null
// module chunks = 
```

**Comment by wernerdaehn** [comment]
I have created a test case for you. Run it with browser debugger active.

https://jsbin.com/xuyikim/edit?html,output

**Comment by wernerdaehn** [comment]
Actually, not even the lazy loading suggestion from your webpage works. Is that possible?
https://www.amcharts.com/docs/v4/tutorials/lazy-loading-amcharts-modules/

**Comment by martynasma** [comment]
It seems that "Access-Control-Allow-Origin" is not being returned by cdn.amcharts.com. We're working on a fix.

As for the dynamic loading, are you loading [script version](https://github.com/amcharts/amcharts4/tree/master/dist/script) or [ES6 modules](https://github.com/amcharts/amcharts4/tree/master/dist/es2015)?

**Comment by wernerdaehn** [comment]
Script version. I am using plain JS, no node.
See my previous posted jsbin example, it is pretty close to the actual code.

One I have completed that, do you want me to wrap that into a full library so that you can show how to use it for SAP customers just like angular, react, etc?

**Comment by Pauan** [comment]
@wernerdaehn You can only use `import` with the ES6 version, not the script version.

In [the documentation for `sap.ui.define`](https://openui5.hana.ondemand.com/api/sap.ui#methods/sap.ui.define) it says that you must use a shim if you are using a third-party library (like amCharts). So you must do something like this:

```js
sap.ui.loader.config({
    shim: {
        "am4charts/core": {
             amd: false,
             exports: "am4core"
        },
        "am4charts/charts": {
             amd: false,
             exports: "am4charts",
             deps: ["am4charts/core"]
        }
    }
});
```

Now you should be able to load `am4charts/core` and `am4charts/charts` normally.

**Comment by wernerdaehn** [comment]
That's how it all started. I define the shim, it loads he am4charts/core.js and fails in there.

![image](https://user-images.githubusercontent.com/13607767/114610854-aa40b580-9ca0-11eb-97f5-4040f9d53523.png)

**Comment by wernerdaehn** [comment]
Here is my library.js file:

```
sap.ui.loader.config({
	shim: {
		'ui5libs/am4charts/dist/core': {
			amd: false,
			exports: 'am4core'
		},
		'ui5libs/am4charts/dist/charts': {
			amd: false,
			exports: 'am4charts',
			deps: ["ui5libs/am4charts/dist/core"]
		}
	}
});
sap.ui.define([
	'jquery.sap.global', 
	'sap/ui/core/library',
	'ui5libs/am4charts/dist/core',
	'ui5libs/am4charts/dist/charts'
	],  function(jQuery, library) {

		"use strict";
		var thislib = ui5libs.am4charts;
		sap.ui.getCore().initLibrary({
			name : "ui5libs.am4charts",
			version: "${version}",
			noLibraryCSS: true,
			dependencies : ["sap.ui.core"],
			types: [],
			interfaces: [],
			controls: [ 
				"ui5libs.am4charts.Chart",
			],
			elements: []
		});
		
		return ui5libs.am4charts;

}, /* bExport= */ true);
```

**Comment by wernerdaehn** [comment]
If I am not mistaken, we do not even get that far that a shim plays a role. 
From my point of view it looks as if it is trying to load the core.js, the webpack tries to find the script name, cannot find one because it was not imported via a script and hence the name is null. And that triggers the error in script[1].

The https://jsbin.com/xuyikim/edit?html,output should be enough to proof.

The shim is, per my understanding, only used to deal with the global variable and the such. But might be totally wrong.

**Comment by Pauan** [comment]
@wernerdaehn It looks like you're using sync mode, which is heavily deprecated in browsers and will be removed in the future.

You can enable async mode by using `data-sap-ui-async="true"`, and now it should use `<script>` tags to load the modules.

Or you can instead change it in your config by setting `async: true`:

```js
sap.ui.loader.config({
        async: true,

	shim: {
		'ui5libs/am4charts/dist/core': {
			amd: false,
			exports: 'am4core'
		},
		'ui5libs/am4charts/dist/charts': {
			amd: false,
			exports: 'am4charts',
			deps: ["ui5libs/am4charts/dist/core"]
		}
	}
});
```

**Comment by wernerdaehn** [comment]
That was definitely a move into the right direction. Next error however:
![image](https://user-images.githubusercontent.com/13607767/114767013-6a90d100-9d67-11eb-867c-1ebdfac7e3a2.png)


My html page had that `data-sap-ui-async="true"` in it already, only the Jsbin did not.
Adding just that causes another error saying "you need to use require". So I changed all sap.ui.define to sap.ui.require.

Now I can see above error in my app and in the jsbin I updated.
https://jsbin.com/xuyikim/edit?html,output

**Comment by Pauan** [comment]
@wernerdaehn You just need to update the shim to use the correct files:

```js
sap.ui.loader.config({
    async: true,

    shim: {
        'am4charts/core': {
            amd: false,
            exports: 'am4core'
        },
        'am4charts/charts': {
            amd: false,
            exports: 'am4charts',
            deps: ["am4charts/core"]
        }
    }
});
```

**Comment by wernerdaehn** [comment]
Thank you so much! I will reciprocate by providing you with a way to use am4charts with SAPUI5.
