### ISSUE TITLE
DateAxis labels to be aligned to columns

### ISSUE THREAD

**Issue by rejochandran** [amcharts/amcharts4#3438]
Hi,

When data is grouped we see that for some groupings such as days and months, the label is set directly below the column 
![image](https://user-images.githubusercontent.com/4696985/114043784-1fae1f80-9876-11eb-82de-5db99687bfce.png)

However, in some groupings like the weeks and quarters (thanks to #3428), we see the labels are added to the date axis and not the columns.
![image](https://user-images.githubusercontent.com/4696985/114044281-9cd99480-9876-11eb-98ad-d6d5dec0392a.png)

I do understand that the labels are for the time units in the axis but is there a way we can show the axis labels in the columns?
something like this
![image](https://user-images.githubusercontent.com/4696985/114044569-ddd1a900-9876-11eb-85e9-2439ff8ca376.png)

**Comment by martynasma** [comment]
Please read [this](https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis).

**Comment by rejochandran** [comment]
Thank you! this resolves the issue! :)
