### ISSUE TITLE
right legend maxcolumn is not working in amcharts piechart

### ISSUE THREAD

**Issue by hshahul** [amcharts/amcharts4#3439]
Hi Team,

Please let me know how can use maxcolumns : 2 is not working right aligned legend?

chart.legend = new am4charts.Legend();
chart.legend.position = "right";
chart.legend.maxColumns=2;

If use chart.legend.scrollable = true; , export image is not showing full legend values

please suggest

**Comment by hshahul** [comment]
https://codepen.io/team/amcharts/pen/eYmLvoR

**Comment by martynasma** [comment]
> Please let me know how can use maxcolumns : 2 is not working right aligned legend?

This is because right-aligned legend has a pre-defined width.

You an reset it manually, e.g.:

```JavaScript
chart.legend = new am4charts.Legend();
chart.legend.position = "right";
chart.legend.maxColumns = 2;
chart.legend.width = 500;
```

> If use chart.legend.scrollable = true; , export image is not showing full legend values

No, way to go about it, but maybe resize chart container on export.

https://codepen.io/team/amcharts/pen/KKNEBwe?editors=0010

**Comment by hshahul** [comment]
Thank you so much for your response.
