### ISSUE TITLE
zoomToDates doesn't work correctly

### ISSUE THREAD

**Issue by guvenacar** [amcharts/amcharts4#3443]
**Bug description**
I have more than 10 years data. Starting at 2009.09.28 to 31.03.2021 (business days). 
ZoomToDates can working only between "2009.09.28" to "2019.01.11" dates. It doesn't work later than "2019.01.11"
 Working with only 1873 records.

 This my codes

`<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>

<script>

    // Themes begin
    am4core.useTheme(am4themes_animated);
    // Themes end

    var chart = am4core.create("chartdiv", am4charts.XYChart);
    chart.paddingRight = 20;

   chart.dataSource.url = "Content/Chart/iron/TestKalinTum.json";

    var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
    dateAxis.renderer.minGridDistance = 50;
    dateAxis.renderer.grid.template.location = 0.5;
    dateAxis.startLocation = 0.5;
    dateAxis.endLocation = 0.5;

    // Create value axis
    var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

    // Create series
    var lineSeries = chart.series.push(new am4charts.LineSeries());
    lineSeries.dataFields.valueY = "value";
    lineSeries.dataFields.dateX = "date";
    lineSeries.strokeWidth = 3;
    lineSeries.showOnInit = false; 

    chart.scrollbarX = new am4core.Scrollbar(); 

            // Pre-zoom the chart
        chart.events.on("ready", function () {
            dateAxis.zoomToDates(
                "2009.09.28",
                "2010.10.06"  
            );
        });
</script>`

<div id="chartdiv"></div> 

**Environment (if applicable)**

 - amChartsversion : 4
 - Browser and its version : Opera latest

**Comment by guvenacar** [comment]
//C# business days maker 

int numberOfDaysTotal = 1873 ;

DateTime start = DateTime.Today;
var dates = Enumerable.Range(0, numberOfDaysTotal)
            .Select(offset => start.AddDays(offset))
            .Where(date => date.DayOfWeek != DayOfWeek.Saturday 
                        && date.DayOfWeek != DayOfWeek.Sunday);

**Comment by xorspark** [comment]
You might be running into timing issues. Instead of using the `ready` event when using a dataSource, try using the `datavalidated` event, which fires after the data has been fully parsed.

```
chart.events.on("datavalidated", function(ev) {
  if (chart.data.length > 0) {
    dateAxis.zoomToDates(
      new Date(2009, 8, 28),
      new Date(2010, 9, 6),
    );
  }
});
```

Do note that [`zoomToDates`](https://www.amcharts.com/docs/v4/reference/dateaxis/#zoomToDates_method) expects `Date` objects. If a string is passed, the chart will either use the `inputDateFormat` set on your chart (by default it is `'yyyy-MM-dd'`) or `new Date` if it doesn't work, which then leaves you at the mercy of the browser's `Date` constructor on string-based dates.

**Comment by guvenacar** [comment]
Thank you, worked now.
