### ISSUE TITLE
Add tooltipHtml for bubble chart

### ISSUE THREAD

**Issue by thevilx** [amcharts/amcharts4#3445]
Hi, I have a bubble chart that I want to use tooltipHtml for it. it's working unless the `snaptoseries` is enabled.
how can I make it work without `snaptoseries` ?
tooltipText is working fine.
when I remove the snaptoseries option no bubble is showing!

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by thevilx** [comment]
https://codepen.io/mjnwn_shahr/pen/oNBEbMb

**Comment by martynasma** [comment]
Thanks.

Try setting `tooltipText` to something. `tooltipHTML` will still override it, but the tooltips will display:

```
series[i].tooltipHTML = `<p>HTML test</p>`
series[i].tooltipText = `...`
```

**Comment by thevilx** [comment]
Unfortunately, it did not work!
tooltiptext shows and hides in a second.
it doesn't show toltipHtml at all.
Thanks for checking it.

**Comment by martynasma** [comment]
You also need to enable cursor snapping:

```
chart.cursor.snapToSeries = series;
```

You have it disabled in your CodePen.

**Comment by thevilx** [comment]
Well, At first I told you , I don't want snaptoseries to be enabled! My first question :
" Hi, I have a bubble chart that I want to use tooltipHtml for it. it's working unless the snaptoseries is enabled. "

**Comment by martynasma** [comment]
Sorry.

In this case you might need something more complex. E.g.:

https://www.amcharts.com/docs/v4/tutorials/multiple-cursor-tooltips-on-scatter-chart/
