### ISSUE TITLE
Hii! Anyone here have an idea how to make this type of graph, Thanks in advance.

### ISSUE THREAD

**Issue by shabbir135** [amcharts/amcharts4#3447]
**Question**

**Environment (if applicable)**

**Additional context**

[****](url
![amsGraph](https://user-images.githubusercontent.com/55679750/114271317-5c247b80-9a2e-11eb-9065-d3de5bf6a2b0.PNG)
)

**Comment by martynasma** [comment]
Yes, it's a GaugeChart:

https://www.amcharts.com/docs/v4/chart-types/gauge-chart/

**Comment by shabbir135** [comment]
> Yes, it's a GaugeChart:
> 
> https://www.amcharts.com/docs/v4/chart-types/gauge-chart/

Yes, I have tried all customization but still not able to achieve this like:
1. needle UI
2. space in the graph
