### ISSUE TITLE
Provide all charts from demo as Json-Config

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts4#3448]
Take this demo chart: https://www.amcharts.com/demos/radar-chart-visualizing-yearly-activities/

Given that you have a diagram editor, it would be good to provide all these advanced charts as Json config as well.
If this is not possible because they use functions, it would be good to enhance the Json config to support such as well.

Keep in mind, for simple charts you do not need an editor, it is for the fancy charts!

**Comment by martynasma** [comment]
Converting all of the demos to JSON would be an enormous effort, if possible at all.

E.g. the demo you mentioned would not be possible for the reasons you pointed out.

It would also not be possible to replicate this chart in Editor.

**Comment by wernerdaehn** [comment]
This raises two points, the task of the conversion as such and the limitations of the Json config. Let's focus on the latter first.

If you are planning to promote the editor, and in my opinion you should, the Json Config must support these cases.
Please consider that dependency.

Meanwhile I will dissect this particular demo chart again in order to understand what parts are preventing the Json Config at the moment. I am familiar with the demo chart but must go though it again to find the missing features in the Json config.

**Comment by martynasma** [comment]
JSON does not support thinks like object literals or functions. So that's a show-stopper right there.

That being said, our JSON-config parser does allow objects and even functions, but making those editable via editor - at least in some usable and meaningful way - would be mission impossible.

This is a discussion we went through internally, and decided on Editor how it is now.

**Comment by wernerdaehn** [comment]
Understood. But keep in mind, some things we can offload to the system generating the data. For example instead of creating a function to sum up the daily numbers to month-totals, the data object can contain these values already.

My point is, it might not be that difficult. But as said, I need to look into the details myself. Maybe I just need time to come to the same conclusion like you. Maybe I can make some suggestions.
