### ISSUE TITLE
Editor: Support data coming from URLs

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts4#3449]
I am currently creating a docker image that can expose any database data either via oData or Json.

Example for Json:

```
http://localhost:8080/HanaAppContainer/protected/rest/query?$select=SELECT%20OBJECT_TYPE,%20count(*)%20as%20COUNT%20FROM%20objects%20GROUP%20BY%20OBJECT_TYPE
```

returns

```
[
 {"OBJECT_TYPE":"TABLE","COUNT":18},
 {"OBJECT_TYPE":"VIEW","COUNT":614},
 {"OBJECT_TYPE":"INDEX","COUNT":3},
 ...
]
```

If the data tab would support URLs, the user could view the data and pick the columns from the Json element names.

With oData one more level would be possible, creating the URL! The user points to the service endpoint, this exposes the metadata. You read the metadata and allow the user to build the query URL interactively.

**Comment by martynasma** [comment]
If this is about the Editor product, please use this repo instead: https://github.com/amcharts/editor4
