### ISSUE TITLE
Gauge Chart should support external data

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts4#3450]
I understand why a Gauge does not need a data series, the "hand" is enough. But when the data comes from a rest service, e.g. one that returns the result of

```
select sum(revenue) as total_revenue from sales_data where year =2021;
```

as a Json response, it would be nice to support that to be consistent. 

```
[
  { "total_revenue": 300.45 }
]
```

Actually it should be fairly simple (and maybe works already?). The data/externaldata is read just like with other charts. And in the hand this value is used via parameter substitution: "value" : "{total_revenue}".

Note: Above service returns an array of objects - it returns a query result - and there is only one array item present always.

**Comment by martynasma** [comment]
Gauge is not a serial chart and will not accept array-based data. Sorry.

If you need to use external data for your Gauge chart, you can do AJAX-loading (either with amCharts built-in functions, or some other means) and set hand value.

Hope that makes sense.

**Comment by wernerdaehn** [comment]
From a chart developer point of view your answer makes sense. From a user convenience point of view it does not. And consistency also not.

Let's split this suggestion into two parts:
- Can you please support the external data feature. So you execute the ajax code instead of customers must do something manually.
- Is the the substitution syntax capable to read array elements? In my example something like "value" : "{[0].total_revenue}" to access the first array's object and from there the total_revenue property. I don't know the capabilities of the syntax yet.

**Comment by martynasma** [comment]
I'm sorry, but we won't be able to accommodate your suggestions.

It would be too much of an overhead to develop and maintain, with little benefit.

Loading external data is not that much code:
https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/#Standalone_usage

**Comment by wernerdaehn** [comment]
Okay. It was worth a try.

**Comment by wernerdaehn** [comment]
I'd like to reopen it given my findings. Just to make sure we are on the same page before closing it again.

To recap, these are the requirements:
1. Support executing a query using the `"dataSource": {"url": "ui5rest/lookup/WEBPROJEKT/VIEW_COLUMN_DISTRIBUTION"}` syntax. (Returns `{"TABLE_NAME":"TABLES","TABLE_COLUMNS_PERCENT":57.142857}` )
2. Support Formatter in the config json like `"hands": [ {"type": "ClockHand","value": "{TABLE_COLUMNS_PERCENT}", ...`
3. Even better, support a hands list template and assume 1) returns an array of values.

Per my understanding you said that none of this is available. However when simply adding the dataSource, I can see the request gets executed.
Now I wonder if the Formatter is working also and I just do not use it correctly.
And if a list template for hands truly is waste or makes sense anyhow.

**Comment by martynasma** [comment]
Creating a DataSource will load the url. However, it will try to set chart's `data`. Since GaugeChart does not use `data`, it will mean nothing.

You can attach events and postprocess loaded data to populate hands if you wish:

https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/#Manipulating_loaded_data

**Comment by wernerdaehn** [comment]
Thanks.
