### ISSUE TITLE
How to hidden content tooltip of a serie that created via createSeries?

### ISSUE THREAD

**Issue by guvenacar** [amcharts/amcharts4#3451]
How to hidden tooltip content of a serie if it is hidden in this sample 
<a href="https://codepen.io/team/amcharts/pen/KKwrmyM"  target="_blank">https://codepen.io/team/amcharts/pen/KKwrmyM</a>

<img src="https://i.ibb.co/KryG1mL/Series-Hidden.png" />

**Comment by guvenacar** [comment]
<img src="https://i.ibb.co/KryG1mL/Series-Hidden.png" />

**Comment by martynasma** [comment]
```JavaScript
  series.adapter.add("tooltipText", function(ev) {
    var text = "[bold]{dateX}[/]\n"
    chart.series.each(function(item) {
      if (!item.isHidden) {
        text += "[" + item.stroke.hex + "]●[/] " + item.name + ": {" + item.dataFields.valueY + "}\n";
      }
    });
    return text;
  });
```

The CodePen was updated as well.

**Comment by guvenacar** [comment]
Many thanks.
