### ISSUE TITLE
When they intersect, two tooltip come out.

### ISSUE THREAD

**Issue by guvenacar** [amcharts/amcharts4#3452]
If they intersect, two (three, four ..)  tooltip come out in this sample 
https://codepen.io/team/amcharts/pen/KKwrmyM
<img src="https://i.ibb.co/hcWhxV6/Tooltip.png" />

**Comment by martynasma** [comment]
Setting `maxTooltipDistance` to `-1` will fix it:

```JavaScript
chart.cursor.maxTooltipDistance = -1; 
```

**Comment by guvenacar** [comment]
Thank you very much, worked.
