### ISSUE TITLE
Lines remain bold even after unmarking

### ISSUE THREAD

**Issue by MarkoB19** [amcharts/amcharts4#3456]
The problem is best seen in the video. after a short time the lines remain bold even after unmarking.
https://www.loom.com/share/2566b39c8ad944fa9c0d6c98ed2e1ff0.

Thank You.

**Comment by martynasma** [comment]
It seems like you're doing something custom as it's not the built-in functionality of the amCharts library. Do you have a working demo?

**Comment by MarkoB19** [comment]
The information is quite sensitive and the subject of ISO 27001 certification. 
We will look at what part of the code we can share. Please wait for a while . 

Thank you for understanding

**Comment by MarkoB19** [comment]
Hi,

Before I continue with my problem description, I'd first like to thank you for the effort that you put into this library. We solved a lot of problems quite easy with the help of your documentation and the whole look and feel of the charts is a lot better than with the previous library that we used for charts.

There are actually two issues that we have. First is that even with the code provided on https://www.amcharts.com/docs/v4/tutorials/using-states-on-lineseries/ some segments remain displayed in the hover state. Debugging shows that `segment.isHover` is properly changed, which means that it's values alternates between `true` and `false,` but the chart view is not updated. Invalidating chart also does not help. Nothing customized is made. The code is pasted as is (with minor chart name variable change).

Second issue that we're trying to solve is offsetting series tooltip within the XYCursor for a certain amount of pixes along the X axis. Reason for that are multiple Y axis (different energy sources), where tooltips obscure view to the line and we'd like to move it +/- 20 pixels, depending on the closer edge of the chart.

![image](https://user-images.githubusercontent.com/43342450/114622957-f09d1100-9cae-11eb-97c2-6e0b235494a6.png)

As you can see, Lokacija 2 - Tlak and Lokacija 2 - Plin 1 are quite close, so we'd like to offset them a bit. It's ok if the arrow does not point directly to the point itself.

**Comment by martynasma** [comment]
We'll need some kind of demo in order to investigate, sorry.

As for the second issue, can you post it in a separate thread? Let's keep this place clean with only one question per thread.

**Comment by MarkoB19** [comment]
Thank you very much, we gave up this way of displaying the data and took this one:
[LINK](https://www.amcharts.com/demos/highlighting-line-chart-series-on-legend-hover/)

**Comment by martynasma** [comment]
Are you still having the issue with the new demo, or you're all set?
