### ISSUE TITLE
Export with getImage with location.href with more than 2 path parts breaks fonts loading

### ISSUE THREAD

**Issue by bubliq** [amcharts/amcharts4#3457]
**Bug description**

Rerpo steps:

1. Create any chart with URL like 
`http://localhost/first/second`
2. Call export as 
`chart.exporting.getImage('png');`
**Expected:** Export done, no errors, fonts ok
**Actual:** Export done, font loading errors with urls like: 
`http://localhost/first/open-sans-v15-latin-300.eot?`

**Environment (if applicable)**

 - amCharts version
4.10.15
 - Browser and its version
Chrome Version 89.0.4389.114 (Official Build) (64-bit)
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.]
 Angular 9

**Additional context**

From debugging, I found that problem caused by function
`Utils.joinUrl`
> else if (leftPath.length > 1) {
                    leftPath.pop();
                }

Which pops only last piece of path ("second" in rerpo steps).

If it's by design, how can I manipulate topUrl for this type of functions like `eachStylesheets`? They use `location.href` as topUrl, so I can't replace them.

**Comment by martynasma** [comment]
Can you please specify import of a custom font in your CSS? Is it via `@import` or `@font-face`. I can't seem to be able to reproduce this with either.

**Comment by bubliq** [comment]
> Can you please specify import of a custom font in your CSS? Is it via `@import` or `@font-face`. I can't seem to be able to reproduce this with either.

Hey, the thing is, I didn't change any of the fonts for amcharts, however, I use dynamic imports of amchart library as chunk for avoiding issue with build-optimizer [like this](https://medium.com/lacolaco-blog/angular-dynamic-importing-large-libraries-8ec079603d0). If it's any help.

There is a screenshot of network.
As you can see, my URL contains two parts of a path `http://host/x/y`
But the fonts default path is of course `http://host/{font-name}` and I can access them via this kind of address.
But as network indicates, the requests for font-loading are coming with `http://host/x/{font-name}`

![Untitled](https://user-images.githubusercontent.com/5256688/114678674-288a6f80-9d14-11eb-9e34-a83543d28714.png)

**Comment by martynasma** [comment]
Any ideas how we can reproduce it?

**Comment by bubliq** [comment]
Well, I can try to create repository with this issue, later today and link it here.
On a paper it needs to be simple angular application with routing to a component with two path parts, that calls export on a chart from that URL.

**Comment by martynasma** [comment]
A simple repro Angular app that we could run would be perfect. Thanks!
