### ISSUE TITLE
Data visualization disappears

### ISSUE THREAD

**Issue by p05ta1** [amcharts/amcharts4#3458]
When forming the "am4charts.XYChart" chart, we need to display several curves/graphs (hereinafter - lines and, in fact, not curves, but broken lines). We display data with one-second-step, but there are situations (such seconds/steps) when it is impossible to fill in all the data - and in this cases the graph either does not initially display lines or they disappear when zooming (changing the horizontal scale). For example, there are cases when with zooming all the lines 📉📈 disappear. How can we solve this problem?

x = am4core.create("chartdiv", am4charts.XYChart);
let dateAxis = x.xAxes.push(new am4charts.DateAxis());
let valueAxis = x.yAxes.push(new am4charts.ValueAxis());

let series = x.series.push(new am4charts.LineSeries());
series.dataFields.dateX = "date";
series.dataFields.valueY = "v1";
series.tooltipText = "{valueY}";

let series2 = x.series.push(new am4charts.LineSeries());
series2.dataFields.dateX = "date";
series2.dataFields.valueY = "v2";
series2.tooltipText = "{valueY}";

x.cursor = new am4charts.XYCursor();

x.scrollbarX = new am4core.Scrollbar();

x.legend = new am4charts.Legend();
x.legend.position = "right";
x.legend.scrollable = true;

x.current = x;

**Comment by xorspark** [comment]
Is your data sorted in datetime ascending order? Out of order data can usually cause problems like this. 

If your data is sorted correctly and you're still seeing this, could you provide a codepen/fiddle with some sample data that reproduces the problem? I'm unable to reproduce your issue with randomly generated data [here](https://codepen.io/team/amcharts/pen/9cf998d19715a330af5a39e09176295f?editors=0010).

**Comment by IsanchezFS** [comment]
Hello @xorspark,

I´m having the same issue, the line series disappear in zoom to Dates function, but if we change manually the zoom the line show ups again, 

My code is here https://codepen.io/Ismaelszr/pen/oNBRNrd 

The following image show the line until Mar 30, but the cursor continues display the tooltip like if the line was there,

![image](https://user-images.githubusercontent.com/65559471/116467329-2e647280-a835-11eb-8690-36406d53f453.png)

and if I increase the zoom at least 3 day more the line appears
![image](https://user-images.githubusercontent.com/65559471/116467628-813e2a00-a835-11eb-9ac5-a5f8ef1c963a.png)


I´m using this version "@amcharts/amcharts4": "^4.10.17" 

Can you help me to understood if I missing some lines or is a issue with the library?

Thanks

**Comment by xorspark** [comment]
@IsanchezFS - your data is out of order as I indicated in my prior response. It needs to be in ascending order. Your data is in descending order, [which is not supported](https://www.amcharts.com/docs/v4/concepts/data/#Date_based_data).
