### ISSUE TITLE
Date axis dynamic grouping "max" aggregator bug

### ISSUE THREAD

**Issue by wwei-flux** [amcharts/amcharts4#3459]
**Bug description**

The built-in "max" aggregator of date axis dynamic grouping feature doesn't seem to work as expected.

Here is a [Codepen](https://codepen.io/weiwei9/pen/QWdrwXa) example I modified based on the example in https://www.amcharts.com/docs/v4/tutorials/using-custom-functions-for-data-item-grouping/

Two data series use the same data values.
Series 1 uses the built-in max aggregator. Series 2 uses a custom function that implements "max" function.
```
// a custom function that implements "max"
series.adapter.add("groupDataItem", function(val) {
  val.value = 0;
  for(var i = 0; i < val.dataItem.groupDataItems.length; i++) {
    var item = val.dataItem.groupDataItems[i]
    if (val.value < item.valueY) {
      val.value = item.valueY;
    }
  }
  return val;
});
// built-in "max"
series2.groupFields.valueY = 'max';
```

They are expected to product same aggregated values, but they don't.

**Environment (if applicable)**

https://codepen.io/weiwei9/pen/QWdrwXa

**Comment by martynasma** [comment]
`"max"` value for the `groupFields` is invalid. You should use `"high"`.
