### ISSUE TITLE
Offsetting series tooltips

### ISSUE THREAD

**Issue by MarkoB19** [amcharts/amcharts4#3460]
We're trying to solve is offsetting series tooltip within the XYCursor for a certain amount of pixels along the X axis. Reason for that are multiple Y axis (different energy sources), where tooltips obscure view to the line and we'd like to move it +/- 20 pixels, depending on the closer edge of the chart.

![image](https://user-images.githubusercontent.com/43342450/114667594-f0793180-9cff-11eb-9b4a-733cc1dffa9c.png)

As you can see, Lokacija 2 - Tlak and Lokacija 2 - Plin 1 are quite close, so we'd like to offset them a bit. It's ok if the arrow does not point directly to the point itself.

**Comment by martynasma** [comment]
And adapter for the `dx` property of the tooltip might help:

```JavaScript
series.tooltip.adapter.add("dx", function(dx, target) {
  return target.background.pointerX > 0 ? -10 : 10;
})
```

**Comment by MarkoB19** [comment]
Thank you very much, this will definitely help.
