### ISSUE TITLE
Sankey diagram showing nodes on same level and causing visual problems

### ISSUE THREAD

**Issue by iColdoCatalin** [amcharts/amcharts4#3461]
So I'm working with amcharts v4 and Sankey diagram. I'm trying a dataset that is quite simple but I have the node 500 and 652 on same level and causing some visual issues as in the picture below. I've tryied to arrange differently the dataset but having same issue. Anyone can help? Is even possibile to reduce the links width in order to make it fit better? (tryied everything from SankeyLink but with no results)

```
[{from: '100', to: '200', value: 1},
{from: '200', to: '450', value: 1},
{from: '450', to: '652', value: 1},
{from: '450', to: '652', value: 1},
{from: '652', to: '500', value: 1},
{from: '652', to: '500', value: 1},
{from: '500', to: '650', value: 1},
{from: '500', to: '650', value: 1}]
```

![sankeydiagramissue](https://user-images.githubusercontent.com/29724985/114696591-1c56e000-9d1d-11eb-94ee-efd90d49c5d2.PNG)

**Comment by martynasma** [comment]
It seems to be a bug caused by all-number names. If I change the name of the last node to something that starts with a letter, the chart displays fine.

We'll see how this can be fixed, and will keep you posted.

Thanks for the heads up!

**Comment by iColdoCatalin** [comment]
@martynasma thank you. I'll be waiting for the fix.

Meanwhile is it possible to reduce the space between nodes? Can I use a width on links? I've search and tested the maxWidth, width and others from SankeyLink but with no results.

**Comment by martynasma** [comment]
> Meanwhile is it possible to reduce the space between nodes? Can I use a width on links? I've search and tested the maxWidth, width and others from SankeyLink but with no results.

No, I'm afraid. The diagram will always space out nodes to the full width of chart container, with links filling in between them.
