### ISSUE TITLE
Reg - Font Color Dynamic Changes in ToolTip

### ISSUE THREAD

**Issue by kaariwedoms** [amcharts/amcharts4#3464]
How to apply conditional classes for the below snippet model tooltip

series.tooltipHTML = `<strong><u>Player Win</u></strong>  <span style="margin-left:210px;" class="cust-post-img pos"> Test</span>
<table class="table-bot">
<tr>
  <th align="left">Open</th>
  <td [ngClass]="'color-sam'">{openValueY.value}</td>
</tr>
<tr>
  <th align="left">Low</th>
  <td>{lowValueY.value}</td>
</tr>
<tr>
  <th align="left">High</th>
  <td>{highValueY.value}</td>
</tr>
</table>

**Comment by martynasma** [comment]
Try in-line formatting functions:

```JavaScript
series.tooltipHTML = "{openValueY.value.formatNumber('#|<font style=\"color: red\">#</font>')}";
```

More info:
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/#Negative_values_and_zeros
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/#Overriding_format

**Comment by kaariwedoms** [comment]
Thx
