### ISSUE TITLE
Remove the last DateAxis label that is added by the chart lib

### ISSUE THREAD

**Issue by NudeFox** [amcharts/amcharts4#3465]
When chart has enough space the DateAxis labels are shown correctly. 
![image](https://user-images.githubusercontent.com/17131070/115027001-d2602c80-9ecb-11eb-8374-d2b9cb00d921.png)

Configuration of DateAxis:
```
const dateAxis = chart.xAxes.push(new am4charts.DateAxis());
dateAxis.renderer.minGridDistance = 30;
dateAxis.renderer.grid.template.disabled = true;
dateAxis.renderer.labels.template.fontSize = 12;
dateAxis.renderer.labels.template.fill = am4core.color('#838FB6');
dateAxis.periodChangeDateFormats.setKey('month', 'MMM');
dateAxis.periodChangeDateFormats.setKey('hour', 'HH:mm');
dateAxis.periodChangeDateFormats.setKey('day', 'dt');
dateAxis.dateFormats.setKey('day', 'dt');
```

But when we shrink down the width chart lib adds the unnecessary end label for next month:
![image](https://user-images.githubusercontent.com/17131070/115027249-25d27a80-9ecc-11eb-9068-e19ce6cd14dd.png)

It's ok to not show that at all, but i can't find how to disable that logic. Also i don't want to manipulate with `gridDistance` as it's set to perfectly fine value. 

*Question*
How to disable that last label, that doesn't exists in data and show only the data points that exists?

**Comment by martynasma** [comment]
Perhaps you can use `maxLabelPosition` for this:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Start_and_end_labels

**Comment by martynasma** [comment]
Perhaps you can use `maxLabelPosition` for this:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Start_and_end_labels
