### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by ikomwrestling** [amcharts/amcharts4#3466]
**Bug description**

www.amcharts.com lacks IPv6 addresses and thus resources (JavaScript) from it can't be received using IPv6.

Since the CDN seems to be served by Cloudflare, which has great IPv6 support, it should hopefully be a simple fix by enable IPv6 in dashboard, as per their [IPv6 documentation](https://support.cloudflare.com/hc/en-us/articles/229666767-Understanding-and-configuring-Cloudflare-s-IPv6-support).

Thank you.

**Comment by martynasma** [comment]
Oops this has somehow has slipped through the cracks.

We do have now IPv6 enabled for CDN. (should work both via www.amcharts.com and cdn.amcharts.com addresses)
