### ISSUE TITLE
Reg - Adding New State in Candlestick(OHCL) Chart

### ISSUE THREAD

**Issue by kaariwedoms** [amcharts/amcharts4#3467]
Currently, candlestick chart supports only two states as mentioned below in referenced image
<img width="408" alt="candlestickchart" src="https://user-images.githubusercontent.com/8941091/115196561-ab913880-a10d-11eb-8e5a-e0346bc843b0.png">
IS that possible to add new state to it (with specified color props)

**Comment by martynasma** [comment]
You can create as many states as needed. However only these four are applied automatically by CandleStickSeries:

1. dropFromOpenState
2. dropFromPreviousState
3. riseFromOpenState
4. riseFromPreviousState

If you need something different, I suggest using an [adapter](https://www.amcharts.com/docs/v4/concepts/adapters/) instead.

**Comment by kaariwedoms** [comment]
> You can create as many states as needed. However only these four are applied automatically by CandleStickSeries:
> 
> 1. dropFromOpenState
> 2. dropFromPreviousState
> 3. riseFromOpenState
> 4. riseFromPreviousState
> 
> If you need something different, I suggest using an [adapter](https://www.amcharts.com/docs/v4/concepts/adapters/) instead.

In my requirement ,I have scenario where If open value is equal to close value, similar like positive /negative marking i need it plot it in chart in different color marking along with existing markings, can u provide steps/ solutions to attain it

**Comment by martynasma** [comment]
Well, there is no built-in state for that. So you would need to use an adapter for it.

E.g.:

```JavaScript
series.columns.template.column.adapter.add("fill", candleColor);
series.columns.template.column.adapter.add("stroke", candleColor);
series.columns.template.lowLine.adapter.add("stroke", candleColor);
series.columns.template.highLine.adapter.add("stroke", candleColor);

function candleColor(color, target) {
  if (target.dataItem.values.openValueY.value == target.dataItem.values.valueY.value) {
    return am4core.color("#888")
  }
  return color;
}
```

**Comment by kaariwedoms** [comment]
Thank you so much for your workaround,, it worked for me @martynasma
