### ISSUE TITLE
RadarChart Category Axis Label Positioning

### ISSUE THREAD

**Issue by XGuGu** [amcharts/amcharts4#3468]
**Question**
Hi amCharts team,

I am using RadarChart and facing an issue in positioning the category label. 
My Category label is having multiple lines conditionally. In different user screen, sometimes the label at the top is cut off or are out of the boundary. I want to change the position of the label and bring them more closer to the center.

<img width="500" alt="amChartQuestion" src="https://user-images.githubusercontent.com/39609237/115306263-3170ac00-a12d-11eb-8692-8f2fe6c548d8.png">

Here is an example for the chart: https://jsfiddle.net/fancyo/8z0g36sa/11/

Thank you so much for checking the question.

Regards

**Comment by martynasma** [comment]
You can fine-tune label position using their `radius` setting, e.g.:

```JavaScript
categoryAxis.renderer.labels.template.radius = -20;
```

**Comment by XGuGu** [comment]
Thanks so much, it solved my issue.
