### ISSUE TITLE
Disabling Tooltip pointer

### ISSUE THREAD

**Issue by kaariwedoms** [amcharts/amcharts4#3469]
1. Is there anyways we can eliminate triangle shape design (Pseudo class selector) attached with Tooltip box , which i have marked in blue color high ligation reference image attached for reference
![chart](https://user-images.githubusercontent.com/8941091/115378668-6a248a00-a1ee-11eb-977a-41f26780db8b.png)

2. Is there any workaround to override/customize mouseover style other than styles mentioned in amcharts documentation
<img width="494" alt="mousecursor" src="https://user-images.githubusercontent.com/8941091/115378940-b1ab1600-a1ee-11eb-888b-fab2fdd4a74a.PNG">

**Comment by martynasma** [comment]
> Is there anyways we can eliminate triangle shape design (Pseudo class selector) attached with Tooltip box , which i have marked in blue color high ligation reference image attached for reference

Yes:

```JavaScript
series.tooltip.background.pointerLength = 0;
```

Let's keep this place clutter-free, both for our own sake and the other's. Please post your other question in a separate issue.

**Comment by kaariwedoms** [comment]
Sorry and thx  for your input it worked lime charm :)
