### ISSUE TITLE
Overriding Mouse Pointer Style

### ISSUE THREAD

**Issue by kaariwedoms** [amcharts/amcharts4#3470]
Is there a way to override mouse cursor style other than the possibilities mentioned below in image
<img width="494" alt="mousecursor" src="https://user-images.githubusercontent.com/8941091/115391306-f6d64480-a1fc-11eb-9033-e5acf2642af6.PNG">

**Comment by martynasma** [comment]
Those are just shortcuts. You can set cursor style to just about anything supported by browsers.

Please note that it's an array consisting of the property key (in this case it will always be `"cursor"`) and CSS value. All those will be applied as applicable by the browser. E.g. `MouseCursorStyle.grab` is the following:

```JSON
[{
		"property": "cursor",
		"value": "move"
}, {
		"property": "cursor",
		"value": "grab"
}, {
		"property": "cursor",
		"value": "-webkit-grab"
}]
```

Hope it makes sense.
