### ISSUE TITLE
Is there any way to set truncate starting position?

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3471]
Hey,

I have this boxes in a chart, this is using both `wrap` and `truncate` set to true. Ideally I would want to have more control over truncation and force it to use as much space as it can.

So if I were to set the boxes width to `150` and height to `50` I would expect the text to fill as much as 150/50

Below is the chart
![image](https://user-images.githubusercontent.com/40542072/115430267-e3cb7080-a20c-11eb-999f-bb02d845809c.png)

Even setting a higher width seems to have this issue persist

![image](https://user-images.githubusercontent.com/40542072/115430454-0fe6f180-a20d-11eb-9429-b7712e7e003a.png)

Is there any to instruct `truncate` where to truncate?
Thank you

**Comment by martynasma** [comment]
There's no options for the truncate. It will follow some fuzzy logic to make the text fit.

I suppose the only option here is to have an adapter for `text` on your labels, then implement your own measuring algo if needed.

Does that make sense?

**Comment by teodosii** [comment]
I see, thanks for reply! I'll then use the text adapter and try to fit text accordingly.
