### ISSUE TITLE
Documentation/Implementation for adding adapters via JSON array is wrong

### ISSUE THREAD

**Issue by GhostKilllaX** [amcharts/amcharts4#3473]
**Bug description**
when loading adapters via a json array the documentation says the id should be in a variable named "type" but in reality it only works with the variable named "key"

**Additional context**
documentation: https://www.amcharts.com/docs/v4/concepts/json-config/#Adapters
example: https://jsfiddle.net/swdek3gt/13/

**Comment by GhostKilllaX** [comment]
@martynasma i think you unintentionally changed (or perhaps it was already) the variable name in dataFields to "key" too. Should be "value" :)
```
{
  "series": [{
    "dataFields": {
      "key": "revenue",    <-- this one should be "value"
      "category": "department"
    },
    "adapter": [{
      "key": "tooltipText",
      "callback": function(val) {
        return "This is a PieSeries: " + val
      }
    }]
  }]
}
```

**Comment by martynasma** [comment]
Indeed. Good catch. Thanks!

P.S. no more later night doc edits for me :)
