### ISSUE TITLE
StepOption Lighten doesn't work consistently

### ISSUE THREAD

**Issue by Vermilion755** [amcharts/amcharts4#3474]
I'm trying to figure out how to setup a chart, or in this specific case, a TreeMap...using ascending shades of a single color. For example, start with red, and for each item, get slightly lighter, rather than using any other colors. I read about ColorSets and themes, and found the StepOptions property where I can specify a value for 'lighten'. However, I can't seem to make any sense of it. I started putting in integer values and reloading my app to see what affect each number would have, but found no discernable pattern. I'm expecting that a low number would make each next item be only slightly lighter, while a high number would make each next item be significantly lighter. I switched to using decimals when I saw some other issue posts using decimals in their examples. This didn't seem to help. 

Here is a codepen example I created: [https://codepen.io/Grymlot/pen/XWpyvwm](https://codepen.io/Grymlot/pen/XWpyvwm)

In the codepen, I have setup 5 different themes, each with the same base color but with a different value for the StepOptions.Lighten property (0.05, 0.1, 0.15, 0.2, and 0.25). Notice that the colors seem to reset at random points. At first, I was guessing the colors reset to the base color once the value got too light to go lighter...but that doesn't seem to play out in the example. Instead, in the 0.05 lighten example, the color gets lighter for 3 colors after the base color, then the 4th seems to get darker. In the 0.1 example, the first color is lighter but the 2nd is darker. 

Can anyone explain how I'm supposed to be accomplishing this, or what I'm doing wrong?

**Comment by Vermilion755** [comment]
Also note, the documentation has no example of using StepOptions properties, anywhere, to follow.

**Comment by martynasma** [comment]
The colors "[wrap around](https://www.amcharts.com/docs/v4/reference/colorset/#wrap_property)". Meaning that when the next calculated lightness reaches [`maxLightness`](https://www.amcharts.com/docs/v4/reference/colorset/#maxLightness_property) it does not just reset to base lightness, but wraps around and goes above `minLightness` by the value that is remaining from reaching `maxLightness`.

Sounds confusing, bet I hope it still makes sense.

**Comment by Vermilion755** [comment]
Thanks @martynasma, that's helpful to know, but I'm still missing any sort of predictability. Is there some way to understand what the maxLightness value is? I had assumed it was a percentage sort of thing, so that way I know it won't wrap until I've added a full 1 (100%). That way, if I want 5 items without wrapping, I would assign a value of 0.2 (1 divided by 5). This seems to match up with the 0.2 value in my example. However, with a value of 0.15, it seems to have wrapped after just 2 new colors. So, I lower it to 0.1 and still it's wrapping after just 2 new colors. So I lower it again to 0.05 and finally it's taking 4 new colors to wrap, and yet that's the same number I get with 0.25. I can't find any consistency here. 

Looking at my example, I would have expected the 'Darker' label of when it's wrapping, to be lower down the further we move to the left (smaller lighten values), indicating the 'lighten' value provided has a predictable effect, but it seems random instead.

![image](https://user-images.githubusercontent.com/83022047/115875010-68371280-a40a-11eb-8193-5ac308f3c7d3.png)

**Comment by Vermilion755** [comment]
Looking at it again with the wrapping set to false, I think that will work for me. It's much more predictable. I think with wrapping on, it's very sporadic and should be investigated. Thanks!

**Comment by martynasma** [comment]
Well, it's definitely not random. I suppose that the "lightness" value of the source color is quite high, so it wraps around very soon.
