### ISSUE TITLE
Category labels disappear depending on container width

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#3476]
**Bug description**

I have reproduced the issue here: https://codepen.io/runfaj/pen/ZELVWWb

In this example, I have 2 charts. You can see the calculated minGridDistance is only 1px different and the chart's container is only 5px different between the 2 charts. However, for some reason in one chart the labels always appear and in the other, only half the labels appear.
![image](https://user-images.githubusercontent.com/3292053/115771647-71bd6d80-a36b-11eb-9cbd-ccc0a50adaa7.png)

Maybe there's some sort of internal calculation that is using subpixel placement instead of whole pixels, causing them to disappear? This seems to also be a probable indicator based on half of the vertical lines in the grid are also disappearing.

We've had several clients report this issue in our application for various chart widths, series types, and count of data points. Each case seems to be resolved by just adjusting the width a few pixels. However, there is no known standard on what to adjust this by because it seems to vary with each chart.

Mostly reproducing in latest chrome on mac or windows.

**Comment by martynasma** [comment]
That is weird. Both charts look identical to me:

![image](https://user-images.githubusercontent.com/1458520/115777348-d30e2c80-a3bd-11eb-8543-9e298c1df1a5.png)

Did you perhaps change something in CodePen? Does this still happening to you?

Also, if you are using retina screen, can you run this in your browser console?

```
window.devicePixelRatio
```

**Comment by runfaj** [comment]
@martynasma That is odd that it is different for you. For my example, I just opened up the codepen from https://www.amcharts.com/demos/simple-column-chart/ and modified to have the label calculation logic - no changes otherwise in codepen.

I just opened up this pen on 2 different computers and both are displaying the same behavior. Here's the stats:
- Computer 1: mac pro, chrome latest, window.devicePixelRatio=2. This has the retina display, but also happens on the 4k monitor attached, so the scaling at 2 is the same for both displays.
- Computer 2: windows 10, brave latest, window.devicePixelRatio=1. This has one monitor that is not retina or 4k (just a regular 1920x1080), so the scaling at 1 is correct.

**Comment by martynasma** [comment]
We will need to reproduce it somehow. Will keep you posted.

**Comment by martynasma** [comment]
OK, so we've investigated this further.

The different behavior is indeed caused by pixelRatio, but not directly. Since you have custom `minGridDistance` calculation mechanism, which relies on axis width, which in turn might be affected by pixel ratio when calculating fractional pixels.

That being said, the label algo seems to be working properly.

The issue is that your dynamic minGridDistance setting is rounded, but based on fractional widths, whereas checks in axis renderer are made against real widths, etc. There might be other similar tiny variations at play.

I suppose your better play would be not to round your calculated value, but rather `Math.floor()` it.

```JavaScript
const roundToNearest = 1;
outputWidth = Math.floor(outputWidth / roundToNearest) * roundToNearest;
```

**Comment by runfaj** [comment]
@martynasma I updated my example to include rounding, floor, and a neither option. In rendering 15 different charts at different sizes, it does appear that the floor fixes it! I'll close the issue and hopefully won't need to follow up after we test our existing issue charts for some of our clients!
