### ISSUE TITLE
Watermark logo still randomly appears on amchart map upon refreshing the page despite added license

### ISSUE THREAD

**Issue by ava8tor** [amcharts/amcharts4#3477]
I'm trying to use a amChart map for in the component of a application built using Angular 6. Before generating the map I'm employ a purchased license using am4core.addLincense("######") in order to remove the am4chart watermark logo attached to the map.

For the most part, this appears to remove watermark from the chart upon running the application. However, there are times where upon compiling or refreshing the application page, the watermark will sometimes randomly respawn despite the added license. 

Is there a way to ensure the map license is added and/or keep the watermark logo from appearing upon rendering the application?

**Comment by martynasma** [comment]
Hi there. Let's discuss license application issues over email. Could you please email us at contact@amcharts.com, as we may ask things that would not be suitable for posting publicly? Thanks!
