### ISSUE TITLE
Axis doesn't start from 0 in various screen sizes

### ISSUE THREAD

**Issue by monetree** [amcharts/amcharts4#3478]
<img width="1440" alt="Screenshot 2021-04-23 at 3 04 58 PM" src="https://user-images.githubusercontent.com/38796292/115852280-879f6100-a445-11eb-9733-dca6882c5a13.png">

` loadChart = () => {
    const { selectedDateScatterPlotData, onClickScatterPlotDot, onClickScatterPlotDotFetchLinks, grid } = this.props;

    let { chart } = this.state;

    am4core.ready(() => {
      chart = am4core.create("scatter-plot", am4charts.XYChart);

      let valueAxisX = chart.xAxes.push(new am4charts.ValueAxis());
      valueAxisX.renderer.ticks.template.disabled = true;
      valueAxisX.renderer.axisFills.template.disabled = true;
      valueAxisX.title.text = "Impact";
      valueAxisX.title.fontSize = "14px";
      valueAxisX.renderer.labels.template.fontSize = 12;
      // valueAxisX.extraMin = 0.2;
      // valueAxisX.extraMax = 0.2;
      valueAxisX.renderer.baseGrid.disabled = true;
      valueAxisX.renderer.grid.template.location = 0;

      let valueAxisY = chart.yAxes.push(new am4charts.ValueAxis());
      valueAxisY.renderer.ticks.template.disabled = true;
      valueAxisY.renderer.axisFills.template.disabled = true;
      valueAxisY.title.text = "Volume";
      valueAxisY.title.fontSize = "14px";
      valueAxisY.renderer.minGridDistance = 100;
      valueAxisY.renderer.labels.template.fontSize = 12;

      valueAxisY.events.on("ready", function(ev) {
        ev.target.min = ev.target.min-10;
        ev.target.max = ev.target.max+10;
      })

      let series = chart.series.push(new am4charts.LineSeries());
      series.dataFields.valueX = "Impact";
      series.dataFields.valueY = "Volume";
      series.dataFields.value = "bubbleSizeValue";
      series.strokeOpacity = 0;
      series.tooltip.pointerOrientation = "vertical";

      let bullet = series.bullets.push(new am4core.Circle());
      bullet.fill = am4core.color("#ff0000");
      bullet.propertyFields.fill = "color";
      bullet.strokeOpacity = 0;
      bullet.strokeWidth = 2;
      bullet.fillOpacity = 0.9;
      bullet.stroke = am4core.color("#ffffff");
      bullet.hiddenState.properties.opacity = 0;

      bullet.tooltipHTML = `
                <div>
                    {Page Name}
                </div>
            `;

      let outline = chart.plotContainer.createChild(am4core.Circle);
      outline.fillOpacity = 0;
      outline.strokeWidth = 3;
      outline.hide(0);

      let blurFilter = new am4core.BlurFilter();
      outline.filters.push(blurFilter);

      bullet.events.on("over", function (event) {
        let target = event.target;
        outline.radius = target.pixelRadius + 2;
        outline.x = target.pixelX;
        outline.y = target.pixelY;
        outline.show();
      });

      bullet.events.on("hit", (event) => {
        this.animateBullet(event.target);
        onClickScatterPlotDot(event.target.dataItem.dataContext["Page Name"]);
        onClickScatterPlotDotFetchLinks();

        if(new URLSearchParams(window.location.search).get("flow") === "service"){
          valueAxisY.renderer.minGridDistance = 50
          document.getElementById("filtersSection").style.display = "none"; 
          document.getElementById('toggle-button').style.display = "None";
        }

      });

      bullet.events.on("out", function (event) {
        outline.hide();
      });

      let hoverState = bullet.states.create("hover");
      hoverState.properties.fillOpacity = 1;
      hoverState.properties.strokeOpacity = 1;

      series.heatRules.push({
        target: bullet,
        min: 4,
        max: 5,
        property: "radius",
      });

      bullet.adapter.add("tooltipY", function (tooltipY, target) {
        return -target.bubbleSizeValue;
      });

      chart.cursor = new am4charts.XYCursor();
      chart.cursor.behavior = "zoomXY";
      chart.cursor.snapToSeries = series;
      chart.zoomOutButton.disabled = true;
      chart.cursor.behavior = "none";

      chart.data = selectedDateScatterPlotData;
      this.setState({ chart, chartScatterPointTemplate: bullet });
    });
  };

  animateBullet = (circle) => {
    const { currentDotAnimation, selectedDotElement } = this.state;
  
      if (_.isEmpty(selectedDotElement) || circle._uid !== selectedDotElement._uid) {
        if (currentDotAnimation) {
          currentDotAnimation._loop = 0
        }
  
        const animation = circle.animate(
          [
            { property: "scale", from: 2, to: 1 },
            { property: "opacity", from: 0.5, to: 1 },
          ],
          1000,
          am4core.ease.circleInOut,
    
        ).loop();
          animation._pause = false
  
        this.setState({currentDotAnimation: animation})
      }
  
      this.setState({
        selectedDotElement: circle
      })
    }
`

Here is my code for scatter plot. But, If you can see in above image i shared the point starts from 0.002 instead of 0.
It is coming fine on linux machine but, in mac or windows this is the problem..

Please let me know how can i fix it ?

**Comment by martynasma** [comment]
Can you doublecheck if you are running the latest amCharts 4 version (4.10.18)?

**Comment by monetree** [comment]
Yes, We are using

**Comment by martynasma** [comment]
Not sure, how this could be happening then.

Would you be able to create a runnable demo?

**Comment by monetree** [comment]
https://aide-demo.fractal.ai/identify/?flow=service&visitor_type=Customer&device_type=App&date=2021-03-10&kpi=service_journey_kpis&column=Self_Service_Rate


Check this link>.

aide
Aide@619

**Comment by martynasma** [comment]
Thanks. Unfortunately, I can't access or debug that. I'm going to have to ask you to provide a runnable version of this chart/data on CodePen or jsFiddle.

**Comment by monetree** [comment]
I have shared credentials to login. Please login
https://aide-demo.fractal.ai
Then visit above url


aide
Aide@619

**Comment by martynasma** [comment]
I meant I can't access the actual code.
