### ISSUE TITLE
am4charts.ValueAxis<am4charts.AxisRendererCircular> doesn't take into account extraMax/extraMin

### ISSUE THREAD

**Issue by ari62** [amcharts/amcharts4#3479]
**Bug description**
Hello, When working with the example for gauges:
https://www.amcharts.com/demos/angular-gauge-with-two-axes/

if you try to edit it to change the range to be outside of the default min/max and you change the code to be 
```
axis.extraMax = .2

axis.extraMin = .2

axis.strictMinMax = false;
```

Then according to the docs I would expect the axis scale to change:
https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Relatively_expanding_the_scale

However it stay's at min/max and the hands go off the axis. I don't know if extraMin/extraMax aren't supposed to be used with AxisRendererCircular.

**Additional context**
Here is the jsfiddle:
https://jsfiddle.net/s86jhz3u/5/

thank you

**Comment by martynasma** [comment]
It seems to be working for me.

With extraMin/extraMax the values range from -40 to 200.

Without: 0 to 160.
