### ISSUE TITLE
Question/Enhancement: Legend for ColumnSeries to display an entry for each category

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#348]
I'm creating a Legend for a ColumnSeries (in a XYChart) and would like the legend to display one entry for each column. This would mimic the behavior of a PieSeries (in a PieChart) where we also by default get a legend that displays an entry for each item in the series. 

Is it possible to do that with a setting on the legend/ColumnSeries? Or will I need to create a separate Series for each item?

In case I need to create a separate ColumnSeries for each item, how do I get the value of the respective item (the only one in the series) to be displayed in the legend?

**Comment by martynasma** [comment]
There's no setting for that, I'm afraid.

Creating series for each column certainly is an option.

Another option on the table is creating a legend with custom items:

https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items

If you need to allow users toggle items, I'd probably go with the first option, so you don't have to implement events to do actual toggling.

If you don't need toggling, second option is probably tidier.

Let me know if that makes sense.

**Comment by Chnoch** [comment]
Thanks for the options.
Since I do need the user to be able to toggle an item the custom items for the legend are probably gonna be quite hard to implement. I'll go forward with adding separate series for each column.

Two questions for that approach:

1. Currently every category has space to display a column for each series, however every series except one is normally empty. Is there a setting to disable this behavior? You can see an example here: https://codepen.io/chnoch/pen/dqKGKV (First category column is on the very left, second one centered and third one on the right. If possible all columns should be centered because all the other series are empty).

2. How can I get the value of the single column for each series to be displayed in the legend? I can't really use the `valueY` property, which makes sense, because on a whole series you can always have many entries with different values. Is it possible to add some kind of meta-data to the series and use these values in the legend?

Thanks for your help

**Comment by martynasma** [comment]
1. Yup, simply set `series.clustered = false` on each of your series.

2. `series.legendSettings.valueText = '{valueY.close}'` should do the trick. However, I can see there's a bug that the value is not being displayed initially, only after cursor interaction. It's a bug we're going to fix.

Make sure you subscribe to #351 for updates

**Comment by Chnoch** [comment]
Thanks, this is perfect! I've already found a workaround for #351 but it's good to know that it'll be resolved in the next release.

One more question (for now ;)): 
Is it possible to trigger the tooltip over the chart when hovering over the legend items? So that it would mimic the behavior of the donut chart where hovering over the legend displays the tooltip of the connected slice? Can I do something like this for each series as well?

**Comment by martynasma** [comment]
Ummm, you can do something like this:

```
chart.legend.itemContainers.template.events.on("over", function(ev) {
  chart.cursor.triggerMove(
    categoryAxis.categoryToPoint(
      categoryAxis.getPositionLabel(
        categoryAxis.indexToPosition(ev.target.dataItem.index)
      )
    ), "soft"
  );
});
```

A bit of a tangle, but doable. And I'm not sure if your example is how your chart will look like in the end. But it works:

https://codepen.io/team/amcharts/pen/qMyvWK?editors=0010

**Comment by Chnoch** [comment]
Thanks, this works well for what I'm looking for!
