### ISSUE TITLE
Multi-series shared tooltip value still show 2 tooltips instead of one

### ISSUE THREAD

**Issue by seta-sonvt** [amcharts/amcharts4#3480]
Hello, I try to using Multi-series shared tooltip value. There is some points that show 2 tooltips instead one. Can someone help me overcome this:

Pic: 
![Screenshot from 2021-04-26 12-20-20](https://user-images.githubusercontent.com/58415957/116032417-d89f9700-a689-11eb-980d-d3e5fcb7b387.png)

Code: https://codepen.io/kuroneko7601/pen/MWJxgxw

**Comment by martynasma** [comment]
Try this:

```
chart.cursor.maxTooltipDistance = -1; 
```

**Comment by seta-sonvt** [comment]
Thanks! It works correctly now
