### ISSUE TITLE
In chord diagram how can I hide links/relation if value range not fits with custom condition

### ISSUE THREAD

**Issue by lavkesh1608** [amcharts/amcharts4#3481]
**Question**

**Environment (if applicable)**

**Additional context**

Hi I am using chord diagram to display pearson coefficient relation between questions , but I want to display only those relation/node who fall between value range -0.5 to +0.5 

Is there a way to handle this ?
You may get more by seeing code snippet -
```
if(relationValue<-0.5 || relationValue>=0.5){

								chartData.push({

								"from":data[i].title,
								"to":data[j].title,								
								"value":relationValue
});

							}
```

**Comment by martynasma** [comment]
Do you want those values to still count toward the size of the node, but hide the link itself if it's small?

**Comment by lavkesh1608** [comment]
Yes hide the link iteself and hide the node also if node total is not fit into given range ? We want to display filtered node there only. Thanks

**Comment by martynasma** [comment]
How about not adding those to data at all then?

**Comment by lavkesh1608** [comment]
No that's not works I already tried that. As per my understanding when we hover on a node of chart , it shows total values, now I want to hide the node (after links counts) using total count value of node. Is there a property/method in `nodeTemplate`  to return true/false/hide for each node

**Comment by martynasma** [comment]
I suppose you can use an adapter for that:

```JavaScript
nodeTemplate.adapter.add("hidden", function(val, target) {
  console.log(target.dataItem.value)
  return target.dataItem.value < 20;
})
```
