### ISSUE TITLE
How to show data with time based

### ISSUE THREAD

**Issue by toriqsetiawan** [amcharts/amcharts4#3482]
**Question**
I have hourly data to show in the chart. but i can change the frequency. for example every 2 hours, 4 hours or 12 hours.
how to skip unused data from js config?

**Environment (if applicable)**
i'm using amcharts4-4.10.18

**Additional context**
```
let frequency = 1;
dateAxis.baseInterval = {
    timeUnit: frequency >= 24 ? "day" : "hour",
    count: frequency >= 24 ? 1 : frequency,
};
```
[Screenshot](https://monosnap.com/file/JjVsyMrpQLXxfvykXA7EWtt4fPw7rK)

**Comment by martynasma** [comment]
`baseInterval` is a setting that instructs your chart about granularity of your data. You should not "lie" to chart about it thinking it will take care of the display :)

Instead, you might need to check out [data item grouping](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping).
