### ISSUE TITLE
Can Sankey nodes be placed with offset or similar to improve visualization

### ISSUE THREAD

**Issue by iColdoCatalin** [amcharts/amcharts4#3484]
So the following data will generate the following attached Sankey diagram.
As you see link between B1 and B is a bit bad to see it that way. 
![sankeydiagram](https://user-images.githubusercontent.com/29724985/116225616-5929ca80-a752-11eb-863c-54fdbf949428.PNG)
But if you put B1 for example half way between A and B this would lead to a much better visualization.
Can this be achived? 

```
dataFromApi = [
  { from: "A", to: "B", total: 1 },
  { from: "A", to: "B1", total: 1 },
  { from: "B", to: "C", total: 1 },
  { from: "B1", to: "B", total: 1 },
  { from: "C", to: "D", total: 1 },
  { from: "D", to: "E", total: 1 },
  { from: "B1", to: "E", total: 1 }
];
```

**Comment by martynasma** [comment]
Maybe with an adapter:

```JavaScript
dataFromApi = [
  { from: "A", to: "B", total: 1 },
  { from: "A", to: "B1", total: 1 },
  { from: "B", to: "C", total: 1 },
  { from: "B1", to: "B", total: 1, dx: -100 },
  { from: "C", to: "D", total: 1 },
  { from: "D", to: "E", total: 1 },
  { from: "B1", to: "E", total: 1 }
];

nodeTemplate.adapter.add("dx", function(dx, target) {
  if (target.dataItem && target.dataItem.dataContext.dx) {
    return target.dataItem.dataContext.dx;
  }
  return dx;
})
```

**Comment by iColdoCatalin** [comment]
> Maybe with an adapter:
> 
> ```js
> dataFromApi = [
>   { from: "A", to: "B", total: 1 },
>   { from: "A", to: "B1", total: 1 },
>   { from: "B", to: "C", total: 1 },
>   { from: "B1", to: "B", total: 1, dx: -100 },
>   { from: "C", to: "D", total: 1 },
>   { from: "D", to: "E", total: 1 },
>   { from: "B1", to: "E", total: 1 }
> ];
> 
> nodeTemplate.adapter.add("dx", function(dx, target) {
>   if (target.dataItem && target.dataItem.dataContext.dx) {
>     return target.dataItem.dataContext.dx;
>   }
>   return dx;
> })
> ```

Can this feature (or something) be added automatically by Sankey diagram ? because it will be very difficult for us to check everytime the dataset for possible nodes on same level that are connected and that "maybe" will result in a bad visualization like the above picture...and maybe if they are on same level and connected the visualization is good but we cannot know that before...

**Comment by martynasma** [comment]
No, I'm afraid we do not plan on implementing any logical changes to SankeyDiagram for amCharts 4. Sorry :(
