### ISSUE TITLE
Force-directed-network : How can i stop all the child nodes from rendering together

### ISSUE THREAD

**Issue by Chinmay-k96** [amcharts/amcharts4#3485]
The nodes spread out along with the children all at once in a force-directed-network. Eg: if i have a node with 3 or 4 levels then all those levels are renderderd on the screen. I want the child nodes to spread only when i click on the node.

**Already tried -**
1) series.maxlevels = 1 --> this property only works for the first parent node level but when i click on the node, all the rest of the children spread out together for all subsequent levels

2) series.dataFields.collapsed="off" and "off" : true --> this one does not work the nodes are spread out irrespective o true or false value

If below is the node
![image](https://user-images.githubusercontent.com/62800512/116252316-16391880-a78d-11eb-90a8-e0531a1492a5.png)

This is what i expect when i click on the node
![image](https://user-images.githubusercontent.com/62800512/116252436-323cba00-a78d-11eb-81db-05090646eed8.png)

This is what i get
![image](https://user-images.githubusercontent.com/62800512/116252509-441e5d00-a78d-11eb-93cb-6300c09aea6b.png)

Please help with this

**Comment by martynasma** [comment]
You have misspelled the `maxLevels`. Note the camelCase syntax:

```
series.maxLevels = 1;
```

**Comment by Chinmay-k96** [comment]
ok may be its because i typed it, but in reality have used the camel case and it works only on the 1st parent node

**Comment by martynasma** [comment]
Gotcha. You can use node's setting `expandAll = false` if you need to open child nodes one by one, not the whole depth:

```JavaScript
series.nodes.template.expandAll = false;
```

**Comment by Chinmay-k96** [comment]
Thank you this helped
