### ISSUE TITLE
Relative offset for LineSeries?

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#3486]
Is there a way to align a line series to position over a specific stack of a column chart?

Basically (forgive my powerpoint) this:
![image](https://user-images.githubusercontent.com/564364/116311964-b6c51380-a760-11eb-96fa-8b20213fc4f8.png)

You see that line series are positioned central to the category cell, but we'd like to move each to be positioned over an individual column stack.

I've tried [dx](https://www.amcharts.com/docs/v4/reference/lineseries/#dx_property), it works (for the line, not the bullet), but only allows a pixel value, which won't work for a resizable / zoomable chart.

There's also a [startLocation](https://www.amcharts.com/docs/v4/tutorials/taming-the-step-line-series/#Adjusting_step_position) property of StepLineSeries, defined in 0..1 interval, which would be perfect — but it doesn't seem to exist for LineSeries.

Any help would be much appreciated.

**Comment by martynasma** [comment]
You may need [this](https://www.amcharts.com/docs/v4/concepts/series/#Data_item_locations).

**Comment by NPC** [comment]
@martynasma This is great, thank you so much!
