### ISSUE TITLE
am4core.options.queue does not render all LineSeries

### ISSUE THREAD

**Issue by robskidmore** [amcharts/amcharts4#3487]
**Bug description**

We calculate a trend line by adding a new LineSeries and giving it its own data after assigning data to the chart. This works without a hitch when `am4core.options.queue` is not enabled. When it is enabled, the trendline is only rendered on the first chart.

If you comment out `am4core.options.queue` on line 3 in the example then all of the trendlines are rendered.

Example: https://codepen.io/robskidmore/pen/yLgwXbO

**Environment**
amcharts 4.10.18

**Comment by martynasma** [comment]
That is because your loadTrendLine function kicks in before the cahrt is initialized and there's no data, hence no trend line.

You can fix that by wrapping it in an array:

```JavaScript
chart.events.once("ready", function() {
    loadTrendLine(chart, data);
})
```

**Comment by robskidmore** [comment]
Perfect. That worked. Thank you.
