### ISSUE TITLE
Showing changePercent value in legend for selected range by the range selector 

### ISSUE THREAD

**Issue by frnqs** [amcharts/amcharts4#3488]
Is it possible to configure chart so that the legend shows the percentage change selected by the range selector e.g. XY Line series chart?
Currently it only shows valueY.changePercent for value indicated by the cursor - the goal is to show changePercent for selected range when cursor is inactive or outside the chart.

**Comment by martynasma** [comment]
I don't think there's a built-in way to do that in legend. Sorry.
