### ISSUE TITLE
Candlestick Date range input to single Day Format

### ISSUE THREAD

**Issue by kaariwedoms** [amcharts/amcharts4#3489]
In my project requirement , i have a scenario where i need to plot candlestick mapping for single day (for ex: Today Date value timer seconds alone will change)
So i have manipulated date key value in json array as mentioned below in the reference image, and the approach didn't worked for me,
<img width="309" alt="datecs" src="https://user-images.githubusercontent.com/8941091/116376208-a5960880-a82d-11eb-997b-f6125020bf50.PNG">

kindly help me out to attain this

**Comment by martynasma** [comment]
I'm not sure I understand the question.

Do you mean you need to take open and close values for a single candle from two separate data points?

**Comment by kaariwedoms** [comment]
Well , i will try to explain elaborately

Here is my json array response, in which date key  value is  (2020-12-23)which is of same date in json array list as mentioned below, **but date key value will differ in terms of milliseconds/seconds/hours but the date remains constant**

{
    'date': '2020-12-23T12:49:56.213',
    'open': 136.65,
    'high': '136.96',
    'low': '134.15',
    'close': 136.65,
    'Volume': '28942700',
    'value': 'win'
  }, {
    'date': '2020-12-23T12:49:21.187',
    'open': 136.65,
    'high': '135.95',
    'low': '131.50',
    'close': 136.65,
    'Volume': '28942700',
    'value': 'win'
  },
{
    'date': '2020-12-23T12:09:21.187',
    'open': 136.65,
    'high': '135.95',
    'low': '131.50',
    'close': 136.65,
    'Volume': '28942700',
    'value': 'win'
  }

I need a workaround to show candle data mappings for single day where date value will vary in terms of secs/hour/milliseconds

currently it works well with below json response
you can see the date value in below response where date value is not same in the array list , 
**here index[0] has ['date': '2018-08-01',] index[1] has ['date': '2018-08-02',]**
{
    'date': '2018-08-01',
    'open': 136.65,
    'high': '136.96',
    'low': '134.15',
    'close': 136.65,
    'Volume': '28942700',
    'value': 'win'
  }, {
    'date': '2018-08-02',
    'open': 136.65,
    'high': '135.95',
    'low': '131.50',
    'close': 136.65,
    'Volume': '28942700',
    'value': 'win'
  }, {
    'date': '2018-08-05',
    'open': 136.65,
    'high': '136.86',
    'low': '132.00',
    'close': 136.65,
    'Volume': '28942700',
    'value': 'win'
  }

but in my requirement i am looking for workaround, in which date value will be constant for ex(Today) i need to differentiate in terms of hours/seconds etc (Single day report)

pls, let know if u need any clarification too

**Comment by martynasma** [comment]
Looks like you need [data item grouping](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping).

P.S. date-based data needs to be in ascending order, so you will need to reverse your first data set.
