### ISSUE TITLE
How to set link min width on a sankey chart?

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3491]
Hi,

I'm trying to figure out a way to set a min stroke width when using SankeyChart. I read on the website docs about `middleLine` but I prefer to have amcharts use as much strokeWidth as possible for the most important links, while the other less improtant link would take a minimum stroke width. My attempt on `middleLine` usage forced all lines to have the same width.

Can that be achieved?

Tried the following but it doesn't seem to be picked

![image](https://user-images.githubusercontent.com/40542072/116412341-43460380-a83f-11eb-9674-852685f7c972.png)

My chart issue shown below

![image](https://user-images.githubusercontent.com/40542072/116412451-61136880-a83f-11eb-86e6-d5b2b0370126.png)

**Comment by martynasma** [comment]
The solution in this case would be to add actual stroke on the links.

And you could have adapter to disable stroke from links that have actual fill width. E.g.:

```JavaScript
linkTemplate.strokeWidth = 1;
linkTemplate.adapter.add("stroke", function(stroke, target) {
  var h = Math.abs(target.linkWidth);
  if (h < 2) {
    target.strokeOpacity = 0.25;
    return target.fill;
  }
  else {
    target.strokeOpacity = 0;
    return stroke;
  }
});
```

Example:
https://codepen.io/team/amcharts/pen/c64bf3d0af594084e9c228ada4ed7f9d?editors=0010

**Comment by teodosii** [comment]
Thank you, that worked great!
