### ISSUE TITLE
Could not find root error after re creating chart on jquery success request.

### ISSUE THREAD

**Issue by SiIverHawk** [amcharts/amcharts4#3493]
I'm having an issue when I try to re render a line graph right after an ajax request is completed. I always get "uncaught error: could not find root" I know it is a problem with `chart.cursor = new am4charts.XYCursor();` I tried to disposed and recreating a new chart instance and it doesn't work.

This is how I create a chart instance:
` 
    
    chart = am4core.create("chartdiv-" + tabNumber, am4charts.XYChart);
    if($(link).attr('data-apply-filter') === 1)
    {
      chart.dispose();
      chart = am4core.create("chartdiv-" + tabNumber, am4charts.XYChart);
    }`

note: `$(link).attr('data-apply-filter')` is always to 1 when clicking a filter button and then returns to 0 when AJAX request is completed

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by SiIverHawk** [comment]
I tried to simulate the error on [this jsfiddle](https://jsfiddle.net/MikkelVI/qpt8exr9/1/) it doens't matter if the data don't show as intended. You just have to click chart 1 then chart 2 or apply filters and watch the console for the script error. The error is **Uncaught Error: Could not find root** related to the XYCursor object.

**Comment by SiIverHawk** [comment]
Updating libraries did the thing and disposed properly.
