### ISSUE TITLE
Gauge chart handling range clicks

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#3494]
Hi,

I have a gauge chart (similar to this [one](https://www.amcharts.com/demos/gauge-with-bands/)) and want to bind an event listener to each range's _hit_ event so I can display a colour picker, allowing the user to change the colour of the particular range.

I already do this successfully on bar, column and pie charts but, alas, not gauges.

I have tried to do this by doing the following but it is not working because the _hit_ event isn't accepted:

```
const range = axis.axisRanges.create();
range.events.on("hit", ...);
```

Is there an easier way? Do you have any advice please?

**Comment by martynasma** [comment]
Try this:

```JavaScript
range.axisFill.interactionsEnabled = true;
range.axisFill.events.on("hit", function(ev) {
  console.log("click")
})
```

**Comment by jbate** [comment]
Genius! :)

Thanks, as always, for the super speedy response @martynasma!
