### ISSUE TITLE
What is the best way to render multiple charts at the same time and avoid freezes?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3495]
I have a dashboard that can hava multiple charts, each chart is feeded with data fetched assynchounsly. 
When the data request is finished a function is called to build the chart. But multiple charts rendering at same time makes my app freezes for some secs. I think maybe this is not the best way to do this

Could someone helps me? Thanks

**Comment by martynasma** [comment]
Maybe you can implement some kind of queue mechanism for updates.

E.g. there's an array you push updates to, then update charts one-by-one. Update first chart, wait for its `datavalidated` event, proceed to another update in the queue.
