### ISSUE TITLE
Can't render my country map

### ISSUE THREAD

**Issue by SiIverHawk** [amcharts/amcharts4#3496]
I started to do heat maps for my country. I grabbed the heat map example in the website and I changed the geodata script, map definitions and projections in the code and the map isn't rendering only the heatmap scale.

I'm providing my testing on [fiddlejs](https://jsfiddle.net/MikkelVI/xh5wre68/1/)

**Comment by martynasma** [comment]
AlbersUSA projection can only be used with the maps of the United States. It won't work for any other region.

You can use any other projection for this map.

**Comment by SiIverHawk** [comment]
> AlbersUSA projection can only be used with the maps of the United States. It won't work for any other region.
> 
> You can use any other projection for this map.

I tried with Albers and it didn't work neither.

**Comment by martynasma** [comment]
Albers projection is not suitable for individual countries, either. It's meant for the whole world.

I'm not sure why you need the projection setting for your map at all. For small countries, default equirectangular projection should be perfect.

Just remove the projection line from your code.
