### ISSUE TITLE
Is there any way to force sankey diagram fit into a container?

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3497]
Hi (again!)

Below is my issue shown (with horizontal scrollbar)
![image](https://user-images.githubusercontent.com/40542072/116676591-d4d48300-a9af-11eb-94e0-1c5325ed4c81.png)

The chart is shown in 2 ways, one would be at its full size where it gets as much vertical space as needed, and the other is as a widget which is a much smaller version like above.

There's some padding logic based on the number of nodes since each node gets shifted down by the rectangle labels.
Is there any way to force it fit into its container? `maxHeight` doesn't seem to address this issue. Since sankey doesn't have a scrollbar functionality, is there any other way?

DOM element is shown below, set to relative positioning with a set width
![image](https://user-images.githubusercontent.com/40542072/116676982-55937f00-a9b0-11eb-8c87-49e1ee16dd01.png)

Thank you

**Comment by martynasma** [comment]
Default padding between nodes is 20px.

You can set it using chart's `nodePadding` property:

```
chart.nodePadding = 5;
```

That will give more space to draw actual nodes in crammed height.
