### ISSUE TITLE
Disabled property not removing from layout when set after chart has rendered

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#35]
Setting the `disabled` property does not seem to work as I expect based on the documentation:

> Controls if element is disabled.
> 
> A disabled element is hidden, and is removed from any processing, layout calculations, and generally treated like if it does not existed.
> 
> The element itself is not destroyed, though. Setting this back to false, will "resurrect" the element.

I read this as that setting `disabled=true` should be like setting the CSS `display:none` on an HTML element, in that the element should be treated as it does not exist.

If I disable an element when initializing an object, it works as I expect.

However, if I set the `disabled` property on a chart that has already rendered, the sprite is just "hidden", the rest of the chart does not reflow to account for the item no longer being enabled.

This makes trying to hide/show elements (like a legend) very difficult. I'm trying to adjust certain elements availability based on the current dimensions of a chart, which can change in realtime.

**Comment by martynasma** [comment]
Solved in [4.0.0-beta.28](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.28) ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta28---2018-06-05)).

**Comment by dswitzer** [comment]
Great work! This seems to be working for me now for the test cases I have.
