### ISSUE TITLE
TreeMap suppress top level drill down on doublehit event

### ISSUE THREAD

**Issue by QadiymStewart** [amcharts/amcharts4#3500]
Currently need a way to suppress the default drill down on single click when doublehit event is triggered for the TreeMap top-level item. Any help is welcomed.

**Comment by martynasma** [comment]
Something like this:

```JavaScript
function prepSeries(seriesTemplate) {
  seriesTemplate.columns.template.events.on("ready", function(ev) {
    var column = ev.target;
    column.events.disableType("hit");
    column.events.on("doublehit", function(ev) {
      chart.zoomToSeriesDataItem(column.dataItem)
    })
  })
}

prepSeries(level0SeriesTemplate);
prepSeries(level1SeriesTemplate);
prepSeries(level2SeriesTemplate);
```

**Comment by QadiymStewart** [comment]
@martynasma Thanks for the suggestion but I still need the hit event to do the default drill down. Only need to suppress the hit event when double click is raised. What's happening is that when I double click both hit and double hit event are raised. Hit causes the TreeMap to drill down and then double hit I have a custom function.

In the code you provided you disabled hit and doubleclick now does the drill down. I need hit enabled and suppressed if double click is raised.

**Comment by martynasma** [comment]
Hm, not sure if that's possible. Sorry :(
