### ISSUE TITLE
How to use images in local folder for force-directed-tree 

### ISSUE THREAD

**Issue by Chinmay-k96** [amcharts/amcharts4#3501]
In force-directed-tree, we can use images instead of standard nodes but how to use images from local folder

**Comment by martynasma** [comment]
You can use images form local folders by pointing them using `file:///` URL notation instead of `http://`.

**Comment by Chinmay-k96** [comment]
can u please show an example. Its not clear..... i am  not able to get  the file this way

**Comment by martynasma** [comment]
Well, if you are able to display images with "http://xxxxxxxxx" URLs then you can just replace them with "file:///C:\xxxxxxxx" to point to local files.

That being said, it does not make a lot of sense, because it won't work on internet, naturally.

**Comment by Chinmay-k96** [comment]
I am getting the below output, th image is not being loaded

![image](https://user-images.githubusercontent.com/62800512/116980137-7e36b400-ace3-11eb-8e03-c2b3f1a53437.png)

**Comment by martynasma** [comment]
Well, then there is no image file with the URL you have supplied on the computer that is viewing your page with the chart.

I'm not sure what to else to say. Using local file son a web page does not make sense.

**Comment by Chinmay-k96** [comment]
Ok then i have to uplaod my local images or svg to a webserver and then use the web url ?

**Comment by martynasma** [comment]
Yes, that would be the correct way to do that.

**Comment by Chinmay-k96** [comment]
ok i had one more thought what i i had an svg like below. how can i use it

I have tried the path feature 

let icon = series.nodes.template.createChild(am4core.Sprite);
icon.propertyFields.path = "path";
icon.horizontalCenter = "middle";
icon.verticalCenter = "middle";

But this dose not work it only excepts  values like this --> "M1093.517,578.324l.714,14.148,20.61,3.627s-2.534,20.137-22.493,19.625-19.623-30.748-19.623-30.748Z" but my svg has lot of other things.....can i use the svg pasted below in any other way

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="44.117" height="44" viewBox="0 0 44.117 44"><defs><style>.a{fill:#fff;opacity:0.305;}.b{fill:#202022;}.c,.h{fill:#008cff;}.d,.e,.f,.g,.j,.l{fill:none;}.d,.g{stroke:#008cff;}.d{stroke-width:0.5px;opacity:0.283;}.e{stroke:#ebebeb;stroke-dasharray:10;opacity:0.674;}.g,.j{stroke-width:3px;stroke-dasharray:3 2;}.h{opacity:0.676;}.i{opacity:0.996;clip-path:url(#a);}.j{stroke:#5d5d5d;}.k,.m{stroke:none;}.m{fill:#008cff;}</style><clipPath id="a"><path class="a" d="M1093.517,578.324l.714,14.148,20.61,3.627s-2.534,20.137-22.493,19.625-19.623-30.748-19.623-30.748Z" transform="translate(-24.517 -3)"/></clipPath></defs><g transform="translate(-1048.208 -573.029)"><circle class="b" cx="22" cy="22" r="22" transform="translate(1048.324 573.029)"/><circle class="c" cx="6" cy="6" r="6" transform="translate(1063 588)"/><g class="d" transform="translate(1057 582)"><circle class="k" cx="12" cy="12" r="12"/><circle class="l" cx="12" cy="12" r="11.75"/></g><g class="e" transform="translate(1060 585)"><circle class="k" cx="9" cy="9" r="9"/><circle class="l" cx="9" cy="9" r="8.5"/></g><g class="f" transform="translate(1050 575)"><path class="k" d="M19,0A19,19,0,1,1,0,19,19,19,0,0,1,19,0Z"/><path class="m" d="M 19 0.5 C 16.50230026245117 0.5 14.07957077026367 0.9890708923339844 11.79911994934082 1.953620910644531 C 9.596210479736328 2.885368347167969 7.61768913269043 4.2193603515625 5.918521881103516 5.918521881103516 C 4.2193603515625 7.61768913269043 2.885368347167969 9.596210479736328 1.953620910644531 11.79911994934082 C 0.9890708923339844 14.07957077026367 0.5 16.50230026245117 0.5 19 C 0.5 21.49769973754883 0.9890708923339844 23.92042922973633 1.953620910644531 26.20088005065918 C 2.885368347167969 28.40378952026367 4.2193603515625 30.38230895996094 5.918521881103516 32.08148193359375 C 7.61768913269043 33.7806396484375 9.596210479736328 35.11463165283203 11.79911994934082 36.04637908935547 C 14.07957077026367 37.01092910766602 16.50230026245117 37.5 19 37.5 C 21.49769973754883 37.5 23.92042922973633 37.01092910766602 26.20088005065918 36.04637908935547 C 28.40378952026367 35.11463165283203 30.38230895996094 33.7806396484375 32.08148193359375 32.08148193359375 C 33.7806396484375 30.38230895996094 35.11463165283203 28.40378952026367 36.04637908935547 26.20088005065918 C 37.01092910766602 23.92042922973633 37.5 21.49769973754883 37.5 19 C 37.5 16.50230026245117 37.01092910766602 14.07957077026367 36.04637908935547 11.79911994934082 C 35.11463165283203 9.596210479736328 33.7806396484375 7.61768913269043 32.08148193359375 5.918521881103516 C 30.38230895996094 4.2193603515625 28.40378952026367 2.885368347167969 26.20088005065918 1.953620910644531 C 23.92042922973633 0.9890708923339844 21.49769973754883 0.5 19 0.5 M 19 0 C 29.49341011047363 0 38 8.506589889526367 38 19 C 38 29.49341011047363 29.49341011047363 38 19 38 C 8.506589889526367 38 0 29.49341011047363 0 19 C 0 8.506589889526367 8.506589889526367 0 19 0 Z"/></g><g class="g" transform="translate(1052 577)"><circle class="k" cx="17" cy="17" r="17"/><circle class="l" cx="17" cy="17" r="15.5"/></g><circle class="h" cx="6" cy="6" r="6" transform="translate(1063 588)"/><g class="i"><g class="j" transform="translate(1052 577)"><circle class="k" cx="17" cy="17" r="17"/><circle class="l" cx="17" cy="17" r="15.5"/></g></g></g></svg>`

**Comment by martynasma** [comment]
Yes, but you will need to Base64-encode the SVG.

You can use a tool like this:
https://dopiaza.org/tools/datauri/index.php

Use output as `href` in an `Image` object.

```
let icon = series.nodes.template.createChild(am4core.Image);
icon.href = "data:image/svg+xml;charset=utf-8;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iNDQuMTE3IiBoZWlnaHQ9IjQ0IiB2aWV3Qm94PSIwIDAgNDQuMTE3IDQ0Ij48ZGVmcz48c3R5bGU+LmF7ZmlsbDojZmZmO29wYWNpdHk6MC4zMDU7fS5ie2ZpbGw6IzIwMjAyMjt9LmMsLmh7ZmlsbDojMDA4Y2ZmO30uZCwuZSwuZiwuZywuaiwubHtmaWxsOm5vbmU7fS5kLC5ne3N0cm9rZTojMDA4Y2ZmO30uZHtzdHJva2Utd2lkdGg6MC41cHg7b3BhY2l0eTowLjI4Mzt9LmV7c3Ryb2tlOiNlYmViZWI7c3Ryb2tlLWRhc2hhcnJheToxMDtvcGFjaXR5OjAuNjc0O30uZywuantzdHJva2Utd2lkdGg6M3B4O3N0cm9rZS1kYXNoYXJyYXk6MyAyO30uaHtvcGFjaXR5OjAuNjc2O30uaXtvcGFjaXR5OjAuOTk2O2NsaXAtcGF0aDp1cmwoI2EpO30uantzdHJva2U6IzVkNWQ1ZDt9LmssLm17c3Ryb2tlOm5vbmU7fS5te2ZpbGw6IzAwOGNmZjt9PC9zdHlsZT48Y2xpcFBhdGggaWQ9ImEiPjxwYXRoIGNsYXNzPSJhIiBkPSJNMTA5My41MTcsNTc4LjMyNGwuNzE0LDE0LjE0OCwyMC42MSwzLjYyN3MtMi41MzQsMjAuMTM3LTIyLjQ5MywxOS42MjUtMTkuNjIzLTMwLjc0OC0xOS42MjMtMzAuNzQ4WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTI0LjUxNyAtMykiLz48L2NsaXBQYXRoPjwvZGVmcz48ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMTA0OC4yMDggLTU3My4wMjkpIj48Y2lyY2xlIGNsYXNzPSJiIiBjeD0iMjIiIGN5PSIyMiIgcj0iMjIiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDEwNDguMzI0IDU3My4wMjkpIi8+PGNpcmNsZSBjbGFzcz0iYyIgY3g9IjYiIGN5PSI2IiByPSI2IiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMDYzIDU4OCkiLz48ZyBjbGFzcz0iZCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTA1NyA1ODIpIj48Y2lyY2xlIGNsYXNzPSJrIiBjeD0iMTIiIGN5PSIxMiIgcj0iMTIiLz48Y2lyY2xlIGNsYXNzPSJsIiBjeD0iMTIiIGN5PSIxMiIgcj0iMTEuNzUiLz48L2c+PGcgY2xhc3M9ImUiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDEwNjAgNTg1KSI+PGNpcmNsZSBjbGFzcz0iayIgY3g9IjkiIGN5PSI5IiByPSI5Ii8+PGNpcmNsZSBjbGFzcz0ibCIgY3g9IjkiIGN5PSI5IiByPSI4LjUiLz48L2c+PGcgY2xhc3M9ImYiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDEwNTAgNTc1KSI+PHBhdGggY2xhc3M9ImsiIGQ9Ik0xOSwwQTE5LDE5LDAsMSwxLDAsMTksMTksMTksMCwwLDEsMTksMFoiLz48cGF0aCBjbGFzcz0ibSIgZD0iTSAxOSAwLjUgQyAxNi41MDIzMDAyNjI0NTExNyAwLjUgMTQuMDc5NTcwNzcwMjYzNjcgMC45ODkwNzA4OTIzMzM5ODQ0IDExLjc5OTExOTk0OTM0MDgyIDEuOTUzNjIwOTEwNjQ0NTMxIEMgOS41OTYyMTA0Nzk3MzYzMjggMi44ODUzNjgzNDcxNjc5NjkgNy42MTc2ODkxMzI2OTA0MyA0LjIxOTM2MDM1MTU2MjUgNS45MTg1MjE4ODExMDM1MTYgNS45MTg1MjE4ODExMDM1MTYgQyA0LjIxOTM2MDM1MTU2MjUgNy42MTc2ODkxMzI2OTA0MyAyLjg4NTM2ODM0NzE2Nzk2OSA5LjU5NjIxMDQ3OTczNjMyOCAxLjk1MzYyMDkxMDY0NDUzMSAxMS43OTkxMTk5NDkzNDA4MiBDIDAuOTg5MDcwODkyMzMzOTg0NCAxNC4wNzk1NzA3NzAyNjM2NyAwLjUgMTYuNTAyMzAwMjYyNDUxMTcgMC41IDE5IEMgMC41IDIxLjQ5NzY5OTczNzU0ODgzIDAuOTg5MDcwODkyMzMzOTg0NCAyMy45MjA0MjkyMjk3MzYzMyAxLjk1MzYyMDkxMDY0NDUzMSAyNi4yMDA4ODAwNTA2NTkxOCBDIDIuODg1MzY4MzQ3MTY3OTY5IDI4LjQwMzc4OTUyMDI2MzY3IDQuMjE5MzYwMzUxNTYyNSAzMC4zODIzMDg5NTk5NjA5NCA1LjkxODUyMTg4MTEwMzUxNiAzMi4wODE0ODE5MzM1OTM3NSBDIDcuNjE3Njg5MTMyNjkwNDMgMzMuNzgwNjM5NjQ4NDM3NSA5LjU5NjIxMDQ3OTczNjMyOCAzNS4xMTQ2MzE2NTI4MzIwMyAxMS43OTkxMTk5NDkzNDA4MiAzNi4wNDYzNzkwODkzNTU0NyBDIDE0LjA3OTU3MDc3MDI2MzY3IDM3LjAxMDkyOTEwNzY2NjAyIDE2LjUwMjMwMDI2MjQ1MTE3IDM3LjUgMTkgMzcuNSBDIDIxLjQ5NzY5OTczNzU0ODgzIDM3LjUgMjMuOTIwNDI5MjI5NzM2MzMgMzcuMDEwOTI5MTA3NjY2MDIgMjYuMjAwODgwMDUwNjU5MTggMzYuMDQ2Mzc5MDg5MzU1NDcgQyAyOC40MDM3ODk1MjAyNjM2NyAzNS4xMTQ2MzE2NTI4MzIwMyAzMC4zODIzMDg5NTk5NjA5NCAzMy43ODA2Mzk2NDg0Mzc1IDMyLjA4MTQ4MTkzMzU5Mzc1IDMyLjA4MTQ4MTkzMzU5Mzc1IEMgMzMuNzgwNjM5NjQ4NDM3NSAzMC4zODIzMDg5NTk5NjA5NCAzNS4xMTQ2MzE2NTI4MzIwMyAyOC40MDM3ODk1MjAyNjM2NyAzNi4wNDYzNzkwODkzNTU0NyAyNi4yMDA4ODAwNTA2NTkxOCBDIDM3LjAxMDkyOTEwNzY2NjAyIDIzLjkyMDQyOTIyOTczNjMzIDM3LjUgMjEuNDk3Njk5NzM3NTQ4ODMgMzcuNSAxOSBDIDM3LjUgMTYuNTAyMzAwMjYyNDUxMTcgMzcuMDEwOTI5MTA3NjY2MDIgMTQuMDc5NTcwNzcwMjYzNjcgMzYuMDQ2Mzc5MDg5MzU1NDcgMTEuNzk5MTE5OTQ5MzQwODIgQyAzNS4xMTQ2MzE2NTI4MzIwMyA5LjU5NjIxMDQ3OTczNjMyOCAzMy43ODA2Mzk2NDg0Mzc1IDcuNjE3Njg5MTMyNjkwNDMgMzIuMDgxNDgxOTMzNTkzNzUgNS45MTg1MjE4ODExMDM1MTYgQyAzMC4zODIzMDg5NTk5NjA5NCA0LjIxOTM2MDM1MTU2MjUgMjguNDAzNzg5NTIwMjYzNjcgMi44ODUzNjgzNDcxNjc5NjkgMjYuMjAwODgwMDUwNjU5MTggMS45NTM2MjA5MTA2NDQ1MzEgQyAyMy45MjA0MjkyMjk3MzYzMyAwLjk4OTA3MDg5MjMzMzk4NDQgMjEuNDk3Njk5NzM3NTQ4ODMgMC41IDE5IDAuNSBNIDE5IDAgQyAyOS40OTM0MTAxMTA0NzM2MyAwIDM4IDguNTA2NTg5ODg5NTI2MzY3IDM4IDE5IEMgMzggMjkuNDkzNDEwMTEwNDczNjMgMjkuNDkzNDEwMTEwNDczNjMgMzggMTkgMzggQyA4LjUwNjU4OTg4OTUyNjM2NyAzOCAwIDI5LjQ5MzQxMDExMDQ3MzYzIDAgMTkgQyAwIDguNTA2NTg5ODg5NTI2MzY3IDguNTA2NTg5ODg5NTI2MzY3IDAgMTkgMCBaIi8+PC9nPjxnIGNsYXNzPSJnIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMDUyIDU3NykiPjxjaXJjbGUgY2xhc3M9ImsiIGN4PSIxNyIgY3k9IjE3IiByPSIxNyIvPjxjaXJjbGUgY2xhc3M9ImwiIGN4PSIxNyIgY3k9IjE3IiByPSIxNS41Ii8+PC9nPjxjaXJjbGUgY2xhc3M9ImgiIGN4PSI2IiBjeT0iNiIgcj0iNiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTA2MyA1ODgpIi8+PGcgY2xhc3M9ImkiPjxnIGNsYXNzPSJqIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMDUyIDU3NykiPjxjaXJjbGUgY2xhc3M9ImsiIGN4PSIxNyIgY3k9IjE3IiByPSIxNyIvPjxjaXJjbGUgY2xhc3M9ImwiIGN4PSIxNyIgY3k9IjE3IiByPSIxNS41Ii8+PC9nPjwvZz48L2c+PC9zdmc+";
```

**Comment by Chinmay-k96** [comment]
Tried it, its not working

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Chinmay-k96** [comment]
The below link from amcharts will do just fine

https://codepen.io/team/amcharts/pen/bJwgVP 

If you can replace the nodes with the attached file, i will be very thank full to you . I have attached a text document because svg is not an acceptable format to upload here........Please change the format to svg or create an svg file using the code inside the text document

[healthy.txt](https://github.com/amcharts/amcharts4/files/6421615/healthy.txt)

**Comment by martynasma** [comment]
Here's a version of the demo with Chrome node replaced with your data:uri'ied SVG:

https://codepen.io/team/amcharts/pen/6b4ef9c19ade1bd6ac459ec0655978db

**Comment by Chinmay-k96** [comment]
did u do any changes to the data output from base64 encoding

**Comment by martynasma** [comment]
No, I just copied it as is into the website I posted link to earlier.

Just make sure you specify proper content type. For SVG that's "image/svg+xml".

**Comment by Chinmay-k96** [comment]
ok thank you........................ can i use both the path feature and image feature together and included whichever i want

i mean both let icon = series.nodes.template.createChild(am4core.Sprite); and let icon = series.nodes.template.createChild(am4core.Image);

**Comment by martynasma** [comment]
Yes. For path you use `Sprite`. For images `Image`.

**Comment by Chinmay-k96** [comment]
Thank you so much for everthing......Its people like you who are motivating the growth of developers..........thank you for you time.

Need one more help.................. please help with this issue --> https://github.com/amcharts/amcharts4/issues/3506
