### ISSUE TITLE
Map chart shows unwanted color suddenly 

### ISSUE THREAD

**Issue by barwalker** [amcharts/amcharts4#3502]
Hi,
My map color doesn’t show correctly. In my machine, it's always blue. But in some other machines, it turns into green.
It’s the browser's issue, isn’t it?
How to fix the chart color to Blue?
Here is the screenshot, I want to fix the color on the right hand side.
[Screenshot](https://ibb.co/2ySZbR6)
Thanks

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by barwalker** [comment]
Well, I found the problem. It's because there is one chart using Material theme and it has been cached somehow.
I use this code below to make sure the Map chart doesn’t take any other's config:
```
am4core.unuseAllThemes();
am4core.useTheme(am4themes_animated);
```
And it works. Thanks.
