### ISSUE TITLE
Using separate values for plotting and labelling and non-monotonic plotting

### ISSUE THREAD

**Issue by MikamB** [amcharts/amcharts4#3505]
Is it possible to change the labels on an axis?

I'm plotting my data points chronologically in the order they were collected, but they are referred to and known by a non-chronological (and sometimes duplicated) numerical label in coordination with the time collected.

I would like to display the non-chronological label on the axis instead of the chronological order value, which is meaningless.

**Comment by martynasma** [comment]
Yes, just use `CategoryAxis`.
