### ISSUE TITLE
State management in force-directed-tree

### ISSUE THREAD

**Issue by Chinmay-k96** [amcharts/amcharts4#3506]
How do i manage the state of an expanded node for a particular node

Example -

I am in a page where I am displaying the force-directed-network graph. I click on a node which expands into 4 nodes. Then I click on one of those 4 nodes and that takes me to another page where some other info is displayed. Then I come back to the page of the force-directed-network graph. Now i want the same node (or nodes) which I expanded to be expanded and others to be closed i:e the state of the nodes should be maintained. Now I can use redux to store the values of the node but how do I tell the chart to expand specific nodes.

**state before clicking** 
![image](https://user-images.githubusercontent.com/62800512/117034400-e657bb00-ad20-11eb-84e9-b144fd2d2266.png)

**different page loads when i click on "salty"**
![image](https://user-images.githubusercontent.com/62800512/117034755-3f275380-ad21-11eb-802a-1318ff398d0e.png)

**now when i go back i need it look same as first image**
![image](https://user-images.githubusercontent.com/62800512/117034896-62520300-ad21-11eb-8124-0f66f5c39714.png)

I am not getting any way to specifically expand the nodes which I want without clicking them......please help here

**Comment by martynasma** [comment]
You can use series `dataFields.collapsed` data fields to point which field in data indicates non-collapsed nodes.

https://www.amcharts.com/docs/v4/chart-types/force-directed/#Setting_data_fields

```JavaScript
networkSeries.dataFields.collapsed = "collapsed";
```

Then just add `collapsed: false` to data for nodes that need to be expanded on load.

**Comment by Chinmay-k96** [comment]
It does not work ................. series.maxLevels takes the higher edge.........it dosent matter if the collapsed is true or false, if series.maxlevels = 1 then only one node will be present and if it is 3 or 4 then all the nodes will be expanded irrespective of what the child nodes collapsed property is assigned

**Comment by martynasma** [comment]
In that case you might get rid of the `maxLevels` and add collapsed value to each node as per requirement.

**Comment by Chinmay-k96** [comment]
Thank you so much

**Comment by Mechman** [comment]
Hi! How to do the same in Amcharts 5?
I tried collapsed: true and disabled:true. It didn't work.

Here is an example: https://codepen.io/mechman/pen/rNJVjKO?editors=0010
I run through all the nodes and I need to find out which ones are collapsed, which ones are expanded.

1. How do I find out it?
2. How can I specify in the incoming data which nodes are expanded and which are collapsed?
