### ISSUE TITLE
Date Axis doesn't zoom to explicitly defined zoom range when using data grouping

### ISSUE THREAD

**Issue by redc2** [amcharts/amcharts4#3507]
When groupData is set to true in DateAxis and its zoom range is outside the date range of data points, the chart still displays the temporally nearest data point and its date. This pen should show what I mean: https://codepen.io/redc22/pen/abJoWXR.

When dateAxis.groupData is set to false, the chart zoom range works as expected (date axis displays the correct zoom range and no data points are visible as there is no data in the zoom range).

Is this intended behavior and how could I make sure that only the explicitly defined date axis zoom range and its corresponding data is visible when groupData = true?

**Comment by martynasma** [comment]
I'm afraid the `DateAxis` can't zoom past actual range when data grouping is enabled.
