### ISSUE TITLE
start position of openDateX and dateX is wrong in column series

### ISSUE THREAD

**Issue by future11** [amcharts/amcharts4#3508]
Here is the code snippet for a waterfall chart. In this chart, start position and end position of column bar in x-axis (Date Axis) is mismatch. I am not sure if this is a bug or wrong settings in this code. I need your help.

chart.data = [ {
  category: "Net revenue",
  date: "2021-04-10",
  openDate: "2021-04-09",
  value: 8786,
  open: 0,
  stepValue: 8786,
  color: chart.colors.getIndex( 13 ),
  displayValue: 8786
}, {
  category: "Cost of sales",
  date: "2021-04-12",
  openDate: "2021-04-10",
  value: 8786 - 2786,
  open: 8786,
  stepValue: 8786 - 2786,
  color: chart.colors.getIndex( 8 ),
  displayValue: 2786
}, {
  category: "Operating expenses",
  date: "2021-04-13",
  openDate: "2021-04-12",
  value: 8786 - 2786 - 1786,
  open: 8786 - 2786,
  stepValue: 8786 - 2786 - 1786,
  color: chart.colors.getIndex( 9 ),
  displayValue: 1786
}, {
  category: "Amortisation",
  date: "2021-04-16",
  openDate: "2021-04-13",
  value: 8786 - 2786 - 1786 - 453,
  open: 8786 - 2786 - 1786,
  stepValue: 8786 - 2786 - 1786 - 453,
  color: chart.colors.getIndex( 10 ),
  displayValue: 453
}, {
  category: "Income from equity",
  date: "2021-04-17",
  openDate: "2021-04-16",
  value: 8786 - 2786 - 1786 - 453 + 1465,
  open: 8786 - 2786 - 1786 - 453,
  stepValue: 8786 - 2786 - 1786 - 453 + 1465,
  color: chart.colors.getIndex( 16 ),
  displayValue: 1465
}, {
  category: "Operating income",
  date: "2021-04-18",
  openDate: "2021-04-17",
  value: 8786 - 2786 - 1786 - 453 + 1465,
  open: 0,
  color: chart.colors.getIndex( 17 ),
  displayValue: 8786 - 2786 - 1786 - 453 + 1465
} ];

var categoryAxis = chart.xAxes.push(new am4charts.DateAxis());
categoryAxis.dataFields.category = "Date";
categoryAxis.renderer.minGridDistance = 40;
categoryAxis.dateFormatter.inputDateFormat = "yyyy-MM-dd";

var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

var columnSeries = chart.series.push(new am4charts.ColumnSeries());
columnSeries.dataFields.dateX = "date";
columnSeries.dataFields.openDateX = "openDate";
columnSeries.dataFields.valueY = "value";
columnSeries.dataFields.openValueY = "open";
columnSeries.fillOpacity = 0.8;
columnSeries.sequencedInterpolation = true;
columnSeries.interpolationDuration = 1500;

var columnTemplate = columnSeries.columns.template;
columnTemplate.strokeOpacity = 0;
columnTemplate.propertyFields.fill = "color";

var label = columnTemplate.createChild(am4core.Label);
label.text = "{displayValue.formatNumber('$#,## a')}";
label.align = "center";
label.valign = "middle";

chart.cursor = new am4charts.XYCursor();
chart.cursor.behavior = "none";

**Comment by future11** [comment]
![image](https://user-images.githubusercontent.com/18210564/117306169-10a29900-ae45-11eb-9c87-5c391cf47cf7.png)

**Comment by martynasma** [comment]
This should fix it:

```JavaScript
columnSeries.baseAxis = valueAxis;
```

**Comment by future11** [comment]
Awesome! Thanks for your help. And one more question.
Can I adjust the position of openDateX and dateX?
I tried the following code but no changes.
columnSeries.dataItems.template.locations.dateX = 0.5;
columnSeries.dataItems.template.locations.openDateX = 0.5;

**Comment by martynasma** [comment]
No, since we switched base axis to Y axis, horizontal DateAxis acts as a regular value axis. Open and Close values are exact dates you set in data. So if you need to end it at midnight next day, you may need to set 12 hours to your timestamps.

Another option is to just move grid to the place you need.

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Positioning

**Comment by future11** [comment]
I see. Thanks
