### ISSUE TITLE
How to create guide range without a full range axis

### ISSUE THREAD

**Issue by Cheng007** [amcharts/amcharts4#3509]
Hi guys.
I created a Axis Range as below, the code is [here](https://codepen.io/Cheng007/pen/abJzpwa)

![image](https://user-images.githubusercontent.com/13946264/117434699-94e93f00-af5f-11eb-83f0-704b4c7c9549.png)

Rather than the line full of all the axisY, I want the line just in series area as the example below.

![image](https://user-images.githubusercontent.com/13946264/117436373-800dab00-af61-11eb-9381-3611b9c7be9d.png)

 What should I do?

**Comment by martynasma** [comment]
That won't work with a range.

You can do it with custom bullet though:

https://www.amcharts.com/docs/v4/tutorials/custom-multiple-element-bullets/

**Comment by Cheng007** [comment]
I will try. Thank you for your suggestion.

**Comment by Cheng007** [comment]
I have drawn the Line by bullet, but how can I add the Line's label under xAxis as the first picture shown 'retire'?

**Comment by martynasma** [comment]
Via "range bullets":

https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_bullets

**Comment by Cheng007** [comment]
Perfect. Thank you guy.
