### ISSUE TITLE
Gauge chart labels don't display text within square brackets

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#3510]
This might exist for other chart types too (I've only tested gauge charts), but text within a square bracket doesn't get displayed in a `Label` object.

You can see from the data that additional information has been provided but is omitted from the final chart.
![image](https://user-images.githubusercontent.com/2857604/117468263-6c0b7e80-af4c-11eb-94a7-b436b489a85a.png)
![image](https://user-images.githubusercontent.com/2857604/117468378-86455c80-af4c-11eb-9729-0984c6056c56.png)

I have tested the string with other characters such as `'{(<` and the text still gets displayed.

Here is a reduced test case:
https://codepen.io/jbate/pen/gOmbXWb?editors=0010

**Comment by xorspark** [comment]
Square brackets and curly braces [need to be escaped](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Escaping) if you want to display them. This is done by doubling up the characters, e.g. `[[merit]]` and `{{text}}`.

**Comment by jbate** [comment]
Ah wonderful! Thanks for the tip 👍
