### ISSUE TITLE
Icon on child bubble of a Forced Directed Tree not center if the diagram start with MaxLevel = 1

### ISSUE THREAD

**Issue by ysi** [amcharts/amcharts4#3515]
I'm using the Force Directed Tree with svg icons in bubble at all levels. All works fine, but if I force starting my diagram with only the 1st level (with command series.maxLevels = 1), icons on bubble at the first level are correctly center, but when I deploy bubble, icons on children bubble are not center anymore.

Even if you specify 'middle' in horizontalCenter and verticalCenter properties of icons, the icons are not center.

You can reproduce the problem, by adding : series.maxLevels = 1 in the amChart example ( https://codepen.io/team/amcharts/embed/EJgNey?default-tab=result&editable=true&theme-id=dark )

Is there a way, a command to force icons to be center at child level ?

Here is my icon code

`//Configure icons
let icon = networkSeries.nodes.template.createChild(am4core.Sprite);
icon.propertyFields.path = "path";
icon.horizontalCenter = "middle";
icon.verticalCenter = "middle";
networkSeries.centerStrength = 0.4;`

I'm using the last version of amcharts (4.10.18) and Angular: 11.2.9

**Comment by martynasma** [comment]
I added `series.maxLevels = 1` (you have a typo btw) to the example you mentioned:

https://codepen.io/team/amcharts/pen/94d35cfb76191d7944644b2d443dae0d

Looks fine to me:

![image](https://user-images.githubusercontent.com/1458520/117770159-48db1a80-b23d-11eb-9806-24ade48b80b2.png)

**Comment by martynasma** [comment]
Indeed. We'll need to figure this out. Thanks.

**Comment by ysi** [comment]
Hi, have you some informations about a fix for this issue ?

**Comment by martynasma** [comment]
OK, so found a workaround for you - pre-hiding all top level nodes:

```JavaScript
//series.maxLevels = 1;

series.events.on("datavalidated", ()=>{
  series.dataItems.each(function(dataItem) {
    if (dataItem.level == 0) {
      dataItem.hide();
    }
  })
})
```

Please note, the `maxLevels` needs to be disabled for this to work.

**Comment by martynasma** [comment]
Example:
https://codepen.io/team/amcharts/pen/94d35cfb76191d7944644b2d443dae0d

**Comment by ysi** [comment]
Great. It's working for me. It does the job. Thanks a lot
