### ISSUE TITLE
Displaying Gantt Chart in table format

### ISSUE THREAD

**Issue by dhiren-eng** [amcharts/amcharts4#3516]
Hi,

I'm trying to display a Gantt chart in a table format as shown below : 
![image](https://user-images.githubusercontent.com/59474883/117774473-2bb34580-b257-11eb-8ba5-ab0f81b52fe5.png)

I've tried implementing the same by creating a table and plotting a separate chart for date axis and for each bar in every cell of the table as seen in the codepen below.
[Gantt in table format sample](https://codepen.io/dhiren530/pen/RwKeWyK)

The display of only bars in each cell was implemented by creating 2 unclustered column series, one having start and end date same as date axis and hiding that series, the other is the visible one with the actual dates plotted. The axes and grid lines have been disabled.

The date axis display was achieved by just reducing the height of the chart and adjusting paddingTop of the chart. 

I've noticed that the bars align perfectly with the date axis no matter how we resize the window.

Wanted to know if this approach is recommended and what could be the drawbacks if any ?

@martynasma @zeroin

**Comment by martynasma** [comment]
Well, it depends on how many actual charts there are.

Each additional chart introduces overhead, so if you have a lot of lines, you might experience performance issues.

That said, there are some things you can do to mitigate that.

https://www.amcharts.com/docs/v4/concepts/performance/#Daisy_chaining_multiple_charts
https://www.amcharts.com/docs/v4/concepts/performance/#Lazy_loading_charts
https://www.amcharts.com/docs/v4/tutorials/generating-static-charts/
