### ISSUE TITLE
When I try to export csv file texts of Chinese, Japanese, or Korean, characters are not displayed correctly. 

### ISSUE THREAD

**Issue by nhatnt** [amcharts/amcharts4#3518]
Dear Amcharts Team
When I try to export csv file texts of Chinese, Japanese, or Korean, characters are not displayed correctly. 
I tried to do following this solution but it's not working.
https://www.amcharts.com/docs/v4/tutorials/using-pdf-export-fonts/
Please help me!

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by nhatnt** [comment]
@martynasma  sorry for lately reply. You can set dataFields following the text bellow and then call to export.
chart.exporting.dataFields = {
  "value": "예산 2020",
  "category": "예산 2020"
}
chart.exporting.export("csv").
This issue is very affect for my korean customer. pls help me

**Comment by martynasma** [comment]
Just tried it. Looks fine:

![image](https://user-images.githubusercontent.com/1458520/119640705-8c2eaf00-be21-11eb-8365-e2d88cfed4c4.png)

**Comment by nhatnt** [comment]
but it's not working in my side. Can i setting some thing in my vue project?

**Comment by nhatnt** [comment]
thank you for supporting but it's still fine korean in file name, but data fields in csv are not correctly display.
What's version amchart you are using?

**Comment by martynasma** [comment]
The latest: 4.10.18.

Would you be able to prep a demo for us to check?

**Comment by nhatnt** [comment]
but my project is secure so i cannot. I try create new amchart vue project and export some thing by korean but not success

**Comment by martynasma** [comment]
I'm sorry but I'm not sure what to suggest. If you manage to put it up online somewhere, let me know.
