### ISSUE TITLE
Change out edge direction in Sankey diagram

### ISSUE THREAD

**Issue by aktx** [amcharts/amcharts4#3519]
Hello!
Can you help me change edge direction in sankey diagram?

Now it seem like source node is "Тестирование", but in fact source node is "Аналитика".  

![sankey-prblm](https://user-images.githubusercontent.com/21019996/117951753-23254280-b31d-11eb-8af0-49e7a155d9ea.png)

**Comment by martynasma** [comment]
Unfortunately, that's not supported. Sorry.
