### ISSUE TITLE
How can I improve treemap highlighting speed?

### ISSUE THREAD

**Issue by PangNem** [amcharts/amcharts4#3521]
**Question**
*How can I improve treemap highlighting speed?*

HI, I'm using amcharts4's treemap, and I applied hoverState fill like this:

```
// darken
hoverState.adapter.add('fill', function (fill, target) {
  if (fill instanceof am4core.Color) {
    var BRIGHTENESS_SIZE = -0.4; // 1 to -1
    return am4core.color(am4core.colors.brighten(fill.rgb, BRIGHTENESS_SIZE));
  }
  return fill;
});
```

But when I deployed treemap at my company's website, It highlights very slowly. (It works fast in a local development environment only use treemap.)

Is related to website speed? or have a displaying speed option?

**Environment (if applicable)**

**Additional context**
treemap gif:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/26791234/118213789-8b089400-b4a9-11eb-9d99-026b84d9c73a.gif)

website page speed:

![image](https://user-images.githubusercontent.com/26791234/118213866-b7bcab80-b4a9-11eb-8749-311a133d49de.png)

**Comment by martynasma** [comment]
Um, hard to say. Would you be able to experiment with your website by removing CSS and other components used, gradually. Maybe pinpoint which one is causing this?
