### ISSUE TITLE
Add value display on bubbles in Bubble Chart

### ISSUE THREAD

**Issue by LouieTian0209** [amcharts/amcharts4#3522]
**Question**
Here's a demo to the Bubble Chart: [https://www.amcharts.com/demos/bubble-chart/](https://www.amcharts.com/demos/bubble-chart/)
In this demo those bubbles have tooltips enabled already but there's no value display on each bubble. What I want to achieve is something like [this map demo](https://www.amcharts.com/demos/map-image-drill-down/). In this map example those values are added by adding child onto the template when creating series, I was attempting to do the same with Bubble Chart as well but was unsuccessful with `series.bullets.template`. Is there a way to display value of each bubble onto the bubble itself at the center?

**Environment (if applicable)**
amCharts 4 with Angular

**Comment by martynasma** [comment]
Yes:

```JavaScript
var bulletLabel = bullet.createChild(am4core.Label);
bulletLabel.horizontalCenter = "middle";
bulletLabel.verticalCenter = "middle";
bulletLabel.text = "{value}";
bulletLabel.fill = am4core.color("#fff");
```

https://codepen.io/team/amcharts/pen/5c52e6356d9490ca6f8cbada431612a9?editors=0010

**Comment by emilyshasha** [comment]
Hi, with regard to this question, I am able to display value on the bubble chart. But since the value that I got from the API contains 0, I’ve tried to hide 0 using the adapter. However, this function only works when the webpage is initialized, if I reinitialize the chart in the same page, the value will disappear, I’d like to ask if there’s something wrong with this function?
```
let bullet = series.bullets.push(new am4charts.CircleBullet());
let bulletLabel = bullet.createChild(am4core.Label);
bulletLabel.adapter.add('text', function(text, target) {
    if (target.dataItem) {
      const count = target.dataItem.dataContext['value'];
      if (count > 0) {
        return '{value}';
      } else {
        bulletLabel.hide();
      }
    }
 });
```

**Comment by LouieTian0209** [comment]
@martynasma Would appreciate it if you could provide some insights. Thanks a lot!
