### ISSUE TITLE
Updating projection on zoom

### ISSUE THREAD

**Issue by adibbz** [amcharts/amcharts4#3524]
I have a drill down world map with an initial chart projection set to `am4maps.projections.Miller();`

However, when a user clicks on the US polygon and  we zoom in, I want to update to use the Albers projection `new am4maps.projections.AlbersUsa()`;

The transition from projections isn't smooth and I also receive this console error when following this workflow:
1. Zoom into another country
2. Zoom back out to world map view
3. Zoom to US
4. Receive console error and broken map
5. `TypeError: Cannot read property '0' of null at e.validatePosition`

Here's my hit event handler:
```
worldPolygon.events.on('hit', ev => {
        const dataContext = ev.target.dataItem.dataContext as any;
        const hasData = !!this.worldSeries.data.find(x => x.id === dataContext.id).fanCount;
        if (hasData) {
          this.chart.projection =
            dataContext.id === 'US'
              ? new am4maps.projections.AlbersUsa()
              : new am4maps.projections.Miller();
          setTimeout(() => {
            this.chart.zoomToMapObject(ev.target, null, null, 1000);
          }, 500);
          this.selectedCountryMap = ev.target;

          // GB needs to grab ukCountriesHigh instead of ukLow
          if (dataContext.id === 'GB') {
            dataContext.map = 'ukCountriesHigh';
          }

          const map = dataContext.map;
          if (map) {
            ev.target.isHover = false;
            countrySeries.geodataSource.url = `https://www.amcharts.com/lib/4/geodata/json/${map}.json`;
            countrySeries.geodataSource.load();
          }
          this.handleCountryClick(dataContext.id);
        }
      });
```

**Comment by martynasma** [comment]
I think changing projection is OK, but not simultaneously while updating geodata.

I suggest changing projection only when geodata loads, e.g.:

```
countrySeries.events.on("datavalidated", ev => {
  // Change projection
  // ...
});
```

As for smoothness, well we can't map "morph" smoothly from one projection to the other.

I guess you can mitigate the effect by hiding the series until geodata is loaded.

Hope that makes sense.

**Comment by adibbz** [comment]
That all makes sense. I tried adding a listener there and then updating the projection but I still receive the same console error. I'm wondering if the chart is trying to zoom during the projection change. As far as I can tell there is no event when a projection change finishes...

```
countrySeries.events.on('datavalidated', ev => {
  if (this.selectedCountry === 'US' && this.selectedMap === 'country') {
    this.chart.projection = new am4maps.projections.AlbersUsa();
  }
});
```

**Comment by martynasma** [comment]
If you could whip up a simple working version of your setup on CodePen I could take a look. Normally, changing the projection does not occur.

**Comment by adibbz** [comment]
This is a very stripped down version and I can get it to work in this [codepen](https://codepen.io/adibbz/pen/ZEeBGJX)

I assuming it's some type of race condition where the chart is trying to zoom in before the projection has changed.

**Comment by adibbz** [comment]
Here's the stack trace. I've been trying to find an event that runs after the map is finished adding child elements because I _think_ that's when `validatePosition()` is called that breaks the map.

<img width="665" alt="Screen Shot 2021-05-19 at 11 30 19 AM" src="https://user-images.githubusercontent.com/6921939/118849701-9a1a8800-b895-11eb-93bd-8f892dd81e8e.png">

**Comment by adibbz** [comment]
After further investigating the issue, ultimately the fix came down to properly disposing of a `MapImageSeries`; 

Previously I was just doing `this.regionalSeries.hide()` but properly removing the `MapImageSeries` with:
```
this.chart.series.removeIndex(this.chart.series.indexOf(this.regionalSeries));
```
allowed me to update the projection without the console error.
