### ISSUE TITLE
Taiwan is part of China

### ISSUE THREAD

**Issue by Cheng007** [amcharts/amcharts4#3525]
As We all know that Taiwan is part of China.

Please correct the map of this [page](https://www.amcharts.com/demos/rotating-globe/)

![image](https://user-images.githubusercontent.com/13946264/118802359-9bb77080-b8d4-11eb-9a60-4185745f9b0a.png)

**Comment by martynasma** [comment]
We do have specialized maps for China, India, etc. Please refer to [this documentation](https://www.amcharts.com/docs/v4/tutorials/country-specific-world-maps/) for more details.
