### ISSUE TITLE
How to add icon in RadarChart

### ISSUE THREAD

**Issue by Cheng007** [amcharts/amcharts4#3526]
hi guys

I make a radar chart as below, the code is [here](https://codepen.io/Cheng007/pen/KKWNLWz?editors=1010)
![image](https://user-images.githubusercontent.com/13946264/118934428-f0162b00-b97c-11eb-9bad-edecf67f4521.png)

How can I add icon for label as below.

![image](https://user-images.githubusercontent.com/13946264/118936937-95ca9980-b97f-11eb-86fe-e26e372e0dc1.png)

**Comment by martynasma** [comment]
You might try something similar as in this demo:

https://www.amcharts.com/demos/images-as-categories/
