### ISSUE TITLE
Range Grid not appearing to toggle visibility on range change

### ISSUE THREAD

**Issue by mbs-Michael** [amcharts/amcharts4#3528]
**Question**
Tried following [this tutorial](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Single_lines) to add a vertical dotted line to a chart via axisRanges. However, for the chart in question, the category data is very dynamic and the value I'm trying to put the line on is not always on the chart. When that happens, the line stays wherever is whenever the chart data changes. I've tried setting an event handler to toggle visibility, and that works from going from visible to invisible, but not the other way around.

[CodePen sample](https://codepen.io/ninjuh1124/pen/poeegNx?editors=0010). As shown there should be two ranges, one at value 1, and one at 2 (invisible on load). Adding a datapoint at 2 doesn't toggle visibility, and removing the datapoint at 1 will make that line disappear, but it won't reappear.

**Comment by martynasma** [comment]
How about using `hide()`/`show()` methods instead of setting `visible` property? That property is kinda tricky, whereas methods are pretty straightforward:

```JavaScript
categoryAxis.events.on("dataitemsvalidated", () => {
  if (typeof categoryAxis.categoryToIndex(range1.category) === "number") {
    range1.show();
  }
  else {
    range1.hide();
  }
  if (typeof categoryAxis.categoryToIndex(range2.category) === "number") {
    range2.show();
  }
  else {
    range2.hide();
  }
});
```

The above seems to work on your CodePen.
