### ISSUE TITLE
Date axis: How to scale from year to seconds when zooming (with CSV file instead of JSON data)?

### ISSUE THREAD

**Issue by DWSuryo** [amcharts/amcharts4#3530]
**Question**

So I forked one of your graphs in codepen [here](https://codepen.io/dwsuryo/pen/poeeRqa). At that pen I provided external CSV data at the comments. I compare the function using JSON data and using CSV from external source. Looks like when I use JSON data. It looks fine with the date being ISO format. It can automatically shows time and date. When i use CSV with the same format as JSON, somehow it only shows date, not even time, Which means the whole time data is overlapped in their respective dates. Am I doing it wrong or Is there a difference of between them especially at the output?

This is the [codepen](https://codepen.io/dwsuryo/pen/XWMMWxy) i am working for

here's my data to test
[date only](https://raw.githubusercontent.com/DWSuryo/flask-with-graphs-training/main/sensor_date.csv)
[iso date (timespec=seconds)](https://raw.githubusercontent.com/DWSuryo/flask-with-graphs-training/main/sensor4.csv)

**Comment by martynasma** [comment]
Try specifying input date format:

```
chart.dateFormatter.inputDateFormat = "i";
```

https://www.amcharts.com/docs/v4/concepts/data/#Parsing_dates_in_data

**Comment by DWSuryo** [comment]
Alright, that solves the issue. I've updated the pen above.  Will ask if I have more problems encountered. Thanks for the solution.
