### ISSUE TITLE
Drop events on map

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#3533]
Hello there,

Is there a way to capture "drop" event with extarnal html item (or file) ?

By example I want to drop a picture into the map and capture "longitude" and "latitude". I don't see any "drop" event in the documentations. 

hit event working well:

```
chart.seriesContainer.events.on("hit", function(ev) {
	 console.log(chart.svgPointToGeo(ev.svgPoint))
});
```
Is there a way to get lat/long by document pointer position ?

Thanks for your help !

**Comment by martynasma** [comment]
I'm afraid we do not have such event built-in.

You will need to utilize `pointerup` event to catch drop event, then use MapChart's built in functions to determine lat/long of the "drop point" (pointer's position on scree when `pointerup` kicked in).

https://www.amcharts.com/docs/v4/reference/mapchart/#svgPointToGeo_method

Please note that "SVG point" is relative to the corner of the `<div>` that map is placed in, whereas mouse event will report screen coordinates, so you will need to adjust for that.

Hope that makes sense.

**Comment by ptorrent** [comment]
Thanks for your answer,

When you say "relative to the corder of the <div>", you mean this corner ?

![image](https://user-images.githubusercontent.com/6083644/119774683-d320b100-bec2-11eb-9253-0641fac013d6.png)

**Comment by martynasma** [comment]
Yup. That's the one.

**Comment by ptorrent** [comment]
thanks at @martynasma , it works perfect. Best support ever :)
