### ISSUE TITLE
How can we set maxHeight on chart container

### ISSUE THREAD

**Issue by vidyashreen1991** [amcharts/amcharts4#3534]
If we have a large number of legends, it is covering the entire chart. The chart is not visible, it is covered with legends.
One way to solve this is to set maxHeight on legends. But is there any way to set maxHeight on a rendered portion of the chart?
<img width="335" alt="Screenshot 2021-05-25 at 4 13 12 PM" src="https://user-images.githubusercontent.com/25095893/119485017-3a7c1b00-bd74-11eb-90d3-60656a8b942b.png">

**Comment by sassomedia** [comment]
The chart should adjust its width and height based on the size of the container div you place it in. If you have a large amount of vertical legend items, are you not able to set the legend to the right of the chart so that two don't interfere with each other?

**Comment by martynasma** [comment]
> But is there any way to set maxHeight on a rendered portion of the chart?

Nope. The chart will always take up the space left to it by the legend.

There are a couple of options:

1) Use fixed-height [scrollable legend](https://www.amcharts.com/docs/v4/concepts/legend/#Scrollable_legend).
2) Put legend into [separate container](https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/).
