### ISSUE TITLE
Amchart4 Legend Column Issue

### ISSUE THREAD

**Issue by sydney-nkosi** [amcharts/amcharts4#3535]
If you have 2 legend columns, how do you reduce the space in between the columns?

**Comment by martynasma** [comment]
It depends on the actual situation.

When you have legend placed on chart top or bottom, it will use "grid" layout, which means that columns will be arranged in actual widths based on the legend labels.

If you have a chart demo you could place on CodePen/jsFiddle I could provide further insight.
