### ISSUE TITLE
How to control the drag of a node in force-directed-tree

### ISSUE THREAD

**Issue by Chinmay-k96** [amcharts/amcharts4#3537]
In a Force-directed-network graph, When I drag a node, it is very unstable and moves around in a haphazard way. How to control its movement to get positioned wherever I release cursor after dragging. Like if I drag from point A to point B, it should stop and be fixed at point B

**Comment by martynasma** [comment]
You might find this demo useful:

https://www.amcharts.com/docs/v4/tutorials/enable-dragging-of-forcedirectednode-to-fixed-location/

**Comment by Chinmay-k96** [comment]
Great....Thank you so much
