### ISSUE TITLE
How to give specific stroke width for every node link in a force-directed-tree

### ISSUE THREAD

**Issue by Chinmay-k96** [amcharts/amcharts4#3538]
In a force-directed-tree graph we have strokeWidth as a configuration --> networkSeries.links.template.strokeWidth = {value}
but I want it to be a key in the data object. I tried doing the below

 networkSeries.links.template.strokeWidth = "linkWidth"

then using this as key name like 
networkSeries.data = [{
     name : "India",
     color : "red",
     linkWidth : value,
     link : ["Sri Lanka", "Pakistan", "China"],
     children : childArray
}]

Here value for link width is different for every object 

But this did not work. How can I achive this

**Comment by martynasma** [comment]
Check this tutorial:
https://www.amcharts.com/docs/v4/tutorials/variable-link-widths-in-forcedirectedtree/

**Comment by Chinmay-k96** [comment]
Thank you so much....u are just amazing
