### ISSUE TITLE
Several points by milliseconds

### ISSUE THREAD

**Issue by DavidAuger** [amcharts/amcharts4#3540]
Hi all, Hi @martynasma ,

We are trying to display a line chart with several points by milliseconds (due to customers' needs - they recorded 20 000 or 10 000 pts / second during 1 second).

We tried to add it into our XYChart with a DateAxis as xAxis, but it appears we have 10 points on the same millisecond.
For now, we get that with a naugthy workaround by putting a point on each millisecond but results in a false xAxis duration (as show in the 1st snapshot down there)

Is there any parameters we misted ? Or is there any way for us to display our chart whitout any data loss, showing each points and a duration of 1 second displayed on xAxis  ?

How we want it to appear:
![image](https://user-images.githubusercontent.com/48203813/119640356-d2334500-be18-11eb-98da-d92773a2489d.png)
Here is, how it actually appearing:
![image](https://user-images.githubusercontent.com/48203813/119640463-ed9e5000-be18-11eb-867d-8011a1348d62.png)
and with a better close up:
![image](https://user-images.githubusercontent.com/48203813/119640536-0444a700-be19-11eb-8694-b47ef5a35771.png)

Best regards,
David

**Comment by martynasma** [comment]
I'm afraid our DateAxis does not go deeper than millisecond, so there's no realizable way to do so.

What I would do in your case, instead of DateAxis, I'd use ValueAxis, then you can use fractional numbers for timestamps, e.g.: `1622092983017.05` would mean halfway between two milliseconds.

This way you cram up a number of points within one millisecond, and it would still maintain the natural scale.

You would need to work on the grid/label positioning/formatting, though. Value axis places grid/labels on "pretty" base-10 numbers, which is not exactly suitable for showing time progression.

However, depending on your requirement, that might not be a problem.

How does that sound?

**Comment by DavidAuger** [comment]
Thank you @martynasma for your quick response !

We did though about changing DateAxis to ValueAxis too, and it sounds logical to me.

One think could not match our requirements however: we need to display dates in labels instead of timestamps.
So we are still wondering how we can convert such timestamps into dates in format "HH:mm:ss n" to have something looking like labels on the 1st screen shot.

Is there any parameters allowing us to "pipe" labels to apply them a transformation like "new Date(<timestamp>)" (either a custom transformation, or specific format parameter) ?

**Comment by martynasma** [comment]
Sure, you can use adapters on those labels:

```JavaScript
valueAxis.renderer.labels.template.adapter.add("text", function(text, target) {
  return chart.dateFormatter.format(target.dataItem.value, "qqq")
})
```

More about date formatting:
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-date-time/

**Comment by DavidAuger** [comment]
Hello @martynasma,

We manage to create chart with ValueAxis to help us match our requirements.
The look is not perfect yet, but we are satisfied with the result regard to the time we had to resolve this issue.
(There is still a strange effect on scroll bar and we didn't manage to display axis labels only on milliseconds as we hoped when chart is zoomed, but it's not a big deal)

Once again, many thanks for your help.
Do you need a small REX from us to guide someone else, or to help you produce a small documentation to help other developpers with same use case ?

Our context was to display some electrical measurements with like 10 000 or 20 000 pts / second (ie 10 to 20 / milliseconds).
The solution you gave us works perfectly well. So for anyone passing through with the same use case, going with ValueAxis and working on adapters seems to be the perfect solution so far.

**Comment by martynasma** [comment]
If you could post your solution in a form o simple CodePen or jsFiddle, that would be great.

I'm sure someone who stumbles upon this thread would appreciate it. Thanks!

**Comment by matinfo** [comment]
@DavidAuger I facing same issue/need to display electrical value provided in nano second for a complete duration of 2 sec. Could you please share your solution? Will be very appreciated.

**Comment by DavidAuger** [comment]
Hello @matinfo,

Indeed, we have the exact same need. That was also to display electrical values with high frequency data samples.

I cannot share our development, but i can discuss with you about the concept.
As explained by @martynasma , DateAxis reachs its limits in this case. That is the reason why you have to use ValueAxis instead.

So:
1. Change / Use valueAxis chart specifically for this case (we kept using dateAxis otherwise in our app)
2. Change adapters to keep a "date like" axis:

> example:
> const xAxis = chart.xAxes.push(new am4charts.ValueAxis());
> 
> // Adapter to convert timestamp (ms) to date format for the xAxis labels
> xAxis.renderer.labels.template.adapter.add("text", function (text, target) {
>   return chart.dateFormatter.format(target.dataItem['value'], "HH:mm:ss n")
> });

3. Change adapters to keep tooltip in "date like" format:

> // Adapter to convert timestamp (ms) to date format for the xAxis tooltip : add nanoseconds in tooltip if needed
> xAxis.adapter.add("getTooltipText", (tsString) => {
>   // Some code to get ts timestamp with our specified precision
> 
>   // no nanosecond = convert the timestamp directly into date format
>   if (Number.isInteger(ts)) {
>     tooltipText = chart.dateFormatter.format(dateFromTsIntegerPart, "HH:mm:ss n") + "ms";
> 
>     // Nanosecond precision needed : calculate the nanoseconds and create the string date
>   } else {
>     // Some code to great entry automatically with expected format: HH + ":" + mm + ":" + "ss" + " " + n + "ms"
>    // Main calculations are here, according to you data
>   }
> 
>   return tooltipText;
> });

4. If you have a scrollbar, you also need to change adapters in consequences:
- ```chart.scrollbarX.startGrip.adapter.add("readerTitle", (stringReader) => {}));```
- ```chart.scrollbarX.endGrip.adapter.add("readerTitle", (stringReader) => {}));```
- ```chart.scrollbarX.thumb.adapter.add("readerTitle", (stringReader) => {}));```

(considering that ```chart.scrollbarX = new am4core.Scrollbar();``` )
