### ISSUE TITLE
Bug with chartXY zooming

### ISSUE THREAD

**Issue by morganevg** [amcharts/amcharts4#3541]
I am currently working with amchart4 in reactjs. I think i have a bug when i arrive on a page with a chartYX : sometimes the chart goes into zoom mode without having touched anything, has anyone ever had the same problem ?

**Comment by martynasma** [comment]
That sounds very weird. Never heard of the chart suddenly deciding to zoom by itself.

Do you by any chance have `maxZoomCount` set on your axis?
