### ISSUE TITLE
Updating the Chart with React state Data.

### ISSUE THREAD

**Issue by Madeindreams** [amcharts/amcharts4#3542]
**What is wrong with my data ?**

https://codepen.io/Idecentralize/pen/PopKGJZ

How do I have to format the data?

**React**

Im working with React and I get the data from the state.

If I don't JSON.stringify I see nothing at all

If i do it's the same error  and i can see the data just like the fiddle

In react i do see the same error, Unable to Load file but I can see the data as well.

**Comment by xorspark** [comment]
FYI, `dataSource` is used when you're loading data from an external URL through the `dataSource.url` property (analogous to fetch/XMLHttpRequest). The parser property is used to tell the chart how to parse the data fetched at the specified URL ([docs](https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/)). It has no impact on anything set directly on the `data` property, so you should probably remove those lines.

You do not need to call `jSON.stringify` when assigning values to the chart's `data` property, [as it expects an array of objects](https://www.amcharts.com/docs/v4/reference/chart/#data_property). Perhaps you need to call `JSON.parse` instead.

**Comment by Madeindreams** [comment]
Thank You! I have manage to make it work!
 I am now looking at updating the data over time. If the grap if getting the data from the state. Is there a reload option or a smooth way to add data?

**Comment by Madeindreams** [comment]
Well I must do something wrong. I load the data history from the state. After that add data to my array every second.
So the state array is growing over time but it's not updating the chart that is connected to that state.

**Comment by xorspark** [comment]
Are you updating the chart.data array directly when your state receives new data (`chart.data = your_updated_state_array`)? If you're not already doing that, try seeing if that helps. I'm not a react expert, so take that suggestion with a grain of salt.

A *minimal* stackblitz/codesandbox that reproduces your issue would help if possible.

**Comment by Madeindreams** [comment]
I pass the data as a selector.  But it runs only once. Im trying to figure out how i can update it or trigger the update.

**Comment by Madeindreams** [comment]
So When i dispatch the ticker i would like the to call some function within the chart.

**Comment by Madeindreams** [comment]
Ok i have tried another technic.

The Chart now update when i push new data. However it's only the last candle that get update. The candle don't move to the left as it updates.

Also every time it updates, the chart reload. This is now my code.

export class Chart extends Component {


      componentDidMount() {
        
        
       
        this.initChart();
      }

      componentDidUpdate(prevProps) {
        //Handle refreshing the chart when the dataset changes
        if(!_.isEqual(prevProps.data, this.props.data)) {
          if(this.chart._super) {
            this.chart.dispose();
          }
          this.initChart();
        }
      }

      componentWillUnmount() {
        if(this.chart._super) {
            this.chart.dispose();
        }
      }

      initChart() {


        //All of our work goes here now
        const { chartId , data} = this.props;
        am4core.useTheme(am4themes_animated);
        

     
       
            this.chart = am4core.create(chartId, am4charts.XYChart);
            this.chart.padding(0, 15, 0, 15);
            this.chart.data =  data;
            this.chart.dataSource.parser = new am4core.JSONParser();
            this.chart.dataSource.parser.options.useColumnNames = false;
            this.chart.dataSource.parser.options.reverse = false;
           // this.chart.dataSource.load();
            this.chart.leftAxesContainer.layout = "vertical";
            this.chart.dateFormatter.dateFormat = "dd/mm/yyyy hh:mm:ss"; 

            let dateAxis = this.chart.xAxes.push(new am4charts.DateAxis());
            dateAxis.renderer.grid.template.location = 0;
            dateAxis.renderer.ticks.template.length = 1;
            dateAxis.renderer.ticks.template.strokeOpacity = 0.1;
            dateAxis.renderer.grid.template.disabled = true;
            dateAxis.renderer.ticks.template.disabled = false;
            dateAxis.renderer.ticks.template.strokeOpacity = 0.2;
            dateAxis.renderer.minLabelPosition = 0.01;
            dateAxis.renderer.maxLabelPosition = 0.99;
            dateAxis.keepSelection = true;
            dateAxis.minHeight = 30;
            dateAxis.groupData = true;
            dateAxis.minZoomCount = 5;
            dateAxis.parseDates= true;
            dateAxis.baseInterval = {
                "timeUnit": "minute",
                "count": 1
              }
            dateAxis.dateFormats.setKey("minute", "HH:mm");
            let valueAxis = this.chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis.tooltip.disabled = true;
            valueAxis.zIndex = 1;
            valueAxis.renderer.baseGrid.disabled = true;
            // height of axis
            valueAxis.height = am4core.percent(65);
            
            valueAxis.renderer.gridContainer.background.fill = am4core.color("#000000");
            valueAxis.renderer.gridContainer.background.fillOpacity = 0.05;
            valueAxis.renderer.inside = true;
            valueAxis.renderer.labels.template.verticalCenter = "bottom";
            valueAxis.renderer.labels.template.padding(2, 2, 2, 2);
            
            //valueAxis.renderer.maxLabelPosition = 0.95;
            valueAxis.renderer.fontSize = "0.8em"
            
            let series = this.chart.series.push(new am4charts.CandlestickSeries());
            series.dataFields.dateX = "time";
            series.dataFields.openValueY = "open";
            series.dataFields.valueY = "close";
            series.dataFields.lowValueY = "low";
            series.dataFields.highValueY = "high";
            series.clustered = false;
            series.tooltipText = "open: {openValueY.value}\nlow: {lowValueY.value}\nhigh: {highValueY.value}\nclose: {valueY.value}";
            series.name = "MSFT";
            series.defaultState.transitionDuration = 0;
            
            let valueAxis2 = this.chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis2.tooltip.disabled = true;
            // height of axis
            valueAxis2.height = am4core.percent(35);
            valueAxis2.zIndex = 3
            // this makes gap between panels
            valueAxis2.marginTop = 30;
            valueAxis2.renderer.baseGrid.disabled = true;
            valueAxis2.renderer.inside = true;
            valueAxis2.renderer.labels.template.verticalCenter = "bottom";
            valueAxis2.renderer.labels.template.padding(2, 2, 2, 2);
            //valueAxis.renderer.maxLabelPosition = 0.95;
            valueAxis2.renderer.fontSize = "0.8em"
            
            valueAxis2.renderer.gridContainer.background.fill = am4core.color("#000000");
            valueAxis2.renderer.gridContainer.background.fillOpacity = 0.05;
            
            let series2 = this.chart.series.push(new am4charts.ColumnSeries());
            series2.dataFields.dateX = "time";
            series2.clustered = false;
            series2.dataFields.valueY = "volume";
            series2.yAxis = valueAxis2;
            series2.tooltipText = "{valueY.value}";
            series2.name = "Series 2";
            // volume should be summed
            series2.groupFields.valueY = "sum";
            series2.defaultState.transitionDuration = 0;
       
            this.chart.cursor = new am4charts.XYCursor();
            
            let scrollbarX = new am4charts.XYChartScrollbar();
            
            let sbSeries = this.chart.series.push(new am4charts.LineSeries());
            sbSeries.dataFields.valueY = "close";
            sbSeries.dataFields.dateX = "time";
            scrollbarX.series.push(sbSeries);
            sbSeries.disabled = true;
            scrollbarX.marginBottom = 20;
            this.chart.scrollbarX = scrollbarX;
            scrollbarX.scrollbarChart.xAxes.getIndex(0).minHeight = undefined;
    
       
            
            /**
             * Set up external controls
             */
            
            // Date format to be used in input fields
            let inputFieldFormat = "hh:mm:ss";
         

            let zoomTimeout;
            function updateZoom() {
              if (zoomTimeout) {
                clearTimeout(zoomTimeout);
              }
              zoomTimeout = setTimeout(function() {
                let start = document.getElementById("fromfield").value;
                let end = document.getElementById("tofield").value;
                if ((start.length < inputFieldFormat.length) || (end.length < inputFieldFormat.length)) {
                  return;
                }
                let startDate = this.chart.dateFormatter.parse(start, inputFieldFormat);
                let endDate = this.chart.dateFormatter.parse(end, inputFieldFormat);
            
                if (startDate && endDate) {
                  dateAxis.zoomToDates(startDate, endDate);
                }
              }, 500);
            }
         
      
        }
    
    render() {
        return <div id={this.props.chartId} style={{ width: "100%", height: "600px" }} />
      }
}
export default Chart

**Comment by xorspark** [comment]
You shouldn't need to dispose of the entire chart for this. If your `props.data` only contains new data points to add to the chart, you should be able to just call `this.chart.addData(this.props.data)`. 

I'm not a react person, but I'm not sure why you're checking against `this.chart._super` when `this.chart` is the actual object, going by your initChart call. This likely explains the not disposed warning you're seeing since ou're checking a property that is seemingly always undefined.
