### ISSUE TITLE
Force-directed-tree : How to remove the circle which amcharts gives by default

### ISSUE THREAD

**Issue by Chinmay-k96** [amcharts/amcharts4#3544]
Amcharts gives a default circle structure for force-directed-tree, but I dont want it as I am using my own svg. I cannot hide it by scaling the svg because svg has some transparency so it will appear even if i scale it. for example in the below screenshot i want only the laptop icon to be visible and not the outer circle

![image](https://user-images.githubusercontent.com/62800512/119844478-152f0e80-bf26-11eb-841a-facb120bf7b0.png)

**Comment by xorspark** [comment]
You can disable the inner and outer circles on the series node template as documented [here](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Disabling_circles):

```
series.nodes.template.circle.disabled = true;
series.nodes.template.outerCircle.disabled = true;
```

**Comment by Chinmay-k96** [comment]
Thank you so much
