### ISSUE TITLE
Force-directed-tree : How to style the label text of a node

### ISSUE THREAD

**Issue by Chinmay-k96** [amcharts/amcharts4#3545]
I want to style the label text for a node. For example in the below screenshot, i want to style the "workstation#2" label

![image](https://user-images.githubusercontent.com/62800512/119844809-60492180-bf26-11eb-8917-7ba985b04f50.png)

**Comment by xorspark** [comment]
The node [label objects](https://www.amcharts.com/docs/v4/reference/label/) are accessible through the the node template, e.g. `series.nodes.template.label`. From there you can use properties such as fill, fontSize, fontWeight, and others listed in the reference doc to tweak as needed. You can also specify inline formatting on the label's `text` property as documented [here](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Visual_formatting)
