### ISSUE TITLE
Container with custom HTML

### ISSUE THREAD

**Issue by aniznik1** [amcharts/amcharts4#3546]
Is it possible to create a container with custom HTML that would be displayed between the grid lines and columns?

Something like:
Grid zIndex = 0
Container zIndex = 1
Series zIndex = 2

The red box you see now is a div with position absolute, but I'm guessing it would be possible to get the same result using an amcharts container?
![image](https://user-images.githubusercontent.com/73177825/119992726-1fefaf00-bfcb-11eb-8644-37d5eceec5e0.png)

**Comment by martynasma** [comment]
No, I'm afraid it's impossible put HTML into amCharts container.
