### ISSUE TITLE
series.dataItems.last.point undefined

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#355]
Hello,

Sometines "series.dataItems.last.point" seems to be undefined:

![image](https://user-images.githubusercontent.com/6083644/45553847-3c585700-b835-11e8-9d18-4a12cd0326f3.png)

Because of this, I'm not able to place bullet properly. As we can see here : 
https://codepen.io/ptorrent/pen/PdBWpP

![image](https://user-images.githubusercontent.com/6083644/45553929-77f32100-b835-11e8-8478-364039977496.png)

**Comment by Gruffers** [comment]
I am experiencing this same problem. The second bullet sticks

**Comment by famithanelofer06** [comment]
facing this same problem. what could be the solution for this?

**Comment by woodly0** [comment]
Hello,
why is this closed? I have the same Issue.
