### ISSUE TITLE
flag image is not exporting properly 

### ISSUE THREAD

**Issue by rmalearner** [amcharts/amcharts4#3550]
**Bug description**

The country-flag images are not visible in the exported image.

Please see and try to export/print chart as an image from following example 
https://codepen.io/rmalearner/pen/vYxWZPR?editors=1011

 - amCharts version : v4
 - Browser and its version : Crome

**Comment by martynasma** [comment]
Images loaded from another host than the page displaying the chart can't be exported because they make canvas "tainted". There is no way around it except putting them on the same domain as the chart page.
