### ISSUE TITLE
Hide overlapping label bullets

### ISSUE THREAD

**Issue by gbieging** [amcharts/amcharts4#3552]
**Question**

I have made a timeline chart from this tutorial: [https://www.amcharts.com/docs/v4/tutorials/creating-timeline-charts/](https://www.amcharts.com/docs/v4/tutorials/creating-timeline-charts/), but with a DateAxis instead of CategoryAxis.

From the data I have, sometimes the bullets become too close and start overlapping. I'm trying to detect when these overlaps occur and have such labels hidden, only appearing when hovering over the parent CircleBullet.

I tried creating an adapter on `"visible"` for the LabelBullet, using `Sprite.hitTest` from the adapter target against every bullet in the `Series.bulletsContainer`, but it doesn't work on first render, and only partially when hovering over the bullets, making them blink.
I tried using the `Sprite.hitTest` on both the `LabelBullet` object and `LabelBullet.label`.
Also tried setting `labelBullet.layout = "absolute"` and `labelBullet.isMeasured = true` as required for the [Overlap Buster Plugin](https://www.amcharts.com/docs/v4/tutorials/plugin-overlap-buster/).
I tried looking at the source code of the Overlap Buster Plugin, but its logic seems hard to adapt to what I need.

Bullets creation code:
```javascript
let bullet = series.bullets.push(new am4charts.CircleBullet());
bullet.circle.radius = 15;
bullet.setStateOnChildren = true;
bullet.states.create("hover");
bullet.circle.states.create("hover").properties.radius = 20;

let image = bullet.createChild(am4core.Image);
image.propertyFields.href = "icon";
image.width = 25;
image.height = 25;
image.horizontalCenter = "middle";
image.verticalCenter = "middle";
let hover = image.states.create('hover'); {
  hover.properties.width = 35;
  hover.properties.height = 35;
}

let labelBullet = series.bullets.push(new am4charts.LabelBullet());
labelBullet.layout = "absolute";
labelBullet.isMeasured = true;
labelBullet.label.maxWidth = 150;
labelBullet.label.wrap = true;
labelBullet.label.truncate = false;
labelBullet.label.textAlign = "middle";
labelBullet.label.padding(8, 4, 8, 4);
labelBullet.setStateOnChildren = true;
labelBullet.states.create("hover").properties.scale = 1.2;
labelBullet.label.paddingTop = 20;
labelBullet.label.paddingBottom = 20;
labelBullet.label.propertyFields.verticalCenter = "center";
labelBullet.label.propertyFields.dy = "offset";
labelBullet.adapter.add("visible", (visible, target) => {
  for (let child of series.bulletsContainer.children.values) {
    if (child instanceof am4charts.LabelBullet) {
      if (child !== target) {
        if (target.label.hitTest(child.label)) {
          return false;
        }
      }
    }
  }

  return true;
});
```

**Environment (if applicable)**

- amCharts 4

**Additional context**

**Comment by zeroin** [comment]
I could recommend to monitor change of start/end of Date axis and show/hide bullets based on that, like this:

```
  dateAxis.events.on("startendchanged", handleBullets);
  series.events.on("visibilitychanged", handleBullets);


 function handleBullets(){
    if (dateAxis.maxZoomed - dateAxis.minZoomed < 30000000) {
      series.dataItems.each(function(dataItem) {
        dataItem.bullets.each(function(key, bullet) {
          bullet.disabled = false;
          bullet.show();
        })
      })
    }
    else {
      series.dataItems.each(function(dataItem) {
        dataItem.bullets.each(function(key, bullet) {
          bullet.hide();
          bullet.disabled = true;
        })
      })
    }   
 }
```

https://codepen.io/team/amcharts/pen/yLbybpp
