### ISSUE TITLE
How to add customized colors for legend marker?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3553]
I am working on amcharts4, where i used legend marker as circle. By default the color inside marker is filling with colors, I need to set specific colors to fill inside the marker.
  I need to set fill the markers color as per series line color.
![Screenshot from 2021-05-31 16-28-21](https://user-images.githubusercontent.com/71019344/120183530-72c8a100-c22d-11eb-9137-4fb779e2addd.png)

`chart.legend = new am4charts.Legend();
      chart.legend.useDefaultMarker = true;
      const marker : any = chart.legend.markers.template.children.getIndex(0);
      marker.cornerRadius(12, 12, 12, 12);
    `
But i'm getting like this as below
![Screenshot from 2021-05-31 16-32-42](https://user-images.githubusercontent.com/71019344/120183899-f4b8ca00-c22d-11eb-84b6-6c340605ea2e.png)

Can you find a quick solution for this to fill customized colors inside marker. 

Thank you.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by meghanaNanuvala** [comment]
Here is the link [to fill the colors in marker as per series color](https://codepen.io/meghanananuvala/pen/zYZpdPZ)
For eg. 1st series line color is bit thick blue in the same way i need customized color to be filled in marker as thick blue instead light blue in pen.

**Comment by martynasma** [comment]
Thanks.

OK, so legend marker takes series' `fill`, whereas you only set `stroke`.

All you need to do is to set `fill` as well:

```JavaScript
series3.stroke = am4core.color(colors[index]);
series3.fill = series3.stroke;
```

**Comment by meghanaNanuvala** [comment]
Thanks, it's working

**Comment by meghanaNanuvala** [comment]
How to decrease the size of legend marker for circle?
