### ISSUE TITLE
How to get the start and end index of current displayed data?

### ISSUE THREAD

**Issue by future11** [amcharts/amcharts4#3554]
Hi,

Is there a way to get the start and end index of current displayed data from chart or data axis object?
For example, I can get minZoomed and maxZoomed for current zoom level in data axis. I need to convert these values to data indices.
The chart data is too big. So it's time consuming work to iterate whole data from start to end. If the library supports this functionality, please let me know how I can get them.

Thanks,
Ben

**Comment by martynasma** [comment]
`minZoomed` and `maxZoomed` are timestamps. You can easily convert them into Date objects by passing them into `Date` constructor:

```JavaScript
var startDate = new Date(dateAxis.minZoomed);
```
