### ISSUE TITLE
Color mismatch between heat legend and graph

### ISSUE THREAD

**Issue by Scylanth** [amcharts/amcharts4#3555]
Hello,

I have noticed an issue with the heat legend : when specifying a min and max value, the colors in the graph do not match the one of the legend.
The color of the highest column is the same than the max of the heat map, but the color shown by the tooltip clearly differs.

https://codepen.io/Scylanth/pen/zYZpxEw

Ii can also be reproduced by opening the last codepen on the heat legend tutorial (https://www.amcharts.com/docs/v4/concepts/legend/heat-legend/) and adding a min and max value in the legend (in that case, with a max value way higher that the actual maximum)

Thanks in advance.

**Comment by martynasma** [comment]
Well you do have HeatLegend's `maxValue` set at 20,000 whereas biggest value in the chart is 1,850 hence the mismatch.

Legend's max value should always use actual maximum value from the real data.

**Comment by Scylanth** [comment]
I set the maxValue to such a high value to show the issue. It is weird to be able to modify it if it should always be equal to the actual maximum value. In any case, the values themselves are good, both on the graph and the legend, but the color on the graph is not.

In my case, I need to display 2 heatmaps and I wanted to make them share a common legend, or at least that the legends have the same range.
I have two different sets of data from different flows but with comparable magnitudes (something like a order 2 between the max values of both graphs). My initial idea was to tweak the HeatLegend's maxValue and have them share the same one, but the visualization is wrong (color shown do not have the same scale).
Would you have any recommendation on how to achieve this if the maxValue can't be set ?

**Comment by martynasma** [comment]
There's no built-in relation between Series and HeatLegend. It's up to you to implement that relation.

So if you have are more complicated logic than 1:1 value scale between one series and one legend, then you will need to adjust your code accordingly.

E.g. modify the code that displays tooltip on legend adjusted for the global scale. Again, since you need custom logic for Heatlegend, you'll need to modify the code accordingly.

Hope that makes sense.

**Comment by Scylanth** [comment]
It does.
It is a bit weird because the value shown in the HeatLegend's tooltip are correct, and the color for the min and the max are taken from the Serie, so there is at least some relation, but not for all elements.

By changing the min and max color for both components and implement a relation between those, I should be able to make something.

Thanks for your help.

**Comment by martynasma** [comment]
> It is a bit weird because the value shown in the HeatLegend's tooltip are correct, and the color for the min and the max are taken from the Serie, so there is at least some relation, but not for all elements.

Well, it's not weird. The legend would take both min/max colors and min/max values from series. But in your example you had them explicitly overridden, hence me mentioning that it had no relation with series. I could've made it clearer. Sorry about that.
