### ISSUE TITLE
Title align right not work when minGridDistance setted

### ISSUE THREAD

**Issue by Cheng007** [amcharts/amcharts4#3558]
I have the [code](https://codepen.io/Cheng007/pen/GRWyQoV)

when I set `categoryAxis.title.align = 'right'`, the title align right correct as below
![image](https://user-images.githubusercontent.com/13946264/120303296-4bdb9f00-c301-11eb-8d2f-4f64310b4a3e.png)

but after set `categoryAxis.renderer.minGridDistance = 10`, the title align middle incorrect.
![image](https://user-images.githubusercontent.com/13946264/120303863-d3c1a900-c301-11eb-80a9-77a801551978.png) 

help

**Comment by martynasma** [comment]
Not sure why, but moving `minGridDistance` line above title align line solves the issue:

```JavaScript
categoryAxis.renderer.minGridDistance = 10
categoryAxis.title.text = 'hello'
categoryAxis.title.align = 'right'
```

**Comment by Cheng007** [comment]
Thank you so much
