### ISSUE TITLE
Force-directed-tree : How to give specific stroke color to a node 

### ISSUE THREAD

**Issue by Chinmay-k96** [amcharts/amcharts4#3559]
I am working on a graph which uses Force-directed-tree where a node is linked with 5 nodes. i:e link property has 5 node names in its array -> link : ["nodeA", "nodeB", "nodeC", "nodeD", "nodeF"]. Now the color of the link or stroke is same as the color given to the node using color field. How to give something like strokeColor : object.strokeColor dynamically.

Like below in amcharts example, the link or stroke takes the color of the node but I want to give my own color 
![image](https://user-images.githubusercontent.com/62800512/120323031-b04b2e00-c302-11eb-8322-24baefdb9d71.png)

**Comment by xorspark** [comment]
You can use an adapter on the link's stroke property and assign your colors that way. For example, using the node name as a driver:

```
series.links.template.adapter.add('stroke', function(stroke, target) {
  switch (target.dataItem.name) {  //name of node associated with link
    // set color here
  }
});
```

[Codepen](https://codepen.io/team/amcharts/pen/14b6f3407edff12f4507d542e2545e02?editors=0010)

**Comment by Chinmay-k96** [comment]
Thank you so much.....it works
