### ISSUE TITLE
Force-directed-tree : How to confine or enclose the graph to a particular layout size

### ISSUE THREAD

**Issue by Chinmay-k96** [amcharts/amcharts4#3560]
I am using Force-directed-tree to display a graph but I have only 800X500px of space to display it. Also I need the nodes to be draggable and positioned wherever required so I am using this --> 

// disable physics for dragged nodes
networkSeries.dragFixedNodes = true;
networkSeries.nodes.template.events.on("dragstop", function(event) {
  event.target.dataItem.fixed = true;  
})

Now the problem here is, if I drag the node to a point above my available space then the node gets stuck in the background and is not retrievable as it gets fixed there. How to make sure that the node never crosses a boundary.

In this link --> https://codepen.io/team/amcharts/pen/VwLYqPa
I you change the CSS of chartdiv to the below, and drag the node towards the right, then you can see that once you leave the cursor the node is lost. 

#chartdiv {
  width: 80%;
  height: 550px;
  max-width: 100%;
} 

Or In the image below that some nodes are hidden in the space above the yellow line
![image](https://user-images.githubusercontent.com/62800512/120325799-a5de6380-c305-11eb-8309-8d73d9c3946e.png)

**Comment by martynasma** [comment]
Well, we could use adapters to constrain x/y to actual chart area:

```JavaScript
networkSeries.nodes.template.adapter.add("y", function(y, target) {
  const radius = target.circle.pixelRadius;
  if (y <= radius) {
    return radius;
  }
  else if (y >= chart.pixelHeight - radius) {
    return chart.pixelHeight - radius;
  }
  return y;
});

networkSeries.nodes.template.adapter.add("x", function(x, target) {
  const radius = target.circle.pixelRadius;
  if (x <= radius) {
    return radius;
  }
  else if (x >= chart.pixelWidth - radius) {
    return chart.pixelWidth - radius;
  }
  return x;
});
```

https://codepen.io/team/amcharts/pen/RwpQdBo?editors=0010

**Comment by Chinmay-k96** [comment]
Thank you so much...... you are great
