### ISSUE TITLE
Bid-Ask Spread on Order Table

### ISSUE THREAD

**Issue by canerasa93** [amcharts/amcharts4#3561]
Hello, I have an bid-ask order chart. I want to show the difference between the buy and sell values with a space, but they always appear adjacent to each other. How can I do that?

![image](https://user-images.githubusercontent.com/55560011/120444335-3497c280-c390-11eb-9d7c-f1307e2bc627.png)

**Comment by martynasma** [comment]
How big of a space? If it's just a line, you can add an [axis range](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides) I suppose.

**Comment by martynasma** [comment]
You could technically assign bid and ask series to different ValueAxis, then [stack those axes](https://www.amcharts.com/docs/v4/tutorials/stacked-axes/) horizontally.

**Comment by canerasa93** [comment]
I have one CategoryAxis and one ValueAxis like this example: https://www.amcharts.com/demos/live-order-book-depth-chart/

how can i add 2 diffrent?

**Comment by martynasma** [comment]
Come to think of it, there's an easier way: just insert a couple of empty categories in data between asks and bids:

```JavaScript
var res = [];
processData(data.bids, "bids", true);
res.push({
  value: "0"
})
res.push({
  value: "1"
})
processData(data.asks, "asks", false);
```

https://codepen.io/team/amcharts/pen/fcee70ea3f636b6960cd497b5d712bfd?editors=0010

**Comment by canerasa93** [comment]
Thank you @martynasma
