### ISSUE TITLE
What is the minimal version of Typescript require currently(amcharts4 v4.10.18)?

### ISSUE THREAD

**Issue by NemoDima** [amcharts/amcharts4#3563]
**Question**
Could you tell me please, What is the minimal version of Typescript require currently(amcharts4 v4.10.18)?

Asked because on https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/
was wrote "IMPORTANT amCharts 4 requires TypeScript 2.9 or later. Using any older version will result in error."

But in the https://github.com/amcharts/amcharts4/blob/master/package.json mentioned:

         "devDependencies": {      
            ...
            "typescript": "3.6.5",
            ...
          }

I would be grateful for clarifications.

I have asked the [same question](https://github.com/amcharts/amcharts4/issues/2531#issuecomment-637481371) before, Hope it doesn't bother you too much.
Thank you.

**Comment by martynasma** [comment]
`devDependencies` are required only if you would like to compile your own version of amCharts 4 from the sources.

To simply use amCharts 4 in your apps you need at least TS 2.9 as per docs.

**Comment by NemoDima** [comment]
@martynasma thank you for clarification.
We have migrated to the last version without any problem.
