### ISSUE TITLE
How to display a series columns tooltip in axis break expanded area?

### ISSUE THREAD

**Issue by andry0092** [amcharts/amcharts4#3565]
Hi, the tooltips doesn't appear on series when the axis break is expanded. 
The same problem appears in the AmChart demo: https://www.amcharts.com/demos/column-chart-with-axis-break/
It's a bug or I'm missing something to do?

The same problem was reported in the issue https://github.com/amcharts/amcharts4/issues/3565

**Comment by martynasma** [comment]
Well, the break is actually an element that is placed above the column, so column does not get hovered because break obstructs it.

You can work around it by adding an `XYCursor` to the chart:

```JavaScript
chart.cursor = new am4charts.XYCursor();
```
