### ISSUE TITLE
How to add additional ticks in Gauge chart?

### ISSUE THREAD

**Issue by sumitkumar991** [amcharts/amcharts4#3566]
**Question**
Is there a way to add the additional ticks between two labels like in the image below? I am using amcharts4.

![ksnip_20210604-121211](https://user-images.githubusercontent.com/42379275/120757633-6d6d9e00-c52e-11eb-891f-77f15205f2cd.png)

**Comment by martynasma** [comment]
No, I'm afraid. amChars 4 does not support minor ticks.

You can probably work around it by adding a second axis without labels.

https://codepen.io/team/amcharts/pen/2a0ad896dcd435f98df0d55b0cd31c74?editors=0010

**Comment by sumitkumar991** [comment]
@martynasma thank you that works.
