### ISSUE TITLE
How to zoom to a particular date range after dynamically replacing the entire chart data

### ISSUE THREAD

**Issue by vidyashreen1991** [amcharts/amcharts4#3567]
It is not zooming correctly if we zoom in programmatically right after replacing the entire chart data. Do we have any event after data is updated in the chart?

**Comment by martynasma** [comment]
Yes, use `datavalidated` event:

```JavaScript
chart.events.on("datavalidated", function(ev) {
  // do your zooming here
  // ...
});
```
