### ISSUE TITLE
Angular Testing animation error

### ISSUE THREAD

**Issue by adibbz** [amcharts/amcharts4#3569]
I see the following error in the console when running `ng test` .  I've tried removing the animations (removed this line: `am4core.useTheme(am4themes_animated);`) in my charts but still see the error. 

<img width="989" alt="Screen Shot 2021-06-04 at 11 37 14 AM" src="https://user-images.githubusercontent.com/6921939/120835129-8aec3900-c529-11eb-9e7a-5547bd9211db.png">

Does anyone have any experience/tips with testing amcharts in angular?

```
amcharts: ^4.10.17
angular: ^11.0.9
karma: ~5.1.1
```

**Comment by Pauan** [comment]
Are you creating your charts outside of the Angular Zone, like this?

```ts
  browserOnly(f: () => void) {
      if (isPlatformBrowser(this.platformId)) {
          this.zone.runOutsideAngular(() => {
              f();
          });
      }
  }

  ngAfterViewInit() {
      this.browserOnly(() => {
          am4core.useTheme(am4themes_animated);

          let chart = am4core.create("chartdiv", am4charts.XYChart);

          // Chart code goes in here
      });
  }
```

**Comment by adibbz** [comment]
@Pauan yup, the only difference is I skipped the platform check

```
  browserOnly(f: () => void) {
    this.zone.runOutsideAngular(() => {
      f();
    });
  }
```
