### ISSUE TITLE
Gauge chart hand visually moves to the max position soon after creation

### ISSUE THREAD

**Issue by maticrozy** [amcharts/amcharts4#3573]
Hi,

I am making an app, where users can create and customize their charts however they wish. Recently I stumbled upon a bug, where the hand of a gauge chart snaps to the end of the axis right after creation.

The app is made in Vue 2.

**Creation of the chart**

When the chart is being created, it loops through an array of user-created axis data like so:

```javascript
let axes = [
  {
    min: 0,
    max: 100,
    parameter: "parameterId"
  },
  .
  .
  .
];

for (let i = 0; i < axes.length; i++) {
  let ax = axes[i];

  let axis = chart.xAxes.push(new am4charts.ValueAxis());
  
  axis.min = ax.min;
  axis.max = ax.max;
  
  axis.parameter = ax.parameter;
  .
  .
  .
}
```

In the loop it also creates a ClockHand and assigns it to the axis.

**The problem**

Every time a user adds a new axis or removes it, the createChart() method runs again, which includes the code snippet above. After this, a method that sets ClockHand values sets the right values, but somehow without the animation and ~1.6 seconds later the hand visually snaps to the end of the axis.

**Example**

[Here is an example of the bug, recreated on CodeSandbox](https://codesandbox.io/s/amcharts-gauge-chart-bug-0gddx?file=/src/App.vue)

Changing the value of the hand does what the chart is supposed to do but if you click on the [Recreate chart] button, the hand will snap to the end of the axis.

**Comment by martynasma** [comment]
Well, the issue is that you start animation (showValue) on a chart that has not initialized yet.

I'd do this:

```JavaScript
chart.events.on("ready", this.setValues);
```

**Comment by maticrozy** [comment]
Oh, I guess the lack of sleep is getting to me. Thank you so much.
