### ISSUE TITLE
I need render chart to getImage correctly?

### ISSUE THREAD

**Issue by ricardomaleixo** [amcharts/amcharts4#3576]
**scenario:**
I recive a data of type: SerieChart from our endPoint.
I'm using this data to create a Sprite result 

here, how i don't want render graph before generate image i set 'htmlElement' (second param) as empty string.
`const res: Sprite = am4core.createFromConfig(chart,'',am4charts[${chart.function}]);` '', 

then using this 'res' i converto to a PNG 
`chart.exporting.getImage('png').then((base64Img) => { this.currentResult = "<img src="${base64Img}" width="100%">"}`

and using this.currentResult to do a innerHTML. 
but, my image genereted from getImage is wrong. 

real graph;
![image](https://user-images.githubusercontent.com/1659954/121365757-4ee11b80-c90f-11eb-98f6-e3d0cc5321af.png)

image from getImage();
![image](https://user-images.githubusercontent.com/1659954/121365934-720bcb00-c90f-11eb-9cd0-06c3eed59172.png)

if need more info, please tell me, and tks!

**Comment by martynasma** [comment]
The issue is that when there is no container, the chart does not have dimensions. Try setting chart's `width` and `height` properties.

**Comment by ricardomaleixo** [comment]
setting this values the image that i received was:
![image](https://user-images.githubusercontent.com/1659954/121371072-a1243b80-c913-11eb-8fda-52eec9f870ea.png)

i have been tring this way to, but same problems occour:
![image](https://user-images.githubusercontent.com/1659954/121371482-f6604d00-c913-11eb-8154-1b832cdfd910.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by ricardomaleixo** [comment]
hi. 
https://codepen.io/ricardoaleixoo/pen/YzZjMMw

**Comment by martynasma** [comment]
Thanks.

Unfortunately, I wasn't able to find a way to generate a PNG output from a chart that is not part of DOM.

Another suggestion: put the chart in a hidden container with dimensions set.

**Comment by ricardomaleixo** [comment]
i'll try this way, if hd success or not, i came here to tell.
