### ISSUE TITLE
Tooltip Background Color Update not happening

### ISSUE THREAD

**Issue by kaariwedoms** [amcharts/amcharts4#3577]
In my project scenario, I tried to update my tooltip props background color using these mentioned config

      series.tooltip.background.fill = am4core.color('#FFFFFF');
        series.tooltip.opacity = 1;

but still i am not 100% white background tone, whether any other additional configs need to be added?
Reference Link - https://codepen.io/redimkaari/pen/ExWgjyR

**Comment by martynasma** [comment]
Please refer to [this tutorial](https://www.amcharts.com/docs/v4/concepts/tooltips/#Color_inheritance).
