### ISSUE TITLE
Converting charts to a PNG then adding to a PDF page using jsPdf does not render the chart if process is running but I am on another Chrome tab or application / window

### ISSUE THREAD

**Issue by philiplee15** [amcharts/amcharts4#3579]
**Bug description**

When not focused on the Chrome tab in question, Amcharts does not fully render charts after some N number of chart renders (I usually get to about N = 10), if I am running a synchronous process of drawing several charts, converting them each into a `png` image and then using that image to add a page to a dynamically built PDF on the fly.

But if I babysit the process, and stay on the tab where the PDF is being rendered (1 page at a time up to 20 pages, with up to 4 amCharts on each page), then the PDF is successfully rendered with all chart images drawn into the PDF.

How can I insure that all the chart images are drawn onto the PDF for our Users on the client side, even if they decide to alt tab or switch tabs in their browser?

I am also noticing that once I reach about the 20-30 chart mark, the subsequent iterations of chart creations sometimes stop altogether and the library gives up, therefore my PDF will have a bunch of pages with incomplete charts, even if I do stay on the tab. I already optimized using dispose configurations && disabled animations to save memory, but still am experiencing this issue.

Chart code:
```
am4core.addLicense(AMCHART_LICENSE_KEY);
am4core.options.autoDispose = true;

// Final PDF Specific Events
if (vueThis.isPdfPage) {
	// // Store data as an output
	chart.exporting.getImage("png").then(function(imgData) {
		vueThis.theChart = imgData;
		chart.dispose();
		vueThis.$emit('outcome-chart-image-complete');
	});
	
	// Download data in browser
	// chart.exporting.export("png");
}
```

jsPdf code:
```
const doc = new jsPDF({
	orientation: 'p',
	unit: 'pt',
	format: 'a4',
});
var coverPage = document.getElementById("coverPageID");
let coverPageImage = await this.$html2canvas(coverPage, options);
doc.addImage(coverPageImage, 'JPEG', 0, 0, pdfWidth, pdfHeight); 
```
Note: The above code blocks happen in a synchronous loop for many charts using JS `await`.

**Environment (if applicable)**

Provide details about your development environment where you think it might be useful. E.g.:
 - amCharts version: ^4.10.4
 - Browser and its version: Chrome Latest
 - Related frameworks and their versions: VueJS, jsPdf, vue-html2canvas, html2canvas

**Additional context**
What I am trying to accomplish is to be able to render about 20 - 100 charts, convert each to an image so that I can successfully render them into a PDF using a png and then subsequently converting the entire html page containing the chart images into a PDF page during a single page load.

**Comment by schubwerk-acristea** [comment]
Hi, i have a similar issue. When exporting, sometimes the charts are completely black(a black block) or even white sometimes.

**Comment by martynasma** [comment]
I'm not familiar with jsPdf, but I suppose that when your export kicks in, not all of the charts are finished loading.

You will need to watch for "ready" event for ALL charts, and only then trigger export.
