### ISSUE TITLE
Disable legend without zooming out with X-Value Axis

### ISSUE THREAD

**Issue by JohnB299** [amcharts/amcharts4#3580]
When I zoomed in on graph and disable a series (clicking on legend) the graph zooms out. I would like to prevent this.

I have looked at issue 678 which proposes a solution and has a link to an example:
Issue: https://github.com/amcharts/amcharts4/issues/678
Example: https://codepen.io/team/amcharts/pen/LMGXpJ?editors=0010

However in my graph I do not have a date axis but instead a value axis for X-axis.
When I change  the example code and change xAxes to ValueAxis, use series datafields valueX iso dateX and change the date data to numbers I see a graph with nrs iso dates on the X-axes. 

However when I zoom in and then disable a series the graph zooms out again.

Is this behaviour correct? Or is it a bug? Or did I just forget to change something.

[AutoFixingValueScale_X_ValueAxis.js.txt](https://github.com/amcharts/amcharts4/files/6629809/AutoFixingValueScale_X_ValueAxis.js.txt)

**Comment by pota-too** [comment]
you have to convert xAxis to Category axis, not value axis.
`var xAxis = chart.xAxes.push(new am4charts.CategoryAxis()); 
xAxis.dataFields.category= "date";  // based on your data category name` 

and assign other parameters to series
`series.dataFields.categoryX = "date";`
`series2.dataFields.categoryX = "date";`

here the demo : https://codepen.io/pota-too/pen/yLMxdwJ

**Comment by martynasma** [comment]
This will do the trick:

```JavaScript
dateAxis.keepSelection = true;
```

**Comment by JohnB299** [comment]
Both solutions work. Thanks for the answers
