### ISSUE TITLE
Don't show emty XAxis lines

### ISSUE THREAD

**Issue by aivashchenkoFluke** [amcharts/amcharts4#3581]
Could you halp me. I can't see line for 1999 year. Because I haven't data for this year. If you zooming chart you can see problem
Example https://jsfiddle.net/7d9tx4eg/
<img width="1412" alt="chart" src="https://user-images.githubusercontent.com/84711987/121530888-90082700-ca06-11eb-938d-3ad7f73527da.png">

**Comment by martynasma** [comment]
If you need natural date scale, you may need to use DateAxis instead of CategoryAxis:

https://jsfiddle.net/54kfue2y/

**Comment by aivashchenkoFluke** [comment]
How to usr ValueAxis instead CategoryAxis? ValueAxis - https://jsfiddle.net/fmqvy3r1/ CategoryAxis - https://jsfiddle.net/fmqvy3r1/1/

**Comment by martynasma** [comment]
If you want to display `ColumnSeries` on a ValueAxis, you will need to assign fixed width to the columns:

```JavaScript
series.columns.template.width = 20;
```

**Comment by aivashchenkoFluke** [comment]
Thanks)
