### ISSUE TITLE
Schrodingers AMCharts: Charts do not convert to PNG if on another Chrome tab

### ISSUE THREAD

**Issue by philiplee15** [amcharts/amcharts4#3582]
Is there any way to force or insure amcharts render a chart when I am not on the specific chrome tab that is rendering the charts?

I have about 30 charts rendering. And it only successfully draws the charts that start drawing while I am on the said tab.

Users on the client side will generate a PDF usingg these charts, and they will most certainly alt tab away, but I want to make sure the charts are drawn and PDF is fully rendered in these cases.

**Comment by martynasma** [comment]
No, I'm afraid. The browser does not process frames on inactive tabs. Sorry.
