### ISSUE TITLE
Heat Map issues

### ISSUE THREAD

**Issue by DimaGavrushko** [amcharts/amcharts4#3583]
**Bug description**

I am trying to implement Heat Map using:
"@amcharts/amcharts4": "^4.10.18"
"react": "^17.0.1"

1.
I need a cursor (zoom) in Heat Map. 
https://codepen.io/team/amcharts/pen/pLOXgO - it is a link with your example of Heat Map. 
You can put that line in your example:  
```chart.cursor = new am4charts.XYCursor()```
and you can see that the behavior is not correct (tooltip always at the top of the chart).

2.
https://www.amcharts.com/docs/v4/tutorials/map-heat-legend-with-real-start-end-value-labels/#Problem

I am trying to display the first and last label in legend as described in the tutorial above. But that doesn't work. This is my code:

```
const series = x.series.push(new am4charts.ColumnSeries());
      if (series.tooltip) {
        series.tooltip.getFillFromObject = false;
        series.tooltip.getStrokeFromObject = true;
        series.tooltip.background.strokeWidth = 2;
      }
      series.dataFields.categoryX = 'time';
      series.dataFields.categoryY = 'date';
      series.dataFields.value = 'value';
      series.sequencedInterpolation = true;
      series.defaultState.transitionDuration = 3000;

      const columnTemplate = series.columns.template;
      columnTemplate.width = am4core.percent(100);
      columnTemplate.height = am4core.percent(100);
      columnTemplate.strokeWidth = 0.2;
      columnTemplate.strokeOpacity = 0.2;
      columnTemplate.stroke = am4core.color(Colors.white);
      columnTemplate.tooltipHTML = `
          <div style="color: #3E4543; line-height: 1.5em; font-size: 14px">
            {date} {time} <span style="font-weight: 500">{value.workingValue}</span>
          </div>
        `;

      series.heatRules.push({
        target: columnTemplate,
        property: 'fill',
        min: am4core.color(Colors.primary),
        max: am4core.color(Colors.blue[0]),
      });

      const heatLegend = x.bottomAxesContainer.createChild(
        am4charts.HeatLegend,
      );
      heatLegend.id = 'heatLegend';
      heatLegend.width = am4core.percent(100);
      heatLegend.valueAxis.renderer.labels.template.fontSize = 9;
      heatLegend.valueAxis.renderer.minGridDistance = 30;

      // eslint-disable-next-line no-inner-declarations,@typescript-eslint/no-explicit-any
      function handleHover(column: any) {
        if (!Number.isNaN(column.dataItem.value)) {
          heatLegend.valueAxis.showTooltipAt(column.dataItem.value);
        } else {
          heatLegend.valueAxis.hideTooltip();
        }
      }

      // heat legend behavior
      series.columns.template.events.on('over', (event) => {
        handleHover(event.target);
      });

      series.columns.template.events.on('hit', (event) => {
        handleHover(event.target);
      });

      series.columns.template.events.on('out', () => {
        heatLegend.valueAxis.hideTooltip();
      });

      heatLegend.series = series;
      heatLegend.valueAxis.renderer.labels.template.adapter.add('text', () => {
        return '';
      });

      const minRange = heatLegend.valueAxis.axisRanges.create();
      minRange.label.horizontalCenter = 'left';
      const maxRange = heatLegend.valueAxis.axisRanges.create();
      maxRange.label.horizontalCenter = 'right';

      series.events.on('datavalidated', (ev) => {
        const hl = ev.target.map.getKey('heatLegend');

        if (hl?.series) {
          const min = hl.series.dataItem.values.value.low;
          const minr = hl.valueAxis.axisRanges.getIndex(0);
          minr.value = min;
          minr.label.text = hl.numberFormatter.format(min).toString();
          const max = hl.series.dataItem.values.value.high;
          const maxr = hl.valueAxis.axisRanges.getIndex(1);
          maxr.value = max;
          maxr.label.text = hl.numberFormatter.format(max).toString();
        }
      });
```
and this is my result: 
![image](https://user-images.githubusercontent.com/22750804/121711452-4d684c80-cae3-11eb-884a-53aef99b9b99.png)

It would be nice if you could help me.

**Comment by xorspark** [comment]
Addressing these in order:

1) You can set `cursorTooltipEnabled` to false to prevent the chart cursor from triggering those tooltips, allowing you to keep the existing tooltip and have zooming available:

```
 series.cursorTooltipEnabled = false;
```


2) You can add ids to your min and max label and have the heat legend's value axis label adapter check the ids before returning either an empty string or the actual value:

```
heatLegend.valueAxis.renderer.labels.template.adapter.add("text", function(labelText, target) {
  if (target.id == "minLabel" || target.id == "maxLabel") {
    return labelText;
  }
  return "";
});

let minRange = heatLegend.valueAxis.axisRanges.create();
minRange.label.id = "minLabel"
minRange.label.horizontalCenter = "left";

let maxRange = heatLegend.valueAxis.axisRanges.create();
maxRange.label.id = "maxLabel";
maxRange.label.horizontalCenter = "right";
// ...
```

[Demo](https://codepen.io/team/amcharts/pen/0bda64e9639881116364bc7c3b319e9b?editors=0010)

**Comment by DimaGavrushko** [comment]
> Addressing these in order:
> 
> 1. You can set `cursorTooltipEnabled` to false to prevent the chart cursor from triggering those tooltips, allowing you to keep the existing tooltip and have zooming available:
> 
> ```
>  series.cursorTooltipEnabled = false;
> ```
> 
> 1. You can add ids to your min and max label and have the heat legend's value axis label adapter check the ids before returning either an empty string or the actual value:
> 
> ```
> heatLegend.valueAxis.renderer.labels.template.adapter.add("text", function(labelText, target) {
>   if (target.id == "minLabel" || target.id == "maxLabel") {
>     return labelText;
>   }
>   return "";
> });
> 
> let minRange = heatLegend.valueAxis.axisRanges.create();
> minRange.label.id = "minLabel"
> minRange.label.horizontalCenter = "left";
> 
> let maxRange = heatLegend.valueAxis.axisRanges.create();
> maxRange.label.id = "maxLabel";
> maxRange.label.horizontalCenter = "right";
> // ...
> ```
> 
> [Demo](https://codepen.io/team/amcharts/pen/0bda64e9639881116364bc7c3b319e9b?editors=0010)

thanks for your help!
