### ISSUE TITLE
Changing DateAxis Data Grouping Intervals by Time?

### ISSUE THREAD

**Issue by shortbrandonpe** [amcharts/amcharts4#3584]
I have a DateAxis on which I set up data grouping, and it is working when grouping data from 0000-2359 (midnight to 11:59 PM). However, I need to group the data from 0700-0659 (7AM to 06:59AM the next day). I'm trying to group everything from 0000-0659 with the previous days data values.

I followed this [link](https://www.amcharts.com/docs/v4/tutorials/using-custom-functions-for-data-item-grouping/), and tried to make the following code work:

```
series.adapter.add("groupValue", function (val) {
    if (new Date(val.dataItem.dataContext.Date).getHours() < 7) { // .Date is a date string which gives the date and time value of the data item
        var curDate = new Date(val.date);
        val.date.setDate(curDate.getDate()-1);
    }
    return val;
});
```

When I run `console.log()` on `val`, it shows the `date` property is expected for each raw data item, but when grouped the values are still by the calendar day. Is it possible to group data in this manner?

**Comment by martynasma** [comment]
Well, grouping is just about collecting several values into a single data point. Each group is still represented by a single timestamp, and is displayed according to DateAxis' rules.

If your grouping results ends up with one data point per day, then the axis displays one grid/label per day, with midnight as its "representative" label.

You can try modifying granularity using `baseInterval`, or can have an adapter on axis' labels to modify what's displayed in it.

Hope that makes sense.

**Comment by shortbrandonpe** [comment]
That will solve how I can display the label correctly. Now I need to ensure the aggregate operations on the data values follow the same logic.

I have one datapoint for every hour of the day and the default granularity is showing the hour points. However, when enough data points are present to trigger grouping to 1 datapoint per day, I'm trying to ensure the values are grouped from 0700-0659, not from 0000-2359. 

My first datapoint is always at 0700. I've tried grouping by `{ timeUnit: "day", count: 1 }` and `{ timeUnit: "hour", count: 24 }` and based on the math the values still seem to group from 0000-2359.

**Comment by martynasma** [comment]
Well, the grouping mechanism is still trying to group into actual periods. That means if it's trying to group into days, then it will take data points from 0000 to 2359, and will kick over those data points to the `groupValue` adapter.

I don't think there's any way to set up grouping with "custom days".
