### ISSUE TITLE
Maximum Call stack size exceeded : Pie Chart

### ISSUE THREAD

**Issue by rrg1248** [amcharts/amcharts4#3587]
Hello,

I am getting maximum Call stack error while loading the pie chart:

Data: Attached file : Data.txt
Code: Attached file : Code.txt

[data.txt](https://github.com/amcharts/amcharts4/files/6647406/data.txt)
[code.txt](https://github.com/amcharts/amcharts4/files/6647408/code.txt)

Please help

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by rrg1248** [comment]
Hello,

Please find below codepen link

https://codepen.io/rrg1248/pen/RwpqqBx

Thanks

**Comment by martynasma** [comment]
You have `series.dataFields.value` set to the same as `series.dataFields.category`. I suppose that's a mistake.

It should point to a field with a numeric value.

**Comment by rrg1248** [comment]
It is working now.
Thanks a lot for quick help.

**Comment by rrg1248** [comment]
Thanks a lot. Closing this issue.
