### ISSUE TITLE
YAxis dissapears when change the data of the chart

### ISSUE THREAD

**Issue by victor-luke** [amcharts/amcharts4#3588]
**YAxis dissapears when change the data of the chart**

Im using XYChart in a vue project. and had problem when change the data, the XYAxis dissapears when try change/update the data

Example:
![image](https://user-images.githubusercontent.com/85583638/121940052-8af6f080-cd02-11eb-925e-c492f9397b96.png)

![image](https://user-images.githubusercontent.com/85583638/121940391-e88b3d00-cd02-11eb-8552-1614933d1e6c.png)

Create the chart in the event mounted
and had propierties (data, series) used to update the info in the chart using watch

Example:
https://9t07i.csb.app/

The first time that click add button, the YAxis is shown, but the second time the YAxis dissapears

**Comment by martynasma** [comment]
Chart expects a pure `Array` as its data.

You are using `this.chartData` which is some sort of modified object, as well as do any manipulations to it.

The chart might not quite grab all the changes you're doing to it.

So there are two options:

1) Make sure you assign chart.data with an array:

```
this.chart.data = data;
```

OR

2) Trigger reparsing of data after each update:

```
this.chart.invalidateData();
```

**Comment by victor-luke** [comment]
Thanks, that helped me with my problem

**Comment by victor-luke** [comment]
I reopened the issue because the bug kept appearing, i change the way that assign the data, now

**Comment by martynasma** [comment]
I'm not sure why it's happening. I can't reproduce this outside of Vue.

That said, the issue is not there if you do not remove and re-create series on every data update.

Not recreating series would be better for performance, too.

Do you think you could go that way?
