### ISSUE TITLE
Behavioral change in hovering of labels in Pie-chart?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3589]
Hi 
I'm currently using amcharts4 in my appplication where the pie-chart is displayed with corresponding label and values were listed.
At  some point i'm not able to place my cursor over label.

![Screenshot from 2021-06-15 15-34-06](https://user-images.githubusercontent.com/71019344/122034475-30878e00-cdef-11eb-907e-eab947187907.png)
In the above picture while i'm moving my cursor to deselect the items from top to bottom, all of sudden at NMS partner i'm not able to see the cursor to perform my functionality.

I don't know what's the reason behind that, but when i hover around the text of NMS partner i'm able to see cursor at point and perform my functionality. 
I need to get the cursor exactly whenever i hovered on the labels. But it's failing.

I kept below lines of code
`pieSeries.labels.template.disabled = true;
            pieSeries.ticks.template.disabled = true;
            // disabling slice tooltip
            pieSeries.slices.template.tooltipText = '';
            pieSeries.slices.template.marginLeft = 40;
`

Can you tell me exactly what's going on and how to overcome this scenario?

Thank you.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by meghanaNanuvala** [comment]
I have added the code [testing](https://codepen.io/meghanananuvala/pen/VwpgBEj?editors=1010) but here i'm not able execute and getting error as **Maximum call stack size exceeded** and getting error at usedefaultMarker.

Can you check

**Comment by martynasma** [comment]
Two things:

1) You do not create legend at all in your CodePen.
2) You have data fields for value and category mixed up.

After fixing those, legend works fine for me in your CodePen.

**Comment by meghanaNanuvala** [comment]
Here, [attached](https://codepen.io/meghanananuvala/pen/VwpgBEj) i created legend but i didn't get the second point.

**Comment by meghanaNanuvala** [comment]
[link](https://codepen.io/meghanananuvala/pen/VwpgBEj).

**Comment by martynasma** [comment]
OK, so can you sum up what's wrong with the chart?

You mentioned cursor. There's no cursor on PieChart. I'm afraid I can't quite understand the issue, even after reading through original description a few times.

**Comment by meghanaNanuvala** [comment]
Codepen is working fine. In my application i written the same lines of code but at some point whenever i hover on labels of pie-chart to disable i can't see the mouse hand on particular label.
![Screenshot from 2021-06-17 13-43-41](https://user-images.githubusercontent.com/71019344/122358234-14f8c080-cf72-11eb-8b02-164d03bd9658.png)
if i try to disable the NMS partner, i'm not able to see mouse hand and whenever hover around the text NMS partner i'm able to see. I need to overcome this

**Comment by martynasma** [comment]
I'm not sure what to suggest. Is there any way you can provide a repro case?
