### ISSUE TITLE
Series over / out events triggerd by Cursor on Category Axis

### ISSUE THREAD

**Issue by alessandrovir** [amcharts/amcharts4#3590]
Hi,
in one of my projects I implemented a variation on this chart
https://www.amcharts.com/demos/bubble-based-heat-map/

What I have is a Bubble Chart with a Category Axis (X) and a Value Axis (Y) with some "bubbles" that are shown based on a value of the data that represent the bubble.
One of the requests is to add the zoom to the chart. 
To enable this, I added a cursor (following code) since I need to zoom only on Y axis (I am not intereseted on X axis now).

```
chart.cursor = new am4charts.XYCursor();
chart.cursor.behavior = 'zoomY';
```

Each bubble has its own tooltip that shows a string defined in separate field, like the tooltip in the example.
In addition to this I added two event handlers, these are some of my customizations.

1) Bubble over 
2) Bubble out

They defines a callback to handle the showing or hiding of an outline for the bubble.

I have two problems now, that I think they are strictly linked.
Please check my codepen to have an example. I edited the first exaple to reflect my customizations
https://codepen.io/alessandrovir/pen/MWpzxwZ

First Problem
When I move with the mouse pointer in the graph area (blank/ white area), it triggers the tooltip on the first bubble added (the one on top,  in my codepen), if the mouse pointer is on a specific bubble, the relative tooltip is shown.
I want to disable the first behavior because I want to trigger the tooltip only when I am with the cursor exactly on the bubble. Or rather, I want to stop the event propagation triggerd from the cursor to the first bubble. It seems that the cursor triggers the over event on the first bullet by default.  ​

Is there a way to show the tooltip only when I am on the bubble? 

I see that this is happens only with the combination category-axis + cursor, line if the category cell over event propagates through the series. 
If I use a value axis on the x axis, this does not happen. But i need the category axis in my chart.
I tried also to showing / hiding the tooltip as a callback in the over / out event  of the bullet (see second problem) but I have some issues handling the events.
 
Second Problem
Points 2 & 3 are defined as follows (you can check my codepen, use browser console to see the logs)

```
bullet.events.on('over', event => { 
// something
})
bullet.events.on('out', event => {
// something
})
```

bullet is an am4charts.Bullet object

As in the first problem, the cursor movement on blank area, triggers the "over" event on the first bubble, with a generic event, but overing the first bubble with the cursor does not trigger any event. 
All works fine inside with other bullets.

In the second event handler (out) when I "leave" the first bullet, it emits the right event (as the one emitted by other bubbles, it is a pointer event) than emit the event of the cursor (it triggers the first callback).

What I am expecting on both events is the same behaviour for all the bubbles, the callbacks must be executed only when i am with the mouse pointer on the bubble instead I have different behaviours with respect to the bubble triggered by cursor and bubbles triggered with pointer over / out.

I wasn't able to enable / disable tooltip neither through callbacks because the event for the first bubble does not work as expected.

Thank You

**Comment by xorspark** [comment]
Setting `cursorTooltipEnabled` to false on the series should fix both of your problems:

```
series.cursorTooltipEnabled = false;
```

**Comment by alessandrovir** [comment]
Thank you @xorspark ! It works as expected!
