### ISSUE TITLE
Value labels are duplicating and different lengths

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#3591]
There's 2 issues present that we've been getting complaints about that both have to do with y-axis labels on an xy chart. The difference is present depending on whether the y-axis is forced to start at 0 or not. For all of the below examples, the only thing changing between each example is the amcharts version and forcing the zero axis. Otherwise the code is identical.

### Issue 1
Y-axis forced to zero.
The number formatting is not staying the same length. This broke in version 4.10.14 and is still an issue in the latest version.
before (4.10.13): https://codesandbox.io/s/amcharts4-y-axis-format-issue-before-sofq4
![image](https://user-images.githubusercontent.com/3292053/122085068-9c520280-cdbf-11eb-8fea-5077cf0047f7.png)

after (4.10.14): https://codesandbox.io/s/amcharts4-y-axis-format-issue-after-p4u03
![image](https://user-images.githubusercontent.com/3292053/122085340-dc18ea00-cdbf-11eb-9cd2-f5a325b15a70.png)

### Issue 2
Y-axis not forced to zero.
Numbers get repeated on the axis. You can see some are whole numbers and some are decimals, but repeats appear. This happens all the way back to 4.5.14 and is still present with the latest version.
before (4.5.13): https://codesandbox.io/s/amcharts4-y-axis-duplicate-issue-before-kvkic
![image](https://user-images.githubusercontent.com/3292053/122092011-af1c0580-cdc6-11eb-9f4f-ff7c2c15d5e5.png)

after (4.5.14): https://codesandbox.io/s/amcharts4-y-axis-duplicate-issue-after-y2liy
![image](https://user-images.githubusercontent.com/3292053/122092248-ef7b8380-cdc6-11eb-8cce-c369427cb16c.png)

For all of these, I'm testing on the latest chrome for latest mac, but I believe it has been happening for clients across windows and safari as well.

**Comment by martynasma** [comment]
Do any of those happen with the latest version (4.10.19)?

I believe we fixed some label/grid issues in 4.10.19.

**Comment by runfaj** [comment]
@martynasma Yes, both are still issues in the latest version unfortunately.

**Comment by martynasma** [comment]
I dug around your app, and it seems there's a lot of custom code. Would you be able to whip up standalone charts, without the overhead of the custom app, which we can test?

**Comment by runfaj** [comment]
@martynasma I updated the two "after" examples that show the issue to only show the code that is rendering the chart. All the configs and chart data can be found in the `src/chart/renderer.js` file:
- the chart data and the showZeroAxis flag is at the top of the file
- the global amcharts options are after the chartData
- the default chart number formatting is found at line 73, followed by loading the chart color and then loading the xy chart
- The xy chart configuration is in the loadXYChart method

**Comment by martynasma** [comment]
The issue seems to be caused by `1` entry in `bigNumberPrefixes`:

```JavaScript
// misc
  bigNumberPrefixes: [
    { number: 1, suffix: "" },
    { number: 1e3, suffix: "k" },
    { number: 1e6, suffix: "M" },
    { number: 1e9, suffix: "B" },
    { number: 1e12, suffix: "T" },
    { number: 1e15, suffix: "P" },
    { number: 1e18, suffix: "E" },
    { number: 1e21, suffix: "Z" },
    { number: 1e24, suffix: "Y" }
  ]
```

Having 1 there does not make a lot of sense to me.

**Comment by runfaj** [comment]
@martynasma That addition was based on the suggestion and enhancement here: https://github.com/amcharts/amcharts4/issues/1721.

Removing it does appear to help a little with the forced zero axis:
![image](https://user-images.githubusercontent.com/3292053/122580995-ce5ba280-d013-11eb-813d-2ed7c5d26dc9.png)

However, without the zero axis, this is _technically_ fixed, but looks quite a bit more cluttered.
before:
![image](https://user-images.githubusercontent.com/3292053/122581586-707b8a80-d014-11eb-8bbd-9265ea0f2f0a.png)

after:
![image](https://user-images.githubusercontent.com/3292053/122581792-a751a080-d014-11eb-951f-ff6efa5a6a06.png)

For both cases, is there a way to keep the number length as consistent as possible? For this example value of `2` for the column:
- with zero axis, keeping everything to a single decimal works (for this particular single value on the chart):
0, 0.1, ..., 0.8, 1.0, 1.2, ... 1.8, 2.0, 2.2. (However, seems like there are a lot more than there needs to be - incrementing by .5 in this case might make more sense since showing 12 values for a single '2' on the chart is a bit overkill.)
- without the zero axis, maybe something like: 1.8, 1.9, 2, 2.1, 2.2. Or even having at 2 decimals is fine 1.80, 1.85, 1.90, 1.95, 2.00, ... as long as there's some more consistency on the lengths of shown digits.

Talking with our designer, I think we can live with the number of axis values (even if 10-12 is quite a lot for this particular use case), but getting the length of decimals consistent is much more important. We can't set to a specific length because the actual number selected for any given chart can range anywhere from 0 to 5 decimals, so ideally whichever displayed decimal is longest on the chart, all the others would match. For example, if the longest decimal on the chart was 1.125, then maybe the corresponding values on the axis would be 0.875, 1.000, 1.125, 1.250, ... Is this possible?

**Comment by martynasma** [comment]
How about setting `maxPrecision` on ValueAxis?

**Comment by runfaj** [comment]
@martynasma Tried that with 1, 2, and 3 for the value - it just limits the length, but doesn't make the lengths consistent:
![image](https://user-images.githubusercontent.com/3292053/122779895-8e8ef800-d26b-11eb-8b48-d3ed6c246cb4.png)

Ideally the image above would show everything with 2 decimals (e.g. 1.80, 1.85, 1.90, ...). I do see that adjustLabelPrecision does this, but as soon as abbreviations for large numbers are needed (e.g. a number format of `#.##a`, this isn't possible. Is there some way, or potential feature that could be added to allow this decimal length to be consistent even with number formatting applied?

**Comment by martynasma** [comment]
At this moment we do not plan on any changes, and I'm not aware of a way to solve this :(

I suppose your best way would be to use an adapter to format labels using your own code. Something like this:

```JavaScript
valueAxis.renderer.labels.template.adapter.add("text", function(text, target) {
  if (target.dataItem.value < 1000) {
    return target.numberFormatter.format(target.dataItem.value, "#.00");
  }
  else {
    return text;
  }
});
```

(I did not test the code above, just an idea)

**Comment by runfaj** [comment]
Thanks - we'll have to look into that option. I'll close this out, since the original issue seems to be resolved!
