### ISSUE TITLE
Firefox issue - Not renderering XY Cloumn series in firefox

### ISSUE THREAD

**Issue by ramiks** [amcharts/amcharts4#3592]
Hi Team,

I am using amchart 4.10.13 in angular 9, Amchart xy chart column series not displaying in Firefox browser.

How to fix the issue.

Thanks in Advance

Regards,
Ramji

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on codesandbox/stackblitz so that we can test?

**Comment by ramiks** [comment]
Hi Team,

Thanks for your reply
I have created stackblitz sample code based on the another example

https://amcharts4-xqfzav.stackblitz.io/

The values are hard-coded one but my scenario its dynamically loading the values.

The same chart working in chrome and Edge. But its not rendering in Firefox. i am using Firefox version 89.0.1.

Thanks in Advance

**Comment by martynasma** [comment]
The demo does not work for me in none of the browsers. The spinner just keeps on spinning :(
