### ISSUE TITLE
How can i apply CategoryAxis with StepLineSeries correctly?

### ISSUE THREAD

**Issue by victor-luke** [amcharts/amcharts4#3593]
I'm using amchart4 in vue.js and  have a data collection which has 2 states(on, off) and i created the chart with `StepLineSeries` and change the status for values(0,1), but i wanna replace `0 to "off"` and `1 to "on"`

![image](https://user-images.githubusercontent.com/85583638/122272897-b3fbba80-ce95-11eb-8887-e73e54f454e5.png)

Then I tried to use `CategoryAxis` but I had a problem, the graph is displayed weirdly

![image](https://user-images.githubusercontent.com/85583638/122277465-c62c2780-ce9a-11eb-9975-0dd00677ea32.png)

How can i apply CategoryAxis with StepLineSeries correctly?

**My example:**
https://iq1xo.csb.app/

**Comment by martynasma** [comment]
I'd say you leave 0 and 1, but replace those with "On" and "Off" using adapters.

```JavaScript
valueAxis.maxPrecision = 0;
    valueAxis.renderer.labels.template.adapter.add("textOutput", (text, target) => {
      if (text == "2") {
        return "On";
      }
      else if (text == "1") {
        return "Off";
      }
      else {
        return "";
      }
    })
```

**Comment by victor-luke** [comment]
thank you very much, this worked for me
