### ISSUE TITLE
How to display tooltip valueX or valueY and multiply by some value

### ISSUE THREAD

**Issue by aivashchenkoFluke** [amcharts/amcharts4#3594]
How to display tooltip valueX or valueY and multiply by some value. For example I need valueX multiply by 5?
<img width="598" alt="Screenshot 2021-06-17 at 15 27 46" src="https://user-images.githubusercontent.com/84711987/122396363-96efe600-cf80-11eb-80b9-806f6ff467b8.png">

**Comment by martynasma** [comment]
You can use an adapter to dynamically construct the tooltip content:

```JavaScript
series.tooltip.label.adapter.add("text", function(text, target) {
  var text = "Frquency: " + (target.dataItem.valueY * 5) + "\n" +
             "Magnitude: " + (target.dataItem.valueX * 5);
  return text;
});
```
