### ISSUE TITLE
Force-directed-tree : Re-rendering of the chart when data is updated

### ISSUE THREAD

**Issue by Chinmay-k96** [amcharts/amcharts4#3595]
I am developing a  react application where I need the force-directed-tree to update its data on a button click. I have tried doing it with an example of color change below

https://codesandbox.io/s/keen-bas-e1f3o?file=/src/styles.css:0-284

But here the entire chart is refreshed to change the color of a single node. Is it possible to re-render just the single node to change the color keeping the other nodes intact ?

**Comment by martynasma** [comment]
No, I'm afraid. ForceDirectedTree does not not support incremental data updates.
