### ISSUE TITLE
How remove duplicate tooltip when xAxes is DateAxis and series match in date and value?

### ISSUE THREAD

**Issue by victor-luke** [amcharts/amcharts4#3596]
I have a chart and a customized tooltip, where tooltip shows all values in the same tooltip

When the date is the same  but value is different, the tooltip shows fine the info

![image](https://user-images.githubusercontent.com/85583638/122494240-ded13600-cf9d-11eb-8567-21b85fd52fab.png)

My problem is when date and value match between series

![image](https://user-images.githubusercontent.com/85583638/122494437-366fa180-cf9e-11eb-920e-8a8702f633be.png)

the tooltip shows 2 times.

What can I do so that the tooltip does not appear 2 times?

**Example**
https://4crzp.csb.app/

**Comment by martynasma** [comment]
This will do the trick:

```JavaScript
chart.cursor.maxTooltipDistance = -1;
```

There's a note about `-1` setting here:
https://www.amcharts.com/docs/v4/concepts/chart-cursor/#Limiting_number_of_series_tooltips
