### ISSUE TITLE
Get Value from Label, total sum.

### ISSUE THREAD

**Issue by kamilkifer** [amcharts/amcharts4#3597]
Im working with React.

I have a graph with a label that calculates the total.
I'm trying to assign the value inside the label to a different variable and use it in a div elsewhere.

Here is an similar example on [CodePen](https://codepen.io/k-kifer/pen/MWpxEdv):
The closest I gotten was managing to console.log = "test: ${values.value.sum}" instead of $1,438.9
Alternatively my code is

```var label = series.createChild(am4core.Label);
var label = series.createChild(am4core.Label);
 label.text = "Total Sum Matched: {valueY.sum} Daily Average: {valueY.average.formatNumber('###.')}";
 tempValue = label.dataItem.value
 console.log("TEMPVALUE IS : " + tempValue)
 

Is something like this possible?

**Comment by martynasma** [comment]
Yes:

```JavaScript
label.adapter.add("textOutput", function(text) {
  console.log(text);
  return text;
});
```

**Comment by kamilkifer** [comment]
Perfect, Thanks!
