### ISSUE TITLE
How can I tell it to chart something that's under a specific json object

### ISSUE THREAD

**Issue by hostup** [amcharts/amcharts4#3598]
Hi everyone.

I am using https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/ to display a chart from a json file.

Here's my [json file](https://zanopool.com/assets/ZxCSZQw1fKNHXFDnfSgCoEWTUTHjgRbiWjWMcuZ9TzKoFurXHeS6FfRKTVPK5ekr5tQNuUKVLziNGhjwK9hiAFTH2YYLgCxGB.json).

I am wondering how I can specify a value that's not direct like time, but display hr that's under miners > string > hr

While `series1.dataFields.categoryX = "time";` works fine, I tried to experiment to find a solution but it didn't work
`series1.dataFields.valueY = "miners,ZxCEuUp34WYFzZq7CQdRQGjjxC2DY2MH22SowQCdHzd6Wz3MRTfdBmW2d6itLwv8jjegGZtadXsEGcaV5Tyyf8Hy1pV1x3DQR,hr";`

**Comment by xorspark** [comment]
Accessing nested properties through dataFields and propertyFields is not supported. Sorry. You'll want to look into transforming your data using the `parseended` event into the standard array of objects format the library expects. There's an example of the event in the documentation you linked here: https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/#Handling_events
