### ISSUE TITLE
Is it possible to set category axis and value axis as Stacked Axes

### ISSUE THREAD

**Issue by manushakaru** [amcharts/amcharts4#3599]
**Question**
I wanted to show Line series chart and Gantt chart in  a one chart as stacked axes. So, I tried the stacked axes examples and it shows value axis and it's data properly but it does not show the Gantt chart. Is it possible to do that kind of scenario? 

**Environment (if applicable)**
amcharts 4
Angular 11

**Additional context**

**Comment by martynasma** [comment]
Technically, you can stack any axis.

However, I'm not sure what you are trying to implement. Do you perhaps have a mockup and a CodePen of what you tried so far?

**Comment by manushakaru** [comment]
@martynasma Thanks for your reply. 

Basically I was trying to stack category axis and value axis. I wanted to show line graph and related time ranges according to some type of categories(best option was Gantt chart). So, I need to include Gantt chart and line chart in a one chart (stacking is more suitable in my use case) . Both charts will use their own data sets. [Here ](https://codepen.io/manushakaru-the-selector/pen/dyvErxB ) I have created the basic structure of the graph using some example.

**Comment by martynasma** [comment]
OK, so you almost got it right, except one thing: CategoryAxis has no data, so it cannot know which categories there are, since you set data directly on series.

To fix that, simply set the same data on the axis as you do on your series for Gantt:

```JavaScript
categoryAxis2.data = data;
```

**Comment by manushakaru** [comment]
@martynasma Perfect. It worked. Thanks very much. Highly appreciate your quick reply.
