### ISSUE TITLE
How to assign multiple value to the legend?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3601]
Hi 
I'm working on amcharts4 where i used nested pie-charts which indicates both values. I need to set legend with corresponding values to display in single row each.

![Screenshot from 2021-06-21 19-56-59](https://user-images.githubusercontent.com/71019344/122778760-e1e46300-d2ca-11eb-91d0-d61a09e73817.png)
let's say, the outer pie indicates value and inner pie indicates volume of category. I need to set the legend as 
category-value-volume in a single row and so on.

Can you let me know how to approach to that.

Thank you.

**Comment by martynasma** [comment]
I'm afraid multi-value legend is not supported. Sorry.

**Comment by meghanaNanuvala** [comment]
Can you consider this as a feature request and implement this? Also, is there any work-around currently to achieve this ?

**Comment by martynasma** [comment]
I'm afraid we're not planning on adding a feature like that.

That you can created custom `Container` elements in chart and selectively move legend items to them.

Here's a working example:
https://www.amcharts.com/docs/v4/tutorials/selectively-placing-legend-items-in-different-containers/
