### ISSUE TITLE
How to reduce the gap between legend label and value?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3602]
Hi

I'm working on amcharts4 pie-chart where legend labels and corresponding values were displayed. But i tried to set minimum gap between them. It doesn't reflect.
![Screenshot from 2021-06-21 20-03-25](https://user-images.githubusercontent.com/71019344/122780000-0bea5500-d2cc-11eb-9f32-1c4315367cd9.png)
Below set of lines were used:
` chart.numberFormatter.numberFormat = '#,###.##';
            chart.legend.valueLabels.template.align = 'right';
            chart.legend.valueLabels.template.textAlign = 'end';
            chart.legend.position = 'right';
            chart.legend.valign = 'middle';
            chart.legend.maxWidth = 400;
            chart.legend.labels.template.maxWidth = 200;
            chart.legend.labels.template.truncate = false;
            chart.legend.labels.template.wrap = true;
            chart.legend.valueLabels.template.truncate = false;
            chart.legend.itemContainers.template.paddingTop = 3;
            chart.legend.itemContainers.template.paddingBottom = 8;
            chart.legend.valueLabels.template.marginLeft = 80;`

Can you help me out with this.
Thank you.

**Comment by martynasma** [comment]
Maybe reduce the `maxWidth` setting you have set on your legend?

**Comment by meghanaNanuvala** [comment]
Still i'm not able to reduce the gap. I am attaching that [code](https://codepen.io/meghanananuvala/pen/VwpgBEj?editors=1010)
Can you check that

**Comment by martynasma** [comment]
OK, this line produces the gap:

```JavaScript
chart.legend.valueLabels.template.marginLeft = 80;
```

I don't think you need 80px margin between value labels and name labels.
