### ISSUE TITLE
sizechanged event not rendering the same as when initially rendered causing wrapped text not centered if single line

### ISSUE THREAD

**Issue by robertpotter2** [amcharts/amcharts4#3603]
When have category labels wrap=true and textAlign="middle" and have event sizechanged not positioning in the middle correctly when the category label is short and not wrapped on initialization. The initial load is not an issue but occurs after any sizechanged event on the chart or categoryAxis. 

See link to my codepen example https://codepen.io/RobPotterII/pen/abJrmKb

My example is derived from the amcharts tutorial on wrapping and given the issue I experimented with an adapter for textAlign that applied "middle" only for longer category labels and nothing "" for shorter ones. If you change the adapter to always return "middle" for each category dataItem (or just comment out the adapter temporarily) then you the issue for single line labels. 

However, trying to do a complex workaround to estimate pixel length of label and determine if would be wrapped and integration with the sizechanged event.  Is there a better way to override the label itemContainer such as with text-align: center for each category data Item? Of course, it would be simplest to address the issue so the sizechanged calculates the same as when initialized.

Please advise on better workaround pr when fix would be available.

Rob

**Comment by robertpotter2** [comment]
I simplified the title on the issue.  See my example in code pen that needs an adapter and require a further substantial further workaround to deal with single lines that need to wrap.

**Comment by zeroin** [comment]
I think the problem was caused by the padding, If I remove it, the labels are positioned in the middle:
https://codepen.io/team/amcharts/pen/KKmpPaa
