### ISSUE TITLE
Floating stacked series above hidden series

### ISSUE THREAD

**Issue by datafoo** [amcharts/amcharts4#3606]
If `invalidateRawData` is called on a chart with 2 stacked `ColumnSeries` (or `StepLineSeries`) and the lowest series is hidden then the chart will repaint the visible series stacked above the hidden series instead of being stacked on the axis.

In other words the series on the top will float above the invisible series on the bottom.

To reproduce:
- open pen <https://codepen.io/jackfoo/pen/NWpZZKm?editors=0011>
- click in the legend to hide the "Research" series
- click on the "Change Data" button
- observe the "Marketing" series floating above the hidden "Research" series

**Comment by zeroin** [comment]
Hi,

I could suggest you this workaround:

```
button.onclick = function() {
  chart.invalidateRawData();
  series.events.once("validated", ()=>{
    chart.series.each((series)=>{
      if(series.isHidden){
        series.hide(0);
      }
    })
  })
};

```

I am afraid we can not fix this from inside.

**Comment by datafoo** [comment]
> ```
> button.onclick = function() {
>   chart.invalidateRawData();
>   series.events.once("validated", ()=>{
>     chart.series.each((series)=>{
>       if(series.isHidden){
>         series.hide(0);
>       }
>     })
>   })
> };
> ```

This workaround is less than ideal because it flashes to re-hide the series.

> I am afraid we can not fix this from inside.

What would block fixing this issue?

**Comment by zeroin** [comment]
I modified the workaround to solve the flicker:

```
button.onclick = function() {  
     chart.series.each((series)=>{
       series.validateRawData();
      if(series.isHidden){
        series.hide(0);
      }
    }) 
};
```

**Comment by datafoo** [comment]
I have noticed the same problem in 2 different cases: when replacing the data and when using `addData`.

Code pens:
1. [invalidateRawData](https://codepen.io/jackfoo/pen/NWpZZKm)
2. [replace data](https://codepen.io/jackfoo/pen/NWjWqGp)
3. [addData](https://codepen.io/jackfoo/pen/oNWNXjr)

**Comment by datafoo** [comment]
I use the 3 cases mentioned above to update the data of a live chart. I manipulate the data for the whole chart not individually per series so the updated workaround does not seem useful at the end.

Here is my code for information:
```ts
const mergeData = (chart: am4charts.XYChart, incoming: DataItem[]) => {
  const existing = chart.data;

  if (incomingStartsWithExisting(existing, incoming)) {
    chart.addData(incoming.slice(existing.length));
  } else if (shouldUpdateExisting(existing, incoming)) {
    for (let i = 0; i < existing.length; i++) {
      existing[i].slot = incoming[i].slot;
      existing[i].direct = incoming[i].direct;
      existing[i].cyclic = incoming[i].cyclic;
      existing[i].directAcc = incoming[i].directAcc;
      existing[i].cyclicAcc = incoming[i].cyclicAcc;
    }
    chart.invalidateRawData();
    chart.addData(incoming.slice(existing.length));
  } else {
    chart.data = incoming;
  }
};
```

**Comment by martynasma** [comment]
We believe that this is coming outside of the free support scope.

In case you do have a support subscription, would you drop us a line on contact@amcharts.com to discuss this further?

**Comment by datafoo** [comment]
> We believe that this is coming outside of the free support scope.
> 
> In case you do have a support subscription, would you drop us a line on [contact@amcharts.com](mailto:contact@amcharts.com) to discuss this further?

This issue is a bug report, not a request for support. Thanks for letting me know though.
