### ISSUE TITLE
Is it possible to create Multivariate Choropleth Map?

### ISSUE THREAD

**Issue by komaldudakiya** [amcharts/amcharts4#3608]
I want to create a choropleth map with 4 variables. Is there a provision to achieve such kind of map? Something like this:

![Multivariate_Choropleth_Map](https://user-images.githubusercontent.com/49227447/123442354-6cda9b80-d5f2-11eb-8834-a0493906c60d.PNG)

**Comment by martynasma** [comment]
You would need to use an adapter for that.

The following tutorial shows similar approach for a regular XYChart:
https://www.amcharts.com/docs/v4/tutorials/multi-color-xy-heatmap/

It would work very similarly for map as well, except that you would target `polygonSeries.mapPolygons.template`.

**Comment by martynasma** [comment]
You would need to use an adapter for that.

The following tutorial shows similar approach for a regular XYChart:
https://www.amcharts.com/docs/v4/tutorials/multi-color-xy-heatmap/

It would work very similarly for map as well, except that you would target `polygonSeries.mapPolygons.template`.
