### ISSUE TITLE
'[]' in Sankey plot data does not render

### ISSUE THREAD

**Issue by ssingh13-rms** [amcharts/amcharts4#3609]
**Bug description**

Data inside '[]' in Sankey plot is not rendered

JS Fiddle to reproduce the bug
https://jsfiddle.net/vufmL8yd/

How it looks:
![Screenshot 2021-06-28 at 2 14 52 PM](https://user-images.githubusercontent.com/47655001/123607153-3a5fb700-d81b-11eb-8af5-ed199bd6ea88.png)

The data:
![Screenshot 2021-06-28 at 2 15 20 PM](https://user-images.githubusercontent.com/47655001/123607227-4d728700-d81b-11eb-9888-a0d62ce1a77a.png)

**Additional context**
Using the Sankey demo from amCharts 4 documentation
https://www.amcharts.com/demos/sankey-diagram/

**Comment by zeroin** [comment]
Just add two [[ and ]] to avoid this:

`{ from: "B", to: "*[[this text will be missing]]*", value: 4 },`

**Comment by ssingh13-rms** [comment]
Thanks for pointing that out @zeroin! 
is this expected behaviour? I will be using the same data in other plots too

**Comment by ssingh13-rms** [comment]
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/
Similarly everything that goes within square brackets [ ... ] is treated as text formatting options, and again is not displayed but rather parsed for text styling instructions.

Should've read the documentation 🤕
