### ISSUE TITLE
dateAxis.positionToDate() returns incorrect value on zoomed chart

### ISSUE THREAD

**Issue by sabi-wabi** [amcharts/amcharts4#3612]
**Bug description**

Goal: Get the date from the date axis as the user scrolls horizontally across the chart. 

`  chart.cursor.events.on("cursorpositionchanged", (e) => {
      const date = new Date(
        dateAxis.positionToDate(e.target.xPosition)
      )});
`

Issue: 

When the user zooms in the chart, the calculated `date` is based on the unzoomed chart's position. 

For example, say that the `dateAxis` have a range from the year 2000 to 2050. 

If the user zooms to between the year 2030 and 2040, and have his cursor right in the middle of the chart, the returned date from `positionToDate` would be 2025 instead of 2035. 

**Environment (if applicable)**

 amCharts version: 4.10.18
 Browser and its version : Brave, latest 
 Related frameworks and their versions : TypeScript

**Comment by zeroin** [comment]
You should convert cursor position to axis position before using positionToDate, like:

`dateAxis.positionToDate(dateAxis.toAxisPosition(e.target.xPosition))`

https://www.amcharts.com/docs/v4/reference/axis/#toAxisPosition_method

**Comment by sabi-wabi** [comment]
Thank you. Apologies for not reading the documentation extensively enough.
