### ISSUE TITLE
How to set pie-chart  size based on the space availability?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3613]
Hi
I'm working on amcharts4 where pie-chart is drawn by giving values to radius and inner-radius. But that size seems to be good in resolution with 1366x768. So when we observe same chart in 1900 resolution screen it's seems to be small. I need to implement the pie-chart drawing based on availability of space by that pie-chart looks good irrespective of screen resolution.

![Screenshot from 2021-06-29 15-34-49](https://user-images.githubusercontent.com/71019344/123779251-9b58bf00-d8ef-11eb-9057-2d397a0eeaf7.png)

In the above snap we have lot of space around pie, that needs to be eliminated and pie size should have to increase.

I have used below lines of code:
` chart.radius = 50;
  chart.innerRadius = 35;
 // Responsive
            chart.responsive.enabled = true;
            chart.responsive.rules.push({
                relevant: function(target) {
                    if (target.pixelWidth <= 600) {
                        return true;
                    }
                    return false;
                },
                state: function(target, stateId) {
                    if (target instanceof am4charts.PieSeries) {
                        var state = target.states.create(stateId);
                        var labelState = target.labels.template.states.create(stateId);
                        labelState.properties.disabled = true;
                        var tickState = target.ticks.template.states.create(stateId);
                        tickState.properties.disabled = true;
                        return state;
                    }

                    return null;
                }
            });`

I tried for responsive chart but it's not reflected, So can you help and check out on how to implement that soon.

Thank you.

**Comment by xorspark** [comment]
You can use percent values for radius and inner radius instead of absolute pixel values.

```
chart.radius = am4core.percent(100);
chart.innerRadius = am4core.percent(70);
```

Adjust this as needed.

**Comment by meghanaNanuvala** [comment]
even i gave like that the pie is not resizing based on the availability of space

**Comment by meghanaNanuvala** [comment]
Thank you
