### ISSUE TITLE
Gantt chart display last date

### ISSUE THREAD

**Issue by manushakaru** [amcharts/amcharts4#3614]
**Question**
Is there a way to show the last date of a Gantt chart. Currently it ends at the beginning of the last date. I need to include the last date also. 
[CodePen ](https://codepen.io/manushakaru-the-selector/pen/XWRWyVJ)

![show last date](https://user-images.githubusercontent.com/36305124/123780964-5766b980-d8f1-11eb-9eab-b1bfa32762c1.png)

**Environment (if applicable)**
amcharts 4
Angular 11

**Additional context**

**Comment by zeroin** [comment]
You should do the following:
1) modify your data by adding hours, minutes and seconds, like:

```
"start": "2018-03-08 00:00:00",
"end": "2018-03-30 23:59:59",
```

2) set inputDateFormat, baseIterval and tooltipDateFormat:
```
categoryAxis.baseInterval = {count:1, timeUnit:"second"}
categoryAxis.tooltipDateFormat = "yyyy-MM-dd"
chart.dateFormatter.inputDateFormat = "yyyy-MM-dd HH:mm:ss"
```
https://codepen.io/team/amcharts/pen/7ed64e79a174c32e1a9a56e38b9d8f95

**Comment by manushakaru** [comment]
@zeroin Sorry for the delay reply. Thanks for you reply. My scenario is different because I use stacked axis chart and date format cannot be changed. However I used to solve it increasing the end date by one day. @martynasma  I think it is better to have an option to include or exclude the displaying last date.
