### ISSUE TITLE
How can I change only the valueAxis label using number format?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3615]
I want to format the Y axis to free a little bit of space for the chart like below:
- 1.000 > 1.0K
- 5.000.000 > 5.0M
- 5.000.000.000 > 5.0B

I did this using the following line, but the result is not exactly what I want:
`this.valueAxis.numberFormatter.numberFormat = '#a';`

![Screenshot from 2021-06-29 10-11-41](https://user-images.githubusercontent.com/48386738/123803361-9c272c00-d8c2-11eb-9dd6-ac414b0749d9.png)

As you can see, I was able to format de Y axis, but it changes the series tooltip format too. How can I change only the number format used in Y axis label?

Thanks for the help!

**Comment by xorspark** [comment]
By default, axes, tooltips, etc reference the same `NumberFormatter` instance that is defined at the chart level. If you only want the axis to have your number formatting, you need to create a separate instance of it with your desired settings:

```
valueAxis.numberFormatter = new am4core.NumberFormatter();
valueAxis.numberFormatter.numberFormat = '#a';
```

[Demo](https://codepen.io/team/amcharts/pen/ab763e958448bebbb9f641bb731b9e9b?editors=0010)
