### ISSUE TITLE
How to add real value display in Pie Chart label?

### ISSUE THREAD

**Issue by LouieTian0209** [amcharts/amcharts4#3617]
**Question**

For Pie Chart (Demo [here](https://www.amcharts.com/demos/pie-chart/)), the default label only shows category and value in percent, while the slices label shows category, value in percent as well as real value. How should I modify the code so that the label also shows real value in addition to what's already displayed, just like slice labels? I have tried `pieSeries.labels.template.tooltipText = "{category}: {value.percent.formatNumber('#.0')}% ({value})";` but it doesn't have any effect on the chart.

**Environment (if applicable)**

amCharts 4

**Comment by zeroin** [comment]
`pieSeries.labels.template.text = "{category}: {value.percent.formatNumber('#.#')}% ({value.value})"`
