### ISSUE TITLE
Disable chart from auto expand and auto shrink

### ISSUE THREAD

**Issue by manisha-seclogic** [amcharts/amcharts4#3618]
![image](https://user-images.githubusercontent.com/64947641/123916610-7a4fa700-d99f-11eb-83fe-bb3331976082.png)

  
![image](https://user-images.githubusercontent.com/64947641/123917242-327d4f80-d9a0-11eb-920e-4e08c09a24e2.png)

in both these images my graph is auto shrinking and expanding as per the screen size 
is there any way to stop this because I want to be set single for all screen

**Comment by zeroin** [comment]
You could simply set your div size in pixels, not in percent.

**Comment by manisha-seclogic** [comment]
then also the graph is expanding in small screen size because pixels will also increase in that case
is there any other way like min or max gap between 2 labels or custom category axis grid?

**Comment by zeroin** [comment]
Axis adjusts label count based on it's width. You can manipulate this using `dateAxis.renderer.minGridDistance = 100` setting

**Comment by manisha-seclogic** [comment]
This didn't help me in any of the screen size
I have created my own grid using below code and this helped me creating a static grid in across all screen sizes
 function createGrid(category) {
         var range = categoryAxisForY.axisRanges.create();
        range.category = category;
        range.label.text = "{category}";
        }
