### ISSUE TITLE
Stacked column diagram with pre-hidden elements

### ISSUE THREAD

**Issue by aktx** [amcharts/amcharts4#3621]
Hello! Could you help me fix that appearance? 
1. Hide 1 element by legend
2. Click "sort" button
3. Get empty stack gap

The third step is excess :DD
![wrong appearance](https://user-images.githubusercontent.com/21019996/124483455-081dfe80-ddb3-11eb-8e88-ea362f6693c9.png)

https://codepen.io/Aktxtka/pen/eYWJByg?editors=1111 - demo

**Comment by zeroin** [comment]
This can only be solved with the following workaround - after you invalidated data, add these lines:

```
  chart.events.once("datavalidated", ()=>{
    chart.series.each((series)=>{
      if(series.isHidden){
        series.hide(0)
      }
    })
  })```

**Comment by aktx** [comment]
```once``` method doesn't help, but if I change it to ```on``` this solves the issue. A new problem: if I deactivate animations, all columns are pre-hidden by default.

https://codepen.io/Aktxtka/pen/eYWJByg?editors=0011 - demo

**Comment by aktx** [comment]
That solves my problem. Thx!

**Comment by aktx** [comment]
That solves my problem, but now is all series is pre-hidden by default.
