### ISSUE TITLE
Change the bullet size (width and height)

### ISSUE THREAD

**Issue by aliuddin-growthRTS** [amcharts/amcharts4#3622]
**Bug description**
I have a problem in changing the bullet size in my chart (xy chart, line series)
so I do some testing with code below:

`
var chart = am4core.create("chartdiv", am4charts.XYChart);

// Add data
chart.data = [{
  "date": new Date(2018, 3, 20),
  "value": 90
}, {
  "date": new Date(2018, 3, 21),
  "value": 102
}, {
  "date": new Date(2018, 3, 22),
  "value": 65
}, {
  "date": new Date(2018, 3, 23),
  "value": 62
}, {
  "date": new Date(2018, 3, 24),
  "value": 55
}, {
  "date": new Date(2018, 3, 25),
  "value": 81
}];

// Create axes
var dateAxis = chart.xAxes.push(new am4charts.DateAxis());

// Create value axis
var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

// Create series
var lineSeries = chart.series.push(new am4charts.LineSeries());
lineSeries.dataFields.valueY = "value";
lineSeries.dataFields.dateX = "date";
lineSeries.name = "Sales";
lineSeries.strokeWidth = 3;

// Add simple bullet
var bullet = lineSeries.bullets.push(new am4charts.Bullet());
var square = bullet.createChild(am4core.Rectangle);
square.horizontalCenter = "middle";
square.verticalCenter = "middle";

// Add outline to the square bullet
square.stroke = am4core.color("#2F4858");
square.strokeWidth = 1;

// Make square drop shadow by adding a DropShadow filter
var shadow = new am4core.DropShadowFilter();
shadow.dx = 2;
shadow.dy = 2;
square.filters.push(shadow);

// Make chart not mask the bullets
chart.maskBullets = false;

//this code is working
square.width = 10;
square.height = 10;

//but this code here is not working
function resizeBullet(){
square.width = 20;
square.height = 20;
}

`
when the function resizeBullet is execute, it will not resize the button. 

So is this a bug or my way in resizing the bullet that was wrong?

**Comment by xorspark** [comment]
Bullet objects are templates so the values set on the property will work when you first initialize the object before the object creates its clones for each of your data points. Any changes to the template will not propagate to the clones that are created post initialization unless you set [`applyOnClones`](https://www.amcharts.com/docs/v4/reference/rectangle/#applyOnClones_property) to true:

```
square.applyOnClones = true; 
```

Your resizeBullet method will work once this is enabled.

[Codepen](https://codepen.io/team/amcharts/pen/4210c291b80e73e0a1caefc19a18de13?editors=1010)
