### ISSUE TITLE
How to add gradient fill for the range?

### ISSUE THREAD

**Issue by constzaytsev** [amcharts/amcharts4#3623]
Adding LinearGradient to the range doesn't work properly. It works on simple objects but not ranges.

CodePen: [https://codepen.io/constzaytsev/pen/JjNXxRR](https://codepen.io/constzaytsev/pen/JjNXxRR)

Are there any options?

**Comment by xorspark** [comment]
You need to set a `fillOpacity` on the range for the gradient to appear:

```
range.contents.fillOpacity = .5;
```

[Updated codepen](https://codepen.io/team/amcharts/pen/2010aa3860502510e6dedd5c5cae9d2a?editors=0010)
