### ISSUE TITLE
Format ValueAxis label with superscript?

### ISSUE THREAD

**Issue by jsodeman** [amcharts/amcharts4#3624]
**Question**

I'd like to have the % symbol in a ValueAxis label display as a superscript as in the image below. (I got the column tooltip one working already)

![2021-07-07_21-05-00](https://user-images.githubusercontent.com/2388842/124846558-14e35380-df67-11eb-94d8-64a977e74fdf.png)

Because the ValueAxis uses the NumberFormatter I can't use the superscript techniques that are available for the string formatter.

I'm wondering if I can add a container to the AxisLabel, but I'm not sure how to find the proper place/way to do that. If I can add a `tspan` to the `text` element of the label then I should be able to do what I need to. I'd appreciate a point in the right direction, thank you.

**Comment by martynasma** [comment]
How about just using an adapter to modify output of labels?

```JavaScript
valueAxis.renderer.labels.template.adapter.add("textOutput", function(text) {
  return text + "[baseline-shift: super]%[/]";
});
```

**Comment by jsodeman** [comment]
Thanks! I'd tried an adapter for "text" which didn't work but "textOutput" worked great.
