### ISSUE TITLE
PanX charts when press left arrow, rightarrow

### ISSUE THREAD

**Issue by BeamKunGzMARK** [amcharts/amcharts4#3626]
**Question**
If I want Charts can panX when press leftarrow or rightarrow same with Tradingview

**Environment (if applicable)**

**Additional context**
amCharts version : 4

I use ValueAxis and DateAxis

**Comment by martynasma** [comment]
There is no such built-in functionality.

You can implement it with custom code, by assigning keyup events to document and using DateAxis' zoom functions to set zoom.

I don't have a demo, but this tutorial might help with the API part:

https://www.amcharts.com/docs/v4/tutorials/zooming-axis-via-api-or-external-scrollbar/#DateAxis
