### ISSUE TITLE
Box plot candle alignment issue  

### ISSUE THREAD

**Issue by manushakaru** [amcharts/amcharts4#3627]
**Question**
I was trying to draw Box plot which consist of different series. However, candle's horizontal alignment is differ from series to series. Also I need to change the Box width as in the Box plot chart [demo](https://www.amcharts.com/demos/box-plot-chart/) not like a candle. Not that each series is create using different data objects. Example Codepen is [here](https://codepen.io/manushakaru-the-selector/pen/mdmEGJd?editors=1111) . Highly appreciate your valuable feedbacks. 

![box issue](https://user-images.githubusercontent.com/36305124/125045049-36088900-e0ba-11eb-8299-bae0bcc4a93b.PNG)

**Environment (if applicable)**
Amcharts 4 

**Additional context**

**Comment by martynasma** [comment]
Try disabling clustering on your CandlestickSeries:

```
series.clustered = false;
```

**Comment by manushakaru** [comment]
@martynasma Great. It solved the issue. Thanks for your quick reply.
