### ISSUE TITLE
Column labels as categories

### ISSUE THREAD

**Issue by TomRed97** [amcharts/amcharts4#3628]
Hello.

I found this example [https://www.amcharts.com/docs/v4/tutorials/column-labels-as-categories/](url), but we need that feature without enabling chart.maskBullets. Is there any solution to do this without setting true chart.maskBullets?

**Comment by martynasma** [comment]
That particular solution requires `maskBullets = false`.

If you have just one series, you could use adapters to override category labels. If there are multiple clustered series, then I don't have an alternative solution for you :(

**Comment by TomRed97** [comment]
Thank you for your quick answer.
