### ISSUE TITLE
Rtl Legend Problem

### ISSUE THREAD

**Issue by thevilx** [amcharts/amcharts4#3629]
Hi, I have enabled `chart.rtl = true;` and this happened :
![Capture](https://user-images.githubusercontent.com/80054917/125069176-a4a21280-e0cb-11eb-80a0-6ef89c23519a.PNG)
Any Idea how can I fix this? tried docs nothin found .

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
