### ISSUE TITLE
am4charts gauge two color hand

### ISSUE THREAD

**Issue by TheLaGmAn** [amcharts/amcharts4#3630]
**Question**

Hi, im creating a gauge, pretty much this example
https://www.amcharts.com/docs/v4/tutorials/customizing-clockhand/
But i cant find a way to create a two-color hand (not gradient, want 50% one color, 50% a second color without gradient), i can only pass a gradient as the fill of the hand.

Any tips on how to do this?

**Comment by martynasma** [comment]
You can have a perfect two-color fill using offsets in gradient:

```JavaScript
var gradient = new am4core.LinearGradient();
gradient.addColor(am4core.color("red"), 1, 0);
gradient.addColor(am4core.color("red"), 1, 0.5);
gradient.addColor(am4core.color("blue"), 1, 0.5);
gradient.addColor(am4core.color("blue"), 1, 1);
hand.hand.fill = gradient;
```
