### ISSUE TITLE
am4charts gauge circle tip

### ISSUE THREAD

**Issue by TheLaGmAn** [amcharts/amcharts4#3631]
Hi, im creating a gauge, pretty much this example
https://www.amcharts.com/docs/v4/tutorials/customizing-clockhand/

But i cant find a way to replace the tip triangle with a Circle, if i added a type of am4Core.Circle its detected as if im trying to change the pin and not the tip, and i cant modify the triangle to add a circle on it.

Any tips on how to do this?

**Comment by martynasma** [comment]
Just tried it. This does it for me:

```JavaScript
var tip = hand.createChild(am4core.Circle);
tip.radius = 10;
tip.horizontalCenter = "middle";
tip.x = am4core.percent(50);
```
