### ISSUE TITLE
Map related Graphs in iOS swift. 

### ISSUE THREAD

**Issue by chennaranganath965** [amcharts/amcharts4#3632]
How to implement map related graphs like Point Map, Choropleth Map and Bubble Map  in iOS swift language ?
If this library supports these graphs please provide any demo.

Thanks in Advance...!
![125055336-b2a06500-e0c4-11eb-812c-3124918bdb5e](https://user-images.githubusercontent.com/44457067/125234634-b4ee0380-e2fe-11eb-8eb1-99f29485c571.png)

**Comment by martynasma** [comment]
I'm afraid we do not have specific support for iOS Swift. Sorry.

**Comment by Ranga321** [comment]
Thanks for response 🙂
