### ISSUE TITLE
Add items to start of dataset without invalidating data 

### ISSUE THREAD

**Issue by saidziani** [amcharts/amcharts4#3633]
Hi, I am implementing a line chart that receives more data from an api when you click on a button. In the Amcharts V4 documentation it was really easy to find a way to push data to the end of the dataset just by using  `addData(rawDataItem: Object | Object[], removeCount?: number)`.

However, if I want to add data to the start of my dataset (from the left), I did not find a convenient solution without invalidating the data (by using `chart.invalidateData()`), which causes a redraw of the chart, and makes the scrollbar series disappear as well!

Please, do you have any method to add data to the start of dataset smoothly without refreshing the whole chart?

**Comment by martynasma** [comment]
> Please, do you have any method to add data to the start of dataset smoothly without refreshing the whole chart?

There's currently no way to add data to the beginning of the data set incrementally. Sorry.

**Comment by saidziani** [comment]
Hi, again please. Is it somewhere in your roadmap to implement this feature or we shouldn't count on it and move on with something else? Thanks in advance @martynasma

**Comment by martynasma** [comment]
I'm afraid, we are not planning on adding this feature for amCharts 4.

It will be in the next major version - amCharts 5 - currently in development. It won't be an upgrade. It will be a totally new charting lib, with no backwards compatibility to v4 code. ¯\_(ツ)_/¯

**Comment by saidziani** [comment]
Thank you @martynasma
