### ISSUE TITLE
How can I do to positioning label on path of LineSeries without restricts width?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3635]
I have a chart that has an absolute line series with a label:
![Screenshot from 2021-07-12 08-17-34](https://user-images.githubusercontent.com/48386738/125280418-66833980-e2eb-11eb-8d87-67f1d9fce6a2.png)

This chart can be resized and in some cases the label could get cut:
![Screenshot from 2021-07-12 08-17-57](https://user-images.githubusercontent.com/48386738/125280575-93cfe780-e2eb-11eb-9d37-ce93aa557522.png)

I want a way to avoid the behavior above: I need to put the label at center of LineSeries path without limiting the label width.

See how I do to positioning the label: 
```ts
this.growthRateLineSeries.events.on(
      'ready',
      () => {
        const label = this.growthRateLineSeries.createChild(am4core.Label);
        label.strokeOpacity = 0;
        label.fontSize = 12;
        label.fill = this.growthRateLineSeries.stroke;
        label.fillOpacity = 1;
        label.truncate = true;
        label.width = 200;
        label.padding(0, 0, 10, 0);
        label.text = `
          ${this._translateService.instant('DASHBOARD.CHART_TYPES.EVOLUTION.CHART_LABELS.GROWTH_RATE')}:
          ${growthRate ? `${growthRate.toFixed(2)}%` : 'N/A'}
        `;
        label.textAlign = 'middle';

        this.growthRateLineSeries.segments.getIndex(0).strokeSprite.events.on('propertychanged', (event) => {
          if (event.property === 'path') {
            label.path = this.growthRateLineSeries.segments.getIndex(0).strokeSprite.path;
            label.locationOnPath = 0.5;
          }
        });
      },
      1000
    );
```

It's pretty identical what a found at amcharts blog: https://www.amcharts.com/putting-labels-on-a-path-bending-circular-labels-and-more-in-amcharts-4-1-2/

Thank you!

**Comment by martynasma** [comment]
Maybe you can try disabling mask on the line series:

```JavaScript
this.growthRateLineSeries.mainContainer.mask = undefined;
```

**Comment by gagigante** [comment]
It does not work form me :(

**Comment by gagigante** [comment]
I am trying to use containers. Do you have any idea? @martynasma

**Comment by gagigante** [comment]
There is a way to positioning a tooltip at middle of a LineSeries?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by gagigante** [comment]
Sure! Here is a example with the problem [codepen](https://codepen.io/renangasperi/pen/QWvRNxv)

**Comment by martynasma** [comment]
Thank you.

The issue is not with amCharts but rather with SVG rendering system.

When you set `path` on a text, it follows the curve. If the curve is shorter than text, text is cut off.

I don't think using `path` will work in your case.

If your line is always horizontal, maybe you can just add Label to `chart.plotContainer` and position it in some other way?

```JavaScript
const point = am4core.utils.spritePointToSvg({x: 0, y: 0}, growthRateLineSeries);
label.x = point.x;
label.y = point.y;
```
