### ISSUE TITLE
Date axis: How to auto rotate labels?

### ISSUE THREAD

**Issue by git-ashish** [amcharts/amcharts4#3637]
I am following the [auto rotate axis labels example](https://www.amcharts.com/docs/v4/tutorials/wrapping-and-truncating-axis-labels/#Auto_rotating_labels) for the category axis but the same doesn't seem to be working for a Date axis. How can this be achieved?

[Here is a Codepen](https://codepen.io/git-ashish/pen/ExmWNWe) where the technique from the Category axis example has been applied but it doesn't seem to be working.

![image](https://user-images.githubusercontent.com/2697421/125749089-08cf07bc-649b-4f78-8829-7fe5283b7d0a.png)

Could you please suggest the correct way to achieve auto rotating labels for the date axis labels?

Thanks!

**Comment by martynasma** [comment]
`DateAxis` does not set `maxWidth` for its labels like `CategoryAxis` does, so you may need to just hardocde some breakpoint:

```JavaScript
dateAxis.events.on("sizechanged", function (ev) {
  var axis = ev.target;
  var cellWidth = axis.pixelWidth / (axis.endIndex - axis.startIndex);
  if (cellWidth < 50) {
    axis.renderer.labels.template.rotation = -45;
    axis.renderer.labels.template.horizontalCenter = "right";
    axis.renderer.labels.template.verticalCenter = "middle";
  } else {
    axis.renderer.labels.template.rotation = 0;
    axis.renderer.labels.template.horizontalCenter = "middle";
    axis.renderer.labels.template.verticalCenter = "top";
  }
});
```

**Comment by git-ashish** [comment]
Ah, okay. Thanks for the quick response!
