### ISSUE TITLE
Series bullets color in series range

### ISSUE THREAD

**Issue by DavidAuger** [amcharts/amcharts4#3638]
Hi all, Hi @martynasma ,

We have built a tool to help users to analyse a part of one of our charts (displaying then maximum, minimum values of data points in the selected section).
To visualize the selected section, we use some series ranges to "hash" series.

It works perfectly well on series stroke, fill with pattern and strokeDashArray, but not on series' bullets point:
![image](https://user-images.githubusercontent.com/48203813/125760397-f7cd8070-d9c6-41b3-ac96-8261aac8b73f.png)

I used your demo to reproduce this issue. I modified this: https://www.amcharts.com/demos/range-chart-with-different-fill-colors/ to have something similar to what we have. So for once, i do have a stackblitz for you :)
https://jsfiddle.net/AugerDav/sd1o5Lrb/3/

We wonder if it is possible to change bullets' color in series ranges, to make it grey as the series pattern ?
If so, what is the right property to do so ? (we would like to keep those series bullet points)

Thanks for your help
Best regards,
David

**Comment by martynasma** [comment]
Well, ranges do not affect bullets. I suppose the only way would be to add an adapter on those bullets to modify their coloring dynamically.

Something like this:

```JavaScript
bullet.adapter.add("stroke", function(stroke, target) {
console.log(target.dataItem.dateX)
	if ((target.dataItem.dateX < new Date(2020, 0, 6)) || (target.dataItem.dateX > new Date(2020, 0, 23))) {
		return am4core.color('#d9d9d9');
  } else {
		return stroke;
	}
})
```

Does that make sense?

**Comment by DavidAuger** [comment]
Hello Martynasma,

Thanks for your response.

I tried your suggestion, changing a bit if condition and it works quiet well in the demo:
![image](https://user-images.githubusercontent.com/48203813/126123489-fdb70912-9c01-43ab-82d6-7325c1ae4fd4.png)

`
  var bullet = series.bullets.push(new am4charts.CircleBullet());
  bullet.fill = new am4core.InterfaceColorSet().getFor("background");
  bullet.fillOpacity = 1;
  bullet.strokeWidth = 2;
  bullet.circle.radius = 3;
  
  bullet.adapter.add("stroke", function(stroke, target) {
	  let s1DataItem = target.dataItem;
	  var s2DataItem = series2.dataItems.getIndex(s1DataItem.index);
	  console.log(target.dataItem.dateX);
    if (s2DataItem.valueY > s1DataItem.valueY) {
      return am4core.color('#d9d9d9');
    }
    else {
      return stroke;
    }
  })
`

Although, i may have still questions. Mainly, i am wondering if it's the best way to link series stroke's color and bullets' color (because it is deeply what we are trying to do: 'grey' when series is shaded and stroke's color otherwise). Because as you can see we need to have the same condition twice: on in this adapter and the other to shade series using axis ranges.
I find it a bit complicated, is there no better practice ?

I was also surprised by a point. As you can read, i kept a console.log() to follow my dataItems and discovered that i had each twice (2 loops of full list to be precise). Is that a common process ?
I mean, as we added a single adapter on "bullet" (and none on "bullet2"), i was expecting it to run function once. What is the reason for this second occurrence ?

**Comment by martynasma** [comment]
Adapter is run whenever property is requested from the object. So it seems that it is being requested twice by some process. No way around it.

As for other approaches, you can add bullet color in data, then assign via propertyFields:

```
bullet.circle.propertyFields.stroke = "bulletColor";
```

**Comment by DavidAuger** [comment]
Hello Martynasma,

We tried the solution using `bullet.adapter` but we didn't succeed to produce the result we expected.
It is mainly my fault, so i just produce a new stackblitz to explain a bit more precisely our needs.

So here is the new stackblitz: https://jsfiddle.net/AugerDav/e8xga9nc/38/ 

Our `series ranges` can be moved and dynamically placed, by dragging the blue bullet (or even an input, but it's quiet similar to bullet drag).
So users can, and will, move ranges from this initial position:
![image](https://user-images.githubusercontent.com/48203813/126755246-c0097294-62df-4f8d-8627-21b8c70c4e35.png)
To this new position (for exemple):
![image](https://user-images.githubusercontent.com/48203813/126755198-fe30d08b-9676-4c57-ae4b-3c3a66d16bf5.png)

As you can see, `bullet.adaptater` works perfectly fine for initial positions (on left of inferior ranges), but as soon as we move ranges they don't change bullets' color.

I can assume that it is because property is not requested any more after initialization, as you explained me above. Is there a way to "reset" property and so force a run of adapter, on each drag event ?

On the contrary of this exemple, we also have some fill color in our bullets, what is the right way to shade it to ?

**Comment by martynasma** [comment]
Well, you moving a range, does not invalidate the bullets which would cause it to redraw.

I suppose you might invalidate them manually:

```
bullet.clones.each((clone) => {
  clone.circle.invalidate();
});
```

You can also create an adapter for `fill` property, just like for `stroke`.

**Comment by DavidAuger** [comment]
Hello Martynasma,

Sorry for the delay.
Unfortunately, i did some tests and was not able to either reach expected behaviour, either use your code correctly.

Here is the thing i understood and what i got:
![image](https://user-images.githubusercontent.com/48203813/130804038-d56629a0-dd30-4e8d-85ae-3fe3fb785336.png)

**Comment by martynasma** [comment]
Indeed. This should work though:

```
bullet.clones.each(function(clone) {
  clone.stroke = clone.stroke;
});
```

When you request `stroke`, adapter is applied anew.

**Comment by DavidAuger** [comment]
Ok indeed, we (almost) got it !! :)

I still observe a strange behavior when i drag "back" (ie forward then backward):
![image](https://user-images.githubusercontent.com/48203813/130831642-9cc7a6ec-0cbb-4f19-923c-ddeb2619a94f.png)

I do understood the case, but not really how to avoid it.
It comes from ```stroke``` bullets adapter, in ```else { return stroke; } ```. If i change and set a specific color, it works fine with the exact same manipulation/scenario:
![image](https://user-images.githubusercontent.com/48203813/130832131-17fca327-fd24-48b1-b30e-143bf384042f.png)

Does ```stroke``` parameter need to be set in this adapter function ?
Is it not supposed to be equal to value we set using configuration line ```series.stroke = am4core.color("#1b7cb3");``` ?
