### ISSUE TITLE
Question about installing AmCharts

### ISSUE THREAD

**Issue by ying5207** [amcharts/amcharts4#3639]
Hi all, I'm a new user without programming knowledge. I have a question about installing AmCharts, hope you can help.
After I key in below commands (Install via NPM) in Windows power shell, what should I do to open the map edit page, or AmCharts software? Should I download TypeScript or JavaScript edit the map?
npm install @amcharts/amcharts4
npm install @amcharts/amcharts4-geodata
npm install @amcharts/amcharts4-fonts

Or should I copy and paste the above commands in TypeScript?

Thanks!

**Comment by martynasma** [comment]
Hi there,

amCharts is a programming library. I'm afraid you will need programming knowledge to use it ;)

It's not something you can run and use as a regular application.

**Comment by ying5207** [comment]
> Hi there,
> 
> amCharts is a programming library. I'm afraid you will need programming knowledge to use it ;)
> 
> It's not something you can run and use as a regular application.

Hi, thanks for your reply.
It is required knowledge of JavaScript?

**Comment by martynasma** [comment]
> It is required knowledge of JavaScript?

Yes.

**Comment by ying5207** [comment]
> > It is required knowledge of JavaScript?
> 
> Yes.

Thanks for reply :)
