### ISSUE TITLE
IndalidateData makes scrollbar series disappear

### ISSUE THREAD

**Issue by saidziani** [amcharts/amcharts4#3640]
Hi, working on implementing a line series, which needs data to be added dynamically to the start of the dataset, the only available solution is push to dataset and then invalidate data again which is working great. 

The only problem here is once invalidation is done, the series inside scrollbar is disappearing! 

Is there any solution foe this please?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by saidziani** [comment]
Hi @martynasma, 
This codepen shows the issue that I am facing https://codepen.io/saidziani/pen/YzVVPYL?editors=1010. try to click on "add data" you'll see the scrollbar disappearing just after invalidating the data.

Thanks in advance.

**Comment by martynasma** [comment]
Thanks.

Try invalidating data for the scrollbar chart, too:

```
chart.scrollbarX.scrollbarChart.invalidateData();
```

**Comment by saidziani** [comment]
Thanks a lot @martynasma that solves the issue (y)
