### ISSUE TITLE
Set the minimum size of a node in a chord diagram

### ISSUE THREAD

**Issue by oneill479** [amcharts/amcharts4#3641]
![Screenshot from 2021-07-16 10-06-02](https://user-images.githubusercontent.com/32404468/125981327-72ecdd9e-b94e-47f4-9d9d-242ec92bba90.png)

If you can see in this photo if there are no links coming out of a node it is resized to a very small size. Is there a way to set the minimum size of a node to keep it from becoming so small?

**Comment by martynasma** [comment]
> If you can see in this photo if there are no links coming out of a node it is resized to a very small size. Is there a way to set the minimum size of a node to keep it from becoming so small?

No, I'm afraid.

**Comment by oneill479** [comment]
> > If you can see in this photo if there are no links coming out of a node it is resized to a very small size. Is there a way to set the minimum size of a node to keep it from becoming so small?
> 
> No, I'm afraid.
Thank you!

**Comment by oneill479** [comment]
> > If you can see in this photo if there are no links coming out of a node it is resized to a very small size. Is there a way to set the minimum size of a node to keep it from becoming so small?
> 
> No, I'm afraid.

Thanks!
