### ISSUE TITLE
Adding Children to MapChart removes map (JSON config)

### ISSUE THREAD

**Issue by ChazUK** [amcharts/amcharts4#3644]
I've been trying to setup a MapChart using the JSON config and have found an issue when adding the `children` property removes the map

https://codepen.io/ChazUK/pen/jOmLrJz

Lines 310 - 322 is the children object, commenting that out and adding it via JS fixes the issue, but I'm trying to have a full JSON config approach.

I checked https://github.com/amcharts/amcharts4/issues/3199 and added the `forceCreate` property but it's still appearing blank

**Comment by martynasma** [comment]
It looks like you modified the CodePen some, which does not have the code that was causing issues anymore.

Did you find a workaround? If you still interested in resolving this, can you bring back the old code back? I can't seem to be able to reproduce it from memory anymore :)
