### ISSUE TITLE
Click & Drag on the map while the map is still moving causes subsequent drag not to work.

### ISSUE THREAD

**Issue by Andrew1431** [amcharts/amcharts4#3648]
**Bug description**

Beginning to drag the map while it's momentum is still dampening results in the drag action being ignored until you release the mouse, causing the map to feel entirely unresponsive if dragging around quickly. Happens on every map in every example.

https://codepen.io/team/amcharts/pen/RBaBBL

**Environment (if applicable)**

Happening to me on chrome, haven't tested elsewhere.

**Additional context**

**Comment by martynasma** [comment]
This can be resolved by disabling inertia:

```
chart.seriesContainer.inert = false;
```

Hope you find it acceptable.

**Comment by Andrew1431** [comment]
Very, thank you!
