### ISSUE TITLE
There is a way to avoid label overlap?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3649]
I have a pareto chart and in some cases the value labels overlaps
![Screenshot from 2021-07-21 15-40-09](https://user-images.githubusercontent.com/48386738/126542369-b5eb6946-9370-4f33-99d8-776cb567a226.png)

How can I avoid this behavior?

**Comment by martynasma** [comment]
No, I'm afraid :(

The chart does not check for bullet overlapping in any way.

**Comment by gagigante** [comment]
Ok, thanks!
