### ISSUE TITLE
Unable to Capture "Hit" Events from XY Cursor  - XY Line Chart

### ISSUE THREAD

**Issue by venigallapraveen** [amcharts/amcharts4#3650]
**Bug description**

Hey there,
I'm trying to capture cursor events from the XY Line Chart. However, I'm unable to capture any click events from the cursor. I'm using the following code to capture click events from the cursor: 
```
chart.cursor.interactionsEnabled = true;

 chart.cursor.events.on("hit", function (ev) {
    console.log("event received from cursor", ev)
    });
```

I also created a CodePen example that verifies this bug.
CodePen (https://codepen.io/venigallapraveen/pen/oNWGGqo)
Note that nothing happens when we click on the chart. Nothing's logged to the console

**Environment (if applicable)**
Amcharts v4.10.13
React v17.0.0

I would appreciate it if you could please look into this issue. 

Thanks,

**Comment by martynasma** [comment]
Cursor is not something to be clicked on. It does not have any "body".

Perhaps you need to catch hit events on a plot container?

```
chart.plotContainer.events.on("hit", ....);
```

**Comment by venigallapraveen** [comment]
Thanks that worked!
