### ISSUE TITLE
Showing percentages instead of numbers in tooltip for Multipleseries tooltip

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3651]
I have to show a percentages instead of number in tooltip for multiseries tooltip.
 [Here is my Code](https://codepen.io/vineelak/pen/YzVrxaG?editors=1010)

![Screenshot from 2021-07-22 14-14-44](https://user-images.githubusercontent.com/74599304/126612513-f0707fe4-6922-46ba-bf2f-c8102dee9bc3.png)

Like above I don't want to show numbers instead I have to show percentage of it.

**Comment by martynasma** [comment]
Can you clarify something: percentage of what?

**Comment by VineelaKantamneni** [comment]
Percentage of that series contribution at that point.
In above image enroll web contribution 62.5 % of total and call center agent contibution 36.5% and remaining 0%.
Like that we have to display

**Comment by martynasma** [comment]
Thanks.

Something like this should do the trick:

```JavaScript
series.adapter.add("tooltipText", function(ev) {
  var text = "[bold]{categoryX}[/]\n"
  chart.series.each(function(item) {
    if (!item.isHidden) {
      var percent = item.tooltipDataItem.values.valueY.totalPercent;
      var percentText = percent ? percent + "%" : "";
      text += "[" + item.stroke.hex + "]●[/] " + item.name + ": " + percentText + "\n";
    }
  });
  return text;
});
```

**Comment by VineelaKantamneni** [comment]
It's working...Thank you so much.

**Comment by VineelaKantamneni** [comment]
![Screenshot from 2021-07-23 19-13-38](https://user-images.githubusercontent.com/74599304/126790955-6c7d7cab-f9b5-4fcf-8a14-4e886e6c4bae.png)
When two points of different series are at sameplace it's showing tooltip twice

**Comment by martynasma** [comment]
You can sent `maxTooltipDistance = -1`

**Comment by VineelaKantamneni** [comment]
Thank you.
