### ISSUE TITLE
There are some option to avoid label overlapping in a pie chart?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3652]
I have a PieChart with label and in some cases the label is overlaped. How can I solve this?

![Screenshot from 2021-07-22 16-31-57](https://user-images.githubusercontent.com/48386738/126698739-18a02186-c9ae-4de8-be8d-1802e91dcf03.png)

**Comment by martynasma** [comment]
Maybe you should just hide labels for very small slices.

https://www.amcharts.com/docs/v4/tutorials/hiding-small-pie-slices/#Hiding_labels
