### ISSUE TITLE
Documentation issue: Polygon (area) series

### ISSUE THREAD

**Issue by gregsadetsky** [amcharts/amcharts4#3653]
The first example under

https://www.amcharts.com/docs/v4/chart-types/map/#Creating_polygon_series

reads:

```js
let polygonSeries = new am4maps.MapPolygonSeries();
map.series.push(series);
```

That should instead be

```js
let polygonSeries = new am4maps.MapPolygonSeries();
map.series.push(polygonSeries);
```

i.e. the `polygonSeries` variable should be passed to the `map.series` array, rather than the non-existent `series` one. Thank you!

**Comment by martynasma** [comment]
Thanks for the heads up! Fixed.
