### ISSUE TITLE
Xlsx dependency contains vulnerability

### ISSUE THREAD

**Issue by m3taphysics** [amcharts/amcharts4#3654]
Version 4.10.20 of AMCharts contains a dependency for package xlsx which contains a vulnerability. Upgrading to > 0.17.0 solves this issue. Could we upgrade this? Our build steps rely on not having vulnerabilities.

https://github.com/amcharts/amcharts4/blob/master/package.json

**Comment by martynasma** [comment]
Duplicate: #3643
