### ISSUE TITLE
npm audit: CVE in  xlsx

### ISSUE THREAD

**Issue by SymbioticKilla** [amcharts/amcharts4#3655]
Moderate        Denial of Service                                                                                                         
  Package         xlsx                                            
  Patched in      >=0.17.0                                         
  Dependency of   @amcharts/amcharts4              
  Path            @amcharts/amcharts4 > xlsx           
  More info       https://npmjs.com/advisories/1767

Can you please update dependency?
"xlsx": "^0.16.4" to "xlsx": "^0.17.0"

Thank you!

**Comment by zapalagrzegorz** [comment]
https://github.com/amcharts/amcharts4/issues/3643

**Comment by SymbioticKilla** [comment]
Oups! Sorry, haven't found it due misspelling perhaps...
