### ISSUE TITLE
XYChartScrollbar series not updating when using invalidateRawData

### ISSUE THREAD

**Issue by mlomb** [amcharts/amcharts4#3656]
**Bug description**

Updating the data inplace and calling `invalidateRawData` doesn't update the scrollbar series.

**Sample**

Demo: https://codepen.io/mlomb/pen/zYwPdWb
This is the [Line Chart with Scroll and Zoom](https://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/) demo with the following addition:
```js
setInterval(() => {
  for(var i = 0; i < chartData.length; i++) {
    chartData[i].visits = Math.random() * 1000;
  }
  chart.invalidateRawData();
}, 1000);
```

**Comment by xorspark** [comment]
You can call `invalidateRawData` on the `scrollbarChart` to update it too:

```
chart.scrollbarX.scrollbarChart.invalidateRawData();
```

I defer to the devs on whether this is intentional or not.
