### ISSUE TITLE
How I can achieve such design with ColumnSeries3D

### ISSUE THREAD

**Issue by QaiserAbbas** [amcharts/amcharts4#3659]
How I can achieve such design with ColumnSeries3D

Simply need to rotate bars and add some nice effects here. 

<img width="159" alt="Screenshot 2021-07-26 at 1 59 13 PM" src="https://user-images.githubusercontent.com/20537558/126963235-308f0a6e-9a3b-4767-8abf-21279b7c1550.png">

**Comment by martynasma** [comment]
Not, possible. Sorry :(

**Comment by QaiserAbbas** [comment]
> Not, possible. Sorry :(

Can we just rotate the columns like this one? so one corner must be in the center.

**Comment by martynasma** [comment]
Nope, it doesn't work like this.
