### ISSUE TITLE
Event for when tooltip is not shown

### ISSUE THREAD

**Issue by daxidngyn** [amcharts/amcharts4#3660]
I am familiar with the tooltipshownat event, but is there an event or any logic for when the tooltip is not showing anymore?

**Comment by martynasma** [comment]
Yes:

```JavaScript
tooltip.events.on("hidden", function(ev) {
  console.log("bye bye tooltip");
});
```

**Comment by daxidngyn** [comment]
While that works, the event is also sometimes activating when the tooltip doesn't disappear, such as scrolling through a large change in data like in the image attached.
![issue JPG](https://user-images.githubusercontent.com/68628068/127064175-7d23d558-d6be-4e13-b9cd-dbdd33416228.png)
