### ISSUE TITLE
Axis change problem

### ISSUE THREAD

**Issue by ifoba** [amcharts/amcharts4#3661]
Hello, I am having problems when changing the axis of the series.
I prepared an example in which the value axis expands to full screen, thereby shifting the graph.

This bug occurs only at certain values, unfortunately I could not identify any dependency.
To reproduce the problem, change the value axis in the example.

[Example](https://codesandbox.io/s/dynamic-axis-change-styd2?file=/src/components/Chart.vue)

**Comment by ifoba** [comment]
Can I get a solution to this problem?

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
