### ISSUE TITLE
Reducing the gap between the legends and values uniformly?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3662]
Hi 
I need a uniform space between the legends and values of pie-chart.

i have used below line but it's not reflecting same if i use more than one chart.
![Screenshot from 2021-07-27 20-16-32](https://user-images.githubusercontent.com/71019344/127175764-71cc8ffe-1ebf-4c10-be77-557f96bc94b0.png)

`            chart.legend.valueLabels.template.marginLeft = 80;
`

in that pic it is different don't what is the reason behind that, can you suggest me better way to set the uniform space between them.

Thanks in advance.

**Comment by martynasma** [comment]
Do you mean uniform gap between label and value label of each item in legend or that legends are the same width on multiple charts?

**Comment by meghanaNanuvala** [comment]
Having same width on multiple charts

**Comment by meghanaNanuvala** [comment]
yeah that's fine
