### ISSUE TITLE
Not getting tooltip pointer if i move the tooltip above the axis

### ISSUE THREAD

**Issue by abhiseksubham** [amcharts/amcharts4#3663]
https://codepen.io/Abhiseksubham/pen/rNmprBO

I have moved the tootip above the chart, but the tooltip pointer is not coming after that.

I have tried the tooltip pointer orientation = "down" as well , but its not working as such.

**Comment by martynasma** [comment]
Try combination of these settings:

```JavaScript
tooltip.ignoreBounds = true;
tooltip.boundingContainer = undefined;
```

**Comment by abhiseksubham** [comment]
this works thanks!
