### ISSUE TITLE
Bullets not showing on Force Directed Tree?

### ISSUE THREAD

**Issue by MarcoAbi** [amcharts/amcharts4#3664]
I'm trying to reproduce something similar to this demo [https://www.amcharts.com/demos/chord-diagram-with-animated-bullets/](url) (in which bullets are animated into a Chord Diagram) but using a Force Directed Tree.

however bullets are not showing up and I don't understand where is the problem.
Here a JSFiddle with the non-working example:

https://jsfiddle.net/d36hfg2z/

Do you have some ideas on how to achieve this?

Thanks!!

**Comment by martynasma** [comment]
ForceDirectedTree does not support bullets on their links, I'm afraid. Sorry.

**Comment by MarcoAbi** [comment]
I see. :(

Thanks a lot anyway!!
