### ISSUE TITLE
I got [Object object] when tooltipHTML using adapter

### ISSUE THREAD

**Issue by golch** [amcharts/amcharts4#3666]
**Bug description**

bug : got [Object object] on tooltipHTML.
expected : String

I think there's a bug when using for loop like below.

`      bullet.adapter.add("tooltipHTML", (text, target) => {
        let categoryX = "New (Yang)";

        let returnValue = "";
        for (let i = 0; i < 3; i++) {
          returnValue += `<div style="color:red">{${categoryX}} : {valueY.value}</div>`
        }

        return returnValue;
      });
`

I only tested ")" for end of the string value. that return [Object object] instead of String value.

**Environment (if applicable)**

amcharts version : 4.10.5
vuejs : 2.6.12
browser : chrome 91.0.4472.114
os : macos

**Additional context**

attached my amchartTest.vue file's full source codes for better understanding.

`<template>
  <div :id="id" style="height:600px;"></div>
</template>

<script>
import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";
import am4themes_animated from "@amcharts/amcharts4/themes/animated";

export default {
  name: "amchartTest.vue",
  props: {
      id: String,
  },
  methods: {
    init() {
      /* Chart code */
      // Themes begin
      am4core.useTheme(am4themes_animated);
      // Themes end

      // Create chart instance
      let chart = am4core.create("chartdiv", am4charts.XYChart);

      // Export
      chart.exporting.menu = new am4core.ExportMenu();

      // Data for both series
      let data = [{
        "New (Yang)": "2009",
        "income": 23.5,
        "expenses": 21.1
      }, {
        "New (Yang)": "2010",
        "income": 26.2,
        "expenses": 30.5
      }, {
        "New (Yang)": "2011",
        "income": 30.1,
        "expenses": 34.9
      }, {
        "New (Yang)": "2012",
        "income": 29.5,
        "expenses": 31.1
      }, {
        "New (Yang)": "2013",
        "income": 30.6,
        "expenses": 28.2,
        "lineDash": "5,5",
      }, {
        "New (Yang)": "2014",
        "income": 34.1,
        "expenses": 32.9,
        "strokeWidth": 1,
        "columnDash": "5,5",
        "fillOpacity": 0.2,
        "additional": "(projection)"
      }];

      /* Create axes */
      let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
      categoryAxis.dataFields.category = "New (Yang)";
      categoryAxis.renderer.minGridDistance = 30;

      /* Create value axis */
      let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

      /* Create series */
      let columnSeries = chart.series.push(new am4charts.ColumnSeries());
      columnSeries.name = "Income";
      columnSeries.dataFields.valueY = "income";
      columnSeries.dataFields.categoryX = "New (Yang)";

      columnSeries.columns.template.tooltipText = "[#fff font-size: 15px]{name} in {categoryX}:\n[/][#fff font-size: 20px]{valueY}[/] [#fff]{additional}[/]"
      columnSeries.columns.template.propertyFields.fillOpacity = "fillOpacity";
      columnSeries.columns.template.propertyFields.stroke = "stroke";
      columnSeries.columns.template.propertyFields.strokeWidth = "strokeWidth";
      columnSeries.columns.template.propertyFields.strokeDasharray = "columnDash";
      columnSeries.tooltip.label.textAlign = "middle";

      let lineSeries = chart.series.push(new am4charts.LineSeries());
      lineSeries.name = "Expenses";
      lineSeries.dataFields.valueY = "expenses";
      lineSeries.dataFields.categoryX = "New (Yang)";

      lineSeries.stroke = am4core.color("#fdd400");
      lineSeries.strokeWidth = 3;
      lineSeries.propertyFields.strokeDasharray = "lineDash";
      lineSeries.tooltip.label.textAlign = "middle";

      let bullet = lineSeries.bullets.push(new am4charts.Bullet());
      bullet.fill = am4core.color("#fdd400"); // tooltips grab fill from parent by default
      // bullet.tooltipText = "[#fff font-size: 15px]{name} in {categoryX}:\n[/][#fff font-size: 20px]{valueY}[/] [#fff]{additional}[/]";
      bullet.adapter.add("tooltipHTML", (text, target) => {
        let categoryX = "New (Yang)";

        let returnValue = "";
        for (let i = 0; i < 3; i++) {
          returnValue += `<div style="color:red">{${categoryX}} : {valueY.value}</div>`
        }

        return returnValue;
      });

      let circle = bullet.createChild(am4core.Circle);
      circle.radius = 4;
      circle.fill = am4core.color("#fff");
      circle.strokeWidth = 3;

      chart.data = data;

    },
  },
  mounted() {
    this.init();
  }
};
</script>
`

**Comment by martynasma** [comment]
amCharts 4 does not support round brackets in data placeholders, because those are reserved for in-line formatting functions. There's no way around it other than renaming your fields in data to not have brackets.

**Comment by golch** [comment]
Thank you for your quick response!
Is there a document which contains that knowledge?

**Comment by martynasma** [comment]
Come to think of it, no :O

Just added this:
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Limitations
