### ISSUE TITLE
AmCharts TrendLines Chart : dateFormatter isint working on chart or any of axis

### ISSUE THREAD

**Issue by abhiseksubham** [amcharts/amcharts4#3667]
**Bug description**

 I want a date format like this :

![Screenshot 2021-07-30 at 6 41 32 PM](https://user-images.githubusercontent.com/2356647/127657910-79df298c-6849-4a2b-9679-0ac9dc438f05.png)

basically it should be a MM/DD format

CodePen: https://codepen.io/Abhiseksubham/pen/jOmxGNV

I have tried following but no change in date.
chart.dateFormatter.dateFormat = "M/d/yyyy";
chart.dateFormatter.dateFormat = "MM/dd";

or even this doesn't work:
dateAxis.dateFormatter.dateFormat = "MM/dd";

**Comment by abhiseksubham** [comment]
I did find a way with dateAxis.dateFormats.setKey("day", "MM/dd");
As shown here:
https://codepen.io/Abhiseksubham/pen/abWGLJR

But the first label isn't formatted here.

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Period_change_format
