### ISSUE TITLE
How to connect candlestick

### ISSUE THREAD

**Issue by BeamKunGzMARK** [amcharts/amcharts4#3669]
**Question**

I have a question about charts 

How do connect the candlestick if the data none have the data at that time that so How I connect 2 candlestick

**Additional context**
![image](https://user-images.githubusercontent.com/39422342/127966624-a696134f-e8e0-4945-a255-206f76dd5546.png)

**Comment by martynasma** [comment]
Try this:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Removing_empty_time_units

**Comment by BeamKunGzMARK** [comment]
or It already connect but I use margin of candlestick then it can use with doesn't connect that?

**Comment by martynasma** [comment]
I'm not entirely sure I understand what you mean.

Do you perhaps have your chart online, or can post on CodePen?

**Comment by BeamKunGzMARK** [comment]
Can you see it in website ? 
https://bkccharts.com/#MVP

CodePen : https://codepen.io/BeamKunGzMARk/project/editor/AwyBmm#

it dosen't connect 

![image](https://user-images.githubusercontent.com/39422342/129468332-4da8ec16-9958-451a-8b70-a0491496edc5.png)

**Comment by martynasma** [comment]
I'm afraid I don't see any "disconnects" in CodePen or the live site you gave link for.

That being said, even if it's happening like you described in some cases, we won't be able to provide a fix. `skipEmptyPeriods` is a workaroundish experimental feature, we're not prepared to dedicated a lot of time to.

I suggest you use regular `CategoryAxis` instead.
