### ISSUE TITLE
Duplicate tooltip when zoom in

### ISSUE THREAD

**Issue by judithzv** [amcharts/amcharts4#3671]
Hello,

I have a fixed tooltip shown in my graph. The problem is when I zoom in, the tooltip is shown both in the old and the new position, generating duplicate tooltips in the graph. 

I have the last version of amcharts4, it is suposed to be solved with the property hideTooltipWhileZooming but still happening. Any idea?

Thank you.
![image](https://user-images.githubusercontent.com/47140392/128037521-d55efc19-36d0-4962-892b-6a14a34986c5.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
