### ISSUE TITLE
How to cache chart / How to use cacheItem

### ISSUE THREAD

**Issue by pratikbidkar** [amcharts/amcharts4#3673]
In document they have mentioned about cacheItem. But how to use that cacheitem is not mentioned. Can anyone tell me?

**Comment by martynasma** [comment]
Cache is an internal tool used by amCharts 4 engine. Please disregard it.

**Comment by pratikbidkar** [comment]
But how to use it?

**Comment by martynasma** [comment]
As I wrote in my previous reply, it's not meant to be used. It's an internal tool.
