### ISSUE TITLE
Increasing Memory Usage when series.removeIndex().dispose()

### ISSUE THREAD

**Issue by Fortunate-87** [amcharts/amcharts4#3674]
**Bug description**

I have a XYchart that i want to reuse, for that i need to dynamically add and remove the series.
Following the instructions (https://www.amcharts.com/docs/v4/tutorials/dynamically-adding-and-removing-series/ ) the app memory usage is increasing continously (more than 4GB) and the tab eventually freezes, when i simply used `chart.series.removeIndex(chart.series.length-1).dispose();` multiple times.

For me deleting every key (typeof === 'object') of the series object freed most of the used memory. I first tried to delete them without timeout/promise after disposing, but the removeIndex() function call chain complained about missing properties. So i used a timeout, which worked, and finally i changed it to a promise resolve call.

For finding the memory "leak" i created a test page.
https://plnkr.co/edit/2kDKQhgbFGowS7PA
The function removeSeries() will dispose the last series in list chart.series.
I created a few switch cases, for easier testing.
Cases 'all-keys' and 'object' prevent increasing memory usage. Cases 'no-keys', 'docu', 'null' and 'seperate' all show increased memory usage.

The webpage has several buttons:
"Series > Plus" appends a new Series
"Series > Minus" removes the last Series
"Series > MinusPlus" calls "Series > Minus" and then "Series > Minus"
"Timer > Plus" sets the setInterval call with "Series > MinusPlus" in an intervall of 1500ms
"Timer > Minus" cancels the previous Timer

Tor testing the memory usage, click the "Series > MinusPlus" Button to first remove the last series and create a new one afterwards. To automate this click you can click the "Timer > Plus" button, which will call the function on an intervall every 1500ms. The "Timer > Minus" Button will remove the setInterval call.

**Steps to reproduce**
1. Create XYChart.
2. Create LineSeries.
3. Remove LineSeries with series.removeIndex().dispose()

Repeat Step 2 to 3 and watch the memory Usage in TaskManager.

**Environment (if applicable)**
amCharts version 4.10.20
Firefox 90.0.2 (64-Bit)

**Additional context**

Memory Usage for three cases 'no-keys', 'all-keys', 'object' over approximately two minutes
![grafik](https://user-images.githubusercontent.com/88091557/128178606-c188874d-5988-4f8a-8a28-12297f2f1975.png)

Im aware removing a series every 1,5s is not a Setting one often encounters, but it shows the problem. My dashboard app uses multiple charts with multiple series and switching the dashboard view to another one does show the increased memory usage.
I also had to get rid of all series properties when the chart needs to be disposed to free most of the used memory. The memory usage still increases a little bit, but that is okay.

Maybe i'm using the chart or series wrong, but i followed the am4charts tutorial and in my app it worked, until i tried to remove the series with the mentioned line of code.

Sidenode:
Is there a way to let the chart update its valueAxis range automatically when data is added, so the minus in the upper right corner doesnt appear?

**Comment by martynasma** [comment]
Have you tried not calling `dispose()`? Normally, removing series from `series` list should automatically dispose it, so maybe your additional call is interfering with the process.

**Comment by Fortunate-87** [comment]
No i didnt try it before. After your suggestion i added the case 'no-dispose' in the plnkr, which does only call removeIndex() on the series List, no saving of the returnvalue. Same Memory behavior.
```
case 'no-dispose': {
    series.removeIndex(series.length - 1); //.dispose();
}
```

**Comment by Fortunate-87** [comment]
No i didnt try that before. After your suggestion i added the case 'no-dispose' in the plnkr, no saving of return value. Still continuously increasing memory usage.
```
case 'no-dispose': {
    series.removeIndex(series.length - 1); //.dispose();
}
```

**Comment by martynasma** [comment]
With "no-dispose" method, are you still seeing the issue of browser memory consumption going to the point where it becomes unresponsive?

I tried your updated demo, indeed the memory keeps increasing for a while because old series objects are in memory, even if they are disposed.

However, after a while browser's GC kicks in and starts clearing up unused stuff, so memory usage actually drops.

While there's no way to force GC on a browser, if you have an update-heavy chart, you may consider using your object clearing method like you described.

Another option to consider is: not disposing series, but rather reusing it, by changing it settings, and/or data, etc.

**Comment by Fortunate-87** [comment]
I did a "longer test" with the "no-dispose" memory, the tab starts at around 260mb Memory and rises to over 6GB after 5 minutes. The Tab does indeed not freeze, but the chart does not update anymore, i expect that to be a operating system problem, because memory usage is near 100%.

We considered reusing the chart and also the series in our application. But that will be another lesson to learn for me while time is short. I will stick with the workaround for now, until i will refactor the application or a fix is provided.
