### ISSUE TITLE
Custom DateAxis tooltip text

### ISSUE THREAD

**Issue by alessandrovir** [amcharts/amcharts4#3675]
Hi all,

I am implementing a linear chart with a `DateAxis` on the x-axis and a `ValueAxis` on y-axis.

Values on X are mapped with iso strings, i'm using `(new Date('2020-01-01')).toIsoString()` to generate the values.

It works well if my data have daily / monthly / yearly granularity (the user can change this granularity trough the UI).
If the data comes with a standard granularity all works fine.

But I need some custom granularities, such as weeks / quarters / semesters etc.

Graph works fine if I have 4 points in a month (the 4 weeks), mapped as 4 days in the month. F.e. the first day of the week. The behaviour with respect daily granularity is the same, but i have only four point in a month.

The same if i am working with Quarters. I have 4 points in the year, every point is identified by the first day on the first month of the quarter (f.e. 2020-01-01, 2020-04-01, 2020-07-01, 2020-10-01). This works as a default month granularity. I see 4 points in a year etc.

In both cases what is wrong is the label inside the tooltip. In the first case i have the day but i need to show the week number (Jan week 1, Jan week 2, Jan week 3...) and in the second case i have the months (Jan, Apr, Jul, Oct) while i need some thing like (2020 Q1, 2020 Q2, 2020 Q3...).
In this case, i was able to extract the Quarter number with `dateAxis.dateFormats.setKey("month", "q");` and then fixing the text with an adapter the return me in the callback the Quarter number
`dateAxis.adapter.add("getTooltipText", function(text, target, key) {
 return "Q" + text;
});`

It works but i dont' have the year info, but this way is not suitable for week granularity. 

With my current implementation I am able to compute from the outside which is the expected tooltip text, and i can bind it to a custom key inside the chart data array.

I am struggling trying to "insert" this text inside the tooltip. I am trying to do something like this 

https://codepen.io/team/amcharts/pen/jOqNreJ

but with a DateAxis (here there is a CategoryAxis)

I tried also something like this 
https://www.amcharts.com/docs/v4/concepts/adapters/#Adding_adapters 
but the target.dataItem inside the adapater callback is undefined

Any ideas? 

Thank you

-----
Amcharts v4.10.15
Angular v.12.1.3
Typescript v4.3.5

**Comment by xorspark** [comment]
You can use the `tooltipDate` property in your getTooltipText adapter's target to get the Date object associated with the tooltip.

```
dateAxis.adapter.add("getTooltipText", function(text, target) {
  if (target.tooltipDate) {
    return chart.dateFormatter.format(target.tooltipDate, "'Q'q yyyy")
  }
  return text;
});
```

[Codepen](https://codepen.io/team/amcharts/pen/5b210d9c9a448eeb6f1dbe541a93cecc?editors=0010)

**Comment by alessandrovir** [comment]
Thank you for the suggestion! 
This method works only to translate date in ISO formats. For example day, month, quarter, year but i can not translate a day into its relative week number of the year, unless i define an external function to compute the week number from the tooltipDate, but this is not a viable solution since this value can not be right. 
For my specific case the value to be inserted inside the tooltip comes from the api, together with the value of the series (y value) and the date (x value).
 Let's say:

```
const myPoint = {
    x_value: Wed Jan 01 2020 00:00:00 GMT+0100,
    y_value: 100,
    tooltip_value: "My custom tooltip"
}
```
Is there any method to get the dataContext of the point that i am overing? 
I want to create a graph that actually works with a date axis but with a custom tooltip on the x axis.

Thank you

**Comment by xorspark** [comment]
Apologies for the delay, this slipped through the cracks.

I'm not sure what you mean that it only works in ISO date formats; tooltipDate is always a Date object representation of the hovered part of the axis as the axis uses Date objects behind the scenes. We also have [a variety of formatting codes](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-date-time/#Format_codes), including week number:

```
  chart.dateFormatter.format(target.tooltipDate, "w") // Year week number 
  chart.dateFormatter.format(target.tooltipDate, "W") // Month week number
```

As for looking up the series data item, you can use the axis' `getSeriesDataItem` method and pass in a series object and the axis position, which you can convert from the cursor position like so:

```
  var dataItem = dateAxis.getSeriesDataItem(chart.series.getIndex(0), dateAxis.toAxisPosition(chart.cursor.xPosition), true);
```

[Updated codepen](https://codepen.io/team/amcharts/pen/db1209b35fbea15a70a5cf002409b29d?editors=0010)

**Comment by alessandrovir** [comment]
Thank you very much! 

`var dataItem = dateAxis.getSeriesDataItem(chart.series.getIndex(0), dateAxis.toAxisPosition(chart.cursor.xPosition), true);`

This is the solution I was looking for!
