### ISSUE TITLE
How to give Height, overflow and cornerRadius in series tooltip

### ISSUE THREAD

**Issue by abdurrehman-alphasquad** [amcharts/amcharts4#3676]

**Comment by martynasma** [comment]
Text tooltips are not scrollbable.

You will need to use `tooltipHTML` then provide content in HTML.

Contents of the HTML-based tooltip are subject to CSS, so you can set max-height, overflow, and other styles there.

**Comment by abdurrehman-alphasquad** [comment]
> Text tooltips are not scrollbable.
> 
> You will need to use `tooltipHTML` then provide content in HTML.
> 
> Contents of the HTML-based tooltip are subject to CSS, so you can set max-height, overflow, and other styles there.

thanku so much for your response @martynasma
