### ISSUE TITLE
Treemap amCharts 4

### ISSUE THREAD

**Issue by DynaSourcerousRex** [amcharts/amcharts4#3677]
**Question**

Hi friends. 

I know that treemaps are meant to determine the size of the parent element by calculating the sum of its children. My question is, what if the sum of children for each parent adds up to the same value - eg, I have categories of defects where you can drill down into more specific areas that the defects subdivide into. The 'value' used is percentage, and so every parent's children will add up to 100%. I cannot use another value as the percentage (eg 'number of defects') because each main category does not have the same amount of possible defects (so if i use 'number of defects' the one block completely overpowers the whole graph).

I am asking because at this point I'm seeing behaviour where a block that has the value of '0.03%' is bigger than one with '1.18%' (I know these are quite small numbers, but the behaviour happens everywhere, this one is just an easy one to demonstrate). I've redacted some labels for work reasons etc etc. 

I've attached a screenshot of the mentioned parent blocks (each with their value as shown on the block labels) and after that, a screenshot of what happens when I drill into each parent (to show it adds up to 100%). Notice the child with 2 children has the same problem as mentioned before where 88.89% gets as much space as 11.11%.

NOTE: The final (lowest)level of the treemap works perfectly, I am guessing because it is taking the percentage values I am passing to it, and so block size and percentage match up. 

<img width="511" alt="Screen Shot 2021-08-06 at 12 48 15 PM" src="https://user-images.githubusercontent.com/4215613/128552138-5d715ef2-b947-4100-a27c-9639c12b90bc.png">

<img width="1532" alt="Screen Shot 2021-08-06 at 12 49 39 PM" src="https://user-images.githubusercontent.com/4215613/128552171-65dfd314-bfcd-4da6-a38c-60c8d1cd441a.png">

<img width="1528" alt="Screen Shot 2021-08-06 at 12 50 16 PM" src="https://user-images.githubusercontent.com/4215613/128552176-cd1c7537-531a-40df-a98f-442501887d5f.png">

Thanks

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
There's no other way for Treemap to size nodes other that sum of all values for its children.

In your case, I would use "number of defects" as a value data field so that nodes are sized correctly.

To avoid abnormally small/large nodes, you could recalculate those using logarithmic scale, e.g. in data instead of value use log():

```
{
  name: "Category X",
  value: 1000,
  logValue: Math.log(1000),
  percent: "0.1%"
}
```

Use `logValue` as an actual value data field.

Use `percent` for labels only.

Hope that makes sense.

**Comment by DynaSourcerousRex** [comment]
That makes a ton of sense! Thanks so much. I just wanted to check something, and I've been scouring the docs to try see how to make this happen, but how do I add in the Log calculation on the fly? Eg, the JSON object I'm dealing with looks something like this:

```
"category": "Category X",
        "name": "Name",
        "id": "ID",
        "defects": 80,
        "percentageOfTotalDefects" : 6.25,
        "totalDefects": 1280,
        "nodes": [
        {
            "category": "Category X 1 ",
            etc etc
```

The way I am using it in the treemap is like this:

```
        chart.dataFields.value = "defects";
        chart.dataFields.name = "name";
        chart.dataFields.children = "nodes";
```
I am not finding a way to add the Math.log to that chart.dataFields.value field. I've seen in the docs that on other charts you can set a valueAxis to logarithmic = true, but the treemap does not have axes created explicitly (neither does it look like one has do that).  I also tried to look for some function that can pre process values before adding them to the chart (eg in TreeMapDataItem i found a function setValue(name: string, value: number, duration?: number, delay?: number ) but not sure what to add to the 'value' part of that function. I'm creating each level like this (here is the second level code):
```

// ### SECOND LEVEL ###
        var level2 = chart.seriesTemplates.create("1");

        let level2_column = level2.columns.template;
        level2_column.column.cornerRadius(3);
        level2_column.fillOpacity = 0.8;
        level2_column.stroke = am4core.color("#fff");
        level2_column.strokeWidth = 2;
        level2_column.strokeOpacity = 1;
        level2_column.tooltipText = "{name} : [bold]{percentageOfDefects}[/]%";

        var level2_bullet = level2.bullets.push(new am4charts.LabelBullet());
        level2_bullet.locationY = 0.5;
        level2_bullet.locationX = 0.5;
        level2_bullet.label.text = "{name} : [bold]{percentageOfDefects}[/]%";
        level2_bullet.label.fill = am4core.color("#000");

```
Another option is to iterate over the entire object (pretty large) and change each node's value (or adding an extra field like you suggest that contains the logValue) before giving it to the chart but that is a lot of extra processing each time the chart loads.  Is there a better way to do this than changing the json object?

**Comment by martynasma** [comment]
There's no other way than to iterate through the data and add Math.log() calculations, I'm afraid.

**Comment by DynaSourcerousRex** [comment]
Alright thanks a lot, I appreciate your time :)
