### ISSUE TITLE
How do you hide labeles that have value of 0 percent in Legend?

### ISSUE THREAD

**Issue by roia-cf** [amcharts/amcharts4#3678]
Hey,
in my PieChart's Legend I have like 12 different lables with unique colored markers, it's getting a little tight so I just wanna filter out the legend items that have the value 0 percent.
Is there a way maybe to loop through the items in the Legend to check which one got the value of 0 percent and just hide it? Or any other soltuion?

Thank you in advance.

**Comment by martynasma** [comment]
Maybe just set `ignoreZeroValues = true` for your `PieSeries`?

https://www.amcharts.com/docs/v4/reference/pieseries/#ignoreZeroValues_property

**Comment by roia-cf** [comment]
Hey @martynasma, thank you for the quick reply!

All it does is not show the zero values in my PieChart itself, but the legened still has the labels with zero value showing.

**Comment by martynasma** [comment]
Hm, indeed.

How about using `dataFields.hiddenInLegend`?

Example:
https://codepen.io/team/amcharts/pen/6b15377a4a5aa7229436e13f662a0ffb?editors=0010

**Comment by roia-cf** [comment]
You're a legend @martynasma(pun indeed intended), it worked!

Thank you (:
