### ISSUE TITLE
Image (png) export from UI vs selenium web driver downloads different images

### ISSUE THREAD

**Issue by madhura-utterwise** [amcharts/amcharts4#3679]
Image (png) export from UI vs selenium web driver downloads different images

I have plotted a 3d cylinder bar chart. Please refer to the codepen link below: 
https://codepen.io/madhura2212/pen/ZEKoBJx

When I export png using the Export menu from UI, the generated image looks exactly like the chart.

I want to export the same chart's image it server side. I have refered to the official documentation: https://www.amcharts.com/docs/v4/tutorials/automating-report-generation-using-selenium-webdriver/

I could export the image as png, but the image is very different than what is generated from UI.

Please find the difference below

![image](https://user-images.githubusercontent.com/83704271/128701153-b3583c76-2611-4138-a460-ac4dc5956943.png)

The chart code is exactly same. If it is useful, generated PDF using selenium webdriver also generates similar incorrect image in it.

Am I missing something?

**Environment (if applicable)**

 - amCharts 4

**Comment by martynasma** [comment]
Have you tried using different browser driver in Selenium?

https://www.selenium.dev/documentation/getting_started/installing_browser_drivers/
