### ISSUE TITLE
Change ForceDirectedTree fontSize based on zoom level?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts4#3680]
Hi there,

Hope this wasn't covered in the docs and I just completely missed it...
I'm working on a `ForceDirectedTree` that is `zoomable`, and when I zoom, the `fontSize` of the labels stay the same; is there anyway to adjust the `fontSize` of labels based on the zoom level?

Thank you!

**Comment by martynasma** [comment]
You can disable `nonScaling` on node labels so that labels scale together with the node when zooming:

```JavaScript
networkSeries.nodes.template.label.nonScaling = false;
```

**Comment by jonofoz** [comment]
@martynasma Perfect, thank you!
