### ISSUE TITLE
How to set legend values close to right?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3683]
Hi

I have been working on pie-charts, 
![Screenshot from 2021-08-11 10-47-17](https://user-images.githubusercontent.com/71019344/128973512-3e95238b-33c6-411b-9910-b46cf241b2f5.png)
in the above picture, i have applied legend width where legend values were closer to legend.
But i want the legend values has to be right most like below ones.
![Screenshot from 2021-08-11 10-49-44](https://user-images.githubusercontent.com/71019344/128973714-58e135fb-8655-494d-aaa4-35ba005001e2.png)

How can i set the legend values to be placed in right position. Is there a way to set those to right most within the legend width.
I'm attaching an demo of this, Can you help me out.
[demo](https://codepen.io/meghanananuvala/pen/VwpgBEj?editors=0010)

Thanks in advance.

**Comment by martynasma** [comment]
Your legend is aligned right to the edge in your demo:

![image](https://user-images.githubusercontent.com/1458520/129062661-ea5969b0-b989-46d2-b2f8-888ca1efa74c.png)

Am I missing something?

**Comment by meghanaNanuvala** [comment]
Can you kindly go through that and get me back what is the solution for that.

**Comment by martynasma** [comment]
The only way to right-align the whole legend when its `width` is set, is like this:

```
chart.legend.contentAlign = "right";
```
