### ISSUE TITLE
Is it possible to represent series as 'day' on date axis as 'time'

### ISSUE THREAD

**Issue by igoriok1994** [amcharts/amcharts4#3685]
It's hard to explain, but I'll try :)

Eg I have data from 2021-08-09 00:00:00 to 2021-08-12 23:00:00. I want to see on DATE axis only time (00:00:00 - 23:59:59). Then each line graph will represent a day (from 2021-08-09 to 2021-08-12)

This is how it can be visualized (data from 6 a.m. to 11p.m. for each day):
Also hover tooltips on separate graph displays this graphs DATETIME
![image](https://user-images.githubusercontent.com/37294916/129170141-22e48421-dcae-45f2-a23b-cd5af0d87f2b.png)

Is it possible to create similar chart with amCharts4?

**Comment by martynasma** [comment]
Yes:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Formatting_date_and_time

**Comment by igoriok1994** [comment]
Sorry, after setting dateFormat everything works fine.
This can be closed.
