### ISSUE TITLE
Theme color set

### ISSUE THREAD

**Issue by TomRed97** [amcharts/amcharts4#3686]
Dears Hello.
I need your help.
We want to check the accessibility of our colors, but we need also your themes' color sets for choosing special colors for our system. So how we can get your all themes' color set lists?

Thank you.

**Comment by martynasma** [comment]
I'm not entirely sure I understand your question.

Our default ColorSet does not have a pre-defined color list, it generates colors on the fly as needed:
https://www.amcharts.com/docs/v4/concepts/colors/#Color_sets

I guess if you need to get a list of colors a color set would generate if needed, you can do so like this:

```
console.log(chart.colors.list);
```

If you need more than default 20 colors, you can force generating more:

```
chart.colors.generate(100);
```

Hope this helps.

**Comment by TomRed97** [comment]
Thank you very much. We will use themes in that case.
