### ISSUE TITLE
Reduce space between 2 Bullet charts: Don't want container to take any space

### ISSUE THREAD

**Issue by abhiseksubham** [amcharts/amcharts4#3688]
Hi I have a requirement to build rows of bullet charts without space, around 40px of space only. 

![Screenshot 2021-08-12 at 9 13 11 PM](https://user-images.githubusercontent.com/2356647/129227963-02df06a2-4247-48c9-acc4-d60a75d01a74.png)

When i go ahead and actually build it, even if i give it 25px space, it ends up taking some space for the padding and the actual chart is rendered only in 11 px something. 

![Screenshot 2021-08-12 at 9 14 01 PM](https://user-images.githubusercontent.com/2356647/129227989-5caea1f2-4892-4f5f-bc06-61e1b9014cc1.png)

I want to remove the extra padding and have chart rendered in the entire container space.

I have a sample chart with only 1 bullet chart, but we might need 8 such bullet charts in [400px.]

Please let me Know how can we achieve this.

**Comment by martynasma** [comment]
You can remove padding on a chart like this:

```
chart.padding(0, 0, 0, 0);
```

**Comment by abhiseksubham** [comment]
this absolutely helps me.
