### ISSUE TITLE
Data is not rendering into XY

### ISSUE THREAD

**Issue by alienbuild** [amcharts/amcharts4#3689]
**Bug description**

Developing a sparkline based off of the example codepen, however replacing the data array of objects with data received from api causes a blank render. 

Original amcharts4 example:
https://codepen.io/team/amcharts/pen/JabepK

Updated with my own data:
https://codepen.io/lkfranklin/pen/dyWrZKV

**Environment**
 - amCharts 4
 - Chrome (Latest)
 - React

**Comment by martynasma** [comment]
You're missing something here ;)

![image](https://user-images.githubusercontent.com/1458520/129310921-fee57f1f-90ec-4605-911b-10c98738a299.png)

**Comment by alienbuild** [comment]
Hahah, thank you ;)
