### ISSUE TITLE
Display countries flag instead of colors (background-image) 

### ISSUE THREAD

**Issue by youssefbenfarhat** [amcharts/amcharts4#3691]
Can I display countries flag instead of colors (background-image) ?
 I'm creating a map and I want to display the flags of each county like this example https://image.shutterstock.com/image-vector/world-map-all-states-their-600w-377445283.jpg

**Comment by martynasma** [comment]
Yes, you can use patterns for that.

For more information refer to this tutorial:
https://www.amcharts.com/docs/v4/concepts/colors/#Patterns

And this demo:
https://www.amcharts.com/docs/v4/tutorials/pie-chart-with-patterned-slice-fills/

**Comment by youssefbenfarhat** [comment]
@martynasma   Can you give me an example please . I followed the two tutorials but I couldn't make it.

**Comment by martynasma** [comment]
OK:
https://codepen.io/team/amcharts/pen/2183742f63558f50d4f1d4b5a5aed36d?editors=0010

**Comment by youssefbenfarhat** [comment]
@martynasma  Thank you so much
