### ISSUE TITLE
Increasing size of ImafeSeries child

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#3692]
I am developing a map chart for our product and the page, where chart is placed, has two tabs. Choosing particular tab changes chart`s data. When i choose the first one everything is fine, then the second one - still okey, and if i return to the first one smth happends with circle sizes. It looks like a bug
![image](https://user-images.githubusercontent.com/18229211/129356917-65456655-1f25-4dde-851b-524ce1823dac.png)
![image](https://user-images.githubusercontent.com/18229211/129357043-21f77cd9-40bb-4322-b824-03af4ad506d0.png)

If i leave only one circle, everything is fine 
![image](https://user-images.githubusercontent.com/18229211/129357361-d33944ab-ab1c-4060-a55b-748285d2ca58.png)
And if i make chart reload every time i switch tabs - it will work okey too, but rerendering the whole chart every time takes too much time.  

**MapChart.tsx**
```
import * as React from 'react';
import { useLayoutEffect } from 'react';
import * as am4core from '@amcharts/amcharts4/core';
import * as am4maps from '@amcharts/amcharts4/maps';
import am4geodata_worldHigh from '@amcharts/amcharts4-geodata/worldLow';

type Data = {
    lon: number;
    lat: number;
    hint: string;
    radius?: number;
    count: number;
}[];
const MapChart: React.FC<{ id: string; data: Data; chartType: string }> = ({
    id,
    data = [],
    chartType
}) => {
    useLayoutEffect(() => {
        const chart = am4core.create(id, am4maps.MapChart);
        chart.geodata = am4geodata_worldHigh;
            chart.panBehavior = 'rotateLong';
          chart.projection = new am4maps.projections.Miller();

        const polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
        polygonSeries.exclude = ['AQ'];
        polygonSeries.useGeodata = true;
        const polygonTemplate = polygonSeries.mapPolygons.template;
        polygonTemplate.fill = am4core.color('#262626');
        polygonTemplate.stroke = am4core.color('#262626');

        const imageSeries = chart.series.push(new am4maps.MapImageSeries());
        imageSeries.data = data;
        imageSeries.mapImages.template.propertyFields.longitude = 'lon';
        imageSeries.mapImages.template.propertyFields.latitude = 'lat';
        // imageSeries.mapImages.template.tooltipText =
        //     '[bold #E3E3E5 line-height: 0.9]{count} [/] \n \n [#787C84]{hint}[/] ';
        // `[bold #E3E3E5 line-height: 0.9] {valueY} [/]\n[${color} font-size: 15px]●[/] [#E3E3E5]{name}[/]   \n[#787C84]{date.formatDate('dd MMM yyyy')}[/]\n`
        imageSeries.tooltip.getFillFromObject = false;
        imageSeries.tooltip.label.textAlign = 'middle';
        imageSeries.tooltip.background.strokeOpacity = 0;
        imageSeries.tooltip.background.fill = am4core.color('#262b39');
        imageSeries.tooltip.width = 53;
        imageSeries.tooltip.height = 40;

        const circle = imageSeries.mapImages.template.createChild(
            am4core.Circle
        );
        const circle2 = imageSeries.mapImages.template.createChild(
            am4core.Circle
        );
        circle.tooltipText =
            '[bold #E3E3E5 line-height: 0.9]{count} [/] \n \n [#787C84]{hint}[/] ';
        circle.propertyFields.radius = 'radius';
        // circle.radius = 5;
        circle.nonScaling = true;
        circle.fillOpacity = 0.6;
        circle.fill = am4core.color('#4154CF');
        circle.events.on('inited', event => {
            // animateBullet(event.target);
            event.target.zIndex = Number.MAX_VALUE;
            event.target.toFront();
        });
        circle.events.on('over', event => {
            // animateBullet(event.target);
            event.target.zIndex = Number.MAX_VALUE;
            event.target.toFront();
        });
        circle.nonScaling = true;
        // const label = chartType;

        circle2.fill = am4core.color('#4154CF');
        circle2.propertyFields.radius = 'radius';
        circle2.fillOpacity = 0.6;
        // circle2.radius = 5;
        // console.log(circle2);
        // circle2.nonScaling = true;
        //
        console.log(data);
        const animateBullet = circle => {
            const animation = circle.animate(
                [
                    { property: 'scale', from: 1, to: 4 },
                    { property: 'opacity', from: 0.6, to: 0 }
                ],
                1000,
                am4core.ease.linear
            );
            animation.events.on('animationended', event => {
                // console.log(event.target.object);
                animateBullet(event.target.object);
            });
        };
        circle2.events.on('inited', event => {
            animateBullet(event.target);
        });
        return () => {
            chart.dispose();
        };
    }, [id, data]);
    return <div id={id} style={{ width: '100%', height: '80vh' }} />;
};

export default MapChart;

```

**Chart usage snippet**
```
                  {this.chartStore.GeographyOfViolationsData[
                            this.store.tabType
                        ]?.length !== 0 && (
                            <>
                                <div
                                    style={{
                                        display:
                                            this.store.tabType === 'fraud'
                                                ? 'block'
                                                : 'none',
                                        opacity: this.store.isOpen[
                                            this.store.tabType
                                        ]
                                            ? 1
                                            : 0,
                                        transition: 'opacity 1s',
                                        width: '100%'
                                    }}
                                >
                                    <MapChart
                                        id={'GeographyOfViolationsFraud'}
                                        data={
                                            this.chartStore
                                                .GeographyOfViolationsData.fraud
                                        }
                                        chartType={this.store.tabType}
                                    />
                                </div>
                                <div
                                    style={{
                                        width: '100%',
                                        display:
                                            this.store.tabType === 'counterfeit'
                                                ? 'block'
                                                : 'none',
                                        opacity: this.store.isOpen[
                                            this.store.tabType
                                        ]
                                            ? 1
                                            : 0,
                                        transition: 'opacity 1s'
                                    }}
                                >
                                    <MapChart
                                        id={'GeographyOfViolationsCounterfeit'}
                                        data={
                                            this.chartStore
                                                .GeographyOfViolationsData
                                                .counterfeit
                                        }
                                        chartType={this.store.tabType}
                                    />
                                </div>
                            </>
                        )}
```

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by 12rita** [comment]
> Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

I tried to imitate described behavior, and somehow now circle sizes increases from the initial state without any toggling. But still: if i get rid of the second circle everything will be fine. 
[Diagram](https://codepen.io/12rita/pen/oNWRqzg)

**Comment by martynasma** [comment]
Thank you.

The issue with this is that your maps start hidden (`display: none`) and thus have no sizing.

When you unhide them, it scales everything, including the circle, hence it being so huge.

Solution would be for the chart not to start hidden.

If that's not possible, maybe you can initialize your MapImageSeries after you unhide the chart.

Finally, if you are using fixed width/height, or know dimensions of the chart, you can set it on it like this:

```
chart.minWidth = 400;
chart.minHeight = 400;
```

Any of those solutions should fix circle issues.

**Comment by 12rita** [comment]
> Thank you.
> 
> The issue with this is that your maps start hidden (`display: none`) and thus have no sizing.
> 
> When you unhide them, it scales everything, including the circle, hence it being so huge.
> 
> Solution would be for the chart not to start hidden.
> 
> If that's not possible, maybe you can initialize your MapImageSeries after you unhide the chart.
> 
> Finally, if you are using fixed width/height, or know dimensions of the chart, you can set it on it like this:
> 
> ```
> chart.minWidth = 400;
> chart.minHeight = 400;
> ```
> 
> Any of those solutions should fix circle issues.

Thank you for the explanations! I suppose, the last solution is the most suitable for my situation and circles really stay normal size after setting min height and width, but when i start to drag the map, the whole map scales anyway and doesn`t scale back even with the mouse rolling. I couldn't replicate this behavior on CodePen, but it looks like the same issue and maybe you know, how to fix it?

Normal state: 
![image](https://user-images.githubusercontent.com/18229211/129884452-d113fc48-bf77-4817-936f-92fb3aa38807.png)

After start dragging:
![image](https://user-images.githubusercontent.com/18229211/129884508-b80bb097-3106-4f5f-9985-77021c9db487.png)

**Comment by martynasma** [comment]
> I couldn't replicate this behavior on CodePen, but it looks like the same issue and maybe you know, how to fix it?

Unfortunately, no - we're not aware of this issue.

If you could replicate it somehow, that would help us in figuring it out.

**Comment by 12rita** [comment]
> > I couldn't replicate this behavior on CodePen, but it looks like the same issue and maybe you know, how to fix it?
> 
> Unfortunately, no - we're not aware of this issue.
> 
> If you could replicate it somehow, that would help us in figuring it out.

Still have no luck in repeting the bug on CodePen. Besides, the problem exist frim the very beginning - when drag is inited the map scales and even move out from the scene:
![image](https://user-images.githubusercontent.com/18229211/129891679-53acc109-714e-4f78-a908-53df3588b07f.png)

I noticed, that higher minWidth leads to smaller scaling of the map.
