### ISSUE TITLE
Multiple y valueAxis  - number format not working

### ISSUE THREAD

**Issue by Vmadmax** [amcharts/amcharts4#3693]
**Bug description**
Number formatter not working on each y-axis.

**Version**
4.10.21

I build the chart with the following code:
```javascript
....
"yAxes": [
    {
        "type": "ValueAxis",
        "id": "standard",
        "cursorTooltipEnabled": false,
        "renderer": {
            "grid": {
                "template": {
                    "stroke": am4core.color("#C7C7C7"),
                    "strokeDasharray": "3",
                }
            },
            "labels": {
                "template": {
                    "fill": am4core.color("#C7C7C7")
                }
            },
        },
        "title": {
            "text": '{{ __('Temperature') }}'
        },
        //"min": 0,
        "strictMinMax": true,
        "extraMin": 0.2,
        "extraMax": 0.2,
        "numberFormatter": {
            "numberFormat": "#.#'°C'",
        },
    },
    {
        "type": "ValueAxis",
        "id": "outside_temperature",
        "cursorTooltipEnabled": false,
        "title": {
            "text": '{{ __('Outside temperature') }}'
        },
        "renderer": {
            "opposite": true
        },
        "strictMinMax": true,
        "extraMin": 0.2,
        "extraMax": 0.2,
        "numberFormatter": {
            "numberFormat": "#.#' LL'",
        },
    }
],
...
```

Everything works fine, but the number formatter isn't working as expected. Both axis shows the same number format, see Screenshot. 
The left y-axis "Temperature" must shown `#.#'°C`
The right y-axis "Outside temperature" must shown `"#.#' LL'"`

What's wrong?

<img width="617" alt="Bildschirmfoto 2021-08-15 um 13 07 35" src="https://user-images.githubusercontent.com/1713226/129476410-913a5825-ce10-4553-a16f-a1a60de64f87.png">

**Comment by xorspark** [comment]
By default AmCharts reuses NumberFormatters and other types of objects where possible; in your case, you're modifying the chart instance's global NumberFormatter in your config twice where the `#.# ' LL '` format overwrote `#.#'°C`. To create new instances with their own unique configuration, you need to specify the `type` and set `forceCreate` to true to each numberFormatter object in your JSON:

```
    // add to each axis' numberFormatter:
    "numberFormatter": {
      "type": "NumberFormatter",
      "forceCreate": true,
      // etc
    }
```

This is explained in more detail here: https://www.amcharts.com/docs/v4/concepts/json-config/#Creating_or_reusing_

**Comment by Vmadmax** [comment]
@xorspark Thanks, it's working!
