### ISSUE TITLE
Primitives fails to honor percents during subsequent validation

### ISSUE THREAD

**Issue by labriola** [amcharts/amcharts4#3694]
**Bug description**

Primitive classes such as Line and Rect seem to internally consider only derived items such as x1 and x2 during validation, however, they allow the setting of percents for width, leading to weird resizing issues. This is somewhat mentioned in the docs where it indicates that width is not used in the rendering... however, it says percentWidth is and, to the best of my ability to trace the code, this is never considered in a validation phase.

Here is a reproduction case
https://codepen.io/labriola/pen/oNWOqyB?editors=0010

Ultimately, any ability to create an environment where the outermost container should resize but combinations of primitives (Line alone will replicate) will show the issue.

**Additional context**

Working on a few complex charting examples. This isn't the final use case, but this is the simplest reproduction case I could create without a lot of additional noise.

Note to reproduce, just resize the browser horizontally. Sometimes you will see the rectangles push off. Sometimes you can cause the lines to draw shorter than otherwise needed, etc.

**Comment by martynasma** [comment]
Unfortunately, it's a limitation of the rendering engine.

Implementing such relative sizing for lines would require a significant overhaul of the layout engine. At this point in life of amCharts 4, we're not able to start implementing such drastic changes, I'm afraid.

I hope you will find some other way to implement this.

Sorry.

**Comment by labriola** [comment]
Understood. Can you see any way that I could manually watch for a resize event and force a re-computation of the size of the line? I have tried a number of techniques to invalidate it, but since the rendering doesn't seem to take them into account it has not worked. Perhaps catch the parent before validation and just manually set the x1 and x2? (Not expecting you to debug this for me but thought that we could leave a clue for anyone else on this issue in case they face a similar problem)

**Comment by martynasma** [comment]
Yeah, I suppose you can watch the "resize" event on a chart or one of its containers:

```JavaScript
chart.events.on("resize", function(ev) {
  console.log(chart.pixelWidth, chart.pixelHeight);
});
```

**Comment by martynasma** [comment]
Sorry, my bad, event should be "sizechanged". Will update previous response.

**Comment by labriola** [comment]
Thanks. That might be the best short term solution as I am not sure how to go about re-architecting all of the custom charts we have created. thanks again
