### ISSUE TITLE
Columns are sticking to the right side

### ISSUE THREAD

**Issue by HouDinitz** [amcharts/amcharts4#3695]
Hi,
I have a problem when the number of columns is not a lot (less than 5), the graph columns are sticking to the right side of the graph.
Can someone think of the reason it is happening?

<img width="701" alt="Screen Shot 2021-08-16 at 2 17 15" src="https://user-images.githubusercontent.com/86915813/129495637-5ccfccfa-921a-4da6-b713-1f9167d46e95.png">

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by HouDinitz** [comment]
It was because of minZoomCount: 5
