### ISSUE TITLE
Set pattern for 3D column chart

### ISSUE THREAD

**Issue by qhuy729** [amcharts/amcharts4#3696]
**Question**

I want to set the pattern for the 3D column chart but look like it just covers only the front side
How to make it cover all

This is my sample
https://codepen.io/qhuy729/pen/YzVMJBX

and this is my purpose
https://i.imgur.com/IWwertd.png

Thanks,

**Comment by martynasma** [comment]
Technically, you can target each separate side for the 3D column like this:

```JavaScript
series.columns.template.column3D.sideRight;
series.columns.template.column3D.sideTop;
series.columns.template.column3D.sideLeft;
series.columns.template.column3D.sideBottom;
```

So can come up with specific settings for pattern fill, too:

```JavaScript
series.columns.template.column3D.sideRight.adapter.add("fill", function(fill, target) {
  var pattern = new am4core.LinePattern();
  pattern.width = 200;
  pattern.height = 200;
  pattern.strokeWidth = 1;
  pattern.y = -50;
  pattern.gap = 5;
  pattern.stroke = target.dataItem.dataContext.color;
  pattern.rotation = 60;
  return pattern;
});
```

**Comment by qhuy729** [comment]
@martynasma Thanks for your help
And I just want to apply a pattern for a specific column, the other column is still set by color
Is it possible?

In my sample it always apply pattern for all column

**Comment by martynasma** [comment]
You'll need to use `propertyFields` for that:
https://www.amcharts.com/docs/v4/concepts/data/#Property_fields
