### ISSUE TITLE
How to set width for each layer container within a SankeyDiagram chart?

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3697]
Hello,

I have the following rendered chart

![image](https://user-images.githubusercontent.com/40542072/129572712-db27f88b-79b7-4d7b-96af-ae1c8d8cef3d.png)

The issue is that everything is too cramped, is there any way to dictate am charts how to space out each vertical container? Also, would the box width be accessible when doing this? These boxes are set as `Rectangle` on top of `nodeLabel` (equivalent of `nodeTemplate.nameLabel.label`)

![image](https://user-images.githubusercontent.com/40542072/129573113-e7771826-5d5e-4aa8-ae9e-562af72906d9.png)

Thanks!

**Comment by martynasma** [comment]
Maybe this demo will help:
https://www.amcharts.com/docs/v4/tutorials/sankey-diagram-with-custom-node-widths-and-positions/
