### ISSUE TITLE
ie11 wont support resizeObserver

### ISSUE THREAD

**Issue by yuanyuanyuan** [amcharts/amcharts4#3699]
**Bug description**

ie error ：SCRIPT：445 Object doesnt support this action

i can see the amchart code will use window.resizeObserver

so  how can i  fixed it like as  resize-observer-polyfill ?

**Environment (if applicable)**

 - amCharts version： 4.2.10
 - Browser and its version  ie11  win10
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.]

**Additional context**

**Comment by martynasma** [comment]
amCharts 4 includes all the necessary polyfills.

That said, we are not using polyfills for resizeObserver, but rather have our own fallback for IEs.

Are you having issues with IE and amCharts not resizing properly?
