### ISSUE TITLE
Use less intrusive technique for printing the chart

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#37]
Currently the chart disables all top-level elements on the page before initiating print of the chart. Then restores after print.

This is kind of intrusive and may create various issues.

We need another technique that's less intrusive.

**Comment by dswitzer** [comment]
DataTables handles this pretty well, so you might look there for inspiration:

https://datatables.net/extensions/buttons/examples/print/customisation.html

The table you're printing opens up in a new window created strictly from JavaScript, then closes immediately after the user either prints or cancels the operation. It works in IE9+, Firefox, Chrome, etc. We haven't noticed any browser issues with the technique either.

**Comment by dswitzer** [comment]
I haven't tried this technique in a while, so I don't know how well it works, but maybe you could render in an iFrame/object and trigger the print within that object.

It might avoid issues with pop-up blockers.

**Comment by martynasma** [comment]
OK, good news :)

We've redone Export Print functionality. Now, the default print method is new hidden `<iframe>`, which seems to work just fine in all major browsers.

Pending wider testing, this looks like a good way to go about printing the charts.

We also threw in an optional CSS-based method, which can be turned on if iframe fails. (it's not a fallback, though, but a configurable option)

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.26](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.26)

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta26---2018-05-30).
