### ISSUE TITLE
Place tooltip to left 

### ISSUE THREAD

**Issue by abhiseksubham** [amcharts/amcharts4#3702]
Hi,

 I Just want to place tooltip to the left as i have a series of bullet charts , with a common axis.

<img width="282" alt="Screenshot 2021-08-17 at 7 36 58 PM" src="https://user-images.githubusercontent.com/2356647/129741155-7bee48e8-17c9-40ac-99b5-d63776cea8a5.png">

**Comment by martynasma** [comment]
To the left of what?

Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by abhiseksubham** [comment]
Yes, here is the codePen issue -> https://codepen.io/Abhiseksubham/pen/rNmprBO

There are two charts with common value axis range.

The tooltip of second chart i want to display at 20M but its coming at 60M in the chart.

**Comment by martynasma** [comment]
If you are not using cursor, putting `tooltipText` on series won't work as expected.

You need to put it on column template:

```JavaScript
series.columns.template.tooltipText = "......";
```

More info here:
https://www.amcharts.com/docs/v4/concepts/tooltips/#Series_tooltips

**Comment by abhiseksubham** [comment]
This works as a charm! 

Thank you so much!!
