### ISSUE TITLE
How to set the legend values to at most right?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3703]
Hi

I have been working on pie-charts,
![Screenshot from 2021-08-11 10-47-17](https://user-images.githubusercontent.com/71019344/129745336-605f480c-bc33-4e86-a644-ff7fdde77fb8.png)
in the above picture, i have applied legend width where legend values were closer to legend.
But i want the legend values has to be right most like below ones.
![Screenshot from 2021-08-11 10-49-44](https://user-images.githubusercontent.com/71019344/129745448-089db74b-0203-4e97-9b1f-77b5418fe608.png)
How can i set the legend values to be placed in right position. Is there a way to set those to right most within the legend width.
I'm attaching an demo of this, Can you help me out.

[demo](https://codepen.io/meghanananuvala/full/VwpgBEj)

Thank you.

**Comment by martynasma** [comment]
I kindly ask not to post duplicate issues (#3683). It will not fast track the solution :)
