### ISSUE TITLE
Pre-zoom a force-directed tree?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts4#3704]
Hi again,

I'm hoping to be able to set the zoom level on a force-directed tree to `0.5`, rather than its initial `0`. I've been looking through the docs, and when I thought I'd found my answer with `zoomFactor`, I realized the property was read-only. Are there any other options to produce the desired effect?

Thanks!

**Comment by martynasma** [comment]
How about this?

https://www.amcharts.com/docs/v4/chart-types/force-directed/#Zooming_via_API

**Comment by jonofoz** [comment]
I had passed by that in hope of a different solution, but this might actually be what I need, the more I think about it... thank you for the tip! 👍
