### ISSUE TITLE
 Amchart map question in vue js app

### ISSUE THREAD

**Issue by elbek** [amcharts/amcharts4#3705]
Hi everyone, we are trying to use amchart and running into an issue where it only shows map (map one down below) and its data on full page refresh. App is single page app(Vue js) so if user goes to other page and comes back it shows empty US map (second map) without any data in it. Would you be able to help resolving the issue. See attached 1st and 2nd map. 

We are using `4.10.21` version

Thank you. 

![map-1](https://user-images.githubusercontent.com/1192727/129798459-dd62b5b1-3382-4375-b772-29334d47c028.jpg)
![map-2](https://user-images.githubusercontent.com/1192727/129798482-de1842cb-4196-409a-8c2b-6823fd97ed6d.jpg)

**Comment by strixy** [comment]
(Vue 2?) Are you re-initializing the map (and deleting the previously held data as a result?) Are you using state management (ie. Vuex) to store your data? Are you referencing that store in your component or is the data only referenced following the API call? (in which case you would need to make that call again when revisiting the page or map it to state and reference that instead). This is most likely not an issue with Amcharts.

**Comment by elbek** [comment]
Using Vue 2, We are not using any state management. Data is referenced after rest api call. Yes api is called every time that page is visited.

**Comment by strixy** [comment]
Can you share some sample code?

**Comment by strixy** [comment]
@elbek Any luck? Still having an issue or have you solved it?
