### ISSUE TITLE
Set tooltip hoveroptions in template? Or how to make tooltips stay longer on MapChart?

### ISSUE THREAD

**Issue by mozboz** [amcharts/amcharts4#3707]
On a MapChart I need tooltips to hang around for a few seconds instead of immediately disappearing.

I've found the IHoverOptions touchOutBehaviour and touchOutDelay which looks like it could be what I need and seems like it applies to tooltips, but I can't figure out how to apply this to the tooltip in a template, or if there are some other options that I need to know about that somehow will enable this (e.g. what's hoverable?)

Sorry chart isn't online, but best effort I have a the moment is this:

```
var marker = imageSeriesTemplate.createChild(am4core.Image);
marker.href = "green-pin.svg";
marker.width = 20;
marker.height = 20;
marker.nonScaling = true;
marker.tooltipText = "{title} bar";
marker.tooltip = maintooltip
marker.tooltip.html = "{title} foo";
marker.tooltip.hoverOptions.touchOutBehaviour = "delay";
marker.tooltip.hoverOptions.touchOutDelay = 5000;
```

This uses my 'maintooltip' tooltip object, which I made in order to be able to easily get to hoverOptions, however the hoverOptions don't seem to be working or don't do what I want.

Looking for any reasonable solution to making tooltips stay around for a while. (I will not have many data points, so many cloned tooltip objects or tooltips on the screen at once is fine)

Thanks!

**Comment by martynasma** [comment]
I'm afraid there's no built-in function to delay tooltip removal on mousout. Sorry.

**Comment by mozboz** [comment]
> I'm afraid there's no built-in function to delay tooltip removal on mousout. Sorry.

Good to know, thanks for the reply, @martynasma 

What are the ways I could go about achieving this? E.g. I've seen settings that look like they cause the tooltip object to be cloned instead of using a single instance, so could I for example:

- Set new tooltips to be cloned
- On mouse over show a cloned tooltip and/or reset timer if tooltip already shown
- On mouse out set a delay
- On delay firing hide tooltip

Thanks, looking for pointers in the right directions to events/functions etc. in the docs that would help achieve this.

**Comment by martynasma** [comment]
Yeah, that sounds like something that could work.

I don't have an example like this, though. Do you think you want to take a stab at implementing it?
