### ISSUE TITLE
TypeScript Type errors from examples

### ISSUE THREAD

**Issue by dahmc** [amcharts/amcharts4#3708]
**Bug description**

I'm trying to build a radar chart, using the examples from here: https://www.amcharts.com/demos/radar-chart/

I then use the TypeScript / ES6 version of the code.

```javascript
/* Imports */
import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";
import am4themes_animated from "@amcharts/amcharts4/themes/animated";

/* Chart code */
// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

/* Create chart instance */
let chart = am4core.create("chartdiv", am4charts.RadarChart);

/* Add data */
chart.data = [{
  "country": "Lithuania",
  "litres": 501
}, {
  "country": "Czechia",
  "litres": 301
}, {
  "country": "Ireland",
  "litres": 266
}, {
  "country": "Germany",
  "litres": 165
}, {
  "country": "Australia",
  "litres": 139
}, {
  "country": "Austria",
  "litres": 336
}, {
  "country": "UK",
  "litres": 290
}, {
  "country": "Belgium",
  "litres": 325
}, {
  "country": "The Netherlands",
  "litres": 40
}];

/* Create axes */
let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis()); // Error here
categoryAxis.dataFields.category = "country"; // Error here

let valueAxis = chart.yAxes.push(new am4charts.ValueAxis()); // Error here
valueAxis.renderer.axisFills.template.fill = chart.colors.getIndex(2);
valueAxis.renderer.axisFills.template.fillOpacity = 0.05;

/* Create and configure series */
let series = chart.series.push(new am4charts.RadarSeries());
series.dataFields.valueY = "litres";
series.dataFields.categoryX = "country";
series.name = "Sales";
series.strokeWidth = 3;
```

The chart works, and it renders. However, TypeScript gives me all sorts of errors

![Screenshot 2021-08-18 at 08 22 17](https://user-images.githubusercontent.com/75008413/129848585-ff5e1267-fb90-4a74-a453-51c6f382eb63.png)
![Screenshot 2021-08-18 at 08 22 34](https://user-images.githubusercontent.com/75008413/129848593-41c7d489-5d12-40db-9e7b-0b0b5b55c858.png)
![Screenshot 2021-08-18 at 08 22 51](https://user-images.githubusercontent.com/75008413/129848601-30649542-4e87-4b4f-8074-e831734dd43f.png)

So, since the code actually works, I think it's the types that are wrong. Is this a known issue?

**Environment (if applicable)**
```
amCharts 4.10.21
react 17.0.2
typescript 4.3.5
```

**Comment by martynasma** [comment]
It's more of docs issue than charts. We are trying to keep code snippets as simple as possible, so that people copy-pasting them would not get into trouble.

Since using TS generics would result in syntax errors in vanilla JS apps, we don't use them.

You can work around it like this:

```JavaScript
let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis<am4charts.AxisRendererCircular>());

let valueAxis = chart.yAxes.push(new am4charts.ValueAxis<am4charts.AxisRendererRadial>());
```

**Comment by dahmc** [comment]
Thanks a lot. That's an easy fix I didn't see :)
