### ISSUE TITLE
Individual Tooltips on sankey nodes and links?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts4#3709]
Hi again!

I made this Codepen to test if I could make individual tooltips for sankey nodes and links: it seems to work, but I don't know what the larger implications of doing it this way are.
https://codepen.io/jonofoz/pen/JjNgogN

Essentially, I'm setting the `from` and `to` to the same node, which seems kinda hacky, and I'm also sacrificing `chart.links.template.propertyFields.id` to make this work, which seems like something I probably shouldn't be removing.

Again, and most of all, I don't know what sort of implications there will be further down the road if I develop this way. Is this the right way to go about making individual tooltips for nodes and links, or is there a better way I haven't found yet? 

Thank you!

**Comment by jonofoz** [comment]
IIUC, nodes linking to themselves is _currently_ the only way to have individual tooltips on nodes and links; doing it where nodes and links are defined separately would be nothing short of re-writing the entirety of how Sankey takes data, I think.

So, might I suggest a `fromTooltip`, and `toTooltip`, and `linkTooltip` on these connections? That could give users the sort of flexibility in declaring tooltips without linking nodes to themselves.

**Comment by martynasma** [comment]
You don't need a node to link to anything to attach a tooltip to it:

This will work just as well, and is official suggest way of doing it:

```JavaScript
chart.data = [
  // Nodes
  { from: "A", tooltip: "I'm A!"},
  { from: "B", tooltip: "I'm B!"},
  { from: "C", tooltip: "I'm C!"},
  { from: "D", tooltip: "I'm D!"},
  // Links
  { from: "A", to: "B", value: 1, id:"A-B", tooltip: "A → B" },
  { from: "A", to: "C", value: 1, id:"A-C", tooltip: "A → C" },
  { from: "A", to: "D", value: 1, id:"A-D", tooltip: "A → D" },
];
```

**Comment by jonofoz** [comment]
@martynasma Oh nice, thank you! I'll try this out.

In the hopes that I can reduce my number of questions in the future, does this happen to be mentioned somewhere in the docs, somewhere I may have missed?

**Comment by martynasma** [comment]
> In the hopes that I can reduce my number of questions in the future, does this happen to be mentioned somewhere in the docs, somewhere I may have missed?

Indirectly:
https://www.amcharts.com/docs/v4/chart-types/sankey-diagram/#Forcing_colors_to_any_node_even_if_it_isn_t_an_originating_node

**Comment by jonofoz** [comment]
@martynasma Awesome, thanks for the example. 👍 I just realized last night I'd seen it in [another example here](https://www.amcharts.com/demos/animated-sankey-diagram/), although I didn't know what to make of it at the time.

Either way, thanks... and cheers for putting up with my barrage of questions. 🙂 I'm trying to keep them as low as I can manage in my timeframe.
