### ISSUE TITLE
Add balloon like tooltip like amcharts 3

### ISSUE THREAD

**Issue by manoj016** [amcharts/amcharts4#371]
Hey,

How can I add balloon like tooltip in XYSeries like amcharts 3.

Exactly like this image attachment.
<img width="1440" alt="screen shot 2018-09-21 at 11 37 25 am" src="https://user-images.githubusercontent.com/41284266/45863214-c8690200-bd92-11e8-8f5b-e05e7243eb89.png">

**Comment by martynasma** [comment]
At this point we don't have immediate plans to implement tooltips like that.

That said, it's possible to tweak current balloons to resemble the shape with a bit of config:

```
series.tooltip.background.cornerRadius = 20;
series.tooltip.background.strokeOpacity = 0;
series.tooltip.pointerOrientation = "vertical";
series.tooltip.label.minWidth = 40;
series.tooltip.label.minHeight = 40;
series.tooltip.label.textAlign = "middle";
series.tooltip.label.textValign = "middle";
```

Here's an example:
https://codepen.io/team/amcharts/pen/LJaZXx/

Hope you find it useful.

**Comment by martynasma** [comment]
Posted as tutorial as well here:
https://www.amcharts.com/docs/v4/tutorials/round-tooltips/

**Comment by manoj016** [comment]
Thank you @martynasma that's really helpful

**Comment by sschrijver** [comment]
Is it also possible to change the background color of the tooltip?
Already tried `series.tooltip.background.fill = am4core.color('#000')` and `series.tooltip.background.color = am4core.color('#000')`, unfortunately without success..
