### ISSUE TITLE
Large amounts of data slows down sankey and creates an inconsistent visual flow?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts4#3711]
Hi again,

I've made an example of several connections in a sankey diagram here:
https://codepen.io/jonofoz/pen/jOmgyMm?editors=0010

I've noticed two things from this:
1. The amount of data in the chart seems to cause some lag when toggling nodes
1. Sometimes the source will appear on the right and the destination on the left (`Data Disambiguation → Kafka Streams` (far mid-right to far top-left), for example)

Am I doing something wrong here?

Thank you!

**Comment by martynasma** [comment]
I'm afraid we won't be able to do anything about toggling performance. There's a lot of nodes to animate.

As for the other question, is "Data Disambiguation" linking to itself on purpose?

**Comment by lancegliser** [comment]
I think that's related to #3709 and trying to get more individual tool tips.

**Comment by jonofoz** [comment]
@martynasma Lance is correct: that issue was made because I wasn't sure if I was going about creating individual tooltips for nodes and links correctly; to answer that would be to answer this.

**Comment by jonofoz** [comment]
Closing this per @martynasma 's answer in #3709 ; fixing the way nodes are assigned tooltips seems to have solved the issue with left-to-right flow not being respected and the performance seems to have received a small but noticeable boost. The 

Codepen has been updated with the latest code.
https://codepen.io/jonofoz/pen/jOmgyMm

Cheers!
