### ISSUE TITLE
Clickable countries, adding URLs to countries

### ISSUE THREAD

**Issue by vahidtakro** [amcharts/amcharts4#3714]
Hello, how can I make each country to be clickable and opens a custom link once the user clicks on?

**Comment by xorspark** [comment]
You can set a [propertyField](https://www.amcharts.com/docs/v4/concepts/data/#Property_fields) on the polygon template's `url` field to pull the URL from your series data. You can also set the [`urlTarget`](https://www.amcharts.com/docs/v4/reference/mappolygon/#urlTarget_property) to control where the links are opened.

[Demo](https://codepen.io/team/amcharts/pen/e585366ce186d266d9076c1d417a698c?editors=0010)

**Comment by vahidtakro** [comment]
> You can set a [propertyField](https://www.amcharts.com/docs/v4/concepts/data/#Property_fields) on the polygon template's `url` field to pull the URL from your series data. You can also set the [`urlTarget`](https://www.amcharts.com/docs/v4/reference/mappolygon/#urlTarget_property) to control where the links are opened.
> 
> [Demo](https://codepen.io/team/amcharts/pen/e585366ce186d266d9076c1d417a698c?editors=0010)

Thanks! that's what I was looking for.
