### ISSUE TITLE
Histograms with value axis

### ISSUE THREAD

**Issue by cutright** [amcharts/amcharts4#3715]
**Question**
As far as I can tell, amCharts does not natively support histograms with a numerical axis?  Long story short, I think I hacked it by attaching `Rectangle` to my bullets that dynamically update.  It looks pretty good, but the performance could be better during resize events.  I wonder if there's a more efficient way to update the `Rectangle` widths than editing the series property and calling `chart.validateData()`?

I also tried storing the events and only updating after a threshold change, but only modest gains.  Maybe there's a way to make edits entirely within amCharts that's more efficient?  Or maybe this is close enough to encourage native support? =)

**Environment (if applicable)**

amCharts4
Vue2
Chrome

**Additional context**

*Screenshot*
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/4778878/130368490-65a51668-8e23-428d-9e65-c4f0a9683dd5.png">

I don't have complete simple code to share, but the concept is pretty simple.  I create a LineSeries, then add a bullet series per line series like this:

*Some relevant methods*
```
    addBullet(key) {
      this.bullet[key] = this.series[key].bullets.push(new am4charts.Bullet());
      this.column[key] = this.bullet[key].createChild(am4core.Rectangle);
      let tooltip = `[bold]Center[/]: {${key}_center}\n[bold]Range[/]: {${key}_range}\n[bold]Counts[/]: {valueY}`;
      this.column[key].tooltipText = tooltip;
      this.column[key].tooltipY = am4core.percent(0);
      this.column[key].width = this.pixelScale
        ? this.getBinWidth(key, this.pixelScale)
        : 10;
      this.column[key].height = '1%'; // percent height ignored?
      this.column[key].fillOpacity = 0.5;
    },
    updateBinWidths(pixelScale) {
      for (let [key, series] of Object.entries(this.column))
        series.width = this.getBinWidth(key, pixelScale);
    },
    getBinWidth(key, pixelScale) {
      // this.binWidth is fractional, custom property
      return this.binWidth * (pixelScale * this.getXWidth(key));
    },
   getXWidth(key) {
      // numerical width of bins is stored the chart data, not the most efficient, but works
      for (let item of this.chartData)
        if (typeof item[key] != 'undefined') return item[`${key}_width`];
      return 1;
    },
```

*Add a responsive rule to catch chart size changes*
```
      const updatePixelScale = this.updatePixelScale; // for scope
      this.chart.responsive.rules.push({
        relevant: function (target) {
          let len = target.xAxes.values[0].axisFullLength;
          let min = target.xAxes.values[0].min;
          let max = target.xAxes.values[0].max;
          if (
            // target.xAxes.values[0] &&
            len &&
            typeof min != 'undefined' &&
            typeof max != 'undefined'
          )
            updatePixelScale(len / (max - min));

          return false;
        },
        state: function (target, stateId) {
          // Code that creates a new SpriteState object to be
          // applied to target if Rule is "relevant"

          return;
        },
      });
```

*Watch result of responsive rule, have component do updates*
```
watch: {
    pixelScale(val) {
      if (val) {
        this.updateBinWidths(val);
        this.chart.validateData();
      }
    },
  },
```

**Comment by martynasma** [comment]
`StepLineSeries` should work just fine on a `ValueAxis`.

Also, if you need to use `ColumnSeries`, you can set `series.column.template.width` to a fixed value, which can be calculated dynamically.

But frankly, I would just go with `StepLineSeries`.
