### ISSUE TITLE
Question: Smoothed Line

### ISSUE THREAD

**Issue by DimaGavrushko** [amcharts/amcharts4#3717]
I want to make my Line chart smoothed.

What parameters of tensionX and tensionY do I need to pass to get a result similar to smoothedLine in amcharts3?

amchart3 smoothedLine:
![image](https://user-images.githubusercontent.com/22750804/130471954-753e7d04-3148-44bf-b15d-6a86c440e2b4.png)

amchart4:
tensionX = 0.6;
tensionY = 1;
![image](https://user-images.githubusercontent.com/22750804/130471988-b778b278-ff0c-4c24-be3e-bf306a581e72.png)

**Comment by martynasma** [comment]
Try not setting tension at all, but rather `smoothing = "monotoneX"`.

https://www.amcharts.com/docs/v4/reference/lineseries/#smoothing_property

If that does not work, I would leave `tensionY` at `1`, and increase `tensionX`.

**Comment by DimaGavrushko** [comment]
@martynasma thanks
