### ISSUE TITLE
GeoJSON file for "Svalbard and Jan Mayen"

### ISSUE THREAD

**Issue by danish1994** [amcharts/amcharts4#3718]
**Bug description**

The drill-down of the Map breaks when we click on `Svalbard and Jan Mayen`. Looks like the geoJSON file used for that has invalid coordinates.

GeoJSON file - https://www.amcharts.com/lib/4/geodata/json/svalbardLow.json

 - amCharts version - 4
 - Browser and its version - Not related to Browser
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.] - Not related to a Framework

**Comment by danish1994** [comment]
![Untitled_ Aug 24, 2021 4_36 PM](https://user-images.githubusercontent.com/6189258/130606391-873329f3-a0fe-4000-92ca-196ef4bff870.gif)

**Comment by martynasma** [comment]
Fixed in geodata package 4.1.22
