### ISSUE TITLE
Node tooltips not respecting maxWidth?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts4#3721]
Hi again,

I've tried setting the `maxWidth` on my nodes to `150` as well as enabling `wrap`ping but it doesn't seem to work. However, it _does_ work on the links. Nothing I've seen in the docs tells me I'm doing something wrong, but I may be...
![image](https://user-images.githubusercontent.com/29444592/130679413-d75f044f-3582-4522-b932-47aaecdf7ecb.png)

Here's my code: https://codepen.io/jonofoz/pen/jOmgyMm?editors=0010
Cheers!

**Comment by xorspark** [comment]
The wrapping works just fine on the nodes; try reducing the maxWidth or adding extra text to your node tooltip to see for yourself.

This is what I see on my end:

![image](https://user-images.githubusercontent.com/2679427/130685232-4d95291f-e438-4970-bc75-92e98ec93d11.png)

**Comment by jonofoz** [comment]
@xorspark Huh. Thank you! I must be tired, because yeah it works perfectly.
