### ISSUE TITLE
collap only two series of bubbles out of five series

### ISSUE THREAD

**Issue by Data-Think-2021** [amcharts/amcharts4#3732]
Hi,
I created column series and then the Circles() to create bubble chart. Now I would like to overlap two series of bubbles (two columns) and adjust the space between them. 
Here is the link in codepen [amcharts bubble](https://codepen.io/team/amcharts/pen/PomZdop). When I use series1.clustered = false; series2.clsutered = false; then all series collaps together. 
at my work I have 5 series. How to collap only two series and set the x distance between the bubbles from each other. I tried to use series2.columns.template.dx = -100; which nothings happens..

Thank you if you can point out. 

Best regards

**Comment by Data-Think-2021** [comment]
Hi, thank you for your reply. However, it doesn't solve the problem. Could you pls. have a look at the link [](https://codepen.io/team/amcharts/pen/PomZdop)? 
I would cluster only two series, but when i use the following 2 lines of codes, all the series cluster together. As I tried with my own data which I have 5 series. It seems the clustered series will always appear in the middel. Then the distance to the other series are random. Do you have an idea or suggestion so that I can freely cluster the series I want and define the distance between the clusted series to others ? 
series1.clustered = false;
series2.clustered = false;

Thank you.

**Comment by martynasma** [comment]
In this case you may need to use two separate X axes, with different `cellStartLocation`/`cellEndLocation`.

https://www.amcharts.com/docs/v4/tutorials/managing-width-and-spacing-of-column-series/

The first X axis would have their cells start and end at 0 and 0.5.

The second would start and end at 0.5 and 1.

Hope that makes sense.
