### ISSUE TITLE
Is it possible to display more information on CategoryAxis when we hover?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3736]
Hi

I'm working on barcharts where on the y-axis we have some specific shorthand codes. Is it possible when we hover on specific code on y-axis to display more information regarding that code.

below screenshot is attched for refernce.
![Screenshot from 2021-08-27 15-55-43](https://user-images.githubusercontent.com/71019344/131113710-e73bfac2-8033-4ab5-b7d2-a62478a0a393.png)
ex: when we hover on 'FTHI' code on y-axis is it possible to display further info.

Thank you and let me know soon.

**Comment by martynasma** [comment]
Yes, you can add `tooltipText` to axis categories:

```JavaScript
yAxis.renderer.labels.template.tooltip = new am4core.Tooltip();
yAxis.renderer.labels.template.tooltipText = "{category}: {someFieldInData}";
```
