### ISSUE TITLE
(play)Button Properties

### ISSUE THREAD

**Issue by IMTanuki** [amcharts/amcharts4#3739]
ENVIRONMENT
- amcharts 4 (latest via cdn)
- bootstrap 5.1

CHART TYPE(S)
- RadarChart
- XYChart

USE CASE
Trying to config amcharts playButton so it's consistent with bootstrap, esp state-related background, border and shadow.

QUESTION(S)
sorry for overloading the question...
1. what (if any) is the border property for playButton?

2. if there is a separate property for border width?

3. is there an bootstrap-equivalent bxoshadow property for playButton? 

I've checked the doc and github issues list...

Thx

**Comment by martynasma** [comment]
> what (if any) is the border property for playButton?
> if there is a separate property for border width?

```
button.background.stroke = am4core.color("#f00");
button.background.strokeWidth = 2;
button.background.strokeOpacity = 1;
```

> is there an bootstrap-equivalent bxoshadow property for playButton?

The following tutorial explains how to add filters (including shadow) to stuff in amCharts 4:
https://www.amcharts.com/docs/v4/tutorials/using-filters/

**Comment by IMTanuki** [comment]
Hi and thx for the quick reply!

Box shadow implementation via filters noted - looks great.

BUt I'm not seeing any reference to a border - is there a border filter?

Thx again!

**Comment by martynasma** [comment]
> BUt I'm not seeing any reference to a border - is there a border filter?

You don't need a border filter. You can set button outline via background stroke properties as per above.

**Comment by IMTanuki** [comment]
Works great! thx!
