### ISSUE TITLE
Bullets do not inherit line segment color (when using propertyFields)

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#374]
I am trying to recreate this v3 demo of changing line/fill colors in a line graph: https://codepen.io/pen/?editors=1010.

In v4, I am using propertyFields. This works great for the line and fill (similar to v3 `lineColorField` and `fillColorsField`).

```
lineSeries.propertyFields.stroke = "lineColor";
lineSeries.propertyFields.fill = "lineColor";
```

However, the propertyFields do not work the same way for the line's bullets. They do not work "continuous", meaning that the fill color is only applied to the data point with that propertyField, not the consecutive ones.

```
var bullet = lineSeries.bullets.push(new am4charts.CircleBullet());
bullet.circle.radius = 4;

// only applies once, to the first bullet in a "sequence"
bullet.circle.propertyFields.fill = "lineColor";
bullet.circle.propertyFields.stroke = "lineColor";
```

Demo: https://codepen.io/team/amcharts/pen/9c31efcf8fcbba4961e74730cac809ac?editors=1010

**Comment by zeroin** [comment]
The only way to achieve this would be adding a separate data field like bulletColor to each of the data items and setting bullet color there. In the future, we might change it, but it's not yet possible.
