### ISSUE TITLE
Tooltip - Duplicate Tooltip Showing

### ISSUE THREAD

**Issue by IMTanuki** [amcharts/amcharts4#3740]
ENVIRONMENT
amcharts 4 (latest via cdn)
bootstrap 5.1

CHART TYPE(S)
RadarChart
XYChart

USE CASE
Trying to config amcharts tooltip to conform to bootstrap theme.

ISSUE
It seems like there are 2 tooltips displaying - the one I configured and a second (basic) tooltip - just want a single tooltip.

CODE
`	// init playButton tooltip
	playButton.tooltipText = "Play / Pause";
	playButton.tooltipText.stroke = xmdColors.white;
	playButton.tooltip.getFillFromObject = false;
	playButton.tooltip.background.fill = xmdColorsTheme.primaryVariant;
`

EXAMPLE
In the following, you can see my configured tooltip above the playButton and a second tooltip below it.

[vid of tooltip](https://imtanuki.tinytake.com/msc/NTc2ODQ0Ml8xNzc2NTU2NA)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by xorspark** [comment]
The other tooltip is the native HTML tooltip, which is controlled by a separate property. If you want to disable it, set `showSystemTooltip` to false.

```
playButton.showSystemTooltip = false;
```

[Documentation](https://www.amcharts.com/docs/v4/reference/playbutton/#showSystemTooltip_property)

**Comment by IMTanuki** [comment]
Thx so much!
