### ISSUE TITLE
How to wrap the text in 2 rows if it is too long in Wicker Chart?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3741]
Hi 

![Screenshot from 2021-08-30 11-48-25](https://user-images.githubusercontent.com/71019344/131294119-fe9c349b-ef89-4ee3-a000-38f265006ea2.png)
In the above picture you can see that there are values on X-axis were overlapping due to large text on each wicker. Can you check any way to wrap it in two rows if we have large text.

Thanks in advance.

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/tutorials/wrapping-and-truncating-axis-labels/
