### ISSUE TITLE
While reloading the chart not able to trace the div element?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3742]
Hi 

While changing something in page itself the wicker chart  able to load and draw, but when i reload the page / navigate from one page to another i'm not able to get the chart.

While doing that i got error in console, 
**Error occurred:html container not found Error: html container not found
    at createChild (vendor.js:92276)**

please suggest something to overcome this situation.

Thank you.

**Comment by martynasma** [comment]
Duplicate: #3745
