### ISSUE TITLE
Scrollbar zooms in on wrong values when zooming backwards

### ISSUE THREAD

**Issue by peirix** [amcharts/amcharts4#3743]
**Bug description**

I see that the zoom function works properly on all demoes on the site, but on my dataset it seems to zoom into the wrong values range, especially when going backwards in time. I've set up a codepen that is able to reproduce the bug:

https://codepen.io/palmustasj/pen/wveMOOE

**Environment (if applicable)**

amCharts 4

**Comment by xorspark** [comment]
[Date base data must be sorted in date-ascending order](https://www.amcharts.com/docs/v4/concepts/data/#Date_based_data). Your date is in date-descending order

**Comment by peirix** [comment]
Ah. Somehow missed that in the documentation. That cleared everything up. Thanks.
