### ISSUE TITLE
Conditionally format categories

### ISSUE THREAD

**Issue by IMTanuki** [amcharts/amcharts4#3744]
ENVIRONMENT
amcharts 4 (latest via cdn)
bootstrap 5.1

CHART TYPE(S)
RadarChart
XYChart

USE CASE
Trying to highlight one category (out of many).

QUESTION(S)
Is it possible to conditionally format (in this case, set font-weight) a single category, based on the category name, as in:
United States  
**China**
Lithuania

- just the category name, not the values...
Thx!

**Comment by xorspark** [comment]
You can use an adapter on the axis label's text property:

```
categoryAxis.renderer.labels.template.adapter.add("text", function(text, target) {
  if (text && target.dataItem && target.dataItem.category == "China") { 
    return "[bold]" + target.dataItem.category + "[/]";
  }
  return  text;
});
```

Note that we have a tutorial dedicated on how to use adapters along with several examples listed here: https://www.amcharts.com/docs/v4/concepts/adapters/

**Comment by IMTanuki** [comment]
You folks have seriously designed a well-architected and scalable product...kudos!
