### ISSUE TITLE
When i hover on particular i'm not getting full string ?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3747]
Hi

![Screenshot from 2021-09-02 15-06-35](https://user-images.githubusercontent.com/71019344/131820977-2b93b047-ad04-409c-acaf-3d3911e1ddc9.png)
I'm having Client API - {channel1} but when i hover on particular channel that i'm getting half of the string like below one.
![Screenshot from 2021-09-02 15-06-26](https://user-images.githubusercontent.com/71019344/131821231-afc5bc2e-c8c9-4481-b99a-891366a0dcf6.png)
Can u check this out and help me to get the full name as when i hover.

Thank you.

**Comment by martynasma** [comment]
Curly brackets denote a placeholder in amCharts strings.

If you need that displayed, you need to escape them by repeating them twice:

`"Client API - {{Channel 1}}"`

**Comment by meghanaNanuvala** [comment]
i mean i'll get the data as "Client API - {Channel 1}", any other way to display in the same way
instead of adding double braces around the text.

**Comment by martynasma** [comment]
I suppose you could use an adapter:

```JavaScript
categoryAxis.tooltip.label.adapter.add("text", function(text) {
  if (text) {
    text = text.replace("{", "{{");
    text = text.replace("}", "}}");
  }
  return text;
});
```

**Comment by meghanaNanuvala** [comment]
Thanks it's working
