### ISSUE TITLE
Problem with Legends

### ISSUE THREAD

**Issue by robertocerdasilva** [amcharts/amcharts4#3749]
Hi there! Could you help me with the following please?

The legend of my chart is sorted down when I have have a very long text. By default, the width of the first legend is equal to the width of the legend below. How can I avoid this situation? (see image, box marked in red)

Important: I must not hide part of the text of any legend or replace it with an ellipsis.

Thanks!

![chart legend with long text](https://user-images.githubusercontent.com/72045538/131945450-a74c343f-5732-43c0-aa62-d55e8ed58e31.png)

Code:

```
chart.legend = new am4charts.Legend()
chart.legend.contentAlign = 'center'
chart.legend.position = 'bottom'
chart.legend.paddingTop = 20
chart.legend.paddingBottom = 0
chart.legend.fontSize = 12
chart.legend.fontWeight = 500
chart.legend.labels.template.width = 50
chart.legend.labels.template.wrap = false
chart.legend.labels.template.truncate = false
chart.legend.markers.template.maxWidth = 95
chart.legend.markers.template.height = 10
```

**Comment by martynasma** [comment]
I'm afraid there's no way to make items wrap into lines, but not get arranged into columns. Sorry.
