### ISSUE TITLE
GeoJSON update for South Africa (ZA)

### ISSUE THREAD

**Issue by danish1994** [amcharts/amcharts4#3752]
**Bug description**

The geoJSON for `South Africa` has old `Region Codes` which were updated from `2020-03-02` - https://www.iso.org/obp/ui/#iso:code:3166:ZA

From ISO code - `Change of subdivision code from ZA-GT to ZA-GP, ZA-NL to ZA-KZN; Update Code Source`

**Comment by martynasma** [comment]
Fixed in geodata package 4.1.22
