### ISSUE TITLE
How can I control the chart render order using queue?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3753]
I have a dashboard which can have multiple charts. To avoid bogging down the browser I am using queue to ensure that the charts will be rendered one-by-one, but the render order is quite messy, is it possible to force a render order?

**Comment by martynasma** [comment]
Well, if you have queueing enabled, the charts will be rendered in the same order as you crate theme using `am4core.create()`.

So perhaps you can control that? :)
