### ISSUE TITLE
When exporting a graphic as an image, the image is blurred

### ISSUE THREAD

**Issue by robertocerdasilva** [amcharts/amcharts4#3756]
Hello good afternoon. I have a problem for which I cannot find a solution. Every time I export a graphic, the texts of the categories and values in the image look somewhat blurry and it is uncomfortable as they require the quality of the image to be very clear and easy to read.

I have the following configuration:

```
chart.exporting.menu = new am4core.ExportMenu()
chart.exporting.menu.items = [{
    "label": "Download",
    "menu": [
        { "type": "png", "label": "Image" },
        { "type": "xlsx", "label": "Xlsx" }
    ]
}]
chart.exporting.useRetina = false
```

The value of "useRetina" I have tested it in false and true, and there are no changes.

Thanks!

**Comment by martynasma** [comment]
Does this happen in all browsers for you?

**Comment by robertocerdasilva** [comment]
Thanks for answering. It happens in Chrome and Edge, in their most updated versions. In Firefox, this is where the image looks best when exporting. (Windows 10 operating system)

**Comment by martynasma** [comment]
Can you post your chart on CodePen? I'd like to take a look.
