### ISSUE TITLE
Series hidden by default but not label legend

### ISSUE THREAD

**Issue by fredmef** [amcharts/amcharts4#3758]
**Bug description**

In the following example [CodePen](https://codepen.io/fredmef/pen/pogEvaX), series1 is hidden by default `series1.hidden = true;` but the corresponding label legend doesn't reflect that this series is hidden. 

<img width="366" alt="image" src="https://user-images.githubusercontent.com/41957018/132368611-6ace8192-401f-4730-a1f5-02dd7d1a3bf7.png">

The label legend for series1 should be in grey color like for the markers.

**Environment (if applicable)**

**Additional context**

**Comment by zeroin** [comment]
There is no way to override font color when it is set in-line. As I understand you want the label to be of the same color as the series. I modified your example which adds adapter for default state and makes this happen without inline formatting:

https://codepen.io/team/amcharts/pen/da1965c44df04303f8071e5b9bcebb5b
