### ISSUE TITLE
Is any chance to fix the #2852 in amcharts5?

### ISSUE THREAD

**Issue by NemoDima** [amcharts/amcharts4#3763]
@martynasma Sorry that bothers you.
Could you please tell me, is any chance to fix the [#2852 ](https://github.com/amcharts/amcharts4/issues/2852) in the new amcharts5?
Best wishes.

**Comment by martynasma** [comment]
Request: please use [amCharts 5](https://github.com/amcharts/amcharts5/issues) repo for reporting V5 issues. This repo is for V4-related bugs/discussion. Thank you for understanding.
