### ISSUE TITLE
Changing DateAxis start/end triggers `Maximum call stack size exceeded` error

### ISSUE THREAD

**Issue by depsimon** [amcharts/amcharts4#3764]
**Bug description**

I'm building a date-based value graph with two axes (dates & values). 
I'm adding an horizontal Scrollbar to make it more usable when there are lots of dates.
I'm trying to preselect the end of the dates range when there are lots of dates. (when there are > 30 dates, i'd like to only show the 30 latests)

I'm using the `start` & `end` properties of the date axis to do that, but I'm having an exception triggered.

I also tried using `this.chart.cursor.xAxis.start = 0.5;` but with the same results.

Demo : https://codesandbox.io/s/busy-galileo-hw9id?file=/src/components/Impressions.vue

**Environment (if applicable)**

- @amcharts/amcharts4 - 4.10.22
- vue ^3

<img width="1372" alt="Screen Shot 2021-09-14 at 9 16 00 AM" src="https://user-images.githubusercontent.com/1822289/133212649-09885aba-9224-40b0-a395-86658d0ea451.png">

**Comment by xorspark** [comment]
As mentioned in our [Vue docs](https://www.amcharts.com/docs/v4/getting-started/integrations/using-vue-js/#selenium-highlight), don't make chart object references inside your data hook as Vue likes to take ownership of anything placed there with its proxy objects, breaking our library. Create the variables in `created` instead, then assign them in your `mounted` hook (in your case, buildChart). This will make the axis' start/end and zoom method work.

Demo: https://codesandbox.io/s/flamboyant-galois-mxwfo?file=/src/components/Impressions.vue

**Comment by depsimon** [comment]
I definitely missed that part in the docs. Thanks for pointing it out, this is what I needed!
