### ISSUE TITLE
How to show the last category label when responsive is enabled?

### ISSUE THREAD

**Issue by Godsex** [amcharts/amcharts4#3766]
**Question**

How to show the last category label when responsive is enabled?

![image](https://user-images.githubusercontent.com/29534170/133232754-59c48e9c-0ff4-4644-a25b-5e2636d761e5.png)

**Comment by martynasma** [comment]
Maybe you can use an approach from these demos:
https://www.amcharts.com/docs/v4/tutorials/force-first-and-last-labels-on-axis/
