### ISSUE TITLE
Sankey nodes crammed at end: is my data wrong, or my styling?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts4#3767]
Hi there,

Our app just received some new data for our implementation of the AMCharts Sankey, and it appears to place both the `"Disambiguation Service"` node and the `"Graph Persistence Service"` node at the far right; AFAIK, the former should not be crammed to the right, since its `to` goes to the latter.

Here's my Codepen: Any idea what's wrong here? I've studied it and poked at it, but haven't found any apparent reason yet that would cause it to do this. I'm feeling it's dead simple, just need a second pair of eyes.
https://codepen.io/jonofoz/pen/YzQXyoR?editors=0010

(Please note, there are several connections from `Source/0005` to `Source/0009` in the data: this is correct, but I'm not sure how or if AMCharts handles multiple edges between two same nodes. Either way, reducing the edges to only one didn't solve my problem.)

Thank you!

**Comment by martynasma** [comment]
There are few issues with the data.

1) The 05 > 09 links appear three times in data.
2) "Empty" 09 link (one without the "to" value) should be moved to the end of the "empty" link list.

**Comment by martynasma** [comment]
https://codepen.io/team/amcharts/pen/d310b2baf3d018b2ce1ea00852c4a4dc?editors=0010

**Comment by jonofoz** [comment]
@martynasma Thank you for the response! Had no idea terminating nodes needed to be at the end. 

One last question: why is 1. a problem? In our case, the three edges represent three different processes across a source and destination, and the sankey seems to handle them like a pro.
https://codepen.io/jonofoz/pen/BaZmoEY?editors=0010

**Comment by jonofoz** [comment]
@martynasma Ah, okay. :) Cheers!
