### ISSUE TITLE
How to reduce size of cell in heat map ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3769]
I have a heat map like given in below code
[https://codepen.io/vineelak/pen/abwZbmx](url)

Instead of large cells I want size of cells like simple table (size should be enought to fit the corresponding value like below one)

![Screenshot from 2021-09-15 18-32-15](https://user-images.githubusercontent.com/74599304/133438241-99cafe58-ae6d-4d22-a055-2b3b0d1b40f1.png)

I have to use single color gradient for the heatmap. Help me to solve it.

Thank You

**Comment by martynasma** [comment]
You have two options:

1) Reducing chart size so that columns in chart are reduced in width along with it.

2) Setting fixed width of the columns, but that will mean that there will be haps between columns.

```
series.columns.template.width = 50;
```

Not entirely sure what else to suggest.

**Comment by VineelaKantamneni** [comment]
Already I had tried second option but it doesn't gave expected result and reducing chart size also haven't give expected result.

Is there a way to control the width and height of grid in am4 charts ?

**Comment by VineelaKantamneni** [comment]
How to adjust width and height of a grid in amcharts ?

**Comment by martynasma** [comment]
Grid in amCharts are vertical and horizontal lines on axes. It is placed according to your data and available space.

The colored squares you see on the chart are columns. They are sized either relative to available space or fixed width/height in pixels, as per your configuration.

If you have chart with plot area sized at 500 pixels, and have 5 categories, each category will be 100 pixel wide. If you have your columns sized at 100%, it means that each column will be 100 pixel wide.

If chart size changes to 1000 pixels width, all columns will become 200 pixel wide.

I'm not sure how to put it another way.

If you need your chart columns or "grid" to be fixed size, regardless of how many categories there are, you will need to automatically calculate width/height of the chart container, and size it accordingly.

The following tutorial might get you on the right track:
https://www.amcharts.com/docs/v4/tutorials/auto-adjusting-chart-height-based-on-a-number-of-data-items/

**Comment by VineelaKantamneni** [comment]
Thank you
