### ISSUE TITLE
show absolute numbers instead of percentage

### ISSUE THREAD

**Issue by manoj016** [amcharts/amcharts4#377]
Hi,

I am trying to show absolute numbers instead of percentage in both legend and tooltip of Pie Series in pie chart. Can someone help me?

Thank you,

**Comment by martynasma** [comment]
Yes:

```
pieSeries.labels.template.text = "{category}: {value.value}";
pieSeries.slices.template.tooltipText = "{category}: {value.value}";
chart.legend.valueLabels.template.text = "{value.value}";
```

**Comment by martynasma** [comment]
Posted here as well:
https://www.amcharts.com/docs/v4/chart-types/pie-chart/#Modifying_labels_legend_tooltip

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by manoj016** [comment]
Thank you very much

**Comment by MirzaSarimBaig** [comment]
I want to convert absolute numbers in percentage here what i am doing,

        var cumulativeSeries = x.series.push(new am4charts.LineSeries());
        cumulativeSeries.dataFields.valueY = "cumulativeFinish";
        cumulativeSeries.dataFields.categoryX = "date";
        cumulativeSeries.yAxis = costValueAxis;
        cumulativeSeries.name = "Cumulative Finish";
        cumulativeSeries.strokeWidth = 2;
        cumulativeSeries.propertyFields.strokeDasharray = "dashLength";
        cumulativeSeries.tooltipText = "{valueY.percent}";
        cumulativeSeries.tensionX = 0.8;
        cumulativeSeries.tensionY = 0.8;
        cumulativeSeries.calculatePercent = true;
        cumulativeSeries.dataFields.valueYShow = "percent";
        
        But still can't achieve right graph.
        Means its converting values in percentage but while mapping the higher number line is below the other line
        
![image](https://github.com/user-attachments/assets/35c99d3d-5966-4baf-b02c-5bcfd9d2b05d)

The output is this but the line should come above the as drawn from the red color
