### ISSUE TITLE
am4chart Bar Chart Race displaying unkown number

### ISSUE THREAD

**Issue by r00nscapenab** [amcharts/amcharts4#3771]
**Bug description**

Bar chart race is displaying "1â€¦" in the graph.. I have tried formatting the number to integer and whole number but it is still the same.. any ideas?
![image](https://user-images.githubusercontent.com/24377641/133869705-89410df8-a277-4b94-8a7c-bf4b892a6601.png)

**Comment by martynasma** [comment]
Please refer to this response: https://github.com/amcharts/amcharts4/issues/3017#issuecomment-713259635
