### ISSUE TITLE
Beta link disable on https://www.amcharts.com/ website

### ISSUE THREAD

**Issue by oliverlj** [amcharts/amcharts4#3772]
On brave browser, the beta link is disable. These is on lib block by default : (https://www.google-analytics.com/analytics.js)

![image](https://user-images.githubusercontent.com/1826498/133935678-003b23b4-cc81-4761-97c8-9433a81eda4a.png)

**Comment by martynasma** [comment]
This is a repo for amCharts 4, so a bit off topic. Thanks, anyway!

Here's the link: https://amcharts.com/v5/
