### ISSUE TITLE
Show min/max values on chart

### ISSUE THREAD

**Issue by igoriok1994** [amcharts/amcharts4#3777]
Hi,

I'm wondering if amChart4 has a feature to show MIN/MAX on then line/bar charts.

Eg (this variant will be the best):
![image](https://user-images.githubusercontent.com/37294916/134162443-7bfecc6c-9896-47d8-8086-ff287a010947.png)

Or:
![image](https://user-images.githubusercontent.com/37294916/134162522-1b03f83e-b32f-44b4-a23c-94d04696ac8a.png)

Or:
![image](https://user-images.githubusercontent.com/37294916/134162592-5f8cc94e-cee8-4c5d-9229-581a7d812eb9.png)

Is it possible to achieve something like this?

**Comment by igoriok1994** [comment]
Is it possible?

**Comment by martynasma** [comment]
There's no built-in feature like that.

I suppose you could add a second series with bullets for min and max value, e.g.:

https://codepen.io/team/amcharts/pen/oNwVjvd

**Comment by igoriok1994** [comment]
Ok. Is it possible to insert in chart container some other element (eg. only label/bullet/rectangle) using x,y coordinates (date + value)?

**Comment by igoriok1994** [comment]
I saw some examples with "axisRange" & "axisBreak" where a vertical line was inserted

**Comment by martynasma** [comment]
If you want to use X/Y coordinates, then you will need to use series with bullets for that.

If you need to add an icon/line on specific category/date/value attached to axis, you can use axis range.
