### ISSUE TITLE
How to get label as Vertical ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3780]
![Screenshot from 2021-09-21 20-35-39](https://user-images.githubusercontent.com/74599304/134197753-5a0bcf11-2195-4373-a956-2f7429f0ebde.png)

I want to represent the label in above bars vertically instead of horizontal.

**Comment by xorspark** [comment]
You can set the [`rotation`](https://www.amcharts.com/docs/v4/reference/label/#rotation_property) in your label object to -90 or 90. Assumine you're using a LabelBullet object:

```
labelBullet.label.rotation = -90;
```

**Comment by VineelaKantamneni** [comment]
Thank You
