### ISSUE TITLE
Value axis does not appear after deleting and then re-adding the XY series 

### ISSUE THREAD

**Issue by mkdudeja** [amcharts/amcharts4#3781]
Hi Team,

**Bug description**

Deleting the series and then re-adding the series cause the value axis to disappear from the chart. I have tried multiple methods like `validateData` and `invalidateData` on yAxis and series. But no luck. 

Codepen replication:
https://codepen.io/mkdudeja/pen/dyRjoQX

Steps to reproduce:
- Click on `Delete series` - Series will be removed and Value axis will be hidden from the chart
- Click on `Add Series` - New series will be added and visible on the chart, however, the value axis doesn't appear back.

**Environment (if applicable)**
 - amCharts version = 4.10.22
 - Browser and its version = Chrome, v93.0

Thanks,
Manish Kumar

**Comment by zeroin** [comment]
Hi,

I modified pen and it solves the issue:
https://codepen.io/team/amcharts/pen/dyRQKdQ

1) when series is removed from the chart, reset _minAdjusted and maxAdjusted to 0. 
2) do not set series data to the same as chart data, this only complicates things.
