### ISSUE TITLE
How to display truncated labels of a axis on hover ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3783]
As my labels of category axis are too long. so I had truncated the labels like below.
![Screenshot from 2021-09-23 11-49-11](https://user-images.githubusercontent.com/74599304/134462436-58b25cd5-ab89-4dc9-8035-2249c5f82429.png)

Now, I have to display complete label when I hover on a label.

Thank you.

**Comment by martynasma** [comment]
Check this out ;)

https://www.amcharts.com/docs/v4/tutorials/wrapping-and-truncating-axis-labels/#Displaying_tooltips

**Comment by VineelaKantamneni** [comment]
Thank You
