### ISSUE TITLE
Stacked Axes | Changing the layout dynamically distort the chart

### ISSUE THREAD

**Issue by mkdudeja** [amcharts/amcharts4#3784]
Hi Team,

Changing the layout of the chart dynamically distorts the chart.

Horizontal to Vertical stacking = Works fine
Vertical stacking to Horizontal = Distorted chart

Demo:
https://codepen.io/mkdudeja/pen/oNwMmaX

*Expected behavior:*
The chart should get updated to newer settings without any distortions.

Try clicking on `toggleLayout`.

Thanks,
Manish Kumar

**Comment by zeroin** [comment]
To solve this, you must reset y of all the yAxes to undefined before changinf layout:
https://codepen.io/team/amcharts/pen/eYRQKxy
