### ISSUE TITLE
How to move legends in a chart to completely right ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3785]
I have a legends in my chart as below.
![Screenshot from 2021-09-23 13-44-09](https://user-images.githubusercontent.com/74599304/134474792-245b455b-cc91-404a-80f1-718bf3ef4e7e.png)

In above image there is space after legends in right side. I have to move those legends completely right side. 

Thank You.

**Comment by martynasma** [comment]
Try disabling value labels:

```Javascript
chart.legend.valueLabels.template.disabled = true;
```

**Comment by VineelaKantamneni** [comment]
Still there is a space like in previous case

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by VineelaKantamneni** [comment]
https://codepen.io/vineelak/pen/BaZxbgy?editors=1010

**Comment by martynasma** [comment]
Thanks. You can remove margin and padding from various elements:

```JavaScript
chart.paddingRight = 0;
chart.legend.marginRight = 0
chart.legend.labels.template.marginRight = 0;
chart.legend.itemContainers.template.marginRight = 0;
```

**Comment by VineelaKantamneni** [comment]
Thank you it's working.
But when I disable a legend then I am getting scroll bar like below.
![Screenshot from 2021-09-24 13-12-39](https://user-images.githubusercontent.com/74599304/134637456-07045d9a-4a5c-4aaa-a0a5-0f96d9101be4.png)

**Comment by martynasma** [comment]
I'm not sure where this scrollbar is coming from. Do you have a demo?

**Comment by VineelaKantamneni** [comment]
No. In codepen I'm not getting it  where as in my application I am getting.

**Comment by martynasma** [comment]
Maybe try adding `override: hidden` CSS to chart container?
