### ISSUE TITLE
How to decrease height of scrollbar in am4 charts?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3786]
![Screenshot from 2021-09-23 14-47-38](https://user-images.githubusercontent.com/74599304/134482881-6db3fccd-f1ed-4c5e-a98e-c2dc45ffb5e5.png)

Size of my scroll bar is like in the above image.But I would like to have height of my scrollbar as like in below image.

![Screenshot from 2021-09-23 14-49-38](https://user-images.githubusercontent.com/74599304/134483077-4918fed2-8e98-4c54-918f-b4d5f569ff92.png)

Thank you.

**Comment by xorspark** [comment]
You can use [`minHeight`](https://www.amcharts.com/docs/v4/reference/scrollbar/#minHeight_property) and [`height`](https://www.amcharts.com/docs/v4/reference/scrollbar/#height_property) to further adjust the size.

```
chart.scrollbarX.height = 30;
chart.scrollbarX.minHeight = 10;
```

Note that your screenshot looks like you're using an XYChartScrollbar, which is larger to account for the chart preview within the scrollbar. The regular scrollbar is much narrower by default:

```
chart.scrollbarX = new am4core.Scrollbar();
```

**Comment by VineelaKantamneni** [comment]
Thank You.
