### ISSUE TITLE
How to draw 2 series in Heat Map Table ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3787]
I had to represent two series in single heat map table using am charts. Is it possible to represent two series in single heat map. If yes then how ?
provide me with a example.

Thank You.

**Comment by martynasma** [comment]
No, I'm afraid.

**Comment by VineelaKantamneni** [comment]
ok. Thank You.

**Comment by VineelaKantamneni** [comment]
can I display additional content , using any call backfunction , in the  cell?

**Comment by martynasma** [comment]
Yes, you can display any textual content using bullets.

**Comment by VineelaKantamneni** [comment]
Thank You

**Comment by VineelaKantamneni** [comment]
How to wrap the text of bullets ?

**Comment by VineelaKantamneni** [comment]
Ok. Thank you.
