### ISSUE TITLE
How to display an external value in tool tip of Heat Map

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3788]
I have to display an external parameter in tool tip text of a heat map table. so I had used a adapter like in below code.

[https://codepen.io/vineelak/pen/abwZbmx?editors=1111](url)

But it's displaying multiple times. I want to display the external parameter only once
Thank You.

**Comment by xorspark** [comment]
This is redundant inside the adapter:

```
series.columns.template.tooltipText = display; //remove this
```

You only need to return the display value from your adapter to update the tooltipText.
