### ISSUE TITLE
How to wrap label bullet text ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3789]
`const bullet = series.bullets.push(new am4charts.LabelBullet());`
      `  bullet.interactionsEnabled = false;`
      `  bullet.label.text = '{value}%';`
       ` bullet.label.fill = am4core.color('#000000');`
        `bullet.locationX = 0.5;`
        `bullet.label.wrap  = true;`
        `bullet.label.maxWidth = 10;`

I had used above lines code to create and wrap a label bullet. But wrapping of label text is not taking place.

Thank You.

**Comment by xorspark** [comment]
You might also need to add `truncate = false` in your LabelBullet setup.

```
bullet.label.truncate = false;
```
