### ISSUE TITLE
Lower half of chart flickering on bar chart race

### ISSUE THREAD

**Issue by multinerd** [amcharts/amcharts4#3790]
**Question**

I am trying to implement the bar race chart.

I copy pasted the code from the website docs and replace the data with my own and some minor changes to the label.
The issue I am having is that the lower half of the chart glitches out and some of the names are overlapping.

https://jsfiddle.net/multinerd/agesz4f7/

**Environment (if applicable)**

 - amCharts v4 from CDN
 - firefox 93
 - vanilla js

**Comment by martynasma** [comment]
Well, you're updating chart data every 10ms but still have Animated theme enabled that enables bar move animations that take like a whole second, hence all the mess.

If you need to update the dat that often, I suggest you lose the Animated theme altogether.

**Comment by multinerd** [comment]
Thank you for the response. 

Disabling the animation fixes the flickering but 2 of the bars are overlapping.

**Comment by multinerd** [comment]
Disregard the issue with overlap. looks like its an issue with my `salesmanName` values. Swapping it to `salesman` got rid of the overlap.
