### ISSUE TITLE
How to customize the color of text and lines?

### ISSUE THREAD

**Issue by mqyun-zoe** [amcharts/amcharts4#3794]
**Question**
![image](https://user-images.githubusercontent.com/87847555/134801639-e36ad082-973d-4de4-8ead-cebcc0373200.png)

https://codepen.io/mqyun/pen/dyRQPVV

How to customize the color of text and lines?

**Comment by martynasma** [comment]
```JavaScript
pieSeries.labels.template.fill = am4core.color("#f00");
pieSeries.ticks.template.stroke = am4core.color("#f00");
```

**Comment by mqyun-zoe** [comment]
> ```js
> pieSeries.labels.template.fill = am4core.color("#f00");
> pieSeries.ticks.template.stroke = am4core.color("#f00");
> ```

How to set different colors for each part？

**Comment by martynasma** [comment]
You can use property fields:
https://www.amcharts.com/docs/v4/concepts/data/#Property_fields
