### ISSUE TITLE
axis range positioning offset

### ISSUE THREAD

**Issue by NilsJacobsen** [amcharts/amcharts4#3795]
Hey together,

I want to get a date marker on a specific date. I used axis range without end date. I used 

```
dateAxis.renderer.labels.template.location = 0.5;
dateAxis.renderer.grid.template.location = 0.5;
```

to get rid of the offset with the normal series but now I have the offset between the actually date and the marker. 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/58360188/134904757-8cbdae7e-71bb-4aa8-85a8-30e2fd27e329.png">
Have you any idea of how to solve this?
I think there should be a solution for the location of axis range but I did not find it.
Thanks for your help.

**Comment by martynasma** [comment]
Actual data item is centered within the period, e.g. data, whereas axis range is is placed at exact timestamp.

Option #1: Set time for the range date to mid-day.

Option #2: Move data items to the beginning of the period/day:
https://www.amcharts.com/docs/v4/concepts/series/#Data_item_locations

**Comment by NilsJacobsen** [comment]
thanks for the quick answer @martynasma option #1 worked for me
