### ISSUE TITLE
Problem with combined tooltip text when group data

### ISSUE THREAD

**Issue by Sam9913** [amcharts/amcharts4#3796]
**Question**
I want to show sum of data with groupInterval of {timeUnit: "month", count: 1}, but it keep giving me the original valueY of the index. I have already read about https://www.amcharts.com/docs/v4/tutorials/multi-series-shared-tooltip-with-colored-bullets/ and this https://github.com/amcharts/amcharts4/issues/1813 but I still facing the problem. 

I have attached the sample below.
https://codepen.io/sam9913/pen/MWoZOLq

**Environment**
 - amCharts version: Latest
 - Browser and its version: Chrome 93.0.4577.82

**Comment by martynasma** [comment]
Your data is out of order. It needs to be sorted in ascending order for it to work properly.

**Comment by Sam9913** [comment]
> Your data is out of order. It needs to be sorted in ascending order for it to work properly.

Thanks for your reply, I have tried and update the codepen data in ascending order but still the same. The tooltip is not showing the sum of the data.

**Comment by martynasma** [comment]
Try this:

```
text += "[" + item.stroke.hex + "]●[/] " + item.name + ": " + item.tooltipDataItem.values.valueY.sum + "\n";
```
