### ISSUE TITLE
Custom zoom in & zoom out buttons

### ISSUE THREAD

**Issue by chiraggirdhar** [amcharts/amcharts4#3798]
I want to implement Custom Zoom in & Zoom out button outside of Am Chart Component.

I'm already using this functionality by using the "+" and "-" buttons.
https://codepen.io/team/amcharts/pen/YgjOop

How to trigger the same functionality from outside buttons.

**Comment by martynasma** [comment]
You can attach the same click handler code you have on built-in buttons, to some external buttons, e.g.:

```JavaScript
document.getElementById("plus").addEventListener("click", function() {
  var diff = dateAxis.maxZoomed - dateAxis.minZoomed;
  var delta = diff * 0.2;
  dateAxis.zoomToDates(new Date(dateAxis.minZoomed - delta), new Date(dateAxis.maxZoomed + delta));
});
```
