### ISSUE TITLE
Question : How to disable serial chart zoom ?

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#380]
Hello !

How to disable serial chart zoom ?

I would like to disable it on mobile phone but keep touch events for cursor ?

I did not find in the documentation.

Thanks for help !

**Comment by martynasma** [comment]
Setting cursor's `behavior` to `"panX"` or `"none"` should do the trick.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by ptorrent** [comment]
Hello,

I'm not sure to see where i should put this parameter ?

**Comment by martynasma** [comment]
```
chart.cursor.behavior = "none";
```
