### ISSUE TITLE
Maps license with amcharts4 license?

### ISSUE THREAD

**Issue by abelardolg** [amcharts/amcharts4#3801]
Hi there,

I wonder if Amcharts4 license is applied to Maps too or the latter needs another license.

Thanks. Best regards.

**Comment by martynasma** [comment]
Maps is an add-on that requires own license. Charts license does not extend to Maps.

So, to use Maps, you need a license for Charts and Maps.

**Comment by abelardolg** [comment]
I have just this text. Sorry for asking this question.

![image](https://user-images.githubusercontent.com/22522883/135449035-d4f39dd4-99ce-433d-81f9-6bf4736e0764.png)

**Comment by martynasma** [comment]
No worries!
