### ISSUE TITLE
Map > heatLegend > reverse property?

### ISSUE THREAD

**Issue by abelardovn** [amcharts/amcharts4#3802]
Hi there,

I have not seen at doc if a "reverse" property exists in heat legends. 
By default, the min value is located at the left side and the max value at the right one.

How could I "reverse" this order, please? 

Thanks in advance. Best regards.

**Comment by martynasma** [comment]
Try this:

```JavaScript
heatLegend.reverseOrder = true;
```

**Comment by abelardolg** [comment]
For a strange reason, when I wrote that sentence, my legend disappeared.
![image](https://user-images.githubusercontent.com/22522883/135472343-a704f4dc-b547-4202-acad-4def0d29dc47.png)

Missing legend when reverseOrder is set to true:
![image](https://user-images.githubusercontent.com/22522883/135472447-132c5cf8-caa8-423d-8418-2867fca67520.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by martynasma** [comment]
Here's a simple map with reversed HeatLegend:
https://codepen.io/team/amcharts/pen/76171193c60d183993b52a0ed1ebb67f?editors=0010

It's working in this scenario, which makes me think that the issue is only wit particular setup, hence asking for a CodePen.

**Comment by abelardovn** [comment]
Hi there,
Yes, it was solved with not touching the code.
Thanks in advance! Best regards.
