### ISSUE TITLE
Map > heatLegend > Three colors to represent several range values

### ISSUE THREAD

**Issue by abelardovn** [amcharts/amcharts4#3803]
I have seen at doc this entry:
![image](https://user-images.githubusercontent.com/87799097/135461936-edd94ce5-9ef4-49a2-806f-854b25f2166a.png)
to assign a color to a value. 

For example, I would like to show this heat legend:
![image](https://user-images.githubusercontent.com/87799097/135461748-4e24085b-77db-4c54-b52d-bc1f62146c3f.png)

My data vary between 1.25 and -1.25. Each country has a value and a color according to that value.

For example, for Spain I have this value and this color:
![image](https://user-images.githubusercontent.com/87799097/135462245-f96f574c-ec45-4020-9322-3d155786168b.png)

And the heat legend object, I set its "configField" property to "config", which is the name of the field in each data...but it doesn't work.
![image](https://user-images.githubusercontent.com/87799097/135462660-a1316af9-e168-411b-a716-28243353f1b2.png)

Is it a bug or I am doing something wrong? 

Could you help me with this issue, please?

Best regards.

**Comment by martynasma** [comment]
There's no way to have a `HeatLegend` with custom multiple color values.

The only way is to have a normal `Legend` with custom values:
https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items

**Comment by abelardolg** [comment]
I think I can't close this issue. I don't the "close issue" option. Best regards.
