### ISSUE TITLE
stacked chart missing values take empty spaces 

### ISSUE THREAD

**Issue by manushakaru** [amcharts/amcharts4#3804]
**Question**

when creating a stacked chart, if category value is missing for one category then it will take empty space for that in the next column. I used angular 11 and amcharts 4. Here is a [codepen ](https://codepen.io/manushakaru-the-selector/pen/mdmEGJd?editors=1010) for the issue. 

**Environment (if applicable)**
Angular 11
Amcharts 4

**Additional context**
![data missing](https://user-images.githubusercontent.com/36305124/135515815-f2b6025b-5baa-4a9d-84f1-4f294f0179ec.PNG)

**Comment by martynasma** [comment]
In amCharts, for stacked series to work properly, they need to have equal number of data items.

In your case each series has different number of those, hence the anomaly.

To fix it, there are two options:

1) Use one central `chart.data` for everything, with keys omitted for categories there are no value for.
2) Make sure that each individual series data has same amount of data items.

```
var data = [
  {
  "label":"x",
  "data":[
    {"label":"a","value":113},      
    {"label":"b","value":2001},
    {"label":"c","value":4636},
     {"label":"d","value":49},
    {"label":"e","value":5133}
    ]
  },
  {
  "label":"y",
  "data":[
    {"label":"a","value":113},      
    {"label":"b","value":2001},
    {"label":"c"},
    {"label":"d","value":49},
    {"label":"e","value":5133}
    ]
  },
  {
  "label":"z",
  "data":[
    {"label":"a","value":12},      
    {"label":"b","value":12},
    {"label":"c","value":21},
    {"label":"d","value":49},
    {"label":"e","value":21}
    ]
  }           
 ];
```

**Comment by manushakaru** [comment]
@martynasma thank you for your reply. I have solved it introducing zero values for missing fields as you mentioned in the  second option. Thanks a lot.
