### ISSUE TITLE
Maps > series data > how to assign a fill to each value

### ISSUE THREAD

**Issue by abelardolg** [amcharts/amcharts4#3805]
Hi there,

I created a legend and set it several objects with "fill" property set to a color to its data property:
![image](https://user-images.githubusercontent.com/22522883/135603023-11c12c82-e84a-4e4c-abc3-a7dfd31822d4.png)

My idea is to independently assign to each country one of these colors:
![image](https://user-images.githubusercontent.com/22522883/135603127-7f56d433-42e1-4804-a536-5324b81a7122.png)

I wonder if this could be done.
The problem here is that series only admit "min" and "max" and it calculates the range of colors according a logarithmic in our case.

Thanks.

**Comment by martynasma** [comment]
You can use `propertyFields` for that:

https://www.amcharts.com/docs/v4/chart-types/map/#Binding_properties_to_data
