### ISSUE TITLE
Legends | placing labels on both sides

### ISSUE THREAD

**Issue by abelardolg** [amcharts/amcharts4#3807]
Hi there,

Since a basic legend by itself doesn't contain a range of values (heatLegend has an associated range of values), I couldn't follow the example of this link:  https://www.amcharts.com/docs/v4/tutorials/map-heat-legend-with-real-start-end-value-labels/

My goal is to reach this one where "+1,25" and "-1,25" labels are placed at beginning and the end of my legend:
![image](https://user-images.githubusercontent.com/22522883/135857047-e64d57e1-cae1-4c17-bace-f37d07d36b0b.png)

Have I to dive into its html elements and get it by accessing to their first:child and last:child elements along with before and after css directives?

Best regards.

**Comment by martynasma** [comment]
Yes, I would think that at this point it's better to create a separate `Container` with 2 `Label` elements and 7 `Rectangle` elements.
