### ISSUE TITLE
How to dynamically resize images based on visible bar counts

### ISSUE THREAD

**Issue by multinerd** [amcharts/amcharts4#3808]
**Question**

Using a bar race chart with an image, how can I dynamically resize the image to match with the size of the bar. 

For example, when there is few data points, the image is tiny compared to the bar size.
![image](https://user-images.githubusercontent.com/6367998/135920414-78d46e32-15c1-4d9a-b279-18f9ba62bffb.png)

And when there is a lot of data points, the image remains the same.
![image](https://user-images.githubusercontent.com/6367998/135920531-30c34ce2-b492-4c25-b835-ec266fe22480.png)

This would be my expected output:

![image](https://user-images.githubusercontent.com/6367998/135921356-2e67dc95-6742-448d-a1c8-78a826d87b6d.png)
![image](https://user-images.githubusercontent.com/6367998/135921215-928f9674-2514-492a-8209-fb040f73741d.png)

**Environment (if applicable)**

Provide details about your development environment where you think it might be useful. E.g.:

 - amCharts version: 4 (https://cdn.amcharts.com/lib/4/core.js)
 - Browser and its version: Firefox 93b9

**Comment by martynasma** [comment]
Are you using `LabelBullet` with HTML as a label? I'm not sure if `scale` will work on it properly.

In any case, I'd use the `Image` as a bullet as per example.

**Comment by multinerd** [comment]
I am not 100% sure what your asking but I believe the answer is no. This is how i had it set up:

```html
            let labelBullet = series.bullets.push(new am4charts.LabelBullet())
            labelBullet.label.horizontalCenter = "left";
            labelBullet.label.text = "{values.valueX.workingValue.formatNumber('#,###.')}";
            labelBullet.label.textAlign = "start";
            labelBullet.label.dx = 40;

            let image = labelBullet.createChild(am4core.Image);
            image.horizontalCenter = "center";
            image.verticalCenter = "bottom";
            image.dx = -20;
            image.dy = 15;
            image.y = am4core.percent(100);
            image.propertyFields.href = "avatar";
            image.tooltipText = series.columns.template.tooltipText;
            image.filters.push(new am4core.DropShadowFilter());
```

I am going to try what you have in the demo you provided and then try to re-add the label after.
