### ISSUE TITLE
Setting Adapter Priorities

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#381]
Hello,

I am using adapters to provide text to a labelBullet and to position it i.e. setting its vertical and horizontal centers.

Though I am prioritizing the text adapter as the 1st one and adapter setting horizontal and vertical centers as 2nd one, it is throwing an error as the dataItem values of label are not defined as it is not setting the label text first. 

Is there anyway to achieve this?

Example:
 labelBullet.label.adapter.add('text', (text, target) => someOtherMethod(text, target), 1);

 labelBullet.label.adapter.add('verticalCenter', (center, target) => {
     const values = target.dataItem.values;  //  => undefined
     // some code
    }, 2);
    labelBullet.label.adapter.add('horizontalCenter', (center, target) => {
     const values = target.dataItem.values;  //  => undefined
      // some code
    }, 2);

**Comment by martynasma** [comment]
Hm, it is only possible to set priorities/order for adapters of the same key. E.g. you have several adapters set on "text". But it's not possible to modify the order of **when** adapter is applied.

That said, all adapters for a bullet should contain `dataItem`.

Take a look here:
https://codepen.io/team/amcharts/pen/ce384fa175e80fa9c27460ff4e898c3c/

I get values on both "text" and "vertical" center adapters.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
