### ISSUE TITLE
How to limit number of columns displayed in HeatMap table?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3812]
I have a heat map table in which there are many columns. Due to many number of columns it's not looking good. Is there a way to limit number of columns to be displayed by default and we can use a scroll bar to see remaining columns.

columns in my heat map table are like below
![Screenshot from 2021-10-06 10-20-09](https://user-images.githubusercontent.com/74599304/136143197-f39bc314-c0d3-48b4-b13e-65771928737e.png)

Like in the case of below grouped chart we are limiting number of bars display by default. could it be possible in the case of heat map to limit no.of columns.
![Screenshot from 2021-10-06 10-32-36](https://user-images.githubusercontent.com/74599304/136143522-53299f47-fe99-4a7a-81f3-005209e71883.png)

**Comment by martynasma** [comment]
Yes, you can add `maxZoomCount` to your CategoryAxis:
https://www.amcharts.com/docs/v4/reference/component/#maxZoomCount_property

Also add scrollbar to your chart:
https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Scrollbars

**Comment by martynasma** [comment]
Those are unmasked bullets.

You can fix it by removing this line of code:

```
// Remove this
chart.maskBullets = false;
```
