### ISSUE TITLE
how to centralise a vertical line in bar chart

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts4#3815]
**Question**

Hi, I have 2 questions regarding adding a vertical red line in a bar chart:

1. I cannot get it centralised in the date column, how can I fix it?
2. I want to add an icon or just an "i" letter at the top of the vertical line (as shown in the screenshot), but I couldn't find a way but to use a label, is there a better way to do it? with the label, I also couldn't put it on the top of the line without changing all the dates label with it!

![Screenshot 2021-10-06 at 12 56 21](https://user-images.githubusercontent.com/8130692/136189991-f2f4d347-eb99-4e35-b30d-38d59504c41f.png)

```ts
const trendLine = xAxis.axisRanges.create();
trendLine.date = new Date(2021, 0, 2);
trendLine.grid.stroke = am4core.color('#D0021B');
trendLine.grid.strokeWidth = 2;
trendLine.grid.strokeOpacity = 1;
trendLine.grid.strokeDasharray = '4,4';
trendLine.label.html = '<span style="display: flex; align-items: center; justify-content: center; font-weight: bold;width: 20px; height: 20px; background: red; border-radius: 50%;color: white">i</span>';
trendLine.label.inside = true;
```

Here is a reproduction https://codesandbox.io/s/hardcore-booth-0ju9z?file=/src/app/app.component.ts

**Environment (if applicable)**

 - amCharts: 4.10.22
 - Angular 12

**Comment by martynasma** [comment]
1) Axis range is placed exactly at the timestamp you have set date for - beginning of the day, whereas column is centered within the day.

To fix you can just set time to noon:

```JavaScript
trendLine.date = new Date(2021, 0, 2, 12);
```

2) This should do the trick:

```JavaScript
trendLine.label.valign = "top";
trendLine.label.dy = -30;
```
