### ISSUE TITLE
color for pie

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3824]
Hi 

I'm attaching an [example](https://codepen.io/meghanananuvala/pen/MWvgrEK?editors=0010), in that when we click on slice of first pie will get draw another pie.

But whenever i first click the slice the color of first slice is not setting for another pie which is created, but other times it is setting properly.

![Screenshot from 2021-10-12 13-02-48](https://user-images.githubusercontent.com/71019344/136911852-a04b3993-cc11-4fbd-afd7-0a49bff89efc.png)
My first click is red slice in  1st pie then i got blue shade pie, but i want that too be in red only.

Do let me know how to overcome this.

Thank you.

**Comment by xorspark** [comment]
Assuming you're using a propertyField for your larger pie's slice colors, move the chart2.data assignment before the count assignment so that the color list gets populated correctly on the first click:

```
  var fill = /* ... */;

  chart2.data = [
  {"2x":"Mag","2y":13550},
  {"2x":"Sam","2y":8194},
  {"2x":"Niha","2y":268045},
  {"2x":"Fiserv","2y":1666},
  {"2x":"Genesis","2y":15597},
  {"2x":"pallavi-CDF","2y":6092},
];
  var count = chart2.data.length;
  pieSeries2.colors.list = [];
  for (var i = 0; i < count; i++) {
    pieSeries2.colors.list.push(fill.brighten(i * 2 / count));
  }

  pieSeries2.appear();
```

[Codepen](https://codepen.io/team/amcharts/pen/a945611c1616b6d061d8b9c5aeff5e60?editors=0010)
