### ISSUE TITLE
Amcharts 4 EventDispatcher is disposed error

### ISSUE THREAD

**Issue by IsaUgurchiev** [amcharts/amcharts4#3826]
When I dispose chart and then create chart again I got "EventDispatcher is disposed"

https://codepen.io/IsaNesquik/pen/yLoNjOq

Why if I move const CONFIG from create function scope to global scope, chart doesn't recreate?

**Comment by xorspark** [comment]
Your clone function doesn't deep clone the original object very well, so there's still references from the first chart that are leftover in your config object. Using a more thorough clone implementation, such as the one  from [this stackoverflow answer](https://stackoverflow.com/a/4460624), will fix the issue.

[Updated codepen](https://codepen.io/team/amcharts/pen/59b31d234d03842138f325340ab2a847?editors=0010)
