### ISSUE TITLE
Certain adapters don't seem to re-fire on data update

### ISSUE THREAD

**Issue by geoffreyrichey** [amcharts/amcharts4#3827]
I have an XYChart with a LineSeries using DateAxis and ValueAxis.

What I'm trying to achieve is to style the dateAxis labels individually based on logic that requires me to reference the series data. Since DateAxis labels don't inherit the dataContext object I tried using adapters which works perfectly on initial render but when I replace the chart data with a new range of data to display only the **text** adapter fires again but the **fill** adapter does not.

```
const dateAxis = chart.xAxes.push(new am4charts.DateAxis())
const labelTemplate = dateAxis.renderer.labels.template

const getDataItem = (target) => {
     if (!target.dataItem?.date) return
    return this.series.dataItems.values.find(o => o.dataContext.date.getTime() === target.dataItem.date.getTime())
}

labelTemplate.adapter.add('text', (text, target) => {

   console.log('This log shows on both initial chart render AND when data is updated')

   const seriesDataItem = getDataItem(target)

    // ... Some logic here to determine text label based on dataItem.dataContext

    return text
})

labelTemplate.adapter.add('fill', (fill, target) => {

    console.log('This log only shows on initial chart render but NOT after data is updated')

    const seriesDataItem = getDataItem(target)

    // ... Some logic here to determine label fill based on dataItem.dataContext

    return fill
})

```

Is this just a limitation to specific adapter property types or is there a way to trigger them manually when data is updated? Also is this the best approach?

**Environment (if applicable)**
"@amcharts/amcharts4": "^4.10.22"

**Comment by martynasma** [comment]
Well, labels are reused for performance reason, which means they do not get fully repainted and thus adapters not fire.

What you can do is to force all labels to be repainted after data update on your date axis:

```JavaScript
dateAxis.events.on("datavalidated", function(ev) {
  ev.target.invalidateLabels();
});
```
