### ISSUE TITLE
MAP chart disappeared after enter map chart page for a second

### ISSUE THREAD

**Issue by xpliu01** [amcharts/amcharts4#3828]
**Bug description**
`  
...
this.imageSeries = this.map.series.push(new am4maps.MapImageSeries());
const imageSeriesTemplate = this.imageSeries.mapImages.template;
imageSeriesTemplate.propertyFields.latitude = 'latitude';
imageSeriesTemplate.propertyFields.longitude = 'longitude';
this.imageSeries.data = [{latitude: ...,  longitude:..., ... }, ...]
this.imageSeries.validateData();
...
`

I was using the amchart map, when I entered in the map page, the map city point was normal for one second then the map chart city point moved into the corner of up left quickly, this is the chrome action.

fixfox action is that: 
 when I entered in the map page, the map city point was normal for one second then the map chart will disappeared and show error "ERROR TypeError: SVGMatrix.a setter: Value being assigned is not a finite floating-point" in the page.

**Environment (if applicable)**
amCharts "version": "4.10.22",
amcharts4-geodata": "^4.1.16
Browser chrome(94.0) and firefox(92.0.1)
Angular Version   "@angular/core": "11.2.6",
Type Script    "version": "4.1.5",

**Additional context**
Firefox:
<img width="1248" alt="Screen Shot 2021-10-14 at 15 37 45" src="https://user-images.githubusercontent.com/13335133/137272802-300a231a-5729-468a-a77b-e23dd6e12d34.png">

Chrome:
<img width="731" alt="Screen Shot 2021-10-14 at 15 38 10" src="https://user-images.githubusercontent.com/13335133/137272816-98ebfe3b-a5df-436c-81c4-944b982b84b8.png">

JS Error console log:
TypeError: SVGMatrix.a setter: Value being assigned is not a finite floating-point value.
    measure https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    validatePosition https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    validatePosition https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    _systemValidatePositions https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    _systemValidatePositions https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    validatePositions https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    update https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    u https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    c https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    u https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    update https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    requestFrame https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    0 https://admin.webex.com/polyfills.7154a0e27e07b3261291.js:1
    invokeTask https://admin.webex.com/polyfills.7154a0e27e07b3261291.js:1
    onInvokeTask https://admin.webex.com/vendor.6a7ad7a4cb6e9a75beec.js:1
    invokeTask https://admin.webex.com/polyfills.7154a0e27e07b3261291.js:1
    runTask https://admin.webex.com/polyfills.7154a0e27e07b3261291.js:1
    invokeTask https://admin.webex.com/polyfills.7154a0e27e07b3261291.js:1
    invoke https://admin.webex.com/polyfills.7154a0e27e07b3261291.js:1
    0 https://admin.webex.com/polyfills.7154a0e27e07b3261291.js:1
vendor.6a7ad7a4cb6e9a75beec.js:1:5978839

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by xpliu01** [comment]
I'm afraid that it's inconvenience to post codes into the out website. this is a strange issue, we can't reproduce this issue in my local but it has this issue in our some customer's browsers. could you help point out which cause scope may cause this JS error in amchart-map?
