### ISSUE TITLE
AmChart scrollbar thumb goes to the end..?

### ISSUE THREAD

**Issue by Shussain011** [amcharts/amcharts4#3833]
**Question**

**Environment (if applicable)**

**Additional context**
I have a question how to set the scrollbar position dynamically according to the given data. In this case I didn't give the position to scrollbar but scrollbar thumb goes to the end don't know why.
![11](https://user-images.githubusercontent.com/89525118/137672912-eb20fd10-a507-4aac-a90d-6952117eb1e3.PNG)

**Comment by martynasma** [comment]
Do you perhaps have `maxZoomCount` set on your axis?

**Comment by Shussain011** [comment]
Yes I used maxZoomCount = 10 @martynasma

**Comment by martynasma** [comment]
Well, there you go. It means that it allows a maximum 10 dates to be shown at a time, hence it being pre-zoomed.

**Comment by Shussain011** [comment]
https://stackblitz.com/edit/react-mlipbe?file=src%2FDragableChart.jsx

here is the link but I used another chart its also a column chart and same issue with it scrollbar goes to anywhere or to the end.

in that chart first you have to select start and end data and number of emails 40 or 50 then chart render.

**Comment by martynasma** [comment]
I'm not seeing any events on chart that can be used for pre-zooming as per tutorial suggestion before in your StackBlitz.

**Comment by Shussain011** [comment]
I apply categoryAxis.maxZoomCount = 10; this on chart.

**Comment by martynasma** [comment]
Yes, but did you try the suggestions in this tutorial?
https://www.amcharts.com/docs/v4/tutorials/pre-zooming-an-axis/
