### ISSUE TITLE
Label(HTML template) is not working with CategoryAxis while export to options like JPG  or PNG

### ISSUE THREAD

**Issue by swapnilh-cognologix** [amcharts/amcharts4#3834]
**Bug description**

Step 1 - Try to export the XYChart with the categoryAxis label html template configuration
`categoryAxis.renderer.labels.template.html = '<div>Test Label</div>';`

Step 2 - Export the chart with PNG or JPG,, for sometime the labels are not visible until the export is completed
Expected Result: The labels(html template) should rendered in the Exported file.
Actual Result: The labels are not rendered in the Exported file.

Working fine without html label template configuration.

https://codepen.io/swapnilh-cognologix/pen/GRvZmRN

**Comment by martynasma** [comment]
> Thanks @xorspark, Just curious if we going to support this in near future?

No. Impossible to reliably convert HTML content into canvas/bitmap on clientside.
