### ISSUE TITLE
How to resize a Heatmap Table ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3837]
I have two different heat maps like below
![Screenshot from 2021-10-19 11-06-13](https://user-images.githubusercontent.com/74599304/137850150-f2de6748-2f9a-47be-907e-cae581a4ed9f.png)
I want to have size of second heat map table as first one.

**Comment by martynasma** [comment]
I don't see any events from the tutorial I linked to in your code. Would you mind trying to add those in?

**Comment by martynasma** [comment]
This works for me:
https://codepen.io/team/amcharts/pen/3bdcfe70ed4f2a1175585ebd8dd87f2a?editors=0010

**Comment by VineelaKantamneni** [comment]
Thank you and I want size of cell in second heat map as the size of the cell in first heat map
![Screenshot from 2021-10-21 12-27-17](https://user-images.githubusercontent.com/74599304/138227058-dbacaffb-1150-432f-866c-19463f5035a4.png)

**Comment by martynasma** [comment]
For that you will need to modify height of the second chart accordingly.

If you have same number of rows for both of the charts, you can find and hardcode height values.

If the number of rows is variable, you can follow this tutorial for applying height dynamically for target column height:
https://www.amcharts.com/docs/v4/tutorials/auto-adjusting-chart-height-based-on-a-number-of-data-items/

**Comment by VineelaKantamneni** [comment]
Thank you.
![Screenshot from 2021-10-21 18-15-59](https://user-images.githubusercontent.com/74599304/138280758-6d973146-b1cd-4ffe-a067-58337041e91c.png)
In the image there is a space between label "Total" and heat map. How to reduce it.

**Comment by martynasma** [comment]
Hm, sorry. This will work:

```
yAxis2.renderer.width = am4core.percent(100);
```

**Comment by VineelaKantamneni** [comment]
It's working. Thank you :)
