### ISSUE TITLE
locationY and locationX act weird on a bullet with series on a vertical CategoryAxis

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#384]
Seems like `locationX` affects both vertical and horizontal position of the bullet, while `locationY` does not seem to have any effect whatsoever.

Example:
https://codepen.io/team/amcharts/pen/af39dc7bfefcd3ed74cefe2b7d9d0cff?editors=0010

**Comment by zeroin** [comment]
This is fixed.
