### ISSUE TITLE
amchart persianDate

### ISSUE THREAD

**Issue by morteza-haghighat** [amcharts/amcharts4#3848]
below topic show the best way to use persian date for amchart
https://github.com/amcharts/amcharts3/issues/181
but using that way are difficult because some timeline charts changing date and you can't get whole the date to convert to persian
for example in
Horizontal Serpentine chart in amchart
https://www.amcharts.com/demos/horizontal-serpentine-chart/
you can't convert Nov 2 or ... to persian date because doesn't have year

Thanks

**Comment by rkamely** [comment]
for tooltip:
dateAxis.adapter.add("getTooltipText", function(text){
  return new Date(text).toLocaleDateString('fa-IR')
})

for label:
dateAxis.renderer.labels.template.adapter.add("text", function(text) {
  return  new Date(text).toLocaleDateString('fa-IR');
});
