### ISSUE TITLE
Cannot read property 'undefined' of undefined when loops present in Sankey diagram

### ISSUE THREAD

**Issue by lukecmstevens** [amcharts/amcharts4#385]
When trying to create a simple sankey diagram using the example [codepen](https://codepen.io/team/amcharts/pen/MGvRaE) I'm getting an error whenever I try and add a simple loop to the sankey diagram `Cannot read property 'undefined' of undefined`.

The only change to the linked codepen I've changed is the last line of the `chart.data` array to;
`{ "from": "H", "to": "A", "value": 9 }`

Will this problem with loops be fixed in the future?

**Comment by martynasma** [comment]
Currently Sankey does not support links going backwards, which your data implies.

I'm not entirely sure if this would be correct from the logical perspective, and whether it is in fact what you are trying to achieve. This type of diagram is meant to depict flows and segregation. Having circular loops would be very confusing.

if you are not trying to achieve loop back to "A", then I suggest naming your target node differently, like "A1".

We'll ping you here when we have a chance to discuss whether this can be addressed in any meaningful way.

Updated example with the issue:
https://codepen.io/team/amcharts/pen/4483d10b09fa5cc021a94be4d1678202/

**Comment by lukecmstevens** [comment]
What I'm trying to achieve is a diagram like [this](https://en.wikipedia.org/wiki/Sankey_diagram#/media/File:Sankeysteam.png) where at a certain node a percent of the flow is returned to the beginning (e.g. power returned to a system, waste being recycled). The original change to the codepen was just the simplest change I could make to demonstrate the issue. Hope this clarifies things a little.

**Comment by martynasma** [comment]
Yup, makes sense. Thanks!

We'll consider implementing this.

**Comment by martynasma** [comment]
We reached a decision not to implement this feature. Sorry.
