### ISSUE TITLE
Category Axis labeling overlapping chart

### ISSUE THREAD

**Issue by OvidiuBan** [amcharts/amcharts4#3858]
The category axis seems to somehow depend on the environment (which other components are on the page and how big they are), because on two different tabs, two different charts react differently.

Even if they are populated with the same data, the result is different.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/11694812/139194597-8966855f-4502-482c-8869-1ab043f60f17.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/11694812/139194603-cec80f02-4f47-4fa1-96bd-bfffd00d1ceb.png)

 - amCharts version 4.10.21
 - Google Chrome version 95.0.4638.54
 - React version 16.14.0

**Comment by OvidiuBan** [comment]
@martynasma I have tried to recreate it but it looks so different even with the same values. 

The labeling issue happens when this would be updated. Any kind of update.

https://jsfiddle.net/OvidiuBan/kqudLa7o/11/

**Comment by martynasma** [comment]
The labels look fine to me in your jsFiddle:

![image](https://user-images.githubusercontent.com/1458520/140957422-016f83ab-eabd-4fbd-b1f9-088f37dc5b5a.png)

What am I missing?

**Comment by OvidiuBan** [comment]
The initial labels look fine yes, the problem is that whenever the props change, the data is being updated and after this the labeling issue appear. 

I'm using a react useEffect handle which updates the chart data.

**Comment by martynasma** [comment]
How do I trigger that?

**Comment by OvidiuBan** [comment]
Basically you just have to update your chart data async. I can try to make a fiddle with react but i am not experienced very well with the js fiddle. I've tried to show you the data format

**Comment by martynasma** [comment]
I'm afraid I'll need some repro case.

I tried updating the data for the chart dynamically, and there was no issues with axis labels.

**Comment by OvidiuBan** [comment]
I have managed to reproduce it here: 

https://codesandbox.io/s/musing-hawking-yjqu7
Steps to reproduce
1) Open in new window
2) Move to the other tab [Update Chart]
3) Click on button
4) Go back to previous tab and look at chart

**Comment by martynasma** [comment]
Thanks.

Since data updating happens while chart is invisible and thus has zero dimensions, updated labels are not positioned properly.

To fix that, simply manually invalidate axis labels after data is updated:

```JavaScript
chartRef.yAxes.getIndex(0).invalidateLabels();
```

**Comment by OvidiuBan** [comment]
Sadly the issue seems to reproduce even with that invalidate.

Updated the sandbox. Am i using it wrong? 

https://codesandbox.io/s/musing-hawking-yjqu7?file=/src/component.tsx

**Comment by martynasma** [comment]
There you go:
https://codesandbox.io/s/priceless-lamarr-0b96v

**Comment by martynasma** [comment]
Wait no, it does not seem to work every time.

In such case, you may need to call that line when tab is switched. I'm sure there are events for that.

**Comment by OvidiuBan** [comment]
That does work, but i guess that the chart should retain the original dimensions even if it is invisible, as it does not get created again. Thank you for the solution.
