### ISSUE TITLE
Using AJAX to display large amount of data with granularity based on zoom level?

### ISSUE THREAD

**Issue by SparkyTD** [amcharts/amcharts4#3863]
I am building a front-end for a data-logging IoT project. Data is collected each second, over a very long timespan, so if I want to display the graph of a month for example, I'd have to pull ~2.5M datapoints from the server. To optimize this, it would be enough to load the data with the granularity based on the current zoom level. So with my example, if the user wants to load the graph of a month, only every hour is requested through AJAX. If the user zooms in on a day, the granularity could increase to every minute.

To implement this, amcharts would have to include zoom information in the AJAX requests, and it would need to update every time the user changes the zoom level.

What is the easiest way of implementing this in amcharts 4?

To get started, I've tried using the `selectionextremeschanged` event to listen to zoom changes, but that fires on every "frame" for the zooming animation. I would need an event that firs only once, after the zoom is completed.

**Comment by martynasma** [comment]
> To get started, I've tried using the selectionextremeschanged event to listen to zoom changes, but that fires on every "frame" for the zooming animation. I would need an event that firs only once, after the zoom is completed.

How about "startendchanged" on your axis?

```JavaScript
dateAxis.events.on("startendchanged", function(){
  var start = Math.floor(dateAxis.start * chart.data.length);
  var end = Math.ceil(dateAxis.end * chart.data.length);
  // ...
})
```
