### ISSUE TITLE
How to auto adjust the width of the chart

### ISSUE THREAD

**Issue by Woonhian** [amcharts/amcharts4#3864]
**Question**
I have a chart where the Y-Axis will have short name labels and long name labels.
Initially when my chart loads with short name label on the Y-Axis, it looks ok:
![Stream Activity Chart (2)](https://user-images.githubusercontent.com/35731563/139591600-5f680666-292d-4fdb-bf24-38aaa7fc057e.png)
After that when I update the chart with long name labels on the Y-Axis, it looks ok too:
![Stream Activity Chart (3)](https://user-images.githubusercontent.com/35731563/139591625-098715f7-f73d-4a76-845a-eefb6c3f856f.png)

However, when I update the chart again back to short name label, the width of the chart seems to be adjusted based on the long name labels previously.
![Stream Activity Chart (4)](https://user-images.githubusercontent.com/35731563/139591674-8ace37bd-81ee-40e5-a856-025324df05c4.png)

How can I ensure that the width of the chart is 100%? I've set chart.responsive.enabled = true; but I can't seem to get the chart to auto-adjust the width.

Thanks in advance!

Here is a similar codepen I'm attaching here: https://codepen.io/woonhian-the-bold/pen/wvqrrOE
Data Set 1 looks ok when 1st loaded, however when it is changed to set 2 and back to 1, the width of the chart for set 1 changed.

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
See solution here: https://github.com/amcharts/amcharts4/issues/3035
