### ISSUE TITLE
Updating charts data is extremely slow!

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts4#3865]
**Bug description**

I am using stacked bar chart (ColumnSeries).

Changing the data of the chart is extremely slow knowing that I am passing a small amount of data (80 records) and I am using the timestamp for the dates to avoid parsing them. 

When I change the data, I only use the following line:
```ts
this.chart.data = this.data;
```

`[Violation] 'requestAnimationFrame' handler took 4819ms`

It works but it is extremely slow, can you explain why? and is there a solution to this issue?

I also noticed that destroying the chart and reinitialise it again with the data is even faster!!!

**Environment (if applicable)**

 - amCharts 4
 - Angular 12

**Comment by martynasma** [comment]
Wow, I'm not sure how 80-record data could take 5 seconds to parse.

Would you be able to share your chart setup on CodePen/jsFiddle so that we can take a look?
