### ISSUE TITLE
maxHeight for SankeyNode not working. 

### ISSUE THREAD

**Issue by Roosvicee** [amcharts/amcharts4#3866]
I am trying to create a Sankey chart with links and nodes that have a fixed size. Currently, the links are fixed by using the following code:

`
//link template
var linkTemplate = chart.links.template;
linkTemplate.colorMode = "gradient";
linkTemplate.fillOpacity = 0;
linkTemplate.middleLine.strokeOpacity = 0.3;
linkTemplate.middleLine.strokeWidth = 5;
`

But I cannot get the nodes to be a fixed size. This is of importance as many nodes do not flow to other nodes, which leads to just a few links "dominating" the screen. I tried by using the maxHeight property of a SankeyNode which did not work:

`var nodeTemplate = am4charts.SankeyNode
nodeTemplate.maxHeight = 1;`

How can I get this to work?

Full code is available on: https://codepen.io/roosvicee/pen/QWMOxam

**Comment by martynasma** [comment]
I'm afraid there's no way to set maximum height constraint for a Sankey Node. Sorry.
