### ISSUE TITLE
Change color ot TreeMap item dinamically

### ISSUE THREAD

**Issue by javier-fjfs** [amcharts/amcharts4#3868]
Hello,

I'm trying to change the color of a treemap item based on the name displayed. This is the code I have:

`
this.level2SeriesTemplate = this.treemap.seriesTemplates.create("1");
this.level2SeriesTemplate.columns.template.adapter.add("fill", (fill, target) => {
      let item_name = (target.dataItem.dataContext as am4charts.TreeMapDataItem).dataContext["name"];
      //check item name
      return am4core.color("<color>");
    });
`

I'm able to get the item name but the color never changes. I'm sure I'm not using the adapter correctly. Any feedback?

Thank you.

**Comment by xorspark** [comment]
You have to set the adapter on the column inside the template:

```
this.level2SeriesTemplate.columns.template.column.adapter.add('fill', (fill, target) => {
  //target.dataItem.parentName is the parent data object name
  //target.dataItem.treeMapDataItem contains the column data item
  // ...
});
```

**Comment by javier-fjfs** [comment]
That worked perfect!!

Thank you!!
