### ISSUE TITLE
Series are not shown when zoomOutButton fontFamily is some font

### ISSUE THREAD

**Issue by prime300th** [amcharts/amcharts4#3869]
**Bug description**

```
chart.zoomOutButton.label.text = "zoom out";
chart.zoomOutButton.label.fontFamily = "Arial";
```
https://jsfiddle.net/5se70r8m/

### NG font example
Arial
Segoe Script
Segoe UI

### OK font example
Courier New
Microsoft Sans Serif
Segoe Print

**Environment (if applicable)**
* Windows 10
  * Arial, Segoe Script, Segoe UI, Courier New, Microsoft Sans Serif, Segoe Print are installed
* Chrome 95
* Firefox 94

**Comment by zeroin** [comment]
This can be solved by setting:

`chart.zoomOutButton.icon.pixelPerfect = false;`

Alternatively you can also set

`chart.zoomOutButton.icon.isMeasured = false;`
and then position label by settin `label.marginRight`

**Comment by prime300th** [comment]
Thank you. It works, series are shown.
https://jsfiddle.net/rxpd0fbk/
