### ISSUE TITLE
valueLabels in legend are only right aligned when position set to "right" or "left"

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#387]
The `valueLabels` of a legend in a chart are only right aligned if the property `chart.legend.position` is set to either `right` or `left`, but not with `top`, `bottom` or `absolute`. This is mostly an issue when using an external container for the legend where it should not have an influence on what position is set on the chart, since I'm handling positioning of the legend directly.

However when using `right` or `left` positioning with an external container there is quite a bit of a margin or vertical translation applied between the chart and the legend. This does not happen when using `top` or `bottom`. This amplifies issue #382 even more, since a larger part of the legend is cut off when having additional content below the legend container.

An example can be seen on https://codepen.io/chnoch/pen/BOedrO, on the bottom of the JS-Part the different positions can be enabled or disabled to see how the behavior of the legend changes.

**Comment by martynasma** [comment]
There's a bit of fuzzy logic applied to legend's items based on its position.

Here's the setter for the position from the source:

```
	public set position(value: LegendPosition) {
		if (this.setPropertyValue("position", value)) {
			if (value == "left" || value == "right") {
				this.margin(10, 20, 10, 20);
				this.valign = "middle";
				this.itemContainers.template.width = percent(100);
				this.valueLabels.template.width = percent(100);
			}
			else {
				this.itemContainers.template.maxWidth = undefined;
				this.width = percent(100);
				this.valueLabels.template.width = 40;
			}
			this.invalidate();
		}
	}
```

You can see what stuff is applied to legend's items, so you can apply the same properties/values directly to items, to achieve required alignment/behavior.

Does that help?

**Comment by Chnoch** [comment]
Thanks for the information, that helps with the issues I was facing.
