### ISSUE TITLE
When series is hidden via legend, incremental update should ignore the corresponding data channel.

### ISSUE THREAD

**Issue by SparkyTD** [amcharts/amcharts4#3872]
**Bug description**

I have a stacked area chart that displays multiple streams of data from and external AJAX source, incrementally updates the data every second (`dataSource.reloadFrequency = 1000`, `dataSource.incremental = true`, `dataSource.keepCount = true`). When I click on one of the legend buttons to hide a stream, the corresponding series does disappear for a moment as expected, however after the next automatic reload, all the series above the hidden one get pushed up, as if the series wasn't hidden correctly. The attached video should make it easier to understand this issue.

Due to the dynamic nature of the external data source, I'm unable to provide a full sample code, but it's basically just the [Stacked Area](https://www.amcharts.com/demos/stacked-area/) example with some minor modifications to accept and parse my custom external data.

https://user-images.githubusercontent.com/45818400/140244832-cfc4ab99-f7f6-4949-a855-7848a417daa8.mp4

**Comment by zeroin** [comment]
I can only suggest to use this workaround - when data is added, you need to set valueY workingValue to 0. Here is a demo illustrating how to do this: https://codepen.io/team/amcharts/pen/9bfc58d8af4c2d9bd2c6ec1ec4f6d91d
