### ISSUE TITLE
Gantt Chart coloring based on task

### ISSUE THREAD

**Issue by RobjSky** [amcharts/amcharts4#3873]
I want to change the AmCharts Gantt in a way that colorizes the bars(tasks) based on the task-name so that each task with the same name has the same color even if they appear in different categories. I also don't want to have the color defined as a property of the dataset but rather just pull a color from am4core.ColorSet() for each task.

In the demo by AmCharts provided below that would mean:

    Gathering requirements = "yellow"
    Producing specifications = "blue" and so on. Is there a way to achieve this?

Demo I'm working off: https://www.amcharts.com/demos/gantt-chart-dates/

Thanks in advance.

**Comment by xorspark** [comment]
You can use an [adapter](https://www.amcharts.com/docs/v4/concepts/adapters/) on the series column's fill property that checks the data item associated with the column and returns the desired color. For example:

```
series1.columns.template.adapter.add('fill', function(fill, target) {
  switch(target.dataItem.dataContext.task) {
    case "Gathering requirements":
      return chart.colors.getIndex(3);
      
    case "Producing specifications":
      return chart.colors.getIndex(6);

    case "Development":
      return chart.colors.getIndex(9);

    case "Testing and QA":
      return chart.colors.getIndex(12);
      
    default:
      return fill; 
  }
});
```

[Demo](https://codepen.io/team/amcharts/pen/688c02a6a3f036375082afe8dde3087d?editors=0010)

**Comment by RobjSky** [comment]
Hi @xorspark, thanks for the input. Your code was really helpful and i was able to apply it to my project.
I adjusted it a little bit to be more flexible in terms of no hardcoding the task values. I instead generated a distinct list from the values given by the data set and than use that list to apply the colors based on index:

     // create distinct list of tasks
     let lookup = {};
     let items = chart2.data;
     let taskname = datapool.attrs[3]
     let distTasks = [];
     // get each task value from source(items)
     for (let item, i = 0; item = items[i++];) {
         let taskvalue = item[taskname];
         // check if task name already in lookup{} if not push into lookup{}
         if (!(taskvalue in lookup)) {
             lookup[taskvalue] = 1;
             distTasks.push(taskvalue);
         }
     }
     
     series1.columns.template.adapter.add('fill', function (fill, target) {
         return chart2.colors.getIndex(distTasks.indexOf(target.dataItem.task));
     });

Thanks again for your help.
