### ISSUE TITLE
How to set a sequence x-axis for heat-map?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3876]
Hi

![Screenshot from 2021-11-10 14-59-29](https://user-images.githubusercontent.com/71019344/141087104-cfc5907b-28bd-4bf1-9d36-c0a7e012d7c3.png)

In that x-axis is not in sequence, i want that  to be sequence. Can you suggest the way to implement that.

Thank you.

**Comment by martynasma** [comment]
I suppose you are using CategoryAxis as an X axis.

It will display categories in the same order as you have them in data. So all you need to do, is to put categories in correct order in your data, as axis will not do any sorting on its own.

**Comment by meghanaNanuvala** [comment]
`
        const xAxis1 = chart1.xAxes.push(new am4charts.CategoryAxis());
        const yAxis1= chart1.yAxes.push(new am4charts.CategoryAxis());

      
            xAxis1.dataFields.category = 'y';
            yAxis1.dataFields.category = 'x';
   
        xAxis1.renderer.grid.template.disabled = true;
        xAxis1.renderer.minGridDistance = 40;
        xAxis1.renderer.labels.template.truncate  = true;
        xAxis1.renderer.labels.template.maxWidth = 70;
        xAxis1.renderer.labels.template.tooltipText = '{categoryX}';
        xAxis1.maxZoomCount = 15;
        // xAxis1.start = 0;
        // xAxis1.end = 1;

        yAxis1.renderer.grid.template.disabled = true;
        yAxis1.renderer.inversed = true;
        yAxis1.renderer.minGridDistance = 30;
        yAxis1.renderer.labels.template.truncate  = true;
        yAxis1.renderer.labels.template.maxWidth = 120;
        yAxis1.renderer.labels.template.tooltipText = '{categoryY}';
      
        // yAxis1.start = 0;
        // yAxis1.end = 1;

        const series1 = chart1.series.push(new am4charts.ColumnSeries());
   
            xAxis1.numberFormatter.numberFormat = '#,###.00';
            series1.dataFields.categoryX = 'y';
            series1.dataFields.categoryY = 'x';
            series1.dataFields.value = 'y1';
    `

I have used above axis

**Comment by martynasma** [comment]
Looks good. So you just need to order your data so that `x` values are in consecutive order.

**Comment by meghanaNanuvala** [comment]
Actually i'm ordering data in proper way, can u look into this.
 'y' value  is indicating hours in proper order still i'm not getting
 `0: {x: 'Sunday   ', y: '00', y1: 1, y2: 0.04}
1: {x: 'Sunday   ', y: '01', y1: 1, y2: 0.04}
2: {x: 'Sunday   ', y: '02', y1: 3, y2: 0.12}
3: {x: 'Sunday   ', y: '04', y1: 1, y2: 0.04}
4: {x: 'Sunday   ', y: '05', y1: 43, y2: 1.72}
5: {x: 'Sunday   ', y: '06', y1: 1, y2: 0.04}
6: {x: 'Sunday   ', y: '07', y1: 1, y2: 0.04}
7: {x: 'Sunday   ', y: '08', y1: 3, y2: 0.12}
8: {x: 'Sunday   ', y: '09', y1: 1, y2: 0.04}
9: {x: 'Sunday   ', y: '12', y1: 2, y2: 0.08}
10: {x: 'Sunday   ', y: '13', y1: 2, y2: 0.08}
11: {x: 'Sunday   ', y: '20', y1: 2, y2: 0.08}
12: {x: 'Sunday   ', y: '21', y1: 3, y2: 0.12}
13: {x: 'Sunday   ', y: '22', y1: 5, y2: 0.2}
14: {x: 'Sunday   ', y: '23', y1: 7, y2: 0.28}
15: {x: 'Monday   ', y: '00', y1: 33, y2: 1.32}
16: {x: 'Monday   ', y: '01', y1: 55, y2: 2.19}
17: {x: 'Monday   ', y: '02', y1: 40, y2: 1.6}
18: {x: 'Monday   ', y: '03', y1: 29, y2: 1.16}
19: {x: 'Monday   ', y: '04', y1: 36, y2: 1.44}
20: {x: 'Monday   ', y: '05', y1: 44, y2: 1.76}
21: {x: 'Monday   ', y: '06', y1: 59, y2: 2.35}
22: {x: 'Monday   ', y: '07', y1: 54, y2: 2.15}
23: {x: 'Monday   ', y: '08', y1: 46, y2: 1.83}
24: {x: 'Monday   ', y: '09', y1: 33, y2: 1.32}
25: {x: 'Monday   ', y: '10', y1: 22, y2: 0.88}
26: {x: 'Monday   ', y: '11', y1: 6, y2: 0.24}
27: {x: 'Monday   ', y: '12', y1: 8, y2: 0.32}
28: {x: 'Monday   ', y: '13', y1: 2, y2: 0.08}
29: {x: 'Monday   ', y: '15', y1: 3, y2: 0.12}
30: {x: 'Monday   ', y: '22', y1: 8, y2: 0.32}
31: {x: 'Monday   ', y: '23', y1: 12, y2: 0.48}
32: {x: 'Tuesday  ', y: '00', y1: 30, y2: 1.2}
33: {x: 'Tuesday  ', y: '01', y1: 42, y2: 1.68}
34: {x: 'Tuesday  ', y: '02', y1: 56, y2: 2.23}
35: {x: 'Tuesday  ', y: '03', y1: 42, y2: 1.68}
36: {x: 'Tuesday  ', y: '04', y1: 45, y2: 1.79}`

**Comment by martynasma** [comment]
Well, the issue is that categories are being repeated, and not all are available.

For example in the "first pass" the "03" is missing, so it will go to the end.

In this case your best bet would be to set separate data for axis:

```
xAxis1.data = ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23'];
```

**Comment by meghanaNanuvala** [comment]
By placing that i'm getting empty
![Screenshot from 2021-11-11 12-49-07](https://user-images.githubusercontent.com/71019344/141255107-b5fab331-c915-43ee-9331-ae1d0b84ef0b.png)
don't we need to assign below line
`   xAxis1.dataFields.category = 'y';`

Do mention what to do exactly, please

**Comment by martynasma** [comment]
Yes, you're right. I made a mistake. Sorry. The data needs to have objects:

```
xAxis1.data = [y: '00', y: '01', y: '02'.........]
```

**Comment by meghanaNanuvala** [comment]
i'm getting all even numbers on axis, i want all 24 values like before
![Screenshot from 2021-11-11 13-19-23](https://user-images.githubusercontent.com/71019344/141259124-5ccda1b5-e681-4f24-8102-0c6fdd7d642f.png)

Can u tell me how to fix that

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by meghanaNanuvala** [comment]
Thank you
