### ISSUE TITLE
Problem with chart logarithmic switch

### ISSUE THREAD

**Issue by NeftaliAcosta** [amcharts/amcharts4#3878]
I have a chart that uses am4charts.LineSeries (). This graph has the option logarithmic = true. When I deactivate all the series and turn all of them back on, the Y axis appears like this.

Any recommendation?

![image](https://user-images.githubusercontent.com/15948880/141215459-a750a2d9-f6fb-4fdd-a1e5-c7a50b744751.png)

Thanks.

**Comment by martynasma** [comment]
I'm having trouble reproducing this. Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Aliaksandr-Yanushkevich** [comment]
@martynasma Hi. I have similar problem with axis toggling. I'm trying to change axis mode to `logarithmic` and this action break my chart. I've created small video, please take a look.

https://user-images.githubusercontent.com/51059670/145535699-611277f1-89d4-4324-b5ab-eb92fac7c6b0.mp4

I use `React + "@amcharts/amcharts4": "^4.10.23"`  and below you can find my useEffect to toggle axis mode:

```
   useEffect(() => {
        if (chart.current) {
            // change Yaxis type
            if (chartType === 'logarithmic') {
                chart.current.yAxes.values[0].logarithmic = true;
                chart.current.yAxes.values[0].treatZeroAs = 0.00001;
            } else {
                chart.current.yAxes.values[0].logarithmic = false;
            }
        }
    }, [chartType]);
```

Maybe function for creating series will be useful for you: 

```
export const createSeries = (chart, {name, data}, color) => {
    // create series
    const series = chart.current.series.push(new am4charts.LineSeries());

    series.name = name;
    series.dataFields.valueY = 'value';
    series.dataFields.valueX = "date";
    series.stroke = am4core.color(color);
    series.data = data;

    const bullet = series.bullets.push(new am4charts.Bullet());
    bullet.propertyFields.showTooltipOn = "showTooltip";
    bullet.tooltipText = "{label} ({date}): [bold]{value}[/]";
    bullet.fill = am4core.color(color);

    const circle = bullet.createChild(am4core.Circle);
    circle.width = 10;
    circle.height = 10;
    circle.horizontalCenter = "middle";
    circle.verticalCenter = "middle";
}
```

**Comment by martynasma** [comment]
@Aliaksandr-Yanushkevich Can you post this as a live demo which we can actually test?

**Comment by Aliaksandr-Yanushkevich** [comment]
@martynasma You can find it here https://codepen.io/aliaksandr-yanushkevich/pen/BawLKLV

**Comment by martynasma** [comment]
Thanks!

I think the issue is with `min` setting on your axis. You have it set to zero, which does not go well when you switch it to log scale.

When you're switching to log, you should probably reset `min` on ValuAxis, too, e.g. set it to `undefined`.

**Comment by Aliaksandr-Yanushkevich** [comment]
@martynasma Thanks! It helps for me!
