### ISSUE TITLE
How to number of columns in a Heat map table ??

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3879]
I have a heat map tables like below with different data lengths.so, no.of columns in a heat map also varying based on data length. Now, I want to get no.of columns in a heat map table.
![Screenshot from 2021-11-11 14-18-36](https://user-images.githubusercontent.com/74599304/141267462-d2148e6b-f07d-46e6-96e9-74da31a78079.png)

Thanks.

**Comment by martynasma** [comment]
I'm not sure what you mean. You need to know number of columns in your chart? I suppose easiest would be to just examine your data?

**Comment by VineelaKantamneni** [comment]
ok. Thank you
