### ISSUE TITLE
Drill down, showing multiple links.

### ISSUE THREAD

**Issue by Roosvicee** [amcharts/amcharts4#3881]
Hi there, I am trying to create a drill-down sankey diagram similar to the one posted on: https://codepen.io/team/amcharts/pen/mKvyVd/ . So far, I achieved pretty much what I wanted but there is one key element that I want to add to the chart, of which I am not quite sure if it is possible. 

In the diagram of https://codepen.io/team/amcharts/pen/mKvyVd/ , you can click on the link between either A --> D or on B--> D to show sub-links based on the main link.  Thus, it goes one level deeper. But is is also possible to show a level deeper based on both links? Now if you click on A-->D you get A1 --> D1, and (A2 + A3) -->D2. And if you click on B-->D you get B1 --> D1, and  (B2 + B3 + B4) -->D2. 

I want to be able to click on both links so all these sub-levels are shown in the diagram. So that the sub-links (A1 + B1) --> D1, and you get (A2 + A3 + B2 + B3+ B4) --> D2. 

Is something like this possible?

**Comment by martynasma** [comment]
I believe it is possible with some additional custom code, however we don't have a ready-made demo like that. Sorry.
