### ISSUE TITLE
Manipulate text for reader

### ISSUE THREAD

**Issue by ouldanov** [amcharts/amcharts4#3884]
How can you manage the text for the reader or is it possible to remove it on scrollbar slider?
![image](https://user-images.githubusercontent.com/38261337/141469635-d5e9d32d-297b-4634-925c-76e8ae4000c9.png)

**Comment by martynasma** [comment]
I suppose you can override reader text using adapter:

```JavaScript
chart.scrollbarX.adapter.add("readerTitle", function() {
  return "";
});
chart.scrollbarX.thumb.adapter.add("readerTitle", function() {
  return "";
});
```

**Comment by ouldanov** [comment]
Yes, that's what I needed, thanks!
