### ISSUE TITLE
Range bullets on top of an axis stroke?

### ISSUE THREAD

**Issue by MatthewAlner** [amcharts/amcharts4#3885]
Hey i'm looking to display Range bullets on top of my Date Axis but they always appear below, i've tried adjusting their zIndex but it seems to have no effect.

I'm using `4.10.21`

Here is a minimal reproduction

https://codepen.io/MatthewAlner/pen/bGrxKMm?editors=0010

any suggestions?

Many Thanks,
Matt

**Comment by MatthewAlner** [comment]
![CleanShot 2021-11-15 at 10 04 12@2x](https://user-images.githubusercontent.com/2782730/141763139-45c1cef1-4fcc-4943-a946-ddfe1a2fce8d.png)
![CleanShot 2021-11-15 at 10 07 08@2x](https://user-images.githubusercontent.com/2782730/141763150-8cdc7247-b0d6-4d95-97c7-9436e78bfd8f.png)

**Comment by martynasma** [comment]
Try this:

```JavaScript
chart.yAxesAndPlotContainer.zIndex = 1000;
```

**Comment by MatthewAlner** [comment]
That fixed it, so did `this.chart.bottomAxesContainer.zIndex = -1;`
