### ISSUE TITLE
Export operation took longer than expected. Something might have gone wrong am chart issue

### ISSUE THREAD

**Issue by ibjas** [amcharts/amcharts4#3886]
I am always getting this issue when exporting using amchart export option. what could be the solution for this.

![image](https://user-images.githubusercontent.com/19263982/141654638-b2429114-2852-4066-bc7f-53e7c29dc807.png)

**Comment by ibjas** [comment]
Mostly I am getting this message for PNG, JPG, PDF export option

**Comment by martynasma** [comment]
While default export timeout should be enough, you may change it to a bigger value to accommodate for slower systems.

https://www.amcharts.com/docs/v4/reference/export/#timeoutDelay_property
