### ISSUE TITLE
Halved bullets for 0 values

### ISSUE THREAD

**Issue by michaelscraft** [amcharts/amcharts4#3887]
Is there a way to make the bullets whole and not halved when series values are 0?

![Screen Shot 2021-11-15 at 4 52 49 PM](https://user-images.githubusercontent.com/22564070/141865769-a51a9eb0-9333-4022-a2d9-753b4eda9fbd.png)

**Comment by xorspark** [comment]
You can set `maskBullets` to false on your chart object to disable the clipping behavior.

```
chart.maskBullets = false;
```

[Documentation](https://www.amcharts.com/docs/v4/concepts/bullets/#Disabling_bullet_clipping)

**Comment by michaelscraft** [comment]
You are a wizard! Thank you!
![Screen Shot 2021-11-15 at 6 26 27 PM](https://user-images.githubusercontent.com/22564070/141873742-29b197dc-5f8a-490c-842e-bb694b223069.png)
