### ISSUE TITLE
Negative values shouldn't break treemap items

### ISSUE THREAD

**Issue by gregtakayama** [amcharts/amcharts4#3888]
In multi-level tree maps, negative values cause subsequent children in an item to not render. 

Steps to reproduce:
1. Create a simple multi-level treemap (I copied the example [here](https://www.amcharts.com/docs/v4/chart-types/treemap/#Multi_level_example))
2. Make the value of the first child of the "First" item negative `{ name: "A1", value: 100 }` => `{ name: "A1", value: -100 }`

Issue: 
- The "First" item along with its children are no longer displayed. (A2 and A3 are not displayed).

Expected: 
- All of the "First" children should be displayed. The docs [say](https://www.amcharts.com/docs/v4/chart-types/treemap/#Zero_negative_values) "When calculating sizes of the items, absolute values will be used instead." So, one would expect a negative value (-100) to be rendered as 100.

CodePen: https://codepen.io/gregt/pen/YzxRLgm

-----

Perhaps a related bug:
Large negative values cause items to completely disappear. 

Steps to reproduce:
1. Create a simple multi-level treemap, same as above.
2. Give a child a large negative value: `{ name: "A1", value: 100 }` => `{ name: "A1", value: -400 }`.

Issue:
- The "First" and "Second" items are not displayed at all. (All "A" and "B" children are not rendering). 

Expected:
- The "First" and "Second" items shouldn't disappear if a value is negative. 
- The negative value should be absolute and should render (-400 => 400).

The same CodePen as above can be used.

**Comment by martynasma** [comment]
Sorry for the conflicting information in the docs. We're amending it as we speak.

Treemap chart is not compatible with the negative values, so you will need to abs them in the source data.

If you still need to display negative values in labels and/or tooltips, you may have to keys: one with absolute value, the other with a value for label/tooltip:

```
{ name: "A1", value: 100, labelValue: -100 }
```

**Comment by gregtakayama** [comment]
Thanks for the quick response, makes sense.
