### ISSUE TITLE
Gantt chart, how to hide border radius of a rectangle if scrolled or zoom

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts4#3889]
**Bug description**

I am using Gantt chart, the rectangle has border radius as seen in the screenshot

![Screenshot 2021-11-16 at 09 55 37](https://user-images.githubusercontent.com/8130692/141953888-299b1e6f-c630-43bc-9fac-a9f45fc8f29e.png)

The problem is when I scroll or zoom in, the border radius is always shown, but it should only be shown in the starting and ending of the rectangle.

reproduction:

https://codepen.io/Mitwoc/pen/GRvwjgL

**Environment (if applicable)**

 - amCharts version 4
 - Angular 12

**Comment by martynasma** [comment]
I'm afraid there's no way to achieve that. Sorry.
