### ISSUE TITLE
Exportable option has no effect on exported data

### ISSUE THREAD

**Issue by Scylanth** [amcharts/amcharts4#3890]
Hello,

I have currently a linechart containing two series. I would like to export only one serie. So I have set the second serie as not exportable (attribute exportable set to false).

I noticed two issues at export time :
- When exporting as a csv, the second serie's data is present in the output csv.
- When exporting as an image, the second serie is correctly not rendered in the image, but its legend is still present.

Example [codepen](https://codepen.io/Scylanth/pen/QWMGJaB).
To reproduce, export as an image and as a csv.

Is the exportable attribute not meant to be used for exporting data?

Thanks in advance

**Comment by martynasma** [comment]
`exportable` setting applies to visual elements only, and has no effect on data.

You can modify what data is being exported using `dataFields`:
https://www.amcharts.com/docs/v4/concepts/exporting/#Changing_order_and_names_of_columns

As for the legend, I'm afraid there's no connection between `exportable` property for series and its legend item. You can probably implement some kind of event that would set it directly:

```JavaScript
chart.events.on("ready", function() {
  chart.legend.itemContainers.each(function(item) {
    var series = item.dataItem.dataContext;
    item.exportable = series.exportable;
  })
})
```

Though, making legend item not exportable will not re-arrange remaining legend items, so there'll be a gap in place of a hidden one.

https://codepen.io/team/amcharts/pen/5bae5222cfc12a13a039ebd8a6317657?editors=0010

**Comment by Scylanth** [comment]
I see, thank you for your help.
