### ISSUE TITLE
Question about DateAxis timezone

### ISSUE THREAD

**Issue by Woonhian** [amcharts/amcharts4#3891]
**Question**
I have a similar chart here: https://codepen.io/woonhian-the-bold/pen/KKvrjmY

My timezone is GMT+08:00. I would like to change the timezone to America/New_York for this chart. When I tried to change the timezone using `chart.dateFormatter.timezone = 'America/New_York'`, even though the time has changed, the zone on the tooltip and the axis is showing GMT+08:00. How can I make the chart such that the tooltip and the axis are showing 22:01 GMT-04:00 instead? Thanks!

![image](https://user-images.githubusercontent.com/35731563/142002298-a94a2261-4006-4570-b70f-a35a9b11c1cc.png)

**Comment by martynasma** [comment]
I think using inline formatting function does not take timezone setting into account.

Try setting global date/time format:

```
chart.dateFormatter.dateFormat = 'd MMMM HH:mm Z';
chart.dateFormatter.timezone = 'America/New_York';
```

Then using just dateX placeholder without inline formatter:

```
series.columns.template.tooltipText = "{dateX}";
```
