### ISSUE TITLE
template.applyOnClones does not apply to template.propertyFields

### ISSUE THREAD

**Issue by furier** [amcharts/amcharts4#3892]
**Bug description**

`series.columns.template.applyOnClones = true` has no impact when changing for instance `series.columns.template.propertyFields.fill` to be a different property, or even `series.columns.template.cursorOverStyle` to a different cursor style depending on `series.columns.template.showTooltipOn` is set to `hit` or `hover`.

https://codepen.io/furier/pen/qBXgXqX

**Use Case**

Switch between color modes without having to redraw the whole graph.

**Expected Behavior**

Colors are changed instantly when swapping between fill properties from the series data.

*Examples*
![image](https://user-images.githubusercontent.com/776919/142397306-de71518d-80f2-4e3d-8fa0-1ce55d1f8a54.png)
![image](https://user-images.githubusercontent.com/776919/142397363-146834fd-4956-4902-a902-d9a0b637b005.png)

**Actual Behavior**

Colors are not changed unless the data is re-fetched from cache and the color change is far from instant but lags behind, this is very noticeable and can take up to several seconds when the chart contains a week of data or up to a month of data with 300 rows.

**Environment**

 - @amcharts/amcharts4: 4.10.22
 - Google Chrome - Version 96.0.4664.45 (Official Build) (64-bit)
 - Vue: 2.6.11

**Comment by martynasma** [comment]
`propertyFields` are not propagated to clones, only those properties that are represented by `I[classname]Properties` interface are propagated, e.g.:

https://www.amcharts.com/docs/v4/reference/icolumnproperties/

Furthermore, `propertyFields` are applied at the moment of data parsing, and cannot be changed dynamically.

I'm not entirely sure what you're end goal is with this functionality, but you might need so other way to achieve it.

**Comment by furier** [comment]
> I'm not entirely sure what you're end goal is with this functionality, but you might need so other way to achieve it.

The columns in the bottom screenshot are mostly red which is representing the columns underlying data's worst status, 
The top screenshot with multiple colors are interpolated colors ranging on a scale depending on every columns underlying data's success rate.

So the bottom screenshot gives you a quick glance at all columns with a red og grey status.
The top screenshot gives you a more detailed glance at which of the columns have more or less bad statuses in relation to each other. so row 343 and 2451 are the ones with most bad statuses.

**Comment by martynasma** [comment]
Right, but the `applyOnClones` setting is useful when you are setting something on a template **after** actual columns are already built.

So, in this case what I'm thinking of is that you need to hot-swap the actual property field to something else.

Or are you saying it does not work right from the start of the chart?

In such case, we'll need a demo to take a look at.

**Comment by furier** [comment]
Sorry updated my previous comment with more stuff in stead of a new one

**Comment by furier** [comment]
> So, in this case what I'm thinking of is that you need to hot-swap the actual property field to something else.

So you are saying use the same property, just swap out the values?

**Comment by martynasma** [comment]
Well, swapping out values would require re-evaluating data anyway. If you're OK with that, then it's one way to go about it.

**Comment by furier** [comment]
@martynasma sorry for the long time to reply, I have been away.

> Well, swapping out values would require re-evaluating data anyway. If you're OK with that, then it's one way to go about it.

It is not ok even tho it works, because thats how it works currently, it's quick with little data but with as much data as in some of the screenshots it can take many seconds, I would like the color change to just be instant and fluent.

**Comment by martynasma** [comment]
In that case I could suggest iterating via actual columns and setting the colors directly:

```JavaScript
series.columns.each(function(column) {
  column.fill = column.dataItem.dataContext.someColorFieldOrSomething;
});
```

**Comment by furier** [comment]
Thank you @martynasma, that was instant and fast!

```
vm.colorPropertyChanged = property => {
  series.columns.each(column => {
    column.fill = column.dataItem.dataContext[property];
    column.stroke = column.dataItem.dataContext[property];
  });
}
```
