### ISSUE TITLE
How to display a given number of legends with highest scores

### ISSUE THREAD

**Issue by gladsonvm** [amcharts/amcharts4#3895]
Hi, Thanks for the wonderful framework!

I have a chart with a lot of legends (~50). I can display all legends on screen with scrollbar using  `legends.scrollable=true` . But when the width and height are set to the chart, and when it is needed to display all the legends total area of html container is a problem.

Is there a way to sort legends based on score of the legends and to limit the number of legends to display?

Lets say legend data is something like below

```
{
'green': 1,
'red': 2,
'blue': 3,
'yellow': 4,
'black' 5,
'cyan':6,
...
....
...
...
} 
```

And the chart should display first 3 legends - green, red and blue (based on number assigned to them). Is it possible?

**Comment by martynasma** [comment]
What kind of chart is that? Is the legend generated automatically, or you are adding items manually?

If you could post your chart on CodePen, that would be great.

**Comment by gladsonvm** [comment]
Yes. Legends are generated automatically. There are about 50 legends. It is a bar chart in which legends are indicated with colors. Is it possible to sort legends based on their corresponding scores? That will also solve the issue. Data source is already returning sorted data.

**Comment by martynasma** [comment]
OK, so what is the "corresponding score" of a `ColumnSeries`?

**Comment by gladsonvm** [comment]
Oh.. excuse me for using legend instead of markers. What I meant was there are 50 markers. I can squeeze in all markers with

```
markerTemplate = chart.legend.markers.template;
        markerTemplate.height = 10;
        markerTemplate.width = 10;
        ```
        and `chart.legend.fontSize = 8`. But still markers are not sorted.

**Comment by martynasma** [comment]
What would they be sorted by? A series has multiple data points with different values. Not a single value.
