### ISSUE TITLE
Draw a Circle on X,Y = 0,0

### ISSUE THREAD

**Issue by calvaradocl** [amcharts/amcharts4#3896]
Dear Amcharts Team,

We have a scatter chart with negative and positive values for X and Y, and we need to add a circle on the center of the XY axis with varying width. We have tried adding an am4core.Circle to the plotContainer, but it uses absolute positioning, and we would like to center it around 0,0, is this possible?

Also, we would like that the size scales with the chart zoom, for example the circle is centered on 0,0 and the size is 10, that means the circle will always have that size, instead of being resized when someone zooms in a specific zone of the chart.

We have a codepen running with two sample points, we tried setting X and Y for the circle with no positive results.

https://jsfiddle.net/darkfile/xw9jL023/1/

Best,
Carlos.

**Comment by martynasma** [comment]
If you need a bubble to be at 0x0 coordinates, why not just add it as any regular bubble via series and its data?

As for zooming when chart is zoomed, I'm afraid there's no such built-in functionality. Sorry.

**Comment by calvaradocl** [comment]
Hi Marty,

From what I understand a bubble series should do the trick, but we can't set a fixed size for the bubble so it doesn't scale with zoom, is that correct?

Best
Carlos.

**Comment by martynasma** [comment]
Bubbles would not scale with zoom. It's a bubble with specific radius in pixels, so it will remain constant.

**Comment by calvaradocl** [comment]
Ok, we will take this implementation ahead with another library, thanks for the clarification.
