### ISSUE TITLE
amchart4 external json Data loading fails in Partition bar chart

### ISSUE THREAD

**Issue by rajkumarj-git** [amcharts/amcharts4#3898]
**Bug description**
Value doesn't exist
    Error: at Object.Mtpk.e.getValue  core.js?ver=1.3:formatted:20929

**Comment by xorspark** [comment]
Assuming you're copying directly from our example and simply replacing `chart.data` with `chart.dataSource.url`, I suspect the error message is coming from calling addRange when no data exists. External JSON is loaded asynchronously, so you need to move those addRange calls inside an event that fires after the data has been loaded, such as the dataSource's `complete` event.

```
chart.dataSource.events.on('done', function(e) {
  // Add ranges after the data has been loaded.
  // Wrap in a setTimeout to ensure that the calls occur post
  // data validation
  setTimeout(function() {
    addRange("Central", "Texas", "North Dakota", chart.colors.getIndex(0));
    addRange("East", "New York", "West Virginia", chart.colors.getIndex(1));
    addRange("South", "Florida", "South Carolina", chart.colors.getIndex(2));
    addRange("West", "California", "Wyoming", chart.colors.getIndex(3));
    // update the legend 
    chart.legend.invalidateData();
  });
});
```

Here's a very basic version of this in action: https://codepen.io/team/amcharts/pen/45604bb6786e18918f76bea206a56c9e?editors=0010 

Adjust this as needed.

**Comment by rajkumarj-git** [comment]
I am glad to thank you for resolving the issue, I feel the amchart support team give their best. My issue was resolved with your solution. The axis ranges are added before there is data  which I wasn't aware of in amchart docs example. All credit goes Martynas Majeris and Anthony P for their support in this regards.
