### ISSUE TITLE
Disable "autocolor" on CandleStick using JSON Config

### ISSUE THREAD

**Issue by MashRoofa** [amcharts/amcharts4#3899]
**Question**

Hello, i have a simple question on how to apply this setting but through the JSON configuration of am4Charts.

`series.columns.template.set("themeTags", []);`

**Comment by martynasma** [comment]
That looks like code from amCharts 5, and won't work on amCharts 4.

What are you trying to achieve?

**Comment by MashRoofa** [comment]
Essentially I'm trying to remove the default colouring of BoxPlot that changes to red and green based on the close / open prices (i.e., i want to set the default theme colour on all columns e.g., yellow for theme kelly). I want to achieve this in am4Charts using the JSON configuration method. Thank you!

**Comment by martynasma** [comment]
Gotcha.

Maybe something like this:

```JSON
series: [{
  // ...
  dropFromOpenState: {
    properties: {}
  },
  riseFromOpenState: {
    properties: {}
  }
}]
```

**Comment by MashRoofa** [comment]
I've tried this but without success. Take a look here [https://codepen.io/ChrisMash/pen/poEgZdM?editors=1010](https://codepen.io/ChrisMash/pen/poEgZdM?editors=1010)

**Comment by martynasma** [comment]
Indeed. Well, then then you will probably need to explicitly set the colors:

```
dropFromOpenState: { properties: { fill: "#67b7dc", stroke: "#67b7dc" } },
riseFromOpenState: { properties: { fill: "#67b7dc", stroke: "#67b7dc" } },
```

**Comment by MashRoofa** [comment]
Ok thank you, is there a possibility this can be added as a feature?

**Comment by martynasma** [comment]
I don't think we'll be doing any significant changes to amCharts 4 at this point. So, probably no :(

**Comment by MashRoofa** [comment]
I totally understand thank you again. I assume that the JSON example solution you provided should work as expected on am5?

**Comment by martynasma** [comment]
Nope. v5 does not support JSON config at all ;)
