### ISSUE TITLE
ColumnSeries Tooltip displaying wrong column info

### ISSUE THREAD

**Issue by flefloch-payps** [amcharts/amcharts4#3900]
Hello,

I have a clustered column chart where I had to enable Cursor.
As indicated in the doc I have added the tooltip to my serie directly (end not to the template) to avoid displaying all the tooltips from the cluster at the same type.
Everything is working correctly, except that the rollOver seem to display the tooltip from the column at the right of the cursor.
I reproduced the issue on this codePen : 
https://codepen.io/fleflochn/pen/yLoMrrB
If you rollOver the top of each column you won't have any problem since there is no data on the right , but if you rollOver on the bottom of each column (so you definitely have a column right to the cursor) you'll see that it displays the tooltip from the +1 column.
I tried to define `maxTooltipDistance=-1` on the cursor but that doesn't seem to change anything. 

May someone point to me what i'm doing incorrectly?

Thank you

**Comment by martynasma** [comment]
When you set `maxTooltipDistance = -1` it will show tooltip to the closest data item to mouse cursor.

When determining closest data item, it will measure distance by both X and Y, so it might seem like it's getting wrong column, but it's not.

Columns are easy to hover, so if you need just one tooltip, I would put `tooltipText` directly on columns, not using cursor or `tooltipText` on series.

Hope that makes sense.

**Comment by flefloch-payps** [comment]
Hello @martynasma , thanks for answering.

I need to have a cursor on my graph (even if it's not present in the codePen I also use cursor to be able to zoom or pan my graph).
That's why I added the tooltipText on the series instead of the columns (using `series.tooltipText` instead of `series.columns.template.tooltipTex`t ), because I don't want to display all the tooltips of the cluster when I rollOver one single column? Or is there another way to avoid displaying all the tooltips at the same time?

**Comment by martynasma** [comment]
> Or is there another way to avoid displaying all the tooltips at the same time?

Yup, there is.

You can set tooltipText directly on column templates + disable cursor tooltips:

https://www.amcharts.com/docs/v4/reference/columnseries/#cursorTooltipEnabled_property

**Comment by flefloch-payps** [comment]
This is exactly what I need !
Completely missed that in the documentation.
Thanks for pointing this out.
