### ISSUE TITLE
two sets of labels in one pie chart

### ISSUE THREAD

**Issue by ajonk93** [amcharts/amcharts4#3902]
Hi, is it possible to have 2 sets of labels in one pie? 
For example, combine those two: 
1. Outside labels with category text, 
2. Inside labels with % value. 
![labels outside](https://user-images.githubusercontent.com/10283897/143224219-404dc941-4a9b-45cf-b4f7-6f277142ff42.PNG)
![labels inside](https://user-images.githubusercontent.com/10283897/143224236-92faeabb-ee4e-48e2-9abe-9b0781fd0b57.PNG)

**Comment by martynasma** [comment]
No, I'm afraid. PieSeries supports only one set of labels.
