### ISSUE TITLE
Set separate width to charts and legend when exporting 

### ISSUE THREAD

**Issue by gladsonvm** [amcharts/amcharts4#3903]
Is it possible to set width/height to chart and legend while exporting? I know doc.push can have width/height attributes which can set size like below

```
doc.content.push({
        columns: [
        {
          image: res[1],
          width: 400,
          height:100,
          margin: [0, 10, 50, 5]
        }],
        columnGap: 0,
      });
```
      
![image](https://user-images.githubusercontent.com/1822969/143228528-0d4d9b57-cd8c-4ee3-b057-b569415b73a1.png)
Above image is snipped from exported pdf. As in the pdf, pie chart looks squeezed in. If it is possible to set width to chart and legend just before exporting (Before it is converted to jpg/png as set in exporting code), this can be solved.

**Comment by martynasma** [comment]
Maybe you can modify the chart before export as per this tutorial:
https://www.amcharts.com/docs/v4/tutorials/modifying-chart-for-export/
