### ISSUE TITLE
NumberFormatter not working on ValueAxis labels and Data labels (LabelBullet)

### ISSUE THREAD

**Issue by Jagan-P** [amcharts/amcharts4#3904]
**Bug description**

Am using JSON-config in which I have a numberFormatter for value-axis and label-bullet. And it doesn't format decimals properly.
```
[
    {
        "type": "ValueAxis",
        "title": {
            "text": "string",
            "id": "axis-title-619e1e40d9869a001981f584",
            "userClassName": ""
        },
        "dataFields": {
            "value": "fund_amount-distinct"
        },
        "numberFormatter": {
            "type": "NumberFormatter",
            "forceCreate": true,
            "numberFormat": "#.0"
        }
    }
]
```

and 

```
{
    "series": [
        {
            "type": "LabelBullet",
            "label": {
                "text": "{valueY}",
                "numberFormatter": {
                    "type": "NumberFormatter",
                    "forceCreate": true,
                    "numberFormat": "#.0"
                },
                "adapter": {},
                "locationY": 0.5,
                "locationX": 0.5,
                "verticalCenter": "bottom",
                "horizontalCenter": "middle"
            }
        }
    ]
}
```
As seen in the below image it only formats the number `0` and not any other number even after using `"numberFormat": "#.0"`

![image](https://user-images.githubusercontent.com/31800888/143230196-f3d5167d-4efb-44f3-b7f6-384022321997.png)

**Environment (if applicable)**

amCharts version: 4.10.22

**Additional context**

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Jagan-P** [comment]
Created a JsFiddle where this issue can be seen - https://jsfiddle.net/y4mv061s/

**Comment by martynasma** [comment]
ValueAxis adjust label precision based on steps. If you rather want it to follow number format blindly, you can disable it using `adjustLabelPrecision: false`.

Creating NumberFormatter for each bullet is wasteful, and, as you can see, does not work, because of how bullets inherit parents.

I suggest setting new number formatter for series, rather than bullet.

Updated fiddle:
https://jsfiddle.net/kybs84nu/

**Comment by Jagan-P** [comment]
> ValueAxis adjust label precision based on steps. If you rather want it to follow number format blindly, you can disable it using `adjustLabelPrecision: false`.
> 
> Creating NumberFormatter for each bullet is wasteful, and, as you can see, does not work, because of how bullets inherit parents.
> 
> I suggest setting new number formatter for series, rather than bullet.
> 
> Updated fiddle: https://jsfiddle.net/kybs84nu/

This works, thanks!

I have one more question with respect to LabelBullet position and almost the same config. Should I create a new question/bug or ask here?

**Comment by Jagan-P** [comment]
In the same JSFiddle that you shared, please change the data to 
```
chart.data = [
    {
        "disbursment_year": 2015,
        "fund_amount-distinct": 1
    },
    {
        "disbursment_year": 2020,
        "fund_amount-distinct": 2
    }
];
```

You should see that the LabelBullet is placed improperly.
![image](https://user-images.githubusercontent.com/31800888/143388625-86ecf580-9d20-40db-867b-257a3de04d52.png)

It shold be in the middle of the bar right?  JSFiddle link - https://jsfiddle.net/tk3y5bL2/

Appreciate if you could help here.

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by Jagan-P** [comment]
Solved
