### ISSUE TITLE
Unable to place LabelBullet in the middle of bar in JSON config

### ISSUE THREAD

**Issue by Jagan-P** [amcharts/amcharts4#3906]
**Question**

Am using LabelBullet for `ColumnSeries` with following config,
```
{
    "type": "ColumnSeries",
    "dataFields": {
        "valueY": "fund_amount-distinct",
        "categoryX": "disbursment_year"
    },
    "name": "fund_amount",
    "id": "619f3aa3d9869a00198204db",
    "events": {},
    "userClassName": "",
    "numberFormatter": {
        "type": "NumberFormatter",
        "forceCreate": true,
        "numberFormat": "#.00"
    },
    "bullets": [
        {
            "type": "LabelBullet",
            "label": {
                "text": "{valueY}",
                "adapter": {}
            },
            "locationY": 0.5,
            "locationX": 0.5
        }
    ]
}
```

Am setting ` "locationY": 0.5,` so that it appears inside the column/bar and in the middle of the bar.

It works fine for large numbers in `chart.data`
```
chart.data = [
    {
        "disbursment_year": 2015,
        "fund_amount-distinct": 1234565557
    },
    {
        "disbursment_year": 2020,
        "fund_amount-distinct": 22345655
    }
];
```
![image](https://user-images.githubusercontent.com/31800888/143399077-56c7ae04-5d70-4df0-8f55-4c411274cc53.png)

But for small numbers in `fund_amount-distinct` it is misplaced. 
JSFiddle - https://jsfiddle.net/91e2hywj/
```
chart.data = [
    {
        "disbursment_year": 2015,
        "fund_amount-distinct": 1
    },
    {
        "disbursment_year": 2020,
        "fund_amount-distinct": 2
    }
];
```

![image](https://user-images.githubusercontent.com/31800888/143399179-0917721f-3c5e-4578-8b83-dcc0e4bb3c4d.png)

And using `Label` inside `series.columns.children` doesn't work too as described here in [Alternative to bullets](https://www.amcharts.com/docs/v4/tutorials/using-label-bullets-on-a-horizontal-bar-chart/#Alternative_to_bullets). 
JSFiddle - https://jsfiddle.net/91e2hywj/1/

Added JSFiddle for both the cases. If any of these 2 works it would be great.

**Environment (if applicable)**
- amCharts version - 4.10.22

**Additional context**

**Comment by martynasma** [comment]
Bullets are placed relative to the "whole column" which extends all the way to the zero.

If you need to center the label in the visible part of the column, you will not be able to use bullet, but rather insert as a child into the column itself, as you correctly assumed.

The only thing that is missing in your fiddle is `forceCreate: true`:

```
            "columns": {
                "children": [
                    {
                        "type": "Label",
                        "forceCreate": true,
                        "text": "{valueY}",
                        "fontSize": 20,
                        "valign": "middle",
                        "dx": 10,
                        "strokeWidth": 0
                    }
                ]
            }
```

**Comment by Jagan-P** [comment]
> Bullets are placed relative to the "whole column" which extends all the way to the zero.
> 
> If you need to center the label in the visible part of the column, you will not be able to use bullet, but rather insert as a child into the column itself, as you correctly assumed.
> 
> The only thing that is missing in your fiddle is `forceCreate: true`:
> 
> ```
>             "columns": {
>                 "children": [
>                     {
>                         "type": "Label",
>                         "forceCreate": true,
>                         "text": "{valueY}",
>                         "fontSize": 20,
>                         "valign": "middle",
>                         "dx": 10,
>                         "strokeWidth": 0
>                     }
>                 ]
>             }
> ```

Adding `forceCreate` works. Thanks much!
