### ISSUE TITLE
Floating columns after new chart data

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3907]
**Bug description**

XYChart with 2 (or more) stacked column series and legend.
![image](https://user-images.githubusercontent.com/58069494/143419774-a07460ae-03cd-4248-a018-679e6f32f71b.png)

Hide the first series per legend click. After that it's still ok. The second series now starts from 0.
![image](https://user-images.githubusercontent.com/58069494/143419932-d979ed2e-563c-4c41-91c3-6fd958afdf3a.png)

Update the chart with new (or the same) data - the first series is still hidden (good - should be) but the second one now floats in the air - as if the first series is painted transparent.
![image](https://user-images.githubusercontent.com/58069494/143420630-7623b0fe-6bb6-4283-91e7-234bba538cd4.png)

https://codepen.io/chrisadler/pen/KKvjJPb?editors=1010

**Environment (if applicable)**

 - amCharts version: 4:10:23 (and earlier)
 - Browser and its version: all browsers/versions

**Comment by zeroin** [comment]
We can only offer this official workaround in this case:
https://codepen.io/team/amcharts/pen/e52bb6dc916e491502be436b69bf773c?editors=1010

You need to force hide series one more time after data is validated.

**Comment by lticadler** [comment]
Ok, thank you very much.
