### ISSUE TITLE
Position of scrollbar

### ISSUE THREAD

**Issue by Lupici** [amcharts/amcharts4#3908]
Hi all, I have a XYChart, with two scrollbar inside

`		this.chart.scrollbarX = new am4core.Scrollbar();
		this.chart.scrollbarY = new am4core.Scrollbar();
`
I want to put them on the left and on the bottom, instead of the default. So I used

`		this.chart.scrollbarX.parent = this.chart.bottomAxesContainer;
		this.chart.scrollbarY.parent = this.chart.leftAxesContainer;
`
but the bars where put beyond the axis labels and title

![image](https://user-images.githubusercontent.com/89850538/143427896-255bf8c9-3bcf-4eb4-80b0-4c584d05899f.png)

Is it possible to put them between the plot area and the axis labels?

The order is to be (from upper to lower) Plot area, scrollbar, axis labels (1,2,3,4..), axis title ("financial.."). The same for the left scrollbar

Thanks to all

L.

**Comment by Lupici** [comment]
Ok, maybe I found a solution, will be helpful for other with my same problem, but I don't know why is different from bottom to left

if I write

`		this.chart.bottomAxesContainer.layout = "absolute";
`
the bottom scrollbar is put on the right position

and I can fine-tune the position with, for example
`this.chart.scrollbarX.y=-10;`

![image](https://user-images.githubusercontent.com/89850538/143431464-689521b5-6fe7-4066-8e4f-e87dad8bf14b.png)

If I made the same for left scrollbar, by write

`this.chart.leftAxesContainer.layout = "absolute";`

the result is this

![image](https://user-images.githubusercontent.com/89850538/143431663-4ad43adc-ec1f-470f-97cb-1471c9a556a6.png)

If I DON'T write `this.chart.leftAxesContainer.layout = "absolute";`

the left bar is rendered in the right position

![image](https://user-images.githubusercontent.com/89850538/143431962-d5a680c3-70ac-446f-80f7-3bbbe560a6a7.png)

Why this difference???

thanks
L.

**Comment by martynasma** [comment]
This is because `leftAxesContainer` has horizontal layout, which means elements are added next to each other.

If you set to "absolute", arranging of elements is disabled and they are all just right-aligned.
