### ISSUE TITLE
am4core.color("transparent") transforms to black?

### ISSUE THREAD

**Issue by nabati** [amcharts/amcharts4#3909]
`am4core.color("transparent")` translates to ~ `rgba(0,0,0,1)`, but should probably be transformed to `rgba(0,0,0,0)`

![image](https://user-images.githubusercontent.com/1499050/143544537-3949a6c4-503c-49b8-beb2-136b98042a82.png)

v4.10.22

**Comment by martynasma** [comment]
It happens because black is default fallback when a string cannot be resolved to a valid color. Since "transparent" is not supported, we get `rgba(0,0,0,1)`.

I suggest using `am4core.color("rgba(0, 0, 0, 0)")`.
