### ISSUE TITLE
Create a XYChart for fill between line

### ISSUE THREAD

**Issue by manoj016** [amcharts/amcharts4#391]
Hi,

As in the Amcharts 3 there is a XYChart fill between line like this 
<img width="1086" alt="screen shot 2018-09-25 at 3 51 33 pm" src="https://user-images.githubusercontent.com/41284266/46008852-86fe8c80-c0db-11e8-804b-35accd246bd5.png">

How can I achieve like this in Amcharts 4.

Thank you,

**Comment by martynasma** [comment]
In amCharts 4 you don't have to have two series to create a fill.

You can set `dataFields.openValueY` for the series, then set fill settings for a series. It will between `valueY` and `openValueY`.

Here's an example:
https://codepen.io/team/amcharts/pen/jZjJaY

If you need the line in the middle, you will need to add a second series, though.

Hope that makes sense.

**Comment by manoj016** [comment]
Thank you very much @martynasma

**Comment by tscislo** [comment]
@martynasma how to do the same in AmCharts 5?
