### ISSUE TITLE
Scrollbar tooltip not updated with chart data (2nd)

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3910]
**Bug description**

unfortunately a reopen for for #3830 
The fix in amCharts 4.10.23 works fine if the chart data is updated.
But if the data is updated per series it's still the same behavior.
`series.data = ... `instead of `chart.data = ...`
Pen: https://codepen.io/chrisadler/pen/BadXYWx?editors=0010

![image](https://user-images.githubusercontent.com/58069494/143579485-d4d0b913-212f-4360-b833-ae1e84d7d03d.png)

after series data update
![image](https://user-images.githubusercontent.com/58069494/143579646-7a6245ee-44d5-437f-8130-cab019d482a3.png)

**Environment (if applicable)**

 - amCharts version: 4.10.23
 - Browser and its version: all Browsers

**Comment by martynasma** [comment]
I'm not sure if we will be making this change.

Though, here's a workaround:

```JavaScript
series.events.on("datavalidated", function() {
  setTimeout(function() {
    chart.scrollbarX.updateThumb(false);
  }, 1000)
})
```

The timeout is needed so that thumb does not grab some intermediate value while axis is animating.

**Comment by lticadler** [comment]
Thank you - updated the pen with your workaround.
