### ISSUE TITLE
lose the fill color in the legend when using stroke in the templateField

### ISSUE THREAD

**Issue by Campergue** [amcharts/amcharts4#3915]
I defined my Series Fill and Stroke using a TemplateField and passed the series.dataItems to the Legend. 
The fill color is only used in the legend if I do not specify a stroke value. 
I would expect that I can set both via the TemplateField reference and that this also works for the Legend.

https://codepen.io/Campergue/pen/ZEXYWKj

![image](https://user-images.githubusercontent.com/6292190/144144134-fcd16e79-4f6f-405f-9f2f-e062559ca9f9.png)

-->

**Environment (if applicable)**
amCharts version : @amcharts/amcharts5 => 5.0.13
Browser and its version : all browers/versions
Related frameworks and their versions:  Angular 12 and NativeJS

**Comment by martynasma** [comment]
This is a repo for amCharts 4. If it's not too much trouble, could you please repost in [appropriate repo](https://github.com/amcharts/amcharts5/issues/)?

**Comment by Campergue** [comment]
Yes, of course. Sorry I did not notice so
