### ISSUE TITLE
Range Label Rotation

### ISSUE THREAD

**Issue by DimaGavrushko** [amcharts/amcharts4#3916]
I need to create vertical labels inside dateAxis ranges.

![image](https://user-images.githubusercontent.com/22750804/144195207-c4f2656d-491e-4b46-800c-4fb02ebf177f.png)

And as a result, I have:
![image](https://user-images.githubusercontent.com/22750804/144195271-286b3eb5-e137-4b39-9562-bf126f16eb31.png)

Labels are cutting off at the top. I want vertical labels at the very top but not cutting them off.

"@amcharts/amcharts4": "^4.10.18",
"react": "^17.0.1",

Thanks for any help.

**Comment by martynasma** [comment]
Try this:

```JavaScript
range.label.horizontalCenter = "right";
```

**Comment by DimaGavrushko** [comment]
@martynasma thanks, it works. but why is it the solution?

**Comment by martynasma** [comment]
Well, labels are rotated and positioned by their center. So if you leave default "middle", then labels are placed by the middle and rotated accordingly.

More details here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Label_rotation
