### ISSUE TITLE
Gannt chart not able to show correctly

### ISSUE THREAD

**Issue by rcalupig-fmg** [amcharts/amcharts4#3917]
Width of Gannt bars are incorrect if data dates span more than a month (eg. November 30th to December 1st).

amchart version: 4.10.22
Chrome version: 96.0.4664.45 (Official Build) (64-bit)
Angular version: 12.1.4

Example data:
![image](https://user-images.githubusercontent.com/94333500/144276676-1ec5e738-cd1a-466b-9cd4-e666195ba60d.png)

Screenshot of Gannt bar:
![image](https://user-images.githubusercontent.com/94333500/144276126-9dc6a00c-9290-4f9c-9866-21e8997b9998.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by rcalupig-fmg** [comment]
Hi @martynasma. Sorry it took me long to respond. I've rectified the issue by using the ticks instead of the datetime string. All good. I'll close this issue.
