### ISSUE TITLE
leftAxesContainer width

### ISSUE THREAD

**Issue by DimaGavrushko** [amcharts/amcharts4#3918]
I have an issue with different y-axes containers widths.
![image](https://user-images.githubusercontent.com/22750804/144459025-82ea9be4-8a0e-435d-b42a-04dabc75e027.png)

For solving it I found a property `chart.leftAxesContainer.width` which I can set the same to both charts.
But I don’t know the height in advance and I have to set a very big high.

1) Do I have a way to get a real content width?
2) Maybe you can suggest another solution.

"@amcharts/amcharts4": "^4.10.18",

**Comment by martynasma** [comment]
I'm assuming you need to sync axis width across multiple charts. We do have a demo for that:

https://www.amcharts.com/docs/v4/tutorials/syncing-width-of-the-vertical-axes-across-multiple-charts/

Hope the code there will make sense.

**Comment by DimaGavrushko** [comment]
@martynasma this works when I have the same number of axes, but I also have other cases:
![image](https://user-images.githubusercontent.com/22750804/144579004-95d15f52-de03-47ae-a43d-86f3240da56a.png)

**Comment by martynasma** [comment]
I suppose you can enhance the code to factor in other axes. I'm afraid I don't have an example like that myself.

**Comment by DimaGavrushko** [comment]
@martynasma, Also, I noticed (but not 100% sure) if I change width once, the measured width will be the same and will not be changed anymore even if I change the chart data.

**Comment by martynasma** [comment]
You might need to resync axes after data is updated, e.g.:

```
chart.events.on("datavalidated", syncAxisWidth);
```
