### ISSUE TITLE
How do I remove these white spaces on the left and right of plot area

### ISSUE THREAD

**Issue by facinick** [amcharts/amcharts4#3919]
<img width="1139" alt="Screenshot 2021-12-03 at 11 07 38 AM" src="https://user-images.githubusercontent.com/12322728/144551183-5043f70f-7769-499c-86e2-7dced907a8c3.png">

**Question**
The area from 15500 to 16000 is blank white as there are no data points, why is it shown in the chart? similarly on the right end

**Comment by martynasma** [comment]
You might need to set `min` and `max` on your X axis, as well as `strictMinMax = true`.

https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Adjusting_scale

**Comment by facinick** [comment]
Thanks @martynasma , strictMinMax did the job!
