### ISSUE TITLE
cursor is not behaving as expected

### ISSUE THREAD

**Issue by facinick** [amcharts/amcharts4#3920]
https://user-images.githubusercontent.com/12322728/144551714-6d72a1d1-cbfa-4079-8d10-fe3378b25590.mov

What am I expecting: when I move cursor in any coordinate on the graph, the tooltip should snap to the series with x coordinate of the mouse cursor.

Code:

    this.chart = am4core.create(this.chartDiv, am4charts.XYChart);
	this.chart.paddingRight = 50;

	this.title = this.chart.titles.create();
	this.title.fontSize = 25;
	this.title.tooltipText = `${this.props.underlyingEquityTradingSymbol} Strike vs PnL`
	this.updateTitle();

	this.setChartData(this.props.chartData);

	const strikeAxis = this.chart.xAxes.push(new am4charts.ValueAxis());
	strikeAxis.title.text = "Strike";
	strikeAxis.title.fontWeight = "bold";
	strikeAxis.startLocation = 0;

	// // set x=cmp line
	this.set_x_cmp_line(strikeAxis);

	const profitlossAxis = this.chart.yAxes.push(new am4charts.ValueAxis());
	profitlossAxis.title.text = "PnL (rs)";
	profitlossAxis.title.fontWeight = "bold";

	this.set_y_zero_line(profitlossAxis);

	this.series = this.chart.series.push(new am4charts.LineSeries());
	this.series.dataFields.valueX = "xValue";
	this.series.dataFields.valueY = "yValue";
	this.series.tooltipText = "{valueX}: INR [bold]{valueY}[/]";

	this.set_PNL_colors(profitlossAxis);

	// cursor
	this.chart.cursor = new am4charts.XYCursor();
	this.chart.cursor.xAxis = strikeAxis;
        this.chart.cursor.yAxis = profitlossAxis;
	this.chart.cursor.behavior = "zoomXY";
	this.chart.cursor.snapToSeries = [this.series];

**Comment by martynasma** [comment]
This is how snapping works. It calculates to the nearest data item by X and Y, not just X.

There's no way around it.

If you need to snap by just X, you might consider upgrading to amCharts 5, which does have an additional setting for that. [More info](https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#Snapping_to_series).

**Comment by facinick** [comment]
<img width="403" alt="Screenshot 2021-12-03 at 2 38 30 PM" src="https://user-images.githubusercontent.com/12322728/144576043-49031dfb-cdf0-4da4-a2bb-50cc091973f1.png">
this is from a website which uses AMcharts 4 (my cursor is way below the slant line... its not showing tooltip at a point in series which is shortest distance from the mouse, but at a point in series which has same X as mouse) and they were able to achieve this, is there really no way? I just want to move my cursor freely, and based on it'x X value show Y intercept on the series as a tooltip...

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
