### ISSUE TITLE
chart responsive is not work

### ISSUE THREAD

**Issue by yuxuejiao** [amcharts/amcharts4#3921]
loading img:
<img width="517" alt="loading" src="https://user-images.githubusercontent.com/18752571/144556959-e1501052-b414-473e-8b74-e72b1d952a02.png">
loaded img: 
<img width="517" alt="loaded" src="https://user-images.githubusercontent.com/18752571/144556976-41a44b06-2a79-47df-8d22-1acb6f263114.png">

Code: `<div class="data" v-loading="loading">
                        <span>{{overallScore}}%</span>
             </div><div v-if="!loading">
                  <LineChart :data="scoreChart.data" :id="scoreChart.id" :keys="scoreChart.keys" :height="120" :colors="scoreChart.colors" unit="%"/>
            </div>`

Technology stack:  "vue": "^2.5.17",  "element-ui": "^2.15.0",  "@amcharts/amcharts4": "^4.10.10"

Description:  If the chart is shown before the percentage above it,  the chart responsive is not work.  So I put `<div v-if='!loading'></div>`  outside the <LineChart.../> to resolve the problem.  I guess whether the amcharts internal implementation of responsiveness cause the problem or not.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
