### ISSUE TITLE
Zooming to map area on click on projections Orthographic

### ISSUE THREAD

**Issue by Oleksandr07** [amcharts/amcharts4#3922]
Is there a feature that brings you closer to the country when you click, for Orthographic projections?
zoomToMapObject is good for Miller projections, but not for Orthographic projections

**Comment by martynasma** [comment]
There's no specific function for that, but you can probably do something like this demo:

https://www.amcharts.com/demos/rotate-globe-to-a-selected-country/

You can add zoom-in as well:

```JavaScript
chart.animate({ key: "rotationX", to: -centroid.longitude, duration: 1500, easing: am5.ease.inOut(am5.ease.cubic) });
chart.animate({ key: "rotationY", to: -centroid.latitude, duration: 1500, easing: am5.ease.inOut(am5.ease.cubic) });
chart.zoomToGeoPoint(centroid, 2, true, 1000);
```

https://codepen.io/team/amcharts/pen/2b94c6a3f1fd807880c10d938f78df8d?editors=0010

**Comment by Oleksandr07** [comment]
Sorry, forgot to specify. I use amCharts 4.

I use the following code:

country = polygonSeries.getPolygonById(id);
chart.animate({ property:"deltaLongitude", to:longitude :
-country.longitude }, 500);
chart.animate({ property:"deltaLatitude", to:latitude : -country.latitude
}, 500);
setTimeout(function () { chart.zoomToMapObject(country); }, 1200);

But in this case, zoom does not always work on devices with slow Internet

сб, 4 груд. 2021 о 12:34 Martynas Majeris ***@***.***> пише:

**Comment by martynasma** [comment]
That code looks good. Do you mean the code does not work on page load or on click?

I can't see how the latter not working could be related to internet connection speed.
