### ISSUE TITLE
Error with initializing ForceDirectedTree

### ISSUE THREAD

**Issue by b-art-eq** [amcharts/amcharts4#3923]
Hi,

I ran into a following problem with simple initializing ForceDirectedTree in my Angular project:

![image](https://user-images.githubusercontent.com/1481265/144905025-f3e7aa61-a570-4911-bf1d-ccf53fdb383e.png)

You can find CodeSanbox example project below:
https://codesandbox.io/s/smoosh-bird-oq7z6

Or maybe I am doing something wrong here...

**Comment by xorspark** [comment]
The main issue is that you're importing `amcharts3` - this is an amcharts4 class:

```
import { create, percent } from "@amcharts/amcharts4/core";
```

This should also come before the plugin import. While this will fix the issue, you'll want to import the charts package as well, [per the directions](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Importing_modules_scripts).

**Comment by b-art-eq** [comment]
Oh, yeah... that's the reason! Thank you!
