### ISSUE TITLE
Legent marker event

### ISSUE THREAD

**Issue by DimaGavrushko** [amcharts/amcharts4#3924]
Do I have a way to add 'hit' event listener on legend marker and legend values?

I tried to do something like that 
![image](https://user-images.githubusercontent.com/22750804/145021591-38c979a8-1424-40ef-b72f-a4fdbba7ba14.png)

but no lucks.

In acmharts3 we had event `clickMarker`

**Comment by xorspark** [comment]
You need to set `interactionsEnabled` to true on the marker and labels:

```
chart.legend.markers.template.interactionsEnabled = true;
chart.legend.markers.template.events.on("hit", function (ev) {
  console.log("clicked marker", ev.target);
});
chart.legend.labels.template.interactionsEnabled = true; 
chart.legend.labels.template.events.on("hit", function (ev) {
  console.log("clicked label", ev.target);
});
chart.legend.valueLabels.template.interactionsEnabled = true; 
chart.legend.valueLabels.template.events.on("hit", function (ev) {
  console.log("clicked value label", ev.target);
});
```

[Demo](https://codepen.io/team/amcharts/pen/e00db03f23bcbae2094f20f029f1780c?editors=0011)

**Comment by DimaGavrushko** [comment]
thanks @xorspark
