### ISSUE TITLE
Is exporting a chart from the backend possible?

### ISSUE THREAD

**Issue by shahrouritTZ** [amcharts/amcharts4#3925]
Hi,

I am trying to export the image of a chart and send it through an email from the backend.

My question is, is there an api in the sdk, that I can pass the data to and it generates the chart export image without the need for it to render?

I have searched the documentation for it, but couldn't find anything related to it

**Comment by martynasma** [comment]
Maybe with some server-side browser:

https://www.amcharts.com/docs/v4/tutorials/automating-report-generation-using-selenium-webdriver/

**Comment by shahrouritTZ** [comment]
Thank you so much, I will have a look at it now.

Closing question.
