### ISSUE TITLE
Point of intersection of two series in one chart?

### ISSUE THREAD

**Issue by facinick** [amcharts/amcharts4#3926]
I have a chart and two line series (a and b) in it.

I want to be be able to do the following:

1. get any Y value in series a, by providing any x value.
2. get (x,y) coordinate of series a and series b intersection.

these seem like fairly basic requirements when I'm plotting this chart, how can I achieve these?

**Comment by martynasma** [comment]
There's no way to calculate intersection of two line series.

There's also no way built-in functionality to calculate Y from an arbitrary X coordinate.

You can also resolve locations of actual data items to XY coordinates. But I suppose that's not what you need.

**Comment by facinick** [comment]
is it not even there in amcharts 5? this seems like a very basic thing to ask for from a charting library?

**Comment by martynasma** [comment]
No, I'm afraid. Sorry.

**Comment by facinick** [comment]
no worries! thanks for the quick response.
