### ISSUE TITLE
Tooltip is not displayed while hovering on line-chart?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3927]
Hi

I have a line-chart where time-interval is set to month by default, and i have a data of only Dec 9th - Dec 31st. I don't what's the problem with tooltip. The tooltip adapter is not triggering while hovering on the chart. I don't even get any errors. Could u help me out how to handle this.

I'm attaching a snap of it.
![Screenshot from 2021-12-10 11-18-31](https://user-images.githubusercontent.com/71019344/145523850-9a31af54-cbc1-4792-9349-9f9e9cb8c2a0.png)

Thank you.

**Comment by martynasma** [comment]
Which tooltip you have in mind? Series? Axis? One that is set directly on line segment?

If you can provide a live chart on CodePen or jsFiddle that would be great.

**Comment by meghanaNanuvala** [comment]
https://codepen.io/meghanananuvala/pen/GRMjpoz?editors=0010

In this codepen it's working fine, but in our local there we are getting line not summing to single point. I don't know what's the reason behind that and while hovering on that i'm getting below error in console.

### Error occurred:Cannot read properties of undefined (reading 'valueY') TypeError: Cannot read properties of undefined (reading 'valueY')

**Comment by martynasma** [comment]
I'm not sure about the error (I don't see it), but one thing that jumps out at me is that you have daily data for one month, yet forcing grouping to months:

```
dateAxis.groupInterval = { timeUnit: 'day', count: 1};
```

Which ends up in just one data point, and thus no line at all.
