### ISSUE TITLE
Slices overlap when in semicircle and 3D

### ISSUE THREAD

**Issue by Javier1zq** [amcharts/amcharts4#3928]
**Bug description**

When a semi circle pie chart is in 3D the slices on the right side of the chart are rendered out of order (The ones at the back are in front of the ones at the front).

Here is a codepen example, (i just turned the official [semicircle](https://www.amcharts.com/demos-v4/semi-circle-pie-chart-v4/) demo into 3D)

https://codepen.io/javier1zq/pen/VwMKmBr

This issue only appears in the top right quadrant of the cirlce (if i were to choose the start angle from 0 to 180 instead of from 180 to 360 it does not render out of order although it is inverted)

**Environment**

amCharts v4

**Comment by martynasma** [comment]
Unfortunately, we won't be able to solve this issue.

3D Pie Chart works only with startAngle of -90 (starting from the top).
