### ISSUE TITLE
Lazy Loading Bullet Images

### ISSUE THREAD

**Issue by xbaha** [amcharts/amcharts4#3930]
I am using Lazyload js to lazy load the images in my chart:
```
        var image = bullet.createChild(am4core.Image);
        image.width = mainimage;
        image.height = mainimage;
        image.horizontalCenter = "middle";
        image.verticalCenter = "middle";
-->        image.propertyFields.href = "productimage";
-->        image.userClassName = "lazyload";
```

The usage of the lazyloader js library is by replacing "href" with "data-src" and adding a class name "lazyload" :
```
<img data-src="https://..." class="lazyload">
```

I have 2 problems here:
1. The "userClassName" does not add the class to the "img" tag, it's added to the parent "g"
2. How do I add "data-src" to "img" tag ?

Thank you.

**Comment by martynasma** [comment]
I'm afraid, amCharts does not have any experience with LazyLoad library you mentioned. Though from what you are describing, I can see how it may have problems with amCharts 4, which does not use `<img>` objects, but rather SVG.
