### ISSUE TITLE
Chart numberFormatter not working correctly when combining commas, decimals and percents

### ISSUE THREAD

**Issue by BuduMcKinsey** [amcharts/amcharts4#3931]
**Bug description**

When trying to combine thousands separator, decimals and percents for the numberFormatter the result is not the one expected.
Example:
Take the number 50
For format '#%' this becomes => 5000%
For '#,##%' => 5,000%
For '#,##.##' you would expect the value to still be 10,000% or at least display 10,000.00%, but the actual value returned is '50,00%'

JSFiddle with edited yAxis numberFormat
https://jsfiddle.net/xj9s078c/

**Comment by xorspark** [comment]
FYI, your code is for v5. This is the v4 repo.

In both versions, `%` is a format code that multiplies the number by 100 and adds the percent sign. If you want to display the literal `%` sign, you need to escape it by wrapping it in single quotes. Given 50 again:

```
"#'%'" => 50%
```

v4: 
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/#Format_codes
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/#Quotes

v5: 
https://www.amcharts.com/docs/v5/concepts/formatters/formatting-numbers/#Format_codes
https://www.amcharts.com/docs/v5/concepts/formatters/formatting-numbers/#Quotes

**Comment by xorspark** [comment]
v4 may need `adjustLabelPrecision` to be disabled: https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Adjusting_label_precision

v5 should just work, but here's documentation on label formatting (and more): https://www.amcharts.com/docs/v5/charts/xy-chart/axes/value-axis/#Label_format

Note that `#` are passive. If you want to always force two decimals, use zeros.

If you're still having issues in v5, open this issue there as this is getting off topic for this repo.
