### ISSUE TITLE
selectionextremeschanged event

### ISSUE THREAD

**Issue by DimaGavrushko** [amcharts/amcharts4#3932]
When I zoom the chart the `selectionextremeschanged` event triggers not only once. I have a logic based on the current range selection. Is there an event that triggers only once after the user changes the range using zoom?

And one more question. How can I understand from the DateAxis object that the axis isn't zoomed? (user clicked on zoom out button)

**Comment by xorspark** [comment]
Animations impact how often this event is fired. Your best bet is to debounce the callback so that your logic will only fire once after a small timeout after the last call.

As for checking for whether the axis isn't zoomed, check whether the start and end properties are 0 and 1 respectively.

```
const debounce = (func, delay) => {
  let debounceTimer;
  return function() {
    const context = this;
    const args = arguments;
    clearTimeout(debounceTimer);
    debounceTimer
      = setTimeout(() => func.apply(context, args), delay);
  }
}; 

dateAxis.events.on('selectionextremeschanged', function(ev) {
  if (ev.target.start == 0 && ev.target.end == 1) {
    console.log('Zoomed out');
  }
  else {
    console.log('Zoomed to: ', new Date(ev.target.minZoomed), new Date(ev.target.maxZoomed));
  }
});
```

**Comment by DimaGavrushko** [comment]
@xorspark thanks for the quick answer. I found another approach

```
dateAxis.events.on('selectionextremeschanged', function(ev) {
  if (ev.target.isInTransition()) {
    return;
  }
  
  ....
});
```

What do you think of this?

**Comment by xorspark** [comment]
There's still a chance you getting a duplicate result in my testing with isInTransition, but if it works for you, go for it.

**Comment by DimaGavrushko** [comment]
@xorspark got you. one more question. do we have an event when the chart is rendered successfully for the user?

**Comment by xorspark** [comment]
`ready` is the event you want. If you have animations enabled and want it to fire when the chart is completely drawn, add a timeout to it.

We're straying away from the original topic of the thread. If you have any further issues or questions, please create a new thread.

**Comment by DimaGavrushko** [comment]
@xorspark okay, thanks a lot for the help
