### ISSUE TITLE
Pie Chart Tooltip Hidden

### ISSUE THREAD

**Issue by Planit-Scheduler-Solutions** [amcharts/amcharts4#3933]
Hi I use amcharts4 combine with angular 13.

I has some view with a lot of pie charts like this:
![image](https://user-images.githubusercontent.com/82387265/146146268-9306f11c-63ca-42bc-ad4d-1e3718eaebcb.png)

I also use the series tooltip feature for explain the view.
The tooltip display has some bug of hidden parts behind other pie charts:
![image](https://user-images.githubusercontent.com/82387265/146146849-6d224a8e-15f1-4e5a-8132-aad9dc575d35.png)

I expected to see the series tooltip up to all pies.

But it looks like if we work 'ltr' the left part of the tooltip is up the left pies and the right part is behind the right pies:

The left part is UP:
![image](https://user-images.githubusercontent.com/82387265/146147647-5ad7a8f5-e258-4e4b-9f95-32dd5ae61872.png)

I tried to play with z-index without any result.

This is the way how I create the series:

`
const pieSeries = this.donutChart.series.push(new am4charts.PieSeries());
pieSeries.slices.template.propertyFields.tooltipText = 'tooltipFormat';
pieSeries.tooltip.label.fontSize = '0.75rem';
`

How can I get the result that I expected(tooltip up to all pies)?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
