### ISSUE TITLE
amcharts4: tell me how to optimize lineChart memory

### ISSUE THREAD

**Issue by skulter** [amcharts/amcharts4#3934]
I am currently showing charts using lineChart among amChart4.
It shows 7 charts on one page, and each chart shows about 100,000 data.
At this point, Chrome's memory is 3,000mb to 4,000mb, and I wonder if there is another way to optimize the memory.
I tested in amchart3 with a similar amount of data, but only half the memory of amchart4 is used.
Is there any way I can reduce the memory?
![image](https://user-images.githubusercontent.com/18344213/146147022-a7c48ffb-67a0-4abe-ab21-486477e68873.png)

**Comment by zeroin** [comment]
V4 will always take more memory than v3, as it uses a much more complicated structure. When working with such amounts of data I would strongly recommend using v5 instead.
