### ISSUE TITLE
CategoryAxis collapsing

### ISSUE THREAD

**Issue by Aliaksandr-Yanushkevich** [amcharts/amcharts4#3935]
**Question**

@martynasma  Hi! I faced with strange chart behaviour. CategoryAxis is collapsed after new data is received. Could you help me to fix it?

![collapse_example](https://user-images.githubusercontent.com/51059670/146315977-a3a6aea7-ce36-4f50-ade3-0711b9114c64.gif)

I noticed that if **category names** is not changed, chart is rendered right way. I can add/remove series on the chart and it looks good. But If I fetch other data with other **category names** first time category axis is collapsed. This bug dissapears when I add new series (**category names** stays the same). It seems to me this is race condition and category Axis has not actual state during series creating. It is looks strange for me because I believe that setting ```chart.data``` is syncronious action and I do it BEFORE creating the series.

Here function for creating series

```
export const createSeries = (chart, categoryAxis, {name, data}, color) => {
    // set chart data
    chart.current.data = [...chart.current.data, ...data];

    // create series
    const series = chart.current.series.push(new am4charts.LineSeries());

    series.name = name;
    series.dataFields.valueY = 'value';
    series.stroke = am4core.color(color);
    series.xAxis = categoryAxis.current;
    series.dataFields.categoryX = 'date';
    series.data = data;

    const bullet = series.bullets.push(new am4charts.Bullet());
    bullet.propertyFields.showTooltipOn = "showTooltip";
    bullet.tooltipText = "{label} ({date}): [bold]{value}[/]";
    bullet.fill = am4core.color(color);

    const circle = bullet.createChild(am4core.Circle);
    circle.width = 10;
    circle.height = 10;
    circle.horizontalCenter = "middle";
    circle.verticalCenter = "middle";
}

```

And of course I reset **chart.data** in useEffect
```
 chart.current.data = [];

 chartData.forEach((data) => {
   const color = data.color;

   createSeries(chart, categoryAxis, data, color);
})
```

 amCharts version ^4.10.18

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Aliaksandr-Yanushkevich** [comment]
@martynasma During creating example on CodePen I'd found bug in useEffect in my code. Issue can be closed.
