### ISSUE TITLE
Regarding GroupInterval

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3936]
Hi

I wonder in my application 
`dateAxis.groupInterval = { timeUnit: 'month', count: 1};`
the above line is not working in my code.

i'm getting below error: 
error TS2551: Property 'groupInterval' does not exist on type 'DateAxis<AxisRenderer>'. Did you mean 'groupIntervals'?

Could u tell me the reason behind that

**Comment by meghanaNanuvala** [comment]
Even i asked before too https://github.com/amcharts/amcharts4/issues/2957
![Screenshot from 2021-12-16 12-54-05](https://user-images.githubusercontent.com/71019344/146326321-87ec5547-db5b-4fc7-b634-dd8e4876b455.png)

**Comment by martynasma** [comment]
That's because `xAxes` is typed to just `Axis`.

You have two options:

1) Add type hind to the compiler:

```JavaScript
const dateAxis: am4charts.DateAxis = chart.xAxes.push(new am4charts.DateAxis());
```

2) Create DateAxis separately then push it:

```
```JavaScript
const dateAxis = new am4charts.DateAxis();
chart.xAxes.push(dateAxis);
```

**Comment by meghanaNanuvala** [comment]
it's working fine but i'm still getting that error.

![Screenshot from 2021-12-16 13-27-41](https://user-images.githubusercontent.com/71019344/146331006-eec7761a-365b-47cd-bf8e-553daf0ac940.png)

**Comment by martynasma** [comment]
It should be good to go.

Which version of amCharts 4 and TypeScript are you using?

**Comment by meghanaNanuvala** [comment]
For Amcharts4 : 4.9.16
typecript : 2.9.2

**Comment by martynasma** [comment]
TypeScript seems to be fine.

Try upgrading to the latest version of amCharts (4.10.23)

**Comment by meghanaNanuvala** [comment]
how to update that ?

**Comment by martynasma** [comment]
Most probably via `package.json` file then running `npm i` or something else that you use to install dependencies.

**Comment by meghanaNanuvala** [comment]
yeah got it.

Thanks
