### ISSUE TITLE
amchart5 Why is there a blank space next to the chart?

### ISSUE THREAD

**Issue by skulter** [amcharts/amcharts4#3937]
I am making a lineChart using amchart5.
I am changing from amchart4 to amchart5, but only in amchart5, spaces are created on both sides of the chart.
For what reason is it made?
![image](https://user-images.githubusercontent.com/18344213/146325947-384ea6c5-f5ca-4969-9568-7850a71611cf.png)

**Comment by martynasma** [comment]
This is a repo for amCharts 4. Please use [amCharts 5 repo](https://github.com/amcharts/amcharts5/) for questions related to it.

**Comment by skulter** [comment]
oh! Sorry.. Thank you!
