### ISSUE TITLE
How to show same axis bullets of all series' present when hovered over on any series?

### ISSUE THREAD

**Issue by abhaypatil87** [amcharts/amcharts4#3938]
**Question**
I have a design of a XY series chart as below. As you can see, when hovering over at any one series, all the bullets from all other series are being shown. I found a similar example in [this](https://www.amcharts.com/docs/v4/tutorials/show-series-bullets-on-category-date-hover/) demo tutorial, but it doesn't have the tooltip visible. When the tooltip is made visible, it's being shown on all the bullets. However, I want only a single tooltip to be visible.

Design:
![Screen Shot 2021-12-16 at 09 31 17](https://user-images.githubusercontent.com/8400709/146420301-73515788-b028-40d2-b122-f656c4c45ed8.png)

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
> When the tooltip is made visible, it's being shown on all the bullets. However, I want only a single tooltip to be visible.

You can limit it to only one tooltip using `maxTooltipDistance`:

https://www.amcharts.com/docs/v4/concepts/chart-cursor/#Limiting_number_of_series_tooltips

**Comment by abhaypatil87** [comment]
If I set the _maxTooltipDistance_ property to -1, I can see only one tooltip for all the series which is what I want, but it won't highlight all the bullets of all the other series just like the design I have attached. Any idea how to achieve that particular behaviour?

**Comment by martynasma** [comment]
Gotcha.

In that case you should probably set up events on chart cursor to be triggered when it moves, then manually trigger hover state on all bullets in the same date.

I know it sounds vague, but I don't have a ready-made example for that :(
