### ISSUE TITLE
Data labels wraping work incorrectly

### ISSUE THREAD

**Issue by CaptainHoangLe** [amcharts/amcharts4#3939]
I am using amchart4 "^4.10.22" , my dataLabels 's piechart are two long so i used wrap and maxWidth properties.
However, my value labels is broken line incorrectly like that 
![bug](https://user-images.githubusercontent.com/53038465/146490993-0f7f3302-17ed-4037-ab95-a9f778ec7775.png)
Please help me to slove this problem . Thanks so much

**Comment by martynasma** [comment]
Just to make sure: do you mean the break in the middle of "3.13M"?

**Comment by CaptainHoangLe** [comment]
> Just to make sure: do you mean the break in the middle of "3.13M"?
Yep, "3.13M" is my expected value

**Comment by CaptainHoangLe** [comment]
And in some situation , Labels is overlapped
![image](https://user-images.githubusercontent.com/53038465/146504229-a8dad0a6-1c3e-44fe-8666-ef5b3e48628f.png)

**Comment by martynasma** [comment]
We'll fix number wrapping in the next version. I'll notify you here when new version is out.

As for label overlapping, the only way to make them check for overlapping is to not disable `alignLabels`.

**Comment by CaptainHoangLe** [comment]
> We'll fix number wrapping in the next version. I'll notify you here when new version is out.

Thanks for your reply, I am looking forward to hearing from you soon

**Comment by martynasma** [comment]
Fixed in 4.10.24.
