### ISSUE TITLE
Setting the category axis line color

### ISSUE THREAD

**Issue by goodmorninggoaway** [amcharts/amcharts4#3940]
**Bug description**

I cannot figure out how the change the color of the line on the category axis. I've tried setting the stroke/strokeWidth on many container and background elements. 

https://codesandbox.io/s/sad-kilby-qplo9?file=/src/App.tsx

**Additional context**
![Untitled](https://user-images.githubusercontent.com/5576375/146844079-2883ccfc-9e9e-40c0-ae08-e804d5d4fe31.jpg)

The line is in the red box. If you look closely, the line is a darker grey than the gridlines. This does not appear to be the zero line, nor is it a grid line.

**Comment by xorspark** [comment]
The axis line is configured on the axis render's `line` object as documented [here](https://www.amcharts.com/docs/v4/concepts/axes/#The_axis_line):

```
categoryAxis.renderer.line.strokeOpacity = 1;
categoryAxis.renderer.line.strokeWidth = 2;
categoryAxis.renderer.line.stroke = am4core.color("#3787ac");
```

**Comment by goodmorninggoaway** [comment]
Thanks for the fast response. I don't think that's it. I set a fat stroke to highlight it
```
categoryAxis.renderer.line.strokeOpacity = 1;
categoryAxis.renderer.line.strokeWidth = 20;
categoryAxis.renderer.line.stroke = am4core.color("#3787ac");
```

![image](https://user-images.githubusercontent.com/5576375/146846327-eab1e655-229e-4d04-afc2-80d08ad05cf3.png)

This is the DOM for that dark line if if jogs your memory; deleting that group element removes the line
![image](https://user-images.githubusercontent.com/5576375/146846499-7e473405-900c-4e6b-937b-f7ddca561516.png)

**Comment by xorspark** [comment]
That line *is* the zero line, which is the `baseGrid`. You can style that like so:

```
valueAxis.renderer.baseGrid.stroke = "#ff0000";
valueAxis.renderer.baseGrid.strokeOpacity = 1;
valueAxis.renderer.baseGrid.strokeOpacity = 2;
```

**Comment by goodmorninggoaway** [comment]
Thanks @xorspark 

For anyone else who runs into this: This is the zero line for the **value axis**, the x-axis. In retrospect, it was obvious.
