### ISSUE TITLE
A tooltip bug was found in the mobile environment.

### ISSUE THREAD

**Issue by skulter** [amcharts/amcharts4#3941]
that bug is
Also available at https://www.amcharts.com/demos/data-grouping-50k-points/

After accessing the address in the mobile environment
After zooming in by dragging the chart, click the '-' button to view the entire chart again.
Clicking on another area reproduces the tooltip not displaying properly and out of focus.

I want to upload a video file, but I don't know how to deliver it, so I left it as text.

Please check the bug.

**Comment by martynasma** [comment]
The demo you referring is amCharts 5, whereas this is a repo for amCharts 5.

If you still think this is a bug, please repost to [proper repo](https://github.com/amcharts/amcharts5/issues).
