### ISSUE TITLE
Duplicated chart data when remove a series range using series.axisRanges.removeValue(range) in Amcharts 5

### ISSUE THREAD

**Issue by gsi-chao** [amcharts/amcharts4#3942]
I try to eliminate ranges attached to a series using amcharts 5, but in the chart the data is duplicated, I am using the function series.axisRanges.removeValue (range);

`
    var rangeDataItem = xAxis.makeDataItem({
              value: value,
              endValue: endValue,
          })
    var range = lineSerie.value.createAxisRange(rangeDataItem)
`

Enviroment
VueJS 3
Amchart 5

![image](https://user-images.githubusercontent.com/32143683/147127933-07709f71-a308-4eb2-970e-6bcac2477d7f.png)

**Comment by xorspark** [comment]
Please post your v5 issue in the [amcharts5 repo](https://github.com/amcharts/amcharts5/issues). This is for v4.

**Comment by gsi-chao** [comment]
Thanks
