### ISSUE TITLE
Links to CDN do not work

### ISSUE THREAD

**Issue by Sequential-circuits** [amcharts/amcharts4#3943]
File not found: https://cdn.amcharts.com/lib/5/lang/de_DE.js

File not found: https://cdn.amcharts.com/lib/5/themes/animated.js

File not found: https://cdn.amcharts.com/lib/version/5.0.18/lang/de_DE.js

File not found: https://cdn.amcharts.com/lib/version/5.0.18/themes/animated.js

**Comment by martynasma** [comment]
This is is a repo for amCharts 4, so I'm gonna go an close this as off-topic.

But thanks for bringing it to our attention! The URLs on our Download page were incorrect, that now been fixed.
