### ISSUE TITLE
LINKS DO NOT WORK

### ISSUE THREAD

**Issue by Sequential-circuits** [amcharts/amcharts4#3944]
Plenty of links to CDN that do not work, even though they are listen in the manual

For example https://cdn.amcharts.com/lib/5/pie.js

Truly annoying and makes this useless

**Comment by martynasma** [comment]
This is is a repo for amCharts 4, so I'm gonna go an close this as off-topic.

But thanks for bringing it to our attention! I found some stray incorrect links in our docs page and fixed them.

If you happen to stumble upon any other documentation issues, please do let us know in [amCharts 5 repo](https://github.com/amcharts/amcharts5/issues) with links to docs pages that have issues.

Thanks once again!
