### ISSUE TITLE
Handling cursor selectionend event causes strange behavior

### ISSUE THREAD

**Issue by alessandrovir** [amcharts/amcharts4#3945]
Hi all, 

I am currently implementing a bubble graph like this one

https://www.amcharts.com/demos-v4/animated-xy-bubble-timeline-chart-v4/

In my implementation I need a way to select some bubbles.
To do this I defined a cursor 
```
this.chart.cursor = new am4charts.XYCursor();
this.chart.cursor.behavior = 'selectXY';
```
I handled the event 
`chart.cursor.events.on('selectended', ev => { some stuff to filter current data});`

This logic works as expected.

The problem is with the selection itself that is a bit buggy in my opinion.

To give an idea you can check this example 
https://codepen.io/team/amcharts/pen/gKYmEL
that has the same strange behavior

If I make a selection with the left mouse button and i drag the selection till the end, the alert appaears correctly.
if I only click with the left button, the selection starts and i am not able not finish it, clicking again left button starts a new selection. And also, the selection does not trigger the alert.
I need some way to reset the selection logic if i am not clicking while selecting.

I tried also to handle the `events chart.cursor.events.on('up', {}=>())` but this is not fired 

Then I need also a way to avoid to start the selection if, f.e. i click on the right mouse button or I click a combination of left click + ctrl key.

In my idea I am trying to do something like:
- if i click the left mouse button and, without relasing it, select and area, perform the selection, trigger the alert and reset the selection.
- If i click the left mouse button (or right button , or combination of left + ctrl key) and relase it, nothing has to happen

Thank you in advance

**Comment by martynasma** [comment]
The problem is that when you just click, resulting event does not produce a "range" value, which in turns make handler code error out and stop any further code execution.

I have updated the CodePen as well as related docs article to check for range:

```JavaScript
chart.cursor.events.on("selectended", function(ev) {
  if (range) {
    var range = ev.target.xRange;
    var axis = ev.target.chart.xAxes.getIndex(0);
    var from = axis.getPositionLabel(axis.toAxisPosition(range.start));
    var to = axis.getPositionLabel(axis.toAxisPosition(range.end));
    alert("Selected from " + from + " to " + to);
  }
});
```

**Comment by alessandrovir** [comment]
@martynasma  thank you! 
Now it works as expected
