### ISSUE TITLE
adding a Property and value to a button element created by amCharts

### ISSUE THREAD

**Issue by jswelsh** [amcharts/amcharts4#3946]
**Question**
Thanks in advance. 

I've been stumbling on this one for a bit now and have tried to apply some of the properties [of the button](https://www.amcharts.com/docs/v4/reference/button) 
I want to add **data-cy** property with a value of "somethingHereForTesting" on the amcharts button.  

I instantiate a button like so 
```
      let buttonContainer = chartRef.current.plotContainer.createChild(am4core.Container);
      buttonContainer.shouldClone = false;
      buttonContainer.zIndex = Number.MAX_SAFE_INTEGER;
      buttonContainer.marginTop = 5;
      buttonContainer.layout = "horizontal";

      let button = buttonContainer.createChild(am4core.Button);
      button.label.text = 'This button';
      button.events.on("hit", function() {
        doSomething()
      });
      button.icon = new am4core.Sprite();
      button.icon.path = 'M2 1 h1 v1 h1 v1 h-1 v1 h-1 v-1 h-1 v-1 h1 z';
      button.icon.scale = 5;
      button.background.cornerRadius(50,50,50,50);
```
the dom element looks like this 
`<g role="button" focusable="true" tabindex="0" transform="translate(0,-8.5)">`
I want it to look like this
`<g data-cy="somethingHereForTesting" role="button" focusable="true" tabindex="0" transform="translate(0,-8.5)">`

any help in the direction I should look or if I'm missing a demo/doc then that would great greatly appreciated.

Cheers

**Environment (if applicable)**
amCharts
React
Cypress

**Additional context**

**Comment by martynasma** [comment]
Something like this should do the trick:

```JavaScript
button.group.node.setAttribute("data-cy", "somethingHereForTesting");
```

**Comment by jswelsh** [comment]
That did the trick. 

Greatly appreciated
