### ISSUE TITLE
Need to put SVG image inside the logo

### ISSUE THREAD

**Issue by abhiseksubham** [amcharts/amcharts4#3947]
Hi ,

I am creating a tooltip like this and trying to place a logo inside this.

`		series.columns.template.tooltipText = `
          Total  <img src ${logo}>  </img>  $${props.data.data[0].value}M`;`

This isn't working so far. Is there a way to use SVG images inside the tooltip ?

**Comment by abhiseksubham** [comment]
= to is left intentionally.

**Comment by martynasma** [comment]
Yes, use `tooltipHTML` instead of `tooltipText`.

In it you can use any HTML including images.
