### ISSUE TITLE
slow render performance while updating chart

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#395]
hello,

with an angular6 application, no particular "things" if i do an update via

     this.amChart.addData(arr);

with length of 2-3 elements (for arr) into a data (already loaded) of 100 elements

i got

zone.js:2052 [Violation] 'requestAnimationFrame' handler took 122ms
zone.js:2052 [Violation] 'requestAnimationFrame' handler took 96ms
zone.js:2052 [Violation] 'requestAnimationFrame' handler took 101ms

and every redraw it's very slow, in chrome on macosx

data it's with 2 series, 2 axis, line with fill color with alpha (not sure if it can help)

i also have do
    am4core.unuseTheme(am4themes_animated);
not sure if it help reducing animations, but i try without improvement

**Comment by ramarro123** [comment]
a little followup, if i do "am4core.useTheme" with animated, i see the animations and the notice 'requestAnimationFrame' took xxx disappear.

also the redraw, even if animated, look less laggy, i am not sure why

**Comment by eliashdezr** [comment]
I also have noticed that amcharts setup and rendering is very slow, regarding the theme you use or without animations. When I enter in my component with any chart from amcharts, it takes around 120ms to render a simple chart from their demos using static data.

There's something weird with this because using echarts with way more data, rendering the same type of chart takes around 10ms or less.

Also disposing the chart takes around 80ms.

**Comment by guylando** [comment]
Same problem here if you put a numeric range slider and move it and update chart while moving the slider then there is a serious lag

**Comment by eliashdezr** [comment]
I put some console time in one of the official examples: 
https://codepen.io/anon/pen/JaggOg

**Comment by ramarro123** [comment]
i don't think that the test show anything of useful, it just benchmark the loading of data.
if i have understood well, the code run on a requestanimation frame, after the data it's loaded, am i right?

**Comment by martynasma** [comment]
@ramarro123 Correct.

amCharts 4 works in async fashion. Any objects created and any settings or data are not applied immediately, but only on the next animation frame.

So we still need some kind of working example to investigate this.

**Comment by guylando** [comment]
rerender your pie charp with legends with number of points in data as appears in the value of this numeric range slider https://refreshless.com/nouislider/
you will see that as you move the slider the chart update happens with a great lag.
This is a major bug so as you are a commercial company one would expect you to put a few minutes into investing this yourself and creating example yourself as described.
This issue wasn't handled for 6 days and basically prevents from using amcharts in places which require good performance.

**Comment by guylando** [comment]
https://codepen.io/team/amcharts/pen/a961369695c27802865524c92a1f1529?editors=1010
If you drag quickly the slider from left to right then you will see a delay of up to a second the slider being stuck

**Comment by ramarro123** [comment]
confirmed, it's terribly slow.
on mobile it's not even usable

**Comment by martynasma** [comment]
@xorspark offered a good workaround to the UX issue where slider gets stuck.

While we are working and will continue working on improving the performance of the charts, I doubt it's even possible to make the chart load/update in such a way that it completely does not impede on browser.

The slider is not some system control. It's an element in DOM, which is being manipulated by JavaScript, just like the chart is DOM element being manipulated by JavaScript. If one script is doing something, the other is waiting, hence the lag.

Even if we make the chart update 3x faster, the continues update issue will still be prominent. So debouncing updates is a good practice altogether.

That said, we'll keep look for ways to make charts faster.

In the interim, we appreciate your patience. And thanks for testing the pre-release software!

**Comment by ptorrent** [comment]
maybe it would be nice to have the same example with echart ? In this case, I'm not sure it's bette with echart..

**Comment by guylando** [comment]
Of course I am debouncing and it doesnt solve the lag. Your debounce interval is too big and anyway there is an obvious lag.

Using echarts to create the same chart updating with same debounce and with same slider creates a chart where the update is immediate. When moving slider when using echarts, the chart changes instantaneously.

**Comment by martynasma** [comment]
I have a request - let's not derail the discussion by introducing comparisons with other products. You're here because you've chosen to use amCharts. Your input is very valuable, and we are working towards making our product better. We'll keep you guys posted.

**Comment by zeroin** [comment]
Just a quick note - we have improved overall performance of all charts in yesterdays release, you are welcome to try. By the way, I am not sure if the chart in the demo is really what you want to achieve, but in case it is, then I would recommend to use series.zoom and legend.zoom methods to show the desired range of data points instead of invalidating data, as this doesn't require new DOM objects to be created and is much faster. Even if your data changes, you can modify values on data items directly or change them in your data objects and call chart.invalidateRawData(). This will also prevent the chart from being rendered from zero.

**Comment by guylando** [comment]
@zeroin if that is more efficient then why not to optimize chart data property setter to do exactly that?

**Comment by martynasma** [comment]
@guylando Because we cannot possibly assume that user is replacing data set with structurally identical one.

**Comment by martynasma** [comment]
@ramarro123 beta.64 should solve any freezin/update issues. I'm going to go ahead and close this, but feel free to reopen, or post any follow up questions, if you're still seeing any deal-breaking performance issues.

**Comment by guylando** [comment]
@zeroin @martynasma 
https://codepen.io/team/amcharts/pen/a961369695c27802865524c92a1f1529?editors=1010
move the slider first to the right most part and then move quickly to the left, as you will see it isn't very smooth. One thing I can see that might be improved is that maybe when splitting rendering to chunks then should first render the most visually significant things like the legends images. Also in your rendering do you abort previous rendering when new rendering is requested?

**Comment by zeroin** [comment]
Yes, previous renderings are aborted. As for non smooth rendering of this particular chart then I must admit that 3d slices are not made well at the moment, we plan to revisit this which will make it more smooth.

**Comment by cpati-kochava** [comment]
We are still seeing significant performance issues with amCharts4. The interesting part is amCharts3 is considerably faster rendering charts. We have side by side charts using the same data, graphs/series, no animation and in some instances amCharts4 even displays a loader whereas amCharts3 almost instantly displays the chart. 

Like others mentioned, there is definitely something weird going on as far as rendering the amCharts4 charts is concerned. We're currently even considering reverting back to amCharts3. 

Vue 2.6.x
amCharts 4.5.16
configurations are based on example setups

**Comment by leeoniya** [comment]
if you guys are intested in a fast time-series chart, here's a shameless plug: https://github.com/leeoniya/uPlot
