### ISSUE TITLE
Memory leak when dynamically removing Series to XYChart

### ISSUE THREAD

**Issue by T-Grave** [amcharts/amcharts4#3950]
**Bug description**
If you remove and add Series often for one single XYChart chart, a serious memory leak becomes apparent.
This is because every Series that has every been added to a chart stays referenced in a very specific Disposer that gets added for every Series.

I've already pinned down the culprit to the following line:

https://github.com/amcharts/amcharts4/blob/097703c0ba0415d243c8b257dad2885d70157830/src/.internal/charts/types/SerialChart.ts#L309

Without knowing exactly what the code does, I do feel like it is code that is specifically tied to each Series, so maybe it makes more sense to use `series.addDisposer` so the event listener gets cleaned up whenever the series is disposed, instead of the chart.

**Comment by zeroin** [comment]
Could you provide us with a codepen of the exact chart where this leak can be reproduced?
