### ISSUE TITLE
Full world map

### ISSUE THREAD

**Issue by monolithed** [amcharts/amcharts4#3951]
Maybe is there a world map with the following state formations?

Abkhazia
Azad Kashmir
Azores
Åland Islands
Ambazonia
American virgin islands
American samoa
England
Antarctica
Aruba
Artsakh
Ashmore Islands
Bermuda
British Virgin Islands
Waziristan
Outer Small Islands (USA)
Guadeloupe
Guernsey
Gibraltar
Hong Kong
Greenland
Guam
Jersey
West Sahara
Canary Islands
Cocos islands
Kosovo
Kurdistan
Curacao
Mayotte
Macau
Order of Malta Palace of Malta
Montserrat
Nakhichevan Autonomous Republic
Niue
Isle of Maine
Wallis and Futuna Islands
Cayman islands
Cook Islands
Turks and Caicos Islands
Palestine
Panama
Papal See (Vatican City State)
Pridnestrovian Moldavian Republic (Transnistria)
Puerto Rico
Northern Ireland
Northern Mariana Islands
Northern Cyprus
Saint Martin
Sint Maarten
Sint Eustatius
Somaliland
Taiwan
Tokelau
Wales
Faroe Islands
Falkland Islands
French polynesia
Scotland
Spitsbergen
South Ossetia

**Comment by martynasma** [comment]
I don't think we have a map like that. However, you can use World map and just include the countries that you need:

https://www.amcharts.com/docs/v4/chart-types/map/#Including_and_excluding_objects
