### ISSUE TITLE
Animation on Gaugechart hand

### ISSUE THREAD

**Issue by mahsashadi** [amcharts/amcharts4#3953]
Hi :)
I draw a GaugeChart. 
i used `hand.showValue(710);`
I need some animation, i.e, its hand move from 0 to its set value once the page is rendering.

**Comment by martynasma** [comment]
The second parameter to [`showValue()`](https://www.amcharts.com/docs/v4/reference/clockhand/#showValue_method) method is number of milliseconds. Set it to play animation:

```JavaScript
hand.showValue(710, 2000);
```
