### ISSUE TITLE
Set empty space left and right from chart

### ISSUE THREAD

**Issue by Aliaksandr-Yanushkevich** [amcharts/amcharts4#3954]
**Question**
Hi. I want to add free space left and right from chart. As I understood, amcharts adds this space automatically and it's equal half of distance between two categories. Is it possible to set this space manually (30px for example)? 

**Environment (if applicable)**
amcharts 4.10.18

codepen example https://codepen.io/aliaksandr-yanushkevich/pen/OJxpooJ

![image](https://user-images.githubusercontent.com/51059670/148699631-b1b8b787-092d-48fb-85ed-60db5b8c7d7a.png)

**Comment by Aliaksandr-Yanushkevich** [comment]
@martynasma

**Comment by martynasma** [comment]
There's no way to set this space using pixels. You can control relative space, though:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

**Comment by Aliaksandr-Yanushkevich** [comment]
Thank you for the answer! Set empty space left and right from chart. It might be useful for someone:
```
 const valueAxis = useRef(null);
 const categoryAxis = useRef(null);

 useEffect(() => {
            const hitsCountAndPaddingMap = {
                50: 0.5,
                100: 2,
                150: 3
            }
// There's no way to set empty space left and right from chart using pixels. https://github.com/amcharts/amcharts4/issues/3954
// but we can control relative space. my logic is based on chart hits amounts. values in hitsCountAndPaddingMap are
// number of empty sections before and after chart area.

// hitCounts - number of categories on the chart

            const counts = Object.keys(hitsCountAndPaddingMap);
            const closest = counts.reduce(function (prev, curr) {
                return (Math.abs(curr - hitsCount) < Math.abs(prev - hitsCount) ? curr : prev);
            });

            const padding = hitsCountAndPaddingMap[closest];

            categoryAxis.current.startLocation = -padding;
            categoryAxis.current.endLocation = padding + 1;
        }, [hitsCount])
```
