### ISSUE TITLE
Display bullet tooltips separately from series tooltips

### ISSUE THREAD

**Issue by JamesDolphin** [amcharts/amcharts4#3955]
I am trying to progromatically display bullets on a multi series line chart and have the tooltip from said bullet override the existing series tooltip when hovered.

     
        for (const group of axi.metricGroupGroups) {
        let series: am4charts.LineSeries = chart.series.push(new am4charts.LineSeries());

        series.dataFields.valueY = `value${group.name}`;
        series.dataFields.dateX = `date${group.name}`;

        series.tensionX = axi.smoothingFactor;
        series.tensionY = axi.smoothingFactor;

        series.strokeWidth = 2;
        series.yAxis = valueAxis;
        series.name = group.name;
        series.tooltipText = "{name}: [bold]{valueY}[/]";

        let bullet = series.bullets.push(new am4charts.Bullet());
        let square = bullet.createChild(am4core.Rectangle);
        square.width = 15;
        square.height = 15;
        square.propertyFields.visible = `hasNotes${group.name}`;
        square.tooltipText = `{notes${group.name}}`;

        // square.hoverable = true;
        // square.events.on("over", function(ev) {
        //   series.tooltipText = `{notes${group.name}}`;
        // })
        
        // square.events.on("out", function(ev) {
        //   series.tooltipText = "{name}: [bold]{valueY}[/]";
        // })
      }
      
      
The above code will render the bullets as required but the series.tooltipText will override the sqaure.tooltipText
      
As you can see via the commented code I tried to implement the idea provided here: #3104 but that solution only seems appropriate for single series line charts as doing this will leave the tooltips for other series blank. 
      
Here is what the issue is when using the #3104 fix on a multi series line chart.

Tooltips no longer show on series that do not have bullets

![image](https://user-images.githubusercontent.com/29121533/148708733-03f5b7d2-5499-45c8-b3a3-48de3a6e1726.png)

What would be an appropriate approach to fix this?

**Comment by zeroin** [comment]
I am not sure if this helps in your case, but try to create a separate tooltip for bullets:
https://codepen.io/team/amcharts/pen/951ddf9b876ca9aeef51109f34e5cdbc?editors=0010
