### ISSUE TITLE
Prevent panning when force graph chart is overlapped by another element?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts4#3956]
Hi again :)

For reference, here's a low-res picture:
![image](https://user-images.githubusercontent.com/29444592/148967671-bcbb7b71-797e-42bf-a195-746d449ed299.png)

The menu at left overlaps the space containing the chart: since clicking on the chart space (in addition to the chart itself) allows for panning the view, and since the menu is `absolute`ly positioned over the chart's space, panning still works when clicking and dragging with the mouse over the menu.

I'm curious to know if there's currently a way to prevent panning when the chart is overlapped?

The UI is being developing in TS and TSX, if that helps any. I'd done some searching into this already, but didn't find anything that struck me as the answer.

Thank you so much!

**Comment by martynasma** [comment]
To temporarily disable all interactivity of the chart use this:

```JavaScript
chart.interactionsEnabled = false;
```

Reset it back to `true` afterwards.

**Comment by jonofoz** [comment]
@martynasma Thanks for the tip! I'll have to see if I can integrate that into a solution. Cheers!
