### ISSUE TITLE
Need to create a Geographical chart as below, which component can i use

### ISSUE THREAD

**Issue by abhiseksubham** [amcharts/amcharts4#3957]
[](url
![Screenshot 2022-01-12 at 12 12 44 PM](https://user-images.githubusercontent.com/2356647/149077667-0cc97fb4-5789-4fb5-bf5f-28df17efe9cc.png)
)

**Comment by zeroin** [comment]
Here is a demo: https://www.amcharts.com/demos/us-heat-map/ 
It's AmMap component + Heat Legend
