### ISSUE TITLE
categoryAxis.renderer.gridType = "polygons" dose not work

### ISSUE THREAD

**Issue by allgrowsm** [amcharts/amcharts4#3959]
**Bug description**
I set to gridType to polygons.
However, circle graph is displayed sometimes.
It dose not happend alyways, but, sometimes...

This is just strage to me.

Do you have any suggestion for this?

![image](https://user-images.githubusercontent.com/19646090/149502418-7b4c309b-6f86-480a-ba22-a162044de4ab.png)

```
[
  {
    "category": "A",
    "lowLayer": 30,
    "candidate": 21,
    "average": 36.965802469136
  },
  {
    "category": "B",
    "lowLayer": 30,
    "candidate": 23,
    "average": 38.834074074074
  },
  {
    "category": "C",
    "lowLayer": 30,
    "candidate": 24,
    "average": 37.580864197531
  }
]

```

```
  var chart = {};
  chart['inteligence_ability'] = am4core.create("chartdiv02", am4charts.RadarChart);
  chart['inteligence_ability'].dataSource.url = "/api/myurl";
  chart['inteligence_ability'].dataSource.load();

  var valueAxis = chart['inteligence_ability'].yAxes.push(new am4charts.ValueAxis());
  valueAxis.renderer.gridType = "polygons";
  valueAxis.max = 80;
  valueAxis.min = 0;

  /* Create axes */
  var categoryAxis = chart['inteligence_ability'].xAxes.push(new am4charts.CategoryAxis());
  categoryAxis.dataFields.category = "category";
  categoryAxis.fontSize = 18;
  categoryAxis.fontWeight = 'bold';
  categoryAxis.renderer.gridType = "polygons";

  /* Create and configure series */
  var series3 = chart['inteligence_ability'].series.push(new am4charts.RadarSeries());
  series3.dataFields.valueY = "lowLayer";
  series3.dataFields.categoryX = "category";
  series3.name = "A";
  series3.strokeWidth = 3;
  series3.fillOpacity = 0.5;
  series3.stroke = am4core.color("#02928a");
  series3.fill = am4core.color("#cde9e7");

  /* Create and configure series */
  var series2 = chart['inteligence_ability'].series.push(new am4charts.RadarSeries());
  series2.dataFields.valueY = "average";
  series2.dataFields.categoryX = "category";
  series2.name = "B";
  series2.strokeWidth = 3;
  series2.fillOpacity = 0.5;
  series2.stroke = am4core.color("#d6d132");
  series2.fill = am4core.color("#f7f7da");

  /* Create and configure series */
  var series = chart['inteligence_ability'].series.push(new am4charts.RadarSeries());
  series.dataFields.valueY = "candidate";
  series.dataFields.categoryX = "category";
  series.name = "C";
  series.strokeWidth = 3;
  series.fillOpacity = 0.5;
  series.stroke = am4core.color("#d74588");
  series.fill = am4core.color("#f6dae7");
```

**Comment by martynasma** [comment]
It does work for me:
https://codepen.io/team/amcharts/pen/cbceb00ecd4f9334acf61d8fbcc9b8f4?editors=0010

**Comment by allgrowsm** [comment]
@martynasma 
Thanks for  reply.
Well...I found one thing about this.

My shared source code is within am4core.ready(function () {}).

When I take my source code from that, it displays correctly.

**Comment by martynasma** [comment]
Nope. Still working even enclosed in `am4core.ready()` :)

https://codepen.io/team/amcharts/pen/cbceb00ecd4f9334acf61d8fbcc9b8f4?editors=0010

**Comment by allgrowsm** [comment]
@martynasma 
Thanks for reply.
Well...this is very storage.
Sometimes, when I first load the graph, it is okay.
But, when I use browser refresh button, it is not polygon.

Now, I will explain more about how I wrote my program.

I have 5 graphs like following.
https://www.amcharts.com/demos-v4/column-chart-with-axis-break-v4/

Also, my program is like this.

```
am4core.options.queue = true;
am4core.options.onlyShowOnViewport = true;

am4core.ready(function () {
 // I have graph  1
});
am4core.ready(function () {
 // I have graph 2
});
am4core.ready(function () {
 // I have graph  3
});
```

Do you think multiple enlosed am4core.ready() causing this bug?

**Comment by martynasma** [comment]
> Do you think multiple enlosed am4core.ready() causing this bug?

I doubt it. Pretty easy to test this, though. Just move everything into a single `read()` callback, or completely out of it.

Also, would you be able to create a CodePen with exact setup that you have which would exhibit this behavior so that we can test?
