### ISSUE TITLE
Implement v4 equivalent of v3's limitToGraph functionality

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#396]
AmCharts v3 provided a `limitToGraph` property that enabled limiting the chart cursor line to a specific graph like in [this v3 demo](https://www.amcharts.com/demos/date-based-data/). There doesn't appear to be a way to set a limitToGraph-like setting in v4's Cursor classes or anywhere else.

**Comment by zeroin** [comment]
4.0.9:  `snapToSeries` added to `XYCursor`. Allows setting series to which cursor lines should be snapped. Works if one of the axis of the series is `DateAxis` or `CategoryAxis`. Won't work if both axes are `ValueAxis`.
