### ISSUE TITLE
AmCharts: The charts become unresponsive after 320 px.

### ISSUE THREAD

**Issue by abhiseksubham** [amcharts/amcharts4#3960]
[](https://codepen.io/dsteakleyfreeman/pen/OddjPW)
![Screenshot 2022-01-17 at 3 08 33 PM](https://user-images.githubusercontent.com/2356647/149750050-1dfa6377-8151-45da-bc6d-07b3ed76e9dd.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
