### ISSUE TITLE
Hiding a node's tooltip when its icon is being hovered over?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts4#3961]
Hi again!

I was wondering, is there any way to turn off a node's tooltip when hovering over its icon?
The icon also has a tooltip, describing what it means.

![image](https://user-images.githubusercontent.com/29444592/150007575-e22d697b-a6f5-4555-9072-f1ac961c204b.png)
 
 Below is a sample of the code, minus any styling concerns.
 
``` ts
const series: ForceDirectedSeries = getTemplate(); // nodes returned from this series have tooltips
const icon = series.nodes.template.createChild(Sprite);
...
icon.events.on("over", (e) => {
  const targetNode = e?.target?.dataItem
    ?.dataContext;
  // disable and hide tooltip somehow
});
icon.events.on("out", (e) => {
  const targetNode = e?.target?.dataItem
    ?.dataContext;
  // enable but not necessarily show tooltip somehow
});
...
icon.propertyFields.tooltipText = "iconTooltipText";
icon.tooltip = new Tooltip();
```

I've tried experimenting with things like `targetNode.hideTooltip()` etc but didn't have any luck.

Thanks!
-Jon

**Comment by martynasma** [comment]
Why not just reset `tooltipText` for the node?

```JavaScript
series.nodes.template.tooltipText = "";
```

**Comment by jonofoz** [comment]
Thanks for the response! My team is currently looking to move over to v5 at this time, so I will have to try this again as the need arises. I now need to attempt this for v5: I will close this one and raise a question in that repository if I can't quite get it.

Thanks again!
