### ISSUE TITLE
( Sankey Diagram chart ) Set SankeyLink min-height for low value nodes

### ISSUE THREAD

**Issue by michaelscraft** [amcharts/amcharts4#3962]
**Question**
Is there a way I can make `Link` from D node to A node to have a min-height of the node D?

JSFiddle: 
https://jsfiddle.net/michaelscraft/4kn1qwse/

- amCharts version  - 4.10.22
- Browser and its version -  Version 97.0.4692.71 (Official Build) (arm64)
- Related frameworks and their versions - Vue 3 v3.2.20

**Comment by martynasma** [comment]
Please refer to this workaround: https://github.com/amcharts/amcharts4/issues/3491#issuecomment-828466763
