### ISSUE TITLE
Store Data placeholder value in a variable

### ISSUE THREAD

**Issue by Lupici** [amcharts/amcharts4#3963]
Hi all, I have a tooltip text in which I use the data placeholder {name}, {date} and so on.
I need to use the variable date (the date actually pointed when I hover on a line) to make searches in other line series and grab data

To explain: I have a graph with many line series. If I hover on a line a tooltip appear and I can see the data  related to that particular date/time

`	
		  
                      series.adapter.add("tooltipText", function(ev) {
			    var text = "[bold]{date.formatDate('yy-MM-dd')}[/]\n"
		            text += "{name}: {value.formatNumber('#.#')}%\n";

			    return text;
			  });
`

I need to get also the other values (for that particular date/time) also from the other line series.... So I need, basically, to know the date/time in order to search the other serie...

If I can store and use in a variable the value of date, I can make something like this:

`	
		  
                      series.adapter.add("tooltipText", function(ev) {

			    var text = "[bold]{date.formatDate('yy-MM-dd')}[/]\n"
		            text += "{name}: {value.formatNumber('#.#')}%\n";

                        var realDate={date} //date in the point the cursor is.....obviously in this way it doesn't work

			    self.chart.series.each(function(item) {

                                   //search in the series for the value associated with realDate.....			        

			    });

			    return text;
			  });`

Is it possible? and How??? My need is to show, when pointing cursor on a series, to show the data of all series in the graph....

Thanks to all

L.

**Comment by martynasma** [comment]
If you need to access data context you can use `series.tooltipDataItem.dataContext`:

```JavaScript
series.adapter.add("tooltipText", function(text, target) {
  console.log(target.tooltipDataItem.dataContext);
  return text;
});
```

**Comment by Lupici** [comment]
Thanks a lot martynasma!!!! Works Well!!!!

L.
