### ISSUE TITLE
Brushable Parallel Coordinates charts

### ISSUE THREAD

**Issue by Tamas-Fuci** [amcharts/amcharts4#3964]
**Question**
Hello!

We've been using amcharts pretty much exclusively in our project, but our most recent requirements are parallel coordinates charts like these:
https://observablehq.com/@d3/brushable-parallel-coordinates
https://parasoljs.github.io/demo/tutorial-3_completed.html

Could something like those be made without a large amount of effort using amcharts? If possible we'd like to keep the library consistent throughout the application. Apart from the parallel, movable coordinate axes, we mainly need the brushable selection, as well as selection of lines by clicking which the above don't seem to support out of the box.

I think the closest starting point would be something like the vertical line charts, and then adding all the functionality with adapters:
https://www.amcharts.com/demos/vertical-line-chart/

Is there a better way to go about it? Any input is appreciated.

Thanks in advance!

**Environment (if applicable)**

amcharts 4.10.20 (could upgrade to 5)
react 16.13

**Comment by martynasma** [comment]
No, I'm afraid there's no way to implement a chart like that in amCharts :(
