### ISSUE TITLE
I set the pie ticks' element,but I cannot find something set on the page.

### ISSUE THREAD

**Issue by leo95123** [amcharts/amcharts4#3966]
**Question**
[code](https://codepen.io/leo95123/pen/JjrQJPq)

result: 
![image](https://user-images.githubusercontent.com/28439527/150452505-94033b93-9625-4f3f-8477-4506d2c2263d.png)

![image](https://user-images.githubusercontent.com/28439527/150452674-088d0c23-0fee-4b73-880d-c7cdf793b725.png)

It can be printed in the console, but can't find on the page.

So, how to use element of PieTick' s properties?

**Comment by martynasma** [comment]
You can configure ticks using their series template, e.g.:

```
pieSeries.ticks.template.stroke = am4core.color("#ff0000");
```

**Comment by leo95123** [comment]
> You can configure ticks using their series template, e.g.:
> 
> ```
> pieSeries.ticks.template.stroke = am4core.color("#ff0000");
> ```

I know what u say. But I wanna  make  custom ticks, just Iike this: 
![image](https://user-images.githubusercontent.com/28439527/150486612-f574d788-95c0-44f8-913c-d8ed307d5aad.png)

The stroke properties can't satisfy my demand.

**Comment by martynasma** [comment]
I'm afraid that's not possible.

**Comment by leo95123** [comment]
> martynasma

OK, thx a lot.
