### ISSUE TITLE
US Heat Map - How to draw US Region and Sub-div heat maps?

### ISSUE THREAD

**Issue by nithincs20** [amcharts/amcharts4#3968]
**Question**

Hello there,
I'm looking into US Heat map integration, I was able to draw the US state maps.
But I wanted to draw the **US region** and **sub-div maps**. How to draw those maps? Is there any tutorials or reference available can you please share? If this can be achieved by the `geodata` can you please provide the data format?

**Environment (if applicable)**

- amCharts version - 4.10.20, amcharts4-geodata - 4.1.22
- Browser and its version - Google chrome, 97.0.4692.71
- Related frameworks and their versions - ReactJS, 17.0.2

**Additional context**

Attaching Region and Sub-div maps here for reference.
**Region** - 
<img width="636" alt="region" src="https://user-images.githubusercontent.com/59362183/150742080-6e5632c4-628e-47ee-9eb1-a1aca6c75799.png">

**Sub-div**
<img width="520" alt="subdiv" src="https://user-images.githubusercontent.com/59362183/150742125-ef53643f-dc4b-4a93-a46e-5c37668f981e.png">

**Comment by martynasma** [comment]
Region or sub-region maps bundled with amCharts.

You can create ones if you have source data.

Refer to this article:
https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/

**Comment by nithincs20** [comment]
Thank you!
