### ISSUE TITLE
Change colour of the legend labels on hover events

### ISSUE THREAD

**Issue by abhaypatil87** [amcharts/amcharts4#3969]
**Question**
I searched through previous issues/examples and found out that on a hover event, you could change the _background_ colour of a legend label. Is it possible to change the label colour itself, when hovering over?

The sample code for the background colour change I found was as below:

```
this.chart.legend.labels.template.events.on('over', function (ev) {
            console.log('clicked label', ev.target);
            ev.target.background.fill = (am4core.color('red'));
});
```

But I couldn't find anywhere how to change the colour of the legend label in particular that's being highlighted.

I appreciate any help or pointers!

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Setting `ev.target.fill` should change the color of the label itself.

**Comment by abhaypatil87** [comment]
I don't think that works. I tried exactly like below, but the label colour doesn't change on hover:

```
        this.chart.legend.labels.template.interactionsEnabled = true;

        this.chart.legend.labels.template.events.on('over', function (ev) {
            console.log(ev.target);
            ev.target.fill = am4core.color('#FF69B4');
        });
```

Could you please provide me with a working example?
Really appreciate your help on this.

**Comment by martynasma** [comment]
There you go:
https://codepen.io/team/amcharts/pen/4d71b151c8260054fb487939a35e4367?editors=0010

**Comment by abhaypatil87** [comment]
Thanks for this! It does work, however, I realised that I have to have another even handler on the itemContainer itself. One is a parent, and the other is a child (the legend label) within that parent (the itemContainer)

While I got something like below to work, it still isn't full-proof, because the fill property still doesn't work. Only stroke and strokeOpacity works.

```
        /* enable interactions */
 this.chart.legend.markers.template.interactionsEnabled = true;
 this.chart.legend.labels.template.interactionsEnabled = true;
this.chart.legend.labels.template.applyOnClones = true;

 this.chart.legend.itemContainers.template.events.on('over', this.onLegendOver.bind(this));

onLegendOver(event): void {
        const itemContainer = event.target;
        const currentSeries = itemContainer.dataItem.dataContext;
        this.chart.series.each(function (chartSeries) {
            if (chartSeries !== currentSeries) {
                chartSeries.strokeOpacity = 0.3;
            }
        });

        /* Highlight the legend label */
        console.log(itemContainer.children.values[1]); // values[1] is the legend label
        // itemContainer.children.values[1].stroke = 'red'; // here, fill doesn't work :(
        itemContainer.children.values[1].strokeWidth = 0.25;
    }

```

I tried almost everything, but nothing seems to be working so far.
Again, thank you for helping me tackle this.

**Comment by martynasma** [comment]
If you need to change color of a legend label on hover, there are better ways to do that, like creating custom states.

Let me know if that's what you are trying to achieve.

**Comment by abhaypatil87** [comment]
Yes, I am trying to change the label colour on hover. How do recommend I do that.

**Comment by abhaypatil87** [comment]
On its own, this above example works, but when you add events like over and out on the labels to add other effects on the chart series', the behaviour doesn't work. Here's a codepen:

https://codepen.io/abhaypatil87/pen/eYeNzrW

Basically, when hovered over a particular legend label, I want to:
1. Change the highlighted legend label colour, _and_
2. Dim the rest of the chart series

and, when the mouse hover is gone, change the legend label color back to default, and reset all the chart series' stroke opacity back to 1.

Can this actually be achieved?

**Comment by martynasma** [comment]
Gotcha. Changing series state, applies settings to its legend item thus knocking off applied state.

Workaround would be to re-apply the state to the label on hover:

```JavaScript
chart.legend.labels.template.events.on("over", function (event) {
  const itemContainer = event.target.parent;
  const currentSeries = itemContainer.dataItem.dataContext;
  chart.series.each(function (chartSeries) {
    if (chartSeries !== currentSeries) {
      chartSeries.strokeOpacity = 0.3;
      setTimeout(function() {
        event.target.setState("hover")
      }, 100)
    }
  });
});
```
