### ISSUE TITLE
Radar chart categories problem

### ISSUE THREAD

**Issue by rferreira98** [amcharts/amcharts4#3971]
i'm trying to render a Radar chart with categories on xAxis with a xAxis range.
The problem is that I'm trying to join data like:

Category X:
 Sub-category X1, value 20
 Sub-category X2, value 30
 Sub-category X3, value 15
 Sub-category X4, value 40
Category Y
 Sub-category Y1, value 50
Category Z
 Sub-category Z1, value 50

With this data, I can't use Series because it implies that X1 is present in every category, X2 as well, and so on...
I end up getting a chart with Category X, Y and Z where Y and Z have wrong values of X1, X2, X3 and X4.

AmChart V5
React framework
Codepen: https://codepen.io/r_ferreira/pen/MWOYwdy

**Comment by rferreira98** [comment]
Result expected:
![Screen Shot 2022-01-26 at 14 39 03](https://user-images.githubusercontent.com/24259712/151183571-7c70d441-ddd2-4e39-a0d4-3e0fbcc2f4eb.png)

**Comment by martynasma** [comment]
If this is question about amCharts 5, please use appropriate repo: https://github.com/amcharts/amcharts5/
