### ISSUE TITLE
speeding up the animation triggered by the click on the legend

### ISSUE THREAD

**Issue by lucasp-cit** [amcharts/amcharts4#3972]
In a chart like this one:

https://codepen.io/team/amcharts/pen/ROXRKW

when clicking in the legend of each individual line an animation occurs.

would be possible to make this hide/show animation faster?

**Comment by martynasma** [comment]
Yes:

```JavaScript
series.defaultState.transitionDuration = 100;
series.hiddenState.transitionDuration = 100;
```

https://codepen.io/team/amcharts/pen/83fb64ce0e881248183835c8a4c07c03

**Comment by lucasp-cit** [comment]
great! Thanks a lot for your help @martynasma!
