### ISSUE TITLE
Map Heat : custom start/end label values for legend in an external container

### ISSUE THREAD

**Issue by nithincs20** [amcharts/amcharts4#3973]
**Question**

Hey,

I wanted to create Heat Map with heat legend with custom label values, and legend positioned at bottom. I tried this example - Chart Legend in an External Container (https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/) created legend in a separate container, and placed at the bottom as needed. It looks fine.

Now, to create the custom label values, I was referring this - Map heat legend with real start/end value labels
(https://www.amcharts.com/docs/v4/tutorials/map-heat-legend-with-real-start-end-value-labels/) [here legend is with its own chart container I guess - couldn't find any other references].
So when I try to integrate with my chart, the following code throwing error.

```
polygonSeries.events.on("datavalidated", function(ev) {
  let heatLegend = ev.target.map.getKey("heatLegend");
  let min = heatLegend.series.dataItem.values.value.low;
  let minRange = heatLegend.valueAxis.axisRanges.getIndex(0);
  minRange.value = min;
  minRange.label.text = "" + heatLegend.numberFormatter.format(min);

  let max = heatLegend.series.dataItem.values.value.high;
  let maxRange = heatLegend.valueAxis.axisRanges.getIndex(1);
  maxRange.value = max;
  maxRange.label.text = "" + heatLegend.numberFormatter.format(max);
});
```
here `ev.target.map.getKey('heatLegend')` is giving undefined and not actually having the reference to heatlegend. So not able to create the legend.

How do I create custom label with legend in external container? If you have any references or other workarounds please share. 

**Environment (if applicable)**

- amCharts version - 4.10.20, amcharts4-geodata - 4.1.22
- Browser and its version - Google chrome, 97.0.4692.71
- Related frameworks and their versions - ReactJS, 17.0.2

**Additional context**

This is what I'm trying to achieve

<img width="728" alt="up" src="https://user-images.githubusercontent.com/59362183/151323999-6f627235-e9f1-48ac-97e5-56d6ea851c69.png">

**Comment by nithincs20** [comment]
Thank you for the quick response. I was able to access the global heatLegend properties for my need.

I have couple of questions too. It would be great if you could answer those as well

- If you look at the legend label text(above image), those are at the left and right side of legend, is this achievable? I was able to place it at the bottom of end/start of the legend, but need to position it as in the above image
- Is there a way to reduce the size(thickness) of the legend?

**Comment by martynasma** [comment]
> If you look at the legend label text(above image), those are positioned at the left and right side of legend, is this achievable? I was able to place it at the bottom of start/end of the legend, but I need to position it as in the above image

Maybe you can just create a separate `Container` with `layout: horizontal` then push two labels and `HeatLegend` objects into it.

I'm afraid I don't have a demo for that.

> Is there a way to reduce the size(thickness) of the legend that amcharts give us?

https://www.amcharts.com/docs/v4/concepts/legend/heat-legend/#Changing_height_or_width

**Comment by nithincs20** [comment]
> https://www.amcharts.com/docs/v4/concepts/legend/heat-legend/#Changing_height_or_width

Okay, I have tried above method, but the height(thickness) of legend is not changing as expected.

This is the sample codepen - https://codepen.io/nithin_cs/pen/vYWLpQw. Would you able to take a look at this and please advice?



> Maybe you can just create a separate Container with layout: horizontal then push two labels and HeatLegend objects into it.

I have created a separate legend container as mentioned if you look at the above codepen sample, my doubt is how do I achieve the label positioning here.

**Comment by martynasma** [comment]
```JavaScript
polygonSeries.events.on("datavalidated", function(ev) {
  var min = polygonSeries.dataItem.values.value.low;
  var max = polygonSeries.dataItem.values.value.high;
  
  var legendContainer = chart.createChild(am4core.Container);
  legendContainer.layout = "horizontal";
  legendContainer.align = "center";
  legendContainer.valign = "bottom";
  
  var minLabel = legendContainer.createChild(am4core.Label);
  minLabel.text = min + "";

  var heatLegend = legendContainer.createChild(am4maps.HeatLegend)
  heatLegend.series = polygonSeries;
  heatLegend.width = 400
  heatLegend.marginLeft = 15;
  heatLegend.marginRight = 15;
  heatLegend.markerContainer.height = 15
  heatLegend.markerContainer.minHeight = 15;
  heatLegend.markerContainer.layout = 'horizontal'
  
  heatLegend.valueAxis.renderer.labels.template.adapter.add("text", function(labelText) {
    return "";
  });
  
  var maxLabel = legendContainer.createChild(am4core.Label);
  maxLabel.text = max + "";
});
```

**Comment by nithincs20** [comment]
Thank you for the code snippet!

**Comment by nithincs20** [comment]
As a newbie to the amCharts4 maps, I wanted to give my few feedbacks on this.


Going through the amCharts4 maps docs I found many good demos and tutorials. But according to my requirements I 
needed some customisation on the default behaviour.

For me I felt challenging in understanding the map APIs (polygonSeries, legend container), its usages and taking advantage of it for my requirements.

So I would love to see more detailed docs on each topics and more examples with references.
Thanks again for all the good works
