### ISSUE TITLE
making initial fade in animation faster

### ISSUE THREAD

**Issue by lucasp-cit** [amcharts/amcharts4#3974]
Hey Guys,

I am having a hard time trying to find out where exactly to make the onload fade in animation faster

https://codepen.io/lucasp-cit/pen/QWObbaz

could you, please, help me find where I should change?

Thanks in advance!

**Comment by martynasma** [comment]
Try this:

```JavaScript
chart.defaultState.transitionDuration = 200;
```

**Comment by lucasp-cit** [comment]
it works perfectly... thanks a lot!
