### ISSUE TITLE
Replay initial animation on data substitution

### ISSUE THREAD

**Issue by Ices-Eyes** [amcharts/amcharts4#3976]
Hi all,
I have a graph (xy bar chart) on a page that is created just the first time. Then the user can choose some parameters then by pressing a buton parameters are sent to the backend that reply with new data, and once received the substitute actual graph data via `chart.data=newdata;`. But when this happen, hraph just present new data. Is there a way to make it replay initial animation of the bar?

Thanks! :)

**Comment by martynasma** [comment]
Check this out:
https://www.amcharts.com/docs/v4/tutorials/trigger-a-replay-of-the-chart-initial-animations/

**Comment by Ices-Eyes** [comment]
Thinks for the reply! Already seen that but it does not seems to work as expected... I've made a little change to the pen
https://codepen.io/Ices_Eyes/pen/gOXPPRV
My case would be something like the second or third test button on there (actually test 3), The animation is not played either in test 2... I think I need to reset something before data change, but not sure on what!

**Comment by martynasma** [comment]
Something like this should do the trick:

```JavaScript
function test3() {
  var newdata=[];
  for(i=1; i < data.length; i++) {
    newdata.push({"date": data[i].date, "value": data[i].value3});
  }
  chart.data=data;
  chart.events.once("datavalidated", function() {
    chart.series.each(function(series) {
      series.appear();
    });
  })
}
```

**Comment by Ices-Eyes** [comment]
Yeah! That works perfectly! Thank you very much! 😃
