### ISSUE TITLE
Incorrect date format for the 1st day of every month

### ISSUE THREAD

**Issue by DineshIntervent** [amcharts/amcharts4#3977]
**Question**
I am using XY charts to show weekly data with dateAxis as X-Axis.
I am formatting the date to be like "**dateAxis.dateFormats.setKey("day", "dd\nMMM");**" and this works fine for every day except for the 1 day of month (please refer the attached screenshot)
Same issue with **dt\nMMM**

![image](https://user-images.githubusercontent.com/86301809/151792078-13cf2a77-01a2-41e3-9c09-4cef001a1007.png)

I tried to use same format by editing few of the examples on the official website and still getting same issue.

**Environment**
 - amCharts version 4

**Additional context**
The issue is happening only with the 1st day on month irrespective of which day of week it comes on eg- Mon, Tues, Wed etc.

Please help on how can I fix this.

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Period_change_format

**Comment by DineshIntervent** [comment]
Thank you this fixed the problem I was facing.
