### ISSUE TITLE
Question: Tootip Triangular Part Configuration

### ISSUE THREAD

**Issue by sauravgaursmith** [amcharts/amcharts4#3978]
Hi Guys, 

I just have question if you can answer. Please see the attached image.I want configure triangular part (Tooltip Pointer) of Amchart Tooltip as shown in image. have walk-through the documentation but no luck. 

![image](https://user-images.githubusercontent.com/25001992/151803355-4b29101d-4a24-4a7e-a9bf-60a30bd82be5.png)

Thank you.

**Comment by martynasma** [comment]
`Tooltip`'s background is an element of type `PointerRectangle`. There are two settings you can use to configure the actual pointer:

https://www.amcharts.com/docs/v4/reference/pointedrectangle/#pointerBaseWidth_property
https://www.amcharts.com/docs/v4/reference/pointedrectangle/#pointerLength_property

E.g.:

```JavaScript
series.tooltip.background.pointerBaseWidth = 20;
series.tooltip.background.pointerLength = 10;
```
