### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by matt-senseye** [amcharts/amcharts4#3979]
We've identified a number of issues relating to timezones in amCharts 4. I'm not sure if this is a single bug, multiple bugs or if I'm just doing something wrong but since it all seems related I have listed them as 4 issues below and can all be demonstrated using the linked CodePen reproduction.

## Reproduction Codepen

https://codepen.io/mattwilson1024/pen/yLPezrG

The example has 4 data points in `Oct, Nov, Dec and Jan`.

In our app we need the user to be able to select a timezone and would like all charts to obey that timezone (regardless of how their system is configured). To demonstrate this, note line 38, which explicitly sets the timezone of the am-chart to `EST`:

```
chart.dateFormatter.timezone = "EST";
```

However, please note that the system timezone also comes into play here - to see the issues that I'm describing manifest themselves, you also need to set the system/OS timezone, for my examples I've used `EST`, like so:

<img width="780" alt="CleanShot 2022-01-31 at 11 46 13@2x" src="https://user-images.githubusercontent.com/26366219/151836063-caa1378d-495b-4d9d-9c0d-f9ffdfa15a9b.png">

## Issue 1: First two months shown on the date axis are wrong

The first two month labels on the x-axis are incorrect and don't match the data. Given the sample data, I would expect `Oct, Nov, Dec, Jan` but instead, it shows `Sep, Oct, Dec, Jan`. This was noticed because November is missing, but on further inspection it comes down to the first two months being mislabelled.

![CleanShot 2022-01-31 at 12 01 08](https://user-images.githubusercontent.com/26366219/151838722-9ce56698-225d-42da-ac82-867bd0c7f6b6.png)

## Issue 2: Chart is not starting at the time I requested

The date axis has `strictMinMax` enabled and lines 41-47 should be setting the displayed range to a specific start & end. 

However if you use the scrollbar to zoom right in on the start of the chart, you can see that the axis is starting at the wrong time. The requested start time was `7pm on 2nd Oct (EST)`, but it seems to begin one day too early (`7pm on 1st Oct`)

![CleanShot 2022-01-31 at 12 02 18](https://user-images.githubusercontent.com/26366219/151838927-fb4439f7-d2e4-445f-8737-5b10ab54145d.png)

## Issue 3: Scrollbar doesn't match main date axis

When adding an `XYChartScrollbar`, the sub-chart embedded in the scrollbar does not adhere to the timezone set on the chart itself.

Not that in the CodePen, the main date axis has `Sep, Oct, Dec, Jan` but the scrollbar has `Oct, Nov, Dec, Jan`. Given that the chart is fully zoomed out, I would expect the scrollbar and the main axis to match.

![CleanShot 2022-01-31 at 12 10 00](https://user-images.githubusercontent.com/26366219/151840155-b898a801-22db-42e2-bce4-cb8c2ee291c5.png)

Explicitly setting a timezone on the scrollbar chart in addition to the main chart makes the two consistent (can be demonstrated by uncommenting line 39 in the CodePen), but I'm not sure if it's correct that I should have to set it twice. My expectation would have been that the scrollbar would "inherit" the same timezone as the parent chart, because the sub-chart gets created automatically by am-charts.

```
scrollbar.scrollbarChart.dateFormatter.timezone = "EST";
```

![CleanShot 2022-01-31 at 12 10 56](https://user-images.githubusercontent.com/26366219/151840215-4f6cbbf1-0d28-49b3-8418-8ae7b4d8c9fd.png)

## Issue 4: System timezone has an effect

The problems described above present themselves in different ways depending on the combination of `system / OS` timezone setting and `chart.dateFormatter.timezone` setting.

Ideally, explicitly passing a timezone to `chart.dateFormatter.timezone` seems like it should "win" over the environment (browser or OS) setting. If I'm setting the timezone on the library explicitly, I want that to be obeyed regardless of the user's system settings.

With the example CodePen,
- System: `EST`, am-charts dateFormatter: `EST` --> shows months `Sep, Oct, Dec, Jan`
- System: `GMT`, am-charts dateFormatter: `EST` --> shows months `Sep, Oct, Nov, Dec`

*Note*: Both cases are actually incorrect, for the data that is passed in, we would expect `Oct, Nov, Dec, Jan` in either case.

![CleanShot 2022-01-31 at 12 19 15](https://user-images.githubusercontent.com/26366219/151841656-95980eea-382e-447f-89d4-6b12ec5299ed.png)

![CleanShot 2022-01-31 at 17 20 05](https://user-images.githubusercontent.com/26366219/151841719-2481505a-ad07-4897-97ed-e9582cbb169d.png)

**Environment (if applicable)**

amCharts version: 4.10.23
Browser: Tested with Chrome 97 on Mac
Related frameworks and their versions: N/A

**Comment by martynasma** [comment]
I'm afraid at this time we do not plan on implementing any changes to how timezones work in amCharts 4. The implementation is somehow many-sided, with a lot of overlapping settings, which makes it hard to cover all possible scenarios.

I strongly suggest taking a look at amCharts 5, which has better [timezone support](https://www.amcharts.com/docs/v5/getting-started/root-element/#time-zone).
