### ISSUE TITLE
addData doesn't remove element from data array

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#398]
i have created an amchart with some data on it via
    this.amChart.addData(blalblabla);
now, the data get updated via MQTT, and i want to keep the number low, due to insane lag on update.

i try to do

        this.amChart.addData(arr, arr.length);

and, standing to docs it should remove element from the begin of dataset.
from console, printing this.amChart.data.length

before i have  248
after  250

so, the 2 elem of array get added, but the first 2 aren't removed.
chart display that behaviour as well, new data are in, the chart refresh, but the old one aren't disposed

**Comment by martynasma** [comment]
I can't seem to reproduce this. Here's my test case:
https://codepen.io/team/amcharts/pen/8e35f25d6a86afc5f75c3d5c3b7826d4?editors=0010

Can you share your chart code and data so that we can test yours?

**Comment by ramarro123** [comment]
installed beta55 and now it work, closed
