### ISSUE TITLE
Pin bullet cannot display label

### ISSUE THREAD

**Issue by kavi87** [amcharts/amcharts4#3981]
Version: Amchart 4.9.9

I'm using JSON config.

```
series: [{
                type: "CurveColumnSeries",

...
 bullets: [{
                  
                    type: "PinBullet",
                    label: {
                        text: "bla bla"
                    },
```
This ends as "source.label.clone is not a function".

It works perfectly using the JS config. Ideally i would prefer the JSON one which is by far much cleaner and readable.

**Comment by martynasma** [comment]
Have you tried with current version (4.10.23)?

If it's still not working, can you post your chart as a CodePen or jsFiddle so that we can take a look?
