### ISSUE TITLE
Series' name with spaces

### ISSUE THREAD

**Issue by DavidAuger** [amcharts/amcharts4#3982]
Hello @martynasma , Hello all,

We observed a strange behaviour on XYChart on some specific series.
We used to create series' name on this format ```<metric>:<device>:<organ>```. And it may happened that <device>'s name have some spaces some times (mainly due that it is name of places in France).

We observed that:

- **browser (Chrome, Firefox, ...) is extremly impacted and its performance downgrade** (main problem form our side)
- chart is loading during a long time (longer than usual)
- chart is displayed without series (but tooltip seems to follow its placement any way)
- legend display automatically name with underscores

Find bellow an example of observed behaviour:
![image](https://user-images.githubusercontent.com/48203813/152134709-dc296e45-804a-456c-9e67-49f86707fd35.png)

And here is an exemple of data:
`[
    {
        Imoy_Irms:Combs La Ville:GT1_ph1-2: 1
        Umoy_Urms:Combs La Ville:GT1_ph1-2: 20748
        date: 1643756415000
        sentinelpathname: "Combs La Ville:GT1_ph1-2"
    },
    ...
]`

We did found a satisfying workaround, by replacing every spaces by underscores - which is technically logical.

My point is

- I dont find any mention of this limitation in documentation, maybe it could help to be written down
- Is it a behaviour by design or is it a bug ?

Best regards,
David

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
