### ISSUE TITLE
Negative values in legends and tooltips near hebrew and arabic letters

### ISSUE THREAD

**Issue by UMSF-K13-3-Sahan** [amcharts/amcharts4#3983]
In tooltips (demo [here](https://jsfiddle.net/Nikitumba/0av3c2e7/)) i have minus sign in wrong place when name of smth presents in hebrew or arabic. It must be on the left side of number.

And in legends minus always in a wrong place

![image](https://user-images.githubusercontent.com/19708817/152194019-e8e8a609-7b36-42f2-a2a1-4bbb63a1d894.png)
![image](https://user-images.githubusercontent.com/19708817/152194092-c42a0e5f-618f-459d-ba67-c431daedf611.png)

![image](https://user-images.githubusercontent.com/19708817/152194511-dc6dc131-b00d-4653-9154-215aee028269.png)

**Comment by martynasma** [comment]
I'm not entirely sure how to go about it. That's how SVG renderer renders text with RTL characters in it.

Legend seems to be fixed by removing `chart.rtl = true`, though. It is because value label is a different DOM element.
