### ISSUE TITLE
pointerOrientation is ignored on axis title tooltip

### ISSUE THREAD

**Issue by keegandonley** [amcharts/amcharts4#3984]
**Bug description**

I'm trying to add a tooltip to a `ValueAxis` title, but the pointerOrientation is ignored so it cannot be rendered properly. 

```javascript
const chart = am4core.create(element, XYChart);

{...}

const axis = chart.yAxes.push(new ValueAxis());
axis.title.text = shortLabel;
axis.title.tooltipText = label;
axis.title.tooltip.pointerOrientation = 'left';

```

**Environment**
Amcharts `4.9.30` (also confirmed this is not working at `4.10.23`)

**Additional context**

Result:
![Screen Shot 2022-02-04 at 10 21 57 AM](https://user-images.githubusercontent.com/12700819/152564760-bcb92e3e-5f0a-4cf3-bda4-e0079c7378cd.png)

**Comment by martynasma** [comment]
It's happening because axis elements (title) uses axis' `Tooltip` instance which has certain settings applied to it by default.

Workaround is to create own tooltip for just the title:

```JavaScript
axis.title.tooltip = new am4core.Tooltip();
```
