### ISSUE TITLE
Pre-zooming an axis boundaries are incorrect

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#3985]
**Bug description**

I wanted to pre-zoom the chart on the X-Axis when the "ready" event triggers
I followed this documentation of amCharts
https://www.amcharts.com/docs/v4/tutorials/pre-zooming-an-axis/

My usecase exactly matched the one given in the codepen of the following section
https://www.amcharts.com/docs/v4/tutorials/pre-zooming-an-axis/#Setting_up_pre_zoom

Here, the zoomRegion is between the start and end of the dataset
This worked really well

But, if you provide the end of the zooming region as the last member of the dataset, the zooming doesn't work as expected
We can still drag the RHS slider to the right, and there will be one item still visible, which shouldn't be the case

What I expect is, when we give the last date of the dataset as the end of the zooming region, the slider should be at the RHS end and shouldn't be further scrollable, and also there shouldn't be any graph concealed in the right section

**Environment (if applicable)**

amCharts version: 4.10.10 (doesn't matter, since, I am able to reproduce from the official code pen demo stated above)
Browser: Chrome 98.0.4758.80

**Additional context**
CodePen: https://codepen.io/team/amcharts/pen/BPaRLG
Please make the following change in the "ready" event handler
```js
chart.events.on("ready", function () {
  dateAxis.zoomToDates(
    new Date(2018, 3, 23),
    new Date(2018, 3, 28) // this is the last date in the dataset
  );
});
```

Please help me on whether there some other workarounds for getting this issue fixed ?
Usecase: I need the end item in the dataset also come in the zoomed region .. :-)

Thank you very much in advance

**Comment by xorspark** [comment]
The axis grids represent a full baseInterval period; in this chart's case, the grids are full days, hours and all. Since the labels are shifted over (`location = .5`), you have to zoom to the middle of the day:

```
chart.events.on("ready", function () {
  dateAxis.zoomToDates(
    new Date(2018, 3, 23),
    new Date(2018, 3, 28, 12)
  );
});
```

More information on the relationship between `location` and date axis can be found here: https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis

**Comment by azharakbar** [comment]
@xorspark 
Thank you very much ... It works now .. 

But, there is a minor issue which I have seen .. 
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/10185101/152636658-c0c3088f-3773-4857-bf68-cc4ef2a711b3.png">

The last label is cut by a very little portion .. 

Is there some configuration to fix this ?

**Comment by xorspark** [comment]
You can increase the paddingRight on the chart.

```
chart.paddingRight = 45;
```

**Comment by azharakbar** [comment]
Ok, Thanks @xorspark
