### ISSUE TITLE
Changing the color of Axis Labels in CategoryAxis and DateAxis

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#3986]
**Question**
Hi, how can I change the color of labels on Axes ? (CategoryAxis, DateAxis) 
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/10185101/152697981-678535cc-6f89-4c97-9b75-c549215c068b.png">

I wanted to change the font-color of the labels in the red-boxes of the above image

**Environment (if applicable)**
amCharts version: `4.10`
Framework: ReactJS
Browser: Chrome 90

**Comment by azharakbar** [comment]
Hi @xorspark,
Can you please help me with this?

**Comment by martynasma** [comment]
Pleas refer to this tutorial:
https://www.amcharts.com/docs/v4/concepts/axes/#Labels

**Comment by azharakbar** [comment]
Got it
```js
categoryAxis.renderer.labels.template.fill = am4core.color("red");
```

**Comment by azharakbar** [comment]
@martynasma Also, one more doubt
<img width="507" alt="image" src="https://user-images.githubusercontent.com/10185101/152753291-50fcf01b-f772-4349-a646-c1d3f53e0659.png">

What is the way to decrease the gap between two series ?

**Comment by azharakbar** [comment]
I mean, the gap between CBRE series and Insource series  /OR/ the gap between Insource series and City FM Series .. 
Thanks in advance

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
