### ISSUE TITLE
Decrease/Increase the gap between columnSeries

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#3987]
**Question**
<img width="507" alt="image" src="https://user-images.githubusercontent.com/10185101/152753291-50fcf01b-f772-4349-a646-c1d3f53e0659.png">

What is the way to decrease the gap between two series ?

**Environment (if applicable)**
amCharts version: 4.10
Framework: ReactJS
Browser: Chrome 90

**Comment by martynasma** [comment]
You can increase gap between columns within same category, by reducing their `width` setting:

https://www.amcharts.com/docs/v5/charts/xy-chart/series/column-series/#Column_width

**Comment by azharakbar** [comment]
Thanks @martynasma

**Comment by azharakbar** [comment]
Sorry, but is this applicable in amcharts4 ?
As you have mentioned the link of v5 ...

**Comment by azharakbar** [comment]
Can you please clarify on this ?
Thanks

**Comment by azharakbar** [comment]
Is this the one ?
https://www.amcharts.com/docs/v4/tutorials/managing-width-and-spacing-of-column-series/#Setting_column_width

**Comment by martynasma** [comment]
Yup, sorry for the wrong link. But you found the correct equivalent for amCharts 4.

**Comment by azharakbar** [comment]
Thank you very much @martynasma
