### ISSUE TITLE
legends behaviour in AmCharts4

### ISSUE THREAD

**Issue by snasir3** [amcharts/amcharts4#3988]
Hi @amcharts  @zeroin ,
I am working towards achieving the same goal as described here (https://github.com/amcharts/amcharts4/issues/2131) except the 'All' option. My task is to implement the following:

when you first click on the legend it only shows data for that legnd and hide other legends
clicking the same legend reset everything
I have come up with the below but it has some issues. For instance, when one legend is clicked and you click legend 2 this leaves the previously selected legend in grey and activates all the other legends and when you click again on legend 2 it shows previously selected legend as well as legend 2.

chart.legend.itemContainers.template.togglable = false
chart.legend.itemContainers.template.events.on('hit', (event) => {
const { target } = event
chart.legend.itemContainers.each((item) => {
const state = item
// if (state !== target) {
// state.isActive = true
// state.dataItem.dataContext.hide()
// }
if (state.dataItem.dataContext.isHidden) {
state.isActive = false
state.dataItem.dataContext.show()
} else {
state.isActive = true
state.dataItem.dataContext.hide()
}
})
target.isActive = false
target.dataItem.dataContext.show()
})

Any help is much appreciated!!

**Comment by snasir3** [comment]
He @martynasma, Please inform me if there has been any progress on this task. I have a tight deadline to complete this task, thanks!

**Comment by martynasma** [comment]
Try something like this:

```JavaScript
chart.legend.itemContainers.template.togglable = false;

chart.legend.itemContainers.template.events.on("hit", function(event){
  var target = event.target;
  var switching = target.isActive;
  chart.legend.itemContainers.each(function(item) {
    var series = item.dataItem.dataContext;
    if (item.dataItem == target.dataItem || (item.isActive && !switching)) {
      item.isActive = false;
      series.show();
    }
    else {
      item.isActive = true;
      series.hide();
    }
  })
});
```

https://codepen.io/team/amcharts/pen/BamdppP?editors=0010

**Comment by snasir3** [comment]
Thanks a lot!

**Comment by snasir3** [comment]
Hi, Could this be converted in amcharts5 please. Much appreciated!
chart.legend.itemContainers.template.togglable = false;

chart.legend.itemContainers.template.events.on("hit", function(event){
  var target = event.target;
  var switching = target.isActive;
  chart.legend.itemContainers.each(function(item) {
    var series = item.dataItem.dataContext;
    if (item.dataItem == target.dataItem || (item.isActive && !switching)) {
      item.isActive = false;
      series.show();
    }
    else {
      item.isActive = true;
      series.hide();
    }
  })
});

**Comment by martynasma** [comment]
Please use appropriate repo for amCharts 5:
https://github.com/amcharts/amcharts5/issues

**Comment by snasir3** [comment]
> Hi @martynasma @amcharts , Could this be converted in amcharts5 please? Much appreciated! chart.legend.itemContainers.template.togglable = false;
> 
> chart.legend.itemContainers.template.events.on("hit", function(event){ var target = event.target; var switching = target.isActive; chart.legend.itemContainers.each(function(item) { var series = item.dataItem.dataContext; if (item.dataItem == target.dataItem || (item.isActive && !switching)) { item.isActive = false; series.show(); } else { item.isActive = true; series.hide(); } }) });

sure opened it here: https://github.com/amcharts/amcharts5/issues/288
