### ISSUE TITLE
How long this version will be maintained?

### ISSUE THREAD

**Issue by lucaspgr** [amcharts/amcharts4#3990]
**How long amcharts4 will be maintained?**  

Recently I've been using this lib and found out that you guys have another version using Canvas API.  

But I have some charts implemented and I wondered for how long will amcharts4 be maintained? And if I should go to the new version, since I'm still learning it.  

I have read this in the docs: [Should I migrate?](https://www.amcharts.com/docs/v5/migrating-from-amcharts-4/#Should_I_migrate_)

**Comment by martynasma** [comment]
amCharts 4 is in feature lock right now.

We'll still be fixing critical issues until end of 2022.

**Comment by lucaspgr** [comment]
Thank you!
