### ISSUE TITLE
Disable single legend item programmatically

### ISSUE THREAD

**Issue by shamiam1980** [amcharts/amcharts4#3991]
I just need to know how to disable a single legend item programmatically on chart reload (_**disable** means: legend is shown greyed out and its linked curve is hidden_), as I need to reload a chart with some new data using some back and forward arrows, but still need to remember the user preference or the state of  legend items (on/off)

**Comment by martynasma** [comment]
This will explain how to do it:
https://www.amcharts.com/docs/v4/concepts/series/#Pre_hiding_series

**Comment by shamiam1980** [comment]
Thanks @martynasma so much always on time.
It just happened to work with series `appeared` event, not `shown` event as in the examples, like this:

```  
    series.events.on("appeared", () => {
        myReactState ? series.show() : series.hide();
    });
