### ISSUE TITLE
Display tooltip only on the oversized labels

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts4#3992]
I am trying to display a tooltip over a label, only if the label is truncated (oversized)

The problem that when I use the `tooltip.adapter.add('disabled')` the target is type of `Tooltip`, but I need to get the reference to the `label.isOversized` (which is the parent that triggers the tooltip)

```ts
const medicationLabel = medicationSeries.bullets.push(new am4charts.LabelBullet());
medicationLabel.label.text = '{medication} ({unit})';
medicationLabel.label.tooltip = new am4core.Tooltip();
medicationLabel.label.tooltipText = '{medication} ({unit})';

medicationLabel.label.tooltip.adapter.add('disabled', (disabled: boolean, target: Am4Core.Tooltip) => {
  // The following always return false because it is the label of the tooltip, not the original label I am looking for!
  return !target.label.isOversized;
});
```

How can I only show tooltip if the label is oversized?

**Environment (if applicable)**

 - amCharts 4
 - Angular 13

**Comment by martynasma** [comment]
Have you tried checking `return !target.isOversized` then?

**Comment by MurhafSousli** [comment]
@martynasma  `target` here is a reference of the tooltip which is not truncated, I need a reference of the `medicationLabel.label. isOversized` which is the one that gets truncated

**Comment by martynasma** [comment]
Right. My bad.

In that case you might try to add an adapter for `tooltipText` on `medicationLabel.label` so that target is label itself.

If adapter would return empty string, tooltip would not appear.

**Comment by MurhafSousli** [comment]
Awesome! it worked, thanks a lot!
