### ISSUE TITLE
Spaces around pieChart

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#3993]
**Question**
Hi! I am kinda confusing dealing with spaces around my pie chart, is there any way to decrease it? 
![image](https://user-images.githubusercontent.com/18229211/153600324-893d74ea-e3fb-4346-b268-506fb8380170.png)
I've tried 

```
chart.padding(0, 0, 0, 0); 
chart.margin(0, 0, 0, 0);
chart.chartContainer.padding(0, 0, 0, 0);
chart.chartContainer.margin(0, 0, 0, 0);
```
but it didn't work out

**Comment by martynasma** [comment]
The pie itself is sized to fit within bounds of the available space, maintaining aspect ratio.

Looking at your screenshot, it seems that height is limiting its further growth.

**Comment by 12rita** [comment]
>  further growth.
But i don`t need growth. On the contrary, i need spaces to shrink, because this chart is placed nearby another one and blank spaces look quite redundant
![image](https://user-images.githubusercontent.com/18229211/153606534-4e9a93f8-f4f3-495d-836b-19f66167733b.png)

**Comment by martynasma** [comment]
Then you will need to reduce width of the chart container.

**Comment by 12rita** [comment]
I set chart.chartContainer.width = am4core.percent(70), that helped, but it looks now, that chart align isn`t central. I set chart.chartContainer.contentAlign = 'center', but it didn`t work out
![image](https://user-images.githubusercontent.com/18229211/153633813-59bdad18-2987-4a8d-ab77-c317a7603421.png)

**Comment by martynasma** [comment]
I mean you need to reduce width of the `<div>` element, so there are less white space.

**Comment by 12rita** [comment]
That worked out, thanks a lot)
