### ISSUE TITLE
Memory leak on amChart5 with map with pulsating bullets

### ISSUE THREAD

**Issue by pokix** [amcharts/amcharts4#3994]
Hello,

I'm facing a memory leaks issue with amCharts5 when using a map with pulsating bullets. I only see this issue with the Microsoft Edge browser.

When using a map with pulsating bullets, if a lot of bullets are drawed (100+), I can see the used memory increasing constantly, and the page just crashes after a few minutes.
It also happens when using a few bullet, but in this case, the page just freezes and crash after a few minutes (between 10-15 minutes).

I can reproduce the issue just by keeping the demo page open like 10 minutes, with Edge : https://www.amcharts.com/demos/map-with-pulsating-bullets/

Thanks in advance for your help.

Kind regards

**Comment by xorspark** [comment]
amCharts5 issues should be posted in the [amCharts5 repo](https://github.com/amcharts/amcharts5/issues).
