### ISSUE TITLE
Apply fill and stroke colors on chart marker

### ISSUE THREAD

**Issue by jawaher1** [amcharts/amcharts4#3997]
I have two lineSeries chart. I want to apply the stroke color for the marker of first series and the fill color for the marker of the second one. Is this possible ? Thanks

**Comment by martynasma** [comment]
Do you mean legend marker?

If that is correct, I'm still not sure how is this a good idea. The legend would show different line color than the actual line color of the series?

**Comment by jawaher1** [comment]
Yes I meant legend marker.

Actually I am combining two things here. I am building a range chart with different colors(https://www.amcharts.com/demos-v4/range-chart-with-different-fill-colors-v4/) and "Line with different colors for ups and downs"
(https://www.amcharts.com/demos-v4/line-different-colors-ups-downs-v4/)
As you can see in the attached screenshot. I have too series chart balance and equity.
I want the balance stroke to be blue and the equity to be grey and then fill the ranges with soft pink and green depending on which series is below the other. Also for the equity chart I am displaying the ups in green and downs in soft pink. 
I want to display the markers as blue for the balance and grey for equity.
Here comes the problem.  If I set  marker.propertyFields.fill = "fill" the balance would be soft pink and if I set marker.propertyFields.fill = "stroke" the equity marker will be default black (because of the ups and downs) that's why I want to check if it's possible to use fill for one and stroke for the other.
![chart](https://user-images.githubusercontent.com/60270395/154238524-fbc7fb05-1afd-4959-9291-8bf0d97aec69.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by jawaher1** [comment]
Here is the JsFiddle https://jsfiddle.net/jawaher1/5ayu1sqj/55/

**Comment by jawaher1** [comment]
Here it is https://jsfiddle.net/jawaher1/5ayu1sqj/63/

**Comment by martynasma** [comment]
Thanks. I think we can work around that with an adapter:

```JavaScript
     marker.adapter.add("fill", function(fill, target) {
       if (target.dataItem) {
         var series = target.dataItem.dataContext.fill;
         return series.name == "Balance" ? series.fill : series.stroke;
       }
       return fill;
     })
```

**Comment by jawaher1** [comment]
It worked for me. Thanks
