### ISSUE TITLE
Multi-panel like charts multi-y axis rendered on right side is applied to all charts

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts4#3998]
**Question**

We are trying to utilize multi-panel like charts. please see attached chart image.

We have Gantt and line chart as a multi panel chart. In line chart i have multiple y axes rendered at different orientation(left or right). As per my example, Intrvl Kwh delivered and  Registered Kwh Delivered.

Issue is Registered Kwh Delivered is applied to Gantt Chart as well, but it should apply to line series. any idea on this would be appreciated! 

![image](https://user-images.githubusercontent.com/11607757/154225328-042c072e-fa98-446c-89be-6b5084611720.png)

**Comment by martynasma** [comment]
I suppose you need to add additional ValueAxis to the right-side. You can make it invisible by disabling its grid/labels, but it needs to be there so that there are two axes and they divvy up vertical space, like on the left.

Hope that makes sense.

**Comment by erYasar** [comment]
@martynasma how to divvy up on right side?

I am using layout type: vertical  `chart.leftAxesContainer.layout = "vertical"`. Currently amcharts divvy up by default.

**Comment by martynasma** [comment]
Well, you do have two axes on the left side.

What I'm saying you should add another axis to the right as well.

The divvying up of space will happen automatically :)

**Comment by erYasar** [comment]
@martynasma , It creates another y-axis on right and doesn't split up.
![image](https://user-images.githubusercontent.com/11607757/154237418-9e151b6d-c7b3-430f-aa6b-91928d823de0.png)

More information i am using multi-panel like chart. https://www.amcharts.com/multi-panel-like-charts-with-amcharts-4/
with setting `chart.leftAxesContainer.layout = "vertical"`

**Comment by martynasma** [comment]
Well, obviously you need to set `chart.rightAxesContainer.layout = "vertical"`, too :)

**Comment by erYasar** [comment]
Thank you @martynasma !!!
