### ISSUE TITLE
Getting TypeError when trying to zoom in beyond a point in multi series chart

### ISSUE THREAD

**Issue by rajat2654** [amcharts/amcharts4#3999]
When we try to zoom in a chart beyond a certain point, we are getting a TypeError as shown. This error occurs only when multiple series are used and not in case of single series.

Working chart example:
![c1](https://user-images.githubusercontent.com/48014274/154237796-7d3df984-8379-493d-a455-4793f965baba.png)

If we try to zoom in any further, error displayed in chart area:
![c2](https://user-images.githubusercontent.com/48014274/154238090-5181cb84-d2dc-4ddf-b10a-f80447fe079b.png)

Error displayed in console:
> TypeError: Cannot read properties of undefined (reading 'getTime')
    at e.setDataSet (core.js:1:529639)
    at core.js:1:355508
    at Object.e.each (core.js:1:806199)
    at t.each (core.js:1:983610)
    at e.calculateZoom (core.js:1:355474)
    at e.validate (core.js:1:888068)
    at e.validate (core.js:1:526502)
    at e.validate (core.js:1:960670)
    at e._systemUpdate (core.js:1:688172)
    at e._systemUpdate (core.js:1:213272)

Data source: We are using combined data source for both in which property names are different for each series
Ex:
> key_1: Tue Sep 14 2021 17:30:00 GMT+0530 (India Standard Time) {}
value_1: 0.0504
key_1: Sat Nov 27 2021 05:00:00 GMT+0530 (India Standard Time) {}
value_1: 0.2383
key_2: Tue Feb 16 2021 07:39:00 GMT+0530 (India Standard Time) {}
value_2: 73.4

We couldn't find the source of error in our implementation as the error is pointing to amcharts 4 library.
Any input on finding the source of error would be appreciated. 

Thank you

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
