### ISSUE TITLE
Chart tooltip not always wide enough

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#40]
It seems that when you have tooltips enabled, that the max-width of the tooltip is limited to the width of the chart. This causes issues when you have a narrow chart, but a long description:

![amchart_4_tooltip_background_too_small](https://user-images.githubusercontent.com/900497/40511329-511cb3dc-5f6d-11e8-9c61-682c7452879c.png)

As you can see from the screenshot above, the text runs out of the tooltip layer. 

(NOTE: The full text of the tooltip is "Assigned To Others: 37.5% (6)".)

Ideally the tooltip expands wide enough to fit the text. Alternatively, maybe the text wraps to multiple lines.

**Comment by martynasma** [comment]
Have you tried setting tooltip's options to workaround that?

A couple of pointers:

```
chart.tooltip.label.maxWidth = 300;
chart.tooltip.label.wrap = true;
```

**Comment by dswitzer** [comment]
@martynasma,

That doesn't seem to work correctly:

https://codepen.io/anon/pen/gzNjKb

(NOTE: I could only get it working by updating the PieSeries object.)

Setting `wrap: true` does force the label to wrap, but not if I set the `maxWidth` too. Trying to set the width just misses things up. It's like the text label expands, but not the whole tooltip.

When the `maxWidth` is set (which you can see in the example), the tooltip is visually left aligned (instead of centered) and does not match the pixel width.

**Comment by martynasma** [comment]
Hey @dswitzer.

Revisiting old issues. Does this issue still relevant to you with the latest version?

I did play around with the tooltips just now. The wrapping / maxWidth combo seems to work fine.

Let me know if I'm missing something, or we can close this.

**Comment by dswitzer** [comment]
Actually, the original issue seems to be resolved now, so I don't need to use the wrap function.
