### ISSUE TITLE
MapLineSeries and MapSplineSeries swapped straight/curved lines

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#400]
Pen:
https://codepen.io/team/amcharts/pen/d1597d1cc0282e22b91e2291f2f6f357

Offending code:
```javascript
var lineSeries = chart.series.push(new am4maps.MapLineSeries());
lineSeries.visible = false;
lineSeries.mapLines.template.propertyFields.imagesToConnect = "imagesToConnect";
lineSeries.data = [
  { imagesToConnect: ["brussels", "prague"] },
  { imagesToConnect: ["brussels", "athens"]},
  { imagesToConnect: ["brussels", "reykjavik"]},
  { imagesToConnect: ["brussels", "dublin"]}
];

var splineSeries = chart.series.push(new am4maps.MapSplineSeries());
splineSeries.visible = false;
splineSeries.mapLines.template.propertyFields.imagesToConnect = "imagesToConnect";
splineSeries.data = [
  { imagesToConnect: ["brussels", "prague"] },
  { imagesToConnect: ["brussels", "athens"]},
  { imagesToConnect: ["brussels", "reykjavik"]},
  { imagesToConnect: ["brussels", "dublin"]}
];
```

Screenshots:

Line series is curved:
![image](https://user-images.githubusercontent.com/2334143/46090415-ab5f7500-c17e-11e8-8ee2-68277ed8f443.png)

Spline series is straight:
![image](https://user-images.githubusercontent.com/2334143/46090458-bfa37200-c17e-11e8-8e80-edc0697e824f.png)

**Comment by zeroin** [comment]
It's not a bug, although it seems so. For line series to be straight, you must set:

lineSeries.mapLines.template.shortestDistance = false;

For spline series to be curved, the line should go through at least 3 points.

**Comment by martynasma** [comment]
FYI: https://www.amcharts.com/docs/v4/chart-types/map/#Curved_vs_straight_lines

**Comment by notacouch** [comment]
My apologies.

Awesome, thank you for the heads up. 

@martynasma  May want to consider noting the latter in the documentation, too, e.g.

https://www.amcharts.com/docs/v4/reference/mapsplineseries/
https://www.amcharts.com/docs/v4/chart-types/map/#Line_series


Something like (bold is my addition)

> Lines can be straight (`MapLineSeries`), arched (`MapArcSeries`), or smoothely curved (`MapSplineSeries`, **please note for lines to be curved they must pass through at least 3 points**).
