### ISSUE TITLE
Is it possible to auto-adjust bar widths within cell?

### ISSUE THREAD

**Issue by EtagiBI** [amcharts/amcharts4#4000]
Hello,

Let's assume that I have the following bar chart:
![изображение](https://user-images.githubusercontent.com/20855725/154260054-41dfb0d9-3a60-4470-9266-b16adafe0298.png)

If I switch off some items in the legend (say, sky blue and violet), I get the following result:
![изображение](https://user-images.githubusercontent.com/20855725/154260671-cc1aa134-c91a-4abd-9c51-cc3dad581f93.png)

As you can see, there's a lot of empty space within cells. 

Is it possible to auto-adjust bar widths within cell after swithcing legend elements on/off?

Desired result:
![изображение](https://user-images.githubusercontent.com/20855725/154262103-638b3307-a945-4a39-bcb4-a3d8a1509bc0.png)

**Comment by martynasma** [comment]
Yes. You can set series `clustered = false` when it's hidden so that other series can reclaim the space.

I put together a small example here:
https://codepen.io/team/amcharts/pen/QWOaKBe

**Comment by EtagiBI** [comment]
Thank you! That's exactly what I need!
