### ISSUE TITLE
XYChart cursor behavior panX movement is not smooth

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts4#4001]
**Bug description**

I am trying to use panning event to scroll the chart horizontally on mobile

I am using XYChart (StackedBar)

```ts
this.chart.cursor = new am4charts.XYCursor();
this.chart.cursor.behavior = 'panX';
```
the problem that it the chart does not scroll smoothly with the pan movement, it seems like there is a delay or an ease function that is being executed when panning!

Is this a known issue? or do I need to reproduce it?

How can I fix it?

**Environment (if applicable)**

 - amCharts version 4
 - Browser and its version
 - Related frameworks and their versions : Angular 13

**Comment by martynasma** [comment]
Yes, a repro case would be useful.

**Comment by MurhafSousli** [comment]
@martynasma Ok I prepared a [reproduction stackblitz]( https://stackblitz.com/edit/angular-ivy-usngvk?file=src%2Fapp%2Fbar-graph%2Fbar-graph.component.ts)

Need to open [this stackblitz demo](https://angular-ivy-usngvk.stackblitz.io/) to inspect in mobile view, then try to swipe or pan right and left on the graph

**Comment by MurhafSousli** [comment]
While reproducing I figured out the cause

in [this file](https://stackblitz.com/edit/angular-ivy-usngvk?file=src%2Fapp%2Fbar-graph%2Fbar-graph.component.ts) line 241, I pass an ease function...

commenting out that line, remove the heavy ease, however, there is still an ease. can that default ease disabled at all?

**Comment by MurhafSousli** [comment]
Yes, but also need to set the duration to 0

```ts
this.xAxis.rangeChangeDuration = 0;
this.xAxis.rangeChangeEasing = am4core.ease.linear;
```

**Comment by MurhafSousli** [comment]
After panning, when zoom event emits, is it possible to figure out the start date in chart viewport?

**Comment by martynasma** [comment]
There is no such universal event.

I suggest you debounce the code you need to execute when panning ends.

However, if you are looking for when pan animation ends, you can use `rangechangeended`.

**Comment by MurhafSousli** [comment]
@martynasma Thanks! one last thing, can I get the start and end dates from the `rangechangeended`?

**Comment by martynasma** [comment]
Well, you already have that code, don't you?

```JavaScript
    let start = axis.getPositionLabel(axis.start);
    let end = axis.getPositionLabel(axis.end);
```

**Comment by MurhafSousli** [comment]
@martynasma That gives the label of the axis, not the date, in my case the label is just one letter

![Screenshot 2022-02-22 at 10 44 14](https://user-images.githubusercontent.com/8130692/155105898-080b1701-8a8f-4fea-806f-6e133dd928d8.png)

Result, start is `S` and end is `S`

**Comment by martynasma** [comment]
Gotcha. OK, so `axis.min` and `axis.max` are timestamps.

You can easily convert them to Date object:

```JavaScript
let start = new Date(axis.min);
let end = new Date(axis.max);
```

**Comment by MurhafSousli** [comment]
Thanks a lot for the support!
