### ISSUE TITLE
Chart doesn`t render after display: none

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#4002]
Hi! My  charts are placed in two tabs. In purpose of improving perfomance, i am using display block and none to prevent redrawing charts after reopening tab: when the tab is clicked some charts get display: block and other ones get display: none. The problem is when i open the tab the first time - everything is going as expected - and then, when i try to open the second tab the chart is simply doesn't render (only xy and column charts, pie charts are okey, don't know, why)
![image](https://user-images.githubusercontent.com/18229211/154986738-3af19eb8-c38a-46b8-b1c1-db2d652daffc.png)
I`ve already tried to set min width and height, but it hasn't worked out. If i place all the charts on one tab - everything is fine.   
I am using react hooks, if there can be any ties with it

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by 12rita** [comment]
Finally managed to repeat this error: [Chart](https://codepen.io/12rita/pen/xxPjRdE)

**Comment by martynasma** [comment]
Thanks.

What are the steps to reproduce the behavior?

I tried clicking on the "Toggle chart" button a few times. It toggles off and on correctly.

**Comment by 12rita** [comment]
The expected behaviour is to change charts, clicking on toggle button. I changed buttons a little to clarify the usage, so when i click "chart 2", i expect the second chart to show

**Comment by martynasma** [comment]
Can you verify if the same is happening with similar setup outside React?

**Comment by 12rita** [comment]
No, i suppose this happens in React only
