### ISSUE TITLE
[amcharts-v4] [auto-zoom] :: Zooming of date axis does not work as expected

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4003]
**Question**
When I use `dateAxis.zoomToIndexes` to auto zoom the axis from `[1, data.length]`, the chart zooms out to show the data points not even in the dataset

```
dateAxis.zoomToIndexes(1, data.length, false, false);
```

**Current behaviour:**
<img width="529" alt="image" src="https://user-images.githubusercontent.com/10185101/154998752-00fc4f5e-52c0-4587-a9b9-0bb17df7f459.png">

**Expectation**
<img width="512" alt="image" src="https://user-images.githubusercontent.com/10185101/154998858-2233f573-af7b-42b8-a8ae-f3f87bafd9cf.png">

**Environment (if applicable)**
amCharts: v4
ReactJS
Chrome 98

**Additional context**
My expectation is that the zoom should be adjusted in a way that only the 0th data index should not be visible on the LHS
and the RHS should be such that it is at the last index of data
But here, the RHS shoots overboard to show the axis values that are not even in my data set

**Comment by martynasma** [comment]
DateAxis does not operate with series data items. It has own data items, that correspond to baseInterval and actual scope.

Therefore zooming to indexes on a DateAxis does not make a lot of sense, since it does not have direct 1:1 to indexes in data.

Use `zoomToDates()` instead.

**Comment by azharakbar** [comment]
Got it, Thanks @martynasma ! :-)
