### ISSUE TITLE
DateAxis: Add a second line label for every week

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts4#4004]
**Question**

How can I add a second line label on every Monday of the week as seen in the screenshot below (May 31)

![Screenshot 2022-02-22 at 18 39 14](https://user-images.githubusercontent.com/8130692/155187671-6e3f432e-ca37-46bf-892a-deb1373191ab.png)

[Stackblitz reproduction](https://stackblitz.com/edit/angular-ivy-v6rynn?file=src%2Fapp%2Fbar-graph%2Fbar-graph.component.ts)

```ts
// I use the following to show only the first char of the day
this.xAxis.dateFormats.setKey('day', 'EEEEE');
this.xAxis.periodChangeDateFormats.setKey('day', 'EEEEE');

// I tried adding the following but didn't work
this.xAxis.dateFormats.setKey('week', '[bold]MMM \n EE[/]');
this.xAxis.periodChangeDateFormats.setKey('week', '[bold]MMM \n EE[/]');
```

Another question, can I add right and left borders on the labels like it shown in the screenshot above?

**Environment (if applicable)**

 - amCharts version 4 
 - Related frameworks and their versions: Angular 13

**Comment by zeroin** [comment]
I would recommend adding adapter for the text property to a label template, like here:
https://codepen.io/team/amcharts/pen/gOXKeZN/96a17c00384cb438267763df97d1461b

The lines between labels are ticks.

**Comment by MurhafSousli** [comment]
@zeroin Nice! I also found another way using grouping labels https://www.amcharts.com/docs/v4/tutorials/grouping-axis-labels-using-ranges/, but I think the way in your example is better
