### ISSUE TITLE
How to get the start and end dates relative to chart viewport?

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts4#4006]
**Question**

I have a cursor panX activated

```ts
chart.cursor = new am4charts.XYCursor();
chart.cursor.behavior = 'panX';
```

I use `rangechangeended` event, but I cannot get the start and end dates relative to the **chart viewport**

```ts
this.xAxis.events.on('rangechangeended', (ev) => {
  let axis = ev.target;
  let start = axis.start;
  let end = axis.end;
  let min = axis.min;
  let max = axis.max;
  console.log(start, ' -- ', end, ' -- 'min, ' -- ', max);
});
```

None of the above properties change on panning, they are always the same which is not helpful to determine the start and end dates of the viewport.

How can I get the first and last dates being displayed in the chart?

![preview](https://user-images.githubusercontent.com/8130692/155105898-080b1701-8a8f-4fea-806f-6e133dd928d8.png)

[stackblitz rerpro](https://stackblitz.com/edit/angular-ivy-v6rynn?file=src%2Fapp%2Fbar-graph%2Fbar-graph.component.ts)

**Environment (if applicable)**

Angular: 13
AmChart: 4

**Comment by zeroin** [comment]
Try using `axis.maxZoomed` and `axis.minZoomed` values.

**Comment by MurhafSousli** [comment]
Yes, worked!
