### ISSUE TITLE
ColumnSeries3D "over" event not working

### ISSUE THREAD

**Issue by Jagan-P** [amcharts/amcharts4#4007]
**amCharts4 version: 4.10.24**

**Description:**
Adding "over" event to **_ColumnSeries3D_** doesn't work in both Object based approach and JSON based approach.

```
var series1 = chart.series.push(new am4charts.ColumnSeries3D());
series1.dataFields.valueY = "visits";
series1.dataFields.categoryX = "country";
series1.name = "Visits";
series1.tooltipText = "{categoryX}: [bold]{valueY}[/]";
series1.columns.template.fillOpacity = .8;
series1.events.on('over', (e) => {
  alert("3D series hovered");
});
```

In the above snippet ` alert("3D series hovered");` can never been seen. 

If `ColumnSeries3D` is changed to `ColumnSeries` in above snippet, the event works fine.

You can see this issue here [https://jsfiddle.net/uochbdsm/](https://jsfiddle.net/uochbdsm/)

**Comment by martynasma** [comment]
The event should be set on a column template, not series directly:

```JavaScript
series1.columns.template.events.on('over', (e) => {
  alert("3D series hovered");
});
```

**Comment by Jagan-P** [comment]
No that is different.

You can add events to column template in `ColumnSeries` too. 
However you can additionally adding events to entire series in case of `ColumnSeries` which gives access to whole lot of properties like `bulletsContainer` , `xAxis`, `yAxis` which I am looking for (and these are not available in column templates events)

But adding events to entire series doesn't work for `ColumnSeries3D` which I am looking for to access `bulletContainer` property in that `event.target` object.

I feel this is a bug. Could you please check this in detail?

**Comment by martynasma** [comment]
This is due how ColumnSeries3D is constructed.

You can easily derive series object out of the column over event too:

```JavaScript
series1.columns.template.events.on('over', (e) => {
  var series = e.target.dataItem.component;
  console.log(series.bulletsContainer);
  alert("3D series hovered");
});
```

**Comment by Jagan-P** [comment]
This works! Thanks   :)
