### ISSUE TITLE
PieSeries and PieSeries3D LabelBullet are hidden by default

### ISSUE THREAD

**Issue by Jagan-P** [amcharts/amcharts4#4008]
**Bug description**

When a `LabelBullet` is added to `PieSeries` or `PieSeries3D` it goes to hidden state by default.

```
var series1 = chart.series.push(new am4charts.PieSeries());
series1.dataFields.value = "visits";
series1.dataFields.category = "country";
series1.name = "Visits";

let bullet = new am4charts.LabelBullet();
bullet.label.text="{value}"
series1.bullets.push(bullet);
```

The label is not visible in this case. However when the `show()` method is called the `LabelBullet` is visible

```
bullet.events.on("ready", (ev)=>{
  ev.target.show();
});
```

Can be seen in action here: [https://jsfiddle.net/rqhL5461/](https://jsfiddle.net/rqhL5461/)
Comment and uncomment the ready function to see this issue.
![image](https://user-images.githubusercontent.com/31800888/156525268-547923dc-fbb9-43d1-a2e1-2d9577c77c85.png)

**Environment (if applicable)**

 - amCharts version: 4.10.24
 - Browser and its version: All browsers
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.] - All frameworks

**Additional context**

**Comment by Jagan-P** [comment]
No. 
Is there any way to make it not go to hiddenState by default?
I haven't mentioned anything expliticitly in chart config to make it go to the hiddenState.
So why is this happening (why does it go to hiddenState)?

**Comment by martynasma** [comment]
There's an underlying reasoning for bullets being hidden by default in PieSeries.

However, given that amCharts 4 is currently in feature freeze, and this not being a critical issue, I can't offer you a "fix" other than a workaround I provided above.

I'm hoping for your understanding.

**Comment by Jagan-P** [comment]
Oh okay. Let me use this then. Thanks for your help.
