### ISSUE TITLE
Date axis label is misleading or incorrect

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#4009]
I have a simple date chart (see CodePen link below) with two data points.

The first data point is: _06-Dec-2021 18:43:37.768_
And the second is: _05-Feb-2022 16:36:46.671_

I am therefore expecting the date axis labels to be _Dec_ and _Feb_, but they are actually Nov and Jan.

I have a date formatter that looks to be set correctly... am I missing something?

This is an aspect of the date charts that often confuse our customers and I'd like to know what the expected behaviour is.

**CodePen**
https://codepen.io/jbate/pen/NWwemPz?editors=0010

**Screenshots**
![image](https://user-images.githubusercontent.com/2857604/156584141-a6bea34c-3bb6-465f-a4cc-95c929464a44.png)

![image](https://user-images.githubusercontent.com/2857604/156584155-70c6ea9a-9527-4c89-9f0e-4786ce91d17e.png)

**Comment by martynasma** [comment]
You don't have `baseInterval` set for your `DateAxis` and thus let it decide as for the granularity of your data, which having just two data points is not very precise.

You need to set it manually, e.g.:

```
dateAxis.baseInterval = { timeUnit: "month", count: 1 };
```

More info:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Manually_specifying_data_granularity

**Comment by jbate** [comment]
Hi @martynasma thanks for the prompt response as always. That's very useful to know.

Do you have any advice if we don't know the data points beforehand? i.e. our customers can plug any data they want into the charts.
Is there anything we do can? Except parse the data ourselves to try and determine the granularity... although I guess amCharts already does this really.

**Comment by martynasma** [comment]
Well, you can ask your users to specify what granularity they want to view their data at?

Or, if you can do better job at figuring out granularity out of user's data than we do, that might also be an option. We do need to cover wide range of contingencies. If you accept data within certain parameters, there might be some easier ways to do it for you.

**Comment by jbate** [comment]
Yes, a configuration option to specify the granularity may be the easiest solution here.
