### ISSUE TITLE
access to data in array as valueY for dataFields

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#401]
hello,

i have a json that's an array of

`{c:epoch, v:[10,100,1000,3012345]}
`

i use

`series.dataFields.dateX = "c";
`
to indicate that on this serie, the epoch it's there
but i can't find a way to  tell to 

`series.dataFields.valueY`

to use v[0] or any particular index.

`series.dataFields.valueY = "v[0]"`

doesn't work.

change the json that i feed to chart, will be hard cos the json it's used for other component on application, and parse it and convert it, it's possible, but it require 20000 (data) *7 (number of charts per page) that seems overkilling (right now i am doing that, cos i haven't find a better way)

**Comment by martynasma** [comment]
The chart's data field can't bind to a member of an array.

You will need pre-process the data so that the chart can use it.

You can use an adapter to do that without modifying source data:

```
chart.adapter.add("data", function(data) {
  var newdata = [];
  for(var i = 0; i < data.length; i++) {
    newdata.push({
      c: data[i].c,
      v: data[i].v.constructor === Array ? data[i].v[0] : data[i].v
    });
  return newdata;
  }
})
```

P.S. the above code is not tested, but it should give you a pretty good idea.

**Comment by ramarro123** [comment]
ok, tnx, i think it's more efficient to use map() in my case.

the caveat it's that in that way, i need to reiterate over 20.000 elements every time i want to update dataset, that's why the option to read directly the dataset without pre-parsing will be, performance speaking, a bit better.

**Comment by martynasma** [comment]
Well, obviously you know your setup better. Yes, iterating once will be better, especially if you have large data sets.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
