### ISSUE TITLE
Stacked bar chart: show all categories tooltips on series column click 

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts4#4010]
**Question**

I need to show tooltips of all bar categories on click, but currently it only show the tooltip of one category

[Reproduction stackblitz](https://stackblitz.com/edit/angular-ivy-jlwmui?file=src%2Fapp%2Fbar-graph%2Fbar-graph.component.ts)

**Environment (if applicable)**

 - amCharts version 4
 - Angular 123

**Comment by martynasma** [comment]
You can use `showTooltipOn = "hit"` on series columns for that:

```JavaScript
series.columns.template.showTooltipOn = "hit";
```

https://www.amcharts.com/docs/v4/reference/sprite/#showTooltipOn_property

**Comment by martynasma** [comment]
Well, in that case you would need to catch "hit" event on the plot container, convert x/y coordinates to axis position, then trigger move of your XYCursor to that position.

I don't have a ready-made demo, but the following tutorials might be useful:
https://www.amcharts.com/docs/v4/tutorials/positioning-xy-cursor-via-api/

**Comment by MurhafSousli** [comment]
I followed that one, it is not helpful. I also don't know how to convert x/y coordinates into axis position.

**Comment by MurhafSousli** [comment]
Can you maybe provide the same example but on click instead of hover, because the hover is not a suitable solution on mobile

**Comment by martynasma** [comment]
The following tutorial details how you can track cursor position and retrieve it on click:
https://www.amcharts.com/docs/v4/tutorials/tracking-cursors-position-via-api/
