### ISSUE TITLE
Line chart scroll bar issue

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts4#4011]
Scenerio:

I have a line chart with scroll bar integrated. when i see full scroll bar data in the chart is good and when i select some rang data is missing in chart. Any idea what could be the problem?

Playground: https://codepen.io/eryasar/pen/yLPWJyY?editors=0010

Full scroll bar
![image](https://user-images.githubusercontent.com/11607757/157195696-d8b573e3-b4d7-4183-bf79-6fabd89bdc97.png)

Range selected: Missing data for april 21

![image](https://user-images.githubusercontent.com/11607757/157196091-bec02a17-e56c-41b6-9ded-83faea3c5146.png)

**Comment by martynasma** [comment]
Your data is in descending order. `DateAxis` expects data in ascending order, hence the anomalies.

**Comment by erYasar** [comment]
It worked! Thanks for the info
