### ISSUE TITLE
Multiple legends for the same chart

### ISSUE THREAD

**Issue by sd189** [amcharts/amcharts4#4012]
**Question**

Can I make multiple legends for the same chart?
the thing is that I'm using external legend and I'm placing it right next to the chart but on export I want to have it underneath with more simple layout and more compact from the original.

**Comment by martynasma** [comment]
I'm afraid charts do not support multiple legends.

I suppose you can create a completely custom legend used for export.

https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items
