### ISSUE TITLE
Wrong hours and minutes in tooltip 

### ISSUE THREAD

**Issue by andrewkazan** [amcharts/amcharts4#4014]
For example I took this demo: https://codepen.io/team/amcharts/pen/bGEVbJj?editors=1111 

I'm add this options for show tooltip 
dateAxis.tooltipDateFormat = 'yyyy-MM-dd HH:mm';

And I'm add hours and minutes to date for chart date. Now date has hours and minutes, but tooltip shown 00:00 instead real hours and minutes  

Screenshot in attached
![Screenshot 2022-03-09 at 4 49 19 PM](https://user-images.githubusercontent.com/31125066/157456545-7a6b3fd1-560e-4314-999e-e506a7538a9a.png)
 file

**Comment by martynasma** [comment]
Well, if you need granularity to show down to the minute, you will need to configure the `baseInterval` of the date axis accordingly:

```JavaScript
dateAxis.baseInterval = { timeUnit: "minute", count: 1 };
```

**Comment by andrewkazan** [comment]
Wow thanks! It's working for me
