### ISSUE TITLE
How to get tooltip in am4 barchart ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#4016]
I want tool tip for my bar chart in the format that it's value must be round to 2 decimal places.

`[
{"x": "Emi", "y": 749.8},
{"x": "Exceptions", "y": 452},
{"x": "Wiza", "y": 14},
{"x": "Michael", "y": 1212.6},
{"x": "Naveen", "y": 30},
{"x": "Praveen", "y": 20},
{"x": "Test", "y": 56.9},
{"x": "VCU", "y": 226}];`

Above is my chart data for each bar in a chart I need a tootip like **Emi : 749.80 USD** .
My code is in below link
[https://codepen.io/vineelak/pen/popJvdm]()

**Comment by martynasma** [comment]
Since you don't have a chart cursor, you need to set `tooltipText` on column templates:

```JavaScript
series.columns.template.tooltipText = '....';
```

**Comment by martynasma** [comment]
If you need two decimal digits, you need to use zeroes instead of hash tags in format: `#,###.00`.

**Comment by VineelaKantamneni** [comment]
Thank you.
