### ISSUE TITLE
Axis padding without a negative range

### ISSUE THREAD

**Issue by DanielScholte** [amcharts/amcharts4#4017]
Hello. I'm having some trouble adding padding to a value axis. I have the following two charts running the same code:
![Original_1](https://user-images.githubusercontent.com/22204349/158365885-82bd674f-e458-43c9-a3c4-cfa4f4b65753.png)
![Original_2](https://user-images.githubusercontent.com/22204349/158365898-3fe02297-6a1b-4e99-8e73-87ed67e61683.png)
  
The first chart shows a range starting at zero, which is correct in the current context.
The second chart, however, has too little padding the values, as is especially clear on the fifth value.
Starting the second at a minimum of zero would remove a lot of detail.
Adding padding using the `extraMin` property fixes this:
![padding_2](https://user-images.githubusercontent.com/22204349/158366675-11a1c8e4-c45b-4cec-aadb-10d693697935.png)

My issue is that this causes the range to go into the negatives when the minimum value is at or close to zero:
![padding_1](https://user-images.githubusercontent.com/22204349/158366775-7171ff2d-1a06-4abd-8b1a-91ec84e50e4e.png)

Is there an option to limit the min value for the range to zero, unless there are negative values in the dataset?

**Comment by DanielScholte** [comment]
Currently fixed it by removing the padding if the range would go below zero.
```ts
const yAxis: ValueAxis<AxisRenderer>; // The relevant ValueAxis
const values: number[]; // Series data

if (yAxis.extraMin != 0 && values.length > 0) {
    const seriesMax = Math.max(...values);
    const seriesMin = Math.min(...values);

    const rangeMin = seriesMin - ((seriesMax - seriesMin) * yAxis.extraMin);

    if (rangeMin < 0 && seriesMin >= 0) {
        yAxis.extraMin = 0;
    }
}
```
An alternative solution is appreciated :)

**Comment by DanielScholte** [comment]
I'm currently using the following code to remove the padding if the range would fall below zero while the minimum series value is above zero.
The calculation is based on the [`getMinMax` function of the ValueAxis class](https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/axes/ValueAxis.ts#L1317), but is incomplete and possibly flawed. But (for now) seems to work for my use case.
Any alternative solution or improved calculation would be helpful :)
```ts
const yAxis: ValueAxis<AxisRenderer>; // Relevant ValueAxis = series.yAxis as ;
const values: number[]; // Series data

if (values.length > 0) {
    const seriesMax = Math.max(...values);
    const seriesMin = Math.min(...values);

    const rangeMin = seriesMin - ((seriesMax - seriesMin) * yAxis.extraMin);

    if (rangeMin < 0 && seriesMin >= 0) {
        yAxis.extraMin = 0;
    }
}
```

**Comment by martynasma** [comment]
How about utilizing chart's `datavalidated` event (kicks in when new data is loaded and parsed).

You could then check actual scale of the axis, then set (or unset) `extraMin` accortingly.

Does that make sense?

**Comment by DanielScholte** [comment]
I've since migrated to Amcharts 5. Tried applying the `datavalidated` event on the series, but I'm unsure where I would retrieve the actual scale of the axis.  
Even when applying the `frameended` event on the root object, both the `min` and `minFinal` properties of the axis are incorrect (placeholder values?).
