### ISSUE TITLE
How can I add a border top alike in AxisRange

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts4#4018]
**Question**

How can I add a line on top of each range segement in the graph?

My code shows a lines for all sides, but I just need a separator line.

```ts
private createRange(value: number, endValue: number, color: string): void {
    const range = this.yAxis.axisRanges.create();
    range.value = value;
    range.endValue = endValue;
    range.axisFill.fill = am4core.color(color);
    range.axisFill.fillOpacity = 0.1;
    range.axisFill.stroke = am4core.color(color);
}

this.createRange(0, 40, '#D0021B');
this.createRange(40, 60, '#FE9000');
this.createRange(60, 100, '#63AF11');
```

**Current:** border for all sides

![Screenshot 2022-03-16 at 11 40 32](https://user-images.githubusercontent.com/8130692/158572060-3ca8de84-5972-4307-a5bf-7ba5e3207465.png)

**Desired:** only border top

![Screenshot 2022-03-16 at 11 41 07](https://user-images.githubusercontent.com/8130692/158572122-6f5eca1c-6fa7-499e-b9a0-f51d05d76667.png)

**Environment (if applicable)**

- Angular 13
- AmCharts 4

**Comment by martynasma** [comment]
Try this:

```JavaScript
range.axisFill.fillOpacity = 0.2;
range.axisFill.strokeWidth = 2;
range.axisFill.strokeOpacity = 1;
range.axisFill.stroke = "#f00000";
```

**Comment by martynasma** [comment]
Oops, sorry, I took the question the wrong way.

You should not add stroke on axis fill then but instead color the the axis range grid line:

```JavaScript
range.grid.strokeWidth = 2;
range.grid.strokeOpacity = 0.1;
range.grid.stroke = am4core.color(color);
```

And also remove the code that relates to `axisFill.stroke*`

**Comment by MurhafSousli** [comment]
Ok now it looks better, but the line is in the center, can I shift it to the `endValue` position?

![Screenshot 2022-03-16 at 15 31 12](https://user-images.githubusercontent.com/8130692/158613561-1de1c6bf-2859-4d19-912b-cab4c901383d.png)


```ts
range.value = value;
range.endValue = endValue;
range.axisFill.fill = am4core.color(color);
range.axisFill.fillOpacity = opacity;
range.grid.strokeWidth = 1;
range.grid.stroke = am4core.color(color);
range.grid.strokeOpacity = 1;
```
