### ISSUE TITLE
How to limit the date x axis with certain interval?

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts4#4019]
For example : I have series of data from Jan'2020 - Jan'2022.

Is it possible to set the chart max limit to Dec'2021? other data in Jan 2022 should be hidden and also scroll should behave the same?

**Comment by martynasma** [comment]
Yes:

```JavaScript
dateAxis.max = new Date(2021, 11, 31).getTime();
```

**Comment by erYasar** [comment]
@martynasma , Thanks it works!
