### ISSUE TITLE
Eckert6 projection + chart.zoomControl = planet shifts to upper left quadrant

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#402]
Pen:
https://codepen.io/team/amcharts/pen/12bcb2b28677989cf2afe6549f1c7d7c

Offending code:
```javascript
// Create map instance
var chart = am4core.create("chartdiv", am4maps.MapChart);

// Set projection
// If you omit this line, the map centers properly
chart.projection = new am4maps.projections.Eckert6(); 

// Zoom control
// If you omit this line, the map centers properly
chart.zoomControl = new am4maps.ZoomControl();

var continentsSeries = chart.series.push(new am4maps.MapPolygonSeries());
// continentsSeries.geodata = am4geodata_worldLow; // happens with this, too.
continentsSeries.geodata = am4geodata_continentsLow;
continentsSeries.useGeodata = true;
```

Screenshot before finished loading:
![image](https://user-images.githubusercontent.com/2334143/46102257-e623d600-c19b-11e8-9091-3b5fece9c82e.png)

Screenshot after finished loading:
![image](https://user-images.githubusercontent.com/2334143/46102225-d99f7d80-c19b-11e8-8433-9654fc261ab9.png)

**Comment by zeroin** [comment]
This should work fine with current version.
