### ISSUE TITLE
Percentage sign in Chart tooltip in RTL should be placed on the left.

### ISSUE THREAD

**Issue by driskull** [amcharts/amcharts4#4021]
**Bug description**

When a pie chart is displayed right-to-left, the value percentage sign should be on the left instead of on the right.

<img width="460" alt="Screen Shot 2022-03-17 at 11 25 35 AM" src="https://user-images.githubusercontent.com/1231455/158871203-19a29693-3ca3-40e8-aa6b-3c1e9ff8b851.png">

<img width="298" alt="Screen Shot 2022-03-17 at 11 25 48 AM" src="https://user-images.githubusercontent.com/1231455/158871221-d0f55d91-1c77-4133-9c1e-ae0f553817fa.png">

Expected results:
Percentage sign should be listed at the left of number in pop-up dialog.

**Environment (if applicable)**

"@amcharts/amcharts4": "4.10.23",

Chrome  99.0.4844.51

**Additional context**

const chart = am4core.create(chartDiv, am4charts.PieChart);
chart.rtl = true;

I tried also setting `rtl` to true on the `tooltip` instance but it didn't make a difference.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by driskull** [comment]
Hi @martynasma,

Yes here's a codepen: https://codepen.io/laurenb14/pen/OJOEGpM?editors=1000

If you wait for the map to load and click on a feature you should be able to see it.

Heres a repro using amcharts sample:
https://codepen.io/driskull/pen/OJzNMRX

I did see this doc: https://www.amcharts.com/docs/v4/concepts/rtl/#Numbers

> This is true for the mixed-language content only.

> If our labels would contain only Latin (letf-to-right) text or numbers/symbols, it would remain as is: rtl setting would have no effect over it.

**Comment by martynasma** [comment]
Thanks.

I don't think there's a anything we can do here, as SVG renderer is treating text differently than HTML.

You can change label text, though:

```JavaScript
pieSeries.labels.template.text = "{category}: %{value.percent.formatNumber('#.0')}";
```

**Comment by driskull** [comment]
Thanks this seems to work:

```ts
series.slices.template.tooltipText = chart.rtl
      ? "{category}: %{value.percent.formatNumber('#.0')}"
      : "{category}: {value.percent.formatNumber('#.0')}%";
```
