### ISSUE TITLE
Incorrect dates in the event

### ISSUE THREAD

**Issue by ifoba** [amcharts/amcharts4#4022]
If we don't use any animation themes, we get incorrect data in the listener.
I gave an example in which you get the correct data, only with a certain delay.
To reproduce the bug, simply select the area in the center of the graph. Watch the result in the console.
[CodePen](https://codepen.io/ifoba/pen/BaJKBKr?editors=0011)

**Comment by martynasma** [comment]
`startchanged` and `endchanged` kick in before actual zoom is happening.

I suggest you use a single event `startendchanged` which kicks in after actual zoom.

**Comment by ifoba** [comment]
Thanks, now it works correctly.
