### ISSUE TITLE
So much of empty space in charts which is very significant when the container is small

### ISSUE THREAD

**Issue by Jagan-P** [amcharts/amcharts4#4023]
**Question**

We are using amcharts inside resizeable containers. When the container size is small, **_almost 18% of the container height in the bottom is unused_** (please see the below image).
![image](https://user-images.githubusercontent.com/31800888/159439050-81dc8e31-a33a-4740-ad59-f460ecc87017.png)

When legends are enabled it becomes even worse, since **_almost 32% of the height of the container is unused_** (split across the top and the bottom of the legend)
![image](https://user-images.githubusercontent.com/31800888/159438665-71d545fb-4aee-4c3a-82b4-21feb8f63013.png)

Is there a way to make charts use up this space? (the columns in series can be shown longer, the x-axis labels can show additional characters and so on)

-->

**Environment (if applicable)**

**Additional context**

**Comment by Jagan-P** [comment]
Okay, this doesn't happen naturally. For few types of charts alone `transform="translate(15,15)"` is being added which is bit significant for smaller containers. After removing this transform using css, this happens.

**CSS to remove transform:**
```
.amcharts-Container.amcharts-Component.amcharts-Chart.amcharts-SerialChart.amcharts-XYChart {
  transform: translate(5px, 0);
}
```

This can be seen here [https://jsfiddle.net/cjg9yf7x/](https://jsfiddle.net/cjg9yf7x/)

Is there a better way of doing this?

**Comment by Jagan-P** [comment]
For legends more space can be saved if we remove the red area here (only green area should be sufficient)

![image](https://user-images.githubusercontent.com/31800888/159462756-1992cc78-17af-499d-bfaa-3fd5e7cb3a3f.png)

**Comment by martynasma** [comment]
I'd suggest you remove default padding from the bottom: `paddingBottom: 0`.

**Comment by Jagan-P** [comment]
> I'd suggest you remove default padding from the bottom: `paddingBottom: 0`.

I tried adding `paddingBottom: 0` to both legend and markers inside it. Doesn't help.

```
legend: {
    scrollable: true,
    disabled: !chartConfig.showLegend,
    position: chartConfig.legendPosition,
    scrollbar: {
        width: 20,
    },
    markers: {
        width: 16,
        height: 16,
        paddingBottom: 0
    },
    paddingBottom: 0
}
```

**Comment by Jagan-P** [comment]
> Okay, this doesn't happen naturally. For few types of charts alone `transform="translate(15,15)"` is being added which is bit significant for smaller containers. After removing this transform using css, this happens.
> 
> **CSS to remove transform:**
> 
> ```
> .amcharts-Container.amcharts-Component.amcharts-Chart.amcharts-SerialChart.amcharts-XYChart {
>   transform: translate(5px, 0);
> }
> ```
> 
> This can be seen here https://jsfiddle.net/cjg9yf7x/
> 
> Please see the comparison.
> 
> ![image](https://user-images.githubusercontent.com/31800888/159460555-24d389c6-4320-4d15-9df0-7f0013c89ee1.png)
> 
> Is there a better way of removing the transform so that the space can be used by the chart elements (series, axis labels etc.)?
> 
> It would be even better if the green area marked on above images could be used too (basically reduced the gap between the x-axis title and the legend and between the legend and the bottom of the container)


@martynasma, may I know how to remove this transform properly so that there is more space in small containers?

**Comment by Jagan-P** [comment]
Setting all four sides of padding to zero to the overall chartObject gives lot of space. 

It is infact this default padding that adds `transform="translate(15,15)" to certain chart types like XYChart, RadarChart, TreeMap etc.

Thanks.
