### ISSUE TITLE
Incorrect tooltip position in y-axis title even after forceCreate and specifying proper pointerOrientation

### ISSUE THREAD

**Issue by Jagan-P** [amcharts/amcharts4#4025]
**Bug description**

According to the official docs the default [pointerOrientation](https://www.amcharts.com/docs/v4/reference/tooltip/#pointerOrientation_property) for charts is `"horizontal"` and it should `Show tooltip either to left or right of the target area, depending on the position within the chart.`

This doesn't happen when adding tooltip to y-axis title. The y-axis title is clearly to the left hand side of the container. It is expected that the tooltip should appear to the right side of y-axis title on hover. But it doesn't happen.

Even after `forceCreate` and specifying ` "pointerOrientation": "horizontal"` this doesn't work.

![image](https://user-images.githubusercontent.com/31800888/159471081-4433588f-f517-4847-b1f8-ce08525bff55.png)

Can be seen [here](https://jsfiddle.net/hx7dob6j/) when you hover on y-axis title `No. of records`

**Environment (if applicable)**

**Additional context**

**Comment by Jagan-P** [comment]
This becomes really painful. Tooltips in general have to be smart enough to determine its best position in all four directions (up, down, left and right) by itself. Many tooltips (in general from other frameworks) can do this and there is even an option to append the tooltip to other containers like "body" tag so that they can overflow and are really flexible.

Please try to provide this feature.

**Comment by martynasma** [comment]
The only workaround I can think of is to override tooltip's `boundingContainer`:

```
            "type": "ValueAxis",
            "title": {
                "text": "No. of records",
                "id": "axis-title-6239acd2f622df003e6860e7",
                "truncate": true,
                "userClassName": "",
                "tooltipText": "No. of records",
                "tooltip": {
           	     "type": "Tooltip",
                 "forceCreate": true,
                "pointerOrientation": "horizontal",
                "callback": function() {
                  this.boundingContainer = this.topParent.tooltipContainer;
                }
              }
            },
```

Of course, it means that config like that cannot be fully serialized.

**Comment by Jagan-P** [comment]
> The only workaround I can think of is to override tooltip's `boundingContainer`:
> 
> ```
>             "type": "ValueAxis",
>             "title": {
>                 "text": "No. of records",
>                 "id": "axis-title-6239acd2f622df003e6860e7",
>                 "truncate": true,
>                 "userClassName": "",
>                 "tooltipText": "No. of records",
>                 "tooltip": {
>            	     "type": "Tooltip",
>                  "forceCreate": true,
>                 "pointerOrientation": "horizontal",
>                 "callback": function() {
>                   this.boundingContainer = this.topParent.tooltipContainer;
>                 }
>               }
>             },
> ```
> 
> Of course, it means that config like that cannot be fully serialized.

Inside the callback function, `this.boundingContainer` is undefined. Did you mean `tooltipContainer`?

**Comment by martynasma** [comment]
Yes, it's undefined by default, hence it not being determine how to position the tooltip.

But if you set it to some actual sized element of the chart, like `tooltipContainer`, it now has point of reference to position against.

**Comment by Jagan-P** [comment]
This works perfectly for all different combinations. 

Tooltips for Y axis on the right, y axis on the left, x-axis on the top and the bottom (basically `axis.renderer.opposite`) and even when the chart is rotated with `axis.renderer.inversed`

This works perfectly for `RadarChart` too and with rotated RadarChart too.

And for wrapping long text added `maxWidth` and `wrap` too.

```
tooltip: {
    type: "Tooltip",
      forceCreate: true,
    "callback": function() {
        this.boundingContainer = this.topParent.tooltipContainer;
        this.label.maxWidth = this.topParent.tooltipContainer.pixelWidth*0.8;
        this.label.wrap = true;
    }
}
```
So this entirely goes inside `title` property of axis.

Thanks again @martynasma

**Comment by Jagan-P** [comment]
There is a problem when the container where the chart is put inside resizes
Basically `this.topParent.tooltipContainer` doesn't scale according to container size changes?

**Comment by martynasma** [comment]
You might need to add "sizechanged" event to the chart to resize your title accordingly.

**Comment by Jagan-P** [comment]
I am adding "sizechanged" event to axis. But the results are random or inaccurate unlike what it yielded in `callback`.

![image](https://user-images.githubusercontent.com/31800888/159694757-9a053fe6-72ab-4d84-9a0f-d66f6a4411b2.png)

![image](https://user-images.githubusercontent.com/31800888/159695013-1afb8e58-d622-4141-b6df-c49f46ab752f.png)

The text `y-axis No.of records......` is the actual tooltip text.
The tooltip background size is incorrect (the black background)
