### ISSUE TITLE
How to make a column in a column series clickable ?

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4026]
**Question**
I have a Column series chart as shown in the below image
<img width="496" alt="image" src="https://user-images.githubusercontent.com/10185101/159560308-2614f0fc-9587-4177-8ca7-23f2f6c65f8c.png">

How can I trigger a click event on this column so as to do a user defined action ?

**Environment (if applicable)**
 - amCharts version 4

**Additional context**

**Comment by azharakbar** [comment]
I want to click each column in the chart so as to show a popup with relevant details related to that column of the series

So how can I bind a click event to each column in the series ?

**Comment by azharakbar** [comment]
In this case, i want the click handler to have the data "FM-HVAC"

**Comment by azharakbar** [comment]
```tsx
columnSeries.columns.template.events.on(
	"hit",
	function (ev) {
		const tradeName = ev?.target?.dataItem?.categories?.categoryX;
		if (!tradeName) return;

		console.log(tradeName);
	},
	this,
);
```

Figured out how to do it 👍 
Is this the correct way ?

**Comment by martynasma** [comment]
Yes, it's a correct way ;)

**Comment by azharakbar** [comment]
Thanks @martynasma
