### ISSUE TITLE
Hi, i have question

### ISSUE THREAD

**Issue by mic3b** [amcharts/amcharts4#4029]
### **Hi, I have question about RadarChart**

I am currently having a problem with RadarChart. Tries to place one smaller RadarChart inside the larger Chart. The smaller RadarChart should be in the center of the larger one. Any of you have any idea how to do this?

![A151DEB6-E728-491E-B42A-66936A404D35](https://user-images.githubusercontent.com/52372495/159748981-fa6e02b8-0d16-443f-9acb-9c037acc8c69.jpeg)

_(My point is for the smaller RadarChart to be inside this empty circle)_

**Environment (if applicable)**

amCharts 4

**Additional context**

**Comment by martynasma** [comment]
The idea would be to have two axes in `chart.yAxes` with different `radius` and `innerRadius` set.

Then you can bind series to those axes via series `yAxis`.

Here's a demo that does exactly that:
https://www.amcharts.com/demos-v4/radar-chart-visualizing-yearly-activities-v4/

Hope it makes sense.
