### ISSUE TITLE
Category Axis (Y-axis) labels not positioned correctly after data change (when minWidth & maxWidth are set)

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#403]
Quite specific issue here:
https://codepen.io/team/amcharts/pen/37a4e70fd9470a3bfba4634c41c8cf90?editors=1010

Bar Chart with 6 categories. On `datavalidated`, I zoom in to 3 categories and enable panning on the Y axis. When  `chart.data` is replaced (and the chart is on its original zoom/pan position), the category axis labels seem to group together on the top-left corner.

![image](https://user-images.githubusercontent.com/13300227/46138095-4faeed80-c24b-11e8-82d4-ea2cedaffd32.png)
 
I believe this has something to do with setting `categoryAxis.minWidth` and `categoryAxis.maxWidth`. By replacing both lines with `categoryAxis.width`, the issue does not appear.

**Comment by zeroin** [comment]
Fixed
