### ISSUE TITLE
[pie-chart] :: How to get the entire chart data set when clicked on a single slice

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4030]
**Question**
Can I get the entire chart data set when clicked on any slice in the pie chart

<img width="199" alt="image" src="https://user-images.githubusercontent.com/10185101/159908070-076af481-d05e-4758-af12-a11d6d2f6950.png">

Suppose If I Click on slice 1, can I get the information of slice 2 also in the "hit" handler ?
Is there some other way to get the entire chart data set when "hit" event is invoked

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
How about just use `chart.data`?

**Comment by azharakbar** [comment]
got it ... thanks @martynasma
