### ISSUE TITLE
BundlePhobia throws an error

### ISSUE THREAD

**Issue by LucasWagner1607** [amcharts/amcharts4#4034]
I need details from the package so i tried Bundlephobia to get those details. Unfortunately i got an error.
Sometimes the error "Internal Server Error" occurs. But i think this is a problem with BundlePhobia.
The other times the error "EntryPoint Error" occurs. 

Steps to reproduce: 
Go to this website: [https://bundlephobia.com/package/@amcharts/amcharts4](url)
Error occurs.

I found another bug report on github that looks like it's the same error: [https://github.com/FriendsOfReactJS/react-css-themr/issues/38](url)
And this article describes the entry point topic: [https://bytearcher.com/articles/main-property-in-package.json-defines-entry-point/](url)

I hope that helps.

**Comment by Pauan** [comment]
@LucasWagner1607 Thanks for the report. This is a bug in BundlePhobia, so there's nothing we can do about it. amCharts 4 doesn't have a main entry point, it has multiple entry points, which BundlePhobia doesn't seem to support.
