### ISSUE TITLE
Is it possible to format cursor text to display 2 decimal places

### ISSUE THREAD

**Issue by geervani** [amcharts/amcharts4#4035]
Hi,

We have a line series with cursor enabled. Is it possible to show the y axis value with 2 decimal place formatting.
![image](https://user-images.githubusercontent.com/9427328/160639246-e3a438d2-72e6-423a-a9fe-d97792943afb.png)

I want to format the highlighted part as we don't have the tooltip.

I am using the the below sample
https://codepen.io/team/amcharts/pen/wRGxPa?editors=0010

Thanks

**Comment by martynasma** [comment]
You're probably looking for this:
https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/#Number_precision_on_ValueAxis

**Comment by geervani** [comment]
> You're probably looking for this: https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/#Number_precision_on_ValueAxis

thanks for the quick reply @martynasma, setting  yAxis.extraTooltipPrecision = 2; worked
