### ISSUE TITLE
Label Event Issue - Removing previous clicked Label upon next clicked Label

### ISSUE THREAD

**Issue by RT404** [amcharts/amcharts4#4036]
In Amcharts 4, we've investigated events on Labels and we've not been able to get the event.off to work (as per the documentation).

When we click (hit) on one of our categoryAxis Labels, we for instance **bold** the Label, however when we click on another Label, the first clicked-on Label remains bolded. What we want is for the clicked Label to remain bolded, and the bolding removed when clicking on another Label.

We've added a stripped down CodePen with the basics. In this example any Label clicked remains bolded, but only desire the most recently clicked on Label to be bolded.

CodePen:
https://codepen.io/Sunburn/pen/mdpwxoV

Any help is very much appreciated, thank you in advance.

AmCharts 4
Angular / .ts
All browsers

**Comment by martynasma** [comment]
What you need to to is to log the last clicked label instance. When another click occurs, you can just reset `fontWeight` on the last label to whatever is your default.

Does that make sense?

**Comment by RT404** [comment]
> 
I'm not sure how you mean logged, but by default are you hinting at a state adapter?

**Comment by RT404** [comment]
Update: At line 75, I've updated the CodePen with a default "State". Then in the function I have a conditional that I'm attempting to remove the bolding from any other previously selected Labels, with no effect (and in two different ways, 1) using the Default State, and 2) forcing the categoryAxis of all Labels).

**Comment by martynasma** [comment]
Try something like this:

```JavaScript
function labelClick(ev) {
  categoryAxis.renderer.labels.each(function(label) {
    label.fontWeight = "normal";
  })
  if (ev.target.fontWeight !== "bold") {
    ev.target.fontWeight = "bold"; // Successfully makes target Bold
  }
}
```

**Comment by RT404** [comment]
Thank you Sir! This indeed did the trick, we appreciate it very much... Thanks again.
