### ISSUE TITLE
Lineseries  tooltip without using a cursor

### ISSUE THREAD

**Issue by geervani** [amcharts/amcharts4#4037]
Hi,

We have the grid with charts in each row as shown in the picture below.
Its a line series and need to display tooltip on hover on the chart series. Is there a way to display tooltip without using a cursor? 
We don't show x, y axis either.  We are using amcharts4

![image](https://user-images.githubusercontent.com/9427328/161202420-738bfa41-c3a0-417b-afe3-de9dff79cb6f.png)

I tried series.tooltipText = "{valueY}"; doesn't seem to work..

Thanks
Geervani

**Comment by martynasma** [comment]
You will need to add a cursor for that.

You can hide all visual elements of the cursor if you don't need them, e.g.:

```JavaScript
chart.cursor.lineX.disabled = true;
chart.cursor.lineY.disabled = true;
xAxis.cursorTooltipEnabled = false;
yAxis.cursorTooltipEnabled = false;
```
