### ISSUE TITLE
Network graph does not seem to have edge weight option

### ISSUE THREAD

**Issue by CordThomas** [amcharts/amcharts4#4038]
**Question**

I have a network that has edge weights which is pretty common in network theory.   I do not see a way to represent the edges based on those weights.   

An example might be:

    {from: "Richard", to: "Larry", weight: 4},
    {from: "Richard", to: "Marta", weight: 7},
    {from: "Larry",   to: "Marta", weight: 1}

The idea would be that the style (thickness, color, etc) of the edge line would be based on that weight value.

**Comment by martynasma** [comment]
Do you mean something link this?

https://www.amcharts.com/docs/v4/tutorials/variable-link-widths-in-forcedirectedtree/

**Comment by CordThomas** [comment]
yes, I did not see that - very helpful.  Thank you.
