### ISSUE TITLE
Bar chart bullet labels overlapping when we have large number as a avlewu

### ISSUE THREAD

**Issue by anthin777** [amcharts/amcharts4#4039]
**Question**
  I am not bel able to show full bullet label of a bar chart when it was a large number , even I have used the 
valueLabel.label.truncate = false;
valueLabel.label.hideOversized = false;
still some part of the number was hidin.

In my case I want to show full value at right side of the bar ? any suggestions to fix this would be appreciate.
![image](https://user-images.githubusercontent.com/82396535/161671226-1d3b872f-53e8-4891-9e8e-6c212fc0d7ed.png)

https://codepen.io/nithin7799/pen/xxppeLW

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Please read this response: https://github.com/amcharts/amcharts4/issues/3887#issuecomment-969435643

**Comment by anthin777** [comment]
As suggested in above mentioned issue, Tried by using chatrt.maskbullets = false, But in this case my labels were going out of the box, I want to show full label with in the plot area.
![image](https://user-images.githubusercontent.com/82396535/161886765-0da4e9d5-3e09-4e69-a990-ee4d9a05d5b2.png)

**Comment by anthin777** [comment]
@martynasma , Can please reopen the ticket ?

**Comment by martynasma** [comment]
In this case, you can relatively expand X axis scale:

https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Relatively_expanding_the_scale
