### ISSUE TITLE
addData doesn't recalculate max/min

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#404]
if addData contains data that are out of chart margin, max/min aren't recomputed
and i have to force max to see the chart correctly.

https://codepen.io/anon/pen/KGPoZM?editors=0010

if you uncomment the min/max portion of code, you see the data correctly, if you leave the code commented, the last item doesn't get displayed

**Comment by martynasma** [comment]
Most clearly a bug. Thanks for the heads up!

**Comment by zeroin** [comment]
Could you check it with current version, it should be fixed. At least your demo works fine :)

**Comment by ramarro123** [comment]
i don't use amchart anymore ,can't check, sorry

**Comment by martynasma** [comment]
No problem.

I'm closing this, but please feel free to post any follow up questions you may have.
