### ISSUE TITLE
Update color of tiles of treemap dynamically

### ISSUE THREAD

**Issue by piyushfs** [amcharts/amcharts4#4040]
I am using a websocket server which streams data every 5 seconds. Whenever the data is received the treemap is updated with the new values as:

`children = chart.dataItems.values

for (var c = 0; c < children.length; c++) {

 let child = children[c];
 
child.value = newvalue

}`

This updates the data with a very nice easing transition of the series template.
However I am not able to update the colors of the tiles.

I want to be able to update the colors of the tiles and call all the adapters on every update. I also dont want to use the chart.invalideData() or chart.invalidateRawData() because I absolutely need the animation which runs on the series object rather than the chart object.

**Comment by zeroin** [comment]
You can access column via seriesDataItem:
`child.seriesDataItem.column.fill = am4core.color("#ff0000");`

**Comment by piyushfs** [comment]
Thanks a lot! Helped me big time!
