### ISSUE TITLE
Is there's a way to define the start and end data to the x- axis in time series?

### ISSUE THREAD

**Issue by soumyaa1804** [amcharts/amcharts4#4042]
**Question**

In xyChart, when we are creating line chart with date as x-axis, the axis itself adjust the data to be shown on x axis. I want to get the min date and max date from the data on x-axis for sure. Other dates can adjust themselves. I tried using [dynamic fixed scale](https://www.amcharts.com/docs/v4/tutorials/fixed-value-axis-scale/#Dynamic_fixed_scale) on x axis but the max value still shows undefined after assigning.

**Environment (if applicable)**

amChart 4
Chrome
React.js

**Additional context**

None

**Comment by martynasma** [comment]
I'm afraid I'm not entirely sure what you are trying to achieve. You want to fix DateAxis min and max so that it cannot be zoomed?

**Comment by soumyaa1804** [comment]
In my line chart, where the x axis represents dates, I want my x-axis to show minimum date from my data and maximum date of my data for sure. Like right now, the chart itself adjust which all dates with labels would be shown on x-axis based upon the chart space we have. But I want to make sure the maximum and minimum dates are shown and the dates in between can adjust themselves.

**Comment by zeroin** [comment]
Here is a tutorial about it: https://www.amcharts.com/docs/v4/tutorials/force-first-and-last-labels-on-axis/
