### ISSUE TITLE
Tooltip position is different when set on series instead of template

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#4043]
If I set the tooltip text for a series on its columns template, the position of the tooltip is in the middle of the bar:
```js
series.columns.template.tooltipText = "{categoryX}: [bold]{valueY}[/]";
```
![image](https://user-images.githubusercontent.com/2857604/162221846-2cd593af-dce4-45f7-803f-34936f33103b.png)

However, if I set the tooltip text on the series itself, the position of the tooltip is at the top of the bar:
```js
series.tooltipText = "{categoryX}: [bold]{valueY}[/]";
```
![image](https://user-images.githubusercontent.com/2857604/162223311-de18ce6e-04a5-4769-888a-4f41d21fe483.png)

Is there a reason for this difference? I assumed it was related to the usage of a cursor.

The reason I ask is because I have a chart with a Y-axis max limit set (to crop off a large value) and it's tooltip is no longer visible if I set the tooltip text on the series instead of its template. 

**CodePen**
https://codepen.io/jbate/pen/MWrVXPV?editors=0010

My preference would be for the tooltips to remain "top aligned", however to always be visible in cases where a column is cropped.

**Comment by martynasma** [comment]
To work around it, you need to set `tooltipText` on column template, not series.

To reposition to the top of the visible portion of the column, simply use `tooltipY`:

```
series.columns.template.tooltipY = 0;
```

**Comment by jbate** [comment]
Perfect! Thanks for the prompt reply as always. 👍
