### ISSUE TITLE
zh_Hans locale .js file doesn't support nonce

### ISSUE THREAD

**Issue by TomBertie** [amcharts/amcharts4#4044]
**am4core.options.nonce supports locales except for zh_Hans**

When I set am4core.options.nonce in other locales such as am4lang_ko_KR, am4lang_ja_JP, am4lang_fr_FR and am4lang_en it works fine, but with am4lang_zh_Hans it is not applying my nonce and therefore breaches my applications CSP

I set:
am4core.options.nonce = "{{ csp_nonce() }}";

Where {{ csp_nonce() }} injects a nonce for the request

When I then include:
<script src="//www.amcharts.com/lib/4/lang/zh_Hans.js" defer></script>
The following abridged exception is thrown:

Refused to load the script 'https://www.amcharts.com/lib/4/lang/zh_Hans.js' because it violates the following Content Security Policy directive: "script-src 'nonce-XXXXXXXXXXXXXXXXXXXXXXXX'

And therefore when I set:
am4core.options.defaultLocale = "am4lang_zh_Hans"
It throws the following additional exception:

Uncaught ReferenceError: am4lang_zh_Hans is not defined

**Environment (if applicable)**

 - amCharts version: 4.10.23
 - Browser and its version: Chrome 100.0.4896.75
 - Related frameworks and their versions: Using vanilla JS and ES6

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by TomBertie** [comment]
Sorry, ignore my issue.  It was an error in the CSP which was excluding the Chinese language pack.
