### ISSUE TITLE
Axis Range with LineSeries

### ISSUE THREAD

**Issue by abhinv01** [amcharts/amcharts4#4045]
Hi, I am trying LineSeries with range and for dataset which has certain value continuously, it shows stroke with both the colors.
In my example for value 0 line drawn has both red and blue color.

It should only show red colour.

![Screenshot 2022-04-11 191603](https://user-images.githubusercontent.com/79756970/162753387-fbf15876-9075-499c-9292-048ac1da8a8b.png)

codepen link: https://codepen.io/Abhinav01/pen/JjMBYwQ

**Comment by abhinv01** [comment]
@zeroin  What if the data set is like this, with `range.value` exists on numerous occasion, is this fixable with two series, if yes how?

![image](https://user-images.githubusercontent.com/79756970/162911068-02b6966d-e601-4ebb-a9e9-e9c80c18657d.png)

codepen link: https://codepen.io/Abhinav01/pen/JjMBYwQ

**Comment by zeroin** [comment]
I am afraid I don't see a way to solve this.
