### ISSUE TITLE
Highlight a cell of a TreeMap on click

### ISSUE THREAD

**Issue by Lupici** [amcharts/amcharts4#4046]
Hi all,
I have a simple Treemap. I have a click event that return me the value of the cell clicked
How to highlight the cell chosen (for example with a border on the cell) when I click the cell?

this is the code I use to select a cell:

`var series = this.chart.seriesTemplates.create("0");`

`series.columns.template.events.on('hit', function(ev) {`

 `     console.log(ev.target.dataItem.dataContext.dataContext.name);`
		
`});`

Thanks to all!

**Comment by zeroin** [comment]
Modified the pen to do so:
https://codepen.io/team/amcharts/pen/NWXLaKL
