### ISSUE TITLE
How to show multiple tooltips on scatter chart with CategoryAxis

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#4049]
Is it possible to show a tooltip when multiple values exist on the same category?

As you can see on the screenshot below, when I hover over a data point it always shows the tooltip for the top item:
![image](https://user-images.githubusercontent.com/2857604/163136759-cd9d4899-74ff-4a6d-b712-e24cdc4d9638.png)

I've created a CodePen below that highlights the issue.

**CodePen**
https://codepen.io/jbate/pen/MWrqOab?editors=0010

I was reading [this tutorial](https://www.amcharts.com/docs/v4/tutorials/multiple-cursor-tooltips-on-scatter-chart/) and understand how to solve it when the X-axis is a ValueAxis but not when it's a CategoryAxis.

Any insights would be appreciated!

**Comment by zeroin** [comment]
No, unless you add a separate series for the duplicates.

**Comment by zeroin** [comment]
I am afraid I don't see a different solution.

**Comment by jbate** [comment]
Ok, thanks anyway. So as I see it, perhaps this isn't the best chart type for that data. The user should possibly choose a different chart?
