### ISSUE TITLE
Make DateAxis TimeFormat consistent for all values

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4050]
**Question**
For date axis, when the period changes, the date format is not consistent
How can I make it consistent ? 

<img width="364" alt="image" src="https://user-images.githubusercontent.com/10185101/163391457-ce71214c-8406-488f-b713-30c07a7483bc.png">
Here since the month changes from March to April, the date format changed from YYYY/MM/DD to MMM DD

I want this also to be in YYYY/MM/DD format
How can I achieve this ?

**Environment (if applicable)**
 - amCharts version : 4.10.10

**Additional context**

**Comment by xorspark** [comment]
You also need to set the `periodChangeDateFormats` to adjust those labels.

More info here: https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Period_change_format

**Comment by azharakbar** [comment]
Thank you @xorspark
