### ISSUE TITLE
Map chart is not having geoData for taiwan(taiwanLow, taiwanHigh)

### ISSUE THREAD

**Issue by anandtripathi5** [amcharts/amcharts4#4051]
**Bug description**

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
It does:
https://cdn.amcharts.com/lib/4/geodata/taiwanLow.js

Map:
https://codepen.io/team/amcharts/pen/PoEyXVp/b1a7de3dc00322a46676509c85049c27

**Comment by anandtripathi5** [comment]
I can see now its added. Thanks
