### ISSUE TITLE
Remove Arrow from Tooltip. Is this possible?

### ISSUE THREAD

**Issue by RT404** [amcharts/amcharts4#4053]
Is it possible to remove or hide the arrow/connector/point in a Tooltip?

I've not found any info on this at present. We're looking to remove the arrow on a yAxis point.

Thanks very much for your help.

_Using Angular/TS / AmCharts 4_

**Comment by xorspark** [comment]
You can set the [`pointerLength`](https://www.amcharts.com/docs/v4/reference/pointedrectangle/#pointerLength_property) on the tooltip's background object to zero to remove the pointer.

```
axis.tooltip.background.pointerLength = 0;
```

**Comment by RT404** [comment]
> You can set the [`pointerLength`](https://www.amcharts.com/docs/v4/reference/pointedrectangle/#pointerLength_property) on the tooltip's background object to zero to remove the pointer.
> 
> ```
> axis.tooltip.background.pointerLength = 0;
> ```

Thank you Sir! This fixes our issue, thanks again!
