### ISSUE TITLE
How do i shrink the size of bar chart

### ISSUE THREAD

**Issue by xzhenghao** [amcharts/amcharts4#4054]
How do i shrink the size of bar chart, the valueAxes and increase the height of the chart so the values can be displayed at the top of the chart

![image](https://user-images.githubusercontent.com/4718721/165486237-6df07533-3feb-4c94-b853-2080c785f5a5.png)

**Comment by zeroin** [comment]
You could set extraMax of ValueAxis to some value like 0.1 or 0.2. This will give more space at the top.

**Comment by xzhenghao** [comment]
Hi,

Do i set it in the "valueAxes" portion, tried it but its not working.

![image](https://user-images.githubusercontent.com/4718721/165651551-2c1a5966-4332-469f-888e-63c4cc72e669.png)

**Comment by martynasma** [comment]
Are you using amCharts 3? This is a repo for amCharts 4. And amCharts 3 is no longer supported, I'm afraid.
