### ISSUE TITLE
Export data browser error when using Google Analytics v4 script

### ISSUE THREAD

**Issue by EddyRespondek** [amcharts/amcharts4#4055]
**Question**

Got a bit of a weird issue with exporting chart data and Google Analytics v4. Sorry for the lack of information to go on. I just wanted to confirm this was happening to anyone else.

A client of ours has updated to the new v4 embed script for Google Analytics with all "Enhanced measurements" enabled. One of these measurements "Outbound clicks" when enabled causes a error in Google Chrome when trying to export data from a chart (tested on CSV and all image export options). In Firefox it simply doesn't download anything at all. No JS errors are recorded.

![ga4-blob-error](https://user-images.githubusercontent.com/136681/165651653-36340592-a9b1-4b8b-931b-9b1573383ea8.jpg)

I have submitted the issue with Google but I'm not betting on a solution anytime soon. So I'm just wondering if this has happened to anyone else and if they ever found a workaround?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
