### ISSUE TITLE
Collapsible Force-Directed Tree skipping color from color set array

### ISSUE THREAD

**Issue by Komald** [amcharts/amcharts4#4056]
**Bug description**

The Collapsible Force-Directed Tree is automatically stepping 2 when applying colors of different networkSeries. We've created am2core color set array and assigned that to networkSeries.colors.list, it's applying color from 0th index, then 2nd index then 4th index and so on..
It's skipping every alternat color from array. 

CodePen link here:
https://codepen.io/nilesh842/pen/xxYKpVm?editors=0010

**Additional context**
Here you  can see every alternat color is getting pick for different bubbles and then last color is applied to last 3 bubbles.

**Comment by martynasma** [comment]
You can force 1 color per step:

```JavaScript
networkSeries.colors.step = 1;
```
