### ISSUE TITLE
How get access to yAxis, series, axisBreak from legend event toggled

### ISSUE THREAD

**Issue by d1skonekt** [amcharts/amcharts4#4057]
**Question**

How get access to yAxis, series, axisBreak from legend event toggled?
(important point chart created just with using json and with method createFromConfig) 

[bar example ](https://codepen.io/Konstantin-Savvin/pen/rNJBZKQ)

```
legend: {
    itemContainers: {
      template: {
        events: {
          toggled: (event) => {
           const yAxes = event?.
           const series = event?.
           const axisBreak  = yAxes?.
          },
        },
      },
    },
  },
```

**Comment by xorspark** [comment]
The series is in the event target's dataItem.dataContext property. The series contains a reference to its y axis in the `yAxis` property, and the `axisBreaks` list template can be directly accessed from the y axis.

```
legend: {
    itemContainers: {
      template: {
        events: {
          toggled: (event) => {
           const series = event.target.dataItem.dataContext;
           const yAxes = series.yAxis;
           const axisBreak  = yAxes.axisBreaks;
          },
        },
      },
    },
  },

**Comment by d1skonekt** [comment]
Yup it's work if legend default. If I'm using custom data for legend logic is different but the idea understand. 
Maybe someone can help with other questions with the collapsed chart after toggle custom legend (or I need to create another question)? 
[my chart ](https://codepen.io/Konstantin-Savvin/pen/BawLpma)
what i'm must added in toggle event for collapsed  part chart that im hidden ? for the chart to behave like in [Demo amchart4](https://www.amcharts.com/demos-v4/partitioned-bar-chart-v4/)

**Comment by xorspark** [comment]
Specifying custom data items changes the situation a bit.

To access the series and y axis  in this case, you can access the chart object itself through the event target's `baseSprite` property and reference the series and y axis directly from it:

```
legend: {
    itemContainers: {
      template: {
        events: {
          toggled: (event) => {
            const chart = event.target.baseSprite; 
            const series = chart.series.getIndex(0);
            const yAxis = chart.yAxes.getIndex(0);
            // ...
          },
        },
      },
    },
  },
