### ISSUE TITLE
Force Directed Tree node click

### ISSUE THREAD

**Issue by vnandyal** [amcharts/amcharts4#4059]
When a node is clicked on a Force Directed Tree, can it open another  Force Directed Tree ? 
I am trying to open a new force directed tree which contains a subset of data from the tree where the node was clicked.  The data subset shows up in the new tree. However, subsequent node clicks in this new tree (to create further new trees or refresh the existing one), freezes the screen. The error usually is a null or undefined data exception in the following code :

 chartRef.current.events.disableType("hit");
                setTimeout(() => {
                    chartRef.current.events.enableType("hit");
                }, 100); 

![image](https://user-images.githubusercontent.com/98782601/166292917-c0332bcf-837f-4925-a25a-ce1b798a6d50.png)

The chart containing the tree is being disposed.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by martynasma** [comment]
In such case, please contact us directly at contact@amcharts.com where we can discuss this privately.

**Comment by vnandyal** [comment]
Sure. Will do.
Thanks


From: Martynas Majeris ***@***.***>
Reply-To: amcharts/amcharts4 ***@***.***>
Date: Wednesday, May 4, 2022 at 11:29 PM
To: amcharts/amcharts4 ***@***.***>
Cc: Vydehi Nandyal ***@***.***>, Author ***@***.***>
Subject: Re: [amcharts/amcharts4] Force Directed Tree node click (Issue #4059)


In such case, please contact us directly at ***@***.******@***.***> where we can discuss this privately.
