### ISSUE TITLE
hard to get item data that matched series

### ISSUE THREAD

**Issue by Andromeda-Main-Line** [amcharts/amcharts4#4060]
using lib : amchart 5

Hello,

I'm trying to get matched item data when I click a series, and make another chart based on that item.

I read homepage amchart 5 documentation already.

They show me about getting event.target object data.

But, too hard to find where the actual selected item is.

My company considering about buying additional license for project.

But they require function what I asked.

If you could, please help me to solve this problem.

**Comment by martynasma** [comment]
This is a repo for amCharts 4. Please use correct repo for amCharts 5:
https://github.com/amcharts/amcharts5
