### ISSUE TITLE
Axis scale (scrollbar zoom) does not update when working with multiple vertical axes

### ISSUE THREAD

**Issue by vonsa** [amcharts/amcharts4#4063]
Hi!

I'm experiencing an issue when using multiples verticle axes together with a scrollbar.

When using a single axis, the scrollbar works as expected:
1. I call series.hide() on the series linked to the secondary vertical axis.
2. Zoom level adjusts to fit the scale

When using 2 vertical axes, it behaves unexpected:
1. I call series.hide() on the series linked to the secondary vertical axis.
2. Axis scale flickers, it seems to adjust and then revert the scrollbar end value to 1.

I have prepared 2 examples for reference, I've applied a timeout of 4 seconds to programmatically hide the series:
1 axis (expected behavior): https://codepen.io/Vonsa/pen/YzeqmbY
2 axes (unexpected behavior): https://codepen.io/Vonsa/pen/QWQNemz

Is it possible for me to use multiple axes while still adjusting the scale properly when hiding one of the series?

All the best,

Coen

**Comment by zeroin** [comment]
Vertical scrollbar and multiple y axes are a no-go, unless both x and y axes are Value axes. But the scale of the y axes in this case won't be updated anyway.

**Comment by vonsa** [comment]
Thanks for clarifying this zeroin.

A multiple y value axes chart currently does scale up correctly (i.e. highest item is 100, max scale value is around that same number. Add an item with value 1000 and the max scale value adjusts appropriately to around 1000), is there any workaround that comes to mind to have it scale down as well when you remove the value 1000 item?

**Comment by zeroin** [comment]
Could you create a codepen? I tried your described scenario and the scale is adjusted:
https://codepen.io/team/amcharts/pen/qBxrErJ/286f3b2c2a2fe6ad90db0899e7229d1e

**Comment by vonsa** [comment]
Hi zeroin,

Thanks for trying to reproduce this.

You can for instance look at the second example I sent in my previous message (https://codepen.io/Vonsa/pen/QWQNemz), it removes the 5000 value for the left axis and you would expect the left vertical axis to scale down to value 600. Also note the scale flickering the moment the high value line dissapears.

I do notice in both of our examples that it will only work with the animation theme. Is it supposed to be this way?

**Comment by zeroin** [comment]
I'm afraid investigations into specific chart setups fall out of scope of our free support here. If you do have a support subscription (amPlus), please contact us at [contact@amcharts.com](mailto:contact@amcharts.com).

**Comment by vonsa** [comment]
Ok thanks for your assistance thusfar
