### ISSUE TITLE
Trying to show Totals in a toolTips within a Stacked Chart with JSON

### ISSUE THREAD

**Issue by zubalea** [amcharts/amcharts4#4066]
I am trying to recreate this example exactly, but with a json config.
https://codepen.io/team/amcharts/pen/WBrWGe

I can't figure out how to write this part in a json config.

```
/* Decorate axis tooltip content */
categoryAxis2.adapter.add("getTooltipText", (text) => {
  var totalValue = 0;
  chart.series.each(function(series) {
    totalValue += series.tooltipDataItem.valueY;
  });
 return "Total: " + chart.numberFormatter.format(totalValue);
});
```

**Comment by martynasma** [comment]
Please refer to this doc which explains how to add adapters in JSON config:

https://www.amcharts.com/docs/v4/concepts/json-config/#Adapters

**Comment by zubalea** [comment]
Thank you
