### ISSUE TITLE
Upside down a tree chart

### ISSUE THREAD

**Issue by san3jaya** [amcharts/amcharts4#4069]
I need to change the orientation of the tree chart like completely upside down as I attached. but there is only 2 config in this tree chart horizontal and vertical. I need to get the root node to the bottom and the other node to grow upside.
![Untitled](https://user-images.githubusercontent.com/8122779/168407662-a2b8c8d3-40e3-49ac-92ea-1f9949d56f02.jpg)

**Comment by martynasma** [comment]
It's not yet possible, I'm afraid.

We'll investigate if this can be easily added, and will let you know here.

**Comment by martynasma** [comment]
This is a repo for amCharts 4. Please use proper repo for [amCharts 5 requests](https://github.com/amcharts/amcharts5/issues).
