### ISSUE TITLE
core.js:1 Uncaught Error: EventDispatcher is disposed

### ISSUE THREAD

**Issue by ChellappanRajan** [amcharts/amcharts4#4071]
**Bug description**
In multi axis chart disposing all previous value axis and adding new value axis to an chart cause Uncaught Error: EventDispatcher is disposed

   [Reproducible Codepen](https://codepen.io/chellappanrajan/pen/ExQZRbx)

**Comment by martynasma** [comment]
In your CodePen you dispose axis, but you leave series that are using it intact. You should either dispose the series as well, or assign them new axes.

**Comment by ChellappanRajan** [comment]
Thanks for the answer.

**Comment by ChellappanRajan** [comment]
Hi @martynasma Do you have any work around for this issue, please let me know?

**Comment by martynasma** [comment]
As I mentioned in one of my previous replies: you need to dispose not only axes but also series that are using them.

**Comment by ChellappanRajan** [comment]
> As I mentioned in one of my previous replies: you need to dispose not only axes but also series that are using them.

I have tried as you suggested, Removed axes and series still getting same error, please check:https://codepen.io/chellappanrajan/pen/ExQZRbx

**Comment by martynasma** [comment]
Almost there :)

Just need to remove series before removing axes:

```JavaScript
seriess.forEach((ser)=>ser.dispose());
valueAxiss.forEach(res=>res.dispose());
```

**Comment by ChellappanRajan** [comment]
Thank you so much!
