### ISSUE TITLE
How to avoid extra decimal symbols in the Sankey's nodes values?

### ISSUE THREAD

**Issue by OGudkov-TechHub** [amcharts/amcharts4#4073]
Hello,

In our project we are using the Sankey diagram. The values for it are provided as the fractional numbers with different number of decimal symbols, from 1 to 5 (it depends on an actual value). The thing is, that from time to time, depending on the values, a node's totalOutgoing value shows extra decimal symbols, like in the screen below:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/28897173/168813604-525d0709-1e77-4481-b661-7314213796b6.png">

There is a requirement, that the totalOutgoing should display an exact sum of outgoing values, so the decimal symbols count is not fixed to a specific number. For example, the values 1.1, 2.22 and 3.333 sum is 6.653, while sum for 1.1 and 2.22 is 3.32.

What might be a solution for this issue? Seems a possible solution might be to apply a custom calculation of the totalOutgoing property, with respect of the values precision, but in a totalOutgoing custom adapter, which I tried to use, totalOutgoing came calculated already. Or maybe there is an another approach which I'm not aware of?

Here is the CodePen link: https://codepen.io/oleggood/pen/VwQpeNZ. It's clearly seen there, that the highest precision is 4 decimal symbols.

The Sunburst diagram has got the same problem. I've solved it with sort of a crutch, and, potentially, can invent something similar here, but it doesn't look as a good approach to me. Especially because your library is highly configurable and developer can potentially reach most of the properties and customize them as he wants to.

Thank you in advance!

**Comment by zeroin** [comment]
This happens because of the floating point error. In case you are sure that there can't be more than 11 fractional numbers, you can simply round the number:

`result += "\n"+am4core.math.round(target.totalOutgoing, 11);`

**Comment by OGudkov-TechHub** [comment]
@zeroin, thank you! Seems work correctly!

I know, why it does happen, but wasn't aware about the round() function. Looks like the amCharts 4 docs hasn't got it; I'm looking here: https://www.amcharts.com/docs/v4/reference/math_module/.
Interesting, that amCharts 5 docs has got the definition of that function, but it's description isn't really correct from my point of view:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/28897173/169018138-e6ac7d4b-b330-4c8c-85f1-ab8e3430ac4c.png">
Date? Specific time unit?

**Comment by zeroin** [comment]
Thanks, we will fix that.
