### ISSUE TITLE
Is there any way to color the each candle in the candlestick series with multiple colors?

### ISSUE THREAD

**Issue by lakshmisivakrupa** [amcharts/amcharts4#4074]
![image](https://user-images.githubusercontent.com/28670867/168990827-396bb9ca-c8d4-4412-b5ed-cd8219b7d32d.png)
In my project I need to color the candles in the candlestick series with multiple colors based on the value axis range.
I know there is axisRange option in amcharts4 ,but that will apply the same color to all candles in the series.I would like to color each candle (based on category axis value)  with multiple colors (as shown in the picture above).
Is there any way to do this in amcharts4?

**Comment by zeroin** [comment]
The only solution I see here would be to add another column series on top of the candlesticks, and color them in a way you want.

**Comment by lakshmisivakrupa** [comment]
> The only solution I see here would be to add another column series on top of the candlesticks, and color them in a way you want.

That helped.Thank you.
