### ISSUE TITLE
Pie chart : How to make legends(or group slices using one legend) represent multiple slices?

### ISSUE THREAD

**Issue by nithincs20** [amcharts/amcharts4#4077]
**Question**

Is there a way to group different slices together by legends in Pie chart? If you see the screenshot,
I need to represent slices 'Ship to Home', 'Ship to Store' with a single legend 'Store', as well as the other slices with 'eCom'. Is there a way I can achieve this?
(I am able to give the colours for diff. slices)

<img width="593" alt="Screenshot 2022-05-24 at 10 57 04 AM" src="https://user-images.githubusercontent.com/59362183/169961317-12b1445e-08d4-47da-9d0b-fc5608128c7d.png"> 

**Environment (if applicable)**

- @amcharts/amcharts4/charts
- Chrome, Version 101.0.4951.64 

**Additional context**

**Comment by YashGupta001** [comment]
Can we get any update team?
