### ISSUE TITLE
[date-axis] :: Last date value disappears when Scrollbar moved to the extreme right

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4078]
**Bug description**
I have a date axis in my chart and also Scrollbar on X-Axis
The last date on the date-axis disappears when the scrollbar is moved to the extreme right

This was observed after I made the configuration change to the dateAxis
```js
dateAxis.skipEmptyPeriods = true;
```

My full code snippet to create date-axis is as follows
```js
export const createDateAxis = (chart, dateFormat) => {
	const finalDateFormat = dateFormat ?? DEFAULT_DATE_FORMAT;
	const dateAxis = chart.xAxes.push(new am4charts.DateAxis());
	dateAxis.renderer.minGridDistance = 60;
	dateAxis.renderer.grid.template.disabled = true;
	dateAxis.renderer.grid.template.location = 0;
	dateAxis.renderer.maxLabelPosition = 0.99;
	dateAxis.renderer.labels.template.fill = am4core.color(CHART_COLORS.label);
	["day", "week", "month", "year"].forEach(function (key) {
		dateAxis.dateFormats.setKey(key, finalDateFormat);
		dateAxis.periodChangeDateFormats.setKey(key, finalDateFormat);
	});
	dateAxis.skipEmptyPeriods = true; // this caused the below attached screenshot behaviour

	return dateAxis;
};
```

<img width="854" alt="image" src="https://user-images.githubusercontent.com/10185101/170121709-73610b43-4b24-4490-a7df-5a3ddb2b6809.png">

Still there is some space on the x-scrollbar left to be moved to the right
Once I move it to the extreme right, then following happens
<img width="824" alt="image" src="https://user-images.githubusercontent.com/10185101/170121867-10a5b1b0-57c2-445f-8401-d674f56dc7e6.png">

**Environment (if applicable)**

**Additional context**

**Comment by azharakbar** [comment]
If i remove this configuration
```js
dateAxis.skipEmptyPeriods = true;
```

Then this is the result
<img width="837" alt="image" src="https://user-images.githubusercontent.com/10185101/170122245-f60dd55a-9567-4d75-a3ca-3fa2b48408ba.png">

The configuration is added as part of the solution raised in #4067

**Comment by martynasma** [comment]
If you do have an amPlus (support) subscription, can you reach out to us directly at contact@amcharts.com? We'll need some more code and data to reproduce this and work it out.

Also, I would consider moving to amCharts 5. Its GaplessDateAxis is very flexible and reliable.
