### ISSUE TITLE
Is it possible to change only the size of the ranges in the gauge with bands?

### ISSUE THREAD

**Issue by OvidiuBan** [amcharts/amcharts4#4079]
Hello!

https://www.amcharts.com/demos-v4/gauge-with-bands-v4/ on this example, is it somehow possible to only resize how big the ranges are? to make them bigger or smaller compared to the chart?

**Comment by martynasma** [comment]
Yes, you can control width of the bands using charts' `innerRadius`:

```
chart.innerRadius = am4core.percent(70);
```

**Comment by OvidiuBan** [comment]
thank you!
