### ISSUE TITLE
angular6 slow build

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#408]
Hi,

after adding amchart4 i noticed that the time to build/compile angular increased of 10x 
also there are a lot of files generated that i am not 100% sure what are and that i am pretty sure i don't use

pdfmake to name one, i don't have any kind of export for my chart, so i don't need that i suppose. it's not possible to disable that to avoid generating useless things?

**Comment by martynasma** [comment]
We're experimenting with various settings and webpack versions, so that reduce compile time.

If there is a significant progress, we'll make sure to let you know here.
