### ISSUE TITLE
[date-axis] :: Start date getting displaced to the beginning of the chart and not in sync with tooltip/cursor position

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4080]
**Bug description**
<img width="720" alt="image" src="https://user-images.githubusercontent.com/10185101/170953968-31b1caef-5c5b-4fdc-8a27-14cf4dd493dd.png">

How can I fix this displacement ?

<img width="860" alt="image" src="https://user-images.githubusercontent.com/10185101/170954059-5d32c631-5a01-43cf-86da-9a4281411410.png">
And also, here, the date 2022/05/21 is not present in the dataset passed to the chart and I also have the configuration to `skipEmptyPeriods = true`, still, the date is being displayed on the axis

Pls help me to fix these issues

**Environment (if applicable)**
 - amCharts version: `4.10.25`
 

**Additional context**

**Comment by martynasma** [comment]
> Why does the date which is not present in the dataSet getting rendered on the date axis

Because `DateAxis` has own scale. It does not correlate with dates 1:1 in data. It just displays own scale, then lays out data items where appropriate within the scale.

If you need 1:1 axis labels with data, you should use `CategoryAxis`.

**Comment by azharakbar** [comment]
Ok, thanks
