### ISSUE TITLE
Multiple axis with more than 1000 data causes UI to freeze

### ISSUE THREAD

**Issue by ChellappanRajan** [amcharts/amcharts4#4081]
Hi
   When we have a multi axis chart with more than 1000 data. It freezes the browser for sometime. How can we improve this time?

[Example Codepen](https://codepen.io/chellappanrajan/pen/oNEEKmg)

**Comment by zeroin** [comment]
I would recommend to switch to v5, it's a lot faster comparing to v4.

**Comment by ChellappanRajan** [comment]
Any alternative without changing version?

**Comment by zeroin** [comment]
I am afraid no.
