### ISSUE TITLE
How can I create a vertical line on year change in Trend charts ?

### ISSUE THREAD

**Issue by abhiseksubham** [amcharts/amcharts4#4082]
I want to create a vertical line when the year changes from 2012 to 2013 in AMCharts trend chart .

https://codepen.io/Abhiseksubham/pen/poaVegN

Something like this :

![Screenshot 2022-06-01 at 4 14 57 PM](https://user-images.githubusercontent.com/2356647/171388626-62cbfaad-e4d8-4179-ad46-7f94a5b5c3d7.png)

How can I achieve this in Amcharts4 ?

**Comment by martynasma** [comment]
You can use an axis range to place vertical lines and labels on any date:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides

**Comment by abhiseksubham** [comment]
Ok I saw the documents , We need to create a Range on category Axis on a particular date. 
We also found this codepen https://codepen.io/Abhiseksubham/pen/XWEGOZR, 
but the examples are for every date.

Could you please help us to create a range for a given particular date.
