### ISSUE TITLE
[tooltip] :: Tooltips getting overlapped

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4086]
**Question**
Axis tooltip and series tooltip is getting overlapped
<img width="509" alt="image" src="https://user-images.githubusercontent.com/10185101/172057484-1f9c152b-525a-45fc-9d93-be6d650db613.png">

How can we fix this ?

**Environment (if applicable)**

**Additional context**

**Comment by zeroin** [comment]
The only way to solve this would be to set direction to 'left' or 'vertical` for the series tooltip.
