### ISSUE TITLE
Set the background color of inner gauge

### ISSUE THREAD

**Issue by OvidiuBan** [amcharts/amcharts4#4087]
Hello! Is it possible to only set the color background inside the gauge?

![image](https://user-images.githubusercontent.com/11694812/172145653-2f6f5247-b492-400d-9546-d4454959ad05.png)

At the moment it seems to affect the entire chart.

**Comment by martynasma** [comment]
Maybe just add another range?

```JavaScript
var range = axis2.axisRanges.create();
range.axisFill.fill = am4core.color(am4core.color("#00ff00"));
range.axisFill.fillOpacity = 0.8;
range.axisFill.zIndex = -1;
range.value = chartMin;
range.endValue = chartMax;
range.grid.strokeOpacity = 0;
range.axisFill.radius = am4core.percent(80);
range.axisFill.innerRadius = 0;
```

https://codepen.io/team/amcharts/pen/eYVjbjg/361e55ad237292fe3f9faa06b0a2c137?editors=0010

**Comment by martynasma** [comment]
It's just about place of the fill range in code. It has to go before any other ranges. I updated the CodePen above.
