### ISSUE TITLE
How to modify the color of amcharts legend text？

### ISSUE THREAD

**Issue by 15602322852** [amcharts/amcharts4#4088]

**Comment by xorspark** [comment]
You can modify the `fill` on the `label` and `valueLabel` on the legend template as [documented here](https://www.amcharts.com/docs/v4/concepts/legend/#Basic_styling_options)

```
chart.legend.labels.template.fill = "#ff0000";
chart.legend.valueLabels.template.fill = "#0000ff";
```

If you need different colors for each legend item, you can use a [propertyField](https://www.amcharts.com/docs/v4/concepts/data/#Property_fields) on the `fill` as demonstrated [here](https://codepen.io/team/amcharts/pen/mdXwzXy/6c3183729fadf8490925812e925d9424?editors=0010)

```
chart.legend.labels.template.propertyField.fill = "propertyInDataContainingYourColor";
```

**Comment by 15602322852** [comment]
How to change the color of the pie chart pointing line？ thanks

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
