### ISSUE TITLE
Is it possible to stop the position from changing when date axis min/max changes?

### ISSUE THREAD

**Issue by Logikgate** [amcharts/amcharts4#4089]
**Question**

When the min or max of a date axis changes is it possible to stop the current zoom level and position from changing? Below is a codepen that shows what I am trying to avoid, 3 seconds after the load it changes the max of the date axis and you can see that the zoom level and position jump. Is there a way to avoid this?

https://codepen.io/logikgate/pen/YzeJZbL

**Environment (if applicable)**

**Additional context**

**Comment by xorspark** [comment]
You can store the axis' current zoom level (`minZoomed` and `maxZoomed`) and reset the zoom after the `datarangedchanged` fires from the min/max change:

```
setTimeout(() => {
  let oldStart = dateAxis.minZoomed;
  let oldEnd = dateAxis.maxZoomed;
  dateAxis.events.once('datarangechanged', () => {
      dateAxis.zoomToDates(new Date(oldStart), new Date(oldEnd), false, true);
  });
  dateAxis.max = 1654722574780;
}, 3000)
```

**Comment by Logikgate** [comment]
Thanks @xorspark I have done that but the chart still flickers when the change happens. I was hoping there would be something built in that would make the update seamless

**Comment by xorspark** [comment]
I'm afraid there isn't any built-in solution for this nor a way to prevent the flicker with the workaround I provided. Sorry.
