### ISSUE TITLE
Displaying label bullets at a given position

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#409]
Hi,

While rendering a chart, only certain labels will be displayed depending on the available width.
Is there any provision to show label bullets only at positions where the xaxis labels are displayed.

In the below link, only USA, japan, uk, india, netherlands, southkorea are displayed on the x-axis, but label bullets are displayed for all bars. So we wanted to display label bullets only at those positions.
Is there any way to achieve that.
https://codepen.io/varshamathukumalli/pen/JmjmZG?editors=0010

**Comment by Varshamathukumalli** [comment]
Hi,

Thanks for the solution. It helped.
How to change the label bullet position to above the bar or inside the bar etc.,

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/concepts/bullets/#Positioning_within_column

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
