### ISSUE TITLE
How do you fit the pie chart 

### ISSUE THREAD

**Issue by 15602322852** [amcharts/amcharts4#4094]
How do you fit the pie chart because when the window shrinks, the text gets obscured 。

**Comment by xorspark** [comment]
I'd recommend looking into our [responsive plugin](https://www.amcharts.com/docs/v4/concepts/responsive/) along with the tips from [this article](https://www.amcharts.com/docs/v4/tutorials/dealing-with-piechart-labels-that-dont-fit/). We have a [pie chart example](https://www.amcharts.com/docs/v4/concepts/responsive/#PieChart)  on the responsive plugin page that outright disables the labels, but you can tweak from there to adjust alignment or enable wrapping/truncating as desired.

**Comment by 15602322852** [comment]
Why does my modification not take effect

**Comment by 15602322852** [comment]
Can I set the indicator information in the graph

**Comment by xorspark** [comment]
Please post any questions that are not related to the original topic as a separate issue. Please also clarify what you mean by indicator information in your new thread. Thank you.
