### ISSUE TITLE
How to set indicator information in pie chart?

### ISSUE THREAD

**Issue by 15602322852** [amcharts/amcharts4#4095]

**Comment by xorspark** [comment]
Are you referring to the labels next to the slices? If so, see here: https://www.amcharts.com/docs/v4/chart-types/pie-chart/#Changing_slice_label_content

If that's not what you're referring to, can you please clarify?

**Comment by 15602322852** [comment]
The information that the pie chart points to, I want to set in the corresponding block of the pie chart

**Comment by xorspark** [comment]
We don't support yaml. We have samples in JS, Typescript/ES6 and JSON.
