### ISSUE TITLE
Dynamically set column opacity when data is updated

### ISSUE THREAD

**Issue by geoffreyrichey** [amcharts/amcharts4#4099]
I have a ColumnSeries chart where I'm using an adapter to set the fill opacity based on the data value i.e..

```
chart.series.columns.template.adapter.add('fillOpacity', (value, target, key) => {
    return target.dataItem.valueY / 100
})
```

This works as expected on initial render. When my chart data is updated, however, the fillOpacity does not update based on the new value. i.e..
```
// Example data update
chart.data[0].value = chart.data[0].value + 10

// Animates the value change for the column
chart.invalidateRawData()

// Tried the following but no luck getting the fill opacity to update based on the new dataItem value
chart.series.columns.template.adapter.apply('fillOpacity')
chart.series.invalidate()
```

AmCharts version 4.10.22

**Comment by zeroin** [comment]
The adapter is simply not called, as the fillOpacity doesn't change. So one way would be to loop through all the columns and do something like that:

`column.fillOpacity = column.fillOpacity`. 

Another way would be to add adapter for some property which is always called, like "x", return the same value as it is passed, but set fillOpacity somewhere before the return. 

If this won't help, it would be best if you could create a codepen of your case so I could modify it.

**Comment by geoffreyrichey** [comment]
Gotcha, that makes sense. I misunderstood how the adapters work. Looping through the columns when the data is changed and setting the fillOpacity worked for me.

Thanks for the help!
