### ISSUE TITLE
Combine tooltips of multiple series

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#410]
I have a chart with multiple series, each with its own data.
Is it possible to combine the tooltips of these series into a single tooltip, displaying the value of each series, visually distinguished with the series color?

**Comment by martynasma** [comment]
This tutorial is technically about HTML, but it has examples on how to combine stuff into single tooltip:

https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/

**Comment by Chnoch** [comment]
Thanks for pointing it out, I have already seen this tutorial. My issue is that we have a dynamic amount of series, each with their own data source and not everything nicely wrapped in a single object with different properties for each series. I'm not quite sure how I would go about displaying a consolidated tooltip in that case. Do you think I'd need to fully merge the data sources ahead of passing them to amcharts?

**Comment by martynasma** [comment]
In this case, I'd probably use an adapter for `tooltipText`. It could dynamically generate a text for all available series.

```
series.adapter.add("tooltipText", function(text, target) {
  // generate text dynamically
  // ...
  return text;
});
```

**Comment by Chnoch** [comment]
Thanks, I'll try it out and see how it goes. I'll close this ticket for now.
