### ISSUE TITLE
How to place line arrow on the boundaries of image marker ?

### ISSUE THREAD

**Issue by adarsh-technocrat** [amcharts/amcharts4#4100]
**Hello Everyone is there any way to place the arrow on the boundaries of the image marker!**

![Screenshot 2022-06-18 141737](https://user-images.githubusercontent.com/47661086/174430289-7bfbe092-8194-4cd3-a3a6-32d1714662cd.png)

![Screenshot 2022-06-18 141817](https://user-images.githubusercontent.com/47661086/174430290-d32e773a-64f5-40a7-b230-5a035d6e423c.png)

Cc: @martynasma 

Thanks in advance :)

**Comment by zeroin** [comment]
Unfortunately I don't see a way to do this. Well, you can set position to 0.95 or so for the arrow, like here:
https://codepen.io/team/amcharts/pen/GRQLYZq/bd31bc9e27b720aa5aca1cb1d9986cd4?editors=1010

But as it is relative position, it will depend on a length of the line, so wont' be exactly where you need them to be. But maybe setting it to 0.8 would be quite user friendly, as now you have arrows which overlap :)

**Comment by adarsh-technocrat** [comment]
> Unfortunately I don't see a way to do this. Well, you can set position to 0.95 or so for the arrow, like here:
> https://codepen.io/team/amcharts/pen/GRQLYZq/bd31bc9e27b720aa5aca1cb1d9986cd4?editors=1010
> 
> But as it is relative position, it will depend on a length of the line, so wont' be exactly where you need them to be. But maybe setting it to 0.8 would be quite user friendly, as now you have arrows which overlap :)

Thanks @zeroin :)
