### ISSUE TITLE
Unclear `invalidateRawData` behavior

### ISSUE THREAD

**Issue by SamueleDecarli** [amcharts/amcharts4#4102]
**Question**

The doc for `invalidateRawData` states
> If you want to have a smooth transition from one data values to another, you change your raw data and then you must call this method.
>
> then instead of redrawing everything, the chart will check raw data and smoothly transit from previous to new data
https://www.amcharts.com/docs/v4/reference/component/#invalidateRawData_method

We also have some information here:
> You can also manipulate and change data in data array.
>
> However, the chart itself won't detect such direct changes.
>
> To take in the changes, you will need to call chart's method `invalidateData()` or `invalidateRawData()`.
>
> Now, let's explain the difference between the two, seemingly similar functions that update the data.
>
> If we use `invalidateData()` the chart will re-evaluate all of the data. It will completely disregard current data set and treat the updated data as a new set of data. This will trigger chart redraw.
>
> `invalidateRawData()` is more subtle. It will assume that data items remain the same, with only their numeric values changed. This will not trigger complete re-parsing of data and redraw, but the chart will rather transition to new values of existing data items. Depending on whether you have animations enabled, this transition will be either instantaneous or will smoothly animate to new values.

https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points

What is not clear to me from the doc is how `invalidateRawData` should behave when a data field is assigned the value `null`.
The two code snippets below lead to what seems like inconsistent behavior

```typescript
declare var component: LineSeries;
 
component.data = [ { valueX: 0, valueY: null }];
// Let chart update, nothing appears as the value is null

component.data[0].valueY = 13;
component.invalidateRawData();

// Chart updates and the value appears

```
vs.

```typescript
declare var component: LineSeries;
 
component.data = [ { valueX: 0, valueY: 13 }];
// Let chart update, something appears

component.data[0].valueY = null;
component.invalidateRawData();

// Chart updates, but the value remains 13
``` 

Should the second code snippet also result in an updated to che chart?  If not, should the first one also not result in an updated chart?

Example pen: 
https://codepen.io/ASamNotAnother/pen/BaYeGLr

**Comment by martynasma** [comment]
I'm afraid `invalidateRawData()` does not work with `null` or missing values.

It can transition from one numeric value to another. If you have `null` coming in at the place where there was a value, and vice versa, the transition won't work.

In such case you need to revalidate the whole data set using `invalidateData()`.

**Comment by SamueleDecarli** [comment]
Thanks for the reply!

So I am to understand that the fact that this works:
```typescript
declare var component: LineSeries;
 
component.data = [ { valueX: 0, valueY: null }];
// Let chart update, nothing appears as the value is null

component.data[0].valueY = 13;
component.invalidateRawData();

// Chart updates and the value appears

```

https://codepen.io/ASamNotAnother/pen/BaYebNJ

Is actually an accident, not the intended behavior and should not be relied upon?

**Comment by jkieboom** [comment]
Could the documentation be improved to mention this more explicitly?
