### ISSUE TITLE
What's the correct way to rotate categories dynamically?

### ISSUE THREAD

**Issue by EtagiBI** [amcharts/amcharts4#4104]
Hello,

Let's assume that I have the following chart:
![изображение](https://user-images.githubusercontent.com/20855725/175282959-80b118aa-e02e-4dfa-b654-0a40af8d05b8.png)

As you can see, there're some missing categories on the category axis. AmCharts thinks that there's not enough horizontal space between categories to render them all. 
I tried to fix it by adjusting `minGridDistance`, but this led to text overlapping and vertcial mismatch of data and its categories:
![изображение](https://user-images.githubusercontent.com/20855725/175282877-6f55aafe-a69c-481a-8291-8bc326e40f6b.png)

Then I decided to implement a another approach when categories dynamically rotate according to container width. Alas, this led to jumping categories when using scrollbar:
![изображение](https://user-images.githubusercontent.com/20855725/175283859-84f29d61-fd18-408c-8d07-52ec7802f14b.png)

So what's the correct way to rotate categories dynamically? It seems that everything works fine without scrollbar, but gets messed up with scrollbar invoolved.

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v4/tutorials/wrapping-and-truncating-axis-labels/#Auto_rotating_labels

**Comment by EtagiBI** [comment]
> Take a look here: https://www.amcharts.com/docs/v4/tutorials/wrapping-and-truncating-axis-labels/#Auto_rotating_labels

I've tweaked this code a bit to make it similar to my actual code:
https://codepen.io/EtagiBI/pen/ZExEEyo

Here's what I get after a few seconds of playing with scrollbar and container size:

![изображение](https://user-images.githubusercontent.com/20855725/176093471-128464d2-2bd6-411b-b7c4-49f8fbeedb40.png)

Am I missing something in my code?

**Comment by martynasma** [comment]
I wouldn't set `wrap = true` on your labels.
