### ISSUE TITLE
How to make the bars in a chart fixed width instead of dynamic resizing ?

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4106]
![image](https://user-images.githubusercontent.com/10185101/176622463-dec089b9-3c42-4159-b744-51eb1bdc45aa.png)

How to always make the bars in charts 2 and 3 of fixed width equal to that we see in the chart 1 ?

I don't want to resize the bars according to the available width/height..

Is there a setting for fixedWidth that can be specified for the column series ?

**Comment by azharakbar** [comment]
@martynasma 
This seems to behave strangely with scrollbars ..
Is there is a maxHeight / maxWidth possible ?

**Comment by azharakbar** [comment]
![image](https://user-images.githubusercontent.com/10185101/177067411-058dbaf4-1482-4264-9aed-606b3276ec39.png)

this is the behoviour with 
```js
series.columns.template.height = 20;
```

**Comment by martynasma** [comment]
Well, in this case you can choose a smaller value for your column's `height`.

Or use `maxHeight`:

```JavaScript
series.columns.template.maxHeight = 20;
```
