### ISSUE TITLE
How to set the distance between text and left ?

### ISSUE THREAD

**Issue by 15602322852** [amcharts/amcharts4#4107]
How to set the distance between text and left ?
![image](https://user-images.githubusercontent.com/70054323/176845998-dfd1b6f0-4ef3-4fa7-bca7-bec9df9b4f83.png)

**Comment by martynasma** [comment]
There's no way to add specific distance between labels and chart edge. But you can reduce pie chart's radius, e.g.:

```
chart.radius = am4core.percent(70);
```
