### ISSUE TITLE
Creating pie chart with curved edges

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4108]
How can I create a chart with below styling ?

Can I do this by a Pie chart ?

If yes, How can I achieve the curved edges in the pie chart ?

![image](https://user-images.githubusercontent.com/10185101/177509448-de4ab624-5bd4-4460-b533-ac39bf221338.png)

**Comment by martynasma** [comment]
You can't do this with PieChart.

But you can do it with a RadarChart. Example:
https://www.amcharts.com/demos-v4/solid-gauge-v4/

Or same demo in amCharts 5:
https://www.amcharts.com/demos/solid-gauge/

P.S. You're posting in amCharts 4 repo, but I strongly suggest looking into amCharts 5 if you're not too invested in amCharts 4.
