### ISSUE TITLE
Does amchart support nested charts like XYChart inside another XYChart or similar

### ISSUE THREAD

**Issue by swapnilh-cognologix** [amcharts/amcharts4#4109]
**Question**

Hi,

I am trying to show Stacked XYChart inside another Stacked XYChart to full-fill our one of requirements.
is this possible with amchart version 4?

**Env details:**
amchart: 4x
angular: 14x

Thanks in advance!

**Comment by martynasma** [comment]
Well, you can nest charts. For example:
https://www.amcharts.com/demos-v4/pie-charts-as-bullets-v4/

It uses PieCharts inside an XYChart.

Do you perhaps have a mockup how you would like to nest two XYCharts?
