### ISSUE TITLE
How to remove the space between two heatmaps ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#4111]
Hi, I have two heat maps like in the below link
[https://codepen.io/vineelak/pen/NWvRMJx](url)

How to remove the space between two heatmaps ??

![A Pen by vineelak](https://user-images.githubusercontent.com/74599304/179908605-3787892e-f30c-4b43-af18-d39c9bf9c5bd.png)

want to remove space showing in above image.

**Comment by VineelaKantamneni** [comment]
Still getting the space (added padding top and bottom zero). Here is the code
[https://codepen.io/vineelak/pen/NWvRMJx](url)

**Comment by zeroin** [comment]
You should set it on chart, not on div:
https://codepen.io/team/amcharts/pen/BarRowy/f8529089d3cbe35e6785453c4381a7ed

**Comment by VineelaKantamneni** [comment]
It's working.
Thank you
