### ISSUE TITLE
If condition not working in template.adapter.add("fill", ())

### ISSUE THREAD

**Issue by acivita** [amcharts/amcharts4#4112]
Hello, I'm discovering Amcharts4 and I'm loving it !!

I usually fix my issues with the documentation/tutorial/stackOverflow but I couldn't find an answer so I'm trying here :).

I try to use an adapter for changing the color of a label, depending on certain properties.

For this example I want to change the color in red if the target has the verticalCenter property.
```
labelTemplate3.adapter.add("fill", function(fill, target) {

      let c1 = am4core.color("blue");
      let c2 = am4core.color("red");

      if (target._dataItem && target._dataItem._dataContext  && target._dataItem._dataContext.verticalCenter)
      {
        console.log("target._dataItem._dataContext.verticalCenter");
        return c2
      }
      else
        return c1
        
    })
```
The log inside is well printed but the color is still blue (c1), looks like it never return c2, and I can't understand why.

My data looks like : 
```
...
{
    "latitude": 48.856614,
    "longitude": 2.352222,
    "title": "Paris",
    "verticalCenter": "middle",
    "horizontalCenter": "right"
  },
...
```

The previous code is : 
```
var labelSeries3 = x.series.push(new am4maps.MapImageSeries());
    labelSeries3.data = tmpData
    labelSeries3.useGeodata = true;
    labelSeries3.calculateVisualCenter = true;
    var labelTemplate3 = labelSeries3.mapImages.template.createChild(am4core.Label);
    labelTemplate3.fontSize = 0.2;
    labelTemplate3.fontFamily =  "comic sans ms"
    labelTemplate3.interactionsEnabled = false;
    labelSeries3.events.on("inited", function () {
    labelSeries3.mapImages.each(function (item) {
        var label = labelSeries3.mapImages.create();
        label.latitude = item.dataItem.dataContext.latitude
        label.longitude = item.dataItem.dataContext.longitude
        label.children.getIndex(0).text = item.dataItem.dataContext.title;
      });
    }); 
```

Ty for your help, I hope is not a dumb mistake :D, if so I'm sorry.

**Comment by martynasma** [comment]
I don't understand your code:

```
labelSeries3.mapImages.each(function (item) {
   var label = labelSeries3.mapImages.create();
   // ...
});
```

You are iterating `mapImages` while creating new entries in `mapImages`? This does not make sense.

I'm not sure if this is related to original issue, but it jumps out at me.

If you could also post your working map in a CodePen, that would make it easier to figure this out.

**Comment by acivita** [comment]
Hello :).

Thank you for your quick response.

I made a codepen : 
https://codepen.io/acivita/pen/gOeWpqZ

I'm thinking about what you said and analysing my code right now.

**Comment by acivita** [comment]
hello its me again.

So thank you for helping i think i solved it.
My new codepen :
