### ISSUE TITLE
I don't understand the behaviour my horitonzalSpace in Label

### ISSUE THREAD

**Issue by acivita** [amcharts/amcharts4#4113]
``Hello :)

I'm trying to align some label close to a circle in my map.

I use the property horizontalSpace like that : 
```
label.adapter.add("horizontalCenter", function(fill, target) {
      if (target._dataItem._dataContext && target._dataItem._dataContext.horizontalCenter)
      {
        target.horizontalCenter = target._dataItem._dataContext.horizontalCenter;
        return target._dataItem._dataContext.horizontalCenter;
      }
  });
```
If I align  to keft, it works 👍 :

![github](https://user-images.githubusercontent.com/8580643/180193855-c968254a-a1d2-48be-9bf3-bdfa54742997.PNG)

But if I use right, some text have more spaces than other.

![github2](https://user-images.githubusercontent.com/8580643/180194911-3038d432-c9c9-47cb-8057-554f63fa417a.PNG)
Like Paris and Herstal.

I tried some variables change like : textAlign,wrap,truncat... but i can't find the solution, I'm sure I missed something.

Any clues to help me ?

There is my codepen if needed : https://codepen.io/acivita/pen/vYRmzgO

Thank you very much <3

**Comment by martynasma** [comment]
I don't see any dots or labels in your CodePen :) Perhaps you have posted wrong code?

**Comment by acivita** [comment]
> I don't see any dots or labels in your CodePen :) Perhaps you have posted wrong code?

Sorry its very small you need to zoom to France :D :D :D

**Comment by martynasma** [comment]
OK, so my guess is that at `fontSize: 0.3` measurement of text gets all wonky, hence the issue.

I wasn't able to find a way around it.

Also, related note: instead of having adapters for `horizontalCenter`/`verticalCenter`, why not have propertyFields?

```JavaScript
label.propertyFields.horizontalCenter = "horizontalCenter";
label.propertyFields.verticalCenter = "verticalCenter";
```

That's way less code with same result :)

**Comment by acivita** [comment]
Hello :).

I hope you are doing fine.

Soo i added border to my labels in order to understand how its work.

To accomplish what i needed by : 
- using horizontalCenter from my data
- using textAlign depending (with 'start' or 'end') of the horizontalCenter property from my data.
-  add a small padding to avoid having letter too close to the point.


Then my horizontal issue was fixed.

```
 dotsSeries.events.on("inited", function () {
    tmpData.forEach(element => {
      var label = labelSeries.mapImages.create();
      label.fontSize = 0.4
      label.latitude = element.latitude;
      label.longitude = element.longitude;
      label.interactionsEnabled = false;
      label.children.getIndex(0).text = element.title;
      label.children.getIndex(0).horizontalCenter = element.horizontalCenter;
      label.children.getIndex(0).verticalCenter = element.verticalCenter;
      label.children.getIndex(0).paddingLeft  = "0.3"
      label.children.getIndex(0).paddingRight  = "0.3"
      label.children.getIndex(0).textAlign = element.horizontalCenter === 'right' ? 'end': 'start'
      });
  });
```

But it was still wrong in vertical, some labels were lower than other...
It was because some of them has down letter like : gjpqy, so i used baseLineRatio in a adapter : 
```
 labelTemplate.adapter.add("baseLineRatio", function(ratio, target) {
    if (checkDownLetter(target.properties.text))
      return -0.5
    else
      return 0;
  })
```

The result is fine now 👍 : 
![amcharts](https://user-images.githubusercontent.com/8580643/181744031-f64aa1f8-76d1-4871-a9eb-1bf98b7b7427.PNG)

Thanks for your help, i can remove the borders now :).

Have a nice day
