### ISSUE TITLE
Confidence interval in LineSeries

### ISSUE THREAD

**Issue by mmilaprat** [amcharts/amcharts4#4114]
Is poosible to add a confidence interval to a series into a LineSeries chart? something like this:

![image](https://user-images.githubusercontent.com/6602727/180372184-6fc35448-20f6-4c29-a095-0486cc11b81a.png)

Details:
amchart: 4x
angular: 13x

Thanks in advance!

**Comment by martynasma** [comment]
I don't have a complete demo, but here's a similar one:
https://www.amcharts.com/demos-v4/range-area-chart-v4/

The idea is this: you have two LineSeries.

1) Man line that goes in the middle.
2) One that you use for area fill. It has both value field and open value field defined with values for upper and lower edge in data, as well as fill defined for it.

Hope that makes sense.

**Comment by martynasma** [comment]
BTW, this is for amCharts 4. Just in case you are looking for amCharts 5 (current version), here's the same demo:
https://www.amcharts.com/demos/range-area-chart/

**Comment by mmilaprat** [comment]
Hi,
Thanks for your response.
I see this example https://www.amcharts.com/demos-v4/range-area-chart-v4/ but is not what I need. 

with this approach I will have 3 lines per each lineseries that I wish to add to the chart and I just need one.

**Comment by martynasma** [comment]
Well, obviously you will need to style as needed.

The series used for fill will need its `strokeOpacity` set to zero so that there's no line.

And the middle line will just go into the middle when you adjust the data.

**Comment by mmilaprat** [comment]
thanks for the ideas. I'll try if something like this works in my case
