### ISSUE TITLE
Sum label inside a donut chart not centered. JSON data. 

### ISSUE THREAD

**Issue by Kalinin** [amcharts/amcharts4#4118]
**Bug description**

Use you tutorial https://www.amcharts.com/docs/v4/tutorials/sum-label-inside-a-donut-chart/
I want to use JSON format to center sum Label in donut. But it is not.

![image](https://user-images.githubusercontent.com/234760/181487408-60e90022-4f00-4e2c-9adb-ed268097c240.png)

I [forked ](https://codepen.io/Kalinin/pen/dymZYPX?editors=0010) [you codepen example ](https://codepen.io/team/amcharts/pen/wZLwyW?editors=0010)

How can i center sum label inside donut? With JSON format.

**Comment by martynasma** [comment]
I updated the CodePen and tutorial. It should now be fine.

Thanks for bringing this to our attention.

**Comment by Kalinin** [comment]
Thank you.
- [Codepen](https://codepen.io/team/amcharts/pen/wZLwyW?editors=0010) is ok now. You removed _bulletsContainer_ wrapper.
- But [tutorial](https://www.amcharts.com/docs/v4/tutorials/sum-label-inside-a-donut-chart/) is not ok. I see _bulletsContainer_ still. 
![image](https://user-images.githubusercontent.com/234760/182358005-31cef995-8f8c-4a8b-9e25-e9966d37804b.png)

**Comment by martynasma** [comment]
Thanks for letting us know. Fixed the tutorial.
