### ISSUE TITLE
Date range painting looks like completely incorrect

### ISSUE THREAD

**Issue by EliseyMartynov** [amcharts/amcharts4#4121]
**Question**
Why date range is painting like that? There are 2 points with range exactly between this 2 points - and range looks like completely incorrect since it's mismatching points :(
![image](https://user-images.githubusercontent.com/66368523/182327639-93fa7a42-82d2-4292-91af-7eb19bfc973a.png)
![image](https://user-images.githubusercontent.com/66368523/182327686-27f6e6d9-1c82-4b9a-a0cd-c7ec72153180.png)
![image](https://user-images.githubusercontent.com/66368523/182327745-8885c613-41e4-44fe-bb3a-7e85dab3cbf8.png)
Sandbox (based on Sandbox from docs): https://codepen.io/magistrfox/pen/poLaRdK

amchart version 4.

**Comment by EliseyMartynov** [comment]
https://github.com/amcharts/amcharts4/issues/2386#issuecomment-624735125
I guess this is the answer for my question
If so - feel free to close that
It's just not really obvious :)

**Comment by martynasma** [comment]
Well, `new Date(2018, 3, 24)` generates a time for the very beginning of April 24th, so that's how the range is painted - beginning from Apr 23 to beginning of Apr 24.

If you need Apr 24 to be covered as well, you have to generate a date for the very end of the day:

`new Date(2018, 3, 24, 23, 59, 59)`

**Comment by EliseyMartynov** [comment]
@martynasma thank you very much, that makes that logic clear! I guess this information will be useful for the next time! But the solution I've found is pretty well fit to my needs.
