### ISSUE TITLE
I want to use different keys to build the chart x-axis and a different one for its label

### ISSUE THREAD

**Issue by mdtalha** [amcharts/amcharts4#4122]
Code- var chart = am4core.create('chartdiv', am4charts.XYChart);

      var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
      categoryAxis.dataFields.category = 'code'    

      var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
      valueAxis.title.text = 'value';

      var series = chart.series.push(new am4charts.ColumnSeries());
      series.dataFields.valueY = 'MAU';
      series.dataFields.categoryX = 'code'
 
      chart.data = [
        {
          code:'1',
          network: 'India',
          MAU: 20,
        },
        {
          code:'2',
          network: 'India',
          MAU: 10,
        },
        {
          code:'3',
          network: 'China',
          MAU: 1,
        },
        {
          code:'4',
          network: 'USA',
          MAU: 1,
        },
        {
          code:'5',
          network: 'UK',
          MAU: 1,
        },
        {
          code:'6',
          network: 'UK',
          MAU: 1,
        },
      ];
i want to show country names(network) instead of the number(code) on x-axis and want to build chart using "code" . This is to handle unique values as you can see i have repetitive values for network . By default amcharts takes label from catrgoryaxis ,i.e, code . How do i change my labels?

![image](https://user-images.githubusercontent.com/57068546/182412991-fa31fddb-a56a-4595-bd7b-11e703b5ce2a.png)

**Comment by martynasma** [comment]
You can use adapters for that:

```JavaScript
categoryAxis.renderer.labels.adapter.add("text", function(text, target) {
  return target.dataItem ? target.dataItem.dataContext.network : text;
});
```
