### ISSUE TITLE
Lazy loading docs should reference viewportTarget option  - onlyShowOnViewport

### ISSUE THREAD

**Issue by samcarton** [amcharts/amcharts4#4123]
**Question\suggestion**

On the [lazy loading docs page](https://www.amcharts.com/docs/v4/concepts/performance/#Lazy_loading_charts) it might be worth mentioning that `options.viewportTarget` will be required if the charts are hosted inside a scrollable container. I only found out by accident when looking at all the available options properties.

**Comment by samcarton** [comment]
Also the part about supporting multiple scroll containers using `HTMLElement[]` set to `options.viewportTarget`, as it is only mentioned in a github issue/release notes somewhere

**Comment by martynasma** [comment]
Good catch! Thanks.

Done.
