### ISSUE TITLE
Change scrollbar behavior

### ISSUE THREAD

**Issue by PavelRusetsky** [amcharts/amcharts4#4125]
Hi, is it to possible to change scrollbar behavior, i want to show data, which is not located in selected date range, but i want to change opacity of it.

Example:
![image](https://user-images.githubusercontent.com/49963615/183971430-a52f238c-0abc-4c45-8fe6-ce4fb86eddf4.png)

**Comment by martynasma** [comment]
There's no such built-in functionality, I'm afraid..

Technically, it could be implemented:

1) Add `Scrollbar` as a standalone element on the chart.
2) Add two axis ranges with semi-transparent fill for left and right.
3) Add events to the scrollbar that would update start/end of the related axis ranges.

Hope that makes sense.

Unfortunately, I don't have a demo like that.
