### ISSUE TITLE
[AmCharts 5] How can I create animated line on map chart

### ISSUE THREAD

**Issue by D-Abdi** [amcharts/amcharts4#4126]
Hello,

I would like to animate a line on a geomap similair to how it is done here https://www.amcharts.com/docs/v4/tutorials/animating-map-lines-with-css/.

Could anyone help me out?

**Comment by zeroin** [comment]
You need to animate strokeDashoffset setting of the mapLines. Here is a demo:
https://codepen.io/team/amcharts/pen/RwMYGrm/a94ed2f15014436a64178ef62a5f3f46

These lines does the thing:
```
var offset = 0
setInterval(()=>{
  lineSeries.mapLines.template.set("strokeDashoffset", offset);
  offset--;
  if(offset == -100){
    offset = 0;
  }
}, 50)
```
