### ISSUE TITLE
[AMCHARTS V4] Logo appearing in the Map, even after adding the license key. Other types of charts working fine.

### ISSUE THREAD

**Issue by anzar-seclogic** [amcharts/amcharts4#4127]
I am using amcharts v4 with react js, and I encountered a peculiar issue where the logo suddenly began appearing on a map chart I have been using. This logo should have been removed after using the license key. More over, this issue only happens in one chart, even though we use amcharts in numerous other places (we don't use any other map chart however)

I have attached the component with logo as well as react imports of the said component.
`import * as am4core from "@amcharts/amcharts4/core";`
`import * as am4maps from "@amcharts/amcharts4/maps";`
`import am4geodata_continentsLow from "@amcharts/amcharts4-geodata/continentsLow";`
`am4core.addLicense(process.env.REACT_APP_AM4LICENSE_KEY);`
![image](https://user-images.githubusercontent.com/81732694/184802981-eacf5fac-e5a4-428e-86f8-aee336212861.png)

**Comment by martynasma** [comment]
Maps is an add-on and requires own license key.

So you need to add both: one for Charts and the other for Maps.

If you have any further questions regarding purchases or licenses, please contact us directly at contact@amcharts.com
