### ISSUE TITLE
How can I add an arrow to each map line of a multiGeoLine?

### ISSUE THREAD

**Issue by moonlight256** [amcharts/amcharts4#4128]
**How can I add an arrow to each map line of a multiGeoLine?**

When I use multiGeoLine to create multiple lines originating from the same point, I want an arrow on each line pointing from source to destination.
However, when I use the built-in arrow of the LineSeries template, it only generates one arrow, located at the midpoint of all the lines.

Example:

```
var lineSeries = chart.series.push(new am4maps.MapLineSeries());
lineSeries.data = [{
  "multiGeoLine": [
    [
      { "latitude": 48.856614, "longitude": 2.352222 },     // Paris
      { "latitude": 40.712775, "longitude": -74.005973 }    // NYC
    ],
    [
      { "latitude": 48.856614, "longitude": 2.352222 },     // Paris
      { "latitude": 49.282729, "longitude": -123.120738 }   // Vancouver
    ]
    ,
    [
      { "latitude": 48.856614, "longitude": 2.352222 },     // Paris
      { "latitude": 41.8781, "longitude": -87.6298 }        // Chicago
    ]
  ]
}];

var lineSeriesTemplate = lineSeries.mapLines.template;
lineSeriesTemplate.arrow.position = 0.5;
lineSeriesTemplate.arrow.width = 10;
lineSeriesTemplate.arrow.height = 10;
```

![image](https://user-images.githubusercontent.com/108032641/184908818-7152ae07-5de4-4896-8086-262bb40160f0.png)

How can I get this to create three arrows, each one at the midpoint of each line? Is there a different approach I should use?

**Environment**

I am using amCharts 4.10.23.

**Comment by martynasma** [comment]
There's no way to position element on a specific segment of a MultiGeoLine.

I suggest you create a separate entries in `lineSeries` for each line.
