### ISSUE TITLE
Axis ticks are not positioned properly when axis labels are rotated

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#413]
Hello,

I want to rotate my axis labels with 90 degrees. But when I am doing so even the ticks are getting rotated.

Is there anyway to avoid this?

**Comment by martynasma** [comment]
I can't seem to reproduce tick rotation, but there's still something's off with the ticks' position with rotated labels:
![image](https://user-images.githubusercontent.com/1458520/46272012-d6b7da80-c557-11e8-8deb-c9ec0dfda332.png)

Example:
https://codepen.io/team/amcharts/pen/bd1ac36afdfda5501467f0204b1326fa?editors=0010

Can you provide your chart code which rotates the ticks?

**Comment by VaishnaviAppannagari** [comment]
Hi,

Yes I have created a sample codepen where the labels are rotated with 180 degrees. 

https://codepen.io/vaish1906/pen/qJZWQQ?editors=0010

As you can see even the ticks are rotated with labels.
