### ISSUE TITLE
Missing zero line when only one column

### ISSUE THREAD

**Issue by mtsoneva** [amcharts/amcharts4#4132]
Hello everyone :)

I am creating horizontal bar chart. I will have negative and/or positive values. I don't want to display the grid lines, but I want to show the zero line like this:
![image](https://user-images.githubusercontent.com/37184051/186677985-b99bed8d-6552-4788-af99-7a94c297d816.png)

But sometimes I may have only one value to display (positive or negative) and in this case the zero line is not showing at all:
![image](https://user-images.githubusercontent.com/37184051/186678639-e163f06d-2515-4846-9afc-90caafca2296.png)

Is there some property for the baseGrid that I am missing?
I tried baseGrid.visible, baseGrid.hidden, line.strokeOpacity, baseGrid.strokeOpacity etc. :D

Here is working codepen - https://codepen.io/mtsoneva/pen/yLKWJRz

**Comment by zeroin** [comment]
This happens because min is not 0. Just set: `valueAxis.min = 0;` and this will do the thing.

**Comment by mtsoneva** [comment]
@zeroin this is working only with positive values.
what if I have only one negative value? The zero line should be on the right side of the line, not on the left like now:
![image](https://user-images.githubusercontent.com/37184051/186683612-d07fdde8-4d78-4524-aaf7-3e201e71bef1.png)

**Comment by zeroin** [comment]
If you values are negative, then 0 is your max value, not min:

`valueAxis.max = 0`

**Comment by mtsoneva** [comment]
yes of course :) I can check what kind of data I have and I will add min or max accordingly.

Thank you so much for your help
