### ISSUE TITLE
How can I create exactly one vertical line on the change in Trend charts ?

### ISSUE THREAD

**Issue by abhiseksubham** [amcharts/amcharts4#4133]
It's a follow up to this story ( https://github.com/amcharts/amcharts4/issues/4082 )

So I saw the documents , We need to create a Range on category Axis on a particular date.
We also found this codepen https://codepen.io/Abhiseksubham/pen/XWEGOZR,
but the examples are for every date.

Could you please help us to create a range for a given particular date.

**Comment by martynasma** [comment]
You can still refer to this tutorial:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides

If you're using a `CategoryAxis`, you just need to use `category` property of the range, rather than `value` or `date`.
