### ISSUE TITLE
NumberFormatter for Combined Tooltip

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4136]
**Question**
I have multi series date chart
The tooltips from all series are combined and displayed as per  the following demo
https://www.amcharts.com/docs/v4/tutorials/multi-series-shared-tooltip-with-colored-bullets/

But I want the numbers displayed in the tooltip to have a numberFormatter `#.00a`

![image](https://user-images.githubusercontent.com/10185101/188503818-dcd33b8a-9124-4858-bfee-58af2163b45d.png)

How can I do this ?

The code snippet for combining tooltips is as follows
```javascript
export const combineSeriesTooltips = (
	chart,
	series,
	dateFormat = DEFAULT_DATE_FORMAT,
) => {
	series.adapter.add("tooltipText", () => {
		let text = `[bold]{dateX.formatDate('${dateFormat}')}[/]\n`;
		chart.series.each(function (item) {
			if (!item.isHidden) {
				if (item.dataFields.valueY != null) {
					text +=
						"[" +
						item.stroke.hex +
						"]●[/] " +
						item.name +
						": $ {" +
						item.dataFields.valueY +
						"}\n";
				}
			}
		});
		return text;
	});

	series.tooltip.getFillFromObject = false;
	series.tooltip.background.fill = am4core.color("#fff");
	series.tooltip.label.fill = am4core.color("#000");
	series.tooltip.defaultState.transitionDuration = 0;
	series.tooltip.hiddenState.transitionDuration = 0;
};
```

Here, I tried by wrapping `item.dataFields.valueY` with numberFormatter, but it didn't work

Can you please help me on this ?

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
You should use in-line formatting:

```
...
": $ {" +
item.dataFields.valueY +
".formatNumber()}\n";
...
```

https://www.amcharts.com/docs/v4/concepts/formatters/#Overriding_format_in_data_fields

**Comment by azharakbar** [comment]
Ok, Thanks @martynasma 
It worked !!
