### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by santosh099** [amcharts/amcharts4#4137]
I am seeing this error when I run the unit tests coverage on my windows machine.  

export { System, system } from "./.internal/core/System";

SyntaxError: Unexpected token 'export'

import * as am4core from '@amcharts/amcharts4/core';
^

we are using the amcharts4 with

node: "^16.13.1"
react: "^17.0.2"

and here is my jest configuration

![Jest Configuration](https://user-images.githubusercontent.com/36532294/188993653-8b5ca63b-5083-44ba-9191-b542c053ebd6.PNG)

**Comment by martynasma** [comment]
Did you follow this guide?
https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/#Using_amCharts_with_Jest
