### ISSUE TITLE
am4maps when the api country code field name is not "ID"

### ISSUE THREAD

**Issue by zubalea** [amcharts/amcharts4#4139]
Trying to find a way to tell the am4maps series that the "id" field in the data is called "countryid"

Tried this (an many many other permutations) with no success.  
var polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
polygonSeries.dataFields.id = 'countryid';

Example taken from the documentation.  All I changed was the id field to say countryid.   
[https://codepen.io/zubalea/pen/QWryYrL](https://codepen.io/zubalea/pen/QWryYrL)

Data being used.
polygonSeries.data = [{
  "countryid": "US",
  "name": "United States",
  "value": 100,
  "fill": am4core.color("#F05C5C")
}, {
  "countryid": "FR",
  "name": "France",
  "value": 50,
  "fill": am4core.color("#5C5CFF")
}];

The reason for this is because the backend is sending different id field name.    I would like the code to adjust to what is being sent to me.

Thank you

**Comment by martynasma** [comment]
Well, but the geodata is still using `id` field. When MapPolygonSeries loads, the geodata and custom data is combined. Having id fields differ results in the issue you mentioned.

If you can't change data coming from the backend, I suggest you refactor the data on client-side, e.g.:

```JavaScript
polygonSeries.data = refactorData([{
  "countryid": "US",
  "name": "United States",
  "value": 100,
  "fill": am4core.color("#F05C5C")
}, {
  "countryid": "FR",
  "name": "France",
  "value": 50,
  "fill": am4core.color("#5C5CFF")
}]);

function refactorData(data) {
  for(var i = 0; i < data.length; i++) {
    data[i].id = data[i].countryid;
  }
  return data;
}
```
