### ISSUE TITLE
Bullet template "disabled" property is not being propagated to cloned bullets

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#414]
Example:
https://codepen.io/dmsmaxim/pen/yRybgq

After 5s I set `circleBullet.disabled = false`, but nothing happens. Bullet remains hidden.
But If I do it in a different order (initially set `circleBullet.disabled = false` and after 5s `circleBullet.disabled = true`), everything works good

**Comment by martynasma** [comment]
In case of bullets `disabled` has a special meaning, so that bullets are not created at all.

We will investigate whether we can amend this behavior so "disabled" bullets are created, and later re-enabled.

In the interim you may work around it by manipulating bullet's opacities instead:

```
circleBullet.fillOpacity = 0;
circleBullet.strokeOpacity = 0;

setTimeout(() => {
  circleBullet.fillOpacity = 1;
  circleBullet.strokeOpacity = 1;
  lineSeries.invalidate();
}, 5000);
```

**Comment by martynasma** [comment]
This seems to have been fixed for some time now. Closing.
