### ISSUE TITLE
I need to set the max value on value axis as 100. It shouldn't exceed 100. But if all the value's in my graph are below 50 then max value shouldn't exceed 50.

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#4141]
I had tried using default behaviour...but when max value in my graph is 100 then it's going up to 120...It's looking like below.
![Screenshot from 2022-09-19 17-54-02](https://user-images.githubusercontent.com/74599304/191016522-07bc36b3-6340-48e7-89e1-f79a1afcdf48.png)

I had set strictminmax property to true then it's giving like below:
for ex: max value is 42%....The value axis is upto 40 only
![Screenshot from 2022-09-19 17-53-46](https://user-images.githubusercontent.com/74599304/191016536-cb59a691-2894-409d-9ea7-721c33ddc822.png)

**Comment by martynasma** [comment]
Try setting `strictMinMax = true` on your Y axis.

**Comment by VineelaKantamneni** [comment]
I had tried setting that if I set that then case 2 mentioned above is arising.
![Screenshot from 2022-09-19 17-53-46](https://user-images.githubusercontent.com/74599304/191023005-238f5dac-234e-4dd1-91e3-96b1bf71763f.png)

for ex: max value is 42%....The value axis is upto 40 only

**Comment by martynasma** [comment]
Not sure how that is possible, unless you also set `max`. Can you post your chart on CodePen?

**Comment by VineelaKantamneni** [comment]
Below are links to code pens.
[https://codepen.io/vineelak/pen/OJZgRLO](url)
In the above graph max value in my graph is 100. by default I'm getting value axis greater than 100.
If I set `valueAxis.strictMinMax = true;` property then the axis is upto 100. 

It's Fine but sometimes I get values of the chart all most equal and the max value on the valueaxis should be based on max value in my data. As I'm setting  `valueAxis.strictMinMax = true;`  I'm getting chart like in below link.
[https://codepen.io/vineelak/pen/KKRqgXY](url)

You can observe above issue in below screenshot. max val60ue in my graph is around 49. so I have to get value axis upto 60. But I'm getting only till 40 due to property `valueAxis.strictMinMax = true;`
![A Pen by vineelak](https://user-images.githubusercontent.com/74599304/191176067-60edbcd2-85eb-4fd7-ad20-40b3b7bf9f70.png)

**Comment by VineelaKantamneni** [comment]
It's working. Thank you. @martynasma and @zeroin
