### ISSUE TITLE
axisRange tooltip auto position on edges

### ISSUE THREAD

**Issue by murilo-kendjy** [amcharts/amcharts4#4143]
Versions: Angular 8, and amcharts 4.10.26

I'm using axisRange + tootltip to generate something like "info events".

![tooltip_position](https://user-images.githubusercontent.com/16575708/191485763-a99dee29-6c4a-4ef2-8e81-f8acb24caf97.jpg)

So far it works ok, the only problem is that some events like the image above is at the edge of the graph, and the tooltip is partially cut.

Is there any way so the tooltip auto position like "Making cursor arrange tooltips" on [Tooltip section](https://www.amcharts.com/docs/v4/concepts/tooltips/)?

The code I'm using:

```
const rangeFatura = xAxis.axisRanges.create();
rangeFatura.value = moment(dataRange).add(2, "m").toDate();
rangeFatura.endValue = moment(dataRange).add(13, "m").toDate();
rangeFatura.axisFill.fill = am4core.color("#ff0000");
rangeFatura.axisFill.fillOpacity = 0.3;
rangeFatura.label.disabled = true;
rangeFatura.axisFill.above = true;

rangeFatura.axisFill.tooltip = new am4core.Tooltip();
rangeFatura.axisFill.tooltipText = "Fechamento de Fatura";
rangeFatura.axisFill.interactionsEnabled = true;
rangeFatura.axisFill.tooltipPosition = 'pointer';
```

**Comment by xorspark** [comment]
Standalone tooltips such as those on axis range fills are not location-aware. You need to explicitly set its [pointerOrientation](https://www.amcharts.com/docs/v4/reference/tooltip/#pointerOrientation_property).

**Comment by murilo-kendjy** [comment]
@xorspark Sorry the late resp, that work thanks!

Just a little note: Maybe its my template but setting pointerOrientation = 'horizontal' solved the info at the end of graph problem, but not at the very beginning, so I need to set it to 'left'.
