### ISSUE TITLE
Is it possible to not instantiate a chart until it is visible?

### ISSUE THREAD

**Issue by stla** [amcharts/amcharts4#4144]
Hello,

I have a [problem with amcharts4 graphics in a dashboard](https://stackoverflow.com/q/73791828/1100107). The dashboard has several pages and there is one chart in each page. When opening it, the chart at the first page is correct. But when going to another page, the chart on this page is already rendered and not correctly. Therefore I'm looking for an option like `onlyShowOnViewport` but to not instantiate the chart when it is not visible (`onlyShowWhenVisible`). I tried this option but it didn't help. I'm using the latest version of **amcharts4** with **React**.

**Comment by zeroin** [comment]
If you render a chart into a div with display:none and later change it to display:block, it should work fine.

**Comment by stla** [comment]
Hello,

That's what I do in my answer on StackOverflow. This is nice except that the button is misplaced.

**Comment by zeroin** [comment]
Try to call `chart.zoomOutButton.hardInvalidate()` when size of a chart changes:

```
chart.events.on("sizechanged", ()=>{
   chart.zoomOutButton.hardInvalidate()
})
```

**Comment by stla** [comment]
Thanks. But this is for a zoom button, right? My button is not a zoom button, this is just a button. But I keep your suggestion in mind, I'll include this code in my package.
