### ISSUE TITLE
Chart.horizontalMouseWheelBehavior - how to make it stop at 0 position of each column

### ISSUE THREAD

**Issue by tessamarelic** [amcharts/amcharts4#4145]
I have used chart.cursor.snapToSeries, this snaps to each column perfectly on touch and drag but there is no way to set this for the horizontalMouseWheelBehavior. It scrolls the chart container freely and stops where ever it wants. 

Is there a way to get mouse wheel scroll to snap to the column start position (0) when it stops.

**Comment by martynasma** [comment]
Fixed in 4.10.30.

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by tessamarelic** [comment]
Hi,We are currently using 4.10.23. Can I straight upgrade to 4.10.30? I’m using Angular 13.ThanksSent from my iPhoneOn 14 Nov 2022, at 8:25 pm, Martynas Majeris ***@***.***> wrote:﻿
Fixed in 4.10.30.
Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
> Hi,We are currently using 4.10.23. Can I straight upgrade to 4.10.30?

Yes.
