### ISSUE TITLE
How do I remove blank space above my chart?

### ISSUE THREAD

**Issue by zacharyJohn98** [amcharts/amcharts4#4147]
I have a chart that is mostly hidden below the fold when the page loads that I would like more visible by moving up the chart in the container. I have tried to use valign on the container as well as the chart with no luck. I want to remove some of the blank space above the gauge.

![Capture](https://user-images.githubusercontent.com/96436244/192057102-febb1704-b0c9-415c-9d75-555f6c7b3b8c.PNG)

**Comment by xorspark** [comment]
You can set a negative margin or padding on the container to shift it upward, for example:

```
chart.chartContainer.marginTop = -50;
// or
chart.chartContainer.paddingTop = -50;
```

**Comment by zeroin** [comment]
If this won't help, could you create a codepen of your chart so we could take a look?
