### ISSUE TITLE
SankeyNode corner radius?

### ISSUE THREAD

**Issue by nsds26** [amcharts/amcharts4#4148]
**Question**
Hey there!

Is there a way to set the corner radius on a SankeyNode? Searched the docs but could not find a property for that.
On column charts we can set the _cornerRadiusTopLeft_ , for example, is there a similar property for a Sankey diagram?

Thanks in advance!

**Comment by zeroin** [comment]
That would be:

```
series.nodes.rectangles.template.setAll({
  cornerRadiusTL:5,
  cornerRadiusTR:5,
  cornerRadiusBL:5, 
  cornerRadiusBR:5
})
```

**Comment by nsds26** [comment]
We're using the amcharts4 version, and to my understanding we don't need to specify the series to create the sankey diagram, is that correct? 
Testing with version 5 I was able to adjust the corner radius using your answer, but unfortunately not on the previous version. 

Thank you!

**Comment by xorspark** [comment]
In v4 you have to set it through the node template's background property. By default it is a Rectangle, so you'd need to replace it with a RoundedRectangle instead in order to specify a corner radius:

```
var nodeTemplate = chart.nodes.template;
nodeTemplate.background.dispose();
nodeTemplate.background = new am4core.RoundedRectangle();
nodeTemplate.background.cornerRadius(10, 10, 10, 10);
```

Demo: https://codepen.io/team/amcharts/pen/yLjpgay/59551318e80b4b5785613888d0ef9d96?editors=0010

**Comment by nsds26** [comment]
That's it!
I don't know why it didn't occur to me to change the background rectangle, but it works perfectly.
Thanks a million!
