### ISSUE TITLE
PinBullet Image padding

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#4149]
Hi! I want to make paddings for images in PinBullets, is there any way to do it? 
My bullets now look like this: 
![image](https://user-images.githubusercontent.com/18229211/193000878-d5335a21-e3a6-4fa9-958e-fd36ed599cfc.png)
Bullet is:  
```
const bullet = series.bullets.push(
                new am4plugins_bullets.PinBullet()
            );
```
If i increase `bullet.background.radius`, the whole image increases. If i decrease `bullet.cirlce.radius`, it only makes the frame around the image thicker without changin the image size, bullet.background.padding and bullet.image.padding make bullets look like this: 
![image](https://user-images.githubusercontent.com/18229211/193002424-27f5f3ca-1466-4bbd-ba1a-6ed50b8673fa.png)

I want image to have paddings like this: 
![image](https://user-images.githubusercontent.com/18229211/193001347-4e00c4ff-d791-4179-a156-af9c6a4f2700.png)
I've tried to find the way in documentation, but haven't succeed

**Comment by zeroin** [comment]
I achieved a similar result by increasing radius and setting scale for the image:
https://codepen.io/team/amcharts/pen/abGqePj/bad1e0e7fbda682d0799aeb5bb0c7957?editors=1010

**Comment by 12rita** [comment]
@zeroin yes, that is what i needed, thank you!)
