### ISSUE TITLE
How to set inner radius of circle bullet

### ISSUE THREAD

**Issue by manoj016** [amcharts/amcharts4#415]
Hi,

I want to set inner radius o the circle bullets like a feature in amcharts 3.

<img width="872" alt="screen shot 2018-09-29 at 5 20 03 pm" src="https://user-images.githubusercontent.com/41284266/46245535-99930180-c40c-11e8-81b4-dd71b4173c4d.png">

Is there any feature for this in amcharts4? Please help.

Thank you

**Comment by martynasma** [comment]
In that case you set bullet's `fill` to white, and its `strokeWidth` to some number:

```
var bullet = series.bullets.push(new am4charts.CircleBullet());
bullet.strokeWidth = 3;
bullet.fill = am4core.color("#fff");
```

https://codepen.io/team/amcharts/pen/YJXGOM/

**Comment by manoj016** [comment]
Thank you very much @martynasma

**Comment by manoj016** [comment]
Hi,
I think one issue is here. When the graph plots if there is many data the bullets showing like a series.
<img width="457" alt="screen shot 2018-10-01 at 1 01 10 pm" src="https://user-images.githubusercontent.com/41284266/46275430-93229800-c57a-11e8-968a-0fdd20ffeb81.png">

And if I zoom it then it shows the proper graph like some bullets.
<img width="415" alt="screen shot 2018-10-01 at 1 01 21 pm" src="https://user-images.githubusercontent.com/41284266/46275892-0d075100-c57c-11e8-8d42-f9f607fa711d.png">

**Comment by martynasma** [comment]
You can set [`minBulletDistance`](https://www.amcharts.com/docs/v4/reference/lineseries/#minBulletDistance_property) to some number larger than 0, e.g. 50.

This will remove bullets when they are too close together (zoomed out), and will show them when user zooms in.

**Comment by martynasma** [comment]
P.S. the default 50 in docs is wrong. It's zero. I'll fix the docs.

**Comment by martynasma** [comment]
It's a setting for series, not bullet ;)

```
series.minBulletDistance = 2000;
```

Although 2000 is a bit excessive ;)

**Comment by martynasma** [comment]
Please note there's a bug with `minBulletDistance`, though: #376

We're going to fix it. You might want to subscribe to that issue so that you can keep up with the progress.
