### ISSUE TITLE
I need to colorize label value in amcharts4 Pie Chart with condition

### ISSUE THREAD

**Issue by canesen7** [amcharts/amcharts4#4150]
![image](https://user-images.githubusercontent.com/67913330/194559997-cbfd65aa-79fd-4240-a440-6e0e7c389cbe.png)

Hi. I have a issue about amcharts4 PieChart. I can colorize the pie if condition is true. But also I need to colorize pie's measure value (label). When I need to colorize pie, I can do it with 

pieSeries.slices.template.propertyFields.fill = "color";

I can add the pie color and label color in data. When I research the this issue I found this code

    chart.events.on('ready', () => {
      chart.series.getIndex(0).labels.each(function(label) {
        label.properties.fill = am4core.color("red")
      });
    });

but it doesn't solve my problem. 

Thank you.

**Comment by xorspark** [comment]
You can apply property field on the label template:

```
pieSeries.labels.template.propertyFields.fill = "color"
```

If you want the legend labels to match, you have to set this on the labels and valueLabels template in the legend.

```
chart.legend.labels.template.propertyFields.fill = "color"
chart.legend.valueLabels.template.propertyFields.fill = "color"
```
