### ISSUE TITLE
Mutating numberFormatter doesn't seem to work

### ISSUE THREAD

**Issue by hfhchan** [amcharts/amcharts4#4151]
**Bug description**
When updating `numberFormatter.numberFormat` or `numberFormatter` itself while also updating the chart data, only the newly appeared labels are formatted to the new number format. If the label already exists, it is kept using the old number format.

Code sample:
```
const percentFormatter = new am4core.NumberFormatter();
percentFormatter.numberFormat = "'percent' #.##%";

const decimalFormatter = new am4core.NumberFormatter();
decimalFormatter.numberFormat = "'decimal' #.##";

initGraph() {
    const xAxis = chart.xAxes.push(new am4charts.ValueAxis());
    xAxis.numberFormatter = percentFormatter;

   chart.data = [{}] // some data which goes from 0% to 320%
}

updateGraph() {
  chart.data = [{}] // some data which goes from -100 to +100
  updateAxis();
}

updateAxis() {
  const xAxis = chart.xAxes.getIndex(0) as am4charts.ValueAxis;
  xAxis.numberFormatter = decimalFormatter;
}
```

When calling `updateGraph()`, the x axis ends up with something like `decimal -1.0`, `decimal -0.5`, `percent 0%`, `decimal 0.5`, `decimal 1.0`.

It seems since the value `0` is chosen to be the x axis label on both before and after the change, amcharts skips reformatting it.

Is there any way I can force it to be reformatted?

**Environment (if applicable)**

 - amCharts version 4
 - Browser: Firefox
 - Related frameworks and their versions: Vue 2

**Comment by xorspark** [comment]
The axis does not update every label, only the ones that have changed. This is by design. If you need to force an update to all labels after a data update, you have to call [invalidateLabels](https://www.amcharts.com/docs/v4/reference/valueaxis/#invalidateLabels_method), e.g. `xAxis.invalidateLabels()`

**Comment by hfhchan** [comment]
That solves the issue! Many thanks!
