### ISSUE TITLE
How do I set the tooltipText properties for line charts in amchart

### ISSUE THREAD

**Issue by 15602322852** [amcharts/amcharts4#4152]
How do I set the tooltopText properties for line charts in amchart?

**Comment by martynasma** [comment]
I suggest taking a look at this extensive tutorial:
https://www.amcharts.com/docs/v4/concepts/tooltips/

**Comment by 15602322852** [comment]
How is it used in the lowdefy?

**Comment by martynasma** [comment]
I'm sorry, I have no idea what lowdefy is :)
