### ISSUE TITLE
[question][need more info]Turning floorplan into map chart

### ISSUE THREAD

**Issue by aekiratli** [amcharts/amcharts4#4156]
Hello,

I have floorplan and zones belonging the floorplan. Data I have is how many people were in the specific zone at that specific time
I am trying to illustrate how many people were in the zone at specific time. Something like this; please see [here](https://community.plotly.com/t/is-there-a-way-to-create-a-heatmap-for-a-floor-plan-in-plotly/61762)

I have seen [US heat map example](https://www.amcharts.com/demos/us-heat-map/). Is there anyway to achieve this using XY map? I am not familiar with geosjon data and, converting floorplan into geojson data is not doable I think. I would really appreciate if you could point where to start. Worst case I will be working on canvas and trying to implement this using polygons

**Comment by martynasma** [comment]
I don't think something like that is possible with an XYChart. Sorry.
