### ISSUE TITLE
problem about npm version 

### ISSUE THREAD

**Issue by isaacqian** [amcharts/amcharts4#4158]
![微信截图_20221019111536](https://user-images.githubusercontent.com/9843702/196589493-e95d1244-dc83-470e-9dc4-8fa16a51a8bf.png)
in npm website the version is 4.10.29
![微信截图_20221019111627](https://user-images.githubusercontent.com/9843702/196589568-d00871e8-e8ac-4a44-8d72-684535984cb7.png)
but detail show used by npm view command is 4.10.28

**Comment by martynasma** [comment]
Can you try again? It looks fine to me now. Maybe it was some caching issue.

**Comment by isaacqian** [comment]
![微信截图_20221019135146](https://user-images.githubusercontent.com/9843702/196607878-c65c3c3f-8037-4ad3-9c8c-79ecef5f01f1.png)
still can't. The scene is: first I specify amcharts version in package.json dependencies. then type 'npm install' command. the result is the error “No matching version found for @amcharts/amcharts4@^4.10.29” is shown.

**Comment by martynasma** [comment]
Try this:

```
npm cache clean --force 
```

**Comment by isaacqian** [comment]
Still can't. Finally, I change amcharts version to 4.10.28, and installed successfully. Thank you very much.
