### ISSUE TITLE
Adding dotted line from bottom to bullet

### ISSUE THREAD

**Issue by Ali-hd** [amcharts/amcharts4#4159]
Hi, 

I am trying to create a dotted line that goes from the bottom date axis to the bullet as seen in the picture inside the codepen

Thanks, Please check the below codepen and desired result under the graph.
https://codepen.io/Alimodz/pen/oNyvYKy

**Comment by martynasma** [comment]
You can use a `Line` object in a bullet to achieve that.

Here's a demo:
https://www.amcharts.com/docs/v4/tutorials/custom-multiple-element-bullets/

**Comment by Ali-hd** [comment]
> You can use a `Line` object in a bullet to achieve that.
> 
> Here's a demo: https://www.amcharts.com/docs/v4/tutorials/custom-multiple-element-bullets/

Works like a charm! thanks so much for the help
