### ISSUE TITLE
PieSerie configField

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#416]
Hello,

I'm not able to make configFIeld work: 

https://codepen.io/ptorrent/pen/XxJZdo

https://www.amcharts.com/docs/v4/reference/pieseries/#configField_property

![image](https://user-images.githubusercontent.com/6083644/46249312-45494b00-c427-11e8-8045-0333650086aa.png)

From the documentation, I think I'm doing okay ^^ 

Thanks for support

**Comment by martynasma** [comment]
Perhaps the documentation is not clear enough. `configField` applies to a particular element. `PieSeries` is not an element. Serie's slices are. So you need to set it on the slice template:

```
pieSeries.slices.template.configField = 'config'
```

This will work as expected.

**Comment by ptorrent** [comment]
Thanks for your answer ! So how to set specific color for each part (data) of the PieChart ?

**Comment by martynasma** [comment]
I wouldn't use `configField` if all you need is to set color of the slice.

I'd rather use `propertyFields`:

```
// Create chart instance
var chart = am4core.create("chartdiv", am4charts.PieChart);

// Add data
chart.data = [{
  "country": "Lithuania",
  "litres": 501.9
}, {
  "country": "Czech Republic",
  "litres": 301.9
}, {
  "country": "Ireland",
  "litres": 201.1
}, {
  "country": "Germany",
  "litres": 165.8
}, {
  "country": "Australia",
  "litres": 139.9
}, {
  "country": "Austria",
  "litres": 128.3
}, {
  "country": "UK",
  "litres": 99,
  "fill" : "#00f"
}, {
  "country": "Belgium",
  "litres": 60,
  "fill" : "#0f0"
}, {
  "country": "The Netherlands",
  "litres": 50,
  "fill" : "#f00"
}];

// Add and configure Series
var pieSeries = chart.series.push(new am4charts.PieSeries());
pieSeries.dataFields.value = "litres";
pieSeries.slices.template.propertyFields.fill = "fill";
pieSeries.slices.template.propertyFields.stroke = "fill";
pieSeries.dataFields.category = "country";
```

**Comment by ptorrent** [comment]
perfect, thanks
