### ISSUE TITLE
Filling line chart

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#4161]
Hi! I am struggling trying to add filling to my line chart. I want the space under the line to be colored. I guess the problem of standart filling is not working is that i have category Y axis. So i tried to add range to my date axis, but it didn't help. Is there any way to make it work? 
What i want: 
![image](https://user-images.githubusercontent.com/18229211/198277695-d6a53b82-8df1-4f1b-b5ab-44326d57af23.png)

[What i get](https://codepen.io/12rita/pen/JjZoebN) (strangely, colored part doesn't really matches with dates)

**Comment by martynasma** [comment]
If you need the fill in a CategoryAxis as Y-axis situation, you may need to set `baseAxis` for your series, so that it knows where to fill to:

```
series.baseAxis = dateAxis;
```

**Comment by 12rita** [comment]
> If you need the fill in a CategoryAxis as Y-axis situation, you may need to set `baseAxis` for your series, so that it knows where to fill to:
> 
> ```
> series.baseAxis = dateAxis;
> ```

I've tried and it makes the lines shift from the bullets, and color block places in the middle of the "line", and i need it to be placed from the line to the date axis:
![image](https://user-images.githubusercontent.com/18229211/198288059-ceaeeff1-a926-42ec-b208-3b9b69a9eb1b.png)

**Comment by martynasma** [comment]
Indeed. In such case, there's probably no way to make such setup as you need to.

Does Y axis absolutely need to be CategoryAxis? It would work if it was a ValueAxis.

**Comment by 12rita** [comment]
I see, i will try to do change it to ValueAxis, i think it should be okay. Thank you
