### ISSUE TITLE
Axis in the middle of the chart

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#4162]
Hi again! Sorry for non-stop questions, but i'm just trying to fit in all the customer's requirements. Is there any way to place xAxis in the middle of the chart? Like this:
![image](https://user-images.githubusercontent.com/18229211/198589906-4fbd7bf1-ff39-4d0b-9d26-8a6eda702f5b.png)
I thought, that timeline chart would be the answer, but i realize, that it onle changes the curviness of chart, not position of axis.

**Comment by martynasma** [comment]
Maybe just use an adapter to dynamically offset the axis `y` property?

```JavaScript
xAxis.adapter.add("y", function(y, target) {
  console.log(chart.plotContainer.pixelHeight)
  return chart.plotContainer.pixelHeight / -2;
});
```

**Comment by 12rita** [comment]
> Maybe just use an adapter to dynamically offset the axis `y` property?
> 
> ```js
> xAxis.adapter.add("y", function(y, target) {
>   console.log(chart.plotContainer.pixelHeight)
>   return chart.plotContainer.pixelHeight / -2;
> });
> ```

Worked perfectly, thanks)
