### ISSUE TITLE
How to give equal width for the Actual pie chart and a pie chart drawn with a slice ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#4163]
I have a pie chart like in below image when I click on it's slice I will get another pie chart. Now, I need to give equal amount of width to both. How to give equal width ??
![Screenshot from 2022-11-03 11-08-50](https://user-images.githubusercontent.com/74599304/199654209-190df59f-a618-4bed-98b0-979614d60ad6.png)

**Comment by martynasma** [comment]
It's clear that with legend on and the amount of available space for the second chart, the pie can't be the same size as the first one.

Unless you would like to disable the legend, or have it overlap the pie itself.

So, I'm not sure how you'd like to handle it.

**Comment by martynasma** [comment]
If you need equal sized pie charts, you need to have conditions where each pie series has exactly the same space.

This means that you might need to either move out the legend into separate container, or set fixed width to the legend.

**Comment by VineelaKantamneni** [comment]
Here is the [demo](https://codepen.io/vineelak/pen/RwJggVL) of chart. Please help me out to get equal width to both charts.

Thank you.

**Comment by martynasma** [comment]
Unless I'm missing something, there's only one chart in the demo you have referred to.

**Comment by martynasma** [comment]
OK. My bad.

For starters, you probably want to have both of your charts to have equal available space:

```JavaScript
chart.width = am4core.percent(50);
chart2.width = am4core.percent(50);
```

Then you could normalize and adjust the radius of the second series when click happens, to match the first one:

```JavaScript
pieSeries2.pixelRadius = pieSeries.pixelRadius;
pieSeries2.dy = -chart.legend.measuredHeight / 2;
```

Updated CodePen:
https://codepen.io/team/amcharts/pen/dyKRZop/e8fbff836ea2483adf440f225d631bf9?editors=0010

**Comment by VineelaKantamneni** [comment]
It's working thank you so much :)
