### ISSUE TITLE
Tooltip Styles

### ISSUE THREAD

**Issue by jayakumarim** [amcharts/amcharts4#4164]
Hi,
I need the tooltip styles same as legends in the screenshot (dash line and dotted line) instead of circles.
please help me how to achieve it.
![tooltip](https://user-images.githubusercontent.com/86111000/199723526-43add28a-e16a-4de4-ae5c-4ca92899c6ff.png)

**Comment by martynasma** [comment]
There's no built-in way to do it, I'm afraid.

You would probably need to use [HTML tooltips](https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/#Tooltips), and put actual images there.

**Comment by jayakumarim** [comment]
> There's no built-in way to do it, I'm afraid.
> 
> You would probably need to use [HTML tooltips](https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/#Tooltips), and put actual images there.
