### ISSUE TITLE
scatter chart/chart with gaps keeps on hanging with multiple series.

### ISSUE THREAD

**Issue by geervani** [amcharts/amcharts4#4165]
Hi, 
I am having a scatter chart/charts with gaps in the series. Data from the service is coming with a "NaN" which we are converting to undefined in the 'beforedatavalidated' event.

We will be having 6-8 line series(dynamic). Scatter chart is working fine with 1 series. But if I try to uncomment the below lines in my codepen sample, the chart hangs. I actually have to add 6 series to it.

//createAxisAndSeries("plot2", "Series 2", false);
//createAxisAndSeries("plot3", "Series 3", false);
//createAxisAndSeries("plot4", "Series 4", false);
//createAxisAndSeries("plot5", "Series 5", false);
//createAxisAndSeries("plot6", "Series 6", false);

We do have huge data (2 days data at a frequency of 1 min). 

CodePen link below for ref 
https://codepen.io/geervani-the-flexboxer/pen/ExovJzY?editors=0010

Highly appreciate any help.. Thanks in advance.. 

Geervani

**Comment by martynasma** [comment]
Using `CategoryAxis` with so many categories is very inefficient.

Since your X value seems to be dates, I strongly suggest using DateAxis instead.

It should be able to handle 6 series with ~2k data points easily.

**Comment by geervani** [comment]
Thanks for quick reply @martynasma, actually we are using DateAxis in the code. Here in codepen since I modified an existing scattered chart it had become CategoryAxis . Sorry about that.
I have updated my code pen sample. 
strangely Now I am able to plot 2 series. But when I uncomment the 3rd one, it hangs again..

**Comment by martynasma** [comment]
Have you tried enabling data point grouping?

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping

**Comment by martynasma** [comment]
Also, I would suggest considering moving to amCharts 5. It's much much faster in situations like this.

**Comment by geervani** [comment]
> Have you tried enabling data point grouping?
> 
> https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping

Yeah I tried applying grouping by minute. But the graph was looking weird after applying grouping..

Also we have license for amcharts4 only..

I noticed that `beforedatavalidated `event is firing multiple times and setting  `ev.target.data = data;` in `beforedatavalidated ` is causing the issue.

So added a flag to avoid reloading. Not sure if this is the right way. Still need to verify this in our dev env.
I have updated the codepen. please do verify.

**Comment by martynasma** [comment]
> I noticed that beforedatavalidated event is firing multiple times and setting ev.target.data = data; in beforedatavalidated is causing the issue.

Well, you are setting a new data in the `beforedatavalidated` handler, which in turns triggers data validation anew, and new `beforedatavalidated` call, etc.

If you need data to be processed only once, you can use `chart.events.once()` (instead of `on()`).

**Comment by geervani** [comment]
ok thats clean.. thank you.
But 1 more questions here, if we get new data from service after sometime, will chart.events.once() be trigged? Actually we have something like, enduser may be on the same page, but the chart need to reload once new data is received..

**Comment by martynasma** [comment]
`once` will trigger only one time.

However, if you need to pre-process the data, you can do that in the code that actually loads the data.

Or have the repeat call check, like the one you have right now.

Both sound equally good to me.
