### ISSUE TITLE
Fill on hover

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#4167]
Hi! Now i need to add filling only on hover. This is question connected with [this one](https://github.com/amcharts/amcharts4/issues/4160). Problem is: filling of the line is considered as part of it. So hover on the filling triggers the hover event. With that, having two series, one exactly beneath the other, it's impossible to hover on the lower one, like on the picture (orange line fill completely overlaps pink line, so its unable to hover on it): 
![image](https://user-images.githubusercontent.com/18229211/200300130-9e1762aa-1b0d-41de-8748-ef2c78a79da6.png)

Is it any way to trigger hover only on line segments, not on line fill? Or other way to produce that behavior?

[Example](https://codepen.io/12rita/pen/NWzWgbW)

**Comment by zeroin** [comment]
You could add hover events on strokeSprite instad of the whole series, but this means that you should make the fillSprite invisible when mouse is out, as otherwise it will still be over the line element of the series beneath. 

This should do the thing:

```
series.segments.template.strokeSprite.events.on("over", (e)=>{
   e.target.parent.children.getIndex(0).visible = true
})

series.segments.template.strokeSprite.events.on("out", (e)=>{
   e.target.parent.children.getIndex(0).visible = false
})
```

**Comment by 12rita** [comment]
Worked perfectly, thanks again)

**Comment by 12rita** [comment]
Hi again! Now i was asked to "wider the space for hover". I mean, now you have to hover exactly on line to trigger event (like i wanted to), but it turned out that this is too narrow space to hover on it. Is there any way to make hover space over line wider (hovering on line fill still not an option, infortunately)?
