### ISSUE TITLE
Error when load external data

### ISSUE THREAD

**Issue by joseserrano15** [amcharts/amcharts4#4169]
I'm using Loading External Data option, but I have a problem, sometimes appears an error in the javascript console: net::ERR_NETWORK_IO_SUSPENDED and in the chart: Unable to load file. 
Anybody knows what could be the problem?

![image](https://user-images.githubusercontent.com/68348356/200945542-95c14ea3-a53b-45fc-abb6-df2c7a516128.png)

**Comment by xorspark** [comment]
It's probably either an issue with your PHP script or a server/network issue on your end. Check the network tab in your browser console for that request.
