### ISSUE TITLE
Cursor and tooltip showing wrong minutes and seconds

### ISSUE THREAD

**Issue by naveennkbk** [amcharts/amcharts4#4170]
Hi all ,
   I created XY series chart , everything working fine . But Cursor date and series date x axis showing different time , Please help me to solve as soon as possible.

  date and time showing correctly but minutes and seconds are showing incorrect .

![image](https://user-images.githubusercontent.com/93131601/201068042-20b33b5f-e35e-4cbe-87dd-7fbb5332752d.png)

 1. used below code for cursor

 dateAxis.tooltipDateFormat = "yyyy-MM-dd hh:mm:ss a";

2. used below code for tooltip

   series.tooltipText = "[bold]{BACnetObjectName}\n[bold]{TimeStampString.formatDate('\YYYY.MM.dd hh:mm:ss a\')}\n[bold]{ValueDescription}{UnitsValue}";

**Comment by martynasma** [comment]
Without being able to see your actual chart, I assume that the axis tooltip is being rounded to the actual `baseInterval` set in your axis settings.

If you need precision down to the second, you might need to use "second" in your baseInterval setting:

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Manually_specifying_data_granularity

**Comment by naveennkbk** [comment]
Am not used any BaseInterval here . Actually in above image u can see that date, time and hours showing correctly . but minutes and seconds are different.

See below i will paste my full code that used for chart creating

        // Create chart instance
        chart = am4core.create("chartdiv", am4charts.XYChart);
        // remove chart logo
        if (chart.logo) {
            chart.logo.disabled = true;
        }
        // Add data
        chart.data = trendLogDataItem;


        //alert(JSON.stringify(trendLogDataItem));

        chart.language.locale["_date_millisecond"] = "mm:ss SSS";
        chart.language.locale["_date_second"] = "HH:mm:ss";
        chart.language.locale["_date_minute"] = "HH:mm";
        chart.language.locale["_date_hour"] = "HH:mm";
        chart.language.locale["_date_day"] = "MM/dd ";
        chart.language.locale["_date_week"] = "ww";
        chart.language.locale["_date_month"] = "MMM";
        chart.language.locale["_date_year"] = "yyyy"
        chart.maskBullets = false;
        // Create axes
        var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
        //dateAxis.dateFormatter.dateFormat = "YYYY.MM.dd hh.MM.ss a";
        //dateAxis.dataFields.data = new Date("{TimeStampString}");

        dateAxis.dateFormats.setKey("hour", "MM/dd hh:mm a");
        dateAxis.periodChangeDateFormats.setKey("hour", "MM/dd hh:mm a");

        chart.dateFormatter.inputDateFormat = "yyyy-MM-ddTHH:mm:ss.SSSZ";
        dateAxis.renderer.minGridDistance = 60;

        

        dateAxis.align = "left";
        //dateAxis.renderer.grid.template.location = 0;
        dateAxis.renderer.minGridDistance = 60;
        //dateAxis.renderer.grid.template.disabled = true;

        dateAxis.renderer.labels.template.textAlign = "middle";
        dateAxis.startLocation = 0.5;
        dateAxis.endLocation = 0.5;

        chart.plotContainer.background.stroke = am4core.color("#262626");

        
        //chart.scrollbarY.series.removeIndex(0);

        var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

        //var rightValueAxis = chart.yAxes.push(new am4charts.ValueAxis());

        //rightValueAxis.renderer.opposite = true;

        valueAxis.title.text = (displayUnits != null && displayUnits !== '') ? displayUnits : '';

        // Create series
        var series = chart.series.push(new am4charts.LineSeries());
        series.dataFields.valueY = "ValueDescription";
        series.dataFields.dateX = "TimeStampString";

        //series.tooltipHTML = '<div style="text-align:left; padding-left: 5px;"><b> {BACnetObjectName}<br/>{TimeStampString.formatDate(\"YYYY.MM.dd hh.MM.ss a\")}<br/>{ValueDescription}{UnitsValue}</b></div>';
        //series.tooltipHTML = '<div>{ToolTipContent}<div>';
        //series.tooltipText = "[bold]{BACnetObjectName}\n[bold]{TimeStampString.formatDate(\"YYYY.MM.dd hh.MM.ss a\")}\n[bold]{ValueDescription}{UnitsValue}";

        series.tooltipText = "[bold]{BACnetObjectName}\n[bold]{TimeStampString.formatDate('\YYYY.MM.dd hh:mm:ss a\')}\n[bold]{ValueDescription}{UnitsValue}";
        series.tooltip.getFillFromObject = false;
        //series.tooltip.background.fill = false;
        series.tooltip.background.stroke = am4core.color("#ff6600");
        series.tooltip.background.strokeWidth = 2;
        series.tooltip.label.fill = am4core.color("#000");
        //series.tooltip.label.padding(7, 30, 7, 30);

        dateAxis.dateFormats.setKey("hour", "MM/dd hh:mm a");
        dateAxis.periodChangeDateFormats.setKey("hour", "MM/dd hh:mm a");
        series.fill = "#ff6600";

        series.stroke = "#ff6600";


        var title = chart.titles.create();
        title.text = "[bold]Trends - " + commonInputDetails.PointName + " - " + commonInputDetails.ObjectType;
        title.fontSize = 15;
        title.marginBottom = 20;



        // Add scrollbar
        chart.scrollbarX = new am4charts.XYChartScrollbar();
        chart.scrollbarX.series.push(series);
        //chart.scrollbarX.minHeight = 10;

        chart.scrollbarY = new am4charts.XYChartScrollbar();
        chart.scrollbarY.series.push(series);

        // Add cursor
        chart.cursor = new am4charts.XYCursor();

        /* Configure cursor lines */
        chart.cursor.lineX.stroke = am4core.color("#004D6D");
        chart.cursor.lineX.strokeWidth = 2;
        chart.cursor.lineX.strokeDasharray = "";

        chart.cursor.lineY.stroke = am4core.color("#004D6D");
        chart.cursor.lineY.strokeWidth = 2;
        chart.cursor.lineY.strokeDasharray = "";
        //chart.cursor.xAxis = dateAxis;
        /*  chart.cursor.snapToSeries = series;*/

        chart.scrollbarX.minHeight = 40;
        
        chart.exporting.filePrefix = commonInputDetails.PointName + " - " + commonInputDetails.ObjectType;



        //this hides regular labels close to the start/end
        dateAxis.renderer.minLabelPosition = 0.08;
        dateAxis.renderer.maxLabelPosition = 0.92;

        dateAxis.renderer.labels.template.fontSize = 10;

        //add ranges
        var minRange = dateAxis.axisRanges.create();
        // this overrides minLabelPosition/maxLabelPosition so that the range labels would be visible
        minRange.maxPosition = 1;
        minRange.minPosition = 0;
        minRange.label.horizontalCenter = "left"
        minRange.label.paddingLeft = 0;



        var maxRange = dateAxis.axisRanges.create();
        // this overrides minLabelPosition/maxLabelPosition so that the range labels would be visible
        maxRange.maxPosition = 1;
        maxRange.minPosition = 0;
        maxRange.label.horizontalCenter = "right"
        maxRange.label.paddingRight = 0;

        dateAxis.events.on("startendchanged", updateRangeLabels)
        dateAxis.events.on("extremeschanged", updateRangeLabels)

        function updateRangeLabels() {
            minRange.value = dateAxis.min + dateAxis.start * (dateAxis.max - dateAxis.min);

            minRange.label.text = dateAxis.dateFormatter.format(minRange.value, "MM/dd");
            //alert(minRange.label.text);
            maxRange.value = dateAxis.min + dateAxis.end * (dateAxis.max - dateAxis.min);

            maxRange.label.text = dateAxis.dateFormatter.format(maxRange.value, "MM/dd");
            //alert(maxRange.label.text);
        }

        chart.scrollbarX.unselectedOverlay.fillOpacity = 0.9;
        //chart.scrollbarY = new am4core.Scrollbar();

        var bullet = series.bullets.push(new am4charts.CircleBullet());
        bullet.circle.stroke = am4core.color("#ff6600");
        bullet.circle.strokeWidth = 2;
        chart.exporting.menu = new am4core.ExportMenu();

        chart.exporting.dataFields = {
            "TimeStampString": "Date/Time",
            "BACnetObjectName": "Reference Object",
            "Value": "Present Value",
            "ValueDescription": "Value Description",
            "Units": "Units"

        };

        var axisTooltip = dateAxis.tooltip;
        axisTooltip.background.fill = am4core.color("#004D6D");
        axisTooltip.background.pointerLength = 0;


        var valueAxisTooltip = valueAxis.tooltip;
        valueAxisTooltip.background.fill = am4core.color("#004D6D");

        dateAxis.adapter.add("getTooltipText", function (text, target) {
            return " [bold]" + text + "[/] ";
        });
        dateAxis.tooltipDateFormat = "yyyy-MM-dd hh:mm:ss a";

        chart.scrollbarX.minHeight = 30;
        chart.scrollbarY.minWidth = 30;

        dateAxis.renderer.labels.fontSize = 30;

        var axisLabels = valueAxis.renderer.labels.template;
        axisLabels.fontSize = 08;
        axisLabels.fontWeight = "bold";

**Comment by martynasma** [comment]
> Am not used any BaseInterval here .

Correct.

That's why chart is trying to figure out it automatically. It does not always have it right, so you need to set it manually.

```JavaScript
dateAxis.baseInterval = { timeUnit: "second", count: 1 };
```

**Comment by naveennkbk** [comment]
Hi can u tell me the way to remove lines in scrollbar 
![image](https://user-images.githubusercontent.com/93131601/201570610-15f40277-ea3f-41af-bd99-ee6cf3ab01ea.png)
i need to show only date time in scrollbar . i need to remove graphics

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by naveennkbk** [comment]
thanks worked
