### ISSUE TITLE
Sankey: Color some paths with different colors

### ISSUE THREAD

**Issue by CarmineBruno** [amcharts/amcharts4#4171]
Hi everyone!

I want to color one specific path (from beginning to end) with a different color.
Something like the image below.

![image](https://user-images.githubusercontent.com/70442479/201158179-563ed4f9-82ef-4349-9ea7-d7e386d09679.png)

The general idea is that all final nodes (on the right) have a boolean value, which if it is true, must color the whole path with a different color.

It is possible to do it with amcharts 4? If yes what kind of function i need to use? I cannot find anywhere something like that

**Comment by martynasma** [comment]
Yes:
https://www.amcharts.com/docs/v4/chart-types/sankey-diagram/#Binding_appearance_to_data

**Comment by CarmineBruno** [comment]
Thank you very much!
