### ISSUE TITLE
remove line series in scrollbar x and scrollbary

### ISSUE THREAD

**Issue by naveennkbk** [amcharts/amcharts4#4172]
Pls help me to remove  line series in scrollbar 

![image](https://user-images.githubusercontent.com/93131601/201641942-2172a667-d6f1-4b57-a353-1540753bc2eb.png)

**Comment by martynasma** [comment]
The series is not added to scrollbar by default. If it's there, it means you have it explicitly in your code.

Something like this:

```
scrollbarX.series.push(series);
```

**Comment by naveennkbk** [comment]
Actually i need this for showing date value from series . but i dont need to show only date and time in scrollbar . not design 
![image](https://user-images.githubusercontent.com/93131601/201660796-62f3a7cf-df45-474f-beef-a9dee3cd2018.png)

**Comment by martynasma** [comment]
Gotcha.

In that case you just need to hide the scrollbar series:

```
scrollbarX.scrollbarChart.seriesContainer.hide();
```

**Comment by martynasma** [comment]
Ummm... what is "up and down horizontal design"?

**Comment by naveennkbk** [comment]
am saying that line over the date and time . that series plot line.

![image](https://user-images.githubusercontent.com/93131601/201675533-82d91452-3710-4bd5-a619-46ef535a5791.png)

the horizontal line over the date and time in scrollbarX

**Comment by martynasma** [comment]
Do you mean the vertical white grid lines?

https://www.amcharts.com/docs/v4/tutorials/customizing-chart-scrollbar/#Disabling_labels_and_grid

**Comment by naveennkbk** [comment]
I cant see the option for hiding grid lines. pls help me to hide those lines

**Comment by martynasma** [comment]
Can you post your exact chart on CodePen? That might let us understand what is that you're asking.
