### ISSUE TITLE
Date axis cut 

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#4173]
Hi! I have now two parts of my chart: axis bullets on my date axis and usual series. For some reason part of the values are not shown on the chart. Last date on dateAxis is the same as last point on series, so some of my axis bullets are cut from the screen. 
As you can see on the [example](https://codepen.io/12rita/pen/Vwdzzey) my last point date is 2022-11-09 (november, 9th), but chart ends after october 13th. Should i set max date manually?

**Comment by martynasma** [comment]
Adding axis bullets does not affect its scale. Only series data does.

So you either need to add empty data points to series data, or use `max` setting of the DateAxis to specify the scale manually.

E.g.:

```
const linesData = [
    {        
        "type": 4,
        "id": "#04",       
        "date": "2022-10-05T02:32:45.000Z",
        "color": "#FFA600"        
    },
    {
       "type": 4,
        "id": "#04",    
        "date": "2022-10-13T10:22:03.000Z",
        "color": "#FFA600",      
    },
    {        
        "date": "2022-11-09T17:24:00.428Z",
    }
]
```

**Comment by 12rita** [comment]
Thanks a lot!
