### ISSUE TITLE
How to give the icon styling in tooltip in multiple series chart ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#4174]
Hi, I have multiple series activity [chart](https://codepen.io/team/amcharts/pen/KKwrmyM) like I mentioned in my previous [ticket](https://github.com/amcharts/amcharts4/issues/3651).
Instead of circle icons in tooltip I need hyphens. How to achieve it ?

**Comment by martynasma** [comment]
Just replace `●` symbol to `−` in tooltipText adapter :)

```JavaScript
text += "[" + item.stroke.hex + "]−[/] " + item.name + ": {" + item.dataFields.valueY + "}\n";
```

**Comment by VineelaKantamneni** [comment]
It's working. Thank you.
