### ISSUE TITLE
compatibility issue with google maps api cdn

### ISSUE THREAD

**Issue by lordham** [amcharts/amcharts4#4175]
There seems to be conflict with the latest google maps api cdn.

We have been using you libraries with google maps for a while, but recently our google maps seem to only be showing grey screens.

<script src="https://maps.googleapis.com/maps/api/js?key=thisisnotthekeyyoulookingfor&callback=initMap&libraries=places&v=weekly" async></script>

with
    <script src="https://cdn.amcharts.com/lib/4/core.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
       
The google map loads but only a grey screen is shown.

Running redraw/refresh scripts for the google does not update the map.

Here is the catch. 

The map works perfectly fine from within a modal. Weird right?

Creating a basic html page referencing the libraries seems to work, so 
I think there is a conflict with one of the draw events, that is preventing the map from being drawn when used on the same page with a chart implementation.

I tried changing the google api to a quarterly versioning, but that didn't seem to solve my issue.

I resolved the issue on my side by pointing to 
    <script src="https://cdn.amcharts.com/lib/version/4.10.29/core.js"></script>
    <script src="https://cdn.amcharts.com/lib/version/4.10.29/charts.js"></script>
    <script src="https://cdn.amcharts.com/lib/version/4.10.29/themes/animated.js"></script>

instead of the latest cdn version.

I just wanted to let you guys know of a possible conflict with google.

kind regards
lordham (my actual name got taken...)

**Comment by martynasma** [comment]
Yeah, it's weird. We do not interfere with any globals or prototypes. Maybe some kind of polyfill was updated, or something.

Do you perhaps have an easy repro case which we can use to test?
