### ISSUE TITLE
sometimes shows the wrong tooltip

### ISSUE THREAD

**Issue by yanmezinskiy777** [amcharts/amcharts4#4176]
![oie_4t5Ej8kLD9EK](https://user-images.githubusercontent.com/34552676/204815291-dc40fb5c-c9ca-4846-9990-0a0e6196eeea.png)
The cursor is on the yellow column but the green column tooltip is displayed. 
![Screenshot_1](https://user-images.githubusercontent.com/34552676/204841633-d940ccb6-669a-4dfe-8a0f-516bfa47c96c.png)
I tried this property but the tooltip stops working if set to false. Is it possible to make only the correct tooltip work when hovering over a column?
link to codepan:
[https://codepen.io/yanmezinskiy777/pen/gOKdorB](https://codepen.io/yanmezinskiy777/pen/gOKdorB)

**Comment by martynasma** [comment]
In amCharts 4, `maxTooltipDistance` is measured using direct distance between cursor and data item, i.e. top of the column. There's no way to implement any other measurement.

If you would consider migrating to amCharts 5, it has more control on how the distance is measured.
