### ISSUE TITLE
Calculate AxisBreak startValue and endValue dynamically

### ISSUE THREAD

**Issue by iamdcchetan** [amcharts/amcharts4#4177]
When using axis breaks in amcharts4, I am struggling to calculate the axisBreak.startValue and axisBreak.endValue to cover all types of possible data. The reasons for requiring a dynamic calculation is because of data coming from the API response which can be anywhere in the range of 1 to 10000 and the values keep changing every day.

I could not find any property which can auto calculate the start and end value of the axis break in the doc https://www.amcharts.com/docs/v4/reference/axisbreak

Is there an option to let amchart auto-calculate the start and end value of the axis break?

If not, is there a function or method recommended to calculate the start and end value of the axis break?

It is similar to https://github.com/amcharts/amcharts4/issues/2766 where there was no conclusion and https://github.com/amcharts/amcharts4/issues/3779 where the suggestion was to set the break to start from 10% and end at 85% of the largest value in the chart. I am just wondering if there is any other approach which can be used.

**Comment by martynasma** [comment]
When you mention calculating start and end for a break, what do you mean?

There's no "universal" way to calculate breaks, so it's according to your own logic.

The relative approach in #3779 makes sense, but I'm not sure what else there could be.
