### ISSUE TITLE
Timeline chart demo links are broken

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#4178]
The timeline chart demos on the website contain broken links:

https://www.amcharts.com/timeline-chart/

An example link from this page is:

https://www.amcharts.com/demos/road-chart/

But this results in a 404. The actual link needs to be changed to include the '-v4' part:

https://www.amcharts.com/demos-v4/road-chart/

**Comment by martynasma** [comment]
Thanks for the heads up! Links are fixed now.

**Comment by jbate** [comment]
Wow that was quick!
