### ISSUE TITLE
How to remove the extra space we are getting after the chart ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#4179]
Anyone please help me out to remove extra space in chart like in below screenshort
![image](https://user-images.githubusercontent.com/74599304/206702838-b0b13366-3f5a-41fd-ad3b-bbdb3c7f7d09.png)

I had tried this [solution](https://github.com/amcharts/amcharts4/issues/3785#issuecomment-926410406) instead right I used bottom but it's not working.

**Comment by martynasma** [comment]
Unless you have explicitly set `height` for the legend, or `paddingBottom` for the chart, that space is not coming from the chart.

Try using browser's DOM explorer, to see where this spacing is coming from.

**Comment by VineelaKantamneni** [comment]
It's fixed now.
Thank you.
