### ISSUE TITLE
How to stop moving the chart to right when clicking on it?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#4180]
I have two charts when I click on the slice of first chart I'll get second one.
for different slices of first chart I'll get different second charts.
I had given a equal amount of width two both charts with the help provided in this [ticket](https://github.com/amcharts/amcharts4/issues/4163)
when I keep clicking on different slices of first chart the second chart keeps changing along with changing it's moving to right too.

case 1 : When I clicked on slice for first time
![Screenshot from 2022-12-14 14-05-59](https://user-images.githubusercontent.com/74599304/207546439-fd1aca7b-8260-45f0-ba98-b50086874c3c.png)

case 2: when I clicks on slice more than 3 times.
![Screenshot from 2022-12-14 14-07-59](https://user-images.githubusercontent.com/74599304/207546931-a2f76391-db99-4992-8021-ee6601d7efe5.png)

Any help to fix this is appreciable.
Thank you.

**Comment by VineelaKantamneni** [comment]
@martynasma 
Could you please provide a solution for it.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
