### ISSUE TITLE
How to update a real-time gantt chart

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#4181]
Hi,

I am trying to create a "real-time" gantt chart but have run into two problems:

1. How to colour columns (projects) by category
2. How to update existing columns (projects)

For the first point I want to colour each bar the same if it belongs to the same project/category, however I can only see to change the colour using the columns' template adapter (below). 
 
`series.columns.template.adapter.add("fill", ...)`

This, understandably, results in all columns being coloured differently whereas I would like those from the same category to be the same. Is there an easier way?

In the case of the latter, I want to update the raw data and then call `invalidateRawData()` however it doesn't seem to work and the [documentation indicates](https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points) it only works for numeric values. Therefore, currently I am still using `addData()`. Is there a way to update a data item's dates?

**Reduced test case:**
https://codepen.io/jbate/pen/RwJzeoP

**Comment by jbate** [comment]
I think I've fixed the second part of the question above using the `beforedatavalidated` event:

```js
chart.events.on('beforedatavalidated', ev => {
      const source = [];

      ev.target.data.forEach(d => {
        // If the entry already exists, then update it and continue (so we don't add another)
        const existingCopyPos = source.findIndex(item => item.name === d.name && item.from === d.from);
        if (existingCopyPos > -1) {
          source[existingCopyPos] = d;
          return;
        }
        source.push(d);
      });
      ev.target.data = source;
});
```

**Comment by martynasma** [comment]
> In the case of the latter, I want to update the raw data and then call invalidateRawData() however it doesn't seem to work and the [documentation indicates](https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points) it only works for numeric values. Therefore, currently I am still using addData(). Is there a way to update a data item's dates?

Have you tried using `invalidateRawData()` though? DateAxis is a ValueAxis in a nutshell, ant you are using timestamps for dates. It might just work.

**Comment by jbate** [comment]
I did and it didn’t work unfortunately. There are a couple of lines in the demo that you can uncomment to test it out. 

Do you have any ideas/advice on the first part of the question around using the same colours per Y-axis line?

**Comment by martynasma** [comment]
> I did and it didn’t work unfortunately. There are a couple of lines in the demo that you can uncomment to test it out.

I don't think any more suggestions, besides using `addData()` or completely rewriting the whole of the data.

> Do you have any ideas/advice on the first part of the question around using the same colours per Y-axis line?

Your approach to refactoring data before it's loaded seems OK to me. Are you having issues with it?

**Comment by jbate** [comment]
I am happy with the loading of the data now. This seems ok to me too. Everything is working as I would expect. Thank you. 

The only issue I’m having is my first bullet point in the question:
> How to colour columns (projects) by category

My solution in the [demo](https://codepen.io/jbate/pen/RwJzeoP) results in every bar being coloured differently, however I need every bar along the same Y-axis line to be coloured the same (each Y-axis line represents a “project”). Does that make sense?

**Comment by martynasma** [comment]
OK, so what you probably need is to us an adapter to dynamically color the bars based on the actual category, not just bar index:

```JavaScript
const colorPaletteByCategory = {
	"Project 1": { hex: "#2bc6be", name: "Teal" },
	"Project 2": { hex: "#1d4f91", name: "Dark blue" },
	"Project 3": { hex: "#e63888", name: "Magenta" },
	"Project 4": { hex: "#6d2077", name: "Purple" },
	"Project 5": { hex: "#e4002b", name: "Red" },
	"Project 6": { hex: "#ff8f1c", name: "Orange" },
	"Project 7": { hex: "#af1685", name: "Raspberry" },
	"Project 8": { hex: "#ffd146", name: "Yellow" },
	"Project 9": { hex: "#426da9", name: "Light blue" },
	"Project 10": { hex: "#2197b9", name: "Sapphire" },
	"Project 11": { hex: "#007a3b", name: "Green" },
	"Project 12": { hex: "#cad03b", name: "Lime" },
	"Project 13": { hex: "#333333", name: "Black" },
	"Project 14": { hex: "#717171", name: "Gray" },
	"Project 15": { hex: "#d6d6d6", name: "Light gray" }
};

// Ideally I want this to colour the bars by category, not for each column
series.columns.template.adapter.add("fill", (fill, target) => {
	// Rotate through each colour available
	console.log(target.dataItem)
	return am4core.color(
		colorPaletteByCategory[target.dataItem.categoryY].hex
	);
});
```

**Comment by jbate** [comment]
Thanks @martynasma I can try something like that. The only problem is that I don't know the categories up front (or how many there will be). However, I can take inspiration from this... I think I can get the distinct category names from the data and then access a different index in that colour palette array for each one (cycling back round to the start again if needed). 

As it sounds like there's not a native way to solve this then let me try that. We can probably close this question now. Thanks for your thoughts.
