### ISSUE TITLE
How to add click event for each column value in XYChart

### ISSUE THREAD

**Issue by shankar5147** [amcharts/amcharts4#4182]
I want to add a click event for each column value so that I can show particular information of the column.

series.columns.template.events.on("hit", function (ev) { var data = ev.target.dataItem.dataContext; })
it's working to the column but while click on column value it's not working 

![graph](https://user-images.githubusercontent.com/43570538/207773551-3af1e57b-fc34-4d7f-bc66-94633582baa7.png)

**Comment by martynasma** [comment]
Simply set `interactionsEnabled = false` on your label bullet.

**Comment by shankar5147** [comment]
Working Thank you @martynasma
