### ISSUE TITLE
async data in tooltipHTML adapter.

### ISSUE THREAD

**Issue by sanket-thotange** [amcharts/amcharts4#4184]
**Question**
I am trying to make an API call to get additional information based on a bullet clicked for series.
If the data is available I am trying to change the tooltipHTML for series.

Is this possible currently?

**Addition Info**
*bullet for series*
```javascript
bullet.events.on('hit', (event) => {
   series.adapter.add('tooltipHTML', (text, target) => {
   // make API call and wait for data
   // here it expects to return string, but I have to wait for API response to get correct info
   });
});  
```

**Comment by martynasma** [comment]
I don't think that will work. Your API call is probably asynchronous, whereas tooltip has to have content to display right now.

I suppose something like this could work:

```JavaScript
bullet.events.on('hit', (event) => {
  series.tooltip.label.text = "";
  // make API call and wait for data
  // then set series.tooltip.label.text = loaded_data;
});  
```
