### ISSUE TITLE
Unable to disable default handleOut behaviour of Legend item

### ISSUE THREAD

**Issue by nelsontrangithub** [amcharts/amcharts4#4185]
I have a PieChart that has a selection state for each slice with the onClick event. This works fine but when the user hovers on the legend item linked to the slice and hovers away the state of the slice is set back to the default state.

I've tried setting handleOut for the legend item to false but this doesn't work. I've scanned the docs but haven't found anything.

**Comment by martynasma** [comment]
If you want to completely disable all rollover activity of the legend items, you can do this:

```JavaScript
chart.legend.itemContainers.template.events.off("over");
```
