### ISSUE TITLE
Chart infinitely switches between week and month groupIntervals

### ISSUE THREAD

**Issue by Dayo-Akinsola** [amcharts/amcharts4#4186]
**Bug description**

I have a XYChart that consists of a single LineSeries. The data provided to the series is an array of daily data points ranging from `date` to `endDate` inclusive (Jan 01 2022 to Nov 30 2022 in the CodePen below). For most date ranges the chart works as expected, but for a few the chart seems to be infinitely switching between using a week and month groupInterval. 

CodePen demo: https://codepen.io/Dayo-Akinsola/pen/qBydZRj

**Environment (if applicable)**

- amCharts version: 4.10.32

**Additional context**
So far the problem appears for the following date ranges with the settings in the CodePen:

Jan 01 2022 - Nov 30 2022
Jan 01 2022 - Nov 29 2022
Jan 01 2022 - Nov 28 2022

**Comment by Dayo-Akinsola** [comment]
@zeroin Any update on this?

**Comment by martynasma** [comment]
We're working on a fix. No ETA, yet.

**Comment by martynasma** [comment]
Fixed in 4.10.33.

## [4.10.33] - 2023-01-02

### Fixed
- `DateAxis` with data grouping enabled could go into infinite loop of switching between period in some specific data setups.
