### ISSUE TITLE
Responsive rules not working if initial dataset is empty

### ISSUE THREAD

**Issue by ismdiego** [amcharts/amcharts4#4187]
I'm working with an XYChart and I'm defining some responsive rules. One of these rules consists in hiding label axes when chart width <= 600.

The problem is if the chart initially has no data to load, the label axes are painted once the chart receives data, so the rule doesn't apply in that case. It seems like rules are applying _before_ and then axes are calculated in that particular case. I don't have this problem when graph have data from the very beginning and then I change the width. But when graphic is initially empty and width <= 600, once I have data the axes labels are painted nevertheless, ignoring the responsive rule.

I have tested this with the latest released version (4.10.32).

**Comment by martynasma** [comment]
Try calling `chart.responsive.applyRules()`. This should force responsive rules without waiting for any events like `datavalidated`.

**Comment by ismdiego** [comment]
Oh! sorry about that. I should have asked before creating a bug report.

Where should be the best place to add that applyrules() call? (taking into account this use case when sometimes the chart starts with empty data)

**Comment by martynasma** [comment]
I suppose chart's ready event should be perfect:

```JavaScript
chart.events.on("ready", function() {
  chart.responsive.applyRules();
});
```

**Comment by kmmccafferty96** [comment]
Having this exact problem with amcharts5 and there is no ready event on the chart, responsive object on the chart, or applyRules on the responsive theme. Is there a new method of doing this?

Thanks!
