### ISSUE TITLE
Routing Homepage issue

### ISSUE THREAD

**Issue by Vaibhav-143143** [amcharts/amcharts4#4188]
onSubmit(name:any ,pass:any)
  {
    if(name=="Admin" && pass=="123")
    {
    
   **this.router.navigateByUrl('/homepage');**
   
    }
    else{
      alert("Sorry Wrong Password!");
    }
  }

in above Angular code i will try to redirect after successful login to home page is not work
link redircrt in title bar but not displaying any details 
any one can help me for solving my problem

**Comment by martynasma** [comment]
How does this relate to amCharts?
