### ISSUE TITLE
Legend series visible state not updated on series show or hide

### ISSUE THREAD

**Issue by samuel-p** [amcharts/amcharts4#419]
The series visible state in a charts legend is not updated on `series.show(300)` or `series.hide(300)`.

Here is a pen, which shows the behaviour: https://codepen.io/anon/pen/LgVQjw

Series 2 is shown, but in the legend it is displayed as hidden. Series 3 is hidden, but in the legend it is displayed as shown.

**Comment by zeroin** [comment]
This is fixed in v 64 beta. Only one difference, in order for series to be initially hidden, you must set series2.hidden = true; instead of visible = false;
