### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'each')

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4190]
**Stack**

- React Typescript
- AmCharts4

[**CodeSandbox**
](https://codesandbox.io/s/beautiful-pine-zs1re0?file=/src/App.tsx)

**Console Error**
`SliceGrouper.ts:246 Uncaught TypeError: Cannot read properties of undefined (reading 'each')
    at SliceGrouper.ts:246:1
    at Object.dispatch (EventDispatcher.ts:444:1)
    at EventDispatcher.ts:346:1
    at triggerIdle (AsyncPending.ts:162:1)
    at System.update (System.ts:351:1)
    at System.ts:405:1`
    
###     **Getting Uncaught type error at sliceGrouper on amCharts 4(Consoled thrice on every re-render), for Chart Created with createFromConfig with the following config.**
    
    `{
    series: [
      {
        type: 'PieSeries',
        dataFields: { value: 'Quantity Ordered', category: 'Product Name' },
        labels: {
          text: '{category}',
          paddingTop: 0,
          paddingBottom: 0,
          fontSize: 10,
          truncate: true,
          maxWidth: 100
        },
        plugins: isSliced
          ? [
              {
                type: 'SliceGrouper',
                threshold: '5',
                groupName: 'Other',
                clickBehavior: 'break'
              }
            ]
          : []
      }
    ],
    data
  };`
  
###   **Sample Data**
  
  export const pieData = [
  { 'Product Name': 'ARO3 Lite', 'Quantity Ordered': 14.0 },
  { 'Product Name': 'ARO3 MIPS', 'Quantity Ordered': 84.0 },
  { 'Product Name': 'ARO5 MIPS', 'Quantity Ordered': 21.0 },
  { 'Product Name': 'Ace Volley 18', 'Quantity Ordered': 2115.0 },
  { 'Product Name': 'Airdrop', 'Quantity Ordered': 307.0 },
  { 'Product Name': 'Arroya Trail Shorts', 'Quantity Ordered': 134.0 },
  { 'Product Name': 'Atom Premium', 'Quantity Ordered': 154.0 },
  { 'Product Name': 'B1B Logo Beenie', 'Quantity Ordered': 24.0 },
  { 'Product Name': 'Bandana', 'Quantity Ordered': 8.0 },
  { 'Product Name': 'Breed', 'Quantity Ordered': 56.0 },
  { 'Product Name': 'Chagos', 'Quantity Ordered': 56.0 },
  { 'Product Name': 'Chino 19 Hybrid Short', 'Quantity Ordered': 66.0 },
  { 'Product Name': 'Clean Days Bagpack', 'Quantity Ordered': 24.0 },
  { 'Product Name': 'Cloth Face Covering Hooded', 'Quantity Ordered': 35.0 },
  { 'Product Name': 'Coaches Tech Jacket', 'Quantity Ordered': 46.0 },
  { 'Product Name': 'Color Block LS Rashguard', 'Quantity Ordered': 53.0 }]

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by mazhar-kv** [comment]
@martynasma , https://codesandbox.io/s/elated-mendel-5fojgf?file=/src/App.tsx

Thanks from the response. I have shared codesandbox Url above, reproducing the issue.

**Comment by martynasma** [comment]
Thanks.

You already have SliceGrouper in your JSON config. There's no need to initialize it again in code.

Everything seems to work for me if I remove this line:

```JavaScript
chart.plugins.push(new am4plugins_sliceGrouper.SliceGrouper());
```

**Comment by mazhar-kv** [comment]
> Thanks.
> 
> You already have SliceGrouper in your JSON config. There's no need to initialize it again in code.
> 
> Everything seems to work for me if I remove this line:
> 
> ```js
> chart.plugins.push(new am4plugins_sliceGrouper.SliceGrouper());
> ```

@martynasma , Can you try refreshing the code sandbox after removing slice grouper?

**Comment by martynasma** [comment]
OK, so TS does not load SliceGrouper module, if it's not used in code directly, hence the error message, when JSON parser tries to instantiate it, because it was treeshaken.

Just add some reference to SliceGrouper in the code, e.g.:

```JavaScript
// Fool the tree-shaking
am4plugins_sliceGrouper;
```

**Comment by mazhar-kv** [comment]
@martynasma , Thanks it worked for PieChart, But Column series i still have the error. 

Link to [codesandbox](https://codesandbox.io/s/elated-mendel-5fojgf?file=/src/pages/Bar.tsx)

**Comment by martynasma** [comment]
Still seeing just PieChart in your link.

**Comment by mazhar-kv** [comment]
> Still seeing just PieChart in your link.

https://codesandbox.io/s/elated-mendel-5fojgf?file=/src/pages/Bar.tsx

can you try this URL ?

**Comment by martynasma** [comment]
Same.

**Comment by mazhar-kv** [comment]
https://codesandbox.io/s/beautiful-pine-zs1re0 

try this one

forked into another library

**Comment by martynasma** [comment]
It's the same. You still have this:

```
function App() {
  return (
    <Pie
      name={"Pie"}
      valueField={"sales"}
      categoryField={"country"}
      data={pieData}
      isSliced
    />
  );
}
```

**Comment by mazhar-kv** [comment]
Can you try in incognito with https://codesandbox.io/s/beautiful-pine-zs1re0?file=/src/App.tsx

**Comment by martynasma** [comment]
OK, thanks.

You have SliceGrouper in your series configuration. It works only for PieSeries, not ColumnSeries.

**Comment by mazhar-kv** [comment]
@martynasma , thank you so much for the support
