### ISSUE TITLE
Question regarding Area Chart

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#4191]
I tried to draw an area chart but could not create it because I think it only supports DateAxis, not CategoryAxis.

My Data Structure Format 
[
    {"date":"A","visits":9},{"date":"B","visits":5},{"date":"C","visits":4},{"date":"D","visits":0},{"date":"E","visits":0},{"date":"F","visits":7}
];

Here is my code 
var chart = am4core.create("chartdiv", am4charts.XYChart);

// Add data
chart.data = [
    {"date":"A","visits":9},{"date":"B","visits":5},{"date":"C","visits":4},{"date":"D","visits":0},{"date":"E","visits":0},{"date":"F","visits":7}
];

// Create axes
let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "date";
categoryAxis.renderer.grid.template.location = 0;
categoryAxis.renderer.minGridDistance = 10;

var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

// Create series
var series = chart.series.push(new am4charts.LineSeries());
series.dataFields.valueY = "visits";
series.dataFields.dateX = "date";
series.strokeWidth = 3;
series.fillOpacity = 0.5;

I try but they always display an error.
"Data fields for series "id-127" are not properly defined"

**Comment by xorspark** [comment]
You have to use `categoryX` on your series if you're using a category X axis. `dateX` is for a date X axis.

```
series.dataFields.categoryX = "date";
```
