### ISSUE TITLE
overlapping data on x axis for line series

### ISSUE THREAD

**Issue by santosh099** [amcharts/amcharts4#4192]
We are seeing an issue for the line series, the data on the x axis is overlapping as shown in the picture below

<img width="503" alt="lineSeries" src="https://user-images.githubusercontent.com/36532294/211182227-c437d987-d7a8-4c87-864f-cd4bbed22e51.png">

We are using the version

"@amcharts/amcharts4": "^4.10.20"

We are setting the field for the X axis as below

series.dataFields.dateX = "'busDt"

lineChart.data = [{
     busDt : "01/06",
     lyValue: 927456
}]

could anyone suggest me what should be done

**Comment by martynasma** [comment]
Perhaps, you have your setting of `minGridDistance` set too low?

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by abhiseksubham** [comment]
This is only happening when the data contains 2 years i.e. from 31 dec to jan 06.

**Comment by martynasma** [comment]
> This is only happening when the data contains 2 years i.e. from 31 dec to jan 06.

It shouldn't matter.

DateAxis should be able to choose a grid/label density which does not make labels overlap.

If they do, you probably have `minGridDistance` set to a pretty low number in your code.
