### ISSUE TITLE
I want to Show Only One Balloon Text in Stack Column amchart 4

### ISSUE THREAD

**Issue by wajihasiddiquidanat** [amcharts/amcharts4#4193]
![Screenshot (98)](https://user-images.githubusercontent.com/99311188/211346338-f879b912-c75a-428b-ba94-598ea8b918e2.png)
![Screenshot (99)](https://user-images.githubusercontent.com/99311188/211346339-4adba44b-d4d8-4881-a5d1-04838290489a.png)

createSeries(seriesVal1, seriesVal3);
            createSeries(seriesVal2, seriesVal4);
            function createSeries(field, name, Total) {
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.name = name;
                series.dataFields.valueY = field;
                series.dataFields.dateX = "D";
                series.dataFields.categoryX = "FPT";
                if (DivID == 'TotalpersonalloansCCM') {
                    series.dataFields.categoryY = "SumValues3";
                }
                else {
                    series.dataFields.categoryY = "SumValues2";
                }
                series.sequencedInterpolation = true;
                series.stacked = true;
                series.text = "Total";
                series.columns.template.tooltipText = "[bold]{text}: {categoryY.formatNumber('0.00')} [/]\n[font-size:14px]{categoryX}";
                series.tooltip.getFillFromObject = false;
                series.tooltip.label.propertyFields.fill = "#000000";
                series.tooltip.label.textAlign = "middle";
                series.tooltip.pointerOrientation = "down";
                series.tooltip.background.propertyFields.stroke = "#000000";
                series.tooltip.background.fill = am4core.color("#000000");
                series.columns.template.tooltipY = 0;
                return series;

            }

here is My Code

**Comment by martynasma** [comment]
Are you also using XYCursor? If the answer is yes, then please refer to this tutorial:
https://www.amcharts.com/docs/v4/concepts/chart-cursor/#Limiting_number_of_series_tooltips

**Comment by wajihasiddiquidanat** [comment]
no, i,m not using XYCursor

**Comment by martynasma** [comment]
In that case, I'm not entirely sure I understand the question. You should already be seeing just one balloon when hovering the columns.

**Comment by wajihasiddiquidanat** [comment]
the chart shows two balloons one for seriesVal1 and one for seriesVa2 I want only one ballon on top of the column....

**Comment by martynasma** [comment]
Gotcha.

I suppose you can do it this way:

1) Add an `XYCursor`.
2) Add `tooltipText` to the topmost series only.
