### ISSUE TITLE
Multiple data in a single stacked chart

### ISSUE THREAD

**Issue by TangoPJ** [amcharts/amcharts4#4195]
Hello.
Help me please, how can I set greater than 3 companies to the single chart, I'm getting the error: `Data fields for series "id-201" are not properly defined`.

Please, look at my following example, pay attention to the 66th line, if you uncomment it you get an error as I mentioned above, what am I doing wrong?

https://jsfiddle.net/RailBatyrshin/8qy273ej/7/

**Comment by martynasma** [comment]
You have the 4th series in a variable `series4`, yet all subsequent configuration options are for `series3`, hence the error.
