### ISSUE TITLE
Display United kingdom with regions

### ISSUE THREAD

**Issue by divyalaxman** [amcharts/amcharts4#4196]
Using amchart4, I already have a working map with USA and Canada region division visible. On click it zoom in to selected region and performs some action.

 I would need to have United kingdom divided in different region like scotland tec. Tired importing the amcharts4-geodata/ukHigh, still not working.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
