### ISSUE TITLE
Cannot read properties of undefined (reading 'timeUnit')

### ISSUE THREAD

**Issue by igoriok1994** [amcharts/amcharts4#4197]
Error on latest version (4.10.33):
![image](https://user-images.githubusercontent.com/37294916/212635021-efec2d8f-ae0f-4116-a817-ccd6fdc5cd90.png)

XYChart with 3 line series.

On 4.10.27 works well:
![image](https://user-images.githubusercontent.com/37294916/212636337-76685ccf-1c13-4db9-acae-0b3b8bcd258b.png)

**Comment by martynasma** [comment]
Would you be able to share your chart code and data so that we can test it?

**Comment by ryzr** [comment]
Having the same issue, adding baseInterval fixed it for me.

```
dateAxis.baseInterval = { count: 1, timeUnit: 'day' }
```

It also went away as soon as I commented out the following:

```
dateAxis.min = this.min.getTime()
dateAxis.max = this.max.getTime()
```
