### ISSUE TITLE
Dependent package acorn showing as acorn5.5.1 is vulnerable even though the installed acorn version is 7.4.1

### ISSUE THREAD

**Issue by jerin** [amcharts/amcharts4#4198]
Dependent package acorn showing as (acorn5.5.1 is vulnerable) even thought the installed acorn version is 7.4.1

Error description :- Acorn contains an infinite loop condition in regexp.js that is triggered when handling UTF_16 surrogates while validating regular expression.

Error path amcharts4 -> static-module -> acorn

we are using an Xray scanner to find out the npm package vulnerabilities .While scanning amcharts4, it pointing acorn 5.5.1 is vulnerable even though the installed version of acorn(acorn 7.4.1) is latest. Is there any old reference exist in latest package? could you please help to fix this issue in amchart4

**Comment by Pauan** [comment]
I looked through the `package-lock.json` and all of the versions of acorn are `7.4.1`. The `package-lock.json` describes *all* of the packages, including transient and intermediary packages, so there aren't any hidden packages.

So you should check your `package-lock.json` or `yarn.lock` file to make sure that acorn is fully upgraded. Also you should delete your `node_modules` folder and run `npm install` / `yarn install` again. If that doesn't fix it, then it's probably a bug with Xray so you should report it to them.

**Comment by jerin** [comment]
Thank you
