### ISSUE TITLE
Tooltip is visible even after the visibility is set to false.

### ISSUE THREAD

**Issue by sarandeepx** [amcharts/amcharts4#4199]
I am now working on the amcharts 4. I have a three series named series1, series2 and series3. I only want series1 and series2 to visible at the initial stage and series3 has to disable. I already set the series3 visibility to false. " series3.visible = false; ". But what is the problem is that series3 tooltip is visible at the initial stage. How to rectify it?

**Comment by martynasma** [comment]
Use `hidden` instead:

https://www.amcharts.com/docs/v4/concepts/series/#Pre_hiding_series

**Comment by sarandeepx** [comment]
Thanks. That solution worked perfectly.
