### ISSUE TITLE
LineSeries with Bullets : extremly slow rendering 

### ISSUE THREAD

**Issue by ivromas** [amcharts/amcharts4#42]
When adding Bullets to LineSeries rendering lasts very long ( vs rendering of just LineSeries on same amount of data). Problem is observed when data consists of more than 400 values (for my machine)
Is this a known issue?

JSON config example (uncommented when rendering with bullets):
`            'series': [{
                'xAxis':'v1',
                'type':'LineSeries',
                'name':run_1_name,
                'stroke':'#FEB201',
                #'strokeOpacity':0,
                'tooltipText':run_1_name + ':{valueY} at {dateX}',
                'dataFields': {
                    'dateX': 'timestamp_run_1',
                    'valueY': 'run_1'
                },
                # "bullets": [{
                    # "type": "CircleBullet",
                #     'tooltipText':run_1_name + ':{valueY} at {dateX}',
                # }]
            }]`

**Comment by martynasma** [comment]
Well, it makes sense that bullets slow stuff down. When you have just line, you have one path object. When you enable bullets, you have 1+400 objects instead.

That said, while it's supposed to be slower, the chart should handle 400 bullets with reasonable grace and acceptable speed.

Did you find it to be not the case? Can you provide your full chart code so that we can test some more?

**Comment by ivromas** [comment]
The script:
`var chart = am4core.createFromConfig(data, "chartdiv", am4charts.XYChart );`
The config:
[v4-chart-bullets.zip](https://github.com/amcharts/amcharts4/files/2040861/v4-chart-bullets.zip)
It contains 1993 values. Actually it is not as big, as I typically use in my amchart-v3 graph but still it renders extremely long. When using amchart-v3 I create line graph with balloon and it renders fast enough.

**Comment by martynasma** [comment]
Thanks!

 We'll definitely check it out. Will keep you posted.

**Comment by martynasma** [comment]
We were able to considerably speed things up. As in order of magnitude faster. Chart with a lot of bullets now behaves reasonably.

The changes will be rolled into the next release later today.

That said, we won't be stopping there. Fight for performance is a never-ending battle, and we still have some ground to cover :)

We'll notify here when the new version is up.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.27](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.27) ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta27---2018-06-01))

I'm gonna close this now, but we'll still keep working on performance. Now worries there ;)
