### ISSUE TITLE
Line Series shows a sudden jump while rendering

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4201]
**Question**
There is a sudden jump of line series chart when the chart renders initially

**Environment (if applicable)**
ReactJS
I have attached the screen recording in the issue

**Additional context**

**Comment by azharakbar** [comment]
[Screen Recording 2023-01-30 at 08.27.35.zip](https://github.com/amcharts/amcharts4/files/10531797/Screen.Recording.2023-01-30.at.08.27.35.zip)

**Comment by martynasma** [comment]
This is most likely the side effect of a `sequencedInterpolation = true` on a series.

If you could provide a running CodePen or jsFiddle of your chart, we could take a look if maybe there's something else in the config that might be causing it.

**Comment by azharakbar** [comment]
Sure @martynasma 
Let me try to create a fiddle out of this
Thanks
