### ISSUE TITLE
Trouble displaying the date on the x-axis

### ISSUE THREAD

**Issue by emasys-sysadmin** [amcharts/amcharts4#4203]
I'm having trouble displaying the date on the x-axis.
With some resolutions it works perfectly, but with others it skips the date and shows it with a offset.

https://www.loom.com/share/cb14b0df2c8b4c1c93363d91f9d2cac2
![image](https://user-images.githubusercontent.com/105679639/215999778-2bf8e60f-bea1-4100-aef5-c08780ab1e2f.png)

Best regards.
Marko

**Comment by zeroin** [comment]
Here is a tutorial which explains all the locations of labels and grid of the axis:
https://www.amcharts.com/docs/v5/tutorials/location-of-items-on-date-axis-and-date-based-series/

**Comment by emasys-sysadmin** [comment]
Thank you.
This is tutorial for V5. Is it possible to do the same in V4?

**Comment by emasys-sysadmin** [comment]
> Here is a tutorial which explains all the locations of labels and grid of the axis: https://www.amcharts.com/docs/v5/tutorials/location-of-items-on-date-axis-and-date-based-series/

Thank you.
This is tutorial for V5. Is it possible to do the same in V4?

**Comment by martynasma** [comment]
Oops, sorry for the wrong link.

Please check here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/
