### ISSUE TITLE
Seeing the direct line from start point to end point | line chart

### ISSUE THREAD

**Issue by swapnilh-cognologix** [amcharts/amcharts4#4204]
This is happening only in case have data in range from December to January Data e.g 
![image](https://user-images.githubusercontent.com/49631041/216240122-1bae38a5-ff91-4aba-b1cd-b7adcb576f77.png)

![image](https://user-images.githubusercontent.com/49631041/216239933-2764394e-99e6-4a1e-b219-2a6e250424fd.png)

Using the below json to render the chart:
`[
  {
    "key": "12/28/2022",
    "val": 3190
  },
  {
    "key": "12/29/2022",
    "val": 140069
  },
  {
    "key": "12/30/2022",
    "val": 143224
  },
  {
    "key": "01/02/2023",
    "val": 87908
  },
  {
    "key": "01/03/2023",
    "val": 410141
  },
  {
    "key": "01/04/2023",
    "val": 324177
  },
  {
    "key": "01/05/2023",
    "val": 296829
  },
  {
    "key": "01/06/2023",
    "val": 301783
  },
  {
    "key": "01/07/2023",
    "val": 681772
  },
  {
    "key": "01/08/2023",
    "val": 140069
  },
  {
    "key": "01/09/2023",
    "val": 6016
  },
  {
    "key": "01/10/2023",
    "val": 143636
  },
  {
    "key": "01/11/2023",
    "val": 140069
  },
  {
    "key": "01/12/2023",
    "val": 2098702
  },
  {
    "key": "01/13/2023",
    "val": 480837
  },
  {
    "key": "01/16/2023",
    "val": 9852
  },
  {
    "key": "01/17/2023",
    "val": 841185
  }
]`
Dev Env:
"@angular/core": "^14.2.7",
"@amcharts/amcharts4": "^4.10.10",

**Comment by zeroin** [comment]
Can you show a codepen of full source of your chart? My guess that you use incorrect date format, probably YYYY instead of yyyy

**Comment by swapnilh-cognologix** [comment]
> 
Hi Zeroin,

Thanks for the quick reply,  below is the sandbox link for the same.

https://codesandbox.io/s/stoic-field-xzcghq

**Comment by martynasma** [comment]
The issue seems to be in your `formatData` function, which puts data items in incorrect order: (sorted using string comparisons, not dates)

![image](https://user-images.githubusercontent.com/1458520/216267121-a1d24399-17d3-4dfa-8383-390a4dc1c2f4.png)

The data items need to be in ascending order.

The source data seems to be already properly sorted. Do you really need to sort them again?

**Comment by swapnilh-cognologix** [comment]
> The issue seems to be in your `formatData` function, which puts data items in incorrect order: (sorted using string comparisons, not dates)
> 
> ![image](https://user-images.githubusercontent.com/1458520/216267121-a1d24399-17d3-4dfa-8383-390a4dc1c2f4.png)
> 
> The data items need to be in ascending order.
> 
> The source data seems to be already properly sorted. Do you really need to sort them again?

No need of sorting again missed somehow, removing the sorting worked for me.

But still have one doubt can you please check the below jsfiddle(JS)
https://codepen.io/swapnilh-cognologix/pen/LYBXZLy

Seeing the vertical line which is not be expected below is the screenshot.
![Line chart date format issue (1)](https://user-images.githubusercontent.com/49631041/216277746-5f52f843-6122-48df-93e9-c8b66301b466.png)

**Comment by martynasma** [comment]
Since you don't have `inputDateFormat` set in this demo, it's down to a browser to interpret the string-based dates. Most probably string like this '2023-1-1' is not being interpreted correctly.

This should fix it:

```
chart.dateFormatter.inputDateFormat = "yyyy-M-d";
```
