### ISSUE TITLE
Problem: changing background of chart

### ISSUE THREAD

**Issue by igoriok1994** [amcharts/amcharts4#4205]
How to clear chart's background?

E.g. I have chart `var chart = am4core.create("chartdiv", am4charts.GaugeChart);`:

I can set  background color:

`chart.background.fill = am4core.color('red');`

It works.

Then I want to set background image:

```
const img = new am4core.Image();
img.href = 'http://.....';
chart.background = img;
```

It also works.

Then I want to reset charts background:

`chart.background = null`

Also works...

Then I want to set background color again. How to do it?

`chart.background.fill = am4core.color('red');`

This code will not works, because I set `chart.background` to `null` before.

Is here any solution?

**Comment by xorspark** [comment]
When the chart is first instantiated, the background is a [Rectangle instance](https://www.amcharts.com/docs/v4/reference/rectangle/). You just need to recreate a new instance in order to set the fill again.

```
chart.background = new am4core.Rectangle()
chart.background.fill = am4core.color('red')
```

**Comment by igoriok1994** [comment]
Thanks. Works fine.
