### ISSUE TITLE
Legend is going out of column chart

### ISSUE THREAD

**Issue by soumyaa1804** [amcharts/amcharts4#4206]
**Question**
Hi Team, I am facing an issue. In my column chart, the legend above the column is going out of chart space and thus getting truncated. Is there any workaround to fix it?

I tried `series1.columns.template.maxHeight = 200` but it's not working.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/40785645/216808484-a685df6a-ee45-4c10-b2db-bd34c8bdb853.png">

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Please refer to the response here: https://github.com/amcharts/amcharts4/issues/2132
