### ISSUE TITLE
Label on link of force directed tree

### ISSUE THREAD

**Issue by Caterina5** [amcharts/amcharts4#4207]
version: amcharts4

similar issues: https://github.com/amcharts/amcharts4/issues/2416

This is my problem: I need to see always the tooltipText on link but I don't want the frame of text.
there is possibility to always active tooltip Text:

`series.links.template.showTooltipOn = "always";`

but with a slow animation and remains the text in frame issue. 

example: https://codepen.io/kate05/pen/yLqrmvw

I have added a node hidden to tree with the information that I have need. But the result it is not well. The link seems fractured.

exmaple: https://codepen.io/kate05/pen/ZEjNzpQ

how I can show always the tooltipText like a label on link?

**Comment by Caterina5** [comment]
There is already the label with the name under the node. I need the information location to be on the link

**Comment by zeroin** [comment]
Sorry, I don't understand. You can put anything you want in the tooltip.

**Comment by Caterina5** [comment]
I need something like this:  https://i.stack.imgur.com/P86AY.jpg

**Comment by Caterina5** [comment]
I think I have solved my problem. I have reduced the font size and tooltip animation time with:
`series.links.template.tooltipText = "[bold font-size: 10px] eth{eth}[/]";`
`series.tooltip.animationDuration = 15;`

Now the tooltip looks similar to the label. Only the frame remains.
https://codepen.io/kate05/pen/GRBVYGy

It can be removed the tooltip frame?

**Comment by martynasma** [comment]
> It can be removed the tooltip frame?

Yes:

```JavaScript
series.tooltip.background.disabled = true;
```

**Comment by Caterina5** [comment]
Thank you very much, I have got what I wanted
