### ISSUE TITLE
Able to click on Tooltip

### ISSUE THREAD

**Issue by laxmipsarva** [amcharts/amcharts4#4208]
**Question**

I was trying to click tooltip on XY Chart which is on right side of bar unable to get column information
![Screen Shot 2023-02-09 at 11 32 55 AM](https://user-images.githubusercontent.com/1643813/217918667-3a2131ce-2a92-441c-b629-b58720a9c571.png)

**Comment by martynasma** [comment]
Perhaps this will help:
https://www.amcharts.com/docs/v4/tutorials/clickable-links-in-tooltips/

**Comment by laxmipsarva** [comment]
@martynasma Thanks for help instead of href `series.columns.template.tooltipHTML = '<b>{category}</b><br><a href="https://en.wikipedia.org/wiki/{category.urlEncode()}">More info</a>';`

I tried following 
`const consoleCategory = (a) => console.log(a);
series.columns.template.tooltipHTML = '<b>{category}</b><br><a href="#" onClick="consoleCategory('{category}')">click here</a>';`

it works in codepen example dows't work in react, also tried 
`window.consoleCategory = (a) => console.log(a);
series.columns.template.tooltipHTML = '<b>{category}</b><br><a href="#" onClick="window.consoleCategory('{category}')">click here</a>';`

**Comment by martynasma** [comment]
How it doesn't work? Do you get an error?

**Comment by laxmipsarva** [comment]
> How it doesn't work? Do you get an error?

There was a typo, I did not see any error on console. After fixing typo and assigning onclick function to window variable this worked on React
