### ISSUE TITLE
Scale title text on mobile devices

### ISSUE THREAD

**Issue by lonewolf9277** [amcharts/amcharts4#4209]
**How can we scale the chart title on mobile devices?**

I have tried adding rules but can't get the title state. Just enabling responsive doesn't change text size on resize.

**I am using amCharts4**

**Comment by martynasma** [comment]
There are no built-in label size rules. You will need to add custom ones:
https://www.amcharts.com/docs/v4/concepts/responsive/#Adding_custom_rules

E.g.:

```JavaScript
//chart.responsive.useDefault = false
chart.responsive.enabled = true;

chart.responsive.rules.push({
  relevant: function(target) {
    if (target.pixelWidth <= 400) {
      return true;
    }
    
    return false;
  },
  state: function(target, stateId) {
    if (target instanceof am4core.Label) {
      var state = target.states.create(stateId);
      state.properties.scale = 1.5;
      return state;
    }
    return null;
  }
});
```

The above will scale up by 50% of all labels.
