### ISSUE TITLE
amCharts 4 dateaxis with different timezones

### ISSUE THREAD

**Issue by ashish0777** [amcharts/amcharts4#4210]
**Question**
I have used am4charts.XYChart to show time series 
![dateaxis](https://user-images.githubusercontent.com/25523728/218473907-0abb045d-2be3-41be-9bf4-714b309547a7.png)

data = [
  {
    "Date": "2022-11-13T00:50:00Z"
  },
  {
    "Date": "2022-11-13T04:58:45Z",
    "SigAvg0": "69",
    "SigMin0": "68.81",
    "SigMax0": "69.35",
    "SigSum0": "13386",
    "SigUOM0": "°F"
  },
  {
    "Date": "2022-11-13T09:07:30Z",
    "SigAvg0": "71.95",
    "SigMin0": "68.81",
    "SigMax0": "73.67",
    "SigSum0": "17555.8",
    "SigUOM0": "°F"
  },..
]

How to achieve dateAxis tooltip for different time zone if user changes timezone from user preferences settings?

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
There's no easy way to force specific time zone for just the tooltip.

Maybe something like this:

```JavaScript
var tooltipFormatter = new am4core.DateFormatter();
tooltipFormatter.timezone = "Australia/Sydney";
tooltipFormatter.dateFormat = "yyyy";

dateAxis.tooltipDateFormat = "i";
dateAxis.tooltip.label.adapter.add("textOutput", function(text, target) {
  if (text) {
    var date = tooltipFormatter.parse(text, "i");
    return tooltipFormatter.format(date, dateAxis.getCurrentLabelFormat());
  }
  return text;
});
```

Hope the code makes sense.

https://codepen.io/team/amcharts/pen/PodoPEy/dcdb23689e99b0fc0f981ce7c486c8a9?editors=0010
