### ISSUE TITLE
color with alpha doesn't take effect on 3D donut boundary

### ISSUE THREAD

**Issue by AsasinCree** [amcharts/amcharts4#4213]
please see https://jsfiddle.net/14vnt673/

In this demo, I add a color list on series with **alpha** color at the **last line code**. But the alpha doesn't apply on the **boundary** and **outline** of the chart.

If there's **other solution** to achive it, please tell me.

**Environment (if applicable)**
amCharts 4

**Comment by martynasma** [comment]
I don't think this will work like that.

The only way is to set opacity of the whole slice, using either an adapter or a property field.

```
series.slices.template.adapter.add("opacity", function(opacity, target) {
  return 0.2;
})
```

**Comment by AsasinCree** [comment]
@martynasma Thank you for quick reply. It's a good solution and I check it. However, there're small **issues** I found
- The **boundaries' color** between slices is still lack of **alpha** . 
![image](https://user-images.githubusercontent.com/18276301/219993248-31877a33-c166-4e5f-8c5a-495625c3d71b.png)
- When you **hover** on the chart, the **hovered slices** will change the color to solid color **without alpha,** is it a bug?
![image](https://user-images.githubusercontent.com/18276301/219993372-58576bfa-3c65-4ad6-acad-2ec2ec166cab.png)

**Comment by martynasma** [comment]
Well, they are not lacking alpha. However, there are two sides laid over each other, so they appear darker.

I'm not entirely sure how to go about it, frankly.

Having a chart with semi-transparent 3D slices is a bit weird.

**Comment by AsasinCree** [comment]
Thanks @martynasma. I got it. What I want is to get it prettier.
Regardless of the boundary issue, what about my **second issue**? Is there any solution for it?

**Comment by martynasma** [comment]
> When you hover on the chart, the hovered slices will change the color to solid color without alpha, is it a bug?

This can be fixed by defining opacity for the default state:

```
series.slices.template.states.getKey("default").properties.opacity = 0.5;
```

Come to think of it, you may use it in place of the previous code I sent. It's not needed if you use the above.

**Comment by AsasinCree** [comment]
Thanks a lot @martynasma. I found _only defining opacity for the default state_ won't change the **opacity** and the opacity takes effect only **after hovering the series**. **Combine your two solution code**, it'll work perfectly!

`series.slices.template.adapter.add("opacity", function(opacity, target) { return 0.5; })
series.slices.template.states.getKey("default").properties.opacity = 0.5;`
