### ISSUE TITLE
Show Or Hide Data labels with JSON config

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4215]
**Stack**

- React Typescript
- AmCharts4

[**CodeSandbox**
](https://codesandbox.io/s/beautiful-pine-zs1re0?file=/src/pages/Bar.tsx)

Can anyone help me how i can show or hide bullet labels or labels inside the graph via JSON config? 

Screenshots

<img width="964" alt="Screenshot 2023-02-22 at 9 58 40 AM" src="https://user-images.githubusercontent.com/89790843/220522368-a759b04b-52ad-4060-9b85-4ce1bdf959a1.png">
<img width="942" alt="Screenshot 2023-02-22 at 10 02 54 AM" src="https://user-images.githubusercontent.com/89790843/220522690-28d12be0-c13f-4bbb-9989-7ad1e004e31f.png">

**Comment by zeroin** [comment]
Your sandbox is not working for me. Do you need to hide them after the chart is initialized? If you don't want them at all, then just don't add them to your config.

**Comment by mazhar-kv** [comment]
@zeroin , Fixed sandbox issue, I have attached screenshots of which labels im talking about. 

I want to introduce a toggle that i can use to show or hide those labels. So how should i do that?

**Comment by zeroin** [comment]
I still don't see the charts like in your pictures in your sandbox, but anyway. You can not do this using json, but after you create a chart, you can work with it without json, so for example, if you want to hide labels of a pie chart, just do:

`chart.series.getIndex(0).labels.template.visible = false`

To hide bullets of xy series:

` chart.series.getIndex(0).bulletsContainer.visible = false`

**Comment by mazhar-kv** [comment]
Thank you :)
