### ISSUE TITLE
How to reduce the space between top and chart

### ISSUE THREAD

**Issue by AsasinCree** [amcharts/amcharts4#4216]
In **3d donut chart**, see this [demo](https://jsfiddle.net/lawrence_li/6L4we1dn/1/) I **hide the labels** and I want to reduce the **space** between **top and pie chart**.
![image](https://user-images.githubusercontent.com/18276301/220594883-b02b21e3-3ba6-4664-9f08-dee7be3e45c4.png)

I tried **margin, padding and align** but still haven't find the answer. Could you please help me?

**Environment (if applicable)**
amchart 4

**Comment by zeroin** [comment]
This should work:

`chart.radius = am4core.percent(100)`

**Comment by AsasinCree** [comment]
Thanks for quick reply @zeroin. It doesn't work if if I **increase the angle**(Sorry I fogot to declare it in my demo). Here's new [demo](https://jsfiddle.net/lawrence_li/6L4we1dn/5/), and I tried **increase the radius** but it won't get close to the top edge. Any solution for this situation?

![image](https://user-images.githubusercontent.com/18276301/220803411-b150828f-f6e1-4416-a1c9-a9c687971b61.png)

**Comment by zeroin** [comment]
Sorry, but our script does not take into account angle.

**Comment by AsasinCree** [comment]
Alright. I found a solution that set the **position** of parent container to `absolute` to reduce the space. Anyway, thank you for your inspiration @zeroin .
