### ISSUE TITLE
How to specify colorset when chart is created with Json config using createFromConfig

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4219]
**Stack**

- React Typescript
- AmCharts4

How to specify colorset when chart is created with Json config using createFromConfig for **XYChart?**

**Comment by xorspark** [comment]
As noted in the [documentation](https://www.amcharts.com/docs/v4/concepts/colors/#XY_Chart_and_derivative_charts) under the JSON tab, a colorset is defined by a `colors` object containing a `list` array:

```
// ...
  "colors": {
    "list": [
      "#845EC2",
      "#D65DB1",
      "#FF6F91",
      "#FF9671",
      "#FFC75F",
      "#F9F871"
    ]
  }
// ...
```

XY and similar charts have this defined at the top level of the chart object, whereas pie/sliced charts define it on the series itself.
