### ISSUE TITLE
How to apply NumberFormatter only on Y-axis not in X-axis

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#4222]
In my case, I want to format the Y-axis's number or value. The reason sometimes in my case I wanted to show ID which is a number they format that number to.

**Comment by xorspark** [comment]
If you want a numberformatter to only apply to a specific axis, you have to create an instance of it and assign it to an axis rather than use the chart-level one.

```
yAxis.numberFormatter = new am4core.NumberFormatter()
// make changes to yAxis.numberFormatter as appropriate
````
