### ISSUE TITLE
Amcharts render chart even if div not present with visibility:hidden that may break page layout

### ISSUE THREAD

**Issue by amanjangra3pg** [amcharts/amcharts4#4223]
The div that appears on the DOM has height and width of 200px and visibility hidden and position absolute. Since visibility hidden on an element would still take up space on DOM so it may break the layout.

JsFiddle LInk : https://jsfiddle.net/aman8842/dwfb85pk/

**Comment by martynasma** [comment]
Your example is creating a chart in a non-existing div. Is that intentional? If that is so, you should not do that.

**Comment by amanjangra3pg** [comment]
That I know but this situation came as we needed to hide and show certain charts based on some conditions, we didn't handle it correctly and the chart creation was taking place in certain situations where div was actually hidden. But at the end of the body the chart was being created and we had an empty space in the bottom of the page which when debugged we got to know that there is a chart there with visibility hidden. 

Ideally, the chart should not get rendered if the div is not present. What is the point of rendering it and then making its visiblity hidden. If that would have been display none, page layout wont get affected.

**Comment by martynasma** [comment]
I believe we don't render actual chart if it's hidden at the moment of initialization.

However, everything is still being setup, e.g. events that handle detection of container size as well as other base objects and elements.

This still requires the target container to be present when chart is being inited.
