### ISSUE TITLE
XY chart bullet labels overlapping

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts4#4224]
Hi Team,

While working on a XY chart I've noticed that if data points are close to each other labels get overlap on each other. Hence, it creates confusion and chart does not looks good. Attached is the screenshot for the same. Please have a look and suggest if anything can be done to improve the chart readability. For example, make the position of labels dynamic so that it will change it's orientation whenever any other data point comes under it.
![image](https://user-images.githubusercontent.com/96469108/224312540-48b479a2-3342-4577-a633-7ee6961c8b56.png)

**Comment by martynasma** [comment]
Perhaps you can use a an [Overlap Buster plugin](https://www.amcharts.com/docs/v4/tutorials/plugin-overlap-buster/).
