### ISSUE TITLE
In what property is value of `valueAxis.axisRange` saved?

### ISSUE THREAD

**Issue by kevinadhiguna** [amcharts/amcharts4#4225]
**Question**

```js
let charts = [];
let rate = 155;

am4core.ready(function () {
  ...
  let chart = am4core.create('amchart-first-xy-chart', am4charts.XYChart);
  let valueAxis = chart.xAxes.push(new am4charts.ValueAxis());
  let range = valueAxis.axisRanges.create();

  range.value = rate;
  range.grid.stroke = am4core.color('blue');
  ...
  charts.push(chart);

  console.log('charts[0] :', charts[0]);
});
```

I would like to get the value of `range.value` above (to modify it).
In what property of `charts[0]` is it stored?

Thanks in advance and have a good day

**Environment (if applicable)**

 - amCharts version : 4.10.18

**Comment by xorspark** [comment]
It's in your valueAxis (`chart.xAxes.getIndex(0)`) under the [`axisRanges`](https://www.amcharts.com/docs/v4/reference/axis/#axisRanges_property) property. Since it is [`ListTemplate`](https://www.amcharts.com/docs/v4/reference/listtemplate/), you can use the usual List methods to access/iterate through all of your ranges:

```
const valueAxis = charts[0].xAxes.getIndex(0)
valueAxis.axisRanges.getIndex(0).value = newValue
// ...
for (let range of valueAxis.axisRanges) {
  range.value = newValue
}
// ...
valueAxis.axisRanges.each((range) => {
  range.value = newValue
})
```

**Comment by kevinadhiguna** [comment]
Thank you kindly @xorspark !

This is a quick recap of what I am looking for : 

```js
let charts = [];
let rate = 155;

am4core.ready(function () {
  ...
  let chart = am4core.create('amchart-first-xy-chart', am4charts.XYChart);
  let valueAxis = chart.xAxes.push(new am4charts.ValueAxis());
  let range = valueAxis.axisRanges.create();

  range.value = rate;
  range.grid.stroke = am4core.color('blue');
  ...
  charts.push(chart);

  console.log('charts[0] :', charts[0]);
});

function updateChart(newRate) {
  const valueAxis = charts[0].xAxes.getIndex(0);

  // Get all axisRanges values
  // for (const range of valueAxis.axisRanges) {
  //   console.log('range.value :', range.value); // <- 10, 20, ..., 60, 70, oldRate, undefined
  // }

  // Assign a new rate
  valueAxis.axisRanges.getIndex((valueAxis.axisRanges.length)-2).value = newRate;

  // Update only changed data (learn more: https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points)
  charts[0].invalidateRawData();

  // Or one can reevaluate and update all data instead
  // charts[0].invalidateData();
}

let rate2 = 175;
updateChart(rate2);
```

**Comment by kevinadhiguna** [comment]
Hi @xorspark , sorry to bother you..

Could you please tell why you knew it was : 
`chart.xAxes.getIndex(0)` under the [axisRanges](https://www.amcharts.com/docs/v4/reference/axis/#axisRanges_property) property based on code above?

In addition, where could you find `xAxes` property documentation in https://www.amcharts.com/docs/v4/reference/tag/class/ ?
I only found `Axis` instead of `xAxes`.

Thanks in advance!

**Comment by kevinadhiguna** [comment]
Thanks a bunch @xorspark :)

One more question please
if xAxes type is List and can be retrieved using `getIndex()`, how would one get the variable with type : `Type $type.Optional` (example: https://www.amcharts.com/docs/v4/reference/bullet/#tooltip_property) ?

For example, getting tooltip from bullet?

I expect something like `getIndex()` method for tooltip : 
```js
let bullet = charts[0].series.getIndex(0).bullets.getIndex(0);
let tooltip = bullet.tooltip.getIndex(0); // <- By all means, `getIndex()` does not even exist since tooltip is not a List..
```

**Comment by xorspark** [comment]
Why would you expect `getIndex()` on a non-List type?

`$type.Optional` basically means the type is either the type defined in `<>` or it can be undefined. You just need to use `bullet.tooltip` but check whether it is undefined.

**Comment by kevinadhiguna** [comment]
Thanks a lot for explaining comprehensively @xorspark 

I had series in chart : 
```js
let series = charts[0].series.getIndex(0);
```
and this was what I was looking for : 
```js
let tooltip = series.tooltip;
```
