### ISSUE TITLE
On chart resize, Xaxis title is not center alligned

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4226]
**Stack**

- React Typescript
- AmCharts4

[**CodeSandbox**
](https://codesandbox.io/s/beautiful-pine-zs1re0?file=/src/pages/Bar.tsx)

I have created a Xychart from Json config. When i change the width of the container dynamically, Xaxis label is not center alligned. Can i fix this with config change?

Screenshots

Before Resizing.
<img width="730" alt="image" src="https://user-images.githubusercontent.com/89790843/224661871-69aeaadf-4b4f-419e-8f96-46da8b02fcc7.png">

After Resizing.
<img width="728" alt="image" src="https://user-images.githubusercontent.com/89790843/224661812-e93d9c9e-1f21-43c1-8a93-1754f0fd9ccb.png">

**Comment by mazhar-kv** [comment]
@amcharts , @martynasma , Can anyone help me out with this?

**Comment by mazhar-kv** [comment]
@martynasma , During my testing the same thing works if im increasing the width.

**Comment by martynasma** [comment]
It seems that this is being caused by `am4core.options.queue = true`.

We'll see if this is something we can fix.

In the interim, I suggest disabling this feature.

**Comment by martynasma** [comment]
Adding `isMeasured: false` to category axis line seems to fix this.

```
    xAxes: [
      {
        id: "c1",
        type: "CategoryAxis",
        dataFields: { category: "Product Name" },
        title: { text: "Product Name" },
        renderer: {
          line: {
            isMeasured: false
          },
          grid: { location: 0 },
          labels: {
            template: {
              rotation: -45,
              horizontalCenter: "right",
              verticalCenter: "middle",
              truncate: true,
              maxWidth: 100
            }
          }
        }
      }
    ],
```

I suggest using this workaround, as we are probably won't be able to roll this into the lib, given the state of life of amCharts 4.

**Comment by mazhar-kv** [comment]
Ok thank you
