### ISSUE TITLE
How to show tooltip data which is number and is not an array of objects?

### ISSUE THREAD

**Issue by kevinadhiguna** [amcharts/amcharts4#4227]
**Question**

I often see in examples that data is often in an array of objects format. Like [this one](https://codepen.io/team/amcharts/embed/ymMzvR?default-tab=result&editable=true&theme-id=dark) :

![question-material](https://user-images.githubusercontent.com/43397636/224899467-66415931-fe30-43d4-b88d-37e197e42cdf.png)

Currrently I want to assign a tooltip to the first redline in the chart below : 
  
![question](https://user-images.githubusercontent.com/43397636/224901064-58c5755e-ace9-402f-a2bb-17d17dd0aec2.png)

The code is something like this : 

```js
let charts = [];
let rate = 155;

am4core.ready(function () {
  ...
  let chart = am4core.create('amchart-first-xy-chart', am4charts.XYChart);
  let valueAxis = chart.xAxes.push(new am4charts.ValueAxis());
  let range = valueAxis.axisRanges.create();

  range.value = rate;
  range.grid.stroke = am4core.color('red');
  ...
  charts.push(chart);

  console.log('charts[0] :', charts[0]);
});
```

I guess the first redline is `valueAxis.axisRanges` (please correct me if I am wrong). 

But the code below does not display the expected outcome : 

```js
let tooltipData = {
  tooltip1: 100,
  tooltip2: '55.13%'
};

const valueAxis = charts[0].xAxes.getIndex(0);

valueAxis.axisRanges.tooltipText = '[bold font-size: 10px]{tooltipData.tooltip1} ({tooltipData.tooltip2}%)[/]';
valueAxis.axisRanges.showTooltipOn = 'always';
```

1. How do I show data in tooltip which the data is not an array of objects? (Because the `tooltipData` is an object)
2. Did I make mistake in pointing the first redline? (the first redline might not be `valueAxis.axisRanges` ?)

Any suggestion is appreciated

**Environment (if applicable)**

 - amCharts version: v4.10.18

**Comment by martynasma** [comment]
You need to add `tooltipText` directly to the grid element of the axis range, as well as create own `Tooltip` instance so it doe snot reuse the one from axis (if you have one added):

```JavaScript
range.grid.tooltip = new am4core.Tooltip();
range.grid.tooltipText = "Hello there";
```
