### ISSUE TITLE
How to show tooltip of some bullets instead of all bullets in a chart?

### ISSUE THREAD

**Issue by kevinadhiguna** [amcharts/amcharts4#4228]
**Question**

`bullet` of Line Series is defined like this : 

```js
let charts = [];

function makeLineSeries() {
  ...
  let chart = charts[0];
  let series = new am4charts.LineSeries();

  let bullet = series.bullets.push(new am4charts.CircleBullet());
  bullet.tooltipText = '{tooltipData1} {tooltipData2}';
  ...

  series = chart.series.push(series);
}

function showTooltipOnSomeBulletsOnly() {
  let bullets = charts[0].series.bullets; // <- undefined (how to get the bullets here?)
  bullets.showTooltipOn = "always"; // <- and thus, this failed
}
```

The chart looks like this : 

![image](https://user-images.githubusercontent.com/43397636/225030570-aeecf1b6-501b-4d45-a833-a33ea3a2a0ba.png)

My objective is show the tooltip of blue bullets that are placed before the first red vertical line. Is it possible to display tooltip of some bullets only and not all bullets?

**Environment (if applicable)**

- amCharts version : 4.10.18

Thanks in advance

**Comment by martynasma** [comment]
You can use `propertyFields` of the bullet to bind its `disabled` property to the values in data.

More about it:
https://www.amcharts.com/docs/v4/concepts/data/#Property_fields

Demo:
https://www.amcharts.com/demos-v4/animated-bullet-at-the-end-of-the-series-v4/

**Comment by martynasma** [comment]
You can create another bullet as `LabelBullet`.

**Comment by kevinadhiguna** [comment]
I don't get it..

In case my explanation was not clear, what I mean is how to get the bullet in line series which is defined as : 
```js
...

// Create bullet
let bullet = series.bullets.push(new am4charts.CircleBullet());

...
```

Because this one failed to get it : 

```js
let circleBullet = charts[0].series.bullet; // <- this was undefined

// I want to modify it like : 
circleBullet.propertyField.showTooltip = "showToolTip";
```

Is there any method or properties to get it?
Thank you

**Comment by martynasma** [comment]
There's no `bullet` property in series.

There are `bullets` which is a list.

```
let circleBullet = charts[0].series.bullets.getIndex(0);
```

**Comment by kevinadhiguna** [comment]
I tried : 
```js
let circleBullet = charts[0].series.bullets.getIndex(0);
```
as you suggested.

Based on https://www.amcharts.com/docs/v4/reference/series/#bullets_property, the type of bullets is ListTemplate but somehow it said :
`TypeError: Cannot read properties of undefined (reading 'getIndex')`

**Comment by martynasma** [comment]
OK, my bad:

```
let circleBullet = charts[0].series.getIndex(0).bullets.getIndex(0);
```

**Comment by kevinadhiguna** [comment]
Thanks a million @martynasma !

This one did the job : 
```js
// Get series element of the XY chart
let series = charts[0].series.getIndex(0);

// Data can be any array of objects but here is an example : 
series.data = [{
  "date": new Date(2018, 0, 1),
  "value": 450,
  "showTooltip": "always"
}, {
  "date": new Date(2018, 0, 2),
  "value": 269
}, {
  "date": new Date(2018, 0, 3),
  "value": 700
}, {
  "date": new Date(2018, 0, 4),
  "value": 490
}, {
  "date": new Date(2018, 0, 5),
  "value": 500,
  "showTooltip": "always"
}];

// Get bullets element in the series and decide to show bullet tooltip or not based on 'showTooltip' property
let bullet = series.bullets.getIndex(0);
bullet.propertyFields.showTooltipOn = 'showTooltip';
```
