### ISSUE TITLE
Chart tooltip not getting fully displayed - AM Charts 4

### ISSUE THREAD

**Issue by kenkage** [amcharts/amcharts4#4229]
It seems chart tooltip on below snapshot cannot extend outside of gridster.

I need to display entire tooltip within same width.

![image](https://user-images.githubusercontent.com/22318756/225075060-162547cc-7df1-48e8-80c6-59e93ee4814d.png)

Tried to split the layer of tooltip and chart by using **chart.tooltip.zIndex**. But no luck ⁠⁠⁠⁠⁠⁠⁠⁠😟

(NOTE: The full text of the tooltip is "Placement Ratio".)

I've implemented scenario mentioned below:
https://stackblitz.com/edit/angular-gridster2-loading-data-with-http-9thhzg?embed=1&file=app/hello.component.ts

**Comment by martynasma** [comment]
It seems that gridster add `overflow: hidden`, which effectively clips everything inside the container, including tooltips.

![image](https://user-images.githubusercontent.com/1458520/225245352-228d106e-5db4-42e9-a23c-0b4cb4934779.png)

There's nothing we can do about it. You can try overriding some CSS, e.g.:

```
#chartdiv, #chartdiv * {
  overflow: visible!important;
}
```

**Comment by kenkage** [comment]
I've updated the stackblitz repository with suggested changes but issue still persists. 😟

**Comment by kenkage** [comment]
Thanks @martynasma  for the idea. This is solved by using the approach mentioned above. 🍻
