### ISSUE TITLE
Force-directed: How to override click to toggle with another event type?

### ISSUE THREAD

**Issue by meganindya** [amcharts/amcharts4#4231]
I asked this question before for amcharts5 (https://github.com/amcharts/amcharts5/issues/835). However, that solution doesn't seem to work for amcharts4.

**Context**

I have a 2-layer deep Force-directed chart that has a set of parent nodes and each has some child nodes. In addition, the child nodes have crosslinks to other child nodes (belonging to different parent nodes).

**Question**

Is it possible to override the default "click to toggle" event with another event type? I want to toggle (show/hide child nodes) on `doublehit` and perform some other task on `hit`.

**Comment by martynasma** [comment]
I suppose you can [disable built-in toggling](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Controlling_toggling_of_nodes) of the nodes, then add your own "hit" and "doublehit" events to them.

**Comment by meganindya** [comment]
I figured that using `node.setActive(!node.isActive)` does the trick. I was trying to do that using `disabled` but that resulted in a different behavior.
