### ISSUE TITLE
Export Chart with labels

### ISSUE THREAD

**Issue by mpetrov95** [amcharts/amcharts4#4234]
I have a HorizontalBarChart that displays searched keys + frequencies. Some of the labels are too long, so we truncated them and added tooltips. Is there any way to export the chart and add the labels in original length (not truncated)?

**Comment by xorspark** [comment]
You can use the `exportstarted` and `exportfinished` events to modify the chart to look different on export. You can find more details here: https://www.amcharts.com/docs/v4/tutorials/modifying-chart-for-export/
