### ISSUE TITLE
How to find actual pixel width of a Label instance?

### ISSUE THREAD

**Issue by meganindya** [amcharts/amcharts4#4235]
In a Force-directed tree, I observed that the width values (measured width, pixel width, etc.) of a node's label all take the value of the node's circle.

Is it possible to get the actual pixel width, which may be bigger (oversize) or smaller than the circle's width?

**Comment by martynasma** [comment]
You can try `measuredWidth`.

**Comment by meganindya** [comment]
I am getting the same size as the circle.
