### ISSUE TITLE
Override Chart colorset provided in JSON config

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4236]
**Stack**

- React Typescript
- AmCharts4

[**CodeSandbox**
](https://codesandbox.io/s/beautiful-pine-zs1re0?file=/src/pages/Bar.tsx)

I have created a Xychart or PIE from Json config. Which has a colorset provided in the JSON config. How to override the existing colorset without re-rendering the entire chart. Since i have to render charts with more than 10k data points, re-rendering takes time.

**Comment by martynasma** [comment]
I suppose you can iterate through `chart.series` and apply `stroke`/`fill` manually from the new colorset.
