### ISSUE TITLE
How to filter lends on zoom

### ISSUE THREAD

**Issue by MrSerWin** [amcharts/amcharts4#4239]
Hello.
I have problem with filtering legend on zoom in or selecting range on the chart: 
1. full chart
https://monosnap.com/file/NYqtxfVaPvOn7rAZ5Lb7XvGrMBpZQT
2. zommend chart
https://monosnap.com/file/TIAMVS1OqIoanGgRyaKGA77U4QcIJ1

expected that legend have only two items "legend 1" and "legend 2" after zoom in

**Comment by martynasma** [comment]
There's no such built-in functionality, I'm afraid.

I suppose it could be implemented using X-axis `startendchanged` event, which would then analyze your data, and would iterate through `legend.itemContainers` and call either `hide()` or `show()`.

Hope that makes sense.

I don't have a ready-made example that does that though.
