### ISSUE TITLE
Scrollbar doesn't take effect on external legend container

### ISSUE THREAD

**Issue by darlesson** [amcharts/amcharts4#424]
The legend container has overflow set as suggested under [the turorial](https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/#Moving_the_Legend), but not all legend items are appearing. In the example below, it should be possible to see up to Value 15.

![image](https://user-images.githubusercontent.com/174226/46391951-43d08a80-c694-11e8-9da5-4223dc45993f.png)

https://codepen.io/team/amcharts/pen/fe940b7ba4b6b286059f431a08b161f5

**Comment by martynasma** [comment]
Found this old issue.

The tutorial since then has been updated with required workarounds to make scrollable external legend.
