### ISSUE TITLE
TreeMap disable zoom count

### ISSUE THREAD

**Issue by canesen7** [amcharts/amcharts4#4241]
Hi. I have a group like this. But I need to delete drilldown events. So, When I click the random column chart gets drilldowned. But I don't want this.
![image](https://user-images.githubusercontent.com/67913330/227935554-008de4b8-57a0-44c6-a8d6-2f8ab3d68208.png)

**Comment by martynasma** [comment]
This should do the trick:

```JavaScript
series.nodes.template.set("toggleKey", "none")
```

**Comment by canesen7** [comment]
Nah. But chart.zoomable = false is solved my issue. thanks for quick answer
