### ISSUE TITLE
How to completely hide a marker in legends?

### ISSUE THREAD

**Issue by kevinadhiguna** [amcharts/amcharts4#4243]
**Question**

Let's say, a series has no data so it is hidden. As far as I know, the example is here : https://codepen.io/team/amcharts/pen/LBjqeP, but I would like to not show the grey line (marker) even though it is already 'hidden' (`series.hidden = true`).

![how-to-completely-hide-marker-in-legends](https://user-images.githubusercontent.com/43397636/228157595-86e6ee8d-0c89-4cc9-b3d0-b95589094136.png)

Is that possible? Or is there any alternative workarounds?
Thank you in advance!

**Comment by martynasma** [comment]
You want to display markers for visible series, but hide marker for hidden series while their label is still visible?

**Comment by kevinadhiguna** [comment]
Thanks a lot, but I am sorry that turned out my question is a bit different to 'hiding a series'.

---

I have an XY chart like this which displays legends on the right side of the chart : 

![question-2](https://user-images.githubusercontent.com/43397636/228198490-1b20c26b-b345-44fd-af32-3c4bfc439642.png)

I would like to : 
1. Change the series marker (the one with '02/02 - 03/06') color from lightblue to grey, as if the series is hidden.
2. Change the label text color in the same series marker (the one with '02/02 - 03/06') from black text to grey text, as if the series is hidden.

Would that be possible? Thank you

**Comment by martynasma** [comment]
So the series is not actually hidden, but you want its marker and label to appear gray anyway?

**Comment by martynasma** [comment]
Well, the marker is constructed of multiple elements, so setting `fill` on it will not propagate further.

You can try applying a desaturate filter, though.

```JavaScript
chart.legend.events.on("datavalidated", function() {
  chart.legend.markers.getIndex(0).filters.push(new am4core.DesaturateFilter());
})
```

The above will "desaturate" the first marker in the legend.
