### ISSUE TITLE
Changing Date format with JSON config and create from config

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4244]
**Stack**

- React Typescript
- AmCharts4

[**CodeSandbox**
](https://codesandbox.io/s/beautiful-pine-zs1re0?file=/src/pages/Bar.tsx)

I have created a Xychart or PIE from Json config. 

1. How to change date format in the Xaxis?
2. How to change dateformat of slice labels in Pie chart

**Comment by martynasma** [comment]
You seem to be already using `dateFormatter.dateFormat` and in-line placeholder formatters, e.g. `{dateX.formatDate(....)}`.

You can use in-line formatting functions for PieChart, too.

```
  labels: {
    text: "{category.formatDate('yyyy-MM-dd')}",
    paddingTop: 0,
    paddingBottom: 0,
    fontSize: 10
  },
```

**Comment by mazhar-kv** [comment]
@martynasma , thank you for the quick response.

Im confused on the usage of dateFormatter, as my changes are not getting formatted with the given format throughout. 

so is your suggestion replacing the label with formatted text?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
