### ISSUE TITLE
Prevent Forced grouping of date axis

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4245]
**Stack**

- React Typescript
- AmCharts4

[**CodeSandbox**
](https://codesandbox.io/s/beautiful-pine-zs1re0?file=/src/pages/Bar.tsx)

I have created a Xychart Json config. But when i have large amounts of data, like this [Codesandbox](https://codesandbox.io/s/beautiful-pine-zs1re0?file=/src/constants.ts),

despite having week as base interval, it gets converted to years. Is there anyway i can still keep it as week, even though the data might be cluttered?

**Comment by xorspark** [comment]
You can overwrite the axis' default gridIntervals array your own to change the granularity. One example is to just provide  a single element array with just a 1 week count:

```
gridIntervals: [{ timeUnit: 'week', count: 1 }],
```

Adjust as needed.

Docs: https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Controlling_automatic_granularity_of_axis_grid

**Comment by mazhar-kv** [comment]
@xorspark , Thank you for your help, your solution worked. But since have lot of data points with zero as x axis value, the chart plots alot of empty points causing the chart to be clustered even though there is nothing to plot. 

do we have any prop that helps us trim data with zero values? or would i have to do it manually to my data?

**Comment by xorspark** [comment]
You have to manually remove zero data points from your data.
