### ISSUE TITLE
How to trim/remove whitespace area in chart where data do not exist?

### ISSUE THREAD

**Issue by kevinadhiguna** [amcharts/amcharts4#4246]
**Question**

I have an XY chart like this and would like to remove the whitespace where series (data) do not exist (the greenlined area) :

![remove-unused-space](https://user-images.githubusercontent.com/43397636/229552694-125555ef-19ef-4870-9efb-9d9bf0e546b7.png)

Is it possible ?
Thank you

**Environment (if applicable)**

 - amCharts version : v4.10.18

**Additional context**

**Comment by kevinadhiguna** [comment]
I tried :

```js
chart.paddingLeft = 0;
chart.paddingRight = 0;
```
 ```js
 chart.chartContainer.paddingLeft = 0;
 chart.chartContainer.paddingRight = 0;
 ```
 
 ```js
 chart.marginLeft = 0;
 chart.marginRight = 0;
 ```
 
```js
chart.chartContainer.marginLeft = 0;
chart.chartContainer.marginRight = 0;
```

But none of them worked

**Comment by kevinadhiguna** [comment]
Turned out I had : 

```js
...
let valueAxis = chart.xAxes.push(new am4charts.ValueAxis());

...
valueAxis.min = 100;
valueAxis.max = 300;
valueAxis.strictMinMax = true;
...
```

Then I proceed to comment them out : 

```js
...
let valueAxis = chart.xAxes.push(new am4charts.ValueAxis());

...
// valueAxis.min = 100;
// valueAxis.max = 300;
// valueAxis.strictMinMax = true;
...
```

However in this condition, should I still apply some of padding/margin right and left mentioned [above](https://github.com/amcharts/amcharts4/issues/4246#issuecomment-1494554426) (like `chart.chartContainer.paddingLeft = 0;`, etc.)?

**Comment by martynasma** [comment]
You can use `extraMax` to relatively expand the scale of an axis:
https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Relatively_expanding_the_scale

**Comment by kevinadhiguna** [comment]
Thank you for that @martynasma , but what value should I put to `extraMin` and `extraMax` to trim spaces?

I applied : 
```js
...
let valueAxis = chart.xAxes.push(new am4charts.ValueAxis());

...
valueAxis.extraMin = 0.0;
valueAxis.extraMax = 0.1;
...
```

and it looked like this:

![question-new](https://user-images.githubusercontent.com/43397636/229857028-d71b5d3a-bf8e-4b1f-9b8b-e01657704e4f.png)

The left one is already as expected, but the right one still has one grid that I want to remove.

---

After that, I changed `valueAxis.extraMax` value to -0.1.

```js
...
let valueAxis = chart.xAxes.push(new am4charts.ValueAxis());

...
valueAxis.extraMin = 0.0;
valueAxis.extraMax = -0.1;
...
```

and the series surpassed the chart which shiuld not be like that :

![question-2-new](https://user-images.githubusercontent.com/43397636/229857131-dd658248-e6d8-4ae5-ac1e-c41339d7a409.png)

**Comment by martynasma** [comment]
> Not yet successfully implemented yet, but I hope it can look like this (no extra grid before the first node and after the last node) :
> 
> ![question-2-new-expected](https://user-images.githubusercontent.com/43397636/229976691-9785b8a0-28c6-4661-80a0-00c419b76edd.png)

Well, that's how the chart SHOULD look like without any additional settings.

If it doesn't, can you post your chart on CodePen or jsFiddle so that we can take a look?

**Comment by kevinadhiguna** [comment]
Sure, the code is like this : https://codepen.io/julien-loki/pen/eYPOLbO

**Comment by martynasma** [comment]
OK, how is this not what you want?

![image](https://user-images.githubusercontent.com/1458520/230071604-23d209b8-c700-42dd-b347-7b91ba2cc3a7.png)


https://codepen.io/team/amcharts/pen/gOBYQLO/46edf48a7134bbcbb43c04d3bfe8b463?editors=0100

**Comment by kevinadhiguna** [comment]
Exactly, thanks a lot for your help!

But I wonder why in the original version, it still has one more unused grid. Although the code is 99% same as the one in Codepen.

![image](https://user-images.githubusercontent.com/43397636/230076088-1f34b647-624f-4197-a351-7c9e6a275f18.png)

**Comment by martynasma** [comment]
> I wonder why in the original version, it still has one more unused grid. Although the code is 99% same as the one in Codepen.

I certainly don't know :) Would you be able to reproduce it in the CodePen?

**Comment by kevinadhiguna** [comment]
Absolutely, here is the one in the same [Codepen](https://codepen.io/julien-loki/pen/eYPOLbO) as above :

![reproduce-unnecessary-grid-existance](https://user-images.githubusercontent.com/43397636/230424618-0dc745a1-3be7-447f-8dcd-91e2b9b50bf9.png)

Somehow grid with axis value of 275 still exists (I only changed the `chartData` variable value)

**Comment by kevinadhiguna** [comment]
Thanks a lot for your feedback, I really appreciate it
I hope I am not interrupting you in a convenient time, feel free to reply later

---

I applied `min`, `max`, and `strictMinMax` values as you recommended : 

```js
let xAxis = charts[0].xAxes.getIndex(0);

xAxis.min = 125;
xAxis.max = 265;
xAxis.strictMinMax = true;
```

but the edge values touched the border line of the chart like this : 

![image](https://user-images.githubusercontent.com/43397636/230593175-ffe9d997-9b64-4985-a629-0d16d9de23ab.png)

Meanwhile, without `strictMinMax` setting : 

```js
let xAxis = charts[0].xAxes.getIndex(0);

xAxis.min = 125;
xAxis.max = 265;
```

It would look like this : 

![image](https://user-images.githubusercontent.com/43397636/230593595-585a590b-a3fe-4332-b5bb-cdb497527c48.png)

**Comment by martynasma** [comment]
Why not use `strictMinMax = true` + `extraMin` and `extraMax` with positive values?

**Comment by kevinadhiguna** [comment]
> Why not use `strictMinMax = true` + `extraMin` and `extraMax` with positive values?

Because [the docs](https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Adjusting_scale) says : extraMin and extraMax are not compatible with strictMinMax setting set to true.

---

However, I tried : 

```js
let xAxis = charts[0].xAxes.getIndex(0);

xAxis.min = 125;
xAxis.max = 165;
xAxis.strictMinMax = true;
xAxis.extraMin = 0.025;
xAxis.extraMax = 0.025;
```

this is quite interesting as its display is quite close to what I expect : 

![right-after-chart-is-generated-2](https://user-images.githubusercontent.com/43397636/230646406-4e8ad8e7-4948-47ca-9f0d-88053ca80ed2.png)

If I extend the scrollbar manually, it will show exactly what I desire : 

![fully-extended-version](https://user-images.githubusercontent.com/43397636/230646584-d456ea60-cbf2-4378-8d22-d62cd013286f.png)

I am not sure why the scrollbar shrinked, is there any workaround to programmatically expand the scrollbar?

Thanks in advance

**Comment by martynasma** [comment]
Right, OK. My bad. Sorry.

OK, so your option is to calculate `min` and `max` to account for extra padding. Use it with `strictMinMax`.

**Comment by kevinadhiguna** [comment]
Thanks for providing that info

However, I guess it is already a bit close to what it's expected to be :

![image](https://user-images.githubusercontent.com/43397636/230761155-dacd5656-349e-45cb-b420-c85f4f731cc1.png)

How can I get the scrollbar expanded to max? Because right after the chart is produced, the scrollbar gets shrinked (Because if it's not it is perfectly what I expect)

---

This is how it looks if the scrollbar is set to the max (I did this manually but hope this can be done programmatically) : 

![image](https://user-images.githubusercontent.com/43397636/230761248-724e5197-79d1-4795-acc0-0e6c185dee44.png)

**Comment by kevinadhiguna** [comment]
Yep, codepen is same as the one above : https://codepen.io/julien-loki/pen/eYPOLbO

**Comment by martynasma** [comment]
Thank you.

I'm not getting "zoom in" in scrollbar on the CodePen. Even with "trim" checkbox checked.

How can I reproduce it?

**Comment by martynasma** [comment]
Does that work for you?

**Comment by kevinadhiguna** [comment]
> Does that work for you?

Fortunately yes, I am still not sure why the default settings still provided an extra grid but at least adding that "padding" variable did the job

![image](https://user-images.githubusercontent.com/43397636/231379209-5cc70279-c12e-4be9-94b6-825fcc2459d2.png)

Thank you for your support throughout the process, much appreciated :)
