### ISSUE TITLE
How to numberFormat with form (de-DE)

### ISSUE THREAD

**Issue by ngvtai** [amcharts/amcharts4#4249]
Hi, team
currently, i am working with amcharts 4 i am trying to re-format the number format displayed on the chart with the form NumberFormat(de-DE) on js
example 123.123,23
thank you for watching

**Comment by xorspark** [comment]
You can import the de_DE locale and set the locale on the chart object to format your numbers as documented here: https://www.amcharts.com/docs/v4/concepts/locales/

HTML:

```
<!-- other includes omitted -->
<script src="//www.amcharts.com/lib/4/lang/de_DE.js"></script>
```

JS:

```
chart.language.locale = am4lang_de_DE;
```
