### ISSUE TITLE
Ability for tooltips to follow the cursor on pie chart slices

### ISSUE THREAD

**Issue by darlesson** [amcharts/amcharts4#425]
Tooltips currently stay centralized on the slices. It would be nice to be able to have them following the cursor.

![image](https://user-images.githubusercontent.com/174226/46393089-a9bf1100-c698-11e8-9a66-6eba98a2e9b3.png)

**Comment by zeroin** [comment]
This is of course possible, you just need to set:

`pieSeries.slices.template.tooltipPosition = "pointer";`

This is Sprite's property and it can be used on any sprite.
