### ISSUE TITLE
How to properly dispose a chart (to avoid Event.Dispatcher error)?

### ISSUE THREAD

**Issue by kevinadhiguna** [amcharts/amcharts4#4250]
**Question**

I have a page in which chart is generated and the code is pretty much like this : 

```js
let charts = [];

am4core.ready(function () {
  ...
  let chart = am4core.create('amchart-first-xy-chart', am4charts.XYChart);
  chart.padding(0, 0, 0, 0);
  chart.legend = new am4charts.Legend();
  ...
  chart.scrollbarX = new am4core.Scrollbar();
  chart.scrollbarY = new am4core.Scrollbar();
  chart.cursor = new am4charts.XYCursor();

  let xAxis = chart.xAxes.push(new am4charts.ValueAxis());
  ...
  let range = xAxis.axisRanges.create();

  let yAxis = chart.yAxes.push(new am4charts.ValueAxis());
  ...

  charts.push(chart);
});

function addSeries(data) {
  let chart = charts[0];
  let series = new am4charts.LineSeries();
  series.data = data;
  
  let bullet = series.bullets.push(new am4charts.CircleBullet());
  series = chart.series.push(series);
}

addSeries(apiResponse);

function removeChart () {
  charts[0].dispose(); 
}
```

Also, I have a button to remove a generated chart but user can generate it again if he clicks generate button. The function that is triggered by the remove chart button is `removeChart()` function above.

The `charts[0].dispose()`, I guess caused the Event.Dispatcher error which should not happen (I know something is wrong with mine, but I followed the amcharts v4 docs).

**Error** : 

```
Uncaught Error: EventDispatcher is disposed
    at t._on (EventDispatcher.ts:369:10)
    at e._on (SpriteEvents.ts:104:25)
    at t.on (EventDispatcher.ts:444:15)
    at e.registerSeries (Axis.ts:1321:16)
    at e.registerSeries (ValueAxis.ts:1833:24)
    at e.setXAxis (XYSeries.ts:1518:31)
    at e.set [as xAxis] (XYSeries.ts:1504:8)
    at e.get [as xAxis] (XYSeries.ts:1537:10)
    at e.hide (XYSeries.ts:2566:26)
    at e.hideInitially (Sprite.ts:9464:10)
```

How to properly dispose a chart to avoid Event.Dispatcher error?

---

**What I have done** : 

I changed it to autoDispose, based on a [suggestion](https://github.com/amcharts/amcharts4/issues/3051#issuecomment-720480530) in same issue, but did not work as well : 

```js
...

function removeChart () {
  // -- None of them worked (both produce the Event.Dispatcher error) --
  am4core.options.autoDispose = true;
  // charts[0].dispose();
}
```

In addition, I am **not able** to [dispose all charts](https://www.amcharts.com/docs/v4/tutorials/chart-was-not-disposed/#Disposing_all_charts_at_once) since I have multiple charts on same page and this will break it : 

```js
...

function removeChart () {
  am4core.disposeAllCharts();
}
```

---

**Environment (if applicable)**

 - amCharts version: 4.10.18
 - Browser and its version
 - Related frameworks and their versions: Angular 1.7.9

**Comment by martynasma** [comment]
It doesn't look like your `removeChart()` function removes disposed chart from your `charts` array. So, if you call `charts[0].dispose()` again, you try to dispose a previously disposed chart, resulting in an error.

Why not use `am4core.registry.baseSprites` array instead?

**Comment by kevinadhiguna** [comment]
Is it like this ?

```js
...

function getChartByContainerId(id) {
  for (let i = 0; i < am4core.registry.baseSprites.length; i++) {
    if (am4core.registry.baseSprites[i].htmlContainer.id === id) {
      return am4core.registry.baseSprites[i];
    }
  }
}

function removeChart () {
  let currentChart = getChartByContainerId('amchart-first-xy-chart'); // <- Same as the one in am4core.create()
  currentChart.dispose(); 
}
```

**Comment by martynasma** [comment]
Yeah. Something like that :)

Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by kevinadhiguna** [comment]
Yep, the code is like this : https://codepen.io/julien-loki/pen/eYPOLbO

Actually in this case, I use Angular.js (not Angular) and JavaScript, so I might have some mistakes as the chart has not been displayed but the logic and config is pretty much just like in the code.

**Comment by martynasma** [comment]
Not getting an error when disposing the chart here:
https://codepen.io/team/amcharts/pen/gOBYQLO/46edf48a7134bbcbb43c04d3bfe8b463

(it's a fork of your CodePen, I just updated div ID to make it work)

**Comment by kevinadhiguna** [comment]
Thanks a lot for your time and help, much appreciated!

However, I just remembered that the Event.Dispatcher error comes after I regenrate chart.
(The flow is : Generate an XY chart according to filters -> Dispose/Remove the initially generated chart -> Change filter values then generate another XY chart in the same place)

> Change filter values then generate another XY chart in the same place

This is exactly the Event.Dispatcher error is displayed in console and new XY chart does not appear.

**Comment by martynasma** [comment]
Well, you are still using your own `charts` registry which contains disposed charts.

In your `createSeries()` function you use `charts[0]` to add series to. Since `chart[0]` contains previously disposed (and not removed) chart, it results in an error.

**Comment by kevinadhiguna** [comment]
Thank you for responding!

> Since `chart[0]` contains previously disposed (and not removed) chart, it results in an error.

Why is it not removed after being disposed?
How do I remove a chart after disposing it?

**Comment by martynasma** [comment]
> Why is it not removed after being disposed?

Well, it's your variable. So you're responsible of adding and removing stuff there ;)

https://stackoverflow.com/a/5767357/634045

**Comment by kevinadhiguna** [comment]
I got it, so I have to make the `charts` array empty, so it can be used to generate another chart and store data/properties of it.

```js
...

function disposeChart() {
  charts[0].dispose();
  
  // Clear charts array so it can be used for another generated chart
  charts.length = 0;
}
```

---

> https://stackoverflow.com/a/5767357/634045

If the array is like : 
```js
let numbers = [5, 3, 1];
```
It would not be hard to select element of `numbers` array, such as `let index = numbers.indexOf(3);`.

However, how does this apply to the `charts` array? May I know the element name of chart in the `charts` array?
Thanks in advance, I appreciate your time :)

**Comment by martynasma** [comment]
I don't know how else to say it. `charts` is a variable you invented and created, so it's your call how to add and remove stuff to it :)

If you want a charts array that get their disposed members removed automatically, use `am4core.registry.baseSprites`. (just don't add anything to it)

**Comment by kevinadhiguna** [comment]
Sorry for that, I managed to remove it with `charts.length = 0`;

> If you want a charts array that get their disposed members removed automatically, use am4core.registry.baseSprites. (just don't add anything to it)

Just like mentioned here : https://www.amcharts.com/docs/v4/tutorials/chart-was-not-disposed/#Auto_disposing_charts
When is it removed automatically? 

Because it also says : 
> Instead of disposing the charts with your own code...
