### ISSUE TITLE
Generate SVG from Backend Server running on Python.

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4251]
Is there a way in Amcharts 4, where can generate an SVG of chart from Backend Server running on Python. 

My objective is to generate a PPT or PDF from a Backend thats fully built for chart generation based with Amcharts 4 JSON createFromConfig

**Comment by martynasma** [comment]
I suppose you can run Selenium in Python:
https://medium.com/jaanvi/headless-browser-in-python-9a1dcc2b608b

And you can use Selenium to run web pages with charts and generate a PDF output:
https://www.amcharts.com/docs/v4/tutorials/automating-report-generation-using-selenium-webdriver/

**Comment by mazhar-kv** [comment]
@martynasma , Thank you for the quick response
