### ISSUE TITLE
Is there an option to generate a chart sprite object without rendering the chart in DOM

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4253]
Is there an option to generate a Chart sprite object without rendering the chart in DOM, using React Js and createFromConfig. 

My objective is to create the chart independent of browser. Possibly in a worker.

**Comment by mazhar-kv** [comment]
@martynasma , is there anyway i can Generate a chart object in a different thread than the current one?

**Comment by martynasma** [comment]
Nope. That won't work. You can't send functional objects like amCharts between workers.

Are you perhaps looking of a way to render a chart on server? You can use Selenium for thathttps://www.amcharts.com/docs/v4/tutorials/automating-report-generation-using-selenium-webdriver/:

**Comment by martynasma** [comment]
ColumnSeries with 10k columns sounds like a lot. And frankly no individual column will be visible to the user.

Why not use StepLineSeries instead?
