### ISSUE TITLE
XY chart with a single 1 value

### ISSUE THREAD

**Issue by pierrdu** [amcharts/amcharts4#4255]
When displaying a rather simple xy chart (months of the year vs number of items) with a single month counting 1 item, I get two lines 1.0 
on the y-axis and the column reaches the second one.
amcharts4 version 4.10.35
See https://www.galerie-insecte.org/galerie/annee.php?tax=Acromis+sparsa for an example.

I think this is a (little) bug.

**Comment by martynasma** [comment]
You have this in your code:

```JavaScript
valueAxis.numberFormatter = new am4core.NumberFormatter();
valueAxis.numberFormatter.numberFormat = "#."; 
```

This means that numbers are rounded to integers.

Try this:

```JavaScript
valueAxis.numberFormatter = new am4core.NumberFormatter();
valueAxis.numberFormatter.numberFormat = "#.#"; 
```

Or if you want only integer grids/labels shown:

```JavaScript
valueAxis.maxPrecision = 0;
```

**Comment by pierrdu** [comment]
Hello,

Thanks for your suggestions. It worked.

Le mardi 11 avril 2023, à 18:10, vous écriviez :

MM> You have this in your code:

MM> ```JavaScript
MM> valueAxis.numberFormatter = new am4core.NumberFormatter();
MM> valueAxis.numberFormatter.numberFormat = "#."; 
MM> ```

MM> This means that numbers are rounded to integers.

MM> Try this:

MM> ```JavaScript
MM> valueAxis.numberFormatter = new am4core.NumberFormatter();
MM> valueAxis.numberFormatter.numberFormat = "#.#"; 
MM> ```

MM> Or if you want only integer grids/labels shown:

MM> ```JavaScript
MM> valueAxis.maxPrecision = 0;
MM> ```




-- 
Bien à vous
Pierre Duhem
***@***.***
