### ISSUE TITLE
How to only display tooltips of particular part in a stacked serie?

### ISSUE THREAD

**Issue by kevinadhiguna** [amcharts/amcharts4#4256]
**Question**

I have an XY chart with stacked series like this : 
 
![image](https://user-images.githubusercontent.com/43397636/232469527-14ef20b5-2608-4b2f-8f74-b90f65f48866.png)

If I hover the second last (from right), tooltips of all parts of the serie appers. 

How to only display tooltips of particular part if it is hovered, in a stacked serie like that?

Thank you in advance

---

Edit : 

My expectation is pretty much like this if I hover on red part (it only displays its tooltip, rather than all tooltips) : 

![image](https://user-images.githubusercontent.com/43397636/232483162-0c114f41-b6b2-44b3-981b-b389c96abfdc.png)

**Comment by zeroin** [comment]
To do this, you should set `tooltipText` not on the series tooltip but on the `series.columns.template` instead. And you don't need to create a tooltip for your series at all.

**Comment by kevinadhiguna** [comment]
Thank you for quick response I guess it is more related to `series.columns.template.showTooltipOn`, rather than `tooltipText`.

However, this does not affect anything since `hover` is the default behavior : 
```
series.columns.template.showTooltipOn = 'hover';
```

**Comment by zeroin** [comment]
Could you create a codepen of your example, I could modify it then.

**Comment by zeroin** [comment]
You codepen was not working because you set field names with first uppercase letter, while your fields in data are all lowercase. And to do the trick, you had to set cursorTooltipEnabled:false for the series:

**Comment by kevinadhiguna** [comment]
That worked splendidly, thanks a ton!
