### ISSUE TITLE
Sankey chart layout incorrect

### ISSUE THREAD

**Issue by smallbear5353** [amcharts/amcharts4#4257]
Different layout for sankey chart between am4 and am5. 

Sample Data:

```
{ "from": "A", "to": "C", "value": 10 },
{ "from": "A", "to": "B", "value": 8 },
{ "from": "B", "to": "C", "value": 4 },
{ "from": "C", "to": "D", "value": 3 },
{ "from": "D", "to": "E", "value": 5 }
```

Code pen for amcharts4 (B-> C is inversed): https://codepen.io/Wesley-Chew/pen/GRYWYPG 

Code pen for amcharts5 (expected layout): https://codepen.io/Wesley-Chew/pen/LYgWgML

Is this an inherent issue with am4charts? Can I have the same layout as amcharts5 demo but on version4?

**Comment by martynasma** [comment]
I'm afraid we won't be able to change layout logic in amCharts 4 because it is nearing its EOL.

Please consider using amCharts 5.
