### ISSUE TITLE
Legends are not Exported

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4262]
Amcharts 4,
React JS

Im using JSON config to generate charts.

Im trying to export an svg using getSvg function. ( chart.exporting.getSVG('svg', {}, false);)  But External Legends are not exported.  Am i doing anything wrong here? can some help me figure out why?

```
chart.exporting.extraSprites.push({
              sprite: legendContainer,
              position: 'bottom',
              marginTop: 20
            });
      
 svgImg = await chart.exporting.getSVG('svg', {}, false);
```

**Comment by martynasma** [comment]
Please refer to this:
https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/#Including_external_legend_in_export

**Comment by mazhar-kv** [comment]
@martynasma , 

as you can see from the code snippet i shared above, I did refer the document you shared and followed the same procedure. But for some reason its not working for me.

**Comment by mazhar-kv** [comment]
Hi @martynasma , 

You can refer to https://codesandbox.io/s/beautiful-pine-zs1re0?file=/src/App.tsx. 

I have generated an svg and rendered it below the chart. as you can see the legends are not appended.

**Comment by martynasma** [comment]
Gotcha. Sorry, somehow it slipped. Unfortunately, including extra items into SVG export will not work, as there's no good way to concatenate multiple SVGs. It will work only for exporting to bitmap image formats. Sorry.
