### ISSUE TITLE
Is there a way to set the x-Axis serie or line to touch the bottom if data is empty?

### ISSUE THREAD

**Issue by kevinadhiguna** [amcharts/amcharts4#4263]
**Question**

I have a graph that is displayed like this currently :

![current-zero-section-touch-down](https://github.com/amcharts/amcharts4/assets/43397636/4bd6a6b8-271e-4fdc-b644-9c47cf2cfdfc)

I would like to display draw the serie or line like this :

![expectation-zero-section-touch-down-2](https://github.com/amcharts/amcharts4/assets/43397636/9470e4c4-2763-4cbf-add9-cf814e85b72c)

Basically, the sections in x-Axis who have no data (such as 165, 175, 185, 205, 215, etc.) have line touched into it.
Is there a way to accomplish this?

Thank you in advance

**Environment (if applicable)**

amcharts: v4.10.18

**Comment by martynasma** [comment]
There's no other way to do that except to add zero values to the data for the missing days.
