### ISSUE TITLE
Adjacent slices are of the same color

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4266]
Stack:
Amcharts 4
React JS

CodePen: https://codesandbox.io/s/mystifying-rui-pjdkgi?file=/src/constants.ts

Question: 
Why two adjacent slices are of the same color? 
I have used Slice grouper. The slice with Others and the one next two it are of the same color.

Also how to format Date Piechart labels when slice grouper is enabled.

**Comment by martynasma** [comment]
I'm not entirely sure what's going on in your React app. Would you be able to post a standalone chart on CodePen?

**Comment by mazhar-kv** [comment]
@martynasma , I have cleaned the Code and Here is the sandbox link https://codesandbox.io/s/mystifying-rui-pjdkgi?file=/src/pages/Pie.tsx

**Comment by martynasma** [comment]
Thank you.

I can see you have 400+ items in your series data, most of which have zero value.

PieSeries does not display zero-value slices anyway, so I suggest removing that from data.

It will not only fix color issue, but will also improve performance and data overhead for users to load.

**Comment by mazhar-kv** [comment]
@martynasma , I removed data items with zero as value. But the issue still persist for me. I have updated the Code sandbox.

**Comment by mazhar-kv** [comment]
@martynasma , Im formatting my Date Labels, but When we use Slice grouper with Groupname Other.  other is also tried to format, but since it doesn't have a date, Its displayed as empty. Is there a workaround for the same?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
