### ISSUE TITLE
id is not set when use the image in force direction chart

### ISSUE THREAD

**Issue by SeyedMostafaHosseinian** [amcharts/amcharts4#4267]

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by martynasma** [comment]
No, but you can set `id` property of the element as well as `am4core.options.autoSetClassName = true`.

This way, it will receive a class name `amcharts-[id]`.

E.g. for force-directed nodes:

```JavaScript
networkSeries.nodes.template.propertyFields.id = "name";
```

All nodes will now have class name set with their name, e.g. `amcharts-Core`.

More info:
https://www.amcharts.com/docs/v4/concepts/data/#Property_fields
https://www.amcharts.com/docs/v4/tutorials/chart-element-class-names-and-css/#Enabling_class_names
