### ISSUE TITLE
Why border color not updating properly on hover of PieChart slices?

### ISSUE THREAD

**Issue by zafarn8** [amcharts/amcharts4#4269]
Stack:
Amcharts 4

CodePen:  [https://codepen.io/zafar/pen/xxyaOQd](url)

https://codepen.io/zafar/pen/xxyaOQd
<img width="327" alt="border issue" src="https://github.com/amcharts/amcharts4/assets/25639232/dee54e60-ef3f-4406-8883-914ffd07abc2">
<img width="340" alt="left border issue" src="https://github.com/amcharts/amcharts4/assets/25639232/cfe44198-d5e4-4e59-815b-af149ac48ee2">
<img width="364" alt="working border" src="https://github.com/amcharts/amcharts4/assets/25639232/3dcfe935-4b0c-47c7-bd51-1f682bc58d46">

Question:
Why border color not updating properly on hover of PieChart slices?

Description:
As you can see in codepen I have a PieChart I added code there when user hover to the any slice border of that slice should change to white color. But, its not working as expected its only updating color for one slice and for remaining two not working properly. I am struggling in this from last two days and checked over library and other forum as well not get much help. Can you please guide me where can we do the improvement in code so that it should work properly.

adding screenshot for reference.

thanks,

**Comment by zeroin** [comment]
This happens because of the order of slices. You should bring the hovered one to front:

```
pieSeries.slices.template.events.on("over", function(e){
  e.target.toFront()
})
```

**Comment by zafarn8** [comment]
thank you, now its working as expected.
