### ISSUE TITLE
Why fillOpacity is not working for PieChart slices?

### ISSUE THREAD

**Issue by zafarn8** [amcharts/amcharts4#4271]
Stack:
Amcharts 4

CodePen: https://codepen.io/zafar/pen/xxyaOQd

Question:
Why fillOpacity is not working for PieChart slices? 
Description:
I have a PieChart in that I added colors for every slices and want to add opacity to that colors. I added below code for adding the opacity but its not working!

`pieSeries.slices.template.fillOpacity = 1;`

It's only working when user hover to any slice. You can see in the codepen. I added the event when user hover to slice that time also opacity should be the same, In this case its working. But for initial render its not applying. Do I need to add something more there?

**Comment by martynasma** [comment]
`fillOpacity = 1` means fully opaque. It's a default setting.

If you need slices to be transparent, the `fillOpacity` value should be less than 1.

**Comment by martynasma** [comment]
I must be missing something. Slices are fully opaque for me, both when idle and when hovered on.
<img width="510" alt="chrome_2023-05-18_19-51-23" src="https://github.com/amcharts/amcharts4/assets/1458520/2da2d914-aabb-477e-8927-eda8c922841a">
<img width="510" alt="2023-05-18_19-51-31" src="https://github.com/amcharts/amcharts4/assets/1458520/203bae9e-aafa-40ae-915c-38c724c2d70e">

**Comment by zafarn8** [comment]
but for me they look different.!! :(

<img width="490" alt="without hover" src="https://github.com/amcharts/amcharts4/assets/25639232/3a9432ac-02d0-4bea-95da-ac770f54e53e">
<img width="380" alt="with hover" src="https://github.com/amcharts/amcharts4/assets/25639232/dac1ecda-cbfd-484b-af63-94af0b88c01d">

**Comment by zafarn8** [comment]
can't we add color for a slice like this `rgba(77, 183, 246, 1)` ?

**Comment by martynasma** [comment]
> but for me they look different.!! :(

The colors of the fill are identical. Even in your screenshots.

Or do you mean the white border that appears on hovered slice?

> can't we add color for a slice like this `rgba(77, 183, 246, 1)` ?

Yes:
https://www.amcharts.com/docs/v4/concepts/colors/#Creating_color_object
https://www.amcharts.com/docs/v4/concepts/colors/#Pie_and_similar_sliced_charts

**Comment by zafarn8** [comment]
> Or do you mean the white border that appears on hovered slice?
no not border color. I am asking about slice color only with opacity.

Can we have option to add properties to slices like we have in css? e.g: background-color: blue, background: ... , background-repeat-x: no-repeat; like this.!
