### ISSUE TITLE
Scroll behaviour - scroll without slider

### ISSUE THREAD

**Issue by akash-pal** [amcharts/amcharts4#4274]
**Question**

The current scroll bar implementation requires the user to grab the scroll bar.

This is the current styling of the scroll bar
```
touch-action: none; user-select: none; -webkit-user-drag: none; cursor: -webkit-grab;
``` 

Instead of grabbing the scrollbar to scroll can the user scroll over the chart itself ?

This is an example of scrollbar implemented in series bar chart

https://stackoverflow.com/questions/54218041/how-to-implement-amchart-stacked-columns-chart-scrollable 

https://codepen.io/Akash-Pal-the-selector/pen/mdzaVRp

**Environment (if applicable)**

**Additional context**

Using the `chart.mouseWheelBehavior = "panX";` mouse wheel over the chart works.
Similarly can the touch scroll work ?

**Comment by zeroin** [comment]
In v4, you can enable panning by adding chart cursor and setting it's behavior to panX:

```
  chart.cursor = new am4charts.XYCursor();
  chart.cursor.behavior = "panX"
```
