### ISSUE TITLE
Specifying start of a week in JSON config

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4275]
Stack
Amcharts 4
React JS

Codesandbox : https://codesandbox.io/s/happy-galileo-huqtl0?file=/src/constants.ts

As you can see, even though My data starts from 02/January/2022, chart gets plotted from December last week 2021. I assume Week doesnt start from Monday. 

How to specify start of a week in Json config

Also how to specify timezone in JSON config?

**Comment by martynasma** [comment]
> How to specify start of a week in Json config 
> Also how to specify timezone in JSON config?

```
dateFormatter: {
  firstDayOfWeek: 0,
  timezone: "Australia/Sydney"
}
```

**Comment by mazhar-kv** [comment]
@martynasma 

https://codesandbox.io/s/happy-galileo-huqtl0?file=/src/constants.ts:868-918

I have updated the timezone to UTC and firstDay of the week as 0 (for sunday). But i dont have a date from 2021, yet i have two weeks plotted in My graph.

**Comment by mazhar-kv** [comment]
also another doubt i hav is that, tooltip shown is for a particular date, but actually the data point is plotted between a range. Is there anyway i can show the tooltip with the range?

**Comment by martynasma** [comment]
If you are using UTC timezone, it's best to use `utc` setting instead of `timezone`:

```
dateFormatter: {
  firstDayOfWeek: 0,
  //timezone: "UTC"
  utc: true
},
```

One other thing to consider is that when counting which week belongs to which year, we look at Wednesday of that week. For the week of 2022-01-02 that falls to 2021, hence "Week 52", instead of "Week 1".

**Comment by martynasma** [comment]
I don't think so. Because then you'd have two "Week 1" for 2023.

I just suggest using different codes for year format:

```
dateFormats: {
  day: "dd-MM-yyyy",
  week: "'WK ' ww-YYYY"
},
periodChangeDateFormats: {
  day: "dd-MM-yyyy",
  week: "'WK ' ww-YYYY"
},
```

**Comment by mazhar-kv** [comment]
Can you let know What is the difference? 

anyways as your suggestion for weeks, if i want to show it as week 1 then it should be after first wed. Am ii right?

**Comment by martynasma** [comment]
Yes, I suppose.

Now that I'm thinking about it, the code which determines week number does not take `firstDayOfWeek` into account. And frankly, I'm not entirely sure if it should. This would create different numbering of weeks for everyone.

**Comment by mazhar-kv** [comment]
ok. Thank you @martynasma. 

Also one more thing is there a way i can show it not as range. eg: 

if i have data for Wk-01 then the value is plotted between wk-01 and wk-02. How to plot the data point on the same line as x axis point ?

**Comment by martynasma** [comment]
You can set the `location` setting on various elements, like grid and labels.

More information here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Positioning

**Comment by mazhar-kv** [comment]
@martynasma , 

Thank you.
