### ISSUE TITLE
amChart4 display a block for one state and displaying full chart on refresh

### ISSUE THREAD

**Issue by sarahFarjallah** [amcharts/amcharts4#4276]
My question here is that I'm trying to create an amhcharts4 map in my screen where it takes multiple inputs such as filter and date calendar and whenever i change i need to redraw my chart with the new data.

it works fine the first time i change a filter however on the second time it display a block of one state.
if i try the same filter the third time it works.

I tried to research this issue but it doesn't seem a known issue.

I'm using ReactJS 
whenever i fetch the data im rerendering the map with new data

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
