### ISSUE TITLE
Can not get apostrophe in amcharts4 word cloud

### ISSUE THREAD

**Issue by DeeshanSharma** [amcharts/amcharts4#4279]
**If the text includes apostrophe words like don't, brother's the rendered word cloud splits everything after an apostrophe for eg: don't becomes don & t, brother's becomes brother & s, which is not what I expect it to be I want to show it as it is exactly**

**And if I add don't to the excludeWords array it is still showing in the word cloud as don & t, and this issue is with most of the special characters**

**Environment (if applicable)**
 - amCharts version: 4.10.35
 - angular version: 8.2.14

Please let me know if I am going wrong somewhere
 
![actual issue](https://github.com/amcharts/amcharts4/assets/42265709/b532b915-1f24-420a-91d0-ff84d6338edb)
![splited word](https://github.com/amcharts/amcharts4/assets/42265709/5751c0e0-8864-4aec-ab64-9bbdc3e84142)

**Comment by DeeshanSharma** [comment]
> I'm afraid word parser treats apostrophe as a quote which is a word breaker.
> 
> There's no way to make `don't` to be count as a single word.
> 
> The only workaround would be to implement your own word parser, and pass in data as words:
> 
> https://www.amcharts.com/docs/v4/chart-types/wordcloud/#Using_structured_data

So can you guide me through the whole process or if you have any sample code like what all things word parser is responsible for or anything that might help

**Comment by martynasma** [comment]
You can start with our built-in parser function, and modify it as needed:
https://github.com/amcharts/amcharts4/blob/master/src/.internal/plugins/wordCloud/WordCloudSeries.ts#L1170

Hope that helps.
