### ISSUE TITLE
Multi-line date formatting of a date axis

### ISSUE THREAD

**Issue by Logikgate** [amcharts/amcharts4#4281]
**Question**
Is it possible to have a date axis show the dates in a multi-line format?  Below is an example of what I'm trying to do. The red text is what I'm trying to add to my existing date axis.

<img width="232" alt="Screenshot 2023-06-01 at 9 20 08 PM" src="https://github.com/amcharts/amcharts4/assets/2379994/028795c0-e93f-4efb-aa83-3b057af495f3">

**Environment (if applicable)**

**Additional context**

**Comment by xorspark** [comment]
You can modify the `dateFormats` and `periodChangeDateFormats` keys to include a newline in the text and use inline formatting to style as needed. For example:

```
dateAxis.dateFormats.setKey("day", "[red font-size: 12px]EEE[/]\nMMM dd");
dateAxis.periodChangeDateFormats.setKey("day", "[red font-size: 12px]EEE[/]\nMMM dd");
```

Docs:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Setting_date_formats
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Visual_formatting
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-date-time/#Format_codes

**Comment by Logikgate** [comment]
@xorspark Thank you! I knew about that api I just didn't expect to be able to put things other than date formats in it 😅
