### ISSUE TITLE
Export options configured but not displayed

### ISSUE THREAD

**Issue by VT-hash** [amcharts/amcharts4#4283]
I have the following config for the export menu for XY charts (with multiple lines).
```javascript
      chart.exporting.menu = new am4core.ExportMenu();
      chart.exporting.menu.items = [
          {
              label: "<i class='fa fa-download'></i>",
              menu: [
                  {
                      "label": "Image",
                      "menu": [
                          { "type": "png", "label": "PNG" },
                          { "type": "jpg", "label": "JPG" },
                          { "type": "svg", "label": "SVG" },
                          { "type": "pdf", "label": "PDF" }
                      ]
                  }, {
                      "label": "Data",
                      "menu": [
                          { "type": "json", "label": "JSON" },
                          { "type": "csv", "label": "CSV" },
                          { "type": "xlsx", "label": "Excel" },
                          { "type": "html", "label": "HTML" },
                          { "type": "pdfdata", "label": "PDF" }
                      ]
                  }, {
                      "label": "Print", "type": "print"
                  }
              ]
          }
      ];
```

Notice that the labels for the export menu are:
- Image
- Data
- Print

All the export menu labels are displayed correctly in most cases, but there are certain cases where the `Data` label becomes missing from the export menu with this same config. 

![image](https://github.com/amcharts/amcharts4/assets/82308558/77a70921-6bdb-454e-a861-1b1099620743)

In what scenarios does the `Data` label get removed from the export menu?

**Comment by xorspark** [comment]
The Data label doesn't appear for charts that don't have the `data` property set at the chart object level. If you're using charts that don't need to set data on the chart object (maps, gauge, venn, for example) or if you only data set at the series level, then the option will not appear. If you only have series-level data, you'll need to use the `data` adapter to provide the data to be exported. We have an example of this here: https://www.amcharts.com/docs/v4/tutorials/combining-local-data-from-multiple-series-for-export/

**Comment by martynasma** [comment]
@VT-hash  Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
