### ISSUE TITLE
Is there a way to center label in nested donut chart.

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#4285]
I share example code

`// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("chartdiv", am4charts.PieChart);

// Let's cut a hole in our Pie chart the size of 40% the radius
chart.innerRadius = am4core.percent(40);

// Add data
chart.data = [{
  "country": "Lithuania",
  "litres": 501.9,
  "bottles": 1500
}, {
  "country": "Czech Republic",
  "litres": 301.9,
  "bottles": 990
}, {
  "country": "Ireland",
  "litres": 201.1,
  "bottles": 785
}, {
  "country": "Germany",
  "litres": 165.8,
  "bottles": 255
}, {
  "country": "Australia",
  "litres": 139.9,
  "bottles": 452
}, {
  "country": "Austria",
  "litres": 128.3,
  "bottles": 332
}, {
  "country": "UK",
  "litres": 99,
  "bottles": 150
}, {
  "country": "Belgium",
  "litres": 60,
  "bottles": 178
}, {
  "country": "The Netherlands",
  "litres": 50,
  "bottles": 50
}];

// Add and configure Series
var pieSeries = chart.series.push(new am4charts.PieSeries());
pieSeries.dataFields.value = "litres";
pieSeries.dataFields.category = "country";
pieSeries.slices.template.stroke = am4core.color("#fff");
pieSeries.slices.template.strokeWidth = 2;
pieSeries.slices.template.strokeOpacity = 1;

// Disabling labels and ticks on inner circle
pieSeries.labels.template.disabled = true;
pieSeries.ticks.template.disabled = true;

// Disable sliding out of slices
pieSeries.slices.template.states.getKey("hover").properties.shiftRadius = 0;
pieSeries.slices.template.states.getKey("hover").properties.scale = 0.9;

// Add second series
var pieSeries2 = chart.series.push(new am4charts.PieSeries());
pieSeries2.dataFields.value = "bottles";
pieSeries2.dataFields.category = "country";
pieSeries2.slices.template.stroke = am4core.color("#fff");
pieSeries2.slices.template.strokeWidth = 2;
pieSeries2.slices.template.strokeOpacity = 1;
pieSeries2.slices.template.states.getKey("hover").properties.shiftRadius = 0;
pieSeries2.slices.template.states.getKey("hover").properties.scale = 1.1;`

what I want for the last series labels should display as usual but for the inner series label shows on the slices.

<img width="304" alt="image" src="https://github.com/amcharts/amcharts4/assets/48621208/780a7324-8cb0-4b76-a620-668fad1b134b">

In the above pic don't care about last series but focus on inner series.

<img width="536" alt="image" src="https://github.com/amcharts/amcharts4/assets/48621208/8c55f34f-29c8-4ea7-ba0a-f45ac1ac6cd7">

I want to apply on this for inner series label or percentage show that which label occupies how much area example 23% like that

**Comment by xorspark** [comment]
Please refer to this tutorial on how to place labels inside the slices: https://www.amcharts.com/docs/v4/tutorials/labels-inside-pie-chart-slices/

You need to apply this to the first (inner) series and adjust the radius settings as needed.

**Comment by Swaraj55** [comment]
Thanks
