### ISSUE TITLE
In case clustered column chart tooltip overlap each other

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#4286]
Here is my codepen link [https://codepen.io/swarajv45/pen/BaGovvY?editors=0010](url)

here is the code

`/**
 * ---------------------------------------
 * This demo was created using amCharts 4.
 * 
 * For more information visit:
 * https://www.amcharts.com/
 * 
 * Documentation is available at:
 * https://www.amcharts.com/docs/v4/
 * ---------------------------------------
 */

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

var chart = am4core.create('chartdiv', am4charts.XYChart)
chart.colors.step = 2;

chart.legend = new am4charts.Legend()
chart.legend.position = 'top'
chart.legend.paddingBottom = 20
chart.legend.labels.template.maxWidth = 95

var xAxis = chart.xAxes.push(new am4charts.CategoryAxis())
xAxis.dataFields.category = 'category'
xAxis.renderer.cellStartLocation = 0.1
xAxis.renderer.cellEndLocation = 0.9
xAxis.renderer.grid.template.location = 0;

var yAxis = chart.yAxes.push(new am4charts.ValueAxis());
yAxis.min = 0;

function createSeries(value, name) {
    var series = chart.series.push(new am4charts.ColumnSeries())
    series.dataFields.valueY = value
    series.dataFields.categoryX = 'category'
    series.name = name
  series.columns.template.tooltipText = `'Custom Label'}: {valueY}`;

    series.events.on("hidden", arrangeColumns);
    series.events.on("shown", arrangeColumns);

    return series;
}

chart.data = [
    {
        category: 'Place #1',
        first: 40,
        second: 55,
        third: 60
    },
    {
        category: 'Place #2',
        first: 30,
        second: 78,
        third: 69
    },
    {
        category: 'Place #3',
        first: 27,
        second: 40,
        third: 45
    },
    {
        category: 'Place #4',
        first: 50,
        second: 33,
        third: 22
    }
]

createSeries('first', 'The First');
createSeries('second', 'The Second');
createSeries('third', 'The Third');
chart.cursor = new am4charts.XYCursor();
    chart.cursor.xAxis = categoryAxis;
function arrangeColumns() {

    var series = chart.series.getIndex(0);

    var w = 1 - xAxis.renderer.cellStartLocation - (1 - xAxis.renderer.cellEndLocation);
    if (series.dataItems.length > 1) {
        var x0 = xAxis.getX(series.dataItems.getIndex(0), "categoryX");
        var x1 = xAxis.getX(series.dataItems.getIndex(1), "categoryX");
        var delta = ((x1 - x0) / chart.series.length) * w;
        if (am4core.isNumber(delta)) {
            var middle = chart.series.length / 2;

            var newIndex = 0;
            chart.series.each(function(series) {
                if (!series.isHidden && !series.isHiding) {
                    series.dummyData = newIndex;
                    newIndex++;
                }
                else {
                    series.dummyData = chart.series.indexOf(series);
                }
            })
            var visibleCount = newIndex;
            var newMiddle = visibleCount / 2;

            chart.series.each(function(series) {
                var trueIndex = chart.series.indexOf(series);
                var newIndex = series.dummyData;

                var dx = (newIndex - trueIndex + middle - newMiddle) * delta

                series.animate({ property: "dx", to: dx }, series.interpolationDuration, series.interpolationEasing);
                series.bulletsContainer.animate({ property: "dx", to: dx }, series.interpolationDuration, series.interpolationEasing);
            })
        }
    }
}`

Anyway, we can do this in a clustered column chart.

![image](https://github.com/amcharts/amcharts4/assets/48621208/5babb1fa-9ade-4fab-b070-42313198a790)

**Comment by Swaraj55** [comment]
Do you mean by using curly braces this is resolved?

**Comment by martynasma** [comment]
No. By adding `tooltipText` directly to series:

```
series.tooltipText = `'Custom Label'}: {valueY}`;
```

Not to columns like you currently have:

```
series.columns.template.tooltipText = 'Custom Label'}: {valueY};
```

**Comment by Swaraj55** [comment]
Ok thanks it is now working
