### ISSUE TITLE
Amcharts4 ScrollbarX Tooltip

### ISSUE THREAD

**Issue by lawrenceryan** [amcharts/amcharts4#4287]
Regarding this thread [#4282](https://github.com/amcharts/amcharts4/issues/4282), I added tooltip to the scrollbarx.
When I hover it for the first time, the tooltip was showing, but the next time I hover it, only the chart tooltip was showing.

The code that I added was 
```chart.scrollbarX.tooltipText = 'This is scrollbar'```

How can I fix this? I'm using amcharts 4.9.37

**Comment by zeroin** [comment]
Could you create an exact codepen where this situation is reproduced?

**Comment by lawrenceryan** [comment]
> Could you create an exact codepen where this situation is reproduced?

Hi, I made it here before on the other thread! You can check it here!
[https://codesandbox.io/s/stacked-column-chart-with-tooltip-t2wjvy](https://codesandbox.io/s/stacked-column-chart-with-tooltip-t2wjvy)

Would this be enough?

**Comment by zeroin** [comment]
When you set tooltipText on a chart, it simply has a higher priority than tooltipText set on any child of a chart, including scrollbar, as it is also a child.

**Comment by lawrenceryan** [comment]
Is there any way so that I can still use the code above with tooltip attached to the scrollbar?

**Comment by zeroin** [comment]
Well, just don't set tooltipText on the whole chart, set it on some child like plotContainer.

**Comment by lawrenceryan** [comment]
So the tooltip based on cursor position will be gone and will be replaced by static position tooltip?

**Comment by zeroin** [comment]
Tooltip based on cursor position must be set on a series, not chart. I really don't see any reason to set tooltipText on whole chart, unless you want the same text to be shown when you hover anywhere on the chart.

**Comment by lawrenceryan** [comment]
Could you please show me how to do it with the code above?

**Comment by zeroin** [comment]
Here it is: https://codesandbox.io/s/stacked-column-chart-with-tooltip-forked-clrfxt

**Comment by lawrenceryan** [comment]
I've checked the code, I think there is no changes between this one
[https://codesandbox.io/s/stacked-column-chart-with-tooltip-forked-43w33q?file=/src/App.js](https://codesandbox.io/s/stacked-column-chart-with-tooltip-forked-43w33q?file=/src/App.js)

**Comment by zeroin** [comment]
sorry, it's not saving for some reason. Here is a code:

```
    chart.cursor.events.on("cursorpositionchanged", function (ev) {
      var xAxis = ev.target.chart.xAxes.getIndex(0);
      var index = xAxis.positionToIndex(
        xAxis.toAxisPosition(ev.target.xPosition)
      );
      var text = "";
      chart.series.each(function (series) {
        if (!series.isHiding) {
          var item = series.dataItems.getIndex(index);
          text += `[${series.stroke.hex}]●[/] ${series.name} : ${item.valueY}\n`;
        }
      });
      chart.series.each(function (series) {
          series.tooltipText = text;
        }
      );
    });
```

**Comment by lawrenceryan** [comment]
I tried the code, it works, but I lose the mouse position tooltip feature.
If possible I would love to keep the mouse position tooltip feature along with the scrollbar tooltip, is there any way to do that?

**Comment by zeroin** [comment]
It is possible, but in hi case you should not set tooltip on series, but on columns instead and the tooltipText method will also be different. I am afraid this is out of scope of free support, if you have a license, please address our support team with this request.

**Comment by lawrenceryan** [comment]
Ah, I see. Thank you for the help!
