### ISSUE TITLE
Use of corner radius on upper series on a stacked columns chart 

### ISSUE THREAD

**Issue by Calandal95** [amcharts/amcharts4#429]
Hello,
i'm trying to make the upper series of a stacked columns chart round using corner radius.
That's my actual chart:
![cattura](https://user-images.githubusercontent.com/39583628/46405197-c0508100-c707-11e8-9107-3adbb4d46f8b.JPG)

The number of series is dynamic. They could be 2 or 5 in example

I want to make the green serie round (up to the 8th column) and the blue serie round from the 9th to the 12th.
How can i achieve this?

Thanks for any help 
Alessio

**Comment by martynasma** [comment]
Also posted this:
https://www.amcharts.com/docs/v4/tutorials/stacked-column-series-with-rounded-corners/

**Comment by Calandal95** [comment]
> You can use adapters to make that happen.
> 
> I put together a small demo here:
> https://codepen.io/team/amcharts/pen/aRdGWm?editors=0010
> 
> It uses adapters for `cornerRadiusTopLeft` and `cornerRadiusTopRight`. The adapter handler checks whether current item is the last in the stack with a value. If it is, rounded corners are used.
> 
> Hope the code makes sense.

Thank you so much! 
I was **almost** sure I had checked the tutorials :)

Alessio

**Comment by martynasma** [comment]
Nah I just made the demo and tutorial after you posted your question ;)

**Comment by husseincarma** [comment]
did this change with am charts 5 ?

**Comment by vik80sh** [comment]
@husseincarma `  series.columns.template.setAll({
        cornerRadiusTL:5,
        cornerRadiusTR:5,
      });`
