### ISSUE TITLE
Count is not visible in few columns

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#4290]
I share an pic

<img width="722" alt="image" src="https://github.com/amcharts/amcharts4/assets/48621208/c9ec6c3c-70ca-4a95-868c-e60a34156f25">

var bullet = series.bullets.push(new am4charts.LabelBullet());
        var label = bullet.label;
        label.text = "{doc_count_value}";
        label.fontSize = 10;
        bullet.locationY = 0.5;

        series.columns.template.events.on("sizechanged", function (ev) {
            //@ts-ignore
            if (ev.target.dataItem && ev.target.dataItem.bullets) {
                var height = ev.target.pixelHeight;
                //@ts-ignore
                ev.target.dataItem.bullets.each(function (id, bullet) {
                    if (height > 20) {
                        bullet.locationY = 0.5;
                        bullet.dy = 0;
                    }
                    else {
                        bullet.locationY = 0;
                        bullet.dy = -15;
                    }
                });
            }
        });

This problem also come when there is single column. data is coming for all columns but it show only few.

**Comment by martynasma** [comment]
It seems you are placing bullets at the bottom of the column if it's higher tan 20px:

```
bullet.locationY = 0;
```

The bullets get placed outside of chart area.

**Comment by Swaraj55** [comment]
Working, thanks
