### ISSUE TITLE
Label Bullets not show in the column in specific condition

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#4291]
this is my code.
var bullet = series.bullets.push(new am4charts.LabelBullet());
        var label = bullet.label;
        label.text = "{label}";
        label.truncate = false;
        label.fontSize = 10;

        series.columns.template.events.on("sizechanged", function (ev) {
          //@ts-ignore
          if (ev.target && ev.target.dataItem && ev.target.dataItem.bullets) {
            var columnWidth = ev.target.pixelWidth;
            console.log(columnWidth)
            if (columnWidth < 120) {
              bullet.locationX = 0;
              bullet.dx = 15; // Adjust the distance between the column and label
            } else {
              bullet.locationX = 0;
              bullet.dx = -20;
            }
          }
        });

<img width="524" alt="image" src="https://github.com/amcharts/amcharts4/assets/48621208/5b534a41-318f-4e9f-9219-7056835fddd9">

In the above screenshot, you see the research column has a small width so the label should be visible outside, and for a large width, a label should be inside the column.
But what is happening here is that large is also so visible inside (accord. to SS) or outside(when we change the case).

**Comment by zeroin** [comment]
If you could create a woking codepen with full source, I could take a look.

**Comment by Swaraj55** [comment]
Sure, 
[https://codepen.io/team/amcharts/pen/rqpwEZ?editors=0010](url)

**Comment by Swaraj55** [comment]
I update the comment

**Comment by zeroin** [comment]
This happens because you modify valueLabel which is just a template of all labels. You should get the label of the same data item instead:

https://codepen.io/team/amcharts/pen/gOQMdEP/85b90267987c8f5c9da834104c596f4e

**Comment by Swaraj55** [comment]
Thanks, @zeroin  it is working for me.
