### ISSUE TITLE
Sticky xAxis

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#4293]
Hello! I am looking for a way to make my xAxis sticky while scrolling, but i can't find any. Is there any chance, it is possible? 
I need it to look like this:
![image](https://github.com/amcharts/amcharts4/assets/18229211/2677569a-d7e4-4271-a559-e89198bca5de)

**Comment by zeroin** [comment]
I am afraid I don't understand from this picture. If you use our default scrollbars, then x and y axis do not move when you scroll.

**Comment by zeroin** [comment]
Well, you can't have exactly the same view with amCharts, but I would say that in general, this is quite the same:

https://codepen.io/team/amcharts/pen/ZEmpLmQ/354d5d44e2b33ff302d5024e3b93b671
