### ISSUE TITLE
focusable not being set

### ISSUE THREAD

**Issue by MANTENN** [amcharts/amcharts4#4294]
**Bug description**

1. create a bullet target
2. set focusable to false

```
  var bulletTarget = lineTarget.bullets.push(new am4charts.Bullet());
  bulletTarget.fill = am4core.color("#000000"); // tooltips grab fill from parent by default
  bulletTarget.focusable = false;
  bulletTarget.tabindex = -1;
  var targetLabel = lineTarget.bullets.push(new am4charts.LabelBullet());
  targetLabel.label.text = "{target}";
  targetLabel.label.fontSize = dynColLabelFontSize;
  targetLabel.label.dx = 15;
  targetLabel.label.horizontalCenter = "left";
  targetLabel.label.fill = am4core.color("#ffffff");
  targetLabel.label.background.fill = am4core.color("#000000");
  targetLabel.label.ariaLabel = "test";
  targetLabel.label.padding(4, 8, 4, 8);
  targetLabel.focusable = false;
  targetLabel.tabindex = -1;
```

when looking at the dom, the focusable attribute is set to true

**Environment (if applicable)**

Provide details about your development environment where you think it might be useful. E.g.:

 - amCharts version 4
 - Browser and its version
 - React 16.14

workaround is to set tabindex to -1(`  targetLabel.tabindex = -1;` and items are not focused

**Comment by MANTENN** [comment]
https://allyjs.io/tutorials/focusing-in-svg.html#:~:text=The%20focusable%20attribute%20defined%20by,false%22%20makes%20the%20element%20inert.

ah, its an edge only api. I assumed am4 charts would handle the focus interopability.

**Comment by martynasma** [comment]
Is it resolved for you, or you still think there's something wrong? In the latter case, could you please provide a CodePen of your whole chart?
