### ISSUE TITLE
target.dataItem.index returns -1

### ISSUE THREAD

**Issue by moncy-kv** [amcharts/amcharts4#4295]
I want to apply multicolor to a column chart through an adapter add function with fill.To get the right color from an array of colors I need the index of the corresponding column ,however target.dataItem.index returns -1 for all columns, hence I cant assign the right colors.

This is the adapter function I used to achieve it.
```
     configToRender.series[0].adapter = {
        fill: function (fill: any, target: any) {

          const colors = modifiedConfig.colors;

          const index = target.dataItem.index;
```

 - amCharts version 4.10.32
 - Chrome
 - React 18.2

**Comment by zeroin** [comment]
I think you should add adapter to series.columns and not to the series itself. 
series.dataItem is indeed set, but it has nothing to do with all the dataitems of a series, it is used just to store some additional data. Check this example: https://www.amcharts.com/demos-v4/column-chart-with-axis-break-v4/

**Comment by moncy-kv** [comment]
Thanks! @zeroin
