### ISSUE TITLE
Last bar is cropped on rendering chart as 3D

### ISSUE THREAD

**Issue by moncy-kv** [amcharts/amcharts4#4297]
**Question**

On creating a 3D chart the last bar gets cropped. Width of the last bar is less compared to others.
Please refer the screenshot and link attached

**Additional context**
https://codesandbox.io/s/3d-charts-cropped-57dw49?file=/src/constants.ts

![image](https://github.com/amcharts/amcharts4/assets/89776023/bc359cd6-c702-4d0a-a722-a48f95f581aa)

**Comment by zeroin** [comment]
The only way to fix it would be to increase paddingRight of the chart.

**Comment by moncy-kv** [comment]
```
    children: [
      {
        type: "Container",
        paddingBottom: 0,
        paddingTop: 0,
        paddingLeft: am4core.percent(20),
        paddingRight: am4core.percent(20)
      }
    ]
```
I tried adding padding but it seems like it doesn't have any effect on the chart.
Modified config is as above.

**Comment by zeroin** [comment]
My mistake, actually what you had to do is to to create `am4charts.XYChart3D` instead of `am4charts.XYChart`, this will solve the issue automatically.

**Comment by moncy-kv** [comment]
It worked. Thanks
