### ISSUE TITLE
Cusrom css zoom property makes chart cursor offsets

### ISSUE THREAD

**Issue by ClaudioGodoi** [amcharts/amcharts4#4298]
When using a custom zoom property to html tag, the charts cursors fails to work going offsets.

to replicate please go to 
https://www.amcharts.com/demos/motion-chart/
check the cursor and then add to html  the property "zoom:0.85"

When is zoomed via browser Ctrl & + or - chart work fine, but via css offsets.

No zoom
![amchartnozoomcursor](https://github.com/amcharts/amcharts4/assets/72524062/0a8723b2-9672-44db-947c-ab07b21d9772)

Zoom:0.85
![amchartzoomcursor](https://github.com/amcharts/amcharts4/assets/72524062/65294b7c-fe82-42e5-8397-e1812d5ec598)

**Comment by zeroin** [comment]
We are aware of problems with the css zoom, but unfortunately we do not have a solution for this. CSS zoom is in general bad practice and we do not recommend using it too.
