### ISSUE TITLE
AmCharts 4, rendering amchart asynchronously

### ISSUE THREAD

**Issue by nodenong** [amcharts/amcharts4#4299]
Hello, 
I am wondering if there is a way to render the amchart asynchronously. I am rendering a "scatter plot", basically a Line chart with bullet and without the line. There is 100,000 data and there would be 100,000 bullet. The rendering of this chart is extremely slow, and caused the page to be unresponsive. Is there anyway to make it run asynchronous so that the webpage is responsive? 

OR

Is there a way to optimize this and make the rendering faster? The render took ~100seconds. 
I can't use the dynamic grouping of data because I really need all the data to show.

Thanks in advance.

I am using React JS with amCharts v4.10.25
Latest chrome browser

**Comment by martynasma** [comment]
I suppose you can wrap chart creation function into a `setTimeout()` so it begins rendering delayed.

Better yet, consider switching to amCharts 5, which is faster.

**Comment by nodenong** [comment]
Hello @martynasma,

Thank you for the fast response. 
`setTimeout()` only delayed the process of starting the rendering. I don't think this is what I am finding.

I may have written my question wrongly or unclear. Got confused between async or sync. 

What I was trying to achieve is allowing the amchart to render without blocking the main thread. Meaning that during the rendering process of the chart, user still can click on other button or navigate to other page.

What i am facing right now is that the amchart of many bullet data took a long time to render, at the same time the whole page is freezed, user are unable to click on anything except for closing the tab or browser.

I had considered on using amCharts 5. However, due to my product is already in production using amCharts 4, migrating to amCharts 5 may need a really long time and seems like finding a solution in amCharts 4 is a better choice.

**Comment by martynasma** [comment]
You might try playing with system setting `updateStepDuration`. E.g.:

```
am4core.system.updateStepDuration = 20;
```

The smaller the value (default: 45) the more frequently rendering will stop giving the other page elements time to catch up.

**Comment by nodenong** [comment]
@martynasma 

That doesn't seems to solve the issue as well unfortunately. 
The page elements was already fully loaded, just that while re-rendering the chart component, if the chart has a lot of data then it will take a long time to render, whilst render, whole page will remain unresponsive until it finish.

**Comment by martynasma** [comment]
Try setting [`parsingStepDuration`](https://www.amcharts.com/docs/v4/reference/component/#parsingStepDuration_property) on your chart to a lower value than default.

**Comment by nodenong** [comment]
Thank you for suggesting the ways. I had tried setting the parsingStepDuration to a lower value, the issue remains and it seems like there is no other way to fix it.
Except maybe it would fix it if I upgrade to amchart 5. This would be my last resort.

**Comment by martynasma** [comment]
Not sure what else to suggest. amCharts 5 is way faster, so maybe you can give that option some though ;)
