### ISSUE TITLE
Maximum call stack size exceeded  at String.replace Error from Sprite.ts

### ISSUE THREAD

**Issue by moncy-kv** [amcharts/amcharts4#4301]
**Question**

I am trying to render a chart using JSON config and I encountered an issue where the loader is shown infinitely if both x-axis and y-axis values are of TEXT type. An error is also shown in browser console. 
![image](https://github.com/amcharts/amcharts4/assets/89776023/27f66894-793c-49fd-8d45-4b4d9d832cc7)
![image](https://github.com/amcharts/amcharts4/assets/89776023/c5108b44-976f-4027-aa6a-b4c06b767ccf)

May I know whats the root cause of this issue and a proper solution for the same? 

Development environment

 - amCharts version :4.10.32
 - Browser and its version : chrome
 - Related frameworks and their versions : ReactJS 18.2.0

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
