### ISSUE TITLE
How to create invert area chart

### ISSUE THREAD

**Issue by maitrungduc1410** [amcharts/amcharts4#4305]
Hi Team,

I'm struggling on creating this chart where Red series is bounded to the top and Blue series is bounded to the bottom, can you please suggest how can I achieve this?

thanks

![unnamed (1)](https://github.com/amcharts/amcharts4/assets/16630193/9110bdd9-4cb1-411b-9c5e-922ab6299d94)

**Comment by martynasma** [comment]
This would require the red series to be attached to a different X axis, that is placed on the opposite side of the chart.

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#axis-position

**Comment by maitrungduc1410** [comment]
> This would require the red series to be attached to a different X axis, that is placed on the opposite side of the chart.
> 
> 
> 
> https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#axis-position

And how about the blue series, it should also be somehow attach to the bottom right? Sorry I'm not clear

Through the link you shared I see that it can be attached to top only.

**Comment by martynasma** [comment]
> And how about the blue series, it should also be somehow attach to the bottom right? Sorry I'm not clear

Yes, you will need two X axes: one would be at the bottom, the blue series would be attached to it, and therefore its fill would be in the lower section. The other one would be placed on top (`opposite: true`). The red series would be attached to the second X axis, so that its fill is in upper section.

Hope that makes sense.

**Comment by maitrungduc1410** [comment]
Thanks, its much more clear to me.

For the Y axis we can use only 1 that's shared for all series right?

**Comment by martynasma** [comment]
> For the Y axis we can use only 1 that's shared for all series right?

Yup.

**Comment by maitrungduc1410** [comment]
Hi @martynasma , I follow the approach you suggested, and it doesn't give me what I actually want.

[Link to reproduce](https://codesandbox.io/s/react-amcharts-fill-upward-8whdvd)

Working Code:

```tsx
import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";
import am4themes_animated from "@amcharts/amcharts4/themes/animated";
import am4themes_dark from "@amcharts/amcharts4/themes/dark";
import { useEffect, useRef } from "react";

am4core.useTheme(am4themes_animated);
am4core.useTheme(am4themes_dark);

const data = [
  {
    confirmedRate: 21,
    baseLine: 40,
    date: "2023-07-02T07:59:51.702Z",
    cancelRate: 11,
  },
  {
    confirmedRate: 89,
    baseLine: 67,
    date: "2023-07-03T07:59:51.702Z",
    cancelRate: 93,
  },
  {
    confirmedRate: 76,
    baseLine: 34,
    date: "2023-07-04T07:59:51.702Z",
    cancelRate: 99,
  },
  {
    confirmedRate: 60,
    baseLine: 38,
    date: "2023-07-05T07:59:51.702Z",
    cancelRate: 28,
  },
  {
    confirmedRate: 47,
    baseLine: 49,
    date: "2023-07-06T07:59:51.702Z",
    cancelRate: 80,
  },
  {
    confirmedRate: 13,
    baseLine: 3,
    date: "2023-07-07T07:59:51.702Z",
    cancelRate: 8,
  },
  {
    confirmedRate: 27,
    baseLine: 76,
    date: "2023-07-08T07:59:51.702Z",
    cancelRate: 6,
  },
  {
    confirmedRate: 62,
    baseLine: 85,
    date: "2023-07-09T07:59:51.702Z",
    cancelRate: 7,
  },
  {
    confirmedRate: 35,
    baseLine: 26,
    date: "2023-07-10T07:59:51.702Z",
    cancelRate: 64,
  },
  {
    confirmedRate: 97,
    baseLine: 47,
    date: "2023-07-11T07:59:51.702Z",
    cancelRate: 63,
  },
];

export default function TestLineChart() {
  const chartRef = useRef<HTMLDivElement>(null);
  const chart = useRef<am4charts.XYChart | null>(null);

  useEffect(() => {
    chart.current = am4core.create(chartRef.current!, am4charts.XYChart);
    // Create axes
    chart.current.xAxes.push(new am4charts.DateAxis());
    chart.current!.yAxes.push(new am4charts.ValueAxis());

    // Add legend
    chart.current.legend = new am4charts.Legend();

    // Add cursor
    chart.current.cursor = new am4charts.XYCursor();
    chart.current.cursor.behavior = "none";

    
    // Confirm rate
    const xAxis0 = new am4charts.DateAxis();
    chart.current.xAxes.push(xAxis0);

    const series0 = chart.current!.series.push(new am4charts.LineSeries());
    series0.dataFields.valueY = "confirmedRate";
    series0.dataFields.dateX = "date";
    series0.strokeWidth = 2;
    series0.xAxis = xAxis0;
    series0.xAxis.renderer.opposite = true;
    series0.name = "Confirmed Rate";
    series0.tooltipText = `{name}: [bold]{valueY}[/]`;
    series0.fillOpacity = 0.8;
    series0.fill = am4core.color("rgb(198,101,126)");
    series0.stroke = am4core.color("rgb(198,101,126)");
    series0.tensionX = 0.8;
    
    // Base Line
    const series1 = chart.current!.series.push(new am4charts.LineSeries());
    series1.dataFields.valueY = "baseLine";
    series1.dataFields.dateX = "date";
    series1.strokeWidth = 2;
    series1.name = "Base Line";
    series1.tooltip!.getFillFromObject = false
    series1.tooltipText = `{name}: [bold]{valueY}[/]`;
    series1.tooltip!.label.fill = am4core.color('black')
    series1.tooltip!.background.fill = am4core.color('white')
    series1.stroke = am4core.color("white");

    const bullet = series1.bullets.push(new am4charts.CircleBullet());
    bullet.circle.stroke = am4core.color('white');
    bullet.circle.strokeWidth = 2;
    bullet.circle.fill = am4core.color('white');

    // set chart data
    chart.current.data = data;

    return () => {
      if (chart.current) {
        chart.current.dispose();
      }
    };
  }, []);

  return <div ref={chartRef} style={{ width: "100%", height: 500 }}></div>;
}
```

this is output, the red series still fill downward, because it shares same YAxis with the white series:

<img width="1630" alt="Screenshot 2023-07-11 at 5 11 54 PM" src="https://github.com/amcharts/amcharts4/assets/16630193/2d3b18a5-a309-4c41-905a-9dc065820357">

**Comment by zeroin** [comment]
Martynas made a mistake, this can not be achieved using two xAxes. Fill is drawn to the 0 or baseValue of Y axis, not X. So to make this possible I would create three ValueAxis, which should be synced (you should monitor min and max of your main axis and set the same for the other axes. Then you should set baseValue for you helper axes - the one used by bottom series should use less than minimum value of your main axis and the top one should use bigger than max value of your main axis.

**Comment by maitrungduc1410** [comment]
Hi @zeroin, I did a try create new Value Axis for my top chart (the Red one), but as you can see it results in there're 2 value axes displayed, in different directions (`top -> bottom` and `bottom -> top`), and because the 2 series I have below don't share same value axis, therefore the fill of the Red series is not correct.

you also mentioned that `which should be synced`, I'm not really clear about it, can you elaborate more, it's really great if you can help me with an example so that I can understand your idea better.

thanks

<img width="1789" alt="Screenshot 2023-07-11 at 10 39 39 PM" src="https://github.com/amcharts/amcharts4/assets/16630193/b83592bd-21ce-4a01-ae9b-9677edcd7e3e">

**Comment by maitrungduc1410** [comment]
@zeroin perfect, thanks for your very good point.

I've succesfully made it here: https://8whdvd.csb.app
