### ISSUE TITLE
Bubble Size of child nodes doesn't scale well with large difference in values

### ISSUE THREAD

**Issue by ralphchristianeclipse** [amcharts/amcharts4#4307]
You can see the P values of the child nodes have a very large difference and the main node is 800k

The other node is 14k while the other one is 2k

![image](https://github.com/amcharts/amcharts4/assets/25447231/20dc0cd1-e199-41ba-a69c-d066b2039b92)

Expected size would be like almost 85% much smaller

How do I set this up?

```ts
   networkSeries.minRadius = am4core.percent(2);
    networkSeries.maxRadius = am4core.percent(15);
```

i have the following min and max radius

**Comment by zeroin** [comment]
We'll need a working codepen with full source code in order to help.
