### ISSUE TITLE
Display Tooltip for Horizontal Line in Amcharts4

### ISSUE THREAD

**Issue by abhayjain2023** [amcharts/amcharts4#4308]
Hello,
I would like to **add a tooltip to the horizontal line**, which can be located in either the first and second quadrants or the third and fourth quadrants. My intention is to enhance data visualization and provide additional context for each line. I would greatly appreciate any insights or guidance on implementing this feature.

**Amcharts Version used**:- 4

Below is a small snippet of my code for reference:

`

        var rangeY5 = valueAxisY.axisRanges.create();
        rangeY5.value = "TEST";
        rangeY5.label.text = "";
        rangeY5.grid.stroke = am4core.color("#CCCCCC"); 
        rangeY5.grid.strokeWidth = 2;
        rangeY5.grid.strokeOpacity = 1;
        var tooltip1 = new am4core.Tooltip();
        
        tooltip1.background.fill = am4core.color("#E73C33");
        tooltip1.background.stroke = am4core.color("#E73C33");
        tooltip1.background.strokeWidth = 2;
        tooltip1.background.cornerRadius = 5;
        tooltip1.label.fill = am4core.color("#FFFFFF");
        tooltip1.label.fontSize = 12;
        tooltip1.label.textAlign = "middle";
        tooltip1.label.width = 120;
        tooltip1.label.maxWidth = 120;
        tooltip1.label.text = "TEST";
`

Thanks!

**Comment by martynasma** [comment]
Please refer to this tutorial on adding tooltips on axis ranges:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Tooltips_on_ranges

**Comment by abhayjain2023** [comment]
I have tried the code with your reference @martynasma , but I am definitely not getting the desired result. I have attached the screenshot and code snippet for your reference.

`
        var rangeY3 = valueAxisY.axisRanges.create();
        rangeY3.value = medianValue;
        rangeY3.label.text = "";
        if (medianValue < 0) {
            rangeY3.grid.stroke = am4core.color("#EE3D8B");    
        } else {
            rangeY3.grid.stroke = am4core.color("#00AC41");
        }
        rangeY3.grid.strokeWidth = 2;
        rangeY3.grid.strokeOpacity = 1;
        rangeY3.label.disabled = true; // To disbale Y axis label text

        if (medianValue < 0) {
            rangeY3.axisFill.fill = am4core.color("#EE3D8B");
        } else {
            rangeY3.axisFill.fill = am4core.color("#00AC41");
        }
        rangeY3.axisFill.fillOpacity = 0.3;
        rangeY3.axisFill.tooltip = new am4core.Tooltip();
        rangeY3.axisFill.tooltipText = medianValue + "%";
        rangeY3.axisFill.interactionsEnabled = true;
        rangeY3.axisFill.isMeasured = true;
`

I would like to position the tooltip specifically over the green line instead of covering the entire area.

![image](https://github.com/amcharts/amcharts4/assets/141400569/a5e6c241-2240-49d2-a963-05a930e61474)

**Comment by martynasma** [comment]
Try this then:

```JavaScript
rangeY3.grid.tooltip = new am4core.Tooltip();
rangeY3.grid.tooltipText = "18" + "%";
rangeY3.grid.interactionsEnabled = true;
rangeY3.grid.isMeasured = true;
```

**Comment by abhayjain2023** [comment]
Thank you, @martynasma , for your guidance. Could you please assist me with another query? I am interested in aligning a tooltip to any quadrant (horizontally), while ensuring it does not coincide with the Y-axis. Additionally, I am curious if it is possible to make the tooltip fixed, meaning it remains visible over the line at all times, even when the mouse is not hovering over it. For reference, I have attached a screenshot and a code snippet.

`
        var rangeY3 = valueAxisY.axisRanges.create();
        rangeY3.value = 18;
        rangeY3.label.text = "";
        rangeY3.grid.stroke = am4core.color("#00AC41");
        rangeY3.grid.strokeWidth = 3;
        rangeY3.grid.strokeOpacity = 1;
        rangeY3.label.disabled = true; // To disbale Y axis label text
        
        rangeY3.grid.fill = am4core.color("#00AC41");
        rangeY3.grid.fillOpacity = 0.3;
        rangeY3.grid.tooltip = new am4core.Tooltip();
        rangeY3.grid.tooltipText = "18" + "%";
        rangeY3.grid.interactionsEnabled = true;
        rangeY3.grid.isMeasured = true;
`

![image](https://github.com/amcharts/amcharts4/assets/141400569/14c9bf2f-8ec5-4931-b147-9b8d204ba814)

**Comment by martynasma** [comment]
Try this:

```JavaScript
rangeY3.grid.tooltipX = am4core.percent(25);
```

**Comment by abhayjain2023** [comment]
Thank you, @martynasma, for your guidance. Could you please assist me with another query? I want a **tooltip to appear when I move the cursor over a specific area**, and I also want the **value in the tooltip to be in bold**. However, I do not want the entire text to be bold, only the value inside the tooltip. Additionally, I would like all the **text inside the tooltip to be centered**-aligned.

`

        var rangeY3 = valueAxisY.axisRanges.create();
        rangeY3.value = "18";
        rangeY3.label.text = "";
        rangeY3.grid.stroke = am4core.color("#00AC41");
        rangeY3.grid.strokeWidth = 3;
        rangeY3.grid.strokeOpacity = 1;
        rangeY3.label.disabled = true; // To disbale Y axis label text

        rangeY3.grid.fill = am4core.color("#00AC41");
        rangeY3.grid.fillOpacity = 0.3;
        rangeY3.grid.tooltip = new am4core.Tooltip();
        rangeY3.grid.tooltipText = "Text Placeholder \n" + "18" + "%";
        rangeY3.grid.tooltip.textAlign = "middle";
        rangeY3.grid.tooltipX = am4core.percent(70);
        rangeY3.grid.interactionsEnabled = true;
        rangeY3.grid.isMeasured = true;

        rangeY3.grid.events.on("over", function (event) {
            rangeY3.grid.dom.style.cursor = "pointer";
        });

        rangeY3.grid.events.on("out", function (event) {
            rangeY3.grid.dom.style.cursor = "default";
        });
`

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
