### ISSUE TITLE
Creating a Tooltip to Show When Hovering Over a Specific Area on the Same Line

### ISSUE THREAD

**Issue by abhayjain2023** [amcharts/amcharts4#4309]
I would like a tooltip to appear when I hover my cursor over a particular area along a horizontal line. The tooltip should also be displayed at the same location on that horizontal line. For example, if I hover over the 25% mark from the left within the chart container on the screen, the tooltip should also be displayed at the 25% position. Similarly, if I hover over the 67% mark from the left, the tooltip should be displayed at the corresponding 67% position on the screen.

I have attached the screenshot for reference & also add the code snippet.

`

        var rangeY3 = valueAxisY.axisRanges.create();
        rangeY3.value = "18";
        rangeY3.label.text = "";
        rangeY3.grid.stroke = am4core.color("#00AC41");
        rangeY3.grid.strokeWidth = 3;
        rangeY3.grid.strokeOpacity = 1;
        rangeY3.label.disabled = true; // To disbale Y axis label text
        
        rangeY3.grid.fill = am4core.color("#00AC41");
        rangeY3.grid.fillOpacity = 0.3;
        rangeY3.grid.tooltip = new am4core.Tooltip();
        rangeY3.grid.tooltipHTML = `
                    <div style="text-align: center;">
                        Text Placeholder :
                        <strong style="font-size: 16px;">18%</strong>
                    </div>
                `;
        rangeY3.grid.tooltip.textAlign = "middle";
        //rangeY3.grid.tooltipX = am4core.percent(80); // This line help us to set the tooltip at that position i.e. 80% from left
        rangeY3.grid.interactionsEnabled = true;
        rangeY3.grid.isMeasured = true;
        
        rangeY3.grid.events.on("over", function (event) {
          rangeY3.grid.dom.style.cursor = "pointer";
          let chartWidth = chart.pixelWidth;
            let mouseX = event.pointer.point.x;
            let containerLeftOffset = chart.pixelX;
            // let marginFromLeft = mouseX - containerLeftOffset - 112;
            let marginFromLeft = mouseX - containerLeftOffset - 205;
            let percentage1 = Number(Math.round((marginFromLeft * 100) / chartWidth));
            rangeY3.grid.tooltipX = am4core.percent(percentage1);
        });
        
        rangeY3.grid.events.on("out", function (event) {
          rangeY3.grid.dom.style.cursor = "default";
        });
`

![image](https://github.com/amcharts/amcharts4/assets/141400569/d04e86d3-bceb-4c04-b039-967fa05d6f09)

**Comment by martynasma** [comment]
In that case, I would suggest not using axis range, but rather a separate `LineSeries` with a data point all the way from -100 to 100 (or whatever rage you need).

It could have a bullets (can be transaprent) so that you have places to hover on.

Does that make sense?

**Comment by abhayjain2023** [comment]
Thanks @martynasma for guidance, but I have tried with the below code using LineSeries but not able to get desired result.

`

var rangeY3 = valueAxisY.axisRanges.create();
        rangeY3.value = medianValue;
        rangeY3.label.text = "";
        if (medianValue < 0) {
          rangeY3.grid.stroke = am4core.color("#D02073"); 
        } else {
          rangeY3.grid.stroke = am4core.color("#00AC41");
        }
        rangeY3.grid.strokeWidth = 3;
        rangeY3.grid.strokeOpacity = 1;
        rangeY3.label.disabled = true; // To disbale Y axis label text
        
        if (medianValue < 0) {
          rangeY3.grid.fill = am4core.color("#D02073");
        } else {
          rangeY3.grid.fill = am4core.color("#00AC41");
        }
        rangeY3.grid.fillOpacity = 0.3;
        rangeY3.grid.tooltip = new am4core.Tooltip();
        rangeY3.grid.tooltip.textAlign = "middle";
        var chartWidth = chart.pixelWidth;
        
        rangeY3.grid.events.on("over", function (event) {
            rangeY3.grid.dom.style.cursor = "pointer";
            let mouseX = event.pointer.point.x;
            let marginFromLeft = mouseX - 275;
            let percentage1 = (marginFromLeft * 100) / chartWidth;
            var tooltipXValue = am4core.percent(percentage1);
            rangeY3.grid.tooltipX = tooltipXValue;
            rangeY3.grid.tooltip.dx = 50;
            rangeY3.grid.tooltip.dy = -2;

            rangeY3.grid.tooltipHTML = `
                <div style="text-align: center;">
                    ${tooltipValue}:
                    <strong style="font-size: 16px;">${medianValue}%</strong>
                </div>
            `;

            rangeY3.grid.tooltip.show();
        });
        
        rangeY3.grid.events.on("out", function (event) {
          rangeY3.grid.dom.style.cursor = "default";
          rangeY3.grid.tooltip.hide();
        });

        rangeY3.grid.interactionsEnabled = true;
        rangeY3.grid.isMeasured = true;

var lineSeries = chart.series.push(new am4charts.LineSeries());
lineSeries.dataFields.valueY = medianValue; // Change "value" to your data field for the Y-axis value
lineSeries.strokeWidth = 3;

// Add a transparent bullet for interaction
var bullet = lineSeries.bullets.push(new am4charts.Bullet());
var circle = bullet.createChild(am4core.Circle);
circle.radius = 10;
circle.fillOpacity = 0; // Set to 0 for transparency

// Attach a tooltip to the bullet
circle.tooltipText = medianValue + "%"; // Change "value" to your data field for the tooltip value

// Data for the LineSeries
var data = [
  { value: medianValue } // Provide the value
];

lineSeries.data = data;

// Add hover events
circle.events.on("over", function (event) {
  circle.cursorOverStyle = am4core.MouseCursorStyle.pointer;
});

circle.events.on("out", function (event) {
  circle.cursorOverStyle = am4core.MouseCursorStyle.default;
});

`

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by abhayjain2023** [comment]
@martynasma  This is my reference code link. 
https://codesandbox.io/s/beautiful-hawking-4vd6zw

The line code starts from line number 493.

My major issue is when I hover on charts then tooltip is not aligned with cursor pointer.

**Comment by martynasma** [comment]
Well, you do have this in your code `rangeY3.grid.tooltip.dx = 50;` which shifts the tooltip 50px to the right.

**Comment by abhayjain2023** [comment]
Thank you for your reply, @martynasma . I'd like to discuss the matter further. Even after removing the mentioned "dx" line, the problem persists. To elaborate, when hovering at the far right on the x-axis, approximately 70-80% from the left, the issue remains. Additionally, the gap between the tooltip and the cursor varies from device to device. If you zoom the screen out to around 80% and then hover over the green line, you will observe the precise error.
Your attention to this matter is greatly appreciated.

**Comment by martynasma** [comment]
Maybe you can try setting `tooltipPosition` to `"pointer"`:
https://www.amcharts.com/docs/v4/reference/sprite/#tooltipPosition_property

**Comment by abhayjain2023** [comment]
Thanks @martynasma !
