### ISSUE TITLE
Browser getting slow if data point increases

### ISSUE THREAD

**Issue by manoj016** [amcharts/amcharts4#431]
currently I am using 16400 data points for demo purpose. But in my case I am using like 50k average data points. The chart cannot handle this amount data points and the browser freezes itself and the graph also. Is there any possible way to solve this problem?

I am sharing a codepen for reference.

https://codepen.io/manoj016/pen/jePmKz?editors=0011

**Comment by martynasma** [comment]
We've just released a new version, that among other things, introduces quite dramatic performance enhancements.

Can you try how that data-heavy chart feels like for you now?

**Comment by zeroin** [comment]
I would also suggest not to use animated theme with such a number of data points. It will slow things down and the animations won't be smooth anyway.

**Comment by zeroin** [comment]
Version 64 beta now splits processes into chunks so freezing browser should not happen or at least a lot less than before.
