### ISSUE TITLE
Help with duplicated charts with autoDispose

### ISSUE THREAD

**Issue by PedroHGaspar** [amcharts/amcharts4#4311]
So, i have a refresh button in my page, that has this code in it:

        $('a.link-reload').click(function(e) {
            e.preventDefault();
            carregaTela();
        });

        function carregaTela() {
            updateData()
        }

inside my updateData():

                    if (seriesContainer.children.length > 0) {
                        am4core.options.autoDispose = true;
                    }

And i also have this autoDispose inside my updateData() so that i don't have the Event Dispatcher Error that charts would disappear.
But with this code the problem of Event Dispatcher is solved, but now, everytime i hit my refresh button, the chart is duplicated, see the image below:

before hit the refresh button:

![image](https://github.com/amcharts/amcharts4/assets/37162818/2053a4d7-397a-4697-80fa-6d2477adb7bf)

after hit the refresh button:

![image](https://github.com/amcharts/amcharts4/assets/37162818/dd04d35e-229d-485d-827a-8082f195ba1b)

if i hit the refresh button several times, the chart will continue to duplicate, and i can't use disposeAllCharts because i have other charts in the page, and they are erased if i use it.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
