### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4314]
Hi @martynasma 
Can you please take a look into

https://github.com/amcharts/amcharts4-geodata/issues/35

**Comment by azharakbar** [comment]
@martynasma Can u please take a look into this

**Comment by Pauan** [comment]
@azharakbar amCharts is a browser library, you cannot use it in Node.

You must use a bundler (like Webpack), which is standard practice for browser libraries.

https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/

**Comment by azharakbar** [comment]
@Pauan 
We are using webpack

**Comment by Pauan** [comment]
@azharakbar If you're using `"type": "module"` then all of your code must be ES6-compatible.

Here is a `.zip` file which works with `"type": "module"`:

[amcharts4-webpack.zip](https://github.com/amcharts/amcharts4/files/12728846/amcharts4-webpack.zip)

The code is completely normal amCharts code, except it adds the `.js` extension to the file imports.

So if you're still having problems, then there is something wrong with your code, so you'll have to show us your code so we can find the problem.
