### ISSUE TITLE
DateAxis dateToPoint calculates wrong position

### ISSUE THREAD

**Issue by igoriok1994** [amcharts/amcharts4#4315]
Hi, 

DateAxis **dateToPoint**  calculates wrong point. So, after **triggerMove** call, cursor position appears on wrong place. 
E.g. I'm calling dateToPoint with "2023-08-15 09:00:00" date. Then triggerMove appears on "2023-08-15 08:00:00".

Hese is an example on codepen:
https://codepen.io/igoriok1994/pen/VwqZgOM

Maybe I'm doing something wrong?

**Comment by martynasma** [comment]
Try adding a pixel to the calculated point:

```JavaScript
let point = dateAxis.dateToPoint(moment.utc('2023-08-15 09:00:00').toDate());
point.x++;
```

**Comment by igoriok1994** [comment]
Is this safe solution? 
E.g. for chart with hourly data for a 1-2 weeks.

**Comment by martynasma** [comment]
I think so.

What I think is happening is that point X is being rounded after converting from a timestamp. Depending on your resolution, device pixel ratio, chart size, etc. it might get rounded up to a previous period.

Adding a pixel ensures that we will beat the rounding up.
