### ISSUE TITLE
Updating values in TreeMap without making chart come back to Home level

### ISSUE THREAD

**Issue by Ccommiss** [amcharts/amcharts4#4318]
Hello, 

I am using amCharts4 Tree Map object. 
I have multiple interdependants components in my visualisation page : I would need to update the tooltip text dynamically, but without going back to "home" if I already clicked on a top-level object. 

I tried invalidateRawData after changing my chart.data elements, but it keeps going back to "home" level. I also tried resetting an adapter after updating my values without any call to invalidate Data, but none of these approaches worked.

Is there any solution to that very specific problem ?

Here's a snippet of the second approach.

``` 
  for (const element of chart.data) {
      updateMyValues(element, data);
    }
// 1) First approach was 
    chart.invalidateRawData();
// 2) Second approach was 
    chart.seriesTemplates.each((i, level) =>
      level.columns.template.adapter.add('tooltipHTML', function(text, target) {
        return '<div>ADAPTER test ( value : {customField})</div>';
      }));
 ``` 

Thanks a lot by advance.

**Environment (if applicable)**

am4Charts
Angular

**Comment by martynasma** [comment]
The second approach seems OK to me, as long as your function `updateMyValues()` updates actual data.
