### ISSUE TITLE
LineSeries not starting from zero 

### ISSUE THREAD

**Issue by zafarn8** [amcharts/amcharts4#4319]
Stack:
Amcharts 4

CodePen:-  [https://codepen.io/zafar/pen/jOXbEOj?editors=0010](url)

as you can see in codepen current behavior of lineSeries chart. below is the screenshot of current behavior.

<img width="960" alt="lineseries default behaviour" src="https://github.com/amcharts/amcharts4/assets/25639232/b5e9becd-474d-4758-812f-504c2cc304f3">

Question: 
Cant we start LineSeries from zero or from beginning? Please check below pic for your reference I highlighted that how I am expecting.

<img width="960" alt="lineseries expected behaviour" src="https://github.com/amcharts/amcharts4/assets/25639232/dcd26603-5c6a-4a10-83dd-c012922d99c1">

Description:
I checked amchart4 documentation to start lineSeries from zero but its not working as I am expecting. below is the technique which I tried.

1. Start and end labels:
dateAxis.renderer.minLabelPosition = 0.05;
dateAxis.renderer.maxLabelPosition = 0.95;

**minLabelPosition = 0.05 will disable all labels in the first 5% length of the axis. Similarly, maxLabelPosition = 0.95 will disable labels in the last 5% along axis length.**
 
as they clearly mentioned in documentation minLabelPosition and maxLabelPosition disable labels from first and last but I don't want to disable any labels that's why it wont work for me.

Is there any way to achieve like that which I added expected graph image in above.

thanks,

**Comment by xorspark** [comment]
You need to use `startLocation` and `endLocation`: https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

**Comment by zafarn8** [comment]
Hi @xorspark thanks for quick reply. I tried that one as well but there is label overlapping issue. Which I asked separately here is the link [https://github.com/amcharts/amcharts4/issues/4320](url)

there is another issue I can say it starting from beginning but when I plot the dot in graph it showing half dot, I guess due to Y-Axis overlap. Is not there any way where we can just draw line in beginning and end. 
Can we draw graph like I added in the image?

<img width="960" alt="lineseries expected behaviour" src="https://github.com/amcharts/amcharts4/assets/25639232/c40677ba-4968-45fb-af97-1d3920eefce4">

**Comment by xorspark** [comment]
`startLocation` and `endLocation` are the only way to extend the line. The half dot is due to bullet masking: https://www.amcharts.com/docs/v4/concepts/bullets/#Disabling_bullet_clipping

Please keep the issues separate. Someone will address the label overlapping issue in your other ticket.

**Comment by zafarn8** [comment]
@xorspark thank you.
