### ISSUE TITLE
How can we add margin or padding to X-Axis first and last label

### ISSUE THREAD

**Issue by zafarn8** [amcharts/amcharts4#4320]
Stack:
Amcharts 4

CodePen:- [https://codepen.io/zafar/pen/JjwYdJw?editors=0010](url)

as you can see in codepen current behavior of lineSeries chart. below is the screenshot of current behavior.

<img width="962" alt="default1" src="https://github.com/amcharts/amcharts4/assets/25639232/09dae5d0-419b-468f-9a6a-845b0bc6e4ff">

dateAxis.startLocation = 0.5;
dateAxis.endLocation = 0.5;

after adding above properties my graph looking like this in below image.

<img width="962" alt="default1" src="https://github.com/amcharts/amcharts4/assets/25639232/85f0dc84-b7bd-4a42-888c-9c029457c6a1">

the X-Axis first label is coming below Y-Axis label and X-Axis last label is going outside the graph as you can see in above image. 

How can we add margin or padding to X-Axis first and last label so that they can look like below graph image.

<img width="962" alt="expected1" src="https://github.com/amcharts/amcharts4/assets/25639232/3778fbe4-19e1-47c2-8d21-bbdc9334b662">

thanks,

**Comment by martynasma** [comment]
It can be done using adapters, but I strongly advice against it as it increases likelihood of labels overlapping:
![image](https://github.com/amcharts/amcharts4/assets/1458520/ad89de9c-0193-4082-9315-092418d956ee)

Instead, why not just position all labels left-aligned?

```JavaScript
dateAxis.renderer.labels.template.horizontalCenter = 0;
```

**Comment by zafarn8** [comment]
Hi @martynasma after adding left-aligned now last label is not visible. please find the screenshot.

<img width="361" alt="last lebel hide" src="https://github.com/amcharts/amcharts4/assets/25639232/61f6a490-060c-42dc-9cbe-4041c26bb558">

**Comment by martynasma** [comment]
I would just hide the last label:

```
xAxis.renderer.maxLabelPosition = 0.95;
```

**Comment by zafarn8** [comment]
but that doesn't work for me. I have to display all labels.

**Comment by martynasma** [comment]
In that case I suggest leaving labels as they are, and increasing `paddingRight` on the chart so that last label fits.
