### ISSUE TITLE
Do I need to remove event listeners manually when I use autoDispose = true? 

### ISSUE THREAD

**Issue by eduardmavliutov** [amcharts/amcharts4#4321]
**Question**

Hello! I found neither information in docs nor similar questions on stackoverflow, can you please tell me, do I need to manually remove event listeners from a chart when I use `autoDispose = true` option?

**Comment by martynasma** [comment]
No, you don't. Disposing the chart will dispose all the listeners, too.

**Comment by eduardmavliutov** [comment]
@martynasma Great! Thank you for a quick response.
