### ISSUE TITLE
Vertical Line not adding on current time

### ISSUE THREAD

**Issue by zafarn8** [amcharts/amcharts4#4322]
Stack:
Amcharts 4

CodePen:- [https://codepen.io/zafar/pen/OJrNVWY?editors=0010](https://codepen.io/zafar/pen/OJrNVWY?editors=0010)

Description:
I am following below documentation to draw vertical line with current time of system as you can see in codepen but its not drawing the line with current time. Could you please let me know where I am doing wrong.

[https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Single_lines](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Single_lines)

thanks,

**Comment by martynasma** [comment]
That's because your data ends before current date/time.

Adding axis ranges do not extend the DateAxis range. If you want that, you can use [`includeRangesInMinMax`](https://www.amcharts.com/docs/v4/reference/dateaxis/#includeRangesInMinMax_property)

```JavaScript
dateAxis.includeRangesInMinMax = true;
```

**Comment by zafarn8** [comment]
I added but cant see the red vertical line.. you can check in codepen.

**Comment by martynasma** [comment]
This is happening because your DateAxis is in day mode, so it displays to the start of the date of the axis range.

Since you are using `new Date()` it adds hours as well, and places axis range on the specific hour, which is outside.

Is this a real application? Will axis ranges be displayed outside actual data scope?

**Comment by zafarn8** [comment]
`Is this a real application? Will axis ranges be displayed outside actual data scope?`
yes, axis range should be display within a graph. there is limit there will be only 7 days data will be there and graph will plot the dot according to data with hours and minutes after that I want to show vertical line it will show your current time that means currently you are here. thats why I using `new Date()`, according to time the line will be move ahead.

**Comment by zafarn8** [comment]
I added but still after refreshing I am getting latest time from response so the only difference between last point plotted time and current time is 1min or may be second in that case the red line should appear after the plotted dot or point. but as you can see its appearing before the dot, you can see in attached screenshot I highlighted the current time of system in bottom and the time which coming from response in tooltip(currently I hardcoded the data but for your testing you can add last point data your current time or 1min before of the current time). Please let me know if you need more clarification.



thanks, 
<img width="403" alt="line not appearing on correct position" src="https://github.com/amcharts/amcharts4/assets/25639232/903eb1f6-bac6-4446-b580-bce5e833fa94">

**Comment by martynasma** [comment]
You can also set `max` of the DateAxis to current date + some minutes.

```JavaScript
dateAxis.max = new Date().getTime();
```

**Comment by xorspark** [comment]
The issue is that you moved the grid to using location = 0.5, which doesn't match up with how the dates are represented on the grid. Date axis labels are placed in the middle of the grid to span the entire period. If you set the location of the grid back to zero and use 0.0001 on the label to move the label onto the grid line, then the placement will be closer to what you're looking for:

```
    dateAxis.renderer.grid.template.location = 0;
    dateAxis.renderer.labels.template.location = 0.001;
```

**Comment by zafarn8** [comment]
@xorspark thank you it works.. also thank you @martynasma for your time and quick reply.
