### ISSUE TITLE
How can we draw line from last plotted dot to current time?

### ISSUE THREAD

**Issue by zafarn8** [amcharts/amcharts4#4323]
Hi, 

Stack:
Amcharts 4

CodePen:- [https://codepen.io/zafar/pen/NWeRQLX?editors=0010](url)

current behavior:
 
<img width="687" alt="draw line from last dot" src="https://github.com/amcharts/amcharts4/assets/25639232/c6b9369b-bd4d-4e1a-bb2c-1e548fb8baa7">

expected behavior:

<img width="687" alt="draw line from last dot expected" src="https://github.com/amcharts/amcharts4/assets/25639232/6f981993-4bbd-4468-accc-646f197c5a33">

Question:
Is there any way to draw line from last plotted dot to current time?

Description: 
As I attached the above expected behavior image where last dot is plotted and after that I draw the green line upto the current time where I am show casing using red vertical line. So, Is there anyway in amchart4 to draw line from last plotted point to the current time.

thanks,

**Comment by xorspark** [comment]
Not automatically. The only ways around it are to either add an extra data point to the existing series ([use propertyFields to change the color](https://www.amcharts.com/docs/v4/concepts/data/#Property_fields)) or create an extra series containing the last blue datapoint and another datapoint for the current time with the desired color.

**Comment by zafarn8** [comment]
Hi @xorspark thanks for reply. If I add extra data in current array then it will add dot as well in the graph and if we create extra series containing last blue data point and another datapoint for current time will it show continues? will current time show dot as well? coz current time datapoint should not show the dot.

Is there any example of creating an extra series with continuing of existing one? this will be very helpful for me.

thanks,

**Comment by xorspark** [comment]
>  If I add extra data in current array then it will add dot as well in the graph 

You can use [propertyFields](https://www.amcharts.com/docs/v4/concepts/data/#Property_fields) on the bullet and line to disable the bullet (`bullet.propertyFields.disabled = /* whatever property contains the boolean for disabled in your data */`).

>  if we create extra series containing last blue data point and another datapoint for current time will it show continues

Do you mean will it automatically update to the current time? No, you need to update the point when you update the line. If you mean will it extend to the end, no, it will stop at the last datapoint you assign to it.

> Is there any example of creating an extra series with continuing of existing one?

It's nothing more than creating a series with the new datapoints. 

```
var extendedSeries = chart.series.push(new am4charts.LineSeries());
extendedSeries.dataFields.dateX = "year";
extendedSeries.dataFields.valueY = "extendedValue";
extendedSeries.stroke = am4core.color("#00ff00");
const lastDataPoint = chart.data[chart.data.length - 1];
extendedSeries.data = [
  { year: lastDataPoint.year, extendedValue: lastDataPoint.value }, 
  { year: currentTime, extendedValue: lastDataPoint.value }, 
];
```

Changing the baseInterval on the axis also helps with placement.

[Codepen](https://codepen.io/team/amcharts/pen/KKbaQge/0b9164ecb414113990a8347705d74e38?editors=0010)

**Comment by zafarn8** [comment]
@xorspark thanks man for all your efforts. its appreciated
