### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'startPoint')

### ISSUE THREAD

**Issue by willcolbert** [amcharts/amcharts4#4325]
**Bug description**

Using a touch interface anywhere on a page with a chart can result in the console error "Uncaught TypeError: Cannot read property 'startPoint' of undefined". 

1 Go to one of the following page - https://www.amcharts.com/demos-v4/drawing-chart-series-with-mouse-or-touch-v4 on a touch device or put Chrome into touch device emulation in the dev tools.

2 Touch/click and hold anywhere on the page

**Environment (if applicable)**

Amcharts v4 / 4.10.38 & chrome newest version

**Additional context**

Related to 
https://github.com/amcharts/amcharts4/issues/3125
https://github.com/amcharts/amcharts4/issues/3326

**Comment by martynasma** [comment]
Which OS are you able to reproduce the issue with on with a Chrome?

We can't seem to be able to reproduce it.

**Comment by willcolbert** [comment]
Version 116.0.5845.179

**Comment by martynasma** [comment]
Thanks.

Current version is 117.0.5938.89. Would you mind trying to upgrade and see if the issue persists for you?

**Comment by willcolbert** [comment]
I cant update yet but once I do Ill see if I can still reproduce it.
