### ISSUE TITLE
Setting any timezone on DateAxis dateFormatter shifts days by one downwards

### ISSUE THREAD

**Issue by tomasporemba** [amcharts/amcharts4#4327]
**Bug description**

Setting a timezone on `dateAxis.dateFormatter` results in days being shifted by one. Using value `new Date('2023-09-21T04:00:00.000Z')` and setting timezone to `America/New_York` should in my opinion result in displaying `Sep 21`, however what we observe is `Sep 20`.

`new Date('2023-09-21T02:00:00.000Z')` in `America/New_York` is in fact `Sep 20`, however it gets displayed as `Sep 19`.

Moreover even setting `UTC` for `new Date('2023-09-21T04:00:00.000Z')` displays `Sep 20`.

https://jsfiddle.net/tomasporemba/wyd0uxna/6/

**Environment**

 - amCharts latest (locally 4.10.36 - same behaviour)
 - Firefox 117, Chrome 116

**Additional context**
Actual behaviour
![image](https://github.com/amcharts/amcharts4/assets/78349091/300f680e-7342-4ba8-baf7-ac45049a95cd)

Expected behaviour
![image](https://github.com/amcharts/amcharts4/assets/78349091/c4e51ec9-7cbc-490c-802c-653311356ddc)

**Comment by tomasporemba** [comment]
If the series contains "hourly" steps, the timezone setting results in date being formatted accordingly and correctly.
https://jsfiddle.net/tomasporemba/wyd0uxna/15/

**Comment by martynasma** [comment]
Well, when you have "daily" granularity, the grid is placed per-day - starting at 00:00 each day. So Sep 18 00:00 in UTC results in Sep 17 in NY.

I'm afraid we won't be able to change this bahavior.

**Comment by martynasma** [comment]
If axis is in daily mode, the grid signifies start of the day, not the actual data point timestamp.

If you need it to respect hours, you need to put DateAxis into hourly mode, as you already pointed out.

Hope that makes sense.

**Comment by tomasporemba** [comment]
Thanks for the clarification - how do you parse the date from the timestamp if
> the grid signifies start of the day

?
Does this mean the `DateAxis` does not honour the `inputDateFormat: 'i'` for example? It just picks the "date part" of the timestamp and disregards any other information the timestamp carries?

**Comment by martynasma** [comment]
The important thing to know is that DateAxis has zero relation to actual data items.

The chart instructs the general range of dates in data, as well as tentative granularity (unless you explicitly set `baseInterval`) and that's it.

From that point onwards the axis itself determines where and how to draw the grid. Usually it's on pretty intervals. E.g. you would not want to draw one grid ant 4am then at 6am for another day.

**Comment by dominikbrazdil** [comment]
The issue here, I think, is that with timezone set on the Axis, the axis labels should be generated with timezone in mind (e.g., startOfTheDay relatively to the timezone, not UTC, as date-fns/tz already supports https://github.com/date-fns/tz)

The not-ideal solution for me here was apply the timezone to the formatter only for the timeUnit (i.e. granularity) smaller than 'day' and leave it balnk otherwise
