### ISSUE TITLE
how to take out automatic zoom?

### ISSUE THREAD

**Issue by PedroHGaspar** [amcharts/amcharts4#4328]
Hey guys, can anyone help me taking this automatic zoom out? Everytime that i refresh my page, this zoom happens, i tried to find some infos in the docs, but i didn't found anything about this automatic zoom... And the data on the chart in the left and right sides are always invisible because of this zoom, that's why i want to take it out.

I've already done this: 
cursor.behavior = "none";
But the zoom is still happening, when i reload the page the informations come "zoomed", making the right and left sides of the chart hidden, so it needs to click on the "-" button to see all the chart data

![image](https://github.com/amcharts/amcharts4/assets/37162818/3d8b9ea7-6ebc-47f0-831f-61ff7e19a7f9)

**Comment by xorspark** [comment]
Can you provide a codepen that reproduces the issue?

**Comment by PedroHGaspar** [comment]
![image](https://github.com/amcharts/amcharts4/assets/37162818/f7a9e150-5f1f-4cbb-bbbe-750a88006234)

this is what appear to me when i reload the page, but it don't show all the data. Now this is what shows when i click on the "-" (zoom out) button

![image](https://github.com/amcharts/amcharts4/assets/37162818/f8c1af8b-ff25-4c16-920a-cf51aee9374b)

The chart make this automatic zoom and idk why, because i've already take off the cursor.behavior

**Comment by PedroHGaspar** [comment]
> ![image](https://user-images.githubusercontent.com/37162818/271376229-f7a9e150-5f1f-4cbb-bbbe-750a88006234.png)
> 
> this is what appear to me when i reload the page, but it don't show all the data. Now this is what shows when i click on the "-" (zoom out) button
> 
> ![image](https://user-images.githubusercontent.com/37162818/271376488-f8c1af8b-ff25-4c16-920a-cf51aee9374b.png)
> 
> The chart make this automatic zoom and idk why, because i've already take off the cursor.behavior

@xorspark

**Comment by xorspark** [comment]
I can't troubleshoot from just screenshots. Please provide a codpen.
