### ISSUE TITLE
Entire data is not plotted from the dataset provided.

### ISSUE THREAD

**Issue by moncy-kv** [amcharts/amcharts4#4330]
Only one set of data is plotted from an array.
I've attached a sample code.
https://codesandbox.io/s/data-not-plotted-7qw49p?file=/src/App.tsx

Development environment:

amCharts version :4.10.32
Browser and its version : chrome
Related frameworks and their versions : ReactJS 18.2.0

**Comment by martynasma** [comment]
You need to specify the format of date your data has:
https://www.amcharts.com/docs/v4/concepts/data/#Parsing_dates_in_data
