### ISSUE TITLE
VennDiagram bug: inconsistent positioning of chart elements

### ISSUE THREAD

**Issue by asdlkj77** [amcharts/amcharts4#4331]
**Bug description**

Hello. I'm using VennDiagram and I'm having problems with inconsistent positioning of chart elements for different numbers in the data.

I want to present 4 sets containing each other:
- A contains B, C and D
- B contains C and D
- C contains D

So the set D is completely contained in the set C, which is completely contained in the set B, which is completely contained in the set A

The problem is that such a graph is drawn in different ways for different numbers present in the data.

Case 1:
If I have data like this:
```
series.dataFields.category = "name";
series.dataFields.value = "value";
series.dataFields.intersections = "sets";
series.data = [
     {name: 'A', value: 78438},
     {value: 38514, sets: ['A', 'B']},
     {name: 'B', value: 38514},
     {value: 16984, sets: ['A', 'C']},
     {value: 16984, sets: ['B', 'C']},
     {name: 'C', value: 16984},
     {value: 5473, sets: ['A', 'D']},
     {value: 5473, sets: ['B', 'D']},
     {value: 5473, sets: ['C', 'D']},
     {name: 'D', value: 5473}
];
```

Then I get the following graph:
![vennCase1](https://github.com/amcharts/amcharts4/assets/147436098/55efaf5c-7811-4782-9331-03a851f6437f)

Case 2:
If I have data like this:
```
series.dataFields.category = "name";
series.dataFields.value = "value";
series.dataFields.intersections = "sets";
series.data = [
     {name: 'A', value: 23936},
     {value: 8365, sets: ['A', 'B']},
     {name: 'B', value: 8365},
     {value: 3984, sets: ['A', 'C']},
     {value: 3984, sets: ['B', 'C']},
     {name: 'C', value: 3984},
     {value: 2669, sets: ['A', 'D']},
     {value: 2669, sets: ['B', 'D']},
     {value: 2669, sets: ['C', 'D']},
     {name: 'D', value: 2669}
];
```

Then I get the following graph:
![vennCase2](https://github.com/amcharts/amcharts4/assets/147436098/911de32a-9fe2-48b9-abb9-4151d2cae8f9)

Case 3:
If I have data like this:
```
series.dataFields.category = "name";
series.dataFields.value = "value";
series.dataFields.intersections = "sets";
series.data = [
     {name: 'A', value: 80015},
     {value: 41946, sets: ['A', 'B']},
     {name: 'B', value: 41946},
     {value: 17023, sets: ['A', 'C']},
     {value: 17023, sets: ['B', 'C']},
     {name: 'C', value: 17023},
     {value: 6982, sets: ['A', 'D']},
     {value: 6982, sets: ['B', 'D']},
     {value: 6982, sets: ['C', 'D']},
     {name: 'D', value: 6982}
];
```

Then I get the following graph:
![vennCase3](https://github.com/amcharts/amcharts4/assets/147436098/7f41ec90-e9f7-49ae-894e-5794ec2a8080)

All the above examples can be obtained by pasting the above code snippets here:
https://codepen.io/team/amcharts/pen/xxGbNOg

The most common positioning for different numbers is like I presented in case 1:
![vennCase1](https://github.com/amcharts/amcharts4/assets/147436098/55efaf5c-7811-4782-9331-03a851f6437f)
but the other cases happen really often

As you can see, each time there are the same dependencies between the sets, the same hierarchy, but depending on the numbers in the data, the chart is displayed in different ways. The problem concerns not only the positioning of set D, but the remaining sets (B and C) can also change their position depending on the data (in the same way as set D - once they stick to the right edge of the superset, once to the left, once to the bottom ). An important thing that I would like to add is that for the same numbers the graph is always drawn the same, so there is no situation where something will suddenly be drawn differently, for example after refreshing the web browser.

In each of these situations, the chart can be considered "correct", but such display changes after data changes may suggest to application users that more than just the numbers have changed, which can be confusing.

Would it be possible for you to modify the chart so that it is displayed consistently (for example, like for the data I provided in case 1):
![vennCase1](https://github.com/amcharts/amcharts4/assets/147436098/55efaf5c-7811-4782-9331-03a851f6437f)

so that different numbers in the data do not result in different positions of the circles on the chart?

Thank you in advance for your help

**Environment**
All settings can be found in the link I sent earlier:
https://codepen.io/team/amcharts/pen/xxGbNOg

And I was using current Google Chrome version

**Comment by martynasma** [comment]
Have you tried setting `sortBy` setting to `"value"`?

https://www.amcharts.com/docs/v4/reference/flowdiagram/#sortBy_property

**Comment by martynasma** [comment]
We're using D3 Venn layout algo. I'm afraid there are no settings that might influence it. Sorry.
