### ISSUE TITLE
Week or Month data averagering

### ISSUE THREAD

**Issue by laurentvolpon777** [amcharts/amcharts4#4338]
Hello,
I'm using amCharts 4 and I was wondering if it was possible to average data by weeks or months. I would like to integrate that into my exporting.menu.items.
I know it is possible to use the groupInterval with different timeUnits. But it doesn't average all the data of the weeks / months. It just shows the last data of each week / month.
Thanks for your help
Laurent

**Comment by zeroin** [comment]
You can have open, close, low, high, close, sum or average:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Aggregate_values

`series.groupFields.valueY = "average";`

**Comment by zeroin** [comment]
Your `baseAxis` in this case is `CategoryAxis`, so the `xAxis` auto-zooms to show all the selected data, and this happens after you call `zoomToDates`. So you have two options here: 

1) set `autoZoom:false` for your xAxis. In this case, if you zoom-in y axis, x axis won't be auto zoomed to the selection. 
2) delay zooming a bit, with setTimeout.

**Comment by laurentvolpon777** [comment]
Thanks a lot for your answer @zeroin. It's working! But for some reasons, even if I put 
```
    series.groupFields.valueY = "average";
    series.groupInterval = { timeUnit: "month", count: 1 };

```
it always average by weeks, but not monthly. Any idea what can cause that?

**Comment by zeroin** [comment]
I will need a codepen where this can be reproduced in order to help.

**Comment by laurentvolpon777** [comment]
Of course, you're right! I'm super busy these days but will try to make a compact version of my super long code.

**Comment by laurentvolpon777** [comment]
Hello @zeroin,
Sorry for the late answer. I hope you're still around :)
I prepared this simple codePen to show you what I want to do. 
[https://codepen.io/laurent777/pen/OJdjwQa](url)
I need to average data using the Export Menu. In this exemple, for some reasons, I can't even average anything and don't know what I'm doing wrong.
Could you please help me?
Thanks a lot

**Comment by zeroin** [comment]
Oh, it's my mistake, you should have set `groupInterval` on axis, not series - sorry.

**Comment by laurentvolpon777** [comment]
Hey @zeroin, thanks for your reply.
It's working indeed but not as it should. Indeed, if you look carefully, it doesn't show the average but actually the last value of the week (or the month).
I made another codepen that better illustrate what I'm saying:
 [https://codepen.io/laurent777/pen/OJdjwQa](url) 

If you just average by week, check the value at April 9th. It corresponds to the value of the 15th. If you just change this latter, it will always be this one, not the average of the week.

And by the way, it says April in the graph, while the month is 3 (March)! Weird

Thanks for your help again

**Comment by zeroin** [comment]
Again, my mistake - the line
`lineSeries.groupFields.valueY = "average";`

should go above groupData = true, as right after you set it to true, it groups data and doesn't know that you need average.

```
                               lineSeries.groupFields.valueY = "average";  
                               dateAxis.groupInterval = { timeUnit: "week", count: 1 };
                               dateAxis.groupData = true;                              
```

**Comment by laurentvolpon777** [comment]
Wow, thanks a million! It was that simple.
Now I can continue my project.
All the best
