### ISSUE TITLE
Legend Truncation not working

### ISSUE THREAD

**Issue by MohitKandpal** [amcharts/amcharts4#4339]
Legend labels are not getting truncated if legends are placed on top with legendContentAlign set to left. I tried multiple settings specified in https://www.amcharts.com/docs/v4/tutorials/truncating-legend-labels/#:~:text=Truncating%20labels,labels.

But still, it does not work. 

Codepen - https://codepen.io/mohit_k/pen/zYeNrLv

As you can see in the above codepen example, I have set **maxWidth** of legend labels to as low as **30** but still my labels are not getting truncated and being shifted to next line. The expectation is to truncate legend labels so as to align them in one line.

In the past, you guys mentioned this as a known issue and later on informed it to be fixed in one of the future releases (but still it is not fixed). Attaching the git link for your reference - https://github.com/amcharts/amcharts4/issues/2338

Please help and suggest how this can be achieved.

**Comment by MohitKandpal** [comment]
Team,
Any update on this ?

**Comment by martynasma** [comment]
When legend is placed at the bottom or top, legend uses grid layout to arrange items into columns, so it overrides your `maxWidth` settings due to fuzzy logic.

The only way to override it is via an adapter:

```JavaScript
chart.legend.labels.template.adapter.add("maxWidth", function() {
  return 30;
});
```
