### ISSUE TITLE
Hide specific tick marks

### ISSUE THREAD

**Issue by devduke** [amcharts/amcharts4#434]
How would I go about hiding the tick marks that do not have a label shown due to using:

`valueAxis.renderer.minLabelPosition = 0.05`
`valueAxis.renderer.maxLabelPosition = 0.95`

Example codepen:
https://codepen.io/anon/pen/yROLaK

Trying to remove the outer tick marks that have no labels (as outlined in the image below)
<img width="844" alt="screen_shot_2018-10-04_at_4_12_44_pm" src="https://user-images.githubusercontent.com/14028544/46500715-852a7c80-c7f1-11e8-825b-b2c6b410d0d3.png">

**Comment by devduke** [comment]
I'm not sure this is the best way to do it but I managed to hide the ticks by applying the following:

```
valueAxis.renderer.ticks.template.adapter.add('visible', (visibility, target, key) => {
    if (target.dataItem.label.dom.getAttribute('display') == 'none') {
        return false
    }
    return visibility
})
```

**Comment by martynasma** [comment]
Just to pitching in. There's currently no better way to hide those ticks as well.

I posted a separate issue here: #437

I suggest you subscribe to updates on it, so you know when we implement a proper solution.
