### ISSUE TITLE
Crypto-js Vulnerability

### ISSUE THREAD

**Issue by rmetel** [amcharts/amcharts4#4340]
Hello,

your current latest version 4.10.38 contains following nested vulnerability in crypto-js https://security.snyk.io/package/npm/crypto-js. This is the dependency tree:

@amcharts/amcharts4@4.10.38
  └─┬ pdfmake@0.2.7
    └─┬ @foliojs-fork/pdfkit@0.13.0
      └── crypto-js@4.1.1

I already checked the sub modules, it would be possible to solve the issue, if you could raise pdfmake to version 0.2.8, because all underlying modules have already been updated.  It would look the following way then, let say you make  amcharts4@4.10.39:

@amcharts/amcharts4@4.10.39
  └─┬ pdfmake@0.2.8 // uses @foliojs-fork/pdfkit@0.14.0
    └─┬ @foliojs-fork/pdfkit@0.14.0 // uses crypto-js@4.2.0
      └── crypto-js@4.2.0 // contains the fix

Thank you in advance :)

**Comment by Pauan** [comment]
@rmetel Thanks for the report, amCharts V4 already uses pdfmake 0.2.8 and crypto-js 4.2.0

You must run `npm update` or `yarn upgrade` in order to upgrade the versions in *your* project, we cannot upgrade the versions for you.

**Comment by rmetel** [comment]
Thank you, it worked! ;)
