### ISSUE TITLE
How can I remove Radar Chart's measure labels?

### ISSUE THREAD

**Issue by canesen7** [amcharts/amcharts4#4342]
Hi. I Have question AmCharts4 Radar Chart.

![image](https://github.com/amcharts/amcharts4/assets/67913330/a02cebcd-ee14-4c0a-a019-a463c4886f82)
 
I have chart like this. But I want to remove radar chart's measure legend. I'd like to see like this

![image](https://github.com/amcharts/amcharts4/assets/67913330/e9975b6b-c182-47d3-a639-c86701bb860a)

I can't find anything in in document because of I don't know this area's name (grid, legend or whatever). 
How can I remove measure's on my radar chart?

**Comment by martynasma** [comment]
Please refer to this doc:
https://www.amcharts.com/docs/v4/concepts/axes/#Disabling_certain_elements

**Comment by canesen7** [comment]
Well, _categoryAxis.renderer.grid.template.disabled = true;_ isn't works? (Also axis.renderer.labels.template.disabled = true and axis.renderer.ticks.template.disabled = true isn't works too.)

**Comment by canesen7** [comment]
> Please refer to this doc: https://www.amcharts.com/docs/v4/concepts/axes/#Disabling_certain_elements

Well, categoryAxis.renderer.grid.template.disabled = true; isn't works? (Also axis.renderer.labels.template.disabled = true and axis.renderer.ticks.template.disabled = true isn't works too.) What is that things name? If I know, I can remove but I don't know which area must disable for remove values on radar chart.

**Comment by martynasma** [comment]
It's for a value axis, not category axis.
