### ISSUE TITLE
How can i use snaptoseries but with LineX and LineY extended to full chart just as without snaptoseries in chart.cursor

### ISSUE THREAD

**Issue by faizan-naeemm** [amcharts/amcharts4#4343]
I have Cursor "snap" to actual data items of the series by setting its snapToSeries property to either a Series reference or an array of Series references.

chart.cursor.snapToSeries = [series1, series2, series3];

Now, the cursor will not follow mouse cursor but rather snap to the nearest data point out of all the series set in snapToSeries.

I want to use chart.cursor.snapToSeries but with chart.cursor.LineX and chart.cursor.LineY extend across the entire chart

**Comment by martynasma** [comment]
I'm afraid there's no way to enable complete crosshair cursor when `snapToSeries` is enabled.

**Comment by faizan-naeemm** [comment]
I have done some thing and it works I have created two lines 
var lineX = chart.plotContainer.createChild(am4core.Line);
lineX.stroke = Linecolours[0];
lineX.strokeWidth = 2;
lineX.fill = Linecolours[0];

ineY = chart.plotContainer.createChild(am4core.Line);
lineY.stroke = Linecolours[0];
lineY.strokeWidth = 2;
lineY.fill = Linecolours[0];

This section handles the logic to update the position of the lineX and lineY according to the cursor's movement (cursorpositionchanged event)

chart.cursor.events.on("cursorpositionchanged", function(ev) {
    var cursor = ev.target;
    if (cursor && cursor.point && cursor.point.x != null && cursor.point.y != null) {
        if (cursor.lineX) {
            lineX.y1 = lineX.y2 = cursor.point.y;
            lineX.x1 = 0;
            lineX.x2 = chart.plotContainer.pixelWidth;
        } else {
            cursor.lineX.disabled = true;
        }
        if (cursor.lineY) {
            lineY.x1 = lineY.x2 = cursor.point.x;
            lineY.y1 = 0;
            lineY.y2 = chart.plotContainer.pixelHeight;
        } else {
            cursor.lineX.disabled = true;
        }
    }
});

it is working but the problem is now the lines are not getting disable even if i move the cursor outside the chart container .. any idea?

**Comment by martynasma** [comment]
Maybe you can use cursor's `hidden` event to hide the lines.
