### ISSUE TITLE
Hiw to bind valueaxistooltip with the exact data point 

### ISSUE THREAD

**Issue by faizan-naeemm** [amcharts/amcharts4#4344]
I have enabled 

chart.cursor.snapToSeries = lineSeries;

now I have the value of data point 1156.7 but in valueaxistooltip the value is appearing 1157

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by faizan-naeemm** [comment]
https://codepen.io/faizannaeem11/pen/XWOxbGL

here it is check the data of 2005 and 2007 it contains decimal points , i want to exact the same data value on my valueaxis tooltip

**Comment by martynasma** [comment]
You may use axis' setting `extraTooltipPrecision` for that:

```JavaScript
valueAxis.extraTooltipPrecision = 1;
```

https://www.amcharts.com/docs/v4/reference/valueaxis/#extraTooltipPrecision_property
