### ISSUE TITLE
How to change the sheet name from data to custom name in excel , and how can i change the position of excel sheet to be start from right hand side (as the data is in arabic)

### ISSUE THREAD

**Issue by faizan-naeemm** [amcharts/amcharts4#4345]
// Set the export configuration
chart.exporting.menu = new am4core.ExportMenu();
chart.exporting.filePrefix = "MyChart"; // Set the file name prefix
chart.exporting.useWebFonts = false; // Use web-safe fonts for better Excel compatibility
chart.exporting.adapter.add("data", function (data) {
  if (data && data.length > 0 && data[0].sheet) {
    data[0].sheet.name = "abc"; // Set the sheet name to "abc"
  }
  return data;
});

**Comment by xorspark** [comment]
You can use the xlsxWorkbook adapter to modify the SheetJS object to modify the name:

```
chart.exporting.adapter.add("xlsxWorkbook", function(wb, xlsx, options) {
  // modify and add additional stuff to workbook object
  // ...
  wb.workbook.SheetNames[0] = "New sheet name"
  wb.workbook.Sheets["New sheet name"] = wb.workbook.Sheets["Data"] 
  return wb;
});
```

The [SheetJS docs](https://docs.sheetjs.com/docs/csf/book#workbook-views) say that you can set RTL by creating a Workbook object containing a `Views` array with the RTL setting . In the adapter it would look like this:

```
  wb.workbook.Workbook = { Views: [{ RTL: true }] }
```
