### ISSUE TITLE
Can we enhance the header color in excel sheet using amcharts 4 ? 

### ISSUE THREAD

**Issue by HaseebMushtaque** [amcharts/amcharts4#4346]
Currently I am modifying the exceel sheet using adapter , I am able to modify the excel sheet name and its position .. how can I change the color of the first row (header)
  chart.exporting.adapter.add("xlsxWorkbook", function (wb) {
     
     var newarray = chart.data.filter(value => Object.keys(value).length !== 0);
     
     // Set sheet name based on language
     var sheetName = @SharedPageData.CurrentLanguage.LanguageID == '1' ? "الأداء المالي" : "Financial performance";
     var sheetData = newarray.map(function (v, t) {
         var d = {};
         d["@Html.LocalizedString("InflationYear")"] = v["FinancialYear"];
         d["@Html.LocalizedString(column1)"] = v["@column1"];
         d["@Html.LocalizedString(column2)"] = v["@column2"];

         return d;
     });

     // Remove existing sheets
     wb.workbook.SheetNames = [];
     wb.workbook.Sheets = {};

     // Add the new sheet
     debugger
     wb.workbook.SheetNames.push(sheetName);
     wb.workbook.Sheets[sheetName] = XLSX.utils.json_to_sheet(sheetData);
     var range = XLSX.utils.decode_range(wb.workbook.Sheets[sheetName]['!ref']);
     for (var C = range.s.c; C <= range.e.c; ++C) {
         var address = XLSX.utils.encode_col(C) + "1"; // <-- first row, column number C
         if (address == "A1" && wb.workbook.Sheets[sheetName][address]) {
             wb.workbook.Sheets[sheetName][address].s = {
                 fill: {
                     patternType: "solid", // none / solid
                     fgColor: { rgb: "FF000000" },
                     bgColor: { rgb: "000000" }
                 },
                 font: {
                     name: 'Times New Roman',
                     sz: 16,
                     color: { rgb: "#FF000000" },
                     bold: true,
                     italic: false,
                     underline: false
                 },
                 border: {
                     top: { style: "thin", color: { auto: 1 } },
                     right: { style: "thin", color: { auto: 1 } },
                     bottom: { style: "thin", color: { auto: 1 } },
                     left: { style: "thin", color: { auto: 1 } }
                 }
             }
             wb.workbook.Sheets[sheetName][address].v = wb.workbook.Sheets[sheetName][address].v.toUpperCase();
         }
          
     }
     // Modify workbook views based on language
     if (@SharedPageData.CurrentLanguage.LanguageID == '1') {
         wb.workbook.Workbook = { Views: [{ RTL: true }] };
     } else {
         wb.workbook.Workbook = { Views: [{ RTL: false }] };
     }

     return wb;
 });

**Comment by martynasma** [comment]
I'm afraid this question falls outside of amCharts functionality. Please refer to the [SheetJS docs](https://docs.sheetjs.com/).
