### ISSUE TITLE
EventDispatcher is disposed

### ISSUE THREAD

**Issue by cristiansandru11** [amcharts/amcharts4#4347]
**Bug description**

 `EventDispatcher is disposed` error is thrown when using  `chart.responsive.enabled = true;` and the route is changed before the chart is fully loaded

 - amCharts version: 4.10.38
 - Browser and its version: Google Chrome Version 119.0.6045.199 (Official Build) (x86_64)
 - Related frameworks and their versions: Angular 17

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
