### ISSUE TITLE
Prevent Bar chart from sorting data

### ISSUE THREAD

**Issue by eduardmavliutov** [amcharts/amcharts4#4349]
**Question**

 - amCharts 4.10.24
 - all browsers
 - Vue 3.3.4

Hello! 

Before passing the data to `createFromConfig` function I sort data manually by value but put 'Total' always first no matter what value it has. But for some reason chart itself sorts data and I can't preserve the intended order.

```
console.log('data', data) // [{ name: 'Total', value: '45'}, { name: 'A', value: 55 }, { name: 'B', value: 33 }]

chart.value = am4core.createFromConfig(
  getConfig(data),
  chartdiv.value,
  am4charts.XYChart,
)
```

I tried to `console.log` data and I see that data has the order I want it to have, but in the end the chart displays it in a different way: the order is totally reversed. 

<img width="1194" alt="Снимок экрана 2024-01-03 в 17 11 33" src="https://github.com/amcharts/amcharts4/assets/40761402/fdba3229-cf94-4b28-ba04-739b5d0e7fbd">

Could you tell me, please, what might be a reason?

**Comment by martynasma** [comment]
The chart never sorts data.

Please note that vertical CategoryAxis will show categories from the bottom up. So if your "TOTAL" category is first in data, it will be shown at the bottom.

You may want to inverse the order if you need to:

```JavaScript
categoryAxis.renderer.inversed = true;
```

**Comment by eduardmavliutov** [comment]
@martynasma thank you a lot for a quick response. 

> vertical CategoryAxis will show categories from the bottom up

I must have missed that while reading the docs, now everything is clear. Added a proper sorting keeping the order you mentioned in mind. 
<img width="877" alt="Снимок экрана 2024-01-08 в 07 39 07" src="https://github.com/amcharts/amcharts4/assets/40761402/18b1d9d2-ae38-4ad3-a41b-ff8e7f903690">
