### ISSUE TITLE
Format value in Y-Axis In millions or thousands

### ISSUE THREAD

**Issue by ranjeetmali** [amcharts/amcharts4#4350]
![image](https://github.com/amcharts/amcharts4/assets/47209336/041288c6-8ddf-40d9-982a-250a6c02ed72)

In this chart, if the data contains more than one item with a value in millions, then display all labels in Y-Axis in millions, and if the values are not in millions, display them in thousands, etc.
For Example, In the above chart, I want values in Y-Axis like $0, $0.5, $1M, $1.5M, $2M, $2.5M.

![image](https://github.com/amcharts/amcharts4/assets/47209336/feec3831-b526-4e48-9b1b-60d9781dfae8)
And In this case
I want values like $0, $0.5B, $1B, $1.5B, $2B

Can this be possible?

**Comment by martynasma** [comment]
Yes.

Please refer to these tutorials:
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/
https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Formatting_labels

**Comment by ranjeetmali** [comment]
Thank you @martynasma 
I apply the above solution you suggested
```
valueAxis.numberFormatter = new NumberFormatter();
        valueAxis.numberFormatter.numberFormat = '#.##!a';
        valueAxis.numberFormatter.bigNumberPrefixes = [
          /*{ number: 1e3, suffix: 'K' },*/
          { number: 1e6, suffix: 'M' },
          { number: 1e9, suffix: 'B' },
          { number: 1e12, suffix: 'T' },
          { number: 1e15, suffix: 'P' }
        ];
        valueAxis.numberFormatter.smallNumberPrefixes = [];
```

But when my all value is in thousands then it shows like this 
![image](https://github.com/amcharts/amcharts4/assets/47209336/b637766f-f927-4f0a-8f6f-b6d6899893f4)

Can I apply this thing dynamically?
For Example, Apply 0.5M when only one Y-axis labels in a Thousand And 0.5B when only one Y-axis labels in a Million.

**Comment by martynasma** [comment]
I'm not entirely sure I understand your question. The formatter acts independently for each number, so there's no way to apply formatting based on some other value.

If you need to apply custom formatting, you might want to consider using an adapter to define a custom formatting function:
https://www.amcharts.com/docs/v4/concepts/adapters/

**Comment by ranjeetmali** [comment]
Thank you @martynasma 
My solution comes with this code

```
let isInMillion = false;
        let isInBillion = false;
        let suffixValues = { 'M': 1e6, 'B': 1e9 };
        this.items.forEach((item, index) => {
          item.values.forEach(item2 => {
            if (item2.value > 1000000000) isInBillion = true;
            if (item2.value > 1000000) isInMillion = true;
          });
        });

        if (isInBillion || isInMillion) {
          valueAxis.numberFormatter = new NumberFormatter();
          valueAxis.numberFormatter.numberFormat = '#.##!a';
          let mainBigPrefix = isInBillion ? 'B' : 'M';

          valueAxis.numberFormatter.bigNumberPrefixes = [
            { number: suffixValues[mainBigPrefix], suffix: mainBigPrefix }
          ];
          valueAxis.numberFormatter.smallNumberPrefixes = [];
        }
```
