### ISSUE TITLE
Show tooltip only on hover of actual chart and not on background

### ISSUE THREAD

**Issue by nikitha-keyvalue** [amcharts/amcharts4#4354]
Please find the attached codepen for a column chart
https://codesandbox.io/p/sandbox/hungry-cache-qn9d4k?file=%2Fsrc%2FApp.tsx%3A9%2C1

The chart looks like this

![Screenshot from 2024-01-10 12-15-09](https://github.com/amcharts/amcharts4/assets/111980971/6b8a7d2d-10bb-48fe-b1df-e9a98ddd24c1)

As you can see the axis tooltips and bar tooltips are shown even if the cursor is in background.How can I modify the config so that the tooltips are shown only on hover of the actual bars ?

**Comment by martynasma** [comment]
You need to disable cursor tooltips as well as move `tooltipText` directly to columns for your series:

```JavaScript
series: [
  {
    type: "ColumnSeries",
    name: "Quantity Ordered",
    dataFields: {
      categoryX: "Product Category",
      valueY: "Quantity Ordered",
    },
    cursorTooltipEnabled: false,
    columns: {
      tooltipText:
        "{categoryX.formatNumber('#,###.##')}: [bold]{valueY.formatNumber('#,###.##')}[/]",
    },
  },
],
```

**Comment by martynasma** [comment]
No, I'm afraid. The axis tooltips are shown independently of the series.

**Comment by nikitha-keyvalue** [comment]
Okay, is it possible to show default cursor on hovering over the bars and hand icon on hovering over the white background?

**Comment by martynasma** [comment]
Yes: https://www.amcharts.com/docs/v4/tutorials/manipulating-mouse-cursor-style/

**Comment by nikitha-keyvalue** [comment]
How do I modify this for line charts for the same behaviour ?

```
series: [
  {
    type: "ColumnSeries",
    name: "Quantity Ordered",
    dataFields: {
      categoryX: "Product Category",
      valueY: "Quantity Ordered",
    },
    cursorTooltipEnabled: false,
    columns: {
      tooltipText:
        "{categoryX.formatNumber('#,###.##')}: [bold]{valueY.formatNumber('#,###.##')}[/]",
    },
  },
],
```

**Comment by martynasma** [comment]
E.g.:

```JavaScript
series: [
  {
    type: "ColumnSeries",
    name: "Quantity Ordered",
    dataFields: {
      categoryX: "Product Category",
      valueY: "Quantity Ordered",
    },
    cursorTooltipEnabled: false,
    columns: {
     cursorOverStyle: am4core.MouseCursorStyle.pointer,
      tooltipText:
        "{categoryX.formatNumber('#,###.##')}: [bold]{valueY.formatNumber('#,###.##')}[/]",
    },
  },
],
```

**Comment by nikitha-keyvalue** [comment]
What I meant was how to show tooltip only on hover of data points for line charts ?

Currently I have added the columns object inside the series of line charts.But the tooltip is not at all shown in this case.

Here is the config of the Line chart


`{
  "colors": {
    "list": [
      "#4287f5",
      "#f0a34a",
      "#f86b9e",
      "#e64e36",
      "#f4c25c",
      "#c3d84a",
      "#8bc959",
      "#a73ed2"
    ]
  },
  "chartContainer": {
    "children": [
      {
        "type": "Container",
        "paddingBottom": 0,
        "paddingTop": 0,
        "paddingLeft": 0,
        "paddingRight": 0
      }
    ]
  },
  "legend": {
    "position": "bottom",
    "maxHeight": 85,
    "scrollable": true
  },
  "cursor": {
    "type": "XYCursor",
    "behavior": "ZoomX",
    "maxTooltipDistance": 20
  },
  "responsive": {
    "enabled": true
  },
  "xAxes": [
    {
      "id": "c1",
      "type": "CategoryAxis",
      "title": {
        "text": "Skill Category"
      },
      "renderer": {
        "line": {
          "isMeasured": false
        },
        "grid": {
          "template": {
            "disabled": true
          }
        },
        "labels": {
          "template": {
            "rotation": -45,
            "horizontalCenter": "right",
            "verticalCenter": "middle",
            "truncate": true,
            "maxWidth": 200,
            "dy": -10
          }
        },
        "minGridDistance": 20
      },
      "tooltipText": "{category.formatNumber('#,###.##')}",
      "dataFields": {
        "category": "Skill Category"
      }
    }
  ],
  "yAxes": [
    {
      "id": "v1",
      "type": "ValueAxis",
      "chart_id": "373b6076-5885-4f2d-a000-904867115df7",
      "title": {
        "text": "Count of Hiring Level"
      },
      "dataFields": {
        "value": "Hiring Level"
      },
      "renderer": {
        "minWidth": 15,
        "minGridDistance": 40,
        "labels": {
          "template": {
            "horizontalCenter": "right",
            "verticalCenter": "middle",
            "truncate": true,
            "maxWidth": 200
          }
        },
        "grid": {
          "location": 0
        }
      }
    }
  ],
  "metaInfo": {
    "chart_id": "373b6076-5885-4f2d-a000-904867115df7"
  },
  "series": [
    {
      "type": "LineSeries",
      "name": "Hiring Level",
      "dataFields": {
        "categoryX": "Skill Category",
        "valueY": "Hiring Level"
      },
      "cursorTooltipEnabled": false,
      "columns": {
        "tooltipText": "{categoryX.formatNumber('#,###.##')}: [bold]{valueY.formatNumber('#,###.##')}[/]"
      }
    }
  ]
}`

**Comment by martynasma** [comment]
LineSeries does not have any identifiable hover points, like ColumSeries has columns.

If you need hovers only on data items in LineSeries, you need to add bullets:
https://www.amcharts.com/docs/v4/concepts/bullets/#Adding_bullets_to_series

Add `tooltipText` to bullet.

**Comment by nikitha-keyvalue** [comment]
On adding bullets for large data, all the bullets are hidden due to minBulletDistance.This is not ideal since the tooltips also becomes inaccessible.Is there any way to solve this ?

**Comment by martynasma** [comment]
If you absolutely need to show tooltip only on hover, you will need to increase `minBulletDistance`. If you don't want the actual bullet to be visible, to can set its `fillOpacity` to `0`. Hovers, will still work.

However, if you have more data points than 100-200, this will be bad UX for the user as it will be very difficult to hover over specific point that they want to hover.

Not to mention, having a lot of bullets might have a significant impact on performance.

I strongly suggest using `XYCursor` for displaying tooltip of the closest data point.

**Comment by nikitha-keyvalue** [comment]
For line series , I have given the cursor to the container as pointer and inside the series was given as
```   series: [
      {
        type: "LineSeries",
        name: "Quantity Ordered",
        cursorOverStyle: am4core.MouseCursorStyle.default,
        dataFields: {
          categoryX: "Product Name",
          valueY: "Quantity Ordered",
        },
        tooltipText:
          "{categoryX.formatNumber('#,###.##')}: [bold]{valueY.formatNumber('#,###.##')}[/]",
      },
    ],
```
However the cursor is still pointer on hovering over the actual line chart? Is this a problem with the config or is it not possible ?

Here is the codesandbox for the above mentioned issue 

https://codesandbox.io/p/sandbox/hungry-cache-qn9d4k?file=%2Fsrc%2Fpages%2FBar.tsx%3A124%2C34
