### ISSUE TITLE
StepLineChart doesn't look right when it's small

### ISSUE THREAD

**Issue by nodenong** [amcharts/amcharts4#4355]
I am trying to create a mini version of a step-line chart. However i had encountered that the step-line doesn't look right after the chart become smaller. Please ignore the overlay lineChart for now.
I had tried changing the minGridDistance to a lower value, it work at first, but when the xAxis range got bigger, the issue persist.

When the chart is small, the step line doesn't look right
![image](https://github.com/amcharts/amcharts4/assets/39426394/6f4925f9-40be-466b-a5e0-ef769d4d4102)

This is what it look like when the chart is bigger. Which is what i want it to look like when its small. (without the grid and axis)
![image](https://github.com/amcharts/amcharts4/assets/39426394/72ded868-b592-4cd5-b07d-7491c5d6223a)

Any idea how do i fix this? Thank you.

 - amCharts version 4.10.36
 - Chrome
 - ReactJS

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by nodenong** [comment]
[https://codepen.io/Ong-Le-Foo/pen/bGZgjBv](url)
I made a sample here.
Click the button then the chart will display

As can be seen from the sample, when its small, the step line behaviour are not correct
Moreover, it is already not correct on a larger view, there are some diagonal line as show in picture below.
![image](https://github.com/amcharts/amcharts4/assets/39426394/8342545f-ed11-4887-bdb2-ea527692bcde)

**Comment by martynasma** [comment]
Thanks.

You have this in your code:

```JavaScript
am4core.options.minPolylineStep = 10;
```

It selectively removes data points from display, which causes the StepLineSeries to misbehave.

I suggest you remove this line. It's for the LineSeries.

**Comment by nodenong** [comment]
This seems
