### ISSUE TITLE
Drawing custom lines shape over map lines.

### ISSUE THREAD

**Issue by harish81** [amcharts/amcharts4#4356]
Hi Guys,

I need to customize amchart map chart to show trade flow lines in track shape. Like this (below image))

![image](https://github.com/amcharts/amcharts4/assets/13818806/4183d700-aa3e-4d0b-a9de-73f596de9d5f)

In order to effectively visualize trade flow lines in a track shape, it is necessary to customize the amchart map chart. These lines should start off narrow at the beginning and gradually become wider as they progress towards the end. The weight or thickness of each line should be determined by its corresponding value. This customization will allow for a more comprehensive and detailed representation of the trade flow data.

I have tried with custom shape but not working well. The working codepen demo is here: https://codepen.io/harish81/pen/PoLbONQ?editors=0010

Please help me with general ideas how we can achieve this

Thanks in advance!

**Comment by martynasma** [comment]
I'm afraid there's no way to make lines with a shape like that.
