### ISSUE TITLE
How to show the all bars in race chart for the first year

### ISSUE THREAD

**Issue by faizan-naeemm** [amcharts/amcharts4#4357]
I am creating Race chart using amcharts v4

The problem I am getting is that initially it just shows the 1 bar of my first year . I saw the example given in documentation , there is a same problem . 

https://www.amcharts.com/demos-v4/bar-chart-race-v4/

**Comment by martynasma** [comment]
It's not a "problem" it's just that the first slide has one column.

If you need more columns in the first year, you need to modify the data accordingly.
