### ISSUE TITLE
Change of Direction of Graph to RTL

### ISSUE THREAD

**Issue by Suleman12** [amcharts/amcharts4#4358]
I want in my am charts 4 graph to display my graph from right to left in arabic View Also. How can I achieve in doing that.
Currently it shows the Graph  in LTR View like this in RTL/Arabic View:

![ScreenshotRTL](https://github.com/amcharts/amcharts4/assets/24837687/61684254-84f5-4395-8c65-78fd92677c0a)

**Comment by martynasma** [comment]
Set `xAxis.renderer.inversed = true`:
https://www.amcharts.com/docs/v4/reference/iaxisrendererproperties/#inversed_property

**Comment by Suleman12** [comment]
I have applied this property the Graph becomes RTL but having issue with the value axis .The Index Values Still Appearing on the left like in this first graph. How can I Invert them also. Thanks
[
<img width="396" alt="ScreenshotRTL" src="https://github.com/amcharts/amcharts4/assets/24837687/d1fc6b12-16da-4c92-872f-e1d89b28a06c">
](url)
