### ISSUE TITLE
How to change the data set in different years of race chart

### ISSUE THREAD

**Issue by faizan-naeemm** [amcharts/amcharts4#4359]
I have plotted a race chart , but for my all year object there is different data set for example .. 

var allData = {
  "2003": [
    {
      "network": "Facebook",
      "MAU": 4020
    },
    {
      "network": "Flickr",
      "MAU": 0
    }
  ],
  "2004": [
    {
      "network": "Meta",
      "MAU": 2000
    },
    {
      "network": "Flickr",
      "MAU": 3675135
    }
  ]
  
  in 2003 i have facebook , in 2004 I have meta , but in chart it is showing the facebook in 2004 with the value of meta .

**Comment by zeroin** [comment]
I would suggest to use the same name, like Meta (Facebook) for all the years.

**Comment by faizan-naeemm** [comment]
Its just an example , but in real problem I have different companies which are not same @zeroin

**Comment by zeroin** [comment]
In this chart: https://www.amcharts.com/demos/bar-chart-race/
we add 0 for all the existing names in each year and it solves the problem of not the same data.
