### ISSUE TITLE
Is there any event to know to when the chart is finished rendering

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#436]
Hi, 
Is there  any event to know when the chart is finished rendering, like in amcharts3 we used to have "rendered" or "drawn"

**Comment by martynasma** [comment]
Heads up, we do now have `"ready"` event which is invoked when container/chart and all its children are ready (drawn).

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by onx2** [comment]
Example code for the `"ready"` event for anyone browsing issues like this / amCharts v4 documentation without success. Hope it helps!

```
import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";

let chart = am4core.create("chartdiv", am4charts.XYChart);

chart.events.on('ready', () => {
  console.log('ready');
});

// Chart code here like adding data and legend

```

Documentation that I found useful:
https://www.amcharts.com/docs/v4/reference/xychart/
https://www.amcharts.com/docs/v4/concepts/event-listeners/

+1 for adding in event examples like `"ready"` to the main documentation page.

If anyone can spot where the `"ready"` event is mentioned in the actual docs and not on a GitHub issue, please share the link with me 😄

**Comment by AndriusRimkus** [comment]
@onx2 https://www.amcharts.com/docs/v4/reference/ixychartevents/#ready_property

**Comment by onx2** [comment]
@AndriusRimkus Thank you!

**Comment by enriquepiatti** [comment]
what event we should use after updating data? (Ready is not fired): https://github.com/amcharts/amcharts4/issues/1485

**Comment by panksi** [comment]
> Heads up, we do now have `"ready"` event which is invoked when container/chart and all its children are ready (drawn).

Believe it or not, I have a situation where transitionended event fires after the chart is ready.
This one is good: 
![image](https://user-images.githubusercontent.com/16855132/171605519-2bf7160a-a9e2-4f9c-8a3c-131c97ead7f2.png)

But sometimes: 
![image](https://user-images.githubusercontent.com/16855132/171606214-abb6693f-a303-4020-8fd5-f9d15ed850cf.png)
