### ISSUE TITLE
Min valueAxis line

### ISSUE THREAD

**Issue by PedroHGaspar** [amcharts/amcharts4#4360]
i've tried to put a grey line on the min value from the API, but for somehow it doesn't work. If i put valueAxis.min = 0, it creates a grey line on the 0, but i want the valueAxis.min to be the minor value from the API:

![image](https://github.com/amcharts/amcharts4/assets/37162818/439f1cba-e320-49cd-a766-e5b29a618d2c)

I want this line here(this is what appears when i put valueAxis.min = 0:

![image](https://github.com/amcharts/amcharts4/assets/37162818/2694eae6-3308-47c0-b602-7838bcb7e510)

**Comment by zeroin** [comment]
It's difficult to tell from the picture, but most likely you try to access min right after you initialize the chart. `min` value is calculated later. You can add `datavalidated` event listener and the access it:

```
chart.events.on("datavalidated", ()=>{
  console.log(valueAxis.min)
})
```

**Comment by PedroHGaspar** [comment]
> It's difficult to tell from the picture, but most likely you try to access min right after you initialize the chart. `min` value is calculated later. You can add `datavalidated` event listener and the access it:
> 
> ```
> chart.events.on("datavalidated", ()=>{
>   console.log(valueAxis.min)
> })
> ```

that's it, it's almost working. Now, there is a way for me to make that grey line only at that valueAxis.min?
![image](https://github.com/amcharts/amcharts4/assets/37162818/995ad0c9-8e26-42e2-9922-0bfd720b62cc)

In this case, i want the grey line to be only on the 0.5. Is it possible?

**Comment by zeroin** [comment]
`axis.renderer.grid.template.disabled = true` should do the thing.

**Comment by PedroHGaspar** [comment]
> `axis.renderer.grid.template.disabled = true` should do the thing.

Thanks, it worked!!!
