### ISSUE TITLE
Text is in pie chart

### ISSUE THREAD

**Issue by s0n11c39** [amcharts/amcharts4#4361]
I have integrated amcharts4 on my website.

![image](https://github.com/amcharts/amcharts4/assets/156957024/08aab22f-4776-4eec-8d85-abac667cf298)

When the website is opened on the mobile phone, the cake diagrams should be displayed one below the other.
It works quite well, but there is an error and I don't know what the problem is:

![WhatsApp Image 2024-01-17 at 20 51 09 (2) Kopie](https://github.com/amcharts/amcharts4/assets/156957024/c42149ea-be96-4bb4-b1ae-2a9631b0eeb2)

I tested the website with an iPhone 14 Pro Max and everything is displayed very well!

This view occurs on an iPhone 14 Pro and smaller devices.

I noticed that when I refresh the page it is displayed normally the next time again like in the pictures - this happens randomly.

the code I use:

[https://pastebin.com/GCA9jeqJ](https://pastebin.com/GCA9jeqJ)

I hope someone knows what to do!

**Comment by martynasma** [comment]
I can't quite reproduce the same issue with iPhone 14 Pro simulator and your code.

Yes, the labels do not fit, but they are not misplaced.

Here's what I'm testing on:
https://codepen.io/team/amcharts/full/xxBqerg/3ddee90236c68620cdf4bd991dbaa00a
