### ISSUE TITLE
In race chart there is some labels are missing 

### ISSUE THREAD

**Issue by faizan-naeemm** [amcharts/amcharts4#4362]
I am plotting amcharts 4 Race Chart. The problem I am getting is that some times there are some labels which does not appear . 
![label missing](https://github.com/amcharts/amcharts4/assets/103881348/d587a882-4f1d-4d79-9801-b4ac136f008c)

as in the attached file you can see.

this is my code 

        `  function createSeries() {
          var series = chart.series.push(new am4charts.ColumnSeries());
          series.dataFields.categoryY = "EntityName";
          series.dataFields.valueX = "EntValue";
          series.tooltipText = "{valueX.value}";
          series.columns.template.strokeOpacity = 0;
          series.columns.template.column.cornerRadiusBottomRight = 5;
          series.columns.template.column.cornerRadiusTopRight = 5;
          series.interpolationDuration = stepDuration;
          series.interpolationEasing = am4core.ease.linear;

          var labelBullet = series.bullets.push(new am4charts.LabelBullet());
          labelBullet.label.horizontalCenter = "left"; //--Default value in documentation is right. left is to show the value outside bar
          labelBullet.label.text =
            "{values.valueX.workingValue.formatNumber('#.0as')}";

          labelBullet.label.textAlign = "end";
          labelBullet.label.dx = 5; //--Default value is -10. -10 will show the value inside bar end

       
          labelBullet.label.truncate = false;
          labelBullet.label.wrap = false;
          labelBullet.label.maxWidth = 200;
          //--✅ End: Bar Lenght

          labelBullet.label.fontSize = ismobile == 1 ? 12 :  15;

      

          chart.zoomOutButton.disabled = true;

          // as by default columns of the same series are of the same color, we add adapter which takes colors from chart.colors color set
          series.columns.template.adapter.add("fill", function (fill, target) {
            //--use below return if do not want to use BarColors colors
            return chart.colors.getIndex(target.dataItem.index);

         

          });

        

          return series;
        }

        var series = createSeries();

       var year = maxYear;
      label.text = year.toString();

      var interval;

    function play() {
    interval = setInterval(function(){
    nextYear();
    }, stepDuration)
    nextYear();
     }
 
    function stop() {
    if (interval) {
    clearInterval(interval);
    }
     }

       function nextYear() {
      year--

     if (year < minYear) {
     year = maxYear;
      }

     var newData = allData[year];
    var itemsWithNonZero = 0;
    for (var i = 0; i < chart.data.length; i++) {
    chart.data[i].EntValue = newData[i].EntValue;
    if (chart.data[i].EntValue > 0) {
      itemsWithNonZero++;
    }
     }

    if (year == maxYear) {
    series.interpolationDuration = stepDuration / 4;
    valueAxis.rangeChangeDuration = stepDuration / 4;
    }
    else {
    series.interpolationDuration = stepDuration;
    valueAxis.rangeChangeDuration = stepDuration;
     }

    chart.invalidateRawData();
    label.text = year.toString();

    categoryAxis.zoom({ start: 0, end: itemsWithNonZero / categoryAxis.dataItems.length });
     }

         categoryAxis.sortBySeries = series;

        chart.data = JSON.parse(JSON.stringify(allData[year]));
        categoryAxis.zoom({ start: 0, end: 1 / chart.data.length });
     
        if (languageId == 1) {
          chart.rtl = true;
        }

         chart.events.on('ready', () => {
          year = maxYear + 1
        nextYear();
       setTimeout(function () {
             playButton.isActive = true; // this starts interval
          }, 4000);
      });
`

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by faizan-naeemm** [comment]
sure

**Comment by faizan-naeemm** [comment]
@martynasma  here is the codepen link 

https://codepen.io/faizannaeem11/pen/eYXvqep

**Comment by martynasma** [comment]
Are you getting that issue in the CodePen you posted? I don't.

**Comment by faizan-naeemm** [comment]
yes i am getting this issue in codepen

**Comment by faizan-naeemm** [comment]
![sa](https://github.com/amcharts/amcharts4/assets/103881348/ba0fc0e9-72a7-4c77-8ebd-3fd4b94fc5c6)

**Comment by martynasma** [comment]
I suspect it might be happening because of the div resize while the chart is building itself.

Try moving this code before chart is created:

```JavaScript
        var chartdiv = document.getElementById("chartdiv");
        if ("0" === "1") {
          chartdiv.style.height = m == "1" ? "95vh" : "90vh";
        } else {
          chartdiv.style.height = m == "1" ? "95vh" : "92vh";
        }
```

**Comment by faizan-naeemm** [comment]
it works . thankyou
