### ISSUE TITLE
Line Graph Smooth Lines

### ISSUE THREAD

**Issue by Suleman12** [amcharts/amcharts4#4364]
I have This Graph. The Graph Does not have smooth lines as a line graph should have. I have setting tensionX Property and also monotoneX Property but to no Effect. Can you please suggest how can I make this graph have smooth lines.
![graphpic](https://github.com/amcharts/amcharts4/assets/24837687/81fb30db-f41c-4d40-ba9f-821e017ba4cd)

**Comment by martynasma** [comment]
Try this setting:
https://www.amcharts.com/docs/v4/concepts/performance/#Simplifying_paths

Or, data point grouping:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping
