### ISSUE TITLE
Am4Charts Radar Chart: I want my data point not show on the axisrange I want to show them in between

### ISSUE THREAD

**Issue by Swaraj55** [amcharts/amcharts4#4365]
Below I share the am4chart example data show on the axisRange

```JavaScript
// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

/* Create chart instance */
var chart = am4core.create("chartdiv", am4charts.RadarChart);

/* Add data */
chart.data = [{
  "country": "Lithuania",
  "litres": 501
}, {
  "country": "Czechia",
  "litres": 301
}, {
  "country": "Ireland",
  "litres": 266
}, {
  "country": "Germany",
  "litres": 165
}, {
  "country": "Australia",
  "litres": 139
}, {
  "country": "Austria",
  "litres": 336
}, {
  "country": "UK",
  "litres": 290
}, {
  "country": "Belgium",
  "litres": 325
}, {
  "country": "The Netherlands",
  "litres": 40
}];

/* Create axes */
var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";

var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.renderer.axisFills.template.fill = chart.colors.getIndex(2);
valueAxis.renderer.axisFills.template.fillOpacity = 0.05;

/* Create and configure series */
var series = chart.series.push(new am4charts.RadarSeries());
series.dataFields.valueY = "litres";
series.dataFields.categoryX = "country";
series.name = "Sales";
series.strokeWidth = 3;
```

<img width="434" alt="image" src="https://github.com/amcharts/amcharts4/assets/48621208/889ec3c7-d7e3-426d-bb72-8b48397d30eb">

I want something like this

<img width="386" alt="image" src="https://github.com/amcharts/amcharts4/assets/48621208/ad3b90e0-bd0e-40c3-b6e2-a0322c2d6047">

this is example I see in an5charts but not know how to do in am4charts

**Comment by martynasma** [comment]
You can set `bent` property for axis labels.

```JavaScript
categoryAxis.renderer.labels.template.bent = true;
```

https://www.amcharts.com/docs/v4/reference/axislabelcircular/#bent_property

**Comment by Swaraj55** [comment]
I used this property in my above example it did not work in am4charts. 
Below I shared the SS I used property but not work.

<img width="826" alt="image" src="https://github.com/amcharts/amcharts4/assets/48621208/7bdc2a35-845a-497b-9161-d692c7ed292d">

I want the bullets should not show on the axis for example 
`
{
  "country": "Belgium",
  "litres": 325
}
`
they show in the axis but I not want to show on axis just take am5charts example they in middle

**Comment by martynasma** [comment]
Please refer to this tutorial about positioning axis elements:
https://www.amcharts.com/docs/v4/concepts/axes/#Positioning_grid_and_labels

**Comment by Swaraj55** [comment]
Thanks, it is working for me.
