### ISSUE TITLE
Ticks on a 3D Pie Chart are misaligned 

### ISSUE THREAD

**Issue by AO-owen** [amcharts/amcharts4#4366]
before mouse over to any slice, the tick is misaligned 

![image](https://github.com/amcharts/amcharts4/assets/35586278/b812e255-e322-4097-8625-664b41b0aad3)

after mouse over to the red slice, then the red slice tick become to normally, is there any method can reset the ticks to normally?
![image](https://github.com/amcharts/amcharts4/assets/35586278/d72ac9c4-8787-4e91-9588-239be8cd959e)

``` javascript
am4core.useTheme(am4themes_animated);

var chart = am4core.create("chartdiv", am4charts.PieChart3D);
chart.hiddenState.properties.opacity = 0; // this creates initial fade-in

chart.data = [
  {
    country: "Lithuania",
    litres: 74.1
  },
  {
    country: "Czech Republic",
    litres: 8.6
  },
  {
    country: "Ireland",
    litres: 2.7
  },
  {
    country: "Germany",
    litres: 2.5
  },
  {
    country: "Other",
    litres: 12.1
  },
];

chart.radius = 120
chart.depth = 15;

chart.legend = new am4charts.Legend();
chart.legend.position = "right";

var series = chart.series.push(new am4charts.PieSeries3D());
series.tooltip.disabled= true
series.dataFields.value = "litres";
series.dataFields.category = "country";
series.slices.template.cornerRadius = 5;
series.colors.step = 3;
```

**Comment by martynasma** [comment]
Updates on amCharts 4 are frozen, except on critical bugs. However, you may fix it like this:

```JavaScript
chart.events.on("datavalidated", function() {
  series.slices.each(function(slice) {
    slice.invalidate()
  });
});
```

**Comment by AO-owen** [comment]
> Updates on amCharts 4 are frozen, except on critical bugs. However, you may fix it like this:
> 
> ```js
> chart.events.on("datavalidated", function() {
>   series.slices.each(function(slice) {
>     slice.invalidate()
>   });
> });
> ```

This is what I want, thankyou
