### ISSUE TITLE
x axis labels are not shown when skipEmptyPeriods is set to true

### ISSUE THREAD

**Issue by nikitha-keyvalue** [amcharts/amcharts4#4367]
I am currently using amcharts v4 for my project. When skipEmptyPeriods is set to true for x-axis, most of the labels on the x-axis are not shown. I want to show labels for all the plotted datapoints on the x axis.

![Screenshot from 2024-01-23 14-11-32](https://github.com/amcharts/amcharts4/assets/111980971/a22804ff-effe-4f75-a141-16c8de9312a6)

**Comment by martynasma** [comment]
Maybe try reducing `minGridDistance`.

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by nikitha-keyvalue** [comment]
That did not seem to work. This is my x axes config for your reference: 
`[
  {
    "id": "c1",
    "type": "DateAxis",
    "title": {
      "text": "Date of Invoice"
    },
    "renderer": {
      "line": {
        "isMeasured": false
      },
      "grid": {
        "template": {
          "disabled": true
        }
      },
      "labels": {
        "template": {
          "rotation": -45,
          "horizontalCenter": "right",
          "verticalCenter": "middle",
          "truncate": true,
          "maxWidth": 200,
          "dy": -10,
          "location": 0.5,
          "adapter": []
        }
      },
      "minGridDistance": 10
    },
    "tooltipText": "",
    "dataFields": {
      "category": "Date of Invoice"
    },
    "dateFormatter": {
      "inputDateFormat": "yyyy-MM-dd'T'HH:mm:ss"
    },
    "groupData": false,
    "baseInterval": {
      "timeUnit": "day",
      "count": 1
    },
    "dateFormats": {
      "second": "ss",
      "minute": "mm",
      "hour": "HH:mm",
      "day": "dd-MM-yyyy",
      "week": "ww-yyyy",
      "month": "MMM-yyyy",
      "year": "yyyy"
    },
    "periodChangeDateFormats": {
      "second": "mm:ss",
      "minute": "HH:mm",
      "hour": "dd-MM-yy HH:mm",
      "day": "dd-MM-yyyy",
      "week": "ww-yyyy",
      "month": "MMM-yyyy",
      "year": "yyyy"
    },
    "skipEmptyPeriods": true,
    "cursorTooltipEnabled": true,
    "gridIntervals": [
      {
        "timeUnit": "day",
        "count": 206
      }
    ]
  }
]`

**Comment by martynasma** [comment]
> That did not seem to work. 

Unfortunately, I don't have any other suggestions.

amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.
