### ISSUE TITLE
How to start the legends from right hand side 

### ISSUE THREAD

**Issue by faizan-naeemm** [amcharts/amcharts4#4368]
I have a question regarding the starting point of the legends , I have a requirement where I need to display a pie chart that contains Arabic content , when the legends break in to the multiple lines , it starts from left hand side which makes the alignment wrong. I want to start the legends from right hand side of the page

As displayed in picture.
![legend](https://github.com/amcharts/amcharts4/assets/103881348/9e183883-cd58-41a7-810f-02b6115b0111)

This is my working code pen link : https://codepen.io/faizannaeem11/pen/yLwomGZ

**Comment by martynasma** [comment]
I'm afraid there's no way to do that. Sorry 🙁

**Comment by faizan-naeemm** [comment]
@martynasma  it should be there as amcharts claim to have support for the languages (R-H-S)
