### ISSUE TITLE
On dispose of bullet, EventDispatcher is disposed error

### ISSUE THREAD

**Issue by JayAsuncion** [amcharts/amcharts4#4370]
**Bug description**

I am trying to delete a bullet without re-rendering the whole chart. I am using the `.dispose()` method of the specific bullet I want to delete.

Amcharts version: 4.10.38

Here is a codepen to replicate the EventDispatcher is disposed error message overlay.
1. Click the Remove bullet 1 button
2. Click the Show right panel button
3. Notice the EventDispatcher is disposed message on the chart

https://codepen.io/jayasuncion/pen/gOEGZpa

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.
