### ISSUE TITLE
Data is not being shown completely

### ISSUE THREAD

**Issue by nikitha-keyvalue** [amcharts/amcharts4#4371]
Please find the attached code

https://codesandbox.io/p/sandbox/hungry-cache-qn9d4k?file=%2Fsrc%2Fconstants.ts%3A21%2C7

Here eventhough the second data point is  '[inconsistent] the row and column count in data review page is shown "undefined'
axis label as well as tooltip shows the row and column count in data review page is shown "undefined.Why is it being cut off ?

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.
