### ISSUE TITLE
Why is my custom icon not using its css class properties?

### ISSUE THREAD

**Issue by MaxStacks** [amcharts/amcharts4#4372]
**Question**

Why is my custom icon not using its css class properties?

On a serpentine chart, I put 2 small Rectangles adjacent to the start and end of the Curved Axis. Both Rectangles are:
-  children of a Container who's parent is the Chart
-  placeholders for svg icons (e.g. race flags for start and finish respectively)
-  identified by class name using their Container's id property

I need these icons to stay beside the Curved Axis start and end points. On smartphones this is easy, since a minimum chart size can be used and scrolling is fine.

On full-screen, the chart stretches up too much and the icon positions change. Using percent based positioning helps, but not enough. Despite many attempts I can't seem to affect the icons with the css class amcharts-finishFlag.

I'd appreciate any help using ccs classes in my code, or even a better way of aligning the blue Rectangles so that Viewport height does not change their position.

Here is my codepen:
codepen.io/Owen-MacWilliam/pen/JjzKXoo

Amcharts 4 using Chrome web browser.
I am ultimately coding in Typescript and Angular 

**Additional context**

Two amcharts tutorials I have based some of my code off:
amcharts.com/docs/v4/tutorials/chart-element-class-names-and-css/
amcharts.com/docs/v4/tutorials/freeze-horizontal-axis/

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.
