### ISSUE TITLE
How to Plot the Chart in the Same Order of Data Given as Input ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#4373]
Hi,
I'm designing a stacked bar chart with two series originated and received.
when chart is drawn I'm getting data plotted in reverse order.

Data given as Input : 
`chart.data = [
    {
        "Originated": 0,
        "Received": 19484.33,
        "name": "JK"
    },
    {
        "Originated": 0,
        "Received": 16776.13,
        "name": "MN"
    },
    {
        "Originated": 0,
        "Received": 35,
        "name": "VK"
    }
]`

Output Chart : 
![Screenshot from 2024-01-31 18-23-57](https://github.com/amcharts/amcharts4/assets/74599304/1ce07786-82c3-4875-a416-d4fe9f436633)

I want JK should be the first bar then MN then VK as in the order of input data given to the chart.

Can you please help me to fix this?

Thanks in advance

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by VineelaKantamneni** [comment]
Hi,
categoryAxis.renderer.inversed = true; 

I kept inversed as true that's why I got like above after removing that it's fine.
Thank you for the response.
