### ISSUE TITLE
Tool tip is not appearing on the bars of the chart while navigating with keyboard.

### ISSUE THREAD

**Issue by msftedad** [amcharts/amcharts4#4374]
**Bug description**

If the tooltip will not appear on the bar graph of the chart, then the color-blind users who also rely on keyboard will not get the information of the graph and they may get confused and may face problems in accessing the UI properly.

**Repro steps**
1.Open [URL](https://www.amcharts.com/demos-v4/funnel-with-gradient-fill-v4/) in edge dev browser.
2.Navigate to the chart present on the page using tab key.
3.Observed that tooltip is defined to the chart is accessible using keyboard or not.

**Actual result**
Tooltip does not appear on the bars of the chart while navigating with keyboard; however, it appears on hovering with mouse on the graphs.

**Expected result**
Tooltip must appear on the bar graph chart while navigating with keyboard on them.

**Environment (if applicable)**
OS Build: Windows 11 Enterprise Insider Preview 22H2 (23541.1000)
Edge Browser: Version 115.0.1880.3 (Official build) dev (64-bit)

**Attachments**
https://github.com/amcharts/amcharts4/assets/93735775/6d1383e4-0ad0-49b1-97b4-fb3d9b77219e

**Comment by martynasma** [comment]
Please refer to this documentation on how to enable hover tooltips on element focus:
https://www.amcharts.com/docs/v4/concepts/accessibility/#Tooltips

**Comment by msftedad** [comment]
Hi Team, "We're currently in discussiom with the PO team. Once we receive the information from them, we'll promptly update you.
