### ISSUE TITLE
Labels are getting overlapped by other data in chart

### ISSUE THREAD

**Issue by Ashishvkale** [amcharts/amcharts4#4375]
Hello team,

Using amchart4, the legacy version.
I'm working on a Gantt chart which shows some data of daily activities going on field.

Problem statement : 
<img width="1300" alt="Screenshot 2024-02-01 at 11 53 11 AM" src="https://github.com/amcharts/amcharts4/assets/97302990/bf99bede-0cf1-43ee-98ff-689d411a0bc0">
img 1
<img width="946" alt="Screenshot 2024-02-01 at 11 54 03 AM" src="https://github.com/amcharts/amcharts4/assets/97302990/7751de73-b7e2-484d-b4be-238afd94a537">
img 2

      In the above images (img 1 & 2) I'm trying to show the full title text of the activities to make it more readable.
      But when another activity comes ahead of its text gets overlapped , Also when I change the time frame text gets overlapped by other activities
      I'm now stacking the activities by checking there start and end date.

Expected behavior :
     
<img width="1134" alt="Screenshot 2024-02-01 at 11 56 05 AM" src="https://github.com/amcharts/amcharts4/assets/97302990/0f68057e-c4f2-4b93-b5cb-35e8bffccece">
img 3

      
      What I wanted to achive is , to get the end point location of the title text ends. and from there we can calculate if activity is overlapping it
      same as I achieved (Pushed manually/hardcoded)  In the given image (img 3) the title is fully readable and activities are getting stacked below if the text is touching another activity
      
      So somehow, I wanted to get the date or location of the title text dynamic end point, so I can compare it with another activity if it's overlapping it
               The main intent behind this is to show the full text without overlapping the things and messing the core functionality of Gantt chart

I would greatly appreciate your input and insights on the matter.
If there are any suggestions, references, or documentation that could help me in obtaining the expected result, it would be incredibly valuable.

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.

**Comment by Ashishvkale** [comment]
I tried reaching contact@amcharts.com and also posted the same on stackOverFlow [https://stackoverflow.com/questions/77918294/amchart4-label-text-gets-overlapped-by-other-lineseries-chart-data](link)
But no success yet. Hoping for some positive  direction here

**Comment by Ashishvkale** [comment]
I tried reaching [contact@amcharts.com](mailto:contact@amcharts.com) and also posted the same on stackOverFlow [https://stackoverflow.com/questions/77918294/amchart4-label-text-gets-overlapped-by-other-lineseries-chart-data](https://github.com/amcharts/amcharts4/issues/link)
But no success yet. Hoping for some positive direction here
