### ISSUE TITLE
How to get the labesl on top of chart without creating container 

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#4376]
Hi, I need to create a stacked bar chart like the one below with the labels on the top of each bar.
![image](https://github.com/amcharts/amcharts4/assets/74599304/1dee96bc-89c8-4564-be43-f42b2809fc89)

I was able to design the chart but was unable to give the labels can you please help me with this.
Thanks for the help

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v4/tutorials/totals-on-column-stacks/

**Comment by VineelaKantamneni** [comment]
Thank you so much. It's working but I got the below issue. Help me to fix this.

When the axis max value is 6K USD and the series total value is around 5997.2 USD. The label is not visible. Please refer to below screenshot
![image](https://github.com/amcharts/amcharts4/assets/74599304/8f756534-8cd1-4b47-b106-388463220e6c)

**Comment by martynasma** [comment]
This will help:
https://www.amcharts.com/docs/v4/concepts/bullets/#Bullets_outside_plot_area

**Comment by VineelaKantamneni** [comment]
That's worked thank you so much.
