### ISSUE TITLE
Getting blur chart image !

### ISSUE THREAD

**Issue by Ashishvkale** [amcharts/amcharts4#4378]
Hello there

Using amcharts4 legacy version
const chartImageData = this.chart?.exporting.getImage("png")

I'm getting blur chart image via getImage("png").

I'm able to get clear image when calling getImage while chart initialisation
But when I move scrollbars, etc.  And then hit getImage then getting blurred image 
same code same everything for both.

Any help will be appreciated

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.
