### ISSUE TITLE
change "resolution" of dataset at zoom level

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#438]
it's possible to change the resolution of a dataset based on zoom level?

at full zoom out do an avg every 50 samples
at 20% zoom do avg every 30 samples
at 50% zoom do avg every 10 samples
at 100% zoom no avg

this can be achived in some way?

**Comment by martynasma** [comment]
I'm afraid dynamic data set resolution and data point grouping is not yet available.

We might introduce it at some point in the future, but I can't provide an ETA.

That said, technically, it should be possible to catch some axis event, then update the whole data set of the chart. Do you think this could be something you'd like to take a stab at?

**Comment by martynasma** [comment]
This has been already implemented:
https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping
