### ISSUE TITLE
Not able to print whole chart

### ISSUE THREAD

**Issue by Ashishvkale** [amcharts/amcharts4#4380]
Hi
I'm using export menu and other getImage for printing the gantt chart
But the limitation is Im only able to print the rows visible in chart
I want all rows image throughout the bottom

![image](https://github.com/amcharts/amcharts4/assets/97302990/92395307-44a9-4444-81c5-4e7ec7a9a182)

Here you can see only some middle rows are shown
If I try to print , this much rows will print only 
Need to print whole chart

Thanks in advance

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.
