### ISSUE TITLE
How to change legend when use slice grouper by zoom click behavior 

### ISSUE THREAD

**Issue by AO-owen** [amcharts/amcharts4#4381]
When I use the slice grouper for pie chart to group items to 'other' and set click behavior to 'zoom', after clicking 'other' , the legends just become to disabled, is there any way to use the 'other' items to build new legends to replace the current legends

**Comment by zeroin** [comment]
Well, theoretically it is possible, but quite complicated. You should start with this tutorial:
https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items

My suggestion would be not to modify the original legend but create a separate legend for this case.
