### ISSUE TITLE
Remove Fill color from Pictorial Stacked Chart

### ISSUE THREAD

**Issue by MohitKandpal** [amcharts/amcharts4#4382]
Hi,

I am using Pictorial Stacked chart in my application and the image I am using is of tyre - 
![image](https://github.com/amcharts/amcharts4/assets/37876993/a31731ed-aee4-40fc-8aa7-27a8c901fdd9)

While rendering this image, I want to use the fill colors of this image and not of amcharts color pallet. Below is the codepen URL - https://codepen.io/mohit_k/pen/abMaZex. Is there any way to achieve this ??

I tried **series.slices.template.fill** property but it can take only one color and this image is using multiple colors. Attaching SVG as well for the reference.

![WINSUPER X3-D-3](https://github.com/amcharts/amcharts4/assets/37876993/ef52cf86-5731-4658-a226-c7aaa9ae7036)

Thanks & Regards,
Mohit Kandpal

**Comment by martynasma** [comment]
You can set the `fillOpacity = 0` to make slices transparent:

```
series.slices.template.fillOpacity = 0;
```

However that will not reveal the image itself as it is used only as a mask. You will need to add the image to the series as well.

**Comment by MohitKandpal** [comment]
Can you please guide me on how to add an **image** to a series and exactly on which attribute to bind the image?

I do know about adding an image but not sure about where to bind it in Pictorial Stacked chart.

I have attached the image above, so if you can please update the codepen.

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.
