### ISSUE TITLE
In a FunnelSeries chart, how can I show labels in the sliceLinks?

### ISSUE THREAD

**Issue by Davian99** [amcharts/amcharts4#4383]
**Question**

I have been trying to use the `labels` property exactly as it is used in the `series` with no success. Is there anyway to do this or is just impossible without creating customs labels and calculating the position dynamically?

Codepen: https://codepen.io/davian99-the-selector/pen/oNVPJyx

**Comment by martynasma** [comment]
There's no built-in label functionality for slice links, I'm afraid.
