### ISSUE TITLE
How to hide the tooltip shown for xAxis title

### ISSUE THREAD

**Issue by nikitha-keyvalue** [amcharts/amcharts4#4384]
I wish to hide the tooltip that is shown for xAxis title but still be able to show the same for when the user hovers over the axis labels and datapoints. 

Initially the behavior was that every time i hover over the axis title the previously hovered data point/ label's value is shown as the title's tooltip. I later changed my tooltipText value to empty string which seemed to be working. But now every time one of the data points is 0 either no tooltip is shown or is shown over the next data point.  

This is my xAxes config for reference:

```
[
    {
        "id": "c1",
        "type": "CategoryAxis",
        "title": {
            "text": "am"
        },
        "renderer": {
            "line": {
                "isMeasured": false
            },
            "grid": {
                "template": {
                    "disabled": true
                }
            },
            "labels": {
                "template": {
                    "rotation": -45,
                    "horizontalCenter": "right",
                    "verticalCenter": "middle",
                    "truncate": true,
                    "maxWidth": 300,
                    "dy": -10,
                    "adapter": [
                        {
                            "key": "text"
                        }
                    ]
                }
            },
            "minGridDistance": 20
        },
        "tooltipText": "",
        "dataFields": {
            "category": "am"
        },
        "cursorTooltipEnabled": true
    }
]
```

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.
