### ISSUE TITLE
How to hide the bullets when zoom in or zoomout event called 

### ISSUE THREAD

**Issue by faizan-naeemm** [amcharts/amcharts4#4385]
I have created a chart , there are lots of customization I have added , for example X and Y lines I added these lines by doing some customization , similarly I am showing bullet as a image and the bullet is also just showing when hover .

The above is working fine , but the problem appearing is that when i zoom in or zoom out the chart then there are lots of bullets enabled , I don't want this to happen , what is the possibility.

Code Pen : [Demo Chart](https://codepen.io/faizannaeem11/pen/mdoQqGg)

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.
