### ISSUE TITLE
Material theme should change look of elements like scrollbar

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#439]
am4core.Scrollbar doesn't obey to material theme, not look like materialized

**Comment by martynasma** [comment]
Do you have any example?

Please note that `XYChartScrollbar` desaturates all colors from the actual charts so they do not stand out.

**Comment by ramarro123** [comment]
not XYChartScrollbar, just am4core.Scrollbar.

the scrollbar it's rendered as a normal bulky scrollbar.

material scrollbar should look like
https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1rSV50Pn4GaYGGkKn4PTtEhQ8jhM_mtxH%2Fsliders-usage-howtouse.png

also, material theme doesn't seem to make everything "material" apart the button.

even the chart loader doesn't follow the material guideline

**Comment by martynasma** [comment]
OK, so we have decided Material theme should remain a color theme, not modify how elements should look like.
