### ISSUE TITLE
Amchart4 is ignoring null-category in data

### ISSUE THREAD

**Issue by romkai** [amcharts/amcharts4#4390]
**Amchart4 is ignoring null-category in data**

The amCharts4 widget is ignoring my category with a `null` value (there are a total of 3 categories, but only two are displayed). How can I fix this without replacing the `null` values in the data? 

Here is an example on CodePen: https://codepen.io/srcmzzwr-the-flexboxer/pen/PogPbbN

**Comment by zeroin** [comment]
And what would you like to be shown as a category label there? null or just nothing? if nothing, then you should use "" instead of null, I don't think null will work for your case.

**Comment by romkai** [comment]
I would like to show the chart column without a label (if category = null). 
Is it possible to do this without modifying the source data?

thanks in advance
