### ISSUE TITLE
minZoomCount for categoryAxis on yAxis

### ISSUE THREAD

**Issue by sknhkrn** [amcharts/amcharts4#4391]
Hi amCharts,

I encounter some issue when trying to use the minZoomCount on my chart. I get results as below:

![image](https://github.com/amcharts/amcharts4/assets/57323027/beb39dd2-2c8c-4446-a9f1-543a066008cb)

My codes are as follows:
![image](https://github.com/amcharts/amcharts4/assets/57323027/07e0e985-50d4-4546-a160-6dc61dc9cf8d)

My categoryAxis is on yAxis, therefore I need the scrollbar or pre-zoom to be on y-axis.

I have tried adding the Pre-zooming source codes but it doesn't work. 
Is there anything I should add before using the above method?

Thanks in advance.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by sknhkrn** [comment]
Hi, the issue have been fixed. Turns out, I need to complete run the chart source code first and only then assign the data to the chart. I will close this issue. Thanks anyway :D
