### ISSUE TITLE
Pie of a Pie (problems with the lines)

### ISSUE THREAD

**Issue by PedroHGaspar** [amcharts/amcharts4#4392]
Hey! I'm trying to hide the lines when the user hides all the data from the charts, but i've tried everything i know to do this, but this lines won't hide. This is my code and 2 prints of the charts:

function createPieChart(chartData, chartId) {

    let show_values = mfoGetMoneyView();

    var container = am4core.create(chartId, am4core.Container);
    container.width = am4core.percent(100);
    container.height = am4core.percent(100);
    container.layout = "horizontal";

    var chart = container.createChild(am4charts.PieChart);
    chart.responsive.enabled = false;
    chart.width = 780;
    chart.height = 461;

    var pieSeries = chart.series.push(new am4charts.PieSeries());
    pieSeries.dataFields.value = "total";
    pieSeries.dataFields.category = "descricao";
    pieSeries.slices.template.events.on("hit", function (event) {
        const selectedCategory = document.getElementById("selected-category");
        const categoryClicked = event.target.dataItem.properties.category;

        selectedCategory.innerHTML = categoryClicked;
        selectSlice(event.target.dataItem);
        var series = event.target.dataItem.component;
        series.slices.each(function (item) {
            if (item.isActive && item != event.target) {
                item.isActive = false;
            }
        });
    });

    pieSeries.colors.list = [
        am4core.color("#064D5E"),
        am4core.color("#038DB2"),
        am4core.color("#45AAB4"),
        am4core.color("#6363EA"),
        am4core.color("#FBB45C"),
        am4core.color("#CCA237"),
    ];

    chart.innerRadius = am4core.percent(35);

    // Put a thick white border around each Slice
    pieSeries.slices.template.stroke = am4core.color("#fff");
    pieSeries.slices.template.strokeWidth = 4;
    pieSeries.slices.template.strokeOpacity = 1;
    pieSeries.slices.template.cursorOverStyle = [
        {
            "property": "cursor",
            "value": "pointer"
        }
    ];

    pieSeries.alignLabels = false;

    pieSeries.ticks.template.disabled = true;
    pieSeries.calculatePercent = true;

    pieSeries.labels.template.text = "{value.percent.formatNumber('#.0')}%";
    pieSeries.labels.template.radius = am4core.percent(-28);
    pieSeries.labels.template.fill = am4core.color("white");
    pieSeries.labels.template.fontSize = 12;
    pieSeries.labels.template.fontWeight = 700;

    chart.legend = new am4charts.Legend();
    chart.legend.valueLabels.template.disabled = true;
    chart.legend.useDefaultMarker = true;
    chart.legend.labels.template.maxWidth = 20;
    chart.legend.labels.template.truncate = true;
    chart.legend.labels.template.fontFamily = "Lato, sans-serif";
    chart.legend.labels.template.fontStyle = "normal";
    chart.legend.labels.template.fontSize = 14;

    var marker = chart.legend.markers.template.children.getIndex(0);
    marker.cornerRadius(12, 12, 12, 12);
    marker.strokeWidth = 0;
    marker.strokeOpacity = 0;
    var markerTemplate = chart.legend.markers.template;
    markerTemplate.width = 16;
    markerTemplate.height = 16;

    pieSeries.labels.template.adapter.add("radius", function (radius, target) {
        if (target.dataItem && (target.dataItem.values.value.percent < 6)) {
            return 0;
        }
        return radius;
    });

    pieSeries.labels.template.adapter.add("fill", function (color, target) {

        if (target.dataItem && (target.dataItem.values.value.percent < 6)) {
            return am4core.color("#000000");
        }
        return color;
    });

    pieSeries.labels.template.adapter.add("text", function (text, target) {
        if (target.dataItem.values.value.percent < 6) {
            return "";
        }
        return text;
    });

    var slice = pieSeries.slices.template;
    slice.states.getKey("hover").properties.scale = 1;
    slice.states.getKey("active").properties.shiftRadius = 0;

    if (show_values) {
        slice.tooltipText = "{category}: {value.percent.formatNumber('#.0')}% (R$ {value})";
    } else {
        slice.tooltipText = "";
    }

    // Create a base filter effect (as if it's not there) for the hover to return to
    var shadow = pieSeries.slices.template.filters.push(new am4core.DropShadowFilter);
    shadow.opacity = 0;

    // Create hover state
    var hoverState = pieSeries.slices.template.states.getKey("hover"); // normally we have to create the hover state, in this case it already exists

    // Slightly shift the shadow and make it more prominent on hover
    var hoverShadow = hoverState.filters.push(new am4core.DropShadowFilter);
    hoverShadow.opacity = 0.7;
    hoverShadow.blur = 5;

    chart.data = chartData;

    chart.language.locale = am4lang_pt_BR;

    pieSeries.slices.template.events.on("hit", function (event) {
        selectSlice(event.target.dataItem);
        var series = event.target.dataItem.component;
        series.slices.each(function (item) {
            if (item.isActive && item != event.target) {
                item.isActive = false;
            }
        })
    })

    var chart2 = container.createChild(am4charts.PieChart);
    chart2.width = am4core.percent(20);
    chart2.radius = am4core.percent(80);
    chart2.innerRadius = am4core.percent(35);

    // Add and configure Series
    var pieSeries2 = chart2.series.push(new am4charts.PieSeries());
    pieSeries2.alignLabels = false;

    pieSeries2.ticks.template.disabled = true;
    pieSeries2.calculatePercent = true;

    pieSeries2.labels.template.text = "{value.percent.formatNumber('#.0')}%";
    pieSeries2.labels.template.radius = am4core.percent(-28);
    pieSeries2.labels.template.fill = am4core.color("white");
    pieSeries2.labels.template.fontSize = 12;
    pieSeries2.labels.template.fontWeight = 700;
    pieSeries2.dataFields.value = "value";
    pieSeries2.dataFields.category = "name";
    pieSeries2.slices.template.states.getKey("active").properties.shiftRadius = 0;
    pieSeries2.events.on("positionchanged", updateLines);

    pieSeries2.slices.template.stroke = am4core.color("#fff");
    pieSeries2.slices.template.strokeWidth = 4;
    pieSeries2.slices.template.strokeOpacity = 1;
    pieSeries2.slices.template.cursorOverStyle = [
        {
            "property": "cursor",
            "value": "pointer"
        }
    ];

    pieSeries2.labels.template.adapter.add("radius", function (radius, target) {
        if (target.dataItem && (Math.abs(target.dataItem.values.value.percent) < 6)) {
            return 0;
        }
        return radius;
    });

    pieSeries2.labels.template.adapter.add("fill", function (color, target) {
        if (target.dataItem && (Math.abs(target.dataItem.values.value.percent) < 6)) {
            return am4core.color("#fff");
        }
        return color;
    });

    var slice = pieSeries2.slices.template;
    slice.states.getKey("hover").properties.scale = 1;
    slice.states.getKey("active").properties.shiftRadius = 0;

    if (show_values) {
        slice.tooltipText = "{category}: {value.percent.formatNumber('#.0')}% (R$ {value})";
    } else {
        slice.tooltipText = "";
    }

    var interfaceColors = new am4core.InterfaceColorSet();

    var line1 = chart.createChild(am4core.Line);
    line1.strokeDasharray = "2,2";
    line1.strokeOpacity = 0.5;
    line1.stroke = interfaceColors.getFor("alternativeBackground");
    line1.isMeasured = false;

    var line2 = chart.createChild(am4core.Line);
    line2.strokeDasharray = "2,2";
    line2.strokeOpacity = 0.5;
    line2.stroke = interfaceColors.getFor("alternativeBackground");
    line2.isMeasured = false;

    var selectedSlice;

    function selectSlice(dataItem) {

        const sliceData = dataItem.dataContext;
        var dataDespesas = {};
        let dataChildren;
        let chart2Data = [];

        selectedSlice = dataItem.slice;

        $.each(dataItem.dataContext.subData, function (item, value) {
            dataDespesas = {
                ...dataDespesas,
                ...value.children
            }
        });

        // if (dataDespesas[sliceData.descricao] == undefined) 

        dataChildren = (dataDespesas[sliceData.descricao].children ? dataDespesas[sliceData.descricao].children : dataDespesas[sliceData.descricao]);

        Object.keys(dataChildren).map((val, index) => {
            chart2Data.push({ name: val, value: Math.abs(dataChildren[val].total) })
        });

        let count = Object.keys(chart2Data).length;
        var fill = selectedSlice.fill;

        chart2.data = chart2Data;
        chart2.height = 425;
        pieSeries2.appear();
        chart2.legend = new am4charts.Legend();
        chart2.legend.useDefaultMarker = true;
        chart2.legend.labels.template.fontFamily = "Lato, sans-serif";
        chart2.legend.labels.template.fontSize = 14;
        chart2.legend.labels.template.color = "#333";
        chart2.legend.valueLabels.template.disabled = true;
        chart2.legend.maxHeight = 30;
        var marker1 = chart2.legend.markers.template.children.getIndex(0);
        marker1.cornerRadius(12, 12, 12, 12);
        marker1.strokeWidth = 0;
        marker1.strokeOpacity = 0;
        var markerTemplate1 = chart2.legend.markers.template;
        markerTemplate1.width = 16;
        markerTemplate1.height = 16;

        var middleAngle = selectedSlice.middleAngle;
        var firstAngle = pieSeries.slices.getIndex(0).startAngle;
        var animation = pieSeries.animate([{ property: "startAngle", to: firstAngle - middleAngle }, { property: "endAngle", to: firstAngle - middleAngle + 360 }], 600, am4core.ease.sinOut);
        animation.events.on("animationprogress", updateLines);

        selectedSlice.events.on("transformed", updateLines);

        pieSeries2.colors.list = [];
        for (var i = 0; i < count; i++) {
            pieSeries2.colors.list.push(fill.lighten(i / count));
        }
    }

    function updateLines() {
        if (selectedSlice) {
            var p11 = { x: selectedSlice.radius * am4core.math.cos(selectedSlice.startAngle), y: selectedSlice.radius * am4core.math.sin(selectedSlice.startAngle) };
            var p12 = { x: selectedSlice.radius * am4core.math.cos(selectedSlice.startAngle + selectedSlice.arc), y: selectedSlice.radius * am4core.math.sin(selectedSlice.startAngle + selectedSlice.arc) };

            p11 = am4core.utils.spritePointToSvg(p11, selectedSlice);
            p12 = am4core.utils.spritePointToSvg(p12, selectedSlice);

            var p21 = { x: 0, y: -pieSeries2.pixelRadius };
            var p22 = { x: 0, y: pieSeries2.pixelRadius };

            p21 = am4core.utils.spritePointToSvg(p21, pieSeries2);
            p22 = am4core.utils.spritePointToSvg(p22, pieSeries2);

            line1.x1 = p11.x;
            line1.x2 = p21.x;
            line1.y1 = p11.y;
            line1.y2 = p21.y;

            line2.x1 = p12.x;
            line2.x2 = p22.x;
            line2.y1 = p12.y;
            line2.y2 = p22.y;

            console.log("line1:", line1)
            console.log("line2:", line2)
        }
    }

    chart.events.on("datavalidated", function () {
        setTimeout(function () {
            selectSlice(pieSeries.dataItems.getIndex(0));
        }, 500);
    });
}

This is my normal chart with the lines:
![image](https://github.com/amcharts/amcharts4/assets/37162818/ffad58a8-2991-40b2-b3ff-ecb455abb2cb)

And this is the chart when i click on all legends and the data hides, but the lines are still there, but i want them to be hidden:
![image](https://github.com/amcharts/amcharts4/assets/37162818/63e8cfff-cb7d-4377-b7cc-ba1d0b33d967)

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.

**Comment by PedroHGaspar** [comment]
That's ok! Thanks for the answer!
