### ISSUE TITLE
How to show text in chart area without overlapping with the bars ?

### ISSUE THREAD

**Issue by nikitha-keyvalue** [amcharts/amcharts4#4393]
Hi,

Is there a way to show a text dynamically over the chart area, so that it never overlaps with the actual plotted chart ? Attaching the screenshot for reference.
![Screenshot from 2024-04-03 09-54-52](https://github.com/amcharts/amcharts4/assets/111980971/ff10a7f9-40f9-4941-8fdb-e45cd8e77b3c)

**Comment by martynasma** [comment]
I take it you are referring to the "Powered by DataSquirrel" text.

You can place the text in the upper section of the plot container. E.g.:
https://www.amcharts.com/docs/v4/tutorials/adding-watermarks-to-charts/

You can also relatively extend the scale of Y axis, so the actual series never go all the way to the top of the plot container:
https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Relatively_expanding_the_scale
