### ISSUE TITLE
[Question] Multiple CandlestickSeries is shifted relative to each other

### ISSUE THREAD

**Issue by decadence** [amcharts/amcharts4#4395]
- amCharts version: 4.10.38
 - Browser and its version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
 - Related frameworks and their versions: Vue 3.4.21

I have `XYChart` with multiple `LineSeries` (hidden on image) and multiple `CandlestickSeries`. I don't know why but candles are shifted relative to each other (on `DateAxis`) even they have equal date (start of hour).

![2024-04-16_15-55-46](https://github.com/amcharts/amcharts4/assets/1434668/7bceb933-c22f-4be1-9c10-16ea06087388)

If I add only one `CandlestickSeries` it appears normal

![image](https://github.com/amcharts/amcharts4/assets/1434668/72366589-e0b8-46eb-8b07-e54d4ad0a7b5)

What can I do about it so candles will have equal position on `DateAxis` and normal width of the candle (for whole hour)?

This is how I add `CandlestickSeries`:
```javascript
for (let candle of this.candles) {
	let series = chart.series.push(new am4charts.CandlestickSeries());
	series.dataFields.dateX = this.dateField;
	series.name = candle.name;
	series.dataFields.valueY = candle.values.close;
	series.dataFields.openValueY = candle.values.open;
	series.dataFields.lowValueY = candle.values.low;
	series.dataFields.highValueY = candle.values.high;
	series.simplifiedProcessing = false;
	series.tooltipText = "Open: {openValueY.value}\nLow: {lowValueY.value}\nHigh: {highValueY.value}\nClose: {valueY.value}";

	scrollbar.series.push(series);
	series.events.disableType("selectionextremeschanged");

	// with break we can add only one CandlestickSeries and it appears as expected
	// break;
}
```

**Comment by martynasma** [comment]
You can disable clustering on a series:

```JavaScript
series.clustered = false;
```

https://www.amcharts.com/docs/v4/reference/candlestickseries/#clustered_property

**Comment by decadence** [comment]
@martynasma thanks for fast response. It works, didn't notice this property when I searched in docs.
