### ISSUE TITLE
Wrong cursor position when viewbox and real width/height not matching

### ISSUE THREAD

**Issue by igoriok1994** [amcharts/amcharts4#4396]
I'm trying to create a chart inside SVG container. I have SVG viewBox, and CSS width/height.
When SVG viewBox matches CSS width/height - its ok. When not - cursors position is wrong.

https://codepen.io/xruyulqu-the-scripter/pen/gOydXzX

Is it possible to fix? Maybe there are some workarounds?

**Comment by martynasma** [comment]
I'm afraid there's nothing we can suggest for using chart as a foreignObject in an SVG.

**Comment by martynasma** [comment]
Maybe amCharts 5 would work better? 😉
