### ISSUE TITLE
Map with clustered points and lines

### ISSUE THREAD

**Issue by urgentdotagency** [amcharts/amcharts4#4397]
Hi, I'm trying to create a map displaying clustered points, together with lines from 1 marker pointing to my points.

I'd like for the lines to point to the cluster point when clustering, unlike the screenshot below, but I'm having trouble finding the right way to do this.

<img width="530" alt="Screenshot 2024-04-18 at 14 57 27" src="https://github.com/amcharts/amcharts4/assets/48589068/10fe7b90-3b71-4d3a-96bc-96778ed56f17">

I'm creating lines and points separately – but is there a way to connect them so cluster changes update the lines?
Or should I listen for cluster updates, and then redraw my lines?

A nod in the right direction would be much appreciated, thank you.

**Comment by martynasma** [comment]
Is this maybe for amCharts 5? amCharts 4 did not support clusytering.

If it's for amCharts 5, please close this and repost in the correct repo: https://github.com/amcharts/amcharts5/

**Comment by urgentdotagency** [comment]
Ah! Of course – had both tabs open and posted in the wrong one, apologies.
