### ISSUE TITLE
force directed graph : label on edge and graph going out of bounds

### ISSUE THREAD

**Issue by annajavascript** [amcharts/amcharts4#4400]
I am not able to add any labels on edges. Is there any work around for that?
also, graph is going out of bound even after setting width & height. scroll not working.
<img width="613" alt="image" src="https://github.com/amcharts/amcharts4/assets/93151969/b9268e9b-d422-4808-b512-851aa413aeee">

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v4/tutorials/labels-on-top-of-the-forcedirectednode/

For zooming:
https://www.amcharts.com/docs/v4/chart-types/force-directed/#Zooming
