### ISSUE TITLE
Need to add custom percentages in Tooltip instead of default CalculatePercentage in amcharts 4

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#4401]
Hi

I need to display percentage along with actual value, which is calculated by us in Stacked bar chart.
![refernce](https://github.com/amcharts/amcharts4/assets/71019344/2d080517-39ef-4677-b7f4-f78290931be6)

I referred this document: https://www.amcharts.com/docs/v4/tutorials/using-percent-values-in-series/

I have written below snippet:

```JavaScript
series.dataFields.valueY = field;
 series.dataFields.categoryX = 'y';           
 series.dataFields.valueYShow = 'originated_percent';
 series.columns.template.tooltipText = '[bold]{name}[/]\n[font-size:12px]{categoryX}: {valueY}[/]' +  '({valueYShow}%[/])';
```

In the above originated_percent, I have given. 
This is how data looks like:

```JavaScript
chart.data = [{
  "Originated": 13,   
  "Received": 19
   "originated_percent": 33.36
   "total": 32
}]
```

Can you help us to add a custom percentage? 
Please reach out to me asap, i need your help.

**Comment by martynasma** [comment]
You can refer to any value in data using curly brackets, e.g.: `{originated_percent}`.

**Comment by meghanaNanuvala** [comment]
is this :  series.dataFields.valueYShow = '{originated_percent}';

Can you please provide exact one, because i have tried above one. It's not as expected.

**Comment by martynasma** [comment]
No, you can refer it in a tooltip:

```JavaScript
series.columns.template.tooltipText = '[bold]{name}[/]\n[font-size:12px]{categoryX}: {valueY}[/]' +  '({originated_percent}%[/])';
```
