### ISSUE TITLE
Columnes cropped in the beginning

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#4402]
**Question**
I am trying to create simple column chart, but the first column somehow is cropped. And tooltip is not working as well
I've tried axis.startLocation and cellStartLocation, but nothing seems to work
![image](https://github.com/amcharts/amcharts4/assets/18229211/786ab83d-3a67-41b9-9a09-10090acad76d)

[Example](https://codepen.io/12rita/pen/oNRYqPx)

**Comment by martynasma** [comment]
Please refer to this documentation:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

**Comment by 12rita** [comment]
> Please refer to this documentation: https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

I did and i tried startLocation and cellStartLocation as i've said, but it didn't work out as expected

**Comment by martynasma** [comment]
OK, I didn't notice you had ValueAxis as your X-axis.

In such case you might consider shifting your columns and axis labels to the right a bit:

```JavaScript
series.columns.template.dx = 4;
...
valueAxis.renderer.labels.template.dx = 4;
```

**Comment by 12rita** [comment]
> OK, I didn't notice you had ValueAxis as your X-axis.
> 
> In such case you might consider shifting your columns and axis labels to the right a bit:
> 
> ```js
> series.columns.template.dx = 4;
> ...
> valueAxis.renderer.labels.template.dx = 4;
> ```

Perfect! Thank you very much. 
What about tooltip? Should i open a new issue for that?

**Comment by martynasma** [comment]
> What about tooltip? Should i open a new issue for that?

Yes. Please.

**Comment by 12rita** [comment]
Okay, thank you
