### ISSUE TITLE
Tooltip doesnt' show on the chart

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#4403]
**Question**
Somehow tooltip is not working on my chart
[Example](https://codepen.io/12rita/pen/oNRYqPx)

**Comment by martynasma** [comment]
You need to use cursor's `snapToSeries`:

```JavaScript
chart.cursor.snapToSeries = chart.series.values;
```

**Comment by 12rita** [comment]
> You need to use cursor's `snapToSeries`:
> 
> ```js
> chart.cursor.snapToSeries = chart.series.values;
> ```

Thank you, that worked. But why it didn't it work in the first place?

**Comment by martynasma** [comment]
Because you are using ValueAxis as X-axis, so the cursor does not have any categories/dates to snap to.

Using `snapToSeries` instructs cursor to snap to data items of the series instead.

**Comment by 12rita** [comment]
> Because you are using ValueAxis as X-axis, so the cursor does not have any categories/dates to snap to.
> 
> Using `snapToSeries` instructs cursor to snap to data items of the series instead.

Got it, thanks for clarification
