### ISSUE TITLE
Screen readers are announcing different data from the visible data on the Funnel chart.

### ISSUE THREAD

**Issue by msftedad** [amcharts/amcharts4#4404]
**Bug description**

**Repro steps:**

1. Open [URL](https://www.amcharts.com/demos-v4/funnel-with-gradient-fill-v4/) in edge browser.
2. Trun on Narrator using 'Ctrl + Win + Enter' key.
3. Navigate to the chart present on the page using tab key.
4. Observe the narrator announcement.

**Actual Results:**

Screen readers are announcing different data from the visible data on the chart bars, it is announcing page view 46.7% figure, but the visible data is 100%.

https://github.com/amcharts/amcharts4/assets/93735775/6c4f0a31-b551-4033-b334-a4af02a47c45

**Expected Results:**

The narrator must announce the exact data information as it is visible.

**Environment (if applicable)**
OS Build: Windows 11 Enterprise 23H2 (22631.3672)
Edge Browser: Version 125.0.2535.85 (Official build) (64-bit)

**Additional context**

**Comment by martynasma** [comment]
It's announcing correct aria label which lists category and percent value by default.

You can configure what is read out by readers using [`itemReaderText`](https://www.amcharts.com/docs/v4/concepts/accessibility/#Series_item_reader_text) of the series:

```JavaScript
series.itemReaderText = "{category}: {value}";
```
```

**Comment by msftedad** [comment]
Hi @martynasma , we are currently in discussion with PO team.Once we receive any information we will promptly update you.Thanks

**Comment by msftedad** [comment]
Discussion is ongoing with PO team, Once we receive information, we will update you soon.
