### ISSUE TITLE
Mutli Date Axis with columnSeries

### ISSUE THREAD

**Issue by pratham3164** [amcharts/amcharts4#4405]
I'm trying to build a multi-dateAxis ColumnSeries chart. I am able to load the data but  the columns of the second dateAxis seem to overlap the first dateAxis column( attaching an image for reference)

![image](https://github.com/amcharts/amcharts4/assets/44560611/1c1d31f9-0d9a-4de6-a965-18d6f3dfe8ba)

Is there a way where I can have those columns next to each other in the same grid instead of overlapping ??

**Comment by zeroin** [comment]
Try to add two additional column series to the second axis with no data.
