### ISSUE TITLE
Add an extra label to a sunburst slice

### ISSUE THREAD

**Issue by diedel** [amcharts/amcharts4#4413]
**Question**

I have a sunburst with two levels and I would like to add the labels "0", "1" and "2" to each of its circunferences, like the ticks of radial axis.
I have managed to do it with this ugly code:
```
var level0 = chart.seriesTemplates.create("0");
label0 = level0.createChild(am4core.Label);
label0.text = "0";
label0.fontSize = 15;
label0.fontWeight = "bold";
label0.isMeasured = false;
label0.x = -105;
label0.y = -120;
```

Is it possible to add a child label to the slice directly and position it nicely?

**Environment (if applicable)**

 - amCharts 4

**Additional context**

![Captura de pantalla 2024-08-05 150225](https://github.com/user-attachments/assets/890a54ec-8e24-48e2-900e-64e6157c0c43)

**Comment by martynasma** [comment]
How about adding a zero-value slices for each level?

They would not affect the general diagram, but you could use them for labels.

**Comment by diedel** [comment]
Nice idea @martynasma , thank you!

![Captura de pantalla 2024-08-08 112137](https://github.com/user-attachments/assets/d58ccff8-9ca4-4592-9648-897648f3a2ab)

I created one zero-value slice for each of the three levels. I display its labels outside of the slice and with "bent" and left padding (I tried to rotate the labels around the slice's arc but I didn't succeed)

```
    var level0 = chart.seriesTemplates.create("0");
    level0.labels.template.inside = false;
    level0.labels.template.fill = am4core.color("#000");
    level0.labels.template.text = "{category}";
    level0.labels.template.bent = true;
    level0.labels.template.paddingLeft = 10;
    level0.slices.template.tooltipText = "";
```

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by diedel** [comment]
Here is the Pen:

https://codepen.io/diedel/pen/VwJBamV

**Comment by martynasma** [comment]
If you need those labels to not be drawn at an angle, you can just add this:

```JavaScript
level0.labels.template.relativeRotation = false;
```
