### ISSUE TITLE
Stacked column series with rounded corners

### ISSUE THREAD

**Issue by eduardmavliutov** [amcharts/amcharts4#4414]
**Question**

Hello! 
I was following [the guide from the documentation](https://www.amcharts.com/docs/v4/tutorials/stacked-column-series-with-rounded-corners/) trying to implement the same feature, but can't make the code work the same way.

Please, take a look at my adapter (the same function is used for both `cornerRadiusBottomRight` and `cornerRadiusTopRight`):
```
const borderRadiusAdapter = (_: number, target: any) => {
    const dataItem = target.dataItem
    let lastSeries: any

    chartInstanceValue.series.each((series) => {
      const isHidden = !series.properties.visible || series.isHidden || series.isHiding
      const shouldProcessSeries = series.dataFields.valueX && dataItem.dataContext[series.dataFields.valueX] && !isHidden
      if (shouldProcessSeries) {
        lastSeries = series
      }
    })

    const currentColumnValueX = dataItem?.component?.dataFields?.valueX
      const lastSeriesValueX = lastSeries?.dataFields?.valueX
      return (lastSeriesValueX && lastSeriesValueX === currentColumnValueX) ? 10 : 0
}
```

When the chart is rendered initially I see the desired rounded corners, but once I start to toggle series, corner radius properties are not updated dynamically (e.g. the third piece of the bar becomes the last one but it doesn't start having rounded corners on the right side). 

I tried to log the `currentColumnValueX` property and I see, that when I toggle for example `Asia` series, `currentColumnValueX` is always equals `Asia`'s `valueX`. That results in the check on the last line of adapter function always being `false`.

https://github.com/user-attachments/assets/b01a8d7f-3cf0-40e8-b344-71324b6307dd

Could you tell me, please, what might be the problem?

**Comment by eduardmavliutov** [comment]
Hello!
I've managed to transform our Vue component into JS fiddle, sorry for not doing it earlier. 
Could you take a look, when you have time, please?
I'm still in the same place, any help is appreciated.

https://codepen.io/eddiLovesJs/pen/NWZwLoy

**Comment by martynasma** [comment]
This question was reviewed by amCharts staff and was determined neither a) bug nor b) simple question that can be answered without doing custom development or reviewing user code.

I'm sorry, but we won't be able to answer your question here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).

**Comment by eduardmavliutov** [comment]
No problem, I understand. 
I've checked - we don't have the amCharts support subscription, unfortunately. But thanks for the respond anyway. Closing the issue.
