### ISSUE TITLE
Forcing tooltips to appear at the top

### ISSUE THREAD

**Issue by alexandersokolow** [amcharts/amcharts4#4419]
Usually the tooltips can be forced to appear on the top by setting the pointerOrientation property to "down", but this property is being ignored in some scenarios, like having multiple tooltips stacked, as pointed out in the [documentation](https://www.amcharts.com/docs/v4/reference/tooltip/#pointerOrientation_property):
> IMPORTANT: in some situations, like having multiple tooltips stacked for multiple series, the "up" and "down" values might be ignored in order to make tooltip overlap algorithm work.

I've checked the source code and this could be remedied by adding a simple property, which I explain in the following:

The [XYChart.ts](https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/types/XYChart.ts) file includes [this function (line 1378)](https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/types/XYChart.ts#L1378), which seems to be where the algorithm for aligning the tooltips takes place. A bit further below, the function contains [this if-condition (line 1481)](https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/types/XYChart.ts#L1481) that would result in the tooltips going from bottom to top and [another if-condition (line 1505)](https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/types/XYChart.ts#L1505) that would result in the tooltips going from top to bottom. The first if-condition also has [this block (line 1498)](https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/types/XYChart.ts#L1498) that checks for whether we have reached the maximum & prematurely breaks it if it does to run the second instead.
If we set the first condition to true, comment out the block and set the second condition to false, it makes the tooltips appear on top (regardless of the pointerOrientation property I suppose).

See this [old codepen](https://codepen.io/alexandersokolow96/pen/qBzqwZY) and [new codepen](https://codepen.io/alexandersokolow96/pen/MWMPWxX) to verify that this works, the new one has those exact changes (I've editted them into the minified core.js file) and the tooltips now all appear on the top. Note that the issue before was that the series tooltips were overlapping with the date tooltip, which doesn't happen anymore if they are on the top, you can also check [this ticket](https://github.com/amcharts/amcharts4/issues/4412) for more context (it was prematurely closed by a github bot).

Would it be possible to add something like a _tooltipsAlgorithmDirection_ property (maybe you can come up with a better name haha) to the XYChart that would make those changes happen? I.e. if we set it to "up" it would replicate my changes, if we set it to "down" it would do the opposite (set the first condition to false and the second to true).
I can create a PR for this if needed, but it's probably a quick change for someone more familiar with the codebase.

**Comment by martynasma** [comment]
V4 has reached its EOL and is on feature freeze. I'm afraid we won't be able to add the feature you suggested.
