### ISSUE TITLE
Wrong year for first day of year

### ISSUE THREAD

**Issue by bmampaey** [amcharts/amcharts4#4420]
**Bug description**

When making a chart with dates on the X axis, the first day of the year appears with the previous year. For example the dates will be 31 Dec 2011 | 1 Jan 201**1**  | 2 Jan 2012 and I expect them to be 31 Dec 2011 |  1 Jan 201**2** | 2 Jan 2012

The bug was not there before version 4.10.39 

In the fiddle below, you can see that the error for the first day of year 2012 is on the X axis label (zoom in eventually), but also on the X axis tooltip

https://jsfiddle.net/nrsy942e/

**Environment (if applicable)**

Amchart version  4.10.39 , firefox 128.0 on Ubuntu

**Comment by zeroin** [comment]
Try to replace YYYY with yyyy. YYYY is Year (of "Week of Year"), used in ISO year-week calendar. May differ from calendar year.

https://www.amcharts.com/docs/v4/concepts/formatters/formatting-date-time/

**Comment by bmampaey** [comment]
Indeed, that was the problem. I see that there is even a "note" about it. Sorry for the false alert.
