### ISSUE TITLE
Render the Zero valueAxis data label on chart

### ISSUE THREAD

**Issue by promptjunkie** [amcharts/amcharts4#4423]
I have a chart where the zero valueAxis data label does not show. I have tried many way to force it but have not been able to figure it out. Any help is appreciated! 

![image](https://github.com/user-attachments/assets/c58f184f-5cd2-4a9c-836f-7ed423c5acfc)

**Comment by martynasma** [comment]
You might want to add `min = 0` to your X axis.

Docs: https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Adjusting_scale
