### ISSUE TITLE
 Toggling Sunburst Chart Slices Using Custom Legends

### ISSUE THREAD

**Issue by amtjoshi** [amcharts/amcharts4#4426]
I have implemented a Sunburst chart using amCharts 4, and I have created custom legends to represent the chart's data categories. I would like to enhance the interactivity of my chart by allowing users to hide and show the slices of the Sunburst chart when they click on these custom legends, similar to the functionality of the standard legends provided by amCharts.

In my current setup, I've successfully created a Sunburst chart and populated custom legends as follows:

https://codepen.io/amit-joshi-the-reactor/pen/ExqNVQd

**Comment by martynasma** [comment]
amCharts 4 support has reached end-of-life Dec 31, 2023.

If you still have support subscription, try contacting amCharts support directly: contact@amcharts.com

Otherwise, you might try posting your questions on StackOverflow.

I hope that sounds reasonable.
