### ISSUE TITLE
 If polyfill vulnerability impacts, Amchart4 or not? Also, if we remove polyfill from amchart Core.js.map and Core.js files, will it affect amchart 4?

### ISSUE THREAD

**Issue by Pooja26j** [amcharts/amcharts4#4428]
We need to remove the references of "polyfill" from our Angular project due to some security constraints.

We have used amchart and its Core.js.map and Core.js files are having "Polyfill" reference. So, we need to remove these references as per our project requirement.

So, need to confirm If polyfill vulnerability impacts Amchart4 or not? Also, if we remove polyfill from amchart Core.js.map and Core.js files, will it affect amchart 4?

Thanks, in advance for the support.

**Comment by martynasma** [comment]
We use core-js polyfill in script (CDN) versions of amCharts 4.

At this time we are not aware of any vulnerabilities with the version of polyfill we are using.

That said, you may consider using an NPM version which does not have a polyfill.
