### ISSUE TITLE
Programmatically scrollbar scrolling 

### ISSUE THREAD

**Issue by fruitbang** [amcharts/amcharts4#4430]
Is there way to scroll legend verticalScrollbar by added buttons?
I need to make something like this:
![image](https://github.com/user-attachments/assets/916ca181-3384-40ec-b62a-5ce41c60f8c7)

**Comment by martynasma** [comment]
Are you referring to amCharts 4? I'm not sure it has verticalScrollbar feature.

**Comment by fruitbang** [comment]
sorry, my mistake, this question about amCharts 5

**Comment by martynasma** [comment]
Yes, please.
