### ISSUE TITLE
Data Points with same timestamp

### ISSUE THREAD

**Issue by amtjoshi** [amcharts/amcharts4#4431]
I am working on an XY chart with two line series in amCharts, where some data points share the same timestamp. Currently, only the last data value is displayed in the tooltip for points with identical timestamps, but I want to display all values associated with each timestamp in the tooltip.

https://codepen.io/amit-joshi-the-reactor/pen/PoMOram

**Comment by martynasma** [comment]
There's no way to do that, I'm afraid.

Unless you want to create an adapter for tooltip label and use your own logic to combine data from several data points.

Docs about adapters:
https://www.amcharts.com/docs/v4/concepts/adapters/
