### ISSUE TITLE
Toggle XY chart's bars (single series) + animate bars like on initial render

### ISSUE THREAD

**Issue by eduardmavliutov** [amcharts/amcharts4#4432]
Hello-hello!

I was following [this guide](https://www.amcharts.com/docs/v4/tutorials/individual-legend-item-for-each-column/#Advanced_example), everything works great, thank you! I have a question though: 

Could you tell me please, is it possible to animate bars when we toggle them? The same way they are animated on the initial render.

I suppose the answer is no, because animation apparently belongs to series, not to columns, but anyway it would be nice to confirm that (or not) with you.

**Comment by martynasma** [comment]
I'm afraid we don't have a demo that would do that 🙁

**Comment by eduardmavliutov** [comment]
That's not a problem 🙂 I was just wondering if it's possible in general to animate a single bar from the series.
