### ISSUE TITLE
Non-rendering of the bar in zoom

### ISSUE THREAD

**Issue by cadu2602** [amcharts/amcharts4#4434]
I identified a possible bug with zoomX when using a DateAxis and a ValueAxis in a bar chart with multiple bars having an openDateX and a dateX. The bug occurs when I select a bar to zoom; the zoom happens, but the bar does not render. Additionally, when using ScrollbarX to zoom, it does not render the content in the center, only on the right edge. This happens when zooming on ScrollbarX from right to left; from left to right, it does not render, showing only the last bar.

I using amcharts4 in version 4.10.34

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by cadu2602** [comment]
I'll set up a jsFiddle as soon as possible. For a quick preview, I'm sending a simple video showing how it’s currently working. During the video, the page reloads at one point.

[Gravação de tela de 2024-12-18 07-52-02.webm](https://github.com/user-attachments/assets/a0d8905b-f16a-4c4f-be60-fe3c165e966c)

**Comment by martynasma** [comment]
That looks to me like data that is not ordered properly. It should come in ascending order.

**Comment by cadu2602** [comment]
It worked, thank you so much for the support!
