### ISSUE TITLE
StepLines interpolation method 

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#444]
Hello,

How to specify the interpolation method for stepline ? (e.g., "stepAfter")

Nothing found about it on 
https://www.amcharts.com/docs/v4/reference/steplineseries/

Thanks for your help

**Comment by martynasma** [comment]
Just to make sure we're on the same page: do you need to specify where the step occurs?

If that is the case, the following tutorial might be useful:
https://www.amcharts.com/docs/v4/tutorials/taming-the-step-line-series/

**Comment by ptorrent** [comment]
Yep thanks !
