### ISSUE TITLE
PieChart created from config is not animating on hide/show

### ISSUE THREAD

**Issue by cam-m** [amcharts/amcharts4#449]
Here's a [pen ](https://codepen.io/cam-m/pen/RepjeY) replicating the issue - Am I missing something obvious?

Thanks,

Cam

**Comment by martynasma** [comment]
Hi there,

I don't think this is related to `createFromConfig`. Here's the same chart with `create()`:
https://codepen.io/team/amcharts/pen/f386503dff463ba0ba2d1eb62519b94f/

Behaves the same.

That aside, how do you expect it to animate? You are hiding the whole series, then making it appear immediately after that.

**Comment by zeroin** [comment]
You should some properties on hiddenState different from default state, like endAngle for example:
https://codepen.io/team/amcharts/pen/bmaNav

**Comment by cam-m** [comment]
Hey sorry the late reply @martynasma and @zeroin - so yes, I _was_ missing something obvious ;) 

I had thought the animations were built into the theme and hadn't noticed this config from the docs:

```
states: {
    hidden: {
        properties: {
            endAngle:-90
        }
    }
}
```

Thanks as aways,

Cam

**Comment by martynasma** [comment]
No worries ;)
