### ISSUE TITLE
It seems impossible to add an event listener to LineSeries

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#451]
Example:
https://codepen.io/dmsmaxim/pen/zmwoeV
Here I try to add 'hit' listener, but it doesn't work with any other event...

**Comment by martynasma** [comment]
For `LineSeries` the interactions are disabled by default, meaning all actions are ignored.

To re-enable them, do this:

```
series2.segments.template.interactionsEnabled = true;
```
