### ISSUE TITLE
Hovering over bullet makes it lose chart cursor hover functionality (updated last post)

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#452]
Example:
https://codepen.io/team/amcharts/pen/2c3fe78200159287da6b6de52f6ce2e2/

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.58](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.58).

## [4.0.0-beta.58] - 2018-10-17

### Added
- `ExportMenu`'s "custom" items can now have `"callback"` which is a function to call when clicked on such custom item.

### Changed
- Slice labels on a `PieChart` now move with the slice (if `alignLables = false`).

### Fixed
- `requestAnimationFrame` now is called only when needed. This reduces idle CPU usage.
- Fixed `m4core.color()` result caching issue.
- Charts were broken in IEs since beta.57.
- `Tooltip` on `LineSeries` was not updating color if segment changed color.
- `MapChart` without any series was displaying an error in console.
- Axis tooltip was trimmed when `renderer.inside = true`.
- `StepLineSeries` `startLocation`/`endLocation` bug fixed.
- `"hover"` state was not being applied to series' bullet if it did not hav `tooltipText` set.
- `bulletLocation` for horizontal `ColumnSeries` fixed.
- Value labels of `Legend` were not in correct positions if `Legend` was positioned at the top or bottom (too close to legend label).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by notacouch** [comment]
Now hover state and tooltips trigger, but if you hover directly over the bullet, then hover out, the cursor ceases to be the trigger until it activates a different plot on the chart:
![cursor-tooltip-deactivate](https://user-images.githubusercontent.com/2334143/47098776-ded37380-d201-11e8-9291-9bca83f1ff5e.gif)

**Comment by martynasma** [comment]
Bringing this issue back to life. Thanks.

**Comment by zeroin** [comment]
It's fixed (at least I can't reproduce this one in v 64 beta)
