### ISSUE TITLE
Nested text formatters don't work

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#453]
Example:
https://codepen.io/dmsmaxim/pen/ZqKKyj

Here I format series.tooltipText like this: 
`"[bold]{name}: [red]{valueY}[/] (but this text is not bold)[/]"`

**Comment by martynasma** [comment]
That is correct. There's currently no way to nest formatting blocks. Every new block resets previous ones.

This should do the trick:
```
"[bold]{name}: [red bold]{valueY}[/] (but this text is not bold)[/]"
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
