### ISSUE TITLE
Add custom action items to ExportMenu - Question

### ISSUE THREAD

**Issue by JKannekens** [amcharts/amcharts4#463]
Hello,

In version 3 of amcharts it was possible to add custom action items to the ExportMenu. Something like this: https://www.amcharts.com/kbase/adding-custom-action-items-export-menu/ Is this also possible in version 4 because I can't seem to find anything about this?

**Comment by martynasma** [comment]
Have you tried modifying `chart.exporting.menu.items`?

https://www.amcharts.com/docs/v4/concepts/exporting/#Modifying_menu_items

**Comment by JKannekens** [comment]
Yes I tried this and this works but I would like to add custom functions to these items (I forget to put this in my question). Is this possible? Like the alert function in my example.

**Comment by JKannekens** [comment]
Wow haha, thank you so much!
