### ISSUE TITLE
Zero-value 3D column is invisible

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#469]
![image](https://user-images.githubusercontent.com/1458520/47173811-c35a8c80-d317-11e8-87c0-0dfde1c3ca39.png)

Probably would make sense to show a flat square.

Example:
https://codepen.io/team/amcharts/pen/46236269d3cc15f1dbd73b71f36af1cc?editors=0010

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.65](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.65).

## [4.0.0-beta.65] - 2018-10-28

### Changed
- `tooltip.hiddenState.transtionDuration` and `tooltip.defaultState.transitionDuration` are now set to 1 (on non-animated theme) to avoid some tooltip flickering.
- Individual legend items (label, value label, and marker) now have their  `interactionsEnabled = false` set by default to avoid double events. If you need to add events to these particular elements (as opposed to the whole legend item), you will need to set `interactionsEnabled = true` on that element.

### Fixed
- Calling `show()` on a `MapSeries` object was resulting in an error.
- 3D columns were not visible if their value was zero.
- Bullets are now hidden if `minBulletDistance` is set.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by XxSven** [comment]
Hello,
Is it possible to hide zero-value 3D columns with a parameter ? In some cases having zero-value 3D columns hidden can be useful, mainly for stacked column chart. You can see at a glance which data is empty and easily hover a serie which was below: 
![image](https://user-images.githubusercontent.com/22731605/73436925-b4042480-434b-11ea-96a7-40ba08af99fd.png)
Here we can't know the two last columns have an empty blue serie, and we can't over the purple serie : 
![image](https://user-images.githubusercontent.com/22731605/73437444-a13e1f80-434c-11ea-979c-4d97eb381d5d.png)
Thanks for the support :) !
