### ISSUE TITLE
Creating zebra stripes for axis and chart

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#470]
I'm trying to recreate the behavior as designed in the following image. I'd like to colorize every other stripe of the chart and the x-axis with a slightly different background-color in order to create a "zebra"-style striped look. Can this behavior be implemented with adapters on the chart and axis? Or will it need further enhancements directly in amcharts to enable this?

![image](https://user-images.githubusercontent.com/247564/47202249-f1be8300-d37c-11e8-9455-09374863e7fa.png)

**Comment by martynasma** [comment]
Easy :)

```
axis.renderer.axisFills.template.fillOpacity = 0.2;
axis.renderer.axisFills.template.fill = am4core.color("red");
```

**Comment by Chnoch** [comment]
This is almost what I'm looking for, thanks a lot!
Your code properly colors the chart area, however the axis labels don't have a background-color. Is it possible to apply the same fills to the label area as well?

And by the way, is there any documentation about `axisFills`, I couldn't quite figure out why this works.

**Comment by martynasma** [comment]
There's this tutorial:
https://www.amcharts.com/docs/v4/tutorials/alternated-axis-fills/

I'm afraid axis fills do not extend to cover labels outside of axis :(

**Comment by Chnoch** [comment]
Thanks for the link, I've missed that.

There are no plans to add the `axisFills` to the labels of the axis as well, or is this on the roadmap for somewhere down the line?

**Comment by martynasma** [comment]
Posted a workaround :)

https://www.amcharts.com/docs/v4/tutorials/alternated-axis-fills/#Extending_to_axis_labels

**Comment by Chnoch** [comment]
Thanks for the workaround. The problem is that we have the labels on top of the chart :( And I haven't been able to move the `plotContainer` area with `pixelMarginTop` or another margin with negative values so that it would begin where the labels are. 
But if you don't have another workaround we'll continue with the stripes in the plot area for now.

**Comment by zeroin** [comment]
We have a workaround for everything :)
You must  set dy to -40 for both axisFills and grid templates, like in this demo: 

https://codepen.io/team/amcharts/pen/yRdKvr

**Comment by Chnoch** [comment]
There is a workaround for everything :D

Thanks for the support, this works as expected!
