### ISSUE TITLE
Reducing gap between bars

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#471]
Hi,

I am plotting a clustered bar chart, when the data is very small the gap between bars is more.
How to reduce the gap between those bars.
Below is the code pen url
https://codepen.io/varshamathukumalli/pen/PyeexZ?editors=0010

**Comment by martynasma** [comment]
A gap between columns is what is left from column's `width`, which is set to 80% by default.

So, to decrease gap, you need to increase column's width:

```
series.columns.template.width = am4core.percent(100); // 100 will make columns stick together (no gap)
```

**Comment by Varshamathukumalli** [comment]
If we apply 100%, we are unable to distinguish where 'Lithuania' is ended and where 'Czech Republic' is started.
Is there any way to distinguish that but making the bars sticking together

**Comment by martynasma** [comment]
Yeah, add a white outline to bars:

```
series.columns.template.stroke = am4core.color("#fff");
series.columns.template.strokeWidth = 2;
```
