### ISSUE TITLE
Question: Toggling 100% Stacked Charts?

### ISSUE THREAD

**Issue by pouretrebelle** [amcharts/amcharts4#473]
I'm trying to make a stacked area graph that can be toggled between a 100% stretched height view and normal stacked values with an external trigger (a button).

I can see from [this pen](https://codepen.io/team/amcharts/pen/KQjKdZ?editors=0010) that these are the properties that enable the 100% stacking:

```js
yAxis.min = 0;
yAxis.max = 100;
yAxis.strictMinMax = true;
yAxis.calculateTotals = true;
series.dataFields.valueY = 'value'; // or whatever
series.dataFields.valueYShow = 'totalPercent';
```

but (ignoring the domain thing for a sec and keeping `calculateTotals` turned on) toggling the `valueYShow` between 'totalPercent' and the series key doesn't do anything. Is this something that can be changed dynamically? I think I don't understand how this data binding works... can I add/remove adapters on the series to control whether it uses the percentage value or not?

Thanks for your help

**Comment by martynasma** [comment]
Good question!

To toggle between 100% and regular stack you need 3 things:

1. Remove/set `"valueYShow"` data fields for all series;
2. Remove/set `min`/`max` for value axis;
3. Call `chart.invalidateData()`.

Working example:
https://codepen.io/team/amcharts/pen/ePrjKz?editors=0010

**Comment by pouretrebelle** [comment]
🙌  Thank you!
