### ISSUE TITLE
Cursor / Tooltip not displayed initially after beta.58

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#482]
I have encountered an issue since beta.58 that the cursor and thus the tooltip are not displayed after the initial render in a chart. Once a rerender is triggered, e.g. through updating data, the tooltips start working.

The chart where the cursor no longer works is contained in a Bootstrap "Collapse" component, which uses an animation to open its content. If I start rendering the chart only once the animation is completed the tooltips and cursor work fine, however if I start rendering the chart as soon as the "Collapse" starts opening, tooltips won't work.

**Comment by martynasma** [comment]
Hey, it would help a lot if you could produce a working demo on codepen or somewhere else we can try.

Do you think you can swing that?

**Comment by Chnoch** [comment]
I'll see if I can reproduce it in a codepen, will let you know.

**Comment by Chnoch** [comment]
Unfortunately I haven't been able to create a demo on codepen to show the behavior, sorry about that. All the info I can provide is that it started happening with beta.58 (so it must have been a change between beta.57 and beta.58.
It might be related to #466 which sounds eerily similar to what I'm encountering. 

And since I do have a workaround I will subscribe to #466 and see if the fix for that will also fix my issue, so we can close this ticket for now.
