### ISSUE TITLE
Sankey `chart.nodes.template.togglable = false` is ignored

### ISSUE THREAD

**Issue by pdavies88** [amcharts/amcharts4#483]
If you use your Sankey Diagram as an example: https://codepen.io/team/amcharts/pen/JLMeEw
A user should not be able to click on a portion of the diagram and have it collapse if toggable is set to false

**Comment by martynasma** [comment]
Thanks for the heads up!

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

The Sankey docs have been updated as per above:
https://www.amcharts.com/docs/v4/chart-types/sankey-diagram/#Disabling_toggling_or_dragging_of_Nodes

**Comment by pdavies88** [comment]
Thanks I noticed this also on the Chord Diagram as well so you may need to update the docs in both places just as a heads up

**Comment by martynasma** [comment]
Good catch. Thanks!

Updated Chord docs as well.
