### ISSUE TITLE
How to force series tooltip location

### ISSUE THREAD

**Issue by devduke** [amcharts/amcharts4#484]
I'm trying to force the series tooltip location to show only on top. I can't seem to find this option in the documentation. I've set the pointerOrientation to vertical.

```
series.tooltip.pointerOrientation = 'vertical'
```
### Always show like this
![tooltip-top](https://user-images.githubusercontent.com/14028544/47401719-7d833700-d710-11e8-8374-4b393a0b8941.png)

### Not like this
![tooltip-bottom](https://user-images.githubusercontent.com/14028544/47401733-8bd15300-d710-11e8-839c-d79cdb7da7d5.png)

**Comment by martynasma** [comment]
There's currently no such setting that would force the Tooltip to always come up on top, even if it would not fit into chart area.

We are going to add one, at which point we'll ping you.

Thanks for the suggestion!

**Comment by martynasma** [comment]
This is now possible using `pointerOrientation = "down"`.
