### ISSUE TITLE
Change pie chart legend bullet size

### ISSUE THREAD

**Issue by Capaman** [amcharts/amcharts4#489]
How to change the size of the bullets in a pie chart legend? 

I can change the font size of each legend with chart.legend.fontSize = 11 ... but how do I change the size of the corresponding bullets? I want to shrink the size and cornerRadius should be also 0 similar to the tooltip

		var series = chart.series.push(new am4charts.PieSeries());
		series.dataFields.value = "litres";
		series.dataFields.category = "country";

		// this creates initial animation
		series.hiddenState.properties.opacity = 1;
		series.hiddenState.properties.endAngle = -90;
		series.hiddenState.properties.startAngle = -90;
		series.fontSize = 11;
		series.tooltip.fontSize = 11;
		series.tooltip.background.cornerRadius = 0;

		chart.legend = new am4charts.Legend();
		chart.legend.fontSize = 11;

**Comment by martynasma** [comment]
Short answer you do it like this:

```
var markerTemplate = chart.legend.markers.template;
markerTemplate.width = 40;
markerTemplate.height = 40;
```

The following section of legend tutorial has examples and code:
https://www.amcharts.com/docs/v4/concepts/legend/#Customizing_markers

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
