### ISSUE TITLE
MapPolygonSeries.hide() / show() does not fade out/in

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#494]
if Animated theme is enabled calling `hide()` and `show()` on a `MapSeries` does not fade it out or in as it should, but rather toggle it off and on.

Exmple:
https://codepen.io/team/amcharts/pen/87cda9a13864538ea25ba3d35fb154ea?editors=0010

(click any country to trigger `hide()` then wait for 5 seconds for `show()` to kick in)

**Comment by zeroin** [comment]
You have to set series.hiddenState.properties.opacity = 0 in order this to work. Added this as default in animated theme.
