### ISSUE TITLE
Preventing Nuxt.js from loading external libraries

### ISSUE THREAD

**Issue by devduke** [amcharts/amcharts4#499]
I can't seem to figure out how to exclude external libraries in Nuxt as shown in the tutorial here for Vue.

https://www.amcharts.com/docs/v4/tutorials/preventing-vue-js-from-loading-external-libraries/

I'm importing amCharts as shown below.
```
import * as am4core from '@amcharts/amcharts4/core'
import * as am4charts from '@amcharts/amcharts4/charts'
import am4themesAnimated from '@amcharts/amcharts4/themes/animated'
```

**Comment by msacchetti** [comment]
Anyone know how to do this?

**Comment by zoxon** [comment]
This worked for me https://github.com/amcharts/amcharts4/issues/272#issuecomment-415970840
