### ISSUE TITLE
Test issue #4

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#5]
Test issue. Disregard.

**Comment by amcharts** [comment]
> New comment from Zendesk by **Martynas Majeris** on ticket **33362**.
> (replying here will automatically notify amCharts support agent)

Test comment #2.

Yours sincerely,

Martynas Majeris
amCharts

**Comment by amcharts** [comment]
> Status of ticket **33362** was changed to **Open** by **Martynas Majeris** on Zendesk.
> (replying here will set ticket's status back to Open until ticket is Closed)
