### ISSUE TITLE
Add support for v3's grouped pie slice and related properties

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#509]
v4 seems to be missing support for grouped pie slices like in v3 through the following properties:

- groupedAlpha
- groupedColor
- groupedDescription
- groupedPulled
- groupedTitle
- groupPercent

**Comment by martynasma** [comment]
Possible with a plugin:
https://www.amcharts.com/docs/v4/tutorials/plugin-slice-grouper/
