### ISSUE TITLE
Refreshing the chart without drawing again

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#512]
Hi,

If we change a property in chart object of a given chart type or change the width and height, instead of redrawing the chart all over again, is there any way to refresh the chart

**Comment by zeroin** [comment]
The chart should redraw itself automatically redrawing only the affected areas. If it doesn't, please, show us the case and we will investigate why.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
