### ISSUE TITLE
type error in chart creation

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#513]
Hi,

am4core.create("chartdiv", am4charts.XYChart)

With the latest update, while creating a chart as above, we are getting this exception:
Argument of type 'typeof XYChart' is not assignable to parameter of type 'new () => Sprite'.
  Type 'XYChart' is not assignable to type 'Sprite'.
    Types of property 'copyFrom' are incompatible.
      Type '(source: XYChart) => void' is not assignable to type '(source: Sprite) => void'.
        Types of parameters 'source' and 'source' are incompatible.
          Type 'Sprite' is not assignable to type 'XYChart'.
            Property '_dataFields' is missing in type 'Sprite'

**Comment by xorspark** [comment]
Did you clear your cache after updating? I'm not seeing this error on my end. If you're still seeing the problem after clearing your cache, can you please provide a codepen that reproduces this?

**Comment by Varshamathukumalli** [comment]
Typescript is throwing this error, not related to browser

**Comment by xorspark** [comment]
My mistake. I just tried this now on beta 71, which went out a couple of hours ago, and I'm not seeing the problem. Can you confirm?

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
