### ISSUE TITLE
Error Chart support

### ISSUE THREAD

**Issue by sandcastle** [amcharts/amcharts4#520]
Please add Error Chart support to v4, I have not seen a solution to this one yet and its a show stopper for us. Thanks 👍 

https://www.amcharts.com/demos/error-chart/

**Comment by martynasma** [comment]
It's in the TODO list. Will ping you when it is available.

Meanwhile, we're going to count on your patience ;)

**Comment by sandcastle** [comment]
@martynasma - thanks for the update. Do you know if it will be in the Nov RTM release?

**Comment by zeroin** [comment]
Error chart is now supported:
https://www.amcharts.com/demos/error-chart/
https://www.amcharts.com/demos/xy-error-chart/
