### ISSUE TITLE
Question: How to represent this

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#523]
Hy guys, I need some help.
I have some X,Y input data (I know every one of them what it means end where to put it) and have to represent them like in the pic bellow.
Basically I will have some horizontal lines in pairs (min-max) of different lengths and between them I have to fill with color or a hash pattern.  What components should I use?
Thank you in advance.

![image](https://user-images.githubusercontent.com/21243081/47970861-7dc9ed80-e093-11e8-83ba-ea6acdffd165.png)

**Comment by martynasma** [comment]
Maybe a chart with two `ValueAxis` and a few `StepLineSeries` with a fill between them, as well as `AxisRanges` as guides?

This is a very crude prototype:
https://codepen.io/team/amcharts/pen/259225a353f5b87b8bb2881a491179ec?editors=0010

**Comment by aniov** [comment]
Thank you, I've done it in a more complicated way. Now I think I should re-make it.

**Comment by martynasma** [comment]
Ah man, so sorry I couldn't get back to you earlier. We're super stretched heading towards release of amCharts 4.

In any case, I'm going to close this, but feel free to reopen or post any follow ups if you have questions.
