### ISSUE TITLE
Perfomances with multiple charts

### ISSUE THREAD

**Issue by Calandal95** [amcharts/amcharts4#525]
Hello,
in my React-based application i'm using multiple charts components created with AmCharts 4 library.
I'm experiencing low performances and freezes during the load of the page (i use react router to navigate through the different pages of my web app. Some pages have multiple charts, others not).
Using the Mozilla Firefox performance tool i had this result:
![cattura](https://user-images.githubusercontent.com/39583628/47992688-cf9f6180-e0ed-11e8-930e-40fcf5d73e43.PNG)

There is something i can do to improve the overall loading perfomances?
Thanks in advance
Alessio

**Comment by Calandal95** [comment]
Hi,
yes i'm running the latest version

**Comment by martynasma** [comment]
OK, cool. Would it be possible to create some kind of live example of your setup, which we can test?

**Comment by Calandal95** [comment]
I can't provide the project i'm working for since it's commercially protected. I can create a similar example but obviously it's not guaranteed that will match the actual perfomances of my project.

**Comment by martynasma** [comment]
I totally understand. If it would be possible to replicate something similar with bogus data, that would go a long way towards helping us in resolving it.

**Comment by BrkCoder** [comment]
https://stackblitz.com/edit/angular-mgrid-example.

I would like to know if we are using JSON-base config approached and started a chart with empty data, does the chart redraw every time a data is changed or any property of chart config is changed?
If so it is very time consuming task.
Does there differences between class based approached and JSON base approached in terms of Performances?
It is a very critical issue for me.

**Comment by zeroin** [comment]
When data is changed, the chart is of course redrawn. When some property is changed, it depends on a property - if you change some color or so, of course it will only change the needed element. But if you change some width or height of some object which influences a lot of layout of the chart, then a lot of objects will be redrawn. The redraw is not instant, so if you change multiple properties of one object, it will be redrawn only once. But as I understand you do change properties of a real objects, not via JSON config, right? as JSON is used only once, when the chart is initialized for the first time. 

I can also suggest you to try this approach - pause all the amcharts execution initially and then unpause it only when all the other elements of your application are build, properly sized, etc. This way you will avoid multiple redraws of the charts. To do so, do this:

`am4core.system.isPaused = true; // pauses everything`
`am4core.system.isPaused = false; // resumes everything`

**Comment by zeroin** [comment]
Just wanted to let you know that initial rendering performance was improved in the latest version, so I would recommend trying it out.
