### ISSUE TITLE
canvg dependency issue

### ISSUE THREAD

**Issue by SGStino** [amcharts/amcharts4#527]
I'm getting the following error while installing amcharts:
`node_modules\canvg\node_modules\canvas\src\canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Canvas.cc)`

I would guess it's related to this:
https://github.com/canvg/canvg/issues/647 

The suggested fix doesn't seem to work.
```
  "resolutions": {
    "canvg": "1.5.3"
  }
```

However, installing canvg with the specific version before installing amchart did:
```
npm install canvg@1.5.3 
npm update @amcharts/amcharts4
```

**Comment by Pauan** [comment]
Yeah, this is an issue with `canvg`, so let's continue the discussion in that canvg issue.

Thanks for letting us know about this!
