### ISSUE TITLE
How to get Pie Chart to have single active slice behavior?  

### ISSUE THREAD

**Issue by taylorehat-cs** [amcharts/amcharts4#529]
By default, the pie chart allows a user select/pull-out multiple slices, is there a way to limit the chart to a single active slice, like a radio button behavior?

Thanks,
Taylor

**Comment by martynasma** [comment]
There's currently no such setting available. We will consider adding one.

In the interim, you can use an event to close all open slices when a slice is selected:

```
pieSeries.slices.template.events.on("hit", function(ev) {
  var series = ev.target.dataItem.component;
  series.slices.each(function(item) {
    if (item.isActive && item != ev.target) {
      item.isActive = false;
    }
  })
});
```

Here's a working example:
https://codepen.io/team/amcharts/pen/ZmGQPZ/

**Comment by taylorehat-cs** [comment]
Awesome. Thank you.
