### ISSUE TITLE
Setting custom DOM id of chart ValueAxis

### ISSUE THREAD

**Issue by Ekliptor** [amcharts/amcharts4#538]
Hi,
im using beta72 from NPM.

I want to set custom DOM ids of additional value axis on the right of my XY chart. I need this for responsive design to hide some axis on smaller screens.

I do:
```
let valueAxisAdditional = chart.yAxes.push(new am4charts.ValueAxis());
valueAxisAdditional.renderer.opposite = true;
valueAxisAdditional.id = "Foo";
```
However, when inspecting the DOM or executing:
`document.getElementById("Foo"); // returns null`
I see that the ID is not set.

Am I missing something? How can i set a custom DOM id for Amchart elements?
Or setting custom css classes would help too.

**Comment by martynasma** [comment]
Setting `id` does not automatically sets the `id` attribute on the element itself.

To force that call the `uidAttr()` method (no params) after setting the `id` property.

(it's an undocumented property, not sure why, frankly) :)

**Comment by Ekliptor** [comment]
On what object do I have to set the id and call uidAttr()?
Doing this on `ValueAxis` doesn't add the ID to the DOM.

**Comment by martynasma** [comment]
OK, sorry. That's not it.

There is a way to set an id on an element:

```
valueAxisAdditional.element.attr({ "id": "Foo" });
```

However, I strongly discourage from using it.

Probably better way to add a class name:

```
valueAxisAdditional.id = "Foo";
valueAxis.setClassName();
```

The value axis element will end up like this:

```
<g class="amcharts-ValueAxis-group amcharts-Foo">
```

So you can can easily target it by class rather than by id.

**Comment by Ekliptor** [comment]
Hi,
`attr({ "id": "Foo" });` is working for me, however your solution to set class names has no effect for me.
Do I have to call this after rendering does it only work on certain elements (not `ValueAxis`)?
Either way, using `attr()` is good enought for me, even if it's discouraged

**Comment by martynasma** [comment]
Technically, it should work for any element.

I noticed I had a typo in my code snipped. Should have been:

```
valueAxisAdditional.id = "Foo";
valueAxisAdditional.setClassName();
```

**Comment by Ekliptor** [comment]
it's working;)
