### ISSUE TITLE
XYChart: Load new data on drag event

### ISSUE THREAD

**Issue by erichstark** [amcharts/amcharts4#539]
Hello, is it somehow possible to load data when drag event occurred in graph? For example if I drag the timeline from left to right, I would like to fetch older data and show them in the graph.

**Comment by martynasma** [comment]
When zoom/pan occurs, an event ["datarangechanged"](https://www.amcharts.com/docs/v4/reference/axis/#datarangechanged_event) is invoked on the affected axis.

I suppose you can add a handler to add the data load missing data, and updating chart's data with it.

https://www.amcharts.com/docs/v4/concepts/data/#Dynamic_updates

Of course, in order for you being able to zoom outside currently loaded data, you might need to pre-fill your data set with empty data points.

I know it's a bit vague, but we don't have any ready-made example that does that.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
