### ISSUE TITLE
Charts with bullets cannot be updated

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#54]
When you create a chart (line, column) that has bullets and you try to update the chart data, beta 26 is throwing the following error:

> Added to children a disposed object!

Here's an example that shows the problem:

https://codepen.io/anon/pen/QxbMoN

When you click the "Update" button, you'll see the error.

If you comment out lines 54-55 (i.e. the `var bullet` lines), the "Update" button will work as expected. 

I've confirmed this breaks with line, column, but I suspect it's happening with any of the charts.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.27](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.27) ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta27---2018-06-01))
