### ISSUE TITLE
Question: Range fill without reverse at axes 0.

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#541]
Hello, How can I use range.contents.fill without color changing side when graph pass OY=0.
Like this:
![image](https://user-images.githubusercontent.com/21243081/48146508-d11f8400-e2bd-11e8-8290-7c7e0292f282.png)
 and not like this: 
https://codepen.io/aniov/pen/yQeOgR?editors=0010

**Comment by martynasma** [comment]
Awesome question!

To do that, we need to tell `LineSeries` to use vertical axis as a `baseAxis`.

We also need to adjust `baseValue` for the horizontal axis to go well into negative zone if we don't want it to fill to zero line.

```
series.baseAxis = yAxis;
xAxis.baseValue = -1000;
```

This should do the trick.

**Comment by aniov** [comment]
Now it's working the way I wanted. Thank you for your help.

**Comment by martynasma** [comment]
You're welcome.

I'm closing this, but please feel free to post any follow up questions you may have.
