### ISSUE TITLE
Exporting API (print) does not work.  

### ISSUE THREAD

**Issue by beizix** [amcharts/amcharts4#542]
when I call exporting API like below, 

`chart.exporting.export( 'print' );`

it only shows message "Export operation took longer than expected. Something might have gone wrong."

![image](https://user-images.githubusercontent.com/3313285/48180562-5ca11f80-e367-11e8-88b6-753a5a902b2c.png)

I tested at Version 4.0.0-beta.73

**Comment by martynasma** [comment]
Does this happen in all browsers?

I just tried it on this chart and it worked:
https://codepen.io/team/amcharts/pen/c9f4fd6f5bad91ed86720999f33dd511?editors=0010

Does it the above link work for you?

If it does, can you check if maybe there's some error in console in your setup?

**Comment by beizix** [comment]
@martynasma oh I checked it was my mistake. sorry. I'll close this issue. thanks for your replay.

**Comment by martynasma** [comment]
No worries ;)

**Comment by moghthalkushal** [comment]
This happens if you have many fonts , i am facing that issue

**Comment by superbrains** [comment]
> @martynasma oh I checked it was my mistake. sorry. I'll close this issue. thanks for your replay.

Please, How did you resolve this Issue?

**Comment by omprakash-sharma** [comment]
I'm facing same issue as above for PieChart with (PNG,JPG,GIF,PDF) format, only SVG export option working fine.
I'm getting two issue in console log.

1. Access to XMLHttpRequest at 'https://www.amcharts.com/lib/3/plugins/export/export.css' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2. core.js?593e:1440 ERROR Error: Uncaught (in promise): IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at A.Element.feColorMatrix.apply (canvg.min.js?cbb7:1)
![export_issue](https://user-images.githubusercontent.com/19792591/58416427-23c85e00-809f-11e9-9514-773496e5d4d1.PNG)

**Comment by bjcCin** [comment]
I'm having the same problem. My exports are spending a lot of time.

**Comment by omprakash-sharma** [comment]
I guess problem with "am4charts.PieChart3D" which trying to get data from "CanvasRenderingContext2D".
changed "am4charts.PieChart3D" to "am4charts.PieChart" working fine.

**Comment by hshahul** [comment]
I am facing this issue in all my charts. sometimes it download image is working fine, most of the time i am getting ""Export operation took longer than expected. Something might have gone wrong" error or network failure error only..

I tried to add milliseconds also but no luck..

Can you provide any good solution for this.

**Comment by Gulp-uglify-warring** [comment]
@bjcCin https://hassan-exultation8.github.io/sunlight/
