### ISSUE TITLE
Issues with series.mapImages.create() on a Map

### ISSUE THREAD

**Issue by lmgarret** [amcharts/amcharts4#547]
Hi ! I've got two issues using `mapImages.create()` in the current version of amcharts.

- ISSUE 1: batch creating mapImages (e.g. in a for-loop) can result in some points not displayed or all of them 
- ISSUE 2: if we use `mapImages.create()` to create mapImages instead of settings all by assigning to `aSerie.data`, then updating `.include` will not change antyhing.

CodePen [here](https://codepen.io/anon/pen/XydYdP), both issues are described at the end. 

For issue 1, try to create point using the "add 5 points" html button. Then by pressing 5 times "add 1 point" button (which works..). 

For issue 2, refresh the codepen, add 5 buttons using the `add 1 point` button, and then click the `'include' p0,p1`, which sadly does nothing...

**Comment by martynasma** [comment]
There seems to be an issue with your function that adds 5 points. I went ahead and simplified it to add exactly five points, and it works fine, at least for me:

```
function add5Points(){
  for(i = 0; i<5; i++){
    addPoint();
  }
}
```

Let me know if it works for you.

**Comment by martynasma** [comment]
Are you sure? It adds 5 points every time for me.

However since, they seem to be added in a grid, some of them might be overlapping giving the impression of only a few being added.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
