### ISSUE TITLE
Amchart 4 Sankey Diagram Node out of range

### ISSUE THREAD

**Issue by aad61404** [amcharts/amcharts4#551]
https://codepen.io/aad61404/pen/aQvRyz?editors=0010

I am using amcharts 4 Sankey diagram and I want to fix the node out of range .

I try

```
chart.height = 500;
chart.contentheight = 500;
chart.contentHeight = 500;
chart.innerHeight = 500;
```
It doesn't work . ( the node would be out of range )

Can I limit the amcharts 4 draw chart in 500 px height ? How can I achieve the desired effect ?

**Comment by martynasma** [comment]
Looks like a bug. We'll need to look for the solution.

Thanks for the heads up!

**Comment by zeroin** [comment]
To fix this, try setting 
`chart.nodePadding = 1;`

as node padding is set in pixels, and you have quite a lot of nodes, then the chart goes out of bounds. With even more nodes, you might need to reduce minNodeSize as well.
