### ISSUE TITLE
Modify current color in a state?

### ISSUE THREAD

**Issue by taylorehat-cs** [amcharts/amcharts4#558]
I've been scouring the color and states documentation trying to figure out how to modify the current color of a column and haven't been able to figure it out.

Essentially, I am trying to do this:
`hoverState.properties.fill = am4core.color([Get Elements Current Color]).saturate(-1);`

**Comment by darlesson** [comment]
Try to use [adapters](https://www.amcharts.com/docs/v4/concepts/adapters/) to change the fill such as in:

```
series.columns.template.adapter.add("fill", function (fill, target) {
  return fill.saturate(-1);
});
```

Please check the example here: https://codepen.io/team/amcharts/pen/694b5f7d8170d3e33735a08c9ed401d1?editors=0010

**Comment by darlesson** [comment]
Try to use [adapters](https://www.amcharts.com/docs/v4/concepts/adapters/) to set the fill as shown below:

```
series.columns.template.adapter.add("fill", function (fill, target) {
        // Setting different colors per column
	return chart.colors.getIndex(target.dataItem.index);
});

var hoverState = series.columns.template.states.create("hover");
hoverState.adapter.add("fill", function (fill, target) {
	return fill.saturate(-1);
});
```

Please check the example here: https://codepen.io/team/amcharts/pen/694b5f7d8170d3e33735a08c9ed401d1?editors=0010

**Comment by taylorehat-cs** [comment]
Thank you!

**Comment by valentinvoilean** [comment]
@darlesson , thanks for the codepen example. That works when we want to update the color of the hovered item.
Is it possible to update the color of all the other items than the hovered one ?

**Comment by darlesson** [comment]
@valentinvoilean, I will have to ask someone else to answer that for you. @martynasma, could you take a look at the question above?
