### ISSUE TITLE
StepLines position

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#560]
Hello,

I'would like to do something like this :

![image](https://user-images.githubusercontent.com/6083644/48468302-c0a26880-e7eb-11e8-92b1-2f6a6b2c940d.png)

But I'm not able to do it. I tried : 
https://codepen.io/team/amcharts/pen/GYNXxj?editors=1010

```javascript
series.startLocation = -0.5
```
![image](https://user-images.githubusercontent.com/6083644/48468388-f9424200-e7eb-11e8-956c-6bcf0925d87f.png)

```javascript
series.startLocation = 0.5;
```
Works as espected 
![image](https://user-images.githubusercontent.com/6083644/48468501-5a6a1580-e7ec-11e8-8bbc-54823fc1b9c1.png)

Thansk for your help

**Comment by martynasma** [comment]
How about this?

```
series.startLocation = -0.5
series.endLocation = 0.5
```

The only issue with it is the first horizontal segment.

I suppose it can be hidden with an axis range.

**Comment by ptorrent** [comment]
Thanks !
