### ISSUE TITLE
Date formatting on Category axis

### ISSUE THREAD

**Issue by alexanderliam** [amcharts/amcharts4#561]
The date format "dd/MM/yyyy" is not applying to the x axis of a XYChart with categories.
I have created a codepen example of the issue i'm having, I understand that the dateformatter is inherited from its parent element so the codepen includes the dateformatter globally, at axis level and at series level:

https://codepen.io/alex-wells/pen/vQmWBz

**Comment by darlesson** [comment]
Is the example sent correct? It seems this chart doesn't need date formatting.

**Comment by alexanderliam** [comment]
Hi, @darlesson I've updated the codepen example, I think I made a mistake when originally asking the question

**Comment by martynasma** [comment]
You are using `CategoryAxis`. This axis treats all of the categories as text, hence no formatting applied.

If you need proper date axis, you need to use `DateAxis`, as well as use `dateX` for series' `dataFields`:

```
var dateAxis = chart.xAxes.push(new am4charts.DateAxis());

....

series1.dataFields.dateX = "category";
series1.dataFields.valueY = "value1";
```

Now, setting format for the DateAxis is not as straightforward as setting `dateFormat`. This axis type have multiple levels of granularity, so you need to set for your target one. In your case it's a day.

```
dateAxis.dateFormats.setKey("day", "dd/MM/yyyy");
dateAxis.periodChangeDateFormats.setKey("day", "dd/MM/yyyy");
```

More info:
https://www.amcharts.com/docs/v4/reference/dateaxis/#dateFormats_property
https://www.amcharts.com/docs/v4/reference/dateaxis/#periodChangeDateFormats_property

And here's your pen updated as per above:
https://codepen.io/team/amcharts/pen/pQPQdN?editors=0010

**Comment by alexanderliam** [comment]
Thank you @martynasma, I've updated the code in my solution and can confirm that works 👍
