### ISSUE TITLE
Sankey chart invalidateData not working

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#563]
Hello,

I am not able to update a value (Sankey Chart, bad rendering when value is updated)

Am I doing something wrong?

https://codepen.io/ptorrent/pen/bQWNwr?editors=0010

```javascript
setInterval(function(){
  chart.data[8].value = Math.random()
  chart.invalidateData()
},1000)
```

Thanks for support

**Comment by martynasma** [comment]
It does work for me. Can you clear your browser cache and try again. Just in case the last update we released last night fixed it.

**Comment by ptorrent** [comment]
Yes it's works on last release :). Sorry
