### ISSUE TITLE
Label bullet's disabled property is not working

### ISSUE THREAD

**Issue by ysreddy99** [amcharts/amcharts4#565]
Hello,

Label bullet's disabled property is not working. Please find the below codepen example.

https://codepen.io/ysreddy/pen/KrmeNE?editors=1010

**Comment by martynasma** [comment]
Why don't you disable the whole bullet?

This works:
```
function disable(){
  labelBullet.disabled = true;
}
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
