### ISSUE TITLE
Dependency sizes

### ISSUE THREAD

**Issue by kanadaj** [amcharts/amcharts4#569]
AmCharts 4 seems to have some ridiculously huge dependencies such as pdfmake and xlsx - could you make these optional? AmCharts 4 is already *huge*, and these libraries don't seem necessary...

![image](https://user-images.githubusercontent.com/3247357/48577894-37d11d00-e910-11e8-8c12-09eb69a12d79.png)

**Comment by eliashdezr** [comment]
@darlesson what about Angular 2+ setups?

**Comment by genichiro** [comment]
> @kanadaj, is this a Webpack and Vue setup? I recommend you to check https://www.amcharts.com/docs/v4/tutorials/preventing-vue-js-from-loading-external-libraries/ if that is the case.
> 
> You could try to set [externals](https://webpack.js.org/configuration/externals/#regex) as in `externals: /(xlsx|pdfmake|canvg)$/gi` if you are only using Webpack.

I succeeded in excluding `xlsx.js` using this setting.
But `pdfmake.js` and `vsf_fonts.js` are still there.

What should I do?

<img width="2549" alt="2018-11-26 2 48 53" src="https://user-images.githubusercontent.com/2802167/48982461-45fc1600-f126-11e8-8227-8228eedf994d.png">

**Comment by Pauan** [comment]
> @kanadaj AmCharts 4 seems to have some ridiculously huge dependencies such as pdfmake and xlsx - could you make these optional?

They are already optional, and will only be loaded when they are actually used.

----

@genichiro Is pdfmake a separate file, or is it included in the bundle? Judging from your screenshot, it looks like it is in a separate `vendors.pdfmake.js` file.

If it is a separate file, you can safely ignore it, because it will only be loaded when it is actually used.

You can use the browser's developer tools to verify that the `vendors.pdfmake.js` file is not being loaded.

**Comment by darlesson** [comment]
@genichiro I tried few solutions and I could find just one that works by removing PDFMake from the regex and using a `function` instead:

```
  externals: [/(xlsx|canvg)/, function(context, request, callback) {

    if (/(pdfmake)/.test(request)) {
      return callback(null, 'commonjs ' + request);
    }
    
    callback();
  }]
```

**Comment by kernel-memory-dump** [comment]
@darlesson  awesome, works like a charm, thank yoouuuuu

**Comment by eliashdezr** [comment]
Is there any news on how to make this work with `angular-cli`?

**Comment by Pauan** [comment]
@eliashdezr With Angular, it does not load the files if they aren't used, so it already works just fine.

You can verify this in the browser's dev tools (specifically, the Network tab).

**Comment by erictuvesson** [comment]
@Pauan Would it be possible to create a build without `pdfmake`? it's just causing a lot of issues everywhere from slowing down compile time and compile errors etc.

**Comment by eliashdezr** [comment]
Agree, pdf export is not a basic feature that should be bundled and imported by default, it is really annoying to deal with it while developing.

**Comment by erictuvesson** [comment]
This is the only thing blocking me from upgrading our website to webpack 4, any updates?

**Comment by martynasma** [comment]
How about this solution proposed earlier in this thread?

https://github.com/amcharts/amcharts4/issues/569#issuecomment-440143826

**Comment by Pauan** [comment]
@erictuvesson If you're getting compile errors, that's a bug and you should report it. There shouldn't be any negative effects at all (except maybe for increased compile time).

As for a separate build, you can always use [the `<script>` tag version](https://www.amcharts.com/docs/v4/getting-started/using-javascript/) which is precompiled, so there shouldn't be any impact on compile times.

----

@eliashdezr Could you explain more about how it's affecting your development? Maybe we can improve that.

**Comment by martynasma** [comment]
FYI, Webpack tutorial updated:
https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/#Large_file_sizes

**Comment by erictuvesson** [comment]
@martynasma That didn't work the last time we tried to solve it (5 months ago), but it still doesn't solve my compiler error. :(

---

@Pauan With the upgrade to webpack 4 babel was removed and amcharts is using babel for the experimental dynmaicImport. I could add back babel, but that includes adding a new loader etc, seems like a lot of steps to just get amcharts working with webpack 4.

Unfortunately I am using Typescript so I can't just switch to use `<script>` tag, but that would solve the compile error. Are there any amcharts typings for typescript?

**Comment by Pauan** [comment]
> That didn't work the last time we tried to solve it (5 months ago)

Make sure you're using a `function` for the `externals` (as described in the link @martynasma posted).

>  With the upgrade to webpack 4 babel was removed and amcharts is using babel for the experimental dynmaicImport.

No, we have never required or used Babel. Webpack has built-in support for `import()` (and has had built-in support for a long time, even in Webpack 3).

It sounds like you are running into [this Webpack bug](https://github.com/webpack/webpack/issues/8656). We have a section [at the top of our Webpack tutorial](https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/) which explains one way to workaround this bug.

> Unfortunately I am using Typescript so I can't just switch to use `<script>` tag, but that would solve the compile error. Are there any amcharts typings for typescript?

Right, losing types is not fun. You can use things like `declare var am4core: any;` to just get it working.

As for more comprehensive typings for `<script>`, we don't have that (since our npm package *does* have typings), and we don't really want to bloat things up for vanilla JavaScript users. But we'll consider it.

**Comment by erictuvesson** [comment]
It doesn't seem like `xlsx`, `canvg` or `pdfmake` is included in the build now even without the `externals`.  👍 

I did some changes to my webpack config and added babel and it works now.

Thanks for the help!

**Comment by havietduc91** [comment]
> FYI, Webpack tutorial updated:
> https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/#Large_file_sizes

Thank for @martynasma answer, it's work for me

**Comment by matinfo** [comment]
Config that worked for me:

```

module.exports = {
  webpack: {
    configure: (webpackConfig, { env, paths }) => {
      webpackConfig = {
        ...webpackConfig,
        plugins: [
          ...webpackConfig.plugins.filter((element) => {
            if (element.options) {
              return !element.options.hasOwnProperty("ignoreOrder");
            }
            return true;
          }),
          new MiniCssExtractPlugin({
            filename: "static/css/[name].[contenthash:8].css",
            moduleFilename: this.moduleFilename,
            ignoreOrder: true,
            chunkFilename: "static/css/[name].[contenthash:8].chunk.css",
          }),
        ],
      };
      return webpackConfig;
    },
...
}
```

```
"@craco/craco": "^5.7.0",
"craco-antd": "^1.19.0",
```

**Comment by Johnnybar** [comment]
Hi, 
after being able to remove the pdfmake and canvas dependencies using @martynasma solution, our backend still reports an error related to them while creating the frontend build. There seem to still be require() function that needs resources from both. One of which is:
[ERROR] ERROR in C:/_Workspace/developing/projects/our-project/projectname/modules/frontend/node_modules/@projectname/frontend/dist/project/js/project.min.js
[ERROR] Module not found: Error: Can't resolve '../../pdfmake/vfs_fonts' in 'C:_Workspace\developing\projects\projectname\project\modules\frontend\node_modules@project\frontend\dist\project\js'

could this be related, among other things, to this line in our minimized file?
` `
/***/ (function(module, exports) {
module.exports = require("../../pdfmake/vfs_fonts");
/***/ }),
/***/ 587:
```

Thanks for your help!

**Comment by NaanProphet** [comment]
> One possible option is to use [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus). You can follow their instructions and add the webpack.extra.js file with the following content:
> 
> ```
> module.exports = {
>     "externals": {
>         "pdfmake": "pdfmake",
>         "xlsx": "xlsx",
>         "canvg": "canvg"
>     }
> }
> ```

Success with [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) in Angular 9. I followed steps 2, 3, and 5 from the [Getting Started](https://github.com/manfredsteyer/ngx-build-plus#getting-started) section. Reminder to [get the right version](https://github.com/manfredsteyer/ngx-build-plus#get-the-right-version).

However, I needed to use the regex/function approach to get canvg and pdfmake to be properly excluded. Otherwise, only xlsx was being excluded. My final `webpack.partial.js` file looks like: 
```
const webpack = require('webpack');

module.exports = {
  externals: [
    function (context, request, callback) {
      if (/xlsx|canvg|pdfmake/.test(request)) {
        return callback(null, "commonjs " + request);
      }
      callback();
    }
  ],
}
```

**Comment by buddhagrg** [comment]
Hi, I have installed amchart4 and in webpack config file added external function as follows; 
```
  externals: [
    function ({ context, request }, callback) {
      if (/canvg|pdfmake/.test(request)) {
        return callback(null, "commonjs " + request);
      }
      callback();
    }
  ],
```
I have  another npm package xlsx (https://www.npmjs.com/package/xlsx) in the app for exporting purpose.
In the above external function, is there any way that i can exclude the xlsx inside that _**amchart package only**_  ? I don't know why but i just think the xlsx inside amchart as default has been a major issue for me. Is there anyway we can solve this issue ?

**Comment by roccomaniscalco** [comment]
Anyone know of a rollup solution?
