### ISSUE TITLE
Sometimes Cursor-enabled series tooltips appear in wrong place, or do not appear at all

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#57]
Happens when switching between categories quickly.

![2018-06-01_18-39-56](https://user-images.githubusercontent.com/1458520/40849713-5a343c4c-65cb-11e8-95a7-a8dcd81af713.gif)

Example: https://codepen.io/team/amcharts/pen/336ea4414ce8b1b7464bfa93ca9758f7/

**Comment by goloveychuk** [comment]
I saw similar bug, and it appeared when I turned on animations

**Comment by martynasma** [comment]
Solved in [4.0.0-beta.28](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.28) ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta28---2018-06-05)).
