### ISSUE TITLE
Animated updates to PieSeries data

### ISSUE THREAD

**Issue by lucianholt97** [amcharts/amcharts4#572]
I'm currently working on a chart, which dynamically responds to filters, set by the user.
Therefore I need to add and remove data points to a PieSeries at a given index. The addData method works so far, but the changes are not animated at all (yes, I am using am4themes_animated). There is a removeData method, but it is not possible to define an index, where the data should be removed. Additionally, the removeData method throws an error "Cannot read property 'values' of undefined" when I remove any element.
When I try to use series.data.splice(), the data gets removed from the series.data array, but there are no visual updates, even combined with series.invalidate(Raw)Data

Is there something I am missing or is amCharts4 currently not able to do what I need it to?
Thank you in advance!
Best regards,
Lucian

**Comment by martynasma** [comment]
To make the values animate from one to another, you need to modify existing data point in data, then call chart's `invalidateRawData()` method.

Example:
https://codepen.io/team/amcharts/pen/d1f4e6f1f1b9592b1a5151730c713cca?editors=0010

Here's more info:
https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points

**Comment by martynasma** [comment]
Sorry for not getting back earlier, and for not catching your requirement.

No, there's no way to animate newly inserted values at the moment.

We might add such capability in the future, but for now there's no option :(

**Comment by martynasma** [comment]
Both should work, except after calling them you need to instruct the chart to revalidate data by calling `chart.invalidateData()`.
