### ISSUE TITLE
Labels alignment issue

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#573]
Hi,

In the codepen provided, x-axis labels are right aligned.
If we want them to be centre aligned and keep the position as _middle_, the positioning of labels is changing.
https://codepen.io/varshamathukumalli/pen/KrmaLv?editors=0010

Is there a way to keep the position same and modify the alignment

**Comment by martynasma** [comment]
You should probably then set labels' `verticalCenter` to "middle":

```
categoryAxis.renderer.labels.template.verticalCenter ='middle';
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
