### ISSUE TITLE
Axis min values with adjusting scales

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#575]
Is it possible to specify a flexible minimal value for a `ValueAxis`? My use case is that I want the `valueAxis` to always (`min`) start at least at 0, with an `extraMin` value of 0.1, so that we have some padding below the 0 axis. This is mostly useful when all values in the chart are in a positive range (e.g. between 2 and 3), which would make amcharts by default select a scale that only displays values in this range (with respect to the `extraMin` flag). However it's also possible that the chart can contain values that are negative. And in this case the scale of the `valueAxis` does not expand to cover the full range of the negative value.

An example can be seen in the following codepen: https://codepen.io/chnoch/pen/QJqeZK
Even though "Distribution" has a value of -1000, the scale only goes from -500 to 1000. How can I enable the `valueAxis` to at least start the scale at 0, but expand in case we have negative elements?

**Comment by martynasma** [comment]
Maybe something like this is the solution:

```
chart.events.on("inited", function(ev) {
  if (valueAxis.min >= 0) {
    valueAxis.min = 0;
  }
  valueAxis.extraMin = 0.1;
});
```

**Comment by Chnoch** [comment]
Thanks, that seems to perfectly match my needs!
