### ISSUE TITLE
Display problem with the Mercator and Miller projections

### ISSUE THREAD

**Issue by TomCorvus** [amcharts/amcharts4#579]
Hello,

I have a display problem with the Mercator and Miller projections in AmMap 4.

![AmMap 4](https://i.postimg.cc/fWPQZjDT/screen0001.jpg)

As you can see, a piece of Russia appears on the left of the map.

Below the result with AmMap 3:

![AmMap 3](https://i.postimg.cc/JnPxmqXr/screen0002.jpg)

Thanks for your answer :thumbsup:

**Comment by martynasma** [comment]
Hi, there.

Well, that's how maps are displayed in amCharts 4. The 180/-180 longitude threshold is cut off and is shown on the other side where it should appear based on coordinates. 

BTW, why is that a problem? :)

**Comment by RobbiesCode** [comment]
Hi Tom,

In amCharts v4 you can change the `deltaLongitude` of the map. Basically this defines the center of the map.

You can easily change it to your desired center like this:

```
chart.deltaLongitude = -10;
```

Possible values are -180 until +180.

Here's a Codepen example: https://codepen.io/team/amcharts/pen/3ec13ecc2f3bdb185ff1c9597100e120?editors=1010

Hope this helps!

**Comment by martynasma** [comment]
Yeah, that works, too :) Thanks rob :)
