### ISSUE TITLE
IE 11 Ignore tooltipHTML and use tooltipText

### ISSUE THREAD

**Issue by WojciechKlisiewicz** [amcharts/amcharts4#580]
Amcharts4 4.0.0 beta 84 (libs from zip file)

tooltipHTML is ignored on IE11 and show tooltipText (instead of tooltipHTML like on Chrome). Setting tooltipText = '' will not help.

**Comment by xorspark** [comment]
tooltipHTML uses `<foreignObject>` to show HTML content in SVG, which [isn't supported by IE 11 and below](https://caniuse.com/#search=foreignobject). You have provide alternate content in tooltipText for IE.

**Comment by xorspark** [comment]
No, it's a browser limitation so there isn't a fix for this, which is why tooltipText is a fallback. Centering text can be done by setting `textAlign` at the series' tooltip label, e.g. `series.tooltip.label.textAlign = "middle";`. I'm following up internally on how to set maxWidth correctly.

**Comment by xorspark** [comment]
Sorry for the delay on this.

You can set `series.tooltip.label.maxWidth` to control the width of the tooltip. If you want the text to wrap when with the width is reached, you also need to set `series.tooltip.label.wrap = true`. If you want the text to get truncated, use `series.tooltip.label.truncate = true`.

**Comment by WojciechKlisiewicz** [comment]
So:
series.tooltip.label.maxWidth = am4core.percent(100);
works with:
series.tooltip.label.wrap = true;

but wrap unfortunately works like word-break: break-all in css but expected will be word-break: normal and white-space: normal to not split simple word. Is no any option to add it in future?

**Comment by havietduc91** [comment]
Thank @WojciechKlisiewicz for raise this issue and I have read this issue on the Amchart docs https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/
```
They will not work on Internet Explorer browsers (Edge is fine) and some other really old browsers. 
The tooltip will try to fall back to the SVG text on those browsers, so you might also want to set 
tooltipText as a mean for alternative content.
```
But hope that someone has some alternatives solutions to show rich tooltip HTML on IE, we'd like to show the tooltip like the below image 

![66103381-c1004980-e5df-11e9-98c1-e47deea36cc0](https://user-images.githubusercontent.com/4966192/69128438-dfae9700-0ade-11ea-9e72-cbf480d57202.png)

anyone can help to resolve this issue, many thanks?
