### ISSUE TITLE
Map tooltipHTML container is too small

### ISSUE THREAD

**Issue by Ekliptor** [amcharts/amcharts4#581]
Amcharts4 beta86 from NPM

Hi,
I'm using a map charts to display tooltips using `tooltipHTML`.
However, the tooltip box is too small, making part of the text unreadable. This same code used to work fine about 3 months ago, so it's likely due to a recent change in your code. Or is there a new API to set tooltip size?

Screen: https://ibb.co/jN8fsA

```
        let chart = am4core.create(chartID, am4maps.MapChart);
        chart.id = chartID;

        // Set map definition
        //chart.geodata = this.addChartDefaultProps(am4geodata_worldLow, ["count", "countPercentageDisplay", "datacenters"]);
        chart.geodata = am4geodata_worldLow;
        // Set projection
        chart.projection = new am4maps.projections.Miller();

        // Create map polygon series
        let polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
        // Make map load polygon (like country names) data from GeoJSON
        polygonSeries.useGeodata = true;

        // Configure series
        let polygonTemplate = polygonSeries.mapPolygons.template;
        polygonTemplate.tooltipHTML = "<div><b>{name}</b><br>" + i18next.t("streams") + i18next.t("colon") +"{count} ({countPercentageDisplay}%)<br>"
        + i18next.t("datacenters") + i18next.t("colon") +"{datacenters}</div>";

        polygonTemplate.adapter.add(/*"tooltipText"*/"tooltipHTML", (text, target) => {
            // text contains markers before replacement: Streams: {streams}
            const data = target.dataItem.dataContext as any;
            if (data.count === undefined || data.count == 0) // actually undefined
                return "<b>" + data.name + "</b>";
            return text;
        });
        polygonTemplate.fill = am4core.color("#bcb8b5");

        // Create hover state and set alternative fill color
        let hs = polygonTemplate.states.create("hover");
        hs.properties.fill = am4core.color("#a09d9a");

        // Remove Antarctica
        polygonSeries.exclude = ["AQ"];
```

**Comment by adtype-com** [comment]
Same problem here. Any solution available?

**Comment by martynasma** [comment]
Do you guys have any sure way to reproduce it?

I tried this:
https://codepen.io/team/amcharts/pen/216ece84d08c9f028bcbf20c64359dd5?editors=0010

Tooltip is sized correctly:
![image](https://user-images.githubusercontent.com/1458520/48851348-7dc82e00-edb3-11e8-9efe-26f6bc67364f.png)

**Comment by adtype-com** [comment]
I just updated to `4.0.0-beta.86` and after solving a typescript compilation issue it works as expected. I did have to add a width and height to the html content wrapper. Although I need to investigate a better solution to support all screen resolutions, don't think this is the best solution.

```
series6.tooltipHTML = `
  <div style="height: 500px !important; width: 600px; !important; padding: 5px;">
    <table>...</table>
  </div>`
```

**Comment by Ekliptor** [comment]
The example of your codepen is NOT working for me in Chrome 70 on OSX.
See https://ibb.co/jzeLSA
The tooltip is again too small, even though unlike in my code it almost has the proper size.

I guess a valid workaround would be to wrap the tooltip HTML in a div and use own styling. But this was not necessary around beta35, so somehow your tooltip styling got worse - especially the height of tooltips

**Comment by martynasma** [comment]
Weird. This is what I get on OSX/Chrome70:

![image](https://user-images.githubusercontent.com/1458520/48891819-15c22800-ee45-11e8-8bc6-2d25c7d8c23a.png)

@Ekliptor can you try clearing your browser cache and trying again?

**Comment by Ekliptor** [comment]
Same problem in Chrome 70 on OSX, also in incognito mode: https://ibb.co/htgkCA
I also just tried in Firefox 63.0.3 (64-bit) and have issues too: https://ibb.co/e2OAeq
The only difference is that FF seems to cut "properly" on the `<br>` tag, not displaying anything below it.

**Comment by martynasma** [comment]
It is shown as `foreignObject` within structure of chart's SVG.

Try running a search for it in element inspector?

**Comment by Ekliptor** [comment]
OK my tooltip object in chrome is always too low in height, only `72px`:
```
<foreignObject width="450.875" height="72"><div style="white-space: nowrap; color: rgb(0, 0, 0); display: block;"><div><b>Brazil</b><br>Some text more text blah<br>OK let's try even longer text how it goes<br>No? Hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm<br>Still no<br>Still no<br>Still no<br>Still no<br></div></div></foreignObject>
```

**Comment by martynasma** [comment]
Sounds like it may be something font-related.

Does non-HTML tooltip size OK for you?

**Comment by Ekliptor** [comment]
Yes it does.
```
        polygonTemplate.tooltipText = "<div><b>{name}</b>\n <br>Some text more\n\n\n text blah<br>OK let's try even longer text how it goes<br>No? Hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm<br>\n\nStill no<br>Still no<br>Still no<br>\n\n\n\n\n\nStill no<br></div>";
```

Results in a `span` instead of the `foreignObject` with the correct size.

**Comment by Ekliptor** [comment]
not in the next few days, but I can confirm it does work in Chrome on an Windows Server 2012 R2: https://ibb.co/n367QV

**Comment by martynasma** [comment]
OK, I'm going to have to shelve this until we find a way to reproduce it.

Awfully tricky to debug issues that can't be reproduced :)

**Comment by adtype-com** [comment]
Interestingly enough, codepen is not working for me either on my mac.

Version 70.0.3538.102 (Official Build) (64-bit) 
Mac OS High Sierra version 10.13.5. Retina 13-inch

<img width="1440" alt="screen shot 2018-11-22 at 11 37 05" src="https://user-images.githubusercontent.com/14118431/48897683-f9c18500-ee4a-11e8-89a7-f1314739bd06.png">

So it does seem to point towards it being a system issue.

**Comment by Ekliptor** [comment]
running `system_profiler SPFontsDataType` gives me the following fonts installed: https://gist.github.com/Ekliptor/a2d7deabfba50291d3611ee3ed7d5be7
The reason it's so many, is because of ImageMagick installed via `brew`

**Comment by martynasma** [comment]
Hey, can you check if this is still relevant with the latest version?

**Comment by Ekliptor** [comment]
just checked it with
`Amcharts 4.0.10` from NPM
OSX Mojave 10.14.2

The error does not occur anymore. Even when removing the CSS of my wrapper div for the `tooltipHTML` I can see all the text👍

**Comment by martynasma** [comment]
Alright. Thanks for checking!

Gonna go ahead and close it then :)
