### ISSUE TITLE
How to remove credits?

### ISSUE THREAD

**Issue by adnanoner** [amcharts/amcharts4#582]
Hi guys,

We're already migrating from v3 to v4 and will upgrade our license. We've added commercialLicense = true however are still seeing the credits. Will this already be fixed in the beta?

**Comment by martynasma** [comment]
Hey,

In amCharts support area, go to "[My Downloads](https://www.amcharts.com/support/my-downloads/)". There should be extensive instructions about the matter.

Or, email us at contact@amcharts.com

**Comment by adnanoner** [comment]
Thanks!
