### ISSUE TITLE
Error when minify/merge core.js with WP Rocket on WordPress

### ISSUE THREAD

**Issue by TomCorvus** [amcharts/amcharts4#585]
Hi, :wave:

I need some information on the AmMap plugin for WordPress.
I updated the code of our map to use AmMap 4 with your WordPress plugin and I have an error in the console when WP Rocket (a cache plugin for WordPress) minifies and merges all JS files called on the page.
[https://www.glanum.com/accueil-2-2/](url)

`Uncaught SyntaxError: Unexpected token }`

This error is in the minified core.js code of AmMap 4.

Here is the code when the file is minified and merged:
`t.length,o=0;o<r&&(t[o](n),i);++o)}}`

And the code of the original file:
`t.length,o=0;o<r&&(t[o](n),i);++o);}}`

The semicolon at the end is missing.

I contacted the WP Rocket team to have more information and her answer is to exclude this file of the minification.

However, before to do that, I want to know if this error can be avoided?

Thanks for your answer.

Links:
[https://wp-rocket.me/](url)
[https://wordpress.org/plugins/amcharts-charts-and-maps/](url)

**Comment by TomCorvus** [comment]
They use the minifier of Matthias Mullie:
[https://www.minifier.org/](url)
[https://github.com/matthiasmullie/minify](url)

You can try the online minifier. The semicolon is deleted.
WP Rocket team will create a ticket on the repo, but not sure that Matthias will fix the problem. He is not active on it since May 2018.
And I don't think WP Rocket will change their minifcation system.

**Comment by jgwhite33** [comment]
I just came across this in a google search. WP Rocket was also deleting the semicolon in my plugin file. I found that if I put a console.log(); directly after the problem line, it keeps the semicolon when minifying. Just thought I would share.

**Comment by martynasma** [comment]
Thanks for sharing these additional details.

I'm not sure putting empty `console.log()` calls is a solution.

I suppose we should wait if minification people fix it on their end. Without applying dubious workarounds, that might affect other people, that are not using this specific minifier or WP Rocket.

Does that sound like a plan?

**Comment by TomCorvus** [comment]
Hi marty,

I agree. This `console.log()` is not the solution. To be honest I'm not sure that minification people will fix this problem. No answer, no pull since February 2018.
It's a pity because WP Rocket is one of the best cache plugin for WordPress but the minifier is not complete.

I will create a ticket on minify repo. Wait and see.

If you find a way to work around this problem, it's great but it's a minify problem, not amChart.

**Comment by martynasma** [comment]
Fair enough.

We'll explore if there are some options to .js compilation we are using that would bullet-proof libraries against tempering by minifiers.

Will keep you posted if we find anything.

**Comment by martynasma** [comment]
OK, so there's no option to compile our .js files "differently".

We use Webpack, as do a lot of other libraries. It produces valid JavaScript, and if the minifier fails at amCharts, it means it could be failing at whole lot of other libraries. So they really ought to fix that on their end.

That said, since our .js files are already minified, you can try excluding amCharts files from minification with negligible impact on page loading speed. Seems like they do have an option for that:

https://docs.wp-rocket.me/article/915-find-the-right-js-files-to-exclude-from-minification

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
