### ISSUE TITLE
Legend postion issue

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#589]
Hi,

When the legend position is given as right, the legends are not starting from the top instead they are starting from the middle.
Below is the codepen url:
https://codepen.io/varshamathukumalli/pen/yQyrrw?editors=1010
Kindly let us know if any property needs to be added to that

**Comment by martynasma** [comment]
There you go:

```
chart.legend.valign = "top"
chart.legend.marginTop = 0;
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
