### ISSUE TITLE
Amcharts 3 minorGridEnabled equivalent in Amcharts 4

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#590]
Hey, is there any field  in amcharts 4 which equivalent to minorGridEnabled in amcharts 3.
This is a very necessary feature for programmers which migrate from amcharts 3.

**Comment by martynasma** [comment]
I'm afraid this feature is not yet implemented in amCharts 4.

We do have it planned, just can't provide an ETA for it.

We'll ping you here when it's available.

**Comment by MarkLyck** [comment]
I really need this for my project to make it clear to our customers that the chart is logscale. :/

Please update this with an ETA when you start working on it!

**Comment by BrkCoder** [comment]
@martynasma Hey I am really need this feature too, please provide a solution for this issue asap!

**Comment by jpgalera** [comment]
any update on this feature?

**Comment by fasidOnGit** [comment]
+1

**Comment by martynasma** [comment]
I'm afraid we won't be implementing this feature. Sorry. Closing.
