### ISSUE TITLE
am4core.color class in configBase

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#591]
Hey I would like to know how am4core.color instance looks in terms of JSON Based Config?

**Comment by martynasma** [comment]
Depends of what you need to do.

If you want to provide a list of colors it looks like this:

```
{
  // ...
  colors: {
    list: ["#a00", "#b00", "#c00", "#d00", "#e00"]
  }
}
```

**Comment by martynasma** [comment]
You're welcome.

I'm closing this, but please feel free to post any follow up questions you may have.
