### ISSUE TITLE
Question: Dragging outside of the chart container

### ISSUE THREAD

**Issue by AndrewK15** [amcharts/amcharts4#593]
Hi Guys, 

is it possible to drag elements (for example, pie slices) outside of the chart container? Goal is to drop pie slice onto a non-amchart managed container (like regular div somewhere else on the page) and receive an event with data from this slice.

Is it possible? If no, will it ever be? Or maybe I need to implement it myself using regular html5 drag&drop?

**Comment by martynasma** [comment]
Here's the trick:

```
chart.maskRectangle = undefined;
```

This will allow dragging elements outside.

I guess you can combine with some code to detect hovering target div to implement what you need.

Hope this helps.

**Comment by AndrewK15** [comment]
OK, nice to see that!
But maybe I will go into another direction -> is there a way to receive dragstart and dragstop events, but do not actually move the chart elements? Maybe this way I can utilize the html5 drag&drop by creating a custom element? 

Is there a doc piece I can check? Maybe I'm missing some essential info that is already available?

**Comment by martynasma** [comment]
There's no drag events if element is not draggable, I'm afraid.

You might utilize "down", "up", and "track" events though.

**Comment by AndrewK15** [comment]
Thank you, this is what I'm going to do then!

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
