### ISSUE TITLE
Question: Why margin in chart is ignored

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#594]
Hey I am initialized the chart using a JSON config file. apparently when I am adding margin properties to the chart config, **the chart ignore my margins**, does we have an attribute of automargin:false like amcharts3?

This is my config:

export const derPlanChartConfig = {
  'id': 'der_plan',
  'xAxes': [{
    'id': 'date',
    'type': 'DateAxis',
    'skipEmptyPeriods': true,
    'baseInterval': {
      'timeUnit': 'minute'
    },
    'renderer': {
      'labels': {
        'fill': '#DADADA',
        'strokeOpacity': 1
      },
      'line': {
        'strokeOpacity': 1,
        'stroke': '#DADADA'
      },
      'grid': {
        'stroke': '#DADADA',
        'strokeOpacity': 1
      },
      'minGridDistance': 30
    }
  }],
  'yAxes': [
    {
      'type': 'ValueAxis',
      'renderer': {
        'labels': {
          'fill': 'white',
          'strokeOpacity': 1
        },
        'line': {
          'strokeOpacity': 1,
          'stroke': 'white'
        }
      }
    }
  ],
  'series': [
    {
      'type': 'ColumnSeries',
      'dataFields': {
        'dateX': 'date',
        'valueY': 'NB'
      },
      'strokeWidth': 5,
      'clustered': false,
      'columns': {
        'width': '100%',
        'tooltipText': 'Value: {valueY.value}'
      },
      'legendSettings': {
        'labelText': '{name}',
        'valueText': '[bold white]{valueY.value}[/bold]',
      },
      'name': 'NSB',
      'fill': '#24aafd',
      'stroke': '#24aafd',
    },
  ],
  'zoomOutButton': {
    'iconPosition': 'right',
    'itemContainers': {
      'paddingTop': 4,
      'paddingBottom': 4,
      'paddingLeft': 4,
      'paddingRight': 4
    }
  },
  'dateFormatter': {
    'dateFormat': 'yyyy-MM-dd hh:mm'
  },
  // Add data
  'data': [],
  // And, for a good measure, let's add a legend
  'legend': {
    'useDefaultMarker': true,
    'position': 'top',
    'labels': {
      'fill': 'white'
    },
    'markers': {
      'width': 10,
      'height': 10,
      'children': [{
        'cornerRadiusTopLeft': 12,
        'cornerRadiusTopRight': 12,
        'cornerRadiusBottomRight': 12,
        'cornerRadiusBottomLeft': 12,
        'strokeWidth': 0.5,
        'strokeOpacity': 1
      }]
    }
  },
  'cursor': {},
  'marginLeft': 70,
  'marginRight': 40,
  'marginBottom': 25,
  'marginTop': 10
};

**Comment by RobbiesCode** [comment]
Hi,

`marginTop` (and the others) are not v4 properties. I understand the confusion. You can use `paddingTop` (and the others) instead (this works in JSON too):

```
chart.paddingRight = 0;
chart.paddingLeft = 0;
chart.paddingTop = 0;
chart.paddingBottom = 0;
```

Here's an example of a simple XY-chart (column chart) where the padding has been reduced to 0 for all sides: https://codepen.io/team/amcharts/pen/10ae965e48b0ad7563d1dd3c56939a44?editors=0110.

Hope this helps!

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
