### ISSUE TITLE
Question: How to position Legend in top right side of chart

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#595]
Hey Apparently there are a lots of capabilities from amcharts3 which are missing from amcharts4 , for example position the legend can be in only 4 places:
1.Top: Starting from the middle.
2.Botton: Starting from the middle.
3.Left side
4.Right side
what if I want to place the legend in the top right side of the chart, how can I do it? 
Please provide an example of codepen.

**Comment by zeroin** [comment]
With V4 you can position legend in any way you want. To top-align the legend, just set: `legend.valign="top"`

https://codepen.io/team/amcharts/pen/vQaNVM?editors=1010

**Comment by BrkCoder** [comment]
Hey Maybe I didn't explain my self correctly, I need the legend on the top right side, but the graph need to be in the bottom and not in the left side.
Which mean that the legend should be on top but on the right side of the top and orientation is horizantal not vertical, and the chart should be on the bottom.
I would be happy if any one can come up with an example, because I didn't find any way to produce this situation.

**Comment by RobbiesCode** [comment]
Hi,

You could set your legend's `position` property to **"top"** and set its `align` and `contentAlign` properties to **"right"**.

Here's the updated demo: https://codepen.io/team/amcharts/pen/RqBzWy?editors=0010

Docs:
https://www.amcharts.com/docs/v4/reference/legend/#Properties
https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/

Hope this helps!

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
