### ISSUE TITLE
Value axis pre-zoom

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#596]
Having the pen bellow: 
https://codepen.io/aniov/pen/LXBGdP?editors=0010

Using zoomToValues on a ValueAxis doesn't seem to correctly position the min/max value.
Setting this: xAxis.zoomToValues(20 , 30) will zoom starting from 26 -> 34.
Another issue is that using animated will auto zoom-out.

ps: Open it in different browsers to see different results.
![image](https://user-images.githubusercontent.com/21243081/49032298-de40dc00-f1b4-11e8-8a98-b88ca20e7bec.png)

Thank you.

**Comment by martynasma** [comment]
I suggest you use chart's `ready` event to pre-zoom. It's the only way to ensure that every chart's child including axes and series are fully loaded and initialized.

```
chart.events.on("ready", () => {
  xAxis.zoomToValues(20 , 30, false, true);
});
```

Using the above seems to make zoom work fine.

**Comment by martynasma** [comment]
Hm, indeed. I'm chalking it up as bug. Will keep you posted.

**Comment by zeroin** [comment]
When chart is inited, line series is show and by doing so it animates it's values from 0 to real ones. THis animation causes the axis to zoom, as it pays attention to series values. So to solve this, you need to set series.showOnInit = false. This will prevent series from animation and the zoom will remain.

**Comment by aniov** [comment]
I've added 'showOnInit = false' to my series.
Can you please see what I'm doing wrong here, because I can't make it work. Thank you.

https://codepen.io/aniov/pen/WYLOLY?editors=0010

**Comment by martynasma** [comment]
We've just released an updated version, which might fix the issue with showOnInit not working.

That explains why it's working for you @RobbiesCode ;)
