### ISSUE TITLE
Height of the legend is not updated automatically when we change the font size of the legend.

### ISSUE THREAD

**Issue by ysreddy99** [amcharts/amcharts4#598]
Hello,

Height of the legend is not updated when we change the font size of the legend. I know you use update cycles for updating the chart, but is there a way to update the legend height instantly? . 

Please find the below code pen example. Click on the "Set font" button you will see height is more than what it supposed to be.

https://codepen.io/ysreddy/pen/XyPWvz?editors=1010

**Comment by martynasma** [comment]
Sorry, can't seem to reproduce it.

Before font size change:
![image](https://user-images.githubusercontent.com/1458520/49125497-fc97fc00-f2c8-11e8-8237-da482652b2a1.png)

After:
![image](https://user-images.githubusercontent.com/1458520/49125509-07eb2780-f2c9-11e8-86cc-0a7824db2d5c.png)

Looks good to me.

Or am I missing something?

Do you perhaps get it in some specific browser only?

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
