### ISSUE TITLE
Perfomances with multiple charts (Angular)

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#599]
Hey an issue regrading react app has been created and I want to inform that problems of performances also exist in angular app.
I am referring  to the original issue: https://github.com/amcharts/amcharts4/issues/525 
Here is my example of the code which run in my client:
https://stackblitz.com/edit/angular-mgrid-example.

**Comment by zeroin** [comment]
Just letting you know that we are working on this issue.

**Comment by BrkCoder** [comment]
thanks 👍

**Comment by zeroin** [comment]
I would also suggest to check the answer I wrote to this thread: https://github.com/amcharts/amcharts4/issues/604 also your original #525

**Comment by BrkCoder** [comment]
Hey zerion, I don't think that my issue is a redrawing cycles but rather the redraw it self is clanky and not smooth. Therefore I can't understand how your solution of #525 can help me:
am4core.system.isPaused = true; // pauses everything
am4core.system.isPaused = false; // resumes everything

It is looks to me that the drawn of the chart cause the following violations in the browser, and this is the reason for why the chart drawing is so heavy and not smooth.
![image](https://user-images.githubusercontent.com/5408870/49153498-8f16ba80-f31e-11e8-9d43-c60b1a388f62.png)

Again I remind you that the charts which in the example only used 58 points of data and 300 points total for all charts. It is very small amount and we aren't talking here about 10k points or 100k points or even 1 million points, we are talking  here about less than 500 points for the total charts.

**Comment by zeroin** [comment]
My idea of pausing the process was to allow all this framework to finish all the other jobs and only when they finished proceed to charts. This way the charts would render more quickly as the cpu won't be occupied with parallel processes. But as I said, we are working on making it much better, I expect to release an update today or tomorrow the latest. I will let you know when it is ready.

**Comment by BrkCoder** [comment]
thanks for your efforts 👍

**Comment by zeroin** [comment]
We released an update (4.0.3) and it should make this initial rendering a lot better.

**Comment by zeroin** [comment]
Just wanted to let you know that we released v 4.0.17, which should perform a lot better, especially for charts with a lot of data.
