### ISSUE TITLE
Chart legends that are disabled on initial rendering can never be made visible

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#60]
This is a weird one. This behavior I think just started with beta 28 (but it's possible it was in beta 27 too).

If you create a chart with a legend and the `legend.disabled` property gets set to `false` during initialization of the chart, setting the `legend.disabled` property back to `true` will never show the legend.

However, if disable the legend in an async event (such as setTimeout()) then it will work. I've put together this example that shows the behavior:

https://codepen.io/anon/pen/LrRBoM

Initially the legend will show. Click the "Toggle Legend" to see that the legend will hide/show each time you click the button.

Now change the `hideByDefault` variable at the top of the JavaScript to `false`. This will trigger the `chart.legend.disabled = true` logic. Now when you click the "Toggle Legend" button the legend never shows.

Finally, if you set the `useAsyncFix` variable to `true`, it will work properly. This is because the `disabled` property isn't set until the next tick.

This bug is breaking my responsive code, which I use to hide the show the legend based on it's current size (via the `maxsizechanged` event).

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.31](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.31).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by dswitzer** [comment]
Good work! It appears to be working correctly now.
