### ISSUE TITLE
Support for rotation of globe (Map with Orthographic projection)

### ISSUE THREAD

**Issue by adtype-com** [amcharts/amcharts4#602]
I was browsing the [following tutorial](https://www.amcharts.com/docs/v4/tutorials/map-with-orthographic-globe-projection/) and was wondering if there is any support for rotation of the globe when using an Orthographic projection by clicking and dragging the mouse on the globe. 

I see that you can control the delta longitude via a slider, but can we do the same directly on the map, instead of sliding the map in 2D?

Example from docs: https://codepen.io/team/amcharts/pen/QBZLbv

Thanks!

**Comment by martynasma** [comment]
Challenge accepted :)

There ya go:
https://codepen.io/team/amcharts/pen/vQzvEv

**Comment by adtype-com** [comment]
Wow this is great! Thank you so much :)

**Comment by adtype-com** [comment]
Sorry just as a comment, there is no deltaLatitude field available in order to perform the same rotation but vertically (via latitude), right?

**Comment by martynasma** [comment]
That is correct. Only `deltaLongitude` is available. Similar rotation for latitudes are orders of magnitude more complex than longitude, hence it not being available now. We might introduce it in the future, although I can't promise when or if that is going to happen. Sorry.
