### ISSUE TITLE
Barchart performance

### ISSUE THREAD

**Issue by AndrewK15** [amcharts/amcharts4#604]
Hi, we are using your charts in our Angular 7 app quite heavily, and for a large amount of data. However, we are facing performance problems. First example is this barchart - we actually use this one, and user has an option to choose an aggregation bucket size (minutes, hours, days etc.).

https://codepen.io/andrewk15/pen/aQaeWG

I agree that there are a lot of columns there, but rendering compared to simple d3 chart is very slow. I understand that amcharts are much more complex and heavy, but is there anything we can do to improve performance? Reducing data size is really not an option as there will be cases with a lot more data points in a chart, and with multiple charts visible at the same time.

Could someone confirm that this is a known thing? Are you guys working on it? Could you provide a guideline to avoid this kind of performance problems? Are we using the API in a wrong way? 

We would really love to go with amcharts 4 for our release!

**Comment by BrkCoder** [comment]
I have issues with line charts and bar charts also with only 58 points.
I am referring to this issue which has been ignored totally by amcharts team:
https://github.com/amcharts/amcharts4/issues/599

**Comment by zeroin** [comment]
We are working on improving performance of our charts. In this case I could suggest setting `minWidth` for valueAxis and `minHeight` for dateAxis or setting `axis.renderer.inside = true`. This will help to avoid one some possible redraws which happen because we have to measure real size the axes occupie. 

Another thing which is good for performance of ColumnSeries is setting `series.simplifiedProcessing = true`, in case you don't need sum, averages and things like that. More [simplified processing](https://www.amcharts.com/docs/v4/reference/columnseries/#simplifiedProcessing_property).

**Comment by BrkCoder** [comment]
Hey From what I see in the example here https://codepen.io/team/amcharts/pen/QJZbJV, you are using a loader to load the chart, can you explain how you make it possible to create a perloader for the chart on initialization?

**Comment by zeroin** [comment]
It's actually not a loader but a progress bar which is shown if parsing data takes more than `component.parsingStepDuration` time, which by default is 50ms. You can increase this time if you don't want to to be visible. As for using it while chart is initializing, then it is not possible at the moment, We really tried to do it, but the result wasn't nice. You can't really measure the real progress of initialization and usually it takes very short time so it just blinks as a distraction. I could recommend adding your custom loader like it is described here: https://www.amcharts.com/docs/v4/tutorials/custom-loading-indicator/

**Comment by zeroin** [comment]
By the way, I have an idea which would increase performance a lot - instead of ColumnSeries you could use StepLineSeries. With so many columns as you have, it will look practically the same but instead of a thousand+ objects you will have just one.

**Comment by zeroin** [comment]
We made quite a lot of improvements which mostly affect initial rendering of the charts in v 4.0.3, it should be much better than it was now. We will continue working on performance.

**Comment by zeroin** [comment]
Just wanted to let you know that we released v 4.0.17, which should perform a lot better, especially for charts with a lot of data.
