### ISSUE TITLE
Threshold based on ValueAxis and DateAxis- Feature Request

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#607]
Hey I want to simulated a threshold which have a single value(for example 730000) and it is between 2 points of time(for example:  "from": 1541055600 & "to": 1541149200).
From what I see AxisRanges(https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/)
is limited and can be only on xAixs or yAxis and have a single value.
How can I simulated this kind of threshold with the current tools which amcharts 4 provide me.
Should I used a LineSeries instead of AxisRanges?

**Comment by zeroin** [comment]
Yes, you have to create line series for this. Here is an example, it illustrates how to do that: https://www.amcharts.com/demos/trend-lines/

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
