### ISSUE TITLE
TreeMap Tooltip Docs

### ISSUE THREAD

**Issue by leralgarmuz** [amcharts/amcharts4#61]
I've been searching around the internet and mainly inside the docs, and I can't find anything related to customizing the Treemap Tooltip, so I can't show different data than the default value and name.

Thanks in advance.

**Comment by leralgarmuz** [comment]
I found a way to achieve this custom Tooltip, I'm not sure if this is the right way to do it, but it is working.

I'm leaving a sample code in case someone else is trying to achieve a custom tooltip.

`let level1 = chart.seriesTemplates.create("0");`
`let level1_column = level1.columns.template;`
`level1_column.tooltipHTML = '<table> <tr><td><h5 style="color: white"><b> {name} </b><small> ({value})</small></h5></td></tr> <tr><td>;{anotherValue}  | {anotherValue}% </td></tr> </table>';`

**Comment by martynasma** [comment]
Hi there,

Yes, this is precisely the way to go. To set custom tooltips you need to use series' `column.template`.

https://www.amcharts.com/docs/v4/concepts/list-templates/

Thanks for sharing your solution!
