### ISSUE TITLE
Stacked ColumnSeries bad render new data

### ISSUE THREAD

**Issue by Akihito759** [amcharts/amcharts4#612]
Hi guys, I have got a problem with 2 live series stacked on XYChart. The first data renders bad:
![image](https://user-images.githubusercontent.com/23390156/49219325-32290c00-f3d3-11e8-80b6-60a08608621e.png)
after adding new data the columnSeries repairs and looks good, but again the newest data render bad :/. 

I was trying adding new data by addData() or update manually with invalidateData() but the problem occurs always.

**Comment by zeroin** [comment]
Hi, 

Could you share the code of your chart, this would help us to find the problem more quickly.

Thanks!

**Comment by Akihito759** [comment]
I'm only testing basic functionality. I need to preset count of connected and disconnected services in real time from signalR. Here is my code :) 
```
this.zone.runOutsideAngular(() => {
        let chart = am4core.create('chartdiv', am4charts.XYChart);
        chart.colors.list = [am4core.color('#33cc33'), am4core.color('#ff3300')];
        chart.zoomOutButton.disabled = true;
        chart.padding(0, 0, 0, 0);
        // Add data

        let dateAxis = chart.xAxes.push(new am4charts.DateAxis());
        //dateAxis.maxWidth = 30;
        dateAxis.dateFormats.setKey('second','HH:mm:ss');
        let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
        //chart.dateFormatter.dateFormat = 'HH:mm:ss';
        let seriesConnected = chart.series.push(new am4charts.ColumnSeries());
        seriesConnected.stroke = am4core.color('#33cc33');
        seriesConnected.dataFields.valueY = 'connected';
        seriesConnected.dataFields.dateX = 'date';
        seriesConnected.stacked = true;
        let seriesDisconnected = chart.series.push(new am4charts.ColumnSeries());
        seriesDisconnected.stroke = am4core.color('#ff3300');
        seriesDisconnected.dataFields.valueY = 'disconnected';
        seriesDisconnected.dataFields.dateX = 'date';
        seriesDisconnected.stacked = true;

        chart.data = [];
        for (let i = 0; i < 30; i++) {
         chart.data.push({ date: new Date().setSeconds(0), connected: 0 });
         chart.data.push({ date: new Date().setSeconds(0), disconnected: 0 });
        }
        this.chart = chart;
      });
      let i = 0;
      setInterval(() => {
        console.log(this.chart.data);
        let dateNow = new Date();
        this.chart.data.shift();
        this.chart.data.shift();
        this.chart.data.push({
          date: dateNow,
          connected: ++i
        });
        this.chart.data.push( {
          date: dateNow,
          disconnected: -i
        });
        this.chart.invalidateData();
      }, 2000);
```

**Comment by zeroin** [comment]
This problems happens because of two data items pushed to the chart with the exactly the same date. 
So I would suggest to do this: 

`        this.chart.data.push({
          date: dateNow,
          connected: ++i,
          disconnected: -i
        });`

And the same thing in the initial data. 
Also, when adding data to the chart, I would recommend using `chart.addData(data, removeCount)` method, as this will be much more efficient, and you won't need to call `chart.invalidateData`.

**Comment by Akihito759** [comment]
Wow thank you for fast replay. I didn't know that we can do it in single data object :), there should be some information of this case in the guide on your website. Ok I will use `chart.addData(data, removeCount)` Thank you very much for fast help :)
