### ISSUE TITLE
Question - Disable Zoom for single chart(Sync Cursor on Multiple charts)

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#613]
Hey I work in a team which implemented sync cursor using the following code:
https://github.com/amcharts/amcharts4/blob/master/dist/ember/vendor/script/amcharts4/examples/javascript/syncing-cursors-and-zoom/index.js

I have multiple cursors on charts and I want to disable a zoom for specific chart which have a bug when zoom in and zoom out.
Can I do it?, is it contrary to sync cursor logic which zoom on all charts at once?

**Comment by RobbiesCode** [comment]
Hi,

The demo you mention includes a function `syncDateAxes` which zooms all charts on the page, following the chart where the zoom started (triggering the `selectionextremeschanged` event).

If you want to exclude one chart from syncing, you could simply add a `continue` statement when `i` equals the chart you want to exclude from syncing.

```

function syncDateAxes(syncWithAxis) {
  
  for (var i = 0; i < charts.length; i++) {
    
    // don't sync chart #3
    if(i == 2){
      continue;
    }
  
    // ...

  }

}
```

Here's a demo that does this: https://codepen.io/team/amcharts/pen/ff1e0096a7381b3e1507511b9619b755?editors=1010.

Be aware that this looks a little funny when the chart cursors are still synced, but the date axes are not aligned.

**Comment by BrkCoder** [comment]
thanks for the quick reply 👍

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
