### ISSUE TITLE
When changing the state in react the maps disappear

### ISSUE THREAD

**Issue by tjones0808** [amcharts/amcharts4#615]
Is there anyway to force a re-render? I am setting the state which does a show/hide on map divs to change which maps are shown. After the show hide, all maps are blanked out. I have my init on ComponentWillMount. Any experienced this yet??

**Comment by tjones0808** [comment]
haha, right after posting i figured this out. I needed to recreated the charts i needed in ComponentDidUpdate too

**Comment by martynasma** [comment]
Great. Glad you worked it out :)

I'm closing this, but please feel free to post any follow up questions you may have.
