### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by Hoet** [amcharts/amcharts4#618]
Hello,

I have been using amcharts a while now in a project. Wanted to update to a newer version and now I get the error message "webpackJsonp is not defined". We do not use webpack, we use gulp instead to build my js files among other things.

How do I get amcharts4 working without having to incorporate webpack in any way.

**Comment by Pauan** [comment]
@Hoet We provide a few different versions of AmCharts 4.

The [`<script>` tag version](https://www.amcharts.com/docs/v4/getting-started/using-javascript/) can be used standalone, without Webpack.

You shouldn't be getting any errors like that, could you please share your gulp script, so we can see if there's anything amiss?

**Comment by Hoet** [comment]
I have tried to use those three files, downloaded them and placed them in my amchart folder, copied the language that we use on the site and the new maps. 

``
/**
 * @license
 * Copyright (c) 2018 amCharts (Antanas Marcelionis, Martynas Majeris)
 *
 * This sofware is provided under multiple licenses. Please see below for
 * links to appropriate usage.
 *
 * Free amCharts linkware license. Details and conditions:
 * https://github.com/amcharts/amcharts4/blob/master/LICENSE
 *
 * One of the amCharts commercial licenses. Details and pricing:
 * https://www.amcharts.com/online-store/
 * https://www.amcharts.com/online-store/licenses-explained/
 *
 * If in doubt, contact amCharts at contact@amcharts.com
 *
 * PLEASE DO NOT REMOVE THIS COPYRIGHT NOTICE.
 * @hidden
 */
webpackJsonp([5],{148:fu``

This is where it breaks. Gulp can build my final .js without problemen, but once you try to create the map you get the before mentioned error message. Below id the gulp file that I use.

``
  var gulp        =require( 'gulp' );
  var sass        =require( 'gulp-sass' );
  var less        =require( 'gulp-less' );
  var cache       =require( 'gulp-cache' );
  var clone       =require( 'gulp-clone' );
  var merge       =require( 'merge-stream' );
  var concat      =require( 'gulp-concat' );
  var rename      =require( 'gulp-rename' );
  var uglify      =require( 'gulp-uglify' );
  var cssnano     =require( 'gulp-cssnano' );
  var plumber     =require( 'gulp-plumber' );
  var imagemin    =require( 'gulp-imagemin' );
  var svgSprite   =require( 'gulp-svg-sprite' );
  var sourcemaps  =require( 'gulp-sourcemaps' );
  var spritesmith =require( 'gulp.spritesmith' );

  // =====================
  // = Task: Clear cache =
  // =====================
  gulp.task( 'cache:clear', function( callback )
  {
    return cache.clearAll( callback )
  });

  // ===========================
  // = Task to optimize images =
  // ===========================
  gulp.task( 'optimize-images', function()
  {
    return gulp
      .src( 'public/images/*.+(png|jpg|svg)' )
      .pipe( cache( imagemin( )))
      .pipe( gulp.dest( 'public/images/' ))
  });

  // ==============
  // = Task: Sass =
  // ==============
  gulp.task( 'sass', function()
  {
    var source =gulp
      .src( 'assets/sass/frontend.scss' )
      .pipe( plumber( ))
      .pipe( sourcemaps.init( ))
      .pipe( sass( ));

    var stylesPipe1 =source
      .pipe( clone( ))
      .pipe( sourcemaps.write( '.' ))
      .pipe( gulp.dest( 'public/css/' ));

    var stylesPipe2 =source
      .pipe( clone( ))
      .pipe( rename({ suffix: '.min' }))
      .pipe( cssnano( ))
      .pipe( sourcemaps.write( '.' ))
      .pipe( gulp.dest( 'public/css/' ));

    return merge( stylesPipe1, stylesPipe2 );
  });

  // ==============
  // = Task: Less =
  // ==============
  gulp.task( 'less', ['png-sprites'], function()
  {
    var source =gulp
      .src( 'assets/less/themes/default/style.less' )
      .pipe( plumber( ))
      .pipe( sourcemaps.init( ))
      .pipe( less( ));

    var stylesPipe1 =source
      .pipe( clone( ))
      .pipe( sourcemaps.write( '.' ))
      .pipe( gulp.dest( 'public/css/' ));

    var stylesPipe2 =source
      .pipe( clone( ))
      .pipe( rename({ suffix: '.min' }))
      .pipe( cssnano({ zindex: false } ))
      .pipe( sourcemaps.write( '.' ))
      .pipe( gulp.dest( 'public/css/' ));

    return merge( stylesPipe1, stylesPipe2 );
  });

  // ====================
  // = Task: Javascript =
  // ====================
  gulp.task( 'javascript', function()
  {
    var source =gulp
      .src([
        'assets/javascript/*.js',
        'assets/javascript/bootstrap/**/*.js',
        'assets/javascript/libraries/**/*.js',
        'assets/javascript/amcharts/*.js',
        //'assets/javascript/amcharts/lang/*.js'
      ])
      .pipe( plumber( ))
      .pipe( concat( 'bestoftravel.js' ))
      .pipe( sourcemaps.init( ));

    var stylesPipe1 =source
      .pipe( clone( ))
      .pipe( sourcemaps.write( '.' ))
      .pipe( gulp.dest( 'public/javascript/' ));

    var stylesPipe2 =source
      .pipe( clone( ))
      .pipe( rename({ suffix: '.min' }))
      .pipe( uglify( ))
      .pipe( sourcemaps.write( '.' ))
      .pipe( gulp.dest( 'public/javascript/' ));

    return merge( stylesPipe1, stylesPipe2 );
  });

  // ====================
  // = Task: svg sprite =
  // ====================
  gulp.task( 'svg-sprites', function()
  {
    return gulp
      .src( 'assets/icons/**/*.svg' )
      .pipe( plumber( ))
      .pipe( svgSprite({
        mode: {
          symbol: {
            dest:   'sprites',
            sprite: 'sprites.svg',
            example: false,
            render: {
              css:  false,
              scss: false
            },
          }
        },
        svg: {
          xmlDeclaration: false,
          doctypeDeclaration: false
        }
      }))
      .pipe( gulp.dest( 'public/images/' ));
  });

  // ====================
  // = Task: png sprite =
  // ====================
  gulp.task( 'png-sprites', function()
  {
    var spriteData =gulp
      .src( 'assets/sprites/**/*.png' )
      .pipe( plumber( ))
      .pipe( spritesmith({
        imgName: 'sprites/sprites.png',
        cssName: 'sprites.less',
        imgPath: '/images/sprites/sprites.png'
      }));

    var imgStream =spriteData.img
      .pipe( gulp.dest( 'public/images/' ));

    var cssStream =spriteData.css
      .pipe( gulp.dest( 'assets/less/' ));

    return merge( imgStream, cssStream );
  });

  // ===============
  // = Task: Watch =
  // ===============
  gulp.task( 'watch', function()
  {
    //gulp.watch( 'assets/sass/**/*.scss', [ 'sass' ]);
    gulp.watch( 'assets/less/**/*.less', [ 'less' ]);
    gulp.watch( 'assets/icons/**/*.svg', [ 'svg-sprites' ]);
    gulp.watch( 'assets/images/**/*.png', [ 'png-sprites' ]);
    gulp.watch( 'assets/javascript/**/*.js', [ 'javascript' ]);
    gulp.watch( 'public/images/*.+(png|jpg|svg)', [ 'optimize-images' ]);
  });

  // =================
  // = Task: Default =
  // =================
  gulp.task( 'default', [ 'optimize-images', 'png-sprites', 'svg-sprites', 'less', 'javascript' ]);
``

**Comment by notacouch** [comment]
Thanks for sharing your task source.

Since you're not using the `<script>` tag versions literally, `core.js` still needs to load first:

In https://www.amcharts.com/lib/4/core.js, you'll find `webpackJsonp` is defined in global scope:

```javascript
window.webpackJsonp=function(i,o,a){ /* ... */ }
```

In this case, [globbing](https://gulpjs.com/docs/en/getting-started/explaining-globs) the amcharts directory will probably pull it in this order:

1. charts.js <-- webpackJsonp `undefined`
2. core.js <-- webpackJsonp defined here
3. maps.js

So you can either adjust your globbing to specify each file specifically, one by one, in order, so `core.js` comes first. Or rename `core.js` so it comes first alphabetically. I suggest the former so whenever there are updates you can just download them and replace them instead of having to rename core.js every time.

Let us know if that works for you.

**Comment by Hoet** [comment]
Hmm, I indeed use a *.js for amcharts, I'll change it so that I can supply a certain order and see if that does fix my issue. I'll be working on that project this weekend so I'l let you know this weekend.

Thanks for your time :)

**Comment by notacouch** [comment]
You're welcome! Yep, hopefully this weekend you'll find the order will do the trick.
