### ISSUE TITLE
Add custom component to axis tooltip

### ISSUE THREAD

**Issue by jakeleventhal** [amcharts/amcharts4#619]
There is no way to add a custom component to the axis tooltip. For example, in this pen https://codepen.io/team/amcharts/pen/LrPLwJ the tooltip text is changed via an adapter. This doesn't support adding in custom react components to the tooltip such as an image

**Comment by martynasma** [comment]
You're right. There's currently no way to use HTML on axis tooltips. We'll need to find a way to do so.

Will let you know when that happens. Sorry, no ETA.

Thanks!

**Comment by martynasma** [comment]
There's a way using an adapter:

```
categoryAxis.tooltip.label.html = "{category}";
categoryAxis.tooltip.label.adapter.add("html", function(text, target) {
  return ">>> <strong>" + text + "</strong> <<<";
});
```
