### ISSUE TITLE
JSON labelBullet template

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#623]
Hello,

Is there a way to set label rotation of a label bullet on Sankey chart ? (json config)

```javascript
// add labels
var labelBullet = chart.links.template.bullets.push(new am4charts.LabelBullet());
labelBullet.label.propertyFields.text = "labelText";
labelBullet.propertyFields.locationX = "labelLocation";
labelBullet.propertyFields.rotation = "labelRotation";
labelBullet.label.horizontalCenter = "left";
labelBullet.label.textAlign = "start";
labelBullet.label.dx = -50;
```

I tried:

```javascript
"links": {
	"colorMode"		: "gradient",
	"propertyFields": {
		"fill"			: "linkColor",
		"fillOpacity"	: "linkOpacity"
	},
	'labelBullet' : {
			propertyFields : {

			},
			rotation : -90,
			horizontalCenter : 'left',
			textAlign :"start",
			dx : -0
	}
}
```

**Comment by martynasma** [comment]
There are no such property as `labelBullet`. You need to push objects into `bullets` array:

```
"links": {
  "bullets": [{
    "type": "LabelBullet",
    "propetyFields": {
       "locationX": "labelLocation",
       "rotation": "labelRotation"
    },
    "label": {
      "horizontalCenter": "left",
      "textAlign": "start",
      "dx": -50,
      "propertyFields": {
        "text": "labelText"
      }
    }
  }]
}
```

**Comment by ptorrent** [comment]
I'm not able to make it works :/ 

I would like to rotate label.

https://codepen.io/ptorrent/pen/bQWNwr?editors=0010

**Comment by martynasma** [comment]
```
nodeTemplate.nameLabel.locationX = 0.5;
nodeTemplate.nameLabel.label.horizontalCenter = "middle";
nodeTemplate.nameLabel.label.verticalCenter  = "middle";
nodeTemplate.nameLabel.label.fill = am4core.color("#fff");
nodeTemplate.nameLabel.label.fontWeight = "bold";
nodeTemplate.nameLabel.rotation = -90;
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by NPC** [comment]
@martynasma JSON for .nodes prop still doesn't work as documented. Usually in JSON I skip the template sub-property, but in SankeyDiagram it seems to be required.

For example, this doesn't work:
`{ "nodes": { "width": 20 }, … }`

But this does:
`{ "nodes": { "template": { "width": 20 } }, … }`

**Comment by Eduardo-Julio** [comment]
As @NPC said, its not working with JSON

**Comment by inf0dr0id** [comment]
This is still the case and very annoying, I've lost a couple of hours figuring this out. It's also wrong in the tutorial "Handling long Sankey labels" (https://www.amcharts.com/docs/v4/tutorials/handling-long-sankey-labels/).

![Bildschirmfoto 2020-12-08 um 16 02 47](https://user-images.githubusercontent.com/24397146/101500556-ec628f00-396e-11eb-9d5e-50404264631a.png)
