### ISSUE TITLE
background 

### ISSUE THREAD

**Issue by rocos-david** [amcharts/amcharts4#624]

**Comment by rocos-david** [comment]
I can't seem to find a way to set the background color when the seriesRange is within a specific set of values.  For example I would like the background (from bottom of the graph to top of the graph) to highlight red when a value is over say 90%.  This graph is live updating so ideally I just set the seriesRange to be between 90 and 100% and this works automatically.  My seriesRange correctly can set the colour and fill for the line series part of the graph, but not the background.

**Comment by martynasma** [comment]
Do you mean you have `AxisRange` working correctly to color the line itself, but can't get it to also work for the fill of the series?

If that is the case, you might missing `fillOpacity` setting in the `AxisRange`. The thing is that range does not automatically inherit `fillOpacity` so you need to set it again. E.g.:

```
range.contents.stroke = am4core.color("#396478");
range.contents.fill = range.contents.stroke;
range.contents.fillOpacity = 1;
```

**Comment by rocos-david** [comment]
Hi, no, the fill and stroke on the actual line work fine using a seriesRange.  However, I'd like the background (probably the dateAxis) to be a full rectangle of color behind this.

This is what I can do with the seriesRange:
![image](https://user-images.githubusercontent.com/43590410/49362540-eadcab80-f743-11e8-94aa-f5c991fd80f0.png)

This is what I'd like it to look like:
![image](https://user-images.githubusercontent.com/43590410/49362597-0c3d9780-f744-11e8-8a35-628d71c94b90.png)

As the data is coming in live I ideally don't want to try have to draw the boxes or create a second series.

**Comment by martynasma** [comment]
Thanks for the clarification.

The only way  can think of how to achieve that is to add AxisRange on a horizontal DateAxis.

However, it would be quite complicated to calculate precise `date` and `endDate` values for it. But, technically, it should be possible to do the map if you're game.

**Comment by rocos-david** [comment]
Ok thanks, it's fine to do on static data but more of a pain on live data.  Thanks for confirming.
