### ISSUE TITLE
Question: amcharts 3 legend valueFunction equivalent in amcharts 4

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#626]
Hey I want to modify the legend according to my dataitems,
which adapter should I used for modifying the final legend, I need an adapter which acts like valueFunction in amcharts 3 where I can access the dataitems and return the final legend items.

any help is welcome.
Thanks in advance,
Barak.

**Comment by martynasma** [comment]
That would be `"text"` if you want to modify text before it is populated with data, or `"textOutput"` if you want to mod already populated and formatted text.

Put it on `chart.legend.valueLabels.template.adapter`, e.g.:

```
chart.legend.valueLabels.template.adapter.add("textOutput", function(text, target) {
  return "--- " + text + " ---";
});
```

**Comment by BrkCoder** [comment]
thanks 👍

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
