### ISSUE TITLE
Localised column names in export

### ISSUE THREAD

**Issue by maurycyg** [amcharts/amcharts4#628]
Is there a way to translate the column names for CSV and XLSX exports?

I've attempted to change the name via a series adapter but that did not work.

**Comment by martynasma** [comment]
You can just use [`dataFields`](https://www.amcharts.com/docs/v4/reference/export/#dataFields_property) for that.

E.g.:

```
chart.exporting.dataFields = {
  category: "My category",
  value: "My value"
};
```
