### ISSUE TITLE
DataSource support for POST requests

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts4#629]
```chart.dataSource.url = "/data/myData.php";```

Is there a way to attach data to this like a POST?  I am not seeing anything in the doc about sending data along with it.

In amcharts3 I was using ajax to achieve this like so : 

```
$.ajax({
    type: 'post',
    url: '/assets/process/charts-am.php',
    data: {'type' : 'Main'},
    dataType : 'json',
	success: initialLoad
});

//on success load it
function initialLoad(series)
{ 
   ………….. load the chart here with series containing my data
}
```

**Comment by martynasma** [comment]
As @notacouch said there's currently no way to make POST requests using DataSource.

That said, I can see how this could be useful.

We'll consider adding such option. Just not sure when/if that is going to happen.

Thanks for the suggestion!
