### ISSUE TITLE
Console.log(lineSeries) results in "Unable to load file" error message

### ISSUE THREAD

**Issue by RobbertBreij** [amcharts/amcharts4#63]
See Codepen: https://codepen.io/team/amcharts/pen/aKmpxa.

While trying to animate an object along a MultiGeoLine in a Codepen environment, I am console.logging lineSeries. This results in an error message "Cannot read property "length" of undefined"  which is shortly thereafter followed by "Unable to load file".

If you outcomment the console.log (line 48), the error message dissapears. Even after removing this console.log, I have no succes when trying to animate an object along a MultiGeoLine (it works alright with single MapLine that connects two images (https://codepen.io/team/amcharts/pen/qKaxYr?editors=0010)

**Comment by martynasma** [comment]
Looks like there a lot of issues with this including CORS. Eliminating those (putting plane.svg on an AWS server that allows CORS from codepen as well as moving stuff out of iframe) fixes those.

Another issue is that you are trying to call `positionToPoint()` on a raw data object, not an actual `MultiGeoLine` object, hence the error.

`series.data` holds raw data, not map objects. So, if you'd like to access automatically-created `MultiGeoLine` objects, you'd need to access `LineSeries.mapLines` list:

```
var line = lineSeries.mapLines.getIndex(0);
```

I updated the actual demo and it works now fine:
https://s.codepen.io/team/amcharts/debug/aKmpxa

Well, it still has functional problems, but it's something you can work on :)
