### ISSUE TITLE
Trimmed bubble chart

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#630]
Example:
https://codepen.io/dmsmaxim/pen/YRbNbK

Is it possible to show all bubbles in this chart without trimming them on edges of the plot area?
![image](https://user-images.githubusercontent.com/15041200/49472741-dc13f880-f818-11e8-9343-9729d30e4044.png)

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
