### ISSUE TITLE
Question: Custom Legend valign is ignored

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#634]
Hey I think that I found a bug in amcharts4. I want create a custom legend which only on my control,
I am creating the legend with legend constructor, I am trying to place the legend on the top right side of the chart container, I am using to place the legend using the following properties:

1. **align** -  Controls horizontal alignment of the element.
This is used by parent Container when layouting its children.

2. **valign** - Controls vertical alignment of the element.
This is used by parent Container when layouting its children.

I have created a stackblitz which demonstrate the problem:
https://stackblitz.com/edit/angular-e3wusx

Any Help will be appreciated !!
Thanks in advance,
Barak

**Comment by martynasma** [comment]
If you want to position the legend without restrictions, so that it does not influence chart layout, I suggest you move it to chart's `tooltipContainer`. It does not have layout, so `align`/`valign` settings will work as expected.

**Comment by BrkCoder** [comment]
Hey thanks for the quick answer, but it isn't the answer which have been looking for, 
if I move the legend into chart's tooltipContainer, then I get a legend over the chart himself.
I need the legend on top right row of the container and beneath this row of legend there is the chart.
Can I achieve this request with cutsom legend, any help is welcome!!

**Comment by BrkCoder** [comment]
> If you want to position the legend without restrictions, so that it does not influence chart layout, I suggest you move it to chart's `tooltipContainer`. It does not have layout, so `align`/`valign` settings will work as expected.

Hey thanks for the quick answer, but it isn't the answer which have been looking for,
if I move the legend into chart's tooltipContainer, then I get a legend over the chart himself.
I need the legend on top right row of the container and beneath this row of legend there is the chart.
Can I achieve this request with cutsom legend, any help is welcome!!

**Comment by BrkCoder** [comment]
> Sure. I thought that's what you needed.
> 
> If you need just a row of legend on top of the chart, you just need to set its `position` to `"top"`.
> 
> No need to do anything else, like setting `parent`, `align`, or `valign`:
> 
> ```
> const legend = new am4charts.Legend();
> this.chart.legend = legend;
> legend.position = "top";
> ```

Every things is good but when I take this aprroach, all my data items are not refelcted and got override by chart defaullts, so I got a different problem now :/
 legend.data = [{
        "name": "2016",
        "fill":"#72A6B2"
      }, {
        "name": "2017",
        "fill": "#667E93"
      }, {
        "name": "2018",
        "fill": "#488BB2"
      }];

**Comment by martynasma** [comment]
Are you sure? It works perfectly fine for me:

https://stackblitz.com/edit/angular-nane3q?file=src/app/app.component.ts

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
