### ISSUE TITLE
 Interference with datatables when buttons are used to export data

### ISSUE THREAD

**Issue by JhonFrederick** [amcharts/amcharts4#635]
On the same page I have a table (using datatables) and I have a graphic created with amchart 4, the problem occurs when I use any of the buttons to export data from the datatables, the files generated by the buttons appear with a text. View image.

I think this is generated by the zoom out / zoom in buttons and by the scrollbar. 

![captura de pantalla de 2018-12-05 15-09-48](https://user-images.githubusercontent.com/20525802/49541235-34daa400-f8a0-11e8-899c-cb17ef52ac06.png)

**Comment by xorspark** [comment]
Would it be possible to provide a fiddle or codepen that reproduces the problem?

**Comment by JhonFrederick** [comment]
I was trying to reproduce the problem and discovered that if I change the version of DataTable, the problem does not occur. The version of the data table where the problem occurred was 1.10.10 with  buttons for DataTable 1.1.0. 

In the most recent versions of DataTable, what I said did not happen. Anyway, I attached the JSFiddle to show what happened.

https://jsfiddle.net/9ko6ja1x/15/

**Comment by xorspark** [comment]
We also use pdfmake, so whatever they did in the older release likely conflicted with how things are set up on our end when our export functionality is also enabled, which is how it somehow included our stuff in your pdf button export. I'll have to defer to our devs on this one.

**Comment by martynasma** [comment]
We do use pdfmake, but it is a bundled isolated version in our application, which is loaded in our scope, and should not conflict even if some other version of pdfmake is used in the same app. So I don't think that's it.

Frankly, I don't think we can do anything to prevent datatables code from going and grabbing part of chart's SVG as part of the export. If some newer version of that lib fixes the issue, then I suggest you make the switch :)

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
