### ISSUE TITLE
Chart with gaps in data requires at least one data point without value?

### ISSUE THREAD

**Issue by davidliang2008** [amcharts/amcharts4#636]
There is a demo (https://www.amcharts.com/demos/chart-with-gaps-in-data/) that shows how you can make the chart display a gap by setting `connect=false` on the series.

But the post didn't emphasis that you **have to** have at least one data point with the x value but no y value at the beginning of the gap in order for the chart to display a gap:

### Case 1: gap between 1966 and 1971
You would have to have a data point for year 1967 without y value
```javascript
...
, {
    "year": "1965",
    "value": -0.217
}, {
    "year": "1966",
    "value": -0.147
}, {
    "year": "1967"
}, {
    "year": "1971",
    "value": -0.19
},
...
```

### Case 2: gap between 1983 and 1989
You would have to have a data point for year 1984 without y value
```
...
, {
    "year": "1983",
    "value": 0.177
}, {
    "year": "1984"
}, {
    "year": "1989",
    "value": 0.104
}, {
    "year": "1990",
    "value": 0.255
},
...
```

Failing to provide a data point like those 2 cases will not have the chart display the gap. 
**Demo:** http://jsfiddle.net/davidliang2008/aq9Laaew/286248/

I wonder if it's possible to display the gap without providing those data points with empty y values?

**Comment by piernik** [comment]
I think I have the same issue: https://codepen.io/piernik/pen/vQoGzJ?editors=0010#0

**Comment by martynasma** [comment]
Refer to `autoGapCount`:
https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Gaps_over_missing_data_points
