### ISSUE TITLE
Question: Draw custom polygon on map chart

### ISSUE THREAD

**Issue by violeng** [amcharts/amcharts4#638]
Hi
Is there anyway or document to draw custom polygon on map like this google map example https://developers.google.com/maps/documentation/javascript/examples/polygon-simple?

Thanks for your support.

**Comment by martynasma** [comment]
Sure:
https://codepen.io/team/amcharts/pen/dQBLJx/

Let me know if you have any questions, how it's implemented.

**Comment by violeng** [comment]
@martynasma It works great and it is am looking for. Thank you for your support.
