### ISSUE TITLE
Bullet Adapter Problem

### ISSUE THREAD

**Issue by pouretrebelle** [amcharts/amcharts4#641]
Hello, I'm trying to make sparklines that show a bullet only at the start and end of each series, but having really inconsistent results:

![image](https://user-images.githubusercontent.com/1901935/49598883-84d86a00-f977-11e8-9642-466cbf57dfb2.png)

This is the code I'm using:

```js
    let bullet = series.bullets.push(new am4charts.CircleBullet())
    const dataLength = data.length
    bullet.circle.adapter.add('disabled', (current, target) => {
      if (!target.dataItem) return current
      const index = target.dataItem.index
      return index !== 0 && index !== dataLength - 1 // only start and end
    })
```

I've tried adding a priority to the adapter but no dice. [Made a reduced test case](https://codepen.io/pouretrebelle/pen/MzNoPj?editors=0010) which is working as expected.

When I wrote the code a couple of weeks ago I had the adapter on `bullet` instead of `bullet.circle` and it worked perfectly, but has stopped working since (I may have updated the package version in the meantime but not sure what from).

Any advice?

**Comment by martynasma** [comment]
The code looks good to me. It's hard to say what's going on without seeing an actual chart that does not work as expected.

There's one thing I could suggest changing:

```
if (!target.dataItem) return current;
```

Change this to:

```
if (!target.dataItem) return true;
```

Let me know if this maybe helped.

**Comment by pouretrebelle** [comment]
That improves it a bit but it's still not right

![image](https://user-images.githubusercontent.com/1901935/49643430-98361480-fa0d-11e8-9bf9-91b72cf7c470.png)

I'll try and put together a cp showing the problem later today

**Comment by martynasma** [comment]
That would be great. I'm sure we can work it out if there was a sure way to reproduce it.

**Comment by martynasma** [comment]
Thanks!

Looks like using `disabled` adapter is not reliable. It is used in some fuzzy logic, sometimes before the data is fully ready, hence it acting unpredictably.

Using strictly visual properties, like `fillOpacity` is much more reliable.

I found this to work 100%:

```
  bullet.circle.adapter.add('fillOpacity', (current, target) => {
    if (!target.dataItem) return 0;
    const index = target.dataItem.index
    return index !== 0 && index !== dataLength - 1 ? 0 : 1; // only start and end
  })
```

**Comment by pouretrebelle** [comment]
:+1:
