### ISSUE TITLE
Multi layered ChordDiagram

### ISSUE THREAD

**Issue by hkmoon** [amcharts/amcharts4#644]
Hi all,

It would be really nice to have multi layer support for ChordDiagram.
However, I am not sue this feature already exists or not.

For example, 
```
chart.data = [
    { from: "A", to: "D", group: "ABC", value: 10 },
    { from: "B", to: "D", group: "ABC", value: 8 },
    { from: "B", to: "E", group: "ABC", value: 4 },
    { from: "B", to: "C", group: "ABC", value: 2 },
    { from: "C", to: "E", group: "ABC", value: 14 },
    { from: "E", to: "D", group: "DEF", value: 8 },
    { from: "C", to: "A", group: "ABC", value: 4 },
    { from: "F", to: "A", group: "DEF", value: 7 },
    { from: "D", to: "B", group: "DEF", value: 1 }
];
```
Then, we can see the grouping information of "A", "B", "C" and "D", "E", "F" easily and the group proportions.

Could you let me know how I can make this if it is easily done in code level?

Thank you so much!

(reference: https://medium.com/@Marianattestad/a-treatise-on-making-circos-plots-from-genomic-data-7ff496849e0)

**Comment by martynasma** [comment]
Hm, there's currently no built-in "grouping" feature in Chord Diagram.

However, this sounds like and interesting feature, we'd like to explore.

I took a look at the link. There seems to be a lot of very complex examples, so not sure how this should look.

Did you mean something like this?

![image](https://user-images.githubusercontent.com/1458520/49646534-02f44980-fa28-11e8-875f-4ea7d0150717.png)

**Comment by hkmoon** [comment]
Wow! Yes! 
Could you let me know how to make the brown layer for Test 1,2,3?

**Comment by hkmoon** [comment]
There is one more thing to ask along with the groups.
Is there way to show the legends box for the colors?
```
{"#yellow": "group1", "#red": "group2", "#blue": "group3"}
```

**Comment by martynasma** [comment]
Ha, not so fast. It's just an image I got off the internet to confirm I understand what's needed. Not live chart.

Let me discuss this with the team and get back to you.

As for the legend, I suppose the only way is to do a custom legend:

https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items

**Comment by hkmoon** [comment]
I thought you had already done it by adding a layer in live coding.

Thank you for considering my feature request, and the information of custom legend. AmCharts documentation has high readability and nice structure to follow. It is awesome.

I am looking forward to seeing more wonderful features even though AmCharts 4 is really amazing now as a big fan of AmCharts.

**Comment by martynasma** [comment]
Unfortunately, we won't be able to implement this, I'm afraid. Sorry.

**Comment by hkmoon** [comment]
@martynasma No problem. Maybe it will be done later based on your priority. I like Chord diagram with animated bullets. ;) Thanks a lot for your efforts!
