### ISSUE TITLE
Cannot set absolute height on SankeyLink and SankeyNode

### ISSUE THREAD

**Issue by Taova** [amcharts/amcharts4#646]
Hi!
I am trying to make my Sankey diagram look the same regardless of the values being passed to it, but I can't get absolute height to work. While in [documentation](https://www.amcharts.com/docs/v4/reference/sankeylink/#height_property) it's said that "the height can either be absolute, set in numer pixels", setting `chart.nodes.template.height ` or `chart.links.template.height ` doesn't seem to have any effect.
Here's my codepen: https://codepen.io/anon/pen/XorNxL?editors=1111
I'd appreciate any help!

**Comment by martynasma** [comment]
There's currently no way to set fixed height/width of the `SankeyNode` or `SankeyLink`. While the properties are there (inherited from `Sprite`), they are being overwritten by the Sankey chart.

There's an already issue for that here: #120

I'm going to mark this one as duplicate. Make sure you subscribe to updates on #120 just so you're updated about progress.

**Comment by Taova** [comment]
@martynasma Thank you for your answer
