### ISSUE TITLE
Map id field

### ISSUE THREAD

**Issue by piernik** [amcharts/amcharts4#656]
Suppose I have map data like this:
```
data = [
    {id2: 'AF', value2: 60.524},
    {id2: 'AL', value2: 77.185},
]
```
I know how to change `value` field: `polygonSeries.dataFields.value = 'value2;`
But how to change `id` field? `polygonSeries.dataFields.polygon = 'id2';` is not working for me.

**Comment by piernik** [comment]
No problem. I can adapt data source.

**Comment by martynasma** [comment]
I'm going to re-open this, as a reference to dev team. Hope that's OK.
