### ISSUE TITLE
AmCharts 4 handling null data

### ISSUE THREAD

**Issue by prabhukhanna** [amcharts/amcharts4#670]
I am working on AmCharts4 where I load data dynamically. Sometimes, there may be null data sent from the response. I need to handle null data in AmCharts4. [ In this link I see the example for Amcharts3 handling null data](https://www.amcharts.com/docs/v3/tutorials/gracefully-handle-charts-data/). How should I handle null data in AmCharts4 ? ?

**Comment by notacouch** [comment]
What do you mean by null data? There's no data at all? An empty array? An empty item within the array? Or a missing or null field within an item? What are you looking to do when you get null data from the response?

Can you provide an example?

What you can do is add an [event listener](https://www.amcharts.com/docs/v4/concepts/event-listeners/) for when the data has loaded. Within the event handler, process the data, determine if it's "null", and make the changes you'd like. More commonly used is the `datavalidated` event, but in this case perhaps [`beforedatavalidated`](https://www.amcharts.com/docs/v4/reference/xychart/#beforedatavalidated_event) is more apt. E.g.

```javascript
chart.events.on("beforedatavalidated", function() {
  // check/manipulate data here
  // do things...
});
```

**Comment by prabhukhanna** [comment]
@notacouch The null data referring to passing an empty array to chart data.
Like **chart.data = [ ];**

**Comment by martynasma** [comment]
Building on @notacouch solution, here's what I came up with:

https://codepen.io/team/amcharts/pen/zyvQjd?editors=0010

I just used `beforevalidated` event because `beforedatavalidated` does not kick in if data is empty.

Hope you find it useful.

**Comment by prabhukhanna** [comment]
@martynasma It worked !! Thanks a ton.

**Comment by notacouch** [comment]
@prabhukhanna 

PieChart version of Martynas' demo:
https://codepen.io/team/amcharts/pen/88d11b5385a2669319c1a0fcdaa1e199/
