### ISSUE TITLE
Performance Tip: Better to add data on Series or on Chart 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#68]
Hi there, 

great work on AmCharts 4. I am currently migrating from Amcharts 3 and I found really useful that I am able to add to a serries data since before I had to do several conversion to flatten them. 

However, I have the feeling that adding the data to the Serries is less performant than on Amcharts 3 that was on the graph. 

Any tips? 

I am working with dataSets of about 30-50 serries that have about 10.000 datasets (dateX)

**Comment by jimmykane** [comment]
For example I understand that if you set on a chart: 

data = [{
date: new Date(), 
key1: 1,
...
key30:

}]

Takes less "space" than on each series adding the date again

**Comment by martynasma** [comment]
Thanks!

We haven't actually done any performance profiling on series data versus one single dataset, but technically the latter (one data set) should be quicker, because you would need to scan the data only once.

We are also still working on performance, so it will only get better.

Meanwhile, if you could share your chart setup, that we can test, it would super helpful. There's so much of data setups we can think of, so real-life configs/data is useful.

**Comment by jimmykane** [comment]
@martynasma  understandable and thanks. 

Give me some time and I can show you a setup if you like to check for performance plus the datasets. 
Still working on the migration branch.

**Comment by martynasma** [comment]
Sounds good. Thanks!

**Comment by jimmykane** [comment]
@martynasma here is the repo https://github.com/jimmykane/quantified-self/tree/feature/amcharts-4
If you need only the code part related to AmCharts https://github.com/jimmykane/quantified-self/blob/2312be05bf0d82e3513b532976eb5ab5834abc60/src/app/components/cards/event/chart/event.card.chart.component.ts

If you run to any problems running it do a second npm install. For some reason, one dependency fails to install I ve seen from travis builds due to npm/git-repo not being a package. 

Anyways there are also the 2 issues I mentioned before. 
- The series when removed are not removed from the chart
- The date axis formating does not work
- The cursor does not work 

Strange....

**Comment by jimmykane** [comment]
@martynasma I am blocked to be honest. 

The performance by using a series to have the data is awefull. I cannot optimize this by any option. 

I will try tonight to use the chart for storing data, but I am afraid that AMC4 performance is compromised regarding big data .

**Comment by martynasma** [comment]
I hear you.

Well, this is a pre-release software after all. We are still working on it, including improving performance.

Your input is very useful and valuable. We'll get there, eventually.

**Comment by jimmykane** [comment]
Just tried the chart data vs series data. 
Actually, most of the bugs I have posted here are solved and the performance difference is tremendous. 

How can we proceed on this? 

Is it fine to give 2 separate commit hashes or 2 ready builds?

**Comment by jimmykane** [comment]
So no worries atm for the performance. My kinda bad for going for the series approach. 
Now with the chart it can be comparable. I will be perhaps posting here remarks and info.

**Comment by peluprvi** [comment]
Almost the same situation here, but I didn't try it out in a different way than using series.
Testing the amCharts4 to see if it's time to migrate it, since we are migrating to Vue.

To test it I'm loading two of the same component into a single page, with the chart script inside the component.

The data tested was a simple array of 12 int numbers, example: `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]`.

It took about 1 second or more to load the 2 charts.

<details>
<summary>The component code</summary>

```html
<template>
  <div
    ref="chartdiv"
    :style="{ height: chartHeight }"
  />
</template>

<script>
  import colors from 'vuetify/es5/util/colors'
  import * as am4core from '@amcharts/amcharts4/core'
  import * as am4charts from '@amcharts/amcharts4/charts'
  // import am4ThemesAnimated from '@amcharts/amcharts4/themes/animated'

  // am4core.useTheme(am4ThemesAnimated)

  export default {
    name: 'Chart',

    props: {
      height: {
        type: [Number, String],
        default: '100%'
      },
      data: {
        type: Array,
        default: function () {
          return []
        }
      }
    },

    computed: {
      chartHeight () {
        let height = Number(this.height)
        return Number.isNaN(height) ? this.height : height + 'px'
      }
    },

    mounted () {
      let chart = am4core.create(this.$refs.chartdiv, am4charts.XYChart)

      chart.paddingTop = 0
      chart.paddingRight = 0
      chart.paddingBottom = 0
      chart.paddingLeft = 0

      let max = 1
      chart.data = this.data.map((data, index) => {
        max = data > max ? data : max
        return {
          column: index,
          value: data
        }
      })

      let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis())
      categoryAxis.renderer.disabled = true
      categoryAxis.renderer.grid.template.location = 0
      categoryAxis.renderer.grid.template.strokeOpacity = 0
      categoryAxis.renderer.ticks.template.disabled = true
      categoryAxis.dataFields.category = 'column'

      let valueAxis = chart.yAxes.push(new am4charts.ValueAxis())
      valueAxis.renderer.disabled = true
      valueAxis.renderer.grid.template.location = 0
      valueAxis.renderer.grid.template.strokeOpacity = 0
      valueAxis.renderer.ticks.template.disabled = true
      valueAxis.tooltip.disabled = true
      valueAxis.min = 0
      valueAxis.max = max
      valueAxis.strictMinMax = true

      let series = chart.series.push(new am4charts.ColumnSeries())
      series.dataFields.categoryX = 'column'
      series.dataFields.valueY = 'value'
      series.stroke = am4core.color(colors.blueGrey.base)
      series.fill = am4core.color(colors.blueGrey.base)
    },

    beforeDestroy () {
      // TODO: update when close https://github.com/amcharts/amcharts4/issues/97#issuecomment-399499287
      // this.chart && this.chart.dispose()
    }
  }
</script>

```

</details>

<details>
<summary>Profiling results</summary>

![image](https://user-images.githubusercontent.com/1561360/41794199-fac3e602-7634-11e8-9d56-157d056e67ac.png)

</details>

**Comment by peluprvi** [comment]
I'm trying to detach this issue from any other.
Using `console.time` and `console.timeEnd` I got this results:

```
// first chart
create chart: 87.8349609375ms
create chart data: 0.339111328125ms
create chart categories: 31.109130859375ms
create chart axis: 19.886962890625ms
create chart series: 20.382080078125ms
total chart time: 164.93017578125ms

// second chart
create chart: 40.808837890625ms
create chart data: 0.0849609375ms
create chart categories: 16.055908203125ms
create chart axis: 16.632080078125ms
create chart series: 14.862060546875ms
total chart time: 92.56494140625ms

// total time
total time: 257.4951171875ms
```

**Comment by jimmykane** [comment]
Try to disable the antimation by not loading the animation theme. 

One more point into this: 

Every time I destroy a chart and recreate it chrome complains about memory leak in the developer console and pauses the execution. 

The third time strangely it works like the first.

**Comment by peluprvi** [comment]
@jimmykane Thanks for you help!

You can see in my https://github.com/amcharts/amcharts4/issues/68#issuecomment-399553304 code that I'm not loading the animation. But in my case there is an issue on Vue that I commented in https://github.com/amcharts/amcharts4/issues/82

I'm also having trouble with destroy/dispose a chart that I reported in https://github.com/amcharts/amcharts4/issues/97
