### ISSUE TITLE
XY chart lines should populate missing values with 0

### ISSUE THREAD

**Issue by jakeleventhal** [amcharts/amcharts4#683]
When you have an xy chart with a line series that has missing values, it should auto-populate the missing values with 0. For example, in the attached image, the line should dip to Y=0 and have a bullet at each date, indicating that there are no values there.
<img width="1093" alt="screen shot 2018-12-13 at 12 36 30 pm" src="https://user-images.githubusercontent.com/15133828/49956785-08dca580-fed4-11e8-8291-34d04325ecbc.png">

**Comment by martynasma** [comment]
I disagree. A zero is as number as, say, ten. It's not a "missing value" it's a zero value. From the dataviz standpoint, it would be completely inappropriate to treat absence of value as zero value.

That said, there are a number of way to achieve what you need.

1) Include actual zeros into your source data.

2) Pre-process your data to add zero values to data before it is used. An "beforedatavalidated" event is perfect for that. E.g.:

```
chart.events.on("beforedatavalidated", function(ev) {
  // Modify whatever is in the ev.target.data
  // ...
});
```

I hope you find it useful.

**Comment by jakeleventhal** [comment]
That's perfect, thanks!
