### ISSUE TITLE
Dragging popup quickly causes tooltip flashing

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#687]
https://codepen.io/anon/pen/maejJb

Drag the popup across the chart extremely quickly and tooltips will show for a brief moment [until the popup catches up to the cursor].

**Comment by martynasma** [comment]
Thanks. We'll try to figure out how to solve this. Just can't provide an ETA. Doesn't seem all that critical :)

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
