### ISSUE TITLE
Hiding a series does not work

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#688]
Hi 

According to the documentation: https://www.amcharts.com/docs/v4/concepts/series/#Pre_hiding_series

`series.hidden = true;`

But even in the example in the documentation this is not correct (it's using visible instead of hidden) but I think it does not work

**Comment by martynasma** [comment]
Oops, sorry. Thanks for the heads up.

Fixed the live example. Should work fine now.

`series.hidden = true` is indeed the right way to pre-hide a series.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by jimmykane** [comment]
Hidden = true does not work

**Comment by jimmykane** [comment]
@martynasma  the problem here is that the property series.hidden = true will not work. 
Visible = true works buts does another thing

**Comment by jimmykane** [comment]
Does this need AmCharts update to a next non released version? 

I am using "@amcharts/amcharts4": "^4.0.8", and for my example, it does not work. 

I have just deployed an example with a debugger breakpoint at: https://quantified-self-io.appspot.com/eventDetails?eventID=bquwPT13t97DO3uVZvgu&tabIndex=2 

You can open the site (it's the staging endpoint for Amcharts 4 migration), open your console and observe that I am using hidden = true for the series I create but the series are not hidden. I have added a breakpoint just exactly before the series is added to the chart

Notice the Chart is drawn iside a tab.

**Comment by martynasma** [comment]
No it does not need an unreleased version. It was implemented quite a while ago. 4.0.8 should be fine.

I'm not sure why those series do not come pre-hidden in your app.

Is there any chance you could provide a standalone runnable demo on codesandbox.io or something?

**Comment by jimmykane** [comment]
One thing that might help is that the series are added asynchronously.

**Comment by jimmykane** [comment]
Its an observable that processes in reatime results, creates series and updates them .

**Comment by martynasma** [comment]
Yeah that might be the issue. If series are added / set as hidden **after** the chart/legend has initialized, they might not render as hidden.

Can you try to call `hide()` instead of setting `hidden`?

**Comment by jimmykane** [comment]
Yup @martynasma `hide()` fixes that🎉

**Comment by jimmykane** [comment]
Perhaps document that somewhere since more and more people are starting to use Firebase, AngularFire and in general async/RxJS
