### ISSUE TITLE
Error Cannot read property 'modal' of undefined

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#69]
```
ERROR TypeError: Cannot read property 'modal' of undefined
    at LineSeries.push../node_modules/@amcharts/amcharts4/.internal/charts/series/Series.js.Series.raiseCriticalError (Series.js:865)
``` 
Portion of the above file: 

```
 // this fails for some browsers. :(
    if (originalConsoleLevel) {
      // IE9 doesn't allow calling apply on console functions directly
      // See: https://stackoverflow.com/questions/5472938/does-ie9-support-console-log-and-is-it-a-real-function#answer-5473193
      Function.prototype.apply.call(originalConsoleLevel, originalConsole, args);
    }
```

`Version 66.0.3359.181 (Official Build) (64-bit) Chrome`

**Comment by jimmykane** [comment]
I am using Raven for logging

**Comment by martynasma** [comment]
Hi there,

Would you be able to share chart code that ends up with the above error?

**Comment by jimmykane** [comment]
IT was Raven from the Angular app. So If I enable the Raven(Sentry) error handler the above crashes.

**Comment by martynasma** [comment]
Um, I must admit I'm not quite sure what you mean, or what Raven is.

This error does not look like it's coming from amCharts, though.

Does the very same chart config work when you use it without Raven?

**Comment by jimmykane** [comment]
Yes it works without raven

**Comment by martynasma** [comment]
Rehashing this. Is there any way to set up a simple working demo with Raven or some other to demonstrate the issue, without me requiring to learn this technology? :)
