### ISSUE TITLE
Weird behaviour when Chart has dynamic addition of series tabs and big datasets

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#690]
Hi, 

I have a very strange case. 

I am displaying the Chart in a tab. 

When the chart is created the tab can be hidden. So the chart can be created without being visible. 

The chart is first created and asynchronously serries are added.  

When the chart is not visible (another tab is open) the redering looks fine when displaying the tab. 

However if you land on the page with the chart visible (landing tab is the chart tab) the series are not correctly aligned as of date, and the chart becomes 100% unresponsive in labels etc. 

This happens only with big datasets. 

Example video: https://drive.google.com/file/d/1YVbHTRcL8DWMSe1h7K08ajyczycqJaQw/view

**Comment by jimmykane** [comment]
You can test the same video here: https://quantified-self-io.appspot.com/eventDetails?eventID=rGXxeYvUZ4adDNqLUosd&tabIndex=2

**Comment by jimmykane** [comment]
It looks like the dates of the series are not parsed or the operation crashes and eventually stops. 

The observation is that the dates of the serries are not correct on the chart, as of all are starting from X[0]. 

then as you can see the chart becomes completely unresponsive and there is a CPU spike till the chart is destroyed.

**Comment by jimmykane** [comment]
I narrowed this down. 

this has todo with the size or resizing on the X axis. 

If I resize the chart the line series displays as it should. 

See this video https://drive.google.com/file/d/15lI8MqOWSY3TLjLzacb4rBDZW1FMv7tT/view

**Comment by jimmykane** [comment]
So this has something todo with dates and resizing or so. How can I help with this?

**Comment by jimmykane** [comment]
@martynasma  can this be due to the order of the series? 
Each series that is added, has it's own data. Those data have date category axis. 
Each series is added to the chart independently of the dates that it's data holds.

**Comment by martynasma** [comment]
Hey there, sorry for not being able to check this out earlier.

I'm not seeing any charts (or tabs) on the live link, so I'm going to go in blind.

I'm attributing issue to the fact that chart might be initializing in a hidden container. When that is the case, the chart can't figure out its dimensions, and it might result in such visual anomalies. Especially if unihiding of the chart container happens during chart initialization process.

I suggest the following course of action:

1) Update to the latest available version. (we've made some changes related to this issue)
2) Call `chart.deepInvalidate()` whenever its tab is unhidden.

Let's see if that helps. Then we can take it from there.

**Comment by jimmykane** [comment]
@martynasma  great, and sorry but the link was now invalid due to code push. 

I will come back to this. Indeed that looks like it perhaps. 

I finally converting my data to an easy format for "pushing" them to the charts and as soon as I am done I ll check how this behaves again. 

I am also suspecting that it has todo with series data, eg when the series have the data payload and not the chart. 

Btw great job guys. Coming back to the new version after about 6 months it's great. 

My task is ti migrate till next month 100% to the new charts so, I love to support with issues and discussions about performance (most of my performance issues are solved btw) 


Ah 

And merry XMAS (if that is the case) and take some rest! You are by far worth it!

**Comment by martynasma** [comment]
Sounds good. Thanks! :)

**Comment by jimmykane** [comment]
This is strange. 
I create a series before the chart is initialized as : 

```
 series = new am4charts.LineSeries();
```


and then I get an error: 

```
console.js:35 ERROR TypeError: Cannot read property 'modal' of undefined
    at LineSeries.push../node_modules/@amcharts/amcharts4/.internal/charts/series/Series.js.Series.raiseCriticalError (Series.js:892)
    at System.push../node_modules/@amcharts/amcharts4/.internal/core/System.js.System.update (System.js:133)
    at System.js:346
    at wrapped (raven.js:376)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:16147)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:496)
    at ZoneTask.invoke (zone.js:485)
    at timer (zone.js:2054)
```


Does this mean that when creating a series the chart has to be there and the series ID has to be unique (not creating the same id series? ) 

I am lost here.

**Comment by jimmykane** [comment]
If I am correct in my assumption this makes it very difficult using angular to integrate Am4Charts. 
I ll explain why. 

The chart needs to be initialized on `ngAfterViewInit`. 

However the `ngAfterViewInit` is called after the data comes in that `ngOnChanges` 

So what is a solution here? 

Since we cannot create a series when data comes in via `new am4charts.LineSeries()` (since that errors) and the chart will need to get initialized later .... Hmmmm

**Comment by jimmykane** [comment]
One more, the visibility is not the problem here. 
I am experiencing very incosistent results @martynasma . 

Remember the hidden on series etc? 

So if adding serries on a chart async: 

- Stroke does not work
- Legend values formating does not work
- Legend name formating to bold only works after resize 
- Data on the chart are not correctly placed on the AXIS . 

Those all happen even with deepinvalidate etc

**Comment by jimmykane** [comment]
Ok latest version (today release) fixed most of the above hmmm

**Comment by jimmykane** [comment]
I ll close this as resolved. Cannot reproduce with 4.0.11 

What changed @martynasma ? Or is this luck?

**Comment by jimmykane** [comment]
yup
