### ISSUE TITLE
Wrong Zoom and animation on iOS for line chart

### ISSUE THREAD

**Issue by ursmeier-mercatus** [amcharts/amcharts4#698]
"@amcharts/amcharts4": "^4.0.6" with Angular 7

Hiding and showing data series on line chart show some "uncontrolled" zoom in on iOS Safari.

![amchart-ios-animation](https://user-images.githubusercontent.com/22747183/50046394-ebaa0180-00a2-11e9-8814-c3bdad131e16.gif)
Works on Mac and Windows and Android Chrome.

Also the scroll bar overlaps left and right on iOS (not on other devices)
![img_1411](https://user-images.githubusercontent.com/22747183/50046437-9a4e4200-00a3-11e9-85f0-3ac87f3605ec.jpg)

Can this be changed with a chart setting? Or is it a bug?
Thanks for any hint.

**Comment by ursmeier-mercatus** [comment]
Thank you very much.
My client is impressed by the graphics :-) and will also license it.

**Comment by dmarchuk** [comment]
Hi @martynasma, any updates on fixing this issue? Maybe you have found some workaround? Thanks!
