### ISSUE TITLE
Wrong cursor detection on the stacked linear diagram

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#699]
Example:
https://codepen.io/dmsmaxim/pen/zyqMBd?editors=1010
In some areas cursor position detection is wrong.
![image](https://user-images.githubusercontent.com/15041200/50047382-7cd9a200-00bc-11e9-84d6-dcfc522d57f8.png)

When you hover this area, `series3.events.on('over', () => console.log(series3.name));` triggers, what is not correct

**Comment by martynasma** [comment]
Looks like related on how stack elements are constructed. There are additional transparent elements present, that obstruct hovers. We'll see if we can rid of them.

![image](https://user-images.githubusercontent.com/1458520/50050800-18dfc980-010e-11e9-8cb1-cecc026f2fbf.png)

**Comment by dmsmaxim** [comment]
Looks like **4.3.6** fixed it
