### ISSUE TITLE
How to disable a Series? 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#70]
Hi, 

how can I disable a series upon creation? 

I tried the disabled element but then when I click on the legend label instead of enabling it, it just grays out the label. 

I tried to .hide() but then the chart would crash. 

Sorry for opening a lot of issues lately but maybe I can contribute.

**Comment by jimmykane** [comment]
What I want to do here , is to create a chart with multiple serries but only show one at start (the user can toggle the rest later) so it will not use so much processing power for the first view.

**Comment by martynasma** [comment]
Gotcha.

Hm, it turns out it's not possible right now. An oversight on our part.

We're going to implement this in a future version. It will function like this: if you set `visible = true` to a series, it will be hidden on load with Legend reflecting that change as well.

**Comment by jimmykane** [comment]
@martynasma  Perfect. No worries and no rush I know its beta

**Comment by martynasma** [comment]
Gah, I meant `visible = false`. Sorry.

**Comment by martynasma** [comment]
Implemented in [4.0.0-beta.37](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.37).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
Related documentation:
https://www.amcharts.com/docs/v4/concepts/series/#Pre_hiding_series

**Comment by jimmykane** [comment]
@martynasma  woop woop!
