### ISSUE TITLE
Funnel vs pyramid

### ISSUE THREAD

**Issue by piernik** [amcharts/amcharts4#703]
Here is funnel and pyramid and funnel based on the same data: https://codepen.io/piernik/pen/zyBRwx?&editable=true

Pyramid is in my opinion ok - every data slice has a value of its' own.
But funnel is a different. We have to provide accumulated value of all previous slices. But I want to provide value of that slice and amchart should accumulate on it's own - is it possible?

EDIT:
If You force Us to provide accumulative values so why in that chart: https://www.amcharts.com/demos/funnel-chart/
600 is 44% insead of 100% ??

**Comment by martynasma** [comment]
I'm not entirely sure what you mean by needing to accumulate values.

Each value in a FunnelSeries represents a slice. The bigger the value, the wider the slice.

All values affect width of its own slice, and has absolutely no relation with the next/previous slice.

Technically speaking, your data does not make a lot of sense on a FunnelSeries, because its meant to show value degradation with each step. But, I guess, it can show your values as well.

Pyramid chart is completely different. Each slice value in it is represented not by with but rather by area or height (depending on setting). So having variable-size values on Pyramid chart makes sense.

**Comment by piernik** [comment]
I'll try to explain:

Ok let's take funnel that represents stages of sales in CRM.

- leads - value of those sales (and only those) is 4000$
- offer sent - value of those is 1000$
- negotiations - value of those is 500$
- won - value of won is 5000$

Those are values of stages!

Funnel created with that data is here: https://codepen.io/piernik/pen/YdpQwx

Now let's take accumulative approach with the same data:

- leads - sum of those and every below is 10500$
- offer sent - sum  of those and below is 6500$
- negotiations - sum 5500$
- won - value of won is 5000$

Now funnel looks ok: https://codepen.io/piernik/pen/PXbjze

1. I have to calculate every step on my own
2. I need different data set for pyramid
3. Funnel chart points that `leads` are 38% and 10500$ but there is no 4000$ value of that stage.

I think it will be better to provide only value of a stage and amcharts will calculate accumulative values.

**Comment by martynasma** [comment]
What you say makes sense. However, it's a niche usage, which I don't think would warrant including this accumulation fuzzy logic into core functionality.

If re-using the data is important, I suggest implementing data pre-processor. E.g.:

```
chart.events.on("beforedatavalidated", function(ev) {
  var chart = ev.target;
  for(var i = 0; i < chart.data.length; i++) {
    chart.data[i].wartosc2 = chart.data[i].wartosc
    if (i > 0) {
      chart.data[i].wartosc2 += chart.data[i - 1].wartosc2;
    }
  }
});
```

This will automatically created accumulated values in `wartosc2` so you can bind your FunnelSeries to it.

**Comment by piernik** [comment]
If I can reopen.
I want to come back to precentge.
This example: https://codepen.io/piernik/pen/PXbjze
First part od funnel chart - `leads`. Tooltip says `38%` What is 38% ? Shouldn't it be 100%?

**Comment by zeroin** [comment]
Here is a pen which solves this issue with with adapters: https://codepen.io/team/amcharts/pen/Gbdvqy
