### ISSUE TITLE
Creating chart without initial target?

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#705]
Is it possible to create a chart without providing an initial target element, and set this element later for drawing?
In my case I have project using amCharts 3 and try to migrate to amCharts 4. With amCharts 3 I create the charts object first, and configure it. I hold references to some amChart classes, used to configre the chart for later adjustments. When everything is done, I draw the chart into the target with `write(target)`.
In amCharts 4, as long as I can see it, everything starts with the creation of the chart into the target. This would break with my project, because the target do not exists, when the chart is created.
The only workaround I see, is to use the JSON creation. But with this I can not hold the references to the amChart Objects.

**Comment by martynasma** [comment]
This is a very good point. And something we have been actually experimenting with ourselves.

I'm hoping to have some more information about this later this week.

Will ping you here.

**Comment by aleksandraleszczyszyn** [comment]
I´m having the same problem. Is there any solution by now?
