### ISSUE TITLE
Dynamically updating series' and related elements' colors

### ISSUE THREAD

**Issue by Eldair** [amcharts/amcharts4#714]
Hello,

Instead of recreating each series in order to update colors I do a for loop on chart object series property which is ok but updating colors is not such an easy task. So, in order to update all colors I have to do the following (XY Line chart)

```
// cursor tooltip
series.fill = color;
// series.stroke = color;
// line
series.segments.getIndex(0).fill = color;
series.segments.getIndex(0).stroke = color;
// bullets
series.bullets.getIndex(0).fill = color;

// shadow
if (series.filters.length) {
    series.filters.getIndex(0).color = color;
}
```
and I still haven't found a way to update related legend marker fill.
Is there some way to connect these options so that I don't have to update each one separately?

**Comment by Eldair** [comment]
Regarding legend I recreate it because I couldn't find any clear connection between markers and series it is applied for.

**Comment by Eldair** [comment]
For Pie chart it seems I have to go through each slice of each series in order to update fill because setting colors.list on series object doesn't update slices

**Comment by martynasma** [comment]
You have raised a good question.

We believe that it should be enough to set series` `fill` and/or `stroke` to make it update itself as well as legend marker automatically.

That is not the case right now, so we will need to implement it, and let you know.

In the interim, the following code should do:

```
series.stroke = am4core.color("#f66");
series.fill = am4core.color("#f66");  
series.invalidate();
chart.feedLegend();
```

https://codepen.io/team/amcharts/pen/93c9cafd846f94ae8abd524aa823d555

**Comment by Eldair** [comment]
Hi,

Thanks for the workaround.
feedLegend() works great
invalidate() works for line chart (stroke/fill of segment) but doesn't work for:
pie chart slices when changing series.colors and invalidating
line chart drop shadow filter (which cannot be updated using my code from the first comment - my mistake for thinking that it does)
bar chart  - series.columns.template.fill/stroke has to be set again

**Comment by martynasma** [comment]
For PieChart this works:

```
pieSeries.colors.list = [
  am4core.color("red")
];
chart.invalidateData();
```

As for filters, I don't think there's a way to re-use one. I suppose you'll need to dispose old ones and add new ones.

**Comment by jimmykane** [comment]
Glad I found this one

**Comment by saveriocaminitiktech** [comment]
I this problem on a Map with a few MapPolygonSeries.
The series are initialised to include only a certain countries each (without redefining geodata).
When I change the include array of a serie programatically I cannot force the map to reflect the change.
I tried invalidateData(), reinit(), and deepInvalidate() both on the series and on the whole map.
No success.

Any suggestion?

**Comment by saveriocaminitiktech** [comment]
I end up using a simple workaround for maps: whenever I change include/exclude properties for a MapPolygonSeries I also set its data property to a new array instance (even a new empty array is ok). This force data update and map refresh.

**Comment by martynasma** [comment]
I believe this has been implemented in `4.7.20`. Closing.

**Comment by Eldair** [comment]
Hi @martynasma this is what I observed (using latest version):
for all chart types except pie chart: calling `feedLegend` is still necessary, legend markers won't change color automatically.
for pie chart: `chart.invalidateData` still has to be called (it updates legend as well)
filters still have to be dropped/recreated

**Comment by saveriocaminitiktech** [comment]
@martynasma I updated to 4.8.6 and for MapPolygonSeries changing the include property does not refresh the map. I still need to set the data property to a new array to force a redraw.

**Comment by fvillarrealcespedes** [comment]
Hi! @martynasma @amcharts I'm actually working with a Force Directed Tree and I have a similar problem. I want to update dinamically the nodes color in function of their value. The value it's constantly updating. I can change the value, and I see the change on the tooltip, but I can't change the color unless I dispose the chart and create a new one. Any suggestion?
