### ISSUE TITLE
Bug connected visible series

### ISSUE THREAD

**Issue by quikki13** [amcharts/amcharts4#715]
We have several buttons on web-site (up-left corner). Each of buttons load set of data for construct charts. When i activate BTN1 and make second series hidden (use click for it) all fine. But after this i activate BTN3 and result on the picture (I have 3 series and stacked this). Data for hidden series comes and displays on charts but without color. It is not local.  I expect that hidden series just don't comes when i change button .

![untitled](https://user-images.githubusercontent.com/43207395/50220560-b56ec980-03a3-11e9-8d9e-0293582c2834.png)

When i click button we get new set of data and update charts without reboot page.

Sorry if it is't bug, then help me decide this problem. TY

**Comment by martynasma** [comment]
Would you be able to provide chart code and data for this so we can see exactly what you are doing on button switch?

**Comment by quikki13** [comment]
@martynasma 
[proj.txt](https://github.com/amcharts/amcharts4/files/2697484/proj.txt)

**_sсheme of objects for draw chart:_**
 class BacklogHistory {
    date:string;
    count:{
        income:{
            a:number, b:number, c:number
        };
        solved:{
            a:number, b:number, c:number
        };
        backlog:{
            a:number, b:number, c:number
        };
    };
}

**Comment by martynasma** [comment]
Thanks. There's no data, though. Can you toss in some sample data so that we can set up a test case, without inventing your data? :)
