### ISSUE TITLE
View is different with ipad (browsers : safari and chrome) 

### ISSUE THREAD

**Issue by chaktanir** [amcharts/amcharts4#725]
Hello, I'm using amcharts V 4.0.9.
I'm trying to create 3d pie charts. It's working with desktop chrome browser very well. But in ipad 3d parts not seen, hit functions not working properly and also tooltips not working properly. I didn't solve this problem can you help me ? Please find pictures below. 
![chrome-view](https://user-images.githubusercontent.com/45783013/50271791-dc320c00-0446-11e9-93ab-4b77cc006c14.png)
![ipad view](https://user-images.githubusercontent.com/45783013/50271800-e227ed00-0446-11e9-8f19-e6356a76f35f.jpeg)

**Comment by RobbiesCode** [comment]
Hi there,

I'm sorry for the late reply. What iPad are you on? Are you using default Safari browser? Do you have a code example? That way I can see if I can reproduce your issue.

**Comment by martynasma** [comment]
We can't seem to be able to replicate the issue you have described.

Please provide a demo, code, or description of the steps needed to reproduce it.
