### ISSUE TITLE
am4maps is not defined

### ISSUE THREAD

**Issue by venkateshthallam** [amcharts/amcharts4#728]
I created a map chart using amcharts and it worked until a hour ago. Now the map doesn't render and the console shows the error message `am4maps is not defined`. I assume it is part of either `core.js` or `maps.js` or it was, the code pen links on your website also doesn't render the maps anymore.

Did you guys push a change to the core or maps js files today?

**Comment by martynasma** [comment]
Sometimes, when we release a new version, your browser might have core.js and maps.js files cached from different versions, which would create a conflict. Try clearing browser cache.
