### ISSUE TITLE
How to achive depth3d in column series

### ISSUE THREAD

**Issue by jgathairu** [amcharts/amcharts4#729]
![capture](https://user-images.githubusercontent.com/29246216/50306286-39a97580-04a6-11e9-9848-82f5a421acc0.PNG)

I was able to do the attached graph using amcharts3. How do I do it on amcharts4

**Comment by notacouch** [comment]
You would use a [`ConeSeries`](https://www.amcharts.com/docs/v4/reference/coneseries/) in a [3D XYChart](https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Going_3D).

Some other notes:

- What you knew as balloons in v3 are now tooltips in v4. By setting `tooltipText` on a relevant object, the tooltip will automatically trigger on hover.
- By default, all the cylinders would be the same color, i.e. the color of their series. In the demo below, [adapters](https://www.amcharts.com/docs/v4/concepts/adapters/) (it's a like a hook into a property as it is about to be set) are used to reset each cylinder's color on-the-fly.
- You'll also see `.template` a bunch in the demo, it's a new concept in v4 called a [`ListTemplate`](https://www.amcharts.com/docs/v4/concepts/list-templates/). It's an instance of a Class that gets cloned/duplicated, so we can operate on that before actual instances of the Class are generated for the chart. With its `applyOnClones` property set to `true` (many cases this is the default), changes made to it can also affect existing clones. 

Here's a demo with some additional comments and references within:
https://codepen.io/team/amcharts/pen/3c3967d0aed0a84322c6b84f68957495

**Comment by jgathairu** [comment]
Hello notacouch, 
Thanks for the pointer, tried your sample and worked well. Howevwer after importing data from my URL via datasource property, it gives an error "Cannot read property 'coneColumn' of undefined". My code is as below.

I have already imported the necessary am charts libraries
<script src="~/amcharts4/core.js"></script>
<script src="~/amcharts4/charts.js"></script>
<script src="~/amcharts4/themes/animated.js"></script>
<script src="~/amcharts4/themes/kelly.js"></script>

my json return data from datasource is as below 
[{"county":"Nairobi","visits":3},{"county":"Mombasa","visits":1},{"county":"Nakuru","visits":1},{"county":"Kirinyaga","visits":1},{"county":"Kisumu","visits":1},{"county":"Kakamega","visits":1},{"county":"Kericho","visits":1},{"county":"Kisii","visits":1},{"county":"Samburu","visits":1},{"county":"Laikipia","visits":1},{"county":"Wajir","visits":1}]


**Why cant the cone series work with datasource url data?**

// Create chart instance
                var chartDistributionByCountyBarChart = am4core.create("chartdiv", am4charts.XYChart3D);
                chartDistributionByCountyBarChart.paddingBottom = 30;
                chartDistributionByCountyBarChart.angle = 35;
                chartDistributionByCountyBarChart.legend = new am4charts.Legend();
                chartDistributionByCountyBarChart.exporting.menu = new am4core.ExportMenu();
                // Add data
                chartDistributionByCountyBarChart.dataSource.url = "/Home/dashboardVueDistributionByCountyBarChart/?startDate=" + startDate + "&endDate=" + endDate;

                //chartDistributionByCountyBarChart.data = [{
                //    "county": "USA",
                //    "visits": 4025
                //}, {
                //    "county": "China",
                //    "visits": 1882
                //}, {
                //    "county": "Japan",
                //    "visits": 1809
                //}, {
                //    "county": "Germany",
                //    "visits": 1322
                //}, {
                //    "county": "UK",
                //    "visits": 1122
                //}, {
                //    "county": "France",
                //    "visits": 1114
                //}, {
                //    "county": "India",
                //    "visits": 984
                //}, {
                //    "county": "Spain",
                //    "visits": 711
                //}, {
                //    "county": "Netherlands",
                //    "visits": 665
                //}, {
                //    "county": "Russia",
                //    "visits": 580
                //}, {
                //    "county": "South Korea",
                //    "visits": 443
                //}, {
                //    "county": "Canada",
                //    "visits": 441
                //}, {
                //    "county": "Brazil",
                //    "visits": 395
                //}, {
                //    "county": "Italy",
                //    "visits": 386
                //}, {
                //    "county": "Taiwan",
                //    "visits": 338
                //}];

                // Create axes
                categoryAxis = chartDistributionByCountyBarChart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.dataFields.category = "county";
                categoryAxis = chartDistributionByCountyBarChart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.dataFields.category = "county";
                categoryAxis.renderer.grid.template.location = 0;
                categoryAxis.renderer.minGridDistance = 30;
                categoryAxis.renderer.labels.template.rotation = 300;
                categoryAxis.renderer.labels.template.hideOversized = false;
                categoryAxis.renderer.labels.template.horizontalCenter = "right";
                categoryAxis.renderer.labels.template.verticalCenter = "middle";
                categoryAxis.tooltip.label.rotation = 270;
                categoryAxis.tooltip.label.horizontalCenter = "right";
                categoryAxis.tooltip.label.verticalCenter = "middle";
                valueAxis = chartDistributionByCountyBarChart.yAxes.push(new am4charts.ValueAxis());
                var series = chartDistributionByCountyBarChart.series.push(new am4charts.ConeSeries());
                series.dataFields.valueY = "visits";
                series.dataFields.categoryX = "county";
                //series.name = "No. of Activities";
                series.columns.template.tooltipText = "{categoryX}: [bold]{valueY}[/]";
                var columnTemplate = series.columns.template;
                // Make the cylinders slightly transparent
                columnTemplate.fillOpacity = 0.85;
                columnTemplate.strokeOpacity = 0.85;
                columnTemplate.tooltipText = "{categoryX}: {valueY}";
                columnTemplate.adapter.add("fill",
                    (fill, target) => {
                        return chart.colors.getIndex(target.dataItem.index);
                    });
                columnTemplate.adapter.add("stroke",
                    (stroke, target) => {
                        return chart.colors.getIndex(target.dataItem.index);
                    });

**Comment by martynasma** [comment]
Your code looks good. The only issue is that in adapters you are referring to `chart` variable, whereas you store chart object in `chartDistributionByCountyBarChart`. Changing that, make your chart with external data work perfectly fine:

https://codepen.io/team/amcharts/pen/1c6cbb14d2a6b4aee50a20768136f553?editors=0010

**Comment by jgathairu** [comment]
Thank you All. Worked

**Comment by jjpshaw** [comment]
How to get this
![amCharts](https://user-images.githubusercontent.com/40715959/71023469-cf62f980-2128-11ea-9f65-42a0c683e649.jpg)
