### ISSUE TITLE
tooltipHTML does not work properly

### ISSUE THREAD

**Issue by zmey-nosak** [amcharts/amcharts4#730]
Hello. TooltipHTML does not work properly when I use it with XYCursor and LabelBullet. You can see it there:
https://jsfiddle.net/StepanKoledov/y21tbhf9

**Comment by martynasma** [comment]
This is a duplicate of #668.

I'm gonna close this issue. Please subscribe to the original one.

**Comment by zmey-nosak** [comment]
Oh, sorry! Thank you
