### ISSUE TITLE
AmCharts.clear(chart); equivalent in version 4?

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts4#731]
I can't seem to find, or figure out, how to clear a chart in version 4.  What is the equivalent of : 

```
AmCharts.clear(chart);
```

in version 4?

**Comment by martynasma** [comment]
In amCharts 4 we use `dispose()` method:

```
chart.dispose();
```

**Comment by morrow95** [comment]
@martynasma  - thanks!

**Comment by emersonbottero** [comment]
You can still put every step you used to create the chart in a function and then
chart.dispose();
set themes
createChart();

amChart is realy fast and recreating the chart is still very responsive. I'm using urlData with 6 series in more then 200 lines and the user never notice the chart was been rebuild.
