### ISSUE TITLE
Labels and branding logo don't appear properly when the container contains padding

### ISSUE THREAD

**Issue by darlesson** [amcharts/amcharts4#734]
Some labels are being cropped, other's passing the container boundaries when the container contains padding. amCharts branding logo also appears out of the container.

![image](https://user-images.githubusercontent.com/174226/50388245-24f6f880-06c5-11e9-8bc3-729edd224d58.png)

**Comment by martynasma** [comment]
We'll see if we can account for padding of the container.

Meanwhile it's best not to have any padding on chart containers, and leave it up to chart's own padding.
