### ISSUE TITLE
Chart does not properly parse date xAxis 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#738]
Hi remember this issue https://github.com/amcharts/amcharts4/issues/690 ? 

I managed to reproduce it with a code pen. 

https://codepen.io/anon/pen/PXjgXa 

Take a look 

Setup: 

Creating 2 series of numeric values and date XAxes inside a timeout. 

The first series has dates before the second series. So the one proceedes the other. 
Eg series 1 goes up to date x and from there series 2 continues. 

However the first time the chart is drawn the dates of the 2 series are not once after each other but mixed. 

See: 

<img width="723" alt="screenshot 2018-12-26 at 14 09 12" src="https://user-images.githubusercontent.com/1268723/50446909-d8572b80-0917-11e9-94c2-4f11b47faad9.png">

But when I resize the width of the window a bit the chart shows correctly 

<img width="1400" alt="screenshot 2018-12-26 at 14 09 58" src="https://user-images.githubusercontent.com/1268723/50446929-fae94480-0917-11e9-9dac-a41e40a5a60c.png">

@martynasma  do you need more info on this? 

- Series are created on time out 
- Invalidating does not solve it.

**Comment by jimmykane** [comment]
Please before running the snippet edit some of the code so live changes apply. Its only then that the issue exposes. 

recording video atm

**Comment by jimmykane** [comment]
Ok here is the recording (its uploaded to drive might take a few to be processed so download it if it's not already) . 

https://drive.google.com/file/d/1F3XqaKxBHCLnhuVAJgHQwHfmE08Lr3xe/view

As you can see: 

- The first time the chart is rendered is not correct. 
- A width resize fixes it
- Staying on that width it's ok 
- Changing a bit the width and triggering a redraw exposes the issue again 
- Changing the width also fixes that again

**Comment by martynasma** [comment]
I can't seem to be able to reproduce this anymore.

Would you please try and confirm whether you are still seeing this issue with the latest version? (4.0.16)

**Comment by jimmykane** [comment]
@martynasma  on the online demo (not sure what version of AmCharts is there) it's still reproducable

**Comment by jimmykane** [comment]
Unfortunately, it's still reproducible on the above codepen and my own project :-( 

<img width="928" alt="screenshot 2019-01-06 at 15 57 42" src="https://user-images.githubusercontent.com/1268723/50737614-e59fd000-11cb-11e9-8544-69bfa401e69d.png">

If you see in the above picture the line looks flat for some reason. Resizing fixes it.

**Comment by martynasma** [comment]
Does this happen in all browsers?

**Comment by jimmykane** [comment]
I have not tested al @martynasma but firefox and chrome have this issue. 

Take a look: https://codepen.io/anon/pen/bORypy

Firefox first open -> Series are overlaping
<img width="1438" alt="screenshot 2019-01-07 at 09 39 41" src="https://user-images.githubusercontent.com/1268723/50757649-5264aa00-1260-11e9-8306-eae12d7c661c.png">


Firefox resize (change window width) -> Serries ok 

<img width="1370" alt="screenshot 2019-01-07 at 09 39 55" src="https://user-images.githubusercontent.com/1268723/50757677-67d9d400-1260-11e9-8a4a-41d307e881fa.png">

**Comment by martynasma** [comment]
Which version of Firefox are you using?

I can't seem to be able to reproduce it with neither FF nor Chrome.

The chart always appears like the second screenshot for me.

**Comment by jimmykane** [comment]
Can you try to change the width of your browser ?
It happens on specific widths!

Latest version for both browsers.

**Comment by jimmykane** [comment]
Just to repeat. This seems to happen on specific widths. You can change
width, reload codepen etc

**Comment by jimmykane** [comment]
It somehow looks like a race condition to be honest

**Comment by jimmykane** [comment]
I noticed that if for example I have a high CPU load this happens more often. So perhaps that helps.

**Comment by jimmykane** [comment]
I can do anything to nail down that bug even a remote team view or slack call. It's the last bug standing for my migration

**Comment by martynasma** [comment]
OK, thanks, after a few attempts I was finally able to reproduce it.

Bugs like that are extremely tricky to fix, so I can't promise this will happen quickly.

Will keep you posted about the progress, tho.

**Comment by jimmykane** [comment]
I don't worry about how fast its fixed. Just to know that its reproducible
its enought for me.

You are doing great work guys and its much appreciated.

**Comment by martynasma** [comment]
@jimmykane Stumbled on this old issue and I cannot seem to be able to reproduce this anymore. It could have been fixed since then. Can you doublecheck if you can still reproduce it?

**Comment by jimmykane** [comment]
Yeah lets close that. Does not seem critical and I cannot reproduce now. 

As you say: Ill go ahead and close this
