### ISSUE TITLE
data adapter runs for each data element

### ISSUE THREAD

**Issue by Epochi** [amcharts/amcharts4#741]
chart adapter for data runs for every element in data array and then several additional times(not sure what affects it).

example in documentations to sort line chart by date
https://www.amcharts.com/docs/v4/concepts/data/#Order_of_data_items

for 8 data items it's called 11 times
for 9 data items it's called 12 times etc

Here's a modified codepen from the documentation that counts every adapter call
https://codepen.io/Bitvala/pen/BvdOaR

is this intended behavior?

**Comment by martynasma** [comment]
`"data"` adapter kicks in every time `chart.data` is requested. So having sort there is probably not the best solution.

Probably better solution would be to use an event, that kicks in once and sorts the data once.

```
chart.events.on("beforedatavalidated", function(ev) {
  chart.data.sort(function(a, b) {
    return (new Date(a.date)) - (new Date(b.date));
  });
});
```

I updated the article as well.

Thanks for the heads up!

**Comment by Epochi** [comment]
Thanks for the quick response.
Also really happy that your solution does not add additional complexity

**Comment by Epochi** [comment]
@martynasma just a quick note, the JSON example should probably be using event target instead of self reference. This way JSON config can be abstracted

```js
{
  // ...
  "events": {
    "beforedatavalidated": function(ev) {
      ev.target.data.sort(function(a, b) {
        return (new Date(a.date)) - (new Date(b.date));
      });
    }
  }
}
```

**Comment by martynasma** [comment]
Good point. Fixed. Thanks!
