### ISSUE TITLE
Is it possible to have a legend for columns (not for series) on a column diagram?

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#746]
Example:
https://codepen.io/dmsmaxim/pen/Xoeamy

It's possible to add a legend for series:
![image](https://user-images.githubusercontent.com/15041200/50528057-c54d8280-0af4-11e9-8f46-77f3484b5b4d.png)

But can I create the same, but for columns? So there will be a marker for every column (column labels on the axis also should be presented).

**Comment by martynasma** [comment]
Challenge accepted :)

https://codepen.io/team/amcharts/pen/ebGreb?editors=0010

**Comment by dmsmaxim** [comment]
But when we create manually (like the example above) legend items, they will be static.
So when we, for example, change column opacity, legend stays the same.
```
setTimeout(() => {
  series.columns.template.fillOpacity = 0.3;
}, 3000);
```
https://codepen.io/dmsmaxim/pen/zyEaPB?editors=0010

**Comment by martynasma** [comment]
Well, in that case you need to update legend as well.

```
setTimeout(() => {
  series.columns.template.fillOpacity = 0.3;
  legend.markers.template.fillOpacity = 0.3;
}, 3000);
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
