### ISSUE TITLE
smooth update for propertyFields dx, dy

### ISSUE THREAD

**Issue by keikoskat** [amcharts/amcharts4#749]
The following example tries to update `dx` and `dy` which are used as propertyFields. 
`invalidateRawData` has no effect and `invalidateData` results in a flickering effect for the first star. 

https://codepen.io/team/amcharts/pen/507997029afbaaf9b52e607265a5655e?editors=1010

Value updates work fine, but dx and dy (and other property fields) do not work with `invalidateRawData`:

```
function change() {
  //chart.data[1]["value1"] = Math.random() * 1000 + 1000;
  //chart.data[1]["value2"] = Math.random() * 100 + 1000;
 
  chart.data[1]['dx'] = 0; 
  chart.data[1]['dy'] = 0; 
  chart.invalidateData();
  //chart.invalidateRawData();
}
```
What can be done for a smooth update without the flicker effect?

**Comment by zeroin** [comment]
I updated the demo: https://codepen.io/team/amcharts/pen/507997029afbaaf9b52e607265a5655e?editors=1010

To show how dx and dy can be changed directly, hope it helps.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
