### ISSUE TITLE
Q: Minimal width of Scrollbar control

### ISSUE THREAD

**Issue by FrankMerema** [amcharts/amcharts4#754]
Having a real big chart with a lot of data, zooming will cause the scrollbar handle to shrink every time you zoom (which makes senses of course ;) ).

My Question: Can I limit the width of the zoom handle to be at least something of 50px? So users still can scroll when zoomed?

Thanks!

**Comment by martynasma** [comment]
Sure :)

```
chart.scrollbarX.thumb.minWidth = 50;
```

**Comment by FrankMerema** [comment]
I experienced some weird behavior with setting the minWidth. When I zoom in to a very small number, say 1 minute, and have a minWidth on the thumb, the scrollbar automagically zooms out to (I guess) the some level related to the width.

Maybe its only disabling zoom on the scrollbar?

I added an example showing the result:
https://codepen.io/anon/pen/WLdRKb?&editable=true

(Zoom in to minute level and then try to scroll using the scrollbar, you will see your zoom level will change)

**Comment by martynasma** [comment]
Indeed. We'll need to look into it. Just not sure when this will happen.

Let me put another option on the table: [`minZoomCount`](https://www.amcharts.com/docs/v4/reference/dateaxis/#minZoomCount_property).

E.g.:

```
dateAxis.minZoomCount = 60;
```

The above will prevent zooming in deeper than 60 time units (minutes in your case), and thus will negate the need for `minWidth` altogether.

Maybe this approach provides better UX by preventing unreasonably deep overzoom.

**Comment by FrankMerema** [comment]
Will use the other option for now, as it is the one I already need :)

**Comment by FrankMerema** [comment]
It was oke in my example data, but for the real data I need to show 3 days of data, which can be zoomed in at a level of seconds. So I need the min width definitely to keep the scrollbar functional. Any thoughts on this?

**Comment by martynasma** [comment]
Hm, maybe adding a fat stroke around the thumb?

```
chart.scrollbarX.thumb.background.stroke = am4core.color("#f00");
chart.scrollbarX.thumb.background.strokeWidth = 5;
```

**Comment by FrankMerema** [comment]
Nice one! I also added the fill so the user won't see the stroke! Thanks!

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
