### ISSUE TITLE
Gauge chart sometimes show wrong value

### ISSUE THREAD

**Issue by MarkLyck** [amcharts/amcharts4#756]
I have a gauge chart on the front page of our website which is a demo of a dynamic gauge chart in our dashboard. (it is using the exact same component, only different is that the demo on the main page is hardcoded) and the front page is server-side-rendered, but the amcharts library is loaded async clientside. (using amcharts animated theme).

sometimes when refreshing the page the gauge chart shows the value "100" (on a scale from -100 to 100) even though the actual value is hardcoded to 82.

<img width="420" alt="screen shot 2018-12-31 at 3 32 53 pm" src="https://user-images.githubusercontent.com/6841110/50562159-e50dc200-0d11-11e9-8906-64e44d1ac184.png">

resizing the window, or refreshing the page causes the chart to jump to its correct value of 82.
I have the chart set to a ~25% width of the window, so resizing the window would cause the chart to re-render.

Here's the code I use to set up the hand:

```
  const hand = chart.hands.push(new am4charts.ClockHand())
  hand.fill = am4core.color(theme.colors.black)
  hand.stroke = am4core.color(theme.colors.black)
  hand.fillOpacity = 1
  hand.strokeWidth = 0
  hand.radius = am4core.percent(98)
  hand.innerRadius = am4core.percent(60)
  hand.pin.disabled = true
  hand.value = 0

  setTimeout(() => {
    hand.showValue(82, 1000, am4core.ease.cubicOut)
  }, 500)
```

I have tried not animating the hand (with the setTimeout) and just setting hand.value directly to 82. But it has the same problem.

I am using the latest amcharts npm package:
"@amcharts/amcharts4": "^4.0.13"

after resizing the window it corrects itself:
<img width="578" alt="screen shot 2018-12-31 at 3 42 13 pm" src="https://user-images.githubusercontent.com/6841110/50562238-b47a5800-0d12-11e9-9ae8-8a39dd2cc1ce.png">

(this doesn't happen every time, it seems random when it happens)
Here's a gist of the full chart code: https://gist.github.com/MarkLyck/5ebbb63be5d19f90cc56841c602b3f27

**Comment by zeroin** [comment]
I tried to reproduce this but with no luck.
Could you try instead of setTimeout use "ready" event, like:

```
chart.events.on("ready", ()=>{
       hand.showValue(82, 1000, am4core.ease.cubicOut);
});
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by gasserdav28** [comment]
How can i add hands when i create the chart from JSON-config?
I'm trying this:

```
 {
            "innerRadius": -15,
            "hands": {
              "value": 23
            },
            "xAxes": [
              {
                "type": "ValueAxis",
                "min": 0,
                "max": 100,
                "strictMinMax": true,
                "axisRanges": [{
                  "value": 0,
                  "endValue": 80,
                  "axisFill": {
                    "fill": "#D0D0D0",
                    "fillOpacity": 1
                  }
                },
                {
                  "value": 80,
                  "endValue": 100,
                  "axisFill": {
                    "fill": "#263996",
                    "fillOpacity": 1
                  }
                }]
              }]
          }
```

**Comment by maxkermarrec** [comment]
Hello,
I found exactly the same problem.
It even appears in the codepen of the demo for the angular chart, if you delete the timeout and only make one call to the randomValue function, the hand jumps to 100.

Thank you.

**Comment by eskayamadeus** [comment]
> I tried to reproduce this but with no luck. Could you try instead of setTimeout use "ready" event, like:
> 
> ```
> chart.events.on("ready", ()=>{
>        hand.showValue(82, 1000, am4core.ease.cubicOut);
> });
> ```

That worked in my case!
