### ISSUE TITLE
Disabling chart touch gestures until tap on it

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#757]
This would allow users scroll the page even on chart surface without triggering zoom on charts which normally prevents the scroll.

**Comment by MarkLyck** [comment]
Thanks for creating this Martynas!

**Comment by martynasma** [comment]
Just noticing this hasn't been closed.

`tapToActivate` is implemented in `4.4.0`.

## [4.4.0] - 2019-04-17

### Added
- Charts now have new property - `tapToActivate` (default: `false`). If set to `true` it will not react to touch drag gestures until user taps on the chart. [More info](https://www.amcharts.com/docs/v4/concepts/touch/).
- New element on charts: `dragGrip`. It's a grip that, when enabled, will allow scrolling the page even if the chart functionality does not permit it, e.g. with chart cursor or `MapChart`. [More info](https://www.amcharts.com/docs/v4/concepts/touch/).
