### ISSUE TITLE
Question: Empty ListTemplate<AxisDataItem>

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#758]
Hey I am trying to deep clone all my axisRanges for later used, but I don't succeed in create an empty ListTemplate<AxisDataItem>.
What I need to send in the constructor in order to satisfy ListTemplate's demands!
This is my code:
```
const deepClones = new ListTemplate<AxisDataItem>( ??? );
xAxis.axisRanges.clone().each(axisRange => deepClones.push(axisRange.clone() as AxisDataItem));
```
Any Help is welcome!
Barak Inbal

**Comment by FrankMerema** [comment]
In the docs I see it expects an Template of the Item you want to add later on.

Also the ListTemplate has an method which copies all items of an other list: https://www.amcharts.com/docs/v4/reference/listtemplate/#copyFrom_method

Don't know if it's helping you but maybe you can give it a try

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
