### ISSUE TITLE
LineSeries bullets shown when "visible": false

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#760]
When a line series is hidden via "visible": false in JSON, its bullets (if present) are shown anyway. Looks funny :) CodePen: https://codepen.io/npc42/pen/wRPxZK

Also, https://www.amcharts.com/docs/v4/concepts/series/#Pre_hiding_series suggests to use “hidden” property, which doesn't work (saw reference from #70).

**Comment by darlesson** [comment]
Please try `"hidden": true` again. It was fixed and released under [4.0.14](https://github.com/amcharts/amcharts4/releases/tag/4.0.14) yesterday.

**Comment by martynasma** [comment]
I can confirm that replacing `visible: false` to `hidden: true` pre-hides the series correctly with current version. Including the bullets.

Closing this, but please feel free to reopen if you are still seeing the issue.
