### ISSUE TITLE
Question: How to set the yAxes on legend label click

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#764]
Hi I am creating a chart where series hold the data and the chart only is setup with a legend. 

I can listen on: 

```
       chart.legend.itemContainers.template.events.on("hit", function (ev) {
          console.log("Clicked on",<am4charts.LineSeries>ev.target.dataItem.dataContext);
         
        });
```

However I kinda dont know how to proceed to achieve: 

When a legend item is clicked I wanat the chart's yAxes to be the only axis and all data should align to that. 

For example if you lets say click on a legend items the whole chart should only have an axis for that and zoomed on that. 

I tried: 

```
        chart.legend.itemContainers.template.events.on("hit", function (ev) {
          console.log("Clicked on",<am4charts.LineSeries>ev.target.dataItem.dataContext);
          const series = <am4charts.LineSeries>ev.target.dataItem.dataContext;
          chart.yAxes.clear();
          const valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
          // valueAxis.file
          valueAxis.min = series.minX;
          valueAxis.max = series.maxX;
          chart.yAxes.push(valueAxis);
          chart.invalidateData();
        });
```

However the above would just add some empty space .... 

Any tips on how: 

To add an perhaps already genereated series yAxes? 
How to revalidate as of zooming to that Axes?

**Comment by martynasma** [comment]
Re-creating axes on each series toggle sounds like an overkill to me :)

How about you create each series with its "own" axis. Then just `hide()` or `show()` both series and its `yAxis` on click?

**Comment by jimmykane** [comment]
That is a good advice thanks! I ll try that out .

**Comment by jimmykane** [comment]
@martynasma  I would love a tiny concept example. I am having a tiny trouble adding an axis to a series.

**Comment by jimmykane** [comment]
How can I create a series with an Axis (could not manage nor find it in the tutorial).

**Comment by jimmykane** [comment]
that worked but: 

1. I need when creating a chart (since I am attaching the series afterwards) to provide an initial axis to the chart else I get an error that there is no yAxis for the chart. 
2. When I add individual axis for each series those axis take space on the side of the chart. 


Regarding 2 how can I  have the axis but not take space? 


See how it looks: 


<img width="809" alt="screenshot 2019-01-09 at 13 10 19" src="https://user-images.githubusercontent.com/1268723/50898592-f2ad0100-140f-11e9-82f5-a22cbb987f1b.png">

**Comment by jimmykane** [comment]
I am figuring this out! 
`disabled` prop  helps!

**Comment by martynasma** [comment]
Right, yeah. Sorry I didn't mention it. Just hiding stuff will still leave space reserved for it. Whereas disabling will completely remove from the layout.

**Comment by jimmykane** [comment]
I hope last and final question (I did it!) 

When hiding/disabling an AXIS then the grid lines are still there. 

How can we remove those? 

see 
<img width="820" alt="screenshot 2019-01-09 at 14 04 25" src="https://user-images.githubusercontent.com/1268723/50901136-9057fe80-1417-11e9-8f01-a072ee87085c.png">

**Comment by jimmykane** [comment]
Most probably: 
`            series.yAxis.renderer.grid.template.hide();
`
