### ISSUE TITLE
On MapImageSeries dataSource load, homeGeoPoint is no longer maintained

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#765]
Example:

https://codepen.io/team/amcharts/pen/db0a3e34a6a1d2e878a7e79c10afbd63

W/o the `MapImageSeries`, the map correctly loads the `homeGeoPoint`:

```javascript
// Initial Position / Zoom
chart.homeZoomLevel = 2.6;
chart.homeGeoPoint = {
    latitude: 39,
    longitude: -96.2456
};
```

Screenshot:
![image](https://user-images.githubusercontent.com/2334143/50674913-5c647f80-0fb8-11e9-9546-95fc5992bcc8.png)

With `MapImageSeries` loaded via external data (issue does not occur with `MapImageSeries.data = [...]`), the map is re-positioned, though it's not clear where/why it's re-positioning (it's not centering on the new images, you can see in the screenshot below that 1 of 2 images is not shown):

```javascript
imageSeries.dataSource.url = "https://codepen.io/team/amcharts/pen/78903713ac17eb6db20c291d7473bb90.js";
// ^[{"title":"ISP","url":"\/airport\/kisp\/","latitude":40.7952,"longitude":-73.1002},{"title":"AEX","url":"\/airport\/kaex\/","latitude":31.3274,"longitude":-92.5486}]
imageSeries.dataSource.parser = new am4core.JSONParser();
imageSeries.dataSource.parser.options.emptyAs = 0;
```

Screenshots:
![image](https://user-images.githubusercontent.com/2334143/50674946-ad747380-0fb8-11e9-8ae4-55a047e23100.png)

`zoomLevel` is still `2.6` as per `homeZoomLevel`, but `zoomGeoPoint` has changed:

![image](https://user-images.githubusercontent.com/2334143/50674983-e876a700-0fb8-11e9-9c96-49b544448659.png)

Rather than `homeGeoPoint`, perhaps the current zoom should be maintained, or one of the two whichever seems more apt at the time. Or if there's a reason the map is being re-positioned, then perhaps a way for the user to influence that reasoning if anything.

**Comment by martynasma** [comment]
This looks like it's been fixed :) Closing.
