### ISSUE TITLE
Barchart click event is not working

### ISSUE THREAD

**Issue by karuppasamy20** [amcharts/amcharts4#766]
this line is not working a bar chart. 
series.slices.template.events.on("hit", function(ev) {
this.getDetails(id,title,ev.target)
}, this);

**Comment by zeroin** [comment]
ColumnSeries doesn't have slices, it has columns, it should be:

```
series.columns.template.events.on("hit", function(ev) {
this.getDetails(id,title,ev.target)
}, this);
```

**Comment by karuppasamy20** [comment]
this one is tried but is not working in stackbar chart but its worked pie chart.

**Comment by zeroin** [comment]
It would help if you could provide a working codepen demo.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
