### ISSUE TITLE
XYChart: Bad Axis display on update chart datas

### ISSUE THREAD

**Issue by aubert-creation** [amcharts/amcharts4#767]
Hey,

When I update the data of my graph, or if I deactivate in the legend one of my series, the axes seem not to be correctly arranged anymore

![image](https://user-images.githubusercontent.com/9222552/50685574-058f9200-101a-11e9-8a63-719450e91076.png)
![image](https://user-images.githubusercontent.com/9222552/50685586-104a2700-101a-11e9-89ed-da77907cc834.png)
![image](https://user-images.githubusercontent.com/9222552/50685595-18a26200-101a-11e9-881c-d33a713072e3.png)
![image](https://user-images.githubusercontent.com/9222552/50685601-20620680-101a-11e9-8704-75d687bbe04b.png)

**Comment by martynasma** [comment]
Can you confirm you are running latest version (4.015)? We have fixed this kind of issue very recently.

If you are still seeing the issue, can you provide the code and data for your charts so that we can test?

**Comment by aubert-creation** [comment]
Oh thanks,
I am updating amcharts today, npm automatically offered me version 4.0.14
But with version 4.0.15, it's fixed!!

**Comment by jimmykane** [comment]
@martynasma  can this issue be related to https://github.com/amcharts/amcharts4/issues/738 ? I will test also later this evening
