### ISSUE TITLE
Issue with legend markers with zero value items when legend item state toggled off/on

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#77]
When rendering a legend, the "marker" for an item with a zero value initially starts off black. However, if you toggle the item on/off, when the item is turned back on the marker is gray.

In the example below, both the "Lithuania" or "Czech Republic" items have zero values. There markers are black by default. Click on either one to toggle the item "off" and then click it again to toggle it "on". Instead of the marker going black again, it's gray. The color should return to it's original state

https://codepen.io/anon/pen/dKVmoa

Is there are way to specify the color of a zero value marker? I'd actually prefer something other than a solid black. Is it possible to make zero value markers transparent?

**Comment by martynasma** [comment]
Indeed. Thanks for the heads up!

**Comment by dswitzer** [comment]
@martynasma 

Is there are way to specify the color of a zero value marker? I'd actually prefer something other than a solid black. 

Also, is it possible to make zero value markers transparent?

**Comment by martynasma** [comment]
They should not be black. They should have whatever the color they'd have from theme if they had a non-zero value. So we're going to be fixing them. A zero is just as valid value as, say, 5 :)

BTW, you probably can change that color using some adapter. But before we attempt to do that, we need to get rid of the "black-zero" bug.

I'll keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.31](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.31).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by dswitzer** [comment]
Good work! It appears to be working correctly now.
