### ISSUE TITLE
tooltipPosition='pointer' disables tooltip

### ISSUE THREAD

**Issue by evead** [amcharts/amcharts4#770]
It seems that activating tooltipPosition on StepLineSeries disables the tooltip.

I want the tooltip to follow the pointer/mouse.

Here is part of my code

`
chart.series = chart.chart.series.push(new am4charts.StepLineSeries());
.......

chart.series.tooltipHTML = "<span style='font-size:12px;'>Value : {valueY.value}</span>";

chart.series.tooltip.getFillFromObject = false;

chart.series.tooltip.background.fill = am4core.color("#7F8CA9");
chart.series.tooltip.background.opacity = 0.7;

**chart.series.tooltipPosition = 'pointer';**
;`

![image](https://user-images.githubusercontent.com/4017030/50708786-7906c300-105d-11e9-953a-b9d14ac398f3.png)

When I remove tooltipPosition, the tooltip shows in top of each bar.

**Comment by martynasma** [comment]
Confirmed.

Here's a simple example for testing:
https://codepen.io/team/amcharts/pen/6f1bf99afae18b6ca4546b71860417a5?editors=0010

**Comment by zeroin** [comment]
It doesn't make sense to use `tooltipPosition = "pointer"` on step series, as it's just one big object. Only ColumnSeries will work with this as you expect. I am afraid there is nothing we can do here.

**Comment by evead** [comment]
It would be good to have the tooltip following the pointer, for my example, the tooltip will be displayed on top of the icon, and the final result is not good.

Moreover, as you can see in the documentation, the tooltipPosition is available in StepLineSeries : 

https://www.amcharts.com/docs/v4/reference/steplineseries/#tooltipPosition_property

**Comment by martynasma** [comment]
`tooltipPosition` is inherited from ascendant class (`Sprite`). There are a lot of elements in amCharts 4 universe, wherever possible and makes sense, it is supported. In some cases, line on Line Series (and its variants) it's not entirely possible.

Theoretically, we could calculate the position along any line series' position. However, that would be a) huge overhead from performance standapoint; b) a lot of fuzzy logic in code for a feature with limited usability.

We might change this approach in the future. But for now we won't be implementing `tooltipPosition = "pointer"` support for any Line series.

I hope you find this reasonable.

**Comment by Ices-Eyes** [comment]
Wold this be supposed to work on a columnseries? I have the same no tooltip behaviour on that too?
