### ISSUE TITLE
Cannot set maxwidth to tooltiphtml

### ISSUE THREAD

**Issue by roshnidevadiga** [amcharts/amcharts4#778]
When the data in my html tooltip is long, it exceeds the screen width and appears broken. I tried setting a max width to my tooltip but it did not seem to work

I tried:
series.tooltip.maxWidth=200

Also once this breaks, if I hover over other items in the treemap, the tooltips which were earlier rendering correctly also break.

I am using amcharts 4.0.9

Here is a codepen example for the same: https://codepen.io/roshnidevadiga/pen/yRNgyZ?editors=1010

**Comment by martynasma** [comment]
Setting `maxWidth` without instructing the label what to do if it exceeds it does not make a lot of sense.

If you'd like your label to wrap, set `wrap: true`. If you'd like the text to be truncated, set `truncate: true`:

```
tooltip: {
  label: {
    maxWidth: 20,
    wrap: true
  }
},
```

**Comment by roshnidevadiga** [comment]
Thanks. This worked. 
But what about that scenario...once the tooltip breaks then if I hover over any other area those tooltips which earlier rendered correctly also break?

**Comment by martynasma** [comment]
> But what about that scenario...once the tooltip breaks then if I hover over any other area those tooltips which earlier rendered correctly also break?

Tooltip object is reused, hence the settings you set on it carries over to all appearances.

Or am I missing something? if you could provide an example, that would be great.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
