### ISSUE TITLE
Top most series in stacked area chart shows a fine line even if all the values are 0

### ISSUE THREAD

**Issue by roshnidevadiga** [amcharts/amcharts4#779]
I faced an issue in stacked area chart.
If the topmost series has all values 0 even then a fine line for that series is observed.
If I change the position of this series and place it below a non zero series, then that 0 series disappears as I would expect it to.
Can you please help me resolve this issue? I do not want the topmost series to show that fine line if all the values are 0

Here is the codepen for the same: https://codepen.io/roshnidevadiga/pen/oPdXQR?editors=1010

**Comment by martynasma** [comment]
That thin line is area series' outline (stroke).

To get rid of it simply set `strokeWidth` to zero:

```
series.strokeWidth = 0;

// ...

series3.strokeWidth = 0;
```

The reason why it's not showing when at the bottom is because zero is directly below axis line.

**Comment by roshnidevadiga** [comment]
Thanks. It worked!
