### ISSUE TITLE
Cannot export charts to an image (PNG/JPG/GIF) in IE11

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#78]
When trying to export a chart to an image (i.e. PNG, JPG, GIF) using Internet Explorer 11 (and I suspect below), the exporting image just includes a loading spinner that says "100%".

Here's a screenshot of what we're seeing:

![amcharts](https://user-images.githubusercontent.com/900497/41540071-511925d6-72dd-11e8-9661-889edaed956f.png)

You can see this behavior by going to the Export CodePen example from the docs and choosing to export to an image:

https://codepen.io/team/amcharts/pen/gzgxZZ

Version: amCharts 4 beta 29

**Comment by martynasma** [comment]
Fixed in 4.0.0-beta.30. ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta30---2018-06-22))

**Comment by dswitzer** [comment]
Things look to be working correctly now.

Thanks!
