### ISSUE TITLE
Set CategoryAxis independently from Series

### ISSUE THREAD

**Issue by jochenjonc** [amcharts/amcharts4#780]
Since one of the newer versions of AmCharts 4, I get the following error: `Cannot read property 'categoryY' of undefined`

My use-case is that I have chart filled with data, but I have a fixed list of items on the CategoryAxis, even if there is no item for that category in my chart data.

The problem occurs when I have set an empty list or nothing as chart.data and have set the data on the categoryAxis.

Is it a bug? Or am I doing something wrong.

**Comment by martynasma** [comment]
Wait, so you have `chart.data = []` and `categoryAxis.data = [ .... something here ... ]`?

If you could provide an example of your chart, it would help us investigate it better, using your precise setup.

**Comment by jochenjonc** [comment]
Yes, that was the case. But to be honest it also could have something todo with Angular and observables.

I'll try to make an example.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
