### ISSUE TITLE
Legend: Position absolute not working

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#781]
Because I do not want that the legend affects the charts size, so I tried to set its position to `absolute`. As mentioned in the documentation, I also set the attributes `x` and `y` to some value, but the legend is placed like the default value for position `bottom`. And the charts size is affected by the legends size.
I am doing something wrong? Is there a possibility to draw the legend in a different `div` element?

**Comment by martynasma** [comment]
Yes:
https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/

The reason why setting `position = "absolute"` does not work as expected is that legend rests in own container.

Moving it to some chart-wide container, like `tooltipContainer` should work:

```
chart.legend = new am4charts.Legend();
chart.legend.position = "absolute";
chart.legend.parent = chart.tooltipContainer;
```

We will also consider doing it automatically. Let's use this issue as a base for this enhancement.

**Comment by sandbox4013** [comment]
![image](https://user-images.githubusercontent.com/49528851/59363220-7eb7b180-8d3d-11e9-9527-1be97bf834d4.png)
Not work for me( 
Also, I tried initial position and valign properties, but i need more flexibility to position legend(like blue square). Any advise?

**Comment by sandbox4013** [comment]
Not elegant, but works for me;
`setTimeout(() => {
      chart.legend.x = 100;
    }, 0);`

**Comment by sdlins** [comment]
Happy birthday to this issue! :tada: 

@martynasma your workaround is not working to me.
@sandbox4013 yours dont too.

One year has been passed... would someone to know some other valid workaround?

**Comment by martynasma** [comment]
To get back to this, it is solvable via moving legend to some other container, e.g.:

```
chart.legend.position = "absolute";
chart.legend.parent = chart.tooltipContainer;
```

We're trying to avoid too much fuzzy logic, so we're not going to do this automatically. Closing.
