### ISSUE TITLE
Question: Prevent default hit handler for legend labels

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#782]
Hi,

I need to call a custom logic on legend label click (just the label, not the marker), but still allow to toggle series on marker click.

I couldn't find a way to prevent the default hit handler on just the labels (this is what I need — my handler instead of the default, not on top), so I had to achieve it via three steps:
```
// 1. Disable default toggle behavior for the whole container
chart.legend.itemContainers.template.clickable = false;

// 2. Custom logic on label
chart.legend.labels.template.interactionsEnabled = true;
chart.legend.labels.template.events.on('hit', e => {
    // Custom logic
});

// 3. Toggle series on marker
chart.legend.markers.template.interactionsEnabled = true;
    chart.legend.markers.template.events.on('hit', e => {
    const series = e.target.parent.dataItem.dataContext;
    series.hidden = series.isHidden ? series.show() : series.hide();
});
```

It works, but is there a simpler way? It'd be nice to include e.preventDefault and e.stopPropagation for event handlers, but I understand this could require a massive rework for you. 

In general, event bubbling seems odd — as far as I can tell, itemContainer's hit handler (the default one) triggers before the label's handler.

**Comment by martynasma** [comment]
I can't seem to think of a simpler way.

Legend items are designed to act on a click on the whole item, not its individual parts.

We also do not have a built-in bubbling/propagation chain interruption. So yes, if you leave default hit event on itemContainers and add an additional one to a label, then the former kicks in sooner because it was added earlier.

Not entirely sure what we can do here :/

**Comment by NPC** [comment]
@martynasma Thank you. As you see, I already had a solution, just that it has to be more complicated than I would have in, say, JQuery. But at least it is possible to achieve what I need, so I'm happy.

**Comment by NPC** [comment]
@martynasma can you please confirm if this is correct to toggle pie slices via legend marker clicks? (doing the same as above, but for PieChart):
```
chart.legend.markers.template.interactionsEnabled = true;
chart.legend.markers.template.events.on('hit', e => {
    let item = e.target.parent.dataItem.dataContext;
    item.slice.isHidden ? item.show() : item.hide();
});
```

The item I retrieve from dataContext for PieChart has isHiding prop (instead of isHidden — naming inconsistency, perhaps?), and it doesn't update on item.hide(), so I had to go through item.slice instead. Seems to work, but looks odd.

**Comment by klikkn** [comment]
@NPC, thanks for example! But it doesn't work without
```
this.chart.legend.itemContainers.template.focusable = false
```

**Comment by NPC** [comment]
I suspect that was changed when #1435 was fixed. Thanks for the headsup, @klikkn, it took me this long to notice the issue myself :)
