### ISSUE TITLE
Gradients without valueAxis.min = 0

### ISSUE THREAD

**Issue by samuel-p** [amcharts/amcharts4#783]
Hello,

if `valueAxis.min` is not 0 you get only a part of the preferred gradient:

https://codepen.io/anon/pen/LMrzQX

![screenshot](https://user-images.githubusercontent.com/7959516/50816315-78ea1a00-1320-11e9-87d6-348fc02d9a41.png)

Is there an option to get the full gradient on dynamic charts that don't have `valueAxis.min = 0`?

**Comment by martynasma** [comment]
Unfortunately, it's not possible to make the gradient to fill only visible part of the area series.

I'm going to leave this as a feature request, in case we find a way to implement it.

**Comment by samuel-p** [comment]
Thank you!

**Comment by Parallaps** [comment]
Any updates? I see the same issue

**Comment by martynasma** [comment]
I'm afraid we won't be able to implement this without significant remakes in underlying rendering mechanism, which would not be feasible.

Sorry. Closing.
