### ISSUE TITLE
Filters hides the line between dots in LineSeries

### ISSUE THREAD

**Issue by andreizet** [amcharts/amcharts4#784]
Hey!

I'm trying to highlight corresponding series when mouse is over a legend item. I've achieved that by adding
```over``` and ```out``` on legend. ```out``` adds a new filter to all the series except the one hovered, and ```out``` clears all the filters.

Check this out: https://codepen.io/andreizet/pen/zyaEQJ

The problem is that when applying filters to Italy series, the line between bullets disappears. It doesn't matter the filter type, or if it's applied when a legend item is hovered or when series are initialized.

Thanks!

**Comment by martynasma** [comment]
Creating and applying filters every time is an expensive operation.

How about creating and applying a custom state instead?

https://www.amcharts.com/docs/v4/concepts/states/

That said, there's probably a bug, which makes a straight line to disappear when `BlurFilter` is applied to it.

We'll need to investigate it.

Will keep you posted.
