### ISSUE TITLE
Removing series from scrollbar does not remove from scrollbarChart

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#785]
[Our guide says](https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Scrollbar_with_preview) to add a preview within a scrollbar we just push a series, e.g.:

```javascript
chart.scrollbarX.series.push(series);
```

However, removing a series' preview is not as straight forward.

E.g. removing a series from the scrollbar has no impact on its `scrollbarChart`:

```javascript
// where series.length is 1:
chart.scrollbarX.series.removeIndex(0);
chart.scrollbarX.series.length; // 0
chart.scrollbarX.scrollbarChart.series.length;  // 1
```

Example:

https://codepen.io/team/amcharts/pen/ef7ac57bd9a44a704d47d483d1859c9f

**Comment by Britford** [comment]
Any chance of reclassifying this as a bug since it is possible to add but not remove a series in a scrollbar?

**Comment by Christian-Adler** [comment]
See also error issue #1799

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
