### ISSUE TITLE
Replacing data while setting min/max not reliable using `invalidateRawData`

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#788]
I have a simple XY chart (x-axis and y-axis are value axes). I have a simple button that loops over the chart's `data` and sets every value to `0`. I also set `max` to 100. Then I call `invalidateRawData` to update the chart.

```
function clearData() {

  for (var i=0;i<192;i++) {
    mychart.data[i].value = 0;
  }
  yAxis.max = 100;
  mychart.invalidateRawData();
  
}
```

This works alright without using an (animated) theme, but when I enable the animated theme, the Y axis somehow thinks it needs to zoom in to near 0.

Demo 1 (invalidateRawData): https://codepen.io/team/amcharts/pen/vvrzwa?editors=0010

How to disable this automatic zooming when I explicitly set max to 100?

I have tried another approach to replace this data, which involves assigning a new array to `chart.data` at once. This does not have the same problem. It works witih animated theme too.

Demo 2 (replace data array): https://codepen.io/team/amcharts/pen/OrvPBV?editors=1010

What is the difference between these methods? Why does invalidateRawData with animated theme enabled zoom in to near-0 (while replacing `data` does not).

**Comment by martynasma** [comment]
Because `invalidateRawData()` is there specifically for the reason of animating existing data values.

Whereas `invalidateData()` is about throwing out current data and taking in new data.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
