### ISSUE TITLE
AxisRange/Guide: Is it possible to have strokes only at start and end?

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#790]
When I have an AxisRange/Guide on my date axis, is it possible, to have a (dashed) line/stroke at at start and end? If I use the `grid` property, I only get a line at the start. If I use `axisFill` I get strokes around the rect, but I don't want lines on top and bottom.

**Comment by martynasma** [comment]
No, I'm afraid. `AxisRange` has only one line element.

The only workaround would be to add a second `AxisRange` for the end-line.
