### ISSUE TITLE
XYChart tooltip overlap above scrollbar

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#791]
https://codepen.io/anon/pen/oJyKeW

Tooltips that are displayed above the scrollbar can overlap. See gif below.
(and tooltips being displayed on top of scrollbars is on purpose, right?)

![overlap](https://user-images.githubusercontent.com/23387905/50846896-40593900-133e-11e9-9b28-eb87a41d665f.gif)

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
