### ISSUE TITLE
XYChart series with no data shows bullet on initial load

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#792]
https://codepen.io/anon/pen/aPjowq

The last series generated has the following value specification:

`series.dataFields.valueY = "visits" + i;    // = "visits3", where i = 3`

"visits3" does not exist in the data assigned to the chart.
When the chart loads, this "visits3" series shows a bullet in the top left corner of the chart. Upon chart view changing (e.g. scroll or zoom), the bullet disappears. See gif below.

I would expect the chart to never show any bullets for a series with nonexistent data.

![gif](https://user-images.githubusercontent.com/23387905/50848346-07bb5e80-1342-11e9-8159-2edf3d4d6dd7.gif)

**Comment by Achilles1515** [comment]
@martynasma 
I think this issue can be closed...?? Maybe this was indirectly fixed at some point, because I am not able to reproduce the floating bullet in the top left in the codepen anymore.

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
