### ISSUE TITLE
Pie chart with pre-pulled slice(s) and non-default values

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#794]
What I'm looking to achieve is something similar to this [demo](https://jsfiddle.net/sassomedia/bj6ncsx7/); a pie chart with pre-pulled slices. One slice is selected upon first render. With any other slices selected afterwards, when new data sets are loaded, the selection remains after re-render. That all works fine.

However, that demo just uses the default values for the `active` state. In this [example](https://jsfiddle.net/sassomedia/r3fxwv1a/), if I change the props `scale` and `shiftRadius`, which I need for my design, the pre-pulling does not work anymore. Well, not completely. Generally, the state works except the `radius` property is not respected. Once rolled over the slices, the state with expanded radius is properly reflected. If I then click on any of the buttons to load a new data set, the "pulled" state/radius goes away again until rollover.

 I've tried to manually set these properties on the `active` state when assigning it but it does have no effect. I've also tried the ["Pie chart with pre-pulled slice(s)" tutorial](https://www.amcharts.com/docs/v4/tutorials/pie-chart-with-pre-pulled-slices/) and that does not work at all when `scale` and `shiftRadius` are changed. The state is not even set.

Is there anything else I could try or is this a bug?

**Comment by sassomedia** [comment]
@martynasma @zeroin do you guys have any suggestion here?

**Comment by martynasma** [comment]
Hey, sorry for the delay. We're dealing with a lot of questions :)

Quick thought: how about using a `"hoverActive"` state?

It's a build-in state name (although it is not created by default so you need to create it) which gets applied when you hover an element that is already active. It gets applied after both hover and active states, so you can combine the two properties.

Not sure if this will solve all of the issues, but might be a good next thing to try.

**Comment by sassomedia** [comment]
@martynasma ok thanks for checking. The issue isn't the `hover` or `hoverActive` state, they work fine, it's the `active` state that's not properly rendering. If you comment out line 109 & 110 in the example https://jsfiddle.net/sassomedia/r3fxwv1a/, you will see it working as expected. But with those lines present, it will not work. On render, that is.

The workaround I found is to set the state afterwards (changed the `setTimeout` from 0 to 1000) and then it works: https://jsfiddle.net/sassomedia/r3fxwv1a/60/. This actually does look kind of nice when you switch between the two DataSets.

So I have a workable solution for now but I still think that there appears to be a bug with those particular props. Might be good to look further into this when time permits. Thanks!

**Comment by martynasma** [comment]
OK, so I think what is going on.

This is caused by the initial animation. Since "hidden" state manipulates angles, when it plays out, the series manipulates radii of their slices, which overrides ones set by the "active" state.

At this moment I can't think of any other way to work around this than to update timeout in your `setTimeout` handler that pre-selects a slice to one that would make it kick in **after** initial animation has played.

Does that make sense?
