### ISSUE TITLE
Series still present after data reset

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#795]
Hello,

https://codepen.io/ptorrent/pen/KbBRmJ?editors=0010

Initial data = []
after 2s = [ array of data ]
after 4s = []

![flash](https://user-images.githubusercontent.com/6083644/50890285-30069400-13fa-11e9-8573-2e2a4a7e5b58.gif)

![image](https://user-images.githubusercontent.com/6083644/50891482-aad0ae80-13fc-11e9-8c7c-2e54643035f7.png)

**Comment by martynasma** [comment]
I can't seem to be able to reproduce it. Works fine for me, the whole cycle.

Can you try clearing your browser cache and retrying? We did something to fix similar issues in 4.0.17 released an hour ago.

**Comment by ptorrent** [comment]
I can reproduce it on chrome/opera after reseting browser cache :/

**Comment by martynasma** [comment]
OK, I was finally able to reproduce it as well.

Weird error, indeed.

Will let you know when it is fixed.

**Comment by BesoKakulia** [comment]
Hi, same error on MapPolygonSeries  data. 
![image](https://user-images.githubusercontent.com/26166174/50898672-509a1280-1429-11e9-86ab-57f4d26d6c22.png)

**Comment by zeroin** [comment]
This problem was fixed in v 4.0.23
