### ISSUE TITLE
Enhancement: collapse space reserved for null-value columns in a cluster

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#799]
Example:
https://codepen.io/dmsmaxim/pen/NeLrZw?editors=0010

Here some values of data points are commented, so columns don't have anything to show at these points. Nonetheless, space for these columns stays reserved. And it looks a little bit confusing. Especially it becomes annoying when there are many columns in groups and many of them don't have data to show.

Is it possible to drop these reserved spaces, so remaining columns in the groups could stretch out to the full width?

**Comment by martynasma** [comment]
No, I'm afraid.

**Comment by martynasma** [comment]
I'm going to leave this here, in case we decide to implement collapsing of empty space empty columns.

**Comment by martynasma** [comment]
At this point we won't be implementing this. Sorry.
