### ISSUE TITLE
Cannot export to CSV or JSON in Internet Explorer 11 or latest Edge

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#80]
Trying to export to either CSV or JSON using either Internet Explorer 11 or the latest version of Edge does not work. 

Clicking the export option doesn't throw any errors, but nothing happens.

You can see this example on the Export CodePen example:
https://codepen.io/team/amcharts/pen/gzgxZZ

Version: amCharts 4 beta 29

**Comment by martynasma** [comment]
Fixed in 4.0.0-beta.30. ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta30---2018-06-22))

**Comment by dswitzer** [comment]
Should exporting be working in IE 9 & 10? It's not for me, but I'm not sure if it's actually supported.

**Comment by martynasma** [comment]
I think data export doesn't work in those legacy browsers since they do not support binary downloads.

I'll have to verify that claim, though.

Will keep you posted.

**Comment by martynasma** [comment]
OK, I think I got to the bottom of it. Fixed in latest dev, to be released with the next official release.

Text-based data (CSV, JSON) downloads will now work down to IE9.

Binary formats (XLSX, PDF) will not.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.31](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.31).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by dswitzer** [comment]
Good work! It appears to be working correctly now.
