### ISSUE TITLE
minGridDistance ignores year label on DateAxis

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#800]
Here's an example: https://codepen.io/npc42/pen/gZdLeE

Looks like DateAxis only shows year on year changes (Jan), but that label's width is ignored when it attempts to calculate # of labels to show and respect minGridDistance — thus causing overlap.

**Comment by martynasma** [comment]
To me, everything seems good to me on the chart.

You have `minGridDistance` set at `30`. The grids come at ~36px now, so `minGridDistance` is not violated.

It's a distance between grid elements, not between labels, which are not checked against overlapping.

However, year label does not fit into 36px. You have two options here:

1) Increase your `minGridDistance`.
2) Change `periodChangeDateFormats` to show only year (without month) for the year label:

```
  "xAxes": [
    {
      "dataFields": { "category": "MONTH" },
      "id": "category_axis",
      "type": "DateAxis",
      "renderer": { "minGridDistance": 30 },
      "cursorTooltipEnabled": true,
      "periodChangeDateFormats": {
        "month": "yyyy"
      }
    }
  ],
```

**Comment by NPC** [comment]
@martynasma Aha, that makes sense, thank you. I misunderstood the meaning of the setting, even though it is clearly named.

I am more concerned about category labels now. They are dynamic and could be anything. I hoped V4 offered a nice way to handle overlap automatically — in V3 I had to use a lot of tinkering on top (guess label widths, define grid frequency, render, check actual label width, update grid frequency, re-render). I guess I'll have to use a similar approach with the new version too.

**Comment by NPC** [comment]
Oh, this may help, nevermind: https://www.amcharts.com/docs/v4/tutorials/wrapping-and-truncating-axis-labels/

Thanks again for your help.
