### ISSUE TITLE
Overlapping tooltips with series with gaps

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#803]
Example: https://codepen.io/anon/pen/wREbmb
When you have series with gaps, and hover the chart at the gaps position (and have a cursor and series tooltips), the tooltips overlap, if the dataitems are to close to each other.
In the example, you can reproduce that, by entering the chart at 1991 with the mouse. If it fixes itself, you can reset it, by hovering the button in the left top corner (which only highlights all series).

By the way, I would suggest, if there are as much tooltips, that they overflow the charts drawing area, they should be aligned top, to save space, so you can see as much tooltips as possible, like in amCharts 3.
At the moment only overlapping tooltips start aligning under each other, even if there is enough space above.

**Comment by martynasma** [comment]
![image](https://user-images.githubusercontent.com/1458520/51037839-072cfd00-15ba-11e9-82be-7c9aedc692aa.png)

**Comment by zeroin** [comment]
This issue was fixed in v 4.0.23

**Comment by CipSoft-Components** [comment]
This fix breaks the tooltips, when using bullets, see #913
