### ISSUE TITLE
Updating data on chart with ColumnSeries results in an error

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#804]
Example:
https://codepen.io/team/amcharts/pen/dac4be245d658233a6d7e5597df2208b?editors=0010

**Comment by martynasma** [comment]
Fixed in [4.0.20](https://github.com/amcharts/amcharts4/releases/tag/4.0.20).

## [4.0.20] - 2011-01-11

### Fixed
- Chart with `ColumnSeries` was failing with an error when `data` was updated.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by pumano** [comment]
Fixed, I test it on 4.0.21
