### ISSUE TITLE
Adding a MapLine on zoomed MapChart ignores nonScalinStroke=true until zoom

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#806]
10px `strokeWidth` line is added on a `MapChart` zoomed to `zoomLevel = 5`. Stroke looks like `10px * 5`:
![image](https://user-images.githubusercontent.com/1458520/51035261-1b6cfc00-15b2-11e9-8490-25ce003a7c28.png)

Same map is zoomed a bit. Line reverts to proper stroke width.
![image](https://user-images.githubusercontent.com/1458520/51035288-317abc80-15b2-11e9-93e9-81962c2c95f6.png)

Example:
https://codepen.io/team/amcharts/pen/f3bb9e2a5c9216570e1feff387337212?editors=0010

**Comment by notacouch** [comment]
This still happens when applying styles to `mapLines.template.line` instead of `mapLines.template` directly:
https://codepen.io/team/amcharts/pen/afcbe3265ff8d2a63e246203afc3786d

![mapline-stroke-zoom-bug](https://user-images.githubusercontent.com/2334143/52029954-8e97cd00-24e3-11e9-8100-93c0571b0266.gif)

**Comment by martynasma** [comment]
Fixed in [4.1.2](https://github.com/amcharts/amcharts4/releases/tag/4.1.2).

## [4.1.2] - 2019-02-05

### Added
- New `Sprite` property `strokeDashoffset` added. Can be used in conjunction with `strokeDasharray`.
- `Label` has two new properties: `path` and `locationOnPath`. If set, will layout the SVG text along a curvature of the SVG path. HTML and multi-line text is not supported.
- `AxisLabelCircular` new property `bent` added. If set to `true`, the label will be bent to follow the curvature of the circle. Distance from the circle can be adjusted using `radius` and `label.paddingBottom`. For `PieSeries` the alignLabels need to to be set to `false` for this feature to work.

### Fixed
- JSON: Having property values with both percent and minus signs in them, was resulting in error.
- "Z" code in `DateFormatter` was not taking UTC setting into account.
- Exporting SVG with Unicode characters in Edge/IE was resulting in invalid SVG.
- Fixed JavaScript error which used happen when disposing chart/changing data in some cases.
- Gantt chart sometimes was not displaying first/last data item.
- Newly added `MapLine` elements were not respecting `nonScalingStroke = true` until zoom level changed.
- Series' tooltip was not always visible with `DateAxis`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
