### ISSUE TITLE
Labels not aligned when axis is scaled

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#809]
This is a follow-up ticket from #707.

In case the axis spans multiple days / months / years and the label template of the axis has a location set, such as `dateAxis.renderer.labels.template.location = 0.5`, the label is aligned only within the part of the scaled axis that belongs to this month, e.g. it's centered in the first third of the scaled axis.
I can see the reasoning behind this in #707, however it looks rather strange and it would be great if this behavior could be made configurable, whether we want the label template location to relate to the whole span or only to its entry in the axis.
The issue can be reproduced in https://codepen.io/chnoch/pen/JwKedJ, depending on screen size.

**Comment by martynasma** [comment]
Thanks for posting this. This is a topic well worth discussing.

We'll ping you once we're ready to do that.

**Comment by martynasma** [comment]
Sorry for bringing out zombie threads, but `dateAxis.renderer.labels.template.location` will now work in all setups.
