### ISSUE TITLE
Print does not work properly in IE11

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#81]
Printing in Internet Explorer 11 is not working properly. It appears to be printing the entire viewport. 

Go to the following example:
https://codepen.io/anon/pen/aKEoRJ

If you use the "Print" option on the export menu it will prevent everything in the viewport, including the CodePen source code layers.

NOTE: Trying to export to a PDF using the Microsoft PDF print driver, results in an empty PDF.

Version: amCharts 4 beta 29

**Comment by martynasma** [comment]
Fixed in 4.0.0-beta.30. ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta30---2018-06-22))

**Comment by dswitzer** [comment]
This fix broke printing in Firefox. Printing working in beta 29, but no longer works. 

I can see the DOM height change very briefly, but I get no print dialog and there are no errors.

**Comment by martynasma** [comment]
Gah. Indeed :(

Reopening this.

**Comment by martynasma** [comment]
OK, fixed this in dev. Will roll into next release.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.31](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.31).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by dswitzer** [comment]
Good work! It appears to be working correctly now.

**Comment by srajanish** [comment]
image export is not working in IE properly,i'm trying to export the chart with transparent background but it's exporting as a black color background in IE,its working fine in chrome .Please give some solution for this issue.
