### ISSUE TITLE
When I create a new am4charts.LineSeries there is no tensionX, tensionY property

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#812]
Hi I create a line series via: 

```
    series = this.chart.series.push(new am4charts.LineSeries());

```

However, I get back a XYSeries that has no tensionY,X props. 

The same happens if I do: 

```
 series =new am4charts.LineSeries();
```

What is going on?

**Comment by martynasma** [comment]
Not sure what you mean. Both `tensionX` and `tensionY` are set in `LineSeries` constructor, so there's absolutely no way they can be set when you instantiate them.

Do you have a demo code?

**Comment by jimmykane** [comment]
Ok let me ask it differently. How can one modify the tension of a series?

**Comment by martynasma** [comment]
Ummm... you set it to a number that's less than 1 :)

```
series.tensionX = 0.8;
```

https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Smoothed_lines

1 (default) means maximum tension, e.g. line is perfectly straight.

When you lower this number, you start relaxing the tension, hence waves starting to appear.

**Comment by jimmykane** [comment]
That is what I try to do but the series does not have that property exported.

**Comment by jimmykane** [comment]
example 
![screenshot 2019-01-14 at 14 01 23](https://user-images.githubusercontent.com/1268723/51114213-eb696700-1804-11e9-8a65-5e7c8e08e0d3.png)


And that is because  when you create a series the return object does not have that property

**Comment by martynasma** [comment]
Is your app in TS?

What IDE are you using?

Below is what I get in a TS app in Sublime Edit:

![image](https://user-images.githubusercontent.com/1458520/51114321-a0a01d00-180d-11e9-98e3-135a7069e6ca.png)

**Comment by jimmykane** [comment]
It's also missing from the DOCs https://www.amcharts.com/docs/v4/reference/xyseries/

Webstorm + pycharm

**Comment by martynasma** [comment]
Those are properties of `LineSeries`, not `XYSeries`.

https://www.amcharts.com/docs/v4/reference/lineseries/#tensionX_property
https://www.amcharts.com/docs/v4/reference/lineseries/#tensionY_property

I suppose this might be an issue of the IDE. Although, it's just a guess. I have never used similar setup as yours.

If your tools have a strong community or support, maybe you can try your luck on their forums?

**Comment by jimmykane** [comment]
Ok but it's strange. Because when I add a Lineseries to the chart I get back an XYseries. 
I add a line series as you can see.

**Comment by jimmykane** [comment]
![screenshot 2019-01-14 at 14 19 00](https://user-images.githubusercontent.com/1268723/51115052-6a5f9f00-1807-11e9-9a4a-2a3f73ac54e9.png)
Somehow the chart sets all inserted series to XYSeries . I think that is the issue of this.

**Comment by jimmykane** [comment]
Ok look I found it. This happens when I create a XYChart. Should I not be doing that ? 

I declare my chart as `private chart: am4charts.XYChart;`

**Comment by jimmykane** [comment]
If my assumption is correct then every XYchart that we create we cannot change the tension. 
Should we be using another chart? Is tension not for XYcharts?

**Comment by martynasma** [comment]
I don't know :/

I still think that your IDE is having issues in how it is treating generics. Could be a configurable thing.

Besides, that does not explain why you would not get `tensionX` if you create a standalone instance of `LineSeries`, unless you type your `series` variable to `XYSeries` as well.

**Comment by jimmykane** [comment]
Ok thanks. Perhaps last question, what is the diff between an XYSeries, a LineSeries and XYChart or Chart? What should be one be using when creating a chart and a series?

**Comment by jimmykane** [comment]
Ok I doublechecked @martynasma . There is something confusing. 

When you push a `LineSeries` to an `XYChart` the series return are always XYSeries due to the type of the chart I suppose. Thus there is no way to set the tension (or at least that is what the editor thinks). 

I am not sure if it's a big issue but it's rather confusing. 

Part of the source that does this: 


```
 /**
     * A list of chart's series.
     *
     * @return {List} Chart's series
     */
    readonly series: ListTemplate<this["_seriesType"]>;
```

Due to using a `SerialChart` class 

Or am I super confused here?

**Comment by jimmykane** [comment]
@Pauan  good tip about 
> So regardless of the type of series, if you use series.push(new am4charts.LineSeries()) then it will always return a LineSeries


the let / const declarations I have intentionally omitted those. No worries.

**Comment by jimmykane** [comment]
@Pauan  actually no: 

When you push a series on the chart it will return the charts internal type of series and that is the probnlem here.

**Comment by jimmykane** [comment]
Chart series is a ListTemplate 

```
  /**
     * A list of chart's series.
     *
     * @return {List} Chart's series
     */
    readonly series: ListTemplate<this["_seriesType"]>;
``` 

And on XY chart the internal series is 

```
  /**
     * Defines a type of series that this chart uses.
     *
     * @type {XYSeries}
     */
    _seriesType: XYSeries;
```

So that is the problem I am trying to reference here

**Comment by jimmykane** [comment]
Another problem with this generic as seen above 

```
  /**
     * A list of chart's series.
     *
     * @return {List} Chart's series
     */
    readonly series: ListTemplate<this["_seriesType"]>;
```
 

IF I do 

```
      const sameTypeSeries = this.chart.series.values.find((serie) => serie.name === stream.type);

``` 

I will (and I believe your editor as well) return a type of XYSeries. 

Can you validate that @Pauan  for example ?

**Comment by martynasma** [comment]
I don't think we can do anything here. At least not quickly :(

As @Pauan suggested, push method always returns the same object of the same type that was pushed.

So it's a matter of configuration/support of the particular IDE or your environment.

**Comment by Pauan** [comment]
> the let / const declarations I have intentionally omitted those. No worries.

The reason I mention it is because every variable can only have one type.

So if your `series` variable is defined as a different type (which isn't `LineSeries`), then it won't work.

But if you use `let`/`const` to make a new variable, then it might work.

> Doing Push on that series ListTemplate will return the type of that series ListTemplate as seen here

If `push` returned `T`, then you are right that it would return `XYSeries`.

But it doesn't return `T`, it uses `K extends T` and then returns `K`. That is done specifically to ensure that it always returns the input type (regardless of what type the Series is).

So it sounds like your editor is simply incorrect, and cannot handle perfectly valid TypeScript code. I recommend filing a bug report with them.

> I will (and I believe your editor as well) return a type of XYSeries.

Yes it will return an `XYSeries`, because that's what the `find` method was designed to do:

https://github.com/Microsoft/TypeScript/blob/3a2f6a3ed1a598a241e7c750873105f22e7a2463/src/lib/es2015.core.d.ts#L12

But that's not the same situation as `push` (which always returns its input type).
