### ISSUE TITLE
How to change line style

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#815]
Hello,

How to change lineSeries styles (JSON config) ? I mean dotted or dashed line ?

I didn't found something about that in the documentation.

Thanks for support

**Comment by martynasma** [comment]
[`strokeDasharray`](https://www.amcharts.com/docs/v4/reference/lineseries/#strokeDasharray_property) is responsible for modifying line appearance.

```
series: [{
  type: "LineSeries",
  strokeDasharray: "3,3"
  // ...
}]
```

This will make the line dashed.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
