### ISSUE TITLE
How to get zoomed min & max of value axis after selectionextremeschanged/rangechangeended?

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#816]
I am trying to obtain visibile start and end values on value axis after the value axis has been zoomed.

For animated themes, I can use `rangechangeended` event on Value Axis:

```
valueAxis.events.on("rangechangeended", function(ev){
  console.log('MIN & MAX', ev.target.minZoomed, ev.target.maxZoomed);
});
```

For non-animated themes, I can use `selectionextremeschanged` event on Value Axis:

```
valueAxis.events.on("selectionextremeschanged", function(ev){
  console.log('MIN & MAX', ev.target.minZoomed, ev.target.maxZoomed);
});
```

However, `minZoomed` and `maxZoomed` do not always return reliable results. Sometimes the grid starts at a different value than what is mentioned in these props.

Codepen demo: https://codepen.io/team/amcharts/pen/LMMKjz.

Screenshots:

![amcharts-both-min-max-not-ok-on-zoomin-rangechangeended-minzoomed-maxzoomed](https://user-images.githubusercontent.com/13300227/51115533-d4c50f00-1808-11e9-817d-ebfcd967511a.png)

![amcharts-maxzoom-not-ok-on-zoomin-rangechangeended-minzoomed-maxzoomed](https://user-images.githubusercontent.com/13300227/51115536-d7bfff80-1808-11e9-9d37-45a7f8d67818.png)

**Comment by martynasma** [comment]
If you are using this with an `XYCursor` you can use its properties to find out precise values via cursor's `yRange` and converting them to real values as it is described here:

https://www.amcharts.com/docs/v4/tutorials/tracking-cursors-position-via-api/

**Comment by Albhaku** [comment]
Please. Can't find it anywhere. Really need to get only displayed data. (I mean, visible, when zoomed)
