### ISSUE TITLE
Request: Auto-width legend

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#817]
Currently legend width can only be fixed (for right/left position). As discussed in #518, it would be nice to include a setting for dynamic auto-width.

**Comment by NPC** [comment]
@martynasma can you please recommend a reliable way to measure legend content width? In #360 you mention legend.contentWidth, but for me it returns value of legend.width (probably because labels are truncated as an individual element before inserted into legend).

Here https://codepen.io/npc42/pen/MZNgpe I try all approaches I could think of, namely:
1. legend.itemContainers max outerWidth
2. Max legend.labels width + max of legend.markers.width + max of legend.valueLabels.width (also, sum of max .contentWidth for them, hoping it'd include actual label width, but nope)
3. Max of legend.itemContainer's sum of .children outerWidth

2nd approach seems to return the highest value, but it is still not enough, by a large margin. so I'm definitely missing something.

**Comment by NPC** [comment]
Also, even though width is set to 80 in the above codepen, the label width is 90, and actual legend with is 118…

**Comment by NPC** [comment]
@martynasma Agreed, it looks scary, but it works well for me. Thank you for this workaround!

**Comment by martynasma** [comment]
Auto-width legend has been implemented in 4.8.0.

More details here:
https://www.amcharts.com/docs/v4/concepts/legend/#Sizing_vertical_legend
