### ISSUE TITLE
Request: Tooltip for truncated label text

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#818]
In #518 this is discussed in context of truncated legend labels, but probably makes sense for all truncated labels (axis etc). Even a simple tooltip (using "title" attribute) would be much better than nothing.

**Comment by martynasma** [comment]
Now that I'm thinking about it, this is already possible:

```
chart.legend.itemContainers.template.tooltipText = "{category}"
```

https://codepen.io/team/amcharts/pen/ZVwLYz?editors=0010

**Comment by NPC** [comment]
@martynasma that helped, thank you!
