### ISSUE TITLE
Issue on FF45, Angular, Column states

### ISSUE THREAD

**Issue by FrankMerema** [amcharts/amcharts4#822]
For indication of the selected (active item) I need to show a kind of blur around the column. This I have done using column states. On Chrome this is working perfect, but I need to support FF45 where its broken.

I have created an example to show the issue:
https://gantt-chart-active-item-bug.stackblitz.io/dashboard

On Chrome if you click on a Column Item it will show a green blur around and when you click an other it will delete the blur from the other and set the clicked item active again. But on FF45 the active item disappears. When selecting an other item, that one will disappear also...

Hopefully you have a solution for this issue.

**Comment by RobbiesCode** [comment]
Hi Frank,

Do you have your chart config somewhere? All I see is minified JS files, which makes it a little hard for me to trace where this comes from. What are you using for the green blur? An SVG filter?

**Comment by martynasma** [comment]
Does the issue happen outside Angular? If it does, can we rule out states by trying to apply same blur effect on series columns directly, not via state on FF45?

Yes, we can test all of that ourselves, but it will help us a lot and speed things up if you can do some heavy lifting in testing.

**Comment by FrankMerema** [comment]
There is again a relation with angular. I have extracted the code to a blank typescript project and it works fine. So again I think it has a relation with Angular and the router maybe? But the same issue occurs on Safari webkit.

Option 2 I would like to try but do you have an example or something so I can investigate that approach?

Thanks for the suggestions (and I am happy to help you guys with these issues :) )

**Comment by jimmykane** [comment]
I have the same issues. Is #841  related?

**Comment by FrankMerema** [comment]
@martynasma any updates on this one?

**Comment by martynasma** [comment]
@FrankMerema Not yet. Sorry. This is turning more complicated than it should.

Seems related to @jimmykane #841. Make sure you subscribe that issue as well, just in case.

**Comment by FrankMerema** [comment]
@martynasma Thanks for the reply!

I was indeed watching that issue already ;) Only question is that you suggest an other solution to try. Can you give a small example how it should be implemented/work?

**Comment by FrankMerema** [comment]
Tested it and I confirm that it's fixed in 4.1.5!

**Comment by martynasma** [comment]
Folks, just released 4.1.5 which should fix the issues with Angular and Safari/FF45.

At least it's so in our tests.

I'm gonna go ahead and close this, but feel free to reopen if you're still seeing issues after upgrading.
