### ISSUE TITLE
Removing SeriesRange does not restore original line series

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#823]
I have an XY chart with a date axis (X) and a value axis (Y). It is a regular line chart.

When I zoom in the chart, I add a Series Range like this:

```
  // Create a series range
  var range = dateAxis.createSeriesRange(series);
  range.date = new Date(startDate);
  range.endDate = new Date(endDate);
  range.contents.stroke = am4core.color("#f00");
  range.contents.fill = am4core.color("#f00");
  range.contents.fillOpacity = 0.5;
```

When I zoom out, I want the Series Range to be gone:

```
  while(dateAxis.axisRanges.values.length){
    dateAxis.axisRanges.removeIndex(0);
  }
```

When the Series Range is removed, the original line series is not restored. The line that was originally "behind" the Series Range is invisible. It looks like there is still a mask applied, or something.

Here's how it looks:

![image](https://user-images.githubusercontent.com/13300227/51173526-e6b0bb80-18b5-11e9-83b0-a3d01c0a8458.png)

Here's the HTML file: [linechart3-github.zip](https://github.com/amcharts/amcharts4/files/2759099/linechart3-github.zip).

To reproduce this issue, click "click to zoom" button first, then click "remove ranges".

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
