### ISSUE TITLE
Display issue of bars in StepLineSeries

### ISSUE THREAD

**Issue by evead** [amcharts/amcharts4#827]
There is an issue with display of bar in StepLineSeries, this issues does not happen on every load, but it happens around 1 out of 5.

![image](https://user-images.githubusercontent.com/4017030/51184666-e7088100-18cc-11e9-89bf-ee8bd196e1ae.png)

In our example, we update the data (very small amount of data) once every 10 seconds. However, the problem happens on the first load and even after the update of data (using invalidateRawData).

**Comment by martynasma** [comment]
Would you be able to post your chart config/data so that we can test your precise setup?

Also, does this happen in all browsers?
