### ISSUE TITLE
Exporting chart to Excel that has colon in title leads to an error

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#83]
When trying to export a chart to Excel that has a colon in the title (i.e. `chart.exporting.title = "Chart: Titles with colons cause errors";`) leads to the file that is generated being corrupted. This happens in all browsers. I've only tested opening the file up in the latest version of Office 365 (i.e. "Excel 2016 MSO (16.0.9330.2124) 32-bit"). 

When opening the file you see the following error:

> We found a problem with some content in `XXXXX.xlsx`. Do you want us to try and recover as much as we can? If you trust the source of this workbook, click Yes.

If you click "Yes", the file does open. 

You can see this behavior here:
https://codepen.io/anon/pen/zapYEp

I suspect this probably due to the fact that setting the `exporting.title` is trying to name the Sheet the same thing. If this is the case, then the sheet name should be sanitized.

Version: amCharts 4 beta 29

**Comment by dswitzer** [comment]
This comment looks like it might be related to the issue:

https://github.com/SheetJS/js-xlsx/issues/376#issuecomment-284465165

**Comment by dswitzer** [comment]
I tried encoding the string as mentioned in the above comment, but that doesn't work for me. As a temporary fix, I'm just stripping out the following characters:

* :
* \
* /
* ?
* \*
* [
* ]

**Comment by martynasma** [comment]
Looks like it's an Excel limitation.

We've added a workaround to automatically gracefully truncate sheet names as well as replace forbidden characters.

Will be rolled into next version. (available later this week)

**Comment by martynasma** [comment]
Fixed in 4.0.0-beta.30. ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta30---2018-06-22))

**Comment by dswitzer** [comment]
Things look to be working correctly now.

Thanks!
