### ISSUE TITLE
Pie Chart 3d labels not centered

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#831]
I am trying to display a simple 3d pie chart that has labels inside the slices:

```
  series.labels.template.disabled = false;
  series.ticks.template.disabled = true;
  //series.alignLabels = true;
  series.labels.template.inside = true;
  series.labels.template.radius = am4core.percent(40);
```

However, as seen on the screenshot, the labels are not centered:

![image](https://user-images.githubusercontent.com/13300227/51252054-1daccd00-199b-11e9-9518-8412e9290e72.png)

Codepen demo: https://codepen.io/team/amcharts/pen/5b09f9484f887579198dd2e565d0712a?editors=1010

**Comment by zeroin** [comment]
This was fixed in v 4.0.23, but you need to explicitly set `alignLabels = false`, as default is true.
