### ISSUE TITLE
Question: Flow chart on map

### ISSUE THREAD

**Issue by Ices-Eyes** [amcharts/amcharts4#838]
Hi all, I'm starting playing a bit with this library, and I see it is possibile to have lines on map. I was wondering if it is possible to make flo charts (or origin destination maps), where each line width on the map is proportional to a value. I've not find any such example in the documentation.
Thanks :)

**Comment by notacouch** [comment]
Hi!

It is certainly possible to have `MapLine`s' width proportional to a value by [binding data to property fields](https://www.amcharts.com/docs/v4/concepts/data/#Property_fields).

Take our [Map With Curved Lines demo](https://www.amcharts.com/demos/map-with-curved-lines/) for example, by adding a field to our data, we'll just call it `value` in this case but it can be anything, we can bind it to the map lines' width like so...:

```javascript
lineTemplate.arrow.propertyFields.strokeWidth = "value";
lineTemplate.propertyFields.strokeWidth = "value";
```

...and the lines/arrows will become as wide as you specify.

Here's a demo with the above and some `value`s in the data I punched in arbitrarily:
https://codepen.io/team/amcharts/pen/a3b9cc4efaec7eb5eb0c2ca38781d888

I get that that's not actually _proportional_. If a 1:1 relationship doesn't cut it, we can use [an adapter](https://www.amcharts.com/docs/v4/concepts/adapters/). Let's say in the above example the `value`s are 10 times larger, meaning we'd want the widths to be 1/10th that size, and let's say we want the arrows to be slightly thicker than their lines. Here's what that code could look like:

```javascript
lineTemplate.adapter.add("strokeWidth", function(width, target) {
  // If data is ready, exists, and there's a value (incl. zero),
  // return proportional width, also adjust arrow while we're at it.
  if (
    target.dataItem &&
    target.dataItem.dataContext &&
    typeof target.dataItem.dataContext.value !== "undefined"
  ) {
    width = target.dataItem.dataContext.value / 10;
    // Update arrow, make it a little thicker than the line
    target.arrow.strokeWidth = width + 3;
  }
  return width;
});
```

And another demo to go along with that:
https://codepen.io/team/amcharts/pen/763a28b74df366d50505ea1649512f89

What do you think? Does this help for your purposes?

**Comment by Ices-Eyes** [comment]
Hi, thanks for the answer. Wasn't realising it should be as easier as to tide the width with the value property in the data. In my case the proportional part isn't that simple, but I can handle it in the backend by reproportionating the data, that has a lot of variation and very large numbers to a good interval of the width properties. But that should not be a problem at all... So thanks :)

**Comment by Ices-Eyes** [comment]
I've been able to reproduce on my end the solution, but facing two different problem that I do not understand.
My data come from a json, so I think to load the data with
`lineSeries.dataSource.url = "myUrl";`
But either if I see the file downloaded in the chrome network panel, then lines do not appear on the graph, and there are no errors in the console. Any tip? If instead of a json i use a javascript object making it read from a script, it works.

Also, the file shoulld contain around 900 lines definition in the form of
``
    [ { from:"aaa" , to:"bbb" , value:44 , multiGeoLine:[[ {longitude:11.7958 , latitude:45.0696 }, {longitude:11.4033 , latitude:45.0898 } ]]}
``
With different starting and ending points. There are about 7 different starting point and many ending points. Btw, when I load all the dataset, I obtain an error in the console, and no lines appear.
`Error: EventDispatcher is disposed
    at e.t.isEnabled (core.js:1)
    at e.Vs7R.e.setPropertyValue (core.js:1)
    at e.set [as segments] (core.js:1)
    at e.QJ7E.e.validate (maps.js:1)
    at maps.js:1
    at core.js:1
    at core.js:1
    at Object.Wglt.e.each (core.js:1)
    at e.QJ7E.e.validate (maps.js:1)
    at core.js:1`

Any tip for this too? :)

**Comment by notacouch** [comment]
Can you provide both the working/not working code samples along with some sample data? If we can replicate the problems it can really help.

If you want to demo dynamic json, [CodePen supports that by just referring to the url with a `.js` at the end](https://blog.codepen.io/2018/05/04/say-you-need-to-get-set-some-json-data-from-a-pen/). So e.g. create a pen with json in its js file, save that, now that js file will be served as json if just referring to the pen url + `.js`.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by yasenm** [comment]
@Ices-Eyes 
Hey saw this post and we had same issue on our end. A fix to handle more than 109 is needed that is clear. But you can do a workaround for the time being. What we did is actually add more than one maplinesseries and push 109 entries in each.


           `let iteration = 0;
            for (let i = 3; i < this.chart.series.values.length; i++) {
                if (iteration > this.graphConnections.length) break;

                const lineSeries = this.chart.series.values[i] as am4maps.MapLineSeries;
                const connections = this.graphConnections.map(x => {
                    return { 'multiGeoLine': x.multiGeoLine };
                }).slice(iteration, iteration + 109);

                iteration += 109;

                lineSeries.data = connections;
            }`

Our line series start from the 3th index. Hope that helps
