### ISSUE TITLE
Question: Load data and chart config from json url

### ISSUE THREAD

**Issue by Ices-Eyes** [amcharts/amcharts4#839]
Hi, I've seen it is possible to load data via external json, and also to load configuration via json and probably external json. But is it possible to load both of this? I mean, I'm trying to load new data into a graph, but the data could have different granularity or so, and then i need to change maybe the axis labels, the title, the variable to witch a series refer to. Is it possible to obtain something like this?

Thanks!

**Comment by martynasma** [comment]
Before we jump into deeper details, are you trying to:

a) create a new chart with all of the config and data or...
b) update some options of the data along the data?

For the record, both are possible with our JSON loader, just with a bit different approach.

**Comment by Ices-Eyes** [comment]
Well, I was trying to achieve the second one, primarily to change series labels and other options...

**Comment by martynasma** [comment]
OK, thanks. So you should be able to load your data and config updates using standalone `DataSource` object.

E.g.:

```
var ds = new am4core.DataSource();
ds.url = "updated/data/url.php";
ds.events.on("done", function(ev) {
  chart.config = ev.data;
});
ds.load();
```

The actual data/config should be JSON object resembling chart config, e.g.:

```
{
  data: [....],
  series: [{
    name: "New series name"
  }],
  xAxes: [{
    title: "New X axis title"
  }]
}
```

The following article explains about JSON config:
https://www.amcharts.com/docs/v4/concepts/json-config/

Hope you find it useful.

**Comment by Ices-Eyes** [comment]
Ok, so just to check if I correctly understand the point here, I need to use an external data source (but maybe it should work also with the internal one...) and update the config prop of the graph when the data has been collected. Good, will make some tries, eventually will update if I find out some problems.

Thanks!!!

**Comment by martynasma** [comment]
Correct. The JSON object does not necessarily has to come from DataSource. You can load (or have it built in) any way you like.
