### ISSUE TITLE
Cannot export to Excel if exporting.title exceeds 31 characters

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#84]
If you try to create a chart and the chart title exceeds 31 characters long, you get the following JavaScript exception:

> Error: Sheet names cannot exceed 31 chars

The sheet name that amCharts creates should be cropped to 31 characters.

You can see this behavior here:
https://codepen.io/anon/pen/GGygKp

Version: amCharts 4 beta 29

**Comment by martynasma** [comment]
Related to #83. Fixed in next version.

**Comment by martynasma** [comment]
Fixed in 4.0.0-beta.30. ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta30---2018-06-22))

**Comment by dswitzer** [comment]
Things look to be working correctly now.

Thanks!
