### ISSUE TITLE
Hovering over chart causes jerkiness in a flexible UI in Firefox

### ISSUE THREAD

**Issue by ailon** [amcharts/amcharts4#840]
Hi,

I've constructed a UI with CSS Grid (not sure if this is the main culprit causing the behavior). Chart div occupies the biggest part of the UI and everything is fine in Chrome and Edge. But in Firefox (64.0.2 on Windows 10) when I hover over the chart it causes scrollbars on the page to constantly appear and disappear which results in the whole UI jumping around.

I've tried to create a repro in Codepen but couldn't reproduce the behavior at first. However, I later noticed that if I resize the window after loading the pen and then hover over the chart the issue surfaces.

Here's the pen: https://codepen.io/ailon/pen/vvwXEe

Resize the preview pane a bit and then hover over the chart area to see the glitch.

Alan.

**Comment by ailon** [comment]
Doesn't seem to happen when using flexbox instead of CSS Grid https://codepen.io/ailon/pen/maYrOx

**Comment by martynasma** [comment]
Doesn't seem to be happening anymore.
