### ISSUE TITLE
Redrawing in same div, breaks cursor of chart with axis ranges and adapter on their axisFill

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#842]
I have `div` element I'm drawing my charts into. The charts have axis ranges, with `axisFill`s with tooltips. The tooltips are activated with `interactionsEnabled = true`. The tooltips content comes from the adapter `tooltipHTML`. `hoverable` is also set to true, and `tooltipPosition` is set to "pointer". The cursor has set its event `cursorpositionchanged`.
After fresh loading of the page with an initial chart, everything works fine. After redrawing new charts into the `div` element, it works fine for a couple of time (around 2 to 4 times). Then it breaks with the following error message/stacktrace in the console:
```
Sprite.ts:8061 Uncaught TypeError: Cannot read property 'SVGContainer' of undefined
    at Sprite.ts:8061
    at Object.dispatch (EventDispatcher.ts:446)
    at EventDispatcher.ts:326
    at Object.e.each (Array.ts:95)
    at e.t._eachListener (EventDispatcher.ts:296)
    at e.t.dispatchImmediately (EventDispatcher.ts:324)
    at e.handleTrack (Interaction.ts:1772)
    at Interaction.ts:1742
    at Iterator.ts:102
    at List.ts:71
```
By debugging, I can say, that `this` at this point is an `axisFill`. The event itself is of type `track`. In my code I never use this event, so it must be something intern of amCharts.

**Comment by CipSoft-Components** [comment]
I also figured out now, that it only happens, if I hover the guides with the mouse, so that the tooltips are displayed. After that, when drawing a new (or the same) chart into the element, the cursor is broken, and I get the error message.

**Comment by RobbiesCode** [comment]
I have played around with your demo for a bit and it seems that you are right. The error message is raised after creating a new chart, but only when `axisRange.axisFill.showTooltip(...)` has been called.

Before proceeding, I am curious about the why of this event listener. The tooltip is shown already by default. If you leave out your `cursorpositionchanged` listener, nothing changes. The tooltip will still display inside your range.

Not saying that anything you do here is wrong per se, but it would help if I could understand what you are trying to achieve.
