### ISSUE TITLE
Custom images on value axis

### ISSUE THREAD

**Issue by evead** [amcharts/amcharts4#843]
Is it possible to have custom images on value axis like in Amcharts 3 : http://jsfiddle.net/kpq1xfyr/1/

I tried to put the icon in my data variables, but it looks like you unescape the value, so it replaces the '&' by '&amp;' : 

```
// Add data
chart.data = [{
  "category": "&eacute;t&eacute;</i>",
  "value": 450
},....
```

**Comment by RobbiesCode** [comment]
I think you could recreate something like that using bullets. Take this demo as a starting point: https://www.amcharts.com/demos/column-chart-images-top/.

These emojis are actually the bullets that belong to the series. They're automatically positioned at the top of the column. You could create another series, an invisible line chart, just to display the images. The value for each series data item would be simply 0, to position the images at the bottom.

I modified the official demo a bit and this is what you end up with: https://codepen.io/team/amcharts/pen/449be62b1bf309e736f2cc0f439b03f1?editors=0010.

```
// Create line series (just for the sake of displaying images)
var series2 = chart.series.push(new am4charts.LineSeries());
series2.dataFields.valueY = "points2";
series2.dataFields.categoryX = "name";

// Add bullets to this line series
// adjust vertical position using dy
var bullet2 = series2.bullets.push(new am4charts.Bullet());
var image2 = bullet2.createChild(am4core.Image);
image2.horizontalCenter = "middle";
image2.verticalCenter = "bottom";
image2.dy = -40;
image2.y = am4core.percent(100);
image2.propertyFields.href = "bullet";
image2.propertyFields.fill = "color";
image2.filters.push(new am4core.DropShadowFilter());
```

**Comment by jakeleventhal** [comment]
@martynasma the suggested solution is not really sufficient. Something like what OP asks for is definitely what is needed. Especially custom rendering so that other things can be placed like tooltips, etc.

**Comment by martynasma** [comment]
Found this old thread. You might find this useful:
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_bullets

**Comment by shubham708** [comment]
Thanks @RobbiesCode. 
somehow `image.href="iconproperty;" `was not accepting different icons stored in chart.data

`image.propertyFields.href = "iconproperty";` solved it for me
