### ISSUE TITLE
show total in stacked charts

### ISSUE THREAD

**Issue by ahmettahasakar** [amcharts/amcharts4#844]
The only examples that I could find are for version 3. How do I add the total value on top of stacked charts. I know how to do it for mouse over tooltips, but how do I put it permanently right above a stacked column

**Comment by martynasma** [comment]
You can do so by adding a `LabelBullet` to the last Series in stack.

Just make sure you set `calculateTotals = true` to your ValueAxis.

Then you can use `{valueY.total}` placeholder.

Here's an example:

https://codepen.io/team/amcharts/pen/6607b4955b25f6030747985d0a0bc736?editors=0010

**Comment by ahmettahasakar** [comment]
Thank you. but what if my columns are horizontal, instead of vertical?

**Comment by ahmettahasakar** [comment]
ok. figured it out. thank you
