### ISSUE TITLE
Question: How to compute using the Tooltip Text Value 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#848]
Its easy to set the tooltip text 

for example 

```
   // series.adapter.add("tooltipText", function (text, target, key) {
    //   debugger;
    //   return ">>> " + text + " <<<";
    // });

```

However, that text usually holds something like `{valueY}` 

I would like to do a computation on that value. 

Is that possible? 

for example I would like to double the values of the tooltipText but I can't due to only having access on the text variable.

**Comment by darlesson** [comment]
You can access the raw value from `target.dataItem.getValue('value')`. Please check more about [the getValue method here](https://www.amcharts.com/docs/v4/reference/dataitem/#getValue_method).

**Comment by jimmykane** [comment]
Thanks! That is it!
