### ISSUE TITLE
Bug: Choropleth heat map scrolling

### ISSUE THREAD

**Issue by cvalmonte** [amcharts/amcharts4#849]
Even when I disable pan and zoom on the choropleth US heat map, I'm unable to scroll up/down inside the browser while the cursor is hovered over the chart. I tried adding a CSS hack, `pointer-events: none`, to the chart's container, but it removes the tooltip feature.

**Comment by martynasma** [comment]
Map automatically hijacks mouse wheel and touch to perform zoom/pan actions.

To disable mouse wheel zoom on map use:

```
chart.mouseWheelBehavior = "none";
```

To disable touch scrolling:

```
chart.seriesContainer.draggable = false;
chart.seriesContainer.resizable = false;
```

Unfortunately, there's currently no way to have both scrolling and zoom/pan on touch.

We are working on some solutions for that, but it's currently not ready.

Please follow this issue: #757

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
