### ISSUE TITLE
Disposed AxisRange is not removed from axisRanges and causes EventDispatcher is disposed error when new AxisRange is created

### ISSUE THREAD

**Issue by blin4444** [amcharts/amcharts4#851]
Hello, I'm using the AxisRange feature on a date axis in my app, and I'm trying to add/remove individual AxisRanges instead of clearing the whole list of AxisRanges, but I'm running into the error: "EventDispatcher is disposed" after removing an AxisRange by calling the dispose() method and then adding another one.

This behavior is demonstrated here: https://codepen.io/blin4444/pen/Xovrqa

1. Click "Add Axis Range"
2. Click "Remove Axis Range"
3. Click "Add Axis Range". The error occurs.

**Comment by martynasma** [comment]
Looks like a bug. Thank you for bringing it to our attention. Will let you know when it's fixed.

P.S. no need to call `chart.validate();` after disposing a range. It will work just the same.

**Comment by blin4444** [comment]
Okay, thanks. Thanks for the tip.

**Comment by martynasma** [comment]
OK, so it's not a bug after all. Disposing an axis range does not remove it from the respective list.

However, removing an axis range from the range list **does** dispose it automatically, so removing is the best way to do it.

So instead of this:

```
range.dispose();
```

Do this:

```
categoryAxis.axisRanges.removeValue(range);
```

**Comment by blin4444** [comment]
Okay. [This page](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/) said that you could just call dispose before. If I call removeValue multiple times, would it scan through the entire axisRange list for each removal?

**Comment by martynasma** [comment]
Yes, it was wrong. Sorry about that. It has been corrected since then.

> If I call removeValue multiple times, would it scan through the entire axisRange list for each removal?

Yes.

**Comment by martynasma** [comment]
Sorry for late reply.

Have you tried?

```
categoryAxis.axisRanges.clear();
```

**Comment by blin4444** [comment]
Thanks for the response. My problem was that I wanted to remove multiple axisRanges, but I did not want to remove all of them.
