### ISSUE TITLE
When changing legend label markers on a legend that is on a container the labelText does not get updated 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#853]
I use series to update the legend label text like so async: 

```
    series.legendSettings.labelText = `${stream.type} [${am4core.color(this.eventColorService.getActivityColor(this.event, activity)).toString()}]${activity.creator.name}[/]`;

```

However only when I change the legend markers like so: 

```
      const legendContainer = am4core.create(this.legendDiv.nativeElement, am4core.Container);
      legendContainer.width = am4core.percent(100);
      legendContainer.height = am4core.percent(100);
      // legendContainer.padding(0, 0,150,0);
      chart.legend.useDefaultMarker = true;
      const marker = <am4core.RoundedRectangle>chart.legend.markers.template.children.getIndex(0);
      marker.cornerRadius(12, 12, 12, 12);
      marker.strokeWidth = 2;
      marker.strokeOpacity = 1;
      marker.stroke = am4core.color("#ccc");
      chart.legend.parent = legendContainer;
```

Then the following happens: 

<img width="806" alt="screenshot 2019-01-19 at 14 44 32" src="https://user-images.githubusercontent.com/1268723/51427515-14b93700-1bf9-11e9-9d37-b283eb93f6d1.png">

While after a while it shows ok:
 
<img width="820" alt="screenshot 2019-01-19 at 14 44 38" src="https://user-images.githubusercontent.com/1268723/51427520-1edb3580-1bf9-11e9-9b4b-5b8406ef9755.png">

**Comment by RobbiesCode** [comment]
Hi Jimmy,

After updating the `labelText`, I suggest calling `invalidate()` on your chart, as the label texts will not automatically refresh.

```
  for(var i = 0; i < chart.series.values.length; i++){
    
    var series = chart.series.getIndex(i);
    series.legendSettings.labelText = `${stream.type} [${am4core.color(this.eventColorService.getActivityColor(this.event, activity)).toString()}]${activity.creator.name}[/]`;
    
  }
  
  chart.invalidate();
```

Hope this helps!

**Comment by jimmykane** [comment]
Here is an example video https://drive.google.com/file/d/1nErxb_1MigYXpwGFrcVhXbOgVCdo-B1i/view

**Comment by jimmykane** [comment]
In the above video @RobbiesCode  you will see that the legend looks quite ok data wise. 
when I hover the mouse it updates to what it should

**Comment by martynasma** [comment]
@jimmykane Since we're quite stretched thin, might you consider helping us by producing a standalone demo version of your chart with this issue? This way we can verify if it's a bug and kick it over to dev for fixing much faster.

**Comment by jimmykane** [comment]
Yes, I can try. My only small issue (thus sometimes I report without a codepen) is the complex setup/data I have. Since I am through 100% AmCharts tattooed on my App why not create actually a standalone since my DB is firebase and can be accessed from anywhere (client) 

Thanks again for the great support and excellent product. 

I I could do something was to at least mention AmCharts at my app. I would like to go more into as I can launch my app first. 

<img width="1426" alt="screenshot 2019-01-30 at 19 33 48" src="https://user-images.githubusercontent.com/1268723/52182199-f9564a80-27fa-11e9-9d84-83bc40c94362.png">
(look at the nice Amcharts mention, at least Suunto knows about you)

**Comment by martynasma** [comment]
Awesome. Thanks man! (amCharts is usually written in cameCase, if I were to nitpick ;)

Suunto is my choice for running watches, too. And my heart bleeds a little every time I log into Movescount and see HC charts there ;)
