### ISSUE TITLE
Animated theme stalls the series properties to return the values depicted.

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#855]
Hi when I am listening on: 

```
  chart.legend.itemContainers.template.events.on("hit", (ev) => {
        // debugger;
        const series = <am4charts.LineSeries>ev.target.dataItem.dataContext;
        if (series.isHidden) {
          this.showSeries(series)
        } else {
          this.hideSeries(series)
        }
      });
```

I get different results with animated theme and without. When using the animated theme the above statement is always hidden (as it's initial state is hidden). 

I am suspecting that the animated theme does not change correctly the series properties at least for the hidden, displayed etc

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
