### ISSUE TITLE
Question / Help Using 'stroke' on adapter (for Legend markers)

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#856]
Hy,
I'm trying to customize the legend using adapters but for some reason using "stroke" to change the color doesn't seem to work. I created a pen :

https://codepen.io/aniov/pen/NeQaQx?editors=0010

What I'm trying to achieve is Legend for:
 Series-1 to be with only a stroke with dash - COLORED like her series.
 Series-2 to be filled and have stroke COLORED like her series. (I'm using stroke so they will have same size)

I'm using adapter properties described in here: https://www.amcharts.com/docs/v4/reference/iroundedrectangleproperties/#cornerRadiusBottomRight_property

**Comment by aniov** [comment]
If for you is working please comment line 74. I get 'Cannot read property 'dataContext' of undefined'.
Also try to click on legends, they will not toggle as initial.

This is what I see now  (same result in chrome, firefox, edge): 
![bad](https://user-images.githubusercontent.com/21243081/51559431-852ab700-1e8a-11e9-8ed6-127a44b03636.PNG)

and what it should be:.
![ok](https://user-images.githubusercontent.com/21243081/51559421-7e03a900-1e8a-11e9-8778-d942a10cec72.png)

Thank you.

**Comment by zeroin** [comment]
Some complicated issue. I found a workaround, you need to create new color in adapter:
`return am4core.color(settings.stroke.hex);`

If I'll find out how to do without it, I will let you know.

**Comment by aniov** [comment]
Just now I sow that you actually gave a solution to my problem. Thank you. :)
