### ISSUE TITLE
Docs: wrong JSON for fillModifier in tutorial

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#858]
In the [article about Colors & Gradients](https://www.amcharts.com/docs/v4/concepts/colors/#Creating_a_pattern), the JSON tab shows wrong config.

This is what it shows:

```
// ... 
"series": [{ 
  "type": "LineSeries", 
  ...
  "fillModifier": { 
    "type": "LinearGradientModifier", 
    "segments": { 
      "fillModifier": { 
        "opacities": [1, 0], 
        "offsets": [0, 1], 
        "gradient": { 
          "rotation": 90 
        } 
      } 
    } 
  } 
}]  
```

This is what actually works:

```
segments: {
  fillModifier: {
    type: "LinearGradientModifier",
    opacities: [1,0],
    offsets: [0,1],
    gradient: {
      rotation: 90
    }
  }
}
```

![schermata 2019-01-18 alle 15 37 09](https://user-images.githubusercontent.com/13300227/51457811-18f96780-1d53-11e9-9a98-504e36a85fc0.png)

Also, clicking the tabs below "Usage in Charts" will jump to "Creating a Pattern" and vice versa.

**Comment by martynasma** [comment]
Fixed docs. Thanks!

Can't reproduce the jump issue you described, though :)
