### ISSUE TITLE
How to add additional column in export to excel option

### ISSUE THREAD

**Issue by JoelJoy58** [amcharts/amcharts4#859]
Hi,
i wanted to add 2 more column other than the chart data columns while i try to export as excel.
can you please help me out.

for Example
Name | Score |Grade|Projects
--------------------------------
abc     |50       |A        |test
bcd     |25       |B        |sample
ram     |75       |A+     |new

here in the above sample the name and the score are the columns i'm passing to chart.data. if i want to export as Excel or csv i want to add the rest all the columns. is it possible.

**Comment by martynasma** [comment]
You can use an adapter "data" to modify data before it is export:

```
chart.exporting.adapter.add("data", function(data) {
  // modify `data`
  // ...
  return data;
});

**Comment by JoelJoy58** [comment]
@martynasma,
if you dont mind can please give an example. that would really help me. here.
thanks

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/concepts/exporting/#Modifying_exported_data

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
