### ISSUE TITLE
Slow performance for multiple axis line chart compared to v3

### ISSUE THREAD

**Issue by andreizet** [amcharts/amcharts4#860]
Hey,

  We are trying to switch our charts from v3 to v4, but seems that the performance is degraded on almost all the charts. Depending on the system, we've found v3 to be 9 times faster than v4 (in some cases). It most cases, v3 is 3-4 times faster than v4, as I said, it depends on the system. 
  Now, the question is: are we doing something wrong? (hope so, cause v4 is far more better than v3)
  
  Below you can find the examples for each version, nothing fancy, just a smoothed, multiple axis line chart with not a lot of data and no animations.

  Thanks!

V3:
https://codepen.io/andreizet/pen/XoLVeb?editors=0010

V4:
https://codepen.io/andreizet/pen/aPgLRG?editors=0011

**Comment by martynasma** [comment]
I don't think you are doing something wrong. v4 is much more advanced, hence it taking a bit longer than much simpler v3.

That said, does extra 200ms make a noticeable difference to the user? That's literally the difference between these two versions on your test chart.

Also, when it comes to charts with a lot of data, you'll notice how v4 performs better, in terms of chunked data parsing/render. Try v3 with 50K of data points. The browser will freeze for a lot of time. In v4 it will stay responsive.
