### ISSUE TITLE
Gauge zoom disable doesn't work on RadarChart

### ISSUE THREAD

**Issue by urirahimi** [amcharts/amcharts4#864]
Steps to reproduce: 
1. create a radar component
2. Add "chart.chartContainer.wheelable = false;"

Zoom still works as screenshot shows.
<img width="612" alt="screen shot 2019-01-21 at 10 23 37 pm" src="https://user-images.githubusercontent.com/19512370/51516185-513c8c80-1dcb-11e9-836a-924f3ff8de90.png">

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
