### ISSUE TITLE
Why it's not possible to (properly) use a theme for only one chart?

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#865]
https://www.amcharts.com/docs/v4/concepts/themes/
![image](https://user-images.githubusercontent.com/15041200/51532209-3a884b00-1e48-11e9-9aea-8b831d522ff1.png)
As the documentation says it's possible to create charts with different themes like this.
But why it's not possible to apply a theme to the chart directly (`chart.useTheme(customTheme)`)?
It would be great to have such an option...

**Comment by jimmykane** [comment]
Yeah the issue here as you describe I believe is that it needs a page reload , or chart recreate if you want to change theme right ?

**Comment by dmsmaxim** [comment]
My point is that I want to have an opportunity to change a theme for an individual chart and not touch others.

**Comment by dmsmaxim** [comment]
Something like this:
```
var charts = [chart1, chart2, chart3];
charts[0].useTheme(theme1);
charts[1].useTheme(theme2);
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by zdm** [comment]
How I can redraw chart with the new theme?
Is it possible without completely destroy chart?
