### ISSUE TITLE
JSON based config for multi axes chart with multiple series

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#866]
Hey I need an example of how to create JSON based config for multi axes chart with multiple series.
I have tried to find how to map between axis and series with no further success.

Best Regards,
Barak Inbal

**Comment by martynasma** [comment]
You can map a series to an axis by id:

```
{
  // ...
  "yAxes": [{
    id: "y1",
    // ...
  }, {
    id: "y2",
    // ...
  }],
  // ...
  "series": [{
    yAxis: "y1",
    // ...
  }, {
    yAxis: "y2",
    // ...
  }]
}
```

**Comment by BrkCoder** [comment]
> You can map a series to an axis by id:
> 
> ```
> {
>   // ...
>   "yAxes": [{
>     id: "y1",
>     // ...
>   }, {
>     id: "y2",
>     // ...
>   }],
>   // ...
>   "series": [{
>     yAxis: "y1",
>     // ...
>   }, {
>     yAxis: "y2",
>     // ...
>   }]
> }
> ```

Hey thanks for the quick reply, I think that I have tried this way and got a bug of event dispatcher, you are saying that I can put on yaxis field a string but it is on contrary to field's type which is yAxis  object only and not a string "y1" or "y2".

**Comment by BrkCoder** [comment]
Thansk for the quick respond,every thing is work as expected 👍
