### ISSUE TITLE
Compilation error with dynamic import (Module parse failed: Unexpected token in Export.js)

### ISSUE THREAD

**Issue by juhasev** [amcharts/amcharts4#868]
I am using Laravel Mix but behind the scenes it uses Webpack 4. All the sudden after running NPM update the Amcharts 4.0.21 started throwing the following error so I am suspecting something has changed in the charting library itself.

```
ERROR in ./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js 3215:14
Module parse failed: Unexpected token (3215:14)
You may need an appropriate loader to handle this file type.
|             return [4
|             /*yield*/
>             , import(
|             /* webpackChunkName: "canvg" */
|             "canvg")];
 @ ./node_modules/@amcharts/amcharts4/core.js 74:0-56 74:0-56
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/modules/Reporting/components/index.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/modules/Reporting/components/index.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/modules/Reporting/components/index.vue
 @ ./resources/assets/js/routes.js
 @ ./resources/assets/js/app.js
```
By default laravel mix excludes node_modules folder from compilation as it should as node_modules should be pre-compiled. I am using Babel 7 and even tried to add syntax-dynamic-import plugin but that didn't help. Here are my configuration:

package.json
```
"devDependencies": {
  "@babel/cli": "^7.2.3",
  "@babel/core": "^7.2.2",
  "@babel/plugin-proposal-object-rest-spread": "^7.2.0",
  "@babel/plugin-syntax-dynamic-import": "^7.2.0",
  "@babel/preset-env": "^7.2.3",
```
.babelrc
```
{
  "presets": [
    "@babel/preset-env"
  ],
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```
versions
```
npm -v 6.4.1 node -v 10.14.1
```
I've been stuck for 24 hours and sort of run out of options to try. The only way to get this going right now is to remove the entire library from the project. No other node module has any issues compiling... Any help would be much appreciated.

I am running the latest version 4.0.21

**Comment by juhasev** [comment]
I also tried transpiling the @amcharts4 module by instructing webpack to specifically include it from node_modules folder but the end result is the same. I've temporarily disabled amcharts4 as we haven't gotten too far into using it yet (was easy). I really like the library so hopefully we get this resolved soon.

**Comment by Pauan** [comment]
That's very strange!

Webpack has built-in support for dynamic `import()`, and we haven't made any changes to the dynamic loading recently.

I just tested it, and compilation seems to work fine on our examples.

Some questions:

1. What version of amCharts 4 were you using before the upgrade?

2. Are you using vanilla ES6 or TypeScript?

3. If you go [into one of our examples](https://github.com/amcharts/amcharts4/tree/master/dist/es2015/examples/javascript/simple-line-chart) and run `yarn`, do you also get a compile error?

4. Is it possible for you to create a reduced test case and send it to us, so we can figure out the problem?

**Comment by sungha** [comment]
I got a exactly same error with webpack 4.29.0 but everything is just fine with webpack v4.28.4

**Comment by dmsmaxim** [comment]
After version 4.0.22+ I'm getting this error:
```
  ERROR in ./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js 2675:49
    Module parse failed: Unexpected token (2675:49)
    You may need an appropriate loader to handle this file type.
    |             return tslib_1.__generator(this, function (_a) {
    |                 switch (_a.label) {
    >                     case 0: return [4 /*yield*/, import(/* webpackChunkName: "canvg" */ "canvg")];
    |                     case 1: return [2 /*return*/, _a.sent()];
    |                 }
     @ ./node_modules/@amcharts/amcharts4/.internal/core/Sprite.js 38:0-41 4850:30-36
     @ ./node_modules/@amcharts/amcharts4/.internal/core/elements/Slice.js
     @ ./node_modules/@amcharts/amcharts4/.internal/themes/animated.js
     @ ./node_modules/@amcharts/amcharts4/themes/animated.js
     @ ./src/js/app/app.js
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/js/app/app.js
    
    ERROR in ./node_modules/@amcharts/amcharts4/.internal/core/responsive/Responsive.js 432:15
    Module parse failed: Unexpected token (432:15)
    You may need an appropriate loader to handle this file type.
    |      */
    |     Responsive.prototype.loadDefaultRules = function () {
    >         return import(/* webpackChunkName: "responsivedefaults" */ "./ResponsiveDefaults");
    |     };
    |     return Responsive;
     @ ./node_modules/@amcharts/amcharts4/core.js 119:0-68 119:0-68
     @ ./src/js/app/app.js
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/js/app/app.js
```

**Comment by juhasev** [comment]
Interesting... I will try with webpack v4.28.4 and see if that is the problem in my case too.

**Comment by juhasev** [comment]
Looks like this issues is in fact webpack related:

https://github.com/webpack/webpack/issues/8656

**Comment by Pauan** [comment]
@sungha Thanks for the information! That bug is already being tracked by Webpack: https://github.com/webpack/webpack/issues/8656

@juhasev Could you check if downgrading Webpack fixes the problem for you?

**Comment by juhasev** [comment]
Quick fix that worked for me:

Remove node_modules and destroy lock file
rm -fr node_modeles
rm -f package-lock.json

Downgrade webpack to last known working version:
npm install webpack@4.28.4

Install acorn 6.0 as NPM cannot find it
npm install acorn@^6.0.0

We will wait till the new NPM comes out. Good work everybody glad this is getting permanently resolved!

**Comment by hassanjuniedi** [comment]
Using yarn install instead of npm install solved the problem for me in (Angular 7 project with amcharts4)
