### ISSUE TITLE
Getting TS2345 error when trying to compile example

### ISSUE THREAD

**Issue by ianoc90** [amcharts/amcharts4#87]
I'm trying to render a simple bar chart through a BarChart class following the example found [here](https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Creating_chart_instance).

Here is the example:
```
import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";

class BarChart {
  container: string;
  data: object;

  constructor(container: string, data: object) {
    this.container = container;
    this.data = data;
  }

  renderChart() {
    const {
      container,
      data
    } = this;

    let chart = am4core.create(container, am4charts.XYChart);
    chart.data = data;

    let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
    categoryAxis.dataFields.category = "country";
    let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
  }
}

export default BarChart;
```

But when I try to build I get the following error:
```
src/BarChart/index.ts:19:44 - error TS2345: Argument of type 'typeof XYChart' is not assignable to parameter of type 'new () => Sprite'.
  Type 'XYChart' is not assignable to type 'Sprite'.
```

**Comment by ianoc90** [comment]
Aha!

This is because I have my `compilerOptions` in my `tsconfig.json` set to strict.

```
  "compilerOptions": {
    "target": "ES2015",
    "module": "commonjs",
    "declaration": true,
    "outDir": "lib",
    "strict": true 
  },
```
After reading through some of the other issues I noticed a comment from @martynasma on #72  explaining that amCharts4 does not support strict mode just yet.

> amCharts 4 code is currently not quite strict mode-ready. We are working on little nitbits that are preventing it, but still are a long way from completing it.

Removing the `"strict": true` prevents the error.

**Comment by martynasma** [comment]
Yup. That's it. We're working on it, but not quite there, yet.

Gonna close this, since it's basically a diplicate of #72. Please make sure you subscribe to updates to that issue to be notified about the progress.
