### ISSUE TITLE
Enhancement: Scrollable legend

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#870]
Currently only way to implement a scrollable legend seems to be in an external container. This is fiddly and causes other issues (e.g. #835). It'd be great to be able to allow scrolling of embedded legend (as it was possible with V3).

**Comment by martynasma** [comment]
Scrollable legend was implemented in 4.8.0.

More details here:
https://www.amcharts.com/docs/v4/concepts/legend/#Scrollable_legend
