### ISSUE TITLE
Question: Map line arrow hover state

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#873]
How do I correctly set hover color for line with an arrow?

Please see https://codepen.io/npc42/pen/exmmjL?editors=0010

If you zoom in and hover the line, you'll notice that the arrow has an inner part (fill) that doesn't seem to inherit the line's fill.

If I add .fill condition to the line's hover state (line 23), then fill sets correctly on line hover — but it doesn't unset when no longer hovering.

PS Is it me, or does the arrow size reduce on zoom, even though I set nonScaling?
PPS Also note the line tooltip position, that's #854, now you have an example.

**Comment by Ices-Eyes** [comment]
Also, the legend position on graphs is not entirely taking into account.

**Comment by martynasma** [comment]
Since arrow element is not a child of the line element, setting fill properties on line series does not affect it.

Probably the easiest way to achieve what you need is to create a "hover" state for the arrow as well:

```
lineSeries.mapLines.template.arrow.fill = am4core.color("#e03e96");
var ahs = lineSeries.mapLines.template.arrow.states.create("hover");
ahs.properties.fill = am4core.color("#ccc");
```

The arrow does not change. However the stroke does get zoomed, because it is not affected by `nonScaling`.

To disable scaling of outline/stroke set `nonScalingStroke = true`.

**Comment by NPC** [comment]
@martynasma sorry for being stubborn, I still think arrow is a line's child, since it inherits the stroke property, even on line hover. Fill is being also used, but incorrectly — that's why I thought it may be a bug.

I've updated the codepen to move arrow inside the mapLines.template, following [this demo](https://www.amcharts.com/demos/map-with-curved-lines/), and behaviour doesn't change.

Setting arrow hover state means that the color will change when I hover the arrow only — I already tried that, and it makes sense, but I want the arrow color to change when I hover the line (same way the stroke already changes). Otherwise it stands out.

PS arrow.nonScalingStroke = true seems to affect it a little, but still you see that arrow is visible well when zoomed out, but as you zoom in it also disappears on the line.

**Comment by notacouch** [comment]
@martynasma  It seems he's accurate about the arrow being a line's child.

E.g. state inheritance via `setStateOnChildren = true` between the line and arrow actually works:

```javascript
lineSeries.mapLines.template.setStateOnChildren = true;

let arrow = lineSeries.mapLines.template.arrow;
arrow.nonScaling = true;
arrow.nonScalingStroke = true;
arrow.fill = am4core.color("#e03e96");
var ahs = arrow.states.create("hover");
ahs.properties.fill = am4core.color("#ccc");

var hs = lineSeries.mapLines.template.states.create("hover");
hs.properties.stroke = am4core.color("#ccc");
hs.properties.fill = am4core.color("#ccc");
```

Demo (fork of his latest link):
https://codepen.io/team/amcharts/pen/5f2c05cd60280a63be783e97c6ddfc32

@NPC ^does the above work for you?

**Comment by NPC** [comment]
@notacouch thank you! Setting setStateOnChildren to true, and adding an arrow hover state (and default fill) resolves the issue for me.

**Comment by notacouch** [comment]
@NPC  You're welcome! Glad that last bit did the trick.
