### ISSUE TITLE
Labels with html do not get exported

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#874]
I have a chart with a stand alone `html` label:

```
var label = chart.plotContainer.createChild(am4core.Label);
// label.text = "This is a footnote. Not responsive.\nBut we can add line breaks.";
label.html = "html: This is a <strong>footnote</strong>. Not responsive.\n<br>But we can add line breaks."
label.fontSize = 16;
label.dx = 40;
label.dy = -10;
label.exportable = true;
```

I also have a legend with a custom item on the same chart, which is also an html label:

```
var legend = new am4charts.Legend();
legend.parent = chart.chartContainer;
legend.data = [{
  "name": "This is a <strong>footnote</strong>. Not responsive.<br>\nBut we can add line breaks."
}];
legend.markers.template.disabled = true;
legend.labels.template.html = "html: {name}";
legend.exportable = true;
//legend.disabled = true;
```

Here's what it looks like:

![screenshot 2019-01-23 at 08 37 50](https://user-images.githubusercontent.com/13300227/51590440-33197e00-1eea-11e9-8cc2-f150eb630efb.png)

The issue is that the standalone label and the legend do not get exported to an image. When I use the simple `text` property, they **do** show up. Is html/foreignObject export not supported? I am on Google Chrome.

Here's the full html file:

[exportashtml.zip](https://github.com/amcharts/amcharts4/files/2786166/exportashtml.zip)

**Comment by martynasma** [comment]
HTML labels are added via `foreignObject` which cannot be converted to canvas for export.

There's no way around that.
