### ISSUE TITLE
Using DurationAxis for xAxis does not show series tooltips 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#877]
In this example 

https://codepen.io/anon/pen/wNBZZJ?=true
<img width="723" alt="screenshot 2019-01-23 at 14 59 30" src="https://user-images.githubusercontent.com/1268723/51611437-878b2080-1f1f-11e9-8450-0d832cf83ad7.png">

As seen tooltips on the series are shown. 

However, using a duration axis for xAxis for the chart like so: 

https://codepen.io/anon/pen/PVwgrb?=true

Has no tooltips 

<img width="716" alt="screenshot 2019-01-23 at 15 00 49" src="https://user-images.githubusercontent.com/1268723/51611523-b73a2880-1f1f-11e9-9fb5-c721f793d07e.png">

(on both examples tooltips are set)

**Comment by martynasma** [comment]
That's by design.

`DurationAxis` is basically a `ValueAxis` with differently formatted labels and increments.

There are no increments (like there are time units on DateAxis or categories on CategoryAxis) that data item specifically belongs to, so there's no way to determine how to display the tooltips.

**Comment by jimmykane** [comment]
@martynasma  so there is not way to actually show tooltips with a duration axis right? 

And in regards to that , pehaps we should not use durationaxis for xAxis , or at least in my case on what I want to achieve?

**Comment by jimmykane** [comment]
or is there a way I can solve this? 

Because as you understand I want the duration as the xAxis , rather than a DateAxis that I could perhaps format and will get clunky.

**Comment by martynasma** [comment]
Correct, there's no way to solve this, I'm afraid.

Same thing would be if you had a `ValueAxis` as an X axis.

**Comment by jimmykane** [comment]
:-( lets close this then

**Comment by jimmykane** [comment]
@martynasma  Just one quicky. Any tips on how to format a Date aXis to act like duration  ?

**Comment by martynasma** [comment]
Ummm, replacing `DurationAxis` with `DateAxis` should do the trick, as long as your X values (or rather `dataFields.dateX` are in milliseconds. It will act then as timestamps.

You might need to adjust some `dateFormats` on the axis, but otherwise it should be doable.

Excellent idea!

**Comment by jimmykane** [comment]
@martynasma  thanks! 

Btw I noticed already that the DateAxis can get numbers (eg ms) or dates as well. (JS DATES) 

What is prefered? (in general)

**Comment by martynasma** [comment]
No preference. Both are perfectly good ways.

**Comment by jimmykane** [comment]
Sifted Dates to unix 0  and that worked like a charm
