### ISSUE TITLE
Pie slice hover assignment on "inited" handler

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#882]
This is a weird one. If I assign over/out handlers to a Pie chart slice right after making a chart — they work fine. Yet if I assign them inside a chart's “inited” handler — they seem to assign too, but don't get triggered.

Please see the [codepen](https://codepen.io/npc42/pen/yGmBBy?editors=0010), over/out 2 are printed to the console, while over/out 1 are not.

What am I doing wrong? Do I need to call some method on the chart for it to re-evaluate its listeners?

**Comment by martynasma** [comment]
Well, by the time "init" kicks in, the slices are already created. So the events that were added to `slices.template` after actual slices were cloned from did not receive them. While those events that were added to template immediately after chart object was created (and before slices were created) carried over.

If you need to set events on slices after chart is initialized, you'd need to iterate through `pieSerie.slices` and attach the event handler individually.

BTW, accessing `series.slices.values` is not recommended. Use `getIndex()` instead:

```
let pieSerie = chart.series.getIndex(0);
```

You can also iterate through any List using built-in `each()`:

```
let pieSerie = chart.series.getIndex(0);
pieSerie.slices.each((slice) => {
  slice.events.on(.......);
});
```

**Comment by NPC** [comment]
@martynasma Perfect, thank you so much! Now it works, and I still have a lot to learn.

Good tip on .values, I'll replace where I can (.each has index as a 2nd argument, nice!). It may also be good to add a general .toArray() method, to allow standard iterators like .reduce, .find, .filter etc.
