### ISSUE TITLE
Dynamic filter data on ammap

### ISSUE THREAD

**Issue by Ices-Eyes** [amcharts/amcharts4#883]
Hi all,
I have a map with lots of line with a value property attached. Is there a way to made ie a slider to filter the lines based on the values? Something similar to the scrollbar you can attach to a standard graph... Or the only way is to delete the line series and recreate it with filtered data?

Thanks :)

**Comment by Ices-Eyes** [comment]
Well, the idea is to hide or shows some lines from a MapLineSeries depending on the "value" property attached to them... I will take a look to the data adapter, thanks fo the tip :)

**Comment by martynasma** [comment]
Yeah, in this case adapter might be a good way to go, except maybe not on data.

```
lineSeries.mapLines.adapter.add("hidden", function(hidden, target) {
  return target.dataItem.dataContext.value < 100 ? true : false;
});
```

Now all lines that have `value` set in their data to less than 100 will be automatically hidden.

**Comment by Ices-Eyes** [comment]
Ok...tryed also with reinit and deepinvalidate, but bot produce no results. reinit just make the graph flash, the other apparently do nothing... :(

**Comment by notacouch** [comment]
You could also try just iterating over all the lines and show/hiding them one by one, e.g. for html5 `range` inputs with `id`s of `minRange` and `maxRange`, and the value property in the data being `value`:

```javascript
var $min = document.getElementById("minRange");
var $max = document.getElementById("maxRange");

function filterLines() {
  lineSeries.mapLines.each(function(line) {
    var value = Number(line.dataItem.dataContext.value);
    var filtered = (value >= Number($min.value) && value <= Number($max.value));
    if (filtered) line.show();
    else line.hide();
  });
}

// add onchange event listeners which execute filterLines();
```

Here's a demo:
https://codepen.io/team/amcharts/pen/67eae88438f09b4ce4dfd1f9692bc26b

Does that work for you?

**Comment by Ices-Eyes** [comment]
Ok, that wold have been my next try... Since I have from one to 5 lineseries in the Graph (with about 900lines in total), I need to iterate to them too, so was wondering if there would be a better way to do that, but it seems not... Will try and write here the result! Thanks for now :)

**Comment by notacouch** [comment]
It seems like you're filtering based on the value of 2 different user inputs. Is there a small or wide range of values for the data/lines/filter? E.g. in my example it's around 10 or so. If that's the case there may be another method. But I imagine ultimately under the hood there will still have to be at least one iteration for all lines per series.

**Comment by Ices-Eyes** [comment]
Actually I'm using a bootstrap-slider component, that have the ability to define ranges. Data are very variable, so there's no predefined interval, hence are really variables (ie between 1 to 60000). By the way, I implemented the solution you suggest, and it seems to work better then I expected, so it's OK for me ;)

**Comment by notacouch** [comment]
Glad to know the good old loop and show/hide did the trick!
