### ISSUE TITLE
Bar Chart readability

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#884]
Hello there,

Is it possible to make bar charts more readable by adding spaces between categories? or a line?

As you can see there, it's hard to see the separation

![image](https://user-images.githubusercontent.com/6083644/51666433-18b0d480-1fbe-11e9-9df4-3a778ed44b37.png)

Thansk for your help !

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
