### ISSUE TITLE
Enhancement: modify chart for export

### ISSUE THREAD

**Issue by JoelJoy58** [amcharts/amcharts4#886]
when i try to export the pie chart as png/jpg. the chart is getting downloaded without the title and the labels. 
can someone help me.
thanks in advance.

**Comment by xorspark** [comment]
Would it be possible to provide a codepen/stackblitz/codesandbox or some way for us to reproduce the problem?  I'm getting the title and labels in my example [here](https://codepen.io/team/amcharts/pen/0a417daee0010d3d018f9c6d874e4f04)

**Comment by JoelJoy58** [comment]
Sorry that was my mistake its because of the background color, the label are not visible in image.
it would be really help full if you help me how to modify the label in the pie during export as png/jpg, and to add  title for the pie during export as png/jpg
for Example.
in my pie on the page is just **"{value.percent.formatNumber('#.0')}% ({value})";**
but during export as png/jpg i want  **"{category} - {value.percent.formatNumber('#.0')}% ({value})";**
as i cant export legend during my export to png/jpg.
could you please help me out.
Thanks in Advance

**Comment by martynasma** [comment]
Unfortunately, there's currently no way to modify chart config specifically for export.

It would make a good feature, though.

We will consider it.

**Comment by martynasma** [comment]
This has been finally implemented in `4.6.8`.

More details:
https://www.amcharts.com/docs/v4/tutorials/modifying-chart-for-export/
