### ISSUE TITLE
Zero column tooltip with scrollbar

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#888]
Please see the [codepen](https://codepen.io/npc42/pen/LqpzNv).

Without scrollbarX the zero value column is hardly visible, and tooltip doesn't show for it (which is what I'd like). Yet adding a scrollbarX allows to highlight it and shows the cursor. This is especially annoying with high data density (many categories / dates shown).

**Comment by martynasma** [comment]
Couple of workarounds for ya:

1) Add a fatter `stroke` / `strokeWidth` to the columns. A zero column will still have some "meat" to react on hovers to.

2) Add a cursor to chart. It will allow displaying tooltips on columns even without directly hovering over them, but rather hovering anywhere within their category.

**Comment by NPC** [comment]
@martynasma Sorry, I knew I didn't explain myself here. I don't want the tooltip or even the sliver of column fill to be shown for zero values. 

For now the only way we found is to replace zero with null — is this what you recommend?
