### ISSUE TITLE
Pie Chart angle of anything above 90 gives odd results

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#890]
When giving pie chart an `angle` of `> 90`, the pie chart will start to look funny. Here's an example of a Pie Chart with `angle` **180**.

Demo: https://codepen.io/team/amcharts/pen/GzpVGL?editors=1010.

An angle of 180 might not make much sense, perhaps cap the angle for a Pie Chart on 90? Otherwise, I would expect the Pie Chart to literally be flipped 180 degrees, and be viewed from the other side (might not be that useful).

Another issue is that the label ticks do not respect the angle setting. In this demo (https://codepen.io/team/amcharts/pen/pGjMLb?editors=1010) you'll see that the ticks still point to the slices as if they were top viewed with an angle of 0.

**Comment by martynasma** [comment]
The biggest available value for `angle` is 90.

It wasn't mentioned anywhere in the docs, so we are going to make that happen.
