### ISSUE TITLE
How to modify tooltipText the font color？

### ISSUE THREAD

**Issue by fashionwill** [amcharts/amcharts4#894]
![image](https://user-images.githubusercontent.com/30282860/51818526-483b4600-230a-11e9-97f6-95782979a43a.png)
How to change the font color to red？
Thank you very much for your help.

http://jsfiddle.net/kup4exgf/1/

**Comment by darlesson** [comment]
You need to set [autoTextColor](https://www.amcharts.com/docs/v4/reference/tooltip/#autoTextColor_property) to `false` which stops the tooltip from trying to figure out the best contrast color for the text.

```
series1.tooltip.autoTextColor = false;
series1.tooltip.label.fill  = am4core.color("#FF0000");
```

Optionally you can use `tooltipText` to set the color using square brackets as [shown in this tutorial](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#List_of_codes).

```
series1.tooltipText = "[#FF0000]Place taken by {name} in {categoryX}: {valueY}[/]";
```

**Comment by Usman78930** [comment]
thanks this worked for me
