### ISSUE TITLE
When disabling a series and not using the animated theme the legend label for that series  is enabled  that it shouldn't

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#896]
Using the Animated theme and disabling a series (the last one in this case) 
CodePen https://codepen.io/anon/pen/bzepbP

Result works as expected

<img width="1434" alt="screenshot 2019-01-28 at 11 58 53" src="https://user-images.githubusercontent.com/1268723/51832129-23d46f00-22f4-11e9-8c4b-8f5bfda70796.png">

Removing the animated theme: 

Codepen https://codepen.io/anon/pen/VgjaLd

Result (NOT OK -> series label shows checked) 

<img width="1407" alt="screenshot 2019-01-28 at 12 00 04" src="https://user-images.githubusercontent.com/1268723/51832202-50888680-22f4-11e9-8ad3-7e0c841f8bbb.png">

**Comment by martynasma** [comment]
I'm not sure what you are trying to do here.

Do you want to pre-hide a series?

In that case you should use `hidden`, not `disabled`.

**Comment by jimmykane** [comment]
@martynasma if I would use disabled wouldn't it exclude it from the calcs?  
So I want to disable the series till the user presses the label. 

But when I am disabling the series with non amimated themes the label state is not correct. 

Thus it looks like the series is enabled. 

On the screenshot 1  one look at the labels 

Then look on the screenshot 2

**Comment by jimmykane** [comment]
in a single sentence. When disabling a series the label is not disabled, when you dont use the animated theme like in the code pens

**Comment by jimmykane** [comment]
To be honest I think I did try to: 

1. Hide, both by setting `hidden=true` and `hide()`
2. Disable the series by `disabled=true` 

The state of the label was still depicted wrong thus listesting on the label checkbox has an invalid state. 

That behaviour is needed as I want to provide some prem features to the user so I need to be able to programmatically in runtime change this. 

 A codepen will follow up.

**Comment by martynasma** [comment]
OK, just to show what I mean:
https://codepen.io/team/amcharts/pen/69cf4c8018fdda80302c1706914850af?editors=0010

This is using `hide()` on a series, and the "active" state is reflected properly.

Please note, that when legend item is hidden, it gets "active" state applied to it. I know it's a bit counterintuitive, but it is what it is. Item is a togglable sprite, so when it is in normal state it has default state applied, when you toggle it on, it gets active state applied.

Hope that makes sense :)

**Comment by jimmykane** [comment]
Yeah that 

> Please note, that when legend item is hidden, it gets "active" state applied to it. I know it's a bit counterintuitive, but it is what it is. Item is a togglable sprite, so when it is in normal state it has default state applied, when you toggle it on, it gets active state applied.

Was what I was looking for!
