### ISSUE TITLE
Uncaught ReferenceError: am4internal_webpackJsonp

### ISSUE THREAD

**Issue by ronbanks** [amcharts/amcharts4#899]
On today's latest version:
amCharts 4 geodata Map data files for JavaScript Maps Version 4.0.30(January 28, 2019) I get this error:

Uncaught ReferenceError: am4internal_webpackJsonp is not defined at worldLow.js:20

Error: Map geodata could not be loaded. Please download the latest <a href="https://www.amcharts.com/download/download-v4/">amcharts geodata</a> and extract its contents into the same directory as your amCharts files.
at index.js:10

This can be observed by loading /amcharts4/examples/javascript/geo-heat-map

**Comment by martynasma** [comment]
Please go back to geodata 4.0.29.

4.0.30 containes a build error.

Our CDN and downloads were already downgraded. We're working on withdrawing an npm package.

**Comment by NPC** [comment]
@martynasma seeing the same (or very similar) issue with 4.1.0.

**Comment by ronbanks** [comment]
hmm, my dev server has these versions on it and I'm not seeing the issue I had before with 4.0.30, working fine for me?

amCharts 4 JavaScript Charts & Maps Version 4.1.0(January 30, 2019)
amCharts 4 geodata Map data files for JavaScript Maps Version 4.1.0(January 30, 2019)

**Comment by NPC** [comment]
Odd, I had to revert to pre-today's version to remove the error. Loading in plain JS via <script> tags. Can't be bothered to try to upgrade again today, have other tasks plus 4.1.0 didn't fix anything vital for me, so I'll wait for the next version to see if it helps.

**Comment by NPC** [comment]
All good with 4.1.1, either fixed, or I did something wrong with 4.1.0.

**Comment by ronbanks** [comment]
the issue seems to have been resolved in the latest version so closing

**Comment by leniel** [comment]
I just got this error right now with the latest version: 4.1.7

**Comment by ronbanks** [comment]
@leniel, I haven't seen this error since I closed it since 4.1.1? Not sure what's causing it for you but I dropped the sample code that you referenced in a [codepen](https://codepen.io/reb777/pen/exWyYv) and it appears to me that neither the sample you referenced nor in this codepen example produces the error.

**Comment by leniel** [comment]
@ronbanks yep... the problem is happening when trying to implement amcharts in this framework:

https://pisquare.osisoft.com/thread/38753-referenceerror-webpackjsonp-is-not-defined

**Comment by leniel** [comment]
Ohhhh they load the libraries in alphabetical order as described here:

https://pisquare.osisoft.com/thread/34314-integrating-javascript-librarycustom-directive-angular-nvd3-into-pi-vision

I had to rename the core.js to acore.js.

It's working just fine now.

**Comment by ronbanks** [comment]
Glad you worked it out. Even more glad to see that you're a believer... ;-)

**Comment by petardfoozer** [comment]
Just piping in, in case anyone else runs into this error

You need to load the core.js file BEFORE you load any of the other files (charts.js, themes/file.js etc...) otherwise you will get the Uncaught ReferenceError: am4internal_webpackJsonp

**Comment by aiden-sobey** [comment]
Was getting this error on Version 4.5.4 (July 08, 2019), renaming `core.js` to `acore.js` fixed it for me.

**Comment by roireshef** [comment]
Guys, this isn't a scalable solution. You must consider the fact website developers are using and js/css optimization and minification tools. The order of loading the js libraries might change, and I would kindly ask to make this plugin robust to it. Thanks.
