### ISSUE TITLE
LineSeries bad rendering if only 2 data points

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#900]
Hello,

If there is only 2 points on a line serie, there is some rendering problems: 
https://codepen.io/ptorrent/pen/RvRebJ

2 data points (after 2s) : 
![image](https://user-images.githubusercontent.com/6083644/51865463-a128cf80-2346-11e9-92e8-4c9509d5a497.png)

3 data points (after 3s): 
![image](https://user-images.githubusercontent.com/6083644/51865483-abe36480-2346-11e9-99ed-7c4dd2d79fe6.png)

**Comment by ptorrent** [comment]
By the way, I'm not sure to understand how cursor works ?

![flash2](https://user-images.githubusercontent.com/6083644/51869294-6deb3e00-2350-11e9-9e23-34e2431607cc.gif)

Why it jumps to the end at 50% of the chart width ?

**Comment by ptorrent** [comment]
Ok I think the problem is: 

series.addData([ ]) don't support an array of 1 element... Can you confirm ?

**Comment by martynasma** [comment]
This does not appear to have anything to do with `addData()`. I get the same view even if I cram all three data points as they are into `data` of the series directly.

What this has to do with is data granularity, or specifically with the `baseInterval` setting. Since you don't have it set, the chart tries to derive it our of the data. When you have two initial data points that are far apart, you get data granularity of 12 hours.

When you add a third one which is only 2 seconds away from the previous one, your data granularity goes to seconds.

So, with such erratic data granularity, it's best not to rely on the chart's detection mechanism, but to specify granularity yourself. E.g.:

```
	"xAxes": [
		{
			"id": "x",
			"type": "DateAxis",
			"dateFormat": {
				"day": "MMMM d, yyyy",
				"hour": "MMMM d, yyyy",
				"week": "MMMM d, yyyy",
				"month": "MMMM d, yyyy",
				"year": "MMMM d, yyyy"
			},
			"isLineAxe": true,
			"min": start,
			"max": end,
			"visible": true,
			"renderer": {
				"inside": false
			},
      "baseInterval": {
        "timeUnit": "hour",
        "count": 12
      }
}
],
```

**Comment by ptorrent** [comment]
I put baseInterval here with a min max on xAxis.

https://codepen.io/ptorrent/pen/ErXKBx

Do you think it's a normal rendering ?

start : new Date(1548630000000) ==> Mon Jan 28 2019 00:00:00 GMT+0100 
end  : new Date(1548716400000) ==> Tue Jan 29 2019 00:00:00 GMT+0100

How do you explain that ?

![image](https://user-images.githubusercontent.com/6083644/52181310-babb9280-27f0-11e9-9ff1-0f07647bece0.png)


Thanks for your support

**Comment by ptorrent** [comment]
And on this example: 

https://codepen.io/ptorrent/pen/exRzzO

Where is my cursor valur 101 ?

I'm working a lot with LineSeries and it's hard to explain everything... but there's a lot of strange think when we add data directly on series in asynchronous way

**Comment by ptorrent** [comment]
By the way the 103 point is at:

new Date(1548709937488+2000) => Mon Jan 28 2019 22:12:19 

Not 12.00 ...

**Comment by martynasma** [comment]
Do you get different results if you add that same data directly to chart?

**Comment by ptorrent** [comment]
Yes, same problem with cusor (unable to see 101 value)

And end point at Mon Jan 28  2019 22:12:19 seems to be at 12:00

https://codepen.io/ptorrent/pen/ErXyWP

**Comment by martynasma** [comment]
Is this real data? I mean you have 3 data points. Two of them are almost a day away, and two 2 seconds.

If this is how your data actually looks like, you need to make a decision on which granularity you need the chart to be at.

Currently you have it set at 12 hours, which is effectively telling your chart "my data points come at no less than 12 hour intervals".

So, when chart is drawing it is considering your 2-second data points to be a single time increment, hence not being to hover over them individually.

If you want second-level precision, then you use `baseInterval` to set it to seconds. This way, you will be able to hover individual data points when you zoom in significantly.
