### ISSUE TITLE
max value isn't taken into account when there is a lot of datas.

### ISSUE THREAD

**Issue by maxkermarrec** [amcharts/amcharts4#907]
Hello,
when i was using my graph with a min and a max value on the ValueAxis it worked well but now that I only want the max to be locked it doesn't work as intended. With few datas it works great but with hundreds of datas the max seems to become random. I set it at 100 and it sometimes go to 2000 or more even though values in the graph are between 0 and 100. If I scroll through the graph, it become 100 again.
Here is the configuration of the axe in JSON :
"yAxes": [
    {
      "type": "ValueAxis",
      "max": 100,
      "baseValue": 0,
      "strictMinMax": true,
      "maxPrecision": 0,
      "rangeChangeDuration": 0
    }
  ],
![image](https://user-images.githubusercontent.com/44021489/51983493-13112e00-2499-11e9-81b4-cd05a73b390e.png)

**Comment by martynasma** [comment]
I'm afraid I can't seem to reproduce it.

Here's my quick test:
https://codepen.io/team/amcharts/pen/ae290f52db2d0574b634f20b63e33c54?editors=0010

Could you please provide a way to reproduce the issue?
