### ISSUE TITLE
Manual data grouping for large amounts of data in line series

### ISSUE THREAD

**Issue by AndiLi99** [amcharts/amcharts4#909]
Hello,

In a line series I may have up to 50,000 points. The performance for a regular chart is too slow to handle it, and I know it will be addressed in the stock chart with the data grouping functionality. While we wait for stock chart v4 to be released, is there a workaround I can use to manually group the data so the performance is not too slow?

Currently I've implemented a function which manually groups the data. However when I try to update the data in the chart when a zoom occurs I'm running into issues with the callbacks. 

Here's my attempt: https://codepen.io/andili99/pen/JxbeWZ
Edit: Here's a closer attempt: https://codepen.io/andili99/pen/WPomao

**Comment by martynasma** [comment]
amCharts support service does not cover usage of the free version of the library.

In case we verify you have reported a bug, we'll mark this issue with a `bug` label, and will get back to you when it is fixed, or we need further details.

For information on contacting amCharts support staff, refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
