### ISSUE TITLE
how to enable the label with HTML content?

### ISSUE THREAD

**Issue by zecampos** [amcharts/amcharts4#910]
I wanted the label to be clickable to be able to enter information submit a method, eg:
<input class = "w3-input w3-border" type = "text">
<button class = "w3-btn w3-blue"> Register </ button>
my line of code:
      let label = chart.createChild(am4core.Label)
            label.clickable = true
            label.isHover = true
            //label.togglable = true
            label.interactionsEnabled = true
            label.pointerOrientation = true
            label.htmlContainer =
              '<input type="button" value="More info" onclick="alert(\'You clicked on {categoryX}\')" />'
            //label.text = 'N';
            label.fontSize = 15
            label.align = 'center';
            label.isMeasured = false
            label.x = 150
            label.y = 0

**Comment by darlesson** [comment]
You can use the [html](https://www.amcharts.com/docs/v4/reference/label/#html_property) property instead of `htmlContainer`.

```
var label = chart.createChild(am4core.Label);
label.html = '<input type="button" value="More info" onclick="alert(\'You clicked on {categoryX}\')" />';
```

**Comment by zecampos** [comment]
@darlesson thanks for replying, I'm using VUE and it does not recognize the v-on: click!
