### ISSUE TITLE
Question: DateX mark period change and initial period

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#916]
Hey I have research amcharts 4 for about a couple of months. and for my understanding there are two main fields in the process of dates to screen after has been converted into date objects:
dateFormats & periodChangeDateFormats.
Now my data is depends on datePicker, this means that the data can change in terms of:
Minutes
Hours
Days
Months 
Years
Now when Data is change in matter of hours:
I need to show at first point the month+ day + hour(am/pm format) of current date and then in the rest of the points to show the hour(am/pm format) only. 

how can I achieved this goal with amcharts4, it seems to me that I need to show always the month & day & hour in am/pm for the all points and can exclude specific points from this behavior.
I have added an example:
https://codepen.io/Barak/pen/exgxyY?turn_off_js=false

Best Regards,
Barak Inbal

**Comment by BrkCoder** [comment]
I am really need an answer it is very crucial to me.

**Comment by martynasma** [comment]
You can use DateAxis' [`gridIntervals`](https://www.amcharts.com/docs/v4/reference/dateaxis/#gridIntervals_property) to modify  what time units the axis uses to build its grid from.

**Comment by BrkCoder** [comment]
thanks!
