### ISSUE TITLE
Animated heatmap

### ISSUE THREAD

**Issue by Ices-Eyes** [amcharts/amcharts4#918]
Hi, I was trying  to find out if it is possible to make an heatmap and have it animated to show changes over time. I've not been able to find out some example of this, so I'd try to post the question here...

**Comment by zeroin** [comment]
I've updated our heatmap demo (some lines in the end). It now changes data each 3 seconds and the bubbles animate radius to new values: https://www.amcharts.com/demos/bubble-based-heat-map/

**Comment by Ices-Eyes** [comment]
Ok, my mistake, I've not been really clear...I was referring to the choroplet map, so something like this chart
https://www.amcharts.com/demos/us-heat-map/
but that also change the values over the time. So for example population on the map, with a timeline that show it in 2009-2010-2011-...-2018... :)

**Comment by martynasma** [comment]
This should work similarly with geo heatmap:

https://codepen.io/team/amcharts/pen/d3c3e7d08cc6cacab766d4c2ed397c78?editors=0010

**Comment by Ices-Eyes** [comment]
Ok, thank you... I will try to elaborate on this to see if I can attach the temporal data to a slider and using the data coming from the json to animate it. Thanks :)
