### ISSUE TITLE
Q: Setting the border radius of elements

### ISSUE THREAD

**Issue by FrankMerema** [amcharts/amcharts4#919]
For the application that I build the design has no border radius on any element. I'am looking for a way to configure all the elements in such a way, that I meet our design.

The XYScrollbar has for example a default border radius. Is there any property to disable the radius (or set it to 0px)?

Thanks!

**Comment by martynasma** [comment]
How about creating a global adapter?

https://www.amcharts.com/docs/v4/concepts/adapters/#Global_adapters

Another option: create a custom theme:

https://www.amcharts.com/docs/v4/tutorials/creating-themes/

**Comment by FrankMerema** [comment]
I don't exactly know what to do now :(

I have made a screen shot of a scrollbar where you can see the border radius. I would like to have some option to make the scrollbar have no border radius. Is there a prop on the scrollbar for setting this?

![example scrollbar](https://user-images.githubusercontent.com/5937851/52194527-8c6f9e80-2854-11e9-9e88-00f73646d3e7.png)

**Comment by martynasma** [comment]
```
chart.scrollbarX.thumb.background.cornerRadius(0, 0, 0, 0);
chart.scrollbarX.background.cornerRadius(0, 0, 0, 0);
```

**Comment by FrankMerema** [comment]
Nice! Thanks for the quick reply!
