### ISSUE TITLE
CategoryAxis inside:true not respected when setting label rotation

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#922]
The `inside = true` setting of a Category Axis does not work together with label rotation. Setting a label rotation of <> 0 will place the label outside the columns, (and partly outside the SVG viewport).

This works well:

```
categoryAxis.renderer.inside=true;
categoryAxis.renderer.labels.template.rotation = 0;
```

This gets messy:

```
categoryAxis.renderer.inside=true;
categoryAxis.renderer.labels.template.rotation = 15;
```

![image](https://user-images.githubusercontent.com/13300227/52161644-9ebcd180-26c8-11e9-8ba6-46c2a412deea.png)

Codepen: https://codepen.io/team/amcharts/pen/QYvpoM?editors=0010

**Comment by martynasma** [comment]
Setting `inside = true` removes padding coming from the axis, but does not modify labels in any other way.

In fact it has some fuzzy logic, e.g. in detecting if label is horizontal (rotation = 0) or vertical (rotation = 90) and then adjusting its center settings for the best fit.

However, for intermediate rotation settings (like in the codepen) it would be too far fetched to assume the legend is horizontal or vertical, so fuzzy logic does not kick in, so you need to set your `verticalCenter` manually. E.g.:

```
categoryAxis.renderer.labels.template.verticalCenter = "bottom";
```

This fixes the issue.
