### ISSUE TITLE
ExportMenu should (probably) be invalidated when chart (or its data) is invalidated

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#926]
Hi I add the export options to my chart like so: 

```
 chart.exporting.menu.items = [{
        label: "...",
        menu: [
          {
            label: "Image",
            menu: [
              { type: "png", label: "PNG" },
              { type: "jpg", label: "JPG" },
              { type: "gif", label: "GIF" },
              { type: "svg", label: "SVG" },
              { type: "pdf", label: "PDF" }
            ]
          }, {
            label: "Data",
            menu: [
              { type: "json", label: "JSON" },
              { type: "csv", label: "CSV" },
              { type: "xlsx", label: "XLSX" }
            ]
          }, {
            label: "Print", type: "print"
          }
        ]
      }];
```

This does not show the data options though.... I am confused why no? 
What am I missing?

**Comment by martynasma** [comment]
Are you perhaps adding it on a Map? Or a chart that does not have any data set (data set directly on series)?

**Comment by jimmykane** [comment]
Dang! That was it. The data on series. Any workaround for this?

**Comment by jimmykane** [comment]
cancel that. That worked for a bit and then it's gone :-(

**Comment by jimmykane** [comment]
Nope. That is not it. Fortunately i have implemented both ways to bind data (with a flag) and even if having the data on the chart the export options do not appear for data. 

Something else that can be causing this ?

**Comment by martynasma** [comment]
Ummm... no idea. I know I must be sounding like a broken record by now, but... any chance of a codepen? :)

**Comment by martynasma** [comment]
One thing to try:

```
console.log(chart.exporting.data);
```

What does it print out?

**Comment by jimmykane** [comment]
There you go. 

https://codepen.io/anon/pen/zedGKL?=true

Its due to adding the data async.

**Comment by jimmykane** [comment]
Here it is :-) 

https://codepen.io/anon/pen/zedGKL?=true

**Comment by jimmykane** [comment]
That was it

**Comment by ciarancourtney** [comment]
> One thing to try:
> 
> ```
> console.log(chart.exporting.data);
> ```
> What does it print out?

@martynasma Sorry for reopening, but data is still missing for me in v4.1.3. I add/remove `LineSeries` to my `chart.series` dynamically, so I think chart.exporting.data is empty because I don't set `chart.data` directly.

This is a bug I think?

**Comment by martynasma** [comment]
@ciarancourtney You set data directly on series, not on chart?

**Comment by ciarancourtney** [comment]
Yes, please see my angularjs component below, I followed the example in https://www.amcharts.com/docs/v4/tutorials/dynamically-adding-and-removing-series/

Sorry, getting a codepen of this is a bit of a chore, hopefully you can follow below

```
import {default as angular, IController, IScope} from 'angular';

import * as am4core from '@amcharts/amcharts4/core';
import * as am4charts from '@amcharts/amcharts4/charts';
import {XYSeries} from '@amcharts/amcharts4/.internal/charts/series/XYSeries'

import {Datapoint, Trend} from "@app/common/types";


interface seriesList {
  name: string
  series: XYSeries
}


export class ChartController implements IController {

  chart: am4charts.XYChart;
  data: Trend[];
  seriesList: seriesList[] = [];

  /*@ngInject*/
  constructor(
    private $scope: IScope,
  ) {}

  $onInit(): void {
    this.makeChart();
    this.addVerticalSlider();
    this.enableExport();

    this.$scope.$watchCollection('$ctrl.data', (new_data: Trend[], old_data: Trend[]) => {

      if (new_data.length > old_data.length) {
        const added = new_data.filter(item => old_data.indexOf(item) < 0);
        for (let series of added) {
          this.addSeries(series.values, series.name)
        }
      } else if (new_data.length < old_data.length) {
        const removed = old_data.filter(item => new_data.indexOf(item) < 0);
        for (let series of removed) {
          this.removeSeries(series.name)
        }
      }
      console.log(this.chart.exporting.data);
      this.chart.exporting.menu.invalidate();
    });
  }

  addVerticalSlider(): void {
    // Add vertical range slider
    // https://www.amcharts.com/demos/date-based-data/
    this.chart.scrollbarY = new am4core.Scrollbar();
    this.chart.scrollbarY.parent = this.chart.leftAxesContainer;
    this.chart.scrollbarY.toBack();
  }

  enableExport(): void {
    this.chart.exporting.menu = new am4core.ExportMenu();
    this.chart.exporting.menu.invalidate();
  }

  makeChart(): void {
    this.chart = am4core.create('chartdiv', am4charts.XYChart);
    this.chart.paddingRight = 20;

    const dateAxis = this.chart.xAxes.push(new am4charts.DateAxis());
    dateAxis.renderer.grid.template.location = 0;

    const valueAxis = this.chart.yAxes.push(new am4charts.ValueAxis());
    valueAxis.renderer.minWidth = 35;

    this.chart.cursor = new am4charts.XYCursor();

    // Add horizontal range slider
    this.chart.scrollbarX = new am4charts.XYChartScrollbar();
  }

  addSeries(data: Datapoint[], name: string): void {
    const series = new am4charts.LineSeries();
    series.dataFields.dateX = 'x';
    series.dataFields.valueY = 'y';
    series.name = name;
    series.tooltipText = name + ' {valueY.value}';
    series.data = data;

    this.chart.series.push(series);

    this.seriesList.push({
      name:name,
      series:series
    });
  }

  removeSeries(name: string) {
    if (this.seriesList.some(a => a.name === name)) {
      const series = this.seriesList.find(s => s.name === name);
      this.chart.series.removeIndex(
        this.chart.series.indexOf(series.series)
      ).dispose();
      this.seriesList = this.seriesList.filter(s => s.name !== name);
    }
  }

  $onDestroy() {
    this.chart.dispose();
  };
}


export const ChartComponent: angular.IComponentOptions = {
  bindings: {
    data: '<',
  },
  controller: ChartController,
  template: `
    <div id='chartdiv' style="width: 100%; height: 500px"></div>
  `
};
```

**Comment by jimmykane** [comment]
@ciarancourtney I think @martynasma  said it won't work with data on series.

**Comment by ciarancourtney** [comment]
So if you use the approach I've used, how do you export csv/json data?

**Comment by jimmykane** [comment]
What I did in my case was quite complicated. But I do suspect that flattening and adding the data to the export obj might do the trick. After the series data is done. But lets wait for recommendations from @martynasma .

**Comment by jimmykane** [comment]
(in my case I have added a toggle to allow the user if he wants export to csv etc the app to put the data on the chart and not per series). That affects performance in my case that is why I prefer to have per series and a toggle for the user .

**Comment by martynasma** [comment]
What I would do is to add a `"data"` adapter on `chart.exporting`.

This way you could implement your own logic on how to aggregate the data from individual series into a single data array, which could be used to export.

**Comment by ciarancourtney** [comment]
OK if I add to the `chart.data` in addSeries now, like so...

    series.data = data;
    this.chart.series.push(series);
    this.chart.data.push(data);

...data export works, but it seems like a hack, whats the point in adding data to each series if I'm adding it to the chart data also?

**Comment by jimmykane** [comment]
@ciarancourtney if you have no special need to add data per series, eg an async operation just add it to the chart only. Like so: 

```
this.chart.series.push(series);
this.chart.data.push(data);
```

**Comment by jimmykane** [comment]
@ciarancourtney  Perhaps this helps. Data can be independent from series. 
For example you can only add data to the chart and dynamically add the series that actually define what to show from the data added on the chart.

**Comment by ciarancourtney** [comment]
> @ciarancourtney Perhaps this helps. Data can be independent from series.
> For example you can only add data to the chart and dynamically add the series that actually define what to show from the data added on the chart.

OK I guess that makes sense in the context of amcharts. In my domain I'm dealing with multiple time series trends, so my mental model is series == data

**Comment by ciarancourtney** [comment]
@martynasma I'm still confused as to what the best approach to take is, my requirements are:

1. Ability to add/remove series dynamically
2. Ability to export csv/json of the currently active series in the chart
3. Each series has a `unit` string which should dynamically be allocated to a matching `ValueAxis`

My datapoint interface is:

    interface Series {
      ReadingTime: number;  // assigned to DateAxis
      [key: string]: number;   // assigned to ValueAxis
    }

`ReadingTime` is the common datetime among all the series, so export should be able to normalize on this.

This seems like a very common use case that should be covered automatically by amcharts, without manual manipulation of series.data or chart.data.

Your suggestion of using a `data` adapter for export still requires me to add and remove data from `chart.data`

Thanks and keep up the good help
