### ISSUE TITLE
Location and DateAxis does not work according to the tutorial

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#927]
Hi great amCharts its me again! 

I was looking to this tutorial https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis and unfortunately the tutorial (codepen) does not work as it should.

**Comment by martynasma** [comment]
Yo. Does not work how?

**Comment by martynasma** [comment]
The preview is for a chart that is zoomed in to showcase how labels are not centered, event when they come in hourly increments.
