### ISSUE TITLE
How to get/select instances of charts created on a page.

### ISSUE THREAD

**Issue by gauravhrana** [amcharts/amcharts4#931]
We are trying to create a dashboard page. And user can select which chart can be added on the page. The requirement is to allow user to pick a theme for his liking for each chart.  We are using Version 4 for AmCharts. 

How do we get the handle for each chart that is being created? As soon as user clicks on a theme, the theme should reflect on the graph itself. Each chart has different Id white it is being created. Any link to the documentation or code snipped would help. 

Thanks

**Comment by martynasma** [comment]
To access all chart instances use `am4core.registry.baseSprites` or `am4core.registry.baseSpritesById`.

Please note that you cannot re-apply a theme to an existing chart object. To apply new theme, you need to first `dispose()` old chart object, `unuseAllThemes()`, `useTheme()`, then create chart object anew.

**Comment by gauravhrana** [comment]
I was not able to find `am4core.registry.baseSprites` or `am4core.registry.baseSpritesById`. Here's how i achieved it. When creating the charts for the first time, i add all the chart objects in an array. As soon as user tries to change a theme, i get the chart from the array, i dispose and delete it from the array and recrete the same chart using new theme as u pointed out. I call `unuseAllThemes()` method and load new theme using `useTheme()` method.

**Comment by moghthalkushal** [comment]
am4core.registry.baseSprites we can get the instance , how do we use baseSpritesById ? , it doesn't expect the div-id , earlier we could get the divs and it's ids too , how can it be done now ?

**Comment by moghthalkushal** [comment]
Found it : am4core.registry.baseSprites[0].htmlContainer.id , can get you ids , please suggest if you have any better approaches .
