### ISSUE TITLE
'Using Webpack' guide broken

### ISSUE THREAD

**Issue by grasmachien** [amcharts/amcharts4#934]
https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/

Both 'canvg' and 'responsive.js' need another loader so the example in the docs is incomplete.

<img width="817" alt="screenshot 2019-02-06 at 17 45 06" src="https://user-images.githubusercontent.com/6026424/52357739-f6479e00-2a36-11e9-8d64-3e4ffcba91d2.png">

**Comment by Pauan** [comment]
The documentation is correct. There is a bug in Webpack which is causing the error: https://github.com/amcharts/amcharts4/issues/868

You can read that to see various workarounds/fixes for it.

Since this isn't a bug with amCharts, I'm going to close this, thanks for the report!
