### ISSUE TITLE
Setting PropertyField to a hexformatted colour causes white lines

### ISSUE THREAD

**Issue by AndiLi99** [amcharts/amcharts4#936]
Here's a codepen which demonstrates the issue.
https://codepen.io/andili99/pen/gqXwOX

**Comment by martynasma** [comment]
Hm, no white lines. What am I missing?

![image](https://user-images.githubusercontent.com/1458520/52414577-6ca6d780-2aed-11e9-9bba-829398b1f88c.png)

**Comment by AndiLi99** [comment]
![circled2](https://user-images.githubusercontent.com/19602233/52418644-7bc16180-2abc-11e9-94d9-4a810405afab.png)
I blew up this one with nearest neighbour interpolation. It may be easier to see here.

**Comment by martynasma** [comment]
This is exact same issue as #937. Please read explanation there.

**Comment by AndiLi99** [comment]
The underlying issue is the same. In this case if you use color objects the engine combines each of the segments into one big segment if they are the same color.
