### ISSUE TITLE
Setting Property Field for modified colors creates white lines

### ISSUE THREAD

**Issue by AndiLi99** [amcharts/amcharts4#937]
Each color is an am4core.color object with the lighten function called.
Here is a codepen which demonstrates the issue.
https://codepen.io/andili99/pen/exegwa

**Comment by AndiLi99** [comment]
This showcases the same issue: https://codepen.io/andili99/pen/KJyWzJ

**Comment by martynasma** [comment]
Ummm... not seeing any white lines. Or am I missing something here?

![image](https://user-images.githubusercontent.com/1458520/52414493-2d788680-2aed-11e9-81b7-70671a54966d.png)

![image](https://user-images.githubusercontent.com/1458520/52414505-38331b80-2aed-11e9-89c8-a76de4ef79a5.png)

**Comment by AndiLi99** [comment]
![circled](https://user-images.githubusercontent.com/19602233/52418299-b5459d00-2abb-11e9-9575-e26500bc2612.png)
Perhaps try changing your monitor settings? I've circled the most obvious one.

**Comment by martynasma** [comment]
Gotcha. This is coming from segments not starting and ending at exact pixel, hence renderer antialiasing the edges and creating a slight lighter edge.

At this time, there's no workaround, I'm afraid.

**Comment by AndiLi99** [comment]
This setting seems to fix the issue:
`series.shapeRendering = 'crispEdges'`

**Comment by AndiLi99** [comment]
Is it possible to apply the shapeRendering setting to only the fill blocks, and not the stroke?

**Comment by martynasma** [comment]
Good catch. Sorry I did not come up with this myself. And thanks for sharing your solution.

I can see you are applying `shapeRendering` using event.

This works for me while setting directly on template as well:

```
series.segments.template.shapeRendering = "crispEdges";
```

To answer your other question, fill element of the segment is in segment's `fillSprite`. (it's undocumented, not sure why)

**Comment by AndiLi99** [comment]
I can't seem to combine the template method with fillSprite.

I tried: `series.segments.template.fillSprite.shapeRendering = "crispEdges";`

**Comment by martynasma** [comment]
Hm, no that does not work, and due to internal organization probably won't :(

The only workaround I can think of is to have to separate Series: one for fills (strokeOpacity = 0 and crispEdges set) the other just for the line.
