### ISSUE TITLE
AxisLabel doesn't have 'getTooltipText' adapter

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#938]
https://www.amcharts.com/docs/v4/reference/axislabel/#Adapters

So now there is no possibility to do something like this:
`categoryAxis.renderer.labels.template.adapter.add('getTooltipText', text => {...})`

**Comment by martynasma** [comment]
If you want to add an adapter to a `Label` use one of its adapters, like `text` or `textOutput`.

**Comment by dmsmaxim** [comment]
But I want adapter for tootip. Not for the label's text. These are different parts

**Comment by jimmykane** [comment]
Example: 
```
 // Set the axis
    series.yAxis = yAxis;
    // Add the tooltips
    yAxis.adapter.add("getTooltipText", function (text, target, key) {
      return `something`;
    });

```

**Comment by dmsmaxim** [comment]
Example from your documentation:
https://codepen.io/team/amcharts/pen/NBWrWG
```
var label = categoryAxis.renderer.labels.template;
...
label.tooltipText = "{category}";
```

So I can set `tooltipText` for the label...
But there is no possibility to use an adapter for dynamically generate the tooltip's text, as I could do for some other elements

**Comment by jimmykane** [comment]
There you go @dmsmaxim 

https://codepen.io/anon/pen/ErojWX


Just add 

```
label.adapter.add("tooltipText", function (text, target, key) {

          return text + 'yo';
        });

```

But you need first as usual to add the tooltipText defined not only the adapter as the adapter works on top
