### ISSUE TITLE
Hiding legend for one series in multiline graph

### ISSUE THREAD

**Issue by amitsarwara** [amcharts/amcharts4#939]
I am using multiline graph, suppose i am showing Blood pressure on graph. There are two values for blood pressure systolic and diastolic. I have shown them in two series on same y axis. Everything is working fine but it is showing two legend (one for systolic and other for diastolic) i want to show only one legend for BP also click the legend should be able to hide/show both series. 

I have searched a lot for this. I don't even know if its possible or not. I anyone can point me to documentation it will helpful.

**Comment by iliyaM** [comment]
Hey I have the same issue also, I have 2 series in a chart and I want to toggle between them, which means only one series can be visible at a time and only one legend label is active.
How can I achieve this goal? please provide a valid example !

**Comment by BrkCoder** [comment]
Hey I have the same issue also, please provide an example or solution:
https://github.com/amcharts/amcharts4/issues/965

**Comment by amitsarwara** [comment]
@iliyaM @BrkCoder , While i was looking for a solution for myself, i did came across the functionality that i think might work for you. I haven't tested it but if it is helpful then cool :)

https://www.amcharts.com/docs/v3/tutorials/using-legend-to-show-only-one-graph-on-click/

**Comment by martynasma** [comment]
Just seeing this.

To disable series from appearing in legend use [`hiddenInLegend`](https://www.amcharts.com/docs/v4/reference/series/#hiddenInLegend_property).

To automatically hide/show related series use series' `hidden`/`shown` events.

https://codepen.io/team/amcharts/pen/moyWJW

**Comment by tscislo** [comment]
@martynasma how to do this in AmCharts 5?

**Comment by jameskajon** [comment]
> @martynasma how to do this in AmCharts 5?

You can control what the legend shows by [setting the legend data](https://www.amcharts.com/docs/v5/concepts/legend/#legend-data).

But that is not equivalent to what `hiddenInLegend` did. The closest I've found is:
```js
series.get("legendDataItem").get("itemContainer").hide();
```

And if your legend is made after your series is, you can use an event:
```js
series.events.once("datavalidated", () => {
  series.get("legendDataItem").get("itemContainer").hide();
});
```
