### ISSUE TITLE
MapLine (multiGeoLine) in JSON config somehow pans map

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#940]
I have a simple World Map, in JSON config. Everything works fine, but when I display a Map Line (MultiGeoLine) the map somehow pans to (more or less) center this map line, resulting in a map that has part of the areas missing (when panning East).

The bug comes from this part:

```
  {
    
    "type": "MapLineSeries",
    
    "data": [{
      "id": "DFW-SFO",
      "multiGeoLine": [
        [
          { "latitude": 32.8972, "longitude": 262.9623 },
          { "latitude": 37.6194, "longitude": 237.627 }
        ]
      ],
      "text": "78500 passengers"
    }],

    "mapLines": {
      "alpha": 1,
      "strokeWidth": 3,
      "stroke": "red",
      "tooltipText": "{text}"
    }
    
  },
```

Demo: https://codepen.io/team/amcharts/pen/ec83cf1e9ce0fa128cb44b0ceb211155?editors=0010.

If I replace the JSON with object based JS, this panning does not happen. You can verify this in the Codepen demo by removing the Map Line series from the JSON config, and uncommenting the `ready` listener at the bottom of the script.

**Comment by martynasma** [comment]
Longitudes used in line data are out of the allowed range (-180 to 180).
