### ISSUE TITLE
Enhancement: Easy way to remove DateAxis labels from XYChartScrollbar

### ISSUE THREAD

**Issue by AndiLi99** [amcharts/amcharts4#941]
Here's my codepen: https://codepen.io/andili99/full/exegwa

I want to remove the dates from my scrollbar, how can I achieve this?

**Comment by martynasma** [comment]
```
scrollbarX.scrollbarChart.events.on("ready", function(ev) {
  ev.target.xAxes.getIndex(0).renderer.labels.template.disabled = true;
});
```

**Comment by martynasma** [comment]
I suppose we could use some better way. I'll leave this open for when we come up with something better.

**Comment by AndiLi99** [comment]
Thank you!
