### ISSUE TITLE
Removing grid lines via config field doesn't work

### ISSUE THREAD

**Issue by AndiLi99** [amcharts/amcharts4#942]
Here is a codepen: https://codepen.io/andili99/pen/pGpweW.

This doesn't work.
`dateAxis.config = 
  {
  "renderer": {
    "grid": {
      "template": {
        "disabled": true
      }
    }
  }
}`
While this does:
`dateAxis.renderer.grid.template.disabled = true;`

**Comment by martynasma** [comment]
Don't use `template`.

This will work:

```
dateAxis.config = { "renderer": { "grid": { "disabled": true } } }
```

This is in the docs BTW:
https://www.amcharts.com/docs/v4/concepts/json-config/#List_templates
