### ISSUE TITLE
Setting CircleBullet fill based on data fields

### ISSUE THREAD

**Issue by reikidd** [amcharts/amcharts4#945]
I'm trying to dynamically set the fill of each bullet based on a data field using adapters. 
The code can be found [here](https://codepen.io/anon/pen/MLQWLG). The specific code for the adapter

> bullet.circle.adapter.add("fill", function(fill, target) {
    if (!target.dataItem) {
      return fill;
    }
    var isViolated = target.dataItem.getWorkingValue("Violation");
    return isViolated === 0 ? am4core.color("green") : am4core.color("red");
  });

and I'm trying to change the color based on the Violation value, but I can't understand how to access the value from a specific data field. Could you guys help me?

**Comment by martynasma** [comment]
I suppose you can get that directly from `dataContext`:

```
var isViolated = target.dataItem.dataContext.Violation;
```

**Comment by reikidd** [comment]
This worked, thanks.
