### ISSUE TITLE
Consistent width for Y axis labels

### ISSUE THREAD

**Issue by gobrendan** [amcharts/amcharts4#947]
Hi, is there a way to specify a width for the Y axis labels? Also, is there a way to add ellipsis when the label is too long?

In the following example, I would want the "200,000" and "1000" labels to be the same width. 

https://codepen.io/team/amcharts/pen/PBZWja?editors=0010

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/tutorials/wrapping-and-truncating-axis-labels/
