### ISSUE TITLE
Connect custom legend with chart series

### ISSUE THREAD

**Issue by amitsarwara** [amcharts/amcharts4#951]
i have created custom legends for the chart and i want them to be connected with series in the chart. So when i toggle the legend series should hide or show. one way of doing this by manually setting an click event and use `show() and hide()` method to toggle.

I am asking is there any way that i can connect them to the series so that default toggle can work? 

Thanks

**Comment by martynasma** [comment]
Yes, add and event to legend's items:

https://www.amcharts.com/docs/v4/concepts/legend/#Handling_events
