### ISSUE TITLE
Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by vinuengico** [amcharts/amcharts4#952]
I have used the XY chart and whenever I move my mouse anywhere on the page console logs an error saying- "Right-hand side of 'instanceof' is not callable"

It keeps logging the same error as long as I am moving the mouse anywhere on the page.

I am not using animated js or anything else, just the core and charts js file.

![image](https://user-images.githubusercontent.com/39088074/52564528-7486b480-2e2a-11e9-823c-434150d46b41.png)

**Comment by martynasma** [comment]
I'm afraid we can't reproduce this.

Would you be able to post a CodePen/jsFiddle of your chart so that we can test?

**Comment by cmdeveloped** [comment]
I'm also running into this issue. I'm running Vue 2.5.17 and using the ES6 method. I'm using the MapChart instance. Researching further, but wanted to give an update.

**Comment by cmdeveloped** [comment]
Found that the issue being thrown is in Interaction.js.
Line 1999;
`Interaction.prototype.isPointerTouch = function (ev) {
        if (typeof Touch !== "undefined" && ev instanceof Touch) {
            return true;
        }`

Removing `ev instanceof Touch` resolved the issue. Still testing.

**Comment by wolfpack4417** [comment]
I'm getting this same issue. A collaborator on Foundation (which I am also using) posted this: https://github.com/zurb/foundation-sites/issues/11674

**Comment by rossb89** [comment]
I'm just posting this in case anyone else comes along here and has the same issue with Foundation and amcharts4.
I didn't spend too much time digging but Foundation does something with it's own version of the Touch object, which is different to what amcharts is expecting Touch to be.
On the page we have a map using this library, we don't really care about the Foundation Touch JS stuff, so a really lame nasty hack was just to add this: `window.Touch = undefined;` before we then run the initialisation of the amcharts sutff...
It's super lame but gets the job done.
