### ISSUE TITLE
"tooltip.tooltipHTML" incorrect content & container width calculation if HTML contains <img> tag

### ISSUE THREAD

**Issue by a6848418** [amcharts/amcharts4#953]
[https://codepen.io/a6848418/pen/daePao](https://codepen.io/a6848418/pen/daePao)

Hi There!

I think there is a little bug within container size calculation method that in my case gives an incorrect tooltip container size when I embed an image into the tooltip using tooltipHTML property

`"tooltipHTML": "<img  class=\"align-bottom\" src=\"assets/img/flags/{id}.png\" alt=\"{id}\">&nbsp; {name}",`

It looks like container size calculation method gets called before image is loaded therefore container size  is just less then the image width in size since method is unable to calculate image with of an image that does not exist yet.

if another map polygon tooltip is toggled and then back initial one then size is calculated fine  and we see correct tooltip container size

another interesting observation is that `tooltip.contentWidth` & `tooltip.measuredWidth` and other multiple width properties of the tooltip event ("shown") target reflect properties of the previously fired event target instead of the current event target fired.

Anyway, codepen link with an example is here:
[https://codepen.io/a6848418/pen/daePao](https://codepen.io/a6848418/pen/daePao)

Thanks in advance for reading this)

Cheers!
Andrey

**Comment by martynasma** [comment]
The tooltip does not watch for load events for each individual image in it so it does not resize itself on load.

I suggest adding width/height parameters to your `<img>` so the tooltip is sized correctly.

**Comment by a6848418** [comment]
Thanks! your suggestion helped to solve my issue.
