### ISSUE TITLE
Does V4 have CSS documentation? 

### ISSUE THREAD

**Issue by gobrendan** [amcharts/amcharts4#954]
V3 has a long list of CSS properties. Does V4 have something like this?

https://www.amcharts.com/docs/v3/tutorials/css-class-names/

**Comment by notacouch** [comment]
Not quite. By and large styles are done via JavaScript or JSON config.

With the [`autoSetClassName`](https://www.amcharts.com/docs/v4/reference/options/#autoSetClassName_property) option set to `true`, all the SVGElements will have relevant CSS classes applied according to their v4 JavaScript Class inheritance. If a series has an `id`, that will appear as a CSS class `amcharts-{id here}` on its SVG group element. It can be used to single out one series over another.

Here's a demo where that is utilized:
https://www.amcharts.com/demos/css-animations/

The option is enabled like so:

```javascript
am4core.options.autoSetClassName = true;
```

Say you provide a series with an `id`, e.g.:

```javascript
series.id = "g2";
```

That series' SVG group element will have a CSS class `amcharts-g2`. In the demo, it also has all the following classes:

```html
<g class="amcharts-g2 
  amcharts-Sprite-group
  amcharts-Container-group
  amcharts-Component-group
  amcharts-Series-group
  amcharts-XYSeries-group
  amcharts-LineSeries-group">...</g>
```

Once that `autoSetClassName` option is enabled, at the moment you're kind of on your own from there, but at least discovery of what to style is sensible given the liberal provision of CSS classes.

Asides from that, there are our Popups and Modals. Those are not SVGElements within the chart, just regular elements. They do ship with some default styling, the reference for which as well as how to modify them can be found here:
["Popups and Modals: Appearance via CSS"](https://www.amcharts.com/docs/v4/concepts/popups-and-modals/#Appearance_via_CSS)

**Comment by dmitryrn** [comment]
Please add docs for styling for V4 🙏

**Comment by notacouch** [comment]
@dmitryrn  Can you elaborate/specify? What are you looking to do? Or just a sample like the above to help get people going?

**Comment by notacouch** [comment]
@gobrendan @dmitryrn: @martynasma has added an official guide on CSS in v4:
https://www.amcharts.com/docs/v4/tutorials/chart-element-class-names-and-css/

Hope it helps.

**Comment by gobrendan** [comment]
Thanks, all! I was looking for a CSS reference (list of class names) for AmCharts V4. The following resource was helpful. However, I moved on to using Highcharts. 

https://www.amcharts.com/docs/v4/tutorials/chart-element-class-names-and-css/
