### ISSUE TITLE
Cursor with fullWidthLineX and no xAxis tooltip does not animate 

### ISSUE THREAD

**Issue by CarlosHdez** [amcharts/amcharts4#956]
This can be replicated with the first demo in the `Animations` document

![animation_bug](https://user-images.githubusercontent.com/5401623/52600224-8c593b00-2e20-11e9-9a14-7d3c06d985a0.gif)

I do not want to have the tooltip but still like the animation that moves the cursor. I don't know if this is a bug or I need to configure differently my cursor.

**Comment by martynasma** [comment]
https://codepen.io/team/amcharts/pen/ed355445d092fc9d17c3e6ebda0e87ea

**Comment by martynasma** [comment]
I'm afraid we won't be able to implement this fix. Sorry.
