### ISSUE TITLE
Chart title does not display tooltip on hover

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#96]
Looks like something is blocking it from receiving `"over"` event.

Example: https://codepen.io/team/amcharts/pen/9698d1d9246d23de9043ee73d8119825?editors=0010

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.31](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.31).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by dswitzer** [comment]
Good work! It appears to be working correctly now.
