### ISSUE TITLE
4.1.5 breaks Firefox series and labels when the chart is inside an Angular material tab 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#960]
With 4.1.6 the labels on external container are not clickable for some reason and the series flicker 

I cannot reproduce this with a codepen unfortunately atm. I will come back though

**Comment by jimmykane** [comment]
And its related to webpack etc

**Comment by martynasma** [comment]
Alright. Let us know if you can find a way to reproduce it.

**Comment by jimmykane** [comment]
Hi  @martynasma  I cannot provide a codepen or plunkr. 
I spend about 5h and cannot reproduce it but it's well reproducable locally and if I push that to production 

https://drive.google.com/file/d/1-RLqxNqWzInfU5b37itsploVrCDH940-/view

Look at the above video 

There are no console errors and this breaks only with 4.1.6  
4.1.5 is ok

**Comment by jimmykane** [comment]
It only breaks on Firefox and labels are not clickable

**Comment by jimmykane** [comment]
4.1.7 does not solve this :-(

**Comment by martynasma** [comment]
Ummmmm... any idea how we can get our hands on your setup with the issue?

You can email us at contact@amcharts.com if you don't want to post that stuff here.

**Comment by jimmykane** [comment]
I have found out, although its quite hard to reproduce on codepen that it's related to tabs and visibility

**Comment by jimmykane** [comment]
Sorry for the accidental close. 
I have to dig more about this issue. 
If the charts are inside a tab that is visible on load that works. 
If the chart is inside a tab that get visible after the chart has been created then the issue appears.

**Comment by martynasma** [comment]
Alright. That's a progress :)

Let us know if you're able to reproduce it outside your app.

What are yo using for tabs btw? Is it some custom stuff, or a framework?

**Comment by jimmykane** [comment]
I can confirm that this broke actually with 4.1.5  the one that fixes the angular issues

**Comment by zeroin** [comment]
Could you try to call `chart.deepInvalidate()` at the moment the visibility of a tab changes to visible?
