### ISSUE TITLE
In 4.1.6. date axis does not format the input date correctly

### ISSUE THREAD

**Issue by AlexAloman** [amcharts/amcharts4#961]
In a XY chart with date axis the chart starts with the previous date. 
Let's take as an example a demo from your website: https://www.amcharts.com/demos/date-based-data/#code
The first day to start should be July 27 and the end date January 30, but instead they are July 26 and January 29. 

For the 4.1.5 version the data is bounded correctly.

**Comment by martynasma** [comment]
This has been fixed in 4.1.8.

Let me know if you are still seeing it after upgrading.
