### ISSUE TITLE
Angular Compile Error 

### ISSUE THREAD

**Issue by robjean9** [amcharts/amcharts4#962]
Hello,

I`m using this example https://www.amcharts.com/demos/variable-radius-radar/

But It works, but every time that i compile my project are breaking.

![screen shot 2019-02-13 at 10 13 48](https://user-images.githubusercontent.com/5704383/52711121-241d6d00-2f78-11e9-8710-ce626994a389.png)
![screen shot 2019-02-13 at 10 14 11](https://user-images.githubusercontent.com/5704383/52711126-25e73080-2f78-11e9-8070-a0c9e7fee0fa.png)

**Comment by Pauan** [comment]
@robjean9 Sometimes TypeScript isn't smart enough to figure out the types, so you need to put in some type annotations:

```ts
let scoreAxis = chart.xAxes.push(new am4charts.CategoryAxis<am4charts.AxisRendererCircular>());

let valueAxis = chart.yAxes.push(new am4charts.ValueAxis<am4charts.AxisRendererRadial>());
```
