### ISSUE TITLE
Question: toggle series visibility according to current legend for multi series chart

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#965]
Hey I have a chart with multiple series: 2 series and I have a desire behavior which I want to achieve, only one series should be visible and only one legend item should be active at a time.
I have tried many ways to manipulate the chart and listen to toggle events, but I can't find a suitable solution for this problem.
Please provide an example or reasonable guidelines for achieving this desired behavior!

Best Regards,
Barak Inbal

**Comment by martynasma** [comment]
Here's an example:
https://codepen.io/team/amcharts/pen/9be3affdc0bf232824a3bdf2f968cf79?editors=0010

**Comment by BrkCoder** [comment]
thanks!
