### ISSUE TITLE
Date Axis points not matching grid

### ISSUE THREAD

**Issue by jbarbede** [amcharts/amcharts4#968]
I'm not sure if my chart settings are wrong or not but I have an issue when displaying a line serie with a Date Axis : points are not correctly displayed on the grid.

I have a pen code to illustrate that: https://codepen.io/anon/pen/rPZVev

When moving the XYcursor, you can easily see that the point for example for April 15th is not synchronized with the grid bar that indicates the date April 15th (some picture could be more explicit):

![amcharts v4 date axis 1](https://user-images.githubusercontent.com/263307/52755181-e76e6780-2fb1-11e9-8368-d9cc47d8ef0e.png)

Is this some normal behavior or do I need to adjust some setting to get the grid and the points synchronized?

**Comment by jimmykane** [comment]
I wonder if you resize the window (x) does this get fixed? I had kinda the same in the past

**Comment by jbarbede** [comment]
I tried but it doesn't fix the issue.

**Comment by martynasma** [comment]
On DateAxis grid/label is shown at the beginning of the cell, while LineSeries data point is shown in the middle.

It's by design.

You can move your grid/label to middle as well using this:

```
dateAxis.renderer.grid.template.location = 0.5;
dateAxis.renderer.labels.template.location = 0.5;
```

**Comment by bcronje** [comment]
> On DateAxis grid/label is shown at the beginning of the cell, while LineSeries data point is shown in the middle.
> 
> It's by design.
> 
> You can move your grid/label to middle as well using this:
> 
> ```
> dateAxis.renderer.grid.template.location = 0.5;
> dateAxis.renderer.labels.template.location = 0.5;
> ```

@martynasma Is there a way to do this by moving the LineSeries data points to the beginning of the cell instead of moving the axis grid/label to the middle? Because if you move the axis labels to the middle the chart ends up with lots of whitespace/padding if there aren't many data points in the chart.
