### ISSUE TITLE
Add how to destroy the chart in all framework tutorials

### ISSUE THREAD

**Issue by peluprvi** [amcharts/amcharts4#97]
I'm using Vue and followed your tutorial.

`am4core.create("chartdiv", am4charts.XYChart)` create a new chart element and it needs to be assined to a local variable otherwise it reacts changes and can generate memory leak.

The chart *must* be destroyed with the component. It *can* also be destroyed when it is not displayed (to better performance on a page with tabs or by using css display).

With that in mind:
- What is the better way to get the chart element and destroy it?
- The chart destroy process must be included into the tutorial on `beforeDestroy` or `destroyed` [Lifecycle hook](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram)
- Angular, React, and others must be updated if they have the same reactivity

To test it, you can:
- Follow the Vue amCharts4 tutorial
- Create a second page (without a chart) using vue-router
- Open the Chrome Performance and start profiling record
- Moving from a chart page to a non chart page the chart must be destroyed
- Returning from the non chart page to a chart page the chart should appear

**Comment by jimmykane** [comment]
You can dispose the chart on destroy or when needed. 
You should also delete the assigned ref var via eg `delete this.chart` where `this.chart` is assigned after calling `create`

**Comment by ailon** [comment]
Thank you @peluprvi for bringing this up. We didn't do cleanup in our Vue tutorial since there was a known issue #65 with our dispose handling. Now that dispose() is fixed we've updated the tutorial to include the cleanup code on beforeDestroy().

Please make sure that you have beta 30 or later to make use of it.

**Comment by martynasma** [comment]
Since this has been address, I'm gonna go ahead and close this. But please let us know if there are still pending issues with this.

**Comment by peluprvi** [comment]
Thanks for the return and for updating the tutorial!
The dispose error stopped, but the main thing here is that JS Heap only grows up when using `this.chart.dispose`.
What I want is to test dispose it without using `this` and see if the profiling results looks different.

My profiling (with dispose):
0-30s = no chart, just a page with a button.
30-60s = 2 column charts, simple, little, just 12 columns each, wothout any other chart element
60s-90s = another page without chart
90s-120s = the same 2 column charts page as before

![image](https://user-images.githubusercontent.com/1561360/41786445-df539098-761b-11e8-9a6e-b8fa3255a6e8.png)

Since I dispose the chart, its script is not expected to run between 60s-90s, but it is running.

Also, inserting it into `this.data` increases a lot of memory usage and some CPU usage, since the chart object is too large and Vue assumes that each chart animation frame is an update to react changes. You can compare with the profiling bellow, without setting it to `this.data` and without `dispose`:

![image](https://user-images.githubusercontent.com/1561360/41787352-86c13ff4-761e-11e8-9fad-afdc4654a44e.png)

Please let me know if you need more details to dig in it.

**Comment by martynasma** [comment]
@peluprvi This seems like a generic memory leak issue, rather than something related to Vue/Angular. I'll keep this closed.

We're currently investigating very similar issue, but feel free to open up a separate GirHub Issue for it.
