### ISSUE TITLE
Allow contributions

### ISSUE THREAD

**Issue by ciarancourtney** [amcharts/amcharts4#970]
I'm assuming you develop on a private repo and push version snapshots to this repo?

Would you consider a more open development approach so contributors can... contribute?

**Comment by martynasma** [comment]
Thank you for your willingness to help!

We are considering it and will allow contributions in due time.

Unfortunately, that is as technical as legal issue. If you ever contributed to a company owned non standard OS license project, you'd probably needed to go through the process of contributor onboarding which includes signing agreements, waivers, and other legal BS.

We're not Google or Facebook, and can't handle a lot of legal overhead, not to mention how to organize it technically, hence the delay.

We'll get there, eventually ;)

**Comment by martynasma** [comment]
We're planning on accepting code contributions after all. Sorry.

**Comment by ciarancourtney** [comment]
@martynasma not planning?

**Comment by stav** [comment]
What about contributing to the awesome documentation?
