### ISSUE TITLE
Series with empty values sometimes get their tooltip stuck on adjacent date

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts4#971]
![2019-02-14_16-47-11](https://user-images.githubusercontent.com/1458520/52794285-3252b280-3078-11e9-9f2a-364a9025c019.gif)

Example:
https://codepen.io/team/amcharts/pen/169cd3b4888acc1eefaafaeb3ff11a71?editors=0010

**Comment by RobbiesCode** [comment]
I just encountered the same issue. Codepen here: https://codepen.io/team/amcharts/pen/89dd4e4f8eb29a17dc19542761c9af35?editors=0010.

**Comment by martynasma** [comment]
Fixed in [4.1.8](https://github.com/amcharts/amcharts4/releases/tag/4.1.8).

## [4.1.8] - 2019-02-15

### Added
- JSON: You can now specify both list of items and template settings for `ListTemplate`, e.g.: `titles: { template: { ... }, values: [{ ... }] }`. Specifying it the old way will still work.

### Changed
- `DateAxis` will now pay attention to `dateFormatter.firstDayOfWeek` when grid is in "weekly" mode.

### Fixed
- Using `proprtyFields` on a `LineSeries` sometimes could result in an error. (fix by @AndiLi99)
- French locale (fr_FR) updated for correct decimal/thousands separators.
- Export: `scale` in image export options was being ignored.
- JSON: `cursor.snapToSeries` was not working in JSON configs.
- Selection was acting funky when zooming `DateAxis` and cursor moved out of plot area.
- An infinite error message loop fixed which was happening if series was added and there was no X or Y axes defined.
- Tooltip on the last available data item was left visible even if cursor moved to the date where the series had no data points.
- When `snapToSeries` was enabled in `XYCursor`, vertical line was not shown.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
