### ISSUE TITLE
XY chart: extremely slow rendering comparing to amcharts-v3

### ISSUE THREAD

**Issue by ivromas** [amcharts/amcharts4#972]
**Background:**
Migrating chart from v3 to v4 version

**Problem:**
#42 is reproduced.

XY chart with bullets is build based on ~44k points, page with chart-v4 becomes unavailable for usage after rendering bar shows 100% (it stops responding)
Chart-v3 renders _same_ data in ~15seconds on my PC, but I can use page then. 
As far as I understood from docs, XY chart with bullets in v4 equals to line graph with bullets (balloons) in v3.

**Expected Behavior**
As for my application, 40-60k of points is average qty for most of charts based on amcharts-v3. It renders not as fast as I would like to, but it is still usable. So, I expected that amcharts-v4 would be at least as fast (and won't lock browser)

**Technical Logs:**
Data for charts is in attach
[bullets-v3.zip](https://github.com/amcharts/amcharts4/files/2865522/bullets-v3.zip)
[bullets-v4.zip](https://github.com/amcharts/amcharts4/files/2865523/bullets-v4.zip)

**Comment by martynasma** [comment]
40K data points should not be issue for amCharts 4 with a single line series.

It should also not lock your page as it supports chunked data processing and chart build.

So I'm guess there's something with the chart setup, that needs optimizing.

If you could also share your chart config, I'd be willing to take a look.

**Comment by ivromas** [comment]
I suppose there is no additional chart config - everything that is used for chart rendering is in attached files.

That is how chart is created on client side:
`am4core.createFromConfig(data, chart_id + "_holder", am4charts.XYChart );`

**Comment by martynasma** [comment]
Sorry my bad, didn't notice there was whole of the code there.

First thing that jumps out at me is that you have bullets enabled.

While line series with 40K+ data points is still a continues line. Each bullet is an individual SVG element. With two series that's an extra 80K of elements to draw. And they won't event be useful because there's no way user can perceive them.

If bullets are removed, the chart starts behaving reasonably fast.

You can enable bullets only when user zooms in significantly, using `series.minBulletDistance`.

**Comment by HenriKoelewijn** [comment]
Although each point will not be individually perceivable with high volume bullet chart plots, high volume scatter plots (bullet plots) with very small bullets are still useful to give a good indication of the area's in which the chart that have more dots. This is a very useful visualization. I am wondering if the line draw performance cannot be replicated when drawing dots. I would love to have a high performance alternative for scatter plots, maybe using canvas.

**Comment by martynasma** [comment]
Canvas charts are on the drawing board, but no ETA yet.

I'm afraid there's nothing you can do right now to speed up charts wit 80K bullets :(

**Comment by HenriKoelewijn** [comment]
Good to hear it is at least on the roadmap. Please add a comment here when you have an estimate of the ETA.
