### ISSUE TITLE
Support keepSelection on ValueAxis

### ISSUE THREAD

**Issue by ShawnXU0208** [amcharts/amcharts4#973]
I have set keepSelection to true, but the value axis still zoom to max level (0-1) while updating data. 

<!doctype html>
<html lang="en">

<style>
#chartdiv {
  width: 100%;
  height: 500px;
}

</style>

<head>
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/maps.js"></script>
</head>

<body>
<div id="chartdiv"></div>
</body>

<script>
// Themes begin
//am4core.useTheme(am4themes_animated);
// Themes end

var newTemp = function(){
	let timestamp = new Date();
    let sensor1 = Math.random() * 10 + 20;
    let sensor2 = Math.random() * 10 + 25;
    let sensor3 = Math.random() * 20 + 80;
	let newTemp = {'time': timestamp, 'sensor1': sensor1, 'sensor2': sensor2, 'sensor3': sensor3};
	return newTemp;
};

// Create chart instance
var chart = am4core.create("chartdiv", am4charts.XYChart);
chart.dataDateFormat = "YYYY/MM/DD JJ:NN";
let data = [];
data.push(newTemp());
chart.data = data;

// Create axes
var timeAxis = chart.xAxes.push(new am4charts.DateAxis());
timeAxis.title.text = "time";
timeAxis.baseInterval = {timeUnit:"second", count: 1};
timeAxis.tooltipDateFormat = "HH:mm, d MMMM";
//dateAxis.renderer.grid.template.location = 0;
//dateAxis.renderer.minGridDistance = 30;

var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.title.text = "temps";
valueAxis.keepSelection = true;

// Add  scrollbars
chart.scrollbarX = new am4charts.XYChartScrollbar();
chart.scrollbarY = new am4charts.XYChartScrollbar();
chart.scrollbarY.parent = chart.leftAxesContainer;

// Create series
var series1 = chart.series.push(new am4charts.LineSeries());
series1.dataFields.valueY = "sensor1";
series1.dataFields.dateX = "time";
series1.yAxis = valueAxis;
series1.name = "product temps";
series1.tooltipText = "{name}\n[bold font-size: 20]{valueY}.c[/]";
//series1.fill = chart.colors.getIndex(0);
series1.strokeWidth = 2;
series1.stroke = 'blue';

var series2 = chart.series.push(new am4charts.LineSeries());
series2.dataFields.valueY = "sensor2";
series2.dataFields.dateX = "time";
series2.yAxis = valueAxis;
series2.name = "air temps";
series2.tooltipText = "{name}\n[bold font-size: 20] {valueY}.c[/]";
//series2.fill = chart.colors.getIndex(0).lighten(0.5);
series2.strokeWidth = 2;
series2.stroke = 'yellow';

var series3 = chart.series.push(new am4charts.LineSeries());
series3.dataFields.valueY = "sensor3";
series3.dataFields.dateX = "time";
series3.name = "check temps";
series3.yAxis = valueAxis;
series3.tooltipText = "{name}\n[bold font-size: 20]{valueY}.c[/]";
series3.strokeWidth = 2;
series3.stroke = 'red';

// Add cursor
chart.cursor = new am4charts.XYCursor();

// Add legend
chart.legend = new am4charts.Legend();
chart.legend.position = "top";

setInterval(function(){
	let aNewTemp = newTemp();
    aNewTemp.time = Date.parse(aNewTemp.time);
    //console.log(aNewTemp);
/*
    if(chart.data.length > 20){
        chart.addData(newTemp, 1);
    }else{
        chart.addData(newTemp);
    }
*/
	
    chart.addData(aNewTemp);
}, 1000);

</script>

</html>

**Comment by martynasma** [comment]
First of all you have it set on your value axis, not on date axis.

Second, `keepSelection` does not work if your chart is fully zoomed out, like it is when it is loaded.

If you would zoom in the chart, then it would keep current selection across updates.

**Comment by ShawnXU0208** [comment]
@martynasma Thank you very much, if I want to keep zoom level on the value axis, what is the right way to do it in amchart?

**Comment by martynasma** [comment]
Well, technically, you can use `keepSelection` on ValueAxis just as well.

Are you saying it is not working?

**Comment by ShawnXU0208** [comment]
@martynasma yes, setting keepSelection to true in this case doesn't work.

**Comment by martynasma** [comment]
OK, so it turns out that `keepSelection` is not yet supported on `ValueAxis`, just on `DateAxis`. Sorry.

I'm going to keep this issue as a feature request, for when we turn to implementing it.

Not sure when that is going to happen, though.

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.
