### ISSUE TITLE
LineSeries gap in data bug(s)?

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#974]
Simple XYChart with a LineSeries, bullets, and x/y Date/Value axes.

With a gap in data:

```javascript
  {
    date: 1549934946000,
    value: 36.6063
  },
  // GAP IN DATA HERE
  {
    date: 1549935006000
  },
  {
    date: 1549935067000,
    value: 36.6084
  },
```

I get a stray line drawn straight to the gap (and a bullet incorrectly renders there, too):
![image](https://user-images.githubusercontent.com/2334143/52825745-f9bcd400-308b-11e9-8d26-4f0e91ccfe10.png)

Zooming in may fix the problem (depending on the zoom):
![image](https://user-images.githubusercontent.com/2334143/52825789-34267100-308c-11e9-8a5d-c558a7f47a02.png)

Also, not sure if this is part of the same or separate issue, if the window is not wide enough (<= 954px), the bullets don't even render at all at the onset (in both Chrome/FF pc):
![image](https://user-images.githubusercontent.com/2334143/52825844-60da8880-308c-11e9-8cbf-be2856ed00a6.png)

Demo:
https://codepen.io/team/amcharts/pen/5723f55f70a1547b863997235ad7cb6c

**Comment by martynasma** [comment]
Regarding bullets:

```
series.minBulletDistance = 15;
```

This makes bullets disappear if they are become bunched up closer than 15px.

That other thing is caused by data points coming in random order. Data points must be ordered in an asecnding order.

```
chart.data.sort(function(a, b) {
  if (a.date == b.date) {
    return 0;
  }
  else if (a.date > b.date) {
    return 1;
  }
  else {
    return -1;
  }
})
```

This fixes "stray" lines ;)

**Comment by maurycyg** [comment]
Speaking of the missing gap, is there a way to render missing data points as 0? so instead of drawing a line between 2 points to draw 0 as it can be misleading e.g. https://codepen.io/maurycyg/pen/RveMLo

**Comment by martynasma** [comment]
@notacouch I disagree. Showing missing data as zero value is misleading. Zero is a legit number. It's different than "absence of data".

Jumping over a missing data point or cutting the line there is much more correct from dataviz standpoint.

You can set `connect = false` on your data to break the line.

That said, you're free to add zero values on missing data points directly in your data.

Hope that sounds reasonable.

**Comment by martynasma** [comment]
Sorry, that last comment was meant for @maurycyg

**Comment by notacouch** [comment]
Yep, the sorted data fixed it:
https://codepen.io/team/amcharts/pen/29889a5b7d01911be061bd6d23ce4f75

> This makes bullets disappear if they are become bunched up closer than 15px.

All of the bullets? it wouldn't alternate bullets?

**Comment by martynasma** [comment]
> All of the bullets? it wouldn't alternate bullets?

Yes. All of them. Bulletocide :P

**Comment by notacouch** [comment]
> Bulletocide :P

Is that in our docs? Not the behavior, the term. How can a term like that go undocumented?!

**Comment by martynasma** [comment]
Just waiting final approval from Webster's... any minute now.
