### ISSUE TITLE
Gap between date axis and value axis

### ISSUE THREAD

**Issue by mehmetnyarar** [amcharts/amcharts4#978]
Hi,

I'd like some gap between the last data point in a line series and the value axis while date axis' grid lines should extend to the value axis.

I tried setting `dateAxis.paddingRight = 50` and `dateAxis.percentWidth = 90` but when I do, the value I get from the `XYCursor` is wrong.

I'd appreciate if you can kindly show me the way to do it.

```
--------------------------------------------------------------------
|                                             |       |            |
|------------------------- Last data point -> * Space | Value axis |
|                                             |       |            |
|                                             |       |            |
|                                             |       |            |
--------------------------------------------------------------------
```

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Controlling_axis_and_cell_lengths

**Comment by mehmetnyarar** [comment]
Hi @martynasma,

Thanks for replying. The article didn't help much.

You can check the edit I made [here](https://codepen.io/anon/pen/dagwdZ?editors=0010)

and what I'd like to achieve [here](https://ibb.co/gVfZ7Pp)

BR

**Comment by martynasma** [comment]
Try adding bug-number `endLocation`:

```
dateAxis.endLocation = 20;
```

Either that, or you can set `max` on your date axis to a future date:

```
// adds a month to the last date
dateAxis.max = chart.data[chart.data.length -1].date.getTime() + 2592000000;
```

**Comment by mehmetnyarar** [comment]
Using `.endLocation` didn't work for different time intervals but setting to a future date seems working well.

Thanks.
