### ISSUE TITLE
Date axis labels not fitting on screen

### ISSUE THREAD

**Issue by promitanan** [amcharts/amcharts4#981]
The 'Jan 2019' text value is always cut off, no matter the dimensions of the chart. I fixed it by wrapping the label text, however I think this may be a bug.

![image](https://user-images.githubusercontent.com/18385581/52892895-d0637d00-314b-11e9-8086-c2bf348adf19.png)

**Comment by martynasma** [comment]
This can be fixed easily by adding some right padding to the chart:

```
chart.paddingRight = 30;
```
