### ISSUE TITLE
Zoom on dateaxis jumps in zoom level

### ISSUE THREAD

**Issue by dorsharon** [amcharts/amcharts4#982]
I have an XYChart with DateAxis and CategoryAxis,
my mouse wheel's behavior is zoomX (dateaxis)
whenever I zoom in further than minutes the zoom level spikes way too far.

Can I slow down the zooming factor?
I tried placing `maxZoomFactor` but it doesn't seem to work...

**Comment by RobbiesCode** [comment]
Hi,

You can use `minZoomCount` which restricts zooming beyond certain number of base interval.

```
chart.mouseWheelBehavior = "zoomX";
dateAxis.minZoomCount = 10;
```

Docs:
https://www.amcharts.com/docs/v4/reference/dateaxis/#minZoomCount_property
https://www.amcharts.com/docs/v4/reference/dateaxis/#maxZoomFactor_property

Codepen demo: https://codepen.io/team/amcharts/pen/66c62670e319b59a00f474cea7d2478a?editors=0010.

Hope this helps!

**Comment by dorsharon** [comment]
Same issue happens in your codepen.
Once you max zoomed, every mouse wheel scroll will make the view "Jump" to far location in the chart.
How do I disable this behaviour?
How do I make sure once it's max zoomed, it stays in that location?

**Comment by wotway84** [comment]
Hi, i am having the same problem. Once i max zoom, the chart starts panning. Did you come up with a way to solve this?
