### ISSUE TITLE
Parsing string date in date based chart

### ISSUE THREAD

**Issue by michaelwright112** [amcharts/amcharts4#984]
Looks like there is an issue with parsing string dates. It is occurring in one of your online demos: https://www.amcharts.com/demos/date-based-data/

I also see a similar issue in my app (amCharts version: 4.1.8)

**Comment by martynasma** [comment]
Thanks for the heads up.

That demo was missing format for input dates:

```
chart.dateFormatter.inputDateFormat = "yyyy-MM-dd";
```

Updated the demo as well.

Let me know if you are still having issues after adding this line.

**Comment by michaelwright112** [comment]
Fixed with inputDateFormat.

Thank you.
