### ISSUE TITLE
Is it also possible to change the background color of the tooltip?

### ISSUE THREAD

**Issue by sschrijver** [amcharts/amcharts4#987]
Is it possible to change the background color of a tooltip?
Already tried `series.tooltip.background.fill = am4core.color('#000')` and `series.tooltip.background.color = am4core.color('#000')`, unfortunately without success..

_Originally posted by @sschrijver in https://github.com/amcharts/amcharts4/issues/371#issuecomment-465024938_

**Comment by martynasma** [comment]
https://www.amcharts.com/docs/v4/tutorials/overriding-series-tooltip-fill-color/

**Comment by sschrijver** [comment]
Thanks, this is working fine!
