### ISSUE TITLE
columns tooltipText ghost text

### ISSUE THREAD

**Issue by bmampaey** [amcharts/amcharts4#989]
Sorry if the following description is not clear, but the problem is difficult to describe, maybe just jump to the example.

_Description_: If there is some data place holder, e.g. "{info}" in the columns tooltipText preceded **directly** by a newline (\n), and that the value for info is empty or not defined for some data point, the info from the previous tooltip with a non empty info value will remain. 

_Example_: here is a simple codepen of a column series to demonstrate the issue https://codepen.io/Benjamin-Mampaey/pen/WPPLdz

The info field of the data is defined for the red column to "I belong to red", empty for the blue column, and not defined for the green. The columns tooltipText is "Category: {categoryX}\n{info}"

If you hover first on the red column, then any other column, there is a lingering "I belong to red" tspan.
The problem does not appear if there is any char between the "\n" and the "{info}", for example adding a simple space after the "\n" ("Category: {categoryX}\n {info}") works as expected.

**Comment by develar** [comment]
Interesting, that I cannot reproduce this bug using your example, but I encountered exactly this bug in my project too.

Once tooltip was shown for item where there are 4 lines of text, tooltip for item where there are only 3 lines of text, will show the 4 line as ghost  from previous item.

To be sure that developers will have easy to reproduce sample, I attached my project too: 
[sample.zip](https://github.com/amcharts/amcharts4/files/2896911/sample.zip)

Video: 
[Untitled.mov.zip](https://github.com/amcharts/amcharts4/files/2896922/Untitled.mov.zip)

**Comment by develar** [comment]
Workaround — use `tooltipText` adapter to compute `tooltipText` template according to your data:

```ts
series.columns.template.adapter.add("tooltipText", (value, target, _key) => {
      const dataItem = target.dataItem
      const index = dataItem == null ? -1 : dataItem.index
      const data = this.chart.data
      const item = index >= 0 && index < data.length ? data[index] as TimeLineItem : null
      if (item == null) {
        return value
      }
      return item.description == null || item.description.length === 0 ? "{name}: {duration}\nlevel: {level}\nrange: {start}-{end}" : "{name}: {duration}\nlevel: {level}\nrange: {start}-{end}\n{description}"
    })
```

In this example — if `description` not present in data item, return `tooltipText` without it.

**Comment by bmampaey** [comment]
Or simpler, you can  just put a space between the "\n" and the "{description}" part
