### ISSUE TITLE
Show tooltip only hover particular circle

### ISSUE THREAD

**Issue by amit648** [amcharts/amcharts4#990]
Hello, 

When mouse pointer in the chart so tooltip show with value but I will show tooltip only circle's hover, so please give some instruction. 

Note: Only one circle hover not all circle hover.
Please check [https://i.imgur.com/35iR6U8.png](https://i.imgur.com/35iR6U8.png)

Here, my demo, 
[https://codepen.io/bhalani-amit/pen/PVVgbW](https://codepen.io/bhalani-amit/pen/PVVgbW)

Thanks

**Comment by notacouch** [comment]
Hello,

If you only want to show the tooltip on a specific series, you can specify `tooltipText` for that series alone. E.g.

```javascript
    // Set tooltip on desired series
    if (series.name === "Operator 2") {
      series1.tooltipText = "${valueY}";
    }
```

Screenshot:
![image](https://user-images.githubusercontent.com/2334143/53052923-fc457200-346d-11e9-8ee5-ac9362168217.png)

Demo:
https://codepen.io/team/amcharts/pen/fc1cd842839de2edcd9b5b6c30211952

**Comment by amit648** [comment]
Thanks for your reply,,

But one more thing this is only one series, I want to apply like this all series. ( Particular series-wise hover )

Thanks.

**Comment by bmampaey** [comment]
Try setting the tooltipText on the bullet and not on the series:
```
var circleBullet = series1.bullets.push(new am4charts.CircleBullet());
circleBullet.tooltipText = "${valueY}";
series1.cursorTooltipEnabled = false;
```
You codepen with the suggested modification:
https://codepen.io/Benjamin-Mampaey/pen/yZWNvZ

**Comment by amit648** [comment]
Yes, @bmampaey 

This one is working fine.

Thanks for giving me a solution.

**Comment by enggomarpu** [comment]
@amit648  do you know how to make tooltip hover on button click in amchart map in react. please explain with an example?
