### ISSUE TITLE
Retain geoPoint when updating series on maps

### ISSUE THREAD

**Issue by grasmachien** [amcharts/amcharts4#992]
How would I retain the geoPoint on the map when updating the map? 
The zoom level seems to stay the same but the location always defaults to the center of the map.

I can get the zoomGeoPoint by calling => this.map.zoomGeoPoint. 
How do I set it after updating the map. 
Or even better. 
How do I disable the automatic centering?

V3 of amcharts had an example explaining this but for V4 it seems this does not exist anymore.

Thanks in advance

**Comment by martynasma** [comment]
What do you mean by "updating the map"?

**Comment by grasmachien** [comment]
Users are able to filter locations on the map.
This means the map will have to be updated with new data.
To achieve this I dispose of the previous series and render them again with the new data.
