### ISSUE TITLE
Multiple valueAxis number format

### ISSUE THREAD

**Issue by CarlosHdez** [amcharts/amcharts4#993]
I'm trying to create a chart with two value axis but each one need to have a separate numberFormat but when I create the chart, all value axis take the formatter of the last axis configured.
As an example, I took the `Multiple Value axes` [demo](https://www.amcharts.com/demos/multiple-value-axes/) and added an extra param where I set the formatter, yet only the last one is used in all formats 
![image](https://user-images.githubusercontent.com/5401623/53032776-229aeb80-3435-11e9-8d76-7d988da4dfd2.png)

**Comment by RobbiesCode** [comment]
Hi,

How are you applying the number formatter? If you apply the formatter on the `valueAxis` (not on the chart itself) it should work:

```
  valueAxis.numberFormatter = new am4core.NumberFormatter();
  valueAxis.numberFormatter.numberFormat = numberFormat; 
```

I have updated the Codepen demo with this `numberFormat` parameter: https://codepen.io/team/amcharts/pen/d2b99b63bfbf900561437ee15b31e855?editors=1010. You'll see that every axis has its own formatting.

Hope this helps!

**Comment by CarlosHdez** [comment]
That's weird, I'm sure I applied them to the value axis, but also I'm seeing this using a JSON based chart this is the configuration I'm using
```{
   "xAxes":[...],
   "yAxes":[
      {
         "type":"ValueAxis",
         ...,
         "numberFormatter":{
            "numberFormat":"#,###,###"
         },
         "min":0
      },
      {
         "type":"ValueAxis",
         ...,
         "numberFormatter":{
            "numberFormat":"#.##%"
         }
      }
   ],
   "series":[
      {
         ....,
         "type":"ColumnSeries",
         "dataFields":{...}
      },
      {
         ...,
         "type":"LineSeries",
         "dataFields":{...}
      }
   ]
   ... 
}
```
And yet this is what I'm seeing
![screen shot 2019-02-20 at 9 10 19 am](https://user-images.githubusercontent.com/5401623/53101467-6baf7600-34ef-11e9-9049-686c720f3156.png)

Thanks for the help

**Comment by martynasma** [comment]
`numberFormatter` is not created for each separate element. It;s rather inherited.

This means that you are setting `numberFormat` on the same chart-wide formatter.

To create a new instance of NumberFormatter try this:

```
   "xAxes":[...],
   "yAxes":[
      {
         "type":"ValueAxis",
         ...,
         "numberFormatter":{
            "type": "NumberFormatter",
            "numberFormat":"#,###,###"
         },
         "min":0
      },
      {
         "type":"ValueAxis",
         ...,
         "numberFormatter":{
            "type": "NumberFormatter",
            "numberFormat":"#.##%"
         }
      }
   ],
   "series":[
      {
         ....,
         "type":"ColumnSeries",
         "dataFields":{...}
      },
      {
         ...,
         "type":"LineSeries",
         "dataFields":{...}
      }
   ]
   ... 
}
```

**Comment by CarlosHdez** [comment]
That makes sense, I tried and it worked like a charm thank you so much
