### ISSUE TITLE
Noticeable lag when zooming in (from 4.1.2 onward)

### ISSUE THREAD

**Issue by puddings** [amcharts/amcharts4#996]
Hi,

I noticed that there is a very noticeable lag when zooming in a line chart with about 3000+ data points.

This issue happened right after 4.1.2 up to the latest version (4.1.1 is still fine).

**Comment by martynasma** [comment]
Is this happening with latest version? (4.1.8)
Can you post your chart config/data?

**Comment by puddings** [comment]
Yes, the issue is still happening on the latest version.

I have attached the chart config and data. Hope they help with troubleshooting the issue.

[chart_config_data.zip](https://github.com/amcharts/amcharts4/files/2887221/chart_config_data.zip)

**Comment by martynasma** [comment]
I did try you chart. Ir zooms nearly instantly for me.

Here's my test case:
https://codepen.io/team/amcharts/pen/551dcdda3d6d7e2e4d5b1d3dd14c8906?editors=0010

Am I missing something?

**Comment by puddings** [comment]
Thanks for taking the time to configure the chart based on my config/data.

I have checked the codepen and it seems like the chart on the codepen did not have zooming animation enabled. I'm not using the animated theme on my chart, but it has a smooth zooming in animation usually, up to version 4.1.1. I can't seem to remove the zooming animation in order to troubleshoot the issue.

**Comment by martynasma** [comment]
Can you create a CodePen based on mine that would have zooming animation enabled like you do in your actual app?

**Comment by puddings** [comment]
I have recreated the CodePen with zoom animation enabled:

[https://codepen.io/puddings/pen/moJVWW](url)

**Comment by martynasma** [comment]
3K+ data points with animations does not sound like a good idea :)

I suggest you disable animations, or at least zoom on X axis:

```
categoryAxis.rangeChangeDuration = 0;
```

Another thing that does not go well with a lot of data points is `CategoryAxis`. It's meant to display manageable amount of categories. Since categories are unique strings, and it's not possible to aggregate/interpolate or otherwise maniplate categories, it's much slower than `DateAxis` or a `ValueAxis`.

Since you have date/time in your data, I suggest you use proper axis type for it: `DateAxis`. I promise, the increase in performance will be dramatic.

**Comment by puddings** [comment]
Thanks for the suggestion. I will try to disable animations for now.

As for `CategoryAxis`, the reason I used it instead of a `DateAxis` is due to the non-linear date/time of my data, as it will produce gaps in between data points.

For the freezing of the animations, it did not happen on the previous versions (4.1.1 and under), so I'm wondering if it is a bug that will be fixed in future versions or are the changes in 4.1.2 that's causing this issue intended and required in order to improve/fix other major bugs?

**Comment by martynasma** [comment]
We have a plan on improving performance of the CategoryAxis with many categories. Not sure when/if that will happen, though.

**Comment by puddings** [comment]
CategoryAxis performance issue is fixed in 4.3.12.

Thank you.
