### ISSUE TITLE
positionToDate() in event "zoomended"

### ISSUE THREAD

**Issue by ericrange** [amcharts/amcharts4#998]
You will get nearly random distributed end and start dates if you are zooming into timeseries data.
I just wanted to have the end and start date of the zoomed data.
```
chart.cursor.events.on('zoomended', (ev) => {
      const range = ev.target.xRange;
      const axis = ev.target.chart.xAxes.getIndex(0);

      const start = axis.positionToDate(axis.toAxisPosition(ev.target.xRange.start));
      const end = axis.positionToDate(axis.toAxisPosition(ev.target.xRange.end));

      this.zoomChanged({
        start,
        end
      });
    });
```
i needed to solve this problem by:
```
    chart.cursor.behavior = "selectX";
    chart.cursor.events.on('selectended', (ev) => {
      const axis = ev.target.chart.xAxes.getIndex(0);

      const start = axis.positionToDate(axis.toAxisPosition(ev.target.xRange.start));
      const end = axis.positionToDate(axis.toAxisPosition(ev.target.xRange.end));

      this.dateAxis.zoomToDates(start, end);

      this.zoomChanged({
        start,
        end
      });
    });
```
this example works.

**Comment by ericrange** [comment]
i guess this is not supposed to work like this?

**Comment by martynasma** [comment]
Can you explain what you mean by "random distributed"?

When zooming DateAxis you will get precise point of the cursor where you started and ended zooming. It may not be directly on a precise date because maybe you started zooming mid-day.

Or are you saying that it does not function like that?
